### ISSUE TITLE
Framework:  something wrong in PR testing pipeline

### ISSUE THREAD

**Issue by jhux2** [trilinos/Trilinos#10006]
## Bug Report
@trilinos/framework @jwillenbring @e10harvey @

### Description

There's appears to be something wrong in the PR testing pipeline.  See https://github.com/trilinos/Trilinos/pull/9998.  All builds/tests show passing, but cdash still reports that the PR testing failed.

**Comment by jhux2** [comment]
Reported in ticket TRILINOSHD-58.

**Comment by jwillenbring** [comment]
The debug and clang 10 builds failed most recently. In the first test run, the debug build failed. These builds are not showing up on CDash for some reason, and that could be the failure that is occurring. I know we have had some issues with this recently. I will socialize this with the Framework team.

**Comment by jwillenbring** [comment]
So looking at the logs for one of the debug builds, there was a merge error applying the change set to the develop branch. I reset the reference date for testing so we should start with a clean repo next time (however, the tests are running and that will not apply until the next attempt). If the issue persists, please make sure the PR can be cleanly merged onto develop in its current state.

**Comment by jhux2** [comment]
@mperego

**Comment by jhux2** [comment]
closing as fixed for the PR in question.
