### ISSUE TITLE
MueLu: Utilities_kokkos Cuthill McKee failing w/o UVM

### ISSUE THREAD

**Issue by csiefer2** [trilinos/Trilinos#10012]
These two tests in MueLu are failing on our non-UVM nightly test builds:

The following tests FAILED:
    66. Utilities_kokkos_double_int_longlong_Kokkos_Compat_KokkosCudaWrapperNode_CuthillMcKee_UnitTest ... 
    81. Utilities_kokkos_std_complex0double0_int_longlong_Kokkos_Compat_KokkosCudaWrapperNode_CuthillMcKee_UnitTest ... 

[Test link here](https://testing.sandia.gov/cdash/test/108095534)

**Comment by jhux2** [comment]
This looks to be a duplicate of #9988.

**Comment by cgcgcg** [comment]
Fixed by #10027.
