### ISSUE TITLE
Kokkos: atomic_add with Kokkos::Serial

### ISSUE THREAD

**Issue by jewatkins** [trilinos/Trilinos#10015]
## Bug Report
@trilinos/kokkos

### Description
I noticed a performance regression when using `Kokkos::atomic_add` on a `Kokkos::Serial` build after the 3.5 promotion (somewhere around 20% slowdown, see https://github.com/sandialabs/Albany/issues/767). I'm not sure if this is a bug since this is not its intended use but I thought it's worth reporting just in case others in Trilinos, kokkos-kernels are using atomic_add in this way. In my case, I was able to recover most of the performance by removing its use from the Kokkos::Serial build.

### Steps to Reproduce
I can provide the steps to reproduce if anyone is interested but I would imagine this could be seen with any atomic_add usage in a Kokkos::Serial build before/after the kokkos promotion. I saw it in a larger case w/ intel and a smaller case w/ clang. I can also provide data if needed.

I can also escalate this to a kokkos issue if this is indeed a bug. Otherwise, I can close this.

**Comment by ndellingwood** [comment]
@jewatkins I reposted your issue to kokkos' github issues kokkos/kokkos#4611

**Comment by crtrott** [comment]
Yeah the switch to the desul atomics disabled that optimization you can still get it back by disabling desul atomics in your serial builds.

**Comment by jewatkins** [comment]
This issue was fixed a while ago, thanks all.
