### ISSUE TITLE
Get standard Trilinos CI build working with SEMS env with CMake 3.3+ on RHEL 7

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#1001]
The SEMS env for the GCC 4.7.2 stack used by the standard Trilinos CI build (#482) fails with CMake 3.3+ on RHEL 7 machines (see #945).  This story is to find a way to fix things so that this env works out of the box on RHEL 7 without hacks.

**Comment by bartlettroscoe** [comment]
If someone can give me an account on a Sandia RHEL 7 machine with the SEMS Env mounted, then I will take a look at this build and try to get it working.

@tawiesn, can I can a temp account on your RHEL 7 machine to try to reproduce the failures and try to find a way to fix (and perhaps get help from the SEMS team to resolve the underlying issues)?

**Comment by jwillenbring** [comment]
Is this still an issue?

**Comment by bartlettroscoe** [comment]
According to @tawiesn, this issue will be solved automatically once we move to GCC 4.9.3 (see #1002).  Therefore, since @tawiesn has a workaround for now, I think we can close this and just want to pull the trigger for #1002 (once Sierra stops relying on Intel 14 / GCC 4.7.2 builds).
 
Closing as wontfix since this will be solved by #1002.

**Comment by bartlettroscoe** [comment]
I removed from the "Trilinos Framework" GitHub project since we closed as wontfix.
