### ISSUE TITLE
ATDM Trilinos 'sems-rhel7' configuration broken on new CEE hpwsXYZ and cee-buildXYZ machines

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#10022]
@trilinos/framework 

### Description

It seems the sems modules are broken on the new CEE 'hpwsXYZ' **and** 'cee-buildXYZ' machines.  And the Trilinos GenConfig scripts don't detect they are broken (see  [below](https://github.com/trilinos/Trilinos/issues/10022#issuecomment-1258821659)).

### Original Description

It appears that the SEMS RHEL7 modules or perhaps just the ATDM Trilinos 'sems-rhel7' configuration is broken on the new CEE HPWS machines.  It seems the builds complete but a lot of tests fail with errors like:

```
symbol lookup error: /projects/sems/install/rhel7-x86_64/sems/compiler/intel/18.0.5/openmpi/1.10.1/lib/libmca_common_verbs.so.7: undefined symbol: ompi_common_verbs_usnic_register_fake_drivers
```

all showing `undefined symbol: ompi_common_verbs_usnic_register_fake_drivers`.

To demonstrate this, I used a recent version of Trilinos 'develop' from ATDM Trilinos testing day 2021-12-21 55091be  as shown by:

```
$ git log-short --name-status --graph 2be5702

*   2be5702 "Merge remote-tracking branch 'origin/develop' into atdm-nightly"
|\  Author: trilinos-autotester <trilinos@sandia.gov>
| | Date:   Fri Dec 10 21:05:07 2021 -0700 (4 days ago)
| |     
| *   55091be "Merge Pull Request #10005 from trilinos/Trilinos/csiefer-827cd90"
| |\  Author: trilinos-autotester <trilinos@sandia.gov>
| | | Date:   Fri Dec 10 13:04:17 2021 -0700 (4 days ago)
```

that was pretty clean as shown in [this query](https://testing.sandia.gov/cdash/index.php?project=Trilinos&date=2021-12-12&filtercount=2&showfilters=1&filtercombine=and&field1=groupname&compare1=62&value1=Experimental&field2=buildname&compare2=65&value2=Trilinos-atdm-).

I demonstrated the problem by running, on my machine 'hpws055', I ran all of the supported ATDM Trilinos 'sems-rhel7' builds for just the Teuchos test suite as:

```
$ env Trilinos_PACKAGES=Teuchos ./ctest-s-local-test-driver.sh all

***
*** ./ctest-s-local-test-driver.sh
***

ATDM_TRILINOS_DIR = '/fgs/rabartl/Trilinos.base2/Trilinos'

Load some env to get python, cmake, etc ...

Hostname 'hpws055.sandia.gov' matches known ATDM host 'hpws055.sandia.gov' and system 'sems-rhel7'
Setting compiler and build options for build-name 'default'
Using SEMS RHEL7 compiler stack GNU-7.2.0 to build DEBUG code with Kokkos node type SERIAL

Running builds:
    sems-rhel7-clang-7.0.1-openmp-shared-release-debug
    sems-rhel7-cuda-10.1-Volta70-complex-shared-release-debug
    sems-rhel7-gnu-7.2.0-openmp-complex-shared-release-debug
    sems-rhel7-intel-18.0.5-openmp-complex-shared-release-debug
    sems-rhel7-intel-18.0.5-openmp-shared-debug
    sems-rhel7-intel-18.0.5-openmp-shared-release-debug
```

<details>

<summary><b>Detailed output from ctest-s-local-test-drivers.sh</b> (click to expand)</summary>

.

```
Tue Dec 14 09:40:26 MST 2021

Running Jenkins driver Trilinos-atdm-sems-rhel7-clang-7.0.1-openmp-shared-release-debug.sh ...

    Creating directory: Trilinos-atdm-sems-rhel7-clang-7.0.1-openmp-shared-release-debug

    Creating directory: SRC_AND_BUILD

    See log file Trilinos-atdm-sems-rhel7-clang-7.0.1-openmp-shared-release-debug/smart-jenkins-driver.out

real    2m27.954s
user    18m49.847s
sys     0m54.898s

14% tests passed, 126 tests failed out of 146

Tue Dec 14 09:42:54 MST 2021

Running Jenkins driver Trilinos-atdm-sems-rhel7-cuda-10.1-Volta70-complex-shared-release-debug.sh ...

    Creating directory: Trilinos-atdm-sems-rhel7-cuda-10.1-Volta70-complex-shared-release-debug

    Creating directory: SRC_AND_BUILD

    See log file Trilinos-atdm-sems-rhel7-cuda-10.1-Volta70-complex-shared-release-debug/smart-jenkins-driver.out

real    4m8.488s
user    28m55.797s
sys     3m33.693s

14% tests passed, 126 tests failed out of 146

Tue Dec 14 09:47:03 MST 2021

Running Jenkins driver Trilinos-atdm-sems-rhel7-gnu-7.2.0-openmp-complex-shared-release-debug.sh ...

    Creating directory: Trilinos-atdm-sems-rhel7-gnu-7.2.0-openmp-complex-shared-release-debug

    Creating directory: SRC_AND_BUILD

    See log file Trilinos-atdm-sems-rhel7-gnu-7.2.0-openmp-complex-shared-release-debug/smart-jenkins-driver.out

real    2m1.078s
user    16m13.491s
sys     1m11.505s

14% tests passed, 126 tests failed out of 146

Tue Dec 14 09:49:04 MST 2021

Running Jenkins driver Trilinos-atdm-sems-rhel7-intel-18.0.5-openmp-complex-shared-release-debug.sh ...

    Creating directory: Trilinos-atdm-sems-rhel7-intel-18.0.5-openmp-complex-shared-release-debug

    Creating directory: SRC_AND_BUILD

    See log file Trilinos-atdm-sems-rhel7-intel-18.0.5-openmp-complex-shared-release-debug/smart-jenkins-driver.out

real    6m24.248s
user    65m14.843s
sys     2m50.406s

14% tests passed, 126 tests failed out of 146

Tue Dec 14 09:55:28 MST 2021

Running Jenkins driver Trilinos-atdm-sems-rhel7-intel-18.0.5-openmp-shared-debug.sh ...

    Creating directory: Trilinos-atdm-sems-rhel7-intel-18.0.5-openmp-shared-debug

    Creating directory: SRC_AND_BUILD

    See log file Trilinos-atdm-sems-rhel7-intel-18.0.5-openmp-shared-debug/smart-jenkins-driver.out

real    1m55.680s
user    14m50.879s
sys     2m12.194s

14% tests passed, 126 tests failed out of 146

Tue Dec 14 09:57:24 MST 2021

Running Jenkins driver Trilinos-atdm-sems-rhel7-intel-18.0.5-openmp-shared-release-debug.sh ...

    Creating directory: Trilinos-atdm-sems-rhel7-intel-18.0.5-openmp-shared-release-debug

    Creating directory: SRC_AND_BUILD

    See log file Trilinos-atdm-sems-rhel7-intel-18.0.5-openmp-shared-release-debug/smart-jenkins-driver.out

real    6m17.964s
user    68m52.389s
sys     3m2.706s

14% tests passed, 126 tests failed out of 146

Tue Dec 14 10:03:42 MST 2021

Done running all of the builds!
```

</details>

which posted to CDash as shown here:

* https://testing.sandia.gov/cdash/index.php?project=Trilinos&date=2021-12-14&filtercount=2&showfilters=1&filtercombine=and&field1=site&compare1=61&value1=hpws055.sandia.gov&field2=buildname&compare2=65&value2=Trilinos-atdm-sems-rhel7

There are 126 failing tests for each build, 756 failing tests across all of these builds as shown here:

* https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&date=2021-12-14&filtercount=3&showfilters=1&filtercombine=and&field1=site&compare1=61&value1=hpws055.sandia.gov&field2=buildname&compare2=65&value2=Trilinos-atdm-sems-rhel7&field3=status&compare3=61&value3=failed

All of these failing tests show the error `undefined symbol: ompi_common_verbs_usnic_register_fake_drivers` as shown in this query:

* https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&date=2021-12-14&filtercount=4&showfilters=1&filtercombine=and&field1=site&compare1=61&value1=hpws055.sandia.gov&field2=buildname&compare2=65&value2=Trilinos-atdm-sems-rhel7&field3=status&compare3=61&value3=failed&field4=testoutput&compare4=95&value4=undefined%20symbol%3A%20ompi_common_verbs_usnic_register_fake_drivers
 
Internal issues:

* [TRILINOSHD-59](https://sems-atlassian-son.sandia.gov/jira/servicedesk/customer/portal/7/TRILINOSHD-59?sda_source=notification-email)
* [TRILINOSHD-14](https://sems-atlassian-srn.sandia.gov/servicedesk/customer/portal/10/TRILINOSHD-14?sda_source=notification-email)

**Comment by bartlettroscoe** [comment]
@trilinos/framework, my understanding is that CEE is pushing everyone to move to these HPWS machines and is eliminating the RWS and EWS machines.  I know the current ATDM Trilinos 'sems-rhel7' builds are running on ascicgpu machines but most Trilinos developers can't get access to those machines.  (For example, I don't think I currently have access to any ascigpu machines.)

I need to have a working set of Trilinos builds in order to test TriBITS work associated with TriBITSPub/TriBITS#367.  Otherwise, I just have to do my best to locally test and cross fingers and merge to Trilinos 'develop'.  But I would rather run a more comprehensive set of builds before merging future TriBITS changes.

**Comment by e10harvey** [comment]
@bartlettroscoe: I don't see this build error showing up in the [PrimaryATDM](https://testing.sandia.gov/cdash/index.php?project=Trilinos&begin=2021-12-08&end=2021-12-14&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=63&value1=sems-rhel7&field2=groupname&compare2=63&value2=PrimaryATDM) or [SecondaryATDM](https://testing.sandia.gov/cdash/index.php?project=Trilinos&begin=2021-12-08&end=2021-12-14&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=63&value1=sems-rhel7&field2=groupname&compare2=63&value2=SecondaryATDM) builds. I will raise this github issue during our meeting tomorrow.

CC: @jwillenbring

**Comment by bartlettroscoe** [comment]
> I don't see this build error showing up in the PrimaryATDM or SecondaryATDM builds. I will raise this github issue during our meeting tomorrow.

@e10harvey, I suspect that is because the builds posting to CDash are running on ASCIGPU machines, not HPWS machines.  The latter are fairly new.  See my comment [above](https://github.com/trilinos/Trilinos/issues/10022#issuecomment-993844532).

**Comment by bartlettroscoe** [comment]
FYI: As a basis of comparison, I ran the exact same Teuchos 'sems-rhel7' builds with the exact same version of Trilinos on the CEE build machine 'cee-build015' and I got all passing builds and tests (except for 3 failing tests from the CUDA build because this machine does not have a GPU).  This shows the problem is with the SEMS modules and/or the ATDM Trilinos env and/or the HPWS machines themselves.

<details>

<summary><b>Details of Teuchos 'sems-rhel7' builds on 'cee-build015' and results on CDash</b> (click to expand)</summary>

.


Now to run the full set of supported builds for Teuchos on the machine 'cee-build015':

```
$ ssh cee-build015

$ cd /scratch/rabartl/Trilinos.base/BUILDS/ATDM/SEMS-RHEL7/CTEST_S/

$ ln -s /scratch/rabartl/Trilinos.base/Trilinos/cmake/std/atdm/ctest-s-local-test-driver.sh .

$ env Trilinos_PACKAGES=Teuchos ./ctest-s-local-test-driver.sh all

***
*** ./ctest-s-local-test-driver.sh
***

ATDM_TRILINOS_DIR = '/scratch/rabartl/Trilinos.base/Trilinos'

Load some env to get python, cmake, etc ...

Hostname 'cee-build015' matches known ATDM host 'cee-build015' and system 'sems-rhel7'
Setting compiler and build options for build-name 'default'
Using SEMS RHEL7 compiler stack GNU-7.2.0 to build DEBUG code with Kokkos node type SERIAL

Running builds:
    sems-rhel7-clang-7.0.1-openmp-shared-release-debug
    sems-rhel7-cuda-10.1-Volta70-complex-shared-release-debug
    sems-rhel7-gnu-7.2.0-openmp-complex-shared-release-debug
    sems-rhel7-intel-18.0.5-openmp-complex-shared-release-debug
    sems-rhel7-intel-18.0.5-openmp-shared-debug
    sems-rhel7-intel-18.0.5-openmp-shared-release-debug

Tue Dec 14 12:08:29 MST 2021

Running Jenkins driver Trilinos-atdm-sems-rhel7-clang-7.0.1-openmp-shared-release-debug.sh ...

    Creating directory: Trilinos-atdm-sems-rhel7-clang-7.0.1-openmp-shared-release-debug

    Creating directory: SRC_AND_BUILD

    See log file Trilinos-atdm-sems-rhel7-clang-7.0.1-openmp-shared-release-debug/smart-jenkins-driver.out

real    3m27.990s
user    32m20.235s
sys     3m51.218s

100% tests passed, 0 tests failed out of 146

Tue Dec 14 12:11:57 MST 2021

Running Jenkins driver Trilinos-atdm-sems-rhel7-cuda-10.1-Volta70-complex-shared-release-debug.sh ...

    Creating directory: Trilinos-atdm-sems-rhel7-cuda-10.1-Volta70-complex-shared-release-debug

    Creating directory: SRC_AND_BUILD

    See log file Trilinos-atdm-sems-rhel7-cuda-10.1-Volta70-complex-shared-release-debug/smart-jenkins-driver.out

real    6m15.396s
user    47m11.151s
sys     9m37.938s

98% tests passed, 3 tests failed out of 146

Tue Dec 14 12:18:13 MST 2021

Running Jenkins driver Trilinos-atdm-sems-rhel7-gnu-7.2.0-openmp-complex-shared-release-debug.sh ...

    Creating directory: Trilinos-atdm-sems-rhel7-gnu-7.2.0-openmp-complex-shared-release-debug

    Creating directory: SRC_AND_BUILD

    See log file Trilinos-atdm-sems-rhel7-gnu-7.2.0-openmp-complex-shared-release-debug/smart-jenkins-driver.out

real    2m56.085s
user    25m14.042s
sys     4m56.947s

100% tests passed, 0 tests failed out of 146

Tue Dec 14 12:21:09 MST 2021

Running Jenkins driver Trilinos-atdm-sems-rhel7-intel-18.0.5-openmp-complex-shared-release-debug.sh ...

    Creating directory: Trilinos-atdm-sems-rhel7-intel-18.0.5-openmp-complex-shared-release-debug

    Creating directory: SRC_AND_BUILD

    See log file Trilinos-atdm-sems-rhel7-intel-18.0.5-openmp-complex-shared-release-debug/smart-jenkins-driver.out

real    7m40.898s
user    89m47.930s
sys     8m25.468s

100% tests passed, 0 tests failed out of 146

Tue Dec 14 12:28:50 MST 2021

Running Jenkins driver Trilinos-atdm-sems-rhel7-intel-18.0.5-openmp-shared-debug.sh ...

    Creating directory: Trilinos-atdm-sems-rhel7-intel-18.0.5-openmp-shared-debug

    Creating directory: SRC_AND_BUILD

    See log file Trilinos-atdm-sems-rhel7-intel-18.0.5-openmp-shared-debug/smart-jenkins-driver.out

real    2m38.976s
user    20m0.146s
sys     6m37.105s

100% tests passed, 0 tests failed out of 146

Tue Dec 14 12:31:29 MST 2021

Running Jenkins driver Trilinos-atdm-sems-rhel7-intel-18.0.5-openmp-shared-release-debug.sh ...

    Creating directory: Trilinos-atdm-sems-rhel7-intel-18.0.5-openmp-shared-release-debug

    Creating directory: SRC_AND_BUILD

    See log file Trilinos-atdm-sems-rhel7-intel-18.0.5-openmp-shared-release-debug/smart-jenkins-driver.out

real    7m23.097s
user    89m8.752s
sys     8m36.234s

100% tests passed, 0 tests failed out of 146

Tue Dec 14 12:38:52 MST 2021

Done running all of the builds!
```

posted to:

* https://testing.sandia.gov/cdash/index.php?project=Trilinos&date=2021-12-14&filtercount=2&showfilters=1&filtercombine=and&field1=site&compare1=61&value1=cee-build015&field2=buildname&compare2=65&value2=Trilinos-atdm-sems-rhel7

with only 3 failing tests in the CUDA build:

* https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&date=2021-12-14&filtercount=3&showfilters=1&filtercombine=and&field1=site&compare1=61&value1=cee-build015&field2=buildname&compare2=65&value2=Trilinos-atdm-sems-rhel7&field3=status&compare3=61&value3=failed

and all 3 because this machine does not have a GPU and displays the error:

```
terminate called after throwing an instance of 'std::runtime_error'
  what():  cudaGetDeviceCount(&m_cudaDevCount) error( cudaErrorInsufficientDriver): CUDA driver version is insufficient for CUDA runtime version /scratch/rabartl/Trilinos.base/BUILDS/ATDM/SEMS-RHEL7/CTEST_S/Trilinos-atdm-sems-rhel7-cuda-10.1-Volta70-complex-shared-release-debug/SRC_AND_BUILD/Trilinos/packages/kokkos/core/src/Cuda/Kokkos_Cuda_Instance.cpp:253
```

as shown in this query:

* https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&date=2021-12-14&filtercount=4&showfilters=1&filtercombine=and&field1=site&compare1=61&value1=cee-build015&field2=buildname&compare2=65&value2=Trilinos-atdm-sems-rhel7&field3=status&compare3=61&value3=failed&field4=testoutput&compare4=95&value4=CUDA%20driver%20version%20is%20insufficient%20for%20CUDA%20runtime%20version

</details>

**Comment by bartlettroscoe** [comment]
FYI: The RHEL7 version is newer on the HPWS machine 'hpws055' than on the older CEE machine 'cee-build015'.  The details are given in [TRILINOSHD-59](https://sems-atlassian-son.sandia.gov/jira/servicedesk/customer/portal/7/TRILINOSHD-59).  It may just be that the SEMS modules are broken for the newer OS.  Hopefully the newer SEMS modules build with Spack will work okay.

**Comment by e10harvey** [comment]
@fryeguy52: Would you please look into the module issues on the HPWS machine?

**Comment by bartlettroscoe** [comment]
FYI: I got a rude reminder this is still broken as documented in https://github.com/trilinos/Trilinos/issues/10836#issuecomment-1216017031.

**Comment by bartlettroscoe** [comment]
And I also hit this as described in https://github.com/trilinos/Trilinos/issues/10823#issuecomment-1207070648.  I don't seem to be remembering that the SEMS modules are broken in the CEE High Performance Work Station (HPWS) machines :-(

**Comment by bartlettroscoe** [comment]
It seems this same problem is impacting the new 'ascic0xy' machines as well.  See #10999.

**Comment by bartlettroscoe** [comment]
Well shoot, this same error is occurring on the 'cee-build030' machine as well :-(

I am trying to run full Trilinos PR builds as part of testing a CMake upgrade as part of #10355 on the beefy machine 'cee-build030' and I can't successfully load a GenConfig env.

Specifically, for the env load scirpt `load-env.sh`:

```
export TRILINOS_DIR=/fgs/rabartl/Trilinos.base/Trilinos
source ${TRILINOS_DIR}/packages/framework/GenConfig/gen-config.sh \
--cmake-fragment GenConfigSettings.cmake \
rhel7_sems-clang-10.0.0-openmpi-1.10.1-serial_release-debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables \
--force -y \
"$@" \
${TRILINOS_DIR}
```

When I source it it produces:

```
$ source load-env.sh

Using system 'rhel7' based on matching hostname 'cee-build030'.
Overriding system to 'rhel7' based on specification in build name 'rhel7_sems-clang-10.0.0-openmpi-1.10.1-serial_release-debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables'.
Matched environment name 'sems-clang-10.0.0-openmpi-1.10.1-serial' in build name 'rhel7_sems-clang-10.0.0-openmpi-1.10.1-serial_release-debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables'.
Matched complete configuration 'rhel7_sems-clang-10.0.0-openmpi-1.10.1-serial_release-debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables'
  for build name 'rhel7_sems-clang-10.0.0-openmpi-1.10.1-serial_release-debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables'.
* CMake fragment file written to: /fgs/rabartl/Trilinos.base/BUILDS/PR/pr_builds/clang-10.0.0/GenConfigSettings.cmake

Using system 'rhel7' based on matching hostname 'cee-build030'.
Overriding system to 'rhel7' based on specification in build name 'rhel7_sems-clang-10.0.0-openmpi-1.10.1-serial_release-debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables'.
Matched environment name 'sems-clang-10.0.0-openmpi-1.10.1-serial' in build name 'rhel7_sems-clang-10.0.0-openmpi-1.10.1-serial_release-debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables'.
Environment 'rhel7_sems-clang-10.0.0-openmpi-1.10.1-serial' validated.
which: no mpicc in (/projects/sems/install/rhel7-x86_64/sems/compiler/clang/10.0.0/base/bin:/projects/sems/install/rhel7-x86_64/sems/compiler/gcc/5.3.0/base/bin:/ascldap/users/rabartl/bin:/usr/lib64/qt-3.3/bin:/ascldap/users/rabartl/perl5/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/puppetlabs/bin)
which: no mpicxx in (/projects/sems/install/rhel7-x86_64/sems/compiler/clang/10.0.0/base/bin:/projects/sems/install/rhel7-x86_64/sems/compiler/gcc/5.3.0/base/bin:/ascldap/users/rabartl/bin:/usr/lib64/qt-3.3/bin:/ascldap/users/rabartl/perl5/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/puppetlabs/bin)
which: no mpif90 in (/projects/sems/install/rhel7-x86_64/sems/compiler/clang/10.0.0/base/bin:/projects/sems/install/rhel7-x86_64/sems/compiler/gcc/5.3.0/base/bin:/ascldap/users/rabartl/bin:/usr/lib64/qt-3.3/bin:/ascldap/users/rabartl/perl5/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/puppetlabs/bin)



********************************************************************************
           E N V I R O N M E N T  L O A D E D  S U C E S S F U L L Y
********************************************************************************
...
```

And then when I try to configure and build Trilinos, the mpiexec command used by Trilinos produces errors like:

```
/fgs/rabartl/Trilinos.base/BUILDS/PR/pr_builds/clang-10.0.0/packages/teuchos/core/test/MemoryManagement/TeuchosCore_RCPNodeTracer_UnitTests.exe: symbol lookup error: /projects/sems/install/rhel7-x86_64/sems/compiler/clang/10.0.0/openmpi/1.10.1/lib/libmca_common_verbs.so.7: undefined symbol: ompi_common_verbs_usnic_register_fake_drivers
```

While this may be a problem with the SEMS modules, it seems that GenConfig can't figure out of it loaded the env correctly or not.

**Comment by bartlettroscoe** [comment]
See https://github.com/trilinos/Trilinos/issues/10999#issuecomment-1288163129
