### ISSUE TITLE
Upgrade standard Trilinos CI build env from GCC 4.7.2 to GCC 4.9.3

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#1002]
**Next Action Status:**

Transition to GCC 4.9.3 for CI build is complete.  Next: Watch post-push CI build for issues and close on Monday 5/18 ...

**Blocking:** #1167
**CC:** @trilinos/framework 

**Description:**

Now that an important internal Trilinos customer is moving from GCC 4.7.2 to 4.9.3, we should switch the [standard Trilinos CI build](https://github.com/trilinos/Trilinos/wiki/Policies-%7C-Safe-Checkin-Testing) to match.  We have been promised that we can make this switch the first of Feb. 2017.

**Tasks:**

1. Try out CI build for all of Trilinos with GCC 4.9.3 SEMS module on branch gcc-4.9.3-ci-1002-and-yaml-cpp-1167 (see [below](https://github.com/trilinos/Trilinos/issues/1002#issuecomment-300805240) [Done]
2. Announce switch from GCC 4.7.2 to GCC 4.9.3 to trilinos-developers (see [below](https://github.com/trilinos/Trilinos/issues/1002#issuecomment-300880843)) [Done] 
3. Change over post-push CI build to GCC 4.9.3 and update the build name replacing GCC-4.7.2 with GCC-4.9.3 on branch 'gcc-4.9.3-ci-1002-and-yaml-cpp-1167' (test locally) (see [below](https://github.com/trilinos/Trilinos/issues/1002#issuecomment-300912887)) [Done]
4. Do the switchover (in short order): (see [below](https://github.com/trilinos/Trilinos/issues/1002#issuecomment-300946627) [Done]
4.1. Merge and push the branch 'gcc-4.9.3-ci-1002-and-yaml-cpp-1167' to 'develop'  [Done]
4.2. Kill and restart the CI server on ceerws1113  [Done]
4.3. Update all of the Trilinos GitHub wiki page documentation for change to GCC 4.9.3 (look for all links with GCC-4.7.2)  [Done]
5. Watch CI build for a while and look out for issues ...

**Comment by bartlettroscoe** [comment]
So it seems that no important SNL customer that I know of still needs support for GCC 4.7.2 with C++11 turned (but one requires GCC 4.4.7 with C++11 turned off for the Epetra stack).  However, one important Trilinos customer at SNL needs to build on machines with Intel 14.0 that use GCC 4.7.2 and GCC 4.8.5 backends.  The question I have is, does Intel 14.0 with a GCC 4.7 .2 accept more C++11 features than just raw GCC 4.7.2?  I mean, is it not just that Intel uses the GCC backend for its set of standard header files?  If that is the case, then would Trilinos code that builds with GCC 4.9.3 also have a good chance at building with Intel 11.0 with a GCC 4.7.2 backend?

@trilinos/kokkos and @trilinos/tpetra developers, do you now how Intel 14.0 with a GCC 4.7.2 handles more current C++11 features and if it has a good shot and building C++11 code that that GCC 4.9.3 would support?

**Comment by bartlettroscoe** [comment]
So it looks like that important SNL Trilinos customer may be able to switch over some of those machines to use Intel 17 with a GCC 4.9.3 backend within the next 6 weeks or so (e.g. the end of April 2017).  Therefore, we should just likely wait until the make that transition before we update our Trilinos builds (starting with this CI build) from GCC 4.7.2 to GCC 4.9.3.

**Comment by bartlettroscoe** [comment]
Looks like Sierra still has a few platforms that are still using Intel 14 / GCC 4.7.2 but the hope is to move to Intel 17 / GCC 4.9.3 on those in the next three weeks.  Therefore, to be safe, I will check back again at the end of the month.

**Comment by tawiesn** [comment]
Btw: Just noticed, that GCC 4.7.2 is not in the SEMS modules for RHEL 7 any more. I can use GCC 4.9.3 as workaround for the sems checkin script.

**Comment by bartlettroscoe** [comment]
@tawiesn, are you on the Sandia SRN?  If so, you can use my machine crf450 to push.  If not, then if GCC 4.9.3 is the best you can do for pre-push testing then so be it (it is better than other alternatives).  Just please watch the CI build on CDash linked to from:

* https://github.com/trilinos/Trilinos/wiki/Policies--%7C-Testing#post_push_ci_testing

to see if your pushes cause any issues.  Take a look a few hours later.  (Yes, the CI build is currently broken with failing MueLu tests since May 4 but I will disable those for pre-push testing if the MueLu developers can't resolve them soon.)

Hopefully this will be resolved by dropping support for GCC 4.7.2 and switching to GCC 4.9.3 by the end of the month (see #1002).

**Comment by bartlettroscoe** [comment]
I created the SEMS help ticket:

* https://sems.sandia.gov/jira/servicedesk/customer/portal/4/SEMSHELPD-488

about the removal of the GCC 4.7.2 modules on RHEL 7.

**Comment by bartlettroscoe** [comment]
The blockers for this change are really controlled by Trilinos customers at Sandia so I added to the SART project board.  I would like to discuss this at the SART meeting.

**Comment by pwxy** [comment]
Actually sequoia is still on gcc 4.7.2
But that platform is not relevant to SNL, so this should not hold up the transition from 4.7.2 to 4.9.3

**Comment by bartlettroscoe** [comment]
At the Trilinos Leaders Meeting today we discussed this Issue.  Given that GCC 4.7.2 is not available through SEMS on RHEL 7 (see below) but GCC 4.9.3 is, it was decided that now would be a good time to consider switching the checkin-test-sems.sh script and the CI build being run from ceerws1113 from GCC 4.7.2 to GCC 4.9.3.  But since SIERRA has not yet gotten rid of its Intel 14 (with GCC 4.7.2 backend) builds, that the other CI build being run from sadl30906 would keep using GCC 4.7.2.  (But is is likely that Intel 14 will accept more C++11 code that raw GCC 4.7.2 so maintaining raw GCC 4.7.2 compatibility might be overkill.)  By the end of the month, SIERRA might be done with Intel 14 and therefore may be completely upgraded to GCC 4.9.3 so this may not be a lot of time for problems to pop up.

I will document the set of tasks in the "Description" field (i.e. the first comment).

----

**NOTE:**:  I got a response back from the SEMS team from [SEMSHELPD-488](https://sems.sandia.gov/jira/servicedesk/customer/portal/4/SEMSHELPD-488):

> We recently set up a new rhel7 build machine. gcc-4.7.2 didn't build successfully on this machine, so we removed it. I'd suggest limiting 4.7.2 testing to rhel6 machines and use something newer for rhel7. Sorry for not notifying; SEMS support for rhel7 was still in the somewhat experimental stage prior to this new build machine.

CC: @trilinos/framework

**Comment by bartlettroscoe** [comment]
I am trying this out now on a local branch.

**Comment by bartlettroscoe** [comment]
I have got the full CI build of Trilinos to pass with GCC 4.9.3 and have added the yaml-cpp as a PT TPL on a branch.  This is now ready to push as soon as I have the standard post-CI server switched over.

----

**DETAILED NOTES:**

***(5/11/2017)***

I created the commits:

```
20de21b "Add yaml-cpp as PT TPL (#1167)"
Author: Roscoe A. Bartlett <rabartl@sandia.gov>
Date:   Wed May 10 19:32:18 2017 -0600 (11 hours ago)

M       cmake/load_sems_dev_env.sh
M       cmake/std/BasicCiTestingSettings.cmake
M       cmake/std/sems/SEMSDevEnv.cmake
M       cmake/std/sems/get_default_modules.sh

c4f78a2 "Change CI build from GCC 4.7.2 to 4.9.3 (#1002)"
Author: Roscoe A. Bartlett <rabartl@sandia.gov>
Date:   Wed May 10 19:18:27 2017 -0600 (11 hours ago)

M       cmake/load_ci_sems_dev_env.sh
M       cmake/std/sems/get_default_modules.sh
```

And pushed to the branch:

```
To git@github.com:bartlettroscoe/Trilinos
 * [new branch]      gcc-4.9.3-ci-1002-and-yaml-cpp-1167 -> gcc-4.9.3-ci-1002-and-yaml-cpp-1167
```

I tested this with:

```
$ ./checkin-test-sems.sh --enable-all-packages=on --local-do-all
```

This resulted in:

```
FAILED: Trilinos/MPI_RELEASE_DEBUG_SHARED_PT: passed=2318,notpassed=2

Wed May 10 21:34:47 MDT 2017

Enabled Packages: 
Disabled Packages: PyTrilinos,Claps,TriKota
Enabled all Packages
Hostname: crf450.srn.sandia.gov
Source Dir: /home/rabartl/Trilinos.base/Trilinos/cmake/tribits/ci_support/../../..
Build Dir: /home/rabartl/Trilinos.base/BUILDS/CHECKIN/MPI_RELEASE_DEBUG_SHARED_PT

CMake Cache Varibles: -DTrilinos_TRIBITS_DIR:PATH=/home/rabartl/Trilinos.base/Trilinos/cmake/tribits -DTrilinos_ENABLE_TESTS:BOOL=ON -DTrilinos_TEST_CATEGORIES:STRING=BASIC -DTrilinos_ALLOW_NO_PACKAGES:BOOL=OFF -DDART_TESTING_TIMEOUT:STRING=300.0 -DBUILD_SHARED_LIBS=ON -DTrilinos_DISABLE_ENABLED_FORWARD_DEP_PACKAGES=ON -DTrilinos_TRACE_ADD_TEST=ON -DTrilinos_ENABLE_SECONDARY_TESTED_CODE:BOOL=OFF -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/MpiReleaseDebugSharedPtSettings.cmake,cmake/std/BasicCiTestingSettings.cmake -DTrilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=ON -DTrilinos_ENABLE_ALL_PACKAGES:BOOL=ON -DTrilinos_ENABLE_ALL_FORWARD_DEP_PACKAGES:BOOL=ON -DTrilinos_ENABLE_PyTrilinos:BOOL=OFF -DTrilinos_ENABLE_Claps:BOOL=OFF -DTrilinos_ENABLE_TriKota:BOOL=OFF
Make Options: -j16
CTest Options: -j16 

Pull: Not Performed
Configure: Passed (3.27 min)
Build: Passed (87.05 min)
Test: FAILED (15.16 min)

99% tests passed, 2 tests failed out of 2320

Label Time Summary:
Amesos               =  18.79 sec (14 tests)
Amesos2              =  10.78 sec (8 tests)
Anasazi              = 102.54 sec (71 tests)
AztecOO              =  17.70 sec (17 tests)
Belos                =  89.27 sec (61 tests)
Domi                 = 153.16 sec (125 tests)
Epetra               =  45.43 sec (61 tests)
EpetraExt            =  13.47 sec (10 tests)
FEI                  =  43.40 sec (43 tests)
Galeri               =   4.30 sec (9 tests)
GlobiPack            =   1.64 sec (6 tests)
Ifpack               =  59.18 sec (53 tests)
Ifpack2              =  46.74 sec (33 tests)
Intrepid             = 174.66 sec (152 tests)
Intrepid2            =  40.83 sec (73 tests)
Isorropia            =   7.90 sec (6 tests)
Kokkos               = 228.79 sec (21 tests)
KokkosKernels        =   6.01 sec (9 tests)
ML                   =  43.78 sec (34 tests)
MiniTensor           =   0.60 sec (2 tests)
MueLu                = 495.61 sec (56 tests)
NOX                  = 134.58 sec (101 tests)
OptiPack             =   6.45 sec (5 tests)
Panzer               = 300.78 sec (129 tests)
Phalanx              =   5.97 sec (18 tests)
Pike                 =   3.18 sec (7 tests)
Piro                 =  25.16 sec (12 tests)
ROL                  = 871.59 sec (132 tests)
RTOp                 =  11.39 sec (24 tests)
Rythmos              = 141.40 sec (83 tests)
SEACAS               =   7.31 sec (8 tests)
STK                  =  24.55 sec (11 tests)
Sacado               =  56.63 sec (292 tests)
Shards               =   1.02 sec (4 tests)
ShyLU                =   8.00 sec (5 tests)
Stokhos              =  89.91 sec (74 tests)
Stratimikos          =  27.32 sec (39 tests)
Teko                 = 179.62 sec (19 tests)
Tempus               = 508.01 sec (9 tests)
Teuchos              =  45.70 sec (125 tests)
ThreadPool           =   8.31 sec (10 tests)
Thyra                =  61.58 sec (80 tests)
Tpetra               = 136.79 sec (127 tests)
TrilinosCouplings    =  41.92 sec (19 tests)
Triutils             =   2.56 sec (2 tests)
Xpetra               =  41.73 sec (17 tests)
Zoltan               = 201.33 sec (16 tests)
Zoltan2              = 128.24 sec (96 tests)

Total Test time (real) = 909.44 sec

The following tests FAILED:
	 97 - TeuchosParameterList_ObjectBuilder_UnitTests_MPI_1 (Failed)
	1895 - Rythmos_StepperBuilder_UnitTest_MPI_1 (Failed) Errors while running CTest
```

These are two problematic tests and have been so for a long time.  The test failure for TeuchosParameterList_ObjectBuilder_UnitTests_MPI_1 was reported in see #482, #449, and #831 and is related to destructors throwing exceptions (see #1303).  The solution was to just disable that that unit test for several GCC compilers.  But really that should be addressed along with the larger story #1303 to remove exceptions from all destructors in Trilinos.

It looks like a similar problem is occuring with the test Rythmos_StepperBuilder_UnitTest_MPI_1 as shown by the commits:

```
52c774a "Rythmos: Added work-around to StepperBuilder unit test for GCC 5.2."
Author: Mark Hoemmen <mhoemme@sandia.gov>
Date:   Mon Sep 21 12:45:45 2015 -0600 (1 year, 8 months ago)

M       packages/rythmos/test/UnitTest/Rythmos_StepperBuilder_UnitTest.cpp

0daf68c "Rythmos: Skip one unit test for GCC 4.8.x"
Author: Roscoe A. Bartlett <bartlettra@ornl.gov>
Date:   Wed Mar 11 09:23:15 2015 -0400 (2 years, 2 months ago)

M       packages/rythmos/test/UnitTest/Rythmos_StepperBuilder_UnitTest.cpp
```

Given the low importance of both of these "builder" classes, I will just follow along and disable these unit tests for now so we can get this GCC 4.9.3 CI build set up and going.  It is likely this will get fixed automatically once we stop the Teuchos Memory Management classes from throwing exceptions in destructrors (see #1303).

With these tests disabled, running the full CI (re-)build and tests again:

```
./checkin-test-sems.sh --enable-all-packages=on --build --test
```

This returned:

```
passed: Trilinos/MPI_RELEASE_DEBUG_SHARED_PT: passed=2320,notpassed=0

Thu May 11 08:12:25 MDT 2017

Enabled Packages: 
Disabled Packages: PyTrilinos,Claps,TriKota Enabled all Packages
Hostname: crf450.srn.sandia.gov
Source Dir: /home/rabartl/Trilinos.base/Trilinos/cmake/tribits/ci_support/../../..
Build Dir: /home/rabartl/Trilinos.base/BUILDS/CHECKIN/MPI_RELEASE_DEBUG_SHARED_PT

CMake Cache Varibles: -DTrilinos_TRIBITS_DIR:PATH=/home/rabartl/Trilinos.base/Trilinos/cmake/tribits -DTrilinos_ENABLE_TESTS:BOOL=ON -DTrilinos_TEST_CATEGORIES:STRING=BASIC -DTrilinos_ALLOW_NO_PACKAGES:BOOL=OFF -DDART_TESTING_TIMEOUT:STRING=300.0 -DBUILD_SHARED_LIBS=ON -DTrilinos_DISABLE_ENABLED_FORWARD_DEP_PACKAGES=ON -DTrilinos_TRACE_ADD_TEST=ON -DTrilinos_ENABLE_SECONDARY_TESTED_CODE:BOOL=OFF -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/MpiReleaseDebugSharedPtSettings.cmake,cmake/std/BasicCiTestingSettings.cmake -DTrilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=ON -DTrilinos_ENABLE_ALL_PACKAGES:BOOL=ON -DTrilinos_ENABLE_ALL_FORWARD_DEP_PACKAGES:BOOL=ON -DTrilinos_ENABLE_PyTrilinos:BOOL=OFF -DTrilinos_ENABLE_Claps:BOOL=OFF -DTrilinos_ENABLE_TriKota:BOOL=OFF
Make Options: -j16
CTest Options: -j16 

Pull: Not Performed
Configure: Not Performed
Build: Passed (6.71 min)
Test: Passed (13.15 min)

100% tests passed, 0 tests failed out of 2320

Label Time Summary:
Amesos               =  19.24 sec (14 tests)
Amesos2              =  10.31 sec (8 tests)
Anasazi              = 101.38 sec (71 tests)
AztecOO              =  16.44 sec (17 tests)
Belos                =  89.59 sec (61 tests)
Domi                 = 146.51 sec (125 tests)
Epetra               =  42.00 sec (61 tests)
EpetraExt            =  12.41 sec (10 tests)
FEI                  =  39.68 sec (43 tests)
Galeri               =   3.96 sec (9 tests)
GlobiPack            =   0.76 sec (6 tests)
Ifpack               =  56.42 sec (53 tests)
Ifpack2              =  48.25 sec (33 tests)
Intrepid             = 157.13 sec (152 tests)
Intrepid2            =  29.81 sec (73 tests)
Isorropia            =   7.91 sec (6 tests)
Kokkos               = 226.74 sec (21 tests)
KokkosKernels        =   4.26 sec (9 tests)
ML                   =  44.09 sec (34 tests)
MiniTensor           =   0.44 sec (2 tests)
MueLu                = 515.32 sec (56 tests)
NOX                  = 128.85 sec (101 tests)
OptiPack             =   5.80 sec (5 tests)
Panzer               = 292.46 sec (129 tests)
Phalanx              =   2.94 sec (18 tests)
Pike                 =   2.29 sec (7 tests)
Piro                 =  24.68 sec (12 tests)
ROL                  = 849.33 sec (132 tests)
RTOp                 =   9.24 sec (24 tests)
Rythmos              = 142.10 sec (83 tests)
SEACAS               =   6.06 sec (8 tests)
STK                  =  23.33 sec (11 tests)
Sacado               =  34.79 sec (292 tests)
Shards               =   0.51 sec (4 tests)
ShyLU                =   8.32 sec (5 tests)
Stokhos              =  88.83 sec (74 tests)
Stratimikos          =  27.55 sec (39 tests)
Teko                 = 171.42 sec (19 tests)
Tempus               = 520.96 sec (9 tests)
Teuchos              =  34.18 sec (125 tests)
ThreadPool           =   8.25 sec (10 tests)
Thyra                =  56.89 sec (80 tests)
Tpetra               = 129.41 sec (127 tests)
TrilinosCouplings    =  42.53 sec (19 tests)
Triutils             =   2.52 sec (2 tests)
Xpetra               =  41.38 sec (17 tests)
Zoltan               = 195.99 sec (16 tests)
Zoltan2              = 126.19 sec (96 tests)

Total Test time (real) = 788.68 sec

Total time for MPI_RELEASE_DEBUG_SHARED_PT = 19.86 min
```

As part of this, I am also testing the addition of YAML as a PT TPL (#1167).  The configure of this branch showed:

```
-- Setting TPL_ENABLE_yaml-cpp='ON' by default for CI testing
...
Explicitly enabled TPLs on input (by user):  yaml-cpp Pthread MPI BLAS LAPACK Boost ParMETIS Zlib HDF5 Netcdf SuperLU BoostLib DLlib 13
...
-- Setting TeuchosCore_ENABLE_yaml-cpp=ON since TPL_ENABLE_yaml-cpp=ON
...
Processing enabled TPL: yaml-cpp (enabled explicitly, disable with -DTPL_ENABLE_yaml-cpp=OFF)
...
-- TeuchosParameterList_YamlParser_test_MPI_1: Added test (BASIC, NUM_MPI_PROCS=1, PROCESSORS=1)!
```

Therefore, when I merge and push this branch, yaml-cpp will be a PT TPL and will therefore be tested as part of standard pre-push and post-push CI testing.

Therefore, this is ready to push as soon as I can switch over the post-push CI server to use GCC 4.9.3.  I will send out an announcement about that before I pull the trigger.

**Comment by bartlettroscoe** [comment]
I gave the Trilinos developers the heads-up about this change in the below email.   I just need to finish testing the updated post-push CI build then I am ready to pull the trigger.

----

From: trilinos-framework-bounces@software.sandia.gov [mailto:trilinos-framework-bounces@software.sandia.gov] On Behalf Of Bartlett, Roscoe A
Sent: Thursday, May 11, 2017 2:19 PM
To: Trilinos Developers List <trilinos-developers@trilinos.org>
Cc: trilinos-framework@software.sandia.gov
Subject: [Trilinos-Framework] FYI: Switching standard Trilinos pre-push and post-push Trilinos CI builds from GCC 4.7.2 to 4.9.3

Hello Trilinos Developers,

FYI:

As discussed at the Trilinos Leaders Meeting yesterday, the standard Trilinos pre-push CI and post-push CI builds will be switching from GCC 4.7.2 to GCC 4.9.3.  This will likely happen later today to tomorrow morning. 

As part of this the yaml-cpp TPL is also being added as a PT TPL and Boost is being updated from 1.55.0 to 1.63.0.

For the motivation and the triggers for making these changes, see:

   https://github.com/trilinos/Trilinos/issues/1002
   https://github.com/trilinos/Trilinos/issues/1167

Comments or concerns can be added as comments to the above GitHub Issues.

But this should not have any impact on people’s development workflows if they are using the checkin-test-sems.sh script.  The switch should will be handled automatically.   (If anyone has any problems with this, let me know.)

Cheers,

-Ross

**Comment by bartlettroscoe** [comment]
I have the post-push CI build ready to go on the branch (testing is shown below).  Now to just pull the trigger and do the switch as per the above list of tasks.

----

**DETAILED NOTES:**

***(5/11/2017)***

To transition the post-push CI build I just made the simple commit:

```
bab8b4e "Transition CI build from GCC 4.7.2 to 4.9.3 (#1002)"
Author: Roscoe A. Bartlett <rabartl@sandia.gov>
Date:   Thu May 11 11:48:42 2017 -0600 (87 seconds ago)

M       cmake/ctest/drivers/sems_ci/TrilinosCTestDriverCore.sems.cmake
```

Now to do a local test of this build:

```
$ cd MOCK_CI_BUILD/
$ ln -s ../../../Trilinos .
$ . ../../../Trilinos/cmake/load_ci_sems_dev_env.sh

$ module list
Currently Loaded Modulefiles:
  1) sems-env                       4) sems-git/2.10.1                7) sems-boost/1.63.0/base        10) sems-hdf5/1.8.12/parallel     13) sems-superlu/4.3/base
  2) sems-python/2.7.9              5) sems-gcc/4.9.3                 8) sems-yaml_cpp/0.5.3/base      11) sems-netcdf/4.3.2/parallel
  3) sems-cmake/3.5.2               6) sems-openmpi/1.6.5             9) sems-zlib/1.2.8/base          12) sems-parmetis/4.0.3/parallel

$ time env CTEST_DASHBOARD_ROOT=$PWD \
     Trilinos_PACKAGES=Teuchos,RTOp \
     CTEST_TEST_TYPE=Experimental \
     CTEST_DO_UPDATES=FALSE \
     CTEST_DO_SUBMIT=TRUE \
     CTEST_START_WITH_EMPTY_BINARY_DIRECTORY=TRUE \
     CTEST_EXPLICITLY_ENABLE_IMPLICITLY_ENABLED_PACKAGES=FALSE \
     CTEST_SUBMIT_CDASH_SUBPROJECTS_DEPS_FILE=FALSE \
     ctest -V -S \
     ../../../Trilinos/cmake/ctest/drivers/sems_ci/ctest_linux_mpi_debug_shared_pt_ci.sems.cmake \
     &> console.out

real    5m41.742s
user    25m41.752s
sys     1m37.967s
```

The output says it submitted:

```
Submitting configure and notes ...
info: using retry_args='RETRY_COUNT;25;RETRY_DELAY;120' for _ctest_submit call
	Add file: /ascldap/users/rabartl/Trilinos.base/BUILDS/GCC-4.9.3/MOCK_CI_BUILD/BUILD/TrilinosRepoVersion.txt
	Add file: /ascldap/users/rabartl/Trilinos.base/Trilinos/cmake/ctest/drivers/sems_ci/ctest_linux_mpi_debug_shared_pt_ci.sems.cmake
	Add file: /ascldap/users/rabartl/Trilinos.base/BUILDS/GCC-4.9.3/MOCK_CI_BUILD/BUILD/CMakeCache.clean.txt
Submit files (using http)
   Send to track: Experimental
   Using HTTP submit method
   Drop site:http://testing.sandia.gov/cdash/submit.php?project=Trilinos
   Uploaded: /ascldap/users/rabartl/Trilinos.base/BUILDS/GCC-4.9.3/MOCK_CI_BUILD/BUILD/Testing/20170511-1804/Configure.xml
   Uploaded: /ascldap/users/rabartl/Trilinos.base/BUILDS/GCC-4.9.3/MOCK_CI_BUILD/BUILD/Testing/20170511-1804/Notes.xml
   Submission successful
```

However, nothing is showing up yet on the CDash page:

* testing.sandia.gov/cdash/index.php?project=Trilinos&date=2017-05-11

I wonder if the CDash processing is running a bit behind?

Okay, 15 minutes later it showed up as the experimental build Linux-GCC-4.9.3-MPI_RELEASE_DEBUG_SHARED_PT_CI on crf450:

* http://testing.sandia.gov/cdash/index.php?project=Trilinos&parentid=2889937

Looks like the right compiler is being used from looking at:

* http://testing.sandia.gov/cdash/buildSummary.php?buildid=2889938

which shows:

```
-- The CXX compiler identification is GNU 4.9.3
-- Check for working CXX compiler: /projects/sems/install/rhel6-x86_64/sems/compiler/gcc/4.9.3/openmpi/1.6.5/bin/mpicxx
-- Check for working CXX compiler: /projects/sems/install/rhel6-x86_64/sems/compiler/gcc/4.9.3/openmpi/1.6.5/bin/mpicxx -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- CMAKE_CXX_COMPILER_ID='GNU'
-- CMAKE_CXX_COMPILER_VERSION='4.9.3'
```

Therefore, this is ready to push and get running in the CI build.

**Comment by bartlettroscoe** [comment]
The transition is complete.  You can see the updated CI server running as linked to from:

* https://github.com/trilinos/Trilinos/wiki/Policies--%7C-Testing#post_push_ci_testing

I think I caught all of the references to this CI build on the wiki.

Again, the other CI build using GCC 4.9.3 Linux-GCC-4.7.2-CONTINUOUS_MPI_OPT_DEV_SHARED  running on sadl30906.srn.sandia.gov at:

* http://testing.sandia.gov/cdash/index.php?project=Trilinos&display=project

The @trilinos/framework team can decide what they want to do with that CI build.

I am putting this story in review to see how the CI build goes for the next few days.

**Comment by bartlettroscoe** [comment]
Looks like this transition has goon pretty smoothly as shown by

* http://testing.sandia.gov/cdash/index.php?project=Trilinos&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=66&value1=MPI_RELEASE_DEBUG_SHARED_PT_CI&field2=groupname&compare2=61&value2=Continuous&field3=buildstarttime&compare3=84&value3=now

There have been several iterations where people pushed and it got picked up.  There has been no reports of problems.  Therefore, I am closing as complete.

**Comment by bartlettroscoe** [comment]
I am leaving "In Review" for now in the [SART Issues](https://github.com/trilinos/Trilinos/projects/1#card-2837170) board so that we can discuss this at the next SART meeting.  Mostly SIERRA will be impacted since it still uses Intel 14 with GCC 4.7.2 backend.

**Comment by pwxy** [comment]
Don't forget the Trilinos users on sequoia (or any other BG/Q such as ANL Mira); they could potentially be impacted since sequoia is still on gcc 4.7.2.

**Comment by bartlettroscoe** [comment]
> Don't forget the Trilinos users on sequoia (or any other BG/Q such as ANL Mira); they could potentially be impacted since sequoia is still on gcc 4.7.2.

Yes, I remember from [above](https://github.com/trilinos/Trilinos/issues/1002#issuecomment-300276267). But since SEMS has dropped the GCC 4.7.2 module from the RHEL 7 env (see [above](https://github.com/trilinos/Trilinos/issues/1002#issuecomment-300305297)) and since people are refusing to test with GCC 4.7.2 before they push (see [here](https://github.com/trilinos/Trilinos/issues/1304#issuecomment-300895704)), that compiler will be harder and harder to support going forward so every Trilinos customer using the Kokkos/Tpetra/C++11 stack would be wise to upgrade there GCC compiler to 4.9.3+ ASAP.
