### ISSUE TITLE
Xpetra warnings

### ISSUE THREAD

**Issue by dridzal** [trilinos/Trilinos#1003]
We have observed some new warnings in Xpetra:

/home/dridzal/research/Trilinos/packages/xpetra/sup/Utils/Xpetra_ThyraUtils.hpp:793:89:   required from here
/home/dridzal/research/Trilinos/packages/xpetra/src/Utils/Xpetra_MapUtils.hpp:337:22: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for(int i = 1; i < numMaps; ++i) {
                      ^
/home/dridzal/research/Trilinos/packages/xpetra/src/Utils/Xpetra_MapUtils.hpp:343:23: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (int b = 0; b < rcpBlockedInput->getNumMaps(); ++b){
                       ^

**Comment by aprokop** [comment]
Ping @trilinos/xpetra

**Comment by tawiesn** [comment]
Checkin script is running...

**Comment by tawiesn** [comment]
Dashboard is clean.
