### ISSUE TITLE
Framework: Autotester fails on module load

### ISSUE THREAD

**Issue by cgcgcg** [trilinos/Trilinos#10036]
## Bug Report
@trilinos/framework 

### Description

https://github.com/trilinos/Trilinos/pull/10000#issuecomment-996859685
The autotester python builds fails with:
```
PRDriver> module load sems-git/2.10.1
Lmod has detected the following error: The following module(s) are unknown:
"sems-git/2.10.1"
```

**Comment by cgcgcg** [comment]
Submitted JIRA ticket TRILINOSHD-61

@jwillenbring @ZUUL42 @prwolfe @william76

**Comment by ZUUL42** [comment]
It looks like the SEMS TPL switchover happened.
I moved all of the builds to the new location, but missed the python3 test.
I'll put in a fix for this to get things passing again.

**Comment by cgcgcg** [comment]
Cool, thank you @ZUUL42

**Comment by cgcgcg** [comment]
FYI, the dev->master AT seems to have the same issues, see e.g. https://github.com/trilinos/Trilinos/pull/10063
