### ISSUE TITLE
Tpetra:  Sparse-Dense matrix multiplication (SpMM)

### ISSUE THREAD

**Issue by rohany** [trilinos/Trilinos#10040]
@trilinos/Tpetra

I'm trying to understand what support TPetra / Trilinos has for different sparse linear algebra kernels. I'm currently looking at the SpMM kernel `C(i, j) = A(i, k) * B(k, j)` where A is sparse, and B, C are dense rectangular matrices. The only matrix multiplication routine I see in TPetra is https://docs.trilinos.org/dev/packages/tpetra/doc/html/namespaceTpetra_1_1MatrixMatrix.html, which takes in 2 `CrsMatrix` objects. Is it possible to represent dense matrices in TPetra? It seems like one could do the SpMM operation by using `MultiVector` objects to implement the dense rectangular matrices, but I don't see a routine to multiply a `CrsMatrix` and a `MultiVector`.

**Comment by rohany** [comment]
Thanks! I'm not sure how I missed that overload of apply...

Do you mind sanity checking my implementation? I was a bit unsure how to set everything up for best performance, so let me know if anything is wrong. In particular, I'm not sure what makes the most sense for the maps -- is using the maps on the input matrix (read from a matrix market file) reasonable, or would it be better to make a new one for this computation?

```
void spmm(Teuchos::RCP<const Teuchos::Comm<int>> comm, Teuchos::RCP<Tpetra::CrsMatrix<double>> B, int warmup, int niter, int kDim, Teuchos::FancyOStream& out) {
  // TODO (rohany): I'm not sure what the best assignment of Domain and Range maps
  //  are here for this operation.
  Tpetra::MultiVector<double> A(B->getDomainMap(), kDim);
  Tpetra::MultiVector<double> C(B->getRangeMap(), kDim);
  A.putScalar(0.0);
  C.putScalar(1.0);

  // Warmup iterations.
  for (int i = 0; i < warmup; i++) {
    B->apply(C, A);
  }
  // Timed iterations.
  auto timer = Teuchos::TimeMonitor::getNewCounter("SpMM");
  for (int i = 0; i < niter; i++) {
    Teuchos::TimeMonitor timeMon(*timer);
    B->apply(C, A);
  }
  Teuchos::TimeMonitor::summarize(comm.ptr(), out);
}
```

**Comment by cgcgcg** [comment]
The maps of the multivectors need to match the domain and range maps of the matrix, so that's correct. Out of curiosity: what's the end goal? I'd assume that `kDim` has been tuned quite a bit, and I'd expect good performance for `kDim` << matrix size.

**Comment by rohany** [comment]
> I'd assume that kDim has been tuned quite a bit, and I'd expect good performance for kDim << matrix size.

Yep, kDim is a small value (32 or 64).

> Out of curiosity: what's the end goal?

I'm working on a system that generates implementations of distributed sparse tensor kernels. I'm comparing the performance of those kernels to PETSc and Trilinos to understand how those kernels compare to heavily optimized systems.

I'll close the issue now, as I think I've got everything I need!
