### ISSUE TITLE
Zoltan2 default Environment() constructor should be replaced/reworked

### ISSUE THREAD

**Issue by mmwolf** [trilinos/Trilinos#1004]
The default Environment() constructor in Zoltan2 uses a default communicator obtained from Teuchos that is MPI_COMM_WORLD.  It then does some global communication with this communicator.  
For applications that use subcommunicators for their Trilinos/Zoltan operations (a subset of the MPI tasks in MPI_COMM_WORLD), this will result in the application hanging in a function called by this constructor.

**Comment by mmwolf** [comment]
For now, I'm going to just try to move some offending instances of Zoltan calling Environment() but eventually we should eliminate this a possibility.  Two possible options:

1. Don't allow Environment constructor to be called without passing in a communicator.  i.e., Environment(comm)
2.  Only have constructors that take comm arguments, but have a default communicator set (for backward compatibility) and put a strong comment about the dangers of going with the default communicator.

**Comment by mhoemmen** [comment]
@trilinos/zoltan2

**Comment by mmwolf** [comment]
I've finished removing all usage of Environment from the input adapters (issue #1005).

**Comment by kddevin** [comment]
We decided that the default constructor that does not accept a communicator should be removed everywhere.  All Environment constructors should take a communicator as input.

**Comment by MicheldeMessieres** [comment]
@kddevin For the main() setups with new Environment() would it be preferable to add a parameter list in the main():

  Teuchos::ParameterList myParams("testParameterList");

Then use the current constructor and pass the comm:
  new Environment(myParams, comm);

Or potentially we could have an Environment constructor which takes only a comm and then assumes a default parameter list.

**Comment by kddevin** [comment]
Hi, @MicheldeMessieres .  Sorry; I do not understand the question.

Right now, we have two Environment constructors:
Environment(Teuchos::ParameterList &, Teuchos::RCP<Teuchos::Comm> &) and
Environment()

We should keep the first one as-is.
We should add Teuchos::RCP<Teuchos::Comm>& as an argument to the second one.

Thus, the test programs would have to add a Comm argument to their constructors, but an additional parameter list would not be needed.

Does that answer the question?  If not, please point me to a specific test program of concern.  Thanks!

**Comment by MicheldeMessieres** [comment]
That answers it perfectly - thank you. I will change Environment() to take the comm as a single parameter and use that in all the mains.

**Comment by MicheldeMessieres** [comment]
@kddevin PR #1061 has these changes. However there was one spot I was uncertain how we wish to format. In Zoltan2_TaskMapping.hpp we had an environment and a problemComm. I think the problemComm should not be used with Environment in general. I changed the API to pass through an environment from the source main which is taskMappingTest3.cpp.  I was not sure if the API should be changed like this so those two files likely will need a revision.
