### ISSUE TITLE
Zoltan2: Test failure for RDC build

### ISSUE THREAD

**Issue by jwillenbring** [trilinos/Trilinos#10043]
## Bug Report
@trilinos/zoltan2 

CC: @kddevin 
CC: @trilinos/framework 

### Description

The RDC build had one test failure the last time it ran: Zoltan2_GraphModel_MPI_4. I wasn't able to find exactly why this failed. I would appreciate any insight as to if this is a failure that needs to be fixed, or if this was a one-off issue perhaps.

https://testing.sandia.gov/cdash/test/109158159

**Comment by e10harvey** [comment]
There is also one other RDC failure in teuchos (@trilinos/teuchos): https://trilinos-cdash.sandia.gov/test/104443.

**Comment by bartlettroscoe** [comment]
The test `TeuchosComm_UnitTestHarness_Parallel_UnitTests_MPI_4` does not use CUDA at all so it is doubtful that failures of that test are realted to CUDA RDC issues.  My guess is that this is the system failures reported in #8759.  Please take Teuchos off of this as #8759 covers the issues (which is not actually a Teuchos problem).

**Comment by kddevin** [comment]
The Zoltan2 failure is due only to mis-aligned output from many processors.  PR #10039 is already submitted to try to fix the problem.  The PR needs a review (anyone can review it, please) and it needs to get through PR testing.  I am hopeful that it will fix the problem. @e10harvey

**Comment by kddevin** [comment]
I suspect this is a one-off error.  The test passed, but the output got mangled so that the test harness couldn't find the "PASS" keyword.
If this problem persists, let me know and we'll reduce the amount of output.
@jwillenbring @e10harvey
