### ISSUE TITLE
Ifpack2:  Choosing of the preconditioner and its parameters for linear system

### ISSUE THREAD

**Issue by WhiteFang13** [trilinos/Trilinos#10049]
## Question
@trilinos/Ifpack2 @trilinos/belos

I am solving the linear system, (obtained by discretization of PDE system, for FEM task). The linear system (Ax = b, where A is matrix and x, b - vectors) consists of about 10^6 equations. We need to solve it many times with non significant right-hand vector 'b' modifications. The matrix 'A' is square, non-symmetric, contains positive and negative values. The matrix rank is equal to its sizes. I ask for your help with choosing of a preconditioner and an iterative solver for the matrix. We have tried Ifpack2_AdditiveSchwarz preconditioner and GMRES solver from BelosFactoryType, both with default parameters. This combination preconditioner+solver have solved our matrix at 2 MPI processes (we have obtained the result), but failed at larger number of MPI processes. At 2 processes the solver wrote that the solution did not converged, but we compared 'Ax' and 'b', and saw that the solution was correct. Another preconditioner 'block relaxation' also from Ifpack2 writes that the matrix (that was correctly calculated at 2 MPI processes) may be partially singular. The direct methods from Amesos2 have successfully solved the matrix (converged), but they are too slow.

Why the iterative solver that works at 2 MPI processes, does not work at its larger number? What are the possible or the best combinations of preconditioner + solver for our task? What parameters do we need for them?
If it is necessary, I can provide the matrix and any additional information.

Waiting for your answers. Thanks!
Lidia

**Comment by WhiteFang13** [comment]
The error messages from 'block relaxation' preconditioner:

Another preconditioner 'block relaxation' also from Ifpack2 writes that the matrix (that was correctly calculated at 2 MPI processes) may be partially singular:
"Ifpack2::DenseContainer::factor: LAPACK's _GETRF (LU factorization with partial pivoting) reports that the computed U factor is exactly singular.  U(601,601) (one-based index i) is exactly zero.  This probably means that the input matrix has a singular diagonal block."
And we have two very small systems, at which the solvers can use more than 2 MPI processes. But starting with some large number of processes (8) we also have the error message:
"Ifpack2::Container::translateRowToCol: On process 38, at least one row index in the set of row indices given to the constructor does not have a corresponding column index in the input matrix's column Map.  This probably means that the column(s) in question is/are empty on this process, which would make the submatrix to extract structurally singular. The invalid global column index is 402."

**Comment by cgcgcg** [comment]
Both the additive Schwarz and block relaxation operate on a similar principle. Extract a block diagonal (overlapping blocks for additive Schwarz) and solve directly on each block. For additive Schwarz at least, these blocks are associate to the process local row space of the matrix. Now, if the number of MPI ranks is increased, the blocks shrink in size. That generally deteriorates the quality of the preconditioner. (Think of the limit of 1 single MPI rank. The preconditioner is just a direct solver.)

As for the error message: it looks like one of the extracted diagonal blocks is singular. Normally that shouldn't happen. What kind of PDE is being discretized here? I could see this happen for a mixed formulation, but maybe there is an issue in the matrix itself?

**Comment by jhux2** [comment]
@trilinos/ifpack2 @trilinos/belos

**Comment by jhux2** [comment]
@WhiteFang13 I'm going to close this issue as answered.  Please reopen if you still have questions.

**Comment by WhiteFang13** [comment]
Thanks a lot for the answer! I am thinking about it, so have not written the next comment. Okay, if it is needed, I'll re-open the issue.
