### ISSUE TITLE
Remove Zoltan2 Environment objects from input adapters

### ISSUE THREAD

**Issue by mmwolf** [trilinos/Trilinos#1005]
This is related to issue #1004.

Our current usage of the default Zoltan2 Environment constructor is dangerous.  Furthermore, the input adapters are inconsistent in whether they use the Environment object (only Xpetra adapters seem to use this) and when they are used, they are only used inconsistent for a few debug errors.  

The plan is to remove all usage of Environment objects in the input adapters and replace them with print statements and simple error catching.

**Comment by mhoemmen** [comment]
@trilinos/zoltan2

**Comment by mmwolf** [comment]
I've finished removing all usage of Environment from the input adapters.  Nothing seems to be broken.
