### ISSUE TITLE
SEACAS: Exodus (apparent) inconsistent check for parallel support in netcdf

### ISSUE THREAD

**Issue by bartgol** [trilinos/Trilinos#10059]
## Question
@trilinos/seacas 

In our library (Albany) we check if parallel exodus is enabled by attempting to compile a dummy main file that includes `exodusII_par.h`. This will compile provided that `NC_HAS_PARALLEL` is defined. In netCDF, this macro is defined if PnetCDF is present _OR_ if HDF5 is built with parallel enabled.

However, in `ex_open_par.c`, exodus errors out if PnetCDF is not enabled (rather than check the `NC_HAS_PARALLEL` macro). This seems an inconsistent behavior. But maybe I'm missing something regarding parallel mechanisms?

@ikalash

**Comment by gsjaardema** [comment]
In the version of `ex_open_par.c` that I look at, it checks whether `PARALLEL_AWARE_EXODUS` is defined.  This is defined in `exodusII.h` as:
```
#if NC_HAS_PARALLEL
#ifndef PARALLEL_AWARE_EXODUS
#define PARALLEL_AWARE_EXODUS
#endif
#else
#ifdef PARALLEL_AWARE_EXODUS
#error "PARALLEL_AWARE_EXODUS defined, but NetCDF NC_HAS_PARALLEL is false"
#endif
#endif
#endif
```

This is with the current source of SEACAS in Trilinos...  I guess I'm not seeing what you are seeing...

**Comment by bartgol** [comment]
So, we see this error
```
Exodus Library Warning/Error: [ex_open_par_int]
	EXODUS: ERROR: Attempting to open the NetCDF file:
	'quadQuad.exo'
	The NetCDF library was not built with PNetCDF support as required for parallel access to this file.
```
which is thrown if the file is "serial" (classic netCDF), but we want to open it in parallel, which requires PnetCDF, correct?

So the macro `PARALLEL_AWARE_EXODUS` for us is ON, which, given the error, means NC_HAS_PARALLEL is on, but PnetCDF is not present, which means that parallel support was enabled in netcdf (via `ENABLE_PARALLEL4`/`ENABLE_HDF5_PARALLEL` and `ENABLE_NETCDF_4`).

So, at this point, I'm a bit confused. If NC_HAS_PARALLEL is ON, why do I need PnetCDF? I would assume that NC_HAS_PARALLEL is enough to enable parallel reads...

**Comment by gsjaardema** [comment]
If you have a classic (non-netcdf-4, non-hdf5-based) file, then you need PnetCDF to open that file in parallel.  If you have a netcdf-4 based file (which uses HDF5 as the on-disk storage format), then the HDF5 library is used to do the parallel reads and writes.  

`NC_HAS_PARALLEL` just signifies that at least one of HDF5 and/or PnetCDF is present, but is not enough to guarantee that any of the netCDF variants can be read/written in parallel.

**Comment by bartgol** [comment]
Ok, that makes sense.

Thanks!
