### ISSUE TITLE
Add gatherv wrapper to Teuchos

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#1006]
@trilinos/teuchos @trilinos/tpetra 

@dridzal requested a gatherv wrapper for either Teuchos or Tpetra.  Tpetra has an implementation of this wrapper now, but it currently lives in an anonymous namespace.  @dridzal would like to see it promoted to the public interface.  See commit b5b1b8f09812500d5bcbd53e9b2a99ead10823de.

It would be easy for just about any Trilinos developer without much Tpetra or Teuchos knowledge to promote Tpetra's current internal implementation to a public interface, and add a unit test.  I'll be happy to review and accept pull requests.

**Comment by dridzal** [comment]
Yes, and it would have to support arbitrary types.  Please correct me if I'm wrong, but the Tpetra version only works on integer data (did I miss something?).  Also, I wonder where these wrappers should live.  It doesn't matter if it's Teuchos or Tpetra, but they need to be in one place.

**Comment by mhoemmen** [comment]
> Yes, and it would have to support arbitrary types.

Define "arbitrary."  In particular, examine MpiTypeTraits and see if it has the coverage you want.

> Also, I wonder where these wrappers should live. It doesn't matter if it's Teuchos or Tpetra, but they need to be in one place.

If you would like to put the implementation of gatherv in Teuchos, along with a unit test, please feel free to do so.

**Comment by kddevin** [comment]
Zoltan2 calls something called Teuchos::gatherv.  It is in Teuchos_CommHelpers.hpp.
Is that what you want?

**Comment by dridzal** [comment]
That would be nice, but it appears that the methods is not implemented ... here is the function body:

  // // FIXME (mfh 16 Apr 2013) We also have to redo the displacements.

  // ConstValueTypeSerializationBuffer<Ordinal,Packet>
  //   charSendBuffer (sendCount, sendBuf);
  // ValueTypeSerializationBuffer<Ordinal,Packet>
  //   charRecvBuffer (totalRecvCount, recvBuf);
  // comm.gatherv (charSendBuffer.getBytes (),
  //               charSendBuffer.getCharBuffer (),
  //               charRecvBuffer.getBytes (),
  //               charRecvBuffer.getCharBuffer (),
  //               root);
  TEUCHOS_TEST_FOR_EXCEPTION(true, std::logic_error,
    "Teuchos::gatherv: The general case is not implemented.");

It appears commented out.  Have I missed something?

**Comment by kddevin** [comment]
Looks as if there are implementations for various sized integers (short, long long, long, int, etc.) in Teuchos_CommHelpers.cpp.  Adding various sized floats would be straightforward.  User-defined data types would be more difficult. 

Perhaps this would be a good task for our Tech-X collaborators?  I don't know fully their commitments for this FY.  @jmwille would know.

**Comment by mhoemmen** [comment]
> It appears commented out. Have I missed something?

There is a partial implementation of a gatherv wrapper in Tpetra.  I was proposing that you move this into a public namespace (either Teuchos or Tpetra) and add a unit test.  If you provide a unit test, I'll be happy to assess it.
