### ISSUE TITLE
STK: failures in Albany-LCM nightlies

### ISSUE THREAD

**Issue by ikalash** [trilinos/Trilinos#10060]
A number of our tests in Albany-LCM are failing, I presume due to changes to STK, since no changes to Albany-LCM have been made recently: 

https://sems-cdash-son.sandia.gov/cdash/viewTest.php?onlyfailed&buildid=27569

The errors look like this:

```

p=0: *** Caught standard std::exception of type 'std::logic_error' :

 Requirement( f[0] == rawField ) FAILED
 Error occurred at: trilinos-install-serial-clang-release/include/stk_mesh/base/MetaData.hpp:802
  0# stk::output_stacktrace(std::ostream&) in /home/lcm/LCM/trilinos-install-serial-clang-release/lib/libstk_util_util.so.13
  1# stk::mesh::Field<double, void, void, void, void, void, void, void>& stk::mesh::MetaData::declare_field<stk::mesh::Field<double, void, void, void, void, void, void, void> >(stk::topology::rank_t, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int) in /home/lcm/LCM/lcm-build-serial-clang-release/src/disc/stk/libalbanySTK.so
  2# Albany::MultiSTKFieldContainer<true>::initializeSTKAdaptation() in /home/lcm/LCM/lcm-build-serial-clang-release/src/disc/stk/libalbanySTK.so
  3# Albany::MultiSTKFieldContainer<true>::MultiSTKFieldContainer(Teuchos::RCP<Teuchos::ParameterList> const&, Teuchos::RCP<stk::mesh::MetaData> const&, Teuchos::RCP<stk::mesh::BulkData> const&, int, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, int, Teuchos::RCP<Albany::StateInfoStruct> const&, Teuchos::Array<Teuchos::Array<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, Teuchos::Array<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > const&) in /home/lcm/LCM/lcm-build-serial-clang-release/src/disc/stk/libalbanySTK.so
  4# Albany::GenericSTKMeshStruct::SetupFieldData(Teuchos::RCP<Teuchos::Comm<int> const> const&, int, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, Teuchos::RCP<Albany::StateInfoStruct> const&, int) in /home/lcm/LCM/lcm-build-serial-clang-release/src/disc/stk/libalbanySTK.so
  5# Albany::IossSTKMeshStruct::setFieldAndBulkData(Teuchos::RCP<Teuchos::Comm<int> const> const&, Teuchos::RCP<Teuchos::ParameterList> const&, unsigned int, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, Teuchos::RCP<Albany::StateInfoStruct> const&, unsigned int, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, Teuchos::RCP<Albany::StateInfoStruct>, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Teuchos::RCP<Albany::StateInfoStruct> > > > const&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > > > const&) in /home/lcm/LCM/lcm-build-serial-clang-release/src/disc/stk/libalbanySTK.so
  6# Albany::DiscretizationFactory::createDiscretization(unsigned int, std::map<int, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::less<int>, std::allocator<std::pair<int const, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > > > const&, Teuchos::RCP<Albany::StateInfoStruct> const&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, Teuchos::RCP<Albany::StateInfoStruct>, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Teuchos::RCP<Albany::StateInfoStruct> > > > const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > > > const&, Teuchos::RCP<Albany::RigidBodyModes> const&) in /home/lcm/LCM/lcm-build-serial-clang-release/src/libalbanyLib.so
  7# Albany::Application::createDiscretization() in /home/lcm/LCM/lcm-build-serial-clang-release/src/libalbanyLib.so
  8# Albany::Application::Application(Teuchos::RCP<Teuchos::Comm<int> const> const&, Teuchos::RCP<Teuchos::ParameterList> const&, Teuchos::RCP<Thyra::VectorBase<double> const> const&, bool) in /home/lcm/LCM/lcm-build-serial-clang-release/src/libalbanyLib.so
  9# Albany::SolverFactory::createAlbanyAppAndModel(Teuchos::RCP<Albany::Application>&, Teuchos::RCP<Teuchos::Comm<int> const> const&, Teuchos::RCP<Thyra::VectorBase<double> const> const&, bool) in /home/lcm/LCM/lcm-build-serial-clang-release/src/libalbanyLib.so
 10# Albany::SolverFactory::createAndGetAlbanyApp(Teuchos::RCP<Albany::Application>&, Teuchos::RCP<Teuchos::Comm<int> const> const&, Teuchos::RCP<Teuchos::Comm<int> const> const&, Teuchos::RCP<Thyra::VectorBase<double> const> const&, bool) in /home/lcm/LCM/lcm-build-serial-clang-release/src/libalbanyLib.so
 11# main in /home/lcm/LCM/lcm-build-serial-clang-release/src/Albany
 12# 0x00007F7FA5585560 in /usr/lib64/libc.so.6
 13# __libc_start_main in /usr/lib64/libc.so.6
 14# _start in /home/lcm/LCM/lcm-build-serial-clang-release/src/Albany
 
 Error: Re-registration of field 'failure_state' with a different template type is not allowed.
```
I am guessing some convention in STK changed?  Could someone please figure out the cause of the issue so we could fix it?

Tagging @lxmota , who is also interested in this problem.

**Comment by alanw0** [comment]
Hi @ikalash, yes we just tightened up a requirement in stk, couldn't figure out how to do it gently. stk used to allow a field to be registered multiple times with different template parameters, which led to bad and undefined behavior. Now it throws if that happens. Please remind me of the github page for downloading Albany and I'll take a look and see if this is a real error with the way 'failure_state' is being defined.

**Comment by alanw0** [comment]
ok I found albany, under github.com/sandialabs/albany. For some reason I had thought it was under snlcomputation.

**Comment by lxmota** [comment]
@alanw0 @ikalash This seems to be specific to LCM (solid mechanics component of Albany), which is here:

https://github.com/sandialabs/LCM

**Comment by alanw0** [comment]
@lxmota thanks, I'll grab LCM and take a look.

**Comment by ikalash** [comment]
Thanks @alanw0 !  Do you still want build instructions?  If so, I can provide them.

**Comment by alanw0** [comment]
@ikalash, yes please do give me some build instructions, it looks like we will need to run the failing test to diagnose what is going on. Thanks.

**Comment by ikalash** [comment]
@alanw0 : sorry about the delay - I was in meetings until now.  For CEE, please use the following scripts  (note that they are in the Albany repo, not LCM, but they should work with LCM): 

- Source modules: https://github.com/sandialabs/Albany/blob/master/doc/dashboards/cee-compute011.sandia.gov/sems-gcc-modules.sh
- Configure, make and make install Trilinos using this configure script: https://github.com/sandialabs/Albany/blob/master/doc/dashboards/cee-compute011.sandia.gov/do-cmake-trilinos-mpi-sems-gcc
- Edit the attached Albany configure script to point to your Trilinos install, then configure and make.  

[do-cmake-albany-mpi-tpetra.txt](https://github.com/trilinos/Trilinos/files/7811017/do-cmake-albany-mpi-tpetra.txt)

The problematic tests will be in the Albany/build/tests/LCM/ACE and Albany/build/tests/Thermal3D directories.  

Some users have reported weird errors on some of the newer cee-compute nodes (e.g., cee-compute030) so it may be better to use the compute nodes with the 20s in their name, e.g., cee-compute020 or cee-compute021.

**Comment by alanw0** [comment]
Thanks @ikalash, I got the build kicked off last night and we will try to get it figured out today.

**Comment by ikalash** [comment]
Sounds great @alanw0 , thanks in advance!

**Comment by alanw0** [comment]
When running the test Ace_Cuboid, the field 'failure_state' is being declared with type `stk::mesh::Field<double,QPTag>` in Albany_GenericSTKFieldContainer_def.hpp and then later is declared with type `stk::mesh::Field<double>` in Albany_MultiSTKFieldContainer_def.hpp.
Before, this was allowed by stk (would create both as separate fields with the same name) but behavior was undefined when requesting the field by name. So it was unclear which of those fields you would be accessing later when writing to it or reading from it. We determined that behavior was erroneous, and that's why it is now throwing.

Is it feasible to make failure_state have consistent template-parameters in the LCM code-base?

**Comment by lxmota** [comment]
Yes, I'll change the code to make it consistent. Thank you for catching this issue.

**Comment by ikalash** [comment]
Thanks @lxmota !  In case it helps, I looked a little bit at the code and I think the problem is "failure_state" is being registered as a QP field here: https://github.com/sandialabs/LCM/blob/master/src/disc/stk/Albany_GenericSTKFieldContainer_Def.hpp#L97 whereas it is a scalar field here: https://github.com/sandialabs/LCM/blob/master/src/disc/stk/Albany_MultiSTKFieldContainer_Def.hpp#L304 (SFT represents scalar field).  I'm a bit confused though as to why the code in Albany_GenericSTKFieldContainer_Def.hpp thinks failure_field is a QP type, given that you seem to set a cell_scalar layout (not qp_scalar) for the field here: https://github.com/sandialabs/LCM/blob/master/src/LCM/models/J2Erosion_Def.hpp#L87 .

**Comment by alanw0** [comment]
@ikalash and @lxmota let me know if you have difficulties with this.
We have had requests to eliminate the extra template-parameters (leaving just the basic type parameter), meaning every field would be simply `stk::mesh::Field<T>`. We have some prototype work exploring this now. This would be a huge improvement, eliminating issues such as this throw entirely. The challenge of course is finding a "gentle" way to do such a change. We'll keep you posted, and try not to rip the rug out from under you.
