### ISSUE TITLE
ShyLu:  remove calls to Xpetra deprecated code from FROSch

### ISSUE THREAD

**Issue by mperego** [trilinos/Trilinos#10078]
## Enhancement
@trilinos/shylu 

There is a call to DeviceLocalView() on an Xpetra multivector, without providing any of the Xpetra::Access::zyx read/write structs:
https://github.com/trilinos/Trilinos/blob/master/packages/shylu/shylu_dd/frosch/src/CoarseSpaces/FROSch_CoarseSpace_def.hpp#L223
The code fails when Trilinos is built with
```
-D Tpetra_ENABLE_DEPRECATED_CODE=OFF  \
-D Xpetra_ENABLE_DEPRECATED_CODE:BOOL=OFF \
```

This error appears when building Albany (see https://github.com/sandialabs/Albany/pull/776), not sure whether Trilinos FROSch tests cover this (we didn't enable them when building Trilinos).

@iyamazaki , @searhein can you look into that?

**Comment by cgcgcg** [comment]
Should be fixed by #10079
