### ISSUE TITLE
Aztec:   recursive residual indicates convergence  though the true residual is too large.

### ISSUE THREAD

**Issue by ztdepztdep** [trilinos/Trilinos#10088]
I am solving a Helmholtz problem with the multiblock spectral collocation method based on the Aztec gmres method and ifpack as preconditioner and I met the following problem. 

`                ***** Problem: Epetra::CrsMatrix
                ***** Preconditioned GMRES solution
                ***** Epetra::Object
                ***** No scaling
                *******************************************************

                iter:    0           residual = 3.583948e+17
                iter:    1           residual = 4.674243e+10
                iter:    2           residual = 2.155970e+10
                iter:    3           residual = 1.748742e+10
                iter:    4           residual = 3.926105e+08
                iter:    5           residual = 6.951430e+05
                iter:    6           residual = 6.092744e+05
                iter:    7           residual = 9.741615e+01
                iter:    8           residual = 6.860595e+01
                iter:    9           residual = 4.608118e+00
                iter:   10           residual = 4.119926e-02
                iter:   11           residual = 5.347023e-03
                iter:   12           residual = 4.372669e-05
                iter:   13           residual = 4.316654e-05
                iter:   14           residual = 1.909257e-11
                iter:   15           residual = 2.705443e-12

        *************************************************************

        Warning: recursive residual indicates convergence
        though the true residual is too large.

        Sometimes this occurs when storage is overwritten (e.g. the
        solution vector was not dimensioned large enough to hold
        external variables). Other times, this is due to roundoff. In
        this case, the solution has either converged to the accuracy
        of the machine or intermediate roundoff errors occurred
        preventing full convergence. In the latter case, try solving
        again using the new 
        Solver:                 gmres
        number of iterations:   15

solution as an initial guess.
        Actual residual =  1.4317e+02   Recursive residual =  2.7054e-12
`
 The actual residual is large compared to the recursive residual of 2.7e-12.  bicgstab metod diverge directly. 

Could you please give me some suggestions?

**Comment by cgcgcg** [comment]
How big is the problem? The implicit residual seems to converge pretty fast. That makes me think that the problem isn't that big. On the other hand, the initial residual is gigantic. What kind of preconditioner are you using?

**Comment by ztdepztdep** [comment]
I use ILUk(2) preconditioner. The problem size is not big.  we have 4 blocks each block has  an order of 16 . 
The order of Checbyshev polynomial is 16 which means each point has 32 neighbors for 2D possion  roblems.

**Comment by cgcgcg** [comment]
Since it's a small problem, could you have a look at the spectrum and make sure it's non-singular? Have you checked the condition number? Have you tried running without the preconditioner?

**Comment by cgcgcg** [comment]
No response. Please reopen if this is still an issue.
