### ISSUE TITLE
Thyra: Add support for x_dot_dot

### ISSUE THREAD

**Issue by rppawlo** [trilinos/Trilinos#1008]
We are adding second time derivative support to the new Tempus time integration package. This requires the model evaluator to support x_dot_dot and a corresponding multiplier (omega) for use in W evaluation:

W= omega*D(f)/D(x_dot_dot)+alpha*D(f)/D(x_dot)+beta*D(f)/D(x)

**Comment by rppawlo** [comment]
@ikalash @ccober6 @trilinos/thyra

**Comment by bartlettroscoe** [comment]
Can we switch to the names:

* W_x_coeff (currently beta)
* W_x_dot_coeff (currently alpah)
* W_x_dot_dot_coeff

?

That is what we should have done from the version beginning.  We can deprecate the old alpha and beta InArgs.

Sound reasonable?

I will commit a cleaned-up and better organized set of Thyra ME files and documentation to better support more additions like this in support of #795.

Is this really already being worked on?

**Comment by ikalash** [comment]
@bartlettroscoe  Would this require all applications that use thyra  ME to change the names of alpha, beta, etc to the new ones you are proposing?

**Comment by rppawlo** [comment]
I was leaving alpha and beta as is. Only adding omega for the coefficient on x_dot_dot. I'd really like to avoid forcing codes to make changes for this addition. And yes - I am actively working on this - have already made the changes to the base class. I am working on modifications to the decorator classes now. Will make this a pull request when finished.

**Comment by bartlettroscoe** [comment]
> Would this require all applications that use thyra ME to change the names of alpha, beta, etc to the new ones you are proposing?

No, we would just deprecate `alpha` and `beta` but they would still be supported (but would emit deprecated warnings when used).   I may just do this while I work on #795.

**Comment by rppawlo** [comment]
@bartlettroscoe what is your time frame for this? The x_dot_dot support is needed asap. I can add the new flags above as well unless you are actively working this now.

**Comment by bartlettroscoe** [comment]
@rppawlo, go ahead and finish and push.  I will deal with the conflicts in my end.

**Comment by rppawlo** [comment]
ok. Since the coefficient on x_dot_dot is new, I will change from "omega" to "W_x_dot_dot_coeff".
