### ISSUE TITLE
Nalu diffs; failed bisect due to file INSTALL/Kokkos-Kernels

### ISSUE THREAD

**Issue by spdomin** [trilinos/Trilinos#10086]
## Bug Report
@trilinos/\<PackageName\>

### Description
We have a number of Nalu diffs this morning. However, when I attempt to perform a bisect, I am noting a failed installation:

CMake Error at packages/kokkos-kernels/src/cmake_install.cmake:45 (file):
  file INSTALL cannot find
  "/home/spdomin/gitHubWork/nightlyBuildAndTest/Trilinos/packages/kokkos-kernels/src/blas/impl/KokkosBlas_util.hpp":

I am currently on the following SHA1 (although, this does not look related to the above):

commit af95cd360c3007eabf56890e6dcbb20af8753ef0 (HEAD)
Author: Eric T. Phipps <etphipp@sandia.gov>
Date:   Tue Jan 11 12:54:02 2022 -0700

    Tempus:  Fix mistake in merge

Just wondering how I should proceed with a bisect?

### Steps to Reproduce
Good:
NaluCFD/Nalu SHA1: 11940e2700d4b94d46b75efe572f2579148c098f
Trilinos/develop SHA1: ea1e91e82b360726c568798ae30b14888a0015d0

Bad:

NaluCFD/Nalu SHA1: 11940e2700d4b94d46b75efe572f2579148c098f
Trilinos/develop SHA1: be781e8c94b085ff3e90ae0a6919016a31659426

**Comment by jhux2** [comment]
@trilinos/kokkos-kernels @ndellingwood @srajama1

**Comment by jhux2** [comment]
@spdomin There aren't a lot of commits between `ea1e91e` and `be781e8`:

https://github.com/trilinos/Trilinos/commits/develop

Looking in that range, one possible reason for the diff could be https://github.com/trilinos/Trilinos/commit/527e5c342119758cf22409a69c4b2fa508c0a12c which came from PR #10028.  Are you able to revert that one PR to see if the diffs go away?

**Comment by jhux2** [comment]
Also, how significant are the diffs?

**Comment by spdomin** [comment]
@jhux2, typical small diffs that we see from Trilinos changes now and then:

dgNonConformalThreeBlade........... FAILED:   s  max diff:  .00000010000000000000243069453454

However, localized to a certain subset of tests. Most all of our regression tests use Muelu + GMRES. No obvious pattern, however, I have not studied the set of tests and capability touched.

The bisect noted @brian-kelley 

commit 86e35b6684e7bd28b57b97078d012cd5a730d8ba
Author: Brian Kelley <bmkelle@sandia.gov>
Date:   Wed Dec 15 13:48:09 2021 -0700

    Patch in Kokkos Kernels #1204 to fix #9856
    
    Remove runtime-sized array reductions from BLAS-1 MV functions. Where
    possible, use the same approach as dot-based GEMM (have multiple teams
    work on a reduction, and use atomics to contribute to the final result).
    If that is not possible, just process each column one at a time. Both
    approaches give better performance than array reductions, and also work
    for any number of columns (e.g. >180 for Cuda, which failed before).

 .../src/blas/impl/KokkosBlas1_dot_mv_impl.hpp      | 704 +++-----------------
 .../src/blas/impl/KokkosBlas1_dot_spec.hpp         | 733 ++++++++++++---------
 .../src/blas/impl/KokkosBlas1_iamax_impl.hpp       | 265 ++------
 .../src/blas/impl/KokkosBlas1_nrm1_impl.hpp        | 283 +++-----
 .../src/blas/impl/KokkosBlas1_nrm2_impl.hpp        | 308 ++++-----
 .../src/blas/impl/KokkosBlas1_nrm2w_impl.hpp       | 322 ++++-----
 .../src/blas/impl/KokkosBlas1_nrminf_impl.hpp      | 224 ++-----
 .../src/blas/impl/KokkosBlas1_sum_impl.hpp         | 263 +++-----
 .../blas/impl/KokkosBlas3_gemm_dotbased_impl.hpp   | 211 +++---
 .../src/blas/impl/KokkosBlas_util.hpp              | 106 +++
 10 files changed, 1290 insertions(+), 2129 deletions(-)
 create mode 100644 packages/kokkos-kernels/src/blas/impl/KokkosBlas_util.hpp

@wjhorne, please also tune in and see if you can help if the Trilinos team poses any questions.

**Comment by spdomin** [comment]
Oh, this is a standard gcc 8.4.0 open MPI 4.0.5 build.

86e35b6684e7bd28b57b97078d012cd5a730d8ba is the first bad commit
commit 86e35b6684e7bd28b57b97078d012cd5a730d8ba

**Comment by jhux2** [comment]
I could absolutely believe that BLAS changes would lead to small differences in dot products due to order of operations, which would then percolate up to GMRES and elsewhere.  I'll let the Kokkos-Kernels team weigh in, though.

**Comment by cgcgcg** [comment]
In order to merge #10028, some tests in Anasazi had to be modified, since computing the same norm in slightly different ways didn't give identical results anymore. Instead, they now had an O(eps) difference.

**Comment by spdomin** [comment]
As long as everyone agrees that the new changes are both 1) correct, and 2) leaves the code base in a more desirable state, then we are happy to re-bless and move forward.

**Comment by jhux2** [comment]
> As long as everyone agrees that the new changes are both 1) correct, and 2) leaves the code base in a more desirable state, then we are happy to re-bless and move forward.

I agree with both.

**Comment by spdomin** [comment]
Great. @wjhorne could you please Robles’s and issue a PR? Thanks to all.

**Comment by wjhorne** [comment]
I'll get the PR through soon, thanks all for the quick turn around on this

**Comment by spdomin** [comment]
We have the PR part of the code base. Once we have a clean nightly result, we can close this ticket. Stay tuned. 

https://github.com/NaluCFD/Nalu/pull/571

**Comment by spdomin** [comment]
Blast. Something non ideal is happening:

Yesterday: 81% tests passed, 14 tests failed out of 75 

Today: 61% tests passed, 29 tests failed out of 75

it’s not clear if Wyatt’s code change was off or there are new Trilinos changes.

**Comment by wjhorne** [comment]
I’ll check it here again in a bit. I did verify a clean set of tests before the pr but maybe something was off on my end in the install

**Comment by wjhorne** [comment]
I believe the additional diffs are not another issue on the Trilinos side. There was a simple Trilinos install issue on my end that I have identified that caused the issue. I fixed it and will submit a re-bless PR after I have double checked it all for certainty. Apologies for the trouble.

**Comment by spdomin** [comment]
Wyatt. Please 1) revert the old commit (I suppose I can do that - whoever is first), 2) re-run the test suite to ensure you see 14 fails, and 3) re-bless only 14 tests. If you don't revert, then you will have to accept all 29 - facilitating churn in the regression test and a possibly slip in missing a diff.

**Comment by spdomin** [comment]
After PR: https://github.com/NaluCFD/Nalu/pull/573

We note: 100% tests passed, 0 tests failed out of 14 on,

Nalu GIT Commit SHA: 614a9e41180f87d782482b571a52ee922cb278d0
Trilinos Version: 13.1-ga5a5bf9a6f1
