### ISSUE TITLE
MueLu: memory leaks in structured grid code

### ISSUE THREAD

**Issue by jhux2** [trilinos/Trilinos#10090]
## Bug Report
@lucbv @pohm01 @mayrmt @rstumin 

### Description
The nightly Valgrind checks aren't clean for some of the structured grid tests.

See [the dashboard](https://testing.sandia.gov/cdash/index.php?project=Trilinos&subproject=MueLu&filtercount=2&showfilters=0&filtercombine=and&field1=groupname&compare1=64&value1=CLEAN&field2=block&field2count=1&field2field1=groupname&field2compare1=64&field2value1=PULL%20REQUEST#) in the Dynamic Analysis section.

**Comment by cgcgcg** [comment]
Fixed in PR #10186.
