### ISSUE TITLE
Zoltan_Malloc (.../trilinos/packages/zoltan/src/all/all_allo.c,194) No space on proc 0 - number of bytes requested = 18446744068066390400

### ISSUE THREAD

**Issue by jbakosi** [trilinos/Trilinos#1010]
I get the above error from `Zoltan/Zoltan2` when requesting 2 partitions on a single MPI rank using OpenMPI 2.0.2. No problem using OpenMPI 1.10.2.

Here is a trace:

```
Zoltan_Malloc (from .../trilinos/packages/zoltan/src/all/all_allo.c,194) No space on proc 0 - number of bytes requested = 18446744068066390400
137: [0] Zoltan ERROR in Zoltan_Invert_Lists (line 250 of .../trilinos/packages/zoltan/src/lb/lb_invert.c):  Insufficient memory.
137: [0] Zoltan ERROR in Zoltan_LB (line 582 of .../trilinos/packages/zoltan/src/lb/lb_balance.c):  Error building return arguments; -2 returned by Zoltan_Compute_Destinations
137:
137: terminate called after throwing an instance of 'std::runtime_error'
137:   what():  0: .../include/Zoltan2_AlgZoltan.hpp,408
137: 0: error: Zoltan LB_Partition
```

The problem is triggered by `Zoltan2::PartitioningProblem<tk::zoltan::GeometricMeshElemAdapter<Zoltan2::BasicUserTypes<double, unsigned long, unsigned long> > >::solve()` at https://github.com/quinoacomputing/quinoa/blob/master/src/LinSys/ZoltanInterOp.C#L151.

Please let me know if/how I can help debugging this.

**Comment by mhoemmen** [comment]
@trilinos/zoltan

**Comment by kddevin** [comment]
@trilinos/zoltan2 
@jbakosi : thanks for reporting this problem.  I am looking for a machine here that has OpenMPI 2.0.2 installed so that I can try to reproduce and fix this error.

In the meantime:  Your error report shows that Zoltan2 is templated with local ordinal type = size_t.  In general, Trilinos prefers signed values for local ordinal type.  Would it be difficult to try your test with a signed local ordinal type?

**Comment by jbakosi** [comment]
Thanks, @kddevin, for the suggestion. I have templated `GeometricMeshElemAdapter` on `long` now and I still get the following

```
Zoltan_Malloc (from .../trilinos/packages/zoltan/src/all/all_allo.c,194) No space on proc 0
 - number of bytes requested = 18446744068067373824
137: [0] Zoltan ERROR in Zoltan_Invert_Lists (line 250 of .../trilinos/packages/zoltan/src/lb/lb_invert.c):  Insufficient memory.
137: [0] Zoltan ERROR in Zoltan_LB (line 582 of .../trilinos/packages/zoltan/src/lb/lb_balance.c):  Error building return arguments; -2 returne
d by Zoltan_Compute_Destinations                 
137:                                             
137: terminate called after throwing an instance of 'std::runtime_error'
137:   what():  0: .../include/Zoltan2_AlgZoltan.hpp,380
137: 0: error: Zoltan LB_Partition               

137:   [0:8] Zoltan2::PartitioningProblem<tk::zoltan::GeometricMeshElemAdapter<Zoltan2::BasicUserTypes<double, long, long> > >::solve(bool)+0x3766  [0x7ffff588bea2]
137:   [0:9] tk::zoltan::geomPartMesh(tk::ctr::PartitioningAlgorithmType, std::array<std::vector<double, std::allocator<double> >, 3ul> const&, std::vector<long, std::allocator<long> > const&, unsigned long, int)+0x71a  [0x7ffff5802a42]
```

I have also tried this on another test case which attempts to partition by 3 (instead of 2) parts on a single MPI rank and for that I get a different error:
```
[0] Zoltan ERROR in Zoltan_Comm_Do_Post (line 180 of .../trilinos/packages/zoltan/src/Utilities/Communication/comm_do.c):  nrecvs not zero, but recv_data = NULL
141: [0] Zoltan ERROR in Zoltan_Invert_Lists (line 211 of .../trilinos/packages/zoltan/src/lb/lb_invert.c):  Error ZOLTAN_FATAL returned from Zoltan_Comm_Do.
141: [0] Zoltan ERROR in Zoltan_Comm_Do_Post (line 180 of .../trilinos/packages/zoltan/src/Utilities/Communication/comm_do.c):  nrecvs not zero, but recv_data = NULL
141: [0] Zoltan ERROR in Zoltan_Invert_Lists (line 223 of .../src/trilinos/packages/zoltan/src/lb/lb_invert.c):  Error ZOLTAN_FATAL returned from Zoltan_Comm_Do.
141: [0] Zoltan ERROR in Zoltan_Comm_Do_Post (line 180 of .../trilinos/packages/zoltan/src/Utilities/Communication/comm_do.c):  nrecvs not zero, but recv_data = NULL
141: [0] Zoltan ERROR in Zoltan_Invert_Lists (line 238 of .../trilinos/packages/zoltan/src/lb/lb_invert.c):  Error ZOLTAN_FATAL returned from Zoltan_Comm_Do.
141: [0] Zoltan ERROR in Zoltan_LB (line 582 of .../trilinos/packages/zoltan/src/lb/lb_balance.c):  Error building return arguments; -1 returned by Zoltan_Compute_Destinations
141:
141: terminate called after throwing an instance of 'std::runtime_error'
141:   what():  0: .../include/Zoltan2_AlgZoltan.hpp,380
141: 0: error: Zoltan LB_Partition
```

**Comment by kddevin** [comment]
@jbakosi Thanks for confirming that the problem persists with different template combinations.

Which compiler are you using in your experiments with both versions of OpenMPI?
We have seen several problems with Intel 17.  For example, #600 .

**Comment by jbakosi** [comment]
Gcc 6.3.0, clang 3.8, and intel 17.0.1 all work with OpenMPI 1.10.2.

I only tried OpenMPI 2.0.2 with gcc 6.3.0 that fails.

**Comment by kddevin** [comment]
Using the compilers and libraries to which I have access, I ran Zoltan's and Zoltan2's tests with OpenMPI 2.0.1 and intel 17.0.098.  They all passed, in both DEBUG and RELEASE mode.

@jbakosi Do you see the same problem with a DEBUG build (-O0)?  Are you able to test with OpenMPI 2.0.2 and intel 17.0.1?  Is there a system at your site that I can access so that I can use your configuration?

**Comment by jbakosi** [comment]
I have tested with OpenMPI 2.0.2 (the system-wide default in [debian/testing](https://packages.debian.org/stretch/libopenmpi2)) + GCC 6.3.0 (also the system-wide default) with DEBUG and that still fails.

I have also tested with OpenMPI 2.0.2 + Intel compiler 17.0.1 (20161005), and my tests, somewhat surprisingly, pass. Since I could _not_ reproduce the problem with the Intel compiler, I am suspicious that the culprit is g++ 6.3.0. I could not test using g++ 5.4.0 (another version available system-wide on debian/testing) due to linking problems.

Since both g++ 6.3.0 and OpenMPI 2.0.2 are very new (and their combination probably not as well tested yet as earlier versions), I suspect this problem (whatever it is) might just go away eventually, but if you want to investigate further, I have also created a docker image with a default debian/testing install. You can reproduce the error the following way:
```
$ docker pull jbakosi/zoltan
$ docker run -ti jbakosi/zoltan
<inside-the-image>$ cd /quinoa; ctest -R inciter:asynclogic_u0.9_pe1 -V
```

Inside the image you can see how Trilinos and Zoltan2 was built in `/quinoa/tpl/build/trilinos` and their install is in `/quinoa/tpl/install/gnu-x86_64`. The Zoltan2-client code that triggers the error is in `/quinoa/src/LinSys/ZoltanInterOp.C`.

Please let me know if I can help with the image, but I'm not sure if we should spend too much more time hunting this problem down, as we are struggling to reproduce the problem using anything else than OpenMPI 2.0.2 (which a pre-release at this point) and g++ 6.3.0.

**Comment by jbakosi** [comment]
I can no longer reproduce this problem (a couple of months later) as it failed originally: using the system-wide OpenMPI 2.0.2 and GCC on debian/testing. Closing.

**Comment by kddevin** [comment]
Thanks for the update,  @jbakosi
