### ISSUE TITLE
MueLu:  optimization question

### ISSUE THREAD

**Issue by Adrian-Diaz** [trilinos/Trilinos#10119]
## Question
@trilinos/\<muelu\>

Greetings,

I noticed in the user guide, https://trilinos.github.io/pdfs/mueluguide.pdf, that I hadn't tried two options that might improve performance; turning on single reduction in Belos and reusing my matrix graph since it never changes.

Regarding the single reduction, is this turned on by default? if not is there an example paramlist doing so?

As for the reuse I added Parameter  name="reuse: type"  type="string"   value="S" to my list.  What I'm unclear of is how to take advantage of reuse in the context of the Driver routines in the examples. My knee jerk reaction was to preserve the memory for the Hierarchy and the Preconditioner object and keep feeding it in every iteration . However that didn't seem to change setup time. Is there another step to that?

Many thanks for any help,

Adrian Diaz

**Comment by cgcgcg** [comment]
Single reduction is off by default. You can pass "Use Single Reduction" = true to BelosBlockCG.

How are you creating the MueLu preconditioner? Are you using `CreateXpetraPreconditioner`, or the Stratimikos interface?

**Comment by Adrian-Diaz** [comment]
Thanks for the info. I'm using the Driver Core routine "PreconditionerSetup" which seems to use the xpetra constructor for the Hierarchy H, I'm actually not sure what its doing with the preconditioner pointer Prec. Maybe it was never being used; I just mirrored the Driver example and passed both H and Prec in.

**Comment by cgcgcg** [comment]
Oh, are you using this:
https://github.com/trilinos/Trilinos/blob/5a67b70fb3816e1cea26554c650b4dc7ca26747d/packages/muelu/test/scaling/Driver.cpp#L468

**Comment by Adrian-Diaz** [comment]
Yes that one.

**Comment by cgcgcg** [comment]
Ok. Yeah, that one isn't very transparent. What you probably want to do is this:
https://github.com/trilinos/Trilinos/blob/5a67b70fb3816e1cea26554c650b4dc7ca26747d/packages/muelu/test/scaling/DriverCore.hpp#L211-L217
(Remove line 216, that's not needed.)
That should set up a MueLu::Hierarchy object for you.

Once you modify your matrix, you can modify the preconditioner by calling
https://github.com/trilinos/Trilinos/blob/5a67b70fb3816e1cea26554c650b4dc7ca26747d/packages/muelu/adapters/xpetra/MueLu_CreateXpetraPreconditioner.hpp#L187-L196

**Comment by Adrian-Diaz** [comment]
I see, so I only need to create H the first time with 211-217 (minus 216) and then pass it to the ReuseXpetraPreconditioner(A, H) routine for every subsequent iteration with the same matrix graph?

**Comment by cgcgcg** [comment]
Provided that you're actually changing the matrix entries, yes. Otherwise there is no need to change the preconditioner. `ReuseXpetraPreconditioner` will generate output that looks similar to `CreateXpetraPreconditioner`. Depending on what you select for "reuse: type", it can be significantly shorter. This should also be reflected in the timings.

**Comment by Adrian-Diaz** [comment]
Seems that sped things up a bit now. Thanks for the help!
