### ISSUE TITLE
 TriBITS: Specific CXX_FLAGS for FROSch

### ISSUE THREAD

**Issue by searhein** [trilinos/Trilinos#10111]
## Question

Is there a way of adding some CXX_FLAGS only for FROSch, such as

```
-D ShyLU_DDFROSch_CXX_FLAGS:STRING= ...
```
?

**Comment by cgcgcg** [comment]
@bartlettroscoe

**Comment by bartlettroscoe** [comment]
Take a look at "Options can also be targeted to a specific TriBITS package using" at:

* https://docs.trilinos.org/files/TrilinosBuildReference.html#adding-arbitrary-compiler-flags-but-keeping-default-build-type-flags

It is not clear from that documentation if that only works at the parent package level or will also work at the sub-package level as well.  We would have to check.   If it is not supported at the subpackage level, that could be added.  (Which is 95% tests and documentation and 5% actually adding the feature which would likely take 2 lines of CMake code.)

NOTE: In the many years of using TriBITS, I can only think of a few times that people have used this and it was only to work around compiler defects.

**Comment by searhein** [comment]
@bartlettroscoe Thanks for the quick reply!

It worked for `ShyLU_DD_CXX_FLAGS` but it did not for `ShyLU_DDFROSch_CXX_FLAGS`. Hence, it seems to be related to the fact that FROSch is a subpackages. However, it would be great if this would be possible. The reason is that I would like to enable warnings and turn them into errors for compiling FROSch locally. If I did that now, I would get the same behavior for `ShyLU_DDBDDC` because it is mandatory for `ShyLU_DD`.

**Comment by searhein** [comment]
@bartlettroscoe Can you please let me know how to do this on the sub-package level? Thank you!

**Comment by bartlettroscoe** [comment]
> @bartlettroscoe Can you please let me know how to do this on the sub-package level? Thank you!

@searhein, let me take a look.  TriBITS 'master' is now ahead of what is currently synced into Trilinos 'develop' due to the delayed merge of PR #9978 (which I am still working on) but I can create a PR for TriBITS directly against Trilinos 'develop' to implement this and then do the Git mechanics to get this back over to the TriBITS side.

**Comment by bartlettroscoe** [comment]
@searhein, see https://github.com/TriBITSPub/TriBITS/issues/442 and please comment on **option-1** vs. **option-2** there.

**Comment by searhein** [comment]
@bartlettroscoe Thanks. I just commented on it.

**Comment by searhein** [comment]
@bartlettroscoe Is there already an update on this? I would really like to try it out. Thank you!

**Comment by bartlettroscoe** [comment]
@searhein, sorry, my time has been dominated by TriBITSPub/TriBITS#433 and TriBITSPub/TriBITS#443 trying to get PR #9978 merged to Trilinos 'develop'.  I should have time tomorrow to work on `<SubProject>_<LANG>_FLAGS` tomorrow.  Sorry for the delay.

**Comment by searhein** [comment]
@bartlettroscoe No problem, I was just wondering. Thanks.

**Comment by bartlettroscoe** [comment]
@searhein, once the Trilinos #10219 is reviewed, approved, and merged, you should be able to set:

```
  -D ShyLU_DDFROSch_CXX_FLAGS:STRING="<flags-just-for-frosh>"
```

and those flags `<flags-just-for-frosh>` should just be appended to the CMAKE_CXX_FLAGS just for the ShyLU_DDFROSch subpackage.

I have strong extensive automated testing for this in https://github.com/TriBITSPub/TriBITS/pull/453.

**Comment by bartlettroscoe** [comment]
@searhein verified this is fixed in https://github.com/trilinos/Trilinos/pull/10219#issuecomment-1059932129.

Closing as complete
