### ISSUE TITLE
Epetra: Get MPI_Comm from Matrix / Epetra_Comm

### ISSUE THREAD

**Issue by philbucher** [trilinos/Trilinos#10122]
## Question
@trilinos/epetra

Hi, I am wondering if it is possible to get the raw `MPI_Comm` from an `Epetra_FECrsMatrix` or an `Epetra_FEVector`. When constructing the Matrix/ the Vector, I only ever pass `Epetra_MpiComm`. Hence I am sure what type the `Epetra_Comm` is that I get from `matrix.Comm()`.
I checked the documentation, tutorials and the issues here but no luck so far.

The following is working for me, but I was thinking that there might be a nicer/native solution:
~~~c++
const Epetra_Comm& r_epetra_comm = matrix.Comm();
const Epetra_MpiComm& r_epetra_mpi_comm = dynamic_cast<const Epetra_MpiComm&>(r_epetra_comm); // static cast does not work due to virtual inheritance from `Epetra_Comm`
MPI_Comm the_comm = r_epetra_mpi_comm.Comm();
~~~

thanks for the help!

**Comment by jhux2** [comment]
@philbucher As far as I know, there's no other way to do it because `Comm` is an abstract base class.  I would do exactly what you're doing.  Hope this helps.

@trilinos/epetra

**Comment by jhux2** [comment]
@philbucher I'm closing this as answered, but please reopen if that's not the case.

**Comment by philbucher** [comment]
sure thanks a lot for answering!
