### ISSUE TITLE
Trilinos PR Testing is down!

### ISSUE THREAD

**Issue by jwillenbring** [trilinos/Trilinos#10131]
## Bug Report
@trilinos/developers

### Description

Trilinos PR testing is not flowing smoothly due to capacity problems on one machine. Admins are working on it.

**Comment by jwillenbring** [comment]
The framework team has implemented a workaround for now that maintains CUDA testing at a decreased level. We are going to try this to see if we can get PRs flowing again. There may be fallout as the temporary test line up does not include a UVM free build. More details to come.

**Comment by jwillenbring** [comment]
We had our first PR successfully test and merge under the temporary testing configuration:

https://github.com/trilinos/Trilinos/pull/10135

Given that things are moving again, I am going to close this ticket after I file a new one outlining the temporary limitations of the current approach. I will pin that ticket to the top so people can see the PR testing status is modified.

**Comment by jhux2** [comment]
Follow-on ticket is #10147.
