### ISSUE TITLE
Zoltan:  Invalid MPI message tag for intelmpi-2021

### ISSUE THREAD

**Issue by nate945** [trilinos/Trilinos#10139]
## Bug Report
@trilinos/zoltan

### Description
We are currently upgrading Sierra from IntelMPI-2019 to IntelMPI-2021.  As part of this we hit an issue in Zoltan around invalid MPI message tags.  It appears when using IntelMPI-2021 the maximum allowable MPI message tag is 524287.  Zoltan is using a tag of up to 1021981, which crashes the Sierra applications.  The MPI standard appears to state that the maximum tag required to be supported is only 32767.  So I don’t think there is any MPI bug here, IntelMPI-2021 just seems to be more restrictive on allowable tags than any of the previous versions.

The problem is at: 
   packages/zoltan/src/matrix/matrix_distribute.c   Line ~ 222

     int msg_tag = 1021982;

When the MPI_IRecv is posted with that tag later on the application will immediately abort with an MPI error.

### Steps to Reproduce
1. SHA1:  [insert here]
1. Configure script:  [attach here]
1. Configure log:  [attach here]
1. Build log:  [attach here]
1. Input deck:  [attach here]
1. Do this.
1. Do that.
1. Shake fist angrily at computer.
1. Run log:  [attach here]

**Comment by ccober6** [comment]
@nate945 FYI, I have found on an Intel oneAPI site the following [link](https://community.intel.com/t5/Intel-oneAPI-HPC-Toolkit/Intel-MPI-maximum-tag-value-is-much-smaller-with-MLX-provider/td-p/1241310), which shows for Intel MPI the maximum tag value has been decreasing, since 2018.  :(

Also the standard states, "..., the tag upper bound value must be _at least_ 32767.", so `msg_tag` should not be less than 32767?

**Comment by nate945** [comment]
@ccober6 I think for future-proofing the msg_tag used by libraries should be 32767 or less because the standard only guarantees that tag values up 0->32767 must be supported.  

It is also possible to run-time query what the maximum message tag is with:
MPI_Comm_get_attr(MPI_COMM_WORLD, MPI_TAG_UB, &tag_ub, &flag);

I observed the number returned there seems to vary wildly on our different platforms.  Most seem to support max int, intelmpi-2021 being the current lowest at ~500,000

**Comment by ccober6** [comment]
I may be misreading it, but the standard reads, 

> Tag Values
Tag values range from 0 to the value returned for MPI_TAG_UB, inclusive. These values are
guaranteed to be unchanging during the execution of an MPI program. In addition, the tag
upper bound value must be at least 32767. An MPI implementation is free to make the
value of MPI_TAG_UB larger than this; for example, the value 2^30 − 1 is also a valid value
for MPI_TAG_UB.
The attribute MPI_TAG_UB has the same value on all processes of MPI_COMM_WORLD.

So it sounds like tags can be 0 to MPI_TAG_UB, and MPI_TAG_UB must >= 32767.

Like you point out if `msg_tag` can be set via 

`MPI_Comm_get_attr(MPI_COMM_WORLD, MPI_TAG_UB, &tag_ub, &flag);`

we are good.  If not, 32767 might be a good default?

Speaking as a completely non-Zoltan developer!  :)

**Comment by nate945** [comment]
Yes, setting msg_tag to the value of MPI_TAG_UB would work for this case as best as I can tell.  That might be the best solution. 
 The Zoltan function appears to count down from that value to generate a number of unique tags, one for each edge weight.  I'm not sure how many edge weights there could hypothetically be, though I would think usually it would be dozens at most.  One thing I couldn't tell for sure looking that source code is if the current large tag (1021981) was picked for any specific reason, or if it just was just some big kinda random number that likely no other part of the code would use as a message tag.

**Comment by kddevin** [comment]
@nate945  Thanks for finding the problem and proposing a fix.  You are correct that the message tag needs to be larger than the number of edge weights (typically zero or one, but possibly some small number like 2-4).  I will submit a PR with your fix.
