### ISSUE TITLE
ROL:  Update method optimization

### ISSUE THREAD

**Issue by Adrian-Diaz** [trilinos/Trilinos#10130]
## Question
@trilinos/\<rol\>

Greetings,

Up until now I hadn't implemented a proper update method like the one shown in the Version 2.0 document and I was trying to bring down how many times ROL calls my global linear solver (MueLU). Before for compliance and mass I was getting about 500 calls since I had a rather foolproof check to always solve in the value and gradient functions. After I implemented the update function, essentially a xerox copy of what was in the version 2.0 doc with pointer swaps and caching, I started getting about 2070 calls to the linear solver though. I checked and it seems that update was being called with temp (used for FD checks?) over 2000 times and the trial setting for the enumeration around 40. My concern is whether those calls with temp are strictly necessary if I have an implemented gradient? Can I turn them off to speed things up somehow?

Thanks for any help,
Adrian

**Comment by dridzal** [comment]
@Adrian-Diaz : Where are the finite difference computations being called from?  If they are called from the FD checks, then just don't call the FD checks anymore.  Are you possibly referring to the finite difference Hessian-vector products?  Certain algorithms may activate FD hessvecs, and that could be very expensive.  In that case, you should override hessvecs with your own implementations, or use Hessian approximations.

**Comment by Adrian-Diaz** [comment]
There's no FD checks called iteratively after the setup phase of the code. I guess it must be the hessian. What does the Hessian approximation do?

**Comment by Adrian-Diaz** [comment]
I implemented an adjoint sensitivity for the Hessianvec for now. It does seem to be converging a good deal faster and to better final results than before. Is there a strategy to reduce how many times the hessvec method gets called? right now it's about 80% of my run time.

**Comment by dridzal** [comment]
Which optimization method are you using?  Is it Lin-More?  It may be good to paste the iteration history.

**Comment by Adrian-Diaz** [comment]
Seems its Lin-More. I attached the optimization history with an output level of 3
[optimization_history.txt](https://github.com/trilinos/Trilinos/files/7993046/optimization_history.txt)

**Comment by Adrian-Diaz** [comment]
This is the parameter file I'm using by the way
[input_ex01_share.txt](https://github.com/trilinos/Trilinos/files/8005397/input_ex01_share.txt)
.
