### ISSUE TITLE
Panzer: out of bounds error in LIDs

### ISSUE THREAD

**Issue by egphill86** [trilinos/Trilinos#10140]
## Bug Report
@trilinos/panzer

### Description
There's a use case of `getElementLIDs(PHX::View<const int*> cellIds, ArrayT lids)` (I saw this come up specifically with the blocked Tpetra gather solution evaluator) that result in a Kokkos out of bounds error. The function fills a local LIDs array with values from the global LIDs, and within the Kokkos functor, the original code loops over the second dimension with
```
       for(int i=0;i<static_cast<int>(local_lids.extent(1));i++)
         local_lids(cell,i) = global_lids(cellIds(cell),i);
``` 
In the corner case, a local LIDs array is passed in that is padded in the second dimension (i.e. `local_lids.extent(1) > global_lids.extent(1)`). There is a comment in `Panzer_GatherSolution_BlockedTpetra_impl.hpp` explaining this:
```
  // We will use one workset lid view for all fields, but has to be
  // sized big enough to hold the largest elementBlockGIDCount in the
  // ProductVector.
```
The problem is that when `local_lids.extent(1) > global_lids.extent(1)`, the above loop goes out of bounds on `global_lids`.

For proper functioning, we should never have `local_lids.extent(1) < global_lids.extent(1)`, so a simple fix is for the loop to run to `global_lids.extent(1)`.

### Steps to Reproduce
Exposed by a test in Drekar run with `KOKKOS_ENABLE_DEBUG_BOUNDS_CHECK=ON`

**Comment by cgcgcg** [comment]
Could this be related to https://github.com/trilinos/Trilinos/issues/10029? That one should be fixed in develop..

**Comment by egphill86** [comment]
> Could this be related to #10029? That one should be fixed in develop..

I don't think these are related. This bug doesn't seem to really affect much. I have a one line fix. I just don't have push privileges with my civilian github account yet.

**Comment by cgcgcg** [comment]
@egphill86 You should be able to open a PR.

**Comment by egphill86** [comment]
> @egphill86 You should be able to open a PR (from your fork).

Yep, you're right. My bad, I didn't fork. Wanna review @cgcgcg

**Comment by rppawlo** [comment]
This is fixed. Closing.
