### ISSUE TITLE
Trilinos PR testing is running with reduced CUDA testing

### ISSUE THREAD

**Issue by jwillenbring** [trilinos/Trilinos#10147]
## Bug Report
@trilinos/developers

Due to system issues, the base CUDA build current running at pull request time is slightly modified from the typical CUDA build, and there is currently no UVM=off CUDA build running at PR time. Restoring the standard set of builds will require hardware fixes that are in flight.

Longer term, we are looking to migrate these builds to different hardware.

**Comment by bartlettroscoe** [comment]
@trilinos/framework, can you please remind us what internal CDash site that the Trilinos PR CUDA builds on 'vortex' are being pushed to?  I know it is not testing.sandia.gov/cdash/ but I don't remember that the internal CDash site this is.  There is no indications with the autotester output like in https://github.com/trilinos/Trilinos/pull/10216 where this other CDash site is.  The summary says:

**Test Name: _cuda_10.1.243**

* Build Num: 375
* Status: ERROR

but there is no indication where those results are posted to.

**Comment by jhux2** [comment]
@bartlettroscoe I think it's https://trilinos-cdash.sandia.gov.

**Comment by cgcgcg** [comment]
If that is indeed the correct link, then I can't access it. Can we make sure that results are getting posted to a location that all developers can see?

**Comment by e10harvey** [comment]
> If that is indeed the correct link, then I can't access it. Can we make sure that results are getting posted to a location that all developers can see?

Yes. This is only temporary until the system issues (reported via https://github.com/trilinos/Trilinos/issues/10147) affecting the cuda 10.1.105 builds are resolved.

**Comment by jwillenbring** [comment]
Today we enabled a new CUDA 11, UVM off build in PR and dev->master testing. We have seen some issues with this build running to completion after having tested it yesterday and successfully running with 2690 tests passing, 0 failing, and no build failures. We will continue to monitor this new build.

**Comment by jwillenbring** [comment]
There are a couple of tests that are failing randomly with some regularity, and there are some things we would still like to turn on with this build, but the core problem for this issue has been resolved - we have a UVM OFF build back in PR, so I am closing this issue.

**Comment by lucbv** [comment]
@jwillenbring do we have an issue to track the problem with CDash access that is reported by @cgcgcg above? If not I will re-open this issue as not fully completed.

**Comment by cgcgcg** [comment]
I'm not aware of another ticket. Re-opening as not fixed.
