### ISSUE TITLE
Amesos2:  Build errors when turning off deprecated code

### ISSUE THREAD

**Issue by mdmosby** [trilinos/Trilinos#10153]
## Bug Report
@trilinos/Amesos2

### Description
This is for SIERRA. When turning off deprecated code in our Trilinos build, there are errors emanating from `Amesos2_Umfpack_def.hpp` regarding undefined types and/or members.

### Steps to Reproduce
1. SHA1:  1b69d0d6781f716b3cd2198efdf891b37783305e
1. Build log:  [install_2.log](https://github.com/trilinos/Trilinos/files/7989039/install_2.log)

**Comment by jhux2** [comment]
@trilinos/amesos2
