### ISSUE TITLE
Tpetra:  best way to add 3 sparse matrices

### ISSUE THREAD

**Issue by rohany** [trilinos/Trilinos#10158]
## Question
@trilinos/TPetra

I'm looking for the best way to do a 3-way add between some sparse matrices (B, C, D) that creates a new resulting sparse matrices. My code right now is:
```
  auto work = [&]() {
    return Tpetra::MatrixMatrix::add(
      1.0,
      false /* transpose */,
      *B,
      1.0,
      false /* transpose */,
      *Tpetra::MatrixMatrix::add(
         1.0,
         false /* transpose */,
         *C,
         1.0,
         false /* transpose */,
         *D
       )
    );
  };
```
but this seems to be quite slow in comparison to some baselines I'm looking at. My thought is that I'm using an incorrect API or using the API's incorrectly. Thanks for the help!

**Comment by jhux2** [comment]
@trilinos/tpetra @csiefer2

**Comment by rohany** [comment]
Bumping this!

**Comment by csiefer2** [comment]
Do the three matrices have the same sparsity pattern?  Or are the patterns diffewrent?

**Comment by rohany** [comment]
They have different sparsity patterns (and I don't necessarily know the output sparsity pattern).

**Comment by csiefer2** [comment]
If you knew the sparsity pattern in advance it would be faster, for sure.

Are your input arguments fillComplete() before you call add?

**Comment by csiefer2** [comment]
Do they all have the same row distribution?

**Comment by rohany** [comment]
I believe so, they are all loaded in the same way using that function, with the same "distribution" set in the `Teuchos::ParameterList` passed to the loader.

**Comment by csiefer2** [comment]
What architecture are you running on (e.g. Serial, OpenMP, Cuda)?  How many MPI ranks?  How many rows per MPI rank?

**Comment by rohany** [comment]
I run on a dual socket IBM power9, and I find best performance on other applications with 2 ranks per node, and each rank using 20 OpenMP threads. I see somewhat slow performance even for 1 node, so 2 ranks total.

I believe that the data loader uses a default uniform distribution between the two ranks -- I've been running on some matrices from the SuiteSparse dataset, such as https://sparse.tamu.edu/LAW/arabic-2005.

**Comment by csiefer2** [comment]
Not 100% surprised.  OpenMP isn't the most heavily used backend for Trilinos.

@brian-kelley Did you look at w.r.t. performance for the Tpetra add for OpenMP.

**Comment by brian-kelley** [comment]
Yes, the original local add kernel was mostly optimized for KNL + OpenMP. But the Tpetra distributed add has to do more work - if the input column maps don't match, it has to convert local indices to global before adding, and then it computes a new column map for the sum, and finally translates the indices back to local. I can't think of a way around those steps in a general add.

But, for the special case of 3 matrices with the same row map, it would be possible to skip the intermediate C+D addition and just combine B,C,D in global indices. Then sort and merge B+C+D, and compute the column map for that.
