### ISSUE TITLE
Teuchos: add a "make_rcp" for RCP analogous to std::make_shared for std::shared_ptr

### ISSUE THREAD

**Issue by rppawlo** [trilinos/Trilinos#1016]
The standard shared pointer supports a make_shared function. It would be useful if Teuchos::RCP had something similar

@trilinos/teuchos @sslattery @bartlettroscoe

**Comment by mhoemmen** [comment]
Note that make_shared requires C++11, since it uses variadic templates.  That's OK, but we should be careful to protect this function with the HAVE_TEUCHOSCORE_CXX11 macro, so as not to break users who depend on Teuchos building with older compilers.

**Comment by bartlettroscoe** [comment]
Yup, we will definitely add `make_rcp()` and other C++11 features to the Teuchos Memory Management Classes.  The only reason that has not been done up to this point (other than lack of time) is there there was no where I could use them.  For example, are we allowed for Thyra and Stratimikos to require C++11 yet? If not, then when?  It has been hard to get excited about C++11 when I am not allowed to use to in the Trilinos packages that I maintain and support.
