### ISSUE TITLE
SEACAS: build error under Intel 2020.2

### ISSUE THREAD

**Issue by jhux2** [trilinos/Trilinos#10172]
## Bug Report
@trilinos/seacas @gsjaardema @jrood-nrel @paulmullowney 

### Description
Colleagues have reported the following Trilinos build error with Intel 2020.2 and (possibly) with gcc 9.3.0.  This is for Trilinos develop `ef73d14babf`.  (A previous build with `cbcdc150777` succeeded.

```
  >> 3952    /projects/ecp/exawind/exawind-testing/spack-manager/stage/jrood/sp
             ack-stage-trilinos-develop-srdtfhnbtdkqj7o2jp2auisdi4vlpqlr/spack-
             src/packages/seacas/libraries/ioss/src/private_copy_fmt/fmt/core.h
             (1706): error: static assertion failed with "Cannot format a const
              argument."
     3953        static_assert(formattable_const, "Cannot format a const argume
             nt.");
     3954        ^
     3955              detected during:
     3956                instantiation of "auto fmt::v8::detail::make_arg<IS_PA
             CKED,Context,<unnamed>,T,<unnamed>>(T &&)->fmt::v8::detail::value<
             Context> [with IS_PACKED=true, Context=fmt::v8::basic_format_conte
             xt<fmt::v8::detail::buffer_appender<char>, char>, <unnamed>=fmt::v
             8::detail::type::custom_type, T=const fmt::v8::remove_cvref_t<cons
             t fmt::v8::remove_reference_t<fmt::v8::group_digits_view<std::size
             _t={unsigned long}>> &> &, <unnamed>=0]" at line 1848
```

**Comment by jhux2** [comment]
I've verified that by reverting `e2a591dca`, I can get past this error.

**Comment by jrood-nrel** [comment]
Can we get this reverted?

**Comment by jhux2** [comment]
@jrood-nrel PR #10179 is in flight to fix this.

**Comment by jhux2** [comment]
@jrood-nrel I think that's the plan if @gsjaardema can't resolve this today.

**Comment by jhux2** [comment]
@jrood-nrel #10179 should fix this issue.  (Thank you, @gsjaardema!)  I verified that my build on Summit finishes successfully with the PR, and fails without it.  Once you've verified that your builds are clean, could you please close?

**Comment by jrood-nrel** [comment]
This looks fixed, but I can't close it.
