### ISSUE TITLE
error: AZ_extract_comm_info: Received elements must be stored after  all 45 local elements

### ISSUE THREAD

**Issue by ztdepztdep** [trilinos/Trilinos#10170]
I solve my problem with ILU preconditioner and bicgstab solver. But it feeds back the following error.Could you please help me out.

```
AZ_extract_comm_info: Received elements must be stored after
                   all 45 local elements
AZ_extract_comm_info: Received elements must be stored after
                   all 57 local elements
AZ_extract_comm_info: Received elements must be stored after
                   all 57 local elements
```
` 
....
.....
.....
......

    int LevelFill=1;
    int Overlap=0;
    Graph_Diffusion = Teuchos::rcp(new Ifpack_IlukGraph(A_Diffusion->Graph(), LevelFill, Overlap));
    Graph_Diffusion->ConstructFilledGraph();    
    RILU_Diffusion = Teuchos::rcp(new Ifpack_CrsRiluk(*Graph_Diffusion));
    RILU_Diffusion->InitValues(*A_Diffusion);
    RILU_Diffusion->Factor();
          
    Epetra_LinearProblem Problem0(A_Diffusion.get(), &X, &S2);
    AztecOO Solver(Problem0);    
    Solver.SetPrecOperator(RILU_Diffusion.get());
    Solver.SetAztecOption(AZ_solver, AZ_bicgstab);
    Solver.SetAztecOption(AZ_conv, AZ_noscaled);
    Solver.SetAztecOption(AZ_diagnostics, AZ_all);
    Solver.SetAztecOption(AZ_output, AZ_none);
    Solver.Iterate(1000, VarBox_RCP->Tolerance);
`

**Comment by cgcgcg** [comment]
Just a guess, but did you check that your column map is ordered in a way that rank-local ids come before off-rank ids?

**Comment by jhux2** [comment]
@rstumin

**Comment by ztdepztdep** [comment]
> Just a guess, but did you check that your column map is ordered in a way that rank-local ids come before off-rank ids?

Thanks,cgcgcg, Could you pleaes give me some infors about how to check it.

**Comment by cgcgcg** [comment]
@ztdepztdep You could try printing the column map, but maybe an easier way to check would be to run this on a single MPI rank. If the error goes away, then it's worth to investigate further in that direction. 

On a different note: if you are just starting to use Trilinos, it might be better to actually use the new solver stack (Tpetra, Belos, Ifpack2, MueLu, etc) instead of the old one (Epetra, Aztec, Ifpack, ML, etc).

**Comment by ztdepztdep** [comment]
> 

@cgcgcg,  I distribute A only in the row direction. So why the column map will affect the results?

**Comment by cgcgcg** [comment]
A common setting is this: A is square, and distributed by rows. Think about y=Ax. Both x and y will follow the same distribution as the rows of A. Now, unless A is block diagonal, multiplying with A will require some entries of x that are not already present locally. That's where the column map comes in.

**Comment by cgcgcg** [comment]
Please reopen if this is still an issue.
