### ISSUE TITLE
MueLu:  Improving Parallel Scaling

### ISSUE THREAD

**Issue by Adrian-Diaz** [trilinos/Trilinos#10174]
## Question
@trilinos/\<muelu\>

Greetings,

I was benchmarking the solve time for a 3D Elastic matrix with N = 3.9 million. I noticed after about 18 MPI ranks it doesn't really speed up anymore, given my settings anyway, with the following timings being the result:

135 s on 3 MPI ranks, 54 s on 9 MPI ranks, 42s on 18 MPI ranks, 40s on 36 MPI ranks.

So far I've made sure the matrices and vectors are very evenly distributed across the ranks. Is there a strategy to improving the scalability of the solve in this case? Is the system too small to speed up the solution time further? The following is the parameter file.
[parameters.txt](https://github.com/trilinos/Trilinos/files/8028394/parameters.txt)

This is the log output with verbosity = extreme:
[solver_log.txt](https://github.com/trilinos/Trilinos/files/8028398/solver_log.txt)

Thanks for any help!

Adrian Diaz

**Comment by cgcgcg** [comment]
Do you have timing logs for the solver? It might help to figure out what parts of the solver are actually not scaling.

**Comment by Adrian-Diaz** [comment]
I just have a timer I put for the full solve time including the preconditioner time; which always seemed to be much smaller than the linear solver portion according to the muelu setup time output. Is there a parameter to output the solver timings?

**Comment by cgcgcg** [comment]
Do you have a block like this at the end of your driver?
https://github.com/trilinos/Trilinos/blob/fa2c4c37b0d7b66501e7fe4dbc9ec6481b4f56d4/packages/muelu/test/scaling/Driver.cpp#L544-L548
I believe running with MueLu's verbosity set to 'High' or more should give you a bunch of timers not only for the setup, but also for the solve.

**Comment by Adrian-Diaz** [comment]
No, I didn't extract the timer structures when I set it up, however I used a standard cpu timer to tell me the elapsed time for both PreconditionerSetup and SystemSolve. The extreme output level in the log above shows me the preconditioner setup time but I've never seen it report solve times; I just subtracted that from the time elapsed for both, which is suggesting about 36s for the solve when using 36 MPI ranks. Does the timer in the driver give a breakdown of the timing for the portions of SystemSolve?

**Comment by cgcgcg** [comment]
Yes, it should even give you per level information for the multigrid hierarchy, such as time spent in smoothing, residuals, restriction, prolongation and coarse solve.

**Comment by Adrian-Diaz** [comment]
[timer_report_2.txt](https://github.com/trilinos/Trilinos/files/8030053/timer_report_2.txt)
[timer_report_8.txt](https://github.com/trilinos/Trilinos/files/8030054/timer_report_8.txt)

These are the timer reports for a smaller N=510K system I tried just now from 2 MPI ranks to 8 MPI ranks. Seems like the Belos  solve time is the one that's not budging.

**Comment by cgcgcg** [comment]
Those timings look suspicious indeed. In particular, `MueLu: Hierarchy: Solve : smoothing (level=0)` takes ~ 1.4s on both 2 and 8 ranks. Generally, I'd expect to see improvements down to 10k rows/rank on CPUs. You're running at 250k and 62.5k. Is there any chance that the process binding is messed up?

**Comment by Adrian-Diaz** [comment]
It's definitely binding to core. The preconditioner setup is also speeding up.

**Comment by jhux2** [comment]
@Adrian-Diaz  Please try changing line 49 in your input deck to this to see if it helps:

```
<Parameter        name="repartition: start level"             type="int"      value="1"/>
```

**Comment by jhux2** [comment]
@trilinos/muelu

**Comment by Adrian-Diaz** [comment]
Changing the number of equations made no substantial difference. Changing start level to 1 slowed it down. I'll try out the scaling example.

**Comment by Adrian-Diaz** [comment]
How would I get the tests to build? I tried -DTrilinos_ENABLE_TESTS=ON but I don't see any associated executables in the build folder. I tried linking the driver myself but for some reason it can't find the Galeri_Exceptions header even when Trilinos is built with Galeri.

**Comment by Adrian-Diaz** [comment]
Using the following as a close representation of the grid size I was using before for N=3.9 million:
mpirun -np P --bind-to core ./MueLu_Driver.exe --xml=elasticity3D_share.xml --matrixType=Elasticity3D --nx=51 --ny=51 --nz=501 > solve_log_32.txt

for P = 4, 8, 16, and 32 with the following parameters
[elasticity3D_share.txt](https://github.com/trilinos/Trilinos/files/8037905/elasticity3D_share.txt)
:

gives me the following output from the driver:
[solve_log_32.txt](https://github.com/trilinos/Trilinos/files/8037907/solve_log_32.txt)
[solve_log_16.txt](https://github.com/trilinos/Trilinos/files/8037910/solve_log_16.txt)
[solve_log_8.txt](https://github.com/trilinos/Trilinos/files/8037911/solve_log_8.txt)
[solve_log_4.txt](https://github.com/trilinos/Trilinos/files/8037915/solve_log_4.txt)

**Comment by cgcgcg** [comment]
I ran your example on my workstation:
```
Timer Name                                           MinOverProcs       MeanOverProcs        MaxOverProcs       MeanOverCallCounts    
-----------------------------------------------------------------------------------------------------------------------------------

 4.log:Belos: PseudoBlockCGSolMgr total solve time   28.2 (1)           28.22 (1)            28.25 (1)          28.22 (1)             
 8.log:Belos: PseudoBlockCGSolMgr total solve time   14.83 (1)          14.84 (1)            14.86 (1)          14.84 (1)             
16.log:Belos: PseudoBlockCGSolMgr total solve time   8.45 (1)           8.458 (1)            8.464 (1)          8.458 (1)             
32.log:Belos: PseudoBlockCGSolMgr total solve time   9.168 (1)          9.181 (1)            9.202 (1)          9.181 (1)
```
I don't actually have 32 physical cores, so the last data point doesn't surprise me. I used serial node for that, not OpenMP. Maybe try with that, since it might help eliminate one source of issues?

**Comment by Adrian-Diaz** [comment]
what did the cmake configure file to build Trilinos for your run look like?

**Comment by cgcgcg** [comment]
[cmake.txt](https://github.com/trilinos/Trilinos/files/8045079/cmake.txt)

**Comment by Adrian-Diaz** [comment]
Is it possible one of the enabled settings in that build like parmetis for zoltan2 is causing a difference? I was using a rather remedial configure script:

cmake -DCMAKE_BUILD_TYPE=RELEASE \
-DTrilinos_MUST_FIND_ALL_TPL_LIBS=TRUE \
-DTPL_ENABLE_MPI=ON \
-DTrilinos_ENABLE_Kokkos=ON \
-DTrilinos_ENABLE_OpenMP=ON \
-DTrilinos_ENABLE_Amesos2=ON \
-DTrilinos_ENABLE_Belos=ON \
-DTrilinos_ENABLE_MueLu=ON \
-DTrilinos_ENABLE_ROL=ON \
-DTrilinos_ENABLE_Ifpack2=ON \
-DTrilinos_ENABLE_Zoltan2=ON \
-DMueLu_ENABLE_TESTS=ON \
-DTrilinos_ENABLE_ALL_PACKAGES=OFF -DTrilinos_ENABLE_ALL_OPTIONAL_PACKAGES=OFF -DTrilinos_ENABLE_TESTS=OFF \
-DCMAKE_INSTALL_PREFIX=. \

**Comment by cgcgcg** [comment]
It seemed that the "Belos Op*x" timer did not scale in your runs. That's a matrix-vector product with the matrix that Galeri sets up. Galeri doesn't do any load balancing, only coarser levels of MueLu are being rebalanced. But we used Zoltan2 multijagged for that, so I don't think that enabling ParMETIS mattered.

**Comment by Adrian-Diaz** [comment]
Well, assuming its not the packages it could also be the compiler and version of MPI. Otherwise, I can't see any other cause other than just the hardware (ran on an intel broadwell).

**Comment by cgcgcg** [comment]
I don't currently have any other ideas. Maybe try a different system?

**Comment by Adrian-Diaz** [comment]
The manual suggests a premigration option for the multijagged algorithm, how do I enable that in the parameter file?

**Comment by jhux2** [comment]
@Adrian-Diaz This should enable pre-migration in your XML deck:
```
    <ParameterList name="repartition: params">
       <Parameter name="algorithm" type="string" value="multijagged"/>
       <Parameter name="mj_premigration_option" type="int" value="1"/>
    </ParameterList> 
```

There a few closed issues that show the effect of pre-migration, e.g., #1538.  Given that your problem & core count is so small, I would be surprised if enabling pre-migration has a positive effect.

**Comment by Adrian-Diaz** [comment]
Yea that didn't matter. By the way, are there options I need to pass to use the equilibrate matrix routine shown in the driver? I was trying that on some of my matrices with bad condition numbers but it seems belos can't converge if I use the equilibrate matrix routine before the preconditioner build and solve.
