### ISSUE TITLE
How to implement Dirichlet boundary conditions in global sparse matrices A

### ISSUE THREAD

**Issue by ztdepztdep** [trilinos/Trilinos#10177]
I want to know is it necessary to subtract bc-values times the ith column of A from the right hand side(this operations are very complex in my ocde ).  Does it has improvement for the condition number of A. 
   
    In my implementation, I want to set the diagonal of A as "1", so we have  1.0*x1=bc-values.  for example 
  
       1.0    0.0   0.0   0.0    x1=bc-values
       a       b      a     0.0     x2=b2
       0        a      b     a       x3 =b3
        0       0      0     1.0     x4=bc-values

  Which function should i use to complete the following tasks.
`For each boundary DoF i,– subtract g(xi) times the ith column of A from the right hand side
– zero out the ith column of A
– zero out the ith row of A
– set Aii = 1
– set the ith entry of the right hand side to g(xi)`

**Comment by cgcgcg** [comment]
I am not sure what the question is. If you have boundary conditions you need to enforce them, otherwise the matrix might be singular. You generally can either (1) entirely eliminate the unknowns, (2) modify rows only, or (3) modify rows and columns.
