### ISSUE TITLE
Tpetra:  Lesson 02 - Example code to be fixed

### ISSUE THREAD

**Issue by romintomasetti** [trilinos/Trilinos#10178]
## Documentation
@trilinos/\<Tpetra\>

I was reading the lesson 02 of Tpetra (see https://docs.trilinos.org/dev/packages/tpetra/doc/html/Tpetra_Lesson02.html).

An example code has

```c++
  // Create a Vector with the 1-D cyclic Map.  Calling the constructor
  // with false for the second argument leaves the data uninitialized,
  // so that you can fill it later without paying the cost of
  // initially filling it with zeros.
  vector_type z (contigMap, false);
```

I think `contigMap` should be replaced with `cyclicMap`.

**Comment by kddevin** [comment]
Thank you for catching and reporting this error.  It is fixed in #10197.
