### ISSUE TITLE
Panzer: why does DOFManager require a raw MPI comm at setup?

### ISSUE THREAD

**Issue by bartgol** [trilinos/Trilinos#10193]
## Question
@trilinos/panzer 

The DOFManager only exposes/uses the comm as a `Teuchos::Comm<int>`, but the setup method requires a raw `MPI_Comm`.

Any reason not to switch to a `Teuchos::Comm` as input (letting the user build it from an `MPI_Comm` if not already built)? This would avoid casts/checks for downstream code (which is likely already using `Teuchos::Comm`), which always make the code a bit clunkier and slower to visually parse...

**Comment by cgcgcg** [comment]
@rppawlo
