### ISSUE TITLE
Tpetra:  Distributor slow path really is slow

### ISSUE THREAD

**Issue by kddevin** [trilinos/Trilinos#10194]
## Bug Report
@trilinos/tpetra @trilinos/zoltan2 @egboman @tasmith4 @seheracer @jhux2 

### Description

@seheracer reports slowdowns in Zoltan2's MultiJagged partitioner.  Slowdowns in Multijagged were also reported by @jhux2  in #9835.

I tracked the problem to Tpetra's slow-path distributor.  

Time spent in the Distributor increased roughly 50x after commit 2a8b7c437c2ce28898413bf013151addec939f77 relative to 76c7b6ac4461d3bbcc8108061df65b0bbdde8679 (determined by git bisect).  The difference is that the new code uses Kokkos::Views rather than ArrayRCPs.  Specifically, the new code uses deep_copy_offset.  In the slow path's tight loops, deep_copy_offset is creating too much overhead.

Running a Zoltan2 test from Sphynx with 2a8b7c437c2ce28898413bf013151addec939f77, we see the slow path distributor times:
```
Tpetra::Distributor: doPosts(3) KV                27.07 (546)       40.56 (546)       53.89 (546)       0.07428 (546)        
Tpetra::Distributor: doPosts(3): barrier KV       0 (0)             0 (0)             0 (0)             0 (0)                
Tpetra::Distributor: doPosts(3): recvs KV         0.002004 (546)    0.002272 (546)    0.002559 (546)    4.162e-06 (546)      
Tpetra::Distributor: doPosts(3): sends KV         27.07 (546)       40.55 (546)       53.89 (546)       0.07427 (546)        
Tpetra::Distributor: doPosts(3): sends KV FAST    0.383 (540)       0.4673 (537)      0.5496 (534)      0.0008702 (537)      
Tpetra::Distributor: doPosts(3): sends KV SLOW    26.68 (6)         40.08 (9)         53.4 (12)         4.453 (9)       
```

When I do a hack replacing deep_copy_offset with memcpy, the times reduce to times comparable to the ArrayRCP version of the code in 76c7b6ac4461d3bbcc8108061df65b0bbdde8679 (which uses std::copy)
```
Tpetra::Distributor: doPosts(3) KV                0.4761 (547)      0.5908 (547)      0.7083 (547)      0.00108 (547)        
Tpetra::Distributor: doPosts(3): barrier KV       0 (0)             0 (0)             0 (0)             0 (0)                
Tpetra::Distributor: doPosts(3): recvs KV         0.002105 (547)    0.002278 (547)    0.002375 (547)    4.164e-06 (547)      
Tpetra::Distributor: doPosts(3): sends KV         0.4728 (547)      0.5874 (547)      0.7049 (547)      0.001074 (547)       
Tpetra::Distributor: doPosts(3): sends KV FAST    0.3488 (541)      0.4314 (538)      0.516 (535)       0.0008018 (538)      
Tpetra::Distributor: doPosts(3): sends KV SLOW    0.1194 (6)        0.1515 (9)        0.1845 (12)       0.01683 (9)    
```

### Steps to Reproduce
Not super easy to reproduce these details, but we can see the increase in partitioning time through Zoltan2's use of the Distributor slow path.
Build Zoltan2 with Zoltan2Sphynx 
I hacked Test_Sphynx to generate more 16 parts regardless of the number of processors, but that may not be necessary.
 mpirun -np 4 Zoltan2_Sphynx.exe --x=100 --y=100 --z=1000 
Build with both SHAs and compare the Sphynx::MJ runtime.

**Comment by tasmith4** [comment]
This is sad.  I'll take a look.

**Comment by kddevin** [comment]
@tasmith4 Thank you for your work on the distributor.  The change to deep_copy_offset definitely recovered some performance, but not all the performance.  See below using the current develop branch with #10224 merged:
```
Tpetra::Distributor: doPosts(3) KV                6.547 (547)       10.17 (547)       13.59 (547)       0.01859 (547) 
Tpetra::Distributor: doPosts(3): barrier KV       0 (0)             0 (0)             0 (0)             0 (0)         
Tpetra::Distributor: doPosts(3): recvs KV         0.001879 (547)    0.002086 (547)    0.002383 (547)    3.814e-06 (547)
Tpetra::Distributor: doPosts(3): sends KV         6.545 (547)       10.17 (547)       13.58 (547)       0.01859 (547) 
Tpetra::Distributor: doPosts(3): sends KV FAST    0.2498 (541)      0.4025 (538)      0.5751 (535)      0.0007481 (538)
Tpetra::Distributor: doPosts(3): sends KV SLOW    6.29 (6)          9.759 (9)         13.14 (12)        1.084 (9)     
```
I confirmed that replacing deep_copy_offset with memcpy still gives times that are in-line with the original tests above.  So the PR recovered a factor of four, but the code is still an order of magnitude slower than deep_copy.
Are these results consistent with the timing you saw in #10224 ?

Note that #10224 appears to have benefits for the FAST path as well, so it is worth keeping.  But the slow path granularity might be too fine for taking the subviews and invoking deep_copy.

**Comment by tasmith4** [comment]
@kddevin These timings are in line with what I saw for deep_copy_offset with #10224, but they are also in line with what I saw when calling memcpy directly (i.e. I wasn't able to reproduce the memcpy timings you listed above).  I had assumed there was some system noise or something that was adding a flat 6 seconds all the way around.  Perhaps I need to dig deeper into why I haven't reproduced the memcpy timings above.

**Comment by tasmith4** [comment]
@kddevin these times are pretty small anyway.  Is there a way to change the args for the zoltan test so the times become larger, and (theoretically anyway) have less potential for noise?

**Comment by kddevin** [comment]
@tasmith4 you can increase any of the x, y, z arguments to increase the problem size.  The matrix corresponds to a 3D mesh, so the number of rows is x * y * z

**Comment by kddevin** [comment]
@tasmith4 Here's a reproducer that I think is representative of what the slow path does.
```
#include <iostream>
#include <limits>

#include "Tpetra_Core.hpp"
#include "Teuchos_TimeMonitor.hpp"
#include "KokkosCompat_View.hpp"

/////////////////////////////////////////////////////////////////////////////
int main(int narg, char** arg)
{
  Tpetra::ScopeGuard tscope(&narg, &arg);
  Teuchos::RCP<const Teuchos::Comm<int> > comm = Tpetra::getDefaultComm();
  int me = comm->getRank();
  int np = comm->getSize();

  if (me == 0) std::cout << "Usage: a.out integer" << std::endl;

  if (narg < 2) exit(-1);

  if (me == 0) std::cout << "Beginning..." << std::endl;

  int nx = std::atoi(arg[1]);

  Kokkos::View<double *, Kokkos::HostSpace> oldCoord("old", nx);
  for (int i = 0; i < nx; i++) oldCoord[i] = double(i+1);

  Kokkos::View<double *, Kokkos::HostSpace> newCoord("new", nx);

  int *permute = new int[nx];
  for (int i = 0; i < nx; i++) permute[i] = std::rand() % nx;


  {
    auto dco = Teuchos::TimeMonitor::getNewTimer("deep_copy_offset");
    Teuchos::TimeMonitor time(*dco);

    for (int i = 0; i < nx; i++) 
      Kokkos::Compat::deep_copy_offset(oldCoord, newCoord, i, permute[i], 1);
  }


  {
    auto mcp = Teuchos::TimeMonitor::getNewTimer("memcpy");
    Teuchos::TimeMonitor time(*mcp);

    for (int i = 0; i < nx; i++) 
      memcpy(&newCoord[permute[i]], &oldCoord[i], sizeof(double));
  }

  Teuchos::TimeMonitor::summarize (); // report timing results

  return 0;
}
```

With this reproducer on the ascicgpu machines, CUDA build, I see
```
> Zoltan2_dvm.exe 10000000
...
Timer Name          Global time (num calls)    
--------------------------------------------------------------------------------
deep_copy_offset    51.95 (1)                  
memcpy              1.508 (1)          
```

**Comment by tasmith4** [comment]
@kddevin for the record, as we discussed today, I can now reproduce your timings.  I also discussed this with @crtrott and I think we have a good path forward for refactoring doPosts to resolve these performance issues.

**Comment by tasmith4** [comment]
This can be closed.  #10935 marked it for automatic closure (not sure why that never triggered), which is consistent with my recollection that we had resolved this issue.

**Comment by jhux2** [comment]
@tasmith4 Thank!
