### ISSUE TITLE
SEACAS: Various test failures  in Cuda build with UVM off

### ISSUE THREAD

**Issue by ndellingwood** [trilinos/Trilinos#10208]
## Bug Report
@trilinos/seacas 

### Description
Testing a non-UVM Cuda build on the Weaver testbed (Power9+Volta70) had the following Seacas tests failing:

```
        1093 - SEACASIoss_structured_cgns_periodic_roundtrip_fpp (Failed)
        1094 - SEACASIoss_structured_cgns_roundtrip_fpp (Failed)
        1095 - SEACASIoss_structured_cgns_roundtrip_fpp2 (Failed)
        1098 - SEACASIoss_structured_cgns_roundtrip_fpp_vertex_cell_fields (Failed)
        1101 - SEACASIoss_structured_cgns_roundtrip_single_fpp_single_fields (Failed)
        1102 - SEACASIoss_structured_cgns_pre_split_join (Failed)
```

I tentatively marked as a bug bug this should be relabeled if the failures are expected in a non-UVM build, I'm not sure what the status currently is

### Steps to Reproduce

1. SHA1: 55d7185956289a91f9f75d4510b1a734ed4efd22

2. Configure script:  [attach here]

```bash
# Load modules
module purge
export ATDM_CONFIG_REGISTER_CUSTOM_CONFIG_DIR=${TRILINOS_DIR}/cmake/std/atdm/contributed/weaver
source ${TRILINOS_DIR}/cmake/std/atdm/load-env.sh weaver-cuda-10.1-opt

# Environment
unset CUDA_LAUNCH_BLOCKING

# CMake config
cmake \
 -GNinja \
 -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
 -DCMAKE_INSTALL_PREFIX="${PWD}/install" \
 -DCMAKE_CXX_STANDARD="14" \
 -DCMAKE_CXX_FLAGS="-pedantic -Wall" \
 -DTrilinos_ENABLE_TESTS=ON \
 -DTrilinos_ENABLE_ALL_PACKAGES=ON \
 -DKokkos_ENABLE_CUDA_UVM=OFF \
$TRILINOS_DIR
```

For Ninja usage, the configuration should be done on the login node; if batching the entire job to a compute node, make the following changes:
```bash
# Environment
export ATDM_CONFIG_USE_NINJA=OFF

# Replace -GNinja with
-G"Unix Makefiles"
```

Also instead of enabling all tests only the seacas tests need be enabled

**Comment by gsjaardema** [comment]
If not too much trouble, can you rerun with `ctest --rerun-failed --output-on-failure` and attach the output.

**Comment by ndellingwood** [comment]
@gsjaardema I've attached files for each test with output after running with the `--output-on-failure` options:
[SEACASIoss_structured_cgns_periodic_roundtrip_fpp.txt](https://github.com/trilinos/Trilinos/files/8098934/SEACASIoss_structured_cgns_periodic_roundtrip_fpp.txt)
[SEACASIoss_structured_cgns_pre_split_join.txt](https://github.com/trilinos/Trilinos/files/8098935/SEACASIoss_structured_cgns_pre_split_join.txt)
[SEACASIoss_structured_cgns_roundtrip_fpp_vertex_cell_fields.txt](https://github.com/trilinos/Trilinos/files/8098936/SEACASIoss_structured_cgns_roundtrip_fpp_vertex_cell_fields.txt)
[SEACASIoss_structured_cgns_roundtrip_fpp.txt](https://github.com/trilinos/Trilinos/files/8098937/SEACASIoss_structured_cgns_roundtrip_fpp.txt)
[SEACASIoss_structured_cgns_roundtrip_fpp2.txt](https://github.com/trilinos/Trilinos/files/8098938/SEACASIoss_structured_cgns_roundtrip_fpp2.txt)
[SEACASIoss_structured_cgns_roundtrip_single_fpp_single_fields.txt](https://github.com/trilinos/Trilinos/files/8098940/SEACASIoss_structured_cgns_roundtrip_single_fpp_single_fields.txt)

Thanks

**Comment by gsjaardema** [comment]
These should now be fixed.  Sorry for the delay, but there was some strange `ifdef` problems that made this only show up on a few systems with a specific version of the CGNS library.  All this should now be working.

**Comment by ndellingwood** [comment]
Thanks @gsjaardema ! I'll try reenabling the tests in the non-UVM Cuda builds

**Comment by gsjaardema** [comment]
I think this is fixed.  If still having problems, please reopen...
