### ISSUE TITLE
SuiteSparse CMakeLists conditional on Cray

### ISSUE THREAD

**Issue by jwillenbring** [trilinos/Trilinos#1020]
The following issue was reported:

In order to build with the Cray compilers, we have to modify Trilinos/packages/common/auxiliarySoftware/SuiteSparse/src/CMakeLists.txt as follows. 
...

@@ -45,7 +45,9 @@ SET_SOURCE_FILES_PROPERTIES(${SOURCES},
                 PROPERTIES
                 LANGUAGE C)
 
-  IF(CMAKE_COMPILER_IS_GNUCC OR CMAKE_COMPILER_IS_GNUCXX)
+  IF ("${CMAKE_CXX_COMPILER_ID}" STREQUAL "cray")
+      #No flags
+  ELSEIF(CMAKE_COMPILER_IS_GNUCC OR CMAKE_COMPILER_IS_GNUCXX)
       IF(CMAKE_CXX_COMPILER_VERSION VERSION_GREATER 4.2)
         SET_SOURCE_FILES_PROPERTIES(${SOURCES},
                 PROPERTIES

@krcb can you review, test, and apply this change? Based on the wording of the message, it seems the change has been tested on Cray already.
CC: @bmpersc

**Comment by bmpersc** [comment]
This whole conditional block looks suspect to me. The default case is to set the same flags as when we have a gnu compiler > 4.2. I think it would be good to have a case specifically for cray. But, based on the report I can't really say which case we were landing in that was giving the wrong behavior, the gnu or the default.

**Comment by krcb** [comment]
I've simplified the block down to only add those flags to the GCC case, removing all other cases. @MicheldeMessieres is going to test and open the PR when tests are complete.

**Comment by bmpersc** [comment]
@krcb that seems like a good solution to me.

**Comment by MicheldeMessieres** [comment]
Ran tests and set up PR #1022

**Comment by bavier** [comment]
BTW, the Cray warnings flags issue was mostly fixed in PR #260

**Comment by krcb** [comment]
This is resolved with merge of #1022
