### ISSUE TITLE
FRoSch: Albany compilation error

### ISSUE THREAD

**Issue by ikalash** [trilinos/Trilinos#10211]
Many of our Albany nightlies are failing due to a FRoSch error: 

```
/.../build/TrilinosInstall/include/FROSch_Tools_def.hpp(166): error: no instance of overloaded function "Tpetra::Distributor::doPostsAndWaits" matches the argument list
```
https://sems-cdash-son.sandia.gov/cdash/viewBuildError.php?buildid=29567

Could someone please have a look at this?

@mperego (not sure who else to tag).

**Comment by rppawlo** [comment]
@srajama1

**Comment by cgcgcg** [comment]
Duplicate of #10202
