### ISSUE TITLE
MueLu: compilation errors with HIP and complex scalar

### ISSUE THREAD

**Issue by jhux2** [trilinos/Trilinos#10227]
## Bug Report
@trilinos/muelu 

### Description
A user has reported that their compilations fails in `MueLu_CoalesceDropFactory_kokkos_def.hpp` with the HIP backend and complex scalar type.

[hip-complex-log.txt](https://github.com/trilinos/Trilinos/files/8112678/hip-complex-log.txt)

**Comment by jhux2** [comment]
@mwglass

**Comment by cgcgcg** [comment]
Should be fixed in PR #10272

**Comment by cgcgcg** [comment]
Please reopen if this is still an issue.
