### ISSUE TITLE
Belos:BlockGmres iteration time is too long for each step

### ISSUE THREAD

**Issue by lixiangliang** [trilinos/Trilinos#10239]
## Question
@trilinos/belos

@cgcgcg @hkthorn I counted the time of each iteration of BlockGmres and found that the iteration time could not achieve the effect I expected. Practical testing found that `Get a view of the part of the Hessenberg matrix needed to hold the norm coeffs` took most of the time in each iteration. 
For example, the total time of a certain iteration is 3.84s, and the time occupied by multiplication is 1.38s, but the above part takes 2.46s. 
I don't understand why it takes so much time here, is there any possibility of optimization? Because I also wrote the code of BlockGmres myself, the iteration time of each step in my code is approximately equal to the time of each multiplication calculation.

**Comment by cgcgcg** [comment]
@trilinos/belos

**Comment by cgcgcg** [comment]
@lixiangliang That seems odd indeed. Can you reproduce this behavior with one of the Belos tests or examples?

**Comment by cgcgcg** [comment]
@lixiangliang I put a timer around this region
https://github.com/trilinos/Trilinos/blob/cd1f2de822758156e2fc24a6cefeeb01dc83436d/packages/belos/src/BelosBlockGmresIter.hpp#L723-L727
but I cannot reproduce the issue. I think we need more details on what you're running.
