### ISSUE TITLE
Ifpack2: Build broken with Hypre support

### ISSUE THREAD

**Issue by finkandreas** [trilinos/Trilinos#10236]
## Bug Report
@trilinos/ifpack2

### Description
I'm trying to compile Ifpack2 with Hypre but I get quite a lot of build errors. It works with Trilinos-13.0.1, it fails with Trilinos-13.2.0, master and development.

### Steps to Reproduce
Quickest way to reproduce
```
spack install trilinos@13.0.1+hypre
spack install trilinos@13.2.0+hypre
spack install trilinos@master+hypre
spack install trilinos@develop+hypre
```
An example of trilinos master branch build error is attached.
[trilinos_build.log](https://github.com/trilinos/Trilinos/files/8125550/trilinos_build.log)

**Comment by cgcgcg** [comment]
It looks like Hypre is built with `HYPRE_Int = int` and Tpetra with `GlobalOrdinal = long long int`. They need to match, as far as I know. I'm assuming this worked in older Trilinos, since there was no Hypre interface in Ifpack2.

**Comment by csiefer2** [comment]
So somebody needs to fix their spackage...

**Comment by cgcgcg** [comment]
@csiefer2 I'd think so. @trilinos/xsdk ?

**Comment by bartlettroscoe** [comment]
@keitat

**Comment by jwillenbring** [comment]
Since this was identified as a probable problem with a Spack package and there was no reply after that, I am going to close this issue.
