### ISSUE TITLE
Zoltan and Xpetra:  ctest failure

### ISSUE THREAD

**Issue by mperrinel** [trilinos/Trilinos#10235]
## Bug Report
@trilinos/zoltan 
@trilinos/xpetra 

### Description
I used spack to configure and build Trilinos and then run a make dashboard to get a CDash report on which I saw different test failures and a build error : 
https://testing.sandia.gov/cdash/index.php?project=Trilinos&begin=2022-02-16&end=2022-02-17&filtercount=1&showfilters=1&field1=buildname&compare1=63&value1=Linux-spack-build-lqyocxo

For Zoltan, some of Zoltan...Parmertis_parallel tests failed : 
https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Linux-spack-build-lqyocxo&field2=buildstarttime&compare2=81&value2=2022-02-16T14%3A33%3A34%20UTC&field3=status&compare3=61&value3=failed

We can see that the test **Zoltan_hg_cage10_zoltan_parallel** failed because of my number of available slot which was not satisfying the 11 slots requested by the test (I have 10). For the others, the problem comes from a diff done during the test.

For XPETRA: the test **Xpetra_MultiVector_UnitTests_MPI_4** failed (1 on 30 failed)
```
Exception message for expected exception:
 
  /home/perrinel/Dev/spack-stage2/spack-stage/spack-stage-trilinos-develop-lqyocxop4nwmlpzpjs3qlweb7ejluu7i/spack-src/packages/tpetra/core/src/Tpetra_MultiVector_def.hpp:2979:
  
  Throw number = 11
  
  Throw test that evaluated to true: (getLocalLength () != A.getLocalLength ())
  
  Tpetra::MultiVector<double,int,long long,Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace>>::reciprocal: MultiVectors do not have the same local length.  this->getLocalLength() = 2 != A.getLocalLength() = 1.
  
 [FAILED]  (0.000203 sec) MultiVector_double_int_longlong_Kokkos_Compat_KokkosSerialWrapperNode_BadCombinations_UnitTest
 Location: /home/perrinel/Dev/spack-stage2/spack-stage/spack-stage-trilinos-develop-lqyocxop4nwmlpzpjs3qlweb7ejluu7i/spack-src/packages/xpetra/test/MultiVector/MultiVector_UnitTests.cpp:2437
 
```

I used a Linux Ubuntu 20.04 and a gcc 9.3.0 compiler with 10 cores.

### Steps to Reproduce
1. clone spack with git 
2. export the TMP variable to a location which is not temporary.
3. Install Trilinos using spack : 
`spack install --test=root --keep-stage --source --overwrite trilinos@develop +boost +mpi +zoltan +exodus +hdf5 +superlu-dist`
4. cd to the Trilinos build directory of spack-stage
5. Enable pthread and boostlib TPL_ENABLED_Pthread=ON and TPL_ENABLED_BoostLib=ON, then run cmake, make and make install
6. Install scotch using spack : 
`spack install --test=root --keep-stage --source --overwrite scotch@6.0.3`
7. Enable Scotch for Trilinos (TPL_ENABLE_Scotch=ON) and set TPL_Scotch_LIBRARIES and TPL_Scotch_INCLUDE_DIRS to the Scotch spack installation directory
```
-- Scotch_LIBRARY_NAMES='ptscotch;ptscotcherr;scotch;scotcherr'
-- TPL_Scotch_LIBRARIES='/home/perrinel/Dev/spack/opt/spack/linux-ubuntu20.04-skylake/gcc-9.3.0/scotch-6.0.3-rqnwr2dgwxyauebfluszngymuib4jenw/lib/libscotch.so;/home/perrinel/Dev/spack/opt/spack/linux-ubuntu20.04-skylake/gcc-9.3.0/scotch-6.0.3-rqnwr2dgwxyauebfluszngymuib4jenw/lib/libptscotch.so;/home/perrinel/Dev/spack/opt/spack/linux-ubuntu20.04-skylake/gcc-9.3.0/scotch-6.0.3-rqnwr2dgwxyauebfluszngymuib4jenw/lib/libptscotcherr.so'
-- TPL_Scotch_INCLUDE_DIRS='/home/perrinel/Dev/spack/opt/spack/linux-ubuntu20.04-skylake/gcc-9.3.0/scotch-6.0.3-rqnwr2dgwxyauebfluszngymuib4jenw/include/'
```

8. disable SuperLU for Amesos:  -D Amesos_ENABLE_SuperLU=OFF
9. run cmake, make and make install again
10. run make dashboard

**Comment by cgcgcg** [comment]
The Xpetra failure is the same as #9795. Should be fixed by PR #10186.

**Comment by kddevin** [comment]
Thanks for your report.
According to your The Zoltan tests with ParMETIS are running and appear to be partitioning correctly.
ParMETIS, however, uses random number generation in a greedy algorithm.  Thus, it can generate different yet equally valid partitions depending on the system's random number generator and how ParMETIS and Zoltan are build and configured.
These different yet equally valid partitions result in Zoltan test failures, as the generated partitions differ from the gold-standard answers used in comparisons.  Error messages of this form are generated:
```
Test brack2_3:partgeomkway-v3 FAILED (Diff failed on 5 files)
```
This gold-standard testing is not ideal, but it allows us to identify when code changes have changed Zoltan's behavior.  
For some mission-critical platforms, we have platform-specific gold-standard files, but maintaining such files for all platforms and configurations is not feasible.  
I see that you are building with gcc 9.3.0.  The gold-standard files were generated with a much older version of gcc; I wonder whether the compiler is making the difference.

**Comment by mperrinel** [comment]
@bartlettroscoe @keitat
@cgcgcg and @kddevin Thanks for the info
