### ISSUE TITLE
ROL: error building tests with Tpetra deprecated code off

### ISSUE THREAD

**Issue by jewatkins** [trilinos/Trilinos#10242]
## Bug Report
@trilinos/rol 

### Description
There's an error building ROL tests with Tpetra deprecated code off.
```
Trilinos/packages/rol/adapters/tpetra/src/function/ROL_TpetraBoundConstraint.hpp:374:46: error: no matching function for call to ‘Tpetra::MultiVector<double, int, long long int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial> >::getLocalViewDevice()’
```
https://sems-cdash-son.sandia.gov/cdash/viewBuildError.php?buildid=29876

Also see https://github.com/sandialabs/Albany/issues/796

**Comment by dridzal** [comment]
@jewatkins , thanks for letting us know.  @mperego , I think you suspected that this would happen.  Also including @gregvw , as he is working on some Kokkos-related extensions for ROL, which may touch on this deprecation.
