### ISSUE TITLE
Zoltan2 Hypergraph model assumes contiguous GID number from base 1

### ISSUE THREAD

**Issue by kddevin** [trilinos/Trilinos#1024]
Zoltan2's hypergraph model assumes global IDs of entities are numbered contiguously from base 1.  Variable numGlobalVertices_ is set to the global maximum GID value.  When global IDs are not numbered contiguously or from base 1, this computation is incorrect.

Also, the Tpetra::Maps used in building the hypergraph model use indexBase=0.  I think they could be more efficient for the non-contiguous case if the minimum ID were computed and used in the Map constructors.

@trilinos/zoltan2

**Comment by mhoemmen** [comment]
@kddevin Would it help if I finally got rid of that indexBase requirement for noncontiguous Maps?

**Comment by kddevin** [comment]
No need, @mhoemmen , but thanks.  The bigger error is in the way our hyoergraph model determines the number of unique GIDs. The Map issue is secondary, and easily resolved with at most an Allreduce.
Thanks.
