### ISSUE TITLE
Amesos2: compilation error w/ Tpetra deprecated code turned off

### ISSUE THREAD

**Issue by ikalash** [trilinos/Trilinos#10247]
@trilinos/amesos2 

We have failed Trilinos builds in the Albany and Albany-LCM builds with Tpetra deprecated code turned off due to Amesos2:

```
[ 78%] Building CXX object packages/amesos2/src/CMakeFiles/amesos2.dir/Amesos2_KokkosCrsMatrix_MatrixAdapter.cpp.o
[ 78%] Building CXX object packages/amesos2/src/CMakeFiles/amesos2.dir/Amesos2_TpetraMultiVecAdapter.cpp.o
[ 78%] Building CXX object packages/amesos2/src/CMakeFiles/amesos2.dir/Amesos2_KokkosMultiVecAdapter.cpp.o
[ 78%] Building CXX object packages/amesos2/src/CMakeFiles/amesos2.dir/Amesos2_Util.cpp.o
[ 78%] Building CXX object packages/amesos2/src/CMakeFiles/amesos2.dir/Amesos2_Version.cpp.o
[ 78%] Building CXX object packages/amesos2/src/CMakeFiles/amesos2.dir/Amesos2_KLU2.cpp.o
[ 78%] Building CXX object packages/amesos2/src/CMakeFiles/amesos2.dir/Amesos2_KLU2_TypeMap.cpp.o
In file included from [packages/amesos2/src/Amesos2_KLU2.cpp:48](https://blob/master/packages/amesos2/src/Amesos2_KLU2.cpp#L48):
In file included from [packages/amesos2/src/Amesos2_KLU2_def.hpp:59](https://blob/master/packages/amesos2/src/Amesos2_KLU2_def.hpp#L59):
In file included from [packages/amesos2/src/Amesos2_SolverCore_def.hpp:56](https://blob/master/packages/amesos2/src/Amesos2_SolverCore_def.hpp#L56):
[packages/amesos2/src/Amesos2_MatrixAdapter_def.hpp:512](https://blob/master/packages/amesos2/src/Amesos2_MatrixAdapter_def.hpp#L512):61: error: no member named 'getNodeE
```
https://sems-cdash-son.sandia.gov/cdash/viewBuildError.php?buildid=29958
https://sems-cdash-son.sandia.gov/cdash/viewBuildError.php?buildid=29945

Could someone please have a look?  Tagging @lxmota who will also be interested in this issue.

**Comment by cgcgcg** [comment]
@trilinos/framework Do we have a nightly build that disables deprecated code? This is the third time this stuff is hitting Albany in the last week or so.

**Comment by ZUUL42** [comment]
@cgcgcg, I'm not sure if it's useful for you in it's current state, but we do have this deprecated nightly build: [CDash](https://testing.sandia.gov/cdash/index.php?project=Trilinos&display=project&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=63&value1=gcc_8.3_deprecated_off&field2=buildstarttime&compare2=84&value2=NOW)

**Comment by cgcgcg** [comment]
@ZUUL42 Thank you! Any idea why that build displays in such a weird way? Makes parsing what's actually failing quite difficult.

**Comment by ZUUL42** [comment]
@cgcgcg, sorry, I have not had the chance to look into that.

**Comment by ndellingwood** [comment]
Looks like the changes to replace `getNode*` by `getLocal*` in #10189 need to be made to Amesos2. I'll put in a PR shortly

**Comment by ndellingwood** [comment]
Opened PR #10250, hopefully just the name change update is needed

**Comment by cgcgcg** [comment]
@ikalash What's the SHA for that build? I did push some deprecated changes yesterday: #10256 and #10257.

**Comment by ikalash** [comment]
Here it is: 

```
commit 1760977a3e33da0dc7310f1e815c2e88fd51ebde
Merge: 6e5d996 1e1bd8a
Author: trilinos-autotester <trilinos@sandia.gov>
Date:   Mon Feb 28 14:18:04 2022 -0700

    Merge Pull Request #10256 from cgcgcg/Trilinos/mueluFixes
    
    Automatically Merged using Trilinos Pull Request AutoTester
    PR Title: Deprecation fixes
    PR Author: cgcgcg
```

**Comment by cgcgcg** [comment]
Ok. Hopefully you won't be seeing the MueLu issues anymore tomorrow. There are PRs #10261 and #10262 for the next set of packages.

**Comment by ikalash** [comment]
Thanks @cgcgcg , I will keep my eye out for the fixes.

**Comment by ikalash** [comment]
Could someone help me answer the following questions?  It's for a code I support that uses Trilinos:

- is Tpetra::StaticProfile going away with the deprecation?  I'm seeing errors that look as following:
```
/home/ikalash/Trilinos/DataTransferKit/packages/Operators/test/tstPolynomialMatrix.cpp:111:54: error: ‘StaticProfile’ is not a member of ‘Tpetra’
                 row_map, col_map, poly_size, Tpetra::StaticProfile ) );
                                                      ^~~~~~~~~~~~~
```
- It looks like getLocalRowView changed too - does it take a Kokkos::View now?
```
/home/ikalash/Trilinos/DataTransferKit/packages/Operators/test/tstCrsMatrixFill.cpp:173:54: error: no matching function for call to ‘Tpetra::CrsMatrix<double, int, long long int>::getLocalRowView(int, Teuchos::ArrayView<const int>&, Teuchos::ArrayView<const double>&)’
     A->getLocalRowView( 0, indices_view, values_view );
```

**Comment by cgcgcg** [comment]
- I believe `StaticProfile` was already the only option before, I think all you need to do is remove `Tpetra::StaticProfile` from the call. @trilinos/tpetra, is that correct?
- Yes, it's Kokkos views now, see:
https://github.com/trilinos/Trilinos/blob/539a887bd89cdd6ecdebcc4783c3347035de6884/packages/tpetra/core/src/Tpetra_CrsMatrix_decl.hpp#L2742-L2753

**Comment by ikalash** [comment]
Thanks @cgcgcg let me see if I can fix this.  Thanks for your responsiveness - I haven't been following all the changes to Tpetra and your replies will save me a lot of time grepping through the code to try to figure out what changed!

**Comment by ikalash** [comment]
Thanks @mperego !  I had to make a few changes in LCM today (as well as DTK) but things seem clean now.  I really hope the dashboard has no failures tomorrow for LCM at least!

**Comment by brian-kelley** [comment]
@ikalash Did switching to the non-deprecated functions fix Albany?

**Comment by ikalash** [comment]
Yes, I think so.  This issue can be closed.
