### ISSUE TITLE
Intrepid2:  Testing coverage in Intrepid2::ProjectionTools

### ISSUE THREAD

**Issue by kyungjoo-kim** [trilinos/Trilinos#10259]
## Enhancement
@trilinos/intrepid2 

Intrepid2 projection tools needs to improve the following things

- ~~the code is not entirely UVM free when the sequential path is applied. kokkoskernels is optional package and it should be tested without it in CUDA~~ Done by #10333 

- the commutativity test is not UVM free and the commutativity test fails without CUDA_LAUNCH_BLOCKING=1, which means there  is missing fence. Once the code is UVM free, this problem is probably resolved as well.

FAD testing with zero derivative dimension. 
- HCURL_TET_In_FEM,HCURL_TRI_In_FEM
- HDIV_TET_In_FEM,HDIV_TRI_In_FEM
- HGRAD_LINE_Cn_FEM,HGRAD_TET_Cn_FEM,HGRAD_TRI_Cn_FEM
- HVOL_LINE_Cn_FEM,HVOL_TET_Cn_FEM,HVOL_TRI_Cn_FEM

Although our FAD tests just check its compiling, this error seems to be legit as the error happens when it uses non-zero FAD dimensions. Also, HEX and QUAD does not show the same trouble when it uses non-zero FAD dimension. This issue seems to be there when the test is created. When the test is created, it tests with the zero FAD dimension while other tests uses non-zero derivative dimensions.

**Comment by mperego** [comment]
The UVM issues have been resolved. Need to check the issue with FAD with nonzero dimension.
