### ISSUE TITLE
Tpetra:  API for explicit async import/export for FE* objects 

### ISSUE THREAD

**Issue by kubagalecki** [trilinos/Trilinos#10275]
## Enhancement
@trilinos/\<tpetra\>

### Intro
Dear Tpetra Team,
I am proposing to add a non-blocking version of `doOwnedToOwnedPlusShared` for the FE* classes which is broken up into begin and end phases. This would be a win for FEMultiVector in particualar.

### Motivating example
Say we are performing a finite element assembly for a non-linear problem. To assemble the local system for a given element, we need the node values for that element's nodes (e.g. velocity values for a flow problem). In Tpetra terms, to call `sumInto*Values` on the `FECrsMatrix`, we first need to access the entries of some corresponding `FEMultiVector`. Since we are dealing with a non-linear problem, we presumably just did a solve, so we have access to the needed entries. More accurately, we have access to the *owned* entries. For internal elements (i.e. elements which do not own any ghost nodes) this is fine. However, non-internal elements need the *owned plus shared* entries for their local assembly. Therefore, before we do any assembly, we need to call `doOwnedToOwnedPlusShared` on the relevant `FEMultiVector`, which implies blocking communications. This leaves performance on the table! We could have been doing assembly on the internal elements while we wait for the communication to complete, to optimally overlap computation and communication.

### Current (rather lacking) solution
Prior to 13.2.0, the only way to circumvent the blocking nature of `doOwnedToOwnedPlusShared` (to the best of my knowledge) was to call it in a separate thread. This introduces all the usual problems, as well as potentially oversubscribing the execution resources when the internal element assembly overlaps with the import operation (if the import operation utilizes parallelism, which I think it does?).
Since 13.2.0 introduced async capabilities for import/export (see f814d2734a2406edb6e49240d238abf603467878), the problem can be solved as follows:
```c++
// sparsity_pattern is the underlying FECrsGraph (needed to get the import object)
// x is the FECrsMultiVector containing the requisite node values
// x is initially in the FE_ACTIVE_OWNED state
auto x_owned_mv_rcp = Teuchos::rcp_dynamic_cast< Tpetra::MultiVector<> >(x);
x->switchActiveMultiVector();
auto x_owned_plus_shared_mv_rcp = Teuchos::rcp_dynamic_cast< Tpetra::MultiVector<> >(x);
x_owned_plus_shared_mv_rcp->beginImport(*x_owned_mv_rcp, *sparsity_pattern->getImporter(), Tpetra::REPLACE);
// Do internal element assembly using x_owned_mv_rcp...
x_owned_plus_shared_mv_rcp->endImport(*x_owned_mv_rcp, *sparsity_pattern->getImporter(), Tpetra::REPLACE);
// Do remaining assembly using x_owned_plus_shared_mv_rcp...
```
As you can see, this is somewhat hacky, as it relies on the implementation details of `FEMultiVector`. To be honest, I've only tested this a limited amount, so I'm not even 100% this works for all possible scenarios.

### Proposed solution
I propose that expert mode `beginOwnedToOwnedPlusShared` and `endOwnedToOwnedPlusShared` member functions be added to `FEMultiVector`. These would effectively just be officially supported versions of the snippet above (just without the switching and casts, since we would have direct access to the underlying member variables).
Similar async functionality can further be added to the shared+owned->owned communication, though I fail to see the use case. Ditto for `FECrsMartix`.

### Final remarks
The proposed change is non-breaking - it is purely an expansion of the existing API. It also seems somewhat trivial to implement, as all the requisite underlying functionality is already there.
I would be happy to contribute the described change (along with tests and documentation), should the maintainers express interest.
Apologies if this is a duplicate or has been addressed elsewhere, if that's the case I must've missed it.

Kind regards,
Jakub

**Comment by kubagalecki** [comment]
Sorry I think I may have messed up the tag: @trilinos/\<tpetra\>

**Comment by kubagalecki** [comment]
Related issue: #9251

**Comment by cgcgcg** [comment]
@trilinos/tpetra
