### ISSUE TITLE
Tpetra build error in continuous

### ISSUE THREAD

**Issue by bmpersc** [trilinos/Trilinos#1027]
@trilinos/tpetra It appears that the addition of cooMatrix from issue #1025 has caused the continuous build to fail. You can see the failure at http://testing.sandia.gov/cdash/viewBuildError.php?buildid=2724420. It looks like the issue is with the usage of sstream so it is probably related to some debugging output.

**Comment by mhoemmen** [comment]
I'll work on this one.

**Comment by mhoemmen** [comment]
std::ostringstream forbids assignment, but I can achieve the desired effect (clear contents, start fresh) by calling `os.str("")`.  I'll try that.  btw this worked fine with Clang 3.5.

**Comment by mhoemmen** [comment]
Done!
