### ISSUE TITLE
Kokkos:  how to tell what version of Kokkos is in Trilinos

### ISSUE THREAD

**Issue by ikalash** [trilinos/Trilinos#10287]
## Question
@trilinos/kokkos
 
I am wondering if someone could tell me how I can tell what version of Kokkos is in Trilinos develop at any given point of time.  A sha for the relevant Kokkos commit or a released version of Kokkos is what I'm looking for.

**Comment by jhux2** [comment]
@ikalash I know this can be done via github, which is perhaps not exactly what you're looking for.

https://github.com/trilinos/Trilinos/pulls?q=is%3Apr+label%3A%22pkg%3A+Kokkos%22+Promotion+in%3Atitle+

**Comment by ikalash** [comment]
Thanks @jhux2 !  Does it mean that the commits corresponding to the most up-to-date Kokkos promotion would be the version that's in Trilinos develop VOTD?  Seems it would be this one from the URL you posted: https://github.com/trilinos/Trilinos/pull/8359/commits .  Am I understanding correctly?

**Comment by jhux2** [comment]
My understanding is that Trilinos VOTD should have all the commits from the latest snapshotted Kokkos promotion, in this case 3.2.01.

**Comment by jhux2** [comment]
@ndellingwood @srajama1 Can one of you two help out here?

**Comment by cgcgcg** [comment]
You could use this:
https://github.com/trilinos/Trilinos/blob/1b69d0d6781f716b3cd2198efdf891b37783305e/packages/kokkos/cmake/KokkosCore_config.h.in#L12
that's being set here:
https://github.com/trilinos/Trilinos/blob/1b69d0d6781f716b3cd2198efdf891b37783305e/packages/kokkos/CMakeLists.txt#L113-L117

**Comment by ikalash** [comment]
Thanks @cgcgcg !  It seems then that Trilinos VOTD has Kokkos 3.5.00, if I'm understanding the versions correctly.
