### ISSUE TITLE
Intrepid2 test fails without UVM

### ISSUE THREAD

**Issue by kyungjoo-kim** [trilinos/Trilinos#10294]
## Bug Report
@trilinos/intrepid2 

Intrepid2_unit-test_MonolithicExecutable_Intrepid2_Tests.exe test fails
```
96. Legendre_DerivativesMatchJacobi_UnitTest ... [Passed] (0.0382 sec)
97. ProjectedGeometry_CircularGeometryConvergesInP_SingleCell_UnitTest ... error for p = 1: 1.14159
Kokkos::View ERROR: attempt to access inaccessible memory spaceAborted (core dumped)
```

### Description

When ``Kokkos_ENABLE_CUDA_UVM=OFF``, the test fails with attempting invalid memory space.

**Comment by CamelliaDPG** [comment]
@kyungjoo-kim, thanks; I'll take a look.
