### ISSUE TITLE
Teuchos:  Tag usage in Teuchos::Comm for multiple asynchronous requests

### ISSUE THREAD

**Issue by tasmith4** [trilinos/Trilinos#10296]
## Question
@trilinos/teuchos @trilinos/tpetra @bartlettroscoe 

@kddevin and I noticed that Tpetra's `Distributor::doPosts` passes the same tag to all calls it makes to the send/receive methods from Teuchos.  We're nervous about this now that we're trying to allow multiple asynchronous calls -- i.e. call `doPosts` on many Distributors in succession, such that multiple invocations of `doPosts` can have requests in flight with the same (hardcoded) tags.

Is this usage ok, or do we need to adjust our tagging strategy?  If it needs adjustment, what best practices should we follow?

**Comment by jhux2** [comment]
Messages with duplicate tags were a problem either in Aztec or ML years ago, so yes, I'd say that hard-coding is bad idea.

**Comment by bartlettroscoe** [comment]
I would say to use different/unique tags with these calls.

**Comment by tasmith4** [comment]
@jhux2 @bartlettroscoe thanks -- opening a new issue to track the addition of a unique tag capability.
