### ISSUE TITLE
Errors during installation in MacOS BigSur

### ISSUE THREAD

**Issue by boblukas** [trilinos/Trilinos#10309]
Dear all,

I am a deal.II user and I need to install some Trilinos libraries to run certain programs.  More precisely, I am following the instructions given at this [documentation page of deal.II](https://www.dealii.org/current/external-libs/trilinos.html). I downloaded the latest Trilinos 13.2.0 release.

Here's my CMake command (I only added `DBoost_INCLUDE_DIRS` and `DTPL_Boost_INCLUDE_DIRS` flags w.r.t. what is written in the linked documentation page):

```
cmake                                            \
    -DTrilinos_ENABLE_Amesos=ON                      \
    -DTrilinos_ENABLE_Epetra=ON                      \
    -DTrilinos_ENABLE_EpetraExt=ON                   \
    -DTrilinos_ENABLE_Ifpack=ON                      \
    -DTrilinos_ENABLE_AztecOO=ON                     \
    -DTrilinos_ENABLE_Sacado=ON                      \
    -DTrilinos_ENABLE_SEACAS=ON                      \
    -DTrilinos_ENABLE_Teuchos=ON                     \
    -DTrilinos_ENABLE_MueLu=ON                       \
    -DTrilinos_ENABLE_ML=ON                          \
    -DTrilinos_ENABLE_ROL=ON                         \
    -DTrilinos_ENABLE_Tpetra=ON                      \
    -DTrilinos_ENABLE_COMPLEX_DOUBLE=ON              \
    -DTrilinos_ENABLE_COMPLEX_FLOAT=ON               \
    -DTrilinos_ENABLE_Zoltan=ON                      \
    -DTrilinos_VERBOSE_CONFIGURE=OFF                 \
    -DTPL_ENABLE_MPI=ON                              \
    -DBUILD_SHARED_LIBS=ON                           \
    -DCMAKE_VERBOSE_MAKEFILE=OFF                     \
    -DCMAKE_BUILD_TYPE=RELEASE                       \
    -DBoost_INCLUDE_DIRS=/usr/local/include/boost/ \
    -DTPL_Boost_INCLUDE_DIRS=/usr/local/include/boost/              \
    -DCMAKE_INSTALL_PREFIX:PATH=$HOME/share/trilinos \
    ../
```

The configuration doesn't give any warnings, but when it comes to install with `make -j8 install`,  I got errors and the following ones are the first. The others are essentially identical, they all say: **error: implicit declaration of function 'XDrawLines' is invalid in C99 [-Werror,-Wimplicit-function-declaration]**

```
[ 10%] Building CXX object packages/pamgen/src/CMakeFiles/pamgen.dir/__/parser/parser.C.o
/Users/lukas/Trilinos-trilinos-release-13-2-0/packages/seacas/libraries/svdi/cgi/x11_vdix11.c:580:5: error: implicit declaration of function 'XDrawLines' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    XDrawLines(display, draw_id, gc, vlist, x11_nvert, CoordModeOrigin);
    ^
/Users/lukas/Trilinos-trilinos-release-13-2-0/packages/seacas/libraries/svdi/cgi/x11_vdix11.c:619:18: error: implicit declaration of function 'XOpenDisplay' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
  if ((display = XOpenDisplay(NULL)) == NULL) {
                 ^
/Users/lukas/Trilinos-trilinos-release-13-2-0/packages/seacas/libraries/svdi/cgi/x11_vdix11.c:619:16: warning: incompatible integer to pointer conversion assigning to 'Display *' (aka 'struct _XDisplay *') from 'int' [-Wint-conversion]
  if ((display = XOpenDisplay(NULL)) == NULL) {
               ^ ~~~~~~~~~~~~~~~~~~
/Users/lukas/Trilinos-trilinos-release-13-2-0/packages/seacas/libraries/svdi/cgi/x11_vdix11.c:620:61: error: implicit declaration of function 'XDisplayName' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    fprintf(stderr, "svdi_x: cannot create window on %s\n", XDisplayName(NULL));

```

I've googled the error and I know what it means, but I can't find any way to fix it honestly. Any help is highly appreciated

**Comment by cgcgcg** [comment]
@trilinos/seacas

**Comment by dridzal** [comment]
@boblukas , I wonder if disabling X11 using

`-DTPL_ENABLE_X11=OFF`

circumvents this issue.

**Comment by boblukas** [comment]
Thanks a lot for your quick reply.

@dridzal  Now I don't see anymore those errors, but I get the following one after a while:
```
[ 27%] Linking C shared library libexodus.dylib
[ 27%] Building C object packages/zoltan/src/CMakeFiles/zoltan.dir/Utilities/Communication/comm_invert_plan.c.o
Undefined symbols for architecture x86_64:
  "_H5get_libversion", referenced from:
      _ex_config in ex_utils.c.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [packages/seacas/libraries/exodus/libexodus.13.2.dylib] Error 1
make[1]: *** [packages/seacas/libraries/exodus/CMakeFiles/exodus.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

I reconfigured with the flag `-DTPL_ENABLE_HDF5=ON`, but now I have a CMakeError saying 

```
Processing enabled TPL: HDF5 (enabled explicitly, disable with -DTPL_ENABLE_HDF5=OFF)
-- Using find_package(HDF5 ...) ...
-- HDF5 C compiler wrapper is unable to compile a minimal HDF5 program.
-- Found HDF5: /opt/local/lib/libhdf5.dylib (found version "1.12.1") found components: C 
CMake Error at cmake/tribits/common_tpls/FindTPLHDF5.cmake:50 (message):
  Trilinos is configured for MPI, HDF5 is not.

      Did CMake find the correct libraries?
      Try setting HDF5_INCLUDE_DIRS and/or HDF5_LIBRARY_DIRS explicitly.

```

HDF5 has been found, but I don't see again how to fix this.

**Comment by dridzal** [comment]
@boblukas , the error

`Trilinos is configured for MPI, HDF5 is not.`

may be informative.  I typically have to use a _parallel_ HDF5 library (built with whatever flavor of MPI is on my system).  It looks like you're missing several TPLs that are needed for your specified build: X11, parallel HDF5, ... do you have (parallel) netcdf?  If you don't need all packages from the specified build, you may be able to get by with simply specifying the location of the Boost TPL, and disabling the packages you don't need.  Otherwise, your build environment and configure script will need some work.

**Comment by gsjaardema** [comment]
You probably need to install a X11-development package on your Mac for the X11 issue, or disable X11 as someone else suggested.  The CMake process is supposed to detect this, but it looks like it is somehow detecting the X11 libraries, but the include files don't exist...

If you are building in parallel with MPI, then you need a parallel HDF5 and netCDF parallel build for your TPL's.  Can also add pNetCDF.

**Comment by gsjaardema** [comment]
Is this working for you?

**Comment by gsjaardema** [comment]
Closed.  Please reopen if still experiencing problems.
