### ISSUE TITLE
Zoltan2:  Status of deprecated code removal

### ISSUE THREAD

**Issue by tasmith4** [trilinos/Trilinos#10318]
## Question
@trilinos/zoltan2 @egboman 

The STK team has started noticing deprecated code warnings from Tpetra through Zoltan2, that are breaking our warnings-as-errors builds in Sierra.  Has the Zoltan2 team already eliminated all usage of Tpetra deprecated code in the latest version (i.e. do we just need to make sure we're using the latest develop)?  If not, what is the status/timeline of this removal?

cc @alanw0

**Comment by kddevin** [comment]
@tasmith4 I believe all deprecated warnings are already handled in Zoltan2.  If you see something different with the latest develop, please let us know.

**Comment by tasmith4** [comment]
Great, thanks @kddevin
