### ISSUE TITLE
Exception thrown in Thyra_BelosLinearOpWithSolveFactory_def.hpp for left preconditioners

### ISSUE THREAD

**Issue by bartgol** [trilinos/Trilinos#1032]
It appears that the class BelosLinearOpWithSolveFactory in stratimikos does not allow a left preconditioner (line 669). However, Belos itself does allow left preconditioners.

Is the stratimikos code not up to date?

**Comment by lucbv** [comment]
@trilinos/stratimikos

**Comment by bartlettroscoe** [comment]
I was not aware that Belos was updated to natively support left preconditioners and handle the requested norms correctly.  I wonder how they are computing accurate estimates of the norms as defined at:

* https://trilinos.org/docs/dev/packages/thyra/doc/html/classThyra_1_1LinearOpWithSolveBase.html#LOWSB_solve_criteria_sec 
* https://trilinos.org/docs/dev/packages/thyra/doc/html/structThyra_1_1SolveCriteria.html#details

?

With left preconditioning, Belos GMRES (for example) would have to compute the actual residual in order to do that (which requires solving the least-squares problem to compute `x` and then an application of the forward operator `A` to compute the residual `r = b - A*x`).  Is that what Belos GMREs does when using left preconditioning?

If Belos is not correctly handling the norms as described above to try to meet the desired tolerance, then the user (i.e. you) are better off implicitly creating the left-preconditioned system and then letting Belos solve that and then just live with setting tolerances on the preconditioned residual `|| P * (b -A*x)||`.

@trilinos/belos developers, how do Belos solvers handle left preconditioners and still allow the user to set a requested tolerance on a the real residual `||b - A*x||` instead of the preconditioned residual `|| P * (b -A*x)||`?

**Comment by bartlettroscoe** [comment]
Of course the one easy case is when you let the solver decide its own solve criteria by passing in solveCriteria=null in `solve()`:

* https://trilinos.org/docs/dev/packages/thyra/doc/html/classThyra_1_1LinearOpWithSolveBase.html#a284237bd162e713dd732aab3f199f3b1

If that is all you need, then this is easy to support.

**Comment by mhoemmen** [comment]
@bartlettroscoe If you use a left preconditioner with Belos' GMRES, the solver iterates first until the implicit residual norm meets the desired tolerance, then computes the explicit residual norm (`norm(b-A*x)`) at each iteration after that until _that_ norm meets the desired tolerance.  (I omitted scaling factors and some other details in the previous discussion, but that conveys the general idea.)

**Comment by bartlettroscoe** [comment]
Then it should be fairly straightforward to add support for left preconditioning for Belos.  We just need someone to add in the functionality and some appropriate tests.

@bartgol, what application needs this?

**Comment by bartgol** [comment]
I apologize for the delay in replying.

I need this for my own little application, built on top of Thyra/NOX (for the ModelEvaluator and nonlinear solve), and Tpetra/Belos/MueLu (for the linear algebra).

What kind of puzzles me is that Belos does support left preconditioners. And on top of that, if one creates the Thyra::DefaultPreconditioner with an unspecified preconditioner, it is still possible to make it a left preconditioner. These few lines of code in stratimikos/adapters/belos/src/Thyra_BelosLinearOpWithSolveFactory_def.hpp are the problem, and highlight the contradiction.

```
    if(unspecified.get()) {
      if (paramList_->get<bool>(LeftPreconditionerIfUnspecified_name, false))
        lp->setLeftPrec(unspecified);
      else
        lp->setRightPrec(unspecified);
    }
    else {
      // Set a left, right or split preconditioner
      TEUCHOS_TEST_FOR_EXCEPTION(
        left.get(),std::logic_error
        ,"Error, we can not currently handle a left preconditioner!"
        );
      lp->setRightPrec(right);

```
So if I want left preconditioning, I still can: I just have to create the preconditioner as "unspecified" and tell the factory to make it a left preconditioner if unspecified. So why not allowing it directly, inside the else below?

**Comment by bartlettroscoe** [comment]
@bartgol,

> These few lines of code in stratimikos/adapters/belos/src/Thyra_BelosLinearOpWithSolveFactory_def.hpp are the problem, and highlight the contradiction.
> 
> ```
>     if(unspecified.get()) {
>       if (paramList_->get<bool>(LeftPreconditionerIfUnspecified_name, false))
>         lp->setLeftPrec(unspecified);
>       else
>         lp->setRightPrec(unspecified);
>     }
>     else {
>       // Set a left, right or split preconditioner
>       TEUCHOS_TEST_FOR_EXCEPTION(
>         left.get(),std::logic_error
>         ,"Error, we can not currently handle a left preconditioner!"
>         );
>       lp->setRightPrec(right);
> ```
> 
> So if I want left preconditioning, I still can: I just have to create the preconditioner as "unspecified" and tell the factory to make it a left preconditioner if unspecified. So why not allowing it directly, inside the else below?

Okay, I was not aware that support for left preconditioning was added to the Thyra/Belos adapters.  Looking at the git log it appears that @ambrad added that in the commit d7fb26cd8:

```
commit d7fb26cd8c98a985a41cd3a4c8ae7aae24ee14fa
Author: Andrew M. Bradley <ambradl@sandia.gov>
Date:   Sun Apr 26 14:22:18 2015 -0600

    Stratimikos: Allow Belos preconditioner to be on left.
    
    If the input preconditioner's side is unspecified, allow the Stratimikos input
    block to place it on the left. This does not change current behavior; to trigger
    it, one must provide the new parameter
        Stratimikos -> Linear Solver Types ->Belos ->
          Left Preconditioner If Unspecified
    and set it to true.
    
    Build/Test Cases Summary
    Enabled Packages: Stratimikos
    0) MPI_DEBUG => passed: passed=39,notpassed=0 (0.92 min)
    1) SERIAL_RELEASE => Test case SERIAL_RELEASE was not run! => Does not affect push readiness! (-1.00 min)

M       packages/stratimikos/adapters/belos/src/Thyra_BelosLinearOpWithSolveFactory_def.hpp
M       packages/stratimikos/adapters/belos/src/Thyra_BelosLinearOpWithSolve_def.hpp
```

@ambrad, can you comment on the context for this change and if the Belos subclasses correctly handle the solve criteria as described [above](https://github.com/trilinos/Trilinos/issues/1032#issuecomment-277297015)?  That is, it looks like the code is not looking at the original residual norm, only the left-preconditioned residual norm.  Is that correct?  I think to match what is used in Belos, we would have to extend the numerator and denominator norms to include the norms of the preconditioned residual `||P*(A*x-b)||` (and initial residual `||(A*x0-b)||`):

* https://trilinos.org/docs/dev/packages/thyra/doc/html/structThyra_1_1SolveCriteria.html#details
* https://trilinos.org/docs/dev/packages/thyra/doc/html/group__Thyra__Op__Solve__fundamental__interfaces__code__grp.html#gaa00883ca75e1ab62ec24a5d697251734

Currently, the left preconditioned residual norm `||P*(A*x-b)||` is not supported by the Thyra::LinearOpWithSolveBase and related classes, only the unpreconditioned norm `||A*x-b||`.

@bartgol, can you please give your exact parameter list and the calling sequence for the various functions?  What solve criteria do you need to set?  That is, do you need to set a tolerance on the left-preconditioned residual like `||P*(A*x-b)|| / ||P*(A*x0-b)|| < requestedTol` or the unpreconditioned residual like `||(A*x-b)|| / ||(A*x0-b)|| < requestedTol`?  That makes a big difference.

Better yet, can you contribute a unit test for the Thyra/Belos adapters that matches your use case and push that to a topic branch and make a PR against the Trilinos 'develop' branch?  That would make it easier for us to make the changes in the classes to support your use case.   Hopefully, from all the information listed above, it may not be that hard after the automated tests are added.   We have to have automated tests for any supported functionality as specified at:

* https://github.com/trilinos/Trilinos/wiki/Trilinos-Testing-Policy

Thanks,

-Ross

**Comment by bartgol** [comment]
Well, I am not deeply interested in using a left preconditioner. Besides, my application is still in the early development stage. I was simply getting this error in my incremental build, while checking that everything else was in place correctly. I haven't really thought about the preconditioner details.

The reason why I opened this issue is that I was puzzled that I could use a left preconditioner with the "unspecified trick", building the Thyra preconditioner as

`Thyra::DefaultPreconditioner<double> prec(my_prec_oper);`

and having "Left Preconditioner If Unspecified"=true in the factory parameter list, while I could not do it if I built the Thyra preconditioner as

`Thyra::DefaultPreconditioner<double> prec(my_prec_oper,Teuchos::null);`

It seems to me that if the first is allowed, then the second way should be allowed too, since it would do the very same thing. Or else, there should be an exception thrown in the first case as well.

It's a matter of internal consistency, so to speak.

**Comment by bartlettroscoe** [comment]
> Well, I am not deeply interested in using a left preconditioner. Besides, my application is still in the early development stage. I was simply getting this error in my incremental build, while checking that everything else was in place correctly. I haven't really thought about the preconditioner details.

Okay, thanks for letting us know.  If left preconditioning is supported in one use case, it should be supported in all.  We will keep track of this and then take a look at this when we are doing other Stratimikos maintenance.
