### ISSUE TITLE
Trilinos+CUDA on Perlmutter

### ISSUE THREAD

**Issue by jrood-nrel** [trilinos/Trilinos#10339]
## Question
I'm curious if anyone has experience building with CUDA on Perlmutter? One issue I seem to be having is that using `MPICH_CXX=/path/to/nvcc_wrapper` doesn't seem to work for me, and `gcc` gets flags intended for `nvcc` and fails. Maybe @jhux2 has done this?

**Comment by jhux2** [comment]
@jrood-nrel I haven't built on Perlmutter myself.  Team @trilinos/muelu?

**Comment by cgcgcg** [comment]
@brian-kelley ?

**Comment by jewatkins** [comment]
I used these to build Trilinos for Albany on Perlmutter a couple months ago:
https://github.com/sandialabs/Albany/blob/master/doc/LandIce/perlmutter/prlm_gcc_modules.sh
https://github.com/sandialabs/Albany/blob/master/doc/LandIce/perlmutter/do-cmake-trilinos-prml-cuda-gcc
https://github.com/sandialabs/Albany/blob/master/doc/LandIce/perlmutter/nvcc_wrapper_a100
https://github.com/sandialabs/Albany/blob/master/doc/LandIce/perlmutter/install-boost-1.72.0.sh

It worked fine on a single node but there was some system issue on multiple nodes. They may have resolved it by now.

**Comment by jrood-nrel** [comment]
Thanks @jewatkins . I will look through those. Is your `nvcc_wrapper` modified at all?

**Comment by jewatkins** [comment]
It might be outdated. You probably only need to modify the host_compiler but I usually modify default_arch too:
```
default_arch="sm_80"
host_compiler=${NVCC_WRAPPER_DEFAULT_COMPILER:-"CC"}
```

**Comment by brian-kelley** [comment]
I have actually not built Trilinos (with MPI) on Perlmutter, only KokkosKernels. Now my cori login isn't working or I would try it. But I don't remember having to do anything too unusual - I used the nvcc_wrapper of current Kokkos develop, and set ``Kokkos_ARCH_AMPERE80=ON``.

**Comment by jhux2** [comment]
@jrood-nrel Did this answer your question?

**Comment by cwpearson** [comment]
I can't yet speak to whether Trilinos works, but I built it on perlmutter with the following:

```bash
    export CUDAARCHS="80" # for cmake 3.20+
    export MPICH_GPU_SUPPORT_ENABLED=1
    export CRAY_ACCEL_TARGET=nvidia80
    export NVCC_WRAPPER_DEFAULT_COMPILER=CC

    module load PrgEnv-gnu
    module load cmake/3.22.0
    module load cudatoolkit
    module load cpe-cuda
```

```bash
cmake .. \
-DCMAKE_CXX_COMPILER=`readlink -f ../Trilinos/packages/kokkos/bin/nvcc_wrapper` \
-DTrilinos_SOURCE_DIR=`readlink -f ../Trilinos` \
-DTPL_ENABLE_MPI=ON \
-DTrilinos_ENABLE_CPACK_PACKAGING=OFF \
-DTrilinos_ENABLE_Kokkos=ON \
-DTrilinos_ENABLE_Tpetra=ON \
-DKokkos_ENABLE_CUDA=ON \
-DKokkos_ARCH_AMPERE80=ON
```

**Comment by cwpearson** [comment]
I think a workaround right now is just to modify

Kokkos_Cuda_Half.hpp in packages/kokkos/core/src/Cuda and adjust all the comparison operators to use the CUDA intrinsics defined here: https://docs.nvidia.com/cuda/cuda-math-api/group__CUDA__MATH____HALF__COMPARISON.html#group__CUDA__MATH____HALF__COMPARISON
for the part guarded by `#ifdef __CUDA_ARCH__`
so something like this:

```c++
  KOKKOS_FUNCTION
  bool operator==(half_t rhs) const {
#ifdef __CUDA_ARCH__
    return static_cast<bool>(__heq(val, rhs.val));
#else
    return __half2float(val) == __half2float(rhs.val);
#endif
  }
```

probably when the Kokkos snapshot in trilinos is updated, this problem will go away

**Comment by cwpearson** [comment]
Aha this problem appears to be caused by not compiling my own translation units that include Trilinos headers for a sufficiently high CUDA architecture. 

I had to fix it with something like
```cmake
add_executable(main main.cpp)
target_link_libraries(main tpetra kokkoscore kokkoskernels)
target_include_directories(main PRIVATE ${Tpetra_INCLUDE_DIRS})
target_compile_options(main PRIVATE ${KOKKOS_CUDA_OPTIONS})
target_link_options(main PRIVATE ${KOKKOS_LINK_OPTIONS})
```

**Comment by cwpearson** [comment]
My CUDA-enabled build looks like this ( I have Trilinos as a submodule in another repository)

```bash
export CUDAARCHS="80" # for cmake 3.20+
export MPICH_GPU_SUPPORT_ENABLED=1
export CRAY_ACCEL_TARGET=nvidia80

export NVCC_WRAPPER_DEFAULT_COMPILER=CC

module load PrgEnv-gnu
module load cmake/3.22.0
module load cudatoolkit
module load cpe-cuda
```

```bash
cmake .. \
-DCMAKE_CXX_COMPILER=`readlink -f ../Trilinos/packages/kokkos/bin/nvcc_wrapper` \
-DTrilinos_SOURCE_DIR=`readlink -f ../Trilinos` \
-DTPL_ENABLE_MPI=ON \
-DTrilinos_ENABLE_CPACK_PACKAGING=OFF \
-DTrilinos_ENABLE_Tpetra=ON \
-DKokkosKernels_INST_OFFSET_INT=OFF \
-DKokkos_ENABLE_PROFILING=ON \
-DTrilinos_WARNINGS_AS_ERRORS_FLAGS="" \
-DTPL_ENABLE_CUDA=ON \
-DTPL_ENABLE_CUBLAS=OFF \
-DTPL_ENABLE_CUSOLVER=OFF \
-DKokkos_ARCH_AMPERE80=ON \
-DKokkosKernels_INST_MEMSPACE_CUDAUVMSPACE=OFF \
-DKokkos_ENABLE_CUDA=ON \
```
