### ISSUE TITLE
STK:  Does class PeriodicBoundarySearch work?

### ISSUE THREAD

**Issue by hillyuan** [trilinos/Trilinos#10347]
## Question
@trilinos/\<STK\>

I am trying to use class PeriodicBoundarySearch following its usage given in stk_search_util/unit_test/UnitTestSearchWithPeriodicBC.cpp but encounter a "not found" compile error when try to include <stk_search_util/PeriodicBoundarySearch.hpp>.  I also found that the file PeriodicBoundarySearch.cpp is included in the compile list still but its unit test of "UnitTestSearchWithPeriodicBC.cpp" is removed.

My question is:
1. Does class PeriodicBoundarySearch still work?
2. If it still works, how to include "PeriodicBoundarySearch.hpp" and revive the above unit test.

Much appreciated for your help.

**Comment by alanw0** [comment]
We will look into this and get back to you as soon as we can.

**Comment by alanw0** [comment]
It looks like our cmake files are not correct for activating that unit-test. We develop stk in a separate repository where we use a different build system. In that environment, this test does work. So I believe that PeriodicBoundarySearch is working. If you have the SearchUtil subproduct of stk enabled, then you should be able to include and use that header. We will try to push an update soon which corrects the cmake file such that this unit-test will be activated and built/run.

**Comment by hillyuan** [comment]
@alanw0 It is grateful to hear that I can use this class with no worry. Look forward to your update. Many thanks!
