### ISSUE TITLE
Improvement in Teuchos::SerialDenseSolver:::solve ()

### ISSUE THREAD

**Issue by bartgol** [trilinos/Trilinos#1034]
There is a check towards the beginning of the method to make sure that A and b are either both equilibrated or both not equilibrated. However, the check is done _after_ equilibrating b and _before_ factoring A (unless A is already factored/inverted)

Clearly, I could call the factor() method before calling solve(), and that would fix the problem. However, since solve() will automatically call factor() if needed, it would be nice if Teuchos did these checks only once it knows that the matrix is for sure factored (or inverted), since the problem of A not being factored may be solved in that step.

**Comment by bartgol** [comment]
@trilinos/teuchos

**Comment by lucbv** [comment]
@trilinos/teuchos

**Comment by hkthorn** [comment]
The pathway through the solve() method is complex given the different options for the solver (inverted/refined/etc.).  This is definitely an issue, but I need to extend the test suite to make sure that the solver does the right thing in all combinations of options.  This bit of logic is also inherited from the Epetra_SerialDenseSolver.  So, that solver would have the exact same issue.

**Comment by hkthorn** [comment]
This has been fixed for the SerialDenseSolver, SerialSymDenseSolver, SerialSpdDenseSolver, SerialBandDenseSolver, and SerialQRDenseSolver.

**Comment by mhoemmen** [comment]
Thanks @hkthorn !!!
