### ISSUE TITLE
Zoltan:  Failing Test in Spack-CM GCC 8.3.0 build

### ISSUE THREAD

**Issue by ZUUL42** [trilinos/Trilinos#10340]
## Bug Report
@trilinos/zoltan 

### Description
I have been working on moving the PR GCC 8.3.0 build over to use SEMS' spack-cm TPLs.
The result has 1 Zoltan test failing. [CDash Results](https://testing.sandia.gov/cdash/index.php?project=Trilinos&display=project&filtercount=3&showfilters=1&filtercombine=and&field1=site&compare1=61&value1=ascic141&field2=buildname&compare2=61&value2=PR-spack-cm-gcc-test-Trilinos_pullrequest_gcc_8.3.0-7065&field3=buildstamp&compare3=61&value3=20220328-2303-Experimental)
- Zoltan_ch_simple_parmetis_parallel

I'm not sure of the cause exactly, so the easy solution is to turn off this test for the GCC 8.3.0 PR build.
However, I wanted to check with Zoltan to see if they could be fixed before I put this build into PR testing next sprint.
They can always be turned back on later as well.

NOTE: This was updated after getting the int64 variants for METIS & ParMETIS TPL built and added to this build.

**Comment by ZUUL42** [comment]
I've had to move versions for a number of TPLs. If knowing the TPL version might help, those can be found [here](https://github.com/trilinos/Trilinos/compare/develop...ZUUL42:spack-cm-gcc), but here is a quick rundown.
SEMS archive TPLs currently used in the GCC 8.3.0 PR build:
```
module-load sems-archive-gcc          : 8.3.0
module-load sems-archive-ninja_fortran: 1.10.0
module-load sems-archive-openmpi      : 1.10.1
module-load sems-archive-boost        : 1.66.0/base
module-load sems-archive-zlib         : 1.2.8/base
module-load sems-archive-hdf5         : 1.10.6/parallel
module-load sems-archive-netcdf       : 4.7.3/parallel
module-load sems-archive-parmetis     : 4.0.3/parallel
module-load sems-archive-scotch       : 6.0.3/nopthread_64bit_parallel
module-load sems-archive-superlu      : 4.3/base
module-load sems-archive-git          : 2.10.1
module-load sems-archive-cmake        : 3.17.1
```
And using SEMS' spack-cm current offerings, we're moving to:
```
module-load sems-gcc            : 8.3.0
module-load sems-ninja          : 1.10.1
module-load sems-openmpi        : 4.0.5
module-load sems-boost          : 1.74.0
module-load sems-zlib           : 1.2.11
module-load sems-hdf5           : 1.10.7
module-load sems-netcdf-c       : 4.7.3
module-load sems-netcdf-cxx     : 4.2
module-load sems-netcdf-fortran : 4.5.3
module-load sems-parallel-netcdf: 1.12.1
module-load sems-metis          : 5.1.0
module-load sems-parmetis       : 4.0.3
module-load sems-scotch-int64   : 6.0.3
module-load sems-superlu        : 4.3
module-load sems-git            : 2.11.1
module-load sems-cmake          : 3.18.4
```

**Comment by kddevin** [comment]
@ZUUL42 The ParMETIS and Scotch TPLs should be built with the same index size (either 32-bit or 64-bit).  This test appears to have different sizes used for ParMETIS and Scotch (likely 32-bit for ParMETIS and 64-bit for Scotch).  Switching ParMETIS to build with 64-bit indices will likely fix all tests.  I believe 64-bit ParMETIS is used in Trillions' PR tests; is that correct?

**Comment by ZUUL42** [comment]
@kddevin, thanks. Most of the new SEMS TPLs are being built with the spack defaults.
I took a peek and it turns out ParMETIS defaults to int64 = off.
So, I sent SEMS a message to get that rebuilt with the int64 variant on.

Looks like METIS defaults to int64 = off as well and real64 = off.
Might you have any insight into if we'll need to have that one rebuilt as well?

**Comment by fryeguy52** [comment]
@ZUUL42 @kddevin I am syncing over parmetis + metis modules with +int64 turned on.  I agree that this should be the default in our configuration going forward

**Comment by ZUUL42** [comment]
I'm testing with the new TPLs. Thanks, @fryeguy52.
So, hopefully we can just close this with the PR that started it.

**Comment by ZUUL42** [comment]
Using sems-metis-**_int64_**/5.1.0 & sems-parmetis-**_int64_**/4.0.3, we're down to 1 failed test.

Since it's for `Zoltan_ch_simple_parmetis_parallel`, I'm guessing that's maybe due to not specifying any flag for parallel as the old TPL did, sems-archive-parmetis/4.0.3/**_parallel_**.

However, the only other spack options are:
```
Variants:
    Name [Default]                 Allowed values          Description
    ===========================    ====================    ===============================================

    build_type [RelWithDebInfo]    Debug, Release,         CMake build type
                                   RelWithDebInfo,         
                                   MinSizeRel              
    gdb [off]                      on, off                 Enables gdb support.
    int64 [off]                    on, off                 Sets the bit width of METIS's index type to 64.
    ipo [off]                      on, off                 CMake interprocedural optimization
    shared [on]                    on, off                 Enables the build of shared libraries.
```
I'm not sure if that would be helpful at all.
Would the "interprocedural" ipo give us what we need maybe?

Any thoughts, @kddevin, @fryeguy52?
