### ISSUE TITLE
Set Trilinos_MUST_FIND_ALL_TPL_LIBS=TRUE by default for Trilinos 15.0

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#10345]
@trilinos/framework

With Trilinos 14.0 coming up, this would be a good time to change the default for `Trilinos_MUST_FIND_ALL_TPL_LIBS` from `OFF` to `ON`.  (By setting `Trilinos_MUST_FIND_ALL_TPL_LIBS_DEFAULT` to `ON` as described [here](https://tribits.org/doc/TribitsUsersGuide.html#project-name-must-find-all-tpl-libs)).  It was turned off by default because it breaks backward compatibility but it causes problems for new users and new configurations (see, for example, https://github.com/trilinos/Trilinos/issues/10322#issuecomment-1071301714).

So as soon as the Trilinos 13.4 branch is created, we should make this change in the 'develop' branch.

**Comment by bartlettroscoe** [comment]
@ccober6, would it be possible to create GitHub Issue Milestone for Trilinos 14.0 so that we can place this and other issues like it to remind us to do these things for Trilinos 14.0?

**Comment by jwillenbring** [comment]
Was this done, or is this still of interest?

**Comment by ccober6** [comment]
Hmm...  We may have just missed this.  @sebrowne

**Comment by sebrowne** [comment]
I missed it for sure.  We can add it to the 14.0.1 release (I think that @hkthorn said that Xyce needs one, see #11685 )

**Comment by ccober6** [comment]
I am in favor of getting it in 14.0.1 and develop, so long as it doesn't cause stakeholders a headache.  They have not had any notice of this.  If it causes backward incompatibilities we will need to wait until Trilinos 15.0 (~Sept 2023).

**Comment by bartlettroscoe** [comment]
This will definitely break backward compatibility but likely in a good way 90% of the time.  And users that don't want this behavior can just set `-D Trilinos_MUST_FIND_ALL_TPL_LIBS=OFF` (which is backward compatible). 

Also, if I had realized that the Trilinos 14.0 release was immanent, I would have made sure and merge:

* https://github.com/TriBITSPub/TriBITS/pull/560
* https://github.com/trilinos/Trilinos/pull/11546

because that might technically break backward compatibility in some corner cases.

**Comment by bartlettroscoe** [comment]
FYI, the conversation about backward compatibility seems to have evolved over the last few years.  Now [semver](https://semver.org) seems to differentiate "major" and "minor" breaks in backward compatibility and incrementing the major version number.  For example, see:

* https://semver.org/#what-if-i-inadvertently-alter-the-public-api-in-a-way-that-is-not-compliant-with-the-version-number-change-ie-the-code-incorrectly-introduces-a-major-breaking-change-in-a-patch-release

If a single configure option can restore backward compatibility and if the change is backward compatibility is obvious, then I think that should not warrant an increment of the major version number.

In order words, I think changing the default of `Trilinos_MUST_FIND_ALL_TPL_LIBS` from `OFF` to `ON` should be okay in a patch release (also since most customers will not touch an `X.Y.0` release and will wait for the `X.Y.1` release before trying to use it).

Up to this point, very good backward compatibility is maintained for customers my setting a few configure options.

**Comment by ccober6** [comment]
@bartlettroscoe if you are comfortable with us patching 14.0 and merging to develop, I would say let's give it try and if we run into issues we can back it out.

@sebrowne, we should create a Trilinos 15.0 issue and link issues related to the release to help include issues like this with 15.

**Comment by bartlettroscoe** [comment]
@sebrowne, @ccober6, let's not forget to do this after Trilinos 14.4 is branched!

**Comment by bartlettroscoe** [comment]
@sebrowne and @ccober6, I created the GitHub Issue milestone [trilinos-15.0](https://github.com/trilinos/Trilinos/milestone/54) to help remind people of what needs to be done before the Trilinos 15.0 release.

**Comment by sebrowne** [comment]
Thanks Ross!  I'm all in favor of putting this in ASAP after we get 14.4 out the door (should be very soon).

**Comment by sebrowne** [comment]
@bartlettroscoe do you want me to do this now that 14.4 is out?

**Comment by bartlettroscoe** [comment]
> @bartlettroscoe do you want me to do this now that 14.4 is out?

Yes, but we will need to write a release note for this.  And this may break some customer's configure scripts because they may have had extra libs they did not need that did not get found but it happened to work anyway.

**Comment by srbdev** [comment]
@bartlettroscoe should I make the change under `cmake/tribits/core/package_arch/TribitsGlobalMacros.cmake` on line 568 or should it only be made specific to Trilinos, with the `Trilinos_` prefix?

**Comment by bartlettroscoe** [comment]
> @bartlettroscoe should I make the change under `cmake/tribits/core/package_arch/TribitsGlobalMacros.cmake` on line 568 or should it only be made specific to Trilinos, with the `Trilinos_` prefix?

No, see:

* https://tribitspub.github.io/TriBITS/users_guide/index.html#project-name-must-find-all-tpl-libs

Setting this in the `CMakeLists.txt` file makes more sense since this does not impact the dependency logic.

**Comment by bartlettroscoe** [comment]
This was completed with the merge of PR:

* #12258
