### ISSUE TITLE
Possible bug in Teuchos::SerialDenseSolve::factor()

### ISSUE THREAD

**Issue by bartgol** [trilinos/Trilinos#1035]
In case refineSolution_==true, the matrix and the factor are stored separately. However, the way the factor is created, that is,

Factor_ = rcp( new SerialDenseMatrix<OrdinalType,ScalarType>(*Matrix_) );

is buggy (I think). In fact, if the original matrix was created as a view (of either another matrix or some raw pointer), then the copy constructor will not do a deep copy of the array values_ stored in *Matrix_, but will only copy the pointer. I believe the above line should be replaced with

Factor_ = rcp( new SerialDenseMatrix<OrdinalType,ScalarType>(Teuchos::Copy, *Matrix_) );

to ensure that *Factor_ is indeed a deep copy of *Matrix_, regardless of how *Matrix_ was created.

**Comment by lucbv** [comment]
@trilinos/teuchos

**Comment by mhoemmen** [comment]
If I remember right, the copy constructor behavior was a "feature not a bug."  There was an issue a while back with how Dakota was using this class.  @hkthorn , does this sound familiar?  On the other hand, the issue a while back related to the copy constructor, not to this internal issue.

@bartgol , it looks like you are interested in solving dense linear systems.  Could you explain your use case a little better?

**Comment by bartgol** [comment]
I have several small (1<order<5) dense linear systems to solve. I am giving my self the option of either using Teuchos::LAPACK directly or rely on Teuchos::SerialDenseSolver (in case these systems will need equilibration and/ore iterative refinement; I am not yet using real data, so I don't know whether this will be actually needed).

I may have phrased my thoughts badly: I am not saying the copy constructor is a bug. That's actually fine. I am suggesting that that copy constructor should not be used there, or else we may end up without a _real_ copy of the original matrix. I think using the "copy-constructor" I mentioned in my previous post should fix the problem (it appears to fix it in my code).

**Comment by hkthorn** [comment]
@bartgol @mhoemmen As Mark said, the copy constructor's behavior was emulating Epetra's SerialDenseMatrix, so that is a "feature not a bug".  However, that would result in the WRONG behavior if the matrix was a view of a larger matrix ...  I will fix that.

**Comment by mhoemmen** [comment]
@bartgol wrote:
> I have several small (1<order<5) dense linear systems to solve. I am giving myself the option of either using Teuchos::LAPACK directly or rely on Teuchos::SerialDenseSolver . . . .

We are working on batched thread-parallel BLAS / LAPACK interfaces too.  @kyungjoo-kim can tell you more about his work there.  This interfaces could pay off under the following conditions:

  1. If you can do the solves all at once rather than one after another in sequence, and 
  2. if you have enough solves to do that it might pay to thread-parallelize across them.

**Comment by bartgol** [comment]
That's exactly my case. I will ask him about it. Thanks!

**Comment by kyungjoo-kim** [comment]
I have worked on KokkosKernels -- GEMM, TRSM and LU (for line smoother). Our target problem consists of 512 instances of small dense problems with blocksizes 5, 9, 15, and 20. It performs quite well for small matrices as we use vectorization explicitly almost everywhere; however, it may require repacking to different data format.

**Comment by hkthorn** [comment]
The potential issue in the SerialDenseSolver::factor() method has been resolved.

**Comment by mhoemmen** [comment]
Thanks @hkthorn !!!
