### ISSUE TITLE
Piro fails to compile

### ISSUE THREAD

**Issue by aprokop** [trilinos/Trilinos#1036]
@trilinos/nox @trilinos/piro

Here is the config:
```cmake
#!/bin/sh
EXTRA_ARGS=$@


ARGS=(
    -D CMAKE_BUILD_TYPE=RELWITHDEBINFO

    -D BUILD_SHARED_LIBS=ON

    ### COMPILERS AND FLAGS ###
    -D Trilinos_ENABLE_Fortran=OFF
    -D CMAKE_CXX_FLAGS="-Wall -Wextra"

    ### TPLS ###
    -D TPL_ENABLE_MPI=ON
    -D TPL_ENABLE_BLAS=ON
    -D TPL_ENABLE_LAPACK=ON

    ### ETI ###
    -D Trilinos_ENABLE_EXPLICIT_INSTANTIATION=ON

    ### PACKAGES CONFIGURATION ###
    -D Trilinos_ENABLE_ALL_PACKAGES=OFF
    -D Trilinos_ENABLE_ALL_OPTIONAL_PACKAGES=OFF
    -D Trilinos_ASSERT_MISSING_PACKAGES=OFF

    -D Trilinos_ENABLE_TESTS=OFF
    -D Trilinos_ENABLE_EXAMPLES=OFF

    -D Trilinos_ENABLE_Belos=ON
    -D Trilinos_ENABLE_Epetra=ON
    -D Trilinos_ENABLE_EpetraExt=ON
    -D Trilinos_ENABLE_ML=ON
    -D Trilinos_ENABLE_NOX=ON
    -D Trilinos_ENABLE_Piro=ON
    -D Trilinos_ENABLE_Teuchos=ON

    ### MISC ###
    -D CMAKE_EXPORT_COMPILE_COMMANDS=OFF
    -D Trilinos_ENABLE_INSTALL_CMAKE_CONFIG_FILES=OFF
    -D Trilinos_DEPS_XML_OUTPUT_FILE=""

    )
cmake -GNinja "${ARGS[@]}" $EXTRA_ARGS ../../
```

Here are the errors:
```
../../packages/piro/src/Piro_Epetra_LOCASolver.hpp:49:25: fatal error: LOCA_Epetra.H: No such file or directory
../../packages/piro/src/Piro_Epetra_NOXSolver.hpp:49:24: fatal error: NOX_Epetra.H: No such file or directory
../../packages/piro/src/Piro_Epetra_PerformSolve.cpp:51:42: fatal error: Thyra_EpetraModelEvaluator.hpp: No such file or directory
```

**Comment by aprokop** [comment]
Removing the line
```
  -D Trilinos_ENABLE_ALL_OPTIONAL_PACKAGES=OFF
```
results in successful compilation but takes longer as more packages are enabled.

**Comment by aprokop** [comment]
The NOX and LOCA variables are fixed by adding
```cmake
-D Trilinos_ENABLE_Ifpack=ON
-D Trilinos_ENABLE_AztecOO=ON
```
This is due to the following code in  `packages/nox/CMakeLists.txt` and `packages/nox/src-epetra/CMakeLists.txt`:
```cmake
COMBINED_OPTION( NOX_ENABLE_ABSTRACT_IMPLEMENTATION_EPETRA
  DEP_OPTIONS_NAMES NOX_ENABLE_AztecOO NOX_ENABLE_Epetra NOX_ENABLE_Ifpack
...
IF (NOX_ENABLE_ABSTRACT_IMPLEMENTATION_EPETRA)
  TRIBITS_ADD_LIBRARY(
    noxepetra
    HEADERS ${HEADERS}
    SOURCES ${SOURCES}
    DEPLIBS nox
    )
ENDIF()
```
Piro does not check for those conditions and includes the headers automatically. 

The Thyra error is fixed by adding
```cmake
-D Trilinos_ENABLE_ThyraEpetraExtAdapters=ON
```
as the corresponding header file is not in the core Thyra.

In general, there are a lot of dependencies issues in the whole Piro/NOX/Thyra interaction for Epetra. Some applications are still using this stack (ACME/CAM, for instance), which may be hit by these hidden bugs.

I'd like to fix this but would need some help as I'm not certain about which components are optional and which are not. @rppawlo Any suggestions?

**Comment by rppawlo** [comment]
@aprokop The quick fix is for Piro to enable the NOX_Epetra support only if the correct nox adapter is enabled - i.e. check for the cmake flag NOX_ENABLE_ABSTRACT_IMPLEMENTATION_EPETRA to be enabled.  Longer term, we could split out the nox adapters into separate subpackages and then the piro interface could have separate dependencies on the nox subpackages. A better long term design fix (but more costly), is to eliminate all the nox adapters. We should code nox directly to the thyra abstractions and thyra would handle the adapter layers. Unfortunately we have internal users relying on the Epetra and straimikos adapter layers and it will take much work in applications to transition everyone to thyra before deprecating. If you would like to talk more, I would be happy to stop by your office later today.

**Comment by tawiesn** [comment]
I can state that there are also external customers using the Epetra adapter layers for NOX.
