### ISSUE TITLE
MueLu: error: ‘EpetraOperator’ is not a member of ‘MueLu’    Teuchos::RCP<MueLu::EpetraOperator> mueLu_Diffusion;

### ISSUE THREAD

**Issue by ztdepztdep** [trilinos/Trilinos#10369]
I tried to work with MueLu following the userguide . but it seems the MueLu namespace doesn't has EpetraOperaotor, and I cann't find it in the help file also.
Could you please help me out.

**Comment by cgcgcg** [comment]
https://github.com/trilinos/Trilinos/blob/7bc4eb697c4ccd9fab1742661da3260a1069d41a/packages/muelu/adapters/epetra/MueLu_EpetraOperator.hpp#L63

**Comment by ztdepztdep** [comment]
> https://github.com/trilinos/Trilinos/blob/7bc4eb697c4ccd9fab1742661da3260a1069d41a/packages/muelu/adapters/epetra/MueLu_EpetraOperator.hpp#L63

 fatal error: MueLu_EpetraOperator.hpp: No such file or directory

It seems the installation process doesn't copy this head file. Could you please help me out

**Comment by cgcgcg** [comment]
Please post how you call CMake and the corresponding output.

**Comment by cgcgcg** [comment]
No response
