### ISSUE TITLE
Thyra::defaultSpmdVectorSpace bug

### ISSUE THREAD

**Issue by jmgate** [trilinos/Trilinos#1037]
In the `Thyra::defaultSpmdVectorSpace()` routine that takes four arguments, the fourth argument is `const int isLocallyReplicated = false`.  It looks like that `int` should be a `bool` instead.  @trilinos/thyra

**Comment by mhoemmen** [comment]
@trilinos/thyra

**Comment by bartlettroscoe** [comment]
Simple copy-and-paste error.  I will fix and push.

**Comment by bartlettroscoe** [comment]
Should be resolved as of commit 129943f.  @jmgate, please add a comment to confirm this is fixed.

BTW, how did you notice the problem with the type of this input parameter?  Did you just happen to see this or did something bad happen?

**Comment by jmgate** [comment]
Yup, it's fixed.  It didn't hurt anything&mdash;I was just trying to figure out how to create a `DefaultSpmdVectorSpace` and was trying to figure out if I needed it to be locally replicated or not.  When I saw `int .* = false`, I did a double-take.

**Comment by bartlettroscoe** [comment]
> Yup, it's fixed.

Excellent!  I will go ahead and close this now.
