### ISSUE TITLE
Trilinos 11.10.2

### ISSUE THREAD

**Issue by aprokop** [trilinos/Trilinos#1039]
@trilinos/framework @bmpersc @jwillenbring 

On trilinos.org website one can download version 11.10.2 [here](https://trilinos.org/download/previous-releases/download-11-10/). However, I cannot figure out how to get the corresponding hash from trilinos source tags and/or branches. None of them seem to contain any combination of numbers 11, 10 and 2. The only thing I see is 11.10.1 release there.

**Comment by jwillenbring** [comment]
@bmpersc Do you know why there isn't a corresponding tag for the 11.10.2 release update?

**Comment by bmpersc** [comment]
It is possible I just forgot to add it, or push it. I'll have to look into it.

**Comment by aprokop** [comment]
I don't think this anymore (I think). Closing.
