### ISSUE TITLE
How to set the minimum iteratoin number in the Azetcoo package.

### ISSUE THREAD

**Issue by ztdepztdep** [trilinos/Trilinos#10395]
How to set the minimum iteratoin number in the Azetcoo package.
I only find the maxmum iteration number, could you please give me some advices.

**Comment by hkthorn** [comment]
Sorry, but there is no such parameter as a "minimum iteration" for iterative solvers.  Because, if given the solution vector with the requested accuracy as the initial guess, they may not need to iterate at all.  Why do you feel you need one?

**Comment by jhux2** [comment]
Feel free to reopen if you still have questions.
