### ISSUE TITLE
MueLu:  Driver Matrix Equilibration

### ISSUE THREAD

**Issue by Adrian-Diaz** [trilinos/Trilinos#10392]
## Question
@trilinos/\<MueLu\>

Greetings,

I was trying out the matrix equilibration function in the driver, which by the way seems to be missing the scaling for the rhs and solution vector as can be seen in the ifpack2 example \packages\ifpack2\example\RelaxationWithEquilibration.cpp, and found that I couldn't get certain systems to converge anymore after rescaling, both with the Driver's equilibration and the equilibration routine from the ifpack 2 example. As an example I tried
  mpirun -np 4  ./MueLu_Driver.exe --xml=elasticity3D.xml --matrixType=Elasticity3D --nx=31 --ny=31 --nz=301 --equilibrate=diag

which fails to converge after 200 iterations of Belos. The 1-norm option converges, albeit much slower than the case with no equilibration. Not sure if this is obsolete code or not, if so is there a more tried and true equilibration I can use from Trilinos?

Sincerely,
Adrian Diaz

**Comment by cgcgcg** [comment]
Not sure who added that feature.@csiefer2?

**Comment by cgcgcg** [comment]
@trilinos/muelu

**Comment by csiefer2** [comment]
Mark added that originally and I relocated it.  It is definitely not well tested

**Comment by jhux2** [comment]
Closing, but please reopen if you have further questions.
