### ISSUE TITLE
How to ExtractCrsDataPointers for Amgcl solver.

### ISSUE THREAD

**Issue by ztdepztdep** [trilinos/Trilinos#10402]
I want to extract the csr format matrix from the Epetra_FECrsMatrix A , and I have found the ExtractCrsDataPointers API , but it can only give the local infors. 
the Amgcl solver need the global csr format for parallel computations. could you please give me some help.

**Comment by cgcgcg** [comment]
I am not an Epetra expert. The matrix is saved using local indices. If you need global indices, row and column maps contain that information.
