### ISSUE TITLE
doxygen 1.8.13 incompatibility

### ISSUE THREAD

**Issue by ilovezfs** [trilinos/Trilinos#1040]
I'm having to set `-DPyTrilinos_DOCSTRINGS:BOOL=OFF` due to an incompatibility with doxygen 1.8.13, which ultimately leads to
```
[ 91%] Built target PanzerDiscFE_SacadoExample
[ 92%] Built target pytrilinos
[ 92%] Swig source /tmp/trilinos-20170129-37787-ninfii/Trilinos-trilinos-release-12-10-1/packages/PyTrilinos/src/LOCA.Epetra.Interface.i
/tmp/trilinos-20170129-37787-ninfii/Trilinos-trilinos-release-12-10-1/packages/PyTrilinos/src/LOCA.Epetra.Interface.i:147: Error: Unable to find 'LOCA_dox.i'
/tmp/trilinos-20170129-37787-ninfii/Trilinos-trilinos-release-12-10-1/packages/PyTrilinos/src/Epetra.i:260: Error: Unable to find 'Epetra_dox.i'
make[2]: *** [packages/PyTrilinos/src/LOCA.Epetra.InterfacePYTHON_wrap.cpp] Error 1
make[1]: *** [packages/PyTrilinos/src/CMakeFiles/PyTrilinos_LOCA_Epetra_Interface.dir/all] Error 2
make: *** [all] Error 2
```

Looking back in the log, there are errors in the initial cmake configuration: https://gist.github.com/ilovezfs/a5f72851bbeecded8d4b87a996b1b3ad

This does not occur if I use doxygen 1.8.12 or 1.8.11.

**Comment by wfspotz** [comment]
This, ultimately, looks like bug with doxygen 1.8.13. I used `doxygen -u` to upgrade the doxyfiles within PyTrilinos, and made some modifications to Epetra and EpetraExt source files to prevent certain warnings, but this did not get the generation of docstrings to work. Doxygen 1.8.13 is crashing with a segfault and no error messages or warnings to help diagnose the problem.

**Comment by wfspotz** [comment]
For PyTrilinos, I have my own doxyfiles that produce XML that is in turn used to generate Python docstrings for wrapped code. With doxygen 1.8.13, these doxyfiles cause doxygen to crash with a segfault (more specifically, Epetra when processing `Epetra_BlockMap`, and EpetraExt when processing `EpetraExt::LightweightMapData`. Has anyone else seen this behavior with the standard Epetra and EpetraExt doxyfiles?

**Comment by wfspotz** [comment]
I have confirmed that this is a doxygen bug in version 1.8.13 and that doxygen developers claim to have fixed it in the current git repository.

**Comment by wfspotz** [comment]
I have pushed a change to the PyTrilinos build system where if PyTrilinos is enabled and doxygen is version 1.8.13, you get a fatal error. You can get around it by setting PyTrilinos_DOCSTRINGS=OFF or by changing your version of doxygen.

**Comment by gpkc** [comment]
@wfspotz This is happening with me with doxygen version 1.8.11:
```
/home/guilherme/Deps/Trilinos/packages/PyTrilinos/src/TriUtils.i:115: Error: Unable to find 'TriUtils_dox.i'
/home/guilherme/Deps/Trilinos/packages/PyTrilinos/src/Epetra.i:260: Error: Unable to find 'Epetra_dox.i'
packages/PyTrilinos/src/CMakeFiles/PyTrilinos_TriUtils.dir/build.make:61: recipe for target 'packages/PyTrilinos/src/TriUtilsPYTHON_wrap.cpp' failed
make[2]: *** [packages/PyTrilinos/src/TriUtilsPYTHON_wrap.cpp] Error 1
CMakeFiles/Makefile2:3029: recipe for target 'packages/PyTrilinos/src/CMakeFiles/PyTrilinos_TriUtils.dir/all' failed
make[1]: *** [packages/PyTrilinos/src/CMakeFiles/PyTrilinos_TriUtils.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2
```

I will try updating. However, this is the current doxygen version on my Fedora dist.

**Comment by wfspotz** [comment]
@gpkc Can you post the output from running `cmake`?

**Comment by gpkc** [comment]
@wfspotz Hmm now that I have checked the output, it is giving these errors:
```
  File "/home/guilherme/Deps/Trilinos/packages/PyTrilinos/doc/Doxygen/docstrings.py", line 29
    print "Running doxygen on package", package, "...",
                                     ^
SyntaxError: Missing parentheses in call to 'print'
```

I'm trying to compile for Python3.

**Comment by gpkc** [comment]
@wfspotz It seems there are a few incompatibilities with Python3 from the PyTrilinos doxygen tools. I think I have fixed them, but I might have changed some functionality. Do you want to take a look, or you will fix them by yourself?

**Comment by wfspotz** [comment]
I thought I had already fixed them myself. I am going to have to do some digging to figure out why these files are not updated. You are trying to build from the develop branch?

**Comment by wfspotz** [comment]
@gpkc When you configure, do you enable the Komplex package? My solution is working for all the other packages, but I get a weird failure when it is processing Komplex that I haven't been able to correct yet.

**Comment by gpkc** [comment]
@wfspotz I was on the master branch. Regarding the Komplex package, it was disabled...
I tried running this on the develop branch but the same python errors happened.

**Comment by wfspotz** [comment]
@gpkc OK. I have been working through a fix. It includes handling the reasons that I did not catch that these docstring Python scripts were still Python 2, so I have to assume that my fixes are more extensive than yours. I was thinking that if your fixes were a little different from mine and they worked with Komplex, then I could leverage them. As soon as I get something working, I will push to develop.

**Comment by gpkc** [comment]
@wfspotz Hmm I was able to generate the Komplex docstrings here. However, again, my fixes are very simple and were made to just make the cmake process work. Your fixes are probably better.

**Comment by wfspotz** [comment]
@gpkc What did you do with the `my_str()` function in `doxy2swig.py`? I guess the other thing is, I'm trying to write code that works with both Python 2 and 3.

**Comment by gpkc** [comment]
@wfspotz I changed the except clause to:
```
except UnicodeEncodeError as e:
```

It works with Python3 and Python2.6+

**Comment by wfspotz** [comment]
@gpkc Yeah, I did that as well (although there is no need to capture the exception in `e`). And when it gets called from `clean_pieces()`?

**Comment by gpkc** [comment]
@wfspotz Well I have removed the if that checks if str is unicode on `clean_pieces()` and was calling my_str everytime. I wasn't aware of the reason for that check, and it ended up working:
```
-            if isinstance(i, unicode):
-                i = my_str(i)
+            i = my_str(i)
```

**Comment by wfspotz** [comment]
@gpkc OK, thanks. I may have been this particular issue more complicated than it needed to be.

**Comment by gpkc** [comment]
@wfspotz If you'd like to try to keep the same logic for this function, I've found this on StackOverflow:
https://stackoverflow.com/questions/4987327/how-do-i-check-if-a-string-is-unicode-or-ascii
The answer by Dave Burton talks about compatibility between Python3 and Python2 on this matter. It seems quite ugly though.

**Comment by wfspotz** [comment]
I suspect the problem I was seeing but you were not might be related to the fact that I was using Python 3.5 and you were using Python 3.6. There was a Unicode character in `Complex_LinearProblem.h` which I have changed to ASCII, and the new scripts work for me with both Python 2 and Python 3. I have pushed it to the `develop` branch.

**Comment by gpkc** [comment]
Oh, I see. Glad to hear it worked out.
