### ISSUE TITLE
Stratimikos: Headers not installed for BelosLinearOpWithSolveFactory

### ISSUE THREAD

**Issue by barche** [trilinos/Trilinos#1042]
It seems the following generated headers don't get installed:
```
Thyra_BelosLinearOpWithSolve.hpp
Thyra_BelosLinearOpWithSolveFactory.hpp
Thyra_GeneralSolveCriteriaBelosStatusTest.hpp
```
Stumbled upon this trying to build a Stratimikos-configured Tpetra-based solver.

**Comment by aprokop** [comment]
@trilinos/stratimikos

**Comment by bartlettroscoe** [comment]
Easy fix.  I will take care of this and push to 'develop'.

**Comment by bartlettroscoe** [comment]
Should be resolved as of commit 47ebfff.  @barche, please pull the 'develop' branch and try this out and add a comment for if it passes or fails.

**Comment by barche** [comment]
Confirmed, this fixes it. Sorry for the delay, I didn't have a developer build installed.

**Comment by bartlettroscoe** [comment]
Thanks!  Closing as complete.
