### ISSUE TITLE
Trilinos fails to build on Crusher

### ISSUE THREAD

**Issue by jrood-nrel** [trilinos/Trilinos#10424]
### Description
While this worked in the past (March 1 specifically), I currently see this error when trying to build on Crusher:
```
  >> 1302    /tmp/mdinit-d8efb4.ll:11028:45: error: value for 'arg' too large, limit is 65535
     1303    !1171 = !DILocalVariable(scope: !1165, arg: 71023, file: !3, line: 1214, type: !12, flags: 64)
     1304                                                ^
     1305    1 error generated.
  >> 1306    make[2]: *** [packages/seacas/libraries/supes/CMakeFiles/supes.dir/build.make:375: packages/seacas/libraries/supes/CMakeFiles/supes.dir/
             mem_mgr/mdinit.F.o] Error 1
```
I'm just building on the CPU, which is all I need there at the moment.

**Comment by jhux2** [comment]
@trilinos/seacas @gsjaardema Would you mind having a look at this?

**Comment by jhux2** [comment]
ping

**Comment by gsjaardema** [comment]
Sorry, just saw this for the first time.   Not sure why I missed it earlier...

What compiler / version is being used for this?

**Comment by jrood-nrel** [comment]
`PrgEnv-amd` and `rocm/5.0.2` was being used here.

**Comment by gsjaardema** [comment]
OK. I'm not familiar with NREL compute systems which I assume Crusher is part of...  Can you give me more info on the architecture of Crusher and the compiler that `PrgEnv-amd` selects.

@jhux2 -- Do you know of a system we have that would be a close analog of Crusher?

**Comment by jrood-nrel** [comment]
Crusher is OLCF.

**Comment by jhux2** [comment]
@gsjaardema I think the closest would be caraway.

**Comment by gsjaardema** [comment]
It looks like PrgEnv-amd uses `amdflang` for the fortran compiler.  The code that shows the failure above (packages/seacas/libraries/supes/mem_mgr/mdinit.F I think) has not changed in 2-6 years except for the modification of a `#if` 10 months ago.  

My best suggestion is that the flang compiler version changed since March 1? and for some reason is generating some bad code for something in mdinit.F.  

Do you have a flang person you can show this to?   I will continue to see if I can reproduce here, but I don't think that any change I made caused the difference from working on March 1 to not working now...

**Comment by jjellio** [comment]
I can try this on LLNL's machine and see about pushing on it from the COE side. Let me see if I can reproduce it.

**Comment by jjellio** [comment]
It does not look like I can reproduce it, the system I have access to does not have all the modules.  I will point our COE rep to this topic though.

**Comment by jrood-nrel** [comment]
Actually this may have been resolved in Trilinos based on someone on our team building successfully on Crusher today. I haven't been able to try it again myself yet.

**Comment by jrood-nrel** [comment]
How can I disable `supes`?

**Comment by jjellio** [comment]
Skimming my build, I see:
```
-- Setting SEACAS_ENABLE_SEACASSupes=ON since Trilinos_ENABLE_SEACAS=ON AND Trilinos_ENABLE_SEACASSupes=ON
-- Setting SEACAS_ENABLE_SEACASSuplib=ON since Trilinos_ENABLE_SEACAS=ON AND Trilinos_ENABLE_SEACASSuplib=ON
-- Setting SEACAS_ENABLE_SEACASSuplibC=ON since Trilinos_ENABLE_SEACAS=ON AND Trilinos_ENABLE_SEACASSuplibC=ON
-- Setting SEACAS_ENABLE_SEACASSuplibCpp=ON since Trilinos_ENABLE_SEACAS=ON AND Trilinos_ENABLE_SEACASSuplibCpp=ON
```

So maybe try `SEACAS_ENABLE_SEACASSupes=OFF` or maybe `Trilinos_ENABLE_SEACASSupes=OFF`. Not sure if that will completely disable it (may have to add the offs to each one)

**Comment by jrood-nrel** [comment]
Ah, that built! Thanks! I will see if I can run on Crusher with this change now.

**Comment by jrood-nrel** [comment]
It's with `PrgEnv-amd` which is flang 14.

**Comment by gsjaardema** [comment]
Not sure what portion(s) of seacas you need/want, but you can also disable fortran which will leave you with most of the libraries and some C/C++ executables.  Can also only build only exodus, or only IOSS and exodus.
