### ISSUE TITLE
Upgrade main Trilinos CDash site April 2022

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#10438]
@trilinos/framework 

@zackgalbreath needs to upgrade the main Trilinos CDash site testing.sandia.gov/cdash/.  He just needs to propose a time to do it and the site will be down and not accepting results during that time period.

**Comment by zackgalbreath** [comment]
Unless anyone objects, I plan to perform this upgrade on Monday, April 18

**Comment by ZUUL42** [comment]
@zackgalbreath Well, currently the vortex jenkins agent is offline. So, the autotester is down. So, from a framework perspective, I'd say the sooner the better. If done while it's still down, it wouldn't affect us.

**Comment by bartlettroscoe** [comment]
>  So, the autotester is down. So, from a framework perspective, I'd say the sooner the better. If done while it's still down, it wouldn't affect us.

@zackgalbreath, in that case, the best time to upgrade would be after about 8 AM MDT (10 AM EDT) after all of the nightly builds have posted.  And as @ZUUL42 says, the sooner the better (even today if you have the time).

**Comment by csiefer2** [comment]
> @zackgalbreath Well, currently the vortex jenkins agent is offline. So, the autotester is down. So, from a framework perspective, I'd say the sooner the better. If done while it's still down, it wouldn't affect us.

See #10428

**Comment by zackgalbreath** [comment]
Thanks for letting me know. Maintenance on testing.sandia.gov is underway.

**Comment by zackgalbreath** [comment]
Maintenance & upgrade are now complete. I performed a test submission and clicked around pretty thoroughly & everything looked good to me. Nonetheless, please let us know if you notice any unusual behavior from https://testing.sandia.gov/cdash

**Comment by ZUUL42** [comment]
@zackgalbreath thanks

**Comment by bartlettroscoe** [comment]
I can verify the upgrade has been done and the site shows updated version at the bottom left:

![image](https://user-images.githubusercontent.com/1959736/163475368-fdcc1d7e-39dd-418c-8464-380f33364ff5.png)

I will go ahead and close this.  Please report any defects and we will make sure they get fixed.
