### ISSUE TITLE
MueLu:  Solve with symmetric matrix storage

### ISSUE THREAD

**Issue by Adrian-Diaz** [trilinos/Trilinos#10449]
## Question
@trilinos/\<MueLu\>

Greetings, I was looking for an example where MueLu was used with a Tpetra crs matrix with a graph corresponding to a symmetric matrix storing only the upper or lower triangular matrix elements. I couldn't find much info on it however, is there a set of parameters that can be used to have MueLu operate with a matrix stored that way? Thanks for any help on the matter.

Adrian Diaz

**Comment by jhux2** [comment]
@Adrian-Diaz MueLu generally assumes that for unstructured grids, the matrix is stored as a CRS matrix.  Afaik, there's not support in Tpetra for taking advantage of matrix symmetry in storage.

**Comment by Adrian-Diaz** [comment]
Tpetra technically lets you already since you can just store the upper or lower elements. I guess its a matter of whether all the ops with symmetry were packaged in the crs matrix class itself (probably ideal). What I was unsure of is whether MueLu was somehow allowing symmetric storage, but probably not since it would likely rely on all the member functions of the crs matrix class.

**Comment by cgcgcg** [comment]
Lots of spots in MueLu's hierarchy setup rely on being able to get all entries in a given row. Symmetric CSR can't do that efficiently. The best I can think of right now is to drop lower triangular entries once a matrix is only needed for matvecs, cause those are effectively quite simply to implement.

**Comment by Adrian-Diaz** [comment]
Yea, ultimately I don't see much for performance gains; especially in the context of a row based matrix decomposition since even matvecs will incur comms which might make things slower. The only advantage of the option is the memory savings if trying to push the size of the matrix.

**Comment by cgcgcg** [comment]
In case you want to push the local matrix size: if you are using the Stratimikos interface we have a VERY experimental option to construct the entire preconditioner in lower precision ("half precision" == true in the parameter list). For this to work, you also need to set `Trilinos_ENABLE_FLOAT=ON` in CMake. This can obviously change the quality of the preconditioner quite significantly.

**Comment by Adrian-Diaz** [comment]
Thanks for the info. Guess that all answers the question.
