### ISSUE TITLE
Troubles with TPL HDF5 parallel

### ISSUE THREAD

**Issue by jjellio** [trilinos/Trilinos#1045]
Hello,

I am having a problem when building with HDF5.  On this system, hdf5 is provided in both parallel and serial versions.
/opt/cray/pe/hdf5-parallel/1.8.16
/opt/cray/pe/hdf5/1.8.16

In the parallel's lib directory, hdf5_fortran is a symbolic link to hdf5_fortran_parallel (the same for other hdf5 libs)

When I configure trilinos, it is not obvious which library names I should provide to TPL_HDF5_LIBRARIES.

If I use
`  -D TPL_HDF5_LIBRARIES:PATH="${HDF5_ROOT}/lib/libhdf5hl_fortran.a;${HDF5_ROOT}/lib/libhdf5_fortran.a;${HDF5_ROOT}/lib/libhdf5_hl.a;${HDF5_ROOT}/lib/libhdf5.a;/usr/lib64/libz.a" \`

e.g.,   `hdf5hl_fortran.a; hdf5_fortran.a; hdf5_hl.a; hdf5.a; libz.a`

Then I have found some unit tests that want to link `-lhdf5hl_fortran_parallel -lhdf5_fortran_parallel`

For example,  EpetraExt_View unit test

`/opt/cray/pe/craype/2.5.6/bin/CC   -xCORE-AVX2 -mkl=parallel -g1 -std=c++11 -qopenmp -O3 -DNDEBUG  -xCORE-AVX2 -mkl=parallel CMakeFiles/EpetraExt_View.dir/cxx_main.cpp.o  -o EpetraExt_View.exe ../../src/libepetraext.a ../../../triutils/src/libtriutils.a ../../../epetra/src/libepetra.a ../../../teuchos/kokkoscomm/src/libteuchoskokkoscomm.a ../../../teuchos/kokkoscompat/src/libteuchoskokkoscompat.a ../../../teuchos/remainder/src/libteuchosremainder.a ../../../teuchos/numerics/src/libteuchosnumerics.a /usr/projects/hpcsoft/cle6.0/common/intel-clusterstudio/2017.1.024/compilers_and_libraries_2017/linux/mkl/lib/intel64/libmkl_intel_lp64.a /usr/projects/hpcsoft/cle6.0/common/intel-clusterstudio/2017.1.024/compilers_and_libraries_2017/linux/mkl/lib/intel64/libmkl_intel_thread.a /usr/projects/hpcsoft/cle6.0/common/intel-clusterstudio/2017.1.024/compilers_and_libraries_2017/linux/mkl/lib/intel64/libmkl_core.a /usr/projects/hpcsoft/cle6.0/common/intel-clusterstudio/2017.1.024/compilers_and_libraries_2017/linux/lib/intel64/libiomp5.a /usr/lib64/libpthread.a /usr/lib64/libm.a /usr/projects/hpcsoft/cle6.0/common/intel-clusterstudio/2017.1.024/compilers_and_libraries_2017/linux/mkl/lib/intel64/libmkl_intel_lp64.a /usr/projects/hpcsoft/cle6.0/common/intel-clusterstudio/2017.1.024/compilers_and_libraries_2017/linux/mkl/lib/intel64/libmkl_intel_thread.a /usr/projects/hpcsoft/cle6.0/common/intel-clusterstudio/2017.1.024/compilers_and_libraries_2017/linux/mkl/lib/intel64/libmkl_core.a /usr/projects/hpcsoft/cle6.0/common/intel-clusterstudio/2017.1.024/compilers_and_libraries_2017/linux/lib/intel64/libiomp5.a /usr/lib64/libpthread.a /usr/lib64/libm.a ../../../teuchos/comm/src/libteuchoscomm.a ../../../teuchos/parameterlist/src/libteuchosparameterlist.a ../../../teuchos/core/src/libteuchoscore.a ../../../kokkos/core/src/libkokkoscore.a /usr/lib64/libdl.a /opt/cray/pe/hdf5-parallel/1.8.16/INTEL/15.0/lib/libhdf5hl_fortran.a /opt/cray/pe/hdf5-parallel/1.8.16/INTEL/15.0/lib/libhdf5_fortran.a /opt/cray/pe/hdf5-parallel/1.8.16/INTEL/15.0/lib/libhdf5_hl.a /opt/cray/pe/hdf5-parallel/1.8.16/INTEL/15.0/lib/libhdf5.a /usr/lib64/libz.a -lhdf5hl_fortran_parallel -lhdf5_fortran_parallel`

Is there a recommended way for writing my configuration script to avoid this? One thought, is to specify BOTH the serial and parallel libnames back to back.. but that would require modifications to the script when linking serial vs parallel HDF5

```
-D TPL_ENABLE_Netcdf=ON \
  -D Netcdf_INCLUDE_DIRS:PATH="${NETCDF_ROOT}/include" \
  -D Netcdf_LIBRARY_DIRS:PATH="${NETCDF_ROOT}/lib" \
  -D TPL_Netcdf_LIBRARIES:PATH="${NETCDF_ROOT}/lib/libnetcdf.a;${HDF5_ROOT}/lib/libhdf5hl_fortran.a;${HDF5_ROOT}/lib/libhdf5_fortran.a;${HDF5_ROOT}/lib/libhdf5_hl.a;${HDF5_ROOT}/lib/libhdf5.a;${PNETCDF_ROOT}/lib/libpnetcdf.a;/usr/lib64/libz.a" \
  -D TPL_Netcdf_PARALLEL:BOOL=ON \
-D TPL_ENABLE_HDF5=ON \
  -D HDF5_INCLUDE_DIRS:PATH="${HDF5_ROOT}/include" \
  -D TPL_HDF5_LIBRARIES:PATH="${HDF5_ROOT}/lib/libhdf5hl_fortran.a;${HDF5_ROOT}/lib/libhdf5_fortran.a;${HDF5_ROOT}/lib/libhdf5_hl.a;${HDF5_ROOT}/lib/libhdf5.a;/usr/lib64/libz.a" \
```

@bartlettroscoe @trilinos/framework

**Comment by jwillenbring** [comment]
@bmpersc Do you know the answer to this?

**Comment by jjellio** [comment]
My current solution is a bit flaky. I compile with the parallel hdf5 names, but still I git  link lines that have
-lhdf5hl_fortran_parallel -lhdf5_fortran_parallel.

So, after configuration, I run sed and delete them! I looked at the findHdf5 cmake module and grepped through Trilinos's source. I don't understand why those  libraries are being add.

**Comment by krcb** [comment]
For what it's worth, my approach to configuring Trillinos with NetCDF & HDF5 parallel (when the serial and parallel locations are in different locations on the system) is to specify:

 -DHDF5_INCLUDE_DIRS:PATH='<PATH_TO_HDF5_PARALLEL_INSTALL>/include' \
  -DHDF5_LIBRARY_DIRS:PATH='<PATH_TO_HDF5_PARALLEL_INSTALL>/lib' \
  -DTPL_ENABLE_HDF5:BOOL=ON \
  -DHDF5_LIBRARY_NAMES:STRING='hdf5;hdf5_hl;hdf5_tools' \
  -DNetcdf_INCLUDE_DIRS:PATH='<PATH_TO_NETCDF_PARALLEL_INSTALL>/include' \
  -DNetcdf_LIBRARY_DIRS:PATH='<PATH_TO_NETCDF_PARALLEL_INSTALL>/lib' \
  -DTPL_ENABLE_Netcdf:BOOL=ON \
  -DNetcdf_LIBRARY_NAMES:STRING='netcdf' \
  -DTPL_Netcdf_PARALLEL:BOOL=ON \

where <PATH_TO_NETCDF_PARALLEL_INSTALL> is replaced by hand by the appropriate locations on the file system. Note that I specify the names of the HDF5 & Netcdf libraries through the appropriate LIBRARY_NAMES variable. The HDF5 build that I'm linking against does have Fortran enabled and built; however I don't explicitly add these into the list of hdf5 library names as I'm not using Fortran in the Trillinos build. If you do needs these, you should be able to add them to the LIBRARY_NAMES variable.

**Comment by jjellio** [comment]
The  problem is that, even when I specify LIBRARIES="...", I am getting these -lhdf5_fortran_parallel libs tacked on to certain link lines. This is with CMake 3.5 or 3.7. I looked through the FineHDF5 module, and it looks like it should detect and choose fortran/HL bindings.. my sed find/replace works well enough.

I am not sure what in HDF5 is actually used.  The build requirements are for an app. And I know they use HDF5 in some way... possibly Fortran.

**Comment by jjellio** [comment]
@krcb changing to library names fixed this. In this case, the library directory contains libs with the name hdf5_parallel.a which is also soft linked to hdf5.a On this machine, it is easiest to just specify the expected library names.

`HDF5_LIBRARY_NAMES="hdf5hl_fortran;hdf5_fortran;hdf5_hl;hdf5"`

```
-D TPL_ENABLE_HDF5=ON \
  -D HDF5_INCLUDE_DIRS:PATH="${HDF5_ROOT}/include" \
  -D HDF5_LIBRARY_DIRS:PATH="${HDF5_ROOT}/lib" \
  -D HDF5_LIBRARY_NAMES:STRING="${HDF5_LIBRARY_NAMES};z" \
```
