### ISSUE TITLE
NOX: Which solver setup should I use to get a most efficient solution of index three DAE's

### ISSUE THREAD

**Issue by octave-user** [trilinos/Trilinos#10450]
## Question
@trilinos/NOX

I have integrated the NOX solver into the free open source multibody dynamics solver MBDyn ([https://public.gitlab.polimi.it/DAER/mbdyn](url))
You can find the the implementation mainly here: [https://public.gitlab.polimi.it/DAER/mbdyn/-/blob/trilinos-solver/mbdyn/base/noxsolver.cc](url).

MBDyn itself is based on a index three DAE formulation and used a Newton Raphson solver for the corrector step of a 2nd order implicit BDF like step integrator. It can be parallelized using multiple threads of execution. An MPI based solution is currently not supported.
It seems that the limited memory Broyden solver and the matrix free Newton Krylov solver from the NOX library are the most promising options in terms of efficiency, at least for some specific problems. 
So, I would like to ask you if you could recommend an optimal configuration of the NOX solver for that application.

**Comment by jhux2** [comment]
@trilinos/nox
