### ISSUE TITLE
EpetraExt::RowMatrixToMatrixMarketFile problem

### ISSUE THREAD

**Issue by ztdepztdep** [trilinos/Trilinos#10466]
I export the matrix with "EpetraExt::RowMatrixToMatrixMarketFile ", but I found that the file doesn't start from the first row of the matrix as shown in the following.  I need to reorder it to let my program run correctly.  Could you please give me some advice? 

> %%MatrixMarket matrix coordinate real general
% 
% A
% A
% 
14641 14641 604881
7056 7056 -8.0518165832361279e+04
7056 7478 6.6856388903229061e+04
7056 7479 -8.0385823121630483e+03
7056 7480 2.2083454082243816e+03
7056 7481 -8.7096355569416141e+02
7056 7482 4.2214464207997088e+02
7056 7483 -2.3400119851934332e+02
7056 7484 1.4261382608674396e+02
7056 7485 -9.3293103150853568e+01
7056 7486 6.4474745319511925e+01
7056 7487 -4.6551779937392396e+01
7056 7488 3.4824056357152955e+01
7056 7489 -2.6813765389538791e+01
7056 7490 2.1131303553456789e+01
7056 7491 -1.6954077237151111e+01
7056 7492 1.3769123924455954e+01
7056 7493 -1.1236693133489936e+01
7056 7494 9.1102329167903235e+00
7056 7495 -7.1763315839293256e+00
7056 7496 5.1661280773902831e+00
7056 7497 -2.0505715976030956e+00
7056 9303 4.9229441198793061e-01
7056 9324 -5.9191787314611513e-02

**Comment by cgcgcg** [comment]
Which entries of the matrix are missing? How many entries should the matrix have, and how many end up in the file?

**Comment by ztdepztdep** [comment]
the matrix has 15876 rows, but in the head it shows 14641 rows, this is the problem.
I modify the head, it can be read into my program. But why this error happened?

**Comment by cgcgcg** [comment]
My best guess is that the Epetra matrix isn't correct. How is it generated? By some Trilinos routine? Or are you setting it up? Have you tried a debug build?

**Comment by ztdepztdep** [comment]
I got it. I use a non-continuous global index for each row in the map.

**Comment by cgcgcg** [comment]
Glad you found it.
