### ISSUE TITLE
Add topics

### ISSUE THREAD

**Issue by aprokop** [trilinos/Trilinos#1047]
Github has a new feature: [topics](https://github.com/blog/2309-introducing-topics) that allows for a better discoverability of projects on Github. Please consider adding it to the repository.

@trilinos/framework

**Comment by aprokop** [comment]
@trilinos/framework Can we add topics? If not, I'm going to close this up.

**Comment by bmpersc** [comment]
@aprokop I think that this could be useful, but is not the most important thing for the Framework to look into right now. It is also likely very low hanging fruit to enable.

This should honestly should be brought up to the larger community, especially on what topics Trilinos should have. With TUG coming up this might be a good topic for developer day.
