### ISSUE TITLE
STK: separate mesh BC definitions for Nalu simulations

### ISSUE THREAD

**Issue by mulligatawny** [trilinos/Trilinos#10487]
## Question
@trilinos/stk

I am using gmesh to generate a mesh and [meshio](https://github.com/nschloe/meshio) to convert a mesh of format .msh to Exodus. However, the side set definition is stripped. I know that I can write a unit test to read in a mesh, skin it, and output. However I need each surface to be uniquely defined for a Nalu simulation, not a single surface that represents all of the exposed surfaces in one surface definition. Is there a call that provides separate mesh definitions?

**Comment by tokusanya** [comment]
@mulligatawny I wish I could help but both of those codes (gmesh and meshio) have nothing to do with STK so I'm unfamiliar with them. Who is the developer of meshio ?

**Comment by mulligatawny** [comment]
It appears that the meshio route is not workable, so I will look for other options for converters. Thanks anyway
