### ISSUE TITLE
GPU capable linear solvers

### ISSUE THREAD

**Issue by kongm** [trilinos/Trilinos#1050]
Hi, are there any solvers in Belos or MueLU (or any other package) with GPU implementations? Thanks.

**Comment by tawiesn** [comment]
As long as you use Tpetra you are also using the corresponding linear algebra kernels (which make use of CUDA, OpenMP,... if enabled). Some of the MueLu kernels have been ported to use Kokkos directly. But these are not enabled by default and should be supposed to be experimental. We are working on that.

**Comment by mhoemmen** [comment]
@kongm Belos does not actually implement linear algebra operations.  Belos just defers to the linear algebra library.  For example, if you use Tpetra with the Kokkos::Cuda execution space (the default if building Trilinos with CUDA enabled), Belos will use Tpetra::CrsMatrix and Tpetra::MultiVector operations, all of which use the GPU.  Also, some Ifpack2 preconditioners / smoothers have kernels which run on the GPU.

**Comment by mhoemmen** [comment]
@kongm Do you know my e-mail address?  I'll be happy to send you a presentation which lists the current set of GPU-enabled computational kernels.

**Comment by aprokop** [comment]
@mhoemmen Please send it to me too!

**Comment by kliegeois** [comment]
@mhoemmen May you send this presentation to me too?

**Comment by ibaned** [comment]
@mhoemmen Count me in as well

**Comment by tjfulle** [comment]
@mhoemmen , me five

**Comment by jjellio** [comment]
You all may want to read through:
https://trilinos.org/pipermail/trilinos-users/2017-January/005801.html

I posted a small example showing how to setup Tpetra execution spaces, as well as some snippets that are useful for debugging.

**Comment by mhoemmen** [comment]
Hold on, wait folks!  I don't have good work e-mail access for the next couple days.  Could you all send me an e-mail to my work e-mail address asking for this?  If you don't know my work e-mail address, please post below and I'll do my best to get this to you.  Thanks!
