### ISSUE TITLE
STK: undefined reference error when building Albany-LCM

### ISSUE THREAD

**Issue by ikalash** [trilinos/Trilinos#10503]
The Albany-LCM nightlies began failing today with the following undefined reference error:

```
../disc/stk/libalbanySTK.so: undefined reference to `stk::mesh::DataTraits const& stk::mesh::data_traits<stk::mesh::FieldBase>()'
```
https://sems-cdash-son.sandia.gov/cdash/viewBuildError.php?buildid=33166

The problem happens when building an Albany-LCM library, but it does not seem that DataTraits are actually referenced anywhere in Albany-LCM, which is making us wonder if this is a pure STK problem that is only getting caught while building Albany-LCM?  Any tips towards fixing this would be useful.  

Tagging @alanw0 and @lxmota .

**Comment by alanw0** [comment]
Hmm, that is puzzling. I can't find anything like that in stk either. We have it for primitive types, like `data_traits<double>` etc, but I can't find any instance of it being templated on a FieldBase. We will figure this out asap.
@djglaze Dave do you have any insights about this?

**Comment by ikalash** [comment]
Thanks @alanw0 .  I had a thought that this might be due to an interaction with DTK (DataTransferKit), which we use in LCM and which uses STK; however, I confirmed that if I build LCM w/o DTK, I still see the same error.

**Comment by djglaze** [comment]
This may have something to do with a bad call to stk::mesh::MetaData::get_field().  There were previously only two overloads of this function: a templated version and an un-templated version.  The un-templated version just gets a FieldBase pointer like this:

    stk::mesh::FieldBase * myField = meta.get_field(stk::topology::NODE_RANK, "myFieldName");

and the templated version gets a field of the correct templated derived type:

    stk::mesh::Field<double> * myField = meta.get_field<stk::mesh::Field<double>>(stk::topology::NODE_RANK, "myFieldName");

My guess is that, somewhere in your code, you have a call of the form:

    stk::mesh::FieldBase * myField = meta.get_field<stk::mesh::FieldBase>(stk::topology::NODE_RANK, "myFieldName");

Note the FieldBase template parameter.  This is completely equivalent to the un-templated version and is not harmful, but it is a bit unnecessary.  We are working toward a simplification of how Fields are registered and managed, and have recently exposed another overload that is just templated on the datatype, such as:

    stk::mesh::Field<double> * myField = meta.get_field<double>(stk::topology::NODE_RANK, "myFieldName");

The type_traits gymnastics required to enable this overload ends up blocking the version templated on FieldBase.  So, the short version is that you likely have a get_field() call somewhere in your code that is templated on FieldBase.  Just remove the template parameter to get it working again.

Please let us know if this doesn't fix the problem, as we might have to dig deeper.

Dave

**Comment by ikalash** [comment]
@djglaze: your proposed fix works!  Thanks so much - we would not have been able to figure this out on our own.  I'll close this tomorrow once the nightlies have a chance to run and report clean.
