### ISSUE TITLE
Kokkos:  Enable multiple cuda arch's

### ISSUE THREAD

**Issue by jrobcary** [trilinos/Trilinos#10506]
## Question
@trilinos/Kokkos

At present, specifying multiple CUDA architectures is disabled by kokkos_arch.cmake.  This prevents us from creating binary distributions for multiple machines with different CUDA cards.  (The rest of our stack does build for multiple cuda architectures, and CMake supports this through CMAKE_CUDA_ARCHITECTURES.)

Is there something intrinsic to Trilinos that has led to this?

How difficult would it be to enable multiple CUDA architectures in Trilinos?

**Comment by csiefer2** [comment]
I asked some of the Kokkos folks, but this is not something officially supported.  You might want to post a question to the Kokkos slack.

**Comment by jrobcary** [comment]
Thx.  Have moved to Kokkos slack.
