### ISSUE TITLE
Phalanx: template classes on Kokkos execution space, and use PHX::Device only as default.

### ISSUE THREAD

**Issue by bartgol** [trilinos/Trilinos#1051]
As it is now, Phalanx decides what is the Kokkos node based on the first available in the list "Cuda, OpenMP, Threads, Serial", and uses it to set the type PHX::Device. This is then used in other places to resolve some types.

However, since I can have a single installation of trilinos with different Kokkos execution spaces enabled, I would like to have the same thing for Phalanx, rather than having to have different trilinos installations just to have different PHX::Device's.

My question is: could we let the Device be a template argument in the places where it's needed (e.g., Phalanx::MDField)? To avoid (or at least minimize) breaking existing code, Phalanx could have a DefaultDevice (selected in the same way that Device is defined now), to which all the template arguments DeviceType will default. Perhaps, for a hypotetic class Phalanx::ClassA, one could change the implementation into

```

template<typename DeviceType=PHX::DefaultDevice>
class ClassA
{
/* code here*/
};

using ClassA = ClassA<>;
```

The using directive is to allow existing code that has 'ClassA a =...;' to keep working (even without the '<>' after ClassA). If ClassA already has template arguments, then the using directive is not needed (and actually wrong). This would allow old code using ClassA to work in the same way (I think). 

On the plus side, my downstream application that links to trilinos, could have the (optional) choice to define a device type that is different from the default Phalanx one. Clearly, at some point one has to define the device type to use in the Kokkos-based structures; but I'd rather that choice to be pushed down to the application that uses Phalanx, rather than be taken inside Phalanx. Otherwise I need several installations of trilinos, one for each Kokkos execution space.

I believe this should be a fairly reasonable addition, especially considereing that it is pretty much what is already done by the Tpetra classes, which have the node as a template argument, with a default to a predefined node (which, as it is done now in Phalanx, is based on the first  available execution space in the list "Cuda, OpenMP, Threads, Serial").

**Comment by rppawlo** [comment]
The main complication will be that we actually have two implementations for MDFields, one for static rank and one for dynamic rank. Right now they are differentiated via template arguments. I'm pretty sure that adding default template argument for the device will result in the compiler not being able to pick between the two classes. I think we can get around this with SFINAE to remove one of the templates.
