### ISSUE TITLE
Teuchos:  Wrong section names causes Doxygen tag file of Teuchos to be unusable in a WARN_AS_ERROR context

### ISSUE THREAD

**Issue by romintomasetti** [trilinos/Trilinos#10511]
## Documentation
@trilinos/\<Teuchos\>

Currently, it is not possible to use the Doxygen generated tag file of Teuchos in a Doxygen project that has `WARN_AS_ERROR=YES`, because a couple of `\section` commands are wrong.

### Suggested fixes

I think the issue can be easily fixed applying the following suggestions

1. https://github.com/trilinos/Trilinos/blob/e85ccf73ae46b00da15b98250f28997aa949c0be/packages/teuchos/core/src/Teuchos_ArrayViewDecl.hpp#L87
should be
```c++
  * \section Teuchos_ArrayView_Req Requirements on the type T 
```

2. https://github.com/trilinos/Trilinos/blob/e85ccf73ae46b00da15b98250f28997aa949c0be/packages/teuchos/core/src/Teuchos_ArrayRCPDecl.hpp#L103
should be
```c++
  * \section Teuchos_ArrayRCP_DesignDiscussion_sec Design discussion 
```

**Comment by jhux2** [comment]
@trilinos/teuchos

**Comment by jhux2** [comment]
@romintomasetti Thanks for the suggestion.

**Comment by jhux2** [comment]
@romintomasetti Could you verify that this fixes the issue you've observed, and then close?  Thanks again for the contribution.

**Comment by romintomasetti** [comment]
@jhux2 I just tried, but it looks like the tag files have not been re-generated yet.

In https://docs.trilinos.org/dev/packages/common/tag_files/, `Teuchos.tag` is still from `2022-05-10 09:09`.

I'll wait that it is updated to test it again.

**Comment by romintomasetti** [comment]
@jhux2 I just tested it, it didn't worked. Doxygen still complains:
```bash
build/docs/teuchos.tag:28766: error: Duplicate anchor Teuchos_ArrayRCP_Req found (warning treated as error, aborting now)
```
I wonder which branch is used to create the documentation ? I'm taking the tag files from https://docs.trilinos.org/dev/packages/common/tag_files/.

**Comment by cgcgcg** [comment]
@jhux2 Looks like the docs are generated using a Github Action. The last run bugged out with

```
Liquid Exception: Liquid syntax error (line 1428): Variable '{{"a", 1}' was not properly terminated with regexp: /\}\}/ in packages/sacado/test/GTestSuite/googletest/googlemock/docs/cook_book.md
/usr/local/bundle/gems/liquid-4.0.3/lib/liquid/block_body.rb:136:in `raise_missing_variable_terminator': Liquid syntax error (line 1428): Variable '{{"a", 1}' was not properly terminated with regexp: /\\}\\}/ (Liquid::SyntaxError)
```

**Comment by jhux2** [comment]
> Looks like the docs are generated using a Github Action.

Can you post a link to that action?

**Comment by cgcgcg** [comment]
https://github.com/trilinos/Trilinos/actions/workflows/pages/pages-build-deployment

**Comment by jhux2** [comment]
Thanks. That action is timestamped two weeks ago, if I'm reading it correctly.

**Comment by cgcgcg** [comment]
Yep. And it has been failing for a while..

**Comment by jhux2** [comment]
@trilinos/framework @jwillenbring I have my doubts as to whether #10520 is the proper fix.

**Comment by jwillenbring** [comment]
> https://github.com/trilinos/Trilinos/actions/workflows/pages/pages-build-deployment

This is actually a standard GitHub action that builds the GitHub pages when someone makes a change. This is not related to Doxygen. That documentation is generated using a crontab on the server.

**Comment by romintomasetti** [comment]
So, what needs to be done here to solve the issue?
The tag files are still not updated according to the changes made in https://github.com/trilinos/Trilinos/pull/10512.
Does this also mean that even the Doxygen documentation at https://trilinos.github.io/teuchos_doxygen.html is not updated ?

**Comment by romintomasetti** [comment]
Also, would you mind adding the Doxygen parameter `HTML_TIMESTAMP  = YES` to help us determine when exactly the "version of the day" really dates back ?

**Comment by jhux2** [comment]
@jwillenbring Any idea what could be going wrong?

**Comment by jwillenbring** [comment]
@jhux2 Looking at this I think the issues is that Doxygen is generated off of the master branch, which has not been updated since late April.

**Comment by romintomasetti** [comment]
I made https://github.com/trilinos/Trilinos/pull/10617 to introduce `HTML_TIMESTAMP = YES`...
