### ISSUE TITLE
Amesos2:  Extend interface to cuSOLVER to solvers other than the one based on Chol factorization

### ISSUE THREAD

**Issue by maartenarnst** [trilinos/Trilinos#10514]
## Question
@trilinos/Amesos2

The cuSOLVER package provides several direct solvers (chol, LU, ...).  However, Amesos2's interface to cuSOLVER currently hardcodes the choice of the Cholesky-factorization-based solver, and it looks like Amesos2's interface currently doesn't allow other types of direct solver to be chosen, e.g. through parameter list options.  E.g., in https://github.com/trilinos/Trilinos/blob/develop/packages/amesos2/src/Amesos2_cuSOLVER_FunctionMap.hpp, all calls to functions from cuSOLVER are hardcoded to be calls to functions whose name involves`chol` and are thus relative to the Cholesky-factorization-based solver. 

My question is thus why the choice was made to seemingly limit Amesos2's cuSOLVER interface to only the Cholesky-factorization-based solver?  I am also wondering if the Trilinos team is planning work on extending Amesos2's cuSOLVER interface.

I would be happy to work on extending Amesos2's cuSOLVER interface to other types of direct solver provided by cuSOLVER.  If such work should be of interest to somebody in the Trilinos team, I would be happy to exchange ideas and coordinate on this work.

Thanks in advance.

**Comment by jhux2** [comment]
@trilinos/amesos2

**Comment by jhux2** [comment]
@ndellingwood @lucbv @iyamazaki

**Comment by iyamazaki** [comment]
Hi @maartenarnst. We can wait for the feedback from others (e.g., if someone already has the extension), but I think it will be great if you can work on it and do a PR. :)

**Comment by jhux2** [comment]
@srajama1 fyi

**Comment by srajama1** [comment]
@maartenarnst It would be great if you can work on it and submit a PR. We will be happy to help you if you have any questions and getting the PR pushed into Trilinos.
