### ISSUE TITLE
stk_transfer: ReducedDependencyGeometricTransfer.hpp does not clear vector before reuse.

### ISSUE THREAD

**Issue by overfelt** [trilinos/Trilinos#10526]
In this line of code:
https://github.com/trilinos/Trilinos/blob/0bd35b1d0298b79ab6e18619e61fa364c84a6267/packages/stk/stk_transfer/stk_transfer/ReducedDependencyGeometricTransfer.hpp#L147
A vector is filled with values to get a list of unique values.  But since this vector has been used previously, there can be some extraneous values in it.  Should have a call to `uniqueProcVec.clear()` before appending to vector.

The side effect of this is to have extra values in `uniqueProcVec` that are not in `vec`.  A recent change to SPARC to use `kokkos::vector` instead of `std::vector` turns on bounds checking when compiled for debugging purposes.  For `std::vector` or `kokkos::vector` in optimized code this does not cause a problems because the value is never used. 

This can be checked by adding a check the vector is empty and running `stk_transfer_unit_tests.exe --gtest_filter=ReducedDependencyGeometricTransferTest.SingleElemToPoint`

**Comment by jhux2** [comment]
@trilinos/stk

**Comment by alanw0** [comment]
@overfelt James we put a fix for this into the sierra repo yesterday. Once our snapshot makes it into Trilinos we'll let you know.
