### ISSUE TITLE
Intrepid2: Cuda non-UVM test failure in Projection_test_DeRham_commutativity_HEX_CUDA_DOUBLE_MPI_1

### ISSUE THREAD

**Issue by ndellingwood** [trilinos/Trilinos#10536]
## Bug Report
@trilinos/intrepid2 

### Description
In Non-UVM Cuda builds with cuda/10.1.105 with Volta70 arch the `Intrepid2_unit-test_Projection_test_DeRham_commutativity_HEX_CUDA_DOUBLE_MPI_1` test consistent fails. 

Here is output snip from the first failure:

```
338: ===============================================================================
338: |                                                                             |
338: |              Test 1 (DeRham Commutativity - HGRAD-HCURL)                    |
338: |                                                                             |
338: ===============================================================================
338: Considering Hex 0: [ 0 1 2 3 4 5 6 7 ] and Hex 1: [ 4 5 6 7 8 9 10 11 ]
338:                                                      ^^^^----FAILURE! 5.25019
338: Gradient of projection is different than projection of gradient at reference points 0
...
```

### Steps to Reproduce
1. SHA1:  020bc729971bdab83f28ead3c034f479c680cdf7
2. Configure script:  Weaver testbed

```bash

# Load modules
module purge
export ATDM_CONFIG_REGISTER_CUSTOM_CONFIG_DIR=${TRILINOS_DIR}/cmake/std/atdm/contributed/weaver
source ${TRILINOS_DIR}/cmake/std/atdm/load-env.sh weaver-cuda-10.1-opt
export ATDM_CONFIG_USE_NINJA=OFF
unset CUDA_LAUNCH_BLOCKING

# Configure
cmake \
 -G"Unix Makefiles" \
 -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
 -DCMAKE_INSTALL_PREFIX="${PWD}/install" \
 -DCMAKE_CXX_STANDARD="14" \
 -DCMAKE_CXX_FLAGS="-pedantic -Wall" \
 -DTrilinos_ENABLE_TESTS=OFF \
 -DTrilinos_ENABLE_ALL_PACKAGES=OFF \
 -DKokkos_ENABLE_CUDA_UVM=OFF \
 -DTrilinos_ENABLE_Intrepid2=ON \
 -DIntrepid2_ENABLE_TESTS=ON \
 -DTrilinos_ENABLE_Sacado=ON \
$TRILINOS_DIR

```

**Comment by mperego** [comment]
This test should not be enabled in CUDA builds. I think we need to comment out these lines 
`https://github.com/trilinos/Trilinos/blob/master/packages/intrepid2/unit-test/Projection/CMakeLists.txt#L145-L148`

**Comment by mperego** [comment]
@ndellingwood I'm working on a PR on projections that I hope to merge next week and I can fix these tests. Alternatively, if you need this fixed sooner, we can disable them when running using CUDA (I thought they were already disabled).

**Comment by kyungjoo-kim** [comment]
@ndellingwood why is this test enabled without uvm ? it is explicitly instantiated with CudaUVMSpace as @mperego indicates. if the uvm space is disabled compile time, this should be compile time error.

**Comment by kyungjoo-kim** [comment]
@ndellingwood what does non-uvm build do ? I thought that the uvm space as a template argument is still available but the default execution space is paired with non-uvm space. we changed the intrepid2 uses device type and explicitly templated with device type. @mperego you may want to check if there is a function that uses execution space as its template parameter. there could be possible mismatch and corruption of data. the test should be fine with UVM and it is instantiated with UVM space. My only concern is that some temporal views are constructed not following the given device type in the code.

**Comment by ndellingwood** [comment]
@mperego @kyungjoo-kim thanks for the fast responses!

It's not urgent on my side, I can disable the test from running on our side for now (i.e. `-DIntrepid2_unit-test_Projection_test_DeRham_commutativity_HEX_CUDA_DOUBLE_MPI_1_DISABLE=ON`)

The most relevant cmake settings to this build are:
```
 -DKokkos_ENABLE_CUDA_UVM=OFF \
 -DTrilinos_ENABLE_Intrepid2=ON \
 -DIntrepid2_ENABLE_TESTS=ON \
```

In this configuration, `-DKokkos_ENABLE_CUDA_UVM=OFF` explicitly disables UVM as the default memory space for the device (CudaSpace is the default if a memory space is not supplied as a type e.g. to a View). CudaUVMSpace is still available for use as a memory space in this configuration when explicitly provided, it is just not the implicit default space

**Comment by kyungjoo-kim** [comment]
@ndellingwood Can Kokkos team provide a functionality showing a warning message that non-default memory space is used or default memory space is used so that we can detect where the view is created ? or providing a runtime function that controls the warning message. for example,
```
Kokkos::setViewAllocationWarning(Kokkos::CudSpace()); /// or setViewAllocationException(Kokkos::CudaSpace()); 
Kokkos::unsetViewAllocationWarning(); /// unset the warning or exception anymore
```
for this particular case, we would like to check the case that the default memory space is used. if it is used in this region, show warning message or throw an exception, so we can pin point the unintended memory allocations.
