### ISSUE TITLE
Framework:  New intel-19.0.5 PR build crashes in git operations expecting a 'develop' branch in fork

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#10538]
## Bug Report

@trilinos/framework 

### Description

The intel-19.0.5 PR build seems to be crashing during the git merge operations and never even gets to running the cmake configure or submitting anything to CDash.  For example, you can see this in the PR testing iterations:

* https://github.com/trilinos/Trilinos/pull/10533#issuecomment-1129473566
* https://github.com/trilinos/Trilinos/pull/10533#issuecomment-1130028485

which both show the error:

```
PRLinuxDriverMerge> git fetch source_remote tribits-299-modern-cmake-targets-2-prep
fatal: Couldn't find remote ref develop
```

Apparently, whatever code is running this is assuming that the GitHub repo fork has a branch called `develop`.  Well, my fork does not have `develop` or `master`.   To explain why, see https://github.com/bartlettroscoe/Trilinos#readme.

The only branch that should be accessed from the GitHub fork is the actual branch associated with the PR.

### Steps to Reproduce

Run a PR build for a branch in a fork that does not have `develop`.

**Comment by ZUUL42** [comment]
I think I know the issue and will take care of it.

**Comment by bartlettroscoe** [comment]
@ZUUL42, looks like this 'develop' problem is now solved as shown in https://github.com/trilinos/Trilinos/pull/10533#issuecomment-1132742915 but now we have a new problem with the intel-19.0.5 build that I just reported in #10549.
