### ISSUE TITLE
Trilinos Multilevel Preconditioner solver for FEM

### ISSUE THREAD

**Issue by Resacd** [trilinos/Trilinos#10539]
I am trying to solve the stokes equations using finite element method. I distributed the mesh across MPI processors using METIS. I assembled all the finite element matrices locally and stored them in CSR format in each processor. I also have some variables referring to local and global indexing. I've already got Trilinos working and I am able to run all  the examples here https://docs.trilinos.org/dev/packages/ml/doc/html/index.html#ml_examples. For a few days I am working around to choose a package which is a block box solver and suitable for my problem. Unfortunately, I couldn't find any example employing finite element and compatible with my domain decomposition. As far as I understood, Trilinos mostly uses examples in Galery package in the link above and all those examples use finite difference method. I thinks for solving a system of linear equation using Trilinos the steps should be summarized in the following step,
1- Loading distributed coefficient matrices from each processor
2- Loading distributed right hand side vector from each processor
3- Calling Ax=b solver
Now my problem is I don't know how to go through these steps since there is no example for this purpose available. 
I would appreciate any hint in advance.

**Comment by cgcgcg** [comment]
We have MueLu for algebraic multigrid and FROSch for domain decomposition methods. Both work for FEM. (Setting up a simple example in Galeri is easier for finite difference, that's why we use that in lots of tests). Where you able to check that the system that you are setting up matches what you expect? (E.g. by writing it out to a matrix market file?) Next, what's your approach for solving Stokes?
@trilinos/muelu @trilinos/shylu

**Comment by Resacd** [comment]
@cgcgcg 
Thanks for your answer. I am using Galerkin method with a linear triangle element and tetrahedral element.
Sorry I didn't understand this part,  `Were you able to check that the system that you are setting up matches what you expect? (E.g. by writing it out to a matrix market file?) `

**Comment by cgcgcg** [comment]
What I meant is: were you able to verify that the Tpetra matrix that you are setting up is indeed correct. Distributing a FEM matrix by rows usually requires some work, unless the elements along the processor boundaries are duplicated.

**Comment by Resacd** [comment]
@cgcgcg 
I didn't do what you are referring to. I am going to solve Ax=b. I think the procedure should be something like following steps,
1- Load the matrix from each processor
2- Load the RHS from each processor
3- call a function to solve the system.
I used METIS to distribute the mesh among processors. Then build the coefficient matrix in each processor. so the coefficient matrix is already distributed. I already have this matrix stored in CSR format. So now I don't know how to load the matrix, RHS and call a block-box solver for this. I think ML_Epetra::MultilevelPreconditioner is good choice. Could you help me or give me any example of this to set up my project. I would be grateful.

**Comment by cgcgcg** [comment]
How about you follow something like https://github.com/trilinos/Trilinos/blob/master/packages/ml/examples/BasicExamples/ml_preconditioner.cpp ?

**Comment by cgcgcg** [comment]
After re-reading the description of your approach, I am concerned that your results will be wrong. You are distributing the mesh. So each element will live on one rank. Then you assemble on the local meshes. You are missing a step to get that information into the required matrix distribution by row. There is no point in talking about solvers until you check that the linear system is correct.

**Comment by Resacd** [comment]
@cgcgcg I feel something is missing here, that's why I tried to explain what I am doing exactly, but I don't understand which step. before I was using HYPRE and domain decomposing was element-wise. for example the first 5 element goes to rank 0, second 5 elements foes to rank 1 and so on. and the HYPRE was using row-wise distribution. after a while I was concern about memory efficiency and that's why I used metis and came up with this. now I feel really stuck and disappointed.

**Comment by cgcgcg** [comment]
Here is the issue: degrees of freedom can be associated with more than one element, and the sub-assembly over several elements contribute to entries in the matrix. Think of an entry (i, i) in the matrix where dof i sits on an interface between two processors. Elements on more than one rank need to contribute to that value. In a row-wise distribution of the matrix, the final value of that entry exists only on one rank.

**Comment by Resacd** [comment]
This can't be solve by a division of number of repetition number? For example if one element is repeated into two processors the corresponding nodal values can be divided by two.

**Comment by cgcgcg** [comment]
Yes, you can duplicate elements and solve the issue that way.

**Comment by Resacd** [comment]
The link you shared it's about finite difference I guess.

**Comment by cgcgcg** [comment]
We also have some old examples for FEM & Epetra:
https://github.com/trilinos/Trilinos/blob/master/packages/trilinoscouplings/examples/scaling/IntrepidPoisson_Pamgen_Epetra_main.cpp

**Comment by Resacd** [comment]
Thanks for your help. Let me go through this example and I will let you know if I have got any success.

**Comment by Resacd** [comment]
@cgcgcg
I have two Elements and two MPI processors. Each MPI processor receives one element and constructs its local stiffness matrices and stores it as follows:

  0------1
  |       /  |
  |    /     |
  | /        |
  2------3

proc 0: 
row_ptr={0,3,6,9}
col_ind={0,1,2,0,1,2,0,1,2}
local2global indexing={0,1,2}---->saying which nodes are in the current processor
global2local indexing={0,1,2,-1}---->re-indexing of nodes in each processor
MPI_repeatition: {1,2,2,1}
right hand side={1,2,0.5}

proc1:
row_ptr={0,0,3,6,9}
col_ind={1,2,3,1,2,3,1,2,3}
local2global indexing={1,2,3}
right hand side={0.2,2,1.4}
MPI_repeatition: {1,2,2,1}
global2local indexing={-1,0,1,2} 

I am going to solve Ax=rhs in which A is already distributed.
could you help me to fill out the A matrix and rhs and call the Muelu or multilevel preconditioner with Aztecoo or epetra and solve this system?

**Comment by cgcgcg** [comment]
@Resacd You need to decide which processor owns which row. Currently, both proc 0 and 1 have entries for rows 1 and 2.
What can be helpful for FEM assembly are helper classes called "FECrsMatrix". Both Epetra and Tpetra should have them. In that way, you can do the local assembly on uniquely distributed elements, and then let Trilinos redistribute the data.

**Comment by Resacd** [comment]
@cgcgcg 
Thanks for your answer.
I am totally confused. there are some nodes shared between processors because each processor is receiving a chunk of element and they will be having some nodes in common. so I should've not distributed the mesh using metis at the beginning of my code?

**Comment by cgcgcg** [comment]
You have two options:
1) Uniquely distribute elements (e.g. using METIS), assemble, then communicate to obtain a row-wise matrix distribution. (See FECrsMatrix for that.)
2) Duplicate elements near the processor boundaries, then assemble only the matrix entries that are owned by the processor.

**Comment by Resacd** [comment]
I will use metis.  So as I understand from what you said I should give chuck of element to each processor. 
Then ask FECrsMatrix to do the assembly?
and what will be the next?
I am just so sorry for taking your time and being naive.

**Comment by cgcgcg** [comment]
After using FECrsMatrix, you should end up with a correctly distributed CrsMatrix for your solve. For the RHS, there is a similar procedure, using FEMultiVector.

**Comment by Resacd** [comment]
Thanks for the help.

**Comment by Resacd** [comment]
do you know where I can get an example of FECrsMatrix to assemble the local stiffness matrix in each processor?
what will happen If I just use my own routine to assemble and then ask trilinos to obtain then communicate to obtain a row-wise matrix distribution? The problem of shared nodes can be solved just by dividing their value by the number of repetition unless something is happening inside trilinos which I have no idea on that which does not allow having shared nodes.

**Comment by cgcgcg** [comment]
For Epetra's FECrsMatrix, have a look at this test:
https://github.com/trilinos/Trilinos/tree/master/packages/epetra/test/FECrsMatrix

You cannot simply divide or multiply shared nodes, that doesn't work for non-uniform elements.

**Comment by Resacd** [comment]
Thanks, this seems to be much help for me. 
There is two kind of assigning nodes to each subdomain.

> First one is Drum1 
>   //   *----*
>   //  3|\  2|
>   //   | \  |
>   //   | 0\1|
>   //   |   \|
>   //   *----*
>   //  0    1
>   //
>   //Element 0 on processor 0, element 1 on processor 1.
>   //Processor 0 will own nodes 0,1 and processor 1 will own nodes 2,3.
>   //Each processor will pass a 3x3 element-matrix to Epetra_FECrsMatrix.
>   //After GlobalAssemble(), the matrix should be as follows:
>   //
>   //         row 0: 2  1  0  1
>   //proc 0   row 1: 1  4  1  2
>   //----------------------------------
>   //         row 2: 0  1  2  1
>   //proc 1   row 3: 1  2  1  4
>   //
and second one in Drum2

>   //   *----*
>   //  3|\  2|
>   //   | \  |
>   //   | 0\1|
>   //   |   \|
>   //   *----*
>   //  0    1
>   //
>   //Element 0 on processor 0, element 1 on processor 1.
>   //Processor 0 will own nodes 0,1,3 and processor 1 will own node 2.
>   //Each processor will pass a 3x3 element-matrix to Epetra_FECrsMatrix.
>   //After GlobalAssemble(), the matrix should be as follows:
>   //
>   //         row 0: 2  1  0  1
>   //proc 0   row 1: 1  4  1  2
>   //         row 2: 0  1  2  1
>   //----------------------------------
>   //proc 1   row 3: 1  2  1  4
>   //

I just don't get where the value of each rows come from. Also this is a simple case with two elements. we assign the element 1 tp processor 0 and there is just one node left and we assign that to the other processor. what if we have mode than 2 elements and 2 processors, Then how each mpi processor will understand which node it should work on.

**Comment by mayrmt** [comment]
@Resacd The keyword here is "overlapping domain decomposition", where the subdomain/processor boundary cuts through an element. Then, each node is uniquely assigned to one processor (and some elements need to be "duplicated" for the FEM evaluation and assembly).

**Comment by Resacd** [comment]
Thanks for your comment. could you tell me where these values come from? 
// row 0: 2 1 0 1
//proc 0 row 1: 1 4 1 2
//----------------------------------
// row 2: 0 1 2 1
//proc 1 row 3: 1 2 1 4

**Comment by Resacd** [comment]
> You have two options:
> 
> 1. Uniquely distribute elements (e.g. using METIS), assemble, then communicate to obtain a row-wise matrix distribution. (See FECrsMatrix for that.)
> 2. Duplicate elements near the processor boundaries, then assemble only the matrix entries that are owned by the processor.

Is there anyway for non row-wise distribution in Trilinos solvers?
Do you mean row-wise access or row-wise distribution by saying redistribute here
 
`you can do the local assembly on uniquely distributed elements, and then let Trilinos redistribute the data.`

**Comment by Resacd** [comment]
@cgcgcg 
Sorry again. If I don't use FECsrMatrix for assembling local matrices but instead I manage my own assembly function in a way that nodes not to be shared between processors then will trilinos work fine? And one another thing, if trilinos just work for row wise distributed matrices what is the point of having METIS in the package? I was thinking when I divide the mesh using metis then all trilinos will be able to do all matrix-vector multiplication and other stuff based on how metis work.

**Comment by cgcgcg** [comment]
You don't have to use the FE* helper classes. You just need a row-wise distribution of the matrix.
For FEM, you need to work with elements and degrees of freedom. and you need to decide on ways to distribute both of them. METIS (and other algos in Zoltan/Zoltan2) is a perfectly reasonable choice to distribute elements. This almost induces a distribution of the degrees of freedom, but you need to decide which rank owns interface unknowns.

**Comment by Resacd** [comment]
I got the idea almost. Thanks for the help. 
I just have one question regarding the case Epetra_CrsMatrix A(Copy, map, 3). what if each row has different number of entry. Should I put this inside a loop?

**Comment by cgcgcg** [comment]
I don't think I understand the use of a loop. We should have some matrix constructors that take a vector of number of entries per row, that's probably what you want.

**Comment by Resacd** [comment]
@cgcgcg 
I am able to load my vectors and matrices from all processors correctly as follows and now I want to redistribute them  and call the solver. can you help we with redistribution.
```
void Solver::LoadRhs(int nNodes_global, VecInt_t& Local2Global, VecDbl_t &rhs) {


	Epetra_MpiComm Comm(MPI_COMM_WORLD);
	int NumGlobalElements = nNodes_global;
	Epetra_IntSerialDenseVector MyGlobalElements;
	int NumMyElements = Local2Global.size();
	MyGlobalElements.Size(NumMyElements);

	for (int i = 0; i < NumMyElements; i++) {
		MyGlobalElements[i] = Local2Global[i];
	}

	Epetra_Map Map(-1, MyGlobalElements.Length(), MyGlobalElements.Values(), 0, Comm);

	Epetra_Vector x(Map);
	for (int i = 0; i < NumMyElements; ++i)  x[i] = rhs[i];
	std::cout << x;
	std::cout << std::endl;
}

void Solver::LoadMtx(int nNodes_global, SparseMatrix& SpM, VecInt_t& Local2Global) {

#ifdef HAVE_MPI
	Epetra_MpiComm Comm(MPI_COMM_WORLD);
#else
	Epetra_SerialComm Comm;
#endif
	int myRank = Comm.MyPID();
	int numProcs = Comm.NumProc();
	if (myRank == 0) {
		// Print out the Epetra software version.
		cout << Epetra_Version() << endl << endl
			<< "Total number of processes: " << numProcs << endl;
	}
#ifdef EPETRA_NO_32BIT_GLOBAL_INDICES
	typedef long long global_ordinal_type;
#else
	typedef int global_ordinal_type;
#endif
	global_ordinal_type numGlobalElements = nNodes_global;
	global_ordinal_type indexBase = 0;
	Epetra_Map Map(numGlobalElements, indexBase, Comm);
	int NumMyElements = Map.NumMyElements();
	global_ordinal_type* MyGlobalElements = NULL;
#ifdef EPETRA_NO_32BIT_GLOBAL_INDICES
	myGlobalElements = map.MyGlobalElements64();
#else
	MyGlobalElements = Map.MyGlobalElements();
#endif
	if (NumMyElements > 0 && MyGlobalElements == NULL) {
		throw std::logic_error("Failed to get the list of global indices");
	}
	if (myRank == 0) {
		cout << endl << "Creating the sparse matrix" << endl;
	}
	int* NumNz = new int[NumMyElements];
	VecInt_t* row_ptr = SpM.row_ptr_;
	VecInt_t* col_ind = SpM.col_ind_;

	for (int i = 0; i < NumMyElements; i++) {
		//NumNz[i] = num_nonzero[MyGlobalElements[i]];
		NumNz[i] = (*row_ptr)[MyGlobalElements[i] + 1] - (*row_ptr)[MyGlobalElements[i]];
	}

	Epetra_CrsMatrix A(Copy, Map, NumNz);
	int NumEntries = 0;
	for (int i = 0; i < NumMyElements; i++) {

		double* Values = new double[NumNz[i]];
		int* Indices = new int[NumNz[i]];
		NumEntries = NumNz[i];
		int col_begin = (*row_ptr)[MyGlobalElements[i]];
		int col_end = (*row_ptr)[MyGlobalElements[i] + 1];
		int k = 0;
		for (int j = col_begin; j < col_end; j++) {
			Values[k] = SpM.val_[j];
			Indices[k] = (*col_ind)[j];
			k++;
			if (k == NumNz[i])break;
		}
		A.InsertGlobalValues(MyGlobalElements[i], NumEntries, Values, Indices);
		delete[] Values;
		delete[] Indices;
	}

	A.FillComplete();
	std::cout << A;
}
```

**Comment by cgcgcg** [comment]
Can you compute the residual $Ax-b$ and check whether the specified system is solved correctly?

**Comment by cgcgcg** [comment]
You can use METIS to distribute the nodes. For this to work, you then need to duplicate elements and only assemble the entries in rows owned by the rank.

**Comment by cgcgcg** [comment]
Please reopen if this is not resolved.
