### ISSUE TITLE
Kokkos:  AMD GPU compiler flags missing, leading to `hipErrorNoBinaryForGpu`

### ISSUE THREAD

**Issue by romintomasetti** [trilinos/Trilinos#10548]
## Bug Report
@trilinos/\<Kokkos\>

### Description

We are compiling Trilinos with the HIP backend.  The **compilation works**, but, afterwards, **running the tests fails** with `hipErrorNoBinaryForGpu`.

We are compiling Trilinos on a workstation computer with a **Radeon Pro VII card**, with has the **VEGA906** architecture.    We do set the flag `Kokkos_ARCH_VEGA906` in our CMake configure script.  We are compiling and running the tests in a docker image with **Rocm 4.5**.

We tried to investigate why the tests are failing.  We noted that the architecture flag `--amdgpu-target=gfx906` (or `--offload-arch=gfx906`) is ultimately not passed to the compiler. On our computer, `hipcc` ended up choosing an old `gfx803` target that our GPU cannot handle, thus leading to the `hipErrorNoBinaryForGpu` error.

We checked which flags were passed to the compiler with `CMAKE_EXPORT_COMPILE_COMMANDS:BOOL=ON`.

We think we tracked down the issue to `kokkos_tribits.cmake`. In this file, there is an *if condition* such that when Kokkos is compiled in the context of a Trilinos build, the line `KOKKOS_SET_LIBRARY_PROPERTIES` is commented out (see https://github.com/trilinos/Trilinos/blob/3f08b33d13fcaa10f720a6672e73acbc0cb57929/packages/kokkos/cmake/kokkos_tribits.cmake#L519 ), whereas if Kokkos is compiled in standalone mode, it runs all fine because `KOKKOS_SET_LIBRARY_PROPERTIES` is called (see https://github.com/trilinos/Trilinos/blob/3f08b33d13fcaa10f720a6672e73acbc0cb57929/packages/kokkos/cmake/kokkos_tribits.cmake#L526 ). This macro `KOKKOS_SET_LIBRARY_PROPERTIES` calls

```cmake
TARGET_COMPILE_OPTIONS(
    ${LIBRARY_NAME}
    PUBLIC $<$<COMPILE_LANGUAGE:${KOKKOS_COMPILE_LANGUAGE}>:${KOKKOS_AMDGPU_OPTIONS}>
)
```

that sets the needed flags (see https://github.com/trilinos/Trilinos/blob/3f08b33d13fcaa10f720a6672e73acbc0cb57929/packages/kokkos/cmake/kokkos_tribits.cmake#L411 ).

We did notice that `Kokkos_ARCH_AMDAVX` and `Kokkos_ARCH_VOLTA70`  flags, which we use on other systems, lead to the corresponding architecture flags to be passed to the compiler (`-mavx` and `-arch=sm_70`, respectively).  We are not sure to understand why these flags are passed correctly whereas the AMD GPU ones are not (in our configuration).

**Comment by jhux2** [comment]
@trilinos/kokkos @bartlettroscoe

**Comment by jhux2** [comment]
@ndellingwood @lucbv @iyamazaki

**Comment by bartlettroscoe** [comment]
NOTE: Once we sync the updated TriBITS (in https://github.com/TriBITSPub/TriBITS/pull/479) to Trilinos 'develop', then the Trilinos CMake system will be using full modern CMake and any compiler options attached to Kokkos library targets should be propagated forward to downstream Trilinos targets  (and CMake customers downstream from Trilinos through imported targets in the installed `<Package>Config.cmake` files).

That merge could happen in the next week depending on how testing goes.

**Comment by jjellio** [comment]
The easiest work around I know, is to set
```
CMAKE_CXX_FLAGS="--offload-arch=gfx906 --rocm-path=/opt/rocm-4.5.0 -x hip"
CMAKE_EXE_LINKER_FLAGS="-x none"
```

That works because the last `-x` flag on the link line is respected, and you can't invoke the linker with `-x hip`.  Hopefully the Cmake stuff goes through soon

**Comment by maartenarnst** [comment]
Thanks, @jjellio, the current fix of enforcing the offload architecture in the flags works indeed.

Thanks, @bartlettroscoe!  We have seen that 
- https://github.com/TriBITSPub/TriBITS/pull/479

has been merged recently.  When do you expect the changes to be synced to Trilinos, so that we can test how the hip flags are passed?

**Comment by bartlettroscoe** [comment]
> When do you expect the changes to be synced to Trilinos, so that we can test how the hip flags are passed?

@maartenarnst, I should be able to post the PR that syncs TriBITS 'master' to Trilinos 'develop' any day now.

**Comment by maartenarnst** [comment]
Following the bot's message, we have checked our build logs, and the rocm flags are now passed. They appear in the `Trilinos_CXX_COMPILER_FLAGS` variable. So, I think we can close this issue. Thanks @bartlettroscoe and @ndellingwood for fixing this!
