### ISSUE TITLE
How to exchange the halo using Tpetra::Vector

### ISSUE THREAD

**Issue by YongjunZHENG** [trilinos/Trilinos#10558]
## Question
@trilinos/Tpetra

Using 2D domain decomposition, each subdomain has a halo region around it owned data for easy implementation of such as finite difference methods. For evolution problems, each timestep, the halo region need to be updated with data from the corresponding neighbour processors.

I can use Import to distribute a vector using a map without halo region to a vector using a map with halo region, but this way needs two vectors and also exchanges already-owned data.  How to exchange only the data in halo region using a inplace vector? 

I tried the enclosed code but it failed to give me a correct solution. 
[exam.txt](https://github.com/trilinos/Trilinos/files/8754083/exam.txt)

Thank you in advance.

Yongjun Zheng

**Comment by cgcgcg** [comment]
@trilinos/tpetra

**Comment by csiefer2** [comment]
The Tpetra FEMultiVector provides this functionality.

[See this](https://docs.trilinos.org/dev/packages/tpetra/doc/html/Tpetra__FEMultiVector__decl_8hpp_source.html)

**Comment by YongjunZHENG** [comment]
@csiefer2 Thanks for the suggestion. If my understanding was not wrong,  using  memory aliasing requires the owned data follows the halo (shared) data or the halo data follows the owned data. In this way, it's feasible to exchange the halo without copying such as
`
	Teuchos::RCP<vector_type> data = Teuchos::rcp (new vector_type (data_halo, dataMap, 0));
	Teuchos::RCP<vector_type> halo = Teuchos::rcp (new vector_type (data_halo, haloMap, data->getLocalLength()));
	import_type importer (dataMap, haloMap);
	data->doImport(*data, importer, Tpetra::INSERT);
`

But for a structured mesh,  the local vector

**Comment by YongjunZHENG** [comment]
Sorry I do not why it was closed, so I reopen it.

**Comment by YongjunZHENG** [comment]
Sorry I accidently clicked close button. I reopen it.

**Comment by csiefer2** [comment]
Yeah, you can't do that.
