### ISSUE TITLE
what is the order of vector output by the  "VectorToMatrixMarketFile"

### ISSUE THREAD

**Issue by ztdepztdep** [trilinos/Trilinos#10568]
Dear friends:
    I output my distributed vector by  "VectorToMatrixMarketFile" API, but I found that the order of vector in the file is not in the natural order. Could you please give me some help with how to output the vector in the natural order? (0. 1 , 2,3,4 ...........)
Regards

**Comment by cgcgcg** [comment]
I believe the output vector is ordered by GID, but that's just by looking at the code, so I might be mistaken.

**Comment by csiefer2** [comment]
Yeah, EpetraExt's output order is by local id (mot global) if you're in serial.

Christian is right: Dump the map to check
