### ISSUE TITLE
MueLu:  Schur complement based block smoother

### ISSUE THREAD

**Issue by maxfirmbach** [trilinos/Trilinos#10567]
## Question
@trilinos/muelu

Right now the schur complement calculation is restricted to a 2x2 matrix and hard coded to be calculated on the second diagonal matrix block. This also restricts the corresponding block smoothers to exactly facilitate this structure.

In my application case I would need a block smoother using the schur complement on the first diagonal matrix block to be efficient. My question is how one could implement this in MueLu. The schur complement calculation shouldn't be the main concern here, but how to handle the block smoothers. I could include some kind of if/else in the exisiting ones to alter the algorithm do produce the correct result, but this bloats up the code.

Is there another, maybe more elegant way to do this?

Joined work with @mayrmt

**Comment by mayrmt** [comment]
@trilinos/muelu

**Comment by mayrmt** [comment]
A technical realization of my proposal will likely result in a similar design as proposed by @pohm01. I'll have to think about that a bit more...

**Comment by maxfirmbach** [comment]
Thanks for the hints!
It looks like MueLu offers a `ReorderBlockAFactory`, which should work for reordering the block structure. Additionally I have seen, that the schur complement smoothers make also use of this by checking if the operator is reordered and if so flipping the vectors of the iteration procedure.

I'll try this out, but it seems like this already solves my problem.

**Comment by tawiesn** [comment]
@maxfirmbach The above check is certainly not complete, but covered all the relevant use cases so far. But i am quite sure, that for more general use cases (nested blocked operators), there might be some fixes necessary...

**Comment by maxfirmbach** [comment]
@tawiesn Okay, then I'll might modify some statements and try to get my application running :+1:
