### ISSUE TITLE
Zoltan2:  Kokkos error when using multijagged decomp method

### ISSUE THREAD

**Issue by alanw0** [trilinos/Trilinos#10577]
## Bug Report
@trilinos/Zoltan2

### Description
We are seeing this kokkos error when using Zoltan2 with the multijagged decomposition method:
Constructor for Kokkos View '' has mismatched number of arguments. Number of arguments = 0 but dynamic rank = 1

This is occurring with the master branch of Trilinos, in Sierra builds. It appears to happen when calling Zoltan2 via Muelu, and also when calling Zoltan2 via stk_balance.
@jclause is setting up a bisect so that we can provide more/better information on when this was introduced. It was not in Sierra's previous copy of Trilinos which was pulled roughly April 8th.

**Comment by cgcgcg** [comment]
@egboman

**Comment by jhux2** [comment]
@alanw0 Is this still a problem?

**Comment by alanw0** [comment]
No this doesn't appear to be an issue any more.
