### ISSUE TITLE
All Trilinos Packages: How to Install from Anasazi to Belos after Building Trilinos?

### ISSUE THREAD

**Issue by glanzkaiser** [trilinos/Trilinos#10576]
## Question
@trilinos/\<Anasazi\>

I am just learning about Trilinos and want to use Anasazi package. I follow this guide:
https://docs.trilinos.org/files/TrilinosBuildReference.html

I build Trilinos by using this file that I have adjusted for the path:
https://github.com/trilinos/Trilinos/blob/master/sampleScripts/do-configure-mkl-mpi-gcc-linux

When I run make then make install, the libraries and include files are only for Kokkos, TPetra, and Teuchos.
How to install Anasazi libraries and include/headers files?

I also want to know whether I can build and install all packages beside Anasazi? so I will have them all complete for Trilinos.

![Bildschirmfoto_2022-05-26_21-25-51](https://user-images.githubusercontent.com/72222484/170508441-af84f036-2e7a-4c08-9013-acd5fd6adc19.png)

**Comment by cgcgcg** [comment]
Did you enable the Anasazi package?

**Comment by glanzkaiser** [comment]
Yes, but I have to recompile and enable Anasazi now.

read on the website https://trilinos.github.io/mpi.html#
The MPI-only collection of packages is sometime referred to as the [Epetra](https://trilinos.github.io/mpi.html#) stack.
[MPI+X](https://trilinos.github.io/mpi_x.html) stack is sometimes called the [Tpetra](https://trilinos.github.io/mpi.html#) stack.

Does that means I only need to install / Enable Epetra to get all the MPI-only packages?
Then TPetra will include EPetra as well then since it is MPI + X ? Correct me if I am wrong.
I am a bit confused here.

![Bildschirmfoto_2022-05-27_05-47-57](https://user-images.githubusercontent.com/72222484/170591919-6324436b-c003-41e4-9974-a18ead219901.png)

**Comment by cgcgcg** [comment]
No, these are two different sets of packages. The Epetra packages are old, and should probably not be used for any new project. The Tpetra stack is newer, and also supports shared memory parallelism.

**Comment by glanzkaiser** [comment]
I see,

I have a hard time for Anasazi, it can't be compiled what is wrong ?
![Bildschirmfoto_2022-05-27_06-38-22](https://user-images.githubusercontent.com/72222484/170598535-09bd9583-aeb2-4a31-8ff0-518b86b084f0.png)
