### ISSUE TITLE
Demos MyApp Error: MPI_ERRORS

### ISSUE THREAD

**Issue by glanzkaiser** [trilinos/Trilinos#10582]
## Bug Report
@trilinos/demos

### Description
I have built Trilinos with do-configure (https://github.com/glanzkaiser/GFreya/blob/main/BLFS/Trilinos-do-configure-blas-lapack-mpi-gcc-linux) till finish then do 
**make install**

Now I go back to the src folder/directory (the one I git clone), I try to compile the demo here:
https://github.com/trilinos/Trilinos/tree/master/demos/simpleBuildAgainstTrilinos

When I try to run it by typing:
**./MyApp**

and then **ctest**

It said MPI Errors here are the screenshots:

![Bildschirmfoto_2022-05-28_14-46-08](https://user-images.githubusercontent.com/72222484/170816076-1fe85d24-82d1-4468-b08a-eb190d3d943c.png)
![Bildschirmfoto_2022-05-28_14-46-19](https://user-images.githubusercontent.com/72222484/170816079-4d60a0d0-10df-4f35-834c-0e682ef31b0b.png)

The questions is simple:
how to fix this MPI Error?

**Comment by csiefer2** [comment]
Can you get an MPI-only hello world problem to work?

**Comment by glanzkaiser** [comment]
Hi @csiefer2 ,

thanks for the reply, I try two different "Hello World" mpi examples:
1. https://github.com/mpitutorial/mpitutorial/blob/gh-pages/tutorials/mpi-hello-world/code/mpi_hello_world.c
2. https://en.wikipedia.org/wiki/Message_Passing_Interface

It still get the same ompi_rte_init failed.. I wonder, perhaps I have to reinstall / rebuild MPI. Any suggestions beside this that I need to check ?


![mpieror2](https://user-images.githubusercontent.com/72222484/170857247-d05f08cb-eddd-497b-8ccd-b4e91aed8ccd.png)
![mpierror1](https://user-images.githubusercontent.com/72222484/170857251-72d08d16-1cae-4f80-ab25-944ba517d853.png)

**Comment by glanzkaiser** [comment]
Just to make clear for everybody,
I installed OpenMPI 4.1.3
and want to install the newest OpenMPI 4.1.4
(https://download.open-mpi.org/release/open-mpi/v4.1/openmpi-4.1.4.tar.gz)

Is it okay with the Trilinos version in the newest develop branch?

MPI and OpenMPI are different right? Are there any packages I need to install to make MPI_init works correctly?

Thank You

**Comment by glanzkaiser** [comment]
Hi all,

I just fixed MPI problem, but it seems the library problem occurs now, I can run Hello World example for MPI, but when I try to run ./MyApp it said that

**no such libmpi.so.40**

I know my problem that I install openmpi-2.1.1 along with OpenFOAM-9, so I need to uninstall the OpenMPI 4.1.4, since when running

**
![Bildschirmfoto_2022-05-30_14-09-07](https://user-images.githubusercontent.com/72222484/170937111-db2ee315-d37f-4803-8204-db0f12a9ef44.png)
![blfs-prob-38-4](https://user-images.githubusercontent.com/72222484/170937079-9ec5a98e-7e18-4987-8aa5-79eeaecefc94.png)**

It leads to the openmpi-2.1.1 

So, anyone here knows how to make libmpi.so.40 ? I also try to solve this here.

**Comment by csiefer2** [comment]
OpenMPI , MPICH and MVAPICH are three most common open implementations of the MPI standard.  Trilinos notionally shouldn't care which one you use.

As for your MyApp, you either need to make sure your MPI library is in your LD_LIBRARY_PATH or do the -rpath dance when you compile

**Comment by jjellio** [comment]
I suspect many of these errors come from running as root.  You're using linux, just install openmpi (using sudo yum install openmpi or apt install openmpi or whatever package manger you have). 

Do all your work work as your regular user account.  You may need to add your *user* ssh public key to the authorized_keys file. e.g., `cat $HOME/.ssh/some_key_name.pub >> $HOME/.ssh/authorized_keys` and maybe do the same to putting it into `authorized_keys2`. 

You should be able to do `ssh localhost` and have that work without a password. All of this as your user account. 


You could also install OpenMPI through [spack](https://github.com/spack/spack), but you will have learn how to do that.  I believe spack will even install OpenFOAM (and Trilinos). something like `spack install openfoam ^openmpi` - but don't quote me on that, there's probably a guide somewhere about it.

**Comment by csiefer2** [comment]
-D TPL_ENABLE_MPI=OFF

will disable MPI for Trilinos

**Comment by glanzkaiser** [comment]
I am compiling without MPI and OpenMP now.
Hopefully it will work. Thank You all.

**Comment by glanzkaiser** [comment]
Just to inform all of you here, after disabling MPI and OpenMP the example can work, at the build directory I try Anasazi - Epetra - BlockDavidson and it can show the computation result.

The problem is the compiling actually not finish as the post above that I have shown. I don't know why NOX LOCA compiling becomes error.

Thank you to all of you who have helped.

![Bildschirmfoto_2022-06-01_17-22-17](https://user-images.githubusercontent.com/72222484/171383240-7d2038c4-a7b8-4b0a-823b-8592a8dac6e3.png)

**Comment by csiefer2** [comment]
You could just disable the NOX tests.

**Comment by glanzkaiser** [comment]
Alright thanks @csiefer2
