### ISSUE TITLE
Anasazi: How to Build Example for Anasazi and Modify the Matrix A

### ISSUE THREAD

**Issue by glanzkaiser** [trilinos/Trilinos#10596]
Hi all,

I am learning this Anasazi as my first solver in Trilinos. I want to know how to edit / modify the matrix A to calculate the Eigenvalues. I can run the example /exe, but I want to modify the input matrix.

Where are the location for cpp? Is it the build directory or the source directory that I should look at? 

As source directory: **I git clone Trilinos**

Thanks.

![Bildschirmfoto_2022-06-01_17-22-17](https://user-images.githubusercontent.com/72222484/171383240-7d2038c4-a7b8-4b0a-823b-8592a8dac6e3.png)

**Comment by jhux2** [comment]
@trilinos/anasazi

**Comment by amklinv-nnl** [comment]
The example source files can be found here: https://github.com/trilinos/Trilinos/tree/master/packages/anasazi/epetra/example/BlockDavidson

**Comment by glanzkaiser** [comment]
Alright thank you @amklinv-nnl
