### ISSUE TITLE
Try Kokkos Example: Illegal Instruction

### ISSUE THREAD

**Issue by glanzkaiser** [trilinos/Trilinos#10593]
Hi all,

I build Trilinos after cloning the git repository of Trilinos without MPI and OpenMP.

I go to the source directory <Trilinos>/packages/kokkos/example

I try the Hello Lambda, it can be compiled but when I run it, it said:
**Illegal Instruction**

How to fix it? Do I need to rebuild with OpenMP=ON? 

![Bildschirmfoto_2022-06-03_06-54-52](https://user-images.githubusercontent.com/72222484/171759017-17028c5f-7156-4301-ad5a-d1e276dfe7da.png)

**Comment by glanzkaiser** [comment]
I am calling `make` in my source folder not the build folder.

**Comment by cgcgcg** [comment]
Please build in the build folder.

**Comment by glanzkaiser** [comment]
I try to, but I can't build it in the build folder, as the build folder of kokkos has no example, thus I move example folder from src to build folder.

I am trying to build again now.

**Comment by glanzkaiser** [comment]
Yes I enable Kokkos Examples and in the build folder there is no example folder, and I move it manually from source but it can't be built.

* I build Trilinos without MPI and OpenMP, I hope that is not the source of the problem.

![Bildschirmfoto_2022-06-04_14-57-53](https://user-images.githubusercontent.com/72222484/171990452-e5337a39-99d4-442b-873f-db2adb96a41a.png)
![Bildschirmfoto_2022-06-04_14-58-06](https://user-images.githubusercontent.com/72222484/171990454-385342be-14e8-415d-8de1-c05902ab94cc.png)

**Comment by cgcgcg** [comment]
@glanzkaiser If the MPI on your system is messed up we cannot do anything to fix that.

**Comment by glanzkaiser** [comment]
I understand then I try to ask at stackoverflow then go bak to Trilinos after my MPI is fixed.
