### ISSUE TITLE
Question regarding thread parallel implementations of solvers and preconditioners in Trilinos 12.2.1

### ISSUE THREAD

**Issue by kongm** [trilinos/Trilinos#1060]
Hi,

I'd like to know which of these solvers and preconditioners are thread-parallel and can execute in hybrid mode (MPI + OpenMP) in Trilinos 12.2.1:
- GMRES
- CG
- Jacobi
- Gauss-Seidel

Thanks,

**Comment by jjellio** [comment]
For GMRES and CG, the bulk of the solver's work is in dot products and vector updates (axpy), and sparse mat-vecs. With GMRES, the larger your subspace (restart length), the more performance will be dominated by calls to dgemv (essentially bulk dot products), if you use ICGS for orthogonalization. If you keep the default (DGKS), you will do lots of dot products.

Tpetra defers calls to dense BLAS to whatever BLAS you linked against.  That is, GMRES/CG will see performance mostly controlled by the quality of your underlying dense BLAS.  Threaded MKL is thread scalable from my experience, as is the sparse mat-vec that Tpetra provides.

Preconditioners are a different story. @srajama1 can probably give you a better idea than me.

For the solvers, link a good threaded BLAS, and you will likely see reasonable GMRES performance. Provided you set OMP_NUM_THREADS, OMP_PLACES, and do not oversubscribe the system you run on.

**Comment by mhoemmen** [comment]
@kongm If you want thread-parallel solvers, it would be best to commit to using the latest version of Trilinos, for proper performance improvements.

**Comment by dlkarnit** [comment]
How true are these statements for Trilinos 12.10?

I believe my BLAS implementation does not support threading (netlib reference BLAS), but I still see perfect 2x speedups with 2 threads for a solver that uses a MueLu preconditioner with Multi-Threaded SGS smoother in a Belos/Tpetra BICGSTAB solver.

**Comment by aprokop** [comment]
> I still see perfect 2x speedups with 2 threads for a solver that uses a MueLu preconditioner with Multi-Threaded SGS smoother in a Belos/Tpetra BICGSTAB solver.

This is really weird. How large is your problem?

**Comment by dlkarnit** [comment]
This particular problem is only ~100k unknowns.

**Comment by mhoemmen** [comment]
I'm closing this issue for now.  Please reopen if you have new information.  Thanks!
