### ISSUE TITLE
Stratimikos:  Missing header Stratimikos_LinearSolverBuilder.hpp

### ISSUE THREAD

**Issue by lxmota** [trilinos/Trilinos#10607]
## Bug Report
@trilinos/\stratimikos

### Description

When trying to compile Albany/LCM, the file `Stratimikos_DefaultLinearSolverBuilder.hpp` has an include for a file `Stratimikos_LinearSolverBuilder.hpp` that does not exist, so the compilation fails. This missing file is also referenced on other files within stratimikos and muelu:

```
[ 89%] Building CXX object src/LCM/CMakeFiles/LCM.dir/evaluators/responses/ProjectIPtoNodalField.cpp.o
In file included from /home/lcm/LCM/LCM/src/LCM/evaluators/responses/ProjectIPtoNodalField.hpp:12,
                 from /home/lcm/LCM/LCM/src/LCM/evaluators/responses/ProjectIPtoNodalField.cpp:5:
/home/lcm/LCM/trilinos-install-serial-gcc-release/include/Stratimikos_DefaultLinearSolverBuilder.hpp:46:10: fatal error: Stratimikos_LinearSolverBuilder.hpp: No such file or directory
 #include "Stratimikos_LinearSolverBuilder.hpp"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

**Comment by lxmota** [comment]
@ikalash Do you see this as well on Albany?

**Comment by ikalash** [comment]
Yes - I already opened an issue: https://github.com/sandialabs/Albany/issues/813 .  I am hoping someone will fix this, as I'm on foreign travel and don't have access to my nightly builds...

**Comment by ikalash** [comment]
I opened an Albany issue to be clear - but opening a Trilinos one like you did is more efficient.

**Comment by jewatkins** [comment]
I confirmed this PR fixes the issue: https://github.com/trilinos/Trilinos/pull/10605

**Comment by cgcgcg** [comment]
Sorry about that!
@jewatkins Thanks for checking that #10605 works in combination with Albany.

**Comment by cgcgcg** [comment]
This should be fixed. Please reopen if this is still an issue.
