### ISSUE TITLE
How convert the HYPRE_IJVector and HYPRE_ParVector to vector of double or array

### ISSUE THREAD

**Issue by Resacd** [trilinos/Trilinos#10611]
I'm using HYPRE to solve a system of linear equations. I already set up the solver and got the result. The results are in HYPRE_IJVector or HYPRE_ParVector and I need to convert them to vector or array. I would be grateful if someone can help me to do this.

**Comment by cgcgcg** [comment]
Are you using the Trilinos interfaces to Hypre?

**Comment by Resacd** [comment]
No, I'm using the hypre from different source but I belive this is the same as hypre in trilinos. Isn't it?

**Comment by cgcgcg** [comment]
Hypre is not part of Trilinos.
