### ISSUE TITLE
Tpetra/Kokkos-kernels: compilation error in HIP build when enabling complex double

### ISSUE THREAD

**Issue by maartenarnst** [trilinos/Trilinos#10612]
## Bug Report
@trilinos/tpetra @trilinos/kokkos-kernels

### Description
What went wrong?  

We are compiling Trilinos with Rocm 5.1.  We are seeing compilation errors when we enable complex doubles (`Trilinos_ENABLE_COMPLEX_DOUBLE`=`ON`).   

The compilation errors look like:

```
~/Trilinos/packages/kokkos-kernels/src/Kokkos_ArithTraits.hpp:1290:12: error: no matching function for call to 'isinf'
    return isinf(real(x)) || isinf(imag(x));
           ^~~~~
~/Trilinos/packages/tpetra/core/src/Tpetra_computeRowAndColumnOneNorms_def.hpp:193:18: note: in instantiation of member function 'Kokkos::Details::ArithTraits<std::complex<double>>::isInf' requested here
        if (KAT::isInf (matrixVal)) {
                 ^
~/Trilinos/packages/tpetra/core/src/Tpetra_computeRowAndColumnOneNorms_def.hpp:675:12: note: in instantiation of function template specialization 'Tpetra::Details::computeLocalRowOneNorms_RowMatrix<std::complex<double>, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace>>' requested here
     return computeLocalRowOneNorms_RowMatrix (A);
            ^
 ~/Trilinos/packages/tpetra/core/src/Tpetra_computeRowAndColumnOneNorms_def.hpp:992:26: note: in instantiation of function template specialization 'Tpetra::Details::computeLocalRowOneNorms<std::complex<double>, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace>>' requested here
   auto result = Details::computeLocalRowOneNorms (A);
                          ^
 /opt/rocm-5.1.0/llvm/lib/clang/14.0.0/include/__clang_hip_cmath.h:509:23: note: candidate template ignored: substitution failure [with __T = double]: no type named 'type' in '__hip_enable_if<false, bool>'
 __HIP_OVERLOAD1(bool, isinf)
 ~~~~~~~~~~~~~~~~~~~~~~^~~~~~
 /opt/rocm-5.1.0/llvm/lib/clang/14.0.0/include/__clang_hip_cmath.h:449:7: note: expanded from macro '__HIP_OVERLOAD1'
       __fn(__T __x) {                                                          \
       ^
 /opt/rocm-5.1.0/llvm/lib/clang/14.0.0/include/__clang_hip_cmath.h:93:31: note: candidate function not viable: call to __device__ function from __host__ function
 __DEVICE__ __CONSTEXPR__ bool isinf(float __x) { return ::__isinff(__x); }
                               ^
 /opt/rocm-5.1.0/llvm/lib/clang/14.0.0/include/__clang_hip_cmath.h:94:31: note: candidate function not viable: call to __device__ function from __host__ function
 __DEVICE__ __CONSTEXPR__ bool isinf(double __x) { return ::__isinf(__x); }
                               ^
 In file included from ~/Trilinos/build-with-GNU-ROCm/packages/tpetra/core/src/Tpetra_computeRowAndColumnOneNorms_COMPLEX_DOUBLE_INT_LONG_LONG_SERIAL.cpp:68:
 In file included from ~/Trilinos/packages/tpetra/core/src/Tpetra_computeRowAndColumnOneNorms_decl.hpp:49:
```

Do you have an idea what might fix things?  

The compilation errors arise in instantiations related to `Tpetra_computeRowAndColumnOneNorms_decl.hpp` and the corresponding `_def.hpp` file.  The functions `forEachLocalRowMatrixRow` and `computeLocalRowAndColumnOneNorms_RowMatrix` in these files do computations on host mirrors of views.  When complex doubles are enabled, they call `Kokkos_ArithTraits.hpp` 's specialisations for the `isNan` and `isInf` functions for `std::complex<double>`.  Around line 1290 in `Kokkos_ArithTraits.hpp`, we can see that these specialisations want to use `std::isnan` and `std::isinf`.  However, these uses are guarded by the macro `KOKKOS_ACTIVE_EXECUTION_MEMORY_SPACE_HOST`.  This macro is defined in `Kokkos_Macros.hpp` and appears to be essentially a proxy for `__HIP_DEVICE_COMPILE__` not being defined.  What appears to be happening is that this macro `KOKKOS_ACTIVE_EXECUTION_MEMORY_SPACE_HOST` is not defined in the pass that `hipcc` makes over this file when the compilation error arises.  It seems `__HIP_DEVICE_COMPILE__` is defined even though `hipcc` is compiling host code.

One way we found to reproduce these compilation errors in a simple example is to try to compile the following code with `hipcc` (with Trilinos's includes and linker flags):

```cpp
#include <iostream>
#include <complex>

#include "Kokkos_Core.hpp"

double isInf(std::complex<double> x) {
    #if defined(KOKKOS_ACTIVE_EXECUTION_MEMORY_SPACE_HOST)
        using std::isinf;
    #endif
    return isinf(real(x));
}
int main() {};
``` 

The compilation fails with similar compilation error messages.   It appears that `hipcc` passes over the code twice, once with `__HIP_DEVICE_COMPILE__` defined and once with `__HIP_DEVICE_COMPILE__` not defined.  It appears to be the pass with `__HIP_DEVICE_COMPILE__` defined that causes the problem.  As in the case of the tpetra compilation error, it is not clear to me why `hipcc` wants to pass over this file, seemingly only including host code, with `__HIP_DEVICE_COMPILE__` defined.

It may also be worthwhile to mention that it is not completely clear to me why the macro `KOKKOS_ACTIVE_EXECUTION_MEMORY_SPACE_HOST` is used in `Kokkos_ArithTraits.hpp` 's specialisations for the `isNan` and `isInf` functions for `std::complex<double>`.  These functions are not marked as Kokkos functions, which appears to suggest that they are compiled only as host code, so it is not completely clear why the guard by the macro is needed.  Removing the guard by the macro might be one way to avoid the compilation errors.  To know whether such a fix would be a good fix, it would probably be important to understand better why the guard by the macro is needed.

**Comment by csiefer2** [comment]
@brian-kelley @lucbv Can you add anything here?

**Comment by brian-kelley** [comment]
@maartenarnst Both of the issues you bring up are valid actually - ``Kokkos::ArithTraits<std::complex<T>>`` is supposed to be supported (in host code obviously), but this Tpetra file is also mixing up the scalar (SC) and impl_scalar types. This is technically OK here as ``std::complex`` is not getting used in device code, and ``std::complex`` and ``Kokkos::complex`` can implicitly convert to each other, but it would still be good to clean this up.

I found that the first issue can be fixed by letting the Kokkos mathematical function wrapper ``Kokkos::Experimental::isnan`` decide the namespace. In this situation it uses ``std::isnan`` and ``std::isinf``, which work. Kokkos_ArithTraits.hpp was trying to just call ``isnan`` and ``isinf``.

Your patch here looks like a good fix for the second issue, thanks for spending time on this! This could be a PR on its own - would you like to open it yourself, or should I create it with your patch?

**Comment by brian-kelley** [comment]
@glhenni That is not related - we recently removed all deprecated code including the getLocalView... functions that don't take access tags. Your code should work if you replace getLocalViewDevice with one of the following, depending on how ``y`` gets used:
```
Y.getLocalViewDevice (Tpetra::Access::ReadOnly) // if you just need a const, read-only view
Y.getLocalViewDevice (Tpetra::Access::ReadWrite) // if you need a nonconst/mutable view
Y.getLocalViewDevice (Tpetra::Access::OverwriteAll) // if you are going to overwrite the entirety of Y - you don't care about the existing contents
```

**Comment by maartenarnst** [comment]
Thanks a lot for the feedback and the PR, @brian-kelley !

I have just made the PR for the issue related to `Tpetra_computeRowAndColumnOneNorms_def.hpp` based on the patch in the comment above.  It's PR #10656.
