### ISSUE TITLE
MueLu:  Support extended MHD models

### ISSUE THREAD

**Issue by rstumin** [trilinos/Trilinos#10619]
## Enhancement
@trilinos/muelu

Current preconditioning options for our MHD system do not address very well extended MHD models very efficiently, at least within some parameter ranges. This includes extended systems that incorporate a hall term, which can introduce a new new large null space operator associated with the fact that $\nabla \times B$  has a nontrivial null space. We are currently investigating patch methods to address this null space.  More information can be found on a Sandia internal webpage https://cee-gitlab.sandia.gov/alegra/source-code/alegranevada/-/issues/662

**Comment by GrahamBenHarper** [comment]
Just as an FYI, I can't read the internal linked issue. I suppose the repo is probably set to private.

**Comment by GrahamBenHarper** [comment]
bad bot. as far as I know, this is still in-progress
