### ISSUE TITLE
DUPLICATE: Getting consistent mass system PR failures with Trilinos PR #10614 with missing results on CDash

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#10622]
@trilinos/framework 

Looks like we are getting mass system failures in PR testing and existing failures on the 'develop' branch

For the PR #10614, all 5 of the PR testing iterations in #10614 show failures in all but one one build (only the build `Trilinos_PR_gcc-7.2.0-serial` is shown passing).  If you look at the builds for PR #10614 submitted to CDash [here](https://trilinos-cdash.sandia.gov/index.php?project=Trilinos&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=63&value1=PR-10614-test&field2=buildstarttime&compare2=84&value2=NOW), you can see there are a lot of missing builds and results:

![image](https://user-images.githubusercontent.com/1959736/173392803-b6269cf1-40f7-4f87-ad0d-30091c756f1e.png)

It looks like there is a pattern for which builds are reporting results and which ones are not:

* **Trilinos_PR_gcc-8.3.0** (`rhel7_sems-gnu-8.3.0-openmpi-1.10.1-openmp_release-debug_static_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables`):
  * Only build name shows up, there are **no configure, build or test results shown on CDash**
* **Trilinos_PR_gcc-7.2.0-serial** (`rhel7_sems-gnu-7.2.0-serial_release-debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_no-mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables`:
  * **All passing and all results shown on CDash**
* **Trilinos_PR_gcc-7.2.0-debug** (`rhel7_sems-gnu-7.2.0-openmpi-1.10.1-serial_debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables`):
  * **Reports 6 errors but no build error details show** and **reports 2 failing SEACAS tests**
* **Trilinos_PR_intel-17.0.1** (`rhel7_sems-intel-17.0.1-mpich-3.2-serial_release-debug_static_no-kokkos-arch_no-asan_no-complex_fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables`): 
  * Only build name shows up, there are **no configure, build or test results shown on CDash**
* **Trilinos_PR_clang-10.0.0** (`rhel7_sems-clang-10.0.0-openmpi-1.10.1-serial_release-debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables`):
  * Only build name shows up, there are **no configure, build or test results shown on CDash**
* **Trilinos_PR_cuda-10.1.243** (`ats2_cuda-10.1.243-gnu-8.3.1-spmpi-rolling_release_static_Volta70_Power9_no-asan_no-complex_no-fpic_mpi_pt_no-rdc_uvm_deprecated-on_no-package-enables`):
  * Only build name shows up, there are **no configure, build or test results shown on CDash**
* **Trilinos_PR_python3** (`rhel7_sems-gnu-7.2.0-anaconda3-serial_debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_no-mpi_no-pt_no-rdc_no-uvm_deprecated-on_pr-framework`):
  * Only build name shows up, there are **no configure, build or test results shown on CDash**

It is reporting 6 build errors for the build **Trilinos_PR_gcc-7.2.0-debug** (`rhel7_sems-gnu-7.2.0-anaconda3-serial_debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_no-mpi_no-pt_no-rdc_no-uvm_deprecated-on_pr-framework`) like [here](https://trilinos-cdash.sandia.gov/viewBuildError.php?buildid=177793), but when I click on the '6', it shows now errors.

Unfortunately, with the GenConfig upgrade, we are no longer getting the Jenkins driver STDOUT posted to CDash so regular Trilinos developers have no way to see what is going wrong with the PR testing infrastructure.

In addition, there looks to be failing SEACS tests that have nothing to do with the PRs they are testing.  If you look at the failing tests for the PR build `test-rhel7_sems-gnu-7.2.0-anaconda3-serial_debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_no-mpi_no-pt_no-rdc_no-uvm_deprecated-on_pr-framework` shown [here](https://trilinos-cdash.sandia.gov/index.php?project=Trilinos&begin=2022-06-01&end=2022-06-13&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=63&value1=test-rhel7_sems-gnu-7.2.0-anaconda3-serial_debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_no-mpi_no-pt_no-rdc_no-uvm_deprecated-on_pr-framework&field2=testsfailed&compare2=43&value2=0) you see 8 runs impacting PRs #10614, #10565, and #10406    had the same two SEACAS failing tests:

* `SEACASIoss_pamgen_exodus_io_info`
* `SEACASIoss_Utst_blob_write_read`

going back to 2022/06/09.  And you can see the these failing tests [here](https://trilinos-cdash.sandia.gov/queryTests.php?project=Trilinos&begin=2022-06-01&end=2022-06-13&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=63&value1=test-rhel7_sems-gnu-7.2.0-anaconda3-serial_debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_no-mpi_no-pt_no-rdc_no-uvm_deprecated-on_pr-framework&field2=status&compare2=62&value2=Passed&field3=block&field3count=2&field3field1=testname&field3compare1=61&field3value1=SEACASIoss_pamgen_exodus_io_info&field3field2=testname&field3compare2=61&field3value2=SEACASIoss_Utst_blob_write_read) showing:

![image](https://user-images.githubusercontent.com/1959736/173400487-30a78b94-4d66-49cf-91ed-b5d37b9e8db3.png)

Can someone on the Trilinos framework team please look into what is happening with all of these failures?

**Comment by e10harvey** [comment]
Sorry about that. I'm still having trouble understanding the existing build&test infrastructure in Trilinos. I think I see the problem and will flag you in the PR.

**Comment by bartlettroscoe** [comment]
Hello @e10harvey, it looks like we are still getting mass infrastructure failures in the PR builds for PR #10614 as shown in the last iteration that just finished 30 minutes ago in https://github.com/trilinos/Trilinos/pull/10614#issuecomment-1158077767 where we are missing a bunch of results showing:

![image](https://user-images.githubusercontent.com/1959736/174159213-21aee1af-30dc-4819-9a91-652145ef7f55.png)

Again, there is no info on GitHub or CDash to give a hit what is wrong here.

**Comment by e10harvey** [comment]
> Again, there is no info on GitHub or CDash to give a hit what is wrong here.

@bartlettroscoe: THanks for reporting. THis is a separate with the cdash server: TRILINOSHD-91. Opening a ticket with the server team now.

**Comment by bartlettroscoe** [comment]
> His is a separate with the cdash server: TRILINOSHD-91. Opening a ticket with the server team now.

@e10harvey,  I can't access TRILINOSHD-91.  Please make sure and loop in Zack Galbreath at Kitware for any issues with CDash. 
 Please don't try to resolve CDash issues on your own.  (This is why we have a contact with Kitware.)

**Comment by bartlettroscoe** [comment]
FYI: An internal issue to address the CDash submit errors has been created:

* https://ndds-jira.sandia.gov/servicedesk/customer/portal/4/DICE-3391

and this has been put at the top of Selected for the SNL Kitware work:

* https://gitlab.kitware.com/snl/project-1/-/issues/209

**Comment by bartlettroscoe** [comment]
FYI: I opened the new issue #10836 for the specific mysterious "6" build errors problem.  Closing these issue as a duplicate (also PR #10614 was eventually merged).
