### ISSUE TITLE
Phalanx: build MDField<const ScalarT> from Tag<ScalarT>

### ISSUE THREAD

**Issue by ibaned** [trilinos/Trilinos#1063]
In Albany, there are complex evaluators which construct their `MDField` members from `Tag`s that are passed in through the parameter list. Until now, `MDField<ScalarT>` built from `Tag<ScalarT>` was fine. In working on  gahansen/Albany#34, I now have `MDField<const ScalarT>` that I'd still like to build from a `Tag<ScalarT>`. I tried
```cpp
field(tag.name(), tag.dataLayout())
```
but `dataLayout` returns a const reference to the layout and the field constructor expects an RCP of a non-const layout. I propose this function be added to `FieldTag` and `Tag<T>`:
```cpp
Teuchos::RCP<PHX::DataLayout> dataLayoutRCP() { return m_data_layout; }
```
unless there is an easier way to do what I'm trying to do, which is also fine.
@trilinos/phalanx @rppawlo

**Comment by rppawlo** [comment]
@ibaned - I will test your suggestion and explore some alternate interoperability options and will try to have a fix in soon. Sorry for the trouble.

**Comment by rppawlo** [comment]
Added a templated copy ctor for the tag class that accepts const or nonconst data types. The tag will get implicitly cast to the correct type for the mdfield. This should work without having to change any code now for the MDField ctor. Unit tests demonstrate this. Tests are running for application codes and if everything passes will push by end of today.

**Comment by ibaned** [comment]
@rppawlo much appreciated, looking forward to it.
