### ISSUE TITLE
ROCBLAS and ROCSOLVER as TPL in Trilinos

### ISSUE THREAD

**Issue by kyungjoo-kim** [trilinos/Trilinos#10640]
## Enhancement

@trilinos/framework I tagged framework because I am not sure who is working on Trilinos cmake build system. 

Could you add ROCBLAS and ROCSOLVER in Trilinos ? This is needed for AMD platform. Sandia ASC applications require the vendor libraries.

**Comment by e10harvey** [comment]
@kyungjoo-kim: If this does not get attention, please submit a ticket to trilinos-help.

**Comment by kyungjoo-kim** [comment]
FYI: @crdohrm .
