### ISSUE TITLE
Amesos2:  Supporting SuperLU_DIST 8.0.0

### ISSUE THREAD

**Issue by keitat** [trilinos/Trilinos#10652]
## Enhancement
@trilinos/amesos2 

The recent release of SuperLU_DIST 8.0.0, released last month, (https://github.com/xiaoyeli/superlu_dist) introduced a change in the APIs (e.g. the first argument of pdgstrs takes a struct representing a few parameters. It is no longer taking a single integer.). 

The xSDK team found this problem during the compile time https://github.com/xsdk-project/xsdk-issues/issues/168#event-6858883174/ .

To resolve this problem, I suggest having another `#ifdef` block to support the new APIs and introduce the new data type for that.

**Comment by srajama1** [comment]
@keitat If you already know what is the change, can you submit a PR please?

**Comment by ndellingwood** [comment]
Looks like this was addressed by #10673
