### ISSUE TITLE
STK: missing header for Mac clang

### ISSUE THREAD

**Issue by spdomin** [trilinos/Trilinos#10654]
## Bug Report
@trilinos/STK

### Description
Missing array header in Mac Clang Nalu build.  May occur on Nalu-Wind. Our Mac testing has been down for many weeks. There may be more to do. 

Error:

packages/stk/stk_util/stk_util/parallel/CMakeFiles/stk_util_parallel.dir/CouplingVersions.cpp

Resolved via:

diff --git a/packages/stk/stk_util/stk_util/parallel/CouplingVersions.cpp b/packages/stk/stk_util/stk_util/parallel/CouplingVersions.cpp
index ea82e6c..d327887 100644
--- a/packages/stk/stk_util/stk_util/parallel/CouplingVersions.cpp
+++ b/packages/stk/stk_util/stk_util/parallel/CouplingVersions.cpp
@@ -7,6 +7,7 @@
 #include <string>
 #include <iostream>
 #include <cassert>
+#include <array>
 
 namespace stk {
 namespace util {

### Steps to Reproduce
1. SHA1:  NaluCFD/Nalu SHA1: 0263ac4053093aba5ddddd80c1d7293a1c910769
Trilinos/develop SHA1: 1d147f1c7d8d708575ab412d78e3132c1d63ad3d

**Comment by alanw0** [comment]
We will put this fix in asap. It's too bad we don't have a mac clang build in the sierra environment, and none of our builds have caught this error.

**Comment by tasmith4** [comment]
@spdomin @jhux2 this fix is included in #10657

**Comment by spdomin** [comment]
All looks well now. I will close the ticket. Many thanks.

**Comment by alanw0** [comment]
@spdomin I'm a little puzzled that you appeared to see the fix when you did. It looks like our stk-to-trilinos pull-request didn't finish testing and merge until approx 3am this morning. But in any case, I believe it is resolved now.
