### ISSUE TITLE
Amesos2:  build with mumps errors

### ISSUE THREAD

**Issue by saitoasukakawaii** [trilinos/Trilinos#10667]
## Question
@trilinos/\<Amesos2\>

Dear all,
Firstly, I comiple mumps using intel oneAPI 2022.1.1 using intel compiler 2022.0.1, mpi 2021.5.0, and mkl 2022.0.1, then compile trilinos with mumps using intel oneAPI 2022.1.1using intel compiler 2022.0.1, mpi 2021.5.0, and mkl 2022.0.1 too. following are my cmake commands:
`cmake                                           	\
    -DTrilinos_ENABLE_Amesos=ON                     	\
    -DTrilinos_ENABLE_AztecOO=ON                     	\
    -DTrilinos_ENABLE_Epetra=ON                      	\
    -DTrilinos_ENABLE_EpetraExt=ON                   	\
    -DTrilinos_ENABLE_Ifpack=ON                      	\
    -DTrilinos_ENABLE_MueLu=ON                       	\
    -DTrilinos_ENABLE_ML=ON                          	\
    -DTrilinos_ENABLE_ROL=ON                         	\
    -DTrilinos_ENABLE_Sacado=ON                      	\
    -DTrilinos_ENABLE_SEACAS=ON                      	\
    -DTrilinos_ENABLE_Teuchos=ON                     	\
    -DTrilinos_ENABLE_Tpetra=ON                      	\
    -DTrilinos_ENABLE_Zoltan=ON                      	\
    -DTrilinos_ENABLE_COMPLEX_DOUBLE=ON              	\
    -DTrilinos_ENABLE_COMPLEX_FLOAT=ON               	\
    -DTrilinos_ENABLE_OpenMP=ON                      	\
    -DTrilinos_VERBOSE_CONFIGURE=OFF                 	\
    -DTrilinos_ENABLE_CXX11=ON							\
    -DTrilinos_ENABLE_FLOAT=ON 							\
    -DTrilinos_ENABLE_COMPLEX=OFF				\
    -DTpetra_INST_INT_INT=ON					\
    -DTpetra_INST_INT_LONG_LONG=OFF				\
    -DTPL_ENABLE_MPI=ON                              	\
    -DTPL_ENABLE_Boost:BOOL=ON                       	\
    -DTPL_ENABLE_Matio=OFF 			      			 	\
    -DTPL_ENABLE_BLAS=ON 								\
    -DTPL_ENABLE_LAPACK=ON								\
    -DTPL_ENABLE_MKL=ON									\
    	-DMKL_LIBRARY_DIRS:FILEPATH="/opt/intel/oneapi/mkl/2022.0.1/lib/intel64" 	\
    	-DMKL_INCLUDE_DIRS:FILEPATH="/opt/intel/oneapi/mkl/2022.0.1/include" 		\
    -DTPL_ENABLE_HDF5:BOOL=ON     	                   								\
        -DHDF5_INCLUDE_DIRS:PATH=/home/tfblab/Trilinos/petsc-3.15.5/x86_64/include 	\
        -DHDF5_LIBRARY_DIRS:PATH=/home/tfblab/Trilinos/petsc-3.15.5/x86_64/lib     	\
    -DTPL_ENABLE_MUMPS:BOOL=ON                       								\
        -DMUMPS_INCLUDE_DIRS:PATH=/home/tfblab/Trilinos/petsc-3.15.5/x86_64/include 		\
        -DMUMPS_LIBRARY_DIRS:PATH=/home/tfblab/Trilinos/petsc-3.15.5/x86_64/lib    			\
    -DTPL_ENABLE_HYPRE:BOOL=ON                       								\
        -DHYPRE_INCLUDE_DIRS:PATH=/home/tfblab/Trilinos/petsc-3.15.5/x86_64/include 		\
        -DHYPRE_LIBRARY_DIRS:PATH=/home/tfblab/Trilinos/petsc-3.15.5/x86_64/lib    			\
    -DBUILD_SHARED_LIBS=ON                           	\
    -DCMAKE_VERBOSE_MAKEFILE=OFF                     	\
    -DCMAKE_BUILD_TYPE=RELEASE                       	\
    -DCMAKE_INSTALL_PREFIX:PATH=/home/tfblab/Trilinos/trilinos_13_4_0 				\
    -DCMAKE_C_COMPILER="/opt/intel/oneapi/mpi/2021.5.0/bin/mpiicc"					\
    -DCMAKE_CXX_COMPILER="/opt/intel/oneapi/mpi/2021.5.0/bin/mpiicpc"				\
    -DCMAKE_Fortran_COMPILER="/opt/intel/oneapi/mpi/2021.5.0/bin/mpiifort"			\
    -DMPI_BASE_DIR=/opt/intel/oneapi/mpi/2021.5.0/ 									\
    -DMPI_EXEC=/opt/intel/oneapi/mpi/2021.5.0/bin/mpiexec 							\
 	-DMPI_C_COMPILER="/opt/intel/oneapi/mpi/2021.5.0/bin/mpiicc"					\
    -DMPI_CXX_COMPILER="/opt/intel/oneapi/mpi/2021.5.0/bin/mpiicpc"					\
    -DMPI_Fortran_COMPILER="/opt/intel/oneapi/mpi/2021.5.0/bin/mpiifort"			\
    -DMPI_EXEC_MAX_NUMPROCS=16							\
    ..`

and errors are:
`/home/tfblab/Trilinos/Trilinos-trilinos-release-13-4-0/packages/amesos2/src/Amesos2_MUMPS_def.hpp(167): error: class "Amesos2::FunctionMap<Amesos2::MUMPS, Amesos2::MUMPST::mumps_double_complex>" has no member "mumps_c"
            function_map::mumps_c(&(mumps_par));
                          ^
          detected during instantiation of "Amesos2::MUMPS<Matrix, Vector>::~MUMPS() [with Matrix=Tpetra::CrsMatrix<std_complex0double0, int, int, Kokkos_Compat_KokkosOpenMPWrapperNode>, Vector=Tpetra::MultiVector<std_complex0double0, int, int, Kokkos_Compat_KokkosOpenMPWrapperNode>]" at line 65 of "/home/tfblab/Trilinos/Trilinos-trilinos-release-13-4-0/packages/amesos2/src/Amesos2_MUMPS.cpp"

compilation aborted for /home/tfblab/Trilinos/Trilinos-trilinos-release-13-4-0/packages/amesos2/src/Amesos2_MUMPS.cpp (code 2)
make[2]: *** [packages/amesos2/src/CMakeFiles/amesos2.dir/build.make:342: packages/amesos2/src/CMakeFiles/amesos2.dir/Amesos2_MUMPS.cpp.o] Error 2
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:9194: packages/amesos2/src/CMakeFiles/amesos2.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make: *** [Makefile:166: all] Error 2
`
my cmake cache, log, and errors are followed with url 
[https://drive.google.com/file/d/1McimSoLNSRQOPZXDWH2oK9XZJKpyzePU/view?usp=sharing](url)
[https://drive.google.com/file/d/1WE4A2t8684FnHnEBp9hdB5gWnHUqgTJ_/view?usp=sharing](url)
[https://drive.google.com/file/d/1kir95j4xNMF_QogyD_YYK4fScKYx8Uln/view?usp=sharing](url)

could anyone help me out?
Best,
Chen

**Comment by cgcgcg** [comment]
@trilinos/amesos2

**Comment by saitoasukakawaii** [comment]
I use gnu compiler gcc/g++/gfortran and mpich compile trilinos with mumps get the same errors, I think there are some mistakes when I compiler the mumps.

**Comment by iyamazaki** [comment]
I'll close this issue since [PR#11833](https://github.com/trilinos/Trilinos/pull/11833) should have fixed it. Please let us know if you still have any issues. Thank you.
