### ISSUE TITLE
Tpetra: did certain routines get renamed / change syntax?

### ISSUE THREAD

**Issue by ikalash** [trilinos/Trilinos#10687]
I was on foreign travel for 3.5 weeks and it seems missed some changes to Tpetra.  Did the syntax for getLocalRowCopy change and getNodeNumElements() go away?  Some of my code that gets tested nightly is not compiling due to errors having to do with these routines.

https://sems-cdash-son.sandia.gov/cdash/viewBuildError.php?buildid=35579

**Comment by ikalash** [comment]
@trilinos/tpetra

**Comment by brian-kelley** [comment]
Oh, and the other one you might run into is the versions of ``Tpetra::MultiVector::getLocalView...`` that didn't take access specifiers (``Tpetra::Access::ReadOnly``, ``ReadWrite``, ``OverwriteAll``) were removed. That goes for the templated ``getLocalView<DeviceType>``, and the non-templated ``getLocalViewHost``/``getLocalViewDevice``.

**Comment by ikalash** [comment]
Thank you, @brian-kelley , I was able to figure out how to fix it.
