### ISSUE TITLE
Framework/ATDM environments on Stria: CMake picks up system mpiexec

### ISSUE THREAD

**Issue by brian-kelley** [trilinos/Trilinos#10684]
## Bug Report
@trilinos/framework 

### Description
After loading the ``stria-arm-release`` environment on Stria, ``$ATDM_CONFIG_MPI_EXEC`` is set to "mpirun" as expected. This should be fine, since ``which mpirun`` points to ``/opt/atse/mpi/openmpi4-arm/4.0.5/bin/mpirun`` which is from the correct MPI module. But when configuring Trilinos, the CMake variable ``MPI_EXEC`` ends up pointing to the system mpiexec, ``/usr/bin/mpiexec`` for some reason (as if it's ignoring PATH). The generated CTestTestfile scripts also hardcode ``/usr/bin/mpiexec`` so tests that use >1 MPI ranks don't work. This issue during config happens whether I configure on the login or compute nodes.

This is due to some system configuration change between June 7 and June 9, and not due to a Trilinos PR from that time range. The Trilinos SHA of the last working Stria performance testing build was 9b0ec55b0ef4, but building that version now exhibits this issue. A workaround is to add ``-DMPI_EXEC=$MPI_ROOT/bin/mpiexec``. Maybe this is an acceptable permanent fix?

### Steps to Reproduce
1. Check out Trilinos develop (exact SHA doesn't seem to matter)
2. Load env: ``source $TRILINOS_SRC/cmake/std/atdm/load-env.sh stria-arm-release``
3. Minimal configure using the ATDM environment:
```
rm -rf CMakeFiles
rm -f CMakeCache.txt

cmake \
-DTrilinos_ENABLE_Tpetra=ON \
-DTpetra_INST_SERIAL=ON \
-DTrilinos_ENABLE_EXPLICIT_INSTANTIATION=ON \
-DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=$TRILINOS_SRC/cmake/std/atdm/ATDMDevEnv.cmake \
-DTPL_ENABLE_MPI=ON \
-DKokkos_ENABLE_SERIAL=ON \
$TRILINOS_SRC
```

Then look at the value of ``MPI_EXEC`` in CMakeCache.txt - the issue is that it's ``/usr/bin/mpiexec`` instead of ``/opt/atse/mpi/openmpi4-arm/4.0.5/bin/mpiexec``.

**Comment by bartlettroscoe** [comment]
@brian-kelley, can you put in a PR to fix this?  I don't now that anyone is supporting these builds at this point.

**Comment by brian-kelley** [comment]
@bartlettroscoe Yep, I just put the workaround I used in #10768 .
