### ISSUE TITLE
Intrepid2: Cuda non-UVM test failure in multiple tests

### ISSUE THREAD

**Issue by ndellingwood** [trilinos/Trilinos#10714]
## Bug Report
@trilinos/intrepid2 

### Description
The following unit tests are failing Cuda builds with UVM disabled as the default device memory space:
```
  319 - Intrepid2_unit-test_Projection_test_convergence_QUAD_Serial_DOUBLE_MPI_1 (Failed)
  321 - Intrepid2_unit-test_Projection_test_convergence_TRI_Serial_DOUBLE_MPI_1 (Failed)
  323 - Intrepid2_unit-test_Projection_test_DeRham_commutativity_QUAD_Serial_DOUBLE_MPI_1 (Failed)
  325 - Intrepid2_unit-test_Projection_test_DeRham_commutativity_TRI_Serial_DOUBLE_MPI_1 (Failed)
  327 - Intrepid2_unit-test_Projection_test_interpolation_projection_QUAD_Serial_DOUBLE_MPI_1 (Failed)
  329 - Intrepid2_unit-test_Projection_test_interpolation_projection_TRI_Serial_DOUBLE_MPI_1 (Failed)
  331 - Intrepid2_unit-test_Projection_test_convergence_QUAD_CUDA_DOUBLE_MPI_1 (Failed)
  333 - Intrepid2_unit-test_Projection_test_convergence_TRI_CUDA_DOUBLE_MPI_1 (Failed)
  335 - Intrepid2_unit-test_Projection_test_DeRham_commutativity_QUAD_CUDA_DOUBLE_MPI_1 (Failed)
  337 - Intrepid2_unit-test_Projection_test_DeRham_commutativity_TRI_CUDA_DOUBLE_MPI_1 (Failed)
  339 - Intrepid2_unit-test_Projection_test_interpolation_projection_QUAD_CUDA_DOUBLE_MPI_1 (Failed)
  341 - Intrepid2_unit-test_Projection_test_interpolation_projection_TRI_CUDA_DOUBLE_MPI_1 (Failed)
```

A common output error message is
```
Kokkos::View ERROR: attempt to access inaccessible memory space
```

Though there may be other types of error as well (I didn't go through all the test output carefully)

### Steps to Reproduce
1. SHA1:  a0654795305b5d5fdbbd18d7123452cd4316f24e
2. Configure script:  (weaver testbed, rhel7W queue)
```bash
# Load modules
module purge
export ATDM_CONFIG_REGISTER_CUSTOM_CONFIG_DIR=${TRILINOS_DIR}/cmake/std/atdm/contributed/weaver
source ${TRILINOS_DIR}/cmake/std/atdm/load-env.sh weaver-cuda-10.1-opt
export ATDM_CONFIG_USE_NINJA=OFF
unset CUDA_LAUNCH_BLOCKING

# Configure
cmake \
 -G"Unix Makefiles" \
 -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
 -DCMAKE_INSTALL_PREFIX="${PWD}/install" \
 -DCMAKE_CXX_STANDARD="14" \
 -DCMAKE_CXX_FLAGS="-pedantic -Wall" \
 -DTrilinos_ENABLE_TESTS=OFF \
 -DTrilinos_ENABLE_ALL_PACKAGES=OFF \
 -DKokkos_ENABLE_CUDA_UVM=OFF \
 -DTrilinos_ENABLE_Intrepid2=ON \
 -DIntrepid2_ENABLE_TESTS=ON \
 -DTrilinos_ENABLE_Sacado=ON \
$TRILINOS_DIR
```

**Comment by kyungjoo-kim** [comment]
@mperego

**Comment by mperego** [comment]
I'll look into that. Wonder why this is not captured by the PR builds. Maybe there are still places in Intrepid2 where we rely on the default Kokkos device?

**Comment by rppawlo** [comment]
Due to limited cuda resources for testing, the PR testing no longer does a UVM=OFF build. We currently only test with UVM=ON. We hope to get a UVM=OFF PR build back up soon...

**Comment by mperego** [comment]
In Intrepid2 we test for Cuda when available, we do not rely on Kokkos default device space. So even when UVM=ON, we have tests for Cuda with UVM off.

**Comment by CamelliaDPG** [comment]
@mperego, not sure if this is related, but I did observe recently when following the instructions for [reproducing PR build errors](https://github.com/trilinos/Trilinos/wiki/Reproducing-PR-Testing-Errors) on vortex that after running the line

```
cmake -C packageEnables.cmake /path/to/Trilinos
```

I had to manually do

```
cmake -D Intrepid2_ENABLE_TESTS:BOOL=ON /path/to/Trilinos
```

i.e., for whatever reason `Intrepid2_ENABLE_TESTS` was not properly set.

**Comment by kyungjoo-kim** [comment]
@mperego there are tests failed for serial execution space. it means that your test or the projection tools use default memory space somewhere. with uvm=on, the problem does not reveal as it is still accessible but with uvm=off, your access to the default memory space pops up as an error.

**Comment by mperego** [comment]
> @mperego there are tests failed for serial execution space. it means that your test or the projection tools use default memory space somewhere. with uvm=on, the problem does not reveal as it is still accessible but with uvm=off, your access to the default memory space pops up as an error.

yes, that was the issue. I added a function to return the determinant of the jacobian of the orientation and I was creating a view without specifying the device type.
