### ISSUE TITLE
How to use externally-installed packages instead of rebuilding them?

### ISSUE THREAD

**Issue by yurivict** [trilinos/Trilinos#10729]
Trilinos installs at least 2 packages, Kokkos and mpich, that conflict with other packages that can be installed through the package manager.

Is there a way to specify that the build should use exyernal packages?

There is a docs [section](https://docs.trilinos.org/files/TrilinosBuildReference.html#configuring-with-kokkos-and-advanced-back-ends) about Kokkos but it doesn't explain how to use external Kokkos.

Version: 13-4-0
OS: FreeBSD 13.1

**Comment by csiefer2** [comment]
Trilinos does not build mpich.

You cannot currently use Trilinos with an externally installed Kokkos.

**Comment by yurivict** [comment]
> Trilinos does not build mpich.

The actual problem is that Trilinos installs files that conflict with mpich:
```
include/mpi.h
include/mpi_config.h
include/mpi_implementation.h
include/mpi_profile.h
include/mpi_prototypes.h
```

**Comment by yurivict** [comment]
> You cannot currently use Trilinos with an externally installed Kokkos.

This makes Trilinos to conflict with external Kokkos package.

**Comment by csiefer2** [comment]
> > You cannot currently use Trilinos with an externally installed Kokkos.
> 
> This makes Trilinos to conflict with external Kokkos package.

Correct.  We don't support thay at present.

**Comment by csiefer2** [comment]
> > Trilinos does not build mpich.
> 
> The actual problem is that Trilinos installs files that conflict with mpich:
> 
> ```
> include/mpi.h
> include/mpi_config.h
> include/mpi_implementation.h
> include/mpi_profile.h
> include/mpi_prototypes.h
> ```

That's completely intentional --- if you're building Zoltan's serial MPI (siMPI) it installs those headers. If you're not buiding siMPI, doesn't.

The fast wat to fix this is to build Trilinos against MPI and it should disable siMPI.  If you really want serial Trilinos, then turn off Zoltan.
