### ISSUE TITLE
Residual Passed into NOX with LineSearchBased Solver and Newton Method

### ISSUE THREAD

**Issue by guoluanjing** [trilinos/Trilinos#1072]
Hello there,

I've got a quick question about passing the residual vector when using Newton method in NOX.

Eventually we are solving \[ Jd = -F \] , so do I pass F or -F to NOX through the computeF function through NOX::Epetra::Interface::Required?

Thanks,
Luanjing

**Comment by rppawlo** [comment]
pass in F, not -F.

A simple example can be found in
Trilinos/packages/nox/test/epetra/Thyra/ModelEvaluator2DSim_def.hpp

**Comment by guoluanjing** [comment]
Got it. Thanks, @rppawlo !
