### ISSUE TITLE
Serring TPL_ENABLE_UMFPACK=ON fails because it looks for amd.h header

### ISSUE THREAD

**Issue by yurivict** [trilinos/Trilinos#10731]
I enabled these extra features: ```EpetraExt_BUILD_BTF EpetraExt_BUILD_EXPERIMENTAL EpetraExt_BUILD_GRAPH_REORDERINGS Teuchos_ENABLE_COMPLEX```.

cmake said that for the ```UMFPACK``` feature is needed for this.

But setting ```TPL_ENABLE_UMFPACK=ON``` causes this error:
```
-- Searching for a header file in the set "umfpack.h":
--   Searching for header 'umfpack.h' ...
-- ERROR: Could not find a header file in the set "umfpack.h"
-- Searching for a header file in the set "amd.h":
--   Searching for header 'amd.h' ...
-- ERROR: Could not find a header file in the set "amd.h"
-- ERROR: Could not find the include directories for TPL 'UMFPACK'!
```

```UMFPACK``` is installed by the package ```suitesparse-umfpack-5.7.9```.
It doesn't install the ```amd.h``` header.

What is wrong?

**Comment by cgcgcg** [comment]
https://xyce.sandia.gov/documentation-tutorials/building-guide/#instTrilinos says you need
```
-DTPL_ENABLE_AMD=ON \
-DAMD_LIBRARY_DIRS="/usr/lib" \
-DTPL_AMD_INCLUDE_DIRS="/usr/include/suitesparse" \
```

**Comment by cgcgcg** [comment]
AMD is part of suitesparse. Maybe it's not enabled in the installed suitesparse?

**Comment by yurivict** [comment]
Ah, yes. ```suitesparse-amd``` is installed and it does provide ```amd.h```

I figured this out. Xyce instructions are missing this: ```-DUMFPACK_INCLUDE_DIRS=${LOCALBASE}/include/suitesparse```

With this it configures successfully now.

Thank you for your help!
