### ISSUE TITLE
how to solve of systems of nonlinear equations with Trilinos

### ISSUE THREAD

**Issue by ztdepztdep** [trilinos/Trilinos#10734]
I have a system of nonlinear equations with 5 unknowns. I want to know which package might i use to solve it.

**Comment by csiefer2** [comment]
NOX would be a good option

**Comment by ztdepztdep** [comment]
> 

Does it have some tutorials? I didn't find it in the trilinos userguides.

**Comment by csiefer2** [comment]
The examples directory has some examples

https://github.com/trilinos/Trilinos/tree/master/packages/nox/examples.

The LAPACK backend might be what you want if your systems are really that small

**Comment by ztdepztdep** [comment]
> 

thanks, i run it sucessfully. But how to get the solution into my own vectors. I only found the print functions in the examples file. 

`    NOX::LAPACK::Group solnGrp =
      dynamic_cast<const NOX::LAPACK::Group&>(solver->getSolutionGroup());

    // Print the answer
    if (utils.isPrintType(NOX::Utils::Parameters)) {
      std::cout << "\n" << "-- Final Solution From Solver --" << "\n";
      std::cout << "|| F(x*) || = " << utils.sciformat(solnGrp.getNormF()) << std::endl;
      solnGrp.print();
    }`

**Comment by jhux2** [comment]
closing as answered

**Comment by ztdepztdep** [comment]
> From the solver, you can call solver->getSolutionGroup().getX(); This returns the NOX::Abstract::Vector. You will have to dynamic cast this to the NOX::Lapack::Vector. You can then access values via the parenthesis operator:
> 
> ```
>       //! Return the i-th element                                                                                                                                                                                                                               
>       double& operator() (int i);
> 
>       //! Return the i-th element (const version)                                                                                                                                                                                                               
>       const double& operator() (int i) const;
> ```

what should i do if the jacobian cann't be provided.

**Comment by rppawlo** [comment]
If a Jacobian can't be provided, you have a few options: (1) use the sacado automatic differentiation package to create one, (2) use the nox Broyden solver, (3) Use the nox MatrixFreeJacobianOperator object as the operator.

**Comment by jhux2** [comment]
@ztdepztdep Please reopen this issue if you still have questions.
