### ISSUE TITLE
Wrong recommendation in the documentation: -D Trilinos_INSTALL_INCLUDE_DIR="/usr/Trilinos_include" 

### ISSUE THREAD

**Issue by yurivict** [trilinos/Trilinos#10744]
The documentation page [here](https://docs.trilinos.org/files/TrilinosBuildReference.html#installing) recommends ```-D Trilinos_INSTALL_INCLUDE_DIR="/usr/Trilinos_include"``` which causes headers installed into ```/usr/usr/Trilinos_include```. This is probably not what is desired.

It should read: ```-D Trilinos_INSTALL_INCLUDE_DIR="Trilinos_include"``` or ```-D Trilinos_INSTALL_INCLUDE_DIR="include/trilinos"```.

**Comment by csiefer2** [comment]
See my response to #10745

**Comment by jhux2** [comment]
@bartlettroscoe Is the Trilinos Build Reference under version control somewhere?

**Comment by bartlettroscoe** [comment]
> @bartlettroscoe Is the Trilinos Build Reference under version control somewhere?

@jhux2, yet it is.  See:

* https://tribits.org/doc/TribitsUsersGuide.html#project-specific-build-reference

**Comment by bartlettroscoe** [comment]
> The documentation page [here](https://docs.trilinos.org/files/TrilinosBuildReference.html#installing) recommends `-D Trilinos_INSTALL_INCLUDE_DIR="/usr/Trilinos_include"` which causes headers installed into `/usr/usr/Trilinos_include`. This is probably not what is desired.

@yurivict, no, that is the documented and tested behavior.  If you give an absolute path, it should comply.

> It should read: `-D Trilinos_INSTALL_INCLUDE_DIR="Trilinos_include"` or `-D Trilinos_INSTALL_INCLUDE_DIR="include/trilinos"`

If you give a relative path, it will be under `${CMAKE_INSTALL_PREFIX}`.

That documentation read:

> If these paths are relative (i.e. don't start with "/" and use type STRING) then they are relative to `${CMAKE_INSTALL_PREFIX}`. Otherwise the paths can be absolute (use type PATH) and don't have to be under `${CMAKE_INSTALL_PREFIX}`.

This gives the user complete control where things are installed.

Does that make sense?
