### ISSUE TITLE
Stokhos: runtime errors in TpetraCrsMatrixMPVectorUnitTest in Cuda without UVM

### ISSUE THREAD

**Issue by maartenarnst** [trilinos/Trilinos#10740]
## Bug Report
@trilinos/stokhos
@etphipp

### Description
After PR #10710 that solved issues relevant to the `TpetraCrsMatrixMPVectorUnitTest` test described in issues #10703 and #10696, @romintomasetti and I are compiling Trilinos with Stokhos enabled in a Cuda build without UVM.  We are seeing new runtime errors in the `TpetraCrsMatrixMPVectorUnitTest` test.

On the one hand, we are seeing again Tpetra sync errors.  We think we tracked down these errors to lines 981--988 in `TpetraCrsMatrixMPVectorUnitTest.hpp` where the code appears to successively create a device view and then a host view of the same vector in the same scope (e.g. `y2`).   

On the other hand, we are seeing runtime errors in the Belos tests that are part of `TpetraCrsMatrixMPVectorUnitTest`.  The error messages say that a deep_copy mechanism can't be found.  We think we tracked down these errors to lines 375, 502 and 508 in `packages/stokhos/src/sacado/kokkos/vector/belos/Belos_TpetraAdapter_MP_Vector.hpp`.  On these lines, the codes wants to do deep copies between host and device views.  What appears to be special about these cases is that the host views are built around data coming from Teuchos SerialDenseMatrices.  As a result, these host views appear to have a padding.  And it seems the deep_copy doesn't know how to handle this particular padding case.  We see these errors in our Cuda build without UVM, but we are not seeing them in a Cuda build with UVM.

We have made a patch for both issues, which I will upload as a PR (#10741):
- to solve the sync errors, we put scopes in the code around lines 981--988 in `TpetraCrsMatrixMPVectorUnitTest.hpp`.  And we also went through the entire file to update all lines of code were local views of vectors are created. 
- to solve the runtime errors for the missing deep_copy mechanism, we wrote a small macro.  If in Cuda without UVM, this macro replaces the problematic `deep_copy` call with a function that first creates an additional compatible view by using create_mirror; this mirror view is filled by looping over the elements; and finally the deep copy is done.  

It is quite possible that a better fix exists for the missing deep_copy mechanism issue.  But this may require deeper understanding of why a `deep_copy` mechanism is missing and how such a mechanism could be added.

**Comment by etphipp** [comment]
What is the exact error you are seeing about the missing deep_copy?  Does any of this look similar to the errors posted here:  https://github.com/kokkos/kokkos/issues/5189#issuecomment-1180762625

**Comment by maartenarnst** [comment]
Hi Eric,

The errors look like this:

```
13. Tpetra_CrsMatrix_MP_SFS_default_local_ordinal_type_default_global_ordinal_type_CudaWrapperNode_BelosGMRES_ICGS_UnitTest ...

*******************************************************
***** Belos Iterative Solver:  Pseudo Block Gmres
***** Maximum Iterations: 100
***** Block Size: 1
***** Residual Test:
*****   Test 1 : Belos::StatusTestImpResNorm<>: (2-Norm Res Vec) / (2-Norm Prec Res0), tol = 1e-09
*******************************************************
Iter   0, [ 1] :    1.000000e+00
Iter   1, [ 1] :    2.040834e-01

p=0: *** Caught standard std::exception of type 'std::runtime_error' :

Error: Kokkos::deep_copy with no available copy mechanism:  to
NOTE: Unit test failed on all processes!
```

The errors in this PR don't seem similar to the errors in kokkos/kokkos#5189.  

But we did find problems with `min` and `max` functions on our side too.  I had the impression that in some of our builds, the compiler is preferring the templated `std::min` and `std::max` functions over the Stokhos overloads.  And so it seemed that it is using the result based on the evaluation of the first sample, causing errors.

**Comment by etphipp** [comment]
I believe this is resolved now so closing. If you still run into trouble, please re-open.
