### ISSUE TITLE
Amesos2:  Amesos2_ShyLUBasker fails to build

### ISSUE THREAD

**Issue by dc-snl** [trilinos/Trilinos#10743]
## Bug Report
@trilinos/Amesos2

### Description
Setting `Amesos2_ENABLE_ShyLU_NodeBasker=ON` causes Trilinos to fail to build. It appears that `Amesos2_ShyLUBasker` is still using some deprecated code. Here are the first few errors:
```
/tmp/source/Trilinos/packages/amesos2/src/Amesos2_ShyLUBasker_def.hpp:789:15: error: 'get_ccs_helper' is not a member of 'Amesos2::Util'; did you mean 'get_1d_copy_helper'?
  789 |         Util::get_ccs_helper<
      |               ^~~~~~~~~~~~~~
      |               get_1d_copy_helper
```

```
/tmp/source/Trilinos/packages/amesos2/src/Amesos2_ShyLUBasker_def.hpp:204:40: error: 'const class Amesos2::MatrixAdapter<Tpetra::CrsMatrix<double, int, long long int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP> > >' has no member named 'returnRowPtr'
  204 |       auto sp_rowptr = this->matrixA_->returnRowPtr();
      |                        ~~~~~~~~~~~~~~~~^~~~~~~~~~~~
```

```
/tmp/source/Trilinos/packages/amesos2/src/Amesos2_ShyLUBasker_def.hpp:207:40: error: 'const class Amesos2::MatrixAdapter<Tpetra::CrsMatrix<double, int, long long int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP> > >' has no member named 'returnColInd'
  207 |       auto sp_colind = this->matrixA_->returnColInd();
      |                        ~~~~~~~~~~~~~~~~^~~~~~~~~~~~
```

```
/tmp/source/Trilinos/packages/amesos2/src/Amesos2_ShyLUBasker_def.hpp:211:40: error: 'const class Amesos2::MatrixAdapter<Tpetra::CrsMatrix<double, int, long long int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP> > >' has no member named 'returnValues'
  211 |       auto sp_values = this->matrixA_->returnValues();
      |                        ~~~~~~~~~~~~~~~~^~~~~~~~~~~~

```

### Steps to Reproduce
1. SHA1:  474b7c5a73e0472800f2437def221ac734a3ea0a
2. Clone, Configure, Build script:
```
git clone https://github.com/trilinos/Trilinos.git source/Trilinos
( cd source/Trilinos ; git checkout develop )
mkdir -p build/Trilinos
cd build/Trilinos

cmake \
    -D Trilinos_ENABLE_ALL_PACKAGES=OFF \
    -D Trilinos_ENABLE_ALL_OPTIONAL_PACKAGES=OFF \
    -D Trilinos_ENABLE_Amesos2=ON \
    -D Trilinos_ENABLE_ShyLU_NodeBasker=ON \
    -D Amesos2_ENABLE_ShyLU_NodeBasker=ON \
    -D Trilinos_ENABLE_OpenMP=ON \
    ../../source/Trilinos

cmake --build . -j40
```
3. Configure log: [configure.txt](https://github.com/trilinos/Trilinos/files/9087706/configure.txt)

4. Build log: [build.txt](https://github.com/trilinos/Trilinos/files/9087707/build.txt)

Let me know if you need any additional information.

Thanks,
--David

**Comment by ndellingwood** [comment]
I've started working on this, updates are needed following removal of Tpetra's deprecated code

**Comment by ndellingwood** [comment]
Adding folks also awaiting resolution of this issue, @hkthorn @iyamazaki

**Comment by iyamazaki** [comment]
Hi, @dc-snl. @ndellingwood's [PR](https://github.com/trilinos/Trilinos/pull/10793) was merged into develop. Please let us know if you are still seeing these errors with the current develop branch.

**Comment by dc-snl** [comment]
> Hi, @dc-snl. @ndellingwood's [PR](https://github.com/trilinos/Trilinos/pull/10793) was merged into develop. Please let us know if you are still seeing these errors with the current develop branch.

Everything looks good as of 35b4d4d7. Thanks all!

**Comment by kaiserls** [comment]
I think the same error occurs for Amesos2_ENABLE_MUMPS:BOOL=ON on the current state of the develop branch SHA: e5c726ed72f1c8589f6eeac9274419ca72bce08a. Should I maybe open a new issue for this?
