### ISSUE TITLE
Multibyte characters in MueLu header file

### ISSUE THREAD

**Issue by mwglass** [trilinos/Trilinos#1075]
I’m seeing some compiler warnings (Cray compiler) from MueLu_MLParameterListInterpreter_def.hpp, lines 260, 261, and 263 :

     An invalid multibyte character sequence appears in the source code.

In a regular editor it looks like just normal spaces in those lines but when I do a dump with ‘od –c’ I see the following (note the 302 and 240 entries). I think those should just be regular spaces.

`0032360       A   g   g   r   e   g   a   t   e       o   p   t   i   o`
`0032400   n       s   u   m   m   a   r   y     302 240   =   =   =   =`
`0032420   =   =   =   =   =   =   =   =   =   =   =   =   =   =   =   =`
`0032440   =   =   =   =   =   "       <   <       s   t   d   :   :   e`
`0032460   n   d   l   ;  \n                           o   s   s       <`
`0032500   <       "   m   i   n       N   o   d   e   s       p   e   r`
`0032520       a   g   g   r   e   g   a   t   e       :         302 240`
`0032540     302 240     302 240     302 240     302 240     302 240   ` 
`0032560 302 240   "       <   <       m   i   n   P   e   r   A   g   g`
`0032600       <   <       s   t   d   :   :   e   n   d   l   ;  \n    `
`0032620                       o   s   s       <   <       "   m   i   n`
`0032640       #       o   f       r   o   o   t       n   b   r   s    `
`0032660   a   l   r   e   a   d   y       a   g   g   r   e   g   a   t`
`0032700   e   d       :       "       <   <       m   a   x   N   b   r`
`0032720   A   l   r   e   a   d   y   S   e   l   e   c   t   e   d    `
`0032740   <   <       s   t   d   :   :   e   n   d   l   ;  \n        `
`0032760                   o   s   s       <   <       "   a   g   g   r`
`0033000   e   g   a   t   e       o   r   d   e   r   i   n   g       :`
`0033020     302 240     302 240     302 240     302 240     302 240    `
`0033040 302 240     302 240     302 240     302 240     302 240   n   a`
`0033060   t   u   r   a   l   "       <   <       s   t   d   :   :   e`
`0033100   n   d   l   ;  \n                           o   s   s       <`
`0033120   <       "   =   =   =   =   =   =   =   =   =   =   =   =   =`
`0033140   =   =   =   =   =   =   =   =   =   =   =   =   =   =   =   =`

**Comment by aprokop** [comment]
@tawiesn I am ready to push this.

**Comment by tawiesn** [comment]
Thx.

**Comment by mwglass** [comment]
Thanks for the quick response!!!

**Comment by aprokop** [comment]
I was a bit too fast. I have a patch that fixes this one file, but it also happens in others. Need to find all of them first.

**Comment by jhux2** [comment]
For the record, something like this should help detect the problem files:
```
#!/bin/sh
grep -n --color=always '[^ -~]\+' $(file `find . * -print` | grep  UTF-8 | cut -d':' -f1)
```

**Comment by aprokop** [comment]
For the future, here is a list of other files with UTF-8 chars in them
```
./intrepid/src/Shared/MiniTensor/Intrepid_MiniTensor_Tensor.h: C++ source, UTF-8 Unicode text
./intrepid/src/Shared/MiniTensor/Intrepid_MiniTensor_LinearAlgebra.h: C source, UTF-8 Unicode text
./intrepid/src/Shared/MiniTensor/Intrepid_MiniTensor_LinearAlgebra.t.h: UTF-8 Unicode text
./intrepid/src/Shared/MiniTensor/Intrepid_MiniTensor_Tensor.i.h: UTF-8 Unicode text
./trios/services/netcdf/src/NcGroupInfo.h: C++ source, UTF-8 Unicode text
./rol/example/wave-calibration/example_01.cpp: C++ source, UTF-8 Unicode text
./ifpack2/doc/UsersGuide/ifpack2guide.bib: BibTeX text file, UTF-8 Unicode text
./zoltan2/test/driver/driverinputs/README.txt: UTF-8 Unicode text, with very long lines
./teko/doc/Build-Preconditioner/build-precond.bib: BibTeX text file, UTF-8 Unicode text
./epetra/ReleaseNotes.txt: ISO-8859 text
./epetra/doc/html/jquery.js: UTF-8 Unicode text, with very long lines
./moertel/src/mortar/mrtr_overlap.cpp: C source, UTF-8 Unicode text
./komplex/src/Komplex_LinearProblem.h: C source, UTF-8 Unicode text
./stk/stk_balance/unit_tests/UnitTestLoadBalanceParentChild.cpp: C++ source, UTF-8 Unicode text
./stk/stk_classic/stk_mesh/doc/index.dox: UTF-8 Unicode text
./stk/stk_classic/stk_adapt/stk_adapt/Percept_MOAB_SimplexTemplateRefiner.cpp: C source, UTF-8 Unicode text
./stk/stk_classic/stk_percept/stk_percept/mesh/gen/SweepMesher.cpp: C source, UTF-8 Unicode text
./stk/stk_doc/stk_mesh/doc/index.dox: UTF-8 Unicode text
./PyTrilinos/doc/UsersGuide/biblio.bib: BibTeX text file, ISO-8859 text
./pamgen/test/test_files/run_test_script_70.res: Par archive data
./ifpack/src/Ifpack_HIPS.h: C++ source, UTF-8 Unicode text
./ifpack/doc/UsersGuide/biblio.bib: BibTeX text file, ISO-8859 text
./panzer/adapters-stk/tutorial/step01/README.txt: UTF-8 Unicode text
./minitensor/src/MiniTensor_Tensor.i.h: UTF-8 Unicode text
./minitensor/src/MiniTensor_Tensor.h: C++ source, UTF-8 Unicode text
./minitensor/src/MiniTensor_LinearAlgebra.t.h: UTF-8 Unicode text
./minitensor/src/MiniTensor_LinearAlgebra.h: C source, UTF-8 Unicode text
./thyra/cmake/.Dependencies.cmake.swp: Vim swap file, version 8.0
./tpetra/core/example/advanced/MultiPrec/IRTR_solvers.hpp: C source, UTF-8 Unicode text
```
I think most of them are not important, though (txt, bib, comments)
