### ISSUE TITLE
panzer testing under nvcc/cuda

### ISSUE THREAD

**Issue by bathmatt** [trilinos/Trilinos#1076]
is there any testing with panzer on cuda?  I find that almost every time I try to build there is an error and it would be good to find these sooner rather than later.   If there is, where is the dashboard?

**Comment by bathmatt** [comment]
Adding @eric-c-cyr @rppawlo to the conversation

**Comment by rppawlo** [comment]
Panzer is tested on CUDA at:

http://testing.sandia.gov/cdash/index.php?project=Trilinos&display=project

Look at the perseus and apollo machines. There are a few failing tests. I think that the BoostLib is not enabled so the STK and panzer/stk-adapters are getting disabled so it might not be full testing. I will dig into this next week.

**Comment by bathmatt** [comment]
Look at bug 1077 for the actual bug report.  This was more on the testing
side of things.

**Comment by bathmatt** [comment]
Also, panzer didn't compile at all, same error that I found.

http://testing.sandia.gov/cdash/viewBuildError.php?buildid=2751263 shows

/usr/bin/ar: CMakeFiles/panzer-disc-fe.dir/Panzer_BasisValues2.cpp.o:
No such file or directory

and compilation stopped.
