### ISSUE TITLE
Panzer not compiling under cuda

### ISSUE THREAD

**Issue by bathmatt** [trilinos/Trilinos#1077]
@eric-c-cyr @kyungjoo-kim 
It looks like some of the changes for the higher order basis stuff broke the cuda build.  I'm getting errors here

     ots::modifyBasisByOrientation(drv_basis_scalar,
                                    drv_basis_scalar_tmp,
                                    drv_orts,
                                    intrepid_basis);
The error mentions an array size issue.

Here is the compile traceback
            instantiation of "Intrepid2::OrientationTools<ExecSpaceType>::CoeffMatrixDataViewType Intrepid2::OrientationTools<ExecSpaceType>::createCoeffMatrix(BasisPtrType) [with ExecSpaceType=PHX::Device, BasisPtrType=Teuchos::RCP<Intrepid2::Basis<Kokkos::Cuda::execution_space, double, double>>]"
/home/mbetten/Trilinos/Trilinos/packages/intrepid2/refactor/src/Orientation/Intrepid2_OrientationToolsDefModifyBasis.hpp(165): here
            instantiation of "void Intrepid2::OrientationTools<ExecSpaceType>::modifyBasisByOrientation(Kokkos::DynRankView<outputValueType, outputProperties...>, Kokkos::DynRankView<inputValueType, inputProperties...>, Kokkos::DynRankView<ortValueType, ortProperties...>, BasisPtrType) [with ExecSpaceType=PHX::Device, outputValueType=double, outputProperties=<Kokkos::Cuda::execution_space>, inputValueType=double, inputProperties=<Kokkos::Cuda::execution_space>, ortValueType=Intrepid2::Orientation, ortProperties=<PHX::Device>, BasisPtrType=Teuchos::RCP<Intrepid2::Basis<Kokkos::Cuda::execution_space, double, double>>]"
/home/mbetten/Trilinos/Trilinos/packages/panzer/disc-fe/src/Panzer_BasisValues2.cpp(581): here
            instantiation of "void panzer::BasisValues2<Scalar>::applyOrientations(const std::vector<Intrepid2::Orientation, std::allocator<Intrepid2::Orientation>> &) [with Scalar=double]"
/home/mbetten/Trilinos/Trilinos/packages/panzer/disc-fe/src/Panzer_BasisValues2.cpp(949): here

/home/mbetten/Trilinos/Trilinos/packages/kokkos/containers/src/Kokkos_DynRankView.hpp(857): error: static assertion failed with "Incompatible DynRankView copy construction"
          detected during:
            instantiation of "Kokkos::Experimental::DynRankView<DataType, Properties...>::DynRankView(const Kokkos::Experimental::DynRankView<RT, RP...> &) [with DataType=double, Properties=<Kokkos::LayoutStride, Kokkos::Cuda::execution_space>, RT=double, RP=<Kokkos::DefaultHostExecutionSpace>]"

**Comment by kyungjoo-kim** [comment]
I see that this is becuase of incompatible layout between host space and device space. When I compute coefficient matrices to modify basis with orientations, I simply calls lapack routine and use host view. Somewhere there is mismatch. 

How urgent is this ? For now, could you compile the code by removing __KK__ definition placed in the panzer disc-fe directory. The old code is protected by ifdef with __KK__ and should be working by removing the definition.

**Comment by bathmatt** [comment]
With a work around I can start my testing work.  What kind of timeframe are
we talking, days/weeks/months?

**Comment by bathmatt** [comment]
ebe8685a7c6c1744fb892afa792b4f7d770a12a3 should have ifdeffed out the KK decl if we are using CUDA.  revert to test.

**Comment by kyungjoo-kim** [comment]
Hi Matt


I changed the code. The problem was the mimatch of space type between basis input (basis has generic interface and it requires predefined view interface - no function template interface avail) and actual input. 

I checked the code compile with cuda but I still have pnetcdf linking issue on hansen and I was not able to check linking example. I am quite sure that the code is working again. Could you verify the tests  on your machine. BTW, why compiling is so slow on cuda ? It seems even slower than before.

**Comment by bathmatt** [comment]
I'll check it in a bit, trilinos is wacked right now because of
https://github.com/trilinos/Trilinos/issues/1099 and I can't update and
build anywhere.

**Comment by kyungjoo-kim** [comment]
From nightly tests, this issue is resolved by now. Can we close this ?

**Comment by bathmatt** [comment]
Sure, it looks like it is resolved,
