### ISSUE TITLE
how to copy the layout of Sacado Fad View?

### ISSUE THREAD

**Issue by ibaned** [trilinos/Trilinos#1078]
I'm trying to create a really simple function for Albany to create an "uninit deep copy" of a view, that is a view with the same layout whose allocation is new and distinct from the input view, but not necessarily copying the contents. I tried to base it off of Kokkos's functions for creating mirrors:

```
template< class T , class ... P >
inline
typename Kokkos::DynRankView<T,P...>::non_const_type
create_copy( const std::string& name,
    const Kokkos::DynRankView<T,P...> & src )
{
  using dst_type = typename Kokkos::DynRankView<T,P...>::non_const_type;
  auto layout = Kokkos::Experimental::Impl::reconstructLayout(src.layout(), src.rank());
  return dst_type( name , layout );
}
```

This worked okay for native Kokkos Views, but it fails for the specialized Views of Sacado Fad types. The Sacado `DynRankDimTraits` treat the Fad dimension in a way that `reconstructLayout` doesn't expect. Also, If I print out the 8th dimension of the layout objects, they are all zero because the Sacado `ViewMapping` hides the fad size in a separate variable.

My question is: how am I supposed to write this simple function such that it works with Sacado's View specializations ?

@trilinos/sacado 
(unsure how to mention Kokkos team from Trilinos repo, going with @hcedwar )

**Comment by mhoemmen** [comment]
@trilinos/sacado @etphipp

**Comment by ibaned** [comment]
Well, I've come up with the following, which seems to work but does need to specialize... I wish the Fad size hadn't been hidden in a variable specific to the specialized ViewMapping...

```cpp
template< class T , class ... P >
inline
typename std::enable_if<
  !Kokkos::is_dynrankview_fad<Kokkos::DynRankView<T,P...>>::value,
  typename Kokkos::DynRankView<T,P...>::non_const_type >::type
create_copy( const std::string& name,
    const Kokkos::DynRankView<T,P...> & src )
{
  using dst_type = typename Kokkos::DynRankView<T,P...>::non_const_type;
  auto layout = Kokkos::Experimental::Impl::reconstructLayout(src.layout(), src.rank());
  return dst_type( name , layout );
}

template< class T , class ... P >
inline
typename std::enable_if<
  Kokkos::is_dynrankview_fad<Kokkos::DynRankView<T,P...>>::value,
  typename Kokkos::DynRankView<T,P...>::non_const_type >::type
create_copy( const std::string& name,
    const Kokkos::DynRankView<T,P...> & src )
{
  using Src = Kokkos::DynRankView<T,P...>;
  using Dst = typename Kokkos::DynRankView<T,P...>::non_const_type;
  auto sl = src.layout();
  auto sm = src.implementation_map();
  auto fad_rank = src.rank();
  sl.dimension[fad_rank] = sm.dimension_scalar();
  auto real_rank = fad_rank + 1;
  auto ml = Kokkos::Experimental::Impl::reconstructLayout(sl, real_rank);
  auto dst = Dst( src.label(), ml );
  return dst;
}
```

I guess I'll close this because its working, but Fad specialization seems badly encapsulated... most operations require new specializations.

**Comment by etphipp** [comment]
Whenever you use things in the Impl namespace, specializations for Fad are likely to be necessary.  Exposing the the Fad rank and size through the regular View API causes countless problems.
