### ISSUE TITLE
Anasazi: code built against Trilinos with rbgen not finding rbgen

### ISSUE THREAD

**Issue by ikalash** [trilinos/Trilinos#10794]
@trilinos/anasazi 

I have a code that is nightly tested that depends on RBGen in Anasazi.  I have the following logic in my CMakeLists.txt for this code that checks whether Trilinos has been built with RBGen, and throws an error if it has not.  The logic is as follows:

```
IF (Anasazi_List_ID GREATER -1)
  MESSAGE("-- Looking for Anasazi: -- found! Continuing.")
  LIST(FIND Trilinos_LIBRARIES rbgen rbgen_List_ID)
  IF (rbgen_List_ID GREATER -1)
    MESSAGE("---- Looking for rbgen library: -- found!  Continuing.")
  ELSE()
    MESSAGE(FATAL_ERROR "---- Looking for rbgen library: -- not found! Rebuild Trilinos with Anasazi_ENABLE_RBGen turned ON.")
  ENDIF()
ELSE()
  MESSAGE(FATAL_ERROR "-- Looking for Anasazi: -- not found! Rebuild Trilinos with Anasazi package.")
ENDIF()
```
Starting this past week, the logic has begun failing (https://sems-cdash-son.sandia.gov/cdash/build/36698/configure) even though I have RBGen turned on in Trilinos and the RBGen files are being built.  Is there another way to check for RBGen presence in Trilinos now?  Is this related to recent changes having to do with the Trilinos build system?

@hkthorn

**Comment by GrahamBenHarper** [comment]
If I'm reading this right, I think it's related to #10614? The failures starting on July 19 seem to line up with the merge date.

**Comment by ikalash** [comment]
@GrahamBenHarper I suspect the same thing.  That PR has caused all sorts of issues for my numerous nightly builds, sigh...  Tagging @bartlettroscoe so he is in the loop.

**Comment by bartlettroscoe** [comment]
I talked with @ikalash about this today.  I will implement the setting of the variable `Anasazi_ENABLE_RBGen` automatically through [`tribits_add_option_and_define()`](https://tribitspub.github.io/TriBITS/users_guide/index.html#tribits-add-option-and-define) as described [above](https://github.com/trilinos/Trilinos/issues/10794#issuecomment-1194130713).

**Comment by ikalash** [comment]
Thanks @bartlettroscoe  - please let me know when the fix is ready.  I am happy to test it.

**Comment by bartlettroscoe** [comment]
@ikalash, I believe this was fixed a long time ago with support for `<Package>_ENABLE_<Feature>` vars being written to the `<Package>Config.cmake` files pulled in by `find_package(Trilinos)`.

**Comment by ikalash** [comment]
Yes, this can be closed,  sorry for not closing earlier.

**Comment by bartlettroscoe** [comment]
👍
