### ISSUE TITLE
Tpetra: document whether FECrsMatrix and FEMultiVector are in "owned" state upon construction

### ISSUE THREAD

**Issue by kubagalecki** [trilinos/Trilinos#10800]
## Documentation
@trilinos/\<tpetra\>

As per the discussion in #9638, constructing a `FECrsMatrix` with a static graph results in a matrix in "owned" and "closed" state. This is not explicitly mentioned in the documentation. It took me a bit of digging/testing to ascertain the state of the matrix upon construction. To save future users some time, I propose adding the following sentence to the relevant constructor of `FECrsMatrix`:

_The matrix is constructed in "owned" and "closed" state. You must first call `beginAssembly` or `beginModify` if you wish to change its entries (the difference between these two can be found elsewhere in the documentation)._

A similar remark goes for `FEMultiVector`. It is also not immediately obvious whether it is constructed in "Owned" or "OwnedPlusShared" state.

**Comment by jhux2** [comment]
@trilinos/tpetra @csiefer2

**Comment by csiefer2** [comment]
Does the above PR look OK for you, @kubagalecki ?

**Comment by kubagalecki** [comment]
Looks good, thanks for addressing this so quickly!
