### ISSUE TITLE
MPI + CUDA build

### ISSUE THREAD

**Issue by Adrian-Diaz** [trilinos/Trilinos#10843]
## Question
@trilinos/\<tpetra\>
Greetings, I was trying to compile Trilinos with CUDA and OpenMPI using the following

cmake -DCMAKE_BUILD_TYPE=RELEASE \
-DTrilinos_MUST_FIND_ALL_TPL_LIBS=TRUE \
-DTPL_ENABLE_MPI=ON \
-DMPI_CXX_COMPILER=${trilinosdir}/packages/kokkos/bin/nvcc_wrapper \
-DCMAKE_CXX_STANDARD:STRING=17 \
-DTrilinos_ENABLE_Kokkos=ON \
-DTPL_ENABLE_CUDA=ON \
-DKokkos_ENABLE_CUDA_UVM=OFF \
-DTrilinos_ENABLE_OpenMP=OFF \
-DTrilinos_ENABLE_Amesos2=ON \
-DTrilinos_ENABLE_Belos=ON \
-DTrilinos_ENABLE_MueLu=ON \
-DTrilinos_ENABLE_ROL=ON \
-DTrilinos_ENABLE_Ifpack2=ON \
-DTrilinos_ENABLE_Zoltan2=ON \
-DMueLu_ENABLE_TESTS=OFF \
-DTrilinos_ENABLE_ALL_PACKAGES=OFF -DTrilinos_ENABLE_ALL_OPTIONAL_PACKAGES=OFF -DTrilinos_ENABLE_TESTS=OFF \
-DCMAKE_INSTALL_PREFIX=. \
..

which gives me the following for the cmake configure:

-- USE_XSDK_DEFAULTS='FALSE'
-- BUILD_SHARED_LIBS='FALSE'
-- CMAKE_BUILD_TYPE='RELEASE'
-- MPI_USE_COMPILER_WRAPPERS='ON'
-- MPI_C_COMPILER='/projects/opt/centos8/x86_64/openmpi/3.1.6-gcc_9.3.0/bin/mpicc'
-- Setting CMAKE_C_COMPILER=${MPI_C_COMPILER}
-- CMAKE_C_COMPILER='/projects/opt/centos8/x86_64/openmpi/3.1.6-gcc_9.3.0/bin/mpicc'
-- MPI_CXX_COMPILER='/scratch/users/adiaz17/Fierro_GPU_test/Fierro/Trilinos/packages/kokkos/bin/nvcc_wrapper'
-- MPI_CXX_COMPILER='/scratch/users/adiaz17/Fierro_GPU_test/Fierro/Trilinos/packages/kokkos/bin/nvcc_wrapper'
-- Setting CMAKE_CXX_COMPILER=${MPI_CXX_COMPILER}
-- CMAKE_CXX_COMPILER='/scratch/users/adiaz17/Fierro_GPU_test/Fierro/Trilinos/packages/kokkos/bin/nvcc_wrapper'
-- MPI_Fortran_COMPILER='/projects/opt/centos8/x86_64/openmpi/3.1.6-gcc_9.3.0/bin/mpif90'
-- Setting CMAKE_Fortran_COMPILER=${MPI_Fortran_COMPILER}
-- CMAKE_Fortran_COMPILER='/projects/opt/centos8/x86_64/openmpi/3.1.6-gcc_9.3.0/bin/mpif90'
-- MPI_EXEC='/usr/bin/mpiexec'
-- The C compiler identification is GNU 9.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /projects/opt/centos8/x86_64/openmpi/3.1.6-gcc_9.3.0/bin/mpicc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- CMAKE_C_COMPILER_ID='GNU'
-- CMAKE_C_COMPILER_VERSION='9.3.0'
-- The CXX compiler identification is GNU 9.3.0

which, later on in the configure, ends up triggering:

CMake Error at packages/kokkos/cmake/kokkos_test_cxx_std.cmake:132 (MESSAGE):
  Invalid compiler for CUDA.  The compiler must be nvcc_wrapper or Clang or
  use kokkos_launch_compiler, but compiler ID was GNU
Call Stack (most recent call first):
  packages/kokkos/cmake/kokkos_tribits.cmake:239 (INCLUDE)
  packages/kokkos/CMakeLists.txt:198 (KOKKOS_SETUP_BUILD_ENVIRONMENT)

I also tried setting without DMPI_CXX_COMPILER by using an export before the script
 export OMPI_CXX=${trilinosdir}/packages/kokkos/bin/nvcc_wrapper

but that leads to the same error at the end and the configure finds my default mpicxx wrapper locations. Are there any other settings I need? Thanks for any help.

Sincerely,
Adrian Diaz

**Comment by jhux2** [comment]
@Adrian-Diaz Here's a snippet that I use on Summit at ORNL, hopefully it's helpful to you:
```
export OMPI_CXX="${trilinos_source_dir}/packages/kokkos/bin/nvcc_wrapper"

ARGS=(
    -D CMAKE_INSTALL_PREFIX:PATH="${trilinos_install_dir}"
    -D CMAKE_BUILD_TYPE:STRING=$BUILD_TYPE
    -D CMAKE_CXX_FLAGS:STRING="--remove-duplicate-link-files" \
    -D MPI_USE_COMPILER_WRAPPERS:BOOL=ON
    -D TPL_ENABLE_CUDA:BOOL=ON
    -D TPL_ENABLE_CUSPARSE:BOOL=ON
    -D Trilinos_ENABLE_TESTS:BOOL=OFF
    -D Trilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=OFF
    -D Trilinos_ENABLE_CXX11:BOOL=ON
    -D Trilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON
    -D Trilinos_ASSERT_MISSING_PACKAGES:BOOL=OFF
    -D Trilinos_ALLOW_NO_PACKAGES:BOOL=OFF
    -D Trilinos_ENABLE_OpenMP:BOOL=OFF
    -D Trilinos_ENABLE_Amesos:BOOL=OFF
    -D Trilinos_ENABLE_Amesos2:BOOL=ON
    -D   Amesos2_ENABLE_SuperLU:BOOL=OFF
    -D   Amesos2_ENABLE_KLU2:BOOL=ON
    -D Trilinos_ENABLE_AztecOO:BOOL=OFF
    -D Trilinos_ENABLE_Belos:BOOL=ON
    -D Trilinos_ENABLE_Epetra:BOOL=OFF
    -D Trilinos_ENABLE_EpetraExt:BOOL=OFF
    -D Trilinos_ENABLE_Ifpack:BOOL=OFF
    -D Trilinos_ENABLE_Ifpack2:BOOL=ON
    -D Trilinos_ENABLE_Kokkos:BOOL=ON
    -D   Kokkos_ARCH_POWER9:BOOL=ON
    -D   Kokkos_ARCH_VOLTA70:BOOL=ON
    -D   Kokkos_ENABLE_OPENMP:BOOL=OFF
    -D   Kokkos_ENABLE_CUDA:BOOL=ON
    -D   Kokkos_ENABLE_CUDA_UVM:BOOL=ON
    -D   Kokkos_ENABLE_CUDA_LAMBDA:BOOL=ON
    -D   Kokkos_ENABLE_CUDA_RELOCATABLE_DEVICE_CODE:BOOL=ON
    -D   Kokkos_ENABLE_DEPRECATED_CODE:BOOL=OFF
    -D Trilinos_ENABLE_KokkosKernels:BOOL=ON
       -D TPL_ENABLE_CUBLAS:BOOL=ON
       -D TPL_ENABLE_CUSPARSE:BOOL=ON
       -D KokkosKernels_ENABLE_TPL_CUBLAS:BOOL=ON
       -D KokkosKernels_ENABLE_TPL_CUSPARSE:BOOL=ON
       -D KokkosKernels_CUSPARSE_ROOT:PATH="$CUDA_ROOT"
       -D KokkosKernels_CUBLAS_ROOT:PATH="$CUDA_ROOT"
       -D KokkosKernels_INST_MEMSPACE_CUDAUVMSPACE:BOOL=ON
    -D Trilinos_ENABLE_ML:BOOL=OFF
    -D Trilinos_ENABLE_MueLu:BOOL=ON
    -D   MueLu_ENABLE_Kokkos_Refactor:BOOL=ON
    -D   MueLu_ENABLE_TESTS:BOOL=OFF
    -D   MueLu_ENABLE_EXAMPLES:BOOL=OFF
    -D Trilinos_ENABLE_Tpetra:BOOL=ON
    -D   Tpetra_ENABLE_CUDA:BOOL=ON
    -D   Tpetra_INST_SERIAL:BOOL=ON
    -D   Tpetra_INST_OPENMP:BOOL=OFF
    -D   Tpetra_INST_DOUBLE:BOOL=ON
    -D   Tpetra_ASSUME_CUDA_AWARE_MPI:BOOL=ON
    -D   Tpetra_ENABLE_EXAMPLES:BOOL=OFF
    -D Trilinos_ENABLE_STK:BOOL=ON
    -D   STK_DISABLE_KOKKOS_SIMD:BOOL=ON
    -D Trilinos_ENABLE_Gtest:BOOL=ON
    -D Trilinos_ENABLE_SEACASExodus:BOOL=ON
    -D Trilinos_ENABLE_SEACASEpu:BOOL=ON
    -D Trilinos_ENABLE_SEACASExodiff:BOOL=ON
    -D Trilinos_ENABLE_SEACASNemspread:BOOL=ON
    -D Trilinos_ENABLE_SEACASNemslice:BOOL=ON
    -D Trilinos_ENABLE_SEACASIoss:BOOL=ON
    -D Trilinos_ENABLE_Teuchos:BOOL=ON
    -D   Teuchos_KOKKOS_PROFILING:BOOL=ON
    -D Trilinos_ENABLE_Xpetra:BOOL=ON
    -D   Xpetra_ENABLE_Kokkos_Refactor:BOOL=ON
    -D Trilinos_ENABLE_Zoltan:BOOL=ON
    -D Trilinos_ENABLE_Zoltan2:BOOL=ON
    -D   Zoltan2_ENABLE_ParMETIS:BOOL=ON
    -D TPL_ENABLE_MPI:BOOL=ON
    -D   MPI_BASE_DIR:PATH="${OLCF_SPECTRUM_MPI_ROOT}"
)
```

**Comment by cgcgcg** [comment]
Yep, gotta make sure it's correctly scoped:
```
{
  node_velocities_distributed->getLocalView <device_type> (Tpetra::Access::ReadWrite);
}

{
  node_velocities_distributed->getLocalView < HostSpace> (Tpetra::Access::ReadOnly);
}

```
You can't have two active views of the same data.

**Comment by Adrian-Diaz** [comment]
I suspected that was happening and scoped the first one, however it still gave me the error in the same place. Does calling import after getting a host view have the same behavior?

**Comment by cgcgcg** [comment]
Most likely yes.

**Comment by Adrian-Diaz** [comment]
Seems scope hammering all the dual view accesses in my code fixed it, thanks for the help.

Adrian
