### ISSUE TITLE
EPIC: Issues with Trilinos PR testing 2022-08

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#10858]
There are a number of issues impacting Trilinos PR testing currently that are blocking many active PRs from passing the PR tester:

* #6861
* #10842
* #10836
* #10847 ... **Tests have been disabled for now**
* #10841 
* #10857 
* #10875
* #10885
* #10893
* #10898
* #10917
* #10931... **Pliris is disabled in ATS2 CUDA PR builds with merge of PR [#10930](https://github.com/trilinos/Trilinos/pull/10930)**

Also of interest:

* #10823 
* #10867
* #10840
* #10849 
* #10899

**Comment by csiefer2** [comment]
https://github.com/trilinos/Trilinos/issues/10896

**Comment by bartlettroscoe** [comment]
> #10896

As explained in https://github.com/trilinos/Trilinos/issues/10896#issuecomment-1218210333, there are not causes of PR failures, they are victims of a build failure that was also reported (or not as per https://github.com/trilinos/Trilinos/issues/10893#issuecomment-1218138724 :-( ).

**Comment by bartlettroscoe** [comment]
Even with all of the fixes in the linked issues [above](), we still have a large log jam in PR testing.  For example, right now [this issues query](https://github.com/trilinos/Trilinos/pulls?q=is%3Aopen+is%3Apr+label%3A%22AT%3A+RETEST%22) shows there are 8 PRs that have the `AT: RETEST` label on them.  It looks like something is wrong with the PR tester is that only one set of PR build is running at one time.  The outer driver for the second set of PRs looks to be broken (see  https://do.sandia.gov/trilinos-ci/job/Trilinos_autotester_driver_inst_1/).  I will post a Trilinos HelpDesk issue.

**Comment by bartlettroscoe** [comment]
FYI: I posted [TRILINOSHD-18](https://sems-atlassian-son.sandia.gov/jira/servicedesk/customer/portal/7/TRILINOSHD-187) to see if they can turn off auto-retest of failing PR builds.  That is often a waste of computing resources as the developer has not even had a chance to look over the failed PR build results to see if rerunning the PR builds is likely to fix anything.

**Comment by bartlettroscoe** [comment]
As noted [above](https://github.com/trilinos/Trilinos/issues/10858#issuecomment-1220937087), only one of two Jenkins `Trilinos_autotester_driver_inst` instances is running and there seems to be logic built into assume that the other instance is running PR builds. For example:

* https://do.sandia.gov/trilinos-ci/job/Trilinos_autotester_driver_inst_0/4489/consoleFull

shows:

```
22:00:38 PROCESSING prnum = 10897
22:00:38    PROCESSING PULL REQ# 10897
22:00:38       - PRINFO - Mergeable: True; State: open; Title: Improve TrilinosInstallTests to make more clear (#10896); By: bartlettroscoe
22:00:38       - SOURCE - Repo: bartlettroscoe/Trilinos; branch: 10896-improve-doc-install-tests; sha: 00ca3870b23ddea877be9f1abbaf1e3bfee833ad; User: bartlettroscoe
22:00:38       - TARGET - Repo: trilinos/Trilinos; branch: develop; sha: f4b73d31ef4f77626c1c7c8c9a86034cc64fa011; User: trilinos
22:00:38       - PR From Fork = True
22:00:38 *** NOTICE: This PR #10897 is not tested by this instance of the pullrequestautotester_inst_0; Instance 1 will test it - SKIPPING THIS PULL 
```

So the PR tester logic seems to thing that the other instance (`Instance 1`) will be testing my PR #10897 but that instance appears to be broken a shown at, for example:

* https://do.sandia.gov/trilinos-ci/job/Trilinos_autotester_driver_inst_1/3857/console

showing:

```
21:42:00 Started by timer
21:42:00 Running as SYSTEM
21:42:01 Building remotely on [pr-host-1](https://do.sandia.gov/trilinos-ci/computer/pr-host-1) (ceecloud_PR_host_1 PR_host) in workspace <...>/Trilinos_autotester_driver_inst_1
21:42:01 [WS-CLEANUP] Deleting project workspace...
21:42:01 [WS-CLEANUP] Deferred wipeout is used...
21:42:07 ERROR: [WS-CLEANUP] Cannot delete workspace: Remote call on pr-host-1 failed
21:42:07 ERROR: Cannot delete workspace: Remote call on pr-host-1 failed
21:42:07 Finished: FAILURE
```

I think as a result, all of the 8 PRs with `AT: RETEST` put on them seem to be assigned to run in PR instance 1 which is broken.

As a result, no PR builds have started since Aug 19, 2022 - 18:08 MDT shown [here](https://trilinos-cdash.sandia.gov/index.php?project=Trilinos&parentid=399425&filtercount=1&showfilters=1&field1=groupname&compare1=61&value1=Pull%20Request&filtercombine=and).

This system does not seem to be very robust to instances of these drivers going down.

**Comment by bartlettroscoe** [comment]
Looking over the PR builds being skipped with the message:

`*** NOTICE: This PR #<prnum> is not tested by this instance of the pullrequestautotester_inst_0; Instance 1 will test it - SKIPPING THIS PULL REQUEST`

at:

* https://do.sandia.gov/trilinos-ci/job/Trilinos_autotester_driver_inst_0/4489/consoleFull

I am noticing that all of the `<prnum>` like #8161, #8737, #8855, ..., #10909 (41 PRs in total) are all **odd numbers**.  That suggests that the PR tester's approach to load balancing is to use `total_num_prs % num_pr_drivers` to compute which PR drivers instance 0, 1, ... will be testing a given PR.  So with two running instances, odd numbered PRs compute to `total_num_prs % num_pr_drivers`.

So if you want to get your PR to be tested, just open a new PR and make sure the PR number is even :-)

**Comment by bartlettroscoe** [comment]
Looking at the history for the broken PR tester driver:

* https://do.sandia.gov/trilinos-ci/job/Trilinos_autotester_driver_inst_1/

it seems that the Trilinos_autotester_driver_inst_1 last ran successfully on 'Aug 16, 2022, 2:03:02 PM'.

* https://do.sandia.gov/trilinos-ci/job/Trilinos_autotester_driver_inst_1/3724/

After that, starting on 'Aug 17, 2022, 6:37:29 PM' for:

* https://do.sandia.gov/trilinos-ci/job/Trilinos_autotester_driver_inst_1/3725/

that instance was broken and not running any PR builds.

So it seems that the PR tester implementation for the last **4 days** has been running only one set of PR builds at a time and then only testing even-numbered PRs :-)

And to back this up, [this CDash query](https://trilinos-cdash.sandia.gov/index.php?project=Trilinos&begin=2022-08-16&end=2022-08-20&filtercount=2&showfilters=1&filtercombine=and&field1=groupname&compare1=61&value1=Pull%20Request&field2=buildname&compare2=63&value2=ats2) shows that the last time an odd-numbered PR was tested was Aug 17, 2022 - 14:18 MDT with the build:

* [PR-10851-test-ats2_cuda-10.1.243-gnu-8.3.1-spmpi-rolling_release_static_Volta70_Power9_no-asan_no-complex_no-fpic_mpi_pt_no-rdc_uvm_deprecated-on_no-package-enables-928](https://trilinos-cdash.sandia.gov/index.php?project=Trilinos&parentid=394666&filtercount=1&showfilters=1&field1=groupname&compare1=61&value1=Pull%20Request&filtercombine=and)

After that, only even-numbered PRs were tested.

And if you look at the current list of PRs with `AT: RETEST` on them [here](https://github.com/trilinos/Trilinos/pulls?q=is%3Aopen+is%3Apr+label%3A%22AT%3A+RETEST%22), you will see they are all odd-numbered PRs.

(NOTE: Those dates don't exactly match up so not sure how an odd-numbered PR was able to be tested after 'Aug 16, 2022, 2:03:02 PM' but the general trend of only even-number PRs getting tested and only odd-numbered PRs that still have `AT: RETEST` holds.)

**Comment by bartlettroscoe** [comment]
FYI: I created the even-numbered PR #10912 to test the [above](https://github.com/trilinos/Trilinos/issues/10858#issuecomment-1221454400) even-only PR testing hypothesis.   But it looks like PR builds will not start up again until tomorrow morning after 7 AM MDT so we will have to wait until then.

**Comment by bartlettroscoe** [comment]
As predicted [above](https://github.com/trilinos/Trilinos/issues/10858#issuecomment-1221459318), the next job fired off at 7:16 AM MDT with:

* https://do.sandia.gov/trilinos-ci/job/Trilinos_autotester_driver_inst_0/4490/

and it is running PR builds for **even-numbered** PR #10912 showing:

```
09:22:10    * ========================
09:22:10    * PERFORMING TESTING ON PULL REQ# 10912 (Run Number 1/2)
09:22:10    * ========================
```

(Jenkins must be showing times according to my browser so this must be 09:22:10 EDT, not MDT).

**Comment by bartlettroscoe** [comment]
Another problem with the PR builds:

* #10931

**Comment by bartlettroscoe** [comment]
FYI: I think the major errors blocking PR builds from passing have been resolved.  Now there are just a few random failures like #6861 that are still taking down PR testing iterations.

**Comment by bartlettroscoe** [comment]
FYI As (not) shown in [this GitHub Issue Query](https://github.com/trilinos/Trilinos/pulls?q=is%3Aopen+is%3Apr+label%3A%22AT%3A+RETEST%22) there are no more PRs with the `AT: RETEST` label.  And no PR builds have started in the last 22 hours  And the two drivers are running with the latest runs shown at:

* https://do.sandia.gov/trilinos-ci/job/Trilinos_autotester_driver_inst_0/4661/consoleFull

and

* https://do.sandia.gov/trilinos-ci/job/Trilinos_autotester_driver_inst_1/3987/consoleFull

And [this GitHub Issue Query](https://github.com/trilinos/Trilinos/pulls?q=is%3Aopen+is%3Apr+-label%3A%22AT%3A+WIP%22+review%3Aapproved) shows that there are just 8 open PRs with approved reviews and of those 7 have a failing PR builds status. 

Therefore, the logjam of PR builds is over.  Yes, there are still a few sources of random failures that may trigger a failing PR testing iteration (i.e. #6861 and #10989) but everything else seems to have been addressed.

I will now close this EPIC and remove the pin.
