### ISSUE TITLE
Framework: testing.sandia.gov/cdash/ getting pulled internally or removed

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#10852]
CC: @cgcgcg, @fryeguy52, @jhux2, @trilinos/framework

### Internal issues

* [TRILINOSHD-161](https://sems-atlassian-son.sandia.gov/jira/servicedesk/customer/portal/7/TRILINOSHD-161)

### Description

It seems the official Trilinos Framework team policy is to no longer support an external Trilinos CDash site as per [TRILINOSHD-145](https://sems-atlassian-son.sandia.gov/jira/servicedesk/customer/portal/7/TRILINOSHD-145) where it was stated:

> Framework does not support testing.sandia.gov. We support trilinos-cdash.sandia.gov.

Given that the all of Trilinos PR and Master Merge builds being run by the Trilinos Framework team are being posted to the SRN site internal SRN CDash trilinos-cdash.sandia.gov, that makes sense.

However, the are still some Trilinos developers, projects, and and package teams that are submitting Trilinos builds to testing.sandia.gov/cdash/ (and also testing-dev.sandia.gov/cdash/ to help support the development of CDash by Kitware).  This mostly includes the ATDM Trilinos builds (which can be switched to submit to trilinos-cdash.sandia.gov) but also includes experimental builds being run on other machines like 'weaver' (from @fryeguy52 [here](https://testing.sandia.gov/cdash/build/11191454/configure)) that are on the SON and can't submit to the SRN site trilinos-cdash.sandia.gov.  (Don't if the the machines 'enigma' and 'geminga' are on the SON or SRN that are submitting builds run by @jhux2?)

Also there is a lot of pressure to not have any external facing sites with the sandia.gov address so moving testing.sandia.gov/cdash/ internally will make things easier for some people who are getting pushed about this.

**Comment by bartlettroscoe** [comment]
FYI: I will put in a PR to change Trilinos/CTestConfig.cmake to post to trilinos-cdash.sandia.gov instead of testing.sandia.gov/cdash/.

**Comment by mayrmt** [comment]
How will this affect external contributors without any affiliation to Sandia (and without access to neither SON nor SRN)?

**Comment by bartlettroscoe** [comment]
> How will this affect external contributors without any affiliation to Sandia (and without access to neither SON nor SRN)?

@mayrmt, not at all.  All of the PR and Master Merge builds are already getting submitted to an internal SRN CDash site trilinos-cdash.sandia.gov.

**Comment by bartlettroscoe** [comment]
FYI: I tried switching the GitHub Actions builds for the https://github.com/TriBITSPub/TriBITS project to my.cdash.org and the results stopped posting (see https://github.com/TriBITSPub/TriBITS/issues/508).  Therefore, I switched that project back to testing.sandia.gov/cdash/.

Therefore, we need to keep testing.sandia.gov publicly accessible to at least support TriBITS.

But for the remaining Trilinos builds, we need to switch the default to submit to the internal trilinos-cdash.sandia.gov so that the ATDM Trilinos builds and the small number of other builds will be submitted there as well.  (We are no longer supposed to be submitting builds from SRN machines to an open CDash site.)  I will create a new issue for that.

**Comment by bartlettroscoe** [comment]
FYI: I created the new issue #10876.

**Comment by bartlettroscoe** [comment]
@ccober6 and @e10harvey, it looks like we are not going to be able to keep these sites external.  So I think the plan is to let them get pulled internally.  I am handing this over to you as the framework leads to do with as you will.

Let me know if you have any questions.

**Comment by bartlettroscoe** [comment]
Reopening for real

**Comment by e10harvey** [comment]
@bartlettroscoe @ccober6, everything that framework owns posts to trilinos-cdash.sandia.gov. We will move the secondary and primary atdm builds there too.

**Comment by jhux2** [comment]
>  (Don't if the the machines 'enigma' and 'geminga' are on the SON or SRN that are submitting builds run by @jhux2?)

Both `enigma` and `geminga` are on the SON.  Is this going to be a problem vis-a-vis submitting to the internal dashboard?

**Comment by bartlettroscoe** [comment]
> > (Don't if the the machines 'enigma' and 'geminga' are on the SON or SRN that are submitting builds run by @jhux2?)
> 
> Both `enigma` and `geminga` are on the SON. Is this going to be a problem vis-a-vis submitting to the internal dashboard?

@jhux2, then we should be able to keep testing.sandia.gov on the SON as long as all other builds on SRN machines get posted to trilinos-cdash.sandia.gov.

**Comment by bartlettroscoe** [comment]
CC: @e10harvey

FYI: After getting some help from Kitware, switching the [TriBITS](https://github.com/TriBITSPub/TriBITS) project back to submitting to my.cdash.org seems to be going well.  Therefore, I don't think there is any need to keep testing.sandia.gov/cdash/ and testing-dev.sandia.gov/cdash/ out on the open web. They can bring them into the SNL SON network.
