### ISSUE TITLE
how to minus two crs matrix  C=A-B

### ISSUE THREAD

**Issue by ztdepztdep** [trilinos/Trilinos#10854]
I want to obtain the difference between two CRS matrix C=A-B. Could you please give me some advice.

**Comment by cgcgcg** [comment]
What are you using? Epetra? Tpetra? Xpetra? The matrix addition usually takes two additional scalar parameters, alpha and beta, and allows you to compute alpha*A+beta*B.

**Comment by jhux2** [comment]
Tpetra is documented here https://docs.trilinos.org/dev/packages/tpetra/doc/html/namespaceTpetra_1_1MatrixMatrix.html.
Epetra is documented here https://docs.trilinos.org/dev/packages/epetraext/doc/html/classEpetraExt_1_1MatrixMatrix.html.

**Comment by ztdepztdep** [comment]
Thanks I use epetra
which API should I use to obtain
this goal



| |
***@***.***
|
|
***@***.***
|




---- Replied Message ----
| From | Christian ***@***.***> |
| Date | 08/10/2022 21:08 |
| To | ***@***.***> |
| Cc | ***@***.******@***.***> |
| Subject | Re: [trilinos/Trilinos] how to minus two crs matrix C=A-B (Issue #10854) |

What are you using? Epetra? Tpetra? Xpetra? The matrix addition usually takes two additional scalar parameters, alpha and beta, and allows you to compute alphaA+betaB.

**Comment by cgcgcg** [comment]
See above.
