### ISSUE TITLE
Kokkos: failing Albany nightly build due to missing header

### ISSUE THREAD

**Issue by ikalash** [trilinos/Trilinos#10868]
The nightly clang CEE build for Albany is failing with an error about a missing Kokkos header:

```
[Albany/src/Albany_KokkosTypes.hpp:19](https://blob/master/Albany/src/Albany_KokkosTypes.hpp#L19):10: fatal error: 'Kokkos_StaticCrsGraph.hpp' file not found
```
https://sems-cdash-son.sandia.gov/cdash/viewBuildError.php?buildid=37594

Curiously, it doesn't happen with any of the other builds, which use different compilers.  Did this header get renamed / removed?

@trilinos/kokkos

**Comment by ikalash** [comment]
Can anyone provide any insight into this issue?  We are still having this failure in Albany.  

@trilinos/kokkos

**Comment by ibaned** [comment]
@ikalash it may help to create an issue at http://github.com/kokkos/kokkos instead

**Comment by ikalash** [comment]
Thanks for the tip @ibaned .  I will do this.

**Comment by ikalash** [comment]
Sorry for not using the format for the issue.  I am super swamped today hosting a visitor...  The problem started on Aug. 10.  If you cannot access the URL, the error is exactly what I cut/paste in the issue about Kokkos_StaticCrsGraph.hpp not being found.  This is why I was asking if it was renamed or removed - I thought perhaps the issue was something as simple as updating the name.

Amy, I can provide scripts once I'm done with my hosting duties.  Please stay tuned.
