### ISSUE TITLE
Improve instructions for reproducing PR builds using GenConfig system

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#10867]
CC: @jhux2, @rppawlo, @csiefer2 

### Internal Issues

* [TRILINOSHD-169](https://sems-atlassian-son.sandia.gov/jira/servicedesk/customer/portal/7/TRILINOSHD-169)

### Description

Some Trilinos developers seem to be confused about how to use the new GenConfig system to successfully and correctly reproduce PR builds on various systems.  It seems the process described at:

* https://github.com/trilinos/Trilinos/wiki/Reproducing-PR-Testing-Errors

is not sufficient.

I will write up a new wiki page detailing a process that I have worked out that seems to work better and will give developers more control on configuring.

**Comment by jhux2** [comment]
@bartlettroscoe Totally forgot about those instructions.  Before you do a re-write, let me use them, and then I can provide feedback.

**Comment by bartlettroscoe** [comment]
@jhux2, just real quick, I create two files in the build dir ...

**load-env-and-cmake-frag-file.sh:**

```
TRILINOS_DIR_local=<trilinos-src-dir>
FULL_BUILD_NAME=<full-build-name>
if [[ -e GenConfigSettings.cmake ]] ; then
  echo "Remvoing existing file GenConfigSettings.cmake ..."
  rm GenConfigSettings.cmake
fi
source $TRILINOS_DIR_local/packages/framework/GenConfig/gen-config.sh \
--cmake-fragment GenConfigSettings.cmake \
${FULL_BUILD_NAME} \
--force \
$TRILINOS_DIR_local \
--force
"$@"
unset TRILINOS_DIR_local
```

**do-configure:**
```
if [[ -e CMakeCache.txt ]] ; then
  echo "Removing CMakeCache.txt ..."
  rm CMakeCache.txt
fi
if [[ -d CMakeFiles ]] ; then
  echo "Removing CMakeFiles ..."
  rm -r CMakeFiles
fi
cmake \
-G Ninja \
-C GenConfigSettings.cmake \
-D Trilinos_ENABLE_ALL_FORWARD_DEP_PACKAGES=OFF \
-D Trilinos_ENABLE_TESTS=ON \
-D Trilinos_TRACE_ADD_TEST=ON \
"$@" \
$TRILINOS_DIR
```

where above you fill in `<trilinos-src-dir>` for your local Trilinos source dir and `<full-build-name>` is copied from the full build name off CDash.

You can then load the env and configure with:

```
$ cd <buildDir>/

$ . load-env-and-cmake-frag-file.sh

$ ./do-configure [extra enables]
```

To do the exact same enables as used in the PR build, you can download the file `packageEnables.cmake` from CDash and pass that in as:

```
$ ./do-configure -C packageEnables.cmake [extra options]
```

NOTES:

* Sourcing `load-env-and-cmake-frag-file.sh` puts you into a new bash shell and exports the env var `TRILINOS_DIR` (which is critical because some of the cache vars set in `GenConfigSettings.cmake` read from `$ENV{TRILINOS_DIR}`).

**Comment by jhux2** [comment]
Here are a few initial comments.

In general, it's not always clear whether the instructions are referring to the dashboard machine or the machine where I'm trying to reproduce the build.

Does the build directory have to be a subdir of Trilinos source, and does it have to have the name `build-PR_<NUM>`?

Step 4)
        "ssh to the machine and move packageEnables.cmake to /path/to/Trilinos/build-PR_<NUM> where <NUM> is the PR number from your GitHub PR."

        - I guess you mean the machine where you want to configure/build?
        - and I'll need to create the directory "build-PR_<NUM>"?

Step 6)

      No machine I have access to has a module called "git".  Maybe just give a min/max git version that's allowable.

**Comment by jhux2** [comment]
More comments:

Step 7:

   <BUILD_NAME> really needs be this???

PR-10775-test-rhel7_sems-gnu-7.2.0-openmpi-1.10.1-serial_debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables-850

**Comment by bartlettroscoe** [comment]
> Does the build directory have to be a subdir of Trilinos source, and does it have to have the name `build-PR_<NUM>`?

No.  Should just be `<buildDir>` and any directory in any place (other than an in-source build).

> `<BUILD_NAME>` really needs be this???
>
> PR-10775-test-rhel7_sems-gnu-7.2.0-openmpi-1.10.1-serial_debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables-850

Almost.  Really only important part is:

* `rhel7_sems-gnu-7.2.0-openmpi-1.10.1-serial_debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables`

> "ssh to the machine and move packageEnables.cmake to /path/to/Trilinos/build-PR_ where is the PR number from your GitHub PR."

That is where the instructions are really lacking.  For example, how do you have any idea how to do builds on 'vortex' unless you are really familiar with that machine?  What they need is a section like:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#specific-instructions-for-each-system

with detailed instructions for each unique system.

But the only difficult system where PRs builds are running is 'vortex'.  All of the other PR builds only run on two types of systems:

* `rhel7`: Any SEMS RHEL-7 machine (including any CEE RHEL-7 machine, all 'ascic' machines, 'ascicgpu' machines, 'hpws' machines, etc.)
* `rhel7-_sems-cuda`: Any 'ascicgpu' machine

Should I just start a new wiki page to document this?

**Comment by bartlettroscoe** [comment]
It just occurred to me how to make this easier for people to use on machines where you just need to log on and load env, configure, build, and run tests.  I will write a `load-gen-config-env.sh` script checked into Trilinos repo that you just call with:

```
$ source <trilinosDir>/packages/framework/load-gen-config-env.sh <full-build-name>
```

which puts you into a new bash shell, generates the file `GenConfigSettings.cmake` and then you configure with:

```
$ cmake \
-G Ninja \
-C GenConfigSettings.cmake \
-D Trilinos_ENABLE_ALL_FORWARD_DEP_PACKAGES=OFF \
-D Trilinos_ENABLE_TESTS=ON \
-D Trilinos_ENABLE_<some-package>=ON \
$TRILINOS_DIR
```

where `TRILINOS_DIR` got set automatically by `load-gen-config-env.sh`.

**Comment by bartlettroscoe** [comment]
@jhux2, FYI, turns out reproducing builds is more tricky than I thought.  I think the framework team only runs these build configurations through Jenkins so things like the env var `WORKSPACE` have become a requirement.  See my updated scripts [above](https://github.com/trilinos/Trilinos/issues/10867#issuecomment-1213553329) which seems to work everywhere.

**Comment by jhux2** [comment]
@bartlettroscoe Thanks, I'll give this a try a bit later this week.

**Comment by bartlettroscoe** [comment]
> @bartlettroscoe Thanks, I'll give this a try a bit later this week.

@jhux2, instead of the scripts above, can you please take a look at and try out the script in #10886?  That seems to be about as good as I can make it (and it makes GenConfig work more similar to the usage of the cmake/std/atdm/load-env.sh script if you think that system works well).

**Comment by bartlettroscoe** [comment]
Just as a positive datapoint, after updating the sync of the SEMS modules to my personal SNL SRN RHEL7 machine 'crf450', using the scripts:

**load-env.sh**
```
export TRILINOS_DIR=${HOME}/Trilinos.base/Trilinos
source ${TRILINOS_SRC}/packages/framework/GenConfig/gen-config.sh \
--cmake-fragment GenConfigSettings.cmake \
rhel7_sems-clang-10.0.0-openmpi-1.10.1-serial_release-debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables \
--force -y \
"$@" \
${TRILINOS_DIR}
```

**do-configure**
```
rm -rf CMakeCache.txt CMakeFiles
cmake \
-G Ninja \
-C GenConfigSettings.cmake \
-D Trilinos_ENABLE_ALL_FORWARD_DEP_PACKAGES=OFF \
-D Trilinos_ENABLE_TESTS=ON \
"$@" \
${TRILINOS_DIR}
```

I was able to fully reproduce the clang-10.0.0 PR build as:

```
$ ssh crf450

$ cd ~/Trilinos.base/BUILDS/PR/clang-10.0.0/

$ . load-env.sh

$ time ./do-configure -DTrilinos_ENABLE_ALL_PACKAGES=ON &> configure.out
real    1m57.620s
user    1m10.530s
sys     0m45.079s

$ time ninja &> make.out

real    85m48.215s
user    2511m15.504s
sys     61m14.569s

$ time ctest -j12 &> ctest.out

real    15m6.953s
user    150m49.781s
sys     13m29.879s

$ grep "failed out of" ctest.out 
100% tests passed, 0 tests failed out of 3396
```

Now I have a full PR build that I can reproduce!

What would improve this a good bit is if a version of the `load-env.sh` script could live in Trilinos so that it could automatically figure out the Trilinos source dir.
