### ISSUE TITLE
ExtractCrsDataPointers(ptr,col,val)  error

### ISSUE THREAD

**Issue by ztdepztdep** [trilinos/Trilinos#10873]
I extract the Crs pointer from my crs matrix . I define the prt, col val by std::vector, but I alway got an error of :

"  error: cannot bind non-const lvalue reference of type ‘int*&’ to an rvalue of type ‘__gnu_cxx::__alloc_traits<std::allocator<int> >::value_type* {aka int*}’"

 how to resolve this problem?

     A_Diffusion->ExtractCrsDataPointers(ptr,col,val); " 
```
  vector<int>    ptr;  
  vector<int>    col; 
  vector<double> val; 
ExtractCrsDataPointers(&ptr[0],&col[0],&val[0]) 
```

**Comment by jhux2** [comment]
Try
```
int *ptr, *col;
double *val;
```

**Comment by cgcgcg** [comment]
Please reopen if this is still an issue.
