### ISSUE TITLE
Framework: PR builds failing due to "No space left on device" 2022-08

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#10875]
## Bug Report

@trilinos/framework, @jhux2, @rppawlo 

### Internal Issues

* [TRILINOSHD-172](https://sems-atlassian-son.sandia.gov/jira/servicedesk/customer/portal/7/TRILINOSHD-172)

### Description

PR builds are failing, such as in the build [PR-10808-test-rhel7_sems-gnu-7.2.0-openmpi-1.10.1-serial_debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables-870](https://trilinos-cdash.sandia.gov/index.php?project=Trilinos&parentid=377950&filtercount=1&showfilters=1&field1=buildstarttime&compare1=84&value1=NOW&filtercombine=and) showing:

```
... No space left on device
```

### Steps to Reproduce

Run PR builds

**Comment by bartlettroscoe** [comment]
And here are other builds where we are seeing this error as well:

* [PR-10829-test-rhel7_sems-gnu-7.2.0-openmpi-1.10.1-serial_debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables-869](https://trilinos-cdash.sandia.gov/index.php?project=Trilinos&parentid=377500&filtercount=2&showfilters=1&field1=groupname&compare1=61&value1=Pull%20Request&field2=builderrors&compare2=43&value2=0&filtercombine=and)

* [PR-10825-test-rhel7_sems-gnu-7.2.0-openmpi-1.10.1-serial_debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables-866](https://trilinos-cdash.sandia.gov/index.php?project=Trilinos&parentid=376214&filtercount=2&showfilters=1&field1=groupname&compare1=61&value1=Pull%20Request&field2=builderrors&compare2=43&value2=0&filtercombine=and)

* [PR-10827-test-rhel7_sems-gnu-7.2.0-openmpi-1.10.1-serial_debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables-854](https://trilinos-cdash.sandia.gov/index.php?project=Trilinos&parentid=371124&filtercount=2&showfilters=1&field1=groupname&compare1=61&value1=Pull%20Request&field2=builderrors&compare2=43&value2=0&filtercombine=and)

Note that all 4 of these builds showing these errors in the last 2 days shown [here](https://trilinos-cdash.sandia.gov/index.php?project=Trilinos&begin=2022-08-12&end=2022-08-13&filtercount=2&showfilters=1&filtercombine=and&field1=groupname&compare1=61&value1=Pull%20Request&field2=builderrors&compare2=43&value2=0) are all running on the machine `ascicgpu142`!

**Comment by bartlettroscoe** [comment]
I bet you that [these "6" build errors builds](https://trilinos-cdash.sandia.gov/index.php?project=Trilinos&filtercount=4&showfilters=1&filtercombine=and&field1=buildname&compare1=63&value1=PR-10808-test&field2=builderrors&compare2=41&value2=6&field3=testsnotrun&compare3=43&value3=50&field4=buildstarttime&compare4=84&value4=NOW) running on **ascic142** showing:

![image](https://user-images.githubusercontent.com/1959736/184520563-9cd84f7a-c081-44fd-9ba3-64891d386c44.png)

are a result of "No space left on device" but is just not being reported to CDash correctly.

**Comment by bartlettroscoe** [comment]
NOTE: This is not the first time we have seem problems with the build node **ascic142** as described in the comments starting in https://github.com/trilinos/Trilinos/issues/3276#issuecomment-412208449 and also https://github.com/trilinos/Trilinos/issues/3276#issuecomment-413699780.

**Comment by bartlettroscoe** [comment]
I will wager that the build errors on the node 'ascic142' for the build:

* `rhel7_sems-gnu-7.2.0-openmpi-1.10.1-serial_debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables`

and the build errors on the node 'ascic158' for the build:

* `rhel7_sems-intel-17.0.1-mpich-3.2-serial_release-debug_static_no-kokkos-arch_no-asan_no-complex_fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables`

over the last two days shown in [this query](https://trilinos-cdash.sandia.gov/index.php?project=Trilinos&begin=2022-08-12&end=2022-08-14&filtercount=2&showfilters=1&filtercombine=and&field1=groupname&compare1=61&value1=Pull%20Request&field2=builderrors&compare2=41&value2=6) showing:

![image](https://user-images.githubusercontent.com/1959736/184559037-2545d658-edb8-4ec0-ace9-9adda63841fa.png)

are due to out-of-memory errors.  The fact there is a bunch of "Not Run" tests with different numbers of tests seems to suggest this.

None of these Jenkins jobs are showing a `LastBuild_<datea>-<time>.log` file as **not** shown at:

* https://do.sandia.gov/trilinos-ci/job/Trilinos_PR_intel-17.0.1/858/
* https://do.sandia.gov/trilinos-ci/job/Trilinos_PR_intel-17.0.1/870/
* https://do.sandia.gov/trilinos-ci/job/Trilinos_PR_gcc-7.2.0-debug/852/
* https://do.sandia.gov/trilinos-ci/job/Trilinos_PR_gcc-7.2.0-debug/877/
* https://do.sandia.gov/trilinos-ci/job/Trilinos_PR_gcc-7.2.0-debug/874/
* https://do.sandia.gov/trilinos-ci/job/Trilinos_PR_gcc-7.2.0-debug/850/

**Comment by bartlettroscoe** [comment]
FYI: All but one of the builds on 'ascic142' with "1" build error over the last two days showing any build errors shown in [this query](https://trilinos-cdash.sandia.gov/index.php?project=Trilinos&begin=2022-08-12&end=2022-08-14&filtercount=4&showfilters=1&filtercombine=and&field1=groupname&compare1=61&value1=Pull%20Request&field2=site&compare2=61&value2=ascic142&field3=builderrors&compare3=43&value3=0&field4=builderrors&compare4=42&value4=6) showing:

![image](https://user-images.githubusercontent.com/1959736/184559360-6e92f60d-58fe-44b2-9983-9419ad89f2dd.png)

show a build error in the package `Zoltan2Sphynx` for the command:

```
"/projects/sems/install/rhel7-x86_64/sems/utility/cmake/3.19.1/bin/cmake" "--build" "." "--config" "Debug" "--" "-j20" "-k" "0"
```

showing:

```
 fatal error: error writing to /tmp/ccz9g0gD.s: No space left on device
```

So that suggests that it is /tmp filling up on 'ascic142', not the main disk space.

The output for the Jenkins ctest -S driver one of these builds at:

* https://do.sandia.gov/trilinos-ci/job/Trilinos_PR_gcc-7.2.0-debug/872/consoleFull

is showing:

```
02:38:17  >>> CTEST_BUILD_NAME         = PR-10834-test-rhel7_sems-gnu-7.2.0-openmpi-1.10.1-serial_debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables-872
02:38:17  >>> PARALLEL_LEVEL           = 20
02:38:17  >>> TEST_PARALLEL_LEVEL      = 4
```

Does `PARALLEL_LEVEL` OF `20` mean that it is running `ninja -j20`?  If so, that may be too high for this build of Trilinos on this platform.

**Comment by bartlettroscoe** [comment]
Wow, the space on /tmp/ on 'ascic142' is in such bad shape, it can't even get through the configure.  The build:

* [PR-10871-test-rhel7_sems-clang-10.0.0-openmpi-1.10.1-serial_release-debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables-885](https://trilinos-cdash.sandia.gov/build/382259)

for the PR #10871 that does not even enable any packages failed in the configure-time compiler check showing:

```
- Check for working Fortran compiler: /projects/sems/install/rhel7-x86_64/sems/compiler/clang/10.0.0/openmpi/1.10.1/bin/mpif90 - broken
CMake Error at /projects/sems/install/rhel7-x86_64/sems/utility/cmake/3.17.1/share/cmake-3.17/Modules/CMakeTestFortranCompiler.cmake:45 (message):
  The Fortran compiler

    "/projects/sems/install/rhel7-x86_64/sems/compiler/clang/10.0.0/openmpi/1.10.1/bin/mpif90"

  is not able to compile a simple test program.

  It fails with the following output:
  ...

    Fatal Error: error closing /tmp/ccEUv3aY.s: No space left on device
    compilation terminated.
    ninja: build stopped: subcommand failed.
  ...

-- Configuring incomplete, errors occurred!
See also "/scratch/trilinos/jenkins/ascic142/workspace/Trilinos_PR_clang-10.0.0/pull_request_test/CMakeFiles/CMakeOutput.log".
See also "/scratch/trilinos/jenkins/ascic142/workspace/Trilinos_PR_clang-10.0.0/pull_request_test/CMakeFiles/CMakeError.log".
```

**Comment by srbdev** [comment]
I've cleared the /tmp/ directory on the system. Do you know if it happened to fill up from a single build, or an accumulation of failures? It was full of .cpp and .sh files from the various packages...

**Comment by bartlettroscoe** [comment]
> I've cleared the /tmp/ directory on the system. Do you know if it happened to fill up from a single build, or an accumulation of failures? It was full of .cpp and .sh files from the various packages...

@srbdev, no clue.  How large is that /tmp/ directory partition?

**Comment by srbdev** [comment]
It's 32G, with about 30G available after cleanup

**Comment by srbdev** [comment]
None, it was 100% full

**Comment by bartlettroscoe** [comment]
FYI: As shown in [this query](https://trilinos-cdash.sandia.gov/index.php?project=Trilinos&begin=2022-08-15&end=2022-08-16&filtercount=2&showfilters=1&filtercombine=and&field1=groupname&compare1=61&value1=Pull%20Request&field2=site&compare2=61&value2=ascic142), there has not been a single test failure reported to CDash from 'ascic142' in the 12 PR builds run after @srbdev cleaned out the /tmp/ directory.  Therefore, we can consider this fixed.
