### ISSUE TITLE
Tpetra::MultiVector: Don't use CudaUVMSpace for internal comm buffers

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#1088]
@trilinos/tpetra 

Blocked by: #1571, #1602, #1658

MPI on Pascal, not K80, appears to be slow when accessing UVM-allocated device buffers, but not standard CUDA device buffers.  This causes trouble with Tpetra::Distributor sending and receiving packed data, as measured by @ambrad .  It also probably causes trouble with dot product and norm.

@crtrott and I wrote an MPI + Kokkos benchmark to measure this independently of Tpetra.

Possible work-around: Don't use CudaUVMSpace for internal comm buffers in DistObject methods packAndPrepareNew and unpackAndCombineNew.  Define a typedef pack_dev_memory_space which is CudaSpace when execution_space is Cuda.

**Comment by mhoemmen** [comment]
Inside Tpetra::DistObject: 
```
#ifdef KOKKOS_HAVE_CUDA
typedef typename std::conditional<std::is_same<typename device_type::execution_space, Kokkos::Cuda>::value, Kokkos::CudaSpace, typename device_type::memory_space>::type pack_memory_space;
#else
typedef typename device_type::memory_space pack_memory_space;
#endif // KOKKOS_HAVE_CUDA
```

**Comment by crtrott** [comment]
I am on it, was thinking I can get that in one batch through with the testing for KokkosKernels.

**Comment by mhoemmen** [comment]
> I am on it, was thinking I can get that in one batch through with the testing for KokkosKernels.

one step at a time :) we don't know if this really the issue yet, also we may have to do the same for dot products and i haven't tested whether this _builds_ yet ;-P

**Comment by crtrott** [comment]
Digging around inside Tpetra_Import_Util2.hpp

**Comment by crtrott** [comment]
Looks like it is compiling :-)

**Comment by crtrott** [comment]
And it only broke the CrsMatrix UnitTests and the BlockCrsMatrix UnitTests, but those are not important right ;-)?

**Comment by crtrott** [comment]
This probably means the sync logic is bad inside pack and unpack ...

**Comment by mhoemmen** [comment]
> This probably means the sync logic is bad inside pack and unpack ...

:( note that we've never tested Tpetra on CUDA not with UVM.  On the other hand, pack and unpack for CrsGraph and CrsMatrix should use the old interface that takes Teuchos::Array*.

**Comment by mhoemmen** [comment]
Just to summarize our debugging session this afternoon: Kokkos::DualView::modify checks whether the input template parameter has the same memory_space as the DualView.  If not, it marks the "host view" modified.  This means that, for example, if the DualView's memory_space is CudaUVMSpace and the input template parameter is CudaSpace, the DualView's host view will get marked as modified, contrary to expectations.  The work-around is to make sure that the input memory_space is right.

**Comment by ambrad** [comment]
@trilinos/tpetra (pinging the issue at MH's request)

**Comment by mhoemmen** [comment]
@ambrad Could you send both @crtrott and me (resend if we have it already) a configure script, a computer on which to demonstrate the problem, and an executable that demonstrates the problem?

**Comment by mhoemmen** [comment]
I think @crtrott has the benchmark -- did we commit it to Tpetra?

**Comment by mhoemmen** [comment]
I'm working on this now.  The idea is to link up with @tjfulle 's work on thread-parallel CrsMatrix pack and unpack, and then get rid of the "old" DistObject interface for good.

**Comment by mhoemmen** [comment]
I'm getting some funny debugging results that suggest that SEMS' build of OpenMPI might not be CUDA-aware.  In particular, I'm getting segfaults when I give CudaSpace buffers to `MPI_Send`, but not when I give CudaUVMSpace buffers to `MPI_Send`.

**Comment by mhoemmen** [comment]
@crtrott @ambrad Have you noticed this?  Should it actually be OK to give CudaSpace buffers to MPI?

**Comment by ibaned** [comment]
I've been wondering how to detect at compile time if MPI is CUDA-aware... that seems increasingly relevant

**Comment by mhoemmen** [comment]
@ibaned I would very much like that.  If it's _not_ CUDA-aware, it segfaults.  Not sure if I want Trilinos to get into the business of setting SIGSEGV handlers, though I think PETSc does or did that as a way to catch user error.

**Comment by mhoemmen** [comment]
OpenMPI 2.0.0 gives users a way to tell if it supports CUDA:

https://www.open-mpi.org/faq/?category=runcuda#mpi-cuda-aware-support

**Comment by ibaned** [comment]
Thanks for that link @mhoemmen !
Even if we can't set the default automatically yet, it certainly seems like portable code is going to need `#ifdef CUDA_AWARE_MPI` conditionals. I'd be interested in performance numbers if you find a proper CUDA-aware MPI and pass it device buffers.

**Comment by ambrad** [comment]
@mhoemmen, yes, giving CudaSpace pointers to MPI is valid if the MPI accepts it. Haven't used the SEMS MPI module for GPU builds.

**Comment by mhoemmen** [comment]
@ambrad wrote:
> Haven't used the SEMS MPI module for GPU builds.

That might explain it.... How hard is it to configure, say, OpenMPI 2.0.x for CUDA?

**Comment by ambrad** [comment]
@mhoemmen, no idea. I've never done it; I use the OpenMPI provided on the testbeds.

**Comment by mhoemmen** [comment]
@ambrad @crtrott Would you happen to know how I can report this issue to SEMS so they can fix their modules?

**Comment by ambrad** [comment]
@mhoemmen, maybe email @jgfouca.

**Comment by mhoemmen** [comment]
Thanks @ambrad !  I built my own OpenMPI 2.x with CUDA enabled and am building Trilinos with it now.  If it works, I'll file the SEMS issue.

**Comment by ibaned** [comment]
@mhoemmen can you post the OpenMPI configure options you used (especially if it works) ?

**Comment by mhoemmen** [comment]
OpenMPI also claims that, as of version 1.7.3, one can use the `ompi_info` executable to find out whether OpenMPI was built with CUDA support.  It tells me that the SEMS OpenMPI module (at least 1.10.1) was _not_ built with CUDA support:
```
$ which ompi_info
/projects/sems/install/rhel6-x86_64/sems/compiler/gcc/4.8.4/openmpi/1.10.1/bin/ompi_info
$ ompi_info --parsable --all | grep mpi_built_with_cuda_support:value
mca:mpi:base:param:mpi_built_with_cuda_support:value:false
```
Here is what I got with my custom OpenMPI 2.1.1 build, showing that does claim to have CUDA support:
```
$ ompi_info --parsable --all | grep mpi_built_with_cuda_support:value
mca:mpi:base:param:mpi_built_with_cuda_support:value:true
```

**Comment by mhoemmen** [comment]
@ibaned Here is how I configured OpenMPI 2.1.1:
```bash
#!/bin/bash

SRC_DIR=${HOME}/src/openmpi-2.1.1
INSTALL_DIR=${HOME}/pkg/openmpi-2.1.1-gcc-4.9.3-cuda-8.0.44

module purge
module load sems-env
module load kokkos-env
module load sems-gcc/4.9.3
module load kokkos-cuda/8.0.44

${SRC_DIR}/configure \
  --enable-mpi-ext=cuda \
  --with-cuda \
  --prefix=${INSTALL_DIR}
```

**Comment by mhoemmen** [comment]
Argh, I can't run any tests with this build yet, since I need to update the CUDA driver to match the run-time environment.  I'll work on that and then post results here.

**Comment by mhoemmen** [comment]
The commit above was just the midpoint of a string of commits leading to the proposed #1088 fix, that includes fixes for other issues.  I just wanted to get those out of the way, since they work now :-) .

I _should_ be able to test OpenMPI 2.1.1 with CUDA 7.5.18, which is a SEMS module and _does_ work on my workstation.  I rebuilt OpenMPI 2.1.1 with CUDA 7.5.18 and GCC 4.9.3 successfully, and am now rebuilding Trilinos with this version of OpenMPI.

**Comment by mhoemmen** [comment]
Trilinos build works with OpenMPI 2.1.1 and CUDA 7.5.18.  I'll try the new commits tomorrow.

**Comment by mhoemmen** [comment]
New commits pass tests!  Not quite done though -- I need to remove some debugging code and make sure that I didn't comment out anything important.

**Comment by mhoemmen** [comment]
#1571 blocks this, because the #1088 fix will break CUDA tests if the MPI is not CUDA aware.

**Comment by mhoemmen** [comment]
Recent Kokkos changes and merging with @tjfulle 's packCrsMatrix added some challenge to this task, but I'm making progress.

**Comment by mhoemmen** [comment]
I got Tpetra to pass tests with CUDA 8.0 and (CUDA-aware) OpenMPI 2.0.1.  I'm working on Stokhos now.

**Comment by mhoemmen** [comment]
Fixed in develop.
