### ISSUE TITLE
Framework:  PR builds taking upwards of a day to run since 2022-08-01

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#10899]
## Bug Report
@trilinos/framework 

### Internal issues

* [TRILINOSHD-182](https://sems-atlassian-son.sandia.gov/jira/servicedesk/customer/portal/7/TRILINOSHD-182)

### Description

As shown in [this query](https://trilinos-cdash.sandia.gov/index.php?project=Trilinos&begin=2022-08-01&end=2022-08-18&filtercount=1&showfilters=1&field1=groupname&compare1=61&value1=Pull%20Request) and sorting build time showing:

![image](https://user-images.githubusercontent.com/1959736/185430266-792be8c9-0cce-4af5-9ea3-c5543d0ad0d4.png)

you can see that some PR builds are taking upwards of a day (24 hours) to do the build.

Seems like PR builds should be set to timeout if they have been running too long.

**Comment by jhux2** [comment]
@bartlettroscoe Is the long compile cycle due to failures?   In general, I don't think it's reasonable to expect a successful PR compile cycle to take O(day).  Capping the time a PR can be tested is a good suggestion.

**Comment by bartlettroscoe** [comment]
> @bartlettroscoe Is the long compile cycle due to failures?

It does look like the cases of excessive time are related to build failures.  But then it is even more important to bug out and so other PRs can have their branches tested.
