### ISSUE TITLE
how to solve pressure Poisson equation with the FULL Neumann boundary condition

### ISSUE THREAD

**Issue by ztdepztdep** [trilinos/Trilinos#10895]
I'm trying to solve the pressure Poisson equation with the FULL Neumann boundary condition. Unfortunately, it leads to the sparse linear system equation Ax = b, where A is singular (because the Neumann BC in all boundaries). Could you please give me some advices about  how to solve it with AztecOO and ifpack. which preconditioner may i use to resolve the null space .

**Comment by cgcgcg** [comment]
If you want a scalable solver, you should use ML or MueLu. Both take a near-nullspace as an argument. At least MueLu has an option to handle the case where the near-nullspace is an actual nullspace.

**Comment by jhux2** [comment]
Closing as answered, please reopen if you have further questions.

**Comment by ztdepztdep** [comment]
> 

hello, I am trying ML, but how to add a near-nullspace as an argument into the ML.

**Comment by cgcgcg** [comment]
There are several options with the prefix "null space:".
