### ISSUE TITLE
Teuchos:  undefined functions

### ISSUE THREAD

**Issue by kliegeois** [trilinos/Trilinos#10892]
## Bug Report
@trilinos/teuchos 
@bartlettroscoe @cgcgcg 

### Description
It seems that there are 2 functions which are declared but are not defined in Teuchos:
- `make_char_nfa` is declared [here packages/teuchos/parser/src/Teuchos_FiniteAutomaton.hpp](https://github.com/trilinos/Trilinos/blob/master/packages/teuchos/parser/src/Teuchos_FiniteAutomaton.hpp#L66) and then defined [here packages/teuchos/parser/src/Teuchos_FiniteAutomaton.cpp](https://github.com/trilinos/Trilinos/blob/master/packages/teuchos/parser/src/Teuchos_FiniteAutomaton.cpp#L417) with a different signature. 
- `aboutBuild` is declared [here packages/teuchos/core/src/Teuchos_Utils.hpp](https://github.com/trilinos/Trilinos/blob/master/packages/teuchos/core/src/Teuchos_Utils.hpp#L64) and is not defined.

It looks like both of them could be remove.

This has been noticed when trying to import a shared library built using pybind11 of Teuchos from python.
It is strange that these undefined symbols have never been an issue up to today.

**Comment by bartlettroscoe** [comment]
> make_char_nfa is declared [here packages/teuchos/parser/src/Teuchos_FiniteAutomaton.hpp](https://github.com/trilinos/Trilinos/blob/master/packages/teuchos/parser/src/Teuchos_FiniteAutomaton.hpp#L66) and then defined [here packages/teuchos/parser/src/Teuchos_FiniteAutomaton.cpp](https://github.com/trilinos/Trilinos/blob/master/packages/teuchos/parser/src/Teuchos_FiniteAutomaton.cpp#L417) with a different signature.

CC: @ibaned 

> aboutBuild is declared [here packages/teuchos/core/src/Teuchos_Utils.hpp](https://github.com/trilinos/Trilinos/blob/master/packages/teuchos/core/src/Teuchos_Utils.hpp#L64) and is not defined.

This was code initially written by Kevin Long 20+ years ago which was just copied into that file.

Note that Trilinos really needs to be cleaned up and have all of the PR builds put on `-Wl,--no-undefined` for the creation of all libs.  That would ensure this never happens again.

@kliegeois, would you be willing to put in a PR to remove the undefined functions?

**Comment by kliegeois** [comment]
@bartlettroscoe sure, I am on it! Thanks!

**Comment by cgcgcg** [comment]
Fixed by #10894
