### ISSUE TITLE
Stratimikos support for Anasazi

### ISSUE THREAD

**Issue by aprokop** [trilinos/Trilinos#1089]
@trilinos/anasazi @amklinv @hkthorn 

If I am not mistaken, Stratimikos currently has not support for Anasazi. If that is correct, how difficult would adding such support be? What are the steps required to do that? Is there any missing functionality preventing it?

My hope that it may not be hard. The Stratimikos support for MueLu was not hard (and that's my only measuring bar).

**Comment by mhoemmen** [comment]
Wouldn't Thyra need a new "eigensolver" interface?  LinearOpWithSolve etc. are designed around linear solves.  You might be able to pass in the system, and get the eigenvectors out, but you would need a new interface to get the eigenvalues.

**Comment by hkthorn** [comment]
Linear solver interfaces and eigensolver interfaces are definitely different.  Stratimikos is designed for linear operator applications that either are or approximate A^{-1}, that does not relate the input-output relationship of an eigensolver.

**Comment by hkthorn** [comment]
There should have been a "to" in the previous comment:  "... that does not relate [to] the input-output relationship of an eigensolver."

**Comment by aprokop** [comment]
> You might be able to pass in the system, and get the eigenvectors out, but you would need a new interface to get the eigenvalues.

Good point. I've never worked with eigen-systems, and feel stupid for not realizing this issue.

The issue is obviously larger than any of us have time work on, so I'm closing it.
Thank you for quick replies.
