### ISSUE TITLE
error: ‘EpetraOperator’ is not a member of ‘MueLu’

### ISSUE THREAD

**Issue by ztdepztdep** [trilinos/Trilinos#10903]
Which header file should i include to make the MuelLu work with Epetra crs matrix.  I have included the following header file 
#include <Epetra_Operator.h>
#include <MueLu_Hierarchy.hpp>
#include <MueLu_EpetraOperator.hpp>
but it seems it doesn't work.

**Comment by cgcgcg** [comment]
`CreateEpetraPreconditioner` from MueLu_CreateEpetraPreconditioner.hpp should do the trick.

**Comment by jhux2** [comment]
> `CreateEpetraPreconditioner` from MueLu_CreateEpetraPreconditioner.hpp should do the trick.

@ztdepztdep MueLu has many tests and examples that demonstrate this, in particular muelu/tests/scaling/Driver.cpp`.  Also see https://docs.trilinos.org/dev/packages/muelu/doc/html/classes.html as well as the MueLu user guide in `Trilinos/packages/muelu/doc/UsersGuide/mueluguide.pdf`.

**Comment by jhux2** [comment]
Closing as answered, please reopen if necessary.
