### ISSUE TITLE
Set up automated testing with SuperLUDist enabled

### ISSUE THREAD

**Issue by ibaned** [trilinos/Trilinos#1091]
As pointed out in #410, #1083, and #1090, it would be valuable to have automated Trilinos testing that enables the SuperLUDist TPL.

@trilinos/framework

**Comment by ibaned** [comment]
As @bartlettroscoe points out, this requires adding SuperLUDist to the SEMS TPL mount.

**Comment by bartlettroscoe** [comment]
SuperLUDist could be added to the offical SEMS set of TPLs or someone could add a 'trilinos' project space and start adding its own TPL builds.   See:

* https://sems.sandia.gov/content/request-project-area-nfs-tpl-build-machines
* https://sems.sandia.gov/content/installing-project-tpl'

In fact, it is likely way past due for Trilinos.  Trilinos is not the only (or the most important) SEMS customer so Trilinos is going to need to take one some of this itself.

@jwillenbring, is something that one of the new Trilinos framework team members could take on?

Note that this is important for testing of the Stratimkos/Amesos (@trilinos/amesos) and Stratimikos/Amesos2 (@trilinos/amesos2) adapters.

**Comment by ZUUL42** [comment]
Tracing this a bit, but a fair amount of the links in those linked issues & PRs are dead.
What configuration options would we like to see added to which build?

Looking at what SuperLU modules I can load from SEMS currently, I'm seeing:
- sems-superlu/4.3/base *_loaded in all current builds_
- sems-superlu/5.2.1/base
- sems-superlu_dist/5.2.2/32bit_parallel
- sems-superlu_dist/5.2.2/64bit_parallel
Do we need updated versions? Or are some of these new from the last comment in 2017?

**Comment by jwillenbring** [comment]
@ZUUL42 These are new as of 2017. 

@ibaned is it still useful to try to set up a build with superlu_dist 5.2.2, or should we work with SEMS to get a newer version installed? We could try the old version very quickly. We might be waiting until we have the new SEMS TPL system in place before we would try an upgraded version.

**Comment by bartlettroscoe** [comment]
It would be good to add SuperLUDist testing with the same version being used by ATDM (current  SuperLUDist 5.4.0).  That would avoid problems like #8258.

**Comment by jwillenbring** [comment]
> It would be good to add SuperLUDist testing with the same version being used by ATDM (current SuperLUDist 5.4.0). That would avoid problems like #8258.

I will communicate this to the SEMS TPL 2.0 TPL team. Thanks.

**Comment by prwolfe** [comment]
Notes from first attempt to set this up in the intel 17 Pr build


1.  SuperLU and SuperLUDist cannot both be enabled. While this is fine, the fact that there is no indication to this end at configure time (and a very unclear one at compile time) is not good. We should makes this more user-friendly
2. The current sems install for both 64 bit and 32 bit requires openmp. Since we are not getting configure information for the super_dist library this is up to the user to find. Link order will also be important and is less than obvious. pulling in *Config.cmake and *Targets.cmake file from the install would be considerably more robust.

Is there anyone from the Amesos2 project that can help with item 1?

**Comment by jwillenbring** [comment]
@srajama1 Do you know who might be able to comment on @prwolfe 's comment:

> SuperLU and SuperLUDist cannot both be enabled. While this is fine, the fact that there is no indication to this end at configure time (and a very unclear one at compile time) is not good. We should makes this more user-friendly

**Comment by jwillenbring** [comment]
@prwolfe Any general updates on this? Is there a path forward for getting something in place, even if it is less than ideal?

**Comment by srajama1** [comment]
@jwillenbring : Do you just need a configure time error if both SuperLU and SuperLU_Dist are enabled ? Basically an if check in Cmake and throw an error or do you need something more complicated.

@ndellingwood Keeping this on your radar.

**Comment by prwolfe** [comment]
Jim,

I had run this before I left and found that there was a type mis-match between the installed libraries and what Trilinos expects. I was trying to trace down how Trilinios sets this up but did not get there yet.

Paul

From: James Willenbring ***@***.***>
Reply-To: trilinos/Trilinos ***@***.***>
Date: Thursday, March 25, 2021 at 1:35 PM
To: trilinos/Trilinos ***@***.***>
Cc: "Wolfenbarger, Paul R" ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [trilinos/Trilinos] Set up automated testing with SuperLUDist enabled (#1091)


@prwolfe<https://github.com/prwolfe> Any general updates on this? Is there a path forward for getting something in place, even if it is less than ideal?

**Comment by prwolfe** [comment]
I found a pair of issues today
* the 64bit version of superlu_dist will not compile against trilinos as it hard codes int_t as "long long" and amuses hard codes the data structures as "int"
* Using the 32bit libraries for superlu_dist requires passing -qopenmp at link time as they are compiled with openmp on

I am running testing now and should have a PR in the morning.

**Comment by prwolfe** [comment]
Last nights build failed on the issue in #5472. I have re-started the build. It will likely be Friday before I get back to the results.

**Comment by jwillenbring** [comment]
With #8947 merged, I am closing this.
