### ISSUE TITLE
Framework:  Jenkins PR driver down and skipping of odd-numbered PRs starting 2022-08-16

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#10917]
## Bug Report
@trilinos/framework

### Internal Issues
* [TRILINOSHD-186](https://sems-atlassian-son.sandia.gov/jira/servicedesk/customer/portal/7/TRILINOSHD-186)

### Description
The  Jenkins PR tester driver became inoperable starting 2022-08-16 as explained in  https://github.com/trilinos/Trilinos/issues/10858#issuecomment-1221454400.  As a result, only even-numbered PRs have been getting testing resulting in a large backup of odd-numbered PRs waiting many days to get tested (currently 8 as shown in [this PR query](https://github.com/trilinos/Trilinos/pulls?q=is%3Aopen+is%3Apr+label%3A%22AT%3A+RETEST%22)).

### Steps to Reproduce
Look at:

* https://do.sandia.gov/trilinos-ci/job/Trilinos_autotester_driver_inst_1/

**Comment by tasmith4** [comment]
@bartlettroscoe can you "share" that internal issue with me?  I'll also note https://github.com/trilinos/Trilinos/pull/10851 appears to be bit by this issue as well although it does not show up in your query -- I don't have RETEST on it since it passed already, but apparently even though it is approved and passing tests, it needs the autotester to circle back before it can merge ...

**Comment by bartlettroscoe** [comment]
@tasmith4 

> @bartlettroscoe can you "share" that internal issue with me?

Done.  See [TRILINOSHD-186](https://sems-atlassian-son.sandia.gov/jira/servicedesk/customer/portal/7/TRILINOSHD-186)

> I'll also note #10851 appears to be bit by this issue as well although it does not show up in your query -- I don't have RETEST on it since it passed already, but apparently even though it is approved and passing tests, it needs the autotester to circle back before it can merge ...

Correct.

**Comment by bartlettroscoe** [comment]
Looks like "Instance 1" is running again just now:

* https://do.sandia.gov/trilinos-ci/job/Trilinos_autotester_driver_inst_1/3955/consoleFull

@e10harvey closed [TRILINOSHD-186](https://sems-atlassian-son.sandia.gov/jira/servicedesk/customer/portal/7/TRILINOSHD-186).

**Comment by jhux2** [comment]
Were the number of test lanes always so low, or were they reduced over time due to resource contention?

**Comment by bartlettroscoe** [comment]
> Were the number of test lanes always so low, or were they reduced over time due to resource contention?

@jhux2, from looking at:

* https://do.sandia.gov/trilinos-ci/

it appears they had as many as 4 of these `Trilinos_autotester_driver_inst_<idx>` jobs running at one time.

**Comment by tasmith4** [comment]
> The solution to this problem is the create a dummy even-numbered PR with a new branch name but same commits and that will get tested right away (because there are currently no even-numbered PRs in the queue waiting to be tested).

@bartlettroscoe I tried this with #10851, but the new even-numbered PR #10920 also seems to be ignored by the autotester.  Where can I check the queues to see what's running and why my new one is also blocked?  I visited the Jenkins page but wasn't sure exactly where to look for this info.

**Comment by bartlettroscoe** [comment]
> @bartlettroscoe I tried this with https://github.com/trilinos/Trilinos/pull/10851, but the new even-numbered PR https://github.com/trilinos/Trilinos/pull/10920 also seems to be ignored by the autotester. Where can I check the queues to see what's running and why my new one is also blocked? I visited the Jenkins page but wasn't sure exactly where to look for this info.

@tasmith4, you can see the most recent runs of the two PR drivers shown at:

* https://do.sandia.gov/trilinos-ci/job/Trilinos_autotester_driver_inst_0/4590/consoleFull
* https://do.sandia.gov/trilinos-ci/job/Trilinos_autotester_driver_inst_1/3955/consoleFull

That PR ID 10920 is not even listed in that output.

I think the reason it did not test PR #10920 is because that PR target for PR #10920 is 'master' instead of 'develop'.  Please change the target branch of PR #10920 to 'develop' and it should get tested.

**Comment by tasmith4** [comment]
> I think the reason it did not test PR https://github.com/trilinos/Trilinos/pull/10920 is because that PR target for PR https://github.com/trilinos/Trilinos/pull/10920 is 'master' instead of 'develop'.

Wow.  Don't know how I missed that ... thanks. :)

**Comment by cgcgcg** [comment]
@bartlettroscoe Do I need to do anything to get an odd-numbered PR scheduled for testing now? #10905 has been sitting idle for 5 days.

**Comment by bartlettroscoe** [comment]
> @bartlettroscoe Do I need to do anything to get an odd-numbered PR scheduled for testing now? #10905 has been sitting idle for 5 days.

@cgcgcg, odd-numbered PRs are being tested again.  See [above](https://github.com/trilinos/Trilinos/issues/10917#issuecomment-1224299528).  From the latest Jenkins output, it is currently testing PR #10827.  The problem is that there is a big backlog of odd-numbered PRs waiting to be tested.  From what I can figure out just looking at the autotester output on Jenkins, looking at the current odd-numbered PRs with `AT: RETEST` listed [here](https://github.com/trilinos/Trilinos/pulls?q=is%3Aopen+is%3Apr+label%3A%22AT%3A+RETEST%22), it looks like there are 4 odd-numbered PRs ahead of #10905.  I don't know the exact logic for selecting what PRs to test (because I have never seen the autotester code), but it sure looks to me like it is just iterating over the PRs in ascending integer ID order and picking the first PR that meets the testing criteria.  (So if the odd-numbered PRs with lower IDs have `AT: RETEST` set on them over and over before the autotester loops around again and they continue to fail, then the later PRs will never get tested).  You will have to ask the @trilinos/framework team for more info.

**Comment by jhux2** [comment]
> > Were the number of test lanes always so low, or were they reduced over time due to resource contention?
> 
> @jhux2, from looking at:
> 
>     * https://do.sandia.gov/trilinos-ci/
> 
> 
> it appears they had as many as 4 of these `Trilinos_autotester_driver_inst_<idx>` jobs running at one time.

As things stabilize, perhaps Framework could try increasing the lanes, even by one.

**Comment by bartlettroscoe** [comment]
See, creating the even-numbered PR #10920 caused it to be tested right away and once it was approved and merged, GitHub is automatically showing the identical PR branch #10851 as merged.

**Comment by bartlettroscoe** [comment]
Odd-numbered PRs are definitely getting tested again as shown [here](https://trilinos-cdash.sandia.gov/index.php?project=Trilinos&date=2022-08-24&filtercount=1&showfilters=1&field1=groupname&compare1=61&value1=Pull%20Request) which shows the testing of PR #10829 [here](https://trilinos-cdash.sandia.gov/index.php?project=Trilinos&date=2022-08-24&filtercount=2&showfilters=1&filtercombine=and&field1=groupname&compare1=61&value1=Pull%20Request&field2=buildname&compare2=65&value2=PR-10829) showing:

![image](https://user-images.githubusercontent.com/1959736/186522156-5a04a656-1f3b-49ea-8df9-6ef4457dba6a.png)

Closing this as complete.
