### ISSUE TITLE
STK:  Cannot find stk_coupling/impl_NamedValues.hpp

### ISSUE THREAD

**Issue by hillyuan** [trilinos/Trilinos#10910]
## Bug Report
@trilinos/\<STK\>

### Description
On WSL Ubuntu with gcc 9.4.0, following compile error arise When STK_ENABLE_TESTS turns on

>stk_unit_tests/stk_coupling/UnitTestNamedValues.cpp:39:10: fatal error: stk_coupling/impl_NamedValues.hpp: No >such file or directory
>   39 | #include <stk_coupling/impl_NamedValues.hpp>

### Steps to Reproduce
  Attached is my configure script.
[configure.txt](https://github.com/trilinos/Trilinos/files/9387108/configure.txt)

  I have checked contents of the file Trilinos\build\packages\stk\stk_unit_tests\stk_coupling\CMakeFiles\stk_coupling_utest.dir\flags.make
[flags.make.txt](https://github.com/trilinos/Trilinos/files/9387113/flags.make.txt)
and found that directory
> packages/stk/stk_coupling

where file stk_coupling/impl_NamedValues.hpp exists, is not included in its CXX_INCLUDES definition. I think it is the reason why the above compile error occurs.

**Comment by alanw0** [comment]
Thanks for the bug report, we believe there is also a similar error in the unit-tests for stk_simd. We will try to fix this as soon as possible.

**Comment by alanw0** [comment]
@hillyuan we haven't figured out what the problem is yet, but it seems as though if you turn on Trilinos_ENABLE_TESTS, then the STK tests build successfully. We'll keep you posted if we figure out what the real problem is.

**Comment by hillyuan** [comment]
This error is cleared after commit cfe07c4fc18b49d08243bf43e6d9a4c747a6b1fe
