### ISSUE TITLE
MueLu:  cmake error

### ISSUE THREAD

**Issue by glhenni** [trilinos/Trilinos#10925]
## Bug Report
@trilinos/\<MueLu\>

Not sure if this is a muelu error or a tribits error (@bartlettroscoe ?) but all our tests failed last night with:
```
Processing enabled package: MueLu (Libs)
-- MueLu: Enabling deprecated code
-- MueLu's tutorial requires for a correct build that if Tpetra is enabled, then GlobalOrdinal=int must be enabled, and either the Serial or OpenMP Nodes in Tpetra be enabled.  Since this is not the case, I am disabling MueLu's tutorial by default.  See Trilinos GitHub Issue #1726 for details: https://github.com/trilinos/Trilinos/issues/1726
CMake Error at /scratch/charonops/jenkins/workspace/ASCIC_Build_Farm_Heavy_CDE-GNU-opt/TriBITS/tribits/core/package_arch/TribitsAddOptionAndDefine.cmake:78 (tribits_pkg_export_cache_var):
  tribits_pkg_export_cache_var Macro invoked with incorrect arguments for
  macro named: tribits_pkg_export_cache_var
Call Stack (most recent call first):
  Trilinos/packages/muelu/CMakeLists.txt:166 (TRIBITS_ADD_OPTION_AND_DEFINE)


-- You chose to enable MueLu's tutorial, even though I told you that it may not build correctly.  You are responsible for whatever build or link errors may occur as a result.
```

**Comment by cgcgcg** [comment]
@trilinos/muelu

**Comment by bartlettroscoe** [comment]
@glhenni, I discovered this last night.  I am about to post the PR to fix this.

**Comment by bartlettroscoe** [comment]
NOTE: This is using the 'master' version of TriBITS which is not in Trilinos 'develop' yet.

**Comment by bartlettroscoe** [comment]
@glhenni, PR https://github.com/TriBITSPub/TriBITS/pull/521 just merged and it accidentally closed this issue because I put "Fixes trilinos/Trilinos#10925" in the text.

Please reopen this issue if you still find your Trilinos build is broken but I am pretty sure this should fix the issue.

**Comment by bartlettroscoe** [comment]
> Historically we've used tribits outside of trilinos, checking it out separately. TBH, I'm not exactly sure why. In this case once you fix it in Tribits/master we'll be good, so it works in our favor in this case.

@glhenni, there are pros and cons to using the tip of TriBITS 'master' with Trilinos (or any TriBITS project).  I will try to remember that Charon is pulling the tip of TriBITS 'master' and do more testing against Trilinos before pushing to TriBITS 'master' in the future.

**Comment by glhenni** [comment]
Everything is back up and running Ross. Really appreciate your speed in fixing it! Thank you.
