### ISSUE TITLE
Do we have a API to test if a Epetra CSR matris  is symetry?

### ISSUE THREAD

**Issue by ztdepztdep** [trilinos/Trilinos#10933]
Do we have a API to test if a Epetra CSR matris  is symetry so I can use CG to solve the Ax=b.

**Comment by cgcgcg** [comment]
CG needs the matrix to be symmetric positive definite. Checking for these properties is pretty expensive. I don't think we have such methods, as the user normally knows these properties anyway.

**Comment by cgcgcg** [comment]
Closing. Please re-open if this isn't resolved.
