### ISSUE TITLE
How to add a value every component to a CSR matrix A

### ISSUE THREAD

**Issue by ztdepztdep** [trilinos/Trilinos#10939]
I want to and "1" to every entry of the epetra CSR matrix A, could you please give me some suggetsions.

**Comment by csiefer2** [comment]
There's no elegant way to do this, sadly.  "Grab the values pointer and loop through it adding 1" would be the most efficient.

**Comment by cgcgcg** [comment]
Closing. Please re-open if this isn't resolved.
