### ISSUE TITLE
Pliris: Pliris tests failing in PR ATS2 CUDA build which should not even be running

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#10931]
## Bug Report
@trilinos/framework

### Internal Issues:

* [TRILINOSHD-192](https://sems-atlassian-son.sandia.gov/jira/servicedesk/customer/portal/7/TRILINOSHD-192)

### Description

So it seems that Pliris tests:

* `Pliris_vector_random_MPI_3`
* `Pliris_vector_random_MPI_4`

are failing the PR CUDA build:

* `ats2_cuda-10.1.243-gnu-8.3.1-spmpi-rolling_release_static_Volta70_Power9_no-asan_no-complex_no-fpic_mpi_pt_no-rdc_uvm_deprecated-on_no-package-enables`

as shown [here](https://trilinos-cdash.sandia.gov/viewTest.php?onlyfailed&buildid=407883) for PR #10930.

This is the first time these Pliris tests have ever been run in this ATS2 PR build in all recorded history as shown in [this index.php query](https://trilinos-cdash.sandia.gov/index.php?project=Trilinos&begin=2022-08-01&end=2022-08-25&filtercount=5&showfilters=1&filtercombine=and&field1=groupname&compare1=61&value1=Pull%20Request&field2=buildname&compare2=63&value2=cuda&field3=subprojects&compare3=93&value3=Pliris&field4=testsduration&compare4=43&value4=0&field5=block&field5count=2&field5field1=testspassed&field5compare1=43&field5value1=0&field5field2=testsfailed&field5compare2=43&field5value2=0) showing:

![image](https://user-images.githubusercontent.com/1959736/186690571-0019e72d-4f10-4411-b5b6-2cbc97d0d519.png)

and in [this queryTests.php query](https://trilinos-cdash.sandia.gov/queryTests.php?project=Trilinos&begin=2022-04-01&end=2022-08-25&filtercount=3&showfilters=1&filtercombine=and&field1=groupname&compare1=61&value1=Pull%20Request&field2=buildname&compare2=63&value2=ats2_cuda-10.1.243-gnu-8.3.1-spmpi-rolling_release_static_Volta70_Power9_no-asan_no-complex_no-fpic_mpi_pt_no-rdc_uvm_deprecated-on_no-package-enables&field3=testname&compare3=65&value3=Pliris) showing:

![image](https://user-images.githubusercontent.com/1959736/186690736-c18ddfd6-363f-4b40-a9ff-16975804c1f7.png)

However, these tests are explicitly disabled in the PR CUDA build:

* `rhel7_sems-cuda-11.4.2-sems-gnu-10.1.0-sems-openmpi-4.0.5_release_static_Volta70_no-asan_complex_no-fpic_mpi_pt_no-rdc_no-uvm_deprecated-on_no-package-enables-482

as shown [here](https://trilinos-cdash.sandia.gov/build/407755/configure) showing:

```
Processing enabled package: Pliris (Libs, Tests, Examples)
     Building the double precision(default) library
-- Pliris_vector_random_MPI_3: NOT added test because Pliris_vector_random_MPI_3_DISABLE='ON'!
-- Pliris_vector_random_MPI_4: NOT added test because Pliris_vector_random_MPI_4_DISABLE='ON'!
```

### Steps to Reproduce

Follow instructions at:

* https://github.com/trilinos/Trilinos/wiki/Addressing-test-failures

**Comment by bartlettroscoe** [comment]
So how is it that PR #10930 is the first time these Pliris tests have even been run for the ATS2 CUDA PR build even when `Trilinos_ENABLE_ALL_PACKAGES=ON`?  Looking at the last PR of mine that ran that enabled all packages was on 2022-08-12 for PR #10813:

* [PR-10813-test-ats2_cuda-10.1.243-gnu-8.3.1-spmpi-rolling_release_static_Volta70_Power9_no-asan_no-complex_no-fpic_mpi_pt_no-rdc_uvm_deprecated-on_no-package-enables-866](https://trilinos-cdash.sandia.gov/index.php?project=Trilinos&parentid=369130&filtercount=1&showfilters=1&field1=buildstarttime&compare1=84&value1=NOW&filtercombine=and)

Looking at the configure output for that PR build [here](https://trilinos-cdash.sandia.gov/build/369130/configure), we see:

```
-- Setting Trilinos_ENABLE_ALL_PACKAGES = ON

...


Final set of non-enabled packages:  Pliris Komplex TriKota Compadre Moertel PyTrilinos NewPackage 7

Final set of non-enabled SE packages:  Pliris ... 23
```

The `Trilinos/PackagesList.cmake` file shows:

```
  Pliris                packages/pliris                   ST
```

So why is Pliris getting disabled on that build?  The GenConfig fragment file for that build [generatedPRFragment.cmake](https://trilinos-cdash.sandia.gov/upload/95cd2ab265494b30e24c1d9dd4468a0e1262265d/generatedPRFragment.cmake) shows:

```
set(Trilinos_ENABLE_SECONDARY_TESTED_CODE OFF CACHE BOOL "from .ini configuration")
```

So that ATS2 PR build is only testing Primary Tested code and not Secondary Tested code?

So an ST package like Pliris will only get enabled if it is explicitly enabled, in this case, because I touched the file `packages/pliris/CMakeLists.txt`.

Looking at the file:

* `packages/framework/ini-files/config-specs.ini`

we see:

```
[USE-PT|YES]
opt-set-cmake-var Trilinos_ENABLE_SECONDARY_TESTED_CODE BOOL : OFF

[USE-PT|NO]
opt-set-cmake-var Trilinos_ENABLE_SECONDARY_TESTED_CODE BOOL : ON
```

and:

```
[ats2_cuda-10.1.243-gnu-8.3.1-spmpi-rolling_release_static_Volta70_Power9_no-asan_no-complex_no-fpic_mpi_pt_no-rdc_uvm_deprecated-on_no-package-enables]
...
use USE-PT|YES
...
```

So it seems that the only PR builds that have `Trilinos_ENABLE_SECONDARY_TESTED_CODE=OFF` are the ATS2 builds.  Why?

**Comment by bartlettroscoe** [comment]
There are a few ways to fix this problem but given that they are trying to get rid of this ATS2 build, the simplest thing is likely to just force disable Pliris in the ATS2 builds.  You should not even be enabling Pliris in any ATS2 build because it will not be enabled unless someone actually changes a file in Pliris.  So that is what I will do in PR #10930.

**Comment by bartlettroscoe** [comment]
FYI: I have disabled these tests in PR #10930 in some new commits I pushed just now.

**Comment by bartlettroscoe** [comment]
With the merge of PR #10930, Pliris is now disabled in the ATS2 PR build.  Therefore, I will put `Disabled Tests` label on this issue and keep it open in case someone wants to fix this.  If there is no chance this will ever get fixed, then please close it.

**Comment by e10harvey** [comment]
> So it seems that the only PR builds that have `Trilinos_ENABLE_SECONDARY_TESTED_CODE=OFF` are the ATS2 builds. Why?

The answer here may be lost. This was ported over from the old PR infrastructure. Would the addition of a "seconday tested (st) config option in `ats2_cuda-10.1.243-gnu-8.3.1-spmpi-rolling_release_static_Volta70_Power9_no-asan_no-complex_no-fpic_mpi_pt_no-rdc_uvm_deprecated-on_no-package-enables` clear this up?

We would then have:
`ats2_cuda-10.1.243-gnu-8.3.1-spmpi-rolling_release_static_Volta70_Power9_no-asan_no-complex_no-fpic_mpi_pt_no-st_no-rdc_uvm_deprecated-on_no-package-enables`

**Comment by sebrowne** [comment]
@bartlettroscoe can we call this closed since ATS2 is gone as far as PR/MM testing are concerned?

**Comment by bartlettroscoe** [comment]
Since ats2 PR build is gone, this is a non-issue.
