### ISSUE TITLE
Does the  Diagonal Perturbations of AzetecOO support the singular matrix A when all Neumann bcs for laplacian problem. 

### ISSUE THREAD

**Issue by ztdepztdep** [trilinos/Trilinos#10934]
When I solve the pressure equation in incompressible flow , the matrix A is a singular matrix since all 4 bcs are Neumann bc, 
I want to know that does the  Diagonal Perturbations of AzetecOO support this kind of bc or do we have other techniques to solve this kind of problems.

**Comment by jhux2** [comment]
@trilinos/aztecoo
