### ISSUE TITLE
MueLu: Tests "MueLu_Structured_Region_Linear*" fail on geminga and enigma, deviation from gold file

### ISSUE THREAD

**Issue by jhux2** [trilinos/Trilinos#10948]
## Bug Report
@trilinos/muelu 

### Description

Linux-sems-gcc-8.3.0-SEMS-OPENMPI-4.0.5_RELEASE_NO-EPETRA_NO-INT_COMPLEX_NO-SERIAL_OPENMP_EXPERIMENTAL 
https://testing.sandia.gov/cdash/viewTest.php?onlyfailed&buildid=11222478

Linux-sems-gcc-8.3.0-SEMS-OPENMPI-4.0.5_RELEASE_NO-SERIAL_OPENMP_COMPLEX_EXPERIMENTAL 
https://testing.sandia.gov/cdash/viewTest.php?onlyfailed&buildid=11223713

Linux-sems-gcc-8.3.0-SEMS-OPENMPI-4.0.5_RELEASE_NO-EPETRA_NO-INT_COMPLEX_EXPERIMENTAL 
https://testing.sandia.gov/cdash/viewTest.php?onlyfailed&buildid=11223849

Linux-sems-gcc-8.3.0-SEMS-OPENMPI-4.0.5_RELEASE_NO-EPETRA_NO-SERIAL_OPENMP_EXPERIMENTAL 
https://testing.sandia.gov/cdash/viewTest.php?onlyfailed&buildid=11222696

Errors like the following:
```
Number of iterations: OK
Using relative error
Residual in iteration 0: OK
Using relative error
Residual in iteration 1: WRONG -- deviation from value in gold file.
End Result: TEST FAILED
```

**Comment by GrahamBenHarper** [comment]
I believe this is related to #9377

**Comment by pohm01** [comment]
After a little investigation, it seems that the initial starting vector is different is different on different builds.

Looking specifically at Linear_Brick3D_Tpetra_MPI_4_regression:
I have two builds on enigma, a serial build that passes and an openmp build that fails. The starting vector between the two builds is not the same. The interesting thing is that the first 128 entries on each rank are the same, and then the remaining 122 entries are different (1000 dofs, 250 on each rank).

So maybe something weird with the random vector generation.

**Comment by pohm01** [comment]
As suggested by @cgcgcg, using the xpetra randomize() implementation fixes the differences in the random starting vectors.

Should I make a PR for the test driver and rerun the gold files to use the xpetra randomize?

**Comment by mayrmt** [comment]
@pohm01 Sounds like this would make the tests more robust. Feel free to make the changes.

**Comment by GrahamBenHarper** [comment]
That's great. Thanks so much!

**Comment by jhux2** [comment]
This has been fixed.  [evidence](https://testing.sandia.gov/cdash/index.php?project=Trilinos&subproject=MueLu&begin=2022-09-14&end=2022-09-15&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=63&value1=Linux-sems-gcc-8.3.0-SEMS-OPENMPI-4.0.5_RELEASE_NO-SERIAL_OPENMP_COMPLEX_EXPERIMENTAL&field2=groupname&compare2=61&value2=Experimental)

<img width="1518" alt="Screen Shot 2022-09-19 at 2 11 19 PM" src="https://user-images.githubusercontent.com/12970120/191107750-b54a4cf0-5beb-484e-9ff4-b2da731fd6a8.png">
