### ISSUE TITLE
MueLu: nightly failures on stria (but no test output)

### ISSUE THREAD

**Issue by jhux2** [trilinos/Trilinos#10942]
## Bug Report
@trilinos/muelu

### Description
Trilinos-atdm-van1-tx2_arm-20.1_openmpi-4.0.5_openmp_static_opt 
https://testing.sandia.gov/cdash/viewTest.php?onlyfailed&buildid=11223002

Failures reported, but no test output is available.

<img width="422" alt="Screen Shot 2022-08-29 at 11 29 38 AM" src="https://user-images.githubusercontent.com/12970120/187272588-33ce50be-1235-46bd-b39d-46e9d5418748.png">

**Comment by GrahamBenHarper** [comment]
I'll handle the `VarDofDriverEmin` test. Some of those functionalities are a little fragile and not intended to be run on varying architectures. I think it also shows up on some of the other nightly testsuites.

**Comment by jhux2** [comment]
@GrahamBenHarper See #10944.

**Comment by jhux2** [comment]
The tests pass/fail randomly, and when they fail, there's no output.  The graph of pass/fail indicates mostly passing, so I'm inclined to think this is a platform issue.
