### ISSUE TITLE
Muelu / IntrepidPCoarsenFactory tests depend on the serial execution space

### ISSUE THREAD

**Issue by jjellio** [trilinos/Trilinos#1094]
Hi!

I have a build that is OpenMP only, and the unit tests from `IntrepidPCoarsenFactory.cpp` want to explicitly use `Kokkos::Serial`.

This causes a compile time error, since the type is undefined. I've temporarily disabled these.

It looks like the tests wants to ensure determinism:
`  void testUniqueNumbering(Teuchos::FancyOStream &out, bool &success)`

This one looks to ensure things are numbered correctly... which should be good to test w/threads.
`  void testBuildSampleElementToNodeMapThreeElementQuad(Teuchos::FancyOStream &out, bool &success)
`

I've temporarily changed them to use `Kokkos::DefaultExecutionSpace`, which should allow my build to finish.

@trilinos/intrepid2 @trilinos/muelu @kyungjoo-kim

**Comment by jhux2** [comment]
@nateroberts

**Comment by jhux2** [comment]
> I have a build that is OpenMP only, and the unit tests from IntrepidPCoarsenFactory.cpp want to explicitly use Kokkos::Serial.
> 
> This causes a compile time error, since the type is undefined. I've temporarily disabled these.

@nateroberts Can you have a look at this issue?

**Comment by jhux2** [comment]
@CamelliaDPG Thanks for looking at this so quickly!

**Comment by CamelliaDPG** [comment]
Just pushed a fix for this to develop: as suggested by @jjellio, replaced Kokkos::Serial with Kokkos::DefaultExecutionSpace.  Thanks for bringing this to our attention!

**Comment by mhoemmen** [comment]
btw if you really want to use Serial but don't want to build Tpetra for Serial, you can set those two options independently.
