### ISSUE TITLE
MueLu: failures on stria due to system error "An ORTE daemon has unexpectedly failed"

### ISSUE THREAD

**Issue by jhux2** [trilinos/Trilinos#10944]
## Bug Report
@trilinos/muelu 

### Description
Trilinos-atdm-van1-tx2_arm-20.1_openmpi-4.0.5_openmp_static_dbg 
https://testing.sandia.gov/cdash/viewTest.php?onlyfailed&buildid=11223573

Tests fail, either with empty output or errors like:
```
--------------------------------------------------------------------------
An ORTE daemon has unexpectedly failed after launch and before
communicating back to mpirun. This could be caused by a number
of factors, including an inability to create a connection back
to mpirun due to a lack of common network interfaces and/or no
route found between them. Please check network connectivity
(including firewalls and network routing requirements).
--------------------------------------------------------------------------
```

**Comment by jhux2** [comment]
Reported to Framework in TRILINOSHD-193.

**Comment by bartlettroscoe** [comment]
CC: @e10harvey 

@jhux2, apparently, the Trilinos framework team does not support the ATDM Trilinos configurations (and has not so for more than a year).

**Comment by jhux2** [comment]
Do any customers rely on stria?

**Comment by bartlettroscoe** [comment]
> Do any customers rely on stria?

The SPARC Trilinos integration builds depend on this build (as shown [here](https://sparc-cdash.sandia.gov/index.php?project=SPARC&filtercount=1&showfilters=1&field1=groupname&compare1=61&value1=Trilinos%20Integration)) and I suspect that EMPIRE uses the ATDM Trilinos `van1-tx2` configuration there as well but you would have to ask one of the EMPIRE developers (e.g. @rppawlo).

If you look at the [git history for the Trilinos/cmake/std/atdm/ directory](https://github.com/trilinos/Trilinos/commits/develop/cmake/std/atdm), you will see who has been maintaining them over the last year or so.  Some examples of developers who have made changes in the last year include @PhilMiller, @brian-kelley, @crtrott, and @ndellingwood.

**Comment by bartlettroscoe** [comment]
> yes - empire uses stria routinely for large scale runs.

Well, as you can see in [this query](https://testing.sandia.gov/cdash/index.php?project=Trilinos&begin=2022-01-01&end=2022-08-30&filtercount=3&showfilters=1&filtercombine=and&field1=groupname&compare1=62&value1=Experimental&field2=buildname&compare2=65&value2=Trilinos-atdm-&field3=buildname&compare3=63&value3=van1-tx2), there have been runtime problems starting testing day 2022-06-09.  But no one monitors these builds anymore so no one noticed.

**Comment by jhux2** [comment]
I was able to build Trilinos on stria using the ATDM mechanism.  The queues are paused until Thursday, but I able to run a MueLu unit test successfully on the login node.

**Comment by jhux2** [comment]
The MueLu unit tests all pass when I run them via `ctest` in a slurm batch script.

Whatever the problem is, it's intermittent and apparently not caused by Trilinos code itself.  As evidence, here's the Pass/Fail graph for the test `MueLu_SimpleTpetra_MPI_4`:

 
![pass-fail](https://user-images.githubusercontent.com/12970120/188024651-37ebf8e8-ca39-443d-ac73-4c46572e8a4d.png)


The test randomly fails with the message
```
--------------------------------------------------------------------------
An ORTE daemon has unexpectedly failed after launch and before
communicating back to mpirun. This could be caused by a number
of factors, including an inability to create a connection back
to mpirun due to a lack of common network interfaces and/or no
route found between them. Please check network connectivity
(including firewalls and network routing requirements).
--------------------------------------------------------------------------
```

**Comment by jhux2** [comment]
Note the OMP warning below.  @bartlettroscoe How would one set `OMP_PROC_BIND=false` for dashboard testing?

```
Kokkos::OpenMP::initialize WARNING: OMP_PROC_BIND environment variable not set
  In general, for best performance with OpenMP 4.0 or better set OMP_PROC_BIND=spread and OMP_PLACES=threads
  For best performance with OpenMP 3.1 set OMP_PROC_BIND=true
  For unit testing set OMP_PROC_BIND=false
Kokkos::OpenMP::initialize WARNING: OMP_PROC_BIND environment variable not set
  In general, for best performance with OpenMP 4.0 or better set OMP_PROC_BIND=spread and OMP_PLACES=threads
  For best performance with OpenMP 3.1 set OMP_PROC_BIND=true
  For unit testing set OMP_PROC_BIND=false
Kokkos::OpenMP::initialize WARNING: OMP_PROC_BIND environment variable not set
  In general, for best performance with OpenMP 4.0 or better set OMP_PROC_BIND=spread and OMP_PLACES=threads
  For best performance with OpenMP 3.1 set OMP_PROC_BIND=true
  For unit testing set OMP_PROC_BIND=false
Kokkos::OpenMP::initialize WARNING: OMP_PROC_BIND environment variable not set
  In general, for best performance with OpenMP 4.0 or better set OMP_PROC_BIND=spread and OMP_PLACES=threads
  For best performance with OpenMP 3.1 set OMP_PROC_BIND=true
  For unit testing set OMP_PROC_BIND=false
OpenMP Max Threads = 2
```

**Comment by bartlettroscoe** [comment]
>  @bartlettroscoe How would one set OMP_PROC_BIND=false for dashboard testing?

@jhux2, you should be able to set that env in the file:

* https://github.com/trilinos/Trilinos/blob/master/cmake/std/atdm/van1-tx2/environment.sh

**NOTE:** If we are going to keep maintaining these ATDM Trilinos configuration scripts, we should consider doing some of the refactorings in #8989.

**Comment by jhux2** [comment]
@bartlettroscoe  While looking at that file, I stumbled upon #10684, which refers to system changes on stria between June 7 and 9, the exact date that many test failures started ([query](https://testing.sandia.gov/cdash/index.php?project=Trilinos&begin=2022-01-01&end=2022-08-30&filtercount=3&showfilters=1&filtercombine=and&field1=groupname&compare1=62&value1=Experimental&field2=buildname&compare2=65&value2=Trilinos-atdm-&field3=buildname&compare3=63&value3=van1-tx2)).

If the ATDM scripts aren't how Trilinos should be built/tested going forward, I prefer not to invest any time in them.

**Comment by rppawlo** [comment]
FYI - EMPIRE is still using the ATDM scripts to build trilinos. There are plans to replace, but that is probably not going to happen anytime soon.

**Comment by bartlettroscoe** [comment]
The problem is that no one is paying attention to the automated ATDM Trilinos builds anymore and I don't know of any plan to cover these platforms and build configurations by the framework team anytime soon.
