### ISSUE TITLE
Trilinos: Clean up valgrind errors

### ISSUE THREAD

**Issue by csiefer2** [trilinos/Trilinos#10945]
Because we have some.  And they should go.

[Ye olde link](https://testing.sandia.gov/cdash/index.php?project=Trilinos&parentid=11182820)

MueLu: #10950

**Comment by cgcgcg** [comment]
@CamelliaDPG Addition of that flag did indeed fix all the Intrepid2 reports
https://testing.sandia.gov/cdash/index.php?project=Trilinos&parentid=11304108#!#%23DynamicAnalysis
Thanks!

**Comment by cgcgcg** [comment]
Last run: https://testing.sandia.gov/cdash/viewDynamicAnalysis.php?buildid=11435938
@jennloe
