### ISSUE TITLE
TeuchosComm Requires MPI v2 but this is not tested for at compile time.

### ISSUE THREAD

**Issue by jjellio** [trilinos/Trilinos#1097]
Reported by David Hysom,

`MPI_Comm_create_keyval` is an MPI2 function, if a user attempts to build with MPI-1, they will get atleast the error below (potentially others?). Is there a compile time check for the MPI spec the compiler supports? If not, attempting to compile a program with `MPI_Comm_create_keyval` could be an option.

```
packages/teuchos/comm/src/Teuchos_MpiReductionOpSetter.cpp:171:43: error: 'MPI_Comm_create_keyval' was not declared in this scope
                                 &key, NULL);
```

@trilinos/teuchos @trilinos/framework

**Comment by mhoemmen** [comment]
@jjellio Does David really want to be able to build with MPI 1, or would he accept using a nonancient MPI version if Teuchos did a configure-time error check?  MPI 2.0 has been out since 1997 (20 years) and I would really rather not promise MPI 1.x support unless somebody really needs it, but I wouldn't mind adding the check that tells people to use a more modern MPI.

**Comment by jjellio** [comment]
He resolved this by swapping to mvapich2. The default on his platform is MPI-1.

I think Trilinos should perform some type of check. I looked through the MPI header (mpi.h), and it does not appear to identify the spec the implementation conforms to.

**Comment by mhoemmen** [comment]
We could use either the MPI_VERSION macro at compile time (preferred), or the MPI_Get_version function at run time.

**Comment by jjellio** [comment]
@mhoemmen is MPI_VERSION reporting the MPI standard version, or the implementation's version? E.g., OpenMPI 1.10, MPT 7.4.2, etc.. I seem to recall seeing MPI_VERSION being the latter, not the former.

**Comment by mhoemmen** [comment]
Hm, we've been assuming the former, that MPI_VERSION tells us the major version of the MPI standard that the implementation implements.

**Comment by jjellio** [comment]
I am likely wrong. I rarely override the default MPI detection. If that is the case, then this is straightforward to implement I imagine.

The purpose of the issue is simply that there is a requirement for MPI-2, so it may as well be enforced

**Comment by mhoemmen** [comment]
I'm fixing this in develop now.  Check-in test script is running.  I just did it with `#error`, with an informative message that tells users that they need to use an MPI implementation with MPI_VERSION >= 2.

**Comment by mhoemmen** [comment]
I just pushed a fix to develop.
