### ISSUE TITLE
How to plot matrix structure to a jpg file

### ISSUE THREAD

**Issue by ztdepztdep** [trilinos/Trilinos#10987]
I want to output the epetra csr matrix to a jpg file. Could you please give me some help?
Regards

**Comment by cgcgcg** [comment]
You could write the matrix to matrix market format and then use scipy + matplotlib.

**Comment by csiefer2** [comment]
Or load the MM file matlab and use spy()

**Comment by ztdepztdep** [comment]
I don't have knowledge about python, I think trilinos has some api can do this job.


| |
Professor Ding、
|
|
***@***.***
|
---- Replied Message ----
| From | Christian ***@***.***> |
| Date | 9/4/2022 00:29 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [trilinos/Trilinos] How to plot matrix structure to a jpg file (Issue #10987) |

You could write the matrix to matrix market format and then use scipy + matplotlib.

**Comment by ztdepztdep** [comment]
ok , i wrote a plotmatrix program in my repo. 
hope this will help you.
