### ISSUE TITLE
how to perform the Cuthill– McKee ordering  for the csr matrix before a iterative solver. 

### ISSUE THREAD

**Issue by ztdepztdep** [trilinos/Trilinos#10988]

**Comment by jhux2** [comment]
@trilinos/zoltan2 @egboman @srajama1

**Comment by srajama1** [comment]
Please see
https://github.com/trilinos/Trilinos/blob/master/packages/zoltan2/test/core/order/ordering1.cpp

**Comment by jhux2** [comment]
Also see the Ifpack2 user guide in `packages/ifpack2/doc/UserGuide.

**Comment by srajama1** [comment]
Closing .. reopen or create new one if needed.
