### ISSUE TITLE
MueLu fails to compile on cuda

### ISSUE THREAD

**Issue by bathmatt** [trilinos/Trilinos#1098]
I'm seeing these errors when I try to compile MueLu

`
[ 87%] Building CXX object packages/muelu/src/CMakeFiles/muelu.dir/Utils/ExplicitInstantiation/MueLu_CoalesceDropFactory.cpp.o
/home/mbetten/Trilinos/Trilinos/packages/xpetra/src/Map/Xpetra_EpetraMap.hpp(655): warning: statement is unreachable

/home/mbetten/Trilinos/Trilinos/packages/xpetra/src/CrsGraph/Xpetra_CrsGraphFactory.hpp(114): error: object of abstract class type "Xpetra::TpetraCrsGraph<int, int, Xpetra::EpetraNode>" is not allowed:
            pure virtual function "Xpetra::CrsGraph<LocalOrdinal, GlobalOrdinal, Node>::computeGlobalConstants [with LocalOrdinal=int, GlobalOrdinal=int, Node=Xpetra::EpetraNode]" has no overrider

/home/mbetten/Trilinos/Trilinos/packages/xpetra/src/CrsGraph/Xpetra_CrsGraphFactory.hpp(114): error: no instance of overloaded function "Xpetra::rcp" matches the argument list
            argument types are: (<error-type>)

`

Here is a compile line, long as it is 

`cd /home/mbetten/builds/drekar/cuda/debug/packages/muelu/src && /projects/sems/install/rhel6-x86_64/sems/compiler/gcc/5.3.0/openmpi/1.10.1/bin/mpicxx    -I/home/mbetten/builds/drekar/cuda/debug -I/home/mbetten/Trilinos/Trilinos/packages/muelu/src -I/home/mbetten/Trilinos/Trilinos/packages/muelu/src/Graph -I/home/mbetten/Trilinos/Trilinos/packages/muelu/src/Graph/BrickAggregation -I/home/mbetten/Trilinos/Trilinos/packages/muelu/src/Graph/UncoupledAggregation -I/home/mbetten/Trilinos/Trilinos/packages/muelu/src/Graph/UserAggregation -I/home/mbetten/Trilinos/Trilinos/packages/muelu/src/Headers -I/home/mbetten/Trilinos/Trilinos/packages/muelu/src/Interface -I/home/mbetten/Trilinos/Trilinos/packages/muelu/src/Interface/FacadeClasses -I/home/mbetten/Trilinos/Trilinos/packages/muelu/src/Misc -I/home/mbetten/Trilinos/Trilinos/packages/muelu/src/MueCentral -I/home/mbetten/Trilinos/Trilinos/packages/muelu/src/Rebalancing -I/home/mbetten/Trilinos/Trilinos/packages/muelu/src/Smoothers -I/home/mbetten/Trilinos/Trilinos/packages/muelu/src/Transfers/BaseClass -I/home/mbetten/Trilinos/Trilinos/packages/muelu/src/Smoothers/BlockedSmoothers -I/home/mbetten/Trilinos/Trilinos/packages/muelu/src/Transfers/BlockedTransfers -I/home/mbetten/Trilinos/Trilinos/packages/muelu/src/Transfers/Generic -I/home/mbetten/Trilinos/Trilinos/packages/muelu/src/Transfers/Energy-Minimization -I/home/mbetten/Trilinos/Trilinos/packages/muelu/src/Transfers/Energy-Minimization/Solvers -I/home/mbetten/Trilinos/Trilinos/packages/muelu/src/Transfers/Geometric-Interpolation -I/home/mbetten/Trilinos/Trilinos/packages/muelu/src/Transfers/Smoothed-Aggregation -I/home/mbetten/Trilinos/Trilinos/packages/muelu/src/Transfers/Petrov-Galerkin-SA -I/home/mbetten/Trilinos/Trilinos/packages/muelu/src/Transfers/User -I/home/mbetten/Trilinos/Trilinos/packages/muelu/src/Transfers/SemiCoarsen -I/home/mbetten/Trilinos/Trilinos/packages/muelu/src/Utils -I/home/mbetten/Trilinos/Trilinos/packages/muelu/src/Utils/ForwardDeclaration -I/home/mbetten/Trilinos/Trilinos/packages/muelu/src/../adapters/epetra -I/home/mbetten/Trilinos/Trilinos/packages/muelu/src/../adapters/tpetra -I/home/mbetten/Trilinos/Trilinos/packages/muelu/src/Transfers/PCoarsen -I/home/mbetten/builds/drekar/cuda/debug/packages/muelu/src -I/home/mbetten/builds/drekar/cuda/debug/packages/intrepid2/refactor/src -I/home/mbetten/Trilinos/Trilinos/packages/intrepid2/refactor/src/Cell -I/home/mbetten/Trilinos/Trilinos/packages/intrepid2/refactor/src/Discretization/Basis -I/home/mbetten/Trilinos/Trilinos/packages/intrepid2/refactor/src/Discretization/FunctionSpaceTools -I/home/mbetten/Trilinos/Trilinos/packages/intrepid2/refactor/src/Discretization/Integration -I/home/mbetten/Trilinos/Trilinos/packages/intrepid2/refactor/src/Orientation -I/home/mbetten/Trilinos/Trilinos/packages/intrepid2/refactor/src/Shared -I/home/mbetten/Trilinos/Trilinos/packages/intrepid2/refactor/src -I/home/mbetten/builds/drekar/cuda/debug/packages/shards/src -I/home/mbetten/Trilinos/Trilinos/packages/shards/src -I/home/mbetten/builds/drekar/cuda/debug/packages/sacado/src -I/home/mbetten/Trilinos/Trilinos/packages/sacado/src -I/home/mbetten/Trilinos/Trilinos/packages/sacado/src/template -I/home/mbetten/Trilinos/Trilinos/packages/sacado/src/parameter -I/home/mbetten/Trilinos/Trilinos/packages/sacado/src/mpl -I/home/mbetten/builds/drekar/cuda/debug/packages/teuchos/kokkoscomm/src -I/home/mbetten/Trilinos/Trilinos/packages/teuchos/kokkoscomm/src -I/home/mbetten/builds/drekar/cuda/debug/packages/teuchos/kokkoscompat/src -I/home/mbetten/Trilinos/Trilinos/packages/teuchos/kokkoscompat/src -I/home/mbetten/Trilinos/Trilinos/packages/teuchos/parameterlist/src -I/home/mbetten/builds/drekar/cuda/debug/packages/teuchos/core/src -I/home/mbetten/Trilinos/Trilinos/packages/teuchos/core/src -I/home/mbetten/builds/drekar/cuda/debug/packages/kokkos/core/src -I/home/mbetten/Trilinos/Trilinos/packages/kokkos/core/src -I/usr/local/cuda/include -I/projects/sems/install/rhel6-x86_64/sems/tpl/boost/1.59.0/gcc/5.3.0/base/include -I/projects/sems/install/rhel6-x86_64/sems/tpl/yaml_cpp/0.5.3/gcc/5.3.0/base/include -I/home/mbetten/Trilinos/Trilinos/packages/teuchos/comm/src -I/home/mbetten/Trilinos/Trilinos/packages/teuchos/remainder/src -I/home/mbetten/builds/drekar/cuda/debug/packages/teuchos/remainder/src -I/home/mbetten/Trilinos/Trilinos/packages/teuchos/numerics/src -I/home/mbetten/builds/drekar/cuda/debug/packages/kokkos/algorithms/src -I/home/mbetten/Trilinos/Trilinos/packages/kokkos/algorithms/src -I/home/mbetten/builds/drekar/cuda/debug/packages/kokkos/containers/src -I/home/mbetten/Trilinos/Trilinos/packages/kokkos/containers/src -I/home/mbetten/builds/drekar/cuda/debug/packages/teko/src -I/home/mbetten/Trilinos/Trilinos/packages/teko/src -I/home/mbetten/Trilinos/Trilinos/packages/teko/src/NS -I/home/mbetten/Trilinos/Trilinos/packages/teko/src/Epetra -I/home/mbetten/Trilinos/Trilinos/packages/teko/src/Tpetra -I/home/mbetten/builds/drekar/cuda/debug/packages/stratimikos/src -I/home/mbetten/Trilinos/Trilinos/packages/stratimikos/src -I/home/mbetten/Trilinos/Trilinos/packages/stratimikos/adapters/belos/src -I/home/mbetten/builds/drekar/cuda/debug/packages/stratimikos/adapters/belos/src -I/home/mbetten/Trilinos/Trilinos/packages/stratimikos/adapters/aztecoo/src -I/home/mbetten/Trilinos/Trilinos/packages/stratimikos/adapters/amesos/src -I/home/mbetten/Trilinos/Trilinos/packages/stratimikos/adapters/ml/src -I/home/mbetten/Trilinos/Trilinos/packages/stratimikos/adapters/ifpack/src -I/home/mbetten/builds/drekar/cuda/debug/packages/belos/tpetra/src -I/home/mbetten/Trilinos/Trilinos/packages/belos/tpetra/src -I/home/mbetten/builds/drekar/cuda/debug/packages/belos/epetra/src -I/home/mbetten/Trilinos/Trilinos/packages/belos/epetra/src -I/home/mbetten/builds/drekar/cuda/debug/packages/belos/src -I/home/mbetten/Trilinos/Trilinos/packages/belos/src -I/home/mbetten/builds/drekar/cuda/debug/packages/aztecoo/src -I/home/mbetten/Trilinos/Trilinos/packages/aztecoo/src -I/home/mbetten/builds/drekar/cuda/debug/packages/triutils/src -I/home/mbetten/Trilinos/Trilinos/packages/triutils/src -I/home/mbetten/builds/drekar/cuda/debug/packages/epetra/src -I/home/mbetten/Trilinos/Trilinos/packages/epetra/src -I/home/mbetten/Trilinos/Trilinos/packages/thyra/adapters/tpetra/src -I/home/mbetten/Trilinos/Trilinos/packages/thyra/adapters/epetra/src -I/home/mbetten/Trilinos/Trilinos/packages/thyra/core/src -I/home/mbetten/Trilinos/Trilinos/packages/thyra/core/src/interfaces/operator_vector/fundamental -I/home/mbetten/Trilinos/Trilinos/packages/thyra/core/src/interfaces/operator_vector/extended -I/home/mbetten/Trilinos/Trilinos/packages/thyra/core/src/support/operator_vector/client_support -I/home/mbetten/Trilinos/Trilinos/packages/thyra/core/src/support/operator_vector/adapter_support -I/home/mbetten/Trilinos/Trilinos/packages/thyra/core/src/interfaces/operator_solve/fundamental -I/home/mbetten/Trilinos/Trilinos/packages/thyra/core/src/interfaces/operator_solve/extended -I/home/mbetten/Trilinos/Trilinos/packages/thyra/core/src/support/operator_solve/client_support -I/home/mbetten/Trilinos/Trilinos/packages/thyra/core/src/interfaces/nonlinear/model_evaluator/fundamental -I/home/mbetten/Trilinos/Trilinos/packages/thyra/core/src/support/nonlinear/model_evaluator/client_support -I/home/mbetten/Trilinos/Trilinos/packages/thyra/core/src/interfaces/nonlinear/solvers/fundamental -I/home/mbetten/Trilinos/Trilinos/packages/thyra/core/src/support/nonlinear/solvers/client_support -I/home/mbetten/builds/drekar/cuda/debug/packages/thyra/core/src -I/home/mbetten/Trilinos/Trilinos/packages/thyra/core/example/operator_vector -I/home/mbetten/Trilinos/Trilinos/packages/rtop/src -I/home/mbetten/Trilinos/Trilinos/packages/rtop/src/interfaces -I/home/mbetten/Trilinos/Trilinos/packages/rtop/src/support -I/home/mbetten/Trilinos/Trilinos/packages/rtop/src/ops_lib -I/home/mbetten/Trilinos/Trilinos/packages/rtop/src/lapack -I/home/mbetten/builds/drekar/cuda/debug/packages/rtop/src -I/home/mbetten/Trilinos/Trilinos/packages/tpetra/core/ext -I/home/mbetten/builds/drekar/cuda/debug/packages/tpetra/core/ext -I/home/mbetten/Trilinos/Trilinos/packages/tpetra/core/inout -I/home/mbetten/builds/drekar/cuda/debug/packages/tpetra/core/inout -I/home/mbetten/Trilinos/Trilinos/packages/tpetra/core/src -I/home/mbetten/Trilinos/Trilinos/packages/tpetra/core/src/kokkos_refactor -I/home/mbetten/builds/drekar/cuda/debug/packages/tpetra/core/src -I/home/mbetten/builds/drekar/cuda/debug/packages/tpetra/kernels/src -I/home/mbetten/Trilinos/Trilinos/packages/tpetra/kernels/src -I/home/mbetten/Trilinos/Trilinos/packages/tpetra/kernels/src/impl -I/home/mbetten/Trilinos/Trilinos/packages/tpetra/kernels/src/stage/graph -I/home/mbetten/Trilinos/Trilinos/packages/tpetra/kernels/src/stage/graph/impl -I/home/mbetten/Trilinos/Trilinos/packages/tpetra/kernels/src/stage/graph/utils -I/home/mbetten/Trilinos/Trilinos/packages/tpetra/classic/LinAlg -I/home/mbetten/Trilinos/Trilinos/packages/tpetra/classic/NodeAPI -I/home/mbetten/builds/drekar/cuda/debug/packages/tpetra/classic/NodeAPI -I/home/mbetten/builds/drekar/cuda/debug/packages/tpetra/classic/src -I/home/mbetten/Trilinos/Trilinos/packages/tpetra/classic/src -I/home/mbetten/Trilinos/Trilinos/packages/thyra/adapters/epetraext/src/model_evaluator -I/home/mbetten/Trilinos/Trilinos/packages/thyra/adapters/epetraext/src/transformer -I/home/mbetten/builds/drekar/cuda/debug/packages/epetraext/src -I/home/mbetten/Trilinos/Trilinos/packages/epetraext/src -I/home/mbetten/Trilinos/Trilinos/packages/epetraext/src/transform -I/home/mbetten/Trilinos/Trilinos/packages/epetraext/src/inout -I/home/mbetten/Trilinos/Trilinos/packages/epetraext/src/coloring -I/home/mbetten/Trilinos/Trilinos/packages/epetraext/src/model_evaluator -I/home/mbetten/Trilinos/Trilinos/packages/epetraext/src/block -I/home/mbetten/Trilinos/Trilinos/packages/epetraext/src/restrict -I/home/mbetten/builds/drekar/cuda/debug/packages/ml/src -I/home/mbetten/Trilinos/Trilinos/packages/ml/src/Include -I/home/mbetten/Trilinos/Trilinos/packages/ml/src/Comm -I/home/mbetten/Trilinos/Trilinos/packages/ml/src/Coarsen -I/home/mbetten/Trilinos/Trilinos/packages/ml/src/FEGrid -I/home/mbetten/Trilinos/Trilinos/packages/ml/src/Main -I/home/mbetten/Trilinos/Trilinos/packages/ml/src/Smoother -I/home/mbetten/Trilinos/Trilinos/packages/ml/src/Krylov -I/home/mbetten/Trilinos/Trilinos/packages/ml/src/Operator -I/home/mbetten/Trilinos/Trilinos/packages/ml/src/Utils -I/home/mbetten/Trilinos/Trilinos/packages/ml/src/RefMaxwell -I/home/mbetten/Trilinos/Trilinos/packages/ml/src/MatrixFree -I/home/mbetten/Trilinos/Trilinos/packages/ml/src/MLAPI -I/home/mbetten/Trilinos/Trilinos/packages/ml/src/LevelWrap -I/home/mbetten/builds/drekar/cuda/debug/packages/ifpack/src -I/home/mbetten/Trilinos/Trilinos/packages/ifpack/src -I/home/mbetten/Trilinos/Trilinos/common/auxiliarySoftware/SuiteSparse/src/AMD/Include -I/home/mbetten/Trilinos/Trilinos/common/auxiliarySoftware/SuiteSparse/src/UFconfig -I/home/mbetten/builds/drekar/cuda/debug/packages/amesos/src -I/home/mbetten/Trilinos/Trilinos/packages/amesos/src -I/home/mbetten/Trilinos/Trilinos/packages/amesos/src/SuiteSparse/AMD/Include -I/home/mbetten/Trilinos/Trilinos/packages/amesos/src/SuiteSparse/COLAMD/Include -I/home/mbetten/Trilinos/Trilinos/packages/amesos/src/SuiteSparse/UFconfig -I/home/mbetten/Trilinos/Trilinos/packages/amesos/src/SuiteSparse/KLU/Include -I/home/mbetten/Trilinos/Trilinos/packages/amesos/src/SuiteSparse/BTF/Include -I/home/mbetten/Trilinos/Trilinos/packages/amesos/src/SuiteSparse/CAMD/Include -I/home/mbetten/Trilinos/Trilinos/packages/amesos/src/SuiteSparse/CCOLAMD/Include -I/home/mbetten/Trilinos/Trilinos/packages/common/auxiliarySoftware/SuiteSparse/src/AMD/Include -I/home/mbetten/Trilinos/Trilinos/packages/common/auxiliarySoftware/SuiteSparse/src/BTF/Include -I/home/mbetten/Trilinos/Trilinos/packages/common/auxiliarySoftware/SuiteSparse/src/CAMD/Include -I/home/mbetten/Trilinos/Trilinos/packages/common/auxiliarySoftware/SuiteSparse/src/CCOLAMD/Include -I/home/mbetten/Trilinos/Trilinos/packages/common/auxiliarySoftware/SuiteSparse/src/COLAMD/Include -I/home/mbetten/Trilinos/Trilinos/packages/common/auxiliarySoftware/SuiteSparse/src/KLU/Include -I/home/mbetten/Trilinos/Trilinos/packages/common/auxiliarySoftware/SuiteSparse/src/UFconfig -I/home/mbetten/builds/drekar/cuda/debug/packages/zoltan/src -I/home/mbetten/Trilinos/Trilinos/packages/zoltan/src/include -I/home/mbetten/Trilinos/Trilinos/packages/zoltan/src/all -I/home/mbetten/Trilinos/Trilinos/packages/zoltan/src/coloring -I/home/mbetten/Trilinos/Trilinos/packages/zoltan/src/graph -I/home/mbetten/Trilinos/Trilinos/packages/zoltan/src/ha -I/home/mbetten/Trilinos/Trilinos/packages/zoltan/src/hier -I/home/mbetten/Trilinos/Trilinos/packages/zoltan/src/hsfc -I/home/mbetten/Trilinos/Trilinos/packages/zoltan/src/lb -I/home/mbetten/Trilinos/Trilinos/packages/zoltan/src/matrix -I/home/mbetten/Trilinos/Trilinos/packages/zoltan/src/order -I/home/mbetten/Trilinos/Trilinos/packages/zoltan/src/par -I/home/mbetten/Trilinos/Trilinos/packages/zoltan/src/params -I/home/mbetten/Trilinos/Trilinos/packages/zoltan/src/tpls -I/home/mbetten/Trilinos/Trilinos/packages/zoltan/src/phg -I/home/mbetten/Trilinos/Trilinos/packages/zoltan/src/rcb -I/home/mbetten/Trilinos/Trilinos/packages/zoltan/src/reftree -I/home/mbetten/Trilinos/Trilinos/packages/zoltan/src/simple -I/home/mbetten/Trilinos/Trilinos/packages/zoltan/src/timer -I/home/mbetten/Trilinos/Trilinos/packages/zoltan/src/Utilities/Communication -I/home/mbetten/Trilinos/Trilinos/packages/zoltan/src/Utilities/DDirectory -I/home/mbetten/Trilinos/Trilinos/packages/zoltan/src/Utilities/Timer -I/home/mbetten/Trilinos/Trilinos/packages/zoltan/src/Utilities/shared -I/home/mbetten/Trilinos/Trilinos/packages/zoltan/src/zz -I/home/mbetten/Trilinos/Trilinos/packages/ifpack2/adapters/thyra -I/home/mbetten/builds/drekar/cuda/debug/packages/ifpack2/adapters -I/home/mbetten/Trilinos/Trilinos/packages/ifpack2/src -I/home/mbetten/builds/drekar/cuda/debug/packages/ifpack2/src -I/home/mbetten/Trilinos/Trilinos/packages/zoltan2/src -I/home/mbetten/builds/drekar/cuda/debug/packages/zoltan2/src -I/home/mbetten/Trilinos/Trilinos/packages/zoltan2/src/algorithms -I/home/mbetten/Trilinos/Trilinos/packages/zoltan2/src/algorithms/partition -I/home/mbetten/Trilinos/Trilinos/packages/zoltan2/src/algorithms/order -I/home/mbetten/Trilinos/Trilinos/packages/zoltan2/src/algorithms/color -I/home/mbetten/Trilinos/Trilinos/packages/zoltan2/src/algorithms/match -I/home/mbetten/Trilinos/Trilinos/packages/zoltan2/src/algorithms/map -I/home/mbetten/Trilinos/Trilinos/packages/zoltan2/src/algorithms/zoltan -I/home/mbetten/Trilinos/Trilinos/packages/zoltan2/src/environment -I/home/mbetten/Trilinos/Trilinos/packages/zoltan2/src/include -I/home/mbetten/Trilinos/Trilinos/packages/zoltan2/src/input -I/home/mbetten/Trilinos/Trilinos/packages/zoltan2/src/models -I/home/mbetten/Trilinos/Trilinos/packages/zoltan2/src/problems -I/home/mbetten/Trilinos/Trilinos/packages/zoltan2/src/util -I/home/mbetten/Trilinos/Trilinos/packages/xpetra/sup/Matrix -I/home/mbetten/Trilinos/Trilinos/packages/xpetra/sup/StridedMap -I/home/mbetten/Trilinos/Trilinos/packages/xpetra/sup/Cloner -I/home/mbetten/Trilinos/Trilinos/packages/xpetra/sup/Utils -I/home/mbetten/builds/drekar/cuda/debug/packages/xpetra/sup -I/home/mbetten/Trilinos/Trilinos/packages/xpetra/src/CrsGraph -I/home/mbetten/Trilinos/Trilinos/packages/xpetra/src/CrsMatrix -I/home/mbetten/Trilinos/Trilinos/packages/xpetra/src/BlockedCrsMatrix -I/home/mbetten/Trilinos/Trilinos/packages/xpetra/src/DistObject -I/home/mbetten/Trilinos/Trilinos/packages/xpetra/src/Export -I/home/mbetten/Trilinos/Trilinos/packages/xpetra/src/Headers -I/home/mbetten/Trilinos/Trilinos/packages/xpetra/src/Import -I/home/mbetten/Trilinos/Trilinos/packages/xpetra/src/Map -I/home/mbetten/Trilinos/Trilinos/packages/xpetra/src/BlockedMap -I/home/mbetten/Trilinos/Trilinos/packages/xpetra/src/MultiVector -I/home/mbetten/Trilinos/Trilinos/packages/xpetra/src/BlockedMultiVector -I/home/mbetten/Trilinos/Trilinos/packages/xpetra/src/BlockedVector -I/home/mbetten/Trilinos/Trilinos/packages/xpetra/src/Operator -I/home/mbetten/Trilinos/Trilinos/packages/xpetra/src/Platform -I/home/mbetten/Trilinos/Trilinos/packages/xpetra/src/RowGraph -I/home/mbetten/Trilinos/Trilinos/packages/xpetra/src/RowMatrix -I/home/mbetten/Trilinos/Trilinos/packages/xpetra/src/Utils -I/home/mbetten/Trilinos/Trilinos/packages/xpetra/src/Utils/ForwardDeclaration -I/home/mbetten/Trilinos/Trilinos/packages/xpetra/src/Vector -I/home/mbetten/builds/drekar/cuda/debug/packages/xpetra/src -I/home/mbetten/builds/drekar/cuda/debug/packages/anasazi/tpetra/src -I/home/mbetten/Trilinos/Trilinos/packages/anasazi/tpetra/src -I/home/mbetten/builds/drekar/cuda/debug/packages/anasazi/epetra/util/ModeLaplace -I/home/mbetten/Trilinos/Trilinos/packages/anasazi/epetra/util/ModeLaplace -I/home/mbetten/builds/drekar/cuda/debug/packages/anasazi/epetra/src -I/home/mbetten/Trilinos/Trilinos/packages/anasazi/epetra/src -I/home/mbetten/builds/drekar/cuda/debug/packages/anasazi/src -I/home/mbetten/Trilinos/Trilinos/packages/anasazi/src -I/home/mbetten/Trilinos/Trilinos/packages/anasazi/src/../thyra/src -I/home/mbetten/Trilinos/Trilinos/packages/anasazi/src/../tpetra/src  -std=c++11 -Wno-unused-local-typedefs -g -O0   -o CMakeFiles/muelu.dir/Utils/ExplicitInstantiation/MueLu_CoalesceDropFactory.cpp.o -c /home/mbetten/builds/drekar/cuda/debug/packages/muelu/src/Utils/ExplicitInstantiation/MueLu_CoalesceDropFactory.cpp
`

**Comment by mhoemmen** [comment]
@trilinos/muelu

**Comment by aprokop** [comment]
@bathmatt Please provide your configuration script.

**Comment by bathmatt** [comment]
Attaching two files, run 
. set_toolchain.txt
[configure.txt](https://github.com/trilinos/Trilinos/files/811632/configure.txt)
[set_toolchain.txt](https://github.com/trilinos/Trilinos/files/811635/set_toolchain.txt)

 cuda
then run the configure.

**Comment by aprokop** [comment]
This is probably due to @csiefer2 commits working on `computeGlobalConstants()` yesterday. My assumption at this point is that he missed one of the classes in Xpetra. Hang on.

**Comment by jhux2** [comment]
There are other known issues in MueLu.  @bathmatt the MueLu team is at CS&E this week.  Can this wait?

**Comment by bathmatt** [comment]
@jhux2 it can wait as I have an ifdef in my configure not to use this if cuda is on.

**Comment by aprokop** [comment]
@tawiesn Does 1a12587df53142b2731c739b3555084ad5394a71 fix this isssue?

**Comment by bathmatt** [comment]
Looks like it does,
