### ISSUE TITLE
Mumps cann't be used with Amesos direct solver.

### ISSUE THREAD

**Issue by ztdepztdep** [trilinos/Trilinos#10995]
I have sucessfully compiled the trilinos 13.4 with mumps enabled . 
But i tried to run the Amesos example and set the solvertype="Mumps". it still feeds me the error about " this solver is not enabled"?
I don't know how to resolve this.

**Comment by jhux2** [comment]
@trilinos/amesos2 @ndellingwood @iyamazaki

**Comment by iyamazaki** [comment]
@ztdepztdep. Just to make sure, is this with Amesos or Amesos2. If Amesos, any particular reason why you are using Amesos, and not Amesos2? I am more familiar with Amesos2, and I may help better with that package. Can you share your build script?

**Comment by ztdepztdep** [comment]
Thank you for your feedback. I compile the trilinos with cuda-gui , i don't have scriptes and I have check the "sue Mumps" during the configuration process. 
I really was confused by this error. I just have tried both Amesos and Amesos2, both give the same error. 


| |
Professor Ding、
|
|
***@***.***
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 9/12/2022 12:10 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [trilinos/Trilinos] Mumps cann't be used with Amesos direct solver. (Issue #10995) |

@ztdepztdep. Just to make sure, is this with Amesos or Amesos2. If Amesos, any particular reason why you are using Amesos, and not Amesos2? I am more familiar with Amesos2, and I may help better with that package. Can you share your build script?

**Comment by iyamazaki** [comment]
@ztdepztdep. I am not familiar with GUI, but can you make sure your Amesos2/MUMPS test passes? To enable the test, I had to enable:
```
-D TPL_ENABLE_MUMPS:BOOL=ON \
  -DTpetra_INST_INT_INT:BOOL=ON \
  -DAmesos2_ENABLE_MUMPS:BOOL=ON \
  -DTPL_MUMPS_INCLUDE_DIRS="${MUMPS_ROOT}/include" \
  -DTPL_MUMPS_LIBRARIES="${MUMPS_ROOT}/lib/libdmumps.a;${MUMPS_ROOT}/lib/libmumps_common.a;${MUMPS_ROOT}/lib/libpord.a;${SCALAPACK_ROOT}/libscalapack.a" \
```
Then, if you run `ctest .` under `packages/amesos2/test`, then you should see something like
```
      Start  4: Amesos2_MUMPS_UnitTests_MPI_4
 4/10 Test  #4: Amesos2_MUMPS_UnitTests_MPI_4 ........................   Passed   15.49 sec
```

**Comment by ztdepztdep** [comment]
Thanks, it complain about the error:


"undefined reference to symbol 'MPI_Comm_set_attr'
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: /usr/local/lib64/libmpi.so.12: error adding symbols: DSO missing from command line"



I have libmpi.so.12 in the /usr/local/lib64 , what is the error? 




| |
Professor Ding、
|
|
***@***.***
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 9/13/2022 05:01 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [trilinos/Trilinos] Mumps cann't be used with Amesos direct solver. (Issue #10995) |

@ztdepztdep. I am not familiar with GUI, but can you make sure your Amesos2/MUMPS test passes? To enable the test, I had to enable:

-D TPL_ENABLE_MUMPS:BOOL=ON \
  -DTpetra_INST_INT_INT:BOOL=ON \
  -DAmesos2_ENABLE_MUMPS:BOOL=ON \
  -DTPL_MUMPS_INCLUDE_DIRS="${MUMPS_ROOT}/include" \
  -DTPL_MUMPS_LIBRARIES="${MUMPS_ROOT}/lib/libdmumps.a;${MUMPS_ROOT}/lib/libmumps_common.a;${MUMPS_ROOT}/lib/libpord.a;${SCALAPACK_ROOT}/libscalapack.a" \


Then, if you run ctest . under packages/amesos2/test, then you should see something like

      Start  4: Amesos2_MUMPS_UnitTests_MPI_4
 4/10 Test  #4: Amesos2_MUMPS_UnitTests_MPI_4 ........................   Passed   15.49 sec

**Comment by jjellio** [comment]
Something is wrong with your compiler or flags. This type of error usually will go away if your compiler adds `-L/path/to/mpi/lib -lmpi -Wl,-rpath,/path/to/mpi/lib`

E.g., with openmpi,

```
mpicc -showme
gcc -I/projects/sems/install/rhel7-x86_64/sems/compiler/gcc/5.1.0/openmpi/4.0.5/include -pthread -Wl,-rpath -Wl,/projects/sems/install/rhel7-x86_64/sems/compiler/gcc/5.1.0/openmpi/4.0.5/lib -Wl,--enable-new-dtags -L/projects/sems/install/rhel7-x86_64/sems/compiler/gcc/5.1.0/openmpi/4.0.5/lib -lmpi
```

If you aren't using an "mpi compiler wrapper" (like mpicc / mpicxx). Then you likely need to set `-DTrilinos_EXTRA_LINK_FLAGS=... that stuff `
