### ISSUE TITLE
which kind of preconditioner may i use to solve thid kind of matrix A in ifpack

### ISSUE THREAD

**Issue by ztdepztdep** [trilinos/Trilinos#10992]
My matrix A has the following structure. I want to find an efficient preconditioner for it. I am using ifpack ilu , but i found it is too slow. 
could you please give me some advices.

![AP mtx](https://user-images.githubusercontent.com/8356693/188589157-13c09f70-f1fb-472d-b828-e4b44a2a2082.jpg)

**Comment by cgcgcg** [comment]
The graph of the matrix is not enough information to decide what kind of preconditioner to use. What kind of problem is this? It looks like the discretization of a PDE, so that's good. Symmetric positive definite?

**Comment by ztdepztdep** [comment]
> The graph of the matrix is not enough information to decide what kind of preconditioner to use. What kind of problem is this? It looks like the discretization of a PDE, so that's good. Symmetric positive definite?

It is generated from spectral element method, it is not a sysmmetric.

**Comment by cgcgcg** [comment]
Alright. How about its nullspace? And what kind of physics?

**Comment by ztdepztdep** [comment]
> Alright. How about its nullspace? And what kind of physics?

it is for incompressible flow solution. and it is a Helmholtz problem.

**Comment by cgcgcg** [comment]
Ok. These guys are difficult to precondition, as they are indefinite. I would suggest you check the literature for approaches. Both multigrid and domain decomposition can be used (and we have both in Trilinos). I believe we had some multigrid example at some point, but I'll need to find it.

**Comment by ztdepztdep** [comment]
yes, it is difficult. I use Amesos to precondition, but the speed is a problem.

**Comment by cgcgcg** [comment]
Have a look at `packages/muelu/test/helmholtz`.
