### ISSUE TITLE
MueLu: File named "aux" prevents successful Trilinos clone on Windows

### ISSUE THREAD

**Issue by dc-snl** [trilinos/Trilinos#10993]
## Bug Report
@trilinos/MueLu

### Description
There's a file named `aux` in the MueLu source tree, causing this issue when cloning on Windows:

```
C:\TEMP>git clone https://github.com/trilinos/Trilinos.git source/Trilinos
Cloning into 'source/Trilinos'...
remote: Enumerating objects: 1219101, done.
remote: Counting objects: 100% (32/32), done.
remote: Compressing objects: 100% (30/30), done.
remote: Total 1219101 (delta 7), reused 13 (delta 2), pack-reused 1219069Receiving objects: 100% (1219101/1219101), 741.
Receiving objects: 100% (1219101/1219101), 745.12 MiB | 8.50 MiB/s, done.

Resolving deltas: 100% (924098/924098), done.
error: invalid path 'packages/muelu/research/caglusa/1d-binary-global/aux'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```

See also: https://stackoverflow.com/questions/61614004/cloning-succeded-but-checkout-failed-due-to-invalid-path-what-is-the-path-probl

> **The problem is Windows**
> 
> [Windows cannot handle any file named AUX.](https://www.howtogeek.com/fyi/windows-10-still-wont-let-you-use-these-file-names-reserved-in-1974/) You can't name a file PRN or CON or COM1 either.

According to the linked article,

> Microsoft provides an official list of reserved file names, and here they are:
> 
> ```
> CON, PRN, AUX, NUL, COM1, COM2, COM3, COM4, COM5, COM6, COM7, COM8, COM9, LPT1, LPT2, LPT3, LPT4, LPT5, LPT6, LPT7, LPT8, and LPT9
> ```
> 
> Note that you can’t use these file names with any file extension. So you can’t name a file “con.txt”, “con.jpg”, “or “con.doc”. And Windows isn’t case sensitive, so it doesn’t matter whether it’s CON, con, or CoN—Windows won’t let you use that name.

### Steps to Reproduce
1. SHA1:  ff31d99fabd259d3aab0602712178226374b2e64
1. Simply try to clone on Windows.

**Comment by cgcgcg** [comment]
FIxed on develop.
