### ISSUE TITLE
Zoltan: outdated-autotools-helper-file

### ISSUE THREAD

**Issue by nschloe** [trilinos/Trilinos#11]
Zoltan still ships autotools helper files with the sources, and they are quite old. Debian marks them as [`outdated`](https://lintian.debian.org/tags/outdated-autotools-helper-file.html):
```
trilinos source: outdated-autotools-helper-file packages/zoltan/config/config.guess 2012-01-01
trilinos source: outdated-autotools-helper-file packages/zoltan/config/config.sub 2012-01-01
```

**Comment by kddevin** [comment]
@trilinos/zoltan
Adding code to test zoltan team email.

**Comment by kddevin** [comment]
@trilinos/zoltan 
Zoltan supports stand-alone (separate from Trilinos) builds using autotools.
Are the configuration files causing any serious problems?  Or just warnings?
If there are no serious problems, we will leave the files as they are.
If there are serious problems, please re-open this issue and provide details.

**Comment by nschloe** [comment]
Those are indeed just warnings, I figured I better report before they begin to become actual errors. Thanks for reviewing.
