### ISSUE TITLE
Tpetra:  Fix or delete HAVE_TPETRA_THROW_EFFICIENCY_WARNINGS

### ISSUE THREAD

**Issue by tasmith4** [trilinos/Trilinos#11005]
## Enhancement
@trilinos/tpetra 

This macro enables warnings for a user when they do things that might be inefficient.  However, it takes an expert Tpetra developer to know it exists and enable it, making it practically useless for its intended purpose.  It should probably be either fixed so it is very easy to enable, or else outright deleted.

**Comment by tjfulle** [comment]
@csiefer2 - did you want to remove the macros, or make them more easy to enable?  I'd vote to remove.  It seems like a unnecessary code maintenance
