### ISSUE TITLE
Kokkos_Sparse_impl_MKL build error

### ISSUE THREAD

**Issue by kongm** [trilinos/Trilinos#1101]
Hi,

I'm trying to build the latest Trilinos git version. I'm using these options:

  -D TSQR_ENABLE_Fortran:BOOL=OFF \
  -D Trilinos_ENABLE_Belos:BOOL=ON \
  -D Trilinos_ENABLE_Ifpack2:BOOL=ON \
  -D Trilinos_ENABLE_Teuchos:BOOL=ON \
  -D Trilinos_ENABLE_CXX11:BOOL=ON \
  -D Trilinos_ENABLE_Tpetra:BOOL=ON \
  -D Trilinos_ENABLE_Kokkos:BOOL=ON \
  -D Trilinos_ENABLE_KokkosKernels:BOOL=ON \
  -D Trilinos_ENABLE_OpenMP:BOOL=ON \
  -D Trilinos_ENABLE_KokkosKernels:BOOL=ON \
  -D Trilinos_ENABLE_Epetra:BOOL=OFF \
  -D Trilinos_ENABLE_TpetraKernels:BOOL=ON \
  -D Trilinos_ENABLE_DEVELOPMENT_MODE:BOOL=OFF \
  -D Trilinos_ENABLE_Panzer:BOOL=OFF \
  -D Trilinos_ENABLE_DEBUG:BOOL=OFF \
  -D Trilinos_ENABLE_Thyra:BOOL=OFF \
  -D Trilinos_ENABLE_CHECKED_STL:BOOL=OFF \
  -D Trilinos_ENABLE_ML:BOOL=OFF \
  -D Tpetra_INST_OPENMP:BOOL=ON \
  -D Tpetra_PRINT_Efficiency_Warnings:BOOL=ON \
  -D Tpetra_ENABLE_EXAMPLES:BOOL=OFF \
  -D Tpetra_ENABLE_TESTS:BOOL=OFF \
  -D Tpetra_ENABLE_Kernels:BOOL=OFF \
  -D Teuchos_ENABLE_COMPLEX:BOOL=OFF \
  -D Teuchos_ENABLE_EXAMPLES:BOOL=OFF \
  -D Teuchos_ENABLE_DEBUG_RCP_NODE_TRACING:BOOL=OFF \
  -D Kokkos_ENABLE_OpenMP:BOOL=ON \
  -D Kokkos_ENABLE_EXAMPLES:BOOL=OFF \
  -D Kokkos_ENABLE_TESTS:BOOL=OFF \
  -D Kokkos_ENABLE_TSQR:BOOL=OFF \
  -D Kokkos_ENABLE_BOUNDS_CHECK:BOOL=ON \
  -D Kokkos_ENABLE_Serial:BOOL=ON \
  -D Belos_ENABLE_TEUCHOS_TIME_MONITOR:BOOL=ON \

The configuration process completes successfully, but when building I get errors such as:
 In function ‘std::string KokkosSparse::Impl::Mkl::matrixDescriptorToString(const int&, std::string, bool, bool)’:
/glb/home/usmkpb/mkongdir/trilinos-src-git/packages/tpetra/kernels/src/impl/Kokkos_Sparse_impl_MKL.cpp:200:64: error: request for member ‘type’ in ‘descr’, which is of non-class type ‘const int’
   out << indent << "Type: " << sparseMatrixTypeToString (descr.type);

or

 In function ‘std::string KokkosSparse::Impl::Mkl::sparseFillModeToString(int)’:
/glb/home/usmkpb/mkongdir/trilinos-src-git/packages/tpetra/kernels/src/impl/Kokkos_Sparse_impl_MKL.cpp:127:15: error: ‘SPARSE_FILL_MODE_LOWER’ was not declared in this scope
   if (mode == SPARSE_FILL_MODE_LOWER) {

as well as other error about not finding sparse_matrix_t, status_type, sparse_status_t, etc.

Am I missing some flags?

**Comment by mhoemmen** [comment]
Hold on, this might be related to #1099.

**Comment by crtrott** [comment]
I'll do it.

**Comment by crtrott** [comment]
can you post a more complete configure file.

**Comment by crtrott** [comment]
Not sure what is going for you. I need a full configure script and what compilers you are using etc.

**Comment by kongm** [comment]
Here are my configure script, the configure log and the CMake logs.

[CMakeError.txt](https://github.com/trilinos/Trilinos/files/814474/CMakeError.txt)
[CMakeOutput.txt](https://github.com/trilinos/Trilinos/files/814477/CMakeOutput.txt)
[do-config.txt](https://github.com/trilinos/Trilinos/files/814476/do-config.txt)
[do-config-log.txt](https://github.com/trilinos/Trilinos/files/814475/do-config-log.txt)

**Comment by kongm** [comment]
Seems like the MKL version used in the configure file is too old. Doesn't even have constants such as SPARSE_INDEX_BASE_ZERO. Will try then with a newer version.

**Comment by crtrott** [comment]
Yeah, also use -mkl both for cxx and linkflags

**Comment by nmhamster** [comment]
@kongm in your logs the compiler is identified as GNU so the `-mkl` will not work (Intel specific). If you want to use the Intel compiler with Intel-MPI then you should use the `mpiicpc`, `mpiicc` and `mpiifort` commands as these will map correctly.

**Comment by kongm** [comment]
@nmhamster  Thanks for pointing that out.

@crtrott @mhoemmen I managed to correctly build Trilinos. Our application is working fine with it. Now I can finally test the new thread parallel solvers. Thanks!

**Comment by mhoemmen** [comment]
@kongm Just curious -- what MKL version were you using before?  I would like to add an MKL version check to KokkosKernels.  See issue here: https://github.com/kokkos/kokkos-kernels/issues/7

**Comment by mhoemmen** [comment]
I closed this issue, and added a KokkosKernels issue to add an MKL version check: https://github.com/kokkos/kokkos-kernels/issues/7
