### ISSUE TITLE
Tpetra: `readSparse` produces incorrect results when final matrix rows are empty

### ISSUE THREAD

**Issue by cwpearson** [trilinos/Trilinos#11024]
@trilinos/tpetra

https://github.com/trilinos/Trilinos/blob/01a5a046a6eaea717edbf32bf68c5bbbfd9a2576/packages/tpetra/core/inout/MatrixMarket_Tpetra.hpp#L3663-L3687

consider a matrix where there are `N` entries in the first row, and no other entries.

`curRow` will always be `0`, therefore `if (curRow > prvRow)` will always be false, therefore all `rowPtr` entries will be 0, except the last one, which will be `N`.

Actually, the `rowPtr` array should be `[0, N, N, ...]`, not `[0, 0, ...., 0, N]`

**Comment by cwpearson** [comment]
A fix would be to delete lines 3673-3678 and add 

```c++
              // rowPtr has one more entry than numRows
              rowPtr[0] = 0;
              for (size_t i = 1; i < numRows+1; ++i) {
                rowPtr[i] = rowPtr[i-1] + numEntriesPerRow[i-1];
              }
```

to replace 3686

**Comment by cgcgcg** [comment]
Sounds like a reasonable fix. PR?

**Comment by cwpearson** [comment]
Assign me!

Probably we never hit this case on most of our real matrices.

**Comment by cwpearson** [comment]
This was fixed in https://github.com/trilinos/Trilinos/commit/2cdb1ac6b3b924d5205d8b95603ca31b1cd29150
