### ISSUE TITLE
MueLu builds zero column prolongator for diagonal matrix

### ISSUE THREAD

**Issue by tawiesn** [trilinos/Trilinos#1103]
By default, MueLu drops "Dirichlet" nodes from aggregation. In the worst case it builds a prolongation operator with zero columns.

There is a "aggregation: preserve Dirichlet points" option (default=off) to keep all Dirichlet nodes unaggregated. The problem is, that there would be no progress in coarsening if we activate that.

What are the options for a smarter handling of this special case?
- We could detect the problem during the aggregation (all nodes "aggregated" with 0 aggregates) and then build a dummy one node aggregate (the coarsening would terminate on the next level)
- We check the size of two consecutive levels and if the matrix size is not shrinking (by a factor X) we stop coarsening...

**Comment by tawiesn** [comment]
@trilinos/muelu

**Comment by jhux2** [comment]
> We check the size of two consecutive levels and if the matrix size is not shrinking (by a factor X) we stop coarsening...

@tawiesn I think @aprokop already implemented this option in MueLu

**Comment by aprokop** [comment]
No, there is nothing in MueLu that deals with this case. There is also an additional bug associated with this issue: if you choose your `aggregation: drop tol` large enough, you will drop all off-diagonal entries which would lead to the exact same issue.

If all nodes are Dirichlet, then essentially this processor does not need to communicate with other processors to solve it's local domain. We need to have some mechanism that shortcuts the hierarchy for that processor.

@tawiesn I think we should do the first approach (construct a dummy aggregate):
- The tentative P would be a single column of all ones
- (if I'm not mistaken) All matrix-matrix multiplications would not require extra communication

**Comment by tawiesn** [comment]
Yes, i agree with @aprokop. Making sure that the aggregation strategy is returning at least one (dummy) aggregate would avoid the crash. We have to throw a warning, too. The coarse solver would then be applied to a problem of size 3x3 or 6x6. Not a big issue, i guess, but not elegant. Most level smoothers can solve the diagonal problem anyway, so it should not a big of issue with respect to convergence...
@jhux2 The MueLu::Hierarchy throws a warning if coarsening stagnates. But when thinking about the details there is no way to deal with above special case with that apporach as it is already crashing before.

**Comment by tawiesn** [comment]
For the parallel case: I think we should have at least one aggregate on each processor. In fact, we would have to check, whether all local nodes have the state IGNORED aggState. If and only if that is the case we would create one aggregate (e.g. for the first local node on the proc).

**Comment by tawiesn** [comment]
I'd propose to add a check in the PreserveDirichletAggregationAlgorithm. This algorithm is hard-coded to be used in the UncoupledAggregationAlgorithm. We can count the number of local nodes with status IGNORED (in the for loop that we already have) and compare it with the number of local nodes. If both numbers are the same it means all nodes have been ignored for aggregation and we'd create one (dummy) aggregate (e.g. including node 0 on the local processor).
Any concerns or better ideas?

**Comment by csiefer2** [comment]
@ibaned : FYI - This is the issue that is blocking the RPI folks.

**Comment by ibaned** [comment]
Interesting, because we've been considering removing Dirichlet rows/columns from the system in Albany. It sounds like that would make life much easier for MueLu. Unfortunately, its a non-trivial effort so not sure which of them will get done first.

**Comment by csiefer2** [comment]
On the RPI problem we're getting this because we wind up with Phase 3 aggregation generating a lot of singletons (for reasons that are not obvious by just looking at the matrix entries).  These aren't Dirichlet nodes or anything else which would make it obviously generate singletons. @jhux2

**Comment by ibaned** [comment]
At some point I think it was mentioned that parallel partitioning is a factor. Does that seem to be relevant to this problem ?

**Comment by aprokop** [comment]
I remember some discussion about parallel partitioning. If I recall correctly, RPI folks partition the domain by slices. I think if you are unlucky, you may partition in such a way that some nodes that belong to a processor may not have any connections to other nodes on the same processor. Which leads to singletons. Don't know if that's the case here.

**Comment by ibaned** [comment]
I would say that is likely, and furthermore I suspect that in real world large-scale problems it will be a common occurrence. So in the long term research should really be done to allow MueLu to coarsen such nodes in parallel. It is better to do some extra communication than be left with a system full of singletons. In the short term, is it fair to say that every node which is not coupled to another node on the same processor will become a singleton? If so it is easy for the RPI folks to write code that will measure this number and print it. We could then compare to the MueLu output (I assume it is printing total number of singletons).

@cwsmith @bgranzow @liz13 let me know if you need help with this, but basically count all the owned vertices which are not adjacent via edges to other owned vertices. We can print this total as an important new partition metric, and once we have that metric we can look for alternate partitioning methods that minimize it.

**Comment by csiefer2** [comment]
RPI issue originally was due to poor partitioning, which generated isolated nodes on a given processor.  However, the RPI team fixed that (at least for this problem).

I've tracked the current issue down to how MueLu does "on processor" node-detection within Phase 3 aggregation.

**Comment by csiefer2** [comment]
The mesh for the RPI problem *still* has isolated nodes, thus MueLu will not work with a non-trivial nullspace.

From a MueLu perspective, we should detect this in a fashion that makes this crystal clear and crash accordingly.

Longer term, we should probably make an (optional) filter available to clean up the initial partition (by migrating those nodes) if this is the case.

**Comment by ibaned** [comment]
1. Are we sure they are isolated due to partitioning, or are they DBC rows ?

2. Would MueLu work well if there were no null space ? Perhaps the finite element problem itself is not fully constrained ?

**Comment by csiefer2** [comment]
1. They are not Dirichlet nodes.  They are isolated due to the partition.

2. MueLu wants the problem to be well-posed (e.g. no nullspace) , but uses the near-nullspace rigid body modes (which we generally refer to as the 'nullspace' which can confuse matters) to generate coarse grids.

**Comment by ibaned** [comment]
Another thing we'll frequently have is disconnected components in a partition. Would that cause the same kind of issues, if a connected component gets coarsened to a single row (?) and is not connected to another coarsened component in the same partition ?

**Comment by csiefer2** [comment]
Repartitioning (which you really want to use at scale) ameliorates the disconnected components issue.

**Comment by bgranzow** [comment]
@cwsmith just developed a utility to check for the existence of 'isolated nodes'.  As @ibaned just brought up, we initially targeted eliminating what we call 'isolated components'. We either wrongly assumed that this would eliminate isolated nodes, or targeted the wrong partitioning metric.

@csiefer2 Just to be clear, the initial mesh we provided you with that has isolated nodes?

**Comment by ibaned** [comment]
> Repartitioning (which you really want to use at scale) ameliorates the disconnected components issue.

Well, the trouble with that (and the reason "slices" are used) is that at really large scale, graph-based repartitioning gets prohibitively slow or crashes. @cwsmith knows better than me, but in the ballpark of billions of elements and hundreds of thousands of ranks, invoking ParMETIS via Zoltan is problematic. RPI has a few alternatives but I suspect they will initially be looking at ParMETIS as a prime candidate to fix this mesh. Is there a different repartitioning method you would suggest, @csiefer2  ?

**Comment by csiefer2** [comment]
@bgranzow : Yes.  The mesh has isolated nodes.

@ibaned : By default we do coordinate-based repartitioning (e.g. RCB or such).  This is generally much faster than graph-based repartitioning and are implemented directly in Zoltan/Zoltan2.

**Comment by ibaned** [comment]
I think I confused MueLu's internal repartitioning with the mesh partitioning. Its good to know that MueLu uses coordinate-based methods, that is also how the mesh itself was partitioned (using RIB on the coordinates of the element centroids). However, since that technique seems to create isolated nodes, we may need to think of something else. It would be good if someone from RPI could post the data here about how many isolated nodes there are.

**Comment by ibaned** [comment]
Apparently the utility developed did not find any isolated nodes (by my definition), which is interesting. We at least should iterate on the definition of isolation, because we can't improve what we can't measure.

My definition assumed first order Lagrange tetrahedra, in which case node connectivity is defined by the mesh edges themselves.

Perhaps DBC nodes are clouding things, i.e. there may be a non-DBC node that is only locally connected to DBC nodes ?

**Comment by bgranzow** [comment]
For completeness, the check for 'isolated nodes' (specifically isolated vertices) is done [here](https://github.com/SCOREC/core/blob/dcVtx/parma/parma.cc#L163). I believe this is consistent with @ibaned's definition of a 'disconnected vertex'. As @ibaned mentioned, this metric indicates 0 disconnected vertices for the mesh ball_300.dmg / fix_ball_300.smb (@csiefer2, I got this mesh from a link Zhen shared via DropBox. Is this the mesh you've been looking at?)

Perhaps we have an incorrect definition of isolated vertices?

**Comment by bgranzow** [comment]
OK, so I think there was a bug in the utility I previously discussed to find disconnected vertices. I apologize. I now see output that suggests there are 29 disconnected vertices in our example mesh.

As an initial test, I took the partitioned mesh and serialized it and then partitioned the mesh with graph-based partitioning with Zoltan, and I see that there are 5 disconnected vertices. I'm struggling to understand how this happens, so I'm next going to attempt to visualize the vertices that are disconnected.

**Comment by tawiesn** [comment]
@csiefer2 added a MueLu option to detect problems like this. See commit ce1a5f6f5a599903dbe740380193f06a7cfebf46

**Comment by aprokop** [comment]
I feel like theoretically a similar situation could also happen if the graph of a matrix is structurally nonsymmetric. But that would require an (expensive) detection check. Anyway, the referenced commit should detect those too.
