### ISSUE TITLE
MueLu: Matrix-free prolongator tests fail for Scalar=complex on Cuda

### ISSUE THREAD

**Issue by cgcgcg** [trilinos/Trilinos#11039]
## Bug Report
@trilinos/muelu 

### Description
https://testing.sandia.gov/cdash/test/144113992

**Comment by cgcgcg** [comment]
@GrahamBenHarper You might want to build and run with Kokkos boundscheck. It seems that there are some bounds errors.

**Comment by GrahamBenHarper** [comment]
Ah shoot thanks for catching this

**Comment by cgcgcg** [comment]
Fixed by PR #11044
