### ISSUE TITLE
Framework:  develop to master promotions occurred, potentially without clean results

### ISSUE THREAD

**Issue by jhux2** [trilinos/Trilinos#11042]
## Question
@trilinos/framework

There are a number of dev to master merges that happened recently, even though testing doesn't appear to have finished cleanly.

https://github.com/trilinos/Trilinos/pull/10919
https://github.com/trilinos/Trilinos/pull/11007
https://github.com/trilinos/Trilinos/pull/10986
https://github.com/trilinos/Trilinos/pull/10938
https://github.com/trilinos/Trilinos/pull/10869
https://github.com/trilinos/Trilinos/pull/11031

Reported in [TRILINOSHD-208](https://sems-atlassian-son.sandia.gov/jira/servicedesk/customer/portal/7/TRILINOSHD-208).

**Comment by bartlettroscoe** [comment]
Responding to comment from @jhux2 in ??? that seems good to show to all Trilinos developers:

> Christian Glusa pointed out that the most recent D2M did pass cleanly and subsequently merged (https://github.com/trilinos/Trilinos/pull/11031). Did this trigger the others to close automatically?
>  Did this trigger the others to close automatically?

That is a good point. Actually, yes, if GitHub detects that the commits are merged in another PR, it will mark the PR as closed.

For example, for PR:

* https://github.com/trilinos/Trilinos/pull/10919

I should have noticed that as a clue where the last (failing) PR build iteration:

* https://github.com/trilinos/Trilinos/pull/10919#issuecomment-1224928670

was way back on 8/23/2022 but the merge commit that trigged the merge of this PR:

* https://github.com/trilinos/Trilinos/commit/d92e59f43d69f3c62d193236e1230c6dbd498c52

was just made yesterday.

Seems that GitHub could make it more clear when a PR is implicitly merged by another PR.

**Comment by jhux2** [comment]
So all is good.  I'll close this question.
