### ISSUE TITLE
Ifpack2: CUDA 11 Compilation Issue

### ISSUE THREAD

**Issue by csiefer2** [trilinos/Trilinos#11048]
The CUDA 11 compiler has trouble with `auto` in the depths of Ifpack2.

**Comment by ndellingwood** [comment]
@csiefer2 I ran into build errors in [#11047](https://github.com/trilinos/Trilinos/pull/11047#issuecomment-1255274682) with ifpack2 compilation errors in the cuda/11 PR test that were unrelated to changes I made with the cuda/11 test (PR had changes only to zoltan2 that would only show up with host-only compilation), is this similar to what you're running into? If so, I'm assuming that test should be disabled in the PR testing?

```
/scratch/trilinos/workspace/Trilinos_PR_cuda-11.4.2-uvm-off/Trilinos/packages/ifpack2/test/unit_tests/Ifpack2_UnitTestBlockCrsUtil.hpp:357:18: error: '__T0' was not declared in this scope; did you mean '__y0'?
  357 |       auto sbppad(sbp);
```

**Comment by e10harvey** [comment]
@fryeguy52: How did cuda11 even get enabled for PR & MM testing with this build error...?
```
1eb8ef76f432 (Andrew M. Bradley   2017-08-23 15:21:37 -0600 357)       auto sbppad(sbp);
```
