### ISSUE TITLE
KokkosKernels/Ifpack2: Major performance regression in RILUK initialize

### ISSUE THREAD

**Issue by brian-kelley** [trilinos/Trilinos#11041]
## Bug Report
@trilinos/kokkos-kernels 
@trilinos/ifpack2 

@srajama1 @ndellingwood @vqd8a @jennloe 

### Description
Between revisions d7d082 (good) and 29b156 (bad), RILUK initialize time for multiple SierraTF problems increased from ~26s to ~136s, roughly a 5x slowdown. The only relevant change in this commit range was the KokkosKernels 3.7 release (or possibly Kokkos, but I think this is very unlikely as a lot of work has been done recently in KokkosKernels and Ifpack2 on the ILU-based preconditioners).

The ATDM env used is ``cuda-10.1.243_gnu-7.3.1_spmpi-2019.06.24-release``. This hasn't changed since we started the performance dashboard (so the known regressions in cuSPARSE 11 sptrsv aren't the culprit)

The solver configuration did not change either:
```
  <Parameter name="solver_type" type="string" value="PseudoBlockGmres"/>
  <ParameterList name="Belos">
    <!-- "Num Blocks" is the krylov subspace size, or iters-per-restart. -->
    <Parameter name="Num Blocks" type="int" value="300"/>
    <Parameter name="Verbosity" type="int" value="33"/>
    <Parameter name="Maximum Iterations" type="int" value="1000"/>
    <Parameter name="Maximum Restarts" type="int" value="20"/>
    <Parameter name="Orthogonalization" type="string" value="ICGS"/>
    <Parameter name="Output Style" type="int" value="1"/>
    <Parameter name="Output Frequency" type="int" value="1"/>
    <Parameter name="Convergence Tolerance" type="double" value="1e-06"/>
  </ParameterList>

  <Parameter name="Ifpack2::Preconditioner" type="string" value="SCHWARZ"/>
  <ParameterList name="Ifpack2">
    <Parameter name="schwarz: overlap level" type="int" value="2"/>
    <Parameter name="schwarz: combine mode" type="string" value="ZERO"/>
    <Parameter name="schwarz: use reordering" type="bool" value="true"/>
    <Parameter name="subdomain solver name" type="string" value="RILUK"/>
    <ParameterList name="subdomain solver parameters">
      <Parameter name="fact: iluk level-of-fill" type="int" value="3"/>
      <Parameter name="fact: iluk level-of-overlap" type="int" value="0"/>
      <Parameter name="fact: type" type="string" value="KSPILUK"/>
      <Parameter name="trisolver: type" type="string" value="KSPTRSV"/>
    </ParameterList>
  </ParameterList>
```

**Comment by brian-kelley** [comment]
Update on this: I have a local matrix that reproduces. I verified that the matrix is identical between the versions. After running the KokkosKernels spiluk driver on it in a few different configurations, I have this:
```
Kokkos/KokkosKernels Version vs.  Symbolic time (s)
Both 3.6.1: 34.2324
3.7/3.6.1: 183.088
Both 3.7:  194.565
```
It appears that the symbolic mostly slowed down from changes in Kokkos core between releases 3.6.1 and 3.7 (although there was some additional slowdown from KokkosKernels across the same versions).

**Comment by srajama1** [comment]
I would recommend to look at the Kokkos part first as that might explain the small slowdown in Kokkos Kernels as well. @crtrott

**Comment by brian-kelley** [comment]
I'm running a bisect over Kokkos between 3.6.1 and 3.7. If that doesn't give any clear answers, I can put the ~240MB reproducer matrix somewhere accessible (kokkos-dev2?)

**Comment by brian-kelley** [comment]
Fix ready in https://github.com/kokkos/kokkos-kernels/pull/1553, and some timings. Turns out a Kokkos change to the default behavior of Kokkos::sort triggered this, effectively making sort of a CudaUVMSpace view happen on GPU with BinSort instead of on host with std::sort - but that change was 100% correct. KokkosKernels was using Kokkos::sort in a way that wasn't intended to be performant - sorting many small arrays in a loop.
