### ISSUE TITLE
Teuchos:  Not sure how to configure correctly configure Trilinos with Teuchos, LAPACK, and BLAS

### ISSUE THREAD

**Issue by flintpierce** [trilinos/Trilinos#11077]
## Question
@trilinos/\TEUCHOS\>

I'm having trouble building Trilinos with Teuchos, LAPACK, and BLAS.  Is there a particular setup I need to do with LAPACK or BLAS installs such that I don't get errors when I try to install Trilinos with Teuchos? 

My Trilinos config script gives errors (on install) whenever I use:

-D Trilinos_ENABLE_Teuchos:BOOL=ON

The errors I am getting are as follows:

../../src/libteuchosnumerics.a(Teuchos_BLAS.cpp.o): In function `Teuchos::BLAS<int, float>::ROTG(float*, float*, float*, float*) const':
/fgs/fpierce/Al-Melt-Relocation/Trilinos/packages/teuchos/numerics/src/Teuchos_BLAS.cpp:126: undefined reference to `srotg_'
../../src/libteuchosnumerics.a(Teuchos_BLAS.cpp.o): In function `Teuchos::BLAS<int, float>::ROT(int const&, float*, int const&, float*, int const&, float*, float*) const':
/fgs/fpierce/Al-Melt-Relocation/Trilinos/packages/teuchos/numerics/src/Teuchos_BLAS.cpp:129: undefined reference to `srot_'
../../src/libteuchosnumerics.a(Teuchos_BLAS.cpp.o): In function `Teuchos::BLAS<int, float>::ASUM(int const&, float const*, int const&) const':
/fgs/fpierce/Al-Melt-Relocation/Trilinos/packages/teuchos/numerics/src/Teuchos_BLAS.cpp:137: undefined reference to `sasum_'
../../src/libteuchosnumerics.a(Teuchos_BLAS.cpp.o): In function `Teuchos::BLAS<int, float>::AXPY(int const&, float const&, float const*, int const&, float*, int const&) const':
/fgs/fpierce/Al-Melt-Relocation/Trilinos/packages/teuchos/numerics/src/Teuchos_BLAS.cpp:155: undefined reference to `saxpy_'
../../src/libteuchosnumerics.a(Teuchos_BLAS.cpp.o): In function `Teuchos::BLAS<int, float>::COPY(int const&, float const*, int const&, float*, int const&) const':
/fgs/fpierce/Al-Melt-Relocation/Trilinos/packages/teuchos/numerics/src/Teuchos_BLAS.cpp:158: undefined reference to `scopy_'
../../src/libteuchosnumerics.a(Teuchos_BLAS.cpp.o): In function `Teuchos::BLAS<int, float>::DOT(int const&, float const*, int const&, float const*, int const&) const':
/fgs/fpierce/Al-Melt-Relocation/Trilinos/packages/teuchos/numerics/src/Teuchos_BLAS.cpp:165: undefined reference to `sdot_'
../../src/libteuchosnumerics.a(Teuchos_BLAS.cpp.o): In function `Teuchos::BLAS<int, float>::IAMAX(int const&, float const*, int const&) const':
/fgs/fpierce/Al-Melt-Relocation/Trilinos/packages/teuchos/numerics/src/Teuchos_BLAS.cpp:172: undefined reference to `isamax_'
......

**Comment by jhux2** [comment]
@trilinos/teuchos

**Comment by jhux2** [comment]
Please post your complete configure line.

**Comment by flintpierce** [comment]
I was able to get past the BLAS errors by specifying the following in my Trilinos configure file:

-D TPL_BLAS_LIBRARIES="/mylocation/libblas.a" and
-D BLAS_LIBRARY_DIRS="/mylocation/

I'm not sure if both are needed

After this, I found I was having gfortran issues I couldn't resolve, but thanks for the help anyway

**Comment by bartlettroscoe** [comment]
> After this, I found I was having gfortran issues I couldn't resolve, but thanks for the help anyway

You usually need to tack on -lgfortran as well with:

```
-D TPL_BLAS_LIBRARIES="/mylocation/libblas.a;-lgfortran" 
```
