### ISSUE TITLE
EXPORT_MAKEFILES:  Can't seem to get Makefile.export.* to show up

### ISSUE THREAD

**Issue by flintpierce** [trilinos/Trilinos#11081]
## Question
@trilinos/\<EXPORT_MAKEFILES\>

I need to generate Makefile.export.* for the Trilinos packages I am building for use with another cmake project (LAMMPS).  However, when I build Trilinos with:

-D Trilinos_ENABLE_EXPORT_MAKEFILES:BOOL=ON

I don't get any Makefile.export.* showing up.

**Comment by jhux2** [comment]
@flintpierce Did you have a look at https://github.com/trilinos/Trilinos/blob/master/INSTALL.rst#4building-against-installed-trilinos?

**Comment by jhux2** [comment]
@bartlettroscoe

**Comment by bartlettroscoe** [comment]
@flintpierce, support for export makefiles was removed a while back to accommodate the upgrade to modern CMake.  See #8598 and #9284.   For a deep technical discussion of this, see https://github.com/TriBITSPub/TriBITS/issues/299.

Sorry for the inconvenience.

**Comment by jhux2** [comment]
@flintpierce Please let us know if there's Trilinos documentation that references `Makefile.export` so that we can fix it.

**Comment by flintpierce** [comment]
https://trilinos.github.io/pdfs/TrilinosBuildReference.pdf  is where I found this.  I have been looking for a case where someone used Trilinos in LAMMPS.  I'm in the process of coupling LAMMPS to SIERRA Fuego, and for this I plan on using STK Coupling, which is part of Trilinos.  However, I've had trouble finding anyone (except one case) where Trilinos libraries were pulled into LAMMPS. The one case I found used export Makefiles.  I will have to keep looking.  Thanks for the help.

**Comment by bartlettroscoe** [comment]
At:

* https://docs.trilinos.org/files/TrilinosBuildReference.html#generating-export-files

it says:

> The project Trilinos can generate export files for external CMake projects or **external Makefile projects**.

That was mention of old support of export makefiles that did not get removed when support was removed.  I will fix that.
