### ISSUE TITLE
NOX:  NOX is disabled in the rhel7 cuda-11.4.2-uvm-off PR build

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#11085]
## Bug Report
@trilinos/nox, @trilinos/framework

### Description
It appears that NOX is being disable in the Trilinos PR rhel7 cuda-11.4.2-uvm-off PR builds.  You can see this at:

https://github.com/trilinos/Trilinos/blob/eb0988078d8bb6f6ba43e56f5caa10dc7c2ffc6b/packages/framework/ini-files/config-specs.ini#L1625

and in PR builds showing up on CDash like [here](https://trilinos-cdash.sandia.gov/build/485967/configure) showing:

```
Explicitly disabled packages on input (by user or by default):   ... NOX ...  9
```

### Steps to Reproduce
See https://github.com/trilinos/Trilinos/wiki/Reproducing-PR-Testing-Errors

**Comment by srbdev** [comment]
FYI I'm currently working on re-enabling some of these packages (and their relevant tests) for the rhel7 cuda-11.4.2-uvm-off PR builds. You can see the current progress on my [fork](https://github.com/srbdev/Trilinos/commits/framework-pr-cuda11-missing-packages). NOX is enabled again, and it built and passed tests successfully.

**Comment by sebrowne** [comment]
@bartlettroscoe I believe all packages are now enabled in that PR build (see [here](https://trilinos-cdash.sandia.gov/build/658871/configure) for a sample configure output)

**Comment by bartlettroscoe** [comment]
Yup, it looks like NOX is not being disabled in any of the PR builds (except the one Python-only build).  For example, for the [PR #11394 iteration](https://trilinos-cdash.sandia.gov/index.php?project=Trilinos&date=2022-12-15&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=PR-11394-test-&field2=subprojects&compare2=93&value2=NOX) we see NOX tests running in 5 of the 6 PR builds (one is the Python only build that does not test any Trilinos packages).
