### ISSUE TITLE
Tpetra: Failures in BlockCrsMatrix test

### ISSUE THREAD

**Issue by cgcgcg** [trilinos/Trilinos#11088]
## Bug Report
@trilinos/tpetra 

### Description
Tpetra's BlockCrsMatrix test fails in several builds.

https://testing.sandia.gov/cdash/testSummary.php?project=1&name=TpetraCore_BlockCrsMatrix_MPI_4&date=2022-09-30

**Comment by csiefer2** [comment]
Attempt 1 to reproduce failed.  Trying again.

**Comment by csiefer2** [comment]
@cgcgcg If the nightlies pass tonight, you can feel free to close this issue.
