### ISSUE TITLE
Stokhos:  Stokhos using deprecated and removed function cusparseScsrmv() (#10954)

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#11084]
## Bug Report

@trilinos/stokhos 

### Description

When attempting to upgrade the TriBITS/Trilinos usage of CUDA (changing from `find_package(CUDA)` to `find_package(CUDATooklit)` to address #10954, see https://github.com/trilinos/Trilinos/issues/10954#issuecomment-1262363127), the testing against Trilinos for the PR rhel7 CUDA build reveled that Stokhos is using the deprecated and then removed function `cusparseScsrmv()` (see [CUSPARSE Library v10.1 documentation](https://docs.nvidia.com/cuda/archive/10.1/pdf/CUSPARSE_Library.pdf)).  I will post a Trilinos PR shortly that will show this error but in my local testing which I submitted to CDash [here](https://testing.sandia.gov/cdash/index.php?project=Trilinos&filtercount=3&showfilters=1&filtercombine=and&field1=groupname&compare1=61&value1=Experimental&field2=buildname&compare2=61&value2=tril-10954-cudatoolkit-1_rhel7_sems-cuda-11.4.2-sems-gnu-10.1.0-sems-openmpi-4.0.5_release_static_Volta70_no-asan_complex_no-fpic_mpi_pt_no-rdc_no-uvm_deprecated-on_no-package-enables&field3=buildstarttime&compare3=84&value3=now), you see the reported errors:

```
/fgs/rabartl/Trilinos.base2/Trilinos/packages/stokhos/src/kokkos/Cuda/Stokhos_Cuda_CrsMatrix.hpp(127): error: identifier "cusparseScsrmv" is undefined

/fgs/rabartl/Trilinos.base2/Trilinos/packages/stokhos/src/kokkos/Cuda/Stokhos_Cuda_CrsMatrix.hpp(171): error: identifier "cusparseDcsrmv" is undefined

/fgs/rabartl/Trilinos.base2/Trilinos/packages/stokhos/src/kokkos/Cuda/Stokhos_Cuda_CrsMatrix.hpp(458): error: identifier "cusparseScsrmm" is undefined

/fgs/rabartl/Trilinos.base2/Trilinos/packages/stokhos/src/kokkos/Cuda/Stokhos_Cuda_CrsMatrix.hpp(506): error: identifier "cusparseDcsrmm" is undefined

/fgs/rabartl/Trilinos.base2/Trilinos/packages/stokhos/src/kokkos/Cuda/Stokhos_Cuda_CrsMatrix.hpp(641): error: identifier "cusparseScsrmm" is undefined

/fgs/rabartl/Trilinos.base2/Trilinos/packages/stokhos/src/kokkos/Cuda/Stokhos_Cuda_CrsMatrix.hpp(706): error: identifier "cusparseDcsrmm" is undefined

6 errors detected in the compilation of "/fgs/rabartl/Trilinos.base2/Trilinos/packages/stokhos/test/UnitTest/Stokhos_KokkosArrayKernelsUnitTest_Cuda.cpp".
```

NOTE: CMake has deprecated the usage of the `FindCUDA.cmake` module (and it is not even listed in CMake documentation in later releases) so we have no choice but to make this change.

### Steps to Reproduce

I will post a Trilinos PR shortly that will show these errors and then you can reproduce on an 'ascicgpuXY' machine using the Trilinos PR rhel7 CUDA build.

**Comment by bartlettroscoe** [comment]
> There are portions of it that can, but there hasn't been enough of a programmatic driver to separate out what can and can't run without UVM.

@etphipp, okay, just wanted to make sure you were aware of this.  But the issue with `cusparseScsrmv()` still remains.  If someone were going to try to enable Stokhos with UVM enabled with CUDA 11, I think they would still see these build errors.

**Comment by etphipp** [comment]
I believe this is resolved now so closing. If you still run into trouble, please re-open.
