### ISSUE TITLE
checkin-test-sems.sh: how to control -j for make and ctest ?

### ISSUE THREAD

**Issue by ibaned** [trilinos/Trilinos#1109]
I'm trying to give separate `-j` arguments to `make` and `ctest` through `checkin-test-sems.sh`. This is the way I'm trying to do it:
```bash
../cmake/std/sems/checkin-test-sems.sh \
--do-all --make-options="-j16" --ctest-options="-j1"
```
But that runs the following make command:
```bash
make -j4 -j16
```
How do I make the first `-j4` disappear ?

**Comment by bartlettroscoe** [comment]
@ibaned,

The flag "-j4" default is getting set in your local-checkin-test-defaults.py file.  See the first note at:

* https://github.com/trilinos/Trilinos/wiki/Policies-%7C-Safe-Checkin-Testing

which states:

"After the first time checkin-test-sems.sh is run, optionally edit the file local-checkin-test-defaults.py for your machine (see comments inside of the script checkin-test-sems.sh itself)."

Just remove the "-j4" option and put in your defaults for your machine.  For example, set local-checkin-test-defaults.py to be:

```
defaults = [
  "--make-options=-j16",
  "--ctest-options=-j1",
  "--ctest-timeout=300",
  "--disable-packages=PyTrilinos,Claps,TriKota",
  "--skip-case-no-email",
  ]
```

If that does now work, please let me know.

But why would you want to run the Trilinos test with just one process with `-j1`?  I routinely run with the build and ctest with 16 processes and it seems to work just fine.

**Comment by ibaned** [comment]
Thanks, I'll reopen this if that does not work. I'm still working out what the right values are, I just wanted to control the two separately.
