### ISSUE TITLE
Seacas:  Skybridge build error relating to MPI_init

### ISSUE THREAD

**Issue by ikalash** [trilinos/Trilinos#11126]
## Bug Report
@trilinos/seacas 

### Description
We started getting a build error in the Trilinos skybridge nightly build related to seacas: 

```
https://sems-cdash-son.sandia.gov/cdash/viewBuildError.php?buildid=40281
```

https://sems-cdash-son.sandia.gov/cdash/viewBuildError.php?buildid=40281

This is with the Intel 18.0.3.20180410 compiler.  Do you have any insight into what is going wrong here?  All the other nightly builds are fine.

**Comment by gsjaardema** [comment]
The `pepu` executable is a parallel build of `epu` and should only be enabled if the underlying build is parallel and the CMake symbol `TPL_ENABLE_MPI` is true and also `SEACAS_HAVE_MPI` is defined.

For some reason, it looks like this is a serial build, but those symbols are somehow defined?  Or there is some other problem with the logic of determining whether MPI is enabled...

This looks like it is a serial build, but for some reason, `pepu` seems to think it is a parallel build...

**Comment by gsjaardema** [comment]
OK, it looks like something reordered the include files in the `pepu.C` file and the `mpi.h` is being included *after* the `epu.C`, ...

Not sure why that doesn't cause issues on other platforms; will fix soon.

**Comment by ikalash** [comment]
Thanks for looking into this @gsjaardema!  Just to clarify, the build on skybridge with the problem has MPI, so it is not a serial build.

**Comment by ikalash** [comment]
I can confirm that this has been fixed. Thanks @gsjaardema !
