### ISSUE TITLE
Panzer: compile times on CUDA

### ISSUE THREAD

**Issue by rppawlo** [trilinos/Trilinos#1113]
The compile times for panzer on CUDA have shot through the roof. The affected object files have to do with building Intrepid2 bases. These files used to have negligible compile times but each object file is now taking 30 to 40 minutes.

Suspect that the offending commit is:
b12febbdfa10fd1da20eccc91180fb7a0943ba1d
as this added the Cn bases (previously it was just C1 and C2 bases). Will look into this more tomorrow. 
@trilinos/panzer 
@bathmatt 
@kyungjoo-kim 
@eric-c-cyr

**Comment by bathmatt** [comment]
@rppawlo are you only seeing these times in cuda/nvcc or all platforms?

**Comment by rppawlo** [comment]
Was not the commit in the comment above. Backed up to well before that and still have slow build times. About 7 files are each taking ~45 minutes each to build. BasisValues2 is the first object we encounter. Now suspect that the transition to the refactor branch of Intrepid2 is when this started.

**Comment by kyungjoo-kim** [comment]
It seems that Intrepid2 is the problem guy. Probably we can look at basisvalues file first. 

Some questions are ....
1. Is it due to FadType ? Can we isolate this problem from the RealType ? 
2. If this FadType is known during compilation, can we do explicit instanciation of intrepid2 inside of panzer disc-fe library (not intrepid2 library) ? 

BTW, Also can we monitor the compile time for each file in the nightly tests ?

**Comment by rppawlo** [comment]
> @rppawlo are you only seeing these times in cuda/nvcc or all platforms?

CUDA only.  On my desktop with OpenMP node, a clean build of the panzer disc-fe library took two minutes.

**Comment by rppawlo** [comment]
> Is it due to FadType ? Can we isolate this problem from the RealType ?

Seems to affect all scalar types. We do explicit instantiation of the BasisValues2 object. I disabled the FAD (Hessian already disabled) type so just the double object is being built and it took 11 minutes.

**Comment by bathmatt** [comment]
OK, at 140 minutes and counting
57985 pts/14   R+   140:48 cicc -arch compute_35 -m64 -ftz=0 -prec_div=1 -prec_sqrt=1 -fmad=1 -nvvmir-library /home/projects/x86-64-haswell-nvidia/cuda/7.5.18/bin/../nvvm/libdevice/libdevice.compute_35.10.bc --orig_src_file_name /home/mbetten/workspace/Trilinos/packages/panzer/disc-fe/src/Panzer_IntegrationValues2.cpp /tmp/tmpxft_0000d26f_00000000-10_Panzer_IntegrationValues2.cpp3.i -o /tmp/tmpxft_0000d26f_00000000-6_Panzer_IntegrationValues2.ptx

**Comment by crtrott** [comment]
Hm I didn't have any issues last week when going through the integration. Do you have a config file?

**Comment by bathmatt** [comment]
@crtrott are you compiling panzer?  I know typically that is left out.

**Comment by crtrott** [comment]
Nope I always do. I compile the whole shulabub, ~1700 Test Executables, 120GB as static build with Cuda.

**Comment by crtrott** [comment]
There is actually test reports here for nightly testing: http://testing.sandia.gov/cdash/index.php?project=Trilinos&parentid=2774774, Panzer is by far the longest build time (1:24) followed by MueLu with 21min and Tpetra with 8 mins.

**Comment by bathmatt** [comment]
Odd, I'm approaching 4 hours on 1 file.  @crtrott what config file do you want?  Can I get you something for hansen?

**Comment by kyungjoo-kim** [comment]
What is memory size on the machines ? It looks like Roger and Matt compile the code on their desktops and Chrisitian compiles on a server machine so that it may not require external space ?

**Comment by crtrott** [comment]
This is the config files from apollo in the test driver directory, or on other occasions the samplescripts/SandiaSems directory where I use the configure_testbeds* scripts.

**Comment by bathmatt** [comment]
Shiller, 128GB

**Comment by crtrott** [comment]
Same memory as my machine.

**Comment by bathmatt** [comment]
I can't use that script on shiller, I get errors

Do you have a configure-testbed somewhere that works on hansen?
[ 24%] Linking CXX shared library libstk_util_use_cases.so
[ 25%] Built target KokkosCore_UnitTest_Serial
/home/projects/x86-64-haswell/bintuils/2.25.0/lib/../x86_64-unknown-linux-gnu/bin/ld:
/home/projects/x86-64-haswell-nvidia/boost/1.59.0/openmpi/1.10.0/gcc/4.8.4/cuda/7.5.18/lib/libboost_program_options.a(cmdline.o):
relocation R_X86_64_32 against
`_ZZN5boost9function1ISt6vectorINS_15program_options12basic_optionIcEESaIS4_EERS1_ISsSaISsEEE9assign_toINS_3_bi6bind_tIS6_NS_4_mfi3mf1IS6_NS2_6detail7cmdlineES9_EENSC_5list2INSC_5valueIPSH_EENS_3argILi1EEEEEEEEEvT_E13stored_vtable'
can not be used when making a shared object; recompile with -fPIC
/home/projects/x86-64-haswell-nvidia/boost/1.59.0/openmpi/1.10.0/gcc/4.8.4/cuda/7.5.18/lib/libboost_program_options.a:
error adding symbols: Bad value
collect2: error: ld returned 1 exit status
make[2]: ***
[packages/stk/stk_util/stk_util/use_cases/libstk_util_use_cases.so.12.11]
Error 1
make[1]: ***
[packages/stk/stk_util/stk_util/use_cases/CMakeFiles/stk_util_use_cases.dir/all]
Error 2
make[1]: *** Waiting for unfinished jobs....

**Comment by crtrott** [comment]
Can I get a as small as possible configure file to show the issue?

**Comment by crtrott** [comment]
Which script were you using? On shiller you probably need to use the *sems* one instead of the normal testbed one since the env variables for the modules are different.

**Comment by crtrott** [comment]
I am trying to build now on hansen, but it is incredibly slow. Even just doing an ls hangs for several seconds.

**Comment by etphipp** [comment]
I noticed that too.  User artoth is swamping the machine.  I am currently building on hansen on one of the compute nodes.

**Comment by rppawlo** [comment]
@etphipp I checked with Alex (artoth). He launched one build with -j8. It should not be his build, but he did kill it to be safe. Looks like the node went down completely now.

**Comment by etphipp** [comment]
The usage was at 24 and I just looked at who was the top user, assuming they were related.  They probably weren't.

**Comment by bathmatt** [comment]
we cannot build drekar under cuda anymore because of these compile times.  It has only a 12 hour time limit...  It was almost done after 12 hours.  

srun: Force Terminated job 1000646
slurmd[shiller04]: *** STEP 1000646.0 CANCELLED AT 2017-03-10T04:45:19 DUE TO TIME LIMIT ***

I can get a configure to run on hansen to show this to help dog this down.  How do we proceed?  This is getting pretty critical.

**Comment by bathmatt** [comment]
I've attached a small script whcih shows this on hansen.  
[config.txt](https://github.com/trilinos/Trilinos/files/834843/config.txt)

**Comment by jhux2** [comment]
@bathmatt What I mean is, have you seen this problem occur without CUDA?

**Comment by rppawlo** [comment]
No longer an issue.
