### ISSUE TITLE
Trilinos master is broken for Albany

### ISSUE THREAD

**Issue by ibaned** [trilinos/Trilinos#1114]
This issue is part short-term and part long-term.
In the short term, kokkos/kokkos-kernels#8 is broken in Trilinos master, and a fix has been pushed to Trilinos develop (0a2eee9). I'd like someone to merge develop into master to get this fix through.

In the long term, it would be highly beneficial to include an application that uses Trilinos as part of the CI process that determines when to merge develop into master. Any application that uses the Tpetra stack would have failed to build due to kokkos/kokkos-kernels#8, but no internal Trilinos tests could have caught it.

I'd be more than happy to work with the Trilinos team to set up a minimal Albany build as an additional CI test, and I think that the same goal could be accomplished using any other application, if there is another application that suits the role better.

@trilinos/framework @jwillenbring @bmpersc

**Comment by jjellio** [comment]
@ibaned Some form of installation testing should be done for shared and static builds. This could be solved in the log term, by having the unit test and examples living in separate repositories. (like many other large projects do, gcc for example). This would partially satisfy your request. The issues you listed also hit me, with another app. I don't think the CI framework needs to use a complicated app though. Simply being able to install the libraries, *then* build and execute the unit tests and/or examples would cover much of this. Ultimately, this is how Trilinos is used... built -> installed and then it becomes a TPL for some code base.

**Comment by ibaned** [comment]
@jjellio I agree. Even unit tests that build off the installed libraries/headers would catch these types of issues.

It seems the master branch has been updated with the fix at this point (thanks!), so I think I'll close this for the short term issue. I hope the long term issue gets some consideration.

**Comment by mhoemmen** [comment]
Thanks for the fix!  Christian pushed the fix to KokkosKernels.
