### ISSUE TITLE
STK: Compile errors due to ambiguous namespace

### ISSUE THREAD

**Issue by mcarlson801** [trilinos/Trilinos#11153]
## Bug Report
@trilinos/STK

### Description
Starting from commit `7bacda8`, Trilinos with STK enabled fails to compile on some machines (in our case, Perlmutter with gcc/11.2.0 compilers) with errors stemming from the following:

```packages/stk/stk_util/stk_util/parallel/MPIDatatypeGenerator.hpp:16:31: error: 'size_t' has not been declared```

The `std::` namespace isn't made explicit when declaring variables of `size_t` in `MPIDatatypeGenerator.hpp` and some compilers throw an error. 

I've verified that changing `size_t` to `std::size_t` in `MPIDatatypeGenerator.hpp` fixes the errors.

**Comment by alanw0** [comment]
Thanks for the report, we'll get this taken care of.

**Comment by alanw0** [comment]
Should have closed this when the stk snapshot was merged 10-19-22.
