### ISSUE TITLE
kokkos: new error during cmake 3.23.1 configuration related to HPX not being found

### ISSUE THREAD

**Issue by glhenni** [trilinos/Trilinos#11152]
## Bug Report
@trilinos/\<kokkos\>

We just started getting the error below during configuration via cmake 3.23.1. I **think** this followed an update of Tribits, although that could just be a coincidence. We're using kokkos as included in trilinos/develop (as of sha1:122be6e2) and we're using tribits/master (as of sha1:63d71817). Maybe @bartlettroscoe might have some ideas?
```
CMake Error at /ascldap/users/glhenni/TriBITS/tribits/core/package_arch/TribitsReadDepsFilesCreateDepsGraph.cmake:787 (message):
  Error, the package 'HPX' is listed as a dependency of the package
  'KokkosCore' but the package 'HPX' is either not defined or is listed later
  in the package order.  This may also be an attempt to create a circular
  dependency between the packages 'HPX' and 'KokkosCore' (which is not
  allowed).  Check the spelling of 'HPX' or see how it is listed in a call to
  tribits_repository_define_packages() in relation to 'KokkosCore'.  To
  ignore/disable the undefined package 'HPX', set the cache variable
  tcad-charon_ASSERT_DEFINED_DEPENDENCIES=IGNORE.
Call Stack (most recent call first):
  /ascldap/users/glhenni/TriBITS/tribits/core/package_arch/TribitsReadDepsFilesCreateDepsGraph.cmake:624 (tribits_abort_on_missing_package)
  /ascldap/users/glhenni/TriBITS/tribits/core/package_arch/TribitsReadDepsFilesCreateDepsGraph.cmake:572 (tribits_set_dep_packages__handle_undefined_pkg)
  /ascldap/users/glhenni/TriBITS/tribits/core/package_arch/TribitsReadDepsFilesCreateDepsGraph.cmake:498 (tribits_set_dep_packages)
  /ascldap/users/glhenni/TriBITS/tribits/core/package_arch/TribitsReadDepsFilesCreateDepsGraph.cmake:1031 (tribits_process_package_dependencies_lists)
  /ascldap/users/glhenni/TriBITS/tribits/core/package_arch/TribitsReadDepsFilesCreateDepsGraph.cmake:966 (tribits_read_subpackage_deps_file_add_to_graph)
  /ascldap/users/glhenni/TriBITS/tribits/core/package_arch/TribitsReadDepsFilesCreateDepsGraph.cmake:302 (tribits_read_package_subpackage_deps_files_add_to_graph)
  /ascldap/users/glhenni/TriBITS/tribits/core/package_arch/TribitsReadDepsFilesCreateDepsGraph.cmake:189 (tribits_read_toplevel_package_deps_files_add_to_graph)
  /ascldap/users/glhenni/TriBITS/tribits/core/package_arch/TribitsReadDepsFilesCreateDepsGraph.cmake:84 (tribits_read_all_package_deps_files_create_deps_graph)
  /ascldap/users/glhenni/TriBITS/tribits/core/package_arch/TribitsReadAllProjectDepsFilesCreateDepsGraph.cmake:80 (tribits_read_deps_files_create_deps_graph)
  /ascldap/users/glhenni/TriBITS/tribits/core/package_arch/TribitsProjectImpl.cmake:154 (tribits_read_all_project_deps_files_create_deps_graph)
  /ascldap/users/glhenni/TriBITS/tribits/core/package_arch/TribitsProject.cmake:92 (tribits_project_impl)
  CMakeLists.txt:61 (TRIBITS_PROJECT)
```

**Comment by glhenni** [comment]
Just to clarify, we are not setting any HPX related configuration variable to TRUE/ON via cmake. In fact we have not changed any configuration variable recently. This error just "spontaneously" started today.

**Comment by bartlettroscoe** [comment]
@glhenni, this is definingly due to the merge of:

* https://github.com/TriBITSPub/TriBITS/pull/530

See:

* https://github.com/TriBITSPub/TriBITS/blob/515df6c76246b28b8bef1cd637622eda0bb49e9f/tribits/CHANGELOG.md#2022-10-11

I suspected there were TPL dependencies being specified in Trilinos for TPLs that were not even being defined.

I can put in a Trilinos PR to fix this problem (even before I update the snapshot TriBITS 'master' is put into Trilinos).

If you need to get this to work urgently, you can set the following cache var when configuring for now:

```
   -D tcad-charon_ASSERT_DEFINED_DEPENDENCIES=IGNORE \
```

Otherwise, the Trilinos PR should be in shortly.

**Comment by bartlettroscoe** [comment]
FYI: PR #11154 should fix this.

**Comment by bartlettroscoe** [comment]
This is not completed until PR #11152 is updated and merged.  Reopening until that occurs.

**Comment by bartlettroscoe** [comment]
@glhenni, with the merge of PR #11154 11 hours ago, this should be resolved.  Can you confirm?

**Comment by glhenni** [comment]
Going forward I've changed all of charon's jobs to use tribits within trilinos to avoid this problem in the future, however, I just completed a build using github Tribits/master and indeed the error is gone. Thanks @bartlettroscoe

**Comment by bartlettroscoe** [comment]
> Going forward I've changed all of charon's jobs to use tribits within trilinos to avoid this problem in the future

@glhenni, I think that is a reasonable thing to do.  It is just too expensive for me to test all of Trilinos against every update to TriBITS 'master'.  (But I sync Trilinos 'master' into Trilinos 'develop' pretty frequently so customers will see the issues then.)

**Comment by bartlettroscoe** [comment]
> I just completed a build using github Tribits/master and indeed the error is gone. Thanks @bartlettroscoe

Closing as complete.
