### ISSUE TITLE
Muelu:  obsolete headers?

### ISSUE THREAD

**Issue by ikalash** [trilinos/Trilinos#11176]
## Bug Report
@trilinos/muelu 

### Description
We are getting build errors in the Albany nightlies due to the following error: 

```
/nightlyAlbanyTests/Results/Trilinos/build/install/include/Thyra_MueLuPreconditionerFactory_def.hpp:50:10: fatal error: MueLu_TpetraOperatorAsRowMatrix.hpp: No such file or directory
```
https://sems-cdash-son.sandia.gov/cdash/viewBuildError.php?buildid=40780

Did MueLu_TpetraOperatorAsRowMatrix.hpp go away or get renamed? Seems Thyra_MueLuPreconditionerFactory_def.hpp needs to be update to reflect the change.

**Comment by mayrmt** [comment]
If I'm not mistaken, PR #11171 is about to add the missing header to the Trilinos installation.

**Comment by ikalash** [comment]
@mayrmt : ok, great, I am glad to hear this is getting taken care of.

**Comment by cgcgcg** [comment]
Should be fixed.

**Comment by ikalash** [comment]
@cgcgcg : great, I'll check tomorrow that  things are back up for Albany.

**Comment by ikalash** [comment]
I can confirm that this issue has been resolved.  Thanks!
