### ISSUE TITLE
Thyra:  How to set convergence tolerance for Krylov solver from code

### ISSUE THREAD

**Issue by kaiserls** [trilinos/Trilinos#11173]
## Question
@trilinos/\<Thyra\>
@searhein 

### What are you wondering about? 
I am wondering how to set the Parameter "Convergence Tolerance" for a Krylov Solver, which is hidden behind the Thyra interface, from the code and not using the xml parameter file.

### How does your question fit into what you're trying to do?
I want to compare the performance of two different preconditioners for the linear system $Ax=b$. To do this I measure the runtime till the preconditioned CG method solves the problem up to certain accuracy, which is typically measured by the residual.
One preconditioner however requires rewriting the system to an equivalent one $A \tilde{x} = \tilde{b}$. I use the zero vector as initial solution and therefore the starting residual is different for each system. Using the same relative convergence tolerance gives results with different accuracy (and using an absolute convergence has to be adapted to the problem size). Therefore I would like to multiply the convergence tolerance with the factor $\frac{\| b\|}{\tilde{\|b\|}}$. This factor is only available after setting up the preconditioner and rewriting the system. See also Issue #9922

### Current code
```c++
Stratimikos::DefaultLinearSolverBuilder linearSolverBuilder;
Stratimikos::enableFROSch<LO,GO,NO>(linearSolverBuilder);
linearSolverBuilder.setParameterList(parameterList)
RCP<LinearOpWithSolveFactoryBase<SC> > solverFactory = Thyra::createLinearSolveStrategy(linearSolverBuilder)

// preconditioner
auto precFactory = solverFactory->getPreconditionerFactory();
RCP<Thyra::PreconditionerBase<SC> > prec = precFactory->createPrec();
Thyra::initializePrec<double>(*precFactory, K_thyra, prec.ptr());

// solver
Teuchos::RCP<Thyra::LinearOpWithSolveBase<SC> > solveOp = solverFactory->createOp(); 
Thyra::initializePreconditionedOp<double>(*solverFactory, K_thyra, prec, solveOp.ptr());   

//op to FROSch Operator
auto nonConstOp = rcp_const_cast<LinearOpBase<SC>>(prec->getUnspecifiedPrecOp());
auto froschLinearOp = rcp_dynamic_cast<Thyra::FROSchLinearOp<SC, LO, GO, NO>,LinearOpBase<SC>>(nonConstOp, true);

// Calculate residual and modify system
SC residualBeforePre=norm(*(thyraBModified->col(0)));
froschLinearOp->preSolve(thyraBModified.ptr());
SC residualAfterPre=norm(*(thyraBModified->col(0)));

if (Comm->getRank()==0) cout<<"Norm of rhs before: " << residualBeforePre << "; Norm of rhs after preSolve: " <<residualAfterPre << endl;

double conv_crit_rel_to_start_res = 1e-6;
double start_res = sqrt(RepeatedMaps[0]->getGlobalNumElements()* 1.*1.) ;//1 because rhs is 1 everywhere
double conv_tol = 1e-6 *  residualBeforePre / residualAfterPre;
```

**Comment by cgcgcg** [comment]
I'm assuming you're using a Krylov solver from Belos? What do you set "Residual Scaling" to?

**Comment by kaiserls** [comment]
I didn't set it at all, yet. I assumed (due to reading the documentation for PseudoBlockGmresSolMgr) that it used the initial residual or the preconditioned initial residual as default.

1. I want to solve them to the same absolute tolerance $\tau=\tilde{\tau}$, but I want this absolut tolerance to scale with the problem size like the relative residual does. I guess I could use the following setting otherwise:
```xml
<Parameter name="Implicit Residual Scaling" type="string" value="None"/>
<Parameter name="Explizit Residual Scaling" type="string" value="None"/>
```
2. Yes, exactly.

**Comment by cgcgcg** [comment]
Ok. So you want indeed to switch of the residual scaling, and then just modify the tolerance for the second solve. What you could try is to change the tolerance in the parameter list for the second solve and then re-setup the linear solver.

**Comment by kaiserls** [comment]
```c++
//TODO: Make this work for Block GMRES
RCP<ParameterList> krylovList =  sublist(sublist(sublist(sublist(parameterList,"Linear Solver Types"),"Belos"),"Solver Types"),"Pseudo Block CG", true);
double convergenceTolerance = krylovList->get<double>("Convergence Tolerance");
double scaledConvergenceTolerance = convergenceTolerance *  residualBeforePre / residualAfterPre;
krylovList->set("Convergence Tolerance", scaledConvergenceTolerance);
// Re setup solver
linearSolverBuilder.setParameterList(parameterList);
solverFactory = Thyra::createLinearSolveStrategy(linearSolverBuilder);
solveOp = solverFactory->createOp(); 
Thyra::initializePreconditionedOp<double>(*solverFactory, K_thyra, prec, solveOp.ptr());
```

**Comment by cgcgcg** [comment]
I wonder whether you actually need to re-create `solveOp`. Some solvers/preconditioners have reuse capabilities that allow to not entirely reallocate.

**Comment by kaiserls** [comment]
Actually, I don't even need to create the object `solveOp` before, just the `solverFactory` to create the preconditioner. Then just the solverFactory is re-created. Thank you for the hint.

On my laptop it takes 3e-4 seconds to execute the complete code block above while the whole program took 25 seconds to execute, so it shouldn't be performance critical. I will keep the timing block for the execution on the cluster to see how long it takes there.

**Comment by cgcgcg** [comment]
Can this issue be closed?

**Comment by kaiserls** [comment]
Yes, thank you for your help!
