### ISSUE TITLE
failing panzer tests on cuda

### ISSUE THREAD

**Issue by bathmatt** [trilinos/Trilinos#1118]
@rppawlo @kyungjoo-kim IntegrationValues2 is failing..
I'm dogging down the failing tests on cuda.  Here is one I could use some help with.  Not sure what is going on.

In integration_values2.cpp we have a test

`   TEST_FLOATING_EQUALITY(int_values_vol.ip_coordinates(0,0,0), 
                           realspace_x_coord_1, 1.0e-8);`

The first value is NaN.  It is computed here

    int_values_vol.evaluateValues(node_coordinates);

This calls down to a call in Intrepid2_CubatureControlVolumeDef.hpp which looks like this

`
   // numNodesPerCell is maximum 8; this repeated run is necessary because of cell tools input consideration
    for (ordinal_type node=0;node<numNodesPerCell;++node) {
      auto subcvJacobianNode    = Kokkos::subdynrankview(subcvJacobian,    Kokkos::ALL(), node, Kokkos::ALL(), Kokkos::ALL(), Kokkos::ALL());
      auto subcvCoordsNode      = Kokkos::subdynrankview(subcvCoords,      Kokkos::ALL(), node, Kokkos::ALL(), Kokkos::ALL());
      auto subcvJacobianDetNode = Kokkos::subdynrankview(subcvJacobianDet, Kokkos::ALL(), node, Kokkos::ALL());
      
      CellTools<SpT>::setJacobian(subcvJacobianNode,    // C, P, D, D
                                  subcvCubaturePoints_, //    P, D
                                  subcvCoordsNode,      // C, N, D
                                  subcvCellTopo_);

      CellTools<SpT>::setJacobianDet(subcvJacobianDetNode,  // C, P
                                     subcvJacobianNode);    // C, P, D, D
    }
    `

The setJacobian call returns an invalid jacobian

(cuda-gdb) p subcvJacobianNode.m_map .m_handle [0]
$95 = -nan(0x8000000000000)
(cuda-gdb) 

The points look to be correct though, i know they are set correctly.

This code should be tested somewhere, is there a good test for getCubature somewhere?  Have either of you seen it?

I have bounds checking on btw.

**Comment by bathmatt** [comment]
BTW, It calls thorugh this with GRAD operator
     Impl::Basis_HGRAD_QUAD_C1_FEM::
        getValues<ExecSpaceType>( outputValues,
                                  inputPoints,
                                  operatorType );

**Comment by bathmatt** [comment]
It looks like basis values 2 is also failing.  

7. basis_values_control_vol_hgrad_UnitTest ... 
 Cell 0 = (0, 0) (0.5, 0) (0.5, 0.5) (0, 0.5) 
 Cell 1 = (0.5, 0) (1, 0) (1, 0.5) (0.5, 0.5) 
 Cell 2 = (0, 0.5) (0.5, 0.5) (0.5, 1) (0, 1) 
 Cell 3 = (0.5, 0.5) (1, 0.5) (1, 1) (0.5, 1) 
 basis_values.basis_scalar.extent_int(0) = 4 == num_cells = 4 : passed
 basis_values.basis_scalar.dimension(1) = 4 == 4 = 4 : passed
 basis_values.basis_scalar.dimension(2) = 4 == num_qp = 4 : passed
 basis_values.basis_scalar(cell,0,i) = -nan == 0.25*(1.0-x)*(1.0-y) = -nan : FAILED ==> /home/mbetten/Trilinos/Trilinos/packages/panzer/disc-fe/test/core_tests/basis_values2.cpp:964

**Comment by kyungjoo-kim** [comment]
This is control volume hgrad. I saw this failed tests. It is similar to the problems we saw before (either space does not match or there is missing synchronization between host and device). When I see the failed test, I kind of think that I would not pay attention on it unless someone complains about it. 

Could you measure the priority of this ? How important to make this test pass on cuda ?  I am wondering if your application code needs this control volume basis.

**Comment by bathmatt** [comment]
I have kokkos bounds check on btw. 
Question
@eric-c-cyr 
@rppawlo 
Are these tests going to cause any other tests to fail?  i.e. is this used in any of the drekar tests or panzer tests?

I'd say the priority is based on that.

**Comment by eric-c-cyr** [comment]
These control volume tests are important for other applications. Drekar does not currently use any control volume code. However, we need to maintain these tests for other customers.

**Comment by kyungjoo-kim** [comment]
Then the question is if the other application (charon) uses cuda ? I believe that this failures only happen on cuda. I just want to priotize my work items.

**Comment by eric-c-cyr** [comment]
I don't believe it does. @karapeterson?

**Comment by karapeterson** [comment]
Charon doesn't currently use cuda, but we do depend heavily on the control volume code.

**Comment by bathmatt** [comment]
Here is what I think the plan forward is.  Have @kyungjoo-kim make a test in intrepid2 that tickles this issue.  Then we disable this test in panzer/cuda until the intrepid2 test is clean.

@rppawlo or @eric-c-cyr do you know how to disable a test under cuda?  I think there is a flag KOKKOS_USE_CUDA

**Comment by rppawlo** [comment]
@kyungjoo-kim any chance we could get the control volume code fixed for cuda builds soon?

**Comment by kyungjoo-kim** [comment]
Okay. I am back ABQ and will work it out tomorrow.

**Comment by rppawlo** [comment]
@kyungjoo-kim Looks like Matt temporarily disabled the failing tests for cuda. You will have to revert this commit to reproduce:

4bf84b8bdd21acf847c56d36afee79e83701ab18

**Comment by kyungjoo-kim** [comment]
I pushed a fix. Panzer unit tests are passed now. Please check if any further problem is.

**Comment by kyungjoo-kim** [comment]
@bathmatt 

Based on the nightly test on apolo, panzer unit tests on cuda are passed. If your code does not produce a problem, could we close this ticket ? 

http://testing.sandia.gov/cdash/buildSummary.php?buildid=2836566

**Comment by bathmatt** [comment]
OK, have you disabled the test ifdef out?

**Comment by kyungjoo-kim** [comment]
yes I removed the ifdef.

**Comment by bathmatt** [comment]
OK, if it isn't closed tomorrow I probably forgot to look :).  Please ping
me

**Comment by kyungjoo-kim** [comment]
Hi @bathmatt . Ping~

**Comment by bathmatt** [comment]
Sorry, closing, thanks!!
