### ISSUE TITLE
Tpetra, Kokkos-Kernels: Error linking against Trilinos libraries when MKL is a TPL

### ISSUE THREAD

**Issue by sphamil** [trilinos/Trilinos#11189]
@trilinos/tpetra
@trilinos/kokkos-kernels

### Description
We're encountering a problem linking against Trilinos 13.4 (undefined reference to `spmv`) from an external project when it is built with Intel MKL as a TPL. No issue is observed with Trilinos 13.2. When building with `develop` we get a Trilinos build error that I believe is identical to #11033. When MKL is disabled as a TPL (but still used as the BLAS/LAPACK implementation), no error is observed. Disabling MKL is not a viable option as the Pardiso MKL solver is our primary preconditioner option for the application.

### Steps to Reproduce
1. Tag:  trilinos-release-13-4-0
1. Configure script: [do-configure.txt](https://github.com/trilinos/Trilinos/files/9864018/do-configure.txt)
1. Configure log: [config.log.txt](https://github.com/trilinos/Trilinos/files/9864090/config.log.txt)
1. Trilinos build log:  [build.log.txt](https://github.com/trilinos/Trilinos/files/9864088/build.log.txt)
1. Build log from external project (link error): [external-build.log.txt](https://github.com/trilinos/Trilinos/files/9864036/external-build.log.txt)
1. Result of `nm --demangle libtpetra.so | grep "spmv("`: [nm_tpetra.txt](https://github.com/trilinos/Trilinos/files/9864082/nm_tpetra.txt)
1. Result of `nm --demangle libkokkoskernels.so | grep "spmv("`: [nm_kokkoskernels.txt](https://github.com/trilinos/Trilinos/files/9864084/nm_kokkoskernels.txt)

Actual external project is export controlled, but I can put together a minimal external project that reproduces the issue if necessary.

**Comment by cgcgcg** [comment]
@trilinos/tpetra @trilinos/kokkos-kernels

**Comment by rppawlo** [comment]
@srajama1

**Comment by sphamil** [comment]
Small update, linking from an external package is not necessary to reproduce. Turning on `Trilinos_ENABLE_TESTS` in the above configure script results in link errors from the Tpetra/Kokkos-Kernels unit tests.

**Comment by csiefer2** [comment]
This does seem to be identical to #11033 @lucbv said he'd look into it.
