### ISSUE TITLE
Teuchos:  Incorrect Type in Lapack interfaces

### ISSUE THREAD

**Issue by waveman68** [trilinos/Trilinos#11187]
## Bug Report
@trilinos/Teuchos

### Description
Parameter beta should be complex like alpha, but it is double (c.f., reference LAPACK [lapacke.h](https://github.com/Reference-LAPACK/lapack/blob/master/LAPACKE/include/lapack.h) on GitHub).

```c++
void PREFIX ZGGEV_F77(Teuchos_fcd, Teuchos_fcd, const int *n, std::complex<double> *A, const int *lda, std::complex<double> *B, const int *ldb, std::complex<double> *alpha, double *beta, double *vl, const int *ldvl, double *vr, const int *ldvr, double *work, const int *lwork, double *rwork, int *info);
```

### Steps to Reproduce
1. SHA1:  [Trilinos GitHub](https://github.com/trilinos/Trilinos/blob/64d50199f342860b00d16cb78cb5730de66438b9/packages/teuchos/numerics/src/Teuchos_LAPACK_wrappers.hpp)

**Comment by hkthorn** [comment]
@waveman68 Got it.

**Comment by hkthorn** [comment]
closing this issue and reopening #11168 because it summarizes the current problem with the Teuchos LAPACK wrappers.
