### ISSUE TITLE
Zoltan2: Uninitialized Kokkos execution space issue encountered while upgrading from trilinos 12.14.1 to 13.0.1

### ISSUE THREAD

**Issue by adityakpandare** [trilinos/Trilinos#11197]
## Question
@trilinos/Zoltan2

I am trying to update my code base to use trilinos 13.0.1 (https://github.com/trilinos/Trilinos/commit/4796b92fb0644ba8c531dd9953e7a4878b05c62d), I get an error `Constructing View and initializing data with uninitialized execution space`, originating from Zoltan2. Previously, our code used the Zoltan2 package from trilinos release 12.14.1, and was able to invoke Zoltan2 without such a problem. As far as I can see, Zoltan2 has no change between these two trilinos releases. [Here](https://github.com/quinoacomputing/quinoa/blob/develop/src/LoadBalance/ZoltanInterOp.cpp)'s our code where Zoltan2's `PartitioningProblem` and `solve` are called.

What am I missing when I migrate from release 12.14.1 to 13.0.1? Please let me know what information I can provide to clarify my question.

**Comment by jhux2** [comment]
@zoltan2 @egboman

**Comment by jhux2** [comment]
@trilinos/zoltan2

**Comment by cgcgcg** [comment]
What's Tpetra node types are enabled in your build? Looks like you're using whatever Tpetra sets as the default:
https://github.com/quinoacomputing/quinoa/blob/1bd04a39557023f7b49213191fe61849c7443622/src/LoadBalance/ZoltanInterOp.cpp#L143

**Comment by adityakpandare** [comment]
@cgcgcg: That's correct, we do not specify the node type, expecting Tpetra's defaults to be okay (https://docs.trilinos.org/dev/packages/tpetra/doc/html/Tpetra_Lesson02.html). Is my understanding incorrect?

**Comment by jhux2** [comment]
@adityakpandare It appears that ZoltanInterOp doesn't have any dependencies outside of Zoltan2, i.e., compiling that file by itself should be enough to reproduce the error.  Is this right?

**Comment by adityakpandare** [comment]
@jhux: You're correct, in that ZoltanInterOp does not have dependencies other than Zoltan2. However, ZoltanInterOp is only defining a class and a function `geomPartMesh()` (which calls Zoltan2's `PartitioningProblem` and `solve`), and does not actually call `geomPartMesh()`. That is done by code external to ZoltanInterOp. So compiling ZoltanInterOp will not really reproduce this error. For that, we would have to write code that calls `geomPartMesh`. Does that answer your question?

**Comment by jhux2** [comment]
@adityakpandare Yes, that answers my question. Would you be able to provide a minimal reproducer that includes a call to geomPartMesh?  This would help the @trilinos/zoltan2 team.

**Comment by adityakpandare** [comment]
I've appended ZoltanInterOp.cpp with code that calls `geomPartMesh()`. Please find it [here](https://github.com/trilinos/Trilinos/files/9912266/ZoltanInterOp.txt). Something like this will reproduce the problem for a small example. Note that the number of parts requested is 1, i.e. Zoltan2 should do partitioning.

**Comment by jhux2** [comment]
@egboman @srajama1

**Comment by egboman** [comment]
Thanks. I'll take a look but I'm no Kokkos expert. I noticed there is no Kokkos::initialize(). Zoltan2 uses Tpetra, which uses KokkosKernels. Question to Tpetra team: Do you assume the user already initialized Kokkos, or do you check for this?

@trilinos/tpetra

**Comment by egboman** [comment]
Zoltan2 requires Tpetra to have been initialized, typically by calling Tpetra::ScopeGuard (https://docs.trilinos.org/dev/packages/tpetra/doc/html/classTpetra_1_1ScopeGuard.html). I don't see this in the ZoltanInterOp.cpp reproducer?

**Comment by adityakpandare** [comment]
@egboman: We did not need calls to any Tpetra functions for Zoltan2 (from Trilinos 12.14.1) to work, which is why it isn't called in the reproducer either. Is this a new requirement since Trilinos's 12.14.1 release?

**Comment by adityakpandare** [comment]
@egboman: I tried including `Tpetra::ScopeGuard tscope(&narg, &arg)` in my code, however, it still triggers the exception "Constructing View and initializing data with uninitialized execution space" as before. So that does not fix it.

**Comment by egboman** [comment]
@adityakpandare Ouch. Thanks for trying. It appears Zoltan2 does not require Tpetra::ScopeGuard (sorry, I was mistaken). In fact, I have been able to build and run a test without it. I suspect something changed in Tpetra or Kokkos. I am not sure how to debug this issue.

**Comment by adityakpandare** [comment]
@egboman: Thanks for looking at this for me. Can this be marked as a bug, considering that the issue can be reproduced? Could we tag the Tpetra team on this perhaps?

**Comment by jhux2** [comment]
@adityakpandare Would you consider upgrading to Trilinos 13.4?  13.0.1 is two years old, and there have been a lot of changes since then.

**Comment by tasmith4** [comment]
@egboman @adityakpandare as another datapoint, on STK, we had to add a call to `Kokkos::initialize()` in the main function for stk_balance once we started using Zoltan2 for geometric partitioning methods, due to Zoltan2's usage of Kokkos for those methods (we did not have to add `Tpetra::ScopeGuard`).  We've generally assumed that this was simply a requirement of using Zoltan2.

**Comment by adityakpandare** [comment]
@jhux2: about upgrading to 13.4: Have there been changes to Zoltan2's "API" between the 13.0.1 and 13.4 versions? 
@tasmith4: I have tried adding `Tpetra::ScopeGuard()`, which did not fix the issue. But I haven't tried `Kokkos::initialize()`. Where would this call go? In the `main()` function?

**Comment by adityakpandare** [comment]
@egboman @tasmith4: adding `Kokkos::initialize()` in main() fixed the issue. It does throw a few warnings at compilation ([warnings.log](https://github.com/trilinos/Trilinos/files/9924111/warnings.log)). If this is our final solution, I have a few questions:
1. Are the warnings a problem for normal code execution?
2. Should `Kokkos::initialize()` be called once per node, per process, or just once on the primary process of the execution?
3. Should I be calling a counterpart to this function, i.e. something like `Kokkos::finalize()` at any point?

**Comment by egboman** [comment]
Great! I think this is the final solution.

1. Not sure. None of the warnings came from Zoltan2.
2. I will look into this. Many users already initialize Kokkos in the application code, and they often want to pass in additional arguments, see: https://github.com/kokkos/kokkos/wiki/Kokkos::initialize 
Perhaps Zoltan2 could check if Kokkos was already initialized or not, and call Kokkos::initialize() only if needed.
4. Call it once per MPI rank.
5. Yes.

**Comment by GrahamBenHarper** [comment]
>     2. Since my code does not explicitly use Kokkos, i.e. it is Zoltan2's dependency, why does Zoltan2 require client code to call `Kokkos:initialize()`, and not call it internally?
> 
>     3. Should `Kokkos::initialize()` be called once per node, per process, or just once on the primary process of the execution?
> 
>     4. Should I be calling a counterpart to this function, i.e. something like `Kokkos::finalize()` at any point?
I can answer a couple of these. Yes, every application should start with a `Kokkos::initialize()` immediately on all MPI ranks **after** initializing MPI, and it should end with a corresponding `Kokkos::finalize()` to free all the resources (see the [Kokkos core wiki](https://kokkos.github.io/kokkos-core-wiki/API/core/Initialize-and-Finalize.html)).

Finally, we don't call `Kokkos::initialize()` in Trilinos packages because there would be no way to feasibly cover all possible cases. For example, if you want some object like a `MultiVector`, we cannot stuff a hidden `Kokkos::initialize()` inside the `MultiVector` if the user hasn't called it already because using `MultiVector`s require Kokkos to be initialized. Now consider that same argument for every conceivable object in Trilinos that depends on Kokkos.

Personally, I have some boilerplate at the start and end of all my applications like 
```
int main(int argc,char * argv[])
{
  // MPI initialization using Teuchos
  Teuchos::GlobalMPISession mpiSession(&argc, &argv, NULL);

  // Call Kokkos::initialize() after MPI so that MPI has the chance to bind
  // processes correctly before Kokkos touches things.
  Kokkos::initialize(argc, argv);
  // Boilerplate  MPI/Kokkos initialization
  Teuchos::RCP<Teuchos::MpiComm<int>> comm = Teuchos::rcp(new typename Teuchos::MpiComm<int>(MPI_COMM_WORLD));
  const int my_rank = comm->getRank();
  const int num_procs = comm->getSize();
  {
  ...
  }
  Kokkos::finalize();

  return 0;
}
```

Hope that helps!
