### ISSUE TITLE
AztecOO: ilut: zero pivot encountered!

### ISSUE THREAD

**Issue by guoluanjing** [trilinos/Trilinos#1119]
Hi there,

I am solving a linear system using AztecOO. I'm using GMRES solver with ilut preconditioner with the defult fill-in and drop parameters. But I have encounted the error message: 
ilut: zero pivot encountered!

I found this old post about the error message:
[https://groups.google.com/forum/#!topic/trilinos/Ps9oKLYdDXA](url)

So I've tried the following:
1. double-checked that RCM ordering is on.
2. I've increased the fill-in to maximum of 1,000,000, roughly the number of elements in my Jacobian matrix, and changed the drop parameter from 0 to 10. The error message still showed but the linear solve converged, but to wrong solution (negative values for chemical concentration).
3. outputted the Jacobian matrix into Matlab, and checked the condition number (10^7, very large) and the singularity (it has an inverse matrix).

Please advise me for what else I could try in order to solve the problem.

Thanks a lot,
Luanjing

**Comment by mhoemmen** [comment]
Just because the matrix itself has an inverse, doesn't mean that you can do ILUT on it.  AztecOO implements ILUT, not ILUTP (ILUT with pivoting).  Try a different preconditioner perhaps.

**Comment by maherou** [comment]
The most common reason for seeing this error is that you have a zero diagonal value somewhere in your matrix.  If you are solving some kind of PDE problem, a zero diagonal value is typically a bug in your code.  If your matrix is not based on PDEs, or has some constraint equations, you can segregate these equations in a block formulation, using ILU only for the equations that have nonzero diagonals, or you could try to put the equations with zero diagonals at the bottom of the matrix.  The diagonal values can become nonzero as the factorization proceeds, not guaranteed, but possible.

Mike

**Comment by guoluanjing** [comment]
@maherou Yes, I checked my jacobian matrix and there are zeros diagonal values. And it is a PDE problem. I will be looking for bugs in the code. Thanks!
