### ISSUE TITLE
MueLu: Broken Nalu builds due to missing MueLu_TpetraOperator_decl.hpp

### ISSUE THREAD

**Issue by spdomin** [trilinos/Trilinos#11192]
Greetings @jhux2 and Muelu team,

I noticed a new build issue in Nalu due to missing MueLu_TpetraOperator_decl.hpp (gcc 8.4)

/gitHubWork/scratch_build/install/gcc8.4.0/Trilinos_nightly_release/include/MueLu_TpetraOperator.hpp:1:10: fatal error: MueLu_TpetraOperator_decl.hpp: No such file or directory
 #include "MueLu_TpetraOperator_decl.hpp"

Good:

NaluCFD/Nalu SHA1: a03c44889e8ffadeec791c17e77a564d2c684017
Trilinos/develop SHA1: b7908f41eb6169df1cf2e92fdea7501dcf9b434c

Bad:

NaluCFD/Nalu SHA1: a03c44889e8ffadeec791c17e77a564d2c684017
Trilinos/develop SHA1: 4cac0ea3e3af6692050850d3eb3c211f3e0371f2

Any help would be greatly appreciated.

Stefan

**Comment by jhux2** [comment]
@spdomin ExaWind team has also reported this.

**Comment by spdomin** [comment]
When I simply hand-copy the set of missing headers to my install, all is well. As such, this looks like a simple installation nuance.

Thanks..

**Comment by spdomin** [comment]
'Looks like the Nalu nightly tests passed this morning, although I read in the https://github.com/trilinos/Trilinos/pull/11199 commentary that other headers were required for Nalu-[wind?] to build? I will report back tomorrow AM.

**Comment by spdomin** [comment]
Looks like this can be closed.
