### ISSUE TITLE
Compiler warnings for Amesos2_Superludist_FunctionMap.hpp

### ISSUE THREAD

**Issue by BarrySmith** [trilinos/Trilinos#112]
/Users/petsc/petsc.clone-4/arch-osx-xsdk-opt/bin/mpicxx -o ex63.o -c -Wall -Wwrite-strings -Wno-strict-aliasing -Wno-unknown-pragmas -g -O3       -I/Users/petsc/petsc.clone-4/include -I/Users/petsc/petsc.clone-4/arch-osx-xsdk-opt/include    `pwd`/ex63.cxx
In file included from /Users/petsc/petsc.clone-4/src/ksp/ksp/examples/tutorials/ex63.cxx:68:
In file included from /Users/petsc/petsc.clone-4/arch-osx-xsdk-opt/include/Amesos2.hpp:45:
In file included from /Users/petsc/petsc.clone-4/arch-osx-xsdk-opt/include/Amesos2_Factory.hpp:102:
In file included from /Users/petsc/petsc.clone-4/arch-osx-xsdk-opt/include/Amesos2_Superludist.hpp:47:
In file included from /Users/petsc/petsc.clone-4/arch-osx-xsdk-opt/include/Amesos2_Superludist_decl.hpp:58:
/Users/petsc/petsc.clone-4/arch-osx-xsdk-opt/include/Amesos2_Superludist_FunctionMap.hpp:285:17: warning: comparison of constant 67 with expression of type 'SLUD::DiagScale_t' is always false [-Wtautological-constant-out-of-range-compare]
      char eq = AMESOS2_SLUD_GET_EQUED(*equed);
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/petsc/petsc.clone-4/arch-osx-xsdk-opt/include/Amesos2_Superludist_FunctionMap.hpp:71:98: note: expanded from macro 'AMESOS2_SLUD_GET_EQUED'
#define AMESOS2_SLUD_GET_EQUED(ds) (((ds)==SLUD::NOEQUIL) ? 'N' : ((ds)==SLUD::ROW) ? 'R' : ((ds)=='C') ? SLUD::COL : SLUD::BOTH)
                                                                                             ~~~~^ ~~~
/Users/petsc/petsc.clone-4/arch-osx-xsdk-opt/include/Amesos2_Superludist_FunctionMap.hpp:306:17: warning: comparison of constant 67 with expression of type 'SLUD::DiagScale_t' is always false [-Wtautological-constant-out-of-range-compare]
      char eq = AMESOS2_SLUD_GET_EQUED(*equed);
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/petsc/petsc.clone-4/arch-osx-xsdk-opt/include/Amesos2_Superludist_FunctionMap.hpp:71:98: note: expanded from macro 'AMESOS2_SLUD_GET_EQUED'
#define AMESOS2_SLUD_GET_EQUED(ds) (((ds)==SLUD::NOEQUIL) ? 'N' : ((ds)==SLUD::ROW) ? 'R' : ((ds)=='C') ? SLUD::COL : SLUD::BOTH)
                                                                                             ~~~~^ ~~~
2 warnings generated.

**Comment by BarrySmith** [comment]
Forgot to add Jason and Satish @sarich@mcs.anl.gov balay@mcs.anl.gov

**Comment by mhoemmen** [comment]
@trilinos/amesos2

**Comment by mhoemmen** [comment]
@BarrySmith Hi Barry!  We appreciate your reports!  I'm not an expert on that particular file so I'm a little scared to change it myself.  I've tagged the Amesos2 developers and am sure they will get back to you right away.  (Many of us are new to Github and we're still learning how to use it for issue tracking.  They probably didn't get a notification about this issue.)

**Comment by srajama1** [comment]
Thanks, Mark. 

Barry, we'll take a look at it. 

It would be nice if you can add @trilinos/amesos2 or @srajama1 in the future.

**Comment by jdbooth** [comment]
@BarrySmith Hi Barry,  
May I ask which version of Superlu_DIST this was from.  We have noticed some changes in the new 4.3 and want to confirm with whatever version you are using.
Thank you!  
@trilinos/amesos2 @srajama1

**Comment by BarrySmith** [comment]
This is 4.3

**Comment by tjhei** [comment]
The following warning is probably related:
```
/ssd/libs-
candi/trilinos-12.6.1-Source/include/Amesos2_Superludist_FunctionMap.hpp:71:125:
warning: enumeral and non-enumeral type in conditional expression
[enabled by default]
((ds)==SLUD::ROW) ? 'R' : ((ds)=='C') ? SLUD::COL : SLUD::BOTH)
```

Let me know if you want a separate issue for it.

**Comment by srajama1** [comment]
Timo, Is this superlu_dist 4.3 as well ?

**Comment by tjhei** [comment]
I only tested SuperLU 4.1.

**Comment by srajama1** [comment]
Got it. Let me take a look.

**Comment by BarrySmith** [comment]
Yes, I get it with 4.3

**Comment by srajama1** [comment]
Thanks for the report. Fixed.
