### ISSUE TITLE
MueLu: MueLu_UnitTestsTpetra_MPI_4 randomly timing out in PR sems-rhel7 builds since 2022-09-27

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#11209]
CC: @trilinos/muelu, @jhux2, @cgcgcg, @csiefer2

## Next Action Status

<status-and-or-first-action>

## Description

As shown in [this query](https://trilinos-cdash.sandia.gov/queryTests.php?project=Trilinos&begin=2022-05-01&end=2022-10-27&filtercount=4&showfilters=1&filtercombine=and&field1=groupname&compare1=61&value1=Pull%20Request&field2=testname&compare2=61&value2=MueLu_UnitTestsTpetra_MPI_4&field3=status&compare3=61&value3=failed&field4=details&compare4=63&value4=timeout) (click "Shown Matching Output" in upper right) the tests:

* `MueLu_UnitTestsTpetra_MPI_4`

in the unique GenConfig builds:

* `rhel7_sems-clang-10.0.0-openmpi-1.10.1-serial_release-debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables`
* `rhel7_sems-gnu-8.3.0-openmpi-1.10.1-openmp_release-debug_static_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables`
* `rhel7_sems-intel-17.0.1-mpich-3.2-serial_release-debug_static_no-kokkos-arch_no-asan_no-complex_fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables`

started failing on testing day 2022-09-27.

The specific set of CDash builds impacted where:

* `PR-10926-test-rhel7_sems-clang-10.0.0-openmpi-1.10.1-serial_release-debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables-1165`
* `PR-10926-test-rhel7_sems-intel-17.0.1-mpich-3.2-serial_release-debug_static_no-kokkos-arch_no-asan_no-complex_fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables-1149`
* `PR-11132-test-rhel7_sems-gnu-8.3.0-openmpi-1.10.1-openmp_release-debug_static_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables-1230`
* `PR-11207-test-rhel7_sems-gnu-8.3.0-openmpi-1.10.1-openmp_release-debug_static_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables-1342`
* `PR-9878-test-rhel7_sems-gnu-8.3.0-openmpi-1.10.1-openmp_release-debug_static_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables-1313`
* `PR-9878-test-rhel7_sems-gnu-8.3.0-openmpi-1.10.1-openmp_release-debug_static_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables-1320`

## Current Status on CDash

Run the [above query](https://trilinos-cdash.sandia.gov/queryTests.php?project=Trilinos&begin=2022-05-01&end=2022-10-27&filtercount=4&showfilters=1&filtercombine=and&field1=groupname&compare1=61&value1=Pull%20Request&field2=testname&compare2=61&value2=MueLu_UnitTestsTpetra_MPI_4&field3=status&compare3=61&value3=failed&field4=details&compare4=63&value4=timeout) adjusting the "Begin" and "End" dates to match today any other date range or just click "CURRENT" in the top bar to see results for the current testing day.

## Steps to Reproduce

See:

* https://github.com/trilinos/Trilinos/wiki/Reproducing-PR-Testing-Errors

If you can't figure out what commands to run to reproduce the problem given this documentation, then please post a comment here and we will give you the exact minimal commands.

**Comment by bartlettroscoe** [comment]
FYI: As shown in [this query](https://trilinos-cdash.sandia.gov/queryTests.php?project=Trilinos&begin=2022-09-18&end=2022-10-27&filtercount=4&showfilters=1&filtercombine=and&field1=groupname&compare1=61&value1=Pull%20Request&field2=testname&compare2=61&value2=MueLu_UnitTestsTpetra_MPI_4&field3=block&field3count=3&field3field1=buildname&field3compare1=63&field3value1=rhel7_sems-clang-10.0.0-openmpi-1.10.1-serial_release-debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables&field3field2=buildname&field3compare2=63&field3value2=hel7_sems-gnu-8.3.0-openmpi-1.10.1-openmp_release-debug_static_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables&field3field3=buildname&field3compare3=63&field3value3=rhel7_sems-intel-17.0.1-mpich-3.2-serial_release-debug_static_no-kokkos-arch_no-asan_no-complex_fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables&field4=block&field4count=2&field4field1=details&field4compare1=61&field4value1=Completed&field4field2=details&field4compare2=61&field4value2=Completed%20(Timeout)), this test has run 408 times between 2022-09-1 and 2022-10-27 in these three builds where it either passed in under 28 seconds or timed out at 10 minutes.

It seems clear that this test is randomly hanging.

**Comment by bartlettroscoe** [comment]
FYI: This issue was created with the help of the tool in #11200.

**Comment by cgcgcg** [comment]
I can reproduce this on Geminga. Sometimes this test just hangs, and sometimes it fails in the construction of an Ifpack2 block relaxtion smoother and then hangs.
```
  /home/caglusa/Trilinos/packages/ifpack2/src/Ifpack2_Relaxation_def.hpp:982:
  
  Throw number = 1
  
  Throw test that evaluated to true: info > 0
  
  GETF2 or GETRI failed on = 1 diagonal blocks.
```
