### ISSUE TITLE
Build failure because of Thyra_Ifpack2PreconditionerFactory.hpp missing

### ISSUE THREAD

**Issue by srbdev** [trilinos/Trilinos#11239]
## Bug Report
@trilinos/panzer 
@trilinos/muelu 
@trilinos/stratimikos 
@trilinos/nox 
@trilinos/teko 
@trilinos/trilinoscouplings 
@trilinos/shylu  
@trilinos/thyra 

### Description
This affecting the following fork https://github.com/e10harvey/Trilinos and branch `sprint17_cpp17`.

I am working on a new nightly build `rhel7_sems-cuda-11.4.2-sems-gnu-10.1.0-sems-openmpi-4.0.5_release_static_Volta70_no-asan_complex_no-fpic_mpi_pt_no-rdc_no-uvm_deprecated-on_all` that enables of all packages, and the build step fails with the following error message:
```bash
/packages/nox/test/tpetra/tTpetra_1DFEM_ME_UnitTests.cpp:68:10: fatal error: Thyra_Ifpack2PreconditionerFactory.hpp: No such file or directory
   68 | #include "Thyra_Ifpack2PreconditionerFactory.hpp"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```
I tried to look for `Thyra_Ifpack2PreconditionerFactory.hpp` in the source code and build directory and cannot find it.  

It looks like it gets included one or more times for the following packages:
```bash
./packages/panzer/adapters-stk/src/Panzer_STK_SetupLOWSFactory.cpp:#include <Thyra_Ifpack2PreconditionerFactory.hpp>
./packages/muelu/research/q2q1/Q2Q1.cpp:#include <Thyra_Ifpack2PreconditionerFactory.hpp>
./packages/muelu/src/Smoothers/MueLu_StratimikosSmoother_def.hpp:#include <Thyra_Ifpack2PreconditionerFactory.hpp>
./packages/muelu/test/maxwell/Maxwell3D.cpp:#include <Thyra_Ifpack2PreconditionerFactory.hpp>
./packages/muelu/example/basic/Teko.cpp:#include "Thyra_Ifpack2PreconditionerFactory.hpp"
./packages/muelu/example/basic/Stratimikos.cpp:#include <Thyra_Ifpack2PreconditionerFactory.hpp>
./packages/muelu/adapters/stratimikos/Xpetra_ThyraLinearOp.hpp:# include <Thyra_Ifpack2PreconditionerFactory.hpp>
./packages/stratimikos/test/galeri_xpetra_driver.cpp:# include <Thyra_Ifpack2PreconditionerFactory.hpp>
./packages/stratimikos/test/test_thyra_tpetra_ifpack2_issue_535.cpp:#include "Thyra_Ifpack2PreconditionerFactory.hpp"
./packages/nox/test/tpetra/tTpetra_HouseholderBorderedSolve_WithUVInPrec.cpp:#include "Thyra_Ifpack2PreconditionerFactory.hpp"
./packages/nox/test/tpetra/tTpetra_HouseholderBorderedSolve_Continuation.cpp:#include "Thyra_Ifpack2PreconditionerFactory.hpp"
./packages/nox/test/tpetra/tTpetra_HouseholderBorderedSolve.cpp:#include "Thyra_Ifpack2PreconditionerFactory.hpp"
./packages/nox/test/tpetra/Tpetra_1DFEM.cpp:#include "Thyra_Ifpack2PreconditionerFactory.hpp"
./packages/teko/src/Teko_InverseLibrary.cpp:#include "Thyra_Ifpack2PreconditionerFactory.hpp"
./packages/teko/examples/BuildPreconditioner/example-driver-belos.cpp:#include "Thyra_Ifpack2PreconditionerFactory.hpp"
./packages/trilinoscouplings/examples/scaling/example_Maxwell_Tpetra.cpp:#include <Thyra_Ifpack2PreconditionerFactory.hpp>
./packages/shylu/shylu_dd/frosch/src/Tools/FROSch_SubdomainSolver_decl.hpp:#include "Thyra_Ifpack2PreconditionerFactory.hpp"
./packages/piro/src/Piro_TempusSolverForwardOnly_Def.hpp:#include "Thyra_Ifpack2PreconditionerFactory.hpp"
./packages/piro/src/Piro_InvertMassMatrixDecorator_Def.hpp:#include "Thyra_Ifpack2PreconditionerFactory.hpp"
./packages/piro/src/Piro_TempusSolver_Def.hpp:#include "Thyra_Ifpack2PreconditionerFactory.hpp"
./packages/piro/src/Piro_RythmosSolver_Def.hpp:#include "Thyra_Ifpack2PreconditionerFactory.hpp"
./packages/piro/test/Main_AnalysisDriver_Tpetra.cpp:#include "Thyra_Ifpack2PreconditionerFactory.hpp"
./packages/piro/test/Main_ThyraSolver_Tpetra.cpp:#include "Thyra_Ifpack2PreconditionerFactory.hpp"
```

Am I missing something, or does it need to get cleaned up? Thank you!

**Comment by bartlettroscoe** [comment]
Can do a [make dashboard](https://docs.trilinos.org/files/TrilinosBuildReference.html#dashboard-submissions) so this shows up on CDash?  Also, where is the Trilinos branch for these changes?  Anyone would need that in order to have any shot at reproducing this.

**Comment by srbdev** [comment]
> Can do a [make dashboard](https://docs.trilinos.org/files/TrilinosBuildReference.html#dashboard-submissions) so this shows up on CDash? Also, where is the Trilinos branch for these changes? Anyone would need that in order to have any shot at reproducing this.

I updated the issue description with a link to the fork and the branch name. Running the `make dashboard` command now.

**Comment by cgcgcg** [comment]
And if this is a build that is supposed to be used by AT or MM, you probably also want to enable MueLu.

**Comment by cgcgcg** [comment]
@rppawlo Looks like some of the Nox-Tpetra tests need an additional CMake guard for the optional dependence of Nox on Ifpack2.

**Comment by rppawlo** [comment]
I see the issue. Will get a fix up by tomorrow.

**Comment by bartlettroscoe** [comment]
We should consider changing one of the faster Trilinos PR builds (or one of the master-merge builds) to do a [package-by-package build and test](https://tribitspub.github.io/TriBITS/users_guide/index.html#all-at-once-versus-package-by-package-mode-tribits-ctest-driver) of Trilinos with optional packages turned off.  That would help to catch optional dependency issues like this.

**Comment by rppawlo** [comment]
@srbdev - I'm curious - why is ifpack2 being disabled? This is a critical package that should never be manually disabled in PR testing. It looks like it is being explicitly disabled in your configure script. Is this temporary while the ifpack team resolves errors? The fix is now up for PR testing in #11242 .

**Comment by rppawlo** [comment]
@srbdev - fixes for nox have been merged into develop

**Comment by srbdev** [comment]
Thank you @rppawlo, and to answer your question: I don't know and I've taken the configuration from the old CUDA 10 build for this new build so I assume it has been like that for a while. Thanks for brining that to my attention though and I'll test again shortly.

**Comment by bartlettroscoe** [comment]
@srbdev, in general be very suspicious of any explicit enables or disables of the form:

```
Trilinos_ENABLE_<Package>=[ON|OFF]
```

There should only be a very small number of package disables common to all of the builds.  (How things like #11205 is a mystery and need to be avoided in the future.)

**Comment by srbdev** [comment]
Good to know! I'm actually working on a parallel effort to this nightly build for the CUDA 11 build to re-enable the explicitly disabled packages - hence the reason for my recent GitHub issues 😄

**Comment by srbdev** [comment]
@trilinos/rol 
@trilinos/shylu 
@trilinos/trilinoscouplings 

Here's a [CDash link](https://trilinos-cdash.sandia.gov/index.php?project=Trilinos&display=project&filtercount=3&showfilters=1&filtercombine=and&field1=site&compare1=61&value1=ascicgpu050&field2=buildname&compare2=61&value2=PR-Trilinos_nightly_cuda-11.4.2-uvm-off-test-rhel7_sems-cuda-11.4.2-sems-gnu-10.1.0-sems-openmpi-4.0.5_release_static_Volta70_no-asan_complex_no-fpic_mpi_pt_no-rdc_no-uvm_deprecated-on_all-259&field3=buildstamp&compare3=61&value3=20221114-0835-Nightly) for the build and you can see the errors for the tagged projects on this comment.

**Comment by bartlettroscoe** [comment]
@rppawlo, @srbdev, @cgcgcg, from looking at the [above](https://github.com/trilinos/Trilinos/issues/11239#issuecomment-1314747421) build on [CDash](https://trilinos-cdash.sandia.gov/build/597737/configure), you can see the Ifpack2 is not the only significant disable as that build also shows the disables

```
Explicitly disabled top-level packages on input (by user or by default):  Ifpack2 ... STK MueLu Stokhos Piro ... 8
```

A build that disabled Ifpack2, STK, Muelu, Stokhos, and Piro is not a sufficient build to run as a PR build.

**Comment by srbdev** [comment]
@bartlettroscoe here's the [CDash link](https://trilinos-cdash.sandia.gov/index.php?project=Trilinos&parentid=606218&filtercount=1&showfilters=1&field1=buildstamp&compare1=61&value1=20221117-0836-Nightly&filtercombine=and) for the build with all the explicit disabled packages and tests removed. You can see the pull request to Evan's fork [here](https://github.com/e10harvey/Trilinos/pull/21).

**Comment by jhux2** [comment]
TrilinosCouplings build errors have been resolved.

**Comment by srbdev** [comment]
Closing this issue since its specific error has been resolved, but the discussion it generated has been captured in these new issues:
- https://github.com/trilinos/Trilinos/issues/11297
- https://github.com/trilinos/Trilinos/issues/11298
- https://github.com/trilinos/Trilinos/issues/11299
- https://github.com/trilinos/Trilinos/issues/11300
- https://github.com/trilinos/Trilinos/issues/11167#issuecomment-1322468842.
