### ISSUE TITLE
Framework: AT Neither Testing nor Commenting on PRs

### ISSUE THREAD

**Issue by GrahamBenHarper** [trilinos/Trilinos#11234]
## Bug Report
@trilinos/framework

### Description
The autotester has been unresponsive for roughly the past three days. There was a bad gateway error in #11226 (see [this comment](https://github.com/trilinos/Trilinos/pull/11226#issuecomment-1302870170)) which I suspect was the last time it responded to anything.

I will link a framework ticket when it is created.

**Comment by cgcgcg** [comment]
Internal ticket: https://sems-atlassian-son.sandia.gov/jira/servicedesk/customer/portal/7/TRILINOSHD-225

**Comment by GrahamBenHarper** [comment]
As shown in [this cdash query](https://trilinos-cdash.sandia.gov/viewBuildGroup.php?project=Trilinos&buildgroup=Pull%20Request&date=2022-11-04) and also from viewing the corresponding BuildGroup timeline, there are no PR results on the dashboard from Nov 4 forward.

**Comment by GrahamBenHarper** [comment]
Looks like it's back up and running since last night. Closing as fixed
