### ISSUE TITLE
KokkosKernels: KokkosKernels_batched_dla tests timing out in ATDM CUDA builds starting before 2022-10-01

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#11235]
CC: @trilinos/kokkos-kernels

## Next Action Status

<status-and-or-first-action>

## Description

As shown in [this query](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&begin=2022-10-01&end=2022-11-06&filtercount=7&showfilters=1&filtercombine=and&field1=groupname&compare1=62&value1=Experimental&field2=buildname&compare2=65&value2=Trilinos-atdm-&field3=testname&compare3=65&value3=Kokkos&field4=site&compare4=62&value4=stria&field5=status&compare5=61&value5=failed&field6=details&compare6=63&value6=Timeout&field7=buildname&compare7=62&value7=Trilinos-atdm-ats1-hsw_intel-19.0.4_mpich-7.7.15_openmp_static_opt) (click "Shown Matching Output" in upper right) the tests:

* `KokkosKernels_batched_dla_cuda_MPI_1`
* `KokkosKernels_batched_dla_serial_MPI_1`

in the builds:

* `Trilinos-atdm-ats2-cuda-10.1.243-gnu-7.3.1-spmpi-rolling_static_dbg`
* `Trilinos-atdm-ats2-cuda-10.1.243-gnu-7.3.1-spmpi-rolling_static_dbg_cuda-aware-mpi`
* `Trilinos-atdm-cee-rhel7_cuda-10.1.243_gnu-7.2.0_openmpi-4.0.3_shared_dbg`
* `Trilinos-atdm-cee-rhel7_cuda-10.1.243_gnu-7.2.0_openmpi-4.0.3_shared_opt`
* `Trilinos-atdm-sems-rhel7-cuda-10.1-Volta70-complex-shared-release-debug`

are timing out either every day or fairly regularly starting before 2022-10-01.

These are timing out every day in most of the debug builds but also timeout fairly regularly in the optimized (opt) build listed above.

NOTE: I filtered out timing out tests on 'stria' and rarely timing out tests when constructing the CDash query given above.

## Current Status on CDash

Run the [above query](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&begin=2022-10-01&end=2022-11-06&filtercount=7&showfilters=1&filtercombine=and&field1=groupname&compare1=62&value1=Experimental&field2=buildname&compare2=65&value2=Trilinos-atdm-&field3=testname&compare3=65&value3=Kokkos&field4=site&compare4=62&value4=stria&field5=status&compare5=61&value5=failed&field6=details&compare6=63&value6=Timeout&field7=buildname&compare7=62&value7=Trilinos-atdm-ats1-hsw_intel-19.0.4_mpich-7.7.15_openmp_static_opt) adjusting the "Begin" and "End" dates to match today any other date range or just click "CURRENT" in the top bar to see results for the current testing day.

## Steps to Reproduce

One should be able to reproduce this failure as described in:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md

and the system-specific instructions at:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#specific-instructions-for-each-system

Just log into any of the associated machines and copy and paste the full CDash build name `<build-name>` listed above and run commands like:

```
$ cd <some_build_dir>/

$ source $TRILINOS_DIR/cmake/std/atdm/load-env.sh <build-name>

$ cmake \
 -GNinja \
 -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
 -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_<package-name>=ON \
 $TRILINOS_DIR

$ make NP=16

$ <command-to-run-on-compute-node> ctest -j4
```

where `<package-name>` is any package that you want to enable to reproduce build and/or test results.

Again, for exact system-specific details on what commands to run to build and run tests, see:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#specific-instructions-for-each-system

If you can't figure out what commands to run to reproduce the problem given this documentation, then please post a comment here and we will give you the exact minimal commands.

**Comment by ndellingwood** [comment]
@bartlettroscoe are these Cuda builds running with parallelism (i.e. ctest -j N, N>1)? If so, can you set the `RUN_SERIAL` option for the `KokkosKernels_batched_dla` in those builds for now? I opened an issue https://github.com/kokkos/kokkos-kernels/issues/1595 to better address the long test time for the next release

**Comment by bartlettroscoe** [comment]
> If so, can you set the RUN_SERIAL option for the KokkosKernels_batched_dla in those builds for now?

@ndellingwood, sure, anyone can do that as documented:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#disable-a-test-for-builds-on-all-platforms

But don't disable the tests, just set:

```
atdm_set_eanble(KokkosKernels_batched_dla_cuda_MPI_1_SET_RUN_SERIAL ON)
atdm_set_eanble(KokkosKernels_batched_dla_serial_MPI_1_SET_RUN_SERIAL ON)
```

In fact, one would put these right after:

https://github.com/trilinos/Trilinos/blob/3558b72a1581d433a1f8bdbf996abb9719b37bae/cmake/std/atdm/ATDMDisables.cmake#L323-L333
