### ISSUE TITLE
tpetra: Can't take host view while device views are active

### ISSUE THREAD

**Issue by cwpearson** [trilinos/Trilinos#11250]
@trilinos/tpetra 

When executing `ctest -R MatrixMarket_Operator -V` with `TPETRA_VERBOSE=1`, get output like

```
Test: Operator Matrix Market I/O, w/ Map with index base 0
170:   Creating the row Map
170:   Creating original matrix
170:  
170:  p=0: *** Caught standard std::exception of type 'std::runtime_error' :
170:  
170:   Tpetra::Details::WrappedDualView (name = Tpetra::CrsGraph column indices; host use_count = 2; device use_count = 3): Cannot access data on host while a device view is alive
170:  [FAILED]  (1.09 sec) OperatorOutput_double_int_longlong_Kokkos_Compat_KokkosCudaWrapperNode_IndexBase0_UnitTest
```

Accessing the host views here is invalid because the device view `indices_new` lives on.
https://github.com/trilinos/Trilinos/blob/14a80ebfde8f69dbbd55b24a42bf6d91cf9f2cb4/packages/tpetra/core/src/Tpetra_Details_crsUtils.hpp#L379-L380

I guess the autotester does not have a GPU build with `TPETRA_VERBOSE=1` enabled.

**Comment by jhux2** [comment]
> I guess the autotester does not have a GPU build with `TPETRA_VERBOSE=1` enabled.

almost certainly not

**Comment by cwpearson** [comment]
To reproduce:
* `make -j`nproc` TpetraCore_MatrixMarket_Operator_Test`
* `export TPETRA_VERBOSE=1`
* `cd Trilinos`
* `ctest -R MatrixMarket_Operator -V`

**Comment by jhux2** [comment]
> > I guess the autotester does not have a GPU build with `TPETRA_VERBOSE=1` enabled.
> 
> almost certainly not

That being said, we could certainly set up a _nightly_ build that enables `TPETRA_VERBOSE=1`.

**Comment by cwpearson** [comment]
fixed in https://github.com/trilinos/Trilinos/pull/11251
