### ISSUE TITLE
Trilinos with CUDA: Where to find build instructions for Trilinos with CUDA?

### ISSUE THREAD

**Issue by mayrmt** [trilinos/Trilinos#11255]
## Documentation
@trilinos/framework 
@trilinos/kokkos @trilinos/kokkos-kernels 

### Current status

There are no public instructions how to build Trilinos with CUDA. Since PR testing results cannot be viewed from outside SNL, it's crucial to be able to reproduce CUDA builds locally -- for contributing code, but of course also for running applications with a Trilinos+CUDA backend.

Currently, [this site on the Trilinos website](https://trilinos.github.io/building_with_CUDA_support.html) provides some totally outdated information.

There seem to be some issues (e.g. https://github.com/trilinos/Trilinos/issues/10339) with code snippets and scattered info on problems with CUDA builds, though I'm not aware of a clear set of ready-to-use instructions.

### Question

Where can I find instructions to build Trilinos with MPI+CUDA support? Where are they documented? Are they documented at all?

**Comment by ccober6** [comment]
This is related to #10798.

**Comment by mayrmt** [comment]
@ccober6 I didn't find the other issue. 

Closing in favor of #10798.
