### ISSUE TITLE
Zoltan: Zoltan_canarySelfMessages_MPI_2 segfaults with cuda/11.4.2 sometimes

### ISSUE THREAD

**Issue by e10harvey** [trilinos/Trilinos#11259]
## Bug Report
@trilinos/zoltan

### Description
Sometimes Zoltan_canarySelfMessages_MPI_2 makes master merge sad.

### Steps to Reproduce
Please see https://github.com/trilinos/Trilinos/pull/11204#issuecomment-1294193721.

CC: @trilinos/framework

**Comment by egboman** [comment]
Sorry, no idea why this test has "random" failures on certain systems.
