### ISSUE TITLE
where can i find the Shylue xamples

### ISSUE THREAD

**Issue by ztdepztdep** [trilinos/Trilinos#11261]
I need to use the Shylu to solve the matrix system generated from the spectral element method. Could you please give me some advices about the where can i find the examples.

**Comment by cgcgcg** [comment]
@trilinos/shylu

**Comment by iyamazaki** [comment]
Hi, @ztdepztdep. There are a few solvers in ShyLU, can you tell us which solver you are interested in? I believe each solver has an `example` director that contains some examples..

**Comment by ztdepztdep** [comment]
> Hi, @ztdepztdep. There are a few solvers in ShyLU, can you tell us which solver you are interested in? I believe each solver has an `example` director that contains some examples..
The attachment is my matrix obtained from the Spectral element method. Could you please give me some suggestions?
![Adiffusion mtx](https://user-images.githubusercontent.com/8356693/201445910-c525e94d-fd4b-4ee8-bb43-fd2b08a6f3e0.jpg)
