### ISSUE TITLE
[Question] Epetra symmetric matrix fill.

### ISSUE THREAD

**Issue by kyungjoo-kim** [trilinos/Trilinos#1126]
could you help me figure out what the most efficient way to fill crs matrix with symmetry ? 

The filled matrix is already upper triangular and Trillions object does not support a symmetry flag as a storage (in my opinion, if wrong, please correct me). How can fill the other part easily ?

**Comment by mhoemmen** [comment]
You have two options:
  1. Use Epetra_FECrsMatrix and insert A(j,i) whenever you see A(i,j), then call GlobalAssemble() or whatever Epetra calls it to communicate all the entries where they belong.
  2. Add the matrix to its transpose, then subtract off the diagonal.  I'm pretty sure that Epetra has add and transpose routines.  @csiefer2 would you happen to know?

**Comment by maherou** [comment]
Kyungjoo,

Give some more details about what you are doing.  Do you need just the matvec operation?  Or do you need for other purposes?

**Comment by csiefer2** [comment]
EpetraExt does have matrix transpose routines, if you decide to go that route.

**Comment by kyungjoo-kim** [comment]
@maherou  I am trying to use Trilinos in LAMMPS and I have experience for that. The problem is to solve charge equilibrium (I consider that this is not quite difficult problem) with CG. The code originally use in-house CG routine with diagonal precondition (they said it is not scale well). I use Epetra + Belos + ML. 

The problem is that LAMMPS uses half-neighbor list, which results in matrix filling on upper triangular. 
- I consider to over-ride Epetra Operator to do symmetric matrix apply and at the end, the preconditioner requires a matrix @csiefer2 please correct me if I am wrong. 
- I use Epetra Transposer and merge them (merging uses row-by-row addition).

**Comment by mhoemmen** [comment]
@kyungjoo-kim ML definitely requires a matrix.  There's no way to implement a symmetrizing RowMatrix without actually storing the (j,i)s for your (i,j)s.  Thus, RowMatrixTransposer is the best option for now.

**Comment by csiefer2** [comment]
I concur w/ @mhoemmen

**Comment by maherou** [comment]
You would not need to physically merge the two matrix objects.  You could satisfy the RowMatrix API by inserting the lower and upper triangle entries from the separate objects.
