### ISSUE TITLE
error: has no member named ‘real’; did you mean ‘val’?    v = T(v.real(), -v.imag());

### ISSUE THREAD

**Issue by ztdepztdep** [trilinos/Trilinos#11267]
Trilinos-trilinos-release-13-4-1/packages/shylu/shylu_node/hts/src/shylu_hts_impl_def.hpp:1214:11: error: ‘class Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::Serial> >’ has no member named ‘real’; did you mean ‘val’?
   v = T(v.real(), -v.imag());
         ~~^~~~
         val
/home/ztdep/Downloads/Trilinos-trilinos-release-13-4-1/packages/shylu/shylu_node/hts/src/shylu_hts_impl_def.hpp:1214:22: error: ‘class Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::Serial> >’ has no member named ‘imag’
   v = T(v.real(), -v.imag());
                    ~~^~~~

**Comment by cgcgcg** [comment]
@trilinos/shylu
