### ISSUE TITLE
    "Kokkos_ENABLE_THREADS" ...... Unknown arguments specified

### ISSUE THREAD

**Issue by ztdepztdep** [trilinos/Trilinos#11269]
When i compile my code with Trilinos13.4.1, i met the following error. 
Could you please help me out.    
CMake Error at /home/ztdep/lib/Trilinos-trilinos-release-13-4-1/lib/cmake/Kokkos/KokkosConfig.cmake:172 (IF):
  if given arguments:
    "Kokkos_ENABLE_THREADS" "AND" "NOT" "DEPRECATED_CODE_3" "IN_LIST" "Kokkos_OPTIONS"

  Unknown arguments specified

**Comment by cgcgcg** [comment]
Please post your CMake invocation and the corresponding output.

**Comment by GrahamBenHarper** [comment]
Hi @ztdepztdep. If your code links against Trilinos, you may need to set `CMAKE_POLICY(SET CMP0057 NEW)` in your project's CMake. See related issue #10467.

**Comment by cgcgcg** [comment]
@ztdepztdep Did that fix the issue?

**Comment by ztdepztdep** [comment]
great thank you very much



| |
***@***.***
|
|
***@***.***
|




---- Replied Message ----
| From | Christian ***@***.***> |
| Date | 11/18/2022 01:13 |
| To | ***@***.***> |
| Cc | ***@***.******@***.***> |
| Subject | Re: [trilinos/Trilinos] "Kokkos_ENABLE_THREADS" ...... Unknown arguments specified (Issue #11269) |

@ztdepztdep Did that fix the issue?
