### ISSUE TITLE
Nalu nightly diffs due to recent ifpack2 change

### ISSUE THREAD

**Issue by spdomin** [trilinos/Trilinos#11262]
## Bug Report
@trilinos/ifpack2

Greetings,

Diffs showed up last night in our gcc 10.2.0, openMPI 4.0.5. Most diffs are small, i.e., O(1e-6) – aside from our wildly nonlinear physics integrated tests that are much higher.

I wanted to know if these changes captured a recent ifpack2 change (see below bisect) are intended and if we all agree that the diffs should be accepted. It looks like they are, and that order of operation-like diffs would appear, however, I wanted to make sure @GrahamBenHarper? 

Bisect details:

Good (11/10/2022):
100% tests passed, 0 tests failed out of 81
NaluCFD/Nalu SHA1: 9a5d3a61a8ff3e9bd34f51cb670b51ea2da5a304
Trilinos/develop SHA1: 31509b0630525264c8ee689d88ac6e834acf0a1d

Bad (11/11/2022):  
33% tests passed, 54 tests failed out of 81
NaluCFD/Nalu SHA1: 9a5d3a61a8ff3e9bd34f51cb670b51ea2da5a304
Trilinos/develop SHA1: d62e83a33d3c78c37dc4482e65ea23f8362f4270

For the bisect, I had to toggle back and forth between Nalu versions that included the new vector type signature for output_types, e.g.:

-    stk::io::set_field_output_type(*someVelocity, stk::io::FieldOutputType::VECTOR_3D);
+    stk::io::set_field_output_type(*someVelocity, "Vector_3D");

This change does not affect pass/fails since we diff on integrated nonlinear residuals.

Findings:

d62e83a33d3c78c37dc4482e65ea23f8362f4270 is the first bad commit
commit d62e83a33d3c78c37dc4482e65ea23f8362f4270
Author: Graham Harper <GrahamBenHarper@users.noreply.github.com>
Date:   Thu Nov 10 19:35:38 2022 -0700

    Ifpack2: Make the Chebyshev power method consistent with itself (#11231)
    
    * Ifpack2: Update PowerMethod to compute absolute eigenvalue or eigenvalue
    
    The Dinv*A matrix for this problem has two dominant eigenvalues, 12.5839 and -10.6639. The original implementation used a random guess and computed the eigenvalues in iterations using the norm, but returned the final answer using xAx. This caused spurious issues where the history would appear to converge, but the final answer would be horribly incorrect. Now the power method computes the spectral radius by default, and it computes xAx iteratively if compute spectral radius is set to false

 packages/ifpack2/doc/UsersGuide/options.tex        |   5 +
 .../ifpack2/src/Ifpack2_Details_Chebyshev_decl.hpp |   6 +
 .../ifpack2/src/Ifpack2_Details_Chebyshev_def.hpp  |  11 +-
 packages/ifpack2/src/Ifpack2_PowerMethod.hpp       | 223 ++++++++++++++-------
 packages/ifpack2/test/belos/CMakeLists.txt         |  12 ++
 .../ifpack2/test/belos/test_Cheby_calore1_mm.xml   |   1 +
 .../test_Cheby_calore1_nospectralradius_mm.xml     |  18 ++
 7 files changed, 204 insertions(+), 72 deletions(-)

**Comment by GrahamBenHarper** [comment]
Hi @spdom, previously it was possible for Chebyshev to obtain a negative spectral radius. This should in general produce more accurate spectral radius estimates and therefore Chebyshev should perform slightly better than it did previously.

**Comment by jhux2** [comment]
@spdomin I agree with @GrahamBenHarper.  Please feel free to rebase Nalu.

**Comment by spdomin** [comment]
@GrahamBenHarper and @jhux2 - thank you for the reply and suggested path forward. I will move on rebasing Nalu.

**Comment by GrahamBenHarper** [comment]
Linking the PR for posterity #11231

**Comment by spdomin** [comment]
100% tests passed, 0 tests failed out of 81
NaluCFD/Nalu SHA1: 19db62c97fffd940bded1642981e3b367b8eeb0e
Trilinos/develop SHA1: 94306b62445d9d1d6f36ee6aa55d809f6506f349

**Comment by alanw0** [comment]
@tasmith4 for reference, this issue may or may not be the same for some of the nalu-wind diffs.
