### ISSUE TITLE
Amesos2: Expose Nnz Counts for KLU + Basker

### ISSUE THREAD

**Issue by csiefer2** [trilinos/Trilinos#1127]
Amesos2 produces counts of nonzeros accessible from the Status' getNnzLU() routine, but only for Pardiso, SuperLU and SuperLUmt.

Issue: Expose that info for KLU2 and Basker.

**Comment by ndellingwood** [comment]
@csiefer2 Starting to look at this now...

**Comment by ndellingwood** [comment]
@csiefer2 These changes are in develop now, closing the issue.
