### ISSUE TITLE
Tempus_IMEX_RK_Partitioned_Staggered_FSA_Partitioned_IMEX_RK_1st_Order_MPI_1 randomly timing out in Trilinos PR builds

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#11296]
CC: @trilinos/tempus, @ccober6, @trilinos/framework 

## Next Action Status

<status-and-or-first-action>

## Description

As shown in [this query](https://trilinos-cdash.sandia.gov/queryTests.php?project=Trilinos&begin=2022-09-01&end=2022-11-21&filtercount=3&showfilters=1&filtercombine=and&field1=testname&compare1=61&value1=Tempus_IMEX_RK_Partitioned_Staggered_FSA_Partitioned_IMEX_RK_1st_Order_MPI_1&field2=status&compare2=61&value2=failed&field3=details&compare3=63&value3=timeout) (click "Shown Matching Output" in upper right) the tests:

* `Tempus_IMEX_RK_Partitioned_Staggered_FSA_Partitioned_IMEX_RK_1st_Order_MPI_1`

in the unique GenConfig builds:

* `rhel7_sems-gnu-7.2.0-openmpi-1.10.1-serial_debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables`
* `rhel7_sems-gnu-8.3.0-openmpi-1.10.1-serial_debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_all`

started failing on testing day 2022-10-28.

The specific set of CDash builds impacted where:

* `PR-11226-test-rhel7_sems-gnu-7.2.0-openmpi-1.10.1-serial_debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables-1442`
* `PR-Trilinos_nightly_gcc_8.3.0-debug-test-rhel7_sems-gnu-8.3.0-openmpi-1.10.1-serial_debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_all-154`
* `PR-Trilinos_nightly_gcc_8.3.0-debug-test-rhel7_sems-gnu-8.3.0-openmpi-1.10.1-serial_debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_all-294`

Looking at [this test for these two builds from 2022-09-01](https://trilinos-cdash.sandia.gov/queryTests.php?project=Trilinos&begin=2022-09-01&end=2022-11-21&filtercount=2&showfilters=1&filtercombine=and&field1=testname&compare1=61&value1=Tempus_IMEX_RK_Partitioned_Staggered_FSA_Partitioned_IMEX_RK_1st_Order_MPI_1&field2=block&field2count=2&field2field1=buildname&field2compare1=63&field2value1=rhel7_sems-gnu-7.2.0-openmpi-1.10.1-serial_debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables&field2field2=buildname&field2compare2=63&field2value2=rhel7_sems-gnu-8.3.0-openmpi-1.10.1-serial_debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_all), one can see this test takes upwards of 8m 48s when it passes.  But it only timeout 3 times out of 258 times.  So that is about a 1% timeout rate.  (But you add that to all of the other random failures in Trilinos and they add up.)

## Current Status on CDash

Run the [above query](https://trilinos-cdash.sandia.gov/queryTests.php?project=Trilinos&begin=2022-09-01&end=2022-11-21&filtercount=3&showfilters=1&filtercombine=and&field1=testname&compare1=61&value1=Tempus_IMEX_RK_Partitioned_Staggered_FSA_Partitioned_IMEX_RK_1st_Order_MPI_1&field2=status&compare2=61&value2=failed&field3=details&compare3=63&value3=timeout) adjusting the "Begin" and "End" dates to match today any other date range or just click "CURRENT" in the top bar to see results for the current testing day.

## Steps to Reproduce

See:

* https://github.com/trilinos/Trilinos/wiki/Reproducing-PR-Testing-Errors

If you can't figure out what commands to run to reproduce the problem given this documentation, then please post a comment here and we will give you the exact minimal commands.

**Comment by sebrowne** [comment]
Other than my standard aversion to disabling tests, I don't really have any issue, as long as @trilinos/tempus is fine with it.

**Comment by ccober6** [comment]
@etphipp Are you  aware of this, and do you have any ideas on it?

**Comment by etphipp** [comment]
I

> @etphipp Are you aware of this, and do you have any ideas on it?

First I've seen it.  I've seen Tempus tests time out in debug builds (which the above referenced build are), especially the various IMEX tests, when running CTest with a high -j number.  I think it has to do with which tests are getting run at the same time (which is random).  I think there is a flag to tell Tribits to not run it in parallel with other tests which may help.

**Comment by bartlettroscoe** [comment]
> I think there is a flag to tell Tribits to not run it in parallel with other tests which may help.

https://docs.trilinos.org/files/TrilinosBuildReference.html#set-specific-tests-to-run-in-serial

But why are we running these expensive tests in full debug PR builds (i.e. `CMAKE_BUILD_TYPE=DEBUG`)  when the are already running fast in the other optimized PR builds?  These expensive tests should be categorized as [`NIGHTLY`](https://tribitspub.github.io/TriBITS/users_guide/index.html#test-test-category-nightly) or [`CONTINUOUS`](https://tribitspub.github.io/TriBITS/users_guide/index.html#test-test-category-continuous) and the full debug builds should be configured with [`-D Trilinos_TEST_CATEGORIES=BASIC`](https://docs.trilinos.org/files/TrilinosBuildReference.html#enabling-different-test-categories) (or `CONTINUOUS` if these expensive tests are categorized as `NIGHTLY`).

As shown in [this query](https://trilinos-cdash.sandia.gov/queryTests.php?project=Trilinos&begin=2022-09-01&end=2022-11-21&filtercount=4&showfilters=1&filtercombine=and&field1=testname&compare1=61&value1=Tempus_IMEX_RK_Partitioned_Staggered_FSA_Partitioned_IMEX_RK_1st_Order_MPI_1&field2=groupname&compare2=61&value2=Pull%20Request&field3=buildname&compare3=64&value3=rhel7_sems-gnu-7.2.0-openmpi-1.10.1-serial_debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables&field4=buildname&compare4=64&value4=rhel7_sems-gnu-8.3.0-openmpi-1.10.1-serial_debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_all) this test finishes in less than 3m 22s in every other build and it is getting run plenty.

Why would we add an additional 7+ minutes to the test time to run these expensive tests by themselves in these debug PR builds when they are already being run in the optimized PR builds?  That does not seem reasonable.

Where is my reasoning off here?

**Comment by sebrowne** [comment]
I think I'm inclined to agree with the "run a smaller less expensive set of tests in debug mode" argument (I don't really have a horse in the race though)

**Comment by bartlettroscoe** [comment]
And note that we are still running debug-mode checking in builds that use optimized compiler flags (those are the so-called `release-debug` builds that use [`CMAKE_BUILD_TYPE=RELEASE`](https://docs.trilinos.org/files/TrilinosBuildReference.html#configuring-to-build-with-default-debug-or-release-compiler-flags) and [`Trilinos_ENABLE_DEBUG=ON`](https://docs.trilinos.org/files/TrilinosBuildReference.html#enabling-runtime-debug-checking) such as in the PR builds `rhel7_sems-gnu-8.3.0-openmpi-1.10.1-openmp_release-debug_static_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables`).  Therefore, all you are testing in full debug build `CMAKE_BUILD_TYPE=DEBUG`  is the compiler's ability to create really slow debug code.  You are not covering any more code or branches than are being covered in the other Trilinos PR builds.

If you want to make sure and cover **all** code in a full debug build, then create faster versions of these more expensive tests (e.g. just run a few time-steps or have a really loose tolerance) and mark them as `BASIC` tests.

Trilinos has a large amount of technical debt in the cost of its test suite.

**Comment by etphipp** [comment]
I wasn't saying you shouldn't disable it.  I was just trying to explain why it runs slowly.  It is fine with me if you disable it.  As a counterpoint though, disabling tests introduces its own technical debt because those disables tend to live on forever and even replicate into new builds when they are copied from an old build.

**Comment by bartlettroscoe** [comment]
> As a counterpoint though, disabling tests introduces its own technical debt because those disables tend to live on forever and even replicate into new builds when they are copied from an old build.

Then just change it so that those tests are disabled by default in all DEBUG builds when not running the `BASIC` or `CONTINUOUS` test suite.  (I can provide the CMake code to demonstrate how to do that in a traceable manner.)  Then we will not be punishing users either when they try to build and run the Trilinos test suite themselves and have a full DEBUG build.

**Comment by ccober6** [comment]
@bartlettroscoe since I am cmake novice, can you share the code on how to disable as you suggested above.

**Comment by bartlettroscoe** [comment]
> @bartlettroscoe since I am cmake novice, can you share the code on how to disable as you suggested above.

@ccober6, see the example commit linked in step B.1 in [Addressing Test Failures](https://github.com/trilinos/Trilinos/wiki/Addressing-Test-Failures).  (NOTE: That is a GenConfig file, not CMake so you will need to consult with the @trilinos/framework team if you have questions about that.)

**Comment by ccober6** [comment]
Hopefully fixed with https://github.com/trilinos/Trilinos/pull/12507.
