### ISSUE TITLE
Piro: Compile errors after recent changes

### ISSUE THREAD

**Issue by lxmota** [trilinos/Trilinos#11293]
## Bug Report
@trilinos/piro

### Description
After recent changes in Piro there are now compile errors in Albany/LCM:

GCC: https://sems-cdash-son.sandia.gov/cdash/viewBuildError.php?buildid=42084
Clang: https://sems-cdash-son.sandia.gov/cdash/viewBuildError.php?buildid=42085

Mention @ikalash and @mperego so that they are aware of this.

**Comment by mperego** [comment]
Sorry for the trouble. PR  https://github.com/sandialabs/LCM/pull/66 should fix it.

**Comment by ikalash** [comment]
@lxmota : the PR was on the LCM side.  I just merged it in.  We'll see tomorrow if things are good again with the nightlies.

**Comment by lxmota** [comment]
@ikalash Thanks! I was confused and I thought it was on the Trilinos side.

**Comment by ikalash** [comment]
I can confirm that this has been resolved.  Thanks @mperego !
