### ISSUE TITLE
seacas: de-vendor fmt

### ISSUE THREAD

**Issue by Neumann-A** [trilinos/Trilinos#11305]
## Enhancement
@trilinos/seacas

Seacas includes its own version of fmt. Unfortunately not enough care was taken to make sure that the internal fmt headers are always found before system provided fmt headers which can/will lead to undefined fmt symbols when linking parts of seacas using fmt. 
So I propose to de-vendor fmt again. A patch doing this can be found here https://github.com/microsoft/vcpkg/blob/87ec397e04c8184c8d901936fdc0e8f64466491f/ports/trilinos/devendor-fmt.patch.
(except for deleting the internal fmt folders which needs to be added)

**Comment by gsjaardema** [comment]
I will take a look.  We have removed the embedded fmt from the SEACAS external repository awhile ago.  Currently only using the embedded fmt with Trilinos until we can get fmt being used as an external TPL with Trilinos.  

Not the best situation, but what we currently have to work with.

**Comment by bartlettroscoe** [comment]
> Currently only using the embedded fmt with Trilinos until we can get fmt being used as an external TPL with Trilinos.

@gsjaardema, what is the issue getting `fmt` treated as an external package/TPL with building SEACAS along with Trilinos?  It is just that we don't want to impose another external TPL dependency on existing Trilinos users?

Note that one could set up the SEACAS TriBITS CMake package to either use an internally built version of an external dependency like `fmt` or to use an externally installed `fmt` as a TriBITS TPL.  Depending on how the CMakeLists.txt files are written, the difficulty of doing so will vary  (but even in the worse case should not be very hard).  Basically, you define the TriBITS TPL `fmt`, and if it is enabled the SEACAS CMakeLists.txt files will see `SEACAS_ENABLE_fmt=TRUE` and `TPL_ENABLE_fmt=TRUE`.  In this case, SEACAS would not build the internal version of `fmt` and just use what is provided by the TriBITS TPL `fmt`.
