### ISSUE TITLE
Framework:  Stokhos is disabled too much in PR testing

### ISSUE THREAD

**Issue by etphipp** [trilinos/Trilinos#11315]
@trilinos/framework 

Looking in the [GenConfig configuration](https://github.com/trilinos/Trilinos/blob/master/packages/framework/ini-files/config-specs.ini) many Stokhos tests are disabled in various builds, sometimes the whole package.  This has caused several regressions to be introduced because the code was never checked by the autotester.  I know this was done for various reasons, but if feasible I would like to start re-enabling those tests to help catch future regressions.  However, I don't want to just undo all of them and throw PR testing into a tizzy or slow down any of the major framework activities going on right now.  Is there a good time for me to start submitting PRs that undo some of these disables, and a priority in terms of which builds to start with or avoid?  I am not aware of any outstanding build or test failures for Stokhos on any platform or configuration.

**Comment by sebrowne** [comment]
@etphipp I'm inclined to agree with your feelings about test disables in general.  Luckily though, all of the Stokhos test disables are strictly applied to ATS2 and weaver configs, both of which will be removed this morning with the C++17 changeover DST.  There is one more case where Stokhos itself is disabled (which will also be removed with the C++17 upgrade).

Let me revisit this tomorrow to double-check, but all Stokhos disables should be gone after this morning.

**Comment by etphipp** [comment]
Excellent!  Thank you @sebrowne!

**Comment by sebrowne** [comment]
As of #11158 this should be resolved.
