### ISSUE TITLE
MueLu: tests/scaling driver does not check input vector dimensions

### ISSUE THREAD

**Issue by GrahamBenHarper** [trilinos/Trilinos#11323]
## Bug Report
@trilinos/muelu 

### Description
I was running the tests/scaling driver earlier while working on new features, and I noticed that the driver was running without complaint while using a matrix and a rhs that didn't even have compatible dimensions. We should double-check dimensions to prevent whatever strange situations may arise as a result.

### Steps to Reproduce
Copy any matrix-market vector you want into `packages/muelu/test/scaling/GblkRhs.dat` and the tests still accept it and run.

**Comment by cgcgcg** [comment]
Not for me:
```
16:  Failed to read the multivector's data: /home/caglusa/Trilinos/packages/tpetra/core/inout/MatrixMarket_Tpetra.hpp:4491:
16:  
16:  Throw number = 1
16:  
16:  Throw test that evaluated to true: as<global_size_t> (X_view.size ()) < numRows * numCols
16:  
16:  The view of X has size 137 which is not enough to accommodate the expected number of entries numRows*numCols = 138*1 = 138.  Please report this bug to the Tpetra developers.
```

**Comment by GrahamBenHarper** [comment]
Ah that's so weird. I definitely messed up when I "replicated" it a few minutes ago (forgot to rebuild to copy the vector over to the build directory), but I have no clue what was happening earlier today because I swear it was solving a 14k-by-14k matrix with a 4k length rhs vector. Nevermind :stuck_out_tongue:
