### ISSUE TITLE
Introduce capability to pass (error) message through minitensor::MiniSolver

### ISSUE THREAD

**Issue by lxmota** [trilinos/Trilinos#1132]
Propagated from https://github.com/gahansen/Albany/issues/79 as it requires changes in MiniTensor.

Also, how to add a minitensor label to Trilinos issues?

@callema21 wrote:

I would like to have the ability to pass an (error) message out of MiniSolver up from a function being called therein. This will support information gathering about failures in LCM constitutive models.

**Comment by ibaned** [comment]
@lxmota  for labels, click above on "Issues", then click "Labels" in the middle, then "New Label" on the right.
