### ISSUE TITLE
Warnings in Trilinos CUDA build

### ISSUE THREAD

**Issue by bathmatt** [trilinos/Trilinos#1133]
Right now we have 21K unique warnings when we build trilinos with cuda.  I've attached a script to show this on shiller when one tries to build panzer.  Because of this there is a lot of info lost in these warnings and it would be good to clean them up.  I've attached the zip file with all the warnings listed.  The worst is stk with boost errors, 

If package owners can look at these and help reduce where we can.  I'm following @mwglass suggestion to reduce the stk ones by including boost as a system lib.  I know @rppawlo is looking at nox and @bartlettroscoe is looking at thyra.  

[warn.zip](https://github.com/trilinos/Trilinos/files/841560/warn.zip)

@jwillenbring here is a question, do we want to assign issues to each of these packages to clean them up?  Is this a priority?

       1        5      117 shards.warn
       1        7      144 ifpack2.warn
       2       10      257 zoltan2.warn
       2       10      257 zoltan.warn
       2       10      299 kokkos-kernels.warn
       2       14      277 triutils.warn
       2       20      362 common.warn
       3       15      421 tpetra.warn
       3       21      466 aztecoo.warn
       4       20      491 piro.warn
       4       32      671 kokkos.warn
       5       33      601 ml.warn
       7       44      906 sacado.warn
       8      156     3319 rol.warn
       8       44     1276 stratimikos.warn
       9       45      978 fei.warn
      14       78     1953 belos.warn
      14       86     2020 rythmos.warn
      16      152     2539 teuchos.warn
      17      109     2366 pamgen.warn
      22      118     2682 nox.warn
      27      137     3496 xpetra.warn
      28      232     4968 epetraext.warn
      32      501     9306 DrekarResearch.warn
      33      257     5658 ifpack.warn
      43      427     8170 teko.warn
      45      335     7209 epetra.warn
      49      257     8162 thyra.warn
      70      447     9110 seacas.warn
     108     1623    25106 panzer.warn
     160     2375    39783 DrekarBase.warn
  
[config.txt](https://github.com/trilinos/Trilinos/files/841543/config.txt)

**Reproducability Instructions for single packages**

See reproducability instructions [below](https://github.com/trilinos/Trilinos/issues/1133#issuecomment-288105176).

**Comment by kddevin** [comment]
Zoltan2/zoltan warnings are fixed.  8f5dd739509a25b9068fbf028e9dd289e56e5764
Thanks for sifting the warnings out for us, @bathmatt .

**Comment by bathmatt** [comment]
Here is the list for icpc/icc  List is included.
[warn_icc.zip](https://github.com/trilinos/Trilinos/files/842544/warn_icc.zip)
 

  1   11  183 zoltan.warn
   1   14  185 aztecoo.warn
   1    6   97 seacas.warn
   2   24  406 DrekarBase.warn
   3   30  573 stk.warn
   3   42  943 ifpack.warn
   6   60 1005 teko.warn
   8  108 1817 panzer.warn
  25  295 5209 total

**Comment by bartlettroscoe** [comment]
I am taking care of the Thyra and Stratimikos warnings in #1140.  Roger is taking care of the NOX/LOCA warnings in #1139.

**Comment by gsjaardema** [comment]
I will fix the seacas warnings.  However, several of them are in generated code (from flex/lex).  Is there a pragma that can be used to suppress the "unreachable code" warning in a specific file?

Also, there is a false positive in that it is picking up a filename of "warnings.c.o"

**Comment by bathmatt** [comment]
for the clang comiler
[clang.zip](https://github.com/trilinos/Trilinos/files/844897/clang.zip)


    1     5   101 seacas.warn
    2    20   364 stk.warn
    2    20   404 kokkos-kernels.warn
    2    20   404 kokkos.warn
    2    26   433 phalanx.warn
    3    18   448 ifpack.warn
    6   108  1478 teuchos.warn
    6    90  1122 pamgen.warn
    8   136  2264 muelu.warn
    8    92  1325 aztecoo.warn
   10   120  2391 DrekarResearch.warn
   11   120  1890 ml.warn
  108  1154 24007 DrekarBase.warn
  261  3118 62741 panzer.warn
  430  5047 99372 total

**Comment by bathmatt** [comment]
@gdsjaar I don't know of anything to supress unreachable code.  Sorry, @bartlettroscoe may know this type of thing??  
And sorry about the warnings.c.o file :)

**Comment by etphipp** [comment]
One thing that can help with nvcc warnings is to disable some of them.  I add this to my cxxflags:
 
`-Xcudafe --diag_suppress=conversion_function_not_usable -Xcudafe --diag_suppress=cc_clobber_ignored -Xcudafe --diag_suppress=code_is_unreachable`
 
That will get rid of some of these superfluous warnings.  A full list of warnings you can turn off is here:
 
http://www.ssl.berkeley.edu/~jimm/grizzly_docs/SSL/opt/intel/cc/9.0/lib/locale/en_US/mcpcom.msg
 
Looks like adding
 
`-Xcudafe --diag_suppress=unsigned_compare_with_zero -Xcudafe --diag_suppress=useless_type_qualifier_on_return_type`
 
would get rid of the pointless comparison and meaningless qualifier warnings.

**Comment by etphipp** [comment]
The -Xcudafe --diag_suppress=code_is_unreachable will suppress the code is unreachable warning.

**Comment by bathmatt** [comment]
I'm worried about suppressing that warning everywhere since I've found things by having it on..  not often though.  I know @bartlettroscoe is looking into macros to help suppress some of these. Things like this (but actual good code) which is the root of a lot of these issues.  
```
#define my_throw_return(....)
throw
#ifndef CUDA
return 0;
#endif

```

**Comment by mwglass** [comment]
#if defined __NVCC__
  #pragma diag_suppress code_is_unreachable
#endif

**Comment by bartlettroscoe** [comment]
All Teuchos, Thyra and Stratimikos warnings should be gone for NVCC on shiller now (see log from (2017/03/20) [here](https://github.com/trilinos/Trilinos/issues/1140#issuecomment-288099504)).

**Comment by bartlettroscoe** [comment]
Now to document how others can reproduce these warnings on an ATTB CUDA machine like hansen or shiller ...

While one can use the full configure script provided [above](https://github.com/trilinos/Trilinos/issues/1133#issue-214087211), that will configure and build all of the Trilinos packages used by Drekar.  That takes a bit of time to configure on these slow ATTB machines and it takes almost 8 hours to build all of that.

Therefore, I have broken that provided script down into pieces that will allow you to more easily work on the warnings for just your package.  Here is how you do that (after cloning Trilinos on an ATTB machine like hansen or shiller):

```
$ cd <some_build_dir>/
$ export TRILINOS_BASE_DIR=<abs_path_to_your_local Trilinos_clone>
$ source $TRILINOS_BASE_DIR/cmake/ctest/drivers/ATTB/load_attb_cuda_env.sh
$ ln -s $TRILINOS_BASE_DIR/cmake/ctest/drivers/ATTB/attb_cuda_config_base.sh .
$ ./attb_cuda_config_base.sh -DTrilinos_ENABLE_<package_you_want_to_enable>=ON \
    -DTrilinos_ENABLE_TESTS=ON
$ make -j10 &> make.out
````

Then to view the warnings for your package, do:

```
$ grep "warning: " make.out | grep "packages/<your_package_dir>" | sort | uniq
```

Now you can fix the warnings for your package for the NVCC CUDA compiler on the ATTB machines.
