### ISSUE TITLE
Check CXX_STANDARD >= 17 at configuration, error out if condition not met

### ISSUE THREAD

**Issue by ndellingwood** [trilinos/Trilinos#11356]
## Enhancement
@trilinos/framework @trilinos/tribits 

I'm not sure which package or team to indicate for the request, so I added framework and tribits to start discussion.

With the updated requirement for c++17 with testing, this issue is to request setting c++17 as the default c++ standard in Trilinos and add a test to check at configuration to confirm this minimum has been met.

A quick check configuring with SHA 940ead2f01e87d7f96134e48d7248a8f2ba71b4c shows the current default is still c++14

The motivation for the request is that the update to c++17 for testing allows newer c++ features into the code base that requires c++17 as a minimum in order to compile (e.g. our eagerly anticipated usage of`if constexpr` , like that included with PR #11338)

When compiling with compilers without c++17 enabled (and that do not support c++17, e.g. cuda/10.1.105) the build could error out (in this case when Stokhos is enabled) though the output message does not make the reason clear:

```
/home/jenkins/weaver-new/workspace/KokkosEco_Trilinos_Weaver_CUDA101_opt/Trilinos/packages/stokhos/src/sacado/kokkos/vector/Sacado_MP_Vector.hpp(272): error: expected a "("
```

(The above is not missing a "(" but makes use of `if constexpr` not recognized by the compiler https://github.com/trilinos/Trilinos/blob/3adb30811047b5690c8344679f5933b9962e267d/packages/stokhos/src/sacado/kokkos/vector/Sacado_MP_Vector.hpp#L272)

**Comment by glhenni** [comment]
I have a weird error when setting `CMAKE_CXX_STANDARD:STRING=17` and use the intel compiler (version below). exodiff (in the seacas package) hangs for a significant number of our regression tests, but strangely not all. I also see errors thrown by epu, another seacas utility. Am I the only one that sees this?

CDE/v3 modules on CEE/ASCIC, intel compiler + OpenMPI 4.1.2
```
% mpicxx --version
icpc (ICC) 2021.1.2 20201208
Copyright (C) 1985-2020 Intel Corporation.  All rights reserved.
```

**Comment by sebrowne** [comment]
@trilinos/seacas

**Comment by glhenni** [comment]
This may just be a problem in *epu*. It's possible the *exodiff* problem is due to the fact that a previous *epu* invocation for the same problem fails. At any rate, I compiled a debug version and there's an assertion failing:
```
Trilinos/packages/seacas/libraries/suplib_cpp/fmt/format-inl.h:699: assertion failed: terminate called without an active exception
```
note that I put a few print statements in that file so the line in the unaltered `format-inl.h` file is 696,
```
FMT_ASSERT(integral == value.f >> -one.e, "");
```

If I compile with c++14 flag set the output of my print statements above that assertion is:
```
	Transferring step 1 to step 1 by 1
integral = 0.000000e+00
value.f = 0.000000e+00
-one.e = 0.000000e+00
```
whereas with c++17 the output is:
```
	Transferring step 1 to step 1 by 1
integral = 1.581010e-322
value.f = 1.581010e-322
-one.e = 1.581010e-322
```

**Comment by glhenni** [comment]
More data, it's bombing when outputting the times to the screen, like line 1639 in *epu.C* (sha1:75bf7c0a). The same thing happens in *exodiff* for the exact same reason. 

I don't fully understand the purpose of the *fmt* stuff so the reason this happens when c++17 is enabled but not when c++14 is enabled eludes me.

**Comment by glhenni** [comment]
It's looking like this is a compiler bug, or some extension implemented in GNU and llvm that intel didn't implement. It works for GNU 10.3 and clang 12 with and without `-std=c++17` but as soon as I add that argument to the intel build it fails. Included below is my best attempt at isolating the problem. The code is a snippet of something out of the *fmt* source code. I can't believe I'm the only one that's going to see this once trilinos moves to `-std=c++17` as the default. 

Compilers I used for this:
- Intel 19.1.2.254 20200623 (cde/v3 modules)
- Intel 2021.1.2 20201208 (cde/v2 modules)
- Intel 2021.3.0 20210609 (sparc intel-2021.3.0_intelmpi-2021.3.0 module)
- GNU 10.3.0
- clang 12.0.1

```c++
#include <iostream>

template <typename T = void> struct basic_impl_data {
  // Normalized 64-bit significands of pow(10, k), for k = -348, -340, ..., 340.
  // These are generated by support/compute-powers.py.
  static constexpr uint64_t pow10_significands[87] = {
  0xfa8fd5a0081c0288, 0xbaaee17fa23ebf76, 0x8b16fb203055ac76,
    0xcf42894a5dce35ea, 0x9a6bb0aa55653b2d, 0xe61acf033d1a45df,
    0xab70fe17c79ac6ca, 0xff77b1fcbebcdc4f, 0xbe5691ef416bd60c,
    0x8dd01fad907ffc3c, 0xd3515c2831559a83, 0x9d71ac8fada6c9b5,
    0xea9c227723ee8bcb, 0xaecc49914078536d, 0x823c12795db6ce57,
    0xc21094364dfb5637, 0x9096ea6f3848984f, 0xd77485cb25823ac7,
    0xa086cfcd97bf97f4, 0xef340a98172aace5, 0xb23867fb2a35b28e,
    0x84c8d4dfd2c63f3b, 0xc5dd44271ad3cdba, 0x936b9fcebb25c996,
    0xdbac6c247d62a584, 0xa3ab66580d5fdaf6, 0xf3e2f893dec3f126,
    0xb5b5ada8aaff80b8, 0x87625f056c7c4a8b, 0xc9bcff6034c13053,
    0x964e858c91ba2655, 0xdff9772470297ebd, 0xa6dfbd9fb8e5b88f,
    0xf8a95fcf88747d94, 0xb94470938fa89bcf, 0x8a08f0f8bf0f156b,
    0xcdb02555653131b6, 0x993fe2c6d07b7fac, 0xe45c10c42a2b3b06,
    0xaa242499697392d3, 0xfd87b5f28300ca0e, 0xbce5086492111aeb,
    0x8cbccc096f5088cc, 0xd1b71758e219652c, 0x9c40000000000000,
    0xe8d4a51000000000, 0xad78ebc5ac620000, 0x813f3978f8940984,
    0xc097ce7bc90715b3, 0x8f7e32ce7bea5c70, 0xd5d238a4abe98068,
    0x9f4f2726179a2245, 0xed63a231d4c4fb27, 0xb0de65388cc8ada8,
    0x83c7088e1aab65db, 0xc45d1df942711d9a, 0x924d692ca61be758,
    0xda01ee641a708dea, 0xa26da3999aef774a, 0xf209787bb47d6b85,
    0xb454e4a179dd1877, 0x865b86925b9bc5c2, 0xc83553c5c8965d3d,
    0x952ab45cfa97a0b3, 0xde469fbd99a05fe3, 0xa59bc234db398c25,
    0xf6c69a72a3989f5c, 0xb7dcbf5354e9bece, 0x88fcf317f22241e2,
    0xcc20ce9bd35c78a5, 0x98165af37b2153df, 0xe2a0b5dc971f303a,
    0xa8d9d1535ce3b396, 0xfb9b7cd9a4a7443c, 0xbb764c4ca7a44410,
    0x8bab8eefb6409c1a, 0xd01fef10a657842c, 0x9b10a4e5e9913129,
    0xe7109bfba19c0c9d, 0xac2820d9623bf429, 0x80444b5e7aa7cf85,
    0xbf21e44003acdd2d, 0x8e679c2f5e44ff8f, 0xd433179d9c8cb841,
    0x9e19db92b4e31ba9, 0xeb96bf6ebadf77d9, 0xaf87023b9bf0ee6b,
    };

#if FMT_GCC_VERSION && FMT_GCC_VERSION < 409
#  pragma GCC diagnostic push
#  pragma GCC diagnostic ignored "-Wnarrowing"
#endif
  // Binary exponents of pow(10, k), for k = -348, -340, ..., 340, corresponding
  // to significands above.
  static constexpr int16_t pow10_exponents[87] = {
    -1220, -1193, -1166, -1140, -1113, -1087, -1060, -1034, -1007, -980, -954,
      -927,  -901,  -874,  -847,  -821,  -794,  -768,  -741,  -715,  -688, -661,
      -635,  -608,  -582,  -555,  -529,  -502,  -475,  -449,  -422,  -396, -369,
      -343,  -316,  -289,  -263,  -236,  -210,  -183,  -157,  -130,  -103, -77,
      -50,   -24,   3,     30,    56,    83,    109,   136,   162,   189,  216,
      242,   269,   295,   322,   348,   375,   402,   428,   455,   481,  508,
      534,   561,   588,   614,   641,   667,   694,   720,   747,   774,  800,
      827,   853,   880,   907,   933,   960,   986,   1013,  1039,  1066};
#if FMT_GCC_VERSION && FMT_GCC_VERSION < 409
#  pragma GCC diagnostic pop
#endif

};

#if __cplusplus < 201703L
    template <typename T> constexpr uint64_t basic_impl_data<T>::pow10_significands[];
    template <typename T> constexpr int16_t basic_impl_data<T>::pow10_exponents[];
#endif

int main(int argc, char** argv)
{
  uint index(44);
  std::cout << "__cplusplus = " << __cplusplus << std::endl;

  printf("pow10_exponents[%d] = %d\n", index, basic_impl_data<>::pow10_exponents[index]);
  printf("pow10_significands[%d] = %lx\n", index, basic_impl_data<>::pow10_significands[index]);

  return 0;
}
```

If you compile it with Intel compilers listed above, with a `-std=c++17` argument, the output is:
```
__cplusplus = 201703
pow10_exponents[44] = 0
pow10_significands[44] = 0

```
If you compile it with GNU or clang, with or without the `-std=c++17` argument;  or if you compile it with intel without the `-std=c++17` argument the output is:
```
__cplusplus = 201703
pow10_exponents[44] = -50
pow10_significands[44] = 9c40000000000000
```

**Comment by ccober6** [comment]
@trilinos/seacas @gsjaardema Hi Greg, it looks like this may be the last holdup on moving forward on C++17.  Do you have any information or timeline on investigated this?  Thanks, Curt

**Comment by sebrowne** [comment]
#11442

**Comment by ndellingwood** [comment]
#11357 merged, thanks @sebrowne !
