### ISSUE TITLE
Percept:  Generalization needed in CMakeLists.txt

### ISSUE THREAD

**Issue by glhenni** [trilinos/Trilinos#11366]
In the project I work on, charon, we use some capability whose name I don't recall, but I'm sure @bartlettroscoe knows, where we supplant the PROJECT_NAME "Trilinos" with our own project name "tcad-charon", with Trilinos subsumed into the "tcad-charon" project. 

The effect of this is that other subprojects, like Percept, can't use variables like `${Trilinos_ENABLE_DEBUG}` but instead should use `${${PROJECT_NAME}_ENABLE_DEBUG}`. The `CMakeLists.txt` in Percept's root breaks when Percept is enabled as part of charon's configuration for this reason. The simple diff below will fix it.

```
diff --git a/packages/percept/CMakeLists.txt b/packages/percept/CMakeLists.txt
index 1eab9908334..14f35fb2a54 100644
--- a/packages/percept/CMakeLists.txt
+++ b/packages/percept/CMakeLists.txt
@@ -11,7 +11,7 @@ TRIBITS_PACKAGE(Percept)
 TRIBITS_ADD_OPTION_AND_DEFINE(${PACKAGE_NAME}_ENABLE_DEBUG
   PERCEPT_DEBUG
   "Build with debug code enabled."
-  ${Trilinos_ENABLE_DEBUG})
+  ${${PROJECT_NAME}_ENABLE_DEBUG})
 
 TRIBITS_ADD_OPTION_AND_DEFINE(${PACKAGE_NAME}_ENABLE_GEOMETRY
   STK_PERCEPT_HAS_GEOMETRY
```

**Comment by bartlettroscoe** [comment]
@glhenni, correct.  Some packages need to be updated every now and then that accidentally use `Trilinos` when it should be `${PROJECT_NAME}`.

And the feature you are using with Charon is that "tcad-charon" is the [TriBITS project](https://tribitspub.github.io/TriBITS/users_guide/index.html#tribits-project) and Trilinos is just a [TriBITS Repository](https://tribitspub.github.io/TriBITS/users_guide/index.html#tribits-repository) in that TriBITS project.  See [Multi-Repository Support](https://tribitspub.github.io/TriBITS/users_guide/index.html#multi-repository-support).

**Comment by bartlettroscoe** [comment]
@trilinos/percept

**Comment by rppawlo** [comment]
@glhenni - Thanks for posting this! The fix was just merged.
