### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by o-kazemi** [trilinos/Trilinos#11396]
Hi there,

I am trying to install the Trilions, but I get the following error. Would anyone please help me?
Thanks.
(base) omid@omid-HP:~/Program/Trilinos-master/build$ cmake \-DCMAKE_INSTALL_PREFIX=/home/omid/Program/Trilinos-master\-DTrilinos_ENABLE_Sacado=ON \-DTrilinos_ENABLE_Teuchos=OFF 
CMake Warning:
  No source or binary directory provided.  Both will be assumed to be the
  same as the current working directory, but note that this warning will
  become a fatal error in future CMake releases.

CMake Error: The source directory "/home/omid/Program/Trilinos-master/build" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.

**Comment by GrahamBenHarper** [comment]
when using CMake, you have to specify where your source directory is. The correct form of the command should be something like 
```
cmake -DCMAKE_INSTALL_PREFIX=/home/omid/Program/Trilinos-master -DTrilinos_ENABLE_Sacado=ON -DTrilinos_ENABLE_Teuchos=OFF YOURSOURCEDIRECTORY
```

**Comment by GrahamBenHarper** [comment]
Closing as completed, but please reopen if this did not fix it.
