### ISSUE TITLE
Stokhos: CUSPARSE_MM_ALG_DEFAULT is not defined in CUDA 12

### ISSUE THREAD

**Issue by romintomasetti** [trilinos/Trilinos#11398]
## Bug Report

@etphipp

### Description

The fixes introduced in
* https://github.com/trilinos/Trilinos/pull/11165

in `packages/stokhos/src/kokkos/Cuda/Stokhos_Cuda_CrsMatrix.hpp` will not compile on `CUDA 12` because of
* https://github.com/kokkos/kokkos-kernels/issues/1630

We also wonder why `KokkosSparse::Impl::spmv_mv_cusparse` was not used in `packages/stokhos/src/kokkos/Cuda/Stokhos_Cuda_CrsMatrix.hpp`. Do you have some more information about that?

Thanks!

**Comment by etphipp** [comment]
The reason `KokkosSparse::Impl::spmv_mv_cusparse` is historical, the code was written before Kokkos-Kernels even existed.  As for the bug, do you have a suggested solution?

**Comment by maartenarnst** [comment]
We took a look into the cusparse library manual for cuda 12.  It's available here:
- https://docs.nvidia.com/cuda/pdf/CUSPARSE_Library.pdf

The parameters for the SPMM algorithm are on Page 246.  The default algorithm was renamed `CUSPARSE_SPMM_ALG_DEFAULT`.

We could code an `#ifdef` based on the `cudart` variable to use `CUSPARSE_MM_ALG_DEFAULT` for cuda < 12 and `CUSPARSE_SPMM_ALG_DEFAULT` for cuda >=12.

We would probably need to coordinate with kokkos-kernels, where a similar function is coded?  How do you think we should proceed?

**Comment by etphipp** [comment]
Once Kokkos-Kernels fixes their issue, we should probably just change Stokhos to use it instead of rolling our own.

**Comment by maartenarnst** [comment]
Thanks, Eric!  On our side, we'll go ahead and implement in our fork a fix with an `#ifdef`.  We'll keep you updated and post it here if we find it works.
