### ISSUE TITLE
Fails to find 'mpi.h' when -DTPL_ENABLE_MPI:BOOL=ON is specified

### ISSUE THREAD

**Issue by yurivict** [trilinos/Trilinos#11395]
Build succeeds without MPI, but it fails when MPI is enabled with ```-DTPL_ENABLE_MPI:BOOL=ON -DMPI_BASE_DIR:PATH=/usr/local -DMPI_BIN_DIR:PATH=/usr/local/bin```.

All cmake arguments:
> -DCMAKE_INSTALL_PREFIX:PATH=/usr/local -DBUILD_SHARED_LIBS:BOOL=ON -DTrilinos_ENABLE_ALL_PACKAGES:BOOL=ON -DTrilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=ON -DTrilinos_ENABLE_SEACAS:BOOL=OFF -DTrilinos_ENABLE_OpenMP:BOOL=OFF -DTPL_ENABLE_MPI:BOOL=ON -DUMFPACK_INCLUDE_DIRS=/usr/local/include/suitesparse -DTPL_AMD_INCLUDE_DIRS=/usr/local/include/suitesparse -DAMD_LIBRARY_DIRS=/usr/local/lib -DMPI_BASE_DIR:PATH=/usr/local  -DMPI_BIN_DIR:PATH=/usr/local/bin -DCMAKE_C_COMPILER:STRING="cc"  -DCMAKE_CXX_COMPILER:STRING="c++"  -DCMAKE_C_FLAGS:STRING="-O2 -pipe  -fstack-protector-strong -fno-strict-aliasing "  -DCMAKE_C_FLAGS_DEBUG:STRING="-O2 -pipe  -fstack-protector-strong -fno-strict-aliasing "  -DCMAKE_C_FLAGS_RELEASE:STRING="-O2 -pipe  -fstack-protector-strong -fno-strict-aliasing  -DNDEBUG"  -DCMAKE_CXX_FLAGS:STRING="-O2 -pipe -fstack-protector-strong -fno-strict-aliasing  -DBOOST_STACKTRACE_GNU_SOURCE_NOT_REQUIRED "  -DCMAKE_CXX_FLAGS_DEBUG:STRING="-O2 -pipe -fstack-protector-strong -fno-strict-aliasing  -DBOOST_STACKTRACE_GNU_SOURCE_NOT_REQUIRED "  -DCMAKE_CXX_FLAGS_RELEASE:STRING="-O2 -pipe -fstack-protector-strong -fno-strict-aliasing  -DBOOST_STACKTRACE_GNU_SOURCE_NOT_REQUIRED  -DNDEBUG"  -DCMAKE_EXE_LINKER_FLAGS:STRING=" -lexecinfo -Wl,-rpath=/usr/local/lib/gcc12  -L/usr/local/lib/gcc12 -B/usr/local/bin -fstack-protector-strong "  -DCMAKE_MODULE_LINKER_FLAGS:STRING=" -lexecinfo -Wl,-rpath=/usr/local/lib/gcc12  -L/usr/local/lib/gcc12 -B/usr/local/bin -fstack-protector-strong "  -DCMAKE_SHARED_LINKER_FLAGS:STRING=" -lexecinfo -Wl,-rpath=/usr/local/lib/gcc12  -L/usr/local/lib/gcc12 -B/usr/local/bin -fstack-protector-strong "  -DCMAKE_INSTALL_PREFIX:PATH="/usr/local"  -DCMAKE_BUILD_TYPE:STRING="Release"  -DTHREADS_HAVE_PTHREAD_ARG:BOOL=YES  -DCMAKE_INSTALL_RPATH_USE_LINK_PATH=YES  -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON  -DFETCHCONTENT_FULLY_DISCONNECTED:BOOL=ON -DEpetraExt_BUILD_BTF:BOOL=ON -DEpetraExt_BUILD_EXPERIMENTAL:BOOL=ON -DEpetraExt_BUILD_GRAPH_REORDERINGS:BOOL=ON -DTrilinos_ENABLE_COMPLEX_DOUBLE:BOOL=ON -DTPL_ENABLE_UMFPACK:BOOL=ON -DTPL_ENABLE_AMD:BOOL=ON -DPython_ADDITIONAL_VERSIONS=3.9 -DBOOST_PYTHON_SUFFIX:STRING=39 -DMPIEXEC_EXECUTABLE:FILEPATH="/usr/local/bin/mpiexec"	 -DMPI_HOME:PATH="/usr/local"

Failure:
```
cd /disk-samsung/freebsd-ports/science/trilinos/work/.build/packages/kokkos/core/src && /usr/local/libexec/ccache/c++ -Dkokkoscore_EXPORTS -I/disk-samsung/freebsd-ports/science/trilinos/work/.build -I/disk-samsung/freebsd-ports/science/trilinos/work/.build/packages/kokkos/core/src -I/disk-samsung/freebsd-ports/science/trilinos/work/Trilinos-trilinos-release-13-4-1/packages/kokkos/core/src -I/disk-samsung/freebsd-ports/science/trilinos/work/.build/packages/kokkos -O2 -pipe -fstack-protector-strong -fno-strict-aliasing  -DBOOST_STACKTRACE_GNU_SOURCE_NOT_REQUIRED   -O2 -pipe -fstack-protector-strong -fno-strict-aliasing  -DBOOST_STACKTRACE_GNU_SOURCE_NOT_REQUIRED  -DNDEBUG -fPIC -std=c++14 -MD -MT packages/kokkos/core/src/CMakeFiles/kokkoscore.dir/impl/Kokkos_HostSpace_deepcopy.cpp.o -MF CMakeFiles/kokkoscore.dir/impl/Kokkos_HostSpace_deepcopy.cpp.o.d -o CMakeFiles/kokkoscore.dir/impl/Kokkos_HostSpace_deepcopy.cpp.o -c /disk-samsung/freebsd-ports/science/trilinos/work/Trilinos-trilinos-release-13-4-1/packages/kokkos/core/src/impl/Kokkos_HostSpace_deepcopy.cpp
--- packages/muelu/doc/UsersGuide/CMakeFiles/MueLu_CopyMasterListTestFiles.dir/all ---
cd /disk-samsung/freebsd-ports/science/trilinos/work/.build/packages/muelu/doc/UsersGuide && /usr/local/bin/cmake -E copy /disk-samsung/freebsd-ports/science/trilinos/work/Trilinos-trilinos-release-13-4-1/packages/muelu/doc/UsersGuide/definitions.tex /disk-samsung/freebsd-ports/science/trilinos/work/.build/packages/muelu/doc/UsersGuide/definitions.tex
--- packages/pamgen/src/CMakeFiles/pamgen.dir/all ---
[  0%] Building CXX object packages/pamgen/src/CMakeFiles/pamgen.dir/radial_inline_mesh_desc.C.o
cd /disk-samsung/freebsd-ports/science/trilinos/work/.build/packages/pamgen/src && /usr/local/libexec/ccache/c++ -Dpamgen_EXPORTS -I/disk-samsung/freebsd-ports/science/trilinos/work/.build -I/disk-samsung/freebsd-ports/science/trilinos/work/.build/packages/pamgen/src -I/disk-samsung/freebsd-ports/science/trilinos/work/Trilinos-trilinos-release-13-4-1/packages/pamgen/src -I/disk-samsung/freebsd-ports/science/trilinos/work/Trilinos-trilinos-release-13-4-1/packages/pamgen/mesh_spec_lt -I/disk-samsung/freebsd-ports/science/trilinos/work/Trilinos-trilinos-release-13-4-1/packages/pamgen/extra_functions -I/disk-samsung/freebsd-ports/science/trilinos/work/Trilinos-trilinos-release-13-4-1/packages/pamgen/rtcompiler -I/usr/local/include -O2 -pipe -fstack-protector-strong -fno-strict-aliasing  -DBOOST_STACKTRACE_GNU_SOURCE_NOT_REQUIRED   -O2 -pipe -fstack-protector-strong -fno-strict-aliasing  -DBOOST_STACKTRACE_GNU_SOURCE_NOT_REQUIRED  -DNDEBUG -fPIC -std=c++14 -MD -MT packages/pamgen/src/CMakeFiles/pamgen.dir/radial_inline_mesh_desc.C.o -MF CMakeFiles/pamgen.dir/radial_inline_mesh_desc.C.o.d -o CMakeFiles/pamgen.dir/radial_inline_mesh_desc.C.o -c /disk-samsung/freebsd-ports/science/trilinos/work/Trilinos-trilinos-release-13-4-1/packages/pamgen/src/radial_inline_mesh_desc.C
--- packages/common/auxiliarySoftware/SuiteSparse/src/CMakeFiles/trilinosss.dir/all ---
--- packages/common/auxiliarySoftware/SuiteSparse/src/CMakeFiles/trilinosss.dir/CAMD/Source/trilinos_camd_aat.c.o ---
--- packages/muelu/doc/UsersGuide/CMakeFiles/MueLu_CopyMasterListTestFiles.dir/all ---
--- packages/muelu/doc/UsersGuide/gen_interpreter.xsl ---
--- packages/zoltan/src/CMakeFiles/zoltan.dir/all ---
--- packages/zoltan/src/CMakeFiles/zoltan.dir/all/all_allo.c.o ---
In file included from /disk-samsung/freebsd-ports/science/trilinos/work/Trilinos-trilinos-release-13-4-1/packages/zoltan/src/all/all_allo.c:57:
In file included from /disk-samsung/freebsd-ports/science/trilinos/work/Trilinos-trilinos-release-13-4-1/packages/zoltan/src/all/all_allo_const.h:51:
In file included from /disk-samsung/freebsd-ports/science/trilinos/work/Trilinos-trilinos-release-13-4-1/packages/zoltan/src/zz/zz_const.h:58:
/disk-samsung/freebsd-ports/science/trilinos/work/Trilinos-trilinos-release-13-4-1/packages/zoltan/src/include/zoltan.h:50:10: fatal error: 'mpi.h' file not found
#include <mpi.h>
         ^~~~~~~
```

Version: 13-4-1
clang-14
FreeBSD 13.1

**Comment by cgcgcg** [comment]
Try to remove `MPI_BASE_DIR` and `MPI_BIN_DIR` from your CMake line. These paths are already searched anyway I think. I believe some of the TPL detection logic is skipped if you specifying them explicitly.

**Comment by yurivict** [comment]
Same problem w/out MPI_BASE_DIR and MPI_BIN_DIR.

**Comment by cgcgcg** [comment]
Wait, it actually starts compiling and doesn't fail in CMake?

**Comment by yurivict** [comment]
Yes. It fails to provide the path to MPI headers to compilation.

A common way to provide the MPI implementation to cmake is through ```-DMPI_HOME:PATH="${MPI_HOME}"```. This is done here too.

**Comment by yurivict** [comment]
Log: 
[trilinos-13.4.1.txt](https://github.com/trilinos/Trilinos/files/10241124/trilinos-13.4.1.txt)

**Comment by cgcgcg** [comment]
Just double checking: mpi.h is at /usr/local/include/mpi.h ?

**Comment by yurivict** [comment]
> Just double checking: mpi.h is at /usr/local/include/mpi.h ?

Yes

**Comment by cgcgcg** [comment]
Wait, are the MPI compiler wrappers actually used? It looks like you're using ccache wrappers and MPI compiler wrappers.

**Comment by yurivict** [comment]
Same happens w/out ccache:
[trilinos-13.4.1-no-ccache.txt](https://github.com/trilinos/Trilinos/files/10241475/trilinos-13.4.1-no-ccache.txt)

**Comment by cgcgcg** [comment]
It's not using the MPI compiler wrappers though:
```
-- Leaving current CMAKE_C_COMPILER=cc since it is already set!
-- Leaving current CMAKE_CXX_COMPILER=c++ since it is already set!
```

**Comment by yurivict** [comment]
There is a variety of ways how MPI compilers can be conveyed to the build.
1. Through passing MPI compilers
2. Through CFLAGS/CXXFLAGS/LDFLAGS
3. Through setting MPI_HOME

It looks like Trilinos fails to find an MPI implementation by default, which is a bug in Trilinos IMO.
But ways 1. and 2. do work. For me the way 2. is better because it preserves the ability to use ccache.

I can build with MPI on now.

Please consider fixing the above-mentioned bug that Trilinos fails to find an MPI implementation during the cmake phase.

**Comment by yurivict** [comment]
When ```MPI_BASE_DIR``` isn't set cmake succeeds but compilation fails. This is hinting that something is wrong with MPI detection in cmake.
