### ISSUE TITLE
importAndFillComplete problem in CUDA build

### ISSUE THREAD

**Issue by kddevin** [trilinos/Trilinos#114]
@trilinos/tpetra 
@trilinos/zoltan2 

I sent this email to the Tpetra experts last week; I'm adding it as an issue so that I don't forget about it.  This issue causes three Zoltan2 tests to fail in Christian's CUDA build on perseus.

Chris Siefert said he would take a look and help debug.

I recently modified Zoltan2 code to use importAndFillComplete.  It is
working almost everywhere, but we have failures in Christian's CUDA
build.  

Here is the error that is thrown:

lowCommunicationMakeColMapAndReindex: Cannot figure out if PID is owned.
/space/jenkins/slave/workspace/Trilinos_perseus_gcc_4.7.2_cuda_7.5.18/MPI_R
ELEASE_DEV_DownStream_ETI_SERIAL-OFF_OPENMP-OFF_PTHREAD-OFF_CUDA-ON_COMPLEX
-ON/Trilinos/packages/tpetra/core/src/Tpetra_Import_Util2.hpp:1174:

Throw number = 1

Throw test that evaluated to true: PID == -1

The call to lowCommunicationMakeColMapAndReindex is called from
transferAndFillComplete.

**Comment by csiefer2** [comment]
I'm able to reproduce the problem on geminga and trying to isolate the cause of the error.

**Comment by csiefer2** [comment]
This bug is due to an error in Tpetra's vector doExport() when used with an Import object.  This bug only seems to appear on CUDA.  I'm attaching a stand-alone driver to reproduce the problem.

@mhoemmen Can you take a crack at this driver on CUDA?

[export_bug.cpp.txt](https://github.com/trilinos/Trilinos/files/110505/export_bug.cpp.txt)

**Comment by csiefer2** [comment]
Also, I'm a little annoyed that github doesn't allow me to attach CPP files without changing them to a TXT extension.  Haters.

**Comment by mhoemmen** [comment]
> Also, I'm a little annoyed that github doesn't allow me to attach CPP files without changing them to a TXT extension. Haters.

@csiefer2 Yeah, ditto for patch files.

**Comment by mhoemmen** [comment]
> This bug is due to an error in Tpetra's vector doExport() when used with an Import object. This bug only seems to appear on CUDA. I'm attaching a stand-alone driver to reproduce the problem.

Thanks Chris!  I'll take a look.  Would you object to this file turning into a unit test?

> @mhoemmen Can you take a crack at this driver on CUDA?

I'll give it a shot.  However, my internet connectivity varies in quality in my current off-site location, so I'm not always able to keep up a connection to the testbeds.  I think what I'll do for now, if it's OK, is turn this into a unit test and get it visible first.  It may take me a little bit -- I have to do some paperwork first.

**Comment by csiefer2** [comment]
That probably would actually make a nice unit test.  

I'll do that on Monday.

**Comment by kddevin** [comment]
I have reverted the code in Zoltan2_XpetraTraits.hpp that used this feature.  There are copious comments in the file, so it should be easy for us to un-revert once this bug is fixed. (grep for SIEFERT)
c99dea93ce10db49d9d5bfbfd23b25f8a0fa737d
If anyone needs the Zoltan2 tests for testing their fix, let me know.

**Comment by mhoemmen** [comment]
Sorry @kddevin .  You might know about my current temporary situation that restricts my ability to work and communicate.  Will get to this as soon as well can.

**Comment by kddevin** [comment]
No worries, @mhoemmen .  
The nightly CDASH emails were causing some confusion in our team.  
By reverting, I was just stopping the emails for now.
Thanks!

**Comment by kddevin** [comment]
@crtrott :  Motivated by @csiefer2 's talk, I will restore use of Tpetra::importAndFillComplete in Zoltan2.  This issue arose from failures in your test suite.  I have no way to reproduce the failures in my environments.  Are you still running the test above so that, after I make the restoration, we can find out whether it now works in your environment?  Thanks.

**Comment by mhoemmen** [comment]
@kddevin wrote:
> Are you still running the test above so that, after I make the restoration, we can find out whether it now works in your environment?

Yes :-) .
