### ISSUE TITLE
Amesos2:  PardisoMKL solver not working correctly

### ISSUE THREAD

**Issue by LeaSassmannshausen** [trilinos/Trilinos#11404]
## Question @srajama1

Hello @srajama1,

I've been having some issues using the Amesos2 PardisoMKL solver.
I am currently working with a software that includes multiple Trilinos packages and I focus on scalability tests using FROSch (SkyLU).
In previous tests I used an older Trilinos Version (March 2022) before much of the deprecated code was deleted
and the Amesos2 PardisoMKL solver worked fine.

Since then the Amesos2 PardisoMKL interface was rewritten to fit the new functions  (no longer use deprecated/deleted code). 
The compilation process is working correctly, but the solver doesn't solve correctly. Other Amesos2 solvers like UMFPACK and KLU still work and solve correctly.

Did anything change with PardisoMKL that could explain this?  

Thank you.

```
terminate called after throwing an instance of 'Thyra::CatastrophicSolveFailure'
  what():  /Trilinos/packages/stratimikos/adapters/belos/src/Thyra_BelosLinearOpWithSolve_def.hpp:700:
Throw number = 2
Throw test that evaluated to true: true
/Trilinos/packages/belos/src/BelosStatusTestImpResNorm.hpp:635:
Throw number = 1
Throw test that evaluated to true: true
Belos::StatusTestImpResNorm::checkStatus(): One or more of the current implicit residual norms is NaN.
```

**Comment by cgcgcg** [comment]
@trilinos/amesos2

**Comment by iyamazaki** [comment]
Thank you, @LeaSassmannshausen. Is this happening for a particular matrix? If so, can you share the matrix. I've been using Amesos2's PardisoMKL interface and have not noticed any issue.

**Comment by LeaSassmannshausen** [comment]
Thank you for your quick reply @iyamazaki . What exactly do you mean? I would have to check for the specific data type. 

ps: I updated my question above. I tend to always receive the CastrophicSolveFailure.

**Comment by LeaSassmannshausen** [comment]
@iyamazaki I just found a setting in my parameter list that caused the solver to produce a wrong solution. I assume the parameter setting has changed in the past month. I athink it has nothing to do with the solver itself but with solver-preconditioner settings. Thank you.
