### ISSUE TITLE
PyTrilinos: Shared libraries build issue

### ISSUE THREAD

**Issue by s-kanaev** [trilinos/Trilinos#11406]
I'm trying to build Trilinos for use with Xyce.
My installation is Fedora 34. openmpi and openmpi-devel packages of version 4.1.0.

The script I use for configuring Trilinos is:

```
# Flags was provided by Xyce build manual
FLAGS="-O3 -fPIC"
OPENMPI_DIR='/usr/lib64/openmpi'

cmake \
    -DBUILD_SHARED_LIBS=ON \
    -DTPL_ENABLE_MPI=ON \
    -DTrilinos_ENABLE_ALL_PACKAGES=ON \
    -DTrilinos_EXTRA_LINK_FLAGS:STRING="-L/usr/lib64 -lhdf5 " \
    -DMPI_C_COMPILER="$OPENMPI_DIR/bin/mpicc" \
    -DMPI_CXX_COMPILER="$OPENMPI_DIR/bin/mpic++" \
    -DMPI_Fortran_COMPILER="$OPENMPI_DIR/bin/mpif77" \
    -DCMAKE_CXX_FLAGS="$FLAGS" \
    -DCMAKE_C_FLAGS="$FLAGS" \
    -DCMAKE_Fortran_FLAGS="$FLAGS" \
    -DTrilinos_ENABLE_CXX11=ON \
    -DCMAKE_INSTALL_PREFIX=~/Apps/XyceLibs/Parallel \
    ..
```

The problem arises when `build/packages/PyTrilinos/src/gen_teuchos_rcp.py` script is run:
```
Traceback (most recent call last):
  File "/home/sergei/projects/Trilinos/build/packages/PyTrilinos/src/gen_teuchos_rcp.py", line 659, in <module>
    main()
  File "/home/sergei/projects/Trilinos/build/packages/PyTrilinos/src/gen_teuchos_rcp.py", line 557, in main
    print("#define MPI_VERSION %s" % get_mpi_version())
  File "/home/sergei/projects/Trilinos/build/packages/PyTrilinos/src/gen_teuchos_rcp.py", line 58, in get_mpi_version
    for line in open(header, 'r').readlines():
FileNotFoundError: [Errno 2] No such file or directory: 'include/mpi.h'
```

Taking a look at appropriate lines of `gen_teuchos_rcp.py` won't let mitigate the issue as the include files for `openmpi-devel` package are a bit distant from `/usr/lib64/openmpi`. The include files are located at `/usr/include/openmpi-x86_64/mpi.h` and the logic in the python script won't let them be found:

```
 46 # Find the MPI base directory                                                   
 47 MPI_BASE_DIR   = ""                                                             
 48 if WITH_MPI:                                                                    
 49     if MPI_BASE_DIR == "":                                                      
 50         MPI_BIN_DIR  = os.path.split("/usr/lib64/openmpi/bin/mpic++")[0]        
 51         MPI_BASE_DIR = os.path.split(MPI_BIN_DIR)[0]                            
 52                                                                                 
 53 ################################################################################
 54                                                                                 
 55 def get_mpi_version():                                                          
 56     header = os.path.join(MPI_BASE_DIR, "include/mpi.h")                        
 57     version = ""                                                                
 58     for line in open(header, 'r').readlines():                                  
 59         if "MPI_VERSION" in line:                                               
 60             version = line.split()[2]                                           
 61             break                                                               
 62     return version                                                              
```

Are there any ways to mitigate this sort of issue? Have I done something wrong at the configure step?

**Comment by cgcgcg** [comment]
I doubt that PyTrilinos is required by Xyce.
What did you set the CMake variable `MPI_BASE_DIR` to?
https://github.com/trilinos/Trilinos/blob/27a6ea008c3ccc915698df88b735c59309a382f2/packages/PyTrilinos/src/gen_teuchos_rcp.py.in#L47

**Comment by s-kanaev** [comment]
Even though, PyTrilinos isn't required for Xyce I guess I could try the package out to see if it's applicable for my pet-project :-)

I didn't set `MPI_BASE_DIR` in this particular case. Though, even when I set it it won't help. I guess it's natural to set it to `/usr/lib64/openmpi` as `bin` and `lib` directories are located there. Though, it doesn't contain `include` directory. The include files for `openmpi-devel` are located in `/usr/include/openmpi-x86_64`.
I guess the best solution here is to add a symlink in `/usr/lib64/openmpi` and set `MPI_BASE_DIR`. Though, is there any CMAKE-only solution?

**Comment by cgcgcg** [comment]
Indeed, I don't get how that logic would work in that case. Maybe @pyt-viper can help?

**Comment by pyt-viper** [comment]
It helps to know that `gen_teuchos_rcp.py` is a generated file.  The source file in the PyTrilinos directory is `src/gen_teuchos_rcp.py.in`.  In there, you can see Cmake variables that get expanded in `gen_teuchos_rcp.py`.  Feel free to fix the logic in the source file to make it behave properly for the case where the `include` directory is in a different parent directory from the `bin` directory.
