### ISSUE TITLE
Panzer: Nodal boundary condition

### ISSUE THREAD

**Issue by delcmo** [trilinos/Trilinos#11414]
Hello,

I am implementing an incompressible Navier-Stockes solver and would need to pin the pressure at a given node that would preferably be on a boundary. This would be equivalent to having a nodal boundary. This question is addressed to @rppawlo.

Is that something Panzer can handle? And if it can, how should I proceed?

Thanks,

Marco

**Comment by rppawlo** [comment]
Hi @delcmo ! The pinning code is not in panzer, but is available in Drekar. You could copy that. It's a little complex due to having to augment the linear system. Will send info in an email shortly.

**Comment by delcmo** [comment]
@rppawlo, thanks for your email. I will look at the logic in Drekar.

Marco
