### ISSUE TITLE
Trilinos build error due to MueLu on Ride with CUDA KokkosNode

### ISSUE THREAD

**Issue by ikalash** [trilinos/Trilinos#1141]
@jhux2 @tawiesn : I am submitting the issue I emailed you about. 

For a week or so, I have been having an issue with my nightly build of Trilinos on Ride with a CUDA KokkosNode.  The code fails to build, due to MueLu.  You will find the error here: http://cdash.sandia.gov/CDash-2-3-0/viewBuildError.php?buildid=49900 .  This seems to happen with develop as well as master branch of Trilinos.

**Comment by ibaned** [comment]
@trilinos/muelu

**Comment by tawiesn** [comment]
@ikalash Sorry, it seems i have no access to cdash.sandia.gov. Can you post the build error here or is it the same problem as [here](http://testing.sandia.gov/cdash/viewBuildError.php?buildid=2794952)? We are quite clean on the (official) dashboard now...

**Comment by ikalash** [comment]
@tawiesn .  Right, this site is on the SRN, which is why you cannot access it.  Here is the compilation error: 

 	https://github.com/gahansen/Albany/blob/master/repos/Trilinos/packages/muelu/src/Smoothers/MueLu_DirectSolver_def.hpp
Build Log Line 	950614
Error 	

/.../repos/Trilinos/packages/stk/stk_topology/stk_topology/topology_type.tcc(246): here
            instantiation of "void stk::topology::topology_type::permutation_nodes(const NodeArray &, unsigned int, NodeOutputIterator) [with Topology=stk::topology::WEDGE_15, NodeArray=stk::mesh::EntityVector, NodeOutputIterator=__gnu_cxx::__normal_iterator>>]" 
/.../repos/Trilinos/packages/stk/stk_topology/stk_topology/topology.tcc(159): here
            instantiation of "void stk::topology_detail::permutation_nodes_impl::operator()(Topology) const [with NodeArray=stk::mesh::EntityVector, NodeOutputIterator=__gnu_cxx::__normal_iterator>>, Topology=stk::topology::topology_type]" 
/.../repos/Trilinos/packages/stk/stk_topology/stk_topology/apply_functor.tcc(171): here
            instantiation of "stk::topology::apply_functor::result_type stk::topology::apply_functor::operator()(stk::topology::topology_t) [with Functor=stk::topology_detail::permutation_nodes_impl>>>]" 
/.../repos/Trilinos/packages/stk/stk_topology/stk_topology/topology.tcc(159): here
            instantiation of "void stk::topology::permutation_nodes(const NodeArray &, unsigned int, NodeOutputIterator) const [with NodeArray=stk::mesh::EntityVector, NodeOutputIterator=__gnu_cxx::__normal_iterator>>]" 
/.../repos/Trilinos/packages/stk/stk_mesh/stk_mesh/baseImpl/elementGraph/ElemElemGraphImpl.cpp(329): here

/.../repos/Trilinos/packages/muelu/src/Smoothers/MueLu_DirectSolver_def.hpp(82): error: object of abstract class type "MueLu::Amesos2Smoother" is not allowed:

            pure virtual function "MueLu::SmootherBase::getNodeSmootherComplexity [with Scalar=double, LocalOrdinal=int, GlobalOrdinal=int, Node=Xpetra::EpetraNode]" has no overrider
          detected during instantiation of "MueLu::DirectSolver::DirectSolver(const std::__cxx11::string &, const Teuchos::ParameterList &) [with Scalar=double, LocalOrdinal=int, GlobalOrdinal=int, Node=Xpetra::EpetraNode]" 
/.../repos/Trilinos/packages/muelu/src/Utils/MueLu_ETI_4arg.hpp(35): here

/.../repos/Trilinos/packages/xpetra/sup/Utils/Xpetra_MatrixMatrix.hpp(1713): warning: statement is unreachable

/home/projects/pwr8-rhel73-lsf/boost/1.60.0/openmpi/1.10.4/gcc/5.4.0/cuda/8.0.44/include/boost/mpl/for_each.hpp(78): warning: calling a __host__ function from a __host__ __device__ function is not allowed
          detected during:
            instantiation of "void boost::mpl::aux::for_each_impl::execute(Iterator *, LastIterator *, TransformFunc *, F) [with Iterator=boost::mpl::v_iter, 6L>, LastIterator=boost::mpl::v_iter, 15L>, TransformFunc=boost::mpl::identity, F=stk::topology_detail::fill_node_container>>>]" 
(82): here

I think it is different than the CDash site you pointed me to.  I have put a log file with all the output if you would like to see it on software-login: 

/home/ikalash/forTobias/nightly_log_rideTrilinos.txt

**Comment by tawiesn** [comment]
@ikalash Thanks. I'll take a look. Should not be too hard to fix.

**Comment by ikalash** [comment]
Thanks @tawiesn !

**Comment by tawiesn** [comment]
@ikalash Hmm. I checked the code and the "missing" routine should be there. What is the current version of the develop branch you use? What node types and global ordinal types do you have enabled in your Trilinos configuration?

**Comment by tawiesn** [comment]
@ikalash. Maybe the easiest is if you send me the configuration file for Trilinos. I should be able to reproduce the problem then.

**Comment by ikalash** [comment]
@tawiesn : It is actually master branch, not develop I just realized.  I forgot that I have Jenkins pull Trilinos so my script that tells it to build develop is not being sourced.  Is it a known problem to have this compilation error in the master branch of Trilinos?  I can try the job with develop Trilinos and let you know if that works.

**Comment by tawiesn** [comment]
Please try the develop branch. I know, that there were some problems like that and i don't know when master has been update last time.

**Comment by ikalash** [comment]
Trying it now.  I'll let you know when the build completes.

**Comment by ikalash** [comment]
@tawiesn : Just tried the develop branch.  There is still a build error, it looks like having to do with MueLu_ShiftedLaplacian_def.hpp: 

 	https://github.com/gahansen/Albany/blob/master/repos/Trilinos/packages/muelu/src/../adapters/tpetra/MueLu_ShiftedLaplacian_def.hpp
Build Log Line 	989724
Error 	

/.../repos/Trilinos/packages/stk/stk_topology/stk_topology/topology_type.tcc(319): here
            instantiation of "std::pair<__nv_bool, unsigned int> stk::topology::topology_type::equivalent(const NodeArrayA &, const NodeArrayB &) [with Topology=stk::topology::HEX_20, NodeArrayA=const stk::mesh::Entity *, NodeArrayB=std::vector>]" 
/.../repos/Trilinos/packages/stk/stk_topology/stk_topology/topology.tcc(194): here
            instantiation of "stk::topology_detail::equivalent_impl::result_type stk::topology_detail::equivalent_impl::operator()(Topology) const [with NodeArrayA=const stk::mesh::Entity *, NodeArrayB=std::vector>, Topology=stk::topology::topology_type]" 
/.../repos/Trilinos/packages/stk/stk_topology/stk_topology/apply_functor.tcc(174): here
            instantiation of "stk::topology::apply_functor::result_type stk::topology::apply_functor::operator()(stk::topology::topology_t) [with Functor=stk::topology_detail::equivalent_impl>>]" 
/.../repos/Trilinos/packages/stk/stk_topology/stk_topology/topology.tcc(287): here
            instantiation of "std::pair<__nv_bool, unsigned int> stk::topology::equivalent(const NodeArrayA &, const NodeArrayB &) const [with NodeArrayA=const stk::mesh::Entity *, NodeArrayB=std::vector>]" 
/.../repos/Trilinos/packages/stk/stk_mesh/stk_mesh/baseImpl/MeshImplUtils.cpp(277): here

/.../repos/Trilinos/packages/muelu/src/../adapters/tpetra/MueLu_ShiftedLaplacian_def.hpp(339): error: object of abstract class type "MueLu::Ifpack2Smoother" is not allowed:

            pure virtual function "MueLu::SmootherBase::getNodeSmootherComplexity [with Scalar=double, LocalOrdinal=int, GlobalOrdinal=int, Node=Xpetra::EpetraNode]" has no overrider
          detected during instantiation of "void MueLu::ShiftedLaplacian::initialize() [with Scalar=double, LocalOrdinal=int, GlobalOrdinal=int, Node=EpetraNode]" 
/.../repos/Trilinos/packages/muelu/src/Utils/MueLu_ETI_4arg.hpp(35): here

/home/projects/pwr8-rhel73-lsf/boost/1.60.0/openmpi/1.10.4/gcc/5.4.0/cuda/8.0.44/include/boost/mpl/for_each.hpp(78): warning: calling a __host__ function from a __host__ __device__ function is not allowed
          detected during:
            instantiation of "void boost::mpl::aux::for_each_impl::execute(Iterator *, LastIterator *, TransformFunc *, F) [with Iterator=boost::mpl::v_iter, 4L>, LastIterator=boost::mpl::v_iter, 20L>, TransformFunc=boost::mpl::identity, F=stk::topology_detail::fill_node_container]" 
(82): here
            instantiation of "void boost::mpl::aux::for_each_impl::execute(Iterator *, LastIterator *, TransformFunc *, F) [with Iterator=boost::mpl::v_iter, 3L>, LastIterator=boost::mpl::v_iter, 20L>, TransformFunc=boost::mpl::identity, F=stk::topology_detail::fill_node_container]" 
(82): here

You can find more output in /home/ikalash/forTobias/nightly_log_rideTrilinos.txt .  Here is the tag from my Trilinos (develop) branch: c78e19ed1b9197188c845adde6fd7d9107ac0adb .

Irina

**Comment by tawiesn** [comment]
@ikalash Thanks Irina. Looks like the same type of problem but in a different class (Ifpack2Smoother instead of Amesos2Smoother). And in fact, the getNodeSmootherComplexity routine was missing in one of the specializations of the Ifpack2Smoother.
Checkin script is running. I hope i get it to pass all tests such that we should see the fix in the develop branch tomorrow.

**Comment by ikalash** [comment]
@tawiesn .  That's great.  My job is schedule to run at 8PM MST tonight.  I'll check on it tonight and tomorrow (if tonight's fails) and let you know the outcome.

**Comment by ikalash** [comment]
@tawiesn : everything was good once again in my ride nightly tests.  I will close the issue.  Thanks for fixing this!
