### ISSUE TITLE
Trilinos: Compilation with Visual Studio

### ISSUE THREAD

**Issue by vryy** [trilinos/Trilinos#11431]
Hello

I'm working in porting an in-house code to compile on Windows. This code uses Trilinos as the linear algebra backend. After some times tweaking I could get Trilinos to compile (with Visual Studio) and it works. I'm happy to expose this work to the repo but is not clear about the process. What is your suggestion?

**Comment by sebrowne** [comment]
As per the new statement in our INTALL document:

```
Trilinos tests with all Compiler/MPI combinations listed at:

  https://github.com/trilinos/Trilinos/wiki/Pull-Request-Testing-Interface

Compilers/MPIs that are not part of our automated process will not receive support.
We are happy to accept Pull Requests enhancing support for other compilers/MPIs as
needed by our customers, with the understanding that said configurations cannot be
guaranteed to work.
```

Basically, feel free to open a pull request with the changes and we are open to accepting them through the normal approval process, but we cannot guarantee that they will continue to work because we do not test with Visual Studio.
