### ISSUE TITLE
Intrepid2/SEACAS:  Build errors for new nightly memory leak testing 

### ISSUE THREAD

**Issue by srbdev** [trilinos/Trilinos#11449]
## Bug Report
@trilinos/intrepid2 
@trilinos/seacas 

### Description
There are build errors for both the Intrepid2 and SEACAS packages for the new `rhel7_sems-clang-11.0.1-openmpi-1.10.1-serial_release-debug_shared_no-kokkos-arch_asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_all` build. This nightly build is being put into place for memory leak testing using Clang ASAN. It is currently ran on the following fork https://github.com/srbdev/Trilinos and branch `TRILFRAME-100-memory-leak-testing-build`.

See the [CDash link](https://trilinos-cdash.sandia.gov/index.php?project=Trilinos&display=project&filtercount=3&showfilters=1&filtercombine=and&field1=site&compare1=61&value1=ascic113&field2=buildname&compare2=61&value2=PR-__UNKNOWN__-test-rhel7_sems-clang-11.0.1-openmpi-1.10.1-serial_release-debug_shared_no-kokkos-arch_asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_all-1&field3=buildstamp&compare3=61&value3=20230109-2109-Experimental) for additional details.

**Comment by gsjaardema** [comment]
The seacas errors look like there is a mismatch in parallel vs serial compilation / linking at some point.

**Comment by gsjaardema** [comment]
It looks like perhaps the incorrect netCDF and HDF5 libraries are being used -- they are parallel versions.  For example:
```
-- TPL_Netcdf_PARALLEL is True
```
But `TPL_ENABLE_MPI` is off...

**Comment by srbdev** [comment]
Ah thank you for pointing that out. I'll double-check the build configuration and test again.

**Comment by CamelliaDPG** [comment]
@srbdev from the errors it sounds like the compiler is choking on the complexity of some Intrepid2 code blocks.  (And maybe the address sanitization stuff makes things more complex?)  Is there a do-configure somewhere that I can look at?  I can try to reproduce on my local machine.

**Comment by srbdev** [comment]
@CamelliaDPG fyi, the base configuration for the build didn't exist so the build itself was misconfigured so I'm testing that out now. If the issues persists for Intrepid2, I'll attach the instructions to replicate here.

**Comment by CamelliaDPG** [comment]
@srbdev Sounds good; I'll keep an eye out.
