### ISSUE TITLE
Krino:  Replace "Trilinos" with "${PROJECT_NAME}" in cmake file

### ISSUE THREAD

**Issue by glhenni** [trilinos/Trilinos#11453]
@trilinos/krino

Krino has a hard-coded "Trilinos" in `krino/CMakeLists.txt` that needs to be changed to "${PROJECT_NAME}" similar to #11366 

```diff
--- a/packages/krino/CMakeLists.txt
+++ b/packages/krino/CMakeLists.txt
@@ -5,7 +5,7 @@ TRIBITS_PACKAGE(Krino)
 TRIBITS_ADD_DEBUG_OPTION()
 TRIBITS_ADD_SHOW_DEPRECATED_WARNINGS_OPTION()
 
-if (${Trilinos_ENABLE_Krino})
+if (${${PROJECT_NAME}_ENABLE_Krino})
   add_subdirectory(krino)
   add_subdirectory(delete_small_elements)
 endif()
```

**Comment by jhux2** [comment]
@drnobleabq

**Comment by jhux2** [comment]
@glhenni If you can submit this as a patch, I'll be happy to approve.

**Comment by glhenni** [comment]
> @glhenni If you can submit this as a patch, I'll be happy to approve.

@jhux2 unfortunately, or maybe thankfully 😉, I am NOT a trilinos developer and have always relied on the kindness of others to apply my patches and create PRs. I only have a **very** vague idea of how that process works.
