### ISSUE TITLE
Amesos2:  Row permutation in SuperLU_dist

### ISSUE THREAD

**Issue by maxfirmbach** [trilinos/Trilinos#11469]
Hello,

In the scope of switching our in-house multi-physics code from `Epetra` to `Tpetra` and thus from `Amesos` to `Amesos2`, we came across a problem in the `Amesos2` adapter of `SuperLU_dist`. In the source code it states, that row permutations are currently not available/allowed, due to a sequential bottleneck in the implementation.

Some parts of our code are depending on this feature, which is available in `Amesos`. For us it would be really helpful and in some parts also necessary to add row permutation as an user input (leaving the current hard coded option as default) to the `SuperLU_dist` interface in `Amesos2`.

A colleague and myself would contribute this feature.
Whats you're opinion on this? Was this never used by someone?

Might be interesting for: @mayrmt @vryy

Best regards,
Max

**Comment by mayrmt** [comment]
@trilinos/amesos2 @srajama1

**Comment by cgcgcg** [comment]
@iyamazaki

**Comment by iyamazaki** [comment]
Thank you, @maxfirmbach. I do not see how a user-provided row perm causes an issue (I think that comment refers to options like computing max-weighted matching). I am away this week, but can take a look next week. Or, if you could contributes, that will be also great!

**Comment by iyamazaki** [comment]
I am just not sure if `symbolicFactorization` of `Amesos2` needs to be changed with an option like `MY_PERMR`.

**Comment by maxfirmbach** [comment]
Maybe I wrote it a bit misleading. We are not using our own row permutation method (as indicated by `MY_PERMR` if I'm not mistaken), but actually we used the default row permutation method in `Amesos`, which is `LargeDiag` I think. I guess with this we intentionally also run into the bottleneck mentioned in the comment, but otherwise some of our linear systems are not solveable with `SuperLU_dist`.

**Comment by iyamazaki** [comment]
Oh, I see. I misunderstood. If you can make an `Amesos2` contribution with that option, that will be great!! Otherwise, I'll need to wait till next week to take a closer look (like how to form the global matrix in `Amesos2`).

**Comment by vryy** [comment]
@iyamazaki Sorry for a bit off topic but i think Amesos2_MUMPS interface is also incomplete, since it does not compile and some code branch still rely on deprecated Tpetra stuff. It would be great if you can also look into it.

**Comment by maxfirmbach** [comment]
The changes are merged, thus closing this issue :rocket:.
