### ISSUE TITLE
STK (?): Build errors

### ISSUE THREAD

**Issue by cgcgcg** [trilinos/Trilinos#11463]
## Bug Report
Looking at the dashboard
https://testing.sandia.gov/cdash/index.php?project=Trilinos
it seems that something in STK broke a lot of nightly builds. Could this be related to #11461? 

@alanw0

**Comment by alanw0** [comment]
@cgcgcg we were under the impression that c++17 is legal now. Is that not the case?

**Comment by cgcgcg** [comment]
#11357 has not yet merged, but it seems like it should go in pretty soon.

**Comment by ikalash** [comment]
I think we are seeing this issue in some Albany builds: https://sems-cdash-son.sandia.gov/cdash/viewBuildError.php?buildid=44055 .  Commenting so that I get notifications on the fix.

**Comment by cgcgcg** [comment]
#11357 merged, so hopefully this is fixed.

**Comment by cgcgcg** [comment]
The builds on https://testing.sandia.gov/cdash/index.php?project=Trilinos are still failing, but not due to STK anymore.
