### ISSUE TITLE
Adding TPL to Trilinos Installation

### ISSUE THREAD

**Issue by Jacob328** [trilinos/Trilinos#11468]
Hi,

I am attempting to build the Peridigm software (https://github.com/peridigm/peridigm) on my university's computer cluster. Peridigm is dependent on Trilinos which is fortunately already installed on the university's cluster (trilinos-12.18.1/gcc-9.3.0), but when I attempt to configure the Peridigm software, I get a fatal error stating that the Trilinos Netcdf TPL is not found.

My questions is... is there any way to add Netcdf to an existing Trilinos installation, or is the only solution to create a brand new Trilinos installation with the Netcdf package enabled?

**Comment by cgcgcg** [comment]
No, you'll have to build your own Trilinos or convince the admin of your cluster to rebuilt Trilinos with Netcdf enabled.

**Comment by Jacob328** [comment]
Thanks @cgcgcg. 
Just wanted to make sure I wasn't doing lots of extra work for nothing!
