### ISSUE TITLE
Question: Trilinos dashboard coverage of CUDA 11

### ISSUE THREAD

**Issue by jhux2** [trilinos/Trilinos#11472]
@trilinos/framework @bartlettroscoe Is there coverage on the Trilinos dashboard for CUDA 11?  There is an experimental build on Geminga using CUDA 11.4.2, but the other builds are all CUDA 10, which are failing (possibly due to the switchover to c++17).

Here is the dashboard link I used:  https://testing.sandia.gov/cdash/index.php?project=Trilinos&filtercount=1&showfilters=1&field1=buildname&compare1=63&value1=cuda.

Am I just looking in the wrong place?

**Comment by bartlettroscoe** [comment]
@sebrowne

**Comment by sebrowne** [comment]
One of the PR/MM builds uses CUDA11.4.2/GCC10.1.0/OpenMPI4.0.5

**Comment by jhux2** [comment]
Alright, thanks.
