### ISSUE TITLE
ROL: tautological overlap comparison warning that looks like a bug

### ISSUE THREAD

**Issue by japlews** [trilinos/Trilinos#11470]
https://github.com/trilinos/Trilinos/blob/15279777559d86713af40b5179401dbd3b141f29/packages/rol/src/sol/function/randvarfunctional/ROL_StochasticObjective.hpp#L181

@trilinos/rol

I am seeing this warning in Sierra clang-14 builds. Just reporting this because it seems like a logic error (`&&` instead of `||`?).

**Comment by dridzal** [comment]
@japlews , thanks!  @dpkouri , does this look like a bug?

**Comment by japlews** [comment]
Hey all, just looking through my active Github issues and I reallized this one is still open. If the fix has been merged with Trilinos, I think we can close this one. Thanks!

**Comment by ccober6** [comment]
Tagging @dridzal and @dpkouri as I did not recieve an edited version with their mentions.

**Comment by GrahamBenHarper** [comment]
It looks like this was covered in a ROL sync, so it's safe to close as completed.

See https://github.com/trilinos/Trilinos/blob/727733ccb61350da468e3cd8fd5daa6bc235d560/packages/rol/src/sol/function/randvarfunctional/ROL_StochasticObjective.hpp#L181
