### ISSUE TITLE
Remove Xpetra warnings when compiling for CUDA

### ISSUE THREAD

**Issue by jhux2** [trilinos/Trilinos#1148]
We can use the macro ```TEUCHOS_NONREACHABLE_RETURN(RETURN_VAL)``` as in issue #1140 to get rid of warnings like

```
Trilinos_apollo_gcc_4.8.4_cuda_7.5.18/MPI_RELEASE_DEV_DownStream_ETI_SERIAL-ON_OPENMP-OFF_PTHREAD-OFF_CUDA-ON_COMPLEX-OFF/Trilinos/packages/xpetra/src/Map/Xpetra_EpetraMap.hpp(655): warning: statement is unreachable
```

**Comment by jhux2** [comment]
@trilinos/xpetra

**Comment by jhux2** [comment]
Examples [here](http://testing.sandia.gov/cdash/viewBuildError.php?type=1&buildid=2791284).

**Comment by aprokop** [comment]
So, does it work for all compilers? Different compilers produce different warnings?

**Comment by jhux2** [comment]
> So, does it work for all compilers? Different compilers produce different warnings?

I think this is just meant to address the particular CUDA warning ```statement is unreachable```.

**Comment by jhux2** [comment]
Closing, as these warnings have been addressed.
