### ISSUE TITLE
Framework:  can't connect to cdash dashboard

### ISSUE THREAD

**Issue by jhux2** [trilinos/Trilinos#11496]
## Bug Report
@trilinos/framework 

### Description
I can't load the dashboard at https://testing.sandia.gov/cdash/index.php?project=Trilinos.  I get the error "503 | CDash cannot connect to the database."

**Comment by sebrowne** [comment]
I'll put in a ticket with the corporate computing people, looks like the server is experiencing some issues

**Comment by sebrowne** [comment]
@jhux2 it should be fixed now.  It must have gone down on 01/20 though, because that's the last set of submissions.  Hopefully the ones from tonight show up as expected.  Good to close?

**Comment by jhux2** [comment]
@sebrowne Yes, it's reachable now.  Thanks for the quick response/fix!
