### ISSUE TITLE
Seacas:  undefined reference when using Ioss::valid_decomp_methods

### ISSUE THREAD

**Issue by sphamil** [trilinos/Trilinos#11490]
@trilinos/seacas @trilinos/stk

We have a project that uses Trilinos as a TPL, including STK for meshing. During mesh loading, we call the `stk::io::StkMeshIoBroker::property_add` method with an argument of `Ioss::Property("DECOMPOSITION_METHOD", decomp)`, where `decomp` is populated from the candidates in `Ioss::valid_decomp_methods()` (from `packages/seacas/libraries/ioss/src/Ioss_Decomposition.h`). This worked correctly until commits of the Trilinos `develop` branch approximately a month ago (possibly slightly longer, unsure of exact timeframe), at which point we get a link error when building our executable:

`undefined reference to 'Ioss::valid_decomp_methods()'`

This appears to be due to these lines in `packages/seacas/libraries/ioss/CMakeLists.txt`:
```
set(CMAKE_C_VISIBILITY_PRESET hidden)
set(CMAKE_CXX_VISIBILITY_PRESET hidden)

set(CMAKE_VISIBILITY_INLINES_HIDDEN ON)
```
I'm not sure if this is a bug or intended behavior. Is there a reason that `Ioss::valid_decomp_methods` would _not_ be exported and therefore not part of a public API? It seems like our usage should be acceptable.

**Comment by alanw0** [comment]
Hopefully Greg sees this due to the 'trilinos/seacas' tag, but also tagging @gsjaardema just in case.

**Comment by gsjaardema** [comment]
Thanks for letting me know.  Will fix today hopefully.

**Comment by gsjaardema** [comment]
Can you see if the recent #11492 commit fixes this issue. I added an export to the function, but it might be that the CMake setting is overriding that and needs to be removed.  It was added for some people using SEACAS on windows, so we might be able to make that setting for windows only if #11492 doesn't fix the issue.

**Comment by gsjaardema** [comment]
Thanks for letting me know.
