### ISSUE TITLE
Panzer: the local dof ordering in Intrepid2FieldPattern does not reflect CellTopology. Is this wanted/desired?

### ISSUE THREAD

**Issue by bartgol** [trilinos/Trilinos#11499]
Say, I have a Quadrilateral_4 topology, and HGRAD C1 intrepid basis on it. I am printing the id (wrt to cell numeration) of nodes on each edge, both from the point of view of the shards cell topo, as well as using DOFManager::getGIDFieldOffsets_closure (which, for a single field, is the same as calling the `Intrepid2FieldPattern::getSubcellClosureIndices`). I get different results:

```
shards
 side 0: 0 1
 side 1: 1 2
 side 2: 2 3
 side 3: 3 0
panzer
 side 0: 0 1
 side 1: 1 2
 side 2: 2 3
 side 3: 0 3
```

From what I understand, this is due to the fact that `Intrepid2FieldPattern::buildSubcellClosure` stores the "geometric" closure in a std::set, so the closure ends up being ordered by subcellDim first, and by subcellOrdinal second (the latter creating a conflict with shards numeration). ~~In 3D, there's also the issue that the method is recursive, which causes all dofs on the first edge's closure to be added first, which means you get some node-based DOFs _after_ some edge-based DOFs.~~

Is this behavior of Intrepid2FieldPattern desired? I would have expected that, for a general FE basis, one gets
- ~~all nodal dofs before all edge dofs, which come before all face dofs, which come before all volume dofs.~~ Edit: nvm, this is already true, since the closure is ordered by subcellDim first.
- if, say, shards says cell node 3 comes before cell node 0 on a subcell, then the DOFManager subell offsets should reflect this.

**Comment by bartgol** [comment]
Note: small modifications to `Intrepid2FieldPattern::buildSubcellClosure` allows to ensure that order of entities (of same subdim) in the closure matches the order that shards says. So fixing this (if fixing is desired at all) would be very quick.

**Comment by jhux2** [comment]
@trilinos/panzer

**Comment by bartgol** [comment]
Also, notice that `Intrepid2FieldPattern::getSubcellIndices(dim,ord)` seems to be doing already the right thing. The issue I notice seems to stem from how the `_closure` method orders the individual subcell indices contributions.

**Comment by rppawlo** [comment]
@bartgol - thanks for finding this. We probably should be consistent where possible with shards. Can you put up a PR? I'd like to test this against some of the apps before merging though. I don't think it should be an issue, but want to be sure.

**Comment by bartgol** [comment]
Yes, I can work on a PR, and a test.

**Comment by bartgol** [comment]
@rppawlo  I have a branch, but I can't run the test b/c I keep getting this error:
```
./PanzerDofMgr_tIntrepidFieldPattern.exe: symbol lookup error: ./PanzerDofMgr_tIntrepidFieldPattern.exe: undefined symbol: _ZN6Kokkos4Impl22SharedAllocationRecordINS_9HostSpaceEvE13s_root_recordE
```
This is a clean build, so there should be no leftover libs/headers from old versions. Does this error ring any bell?

**Comment by rppawlo** [comment]
@bartgol - I have not seen that one before.

**Comment by bartgol** [comment]
Uhm, the "fix" I tried only works for C1 elements, since Intrepid'd ordering of edges is different than shards's ordering. The `subcellIndices_` in `Intrepid2FieldPattern` would follow intrepid's convention, so even if the geometric subcell closure reflects shards ordering, the indices will get mixed up with intrepid's ordering.

I'm actually a bit puzzled by this. If the user asks for the closure indices on subDim=1, subOrd=6 (an edge of an hexa), what should he expect? the 6th edge in shards terms, or the 6th edge in intrepid terms?

**Comment by mperego** [comment]
Intrepid2 relies on Shards topology, so it's not correct to say that Intrepid2 ordering of edges is different than the shards one.
However, the way DOFs are numbered in Intrepid2 does not necessarily reflect shards ordering, but you can _always_ get the DOFs on any Shards entity (point, edge, face) by using `getDoFOrdinal()`.

**Comment by bartgol** [comment]
Yeah, that's more accurate. It's just confusing, I guess. Thanks!
