### ISSUE TITLE
Add an option for switching between storing block inverse or block factors storage in block Jacobi and Gauss-Seidel

### ISSUE THREAD

**Issue by aprokop** [trilinos/Trilinos#115]
@trilinos/ifpack2 @mhoemmen 

 Ifpack2 now stores and applies the inverse of the matrix's block diagonal explicitly (#96). Theoretically, this is a tradeoff. If block size is large enough, you can get better performance out of linear solves rather than full inversion when doing a limited number of iterations. So a user should be able to decide the appropriate approach for it.

**Comment by mhoemmen** [comment]
> On Jan 29, 2016, at 11:00 PM, Andrey Prokopenko <notifications@github.com> wrote:
> Theoretically, this is a tradeoff. If block size is large enough, you can get better performance out of linear solves rather than full inversion when doing a limited number of iterations. 

Thanks for pointing this out and filing the issue!

Note that GETRI immediately follows GETRF in the setup code, so the block should still be in L1 (as long as it fits).  Furthermore, storing blocks explicitly gives us the freedom to use different algorithms for block inversion.  For example, we could use approximate inverse via Newton iteration for cheaper setup, or extended-precision temporaries for more accuracy.
