### ISSUE TITLE
Tpetra: Do not use deprecated `KOKKOS_ACTIVE_EXECUTION_MEMORY_SPACE_*` macros

### ISSUE THREAD

**Issue by dalg24** [trilinos/Trilinos#11510]
## Bug Report
@csiefer2
@ndellingwood 

Compatibility with Kokkos

### Description
See kokkos/kokkos#4668 or (better) the [release 3.6 briefing slides](https://github.com/kokkos/kokkos-tutorials/blob/main/Other/ReleaseBriefings/release-36.pdf) p45-50

Please make sure you read the warning on the last page.  Don't just go and replace with `KOKKOS_IF_ON_{HOST,DEVICE}`, consider whether you can deduce the execution space and specialize or use `if constexpr`.

These are not portable and we are about to remove them.

```
packages/tpetra/core/src/Tpetra_BlockCrsMatrix_def.hpp:427:#if defined( KOKKOS_ACTIVE_EXECUTION_MEMORY_SPACE_HOST )

**Comment by ndellingwood** [comment]
@trilinos/tpetra

**Comment by csiefer2** [comment]
@ndellingwood Can we constexpr check if execution space is HostSpace inside a Kokkos parallel region?

**Comment by ndellingwood** [comment]
> Can we constexpr check if execution space is HostSpace inside a Kokkos parallel region?

@csiefer2 I'm not sure, I haven't tried this. It seems like a reasonable thing to try, but I don't have enough experience using `if constepxr` in place of sfinae patterns to say for sure
