### ISSUE TITLE
Can I set the C++ standard?

### ISSUE THREAD

**Issue by VictorEijkhout** [trilinos/Trilinos#11512]
1. I see no mention of the C++ standard on the installation instructions.

2. But you definition insert a standard:

```
Building CXX object commonTools/gtest/CMakeFiles/gtest.dir/gtest/gtest-all.cc.o
cd /work2/00434/eijkhout/trilinos/build-13-4-1-clx-oneapi-impi/commonTools/gtest && /scratch1/p\rojects/compilers/oneapi_2022.3.0/mpi/latest/bin/mpicxx -DGTEST_HAS_PTHREAD=0 -Dgtest_EXPORTS -\I/work2/00434/eijkhout/trilinos/build-13-4-1-clx-oneapi-impi -I/work2/00434/eijkhout/trilinos/t\rilinos-13-4-1/commonTools/gtest -O2  -DMPICH_SKIP_MPICXX -O3 -DNDEBUG -fPIC -std=c++14 -MD -MT\ commonTools/gtest/CMakeFiles/gtest.dir/gtest/gtest-all.cc.o -MF CMakeFiles/gtest.dir/gtest/gte\st-all.cc.o.d -o CMakeFiles/gtest.dir/gtest/gtest-all.cc.o -c /work2/00434/eijkhout/trilinos/tr\ilinos-13-4-1/commonTools/gtest/gtest/gtest-all.cc
```

3. And Intel's `dpcpp` complains that it does not accept anything under 17.  Complains a lot.

It should be safe to specify 17 on the commandline, even if Trilinos uses only 17, right? So can I?

**Comment by jhux2** [comment]
@VictorEijkhout Trilinos develop and master branches require c++17 as of January 2023.  The cmake option is
`-D CMAKE_CXX_STANDARD:STRING`, e.g., `CMAKE_CXX_STANDARD:STRING=17`.

Be forewarned that if you specify c++17 for an earlier version of Trilinos, some packages may not be compliant.

**Comment by bartlettroscoe** [comment]
> I see no mention of the C++ standard on the installation instructions.

https://docs.trilinos.org/files/TrilinosBuildReference.html#setting-the-c-language-standard-for-trilinos

**Comment by jhux2** [comment]
Closing as answered.  @VictorEijkhout If you still have questions, please reopen.
