### ISSUE TITLE
Framework: Failed builds not posting to cdash

### ISSUE THREAD

**Issue by csiefer2** [trilinos/Trilinos#11535]
See this PR: https://github.com/trilinos/Trilinos/pull/11516
Also TRILINOSHD-243

**Comment by sebrowne** [comment]
I just checked and we're getting hit with a module load error (very early in the process, so no reporting) from the SEMS modules. I've made them aware of it, and hopefully they'll get back to me with an ETA for a fix soon. I may disable the autotester until then to reduce confusion.

Dual posting to track progress here.

**Comment by sebrowne** [comment]
SEMS has informed me that they think this issue is fixed, so we shall see next time the autotester starts.  I can confirm that I'm able to load the environment in question on my machine now.

**Comment by csiefer2** [comment]
I just got my PR through, so closing.  Thanks @sebrowne !
