### ISSUE TITLE
Panzer:  possible wrong connectivity if 2+ dofs per cell

### ISSUE THREAD

**Issue by bartgol** [trilinos/Trilinos#11536]
### Description
I think the STKConnManager is not adding the correct connectivity for Cell dofs, in case there are 2+ cell dofs. In particular, [this](https://github.com/trilinos/Trilinos/blob/23abb970c3a037feaa064e969c38b264119a9945/packages/panzer/adapters-stk/src/Panzer_STKConnManager.cpp#L289) line:

```
         for(LocalOrdinal i=0;i<cellIdCnt;i++)
            connectivity_.push_back(cellOffset+cellIdCnt*(bulkData.identifier(element)-1));
 ```
is adding the same Id for all the dofs of the cell, and should instead be
```
         for(LocalOrdinal i=0;i<cellIdCnt;i++)
            connectivity_.push_back(cellOffset+cellIdCnt*(bulkData.identifier(element)-1) + i);
```
just like it's done for subcell connectivities.

@trilinos/panzer does this seem the case to you too? Or am I missing something?

**Comment by rppawlo** [comment]
@eric-c-cyr - can you look at this?

**Comment by bartgol** [comment]
Eryc clarified things for me. This is a bit of an inconsistency with what is done in `addSubcellConnectivities`, where the number of ids per entity is considered, but it's not a problem, since the ConnManager is used by the DOFManager passing a `GeometricAggFieldPattern` obj, so there's always 1 dof per geometric entity anyways.
