### ISSUE TITLE
Framework: Add TPL HYPRE to tested configurations

### ISSUE THREAD

**Issue by tjfulle** [trilinos/Trilinos#11532]
In response to #11531: an internal Sandia customer requests that TPL HYPRE (version 2.18.2, https://github.com/hypre-space/hypre/archive/v2.18.2.tar.gz) be added to the PR test configurations.

We suggest the following configuration when building:

```
export F77=mpif77
export CC=mpicc
export CXX=mpicxx
cmake \
  -DHYPRE_WITH_MPI=ON \
  -DHYPRE_ENABLE_HYPRE_LAPACK=OFF \
  -DTPL_LAPACK_LIBRARIES=<lapack libs> \
  -DHYPRE_ENABLE_HYPRE_BLAS=OFF \
  -DTPL_BLAS_LIBRARIES=<blas libs> \
  -DHYPRE_WITH_OPENMP=OFF \
  -DHYPRE_ENABLE_BIGINT=int64 \
  -DHYPRE_ENABLE_MIXEDINT=OFF \
  -DHYPRE_ENABLE_COMPLEX=OFF \
  -DHYPRE_SHARED=OFF \
  -DHYPRE_ENABLE_FEI=OFF \
  -DHYPRE_WITH_DSUPERLU=OFF \
  $HYPER_SOURCE_DIR
```
@bartlettroscoe

**Comment by bartlettroscoe** [comment]
@trilinos/framework, @sebrowne

**Comment by sebrowne** [comment]
I will discuss this with @ccober6.  Currently we rely on the SEMS TPLs for our underlying TPLs, so if we follow the current methodology, this would have to be preceded by a request for SEMS to install HYPRE.

That being said, I would like to explore a containerized+spack build of Trilinos that does not require SEMS TPLs, so it may be applicable to that test case if we get to working on such a build soon.

**Comment by sebrowne** [comment]
After discussing this with @ccober6, we will not be adding this configuration to our set of tested configs at this time, given the aforementioned model by which we support TPLs.  We can revisit this once we have greater support for the AUE stack from ASC DevOps (I believe that HYPRE is in that stack), or if/once we transition to containerized workflows and can more nimbly support different configurations.

We can leave this issue open.
