### ISSUE TITLE
MueLu tutorial has undefined references

### ISSUE THREAD

**Issue by VictorEijkhout** [trilinos/Trilinos#1153]
`CMakeFiles/MueLu_tutorial_laplace2d.dir/laplace2d.cpp.o: In function `Teuchos::RCP<MueLu::SmootherPrototype<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > > MueLu::GetIfpackSmoother<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Teuchos::ParameterList const&, int const&)':
laplace2d.cpp:(.text._ZN5MueLu17GetIfpackSmootherIdiiN6Kokkos6Compat23KokkosDeviceWrapperNodeINS1_6SerialENS1_9HostSpaceEEEEEN7Teuchos3RCPINS_17SmootherPrototypeIT_T0_T1_T2_EEEERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS7_13ParameterListERKSB_[_ZN5MueLu17GetIfpackSmootherIdiiN6Kokkos6Compat23KokkosDeviceWrapperNodeINS1_6SerialENS1_9HostSpaceEEEEEN7Teuchos3RCPINS_17SmootherPrototypeIT_T0_T1_T2_EEEERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS7_13ParameterListERKSB_]+0x36): undefined reference to `MueLu::IfpackSmoother<Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::IfpackSmoother(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Teuchos::ParameterList const&, int const&)'
CMakeFiles/MueLu_tutorial_laplace2d.dir/laplace2d.cpp.o: In function `MueLu::MutuallyExclusiveTime<MueLu::Level>::start(bool)':
laplace2d.cpp:(.text._ZN5MueLu21MutuallyExclusiveTimeINS_5LevelEE5startEb[_ZN5MueLu21MutuallyExclusiveTimeINS_5LevelEE5startEb]+0x3b8): undefined reference to `MueLu::myParent_[abi:cxx11]'
laplace2d.cpp:(.text._ZN5MueLu21MutuallyExclusiveTimeINS_5LevelEE5startEb[_ZN5MueLu21MutuallyExclusiveTimeINS_5LevelEE5startEb]+0x41b): undefined reference to `MueLu::myParent_[abi:cxx11]'
`

And fiddle. I can't attach the log file because it's too large. Beats me why you guys keep using github.

https://www.dropbox.com/s/i3bnbxj97kscmdl/trilinos-12_intel17_impi_17_0.log?dl=0

**Comment by tawiesn** [comment]
We cannot access dropbox. Could you provide your configuration script such that we can try to reproduce the problem?

**Comment by VictorEijkhout** [comment]
On Mar 20, 2017, at 5:55 PM, Tobias Wiesner <notifications@github.com<mailto:notifications@github.com>> wrote:

We cannot access dropbox. Could you provide your configuration script such that we can try to reproduce the problem?

The script has too many machine dependencies.

Can copy that log from dropbox with your private account and then copy it to your work machine?

Or do you have a place for incoming ftp?

Can you inccrease the upload limit for github?

Victor.

**Comment by VictorEijkhout** [comment]
`cmake -VV \
  -D BUILD_SHARED_LIBS:BOOL=ON \
  -D Trilinos_VERBOSE_CONFIGURE=OFF \
  -D CMAKE_VERBOSE_MAKEFILE=ON \
  -D Trilinos_ENABLE_ALL_PACKAGES:BOOL=OFF \
  -D Trilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=OFF \
  -D Trilinos_ENABLE_TESTS:BOOL=OFF \
  -D Trilinos_ENABLE_EXAMPLES:BOOL=ON \
  -D Trilinos_ENABLE_Export_Makefiles:BOOL=ON \
  -D Trilinos_ENABLE_Fortran:BOOL=ON \
  \
  -D CMAKE_INSTALL_PREFIX:PATH=${INSTALL_LOCATION} \
  -D CMAKE_BUILD_TYPE:STRING=RELEASE \
  -D CMAKE_C_FLAGS:STRING="${COPTFLAGS} ${MKLFLAG}" \
  -D CMAKE_CXX_FLAGS:STRING="${COPTFLAGS} ${MKLFLAG} -DMPICH_SKIP_MPICXX" \
  \
  -D BLAS_INCLUDE_DIRS:PATH="${TACC_MKL_INC}" \
  -D BLAS_LIBRARY_DIRS:PATH="${TACC_MKL_LIB}" \
  -D BLAS_LIBRARY_NAMES:STRING="mkl_intel_lp64;mkl_sequential;mkl_core;pthread" \
  -D LAPACK_INCLUDE_DIRS:PATH="${TACC_MKL_INC}" \
  -D LAPACK_LIBRARY_DIRS:PATH="${TACC_MKL_LIB}" \
  -D LAPACK_LIBRARY_NAMES:STRING="mkl_intel_lp64;mkl_sequential;mkl_core;pthread" \
  \
  -D TPL_ENABLE_MPI:BOOL=ON \
  -D MPI_EXEC:FILEPATH="/opt/apps/xalt/0.6/bin/ibrun" \
  -D TPL_ENABLE_GLM=OFF \
  -D TPL_ENABLE_Matio=OFF \
  \
  -D TPL_ENABLE_Boost:BOOL=ON \
  -D Boost_INCLUDE_DIRS:PATH=$TACC_BOOST_INC      \
  -D Boost_LIBRARY_DIRS:PATH=$TACC_BOOST_LIB      \
  -D TPL_ENABLE_BoostLib:BOOL=ON \
  -D BoostLib_INCLUDE_DIRS:PATH=$TACC_BOOST_INC      \
  -D BoostLib_LIBRARY_DIRS:PATH=$TACC_BOOST_LIB      \
  \
  -D TPL_ENABLE_HDF5:BOOL=ON \
  -D HDF5_INCLUDE_DIRS:PATH=$TACC_HDF5_INC    \
  -D HDF5_LIBRARY_DIRS:PATH=$TACC_HDF5_LIB    \
  -D TPL_ENABLE_Netcdf:BOOL=ON \
  -D Netcdf_INCLUDE_DIRS:PATH=$TACC_NETCDF_INC    \
  -D Netcdf_LIBRARY_DIRS:PATH=$TACC_NETCDF_LIB    \
  \
  -D Trilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=ON \
  \
  -D Trilinos_ENABLE_Amesos:BOOL=ON \
  -D Amesos2_ENABLE_Basker:BOOL=ON \
  -D Trilinos_ENABLE_Anasazi:BOOL=ON \
  -D Trilinos_ENABLE_AztecOO:Bool=ON \
  -D Trilinos_ENABLE_Belos:BOOL=ON \
  -D Trilinos_ENABLE_Epetra:Bool=ON \
  -D Trilinos_ENABLE_EpetraExt:Bool=ON \
  -D                 Epetra_ENABLE_TESTS:BOOL=ON \
  -D Trilinos_ENABLE_FEI:Bool=OFF \
  -D Trilinos_ENABLE_Ifpack:Bool=ON \
  -D Trilinos_ENABLE_Intrepid:BOOL=ON \
  -D                 Intrepid_ENABLE_TESTS:BOOL=ON \
  -D Trilinos_ENABLE_Issoropia:BOOL=ON \
  -D Trilinos_ENABLE_Kokkos:BOOL=ON \
  -D Trilinos_ENABLE_ML:BOOL=ON \
  -D Trilinos_ENABLE_MOOCHO:BOOL=ON \
  -D Trilinos_ENABLE_MueLu:BOOL=OFF \
  -D Trilinos_ENABLE_NOX=ON \
  -D                 NOX_ENABLE_TESTS:BOOL=OFF \
  -D Trilinos_ENABLE_Pamgen:Bool=ON \
  -D Trilinos_ENABLE_Panzer:Bool=ON \
  -D Trilinos_ENABLE_Phalanx:BOOL=ON \
  -D Phalanx_EXPLICIT_TEMPLATE_INSTANTIATION=ON \
  -D Trilinos_ENABLE_Rythmos:BOOL=ON \
  -D Trilinos_ENABLE_Sacado:Bool=ON \
  -D Trilinos_ENABLE_SEACASIoss:BOOL=ON \
  -D Trilinos_ENABLE_SEACAS:BOOL=ON \
  -D Trilinos_ENABLE_SEACASBlot:BOOL=ON \
  -D Trilinos_ENABLE_SECONDARY_STABLE_CODE:BOOL=ON \
  -D Trilinos_ENABLE_Shards:BOOL=ON \
  -D Trilinos_ENABLE_ShyLU:BOOL=ON \
  -D Trilinos_ENABLE_STK:BOOL=ON \
  -D Trilinos_ENABLE_Stokhos:BOOL=ON \
  -D Trilinos_ENABLE_Stratimikos:BOOL=ON \
  -D Trilinos_ENABLE_Teko:BOOL=ON \
  -D Trilinos_ENABLE_Teuchos:BOOL=ON \
  -D Trilinos_ENABLE_Tpetra:BOOL=ON \
  -D Trilinos_ENABLE_TriKota:BOOL=ON \
  -D Trilinos_ENABLE_Zoltan:BOOL=ON \
  \
  -D CMAKE_PYTHON_INCLUDE_DIR:PATH="${TACC_PYTHON_INC}" \
  -D CMAKE_PYTHON_LIBRARIES:STRING="${TACC_PYTHON_LIB}" \
  -D Trilinos_ENABLE_PyTrilinos:Bool=ON \
  -D PyTrilinos_DOCSTRINGS:BOOL=OFF \
  -D SWIG_EXECUTABLE:FILEPATH=${TACC_SWIG_DIR}/bin/swig \
  \
  ${TRILINOS_LOCATION}/trilinos-${VERSION} \
  | tee /admin/build/admin/rpms/stampede/SPECS/trilinos-${VERSION}-cmake.log 2>&1`

**Comment by VictorEijkhout** [comment]
Please note that MueLu has been disabled in this one.

[trilinos.cmake.txt](https://github.com/trilinos/Trilinos/files/856642/trilinos.cmake.txt)

**Comment by VictorEijkhout** [comment]
Was that enough?

With MueLu disabled I was able to complete the build.

V.

**Comment by mhoemmen** [comment]
@trilinos/muelu

**Comment by VictorEijkhout** [comment]
Finally it occurred to me to compress the log file.....
[trilinos-12_intel17_impi_17_0.log.zip](https://github.com/trilinos/Trilinos/files/865680/trilinos-12_intel17_impi_17_0.log.zip)

**Comment by jhux2** [comment]
@VictorEijkhout You can also just disable the tutorial with the cmake option ```-DMueLu_ENABLE_Tutorial:BOOL=OFF```

**Comment by jhux2** [comment]
> Can copy that log from dropbox with your private account and then copy it to your work machine? Or do you have a place for incoming ftp? Can you inccrease the upload limit for github?

Sorry, dropbox is not an option.  [Github](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) determines the file size limits.

**Comment by VictorEijkhout** [comment]
On Mar 23, 2017, at 4:38 PM, Jonathan Hu <notifications@github.com<mailto:notifications@github.com>> wrote:

Sorry, dropbox is not an option.  Github<https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/> determines the file size limits.

I realize that. I uploaded a zipped version earlier today.

Victor.

PS github is a disaster. On an earlier ticket I attached a file multiple times, never getting a message that github didn’t accept it. You only see that on the web interface.

**Comment by VictorEijkhout** [comment]
On Mar 23, 2017, at 3:15 PM, Jonathan Hu <notifications@github.com<mailto:notifications@github.com>> wrote:

disable the tutorial with the cmake option -DMueLu_ENABLE_Tutorial:BOOL=OFF

Works, thanks.

Victor.

**Comment by aprokop** [comment]
Not sure if this is still a problem. Closing for now.

**Comment by VictorEijkhout** [comment]
No one has ever told me that the problem was fixed. Did you actually test that the problem went away? Personally I don’t have time for that, so I’m choosing the easy way out by just not building the tutorials.

Victor.

On May 13, 2017, at 8:56 PM, Andrey Prokopenko <notifications@github.com<mailto:notifications@github.com>> wrote:


Not sure if this is still a problem. Closing for now.

**Comment by aprokop** [comment]
Right. I think we have this workaround of not building the tutorials, and apparently nobody had time to look at it for almost two months.
