### ISSUE TITLE
Teuchos / Tpetra: deep_copy_offset is not obviously async but it should be labeled to make it obvious

### ISSUE THREAD

**Issue by csiefer2** [trilinos/Trilinos#11566]
As discovered by this PR https://github.com/trilinos/Trilinos/pull/11565. @crtrott to add comments below

See below discussion.

**Comment by crtrott** [comment]
I personally believe that you should have a version which takes a execution space instance, and that one would be async, while the one without will synchronize. Its gonna be hard to explain to anyone that
```c++
Kokkos::deep_copy(A,B);
Kokkos::Compar::deep_copy_range(A,B,0,0,100);
``` 
are synchronous, but
```c++
Kokkos::Compat::deep_copy_offset(A,B,0,0,100);
```
is asynchronous ...

**Comment by crtrott** [comment]
Oh and btw. we should deprecate/move to other namespace things in Trilinos packages which define stuff in the Kokkos:: namespace. That

**Comment by csiefer2** [comment]
@cwpearson also noticed something along this line: https://github.com/trilinos/Trilinos/pull/11325
