### ISSUE TITLE
Set up Windows VMs for Trilinos testing

### ISSUE THREAD

**Issue by jwillenbring** [trilinos/Trilinos#1157]
@trilinos/framework 

As discussed earlier today, we need to set up a couple of VMs for Trilinos testing on Windows. Here is a rough outline of the associated tasks:

1) Install all necessary software on 1st VM. Visual Studio 2015 is the current target at a high level, but we also need git (and possibly putty to support git), CMake, blas, lapack and mpi.
2) Test first VM by building some subset of Trilinos.
3) When VM seems to be in good shape, copy the VM so that we eventually have 1 that runs Jenkins jobs, and 1 developers are allowed to log directly in to for debugging.

We can split some of this into separate tickets in the future if it makes sense.

**Comment by mplooster** [comment]
We will probably want to install [Ninja](https://ninja-build.org/) as well (see #1160).

**Comment by mplooster** [comment]
Also, we will likely need Perl for the Zoltan regression tests.

**Comment by jwillenbring** [comment]
We decided today to not create a second VM for now, but rather to set up the first VM as a Jenkins slave and use that for the purposes of both VMs unless that proves inadequate.
