### ISSUE TITLE
Panzer:  Define or access time derivatives in the boundary factory

### ISSUE THREAD

**Issue by delcmo** [trilinos/Trilinos#11572]
## Question
Hello,

I am trying to add a boundary flux to the boundary strategy logic and one of the dependent variable is function of the time derivatives. I cannot figure out how to access the time derivative from `BCStrategy` class. I understand I have to register the corresponding evaluator as it is currently being done for the degree of freedom and the gradient with the functions `DOF` and `DOFGradient`, respectively.

I would appreciate if you could provide some help or point me to an example/issue related to the same topic.

Thanks,
Marco

**Comment by cgcgcg** [comment]
@trilinos/panzer @rppawlo
