### ISSUE TITLE
Framework: how to pass batch options through cmake

### ISSUE THREAD

**Issue by jhux2** [trilinos/Trilinos#11573]
## Question
@trilinos/framework @sebrowne @bartlettroscoe 

I would like to run Trilinos unit tests on vortex.  I recall there's a mechanism for making sure that if I run ctest on a compute node, that it picks up the correct run command (`jsrun` in this case) and options.  However, I can't find the details anywhere in my old scripts.

Is this done via a CMake configure line?  Is there some documentation I can look at?  Thanks.

**Comment by bartlettroscoe** [comment]
@jhux2, everything I know about running on vortex is shown in the ATDM Trilinos configuration and drivers under:

```
cmake/std/atdm/ats2/
cmake/ctest/drivers/atdm/ats2/
```

However, that configuration has not been maintained and is currently failing the configure a shown [here](https://testing.sandia.gov/cdash/index.php?project=Trilinos&date=2023-02-16&filtercount=2&showfilters=1&filtercombine=and&field1=groupname&compare1=62&value1=Experimental&field2=buildname&compare2=65&value2=Trilinos-atdm-ats2) showing:

![image](https://user-images.githubusercontent.com/1959736/219790994-a96536bf-ca2b-4d16-bb2f-e2f81e72366d.png)

My guess is that if someone updates the compilers used in that configuration, it will still work.  See:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#ats-2

**Comment by jhux2** [comment]
@bartlettroscoe  Switching to CUDA 11.x would certainly fix the configuration error introduced when Trilinos moved to requiring C++17.

Thanks for the pointers.  For the record, I found that these cmake options are necessary to be able to run Trilinos tests on GPU on vortex:

```
  -D MPI_EXEC:FILEPATH=/opt/ibm/spectrum_mpi/jsm_pmix/bin/jsrun
  -D MPI_EXEC_POST_NUMPROCS_FLAGS:STRING="-M;-gpu;-r4;-c4;-g1;-brs"
```

**Comment by sebrowne** [comment]
I do have a tentative story to enable building on ATS2 again via the GenConfig system (effectively porting the stuff from the ATDM system over and updating the compilers).  @cgcgcg asked for it on our help desk as [TRILINOSHD-244](https://sems-atlassian-son.sandia.gov/jira/projects/TRILINOSHD/queues/custom/122/TRILINOSHD-244) if you want to follow what happens.
