### ISSUE TITLE
Framework: unable to connect to PR dashboard

### ISSUE THREAD

**Issue by jhux2** [trilinos/Trilinos#11580]
## Bug Report
@trilinos/framework @sebrowne

Links to PR testing results return an error.  This can be seen, for example, in PR #11576.  In that PR, the link https://trilinos-cdash.sandia.gov/index.php?project=Trilinos&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=63&value1=PR-11576-test&field2=buildstarttime&compare2=84&value2=NOW causes the following:

<img width="1434" alt="Screen Shot 2023-02-20 at 5 24 11 PM" src="https://user-images.githubusercontent.com/12970120/220224258-7d7400d9-ccb9-47a4-bc11-61f0bb8729db.png">

**Comment by jhux2** [comment]
PR dashboard is accessible again.

**Comment by sebrowne** [comment]
@jhux2 I think that the team that manages our server processes was performing maintenance and patches yesterday from 5-6PM ish, so that likely was the cause of the service interruption.
