### ISSUE TITLE
Adelus: Link Error on Library Load

### ISSUE THREAD

**Issue by matekelemen** [trilinos/Trilinos#11593]
## Bug Report
@srajama1 (Adelus)

### Description
I'm working on a project that uses Trilinos on the C++ level and has bindings for python. The library compiles just fine, but when python tries to load a binary module that's supposed to link with Trilinos (and eventually Adelus I guess), it fails with the following message:
```
ImportError: /usr/lib/libzadelus.so.13: undefined symbol: _ZN6Adelus10nprocs_colE
```

I'm on an up-to-date Manjaro and am using [Trilinos from the AUR](https://aur.archlinux.org/packages/trilinos). This has been an issue since at least last December, but probably several weeks before that too. Here's the [issue and temporary fix](https://github.com/KratosMultiphysics/Kratos/issues/10536) on our side, should you need it.

I've been looking around on our side but couldn't find out what might be the cause, so I'm hoping someone recognizes what's going on. I know this isn't much of a useful description to you because you have no idea how the project I'm working on uses Trilinos, but in case you've had similar problems / bug reports please let me know.

**Comment by jjellio** [comment]
I remember seeing this when working with HPE to build various things.  I think our work around was to build with static libs, but that won't really work well here.

I think a fix would be to add a ETI  files for:
https://github.com/trilinos/Trilinos/blob/master/packages/adelus/src/Adelus_vars.hpp

(instantiate for the types needed, complex, etc..) - and move the definition bits from the hpp into a cpp.

**Comment by jhux2** [comment]
@trilinos/adelus

**Comment by vqd8a** [comment]
@matekelemen This is because we used some global variables in Adelus. I had a fix for this issue in the Trilinos ```develop``` branch and then ```master``` branch in Aug 2022. I am seeing you are using Trilinos 13.4.1 which I believe it did not include this fix. 
Could you please try building your code again with either Trilinos ```master``` branch or ```develop``` branch? If you still see the issue, I am going to try what @jjellio suggested above.

**Comment by matekelemen** [comment]
I tried the current `master` and it seems to have solved the issue. Do you have an ETA on your next release?

Thanks for the help!

**Comment by vqd8a** [comment]
@matekelemen Thanks for letting me know. @jhux2 Do you know the answer for the question above?

**Comment by jhux2** [comment]
> Do you have an ETA on your next release?

@vqd8a I don't know, but @sebrowne probably does.

**Comment by sebrowne** [comment]
Ideally sooner than later.  We're waiting on Kokkos 4.0 to be integrated, but the plan is to release pretty soon after that.  Target is sometime in March.

**Comment by matekelemen** [comment]
Thanks for the update! I'll close the issue once the new release is out, just in case anyone else runs into this problem.
