### ISSUE TITLE
Teuchos::size overload problem

### ISSUE THREAD

**Issue by VictorEijkhout** [trilinos/Trilinos#11591]
```
[ 16%] Building CXX object packages/teuchos/remainder/src/CMakeFiles/teuchosremainder.dir/Teuchos_StringToIntMap.cpp.o
cd /work2/00434/eijkhout/trilinos/build-13-4-1-clx-intel-impi/packages/teuchos/remainder/src && /scratch1/projects/compilers/intel20u1/compilers_and_libraries_2020.1.217/linux/mpi/intel64/bin/mpic
xx -DTEUCHOS_LIB_EXPORTS_MODE -Dteuchosremainder_EXPORTS -I/work2/00434/eijkhout/trilinos/build-13-4-1-clx-intel-impi -I/work2/00434/eijkhout/trilinos/trilinos-13-4-1/packages/teuchos/remainder/sr
c -I/work2/00434/eijkhout/trilinos/build-13-4-1-clx-intel-impi/packages/teuchos/remainder/src -I/work2/00434/eijkhout/trilinos/build-13-4-1-clx-intel-impi/packages/teuchos/core/src -I/work2/00434/
eijkhout/trilinos/trilinos-13-4-1/packages/teuchos/core/src -I/work2/00434/eijkhout/trilinos/build-13-4-1-clx-intel-impi/packages/kokkos/core/src -I/work2/00434/eijkhout/trilinos/trilinos-13-4-1/p
ackages/kokkos/core/src -I/work2/00434/eijkhout/trilinos/build-13-4-1-clx-intel-impi/packages/kokkos -O2 -mkl -DMPICH_SKIP_MPICXX   -O3 -DNDEBUG -fPIC -std=c++17 -MD -MT packages/teuchos/remainder
/src/CMakeFiles/teuchosremainder.dir/Teuchos_StringToIntMap.cpp.o -MF CMakeFiles/teuchosremainder.dir/Teuchos_StringToIntMap.cpp.o.d -o CMakeFiles/teuchosremainder.dir/Teuchos_StringToIntMap.cpp.o
 -c /work2/00434/eijkhout/trilinos/trilinos-13-4-1/packages/teuchos/remainder/src/Teuchos_StringToIntMap.cpp
/work2/00434/eijkhout/trilinos/trilinos-13-4-1/packages/teuchos/parser/src/Teuchos_make_lalr1_parser.cpp(50): error: more than one instance of overloaded function "Teuchos::size" matches the argument list:
            function template "auto std::size(const _Container &)->decltype((<expression>))"
            function template "int Teuchos::size(const std::vector<T, std::allocator<T>> &)"
            argument types are: (const Teuchos::Grammar::Productions)
    for (int i = 0; i < size(g.productions); ++i) {
                        ^
/work2/00434/eijkhout/trilinos/trilinos-13-4-1/packages/teuchos/parser/src/Teuchos_stack.hpp(9): note: this candidate was rejected because at least one template argument could not be deduced
  int size(std::stack<T> const& s) { return static_cast<int>(s.size()); }
      ^
```

Intel 19 compiler.

**Comment by jhux2** [comment]
@trilinos/teuchos

**Comment by VictorEijkhout** [comment]
I'd appreciate a resolution to this. While I can compile the latest repo pull, you have changed cmake discovery, so I can not build dealii with that. 

(I have suggested before that you add dealii to your set of regression tests. It has found problems in your setup any number of times. But that's another matter.)

**Comment by bartlettroscoe** [comment]
This is a Trilinos build issue, not a customer build issue.  Why are we not seeing this in any automated Trilinos builds?  Are there no automated builds of Trilinos using Intel 19?s

@sebrowne

**Comment by sebrowne** [comment]
That is correct.  Trilinos current only has automated builds/testiong against the compilers/MPIs listed here: https://github.com/trilinos/Trilinos/wiki/Pull-Request-Testing-Interface

I will note that although that page does not include the Intel compilers, we are currently working on restoring a missing build to that page that uses Intel-2021.3.0/OpenMPI-4.0.5

**Comment by bartlettroscoe** [comment]
@VictorEijkhout, as you can reproduce this and we can't, can you submit a PR with a commit that fixes the problem?

**Comment by VictorEijkhout** [comment]
Sorry, that's not going to happen. I've never dug into your source code so I wouldn't know where to start.

I'll next explore gcc & Intel 1api.

**Comment by bartlettroscoe** [comment]
@VictorEijkhout, apparently there is an official Trilinos compiler support policy documented at:

* https://github.com/trilinos/Trilinos/blob/develop/INSTALL.rst#5support-for-different-compilersmpis

which seems to be consistent with what was requested [above](https://github.com/trilinos/Trilinos/issues/11591#issuecomment-1442070819).

Thanks for reporting issues like this.  This helps us get a head start once we get to porting work once we get access to build configurations for these compilers.  And in the meantime, it lets other users know this is an issue so they don't need to report it as well.
