### ISSUE TITLE
Xpetra causing build errors for Albany

### ISSUE THREAD

**Issue by ikalash** [trilinos/Trilinos#11606]
We are having Xpetra-related build errors in the Albany nightlies on Weaver and Cori related to incomplete types.  Please see: 

https://github.com/sandialabs/Albany/issues/915
and 
https://my.cdash.org/viewBuildError.php?buildid=2293991 

The former is when building Albany against Trilinos; the latter is in building Trilinos.  Could someone please look into this?  

Tagging @bartgol who may be interested in this issue.

**Comment by ikalash** [comment]
@trilinos/xpetra

**Comment by cgcgcg** [comment]
Is it possible that something else changed? As far as I can tell, nothing changed in Xpetra since January 23.

**Comment by cgcgcg** [comment]
Ah, I think what happened is that #11583 got merged. `Xpetra_ENABLE_Epetra=OFF` is set explicitely but `Xpetra_ENABLE_EpetraExt=ON` gets set automatically during configure. Don't know what exactly triggers this or if this is indeed the intended behavior. But you should be able to fix your build by setting `Xpetra_ENABLE_EpetraExt=OFF`.

**Comment by ikalash** [comment]
I will try this and report back.  Thanks for the fast reply.

**Comment by ikalash** [comment]
It appears this fixed the problem.  Thanks for your help @cgcgcg !
