### ISSUE TITLE
Windows install capability

### ISSUE THREAD

**Issue by jwillenbring** [trilinos/Trilinos#1163]
@trilinos/framework 

It needs to be possible to install Trilinos libraries on a Windows machine and have supporting infrastructure for calling those libraries from an application. This story is for tracking the development of those features.

**Comment by AuroraDysis** [comment]
I think [vcpkg](https://github.com/Microsoft/vcpkg) is a convenient way.

**Comment by mplooster** [comment]
@AuroraDysis  Do you know if vcpkg works with CMake/CPack?

**Comment by AuroraDysis** [comment]
Yes, it supports CMake/CPack.
