### ISSUE TITLE
Tpetra&KokkosKernels: Debug mode checks on SpGEMM fail

### ISSUE THREAD

**Issue by cgcgcg** [trilinos/Trilinos#11655]
@trilinos/kokkos-kernels @trilinos/tpetra 

## Bug Report
In debug builds Kokkos Kernels recently added checks that the input matrices are sorted. Some TPLs require that, but currently Tpetra SpGEMM cannot use them.

When computing `A*B` on multiple ranks, Tpetra imports B into the colMap of A. The resulting Bmerged is not necessarily sorted and hence triggers the assert in Kokkos Kernels.

One such example is the test `PanzerMiniEM_MiniEM-BlockPrec_RefMaxwell_reuse_MPI_4`. I verified that in this case both A and B are sorted, but Bmerged is not.

**Comment by jhux2** [comment]
> Some TPLs require that, but currently Tpetra SpGEMM cannot use them.

@cgcgcg By this, you mean that Tpetra's SpGEMM is unable to take advantage of sorted indices?

**Comment by cgcgcg** [comment]
It seems that whenever Tpetra does an SpGEMM, no matter what TPLs are enabled, we end up with the KokkosKernels implementation (due to wrong type for offsets). Kokkos Kernels does not require sorted indices, only some TPLs do.

**Comment by brian-kelley** [comment]
@jhux2 It's because Tpetra CrsMatrix uses offset = size_t for the local matrix type, but all 3 TPLs only work when offset = int (offset being the rowptrs element type).

I'm thinking of adding the code in Tpetra MatrixMatrix to convert the offsets to int explicitly so that the TPLs can be called (just for performance).

**Comment by jhux2** [comment]
> It seems that whenever Tpetra does an SpGEMM, no matter what TPLs are enabled, we end up with the KokkosKernels implementation (due to wrong type for offsets).

> It's because Tpetra CrsMatrix uses offset = size_t for the local matrix type, but all 3 TPLs only work when offset = int (offset being the rowptrs element type).

@cgcgcg @brian-kelley Gotcha, makes sense.

**Comment by cgcgcg** [comment]
@rppawlo Can you confirm that #11663 fixed this for EMPIRE?

**Comment by cgcgcg** [comment]
@brian-kelley I guess we can leave the issue open to track that something should still happen on the Tpetra side.
