### ISSUE TITLE
MueLu: Build errors in matrix-free example

### ISSUE THREAD

**Issue by cgcgcg** [trilinos/Trilinos#11660]
## Bug Report
```
/home/caglusa/Trilinos/packages/muelu/research/graham/mf_example_01.cpp:627:7: error: 'sleep' was not declared in this scope
       sleep(my_rank);
       ^~~~~
```

Also:

https://testing.sandia.gov/cdash/viewBuildError.php?buildid=11498666

**Comment by GrahamBenHarper** [comment]
Hah, that's a really random error. I guess I need `<unistd.h>` included? I can also fix the inconsistent Teuchos::Comm vs Teuchos::MpiComm usage.

**Comment by GrahamBenHarper** [comment]
Okay I'm having trouble reproducing this somehow. It even builds on Fugaku without issue, which is ironic since building on Fugaku has been the hardest for us. I'll see if I can reproduce the environment/config so I can fix all these at once instead of doing repeated incremental fixes.

**Comment by cgcgcg** [comment]
No more build errors!

**Comment by cgcgcg** [comment]
Spoke too soon. There are a bunch of hard coded template args that cause link errors.

**Comment by GrahamBenHarper** [comment]
oh yeah, I assume things like hardcoded uses of double? link to the failures?

**Comment by GrahamBenHarper** [comment]
Ohhh I see now. It's probably from
```
    using SC = double;
    using LO = int;
    using GO = long long;
    using NO = Tpetra::MultiVector<>::node_type;
```
With the testing framework in there, what do you think is an appropriate fixup for that?

**Comment by cgcgcg** [comment]
Just use the template args:
https://github.com/trilinos/Trilinos/blob/07a951062df54e4d4a095c1358fcf1102d9243cc/packages/muelu/research/graham/mf_example_01.cpp#L441

**Comment by GrahamBenHarper** [comment]
How about now? :)

**Comment by cgcgcg** [comment]
Seems to build.
