### ISSUE TITLE
Kokkos:  Seemingly repeated failing test

### ISSUE THREAD

**Issue by sebrowne** [trilinos/Trilinos#11678]
@trilinos/kokkos 

## Bug Report
https://trilinos-cdash.sandia.gov/viewTest.php?onlyfailed&buildid=789888 demonstrates a KokkosCore unit test that has been seemingly repeatedly failing for me when I'm running trying to merge PR #11645 .  I think both of the unit tests in that tester have failed, so it may not be an issue with the test itself, but it's happened enough to me now that I felt comfortable reaching out for help.

Is there something wrong with how we've got PR testing set up?  I know that we're still running all of the tests on the first machine GPU, which hopefully will be addressed by #11391 .  Not sure if that's related, but I thought it may be.

**Comment by ndellingwood** [comment]
@sebrowne the [KokkosCore_UnitTest_CudaTimingBased_MPI_1](https://trilinos-cdash.sandia.gov/test/22109989) tests' pass/fail criteria is based on timing results and can be quite flaky, I would suggest disabling that test if it is causing problems with PR testing
