### ISSUE TITLE
Tpetra: possible optimization when removing zeros

### ISSUE THREAD

**Issue by jhux2** [trilinos/Trilinos#11671]
## Enhancement
This is a potential follow-up to #11604.  In `removeCrsMatrixZeros` there should be a check whether any zeros were actually removed.  If not, then the function can just return early.

**Comment by brian-kelley** [comment]
@jhux2 I think #11715 took care of this, can it be closed?

**Comment by jhux2** [comment]
@brian-kelley Yep, thanks!
