### ISSUE TITLE
Piro: compilation errors building Albany-LCM

### ISSUE THREAD

**Issue by ikalash** [trilinos/Trilinos#11670]
We have compilation errors in Albany-LCM due to things in Piro pertaining to ROL/analysis: 

https://sems-cdash-son.sandia.gov/cdash/viewBuildError.php?buildid=46293

The errors look like this: 
```
[packages/piro/src/Piro_PerformAnalysis.cpp:662](https://blob/master/packages/piro/src/Piro_PerformAnalysis.cpp#L662):85: error: ‘H_dotP’ was not declared in this scope
```

@mperego , @kliegeois : is this due to changes you pushed recently?

@trilinos/piro

**Comment by ikalash** [comment]
Tagging @lxmota who is also interested in this issue.

**Comment by mperego** [comment]
Oh sorry. I think there is a missing ifdef guard for Teko. Probably you are not enabling Teko. I'll create a PR with the fix.

**Comment by ikalash** [comment]
Thank you!

**Comment by mperego** [comment]
@ikalash can you please approve #11762?
