### ISSUE TITLE
Kokkos: issues with Kokkos::Compat space

### ISSUE THREAD

**Issue by ikalash** [trilinos/Trilinos#11683]
We're getting failures in the Albany and Albany-LCM nightlies related to Kokkos::Compat:

https://sems-cdash-son.sandia.gov/cdash/viewBuildError.php?buildid=46392

```
[Albany/src/Albany_KokkosTypes.hpp:16](https://blob/master/Albany/src/Albany_KokkosTypes.hpp#L16):10: fatal error: KokkosCompat_ClassicNodeAPI_Wrapper.hpp: No such file or directory
```
https://sems-cdash-son.sandia.gov/cdash/viewBuildError.php?buildid=46410
```
[packages/tpetra/core/src/TpetraCore_ETIHelperMacros.h:143](https://blob/master/packages/tpetra/core/src/TpetraCore_ETIHelperMacros.h#L143):18: error: ‘Compat’ in namespace ‘Kokkos’ does not name a type
```
https://sems-cdash-son.sandia.gov/cdash/viewBuildError.php?buildid=46409
```
[packages/tpetra/core/src/Tpetra_Details_getGraphDiagOffsets.cpp:61](https://blob/master/packages/tpetra/core/src/Tpetra_Details_getGraphDiagOffsets.cpp#L61):3: error: no member named 'Compat' in namespace 'Kokkos'
```
Could someone please help resolved this?  Please let me know if I should open a separate issue with Kokkos.

@kokkos-devops-admin

**Comment by cgcgcg** [comment]
@trilinos/tpetra @cwpearson

**Comment by ikalash** [comment]
Update: the first issue with Albany is on our side - we needed to update Albany to comply with Tpetra changes and @maxcarl has opened a PR on this.  The issues in LCM however are on the Trilinos side.  Tagging @lxmota who likely is interested in this issue from the LCM side.

**Comment by maxcarl** [comment]
> Update: the first issue with Albany is on our side - we needed to update Albany to comply with Tpetra changes and @maxcarl has opened a PR on this. The issues in LCM however are on the Trilinos side. Tagging @lxmota who likely is interested in this issue from the LCM side.

Pretty sure you didn't mean to tag me, since I have never heard of this repo 😉

**Comment by ikalash** [comment]
Sorry, it was supposed to be @mcarlson801!

**Comment by csiefer2** [comment]
@cwpearson

**Comment by tkordenbrock** [comment]
I have also run into a couple of problems making the transition to the new `Tpetra::KokkosCompat` namespace.

First is that the header guard in `KokkosCompat_ClassicNodeAPI_Wrapper.hpp` is the same as in the new `Tpetra_KokkosCompat_ClassicNodeAPI_Wrapper.hpp`.  Both use `TPETRAKOKKOSCOMPAT_CLASSICNODEAPI_WRAPPER_HPP` which requires an `#undef` before `KokkosCompat_ClassicNodeAPI_Wrapper.hpp` can be successfully included.

Second is that `package/tpetra/core/compat/CMakeLists.txt` uses `${PACKAGE_NAME}_ENABLE_DEPRECATED_CODE` to decide which headers to install.  `PACKAGE_NAME` is defined as `TpetraCore` so the usual `Tpetra_ENABLE_DEPRECATED_CODE` isn't sufficient to enable the deprecated types in `Kokkos::Compat`.

**Comment by ikalash** [comment]
We are still seeing this issue in LCM.  It would be great if someone from @trilinos/tpetra could have a look at this / get this fixed so that our code works again.  It's curious that this is not happening in Albany master.  Perhaps the difference is different options enabled in Trilinos?

**Comment by cwpearson** [comment]
@tkordenbrock and @ikalash , I will get on this right away.

**Comment by ikalash** [comment]
@cwpearson : thank you!

**Comment by tkordenbrock** [comment]
> @tkordenbrock I believe #11700 will address your problems

Thanks!

**Comment by jhux2** [comment]
> I'm unfamiliar with Albany-LCM, can you point me at the errors you're seeing so I can be sure to address them?

@cwpearson Can you access the links in the description above?

**Comment by cwpearson** [comment]
I see at the end of the configure step of the failed build you linked above:

```
Processing ETI support: TpetraCore
-- TpetraCore: Processing ETI / test support
-- Enabled Scalar types:        long long|double
-- Enabled LocalOrdinal types:  int
-- Enabled GlobalOrdinal types: long long
-- Enabled Node types:          Tpetra::KokkosCompat::KokkosSerialWrapperNode
-- Excluded type combinations: :
-- Set of enabled types, before exclusions: S={double} LO={int} GO={long long} N={Kokkos::Compat::KokkosSerialWrapperNode};S={double} N={Tpetra::KokkosCompat::KokkosSerialWrapperNode} LO={int} GO={long long};S={long long} N={Tpetra::KokkosCompat::KokkosSerialWrapperNode} LO={int} GO={long long};S={double} N={Tpetra::KokkosCompat::KokkosSerialWrapperNode} LO={int} GO={long long}
```

I believe that `Kokkos::Compat::KokkosSerialWrapperNode` is causing the problem. I am trying to determine where it came from

**Comment by ikalash** [comment]
@cwpearson : is the KokkosNode N set by a Trilinos configure option?  My guess is that it is, if this is printed upon configuring Trilinos.

@lxmota : can you please point us to the configure script for Trilinos that is being used in the LCM builds on algol/proxima?  I'd like to compare it to the one I have for the Albany master tests.

**Comment by cwpearson** [comment]
The default node in your build seems to be properly set: 
```
-- Setting default Node to Tpetra::KokkosCompat::KokkosSerialWrapperNode.
```

**Comment by ikalash** [comment]
@cwpearson : I am not sure I follow the above two comments.  We want Tpetra::KokkosCompat::KokkosSerialWrapperNode to be set, right?  It looks like the code is doing that?

I just looked some more at the configure options and configure output, and it looks like Tpetra and Xpetra deprecated code is disabled in the LCM build, whereas it is enabled in the main Albany.  Could that be the problem?

**Comment by cgcgcg** [comment]
My understanding is that @cwpearson tried to reproduce that build and didn't see the same CMake output, i.e. nothing about `Kokkos::Compat::KokkosSerialWrapperNode`. Would it be possible to nuke the build directory and see if some leftover stuff from a previous build caused the problem?

**Comment by ikalash** [comment]
@lxmota : are the build dirs in the nightly algol and proxima builds removed each night?  I thought they were.  I modified the nightly test scripts to enable deprecated tpetra code to see if it fixes the problem.

**Comment by lxmota** [comment]
Yes, the source, build and install directories are deleted and both Trilinos and Albany/LCM are cloned and rebuilt from scratch each night.

**Comment by cgcgcg** [comment]
Thanks for checking. So it has to be something else on our end.

**Comment by cgcgcg** [comment]
I believe I have an idea. Your build enables DataTransferKit. In its CMake configure it does this:
https://github.com/ORNL-CEES/DataTransferKit/blob/857b3642b0144fe49897469c1c20ca66af1e36cd/CMakeLists.txt#L71-L87
Maybe that is propagated back to Tpetra?

**Comment by cwpearson** [comment]
I believe @cgcgcg is right. I think DataTransferKit will need a patch like this to update it's integration with Tpetra's ETI:

```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index db75c1b4..03f01734 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -74,16 +74,16 @@ ELSE()
         SET(${PACKAGE_NAME}_ETI_GORDS   "long")
         SET(${PACKAGE_NAME}_ETI_NODES "")   # start with the empty list
         IF ("SERIAL" IN_LIST Kokkos_DEVICES)
-          LIST(APPEND ${PACKAGE_NAME}_ETI_NODES "Kokkos::Compat::KokkosSerialWrapperNode")
+          LIST(APPEND ${PACKAGE_NAME}_ETI_NODES "Tpetra::KokkosCompat::KokkosSerialWrapperNode")
         ENDIF()
         IF ("OPENMP" IN_LIST Kokkos_DEVICES)
-          LIST(APPEND ${PACKAGE_NAME}_ETI_NODES "Kokkos::Compat::KokkosOpenMPWrapperNode")
+          LIST(APPEND ${PACKAGE_NAME}_ETI_NODES "Tpetra::KokkosCompat::KokkosOpenMPWrapperNode")
         ENDIF()
         IF ("CUDA" IN_LIST Kokkos_DEVICES)
-          LIST(APPEND ${PACKAGE_NAME}_ETI_NODES "Kokkos::Compat::KokkosCudaWrapperNode")
+          LIST(APPEND ${PACKAGE_NAME}_ETI_NODES "Tpetra::KokkosCompat::KokkosCudaWrapperNode")
         ENDIF()
         IF("THREADS" IN_LIST Kokkos_DEVICES)
-          LIST(APPEND ${PACKAGE_NAME}_ETI_NODES "Kokkos::Compat::KokkosThreadsWrapperNode")
+          LIST(APPEND ${PACKAGE_NAME}_ETI_NODES "Tpetra::KokkosCompat::KokkosThreadsWrapperNode")
         ENDIF()
     ELSE()
         # Setup the same ETI as Tpetra but do not set global ordinal types as
diff --git a/cmake/ETI.cmake b/cmake/ETI.cmake
index 777e8285..838efdf8 100644
--- a/cmake/ETI.cmake
+++ b/cmake/ETI.cmake
@@ -74,13 +74,13 @@ ENDFUNCTION()
 #
 # NAME_IN [in] The type to mangle.
 FUNCTION(DTK_NODE_MACRO_NAME NAME_OUT NAME_IN)
-    STRING(REGEX MATCH "Kokkos::Compat::Kokkos(.*)WrapperNode" TMP0 "${NAME_IN}")
+    STRING(REGEX MATCH "Tpetra::KokkosCompat::Kokkos(.*)WrapperNode" TMP0 "${NAME_IN}")
     STRING(COMPARE EQUAL "${TMP0}" "" DOES_NOT_MATCH)
     IF(DOES_NOT_MATCH)
         MESSAGE(FATAL_ERROR "DTK: Node $NAME_IN is not a supported Node type.")
     ELSE()
         # Extract the Kokkos execution space (KOKKOS_EXEC_SPACE) from the Node name.
-        STRING(REGEX REPLACE "Kokkos::Compat::Kokkos(.*)WrapperNode" "\\1" KOKKOS_EXEC_SPACE "${NAME_IN}")
+        STRING(REGEX REPLACE "Tpetra::KokkosCompat::Kokkos(.*)WrapperNode" "\\1" KOKKOS_EXEC_SPACE "${NAME_IN}")
 
         # Special case: Threads.  The macro name unfortunately differs
         # from the execution space name in a way that doesn't fit the
diff --git a/packages/Meshfree/src/DTK_SplineOperator_decl.hpp b/packages/Meshfree/src/DTK_SplineOperator_decl.hpp
index d61a02aa..de5aaecb 100644
--- a/packages/Meshfree/src/DTK_SplineOperator_decl.hpp
+++ b/packages/Meshfree/src/DTK_SplineOperator_decl.hpp
@@ -47,7 +47,7 @@ class SplineOperator : public PointCloudOperator<DeviceType>
                    "Only implemented for linear basis functions!" );
     using LO = int;
     using GO = long long;
-    using NO = Kokkos::Compat::KokkosDeviceWrapperNode<
+    using NO = Tpetra::KokkosCompat::KokkosDeviceWrapperNode<
         typename DeviceType::execution_space>;
     using SC = Coordinate;
```

I think this is propagated to Tpetra because during Tpetra's ETI instantiation I now have a long list of ETIs, with some duplicates:

```
Set of enabled types, before exclusions: S={int} LO={int} GO={long long} N={Tpetra::KokkosCompat::KokkosSerialWrapperNode};S={double} N={Tpetra::KokkosCompat::KokkosSerialWrapperNode} LO={int} GO={long long};S={double} N={Tpetra::KokkosCompat::KokkosSerialWrapperNode} LO={int} GO={long long};S={long long} N={Tpetra::KokkosCompat::KokkosSerialWrapperNode} LO={int} GO={long long};S={double} N={Tpetra::KokkosCompat::KokkosSerialWrapperNode} LO={int} GO={long long}
```

I configured Trilinos the following way to test this:

```
cmake .. \
-DTRIBITS_HANDLE_TRIBITS_DEPRECATED_CODE=IGNORE \
-DCMAKE_CXX_COMPILER=mpicxx \
-DTPL_ENABLE_MPI=ON \
-DTrilinos_ENABLE_Tpetra=ON \
-DTpetra_ENABLE_DEPRECATED_CODE=OFF \
-DTpetra_INST_INT_LONG_LONG=ON \
-DTpetra_INST_INT_INT=OFF \
-DTpetra_INST_PTHREAD=OFF \
-DTrilinos_ENABLE_EXPLICIT_INSTANTIATION=ON \
-DTrilinos_ENABLE_DataTransferKit=ON \
-DDataTransferKit_ENABLE_DBC=ON \
-DDataTransferKit_ENABLE_TESTS=OFF \
-DDataTransferKit_ENABLE_EXAMPLES=OFF \
-DTrilinos_EXTRA_REPOSITORIES=DataTransferKit \
2>&1 | tee config.log
```

**Comment by cwpearson** [comment]
@tkordenbrock I just merged https://github.com/trilinos/Trilinos/pull/11700, could you report back whether that resolves your issues?

**Comment by ikalash** [comment]
Thanks @cwpearson and @cgcgcg .  Let me look into this.  It should be possible to put the patch into DTK once I reproduce the issue and figure out how to apply the patch you are proposing.

**Comment by tkordenbrock** [comment]
@cwpearson Thanks for the fix.  Our builds look good now.

@ikalash My apologies for hijacking your issue.  I should have opened a new one.

**Comment by ikalash** [comment]
No worries @tkordenbrock .  

Just to follow up, I have confirmed that the problem is the logic in DTK's CMakeLists.txt.  Unfortunately, the fix is not so simple - there are many calls to routines that no longer exist in Trilinos in DTK, which I need to fix to get the code to compile again.  I am working on this currently.

**Comment by ikalash** [comment]
I was able to get the nightlies back up by making changes to DTK.  Thanks again @cgcgcg and @cwpearson for your help in triaging the problem!
