### ISSUE TITLE
Matrix-Free in NOX

### ISSUE THREAD

**Issue by guoluanjing** [trilinos/Trilinos#1168]
Hi there,

I have used an analytic Jacobian for the conventional Newton method in NOX to solve a coupled flow, transport, and chemical reaction system. I build the system up for the purpose of using the Matrix-Free method.

After I set up the jacobian operator as Matrix-Free, tried the no-preconditioning at first ("Preconditioner Operator", "Use Jacobian"), and kept the linear solver (AztecOO/GMRES) and everything else the same. The problem I have now is that as each linear iteration goes, the solution is going towards the opposite direction. For example, the pressure value that is supposed to go up due to injection is going down, and the concentration that is supposed to go up keeps going down until negative and crashes the simulation. 

I went inside NOX and checked step by step how it is iterating. One thing that bothers me is that at the very _first_ computF call in my Problem_Interface is to evaluate the initial residual r0, but the _second_ one should be the residual evaluation based on the perturbed solution vector (u + eta*x) to evaluate the matrix-vector product **J** r0, right? Why is the solution coming out of this iteration exactly the same as the initial guess?

I would greatly appreciate any help you could provide!

Thank you,
Luanjing

**Comment by mhoemmen** [comment]
@trilinos/nox

**Comment by guoluanjing** [comment]
About the question I asked, I found out that the first `computeF()` call is due to the `NormF(NOX::Abstract::Group& initialGuess, double tolerance)` call for setting up the relative residual convergence criteria. The second one is in `MatrixFree::computeJacobian()` call to evaluate fo, the third and subsequent calls to `computeF()` are then for fp evaluations. Thus the solution vector values should not change until the third `computeF()` call.

So that question is solved. But the problem of diverging still exist when I use MatrixFree Jacobian operator to solve, while the system is solved perfectly fine with Analytical Jacobian. I was wondering if there's anything I could try to figure out what is causing the problem, e.g. information I could output, and possible reasons you or your users have found before?

Thanks a lot,
Luanjing

**Comment by rppawlo** [comment]
@guoluanjing Which back end adapters are you using with nox - epetra, stratimikos/epetra or thyra? An issue that appears often with matrix free is when the equations are poorly scaled. In that case, the perturbation in the directional derivative may not give a good approximation of the Jacobian-vector product. We usually see some progress and then stagnation so this may not be your issue. One simple test is to do a matrix vector product with the nox matrix free object and then with your analytic Jacobian and look for any differences in the result. Along these lines, when you evaluate the residual, do you perform any clipping of solution values internally? For example, when solving for temperature, you might clip negative values to keep the temperature positive or you might clip species mass fractions to keep them between zero and one. If the perturbation in JFNK takes you outside your bounds and then you clip the value to remain positive, then the Jacobian-vector product will be inaccurate.

**Comment by guoluanjing** [comment]
Hi @rppawlo , I'm using epetra with NOX. And we used to do clipping of values for mole fractions when it is outside the range of 0 to 1, but I have removed it, so not anymore.

I see divergence from the very beginning, i.e., nonlinear iteration # 0. Have not seen the issue of progress then stagnation that could be caused by poorly scaled equations. But I'm curious about what you would look for to evaluate the scales of the equations (values of solution variables or residual of equations or something else), and what to do to scale the equations.

And I'm interested in doing the test you suggested, but I can't think of a way to do it. Could you please offer some guidelines?

Thanks a lot,
Luanjing

**Comment by guoluanjing** [comment]
Hi there, 

I have two follow-up questions that are I think more specific to answer for you experts:

1. since I have analytical jacobian and initial residual vector, I could manually calculate Krylov vectors. Is there a way to output Krylov vectors from the GMRES solver under MatrixFree scheme for me to compare?

2. How could I use the setPerturbation() function in MatrixFree, i.e., where and how can I supply an `eta ` value?

Thanks!
Luanjing
