### ISSUE TITLE
Tpetra: improve performance of sortAndMergeCrsEntries

### ISSUE THREAD

**Issue by jhux2** [trilinos/Trilinos#11696]
## Enhancement
@trilinos/tpetra 

`Import_Util::sortAndMergeCrsEntries` is a hotspot when profiling transfer-and-fill-complete on device.

timer label "TAFC sortAndMergeCrsEntries"

Part of https://github.com/trilinos/Trilinos/issues/11689.

**Comment by brian-kelley** [comment]
@jhux2 Could try switching it out for
```
#include "KokkosSparse_SortCrs.hpp"
auto lclMatrixMerged = KokkosSparse::sort_and_merge_matrix(lclMatrix);
```
It looks like ``Import_Util::sortAndMergeCrsEntries`` actually runs on host sequentially so that should help a lot

**Comment by jhux2** [comment]
@brian-kelley Thank you for the suggestion!

**Comment by lucbv** [comment]
Okay after merging #11751 we should close this
