### ISSUE TITLE
New "MT Gauss-Seidel" does not seem to work from within MueLu

### ISSUE THREAD

**Issue by aprokop** [trilinos/Trilinos#117]
@trilinos/ifpack2 @srajama1 @mndevec 

In MueLu, we have a driver that allows us to run arbitrary input decks (located in muelu/test/scaling, MueLu_Driver.exe, enabled when MueLu tests are enabled). In particular, it is possible to test Ifpack2 smoothers with MueLu input deck by constructing a one level hierarchy.

I tried running the driver with the following input deck:
```xml
<ParameterList name="MueLu">
  <Parameter        name="max levels"    type="int"      value="1"/>
  <Parameter        name="coarse: type"  type="string"   value="RELAXATION"/>
  <ParameterList    name="coarse: params">
    <Parameter      name="relaxation: type"     type="string"   value="Gauss-Seidel"/>
  </ParameterList>
</ParameterList>
```
running it like this `./MueLu_Driver.exe --xml=onelevel-2_np4.xml --solver=standalone`. Here, `standalone` means use MueLu to iterate, so this is essentially a fixed point iteration solver. The result with regular Gauss-Seidel shows expected convergence:
```
 iter:    0           residual = {9.99999999999999778e-01}
 iter:    1           residual = {2.91355224068349961e-01}
 iter:    2           residual = {1.03112694566287258e-01}
 iter:    3           residual = {4.24030494030126423e-02}
 iter:    4           residual = {2.09351268542225487e-02}
 iter:    5           residual = {1.23958077884280798e-02}
 iter:    6           residual = {8.39363169782942654e-03}
 iter:    7           residual = {6.18796307752396586e-03}
 iter:    8           residual = {4.81762942015303165e-03}
 iter:    9           residual = {3.89531035831334332e-03}
 iter:    10           residual = {3.23934079863641899e-03}
```

I then changed `Gauss-Seidel` in the input deck to `MT Gauss-Seidel` and here is the result:
```
 iter:    0           residual = {9.99999999999999778e-01}
 iter:    1           residual = {9.99999999999999778e-01}
 iter:    2           residual = {9.99999999999999778e-01}
 iter:    3           residual = {9.99999999999999778e-01}
 iter:    4           residual = {9.99999999999999778e-01}
 iter:    5           residual = {9.99999999999999778e-01}
 iter:    6           residual = {9.99999999999999778e-01}
 iter:    7           residual = {9.99999999999999778e-01}
 iter:    8           residual = {9.99999999999999778e-01}
 iter:    9           residual = {9.99999999999999778e-01}
 iter:    10           residual = {9.99999999999999778e-01}
```
This is definitely not the expected behavior. Even if coloring changes the convergence, it should still converge, right?

I would be happy to work with anybody to fix this issue.

**Comment by mhoemmen** [comment]
Hi Andrey -- you have to define MD_EXPERIMENTAL in Ifpack2_Relaxation_decl.hpp, and do some other things (see Mehmet's instructions near the end).  I pointed out in Issue #85 that if MD_EXPERIMENTAL is not defined, currently Ifpack2 just does nothing, rather than erroring out.  That would explain why the residual isn't changing ;-)

**Comment by srajama1** [comment]
Too much, you filed an issue for something which is hidden from even experimental :)

Like Mark said we are hiding it until I can test multiple scenarios.

**Comment by aprokop** [comment]
> Too much, you filed an issue for something which is hidden from even experimental :)

Then shouldn't you also hide "MT Gauss-Seidel" type switches behind MD_EXPERIMENTAL? I thought it was hidden, and simply gave it a try for fun, and it ran, but produced nothing.

**Comment by srajama1** [comment]
Good point we probably should hide that too :) Will do.

**Comment by srajama1** [comment]
I should say thanks for the willingness to try it. If you are curious follow the instruction in the other issue #85 to test it.
