### ISSUE TITLE
Amesos2:  Superludist build broken when complex is disabled.

### ISSUE THREAD

**Issue by vbrunini** [trilinos/Trilinos#11716]
## Bug Report
@iyamazaki #11710 broke all of SPARC's Trilinos integration builds because we do not enable complex and the declarations of slu_dist_mult that were added are all inside an `#ifdef TEUCHOS_ENABLE_COMPLEX` but are used unconditionally.

**Comment by jhux2** [comment]
@trilinos/amesos2
