### ISSUE TITLE
MueLu: Merge AmalgamationInfo and AmalgamationInfo_kokkos

### ISSUE THREAD

**Issue by cgcgcg** [trilinos/Trilinos#11719]

**Comment by spdomin** [comment]
Looks like Nalu is hitting this error as well and our nightly tests are failing. I seem to recall @jhux2 giving me a heads up that Muelu headers would be changing, however, that was from the application interface side.

Best,

/home/spdomin/gitHubWork/scratch_build/install/gcc10.3.0/Trilinos_nightly_release/lib/libmuelu.a(ETI_MueLu_RefMaxwell.cpp.o):(.rodata._ZTVN5MueLu14FactoryManagerIdiiN6Tpetra12KokkosCompat23KokkosDeviceWrapperNodeIN6Kokkos6SerialENS4_9HostSpaceEEEEE[_ZTVN5MueLu14FactoryManagerIdiiN6Tpetra12KokkosCompat23KokkosDeviceWrapperNodeIN6Kokkos6SerialENS4_9HostSpaceEEEEE]+0x48): undefined reference to `MueLu::FactoryManager<double, int, int, Tpetra::KokkosCompat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::GetFactory(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
/home/spdomin/gitHubWork/scratch_build/install/gcc10.3.0/Trilinos_nightly_release/lib/libmuelu.a(ETI_MueLu_RefMaxwell.cpp.o):(.rodata._ZTVN5MueLu14FactoryManagerIdiiN6Tpetra12KokkosCompat23KokkosDeviceWrapperNodeIN6Kokkos6SerialENS4_9HostSpaceEEEEE[_ZTVN5MueLu14FactoryManagerIdiiN6Tpetra12KokkosCompat23KokkosDeviceWrapperNodeIN6Kokkos6SerialENS4_9HostSpaceEEEEE]+0x50): undefined reference to `MueLu::FactoryManager<double, int, int, Tpetra::KokkosCompat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::hasFactory(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
/home/spdomin/gitHubWork/scratch_build/install/gcc10.3.0/Trilinos_nightly_release/lib/libmuelu.a(ETI_MueLu_RefMaxwell.cpp.o):(.rodata._ZTVN5MueLu26AmalgamationFactory_kokkosIdiiN6Tpetra12KokkosCompat23KokkosDeviceWrapperNodeIN6Kokkos6SerialENS4_9HostSpaceEEEEE[_ZTVN5MueLu26AmalgamationFactory_kokkosIdiiN6Tpetra12KokkosCompat23KokkosDeviceWrapperNodeIN6Kokkos6SerialENS4_9HostSpaceEEEEE]+0x58): undefined reference to `MueLu::AmalgamationFactory_kokkos<double, int, int, Tpetra::KokkosCompat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::GetValidParameterList() const'
/home/spdomin/gitHubWork/scratch_build/install/gcc10.3.0/Trilinos_nightly_release/lib/libmuelu.a(ETI_MueLu_RefMaxwell.cpp.o):(.rodata._ZTVN5MueLu26AmalgamationFactory_kokkosIdiiN6Tpetra12KokkosCompat23KokkosDeviceWrapperNodeIN6Kokkos6SerialENS4_9HostSpaceEEEEE[_ZTVN5MueLu26AmalgamationFactory_kokkosIdiiN6Tpetra12KokkosCompat23KokkosDeviceWrapperNodeIN6Kokkos6SerialENS4_9HostSpaceEEEEE]+0x60): undefined reference to `MueLu::AmalgamationFactory_kokkos<double, int, int, Tpetra::KokkosCompat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::DeclareInput(MueLu::Level&) const'
/home/spdomin/gitHubWork/scratch_build/install/gcc10.3.0/Trilinos_nightly_release/lib/libmuelu.a(ETI_MueLu_RefMaxwell.cpp.o):(.rodata._ZTVN5MueLu26AmalgamationFactory_kokkosIdiiN6Tpetra12KokkosCompat23KokkosDeviceWrapperNodeIN6Kokkos6SerialENS4_9HostSpaceEEEEE[_ZTVN5MueLu26AmalgamationFactory_kokkosIdiiN6Tpetra12KokkosCompat23KokkosDeviceWrapperNodeIN6Kokkos6SerialENS4_9HostSpaceEEEEE]+0x68): undefined reference to `MueLu::AmalgamationFactory_kokkos<double, int, int, Tpetra::KokkosCompat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::Build(MueLu::Level&) const'
/home/spdomin/gitHubWork/scratch_build/install/gcc10.3.0/Trilinos_nightly_release/lib/libmuelu.a(ETI_MueLu_RefMaxwell.cpp.o):(.rodata._ZTVN5MueLu26AmalgamationFactory_kokkosIdiiN6Tpetra12KokkosCompat23KokkosDeviceWrapperNodeIN6Kokkos6SerialENS4_9HostSpaceEEEEE[_ZTVN5MueLu26AmalgamationFactory_kokkosIdiiN6Tpetra12KokkosCompat23KokkosDeviceWrapperNodeIN6Kokkos6SerialENS4_9HostSpaceEEEEE]+0xc0): undefined reference to `non-virtual thunk to MueLu::AmalgamationFactory_kokkos<double, int, int, Tpetra::KokkosCompat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::GetValidParameterList() const'
/home/spdomin/gitHubWork/scratch_build/install/gcc10.3.0/Trilinos_nightly_release/lib/libmuelu.a(ETI_MueLu_RefMaxwell.cpp.o):(.rodata._ZTVN5MueLu19AmalgamationFactoryIdiiN6Tpetra12KokkosCompat23KokkosDeviceWrapperNodeIN6Kokkos6SerialENS4_9HostSpaceEEEEE[_ZTVN5MueLu19AmalgamationFactoryIdiiN6Tpetra12KokkosCompat23KokkosDeviceWrapperNodeIN6Kokkos6SerialENS4_9HostSpaceEEEEE]+0x58): undefined reference to `MueLu::AmalgamationFactory<double, int, int, Tpetra::KokkosCompat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::GetValidParameterList() const'
/home/spdomin/gitHubWork/scratch_build/install/gcc10.3.0/Trilinos_nightly_release/lib/libmuelu.a(ETI_MueLu_RefMaxwell.cpp.o):(.rodata._ZTVN5MueLu19AmalgamationFactoryIdiiN6Tpetra12KokkosCompat23KokkosDeviceWrapperNodeIN6Kokkos6SerialENS4_9HostSpaceEEEEE[_ZTVN5MueLu19AmalgamationFactoryIdiiN6Tpetra12KokkosCompat23KokkosDeviceWrapperNodeIN6Kokkos6SerialENS4_9HostSpaceEEEEE]+0x60): undefined reference to `MueLu::AmalgamationFactory<double, int, int, Tpetra::KokkosCompat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::DeclareInput(MueLu::Level&) const'
/home/spdomin/gitHubWork/scratch_build/install/gcc10.3.0/Trilinos_nightly_release/lib/libmuelu.a(ETI_MueLu_RefMaxwell.cpp.o):(.rodata._ZTVN5MueLu19AmalgamationFactoryIdiiN6Tpetra12KokkosCompat23KokkosDeviceWrapperNodeIN6Kokkos6SerialENS4_9HostSpaceEEEEE[_ZTVN5MueLu19AmalgamationFactoryIdiiN6Tpetra12KokkosCompat23KokkosDeviceWrapperNodeIN6Kokkos6SerialENS4_9HostSpaceEEEEE]+0x68): undefined reference to `MueLu::AmalgamationFactory<double, int, int, Tpetra::KokkosCompat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::Build(MueLu::Level&) const'
/home/spdomin/gitHubWork/scratch_build/install/gcc10.3.0/Trilinos_nightly_release/lib/libmuelu.a(ETI_MueLu_RefMaxwell.cpp.o):(.rodata._ZTVN5MueLu19AmalgamationFactoryIdiiN6Tpetra12KokkosCompat23KokkosDeviceWrapperNodeIN6Kokkos6SerialENS4_9HostSpaceEEEEE[_ZTVN5MueLu19AmalgamationFactoryIdiiN6Tpetra12KokkosCompat23KokkosDeviceWrapperNodeIN6Kokkos6SerialENS4_9HostSpaceEEEEE]+0xc0): undefined reference to `non-virtual thunk to MueLu::AmalgamationFactory<double, int, int, Tpetra::KokkosCompat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::GetValidParameterList() const'

**Comment by cgcgcg** [comment]
@spdomin This PR hasn't merged yet, so I don't think it's causing the issues you are seeing ;-)
Can you point me to your build script?

**Comment by spdomin** [comment]
We are using this - mostly:

https://github.com/NaluCFD/Nalu/blob/master/build/do-configTrilinos_release

However, our nightly adds:

< -DTrilinos_ENABLE_Stratimikos:BOOL=OFF \
< -DTrilinos_ENABLE_Thyra:BOOL=OFF \

Thanks for any guidance..
