### ISSUE TITLE
Amesos2 Epetra and Tpetra adapter tests fail

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#1172]
@trilinos/amesos2 

There are a few builds on the dashboard where Amesos2's Epetra and Tpetra adapter tests fail.  They appear to include MPI and non-MPI, as well as DEBUG and RELEASE.

http://testing.sandia.gov/cdash/viewTest.php?onlyfailed&buildid=2797397
http://testing.sandia.gov/cdash/viewTest.php?onlyfailed&buildid=2798217
http://testing.sandia.gov/cdash/viewTest.php?onlyfailed&buildid=2798091

From examining the test output, it looks like the tests print pass output on Process 0, but the global all-reduce at the end of the test catches some problem on other process(es).

**Comment by ndellingwood** [comment]
Closing since dashboard has been clean for these tests, fixed by sha1 bab8b66393e97c632d9530b8fb38d69bf6abdc2b
