### ISSUE TITLE
Kokkos: Wrong CMake package compatibility mode

### ISSUE THREAD

**Issue by masterleinad** [trilinos/Trilinos#11725]
## Bug Report
We discovered in https://github.com/kokkos/kokkos/pull/6012 that we missed updating the compatibility mode in https://github.com/kokkos/kokkos/pull/5759 which means that the Kokkos package in Trilinos 14.0.0 would not be recognized if users asked for Kokkos versions prior to 4.0.00 such as
```
find_package(Kokkos 3.7) 
```

https://github.com/kokkos/kokkos/pull/6012 fixes this and the fix will be cherry-picked in https://github.com/kokkos/kokkos/pull/6013 which should be part of Kokkos 4.0.01 (will be merged into `Trilinos` when released).

**Comment by ccober6** [comment]
@sebrowne , we should also get this on the Trilinos 14.0 branch.

**Comment by sebrowne** [comment]
@ccober6 I can do that once Kokkos 4.0.01 is in.

**Comment by masterleinad** [comment]
> @ccober6 I can do that once Kokkos 4.0.01 is in.

`Kokkos 4.0.01` will contain a patch anyway. Of course, there are some more places in `Trilinnos` that would have a similar problem:

> $ git grep -n " COMPATIBILITY " | grep "SameMajorVersion"
cmake/tribits/core/package_arch/TribitsProjectWriteConfigFile.cmake:221:    COMPATIBILITY SameMajorVersion
packages/compadre/cmake/bob.cmake:670:        COMPATIBILITY SameMajorVersion)
packages/compadre/cmake/bob.cmake:765:        COMPATIBILITY SameMajorVersion)
