### ISSUE TITLE
Amesos2 KLU2 test fails

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#1173]
@trilinos/amesos2 

The Amesos2 KLU2 test fails on one test build:

http://testing.sandia.gov/cdash/viewTest.php?onlyfailed&buildid=2797397

It looks like the test prints pass output on Process 0, but fails on one or more other processes.  The global all-reduce at the end of the test catches this.

**Comment by ndellingwood** [comment]
Fixed with commit e31b14c8cc83787ff4b8d9849f7bd1d0a735d055, closing the issue.
