### ISSUE TITLE
Kokkos:  Snapshot SHA1 does not exist in Kokkos repo

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#11752]
## Bug Report

@trilinos/kokkos, @ndellingwood 

### Description

While trying to apply the Kokkos-specific commits from Trilinos PR:

* #11546 

to the native Kokkos repo, it seems that the Kokkos repo SHA1 reported in the last snasphsot commit 99eb69cae7cc9733efc7d7315aedfeb9d145fcbd reported as `feb2394320809032a1b4570a5cfd78c6910e6f86` in the commit message

```
commit 99eb69cae7cc9733efc7d7315aedfeb9d145fcbd
Author: Nathan Ellingwood <ndellin@sandia.gov>
Date:   Thu Feb 23 21:19:20 2023 -0700

    Snapshot of kokkos.git from commit feb2394320809032a1b4570a5cfd78c6910e6f86
    
    From repository at git@github.com:kokkos/kokkos.git
    
    At commit:
    commit feb2394320809032a1b4570a5cfd78c6910e6f86
    Author: Nathan Ellingwood <ndellin@sandia.gov>
    Date:   Thu Feb 23 21:17:22 2023 -0700
    
        kokkos: enable deprecated code 3 by default in Trilinos
    
        Temporarily needed to support deprecated code usage in Trilinos
```

does not actually exist in the Kokkos GitHub repo.

For example, when I do:

```
$ cd kokkos/

$ git status
On branch develop
Your branch is up to date with 'github/develop'.

$ git remote -v | grep "^github"
github  git@github.com:kokkos/kokkos.git (fetch)
github  git@github.com:kokkos/kokkos.git (push)

$ git fetch github

$ git log-short --name-status -1 github/develop
fdb089b34 "Add UnorderedMapInsertOps for coo2crs (#5877)"
Author: Evan Harvey <57234914+e10harvey@users.noreply.github.com>
Date:   Thu Mar 30 07:04:37 2023 -0600 (30 hours ago)

M       containers/src/Kokkos_UnorderedMap.hpp
M       containers/unit_tests/TestUnorderedMap.hpp
nothing to commit, working tree clean
```

there is not Kokkos commit `feb2394320809032a1b4570a5cfd78c6910e6f86`:

```
$ git log-short --name-status feb2394320809032a1b4570a5cfd78c6910e6f86
fatal: bad object feb2394320809032a1b4570a5cfd78c6910e6f86
```

Because if it, it is not straightforward to use git format-patch and git am to being commits over from Trilinos to Kokkos.

The rule with snapshotting is that the commit SHA1 for the top commit in your repo must exist in a long-term branch in the main git repo.  If that is not the case, then don't do the snapshot commit until you have that commit.

**Comment by bartlettroscoe** [comment]
NOTE: Even a rebased commit with that same summary message does not even exist:

```
$ cd kokkos/

$ git remote -v | grep "^github"
github  git@github.com:kokkos/kokkos.git (fetch)
github  git@github.com:kokkos/kokkos.git (push)

$ git log-short --name-status --grep="kokkos: enable deprecated code 3 by default in Trilinos"
[empty]
```

Therefore, I have no idea what version of Kokkos actually corresponds to what was snapshotted in the commit 99eb69cae7cc9733efc7d7315aedfeb9d145fcbd.

So to find out exactly, I will need to manually compare the kokkos files I modified in Trilinos PR:

* #11546

as of commit 99eb69cae7cc9733efc7d7315aedfeb9d145fcbd to try to find an acceptable commit for which to create a branch to use 'git am' to apply the commits from Trilinos (pulled off with `git format-patch').

**Comment by ndellingwood** [comment]
@bartlettroscoe I made a mistake during the snapshot process; to accommodate some unresolved deprecated code usage in Trilinos we set Kokkos_ENABLE_DEPRECATED_CODE_3 on by default for Trilinos, but not in the Kokkos standalone release.
The mistake I made is that I applied that change to kokkos at kokkos/kokkos@606866d47dfb2365a0352bdadfbc1ca2ec51d5a3 (which is on the master branch of the repo) before snapshotting to Trilinos, which included the local change you see in the sha (but untracked in the kokkos repo).
I should have made this change to Trilinos after the snapshot of kokkos, which should have been snapshot from kokkos/kokkos@606866d47dfb2365a0352bdadfbc1ca2ec51d5a3.
Sorry for the mistake and the confusion this caused

**Comment by bartlettroscoe** [comment]
> The mistake I made is that I applied that change to kokkos at https://github.com/kokkos/kokkos/commit/606866d47dfb2365a0352bdadfbc1ca2ec51d5a3 (which is on the master branch of the repo) before snapshotting to Trilinos, which included the local change you see in the sha (but untracked in the kokkos repo).

@ndellingwood, it is fine to do any workflow you want.  The snapshot workflow is very flexible.  The only hard and fast rule is that that commit in the orig repo being snapshotted needs to be pushed to a long-lived branch in the main git repo.

I am wondering if we should extend the snapshotting process to assert that that is the case?  (E.g. you could check that a commit with that SHA1 exists in the remote tracking branch.  That is not a guarantee that someone will not delete the remote branch in the main repo but that would catch some of these instances.)
