### ISSUE TITLE
Analysis of configure and build failures due to KokkosKernels pushes on March 1-2 reported in #1099

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#1176]
**Description:**

This story is to analyze the KokkosKernels commits pushed on March 1-2, 2017 that broke the configure and build of Trilinos that was reported in #1099 and see if usage of the [checkin-test-sems.sh](https://github.com/trilinos/Trilinos/wiki/Policies-%7C-Safe-Checkin-Testing) script could have avoided the failures (and resulting consequences) if it had been used for the test and push (which would have stopped the push).

This started when a set of commits were pushed to the Trilinos 'develop' branch on March 1 with the top commit 97ed757 being:

```
97ed757 [Wed Mar 1 08:24:01 2017 -0700] <crtrott@sandia.gov>
Kokkos-Kernels: Adding Kokkos-Kernels as a stand-alone package
```

as shown by the CI build:

* http://testing.sandia.gov/cdash/viewConfigure.php?buildid=2766164

That version of Trilinos failed to configure as shown on that CI build iteration.

Later that day, issue #1099 was created by an important Trilinos customer and it resulted in 35 comments that involved 9 people in that issue before it was resolved.

An attempt to fix this problem was pushed later that day with the top commit de7ac5a being:

```
de7ac5a [Wed Mar 1 13:17:16 2017 -0700] <mhoemme@sandia.gov>
KokkosKernels: Fix #1099
```

as shown by the CI build:

* http://testing.sandia.gov/cdash/viewConfigure.php?buildid=2766462

That version passed the configure but resulted in many build failures.

The build was not finally fixed until March 2 as shown at:

* http://testing.sandia.gov/cdash/viewConfigure.php?buildid=2767860

Could the usage of the checkin-test-sems.sh script have caught these problems and stop the pushes that broke the configure and build of Trilinos over these two days?

**CC:** @trilinos/framework, @bathmatt, @crtrott, @mhoemmen

**Comment by bartlettroscoe** [comment]
As described below, the [checkin-test-sems.sh](https://github.com/trilinos/Trilinos/wiki/Policies-%7C-Safe-Checkin-Testing) script produced the exact same configure and build failures shown for the standard CI build for the pushed Trilinos versions 97ed757 and de7ac5a.  Therefore, if the checkin-test-sems.sh script had been used to test and push these versions, then the pushes would have been stoppped and developers and customers pulling from the Trilinos 'develop' branch would not have experienced these failures and issue #1099 would have never of been created.

----

**DETAILED NOTES:**

**(2017/03/23)**

To see if usage of the checkin-test-sems.sh script could have caught these failures before pushing to the 'develop' branch, I will use the SEMS env on the standard CEE LAN machine ceerws1113 with the standard checkin-test-sems.sh script at that time (which is version controlled in Trilinos).  First, to reproduce the CI build with the commit 97ed757 I do:

```
$ ssh ceerws1113

$ cd /scratch/rabartl/Trilinos.base/Trilinos/
$ git fetch
$ git checkout 97ed757

$ cd /scratch/rabartl/Trilinos.base/BUILDS/CHECKIN
$ ./checkin-test-sems.sh \
  --enable-all-packages=off --enable-packages=KokkosKernels \
  --local-do-all
```

This existed in under 2 minutes and showed a failed configure:

```
FAILED CONFIGURE/BUILD/TEST: Trilinos: ceerws1113

Fri Mar 17 10:22:39 MDT 2017

Enabled Packages: KokkosKernels
Disabled Packages: PyTrilinos,Claps,TriKota
Enabled all Forward Packages

Build test results:
-------------------
0) MPI_RELEASE_DEBUG_SHARED_PT => FAILED: configure failed => Not ready to push! (1.33 min)
```

The configure output in the file:

```
/scratch/rabartl/Trilinos.base/BUILDS/CHECKIN/MPI_RELEASE_DEBUG_SHARED_PT/configure.out
```

showed:

```
Processing enabled package: KokkosKernels (Libs, Tests, Examples)
CMake Error at packages/kokkos-kernels/CMakeLists.txt:46 (TRIBITS_ADD_OPTION_AND_DEFINE):
  TRIBITS_ADD_OPTION_AND_DEFINE Macro invoked with incorrect arguments for
  macro named: TRIBITS_ADD_OPTION_AND_DEFINE
```

That is exactly the same configure error showed at:

* http://testing.sandia.gov/cdash/viewConfigure.php?buildid=2766164

Now what about the commit de7ac5a that tried to fix this?  Would the checkin-test-sems.sh script have detected the build failures associated with this?  Trying this out:

```
$ ssh ceerws1113

$ cd /scratch/rabartl/Trilinos.base/Trilinos/
$ git fetch
$ git checkout de7ac5a

$ cd /scratch/rabartl/Trilinos.base/BUILDS/CHECKIN
$ ./checkin-test-sems.sh \
  --enable-all-packages=off --enable-packages=KokkosKernels \
  --local-do-all
```

This exited in under 4 minutes and it showed build failures:

```
FAILED CONFIGURE/BUILD/TEST: Trilinos: ceerws1113

Fri Mar 17 10:37:08 MDT 2017

Enabled Packages: KokkosKernels
Disabled Packages: PyTrilinos,Claps,TriKota
Enabled all Forward Packages

Build test results:
-------------------
0) MPI_RELEASE_DEBUG_SHARED_PT => FAILED: build failed => Not ready to push! (3.96 min)
```

The build output in the file:

```
/scratch/rabartl/Trilinos.base/BUILDS/CHECKIN/MPI_RELEASE_DEBUG_SHARED_PT/make.out
```

showed errors like:

```
In file included from /scratch/rabartl/Trilinos.base/Trilinos/packages/kokkos-kernels/src/impl/Kokkos_Sparse_impl_spmv.hpp:47:0,
                 from /scratch/rabartl/Trilinos.base/Trilinos/packages/kokkos-kernels/src/Kokkos_Sparse.hpp:63,
                 from /scratch/rabartl/Trilinos.base/Trilinos/packages/kokkos-kernels/src/impl/Kokkos_Sparse_V_impl_spmv_OpenMP_integers.cpp:47:
/scratch/rabartl/Trilinos.base/Trilinos/packages/kokkos-kernels/src/impl/Kokkos_Sparse_impl_spmv_decl.hpp:227:1: error: ‘Threads’ is not a member of ‘Kokkos’
/scratch/rabartl/Trilinos.base/Trilinos/packages/kokkos-kernels/src/impl/Kokkos_Sparse_impl_spmv_decl.hpp:227:1: error: ‘Threads’ is not a member of ‘Kokkos’
/scratch/rabartl/Trilinos.base/Trilinos/packages/kokkos-kernels/src/impl/Kokkos_Sparse_impl_spmv_decl.hpp:227:1: error: template argument 1 is invalid
/scratch/rabartl/Trilinos.base/Trilinos/packages/kokkos-kernels/src/impl/Kokkos_Sparse_impl_spmv_decl.hpp:227:1: error: invalid type in declaration before ‘;’ token
/scratch/rabartl/Trilinos.base/Trilinos/packages/kokkos-kernels/src/impl/Kokkos_Sparse_impl_spmv_decl.hpp:227:1: error: ‘OpenMP’ is not a member of ‘Kokkos’
/scratch/rabartl/Trilinos.base/Trilinos/packages/kokkos-kernels/src/impl/Kokkos_Sparse_impl_spmv_decl.hpp:227:1: error: ‘OpenMP’ is not a member of ‘Kokkos’
...
```

These are the exact same failures you see, for example, at:

* http://testing.sandia.gov/cdash/viewBuildError.php?buildid=2766462

**Comment by mhoemmen** [comment]
Another general lesson might be "pushing major changes during SIAM CSE[, Supercomputing, etc.] is suboptimal" ;-)

**Comment by bartlettroscoe** [comment]
NOTE: The usage of the checkin-test-sems.sh script from another machine should be much easier now that there is a simplified process for developing on your local machine (e.g. a Mac OSX laptop) but then use a SNL COE Linux RHEL 6 machine to do the test and push.  See:

* https://github.com/trilinos/Trilinos/wiki/Local-development-with-remote-pull%2C-test%2C-and-push

I will be happy to sit down (in person or virtually) to help anyone set this up and try this out.  It should only take 20 minutes of that person's time to set this up.  The using it is just a single script invocation from your local machine and the rest is automatic.  Just let me know.
