### ISSUE TITLE
Trilinos config question on Intel: infamous missing dlarnd_ A::theFunction()

### ISSUE THREAD

**Issue by spdomin** [trilinos/Trilinos#11786]
## Question
Greetings,

I know this seems like an old issue, however, I am hitting an error in my Intel-based Trilinos config (see below two errors and Trilinos config).

The short story is that I am finding a segfault on Intel 21.3.0 modules, so I moved to a production "cde-based" set of modules (including an HDF5, NetCDF, etc. builds) that are using intel-2021.1.2 and openmpi 4.1.2. Since the segfault seemed to be a NetCDF issue, I wanted to remove any uncertainty in my builds (even though I have been building these TPLS for many years). 

In reality, my Intel builds of nalu have been broken since the big jump from Intel 19 to the 21 version.

The config error appears below. I found an old Trilinos line of discussion on this issue five years ago, https://gitlab.osti.gov/jmwille/Trilinos/-/issues/2005 that was resolved - seemingly - by removing a dependency. However, the resolution seemed to be quite jumpy in nature and reverted to some removal of code in Trilinos that LAPACK had deprecated. Yet, here I am:)

Does anyone have a particular fix for this?

# My config file:

mpi_base_dir=/projects/cde/v3/2023-03/x86_64/spack/opt/spack/linux-rhel7-x86_64/intel-2021.1.2/openmpi-4.1.2-x4uzz3imuajfbw6uz4yhcyrua6j5pub7
nalu_install_dir=/projects/netpub/nalu/scratch_build/install/intel-21.1.2_4.1.2_cde

netcdf_install_dir=/cde/v3/netcdf-c/4.8.1-intel-2021.1.2-openmpi-4.1.2
hdf_install_dir=cde/v3/hdf5/1.10.6-intel-2021.1.2-openmpi-4.1.2
pnetcdf_install_dir=cde/v3/parallel-netcdf/1.12.2-intel-2021.1.2-openmpi-4.1.2

trilinos_install_dir=$nalu_install_dir/Trilinos_stable_release

echo "nalu_install_dir = \"$nalu_install_dir\""

EXTRA_ARGS=$@

find . -name "CMakeFiles" -exec rm -rf {} \;
rm -f CMakeCache.txt

cmake \
-DCMAKE_INSTALL_PREFIX=$trilinos_install_dir \
-DTrilinos_ENABLE_CXX11=ON \
-DCMAKE_BUILD_TYPE=RELEASE \
-DTrilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON \
-DTpetra_INST_DOUBLE:BOOL=ON \
-DTpetra_INST_INT_LONG:BOOL=ON \
-DTpetra_INST_INT_LONG_LONG:BOOL=OFF \
-DTpetra_INST_COMPLEX_DOUBLE=OFF \
-DTrilinos_ENABLE_TESTS:BOOL=OFF \
-DTrilinos_ENABLE_ALL_OPTIONAL_PACKAGES=OFF \
-DTrilinos_ALLOW_NO_PACKAGES:BOOL=OFF \
-DTPL_ENABLE_MPI=ON \
  -DMPI_BASE_DIR:PATH=$mpi_base_dir \
-DTPL_ENABLE_SuperLU=OFF \
-DTrilinos_ENABLE_Epetra:BOOL=OFF \
-DTrilinos_ENABLE_Tpetra:BOOL=ON \
-DTrilinos_ENABLE_ML:BOOL=OFF \
-DTrilinos_ENABLE_MueLu:BOOL=ON \
-DTrilinos_ENABLE_EpetraExt:BOOL=OFF \
-DTrilinos_ENABLE_AztecOO:BOOL=OFF \
-DTrilinos_ENABLE_Belos:BOOL=ON \
-DTrilinos_ENABLE_Ifpack2:BOOL=ON \
-DTrilinos_ENABLE_Amesos2:BOOL=ON \
-DTrilinos_ENABLE_Zoltan2:BOOL=ON \
-DTrilinos_ENABLE_Ifpack:BOOL=OFF \
-DTrilinos_ENABLE_Amesos:BOOL=OFF \
-DTrilinos_ENABLE_Zoltan:BOOL=ON \
-DTrilinos_ENABLE_STKMesh:BOOL=ON \
-DTrilinos_ENABLE_STKSimd:BOOL=ON \
-DTrilinos_ENABLE_STKIO:BOOL=ON \
-DTrilinos_ENABLE_STKTransfer:BOOL=ON \
-DTrilinos_ENABLE_STKSearch:BOOL=ON \
-DTrilinos_ENABLE_STKUtil:BOOL=ON \
-DTrilinos_ENABLE_STKTopology:BOOL=ON \
-DTrilinos_ENABLE_STKBalance:BOOL=OFF \
-DTPL_ENABLE_BoostLib:BOOL=OFF \
-DTrilinos_ENABLE_STKUnit_tests:BOOL=OFF \
-DTrilinos_ENABLE_STKUnit_test_utils:BOOL=OFF \
-DTrilinos_ENABLE_Gtest:BOOL=ON \
-DTrilinos_ENABLE_SEACASExodus:BOOL=ON \
-DTrilinos_ENABLE_SEACASEpu:BOOL=ON \
-DTrilinos_ENABLE_SEACASExodiff:BOOL=ON \
-DTrilinos_ENABLE_SEACASNemspread:BOOL=ON \
-DTrilinos_ENABLE_SEACASNemslice:BOOL=ON \
-DTrilinos_ENABLE_SEACASIoss:BOOL=ON \
-DTPL_ENABLE_Netcdf:BOOL=ON \
-DNetCDF_ROOT:PATH=${netcdf_install_dir} \
-DHDF5_ROOT:PATH=${hdf_install_dir} \
-DHDF5_NO_SYSTEM_PATHS=ON \
-DPNetCDF_ROOT:PATH=${pnetcdf_install_dir} \
$EXTRA_ARGS \
../

# My Modules:

  1) cde/v3/hdf5/1.10.6-intel-2021.1.2-openmpi-4.1.2              6) cde/v3/cmake/3.23.1
  2) cde/v3/netcdf-c/4.8.1-intel-2021.1.2-openmpi-4.1.2           7) cde/v3/ninja/1.10.2
  3) cde/v3/openmpi/4.1.2-intel-2021.1.2                          8) cde/v3/gcc/10.3.0
  4) cde/v3/parallel-netcdf/1.12.2-intel-2021.1.2-openmpi-4.1.2   9) cde/v3/anaconda3/2021.05
  5) cde/v3/netlib-lapack/3.10.1-intel-2021.1.2

# Errors

Run Build Command(s):/usr/bin/gmake -f Makefile cmTC_1aa7b/fast && /usr/bin/gmake  -f CMakeFiles/cmTC_1aa7b.dir/build.make CMakeFiles/cmTC_1aa7b.dir/build
gmake[1]: Entering directory `/projects/netpub/nalu/scratch_build/packages/Trilinos/build_stable_release_intel-21.1.2_cde/CMakeFiles/CMakeTmp'
Building CXX object CMakeFiles/cmTC_1aa7b.dir/src.cxx.o
/projects/cde/v3/2023-03/x86_64/spack/opt/spack/linux-rhel7-x86_64/intel-2021.1.2/openmpi-4.1.2-x4uzz3imuajfbw6uz4yhcyrua6j5pub7/bin/mpicxx -DHAVE_TEUCHOS_LAPACKLARND  -O3 -DNDEBUG -std=c++17 -MD -MT CMakeFiles/cmTC_1aa7b.dir/src.cxx.o -MF CMakeFiles/cmTC_1aa7b.dir/src.cxx.o.d -o CMakeFiles/cmTC_1aa7b.dir/src.cxx.o -c /projects/netpub/nalu/scratch_build/packages/Trilinos/build_stable_release_intel-21.1.2_cde/CMakeFiles/CMakeTmp/src.cxx
Linking CXX executable cmTC_1aa7b
/projects/cde/v3/2023-03/x86_64/spack/opt/spack/linux-rhel7-x86_64/gcc-10.3.0/cmake-3.23.1-ty5e4oygo6foldcbvcpqem5ff3ouagz5/bin/cmake -E cmake_link_script CMakeFiles/cmTC_1aa7b.dir/link.txt --verbose=1
/projects/cde/v3/2023-03/x86_64/spack/opt/spack/linux-rhel7-x86_64/intel-2021.1.2/openmpi-4.1.2-x4uzz3imuajfbw6uz4yhcyrua6j5pub7/bin/mpicxx -O3 -DNDEBUG CMakeFiles/cmTC_1aa7b.dir/src.cxx.o -o cmTC_1aa7b  /projects/cde/v3/2023-03/x86_64/spack/opt/spack/linux-rhel7-x86_64/intel-2021.1.2/netlib-lapack-3.10.1-3v37xopgetk7ubgyctzfpzjrk5tckvkg/lib64/liblapack.so
CMakeFiles/cmTC_1aa7b.dir/src.cxx.o: In function `main':
src.cxx:(.text+0x42): undefined reference to `dlarnd_'
gmake[1]: *** [cmTC_1aa7b] Error 1
gmake[1]: Leaving directory `/projects/netpub/nalu/scratch_build/packages/Trilinos/build_stable_release_intel-21.1.2_cde/CMakeFiles/CMakeTmp'
gmake: *** [cmTC_1aa7b/fast] Error 2

...and run output:

Return value: 1
Source file was:

#define F77_BLAS_MANGLE(name,NAME) name ## _

#define DLARND_F77   F77_BLAS_MANGLE(dlarnd,DLARND)

extern "C" { double DLARND_F77(const int* idist, int* seed); }

int main()
{

  const int idist = 1;
  int seed[4] = { 0, 0, 0, 1 };

  double val = DLARND_F77(&idist, seed);

  return (val < 0.0 ? 1 : 0);

}

Performing C++ SOURCE FILE Test HAVE_CXX_PRAGMA_WEAK failed with the following output:
Change Dir: /projects/netpub/nalu/scratch_build/packages/Trilinos/build_stable_release_intel-21.1.2_cde/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/gmake -f Makefile cmTC_82714/fast && /usr/bin/gmake  -f CMakeFiles/cmTC_82714.dir/build.make CMakeFiles/cmTC_82714.dir/build
gmake[1]: Entering directory `/projects/netpub/nalu/scratch_build/packages/Trilinos/build_stable_release_intel-21.1.2_cde/CMakeFiles/CMakeTmp'
Building CXX object CMakeFiles/cmTC_82714.dir/src.cxx.o
/projects/cde/v3/2023-03/x86_64/spack/opt/spack/linux-rhel7-x86_64/intel-2021.1.2/openmpi-4.1.2-x4uzz3imuajfbw6uz4yhcyrua6j5pub7/bin/mpicxx -DHAVE_CXX_PRAGMA_WEAK  -O3 -DNDEBUG -std=c++17 -MD -MT CMakeFiles/cmTC_82714.dir/src.cxx.o -MF CMakeFiles/cmTC_82714.dir/src.cxx.o.d -o CMakeFiles/cmTC_82714.dir/src.cxx.o -c /projects/netpub/nalu/scratch_build/packages/Trilinos/build_stable_release_intel-21.1.2_cde/CMakeFiles/CMakeTmp/src.cxx
Linking CXX executable cmTC_82714
/projects/cde/v3/2023-03/x86_64/spack/opt/spack/linux-rhel7-x86_64/gcc-10.3.0/cmake-3.23.1-ty5e4oygo6foldcbvcpqem5ff3ouagz5/bin/cmake -E cmake_link_script CMakeFiles/cmTC_82714.dir/link.txt --verbose=1
/projects/cde/v3/2023-03/x86_64/spack/opt/spack/linux-rhel7-x86_64/intel-2021.1.2/openmpi-4.1.2-x4uzz3imuajfbw6uz4yhcyrua6j5pub7/bin/mpicxx -O3 -DNDEBUG CMakeFiles/cmTC_82714.dir/src.cxx.o -o cmTC_82714
CMakeFiles/cmTC_82714.dir/src.cxx.o: In function `main':
src.cxx:(.text+0x47): undefined reference to `A::theFunction()'
gmake[1]: *** [cmTC_82714] Error 1
gmake[1]: Leaving directory `/projects/netpub/nalu/scratch_build/packages/Trilinos/build_stable_release_intel-21.1.2_cde/CMakeFiles/CMakeTmp'
gmake: *** [cmTC_82714/fast] Error 2

Source file was:

#include <iostream>

namespace A {
// theFunction never gets defined, because we
// don't link with a library that defines it.
// That's OK, because it's weak linkage.
#pragma weak theFunction
extern void theFunction ();
}

int main() {
  std::cout << "Hi!  I am main." << std::endl;
  if (A::theFunction != NULL) {
    // Should never be called, since we don't link
    // with a library that defines A::theFunction.
    A::theFunction ();
  }
  return 0;
}

**Comment by jhux2** [comment]
@trilinos/framework

**Comment by sebrowne** [comment]
I've seen this before, and I can't remember off the top of my head how to fix it.  I'll try to take a look at it early this coming week.

**Comment by spdomin** [comment]
Much appreciated.
