### ISSUE TITLE
STK:  With BulkData's public Constructor being deprecated, what is the desired method for constructing a new BulkData instance?

### ISSUE THREAD

**Issue by palmerb4** [trilinos/Trilinos#11792]
@trilinos/STK @alanw0 

As the title states, I noticed that BulkData's detailed public constructor is listed as deprecated and should have been deleted quite some time ago.
```
#ifndef STK_HIDE_DEPRECATED_CODE // Delete after August 2022
  /** \brief  Construct mesh bulk data manager conformal to the given
   *          \ref stk::mesh::MetaData "meta data manager" and will
   *          distribute bulk data over the given parallel machine.
   *
   *  - The maximum number of entities per bucket may be supplied.
   *  - The bulk data is in the synchronized or "locked" state.
   */
  STK_DEPRECATED BulkData(   MetaData & mesh_meta_data
            , ParallelMachine parallel
            , enum AutomaticAuraOption auto_aura_option = AUTO_AURA
#ifdef SIERRA_MIGRATION
            , bool add_fmwk_data = false
#endif
            , FieldDataManager *field_dataManager = nullptr
            , unsigned bucket_capacity = impl::BucketRepository::default_bucket_capacity
            );
#endif
```
However, this is the constructor used by stk::mesh::MeshBuilder to construct the BulkData instance. So if this constructor is being deprecated, what alternative method should users now use to build BulkData? I couldn't find an answer to this question either in the STK Manual V 5.1.9 or in Nalu-wind's source code (nalu appears to also use MeshBuilder). 

Best,
Bryce

**Comment by alanw0** [comment]
Hi @palmerb4, thanks for this question. In fact MeshBuilder uses BulkData's other constructor, which is a protected method, (the one that takes MetaData as a shared_ptr), and which is not being deprecated.
I think that version 5.1.9 of the manual pre-dates MeshBuilder. We will put out an updated manual soon that documents MeshBuilder.
MeshBuilder is indeed the preferred way to create instances of BulkData.

We decided to create MeshBuilder, and correspondingly deprecate public direct construction of BulkData, to give us more freedom to potentially create specializations (derived classes) of BulkData for specialized use-cases, specialized performance optimizations etc., without requiring users to choose from, or know about, those derived classes.

Correspondingly, of course, we are trying to get better about updating our manual, and also will make sure that users can find and access the manual. :-)

**Comment by palmerb4** [comment]
Hi @alanw0, thanks for the quick reply! Looking deeper, I missed the fact that MeshBuilder is a friend class of BulkData and therefore has access to its protected constructor. That resolves my question, so I'll close out this issue. 

Cheers,
Bryce
