### ISSUE TITLE
pamgen / exodus connection

### ISSUE THREAD

**Issue by VictorEijkhout** [trilinos/Trilinos#11797]
```
-- Configuring done
^[[31mCMake Error at cmake/tribits/core/package_arch/TribitsAddLibrary.cmake:472 (target_link_libraries):
  Target "pamgen" links to:

    ExodusII::all_libs

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.
   ```

???

**Comment by VictorEijkhout** [comment]
configure line as in https://github.com/trilinos/Trilinos/issues/11796

**Comment by jhux2** [comment]
@trilinos/seacas

**Comment by gsjaardema** [comment]
@bartlettroscoe Any ideas on what is wrong with either SEACAS/Exodus or Pamgen cmake files?

**Comment by bartlettroscoe** [comment]
@VictorEijkhout, what is the SHA1 for this Trilinos version?  Also, can you please attach the full CMake output and CMakeCache.txt file?

**Comment by VictorEijkhout** [comment]
This is the 14.0.0 release.
[exodus.zip](https://github.com/trilinos/Trilinos/files/11256538/exodus.zip)

**Comment by VictorEijkhout** [comment]
Confirmed also a problem in 13.4.1 and the git repo. 

I'd appreciate help with this.

**Comment by gsjaardema** [comment]
If I grep a SEACAS installation for any `all_libs` symbols that contain `exodus` (case insensitive).  I get `SEACASExodus::all_libs`  

Can you try changing the `packages/pamgen//cmake/Dependencies.cmake` to use `Exodus` instead of `ExodusII` and see if that works?

**Comment by gsjaardema** [comment]
Or probably `SEACASExodus`

**Comment by VictorEijkhout** [comment]
Did that cause this:
```
-- Setting Trilinos_ENABLE_SEACASExodus_for=OFF because SEACASExodus_for has a required library\ dependence on disabled package SEACASExodus
```
?

**Comment by VictorEijkhout** [comment]
In the end it may have been that NetCDF was inadvertently disabled. I now have a completely trilinos installation. Except that `peridigm` keeps complaining
```
/work2/00434/eijkhout/peridigm/peridigm-git/src/core/Peridigm_DataLoader.cpp(51): catastrophic error: cannot open source file "exodusII.h"
  #include <exodusII.h>
```
and indeed, that file is not copied over to the prefix location. So I enabled `exodusII`, which brought me back to ticket
https://github.com/trilinos/Trilinos/issues/11793

**Comment by VictorEijkhout** [comment]
> Or probably `SEACASExodus`

Almost.

```
SEACASExodusII
```
was what made it work for me. If that passes all your regression tests (which why did not catch this?) then please push to the repo and a point release.
