### ISSUE TITLE
HDF5 build options

### ISSUE THREAD

**Issue by VictorEijkhout** [trilinos/Trilinos#11793]
Trilinos 14.0.0 installation bombs with

```
/work/00434/eijkhout/trilinos/trilinos-14.0.0/packages/epetraext/src/inout/EpetraExt_HDF5.cpp(347): error: identifier "H5Pset_fapl_mpio" is undefined
      H5Pset_fapl_mpio(plist_id_, mpiComm, MPI_INFO_NULL);
      ^
```

which seems to indicate that some of the HDF5 parallel I/O is missing.

Do you have documentation about your preferred build options for HDF5? I'm using 

```
cmake -D CMAKE_INSTALL_PREFIX=/work/00434/eijkhout/hdf5/installation-1.14-milan-intel-impi                     
-D HDF5_ENABLE_Z_LIB_SUPPORT:BOOL=ON 
-D ZLIB_DIR:PATH=/work/00434/eijkhout/zlib/installation-1.2.13-milan-intel 
-D ZLIB_INCLUDE_DIR:PATH=/work/00434/eijkhout/zlib/installation-1.2.13-milan-intel/include 
-D ZLIB_LIBRARY:PATH=/work/00434/eijkhout/zlib/installation-1.2.13-milan-intel/lib/libz.so 

-D HDF_ENABLE_PARALLEL:BOOL=ON 
-D CMAKE_C_FLAGS=--enable-parallel 
-D CMAKE_CXX_FLAGS=--enable-parallel      
                
-D CMAKE_VERBOSE_MAKEFILE=ON                     
/work/00434/eijkhout/hdf5/hdf5-1.14
```

Sample compile line from the hdf5 installation:

```
cd /work/00434/eijkhout/hdf5/build-1.14-milan-intel-impi/src 
&& /scratch/projects/compilers/oneapi_2022.2.0/mpi/latest/bin/mpicc 
-D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -D_POSIX_C_SOURCE=200809L 
-I/work/00434/eijkhout/zlib/installation-1.2.13-milan-intel/include 
-I/work/00434/eijkhout/hdf5/hdf5-1.14/src 
-I/work/00434/eijkhout/hdf5/hdf5-1.14/src/H5FDsubfiling 
-I/work/00434/eijkhout/hdf5/build-1.14-milan-intel-impi/src 
-std=c99 
--enable-parallel -O2 -g -DNDEBUG -fPIE -std=gnu99 
-MD -MT src/CMakeFiles/H5detect.dir/H5detect.c.o 
-MF CMakeFiles/H5detect.dir/H5detect.c.o.d 
-o CMakeFiles/H5detect.dir/H5detect.c.o 
-c /work/00434/eijkhout/hdf5/hdf5-1.14/src/H5detect.c
```

**Comment by jhux2** [comment]
@trilinos/epetra @trilinos/epetraext 

@VictorEijkhout If you don't require EpetraExt HDF5 I/O, a work around is just disabling it.

**Comment by VictorEijkhout** [comment]
But I do need it for `exodusII`, which I need for `peridigm`.

So what are your required HDF5 build options?

**Comment by bartlettroscoe** [comment]
@VictorEijkhout, how are you configuring and building HDF5?   What version of HDF5 is this?

If you don't need HDF5 support in EpetraExt, I would suggest you just disabled it with:

```
-D EpetraExt_ENABLE_HDF5=OFF
```

I don't remember what functionality in EpetraExt needs HDF5 but I know many customers just disable this.

**Comment by VictorEijkhout** [comment]
But `exodusII` needs parallel hdf5, not?

**Comment by bartlettroscoe** [comment]
> But `exodusII` needs parallel hdf5, not?

The usage of HDF5 in SEACASExodus has nothing to do with the usage of HDF5 in EpetraExt, as far as I know.

If you go into the build subdir:

```
$ cd pacakges/seacas/

$ make -j 20
```

what happens?  Does all of SEACAS build?

**Comment by gsjaardema** [comment]
This is how I typically configure HDF5 for a parallel build.
```
cmake .. -DCMAKE_C_COMPILER:FILEPATH=mpicc \
         -DBUILD_SHARED_LIBS:BOOL=${SHARED} \
         -DBUILD_TESTING:BOOL=OFF \
         -DCMAKE_INSTALL_PREFIX=${INSTALL_PATH} \
	 -DCMAKE_BUILD_TYPE=Release \
	 -DDEFAULT_API_VERSION=V18 \
	 -DHDF5_ENABLE_PARALLEL:BOOL=ON \
	 -DHDF5_ENABLE_Z_LIB_SUPPORT:BOOL=ON \
	 -DHDF5_BUILD_CPP_LIB:BOOL=OFF \
	 -DHDF5_BUILD_FORTRAN:BOOL=OFF \
	 -DHDF5_BUILD_HL_LIB:BOOL=ON \
	 -DHDF5_DISABLE_COMPILER_WARNINGS:BOOL=ON 
```
If you are using the parallel-aware exodus, then you need a parallel hdf5 build.

**Comment by gsjaardema** [comment]
> > But `exodusII` needs parallel hdf5, not?
> 
> The usage of HDF5 in SEACASExodus has nothing to do with the usage of HDF5 in EpetraExt, as far as I know.
> 
Except that you only have a single HDF5 for use in all of the Trilinos build...
