### ISSUE TITLE
failing in Trilinos' cmake as try to build

### ISSUE THREAD

**Issue by abdulbadii** [trilinos/Trilinos#11799]
As try building by
```
mkdir  build && cd build
cmake .. \
		-G "Unix Makefiles" \
		-DCMAKE_CXX_FLAGS="${CXXFLAGS/-O2/-O3} -fPIC" \
		-DCMAKE_C_FLAGS="${CFLAGS/-O2/-O3} -fPIC" \
		-DCMAKE_Fortran_FLAGS="${FFLAGS/-O2/-O3} -fPIC" \
		-DTrilinos_INSTALL_INCLUDE_DIR="/usr/include/trilinos" \
		-DTrilinos_INSTALL_LIB_DIR="/usr/lib/trilinos" \
		-DCMAKE_MAKE_PROGRAM="make" \
		-DTrilinos_ENABLE_NOX=ON \
		-DNOX_ENABLE_LOCA=ON \
		-DTrilinos_ENABLE_EpetraExt=ON \
		-DEpetraExt_BUILD_BTF=ON \
		-DEpetraExt_BUILD_EXPERIMENTAL=ON \
		-DEpetraExt_BUILD_GRAPH_REORDERINGS=ON \
		-DTrilinos_ENABLE_TrilinosCouplings=ON \
		-DTrilinos_ENABLE_Ifpack=ON \
		-DTrilinos_ENABLE_Isorropia=ON \
		-DTrilinos_ENABLE_AztecOO=ON \
		-DTrilinos_ENABLE_Belos=ON \
		-DTrilinos_ENABLE_Teuchos=ON \
		-DTeuchos_ENABLE_COMPLEX=ON \
		-DTrilinos_ENABLE_Amesos=ON \
		-DAmesos_ENABLE_KLU=ON \
		-DTrilinos_ENABLE_Sacado=ON \
		-DTrilinos_ENABLE_Kokkos=OFF \
		-DTrilinos_ENABLE_ALL_OPTIONAL_PACKAGES=OFF \
		-DTrilinos_ENABLE_CXX11=ON \
		-DTPL_ENABLE_AMD=ON \
		-DAMD_LIBRARY_DIRS="/usr/lib" \
		-DTPL_AMD_INCLUDE_DIRS="/usr/include/suitesparse" \
		-DTPL_ENABLE_BLAS=ON \
		-DTPL_ENABLE_LAPACK=ON \
		-DTPL_ENABLE_MPI=OFF \
		-DBUILD_SHARED_LIBS=OFF \
		-DCMAKE_BUILD_TYPE='None' \
		-Wno-dev

```
after long list/message of cmake, encoutered error:

```
CMake Error in packages/epetraext/src/CMakeLists.txt:
  Imported target "AMD::all_libs" includes non-existent path

    "/usr/include/suitesparse"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.



CMake Error in packages/epetraext/src/CMakeLists.txt:
  Imported target "AMD::all_libs" includes non-existent path

    "/usr/include/suitesparse"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide
```

On Arch, any idea what's causing it non existent?

**Comment by cgcgcg** [comment]
@abdulbadii It looks to me like you are specifying a path (`/usr/include/suitesparse` ) that doesn't exist. Did you check that the path exists?

**Comment by abdulbadii** [comment]
almost know nothing as I'm noob, just looked up / ceated in Arch AUR cmake command that's such above, what I did:

`$ sudo pacman --noconfirm --needed -S suitesparse 'gcc-fortran`

and confirm all installed updated

```

$ git clone --depth 1 https://github.com/trilinos/Trilinos.git
$ cd Trilinos

```
then do Arch cmake command cheated in AUR such was posted but failed so

**Comment by jhux2** [comment]
@abdulbadii What type of problems are you interested in solving?  What Trilinos packages are you interested in?

**Comment by abdulbadii** [comment]
xyce

exact package name
xyce-serial
(The Xyce Parallel Electronic Simulator is a SPICE-compatible circuit simulator)

the point is it's dependency is `trilinos`, more exactly `trilinos-xyce-serial`

**Comment by hkthorn** [comment]
@abdulbadii Xyce is not a Trilinos package.  Xyce uses Trilinos to provide linear algebra and solvers.  Please follow the Xyce building guide at 

https://xyce.sandia.gov/documentation-tutorials/building-guide/

which also has architecture specific notes.  Please target any specific build issues to the Xyce team through the Xyce Google group (https://groups.google.com/g/xyce-users) or Github (https://github.com/Xyce/Xyce/issues).  From what I can see your issues are not having the proper TPLs installed on your platform or the paths to those TPLs in the cmake script.

**Comment by jhux2** [comment]
@hkthorn Thank you for chiming in.  I'll close this in favor of the links you provided.
