### ISSUE TITLE
MueLu: Run time errors related to kokkos views

### ISSUE THREAD

**Issue by maxfirmbach** [trilinos/Trilinos#11806]
### Description
Suddenly, after the aggregation procedure I run into these errors:
- `Constructing View and initializing data with uninitialized execution space`
- `Dummy function getHostLocalView, should be overwritten at`

I'm still building with the `Epetra`-stack, never encountered these errors before.

### Steps to Reproduce
SHA1:  dd18e71fef3b09d3e002158bd38a084bb32fdb9f
Configure script: [configure-script.zip](https://github.com/trilinos/Trilinos/files/11295339/configure-script.zip)

**Comment by mayrmt** [comment]
@GrahamBenHarper Might this be related to #11787?

**Comment by cgcgcg** [comment]
@maxfirmbach For the dummy function errors, do you get line numbers?

**Comment by maxfirmbach** [comment]
Yes, mainly `Xpetra_MultiVector_decl.hpp:332`.

**Comment by cgcgcg** [comment]
What's the GO? It looks like GO=int should work, but long long might miss some stuff.

**Comment by cgcgcg** [comment]
Hm. Just by looking at the code this should work. I'm on travel and can't build anything. I'll let @GrahamBenHarper have fun with that.

**Comment by maxfirmbach** [comment]
The errors already appear in the MueLu tests, but yes, also with our application Baci ;) (which is not surprising).

**Comment by GrahamBenHarper** [comment]
Hi @maxfirmbach, I was able to mostly build using the configure you provided. There was an error building Zoltan2Sphynx for some reason, but I was able to ignore it since it was at the end of the build and nothing depended on it.
```
In file included from /ascldap/users/gbharpe/Programming/cpp/Trilinos/Trilinos-source/packages/teuchos/core/src/Teuchos_Ptr.hpp:48,
                 from /ascldap/users/gbharpe/Programming/cpp/Trilinos/Trilinos-source/packages/teuchos/core/src/Teuchos_CommandLineProcessor.hpp:56,
                 from /ascldap/users/gbharpe/Programming/cpp/Trilinos/Trilinos-source/packages/zoltan2/test/sphynx/Sphynx_Research_Driver.cpp:46:
/ascldap/users/gbharpe/Programming/cpp/Trilinos/Trilinos-source/packages/teuchos/core/src/Teuchos_RCP.hpp: In instantiation of 'Teuchos::RCP<T>::RCP(const Teuchos::RCP<T2>&) [with T2 = const Tpetra::Map<int, long long int, Tpetra::KokkosCompat::KokkosDeviceWrapperNode<Kokkos::Serial> >; T = const Tpetra::Map<>]':
/ascldap/users/gbharpe/Programming/cpp/Trilinos/Trilinos-source/packages/zoltan2/test/sphynx/Sphynx_Research_Driver.cpp:460:62:   required from here
/ascldap/users/gbharpe/Programming/cpp/Trilinos/Trilinos-source/packages/teuchos/core/src/Teuchos_RCP.hpp:297:19: error: cannot convert 'const Tpetra::Map<int, long long int, Tpetra::KokkosCompat::KokkosDeviceWrapperNode<Kokkos::Serial> >*' to 'const Tpetra::Map<>*' in initialization
  297 |   : ptr_(r_ptr.get()), // will not compile if T is not base class of T2
      |          ~~~~~~~~~^~
      |                   |
      |                   const Tpetra::Map<int, long long int, Tpetra::KokkosCompat::KokkosDeviceWrapperNode<Kokkos::Serial> >*
/ascldap/users/gbharpe/Programming/cpp/Trilinos/Trilinos-source/packages/teuchos/core/src/Teuchos_RCP.hpp: In instantiation of 'Teuchos::RCP<T>::RCP(const Teuchos::RCP<T2>&) [with T2 = Tpetra::MultiVector<double, int, int, Tpetra::KokkosCompat::KokkosDeviceWrapperNode<Kokkos::Serial> >; T = Tpetra::MultiVector<double, int, long long int, Tpetra::KokkosCompat::KokkosDeviceWrapperNode<Kokkos::Serial> >]':
/ascldap/users/gbharpe/Programming/cpp/Trilinos/Trilinos-source/packages/zoltan2/test/sphynx/Sphynx_Research_Driver.cpp:548:43:   required from here
/ascldap/users/gbharpe/Programming/cpp/Trilinos/Trilinos-source/packages/teuchos/core/src/Teuchos_RCP.hpp:297:19: error: cannot convert 'Tpetra::MultiVector<double, int, int, Tpetra::KokkosCompat::KokkosDeviceWrapperNode<Kokkos::Serial> >*' to 'Tpetra::MultiVector<double, int, long long int, Tpetra::KokkosCompat::KokkosDeviceWrapperNode<Kokkos::Serial> >*' in initialization
```

On the MueLu side, I see `24% tests passed, 67 tests failed out of 88`, and it looks like some of the runtime errors are of the form
```
11:  p=0: *** Caught standard std::exception of type 'std::runtime_error' :
11:  
11:   Dummy function getHostLocalView, should be overwritten at/ascldap/users/gbharpe/Programming/cpp/Trilinos/Trilinos-source/packages/xpetra/src/MultiVector/Xpetra_MultiVector_decl.hpp:332
11:  [FAILED]  (0.00123 sec) VariableDofLaplacianFactory_double_int_int_Tpetra_KokkosCompat_KokkosSerialWrapperNode_VarLaplPtent_UnitTest
11:  Location: /ascldap/users/gbharpe/Programming/cpp/Trilinos/Trilinos-source/packages/muelu/test/unit_tests/VariableDofLaplacianFactory.cpp:220
```

I'll keep working on this. @jhux2 do you have any ideas what this message means with respect to the Epetra-Xpetra interface? We have both Tpetra, Epetra, and EpetraExt enabled, but specify using Epetra in the Xpetra configure options.

**Comment by cgcgcg** [comment]
@GrahamBenHarper As far as I can tell it means that something is calling `getHostLocalView` of the base class.

**Comment by GrahamBenHarper** [comment]
@cgcgcg that's what it seemed like to me as well, but I'm hoping somebody more familiar with Xpetra internals has more context as to whether it's intentional, just a simple missing implementation, or something else

**Comment by cgcgcg** [comment]
There should be no missing implementations. If we do, please add them. I don't think this is intentional.

**Comment by jhux2** [comment]
@GrahamBenHarper That message looks like a typo:

https://github.com/trilinos/Trilinos/blob/e7012f3ffc95e9915aeb65ff30660beae7d05e3d/packages/xpetra/src/MultiVector/Xpetra_MultiVector_decl.hpp#L330-L337

**Comment by GrahamBenHarper** [comment]
@maxfirmbach when you have a chance, can you let me know if this fixes the issues or if there is a different error? we're working on getting a config like this pulled into our nightly testing since it doesn't seem to be covered by the autotester for develop or master.

**Comment by maxfirmbach** [comment]
Problem is fixed, thanks for the quick help :).

**Comment by GrahamBenHarper** [comment]
That's great! Thank you for bringing it to our attention!
