### ISSUE TITLE
Framework: CODEOWNERS file and mechanism is broken 

### ISSUE THREAD

**Issue by mayrmt** [trilinos/Trilinos#11812]
@trilinos/framework 

## Bug Report

As reported by @lucbv in #11808, in particular in [this comment](https://github.com/trilinos/Trilinos/pull/11808#issuecomment-1520928275), we used to work with the `CODEOWNERS` file to manage approval rights in PRs. This seems to be broken.

When looking at the `CODEOWNERS` file on GitHub, I can see the following error:

<img width="426" alt="Screen Shot 2023-04-25 at 08 25 53" src="https://user-images.githubusercontent.com/14297653/234192795-2a40145a-dd0f-4b2f-a5b4-3be196b75bb2.png">

And in more detail: 

<img width="642" alt="Screen Shot 2023-04-25 at 08 26 02" src="https://user-images.githubusercontent.com/14297653/234192843-a930afc8-6b82-41f5-9009-da70a06c927b.png">

These errors do apply to all teams, not only the few shown in the screenshots.

⚠️ With the `CODEOWNERS` mechanism being broken, PRs are fully approved by only a single reviewer, not by one reviewer per package/team. 

### Description

One would expect the `CODEOWNERS` file to not contain errors. Furthermore, access rights of teams need to be set correctly, such that the PR approval can be organized by teams again.

### Steps to Reproduce

1. Look at the `CODEOWNERS` file on GitHub to see the above error messages: https://github.com/trilinos/Trilinos/blob/master/.github/CODEOWNERS
1. Look at recent PRs, where a single approval approved the entire PR, although multiple packages have been changed. Example: https://github.com/trilinos/Trilinos/pull/11808

**Comment by jhux2** [comment]
@mayrmt Could it be that the teams for which this used to work have lost repository-read permissions?   See https://github.com/trilinos/Trilinos/issues/3761 for a discussion.

**Comment by mayrmt** [comment]
@jhux2 While reading through #3761, I stumbled across [this comment](https://github.com/trilinos/Trilinos/issues/3761#issuecomment-439178995) by @jmgate, stating that auto-requesting reviews via the `CODEOWNERS` file requires write access for the teams. So, maybe write access is the missing feature. I don't know, since I can't look into the configurations of the team in the Trilinos organization on GitHub.

**Comment by jhux2** [comment]
> While reading through #3761, I stumbled across [this comment](https://github.com/trilinos/Trilinos/issues/3761#issuecomment-439178995) by @jmgate, stating that auto-requesting reviews via the `CODEOWNERS` file requires write access for the teams. So, maybe write access is the missing feature. I don't know, since I can't look into the configurations of the team in the Trilinos organization on GitHub.

Maybe @sebrowne knows whether the @trilinos/muelu team lost its write access?

**Comment by jwillenbring** [comment]
@ccober6 Could this be due to the changes with team access in revamping the developer team structure?

**Comment by ccober6** [comment]
Ok, this is likely related to a change I made to close a security loophole (Brent mentioned it also, https://github.com/trilinos/Trilinos/issues/2013#issuecomment-354814699.).  Need to talk through a solution.  Maybe https://github.com/trilinos/Trilinos/issues/2013#issuecomment-354846931.

**Comment by ccober6** [comment]
FYI, all teams have lost their write access.

**Comment by mayrmt** [comment]
@ccober6 thanks for looking into this!

**Comment by jhux2** [comment]
> we used to work with the `CODEOWNERS` file to manage approval rights in PRs. This seems to be broken

@mayrmt According to the [documentation](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#about-code-owners), "[code] owners are automatically requested for review when someone opens a pull request that modifies code that they own."

I agree that's a nice feature to have, but any Trilinos developer can still review, and the MueLu team  @mention will still alert all members.

**Comment by mayrmt** [comment]
@jhux2 i agree. PR review and approval also works without CODEOWNERS. I did it a neat feature, especially for PRs that touch multiple packages (as in PR #11808 for example).

**Comment by mayrmt** [comment]
Seems to work again. Closing.
