### ISSUE TITLE
Tpetra: matrix filling, fillComplete performance regression

### ISSUE THREAD

**Issue by brian-kelley** [trilinos/Trilinos#11820]
### Description
Between Mar. 28 and Mar. 29 (versions 7969c and a2064), the ATS-2 performance dashboard shows graph/matrix filling and fillComplete() slowing down significantly, ~50% or more.

These are the sub-timers that jumped:
- FEAssembly
  - ElementLoop (Graph)
  - FillComplete (Graph)
- MueLu Setup-Solve
  - Matrix Build
    - Galeri: Laplace 3D fillComplete
    - Galeri: Laplace 3D generation

The migration of the Jenkins job does not appear to be related. The Mar. 29 run was on the old jenkins-srn, and no script changes had happened by that point. Mar. 30 was the first run on the new JaaS jenkins.

**Comment by jhux2** [comment]
@brian-kelley I see this also on the crusher dashboard.
