### ISSUE TITLE
MueLu: Hard dependency on Tpetra is implicit

### ISSUE THREAD

**Issue by GrahamBenHarper** [trilinos/Trilinos#11821]
## Bug Report
@trilinos/muelu 

Based on our dependencies list, we have Tpetra listed as an optional package
```cmake
SET(LIB_REQUIRED_DEP_PACKAGES Teuchos Xpetra KokkosCore KokkosContainers KokkosKernels)
SET(LIB_OPTIONAL_DEP_PACKAGES Amesos Amesos2 AvatarT Belos Epetra EpetraExt Teko
                              Ifpack Ifpack2 Intrepid2 ML Tpetra
                              Zoltan Zoltan2Core Stratimikos Thyra ThyraTpetraAdapters
                              Isorropia)
```

However, since we require Kokkos to be enabled now, we have logic that is confusing like
```cmake
IF (${PACKAGE_NAME}_ENABLE_KokkosCore AND NOT ${PACKAGE_NAME}_ENABLE_Tpetra)
  MESSAGE(FATAL_ERROR "MueLu requires that if Kokkos is enabled, Tpetra must also be enabled.")
ENDIF()
```

We should clean up this sort of logic and make these sorts of details a little more obvious.

**Comment by cgcgcg** [comment]
I started working on that in #11387. If we don't remove Epetra at the same time this is probably not too bad.

**Comment by GrahamBenHarper** [comment]
I started working on this as a separate PR. Am I correct in seeing that we should remove `test/permutation` since it never builds?

**Comment by cgcgcg** [comment]
Why does it not build?

**Comment by GrahamBenHarper** [comment]
Simply changing the CMake line to `IF(NOT HAVE_MUELU_COMPLEX AND HAVE_MUELU_EPETRA)` results in a new passing test on an Xpetra_Epetra build.

I also replaced a piece of the test driver with
```
  if (lib == Xpetra::UseTpetra) {
    return main_<double,int,int,Tpetra::KokkosClassic::DefaultNode::DefaultNodeType>(clp, lib, argc, argv);
  }
```
and it seems to also pass with `--linAlgebra=Tpetra` in an Epetra build. However, a bit of the test is hard-coded to Epetra, so it would take more effort to get it working in an Epetra=OFF build.

Since the PR is already testing, I'll wait to push this fix for now, but I just wanted to document what I see related to that permutation test.

**Comment by GrahamBenHarper** [comment]
Closing this and splitting the `PermutationFactory` issue into #11836 instead.
