### ISSUE TITLE
MueLu:  Block operators are supported with the Stratimikos interface?

### ISSUE THREAD

**Issue by nasseralkmim** [trilinos/Trilinos#11826]
## Question

Hi,

I'm planning to use MueLu to solve a multi-field problem using the Stratimikos interface.
However, when using the `SubBlockAFactory`, it seems that MueLu expects a `BlockedCrsMatrix`, from this error message:

`MueLu::BlockedDirectSolver::Build: input matrix A is not of type BlockedCrsMatrix.
`

But the only object that I provided to create the  `Thyra::LinearOpBase` was an `Epetra_CrsMatrix`.
I tried to do some conversion between this Epetra object into Xpetra, and then convert the Xpetra into the Thyra Linear operator, but still no success.
Is this MueLu feature supported by Stratimikos?

**Comment by cgcgcg** [comment]
I am not sure I follow. (But I am not very familiar with the blocked stuff.) Are you using a single Epetra_CrsMatrix as the input? Or a blocked matrix? If it's a single CRS matrix I don't think you can use the block stuff. MueLu needs to know what the blocks are. There might be some way of detecting the blocks and splitting into a block operator.

**Comment by nasseralkmim** [comment]
Initially, I tried with a regular `Epetra_CrsMatrix`, and as you said, it does not work.
The workaround I thought about was to create the blocked operator that MueLu expects with Xpetra and then try to cast this Xpetra object as a `Thyra::LinearOpBase`.
But something might have gone wrong along the way.

I wonder if there is a better way of using this MueLu feature with the standard Stratimikos/Thyra interface.
At the bottom line, I need to create a `Thyra::LinearOpWithSolveBase` object which takes a `Thyra::LinearOpBase`.

**Comment by cgcgcg** [comment]
Here is what we have in a test for creating a blocked op from a single matrix:
https://github.com/trilinos/Trilinos/blob/d82ed05306b491146fc6b2ceed766100dc4a6fbd/packages/muelu/test/blockedtransfer/BlockedTransfer.cpp#L226-L256
Here is the code that unwraps the Thyra object into a blocked Xpetra operator. So you essentially want to wrap the other way around:
https://github.com/trilinos/Trilinos/blob/d82ed05306b491146fc6b2ceed766100dc4a6fbd/packages/muelu/adapters/stratimikos/Thyra_MueLuPreconditionerFactory_def.hpp#L494-L517
