### ISSUE TITLE
shylu:  enabling transpose of FROSch solver object

### ISSUE THREAD

**Issue by thartland** [trilinos/Trilinos#11831]
Are there any plans to enable a transpose option for FROSch solvers as here? https://github.com/trilinos/Trilinos/blob/master/packages/shylu/shylu_dd/frosch/src/SolverInterfaces/FROSch_Amesos2SolverTpetra_def.hpp#L102

**Comment by GrahamBenHarper** [comment]
Pinging @searhein since he may have more information

**Comment by jhux2** [comment]
@trilinos/shylu

**Comment by searhein** [comment]
@thartland I wasn't going to implement this soon. But I would be happy to take a look if you could give me some more details on what you would need.

**Comment by thartland** [comment]
Thanks @searhein, I think that I need to take a step back and look at this more carefully/consult with my team before I am able to provide such details. I am closing this issue for now. Thanks again for your response.

**Comment by searhein** [comment]
@thartland Ok, sounds good. Just let me know in case.
