### ISSUE TITLE
Piro: missing Teko ifdef

### ISSUE THREAD

**Issue by ikalash** [trilinos/Trilinos#11848]
There are failures in the Albany/LCM nightly builds due to Teko not being turned on in the build.  I think there is a missing ifdef.  Is this related to recent changes in Piro, @mperego, @kliegeois ?  Tagging @lxmota who is interested in this issue as an Albany/LCM developer.

**Comment by ikalash** [comment]
I forgot to include the link to the error on CDash, sorry.  It can be found here: https://sems-cdash-son.sandia.gov/cdash/viewBuildError.php?buildid=48060 .

**Comment by kliegeois** [comment]
@ikalash the cdash above is clean, can we close this issue?

**Comment by ikalash** [comment]
@kliegeois : yes!  Done.
