### ISSUE TITLE
Intrepid2: Valgrind warning

### ISSUE THREAD

**Issue by cgcgcg** [trilinos/Trilinos#11847]
@trilinos/intrepid2 @CamelliaDPG 

## Bug Report
Our nightly valgrind runs flagged something in StructuredIntegration:
https://testing.sandia.gov/cdash/viewDynamicAnalysisFile.php?id=517238

**Comment by CamelliaDPG** [comment]
@cgcgcg Thanks for the report.  That's interesting; it looks like it's an issue with the (implicit) Data copy constructor.  Not too sure beyond that at the moment, but I'll investigate!

**Comment by cgcgcg** [comment]
This is still an issue.

**Comment by CamelliaDPG** [comment]
@cgcgcg Sorry for neglecting this.  Looking at the log you linked, at the top it says:

```
==74601== Warning: client switching stacks?  SP change: 0x1ffee84e20 --> 0x1ffeadbf40
==74601==          to suppress, use: --max-stackframe=3837664 or greater
```

Would it be possible to change the invocation of valgrind to include `--max-stackframe=3837664` (or preferably greater)?  I think these may be spurious errors stemming from us using more memory than valgrind is expecting.

**Comment by mperego** [comment]
@cgcgcg who's taking care of the valgrind builds? Is it possible to make the change requested by @CamelliaDPG ?

**Comment by cgcgcg** [comment]
Those builds are owned by the MueLu team. I ended up disabling Intrepid2 because of issues with link times.

**Comment by mperego** [comment]
OK. Can we close this issue?

**Comment by cgcgcg** [comment]
Sounds good to me.
