### ISSUE TITLE
Tpetra: Require setting Teuchos_ENABLE_LONG_LONG_INT=ON

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#1184]
@trilinos/tpetra 

`Teuchos_ENABLE_LONG_LONG_INT=ON` is the default setting of that CMake variable.  The only reason to turn off `long long` support in Teuchos is if building with C++11 disabled, but Tpetra requires C++11.

It used to be that `Teuchos_ENABLE_LONG_LONG_INT` controlled whether Tpetra enabled `GlobalOrdinal=long long`.  Currently, disabling it still makes Tpetra disable that GlobalOrdinal type.  However, the better approach is to tell Tpetra directly via `Tpetra_INST_INT_LONG_LONG=ON`.

**Comment by bathmatt** [comment]
Shouldn't there be a global use long_long use double use complex?  This
could control all the ETI and stuff?  I thought tuechos was the lowest
package and thus controlled all above (or below depending on your point of
view) it..

**Comment by mhoemmen** [comment]
The original reason for `Teuchos_ENABLE_LONG_LONG_INT` was that `long long` was a nonstandard extension to C++98.  C++11 mandates it, but Teuchos does not (yet) require C++11 and has (non-Trilinos) customers that depend on continued C++98 support.

**Comment by mhoemmen** [comment]
We fixed this: https://github.com/trilinos/Trilinos/blob/de338381e324785a7ef792fc30ecfd91867082f1/packages/teuchos/CMakeLists.txt#L153
