### ISSUE TITLE
Seacas / Exodus compilation problem / NetCDF

### ISSUE THREAD

**Issue by VictorEijkhout** [trilinos/Trilinos#11857]
```
/work2/00434/eijkhout/trilinos/trilinos-13.4.1/packages/seacas/libraries/exodus/src/ex_utils.c:1745:19: error: expected identifier or '('
        const int NC_SZIP_NN = 32;      /* Selects nearest neighbor coding method for szip. */
                  ^
/work2/00434/eijkhout/netcdf/installation-4.9.2-clx-intel23-impi/include/netcdf.h:332:20: note: expanded from macro 'NC_SZIP_NN'
#define NC_SZIP_NN 32 /**< SZIP NN option mask. */
                   ^
```

Are you redefining a NetCDF constant?

Intel OneAPI 23.0.1 but I don't think that matters.

**Comment by VictorEijkhout** [comment]
Any word on this? Is NetCDF part of your regression suite?

**Comment by gsjaardema** [comment]
The code in question in my repository version is:
```
#if !defined(NC_SZIP_EC)
        const int NC_SZIP_EC = 4; /* Selects entropy coding method for szip. */
#endif
#if !defined(NC_SZIP_NN)
        const int NC_SZIP_NN = 32; /* Selects nearest neighbor coding method for szip. */
#endif
```
I'm not sure why your build would be stepping inside this.  Is this a recent version that you are using?

**Comment by VictorEijkhout** [comment]
Recent version of what? If you parse my original post you'll see that I'm using trilinos 13.4.1 and netcdf 4.9.2

**Comment by VictorEijkhout** [comment]
I'll try trilinos 14 but that breaks dealii because you changed something fundamental.

**Comment by gsjaardema** [comment]
What did I change?

**Comment by VictorEijkhout** [comment]
Please confirm that you have netcdf in your regression suite and which version is compatible with what version of trilinos?

**Comment by VictorEijkhout** [comment]
> What did I change?

https://github.com/dealii/dealii/issues/14812

**Comment by gsjaardema** [comment]
netCDF is in the SEACAS regression suite and I compile with multiple versions of netCDF including 4.9.2.  I periodically snapshot the SEACAS code into Trilinos which also builds using netCDF.

**Comment by VictorEijkhout** [comment]
This is still a problem. Can you do a maintainance release of 13.x?

**Comment by VictorEijkhout** [comment]
Actually, the only reason to use 13 because because of dealii and they have updated, so this problem has gone away.
