### ISSUE TITLE
Intrepid2 Basis parameters

### ISSUE THREAD

**Issue by bathmatt** [trilinos/Trilinos#1185]
Can we move the basis parameters into the actual basis as a const static, or a #define?

Example 
basis::getCardinality() {return 4;} for quad?
Right now it is a virtual function and with the move to more kokkos callable functions it seems like this is a bad idea not to have it defined at compile time.

**Comment by mperego** [comment]
I think it makes sense. I'll look into that.

**Comment by mperego** [comment]
@bathmatt This is a very old issue.. I guess the problem is that the cardinality depends on the basis order, which is not defined at compile time. We might decide to template the basis on the order at some point, but we haven't decided on that yet. @CamelliaDPG  feel free to weigh in.

**Comment by CamelliaDPG** [comment]
@bathmatt @mperego Adding a template parameter would introduce a certain amount of complexity for downstream code, and it's not clear to me when it would be important/useful to call a Basis method from device code; the usual use cases work with Basis instances on host, and Basis members launch parallel kernels.  It could be that the compiler would do fancy things with compile-time loop sizes, etc., but a) I'd want some evidence before we invested too much in that, and b) I think we could take advantage of that without exposing it as a template parameter on the Basis class (by doing run-time switch that calls compile-time kernels — of course, that would come at a cost for compile time, and binary sizes).
