### ISSUE TITLE
NOX: Don't just throw exceptions via 'throw "NOX error";'

### ISSUE THREAD

**Issue by bangerth** [trilinos/Trilinos#11868]
NOX is a great nonlinear solver, but it reports errors via both nonzero return codes,  as well as by throwing exceptions. That's already awkward -- pick one or the other. But to make it worse, it throws exceptions as simply `char *` objects. See for example here: https://github.com/trilinos/Trilinos/blob/master/packages/nox/src/NOX_Direction_Newton.C#L328-L333

Throwing exceptions not derived from `std::exception` is generally poor style, because to catch such exception, you have to know its type. If it were derived from `std::exception`, you could just do `catch (const std::exception &e) { std::cout << e.what() << std::endl; }` to learn what the exception was about, which works for all classes derived from `std::exception`. But for everything else, you have to *know* the type thrown, and that type is generally not documented.

A better version of the `throwError()` function linked to above would be
```
void NOX::Direction::Newton::throwError(const std::string& functionName, const std::string& errorMsg)
{
    if (utils->isPrintType(Utils::Error))
      utils->err() << "NOX::Direction::Newton::" << functionName << " - " << errorMsg << std::endl;
    throw std::runtime_error("NOX Error");
}
```
which uses https://en.cppreference.com/w/cpp/error/runtime_error . Ideally, the exception would also include `functionName` and `errorMsg`. There are multiple versions of `throwError()` in the NOX code base, all of which should be changed in this way.

Just to illustrate how much these two design decisions above (return codes + exceptions, exceptions not derived from `std::exception`) make it difficult to properly deal with errors, here's the code in deal.II (to be proposed as a pull request soon) looks like:
```
    // Solve, then check whether an exception was thrown by one of the user
    // callback functions. If so, exit by rethrowing the exception that
    // we had previously saved. This also calls the destructors of all of
    // the member variables above, so we do not have to clean things up by hand.
    //
    // NOX has the annoying habit of reporting success through a return code,
    // but if a user callback function throws an exception (which we translate
    // into a return code of -1), then it throws its own exception. So we
    // have to check both the return code and also catch exceptions :-(
    try
      {
        const auto status = solver->solve();

        if (status == NOX::StatusTest::Converged)
          return solver->getNumIterations();
        else
          {
            // See if NOX aborted because we had thrown an exception in a user
            // callback:
            if (pending_exception)
              {
                std::exception_ptr this_exception = pending_exception;
                pending_exception                 = nullptr;

                std::rethrow_exception(this_exception);
              }

            // If that was not the case, NOX just didn't converge:
            AssertThrow(status == NOX::StatusTest::Converged,
                        ExcNOXNoConvergence());
          }
      }
    // See if NOX returned by triggering an exception. In a sign of generally
    // poor software design, NOX throws an exception that is not of a class
    // derived from std::exception, but just a char*. That's a nuisance -- you
    // just have to know :-(
    catch (const char *s)
      {
        // Like above, see if NOX aborted because there was an exception
        // in a user callback. In that case, collate the errors if we can
        // (namely, if the user exception was derived from std::exception),
        // and otherwise just let the user exception propagate (then swallowing
        // the NOX exception):
        if (pending_exception)
          {
            std::exception_ptr this_exception = pending_exception;
            pending_exception                 = nullptr;

            try
              {
                std::rethrow_exception(this_exception);
              }
            catch (const std::exception &e)
              {
                // Collate the exception texts:
                throw ExcMessage(
                  "NOX aborted with an error text of <" + std::string(s) +
                  "> after a user callback function had thrown an exception " +
                  "with the following message:\n" + e.what());
              }
            catch (...)
              {
                // Let user exception propagate if of a different type:
                throw;
              }
          }

        // NOX just happened to throw an exception, but it wasn't because there
        // was a user callback exception before. Convert the char* to something
        // more readable:
        AssertThrow(false,
                    ExcMessage("NOX aborted with an error text of <" +
                               std::string(s) + ">."));
      }
```

**Comment by GrahamBenHarper** [comment]
@trilinos/nox

**Comment by bangerth** [comment]
As a point of reference, there are 271 cases of `throw "..."` in NOX alone:
```
> grep -r 'throw "' packages/nox/ | wc -l
271
```
(Of these, ~100 are in `tests/`.)

In all of Trilinos, there are 739 cases of the string `throw "`, but there are also 2655 places where Trilinos uses `throw std::` (followed by `logic_error` or `runtime_error`), so there is definite precedent for doing things differently.

I did find this case, which is funny at first, but really quite unhelpful at its core:
```
packages/teuchos/parameterlist/example/ParameterList/xml_data_types.cpp:      throw "Uh oh...";
```

**Comment by rppawlo** [comment]
Thanks @bangerth for the detailed comments. We will work to fix this. I agree with everything you say. The original error handling was implemented back in 2001 while we were still learning c++ and cleanup just hasn't been a priority. It's definitely due for an overhaul. We typically throw std::runtime_error for exceptions in most other packages. Would this work for you? Would you like nox to implement derived exception classes so as to differentiate failure types coming from nox?

**Comment by bangerth** [comment]
@rppawlo I think `std::runtime_exception` is a great choice. 

I should note that if that's the way you want to go, I'd be happy to write a patch for NOX to make that change. I don't know how to test Trilinos, but I can at least come up with the code change and make sure it compiles.

**Comment by GrahamBenHarper** [comment]
@bangerth There are a variety of different configurations that we care about when testing Trilinos, but the autotester handles almost all of them. If you have something that works on some configuration locally, that's often the majority of the necessary work. I believe enabling tests for NOX is as simple as adding `-D NOX_ENABLE_TESTS:BOOL=ON` at configure time. We can help relay any feedback if the autotester reports an issue. Thank you for looking into this!
