### ISSUE TITLE
Tpetra::CrsMatrix: Add unit test for Import/Export with static-graph, post-first-fillComplete source matrix; separate out that case into nonmember functions that can be thread-parallelized in the future

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#1187]
@trilinos/tpetra 
Blocks: #800 

@etphipp found a bug in recent changes to CrsMatrix pack, for the special case where the object to pack (the source matrix) isStaticGraph() and is post-first-fillComplete.  I'm astonished that no tests downstream of Tpetra caught this, until Stokhos.  This means we need to add a Tpetra unit test for this case.

@etphipp reported a failure when using Stokhos with Amesos2 Basker.  May have to enable Basker in Amesos2, which is not enabled by default.  I think it's `Amesos2_ENABLE_Basker:BOOL=ON`.

**Comment by tjfulle** [comment]
I could gin something up as I'm coming up to speed on #800

**Comment by mhoemmen** [comment]
@tjfulle Awesome, thanks!!!  It would help since I need to write up the benchmarking report this week.

**Comment by ibaned** [comment]
This bug broke a lot of Albany tests, and @etphipp gave us a Tpetra patch that fixes it for us. I'd like to get this patch into develop ASAP:
```
diff --git a/packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp b/packages/tpetra
index 30eba0f..7e8d4b7 100644
--- a/packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp
+++ b/packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp
@@ -5924,8 +5924,8 @@ namespace Tpetra {
     // Since the matrix is locally indexed on the calling process, we
     // have to use its column Map (which it _must_ have in this case)
     // to convert to global indices.
-    const offset_type rowBeg = this->lclMatrix_.graph.row_map[numEnt];
-    const offset_type rowEnd = this->lclMatrix_.graph.row_map[numEnt + 1];
+    const offset_type rowBeg = this->lclMatrix_.graph.row_map[lclRow];
+    const offset_type rowEnd = this->lclMatrix_.graph.row_map[lclRow + 1];
 
     auto indIn = Kokkos::subview (this->lclMatrix_.graph.entries,
                                   pair_type (rowBeg, rowEnd));
```
Even if the new test isn't there yet, as long as the old tests keep passing we should probably get this in. It seems small for a PR, but let me know if submitting a PR would help.

**Comment by mhoemmen** [comment]
I'm running the check-in test now.

**Comment by mhoemmen** [comment]
Sorry, closed too early, it's not pushed yet.

**Comment by mhoemmen** [comment]
It takes so long because the only way to get complete downstream testing is to enable a bunch of stuff, including Tempus, that has unit tests that take a long time to run.

**Comment by ibaned** [comment]
Yep, I've been there :)

**Comment by mhoemmen** [comment]
Whatever, taking too long, I just pushed the fix.  I did actually test everything.  Two Domi tests failed and I just didn't want to go there.  I enabled everything downstream so nobody complain at me ;-)

**Comment by ibaned** [comment]
I'm all set with this, but should we perhaps keep it open until a unit test is in place ?

**Comment by mhoemmen** [comment]
Ah, thanks @ibaned , good point :)

**Comment by tjfulle** [comment]
@ibaned, I was thinking the same thing.

**Comment by tjfulle** [comment]
Since the function in question, `CrsMatrix::packRowStatic`, that led to this bug is a private member of the CrsMatrix class, it is not easily tested.  For this, and other design considerations, @mhoemmen and I have decided to make `packRowStatic` a nonmember function that takes a `KokkosSparse::CrsMatrix`.  

@mhoemmen, might it be better to put both `packRow` and `packRowStatic` in a new header file `tpetra/core/src/Tpetra_Details_packRow.hpp` (with new functions in the `Tpetra::Details` namespace), rather than just `packRowStatic`?

The following member functions/data are needed in `packRowStatic`:

- `isStaticGraph()`
- `lclMatrix_`
- `staticGraph_`

Call the new functions `crsMatrixPackRow` for the static case (per redesign requirements, we should emphasize the “static” case over the “dynamic” case) and `crsMatrixPackRowDynamic`

**Comment by mhoemmen** [comment]
btw, please use the column Map to convert from local to global.

**Comment by tjfulle** [comment]
@mhoemmen, I committed the new static CrsMatrix packing code, see 904e453bb9fc99c661dfb4a18d548b9137d5d25b.  I haven't yet created the unit tests for the different packing procedures.  I'll get on that and open a PR.  If you see anything before then, let me know!

**Comment by mhoemmen** [comment]
Thanks @tjfulle !  I made some comments on that commit https://github.com/trilinos/Trilinos/commit/904e453bb9fc99c661dfb4a18d548b9137d5d25b .  I only noted a few minor things to change.  Thanks!

**Comment by tjfulle** [comment]
@mhoemmen , sorry, I was away for my kids spring break part of last week.  `Tpetra_Details_packCrsMatrix.hpp` has been modified per your peer review suggestions and a unit test committed (7217289b45ede7b34395e892816b372bce23a7f4).  Running checkin test script now (I've had multiple internal g++ compiler errors on my blade that I have hopefully tracked down and resolved).

**Comment by mhoemmen** [comment]
@tjfulle Nice! :-D  Thanks for working on this!  No need to apologize!

Given the lack of test coverage for this case, I can see the point of turning off downstream packages, but you still might like to test Stokhos just to make sure that it builds.  Otherwise, no worries!

**Comment by tjfulle** [comment]
@mhoemmen, I had a PR ready to go, but littered the git history by inadvertently rebasing when I should have merged...  I'm sure some git ninja could clean it up, I just created a new branch with the changed code (dbcfba8fdf96a2e0f26bb557733664691f04ef26).  All Tpetra tests passed on my workstation, I'm just waiting for a blessing from my blade to open a PR.  The test coverage is still weak - just a single unit test of packCrsMatrix that more than anything tests the interface (the actual matrix/packing is trivial).

Perhaps unrelated, but I thought I'd mention before I forget - the packing routines (both old and updating) take a Distributor object in the calling arguments that is not used.  I'm not sure if it is an artifact or placeholder for future features?

**Comment by mhoemmen** [comment]
@tjfulle wrote:
> I'm sure some git ninja could clean it up, I just created a new branch with the changed code....

If it's just one commit and you want to "copy" it into a different branch, you can do `git cherry-pick $COMMIT` where `$COMMIT` refers to the commit to pull in (e.g., a SHA1).  I quoted "copy" because the result is a different commit (with a different SHA1), even though it retains the original commit message.

> The test coverage is still weak - just a single unit test of packCrsMatrix that more than anything tests the interface (the actual matrix/packing is trivial).

Stokhos actually tests that case, hence the suggestion to turn on some downstream packages.  If you're in a hurry, just enable TpetraCore, Amesos2, Zoltan2, Ifpack2, Xpetra, MueLu, and Stokhos, and disable forward packages.

> Perhaps unrelated, but I thought I'd mention before I forget - the packing routines (both old and updating) take a Distributor object in the calling arguments that is not used. I'm not sure if it is an artifact or placeholder for future features?

Tpetra imitated Epetra.  `Epetra_DistObject`'s pack and unpack methods take an `Epetra_Distributor`.  Your guess sounds reasonable but I'm not quite sure of the design rationale (the whole point of DistObject is to separate the communication pattern from pack and unpack).
Your guess is correct :-)  It

**Comment by mhoemmen** [comment]
@tjfulle fixed it in develop, yay!
