### ISSUE TITLE
Create jenkins tests for GCC 4.9.3 SERIAL and WError and add to dashboard

### ISSUE THREAD

**Issue by william76** [trilinos/Trilinos#1188]
@trilinos/framework 

Get tests for GCC 4.9.3 running and put them onto the Experimental CDash board.

So far, these are the tests in the [Experimental](http://testing.sandia.gov/cdash/index.php?project=Trilinos##Experimental) dashboard:
- Linux-gcc-4.9.3-SERIAL_Release_gcc_4.9.3__DEV
  - @bmpersc pretty much put this one together using his parameterized build.
- Linux-GCC-4.9.3-MPI_Release_Werror_DEV
  - I put this together.  The CMake scripts are in my fork in the [rhel6-x86_64 directory on my gcc-4.9.3-MPI-Werror branch](https://github.com/william76/Trilinos/tree/gcc-4.9.3-MPI-Werror/cmake/ctest/drivers/rhel6-x86_64).

@jwillenbring , @bmpersc : Have a look at the #WError test that's running under experimental to make sure it's running a reasonable configuration so we can decide if I should put in a pull request to move my CMake files over.

**Comment by william76** [comment]
See pull request #1273

**Comment by jwillenbring** [comment]
This was completed when #1273 was merged. Closing.
