### ISSUE TITLE
Tpetra: gap sequence in shell sort

### ISSUE THREAD

**Issue by jhux2** [trilinos/Trilinos#1189]
In the Tpetra shell short, the gap sequence is currently {1,2,4,8,...}.  This could lead to poor performance in some cases.  (See bugzilla bugs [4301](https://software.sandia.gov/bugzilla/show_bug.cgi?id=4301) and [4244](https://software.sandia.gov/bugzilla/show_bug.cgi?id=4244).)   Similar gap sequences were partially fixed in Epetra.

I *haven't* encountered any problems with shell sort in Tpetra, so this issue merely serves to record the matter.

@trilinos/tpetra

**Comment by mhoemmen** [comment]
Thanks @jhux2 !  You are, of course, welcome to contribute :-)

**Comment by jhux2** [comment]
@mhoemmen Yep, I came across this while looking at the SpGEMM, and didn't want to forget it.  Not sure which gap sequence is better, however.

**Comment by jhux2** [comment]
Checkin script is running.

**Comment by jhux2** [comment]
Changed in commit bba86ce.   During the checkin script, these two tests failed:
```
99% tests passed, 2 tests failed out of 917
The following tests FAILED:
	627 - Anasazi_Epetra_ModalSolversTester_MPI_4 (Failed)
	642 - Anasazi_Epetra_OrthoManagerGenTester_1_MPI_4 (Failed)
```
When I reran these by hand, they passed.   That plus the fact that they are Epetra-based makes me comfortable doing a force push.

**Comment by mhoemmen** [comment]
Thanks @jhux2 !

**Comment by mhoemmen** [comment]
btw you can disable tests by adding the following line to your check-in test script invocation:
```
--ctest-options="-E '(Anasazi_Epetra_ModalSolversTester|Anasazi_Epetra_OrthoManagerGenTester_1)'"
```
This is nicer to do than a force-push.  For one thing, it proves that you got the code to build ;-)
