### ISSUE TITLE
Tpetra: Graph / matrix insert doesn't merge, taking extra space & hindering thread parallelism

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#119]
@trilinos/tpetra 

CrsGraph::insert{Local,Global}Indices and CrsMatrix::insert{Local,Global}Values currently do something nonintuitive: multiple inserts to the same row and column index are stored separately and not merged until fillComplete.  For example, inserting (1,1) into a CrsGraph 10 times would require storing 10 entries, until fillComplete, at which point the entries get merged together into a single entry.  This is especially bad for StaticProfile, which currently would counterintuitively fail on 9 of those 10 inserts if the user reasonably gave CrsGraph an upper bound of 1 entry per row.  We don't want users to have to rely on DynamicProfile, which is both slow and (especially due to this issue) memory-intensive.

Commit 68e77d53dbc250add4680244676e47576e6b7e4f begins the process of fixing this.  It does not yet change the behavior of CrsGraph or CrsMatrix.  For now, Tpetra has new internal utility functions for merging indices (for CrsGraph) or indices and values together (for CrsMatrix).  I also added some unit tests for the new functions.  However, they still need to be integrated into CrsGraph and CrsMatrix.  My initial attempts broke a lot of invariants and made a lot of tests fail.  I realize I'll have to do this VERY cautiously.

**Comment by mhoemmen** [comment]
Current status:

  - I need to add patches here (as .txt files, since GitHub doesn't take .patch files).  Patches fail tests but are still worth having as a reference for doing work.

  - For second attempt at fixing this, be more cautious.  In particular, don't try to get rid of lazy allocation.

**Comment by mhoemmen** [comment]
This is story-level, because it needs to be broken up into smaller tasks in order to succeed.
The solution for #601 actually addressed a small part of this for CrsGraph.

**Comment by mhoemmen** [comment]
I've been looking at this.  It turns out that it's not enough to check whether input indices have matching entries currently in the row.  One must also check whether the input itself has duplicates.  Otherwise, if the input is (for example) [1, 1, 1, 1], insertion into an empty row [] would result in [1, 1, 1, 1], but insertion into a row [1] would result in [1].

**Comment by mhoemmen** [comment]
BUMP: This hinders (not actually blocks) https://github.com/trilinos/Trilinos/issues/2267 .  

  1. It makes the "local assembly into owned graph" part of that use pattern more difficult.
  2. It inflates the amount of memory that a fix for #2267 might need.

@william76 @tjfulle

**Comment by mhoemmen** [comment]
@trilinos/tpetra BUMP per @csiefer2 request

**Comment by mhoemmen** [comment]
I have a vague memory that this got fixed early this year, but I might be remembering a different bug.

**Comment by mhoemmen** [comment]
@csiefer2 Did y'all actually fix this?

**Comment by csiefer2** [comment]
Kokkos-level graph assembly (in progress) should render this moot, at least if you're using it.
