### ISSUE TITLE
BLAS and Lapack:  close library check

### ISSUE THREAD

**Issue by DragonPara** [trilinos/Trilinos#11901]
my cmake options
```cmake
cmake ../
          -DTPL_ENABLE_BLAS=ON              \
          -DBLAS_LIBRARY_DIRS='/public/software/compiler/intel/2022/mkl/2022.1.0/lib/intel64' \
          -DBLAS_LIBRARY_NAMES='libstdc++.a' \
          -DTPL_ENABLE_LAPACK=ON \
          -DLAPACK_LIBRARY_DIRS='/public/software/compiler/intel/2022/mkl/2022.1.0/lib/intel64'\
          -DLAPACK_LIBRARY_NAMES='libstdc++.a' \
          -DCMAKE_CXX_FLAGS="-L/public/software/compiler/intel/2022/mkl/2022.1.0/lib/intel64 -qmkl"\
          -DCMAKE_C_FLAGS="-L/public/software/compiler/intel/2022/mkl/2022.1.0/lib/intel64 -qmkl"\
```
I want to use ***blas*** and ***lapack*** of mkl library. but mkl's blas lib not a independent lib, set all libs to `BLAS_LIBRARY_NAMES` is worse than use `-qmkl`. but `-qmkl `can't set in `DBLAS_LIBRARY_NAMES`. I want use `DCMAKE_CXX_FLAGS` instead of it. How to delete `DBLAS_LIBRARY_DIRS` `DBLAS_LIBRARY_NAMES` `DLAPACK_LIBRARY_DIRS` `DLAPACK_LIBRARY_NAMES` options without lib check error

**Comment by jhux2** [comment]
@DragonPara It is possible to specify MKL with the correct cmake configure options.  Please have a look at example 2 in https://docs.trilinos.org/files/TrilinosBuildReference.html#specifying-the-location-of-the-parts-of-an-enabled-external-package-tpl.  Getting the MKL library ordering is sometimes tricky, but once you have it, everything should work.

**Comment by DragonPara** [comment]
After I used your link-advisor, it gave me a long string
` -Wl,--start-group ${MKLROOT}/lib/intel64/libmkl_intel_ilp64.a ${MKLROOT}/lib/intel64/libmkl_sequential.a ${MKLROOT}/lib/intel64/libmkl_core.a -Wl,--end-group -lpthread -lm -ldl`
It's so long. Can we close the search for the blas library by using the cmake options instead of modifying CMakeLists.txt?🙂

**Comment by jhux2** [comment]
There's no need to modify CMakeLists.txt.  It's all done via cmake command line options.  Did you look at the documentation I referenced?  In there is this hint:
```
In this case, one could specify this with the following do-configure script:

#!/bin/bash

INTEL_DIR=/usr/local/intel/Compiler/11.1/064

cmake \
  -D TPL_ENABLE_BLAS=ON \
  -D BLAS_LIBRARY_DIRS="${INTEL_DIR}/em64t;${INTEL_DIR}/intel64" \
  -D BLAS_LIBRARY_NAMES="mkl_intel_lp64;mkl_intel_thread;mkl_core;iomp5" \
  ...
  ${PROJECT_SOURCE_DIR}
```

You should be able to modify this, using the information that advisor produced for your case.
