### ISSUE TITLE
TriKota build issue with gcc-6.3.1

### ISSUE THREAD

**Issue by ikalash** [trilinos/Trilinos#1190]
I recently upgraded the compiler on my Linux workstation to gcc-6.3.1.  With this compiler, I get a compilation error when I build Trilinos with Trikota.  Here is the error: 

[  7%] Building C object packages/common/auxiliarySoftware/SuiteSparse/src/CMakeFiles/trilinosss.dir/AMD/Source/trilinos_amd_post_tree.c.o
/home/ikalash/nightlyAlbanyTests/Results/Trilinos/packages/TriKota/Dakota/packages/DDACE/src/Analyzer/MainEffectsExcelOutput.cpp: In member function ‘std::__cxx11::string MainEffectsExcelOutput::computeExcelOutput(std::vector<std::vector<double> >, std::vector<std::vector<double> >)’:
/home/ikalash/nightlyAlbanyTests/Results/Trilinos/packages/TriKota/Dakota/packages/DDACE/src/Analyzer/MainEffectsExcelOutput.cpp:276:17: error: no match for ‘operator<<’ (operand types are ‘std::ostream {aka std::basic_ostream<char>}’ and ‘std::ostringstream {aka std::__cxx11::basic_ostringstream<char>}’)
       std::cout << ss << std::endl;
       ~~~~~~~~~~^~~~~
/home/ikalash/nightlyAlbanyTests/Results/Trilinos/packages/TriKota/Dakota/packages/DDACE/src/Analyzer/MainEffectsExcelOutput.cpp:276:17: note: candidate: operator<<(int, int) <built-in>
/home/ikalash/nightlyAlbanyTests/Results/Trilinos/packages/TriKota/Dakota/packages/DDACE/src/Analyzer/MainEffectsExcelOutput.cpp:276:17: note:   no known conversion for argument 2 from ‘std::ostringstream {aka std::__cxx11::basic_ostringstream<char>}’ to ‘int’
In file included from /usr/include/c++/6.3.1/istream:39:0,
                 from /usr/include/c++/6.3.1/sstream:38,
                 from /home/ikalash/nightlyAlbanyTests/Results/Trilinos/packages/TriKota/Dakota/packages/DDACE/include/MainEffectsExcelOutput.h:9,
                 from /home/ikalash/nightlyAlbanyTests/Results/Trilinos/packages/TriKota/Dakota/packages/DDACE/src/Analyzer/MainEffectsExcelOutput.cpp:1:
/usr/include/c++/6.3.1/ostream:108:7: note: candidate: std::basic_ostream<_CharT, _Traits>::__ostream_type& std::basic_ostream<_CharT, _Traits>::operator<<(std::basic_ostream<_CharT, _Traits>::__ostream_type& (*)(std::basic_ostream<_CharT, _Traits>::__ostream_type&)) [with _CharT = char; _Traits = std::char_traits<char>; std::basic_ostream<_CharT, _Traits>::__ostream_type = std::basic_ostream<char>]
       operator<<(__ostream_type& (*__pf)(__ostream_type&))
       ^~~~~~~~

This issue did not occur with my old compiler (gcc-4.9.2).  Has anyone else experienced this problem?

**Comment by ikalash** [comment]
@trilinos/developers

**Comment by ikalash** [comment]
@briadam

**Comment by briadam** [comment]
@ikalash This was fixed in the upstream TPL in Nov 2015: https://software.sandia.gov/trac/ddace/changeset/450  These changes would have appeared in Dakota shortly thereafter, certainly in Dakota 6.4.  If you need to patch TriKota's Dakota, you can use the DDACE URL to generate a patch (It's just a missing .str()), otherwise, if time permits, maybe upgrade the Dakota version in use...

**Comment by ikalash** [comment]
Thanks, @briadam .  My nightly test scripts get Dakota as follows: 

wget -nv --no-check-certificate \
 https://development.sandia.gov/dakota/distributions/dakota/votd/Dakota_votd.src.tar.gz 

I am guessing this is a really old version.  What would be the path to a newer version?

**Comment by ibaned** [comment]
https://dakota.sandia.gov/download.html

https://dakota.sandia.gov/content/getting-dakota-source-code

**Comment by briadam** [comment]
Thanks @ibaned  
@ikalash Note that if you login to the site you will be presented with both public Dakota and SNL-internal options, depending on where you will be using it.  Feel free to contact me and Adam Stephens separately if you have issues with SNL-specific versions.

**Comment by ikalash** [comment]
Switching to a newer Dakota resolved the problem.  Thanks!
