### ISSUE TITLE
Tpetra: RCP Thread-safety issues with parallel host backends without setting Teuchos_ENABLE_THREAD_SAFE=ON

### ISSUE THREAD

**Issue by ndellingwood** [trilinos/Trilinos#11921]
## Bug Report
@trilinos/tpetra 

This issue is to relay info from https://github.com/kokkos/kokkos/issues/6082 regarding some RCP thread-safety issues encountered testing Tpetra with Kokkos@develop branch with the OpenMP backend (a couple different testing configurations are posted in the issue)

The problem seems to occur with kernels that capture RCPs, creating multiple copies within OpenMP parallel regions which is not thread-safe without setting `Teuchos_ENABLE_THREAD_SAFE=ON` , e.g.  https://github.com/trilinos/Trilinos/blob/cd2c0a141460b8c8ad028a6034e1333d137b3849/packages/tpetra/core/src/Tpetra_CrsGraph_def.hpp#L5893-L5969 

A couple potential options to resolve this could be to set `Teuchos_ENABLE_THREAD_SAFE=ON` as default, or make sure no RCPs are passed to Kokkos' parallel_* kernels, or ?

Adding @masterleinad who helped triage this

**Comment by jhux2** [comment]
@trilinos/teuchos

**Comment by bartlettroscoe** [comment]
One would have to do some profiling to see the impact of turning on thread safety for RCP, especially in these low-level routines.  Otherwise, I don't have a strong opinion one way or the other.

**Comment by masterleinad** [comment]
Related to https://github.com/trilinos/Trilinos/issues/11931.

**Comment by nmm0** [comment]
Even if `Teuchos_ENABLE_THREAD_SAFE=ON` has too much of a performance implication if enabled globally, it's still necessary to make sure that anything accessed in a parallel kernel is thread safe. So either in this case we need to make sure the RCP is not passed in to the kernel (so the refcount won't race) or to correctly guard RCP in this instance with some sort of lock.

On the Kokkos side, we can't guarantee that thread-unsafe code works.

**Comment by masterleinad** [comment]
> Would a configure-time check in Tpetra requiring Teuchos_ENABLE_THREAD_SAFE=ON if you're using a host-threaded backend work for people?

Sounds reasonable if it doesn't break users' configurations.

**Comment by crtrott** [comment]
We do need a decision on this: we do not promise not to make a copy of the functor per thread inside backends, and I think it would be a serious implementation constraint issue if we did.

**Comment by bartlettroscoe** [comment]
> @bartlettroscoe is the short term plan OK?

@csiefer2, that sounds reasonable to me.

I just wish Trilinos had a comprehensive and robust performance test suite so we could see the performance impact this will have (before we hear it from users if there is an issue with some algorithms).  But note that I suspect that a good bit of this performance critical software could be refactored to use semi-persisting associations (using `Teuchos::Ptr<T>` instead of `Teuchos::RCP<T>`) and avoid passing RCPs into such code (see section "5.12.3 Performance tuning strategies, semi-persisting associations" in [here](https://bartlettroscoe.github.io/publications/TeuchosMemoryManagementSAND.pdf)).

**Comment by bartlettroscoe** [comment]
> @bartlettroscoe I can do a PR and mark you as a reviewer.

👍

**Comment by ndellingwood** [comment]
@csiefer2 mostly, thanks for working on this! There were some changes to kokkos-kernels that need a matching PR to the kokkos-kernels repo (to avoid clobber with the next release), once that goes in we should be in good shape

I enabled `Teuchos_ENABLE_THREAD_SAFE=ON` in our nightly OpenMP builds to verify the setting would resolve the failures in https://github.com/kokkos/kokkos/issues/6082, so these changes should take care of it. Thanks!

**Comment by ndellingwood** [comment]
Matching patch with the changes from https://github.com/trilinos/Trilinos/commit/21e643d7566c5afb5b882641378e9237a1681b70 to kokkos-kernels is up https://github.com/kokkos/kokkos-kernels/pull/1854

**Comment by bartlettroscoe** [comment]
> @csiefer2 mostly, thanks for working on this! There were some changes to kokkos-kernels that need a matching PR to the kokkos-kernels repo (to avoid clobber with the next release), once that goes in we should be in good shape

@ndellingwood, sorry I did not follow up on that right after I made the change and thanks for catching this.  (Not sure why this was not caught in the testing of PR #11863).

**Comment by ndellingwood** [comment]
@bartlettroscoe no worries, thanks for the quick fix with https://github.com/trilinos/Trilinos/commit/21e643d7566c5afb5b882641378e9237a1681b70 👍

**Comment by ndellingwood** [comment]
https://github.com/kokkos/kokkos-kernels/pull/1854 is merged
In an OpenMP nightly build (gcc/8.3 on Power9) with Kokkos Core+Kernels develop branches there was a performance test  failure with `TeuchosCore_RCP_PerformanceTests_basic_MPI_1` following merge of this PR. The build does not run unit tests with parallelism (i.e. `ctest -j1`). If the test is enabled by PR testing should it be disabled to avoid spurious failures? @bartlettroscoe

**Comment by bartlettroscoe** [comment]
> In an OpenMP nightly build (gcc/8.3 on Power9) with Kokkos Core+Kernels develop branches there was a performance test failure with `TeuchosCore_RCP_PerformanceTests_basic_MPI_1` following merge of this PR.

@ndellingwood, can you run `make dashboard` and post this to CDash?

**Comment by ndellingwood** [comment]
> @ndellingwood, can you run `make dashboard` and post this to CDash?

@bartlettroscoe I don't have the nightly build configured to post to CDash, it's on my list of TODOs. Is it helpful if I point you to the Jenkins build for now? https://jenkins-son.sandia.gov/job/KokkosEco_Trilinos_Weaver_Gcc830_OpenMP_opt/251/consoleFull
