### ISSUE TITLE
Sacado: compilation fails on HIP when using `Sacado_Fad_Exp_Atomic` (syntax)

### ISSUE THREAD

**Issue by romintomasetti** [trilinos/Trilinos#11924]
# Bug Report

@trilinos/sacado

Looking at:
https://github.com/trilinos/Trilinos/blob/0a376ba29537c19384056f04d8925d7587bc3dc3/packages/sacado/src/new_design/Sacado_Fad_Exp_Atomic.hpp#L317
it is clear that it will not compile on HIP (this is enclosed in a `KOKKOS_ENABLE_HIP`) because of `desul:atomic_` instead of `desul::atomic_` (note the double column).

@etphipp I wonder how this was not detected by the CI?

**Comment by etphipp** [comment]
Fixed.

**Comment by romintomasetti** [comment]
@etphipp Just for us to understand, you mean there is no test generated by CMake for Sacado when compiling on HIP or do you mean Trilinos never tests for HIP ?

**Comment by etphipp** [comment]
Trilinos does not currently test on HIP.  There are plans to, but I don't believe we have the hardware setup yet.
