### ISSUE TITLE
teuchos:  Error when compiling with g++ 13.1.1

### ISSUE THREAD

**Issue by bradbell** [trilinos/Trilinos#11923]
## Bug Report
@bartlettroscoe

### Description

    ... /Trilinos-trilinos-release-14-0-0/packages/teuchos/core/src/Teuchos_BigUIntDecl.hpp:67:8:  error: ‘uint32_t’ in namespace ‘std’ does not name a type; did you mean ‘wint_t’?
        67 |   std::uint32_t x[n];

### Bug Fix
Add the following line directly below #include <iosfwd> in Teuchos_BigUIntDecl.hpp:

    #include <cstdint>

### Steps to Reproduce
The cmake command below must choose version 13.1.1 of the g++ compiler:

1. wget https://github.com/trilinos/Trilinos/archive/refs/tags/trilinos-release-14-0-0.tar.gz
2. tar -xzf trilinos-release-14-0-0.tar.gz
3. cd Trilinos-trilinos-release-14-0-0
4. mkdir build
5. cd build
6. cmake -D Trilinos_ENABLE_Sacado=ON ..
7. make

**Comment by bartlettroscoe** [comment]
@bradbell, would you mind putting in a PR to address this and verify it fixes things on your end?  Note that the most recent version of g++ being tested with Trilinos looks to be GNU 10.1.0 (as part of the `rhel7_sems-cuda-11.4.2-sems-gnu-10.1.0-sems-openmpi-4.0.5` build, see [here](https://github.com/trilinos/Trilinos/pull/11811#issuecomment-1558124090) for example).  Note the support policy for Trilinos w.r.t. compilers and MPI versions [here](https://github.com/trilinos/Trilinos/blob/master/INSTALL.rst#support-for-different-compilers-mpis).

**Comment by bradbell** [comment]
The fix is already in the master branch; see lines 45 and 46 of
https://github.com/trilinos/Trilinos/blob/master/packages/teuchos/core/src/Teuchos_BigUIntDecl.hpp
where the following text now appears:
```
#include <iosfwd>
#include <cstdint>
```

**Comment by GrahamBenHarper** [comment]
Thank you for the update @bradbell! I'll link #11676 for posterity.
