### ISSUE TITLE
Tribits:  PR#11808 breaks kokkos configure with TPL_ENABLE_HWLOC=ON

### ISSUE THREAD

**Issue by maartenarnst** [trilinos/Trilinos#11938]
## Bug Report

@bartlettroscoe

### Description

We're compiling Trilinos with `TPL_ENABLE_HWLOC=ON`. Configure aborts in Kokkos on line 

- https://github.com/trilinos/Trilinos/blob/6e909bbd7ddad6a1177ea78813048f400dc4bbe4/packages/kokkos/cmake/kokkos_tpls.cmake#L29 

It seems the issue is due to a change in PR #11808:

- https://github.com/trilinos/Trilinos/blob/6e909bbd7ddad6a1177ea78813048f400dc4bbe4/packages/kokkos/cmake/Dependencies.cmake#L2

It seems the issue can be solved by replacing `KOKKOS_TPL_OPTION(HWLOC   Off)` on line 34 in `kokkos_tpls.cmake` with `KOKKOS_TPL_OPTION(HWLOC   Off TRIBITS HWLOC)`.

**Comment by bartlettroscoe** [comment]
@trilinos/kokkos

**Comment by bartlettroscoe** [comment]
@maartenarnst, FYI, this should be address in Trilinos PR #11863 (commit https://github.com/trilinos/Trilinos/pull/11863/commits/6bffd4453c77f5f96c3db4eb0d4dcb6644c14f66) and Kokkos PR https://github.com/kokkos/kokkos/pull/6176.

**Comment by maartenarnst** [comment]
Thanks a lot!
