### ISSUE TITLE
Tpetra:  incorrect behavior when a non-trivial series of moves are happening

### ISSUE THREAD

**Issue by fnrizzi** [trilinos/Trilinos#11931]
## Bug Report
@csiefer2

### Description

i am trying to create a "registry" (a struct) holding instances of tpetra block vectors and then move the registry object to another object `Foo` that owns that registry and use it inside of it. See below the usecase. 
if i create the registry directly and move it to the constructor of `Foo`, all extents printed make sense.
If i create an instance of `Foo` by calling `createFoo`, then things do not work. 

```cpp
#include <Tpetra_Core.hpp>
#include <Tpetra_BlockVector.hpp>
#include <Tpetra_Map.hpp>
#include <Teuchos_CommHelpers.hpp>
#include <Tpetra_Map_decl.hpp>


using tcomm    = Teuchos::Comm<int>;
using map_t    = Tpetra::Map<>;
using vec_type = Tpetra::BlockVector<>;

class MyObject{
private:
  map_t map_;
public:
  using state_type = vec_type;

  MyObject(){
    Teuchos::RCP<const tcomm> comm_ = Teuchos::rcp (new Teuchos::MpiComm<int>(MPI_COMM_WORLD));
    const int numGlobalEntries = 15*comm_->getSize();
    map_ = map_t(numGlobalEntries, 0, comm_);
  }
  state_type createState() const{
    state_type v(map_, 5);
    return v;
  }
};

template<class DT1, class DT2>
struct Registry{
  DT1 d1_;
  DT2 d2_;
  DT1 & getA(){ return d1_; }
  DT2 & getB(){ return d2_; }
};

void print(int rank, const std::string & s1, const std::string & s2, vec_type r){
  std::cout << "\n";
  auto tpmv  = r.getVectorView();
  std::cout << s1 << "ext = " << r.getMap()->getGlobalNumElements() << "\n";
  std::cout << s2 << "ext = " << tpmv.getMap()->getGlobalNumElements() << "\n";
}

template<class RegistryType>
class Foo{
  int rank_;
  RegistryType reg_;
public:
  Foo(RegistryType && reg) : reg_(std::move(reg))
  {
    MPI_Comm_rank(MPI_COMM_WORLD, &rank_);
    auto & a = reg_.getA();
    auto & b = reg_.getB();
    print(rank_, "CONSTR-block-A ", "CONSTR-tpetr-A ", a);
    print(rank_, "CONSTR-block-B ", "CONSTR-tpetr-B ", b);
  }

  void dummy() {
    auto & a = reg_.getA();
    auto & b = reg_.getB();
    print(rank_, "DUMMY-block-A ", "DUMMY-tpetr-A ", a);
    print(rank_, "DUMMY-block-B ", "DUMMY-tpetr-B ", b);
  }
};

template<class T>
auto createFoo(const T& system){
  using state_t    = typename T::state_type;
  using registry_t = Registry<state_t, state_t>;
  registry_t reg{system.createState(), system.createState()};
  return Foo<registry_t>(std::move(reg));
}

template<class T>
auto createRegistry(const T & system){
  using state_t    = typename T::state_type;
  using registry_t = Registry<state_t, state_t>;
  registry_t reg{system.createState(), system.createState()};
  return reg;
}

int main(int argc, char **argv)
{
  Tpetra::ScopeGuard tpetraScope (&argc, &argv);
  {
    {
      std::cout << "starting case that works\n";
      MyObject object;
      auto reg = createRegistry(object);
      Foo<decltype(reg)> f(std::move(reg));
      f.dummy();
    }

    {
      std::cout << "\n";
      std::cout << "\n";
      std::cout << "starting case that does NOT work\n";
      MyObject object;
      auto f = createFoo(object);
      f.dummy();
    }
  }

  return 0;
}
```
prints: 
```
starting case that works

CONSTR-block-A ext = 15
CONSTR-tpetr-A ext = 75

CONSTR-block-B ext = 15
CONSTR-tpetr-B ext = 75

DUMMY-block-A ext = 15
DUMMY-tpetr-A ext = 75

DUMMY-block-B ext = 15
DUMMY-tpetr-B ext = 75


starting case that does NOT work

CONSTR-block-A ext = 15
CONSTR-tpetr-A ext = 75

CONSTR-block-B ext = 15
CONSTR-tpetr-B ext = 75

DUMMY-block-A ext = 15
DUMMY-tpetr-A ext = 1

DUMMY-block-B ext = 15
DUMMY-tpetr-B ext = 75
```
Notice how in the second part we get `DUMMY-tpetr-A ext = 1` instead of 75. 

### Steps to Reproduce
1. SHA1: 3cf925bab1d6ac071e5aff9671cce5a5889accf2  but I found out this happens even with the ef73d14babf6e7556b0420add98cce257ccaa56b
1. Configure script: 
```
cmake -D CMAKE_BUILD_TYPE:STRING=Debug -D BUILD_SHARED_LIBS:BOOL=ON -D TPL_FIND_SHARED_LIBS=ON -D Trilinos_LINK_SEARCH_START_STATIC=OFF -D CMAKE_VERBOSE_MAKEFILE:BOOL=TRUE -D TPL_ENABLE_MPI:BOOL=ON -D MPI_C_COMPILER:FILEPATH=/Users/fnrizzi/Desktop/work/tpls/openmpi/install-gcc11/bin/mpicc -D MPI_CXX_COMPILER:FILEPATH=/Users/fnrizzi/Desktop/work/tpls/openmpi/install-gcc11/bin/mpic++ -D MPI_EXEC:FILEPATH= -D MPI_USE_COMPILER_WRAPPERS:BOOL=ON -D Trilinos_ENABLE_Fortran:BOOL=ON -D MPI_Fortran_COMPILER:FILEPATH=/Users/fnrizzi/Desktop/work/tpls/openmpi/install-gcc11/bin/mpifort -D Trilinos_ENABLE_TESTS:BOOL=OFF -D Trilinos_ENABLE_EXAMPLES:BOOL=OFF -D TPL_ENABLE_BLAS=ON -D TPL_ENABLE_LAPACK=ON -D Kokkos_ENABLE_SERIAL:BOOL=ON -D Kokkos_ENABLE_THREADS:BOOL=OFF -D Kokkos_ENABLE_OPENMP:BOOL=OFF -D Kokkos_ENABLE_DEPRECATED_CODE=OFF -D Trilinos_ENABLE_ALL_PACKAGES:BOOL=OFF -D Trilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=OFF -D Trilinos_ENABLE_Teuchos:BOOL=ON -D Trilinos_ENABLE_Epetra:BOOL=ON -D Trilinos_ENABLE_Tpetra:BOOL=ON -D Tpetra_ENABLE_DEPRECATED_CODE:BOOL=OFF -D Tpetra_ENABLE_TSQR:BOOL=ON -D Trilinos_ENABLE_EpetraExt:BOOL=ON -D Trilinos_ENABLE_AztecOO:BOOL=ON -D Trilinos_ENABLE_Ifpack:BOOL=ON -D Trilinos_ENABLE_Ifpack2:BOOL=ON -D Trilinos_ENABLE_ROL:BOOL=ON -D CMAKE_INSTALL_PREFIX:PATH=../install ../Trilinos
```

1. Configure log:  [log.txt](https://github.com/trilinos/Trilinos/files/11611268/log.txt)
2. Compiler: gcc11-3.0 and openmpi 4.1.3 (however the code is run with just 1 rank)

<br>
<br>
<br>

# Smaller reproducer and a solution that works 

I was able to do this: 
- smaller reproducer:  taking all the relevant classes from source code and strip out everything that is not needed
[tpetra_moving_bug_reproducer.txt](https://github.com/trilinos/Trilinos/files/11612073/tpetra_moving_bug_reproducer.txt)
This code prints the same as above.

- one solution to this: i was able to make things work if I change the way the map is stored inside the `DistObject` class. 
if i store it by value instead of using the rcp, things work: 
[tpetra_moving_bug_fix.txt](https://github.com/trilinos/Trilinos/files/11612089/tpetra_moving_bug_fix.txt) and this prints:
```
starting case that works

CONSTR-block-A ext = 15
CONSTR-tpetr-A ext = 75

CONSTR-block-B ext = 15
CONSTR-tpetr-B ext = 75

DUMMY-block-A ext = 15
DUMMY-tpetr-A ext = 75

DUMMY-block-B ext = 15
DUMMY-tpetr-B ext = 75


starting case that does NOT work

CONSTR-block-A ext = 15
CONSTR-tpetr-A ext = 75

CONSTR-block-B ext = 15
CONSTR-tpetr-B ext = 75

DUMMY-block-A ext = 15
DUMMY-tpetr-A ext = 75

DUMMY-block-B ext = 15
DUMMY-tpetr-B ext = 75
```

**Comment by masterleinad** [comment]
Related to https://github.com/trilinos/Trilinos/issues/11921.

**Comment by jhux2** [comment]
@trilinos/tpetra

**Comment by fnrizzi** [comment]
@csiefer2 thanks for the comment! 
my issue above was with the serial backend on, how is that related to the threads backend?

**Comment by fnrizzi** [comment]
@csiefer2 no worries! as written above, this issue pops up from a very recent sha and also a quite older one so it doees not look like anything new

**Comment by fnrizzi** [comment]
Can you paste here the unit test? Just curious

**Comment by fnrizzi** [comment]
Yea that outrageous number appeared to me too , I don't remember when exactly but I saw that as well. 

Also, please note that above there are 2 shas that give me the wrong behavior. And on sha is pretty old , I think a year ago or so

**Comment by fnrizzi** [comment]
Yes weird indeed... btw the tentative solution I posted above worked and that seems to indicate it has something to do with the teuchos rcp inside the DistObject base class

**Comment by brian-kelley** [comment]
The bad MultiVector is probably off in uninitialized memory, maybe valgrind will give some useful info about what's going on

**Comment by cwpearson** [comment]
To expand a bit...

A `BlockMultiVector` has a member `MultiVector mv_`.
The `BlockMultiVector` ctor takes a reference to a map, uses that to construct a member map, gets an RCP from that member map with `rcpFromRef`:

https://github.com/trilinos/Trilinos/blob/2f8614ce01b61271bad2ccbc96e8d226124ebae6/packages/teuchos/core/src/Teuchos_RCPDecl.hpp#L1287-L1297

and then passes that **NON-OWNING** rcp to the `mv_`: 

https://github.com/trilinos/Trilinos/blob/2960af596efdd3ddb7029d3fab57c8e81533432c/packages/tpetra/core/src/Tpetra_BlockMultiVector_def.hpp#L90-L91

I think the comment on line 91 is wrong, because `pointMap_` may in fact "go away", if the BMV is moved (`pointMap_` is a map, not an `RCP<map>`)!

A fair number of the `BlockMultiVector` copy- and move-ctors are defaulted:

https://github.com/trilinos/Trilinos/blob/2960af596efdd3ddb7029d3fab57c8e81533432c/packages/tpetra/core/src/Tpetra_BlockMultiVector_decl.hpp#L219-L231

So when `BMV` gets moved, the `MV` will also get moved, but that non-owning RCP inside `mv_` will still point back to the map in the moved-from `BMV`, which may cause an error if the moved-from BMV is overwritten or otherwise invalid (which is permitted after a move).

I'm not sure exactly why this hasn't cropped up before, except that if people have been using `RPC<BMV>`, it's conceivable they won't have this problem because the heap-allocated BMV is not ever moved.

A big-picture solution might be be to make `Teuchos::RCP` always owning (a la `std::shared_ptr`), and have a non-owning pointer be a separate type (`std::weak_ptr`). Then misusing a non-owning pointer as an owning pointer (as in the multivector map) would be a compile-time error.

**Comment by fnrizzi** [comment]
@csiefer2 
> What's the real end goal for this registery thing?
The use case I reported above reproduces exactly what i need: an instance of the registry is something that stores the data and then this registry instance is moved to another object (a Foo instance) who would then own it permanently and manager its lifetime. 

Specifically, the real use case is for implementing nonlinear solvers:

https://github.com/Pressio/pressio/tree/9d59e3235d743fdac29ec91a4dab76a3e471efae/include/pressio/solvers_nonlinear

The registry is the "registry" storing a bunch of operators and things we need. 
This registry is then moved to the actual nonlinear solver object that would own it.

**Comment by fnrizzi** [comment]
@csiefer2 thanks for the reply! 

> std::move does not play nicely with pointers

Why std::move should not play nice with pointers? You means with Teuchos RCPs specifically or in general? 

> there's a very real chance this won't be the only bug like this you see.

yeah that is fine, if I can help finding them, am happy to :) 
if the move operations are not well tested in tpetra, that is fine too
