### ISSUE TITLE
Tpetra::MultiVector: cublas{D,S}gemm interface change?

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#1194]
@trilinos/tpetra

@mwglass reported build errors in tpetra/core/src/kokkos_refactor/Kokkos_MV_GEMM.hpp, relating to a wrong first argument for cublasSgemm and cublasDgemm.  It looks like he is seeing a different cuBLAS header file than we are.  This could be an artifact of how he builds Trilinos, but it reminds me that we need to check whether there are interface changes coming for those cuBLAS functions that could break the build in the near future.

Subtasks:
- [x] Research interface changes and associated cuBLAS version numbers for these functions
- [x] If needed, implement a work-around in Tpetra
- [x] Discuss a better interface in KokkosKernels for GEMM functionality (#1195)

**Comment by mwglass** [comment]
There is a cublas.h and a cublas_v2.h file in the cuda include dir. The v2 file has a cublasHandle_t argument add at the beginning of the arg list. We must be picking up that header somewhere.

**Comment by mhoemmen** [comment]
Thanks @mwglass !  The cuBLAS manual says that "Starting with version 4.0, the cuBLAS Library provides a new updated API, in addition to the existing legacy API. . . . The new cuBLAS library API can be used by including the header file 'cublas_v2.h'." 

http://docs.nvidia.com/cuda/cublas/

The manual also says: "In general, new applications should not use the legacy cuBLAS API, and existing existing applications should convert to using the new API if it requires sophisticated and optimal stream parallelism or if it calls cuBLAS routines concurrently from multiple threads."

This suggests that Tpetra needs to switch to the new interface in cublas_v2.h.  Would that fix this issue for you?

**Comment by mhoemmen** [comment]
@mwglass -- another approach would be for Tpetra to hide the 'cublas.h' header file include in a .cpp file.  This should be quicker to do than what I described in my previous comment.  I will try that first.  Later we can go back and use the new API.

I would prefer to defer using the new API, because it requires global initialization and finalization of a context object.  I'll have to be careful to see how that interacts with `Kokkos::Cuda::finalize`, in particular, whether it needs to be called before `Kokkos::Cuda::finalize`.  See https://github.com/kokkos/kokkos/issues/714 for a Kokkos feature request that could make this easier.

**Comment by mwglass** [comment]
Thanks for the update. I will also see if I can track down how we are picking up the new api header file in our builds.

**Comment by mhoemmen** [comment]
CUDA and non-CUDA builds build.  Just did a rebase so I have to rebuild.  I'm running CUDA tests now.

**Comment by mhoemmen** [comment]
I'm attaching a patch that fixes the issue.  Check-in tests almost done.

[patch.txt](https://github.com/trilinos/Trilinos/files/883206/patch.txt)

**Comment by mhoemmen** [comment]
@mwglass I just pushed a fix to develop.  See my previous comment for a patch that fixes the issue.

Note to myself: this issue came up because of actual use of cuBLAS v2 API (not just the header file) in an application.  That justifies hiding the v1 header file.

**Comment by mwglass** [comment]
Thanks!
