### ISSUE TITLE
Framework:  PR results have gaps in them

### ISSUE THREAD

**Issue by jhux2** [trilinos/Trilinos#11956]
@trilinos/framework 

Results look spotty.

https://trilinos-cdash.sandia.gov/index.php?project=Trilinos&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=PR-&field2=buildstarttime&compare2=84&value2=NOW&field3=buildstarttime&compare3=83&value3=NOW-24hours

**Comment by sebrowne** [comment]
Oh wonderful.  I checked and the pass/fail status is correct, #11840 had errors.  But the submission code didn't have an issue, it thinks the results made it to CDash successfully.  I'm really hoping this is just a temporary server load deal, that's happened before.  I'll monitor the dashboard and see if they start showing up again.  If not, we'll have to get Kitware to look at the server.

**Comment by jhux2** [comment]
@sebrowne Short of retesting, is there any way to see the errors?

**Comment by sebrowne** [comment]
Not easily no.  I can manually email you the console output, but that won't have build issues, only tests.  And I'd have to do it for each build :(

Unfortunately, I'd suggest retesting.

**Comment by sebrowne** [comment]
Okay, looks like my hunch was correct.  The results are now showing up in your given link.  Can we close this and hope that it was just a transient issue with the CDash server?
