### ISSUE TITLE
Zoltan:  question about Zoltan_config.h

### ISSUE THREAD

**Issue by RongquanHE** [trilinos/Trilinos#11960]
### Description
Trilinos/Trilinos/packages/zoltan/src/include/Zoltan_config.h, the file named by Zoltan_config.h.in, I think it is a mistake.

**Comment by jhux2** [comment]
@RongquanHE Could you please be more specific?  If you're running into configure or build problems, please provide instructions to reproduce.

@trilinos/zoltan

**Comment by jhux2** [comment]
Closing due to lack of information.  Please reopen if you can provide more details.
