### ISSUE TITLE
Ifpack_SparseContainer can't be used without initializing MPI

### ISSUE THREAD

**Issue by Sbte** [trilinos/Trilinos#1196]
`Ifpack_SparseContainer` can't be used when Trilinos is compiled with MPI support but it is used without calling `MPI_Initialize`. This happens because a serial MPI communicator is instantiated in the constructor:

https://github.com/trilinos/Trilinos/blob/master/packages/ifpack/src/Ifpack_SparseContainer.h#L323

A case where one might want to use this without calling `MPI_Initialize` is when `Epetra_SerialComm` is used for all vectors and matrices. Is there any reason why `Epetra_MpiComm(MPI_COMM_SELF)` is used instead of `Epetra_SerialComm` in `Ifpack_SparseContainer`? If not I can submit a pull request that gets rid of this if you like.

**Comment by mhoemmen** [comment]
@Sbte Thanks for reporting!  It's a bit of a strange use case to use Epetra and downstream packages with MPI enabled, but not with MPI communicators.  On the other hand, it's certainly possible that users might try this.  I much prefer using MPI if it is available, including `MPI_COMM_SELF`.  How about this:
```
#ifdef HAVE_MPI
  if (MPI is initialized) { // you can ask this, because mpi.h gets included
    SerialComm_ = Teuchos::rcp( new Epetra_MpiComm(MPI_COMM_SELF) );
  }
  else {
    SerialComm_ = Teuchos::rcp( new Epetra_SerialComm );
  }
#else
  SerialComm_ = Teuchos::rcp( new Epetra_SerialComm );
#endif
```
Please feel free to submit a pull request.  Thanks!

**Comment by Sbte** [comment]
@mhoemmen Yes, I can do that. I was just wondering what the advantage is of using `MPI_COMM_SELF` over `Epetra_SerialComm`. I suppose that they are at least supposed to do the same thing. If not it might explain some of the errors that I get at the moment :)

I myself use it in an interface between our code and Matlab by the way, just so we can more easily try out and debug some things. And in that case I prefer not to use MPI.

**Comment by mhoemmen** [comment]
@Sbte wrote:
> I was just wondering what the advantage is of using `MPI_COMM_SELF` over Epetra_SerialComm. I suppose that they are at least supposed to do the same thing. If not it might explain some of the errors that I get at the moment :)

With respect to Epetra, they are supposed to do the same thing.  However, if your application actually uses MPI, using `Epetra_MpiComm` everywhere (even with `MPI_COMM_SELF`) means that you can always get the `MPI_Comm` out of the `Epetra_Comm` (via `dynamic_cast`) and do MPI things with it -- e.g., `MPI_Intercomm_create`, attach key-value pairs to it, and use it in `MPI_Pack`.  It also means that if you use MPI profiling tools, the tools will capture operations on that `Epetra_Comm`.
