### ISSUE TITLE
AztecOO:  Problem size limit despite available memory

### ISSUE THREAD

**Issue by max-si** [trilinos/Trilinos#11965]
## Question
@trilinos/aztecoo @rstumin

I am hitting a limit on the size of matrix that can be solved on a single compute node, regardless of how much memory is available on the node. The maximum size I can solve is a 50 million by 50 million matrix, using the AZ_gmres solver with AZ_kspace = 20. I have tested this issue on three HPC clusters with memory per node of 96 GB, 256 GB, and 512 GB, and the maximum problem size is the same for each.  

When I double the size of the matrix (100 million by 100 million), there is a seg fault after a few iterations. Using the GNU "time -v" tool I see the Maximum resident set size is 39270700 kB (39.27 GB) for the 50x50 million matrix program and 80354276 kB (80.35 GB) for the 100x100 million matrix program. Even on the cluster with the least memory (96 GB), calling "free -h" shows 88 GB of "available memory" which should be enough for the problem. 

Is there a reason the solver is not utilizing all the available memory?

**Comment by cgcgcg** [comment]
AztecOO is using legacy linear algebra provided by Epetra. This means in particular that the local ordinal type is hard coded. All bets are off what happens once you run out of that.

**Comment by max-si** [comment]
I finally got around to

**Comment by max-si** [comment]
Finally got around to rewriting it using Teptra and Belos. Fixed the issue and improved execution time. Thanks for the tip.
