### ISSUE TITLE
Amesos2 Stratimikos adapter: Failing example

### ISSUE THREAD

**Issue by cgcgcg** [trilinos/Trilinos#11983]
## Bug Report

The Amesos2 Stratimikos adapter is enabled when
https://github.com/trilinos/Trilinos/blob/f71c76a93b4c320c9c0d20bf8bc88020ca99b59f/packages/stratimikos/adapters/CMakeLists.txt#L29-L34

The example driver tests Amesos2 without checking the status of KLU2:
https://github.com/trilinos/Trilinos/blob/f71c76a93b4c320c9c0d20bf8bc88020ca99b59f/packages/stratimikos/example/tpetra/CMakeLists.txt#L4-L11
and fails when KLU2 is not available:
https://testing.sandia.gov/cdash/test/161831268

What needs to happen here? Does the adapter in fact only work for KLU2? Or would it also work for other solvers?

**Comment by cgcgcg** [comment]
@srajama1 @ndellingwood Any guidance?

**Comment by ndellingwood** [comment]
@cgcgcg I'm inexperienced with Stratimikos and this driver, so I think the safe bet is to assume this only works for KLU2 as a starting point based on the adapter check (might work for others, but would require testing to confirm) and update the example check to only add the driver if KLU2 is enabled (so update [Trilinos/packages/stratimikos/example/tpetra/CMakeLists.txt](https://github.com/trilinos/Trilinos/blob/f71c76a93b4c320c9c0d20bf8bc88020ca99b59f/packages/stratimikos/example/tpetra/CMakeLists.txt#L5 to something like `EXCLUDE_IF_NOT_TRUE ${PACKAGE_NAME}_ENABLE_Amesos2 AND Amesos2_ENABLE_KLU2`). Does that sound reasonable for now?

**Comment by cgcgcg** [comment]
Thanks @ndellingwood. I update the CMake logic then.
