### ISSUE TITLE
Tpetra:  Better user input checking in convertToBlockCrsMatrix

### ISSUE THREAD

**Issue by jgfouca** [trilinos/Trilinos#11984]
## Enhancement
@csiefer2 

I recently tried using convertToBlockCrsMatrix from Tpetra_BlockCrsMatrix_Helpers and I kept getting matrices with bad entries back. Fortunately there was some comments in the implementation that made it clear that the converter expected the incoming CRS matrix to have all the non-empty blocks to be fully populated, with zeroes if need be. Once I "filled" my CSR, the routine worked fine. It would have been nice if, at least in debug mode, this condition was checked and a clear error message provided.

I have implemented a "block fill" routine that I will submit in a future PR.

**Comment by cgcgcg** [comment]
@trilinos/tpetra
