### ISSUE TITLE
Framework: AT issues related to Github outage

### ISSUE THREAD

**Issue by GrahamBenHarper** [trilinos/Trilinos#12010]
@trilinos/framework @sebrowne

It looks like the Github outage broke the autotester. See #12006 and #12008 for example, reporting an internal communication error.

**Comment by sebrowne** [comment]
I think this is fixed.  The CEE outage caused some issues on the automation server, but I think I restored the good configuration now.  I'm RETESTing 12006, and if it works I'll go RETEST the others that have failed this afternoon.

**Comment by sebrowne** [comment]
Confirmed that it's running again.  Reopen if issue reoccurs.

**Comment by GrahamBenHarper** [comment]
Thank you @sebrowne!
