### ISSUE TITLE
Belos:  BlockGmresSolMgr significantly slower on CUDA when not using UVM

### ISSUE THREAD

**Issue by ddement** [trilinos/Trilinos#12029]
@srajama1

We have been doing a series of experiments in Nalu-Wind regarding the removal of UVM from CUDA runs.  When Trilinos is built without UVM, most regression tests run slightly faster than with it.  However, one case runs approximately 30x slower when UVM is not used.  In particular, this slowdown has been traced primarily to the "BlockGmresSolMgr total solve time" and "ICGS[2]: Ortho (Norm)" timing lines from Belos.  Several other regression tests exercise other Belos solvers, and none of them show similar regressions.  

Unfortunately, the reproducer for this case is a Nalu-Wind regression test - we do not have a more minimal problem.  The regression test in question is the "taylorGreenVortex_p3" test.  We can assist with running and debugging as necessary.  @jhux2 may also have experience with running this case.

**Comment by jhux2** [comment]
@trilinos/belos

**Comment by jhux2** [comment]
@ddement #11837 is in progress to address GMRES orthogonalization in Belos.  I'm wondering if you are running into the case that the PR is addressing.

**Comment by cgcgcg** [comment]
Maybe related: #9979 ?

**Comment by jhux2** [comment]
@ddement Do you know if the 30x slowdown is in the velocity, continuity, or both phases?  It's been quite a while since I ran this test case.

**Comment by ddement** [comment]
@jhux

It is used for the velocity solve.  Continuity uses BiCGStab, which is a little slower (a couple seconds) on this particular run, but nowhere near the 30x number.  

I'll take a look at the other PRs to see if I think they're related - I would not be surprised if they are.
