### ISSUE TITLE
Query nonlinear solver state from Thyra::ModelEvaluator

### ISSUE THREAD

**Issue by ibaned** [trilinos/Trilinos#1204]
This is actually a high-level design issue for Albany, but I'm opening it as a Trilinos issue to get feedback from Trilinos developers.

In Albany, we interface with non-linear solvers like NOX through a `Thyra::Model Evaluator` derived class. Most of the interesting interaction happens through the `evalModelImpl` method.

The NOX algorithm goes roughly like this:

```cpp
while(1) {
  residual = ask_for_residual(x);
  if (is_converged (residual)) break;
  jacobian = ask_for_jacobian(x);
  step = solve_linear_system (jacobian, residual);
  x += step;
}
```

The two pseudo-code ask_for calls become separate calls to `evalModelImpl`, both times `inArgs` has `x`, once `outArgs` has `W_op` and the second time `outArgs` has `f`.

The first problem is that we are starting to consider various modifications of the residual which are based on jacobian information. One example of this is scaling linear system rows based on diagonal values. Issue gahansen/Albany#55 illustrates well why this failed: we don't know which residual queries correspond to which jacobian queries. Even better for us would be if we were informed when the solution is update between one step and the next. From this we could infer associated queries.

While row scaling is something that NOX  could implement, we are also considering similar modifications that are based on Dirichlet boundary condition information, which NOX can't access natively.

A second, related problem is that it may make sense to use the non-modified residual for convergence checking and the modified residual for linear system solution. The reason is to avoid artificially changing the tolerance as a consequence of scaling. This would require some mechanism for updating the residual between the two steps.

As I think about this, I could envision a NOX PrePostOperator could handle the DBC operations too,  if it could be defined in Albany and then given to NOX. This would have to go through Piro, though maybe would not require different use of Thyra...

@lxmota @agsalin @trilinos/thyra @trilinos/nox @gahansen @bartgol

**Comment by ibaned** [comment]
@bgranzow

**Comment by lxmota** [comment]
Another situation where this arises is in our implementation of the Schwarz alternating method, where multiple subdomains are coupled. The global solution is obtained through a Schwarz loop that for each iteration requires a NOX nonlinear solve for each of the subdomains. The convergence criterion for the Schwarz loop requires knowledge of the solution before and after the NOX solve for each subdomain, but this is not available at that level.

**Comment by rppawlo** [comment]
@ibaned NOX does support row sum scaling and in some cases we do disable the scaling in StatusTest checks (partial but not complete support for this). Disabling the checks can be dangerous depending on the algorithm being used. I'm in Albuquerque this week. Can we meet and discuss in more detail?

**Comment by ibaned** [comment]
Thanks @rppawlo . I'll follow up with you by email tomorrow.

**Comment by ibaned** [comment]
Just had a great meeting with @rppawlo . We went over the existing scaling implementations, both in NOX via PrePostOperators and implicit scaling in NOX Vectors, and the Rythmos Observer in Piro. While the matrix/vector modifications for Dirichlet boundary conditions could in theory be implemented as one or more NOX PrePostOperators, what we will probably try initially is to simply use a NOX PrePostOperator to indicate to Albany the start and end of non-linear solver iterates.

This should probably move back to the Albany repository for in-depth discussion on what we do there, that will be in gahansen/Albany#105

**Comment by bartlettroscoe** [comment]
I just saw this issue (I did not get a notification email).  Is this still a valid issue?  If not, can we close?

**Comment by ibaned** [comment]
This can definitely be closed, thanks for checking.

**Comment by bartlettroscoe** [comment]
> This can definitely be closed, thanks for checking.

Closing as "worksforme".
