### ISSUE TITLE
Seacas: undefined reference to NetCDF function

### ISSUE THREAD

**Issue by ikalash** [trilinos/Trilinos#12045]
The Albany Trilinos nightlies on my RHEL8 workstation failed last night for the first time with the following error: 

```
[2910/6628] Linking CXX executable packages/seacas/applications/aprepro/aprepro
FAILED: packages/seacas/applications/aprepro/aprepro
: && /tpls/install/bin/mpicxx -pedantic -Wall -Wno-long-long -Wwrite-strings -Wshadow -Woverloaded-virtual    -O3 -DNDEBUG  packages/seacas/applications/aprepro/CMakeFiles/aprepro.dir/aprepro.C.o -o packages/seacas/applications/aprepro/aprepro  -Wl,-rpath,/nightlyAlbanyTests/Results/Trilinos/build/packages/seacas/libraries/aprepro_lib:/nightlyAlbanyTests/Results/Trilinos/build/packages/seacas/libraries/exodus:/nightlyCDash/albany-tpls-gcc-11.1.1-openmpi-4.1.0/lib:  packages/seacas/libraries/aprepro_lib/libaprepro_lib.so.14.3  packages/seacas/libraries/exodus/libexodus.so.14.3  /nightlyCDash/albany-tpls-gcc-11.1.1-openmpi-4.1.0/lib/libnetcdf.so  /nightlyCDash/albany-tpls-gcc-11.1.1-openmpi-4.1.0/lib/libhdf5.so  /usr/lib64/libz.so  /nightlyCDash/albany-tpls-gcc-11.1.1-openmpi-4.1.0/lib/libhdf5_hl.so && :
packages/seacas/libraries/exodus/libexodus.so.14.3: undefined reference to `nc_def_var_fill'
collect2: error: ld returned 1 exit status
```
Did the requirements for how netcdf needs to be configured for seacas change?  Netcdf has not changed on the machine and the builds were fine until last night.

@trilinos/seacas

**Comment by ikalash** [comment]
Some additional info: the following MR is what caused the issues to start happening 

https://github.com/trilinos/Trilinos/commit/34934050ffee2ffe5ad75d1f08c12697cfd6c1f6

Tagging @gsjaardema , the author of the PR.

**Comment by ikalash** [comment]
@gsjaardema : below is the output for when I run nc-config --all: 

```
(base) [ikalash@camobap bin]$ ./nc-config --all

This netCDF 4.4.1 has been built with the following features: 

  --cc        -> /tpls/install/bin/mpicc
  --cflags    ->  -I/nightlyCDash/albany-tpls-gcc-11.1.1-openmpi-4.1.0/include -fPIC -O3 -march=native -I/nightlyCDash/albany-tpls-gcc-11.1.1-openmpi-4.1.0/include
  --libs      -> 

  --has-c++   -> no
  --cxx       -> 
  --has-c++4  -> no
  --cxx4      -> 

  --fc        -> /nightlyAlbanyTests/spack/opt/spack/linux-rhel8-haswell/gcc-11.1.0/openmpi-4.1.2-w65ftkfoqlafeb3nlcngwixdd4dwmkof/bin/mpif90
  --fflags    -> -I/nightlyAlbanyTests/spack/opt/spack/linux-rhel8-haswell/gcc-11.1.0/netcdf-fortran-4.5.3-4ayi4q2qeljqfhwsiphliahesj6xgw6m/include -I/nightlyAlbanyTests/spack/opt/spack/linux-rhel8-haswell/gcc-11.1.0/netcdf-fortran-4.5.3-4ayi4q2qeljqfhwsiphliahesj6xgw6m/include
  --flibs     -> -L/nightlyAlbanyTests/spack/opt/spack/linux-rhel8-haswell/gcc-11.1.0/netcdf-fortran-4.5.3-4ayi4q2qeljqfhwsiphliahesj6xgw6m/lib -lnetcdff
  --has-f90   -> 
  --has-f03   -> yes

  --has-dap   -> no
  --has-nc2   -> yes
  --has-nc4   -> no
  --has-hdf5  -> no
  --has-hdf4  -> no
  --has-logging-> no
  --has-pnetcdf-> no
  --has-szlib -> 

  --prefix    -> /nightlyCDash/albany-tpls-gcc-11.1.1-openmpi-4.1.0
  --includedir-> /nightlyCDash/albany-tpls-gcc-11.1.1-openmpi-4.1.0/include
  --version   -> netCDF 4.4.1
```
To provide some additional info, I built this netcdf from scratch on the machine.  This was done using the following hdf5 and netcdf configure scripts: 

https://github.com/sandialabs/Albany/blob/master/doc/nightlyTestHarness/camobap/hdf5-1.8.17-configure.sh
https://github.com/sandialabs/Albany/blob/master/doc/nightlyTestHarness/camobap/netcdf-4.4.1-configure.sh

**Comment by gsjaardema** [comment]
OK. That explains it.  The `nc_def_var_fill` function was added in 4.6.0 I think.  You are running 4.4.1 which was released in 2016...   Is there a reason for using such an old version?  The netCDF developers (and I) have improved the scalability and speed of netCDF significantly since then...

I can add code that skips the call to `nc_def_var_fill` for older versions if there is a reason to stick with that version. (I will probably add that code no matter what I guess since it breaks existing builds)

**Comment by ikalash** [comment]
> OK. That explains it. The `nc_def_var_fill` function was added in 4.6.0 I think. You are running 4.4.1 which was released in 2016... Is there a reason for using such an old version? The netCDF developers (and I) have improved the scalability and speed of netCDF significantly since then...

Regarding why we are using such an old version.  We build another code on top of Albany that is fortran and rather old.  I know that the code works with netcdf 4.4.1 and can be touchy, so I always stuck with what works and never tried to upgrade the netcdf.  I could try to do that to see if it corrects the problem.

**Comment by gsjaardema** [comment]
Based on @ikalash comment in #12051, this problem has been solved.

**Comment by ikalash** [comment]
Thank you for fixing this, @gsjaardema !
