### ISSUE TITLE
Zoltan: Can't build Large_Data tests with Visual Studio

### ISSUE THREAD

**Issue by mplooster** [trilinos/Trilinos#1205]
Currently building fails because Visual Studio doesn't have getopt.h, which is used in [stressTestPHG.c](https://github.com/trilinos/Trilinos/blob/4bfc9e957053212d76db4b09c9b66bbbeeaa80a9/packages/zoltan/test/Large_Data/stressTestPHG.c) and [stressTestGRAPH.c](https://github.com/trilinos/Trilinos/blob/4bfc9e957053212d76db4b09c9b66bbbeeaa80a9/packages/zoltan/test/Large_Data/stressTestGRAPH.c). To fix, I see two options:

1. Disable the test on Windows (which would leave zoltan virtually untested on Windows when building with MPI).
2. Replace getopt.h with a cross-platform argument parser. For example [getopts.h](https://github.com/trilinos/Trilinos/blob/4bfc9e957053212d76db4b09c9b66bbbeeaa80a9/packages/pamgen/example/getopts.h) and [getopts.C](https://github.com/trilinos/Trilinos/blob/4bfc9e957053212d76db4b09c9b66bbbeeaa80a9/packages/pamgen/example/getopts.C) (used in an example in pamgen) don't seem to have any issues on Windows and could easily be used in zoltan as well (provided it's license is compatible, of course).

@trilinos/zoltan @trilinos/framework Which option would you like me to do?

Related to issue #1160.

**Comment by kddevin** [comment]
Rather than add new source code, perhaps we can set default parameter values that make sense in each test that uses getopt.  For linux builds, we can keep the getopt capability to vary the tests.  For windows builds, we can #ifdef out the getopt capability and run with the default values.   Testing with default values is probably sufficient for windows.

Is WIN32 the correct macro to check?  We use it elsewhere in zoltan.

What is your timeframe for getting these changes?

**Comment by mplooster** [comment]
> Is WIN32 the correct macro to check? We use it elsewhere in zoltan.

It would probably be better to check _MSC_VER. I believe getopt.h is available in MinGW and Cygwin, and if I am remembering correctly, WIN32 is defined for those, while _MSC_VER is only defined for the Visual Studio compilers.

> What is your timeframe for getting these changes?

Ideally, within a week (sooner if possible). Zoltan is one of the packages I need to build for #1160. If it will speed things along, I am happy to do the actual coding and submit a pull request. However, I would need some direction from the zoltan team (either in this issue or via email) on what you would like to see.

**Comment by kddevin** [comment]
I pushed some changes but I have no way to test on windows. 
I'll close the issue, but please reopen if you still have troubles.

**Comment by mplooster** [comment]
@kddevin Thanks. That fixed the getopt issue. Unfortunately, stressTestPHG.c also has a problem with <sys/time.h>. GitHub won't let me reopon the issue (probably because I don't have write access to the reop and as [explained here](http://stackoverflow.com/questions/21333654/how-to-re-open-an-issue-in-github), I didn't close it), so could you reopen it?

**Comment by kddevin** [comment]
should be good now.

**Comment by mplooster** [comment]
@kddevin Thanks again for your quick work! That fixed the <sys/time.h> issue. One last thing, and then I think we should be home-free. For obvious reasons, Visual Studio does not like the function `Zoltan_write_linux_meminfo` in stressTestPHG.c (and the other signal handling in `meminfo_signal_handler`). If you could also take care of that, I'm pretty sure it will build on Visual Studio without any further problems.

**Comment by mplooster** [comment]
I think Zoltan_write_linux_meminfo also appears in dr_main.c, and should be handled there, as well.

**Comment by mplooster** [comment]
That did the trick. Thanks!
