### ISSUE TITLE
MueLu: build with -DMueLu_ENABLE_PROFILING=ON fails.

### ISSUE THREAD

**Issue by bathmatt** [trilinos/Trilinos#12062]
## Bug Report
If you build with -DMueLu_ENABLE_PROFILING=ON it fails to build with the following error

```
/lustre/fsw/devtech/hpc-devtech/mattb/Trilinos/Trilinos/packages/muelu/src/Utils/MueLu_Monitor.cpp(46): error: expression must be an lvalue or a function designator
            static_cast<std::ostringstream*>( &(std::ostringstream() << " " << timerIdentifier_++) )->str() + ": " + msg + " (level=" + Teuchos::Utils::toString(levelID) + ")", timerLevel));
                                               ^

/lustre/fsw/devtech/hpc-devtech/mattb/Trilinos/Trilinos/packages/muelu/src/Utils/MueLu_Monitor.cpp(60): error: expression must be an lvalue or a function designator
            static_cast<std::ostringstream*>( &(std::ostringstream() << " " << timerIdentifier_++) )->str() + ": " + msg + " (level=" + Teuchos::Utils::toString(level.GetLevelID()) + ")", timerLevel));
                                               ^

2 errors detected in the compilation of "/lustre/fsw/devtech/hpc-devtech/mattb/Trilinos/Trilinos/packages/muelu/src/Utils/MueLu_Monitor.cpp".
[51/289] Building CXX object packages/muelu/src/CMakeFiles/muelu.dir/Utils/ExplicitInstantiation/ETI_MueLu_AggregationStructuredAlgorithm_kokkos.cpp.o
/lustre/fsw/devtech/hpc-devtech/mattb/Trilinos/Trilinos/packages/kokkos/core/src/impl/Kokkos_ViewMapping.hpp(3600): warning #20011-D: calling a __host__ function("std::__cxx11::basic_string<char,     ::std::char_traits<char> , ::std::allocator<char> > ::basic_string(const ::std::__cxx11::basic_string<char,     ::std::char_traits<char> , ::std::allocator<char> > &)") from a __host__ __device__ function("MueLu::Describable::Describable [subobject]") is not allowed

```

### Description

What went wrong?  What should have happened?  Do you have an idea what might
fix things?  How has this bug affected you?  What are you trying to accomplish?
What specifically must we demonstrate to call this work complete?

### Steps to Reproduce
1. SHA1: VOTD
1. Configure script: 
[conf.txt](https://github.com/trilinos/Trilinos/files/12080583/conf.txt)

1. Configure log:  [attach here]
1. Build log:  [attach here]
1. Input deck:  [attach here]
1. Do this.
1. Do that.
1. Shake fist angrily at computer.
1. Run log:  [attach here]

**Comment by bathmatt** [comment]
#define MUELU_TIMER_AS_STRING static_cast<std::ostringstream*>( &(std::ostringstream() << " " << timerIdentifier_++) )->str()

This define is bad it looks like,

**Comment by cgcgcg** [comment]
@trilinos/muelu I have never ever ever used `MueLu_ENABLE_PROFILING`. What it seems to be designed to do is add a timer number to each MueLu timer. I am not sure why the string is constructed in that particular way:
https://github.com/trilinos/Trilinos/blob/af939b958a8e36a22611e6ea9d5129bab7d08f2c/packages/muelu/src/Utils/MueLu_Monitor.hpp#L182-L186
when `" " + std::to_string(timerIdentifier_++)` should work as well.
Should we simply remove the profiling option? The flag also enables compilation of `ReportTimeAndMemory` but that function does not appear to be used anywhere.

@bathmatt Did you try to use the flag for a specific reason, or just because you figured it could help with profiling?

**Comment by bathmatt** [comment]
not sure why it's not just std::to_string(timerIdentifier_++) but hey, what do I know.

**Comment by bathmatt** [comment]
Oh BTW, I'm not allowed to submit a patch to trilinos without prior approval of the project.  So, I can only make suggestions.  At some point I'll probably do the paperwork to get approval.

**Comment by cgcgcg** [comment]
No worries. I think it might sense to remove the logic entirely. One less CMake flag is a good thing.

**Comment by jhux2** [comment]
I'm support getting rid of that option.  The idea was to make post-processing easier, but as @cgcgcg mentioned, the option doesn't ever get used.
