### ISSUE TITLE
MueLu: Optimization for non-threaded sparse matrix-matrix multiply

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#1206]
@trilinos/muelu 
@sthomas61 implemented changes in TpetraExt_MatrixMatrix_def.hpp that sped it up by 2x.  

@csiefer2 @jhux2 Could one of you please review these changes?  Thanks :-)

I'm attaching the file here so we don't lose it.  I had to rename it to have a .txt extension so GitHub would accept it.  Next steps are to submit a pull request with the changes, test the pull request, then merge into develop.

[TpetraExt_MatrixMatrix_def.hpp.txt](https://github.com/trilinos/Trilinos/files/893809/TpetraExt_MatrixMatrix_def.hpp.txt)

**Comment by csiefer2** [comment]
The patch as submitted fails the Tpetra unit tests.  

I'll try to spend a bit of time trying to figure out why.

**Comment by sthomas61** [comment]
Proposing a different patch that does not introduce a second loop.
Splits some of the existing  for-if-else loops into two separate loops
with exits on the conditions, Could lead to improved cache locality.


[TpetraExt_MatrixMatrix_def.hpp.txt](https://github.com/trilinos/Trilinos/files/911209/TpetraExt_MatrixMatrix_def.hpp.txt)

**Comment by sthomas61** [comment]
best results when compiled with -O2 -funroll-loops:
abl-256^3 run on 96 Haswell cores, run time now 599 sec. 50 steps
Avg No-output time 599.1 sec

**Comment by jhux2** [comment]
@sthomas61 Can you post the compiler version you are using?

**Comment by sthomas61** [comment]
gcc 5.2.0

**Comment by sthomas61** [comment]
perhaps the best result so far: Chebyshev degree 3, with the original MatMat code with loop unrolling and #pragma GCC ivdep for the loop line 1554
Avg No-output time 597.9138 sec

**Comment by sthomas61** [comment]
96 cores, 50 steps, lowest time so far
Avg No-output time 596.8403 sec

**Comment by sthomas61** [comment]
now using the MueLu scaling test driver for timings -
introduced "Const Aval" for the outer loops - results in 25% improvement in MueLu set-up 
(repeated 100x). 
[TpetraExt_MatrixMatrix_def.hpp.txt](https://github.com/trilinos/Trilinos/files/921113/TpetraExt_MatrixMatrix_def.hpp.txt)

**Comment by sthomas61** [comment]
[MueLu100.log.txt](https://github.com/trilinos/Trilinos/files/921116/MueLu100.log.txt)

**Comment by sthomas61** [comment]
[MueLuConst100.log.txt](https://github.com/trilinos/Trilinos/files/921117/MueLuConst100.log.txt)

**Comment by sthomas61** [comment]
there is still "chop" in the timings due to communication but with 100x set-up 
more consistent timings

**Comment by mhoemmen** [comment]
@sthomas61 does the fix for #1248 make this issue obsolete?  Just curious :-)

**Comment by jhux2** [comment]
I committed @sthomas61's changes some time ago.  Closing, but feel free to reopen if necessary.
