### ISSUE TITLE
Framework: CUDA PR testing down?

### ISSUE THREAD

**Issue by jhux2** [trilinos/Trilinos#12072]
## Bug Report
Testing for `rhel7_sems-cuda-11.4.2-sems-gnu-10.1.0-sems-openmpi-4.0.5_release_static_Volta70_no-asan_complex_no-fpic_mpi_pt_no-rdc_no-uvm_deprecated-on_no-package-enables` is failing for a number of PR.  The common error is something like this:

`error while loading shared libraries: libcusparse.so.11: cannot open shared object file: No such file or directory`

For example, see #12069, #12070, #12071.

@trilinos/framework

**Comment by sebrowne** [comment]
It is expected that service will be restored after an overnight sync process.  I'll turn off the autotester until tomorrow just to prevent confusion.

**Comment by sebrowne** [comment]
I spot checked the environment and I believe this is fixed now.  Re-enabled autotester, and I'll AT: RETEST the mentioned PRs
