### ISSUE TITLE
What bit of CMake code actually defines F77_BLAS_MANGLE

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#1207]
@trilinos/framework 

I'm curious because it magically seems to work in my .h.in header, but I don't see where it gets defined.  Is this just a freebie that comes with CMake, or does it happen in TriBITS?

I'm asking because this is relevant for KokkosKernels etc.

**Comment by bartlettroscoe** [comment]
This is in TriBITS:

```
$ find cmake/tribits/core/ -name "*.cmake" -exec grep -nH F77_BLAS_MANGLE {} \;
cmake/tribits/core/package_arch/TribitsBLASMangling.cmake:46:  SET(F77_BLAS_MANGLE_DEFAULT ${F77_FUNC})
cmake/tribits/core/package_arch/TribitsBLASMangling.cmake:48:  SET(F77_BLAS_MANGLE_DEFAULT "UNDEFINED")
cmake/tribits/core/package_arch/TribitsBLASMangling.cmake:51:  SET(F77_BLAS_MANGLE_DEFAULT "${F77_FUNC}")
cmake/tribits/core/package_arch/TribitsBLASMangling.cmake:57:SET(F77_BLAS_MANGLE ${F77_BLAS_MANGLE_DEFAULT} CACHE STRING
cmake/tribits/core/package_arch/TribitsBLASMangling.cmake:60:MARK_AS_ADVANCED(F77_BLAS_MANGLE)
```

I don't know if raw CMake has such a thing.

Why does KokkosKernels not just snapshot TriBITS and let that be the CMake build system for KokkosKernels + Kokkos?  I can help you set that up pretty fast.

**Comment by mhoemmen** [comment]
@bartlettroscoe wrote:
> Why does KokkosKernels not just snapshot TriBITS and let that be the CMake build system for KokkosKernels + Kokkos? I can help you set that up pretty fast.

Thanks for the kind offer!  I'd better leave that to @crtrott and @hcedwar .

I'm actually working in Tpetra now, so I can rely on TriBITS just fine.  I'm just wondering how I got this handy variable `@F77_BLAS_MANGLE@` and whether I need to include some TriBITS file in my CMakeLists.txt file explicitly, in case package dependencies change at some point.  Thanks!

**Comment by mhoemmen** [comment]
@bartlettroscoe wrote:
> I don't know if raw CMake has such a thing.

https://cmake.org/cmake/help/v3.0/module/FortranCInterface.html

Not sure when it got added.  This is 3.0.2 documentation.

**Comment by bartlettroscoe** [comment]
> https://cmake.org/cmake/help/v3.0/module/FortranCInterface.html
>
> Not sure when it got added. This is 3.0.2 documentation.

Yes, I knew that CMake added support for automatic Fortran/C name mangling determination (and TriBITS/Teuchos and the rest of Trilinos should like change over to that at some point).  But the BLAS mangling may be different than the Fortran/C managing.  This separate macro was to get some builds to work where the Fortran managling and the BLAS mangling were different.  I don't know if FindBLAS.cmake, for example, addresses BLAS-specific mangling.

**Comment by mhoemmen** [comment]
@bartlettroscoe that's fine then :-)  I'm perfectly happy continuing to use `@F77_BLAS_MANGLE@` in Tpetra.

**Comment by bartlettroscoe** [comment]
@mhoemmen, can we close this?  I think the question has been answered.

**Comment by mhoemmen** [comment]
@bartlettroscoe Sounds good -- thanks for answering! :-)
