### ISSUE TITLE
Zoltan2:  questions about PuLP experiments with vertex weights

### ISSUE THREAD

**Issue by kddevin** [trilinos/Trilinos#1209]
Hi, @gslota .  Do you have time to answer some PuLP questions?

-  When I run Zoltan2's driver using PuLP and a fixed XML file, should I expect the same partition from PuLP every time?  I am seeing variation in the output from run to run.  Do I need to set the pulp_seed to get deterministic output?

-  When I run PuLP using vertex weights, sometimes (but not all times -- see above), all vertices get assigned to one part.  Is this behavior expected?  The problem is small (25 vertices), two parts requested) and I am running on one MPI processor.  Here's the output:

$ Zoltan2_test_driver.exe driverinputs/pulpVwgtTest.xml
Teuchos::GlobalMPISession::GlobalMPISession(): started processor with name vesper.sandia.gov and rank 0!
Input file source: driverinputs/pulpVwgtTest.xml
UserInputForTests, open ./vwgt.graph
UserInputForTests, open ./vwgt.coords
UserInputForTests, 25 vertices,80 edges,1 vertex weights, 0 edge weights
UserInputForTests, read 25 2-dimensional coordinates.

Running test: pulp-v

Creating a new partitioning problem.
Using input adapter type: XpetraCrsGraph
N global 25 25
procid: 0, n: 25, m: 80, vb: 1.050000, eb: 1.100000, p: 2
        Doing bfs init stage with 2 parts
done:  0.001349(s)
        Beginning vertex (and edge) refinement
                Doing (weighted) vert balance and refinement stage
Task 0, pulp_v_weighted() time  0.009040 (s)
done:  0.009065(s)
        Finished outer loop iter 1:  0.009074(s)
Partitioning finished:  0.010458(s)
partitioning problem solved.
Create evaluate class for: partitioning
Graph Metrics:  (1 parts)
Target number of parts is: 2
                           total         max
           edge cuts           0           0
        md edge cuts           0           0
          md message           0           0

Imbalance Metrics: (1 existing parts)
Target number of parts is 2
                            min        max        avg   imbalance
        object count          0         25       12.5           2
            weight 0          0         45       22.5           2

MetricAnalyzer::analyzeMetrics() returned false and the test is FAILED.
FAILED: imbalance value: 2 is not below 1.2
1 out of 1 metric checks  FAILED.

adapter construction time 0.00142002
problem construction time 0
solve time 0.022069
Problem run returned false
Test Driver with 1 processes has reduced result code 1 and is exiting in the FAILED state.

Thanks, @gmslota.

@trilinos/zoltan2

**Comment by mmwolf** [comment]
I had a similar issue with running on a very small problem for some of the work I'm doing for the mobile network folks.  I was running pulp directly on a very small problem and sometimes it would partitioning things evenly; other times, it would assign everything to one part.  I can send the test program if people are interested.

**Comment by gslota** [comment]
Hi @kddevin,

For the first question: PuLP is non-deterministic by default. You are correct, in that setting the seed is needed for 'deterministic' output. However, especially for XtraPuLP, partitions will likely differ from run to run due to non-deterministic execution from threads. To get consistent output, one would need to both set the seed and run on only a single thread.

For the second question, that is a known bug. XtraPuLP restricts per-iteration part update assignments, but on extremely small problems, this restriction can end up being too loose. I'll implement logic to handle such cases. I don't think this issue appears with regular PuLP.

**Comment by kddevin** [comment]
Thanks for your reply, @gslota .  
Do you have an estimate of when the known bug will be fixed?  I ask only because I know that the first test my users will run will be a very simple, ten-element graph.  If the fix is imminent, I will wait until after the fix to have them run PuLP.  If you do not have time now, I will try to steer them toward larger initial tests.  Thanks.

**Comment by gslota** [comment]
Sorry for the delay, @kddevin.

I am currently finishing up and testing a fix. Hopefully, I will be pushing updates to the PuLP library today or this weekend. I ran into some issues getting Trilinos up and running on my new system, which delayed me testing the PuLP fixes until now.

**Comment by gslota** [comment]
@kddevin @mmwolf 

I've implemented the bug fixes for XtraPuLP: https://github.com/HPCGraphAnalysis/PuLP

There were a few minor issues and one major one, that all would have impacted partition output for small test cases. Let me know if you're still having issues with this most recent version.

**Comment by kddevin** [comment]
Thanks, @gmslota.  
Unfortunately, I am still able to generate partitions with all vertices in one processor when I am using weights.  
cd BUILD/packages/zoltan2/test/driver
mpirun -np 4 Zoltan2_test_driver.exe driverinputs/pulpVwgtTest.xml
This test bi-partitions a 5x5 graph with nonuniform weights.

**Comment by gslota** [comment]
@kddevin 

Hmmm, I'm not able to reproduce it. I'm getting consistent imbalance of 1.022, even when oversubscribing threads.

Imbalance Metrics: (2 existing parts)
                            min        max        avg   imbalance
        object count         10         15       12.5         1.2
            weight 0         22         23       22.5       1.022

Success: imbalance (weight: 0) value: 1.02222 is in range: 0.1 to 1.9
1 out of 1 metric checks PASSED.

It looks like I did modify the xml file but didn't push it; though since I only did a minor change to the metric evaluation, I'm not sure if this would cause the vertices to all end up on the processor. The relevant portion of what I'm currently using is:

  <ParameterList name="pulp-v">
    <Parameter name="kind" type="string" value="partitioning"/>
    <ParameterList name="InputAdapterParameters">
      <Parameter name="data type" type="string" value="xpetra_crs_graph"/>
      <Parameter name="input adapter" type="string" value="XpetraCrsGraph"/>
    </ParameterList>
    <ParameterList name="Zoltan2Parameters">
      <Parameter name="algorithm" type="string" value="pulp"/>
      <Parameter name="compute_metrics" type="bool" value="true"/>
      <Parameter name="num_global_parts" type="int" value="2"/>
      <Parameter name="pulp_vert_imbalance" type="double" value="1.05"/>
      <Parameter name="pulp_verbose" type="bool" value="true"/>
      <Parameter name="pulp_seed" type="int" value="1"/>
    </ParameterList>
    <ParameterList name="Metrics">
      <ParameterList name="metriccheck1">
        <Parameter name="check" type="string" value="imbalance"/>
        <Parameter name="weight" type="int" value="0"/>
        <Parameter name="lower" type="double" value="0.1"/>
        <Parameter name="upper" type="double" value="1.9"/>
      </ParameterList>
    </ParameterList>
  </ParameterList>

**Comment by gslota** [comment]
```xml
<ParameterList` name="pulp-v">
    <Parameter name="kind" type="string" value="partitioning"/>
    <ParameterList name="InputAdapterParameters">
      <Parameter name="data type" type="string" value="xpetra_crs_graph"/>
      <Parameter name="input adapter" type="string" value="XpetraCrsGraph"/>
    </ParameterList>
    <ParameterList name="Zoltan2Parameters">
      <Parameter name="algorithm" type="string" value="pulp"/>
      <Parameter name="compute_metrics" type="bool" value="true"/>
      <Parameter name="num_global_parts" type="int" value="2"/>
      <Parameter name="pulp_vert_imbalance" type="double" value="1.05"/>
      <Parameter name="pulp_verbose" type="bool" value="true"/>
      <Parameter name="pulp_seed" type="int" value="1"/>
    </ParameterList>
    <ParameterList name="Metrics">
      <ParameterList name="metriccheck1">
        <Parameter name="check" type="string" value="imbalance"/>
        <Parameter name="weight" type="int" value="0"/>
        <Parameter name="lower" type="double" value="0.1"/>
        <Parameter name="upper" type="double" value="1.9"/>
      </ParameterList>
    </ParameterList>
  </ParameterList>```

**Comment by kddevin** [comment]
@gslota 
You are correct.  I must have built the updated version incorrectly; I suspect I built but did not install.  
I apologize for the noise.

Thank you for the fix!!
