### ISSUE TITLE
MueLu:  Prolongator smoothing

### ISSUE THREAD

**Issue by maxfirmbach** [trilinos/Trilinos#12090]
## Question
Hello everyone,

I'm trying to solve a Schur complement equation by using a rather standard algebraic multigrid and I'm running into the following problem: By applying a prolongator smoothing onto my tentative prolongator, my final coarse level matrix turns
out to be way denser than my fine level matrix (up to 30%-40% more entries). With just plain aggregation things are working
as expected ...
This is a really strange behavior I can't explain right now, I understand that the smoothing procedure makes the coarse level matrix more dense, but normally not to this extend. Does someone has an idea why there are so many entries added?

My multigrid summary looks as follows:
```shell
--------------------------------------------------------------------------------
---                            Multigrid Summary                             ---
--------------------------------------------------------------------------------
Scalar              = double
Number of levels    = 3
Operator complexity = 2.37
Smoother complexity = 0.00
Cycle type          = V

level  rows    nnz       nnz/row  c ratio  procs
  0  180888  95292996  526.81                26
  1  14148   130778392 9243.60  12.79        26
  2  156     24336     156.00   90.69        26

Smoother (level 0) both : Ifpack_AdditiveSchwarz, ov = 1, local solver =
                ***** `IFPACK ILUT (fill=1, relax=0, athr=0, rthr=1, droptol=0.001)'
                ***** Condition number estimate = 843.461

Smoother (level 1) both : Ifpack_AdditiveSchwarz, ov = 1, local solver =
                ***** `IFPACK ILUT (fill=1, relax=0, athr=0, rthr=1, droptol=0.001)'
                ***** Condition number estimate = 808.897

Smoother (level 2) pre  : MueLu::AmesosSmoother{type = Umfpack}
Smoother (level 2) post : no smoother
```

I think it's quite clear, that the problem especially arises on the first level of the multigrid hierarchy.

Best regards,
Max

@muelu and @mayrmt

**Comment by cgcgcg** [comment]
Is the operator itself denser than what you usually use? Cause $A_0$ is definitely quite dense already. To me this seems like expected behavior.

**Comment by jhux2** [comment]
If there are explicit zeros stored in $A_0$, MueLu has an option to filter out zero entries in $A_1$ after the triple matrix product.  @maxfirmbach Are the entries in $A_0$ here all nonzero?

**Comment by maxfirmbach** [comment]
Sorry for the late reply.

> Is the operator itself denser than what you usually use? Cause A0 is definitely quite dense already. To me this seems like expected behavior.

Yes, the operator stems from a Schur complement calculation, which in the end is quite dense.



> If there are explicit zeros stored in A0, MueLu has an option to filter out zero entries in A1 after the triple matrix product. @maxfirmbach Are the entries in A0 here all nonzero?

I think there shouldn't be a lot of explicit zeros stored in $A_0$. The operator is still sparse, but for the size "quite" dense, if this makes sense.

It really seems like this is just expected behavior as mentioned by @cgcgcg. For now I stay with an unsmoothed aggregation, the results look promising so I might come back to a smoothed one later.

**Comment by jhux2** [comment]
Closed as answered.
