### ISSUE TITLE
Set Trilinos_USE_GNUINSTALLDIRS=ON for Trilinos 15.0

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#12104]
CC: @sebrowne, @ccober6 

## Description

TriBITS has had the ability to use that paths selected by the standard CMake module [GNUInstallDirs.cmake](https://cmake.org/cmake/help/v3.23/module/GNUInstallDirs.html) for a **long** time (see [Setting the install prefix](https://docs.trilinos.org/files/TrilinosBuildReference.html#setting-the-install-prefix)).  But it is turned off in TriBITS by default (for the sake of backward compatibility) and it was never turned on in Trilinos by default (also to maintain backward compatibility).

Therefore, in the goal to move Trilinos and TriBITS to modern CMake ( see TriBITSPub/TriBITS#411), we should hard set the **non-cache** variable `Trilinos_USE_GNUINSTALLDIRS=ON` in the base Trilinos `CMakeLists.txt` file.  This will force every Trilinos user to absorb this change in Trilinos 15.0 (but most customers should never even notice).

Once Trilinos 15.0 comes out, then we can refactor TriBITS to just directly use the standard variables that come from the standard CMake module `include(GNUInstallDirs)`.

Easy as pie (at least for Trilinos and TriBITS).

**Comment by bartlettroscoe** [comment]
FYI: There may be a defect in CMake that may be problematic to customers, at least for CMake 3.23.1 (see https://gitlab.kitware.com/cmake/cmake/-/issues/25157).

**Comment by sebrowne** [comment]
@bartlettroscoe would you like me to do this now that 14.4 is out?

**Comment by bartlettroscoe** [comment]
> because it will install libs in `<prefix>/libs64/` instead of in `<prefix>/libs/` and that is liable to break some things

As predicted:

* https://github.com/sandialabs/Albany/issues/982

**Comment by bartlettroscoe** [comment]
With the merging of #12258 (and the follow-ups dealing with customers and broken configurations), this is complete.
