### ISSUE TITLE
AztecOO: Fortran string ABI binding needs new option for OpenBLAS on POWER 

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#1212]
See #1208.

**Comment by maherou** [comment]
I think the best approach is to add this to the work list for Tech-X.  Added Kris Beckwith and Jim Willenbring to the assignees list.

**Comment by mhoemmen** [comment]
@maherou Would it make sense to have Tech-X solve the problem for all packages at once?  This seems like something that could go into TriBITS, per discussion in #1208, so that all packages could use a common solution.  That would certainly make life easier for internal customers.

**Comment by maherou** [comment]
Yes, a holistic approach to these issues is certainly the best option.
@jwillenbring, @krcb: Can you discuss this at the next Trilinos-Tech-X meeting?

**Comment by mhoemmen** [comment]
It looks like @bathmatt can work around for now, by using ESSL.  The only problem is that using OpenMP threads in ESSL requires the XL OpenMP run-time environment.  It's possible to use GCC + OpenMP with ESSL, but then you have to use the non-threaded version of ESSL.

**Comment by jwillenbring** [comment]
@maherou - yes, @krcb and I can discuss this next week.
