### ISSUE TITLE
Trilinos:  Cannot build on a MacBook Pro with Intel processor

### ISSUE THREAD

**Issue by nathanielmorgan** [trilinos/Trilinos#12130]
## Bug Report
Cannot build on a MacBook Pro with Intel processor, any advise on how to build Trilinos using MacBook would be welcomed.  Thanks.

### Description
Unable to build Trilinos:
-- Verifying Fortran/CXX Compiler Compatibility - Failed
CMake Error at /usr/local/Cellar/cmake/3.23.1/share/cmake/Modules/FortranCInterface.cmake:400 (message):
  The Fortran compiler:

    /usr/local/bin/mpif90

  and the CXX compiler:

    /usr/local/bin/mpicxx

  failed to compile a simple test project using both languages.

**Comment by nathanielmorgan** [comment]
Thank you for the quick response.  Yes, I can build Trilinos on the LANL HPC systems.  However, I cannot built it on my Mac laptop, which is my primary machine used to write code.

Regards,
Nathaniel

Nathaniel Morgan, PhD
Analysis Software Development Team Leader
Scientist 5
E-2: Modern Manufacturing Methodologies

Office: 505-667-0031
Mobile: 505-412-8225

Los Alamos National Laboratory
lanl.gov<http://lanl.gov>

On Aug 15, 2023, at 1:30 PM, Christian Glusa ***@***.******@***.***>> wrote:



No idea if that's a broken compiler or something else. You could check CMakeFiles/CMakeError.log or CMakeFiles/CMakeOutput.log if there are any clues. Do they work if you compile anything else with them?

**Comment by cgcgcg** [comment]
So you have tested that the compilers on your laptop do, in fact, work? I am asking because the check that fails is not a Trilinos check but something out of CMake.

**Comment by nathanielmorgan** [comment]
I agree, I am trying to find how to correctly set compiler flags and compiler paths.  The log files are somewhat cryptic to me, perhaps you can make sense of the following error:
Undefined symbols for architecture x86_64:
  "_VerifyFortran", referenced from:
      _main in main.c.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [VerifyFortranC] Error 1
make[2]: *** [CMakeFiles/VerifyFortranC.dir/all] Error 2
make[1]: *** [CMakeFiles/VerifyFortranC.dir/rule] Error 2
make: *** [VerifyFortranC] Error 2

**Comment by cgcgcg** [comment]
Is that the first error? Can you check in `CMakeCache.txt` what `CMAKE_LINKER` is set to and whether that works?

**Comment by nathanielmorgan** [comment]
The first error reported in the log file is,

clang: error: unsupported argument 'auto' to option 'flto='
clang: warning: optimization flag '-ffat-lto-objects' is not supported [-Wignored-optimization-argument]
make[3]: *** [CMakeFiles/symbols.dir/mymodule_.c.o] Error 1
make[2]: *** [CMakeFiles/symbols.dir/all] Error 2
make[1]: *** [CMakeFiles/FortranCInterface.dir/rule] Error 2
make: *** [FortranCInterface] Error 2

**Comment by nathanielmorgan** [comment]
Concerning `CMAKE_LINKER`, it is set to,
//Path to a program.
CMAKE_LINKER:FILEPATH=/usr/bin/ld

**Comment by cgcgcg** [comment]
As far as I can tell we don't set `-flto=auto` anywhere. Is there any way that this is coming from your environment? Can you post how you configure and what output CMake is giving you?

**Comment by nathanielmorgan** [comment]
Good news, we now pass the c/fortran compatibility test with Trilinos, although we hit another issue building it.  The issue was with cmake.  For some reason, it refused to except our settings to use g++ 13 and would use clang, while accepting environment settings to use gfortran.  The mix of clang and gfortran caused the issue

**Comment by cgcgcg** [comment]
Is the new issue something you want to work through on your own? Do you want to open a new issue or continue on this one?

**Comment by nathanielmorgan** [comment]
I will try to resolve it on my own.  You can close this ticket
