### ISSUE TITLE
Stokhos: test failure when compiling on arm64

### ISSUE THREAD

**Issue by maartenarnst** [trilinos/Trilinos#12157]
@trilinos/stokhos
@etphipp 

### Description

We are compiling Trilinos with Stokhos enabled and running Stokhos tests on arm64. We're seeing some of the tests checking the mathematical functions for the ensemble type fail.

The reason seems to be that some of the tests involve checking the result when a function such as `log` is applied to an ensemble filled with values such as `0.`, `0.2`, ... In this case, the result for the first sample `log(0)` returns `-Inf`.  The Stokhos test is then testing whether the right result is obtained in terms of a relative error. If the correct result is obtained, this leads to `0. * -Inf`. And it seems the result of this operation is different on arm64 than on amd64.

Replacing `if (err  > tol) {` with ` if ( (err  > tol) && (err != 0.) ) {` in `packages/stokhos/test/UnitTest/Stokhos_UnitTestHelpers.hpp` fixed the issue. I will introduce and link a PR with this change. But, @etphipp, if you should want to go for another fix, I'll be happy to update the PR.

**Comment by etphipp** [comment]
Looks good, thanks for reporting and the fix @maartenarnst!

**Comment by maartenarnst** [comment]
Thanks, @etphipp! This was our quickest pr ever :)
