### ISSUE TITLE
Zoltan does not respect the cmake MPI_EXEC flags

### ISSUE THREAD

**Issue by bathmatt** [trilinos/Trilinos#1217]
I set 
MPI_EXEC_POST_NUMPROCS_FLAGS to "-map-by;socket:PE=8;--oversubscribe" and when I run all the tests I get zoltan failures because it doens't respect these flags

```
Running: "/home/projects/pwr8-rhel73-lsf/perl/5.22.1/bin/perl" "../ctest_zoltan.pl" "--np" "4" "--debug" "--mpiexec" "/home/projects/pwr8-rhel73-lsf/openmpi/1.10.4/gcc/5.4.0/cuda/8.0.44/bin/mpiexec" "--mpiexecarg" "-np" "--pkg" "Zoltan"

--------------------------------------------------------------------------------

CTEST_FULL_OUTPUT
--np4--debug--mpiexec/home/projects/pwr8-rhel73-lsf/openmpi/1.10.4/gcc/5.4.0/cuda/8.0.44/bin/mpiexec--mpiexecarg-np--pkgZoltan
DEBUG HOSTNAME ride16 ride1
DEBUG:  package Zoltan
 05:31:24 up 21 days, 18:57,  0 users,  load average: 12.14, 17.14, 10.52
DEBUG:  mpiexec /home/projects/pwr8-rhel73-lsf/openmpi/1.10.4/gcc/5.4.0/cuda/8.0.44/bin/mpiexec --mca mpi_yield_when_idle 1 -np
DEBUG  Dir /home/jenkins/workspace/Drekar-ride-cuda-opt-all-test/build_drekar_CUDA_RELEASE_CUDA/packages/zoltan/test/hg_diag500_4 dirname diag500_4
DEBUG  Outfilebase: ;  Dropbase: 
DEBUG  Running test 0 on zdrive.inp.phg
DEBUG  Test name:  phg
DEBUG  Archfilebase: diag500_4.phg.4.; Dropbase: diag500_4.phg.drops.4.
DEBUG Executing now:  /home/projects/pwr8-rhel73-lsf/openmpi/1.10.4/gcc/5.4.0/cuda/8.0.44/bin/mpiexec --mca mpi_yield_when_idle 1 -np 4 ../zdrive.exe zdrive.inp.phg 2>&1 | tee diag500_4.phg.4.outerr
```

**Comment by kddevin** [comment]
Hi, @bathmatt .  You are correct, as the perl script used for testing in Zoltan was written largely outside the Trilinos build system; indeed, since Zoltan is downloadable separately from Trilinos, the script does not use any of the cmake variables.

How important is modifying this script to run in this environment?  
If it is important, by when do you hope that it is changed?  
Do you need full testing, or would some basic sanity testing be sufficient in this environment? 

Thanks.

**Comment by bathmatt** [comment]
I'm trying to get to a clean dashboard on the testbed platforms,  Lots of
zoltan issues pop up.  I can skip the zoltan tests but when something comes
up with muelu and zoltan not sure what to do about it.  It does set a bad
precedent with "Trilinos should pass its tests on platforms we care about"

It isn't super important for Z1 but is for Z2 which looks like it doesn't
have this issue.

**Comment by kddevin** [comment]
You are correct that Zoltan2 does not have this issue, since it was born and grew up in the Trilinos environment.  Zoltan is different because it was imported into Trilinos long after its birth and it leads a dual life.

Do any Zoltan tests pass on this platform?  I am guessing only the perl-script based tests (like the one you show above) fail; if I am wrong, we have a bigger issue with which to deal.

**Comment by bathmatt** [comment]
these pass
Zoltan_ch_serial_zoltan_parallel    1.50408            passed
Zoltan_ch_simple3d_zoltan_parallel
Zoltan_test_get_callbacks_MPI_4

**Comment by kddevin** [comment]
Hmm, I was hoping to see the following:

 1/57 Test  #1: Zoltan_stressTestGRAPH_P_0_MPI_8 ...........   Passed    0.70 sec
 2/57 Test  #2: Zoltan_stressTestGRAPH_P_1_MPI_8 ...........   Passed    0.69 sec
 3/57 Test  #3: Zoltan_stressTestGRAPH_0_MPI_8 .............   Passed    0.99 sec
 4/57 Test  #4: Zoltan_stressTestGRAPH_1_MPI_8 .............   Passed    0.99 sec
 5/57 Test  #5: Zoltan_stressTestPHG_0_MPI_8 ...............   Passed    0.69 sec
 6/57 Test  #6: Zoltan_stressTestPHG_1_MPI_8 ...............   Passed    0.69 sec
 7/57 Test  #7: Zoltan_test_get_callbacks_MPI_4 ............   Passed    0.68 sec

If the "stressTest" tests did not pass, would you please send me the output from them?

**Comment by kddevin** [comment]
Or maybe you are configuring with 
-D MPI_EXEC_MAX_NUMPROCS:STRING=4
so that they aren't run?

**Comment by bathmatt** [comment]
didn't run...
can you get to this?
https://jenkins-srn.sandia.gov:8443/view/Drekar/job/Drekar-ride-cuda-opt-all-test/2/ctestResult/

**Comment by bathmatt** [comment]
correct, 4 procs max

**Comment by kddevin** [comment]
OK; let me think about this issue a bit.  By when do you hope to have this issue resolved?  Thanks.
In the meantime, zoltan is exercised a bit through zoltan2 tests -- maybe a little peace of mind.

No, I can't access the jenkins page -- 404 error.  No worries, though; your list is sufficient.

**Comment by bathmatt** [comment]
It's not a huge concern as I don't think these are causing my issue
failures in my tests.  Other issues are higher.  But if we get to nearly a
clean dashboard these will move up the list.

**Comment by kddevin** [comment]
@bathmatt Is this issue still important for you?  I am looking at old Zoltan issues today.

**Comment by kddevin** [comment]
This bug will be closed unfixed.  If it becomes a blocker, please re-open.
