### ISSUE TITLE
Tpetra: unnecessary UVM ETI

### ISSUE THREAD

**Issue by jhux2** [trilinos/Trilinos#12189]
Is this usage of UVM a problem?  This doesn't appear to be `ifdef` guarded.

https://github.com/trilinos/Trilinos/blob/004eee56561d879b5acef3eb63e70db9e388b217/packages/tpetra/core/src/Tpetra_Details_FixedHashTable_Cuda.cpp#L58-L66

@trilinos/tpetra

**Comment by jhux2** [comment]
This is only instantiating for UVM, so perhaps it's not so bad.

**Comment by brian-kelley** [comment]
It seems like we never use FixedHashTable with the ``<Cuda, CudaUVMSpace>``, regardless of the ``Tpetra_ENABLE_CUDA_UVM`` setting. There's no major harm in instantiating for it, but it adds some library size and build time.

**Comment by jhux2** [comment]
FHT instantiated on `<Cuda, CudaUVM> is needed even to build Tpetra's own tests.  I'm closing this as invalid/wontfix.
