### ISSUE TITLE
Tpetra maps, local maps and constructors.

### ISSUE THREAD

**Issue by bathmatt** [trilinos/Trilinos#1218]
I want to create a tpetra map in my class and then store a local copy of a local_map_type.  However, local_map_type doesn't have a default constructor.  

Here is my workflow, and I don't know how to go forward, suggestions?

```
struct my_struct {
  RCP<Map> my_map;
  Map::local_map_type my_local_map;

  my_struct() { 
    my_map = build_map();
    my_local_map = my_map->getLocalMap();
  }
KOKKOS_INLINE_FUNCTION int func() {return my_local_map.getLocalElement(7);}
};

main() {
my_struct ms;
parallel_for(...  { ms.func();});

```

**Comment by mhoemmen** [comment]
Would you like `local_map_type` to have a default constructor?  I'm not quite sure what the question is.

**Comment by bathmatt** [comment]
That would help move me past this issue.

**Comment by bathmatt** [comment]
I was stating my problem, not suggesting a solution as often people might
have better ones than I can come up with on my one :)

**Comment by bathmatt** [comment]
@mhoemmen can I just create a default ctor  and push?

**Comment by mhoemmen** [comment]
@bathmatt Sure, go ahead.  I think all you would need to do is imitate what `Tpetra::Map`'s default constructor does.  Thanks!

**Comment by bathmatt** [comment]
Added in 
6bd9788fcfd4ad3e406e49448a6fe2f18955e495

**Comment by mhoemmen** [comment]
Thanks @bathmatt !
