### ISSUE TITLE
Muelu: Multithreaded performance of Muelu and Ifpack2 SGS

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#1219]
@trilinos/ifpack2 @trilinos/muelu 

[Edited to include contributors, who agreed to be public]

I just got the following e-mail from @wppowers and @eamarttila : 

> Hi Mark,
>
> I have been doing some profiling (using Intel's Vtune) of simulations using the experimental multi-threaded gauss-seidel smoother and comparing the results to the same simulation using only MPI. I am seeing that a run using 1 MPI process and 4 openMP threads is roughly 20% slower than solving the same problem using 4 MPI processes and 1 openMP thread per process.
>
> 1. Would you expect this type of a performance gap between multi-threaded and multi-process runs?
>
> I have a small sample program attached that illustrates our typical usage of trilinos and also manifests the performance issue. Additionally I can send the inputs we are using if it will help with answering the question.
>
> I also noticed during profiling that the computation of the preconditioner does not appear to
be threaded.
>
> 2. Is this true?
> 3. If so, are there plans to thread the preconditioner computation?
>
> Something that was highlighted by Vtune was a load imbalance during the multi-threaded runs.  I was curious if telling openMP to use dynamic scheduling would help with the load imbalance, but I don't know how to accomplish that through trilinos. In fact, it appears from the profiling results that some of the loops are using dynamic scheduling and others are using static scheduling.
>
> 4. Is there a way to tell trilinos to default to a specific type of thread scheduling, particularly from the higher level interfaces such as MueLu and Tpetra?
>
> Thanks for your assistance!

I got their permission to post this e-mail and a sample code that they wrote.  Attached is a .tgz archive that has an example .cpp file, a Makefile, and some kind of project file for an IDE. 
[multi-threaded-belos-solve.tgz.txt](https://github.com/trilinos/Trilinos/files/903239/multi-threaded-belos-solve.tgz.txt)

One issue with the example code is that it uses the new multithreaded Gauss-Seidel through MueLu, as a smoother.  I'm not sure if MueLu has plugged in that option yet, which is why I'm CC'ing the MueLu developers.

**Comment by mndevec** [comment]
Hi Mark, thank you for the notification. I will look into this. 

But I am not sure from the post if the problem is related to Multi-threads Gauss Seidel scaling. It sounds like some portions of the code is serial, and the problem might simply be related to that.

**Comment by mhoemmen** [comment]
@mndevec The example constructs a multigrid hierarchy, and the submitter didn't say how many multigrid levels they needed.  None of algebraic multigrid setup is currently threaded by default.  Would be nice to get your sparse matrix-matrix multiply enabled by default too :-) .  In any case, it's unclear how to interpret the submitter's statements without more information.

**Comment by srajama1** [comment]
If not github, can you send the submitter's contact to both of us internally in Sandia ?

**Comment by mhoemmen** [comment]
I'm awaiting clarification from them regarding permissions.

**Comment by mhoemmen** [comment]
I added the submitters to the CC list.

**Comment by mhoemmen** [comment]
They also write: 
> Regarding the number of multigrid levels which are used, we are just taking the defaults used by the ML preconditioner using the `ML2MueLuParameterTranslator` since we had been using ML prior to migrating to MueLu.

**Comment by wppowers** [comment]
I should mention that when the preconditioner was only computed once at the beginning of the run rather than periodically throughout the simulation, the performance only improved by about 1%. So even when the serial portion of the sample program was eliminated, the 1 process 4 thread per process run was still about 19% slower than the 4 process 1 thread per process run.

**Comment by jhux2** [comment]
MueLu has a separate code path that explicitly enables Kokkos in the multigrid setup.  To enable that code, please add these cmake options.
```
-DMueLu_ENABLE_Experimental:BOOL=ON
-DMueLu_ENABLE_Kokkos_Refactor:BOOL=ON
-DXpetra_ENABLE_Experimental:BOOL=ON
-DXpetra_ENABLE_Kokkos_Refactor:BOOL=ON
```
Regardless of whether you use these options, the apply of the preconditioner will always use Kokkos, because you're using Tpetra.

**Comment by srajama1** [comment]
@wppowers : The SGS preconditioner is one portion of the MueLU setup and apply. Both the preconditioner computation and apply are multithreaded. This is not true for all of MueLU setup and apply though. It is going to depend on lot of options.

**Comment by jhux2** [comment]
> @wppowers : The SGS preconditioner is one portion of the MueLU setup and apply. Both the preconditioner computation and apply are multithreaded. This is not true for all of MueLU setup and apply though. It is going to depend on lot of options.

Right, I should have been much more careful in my statement.  The multigrid setup is not fully threaded yet, but adding the cmake options I mentioned will activate the portions that are.  Any part of the multigrid apply that uses a matrix-vector kernel (e.g., grid transfers, polynomial smoothers) will use Kokkos.  And as @srajama1 mentions, SGS is also threaded in its setup and apply.  Someone else will have to comment on the coarse grid solve and the Tpetra import/export operations.

**Comment by wppowers** [comment]
@jhux2 Thanks for those suggestions. I will give that a shot. We are currently using the following experimental options.

-DTpetraKernels_ENABLE_Experimental:BOOL=ON 
-D fpack2_ENABLE_Experimental:BOOL=ON 
-DIfpack2_ENABLE_Experimental_KokkosKernels_Features:BOOL=ON

**Comment by srajama1** [comment]
The options provided by @jhux2 can enable the existing multithreaded portions of Muelu. It would be nice to know if this is enough for this application usage. If not, it would be nice to get a prioritized list for your use cases. We will keep that list in mind as we prioritize multithreading different portions of the stack.

I am changing the title to reflect this is a MueLu multithreading usage and not Ifpack2 SGS usage.

**Comment by wppowers** [comment]
I did enable the options provided by @jhux2, and that did not make a difference in our use case. The performance was unchanged and VTune still identified the same bottlenecks. If there are any other suggestions that I can try, I would be happy to do so.

**Comment by srajama1** [comment]
@wppowers : Can you give us the top bottlenecks for your usecase ? You can either add it to the issue or e-mail it to us. It is quite possible these portions are not multithreaded yet.

**Comment by wppowers** [comment]
@srajama1. The primary bottlenecks I am seeing are listed below. I am also comparing them to what I see when doing a multi-process run.

MueLu::TopRAPFactory::Build() - This function appears to be executing in serial when using 4 threads, but is utilizing all 4 processes 90% of the time when using 4 processes.

MuLue::Hierarchy::iterate() - This function utilizes all 4 processes for about 80% of a 4 process run, but only utilizes 4 threads for about 25% of a 4 thread run. About 60% of the time, 3 threads are being utilized.

IfPack2::Relaxation::MtGaussSeidel() - This function utilizes all 4 process for about 80% of a 4 process run, but only utilizes all 4 threads for about 20% of a 4 thread run. About 70% of the time, 3 threads are being utilized.

Those are the primary differences I am seeing when comparing a 4 process run to a 4 thread run. If there is any other information that would be helpful, let me know.

**Comment by srajama1** [comment]
Thanks ! This is useful information.  @jhux2 is the best person to answer the first two. The third one is a multithreaded kernel. The #threads that will be used here will be dependent on the size and the structure of the problem. MPI will utilize all 4 processes because we decomposed the problem. I am ssuming threads are getting 4 times larger problems here. This will allow potential use of 4 threads, but we don't do the same decomposition as MPI would have done to get the same efficiency. Instead we use all the info available to the four threads. Typically, this should result in a better smoother for multigrid. Do you see exact same number of iterations between the two runs ?

**Comment by wppowers** [comment]
@srajama1 The iteration counts differ slightly between the two runs. The 4 process case takes 22 iterations and the 4 thread case takes 24 iterations.

**Comment by srajama1** [comment]
I was thinking it will be the other way around, with threads taking fewer iterations as they have more information. This has to be investigates the multigrid level though.

**Comment by wppowers** [comment]
@srajama1 Actually, you are correct. I flipped the numbers. The 4 process case takes 24 iterations and the 4 thread case takes 22 iterations.

**Comment by srajama1** [comment]
That makes sense. I believe that improvement in the iteration count comes from using threads. In a tough to solve use case, I would have expected the improvement in the number of iterations to help offset the reduction in efficiency (4 vs 3 threads in 80% and 70% of the time).  Still, only 3 threads being utilized mostly is surprising.
