### ISSUE TITLE
Tpetra: getGlobalRowCopy should return an empty row instead of throwing if nonowned row

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#122]
@trilinos/tpetra 

If users give getGlobalRowCopy a row that does not live on the calling process, the method should return an empty row, rather than throwing an exception.  This change will make its behavior more consistent with that of replace\* and sumInto*.

**Comment by mhoemmen** [comment]
Note my FIXME from 22 Aug 2014:
```
    // FIXME (mfh 22 Aug 2014) Instead of throwing an exception,
    // should just set NumIndices=0 and return.  In that case, the
    // calling process owns no entries in that row, so the right thing
    // to do is to return an empty copy.
```

**Comment by mhoemmen** [comment]
Fixing this may require Tpetra test revisions, since some tests may expect getGlobalRowCopy to throw in this case.

**Comment by tjfulle** [comment]
@mhoemmen, your comment referenced above is no longer in the code.  Did this already get fixed?  It's not clear to me where the code is throwing (in `CrsGraph` and `CrsMatrix`) for the case that the row is not owned by the process (though, I've just started looking at it).

**Comment by mhoemmen** [comment]
@tjfulle I think you're right.  I just took a look at `getGlobalRowCopy` in both CrsGraph and CrsMatrix, and it looks like it only throws if the user didn't provide enough room for output.  It should simply set `numEntries=0` and return if the input row is not in the row Map on the calling process.

**Comment by tjfulle** [comment]
@mhoemmen  That’s what I thought.  I’ll put in a test to confirm, push, and close this issue.

**Comment by mhoemmen** [comment]
Thanks! :D

**Comment by mhoemmen** [comment]
btw if we want to make those methods _never_ throw, we should open a separate issue for that.  That's something for which we can test at compile time, using `noexcept`.
