### ISSUE TITLE
Amesos:  define/cast errors

### ISSUE THREAD

**Issue by andreili** [trilinos/Trilinos#12200]
## Bug Report
@srajama1 

### Description
All of this bugs a valid for version 14.4.0 and git hash 5aaae1ada6fe1ce777e671a0ff84fdc4f0779406.

On Amesos CSparse module I see two issues (detected on linking for Xyce simulator):
* Invalid "ifdef/include" order;
* Invalid cast for malloc.

About order - into Amesos_CSparse.h/.cpp we have "#ifdef HAVE_AMESOS_CSPARSE" before include configure file. And this causes to ignore all sources on this module:
https://github.com/trilinos/Trilinos/blob/master/packages/amesos/src/Amesos_CSparse.h#L31
https://github.com/trilinos/Trilinos/blob/master/packages/amesos/src/Amesos_CSparse.cpp#L29

About cast - after fix a configuration define, I see a cast error (invalid cast from "ptrdiff_t*" to "unsigned long int*") on this two lines:
https://github.com/trilinos/Trilinos/blob/master/packages/amesos/src/Amesos_CSparse.cpp#L137
https://github.com/trilinos/Trilinos/blob/master/packages/amesos/src/Amesos_CSparse.cpp#L138

**Comment by jhux2** [comment]
@trilinos/amesos
