### ISSUE TITLE
Missing -lcublas in Trilinos config export

### ISSUE THREAD

**Issue by ambrad** [trilinos/Trilinos#1220]
@trilinos/tpetra 

It seems the cublas lib (i.e., -lcublas on the link line) is not appended to the list of TPL libs in the installed
    Trilinos_TPL_LIBRARIES lib/cmake/Trilinos/TrilinosConfig.cmake
If I add -lcublas to the app's link line (in the corresponding link.txt), then all is well. This is with Cuda 8. So it does seem to be just an issue of a missing TPL lib in one of Tpetra's CMakeLists.txt.

This is associated with recent changes to Tpetra_Details_cublasGemm.cpp.

Thanks!

**Comment by mhoemmen** [comment]
Hm, I did actually test this with CUDA so I'm not sure what's different with this build environment.  It looks like Trilinos doesn't actually have a cuBLAS TPL. Should we add this?

**Comment by ambrad** [comment]
What is the link.txt file associated with the test you ran? Does it have -lcublas in it? If so, then the question is why it doesn't show up anywhere in TrilinosConfig.cmake. (Or does it show up for you?)

**Comment by mhoemmen** [comment]
Hi @ambrad !  My Makefile.export.Trilinos file says that I'm linking with cublas:
```
Trilinos_TPL_LIBRARIES= /usr/lib64/libdl.so /projects/sems/install/rhel6-x86_64/sems/tpl/boost/1.59.0/gcc/4.8.4/base/lib/libboost_program_options.so /projects/sems/install/rhel6-x86_64/sems/tpl/boost/1.59.0/gcc/4.8.4/base/lib/libboost_system.so /projects/sems/install/rhel6-x86_64/sems/tpl/superlu/4.3/gcc/4.8.4/base/lib/libsuperlu.a /projects/sems/install/rhel6-x86_64/sems/tpl/netcdf/4.3.2/gcc/4.8.4/openmpi/1.10.1/parallel/lib/libnetcdf.so /projects/sems/install/rhel6-x86_64/sems/tpl/hdf5/1.8.12/gcc/4.8.4/openmpi/1.10.1/parallel/lib/libhdf5.a /usr/lib64/libz.so /projects/sems/install/rhel6-x86_64/sems/tpl/hdf5/1.8.12/gcc/4.8.4/openmpi/1.10.1/parallel/lib/libhdf5_hl.a /projects/sems/install/rhel6-x86_64/sems/tpl/parmetis/4.0.3/gcc/4.8.4/openmpi/1.10.1/parallel/lib/libparmetis.a /projects/sems/install/rhel6-x86_64/sems/tpl/parmetis/4.0.3/gcc/4.8.4/openmpi/1.10.1/parallel/lib/libmetis.a /usr/lib64/liblapack.so /usr/lib64/libblas.so /projects/sems/install/rhel6-x86_64/kokkos/compiler/cuda/7.5.18/lib64/libcudart.so /projects/sems/install/rhel6-x86_64/kokkos/compiler/cuda/7.5.18/lib64/libcublas.so /projects/sems/install/rhel6-x86_64/kokkos/compiler/cuda/7.5.18/lib64/libcufft.so
```

**Comment by ambrad** [comment]
I think I know the issue. In my build, I did not explicitly (i) set TPL_ENABLE_CUDA=ON; I just (ii) set Kokkos_ENABLE_Cuda=ON. Tpetra uses KOKKOS_HAVE_CUDA to decide whether to use cuBLAS, which is triggered by (ii). But only (i) triggers -lcublas.

So there are perhaps some questions about consistency of what gets triggered, but now at least I know what flag to provide in the config to get the link line I want automatically.
