### ISSUE TITLE
Test ROL_example_PDE-OPT_topo-opt_elasticity_example_01_MPI_4  timing out in CI build starting 4/6/2017

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#1221]
**CC:** @trilinos/rol, @eric-c-cyr, @trilinos/framework 

**Description:**

Looks like the test `ROL_example_PDE-OPT_topo-opt_elasticity_example_01_MPI_4` started timing out at 10 minutes in this CI iteration today:

    http://testing.sandia.gov/cdash/index.php?project=Trilinos&parentid=2823204&filtercount=3&showfilters=1&field1=groupname&compare1=61&value1=Continuous&field2=buildstarttime&compare2=84&value2=now&filtercombine=and

Looking at the commits pulled in this range (which you get from the “updates” page link under the “Updates” column):

```
$ git log-short --name-status 1824cbc54 ^c764aed364

1824cbc "zoltan2:  fix test failures when building without PuLP."
Author: K. Devine <kddevin@sandia.gov>
Date:   Wed Apr 5 10:43:16 2017 -0600 (32 hours ago)

M       packages/zoltan2/test/unit/environment/AllParameters.cpp

7211acd "ROL: Resorting to SimOpt PDE Constraint Solve in CompositeEqualtiyConstraint_SimOpt"
Author: Eric C. Cyr <eccyr@sandia.gov>
Date:   Wed Apr 5 10:23:17 2017 -0600 (32 hours ago)

M       packages/rol/src/function/ROL_CompositeEqualityConstraint_SimOpt.hpp
```

Therefore, the change is almost certainly due to Eric’s commit.

We either need to fix this test so that it finishes in less than 10 minutes for the standard CI build or it needs to be removed from the BASIC set of tests that run as part of the standard CI build.

Until this gets fixed, people trying to run the checkin-test-sems.py script to test and push will have their pushes stopped due to this failing test.

**Comment by dridzal** [comment]
​There may be a delay in the CDash reporting -- commit 4cd881 should have fixed this issue (it was not a simple timeout, it was an algorithmic issue).

**Comment by bartlettroscoe** [comment]
> ​There may be a delay in the CDash reporting -- commit 4cd881 should have fixed this issue

Yup, there was some lag.  Looks like this is fixed as of the current CI iteration:

*  http://testing.sandia.gov/cdash/index.php?project=Trilinos&parentid=2824818&filtercount=3&showfilters=1&field1=groupname&compare1=61&value1=Continuous&field2=buildstarttime&compare2=84&value2=now&filtercombine=and

> it was not a simple timeout, it was an algorithmic issue

Then it was an algorithmic issue that made it run more than 10 minutes in a debug build since it was reported as a timeout, for example:

* http://testing.sandia.gov/cdash/viewTest.php?onlyfailed&buildid=2824754

Thanks for fixing quickly!

(it is just that the CI build was broken continuously for more than the last 24 hours, but they were due to different errors that unfortunately overlapped.)

I think both of these failures would have been caught before the push if the checkin-test-sems.sh script would have been used.  There is now a nice remote pull/test/push process that once set up requires just a single command and it will run everything on a remote machine.  See:

    https://github.com/trilinos/Trilinos/wiki/Local-development-with-remote-pull,-test,-and-push

I can help anyone interested to set this up.
