### ISSUE TITLE
tpetra compile cuda and shiller

### ISSUE THREAD

**Issue by bathmatt** [trilinos/Trilinos#1222]
I'm getting this in my integration testing on shiller/cuda

[ 55%] Building CXX object packages/tpetra/core/src/CMakeFiles/tpetra.dir/Tpetra_Details_libGemm.cpp.o

/home/jenkins/workspace/Drekar-shiller-cuda-debug/Trilinos/packages/tpetra/core/src/Tpetra_Details_libGemm.cpp(127): error: namespace "std" has no member "runtime_error"

/home/jenkins/workspace/Drekar-shiller-cuda-debug/Trilinos/packages/tpetra/core/src/Tpetra_Details_libGemm.cpp(186): error: namespace "std" has no member "runtime_error"

2 errors detected in the compilation of "/tmp/tmpxft_000054d8_00000000-7_Tpetra_Details_libGemm.cpp1.ii".
make[2]: *** [packages/tpetra/core/src/CMakeFiles/tpetra.dir/Tpetra_Details_libGemm.cpp.o] Error 2
make[2]: Target `packages/tpetra/core/src/CMakeFiles/tpetra.dir/build' not remade because of errors.
make[1]: *** [packages/tpetra/core/src/CMakeFiles/tpetra.dir/all] Error 2
make[1]: Target `all' not remade because of errors.
make: *** [all] Error 2

**Comment by ambrad** [comment]
See also #1220, also related to Tpetra_Details_libGemm.cpp.

**Comment by kddevin** [comment]
@bathmatt 
I don't have the expertise to fix this problem, but I'd try the suggestion at the link below
http://stackoverflow.com/questions/4861777/missing-stdruntime-error-in-qtmingw
It says to 
#include <stdexcept>

Since you already have a build environment set up, would it be difficult to try this addition for us, @bathmatt ?    Thanks.

@crtrott  or @nmhamster   Do you think including <stdexcept> as recommended above will fix this problem?  

http://en.cppreference.com/w/cpp/error/runtime_error

**Comment by nmhamster** [comment]
@kddevin do you have `#include <stdexcept>` in the file being compiled?

**Comment by kddevin** [comment]
Oops, github must not have liked the angle-brackets in my previous message. 

@bathmatt since you already have a build environment set up, would it be easy for you to try including stdexcept as recommended by the webpages and @nmhamster ?  Thanks.

**Comment by bathmatt** [comment]
Pushed this, waiting for testing...

**Comment by mhoemmen** [comment]
Thanks all!  I did actually test this with CUDA so I'm not sure what's different with this build environment.

**Comment by bathmatt** [comment]
This is why we need the testbed machines tested and trilinos team watching
those results...  I'm running my tests through right now, we'll see if it
is fixed

**Comment by bathmatt** [comment]
f15460c appears to have fixed this issue

**Comment by nmhamster** [comment]
@bathmatt @mhoemmen @kddevin I thought we had testing running on Shiller and Hansen at the moment, is that not the case? My VPN is awful today so I can't check.

**Comment by bathmatt** [comment]
http://testing.sandia.gov/cdash/index.php?project=Trilinos&date=2017-04-07
begs to differ.  I'm not seeing any on shiller either.

**Comment by kddevin** [comment]
@bathmatt Thanks for making that change and running the test for us.

**Comment by bathmatt** [comment]
I just made sure it would compile, and not check any runtime issue that
could come up...
