### ISSUE TITLE
Framework: Resolving PR history given 'develop' history change

### ISSUE THREAD

**Issue by sebrowne** [trilinos/Trilinos#12250]
Given the recent history change to the 'develop' branch, you may need to modify the history of any topic branches created 09/05 - 09/12:

To update your local ‘develop’ branch, these commands will (in general) work:
```
git fetch origin (assuming that your origin is https://github.com/trilinos/Trilinos.git)
git checkout develop
git reset --hard origin/develop
```
 
Next, to update your topic branch, these commands will (in general) work:
```
git checkout $MYBRANCH
# OPTIONAL: git checkout -b backup_$MYBRANCH  # This ensures that you can recover your original branch, if you need to
git rebase develop
git push --force origin $MYBRANCH  # This will overwrite your branch on the remote, so be sure it is in a good state
```
 
 
PLEASE NOTE: These commands are not guaranteed to work depending on how your repository is set up.  They are intended to help in the general case.  There are many other ways to resolve the history conflict depending on how you prefer to use git.  Please refer to the git documentation for more in-detailed help.

**Comment by spdomin** [comment]
@cgcgcg, do you believe that this is germane to my bisect issues?

**Comment by cgcgcg** [comment]
It's not the cause of your bisect issues, but probably the reason why your "bad" SHA doesn't resolve to anything in the Trilinos repo.

**Comment by spdomin** [comment]
I am still having issues with the bisect. I simply wonder if my SHA1s provided in my regression test summary are valid? Do I need to move back to a SHA1 before this history change was made, i.e.,

73dcc21ae6078b22b4e281e7064bb2f221339cd0

?

**Comment by sebrowne** [comment]
Some time has passed, suspect most of these issues have been resolved.  There is now an Actions check that prohibits bad commits from being added as well.
