### ISSUE TITLE
NOX test failing due to stratimikos changes

### ISSUE THREAD

**Issue by rppawlo** [trilinos/Trilinos#1226]
The commit below has caused a single nox test to fail in the Trilinos CI build. 

```
commit c3aa0ffa1a55ae46ea2f08b32484aef06d5250ea
Author: Chris Siefert <csiefer@sandia.gov>
Date:   Fri Apr 7 13:14:50 2017 -0600

    Stratimikos: Adding RefMaxwell support
```

@csiefer2 
@trilinos/nox 
@trilinos/muelu 

Output from failing test on cdash:

```
Test output

Teuchos::GlobalMPISession::GlobalMPISession(): started processor with name ceerws1113 and rank 1!
Teuchos::GlobalMPISession::GlobalMPISession(): started processor with name ceerws1113 and rank 2!
Teuchos::GlobalMPISession::GlobalMPISession(): started processor with name ceerws1113 and rank 3!
Teuchos::GlobalMPISession::GlobalMPISession(): started processor with name ceerws1113 and rank 0!
--------------------------------------------------------------------------
mpiexec noticed that the job aborted, but has no info as to the process
that caused that situation.
--------------------------------------------------------------------------
```

**Comment by rppawlo** [comment]
The failure is triggered by a new cast that was added:

+  RCP<const Epetra_CrsMatrix>
+    epetraFwdCrsMat = rcp_dynamic_cast<const Epetra_CrsMatrix>(epetraFwdRowMat,true);

This is a more stringent requirement because it requires a Crs matrix as opposed to just a row matrix (like when using vbr or user defined objects).

Since the object "epetraFwdCrsMat" is only used for the ref-maxwell preconditioner, the above code block should be changed to:

  RCP<const Epetra_CrsMatrix> epetraFwdCrsMat;
  if (problemType == ML_PROBTYPE_REFMAXWELL)
    epetraFwdCrsMat = rcp_dynamic_cast<const Epetra_CrsMatrix>(epetraFwdRowMat,true);

This allows the nox test to pass.

@csiefer2 - Can I make this change?

**Comment by bartlettroscoe** [comment]
Why did the failed `rcp_dynamic_cast<const Epetra_CrsMatrix>(epetraFwdRowMat,true)` not result in a nice exception message?  Is should have printed out a nice error message describing why the dynamic cast failed.

**Comment by csiefer2** [comment]
As per the doxygen, rcp_dynamic_cast isn't supposed to throw by default.

**Comment by rppawlo** [comment]
It does print the RCP cast failure message if you make the test verbose.

**Comment by rppawlo** [comment]
Here's the message:
```
p=0: *** Caught standard std::exception of type 'Teuchos::m_bad_cast' :

 /ascldap/users/rppawlo/Trilinos/packages/teuchos/core/src/Teuchos_dyn_cast.cpp:61:
 
 Throw number = 1
 
 Throw test that evaluated to true: true
 
 dyn_cast<Epetra_CrsMatrix>(Epetra_RowMatrix) : Error, the object with the concrete type 'NOX::Epetra::FiniteDifference' (passed in through the interface type 'Epetra_RowMatrix')  does not support the interface 'Epetra_CrsMatrix' and the dynamic cast failed!
```

**Comment by bartlettroscoe** [comment]
> It does print the RCP cast failure message if you make the test verbose

Does that test produce a lot of output?  If not, then it might be nice to add `--verbose` to the invocation by CTest so that we can see this on CDash.  That would speed up the triaging and diagnosis.

**Comment by bartlettroscoe** [comment]
> Serves me right for copy & pasting code.

That is why we have the safety net of the checkin-test-sems.sh script and the CI build.  It helps us catch our own mistakes before we publish them.  It has saved me from pushing bad code many times over the years.

**Comment by rppawlo** [comment]
Not much output. I can change that as part of this push.

**Comment by csiefer2** [comment]
--no-enable-fwd-packages was clearly the mistake here :)

**Comment by csiefer2** [comment]
BTW, this doesn't fix Teko's problem.  I'll get 'em both in the next half hour or so I think.

**Comment by csiefer2** [comment]
Checkin test chugging on fix for both issues.

**Comment by csiefer2** [comment]
Fix pushed.

As an aside, we should probably consider adding stronger unit testing to Stratimikos.

**Comment by bartlettroscoe** [comment]
> As an aside, we should probably consider adding stronger unit testing to Stratimikos.

Agreed.

**Comment by bartlettroscoe** [comment]
This is fixed as documented at:

* https://github.com/trilinos/Trilinos/issues/1227#issuecomment-293064421

Closing as complete.
