### ISSUE TITLE
Framework: add action to delete merge branches?

### ISSUE THREAD

**Issue by jhux2** [trilinos/Trilinos#12270]
## Question
@trilinos/framework Is it be possible to add a github action to delete branches that have been auto-merged?  Right now, when a PR is automerged and the branch lives in the Trilinos repo, the author has to remember to delete the branch.  As a result, there are a lot of dead branches, including merges to master.  (Alternatively, the project could require branches to be in the author's own fork.)

**Comment by sebrowne** [comment]
I'm fully in favor of this.  I'll try to remember to bring this up at TUG next week, if we get support then we can probably just turn it on.

I'll also note that I'm fully in favor of forcing the fork workflow so that the central repository does not contain WIP from developers.

**Comment by ccober6** [comment]
Adding to the list for open discussion topics.

**Comment by ccober6** [comment]
Putting on the agenda for the Operational Leadership meeting this week.

**Comment by ccober6** [comment]
@jhux2 , I think this is done.  The autotester deletes merged branches, and we went through and cleaned old branches that people were not using.  Can we close this and finished?

**Comment by jhux2** [comment]
Yes, I agree.
