### ISSUE TITLE
Trilinos CI build broken starting on 4/8/2017 with failing NOX and Teko tests

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#1227]
**CC:** @trilinos/framework, @trilinos/teko, @trilinos/nox 

Hello @csiefer2 and @tawiesn,

One (or more) of the commits pushed by you to Trilinos 'develop' on 4/8/2017 broke the CI build (with failing tests NOX_1DfemStratimikosPrec_MPI_4 and  Teko_DiagonallyScaledPreconditioner_MPI_1) as shown here:

* http://testing.sandia.gov/cdash/index.php?project=Trilinos&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Linux-GCC-4.7.2-MPI_RELEASE_DEBUG_SHARED_PT_CI&field2=groupname&compare2=61&value2=Continuous&field3=buildstarttime&compare3=84&value3=now

and in more detail here:

* http://testing.sandia.gov/cdash/index.php?project=Trilinos&parentid=2827563&filtercount=3&showfilters=1&field1=groupname&compare1=61&value1=Continuous&field2=buildstarttime&compare2=84&value2=now&filtercombine=and

The only commits pulled that CI iteration were commits from you two as shown, for example, here:

* http://testing.sandia.gov/cdash/viewNotes.php?buildid=2827737##note0

The test Teko_DiagonallyScaledPreconditioner_MPI_1 failure at:

* http://testing.sandia.gov/cdash/testDetails.php?test=37874341&build=2827737

shows:

```
4. tDiagonallyScaledPreconditioner_application_test_row_UnitTest ... Teko: Inverse "Amesos" is of type strat prec = 0, strat solv = 1, block prec = 0
 Teko: Inverse "ML" is of type strat prec = 1, strat solv = 0, block prec = 0
Error, the parameter {name="refmaxwell: 11list",type="ParameterList",value="..."}
in the parameter (sub)list "ANONYMOUS->Preconditioner Types->ML->ML Settings"
was not found in the list of valid parameters!
```

The other test failure does not show any useful output.

**Comment by bartlettroscoe** [comment]
We need to resolve this ASAP using one of the following options:

1. Fix the failing tests to make them pass
2. Disable those tests in the standard CI build 
3. Back out those commits.

Until we do this, people using the checkin-test-sems.sh script to test upstream packages from these will have their pushes stopped.

**Comment by mhoemmen** [comment]
See #1226 -- it looks like @rppawlo proposed a work-around and is just waiting for confirmation.

**Comment by rppawlo** [comment]
#1126 fixes the nox issue, not the teko issue. The fix would have pushed via checkin test script, but was blocked by Teko failure.

**Comment by bartlettroscoe** [comment]
> #1126 fixes the nox issue, not the teko issue. The fix would have pushed via checkin test script, but was blocked by Teko failure.

You can push by disabling the failing teko test as described in the next to last "NOTE" at the bottom at of:

* https://github.com/trilinos/Trilinos/wiki/Policies-%7C-Safe-Checkin-Testing

by adding:

```
--extra-cmake-options="-DTeko_DiagonallyScaledPreconditioner_MPI_1_DISABLE=ON"
```

to your invocation of the checkin-test-sems.sh script.

If you have completed the pull, configure, and build, then just rerun the tests and push with:

```
./checkin-test-sems.sh \
   --extra-cmake-options="-DTeko_DiagonallyScaledPreconditioner_MPI_1_DISABLE=ON" \
   --test --push
```

(also add `--no-rebase` if it is not okay to rebase.)

**Comment by mhoemmen** [comment]
@rppawlo you mean #1226? just checking :)

**Comment by bartlettroscoe** [comment]
Should be fixed as of commit 9b801c2b.  We will confirm in the next CI build iteration.

Thanks for addressing so quickly @csiefer2!

**Comment by rppawlo** [comment]
> @rppawlo you mean #1226? just checking :)

yes. just fixed in comments above

Thanks @csiefer2 !

**Comment by bartlettroscoe** [comment]
Okay, these tests are now shown passing (see the `-1` in the 'Fail' column `+1` in the 'Pass' column for Teko and NOX rows) in the last CI iteration:

* http://testing.sandia.gov/cdash/index.php?project=Trilinos&parentid=2831042&filtercount=3&showfilters=1&field1=groupname&compare1=61&value1=Continuous&field2=buildstarttime&compare2=84&value2=now&filtercombine=and

Closing as complete.

Thanks again!
