### ISSUE TITLE
PackageName:  General Summary of the Question

### ISSUE THREAD

**Issue by libm3l** [trilinos/Trilinos#12293]
Hello

I was able to configure and compile trilinos. Then I try to compile another solver which uses trilinos functionality. I get an error message:

../../include/Epetra_ConfigDefs.h:108:10: fatal error: Epetra_config.h: No such file or directory
 #include <Epetra_config.h>

I checked and Epetra_config.h does not exist in my trilinos installation. It seems to me that Epetra_config.h is created by cmake. How can I re-create this file?

Thank you
Adam J.

**Comment by cgcgcg** [comment]
@libm3l Could you post the output from you CMake call? This looks like an incomplete configuration.

**Comment by libm3l** [comment]
Here is my configure command:
/opt/cmake/cmake-3.27.4/bin/cmake -DTPL_ENABLE_MPI=ON -DCMAKE_INSTALL_PREFIX=$TRILINOS_ROOT -DTrilinos_ENABLE_Sacado=ON -DTrilinos_ENABLE_Pliris=OFF -DTrilinos_ENABLE_Kokkos=OFF -DBUILD_SHARED_LIBS=ON ../ -DTPL_ENABLE_BLAS=OFF

and attached is file with cmake output 
[output_file.txt](https://github.com/trilinos/Trilinos/files/12677039/output_file.txt)

**Comment by cgcgcg** [comment]
Looking at the file I see:
```
Final set of non-enabled top-level packages:  TrilinosFrameworkTests TrilinosATDMConfigTests Gtest Kokkos KokkosKernels RTOp MiniTensor Epetra Zoltan Shards Triutils EpetraExt Tpetra TrilinosSS Domi Thyra Xpetra Isorropia Pliris AztecOO Galeri Amesos Pamgen Zoltan2Core Ifpack ML Belos ShyLU_Node Amesos2 SEACAS Komplex Anasazi Ifpack2 Stratimikos FEI Teko TriKota Intrepid Intrepid2 Compadre STK Percept Krino Phalanx NOX Moe
rtel MueLu Zoltan2Sphynx Zoltan2 ShyLU_DD ShyLU Rythmos Tempus Stokhos ROL Piro Panzer PyTrilinos NewPackage Adelus TrilinosCouplings Pike TrilinosBuildStats TrilinosInstallTests 64
```
Epetra isn't enabled.

**Comment by libm3l** [comment]
Thanks! I'll try to enable it

**Comment by cgcgcg** [comment]
Ok. Feel free to post on this issue if you encounter difficulties. If the build does go through, please remember to close it.

**Comment by libm3l** [comment]
Just one question - how can I enable Epetra? I do not see any option in cmake --help. Thank you!

**Comment by cgcgcg** [comment]
```
-D Trilinos_ENABLE_Epetra=ON
-D Trilinos_ENABLE_EpetraExt=ON
```
should do the trick. You might have to enable BLAS as well. (Currently you're disabling it.)

**Comment by libm3l** [comment]
Thanks a lot!
