### ISSUE TITLE
Trilinos:  Trouble installing Trilinos

### ISSUE THREAD

**Issue by bdas123** [trilinos/Trilinos#12290]
I am having trouble building Trilinos on LoneStar 6. 

Before I contact them, I thought I would share my configure.sh (configure.txt) and output log (output.txt) and see if you have any insight. 

[configure.txt](https://github.com/trilinos/Trilinos/files/12675490/configure.txt)
[output.txt](https://github.com/trilinos/Trilinos/files/12675496/output.txt)

Here is a list of the related packages and their versions:

  1) cmake/3.24.2   3) xalt/2.10.32   5) intel/19.1.1   7) impi/19.0.9
  2) pmix/3.2.3     4) TACC           6) netcdf/4.6.2   8) python3/3.9.7

Appreciate the help.

**Comment by bdas123** [comment]
/opt/apps/gcc/9.4.0/bin/ld: cannot find -lMPI::MPI_C
make[2]: *** [packages/epetraext/src/CMakeFiles/epetraext.dir/build.make:984: packages/epetraext/src/libepetraext.so.12.11] Error 1
make[1]: *** [CMakeFiles/Makefile2:5357: packages/epetraext/src/CMakeFiles/epetraext.dir/all] Error 2
make: *** [Makefile:169: all] Error 2

**Comment by cgcgcg** [comment]
You could try to reconfigure with `MPI_BASE_DIR` set to make sure MPI libraries and includes are found. Could you also post the output of CMake?

**Comment by cgcgcg** [comment]
Please reopen if this is still an issue.
