### ISSUE TITLE
Belos:  BelosTpetraTestFramework.hpp compilation fatal error: 'Trilinos_Util_iohb.h' file not found

### ISSUE THREAD

**Issue by ndellingwood** [trilinos/Trilinos#12333]
## Bug Report
@trilinos/belos 

### Description
Compilation with Hip+rocm/5.2.0, Serial+gcc/11.3.0 fails with output of the form:
```
03:24:40 In file included from /home/jenkins/caraway-new/workspace/Trilinos_Caraway_Hip_Serial_Rocm5_2_0/Trilinos/packages/belos/tpetra/example/TFQMR/PseudoBlockTFQMRTpetraExFile.cpp:73:
03:24:40 /home/jenkins/caraway-new/workspace/Trilinos_Caraway_Hip_Serial_Rocm5_2_0/Trilinos/packages/belos/tpetra/src/BelosTpetraTestFramework.hpp:56:10: fatal error: 'Trilinos_Util_iohb.h' file not found
03:24:40 #include "Trilinos_Util_iohb.h"
```

I scanned over the failing file for changes the include line has been there since 2019, not sure what would trigger this kind of error...

This is a list of changes that possibly could have triggered the error

[#745 (Sep 26, 2023 10:12:00 PM)](https://jenkins-son.sandia.gov/job/Trilinos_Caraway_Hip_Serial_Rocm5_2_0/745/changes)

    Tpetra: fix uninitialized const ref complaints from clang 14 compiler — [Julia A. Plews](https://jenkins-son.sandia.gov/user/japlews/) / [detail](https://jenkins-son.sandia.gov/job/Trilinos_Caraway_Hip_Serial_Rocm5_2_0/745/changes#detail0)
    ShyLU: Make DebugManager take a user's comm in constructor — [domagala.jacob](https://jenkins-son.sandia.gov/user/domagala.jacob/) / [detail](https://jenkins-son.sandia.gov/job/Trilinos_Caraway_Hip_Serial_Rocm5_2_0/745/changes#detail1)
    Belos: add Tpetra GCRODR test — [antoine.meyer54](https://jenkins-son.sandia.gov/user/antoine.meyer54/) / [detail](https://jenkins-son.sandia.gov/job/Trilinos_Caraway_Hip_Serial_Rocm5_2_0/745/changes#detail2)
    ShyLu: Remove shylu_debug_manager.hpp — [domagala.jacob](https://jenkins-son.sandia.gov/user/domagala.jacob/) / [detail](https://jenkins-son.sandia.gov/job/Trilinos_Caraway_Hip_Serial_Rocm5_2_0/745/changes#detail3)
    Automatic snapshot commit from tribits at c9414267 — [Roscoe A Bartlett](https://jenkins-son.sandia.gov/user/rabartl/) / [detail](https://jenkins-son.sandia.gov/job/Trilinos_Caraway_Hip_Serial_Rocm5_2_0/745/changes#detail4)
    Improve release note for using GNUInstallDirs by default (#12104) — [Roscoe A Bartlett](https://jenkins-son.sandia.gov/user/rabartl/) / [detail](https://jenkins-son.sandia.gov/job/Trilinos_Caraway_Hip_Serial_Rocm5_2_0/745/changes#detail5)
    Belos: Provide Tpetra version of TFQMR examples — [thomas.dutheillet](https://jenkins-son.sandia.gov/user/thomas.dutheillet/) / [detail](https://jenkins-son.sandia.gov/job/Trilinos_Caraway_Hip_Serial_Rocm5_2_0/745/changes#detail6)
    Mention find_package(Trilinos ...) problem with undefined compilers (#12104) — [Roscoe A Bartlett](https://jenkins-son.sandia.gov/user/rabartl/) / [detail](https://jenkins-son.sandia.gov/job/Trilinos_Caraway_Hip_Serial_Rocm5_2_0/745/changes#detail7)
    KokkosKernels: KokkosSparse_spmv_bsrmatrix_tpl_spec_decl.hpp: block_layout -> block_layout_type — [Carl William Pearson](https://jenkins-son.sandia.gov/user/cwpears/) / [detail](https://jenkins-son.sandia.gov/job/Trilinos_Caraway_Hip_Serial_Rocm5_2_0/745/changes#detail8)

[#744 (Sep 25, 2023 10:12:00 PM)](https://jenkins-son.sandia.gov/job/Trilinos_Caraway_Hip_Serial_Rocm5_2_0/744/changes)

    shylu: make shylu_node lib optional — [Nathan David Ellingwood](https://jenkins-son.sandia.gov/user/ndellin/) / [detail](https://jenkins-son.sandia.gov/job/Trilinos_Caraway_Hip_Serial_Rocm5_2_0/744/changes#detail0)
    Use rational number representation where immediate. — [maarten.arnst](https://jenkins-son.sandia.gov/user/maarten.arnst/) / [detail](https://jenkins-son.sandia.gov/job/Trilinos_Caraway_Hip_Serial_Rocm5_2_0/744/changes#detail1)
    Belos: Provide Tpetra version of RCG example — [antoine.meyer54](https://jenkins-son.sandia.gov/user/antoine.meyer54/) / [detail](https://jenkins-son.sandia.gov/job/Trilinos_Caraway_Hip_Serial_Rocm5_2_0/744/changes#detail2)
    Belos: Remove the Dummy file — [antoine.meyer54](https://jenkins-son.sandia.gov/user/antoine.meyer54/) / [detail](https://jenkins-son.sandia.gov/job/Trilinos_Caraway_Hip_Serial_Rocm5_2_0/744/changes#detail3)
    Amesos2: Ifpack2: Panzer: fix deprecation warning — [Jonathan Hu](https://jenkins-son.sandia.gov/user/jhu/) / [detail](https://jenkins-son.sandia.gov/job/Trilinos_Caraway_Hip_Serial_Rocm5_2_0/744/changes#detail4)

### Steps to Reproduce
1. SHA1: bc477b0b056cdfd3347fcd499dd584438865d9cc
2. Hip+rocm/5.2.0 Configuration (Caraway testbed)
```bash
module load rocm/5.2.0 cmake/3.25.2 openblas/0.3.20/rocm/5.2.0 openmpi/4.1.4/rocm/5.2.0
export OMPI_CXX=/home/projects/ROCm/rocm-5.2.0/bin/hipcc

cmake \
-DCMAKE_INSTALL_PREFIX=$PWD/install \
-DCMAKE_CXX_STANDARD="17" \
-DCMAKE_C_COMPILER="mpicc" \
-DCMAKE_CXX_COMPILER="mpicxx" \
-DCMAKE_Fortran_COMPILER=`which gfortran` \
-DCMAKE_BUILD_TYPE="RELEASE" \
-DBUILD_SHARED_LIBS="OFF" \
-DTrilinos_ENABLE_TESTS=ON \
-DTrilinos_ENABLE_ALL_PACKAGES=OFF \
-DTrilinos_ENABLE_ALL_OPTIONAL_PACKAGES=OFF \
-DTrilinos_ENABLE_EXPLICIT_INSTANTIATION=ON \
-DTrilinos_ASSERT_MISSING_PACKAGES=OFF \
-DTrilinos_ALLOW_NO_PACKAGES=OFF \
-DTrilinos_ENABLE_OpenMP=OFF \
-DTrilinos_ENABLE_Amesos2=ON \
-DAmesos2_ENABLE_SuperLU=OFF \
-DAmesos2_ENABLE_KLU2=ON \
-DTrilinos_ENABLE_Belos=ON \
-DTrilinos_ENABLE_Ifpack2=ON \
-DTrilinos_ENABLE_Kokkos=ON \
-DKokkos_ARCH_VEGA908=ON \
-DKokkos_ENABLE_CUDA=OFF \
-DKokkos_ENABLE_HIP=ON \
-DKokkos_ENABLE_OPENMP=OFF \
-DTrilinos_ENABLE_KokkosKernels=ON \
-DTrilinos_ENABLE_MueLu=ON \
-DMueLu_ENABLE_Kokkos_Refactor=ON \
-DTrilinos_ENABLE_Tpetra=ON \
-DTpetra_ENABLE_CUDA=OFF \
-DTpetra_INST_HIP=ON \
-DTpetra_INST_SERIAL=OFF \
-DTpetra_INST_OPENMP=OFF \
-DTpetra_INST_DOUBLE=ON \
-DTrilinos_ENABLE_Gtest=ON \
-DTrilinos_ENABLE_Teuchos=ON \
-DTrilinos_ENABLE_Xpetra=ON \
-DXpetra_ENABLE_Kokkos_Refactor=ON \
-DTrilinos_ENABLE_Zoltan2=ON \
\
-DTPL_ENABLE_BLAS=ON \
-DTPL_ENABLE_LAPACK=ON \
  -D BLAS_LIBRARY_DIRS:FILEPATH="${OPENBLAS_ROOT}/lib" \
  -D BLAS_LIBRARY_NAMES:STRING="openblas" \
-D TPL_ENABLE_LAPACK:STRING=ON \
  -D LAPACK_INCLUDE_DIRS:FILEPATH="${OPENBLAS_ROOT}/include" \
  -D LAPACK_LIBRARY_DIRS:FILEPATH="${OPENBLAS_ROOT}/lib" \
  -D LAPACK_LIBRARY_NAMES:STRING="openblas" \
\
-DTPL_ENABLE_MPI=ON \
-DMPI_USE_COMPILER_WRAPPERS=ON \
-DMPI_EXEC="mpirun" \
-DMPI_EXEC_NUMPROCS_FLAG="-np" \
$TRILINOS_DIR
```

3. Serial + gcc/11.3.0 Configuration (Blake testbed):
```bash
module purge
module load cmake gcc/11.3.0 openmpi/4.1.5 openblas/0.3.23
module load boost/1.82.0 hdf5/1.14.1-2 zlib/1.2.13 netcdf-c/4.9.2
module load metis/5.1.0 parmetis/4.0.3
module list

export NETCDF_ROOT=${NETCDF_C_ROOT}
export PNETCDF_ROOT=${NETCDF_C_ROOT}
export CONFIG_HDF5_LIBS="-L${HDF5_ROOT}/lib;${HDF5_ROOT}/lib/libhdf5_hl.a;${HDF5_ROOT}/lib/libhdf5.a;-lz;-ldl"
export CONFIG_NETCDF_LIBS="-L${NETCDF_C_ROOT}/lib;${NETCDF_C_ROOT}/lib/libnetcdf.a;${CONFIG_HDF5_LIBS}"

# Configure Trilinos
cmake \
  -D CMAKE_CXX_COMPILER="`which mpicxx`" \
  -D CMAKE_C_COMPILER="`which mpicc`" \
  -D CMAKE_Fortran_COMPILER="`which mpifort`" \
  -D CMAKE_CXX_FLAGS="-g" \
  -D CMAKE_C_FLAGS="-g" \
  -DTPL_ENABLE_MPI=ON \
  -DTPL_ENABLE_BLAS:BOOL=ON \
   -DBLAS_LIBRARY_DIRS:FILEPATH=${OPENBLAS_ROOT}/lib \
   -DBLAS_LIBRARY_NAMES:STRING="openblas" \
  -DTPL_ENABLE_LAPACK:BOOL=ON \
   -DLAPACK_INCLUDE_DIRS:FILEPATH=${OPENBLAS_ROOT}/include \
   -DLAPACK_LIBRARY_DIRS:FILEPATH=${OPENBLAS_ROOT}/lib \
   -DLAPACK_LIBRARY_NAMES:STRING="openblas" \
  -DTPL_ENABLE_Boost=ON \
   -DBoost_INCLUDE_DIRS:PATH="${BOOST_ROOT}/include" \
   -DBoost_LIBRARY_DIRS:PATH="${BOOST_ROOT}/lib" \
  -DTPL_ENABLE_BoostLib=ON \
   -DBoostLib_INCLUDE_DIRS:PATH="${BOOST_ROOT}/include" \
   -DBoostLib_LIBRARY_DIRS:PATH="${BOOST_ROOT}/lib" \
  -DTPL_ENABLE_Zlib=ON \
   -DZlib_INCLUDE_DIRS:PATH="${ZLIB_ROOT}/include" \
   -DTPL_Zlib_LIBRARIES:PATH="${ZLIB_ROOT}/lib/libz.a" \
  -DTPL_ENABLE_HDF5=ON \
   -DHDF5_INCLUDE_DIRS:PATH="${HDF5_ROOT}/include" \
   -DTPL_HDF5_LIBRARIES:PATH="${CONFIG_HDF5_LIBS}" \
  -DTPL_ENABLE_Netcdf=ON \
   -DNetcdf_INCLUDE_DIRS:PATH="${NETCDF_ROOT}/include" \
   -DTPL_Netcdf_LIBRARIES:PATH="${CONFIG_NETCDF_LIBS}" \
  -D TPL_ENABLE_METIS:BOOL=ON \
   -D METIS_INCLUDE_DIRS:PATH="${METIS_ROOT}/include" \
   -D METIS_LIBRARY_DIRS:PATH="${METIS_ROOT}/lib" \
   -D METIS_LIBRARY_NAMES:STRING="metis" \
  -D TPL_ENABLE_ParMETIS:BOOL=ON \
   -D ParMETIS_INCLUDE_DIRS:PATH="${PARMETIS_ROOT}/include;${METIS_ROOT}/include" \
   -D ParMETIS_LIBRARY_DIRS:PATH="${PARMETIS_ROOT}/lib" \
   -D ParMETIS_LIBRARY_NAMES:STRING="parmetis" \
\
  -DTrilinos_ENABLE_ALL_PACKAGES=OFF \
  -DTrilinos_ENABLE_ALL_OPTIONAL_PACKAGES=OFF \
  -DTrilinos_ENABLE_TESTS=OFF \
  -DTrilinos_MUST_FIND_ALL_TPL_LIBS=TRUE \
  -DTrilinos_ENABLE_COMPLEX=ON \
  -DTrilinos_ENABLE_OpenMP=OFF \
  -DTrilinos_ENABLE_Kokkos=ON \
  -D Kokkos_ENABLE_SERIAL=ON \
  -D Kokkos_ARCH_SKX=ON \
  -DTrilinos_ENABLE_KokkosKernels=ON \
  -DTrilinos_ENABLE_Tpetra=ON \
   -D Tpetra_ENABLE_TESTS=ON \
  -DTrilinos_ENABLE_Belos=ON \
   -D Belos_ENABLE_TESTS=ON \
  -DTrilinos_ENABLE_Sacado=ON \
  -DTrilinos_ENABLE_Stokhos=ON \
  -DTrilinos_ENABLE_Intrepid2=ON \
  -DTrilinos_ENABLE_Amesos2=ON \
  -DTrilinos_ENABLE_Ifpack2=ON \
  -DTrilinos_ENABLE_Zoltan2=ON \
\
  -DTPL_ENABLE_Matio=OFF \
\
$TRILINOS_DIR
```

**Comment by ndellingwood** [comment]
This showed up for me with a gcc/11.3.0 build with the Serial backend as well, updated the OP to add a reproducer configuration

**Comment by hkthorn** [comment]
@ndellingwood There is an error in the CMakeLists.txt file in that directory that is causing cmake to build it even if Triutils is not enabled.  I'll get a PR in for that.  Thanks!

**Comment by ndellingwood** [comment]
Thanks @hkthorn !

**Comment by ndellingwood** [comment]
Closing following merge of #12343, thanks @hkthorn !

**Comment by ndellingwood** [comment]
This error is still occurring with the rocm build, reopening (sorry @hkthorn ). Looks like the gmres test

```
00:23:33 In file included from /home/jenkins/caraway-new/workspace/Trilinos_Caraway_Hip_Serial_Rocm5_2_0/Trilinos/packages/belos/tpetra/test/BlockGmres/test_resolve_gmres_hb.cpp:58:
00:23:33 /home/jenkins/caraway-new/workspace/Trilinos_Caraway_Hip_Serial_Rocm5_2_0/Trilinos/packages/belos/tpetra/src/BelosTpetraTestFramework.hpp:56:10: fatal error: 'Trilinos_Util_iohb.h' file not found
00:23:33 #include "Trilinos_Util_iohb.h"
00:23:33          ^~~~~~~~~~~~~~~~~~~~~~
00:23:33 1 error generated when compiling for gfx908.
00:23:33 make[2]: *** [packages/belos/tpetra/test/BlockGmres/CMakeFiles/Belos_Tpetra_resolve_gmres_hb.dir/build.make:76: packages/belos/tpetra/test/BlockGmres/CMakeFiles/Belos_Tpetra_resolve_gmres_hb.dir/test_resolve_gmres_hb.cpp.o] Error 1
00:23:33 make[2]: Leaving directory '/home/jenkins/caraway-new/workspace/Trilinos_Caraway_Hip_Serial_Rocm5_2_0/Build'
00:23:33 make[1]: *** [CMakeFiles/Makefile2:42878: packages/belos/tpetra/test/BlockGmres/CMakeFiles/Belos_Tpetra_resolve_gmres_hb.dir/all] Error 2
00:23:33 make[1]: *** Waiting for unfinished jobs....
00:23:35 In file included from /home/jenkins/caraway-new/workspace/Trilinos_Caraway_Hip_Serial_Rocm5_2_0/Trilinos/packages/belos/tpetra/test/BlockGmres/test_pseudo_gmres_hb.cpp:62:
00:23:35 /home/jenkins/caraway-new/workspace/Trilinos_Caraway_Hip_Serial_Rocm5_2_0/Trilinos/packages/belos/tpetra/src/BelosTpetraTestFramework.hpp:56:10: fatal error: 'Trilinos_Util_iohb.h' file not found
00:23:35 #include "Trilinos_Util_iohb.h"
```

**Comment by ndellingwood** [comment]
This is resovled
