### ISSUE TITLE
Ifpack2: RILUK (with KK spiluk) runs out of memory on serial backend, not Cuda

### ISSUE THREAD

**Issue by brian-kelley** [trilinos/Trilinos#12340]
### Description
On the SierraTF abnormal energy problems, this Ifpack2 preconditioner works fine on Vortex with 16 ranks:
```
  <Parameter name="Ifpack2::Preconditioner" type="string" value="SCHWARZ"/>
  <ParameterList name="Ifpack2">
    <Parameter name="schwarz: overlap level" type="int" value="2"/>
    <Parameter name="schwarz: combine mode" type="string" value="ZERO"/>
    <Parameter name="schwarz: use reordering" type="bool" value="true"/>
    <Parameter name="subdomain solver name" type="string" value="RILUK"/>
    <ParameterList name="subdomain solver parameters">
      <Parameter name="fact: iluk level-of-fill" type="int" value="3"/>
      <Parameter name="fact: iluk level-of-overlap" type="int" value="0"/>
      <Parameter name="fact: type" type="string" value="KSPILUK"/>
      <Parameter name="trisolver: type" type="string" value="KSPTRSV"/>
    </ParameterList>
  </ParameterList>
```
but when moved to Eclipse with 144 ranks (even spread over 9 or 16 nodes), the job is killed due to out-of-memory. This is strange because the local matrix on each rank has 9x fewer rows than with the 16-rank distribution, so even with the level-2 overlap it seems like the total size of the LU factors should be significantly smaller. On the other hand, it's possible that high-density rows are causing the overlapping matrices to be larger than expected.

**Comment by brian-kelley** [comment]
@vbrunini @jclause  @jhux2 Here are some measurements for one of the problems, with 21398968 total (global) entries. I ran with 144 ranks (over 12 nodes of Eclipse).

| Schwarz overlap  | ILU fill level | max nnz(Alocal) | max nnz(L) + nnz(U) | GMRES iters | Total solve time |
| ------------- | ------------- | ---- | ---- | ---- | --- |
| 0  | 0  | 121114 |131114 | 87 | 1.34247 |
| 0  | 1  |121114 | 226382| 88 | 1.28338 |
| 0  | 2  |121114 | 379032| 88 |  1.66014 |
| 1  | 0  |6182360 | 6662006|40 | 5.19928 | 
| 1  | 1  |6182360 | 14325024| 38 | 6.24606 |
| 1  | 2  |6182360 |28037414 | 40 | 8.66948 |
| 2  | 0  | 8942413|OOM |- | - |
| 2  | 1  |8942413 | OOM | - | - |
| 2  | 2  | 8942413| OOM | - | - |

I don't think there is any bug here - the bulk rows cause the memory usage of both overlapping Schwarz and ILU to increase very quickly as the overlap level/fill level increase. For example, by Schwarz overlap level 2, over 1/3 of the global matrix is locally replicated on one rank. And for overlap=1, fill=2, the L and U factors on one rank are combined larger than the original global matrix (28M vs. 21M entries).

The solution here is just to keep these parameters as small as possible, I think. Yes, a larger overlap gives a much more effective preconditioner but the cost (in preconditioner apply time) is so high that the time-to-solution is worse.

**Comment by jhux2** [comment]
@brian-kelley Thank you for the analysis.
