### ISSUE TITLE
 ROL_adapters_tpetra_test_sol_TpetraSimulatedConstraintInterfaceDual_MPI_4 timing out in CI build after push on 4/11/2017

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#1235]
**Description:**

It looks like a one of the commits pushed to Trilinos that was pulled in this CI iteration today:

* http://testing.sandia.gov/cdash/index.php?project=Trilinos&parentid=2832775&filtercount=3&showfilters=1&field1=groupname&compare1=61&value1=Continuous&field2=buildstarttime&compare2=84&value2=now&filtercombine=and

where the commits pulled are shown here:

* http://testing.sandia.gov/cdash/viewNotes.php?buildid=2832781##note1 

resulted in the test `ROL_adapters_tpetra_test_sol_TpetraSimulatedConstraintInterfaceDual_MPI_4` starting to timeout in the standard CI build (and that is at 10 minutes).

From looking at the commits, it seems likely that changes from a ROL developer resulted in this ROL test now timing out.

**CC:** @trilinos/framework, @trilinos/rol

**Comment by dridzal** [comment]
I believe that the commit

https://github.com/trilinos/Trilinos/commit/d6fced53c9c6e717623fd27a4e7c086f9e92af15

took care of this issue.  I'll reopen if necessary.

**Comment by bartlettroscoe** [comment]
Yup.  Looks like it got cleaned up in this CI iteration:

* http://testing.sandia.gov/cdash/index.php?project=Trilinos&parentid=2834087&filtercount=3&showfilters=1&field1=groupname&compare1=61&value1=Continuous&field2=buildstarttime&compare2=84&value2=now&filtercombine=and

and we see the commit d6fced5 in the Updates.txt notes file:

* http://testing.sandia.gov/cdash/viewNotes.php?buildid=2834397##note1

Thanks for fixing so quickly :-)
