### ISSUE TITLE
Building and running error with Epetra while pthread is enabled 

### ISSUE THREAD

**Issue by kliegeois** [trilinos/Trilinos#1236]
I have two linked issues.

1) While trying to run the MueLu tutorial, I faced a cast error:

```
Cast from Xpetra::CrsMatrix to Xpetra::EpetraCrsMatrix failed.
```
It seems that Tobias has already faced the same cast error in the test packages/muelu/test/navierstokes/Navier2D_Epetra.cpp as shown in the following print screen.

<img width="640" alt="piece jointe" src="https://cloud.githubusercontent.com/assets/15634348/24945673/826640c8-1f60-11e7-959c-93df2ebbecba.png">

In my case, I am building on macOS Sierra 10.12.4 with clang (Apple LLVM version 8.1.0 (clang-802.0.41)) with pthread switched to ON , serial, openmp, and cuda switched to OFF. Disabling pthread removed the cast error and it was possible to run the MueLu tutorial.

2) I have tried to build the TrilinosCouplings examples with pthread switched to ON , serial, openmp, and cuda switched to OFF. The compilation failed while compiling the file packages/trilinoscouplings/examples/scaling/IntrepidPoisson_Pamgen_Epetra_main.cpp with the following error:
```
In file included from /Users/kliegeois/dev/Trilinos/packages/trilinoscouplings/examples/scaling/IntrepidPoisson_Pamgen_Epetra_main.cpp:63:
In file included from /Users/kliegeois/dev/Trilinos/packages/teuchos/core/src/Teuchos_GlobalMPISession.hpp:52:
In file included from /Users/kliegeois/dev/Trilinos/packages/teuchos/core/src/Teuchos_ArrayView.hpp:47:
In file included from /Users/kliegeois/dev/Trilinos/packages/teuchos/core/src/Teuchos_ArrayRCP.hpp:46:
In file included from /Users/kliegeois/dev/Trilinos/packages/teuchos/core/src/Teuchos_ArrayRCPDecl.hpp:47:
/Users/kliegeois/dev/Trilinos/packages/teuchos/core/src/Teuchos_RCP.hpp:288:5: error: cannot initialize a member subobject of type
      'MueLu::Hierarchy<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > *' with an
      rvalue of type 'MueLu::Hierarchy<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Threads,
      Kokkos::HostSpace> > *'
  : ptr_(r_ptr.get()), // will not compile if T is not base class of T2
    ^    ~~~~~~~~~~~
/Users/kliegeois/dev/Trilinos/packages/trilinoscouplings/examples/scaling/IntrepidPoisson_Pamgen_Epetra_main.cpp:286:45: note: in
      instantiation of function template specialization 'Teuchos::RCP<MueLu::Hierarchy<double, int, int,
      Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > >::RCP<MueLu::Hierarchy<double, int, int,
      Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Threads, Kokkos::HostSpace> > >' requested here
          M = rcp(new MueLu::EpetraOperator(H));
```

This error was removed while compiling: 
- with serial switched to ON , pthread, openmp, and cuda switched to OFF. 
- or with pthread switched to ON , serial, openmp, and cuda switched to OFF, and TrilinosCouplings_ENABLE_Epetra:BOOL=OFF.

**Comment by mhoemmen** [comment]
@trilinos/muelu

**Comment by tawiesn** [comment]
@kliegeois Comment on problem 2: it seems you have both the Epetra and Tpetra stack enabled with Xpetra, but Tpetra is only instantiated on the Pthread node. This is not possible. The logic of Xpetra is to provide a 100% compatibility layer for both Tpetra and Epetra. That is, as soon as you have both Epetra and Tpetra enabled (with Xpetra) you have to enable either the Serial or the OpenMP node (in addition to the desired Pthreads node). If you disable Epetra completely, you should be able to build a Trilinos version with Tpetra support on the Pthreads node only. Does that make sense?
I'm going to add a check in CMakeLists.txt which should catch this problem during configure time with a helpful error message. This should go into the develop branch within the next couple of days.

**Comment by tawiesn** [comment]
This configure check will also filter problem 1.

**Comment by kliegeois** [comment]
@tawiesn Yes, it does definitely make sense. 
Just to make sure, I have just rebuild Trilinos with serial and pthread switched to ON. The compilation has ended without errors and it the MueLu tutorial ran smoothly. Both problems are gone.

Thanks a lot.
