### ISSUE TITLE
tpetra w/ CUDA 12: tpetra/core/test/KokkosIntegration/Intercept.cpp(86): error: function "cudaMemcpy2DAsync" has already been defined

### ISSUE THREAD

**Issue by eugeneswalker** [trilinos/Trilinos#12377]
## Bug Report
@csiefer2 @nchaimov

### Description
Building `trilinos@master +testing +amesos +amesos2 +anasazi +aztec +belos +boost +epetra +epetraext +ifpack +ifpack2 +intrepid ~intrepid2 +isorropia +kokkos +ml +minitensor +muelu +nox +piro +phalanx +rol +rythmos +sacado +stk +shards +shylu +stokhos +stratimikos +teko +tempus +tpetra +trilinoscouplings +zoltan +zoltan2 +superlu-dist gotype=long_long +wrapper +cuda cuda_arch=80 cxxstd=17` fails using:
* CUDA 12.0.1
* GCC 11.4.0
* Ubuntu 20.04, X86_64

```
$> spack dev-build -j48 +testing +amesos +amesos2 +anasazi +aztec +belos +boost +epetra +epetraext +ifpack +ifpack2 +intrepid ~intrepid2 +isorropia +kokkos +ml +minitensor +muelu +nox +piro +phalanx +rol +rythmos +sacado +stk +shards +shylu +stokhos +stratimikos +teko +tempus +tpetra +trilinoscouplings +zoltan +zoltan2 +superlu-dist gotype=long_long +wrapper +cuda cuda_arch=80 cxxstd=17
...
/e4s-develop/collab/trilinos/ctest-cuda/Trilinos/packages/tpetra/core/test/KokkosIntegration/Intercept.cpp(86): error: function "cudaMemcpy2DAsync" has already been defined
/e4s-develop/collab/trilinos/ctest-cuda/Trilinos/packages/tpetra/core/test/KokkosIntegration/Intercept.cpp(98): error: function "cudaMemcpy3DAsync" has already been defined
/e4s-develop/collab/trilinos/ctest-cuda/Trilinos/packages/tpetra/core/test/KokkosIntegration/Intercept.cpp(110): error: function "cudaMemcpyAsync" has already been defined
[ 77%] Linking CXX shared library libApiTest.so
...
```

### Steps to Reproduce
Reproducible here using Docker container image:
* `ecpe4s/ubuntu20.04-runner-amd64-gcc-11.4-mpi-base:2023.08.20`

Spack environment: [spack.yaml.txt](https://github.com/trilinos/Trilinos/files/12839430/spack.yaml.txt)

<details><summary>Concretization</summary>

<pre>
 -   sdfflej  trilinos@master%gcc@11.4.0~adelus~adios2+amesos+amesos2+anasazi+aztec~basker+belos+boost~chaco~complex+cuda~cuda_rdc~debug~dtk+epetra+epetraext~epetraextbtf~epetraextexperimental~epetraextgraphreorderings~exodus+explicit_template_instantiation~float+fortran~gtest~hdf5~hypre+ifpack+ifpack2+intrepid~intrepid2~ipo+isorropia+kokkos~mesquite+minitensor+ml+mpi+muelu~mumps+nox~openmp~panzer+phalanx+piro~python~rocm~rocm_rdc+rol+rythmos+sacado~scorec+shards+shared+shylu+stk+stokhos+stratimikos~strumpack~suite-sparse~superlu+superlu-dist+teko+tempus+testing+thyra+tpetra+trilinoscouplings~uvm+wrapper~x11+zoltan+zoltan2 build_system=cmake build_type=Release cuda_arch=80 cxxstd=17 generator=make gotype=long_long arch=linux-ubuntu20.04-x86_64
[+]  ia5ufsp      ^boost@1.83.0%gcc@11.4.0~atomic~chrono~clanglibcpp~container~context~contract~coroutine~date_time~debug+exception~fiber~filesystem+graph~graph_parallel~icu~iostreams~json~locale~log+math+mpi+multithreaded~nowide~numpy~pic~program_options~python~random~regex~serialization+shared~signals~singlethreaded+stacktrace~system~taggedlayout~test~thread~timer~type_erasure~versionedlayout~wave build_system=generic cxxstd=17 patches=a440f96 visibility=hidden arch=linux-ubuntu20.04-x86_64
[+]  j56nveb      ^cmake@3.27.6%gcc@11.4.0~doc+ncurses+ownlibs build_system=generic build_type=Release arch=linux-ubuntu20.04-x86_64
[+]  krhswgy          ^curl@8.1.2%gcc@11.4.0~gssapi~ldap~libidn2~librtmp~libssh~libssh2+nghttp2 build_system=autotools libs=shared,static tls=openssl arch=linux-ubuntu20.04-x86_64
[+]  y72nyuk              ^nghttp2@1.52.0%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]  m2nqw34              ^openssl@3.1.3%gcc@11.4.0~docs+shared build_system=generic certs=mozilla arch=linux-ubuntu20.04-x86_64
[+]  thgudgh                  ^ca-certificates-mozilla@2023-05-30%gcc@11.4.0 build_system=generic arch=linux-ubuntu20.04-x86_64
[+]  4ahtcrh          ^ncurses@6.4%gcc@11.4.0~symlinks+termlib abi=none build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]  vkxpza5      ^cuda@12.0.1%gcc@11.4.0~allow-unsupported-compilers~dev build_system=generic arch=linux-ubuntu20.04-x86_64
[+]  w3n2rgb          ^libxml2@2.10.3%gcc@11.4.0+pic~python+shared build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]  bb6pvt7              ^libiconv@1.17%gcc@11.4.0 build_system=autotools libs=shared,static arch=linux-ubuntu20.04-x86_64
[+]  7gqmxvf              ^xz@5.4.1%gcc@11.4.0~pic build_system=autotools libs=shared,static arch=linux-ubuntu20.04-x86_64
[+]  axbtmvn      ^gmake@4.4.1%gcc@11.4.0~guile build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]  tkc6zfe      ^hwloc@2.9.1%gcc@11.4.0~cairo+cuda~gl~libudev+libxml2~netloc~nvml~oneapi-level-zero~opencl+pci~rocm build_system=autotools cuda_arch=none libs=shared,static arch=linux-ubuntu20.04-x86_64
[+]  wjzjxgg          ^libpciaccess@0.17%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]  3cmrrml              ^libtool@2.4.7%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]  dije4dh                  ^m4@1.4.19%gcc@11.4.0+sigsegv build_system=autotools patches=9dc5fbd,bfdffa7 arch=linux-ubuntu20.04-x86_64
[+]  uxiki2z                      ^libsigsegv@2.14%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]  pv4s6pa              ^util-macros@1.19.3%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]  hjpgnti          ^pkgconf@1.9.5%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]  f4abxog      ^kokkos-nvcc-wrapper@4.1.00%gcc@11.4.0 build_system=generic arch=linux-ubuntu20.04-x86_64
[+]  l6dookb      ^metis@5.1.0%gcc@11.4.0~gdb~int64~ipo~real64+shared build_system=cmake build_type=Release generator=make patches=4991da9,93a7903,b1225da arch=linux-ubuntu20.04-x86_64
[e]  4vf2w2d      ^mpich@4.1.2%gcc@11.4.0~argobots~cuda+fortran~hwloc+hydra+libxml2+pci~rocm+romio~slurm~vci~verbs~wrapperrpath build_system=autotools datatype-engine=auto device=ch4 netmod=ofi pmi=pmi arch=linux-ubuntu20.04-x86_64
[+]  2n67kk5      ^openblas@0.3.24%gcc@11.4.0~bignuma~consistent_fpcsr+fortran~ilp64+locking+pic+shared build_system=makefile symbol_suffix=none threads=none arch=linux-ubuntu20.04-x86_64
[+]  ymeouv6          ^perl@5.38.0%gcc@11.4.0+cpanm+opcode+open+shared+threads build_system=generic patches=714e4d1 arch=linux-ubuntu20.04-x86_64
[+]  z5d3lru              ^berkeley-db@18.1.40%gcc@11.4.0+cxx~docs+stl build_system=autotools patches=26090f4,b231fcc arch=linux-ubuntu20.04-x86_64
[+]  mxcjdbv              ^bzip2@1.0.8%gcc@11.4.0~debug~pic+shared build_system=generic arch=linux-ubuntu20.04-x86_64
[+]  zafnh7n                  ^diffutils@3.9%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]  adx2gsg              ^gdbm@1.23%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]  bhdepb5                  ^readline@8.2%gcc@11.4.0 build_system=autotools patches=bbf97f1 arch=linux-ubuntu20.04-x86_64
[+]  wcatis4      ^parmetis@4.0.3%gcc@11.4.0~gdb~int64~ipo+shared build_system=cmake build_type=Release generator=make patches=4f89253,50ed208,704b84f arch=linux-ubuntu20.04-x86_64
[+]  ur6zd25      ^superlu-dist@develop%gcc@11.4.0~cuda~int64~ipo~openmp~rocm+shared build_system=cmake build_type=Release generator=make arch=linux-ubuntu20.04-x86_64
[+]  hpmj5kc      ^zlib-ng@2.1.3%gcc@11.4.0+compat+opt build_system=autotools patches=299b958,ae9077a,b692621 arch=linux-ubuntu20.04-x86_64
</pre></details>

```
$> docker run -it ecpe4s/ubuntu20.04-runner-amd64-gcc-11.4-mpi-base:2023.08.20
root@a6fe029d2d1d:/# git clone https://github.com/eugeneswalker/spack
root@a6fe029d2d1d:/# git -C spack checkout trilinos-ctest
root@a6fe029d2d1d:/# git -C spack log -1
commit 97e40a4bdc8529bf9ae542cc69007796d77b9665 (HEAD -> trilinos-ctest, origin/trilinos-ctest)
Author: eugeneswalker <eugenesunsetwalker@gmail.com>
Date:   Thu Sep 28 13:48:57 2023 -0700

    add kokkos-nvcc-wrapper v4.1.00

root@a6fe029d2d1d:/# . spack/share/spack/setup-env.sh
root@a6fe029d2d1d:/# spack env activate -d .
root@a6fe029d2d1d:/# spack concretize -f | tee concretize.log
root@a6fe029d2d1d:/# spack install --only dependencies --include-build-deps
... OK

root@a6fe029d2d1d:/# git clone https://github.com/trilinos/Trilinos.git
root@a6fe029d2d1d:/# git -C Trilinos checkout 5aaae1ada6fe1ce777e671a0ff84fdc4f0779406

root@a6fe029d2d1d:/# cd Trilinos
root@a6fe029d2d1d:/# nohup bash -c "time spack dev-build -j48 trilinos@master +testing +amesos +amesos2 +anasazi +aztec +belos +boost +epetra +epetraext +ifpack +ifpack2 +intrepid ~intrepid2 +isorropia +kokkos +ml +minitensor +muelu +nox +piro +phalanx +rol +rythmos +sacado +stk +shards +shylu +stokhos +stratimikos +teko +tempus +tpetra +trilinoscouplings +zoltan +zoltan2 +superlu-dist gotype=long_long +wrapper +cuda cuda_arch=80 cxxstd=17" &

root@a6fe029d2d1d:/# tail -f nohup.out
...
/e4s-develop/collab/trilinos/ctest-cuda/Trilinos/packages/tpetra/core/test/KokkosIntegration/Intercept.cpp(86): error: function "cudaMemcpy2DAsync" has already been defined
/e4s-develop/collab/trilinos/ctest-cuda/Trilinos/packages/tpetra/core/test/KokkosIntegration/Intercept.cpp(98): error: function "cudaMemcpy3DAsync" has already been defined
/e4s-develop/collab/trilinos/ctest-cuda/Trilinos/packages/tpetra/core/test/KokkosIntegration/Intercept.cpp(110): error: function "cudaMemcpyAsync" has already been defined

[ 77%] Linking CXX shared library libApiTest.so
...
```

**Comment by maartenarnst** [comment]
Might be related to  
- #12266.

**Comment by eugeneswalker** [comment]
> @eugeneswalker Can you try develop? @maartenarnst's fixes aren't in master yet.

Fixed in develop, thank you!
