### ISSUE TITLE
Minitensor produces compiler warning with Intel 17

### ISSUE THREAD

**Issue by djlittl** [trilinos/Trilinos#1238]
I'm using minitensor::Vector in an application code, and when building on linux with Intel 17.0.1 I am seeing the following warning.

include/MiniTensor_Vector.h(125): warning #488: template parameter "ArrayT" is not used in declaring the parameter types of function template "minitensor::Vector<<f>T, N, ES>::Vector<<f>ArrayT,iType>(Kokkos::Impl::enable_if<<f><<f>expression>, ArrayT>::type &, iType)"
    template<<f>class ArrayT, typename iType>

I have passed additional details directly to @lxmota, author of mini tensor.

**Comment by dridzal** [comment]
I've seen the same warning with Intel 17.0.1.  It would be good to clean it up, as it comes up a lot when building Trilinos.

**Comment by lxmota** [comment]
This issue has been solved on the Trilinos side, but it required changes that will affect @djlittl's application. I will have to coordinate with him on that.

The Intel 17 compiler is producing other warning messages as well for MiniTensor. I'm currently working on those.
