### ISSUE TITLE
Teuchos:  clang reporting improper cast in Teuchos_LAPACK.cpp

### ISSUE THREAD

**Issue by glhenni** [trilinos/Trilinos#12385]
## Bug Report
@bartlettroscoe not really sure who owns this one but the error is happening when compiling _Teuchos\_LAPACK.cpp_ so you're the "lucky" winner.

### Description
As of last night I'm getting the following error when compiling _Teuchos\_LAPACK.cpp_ from the _develop_ branch:
```
/Trilinos/packages/teuchos/numerics/src/Teuchos_LAPACK.cpp:2096:49: error: implicit conversion from '_Complex double' to 'const double' is not permitted in C++
    return static_cast<Kokkos::complex<double>>(z);
           ~~~~~~~~~~~                          ^
1 error generated.
```

**Comment by hkthorn** [comment]
@glhenni Which platform/machine are you using that generated this error?

**Comment by glhenni** [comment]
> @glhenni Which platform/machine are you using that generated this error?

This is an ascic platform, ascic0202, but it should be the same as any SRN COE RHEL7, e.g,, ascic0180, cee-build030, etc. I'm using `module load cde/v3/devpack/clang-ompi`

**Comment by vqd8a** [comment]
I was able to re-produce the error. I am going to have a PR to fix it.

**Comment by hkthorn** [comment]
@vqd8a Thanks!

**Comment by bartlettroscoe** [comment]
CC: @sebrowne 

Can we ask why none of the Trilinos PR or nighty builds showed this error?  Is anyone concerned that there is no automated test coverage for:

* #12388 

?

(That PR does not touch any tests or any build configurations that would have exposed the error reported here.)

Note the Trilinos test policy:

* https://github.com/trilinos/Trilinos/wiki/Trilinos-Testing-Policy

**Comment by bartlettroscoe** [comment]
> @bartlettroscoe not really sure who owns this one but the error is happening when compiling Teuchos_LAPACK.cpp so you're the "lucky" winner.

@glhenni, I am okay with being the winner on these if I can get the funding to do it 😊
