### ISSUE TITLE
Teuchos::OrdinalTraits constexpr

### ISSUE THREAD

**Issue by bartgol** [trilinos/Trilinos#1242]
I was trying to use Teuchos::OrdinalTraits::invalid() in a constexpr, and the compiler bit me.

So I was wondering: is there a reason why the methods in Teuchos::OrdinalTraits are not constexpr?

**Comment by mhoemmen** [comment]
@trilinos/teuchos Teuchos has users who need to build with C++98 compilers, so it cannot use `constexpr` by default.  If you would like to submit a patch or pull request to fix this, please use the `HAVE_TEUCHOSCORE_CXX11` macro to protect use of C++11 features, and have a fall-back for C++98 compilers.  Thanks!
