### ISSUE TITLE
How to link Kokkos issues in the SART board?

### ISSUE THREAD

**Issue by bathmatt** [trilinos/Trilinos#1243]
There are kokkos issues on the kokkos board to the SART board?  We need to track these as well without duplication

**Comment by bartlettroscoe** [comment]
Why not just create dummy Trilinos GitHub issues in the SART board that just provide links to the issues in https://github.com/kokkos/kokkos/issues?  That is low overhead and does the job of making sure that it is seen in SART meetings.

**Comment by ibaned** [comment]
With the proper link syntax: `kokkos/kokkos#123`, GitHub will create a bi-directional link between them that is easy to see and will remind us to close the Trilinos issue when the Kokkos issue is closed.
