### ISSUE TITLE
Anasazi:  Installation with Tpetra

### ISSUE THREAD

**Issue by Adrian-Diaz** [trilinos/Trilinos#12439]
Greetings, 
I was trying to install the anasazi package along with my usual build but it seems the basic anasazi=ON didn't give me all the header files I need such as AnasaziGlobalComm.hpp. Are there any other build settings required? The following is my cmake config for Trilinos:

-D CMAKE_BUILD_TYPE=Release
-D Trilinos_MUST_FIND_ALL_TPL_LIBS=TRUE
-D CMAKE_CXX_STANDARD=17
-D TPL_ENABLE_MPI=ON
-D Trilinos_ENABLE_Kokkos=ON
-D Trilinos_ENABLE_OpenMP=ON
-D Trilinos_ENABLE_Amesos2=ON
-D Trilinos_ENABLE_Belos=ON
-D Trilinos_ENABLE_MueLu=ON 
-D Trilinos_ENABLE_ROL=ON 
-D Trilinos_ENABLE_Ifpack2=ON
-D Trilinos_ENABLE_Zoltan2=ON 
-D Trilinos_ENABLE_Anasazi=ON 
-D MueLu_ENABLE_TESTS=OFF 
-D Trilinos_ENABLE_ALL_PACKAGES=OFF 
-D Trilinos_ENABLE_ALL_OPTIONAL_PACKAGES=OFF 
-D Trilinos_ENABLE_TESTS=OFF 
-D CMAKE_INSTALL_PREFIX=${TRILINOS_INSTALL_DIR} 

Thanks for any help rendered,

Sincerely,
Adrian Diaz

**Comment by cgcgcg** [comment]
Hm, this should have been fixed in #12177. Can you pull a recent develop?

**Comment by Adrian-Diaz** [comment]
Yea re-pulling Trilinos seems to have worked. Thanks!
