### ISSUE TITLE
Random build errors bringing down PR build & test iterations 2023

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#12450]
CC: @ccober6, @sebrowne, @trilinos/framework 

## Description

Anecdotal evidence seems to suggest that overloading build failures are bringing down PR testing iterations fairly regularly (but we need more data to quantify this).  For example, the PR iteration:

* https://github.com/trilinos/Trilinos/pull/12442#issuecomment-1780099282

Was killed due to random overloading build errors showing output like:

```
icpc: error #10106: Fatal error in /projects/sems/install/rhel7-x86_64/sems-compilers/tpl/intel-oneapi-compilers/2021.3.0/gcc/8.3.0/base/fptsktp/compiler/2021.3.0/linux/bin/intel64/mcpcom, terminated by kill signal
```

and

```
g++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
```

This, together with all of the other random test failures in Trilinos (such as random test timeouts in #12391) conspire to result in a lot of PR testing iterations that would have passed to fail.

## Suggested solution

It seems highly likely that if the build was ran again after the initial failure that it would likely pass on the second try.  Afterall, that is what a developer would do on their local machine.  They would not blow away the entire build directory and start from scratch (which is what the Trilinos autotester does).  Therefore, if the CTest -S driver was modified to do one extra rebuild, that may cause many of these builds to pass.  This presents a problem on what to report to CDash but it would likely greatly avoid these random build errors from bringing down.

But someone must set up metrics for the Trilinos testing system to monitor how many of these random build errors are occurring.

**Comment by sebrowne** [comment]
@bartlettroscoe this is exactly what SPARC does for their nightly builds (particularly this has a tendency of hitting the classic Intel compilers, I was very surprised to see it for GCC).  And yes, it does cause an issue with what is reported to CDash in that you can see build failures that aren't "real", meaning the code built the second time around (they also reduce the core count to 4 on the retry to help avoid overloading, because we assume that MOST everything else got built).

**Comment by bartlettroscoe** [comment]
> @bartlettroscoe this is exactly what SPARC does for their nightly builds (particularly this has a tendency of hitting the classic Intel compilers, I was very surprised to see it for GCC).

👍

> And yes, it does cause an issue with what is reported to CDash in that you can see build failures that aren't "real", meaning the code built the second time around (they also reduce the core count to 4 on the retry to help avoid overloading, because we assume that MOST everything else got built).

There are a few ways to avoid the CDash problem.  One way is to not submit the failing build results to CDash and only submit the rebuild results.  The other issue is reporting the time taking to complete the build.  We could work with Kitware to improve the handling of rerunning the builds and rerunning the tests to improve this. But for now, just reporting everything but allowing it to pass is "better" than what is happening now.

**Comment by sebrowne** [comment]
@cgcgcg @rppawlo @mperego @ccober6 how do we feel about this technical approach?  Is this something we want to discuss at the next Operational Leaders meeting?  Time/effort required to implement the behavior of "if build failed, retry with fewer processors" is very low.  Outcome would be getting around resource issues with the build (anecdotally), but CDash would still show the errors (even if the retry worked).

**Comment by ccober6** [comment]
Let's see if we can handle this via comments on this issue.  I am generally in favor of doing this.  One question I have is would it be fairly easy way to see if it was retried?  If someone is doing postmortem on the build, will it be hard to tell what happened?
