### ISSUE TITLE
Tpetra: cmake logic for detecting GPU-aware MPI only works for OpenMPI variants

### ISSUE THREAD

**Issue by jhux2** [trilinos/Trilinos#12468]
## Bug Report
The Tpetra Cmake logic for setting `Tpetra_ASSUME_GPU_AWARE_MPI` assumes the existence of `ompi_info`.  The latter is specific to OpenMPI.

### Description
Frontier uses an MPICH variant. Tpetra incorrectly sets `Tpetra_ASSUME_GPU_AWARE_MPI` to false (if the option isn't explicitly set on the commmand line).

**Comment by jhux2** [comment]
Are there currently GPU architectures where the MPI is _not_ GPU aware?

Should the default be to assume GPU-aware MPI?

**Comment by jhux2** [comment]
I assume we'd need to deprecate this?

**Comment by jhux2** [comment]
Will the merge of #12517, Tpetra now defaults to assuming that MPI is GPU aware.

If an application is using an MPI that isn't GPU aware, the app should either configure Trilinos with

`-DTpetra_ASSUME_GPU_AWARE_MPI:BOOL=FALSE`

or at run time set the environment variable

`export TPETRA_ASSUME_GPU_AWARE_MPI=0`.

**Comment by rppawlo** [comment]
Just a heads up. This change caused a lot of testing failures inside sandia. The internal cuda test machines don't seem to have cuda aware mpi installed. The failures are seg faults with no real info, so it is not easy to debug. You might want to send out an email to the trilinos lists mentioning this change.
