### ISSUE TITLE
MueLu: Coupled aggregation is still listed as an option

### ISSUE THREAD

**Issue by GrahamBenHarper** [trilinos/Trilinos#12477]
## Bug Report
The option for coupled aggregation ("aggregation: type" = "coupled") is still listed in a few places like documentation, despite being removed in #11687

**Comment by GrahamBenHarper** [comment]
Fixed by #10633

**Comment by cgcgcg** [comment]
Didn't we have to keep some remainders of coupled to deal with brick agg?

**Comment by GrahamBenHarper** [comment]
Good question. I can tell you now based on independent testing and based on the test results in #10633, specifying "aggregation: type" = "coupled" results in an error `MueLu::FactoryFactory: unknown factory name : CoupledAggregationFactory`, and there are no xml-based tests which specify "aggregation: type" = "coupled", so it makes sense to remove this option from the master list (which is what I did https://github.com/trilinos/Trilinos/pull/10633/commits/0b370c5342b019afb692158c35f4a9d933e486ad)

**Comment by cgcgcg** [comment]
After looking at the code, here is what the situation is: we can indeed fully purge "coupled", but we cannot remove the "AggregatesCrossProcessors" thing because brick aggregation uses that.

**Comment by GrahamBenHarper** [comment]
Thanks @cgcgcg ! I'm glad you checked since I bundled it into the tutorial PR
