### ISSUE TITLE
Framework: results from RHEL7 CUDA 11.4.2 testing aren't being reported on the dashboard

### ISSUE THREAD

**Issue by jhux2** [trilinos/Trilinos#12498]
## Bug Report
@trilinos/framework @sebrowne  On PRs #12491 and #12493, the same build is failing: `rhel7_sems-cuda-11.4.2-sems-gnu-10.1.0-sems-openmpi-4.0.5_release_static_Volta70_no-asan_complex_no-fpic_mpi_pt_no-rdc_no-uvm_deprecated-on_no-package-enables`.  If there are results, I don't see them on the dashboard.

**Comment by jhux2** [comment]
Same story for #12058.

**Comment by sebrowne** [comment]
Spot-checked those and the Jenkins job timed out near the end of the testing phase (at 10hrs).  This is starting to happen more frequently (anecdotally).  That is a pretty long time.  And almost all of it was in the tests, I confirmed they started at 08:17 on one build, and it timed out at about 18:10.  Will consider increasing the timeout to 12hr for now, but this is a good argument to continue work on #11391 to make better use of the GPUs for testing.

**Comment by cgcgcg** [comment]
Can you see if some particular tests are taking a long time? Or are the tests pretty much slow across the board?

**Comment by sebrowne** [comment]
Looks across-the-board-ish.  Meaning, almost every test took more than 60s.  This may have to do with how the machine is running tests (which is actually what #11391 addresses).  Difficult to tell if there is a within-the-code reason that the tests are taking so long, but my gut feeling is no, this has to do with how we're using the CPUs and GPUs on those machines.

**Comment by sebrowne** [comment]
Hit #12509

**Comment by kliegeois** [comment]
And #12542

**Comment by jhux2** [comment]
More general question -- some PRs are getting tested repeatedly, whereas others languish with little to none.  I'm curious if anyone knows why this is.  Bad luck, design, something else?

Example of a PR with 4 rounds of testing, submitted 2 days ago: #12532.
Example of a PR with 2 rounds of testing, submitted 3 days ago:  #12529.
Example of PR with no testing, submitted 2 days ago: #12533.

**Comment by jhux2** [comment]
> More general question -- some PRs are getting tested repeatedly, whereas others languish with little to none. I'm curious if anyone knows why this is. Bad luck, design, something else?
> 
> Example of a PR with 4 rounds of testing, submitted 2 days ago: #12532. Example of a PR with 2 rounds of testing, submitted 3 days ago: #12529. Example of PR with no testing, submitted 2 days ago: #12533.

@csiefer2 mentioned that there are two (possibly more) AT lanes, and which lane a PR is assigned to is a function of the PR number itself.

**Comment by ndellingwood** [comment]
Hit by this with #12505 , https://github.com/trilinos/Trilinos/pull/12505#issuecomment-1817954031

**Comment by sebrowne** [comment]
Hit #12551 

I'm going to increase the timeout on the CUDA job as a temporary workaround, hopefully granting it another 1-2 hours will alleviate this a little bit in the short term.

**Comment by sebrowne** [comment]
> More general question -- some PRs are getting tested repeatedly, whereas others languish with little to none. I'm curious if anyone knows why this is. Bad luck, design, something else?
> 
> Example of a PR with 4 rounds of testing, submitted 2 days ago: #12532. Example of a PR with 2 rounds of testing, submitted 3 days ago: #12529. Example of PR with no testing, submitted 2 days ago: #12533.

I believe the autotester was a bit crashy late last week, which can cause the behavior you're describing (it loses track of a set of tests, and re-tests the same PR).

**Comment by jhux2** [comment]
I think this can be closed as fixed.
