### ISSUE TITLE
MPI_Iallreduce issues

### ISSUE THREAD

**Issue by tjfulle** [trilinos/Trilinos#1249]
@mhoemmen and I thought it might warrant opening an issue regarding a problem I am having with `MPI_Iallreduce` getting a pipelined CG implementation working in Lammps.  It may be relevant to non-blocking algorithms planned for @trlinos/tpetra.  @nmhamster and @crtrott, perhaps you can see the problem?

I have run in to an issue with `openmpi` (version 1.8.7, 1.10.1, 2.0.1) `+gcc6` (and clang) where using `MPI_Iallreduce` to compute a parallel dot product followed by `MPI_Wait` gives different (wrong) answers than a dot product implemented with `MPI_Allreduce`.  The following code fails:

```c
#include <mpi.h>
#include <iostream>

int IDotProduct(double& res, double* a, double* b, int n, MPI_Request* request)
{
  res = 0.;
  double ldot = 0.;
  for(int i=0; i<n; i++) ldot += (a[i] * b[i]);
  return MPI_Iallreduce(&ldot, &res, 1, MPI_DOUBLE, MPI_SUM, MPI_COMM_WORLD, request);
}

int main(int argc, char** argv)
{
  MPI_Init(&argc, &argv);
  int world_rank;
  MPI_Comm_rank(MPI_COMM_WORLD, &world_rank);
  int world_size;
  MPI_Comm_size(MPI_COMM_WORLD, &world_size);

  double a[] = {1.};
  double gdot = 0;
  MPI_Request request;
  IDotProduct(gdot, a, a, 1, &request);
  MPI_Wait(&request, MPI_STATUS_IGNORE);
  double expected = static_cast<double>(world_size);
  if (gdot != expected) {
    std::cerr << "Expected dot product to be " << expected
              << " but got " << gdot << std::endl;
  }
  MPI_Finalize();
  return 0;
}
```

Strangely, the code passes if the call to `MPI_Wait` is moved in to the `IDotProduct` function:

```c
int IDotProduct(double& res, double* a, double* b, int n, MPI_Request* request)
{
  res = 0.;
  double ldot = 0.;
  for(int i=0; i<n; i++) ldot += (a[i] * b[i]);
  MPI_Iallreduce(&ldot, &res, 1, MPI_DOUBLE, MPI_SUM, MPI_COMM_WORLD, request);
  MPI_Wait(request, MPI_STATUS_IGNORE);
  return 0;
}
```

Perhaps even more strange is that the code also passes if the call to `MPI_Wait` is moved in to the `IDotProduct` function as:

```c
int IDotProduct(double& res, double* a, double* b, int n, MPI_Request* request)
{
  if(n<0) {
    MPI_Wait(request, MPI_STATUS_IGNORE);
    return 0;
  }
  res = 0.;
  double ldot = 0.;
  for(int i=0; i<n; i++) ldot += (a[i] * b[i]);
  return MPI_Iallreduce(&ldot, &res, 1, MPI_DOUBLE, MPI_SUM, MPI_COMM_WORLD, request);
}
```

In this case, the caller would call `IDotProduct` twice: once with `n>0` to compute the dot product and again with `n<0` to perform the `MPI_Wait`.

I'm at a loss as to why the last two cases work but not the first.  The original code passes with `mpich+intel`.

**Comment by vbrunini** [comment]
Is MPI_Iallreduce guaranteed to copy the local send buffer? You are giving it &ldot which is local to IDotProduct. If it doesn't copy the local buffer I believe you have undefined behavior which could explain the compiler differences.

**Comment by mhoemmen** [comment]
@vbrunini That's a good point!  I didn't think of that when I looked at @tjfulle 's code earlier.  @tjfulle was not reusing the _output_ buffer, but the _input_ (local dot product result) buffer was a stack variable.

**Comment by tjfulle** [comment]
@vbrunini, yes, a very good point!  That fixes this simple problem.  Hopefully it fixes the issue in the larger code...
