### ISSUE TITLE
MueLu: MueLu_MasterList_MPI_1 failure with MacOS - local environment issue?

### ISSUE THREAD

**Issue by ndellingwood** [trilinos/Trilinos#12500]
## Question
@trilinos/muelu @csiefer2 @cgcgcg @GrahamBenHarper 

In a build of Trilinos on my Mac (using MacPorts for compilers) I have failures with `MueLu_MasterList_MPI_1` as follows:

```
    Start 885: MueLu_MasterList_MPI_1
1/1 Test #885: MueLu_MasterList_MPI_1 ...........***Failed    4.32 sec
sed: 1: "MueLu_MasterList.cpp": invalid command code M
sed: 1: "MueLu_MasterList.cpp": invalid command code M
...
569c569
<             "<Parameter name=\"multigrid algorithm\" type=\"string\" value=\""pg"\"/>"
---
>             "<Parameter name=\"multigrid algorithm\" type=\"string\" value=\"pg\"/>"
MueLu_MasterList.cpp does not match
Do not edit MueLu_MasterList.cpp directly, but edit masterList.xml and run update_params.sh
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpiexec detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[1775,1],0] 
  Exit code:    1
--------------------------------------------------------------------------


0% tests passed, 1 tests failed out of 1

Subproject Time Summary:
MueLu    =   4.32 sec*proc (1 test)

Total Test time (real) =  20.39 sec

The following tests FAILED:
  885 - MueLu_MasterList_MPI_1 (Failed)
```

Is my version of sed incompatible with the test?

From my sed man page:
```
...
HISTORY
     A sed command, written by L. E. McMahon, appeared in Version 7 AT&T UNIX.

AUTHORS
     Diomidis D. Spinellis <dds@FreeBSD.org>

BUGS
     Multibyte characters containing a byte with value 0x5C (ASCII ‘\’) may be incorrectly treated as line continuation characters in arguments to the
     “a”, “c” and “i” commands.  Multibyte characters cannot be used as delimiters with the “s” and “y” commands.

macOS 12.7                                                            June 10, 2020                                                            macOS 12.7
```

Thanks

**Comment by cgcgcg** [comment]
Could this be an encoding issue?

**Comment by ndellingwood** [comment]
> Could this be an encoding issue?

@cgcgcg could you explain a bit more (I'm not sure how to tell)? Is there something I can test further to help triage?

**Comment by ndellingwood** [comment]
Apple (FreeBSD) sed does behave a bit different than Linux (GNU) sed, in case that is helpful

**Comment by cgcgcg** [comment]
The test is reading some xml files that we have and generates a cpp file with default parameters. We check that this generated file matches the one that we keep in the repo. This is to make sure that no discrepancies between xml and cpp were introduced. Somehow we get a minor diff on Mac.

**Comment by ndellingwood** [comment]
@cgcgcg is this relevant regarding sed? https://stackoverflow.com/a/19457213

**Comment by GrahamBenHarper** [comment]
HI @ndellingwood, I think you're onto something. We do have some checks for Apple's (BSD) sed in MueLu, but maybe it is not sufficient now. In particular, here are some comments from Andrey in 2014.
https://github.com/trilinos/Trilinos/blob/1767fbf9a3b6426941f5ab87efd9990c3a43e5ca/packages/muelu/test/interface/ParameterListInterpreter.cpp#L439-L446

So we are running `sed -i "" "..." FILE` in at least a few places. However, we do not call it in `update_params.sh`, which is probably exactly what causes your issue. Can you check if adding the "" after both `sed -i` in `packages/muelu/doc/UsersGuide/update_params.sh` fixes it for Apple?
https://github.com/trilinos/Trilinos/blob/1767fbf9a3b6426941f5ab87efd9990c3a43e5ca/packages/muelu/doc/UsersGuide/update_params.sh#L176-L178

**Comment by ndellingwood** [comment]
@GrahamBenHarper that change to update_params.sh resolved the failure 👍

**Comment by GrahamBenHarper** [comment]
@ndellingwood does the merged pr on develop fix the issue you were seeing?

**Comment by ndellingwood** [comment]
@GrahamBenHarper thanks for putting in the PR! I'll rebuild and test with it

**Comment by ndellingwood** [comment]
Test is now passing on my Mac, thanks!
