### ISSUE TITLE
Trilinos, Tpetra, Kokkos and OpenMP

### ISSUE THREAD

**Issue by dridzal** [trilinos/Trilinos#12508]
## Question

Are there examples of Trilinos configure options, and RHEL environment options, for the Tpetra/Kokkos linear algebra stack on a **single MPI rank** with **OpenMP**?  The CPU is dual socket Intel Xeon.
@trilinos/tpetra
@trilinos/kokkos 
@trilinos/framework
@trilinos/kokkos-kernels

**Comment by jhux2** [comment]
@dridzal Have you tried `-DTrilinos_ENABLE_OpenMP:BOOL=ON`?

**Comment by dridzal** [comment]
@jhux2 I haven't tried anything yet, I'm just getting started.  I can try the options you mentioned.  Will it grab all threads by default, or do I have to set some Kokkos env variables?

**Comment by jhux2** [comment]
@dridzal That I don't know.
