### ISSUE TITLE
Ifpack2: Ifpack2_ILUTSingleProcessUnitTests_MPI_1 test fails on MI100

### ISSUE THREAD

**Issue by jwillenbring** [trilinos/Trilinos#12510]
@trilinos/ifpack2 

This failure was found on the U Oregon Frank cluster, building Trilinos through Spack. Here is the test output:

227/416 Test #1260: Ifpack2_ILUTSingleProcessUnitTests_MPI_1 ..................................***Failed  Required regular expression not found. Regex=[End Result: TEST PASSED
]  1.02 sec
Teuchos::GlobalMPISession::GlobalMPISession(): started processor with name runner-dp7khezpw-project-21-concurrent-0 and rank 0!

***
*** Unit test suite ...
***

Sorting tests by group name then by the order they were added ... (time = 7.26e-06)

Running unit tests ...

0. Ifpack2ILUT_double_int_longlong_ParILUT_UnitTest ...
 A = Teuchos::RCP<Tpetra::CrsMatrix<double, int, long long, Tpetra::KokkosCompat::KokkosDeviceWrapperNode<Kokkos::HIP, Kokkos::HIPSpace> > >{ptr=0x1de1c80,node=0x26c8260,strong_count=2,weak_count=0} != Teuchos::null = 0 : passed
 Test that code {prec.setParameters (params);} throws std::runtime_error: passed

 Exception message for expected exception:

  /Trilinos/packages/ifpack2/src/Ifpack2_ILUT_def.hpp:206:

  Throw number = 1

  Throw test that evaluated to true: (params.isParameter(paramName) && this->useKokkosKernelsParILUT_)

  Ifpack2::ILUT: Parameter fact: ilut level-of-fill is meaningless for algorithm par_ilut.

 Test that code {prec.setParameters (params);} does not throw : passed
 prec.initialize()
 prec.compute()
 before solve, |xact|: : 17.0743, 17.2522
 |e|        = [0.0132799, 0.303919]
 |b|        = [75.5637, 77.2754]
 |b-Ax|     = [15.1966, 14.3735]
 |b-Ax|/|b| = [0.20111, 0.186004]
 norms(0) = 15.1966 < 0.2 * bnorms(0) = 15.1127 : FAILED ==> /Trilinos/packages/ifpack2/test/unit_tests/Ifpack2_UnitTestSingleProcessILUT.cpp:248
 norms(1) = 14.3735 < 0.25 * bnorms(1) = 19.3188 : passed
 [FAILED]  (0.589 sec) Ifpack2ILUT_double_int_longlong_ParILUT_UnitTest
 Location: /Trilinos/packages/ifpack2/test/unit_tests/Ifpack2_UnitTestSingleProcessILUT.cpp:81

The following tests FAILED:
    0. Ifpack2ILUT_double_int_longlong_ParILUT_UnitTest ...

Total Time: 0.589 sec

Summary: total = 1, run = 1, passed = 0, failed = 1

End Result: TEST FAILED

We are working on getting this build set up (all passing), and also in figuring out what output is most helpful for debugging.

**Comment by cgcgcg** [comment]
@jhux2 ?

**Comment by jhux2** [comment]
@jwillenbring Can you provide an equivalent cmake recipe?

**Comment by jhux2** [comment]
@jwillenbring I'm loosening this test tolerance.  If you have a chance, can you try the branch to see if it fixes the problem?
