### ISSUE TITLE
Tpetra: Add "scope guard" wrapper for Kokkos Profiling regions

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#1252]
@trilinos/tpetra

**Comment by mhoemmen** [comment]
Fixed in develop.

**Comment by vbrunini** [comment]
Thoughts on getting this moved into Kokkos? I imagine a lot of people will end up writing their own if it isn't in Kokkos.

**Comment by crtrott** [comment]
Is that something you want? A small class as an automatic pop region scope guard?

**Comment by vbrunini** [comment]
Yeah that would be great.

**Comment by mhoemmen** [comment]
Hi @crtrott !  It's true that this could be more generally useful, but the main point of the class in Tpetra was encapsulation.  See #1256 (just closed).
