### ISSUE TITLE
Trilinos compilaton failed while building libteko.so

### ISSUE THREAD

**Issue by ajithperera** [trilinos/Trilinos#12534]
Hello: I am trying to build deal-II (https://github.com/dealii/dealii) software using the package manager candi(https://github.com/dealii/candi). Installing Trilinos (a dependent) (with gcc/12.2.0 and openmpi/4.1.5) fails while the shared library libteako.so is being built.  

I see multiple error messages like 
defaults()':
/apps/gcc/12.2.0/openmpi/4.1.5/dealii/9.5.1/tmp/unpack/Trilinos-trilinos-release-14-4-0/packages/stratimikos/src/Stratimikos_LinearSolverBuilder_def.hpp:559: multiple definition of `Stratimikos::LinearSolverBuilder<double>::initialize Defaults()'
CMakeFiles/teko.dir/NS/Teko_InvLSCStrategy.cpp.o:/apps/gcc/12.2.0/openmpi/4.1.5/dealii/9.5.1/tmp/unpack/Trilinos-trilinos-release-14-4-0/packages/stratimikos/src/Stratimikos_LinearSolverBuilder_def.hpp:559: first defined here CMakeFiles/teko.dir/NS/Teko_LSCPreconditionerFactory.cpp.o: In function `Stratimikos::LinearSolverBuilder<double>::initializeDefaults()':

Any help to get over this error is very much appreciated. 

Regards, Ajith Perera, Uni. Florida

**Comment by cgcgcg** [comment]
Could you post the CMake configure line and the CMake terminal output? It could also be helpful to post more of the error message.

**Comment by ajithperera** [comment]
I am attach

**Comment by ajithperera** [comment]
I am attaching the configure and build log files. 
[candi_build.log](https://github.com/trilinos/Trilinos/files/13370277/candi_build.log)
[candi_configure.log](https://github.com/trilinos/Trilinos/files/13370279/candi_configure.log)

**Comment by cgcgcg** [comment]
Please also post the CMake arguments that are used to configure Trilinos.

**Comment by ajithperera** [comment]
Thanks. Here are they. I added the .txt so that the files can be seen to attach (I should have done that in the first place and sent you all four files at once). 

[candi_configure.txt](https://github.com/trilinos/Trilinos/files/13370605/candi_configure.txt)
[candi_build.txt](https://github.com/trilinos/Trilinos/files/13370606/candi_build.txt)

**Comment by cgcgcg** [comment]
Just a hunch: can you try `Trilinos_ENABLE_EXPLICIT_INSTANTIATION=ON`?

**Comment by ajithperera** [comment]
Absolutely. I will do it tomorrow and let you know.

**Comment by GrahamBenHarper** [comment]
candi seems to specify `-D Trilinos_ENABLE_EXPLICIT_INSTANTIATION=OFF \`, (see https://github.com/dealii/candi/blob/master/deal.II-toolchain/packages/trilinos.package#L238).

I see @tjhei has a comment about it here https://github.com/dealii/candi/commit/9473b329b784faab06efb4953cebad40f147116c, but I'm unsure how that interacts with Trilinos. I think in general we utilize Trilinos with explicit instantiation on.

**Comment by ajithperera** [comment]
Thank you. Trilinos_ENABLE_EXPLICIT_INSTANTIATION=ON resolved the problem and trilinos 14.4.0 installation went to completion. I had difficulties getting trillions installed via candi, but not independently.  I presume that this is the default internally.  Thank you for addressing this issue promptly. It is very much appreciated!
