### ISSUE TITLE
Tpetra::Details::packCrsMatrix test should actually test pack results

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#1253]
@trilinos/tpetra 

Tpetra::Details::packCrsMatrix test should actually test pack results, not just whether packing didn't throw an exception.

**Comment by mhoemmen** [comment]
Fixed in develop.

**Comment by mhoemmen** [comment]
oops, closed wrong issue :)

**Comment by tjfulle** [comment]
Notes from conversation about this issue and future thread parallel global assembly:

- Separate out unpackCrsMatrix.
- Use the new unpackCrsMatrix to test packCrsMatrix.
- Finish fixing #1253 using (2).

**Comment by tjfulle** [comment]
Just opened a PR to close this issue.  Running `sems-checkin-script.sh` now.

**Comment by mhoemmen** [comment]
@tjfulle I finished squashing the commits and am running downstream tests now.  Two Stokhos tests fail for me; I'm just checking now whether those were failing before.

**Comment by mhoemmen** [comment]
Just pushed!  Thanks @tjfulle ! :-D
