### ISSUE TITLE
Add TPLs for Amesos2 in Nightly Builds

### ISSUE THREAD

**Issue by srajama1** [trilinos/Trilinos#1255]
We need to add SuperLU-Dist, SuperLU and UMFPACK as part of nightly tests.

@jwillenbring @krcb @MicheldeMessieres @trilinos/framework

**Comment by krcb** [comment]
The Amesos2 Umfpack interface was tested with UMFPACK V5.7.6 (May 4, 2016)

**Comment by krcb** [comment]
There are a set of issues for SuperLU version support, e.g. #379, #411, #563 that could be reviewed as part of this and from that we could determine which version(s) of SuperLU will be supported (taking into account customer requirements, etc.).

**Comment by krcb** [comment]
SuperLU-Dist: again, there's a question of which version, 4 or 5?

**Comment by ibaned** [comment]
Unlike SuperLU, SuperLU-Dist version 5 seems to be compatible with the latest Trilinos, so I recommend you use that.

**Comment by srajama1** [comment]
SuperLU-Dist : Let us use 5.

SuperLU - There is PR for 5 waiting to be integrated and haven't been tested. May be we can merge it and add 5 there as well.

UMFPACK 5.7.6 is good.

**Comment by srajama1** [comment]
@jwillenbring : Pinging to see what are your thoughts on this.

**Comment by srajama1** [comment]
@jwillenbring : Pinging to see your thoughts on this.

**Comment by jwillenbring** [comment]
It appears that SuperLu is available on the SEMS NFS mount, and SuperLU_Dist and UMFPACK are not available. Is this consistent with your experience? Is SuperLU 4.3 an acceptable version?

**Comment by srajama1** [comment]
We have added support for SuperLU 5, but any testing is better than no testing. We can start with SuperLU 4.3 first.

**Comment by bartlettroscoe** [comment]
SuperLU 4.3 is already part of the standard CI build of Amesos2 and has been for many months  You can see this, for example, this morning on CDash at:

* https://testing.sandia.gov/cdash/viewConfigure.php?buildid=2939094

which shows:

```
-- Setting Amesos2_ENABLE_SuperLU=ON since TPL_ENABLE_SuperLU=ON
[...]
Final set of enabled TPLs:  yaml-cpp Pthread MPI BLAS LAPACK Boost ParMETIS Zlib HDF5 Netcdf SuperLU BoostLib DLlib 13
[...]
Processing enabled TPL: SuperLU (enabled explicitly, disable with -DTPL_ENABLE_SuperLU=OFF)
-- SuperLU_LIBRARY_NAMES='superlu;lapack;blas'
-- TPL_SuperLU_LIBRARIES='/projects/sems/install/rhel6-x86_64/sems/tpl/superlu/4.3/gcc/4.9.3/base/lib/libsuperlu.a;/usr/lib64/liblapack.so;/usr/lib64/libblas.so'
-- TPL_SuperLU_INCLUDE_DIRS='/projects/sems/install/rhel6-x86_64/sems/tpl/superlu/4.3/gcc/4.9.3/base/include'
```

I set that up a long time ago as part of #482 and its supporting stories.

Therefore, Amesos2 with SuperLU 4.3 gets tested pre-push by everyone using the checkin-test-sems.sh script.

**Comment by srajama1** [comment]
Can you remind me how this works ? If it is part of CI build, is it also part of a nightly build where we have the commitment to maintain it clean ?

**Comment by bartlettroscoe** [comment]
> Can you remind me how this works ? If it is part of CI build, is it also part of a nightly build where we have the commitment to maintain it clean ?

How it works is described in detail in:

* https://github.com/trilinos/Trilinos/wiki/SEMS-Dev-Env

If the Trilinos Framework team were to take advantage of this system, then then this would be automated in all SEMS-based nightly builds.

**Comment by srajama1** [comment]
Ok, this might be a stupid question after reading it. It appears we don't use the SEMS-Dev-Env for nightlies, so SuperLU is not tested. Is that correct ?

**Comment by jwillenbring** [comment]
>SuperLU-Dist : Let us use 5.
>SuperLU - There is PR for 5 waiting to be integrated and haven't been tested. May be we can merge it and add 5 there as well.
>UMFPACK 5.7.6 is good.

A request for these versions has been submitted as SEMS help desk ticket 558. If SEMS is unable to help, we will need to add them to a project space on the NFS mount.

**Comment by jwillenbring** [comment]
@srajama1 As previously discussed, SEMS is also planning to take a broader look at TPL support after your recent mention of this topic. 

A preliminary questions from SEMS and @bmpersc is if you plan to continue to support SuperLU 4.3 in addition to 5.

**Comment by srajama1** [comment]
@jwillenbring : Thanks a lot !

**Comment by srajama1** [comment]
Checking to see the status of this. There is another issue #1782 that is similar as well.

**Comment by bmpersc** [comment]
@srajama1 The @trilinos/framework team just had a discussion about this and we decided that all of these TPLS are reasonable for us to provide. The question is will SEMS be willing to support some or all or will Trilinos need to do that. I will have a conversation with @dmvigi to see what SEMS is willing to do. After that we will have a much better idea of when these will be available.

**Comment by srajama1** [comment]
Checking to see the results of this conversation with @dmvigi

**Comment by bmpersc** [comment]
@srajama1, the gist was that SEMS would be willing to support discussed TPLs so long as they weren't "hard" to build. Basically anything that would require changing files or fixing issues on the platforms would be a hard stop for SEMS. However, I don't believe that will be a big issue, but it does remain to be seen. 

I haven't had a chance to dig into them yet to see if there are issues, but I should be able to get to it this week.

**Comment by srajama1** [comment]
Thanks ! None of these TPLs are hard to build to my knowledge.

**Comment by ndellingwood** [comment]
For reference, if SuperLU 5.0 or 5.1 gets added to testing and ML is enabled as well the following configure option will be needed as ML does not support SuperLU 5.x:
`ML_ENABLE_SuperLU:BOOL=OFF`

**Comment by srajama1** [comment]
@bmpersc : Ping

@jwillenbring

**Comment by srajama1** [comment]
Ping again ... after more than an year

**Comment by ndellingwood** [comment]
Adding as reference #3508 for superlu_dist TPL testing needed.

**Comment by jwillenbring** [comment]
@srajama1 @ndellingwood I just got an update from SEMS on the status of these requests. SuperLU, SuperLU_dist and metis/parmetis have been installed, we just need to add them to one or more builds. The current holdup for installation was with Suite Sparse. I will follow up separately on this.

**Comment by srajama1** [comment]
Just to have some activity.

**Comment by jwillenbring** [comment]
@srajama1 So I looked at the status of this. We did add superlu_dist not too long ago, and we had superlu testing. The missing piece is UMFPACK. I did confirm that UMFPACK is not part of the current spack-cm offering. Is there a specific version of UMFPACK that would be most relevant? Should we take the Spack default? Also, I followed up, and if we need multiple versions of TPLs, the team suggested trying to get a full list and let spack run with installing everything it could and test them in a batch instead of individually.

**Comment by srajama1** [comment]
@jwillenbring Is there a build with SuperLU and SuperLU-Dist?

I doubt configuring Trilinos with multiple version of same TPL would work. Cmake detects one version in the current FindTPL logic in TriBITS. After that we use the macro in our code like the following

#ifdef TPLv1
// ...
#elseif TPLv2 
// ..
#endif 

I am almost sure if there are many versions we would need separate builds. Please see here.

https://github.com/trilinos/Trilinos/blob/master/cmake/TPLs/FindTPLUMFPACK.cmake

We do nbot support more than version 5, but we can add if needed.

**Comment by jwillenbring** [comment]
@srajama1 Sorry I was unclear. There are separate builds with superlu and superlu_dist. To my knowledge, they cannot be both used in a single build. Also, for the multiple version testing I was saying we could potentially configure different builds to test different versions. For example, a clang bulid of Trilinos could test one version of a TPL, while a gcc build could test a different version. 

So is there a specific version of UMFPACK you would like us to test, or just anything 5 or less?
