### ISSUE TITLE
Teuchos::ParameterList::get() with default value

### ISSUE THREAD

**Issue by jmgate** [trilinos/Trilinos#1257]
Any time I try using `ParameterList`'s `get` routine that allows you to specify a default value in case the parameter isn't found, I can never actually get it to work.  The compiler tells me

```
...
error: no matching function for call to 'Teuchos::ParameterList::get(const char [15], int) const'
       double contactLength(data.get<double>("Contact Length", 1)),
                                                                ^
...
note: candidate: T& Teuchos::ParameterList::get(const string&, T) [with T = double; std::__cxx11::string = std::__cxx11::basic_string<char>] <near match>
...
```

I've tried switching the parameter name from a string constant to an actual string, but then I just get the same problem with a slightly different error message.  What am I missing here?

Many thanks.

@trilinos/teuchos

**Comment by rppawlo** [comment]
remove the type specification on the get call. It is deduced from the default value.

double contactLength(data.get("Contact Length", 1.0))

**Comment by jmgate** [comment]
I'm afraid that didn't do the trick.

```
/build/Packages/Trilinos/tcad-charon/driver/Charon_Main.cpp: In function ‘void getCurrentConstraintBCs(const Teuchos::ParameterList&, charon::
CurrentConstraintList&)’:
/build/Packages/Trilinos/tcad-charon/driver/Charon_Main.cpp:812:58: error: no matching function for call to ‘Teuchos::ParameterList::get(const
 char [15], double) const’
       double contactLength(data.get("Contact Length", 1.0)),
                                                          ^
In file included from /build/Packages/Trilinos/packages/teuchos/comm/src/Teuchos_TimeMonitor.hpp:68:0,
                 from /build/Packages/Trilinos/packages/teuchos/comm/src/Teuchos_CommUtilities.hpp:45,
                 from /build/Packages/Trilinos/packages/teuchos/comm/src/Teuchos_CommHelpers.hpp:46,
                 from /build/Packages/Trilinos/packages/teuchos/kokkoscomm/src/Kokkos_TeuchosCommAdapters.hpp:47,
                 from /build/Packages/Trilinos/packages/sacado/src/KokkosExp_View_Fad.hpp:1088,
                 from /build/Packages/Trilinos/packages/sacado/src/Sacado_Fad_ScalarTraitsImp.hpp:627,
                 from /build/Packages/Trilinos/packages/sacado/src/Sacado_Fad_DFadTraits.hpp:144,
                 from /build/Packages/Trilinos/packages/sacado/src/Sacado.hpp:51,
                 from /build/Packages/Trilinos/packages/panzer/disc-fe/src/Panzer_Traits.hpp:56,
                 from /build/Packages/Trilinos/tcad-charon/src/bc_strategies/Charon_BCStrategy_Factory.hpp:20,
                 from /build/Packages/Trilinos/tcad-charon/driver/Charon_Main.cpp:33:
/build/Packages/Trilinos/packages/teuchos/parameterlist/src/Teuchos_ParameterList.hpp:900:4: note: candidate: T& Teuchos::ParameterList::get(const string&, T) [with T = double; std::__cxx11::string = std::__cxx11::basic_string<char>] <near match>
 T& ParameterList::get(const std::string& name_in, T def_value)
    ^~~~~~~~~~~~~
/build/Packages/Trilinos/packages/teuchos/parameterlist/src/Teuchos_ParameterList.hpp:900:4: note:   passing ‘const Teuchos::ParameterList*’ as ‘this’ argument discards qualifiers
/build/Packages/Trilinos/packages/teuchos/parameterlist/src/Teuchos_ParameterList.hpp:915:14: note: candidate: std::__cxx11::string& Teuchos::ParameterList::get(const string&, char*)
 std::string& ParameterList::get(const std::string& name_in, char def_value[])
              ^~~~~~~~~~~~~
/build/Packages/Trilinos/packages/teuchos/parameterlist/src/Teuchos_ParameterList.hpp:915:14: note:   no known conversion for argument 2 from ‘double’ to ‘char*’
/build/Packages/Trilinos/packages/teuchos/parameterlist/src/Teuchos_ParameterList.hpp:920:14: note: candidate: std::__cxx11::string& Teuchos::ParameterList::get(const string&, const char*)
 std::string& ParameterList::get(const std::string& name_in, const char def_value[])
              ^~~~~~~~~~~~~
/build/Packages/Trilinos/packages/teuchos/parameterlist/src/Teuchos_ParameterList.hpp:920:14: note:   no known conversion for argument 2 from ‘double’ to ‘const char*’
/build/Packages/Trilinos/packages/teuchos/parameterlist/src/Teuchos_ParameterList.hpp:925:4: note: candidate: template<class T> T& Teuchos::ParameterList::get(const string&)
 T& ParameterList::get(const std::string& name_in)
    ^~~~~~~~~~~~~
/build/Packages/Trilinos/packages/teuchos/parameterlist/src/Teuchos_ParameterList.hpp:925:4: note:   template argument deduction/substitution failed:
/build/Packages/Trilinos/tcad-charon/driver/Charon_Main.cpp:812:58: note:   candidate expects 1 argument, 2 provided
       double contactLength(data.get("Contact Length", 1.0)),
```

**Comment by rppawlo** [comment]
Is your parameter list const? I believe you need a non-const parameter list to set the default in it.

**Comment by ibaned** [comment]
I think @rppawlo is right about what the issue is. It annoys me that there isn't a `get(name, default)` that doesn't set the value in the parameter list, but instead just returns the default if the value isn't set.

**Comment by bartlettroscoe** [comment]
> Is your parameter list const? I believe you need a non-const parameter list to set the default in it.

Yup, that is the issue.  You can see this from the compile error message show [above](https://github.com/trilinos/Trilinos/issues/1257#issue-223188403) which showed:

```
error: no matching function for call to 'Teuchos::ParameterList::get(const char [15], int) const'
       double contactLength(data.get<double>("Contact Length", 1)),
                                                                ^
```

That `const` on the end shows that this function is getting called on a `const` PL object.

> I think @rppawlo is right about what the issue is. It annoys me that there isn't a get(name, default) that doesn't set the value in the parameter list, but instead just returns the default if the value isn't set.

But that function would never get called in correct software.  The proper usage of a PL is for the user to set a non-const PL and then the object will validate the list (which will set most defaults in the non-const PL) and then will grab out values.  If the validation does not set all of the defaults, then the object would set the default when it grabbed the value.  A const PL is almost never used in much of the code (or validation sets the defaults then the rest of the code works with a const PL but would never try to set the default at that point). 

What code is working with a const PL and yet still trying to set defaults?

**Comment by ibaned** [comment]
I guess I just picture a different usage where the user sets a non-const PL which then becomes a const PL, and subsequent code tries to grab values, but if they are not set by the user then it just returns the default without setting it. Having a separate validation pass is becoming harder in use cases when the list of valid parameters in one sublist depends on the contents of an earlier parameter, or even on simulation state that won't be known until after initialization. Anyway, with the current `get` implementation I guess keeping the PL non-const is easiest.

**Comment by jmgate** [comment]
Thanks for all the clarification everyone.  Closing&hellip;

**Comment by bartlettroscoe** [comment]
> I guess I just picture a different usage where the user sets a non-const PL which then becomes a const PL, and subsequent code tries to grab values, but if they are not set by the user then it just returns the default without setting it. Having a separate validation pass is becoming harder in use cases when the list of valid parameters in one sublist depends on the contents of an earlier parameter, or even on simulation state that won't be known until after initialization. Anyway, with the current get implementation I guess keeping the PL non-const is easiest.

Whether validation sets defaults or not is not the primary issue.  The primary issue is that if some algorithmic or solver object picks some value for PL parameter (because the user did not specify it), then that object should set that chosen value into the PL so that the user can see what that value is after the object is finished running.  That way, the user can see the value that got used and is better informed on how to tweak that value if needed/desired.  That seems very valuable when you have complex nested algorithms with upwards of 100+ parameters.  Otherwise, users are forced to search source code and open a debugger to figure out what parameter values are used in many cases.

Should we create a GitHub issue to clean up PL list usage and idioms in Trilinos?

**Comment by ibaned** [comment]
I guess the argument for informing the user makes sense.
> Should we create a GitHub issue to clean up PL list usage and idioms in Trilinos?
I don't yet see anything wrong in Trilinos, but I guess what this really means is we should make sure PLs are passed around non-const the vast majority of the time. I'll see if I can do that in the applications I'm concerned with.

**Comment by bartlettroscoe** [comment]
> I don't yet see anything wrong in Trilinos

I bet if we look, we will find many examples in Trilinos where a const PL is accepted and the values for missing PL params are never reported back to the user.
