### ISSUE TITLE
Tpetra: Incompatible view in cuda uvm build

### ISSUE THREAD

**Issue by jewatkins** [trilinos/Trilinos#12574]
## Bug Report
@trilinos/tpetra 

Our trilinos cuda uvm build started failing yesterday in Tpetra_Map:
```
/.../repos/Trilinos/packages/kokkos/core/src/Kokkos_View.hpp(1319): error: static assertion failed with "Incompatible View copy construction"
          detected during:
            instantiation of "Kokkos::View<DataType, Properties...>::View(const Kokkos::View<RT, RP...> &, std::enable_if_t<Kokkos::Impl::ViewMapping<Kokkos::View<DataType, Properties...>::traits, Kokkos::View<RT, RP...>::traits, Kokkos::ViewTraits<DataType, Properties...>::specialize>::is_assignable_data_type, void> *) [with DataType=const Tpetra::longlong *, Properties=<Kokkos::Device<Kokkos::CudaUVMSpace::execution_space, Kokkos::CudaUVMSpace::memory_space>>, RT=const Tpetra::longlong *, RP=<Kokkos::LayoutLeft, Kokkos::Device<Kokkos::CudaSpace::execution_space, Kokkos::CudaSpace::memory_space>>]" 
/.../repos/Trilinos/packages/tpetra/core/src/Tpetra_Map_def.hpp(1793): here
            instantiation of "Tpetra::Map<LocalOrdinal, GlobalOrdinal, Node>::global_indices_array_device_type Tpetra::Map<LocalOrdinal, GlobalOrdinal, Node>::getMyGlobalIndicesDevice() const [with LocalOrdinal=int, GlobalOrdinal=Tpetra::longlong, Node=Tpetra::Tpetra_KokkosCompat_KokkosCudaWrapperNode]" 
/.../repos/Trilinos/packages/tpetra/core/src/Tpetra_Map.cpp(56): here
```
The data types are not the same in the new Tpetra Map function here: https://github.com/trilinos/Trilinos/pull/12563. Here's another message with the dst, src types:
```
DstTraits=Kokkos::ViewTraits<const Tpetra::longlong *, Kokkos::Device<Kokkos::CudaUVMSpace::execution_space, Kokkos::CudaUVMSpace::memory_space>>, 
SrcTraits=Kokkos::ViewTraits<const Tpetra::longlong *, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::CudaSpace::execution_space, Kokkos::CudaSpace::memory_space>>
```
I think these are the conflicting types:
```
Kokkos::View<const global_ordinal_type*, device_type>
Kokkos::View<const global_ordinal_type*, Kokkos::LayoutLeft, no_uvm_device_type>
```
defined here:
https://github.com/trilinos/Trilinos/blob/develop/packages/tpetra/core/src/Tpetra_Map_decl.hpp#L768
https://github.com/trilinos/Trilinos/blob/develop/packages/tpetra/core/src/Tpetra_Map_decl.hpp#L1240

Cuda build works.

@ikalash @mperego @mcarlson801 @csiefer2

**Comment by cgcgcg** [comment]
@csiefer2 This looks like PR #12563.

**Comment by jhux2** [comment]
Stuff like this will occasionally slip through because we don't test with UVM enabled.

**Comment by sebrowne** [comment]
@ccober6 yes: https://trilinos-cdash.sandia.gov/index.php?project=Trilinos&filtercount=1&showfilters=1&field1=buildname&compare1=63&value1=%5C_uvm%5C_

But it appears to have been timing out for quite a while (the build).  I recall having to fix a perpetual compile hang in one file at some point in Stokhos, but I'm not positive it was the same build....

**Comment by jhux2** [comment]
> Note that it also enables RDC.
> 
> But it appears to have been timing out for quite a while (the build). I recall a perpetual compile hang in one file at some point in Stokhos, but I'm not positive it was the same build....

In case it's helpful, the last reported build was 8/18/2023.

**Comment by mperego** [comment]
I think so. @mcarlson801 please reopen if needed.
