### ISSUE TITLE
Catastrophic configure and build failures in Trilinos PR builds starting 2023-11-30

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#12571]
@sebrowne, @trilinos/framework 

As shown in [this query](https://trilinos-cdash.sandia.gov/index.php?project=Trilinos&begin=2023-11-01&end=2023-11-30&filtercount=2&showfilters=1&filtercombine=and&field1=groupname&compare1=61&value1=Pull%20Request&field2=buildname&compare2=63&value2=rhel7_sems-cuda-11.4.2-sems-gnu-10.1.0-sems-openmpi-4.0.5_release_static_Volta70_no-asan_complex_no-fpic_mpi_pt_no-rdc_no-uvm_deprecated-on_no-package-enables) the PR build:

* `rhel7_sems-cuda-11.4.2-sems-gnu-10.1.0-sems-openmpi-4.0.5_release_static_Volta70_no-asan_complex_no-fpic_mpi_pt_no-rdc_no-uvm_deprecated-on_no-package-enables`

started failing the configure in all PR builds since Build Start Time "2023-11-30 17:53:07" showing, for example:

```
Processing enabled external package/TPL: Netcdf (enabled explicitly, disable with -DTPL_ENABLE_Netcdf=OFF)
-- Netcdf_LIBRARY_NAMES='netcdf;pnetcdf;curl'
-- TPL_Netcdf_LIBRARIES='-L/projects/sems/install/rhel7-x86_64/sems/tpl/netcdf-c/4.8.1/gcc/10.1.0/openmpi/4.0.5/4k6fgkm/lib64;/projects/sems/install/rhel7-x86_64/sems/tpl/netcdf-c/4.8.1/gcc/10.1.0/openmpi/4.0.5/4k6fgkm/lib/libnetcdf.a;/projects/sems/install/rhel7-x86_64/sems/tpl/parallel-netcdf/1.12.2/gcc/10.1.0/openmpi/4.0.5/eo3ron2/lib/libpnetcdf.a;/projects/sems/install/rhel7-x86_64/sems/tpl/hdf5/1.10.7/gcc/10.1.0/openmpi/4.0.5/3lf3ds2/lib/libhdf5_hl.so;/projects/sems/install/rhel7-x86_64/sems/tpl/hdf5/1.10.7/gcc/10.1.0/openmpi/4.0.5/3lf3ds2/lib/libhdf5.a;/projects/sems/install/rhel7-x86_64/sems/v2/tpl/zlib/1.2.11/gcc/10.1.0/base/rywytxe/lib/libz.a;-ldl'
-- Searching for headers in Netcdf_INCLUDE_DIRS='/projects/sems/install/rhel7-x86_64/sems/tpl/netcdf-c/4.8.1/gcc/10.1.0/openmpi/4.0.5/4k6fgkm/include'
-- Searching for a header file in the set "netcdf.h":
--   Searching for header 'netcdf.h' ...
-- ERROR: Could not find a header file in the set "netcdf.h"
-- ERROR: Could not find the include directories for TPL 'Netcdf'!
-- TIP: If the TPL 'Netcdf' is on your system then you can set:
     -DNetcdf_INCLUDE_DIRS='<dir0>;<dir1>;...'
   to point to directories where these header files may be found.
   Or, just set:
     -DTPL_Netcdf_INCLUDE_DIRS='<dir0>;<dir1>;...'
   to point to the include directories which will bypass any search for
   header files and these include directories will be used without
   question in the build.  (But this will result in a build-time error
   obviously if the necessary header files are not found in these
   include directories.)
-- ERROR: Failed finding all of the parts of TPL 'Netcdf' (see above), Aborting!

-- TPL_Netcdf_PARALLEL is False
-- NOTE: The find module file for this failed TPL 'Netcdf' is:
     /scratch/trilinos/workspace/Trilinos_PR_cuda-11.4.2-uvm-off/Trilinos/cmake/tribits/common_tpls/FindTPLNetcdf.cmake
   which is pointed to in the file:
     /scratch/trilinos/workspace/Trilinos_PR_cuda-11.4.2-uvm-off/Trilinos/TPLsList.cmake

TIP: Even though the TPL 'Netcdf' was explicitly enabled in input,
it can be disabled with:
  -DTPL_ENABLE_Netcdf=OFF
which will disable it and will recursively disable all of the
downstream packages that have required dependencies on it.
When you reconfigure, just grep the cmake stdout for 'Netcdf'
and then follow the disables that occur as a result to see what impact
this TPL disable has on the configuration of Trilinos.

CMake Error at cmake/tribits/core/package_arch/TribitsProcessEnabledTpls.cmake:278 (message):
  ERROR: TPL_Netcdf_NOT_FOUND=TRUE, aborting!
Call Stack (most recent call first):
  cmake/tribits/core/package_arch/TribitsProcessEnabledTpls.cmake:171 (tribits_address_failed_tpl_find)
  cmake/tribits/core/package_arch/TribitsProcessEnabledTpls.cmake:105 (tribits_process_enabled_standard_tpl)
  cmake/tribits/core/package_arch/TribitsProjectImpl.cmake:199 (tribits_process_enabled_tpls)
  cmake/tribits/core/package_arch/TribitsProject.cmake:92 (tribits_project_impl)
  CMakeLists.txt:103 (TRIBITS_PROJECT)
```

We are also seeing a some random build errors showing the compiler crashing like in [this query](https://trilinos-cdash.sandia.gov/index.php?project=Trilinos&begin=2023-11-30&end=2023-12-01&filtercount=2&showfilters=1&filtercombine=and&field1=groupname&compare1=61&value1=Pull%20Request&field2=builderrors&compare2=43&value2=1) showing:

![image](https://github.com/trilinos/Trilinos/assets/1959736/585ff671-0704-4ee8-97f8-6fcf5f17eab3)

No PR iteration will pass while the `cuda-11.4.2` configure failures are occurring.

**Comment by jmlapre** [comment]
Anderson and I added a band-aid fix for the moment as we don't have access to properly fix this issue.  Trying a retest.

**Comment by sebrowne** [comment]
Core issue is here: https://github.com/trilinos/Trilinos/pull/12566#issuecomment-1834686137

I show that @fryeguy52 fixed this last Friday after noon.  Now it's experiencing build errors because the underlying HDF5 version for the new NetCDF was updated.  I've fixed this and am testing it now.  ETA for the fix to be in is within ~3 hours pessimistically.

**Comment by sebrowne** [comment]
Two different PRs have passed their CUDA builds (#12566 and #12575).  I believe we can mark this as closed.
See https://trilinos-cdash.sandia.gov/index.php?project=Trilinos&filtercount=2&showfilters=1&filtercombine=and&field1=groupname&compare1=61&value1=Pull%20Request&field2=buildname&compare2=63&value2=cuda for confirmation (change went in after the two failures, confirmed with the timestamps).

**Comment by bartlettroscoe** [comment]
@sebrowne, we still seem to be seeing random build errors showing that the compiler is being killed most recently started 2 hours ago shown [here](https://trilinos-cdash.sandia.gov/index.php?project=Trilinos&date=2023-12-04&filtercount=1&showfilters=1&field1=buildname&compare1=61&value1=PR-12575-test-rhel7_sems-intel-2021.3-sems-openmpi-4.0.5_release-debug_shared_no-kokkos-arch_no-asan_no-complex_fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-off_no-package-enables-1521) showing:

![image](https://github.com/trilinos/Trilinos/assets/1959736/71cb9b03-c661-4107-8203-b51fc8d52d6f)

The build errors are shown [here](https://trilinos-cdash.sandia.gov/viewBuildError.php?buildid=1298644) showing output containing `terminated by kill signal` like:

```
icpc: error #10106: Fatal error in /projects/sems/install/rhel7-x86_64/sems-compilers/tpl/intel-oneapi-compilers/2021.3.0/gcc/8.3.0/base/fptsktp/compiler/2021.3.0/linux/bin/intel64/mcpcom, terminated by kill signal
compilation aborted for packages/intrepid2/unit-test/Projection/test_convergence_TET_Serial_DOUBLE.cpp (code 1)
```

Looking at this query:

* [All PR builds showing 0 configure errors and between 2 and 8 build errors since 2023-11-27](https://trilinos-cdash.sandia.gov/index.php?project=Trilinos&begin=2023-11-27&end=2023-12-04&filtercount=4&showfilters=1&filtercombine=and&field1=groupname&compare1=61&value1=Pull%20Request&field2=configureerrors&compare2=41&value2=0&field3=builderrors&compare3=43&value3=2&field4=builderrors&compare4=44&value4=9)

showing:

![image](https://github.com/trilinos/Trilinos/assets/1959736/55bd7537-ca0e-4961-ae2c-973d8cec55cc)

all seem to be showing 4 builds showing compiler crashes like this.

They all seem to be occurring while building Intrepid2 objects.  I am wondering if these `.o` files are consuming too much RAM in the compiler and crashing the build because too many parallel build processes are being used on these machines?

This needs to be resolved as well.

NOTE: Unfortunately, CDash does not provide a way to search for builds that have build errors containing certain strings (like exists for the `Test Output` filter for the `queryTests.php` page).  It would be great if it did.  (This is something we could ask Kitware for.)

**Comment by sebrowne** [comment]
@bartlettroscoe the only short-term solution that we have for those types of failures is decreasing the compiler or link parallelism.  Those builds are all reporting that they used -j20 for their build parallelism, which is already not very high (in my opinion).  We can also separately reduce the link parallelism (ninja allows that) since link operations tend to gobble more memory when they are running.

**Comment by sebrowne** [comment]
Okay, looking at our PR drivers, there is a heuristic that we can use to try and dynamically reduce the number of cores with respect to the memory on the machine.  It's currently set to 3Gb per core, and I'll try increasing it to 4Gb per core.  This will likely help the smaller machines where memory is more limited (three of the linked failures were on small machines).  See #12581

**Comment by sebrowne** [comment]
Okay, CUDA is still in a bad state.  We're seeing runtime errors from the SEACAS tests that say:

```
Warning! ***HDF5 library version mismatched error***
The HDF5 header files used to compile this application do not match
the version used by the HDF5 library to which this application is linked.
Data corruption or segmentation faults may occur if the application continues.
This can happen when an application was compiled by one version of HDF5 but
linked with a different version of static or shared HDF5 library.
You should recompile the application or check your shared library related
settings such as 'LD_LIBRARY_PATH'.
You can, at your own risk, disable this warning by setting the environment
variable 'HDF5_DISABLE_VERSION_CHECK' to a value of '1'.
Setting it to 2 or higher will suppress the warning messages totally.
Headers are 1.10.7, library is 1.12.2
```

I looked and here is the relevant configure output:
```
Processing enabled external package/TPL: HDF5 (enabled explicitly, disable with -DTPL_ENABLE_HDF5=OFF)
-- HDF5_LIBRARY_NAMES='hdf5;z;hdf5_hl'
-- TPL_HDF5_LIBRARIES='/projects/sems/install/rhel7-x86_64/sems/tpl/hdf5/1.12.2/gcc/10.1.0/openmpi/4.0.5/n5nu7f7/lib/libhdf5_hl.so;/projects/sems/install/rhel7-x86_64/sems/tpl/hdf5/1.12.2/gcc/10.1.0/openmpi/4.0.5/n5nu7f7/lib/libhdf5.a;/projects/sems/install/rhel7-x86_64/sems/v2/tpl/zlib/1.2.11/gcc/10.1.0/base/rywytxe/lib/libz.a;-ldl'
-- Searching for headers in HDF5_INCLUDE_DIRS='/projects/sems/install/rhel7-x86_64/sems/tpl/hdf5/1.12.2/gcc/10.1.0/openmpi/4.0.5/n5nu7f7/include'
-- Searching for a header file in the set "hdf5.h":
--   Searching for header 'hdf5.h' ...
--     Found header '/projects/sems/install/rhel7-x86_64/sems/tpl/hdf5/1.12.2/gcc/10.1.0/openmpi/4.0.5/n5nu7f7/include//hdf5.h'
-- Found TPL 'HDF5' include dirs '/projects/sems/install/rhel7-x86_64/sems/tpl/hdf5/1.12.2/gcc/10.1.0/openmpi/4.0.5/n5nu7f7/include'
-- TPL_HDF5_INCLUDE_DIRS='/projects/sems/install/rhel7-x86_64/sems/tpl/hdf5/1.12.2/gcc/10.1.0/openmpi/4.0.5/n5nu7f7/include'
```

This indicates the headers are consistent as far as we can set them (I think).  I suspect a possible issue with the installations?  @fryeguy52 does this ring any bells?

I'll work on reproducing this locally to see if there's something we can fix.

**Comment by sebrowne** [comment]
I figured out the SEACASIoss failures.  The CGNS module needs to be changed as well.  Will have this fixed ASAP.

**Comment by bartlettroscoe** [comment]
These failures have been resolved for a while so I will close this.  But it looks like there is another major problem that I will document in a new Issue.
