### ISSUE TITLE
Compile error in Teuchos_YamlParser.cpp

### ISSUE THREAD

**Issue by lxmota** [trilinos/Trilinos#1260]
When trying to compile with yaml-cpp enabled, I get the following compile error:

/home/amota/LCM/Trilinos/packages/teuchos/parameterlist/src/Teuchos_YamlParser.cpp: In static member function âstatic T Teuchos::QuotedAs<T>::eval(const YAML::Node&)â:
/home/amota/LCM/Trilinos/packages/teuchos/parameterlist/src/Teuchos_YamlParser.cpp:79:46: error: âconst class YAML::Nodeâ has no member named âMarkâ
       throw YAML::TypedBadConversion<T>(node.Mark());

**Comment by ibaned** [comment]
So this line of code was added in my PR #1244. Its possible that it doesn't work for older `yaml-cpp` versions, as I was using the latest version from their GitHub repository. Luckily, this line of code just needs to throw any exception, so maybe I'll change it to use a plain old `std::runtime_error`.

**Comment by ibaned** [comment]
@lxmota I've pushed the proposed fix. Please let me know if this fixes your compilation.

**Comment by lxmota** [comment]
@ibaned Yes, that fixed it. Thanks.
