### ISSUE TITLE
EpetraExt::RowMatrix_Transpose returns non-filled matrix

### ISSUE THREAD

**Issue by xamhn** [trilinos/Trilinos#1261]
When computing the explicit transpose of an Epetra_RowMatrix with EpetraExt::RowMatrix_Transpose the returned matrix is *not filled*, i.e. filled()=false, in case that 2 or more MPI processes are used. In my particular case the matrix is rectangular.
Problem occurred with Release 12.10. In release 12.8 the returned matrix is filled.

**Comment by lucbv** [comment]
@mhoemmen did you look into this?
I did a quick fix in the EpetraExt transpose routine a couple weeks ago see commit 8ed300d, aae5735 to avoid communicator splitting. At that point it seemed that the transpose was returning a filled matrix.
Do we have an example that would return a non filled matrix?
This would create an issue in MueLu because of the change in 9976e98.
If we can get an example I would not mind looking at it.

**Comment by mhoemmen** [comment]
@lucbv I am not in charge of Epetra.  I'm really super busy with Tpetra and other work at the moment.  I would suggest that you talk either with @maherou or with @jhux2 about the request for Epetra.  Thanks!

**Comment by lucbv** [comment]
@mhoemmen, ok, I just wanted to make sure that we are not working on it at the same time.
@xamhn do you have a small example that reproduces this error?

**Comment by xamhn** [comment]
@lucbv Sure, find a snippet below. For release 12.10 it produces output:

```
My PID: 0 Matrix filled before calling 'fillComplete'? 0
My PID: 1 Matrix filled before calling 'fillComplete'? 0
My PID: 0 Matrix filled after calling 'fillComplete'? 1
My PID: 1 Matrix filled after calling 'fillComplete'? 1
My PID: 0 Transpose of Matrix filled? 0
My PID: 1 Transpose of Matrix filled? 1
``` 

If I just replace /packages/epetraext/src/transform with the respective folder from release 12.8 the output is:
```
My PID: 0 Matrix filled before calling 'fillComplete'? 0
My PID: 1 Matrix filled before calling 'fillComplete'? 0
My PID: 1 Matrix filled after calling 'fillComplete'? 1
My PID: 0 Matrix filled after calling 'fillComplete'? 1
My PID: 1 Transpose of Matrix filled? 1
My PID: 0 Transpose of Matrix filled? 1
```

Snippet:
```
// construct 2x1 Epetra_Crs Matrix on 2 processes, where process with 
// PID 0 owns no rows and PID 1 ows both rows. Then compute transpose 
// with Epetra_Ext::RowMatrix_Transpose

// comm_: Epetra_Comm object

int pid = comm_.MyPID();

// create map
int my_global_ele[2];
int global_ele;
int my_ele;

if (pid==0)
{
  global_ele = 2;
  my_ele = 0;
}
else
{
  my_global_ele[0] = 0;
  my_global_ele[1] = 1;
  global_ele = 2;
  my_ele = 2;
}
Teuchos::RCP<Epetra_Map> map = Teuchos::rcp(new Epetra_Map(global_ele,my_ele,my_global_ele,0,comm_));

// create matrix
int numEntries = 1;
Teuchos::RCP<Epetra_CrsMatrix> matrix = Teuchos::rcp(new Epetra_CrsMatrix(Copy, *map, &numEntries));

double val = 2; // some random value
int ind = 0;

// process 0 has nothing to do here
if (pid)
{
  for (int i=0; i<2; i++)
  {
    int err = matrix->InsertGlobalValues(i,1,&val,&ind);
    if (err)
      // throw some error
  }
}

std::cout << "My PID: "<< pid << " Matrix filled before calling 'fillComplete'? " << matrix->Filled() << std::endl;

matrix->FillComplete();

std::cout << "My PID: "<< pid << " Matrix filled after calling 'fillComplete'? " << matrix->Filled() << std::endl;

EpetraExt::RowMatrix_Transpose transposer;
Epetra_CrsMatrix* tp_matrix = dynamic_cast<Epetra_CrsMatrix*>(&transposer(*matrix));

std::cout << "My PID: "<< pid << " Transpose of Matrix filled? " << tp_matrix->Filled() << std::endl;
```

**Comment by jhux2** [comment]
@lucbv I see only one commit difference between 12.8 and 12.10: a9f5581.

**Comment by lucbv** [comment]
@xamhn I have started working on this issue, thanks for the example, it will speed things up for me.
@jhux2 Good to know that only few things have changed in between versions it will make things easy to track.
I'll keep you posted on the progress I make for this issue.

**Comment by lucbv** [comment]
@xamhn , this problem is related to the patch I submitted a few weeks ago aae5735.
After running the code snippet with the current version of develop I do not see any errors, here is my output:

```My PID: 0 Matrix filled before calling 'fillComplete'? 0
My PID: 1 Matrix filled before calling 'fillComplete'? 0
My PID: 0 Matrix filled after calling 'fillComplete'? 1  
My PID: 1 Matrix filled after calling 'fillComplete'? 1  
My PID: 1 Transpose of Matrix filled? 1  
My PID: 0 Transpose of Matrix filled? 1```

Here the story is that the commit that @jhux2 pointed at above is not handling the case of a restricted communicator (see comments on line 4876) and aae5735 avoids communicator splitting when one of the mpi rank has no entries in the transposed matrix.
