### ISSUE TITLE
Tpetra with kokkos::complex

### ISSUE THREAD

**Issue by bathmatt** [trilinos/Trilinos#1262]
I tried to enable Kokkos::complex<double> in tpetra and I'm getting std::complex.  how does one enable kokkos??

According to nm I'm only getting std ones

dir-src (gcc) 114 $ nm -C
/home/mbetten/installs/install-for-panzer/gcc-DEBUG/lib/libtpetra.a
|grep Vector |grep complex |grep replaceLocalValue |grep -v std

returns nothing and I get errors about missing kokkos::complex versions.

where the grep std replacement shows lots of hits

My first try used just
-D Tpetra_INST_COMPLEX_DOUBLE:BOOL=ON \

but it said it needed teuhos so I did

-D Teuchos_ENABLE_COMPLEX:BOOL=ON \

and that got me std::complex

Tried Trilinos_ENABLE_COMPLEX_DOUBLE and still nope

dir-debug (gcc) 24 $ grep -i complex out
-- Performing Test CXX_COMPLEX_BLAS_WORKS
-- Performing Test CXX_COMPLEX_BLAS_WORKS - Success
   Scalars: double;complex<double>
-- <complex, int, int>       : ON
-- Enabled Scalar types:        double|std::complex<double>
-- Set of enabled types, before exclusions: S={double} N={Kokkos::Compat::KokkosOpenMPWrapperNode} LO={int} GO={int};S={double} N={Kokkos::Compat::KokkosOpenMPWrapperNode} LO={int} GO={long long};S={std::complex<double>} N={Kokkos::Compat::KokkosOpenMPWrapperNode} LO={int} GO={int};S={std::complex<double>} N={Kokkos::Compat::KokkosOpenMPWrapperNode} LO={int} GO={long long}
-- Enabled Scalar types:        int|long long|double|std::complex<double>
-- Set of enabled types, before exclusions: S={int} LO={int} GO={int} N={Kokkos::Compat::KokkosOpenMPWrapperNode};S={int} LO={int} GO={long long} N={Kokkos::Compat::KokkosOpenMPWrapperNode};S={double} N={Kokkos::Compat::KokkosOpenMPWrapperNode} LO={int} GO={int};S={double} N={Kokkos::Compat::KokkosOpenMPWrapperNode} LO={int} GO={long long};S={std::complex<double>} N={Kokkos::Compat::KokkosOpenMPWrapperNode} LO={int} GO={int};S={std::complex<double>} N={Kokkos::Compat::KokkosOpenMPWrapperNode} LO={int} GO={long long};S={int} N={Kokkos::Compat::KokkosOpenMPWrapperNode} LO={int} GO={int};S={int} N={Kokkos::Compat::KokkosOpenMPWrapperNode} LO={int} GO={long long};S={long long} N={Kokkos::Compat::KokkosOpenMPWrapperNode} LO={int} GO={int};S={long long} N={Kokkos::Compat::KokkosOpenMPWrapperNode} LO={int} GO={long long};S={double} N={Kokkos::Compat::KokkosOpenMPWrapperNode} LO={int} GO={int};S={double} N={Kokkos::Compat::KokkosOpenMPWrapperNode} LO={int} GO={long long};S={std::complex<double>} N={Kokkos::Compat::KokkosOpenMPWrapperNode} LO={int} GO={int};S={std::complex<double>} N={Kokkos::Compat::KokkosOpenMPWrapperNode} LO={int} GO={long long}

**Comment by mhoemmen** [comment]
@bathmatt Are you using `Scalar=std::complex<double>`?  `Kokkos::complex` is only an internal type that makes Kokkos work.  You're supposed to use `Scalar=std::complex<double>` and let Tpetra take care of the rest.  Hence `impl_scalar_type` etc.

**Comment by bathmatt** [comment]
I have my own matrix type since I'm dealing with dense object.  It is
Kokkos::Complex not std.  I'd like to use the export routines of tpetra and
not have to write my own.  I don't really want to mix complex types.

Can I say Kokkos:complex a = std::complex<double>(1,2)??

is the math all automatic?

So, does getDualView return Kokkos::DualView<Kokkos::Complex<double>*> then
for a vector?

**Comment by bathmatt** [comment]
Yeah, that doesn't work because getDualView returns a view to a view of
std::complex, not kokkos::complex.

```
   Kokkos::View<Cmplx*> aa= shared_soln_->getDualView().d_view;


```
errors out as
```
[ 50%] Building CXX object src/CMakeFiles/ComplexMatrix.exe.dir/main.cpp.o
In file included from
/home/mbetten/installs/install-for-panzer/gcc-DEBUG/include/Kokkos_Parallel.hpp:52:0,
                 from
/home/mbetten/installs/install-for-panzer/gcc-DEBUG/include/Kokkos_Serial.hpp:52,
                 from
/home/mbetten/installs/install-for-panzer/gcc-DEBUG/include/Kokkos_Core.hpp:53,
                 from
/home/mbetten/Trilinos/N-Body/src/const_len_vector.hpp:10,
                 from /home/mbetten/Trilinos/N-Body/src/main.cpp:1:
/home/mbetten/installs/install-for-panzer/gcc-DEBUG/include/Kokkos_View.hpp:
In instantiation of ‘Kokkos::View<DataType, Properties>::View(const
Kokkos::View<RT, RP ...>&) [with RT = Kokkos::complex<double>**; RP =
{Kokkos::LayoutLeft, Kokkos::OpenMP, void}; DataType =
Kokkos::complex<double>*; Properties = {}]’:
/home/mbetten/Trilinos/N-Body/src/ParallelMatrix.hpp:294:58:   required
from here
/home/mbetten/installs/install-for-panzer/gcc-DEBUG/include/Kokkos_View.hpp:1221:7:
error: static assertion failed: Incompatible View copy construction
       static_assert( Mapping::is_assignable , "Incompatible View copy
construction" );
       ^~~~~~~~~~~~~
make[2]: *** [src/CMakeFiles/ComplexMatrix.exe.dir/main.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/ComplexMatrix.exe.dir/all] Error 2
make: *** [all] Error 2
dir-src (gcc) 69 $
```

**Comment by srajama1** [comment]
@bathmatt : Why not use multivector ?

**Comment by bathmatt** [comment]
How would that make things different?  First, it is the conversion from std::complex to kokkos::complex?  Are you suggesting I use a MV (real, imag)?

**Comment by srajama1** [comment]
Yeah, splitting complex to (real, imag) is one option, but that will defeat the purpose of templated stack. I wasn't recommending that.

At least the way I understand the design you shouldn't use Kokkos::complex. Using MV with std::complex is one way.

**Comment by bathmatt** [comment]
I'm not sure you understand the problem
I have myfunctor(Kokkos::View<Kokkos::complex<..>> my_data);
it has to be a kokkos complex not a std::complex because I do things to it in my functor on device

However, I want to use the tpetra import export routines.  Therefore, I want a tpetra vector or mv, either is fine.  However, tpetra only supports std::complex, not kokkos::complex as far as I can tell.  I don't know how to get a kokkos::complex view out. 

Should I just use C to fix it

my_view = *(Kokkos::View<Kokkos::complex<..>>*)(&myvec.getDualView().d_view);

I'm assuming that should do the right thing most of the time but it is a hack.

**Comment by srajama1** [comment]
My bad, I didn't understand what you were facing. Your hack could happen in a getLocalVector() so you and other users don't see it.

**Comment by bathmatt** [comment]
Can we fix the logic in tpetra cmake so we can use Kokkos::Complex??  It is templated code so that should be doable, 

In the mean time, will my hack fix work?  @crtrott @mhoemmen ideas?  Can I just do

```
Kokkos::View<Kokkos::complex<..>> my_view = *(Kokkos::View<Kokkos::complex<..>>*)(&myvec.getDualView().d_view);
```
and work around this?

**Comment by bathmatt** [comment]
So, it looks like d_view does return kokkos::complex<>**  I think, (it is very hard to tell).  So, that I've opened #1265 to address the bug in returning a 2d view for a 1D structure.  

Can subview reduce rank of a view?

**Comment by bathmatt** [comment]
OK, looks like I've got a workaround, keeping issue #1265 open because I believe it is a bug.

**Comment by mhoemmen** [comment]
@bathmatt wrote:
> Yeah, that doesn't work because getDualView returns a view to a view of std::complex, not kokkos::complex.

Nope.  `getDualView` returns `DualView<impl_scalar_type**, ...>`.  `impl_scalar_type` is `Kokkos::complex<T>` when `scalar_type` is `std::complex<T>`.
