### ISSUE TITLE
Epetra: error code of ExtractGlobalRowCopy function

### ISSUE THREAD

**Issue by swiesheier** [trilinos/Trilinos#12638]
When calling Epetra_CrsGraph::ExtractGlobalRowCopy, I get a negative integer (-1) as a result. 

What does this integer mean? The html docu just states "Integer error code, set to 0 if successful. "

I am accessing this function from a third party software and am just interested in what the errror conceptually means to narrow down my problem.

**Comment by jhux2** [comment]
@swiesheier I'm not an Epetra develop, but that return code appears to indicate that the global row number is out-of-range:
https://github.com/trilinos/Trilinos/blob/8e119db068e5d8f8f0d2f6d77a8b640b645f4b84/packages/epetra/src/Epetra_CrsGraph.cpp#L2024-L2025.
