### ISSUE TITLE
Sacado: change dependency to Teuchos sub-packages

### ISSUE THREAD

**Issue by ibaned** [trilinos/Trilinos#1263]
Please refer to TriBITSPub/TriBITS#188 for the details on why it is bad to list just `Teuchos` as a dependency of `Sacado`. This issue is to request that Sacado developers change their dependencies to list teuchos sub-packages like `TeuchosCore`, and change the `#ifdef`s in the code to use `HAVE_SACADO_TEUCHOSCORE` instead of `HAVE_SACADO_TEUCHOS`, for example.

@trilinos/sacado

**Comment by bartlettroscoe** [comment]
Looking at:

```
$ cat packages/sacado/cmake/Dependencies.cmake 
SET(LIB_REQUIRED_DEP_PACKAGES)
SET(LIB_OPTIONAL_DEP_PACKAGES Teuchos KokkosCore TeuchosKokkosComm)
SET(TEST_REQUIRED_DEP_PACKAGES)
SET(TEST_OPTIONAL_DEP_PACKAGES TeuchosCore KokkosContainers)
SET(LIB_REQUIRED_DEP_TPLS)
SET(LIB_OPTIONAL_DEP_TPLS)
SET(TEST_REQUIRED_DEP_TPLS)
SET(TEST_OPTIONAL_DEP_TPLS ADOLC ADIC CppUnit)
```

and

```
$ find packages/sacado -name "CMakeLists.txt" -exec grep -nH ENABLE_Teuchos {} \;
packages/sacado/test/UnitTests/CMakeLists.txt:10:IF (Sacado_ENABLE_Teuchos)
packages/sacado/test/performance/CMakeLists.txt:6:IF (${PACKAGE_NAME}_ENABLE_Teuchos AND NOT Kokkos_ENABLE_Cuda)
packages/sacado/test/performance/CMakeLists.txt:75:IF (Sacado_ENABLE_Teuchos AND Sacado_ENABLE_KokkosCore)
packages/sacado/test/performance/fenl_assembly_view/CMakeLists.txt:7:    Sacado_ENABLE_Teuchos)
packages/sacado/test/performance/fenl_assembly/CMakeLists.txt:7:    Sacado_ENABLE_Teuchos)
packages/sacado/test/TestSuite/CMakeLists.txt:16:IF (${PACKAGE_NAME}_ENABLE_Teuchos)
packages/sacado/example/CMakeLists.txt:126:IF(Sacado_ENABLE_Teuchos)
packages/sacado/src/CMakeLists.txt:174:IF (${PACKAGE_NAME}_ENABLE_Teuchos)
packages/sacado/src/CMakeLists.txt:213:ENDIF(${PACKAGE_NAME}_ENABLE_Teuchos)
```

and:

```
 find packages/sacado/src -name "*pp" -exec grep Teuchos {} \; | grep include | sort | uniq
#include "Kokkos_TeuchosCommAdapters.hpp"
#include "Teuchos_Array.hpp"
#include "Teuchos_Assert.hpp"
#include "Teuchos_BLAS.hpp"
#include "Teuchos_LAPACK.hpp"
#include "Teuchos_PromotionTraits.hpp"
#include "Teuchos_RCP.hpp"
#include "Teuchos_ScalarTraits.hpp"
#include "Teuchos_SerializationTraitsHelpers.hpp"
#include "Teuchos_SerializationTraits.hpp"
```

and:

```
$ find packages/sacado -name "*pp" -exec grep Teuchos {} \; | grep include | sort | uniq
#include "Kokkos_TeuchosCommAdapters.hpp"
#include "Teuchos_Array.hpp"
#include "Teuchos_Assert.hpp"
#include "Teuchos_BLAS.hpp"
#include "Teuchos_CommandLineProcessor.hpp"
#include "Teuchos_CommHelpers.hpp"
#include "Teuchos_Comm.hpp"
#include "Teuchos_DefaultComm.hpp"
#include "Teuchos_GlobalMPISession.hpp"
#include "Teuchos_LAPACK.hpp"
#include "Teuchos_PromotionTraits.hpp"
#include "Teuchos_RCP.hpp"
#include "Teuchos_ScalarTraits.hpp"
#include "Teuchos_SerializationTraitsHelpers.hpp"
#include "Teuchos_SerializationTraits.hpp"
#include "Teuchos_StandardCatchMacros.hpp"
#include "Teuchos_TestingHelpers.hpp"
#include "Teuchos_Time.hpp"
#include "Teuchos_UnitTestHarness.hpp"
#include "Teuchos_UnitTestRepository.hpp"
#include "Teuchos_VerboseObject.hpp"
```

you need to change sacado/Dependencies.cmake to be:

```
TRIBITS_PACKAGE_DEFINE_DEPENDENCIES(
  LIB_OPTIONAL_PACKAGES KokkosCore TeuchosCore TeuchosNumerics TeuchosKokkosComm
  TEST_OPTIONAL_PACKAGES TeuchosComm KokkosContainers
  TEST_OPTIONAL_TPLS ADOLC ADIC CppUnit
  )
```

and then replace the logic based on `${PACKAGE_NAME}_ENABLE_Teuchos` with logic based on  `${PACKAGE_NAME}_ENABLE_TeuchosCore` , `${PACKAGE_NAME}_ENABLE_TeuchosNumerics` and/or `${PACKAGE_NAME}_ENABLE_TeuchosComm` in the CMakeLists.txt files.

This should not be a lot of work to fix.  I could likely bang that out pretty fast and then post a PR to fix this.

**Comment by etphipp** [comment]
*sigh*

OK.  Is there some reason this is coming up?

**Comment by bartlettroscoe** [comment]
> OK. Is there some reason this is coming up?

See the first comment in TriBITSPub/TriBITS#188.

The way that Sacado is delcaring its dependencies on Teuchos is not really correct based on the rules defined at:

* https://tribits.org/doc/TribitsDevelopersGuide.html#tribits-dependency-handling-behaviors

Either that or MiniTensor needs to just give up and declare a required dependency on Teuchos (which is not the direction we should be going in Trilinos).

**Comment by bartlettroscoe** [comment]
To state this this in a more positive way, Sacado should narrow the list dependencies on Teuchos as much as it can, like it is already doing for Kokkos.  If Sacado is depending on all of Teuchos even if it only uses a subset of its subpackages, then why does Sacado not just depend on all of Kokkos instead of declaring a dependency on only the subpackages KokkosCore and KokkosContainers?  Why is Sacado being (properly) selective with Kokkos but not with Teuchos?  Either Scado should be consistent and just declare optional dependencies on all of `Kokkos` and `Teuchos` or it should be selective and only list dependencies on the Kokkos and Teuchos subpackages that it actually uses.

Does this make sense?  If so, why not?

**Comment by bartlettroscoe** [comment]
FYI: PR #4546 should have this problem addressed now.

**Comment by etphipp** [comment]
PR #4546 should resolve this, so I am closing this issue.
