### ISSUE TITLE
MiniTensor: issues blocking efficient GPU usage

### ISSUE THREAD

**Issue by ibaned** [trilinos/Trilinos#1264]
@lxmota 
This issue is here to collect all the different problems there would be with using MiniTensor in a runtime and memory efficient way on GPUs for the Alexa application. It is not urgent that these get solved, since we have an alternative approach besides MiniTensor that we can use for a while. Feel free to use this as the basis for improvements to MiniTensor at your discretion. If most of them get resolved, MiniTensor will then be useful to Alexa.

1. Unnecessary variables in objects. `sizeof(Tensor<double,3>)==96`, while `sizeof(double)*3*3==72`. The extra 24 bytes are for three different things:
   1. The `size_` integer in `Storage`, to support changing it at runtime. We would like a variant of `Storage` similar to `DYNAMIC` instead it means `REALLY_STATIC` or something.
   1. The `dimension_` integer in `TensorBase`. One possible fix is to move `dimension_` into `Storage`, so that the `REALLY_STATIC` thing above could fix that as well. [DONE]
   1. The `vtable` for `TensorBase`. Because the `TensorBase` destructor was declared `virtual`, every `TensorBase` object has a `vtable`. This should only be needed if something like this is being done:
      ```cpp
      TensorBase<...>* ptr = new Tensor<double,2>;
      delete ptr;
      ```
      My recommendation is to make the destructor not virtual. Also, the destructor still has a definition even though it is virtual. That should be removed if its going to stay virtual. [DONE]

1. All constructors fill components with `NaN`. While this is useful for debugging, we really need an option to construct a `Tensor` that does not set any values. Setting these values can be quite expensive if the lifetimes of `Tensor`s are short.

1. Calling non-`KOKKOS_INLINE_FUNCTION`s from `KOKKOS_INLINE_FUNCTION`s.
   1. The biggest thing here is the use of `Teuchos::ScalarTraits`. `Kokkos::ArithTraits` was created (I think) to replace `Teuchos::ScalarTraits` in GPU code. Please consider switching to `Kokkos::ArithTraits`
   1. C++ standard library objects should not be used in GPU-callable code. This includes `std::pair` and definitely includes `std::vector`, both of which were involved in some MiniTensor `KOKKOS_INLINE_FUNCTION` calls.
   1. Likewise, `boost::tie` and `boost::tuple`, actually anything from Boost, should not be called from `KOKKOS_INLINE_FUNCTION` code.

**Comment by lxmota** [comment]
I'm open to work and fix all these issues.

My only concern is that we should keep compatibility with existing code. MiniTensor is used in both research and production codes.

**Comment by ibaned** [comment]
Sounds good, thank you. If there is a particular item that looks like it cannot be resolved due to production code requirements, please indicate that in these comments so we get an idea of the difficulty level of each item.

**Comment by MalachiTimothyPhillips** [comment]
I've encountered a couple of these issues from ```operator[]``` in ```Storage``` not being marked ```KOKKOS_INLINE_FUNCTION```.

Here is a pull request that addresses (some) of these issues: https://github.com/trilinos/Trilinos/pull/3005.

**Comment by ibaned** [comment]
I think MiniTensor is not maintained anymore.

**Comment by lxmota** [comment]
Well, I'm still fixing issues that I can. I don't ever recall seeing this pull request, but maybe I can just merge it.

**Comment by lxmota** [comment]
Ok, I reviewed this. Some of it was done, and the other outstanding issues were most relevant if MiniTensor were to be used in (now) LGR. Since @ibaned (most of) and I (a little) have ported to LGR some of MiniTensor's functionality, these issues are low priority here (such as getting rid of boost calls).
