### ISSUE TITLE
Kokkos: Comparing signed to unsigned values in KokkosExp_MDRangePolicy.hpp

### ISSUE THREAD

**Issue by william76** [trilinos/Trilinos#1266]
KokkosExp_MDRangePolicy.hpp was changed that added some new warnings to the build that was caught in the Werror build:

```
Trilinos/packages/kokkos/core/src/KokkosExp_MDRangePolicy.hpp:239:5: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
Trilinos/packages/kokkos/core/src/KokkosExp_MDRangePolicy.hpp:245:7: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
```

Offending code lines are: [239](https://github.com/trilinos/Trilinos/blob/develop/packages/kokkos/core/src/KokkosExp_MDRangePolicy.hpp#L239) and [245](https://github.com/trilinos/Trilinos/blob/develop/packages/kokkos/core/src/KokkosExp_MDRangePolicy.hpp#L245).

There's no '@' label for Trilinos/Kokkos label, so I couldn't tag this issue.

**Comment by ibaned** [comment]
Hi @william76 , Kokkos issues should be opened on the [Kokkos repository](https://github.com/kokkos/kokkos/issues/749).

I've gone ahead and moved this issue for you to kokkos/kokkos#749.

I'll close this issue, and we can continue in the one in the Kokkos repository.

**Comment by mhoemmen** [comment]
@william76 btw, we can fix this in Trilinos temporarily if you can't wait until the next integration of Kokkos into Trilinos.

**Comment by ibaned** [comment]
@mhoemmen :  @ndellingwood did that yesterday in 6d781fb

**Comment by mhoemmen** [comment]
@ibaned cool :D
