### ISSUE TITLE
Framework: naming of PR tests is misleading

### ISSUE THREAD

**Issue by jhux2** [trilinos/Trilinos#12686]
## Enhancement
@trilinos/framework

Three of the PR build names contain the phrase `no-complex`, but complex is enabled in each.  You can see this in the results for PR #12684:

![image](https://github.com/trilinos/Trilinos/assets/12970120/e09356af-c80c-40d0-8ed2-d50889e16691)

**Comment by sebrowne** [comment]
Thanks for catching this @jhux2 !  I saw your tag last night, checked it out, and agree that we're blatantly enabling couplex<double> in many places that we do not intend to 😢.  I will push a fix ASAP.

**Comment by bartlettroscoe** [comment]
The problem is that the GenConfig system does not get the build options from the build name (which is what the ATDM Trilinos configuration did so it was almost impossible for the build name to be wrong).  For GenConfig, it requires people carefully make them match (and people make mistakes).   No clear why that feature was not maintained in the GenConfig system.

**Comment by sebrowne** [comment]
Fixed with #12690

**Comment by jhux2** [comment]
@sebrowne Thanks!  I can confirm that complex is disabled in Tpetra ETI for the builds labeled `no-complex`.

However, cmake [output](https://trilinos-cdash.sandia.gov/build/1369527) indicates that Tacho is enabling complex:

```
Processing enabled top-level package: ShyLU_Node (HTS, Tacho, FastILU)
-- Generating ETI: Tacho_Driver_ETI_double_Serial.cpp
-- Generating ETI: Tacho_Driver_ETI_float_Serial.cpp
-- Generating ETI: Tacho_Driver_ETI_complex_double_Serial.cpp
-- Generating ETI: Tacho_Driver_ETI_complex_float_Serial.cpp
```

**Comment by sebrowne** [comment]
Okay, I'll take a look and see if there's something special about how Tacho decides if complex is enabled or disabled.

**Comment by sebrowne** [comment]
@jhux2 it is always done explicitly in `shylu_node/tacho/src/CMakeLists.txt` with no way to disable it.  Not sure if it actually matters?

**Comment by jhux2** [comment]
> it is always done explicitly in `shylu_node/tacho/src/CMakeLists.txt` with no way to disable it. Not sure if it actually matters?

@sebrowne Thanks for looking.  I'll close this as fixed and open a separate issue for ShyLU.
