### ISSUE TITLE
 Epetra to Tpetra Stack

### ISSUE THREAD

**Issue by dgmaths9** [trilinos/Trilinos#12683]
I am trying to move a code from Epetra to Tpetra Stack.

I am experiencing problems in generating Tpetra::FECrsGraph. I illustrate it through an example of 2 processes below:

ownedRowMap:
   pid 0:  {0,2,4} 
   pid 1: {1,3,5,6,7,8}

ownedPlusSharedRowMap:
   pid0: {0,1,2,3,4,5}
   pid1: {1,3,5,6,7,8}

if I build a graph
  size_t maxEntriesPerRow = 20;
  RCP<fe_graph_type> fe_crs_graph = rcp(new fe_graph_type(ownedRowMap, ownedPlusSharedRowMap, maxEntriesPerRow));

I get the error: 
Throw test that evaluated to true: (ownedRowsImporter_->getNumSameIDs() != ownedRowsImporter_->getSourceMap()->getLocalNumElements())

Tpetra::FECrsGraph<int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP, Kokkos::HostSpace> >::FECrsGraph::setup(): ownedRowMap contains entries which are not in the ownedPlusSharedRowMap.
  
How can I solve this problem?
thanks,
Deepak

**Comment by dgmaths9** [comment]
@csiefer2 thanks for answering, that solved the problem. 
I have three other questions.

1. How can I extract data from a Tpetra_Vector to a std::vector (or a boost vector)?
2. How to get the address of the first element of a Tpetra_Vector? (For Epetra I was using &(*v)[0] )
3. Is there parallel support for reading and writing of distributed Tpetra_Vector using MPI?

Many thanks,
Deepak

**Comment by dgmaths9** [comment]
Thanks again!!
Is there a way to print the elements of a Tpetra_Map?

**Comment by cgcgcg** [comment]
Have a look at the `describe` method of `Tpetra::Map`: https://docs.trilinos.org/dev/packages/tpetra/doc/html/classTpetra_1_1Map.html

**Comment by dgmaths9** [comment]
Thanks Christian!! Sorry for this late msg.

**Comment by cgcgcg** [comment]
@dgmaths9 May we close this issue?

**Comment by dgmaths9** [comment]
Yes, please.

------------------------------------------------------
Deepak Garg
Istituto Nazionale di Geofisica e Vulcanologia
Via Cesare Battisti 53 - 56125 Pisa - Italy
mobile: +39 3661239424
***@***.***
-------------------------------------------------------
