### ISSUE TITLE
Teuchos YAML tests failing in Nightly build Linux-GCC-4.7.2-RELEASE_DEV_Teuchos_YAML on dorksaber

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#1268]
**Description:**

The Teuchos YAML tests TeuchosParameterList_YamlParser_test and TeuchosComm_ParameterList_UnitTest_Parallel have been failing for many days on for the build shown in the below email.  The failed unit tests showed:

```
3. YAML_ConvertFromXML_UnitTest ... One list is missing parameter: "coarse: max size"
One list is missing parameter: "coarse: max size"

 Teuchos::haveSameValuesUnordered(*xmlList, *yamlList, true) = false == true = true : FAILED ==> /home/nightlyTesting/RELEASE_DEV_Teuchos_YAML/Trilinos/packages/teuchos/comm/test/ParameterList/ParameterList_yaml_Parallel.cpp:96
 Teuchos::haveSameValuesUnordered(*xmlList, *yamlList, true) = true == true = true : passed
 Teuchos::haveSameValuesUnordered(*xmlList, *yamlList, true) = true == true = true : passed
 Teuchos::haveSameValuesUnordered(*xmlList, *yamlList, true) = true == true = true : passed
 Teuchos::haveSameValuesUnordered(*xmlList, *yamlList, true) = true == true = true : passed
 Teuchos::haveSameValuesUnordered(*xmlList, *yamlList, true) = true == true = true : passed
 [FAILED]  (0.0214 sec) YAML_ConvertFromXML_UnitTest
 Location: /home/nightlyTesting/RELEASE_DEV_Teuchos_YAML/Trilinos/packages/teuchos/comm/test/ParameterList/ParameterList_yaml_Parallel.cpp:80
```

Might be good if the failure of `Teuchos::haveSameValuesUnordered(*xmlList, *yamlList, true)` could  be a little more verbose so we can see what part did not match.  Now someone will have to reproduce that build and run a debugger to see what failed.

----

From: teuchos-regression-bounces@software.sandia.gov [mailto:teuchos-
regression-bounces@software.sandia.gov] On Behalf Of CDash
Sent: Wednesday, April 26, 2017 2:32 AM
To: teuchos-regression@software.sandia.gov
Subject: [Teuchos-Regression] FAILED (t=2): Trilinos/Teuchos - Linux-GCC-4.7.2-
RELEASE_DEV_Teuchos_YAML - Nightly

A submission to CDash for the project Trilinos has failing tests.
You have been identified as one of the authors who have checked in changes
that are part of this submission or you are listed in the default contact list.

Details on the submission can be found at
http://testing.sandia.gov/cdash/buildSummary.php?buildid=2859609

Project: Trilinos
SubProject: Teuchos
Site: dorksaber.srn.sandia.gov
Build Name: Linux-GCC-4.7.2-RELEASE_DEV_Teuchos_YAML
Build Time: 2017-04-26T06:25:58 UTC
Type: Nightly
Tests failing: 2

*Tests failing*
TeuchosParameterList_YamlParser_test
(http://testing.sandia.gov/cdash/testDetails.php?test=38287211&build=2859609)
TeuchosComm_ParameterList_UnitTest_Parallel
(http://testing.sandia.gov/cdash/testDetails.php?test=38287218&build=2859609)

----

**CC:** @trilinos/teuchos, @ibaned

**Comment by bartlettroscoe** [comment]
I created this issue mostly because I am getting spammed every day with these CDash failures.  We need to make recurring CDash emails that go unresolved for days (or weeks, months, and years) go away.

Once we upgrade to GCC 4.9.3 for the standard CI build (see #1002), then we can add yaml-cpp to the set of PT TPLs (see #1167) and then we can finally properly protect the Teuchos PL/YAML reader/writer.

But until that happens, this build likely needs to go to the new "Specialized" CDash track/group (see #1182). 

@william76, can you please move this build to the "Specialized" track as well?

Thanks,

-Ross

**Comment by ibaned** [comment]
1. These tests are passing on my workstation which uses the latest `yaml-cpp` from GitHub, so whatever it is is likely specific to an old `yaml-cpp` version

2. Looking at the output of `TeuchosParameterList_YamlParser_test`, it looks like `yaml-cpp` at some point sorted the parameters, probably alphabetically:
```
5. YAML_TwoDArrayConvert_UnitTest ... 
 yamlString = %YAML 1.1
 ---
 ANONYMOUS:
   Problem: 
     Neumann BCs: 
       Time Dependent NBC on SS cyl_outside for DOF all set P: 
         BC Values: [[0], [10], [20]]
   Discretization: 
     Node Set Associations: [['1', '2'], [top, bottom]]
 ...
  == expectedYamlString = %YAML 1.1
 ---
 ANONYMOUS:
   Problem: 
     Neumann BCs: 
       Time Dependent NBC on SS cyl_outside for DOF all set P: 
         BC Values: [[0], [10], [20]]
   Discretization: 
     Node Set Associations: [['1', '2'], [top, bottom]]
 ...
  : passed
 yamlString2 = %YAML 1.1
 ---
 ANONYMOUS:
   Discretization: 
     Node Set Associations: [['1', '2'], [top, bottom]]
   Problem: 
     Neumann BCs: 
       Time Dependent NBC on SS cyl_outside for DOF all set P: 
         BC Values: [[0], [10], [20]]
 ...
  == expectedYamlString = %YAML 1.1
 ---
 ANONYMOUS:
   Problem: 
     Neumann BCs: 
       Time Dependent NBC on SS cyl_outside for DOF all set P: 
         BC Values: [[0], [10], [20]]
   Discretization: 
     Node Set Associations: [['1', '2'], [top, bottom]]
 ...
  : FAILED ==> /home/nightlyTesting/RELEASE_DEV_Teuchos_YAML/Trilinos/packages/teuchos/parameterlist/test/yaml/YamlParameterList.cpp:170
```
I'll try changing the input to be already sorted. This may be the same fundamental cause of the other test failure. Could we also consider using an `Ordered` comparison ?

**Comment by ibaned** [comment]
nevermind about `Ordered`, I'm guessing `Unordered` means it will still succeed if the order gets changed, so the `YAML_ConvertFromXML_UnitTest` might really have lost a parameter somehow.

**Comment by ibaned** [comment]
I've pushed f0ad0e5 which will hopefully fix one of these tests.

**Comment by ibaned** [comment]
I suspect jbeder/yaml-cpp#386 and its resolution in jbeder/yaml-cpp@f0b15cd are what changed the behavior from auto-sorting to preserving the original order. Maintaining order is understandably important to lots of `yaml-cpp` users, as one can see in jbeder/yaml-cpp#169. The new behavior is in the master branch, but no formal release of `yaml-cpp` has been done in a long time (> 1 year).

**Comment by ibaned** [comment]
Anyone interested please join me in requesting a new release at jbeder/yaml-cpp#415

**Comment by ibaned** [comment]
Okay, it seems the "bug" in the old version is pretty bad. Because the old type was a map that used pointers as keys, the sort order is based on the memory allocation behavior, not anything sane like alphabetical order. @bartlettroscoe is there an API to sort the parameters in a `Teuchos::ParameterList` ? We may have to work around the bad behavior of the currently released version of `yaml-cpp` until they release a new version.

**Comment by ibaned** [comment]
also, I can't reproduce the `TeuchosComm_ParameterList_UnitTest_Parallel` on my workstation even after using `yaml-cpp` version 0.5.3.

**Comment by bartlettroscoe** [comment]
> is there an API to sort the parameters in a Teuchos::ParameterList ?

I don't think so from looking at:

```
$ grep -inH sort packages/teuchos/parameterlist/src/Teuchos_ParameterList*
[empty]
```

Nothing about the PL requires anything to be sorted.  In fact, we put a lot of effort into making the PL and the XML reader/writer maintain the original ordering.  That is actually required by the XML standard (and I think should be required by a YAML standard as well).  It turns out that you can actually embed useful info in the ordering of sublists (e.g. I think Panzer/Drekar takes advantage of this).

**Comment by ibaned** [comment]
Yea, I'm all for order preservation. There was a sort of cop-out in jbeder/yaml-cpp#169 because somehow the YAML spec doesn't require this, but everyone who commented seems to want order preservation. By design or by accident, I think the latest master branch of `yaml-cpp` does preserve order, but 0.5.3 does not (in fact, it always reverses the PL in the test, no matter which order I write it in).

**Comment by bartlettroscoe** [comment]
> I can't reproduce the TeuchosComm_ParameterList_UnitTest_Parallel on my workstation even after using yaml-cpp version 0.5.3.

Then you will need to contact the owner of the machine dorksaber.srn.sandia.gov to give you an account so that you can reproduce this there, or ask them (or the @trilinos/framework team) to relegate this to a "Specialized" build, or disable these tests in that build so that this email spam goes away.  One way or another, these failures need to go away.

**Comment by jhux2** [comment]
@csiefer2 @brian-kelley

**Comment by brian-kelley** [comment]
haveSameValuesUnordered() does an unordered, recursive comparison of param lists. It just checks name, type, and value of each parameter. I ran the unit tests when I approved the PR last week and they passed then (on my machine with up to date yaml). As far as I know yaml and yaml-cpp never made any promise to maintain any particular ordering, and the Teuchos functions and tests were written with this in mind. I'll figure this out in the next couple of hours.

**Comment by ibaned** [comment]
Well this is fairly strange. I built on `dorksaber`, trying to use mostly the same configuration as CDash (including the `yaml-cpp` installation), and neither test fails in that build. I'll focus on fixing the one and only failure I can reproduce so far.

**Comment by ibaned** [comment]
Okay, second try at a fix for one of these tests. Replaced the exact text comparison with an `Unordered` `ParameterList` comparison. That should be resistant to these occasional reorderings. Lets see what things look like in the next CI iteration.

**Comment by ibaned** [comment]
If one looks at the pass/fail graph here:
http://testing.sandia.gov/cdash/testDetails.php?test=38287218&build=2859609
The parallel test alternates success and failure every other day. There is some non-determinism at work here.

I actually just did get it to fail once by doing `ctest -j 40`, but I haven't gotten it to happen again....

**Comment by brian-kelley** [comment]
@ibaned I think you're right about the "order" of YAML map entries being based on memory address or something else that is nondeterministic. I couldn't reproduce the failure on my machine either, even though the relevant parts of the build environment (serial build, yaml-cpp 0.5.3) are identical to dorksaber.

Edit: I also changed TwoDArrayConvert to use "haveSameValuesUnordered()" instead of comparing the expected and actual YAML strings directly. That should fix this permanently.

**Comment by ibaned** [comment]
> Edit: I also changed TwoDArrayConvert to use "haveSameValuesUnordered()" instead of comparing the expected and actual YAML strings directly. That should fix this permanently.

I think we may have independently arrived at the same fix for that test. I pushed mine to develop.

**Comment by ibaned** [comment]
I was able to trigger another non-deterministic failure and capture the output:
```
0. Teuchos_ParameterList_xmlUpdateAndBroadcast_UnitTest ... [Passed] (0.00028 sec)
1. Teuchos_ParameterList_xmlUpdateAndBroadcastNoOverWrite_UnitTest ... [Passed] (0.000183 sec)
2. YAML_MPIBroadcast_UnitTest ... [Passed] (0.000676 sec)
3. YAML_ConvertFromXML_UnitTest ... One list is missing parameter: "Problem"
One list is missing parameter: "Problem"

 Teuchos::haveSameValuesUnordered(*xmlList, *yamlList, true) = true == true = true : passed
 Teuchos::haveSameValuesUnordered(*xmlList, *yamlList, true) = true == true = true : passed
 Teuchos::haveSameValuesUnordered(*xmlList, *yamlList, true) = false == true = true : FAILED ==> /home/daibane/src/Trilinos/packages/teuchos/comm/test/ParameterList/ParameterList_yaml_Parallel.cpp:96
 Teuchos::haveSameValuesUnordered(*xmlList, *yamlList, true) = true == true = true : passed
 Teuchos::haveSameValuesUnordered(*xmlList, *yamlList, true) = true == true = true : passed
 Teuchos::haveSameValuesUnordered(*xmlList, *yamlList, true) = true == true = true : passed
 [FAILED]  (0.0211 sec) YAML_ConvertFromXML_UnitTest
 Location: /home/daibane/src/Trilinos/packages/teuchos/comm/test/ParameterList/ParameterList_yaml_Parallel.cpp:80
```

It looks like under certain conditions we lose a parameter. I suspect maybe what happens is we run out of memory, and all the `try`/`catch` stuff we have to do with `yaml-cpp` is catching a `std::bad_alloc`. Other than that its a bug.

**Comment by brian-kelley** [comment]
I think we should just avoid all file writes in the YAML unit tests. We can easily do this since we can read/write YAML lists from strings and stringstreams.

**Comment by bartlettroscoe** [comment]
Each test needs to write and read files with unique names.  Otherwise, move one of the unit tests into a subdir and that will fix this as well.

**Comment by ibaned** [comment]
As long as avoiding file I/O doesn't defeat the purpose of this test, I'd prefer switching to stringstreams. @brian-kelley would you be okay making this change ?

**Comment by bartlettroscoe** [comment]
> As long as avoiding file I/O doesn't defeat the purpose of this test, I'd prefer switching to stringstreams.

Well you need at least one test that reads a YAML file and at least one test that writes a YAML file and makes sure the behavior is correct.  I found that on some systems, you can't have the same test write a file and then read it back in again right away.  On some systems, the write is not completed before the read.  Therefore, you need one test that reads from a version controled file and makes sure the right PL is read in.  Then you need a test that writes a YAML file and then compares that file to a known good YAML file (which works great when order is maintained).  We have tests like this for the XML PL reader/writer.

**Comment by ibaned** [comment]
How about we do real file I/O in one the `teuchos/parameterlist/` tests, and switch the `teuchos/comm/ParameterList` (i.e. parallel) tests to stringstreams ? The parallel tests are the only ones that are called multiple times by CTest (one rank and N ranks).

**Comment by bartlettroscoe** [comment]
> How about we do real file I/O in one the teuchos/parameterlist/ tests, and switch the teuchos/comm/ParameterList (i.e. parallel) tests to stringstreams ? The parallel tests are the only ones that are called multiple times by CTest (one rank and N ranks).

I think you need at least one test that tests the function Teuchos::updateParametersFromYamlFileAndBroadcast() in a multi-process MPI job.  Writing an XML file should only occur on the root processor you don't need to test that in parallel (unless the code might try to write the same file from multiple processes which would be very bad).

**Comment by brian-kelley** [comment]
I've changed the parallel tests to stringstreams, and I'm getting an error where some double values (value 0) are read back as int (after XML -> YAML conversion). I know this was working before so it's probably a mistake on my end - I'll keep working on this tonight.

@bartlettroscoe It seems like there are a lot of reasons to enforce a consistent order to yaml param lists. I could actually do this, by sorting all key-value pairs by key after reading them in with the current logic.

**Comment by brian-kelley** [comment]
I agree, updateParametersFromYamlFileAndBroadcast() isn't tested anywhere currently, but testing it should be straightforward. How about I do that in teuchos/comm/test/ParameterList/ParameterList_yaml_Parallel.cpp using the existing yaml testing files.

**Comment by ibaned** [comment]
> I'm getting an error where some double values (value 0) are read back as int (after XML -> YAML conversion)

I think as part of #1181 we removed the existing formatting code to allow users more control over the formatting. That does, however, leave the default behavior such that doubles which are whole numbers get interpreted as ints by YAML.

I currently enforce correct conversion by passing `<< std::scientific` to the stream before writing YAML, I recommend you do this in the short term (and also do `std::setprecision(17)` if you want the values to be similar). Maybe we should add code to the YAML writer to check whether the stream formatting will cause a type error and if so do something simple like print `1.0` instead of `1`.

**Comment by william76** [comment]
@bartlettroscoe I've updated my list to move this test over for the Specialized track when I do the big shuffle.

**Comment by ibaned** [comment]
Once @brian-kelley 's fixes are in, we should consider moving it to a higher tier. I believe one of @bartlettroscoe 's priorities is to prevent breakage of the YAML functionality, via this testing.

**Comment by bartlettroscoe** [comment]
> Once @brian-kelley 's fixes are in, we should consider moving it to a higher tier. I believe one of @bartlettroscoe 's priorities is to prevent breakage of the YAML functionality, via this testing.

We can have this discussion after @jwillenbring documents these different testing tracks in detail so that we can select the best track.

Once we can move the standard CI build from GCC 4.7.2 to GCC 4.9.3 (see #1002), then we should be able to add yaml-cpp as a PT TPL and then the YAML functionality will be well preserved (assuming we can get people to actually run the standard CI build before they push).  Until then, it will be harder to keep the YAML build working.  The problem that lead to this issue is that the interested parties were not getting CDash emails and it failed for a while before I finally created this issue.

We will ask Kitware to add more flexible CDash email notification strategies so that people who want to get alerted about certain builds and certain packages can set up to get those.

**Comment by bartlettroscoe** [comment]
Not an issue anymore now that yaml-cpp is a PT TPL part of standard CI testing.

Closing as worksforme.

**Comment by bartlettroscoe** [comment]
So does this build need to be running anymore on dorksaber?  If not, please remove it.

**Comment by brian-kelley** [comment]
Just pushed 86eb69ffd to fix a few things. The parallel test now uses stringstreams but the serial one still uses file I/O. When writing out YAML with a std::ostream, I check the format flags to make sure that doubles will be preserved (i.e. 5.0 will always be printed with a decimal point), then restore the flags after the writing. Also, it turns out Chris Luchini wrote a test for updateYamlParametersAndBroadcast a long time ago, I just didn't see it before.
