### ISSUE TITLE
MueLu block size warning

### ISSUE THREAD

**Issue by aprokop** [trilinos/Trilinos#1269]
Per user:

I have an application that uses Tpetra + MueLu + Belos to solve linear
systems obtained via finite element assembly. To create the MueLu
preconditioner, I am using the function:
MueLu::CreateTpetraPreconditioner:

https://github.com/trilinos/Trilinos/blob/master/packages/muelu/adapters/tpetra/MueLu_CreateTpetraPreconditioner.hpp#L49

I am passing this function the required Tpetra::Operator (inA) and
input Teuchos::ParameterList (inParamList), as well as the optional
coordinate Tpetra::MultiVector (inCoords). For a problem with 3
degrees of freedom per node (linear elasticity), I specify the MueLu
input parameter "number of equations" to be equal to 3, and I see the
warning below:

```
******* WARNING *******
Setting matrix block size to 3 (value of the parameter in the list)
instead of 1 (provided matrix).
You may want to check "number of equations" (or "PDE equations" for
factory style list) parameter.
```

I am curious if anyone has experienced this before, and if the fix is
immediately obvious.

**Comment by aprokop** [comment]
This is a minor warning, and it does not pose a problem in this case. It simply indicates that after your original operator was converted to Xpetra object (Xpetra matrix, specifically) that matrix was still considered scalar on the input. You did the right thing by indicating the number of equations, and this warning means that from now on we are going to treat a scalar matrix as a block matrix.

@tawiesn 

We could certainly do a better job on phrasing the warning and finding a situation where it is necessary. When do we really want this to be a warning, and when a simple Runtime0? I feel like if we switch from scalar to block matrices through a provided "number of equations", it should not be a warning. But I also recall that there was history behind this.

**Comment by aprokop** [comment]
Per @tawiesn:


we certainly could do a better job or make the warning (or printout) more verbose.

I think we can distinguish the following scenarios:

1) The user creates the Xpetra::Matrix by hand and also sets the block size. Then, the warning would make sense if the user (accidently) overwrites the block size by a leftover "number of equations". That is, there should probably be a warning if blockSize in the matrix is > 1 and different to what is set in the xml file. Maybe there should be always a warning if the block size stored in the Xpetra::Matrix differs from what is set in the solver parameters. Not sure how easy this is. I guess "number of equations" is validated and the default is 1. So, if the user does not set it in the parameter list, we might want to ignore it (no warning, just printout?)

2) I think it is simpler if the user uses the Create{E,T}petraPreconditioner interface. Since Epetra_CrsMatrix and Tpetra::CrsMatrix have no notion of a block size, the user HAS to set it by hand in the parameter list ("number of equations"). A standard printout (instead of a warning) would probably be sufficient.

However, the Create{E,T}PetraPreconditioner routines call the general routines in CreateXpetraPreconditioner which would trigger the warning. So i am not fully sure what the best logic would be.

I think you are right: if we switch from scalar to block: just do printout
If we have some kind of block operator and the parameter "number of equations" is set (to something different) then throw a warning.

Did i forget something?

**Comment by aprokop** [comment]
I feel like the problem would go away if we knew in `CreateXpetraPreconditioner` whether it was called through `Create{E,T}petraPreconditioner` or not. If it was, we don't need a warning. If it was not, this means somebody explicitly constructed an `Xpetra` matrix.

However, this seems to be a subset of block size 1 to another block size, so we could ignore that. Are there situations where it is appropriate to trigger a warning if the block size changes from 1 to something else due to the parameter list? I think at some point I got burned by running a Laplacian with an artifact "number of equations" from a parameter list and made this a warning (Runtime is not as visible).

**Comment by tawiesn** [comment]
@aprokop The problem is: people might try to apply the same solver settings from an xml file to different scalar and blocked problems, forgetting about the "number of equations" parameter.
In fact "number of equations" belongs to the matrix properties and not to the solver settings. People might be glad if they get a warning/reminder that a specific xml file, that they used for a block system should applied to a different problem with another block size. In the best case, MueLu will crash during the aggregation. In the worst case, MueLu will solve the problem but show worse performance (just because of an accidently wrong "number of equations" parameter set in the xml file).

**Comment by aprokop** [comment]
@tawiesn But then you essentially are saying that we should always produce a warning as that is the most clear indicator! And that Runtime0/Runtime1 won't cut it because it's not as visible.

**Comment by tawiesn** [comment]
All what i'm trying to say: there might be cases where this warning can save you a lot of time avoiding unnecessary mistakes. And there are cases where people get confused by the warning.

We probably could do the following:
1) if the user is using CreateXpetraPreconditioner and sets "number of equations" (i.e. it is in the ParameterList explicitly set) then throw a warning. You should not use both the CreateXpetraPreconditioner routine and "number of equations"
2) if the user is using Create{E,T}PetraPreconditioner throw a warning if "number of equations" NOT set. We would extract "number of equations", set the block size in the Xpetra::Matrix, remove the "number of equations" paramter from the parameter list and call CreateXpetraPreconditioner.

I haven't checked the details. Would need to look at the source code whether this would work or not.
