### ISSUE TITLE
Framework: PR test machine problem?

### ISSUE THREAD

**Issue by jhux2** [trilinos/Trilinos#12732]
## Bug Report
@trilinos/framework @sebrowne 

PR testing for #12726 and #12722 are failing on ascic164 with similar errors but in unrelated packages.  Memory or disk space issue?

```
 Standard Error 	

collect2: fatal error: ld terminated with signal 9 [Killed]
compilation terminated.
[CTest: warning matched] /usr/bin/ld: warning: libgfortran.so.3, needed by /usr/lib64/liblapack.so, may conflict with libgfortran.so.5
```

**Comment by jhux2** [comment]
And #12731.

**Comment by sebrowne** [comment]
This is effectively the same issue as was first seen in https://github.com/trilinos/Trilinos/pull/12707#issuecomment-1932829501.  I'm monitoring and can confirm that some of the machines are reliably running out of disk space, and it appears to be just from our builds/tests.  Some of them have over 1TB of disk, so I think we have a problem, unless it REALLY does take that much space to build and test OpenMP + GCC + OpenMPI Trilinos.

**Comment by cgcgcg** [comment]
Is there something in particular that uses a lot of space? Or is the increase across the board on all object files?

**Comment by sebrowne** [comment]
The builds that are particularly problematic are (now that I notice it) the statically-linked ones.  So my guess is that my conclusion will be "It's just that expensive to link Trilinos statically". More specifically, I think it's that expensive to link _the tests_ statically.  I'm running a build to get a feel for how much space that build takes, and will report back.  Most likely some code change pushed the build sizes up just a little bit, and it's now running up against our hard disk sizes on some of the machines.

**Comment by sebrowne** [comment]
Yep, we are in the unfortunate position of "that build really does take over 200GB of disk space".  Static linking is a bear, to be sure.  See attached disk usage plot of my replicating PR build on one of the machines that has been running out of space.  Will need to discuss the priority of a statically-linked Trilinos (with all of its tests) with the Operational Leadership Team.  I can try to get it to place that build on only machines with larger disks for now, but no real promises that it will get better prior to discussing it and deciding on a longer-term path forwards.

![diskusage](https://github.com/trilinos/Trilinos/assets/22149837/4cbbbd7d-9b0a-4249-913c-206d16f03503)

**Comment by jhux2** [comment]
```
6.8G    amesos2
9.2G    anasazi
28G     belos
21G     ifpack2
5.4G    intrepid
23G     intrepid2
9.8G    ml
15G     stratimikos
35G     teko
5.2G    teuchos
5.5G    thyra
56G     tpetra
6.8G    xpetra
```

Is that all? ;p

**Comment by jhux2** [comment]
Would it be ok to temporarily disable the static PR build?

**Comment by sebrowne** [comment]
> Would it be ok to temporarily disable the static PR build?

I'd like to avoid that at all costs if we intend to keep caring about it.  I'm going to try and assign those builds to a specific machine to keep them from running out of space temporarily.

**Comment by rppawlo** [comment]
Is that big memory jump due to the kokkos update? If so I think they would care about a regression of that magnitude.

**Comment by sebrowne** [comment]
I can try to bisect it.  My gut feeling is no, but it may have been the straw so to speak.  I'll check out a version from a month ago and compare the on-disk size and report back tomorrow.

**Comment by ndellingwood** [comment]
> Is that big memory jump due to the kokkos update? If so I think they would care about a regression of that magnitude.

@rppawlo the kokkos update was a patch release consisting primarily of bug fixes and patch matches of PRs made to Trilinos, the changes were pretty minimal compared to what was already in Trilinos with 4.2.00, it wouldn't make sense to me that the patch release would trigger a large spike in memory usage.

**Comment by sebrowne** [comment]
Aaaaand one of them is running out again (will likely affect https://github.com/trilinos/Trilinos/pull/12739)

**Comment by sebrowne** [comment]
I did some VERY brief additional triage for the `-g` flag, and it appears we are enabling `Trilinos_ENABLE_DEBUG_SYMBOLS` in all PR builds.  Which is (in my opinion) completely inappropriate.  My guess is that the prior behavior in Kokkos actually _fixed_ this issue (or at least, hid it).  I will triple-check tomorrow morning, but if that shrinks the builds enough, I'll make the change immediately.  Thank you so much for the triage help @ndellingwood !

**Comment by ndellingwood** [comment]
@sebrowne excellent, thanks for the triage and update! 

I tested a build with the kokkos master branch (i.e. 4.2.01) and reverted the change that dropped Kokkos' setting of Trilinos CMAKE_CXX_FLAGS:
```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 4a4e7a5..d20b3c8 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -252,6 +252,7 @@ ENDIF()
 # subpackages
 
 ## This restores the old behavior of ProjectCompilerPostConfig.cmake
+# It sets the CMAKE_CXX_FLAGS globally to those used by Kokkos
 # We must do this before KOKKOS_PACKAGE_DECL
 IF (KOKKOS_HAS_TRILINOS)
   # Overwrite the old flags at the top-level
@@ -279,13 +280,21 @@ IF (KOKKOS_HAS_TRILINOS)
     SET(KOKKOSCORE_XCOMPILER_OPTIONS "${KOKKOSCORE_XCOMPILER_OPTIONS} -Xcompiler ${XCOMP_FLAG}")
     LIST(APPEND KOKKOS_ALL_COMPILE_OPTIONS -Xcompiler ${XCOMP_FLAG})
   ENDFOREACH()
+  SET(KOKKOSCORE_CXX_FLAGS "${KOKKOSCORE_COMPILE_OPTIONS} ${KOKKOSCORE_XCOMPILER_OPTIONS}")
   IF (KOKKOS_ENABLE_CUDA)
     STRING(REPLACE ";" " " KOKKOSCORE_CUDA_OPTIONS    "${KOKKOS_CUDA_OPTIONS}")
     FOREACH(CUDAFE_FLAG ${KOKKOS_CUDAFE_OPTIONS})
       SET(KOKKOSCORE_CUDAFE_OPTIONS "${KOKKOSCORE_CUDAFE_OPTIONS} -Xcudafe ${CUDAFE_FLAG}")
       LIST(APPEND KOKKOS_ALL_COMPILE_OPTIONS -Xcudafe ${CUDAFE_FLAG})
     ENDFOREACH()
+    SET(KOKKOSCORE_CXX_FLAGS "${KOKKOSCORE_CXX_FLAGS} ${KOKKOSCORE_CUDA_OPTIONS} ${KOKKOSCORE_CUDAFE_OPTIONS}")
   ENDIF()
+  # Both parent scope and this package
+  # In ProjectCompilerPostConfig.cmake, we capture the "global" flags Trilinos wants in
+  # TRILINOS_TOPLEVEL_CXX_FLAGS
+  SET(CMAKE_CXX_FLAGS "${TRILINOS_TOPLEVEL_CXX_FLAGS} ${KOKKOSCORE_CXX_FLAGS}" PARENT_SCOPE)
+  SET(CMAKE_CXX_FLAGS "${TRILINOS_TOPLEVEL_CXX_FLAGS} ${KOKKOSCORE_CXX_FLAGS}")
+  #CMAKE_CXX_FLAGS will get added to Kokkos and Kokkos dependencies automatically here
   #These flags get set up in KOKKOS_PACKAGE_DECL, which means they
   #must be configured before KOKKOS_PACKAGE_DECL
   SET(KOKKOS_ALL_COMPILE_OPTIONS
```

The tpetra/core/tests build size dropped from 2.5G back down to 224M, so some combo of that change along with allowing the `-g` flag to be added to compilation resulted in the build size blow up.

@sebrowne Hopefully the change to `Trilinos_ENABLE_DEBUG_SYMBOLS` to drop discontinue use of `-g` in the OpenMP build is sufficient to get things back on track, fingers crossed!

**Comment by ndellingwood** [comment]
@sebrowne one more bit of good news, adding the cmake option you suggested ` -DTrilinos_ENABLE_DEBUG_SYMBOLS=OFF` reduced the `tpetra/core/tests` build size back down to 224M (no changes to Trilinos or Kokkos), so that change should get the OpenMP PR build back to normal

**Comment by sebrowne** [comment]
I feel comfortable declaring that this is what was compounding to cause the size explosion.  See #12742

**Comment by jhux2** [comment]
@sebrowne and @ndellingwood Thank you both for tracking this down!

**Comment by sebrowne** [comment]
Confirmed fixed
