### ISSUE TITLE
KLU2 is considerably slower than KLU on small matrices

### ISSUE THREAD

**Issue by CamelliaDPG** [trilinos/Trilinos#1274]
We are seeing as much as a 20x performance difference between KLU and KLU2 (using Epetra objects with the former, Tpetra with the latter) on a 1448x1448 matrix solve with 15716 nonzeros.  If we use KLU2 with Epetra matrices and vectors, the slowdown is 5x instead.  Have sent details (including a driver and matrix file) to @ndellingwood.  @trilinos/amesos2

**Comment by srajama1** [comment]
Thanks for sending the files. Is this serial run ?

**Comment by CamelliaDPG** [comment]
Yes, this is a serial run.  In the example driver I used for the timings, I'm just calling Amesos2::Solver::solve() and Amesos_Klu::Solve(), with no explicit calls to symbolicFactorization() or numericFactorization().  solve() is called repeatedly on the same Solver object (with unchanged matrix), so I presume that factorization done within the first call to solve() will be reused.

The case in which we encountered this was within MueLu vs ML--we are refactoring some code to move to a newer Trilinos stack (MueLu/Belos/Tpetra in place of ML/Aztec).  It looks to me like MueLu::Amesos2Smoother is also just calling Amesos2::Solver::solve() rather than making any explicit calls to numericFactorization() or symbolicFactorization().

**Comment by srajama1** [comment]
In principle just calling Amesos2::Solver::solve() is a convenience for naive users. I would recommend changing it to call all three calls separately. Then we can optimize for the cases where symbolic structure of the matrix changes, numeric values have changed, and vector entries have changed. 

That said this may not be the issue in this case as you are doing it for one solve.

@jhux2

**Comment by jhux2** [comment]
@CamelliaDPG Is the AMG preconditioner being completely rebuilt each time? I agree that reuse is ultimately what the application should strive for.  But right now, depending on how @CamelliaDPG responds,  I'd say the current usage is a fair comparison between ML and MueLu.

@srajama1 In MueLu, the Amesos2 solver is constructed first during multigrid setup with this call
```
prec_ = Amesos2::create<Tpetra_CrsMatrix,Tpetra_MultiVector>(type_, tA);
```
where ```type_``` is ```Klu```.  I assume the create does the numeric factorization?

**Comment by srajama1** [comment]
No, create just create the solver. Think of it as initialization. When solve is called later it sees numeric factorization is not done, so it does it.

From my understanding, this is a fair comparison. There is something odd in Epetra vs Tpetra. They both do the exact same things like construct importers and import a matrix. The other portion is KLU vs KLU2. They are almost identical in functionality. My gut feeeling this is again overhead cost somewhere outside the solver itself.

**Comment by CamelliaDPG** [comment]
@jhux2, in the refactor that instigated the issue, the AMG preconditioner is built once and reused.  In the sample driver, I'm using Amesos/Amesos2 directly (MueLu/ML are not involved).  There, for Amesos I use the constructor Amesos_Klu(EpetraLinearProblem) and for Amesos2 I use Amesos2::create().

**Comment by ndellingwood** [comment]
The following sequence of messages report comparisons of performance before/after optimizations to the KLU2 interface in Amesos2 using the provided driver code (with slight modifications):

System: kokkos-dev with sems-env and Trilinos configuration similar to @CamelliaDPG (Trilinos_DEBUG disabled)
1. Small matrix with reused symbolic and numeric factorization results after initial run 

System: hansen test-bed: no sems-env, minimal Trilinos configuration
1. Small matrix with reused symbolic and numeric factorization results after initial run 
2. Large matrix with reused symbolic and numeric factorization results

**Comment by ndellingwood** [comment]
kokkos-dev with sems-env and @CamelliaDPG Trilinos configuration:

Small matrix (nrows = 1448,  nnz = 17344)
10000 solves
Initial run:
```
Timer Name                                  Global time (num calls)
--------------------------------------------------------------------------------
KLU                                         0.4 (1e+04)
KLU2                                       5.99 (1e+04)
KLU2Epetra                            3.42 (1e+04)
```
* The results reflect the performance difference initially reported by @CamelliaDPG ; here 15x difference between KLU2+Tpetra vs KLU, and 8.5x difference between KLU2+Epetra vs KLU

After KLU2 optimizations:
```
Sample 1:
KLU                                         0.31 (1e+04)
KLU2                                       0.33 (1e+04)
KLU2Epetra                            0.39 (1e+04)

Sample 2:
KLU                                         0.41 (1e+04)
KLU2                                       0.37 (1e+04)
KLU2Epetra                            0.33 (1e+04)

Sample 3:
KLU                                         0.38 (1e+04)
KLU2                                       0.39 (1e+04)
KLU2Epetra                            0.36 (1e+04)

Sample 4:
KLU                                         0.26 (1e+04)
KLU2                                       0.38 (1e+04)
KLU2Epetra                            0.35 (1e+04)
```

* I posted a few samples because there was some inconsistency/jitter when testing with smaller matrix.

**Comment by ndellingwood** [comment]
Hansen testbed (Haswell CPU) without sems-env, minimal Trilinos configuration (Amesos + KLU, Amesos2 + KLU2, Epetra, Tpetra)

Small matrix (nrows = 1448, nnz = 17344)
10000 solves
Initial run:
```
Timer Name                                  Global time (num calls)
--------------------------------------------------------------------------------
KLU                                         0.46 (1e+04)
KLU2                                        1.41 (1e+04)
KLU2Epetra                                  1.18 (1e+04)
```

After KLU2 optimizations:
```
Sample 1:
KLU                                         0.66 (1e+04)
KLU2                                        0.79 (1e+04)
KLU2Epetra                                  0.8 (1e+04)

Sample2:
KLU                                         0.37 (1e+04)
KLU2                                        0.58 (1e+04)
KLU2Epetra                                  0.44 (1e+04)

Sample 3:
KLU                                         0.56 (1e+04)
KLU2                                        0.58 (1e+04)
KLU2Epetra                                  0.54 (1e+04)

Sample 4:
KLU                                         0.5 (1e+04)
KLU2                                        0.48 (1e+04)
KLU2Epetra                                  0.5 (1e+04)
```

**Comment by ndellingwood** [comment]
Hansen testbed (Haswell CPU) without sems-env, minimal Trilinos configuration (Amesos + KLU, Amesos2 + KLU2, Epetra, Tpetra)

Larger matrix (nrows = 682712, nnz = 2329176) 
1000 solves
Initial run:
```
Timer Name                                  Global time (num calls)
--------------------------------------------------------------------------------
KLU                                         19.56 (1000)
KLU2                                        39.84 (1000)
KLU2Epetra                                  37.05 (1000)
```

After KLU2 optimizations:
```
Sample 1:
KLU                                         19.34 (1000)
KLU2                                        18.81 (1000)
KLU2Epetra                                  18.72 (1000)

Sample 2:
KLU                                         18.63 (1000)
KLU2                                        18.29 (1000)
KLU2Epetra                                  18.04 (1000)

Sample 3:
KLU                                         18.57 (1000)
KLU2                                        18.07 (1000)
KLU2Epetra                                  17.93 (1000)

Sample 4:
KLU                                         18.73 (1000)
KLU2                                        18.4 (1000)
KLU2Epetra                                  18.31 (1000)
```

**Comment by CamelliaDPG** [comment]
Thanks, @ndellingwood!  Those performance numbers are excellent.  I look forward to trying this out in my code.

**Comment by ndellingwood** [comment]
@CamelliaDPG Running some checkin testing now, will let you know when it goes into develop

**Comment by ndellingwood** [comment]
checkin script showed I broke a couple MueLu tests with my changes, working on finding and fixing.

**Comment by ndellingwood** [comment]
Oops, I was running local tests and did not rebase my branch since the fixes discussed in issue #1290. Likely this goes away once I squash commits, rebase, and --do-all checkin tests.

**Comment by ndellingwood** [comment]
Checkin test passed with changes shown in  	f1d42c1 (but rebased to develop and tested from there); commit pushed to develop branch via checkin script, sha f0a836e8254bd11bffb8a9f3caff64128752fc57

**Comment by srajama1** [comment]
Can we check and close this ?

**Comment by CamelliaDPG** [comment]
Sounds good to me.  Thanks @ndellingwood and @srajama1!
