### ISSUE TITLE
Check for Trilinos_ENABLE_OpenMP if Kokkos/Tpetra need OpenMP

### ISSUE THREAD

**Issue by aprokop** [trilinos/Trilinos#1277]
Trilinos should complain during configure if `Kokkos_ENABLE_OpenMP=ON` or `Tpetra_INST_OPENMP=ON` but `Trilinos_ENABLE_OpenMP` is off.

Otherwise, it fails during compilation of Kokkos along the lines of your compiles does not support OpenMP or something like that with no indication of how to fix it.

**Comment by mhoemmen** [comment]
Just pushed a fix; thanks @aprokop !
