### ISSUE TITLE
Supported CUDA version for Trilinos

### ISSUE THREAD

**Issue by tawiesn** [trilinos/Trilinos#1278]
When porting Trilinos kernels to Kokkos what CUDA versions shall be supported (specifically Cuda 7.5 or Cuda 8)?
For example, support for lambdas in Cuda 7.5 seems extremely limited. (see, e.g., https://github.com/kokkos/kokkos/issues/763)
Is there a Trilinos-wide decision?
@trilinos/tpetra @trilinos/muelu @trilinos/xpetra @jhux2 @mhoemmen

**Comment by mhoemmen** [comment]
Hi @tawiesn !  We've had conversations about this for a while over e-mail.  It's not my place to make this decision for all of Trilinos.

@csiefer2 requested that Trilinos come to an agreement on CUDA version requirements.  He proposes the following requirement:

"With default build options for CUDA, all Trilinos code must build and pass tests with CUDA 7.5 as long as Titan is in operation."

("Default build options" here could include the `__device__` lambda option, which Kokkos enables by default even with CUDA 7.5.)

It's not my place to make this decision for all of Trilinos.  Whatever we decide, we should be aware that `__host__ __device__` lambdas only work with Kokkos for CUDA >= 8.0.  Kokkos only supports  `__device__` lambdas with CUDA 7.5.  In practice, a CUDA 7.5 requirement would prevent use of `KOKKOS_LAMBDA` with the host execution space.  This forces one of the following options:

  1. Code using lambdas with Kokkos needs two separate code paths for host vs. GPU.
  2. Code cannot use lambdas with Kokkos, unless explicitly for host execution spaces only.
  3. Code cannot build for both host and GPU in the same build (e.g., enable both Cuda and Serial Node types in Trilinos).

If we don't want to impose these constraints, then we need to require CUDA >= 8.0.  Whatever we decide, we should decide _something_.  This has to be Trilinos-wide, at least among those packages that depend on Kokkos.

**Comment by ibaned** [comment]
One thing I'd like to add for consideration is the long-term design impact of the decision made. Suppose we elect not to use lambdas or to always have two separate code paths. Once CUDA 7.5 stops being a requirement, we will have a big code refactoring to undertake. I would also append to @csiefer2 's statement "as long as Titan is in operation and it only supports CUDA 7.5". The situation on Titan is reminiscent of the situation on Blue Gene/Q, where the requirement of GCC 4.7.2 was finally lifted with the help of `bgclang`. I hope a similar thing can be done for Titan, and I hope future hardware acquisitions will include a longer-term commitment to adopt new compilers.

Being realistic though, I think the most likely options are (1) don't use lambdas yet or (2) if users want to run the same kernel in both host and device execution spaces then they need CUDA 8.0

**Comment by nmhamster** [comment]
Guys, we expect ORNL to complete the migration to Summit in mid/late 2018. This will not run CUDA7.5. So you could plan around that?

**Comment by csiefer2** [comment]
Folks are writing functor code every day that will need to get rewritten w/ lambdas.  I just want to call "stop" right now and have everything lambda from here on out (with some #ifdef sorcery to protect Titan until next year).

**Comment by mhoemmen** [comment]
@csiefer2 wrote:
> Folks are writing functor code every day that will need to get rewritten w/ lambdas. I just want to call "stop" right now and have everything lambda from here on out (with some #ifdef sorcery to protect Titan until next year).

Just to clarify for other folks: I am in favor of a pro-CUDA-8.0 approach; I'm just playing devil's advocate.  We do have to make a conscious decision whether to support Titan.  Sierra has already decided to require CUDA >= 8.0, according to @mwglass .  I would like to know if Trilinos plans to have the same requirement.  @maherou , what should we do?

**Comment by ibaned** [comment]
It sounds from @nmhamster and @csiefer2 that even if we do need to support CUDA 7.5 it should be limited to a timeframe of one year and apply only to existing code, with new features possibly residing within some `#ifdef CUDA8`.

**Comment by csiefer2** [comment]
Talked with @bmpersc.  How do we want the version check in our packages.  There are a few ideas.

1. Macros like CUDA8, CUDA9, etc.  Downside: Maintenance cost for framework team (every time there is a new CUDA).
2. Tests for individual features (e.g. CUDA_HAVE_DEVICE_LAMBDA).  Downside:  We don't generally do feature support tests for anything else.
3.  Version number in a variable like CUDA_VERSION (so we do stuff like #if CUDA_VERSION > 30200).  This is how GCC version macros work.  Downside:  Could generate ugly code in Trilinos package.

Personally, I like #3.  Thoughts?

**Comment by ibaned** [comment]
I've created kokkos/kokkos#1019 to propose that Kokkos provide this preprocessor symbol definition for Trilinos to check.

**Comment by csiefer2** [comment]
I'd like to vote against relying on Kokkos for this, because we'd have to wait for the next Kokkos snapshot to use it...

**Comment by ibaned** [comment]
We can aways add the patch directly to the Trilinos copy of Kokkos for urgent things, we've done this a lot in the past. I've already drafted some of the changes.

Kokkos is supposed to be somewhat responsible for handling this kind of CUDA stuff, I'd prefer that over every Trilinos package directly checking some `_CUDACC_VER_` thing.

You want your package to require just lambdas on the device, or lambdas that work on both host and device?

If you want a configure-time check, the easiest thing is probably to have CMake try compiling a test program, because most of the information seems to be in preprocessor macros. We can also put this in the Kokkos CMake files.

**Comment by csiefer2** [comment]
What you propose is effectively Option 2 from above.  If lambdas are the only thing we're ever going to do this check for, then this is fine.  But it might become unwieldy if we need to start checking for more stuff.


Once we require CUDA8 (next year), I want to be able to say "No device lambdas == No CUDA Node Compilation."  For now, we'll have some (non-device) fallback code that will work correctly.

**Comment by mhoemmen** [comment]
Mainly I want somebody to tell us what the requirements are.  The only application that has actually imposed a requirement is Sierra, which tests with CUDA 8.0.  Are there applications running on Titan that need CUDA 7.5 to work?  @rppawlo , would you happen to know?

**Comment by csiefer2** [comment]
Albany on Titan

**Comment by mhoemmen** [comment]
I just sent an e-mail to @ikalash to ask about Albany requirements.

**Comment by ikalash** [comment]
Tagging @jewatkins, the primary person who is running / developing CUDA code these days.  We are not currently running Albany on Titan GPUs and haven't in awhile.  @jewatkins and I were not planning to run on Titan + GPUs b/c they are old (K20s) but rather wait till CY2018 for access to the new ORNL machine, Summit.  I imagine that one will have support for CUDA >= 8.0.  @mperego, as the PISCEES2 Sandia lead, do you agree with the plan to wait for Summit?  I imagine we will try to get an allocation there?

**Comment by jhux2** [comment]
> Tagging @jewatkins, the primary person who is running / developing CUDA code these days. We are not currently running Albany on Titan GPUs and haven't in awhile. @jewatkins and I were not planning to run on Titan + GPUs b/c they are old (K20s) but rather wait till CY2018 for access to the new ORNL machine, Summit. I imagine that one will have support for CUDA >= 8.0. @mperego, as the PISCEES2 Sandia lead, do you agree with the plan to wait for Summit? I imagine we will try to get an allocation there?

Wait, does this mean not worrying about maintaining backwards compatibility for 7.5 on Titan?  @csiefer2

**Comment by mhoemmen** [comment]
I e-mailed @maherou to ask if applications besides Albany need the latest version of Trilinos, and need to run on Titan.

**Comment by ikalash** [comment]
@jhux2 : I would say yes, we don't need to worry about CUDA + Titan, but I will confirm this Monday when we have a PISCEES2 project meeting.  I would be extremely surprised if any other application in Albany besides FELIX ever ran on Titan.  @ibaned , can you please confirm?

**Comment by mhoemmen** [comment]
@tawiesn , would you happen to know if your colleagues at TUM need CUDA 7.5?

**Comment by maherou** [comment]
It would be prudent to ping at least one Titan and Tpetra users.  Tom Evans leads the ExaSMR project for ECP.  He might be able to inform our choices.  I will forward this thread to him.

**Comment by mhoemmen** [comment]
@rppawlo says, "The higher the CUDA version the better," and "... using lambdas pretty heavily."

**Comment by jwillenbring** [comment]
The xSDK, of which Trilinos is a part, builds on Titan, but the current target build I don't believe uses CUDA. I can't speak for future plans specifically. The modules loaded currently are:

module load modules
module swap PrgEnv-pgi PrgEnv-gnu
module swap gcc gcc/5.3.0
module load cmake3
module load cray-hdf5-parallel/1.8.14
module load mercurial

**Comment by sphamil** [comment]
I'll speak on behalf of Tom Evans.  I don't think we have an objection to Trilinos requiring CUDA 8.  We use Trilinos, but we don't use the CUDA implementation currently.  Our GPU-capable routines are currently using raw CUDA with the linear algebra done on the CPU.  Hopefully we'll be moving to a Kokkos implementation at some point, but it's not likely during Titan's lifetime.  So don't hold back on our account, I know the lambda support will greatly simplify things for you guys.  Thanks @maherou for including us in the discussion.

**Comment by sphamil** [comment]
Also, in case it's potentially relevant for the decision making, the SciComp group at ORNL seems pretty optimistic that they'll have CUDA 8 on Titan by the end of the calendar year, so it might not be an issue for Titan's entire life.  It sounds like Nvidia is stepping up and trying to help with the upgrade even if Cray doesn't help out.

**Comment by ibaned** [comment]
@mperego also told me today that PISCEES2 doesn't need CUDA 7.5 either, so Albany isn't an issue either

**Comment by mhoemmen** [comment]
Thanks @sphamil !  It's super helpful to know this.

Trilinos folks: Do we just want to assume CUDA 8.0, or do we want a more formal process, like a release or tag that marks the last promise of CUDA 7.5 support?

**Comment by tawiesn** [comment]
@mhoemmen 

> @tawiesn , would you happen to know if your colleagues at TUM need CUDA 7.5?

They certainly want to use Kokkos at some point. As far as i know there are no specific constraints with respect to the CUDA version (the newer the better, i guess).

**Comment by tawiesn** [comment]
@mhoemmen 

> Trilinos folks: Do we just want to assume CUDA 8.0, or do we want a more formal process, like a release or tag that marks the last promise of CUDA 7.5 support?

I would vote for something formal. This is certainly an important information for external users of Trilinos which CUDA version they need. There should be a place, where the exact minimum version requirements for CUDA (and also other TPLs are listed). I think we had already discussions about this at some TUG meetings.

**Comment by mhoemmen** [comment]
Just to clarify, "formal" means "a release or tag that marks the last release supporting CUDA 7.5."  That's different than just stating the CUDA version requirement explicitly.  We should always do the latter :-) .

**Comment by mhoemmen** [comment]
Discussion at the Trilinos leaders meeting last week suggests that Trilinos developers intend the following:

  - Trilinos must build and pass tests with CUDA 7.5 until the next minor version release.
  - Trilinos developers may require CUDA >= 8.0 for new features, but must use `CUDA_VERSION` to disable building and testing those features if CUDA >= 8.0 is not available.
  - After the next minor version release, Trilinos will require CUDA >= 8.0.

@maherou, @jhux2, @csiefer2, is that accurate?  If not, please feel free to reopen this issue.  Thanks all!
