### ISSUE TITLE
Piro: Optional vs. Required Dependencies for Tpetra and Teko

### ISSUE THREAD

**Issue by sebrowne** [trilinos/Trilinos#12799]
## Bug Report
There's no Piro team, so I'm tagging @kliegeois since I think he did the most work on this package last?
Also tagging @trilinos/tpetra and @trilinos/teko since they are the related packages.

### Description
The way the Piro code is currently written, Teko and Tpetra are required dependencies.  I see two ways to fix this:

1. Correct the `#ifdef`s in Piro to correspond with the values of `HAVE_PIRO_TPETRA` and `HAVE_PIRO_TEKO`
2. Move the optional dependencies to required dependencies.  The code appears to assume that if ROL is enabled, Tpetra is as well, and if Tempus is enabled, then Teko is as well.  That's a bit hairy, since Teko is still technically optional, but it's required if Tempus is on.  ROL is a required dependency, so Tpetra most likely should be as well.  I did this change and it does fix the compile failures, but again is not perfectly descriptive of the dependency chain.

NOTE: This is holding up our ability to integrate 15.1.X into Spack, since their CI caught the bug (see https://github.com/spack/spack/pull/42996).  We need this fixed on both `develop` and `trilinos-release-15-1-branch` in order to release a 15.1.1 that doesn't have the bug.

### Steps to Reproduce
1. SHA1:  develop
4. Configure script:
```
cmake -G Ninja \
-DTrilinos_ENABLE_ALL_PACKAGES=OFF \
-DTrilinos_ENABLE_ALL_OPTIONAL_PACKAGES=OFF \
-DTrilinos_ENABLE_Piro=ON \
-DTrilinos_ENABLE_ROL=ON \
-DTrilinos_ENABLE_Tempus=ON \
-DTrilinos_ENABLE_Teko=OFF \
-DTrilinos_ENABLE_Tpetra=OFF \
```

You don't strictly need the Teko and Tpetra disables, but I added them so that they're toggle-able to demonstrate it working vs. breaking.

**Comment by cgcgcg** [comment]
@ikalash

**Comment by ccober6** [comment]
![Dependencies](https://github.com/trilinos/Trilinos/assets/19675338/3fd574af-59fb-4d4f-99a9-97d738fecbae)

Here is the Piro dependency DAG.

**Comment by ikalash** [comment]
I feel like the Tpetra dependency being mandatory makes sense.  We should be able to build w/o Teko however.  What do other folks think about this?  There's also an Epetra dependency, though it's not being used much (at all?) these days.

**Comment by mperego** [comment]
I agree that it's probably OK to have Tpetra as a required dependency. As for Teko, I think we can make it optional easily, even if Tempus is enabled. @sebrowne, why don't we make Tpetra and Teko required dependencies for now, so that you can move forward with the Spack integration. Next time @kliegeois  or I work on Piro, we'll look into making Teko optional.

**Comment by ccober6** [comment]
@trilinos/piro

**Comment by sebrowne** [comment]
I misspoke :( ROL is NOT a required dependency of Piro the way it is now.  So the Tpetra issue isn't an issue if ROL is disabled, putting it in the same boat as Teko.

I will submit a PR with Tpetra and Teko being required, as long as we're okay with that not being exactly representative of the truth (but it will fix the compile errors).

**Comment by mperego** [comment]
> I will submit a PR with Tpetra and Teko being required

Yes, please go ahead. Thanks!

**Comment by sebrowne** [comment]
PRs are open, and I will have to change the Spack PR as well to reflect the new dependencies.  Will do that once we have a 15.1.1.

**Comment by mperego** [comment]
@sebrowne can we close this issue?
