### ISSUE TITLE
MueLu broken under cuda and maybe others

### ISSUE THREAD

**Issue by bathmatt** [trilinos/Trilinos#1279]
make[2]: *** [packages/muelu/src/CMakeFiles/muelu.dir/Utils/ExplicitInstantiation/MueLu_GeneralGeometricPFactory.cpp.o] Error 2

          detected during instantiation of "void MueLu::GeneralGeometricPFactory<Scalar, LocalOrdinal, GlobalOrdinal, Node>::BuildP(MueLu::GeneralGeometricPFactory<Scalar, LocalOrdinal, GlobalOrdinal, Node>::Level &, MueLu::GeneralGeometricPFactory<Scalar, LocalOrdinal, GlobalOrdinal, Node>::Level &) const [with Scalar=double, LocalOrdinal=int, GlobalOrdinal=int, Node=EpetraNode]"
(127): here

/home/mbetten/Trilinos/Trilinos/packages/teuchos/core/src/Teuchos_RCP.hpp(288): error: a value of type "Xpetra::Map<int, int, KokkosClassic::DefaultNode::DefaultNodeType> *" cannot be used to initialize an entity of type "const Xpetra::Map<int, int, Xpetra::EpetraNode> *"

**Comment by bathmatt** [comment]
Looks like it is line 830 of Trilinos/packages/muelu/src/Transfers/GeneralGeometric/MueLu_GeneralGeometricPFactory_def.hpp

**Comment by tawiesn** [comment]
Thanks @bathmatt for reporting. @jhux2 is already looking into it. The fix should be trivial.

**Comment by tawiesn** [comment]
@jhux2 There are probably more problems (i saw some errors related to mixing up SC and LO (which causes problems for std::complex), as well as mixing up default Node types)

**Comment by jhux2** [comment]
> Looks like it is line 830 of Trilinos/packages/muelu/src/Transfers/GeneralGeometric/MueLu_GeneralGeometricPFactory_def.hpp

@bathmatt Thanks for the line number, that makes my life easier.  A call is missing a template argument.  I'll merge this into the other fixes I'm working on.

**Comment by jhux2** [comment]
@bathmatt Commit 94df634 should fix this.  Let me know if it does not.

**Comment by jhux2** [comment]
@lucbv is looking at the unit test itself.  The coordinate vectors there should always be of type ```double```, rather Scalar, which could be ```std::complex<double>``` or even something stranger.

**Comment by lucbv** [comment]
@jhux2 @bathmatt , I pushed a first commit on Friday [604353e](https://github.com/trilinos/Trilinos/commit/604353ebb007bf44923747625639e48f5ce0f7fc) that should fix issues in GeneralGeometricPFactory and I just pushed another one to fix some more issues in MueLu_PerfUtils

**Comment by lucbv** [comment]
It seems that the fixes are satisfactory so I am closing this issue.
