### ISSUE TITLE
MueLu: build errors when enabling MueLu_ENABLE_Kokkos_Refactor

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#128]
@trilinos/muelu 

When I enable MueLu_ENABLE_Kokkos_Refactor, I get build errors:

.../Trilinos/packages/muelu/src/Graph/MueLu_Aggregates_kokkos_def.hpp:111:51: error: no member named 'getLocalView' in 'Xpetra::Vector<int, int, int,
      Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Threads, Kokkos::HostSpace> >'
      auto procWinner   = procWinner_  ->template getLocalView<DeviceType>();
                          ~~~~~~~~~~~             ^
.../Trilinos/packages/muelu/src/Graph/MueLu_Aggregates_kokkos_def.hpp:110:51: error: no member named 'getLocalView' in 'Xpetra::Vector<int, int, long
      long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Threads, Kokkos::HostSpace> >'
      auto vertex2AggId = vertex2AggId_->template getLocalView<DeviceType>();

The only reason I'm trying this is that I would like to enable the Xpetra vs. Epetra vs. Tpetra vs. Kokkos fill benchmark, mentioned in Issue #118.  However, the benchmark is only enabled if MueLu_ENABLE_Kokkos_Refactor is ON.

**Comment by aprokop** [comment]
Mark, you need to enable Kokkos Redactor in Xpetra too.

**Comment by aprokop** [comment]
I pushed a commit to MueLu that now throws an error if one forgot to enable Xpetra's Kokkos Refactor.

**Comment by mhoemmen** [comment]
Thanks Andrey!  Hope I'm not being a pest!  Does the example in question actually require the Kokkos refactor versions of Xpetra and MueLu?  Could I guard the parts of it that do with macros?

**Comment by aprokop** [comment]
On the contrary, I'm thankful to you for reporting these issues. It is much better to catch these things earlier.

The test really only requires Xpetra Kokkos Refactor, as getLocalMatrix in Xpetra is hidden behind the guard. The reason you need MueLu Kokkos Refactor is simply because the directory I put the test in is guarded by that. Feel free to copy the test to Tpetra if needed.
