### ISSUE TITLE
Need clarification on netcdf

### ISSUE THREAD

**Issue by VictorEijkhout** [trilinos/Trilinos#12854]
I'm failing to build with netcdf. Probaby part of the problem is that I don't know which netcdf library to load.

1. There is netcdf version 4.9 or so, which can be built sequentially or parallel
2. There pnetcdf out of the parallel-netcdf project.

Which of these three are you expecting?

See also https://github.com/trilinos/Trilinos/issues/12779

**Comment by ccober6** [comment]
@gsjaardema

**Comment by VictorEijkhout** [comment]
Note that I only supply 
```
 -D TPL_ENABLE_Netcdf:BOOL
```
but the cmake output has:
```
Trilinos_DEFINED_TPLS='MKL;[stuff];HDF5;CGNS;Pnetcdf;Netcdf;
```

Does that mean that you are looking for both sequential 4.9 and pnetcdf 1.12 or so?

Also, the fact that you list hdf5 means that you want the sequential version?

Victor.

**Comment by VictorEijkhout** [comment]
See https://github.com/trilinos/Trilinos/issues/12857
