### ISSUE TITLE
Thyra: Add support for user extensible InArgs and OutArgs on ModelEvaluator

### ISSUE THREAD

**Issue by rppawlo** [trilinos/Trilinos#1285]
Some years ago, Eric Cyr had suggested an extension to the ModelEvaluator to allow users to extend the InArgs and OutArgs objects without modifying the core objects for each new type. We would like to add this to the ModelEvaluator for Tempus for handling mass matrices under IMEX

@eric-c-cyr @ccober6 @bartlettroscoe 
@trilinos/thyra

**Comment by bartlettroscoe** [comment]
An alternative is to add a PL object to the InArgs and OutArgs to allow complete flexibility in extending these.   That was in the plans many years ago now documented in the backlog list:

* https://docs.google.com/document/d/1hKAcFSK6uZi5DunoofvKmNcdBBT1z64MHSBZh6ctm9U/edit#bookmark=id.v21prgsgz2ye

There are pros and cons to the more typesafe approach Eric suggested but I think adding PLs to these is a good idea since it provides 100% flexibility at runtime.  We just need to caution people to not get too crazy with these PLs since they have no compile-time checking at all.

**Comment by rppawlo** [comment]
We have been working to strip ParameterLists out of our code where ever possible. The main issue is that it is much harder for users of our libraries to figure out what is really required without going into an object's definition and looking for a validated list or trying to find all uses of get(). I do like the ParameterList and there are places where it is very useful - as in setting options for a library, but for certain APIs that require concrete objects, we have tried to get away from them. It's extra code for validation too. In discussing this with some others, I think since the ME is already so complex, it is much clearer to users to have a concrete object to grab. I'm open to adding either or both methods. Any others have opinions - @eric-c-cyr @etphipp @bathmatt @agsalin @ccober6 @dridzal ?

**Comment by bartlettroscoe** [comment]
I think you need the PL objects in the InArgs and OutArgs to allow for quick prototyping of new ideas for for passing very specialized or crazy or very specialized types of data.  I don't remember Eric's proposal but the fact that InArgs and OutArgs are currently managed as value object, straightforward extension mechanisms using inheritance will not work.  Therefore, you would need to register additional extensions as a collection of new objects that you would have to handle dynamically, not too different from a PL parameter.  Anyway, it would be good to dig up Eric's proposal and look over it in detail.

But before we add anymore stuff to the ME objects, I really need to finish the cleanup and reorganization that I started over the XMAS break.  The current (dis)organization of the ME will make it hard to add more stuff (or just maintain what is there).  (Amazing what putting aside a piece of software for 5+ years does to help to see problems you did not see before :-) )

**Comment by rppawlo** [comment]
Just created a pull request with the code as suggested by Eric. It has new thyra tests that are passing, but I have not run all of trilinos. Will do that now and report back.

**Comment by rppawlo** [comment]
> Therefore, you would need to register additional extensions as a collection of new objects that you would have to handle dynamically, not too different from a PL parameter.

yes - I used Teuchos::any to hold the objects in the internals of the class. The main difference is that the user doesn't need to bother with keys or validation of a parameter list. It has strict type checking directly in the interface.

**Comment by rppawlo** [comment]
checkin test script passes so this is ready to push unless reviewers want changes

**Comment by eric-c-cyr** [comment]
This looks good to me. The only sad thing, is the need for "template" in the call to get.

**Comment by bartlettroscoe** [comment]
> The only sad thing, is the need for "template" in the call to get.

You can use a non-member function to to avoid the "template" in the call.  You can see an example of this with the PL interface, for example `git<int>(list, "Iters")`:

* https://trilinos.org/docs/dev/packages/teuchos/doc/html/classTeuchos_1_1ParameterList.html#a02181a9dd9eb3f5b314ca439db5000bc

Those are easy to add.

**Comment by bartlettroscoe** [comment]
I will do a review of #1307 later today and comment there.

**Comment by rppawlo** [comment]
moving to in_review. Will wait a few days to see if issues turn up in downstream app codes before closing.
