### ISSUE TITLE
Tpetra: Compile error with GCC 7.1

### ISSUE THREAD

**Issue by gahansen** [trilinos/Trilinos#1286]
When compiling Tpetra with GCC 7.1, I see the following error:

/lore/ghansen/nightly/repos/Trilinos/packages/tpetra/core/src/Tpetra_Details_iallreduce.hpp:175:43: error: expected ')' before '<' token
   DeferredActionCommRequest (std::function< void (int) > action);
                                           ^
/lore/ghansen/nightly/repos/Trilinos/packages/tpetra/core/src/Tpetra_Details_iallreduce.hpp:188:8: error: 'function' in namespace 'std' does not name a template type
   std::function<void(void) > action_;

I was able to get a clean compile by adding the include:

#include <functional>

to the include list (line 71) of packages/tpetra/core/src/Tpetra_Details_iallreduce.hpp

CC: @trilinos/tpetra @trilinos/framework

**Comment by gahansen** [comment]
Meant to paste the "include" line as code:

 `#include <functional>`

**Comment by tjfulle** [comment]
From [Porting to GCC7](https://gcc.gnu.org/gcc-7/porting_to.html)

> ### Header dependency changes
> Several C++ Standard Library headers have been changed to no longer include the `<functional>` header. As such, C++ programs that used components defined in `<functional>` without explicitly including that header will no longer compile.
>
> Previously components such as `std::bind` and `std::function` were implicitly defined after including unrelated headers such as `<memory>`, `<future>`, `<mutex>`, and `<regex>`. Correct code should `#include <functional>` to define them.

**Comment by ibaned** [comment]
Here is a pull request if it helps: #1287

**Comment by mhoemmen** [comment]
@ibaned is it safe to do this with earlier compilers?  Thanks for the PR btw :)

**Comment by ibaned** [comment]
@mhoemmen I can't think of any reason it would fail with older compilers, even C++98 should be fine.

**Comment by gahansen** [comment]
@ibaned and @mhoemmen - I grepped the Trilinos "packages" directory on down and
`#include <functional>`
appears to show up all over the place. I saw a similar pattern combining that include file and the `std::function` usage in kokkos/core/src/impl/Kokkos_Synchronic_n3998.hpp

**Comment by mhoemmen** [comment]
@gahansen Thanks for checking!  This is reassuring.  I will approve the PR.

**Comment by mhoemmen** [comment]
Thanks @ibaned for the PR!  I just approved it.
