### ISSUE TITLE
ShyLU Basker multiple numeric solves with single symbolic failure

### ISSUE THREAD

**Issue by srajama1** [trilinos/Trilinos#1289]
Xyce simulations fails for an internal matrix when a single symbolic reused for multiple numeric solves with latest changes to compose permutations. @hkthorn reported this issue.

@ndellingwood has analyzed it and found the problem. This needs a fix and an unit test as well.

**Comment by ndellingwood** [comment]
@srajama1 @hkthorn I just put in a PR for with a fix. 
@hkthorn this should fix the issue, please let me know if there are any problems. 
@srajama1 I need to modify my example test to add as a unit test (it uses matrices not available in Amesos2). Will close after I get the test added.

**Comment by hkthorn** [comment]
@srajama1 @ndellingwood Do you need anything from me to close this issue, like a smaller test matrix?

**Comment by hkthorn** [comment]
While the Basker solver works for completing the simulation of a power grid network in Xyce, there are other circuits/networks for which the Basker solver fails to enable a simulation to complete.  Sequences from other circuits, for which ShyLU Basker fails, are available to test the issue.
