### ISSUE TITLE
Remove all failures in "Clean" track builds.

### ISSUE THREAD

**Issue by jwillenbring** [trilinos/Trilinos#1294]
Done for this ticket means all "Clean" track builds shown on 

[http://testing.sandia.gov/cdash/index.php?project=Trilinos&date=2017-05-07](http://testing.sandia.gov/cdash/index.php?project=Trilinos&date=2017-05-07)

are 100% passing.

**Comment by william76** [comment]
Per our discussion this morning:

I will do the following:
- Remove GCC 4.8.x tests from the nightly testing.  We aren't aware of anyone that cares about this build and they're bad candidates for the "clean" track since they do not complete by the start of the day.
- Change the GCC 4.8.x tests off the "Clean" track into "Specialized" in case they need reactivation so that they do not reappear in the "Clean" track.
-  Start working on cleaning up the failures on the Linux-GCC-4.7.2-SERIAL_OPT_DEV build.
   - @jwillenbring - We're keeping this build from muir on the Clean track, right?

@bmpersc will put in a ticket for moving the prototype parameterized build into Trilinos.  Once that's complete and we clean up the GCC 4.7.2 build, we'll move the GCC 4.9.3 tests that run on ASCIC up to the Clean track.

@bmpersc, @jwillenbring : Are these the 4.9.3 builds we were expecting to move to Clean? 
- Linux-gcc-4.9.3-MPI_Release_gcc_4.9.3_openmpi_1.8.7_DEV
- Linux-gcc-4.9.3-SERIAL_Release_gcc_4.9.3__DEV

**Comment by william76** [comment]
Moved the following tests up to Specialized from Experimental and did a test-run to make sure the parameters can control the track correctly.  
- Linux-gcc-4.9.3-MPI_Release_gcc_4.9.3_openmpi_1.8.7_DEV
- Linux-gcc-4.9.3-SERIAL_Release_gcc_4.9.3__DEV

It looks like it was successful, so I'm moving them up to the Clean track for tonight.

**Comment by william76** [comment]
Bill Spotz is checking into the two test failures on Domi.  So far he wasn't able to replicate the failure with his configuration and will try to test a configuration closer to the one used for the dashboard.

**Comment by bartlettroscoe** [comment]
Why is Sundance part of the "Clean" builds as shown at:

* http://testing.sandia.gov/cdash/index.php?subproject=Sundance&project=Trilinos&date=2017-05-12

?

I might argue that the "Clean" builds should only contain Primary Tested packages.  Those are the packages that are important to SNL customers.  All other Secondary Packages should be excluded from these "Clean" builds (but it is fine to leave them in "Nightly" and "Specialized" builds as long as the package teams for these ST packages is committed to keeping them working).

**Comment by william76** [comment]
@bmpersc 
@jwillenbring 

As I'm still somewhat new with Trilinos, I don't know what might be considered 'core' packages in the sense of what is appropriate to be put on the "clean" track... Should we pull Sundance from the GCC 4.9.3 builds that are running currently on the clean track?

The GCC 4.9.3 builds on the Clean track are using the new parameterized build system... If we should pull Sundance, is there any easy way to disable that one?

**Comment by bartlettroscoe** [comment]
Why have the non-critical non-PT packages like CTrilinos and Sundance not been removed from these "Clean" builds yet as shown today, for example, here:

* http://testing.sandia.gov/cdash/index.php?project=Trilinos&parentid=2899356

@william76, unless @jwillenbring expresses a strong concern immediately, please add:

```
SET(Trilinos_ENABLE_SECONDARY_STABLE_CODE OFF)
```

to the `ctest -S` driver scripts for these "Clean" builds.

**Comment by bartlettroscoe** [comment]
This is obviously already in progress so I put it so in [Trilinos Framework](https://github.com/orgs/trilinos/projects/1) board.

**Comment by bartlettroscoe** [comment]
Note that the "Clean" builds are still broken as of today as shown at:

* http://testing.sandia.gov/cdash/index.php?project=Trilinos&display=project&date=2017-05-23

with Sundance failing to build.  That is 11 days after this issue noted [above](https://github.com/trilinos/Trilinos/issues/1294#issuecomment-301117337).

At the SART meeting today, @bmpersc said he tried to disable extra repos and that it was not working (see #1355)? But he said that he did not know if Secondary Tested code and packages in general should be removed from the "Clean" builds as I suggested 6 days ago [above](https://github.com/trilinos/Trilinos/issues/1294#issuecomment-302195574).

**Comment by bartlettroscoe** [comment]
We are still seeing Sundance being built and failing, for example, today:

* http://testing.sandia.gov/cdash/index.php?project=Trilinos&parentid=2923164

Can we resolve this before we put up more builds?  There will be some ATDM builds that we will want to post to "Clean" soon.

**Comment by bartlettroscoe** [comment]
Note that the "clean" builds were actually clean from May 25-27 as shown at:

* http://testing.sandia.gov/cdash/index.php?project=Trilinos&date=2017-06-02&filtercount=2&showfilters=1&filtercombine=and&field1=groupname&compare1=61&value1=Clean&field2=buildstarttime&compare2=84&value2=now

Why was this story not closed then?  Is it not just a maintenance issue now?  What is the process for keeping these clean?

**Comment by jwillenbring** [comment]
The story was not closed due to the timing of the clean days relative to staff availability. Since there are a few problems that have persisted for multiple days, I went and filed tickets for the current failures:

#1392 #1393 #1395 

I don't think this is the model we want to use because it provides a disincentive for people to triage issues themselves, but some initial prodding will be necessary to get used to keeping clean builds clean.

**Comment by bartlettroscoe** [comment]
@jwillenbring:

> I don't think this is the model we want to use because it provides a disincentive for people to triage issues themselves

What do you mean?  What process were you imagining by which the "Clean" builds would be kept clean?

We need a process where we are assured that failures are being addressed in a timely way yet we don't have multiple people unnecessarily triaging the same problems.  I can suggest a process that does just this.  Should we create a separate GitHub issue for that process?  This is really important and not to be taken lightly or the "Clean" builds will very be clean.

**Comment by jwillenbring** [comment]
The definition of done for this was completed a while ago (100% passing clean builds), but the ticket was never closed. I will close the ticket since it was meant to get us set up with initially passing clean builds, not be open indefinitely in case a clean build fails at some point.
