### ISSUE TITLE
DTK headers no longer being installed when building Trilinos with DTK

### ISSUE THREAD

**Issue by ikalash** [trilinos/Trilinos#12952]
On 4/18, something changed in Trilinos causing certain headers from DTK (DataTransferKit) to no longer be installed, e.g., DTK_STKMeshHelpers.hpp.  This is messing up our nightly Albany-LCM builds, which use DTK.  

This commit was OK: 32ed06830fb9eb3685e8236574afb1f1b2286676
This commit is broken: 5275b578ebb3903004789a86f8dff81df185e7b6

I am attaching a configure script for Trilinos.  We use this version of DTK:

git@github.com:ikalash/DataTransferKit
dtk-2.0-tpetra-static-graph branch

[do-cmake.txt](https://github.com/trilinos/Trilinos/files/15068638/do-cmake.txt)

One specific file that is not installed is called DTK_STKMeshHelpers.hpp .

Tagging @lxmota who is also interested in this issue.

**Comment by ikalash** [comment]
Could this be from STK, seacas or deprecated package-related changes introduced on 4/18-4/19?  @alanw0 @gsjaardema @sebrowne   

I am basing my conjecture by looking at the commits b/w the good and bad one and guessing on what might have cause the issue.

**Comment by sebrowne** [comment]
My change is the most likely candidate.  I cannot find any references to `DTK_STKMeshHelpers.hpp` in the linked repository.  Does that header come from DTK or Trilinos?

Can you email the configure log from your broken DTK build to my Sandia email?  I can try to see what happened.

If there is ANY dependency on any of the to-be-deprecated packages, this error likely indicates that you have a dependency on a package that will be deprecated and you have not explicitly enabled that package.

**Comment by ikalash** [comment]
@sebrowne : it is indeed your merge regarding the deprecated package change a28cd86abf70fec5249a92ed4c67d61f1f12ed4a .  When I check out what I believe is he last commit before yours 32ed06830fb9eb3685e8236574afb1f1b2286676 everything is good. 

So the thing is that there is no error in building Trilinos - it builds but doesn't include all the required DTK headers.  Then when we go to build Albany on top of Trilinos, it complains that there are missing DTK headers, and if you look at Trilinos/build/install/include, indeed they are missing.  

The header lives in DTK, not Trilinos, if that is what you are asking.  I am not sure how the build magic with TriBiTs is supposed to work with an external package like DTK, so it's hard for me to conjecture what went wrong.

What I could do is create a set of configure scripts to build Trilinos and then LCM, to reproduce the problem (but you would only need to build Trilinos and check the install/include dir to see if the missing headers are there or not).  Would this be helpful?

**Comment by sebrowne** [comment]
I can probably reproduce the issue with the CMake command you provided earlier.  But I'm hung up on where that header is supposed to come from so I can look at the build/install logic around it.  I can't find the string "STK" in that repository either in any file names or in any files (tried `git grep STK` and `find . -name "*STK*"`).  I cloned `git@github.com:ikalash/DataTransferKit.git` and am looking at the `master` branch.  Any other example filenames for other missing headers may help as well.

**Comment by rppawlo** [comment]
This PR changed trilinos cmake configures so that secondary tested code is now off by default. dtk is probably declared a secondary package. You may have to enable dtk and any dependencies in trilinos manually now (especially if they related to epetra stack).

**Comment by sebrowne** [comment]
@rppawlo DTK is marked as ST, so that part holds, but the configure command @ikalash provided shows they are passing `-DTrilinos_ENABLE_DataTransferKit=ON`.  When I try with that, it DOES enable DTK for me.  I suspect something a bit more convoluted is going awry.

**Comment by rppawlo** [comment]
I think you just have to enable the STKMeshAdapters subpackage. Possibly others from the list below.

Albany is using DTK version 2.0 which is very different from the master branch 3.1. If you check out the 2.0 tag, you can see the adapters to all the major mesh databases including STK. They are implemented as secondary stable subpackages:

```
TRIBITS_PACKAGE_DEFINE_DEPENDENCIES(
  SUBPACKAGES_DIRS_CLASSIFICATIONS_OPTREQS
    Utils                 packages/Utils                  SS  REQUIRED
    Interface             packages/Interface              SS  REQUIRED
    BasicGeometryAdapters packages/Adapters/BasicGeometry SS  OPTIONAL
    IntrepidAdapters      packages/Adapters/Intrepid      SS  OPTIONAL
    Operators             packages/Operators              SS  REQUIRED
    C_API                 packages/Adapters/C_API         SS  OPTIONAL
    Fortran_API           packages/Adapters/Fortran_API   SS  OPTIONAL
    STKMeshAdapters       packages/Adapters/STKMesh       SS  OPTIONAL
    MoabAdapters          packages/Adapters/Moab          SS  OPTIONAL
    LibmeshAdapters       packages/Adapters/Libmesh       SS  OPTIONAL
    ClassicDTKAdapters    packages/Adapters/ClassicDTK    SS  OPTIONAL
  )
```

**Comment by sebrowne** [comment]
Confirmed, that's almost certainly the issue.  Here is my configure output without explicitly enabling the subpackages:


```
-- NOTE: Not Setting Trilinos_ENABLE_DataTransferKitBasicGeometryAdapters=ON even though DataTransferKit has an optional dependence on DataTransferKitBasicGeometryAdapters because Trilinos_ENABLE_SECONDARY_TESTED_CODE=OFF
-- NOTE: Not Setting Trilinos_ENABLE_DataTransferKitIntrepidAdapters=ON even though DataTransferKit has an optional dependence on DataTransferKitIntrepidAdapters because Trilinos_ENABLE_SECONDARY_TESTED_CODE=OFF
-- NOTE: Not Setting Trilinos_ENABLE_DataTransferKitC_API=ON even though DataTransferKit has an optional dependence on DataTransferKitC_API because Trilinos_ENABLE_SECONDARY_TESTED_CODE=OFF
-- NOTE: Not Setting Trilinos_ENABLE_DataTransferKitFortran_API=ON even though DataTransferKit has an optional dependence on DataTransferKitFortran_API because Trilinos_ENABLE_SECONDARY_TESTED_CODE=OFF
-- NOTE: Not Setting Trilinos_ENABLE_DataTransferKitSTKMeshAdapters=ON even though DataTransferKit has an optional dependence on DataTransferKitSTKMeshAdapters because Trilinos_ENABLE_SECONDARY_TESTED_CODE=OFF
-- NOTE: Not Setting Trilinos_ENABLE_DataTransferKitMoabAdapters=ON even though DataTransferKit has an optional dependence on DataTransferKitMoabAdapters because Trilinos_ENABLE_SECONDARY_TESTED_CODE=OFF
-- NOTE: Not Setting Trilinos_ENABLE_DataTransferKitLibmeshAdapters=ON even though DataTransferKit has an optional dependence on DataTransferKitLibmeshAdapters because Trilinos_ENABLE_SECONDARY_TESTED_CODE=OFF
-- NOTE: Not Setting Trilinos_ENABLE_DataTransferKitClassicDTKAdapters=ON even though DataTransferKit has an optional dependence on DataTransferKitClassicDTKAdapters because Trilinos_ENABLE_SECONDARY_TESTED_CODE=OFF
```

**Comment by ikalash** [comment]
@rppawlo @sebrowne : is the suggestion to add the configure option in the note, e.g., ``Trilinos_ENABLE_DataTransferKitSTKMeshAdapters=ON ``?  I tried this and the header is still missing when I install.

**Comment by ikalash** [comment]
I spoke too soon - things are good with the additional enables (earlier I was searching for the missing header from memory and didn't get the name quite right).  Thank you, we will add the configure options to our nightlies to avoid the error.
