### ISSUE TITLE
Thyra routines not found when compiling Albany-LCM on top of Trilinos

### ISSUE THREAD

**Issue by ikalash** [trilinos/Trilinos#12960]
We are seeing a strange behavior in Albany-LCM since some of the Trilinos changes introduced end of last week.  Some basic Thyra vector routines are not found, e.g., ```Thyra::copy```:

```
[ 38%] Building CXX object src/CMakeFiles/albanyLib.dir/evaluators/bc/PHAL_SDirichlet.cpp.o
/home/lcm/LCM/LCM/src/LCM/solvers/Schwarz_Coupled.cpp:679:12: error: no member named 'copy' in namespace 'Thyra'
    Thyra::copy(*xMV->col(0), xT_vec.ptr());
    ~~~~~~~^
[ 38%] Building CXX object src/CMakeFiles/albanyPDEs.dir/evaluators/pde/PHAL_NSForchheimerTerm.cpp.o
/home/lcm/LCM/LCM/src/LCM/solvers/Schwarz_Coupled.cpp:688:14: error: no member named 'copy' in namespace 'Thyra'
      Thyra::copy(*xMV->col(1), x_dotT_vec.ptr());
      ~~~~~~~^
[ 39%] Building CXX object src/CMakeFiles/albanyPDEs.dir/evaluators/pde/PHAL_NSMomentumResid.cpp.o
[ 39%] Building CXX object src/CMakeFiles/albanyLib.dir/evaluators/bc/PHAL_DirichletCoordinateFunction.cpp.o
```
Here is the routine that has the problem: https://github.com/sandialabs/LCM/blob/main/src/LCM/solvers/Schwarz_Coupled.cpp#L679 .  We have the required Thyra include: https://github.com/sandialabs/LCM/blob/main/src/LCM/solvers/Schwarz_Coupled.cpp#L15 .  

There have been no nontrivial changes to Albany-LCM in the past few weeks, so I am sure that the issue is from changes to Trilinos, perhaps the deprecated package changes last week by @sebrowne ?

@trilinos/thyra 

Tagging @lxmota who is interested also in this issue.

**Comment by bartlettroscoe** [comment]
@ikalash, I am guessing there is a missing header file.  Not sure what caused this.   Will need to look in more detail when I get a break.

**Comment by ikalash** [comment]
The strange thing is that Thyra_VectorBase.hpp is installed and included in the file reporting the issue.  Thanks for looking at it @bartlettroscoe .

**Comment by cgcgcg** [comment]
Maybe you also need `#include "Thyra_VectorStdOps.hpp"`?

**Comment by ikalash** [comment]
> Maybe you also need `#include "Thyra_VectorStdOps.hpp"`?

I think that actually does it!  @lxmota can you please try in the nightly builds to verify that adding the include to Schwarz_Coupled.hpp fixes the problem?  I'm surprised that the new include is needed now, whereas it was not needed before.  Something must have changed in Trilinos to require this new include.

**Comment by bartlettroscoe** [comment]
> > Maybe you also need `#include "Thyra_VectorStdOps.hpp"`?
> 
> I think that actually does it! @lxmota can you please try in the nightly builds to verify that adding the include to Schwarz_Coupled.hpp fixes the problem? I'm surprised that the new include is needed now, whereas it was not needed before. Something must have changed in Trilinos to require this new include.

It may have come in accidentally through an Epetra-related ThyraEpetraAdapters header file that was getting pulled in indirectly from downstream package header files?  This was likely caused by:

* https://github.com/trilinos/Trilinos/pull/12869

?

@ikalash, I suspect that if your look at your Trilinos configure STDOUT before and after this PR was merged, that you will see that Epetra-related packages were enabled before but not after.  Just an educated guess.

**Comment by ikalash** [comment]
@bartlettroscoe : that is possible.  Our nightlies are clean today so I will close.
