### ISSUE TITLE
Kokkos-kernels: BLAS name mangling causing compilation issues on Vortex with `cher`, `zher`, `cher2`, and `zher2`

### ISSUE THREAD

**Issue by MalachiTimothyPhillips** [trilinos/Trilinos#12962]
Trilinos mirror of https://github.com/kokkos/kokkos-kernels/issues/2184.

In short, it appears making the method name for the `HostBlas` type the same as one of the `extern "C"`'d functions is causing compilation errors on my end on (some) cuda platforms (vortex).

Fortunately, https://github.com/kokkos/kokkos-kernels/pull/2183 fixes the issue for me.
I'll have a MR here shortly.

**Comment by ndellingwood** [comment]
This is an interesting case, it wasn't caught in Trilinos CI nor in our integration testing builds on Weaver (Power9+Volta70). In the Weaver builds we use OpenBLAS, the posted configuration [here](https://github.com/kokkos/kokkos-kernels/issues/2184#issuecomment-2075746516) uses netlib blas and lapack for the host tpl, will try to confirm if that was the gap in testing (it looks like the Trilinos CI uses installs on the system path of the ascic machines?)

**Comment by MalachiTimothyPhillips** [comment]
Marking as closed with #12963 being merged in. Not sure if we should add some sort of coverage to exercise this case?
