### ISSUE TITLE
Epetra:  Creation of Epetra_MpiComm instance causing error/warning in IDE

### ISSUE THREAD

**Issue by abodado** [trilinos/Trilinos#12985]
## Question
@ccober6

I have a question about:
https://github.com/trilinos/Trilinos/blob/master/packages/epetra/example/Lessons/Lesson02-Map-Vector/lesson02_init_map_vec.cpp

When I try to work with it in my IDE (using qt creator 4.11), I get the error: “variable type ‘Epetra_MpiComm’ is an abstract class”.

As such, the IDE doesn’t provide suggestions for functions related to the “comm” variable. I understand I can see the functions here: https://docs.trilinos.org/dev/packages/epetra/doc/html/classEpetra__Comm.html#details

But that's inconvenient and prone to bug creation. So, I was wondering if anyone has heard of this issue and if there is a fix. Here is a screen shot of the error/warning from the IDE:
![image](https://github.com/trilinos/Trilinos/assets/62546087/88facecf-02bd-4957-aa42-6a8481e70c67)

**Comment by cgcgcg** [comment]
Not a fix, but a recommendation: Epetra (and packages that depend on it) is deprecated and will be removed in the near future. I would recommend against using it for writing new code. You can use Tpetra in its place. A lot of the concepts are identical, but it runs on new architectures and supports larger problems.

**Comment by abodado** [comment]
Thank you for the suggestion. Our code is currently based in Epetra. I was trying to improve some logic and using the Epetra examples as a guide. Based on your suggestion, I loaded the Tpetra based lesson02_init_map_vec.cpp example into my IDE and there is no such error as there was with Epetra. My goal is to move to Tpetra eventually. But I will live with the small inconvenience of the Epetra comm issue for now. The good news is that even though the IDE complains and fails to autocomplete related functions, the code still compiles.

**Comment by ccober6** [comment]
Unless there are further questions, I will close.  Please reopen if needed.
