### ISSUE TITLE
Belos: lots of warnings regarding usage of null pointers

### ISSUE THREAD

**Issue by bartgol** [trilinos/Trilinos#12998]
## Bug Report

Apologies if this was already reported (though I did not find it among issues with the "pkg: belos" label).

I am getting several compiler warnings from a few Belos files (I think they are all `BelosXYZSolMgr.hpp`). The warnings are of the form
```
/ascldap/users/lbertag/workdir/trilinos/trilinos-src/develop/packages/belos/src/BelosBlockGmresSolMgr.hpp: In member function 'void Belos::BlockGmresSolMgr<ScalarType, MV, OP>::setParameters(const Teuchos::RCP<Teuchos::ParameterList>&) [with ScalarType = double; MV = Thyra::MultiVectorBase<double>; OP = Thyra::LinearOpBase<double>]':
/ascldap/users/lbertag/workdir/trilinos/trilinos-src/develop/packages/belos/src/BelosBlockGmresSolMgr.hpp:667:24: warning: 'this' pointer is null [-Wnonnull]
  667 |       paramsOrtho->set ("depTol", orthoKappa_ );
```
The compiler is indeed correct, since [here](https://github.com/trilinos/Trilinos/blob/6e2f44ec1e0ab10f0c483ad1274c6194349db76f/packages/belos/src/BelosBlockGmresSolMgr.hpp#L665) we are creating a null RCP, and dereferencing it inside the if statement, without first creating the new param list. The inline comment "can be null" seems to suggest the issue was somewhat known (even though it's an understatement: it _is_ null).

1. Sha:  6e2f44ec1e0ab10f0c483ad1274c6194349db76f
2. Compiler: g++ 13.2.0

I am not attaching the config/build scripts, since I think they are not really important: looking at the code, it seems obvious to me that the compiler is right. We should probably have something like this?
```c++
    Teuchos::RCP<Teuchos::ParameterList> paramsOrtho;   // can be null
    paramsOrtho = Teuchos::rcp(new Teuchos::ParameterList(""));
    if (orthoType_=="DGKS" && orthoKappa_ > 0) {
      paramsOrtho->set ("depTol", orthoKappa_ );
    }
```

I assume none of the Trilinos tests exercise the conditions that would trigger the if statement block to be executed?

**Comment by hkthorn** [comment]
Gah!!!!! It's in several places.  I'll take care of it.

**Comment by hkthorn** [comment]
@bartgol This should take care of the compiler warnings.  Thanks!

**Comment by bartgol** [comment]
> @bartgol This should take care of the compiler warnings. Thanks!

Thanks for the ninja-fix!
