### ISSUE TITLE
Four failing MueLu tests in all MPI builds and two in all Serial builds since 5/4/2017

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#1299]
One (or more) of the commits (or the combination of commits) pushed by several people broke one Intrepid2 test and four MueLu tests in this CI build on 5/4/2017:

* http://testing.sandia.gov/cdash/index.php?project=Trilinos&parentid=2876438&filtercount=3&showfilters=1&field1=groupname&compare1=61&value1=Continuous&field2=buildstarttime&compare2=84&value2=now&filtercombine=and

which shows the failing tests:

* Intrepid2_refactor_unit-test_Shared_Polylib_Serial_Test_01_MPI_1
* MueLu_UnitTestsEpetra_MPI_1
* MueLu_UnitTestsEpetra_MPI_4
* MueLu_UnitTestsTpetra_MPI_1
* MueLu_UnitTestsTpetra_MPI_4

The commits that were pulled in the following CI iteration on 5/4/2018 involve the range of Trilinos commits 75ba6df..1d4823c and the commits are shown here:

* http://testing.sandia.gov/cdash/viewNotes.php?buildid=2876439##note1

The commits pulled in this CI iteration were by the people:

```
$ git shortlog -ns 75ba6df..1d4823c
     6  Kyungjoo Kim
     2  Nathan Ellingwood
     1  Alejandro Mota
     1  Dan Ibanez
     1  Mark Hoemmen
```

The commits showing the standard CI build was run are:

```
$ git log-short --grep="Build/Test Cases Summary" 75ba6df..1d4823c
26d683b "MiniTensor #1264: Switch from Teuchos::ScalarTraits to Kokkos::Detail::ArithTraits."
Author: Alejandro Mota <amota@sandia.gov>
Date:   Thu May 4 13:22:29 2017 -0700 (4 days ago)
```

Therefore, any of these other 4 individuals may have broken the standard CI build.  One would have to examine the individual commits and do more investigation to figure our what changes are breaking these tests.

Also, note that these tests are failing for all **ALL** the "Nightly" and (ironically) "Clean" builds for MueLu as shown at:

* http://testing.sandia.gov/cdash/index.php?project=Trilinos&date=2017-05-07&subproject=MueLu

The only build that does not show MueLu test failures is the Epetra-only build (Linux-GCC-5.2.0-SERIAL_DEBUG_DEV_MueLu_Epetra).  Therefore, this is a wide-spread failure.

NOTE: I am not mentioning anyone or adding any labels yet because I want to see how long it takes for the current Trilinos development community to discover and fix these failures.  I am just creating this issue so that I can use the Issue ID number in the commit where I disable these four tests in pre-push testing (but not post-push testing).  This is needed so that we don't stop people trying to use the checkin-test-sems.sh script to push.  We can't have recuring failures being ignored from stopping other people from using the checkin-test-sems.sh script.

**Comment by ndellingwood** [comment]
I believe the failing MueLu unit tests are being tracked in issue #1290 (reported May 5, 2017) and are being addressed/fixed by @kyungjoo-kim @jhux2 @CamelliaDPG  (please correct me if I'm wrong!) 
I have no info to add regarding the test Intrepid2_refactor_unit-test_Shared_Polylib_Serial_Test_01_MPI_1

**Comment by bartlettroscoe** [comment]
> I believe the failing MueLu unit tests are being tracked in issue #1290 (reported May 5, 2017) and are being addressed/fixed by @kyungjoo-kim @jhux2 @CamelliaDPG (please correct me if I'm wrong!)

I searched for the names of one of the failing tests (i.e. MueLu_UnitTestsEpetra_MPI_1) and could not find any issues.  (I think it is best practice to actually list out the failing tests in GitHub issues.  That way, it is easy to find and differentiate from other possible failures.)

**Comment by ndellingwood** [comment]
The commit that caused the break has commit 0182187  (sorry, was only testing with Cuda). 
https://github.com/trilinos/Trilinos/commit/01821876992ecad172279491c74ed304e74a2c53

**Comment by bartlettroscoe** [comment]
> The commit that caused the break has commit 0182187 (sorry, was only testing with Cuda).

Can we revert that commit until the failures are resolved?  Or, we can just disable these these failing tests in pre-push testing so that we don't cause other people to have their pushes stopped.

**Comment by tawiesn** [comment]
@bartlettroscoe I agree with you that it makes sense to list the names of all the failing tests. But then we all have to agree that we use the exact names of tests. In fact, you would have found the issue if you would have searched for 
MueLu_UnitTests{E,T}petra 
or 
MueLu_UnitTests
Or, since you know it is a MueLu related issue, you search for MueLu or the MueLu tag.

**Comment by bartlettroscoe** [comment]
@tawiesn, I agree.  I should have looked harder.

It is just that usually when I have looked for a GitHub issue for failures on CDash I have not been able to find them.  Therefore, I have stopped looking as hard.  (Hopefully we can get better at creating GitHub issues for cover every commit and then our searches for existing problems will yield finds more often.)

**Comment by bartlettroscoe** [comment]
Closing this since it is a duplicate of already created issue (that I should have looked harder to find) #1290.
