### ISSUE TITLE
error: 'isExperimental' was not declared in this scope

### ISSUE THREAD

**Issue by nschloe** [trilinos/Trilinos#130]
Commit 12896cfacbb5f051e27e7a4175b6a8c522f3a7f7 introduces the build error
```
packages/ifpack2/src/Ifpack2_RILUK_decl.hpp:673:32: error: 'isExperimental' was not declared in this scope
   new_riluk->isExperimental_ = isExperimental;
```

**Comment by tawiesn** [comment]
The test_2_RILUK_Experimental_nos1_hp.xml file is missing, too. I've added a dummy file to keep Trilinos compiling for the nightlies.
@jdbooth: Please review my patches and push the correct xml file

**Comment by jdbooth** [comment]
Removed the need in CMake.
Will remove the dummy file in future.
