### ISSUE TITLE
MueLu: compile times are significantly higher

### ISSUE THREAD

**Issue by jhux2** [trilinos/Trilinos#1300]
@trilinos/muelu @csiefer I've noticed a significant uptick MueLu's compile times.   For example, the geminga nightly tests are now taking *much* longer than previously.  For example, the geminga tests last Friday finished at 18:26 MT.  They started at 22:00 MT the prior evening.

Has anyone noticed whether their day-to-day compile times have increased?

**Comment by aprokop** [comment]
The past week geminga nightlies finish by 10:30am. Closing. Reopen if still an issue.
