### ISSUE TITLE
Piro+Tempus: cannot build TempusSolver from parameter list

### ISSUE THREAD

**Issue by bartgol** [trilinos/Trilinos#1302]
It appears that Piro and Tempus have different ways to organize the input parameter lists, and the validation of inputs in Piro makes it impossible to use the TempusSolver constructor which takes parameter list and model as input (and supposedly builds the integrator/stepper depending on the parameters).

In particular, Tempus requires a sublist of name stepperName inside the main Tempus parameter list, while Piro does not allow, say, a "Backward Euler" sublist of the main Tempus parameter list. Instead, Piro assumes there is a "Tempus"->"Tempus Stepper" sublist, which never appears in the Tempus package source code.

Perhaps the Piro and Tempus assumption on the input parameter list organization diverged at some point? Or perhaps the original idea (somehow got lost) was to make Tempus look for the stepper sublist in "Tempus"->"Tempus Integrator"?

**Comment by ibaned** [comment]
There seem to be no @trilinos/tempus or @trilinos/piro teams.... I'll just mention @ikalash

**Comment by sconde** [comment]
@bartgol are you still having issue with this?

**Comment by bartgol** [comment]
@sconde , I think I managed to get it to work. I forgot what I changed, though. It was a project I had to put aside due to other big deadlines, and I still have to go back to it. I guess you can close this for now. When I get back to work on said project, I will reopen if the issue persist (though I think I don't have the issue anymore).

**Comment by sconde** [comment]
Ok. Thank you.
