### ISSUE TITLE
Framework:  how to reproduce errors using genconfig and RHEL8

### ISSUE THREAD

**Issue by jhux2** [trilinos/Trilinos#13022]
## Question

@trilinos/framework @sebrowne 

Many SNL workstations and CEE resources are being upgraded to RHEL8 or RHEL9.  How should developers reproduce errors that show up on the dashboard or in PR testing, which uses RHEL7?  The `genconfig` [instructions](https://github.com/trilinos/Trilinos/wiki/Reproducing-PR-Testing-Errors) are RHEL7 specific.

**Comment by jhux2** [comment]
Opened a related SEMS ticket:  SEMSHELPD-3859.

**Comment by achauphan** [comment]
@jhux2 wanted to update you that we are working on this. The error that you are running into is exactly what's hitting our PR systems for that specific cuda no-uvm build due to the rhel8 upgrade.

**Comment by achauphan** [comment]
Circling back on this, (@jhux2 you may already be aware of this work around, so for anyone else),

Since ascicgpu machines are rhel8 and we do not have a rhel8 cuda config ready yet, in order to reproduce one of the existing rhel7 configurations on the rhel8 machines, you will need to use SEMS' rhel7 modules. This is the work around that is currently implemented for the rhel7 PR tests that run on our rhel8 machines.

The work around is that you will have to make your own copy of `/projects/sems/modulefiles/utils/sems-modules-init.sh`, add the rhel8 hostname you're using to the bottom of the script, and source that script. This will load the rhel7 SEMS modules on a rhel8 machine to test a rhel7 PR configuration.

Once we have finalized the rhel8 cuda config, this work around will not be needed we will be able to use the SEMS rhel8 modules.

**Comment by hkthorn** [comment]
@achauphan Thanks!  I was able to use these instructions to get building on ascicgpu030 again!

**Comment by achauphan** [comment]
@csiefer2 for which configuration + machine is this happening on and is this happening with the bypass?

**Comment by sebrowne** [comment]
@csiefer2 I _just_ (this morning, hasn't taken effect in the current AT run) pulled the trigger on migrating those builds (GCC + OpenMPI) to their updated RHEL8 counterparts.  We're at the point where only the Intel build should be using the RHEL7 configuration (and we hope to transition that tomorrow morning).

**Comment by jhux2** [comment]
I've found that not all of the builds are reproducible.  I guess from the error message that this is known/expected?  For example, the following doesn't work for me:

```
export GENCONFIG_BUILD_NAME="rhel8_sems-gnu-8.5.0-openmpi-4.1.6-openmp_release-debug_static_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables"
source $TRILINOS_SRC/packages/framework/GenConfig/gen-config.sh --force --cmake-fragment gen-config.cmake $GENCONFIG_BUILD_NAME $TRILINOS_SRC

Using system 'rhel7' based on matching hostname 'ascicgpu032'.
Overriding system to 'rhel8' based on specification in build name 'rhel8_sems-gnu-8.5.0-openmpi-4.1.6-openmp_release-debug_static_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables'.

+==============================================================================+
|   ERROR:  Unable to find alias or environment name for system 'rhel8' in
|           build name 'rhel8_sems-gnu-8.5.0-openmpi-4.1.6-openmp_release-debug_static_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables'.
|
|   - Supported Environments for 'rhel8':
|     - aue-gcc-openmpi
|     - cuda-gcc-openmpi
|     - gcc-openmpi
|     - gcc-serial
|     - oneapi-intelmpi
|     - sems-clang-11.0.1-openmpi-4.0.5-serial
|     - sems-cuda-11.4.2-gnu-10.1.0-openmpi-4.1.6
|     - sems-cuda-11.4.2-sems-gnu-10.1.0-sems-openmpi-4.1.4
|     - sems-gnu-8.5.0-openmpi-4.1.6-serial
|     - sems-gnu-8.5.0-serial
|
|   See `../../../../home/jhu/trilinos/Trilinos-ihalim/packages/framework/ini-files/supported-envs.ini` for details on the available environments.
|
|   To force-load an environment see the guidance in the `--help` output.
|
+==============================================================================+
```

**Comment by achauphan** [comment]
@jhux2 do you know how old the branch you're using is? The `sems-gnu-8.5.0-openmpi-4.1.6-openmp` was added on 06-18-24 to `develop` branch and can be seen [here](https://github.com/trilinos/Trilinos/blame/d08d1c0bc20a3ba81c7027406c1e4d9a62069abb/packages/framework/ini-files/supported-envs.ini#L188)

**Comment by jhux2** [comment]
@achauphan Yes, that's the issue, thank you.  The branch that I was using was just a bit too old to have that commit.

**Comment by jhux2** [comment]
I'm closing this as fixed.  Thank you, @achauphan.
