### ISSUE TITLE
Kokkos: How do I build with external kokkos?

### ISSUE THREAD

**Issue by jewatkins** [trilinos/Trilinos#13039]
## Question
@trilinos/framework @trilinos/kokkos 

I'm trying to use trilinos with an external kokkos but I'm running into the following runtime error:
`malloc_consolidate(): invalid chunk size` 
even when first building trilinos/packages/kokkos externally and linking it in trilinos. I tested this with Trilinos 15.1.1 on two machines. What would be the correct way to do this?

Right now, I'm just doing the follow:
```
  -D TPL_ENABLE_Kokkos:BOOL=ON \
  -D Kokkos_DIR=${KOKKOS_DIR}/lib64/cmake/Kokkos \
```
because trilinos wasn't able to find the kokkos cmake files when adding the include/library paths like I do other tpls. Is that the correct way?

**Comment by mperego** [comment]
@trilinos/framework

**Comment by mperego** [comment]
@bartlettroscoe

**Comment by bartlettroscoe** [comment]
> Is that the correct way?

@jewatkins, that should be the correct way. See [5.17   Building against pre-installed packages](https://docs.trilinos.org/files/TrilinosBuildReference.html#building-against-pre-installed-packages).  (But you might also try setting `Kokkos_ROOT` instead of `Kokkos_DIR` as per [`find_package()` documentation](https://cmake.org/cmake/help/v3.23/command/find_package.html?highlight=find_package) .)

Can you please attach your full configure script and the full CMake STDOUT+STDERR output?

**Comment by bartlettroscoe** [comment]
@jewatkins, when you configure again and send the output, add the CMake argument `-debug-find-pkg=Kokkos` and do:

```
$ cd <buildDir>
$ rm -r CMakeCache.txt CMakeFiles/
$ cmake [your options] --debug-find-pkg=Kokkos <trilinosSrc> &> configure.out
```

and attach the generated `configure.out` and `CMakeCache.txt` files.

**Comment by jewatkins** [comment]
Thanks, I'll try this today and report.

**Comment by jhux2** [comment]
@jewatkins  Fyi, Kokkos slack also has a trilinos channel.

**Comment by jewatkins** [comment]
> @jewatkins Fyi, Kokkos slack also has a trilinos channel.

ah didn't know that, thanks

**Comment by jewatkins** [comment]
[trilinos-kokkos-temp.zip](https://github.com/trilinos/Trilinos/files/15474834/trilinos-kokkos-temp.zip)
Here are the files. `int-kokkos` builds trilinos as usual while `ext-kokkos` uses the same kokkos but as a tpl. I also included the kokkos configuration file.

**Comment by bartlettroscoe** [comment]
@jewatkins, from looking at the `confiugre.out` file in the directory `ext-kokkos`, it looks it found and used externally installed Kokkos fine.  The critical bits of output are:

```Adjust the set of internal and external packages:

-- Treating internal package Kokkos as EXTERNAL because TPL_ENABLE_Kokkos=ON
<...>
```

and

```
Final set of enabled top-level external packages/TPLs:  MPI BLAS LAPACK Boost HDF5 Pnetcdf Netcdf DLlib Kokkos 9
```

and

```
Getting information for all enabled TriBITS-compliant or upstream external packages/TPLs in reverse order ...

Processing enabled external package/TPL: Kokkos (enabled explicitly, disable with -DTPL_ENABLE_Kokkos=OFF)
-- Calling find_package(Kokkos) for TriBITS-compliant external package
-- Enabled Kokkos devices: SERIAL
<...>
-- Found Kokkos_DIR='/lcrc/group/e3sm/ac.jwatkins/LandIce/KokkosBuilds/build-gcc-trilinos-kokkos/install/lib64/cmake/Kokkos'
```

and

```
Finished configuring Trilinos!

-- If publishing results using Trilinos, please cite us: https://trilinos.github.io/cite.html
-- Configuring done
-- Generating done
-- Build files have been written to: /lcrc/group/e3sm/ac.jwatkins/LandIce/TrilinosBuilds/build-gcc-trilinos-kokkos2
```

Now, the question of compatibility is a different issue that might be the cause of the runtime error `malloc_consolidate(): invalid chunk size` you are seeing.  There are a lot of open questions here:

1. What compilers and compiler settings are being used for Trilinos and external Kokkos?
2. Could any configuration setting for Trilinos and external Kokkos be different that might cause this?
3. What version of Kokkos is being used for the external Kokkos and what version of Trilinos is being used?

P.S. One advantage of building packages in the same CMake project is to avoid incompatibility issues.  The other way is to try to use Spack to build Kokkos and Trilinos (which builds them as independent CMake projects).

**Comment by bartlettroscoe** [comment]
@jewatkins, BTW, I should have asked this from the beginning, but what is the stack trace for the error `malloc_consolidate(): invalid chunk size`?  That will give a clue for where to look for the incompatibility problem between the Kokkos build and the Trilinos build.  (And that will suggest where more checks need to be added to the Trillinos CMakeLists.txt file, like for Tpetra, to ensure that a compatible Kokkos is being used.)

**Comment by jewatkins** [comment]
1. compiler is gcc-9.3.0.
2. I don't think they are different. I use the same `Kokkos_` cmake settings in both the internal and external kokkos build but maybe there's something missing.
3. I use Trilinos' internal kokkos package as my external Kokkos build and I still see the same error. I use Trilinos 15.1.1.

I might look into spack to see if that works or if I get the same error.

I wasn't able to get a good stack trace even with a debug build in the app. I was going to try adding debug symbols upstream next. Just wanted to confirm I was configuring external kokkos correctly first.

**Comment by bartlettroscoe** [comment]
> I might look into spack to see if that works or if I get the same error.

That is what I would try next.  But the versions of Kokkos and Trilinos as built by Spack will be different from what you are attempting.  I believe that Spack builds an official release of Kokkos, not the snapshot of Kokkos in Trilinos.

NOTE: Is is possible that the internal version of Kokkos in the Trilinos source tree may not actually work when installed first and then building Trilinos against that.  (One would not think that would be the case, but unless there is some automated process testing those exact versions with that build configuration, it is possible that version of Kokkos may only work when built internally with the rest of Trilinos.  Any configuration not tested is likely broken, which is a corollary of Murphy's Law for software.)

**Comment by jewatkins** [comment]
I was able to fix this by comparing the cmake cache of both builds and noticing trilinos was building shared libs for kokkos and I was using static libs for external kokkos. Switching to shared libs fixed the issue. 

I also added `Kokkos_ENABLE_COMPLEX_ALIGN:BOOL=OFF` to my external kokkos build because I saw it in the trilinos build but I think it was the lib type that caused the issue.

**Comment by jhux2** [comment]
@jewatkins Glad you got this resolved.  Could this type of incompatibility be detected automatically?

**Comment by bartlettroscoe** [comment]
> Could this type of incompatibility be detected automatically?

@jhux2, in general, no.  While it is true that you generally can't link shared a shared *.so lib against a static *.a lib, you can if you build the static *.a lib with -fPIC.  This issue of compatible package builds is a major problem that a system like TriBITS and Spack are designed to avoid.

**Comment by jhux2** [comment]
@bartlettroscoe Thanks.  I figured it was worth asking.

**Comment by jewatkins** [comment]
I had `-fPIC` in my kokkos lib so not sure why the malloc error showed up but it might be specific to the app since there are other libs trying to use kokkos.

We'll probably transition to spack at some point, we just need to use a specific kokkos right now.
