### ISSUE TITLE
which package solve the ODE system?

### ISSUE THREAD

**Issue by ztdepztdep** [trilinos/Trilinos#13049]
I want to know which package in Trilinos solve the ODE system.

**Comment by ccober6** [comment]
If you are talking about the actual solvers, you should look at one of the packages in the Solvers Area (@cgcgcg or https://github.com/trilinos/Trilinos/wiki/Trilinos-Package-Owners).  If you are talking about time integration, Tempus is the time integration package.

**Comment by cgcgcg** [comment]
@ztdepztdep Can this be closed?
