### ISSUE TITLE
ROL::Vector_SimOpt::print() doesn't do anything useful.

### ISSUE THREAD

**Issue by jmgate** [trilinos/Trilinos#1306]
I was trying to figure out what's inside a `ROL::Vector_SimOpt`, when I noticed it conveniently has a `print()` routine.  Unfortunately calling the method produces
```
Sim: The method print was called, but not implemented
Opt: The method print was called, but not implemented
```
It looks like `ROL::Vector` has a handful of routines that do something similar.  Is this expected behavior, or was development of these classes not finished?
@trilinos/rol

**Comment by gregvw** [comment]
The method was added for testing with concrete types such as ROL::StdVector. ROL::Vector_SimOpt is an abstract container class much like ROL::Vector, so things like print() and elementwise functions don't have any particular meaning without the notion of elemental access. 

That being said, it would be easy to implement print for SimOpt by simply calling print for the Sim and Opt vectors. The thought does occur, however, that one may not wish to print both subvectors to the same stream, as set by the interface. There is a design question of how this should be handled. 

Some possibilities:

1. Vector_SimOpt::print(outStream)  calls vec1_->print(outStream);  vec2_->print(outStream); 
2. print only writes the OPT vector
3. Implement a print_1 and print_2 

I'm open to suggestions

**Comment by jmgate** [comment]
Sorry @gregvw, I didn't see this response way back when.  The behavior I would expect would be for `print()` to print both vectors to the same stream, but perhaps that's not the best idea.  At this point, however, I've completely forgotten why I asked this question, so apparently it didn't bother me for long.  Closing&hellip;
