### ISSUE TITLE
kokkos: initialization time excessive

### ISSUE THREAD

**Issue by jrobcary** [trilinos/Trilinos#13078]
## Bug Report
@kokkos @crtrott

### Description
When I link trilinos with CUDA into our executable, the initialization time increases dramatically.  The call is

 tpetraScope = new Tpetra::ScopeGuard(argc, argv);

### Steps to Reproduce
1. SHA1:  [insert here]
1. Configure script:  [attach here]
[vcloud.txcorp.com-trilinos-parcuda-config.sh.txt](https://github.com/user-attachments/files/15776048/vcloud.txcorp.com-trilinos-parcuda-config.sh.txt)

1. Configure log:  [attach here]
[vcloud.txcorp.com-trilinos-parcuda-config.txt](https://github.com/user-attachments/files/15776052/vcloud.txcorp.com-trilinos-parcuda-config.txt)

1. Build log:  [attach here]. Too large.
1. Input deck:  [attach here]
1. Do this.
1. Do that.
1. Shake fist angrily at computer.
1. Run log:  [attach here]
My code takes 376 seconds
-- Getting version from error stream of /home/research/cary/opt/imp/volatile-gcc1120/vorpal-r42954/bin/vorpalser --version at local time 2024-06-10T09:47:40.
-- /home/research/cary/opt/imp/volatile-gcc1120/vorpal-r42954/bin/vorpalser completed at local time 2024-06-10T09:53:56.
CMake Warning at txcmake/TxEngFindVersion.cmake:52 (message):
  Elapsed time: 376 seconds
Call Stack (most recent call first):
  txcmake/Modules/FindTxVorpal.cmake:143 (TxEngFindVersion)
  txcmake/TxComposerConfigure.cmake:82 (find_package)
  CMakeLists.txt:185 (include)

-- [TxEngFindVersion] Engine executable --version output: Kokkos::Cuda::initialize WARNING: running kernels compiled for compute capability 7.0 on device with compute capability 8.6 , this will likely reduce potential performance.

Kokkos::Cuda::initialize WARNING: Cuda is allocating into UVMSpace by default
                                  without setting CUDA_MANAGED_FORCE_DEVICE_ALLOC=1 or
                                  setting CUDA_VISIBLE_DEVICES.
                                  This could on multi GPU systems lead to severe performance"
                                  penalties.
VORPAL trunk-r42954-2024-06-09 GPU

**Comment by crtrott** [comment]
What does excessive mean? It is a pretty well known issue of CUDA that the initial driver init stuff can take anything from a few seconds to a minute when a process first starts using the GPU. In rare cases we have seen even times in excess of a minute. If you put the driver into "keep my GPU ready at all times" the time goes down to the few seconds regime generally. But that means certain energy saver states will not be reached. Generally on a warmed up GPU Kokkos::initialize should take <1 sec. 

```c++
#include <Kokkos_Core.hpp>
#include <cmath>

int main(int argc, char* argv[]) {

  Kokkos::Timer timer;
  Kokkos::initialize(argc, argv);
  {
    double time=timer.seconds();
    printf("InitTime: %lf\n",time);
  }
  Kokkos::finalize();
}
```

```
[crtrott@kokkos-dev-2 InitTime]$ ./test.cuda 
Kokkos::OpenMP::initialize WARNING: OMP_PROC_BIND environment variable not set
  In general, for best performance with OpenMP 4.0 or better set OMP_PROC_BIND=spread and OMP_PLACES=threads
  For best performance with OpenMP 3.1 set OMP_PROC_BIND=true
  For unit testing set OMP_PROC_BIND=false

InitTime: 0.170501
```

**Comment by jrobcary** [comment]
We are seeing multiple minutes, so we will dig into this more.

**Comment by crtrott** [comment]
You could try building above little code and see if that also reproduces it. Here is a simple Makefile:

```
KOKKOS_PATH = ${HOME}/Kokkos/kokkos
SRC = $(wildcard *.cpp)
KOKKOS_DEVICES=Cuda,OpenMP
KOKKOS_CUDA_OPTIONS=enable_lambda
KOKKOS_ARCH = SKX,Volta70

default: build
        echo "Start Build"

ifneq (,$(findstring Cuda,$(KOKKOS_DEVICES)))
CXX = ${KOKKOS_PATH}/bin/nvcc_wrapper
EXE = test.cuda
else
CXX = g++
EXE = test.host
endif

CXXFLAGS = -O3 -g
LINK = ${CXX}
LINKFLAGS =  

DEPFLAGS = -M

OBJ = $(SRC:.cpp=.o)
LIB =

include $(KOKKOS_PATH)/Makefile.kokkos

build: $(EXE)

$(EXE): $(OBJ) $(KOKKOS_LINK_DEPENDS)
        $(LINK) $(KOKKOS_LDFLAGS) $(LINKFLAGS) $(EXTRA_PATH) $(OBJ) $(KOKKOS_LIBS) $(LIB) -o $(EXE)

clean: kokkos-clean 
        rm -f *.o *.cuda *.host

# Compilation rules

%.o:%.cpp $(KOKKOS_CPP_DEPENDS)
        $(CXX) $(KOKKOS_CPPFLAGS) $(KOKKOS_CXXFLAGS) $(CXXFLAGS) $(EXTRA_INC) -c $<
```

Just adjust the path to Kokkos (not the installed one, but source clone) and put the Makefile and the above source code copied into a "main.cpp" into some directory and type `make`.

**Comment by crtrott** [comment]
If you do the above trial and that still shows multiple minutes we can reduce further to a CUDA only (no Kokkos) reproducer.

**Comment by crtrott** [comment]
Oh you could also try `make KOKKOS_CUDA_OPTIONS=force_uvm` since it looks like your Trilinos build still does that.

**Comment by crtrott** [comment]
Oh this is on Windows isn't it? Not sure what the UVM thing does there perf wise.

**Comment by jrobcary** [comment]
I added this simple code,

```
// Configuration
#include <tximplicit_config.h>

#include <Kokkos_Core.hpp>

// Std includes
#include <cmath>
#include <iostream>

int main(int argc, char* argv[]) {

  Kokkos::Timer timer;
  Kokkos::initialize(argc, argv);
  {
    double time=timer.seconds();
    printf("Kokkos initialization time: %lf\n",time);
  }
  Kokkos::finalize();

}

```

to our build system.  Initialization is still slow:

```
cary@vcloud/.../tests$ date; ./kokkosInitTimer ; date
Mon Jun 10 20:23:48 MDT 2024
Kokkos::Cuda::initialize WARNING: running kernels compiled for compute capability 7.0 on device with compute capability 8.6 , this will likely reduce potential performance.

Kokkos::Cuda::initialize WARNING: Cuda is allocating into UVMSpace by default
                                  without setting CUDA_MANAGED_FORCE_DEVICE_ALLOC=1 or
                                  setting CUDA_VISIBLE_DEVICES.
                                  This could on multi GPU systems lead to severe performance"
                                  penalties.
Kokkos initialization time: 970.607397
Mon Jun 10 20:40:00 MDT 2024
```

but setting

```
export CUDA_MANAGED_FORCE_DEVICE_ALLOC=1
export CUDA_VISIBLE_DEVICES=0
```
speeds things up:

```
date; ./kokkosInitTimer ; date
Mon Jun 10 20:44:10 MDT 2024
Kokkos::Cuda::initialize WARNING: running kernels compiled for compute capability 7.0 on device with compute capability 8.6 , this will likely reduce potential performance.
Kokkos initialization time: 237.258714
Mon Jun 10 20:48:08 MDT 2024
```

by a factor of 4, but it is still more like 4 minutes rather than one.

**Comment by crtrott** [comment]
Ok, that last bit of info is interesting. Looks like you got 2 GPUs in your system, and that your GPU/Host link is pretty slow. Are you running this in a container or something? Also is the GPU shared between multiple things? Could you try doing the experiment without turning Kokkos_ENABLE_CUDA_UVM on?

**Comment by jrobcary** [comment]
Only one GPU
```
$ nvidia-smi -L
GPU 0: NVIDIA RTX A2000 (UUID: GPU-2d86f647-a801-3a45-ad7d-4fafc6fca65f)
$ 
```
No container.
This is a headless workstation
Communicating over PCI
```
$ lspci | grep -i nvidia
c1:00.0 VGA compatible controller: NVIDIA Corporation GA106 [RTX A2000] (rev a1)
c1:00.1 Audio device: NVIDIA Corporation GA106 High Definition Audio Controller (rev a1)
```
Rebuildling trilinos without UVM.  Will take a while.

BTW, our own CUDA code, which runs next to this, does not have this problem.

**Comment by crtrott** [comment]
What does "in sequence" mean?

**Comment by jrobcary** [comment]
It means that we advance particles with our own explicit updaters, then we'll do, eg, a Poisson solve using Trilinos, then we finite difference that to get the electric field using our own explicit updaters, then back to particles and continue the loop.

**Comment by crtrott** [comment]
Did you (or could you) run an Nvidia profiler over the little Kokkos only code to see where it gets stuck for the 4 minutes? I.e. what's going on there?

**Comment by jrobcary** [comment]
Result of buiding trilinos with Kokkos_ENABLE_CUDA_UVM=OFF:

**Comment by jrobcary** [comment]
```
$ date; ./kokkosInitTimer; date
Tue Jun 11 08:32:12 MDT 2024
Kokkos::Cuda::initialize WARNING: running kernels compiled for compute capability 7.0 on device with compute capability 8.6 , this will likely reduce potential performance.
Kokkos initialization time: 769.822446
Tue Jun 11 08:45:06 MDT 2024
```

so about 13 mins.

**Comment by jrobcary** [comment]
The first attempt had a reduced time, but no output and nsys crashed

```
$ date; nsys profile ./kokkosInitTimer; date
Tue Jun 11 08:49:32 MDT 2024
Warning: LBR backtrace method is not supported on this platform. DWARF backtrace method will be used.
Collecting data...
Kokkos::Cuda::initialize WARNING: running kernels compiled for compute capability 7.0 on device with compute capability 8.6 , this will likely reduce potential performance.
Kokkos initialization time: 197.540866
Processing events...
terminate called after throwing an instance of 'boost::wrapexcept<QuadDCommon::NotFoundException>'
  what():  NotFoundException
Aborted (core dumped)
Tue Jun 11 08:52:59 MDT 2024
```

Will try again with -o

**Comment by crtrott** [comment]
btw. does it make it a difference to use Kokkos_ARCH_AMPERE86=ON ?

**Comment by jrobcary** [comment]
Here is the report from nsys.  To use, need to remove the ending .txt.

[report1.nsys-rep.txt](https://github.com/user-attachments/files/15791999/report1.nsys-rep.txt)

Looks like it just hangs around in query_cuda_kernel_arch for all the time.

**Comment by crtrott** [comment]
Hm it looks like what it's doing is in the first kernel launched (query_cuda_kernel_arch) it starts loading stuff from the JIT Cache. If you expand the operation you see "Runtime Triggered Module Loading" and it starts loading stuff from the JIT cache - like 1700 entries?? What I do not understand is that it says all of them start between 0.34s and 3.5s and then there is a jump of almost 200s to a second RuntimeTriggered Module Loading - both grouped under the query_cuda_kernel_arch entry. But that initial Runtime Triggered Module Loading is what takes 200s on your machine - and I don't know what the heck that is supposed to be.

But here is a suspicion: did you build the test app with a dependency on all of Trilinos? I am wondering if it is recompiling all kernels found in the libraries linked into the test app for 8.6 (since you apparently did compile for 7.0). So effectively you are recompiling chunks of Trilinos at the first kernel launch.

**Comment by crtrott** [comment]
Did you try compiling for your actual GPU architecture. I am wondering if that will avoid the JIT step.

**Comment by jrobcary** [comment]
First, a build with just arch=86 and linking to only kokkos 

```
  target_link_libraries(kokkosInitTimer
    PUBLIC tximplicit_top
    Kokkos::all_libs
    )
```

gives a fraction of a second,:

```
$ date; nsys profile ./kokkosInitTimer ; date
Tue Jun 11 15:19:53 MDT 2024
Kokkos initialization time: 0.148068
Generating '/tmp/nsys-report-f46b.qdstrm'
[1/1] [========================100%] report4.nsys-rep
Generated:
    /home/research/cary/projects/xsimall-dev3/builds/tximplicit/ser/txmbase/tests/report4.nsys-rep
Tue Jun 11 15:19:56 MDT 2024
```

If I link in our txmbase, 

```
  target_link_libraries(kokkosInitTimer
    PUBLIC tximplicit_top
    txmbase
    Kokkos::all_libs
    )
```

Then the time blows up again.  Our txmbase is linked to

```
target_link_libraries(txmbase
  PUBLIC txmstd
# This linkage is private so that final libs can include what they need
  PRIVATE
  tximplicit_top
  TxSim::txsbase TxSim::txsstd TxSim::txsdevices
  TxUtils
  MueLu::all_libs
  Belos::all_libs
  Tpetra::all_libs
  Ifpack::all_libs
  TeuchosComm::all_libs
  Kokkos::all_libs
  TrilinosSS::all_libs
  )
```

But I did not think that mattered, as txmbase is a static library, and the above linkage is private.  I'll mess around with directly linking those into the executable.

**Comment by crtrott** [comment]
Ok so it is not a Kokkos specific thing, or Kokkos::initialize per se, its just that the JIT depends on first kernel execution (which happens in Kokkos::initialize) and how long that takes depends on what you link in.
Can you figure out if it is a specific of these libraries which is causing the explosion, or just the aggregate?

**Comment by crtrott** [comment]
We other thing I was wondering: what if you blow the JIT cache away at: `/home/research/cary/.nv/ComputeCache/`

**Comment by crtrott** [comment]
Also the txmbase: was that all compiled for CC 8.6?

**Comment by jrobcary** [comment]
Yes, txmbase in that test was purely CC8.6.  Trilinos was built with -DKokkos_ARCH_AMPERE86:BOOL='ON'.

**Comment by jrobcary** [comment]
With the libraries

```
    Ifpack::all_libs # < 1s. needs gortran
    TrilinosSS::all_libs # faet
    TeuchosComm::all_libs # fast
    Kokkos::all_libs
```

the initialization is fast, < 1s.

Adding in

`    Tpetra::all_libs # 23s`

increases the time to 23s.

Adding in

`    Belos::all_libs # 25s`

does not increase the time much.

Adding in

`MueLu::all_libs #  Kokkos initialization time: 185.464317`

increases the time to more than 3 minutes.

This in spite of the fact that none of these libraries are needed for a successful link.

**Comment by jrobcary** [comment]
Final results all are for compiled on CC=70, run on CC=86.

The big bumps in time are from (1) adding in Tpetra, then (2) adding in MueLu.

```
# Adding in through Tpetra::all_libs linked in
# With sudo nvidia-smi -i 0 -pm DISABLED, startup time is
# Kokkos initialization time: 20.515842
# With sudo nvidia-smi -i 0 -pm ENABLED
# Kokkos initialization time: 18.943617
# nvidia-persistenced --user cary
# Kokkos initialization time: 20.130120
    # MueLu::all_libs
    # Belos::all_libs
# Adding in through Tpetra::all_libs linked in
# With sudo nvidia-smi -i 0 -pm DISABLED, startup time is
# Kokkos initialization time: 10.346398
# With sudo nvidia-smi -i 0 -pm ENABLED
# Kokkos initialization time: 9.459831
# Same with nvidia-persistenced --user cary
    # Tpetra::all_libs
    # Ifpack::all_libs
    # TrilinosSS::all_libs
    # TeuchosComm::all_libs
# With only Kokkos::all_libs linked in
# With sudo nvidia-smi -i 0 -pm DISABLED, startup time is
# Kokkos initialization time: 0.830274
# With sudo nvidia-smi -i 0 -pm ENABLED
# Kokkos initialization time: 0.093535
```

This is good enough that I will close this.

**Comment by jrobcary** [comment]
Good enough, so closing.
