### ISSUE TITLE
Intrepid2: Compile failures on nightly testing Linux-GCC-4.7.2-SERIAL_OPT_DEV

### ISSUE THREAD

**Issue by william76** [trilinos/Trilinos#1308]
@trilinos/intrepid2 

The nightly tests are failing on the files:
- packages/intrepid2/refactor/unit-test/Discretization/Basis/HGRAD_LINE_Cn_FEM/Serial/test_01.cpp
- packages/intrepid2/refactor/unit-test/Discretization/Basis/HGRAD_LINE_Cn_FEM_JACOBI/Serial/test_01.cpp

This is caused by the same thing in both, they load in a header file that has an if() { block that starts inside a #ifdef block but is closed outside the #endif. 

Commit [c719de51007](https://github.com/trilinos/Trilinos/commit/c719de51007cc14321e8f46b8d42c238b81327b2) is the source of the bug.

## packages/intrepid2/refactor/unit-test/Discretization/Basis/HGRAD_LINE_Cn_FEM_JACOBI/Serial/test_01.cpp

The error happens in the file [packages/intrepid2/refactor/unit-test/Discretization/Basis/HGRAD_LINE_Cn_FEM_JACOBI/Serial/test_01.hpp](https://github.com/trilinos/Trilinos/blob/develop/packages/intrepid2/refactor/unit-test/Discretization/Basis/HGRAD_LINE_Cn_FEM_JACOBI/test_01.hpp).  The `if()` statement that is begun on line [149](https://github.com/trilinos/Trilinos/blob/develop/packages/intrepid2/refactor/unit-test/Discretization/Basis/HGRAD_LINE_Cn_FEM_JACOBI/test_01.hpp#L149) and terminated on line [231](https://github.com/trilinos/Trilinos/blob/develop/packages/intrepid2/refactor/unit-test/Discretization/Basis/HGRAD_LINE_Cn_FEM_JACOBI/test_01.hpp#L231) should be fixed so that it's either completely inside or outside the #ifdef HAVE_INTREPID2_DEBUG guard on line [147](https://github.com/trilinos/Trilinos/blob/develop/packages/intrepid2/refactor/unit-test/Discretization/Basis/HGRAD_LINE_Cn_FEM_JACOBI/test_01.hpp#L147).

## packages/intrepid2/refactor/unit-test/Discretization/Basis/HGRAD_LINE_Cn_FEM/Serial/test_01.cpp
The same issue applies as before, but to file [packages/intrepid2/refactor/unit-test/Discretization/Basis/HGRAD_LINE_Cn_FEM/test_01.hpp](https://github.com/trilinos/Trilinos/blob/develop/packages/intrepid2/refactor/unit-test/Discretization/Basis/HGRAD_LINE_Cn_FEM/test_01.hpp)
The `if()` statement that begins on line [150](https://github.com/trilinos/Trilinos/blob/develop/packages/intrepid2/refactor/unit-test/Discretization/Basis/HGRAD_LINE_Cn_FEM/test_01.hpp#L150) is the culprit.

**Comment by mperego** [comment]
Thanks. I'm fixing this. I only checked the code in debug mode, so this bug was not exposed.

**Comment by mperego** [comment]
This should be solved by commit c13acc49391e46ed9.
