### ISSUE TITLE
Ifpack2: Ifpack2_RILUK_{2,4}streams_hb_belos_MPI_4 test failures in Hip builds, and Cuda with UVM

### ISSUE THREAD

**Issue by ndellingwood** [trilinos/Trilinos#13098]
## Bug Report
@trilinos/ifpack2 

### Description
Trilinos develop branch (most recent test with SHA a0060111d86d1bc44cb70e8b8ee8358d68314a2b) has the `Ifpack2_RILUK_{2,4}streams_hb_belos_MPI_4` tests failing in Hip builds with rocm/5.6.1 on MI210 arch; in a nightly build the 2-proc tests also failed `Ifpack2_RILUK_{2,4}streams_hb_belos_MPI_2`, but I did not manually reproduce that yet

**Ifpack2_RILUK_2streams_hb_belos_MPI_4**:
```
...
Converged in 1000 iterations.
Preconditioner attributes:
 "Ifpack2::RILUK": {Initialized: true, Computed: true, Level-of-fill: 2, KK-SPILUK, KK-Stream, Global matrix dimensions: [237, 237], Global nnz: 1017, "Ifpack2::LocalSparseTriangularSolver": {Label: "lower", Initialized: true, Computed: true, KK-SPTRSV, KK-SolveStream, Matrix: null}, "Ifpack2::LocalSparseTriangularSolver": {Label: "upper", Initialized: true, Computed: true, KK-SPTRSV, KK-SolveStream, Matrix: null}}
2-Norm of 0th RHS      vec: 9.70627
2-Norm of 0th residual vec: 50.7781 -> 5.23147
Achieved tolerance: 5.23147, Requested tolerance: 1e-07
Actual iters(1000) > expected number of iterations (80), or resid-norm(5.23147) >= 1e-07
proc 0 total program time: 1.91888
End Result: TEST FAILED
```

The `Ifpack2_RILUK_4streams_hb_belos_MPI_4` failure mode is similar

The failures showed up in a nightly job after merge of the following commits:

    Fix mistake in #13058: cmake option default ([detail](https://jenkins-son.sandia.gov/job/Trilinos_Caraway_Hip_Serial_Rocm5_6_1_MI210/240/changes#detail))
    Bump step-security/harden-runner from 2.8.0 to 2.8.1 ([detail](https://jenkins-son.sandia.gov/job/Trilinos_Caraway_Hip_Serial_Rocm5_6_1_MI210/240/changes#detail))
    Belos: Adds example for SolverManager using Epetra and Tpetra ([detail](https://jenkins-son.sandia.gov/job/Trilinos_Caraway_Hip_Serial_Rocm5_6_1_MI210/240/changes#detail))
    Tpetra: skip test that spmv_mv used cusparse ([detail](https://jenkins-son.sandia.gov/job/Trilinos_Caraway_Hip_Serial_Rocm5_6_1_MI210/240/changes#detail))

but #13091 only updated a Tpetra test, #13088 added a Belos example, and #13081 fixed a cmake option name, no apparent relevant source code changes. The day before, ifpack2 PR #13057 merged and did not demonstrate the failures with the first run of tests though made relevant changes to RILUK. The failures seem to be a bit spurious (for example, the 4-proc tests failed for me reliably, but the 2-proc tests did not fail when I ran manually)

### Steps to Reproduce
1. SHA1:  a0060111d86d1bc44cb70e8b8ee8358d68314a2b
2. Configure script:  Caraway testbed, MI210 queue
```bash
# Environment
module load python rocm/5.6.1 cmake openmpi/4.1.5 openblas/0.3.23 ninja/1.11.1
module list
export OMPI_CXX=$ROCM_PATH/bin/hipcc
export TPETRA_ASSUME_GPU_AWARE_MPI=0

export TRILINOS_DIR=<path-to-your-repo>

cmake \
-G"Ninja" \
-DCMAKE_INSTALL_PREFIX=$PWD/install \
-DCMAKE_CXX_STANDARD="17" \
-DCMAKE_CXX_COMPILER="`which mpicxx`" \
-DCMAKE_C_COMPILER="`which mpicc`" \
-DCMAKE_FORTRAN_COMPILER="`which mpifort`" \
-DCMAKE_BUILD_TYPE="RELEASE" \
-DBUILD_SHARED_LIBS=OFF \
\
-DTrilinos_ENABLE_ALL_PACKAGES=OFF \
-DTrilinos_ENABLE_ALL_OPTIONAL_PACKAGES=OFF \
-DTrilinos_ENABLE_EXPLICIT_INSTANTIATION=ON \
-DTrilinos_ASSERT_MISSING_PACKAGES=OFF \
-DTrilinos_ALLOW_NO_PACKAGES=OFF \
-DTrilinos_ENABLE_OpenMP=OFF \
-DTrilinos_ENABLE_TESTS=OFF \
\
-DTrilinos_ENABLE_Amesos2=ON \
 -DAmesos2_ENABLE_SuperLU=OFF \
 -DAmesos2_ENABLE_KLU2=ON \
-DTrilinos_ENABLE_Belos=ON \
-DTrilinos_ENABLE_Ifpack2=ON \
-DTrilinos_ENABLE_Kokkos=ON \
 -DKokkos_ARCH_VEGA90A=ON \
 -DKokkos_ENABLE_CUDA=OFF \
 -DKokkos_ENABLE_HIP=ON \
 -DKokkos_ENABLE_OPENMP=OFF \
-DTrilinos_ENABLE_KokkosKernels=ON \
-DTrilinos_ENABLE_MueLu=ON \
-DTrilinos_ENABLE_Tpetra=ON \
 -DTpetra_ENABLE_CUDA=OFF \
 -DTpetra_INST_HIP=ON \
 -DTpetra_INST_SERIAL=OFF \
 -DTpetra_INST_OPENMP=OFF \
 -DTpetra_INST_DOUBLE=ON \
-DTrilinos_ENABLE_Gtest=ON \
-DTrilinos_ENABLE_Teuchos=ON \
-DTrilinos_ENABLE_Xpetra=ON \
-DTrilinos_ENABLE_Zoltan2=ON \
-DTrilinos_ENABLE_Panzer=ON \
-DTPL_ENABLE_BLAS=ON \
  -D BLAS_LIBRARY_DIRS:FILEPATH="${OPENBLAS_ROOT}/lib" \
  -D BLAS_LIBRARY_NAMES:STRING="openblas" \
-DTPL_ENABLE_LAPACK=ON \
  -D LAPACK_INCLUDE_DIRS:FILEPATH="${OPENBLAS_ROOT}/include" \
  -D LAPACK_LIBRARY_DIRS:FILEPATH="${OPENBLAS_ROOT}/lib" \
  -D LAPACK_LIBRARY_NAMES:STRING="openblas" \
-DTPL_ENABLE_Netcdf=OFF \
-DTPL_ENABLE_MPI=ON \
-DMPI_USE_COMPILER_WRAPPERS=ON \
-DMPI_EXEC="mpirun" \
-DMPI_EXEC_NUMPROCS_FLAG="-np" \
-DMPI_EXEC_POST_NUMPROCS_FLAGS:STRING="-bind-to;none" \
$TRILINOS_DIR

make -j20

ctest -R streams_hb_belos_MPI_4
```

**Comment by ndellingwood** [comment]
This also failed in cuda/11.2.2 build with uvm enabled

**Comment by ndellingwood** [comment]
Just to update, this test has been failing consistently and reliably in Hip and Cuda+UVM builds since posting

**Comment by cgcgcg** [comment]
@vqd8a Are you the best person to look into this?

**Comment by vqd8a** [comment]
@ndellingwood @cgcgcg I am trying to.

**Comment by cgcgcg** [comment]
Great, thank you @vqd8a !

**Comment by ndellingwood** [comment]
@vqd8a with the Cuda+UVM job, I am running with `ctest -j2` (i.e. tests running in parallel); it could be that the tests are in contention for resources and just need to be marked with RUN_SERIAL option - if that is all that's needed I can do that local to my job

This is not the case with the Hip builds though, no parallelism when running those tests

**Comment by vbrunini** [comment]
Pretty sure this was my fault, I was able to replicate those tests failing and the addition of a few fences got them working again for me with #13184
