### ISSUE TITLE
Ifpack2: More modular software architecture (esp. triangular solves & ILU)

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#131]
@trilinos/ifpack2 @trilinos/amesos2 

This relates to the recent addition of Basker's thread-parallel incomplete LU factorization (ILU) to `Ifpack2::RILUK`.  I really appreciate all the work that people are doing in Ifpack2 to improve support for thread parallelism.  

What I see happening is that a lot of us are patching what amount to entirely new preconditioners, into existing classes.  I've been doing that with BlockCrsMatrix, and others have been doing that with other classes.  I think that's OK for prototyping, but I worry that eventually it will make the classes super complicated.  It may also add complication time.

It would be good to remember LinearSolver and LinearSolverFactory at this point.  We already have plenty of different ways to achieve abstraction.  For example, maybe it's appropriate to treat thread-parallel sparse triangular solves as an "inner solver."  If we don't want to expose a new solver in Ifpack2's public interface, we can put it in the `Ifpack2::Details` namespace.  I'm not sure if we have to worry about it for Basker, but I want people to keep this in mind going forward.

Thanks all!

**Comment by jdbooth** [comment]
Hi Mark,

Yes, I agree we should come up with a method to keep the interface classes for ifpack2 clean.  It would be great to sit down and come up with a plan for abstract that fits everyone's needs (Though nothing will make everyone happy). I honestly was surprised at the layout when looking at some of the classes.  It seems like the implementation in the past where blended with the interfaces.  Though, one might not have thought we would have multiple different implementations for one particular type of precondition interface.  However, we will in the future, such as ILU - serial (RILUK already there), ILU -cpu/phi (Basker), ILU - GPU (FAST - Siva/Erik version of Edmond's code) 

@trilinos/ifpack2

**Comment by egboman** [comment]
Perhaps it would be better if each algorithm is in a separate class, even if they conceptually do the same thing? This is probably better from a software point of view, but my concern is that users may be confused if there are say 3-6 different classes for ILU preconditioners.

**Comment by srajama1** [comment]
This is tricky. Let us talk.

**Comment by hcedwar** [comment]
Perhaps the strategy we use in Kokkos with a single non-virtual public interface class that has a template policy/property parameter to select the algorithmic variant.

**Comment by srajama1** [comment]
Yep, that is what I am thinking.

**Comment by mhoemmen** [comment]
Users wouldn't see multiple classes; they would live in Ifpack2::Details (implementation namespace).  No need for template polymorphism; all this is coarse-grained.

On Feb 6, 2016, at 12:30 AM, Erik Boman <notifications@github.com<mailto:notifications@github.com>> wrote:


Perhaps it would be better if each algorithm is in a separate class, even if they conceptually do the same thing? This is probably better from a software point of view, but my concern is that users may be confused if there are say 3-6 different classes for ILU preconditioners.

-

**Comment by srajama1** [comment]
It is the same discussion we had in SGS a week ago. Eventually it would be nice to choose the algorithm based on the type, but for now we need to deliver these codes to customers in two weeks or so. Excuse the mess for few weeks, not just here in SGS and other places.

**Comment by mhoemmen** [comment]
> Excuse the mess for few weeks, not just here in SGS and other places.

Unfortunately Github doesn't appear to have a way to prioritize issues, or I would make this one lower priority :-)  I just want it out there so we remember to come back to it later.

**Comment by mhoemmen** [comment]
> Perhaps the strategy we use in Kokkos with a single non-virtual public interface class that has a template policy/property parameter to select the algorithmic variant.

It's OK for Ifpack2 to pick the algorithmic variant using run-time parameters and/or run-time polymorphism.  Ifpack2 operations are coarse grained -- e.g., "set up the preconditioner," "apply the preconditioner" -- so we can afford a virtual method call or checking a parameter.  The point is really to keep the code short and clean, and keep compilation times down.

**Comment by maherou** [comment]
We are experimenting with Kanban APIs for GitHub issues.  This tool enables enhanced interaction with GitHub issues, including a size metric.

https://waffle.io/trilinos/Trilinos

You can use this API for easier interaction with issues.

Mike

**Comment by eric-c-cyr** [comment]
Thanks Mark! Its important to realize that often time the compile time solution is good for libraries is terrible for applications that tend to like dynamic structure (why wouldn't I want to be able to choose between preconditioners at run time). In general each additional template parameter at a low level is a huge code burden for the application at a high level.

**Comment by mhoemmen** [comment]
In this particular case, there is no benefit to using compile-time polymorphism, because these are coarse-grained operations.  We don't need to inline through them, for example, and we only need to support template parameter combinations that Tpetra supports.

The two levels of KokkosKernels kernels are meant, actually, to reduce the number of template parameter combinations that Trilinos must build.  The outer level strips away the variations and assigns to particular View types, so the inner level only gets instantiated for those types.  The inner level actually implements the kernel; the outer just checks inputs and assigns Views.

On Feb 6, 2016, at 1:25 PM, eric-c-cyr <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks Mark! Its important to realize that often time the compile time solution is good for libraries is terrible for applications that tend to like dynamic structure (why wouldn't I want to be able to choose between preconditioners at run time). In general each additional template parameter at a low level is a huge code burden for the application at a high level.

-

**Comment by srajama1** [comment]
I see that point for fewer template parameters, but this is a different case. Ideally, I would have liked tempting just for types, but that boat is long gone :) These are *not* new template parameters. I was thinking of just using existing ones (say Device) to pick the algorithms. Some device and algorithm combination won't even make sense. I can check at compile time and error out, but then the user has to have the knowledge of what make algorithm makes sense where. Edge based coloring and some X algorithm in GPU vs Vertex based algorithm and Y algorithm in GPU. How can we avoid the users having to understand these and set the parameters correctly at runtime based on what is compiled ?

**Comment by eric-c-cyr** [comment]
Why wouldn't you still do that and simply not "offer" the particular algorithm to the user (at runtime) through the dynamic interface? No need to error out at compile time. Perhaps I'm missing something.

**Comment by srajama1** [comment]
May be I am the one missing something. Let us talk in person so I can understand what you mean.

**Comment by mhoemmen** [comment]
Discussion has been good.  I think we can close this overarching issue and focus on the individual cases.  Thanks all!
