### ISSUE TITLE
MueLu: Screen output #active processes wrong

### ISSUE THREAD

**Issue by tawiesn** [trilinos/Trilinos#1310]
I noticed that the screen output for #active processes is wrong (off by one)

Using 1 processor (serial) i get

>  Ptent Load balancing info
>  Ptent   # active processes: 2/1

It should be 

>  Ptent Load balancing info
>  Ptent   # active processes: 1/1

Using 2 processors i get

>  Ptent Load balancing info
>  Ptent   # active processes: 3/2

instead of

>  Ptent Load balancing info
>  Ptent   # active processes: 2/2

@trilinos/muelu @jhux2

**Comment by jhux2** [comment]
Yes, I saw this yesterday.  Checkin script is running as we speak (well, type).

**Comment by lucbv** [comment]
@tawiesn that is possibly related to some changes I did in the statistics output in commit 3503780.
Do you want me to check there?

**Comment by aprokop** [comment]
@lucbv Yeah, it seems that patch did not reset `numActiveProcs` to 0 inside `#ifdef HAVE_MPI` clause.

**Comment by jhux2** [comment]
Should be fixed with commit 6c70b55.

**Comment by aprokop** [comment]
@jhux2 Bonus points for checking `numRows == 0`. The only thoughts about that are: empty matrix passed by a user, or all rows are Dirichlet at some point (but it will probably break earlier).

**Comment by jhux2** [comment]
@aprokop Actually, my commit is not right for the serial case.  If ```numRows==0```, then ```numActiveprocs=0```, and the statistics in the later lines will crash due to division by 0.

**Comment by lucbv** [comment]
@jhux2 why would we have `numRows==0` in the serial case? This seems to only happen if you have an empty matrix.
Also where are we dividing by zero, I thought that all the divisions are guarded with tertiary operators.

**Comment by jhux2** [comment]
> Also where are we dividing by zero, I thought that all the divisions are guarded with tertiary operators

@lucbv Ah, you are correct.  I'll close this issue, then.
