### ISSUE TITLE
Ifpack2: Defaults for Relaxation type preconditioners

### ISSUE THREAD

**Issue by egphill** [trilinos/Trilinos#1311]
In Thyra_Ifpack2PreconditionerFactory_def.hpp, there is logic setting the "schwarz: overlap level" parameter if it isn't already set. This parameter is not in the set of valid parameters for Relaxation type preconditioners, so an error is thrown during validation for relaxation preconditioners.

**Comment by mhoemmen** [comment]
@trilinos/ifpack2 @trilinos/thyra

**Comment by bartlettroscoe** [comment]
@egphill, can you provide more details? We need to see why there is not an automated test for this use case.

**Comment by egphill** [comment]
@bartlettroscoe, I'm trying to call a Jacobi preconditioner from Ifpack2 through Teko within Drekar. The parameter list being given to Thyra::Ifpack2PreconditionerFactory is

>             <ParameterList name="Jacobi Mass">
>               <Parameter name="Prec Type"                               type="string"   value="Relaxation"/>
>               <ParameterList name="Ifpack2 Settings">
>                 <Parameter name="relaxation: type"                      type="string"   value="Jacobi"/>
>               </ParameterList>
>             </ParameterList>

And the error I'm getting is

>   *** THROWN EXCEPTION ***
>   Error, the parameter {name="schwarz: overlap level",type="int",value="0"}
>   in the parameter (sub)list "SimpleEM Parameters->Linear Solver->Preconditioner Types->Teko->Inverse Factory Library->Jacobi Mass->Ifpack2 Settings"
>   was not found in the list of valid parameters!
>   
>   The valid parameters and types are:
>     {
>       "relaxation: type" : string = Jacobi
>       "relaxation: sweeps" : int = 1
>       "relaxation: damping factor" : double = 1
>       "relaxation: zero starting solution" : bool = 1
>       "relaxation: backward mode" : bool = 0
>       "relaxation: use l1" : bool = 0
>       "relaxation: l1 eta" : double = 1.5
>       "relaxation: min diagonal value" : double = 0
>       "relaxation: fix tiny diagonal entries" : bool = 0
>       "relaxation: check diagonal entries" : bool = 0
>       "relaxation: local smoothing indices" : Teuchos::ArrayRCP<int> = Teuchos::ArrayRCP<int>{ptr=0,lowerOffset=0,upperOffset=-1,size=0,node=0,strong_count=0,weak_count=0}
>     }

From what I've gathered, a validateParametersAndSetDefaults() is called in Ifpack2PreconditionerFactory::setParameterList() which sets Overlap = 0 in my "Jacobi Mass" parameter list. Then within the if statement at Thyra_Ifpack2PreconditionerFactory_def.hpp:175, because "Overlap" has been set, "schwarz: overlap level" gets set in the "Ifpack2 Settings" parameter list.

**Comment by bartlettroscoe** [comment]
@etphipp, I would have to look at how the PL is being handled to see if it is reasonble.  But since I did not write or modify any of this code, as shown by:

```
$ git shortlog -ns -- packages/ifpack2/adapters/thyra/
     7  Mark Hoemmen
     2  Brent M. Perschbacher
     1  Julien Cortial
     1  Sidafa Conde
```

it would take me some time to ramp up on this.

@mhoemmen, do you have an idea how to resolve this?

**Comment by mhoemmen** [comment]
Could we just take out the "set defaults" part of that?  I don't recall doing serious work on Thyra's Ifpack2 adapters; I may have just reformatted or added a new parameter.  Is it Ifpack2 that throws, or Thyra?  If it's Ifpack2::Relaxation, we could just change how it validates.  I'm not sure if it would break Thyra to get rid of the "set defaults" part.

**Comment by egphill** [comment]
Taking out the "set defaults" in the Thyra adapter does fix my use case. Removing the logic that sets "schwarz: overlap level" also works. I'm just not sure how much those options affect other use cases. The exception is thrown in Ifpack2::Relaxation, so changing the validation there would also work.

**Comment by mhoemmen** [comment]
Is there a failing test?  I've got a lot on my plate and want to help fix this, but I'm not sure where to start.

**Comment by egphill** [comment]
@mhoemmen There is not a failing test checked in, unfortunately. I can modify a Teko test pretty easily to reproduce the error and send you a patch if that helps.

**Comment by mhoemmen** [comment]
@egphill also please make sure that the test does not depend on too many TPLs; thanks :-)

**Comment by aprokop** [comment]
Another interesting tidbit about defaults in Thyra: the default for Ifpack2 solver is `ILUT`.

**Comment by mhoemmen** [comment]
Please reopen if this is still an issue.
