### ISSUE TITLE
Zoltan2 partitioning metrics return scalar_t; should return double

### ISSUE THREAD

**Issue by kddevin** [trilinos/Trilinos#1312]
Zoltan2's partitioning metrics class EvaluatePartition returns, among other things, imbalance values.  Imbalance is inherently a float or double.  While scalar_t is often float or double, it could be int.  When scalar_t is int, returning imbalance as an int is inaccurate. 

It appears that currently, all metrics are stored as scalar_t.  We could store them as double instead.
@trilinos/zoltan2

**Comment by mhoemmen** [comment]
Would this imply not needing to instantiate CrsMatrix for Scalar=int?  That would be nice :-)

**Comment by kddevin** [comment]
No; sorry.  This change wouldn't affect our use of CrsMatrix.  But the proposed directory work that you and I discussed separately would likely reduce our dependence on CrsMatrix.
