### ISSUE TITLE
Ioss: missing header

### ISSUE THREAD

**Issue by ikalash** [trilinos/Trilinos#13134]
It appears there is a missing header included in an Ioss file that is causing Albany build failures:

```
/projects/albany/nightlyCDashWeaver/build/TrilinosInstall/include/Ioss_Field.h:12:10: fatal error: fmt/ostream.h: No such file or directory
```

https://sems-cdash-son.sandia.gov/cdash/viewBuildError.php?buildid=91235

**Comment by overfelt** [comment]
Same for the SPARC project. There is a new include of a header file. The header file is in the Seacas directories but the header file is not marked for installation so Seacas builds but later the SPARC build fails when trying to find the file.

**Comment by gsjaardema** [comment]
I will fix tonight or tomorrow. Should not be using fmt inpblic headers in tailings until we have fmt as TPL.

**Comment by ikalash** [comment]
@gsjaardema : thank you!  I will keep an eye out for your fix.

**Comment by spdomin** [comment]
I executed a Nalu build and still see this error on: 

`commit cbd6987eb1a444d5203ec7a8e9e6c79d04d7a884 (HEAD -> develop, origin/develop)
Merge: 8614dae2bd2 9fefc29a3d3
Author: Curtis Ober <ccober@sandia.gov>
Date:   Tue Jun 25 08:14:45 2024 -0600
`
I will double check...

**Comment by gsjaardema** [comment]
Should be fixed once #13155 is merged...

**Comment by ikalash** [comment]
Thank you @gsjaardema !  I will give it a try once the PR is merged.

**Comment by spdomin** [comment]
I will add this comment directly to the issue, not the PR:

I have checked that BUILT_IN_SIERRA has not been defined in my build/test process and neither appears in the Trilinos config step nor the Nalu step.

fgs/spdomin/nightly/scratch_build/install/gcc10.3.0/Trilinos_nightly_release/include/Ioss_Region.h:26:10: fatal error: fmt/ostream.h: No such file or directory 26 | #include <fmt/ostream.h> 
Above, the line number matches the code that is ifdef out.

**Comment by gsjaardema** [comment]
Sorry, I missed that one ans assumed the Ioss_Field.h was the only one.  I will fix this tonight and then try to make it more robust for the next snapshot.

**Comment by overfelt** [comment]
Thanks, @gsjaardema , this fixed the SPARC build.

**Comment by spdomin** [comment]
Yes, we are good as well - feel free to close (unless you need Albany)
`100% tests passed, 0 tests failed out of 84
Trilinos/develop SHA1: bb26eaf1b306f64ee5adb2d8fb001e529a66d39d`

**Comment by ikalash** [comment]
This has been resolved - thank you!  Note that we still have an Ioss-related issue in our warning-free build: https://github.com/trilinos/Trilinos/issues/13168 .
