### ISSUE TITLE
[Tempus] WrapperModelEvaluator: add W_prec capability

### ISSUE THREAD

**Issue by bartgol** [trilinos/Trilinos#1313]
Currently, the ResidualModelEvaluator does not do anything to allow the use of W_prec. NOX has two ways to get a preconditioner from the model: through `model_->create_W_prec()` and through `model_->get_W_factory()->getPreconditionerFactory()->createPrec()` (assuming the prec factory is nonnull). Without the support for W_prec in ResidualModelEvaluator, in order to get NOX to use a preconditioner one must force his/her transientModel object to return a lows factory that does have a valid preconditioner factory

However, this is not always convenient/safe. One may want to always use his/her particular preconditioner for the problem at hand, and writing such a generic structure as a preconditioner factory for just one preconditioner seems too big of a hassle (besides not forcing the user to use the particular preconditioner for the problem). He/she may be better off writing the create_W_prec method in his/her model evaluator, and be done with it.

To fix this, I suggest to add the following lines to the method createOutArgsImpl of ResidualModelEvaluator

```
   MEB::OutArgsSetup<Scalar> transientOutArgs = transientModel_->createOutArgs();
   if (transientOutArgs.supports(MEB::OUT_ARG_W_prec))
   {
     outArgs.setSupports(MEB::OUT_ARG_W_prec);
   }
```

add this method to the class

```
     Teuchos::RCP<Thyra::PreconditionerBase<Scalar> > create_W_prec() const
          { return transientModel_->create_W_prec(); }
```

and finally add these lines in the evalModelImpl method (right before the call to evalModel of the transientModel)

```
   if (outArgs.supports(MEB::OUT_ARG_W_prec) && transientOutArgs.supports(MEB::OUT_ARG_W_prec))
   {
     transientOutArgs.set_W_prec(outArgs.get_W_prec());
   }

```
(the second part in the if may be redundant, I'm not sure).

**Comment by bartlettroscoe** [comment]
CC: @trilinos/thyra, @trilinos/nox

**Comment by bartgol** [comment]
Pinging the Tempus team, and changing the name of the issue, since the class ResidualModelEvaluator does not exist anymore, replaced by WrapperModelEvaluator.

The issue still exists. I am willing to add the missing lines to WrapperModelEvaluator, if the team is busy.

**Comment by ccober6** [comment]
@bartgol, definitely apologize for the tardiness on this issue.  I think this good, and if you can put it in, that would be great.  I would double check it with @rppawlo.

**Comment by bartgol** [comment]
@ccober6 no worries. With so many issues around (and other projects too), it happens that a few slip through the cracks.

I'm compiling a little branch, and will do a PR as soon as I can check the fix works.

**Comment by bartgol** [comment]
@ccober6 I've created a PR, hopefully I followed all the guidelines correctly (I've never contributed to trilinos before). I did not run tests, as I believe this should not break anything, since it only adds a functionality to WrapperModelEvaluatorBasic.

**Comment by bartlettroscoe** [comment]
Simply not breaking existing tests is not enough.  Typically, new tests should be added to cover new functionality.  See:

* https://github.com/trilinos/Trilinos/wiki/Trilinos-Testing-Policy

**Comment by bartgol** [comment]
@bartlettroscoe Turns out one of the tests did fail. However, the test failed saying (basically) that the functionality I introduced was not yet supported. Since it is now supported, I think that test is now indeed testing the new functionality.

Perhaps @ccober6 or one of the Tempus team should double check my last statement, but I'm 90% confident is correct.
