### ISSUE TITLE
Ioss: code does not compile in warning-free build

### ISSUE THREAD

**Issue by ikalash** [trilinos/Trilinos#13168]
Albany has a nightly warning-free build, which failed compiling today due to unused variables in Ioss:

https://sems-cdash-son.sandia.gov/cdash/viewBuildError.php?buildid=100961

```
/.../repos-gcc/Trilinos/packages/seacas/libraries/ioss/src/exodus/Ioex_DecompositionData.C: In instantiation of 'void Ioex::DecompositionData<INT>::decompose_model(int, const std::string&) [with INT = long int; std::string = std::__cxx11::basic_string<char>]':
[Trilinos/packages/seacas/libraries/ioss/src/exodus/Ioex_DecompositionData.h:124](https://blob/master/Trilinos/packages/seacas/libraries/ioss/src/exodus/Ioex_DecompositionData.h#L124):10:   required from here
[Trilinos/packages/seacas/libraries/ioss/src/exodus/Ioex_DecompositionData.C:294](https://blob/master/Trilinos/packages/seacas/libraries/ioss/src/exodus/Ioex_DecompositionData.C#L294):13: error: unused variable 'status' [-Werror=unused-variable]
```

@trilinos/seacas 

Sorry @gsjaardema to keep making you fix stuff...

**Comment by ikalash** [comment]
@gsjaardema : do you have a chance to fix this sometime this week?  We are still seeing failures in our warning-free build due to unused variables in seacas: https://sems-cdash-son.sandia.gov/cdash/viewBuildError.php?buildid=119436 .

**Comment by gsjaardema** [comment]
I have a PR in place that should fix this.  Will add a better fix to SEACAS so that next snapshot won't break.  I will also see why I am not seeing the warnings in my seacas CI builds...

**Comment by gsjaardema** [comment]
I will also try to figure out why I'm not seeing the notificaitons...

**Comment by ikalash** [comment]
Thanks for fixing it!  I thought you might have been OOO around the 4th of July holiday, so I did not realize you were not receiving the notifications about the issue.  That is odd.
