### ISSUE TITLE
Please update main release (15.2?)

### ISSUE THREAD

**Issue by 3rav** [trilinos/Trilinos#13177]
Please update main release, because: https://github.com/trilinos/Trilinos/pull/12995

**Comment by 3rav** [comment]
Can I count on a new release soon?

**Comment by ccober6** [comment]
We should release Trilinos 16.0 in the next week or so.

**Comment by 3rav** [comment]
https://github.com/trilinos/Trilinos/releases/tag/trilinos-release-16-0-0
