### ISSUE TITLE
Update Request for Online Documentation

### ISSUE THREAD

**Issue by avfav1235** [trilinos/Trilinos#13189]
Dear Trilinos Team,

I am currently a student exploring the Trilinos library for HPC finite element simulations. And I’m particularly interested in the heterogeneous Tpetra and Kokkos modules and MueLu.

However, I have encountered an issue with the accessibility of updated documentation. It appears that many of the tutorials and pdfs available on [the official website](https://trilinos.github.io/getting_started.html) are outdated, and [the `dev` version of official Doxygen page](https://docs.trilinos.org/dev/packages/) is also outdated (most packages last updated before 2020).

For example, I was looking for information on the `Tpetra::FECrsMatrix` class. While I can see references to this module in the GitHub repository, it is absent from [Tpetra’s official Doxygen documentation](https://docs.trilinos.org/dev/packages/tpetra/doc/html/namespaceTpetra.html), which has not been refreshed since 2021. After extensive searching, I did find some useful resources to learn, but an updated documentation page would greatly help in accessing the latest APIs and documentations.

Thanks again for this amazing library.

**Comment by cgcgcg** [comment]
@trilinos/tpetra From what I can tell the doxygen does get regenerated on master merge. Last time was a week ago. But I don't see the FECrsMatrix either, so something isn't right.

**Comment by cgcgcg** [comment]
@avfav1235 Where do you see that the Tpetra doxygen has not been refreshed since 2021? The bottom of the page that you linked claims "Generated on Fri Jun 28 2024 09:19:10".

**Comment by avfav1235** [comment]
> @avfav1235 Where do you see that the Tpetra doxygen has not been refreshed since 2021? The bottom of the page that you linked claims "Generated on Fri Jun 28 2024 09:19:10".

I apologize for the confusion, it seems I made a mistake. I (incorrectly) assumed that the "Last modified" date on [this page](https://docs.trilinos.org/dev/packages/) represented the last time the entire folder (and all its contents) was modified, which appears not to be the case.

Regarding the original issue, the Tpetra doxygen site does list [the FECrsMatrix hpp files](https://docs.trilinos.org/dev/packages/tpetra/doc/html/Tpetra__FECrsMatrix__fwd_8hpp_source.html). However, the `FECrsMatrix` class cannot be found.

**Comment by jhux2** [comment]
Please reopen if this isn't resolved.
