### ISSUE TITLE
STK: build error with clang compiler

### ISSUE THREAD

**Issue by ikalash** [trilinos/Trilinos#13226]
In our nightly Albany testing, we are seeing an error in the clang CEE build pertaining to STK regarding a missing include: 

```
[Trilinos/packages/stk/stk_balance/stk_balance/internal/balanceTypes.hpp:38](https://blob/master/Trilinos/packages/stk/stk_balance/stk_balance/internal/balanceTypes.hpp#L38):10: fatal error: 'TpetraCore_config.h' file not found
```
https://sems-cdash-son.sandia.gov/cdash/viewBuildError.php?buildid=119502

Could someone please take a look?

**Comment by alanw0** [comment]
@ikalash do you know when this started? stk hasn't been updated in trilinos since June 3. I wonder if something changed about the tpetra configuration.
In any case, I'll see if I can reproduce this, the stk error should be a configuration error rather than a build error, if tpetra is not available...

**Comment by ikalash** [comment]
@alanw0 : it actually started today.  You can reproduce the problem by using the following modules / Trilinos configure script:

https://github.com/sandialabs/Albany/blob/master/doc/dashboards/cee-compute011.sandia.gov/sems-clang-modules.sh 
https://github.com/sandialabs/Albany/blob/master/doc/dashboards/cee-compute011.sandia.gov/do-cmake-trilinos-mpi-sems-clang

Thank you!

**Comment by alanw0** [comment]
@ikalash thanks for the pointer to the scripts, they worked perfectly.
Unfortunately I didn't reproduce the error shown on your dashboard. `make` built everything, include stk_balance.
I wonder if your nightly build just happened to run into a file-system hiccup or something?

**Comment by ikalash** [comment]
@alanw0 : could be.  I will check tomorrow what happens.

**Comment by ikalash** [comment]
The problem has gone away.  It was probably a system issue.  Closing.  Thanks for looking at it @alanw0 .
