### ISSUE TITLE
MueLu: something is wrong in IfpackSmoother

### ISSUE THREAD

**Issue by aprokop** [trilinos/Trilinos#1323]
From line 225:
```c++
        if (type_ == "LINESMOOTHING_BANDED_RELAXATION" ||
            type_ == "LINESMOOTHING_BANDED RELAXATION" ||
            type_ == "LINESMOOTHING_BANDEDRELAXATION")
          type_ = "block relaxation";
        else
          type_ = "block relaxation";
```
The `type_` is always set to `block relaxation`. A mistake?

**Comment by tawiesn** [comment]
@aprokop Thanks for pointing this out. As far as i can see this is no mistake. We just could remove the if-clause. We always need "block relaxation". There is a similar thing in the Ifpack2Smoother. This could be simplified, too.

**Comment by aprokop** [comment]
@tawiesn Sounds good. Could you please remove it? I'm not too familiar with the code.

Btw, this was caught by the PVS static analysis tool from #821.

**Comment by mhoemmen** [comment]
@csiefer2 knows about this -- I think Ifpack2::BlockRelaxation with a BandedContainer implements banded relaxation -- is that right?  @trilinos/ifpack2

**Comment by csiefer2** [comment]
Correct:  Ifpack2::BlockRelaxation with a BandedContainer implements banded relaxation.

**Comment by aprokop** [comment]
@tawiesn 

> There is a similar thing in the Ifpack2Smoother. This could be simplified, too.

The logic in `Ifpack2Smoother` seems different:

```c++
      if (type_ == "LINESMOOTHING_BANDED_RELAXATION" ||
          type_ == "LINESMOOTHING_BANDED RELAXATION" ||
          type_ == "LINESMOOTHING_BANDEDRELAXATION")
        type_ = "BANDEDRELAXATION";
      else
        type_ = "BLOCKRELAXATION";
```
