### ISSUE TITLE
Trilinos in Rocky Linux 9

### ISSUE THREAD

**Issue by deejdeej** [trilinos/Trilinos#13257]
I'm working with a faculty member trying to get Trilinos 15.1.1 working in Rocky Linux 9.  The compile seems to go okay, however the ctests return 67% tests passed, 179 tests failed out of 537.  Most of the ones that fail report SEGFAULT.

For example:  369 - AztecOO_AztecOO_test (SEGFAULT)

Running the test individually:
$ ctest -R AztecOO_AztecOO_test -VV
UpdateCTestConfiguration  from :/mnt/research/deej/src/trilinos/Trilinos-trilinos-release-15-1-1/mybuild/DartConfiguration.tcl
Parse Config file:/mnt/research/deej/src/trilinos/Trilinos-trilinos-release-15-1-1/mybuild/DartConfiguration.tcl
 Add coverage exclude regular expressions.
UpdateCTestConfiguration  from :/mnt/research/deej/src/trilinos/Trilinos-trilinos-release-15-1-1/mybuild/DartConfiguration.tcl
Parse Config file:/mnt/research/deej/src/trilinos/Trilinos-trilinos-release-15-1-1/mybuild/DartConfiguration.tcl
Test project /mnt/research/deej/src/trilinos/Trilinos-trilinos-release-15-1-1/mybuild
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 369
    Start 369: AztecOO_AztecOO_test

369: Test command: /mnt/research/deej/src/trilinos/Trilinos-trilinos-release-15-1-1/mybuild/packages/aztecoo/test/AztecOO/AztecOO_AztecOO_test.exe "-v"
369: Working Directory: /mnt/research/deej/src/trilinos/Trilinos-trilinos-release-15-1-1/mybuild/packages/aztecoo/test/AztecOO
369: Test timeout computed to be: 1500
369: Initial 2-norm of b-A*x: 11.4018
369: testing recursive solve (AztecOO as preconditioner for another AztecOO).
1/2 Test #369: AztecOO_AztecOO_test .............***Exception: SegFault  0.13 sec
test 376
    Start 376: AztecOO_AztecOO_test_LL

376: Test command: /mnt/research/deej/src/trilinos/Trilinos-trilinos-release-15-1-1/mybuild/packages/aztecoo/test/AztecOO_LL/AztecOO_AztecOO_test_LL.exe "-v"
376: Working Directory: /mnt/research/deej/src/trilinos/Trilinos-trilinos-release-15-1-1/mybuild/packages/aztecoo/test/AztecOO_LL
376: Test timeout computed to be: 1500
376: Initial 2-norm of b-A*x: 11.4018
376: testing recursive solve (AztecOO as preconditioner for another AztecOO).
2/2 Test #376: AztecOO_AztecOO_test_LL ..........***Exception: SegFault  0.12 sec

0% tests passed, 2 tests failed out of 2

Subproject Time Summary:
AztecOO    =   0.25 sec*proc (2 tests)

Total Test time (real) =   1.45 sec

The following tests FAILED:
	369 - AztecOO_AztecOO_test (SEGFAULT)
	376 - AztecOO_AztecOO_test_LL (SEGFAULT)
Errors while running CTest
Output from these tests are in: /mnt/research/deej/src/trilinos/Trilinos-trilinos-release-15-1-1/mybuild/Testing/Temporary/LastTest.log
Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.

LastTest.log contains:

$ cat LastTest.log 
Start testing: Jul 18 13:22 EDT
----------------------------------------------------------
369/537 Testing: AztecOO_AztecOO_test
369/537 Test: AztecOO_AztecOO_test
Command: "/mnt/research/deej/src/trilinos/Trilinos-trilinos-release-15-1-1/mybuild/packages/aztecoo/test/AztecOO/AztecOO_AztecOO_test.exe" "-v"
Directory: /mnt/research/deej/src/trilinos/Trilinos-trilinos-release-15-1-1/mybuild/packages/aztecoo/test/AztecOO
"AztecOO_AztecOO_test" start time: Jul 18 13:22 EDT
Output:
----------------------------------------------------------
Initial 2-norm of b-A*x: 11.4018
testing recursive solve (AztecOO as preconditioner for another AztecOO).
<end of output>
Test time =   0.13 sec
----------------------------------------------------------
Test Failed.
"AztecOO_AztecOO_test" end time: Jul 18 13:22 EDT
"AztecOO_AztecOO_test" time elapsed: 00:00:00
----------------------------------------------------------

376/537 Testing: AztecOO_AztecOO_test_LL
376/537 Test: AztecOO_AztecOO_test_LL
Command: "/mnt/research/deej/src/trilinos/Trilinos-trilinos-release-15-1-1/mybuild/packages/aztecoo/test/AztecOO_LL/AztecOO_AztecOO_test_LL.exe" "-v"
Directory: /mnt/research/deej/src/trilinos/Trilinos-trilinos-release-15-1-1/mybuild/packages/aztecoo/test/AztecOO_LL
"AztecOO_AztecOO_test_LL" start time: Jul 18 13:22 EDT
Output:
----------------------------------------------------------
Initial 2-norm of b-A*x: 11.4018
testing recursive solve (AztecOO as preconditioner for another AztecOO).
<end of output>
Test time =   0.12 sec
----------------------------------------------------------
Test Failed.
"AztecOO_AztecOO_test_LL" end time: Jul 18 13:22 EDT
"AztecOO_AztecOO_test_LL" time elapsed: 00:00:00
----------------------------------------------------------

End testing: Jul 18 13:22 EDT

AztecOO =   0.25 sec*proc

Trilinos was built with:
TRILINOS_HOME=/mnt/research/deej/src/trilinos/Trilinos-trilinos-release-15-1-1
        
cmake \
  -D Trilinos_ENABLE_TESTS=ON \
  -D CMAKE_BUILD_TYPE=DEBUG \
  -D CMAKE_INSTALL_PREFIX:PATH=/mnt/local/trilinos-15.1.1 \
  -D Trilinos_ENABLE_ALL_PACKAGES=OFF \
  -D TPL_ENABLE_MPI=OFF \
  -D BUILD_SHARED_LIBS=ON \
  -D Trilinos_ENABLE_Fortran=ON \
  -D Trilinos_ENABLE_Teuchos=ON \
  -D Trilinos_ENABLE_Tpetra=ON \
  -D Trilinos_ENABLE_Epetra=ON \
  -D Trilinos_ENABLE_EpetraExt=ON \
  -D Trilinos_ENABLE_AztecOO=ON \
  -D Trilinos_ENABLE_Ifpack=ON \
  -D Trilinos_ENABLE_ML=ON \
  -D Trilinos_ENABLE_Amesos=ON \
  -D Trilinos_ENABLE_NOX=ON \
  ${TRILINOS_HOME}

As a side note the above build worked fine on Rocky Linux 8 using Trilinos 13.2.0.  We tried 13.2.0 on Rocky Linux 9 but it also gives lots of segmentation faults on many of the packages.

Any suggestions as to how to troubleshoot this?

Thank you.

**Comment by cgcgcg** [comment]
You could try to get actual test output from a failing test, or even run them using gdb.

I need to point out that all these packages will get dropped from Trilinos in the near future.

**Comment by deejdeej** [comment]
Could you clarify what you mean by "actual test output"?  I'm happy to try running whatever you think may help to debug this.  

The faculty member is aware that these packages are slated to be dropped in the future, but that is what his workflow uses at the moment.  Trying to do what I can to help him.

**Comment by deejdeej** [comment]
$ gdb -q --args ./AztecOO_AztecOO_test.exe -v
Reading symbols from ./AztecOO_AztecOO_test.exe...
(gdb) run
Starting program: /mnt/research/deej/src/trilinos/Trilinos-trilinos-release-15-1-1/mybuild/packages/aztecoo/test/AztecOO/AztecOO_AztecOO_test.exe -v
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Initial 2-norm of b-A*x: 11.4018
testing recursive solve (AztecOO as preconditioner for another AztecOO).

Program received signal SIGSEGV, Segmentation fault.
0x00001555541f8df0 in ddot_ () from /lib64/libblas.so.3
Missing separate debuginfos, use: dnf debuginfo-install blas-3.9.0-10.el9.x86_64 lapack-3.9.0-10.el9.x86_64
(gdb) 


# dnf debuginfo-install blas-3.9.0-10.el9.x86_64 lapack-3.9.0-10.el9.x86_64
enabling epel-debuginfo repository
enabling epel-cisco-openh264-debuginfo repository
enabling extras-debuginfo repository
enabling rpmfusion-free-updates-debuginfo repository
enabling rpmfusion-nonfree-updates-debuginfo repository
Last metadata expiration check: 0:03:01 ago on Thu 18 Jul 2024 02:45:11 PM EDT.
Could not find debuginfo package for the following installed packages: blas-3.9.0-10.el9.x86_64, lapack-3.9.0-10.el9.x86_64
Could not find debugsource package for the following installed packages: blas-3.9.0-10.el9.x86_64, lapack-3.9.0-10.el9.x86_64
Dependencies resolved.
Nothing to do.
Complete!

**Comment by cgcgcg** [comment]
Sorry, what I meant is the following. Instead of running using `ctest` you could do `ctest -V`. But it seems that that particular test didn't actually give you any additional output. Do any of the other tests give you more with gdb? If not, you're best bet is to build with `-D CMAKE_BUILD_TYPE=Debug` to get debug symbols and additional debug checks.

**Comment by deejdeej** [comment]
Thank you.  This was already built with "-D CMAKE_BUILD_TYPE=DEBUG".   

This one is interesting.  Segfaults running it from the command line directly, but seems to run fine through gdb?

$ ./Epetra_BasicPerfTest_test.exe "16" "12" "1" "1" "25" "-v"
Epetra in Trilinos 15.1.1

Epetra::Comm::Processor 0 of 1 total processors.
 Number of local nodes in X direction  = 16
 Number of local nodes in Y direction  = 12
 Number of global nodes in X direction = 16
 Number of global nodes in Y direction = 12
 Number of local nonzero entries       = 4800
 Number of global nonzero entries      = 4800
 Number of Processors in X direction   = 1
 Number of Processors in Y direction   = 1
 Number of Points in stencil           = 25


*************** Results for 1 RHS with  dynamic profile
Time to insert matrix values = 0.000421
Time to complete fill        = 0.000275
Time to create Jagged diagonal matrix = 0.000205
Segmentation fault (core dumped)


$ gdb -q --args ./Epetra_BasicPerfTest_test.exe "16" "12" "1" "1" "25" "-v"
Reading symbols from ./Epetra_BasicPerfTest_test.exe...
(gdb) run
Starting program: /mnt/research/deej/src/trilinos/Trilinos-trilinos-release-15-1-1/mybuild/packages/epetra/test/BasicPerfTest/Epetra_BasicPerfTest_test.exe 16 12 1 1 25 -v
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Epetra in Trilinos 15.1.1

Epetra::Comm::Processor 0 of 1 total processors.
 Number of local nodes in X direction  = 16
 Number of local nodes in Y direction  = 12
 Number of global nodes in X direction = 16
 Number of global nodes in Y direction = 12
 Number of local nonzero entries       = 4800
 Number of global nonzero entries      = 4800
 Number of Processors in X direction   = 1
 Number of Processors in Y direction   = 1
 Number of Points in stencil           = 25


*************** Results for 1 RHS with  dynamic profile
Time to insert matrix values = 0.000436
Time to complete fill        = 0.000285
Time to create Jagged diagonal matrix = 0.000203
ResNorm = 0: Total MFLOPs for 10  Jagged Diagonal MatVec's with (Trans = 0) 449.375 (0.000192 s)
ResNorm = 0: Total MFLOPs for 10  Jagged Diagonal MatVec's with (Trans = 1) 447.047 (0.000193 s)
ResNorm = 0: Total MFLOPs for 10 old MatVec's with dynamic Profile (Trans = 0)  and without optimized storage = 371.897 (0.000232 s)
ResNorm = 0: Total MFLOPs for 10 new MatVec's with dynamic Profile (Trans = 0)  and without optimized storage = 451.728 (0.000191 s)
ResNorm = 0: Total MFLOPs for 10 old MatVec's with dynamic Profile (Trans = 1)  and without optimized storage = 308.143 (0.00028 s)
ResNorm = 0: Total MFLOPs for 10 new MatVec's with dynamic Profile (Trans = 1)  and without optimized storage = 408.91 (0.000211 s)
ResNorm = 0: Total MFLOPs for 10 old MatVec's with dynamic Profile (Trans = 0)  and with    optimized storage = 355.062 (0.000243 s)
ResNorm = 0: Total MFLOPs for 10 new MatVec's with dynamic Profile (Trans = 0)  and with    optimized storage = 595.034 (0.000145 s)
ResNorm = 0: Total MFLOPs for 10 old MatVec's with dynamic Profile (Trans = 1)  and with    optimized storage = 253.021 (0.000341 s)
ResNorm = 0: Total MFLOPs for 10 new MatVec's with dynamic Profile (Trans = 1)  and with    optimized storage = 420.878 (0.000205 s)
Time to insert matrix values = 0.000304
Time to complete fill        = 0.000101
Time to insert matrix values = 0.00034
Time to complete fill        = 0.000134
ResNorm = 0: Total MFLOPs for 10  Lower solves dynamic Profile (Trans = 0)  and without opt storage = 312.917 (0.000144 s)
ResNorm = 0: Total MFLOPs for 10  Upper solves dynamic Profile (Trans = 0)  and without opt storage = 489.783
ResNorm = 0: Total MFLOPs for 10  Lower solves dynamic Profile (Trans = 1)  and without opt storage = 425.094 (0.000106 s)
ResNorm = 0: Total MFLOPs for 10  Upper solves dynamic Profile (Trans = 1)  and without opt storage = 441.765
ResNorm = 0: Total MFLOPs for 10  Lower solves dynamic Profile (Trans = 0)  and with    opt storage = 523.953 (8.6e-05 s)
ResNorm = 0: Total MFLOPs for 10  Upper solves dynamic Profile (Trans = 0)  and with    opt storage = 542.892
ResNorm = 0: Total MFLOPs for 10  Lower solves dynamic Profile (Trans = 1)  and with    opt storage = 489.783 (9.2e-05 s)
ResNorm = 0: Total MFLOPs for 10  Upper solves dynamic Profile (Trans = 1)  and with    opt storage = 375.5

Total MFLOPs for 10 Norm2's= 640
Total MFLOPs for 10 Dot's  = 1920
Total MFLOPs for 10 Updates= 768

*************** Results for 2 RHS with  dynamic profile
Time to insert matrix values = 0.000246
Time to complete fill        = 0.00026
Time to create Jagged diagonal matrix = 0.000147
ResNorm = 0: Total MFLOPs for 10  Jagged Diagonal MatVec's with (Trans = 0) 522.909 (0.00033 s)
ResNorm = 0: Total MFLOPs for 10  Jagged Diagonal MatVec's with (Trans = 1) 510.533 (0.000338 s)
ResNorm = 0: Total MFLOPs for 10 old MatVec's with dynamic Profile (Trans = 0)  and without optimized storage = 394.874 (0.000437 s)
ResNorm = 0: Total MFLOPs for 10 new MatVec's with dynamic Profile (Trans = 0)  and without optimized storage = 634.412 (0.000272 s)
ResNorm = 0: Total MFLOPs for 10 old MatVec's with dynamic Profile (Trans = 1)  and without optimized storage = 333.772 (0.000517 s)
ResNorm = 0: Total MFLOPs for 10 new MatVec's with dynamic Profile (Trans = 1)  and without optimized storage = 433.568 (0.000398 s)
ResNorm = 0: Total MFLOPs for 10 old MatVec's with dynamic Profile (Trans = 0)  and with    optimized storage = 471.475 (0.000366 s)
ResNorm = 0: Total MFLOPs for 10 new MatVec's with dynamic Profile (Trans = 0)  and with    optimized storage = 605.474 (0.000285 s)
ResNorm = 0: Total MFLOPs for 10 old MatVec's with dynamic Profile (Trans = 1)  and with    optimized storage = 325.585 (0.00053 s)
ResNorm = 0: Total MFLOPs for 10 new MatVec's with dynamic Profile (Trans = 1)  and with    optimized storage = 534.241 (0.000323 s)
Time to insert matrix values = 0.000335
Time to complete fill        = 0.0001
Time to insert matrix values = 0.000292
Time to complete fill        = 0.000103
ResNorm = 0: Total MFLOPs for 10  Lower solves dynamic Profile (Trans = 0)  and without opt storage = 592.895 (0.000152 s)
ResNorm = 0: Total MFLOPs for 10  Upper solves dynamic Profile (Trans = 0)  and without opt storage = 613.061
ResNorm = 0: Total MFLOPs for 10  Lower solves dynamic Profile (Trans = 1)  and without opt storage = 439.61 (0.000205 s)
ResNorm = 0: Total MFLOPs for 10  Upper solves dynamic Profile (Trans = 1)  and without opt storage = 446.139
ResNorm = 0: Total MFLOPs for 10  Lower solves dynamic Profile (Trans = 0)  and with    opt storage = 574.013 (0.000157 s)
ResNorm = 0: Total MFLOPs for 10  Upper solves dynamic Profile (Trans = 0)  and with    opt storage = 421.121
ResNorm = 0: Total MFLOPs for 10  Lower solves dynamic Profile (Trans = 1)  and with    opt storage = 570.38 (0.000158 s)
ResNorm = 0: Total MFLOPs for 10  Upper solves dynamic Profile (Trans = 1)  and with    opt storage = 589.02

Total MFLOPs for 10 Norm2's= 698.182
Total MFLOPs for 10 Dot's  = 7680
Total MFLOPs for 10 Updates= 768

*************** Results for 4 RHS with  dynamic profile
Time to insert matrix values = 0.000256
Time to complete fill        = 0.00028
Time to create Jagged diagonal matrix = 0.000156
ResNorm = 0: Total MFLOPs for 10  Jagged Diagonal MatVec's with (Trans = 0) 505.3 (0.000683 s)
ResNorm = 0: Total MFLOPs for 10  Jagged Diagonal MatVec's with (Trans = 1) 569.505 (0.000606 s)
ResNorm = 0: Total MFLOPs for 10 old MatVec's with dynamic Profile (Trans = 0)  and without optimized storage = 537.57 (0.000642 s)
ResNorm = 0: Total MFLOPs for 10 new MatVec's with dynamic Profile (Trans = 0)  and without optimized storage = 634.412 (0.000544 s)
ResNorm = 0: Total MFLOPs for 10 old MatVec's with dynamic Profile (Trans = 1)  and without optimized storage = 383.041 (0.000901 s)
ResNorm = 0: Total MFLOPs for 10 new MatVec's with dynamic Profile (Trans = 1)  and without optimized storage = 491.624 (0.000702 s)
ResNorm = 0: Total MFLOPs for 10 old MatVec's with dynamic Profile (Trans = 0)  and with    optimized storage = 531.772 (0.000649 s)
ResNorm = 0: Total MFLOPs for 10 new MatVec's with dynamic Profile (Trans = 0)  and with    optimized storage = 763.54 (0.000452 s)
ResNorm = 0: Total MFLOPs for 10 old MatVec's with dynamic Profile (Trans = 1)  and with    optimized storage = 360.251 (0.000958 s)
ResNorm = 0: Total MFLOPs for 10 new MatVec's with dynamic Profile (Trans = 1)  and with    optimized storage = 629.781 (0.000548 s)
Time to insert matrix values = 0.000318
Time to complete fill        = 9.9e-05
Time to insert matrix values = 0.000317
Time to complete fill        = 9.8e-05
ResNorm = 0: Total MFLOPs for 10  Lower solves dynamic Profile (Trans = 0)  and without opt storage = 625.833 (0.000288 s)
ResNorm = 0: Total MFLOPs for 10  Upper solves dynamic Profile (Trans = 0)  and without opt storage = 538.03
ResNorm = 0: Total MFLOPs for 10  Lower solves dynamic Profile (Trans = 1)  and without opt storage = 390.976 (0.000461 s)
ResNorm = 0: Total MFLOPs for 10  Upper solves dynamic Profile (Trans = 1)  and without opt storage = 398.761
ResNorm = 0: Total MFLOPs for 10  Lower solves dynamic Profile (Trans = 0)  and with    opt storage = 709.606 (0.000254 s)
ResNorm = 0: Total MFLOPs for 10  Upper solves dynamic Profile (Trans = 0)  and with    opt storage = 747.884
ResNorm = 0: Total MFLOPs for 10  Lower solves dynamic Profile (Trans = 1)  and with    opt storage = 602.809 (0.000299 s)
ResNorm = 0: Total MFLOPs for 10  Upper solves dynamic Profile (Trans = 1)  and with    opt storage = 587.101

Total MFLOPs for 10 Norm2's= 768
Total MFLOPs for 10 Dot's  = 15360
Total MFLOPs for 10 Updates= 768

*************** Results for 8 RHS with  dynamic profile
Time to insert matrix values = 0.000244
Time to complete fill        = 0.000267
Time to create Jagged diagonal matrix = 0.000133
ResNorm = 0: Total MFLOPs for 10  Jagged Diagonal MatVec's with (Trans = 0) 558.447 (0.001236 s)
ResNorm = 0: Total MFLOPs for 10  Jagged Diagonal MatVec's with (Trans = 1) 543.924 (0.001269 s)
ResNorm = 0: Total MFLOPs for 10 old MatVec's with dynamic Profile (Trans = 0)  and without optimized storage = 615.187 (0.001122 s)
ResNorm = 0: Total MFLOPs for 10 new MatVec's with dynamic Profile (Trans = 0)  and without optimized storage = 674.062 (0.001024 s)
ResNorm = 0: Total MFLOPs for 10 old MatVec's with dynamic Profile (Trans = 1)  and without optimized storage = 394.198 (0.001751 s)
ResNorm = 0: Total MFLOPs for 10 new MatVec's with dynamic Profile (Trans = 1)  and without optimized storage = 474.066 (0.001456 s)
ResNorm = 0: Total MFLOPs for 10 old MatVec's with dynamic Profile (Trans = 0)  and with    optimized storage = 621.838 (0.00111 s)
ResNorm = 0: Total MFLOPs for 10 new MatVec's with dynamic Profile (Trans = 0)  and with    optimized storage = 797.044 (0.000866 s)
ResNorm = 0: Total MFLOPs for 10 old MatVec's with dynamic Profile (Trans = 1)  and with    optimized storage = 381.559 (0.001809 s)
ResNorm = 0: Total MFLOPs for 10 new MatVec's with dynamic Profile (Trans = 1)  and with    optimized storage = 623.523 (0.001107 s)
Time to insert matrix values = 0.000316
Time to complete fill        = 0.0001
Time to insert matrix values = 0.000308
Time to complete fill        = 9.6e-05
ResNorm = 0: Total MFLOPs for 10  Lower solves dynamic Profile (Trans = 0)  and without opt storage = 663.867 (0.000543 s)
ResNorm = 0: Total MFLOPs for 10  Upper solves dynamic Profile (Trans = 0)  and without opt storage = 599.8
ResNorm = 0: Total MFLOPs for 10  Lower solves dynamic Profile (Trans = 1)  and without opt storage = 445.587 (0.000809 s)
ResNorm = 0: Total MFLOPs for 10  Upper solves dynamic Profile (Trans = 1)  and without opt storage = 447.801
ResNorm = 0: Total MFLOPs for 10  Lower solves dynamic Profile (Trans = 0)  and with    opt storage = 810.067 (0.000445 s)
ResNorm = 0: Total MFLOPs for 10  Upper solves dynamic Profile (Trans = 0)  and with    opt storage = 722.405
ResNorm = 0: Total MFLOPs for 10  Lower solves dynamic Profile (Trans = 1)  and with    opt storage = 640.284 (0.000563 s)
ResNorm = 0: Total MFLOPs for 10  Upper solves dynamic Profile (Trans = 1)  and with    opt storage = 615.154

Total MFLOPs for 10 Norm2's= 520.678
Total MFLOPs for 10 Dot's  = 30720
Total MFLOPs for 10 Updates= 520.678
[Inferior 1 (process 545816) exited normally]
Missing separate debuginfos, use: dnf debuginfo-install blas-3.9.0-10.el9.x86_64 lapack-3.9.0-10.el9.x86_64
(gdb)

**Comment by jhux2** [comment]
The gdb trace is failing in blas.  You might try configuring/building against a reference implementation to see if that helps.

**Comment by cgcgcg** [comment]
@deejdeej Did these suggestions fix the issue? Can this be closed?

**Comment by deejdeej** [comment]
It has not been solved yet.  I'm away from work and won't be able to get back to this until next week.  Thank you for checking in.

**Comment by deejdeej** [comment]
Compiling lapack/blas from source fixed the issues we were seeing.

I used lapack-3.12.0 and compiled with:
cmake -DCMAKE_INSTALL_PREFIX=/mnt/local/lapack-3.12.0 -DBUILD_SHARED_LIBS=YES ..
cmake --build . -j --target install

and built Trilinos 15.1.1 with:

export TRILINOS_HOME=/mnt/research/deej/src/trilinos/Trilinos-trilinos-release-15-1-1
export LD_LIBRARY_PATH=/mnt/local/lapack-3.12.0/lib64:$LD_LIBRARY_PATH
        
cmake \
  -D Trilinos_ENABLE_TESTS:BOOL=ON \
  -D CMAKE_INSTALL_PREFIX:PATH=/mnt/local/trilinos-15.1.1 \
  -D CMAKE_BUILD_TYPE:STRING=RELEASE \
  -D Trilinos_ENABLE_ALL_OPTIONAL_PACKAGES:STRING=OFF \
  -D CMAKE_C_FLAGS:STRING="-lgfortran" \
  -D CMAKE_CXX_FLAGS:STRING="-lgfortran" \
  -D DART_TESTING_TIMEOUT:STRING=600 \
  -D TPL_ENABLE_MPI=OFF \
  -D TPL_ENABLE_BLAS=ON \
  -D TPL_ENABLE_LAPACK=ON \
  -D TPL_BLAS_LIBRARIES=/mnt/local/lapack-3.12.0/lib64/libblas.so \
  -D TPL_LAPACK_LIBRARIES=/mnt/local/lapack-3.12.0/lib64/liblapack.so \
  -D Trilinos_ENABLE_Fortran:BOOL=ON \
  -D Trilinos_ENABLE_Teuchos:BOOL=ON \
  -D Trilinos_ENABLE_Tpetra:BOOL=ON \
  -D Trilinos_ENABLE_Epetra:BOOL=ON \
  -D Trilinos_ENABLE_EpetraExt:BOOL=ON \
  -D Trilinos_ENABLE_AztecOO:BOOL=ON \
  -D Trilinos_ENABLE_Ifpack:BOOL=ON \
  -D Trilinos_ENABLE_ML:BOOL=ON \
  -D Trilinos_ENABLE_Amesos:BOOL=ON \
  -D Trilinos_ENABLE_NOX:BOOL=ON \
  -D Trilinos_ENABLE_Didasko:BOOL=ON \
  ${TRILINOS_HOME}

and ctest returns:
100% tests passed, 0 tests failed out of 476

Thank you for the pointers, and I just noticed Trilinos 16 was released, so I'll give that a try as well.

**Comment by cgcgcg** [comment]
Great! Thank you for taking the time to report back!

**Comment by deejdeej** [comment]
For completeness I just tested with Trilinos 16.0.0.  I get the same SEGFAULTS when using the distro supplied lapack/blas with ctest giving 74% tests passed, 125 tests failed out of 476.  It works without errors when compiling against the source built lapack/blas with 100% tests passed, 0 tests failed out of 476.

Hopefully this helps someone else save some time in the future.
