### ISSUE TITLE
Tpetra: delete deprecated headers in tpetra/core/compat for Trilinos release 16.0

### ISSUE THREAD

**Issue by jhux2** [trilinos/Trilinos#13262]
## Enhancement

A number of headers in `packages/tpetra/core/compat` are marked as deprecated.

https://github.com/trilinos/Trilinos/blob/d71aa67247678321da0b4ca2e822f28b8aed8db4/packages/tpetra/core/compat/CMakeLists.txt#L33-L42

Can they be deleted for Trilinos release 16.0?

@trilinos/tpetra @csiefer2

**Comment by cwpearson** [comment]
I think these were deprecated (by me) in https://github.com/trilinos/Trilinos/pull/11632
