### ISSUE TITLE
MueLu does not build with Epetra disabled

### ISSUE THREAD

**Issue by etphipp** [trilinos/Trilinos#133]
@trilinos/muelu 

Buiding MueLu with Epetra disabled results in this build error:

In file included from /home/etphipp/Trilinos/Trilinos/packages/muelu/adapters/stratimikos/Thyra_MueLuPreconditionerFactory_decl.hpp:84:0,
                 from /home/etphipp/Trilinos/Trilinos/packages/muelu/adapters/stratimikos/Thyra_MueLuPreconditionerFactory_def.hpp:49,
                 from /home/etphipp/Trilinos/build/opt_mpi_stokhos_nocuda/packages/muelu/adapters/ExplicitInstantiation/Thyra_MueLuPreconditionerFactory.cpp:52:
/home/etphipp/Trilinos/Trilinos/packages/muelu/adapters/xpetra/MueLu_CreateXpetraPreconditioner.hpp:18:36: fatal error: MueLu_EpetraOperator.hpp: No such file or directory
 #include <MueLu_EpetraOperator.hpp>

I commented out the include of MueLu_EpetraOperator.hpp and it appeared to compile since Epetra does not appear to be used directly in that file.  However I did not test if it works with Epetra enabled.

**Comment by tawiesn** [comment]
Thanks Eric for reporting this. May i guess? You have the serial node disabled? Which nodes do you have enabled in your configuration? We have to adapt the guards for the MueLu::EpetraOperator appropriately.

**Comment by tawiesn** [comment]
I'm preparing a fix for this. Speaking of MueLu_EpetraOperator: i suspect the guards for the node types are not fully correct in MueLu_EpetraOperator operator, which probably makes trouble if you have the serial node disabled and the OpenMP node enabled for Epetra. But this is a separate issue.

**Comment by etphipp** [comment]
I had Epetra explicitly disabled in MueLu.  I added this to my configure script a little while ago when MueLu required the Serial node when Epetra was enabled (I usually build with only the OpenMP and Cuda nodes enabled).   Maybe that's not needed anymore, but it caught this error at least.

-Eric

On Feb 7, 2016, at 9:45 AM, tawiesn <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm preparing a fix for this. Speaking of MueLu_EpetraOperator: i suspect the guards for the node types are not fully correct in MueLu_EpetraOperator operator, which probably makes trouble if you have the serial node disabled and the OpenMP node enabled for Epetra. But this is a separate issue.

-

**Comment by tawiesn** [comment]
According to the dashboard MueLu is compiling again if Epetra is disabled
