### ISSUE TITLE
MueLu: build error in warning-free build

### ISSUE THREAD

**Issue by ikalash** [trilinos/Trilinos#13317]
There are issues in the Albany warning free build again, this time from sign compare errors in MueLu. 

```
[Trilinos/packages/muelu/src/Transfers/Smoothed-Aggregation/MueLu_ReitzingerPFactory_def.hpp:265](https://blob/master/Trilinos/packages/muelu/src/Transfers/Smoothed-Aggregation/MueLu_ReitzingerPFactory_def.hpp#L265):23: error: comparison of integer expressions of different signedness: 'MueLu::ReitzingerPFactory<double, int, long long int, Tpetra::KokkosCompat::KokkosDeviceWrapperNode<Kokkos::Serial> >::LO' {aka 'int'} and 'size_t' {aka 'long unsigned int'} [-Werror=sign-compare]
```
https://sems-cdash-son.sandia.gov/cdash//viewBuildError.php?buildid=165932

Given how frequently these issues are coming up in the Albany nightlies, maybe there should be a warning-free Trilinos build in some of the CI tests that happen?

@trilinos/muelu

**Comment by cgcgcg** [comment]
This will get fixed by #13312. Also see #13308 for an effort to enable more warnings-as-errors testing for Trilinos.

**Comment by ikalash** [comment]
Thank you @cgcgcg !

**Comment by ikalash** [comment]
This issue has been resolved.  Thank you for fixing!
