### ISSUE TITLE
STK: Hanging `NgpMeshTest.volatileFastSharedCommMap` subtest with kokkos release-candidate-4.4.00

### ISSUE THREAD

**Issue by ndellingwood** [trilinos/Trilinos#13328]
## Bug Report
@alanw0 @ldh4 

### Description
When testing the Trilinos CI openmpi/4.1.6+gcc/8.5.0 configuration with the kokkos 4.4 release candidate branches I encountered a hang/deadlock in the `NgpMeshTest.volatileFastSharedCommMap` subtest of `STKUnit_tests_stk_mesh_unit_tests_MPI_4`

It looks like this was triggered due to attempts to allocate a View labeled as `CommMapIndices` within a parallel region

### Steps to Reproduce
Reproducing require use of the kokkos and kokkos-kernels develop branches (or release-candidate-4.4.00 branches ), and can be setup as follows:
```
# Repo prep
git clone -b develop https://github.com/trilinos/Trilinos.git
TRILINOS_DIR=$PWD/Trilinos
git clone -b develop https://github.com/kokkos/kokkos.git
KOKKOS_DIR=$PWD/kokkos
git clone -b develop https://github.com/kokkos/kokkos-kernels.git
KOKKOSKERNELS_DIR=$PWD/kokkos-kernels

cd $TRILINOS_DIR
ln -s ${KOKKOS_DIR}/kokkos kokkos
ln -s ${KOKKOSKERNELS_DIR}/kokkos-kernels kokkos-kernels
cd -

mkdir -p Build
cd Build
```

Then, if on a supported CEE machine with sems modules, the Trilinos CI [reproducer instructions](https://github.com/trilinos/Trilinos/wiki/Reproducing-PR-Testing-Errors) for `rhel8_sems-gnu-8.5.0-openmpi-4.1.6-serial_debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables` can be followed with e.g these files for the cmake fragments https://trilinos-cdash.sandia.gov/build/1761399/files

For the cmake configure line, use the following from the Build directory (the key addition here is to override the kokkos and kokkos-kernels packages):
```
cmake -D Trilinos_CONFIGURE_OPTIONS_FILE=$PWD/generatedFragment.cmake -C "$PWD/packageEnables.cmake" -G "Ninja" -DTrilinos_ENABLE_Kokkos=ON -DTrilinos_ENABLE_Tpetra=ON -DTrilinos_ENABLE_TESTS=ON -DKokkos_SOURCE_DIR_OVERRIDE:STRING=kokkos -DKokkosKernels_SOURCE_DIR_OVERRIDE:STRING=kokkos-kernels -DML_ENABLE_SuperLU=OFF $TRILINOS_SRC
```

If helpful, I can provide scripts and files I used for my build on a machine that had sems modules available

**Comment by ndellingwood** [comment]
@dalg24 has been working on a kokkkos-tool to help detect problematic View allocations, deallocations etc (for example within parallel regions)

This is output of the test when using that tool, to help give something a bit more concrete about the failure (beyond the test hanging):

```
*** Starting test NgpMeshTest.volatileFastSharedCommMap
allocating "CommMapIndices" within parallel region "Z52check_volatile_fast_shared_comm_map_values_on_deviceRKN3stk4mesh8HostMeshEiRKN6Kokkos4ViewIPNS0_13FastMeshIndexEJNS4_9HostSpaceEEEEEUlmE_"
[kokkos-dev-2:1743182] *** Process received signal ***
[kokkos-dev-2:1743182] Signal: Aborted (6)
[kokkos-dev-2:1743182] Signal code:  (-6)
allocating "CommMapIndices" within parallel region "Z52check_volatile_fast_shared_comm_map_values_on_deviceRKN3stk4mesh8HostMeshEiRKN6Kokkos4ViewIPNS0_13FastMeshIndexEJNS4_9HostSpaceEEEEEUlmE_"
[kokkos-dev-2:1743181] *** Process received signal ***
[kokkos-dev-2:1743181] Signal: Aborted (6)
[kokkos-dev-2:1743181] Signal code:  (-6)
allocating "CommMapIndices" within parallel region "Z52check_volatile_fast_shared_comm_map_values_on_deviceRKN3stk4mesh8HostMeshEiRKN6Kokkos4ViewIPNS0_13FastMeshIndexEJNS4_9HostSpaceEEEEEUlmE_"
[kokkos-dev-2:1743184] *** Process received signal ***
[kokkos-dev-2:1743184] Signal: Aborted (6)
[kokkos-dev-2:1743184] Signal code:  (-6)
allocating "CommMapIndices" within parallel region "Z52check_volatile_fast_shared_comm_map_values_on_deviceRKN3stk4mesh8HostMeshEiRKN6Kokkos4ViewIPNS0_13FastMeshIndexEJNS4_9HostSpaceEEEEEUlmE_"
[kokkos-dev-2:1743183] *** Process received signal ***
[kokkos-dev-2:1743183] Signal: Aborted (6)
[kokkos-dev-2:1743183] Signal code:  (-6)
...
```

**Comment by alanw0** [comment]
Thanks for the report, we will look into this.
I think that test was intended to simply return a subview into a pre-existing view. (Is that legal on device?)
Your diagnostic sounds like it may be doing an allocation which I don't think we meant to do...

**Comment by dalg24** [comment]
Creating a subview is legal.  But here an allocation is happening.

**Comment by crtrott** [comment]
The test is probably getting instantiated with HostMesh which does allocate. 

You need to do something like this: 

```c++
void check_volatile_fast_shared_comm_map_values_on_device(const stk::mesh::NgpMesh & ngpMesh, int proc, const stk::mesh::DeviceCommMapIndices & deviceCommMapIndicesGold)
{
  auto test = KOKKOS_LAMBDA(size_t i)
                       {
                         stk::mesh::DeviceCommMapIndices deviceCommMapIndices = ngpMesh.volatile_fast_shared_comm_map(stk::topology::NODE_RANK, proc);

                         for (size_t entry = 0; entry < deviceCommMapIndices.size(); ++entry) {
                           NGP_EXPECT_EQ(deviceCommMapIndicesGold[entry].bucket_id, deviceCommMapIndices[entry].bucket_id);
                           NGP_EXPECT_EQ(deviceCommMapIndicesGold[entry].bucket_ord, deviceCommMapIndices[entry].bucket_ord);
                         }
                       };
  if constexpr (ngp_Mesh_is_Host_Mesh) {
    test(0);
  } else {
    Kokkos::parallel_for(stk::ngp::DeviceRangePolicy(0, 1), test);
  }
}
```

**Comment by crtrott** [comment]
Just to make that clear: it IS illegal to allocate new Views inside parallel_for even on Host. With Threads backend for example this will not work at all (or at a minimum end up with some unitialized View elements).

**Comment by ndellingwood** [comment]
I tested the suggestion in https://github.com/trilinos/Trilinos/issues/13328#issuecomment-2272005002 with the mpi+gcc/8.5.0 build, the full `STKUnit_tests_stk_mesh_unit_tests_MPI_4` unit test passed without problems

**Comment by alanw0** [comment]
Yes this all makes sense.
A short-term solution like @crtrott suggests will be fine.
But we probably need to develop a solution where HostMesh doesn't do a view creation in that method.
In practice HostMesh is not supposed to get used in GPU builds, but since allocation within parallel_for isn't legal even on host, we need to give this a little more thought.
