### ISSUE TITLE
Teko unused variables causing build error in warning-free build

### ISSUE THREAD

**Issue by ikalash** [trilinos/Trilinos#13358]
The Albany warning-free build is broken again due to unused variables in Trilinos, Teko in particular:

https://sems-cdash-son.sandia.gov/cdash//viewBuildError.php?buildid=183349

```
[Trilinos/packages/teko/src/Teko_DiagonalPreconditionerFactory.cpp:43](https://blob/master/Trilinos/packages/teko/src/Teko_DiagonalPreconditionerFactory.cpp#L43):27: error: unused variable 'MyState' [-Werror=unused-variable]
```
Could someone please fix this?

@trilinos/teko

**Comment by ikalash** [comment]
This is actually Teko, not MueLu.  I have corrected the issue.  Sorry for the confusion.

**Comment by cgcgcg** [comment]
@achauphan Why didn't the AT catch this? Wasn't this the point of the recent changes?

**Comment by ikalash** [comment]
Ok, then it's this issue which we haven't gotten around to addressing in LCM: https://github.com/sandialabs/LCM/issues/87 .  I guess the deprecated code we were using has been removed?

**Comment by cgcgcg** [comment]
No, I totally cause the issue with my PR yesterday. It makes sense that your build is failing due to that. But I am wondering why we didn't catch this in Trilinos.

**Comment by cgcgcg** [comment]
@ikalash Should be fixed on develop.

**Comment by ikalash** [comment]
Thank you @cgcgcg !  I will check the nightlies tomorrow and close if things are clean.

**Comment by sebrowne** [comment]
@cgcgcg I checked and I cannot explain why the warning-as-error didn't pop for that file in your PR.  The flags look correct, and Epetra and Teko were both enabled.  If I had to grasp at straws, I would blame ccache ran the preprocessor and got a match, but that seems VERY unlikely given my historical experience.
