### ISSUE TITLE
STK: removed function causing build errors in Albany nightlies

### ISSUE THREAD

**Issue by ikalash** [trilinos/Trilinos#13357]
Did ```get_entities_through_relations``` go away in STK?  We are getting the following build error in Albany:

```
/nightlyCDash/repos/Albany/src/disc/stk/percept/stk_rebalance/Rebalance.cpp:103:16: error: 'get_entities_through_relations' is not a member of 'stk::mesh'
```
https://sems-cdash-son.sandia.gov/cdash/viewBuildError.php?buildid=183419

Is there an alternate function that should be used now?

@trilinos/seacas

**Comment by ikalash** [comment]
Adding the include fixed it!  Thanks @alanw0 !

Another question.  We have a STK-related build error in Albany-LCM as well, which for some reason isn't seen in the dashboard but is there.  Here is the error:

```
[ 20%] Building CXX object src/CMakeFiles/albanyLib.dir/PHAL_Utilities.cpp.o
In file included from /home/lcm/LCM/LCM/src/disc/stk/percept/stk_rebalance/Partition.cpp:9:
/home/lcm/LCM/LCM/src/./disc/stk/percept/stk_rebalance/Partition.hpp:54:35: error: no member named 'Cartesian' in namespace 'stk::mesh'
   54 | typedef mesh::Field<double, mesh::Cartesian> VectorField;
 ```
Has ```mesh::Cartesian``` been removed?

**Comment by alanw0** [comment]
Yes the templating of fields has changed, there is now only 1 template parameter which is the data-type (double in this case).
I believe @djglaze interacted with @mperego on this issue previously, and a lot of field-usage was converted in this Albany PR: [#963](https://github.com/sandialabs/Albany/pull/963)

**Comment by ikalash** [comment]
Ok, then it's this issue which we haven't gotten around to addressing in LCM: https://github.com/sandialabs/LCM/issues/87 . I guess the deprecated code we were using has been removed?

**Comment by alanw0** [comment]
Yes that's right, the deprecated code has now been removed.
My apologies, we should have sent out an alert that that was happening. I believe we kept the deprecation window open for longer than usual on this change, but still a communication at the end of the window would have been helpful.

**Comment by ikalash** [comment]
No worries.  It has been on my to do list to fix this for awhile but I haven't had a chance to get to it.

**Comment by mperego** [comment]
Thanks @ikalash for fixing the Percept code in Albany. I don't think we need the Percept code any longer, I'll remove at some point.

**Comment by ikalash** [comment]
@mperego : no problem.  I agree about percept removal.
