### ISSUE TITLE
Disable Fortran by default for Trilinos on Mac OSX machines as well?

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#1338]
**CC:** @trilinos/developers, @trilinos/framework

**Description:**

Given that most Mac OSX machines don't have a working Fortran compiler by default, should we change the CMake logic to disable Fortran by default on Mac OSX machines?  That will technically break backward compatibility but given the you don't need Fortran to get a lot out of Trilinos, I am not sure how many users would notice.

I am asking this since I am modifying TriBITS to fix a defect in how it handles the default for `<Project>_ENABLE_Fortran` and I want to move all special platform-specific logic to the project itself.  Since I will be updating Trilinos/CMakeLists.txt for this refactoring, I thought I would ask about since I could make this change at the same time.

**Comment by aprokop** [comment]
Personally, I don't see why you would want to enable Fortran if none of the enabled packages require it. So I think disabling Fortran by default is the right thing to do as long as during the configuration a package that requires it may turn it back on. I would probably go further and disable it by default even on Linux.

**Comment by bartlettroscoe** [comment]
> Personally, I don't see why you would want to enable Fortran if none of the enabled packages require it.

I think there are still some better optimized kernels for Epetra written in Fortran.  Also, disabling Fortran for Linux by default may be too much of a break of backward compatibility.

But let's see what other Trilinos developers think about this.

**Comment by mhoemmen** [comment]
@bartlettroscoe wrote:
> I think there are still some better optimized kernels for Epetra written in Fortran.

The sparse-matrix-times-multiple-vectors kernel is in Fortran.  I'm not sure if there is a C++ replacement with equivalent performance, though it would not be hard to write one (strip mine and unroll -- or just call Christian's kernel if that package is enabled).

**Comment by mhoemmen** [comment]
What would happen to Mac users who build, say, gcc and gfortran with Homebrew?  Would they need to enable Fortran explicitly?  The Homebrew case is pretty common -- Mac users expect to need to build TPLs, even MPI, so they either have to do it themselves, or use a system like Homebrew.

**Comment by tjfulle** [comment]
By default, Mac OS X does not ship with any compiler.  Anyone who builds Trilinos on a Mac must download/install compilers and then any TPLs.  Most will do this with Homebrew or Macports, in which case gcc+gfortran is probably going to be built as a prerequisite.

 Can't cmake check the compiler vendor and look for an associated fortran compiler?  Does it have to be platform specific?

**Comment by bartlettroscoe** [comment]
> Can't cmake check the compiler vendor and look for an associated fortran compiler? Does it have to be platform specific?

We can do anything we want in the Trilinos/ProjectName.cmake file (there is not a block of code you can modify there to set `Trilinos_ENABLE_Fortran_DEFAULT` with any logic you want on "Darwin").  But my view is that if you are on a Mac OSX machine, you likely don't care about performance as much so not enabling Fortran by default is not a big deal.  But given the feedback we have gotten from some Trilinos users about problems with Fortran on OSX, I think we should lean toward disabling it by default.

**Comment by bartlettroscoe** [comment]
Given the move to Kokkos and Tpetra, I think it makes even more sense to have Fortran disabled by default for Trilinos.  That would provide a much nicer first experience for Mac OSX users.

**Comment by wadeburgess** [comment]
Migrated to Jira.
