### ISSUE TITLE
SEACAS: Ioss_Field.h header "fmt/ostream.h" not found 

### ISSUE THREAD

**Issue by spdomin** [trilinos/Trilinos#13382]
The error captured in https://github.com/trilinos/Trilinos/issues/11487 is showing up again:

In file included from /projects/netpub/nalu/scratch_build/install/gcc10.3.0/Trilinos_nightly_release/include/stk_io/IossBridge.hpp:41,
from /fgs/spdomin/nightly/Nalu/src/DataProbePostProcessing.C:33:
/projects/netpub/nalu/scratch_build/install/gcc10.3.0/Trilinos_nightly_release/include/Ioss_Field.h:12:10: fatal error: fmt/ostream.h: No such file or directory
12 | #include <fmt/ostream.h>

```
Bad: Trilinos/develop SHA1: https://github.com/trilinos/Trilinos/commit/94b60d005ec42fe20eda3a869712ffab8548b271
Good: Trilinos/develop SHA1: https://github.com/trilinos/Trilinos/commit/c8548cf7bdc5a50daff9fdf93d493228a74a3973
```

**Comment by jhux2** [comment]
@gsjaardema @trilinos/seacas

**Comment by ikalash** [comment]
I can confirm that this issue has been resolved for Albany.

**Comment by gsjaardema** [comment]
Sorry for the problem.  I will try to address this in a more sustainable manner for future snaphshots...
