### ISSUE TITLE
Eliminate warnings in CI build coming from mpi.h with GCC 4.9.3 and OpenMPI from 1.6.5

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#1341]
**Next Action Status:**

Adding `-isystem` for OpenMPI 1.6. include dir makes warnings go away locally but not for CTest -S script.  Asked SEMS if they could patch mpi.h file (but unknown when that might happen).  Next: Switch CI build to GCC 4.8.4 which does not emit the warnings?

**CC:** @trilinos/framework

**Description:**

With the upgrade to GCC 4.9.3 (see #1002), we are now getting a lot of warnings from OpenMPI 1.6.5 headers like:

```
In file included from /projects/sems/install/rhel6-x86_64/sems/compiler/gcc/4.9.3/openmpi/1.6.5/include/mpi.h:253:0,
                 from /scratch/rabartl/Trilinos.base/SEMSCIBuild/Trilinos/packages/teuchos/core/src/Teuchos_Time.hpp:56,
                 from /scratch/rabartl/Trilinos.base/SEMSCIBuild/Trilinos/packages/teuchos/core/src/Teuchos_Time.cpp:45:
/projects/sems/install/rhel6-x86_64/sems/compiler/gcc/4.9.3/openmpi/1.6.5/include/mpi_portable_platform.h:374:34: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
              _STRINGIFY(__GNUC__)"."_STRINGIFY(__GNUC_MINOR__)"."_STRINGIFY(__GNUC_PATCHLEVEL__)
                                  ^
/projects/sems/install/rhel6-x86_64/sems/compiler/gcc/4.9.3/openmpi/1.6.5/include/mpi_portable_platform.h:374:63: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
              _STRINGIFY(__GNUC__)"."_STRINGIFY(__GNUC_MINOR__)"."_STRINGIFY(__GNUC_PATCHLEVEL__)
                                                               ^
```

such as you see, for example, in this CI iteration:

* http://testing.sandia.gov/cdash/viewBuildError.php?type=1&buildid=2902564

Looking at the new "Clean" build 
Linux-gcc-4.9.3-MPI_Release_gcc_4.9.3_openmpi_1.8.7_DEV  targeted for SIERRA, for example, at:

* http://testing.sandia.gov/cdash/index.php?project=Trilinos&parentid=2901291

perhaps our CI build should be upgraded to OpenMPI 1.8.7?

In any case, this story is to make these warnings go away so they don't spam Trilinos developers and CDash.

**Comment by bartlettroscoe** [comment]
Not sure why the other CI build maintained by the Trilinos Framework team is not showing these warnings:

* http://testing.sandia.gov/cdash/index.php?project=Trilinos&parentid=2901921

So, @trilinos/framework team, given that SIERRA seems to be using OpenMPI 1.87, any reason not to upgrade for the CI build?

**Comment by mhoemmen** [comment]
SIERRA uses OpenMPI 1.6.4 by default.  They had troubles with 1.8.7 and would likely switch to 1.10.? if they ever upgrade.  (This annoys me greatly, since 1.6.4 doesn't even implement MPI 3.)

**Comment by bartlettroscoe** [comment]
Then what customer does the build `Linux-gcc-4.9.3-MPI_Release_gcc_4.9.3_openmpi_1.8.7_DEV` on `ascic142` shown at:

* http://testing.sandia.gov/cdash/index.php?project=Trilinos&parentid=2901291

target?

@prwolfe, I was assuming this was a build that you set up as part of Sierra/Trilinos integration testing.

@jwillenbring, I think we should require that every build on the "Clean" track be listed on some wiki page on this site that lists the exact Trilinos customers that this build is designed to support.  If there is not a specific Trilinos customer that one of these builds is not specifically targeted to support, then it should not be there.  And we should explain **how** that build supports each specific customer.  I will do this for the ATDM-targeted builds for sure.  We should do this for **all** of these "Clean" builds.

**Comment by bartlettroscoe** [comment]
I can confirm that switching from OpenMPI 1.6.5 to 1.8.7 for GCC 4.8.3 makes these OpenMPI warnings go away.

Since the other CI build [Linux-GCC-4.7.2-CONTINUOUS_MPI_OPT_DEV_SHARED](http://testing.sandia.gov/cdash/index.php?project=Trilinos&display=project&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Linux-GCC-4.7.2-CONTINUOUS_MPI_OPT_DEV_SHARED&field2=buildstarttime&compare2=84&value2=now) run by the @trilinos/framework team is using OpenMPI 1.6.5, I think it is safe to update the CI build [
Linux-GCC-4.7.2-CONTINUOUS_MPI_OPT_DEV_SHARED ](http://testing.sandia.gov/cdash/index.php?project=Trilinos&date=2016-11-30&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=66&value1=MPI_RELEASE_DEBUG_SHARED_PT_CI&field2=groupname&compare2=61&value2=Continuous&field3=buildstarttime&compare3=84&value3=now) to use OpenMPI 1.8.7.

> SIERRA uses OpenMPI 1.6.4 by default. They had troubles with 1.8.7 and would likely switch to 1.10.? if they ever upgrade. (This annoys me greatly, since 1.6.4 doesn't even implement MPI 3.)

Since most MPI calls in Trilinos are done through the Teuchos::Comm class wrappers (and those MPI features have been around for 20 years), I don't think there is a large risk in Trilinos packages using parts of the MPI 3 standard.  Therefore, if Trilinos passes with OpenMPI 1.8.7, I think there is a good chance it will pass with OpenMPI 1.6.4 as well.

Therefore, I am going to go ahead and update the standard CI build associated with the checkin-test-sems.sh script to use OpenMPI 1.8.7.

**Comment by prwolfe** [comment]
Sierra has found significant speed issues with the 1.8 series. I am pushing for 1.10.2 here, but i'm not sure how fast that will happen

**Comment by bartlettroscoe** [comment]
@prwolfe:

> Sierra has found significant speed issues with the 1.8 series. I am pushing for 1.10.2 here, but i'm not sure how fast that will happen

So from a Sierra perspective, would you rather we change this CI to OpenMPI 1.10.2 rather than 1.8.7?  That way, this CI build would use 1.10.2 and the other CI build would use 1.6.4.

**Comment by bartlettroscoe** [comment]
It appears we are also seeing performance problems with OpenMPI 1.8.7 w.r.t. 1.6.5 even on the small Trilinos test suite as shown by the timeouts below when I ran the checkin-test-sems.sh script when trying to push the change to OpenMPI 1.8.7.

I will try OpenMPI 1.10.1 and push if that passes.

----

```
FAILED CONFIGURE/BUILD/TEST: Trilinos: crf450.srn.sandia.gov

Mon May 22 16:10:46 MDT 2017

Enabled Packages: 
Disabled Packages: PyTrilinos,Claps,TriKota Enabled all Packages

Build test results:
-------------------
0) MPI_RELEASE_DEBUG_SHARED_PT => FAILED: passed=2310,notpassed=15 => Not ready to push! (108.79 min)


Failed because one of the build/test cases failed!

*** Commits for repo :
  3bdcbfe Merge branch 'develop' of github.com:trilinos/Trilinos into develop
  b7318cb Switch CI build to to OpenMPI 1.8.7 (#1341)

0) MPI_RELEASE_DEBUG_SHARED_PT Results:
---------------------------------------

  FAILED: Trilinos/MPI_RELEASE_DEBUG_SHARED_PT: passed=2310,notpassed=15
  
  Mon May 22 16:10:46 MDT 2017
  
  Enabled Packages: 
  Disabled Packages: PyTrilinos,Claps,TriKota
  Enabled all Packages
  Hostname: crf450.srn.sandia.gov
  Source Dir: /home/rabartl/Trilinos.base/Trilinos/cmake/tribits/ci_support/../../..
  Build Dir: /home/rabartl/Trilinos.base/BUILDS/CHECKIN/MPI_RELEASE_DEBUG_SHARED_PT
  
  CMake Cache Varibles: -DTrilinos_TRIBITS_DIR:PATH=/home/rabartl/Trilinos.base/Trilinos/cmake/tribits -DTrilinos_ENABLE_TESTS:BOOL=ON -DTrilinos_TEST_CATEGORIES:STRING=BASIC -DTrilinos_ALLOW_NO_PACKAGES:BOOL=OFF -DDART_TESTING_TIMEOUT:STRING=300.0 -DBUILD_SHARED_LIBS=ON -DTrilinos_DISABLE_ENABLED_FORWARD_DEP_PACKAGES=ON -DTrilinos_TRACE_ADD_TEST=ON -DTrilinos_ENABLE_SECONDARY_TESTED_CODE:BOOL=OFF -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/MpiReleaseDebugSharedPtSettings.cmake,cmake/std/BasicCiTestingSettings.cmake -DTrilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=ON -DTrilinos_ENABLE_ALL_PACKAGES:BOOL=ON -DTrilinos_ENABLE_ALL_FORWARD_DEP_PACKAGES:BOOL=ON -DTrilinos_ENABLE_PyTrilinos:BOOL=OFF -DTrilinos_ENABLE_Claps:BOOL=OFF -DTrilinos_ENABLE_TriKota:BOOL=OFF
  Make Options: -j16
  CTest Options: -j16 
  
  Pull: Passed (0.00 min)
  Configure: Passed (3.75 min)
  Build: Passed (86.70 min)
  Test: FAILED (18.33 min)
  
  99% tests passed, 15 tests failed out of 2325
  
  Label Time Summary:
  Amesos               =   5.42 sec (14 tests)
  Amesos2              =   2.18 sec (8 tests)
  Anasazi              =  36.14 sec (71 tests)
  AztecOO              =   4.86 sec (17 tests)
  Belos                =  36.46 sec (64 tests)
  Domi                 = 138.41 sec (125 tests)
  Epetra               =  48.84 sec (61 tests)
  EpetraExt            =   3.85 sec (10 tests)
  FEI                  =  48.42 sec (43 tests)
  Galeri               =   5.81 sec (9 tests)
  GlobiPack            =   2.54 sec (6 tests)
  Ifpack               =  23.23 sec (53 tests)
  Ifpack2              =  66.97 sec (33 tests)
  Intrepid             = 1365.24 sec (152 tests)
  Intrepid2            = 207.53 sec (73 tests)
  Isorropia            =   1.48 sec (6 tests)
  Kokkos               = 910.47 sec (21 tests)
  KokkosKernels        =  18.37 sec (9 tests)
  ML                   =  26.32 sec (34 tests)
  MiniTensor           =   0.96 sec (2 tests)
  MueLu                = 1232.67 sec (56 tests)
  NOX                  = 310.17 sec (101 tests)
  OptiPack             =   2.51 sec (5 tests)
  Panzer               = 466.52 sec (129 tests)
  Phalanx              =  11.62 sec (18 tests)
  Pike                 =   4.97 sec (7 tests)
  Piro                 =  27.09 sec (12 tests)
  ROL                  = 2767.44 sec (133 tests)
  RTOp                 =   9.34 sec (24 tests)
  Rythmos              = 1014.54 sec (83 tests)
  SEACAS               =  36.97 sec (8 tests)
  STK                  = 103.14 sec (11 tests)
  Sacado               = 116.00 sec (292 tests)
  Shards               =   2.60 sec (4 tests)
  ShyLU                =   4.14 sec (5 tests)
  Stokhos              = 363.67 sec (74 tests)
  Stratimikos          = 131.64 sec (39 tests)
  Teko                 = 506.21 sec (19 tests)
  Tempus               = 1551.12 sec (9 tests)
  Teuchos              =  52.67 sec (125 tests)
  ThreadPool           =   5.98 sec (10 tests)
  Thyra                =  34.17 sec (80 tests)
  Tpetra               =  51.35 sec (127 tests)
  TrilinosCouplings    = 299.43 sec (19 tests)
  Triutils             =   0.35 sec (2 tests)
  Xpetra               =  27.64 sec (17 tests)
  Zoltan               =  22.92 sec (16 tests)
  Zoltan2              =  55.15 sec (97 tests)
  
  Total Test time (real) = 1099.96 sec
  
  The following tests FAILED:
  	 11 - KokkosCore_UnitTest_Serial_MPI_1 (Timeout)
  	 30 - KokkosContainers_UnitTest_Serial_MPI_1 (Timeout)
  	 31 - KokkosAlgorithms_UnitTest_MPI_1 (Timeout)
  	1262 - Anasazi_Epetra_OrthoManagerGenTester_1_MPI_4 (Failed)
  	1436 - Teko_testdriver_tpetra_MPI_1 (Timeout)
  	1826 - MueLu_UnitTestsTpetra_MPI_1 (Timeout)
  	1834 - MueLu_ParameterListInterpreterEpetra_MPI_1 (Timeout)
  	1836 - MueLu_ParameterListInterpreterTpetra_MPI_1 (Timeout)
  	1919 - Rythmos_IntegratorBuilder_ConvergenceTest_MPI_1 (Timeout)
  	1945 - Tempus_BackwardEuler_MPI_1 (Timeout)
  	1948 - Tempus_DIRK_MPI_1 (Timeout)
  	1949 - Tempus_HHTAlpha_MPI_1 (Timeout)
  	1950 - Tempus_Newmark_MPI_1 (Timeout)
  	2078 - ROL_test_sol_solSROMGenerator_MPI_1 (Timeout)
  	2095 - ROL_example_burgers-control_example_06_MPI_1 (Timeout)
  Errors while running CTest
  
  Total time for MPI_RELEASE_DEBUG_SHARED_PT = 108.79 min
```

**Comment by bartlettroscoe** [comment]
Trying to switch to OpenMPI 1.10.1 caused timeouts as well as shown in the below checkin-test-sems.sh output.

I will try another approach to eliminate these MPI warnings with GCC 4.9.3 + OpenMPI 1.6.5.

----

```
FAILED CONFIGURE/BUILD/TEST: Trilinos: crf450.srn.sandia.gov

Mon May 22 22:27:42 MDT 2017

Enabled Packages: 
Disabled Packages: PyTrilinos,Claps,TriKota Enabled all Packages

Build test results:
-------------------
0) MPI_RELEASE_DEBUG_SHARED_PT => FAILED: passed=2310,notpassed=15 => Not ready to push! (108.02 min)


Failed because one of the build/test cases failed!

*** Commits for repo :
  f7bb997 Merge branch 'tribits_github_snapshot' into develop
  341fec9 Switch CI build to to OpenMPI 1.10.1 (#1341)
  12b2cdd Automatic snapshot commit from tribits at 3fe4ff1

0) MPI_RELEASE_DEBUG_SHARED_PT Results:
---------------------------------------

  FAILED: Trilinos/MPI_RELEASE_DEBUG_SHARED_PT: passed=2310,notpassed=15
  
  Mon May 22 22:27:41 MDT 2017
  
  Enabled Packages: 
  Disabled Packages: PyTrilinos,Claps,TriKota
  Enabled all Packages
  Hostname: crf450.srn.sandia.gov
  Source Dir: /home/rabartl/Trilinos.base/Trilinos/cmake/tribits/ci_support/../../..
  Build Dir: /home/rabartl/Trilinos.base/BUILDS/CHECKIN/MPI_RELEASE_DEBUG_SHARED_PT
  
  CMake Cache Varibles: -DTrilinos_TRIBITS_DIR:PATH=/home/rabartl/Trilinos.base/Trilinos/cmake/tribits -DTrilinos_ENABLE_TESTS:BOOL=ON -DTrilinos_TEST_CATEGORIES:STRING=BASIC -DTrilinos_ALLOW_NO_PACKAGES:BOOL=OFF -DDART_TESTING_TIMEOUT:STRING=300.0 -DBUILD_SHARED_LIBS=ON -DTrilinos_DISABLE_ENABLED_FORWARD_DEP_PACKAGES=ON -DTrilinos_TRACE_ADD_TEST=ON -DTrilinos_ENABLE_SECONDARY_TESTED_CODE:BOOL=OFF -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/MpiReleaseDebugSharedPtSettings.cmake,cmake/std/BasicCiTestingSettings.cmake -DTrilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=ON -DTrilinos_ENABLE_ALL_PACKAGES:BOOL=ON -DTrilinos_ENABLE_ALL_FORWARD_DEP_PACKAGES:BOOL=ON -DTrilinos_ENABLE_PyTrilinos:BOOL=OFF -DTrilinos_ENABLE_Claps:BOOL=OFF -DTrilinos_ENABLE_TriKota:BOOL=OFF
  Make Options: -j16
  CTest Options: -j16 
  
  Pull: Passed (0.00 min)
  Configure: Passed (2.77 min)
  Build: Passed (86.30 min)
  Test: FAILED (18.94 min)
  
  99% tests passed, 15 tests failed out of 2325
  
  Label Time Summary:
  Amesos               =   5.62 sec (14 tests)
  Amesos2              =   2.94 sec (8 tests)
  Anasazi              =  34.58 sec (71 tests)
  AztecOO              =   5.84 sec (17 tests)
  Belos                =  33.75 sec (64 tests)
  Domi                 = 142.72 sec (125 tests)
  Epetra               =  40.06 sec (61 tests)
  EpetraExt            =   3.84 sec (10 tests)
  FEI                  =  39.75 sec (43 tests)
  Galeri               =   7.35 sec (9 tests)
  GlobiPack            =   2.73 sec (6 tests)
  Ifpack               =  25.65 sec (53 tests)
  Ifpack2              =  67.95 sec (33 tests)
  Intrepid             = 1812.86 sec (152 tests)
  Intrepid2            = 239.11 sec (73 tests)
  Isorropia            =   1.48 sec (6 tests)
  Kokkos               = 909.55 sec (21 tests)
  KokkosKernels        =  31.48 sec (9 tests)
  ML                   =  20.28 sec (34 tests)
  MiniTensor           =   0.70 sec (2 tests)
  MueLu                = 1302.41 sec (56 tests)
  NOX                  = 364.95 sec (101 tests)
  OptiPack             =   3.25 sec (5 tests)
  Panzer               = 518.96 sec (129 tests)
  Phalanx              =  13.73 sec (18 tests)
  Pike                 =   4.09 sec (7 tests)
  Piro                 =  19.67 sec (12 tests)
  ROL                  = 2965.97 sec (133 tests)
  RTOp                 =   9.71 sec (24 tests)
  Rythmos              = 970.42 sec (83 tests)
  SEACAS               =  52.69 sec (8 tests)
  STK                  = 120.51 sec (11 tests)
  Sacado               = 103.25 sec (292 tests)
  Shards               =   2.26 sec (4 tests)
  ShyLU                =   3.68 sec (5 tests)
  Stokhos              = 242.58 sec (74 tests)
  Stratimikos          = 125.17 sec (39 tests)
  Teko                 = 543.13 sec (19 tests)
  Tempus               = 1597.54 sec (9 tests)
  Teuchos              =  49.14 sec (125 tests)
  ThreadPool           =   5.77 sec (10 tests)
  Thyra                =  31.65 sec (80 tests)
  Tpetra               =  48.34 sec (127 tests)
  TrilinosCouplings    = 386.23 sec (19 tests)
  Triutils             =   0.43 sec (2 tests)
  Xpetra               =  25.86 sec (17 tests)
  Zoltan               =  20.86 sec (16 tests)
  Zoltan2              =  47.95 sec (97 tests)
  
  Total Test time (real) = 1135.99 sec
  
  The following tests FAILED:
  	 11 - KokkosCore_UnitTest_Serial_MPI_1 (Timeout)
  	 30 - KokkosContainers_UnitTest_Serial_MPI_1 (Timeout)
  	 31 - KokkosAlgorithms_UnitTest_MPI_1 (Timeout)
  	1436 - Teko_testdriver_tpetra_MPI_1 (Timeout)
  	1826 - MueLu_UnitTestsTpetra_MPI_1 (Timeout)
  	1834 - MueLu_ParameterListInterpreterEpetra_MPI_1 (Timeout)
  	1836 - MueLu_ParameterListInterpreterTpetra_MPI_1 (Timeout)
  	1915 - Rythmos_BackwardEuler_ConvergenceTest_MPI_1 (Timeout)
  	1919 - Rythmos_IntegratorBuilder_ConvergenceTest_MPI_1 (Timeout)
  	1945 - Tempus_BackwardEuler_MPI_1 (Timeout)
  	1948 - Tempus_DIRK_MPI_1 (Timeout)
  	1949 - Tempus_HHTAlpha_MPI_1 (Timeout)
  	1950 - Tempus_Newmark_MPI_1 (Timeout)
  	2078 - ROL_test_sol_solSROMGenerator_MPI_1 (Timeout)
  	2103 - ROL_example_parabolic-control_example_03_MPI_1 (Timeout)
  Errors while running CTest
  
  Total time for MPI_RELEASE_DEBUG_SHARED_PT = 108.02 min
```

**Comment by bartlettroscoe** [comment]
Just to compare the runtimes with the different versions of OpenMPI, below is the runtimes for a push I just did with the checkin-test-sems.sh script on the same machine using OpenMPI 1.6.5.  Look at the dramatic difference, for example, in the total runtimes for the ROL test suite:

* OpenMPI 1.6.5: 855.21 sec (133 tests)
* OpenMPI 1.8.7: 2767.44 sec (133 tests)
* OpenMPI 1.10.1: 2965.97 sec (133 tests)

Wow, that is huge.  What is going on with these other versions of OpenMPI and some of these MPI tests in Trilinos?

In any case, I found a way to eliminate the warnings from the OpenMPI 1.6.5 mpi.h header reported [above](https://github.com/trilinos/Trilinos/issues/1341#issue-229728088).  I just added a `-isystem` include for the MPI include dir and that eliminates the warnings.  I am in the process of pushing that right now.

----

**Using OpenMPI 1.6.5**

```
DID PUSH: Trilinos: crf450.srn.sandia.gov

Tue May 23 06:57:32 MDT 2017

Enabled Packages: 
Disabled Packages: PyTrilinos,Claps,TriKota Enabled all Packages

Build test results:
-------------------
0) MPI_RELEASE_DEBUG_SHARED_PT => passed: passed=2325,notpassed=0 (101.95 min)

*** Commits for repo :
  966fbaa Merge branch 'tribits_github_snapshot' into develop
  12b2cdd Automatic snapshot commit from tribits at 3fe4ff1

0) MPI_RELEASE_DEBUG_SHARED_PT Results:
---------------------------------------

  passed: Trilinos/MPI_RELEASE_DEBUG_SHARED_PT: passed=2325,notpassed=0
  
  Tue May 23 06:57:25 MDT 2017
  
  Enabled Packages: 
  Disabled Packages: PyTrilinos,Claps,TriKota
  Enabled all Packages
  Hostname: crf450.srn.sandia.gov
  Source Dir: /home/rabartl/Trilinos.base/Trilinos/cmake/tribits/ci_support/../../..
  Build Dir: /home/rabartl/Trilinos.base/BUILDS/CHECKIN/MPI_RELEASE_DEBUG_SHARED_PT
  
  CMake Cache Varibles: -DTrilinos_TRIBITS_DIR:PATH=/home/rabartl/Trilinos.base/Trilinos/cmake/tribits -DTrilinos_ENABLE_TESTS:BOOL=ON -DTrilinos_TEST_CATEGORIES:STRING=BASIC -DTrilinos_ALLOW_NO_PACKAGES:BOOL=OFF -DDART_TESTING_TIMEOUT:STRING=300.0 -DBUILD_SHARED_LIBS=ON -DTrilinos_DISABLE_ENABLED_FORWARD_DEP_PACKAGES=ON -DTrilinos_TRACE_ADD_TEST=ON -DTrilinos_ENABLE_SECONDARY_TESTED_CODE:BOOL=OFF -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/MpiReleaseDebugSharedPtSettings.cmake,cmake/std/BasicCiTestingSettings.cmake -DTrilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=ON -DTrilinos_ENABLE_ALL_PACKAGES:BOOL=ON -DTrilinos_ENABLE_ALL_FORWARD_DEP_PACKAGES:BOOL=ON -DTrilinos_ENABLE_PyTrilinos:BOOL=OFF -DTrilinos_ENABLE_Claps:BOOL=OFF -DTrilinos_ENABLE_TriKota:BOOL=OFF
  Make Options: -j16
  CTest Options: -j16 
  
  Pull: Passed (0.00 min)
  Configure: Passed (2.85 min)
  Build: Passed (86.24 min)
  Test: Passed (12.86 min)
  
  100% tests passed, 0 tests failed out of 2325
  
  Label Time Summary:
  Amesos               =  20.00 sec (14 tests)
  Amesos2              =  10.67 sec (8 tests)
  Anasazi              = 103.30 sec (71 tests)
  AztecOO              =  16.64 sec (17 tests)
  Belos                =  96.34 sec (64 tests)
  Domi                 = 148.50 sec (125 tests)
  Epetra               =  45.20 sec (61 tests)
  EpetraExt            =  14.18 sec (10 tests)
  FEI                  =  42.45 sec (43 tests)
  Galeri               =   5.03 sec (9 tests)
  GlobiPack            =   1.66 sec (6 tests)
  Ifpack               =  57.73 sec (53 tests)
  Ifpack2              =  46.01 sec (33 tests)
  Intrepid             = 179.44 sec (152 tests)
  Intrepid2            =  42.52 sec (73 tests)
  Isorropia            =   7.67 sec (6 tests)
  Kokkos               = 232.04 sec (21 tests)
  KokkosKernels        =   4.51 sec (9 tests)
  ML                   =  44.73 sec (34 tests)
  MiniTensor           =   1.30 sec (2 tests)
  MueLu                = 302.97 sec (56 tests)
  NOX                  = 135.21 sec (101 tests)
  OptiPack             =   6.64 sec (5 tests)
  Panzer               = 309.47 sec (129 tests)
  Phalanx              =   5.71 sec (18 tests)
  Pike                 =   3.58 sec (7 tests)
  Piro                 =  25.59 sec (12 tests)
  ROL                  = 855.21 sec (133 tests)
  RTOp                 =  10.74 sec (24 tests)
  Rythmos              = 150.07 sec (83 tests)
  SEACAS               =   9.57 sec (8 tests)
  STK                  =  25.62 sec (11 tests)
  Sacado               =  53.44 sec (292 tests)
  Shards               =   1.18 sec (4 tests)
  ShyLU                =   8.01 sec (5 tests)
  Stokhos              =  87.60 sec (74 tests)
  Stratimikos          =  32.23 sec (39 tests)
  Teko                 = 162.27 sec (19 tests)
  Tempus               = 510.75 sec (9 tests)
  Teuchos              =  46.76 sec (125 tests)
  ThreadPool           =   8.22 sec (10 tests)
  Thyra                =  62.40 sec (80 tests)
  Tpetra               = 134.98 sec (127 tests)
  TrilinosCouplings    =  43.37 sec (19 tests)
  Triutils             =   2.40 sec (2 tests)
  Xpetra               =  47.91 sec (17 tests)
  Zoltan               = 198.33 sec (16 tests)
  Zoltan2              = 130.65 sec (97 tests)
  
  Total Test time (real) = 771.56 sec
  
  Total time for MPI_RELEASE_DEBUG_SHARED_PT = 101.95 min
```

**Comment by bartlettroscoe** [comment]
I pushed the commit 42c3fb5 a few hours ago that should clean up these warnings.  For some reason, this did not trigger a CI build (it should have triggered the enable and testing of all packages?).

In any case, we can wait and see what happens when the CI build fires off fresh tomorrow to see if these warnings go away (then we can clean up other warnings like I say for the yaml-cpp header file).

**Comment by bartlettroscoe** [comment]
For some reason I can't explain, the change I made in commit 42c3fb5 that added `-isystem` include for the MPI include directory for mpi.h made the warnings go away for a local build of Trilinos but did **not** make the warnings go away for the CTest driver build of Trilinos as shown, for example, here:

* http://testing.sandia.gov/cdash/index.php?project=Trilinos&parentid=2913695

I will now try to disable this warning using pragmas as described at:

* https://stackoverflow.com/questions/3378560/how-to-disable-gcc-warnings-for-a-few-lines-of-code

**Comment by bartlettroscoe** [comment]
I experimented with:

```
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wliteral-suffix"
#include "mpi.h"
#pragma GCC diagnostic pop
```

and that did not make the warnings go away.

I am at a loss of what to do to make these warnings go away.  I wish we could just patch this OpenMPI 1.6.5 mpi.h header to fix this.  But that would require SEMS tweaking their source for OpenMPI 1.6.5.  To test this, since I am syncing the SEMS env on my machine crf450, I made the change:

```
374c374
<              _STRINGIFY(__GNUC__)"."_STRINGIFY(__GNUC_MINOR__)"."_STRINGIFY(__GNUC_PATCHLEVEL__)
---
>              _STRINGIFY(__GNUC__) "." _STRINGIFY(__GNUC_MINOR__) "." _STRINGIFY(__GNUC_PATCHLEVEL__)
```

to the file:

* `/projects/sems/install/rhel6-x86_64/sems/compiler/gcc/4.9.3/openmpi/1.6.5/include/mpi_portable_platform.h`

and that removed the warnings.

I will ask to see if the SEMS team can apply this patch to their copy of OpenMPI 1.6.5 to make these warnings go away.

**Comment by bartlettroscoe** [comment]
I asked that the SEMS team apply this patch to OpenMPI 1.6.5 at:

* https://software-sandbox.sandia.gov/jira/servicedesk/customer/portal/4/SEMSHELPD-506

back on May 24, 2017 yet.  No response as of yet.

**Comment by bartlettroscoe** [comment]
The other option is to create GitHub issues for the tests timing out with OpenMPI 1.8.7 and then ask someone to address them (or disable them in the standard CI build until they can be fixed).  Either this points to a problem with OpenMPI 1.8.7 or with these Trilinos packages.  But it would take a more in-depth study to figure out what the problem is.  Who can take this on?

**Comment by bartlettroscoe** [comment]
> I asked that the SEMS team apply this patch to OpenMPI 1.6.5 at:
>
> *  https://software-sandbox.sandia.gov/jira/servicedesk/customer/portal/4/SEMSHELPD-506

Got a response.  The response is that this 4-char white-space change will need to go before the SEMS stewards and they will need to vote it up or down before it can be done.

If we want these warnings to go away sooner, we may need to go with another approach.

**Comment by ibaned** [comment]
I wish GitHub had a reaction for "I disapprove of the situation you describe, but I know its not your fault" :)

**Comment by bartlettroscoe** [comment]
It seems another benefit to changing the minimum GCC version and the GCC version for the default CI build from GCC 4.9.3 to 4.8.4 (see https://github.com/trilinos/Trilinos/issues/1363#issuecomment-310525233) is that it also looks to eliminate all of these warnings!

I am even more eager to make the change from GCC 4.9.3 back to GCC 4.8.4 based on this finding.

**Comment by bartlettroscoe** [comment]
By switching from GCC 4.9.3 to GCC 4.8.4, we no longer see these warnings coming from the OpenMPI 1.6.5 headers.  You can see that the Teuchos build is clean of these OpenMPI warnings in the first CI build this morning using CC 4.8.4 at:

* https://testing.sandia.gov/cdash/index.php?project=Trilinos&parentid=2970801

(but still shows 3 warnings for yaml-cpp which we need to take care of next.)

But you see a bunch of these OpenMPI warnings in the first CI build for Teuchos yesterday using GCC 4.9.3:

* https://testing.sandia.gov/cdash/index.php?project=Trilinos&parentid=2968848

I notified the SEMS team in:

* https://software-sandbox.sandia.gov/jira/servicedesk/customer/portal/4/SEMSHELPD-506

that patching the OpenMPI 1.6.5 header to remove these warnings with GCC 4.9.3 is no longer a priority.

I am closing this issue as complete (wontfix).
