### ISSUE TITLE
Teuchos: Failed Nalu nightly due to missing mpi.h header

### ISSUE THREAD

**Issue by spdomin** [trilinos/Trilinos#13410]
/Trilinos/packages/teuchos/core/src/Teuchos_GlobalMPISession.cpp:17:12: fatal error: mpi.h: No such file or directory
 #  include "mpi.h"

Bad:

```
NaluCFD/Nalu SHA1: 1ef81b6de5bbf1964d8bec6b0b64810def33b123
Trilinos/develop SHA1: 49d2b72017a98e8b2d742414fb21a7c4f1697466
```

Good:

```
NaluCFD/Nalu SHA1: 1ef81b6de5bbf1964d8bec6b0b64810def33b123
Trilinos/develop SHA1: 17d4af059257bdc683c3c7b18028cd08499e385e
```

I am curious to understand why we are seeing this recent set of build errors that are killing nightly testing.

**Comment by jhux2** [comment]
@spdomin I can't see anyway that either commit could be causing that.  Can you post the output from the cmake configure process?  That might give a hint as to why `mpi.h` isn't being found.

**Comment by spdomin** [comment]
I know, I was processing a bisect and saw that there were no relevant changes besides a seacas change.

Let me simply re-process a build and test and see what happens. Perhaps a module was simply not found during the nightly process.

**Comment by spdomin** [comment]
It looks like there was a module issue and openmpi was not loaded properly. The tests this AM ran without issue. Thanks for looking at this @jhux2, and apologies for the false positive.
