### ISSUE TITLE
Tpetra::Crs{Graph,Matrix}: Make sure parallel local pack uses right exec space

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#1345]
@trilinos/tpetra This is not the same "parallel pack" as that used by global assembly.  This is packing from 2-D or unpacked 1-D storage, into packed 1-D storage.  Both CrsGraph and CrsMatrix do this in parallel using a functor.  However, the code in question was doing a Kokkos::parallel_for with an integer range, instead of with a RangePolicy.  Kokkos interprets an integer range as a RangePolicy with the default execution space.  This may not be correct; for example, if Tpetra enables both Cuda and Serial execution spaces, the default execution space may be Cuda, even though the Tpetra object's execution space is Serial.

The fix is to replace the integer range with a RangePolicy that explicitly specifies the correct execution space.

This may have relevance to performance as well as correctness, depending on the default execution space vs. the Tpetra's object's execution space.

**Comment by tawiesn** [comment]
@jhux2 Same problem as we have in MueLu: Lesson learned: never use integer range but always a Kokkos::RangePolicy.

**Comment by mhoemmen** [comment]
@tawiesn I think it's OK for users (who trust the default execution space), but not for Trilinos developers who are writing code templated on (what amounts to) the execution space.  (I'm only writing this in case users read this issue and start getting worried.  They only need to know that an integer range makes Kokkos use the default execution space.)

**Comment by mhoemmen** [comment]
Fixed in develop.
