### ISSUE TITLE
kokkos:  error: no member named 'sort_option' in 'SPADDHandle'

### ISSUE THREAD

**Issue by LutzGross** [trilinos/Trilinos#13479]
## Bug Report
Trilinos organization members, please @ mention the correct package team.  
If you are not a member, please refer to https://github.com/trilinos/Trilinos/wiki/Trilinos-Package-Owners to mention the correct parties (because non-members cannot mention Github teams).

### Description
compilation of Trilinos 16 (aslo 15) fails on MacOS with 

packages/kokkos-kernels/sparse/src/KokkosSparse_spadd_handle.hpp:113:44: error: no member named 'sort_option' in 'SPADDHandle<lno_row_view_t_, lno_nnz_view_t_, scalar_nnz_view_t_, ExecutionSpace, MemorySpace>'

This under homebrew llvm@19.1.0 and gcc@14.2.0  and

Apple clang version 16.0.0 (clang-1600.0.26.3)
Target: arm64-apple-darwin23.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

### Steps to Reproduce
- script to invoke cmake: [mk_trilinos.sh.gz](https://github.com/user-attachments/files/17145522/mk_trilinos.sh.gz)

**Comment by cgcgcg** [comment]
@trilinos/kokkos-kernels 

@LutzGross You might want to move this issue to https://github.com/kokkos/kokkos-kernels

**Comment by jhux2** [comment]
See https://github.com/kokkos/kokkos-kernels/issues/2347.
