### ISSUE TITLE
Line smoother (block Jacobi-block tridiagonal)

### ISSUE THREAD

**Issue by ambrad** [trilinos/Trilinos#1350]
This issue will track the line smoother development.

Goals:
* Performance parity with an app-native impl on CPU/KNL, and (obviously) performance portability to GPU.
* Using the splitting A = M + N, with M the block Jacobi-block tridiag preconditioner, do the matvec Nx rather than Ax.
* Cleanly separate symbolic and numeric phases; maximize what is done in symbolic and minimize what is done in numeric.
* Use the new batch routines in KokkosKernels.

Work will proceed in the fork https://github.com/ambrad/Trilinos/tree/linesmoother

@trilinos/ifpack2 @kyungjoo-kim @srajama1

**Comment by ambrad** [comment]
@kyungjoo-kim will make the batched code available in the Trilinos installation in KokkosKernels::Experimental. No rush on this; I'm currently just hacking it in now. But when it's in automatically, it will be easier for others to run the line smoother before it goes into develop.

I'll also use KokkosKerenels::Test in Ifpack2's tests for this preconditioner if there are no objections.

**Comment by mhoemmen** [comment]
@ambrad Is the plan to make this available through the existing Ifpack2::BlockRelaxation, or through a different Ifpack2 preconditioner?

**Comment by ambrad** [comment]
@mhoemmen, it will be accessed through BlockRelaxation, using the new container BlockTriDiContainer. It's possible BlockTriDiContainer will eventually morph to just TriDiContainer, replacing the current one with a perf-portable one that handles both scalar and block cases. To be clear, though, completion of this current issue will result in BlockTriDiContainer, unless there are objections.

**Comment by mhoemmen** [comment]
@ambrad No objections from me :-)

**Comment by kyungjoo-kim** [comment]
@ambrad batched code is available in trilinos installation.

**Comment by ambrad** [comment]
See PR #1638

**Comment by ambrad** [comment]
I should update this issue to reflect what was done. Q4 goals were to get the block-tridiag-block-Jacobi and pure block-Jacobi methods *performant* on CPU and Xeon Phi. This has been done and will be pushed soon.

In FY18, GPU performance will be a target. Currently, unit tests pass, but the code is not performant, on GPU.

**Comment by srajama1** [comment]
@kyungjoo-kim I think this can be closed ?
