### ISSUE TITLE
Build failed on Ubuntu

### ISSUE THREAD

**Issue by georgtree** [trilinos/Trilinos#13526]
Hello!
I got this error while building trilinos serial on ubuntu:

```
[  8%] Built target chaco
/home/georgtree/trilinos_serial/Trilinos-trilinos-release-12-12-1/packages/seacas/libraries/svdi/cgi/met_vdimet.f:944:24:

  944 |       CALL CDR1CH(1,CHR,IN)
      |                        1
......
 1119 |       CALL CDR1CH(J,NSTR(I),ITEMP)
      |                            2
Error: Type mismatch between actual argument at (1) and actual argument at (2) (INTEGER(4)/INTEGER(8)).
/home/georgtree/trilinos_serial/Trilinos-trilinos-release-12-12-1/packages/seacas/libraries/svdi/cgi/met_vdimet.f:945:18:

  945 |       CALL CDRCVT(IN,CHAR)
      |                  1
......
 1122 |       CALL CDRCVT(ITEMP,ITEMP1)
      |                  2
Error: Type mismatch between actual argument at (1) and actual argument at (2) (INTEGER(4)/INTEGER(8)).
/home/georgtree/trilinos_serial/Trilinos-trilinos-release-12-12-1/packages/seacas/libraries/supes/mem_mgr/mdinit.F:709:37:

  261 |       MYLOC = IXLNUM (MYV)
      |                      2               
......
  709 |             DPOINT(ROW,1,1) = IXLNUM(NEWLOC)
      |                                     1
Error: Rank mismatch between actual argument at (1) and actual argument at (2) (rank-1 and scalar)
/home/georgtree/trilinos_serial/Trilinos-trilinos-release-12-12-1/packages/seacas/libraries/supes/mem_mgr/mdinit.F:768:42:

  261 |       MYLOC = IXLNUM (MYV)
      |                      2                    
......
  768 |             DPOINT(ROW,CHRCOL,1) = IXLNUM(NEWLOC)
      |                                          1
Error: Rank mismatch between actual argument at (1) and actual argument at (2) (rank-1 and scalar)

```

Looks like there is an issue with gfortran flags, but I don't know how to avoid it, thank you in advance,

**Comment by cgcgcg** [comment]
@gdsjaar FYI

@georgtree Is there a reason for building a Trilinos that's 7 years old?

**Comment by georgtree** [comment]
Hello, it is a requirement for xyce

**Comment by gsjaardema** [comment]
The gfortran argument `-fallow-argument-mismatch` can be used to quiet these messages.  I thought we were using that already in current code, but I can't seem to find it in the repository anywhere....

The code where that is showing up is in some older legacy graphic libraries that are still being used for blot and fastq.  If you are not using those applications in xyce, then you could alternatively turn off building of those...   Although will probably also show up in some of the other fotrran seacas applications.

**Comment by olisnr** [comment]
for ubuntu 20.04 install:

sudo apt install gmp-static
sudo apt install -y libgmp-dev
sudo apt install -y libmpfr-dev
sudo apt install -y libatlas-base-dev
sudo apt install -y gfortran make cmake bison flex libfl-dev libfftw3-dev libsuitesparse-dev libblas-dev liblapack-dev libtool autoconf automake git libopenmpi-dev openmpi-bin

sudo apt install gmp-static
sudo apt install -y libgmp-dev
sudo apt install -y libmpfr-dev
sudo apt install -y libatlas-base-dev
sudo apt install nvidia-cuda-toolkit

sudo apt install -y bison flex libfl-dev libfftw3-dev libsuitesparse-dev libblas-dev liblapack-dev libtool libopenmpi-dev openmpi-bin libtpl-dev libsuitesparse-dev libumfpack5

sudo apt install gmp-static
sudo apt install -y libgmp-dev
sudo apt install -y libmpfr-dev
sudo apt install -y libatlas-base-dev

sudo apt install libnetcdf-dev

then try again

**Comment by cgcgcg** [comment]
@georgtree Can this be closed?

**Comment by georgtree** [comment]
yes
