### ISSUE TITLE
MueLu: MutuallyExclusiveTime exception thrown in destructor

### ISSUE THREAD

**Issue by tawiesn** [trilinos/Trilinos#1353]
Found by coverity:
https://scan8.coverity.com/reports.htm#v29792/p10118/fileInstanceId=15413332&defectInstanceId=5209626&mergedDefectId=156776

See also discussion here #1303 

I think the exception thrown in line 146 of MutuallyExclusiveTime.hpp should just be removed. It is not really necessary and the exception message seems incorrect, too.
@jhux2 @trilinos/muelu

**Comment by jhux2** [comment]
> I think the exception thrown in line 146 of MutuallyExclusiveTime.hpp should just be removed. It is not really necessary and the exception message seems incorrect, too.

Agreed.  We could just issue a warning message instead, as is done on line 106.  There's a similar problem in MueLu_LinkedList.cpp, line 84.  Coverity CID 156837.

**Comment by tawiesn** [comment]
Ok. I change it to an error message.

**Comment by aprokop** [comment]
Maybe get rid of all `TEUCHOS_TEST_FOR_EXCEPTION` in timers? Timers should not terminate program execution.

**Comment by tawiesn** [comment]
@aprokop Well, timers should not terminate the program. But exceptions might help to use the timers correctly. It's only important that no exceptions are thrown in the desctructors which would result in undefined behavior.

**Comment by aprokop** [comment]
@tawiesn Well, if the exceptions are thrown in other places, we then rely on the use to wrap MueLu's code with `try{} catch{}`. And the warnings should be enough to debug the incorrect use of timers.
Anyway, I don't hold a strong opinion on this.
