### ISSUE TITLE
Teuchos: Use of non-existent method

### ISSUE THREAD

**Issue by cgcgcg** [trilinos/Trilinos#13558]
@trilinos/teuchos 

## Bug Report
`Teuchos::ConstNonconstObjectContainer::count` uses `RCP::count()` but there is no such method:
https://github.com/trilinos/Trilinos/blob/e7fd307aba00df75d7aad0677d45cec45eea4251/packages/teuchos/core/src/Teuchos_ConstNonconstObjectContainer.hpp#L332-L333
What's the correct fix here? 
- Use `RCP::weak_count()`, or
- use `RCP::strong_count()`, or
- delete `Teuchos::ConstNonconstObjectContainer::count` since it's not used anywhere?

**Comment by bartlettroscoe** [comment]
I would vote for deleting it.  Users can just grab the RCP and query the account themselves.

**Comment by cgcgcg** [comment]
@bartlettroscoe Sounds good. I'll delete the method.
