### ISSUE TITLE
Having trouble installing Ubuntu 24.04

### ISSUE THREAD

**Issue by ET-w** [trilinos/Trilinos#13550]
Hi, 

Can anyone please help me out.  I am trying to install on Ubuntu (TBH I am new to Ubuntu).  

This is my do-configure:
cmake \
-DTPL_ENABLE_MPI=ON \
-DTPL_ENABLE_Netcdf=OFF \
-DMPI_BASE_DIR=/usr/bin/gcc \
-DTrilinos_ENABLE_ALL_PACKAGES=ON \
-DCMAKE_INSTALL_PREFIX=/home/erik/Trilinos \
/home/erik/Downloads/Trilinos-master

I think this is pretty standard. All I added was to not enable Netcdf because it threw an error since it could not be found. 

When I go to make, this is the error:
...
[ 61%] Built target stk_search
[ 61%] Building CXX object packages/stk/stk_transfer/stk_transfer/CMakeFiles/stk_transfer.dir/copy_by_id/SearchByIdGeometric.cpp.o
In file included from /home/erik/Downloads/Trilinos-master/packages/stk/stk_search/stk_search/morton_lbvh/MortonLBVH_Search.hpp:37,
                 from /home/erik/Downloads/Trilinos-master/packages/stk/stk_search/stk_search/morton_lbvh/CoarseSearchMortonLBVH.hpp:41,
                 from /home/erik/Downloads/Trilinos-master/packages/stk/stk_search/stk_search/CoarseSearch.hpp:43,
                 from /home/erik/Downloads/Trilinos-master/packages/stk/stk_transfer/stk_transfer/copy_by_id/SearchByIdGeometric.cpp:38:
/home/erik/Downloads/Trilinos-master/packages/stk/stk_search/stk_search/morton_lbvh/MortonLBVH_Tree.hpp: In instantiation of ‘struct stk::search::MortonAabbTree<stk::search::MortonAabbTree<Kokkos::View<stk::search::BoxIdent<stk::search::Box<float>, stk::search::IdentProc<long unsigned int> >*, Kokkos::Serial>, Kokkos::Serial>, Kokkos::Serial>’:
/home/erik/Downloads/Trilinos-master/packages/stk/stk_search/stk_search/morton_lbvh/MortonLBVH_ParallelConsistencyUtils.hpp:158:81:   required from ‘std::pair<std::vector<RangeBoxType>, std::vector<RangeIdentProcType> > stk::search::morton_extend_local_range_with_remote_boxes_that_might_intersect(const std::vector<std::pair<_Tp1, _Tp2> >&, const std::vector<std::pair<RangeBoxType, RangeIdentProcType> >&, MPI_Comm, const ExecutionSpace&) [with ExecutionSpace = Kokkos::Serial; DomainBoxType = Sphere<float>; DomainIdentProcType = IdentProc<long unsigned int>; RangeBoxType = Sphere<float>; RangeIdentProcType = IdentProc<long unsigned int>; MPI_Comm = ompi_communicator_t*]’
/home/erik/Downloads/Trilinos-master/packages/stk/stk_search/stk_search/morton_lbvh/CoarseSearchMortonLBVH.hpp:150:82:   required from ‘void stk::search::coarse_search_morton_lbvh(const std::vector<std::pair<_T1, _T2> >&, const std::vector<std::pair<_ForwardIterator1, _ForwardIterator2> >&, MPI_Comm, std::vector<std::pair<DomainIdentType, RangeIdentType> >&, bool, bool) [with DomainBoxType = Sphere<float>; DomainIdentProcType = IdentProc<long unsigned int>; RangeBoxType = Sphere<float>; RangeIdentProcType = IdentProc<long unsigned int>; MPI_Comm = ompi_communicator_t*]’
/home/erik/Downloads/Trilinos-master/packages/stk/stk_search/stk_search/CoarseSearch.hpp:108:32:   required from ‘void stk::search::coarse_search(const std::vector<std::pair<_T1, _T2> >&, const std::vector<std::pair<_ForwardIterator1, _ForwardIterator2> >&, SearchMethod, stk::ParallelMachine, std::vector<std::pair<DomainIdentType, RangeIdentType> >&, bool, bool, bool) [with DomainBoxType = Sphere<float>; DomainIdentProcType = IdentProc<long unsigned int>; RangeBoxType = Sphere<float>; RangeIdentProcType = IdentProc<long unsigned int>; stk::ParallelMachine = ompi_communicator_t*]’
/home/erik/Downloads/Trilinos-master/packages/stk/stk_transfer/stk_transfer/copy_by_id/SearchByIdGeometric.cpp:98:29:   required from here
/home/erik/Downloads/Trilinos-master/packages/stk/stk_search/stk_search/morton_lbvh/MortonLBVH_Tree.hpp:93:9: error: no type named ‘HostMirror’ in ‘struct stk::search::MortonAabbTree<Kokkos::View<stk::search::BoxIdent<stk::search::Box<float>, stk::search::IdentProc<long unsigned int> >*, Kokkos::Serial>, Kokkos::Serial>’
   93 |   using BoxViewType_hmt = typename ViewType::HostMirror;
      |         ^~~~~~~~~~~~~~~
/home/erik/Downloads/Trilinos-master/packages/stk/stk_search/stk_search/morton_lbvh/MortonLBVH_Tree.hpp:94:9: error: no type named ‘value_type’ in ‘using stk::search::MortonAabbTree<stk::search::MortonAabbTree<Kokkos::View<stk::search::BoxIdent<stk::search::Box<float>, stk::search::IdentProc<long unsigned int> >*, Kokkos::Serial>, Kokkos::Serial>, Kokkos::Serial>::BoxViewType = struct stk::search::MortonAabbTree<Kokkos::View<stk::search::BoxIdent<stk::search::Box<float>, stk::search::IdentProc<long unsigned int> >*, Kokkos::Serial>, Kokkos::Serial>’ {aka ‘struct stk::search::MortonAabbTree<Kokkos::View<stk::search::BoxIdent<stk::search::Box<float>, stk::search::IdentProc<long unsigned int> >*, Kokkos::Serial>, Kokkos::Serial>’}
   94 |   using BoxType         = typename BoxViewType::value_type::box_type;
      |         ^~~~~~~
/home/erik/Downloads/Trilinos-master/packages/stk/stk_search/stk_search/morton_lbvh/MortonLBVH_Tree.hpp:97:9: error: no type named ‘value_type’ in ‘struct stk::search::MortonAabbTree<Kokkos::View<stk::search::BoxIdent<stk::search::Box<float>, stk::search::IdentProc<long unsigned int> >*, Kokkos::Serial>, Kokkos::Serial>’
   97 |   using kokkos_aabb_types = MortonAabbTypes<real_type, ExecutionSpace>;
      |         ^~~~~~~~~~~~~~~~~
make[2]: *** [packages/stk/stk_transfer/stk_transfer/CMakeFiles/stk_transfer.dir/build.make:107: packages/stk/stk_transfer/stk_transfer/CMakeFiles/stk_transfer.dir/copy_by_id/SearchByIdGeometric.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:14161: packages/stk/stk_transfer/stk_transfer/CMakeFiles/stk_transfer.dir/all] Error 2
make: *** [Makefile:166: all] Error 2

Thanks

**Comment by alanw0** [comment]
This build error in stk-search was fixed just a few days ago by this pull-request into the develop branch: https://github.com/trilinos/Trilinos/pull/13547

**Comment by cgcgcg** [comment]
@ET-w Can this be closed?
