### ISSUE TITLE
Teko: Assigning -1 to size_t

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#1356]
@trilinos/teko I was testing Teko and noticed several build warnings like this (in other files too):
```
.../Trilinos/packages/teko/src/Tpetra/Teko_InterlacedTpetra.cpp(259): warning: integer conversion resulted in a change of sign
```
I looked at the line in question, and it directly assigns -1 to a `size_t` variable.  This is probably meant as a flag "invalid" value.  If you want that, you may use `Teuchos::OrdinalTraits<size_t>::invalid()`.

**Comment by egphill** [comment]
@mhoemmen Thanks for pointing this out. I can go through and fix these.
