### ISSUE TITLE
Kokkos:  compiling with HIP on Frontier

### ISSUE THREAD

**Issue by kgottiparthi** [trilinos/Trilinos#13572]
We compiled Trilinos-16 on Frontier and configured it with HIP. We have a code that uses this installation and the following compilation error occurs 

PenaltyParameter_impl.hpp:76:49: error: __host__ function 'operator()' cannot overload __host__ __device__ function 'operator()'
void ViscousPenaltyParameter<EvalType, Traits>::operator()(
                                                ^
PenaltyParameter.hpp:40:10: note: previous declaration is here
    void operator()(
         ^
1 error generated when compiling for gfx90a.

The location the code complains uses 

    KOKKOS_INLINE_FUNCTION
    void operator()(
        const Kokkos::

We are not sure if we need to update this to compile with HIP. Please advice us how to proceed. 

Thank you,
Kalyan

**Comment by cgcgcg** [comment]
I cannot find that code in Trilinos. Can you point me to it?

**Comment by jhux2** [comment]
@kgottiparthi You might ask on the Kokkos slack channel instead.

**Comment by kgottiparthi** [comment]
We were able to fix this by defining every operator instance with KOKKOS_INLINE_FUNCTION. This is not an issue now. 

Thank you,
Kalyan
