### ISSUE TITLE
Tpetra::CrsGraph: Get rid of nodeNumEntries_ (or compute as a "local collective")

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#1357]
@trilinos/tpetra See #1342 for discussion.

The fact that CrsGraph updates `nodeNumEntries_` every time users insert an edge, adds state and hinders thread safety and scalability.  It would make more sense to have `getNodeNumEntries` compute this on demand, possibly caching it, using the following pattern:
```
numEnt = atomically fetch nodeNumEntries_;
if (numEnt has an "invalid" flag value) {
  compute numEnt;
  Kokkos::atomic_assign (&nodeNumEntries_, numEnt);
}
return numEnt;
```

**Comment by aprokop** [comment]
Doesn't your pseudo-code result in a race condition?

**Comment by maherou** [comment]
While it is fine to do modest refactoring of the Tpetra global data view, this is another example of why we should direct users to Kokkos and aggressively deprecate the Tpetra facade to Kokkos.

**Comment by mhoemmen** [comment]
@aprokop wrote:
> Doesn't your pseudo-code result in a race condition?

Probably :-)  The intent is "cache value, and update only when necessary" (e.g., first fillComplete).

**Comment by mhoemmen** [comment]
@maherou wrote:
> While it is fine to do modest refactoring of the Tpetra global data view, this is another example of why we should direct users to Kokkos and aggressively deprecate the Tpetra facade to Kokkos.

It's easier to do that, and to refactor Tpetra, if we first remove all the unnecessary state from Tpetra that we can remove without changing semantics.  I would rather start with less code and less state.

**Comment by mhoemmen** [comment]
Fixed now in develop.

**Comment by mhoemmen** [comment]
The implementation of the fix just recomputes getNodeNumEntries() as needed.  This only requires actual computation (rather than a simple lookup) if the graph / matrix is DynamicProfile.
