### ISSUE TITLE
STK Link error with NALU after weekend integration

### ISSUE THREAD

**Issue by crtrott** [trilinos/Trilinos#136]
WIth the new version of STK I now get link errors in NALU:

```
Linking CXX executable naluX
icpc: command line warning #10006: ignoring unknown option '-Wno-pragmas'
icpc: command line warning #10006: ignoring unknown option '-Wno-delete-non-virtual-dtor'
/home/crtrott/TrilinosBuild/OpenMP/Intel/15.0.2/Nalu/install-muelukk/lib/libstk_mesh_base.a(ElemElemGraph.cpp.o): In function `stk::mesh::ElemElemGraph::pack_shared_side_nodes_of_elements(stk::CommSparse&, std::multimap<stk::mesh::impl::EntitySidePair, stk::mesh::impl::ProcFaceIdPair, std::less<stk::mesh::impl::EntitySidePair>, std::allocator<std::pair<stk::mesh::impl::EntitySidePair const, stk::mesh::impl::ProcFaceIdPair> > >&)':
/home/crtrott/Trilinos/packages/stk/stk_mesh/stk_mesh/baseImpl/elementGraph/ElemElemGraph.cpp:483: undefined reference to `stk::mesh::impl::get_element_block_part_ordinals(stk::mesh::Entity, stk::mesh::BulkData const&)'
/home/crtrott/TrilinosBuild/OpenMP/Intel/15.0.2/Nalu/install-muelukk/lib/libstk_mesh_base.a(ElemElemGraph.cpp.o): In function `stk::mesh::ElemElemGraph::create_parallel_info(stk::mesh::Entity, stk::mesh::Entity, int, int)':
/home/crtrott/Trilinos/packages/stk/stk_mesh/stk_mesh/baseImpl/elementGraph/ElemElemGraph.cpp:1791: undefined reference to `stk::mesh::impl::get_element_block_part_ordinals(stk::mesh::Entity, stk::mesh::BulkData const&)'
/home/crtrott/Trilinos/packages/stk/stk_mesh/stk_mesh/baseImpl/elementGraph/ElemElemGraph.cpp:1791: undefined reference to `stk::mesh::impl::get_element_block_part_ordinals(stk::mesh::Entity, stk::mesh::BulkData const&)'
make[2]: *** [naluX] Error 1
make[1]: *** [CMakeFiles/naluX.dir/all] Error 2
make: *** [all] Error 2
```

Probably something stupid simple, but if you need more info let me know.

**Comment by gdsjaar** [comment]
The missing function should be provided in stk_mesh/stk_mesh/baseImpl/EquivalentEntityBlocks.cpp.  This should be in the stk_mesh_base library which is also where the ElemElemGraph.cpp ends up.  They should be in the same library, so not sure why the symbol isn't being resolved.

..Greg
--
"A supercomputer is a device for turning compute-bound problems into I/O-bound problems"

**Comment by bmpersc** [comment]
It looks like the STK cmake build is out of date again. Only the stk_mesh/stk_mesh/base dir is being built in Trilinos. I'll fix this in Sierra and pull it over to Trilinos today.

**Comment by pbosler** [comment]
I suspect this issue is related to https://github.com/trilinos/Trilinos/issues/62, which has been causing problems with my Mac builds.   I'm optimistic this might fix that one, too!

Pete

**Comment by bmpersc** [comment]
I just verified that currently the stk build is doing the right thing. I didn't try to link nalu, but my stk_mesh base library has the missing symbol. The disconnect may be either in the export files from Trilinos or the way Nalu is using them. I'll need to dig more there to find out which.

Pete,
  I doubt these are related, the missing symbols from that bug are in a very different part of STK. It is entirely possible that those symbols were in a file that had to be removed due to the fact that it couldn't be built in Trilinos due to it's dependencies. That too will require digging to figure out what the issue is.

**Comment by aprokop** [comment]
Is this still an issue, or can it be closed?

**Comment by alanw0** [comment]
I don't recall seeing this github issue before, but the code issue has been resolved.
