### ISSUE TITLE
MueLu: Unused variable

### ISSUE THREAD

**Issue by cgcgcg** [trilinos/Trilinos#13605]
## Bug Report
Albany reported a failing warnings-as-errors build here: https://github.com/sandialabs/Albany/issues/1090

```
[Trilinos/packages/muelu/src/Interface/MueLu_ParameterListInterpreter_def.hpp:1302](https://blob/master/Trilinos/packages/muelu/src/Interface/MueLu_ParameterListInterpreter_def.hpp#L1302):8: error: variable 'useAggregateQualities' set but not used [-Werror=unused-but-set-variable]
```

Looks like this could have been caused by https://github.com/trilinos/Trilinos/pull/13592

**Comment by maxfirmbach** [comment]
@cgcgcg Can this be closed?
