### ISSUE TITLE
Framework:  "TrilinosInstallTests_reduced_tarball" failing in a few PRs

### ISSUE THREAD

**Issue by jhux2** [trilinos/Trilinos#13615]
## Bug Report

@trilinos/framework Several PRs pass all tests except "TrilinosInstallTests_reduced_tarball", e.g., #13607 and #13606.  This can probably be resolved by retesting everything, but this seems like a waste of time & resources.  Going forward, would there be some way of rerunning just the reduced tarball test, assuming all other PR tests have passed?

**Comment by sebrowne** [comment]
Good catch, I accidentally broke our "non-blocking build" capability with a recent change.  I just fixed it, and it should be fixed now.  That build (the one called "Python3") which is SUPPOSED to only run our (Framwork's) unit tests has been giving us issues for a while (it shouldn't even be running that test).  So we set it to non-blocking a while back, which means that even if the CDash page shows a failure, it will PASS in GitHub.  I think it's fixed now, apologies for the churn.  I will check on the builds later tonight and close this if I can confirm it's fixed.

**Comment by cgcgcg** [comment]
#13578 seems to have been hit by this as well.

**Comment by cgcgcg** [comment]
Trilinos_PR_python3 also failed in #13589.

**Comment by sebrowne** [comment]
Okay I think I have it fixed now (but it's very obnoxious/impossible to test), so I added RETEST to the linked PRs.

**Comment by sebrowne** [comment]
99% sure this is fixed, closing (but can be reopened if anybody notices it's still occurring).

**Comment by cgcgcg** [comment]
Looks fixed to me, thank you!
