### ISSUE TITLE
TriBITS: CuSolver TPL still uses raw find_library call

### ISSUE THREAD

**Issue by terwin** [trilinos/Trilinos#13624]
## Bug Report
@bartlettroscoe

### Description
#11093 updated CUDA TPLs to use `find_package(CUDATookit)` rather than raw `find_` commands, but [cmake/TPLs/FindTPLCUSOLVER.cmake](https://github.com/trilinos/Trilinos/blob/70822c3f3191b8abe57c9945ec830507b6f17c43/cmake/TPLs/FindTPLCUSOLVER.cmake) was excluded.

**Comment by bartlettroscoe** [comment]
CC: @trilinos/framework, @sebrowne 

@terwin, what is the underlying driver for this request?  PR #11093 was in response to a specific issue with a customer code (see #10954).

**Comment by terwin** [comment]
@bartlettroscoe, I encountered this while rebuilding our code (without rebuilding Trilinos) after the CUDA installation on our system was moved. The build failed due to a single hard-coded path in the Trilinos installation (in CUSOLVERConfig.cmake). Digging into the origin of that hard-coded path, I found that the cuSOLVER TPL was inconsistent with the other CUDA TPLs and traced it back to #11093. This seemed like an oversight in that PR.

**Comment by bartlettroscoe** [comment]
@terwin, if you are in position to give this a try, could you try updating [cmake/TPLs/FindTPLCUSOLVER.cmake](https://github.com/trilinos/Trilinos/blob/70822c3f3191b8abe57c9945ec830507b6f17c43/cmake/TPLs/FindTPLCUSOLVER.cmake) to replicate the changes made in those other modules?

**Comment by terwin** [comment]
@bartlettroscoe, sure. I'll submit a PR later today.

**Comment by sebrowne** [comment]
Thanks for doing the legwork on this @terwin and @bartlettroscoe !
