### ISSUE TITLE
Phalanx: any_cast failure in test

### ISSUE THREAD

**Issue by ibaned** [trilinos/Trilinos#1365]
Running the test
```
Phalanx_mdfield_runtime_MPI_1
```

Prints the following:

```
Error in runtime PHX::MDField::setFieldData() in PHX::any_cast. Tried to cast the field "Test1" with the identifier "Test1:double:<Cell>(100)" to a type of "???" from a PHX::any object containing a type of "Kokkos::View<double**, Kokkos::Serial>".
```

And despite that, the test passes.

@trilinos/phalanx

**Comment by rppawlo** [comment]
That is actually the correct behavior. I think this is an issue with the Teuchos test harness printing a partial message. If you rerun the test in verbose mode with:

./Phalanx_mdfield_runtime.exe --details=ALL

then you get the full output that tells you that this throw is expected:

```
 Test that code {f1.setFieldData(PHX::KokkosViewFactory<double,PHX::Device>::buildView(f2.fieldTag()));} throws PHX::bad_any_cast: 

Error in runtime PHX::MDField::setFieldData() in PHX::any_cast. Tried to cast the field "Test1" with the identifier "Test1:double:<Cell>(100)" to a type of "???" from a PHX::any object containing a type of "Kokkos::View<double**, Kokkos::OpenMP>".
passed
 
 Exception message for expected exception:
 
  PHX::any::bad_any_cast: failed conversion using PHX::any_cast
  
 Testing operator<<()...passed!
```

It looks like in non-verbose mode, the result of the TEST_THROW is getting printed when it shouldn't be.

**Comment by ibaned** [comment]
Thanks @rppawlo , I guess theres nothing wrong here but some extra prints, and those aren't really a huge deal.
