### ISSUE TITLE
TpetraExt::MatrixMatrix::add thread scaling needs improvement

### ISSUE THREAD

**Issue by pwxy** [trilinos/Trilinos#1367]
Trilinos was built with kokkos node type OpenMP (intel 17.0.2 compiler)
Looked at thread scaling for a single KNL.
Running with 1 MPI process and increasing number of threads from 1 to 64 (so have one thread per core).

| t |  TpetraExt::MatrixMatrix::add (seconds) |
| -- |:--:|
| 1  | 1154.0 |
| 2  | 799.8 |
| 4  | 620.5 |
| 8  | 527.3 |
| 16 | 483.9 |
| 32 | 467.4 |
| 64 | 461.7 |

Most of the TpetraExt::MatrixMatrix::add time is due to Tpetra::CrsMatrix::fillComplete
The suboptimal scaling of  TpetraExt::MatrixMatrix::add is due the suboptimal scaling of Tpetra::CrsMatrix::fillComplete
fillComplete time is very roughly 1/3 time Tpetra::CrsGraph::makeColMap, 1/3 time Tpetra::CrsMatrix::sortAndMergeIndicesAndValues, and 1/3 time Tpetra::CrsGraph::makeIndicesLocal

Thread scalability of CrsMatrix::fillComplete has already been reported in:
Tpetra: Improve thread scalability of CrsMatrix::fillComplete #829

**Comment by mhoemmen** [comment]
@pwxy This is good to know; thanks for sharing the timings!  Here is current status of the functions you mentioned:

  - `sortAndMergeIndicesAndValues` should be OpenMP thread parallel at this point, at least in develop.
  - `makeIndicesLocal` will not be hard to make thread parallel.  However, see below.
  - `makeColMap` will not be very hard to make thread parallel, _if_ I'm allowed to sort that column indices.  (Tpetra sorts by default.  However, it has a run-time option to preserve user order of column indices in the column Map.  This will be very hard to thread-parallelize in an efficient way.)  However, see below.

it surprises me that `TpetraExt::MatrixMatrix::add` needs to create a column Map and convert from global to local.  It should use `setUnion` on the column Maps and Import objects of the two input matrices, thus bypassing `makeColMap` and `makeImportExport`.  That means it _should_ be able to fill using local indices.

@jhux2 Does `add` get called in MueLu setup?  I thought it had gotten subsumed into the Jacobi matrix-matrix multiply?

**Comment by pwxy** [comment]
@jhux2 MatrixMatrix::add does not get called in MueLu setup.  However, it is called by teko.

@mhoemmen I am using trilinos develop (but as of May 24); from the above table, some portions of TpetraExt::MatrixMatrix::add are threaded, and I assume this is sortAndMergeIndicesAndValues as you mentioned.
@aprokop would you happen to know why MatrixMatrix::add "needs to create a column Map and convert from global to local" ?

**Comment by mhoemmen** [comment]
@pwxy I think what's happening, is that `TpetraExt::MatrixMatrix::add` dispatches to `Tpetra::CrsMatrix::add`, and the latter just always uses global indices.  It looks like MueLu optimized its use cases, but we haven't had a reason yet (until Teko) to optimize other use cases.

**Comment by mhoemmen** [comment]
@pwxy Could you send me an e-mail defining priority of this effort?  The work would be straightforward, but it would take time away from the other things we're working on this FY.  Also, does Teko fill-complete the input matrices first?

**Comment by aprokop** [comment]
> @aprokop would you happen to know why MatrixMatrix::add "needs to create a column Map and convert from global to local" ?

@pwxy Not sure.

> @jhux2 Does add get called in MueLu setup? I thought it had gotten subsumed into the Jacobi matrix-matrix multiply?

@mhoemmen The answer is no for the standard use case. There are other use cases where we do call it directly, though, like energy minimization or Petrov-Galerkin.

**Comment by pwxy** [comment]
@eric-c-cyr @egphill would you happen to know whether  PlasmaPreconditionerFactory::buildPreconditionerOperator fill-completes the matrices before calling TpetraExt::MatrixMatrix::add (called by Teko::explicitAdd)? I'm guessing no.

**Comment by egphill** [comment]
@pwxy fillComplete does get called in Teko::explicitMultiply, so I think yes.

**Comment by pwxy** [comment]
I see in TpetraExt::MatrixMatrix_def.hpp that there is one TpetraExt::MatrixMatrix::add() and two TpetraExt::MatrixMatrix::Add()

From the "TEUCHOS_TEST_FOR_EXCEPTION" I have a reasonable guess what each is for, but which one should Teko::explicitAdd() be calling?



TpetraExt::MatrixMatrix::Add()

  TEUCHOS_TEST_FOR_EXCEPTION(!A.isFillComplete(), std::runtime_error,
    prefix << "ERROR, input matrix A.isFillComplete() is false; it is required to be true. "
    "(Result matrix B is not required to be isFillComplete()).");
  TEUCHOS_TEST_FOR_EXCEPTION(B.isFillComplete() , std::runtime_error,
    prefix << "ERROR, input matrix B must not be fill complete!");
  TEUCHOS_TEST_FOR_EXCEPTION(B.isStaticGraph() , std::runtime_error,
    prefix << "ERROR, input matrix B must not have static graph!");
  TEUCHOS_TEST_FOR_EXCEPTION(B.isLocallyIndexed() , std::runtime_error,
    prefix << "ERROR, input matrix B must not be locally indexed!");
  TEUCHOS_TEST_FOR_EXCEPTION(B.getProfileType()!=DynamicProfile, std::runtime_error,
    prefix << "ERROR, input matrix B must have a dynamic profile!");



TpetraExt::MatrixMatrix::add()

  TEUCHOS_TEST_FOR_EXCEPTION(!A.isFillComplete () || !B.isFillComplete (), std::invalid_argument,
    prefix << "A and B must both be fill complete.");



TpetraExt::MatrixMatrix::Add()

  TEUCHOS_TEST_FOR_EXCEPTION(
    ! A.isFillComplete () || ! B.isFillComplete (), std::invalid_argument,
    prefix << "Both input matrices must be fill complete before calling this function.");



Could you remind me the other optimizations that could be done for either 
TpetraExt::MatrixMatrix::add() or TpetraExt::MatrixMatrix::Add() to reduce the fillComplete calls
in order to improve thread scaling of Teko::explicitAdd()?

**Comment by mhoemmen** [comment]
@jhux2 @csiefer2 I'll be stuck in meetings for the next two days and won't have a chance to look at this.  Could one or both of you two help out?  Thanks!

**Comment by pwxy** [comment]
@mhoemmen would you have a chance to explain which Add() or add() I should be using?  Thanks!

**Comment by mhoemmen** [comment]
@pwxy Use `Add()` (capital A) for now.

**Comment by jhux2** [comment]
@brian-kelley has been working on a threaded kernel. Adding @csiefer2 to the discussion.

**Comment by mhoemmen** [comment]
@jhux2 @brian-kelley Nice! :-D  btw is there a plan to consolidate the `add()` and `Add()` implementations?  It would be nicer if there were only one code to edit :)

**Comment by brian-kelley** [comment]
@mhoemmen Yes, @csiefer2 and I talked about doing that. I will probably write a single add() that covers all the use cases of the current functions, and then change the old ones to wrappers.

**Comment by mhoemmen** [comment]
@brian-kelley Thanks!

**Comment by brian-kelley** [comment]
@mhoemmen One of the Add() functions (TpetraExt_MatrixMatrix_decl.hpp:206) takes the output C as an RCP by value, so in the case that C is null on input, there is no way to create a new matrix and have it visible to the caller:
~~~~
template <class Scalar,
          class LocalOrdinal,
          class GlobalOrdinal,
          class Node>
void Add(
  const CrsMatrix<Scalar, LocalOrdinal, GlobalOrdinal, Node>& A,
  bool transposeA,
  Scalar scalarA,
  const CrsMatrix<Scalar, LocalOrdinal, GlobalOrdinal, Node>& B,
  bool transposeB,
  Scalar scalarB,
  Teuchos::RCP<CrsMatrix<Scalar, LocalOrdinal, GlobalOrdinal, Node> > C);
~~~~
This is acknowledged in the documentation:
~~~~
/// \warning The case where C == null on input does not actually work.
///   In order for it to work, we would need to change the interface
///   of this function (for example, to pass in C as a (pointer or
///   nonconst reference) to a Teuchos::RCP).  Please use add() (which
///   see) if you want matrix-matrix add to return a new instance of
///   CrsMatrix.
~~~~
I was wondering if I could either change C to be a reference, or update the documentation to say that C must not be null. Could I do one of those (preferably the first), or should I just leave it?

**Comment by brian-kelley** [comment]
@mhoemmen As an update, I got the kernels and tests working (one for sorted graph, one for unsorted graph). These create new graphs. I will also create two more kernels for the graph reuse case (B's graph already matches sum's sparsity pattern, should be much faster). I'm wondering about that Add() interface because I am consolidating the add/Adds into one general function.

**Comment by mhoemmen** [comment]
@brian-kelley I would say, add a new "add" function (please use lower case for consistency with Tpetra) with the interface that you want.  We can worry about compatibility later.

The "add" function really has two use cases:

  1. C doesn't exist yet.  Create it and return it.
  2. C exists.  Overwrite it with the result.  Reuse any allocations or communication patterns already in C that make sense to reuse.

The former calls for returning C as an `RCP<CrsMatrix>`; the latter calls for taking C as a nonconst reference output argument.

**Comment by brian-kelley** [comment]
I just made the pull request for this issue: #1606. @pwxy, the thread scaling results I measured are very good compared to what existed before (100K rows, 100 nz per row, avg over 100 trials on bowman KNL):
Threads-------MatrixMatrix::add() Time (sec)
1 5.3481871
2 2.7995903
4 1.4830135
8 0.8161387
16 0.5162359
32 0.3524023
64 0.23034902

**Comment by brian-kelley** [comment]
@jhux2 Would you like me to add you as a reviewer? Anyone else I should add?

**Comment by jhux2** [comment]
> @jhux2 Would you like me to add you as a reviewer? Anyone else I should add?

@brian-kelley Yes, please do.  You've already got the two reviewers I would have suggested.

**Comment by pwxy** [comment]
I'm running drekar on a single KNL of mutrino, with 1 MPI process, and I increase the OMP threads from 1 to 64 (1 OMP thread per core):

old TpetraExt::MatrixMatrix::add

| t | time(s) |
| -:| -:|
|1|143.30|
|2|99.62|
|4|77.44|
|8|66.25|
|16|61.03|
|32|58.90|
|64|58.33|

@brian-kelley's new TpetraExt::MatrixMatrix::add

| t | time(s) |
| -:| -:|
|1|17.24|
|2|8.94|
|4|4.92|
|8|2.75|
|16|1.88|
|32|1.60|
|64|1.57|

drekar/Trilinos was built with intel 17.0.2 and gnu 6.1.0 (Trilinos repo as of August 16, 2017)

The first thing to notice is that the new TpetraExt::MatrixMatrix::add is significantly faster even for one OMP thread, about 8x faster.  And then it thread scales well to 16 threads.
Excellent improvement @brian-kelley 

Unfortunately I tried the following study on a single KNL where I started with 64 MPI processes with 1 thread,
and then kept halving the number of MPI processes and doubling the number of OMP threads so that
(MPI processes)*(OMP threads)=64

I would have expected the MatrixMatrix::add time to stay roughly constant, but it doesn't:

|MPI| t|  time(s)|
| -:| -:| -:|
|64 | 1|  54.74|
|32 | 2|  72.75|
|16 | 4|  95.35|
|8  | 8|  132.70|
|4  |16|  191.50|
|2  |32| 263.30|
|1  |64|  13.15|

I discussed this with this @brian-kelley afternoon, and he tracked it down to a problem with OpenMP node.
So it seems that for now, I cannot use the new fast TpetraExt::MatrixMatrix::add with more than one MPI process.

**Comment by jhux2** [comment]
Adding @csiefer2.

**Comment by brian-kelley** [comment]
@pwxy Are the 1 rank, 64 thread time (last chart) for the same problem and running in the same configuration/environment as the middle chart with 1 thread, 64 threads? The middle time is 1.57s, but the last one is 13.15s. What is the difference between those two cases?

**Comment by pwxy** [comment]
@brian-kelley I updated my previous comment; the 13.15s time is for a problem 8 times larger than the 1.57s time, hence the 8x larger factor in time.

**Comment by mhoemmen** [comment]
FYI @brian-kelley asked me to wait on the merge of #1606 (that would fix this issue), until he changes the code to use `Tpetra::Import::setUnion` (see my review in #1606), and possibly also adds thread parallelization to the implementation of `setUnion`.

**Comment by jhux2** [comment]
> I discussed this with @brian-kelley this afternoon, and he tracked it down to a problem with OpenMP node.
> So it seems that for now, I cannot use the new fast TpetraExt::MatrixMatrix::add with more than one MPI process.


@brian-kelley What is/was the issue with OpenMP node?

**Comment by brian-kelley** [comment]
@jhux2 While increasing the number of SerialNode ranks, the running time decreases as you would expect, but with OpenMP node the time increases. I've observed this on both cee-compute (xeon) and KNL machines but I have no idea why it happens. I could be missing some runtime parameter or environment variable, or it's just a performance bug.

**Comment by mhoemmen** [comment]
@brian-kelley What are your environment variables and OpenMP parameters btw?

**Comment by brian-kelley** [comment]
Environment variables:
~~~~
export OMP_NUM_THREADS=4
export OMP_PLACES=threads
export OMP_PROC_BIND=spread
export OMP_DISPLAY_ENV=verbose
~~~~
CMake configuration: https://gist.github.com/brian-kelley/479acc152e6addde0b54428aba8626eb

**Comment by mhoemmen** [comment]
@brian-kelley what's the scoop?  Do we need to do some deeper performance analysis?

**Comment by brian-kelley** [comment]
@mhoemmen I tried to profile this problem, and I actually can't replicate the OpenMP node slowdown on KNL anymore (but I still do on xeon). I went through my communication with other people about this and the last time I got the bad rank scaling on KNL was actually the day before I got the right command to launch an MPI+OpenMP program:
~~~~
mpirun -np <procs> --map-by numa:PE=<threads> numactl --membind=1 ./<program>
~~~~
| threads | ranks | time(s) |
| -:| -:|
|8|8|0.1186|
|16|4|0.124553|
|32|2|0.137332|
|64|1|0.133752|

Import::setUnion is fairly expensive now and since it scales with ranks but not threads, that by itself makes up the small difference between these times.

When I saw @pwxy's times it looked very much like what I had seen before so I assumed it to be the same problem. But he was using the correct command and environment variables (given above and in my last comment), so I don't know what the issue is. I was surprised to see that the ranks work fine for me now.

**Comment by mhoemmen** [comment]
@brian-kelley I'm trying to compare old and new times, but it looks like the times aren't comparable.  Do you have an updated list of old vs. new times?  Also, by how much does this slow down Serial Node?

**Comment by brian-kelley** [comment]
New code, OpenMP node:
| Ranks | Threads | Avg add() time |
|:--:|:--:|:--:|
|8|8|0.1186|
|16|4|0.124553|
|32|2|0.137332|
|64|1|0.133752|

**Comment by mhoemmen** [comment]
@brian-kelley Does it fail on Haswell, given a comparable configuration (OpenMP, 1 thread per MPI process)?  If not, I think we should just do a final review and accept this.

**Comment by brian-kelley** [comment]
@mhoemmen On geminga (2 sockets, each with 10 cores, and 2 hyperthreads/core), using these options:
~~~~
export OMP_NUM_THREADS=4
export OMP_PLACES=cores
export OMP_PROC_BIND=spread
export OMP_DISPLAY_ENV=verbose

mpirun -np 4 --map-by socket ./program.exe
~~~~

it doesn't fail, the performance with many ranks isn't great either. I tried playing around the "--map by ppr:N:socket" binding but didn't get any improvement.

Ranks vs. threads, holding ranks * threads = 16:

| Ranks | Threads | Avg add() time |
|:--:|:--:|:--:|
|1|16|0.169234|
|2|8|0.166704|
|4|4|0.429636|
|8|2|0.62643|
|16|1|1.78967|

1 thread, N ranks:

| Ranks | Avg add() time |
|:--:|:--:|
|1|0.91327|
|2|0.673499|
|4|0.605082|
|8|0.826463|
|16|1.72138|

**Comment by mhoemmen** [comment]
@brian-kelley Final question: Is it faster than it was before?  If so, I'm accepting this thing :-) .

**Comment by brian-kelley** [comment]
@mhoemmen It's certainly a large factor faster than it was before. @pwxy said it was 8x better for his problem on a single rank/thread. I just did some final git cleanup (squashing, fixing conflicts against develop) so I would say it's ready to go.

I also profiled the Import::setUnion, and I didn't find any obvious things to parallelize or get big speedups. The most expensive things inside are std::sort and std::merge, and I don't think I can beat those. I could do a bucket sort and then sort buckets in parallel, but there's still a large amount of work to do in serial and then you also have to copy between host and device twice.

**Comment by mhoemmen** [comment]
@brian-kelley wrote:
> It's certainly a large factor faster than it was before. @pwxy said it was 8x better for his problem on a single rank/thread. I found the same thing a while ago but I don't have any official numbers.

I'll take that :-D .

> The most expensive things inside are `std::sort` and `std::merge`, and I don't think I can beat those.

Kokkos has a thread-parallel sort, but it currently lacks a merge.  We can always go back later and fix that.  C++17 proposals even include thread-parallel versions of standard library algorithms, so we may not even need to write it, at least not for CPUs.

**Comment by aprokop** [comment]
Is the next step for this to be incorporated as part of the Jacobi kernel? (Sorry for a hijacking the conversation slightly)

**Comment by mhoemmen** [comment]
@aprokop No worries!  The main issue here was that @pwxy needed sparse matrix-matrix add by itself to be thread parallel, since his app was using it through Teko.  It would make sense to extend the results to the Jacobi kernel, though we should talk to @mndevec about his optimization plans for sparse matrix-matrix multiply.

**Comment by brian-kelley** [comment]
@mhoemmen Something else we could try is just replacing the body of CrsMatrix::add() with this kernel, since it also returns a new matrix. That would speed up a lot more applications than just the TpetraExt add() and it would be very easy to do, except that TpetraExt is a separate build step that depends on Tpetra. Is there anything that can be done about this?

**Comment by aprokop** [comment]
@mhoemmen This may be stupid, but can't we try local matrix-matrix multiply with matrix-matrix add using independently @mndevec and @brian-kelley codes. The second one could bypass the `setUnion` call as we *know* that column map of AB would contain that of B. Later, we could try to optimize inside matrix-matrix multiply.

Ideally, I'd like to know the answer to the question: what is the fastest to run with a single thread right now: the serial Jacobi kernel, or the new matrix-matrix multiply with matrix-matrix add.

**Comment by mhoemmen** [comment]
@brian-kelley wrote:
> Something else we could try is just replacing the body of CrsMatrix::add() with this kernel, since it also returns a new matrix. 

`CrsMatrix::add` takes `A` as a `RowMatrix`, so it needs a fall-back host implementation in case `A` is not a `CrsMatrix`.  Otherwise, yes, this is a good idea :-) .

> That would speed up a lot more applications than just the TpetraExt add() and it would be very easy to do, except that TpetraExt is a separate build step that depends on Tpetra. Is there anything that can be done about this?

We could (and should) move the implementation of the add function out of so-called TpetraExt, into `tpetra/core/src`.  TpetraExt "happened" but I didn't make it that way.  I see sparse matrix-matrix add and multiply as fundamental to a sparse linear algebra package; they don't belong in a separate fake "package."

**Comment by mhoemmen** [comment]
btw I'm getting some build errors with #1606, when I enable CUDA and turn on complex arithmetic via `Teuchos_ENABLE_COMPLEX:BOOL=ON` and `Trilinos_ENABLE_DOUBLE_COMPLEX:BOOL=ON`.  See comments there.

**Comment by brian-kelley** [comment]
@mhoemmen Sorry about that, I assumed that A and B would always have an Import but that's not true. To fix this I just went back to my own map union function.

**Comment by brian-kelley** [comment]
@mhoemmen There are now a bunch of build errors in the MueLu tests (all because "std::fabs" isn't found, probably just missing "include cmath"), so 44 MueLu tests weren't run, but the 20 MueLu tests that did run and all Ifpack2 tests pass.

**Comment by jjellio** [comment]
@brian-kelley,

Try:
-np 4 --map-by ppr:2:socket:pe=5

E.g., 2 MPI tasks per socket, each task gets 5 processing elements.

I'd also inspect --display-map --report-bindings, OpenMPI should print little X's indicating which task owns which core/thread. The point being to make sure that no tasks are sharing a core.

**Comment by mhoemmen** [comment]
@brian-kelley wrote:
> I read that std::fabs officially exists for float, double and long double.

It's not a`__device__` function though.  Use `Kokkos::ArithTraits::abs` for that :-) .

**Comment by mhoemmen** [comment]
btw I squashed PR #1606 into a single commit:

https://github.com/trilinos/Trilinos/commit/2e7cba859bafd69602ad31c1e8f0f5c9b7f3b443

and pushed it to develop today.  Thanks @brian-kelley !!! :-D  Thanks all for participating!
