### ISSUE TITLE
question about the usage of BGMRES

### ISSUE THREAD

**Issue by CSjkcyz** [trilinos/Trilinos#13672]
## BlockGmres did not converge!
Hello,
When I try to solve the problem with multiple right-terminal terms using BlockGmres method, after adding and setting blockSize>1 in BlockGmresKokkosExFile.cpp, why the result is not correct: ERROR: Belos did not converge! But setting blockSize=1 converges, does this mean that the algorithm has special requirements for solving matrices or certain parameters? The matrix I tested with is bcsstk12.mtx, num-rhs=4, blockSize=4.

Thanks!

**Comment by cgcgcg** [comment]
@trilinos/belos

**Comment by cgcgcg** [comment]
@hkthorn

**Comment by CSjkcyz** [comment]
Thank you, my problem is solved.
