### ISSUE TITLE
Zoltan:  HDF5 / Exodus linking error

### ISSUE THREAD

**Issue by tread7284** [trilinos/Trilinos#13686]
## Question
Trilinos organization members, please @ zoltran.  

During the make-step of Zoltran, I encounter a HDF5 / Exodus linking error. It occurs in Linking CXX executable test_generate_exo_files, Linking CXX executable epu, Linking CXX executable conjoin, and Linking CXX executable exodiff.

/usr/bin/ld: ../../libraries/exodus/libexodus.a(ex_utils.c.o): undefined reference to symbol 'H5get_libversion@@HDF5_SERIAL_1.8.7'
/usr/bin/ld: /lib/x86_64-linux-gnu/libhdf5_serial.so.103: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [packages/seacas/applications/exodiff/CMakeFiles/exodiff.dir/build.make:341: packages/seacas/applications/exodiff/exodiff] Error 1
make[1]: *** [CMakeFiles/Makefile2:9569: packages/seacas/applications/exodiff/CMakeFiles/exodiff.dir/all] Error 2
make: *** [Makefile:166: all] Error 2

I am not sure if I need to set a FLAG or if this is CMAKE linking issue. I was able to build and install Trilinos on my laptop, with the same env setup. Any help would be greatly appreciated!

**Comment by tread7284** [comment]
@ccober6 Thank you for re-directing the question to the correct Teams. I solved the problem, a explicit FLAG calling HDF5 was need. Thank you for your quick response

**Comment by ccober6** [comment]
Glad you were able to find the issue!
