### ISSUE TITLE
Sacado: build fail with GCC 4.4.7 no C++11 after MemoryPool changes

### ISSUE THREAD

**Issue by ibaned** [trilinos/Trilinos#1368]
http://testing.sandia.gov/cdash/viewBuildError.php?buildid=2923450

Pointed out to me by @etphipp

**Comment by ibaned** [comment]
So `std::uint32_t` is not official until C++11, but I believe `uint32_t` in the global namespace should still be available through `<stdint.h>`. I'll make a PR shortly.

**Comment by etphipp** [comment]
I don't exactly understand why this code even gets enabled in the failed build---seems like Kokkkos is enabled but the compiler doesn't support C++11.  That seems like a configuration problem, but this should fix the error regardless.

**Comment by ibaned** [comment]
I think there is a bit of Sacado code that declares the arguments to build a MemoryPool, which uses the `uint32_t` type, and that code is still compiled even if KokkosCore isn't enabled.

**Comment by ibaned** [comment]
The fix seems to have worked:
http://testing.sandia.gov/cdash/buildSummary.php?buildid=2934212
Please reopen if thats not the case.
