### ISSUE TITLE
Trilinos Header files are not found

### ISSUE THREAD

**Issue by cloud9legendre** [trilinos/Trilinos#13695]
When I try to configure using following cmake file and then build the project using ```make -j 4``` i get some of the header files are not there. But when i manually check the files are in ``` /usr/local/bin/trilinos/include/ ```. I dont know whether i forgot or something but i added the paths to the system varibles and tried to specifiy them in cmake config. But doesnt work. Do i have to reinstall trilinos with a modified configureation or am i looking at the wrong place.
``` 
/usr/local/bin/trilinos/include/Sacado_ConfigDefs.h:58:10: fatal error: Kokkos_Macros.hpp: No such file or directory
   58 | #include "Kokkos_Macros.hpp"
      |          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
```
Full log is here ->  [build.log](https://github.com/user-attachments/files/18252210/build.log)

cmake cofig file for my project
```cmake
rm -f CMakeCache.txt
rm -rf CMakeFiles/

cmake \
-D CMAKE_BUILD_TYPE:STRING=Release \
-D Trilinos_DIR:PATH=/usr/local/bin/trilinos/lib/cmake/Trilinos \
-D CMAKE_C_COMPILER:STRING=/usr/bin/mpicc \
-D CMAKE_CXX_COMPILER:STRING=/usr/bin/mpicxx \
-D BOOST_ROOT=/usr/local/boost \
-D CMAKE_CXX_FLAGS:STRING="-O2 -Wall -std=c++11 -pedantic -Wno-long-long -ftrapv -Wno-deprecated" \
/home/ashen/Documents/peridigm
```

**Comment by cgcgcg** [comment]
It is possible that peridigm is not correctly setting up the Trilinos dependency. We saw a similar issue in #13639. What you could try is to add 
```
Trilinos::all_libs
```
to this list
https://github.com/peridigm/peridigm/blob/82c6ad8f8152aaa3c8a2b4e7b31f82b8e1c6f28c/CMakeLists.txt#L284-L287
and see if that has any effect.

**Comment by cloud9legendre** [comment]
Issue Seemed to be resolved when i copied the contents of ```path/to/trilinos/inlcude/kokkos``` folder to the```path/to/trilinos/inlcude``` folder. I also added ```Trilinos::all_libs``` and added
```
include_directories(
    ${NETCDF_INCLUDE_DIRS}
    /usr/include
    /usr/local/include
    /usr/local/netcdf-c-4.9.2/include
)
```
to the CMakeLists.txt and the Project compiled successfully. Thanks for the help

**Comment by Dli292** [comment]
Hi, Can anyone please explain how to add Trilinos::all_libs to the CMakeLists? I just got the same issue. 
I did 
```
set (REQUIRED_LIBS
  ${BlasLapack_Libraries}
  ${Trilinos_TPL_LIBRARIES}
  ${Trilinos::all_libs}
)
```
which was invalid. Thanks.

**Comment by cgcgcg** [comment]
@Dli292 
Try with
```cmake
set (REQUIRED_LIBS
  ${BlasLapack_Libraries}
  Trilinos::all_libs
)
```
