### ISSUE TITLE
Teuchos: proposal for TeuchosParser subpackage

### ISSUE THREAD

**Issue by ibaned** [trilinos/Trilinos#1371]
The purpose of TeuchosParser would be to provide a C++ library which takes a language described by a Context Free Grammar and a set of tokens described by Regular Expressions, and generates a table-driven LALR(1) parser for this language. The parser takes the form of a C++ base class with virtual functions that users override to provide callbacks at each parsing step, allowing users to focus on how to interpret the language constructs, not how to interpret the text file.

Immediate benefits of TeuchosParser would be:

1. Applications often want users to be able to specify boundary and initial conditions with arbitrary mathematical expressions in strings. Currently two pieces of Trilinos code enable this:
      - The "runtime compiler" in Pamgen
      - The STKExprEval sub-package

    Both of these packages have hand-coded parsers. TeuchosParser could provide their parsing infrastructure, leaving these packages free to focus on the execution of the expressions themselves.
1. The Teuchos XML parser, also hand-coded, could be replaced with a call to TeuchosParser, with callbacks to build the Teuchos ParameterList.
1. The Teuchos YAML parser could be refactored to not rely on `yaml-cpp`, and use TeuchosParser instead. TPLs in general have the disadvantage of being less readily available on all platforms compared to Trilinos packages. `yaml-cpp` in particular makes excessive use of exceptions during normal operation and has been slow to release new versions.
1. Trilinos packages and applications that use Trilinos would have a much lower barrier to defining their own languages, possibly dynamically at runtime, without creating yet another hand-coded parser.

I already have prototype code ready to provide the core of this functionality, what remains to be done is some technical cleanup followed by the integrations above. I've discussed with @jgfouca and @bartlettroscoe who so far approve of this idea.

@trilinos/teuchos

**Comment by mhoemmen** [comment]
STK likely needs to work without Trilinos, or at least won't be keen on a Teuchos dependency.  I don't think we have to worry about that; the parser would have value for Trilinos alone.

**Comment by bartlettroscoe** [comment]
> STK likely needs to work without Trilinos, or at least won't be keen on a Teuchos dependency. I don't think we have to worry about that; the parser would have value for Trilinos alone.

Actually STK does appear to depend on some Trilinos packages and TeuchosCore in particular.  Check out:

```
[rabartl@crf450 Trilinos (develop)]$ find packages/stk/ -name Dependencies.cmake -exec grep -nH _PACKAGES {} \; | grep Teuchos
packages/stk/stk_classic/cmake/Dependencies.cmake:1:SET(LIB_REQUIRED_DEP_PACKAGES Shards Teuchos)
packages/stk/stk_io/cmake/Dependencies.cmake:1:SET(LIB_REQUIRED_DEP_PACKAGES TeuchosCore SEACASIoss STKMesh)

[rabartl@crf450 Trilinos (develop)]$ find packages/stk/stk_io/ -type f -exec grep -nH Teuchos_ {} \;
packages/stk/stk_io/stk_io/StkMeshIoBroker.hpp:39:#include <Teuchos_RCP.hpp>              // for RCP::RCP<T>, RCP::operator*, etc
packages/stk/stk_io/stk_io/StkMeshIoBroker.hpp:49:#include "Teuchos_RCPDecl.hpp"          // for RCP
packages/stk/stk_io/stk_io/StkMeshIoBroker.cpp:79:#include "Teuchos_RCP.hpp"              // for RCP::operator->, etc
packages/stk/stk_io/stk_io/InputFile.cpp:59:#include "Teuchos_Ptr.hpp"              // for Ptr::get
packages/stk/stk_io/stk_io/InputFile.cpp:60:#include "Teuchos_PtrDecl.hpp"          // for Ptr
packages/stk/stk_io/stk_io/InputFile.cpp:61:#include "Teuchos_RCP.hpp"              // for is_null, RCP::operator->, etc
packages/stk/stk_io/stk_io/util/Gmesh_STKmesh_Fixture.cpp:41:#include "Teuchos_RCP.hpp"              // for RCP::operator->
packages/stk/stk_io/stk_io/util/Gmesh_STKmesh_Fixture.cpp:42:#include "Teuchos_RCPDecl.hpp"          // for RCP
packages/stk/stk_io/stk_io/InputFile.hpp:37:#include <Teuchos_RCP.hpp>              // for is_null, RCP::operator->, etc
```

Therefore, I don't see why adding a TeuchosParser dependency would be so unattractive (but I could be wrong).

Also note the converse is that Trilinos packages and downstream customers that may currently depend on STK and want to remove that dependency will be able to use this new capability and more easily remove their STK dependency.

**Comment by ibaned** [comment]
> downstream customers that may currently depend on STK and want to remove that dependency will be able to use this new capability and more easily remove their STK dependency.

That is precisely the situation for an application I work on.

**Comment by mhoemmen** [comment]
> Therefore, I don't see why adding a TeuchosParser dependency would be so unattractive (but I could be wrong).

The main issue is the "STK integration dance."  STK only gets changed in STK's repo.  If it builds and passes tests, it might get merged back into Trilinos.  Furthermore, STK's repo has its own copy of Trilinos, that may only get updated if both Trilinos and STK (and friends) build and pass their tests.  Thus, changing Trilinos in a way that STK can see the changes can be hard.

**Comment by ibaned** [comment]
We'll save the STKExprEval integration for last, and only do it if there is actual interest from the STK team. None of the integrations are strictly necessary, but we should do the ones where the package maintainer sees it as a net positive change.

**Comment by jwillenbring** [comment]
@bmpersc should be aware of this conversation due to his involvement in the process of updating STK in Trilinos.

**Comment by mhoemmen** [comment]
I talked to the STK developers about this.  They plan to reply here.

**Comment by alanw0** [comment]
Hi everyone, (and thanks Mark for bringing this to the stk team's attention)

It is possible that replacing the guts of StkExprEval with a new parser could be an improvement, but StkExprEval has been relatively untouched in recent months/years (meaning stable), and I don't know if we would have a lot of motivation to put development effort into that, given other pressing priorities.

Regarding dependencies: sorry to hear @ibaned has had negative experiences with stk.
Thanks Ross for pointing out stk's dependence on Teuchos. If we replace our usage of Teuchos::RCP with std::shared_ptr in stk_io, we could drop a dependency. We've also been trying to reduce our dependence on boost lately.

**Comment by ibaned** [comment]
@alanw0 our desire to use something besides STKExprEval isn't really due to some quality issue with STKExprEval, but rather that we want to evaluate expressions in parallel on the GPU, which is something that was never part of STKExprEval's design requirements or advertised feature set.

That said, I'm happy that STK is trying to reduce its dependency on Boost, I fully support that direction.

Its completely fine if STKExprEval doesn't want to make changes, its enough that you're aware of this upcoming functionality in case it becomes relevant to new parsing needs in STK and downstream applications.

**Comment by ibaned** [comment]
With the close of #1396, TeuchosParser is now a new EX subpackage in the develop branch, in the form of these three commits:
5078b1f
63fd67d
315dff7
It is documented and functional, though nothing in Trilinos depends on it yet. Integrations to follow as time allows.

Closing this issue as we are past the proposal phase.
