### ISSUE TITLE
Tpetra Multivector documentation error:  norm1

### ISSUE THREAD

**Issue by kddevin** [trilinos/Trilinos#1372]
The Tpetra Multivector documentation describes norm1 as
"The one-norm of a vector is the sum of squares of the magnitudes of the vector's entries"
https://trilinos.org/docs/dev/packages/tpetra/doc/html/classTpetra_1_1MultiVector.html#aa1ea9cf6f0b0626ecdfc21f5dc522e55

Isn't the one-norm the sum of the absolute values (magnitudes) of the vector's entries?
http://mathworld.wolfram.com/L1-Norm.html

Indeed, the code looks as if it follows the latter. 

@trilinos/tpetra

**Comment by jhux2** [comment]
@kddevin You're right, the documentation is incorrect.

**Comment by mhoemmen** [comment]
Want to send me a pull request?

**Comment by mhoemmen** [comment]
Just pushed a fix to develop.

**Comment by kddevin** [comment]
This change just requires editing doxygen comments, right?  
Editing comments isn't worth the hassle of a pull request for either of us.
If you need me to do it, I will do so directly in develop branch.

**Comment by mhoemmen** [comment]
@kddevin Don't worry, it's done :)

**Comment by mhoemmen** [comment]
also it's possible to create a PR and edit files in the web browser :)

**Comment by kddevin** [comment]
Thanks, @mhoemmen 
Sorry for the late reply; Github isn't sending me all my memos.

**Comment by mhoemmen** [comment]
@kddevin no problem :D
