### ISSUE TITLE
Panzer test timeouts 

### ISSUE THREAD

**Issue by ikalash** [trilinos/Trilinos#1373]
I am trying to use Ross's Trilinos checkin script (https://github.com/trilinos/Trilinos/wiki/Local-development-with-remote-pull,-test,-and-push) to push to Piro.  I am unable to do so b/c the script is reporting the following test failures (timeouts) in Panzer.  I have verified that my change to Piro is not the cause of these failures.  Has anyone else seen this issue? 

  The following tests FAILED:
          60 - PanzerDiscFE_LinearObjFactory_Tests_MPI_2 (Timeout)
          92 - PanzerAdaptersSTK_assembly_engine_MPI_4 (Timeout)
         123 - PanzerAdaptersSTK_CurlLaplacianExample (Timeout)
         125 - PanzerAdaptersSTK_MixedPoissonExample (Timeout)
         132 - PanzerAdaptersSTK_main_driver_energy-ss (Timeout)
         136 - PanzerAdaptersSTK_main_driver_energy-ss-blocked-tp (Timeout)

It seems to have started yesterday afternoon - yesterday morning I was able to push to Piro using the checkin script was fine (so all panzer tests passed).

**Comment by rppawlo** [comment]
@ikalash - Have not seen this issue. There have not been any changes to panzer in the last 5 days. I will launch a test now and check the timings on my workstation.

**Comment by ikalash** [comment]
@rppawlo : right, I checked git log and did not see any panzer changes, which is what puzzles me.  If you could check this on your workstation, that would be great.  I encounter the issue on ceerws1113, the remote machine that is supposed to do the push in my checkin workflow.

**Comment by ikalash** [comment]
This has been resolved with Ross's push: https://github.com/trilinos/Trilinos/commit/f690932be91d28261cd4b8cfac758978496bf476 .  The root cause is being investigated under issue #1374.

**Comment by mhoemmen** [comment]
@tjfulle fixed #1374.  Thanks all!

**Comment by bartlettroscoe** [comment]
@ikalash, sorry I just noticed this issue.

I am going to set things up so that I get an email for any CI build failure immediately so that I can react to these failures sooner.  I will immediately disable the failing tests in pre-push testing so that they don't trip up other people like you who are just trying to do the right thing when they test and push.

We will make this better.
