### ISSUE TITLE
Failing Panzer tests in CI build starting 5/31/2017

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#1374]
**CC:** @trilinos/panzer, @trilinos/framework

**Description:**

The following Panzer tests starting timing out in the lasts CI iteration:

* PanzerAdaptersSTK_assembly_engine_MPI_4 	Failed 	10m 100ms 	Completed (Timeout)
* PanzerAdaptersSTK_CurlLaplacianExample 	Failed 	10m 80ms 	Completed (Timeout)
* PanzerAdaptersSTK_main_driver_energy-ss 	Failed 	10m 70ms 	Completed (Timeout)
* PanzerAdaptersSTK_main_driver_energy-ss-blocked-tp 	Failed 	10m 70ms 	Completed (Timeout)
* PanzerAdaptersSTK_MixedPoissonExample 	Failed 	10m 80ms 	Completed (Timeout)
* PanzerDiscFE_LinearObjFactory_Tests_MPI_2 	Failed 	10m 30ms 	Completed (Timeout)

where the CI iteration is shown here:

* http://testing.sandia.gov/cdash/index.php?project=Trilinos&parentid=2926022

The range of new commits pulled in this CI iteration was  f6353cf11175b73d88c7b9e29dddbd86165c5434..7dd3d7c3d4d0743ad835ddef089ef45ef057fd8f.

This story will investigate these new failures and fix them.

**Comment by ikalash** [comment]
For me this started yesterday afternoon.  See issue #1373.  I don't believe it has to do with my checkins to piro and tempus.  I was using your checkin script to push.

**Comment by bartlettroscoe** [comment]
Looks like the pushed commit f6353cf:

```
f6353cf "Tpetra: Thread-parallelize packCrsMatrix"
Author: Tim Fuller <tjfulle@sandia.gov>
Date:   Thu May 18 15:48:23 2017 -0600 (20 hours ago)
```

broke this.  Looks like @tjfulle was the author and @mhoemmen pushed this commit (and did not use `./checkin-test-sems.sh --do-all --push` to test and push these changes).

----

**DETAILED NOTES:**

Testing out Panzer with commit f6353cf with the CI build on crf450 ...

First, checkout f6353cf:

```
[rabartl@crf450 Trilinos (develop)]$ git checkout f6353cf
Note: checking out 'f6353cf'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at f6353cf... Tpetra: Thread-parallelize packCrsMatrix
```

How to test Panzer with the CI build on crf450:

```
$ ./checkin-test-sems.sh --enable-all-packages=off --no-enable-fwd-packages \
  --enable-packages=Panzer --local-do-all
```

That reproduced the failures:

```
  95% tests passed, 6 tests failed out of 129
  
  Label Time Summary:
  Panzer    = 2033.09 sec (129 tests)
  
  Total Test time (real) = 641.29 sec
  
  The following tests FAILED:
  	 48 - PanzerDiscFE_LinearObjFactory_Tests_MPI_2 (Timeout)
  	 80 - PanzerAdaptersSTK_assembly_engine_MPI_4 (Timeout)
  	111 - PanzerAdaptersSTK_CurlLaplacianExample (Timeout)
  	113 - PanzerAdaptersSTK_MixedPoissonExample (Timeout)
  	120 - PanzerAdaptersSTK_main_driver_energy-ss (Timeout)
  	124 - PanzerAdaptersSTK_main_driver_energy-ss-blocked-tp (Timeout)
```

My guess is that the breaking commit was:

```
commit f6353cf11175b73d88c7b9e29dddbd86165c5434
Author:     Tim Fuller <tjfulle@sandia.gov>
AuthorDate: Thu May 18 15:48:23 2017 -0600
Commit:     Mark Hoemmen <mhoemme@sandia.gov>
CommitDate: Tue May 30 19:41:55 2017 -0600

    Tpetra: Thread-parallelize packCrsMatrix
    
    @trilinos/tpetra
    
    Comments (by @tjfulle):
    
    - Tpetra_Details_packCrsMatrix.hpp implements threaded packing.
    - The Pack/Unpack test creates a much larger matrix with random column
      GIDs to give more confidence in the packing procedure.
    - Added script to run checkin-test.py with Intel 16 compilers
    
    @tjfulle wrote the initial implementation.  @mhoemme reviewed the
    code, fixed tests (especially for MPI-parallel correctness), combined
    counts and offsets into a single parallel_scan, and fixed the
    implementation for CUDA correctness.
    
    Build/Test Cases Summary
    Enabled Packages: TpetraCore
    Disabled Packages: FEI,PyTrilinos,Moertel,STK,SEACAS,ThreadPool,OptiPack,Rythmos,Intrepid,ROL,Panzer
    Enabled all Forward Packages
    0) MPI_RELEASE_DEBUG_SHARED_PT => Test case MPI_RELEASE_DEBUG_SHARED_PT was not run! => Does not affect push readiness! (-1.00 min)
    1) MPI_DEBUG_REAL => passed: passed=666,notpassed=0 (70.63 min)
    2) SERIAL_RELEASE_REAL => passed: passed=579,notpassed=0 (48.17 min)
    Other local commits for this build/test group: 28d54c4, 324678a
```

Looks like Panzer was not tested and the standard CI build was not even run before push.

**Comment by rppawlo** [comment]
I did reproduce the failure with the sems 4.9 environment on my workstation and reverting the commit fixed the issue. The funny thing is that gcc5.4 passes clean.

**Comment by tjfulle** [comment]
I'm starting to look in to this now.

**Comment by bartlettroscoe** [comment]
FYI: to push with the checkin-test-sems.sh script while these 6 Panzer tests are broken (#1374), run the checkin-test-sems.sh script with:

```
./checkin-test-sems.sh \
  --extra-configure-options="-DPanzerDiscFE_LinearObjFactory_Tests_MPI_2_DISABLE=ON -DPanzerAdaptersSTK_assembly_engine_MPI_4_DISABLE=ON -DPanzerAdaptersSTK_CurlLaplacianExample_DISABLE=ON -DPanzerAdaptersSTK_MixedPoissonExample_DISABLE=ON -DPanzerAdaptersSTK_main_driver_energy-ss_DISABLE=ON -DPanzerAdaptersSTK_main_driver_energy-ss-blocked-tp_DISABLE=ON" \
  --do-all --push
```

Unfortunately, that will not work with the [remote pull/test/push process](https://github.com/trilinos/Trilinos/wiki/Local-development-with-remote-pull,-test,-and-push) that many people are now using.  Therefore, to keep everyone working productively, we need to disable these failing tests in pre-push testing ASAP or they will block other people using the checkin-test-sems.sh script.

@tjfulle, if you can fix this ASAP, please let me know.  Otherwise, I will disable these tests in pre-push testing so this does not block other people's pushes.

**Comment by bartlettroscoe** [comment]
I pushed  	f690932 which disables these tests in pre-push testing with the checkin-test-sems.sh script only.  Therefore, they will not stop anyone else's pushes but these failures will still be seen on the post-push builds (and all other builds of Trilinos).

When these tests can be fixed for the standard CI build, the person should revert this commit in their local 'develop' branch with:

```
git revert f690932
```

before they run `./checkin-test-sems.sh --do-all --push` to test and push this.

**Comment by tjfulle** [comment]
Problem found, running the tests now.

**Comment by tjfulle** [comment]
Resolved with #1384

**Comment by bartlettroscoe** [comment]
Should not close until the CI build confirms these tests are running and passing.

Opening and putting into review.

**Comment by bartlettroscoe** [comment]
The CI build last night shown here:

* http://testing.sandia.gov/cdash/index.php?project=Trilinos&parentid=2928524

showed these Panzer tests now passing.  The fixing commits pushed by @mhoemmen:

```
$ git log --pretty=fuller --name-status  2410f36f443d ^81bc875b

commit 2410f36f443d2cb8d7a0274408febceddc4426c5
Author:     Tim Fuller <tjfulle@sandia.gov>
AuthorDate: Thu Jun 1 14:30:45 2017 -0600
Commit:     Mark Hoemmen <mhoemmen@users.noreply.github.com>
CommitDate: Thu Jun 1 16:11:33 2017 -0600

    Revert "Disable 6 failing Panzer tests in CI build (#1374 and #1304)"
    
    This reverts commit f690932be91d28261cd4b8cfac758978496bf476.
    
    Build/Test Cases Summary
    Enabled Packages: TpetraCore
    Disabled Packages: PyTrilinos,Claps,TriKota
    Enabled all Forward Packages
    0) MPI_RELEASE_DEBUG_SHARED_PT => passed: passed=1469,notpassed=0 (89.37 min)
    Other local commits for this build/test group: 8b6038c

M       cmake/std/sems/checkin-test-sems.sh

commit c8ad1d40c00922fbc208cad2932043bc2903cfbc
Author:     Tim Fuller <tjfulle@sandia.gov>
AuthorDate: Thu Jun 1 14:26:45 2017 -0600
Commit:     Mark Hoemmen <mhoemmen@users.noreply.github.com>
CommitDate: Thu Jun 1 16:11:33 2017 -0600

    Tpetra: Removing over-zealous check from Tpetra_Details_packCrsMatrix.hpp
    
    @trilinos/tpetra
    
    Pack functor in Tpetra_Details_packCrsMatrix.hpp erroneously checked that the
    number of rows to pack was equal to the number of offsets.  There are
    situations when the number of rows to pack could be less than the number of
    offsets, leading this check to throw (incorrect) errors.

M       packages/tpetra/core/src/Tpetra_Details_packCrsMatrix.hpp
```

which matches the set of new commits pulled in that CI iteration shown [here](http://testing.sandia.gov/cdash/viewNotes.php?buildid=2928525##note1).

(And this shows that the standard CI build was used to test and push enabling all downstream packages, thanks @mhoemmen!)

Closing as complete.

**Comment by maherou** [comment]
I would like to have a retrospective on this issue, to understand the root causes of the regression and time estimates in restoring a clean build.  The information will be helpful in planning for improved testing and integration processes.

**Comment by mhoemmen** [comment]
@maherou Two issues:

  1. Tim's unit test did not exercise the case of packing only a subset of local rows.  This was the case that triggered the incorrect error check.
  2. I've been turning off Panzer tests, because of TPL issues on my workstation.  The right thing to do would be to fix the TPL issues.

I don't see much else going on here.

**Comment by bartlettroscoe** [comment]
@mhoemmen, don't you have a CEE LAN machine where you can run the checkin-test-sems.sh script from?   Your push on Thursday:

```
commit 4d5abf0eb9f8803728bc6709f239092856320599
Author:     Tim Fuller <tjfulle@sandia.gov>
AuthorDate: Thu Jun 1 16:33:24 2017 -0600
Commit:     Mark Hoemmen <mhoemmen@users.noreply.github.com>
CommitDate: Thu Jun 1 23:16:43 2017 -0600

    Tpetra: Resolve incorrect comparisons of signed to unsigned int in Tpetra test
    
    @trilinos/tpetra
    
    Review: @mhoemme
    Addresses: #1380
    
    Build/Test Cases Summary
    Enabled Packages: TpetraCore
    Disabled Packages: PyTrilinos,Claps,TriKota
    Enabled all Forward Packages
    0) MPI_RELEASE_DEBUG_SHARED_PT => passed: passed=1469,notpassed=0 (14.18 min)

M       packages/tpetra/core/test/CrsMatrix/CrsMatrix_PackUnpack.cpp
```

seems to indicate that you can run the checkin-test-sems.sh script.  We set it up so that you could use the remote pull/test/push process to your CEE LAN machine.  Is that not working for you?  If not, how were you able to do this push shown above?

**Comment by tjfulle** [comment]
@bartlettroscoe, I was the author of the commit and ran the tests on my blade.

**Comment by bartlettroscoe** [comment]
@tjfulle:

> I was the author of the commit and ran the tests on my blade.

Yes, but the standard CI build was not run and Panzer was not enabled and tested when f6353cf111 got tested and pushed.  See the git fuller log message shown [above](https://github.com/trilinos/Trilinos/issues/1374#issuecomment-305332817).

**Comment by tjfulle** [comment]
@bartlettroscoe, right.  I was referring only to your last comment.  I made that push and Mark merged the PR.

**Comment by bartlettroscoe** [comment]
>  I was referring only to your last comment. I made that push and Mark merged the PR.

Wait, are people just clicking the "Merge" button on the PR Issue?

**Comment by tjfulle** [comment]
@bartlettroscoe, in the case of the commit that you quoted, yes.  That commit was merely resolving some compiler issues in an internal Tpetra test (and still invoked the checkin script against the trilinos develop branch).  For the commit that resolved this Panzer issue, Mark and I went through a lengthier review process before merging the commits.

**Comment by maherou** [comment]
Based on the first item in Mark's brief retrospective, and Item 2 in the [Triinos testing policy](https://github.com/trilinos/Trilinos/wiki/Trilinos-Testing-Policy), this missing test is a bug.

@tjfulle: If you haven't filed an issue related to this bug, please do so.
