### ISSUE TITLE
Remove Phalanx and Panzer from -Werror GCC 4.7.2 build

### ISSUE THREAD

**Issue by jwillenbring** [trilinos/Trilinos#1375]
CC: @bartlettroscoe @william76 

@rppawlo requested Phalanx and Panzer be removed from the GCC 4.7.2 Werror build. Phalanx and Panzer should be included in the 4.9 build.

**Comment by jwillenbring** [comment]
CC: @bmpersc 

@rppawlo I pushed a fix to develop to disable Panzer and Phalanx for this build. Please comment here if you continue to get failure messages (the repo for nightly builds is updated daily, so you may get one more set of failures). Note it is our intention to retire this build soon and move to a 4.9.3 Werror build. There is already an experimental version of the new build running.

**Comment by rppawlo** [comment]
Thanks @jwillenbring !
