### ISSUE TITLE
Teuchos: Teuchos::any requires too many operators

### ISSUE THREAD

**Issue by ibaned** [trilinos/Trilinos#1377]
While working on #1371, I'm having a tough time using `Teuchos::any` because:

1. To support its non-standard `operator==`, it requires the held type to always have an `operator==`
2. To support its non-standard print functionality, it requires the held type to always work with `operator<<` into a stream

This really limits what  can be put into `Teuchos::any`, and I'd like to use it in the TeuchosParser interface in a way that users can put literally any type they want into it, but thats going to be a tough sell if they need to define `operator==` and `operator<<` for all such types.

This applies to non-user types too, I'm looking at having to define `operator<<` for `std::set<char>`....

I'd really like to cut back on these requirements, but they seem to be used in `Teuchos::ParameterList` to implement its own `operator==` and `operator<<`....

@bartlettroscoe

**Comment by ibaned** [comment]
I guess this is a question about what is the best way for me to proceed. It may be to just keep defining these operators...

**Comment by ibaned** [comment]
@trilinos/teuchos

**Comment by bartlettroscoe** [comment]
Unfortunately, the usage of Teuchos::any in Teuchos::ParameterList requires operator==() and opeator<<() and these have to be virtual functions on the interface or this can't work given the nature of the Teuchos::any class.  In my opinion, every type should have operator<<() defined to aid in debugging.  And operator==() can always be implemented by comparing addresses for value types and references types.  And for a concrete type, both can be implemented non-invasively as non-member functions.

**Comment by ibaned** [comment]
Yea, I think you're right. in order to get the dispatch to work without knowing ahead of time what the type is, theres really no choice. I'll remind myself to document these requirements in the TeuchosParser documentation. Thanks @bartlettroscoe !

**Comment by ibaned** [comment]
Reopening because I think I can use C++11 to make this less painful on users

**Comment by ibaned** [comment]
Figured out a decent fix in #2196
