### ISSUE TITLE
Upgrade Trilinos for replacement of PARSE_ARGUMENTS() in TriBITS (TriBITSPub/TriBITS#181)

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#1378]
This story is to track the work to update Trilinos to use an updated version of TriBITS that removes the usage of the home-grown `PARSE_ARGUMENTS()` with the built-in CMake function `CMAKE_PARSE_ARGUMENTS()` (see TriBITSPub/TriBITS#181).

When I tried the upgrade, I got a bunch of configure warnings and errors due to stronger checking provided by `CMAKE_PARSE_ARGUMENTS()`.

**Comment by bartlettroscoe** [comment]
Using the `do-configure` script:

```
#!/bin/bash

cmake \
-DTPL_ENABLE_MPI=ON \
-DCMAKE_BUILD_TYPE=RELEASE \
-DTrilinos_ENABLE_DEBUG=ON \
-DBUILD_SHARED_LIBS=ON \
-DTrilinos_ENABLE_SECONDARY_TESTED_CODE=OFF \
-DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/MpiReleaseDebugSharedPtSettings.cmake,cmake/std/BasicCiTestingSettings.cmake \
-DTrilinos_ENABLE_DEBUG_SYMBOLS=ON \
-DTrilinos_ENABLE_EXPLICIT_INSTANTIATION=ON \
-DTrilinos_ENABLE_CONFIGURE_TIMING=ON \
-DTrilinos_ENABLE_TESTS=ON \
-DTrilinos_TRACE_ADD_TEST=ON \
-DCTEST_BUILD_FLAGS=-j16 \
-DCTEST_PARALLEL_LEVEL=16 \
"$@" \
../../../Trilinos
```

Using the Trilinos version:

```
f690932 "Disable 6 failing Panzer tests in CI build (#1374 and #1304)"
Author: Roscoe A. Bartlett <rabartl@sandia.gov>
Date:   Thu Jun 1 06:53:30 2017 -0600 (81 minutes ago)
```

Using the updated version of TriBITS:

```
6201f8f "Remove duplicate 'NAME' arg in CMAKE_PARSE_ARGUMENTS() (#181)"
Author: Roscoe A. Bartlett <rabartl@sandia.gov>
Date:   Thu Jun 1 08:51:51 2017 -0600 (14 seconds ago)
\
```

I use the standard CI build of Trilinos to test out configure of all packages with:

```
$ cd ~/Trilinos.base/BUILDS/GCC-4.9.3/MPI_RELEASE_DEBUG_SHARED_PT
$ . ~/Trilinos.base/Trilinos/cmake/load_ci_sems_dev_env.sh
$ rm -r CMake*
$ time ./do-configure -DTrilinos_TRIBITS_DIR:STRING=TriBITS/tribits -DTrilinos_ENABLE_ALL_PACKAGES=ON &> configure.out

real    0m10.080s
user    0m6.889s
sys     0m2.520s
```

This fails the configure with the configure error shown below.

----

```
[...]

Processing enabled package: RTOp (Libs, Tests, Examples)
CMake Error at cmake/TrilinosCreateClientTemplateHeaders.cmake:31 (PARSE_ARGUMENTS):
  Unknown CMake command "PARSE_ARGUMENTS".
Call Stack (most recent call first):
  packages/rtop/src/CMakeLists.txt:25 (TRILINOS_CREATE_CLIENT_TEMPLATE_HEADERS)


-- Configuring incomplete, errors occurred!
See also "/ascldap/users/rabartl/Trilinos.base/BUILDS/GCC-4.9.3/MPI_RELEASE_DEBUG_SHARED_PT/CMakeFiles/CMakeOutput.log".
See also "/ascldap/users/rabartl/Trilinos.base/BUILDS/GCC-4.9.3/MPI_RELEASE_DEBUG_SHARED_PT/CMakeFiles/CMakeError.log".
```

**Comment by bartlettroscoe** [comment]
This is fixed by the branch:

* https://github.com/bartlettroscoe/Trilinos/tree/cmake-parse-arguments-1378

I will push when I push the snapshot of TriBITS as part of TriBITSPub/TriBITS#181.

**Comment by bartlettroscoe** [comment]
Just pushed the commit ce82bb8 as part of pushing the commit 81bc875 that addresses this.  I am putting this in review to see if anything comes up due to this change.

NOTE: There was a small change to the TriBITS Dashboard Driver system that was not tested.  It is very unlikely that it will be broken but it is something that we need to watch for.

**Comment by jwillenbring** [comment]
@rabartl 
Can this issue be closed?

**Comment by bartlettroscoe** [comment]
> Can this issue be closed?

@jwillenbring, yes, I think this was done a long time ago.
