### ISSUE TITLE
Add Trilinos Developer Instructions for GitHub Issues and waffle.io

### ISSUE THREAD

**Issue by jwillenbring** [trilinos/Trilinos#138]
@maherou has asked me to write up some instructions for using GitHub Issues and waffle.io. I am going to do this on a Trilinos GitHub wiki page. I am going to use the IDEAS Jira instructions as a guide.

**Comment by jwillenbring** [comment]
@maherou 

I completed a rough draft of this page. 

https://github.com/trilinos/Trilinos/wiki/Managing-Trilinos-Project-Issues

It was not clear to me how much detail about deliverable tracking and customer-specific issue tracking was appropriate for this page. I have some thoughts to share with you on that issue if you want to pursue it. Please provide feedback on what I have (and don't have) in this page.

**Comment by maherou** [comment]
I modified the bottom of the page slightly, just enumerating the steps so that a developer can scan quickly to see what has to be done.
