### ISSUE TITLE
Tpetra: dashboard errors in Nightly track

### ISSUE THREAD

**Issue by jhux2** [trilinos/Trilinos#1380]
There are a few failures in the Tpetra [Nightly](http://testing.sandia.gov/cdash/index.php?project=Trilinos&subproject=Tpetra##Nightly).  Most appear to be related to ```CrsMatrix_PackUnpack.cpp```:

   *  http://testing.sandia.gov/cdash/viewBuildError.php?buildid=2926719
   *  http://testing.sandia.gov/cdash/viewTest.php?onlyfailed&buildid=2927333
   *  http://testing.sandia.gov/cdash/viewTest.php?onlyfailed&buildid=2927931

@trilinos/tpetra

**Comment by mhoemmen** [comment]
That's a warnings-as-errors build.  Warnings in tests are lower priority than library warnings.  We'll look at the test failures.

**Comment by mhoemmen** [comment]
@tjfulle is working on this.  He will push a fix soon.  Thanks!

**Comment by mhoemmen** [comment]
This relates to #1374.  @tjfulle will separate the fix for the run-time error, from the fix for the build warnings.  The fix for the run-time error was just pushed.

**Comment by mhoemmen** [comment]
https://github.com/trilinos/Trilinos/pull/1385 (just merged) fixes the warnings.  The two approved and merged pull requests should thus fix this entire issue.  Thanks!
