### ISSUE TITLE
Eliminate unnecessary rebuilds of Trilinos code on a reconfigure

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#1386]
**CC:** @trilinos/framework, @maherou, @rppawlo, @jhux2 

**Description:**

It has been reported by several people (and in #1241) that some (or perhaps all) reconfigurations of Trilinos will trigger the rebuild of a **lot** of object files, libraries and executables.

This story is to officially investigate this issue and try to resolve any problems that are discovered.

To help diagnose this, the Ninja build tool should be used since it can be used to trace why the build system triggers the rebuilds of each object file.

**Comment by bartlettroscoe** [comment]
Now that there is the broader SART epic:

* https://software-sandbox.sandia.gov/jira/browse/TRIL-183

that will get discussed in SART meetings, I am removing this one specific issue from the Trilinos SART board.  We really need to push on the overall problem of reducing the build and rebuild times for Trilinos at the SART level, not these lower-level issues.

**Comment by rppawlo** [comment]
@jhux2 The culprit seems to be a single file in muelu. With ETI enabled muelu autogenerates many *.cpp files in the build directory. CMake is smart enough not to overwrite the files if nothing changes so that the new timestamp does not trigger a rebuild. But the configure process *always* rerwites one single file even if nothing has changed: MueLu_DemoFactory.cpp. I don't quite understand why this file is treated differently from the other cpp files generated by muelu. Tracked it down with ninja:

```
ninja explain: output packages/muelu/src/CMakeFiles/muelu.dir/Utils/ExplicitInstantiation/MueLu_DemoFactory.cpp.o older than most recent input packages/muelu/src/Utils/ExplicitInstantiation/MueLu_DemoFactory.cpp (1496951280 vs 1496951783)
```

**Comment by bartlettroscoe** [comment]
To avoid this, MueLu needs to use the built-in CMake function configure_file() command.  That will avoid touching the generated file unless it changes (therefore not triggering an unneeded rebuild).  Let me know if MueLu developers have questions about this.

**Comment by jhux2** [comment]
> @jhux2 The culprit seems to be a single file in muelu. With ETI enabled muelu autogenerates many *.cpp files in the build directory. CMake is smart enough not to overwrite the files if nothing changes so that the new timestamp does not trigger a rebuild. But the configure process always rerwites one single file even if nothing has changed: MueLu_DemoFactory.cpp. I don't quite understand why this file is treated differently from the other cpp files generated by muelu. Tracked it down with ninja:

@rppawlo Thanks!  I will fix this.

**Comment by jhux2** [comment]
> To avoid this, MueLu needs to use the built-in CMake function configure_file() command. That will avoid touching the generated file unless it changes (therefore not triggering an unneeded rebuild). Let me know if MueLu developers have questions about this.

Thanks @bartlettroscoe.  First, though, I need to determine why this file is treated differently than any of the others.

**Comment by bartlettroscoe** [comment]
I can verify that the file:

* packages/muelu/src/Utils/ExplicitInstantiation/MueLu_DemoFactory.cpp

is getting its timestamp updated every time you configure but the contents don't change.

I did the following experiment to show that it is just this one file being the problem (at least for MueLu and upstream):

```
$ touch file_before_reconfigure.txt
$ cmake .
```

then you can sort the most recently modified files with:

```
$ find . -type f -printf '%T@ %p\n' | grep -v /CMakeFiles/ | grep -v /Makefile | grep -v \.cmake | sort -nr

1496962310.0195075690 ./README.txt
1496962310.0195075690 ./LICENSE.txt
1496962309.4175075700 ./packages/muelu/src/Utils/ExplicitInstantiation/MueLu_DemoFactory.cpp
1496962307.4495075700 ./TrilinosRepoVersion.txt
1496962304.4325075590 ./file_before_reconfigure.txt
1496961737.8275079270 ./CMakeCache.txt
...
```

See, the file MueLu_DemoFactory.cpp is listed before the file file_before_reconfigure.txt so MueLu_DemoFactory.cpp got modified after I ran the reconfigure.

This is also a trick you can use to track down which files are getting updated even if they don't change.

**Comment by jhux2** [comment]
@rppawlo I've pushed a change which fixes the issue locally for me.  Could you update and see if this addresses the rebuilds that you're seeing?

**Comment by rppawlo** [comment]
@jhux2 That fixed it. Thanks!
