### ISSUE TITLE
CrsMatrixGetDiagCopyFunctor fails on matrices with empty rows

### ISSUE THREAD

**Issue by tawiesn** [trilinos/Trilinos#1387]
CrsMatrixGetDiagCopyFunctor does not work with matrices containing empty rows.

For a special application i have a matrix with empty rows (which are fixed later). 
>         Proc Rank   Global Row  Num Entries(Index,Value)
>                 0            0           18 (0, 148.52)  (1, 1.80)  (3, 0.00)  (4, -0.25)  (5, 0.96)  (7, -0.00)  (40, 1.26)  (41, -2.08)  (43, -0.00)  (420, 3.25)  (421, -2.21)  (423, 0.00)  (596, 2.18)  (597, -0.00)  (599, 0.00)  (2100, 0.07)  (2101, 0.84)  (2103, 0.00) 
>                 0            1           18 (0, 1.80)  (1, 126.82)  (3, -0.00)  (4, 0.96)  (5, 3.06)  (7, 0.00)  (40, -2.21)  (41, 1.62)  (43, -0.00)  (420, -2.21)  (421, 3.25)  (423, 0.00)  (596, 0.00)  (597, -0.18)  (599, 0.00)  (2100, 0.96)  (2101, 1.49)  (2103, -0.00) 
>                 0            2            0
>                 0            3           18 (0, 0.00)  (1, 0.00)  (3, -0.00)  (4, 0.00)  (5, -0.00)  (7, 0.00)  (40, 0.00)  (41, 0.00)  (43, 0.00)  (420, -0.00)  (421, -0.00)  (423, 0.00)  (596, 0.00)  (597, -0.00)  (599, 0.00)  (2100, -0.00)  (2101, 0.00)  (2103, 0.00) 
>                 0            4           24 (0, -0.25)  (1, 0.96)  (3, 0.00)  (4, 162.09)  (5, -2.03)  (7, 0.00)  (40, 6.25)  (41, 1.17)  (43, 0.00)  (232, 0.41)  (233, -1.01)  (235, -0.00)  (596, 0.44)  (597, -1.08)  (599, 0.00)  (604, 0.88)  (605, 2.17)  (607, -0.00)  (736, 1.25)  (737, 1.17)  (739, -0.00)  (752, 3.47)  (753, -1.08)  (755, 0.00) 
>                 0            5           24 (0, 0.96)  (1, 3.06)  (3, -0.00)  (4, -2.03)  (5, 164.43)  (7, -0.00)  (40, 1.17)  (41, -0.51)  (43, -0.00)  (232, -1.01)  (233, 1.58)  (235, -0.00)  (596, -1.08)  (597, 1.69)  (599, 0.00)  (604, 2.17)  (605, 3.38)  (607, 0.00)  (736, 1.17)  (737, -0.10)  (739, 0.00)  (752, -1.08)  (753, -0.28)  (755, 0.00) 
>                 0            6            0
>                 0            7           24 (0, -0.00)  (1, 0.00)  (3, 0.00)  (4, 0.00)  (5, -0.00)  (7, -0.00)  (40, -0.00)  (41, 0.00)  (43, 0.00)  (232, 0.00)  (233, 0.00)  (235, 0.00)  (596, -0.00)  (597, -0.00)  (599, 0.00)  (604, 0.00)  (605, -0.00)  (607, 0.00)  (736, 0.00)  (737, -0.00)  (739, 0.00)  (752, -0.00)  (753, -0.00)  (755, 0.00) 
>                 0            8           12 (8, 107.94)  (9, 1.17)  (11, -0.00)  (16, 3.42)  (17, 0.03)  (19, -0.00)  (264, 3.85)  (265, -1.69)  (267, 0.00)  (356, 0.25)  (357, 0.60)  (359, 0.00) 
>                 0            9           12 (8, 1.17)  (9, 112.71)  (11, 0.00)  (16, 0.04)  (17, 1.53)  (19, -0.00)  (264, -1.68)  (265, 0.21)  (267, 0.00)  (356, 0.58)  (357, 1.37)  (359, -0.00) 
>                 0           10            0
> 

I'd like to extract the diagonal of that matrix. I would expect that the entries of the empty rows are set to zero by default (that's also what is happening in line 117 of Tpetra_Details_getDiagCopyWithoutOffsets_decl.hpp). However, the following code in the same file then counts the empty rows (offset == numEnt == 0) as errors.

```
      if (offset == numEnt) {
        ++errCount;
      }
      else {
        D_(lclRowInd) = curRow.value(offset);
      }
```

Any objections changing the code, e.g., to 

```
      if (offset == numEnt && numEnt > 0) {
        ++errCount;
      }
      else if (offset != numEnt) {
        D_(lclRowInd) = curRow.value(offset);
      }
```

@mhoemmen @trilinos/tpetra @trilinos/xpetra

**Comment by mhoemmen** [comment]
@tawiesn No objections.  Would you like to fix this?

**Comment by aprokop** [comment]
As a person not familiar with the code, why does extracting a matrix diagonal try to be smart? Should not simply return the diagonal with zeros, and allow the user to figure things out? The only failing mode I would expect is if something wrong with an internal matrix structure.

**Comment by tawiesn** [comment]
@mhoemmen Thanks for the comments. With your proposed solution one has to touch the Ifpack2 preconditioners, too? And one would have to change the code in Tpetra not throwing an error when there are empty rows, right? I'm not sure whether i like this solution approach and this particular "feature":
Having this "additional logic" in the diagonal extraction code is definitely a different behavior than in Epetra. Furthermore, the error is only thrown if Tpetra is compiled with HAVE_TPETRA_DEBUG (which i have enabled). So, i agree with @aprokop: Why not having a special routine in Ifpack2 which throws an error if there are missing rows (instead of using the getLocalDiag... routines. The error flag is only checked in the Tpetra debug version anyway.)?

I'm flying out next week to a conference in Europe, so i don't have time to work on that now. If we don't find the right fix for this problem, I'm tending to implement my own special routine in Xpetra which just does the proper extraction of the diagonal. The problem is that it will not use Kokkos (since Kokkos does not compile under Windows and this is for an external project who wants to run under Windows). As a consequence one has to touch the code again, once one wants to use Kokkos for routines like that.
@jhux2 @rstumin

**Comment by mhoemmen** [comment]
@aprokop wrote:
> As a person not familiar with the code, why does extracting a matrix diagonal try to be smart? 

Backwards compatibility with previous Ifpack2 behavior.  (I agree that Tpetra shouldn't be responsible for that, but it would make sense for Tpetra to tell the user that some rows don't have diagonal entries.  I agree that some missing diagonal entries, or zero diagonal entries, should not be an error condition from Tpetra's perspective.)

**Comment by mhoemmen** [comment]
@tawiesn wrote:
> Why not having a special routine in Ifpack2 which throws an error if there are missing rows (instead of using the getLocalDiag... routines. The error flag is only checked in the Tpetra debug version anyway.)?

I am indifferent :-) Please feel free to submit a pull request with the desired changes, and I'll accept it right away.

**Comment by tawiesn** [comment]
@mhoemmen This might take a while since i'm going on a trip to Europe now. Furthermore, i don't really know which Ifpack2 preconditioners rely on the error thrown by Tpetra. I can grep through Ifpack2 or maybe you can point me to the relevant preconditioners? I think i would put the "checkForMissingRows" routine directly in Ifpack2 rather than Tpetra, i guess?

**Comment by mhoemmen** [comment]
@tawiesn safe travels! :-D could you give me a sense for the priority of this work?  is this a research thing or does some application need it?

**Comment by tawiesn** [comment]
@mhoemmen We need this for a crada and sandia-internal applications.

**Comment by jhux2** [comment]
@mhoemmen wrote:
> > Furthermore, the error is only thrown if Tpetra is compiled with HAVE_TPETRA_DEBUG (which i have enabled). So, i agree with @aprokop: Why not having a special routine in Ifpack2 which throws an error if there are missing rows (instead of using the getLocalDiag... routines. The error flag is only checked in the Tpetra debug version anyway.)?

> I am indifferent :-) Please feel free to submit a pull request with the desired changes, and I'll accept it right away.

@tawiesn wrote:
> @mhoemmen This might take a while since i'm going on a trip to Europe now. Furthermore, i don't really know which Ifpack2 preconditioners rely on the error thrown by Tpetra. I can grep through Ifpack2 or maybe you can point me to the relevant preconditioners? I think i would put the "checkForMissingRows" routine directly in Ifpack2 rather than Tpetra, i guess?

My two cents.  Because the exception is thrown only in debug mode, there appears to be low risk that removing the exception will change results for an application.

Are there objections to simply removing the exception?  If we want to be extra careful, we can label this issue as "results impacting".

**Comment by mhoemmen** [comment]
@jhux2 wrote:
> Are there objections to simply removing the exception? If we want to be extra careful, we can label this issue as "results impacting".

I have no objections.  We can also document the method, explaining that it fills in zeros for missing diagonal entries.

**Comment by tawiesn** [comment]
> I have no objections. We can also document the method, explaining that it fills in zeros for missing diagonal entries.

Sounds good to me. I can do that after my return.

**Comment by tawiesn** [comment]
Fixed. See commit 1ccccecb22d3e1619da8a0513b3d0ed5f706a416
