### ISSUE TITLE
cmake rerun everytime I run make on chama

### ISSUE THREAD

**Issue by bathmatt** [trilinos/Trilinos#139]
For some reason Trilinos reconfigures every time I type make, adds about 5 minutes to the make cycle.  Doesn't look like it is a filesystem time issue..

[mbetten@chama-login8 build]$ date
Thu Feb 11 14:19:31 MST 2016
[mbetten@chama-login8 build]$ touch a
[mbetten@chama-login8 build]$ date
Thu Feb 11 14:19:33 MST 2016
[mbetten@chama-login8 build]$ ls -l a
-rw------- 1 mbetten mbetten 0 Feb 11 14:19 a
[mbetten@chama-login8 build]$ 

[mbetten@chama-login8 build]$ make VERBOSE=1
/home/mbetten/cmake-2.8.11.2-Linux-i386/bin/cmake -H/ascldap/users/mbetten/work/Drekar/Trilinos -B/ascldap/users/mbetten/work/Drekar/build --check-build-system CMakeFiles/Makefile.cmake 0
Re-run cmake: build system dependency is missing

**Comment by jwillenbring** [comment]
@bartlettroscoe or @bmpersc have you seen this kind of behavior before?

@bathmatt is it only on chama you are seeing this? Have you seen it in the past? What configuration options are you using? An initial search turned up very little. Only one real hit related to another project that uses fortran compilers optionally, but that was from a while back and it wasn't clear then why this would't have come up many times before.

**Comment by bartlettroscoe** [comment]
I think I have seen something like this before but I can’t remember the details.

My advice is to use the Ninja generator and then let Ninja tell you what it is doing (I don’t remember the name of the option but it exists).

-Ross

**Comment by bartlettroscoe** [comment]
The command is `ninja -d explain`.  To build with ninja just configure with `-G Nina`.

**Comment by bartlettroscoe** [comment]
You just can't have any Fortran code to use Ninja.  But if you don't need Fortran, just turn it off with `-DTrilinos_ENABLE_Fortran=OFF`.

**Comment by bathmatt** [comment]
@jwillenbring It is only on chama, haven't seen it before (except when I tried to use native cuda), I've attached my configure script.

@bartlettroscoe I can look at the ninja build, is the goal of using ninja to track down the problem or to fix the issue, I need fortran for part of this.

**Comment by bathmatt** [comment]
Configure script
[configure-drekar.sh.txt](https://github.com/trilinos/Trilinos/files/130994/configure-drekar.sh.txt)

**Comment by bartlettroscoe** [comment]
> @bartlettroscoe I can look at the ninja build, is the goal of using ninja to track down the problem or to fix the issue, I need fortran for part of this.

The goal is to track down the problem, not fix it.  CASL is paying Kitware to add Fortran support for Ninja but Google is not accepting the changes.  Not clear if CMake+Ninja will ever support Fortran (at least not the official version).

**Comment by bathmatt** [comment]
Configure script
[configure-drekar.sh.txt](https://github.com/trilinos/Trilinos/files/130994/configure-drekar.sh.txt)

**Comment by bathmatt** [comment]
It looks like the newest cmake fixes this issue, 3.5-rc2
