### ISSUE TITLE
MueLu export functionality broken

### ISSUE THREAD

**Issue by tawiesn** [trilinos/Trilinos#1399]
Commit 67accd45a95d5c29f0987528471de422a497a0dc breaks the export or "DataToWrite" functionality. The problem is that 
`L->AddKeepFlag(name, &*levelManagers_[data[i]]->GetFactory(name));`
assumes that there is a FactoryManager for each level. This is only guaranteed in the Easy parameter input deck but not in the Factory-based parameter input deck. (see lines 1673ff in MueLu_ParameterListInterpreter_def.hpp versus lines 360ff).
@csiefer2 Can you comment on this? I guess you added that code for exporting "pcoarsen: element to node map". Why do we need that for "A", "P"... where we don't really need a FactoryManager to access the data.

**Comment by tawiesn** [comment]
@trilinos/muelu @jhux2 @csiefer2

**Comment by jhux2** [comment]
> @csiefer2 Can you comment on this? I guess you added that code for exporting "pcoarsen: element to node map". Why do we need that for "A", "P"... where we don't really need a FactoryManager to access the data.

@tawiesn The idea is to flag data built during the Hierarchy construction that we want to write afterwards.   While some data is kept, other data isn't, e.g., Coordinates and Nullspace.

**Comment by csiefer2** [comment]
@jhux2 Bingo.

**Comment by tawiesn** [comment]
Well, the DataToWrite mechanism was only meant for "A", "P" and "R". Extending it to more general data is more complicated.

**Comment by csiefer2** [comment]
Just fixed the PLI interface for A @ level 0 for @rstumin
