### ISSUE TITLE
Isorropia: Separate experimental Tpetra-dependent code into its own subpackage

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#1406]
@trilinos/zoltan @kddevin @mmwolf 

I would like to separate Isorropia's experimental Tpetra-dependent code, which is disabled by default anyway, into a different subpackage from the rest of Isorropia.  This will reduce the number of packages whose tests unnecessarily get enabled, when I change Tpetra and run the check-in test script.  See discussion starting here: https://github.com/trilinos/Trilinos/issues/1395#issuecomment-306578732

I propose to call the new subpackages IsorropiaTpetra (for Tpetra-dependent code) and IsorropiaMain (for everything else).  If anyone objects to this plan or to the subpackage names, please let me know.  Thanks!

**Comment by mhoemmen** [comment]
This should be easy to do, because all the Tpetra-dependent code lives in `isorropia/src/tpetra` anyway.  Also, @mmwolf especially, would it be OK just to delete this code?  It's disabled by default anyway, and I suspect it hasn't been used or tested in years.

**Comment by mmwolf** [comment]
We can talk about this at tomorrow's Zoltan meeting.  I'm of the opinion that the code can be deleted, but I might be overruled.  I believe Zoltan2 is increasingly making Isorropia obsolete.  I believe at this point the only code unique to Isorropia is the coloring and matching.

**Comment by aprokop** [comment]
Adding @trilinos/muelu as we have an Isorropia interface that may be affected but this change. I don't think we (MueLu) really use it, though.

**Comment by bartlettroscoe** [comment]
Once you make this its own subpackage, you can declar it `EX` which means it will not get enabled by default, ever (which is the right thing for experimental code that is not important to be tested).  @mhoemmen, this means you would not even need to test this when you run the checkin-test-sems.sh script.

**Comment by mhoemmen** [comment]
@aprokop wrote:
> Adding @trilinos/muelu as we have an Isorropia interface that may be affected but this change. I don't think we (MueLu) really use it, though.

It should only be affected if MueLu uses Isorropia's optional, experimental Tpetra code.  That doesn't even build by default.  I'll test MueLu with Tpetra disabled before trying this out :-)

**Comment by kddevin** [comment]
@egboman

**Comment by egboman** [comment]
@mhoemmen Don' waste your time - just deprecate the experimental Tpetra code. I highly doubt anybody uses it as I'm not even sure it builds. Zoltan2 is the way forward.

**Comment by mmwolf** [comment]
Erik's comment was the consensus at the Zoltan meeting.

**Comment by mhoemmen** [comment]
@egboman wrote:
> @mhoemmen Don't waste your time - just deprecate the experimental Tpetra code. 

I can't actually deprecate it.  The issue is that the code introduces an optional Tpetra dependency.  TriBITS has no idea of a "dependency that depends on a CMake variable"; any experimental feature requires an optional dependency to be declared, and optional dependencies get enabled by default when testing.

Here are the two options:

  1. Remove or comment out the code in question
  2. Introduce subpackages as described above

Which would you prefer?  I am willing to do this, because it will save me build and test time.

**Comment by mmwolf** [comment]
In theory, we don't mind if you delete it.  Our only concern about doing this is that there might be a unknown user that might depend on this.  We think this is unlikely.

**Comment by mhoemmen** [comment]
@mmwolf wrote:
> In theory, we don't mind if you delete it. Our only concern about doing this is that there might be a unknown user that might depend on this. We think this is unlikely.

It looks like the capability _cannot_ be enabled.  See line 92 of `isorropia/src/CMakeLists.txt`.  None of that code gets enabled at all.  It's protected by the `HAVE_ISORROPIA_MACRO`, which is never defined.  That suggests we could just delete it.

I'll wait for instructions.  If you decide you want to keep the code, it likely won't take me more than a couple hours to make the subpackages.

**Comment by bartlettroscoe** [comment]
Another thing we might be able to do is to set the default for the var `Isorropia_ENABLE_Tpetra` to `OFF`.  That should stop the forward propagation of the enable of Tpetra to also enable Isorropia.   That would also stop the backward enable of Tpetra if Another thing we might be able to do is to set the default for the var `Isorropia_ENABLE_Tpetra` to `OFF`.  That should stop the forward propagation of the enable of the Tpetra libraries when Isorropia was enabled.  That would, in essence, make the dependence of Isorropia on Tpetra experimental (in that it would never be turned on by default in automated testing unless `Isorropia_ENABLE_Tpetra=ON` was explicitly set).  We could even add an offical macro for this to TriBITS that could be called in the Dependencies.cmake file for Isorropia.

If people are interested in that approach, I will make sure there is a TriBITS unit test for that use case (and if not, I will add one and then fix the code to pass it).  Then we can add this to Isorropia and then an EX subpackage for Tpetra in Isorropia would not be needed.

Let me know.

**Comment by mhoemmen** [comment]
Thanks @bartlettroscoe !  I think the better approach in this case is for the Isorropia team to decide whether they want to get rid of this code completely, or stuff it in a subpackage.

**Comment by mmwolf** [comment]
Go ahead and delete it.

**Comment by egboman** [comment]
I agree. We don't want anybody to start using this code.

**Comment by mhoemmen** [comment]
I'm running the check-in test script now.

**Comment by aprokop** [comment]
Apparently, we do have a [branch in code](https://github.com/trilinos/Trilinos/blob/develop/packages/muelu/src/Rebalancing/MueLu_IsorropiaInterface_def.hpp) for Isorropia/Tpetra version. That has to be ripped too (just to clean things up, it will never get triggered otherwise).

**Comment by aprokop** [comment]
@tawiesn You added Isorropia interface in MueLu. Do Munich folks use it (specifically, Tpetra variant) for anything?

**Comment by mhoemmen** [comment]
1 Teko and 1 Rythmos test failed; neither is related.  I'll exclude the two tests and run again.

**Comment by egboman** [comment]
Thank you, @mhoemmen You may delete the Isorropia-Tpetra git branch, too.

**Comment by mhoemmen** [comment]
I just pushed these changes (removal of Tpetra code and dependency from Isorropia) to the develop branch.

@egboman I can't actually delete the Isorropia-Tpetra git branch, but folks on the @trilinos/framework team can.  I wouldn't worry about it unless we are running out of space.

**Comment by bartlettroscoe** [comment]
@mhoemmen:

> 1 Teko and 1 Rythmos test failed; neither is related. I'll exclude the two tests and run again.

You got these failures with the standard CI build with the checkin-test-sems.sh script?  Your push commit shown below does not indicate that.

And the CI build is clean on CDash as shown at:

* https://testing.sandia.gov/cdash/index.php?project=Trilinos&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Linux-GCC-4.9.3-MPI_RELEASE_DEBUG_SHARED_PT_CI&field2=groupname&compare2=61&value2=Continuous&field3=buildstarttime&compare3=84&value3=now

Please clarify what build this was where you saw these failures.

----

Fri Jun  9 10:57:07 MDT 2017

commit b468430be1ffd81e985863b2bafd7b769f68003c
Author:     Mark Hoemmen <mhoemme@sandia.gov>
AuthorDate: Thu Jun 8 17:11:46 2017 -0600
Commit:     Mark Hoemmen <mhoemme@sandia.gov>
CommitDate: Fri Jun 9 10:56:08 2017 -0600

    Isorropia: Fix #1406 (remove experimental Tpetra interface)
    
    @trilinos/zoltan
    
    Build/Test Cases Summary
    Enabled Packages: Isorropia
    Disabled Packages: PyTrilinos,Moertel,STK,SEACAS,ThreadPool,OptiPack,TeuchosParser
    Enabled all Forward Packages
    0) MPI_RELEASE_DEBUG_SHARED_PT => passed: passed=521,notpassed=0 (25.98 min)

Commits pushed:
b468430 Isorropia: Fix #1406 (remove experimental Tpetra interface)

**Comment by tawiesn** [comment]
@aprokop I'm using the Isorropia interface a lot. But only with Epetra.

**Comment by aprokop** [comment]
@tawiesn OK, then we should get rid of the Tpetra one in MueLu.

**Comment by mhoemmen** [comment]
@bartlettroscoe Could you please clarify priority of Rythmos work over e-mail?  I have a sense of priority for Teko, but not for Rythmos.  I don't mean to criticize the package, it's just that I don't know who is using it and how much time I should spend working on it vs. all the other things.

**Comment by bartlettroscoe** [comment]
@mhoemmen:
> Could you please clarify priority of Rythmos work over e-mail? I have a sense of priority for Teko, but not for Rythmos. I don't mean to criticize the package, it's just that I don't know who is using it and how much time I should spend working on it vs. all the other things.

We can discuss over email (or better over phone) but the selection of PT packages was done by a rigorous process that was tracked in #410.  In short, Rythomos is being used by an important SNL Trilinos customer and even if it is not being actively developed, it is being actively used so we can't break it.

**Comment by mhoemmen** [comment]
@bartlettroscoe OK, good to know, thanks :-)  I will test Rythmos again with my local builds and see if those tests are still failing.  I was able to push with your (very useful! :-D ) remote check-in test script, so at least everything is OK with Rythmos there.
