### ISSUE TITLE
stk::io::StkMeshIoBroker in parallel

### ISSUE THREAD

**Issue by juan42** [trilinos/Trilinos#141]
When running a minimal example in parallel (lets assume mpirun -n 2 on a single host) for example

```
stk::io::StkMeshIoBroker broker(MPI_COMM_WORLD);
broker.property_add(Ioss::Property("DECOMPOSITION_METHOD", "rcb"));
broker.add_mesh_database(absoluteFileName, stk::io::READ_MESH);
```
The add_mesh_database routine throws
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  Expr '!(Teuchos::is_null(m_database) || !m_database->ok(true))' eval'd to true, throwing.
Error occured at: juan/src/Trilinos/packages/stk/stk_io/stk_io/InputFile.cpp:104
Error: ERROR: Could not open database '/home/juan/src/Trilinos/_build/packages/trilinoscouplings/examples/scaling/unit_cube_10int_hex.exo' of type 'exodusii'
```

This also happens in the `packages/trilinoscouplings/examples/scaling/example_Poisson_stk.cpp` example.

I can not find any further documentation or hints about this issue. Is my assumption wrong, that it should work in parallel or do i have to configure further properties?

EDIT:
I'm testing this now with parallel-netcdf (which might be the issue)

**Comment by juan42** [comment]
This issue can be marked as resolved. Building netcdf with parallel-netcdf works as expected.

```
Using decomposition method 'RCB' on 2 processors.
Rank 	 Nodes
0 	 500
1 	 500
```

**Comment by gsjaardema** [comment]
Sorry for the confusion.  I am working on providing better diagnostics which will hopefully detect and report when compiled against a serial netcdf and trying to use the auto-decomposition options.  Glad you were able to figure out the issue.
