### ISSUE TITLE
Panzer broken by cafe86a

### ISSUE THREAD

**Issue by jmgate** [trilinos/Trilinos#1411]
As of commit cafe86a by @kyungjoo-kim, @trilinos/panzer has been broken, causing failures in tests for Panzer, Drekar, and Charon:

PanzerAdaptersSTK_tPointBasisValuesEvaluator_MPI_1
PanzerAdaptersSTK_tBasisTimesVector_MPI_1
PanzerAdaptersSTK_MixedPoissonExample
PanzerAdaptersSTK_CurlLaplacianExample-ConvTest-Order-1
PanzerAdaptersSTK_CurlLaplacianExample
Drekar_standing_wave
Drekar_source_inversion
Drekar_plasma_oscillation_tetmesh
Drekar_plasma_oscillation_rtc_2D
Drekar_plasma_oscillation_rtc
Drekar_plasma_oscillation_ES_2D
Drekar_plasma_oscillation_ES
Drekar_plasma_oscillation
Drekar_mag_standing_wave
Drekar_impedance_bc
Drekar_elc_standing_wave
Drekar_drekar_mhd_plasma_blockPrec
Drekar_drekar_mhd_perry_rotor
Drekar_drekar_mhd_atmospheric_burst
Drekar_current_drive
Drekar_braginskii_zeroB
Drekar_braginskii_strongB
Charon_charon_mp_tiox.ddionlatt.symeffpg
Charon_charon_mp_tiox.ddionlatt.effpg
Charon_charon_mp_resistor_MB.SGCVFEMDD
Charon_charon_mp_resistor_MBFull.SGCVFEMDD
Charon_charon_mp_resistor_MBFull.EFFPGDD
Charon_charon_mp_resistor_MB.EFFPGDD
Charon_charon_mp_resistor_FD.SGCVFEMDD
Charon_charon_mp_resistor_FDFull.SGCVFEMDD
Charon_charon_mp_pndiode.trime.sg.inv
Charon_charon_mp_pndiode.sg.recomb
Charon_charon_mp_pndiode.sg.lin.varstep
Charon_charon_mp_pndiode.sg.lfmob
Charon_charon_mp_pndiode.sg.hocurrent
Charon_charon_mp_pndiode.sg.hfmob
Charon_charon_mp_pndiode.sg.fd
Charon_charon_mp_pndiode.sg.equ
Charon_charon_mp_pndiode.sg.current
Charon_charon_mp_pndiode.resistor
Charon_charon_mp_pndiode.effpg.hocurrent
Charon_charon_mp_pndiode.effpg.current
Charon_charon_mp_particleStrike
Charon_charon_mp_npn-hbt.sg.telt
Charon_charon_mp_gaas.harmon.mob
Charon_charon_mp.dof-scaling
Charon_charon_mp_bjt2d.sg.hocurrent
Charon_charon_mp_bjt2d.sg.current
Charon_charon_mp_2n2222.sg_cluster
Charon_charon_mp_2n2222.sg
Charon_charon_mp_2c2907.sg

You can find my config script here:  [myConfigScript.txt](https://github.com/trilinos/Trilinos/files/1065121/myConfigScript.txt).

**Comment by kyungjoo-kim** [comment]
What is your test environment ? In my workstation, I cannot reproduce the panzer failures.

**Comment by jmgate** [comment]
RHEL7, gcc-6.2.0, cmake-3.6.1, hdf5-1.10.0, netcdf-4.4.1, netcdf-cxx4-4.3.0, openmpi-2.0.0...  What else do you need?

**Comment by jmgate** [comment]
Also seeing these Charon failures on all of Charon's test beds:  RHEL6, Ubuntu16, Darwin.

**Comment by kyungjoo-kim** [comment]
I saw your configure script but I do not have the repo for charon and drekar. I first check if the checkin script can filter out this issue with sems modules.

**Comment by jmgate** [comment]
On the Charon machines, I'm seeing this configure warning:
```
CMake Warning:
  Manually-specified variables were not used by the project:
 
    HAVE_INTREPID_KOKKOSCORE
```
Might that have something to do with this, or is that totally unrelated?

**Comment by kyungjoo-kim** [comment]
I do not recorgnize the flag. I was told that charon now uses Intrepid2. Is that related with the other version of Intrepid ?

**Comment by jmgate** [comment]
Looks like most of the failures I'm seeing relate to
```
terminate called after throwing an instance of 'std::logic_error'
  what():  /build/Packages/Trilinos/packages/panzer/disc-fe/src/Panzer_BasisValues2.cpp:1174:

Throw number = 1

Throw test that evaluated to true: true

panzer::BasisValues2::applyOrientations : Not this.
[s1002179:53661] *** Process received signal ***
```
All Panzer test output can be found here:  
[myTestOutput.txt](https://github.com/trilinos/Trilinos/files/1065343/myTestOutput.txt)

**Comment by kyungjoo-kim** [comment]
Oh..... It looks like that your trilinos is not fully updated. That is temporary exception throw for debugging panzer and it is removed then pushed. I am not sure how the intermediate commit is alive in your pulling the repo.

**Comment by kyungjoo-kim** [comment]
For testing, I add one dummy commit and ran the checkin test to push. When you pull the repo, you should see this log.
```
    1 commit c8cdcb4933cb7c4b1f9440b73a55e29721a03a29
      2 Author: Kyungjoo Kim <kyukim@sandia.gov>
      3 Date:   Fri Jun 9 15:21:50 2017 -0600
      4 
      5     Panzer - dummy commit to use checkin script push #1411
      6     
      7     Build/Test Cases Summary
      8     Enabled Packages: PanzerAdaptersSTK
      9     Disabled Packages: PyTrilinos,Claps,TriKota
     10     Enabled all Forward Packages
     11     0) MPI_RELEASE_DEBUG_SHARED_PT => passed: passed=139,notpassed=0 (11.18 min)
     12 
     13 commit 3958350daababd03f37fc422bf6a546d2d5ab5f5
     14 Author: Denis Ridzal <dridzal@sandia.gov>
     15 Date:   Fri Jun 9 11:24:05 2017 -0600
     16 
     17     Making sure that the input files that we used for the paper are
     18     identical to the ones in the repo.
```

**Comment by jmgate** [comment]
> I am not sure how the intermediate commit is alive in your pulling the repo.

It's still alive because you didn't squash your commits before pushing.  If you leave commits in the history that break the code (intentionally or not) and push, `git bisect` will find the commit that breaks the code and deem it the first bad commit, even if the very next commit removes, in this case, the intentional exception throw.  Are you familiar with `git bisect` or with the process of squashing commits before pushing?

**Comment by jmgate** [comment]
This issue was due to a `git bisect` that found code that was intentionally broken.  Closing here, but the discussion continues in issue #1417.
