### ISSUE TITLE
Changes to Panzer broke Charon testing

### ISSUE THREAD

**Issue by jmgate** [trilinos/Trilinos#1417]
The following commits for high-order HGRAD, HDIV, and HCURL bases in @trilinos/intrepid2 and @trilinos/panzer have broken 30 tests in Charon:

- 36745f97b3f163853ed3e27f41f17f5885c24b30
- 8ac0c908552181662222ef321dbd5ae2bdc71445
- c66a81102131c7b19d793a9416889491dd0ad3d7
- 07368cc3661d7cbf0bb7c5646a058e17661fb010
- cafe86a17cc8bf1ebd4c1c81fd54a992a603953b
- 95d72c3748159be979f87a1609a83462465772fa

**Comment by jmgate** [comment]
The following is an email conversation between @kyungjoo-kim and myself.

> Gates, Jason Matthew
> Mon 6/12/2017 1:50 PM
> Sent Items
> Reverting just disc-fe/src/ makes it such that all the Charon tests pass, but the following tests fail for reasons I can't discern:
>   119 - PanzerAdaptersSTK_PoissonExample-ConvTest-Tri-Order-3 (Failed)
>   120 - PanzerAdaptersSTK_PoissonExample-ConvTest-Tri-Order-4 (Failed)
>   125 - PanzerAdaptersSTK_MixedPoissonExample-ConvTest-Hex-Order-2 (Failed)
>   126 - PanzerAdaptersSTK_MixedPoissonExample-ConvTest-Hex-Order-3 (Failed)
> No segfaults, no exceptions thrown -- it just looks like the test output stops, you get a TEST_# PASSED, and then the final test on convergence fails.

> Gates, Jason Matthew
> Mon 6/12/2017 12:53 PM
> Sent Items
> I'm afraid I can't get you access to Charon at this point.  I'll try your suggestion of just reverting disc-fe and get back to you.  Thanks.

> Kim, Kyungjoo (-EXP)
> Mon 6/12/2017 12:02 PM
> That would be easier for me to see the error. Since you use first order HGRAD element, there is no orientation business and typically panzer block orientation routine (not even invoke them) when it is not required. Then, the error comes from panzer modification not from Intrepid2. FAD does not affect for 1st order HGRAD element. The high order elements use some workspace and when FAD is used the workspace allocation needs some more attention. So, FAD is not a problem then.
> 
> I check the diff between the current version and the last sucessful version. I do not see any particular modification that can influence 1st order HGRAD assembly here. 
> 
> cd packages/panzer/disc-fe/src
> git diff 72d72d94aed51d153a4e19e03043fec0f951566c .  
>  
> If you don't mind, could you also check if the code passes the test after only reverting panzer/disc-fe to the 72d72d commit ?
> 
> Best
> Kyungjoo

> Gates, Jason Matthew
> Mon 6/12/2017 11:47 AM
> Sent Items
> The elements are all first-order HGRAD -- shouldn't require any orientation info.  Everything does use FAD.  We were just going through the process of open-sourcing Charon, so let me see if I can get you access to it so you can see what I'm seeing.

> Kim, Kyungjoo (-EXP)
> Mon 6/12/2017 11:32 AM
> I am not in CSRI this week and working remotely. Those changes I made are related to high order element orientations in global assembly. My modifications in Intrepid2 are high order hgrad, hcurl and hdiv (not CV elements).
> 
> Which elements are used in those failed tests ? Is any orientation related information required in those tests ? Does it use FAD (from my experience, subtle changes often trigger a problem in FAD).
> 
> Best
> Kyungjoo 
> 
> PS. I cannot see export controlled source code.

> Gates, Jason Matthew
> Mon 6/12/2017 11:07 AM
> Sent Items
> To:
> Kim, Kyungjoo (-EXP);
> Hi Kyungjoo,
>
> Do you have time to meet sometime to walk me through your changes to Panzer from last week.  If I look at Trilinos’ commit 72d72d9, all our Charon tests are passing, but if I look at 8ac0c90, we have 30 tests failing due to the nonlinear solver never converging.  I’m trying to look at the intervening commits as a whole, because it sounds like the code isn’t necessarily working at each individual commit, but I’m having a hard time understanding why this is affecting Charon.  My schedule is free until 2 PM, and from 4-6 PM, or tomorrow between 10:30 AM and 1:30 PM.  When would be a convenient time to swing by?
> 
> Many thanks,
> 
> Jason

**Comment by jmgate** [comment]
I'm afraid at this point, these changes have held up Charon for almost a week.  It doesn't look like we'll get any closer to figuring out what's wrong until @kyungjoo-kim, @eric-c-cyr, and @rppawlo are back in the office.  I have permission from Trilinos to revert these commits, such that they can be re-reverted next week when everyone's back in town and we can figure out what needs to be fixed.

Are these commits essential to any capability added to Drekar or any other application last week?  @bathmatt, do you know if these commits are necessary for you?  If I don't hear back from anyone by 1 PM Mountain Time, I'll go ahead and push the revert.

**Comment by jmgate** [comment]
> Kim, Kyungjoo (-EXP)
> Tue 6/13/2017 10:40 AM
> To:
> Gates, Jason Matthew;
> Cc:
> Pawlowski, Roger P;
> 
> Okay. Then Charon actually uses orientation information and its infrastructure. This is a more subtle problem. Dont have to worry about those test failures (I will carefully rebase my commits next time). 
> 
> Roger, 
> 
> The current panzer passes all unit tests but fails charon tests. It looks like that charon uses orientation with 1st order hgrad functions and I probably do not change all orientation related functions and panzer unit tests do not cover these changes. As I am not able to access charon, I have no idea how this problem is related with my orientation changes. In workset factory, we do now orientation setup differently (no explicit sign factors are computed in the container). Probably charon uses the sign factors. From what I see in evaluators, these sign factors can also be computed separately as dependent MD field.
> 
> 
> Best
> Kyungjoo

**Comment by jmgate** [comment]
The revert is complete and has been pushed to develop.  Moving this issue to "In Review" so we can review it when everyone's back in town next week.

**Comment by jmgate** [comment]
@eric-c-cyr, @rppawlo, @kyungjoo-kim:  I assume this issue can be closed by now, correct?  Did we open another issue to get @kyungjoo-kim's latest changes into Trilinos?

**Comment by eric-c-cyr** [comment]
No this has to be done, I will do so.
