### ISSUE TITLE
enum Epetra_DataAccess pollutes global namespace

### ISSUE THREAD

**Issue by jwuttke** [trilinos/Trilinos#1420]
a library shouldn't define global constants like "Copy" or "View".

**Comment by ibaned** [comment]
mentioning @maherou @mhoemmen @csiefer2 since there is no @trilinos/epetra

**Comment by mhoemmen** [comment]
I'm not actually responsible for Epetra.  I could fix it, but that would break backwards compatibility.  I will leave that decision to @maherou .

**Comment by maherou** [comment]
This is a known issue, but removing the names would result in backward incompatibility, which is prohibited until we change to the next major version (Trilinos 13).  I don't know a way to remove these symbols in a compliant way.
