### ISSUE TITLE
Getting spammed by configure failures for Linux-GCC-4.7.2-RELEASE_DEV_MueLu_Matlab Nightly build

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#1421]
**CC:**  @trilinos/framework, @trilinos/muelu, @maherou 

**Description**

I am getting spammed by 4 CDash emails every day for configure failures for the "Nightly" build `Linux-GCC-4.7.2-RELEASE_DEV_MueLu_Matlab`.  The most recent is:

* https://testing.sandia.gov/cdash/index.php?project=Trilinos&parentid=2946611

This fails with:

```
Processing enabled TPL: MATLAB (enabled explicitly, disable with -DTPL_ENABLE_MATLAB=OFF)
-- MATLAB_LIBRARY_NAMES='mex;mx;eng'
-- Searching for libs in MATLAB_LIBRARY_DIRS='/nfsshare/matlab/bin/glnxa64'
-- Searching for a lib in the set "mex":
--   Searching for lib 'mex' ...
-- NOTE: Did not find a lib in the lib set "mex" for the TPL 'MATLAB'!
-- ERROR: Could not find the libraries for the TPL 'MATLAB'!
-- TIP: If the TPL 'MATLAB' is on your system then you can set:
     -DMATLAB_LIBRARY_DIRS='<dir0>;<dir1>;...'
   to point to the directories where these libraries may be found.
   Or, just set:
     -DTPL_MATLAB_LIBRARIES='<path-to-libs0>;<path-to-libs1>;...'
   to point to the full paths for the libraries which will
   bypass any search for libraries and these libraries will be used without
   question in the build.  (But this will result in a build-time error
   if not all of the necessary symbols are found.)
-- ERROR: Failed finding all of the parts of TPL 'MATLAB' (see above), Aborting!

CMake Error at cmake/TPLs/FindTPLMATLAB.cmake:94 (MESSAGE):
   Could not find mex.
Call Stack (most recent call first):
  /home/nightlyTesting/Trilinos/cmake/tribits/core/package_arch/TribitsProcessEnabledTpl.cmake:89 (INCLUDE)
  /home/nightlyTesting/Trilinos/cmake/tribits/core/package_arch/TribitsGlobalMacros.cmake:1647 (TRIBITS_PROCESS_ENABLED_TPL)
  /home/nightlyTesting/Trilinos/cmake/tribits/core/package_arch/TribitsProjectImpl.cmake:202 (TRIBITS_PROCESS_ENABLED_TPLS)
  /home/nightlyTesting/Trilinos/cmake/tribits/core/package_arch/TribitsProject.cmake:93 (TRIBITS_PROJECT_IMPL)
  CMakeLists.txt:93 (TRIBITS_PROJECT)
```

This thing is a "Matlab" build.  If that does not qualify for the "Specialized" track, I don't know what does.

Can we please either fix this or demote this to "Specialized" or "Experimental"?  Letting this fail day after day is only going to teach people to filter and ignore CDash emails.

**Comment by mhoemmen** [comment]
@csiefer2

**Comment by bartlettroscoe** [comment]
Still getting spammed every day.  By now I suspect that most Trilinos developers have put in email filters to not see CDash emails.  I have put in an email filter just for this one build.  I just hope other Trilinos developers are as selective.

**Comment by bmpersc** [comment]
I have moved this build to the specialized track per the discussion during the leaders meeting.

**Comment by bartlettroscoe** [comment]
I did not get spammed with emails from this build today.  Looking at CDash today:

* https://testing.sandia.gov/cdash/index.php?project=Trilinos&display=project&date=2017-06-21

you can see that the `Linux-GCC-4.7.2-RELEASE_DEV_MueLu_Matlab` build is now appearing in the "Specialized" dashboard.  The commit that would have been assumed to make this change was e40c04a:

```
e40c04a "Move Muelu matlab testing reporting to specialized track"
Author: Brent Perschbacher <bmpersc@sandia.gov>
Date:   Tue Jun 20 17:11:02 2017 -0600 (16 hours ago)

M       cmake/ctest/drivers/dorksaber/ctest_linux_nightly_serial_release_muelu_matlab_dorksaber.cmake
```

(But it did not get liked to this GitHub issue becuase the GitHub ID #1421 was not added to the git commit log.)

Therefore, I am closing this issue.
