### ISSUE TITLE
Get all SERIAL tests in Trilinos to run as 1-process tests in MPI builds

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#1422]
**CC:** @trilinos/framework 

**Description:**

A big problem we have with SQA and test of Trilinos is that many Trilinos packages have significant numbers of tests that only run in a non-MPI serial build (e.g. Pamgan #1415 and SEACAS #1392).  That means that running the standard CI build MPI_RELEASE_DEBUG_SHARED_PT does not run any of these tests.

This story is to create a place-marker for package-specific stories to get all of their single-process tests now running only in the non-MPI serial build to also run in the MPI builds.  This way, the set of tests run in a serial build will be a strict subset of the tests run in the MPI build.  Therefore, passing the MPI build will give higher confidence that the serial build will also pass all of its tests.

**Comment by gsjaardema** [comment]
All SEACAS tests should now run in both serial and parallel build.
The only exception is for two cgns-related tests which have an issue with hdf5 freeing something after MPI_Finalize is called that are being looked at...

**Comment by gsjaardema** [comment]
Removing seacas label since this has been fixed in seacas.  Not sure that is a good practice, but it will not show up in my to-do list anymore.
