### ISSUE TITLE
KokkosKernels: Problems with Kokkos_Sparse_CrsMatrix

### ISSUE THREAD

**Issue by brian-kelley** [trilinos/Trilinos#1423]
I'm trying to use the Kokkos::CrsMatrix to write a local threaded matrix addition. I've run into a couple of issues with it (one I've figured out, and one I haven't - maybe I should make 2 issues?):

-The documentation says that the [raw host array constructor](https://trilinos.org/docs/dev/packages/kokkos/doc/html/classKokkos_1_1CrsMatrix.html#a0c2a800a9ffc10f658038bb64ac47972) expects coordinates format (rows, cols, values) but it really expects CRS (rowptrs, colinds, values). I've changed my usage code to give CRS and it now works.

-I should be able to get a [Kokkos::SparseRowView](https://trilinos.org/docs/dev/packages/kokkos/doc/html/structKokkos_1_1SparseRowView.html) of row i by calling mat.row(i). This should let me directly get at the colinds and values in row i. But, every view I get back is empty (rowView.length == 0). I tried calling .row(i) for every row:

> C has 380473 nonzeros, 10000 rows, 10000 cols.
> Number of nz in each row: 0 0 0 0 0 0 0 0 0 0 (...and so on for 10,000 zeros)

C->nnz(), C->numRows() and C->numCols() all print what I expect (the first line of output), so there are entries in there. This looks like a simple bug, but is there anything special I need to do to get these row views?

**Comment by srajama1** [comment]
The documentation is wrong. We will fix it. As the name suggests this is CRS Matrix.

Can you send me your small example or attach it to this issue ? Also I assume you are using the KokkosKernels within Trilinos as the issue you filed is in Trilinos.

**Comment by brian-kelley** [comment]
Yes, I'm using it from Tpetra (develop branch).
[Snippet from my testing code](https://gist.github.com/brian-kelley/bdda802df5aa7534755361b47ca76b3a)
[The addition code](https://gist.github.com/brian-kelley/5227402149e6c776675b8fa431f8f860)

**Comment by srajama1** [comment]
@brian-kelley : Needless to say I am not able to reproduce what you are doing as the code is partial. Do you want me to sit with you to debug and see what is happening ?

**Comment by brian-kelley** [comment]
@srajama1 I just emailed you a full patch that will let you run that test.

**Comment by brian-kelley** [comment]
The problem was with my add kernel, and everything works now.

**Comment by srajama1** [comment]
Thanks, @brian-kelley.
