### ISSUE TITLE
I know how to get rid of CUDA_LAUNCH_BLOCKING=1 requirement

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#1424]
@trilinos/tpetra @trilinos/ifpack2 @trilinos/muelu @trilinos/amesos2 @trilinos/zoltan2 @crtrott @nmhamster 

The issue is that the mirror View of a CudaUVMSpace View is just the same View.  That's not unreasonable, since it _is_ accessible from host.  However, it means that if you write to the View from (host, device), then want to access it from (device, host), you'll need to fence (otherwise you'll get "bus errors," invalid data, etc.).

I tried this and it worked.  First, if you need to create mirror Views, insist on them being host Views:
```
Kokkos::View<double*> x ("x", 100);
auto x_h = Kokkos::create_mirror_view (Kokkos::HostSpace (), x);
Kokkos::deep_copy (x_h, x);
fill_on_host (x_h);
Kokkos::deep_copy (x, x_h);
```
No need for fences in the above code.  Second, insert fences only if you plan to access the UVM Views on host without copying.

I've CC'd everyone because this is not just some Tpetra thing.  Everything downstream of Tpetra needs to pay attention to how they access Kokkos::View data, or data that ultimately live in Kokkos Views.

The best way to fix this would be to turn off Kokkos' use of UVM by default, then fix the resulting build and test errors.  However, I don't see that happening any time soon.

**Comment by kddevin** [comment]
Thanks, @mhoemmen .  I know that we originally scheduled this work for FY18, but I've heard some chatter about it here, too.  Should we look for a way to reprioritize it to this summer?  Maybe look for someone to help you do it?  What do you think?

**Comment by mhoemmen** [comment]
@kddevin Thanks for responding! :-)  I've been experimenting with this in my current project.  I don't have a sense for priority, but it's frustrating to require `CUDA_LAUNCH_BLOCKING=1`.  I think we could fix a lot of this with some small changes to Kokkos, e.g., requiring `deep_copy` from or to a UVM View to fence, and making `host_mirror_space` of `CudaUVMSpace` be `HostSpace`.  Mainly, I would like some downstream packages to know about and take some ownership for this issue.

**Comment by ibaned** [comment]
> The best way to fix this would be to turn off Kokkos' use of UVM by default, then fix the resulting build and test errors. However, I don't see that happening any time soon.

More like Trilinos' use of Kokkos' UVM capability by default. A lot of what you're proposing sounds like the same work that is required to move to using `CudaSpace` proper instead of `CudaUVMSpace`. Still, its good that you figured this out.

**Comment by mhoemmen** [comment]
@csiefer2 and @jjellio have shown that `CUDA_LAUNCH_BLOCKING=1` means something stronger than just fencing after every kernel.  That is, some code crashes with launch blocking off but fencing after every kernel, but doesn't crash with `CUDA_LAUNCH_BLOCKING=1`.  Thus, this issue is invalid.
