### ISSUE TITLE
Exodus building chaco without PIC flag

### ISSUE THREAD

**Issue by BarrySmith** [trilinos/Trilinos#1425]
It appears that Chaco is built as a static library without the PIC flag from within Exodus even if Trilinos is built with shared library support. This makes it impossible to build shared libraries that depend on all of the Trilinos libraries. @amklinv Could you please add the TAG or email for the Exodus developers so they see this issue, thanks.

https://github.com/LLNL/spack/issues/4502

     CLINKER /tmp/amklinv/spack-stage/spack-stage-WPM2JX/petsc/arch-linux2-c-opt/lib/libpetsc.so.3.07.5
/usr/bin/ld: /global/u1/a/amklinv/edison/spack/opt/spack/cray-CNL-ivybridge/gcc-6.1.0/trilinos-xsdk-0.2.0-kyct3xwwu6gnmehtbshvsgledvdnunko/lib/libchaco.a(int
erface.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/global/u1/a/amklinv/edison/spack/opt/spack/cray-CNL-ivybridge/gcc-6.1.0/trilinos-xsdk-0.2.0-kyct3xwwu6gnmehtbshvsgledvdnunko/lib/libchaco.a: could not read
symbols: Bad value
collect2: error: ld returned 1 exit status
gmake[2]: *** [/tmp/amklinv/spack-stage/spack-stage-WPM2JX/petsc/arch-linux2-c-opt/lib/libpetsc.so.3.07.5] Error 1
gmake[2]: Leaving directory `/tmp/amklinv/spack-stage/spack-stage-WPM2JX/petsc'
gmake[1]: *** [gnumake] Error 2
gmake[1]: Leaving directory `/tmp/amklinv/spack-stage/spack-stage-WPM2JX/petsc'
**************************ERROR*************************************
  Error during compile, check arch-linux2-c-opt/lib/petsc/conf/make.log
  Send it and arch-linux2-c-opt/lib/petsc/conf/configure.log to petsc-maint@mcs.anl.gov
********************************************************************

**Comment by gsjaardema** [comment]
The original thinking for building chaco static only was that it was used only internally by nem_slice and not (originally) going to be used by any applications external to SEACAS.  I have since realized that there are applications using chaco externally.

I will remove the STATIC specification from chaco so it will respect the shared/static specification of the Trilinos build.

**Comment by BarrySmith** [comment]
Thanks. Even when we don't use chaco explicitly, on certain systems like the Mac when you build a shared library it sucks in all the .a libraries on the link line (and they need to be listed because everything must be resolved when building a shared library on Macs) so if anything in the .a libraries is not PIC it errors out in building the shared library (as you can see in Alicia's build).

   Thanks for the quick response.

    Barry
