### ISSUE TITLE
Finish moving Kokkos View implementation out of the experimental namespace

### ISSUE THREAD

**Issue by dsunder** [trilinos/Trilinos#1426]
The following classes and methods have moved out of the ```Kokkos::Experimental``` namespace.

```c++
Kokkos::ViewTraits ;
Kokkos::View ;
Kokkos::Subview ;
Kokkos::is_view ;
Kokkos::subview ;
Kokkos::ALL ;
Kokkos::WithoutInitializing ;
Kokkos::AllowPadding ;
Kokkos::view_alloc ;
Kokkos::view_wrap ;
Kokkos::deep_copy ;
Kokkos::create_mirror ;
Kokkos::create_mirror_view ;
Kokkos::resize ;
Kokkos::realloc ;

Kokkos::Impl::ViewFill ;
Kokkos::Impl::ViewRemap ;
Kokkos::Impl::ViewCtorProp ;
Kokkos::Impl::is_view_label ;
Kokkos::Impl::WithoutInitializing_t ;
Kokkos::Impl::AllowPadding_t ;
Kokkos::Impl::SharedAllocationRecord ;
Kokkos::Impl::SharedAllocationTracker ;
Kokkos::Impl::ViewMapping ;
Kokkos::Impl::ViewDataAnalysis ;
```

**Comment by ibaned** [comment]
@dsunder did you figure out what was wrong with our commit to Kokkos yesterday? are these really truly available outside of `Experimental`?

**Comment by dsunder** [comment]
They are.  The problem yesterday was I didn't catch the nested namespace implementations, just the calls.

**Comment by ibaned** [comment]
Okay... this will be part of the next Kokkos promotion then.

**Comment by dsunder** [comment]
It can happen with the current Trilinos, since these things are defined in the Experimental namespace and are injected into the Kokkos namespace currently.  I'm preparing a Kokkos PR that flips the code so that they are defined in Kokkos and injected into experimental.

**Comment by ibaned** [comment]
Ah yep, I keep forgetting and you have to keep reminding me haha. I'll see if I can make a Trilinos PR in the near future.

**Comment by ibaned** [comment]
#1428 addresses all the ones I could find.

There are a few in STK, and the process for getting changes into STK is different. I'll work on that as well.

@dsunder please take a look at the branch for #1428 and let me know if I missed any.

**Comment by crtrott** [comment]
I assume we can close this by now.
