### ISSUE TITLE
./doc/build_docs for Epetra

### ISSUE THREAD

**Issue by nschloe** [trilinos/Trilinos#1431]
The most common way for a Trilinos package to build its docs is to call `./doc/build_docs`. Unfortunately, Epetra doesn't have that, meaning that the Debian package, for example, doesn't contain Epetra docs. [We've recently had a user point that out](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=864779), so I thought I mention it here, hoping for someone to put a `./doc/build_docs` in Epetra.

**Comment by mhoemmen** [comment]
@trilinos/epetra

**Comment by ibaned** [comment]
@trilinos/epetra isn't a team... @trilinos/framework someone needs to determine ownership of Epetra and create the @trilinos/epetra team...

**Comment by jwillenbring** [comment]
@nschloe what version are you looking at? I see such a file in the repo: https://github.com/trilinos/Trilinos/blob/master/packages/epetra/doc/build_docs

We rely on this for the official deoxygenated generation for the website.

**Comment by nschloe** [comment]
Thanks @jwillenbring for the reply.

I looked at the 12.10.1 release where you'll find
```
$ ls -l packages/epetra/
browser
cmake
CMakeLists.txt
Copyright.txt
example
ReleaseNotes.txt
src
test
```
 – no `docs/`. They _are_ in master however. Those files don't get filtered out in the release process, do they?

**Comment by bmpersc** [comment]
@nschloe Epetra does have an exclusion for the doc directory for the tarball release. It should still be there on the 12.10 branch, but not in the tarball(s) made from that branch.

I'm not sure what the specific reason for that exclusion was/is, but it could have been that there were documents that hadn't gone through the appropriate review process. Given that we are now releasing it as part of our repo those reviews should have already happened and would allow us to stop excluding that directory from the tarball. Is Epetra the only package this is an issue for or just the only one that has been noticed? I would suspect there are others.

**Comment by nschloe** [comment]
>  I would suspect there are others.

I guess there'll be others, but people don't really look at locally installed documentation anymore. Frankly I was surprised that the lack of Epetra (of all packages) got noticed at all. If that could be fixed for the next release, I could close the bug on the Debian side.

**Comment by mhoemmen** [comment]
I made an Epetra team: @trilinos/epetra
