### ISSUE TITLE
MueLu doesn't compile with gcc7

### ISSUE THREAD

**Issue by VictorEijkhout** [trilinos/Trilinos#1434]
```In file included from /admin/build/rpms/BUILD/trilinos-12.10.1/packages/muelu/src/Interface/../Utils/MueLu_Utilities_decl.hpp:59:0,
                 from /tmp/trilinos-build/packages/muelu/src/MueLu_Utilities.hpp:1,
                 from /admin/build/rpms/BUILD/trilinos-12.10.1/packages/muelu/src/Interface/../MueCentral/MueLu_Level.hpp:68,
                 from /admin/build/rpms/BUILD/trilinos-12.10.1/packages/muelu/src/Interface/../MueCentral/MueLu_Factory.hpp:65,
                 from /admin/build/rpms/BUILD/trilinos-12.10.1/packages/muelu/src/Interface/../MueCentral/MueLu_SingleLevelFactoryBase.hpp:51,
                 from /admin/build/rpms/BUILD/trilinos-12.10.1/packages/muelu/src/Interface/../Graph/MueLu_AmalgamationFactory_decl.hpp:53,
                 from /tmp/trilinos-build/packages/muelu/src/MueLu_AmalgamationFactory.hpp:1,
                 from /admin/build/rpms/BUILD/trilinos-12.10.1/packages/muelu/src/Interface/../MueCentral/MueLu_FactoryManager_def.hpp:54,
                 from /tmp/trilinos-build/packages/muelu/src/MueLu_FactoryManager.hpp:2,
                 from /admin/build/rpms/BUILD/trilinos-12.10.1/packages/muelu/src/Interface/../Headers/MueLu.hpp:67,
                 from /admin/build/rpms/BUILD/trilinos-12.10.1/packages/muelu/example/advanced/blockcrs/BlockCrs.cpp:60:
/admin/build/rpms/BUILD/trilinos-12.10.1/packages/xpetra/src/CrsMatrix/Xpetra_TpetraBlockCrsMatrix.hpp: In instantiation of 'void Xpetra::TpetraBlockCrsMatrix<Scalar, LocalOrdinal, GlobalOrdinal, Node>::getLocalDiagOffsets(Teuchos::ArrayRCP<long unsigned int>&) const [with Scalar = double; LocalOrdinal = int; GlobalOrdinal = long int; Node = Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial>]':
/admin/build/rpms/BUILD/trilinos-12.10.1/packages/muelu/example/advanced/blockcrs/BlockCrs.cpp:512:1:   required from here
/admin/build/rpms/BUILD/trilinos-12.10.1/packages/xpetra/src/CrsMatrix/Xpetra_TpetraBlockCrsMatrix.hpp:339:7: warning: 'void Tpetra::Experimental::BlockCrsMatrix<S, LO, GO, N>::getLocalDiagOffsets(Teuchos::ArrayRCP<long unsigned int>&) const [with Scalar = double; LO = int; GO = long int; Node = Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial>]' is deprecated [-Wdeprecated-declarations]
       mtx_->getLocalDiagOffsets(offsets);
       ^~~~
In file included from /tmp/trilinos-build/packages/tpetra/core/src/Tpetra_Experimental_BlockCrsMatrix.hpp:2:0,
                 from /admin/build/rpms/BUILD/trilinos-12.10.1/packages/xpetra/src/CrsMatrix/Xpetra_TpetraBlockCrsMatrix.hpp:53,
                 from /admin/build/rpms/BUILD/trilinos-12.10.1/packages/muelu/src/Interface/../Utils/MueLu_Utilities_decl.hpp:59,
                 from /tmp/trilinos-build/packages/muelu/src/MueLu_Utilities.hpp:1,
                 from /admin/build/rpms/BUILD/trilinos-12.10.1/packages/muelu/src/Interface/../MueCentral/MueLu_Level.hpp:68,
                 from /admin/build/rpms/BUILD/trilinos-12.10.1/packages/muelu/src/Interface/../MueCentral/MueLu_Factory.hpp:65,
                 from /admin/build/rpms/BUILD/trilinos-12.10.1/packages/muelu/src/Interface/../MueCentral/MueLu_SingleLevelFactoryBase.hpp:51,
                 from /admin/build/rpms/BUILD/trilinos-12.10.1/packages/muelu/src/Interface/../Graph/MueLu_AmalgamationFactory_decl.hpp:53,
                 from /tmp/trilinos-build/packages/muelu/src/MueLu_AmalgamationFactory.hpp:1,
                 from /admin/build/rpms/BUILD/trilinos-12.10.1/packages/muelu/src/Interface/../MueCentral/MueLu_FactoryManager_def.hpp:54,
                 from /tmp/trilinos-build/packages/muelu/src/MueLu_FactoryManager.hpp:2,
                 from /admin/build/rpms/BUILD/trilinos-12.10.1/packages/muelu/src/Interface/../Headers/MueLu.hpp:67,
                 from /admin/build/rpms/BUILD/trilinos-12.10.1/packages/muelu/example/advanced/blockcrs/BlockCrs.cpp:60:
/admin/build/rpms/BUILD/trilinos-12.10.1/packages/tpetra/core/src/Tpetra_Experimental_BlockCrsMatrix_def.hpp:1059:3: note: declared here
   BlockCrsMatrix<Scalar,LO,GO,Node>::
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://gcc.gnu.org/bugs/> for instructions.
make[2]: *** [packages/muelu/example/advanced/multiplesolve/CMakeFiles/MueLu_StandardReuse.dir/StandardReuse.cpp.o] Error 4
make[2]: Leaving directory `/tmp/trilinos-build'
make[1]: *** [packages/muelu/example/advanced/multiplesolve/CMakeFiles/MueLu_StandardReuse.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
g++: internal compiler error: Killed (program cc1plus)
```
Let me know what files I can send you.

Victor.

**Comment by ibaned** [comment]
@trilinos/muelu

**Comment by aprokop** [comment]
Oh, man, it's one of the dreaded `g++: internal compiler error:`. Not sure how to proceed.

**Comment by ibaned** [comment]
Regardless of whether the code can be modified to avoid this internal error, it is still a bug in GCC. I would do as the message says:
```
See <https://gcc.gnu.org/bugs/> for instructions.
```
Lets see if we can collect sufficient information to submit a bug report.

Note that the Albany project as been successfully compiling Trilinos with GCC 7.1 for some time now.

@VictorEijkhout  could you send us the following items as requested by the GCC instructions?
 - [ ] the exact version of GCC (please run `gcc -v` and paste the output)
 - [ ] the system type (I guess `uname -a` is a good start)
 - [ ] the options given when GCC was configured/built (part of `gcc -v`)
 - [ ] the complete command line that triggers the bug (for this one, please rerun your compilation as `make VERBOSE=1`, and then all command lines should be printed. Please include the command line prior to the error)
 - [ ] the compiler output (error messages, warnings, etc. after the relevant command line).
 - [ ] the preprocessed file (`*.i*`) that triggers the bug, generated by adding -save-temps to the complete compilation command:
       copy-paste the compile command and add `-v -save-temps` before all other flags. This should create some new files which you could please attach to this issue (you may have to append `.txt` to their names).

**Comment by nmhamster** [comment]
@mhoemmen @ibaned @crtrott @trilinos/muelu - I can report that I successfully built MueLu and its tests (as I compiled and linked) using GCC 7.1.0 on one of new testbeds this weekend. This error could be a result of the flags or architecture specific optimization being used/not being used, but there is a proof point that the compiler can generate code for MueLu.

**Comment by VictorEijkhout** [comment]
+ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/opt/apps/gcc/7.1.0/libexec/gcc/x86_64-pc-linux-gnu/7.1.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /admin/build/rpms/BUILD/gcc-7.1.0/configure --enable-libssp --enable-gold=yes --enable-ld=default --enable-plugins --enable-lto --with-tune=generic --enable-languages=c,c++,fortran --disable-multilib --prefix=/opt/apps/gcc/7.1.0 --with-gmp=/opt/apps/gcc/7.1.0 --with-mlgmp=/opt/apps/gcc/7.1.0 --with-mpfr=/opt/apps/gcc/7.1.0 --with-mpc=/opt/apps/gcc/7.1.0 --with-isl=/opt/apps/gcc/7.1.0
Thread model: posix
gcc version 7.1.0 (GCC) 
+ uname -a
Linux build.stampede2.tacc.utexas.edu 3.10.0-514.10.2.el7.x86_64 #1 SMP Fri Mar 3 00:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by VictorEijkhout** [comment]
And on a further attempt I can not get it to crash any more. 
I'll follow up if I have more information, but for now let's close this.

**Comment by ibaned** [comment]
Okay, thanks @VictorEijkhout . As you said, please reopen this if you can reproduce the crash again. It may have just run out of RAM due to other jobs at the time or something...
