### ISSUE TITLE
STK Search will Not Compile when OpenMP is enabled with GCC 7.1.0

### ISSUE THREAD

**Issue by nmhamster** [trilinos/Trilinos#1438]
@trilinos/stk - spent the weekend trying to compile Trilinos master with OpenMP enabled on one of our new testbeds. I have been using GCC 7.1.0. After a while I realized the error is that an OpenMP (`#pragma omp for`) is not used immediately prior to a loop and so this is causing some odd compiler warnings and errors to get generated. Code is on/or around line 116 of `packages/stk/stk_search/stk_search/PrototypeSearchUtilsInstrumented.hpp`

```
#ifdef _OPENMP
#pragma omp for
#endif
    const unsigned numBoxDomain = local_domain.size();
    for(unsigned iboxA = 0; iboxA < numBoxDomain; ++iboxA) {
      stk::search::add_to_box(curBox.GetBox(), local_domain[iboxA].first);
    }
  }
```

Should be made (pragma moved down) in order to get code to compile successfully:

```
    const unsigned numBoxDomain = local_domain.size();
#ifdef _OPENMP
#pragma omp for
#endif
    for(unsigned iboxA = 0; iboxA < numBoxDomain; ++iboxA) {
      stk::search::add_to_box(curBox.GetBox(), local_domain[iboxA].first);
    }
  }
```

This allows compilation to continue but the compiler eventually claims it ignores the pragma so there may be some other changes needed. Still working through everything.

**Comment by mhoemmen** [comment]
I CC'd this as Ticket # 17195 in their system.

**Comment by nmhamster** [comment]
@mhoemmen - thank you!

**Comment by khpierson** [comment]
Si, Mark,
I spot checked the code in question in the master version of stk_search this morning and this issue has already been fixed. On the sierra side, we do not have modules completely set up to run gcc 7.1 yet, so thanks for pointing out how to fix the issue. I'm not sure how quickly the changes will propagate back to Trilinos but I'm sure you already have a work-around.
-Kendall

**Comment by nmhamster** [comment]
@khpierson - thanks for the update. There are some GCC 7.1 modules rolling on out on the testbeds at the moment although I realize that we need the SQE team to pick those up for you and they have a very busy queue. I'll keep an eye out for the changes and work around them for now. Will close this issue as you guys have a fix done. Thanks for your help.

**Comment by mhoemmen** [comment]
I closed Ticket # 17195 in their system.  Thanks all!
