### ISSUE TITLE
stokhos build failing on mira (trilinos-release-12-6-branch)

### ISSUE THREAD

**Issue by sarich** [trilinos/Trilinos#144]
This build is failing on mira.alcf.anl.gov, the master branch is compiling without any problems.
I'm using gcc-4.8.4 

```
In file included from  /gpfs/mira-fs1/projects/OSCon/sarich/petsc/arch-gcc-downloads/externalpackages/git.trilinos/build/packages/stokhos/src/Ifpack2_Details_Chebyshev_MP_Vector_Serial.cpp:55:1:   required from here
/projects/OSCon/sarich/petsc/arch-gcc-downloads/include/Ifpack2_Details_Chebyshev_def.hpp:707:9: error: 'const class Tpetra::CrsGraph<int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial>, false>' has no member named 'getLocalDiagOffsets'
         A_crsMat->getCrsGraph ()->getLocalDiagOffsets (diagOffsets_);
         ^
/projects/OSCon/sarich/petsc/arch-gcc-downloads/include/Ifpack2_Details_Chebyshev_def.hpp:725:11: error: 'const class Tpetra::CrsGraph<int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial>, false>' has no member named 'getLocalDiagOffsets'
           A_crsMat->getCrsGraph ()->getLocalDiagOffsets (diagOffsets_);
```

**Comment by etphipp** [comment]
Are you sure this is the 12.6 branch?  I am looking at this file on github for the trilinos-release-12-6-branch and I am not seeing the code that is causing the problem.  Furthermore the commit that added this in the master branch (f5aaebe) didn't occur until after the branch was created (and doesn't appear to be cherry-picked onto this branch).

-Eric

**Comment by sarich** [comment]
Hi Eric,

I am sure of the intended branch (commit
0012a3e1f3dfbb9183071a8f882fc291034b27b4), it's possible something went
wrong getting it:

git clone https://github.com/trilinos/trilinos
git fetch
git rev-parse origin/trilinos-release-12-6-branch

> (0012a3e1f3dfbb9183071a8f882fc291034b27b4)


git checkout -f 0012a3e1f3dfbb9183071a8f882fc291034b27b4

Jason

**Comment by etphipp** [comment]
OK, after you do that, look at line 707 of packages/ifpack2/src/Ifpack2_Details_Chebyschev_def.hpp.  You will find the line of code there is not

A_crsMat->getCrsGraph ()->getLocalDiagOffsets (diagOffsets_);

However if you checkout the master branch, it is.

-Eric

**Comment by etphipp** [comment]
I assume this is no longer relevant, so closing.  If not, please reopen.
