### ISSUE TITLE
Zoltan: Parallel test failures on Windows (MSVC)

### ISSUE THREAD

**Issue by mplooster** [trilinos/Trilinos#1440]
@trilinos/zoltan This issue was discovered while setting up the builds for #1160.

There are at least two issues with running the Zoltan parallel tests on Windows, both of which could be solved by modifying the [ctest_zoltan.pl](https://github.com/trilinos/Trilinos/blob/0ea2ae7c0da6e531126db2b3a5dd3bf51f1ce2ce/packages/zoltan/test/ctest_zoltan.pl) script.

1. There is an issue with spaces in the MPI path, which unfortunately, Windows likes to do. It is possible to resolve this by adding quotes around the $mpiexec variable in the script.

2. The program "tee" does not exist on Windows, which the script relies upon heavily for success. However, Windows does have [a version of tee included in Powershell](https://msdn.microsoft.com/en-us/powershell/reference/5.1/microsoft.powershell.utility/tee-object). If I replace tee in the script with "Powershell.exe -Command \\"tee\\" -filepath", it seems to resolve that issue.

When I implement these two changes, the number of test failures I get on Windows goes down from 23 to 5. I haven't had a chance to dive-in to the remaining test failures, but I suspect it is an issue with the testing setup on Windows and not the Zoltan code itself.

Is this something that the Zoltan team can fix? If it is not worth the effort to change it, we can always turn off Zoltan testing for issue #1160.

**Comment by mplooster** [comment]
@trilinos/zoltan @trilinos/framework 
Any thoughts on this?

**Comment by kddevin** [comment]
@mplooster I was checking Trilinos' wiki instructions for unblocking github emails, when I found this issue report.  This one must have been blocked, as I can't find it anywhere in my mailbox.  So sorry!

Certainly, as long as your first idea works on linux/mac, we can do that.

For the second idea, is there a way for perl to determine that it is running on a windows system?  If so, we can define the tee command to be tee on unix and powershell on windows.  But I don't know how to have perl test for windows platforms; do you?

I'm including @csiefer2 as he has been trying to run Zoltan tests on windows.

**Comment by mplooster** [comment]
@kddevin [Here are some suggestions](https://stackoverflow.com/questions/334686/how-can-i-detect-the-operating-system-in-perl) that might work for determining the OS in Perl.

**Comment by kddevin** [comment]
@mplooster I pushed the change as you recommended:  check for the operating system type and set "tee" to be "Powershell..." on windows systems.  The changes work fine on linux systems.  Unfortunately, I have no way to test the windows part of the changes.   Are you able to test them in your environment?
I will close this issue for now; if the problem persists, please reopen it.  Thanks!
