### ISSUE TITLE
MueLu: Wrong instantiation of demoFactory in ETI system

### ISSUE THREAD

**Issue by lucbv** [trilinos/Trilinos#1444]
@jhux2 @aprokop 
This issue is relate to commit 8250ce5 where the demoFactory, the idea is to remove this factory class from the LO_GO_NO instantiation group to only have it in the SC_LO_GO_NO group. This should hopefully stop the rebuilding of that factory on every compilation of MueLu.

**Comment by lucbv** [comment]
The following commit bd95c74 should have fixed the ETI, I have a new factory to push in MueLu so I'll wait until then to confirm that the fix work before closing the issue

**Comment by aprokop** [comment]
OK, so that issues was not about DemoFactory being problematic for ETI, but rather that it was erroneously put in a second, wrong ETI list?

**Comment by lucbv** [comment]
Yes it was wrongly put in both ETI lists

**Comment by jhux2** [comment]
> Yes it was wrongly put in both ETI lists

@lucbv Thanks for catching this!

**Comment by lucbv** [comment]
This looks good on my latest pull/push cycle so I'll close this issue
