### ISSUE TITLE
Anasazi tests fail with checkin script and secondary-stable code enabled

### ISSUE THREAD

**Issue by kddevin** [trilinos/Trilinos#145]
@trilinos/anasazi 
I am trying to run the checkin script with secondary-stable code enabled.  The following anasazi tests fail.  All my code changes are in zoltan and zoltan2, so I don't suspect them as the problem.

595 - Anasazi_Epetra_ModalSolversTester_MPI_4 (Failed)
609 - Anasazi_Epetra_OrthoManagerGenTester_0_MPI_4 (Failed)
610 - Anasazi_Epetra_OrthoManagerGenTester_1_MPI_4 (Failed)

Error messages for 595:
ERROR:  V*Q failed.
    orthonorm error of applyHouse: 0.308401
ERROR:  applyHouse failed.
        error(VQ - house(V,H,tau): 3.5943e-16

Error messages for 609:
**\* Caught standard std::exception of type 'std::runtime_error' :
 /home/kddevin/code/Trilinos/packages/anasazi/epetra/test/OrthoManager/cxx_gentest.cpp:261:
 Throw number = 1
 Throw test that evaluated to true: err > TOL
 New X1 did not meet tolerance: orthog(X1,Y2) == 1.07011

Error messages for 610:
**\* Caught standard std::exception of type 'std::runtime_error' :
 /home/kddevin/code/Trilinos/packages/anasazi/epetra/test/OrthoManager/cxx_gentest.cpp:261:
 Throw number = 1
 Throw test that evaluated to true: err > TOL
 New X1 did not meet tolerance: orthog(X1,Y2) == 1.14092

My custom config options for these tests are listed below.  Is there some other CMake magic that I need to include (or that could be made the default in the checkin script)?  

Thanks for your help!

-D Trilinos_ENABLE_SECONDARY_STABLE_CODE=ON
-D Trilinos_ENABLE_Epetra:BOOL=ON
-D Trilinos_ENABLE_Galeri:BOOL=ON
-D Trilinos_ENABLE_Pamgen:BOOL=ON
-D Zoltan_ENABLE_EXAMPLES:BOOL=ON
-D Zoltan_ENABLE_TESTS:BOOL=ON
-D Zoltan2_ENABLE_EXAMPLES:BOOL=ON
-D Zoltan2_ENABLE_TESTS:BOOL=ON
-D Zoltan2_ENABLE_Experimental:BOOL=ON
-D Zoltan_ENABLE_Scotch:BOOL=ON
-D Zoltan2_ENABLE_Scotch:BOOL=ON
-D Scotch_LIBRARY_DIRS:FILEPATH="/home/kddevin/code/Scotch/scotch_6.0.3/32bit_openmpi/lib"
-D Scotch_INCLUDE_DIRS:FILEPATH="/home/kddevin/code/Scotch/scotch_6.0.3/32bit_openmpi//include"
-D Zoltan_ENABLE_ParMETIS:BOOL=ON
-D Zoltan2_ENABLE_ParMETIS:BOOL=ON
-D ParMETIS_LIBRARY_DIRS:FILEPATH="/home/kddevin/code/ParMETIS/ParMETIS-4.0.3/32bit_openmpi"
-D ParMETIS_INCLUDE_DIRS:FILEPATH="/home/kddevin/code/ParMETIS/ParMETIS-4.0.3/32bit_openmpi"
-D Teuchos_ENABLE_STACKTRACE=OFF
-D MPI_BIN_DIR:PATH=/usr/lib64/openmpi/bin
-D TPL_ENABLE_MPI:BOOL=ON
-D MPI_EXEC_MAX_NUMPROCS:STRING=12
-D TPL_ENABLE_Boost=OFF
-D TPL_ENABLE_Netcdf=OFF
-D TPL_ENABLE_BoostLib=OFF
-D Trilinos_ENABLE_SEACAS:BOOL=OFF
-D Trilinos_ENABLE_STK:BOOL=OFF
-D DART_TESTING_TIMEOUT:STRING=1300
-D Amesos2_ENABLE_KLU2=ON

**Comment by amklinv** [comment]
Those particular tests have been failing since Christmas, so you definitely didn't break them.  (Thanks for reporting this though!)

**Comment by kddevin** [comment]
Closing this issue, as checkin test script is superceded by ATDM testing.
