### ISSUE TITLE
Tpetra: How to control memory allocation for Tpetra objects?

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#1450]
@trilinos/tpetra 

Here is the original message posted to `trilinos-users`:
> We are working on a memory allocator for persistence storage, e.g., SSDs. This is to be used for fault-tolerance purposes. We want to integrate this malloc() into an application which uses Tpetra CrsMatrix and MultiVector objects. We need to do this for selected objects only, while remaining objects can use the standard interface.
>
> What steps will need to be taken to achieve this integration?

Could you clarify "selected objects only"?  Could this be a compile-time decision (e.g., supplying a different template parameter for the Kokkos memory space), or must it be a run-time decision?

If the former, then one could do this by adding a new Kokkos memory space that allocates on the SSD.  Kokkos already has allocators for different kinds of CUDA memory (device, UVM, host pinned) and for HBM on KNL.  It would likely not be hard to implement another one for SSDs.

**Comment by rizwanashraf** [comment]
It is supposed to be a compile-time decision. Thus, according to your suggestion, adding a new Kokkos memory space may be the way to go forward on this.

Thanks!

**Comment by mhoemmen** [comment]
@rizwanashraf wrote:
> Thus, according to your suggestion, adding a new Kokkos memory space may be the way to go forward on this.

Yes.  The main challenge after that is interoperability of these special Tpetra objects with regular non-SSD Tpetra objects, and downstream solvers (that use Tpetra objects).  Tpetra objects already have methods like `clone` and `deep_copy` for conversion between different memory spaces.  You may have to do some work there.

The "right" approach might be to use `Kokkos::DualView` with your memory space, so that it can help you manage memory transfers between SSD and DRAM.  I could talk for a while about readiness of DualView with respect to different Tpetra objects.  MultiVector is pretty much done there, but CrsGraph and CrsMatrix need some work (they currently depend on UVM for CUDA, which is currently the only tested memory space that is not `HostSpace`).

**Comment by mhoemmen** [comment]
In short, the amount of work depends on what solvers you would like to use, whether the SSD is coherent with main memory on your system, what performance you expect, and how much work you would like to do ;-) .

**Comment by mhoemmen** [comment]
I'm closing this issue.  Please feel free to reopen if the question is not answered, or to open a new issue if you have a new question.
