### ISSUE TITLE
Tpetra: Compile error when trying to communicate data from Kokkos::View using Tpetra::Distributor

### ISSUE THREAD

**Issue by dalg24** [trilinos/Trilinos#1454]
```c++
Tpetra::Distributor distributor( comm );
// assume exportProcIDs is some Kokkos::View
int const n_exports = exportProcIDs.extent( 0 );
int const n_imports = distributor.createFromSends(
    Teuchos::ArrayView<int const>( exportProcIDs.data(), n_exports) );
Kokkos::View<int *, DeviceType> exports( "exports", n_exports );
Kokkos::View<int *, DeviceType> imports( "imports", n_imports );
distributor.doPostsAndWaits( exports, 1, imports ); // <-- does not compile
```

**Comment by aprokop** [comment]
@trilinos/tpetra @trilinos/teuchos 

A bit more description of the problem: one would expect that `doPostsAndRecevies()` work with Kokkos Views. However, that is not true, and they seem to work only with `Teuchos::ArrayView`. The problem seems to be that at some point, Teuchos tries to call `isend(const Teuchos::ArrayRCP<const type>& ...)`, but instead gets `Teuchos::ArrayRCP<type>&` which causes cv-qualifier problem. 

With the following patch it seems to compile:
```diff
diff --git a/packages/teuchos/kokkoscomm/src/Kokkos_TeuchosCommAdapters.hpp b/packages/teuchos/kokkoscomm/src/Kokkos_TeuchosCommAdapters.hpp
index 803577d..7e3b667 100644
--- a/packages/teuchos/kokkoscomm/src/Kokkos_TeuchosCommAdapters.hpp
+++ b/packages/teuchos/kokkoscomm/src/Kokkos_TeuchosCommAdapters.hpp
@@ -104,7 +104,8 @@ isend (const ViewType& sendBuffer,
        const Comm<Ordinal>& comm)
 {
   using Kokkos::Compat::persistingView;
-  return isend(persistingView(sendBuffer), destRank, tag, comm);
+  typename ViewType::const_type sendBuffer_const = sendBuffer;
+  return isend(persistingView(sendBuffer_const), destRank, tag, comm);
 }
 
 //! Variant of ireceive that takes a tag argument (and restores the correct order of arguments).
```

**Comment by aprokop** [comment]
One more comment: changing
```diff
- Kokkos::View<int *, DeviceType> exports( "exports", n_exports );
+ Kokkos::View<const int *, DeviceType> exports( "exports", n_exports );
```
does not solve the issue, as it breaks in a different way (I think after `isend`).

However, running with `Teuchos::ArrayView<const int> exports;` works. So there may be multiple things wrong here.

**Comment by mhoemmen** [comment]
@dalg24 Could you clarify what it is you want to do?  That could help us find a work-around for you until we can fix this.  Thanks!

**Comment by dalg24** [comment]
I am trying to use `Tpetra::Distributor` to communicate the data from and to a `Kokkos::View` on the device.

My current workaround is to create mirror views on the host, copy the data, and build a `Teuchos::ArrayView`.
```c++
auto exports_host = Kokkos::create_mirror_view( exports );
Kokkos::deep_copy( exports_host, exports );
auto imports_host = Kokkos::create_mirror_view( imports );
Teuchos::ArrayView<int const> exports_cv( exports_host.data(), n_exports );
Teuchos::ArrayView<int> imports_v( imports_host.data(), n_imports );

distributor.doPostsAndWaits( exports_cv, 1, imports_v );

Kokkos::deep_copy( imports, imports_host );
```

**Comment by mhoemmen** [comment]
@dalg24 wrote:
> I am trying to use Tpetra::Distributor to communicate the data from and to a Kokkos::View on the device.

Why not just use a Tpetra::Vector or Tpetra::MultiVector, with Tpetra::Import or Tpetra::Export?  Why do you need to work with Distributor directly?

**Comment by aprokop** [comment]
@mhoemmen Because the data is a custom serialized data and Tpetra::MultiVector sounds like an overkill.

**Comment by mhoemmen** [comment]
@aprokop wrote:
> Because the data is a custom serialized data and Tpetra::MultiVector sounds like an overkill.

That's fair.  It looks like a harmless change to me.  On the other hand, we _do_ have an `Teuchos::isend` overloaded for `Kokkos::View`:

https://github.com/trilinos/Trilinos/blob/develop/packages/teuchos/kokkoscomm/src/Kokkos_TeuchosCommAdapters.hpp

though it looks like the current implementation has the same cv-qualifier issue as the code your patch fixes.  Perhaps we should fix the `isend` overload for `View` instead, and use that in `Distributor`?

**Comment by mhoemmen** [comment]
Let's do test-driven development.  @dalg24 or @aprokop , could you please send me a stand-alone unit test?  Once I get that, I'll implement the above proposed fix.  Thanks! :-D

**Comment by mhoemmen** [comment]
Also, @dalg24 , it would help for planning purposes to know the customer / application.  If you would prefer to send that over e-mail, please feel free.  Thanks!

**Comment by dalg24** [comment]
```c++
    Teuchos::RCP<const Teuchos::Comm<int>> comm =
        Teuchos::DefaultComm<int>::getComm();
    int const comm_rank = comm->getRank();
    int const comm_size = comm->getSize();

    Tpetra::Distributor distributor( comm );
    int const n = 3 * comm_size;
    Kokkos::View<int *, DeviceType> proc_ids( "proc_ids", n );
    int const n_exports = proc_ids.extent( 0 );
    using ExecutionSpace = typename DeviceType::execution_space;
    Kokkos::parallel_for(
        "fill_proc_ids", Kokkos::RangePolicy<ExecutionSpace>( 0, n ),
        KOKKOS_LAMBDA( int i ) { proc_ids( i ) = i % comm_size; } );
    Kokkos::fence();
    auto proc_ids_host = Kokkos::create_mirror_view( proc_ids );
    Kokkos::deep_copy( proc_ids_host, proc_ids );
    int const n_imports = distributor.createFromSends(
        Teuchos::ArrayView<int const>( proc_ids_host.data(), n_exports ) );
    Kokkos::View<int *, DeviceType> exports( "exports", n_exports );
    Kokkos::parallel_for(
        "fill_exports", Kokkos::RangePolicy<ExecutionSpace>( 0, n_exports ),
        KOKKOS_LAMBDA( int i ) { exports( i ) = comm_rank; } );
    Kokkos::fence();

    Kokkos::View<int *, DeviceType> imports( "imports", n_imports );
#define WORKAROUND 1
#ifndef WORKAROUND
    distributor.doPostsAndWaits( exports, 1, imports );
    auto imports_host = Kokkos::create_mirror_view( imports );
    Kokkos::deep_copy( imports_host, imports );
#else
    auto exports_host = Kokkos::create_mirror_view( exports );
    Kokkos::deep_copy( exports_host, exports );
    auto imports_host = Kokkos::create_mirror_view( imports );
    distributor.doPostsAndWaits(
        Teuchos::ArrayView<int const>( exports_host.data(), n_exports ), 1,
        Teuchos::ArrayView<int>( imports_host.data(), n_imports ) );
    Kokkos::deep_copy( imports, imports_host );
#endif

    for ( int i = 0; i < n_imports; ++i )
        TEUCHOS_ASSERT_EQUALITY( imports_host( i ), i / 3 );
}
```

This is for [DataTransferKit](https://github.com/ORNL-CEES/DataTransferKit).  I am implementing a distributed search tree.  I intended to use `Tetra::distributor` to forward queries to processes that own objects occupying some space or close to some point in space.

**Comment by mhoemmen** [comment]
@dalg24 Thanks!  If @aprokop feels like putting that in, he's welcome, otherwise I'll work on it (I may not get to it today).

**Comment by mhoemmen** [comment]
@dalg24 I've got a fix ready; just need to run the check-in tests.  btw, how many MPI processes does the test need?  I ran it with 4 processes, and the test passed (after I applied the fix).

**Comment by dalg24** [comment]
@aprokop @mhoemmen 
Your patch did the trick.  Thank you!

**Comment by mhoemmen** [comment]
@dalg24 Thanks for testing and for contributing the unit test!

**Comment by mhoemmen** [comment]
@aprokop Thanks for the proposed fix!
