### ISSUE TITLE
Remove yaml-cpp warnings

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#1458]
**CC:** @trilinos/framework, @trilinos/teuchos 

**Description:**

The yaml-cpp headers generate some warnings when building with the standard CI build of Trilinos.  A current version of Trilinos (as of yesterday) with the SEMS GCC 4.8.4 shows 33 warnings total with 11 unique warnings as shown by:

```
$ grep warning: MPI_RELEASE_DEBUG_SHARED_PT/make.out | grep include/yaml-cpp | wc -l
33

$ grep warning: MPI_RELEASE_DEBUG_SHARED_PT/make.out | $ grep include/yaml-cpp | sort | uniq | wc -l
11
```

These unique warnings are:

```
/projects/sems/install/rhel6-x86_64/sems/tpl/yaml_cpp/0.5.3/gcc/4.8.4/base/include/yaml-cpp/node/detail/node.h:110:60: warning: declaration of ‘node’ shadows a member of 'this' [-W
/projects/sems/install/rhel6-x86_64/sems/tpl/yaml_cpp/0.5.3/gcc/4.8.4/base/include/yaml-cpp/node/detail/node.h:68:35: warning: declaration of ‘mark’ shadows a member of 'this' [-Ws
/projects/sems/install/rhel6-x86_64/sems/tpl/yaml_cpp/0.5.3/gcc/4.8.4/base/include/yaml-cpp/node/detail/node.h:72:39: warning: declaration of ‘type’ shadows a member of 'this' [-Ws
/projects/sems/install/rhel6-x86_64/sems/tpl/yaml_cpp/0.5.3/gcc/4.8.4/base/include/yaml-cpp/node/detail/node.h:81:46: warning: declaration of ‘scalar’ shadows a member of 'this' [-
/projects/sems/install/rhel6-x86_64/sems/tpl/yaml_cpp/0.5.3/gcc/4.8.4/base/include/yaml-cpp/node/detail/node.h:85:40: warning: declaration of ‘tag’ shadows a member of 'this' [-Wsh
/projects/sems/install/rhel6-x86_64/sems/tpl/yaml_cpp/0.5.3/gcc/4.8.4/base/include/yaml-cpp/node/detail/node.h:91:45: warning: declaration of ‘style’ shadows a member of 'this' [-W
/projects/sems/install/rhel6-x86_64/sems/tpl/yaml_cpp/0.5.3/gcc/4.8.4/base/include/yaml-cpp/node/detail/node_ref.h:32:35: warning: declaration of ‘mark’ shadows a member of 'this' 
/projects/sems/install/rhel6-x86_64/sems/tpl/yaml_cpp/0.5.3/gcc/4.8.4/base/include/yaml-cpp/node/detail/node_ref.h:33:39: warning: declaration of ‘type’ shadows a member of 'this' 
/projects/sems/install/rhel6-x86_64/sems/tpl/yaml_cpp/0.5.3/gcc/4.8.4/base/include/yaml-cpp/node/detail/node_ref.h:34:40: warning: declaration of ‘tag’ shadows a member of 'this' [
/projects/sems/install/rhel6-x86_64/sems/tpl/yaml_cpp/0.5.3/gcc/4.8.4/base/include/yaml-cpp/node/detail/node_ref.h:36:46: warning: declaration of ‘scalar’ shadows a member of 'this
/projects/sems/install/rhel6-x86_64/sems/tpl/yaml_cpp/0.5.3/gcc/4.8.4/base/include/yaml-cpp/node/detail/node_ref.h:37:45: warning: declaration of ‘style’ shadows a member of 'this'
```

This story is to make these warnings go away.

**Comment by bartlettroscoe** [comment]
Since we can't fix yaml-cpp, we need to just disable these warnings.  To achieve this, I will try adding `-DTrilinos_TPL_SYSTEM_INCLUDE_DIRS=TRUE` for the CI build of Trilinos as per:

* https://tribits.org/doc/TribitsBuildReference.html#disable-warnings-from-tpl-header-files

I am hesitant to make this the default for Trilinos because it breaks builds with other gfortran compilers with code that use module files and includes.

**Comment by brian-kelley** [comment]
@bartlettroscoe Another solution (ugly, but with no side effects) could be:
~~~~
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wshadow"
#include "yaml-cpp.h"
#pragma GCC diagnostic pop
~~~~

**Comment by bartlettroscoe** [comment]
> Another solution (ugly, but with no side effects) could be:
>
> ```
> #pragma GCC diagnostic push
> #pragma GCC diagnostic ignored "-Wshadow"
> #include "yaml-cpp.h"
> #pragma GCC diagnostic pop
> ```

Every time I tried that with GCC it never works.

If it were not for the legacy gfortran issue, I would say that every TriBITS project should use `-D<Project>_TPL_SYSTEM_INCLUDE_DIRS=TRUE`

**Comment by bartlettroscoe** [comment]
I pushed the commit f389f27 to github 'develop'.  I verified that none of these YAML warnings appeared in the checkin-test-sems.sh build of all of the PT packages in Trilinos:

```
$ grep warning: MPI_RELEASE_DEBUG_SHARED_PT/make.out | grep include/yaml-cpp
[empty]
```

However, the post-push CI build is still showing these warnings:

* https://testing.sandia.gov/cdash/viewBuildError.php?type=1&buildid=2972831

We even see the include dir for yaml-cpp being included with:

```
"-isystem" "/projects/sems/install/rhel6-x86_64/sems/tpl/yaml_cpp/0.5.3/gcc/4.8.4/base/include"
```

at:

* https://testing.sandia.gov/cdash/viewBuildError.php?type=1&buildid=2972831


I wonder if this has something to do with the launcher script that gets used when building with CMake?  Because when you do the build locally, you don't see this.

**Comment by ibaned** [comment]
Just FYI, I tried to actually fix this in `yaml-cpp` as jbeder/yaml-cpp#486 and jbeder/yaml-cpp#490. One was accepted and one was rejected because these warnings only show up with compilers that are old by the standards of most people outside Sandia.

I'm working on using TeuchosParser to replace `yaml-cpp`, which will also "fix" this.

**Comment by bartlettroscoe** [comment]
Since I have not been able to make these warnings go away, I took this out of "in progress" and put this into the backlog again.

I guess the good news is that these warnings should be gone for developers when running raw `make` so that is better than nothing.

I need to get with Kitware to figure out why `-isystem` does not suppress warnings when using the "launchers" compile wrappers that are used to collect build results to submit to CDash.  That also foiled my attempt  to make the OpenMPI 1.6.5 warnings go away with GCC 4.9.3 (see #1341).

**Comment by bartlettroscoe** [comment]
@ibaned,

Now that TeuchosParser is implementing YAML parsing for the Teuchos PL YAML parsing code, does the standard Trilinos CI build still need to be enabling the yaml-cpp TPL and SEMS module for this?  If not, then we should turn this off.

**Comment by ibaned** [comment]
@bartlettroscoe  Effectively `yaml-cpp` is not needed by Trilinos anymore, so yes we can move forward with turning it off in CI builds.

**Comment by bartlettroscoe** [comment]
Okay, I will try to disable the yaml-cpp TPL and see if we get all of the same tests passing.

**Comment by bartlettroscoe** [comment]
Note that since the switch over to using TeuchosParser for YAML parsing, we are no longer seeing warnings from yaml-cpp headers we once saw.  You can see this, for example, in:

* https://testing.sandia.gov/cdash/viewBuildError.php?type=1&buildid=3156098

that no warnings are coming from yaml-cpp header files.

**Comment by bartlettroscoe** [comment]
Does TeuchosCore need even an optional dependency on yaml-cpp at this point?  Can we take "yaml-cpp" out of the file teuchos/cmake/Dependencies.cmake?

**Comment by ibaned** [comment]
> Can we take "yaml-cpp" out of the file teuchos/cmake/Dependencies.cmake?

Yes, I think we can.

**Comment by bartlettroscoe** [comment]
I pushed the commits e0ac153 and 0b7dc2c which have completely removed the yaml-cpp from the standard SEMS env and standard CI build and from the dependencies of Teuchos subpackages.

You can see yaml-cpp **not** being enabled, for example, in the CI build this morning at:

* https://testing.sandia.gov/cdash/viewConfigure.php?buildid=3158455

which shows:

```
Final set of non-enabled TPLs:  MKL yaml-cpp [...] 91
``` 

and no other mention of 'yaml-cpp' in the configure output.

And as a result, we are not seeing any yaml-cpp warnings for Teuchos as shown, for example, in the CI build this morning at:

* https://testing.sandia.gov/cdash/viewBuildError.php?type=1&buildid=3158455

(the only warning shown there is, ironically, is an unused var warning in the file teuchos/parameterlist/test/yaml/YamlParameterList.cpp.)

Closing as complete.

Thanks @ibaned for removing our need for yaml-cpp!
