### ISSUE TITLE
[Tempus] IntegratorBasic::setInitialState to take RCP to const VectorBase

### ISSUE THREAD

**Issue by bartgol** [trilinos/Trilinos#1460]
I am  using Tempus as time integrator, and I have to go through a few loops to set the initial condition. In particular, since my initial condition is a const vector, I find myself choosing between making a copy of it (waste) or using a const_cast (which I try to avoid like the plague).

I was wondering if it was possible to have these method to take RCP's to const VectorBase vectores. After all, it appears to me that xdot0 and xdotdot0 are already copied (if not null). I would expect that x0 would also be copied, and that all the inputs were pointers to const objects, since I assume Tempus is not going to modify the initial condition(s) vectors...

**Comment by bartgol** [comment]
@ikalash I can't add labels cause I'm not part of the organization, so I'm tagging you (since I know you work on Tempus), and you can then add the proper labels so that this gets to the attention of the right people. Thanks!

**Comment by mhoemmen** [comment]
@bartgol I made a tempus team and added @ikalash to it.  I can't make @ikalash maintainer though; @trilinos/framework may have to do that.

**Comment by bartlettroscoe** [comment]
@bartgol, I just saw this (I did not get an email notification).

Can you be more specific?  I need to see if this is an issue with Thyra software or if it is specific to Tempus.

**Comment by ccober6** [comment]
This was fixed by @etphipp in 2b6d4d0c.
