### ISSUE TITLE
Determine if Thyra is free of needing to keep C++98 support

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#1465]
**CC:** @trilinos/thyra, @trilinos/framework 

**Description:**

While working #1442 as part of #330, I realized that the only automated C++98 build for Trilinos is the build `Linux-GCC-4.4.7-MPI_OPT_DEV_XYCE` most recently shown at:

* https://testing.sandia.gov/cdash/index.php?project=Trilinos&parentid=2937894

That build actually only enables a few packages set by:

```
SET( Trilinos_EXCLUDE_PACKAGES ${EXTRA_EXCLUDE_PACKAGES} PyTrilinos Kokkos Gtest ThreadPool RTOp Shards Thyra Xpetra Galeri Pamgen ML SEACAS Anasazi Stratimikos FEI Intrepid STK MueLu)

SET(Trilinos_PACKAGES NOX EpetraExt TrilinosCouplings Ifpack Isorropia AztecOO Belos Teuchos Amesos Sacado Zoltan Epetra Triutils)

SET( EXTRA_CONFIGURE_OPTIONS
  "-DEpetraExt_BUILD_BTF=ON"
  "-DTeuchos_ENABLE_COMPLEX=ON"
  "-DNOX_ENABLE_LOCA=ON"
  "-DTPL_ENABLE_ParMETIS:BOOL=OFF"
  "-DTrilinos_ENABLE_ALL_OPTIONAL_PACKAGES=OFF"
  "-DTrilinos_ENABLE_ALL_PACKAGES:BOOL=OFF"
  )
```

In this build, they actually disable all optional packages.  Since Thyra is only an optional package in all of those listed packages and is explicitly excluded from the top level, that seems to show that not even a single Thyra library is being enabled and built for the Xyce build of Trilinos.

And that is consistent with the response given for Xyce in [TRIL-95](https://software-sandbox.sandia.gov/jira/browse/TRIL-95) which listed the enabled packages for Xyce as:

* Final set of enabled packages: Kokkos Teuchos Sacado Epetra Zoltan Triutils Tpetra EpetraExt Isorropia AztecOO Amesos Ifpack ML Belos ShyLU Amesos2 NOX TrilinosCouplings 18

* Final set of enabled SE packages: KokkosCore KokkosContainers KokkosAlgorithms Kokkos TeuchosCore TeuchosParameterList TeuchosComm TeuchosNumerics TeuchosRemainder TeuchosKokkosCompat TeuchosKokkosComm Teuchos Sacado Epetra Zoltan Triutils TpetraClassic TpetraKernels TpetraTSQR TpetraCore Tpetra EpetraExt Isorropia AztecOO Amesos Ifpack ML Belos ShyLUCore ShyLU Amesos2 NOX TrilinosCouplings 33

If this is true, I think this means that Thyra is free to use C++11 features in the libraries and the tests.

**Comment by bartlettroscoe** [comment]
I added this to the SART board to bring this up at the next SART meeting.  Note that if Thyra is free of C++98 support then so is Stratimikos and every piece of downstream code from Thyra.

If this is indeed true, then it makes dropping C++98 support from the rest of Trilinos (i.e. #1390) a little less urgent, at least from the ATDM perspective.

**Comment by bartlettroscoe** [comment]
The answer is no and has been so since Trilinos required C++11 more than a year ago :-)

**Comment by mhoemmen** [comment]
@bartlettroscoe You mean that "Thyra can use C++11 features" right?

**Comment by bartlettroscoe** [comment]
> You mean that "Thyra can use C++11 features" right?

@mhoemmen, I guess that is what I was trying to say with this issue.

Actually, I am looking forward to using C++14 features in the Kokkos-aware RTOp refactor.

**Comment by mhoemmen** [comment]
@bartlettroscoe wrote:
> Actually, I am looking forward to using C++14 features in the Kokkos-aware RTOp refactor.

We all are :-) It's worth it just for `std::make_unique`.
