### ISSUE TITLE
Inconsistent gcc version load by configure and load_sems_dev_env.sh

### ISSUE THREAD

**Issue by lucbv** [trilinos/Trilinos#1467]
@bartlettroscoe 
I am having some issues this morning with the different compiler versions loaded by various trilinos script.
When I load the sems-environment with:
```source cmake/load_sems_dev_env.sh```
it sets the compiler to gcc-4.8.4
However after I run my configure script, in which I do not set the compiler since I rely on cmake to detect it, here is what my environment looks like:
```
Currently Loaded Modulefiles:
  1) sems-env                       4) sems-git/2.10.1                7) sems-boost/1.63.0/base        10) sems-hdf5/1.8.12/parallel     13) sems-superlu/4.3/base
  2) sems-python/2.7.9              5) sems-gcc/4.9.3                 8) sems-yaml_cpp/0.5.3/base      11) sems-netcdf/4.3.2/parallel
  3) sems-cmake/3.5.2               6) sems-openmpi/1.6.5             9) sems-zlib/1.2.8/base          12) sems-parmetis/4.0.3/parallel
```
Finally I get this type of warning when I compile:
```/projects/sems/install/rhel7-x86_64/sems/compiler/gcc/4.8.5/openmpi/1.6.5/include/mpi_portable_platform.h:374:63: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]```
which reports gcc-4.8.5 as compiler?

I am attaching my configure script in case it yields any clues.
[configure_trilinos.sh.txt](https://github.com/trilinos/Trilinos/files/1115771/configure_trilinos.sh.txt)

**Comment by bartlettroscoe** [comment]
@lucbv,

Can you try opening a fresh shell and trying again?  When you do `source Trilinos/cmake/load_sems_dev_env.sh`, it should blow away your current modules and load the new ones, which should be for GCC 4.8.4.

There is nothing that mentions loading a GCC 4.9.3 module left in the 'develop' branch for those scripts as shown by:

```
$ grep -nH 4.8.3 cmake/std/sems/*
cmake/std/sems/SEMSDevEnv.cmake:24:  # Make OpenMPI 1.6.5 mpi.h with GCC 4.8.3 warnings go away (see #1341)
```

(But that is just a comment, not anything that would impact the modules.)

> Finally I get this type of warning when I compile:
> ```
> /projects/sems/install/rhel7-x86_64/sems/compiler/gcc/4.8.5/openmpi/1.6.5/include/mpi_portable_platform.h:374:63: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
> which reports gcc-4.8.5 as compiler?

That is a long sad story (see #1341).  But it is resolved by the switch GCC 4.8.4 (see #1453).

Let's get this resolved quickly.  We can get on Skype if we need to so that I can poke around and see what is happening.

**Comment by lucbv** [comment]
Interestingly it is now back to normal and I don't get the annoying ```unable to find CXXABI_1.3.8``` while I run my tests. This happened for three build cycles on clean terminals...
If that happens again I'll let you know about it. In the meantime I think I could close this.

**Comment by bartlettroscoe** [comment]
@lucbv,

> Interestingly it is now back to normal and I don't get the annoying `unable to find CXXABI_1.3.8` while I run my tests. This happened for three build cycles on clean terminals...
If that happens again I'll let you know about it. In the meantime I think I could close this.

If you have any other strange things like this happen, don't hesitate to let me know.

Closing as requested.
