### ISSUE TITLE
Improper python environment on test machine hansel

### ISSUE THREAD

**Issue by jhux2** [trilinos/Trilinos#1468]
@trilinos/framework There appears to be a problem with the python environment on the test machine ```hansel.sandia.gov```.   As a result, two ML tests are failing for the 12.10.1 release.  The symptom is

```
'import site' failed; use -v for traceback
Traceback (most recent call last):
  File "/jenkins/slave/workspace/Trilinos_hansel_release_12.10/MPI_RELEASE_12.10.1_SHARED/Trilinos/commonTools/test/utilities/compareTestOutput", line 9, in <module>
    import re
ImportError: No module named re
```

Errors can be found [here](https://testing.sandia.gov/cdash/testDetails.php?test=39699947&build=2975943) and [here](https://testing.sandia.gov/cdash/viewTest.php?onlyfailed&buildid=2975354).

**Comment by aprokop** [comment]
@trilinos/framework

**Comment by jwillenbring** [comment]
@william76 is this something you could look at?

**Comment by jwillenbring** [comment]
I don't think this is relevant anymore. If it is, please reopen.
