### ISSUE TITLE
MueLu: output truncated after rebalancing and proc 0 drops out

### ISSUE THREAD

**Issue by jhux2** [trilinos/Trilinos#1471]
If MueLu is run in parallel with rebalancing enabled, and processor 0 is not in the MPI communicator after rebalancing, then no detailed setup output is printed.

This is reproducible on two processors with MueLu's scaling driver:

```mpirun -np 2 ./MueLu_Driver.exe  --matrixType=Laplace3D --xml=scaling.xml --nx=34 --ny=34 --nz=34 --rebuild=1 --solver=none --notimings```

where the rebalancing options are as follows:

```
    <Parameter        name="repartition: enable"                  type="bool"     value="true"/>
    <Parameter        name="repartition: print partition distribution"    type="bool"     value="true"/>
    <Parameter        name="repartition: partitioner"             type="string"   value="zoltan2"/>
    <Parameter        name="repartition: start level"             type="int"      value="1"/>
    <Parameter        name="repartition: min rows per proc"       type="int"      value="1500"/>
    <Parameter        name="repartition: max imbalance"           type="double"   value="1.1"/>
    <Parameter        name="repartition: remap parts"             type="bool"     value="false"/>
    <!-- start of default values for repartitioning (can be omitted) -->
    <Parameter name="repartition: remap parts"                type="bool"     value="true"/>
    <Parameter name="repartition: rebalance P and R"          type="bool"     value="false"/>
    <ParameterList name="repartition: params">
       <Parameter name="algorithm" type="string" value="multijagged"/>
    </ParameterList>
```

I think this is related to commit 38ad38f2.

**Comment by lucbv** [comment]
This is something I should keep an eye on as this could also happen if rank 0 is dropped in the not-rebalanced case described in issue 1466

**Comment by aprokop** [comment]
In addition to a)-c) mentioned in the commit, another option would be to allow `FancyOStream` to work in parallel. If processor 0 is dropped, it needs to turn on the waiting mode to receive chunks of output from other processors to print.

**Comment by pwxy** [comment]
I believe this was the reason why there used to be the MueLu parameter "repartition: keep proc 0"?
I believe this parameter was removed because often not keeping proc 0 can reduce the amount of data movement for coarse level repartitioning.

**Comment by aprokop** [comment]
From what I recall, keeping proc 0 had a significantly worse performance than not keeping it.

**Comment by jhux2** [comment]
> I believe this was the reason why there used to be the MueLu parameter "repartition: keep proc 0"?
> I believe this parameter was removed because often not keeping proc 0 can reduce the amount of data movement for coarse level repartitioning.

> From what I recall, keeping proc 0 had a significantly worse performance than not keeping it.

I'd believe that.  The option "keep proc 0" was a hack for expediency's sake.

**Comment by tawiesn** [comment]
#1466
