### ISSUE TITLE
Document and add debug-mode runtime checks non-aliasing assumptions

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#1472]
**CC:** @trilinos/thyra 

**Description:** 

During the refactoring work for Thyra in #330, it was discovered that Belos aliases some of the input and output arguments in calls the Thyra::linear_combination().  That complicated the refactoring done in #330.  The assumption in Thyra from the earliest days (when it was called TSFCore, see [TSFCoreSAND.pdf](https://github.com/trilinos/Trilinos/files/1116655/TSFCoreSAND.pdf)) was that input objects must not alias output arguments, or the behavior is undefined (just like with Fortran).  However, some implementations of operations (like the element-wise implementation of Thyra::linear_combination() using the RTOp::LinearCombinationTOp subclass) allowed aliasing and worked correctly (by accident).

The reason that Thyra has the non-aliasing assumption is for just the reason for the complexity that had to be added in the commit 1de126c87242 .  It is a pain to write the implementations of things if you have to be constantly checking for aliasing and it creates inefficeint code that has to create expensive temp copies in order to carry out requested operations (like in the Belos example).  And with abstract objects, it can be very hard to detect aliasing of underlying memory (I can give several examples of this).  So the best policy is to just strictly disallow aliasing and say that if clients pass in aliased input and output objects, then the results are undefined.  That is what the Fortran standard does for the entire language (and since Thyra objects can call Fortran functions, this makes sense as well).

This story is to:

* Add clear documentation (both at the global level and the prototype for each function) that aliasing is not allowed (and if inputs and outputs are aliased, the results are undefined).
* Add debug-mode runtime checks for aliasing of input and output arguments to all of the non-virtual interface (NIV) member functions in all of the Thyra classes as possible.
* Update all of the Trilinos and customer code as possible that is passing in aliased input and output arguments.
* Remove current Thyra implementions that try to handle aliasing.

For all other external customers of Thyra, they will need to fix their code to not pass in aliased input and output objects (and create the temp objects themselves if needed).

**Possible Implementation:**

The way to implement this for Thyra is to add a new member function `aliasStatus(mv)` to the Thyra::LinearOpBase interface:

```
namespace Thyra {

// We can use C++11 now due to #1465!
enum class EAliasStatus { IS_ALIASED, NOT_ALIASED, UNKNOWN };

template<class Scalar>
class LinearOpBase: ... {
private:
  ...
  // NVI public function
  EAliasStatus aliasStatus(const MultiVectorBase<Scalar> &mv) const
    { return this->aliasStatusImpl(mv); }
  ...
protected:
  ...
  // NVI virtual function
  virtual EAliasStatus aliasStatus(const MultiVectorBase<Scalar> &mv) const = 0;
  ...
}; 

} // namespace Thyra
```

The Thyra::LinearOpDefaultBase class would have a default override of `aliasStatus()` that returned `Thyra::EAliasStatus::UNKNOWN` (so this would not break backward compatibility).

Thyra would then provide a non-member non-friend helper function like:

```
template<class Scalar>
void debugAssertNonAliasedInputsOutputs(
  const ArrayView<const Ptr<const LinearOpBase<Scalar> > > &inputs,
  const ArrayView<const Ptr<const LinearOpBase<Scalar> > > &outputs,
  const std::string &functionName );
```

That function would then throw an exception if it detected that any of the `input[i]` objects aliased any of the `output[j]` objects (using the new `aliasStatus()` member function).

Since every Thyra::LinearOpBase, Thyra::MultiVectorBase, and Thyra::VectorBase object all derive from Thyra::LinearOpBase, this one function could be used to assert non-aliasing in every operation in all of the Thyra interfaces like, for example:

```
template<class Scalar>
class LinearOpBase ... {

  ...

  void apply(
    const EOpTransp M_trans,
    const MultiVectorBase< Scalar > &X,
    const Ptr< MultiVectorBase< Scalar > > &Y,
    const Scalar alpha = static_cast< Scalar >(1.0),
    const Scalar beta = static_cast< Scalar >(0.0) 
    )
  {
    debugAssertNonAliasedInputsOutputs( Teuchos::tuple<...>(Y),
      Teuchos::tuple<...>(Teuchos::ptr(*this), Teuchos::ptrFromRef(X),
      "Thyra::LinearOpBase::apply(M_trans, X, Y, alpha, beta)" );
    applyImpl(M_trans, X, Y, alpha, beta);
  }

  ...
};
```

Once the function `debugAssertNonAliasedInputsOutputs()` is written and unit tested, it should not take long to add calls to this function (or indirectly using helper macros perhaps) in all of the Thyra intreface functions (that are using the NVI idiom anyway).

The harder part might be fixing Trilinos code (like Belos) trying to alias input and output objects.

**Comment by mhoemmen** [comment]
Belos is probably creating "generalized views" (i.e., deep copies that copy back on destruction) of Thyra objects all over the place.  This makes me concerned about performance of Belos solvers with Thyra objects.  Not saying it's Thyra's fault; rather, it's a mismatch of Belos' expectations and Thyra's expectations.

**Comment by bartlettroscoe** [comment]
> Belos is probably creating "generalized views" (i.e., deep copies that copy back on destruction) of Thyra objects all over the place. This makes me concerned about performance of Belos solvers with Thyra objects. Not saying it's Thyra's fault; rather, it's a mismatch of Belos' expectations and Thyra's expectations.

In that case, detecting aliasing will be more difficult.  We would have to add an `isAliased()` member function to allow Thyra::MultiVectorBase objects to determine if they are aliases of each other (i.e. if they share the same underlying memory).

But note that if there is aliasing, then a copy is getting created in the underlying implementation as shown at:

* https://github.com/trilinos/Trilinos/blob/develop/packages/thyra/adapters/tpetra/src/Thyra_TpetraMultiVector_def.hpp#L221

Therefore, I would argue that it would be better to detect the aliasing and throw rather than silently create a copy.  That way, the client can decide how to handle the aliasing problem.  The client might able to change how it manages objects and memory and avoid the copy.  But if a copy is needed, then this is visible to the client and there is not a hidden cost.

Does anyone not agree with that assessment?

**Comment by mhoemmen** [comment]
> Therefore, I would argue that it would be better to detect the aliasing and throw rather than silently create a copy. That way, the client can decide how to handle the aliasing problem. The client might able to change how it manages objects and memory and avoid the copy. But if a copy is needed, then this is visible to the client and there is not a hidden cost.
> 
> Does anyone not agree with that assessment?

I think that's a good plan.  It would make sense for downstream stuff using Thyra to turn on a "detect aliasing" feature, as a way to reassure themselves that they aren't using too much memory or spending too much time copying.

I've been thinking mainly about the typical Belos use case, as would show up in GMRES:

  1. Create a MultiVector to store basis vectors
  2. Extract subviews of that MultiVector to represent either the current basis vector, or some previous basis vectors

Does (2) actually create deep copies?  I had thought that it did when I looked a while back, but I don't want to spread Fear / Uncertainty / Doubt if that's not true :-) .

**Comment by bartlettroscoe** [comment]
> 2.  Extract subviews of that MultiVector to represent either the current basis vector, or some previous basis vectors
> 
> Does (2) actually create deep copies? I had thought that it did when I looked a while back, but I don't want to spread Fear / Uncertainty / Doubt if that's not true :-) .

No, a Thyra::TpetraMultiVector object will not create deep copies of underlying data on contiguous or non-contiguous sub-views.  See the implementation of contiguous views (using raw Tpetra::MultiVector subview functions) at:

* https://trilinos.org/docs/dev/packages/thyra/doc/html/classThyra_1_1TpetraMultiVector.html#a6ce55accd81fe8ad28c8323f2b4cc558
* https://trilinos.org/docs/dev/packages/thyra/doc/html/classThyra_1_1TpetraMultiVector.html#a7b953ccbc128f4726e1a861b116e439e

and non-contiguous views (using Thyra::DefaultColumnwiseMultiVector) at:

* https://trilinos.org/docs/dev/packages/thyra/doc/html/classThyra_1_1MultiVectorDefaultBase.html#af1728b38b64109cd66117138483470f6
* https://trilinos.org/docs/dev/packages/thyra/doc/html/classThyra_1_1MultiVectorDefaultBase.html#a329e943245ebf6f0cbc3c1bb0f945691

I don't think that Belos actually ever requests a non-contiguous view, does it?  The Belos/Thyra adapters are smart enough to detect a contiguous subview and call the right function as shown at:

* https://github.com/trilinos/Trilinos/blob/master/packages/stratimikos/adapters/belos/src/BelosThyraAdapter.hpp#L223

So think this is the right strategy: The Thyra non-virtual interface (NVI) member functions in debug-mode can look for aliasing and then throw if it finds it.  But to detect aliasing, the Thyra::MultiVectorBase interface will need a `isAliased(otherMv)` member function.  I will update the plan in the above description.

**Comment by mhoemmen** [comment]
@bartlettroscoe wrote:
> No, a Thyra::TpetraMultiVector object will not create deep copies of underlying data on contiguous or non-contiguous sub-views.

Thanks for clearing that up -- I was a bit worried about that.

> I don't think that Belos actually ever requests a non-contiguous view, does it?

The pseudoblock solvers do, when computing with multiple right-hand sides.  If some but not all right-hand sides converge, the solvers continue by creating a noncontiguous view of the remaining right-hand sides and iterating on those.  If anybody wanted to optimize this, they could change the pseudoblock solvers to pack the unconverged right-hand sides instead.
