### ISSUE TITLE
Collect items for major refactoring of Thyra to make simpler and more sustainable

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#1473]
**CC:** @trilinos/thyra, @rppawlo, @atoth1

**Description:**

Thyra is a feature-full but complex set of software supporting the development of abstract numerical algorithms (ANAs).  Over the years since Thyra has been in use, many potential developers have been scared off or intimidated by the complexity of Thyra.

This story is to collect a set of ideas on how we can refactor Thyra to make it simpler to understand, use, and extend, without destroying the OO design features and functionality.

To help collect these ideas, I have created the Google Doc "Simplifying Thyra":

* https://docs.google.com/document/d/1oHZzTHwl9D2lZ_on8HSg0zmAuB6wmToDtq2SOPzxmQs 

For now we are just going to collect ideas in that document.

ToDo: Define full scope for this story and a clear definition of done.

**Comment by jhux2** [comment]
@bartlettroscoe Around the time of the commits that changed ```Trilinos_ENABLE_``` to ```${PROJECT_NAME}_ENABLE_```, one of the MueLu experimental nightly builds began exiting early, due to no packages being enabled.  Prior to that change, the nightly build was running nontrivially. Here's the test [before](https://testing.sandia.gov/cdash/buildSummary.php?buildid=3009894) and [after](https://testing.sandia.gov/cdash/buildSummary.php?buildid=3011766).

Could the change in the MueLu experimental build be a side effect of these commits?

Admittedly, at the same time there was a big commit to MueLu with ETI.  I also have a superficial understanding of the nightly build and test system ....

**Comment by bartlettroscoe** [comment]
@jhux2, it is because Xpetra libraries failed to build and that takes out MueLu because MueLu has a required dependence on Xpetra.  If you look at the configure output for the "after" case at:

*  https://testing.sandia.gov/cdash/viewConfigure.php?buildid=3011766

you will see:

```
 ***
 *** WARNING: Setting Trilinos_ENABLE_MueLu=OFF which was 'ON' because MueLu has a required library dependence on disabled package Xpetra but Trilinos_DISABLE_ENABLED_FORWARD_DEP_PACKAGES=ON!
 ***

...


***
*** WARNING:  There were no packages configured so no libraries or tests/examples will be built!
***
```

If up back up to the top-level package-by-package build at:

* https://testing.sandia.gov/cdash/index.php?project=Trilinos&parentid=3011733

you can see that Xpetra had library (not tests or examples) build failures shown at:

* https://testing.sandia.gov/cdash/viewBuildError.php?buildid=3011748

Are those Xpetra build errors related to the `Trilinos_ENABLE`_ to `${PROJECT_NAME}_ENABLE_` refactoring?

What you are seeing in the lovely behavior of the package-by-package CTest driver that will disable downstream package if required upstream packages failed to build mentioned at:

* https://tribits.org/doc/TribitsDevelopersGuide.html#tribits-package-by-package-ctest-dash-driver

But this behavior will be gone once we can use the new all-at-once configure/build/test:

* https://github.com/TriBITSPub/TriBITS/issues/183

**Comment by tawiesn** [comment]
@jhux2 @bartlettroscoe 
It seems that Kokkos_ArithTraits.hpp has been moved from Kokkos to Kokkos-kernels (but it still has the same filename). In commit 98f0c0827d i added kokkos-kernels as an optional dependency to Trilinos. However i am not sure whether this is enough. Kokkos is an optional dependency for Xpetra (we cannot make it obligatory as Kokkos still does not compile for Windows as far as i know). But now we need Kokkos and Kokkos-kernels. I did not check it but i guess Kokkos-kernels is not compiled, right? I don't know whether there is a Tribits option to have two or none packages as optional dependency.
We could add a check in the Xpetra CMakeLists.txt whether both Kokkos and Kokkos-kernels is enabled and throw an error if one of them is not enabled...

**Comment by mhoemmen** [comment]
@tawiesn If it helps, Tpetra requires kokkos-kernels.  Thus, you could just use the optional dependency of Xpetra on Tpetra to get kokkos-kernels.

**Comment by bartlettroscoe** [comment]
If Xpetra directly includes a header file from KokkosKernels then it needs to define a directly dependency on KokkosKernels.  It should not rely on indirect dependencies to get it.

Whoever did that refactoring and did not update downstream packages messed up.

This discussion about MueLu, Xpetra, and Kokkos has nothing to do with this the scope of this Story so this discussion should be moved to another GitHub issue and the comments here should be deleted.

**Comment by jhux2** [comment]
> @jhux2, it is because Xpetra libraries failed to build and that takes out MueLu because MueLu has a required dependence on Xpetra.

@bartlettroscoe Thanks, I always forget that upstream failures could be the cause.  I will open a separate issue.
