### ISSUE TITLE
[Tempus] StepperBackwardEuler::takeStep

### ISSUE THREAD

**Issue by bartgol** [trilinos/Trilinos#1475]
@trilinos/tempus 
I am wondering whether the behaviour of this method is correct or not. In particular, I see that this class does not attempts to take the step (and returns) if the current stepperStatus is FAILED. Comparing this to the Newmark class (also implicit), I believe this is wrong. In the Newmark class, the stepperStatus is only set (to FAILED or PASSED) depending on whether the current step succeeded or not.

With the current implementation in StepperBackwardEuler, it appears to me that, once a time step fails (too big), the smaller time step (dt/2, set by TimeStepControl when the previous stepperStatus is FAILED) will never be tried, since the check on the stepper status causes the method to return prematurely.

I would suggest to change StepperBackwardEuler to **set** stepperStatus in takeStep **after** the call to the Thyra solve, and not **reading** it **before**. Since stepperStatus is already set after the call to the thyra solve, the solution would be to simply remove the check at line 235 of Tempus_StepperBackwardEuler_impl.hpp.

**Comment by ccober6** [comment]
This was fixed back in July with 664067f8.
