### ISSUE TITLE
Tpetra: Isolate sparse matrix-matrix multiply local kernel

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#148]
@trilinos/tpetra @mndevec @srajama1 @csiefer2 

In Tpetra, we need to isolate the "local" part of the sparse matrix-matrix multiply kernel from the "global" (MPI communication) part.  This will facilitate thread parallelization and the use of third-party libraries' implementations of the local kernel.

**Comment by mhoemmen** [comment]
MueLu sometimes actually wants to compute the Jacobi update $C = (I - \omega D^{-1} A) B$.

**Comment by csiefer2** [comment]
We need both Jacobi & SpMM.  They're basically the same kernel if you're smart about it.

**Comment by mhoemmen** [comment]
Andrey just explained to me that muelu/src/Misc/MueLu_RAPFactory_def.hpp uses Multiply, so yes :)

**Comment by mhoemmen** [comment]
mult_A_B_newmatrix does $C := A (B_{local} + B_{remote})$.

**Comment by mhoemmen** [comment]
I'm looking at mult_A_B_newmatrix now.  c_status is just something used internally.  Key inputs:

- Bk = targetMapToOrigRow[Ak] is valid if the local column of A, A.ind[k], is a local row of B (i.e., belongs to B_local).  In that case, Bk is the current local row of B_local at which to look.  Otherwise, Ik = targetMapToImportRow[Ak] is the current local row of B_remote at which to look.

- Bcol2col[Bcolind[j]]

**Comment by mhoemmen** [comment]
The output matrix C of mult_A_B_newmatrix gets its column Map and Import as the union of the column Maps resp. Imports of B_local and B_remote.

**Comment by aprokop** [comment]
I just want to document that I've tried a slightly different variant to speed things up, but was not successful. The thing I tried was to accumulate products and then merge together.

https://gist.github.com/aprokop/05ba603a934c7a96ac80

I would like for us to discuss what kind of improvements we may want to consider, and what is the path forward for multithreaded MMM.

@mhoemmen @mndevec @csiefer2

**Comment by srajama1** [comment]
Mehmet and I have an algorithm worked out that we expect to be "performance portable". Mehmet is implementing that. We are expecting Chris & Chris to take care of the distributed memory stuff.

**Comment by aprokop** [comment]
During the dungeon I wrote a quick serial wrapper for Kokkos experimental graph wrappers in MMM. While I don't have numbers any longer, running the KK1 version was many times slower than the existing implementation for a single thread.

**Comment by srajama1** [comment]
Not the existing one, that is a preliminary implementation we started with so we have something there. The new one will have two steps, symbolic and numeric. You want it faster than  we can develop it. Is there some urgency on this ? We were planning for late April or Early May. 

Someone wants to isolate the local kernel before then, that is ok. But the threaded kernel on all three platforms that we care will take some work.

**Comment by aprokop** [comment]
No particular urgency, just a general desire to see faster MMM.
Is there a way I can look at the newest implementation/algorithm?

**Comment by srajama1** [comment]
We can explain our current thinking in person with a board. The primary trouble is getting it to work in GPUs.

**Comment by mndevec** [comment]
@aprokop 
I dont have a complete implementation yet for Matrix Multiplication. I only have interfaces to MKL, cuSPARSE and CUSP. 
Which one you compare against the sequential?

**Comment by aprokop** [comment]
I tried SPGEMM_MKL and SPGEMM_KK1. KK1 was the slow one, I believe.

**Comment by mndevec** [comment]
KK1 is incomplete, it does not have multiplication. It shouldn't produce any result.

**Comment by aprokop** [comment]
I did not check for what it did, I just checked the runtime when running with an example in tpetra.

**Comment by mhoemmen** [comment]
@jhux2 @csiefer2 @trilinos/muelu Please tell us which sparse matrix-matrix multiply routines matter most.
  - mult_A_B_newmatrix?
  - jacobi_A_B_newmatrix?
  - What about *_reuse?

**Comment by mhoemmen** [comment]
@csiefer2 @jhux2 Also, is there some reason why mult_A_B_newmatrix and jacobi_A_B_newmatrix use entirely different local sparse matrix-matrix multiply algorithms?

**Comment by aprokop** [comment]
@mhoemmen 
> Please tell us which sparse matrix-matrix multiply routines matter most.
> 
> mult_A_B_newmatrix?
> jacobi_A_B_newmatrix?
> What about *_reuse?

*newmatrix all matter. *_reuse matters significantly less as the MueLu reuse has not been heavily used yet.

**Comment by csiefer2** [comment]
@mhoemmen: mult_A_B_newmatrix and jacobi_A_B_newmatrix use almost identical local algorithms.  The only difference is whether or not you have the Jacobi part.  The code is cut and paste because there was no good way to do it all in one routine that I could think of.

**Comment by ambrad** [comment]
@aprokop, now that RILUK supports reuse properly and efficiently, does that change the importance of reuse? Or are there other blockers to effective reuse in MueLu?

**Comment by mhoemmen** [comment]
@csiefer2 wrote:
> mult_A_B_newmatrix and jacobi_A_B_newmatrix use almost identical local algorithms. The only difference is whether or not you have the Jacobi part. The code is cut and paste because there was no good way to do it all in one routine that I could think of.

That's OK -- I was mainly wondering why the local sparse matrix-matrix multiply algorithms are just a tiny bit different (not just because of mult vs. jacobi interface) between the two functions.

**Comment by aprokop** [comment]
@ambrad I have not looked at the recent RILUK changes, but if as you say it does the proper separation of symbolic() and numeric(), it definitely makes it easier. If everything on the path to do AdditiveSchwarz with overlapping subdomains and RILUK does the correct separation of symbolic() and numeric() phases, I believe the proper reuse implementation in MueLu can be written quickly. 

One of my concerns is the overlapping matrix part where I think it does the import during the Setup() phase.

**Comment by mhoemmen** [comment]
I'm going to close this, because it kind of happened.
