### ISSUE TITLE
Headers need to use <mpi.h> instead of "mpi.h"

### ISSUE THREAD

**Issue by bangerth** [trilinos/Trilinos#1480]
We got a bug report for deal.II that in essence shows this error message:
```

    In file included from /usr/local/include/ml_epetra_utils.h:42:0,
                     from /usr/local/include/ml_MultiLevelPreconditioner.h:86,
                     from ~/Downloads/dealii/source/lac/trilinos_precondition_ml.cc:33:
    /usr/local/include/mpi.h:157:16: error: redefinition of ‘struct MPI_Status’
     typedef struct MPI_Status {
                    ^~~~~~~~~~
    In file included from ~/Downloads/dealii/build/include/deal.II/base/config.h:328:0,
                     from ~/Downloads/dealii/include/deal.II/lac/trilinos_index_access.h:19,
                     from ~/Downloads/dealii/source/lac/trilinos_precondition_ml.cc:16:
    /opt/intel/compilers_and_libraries/linux/mpi/include64/mpi.h:679:16: note: previous definition of ‘struct MPI_Status’
```
Note how the conflicting declarations come from `/usr/local/include/mpi.h` and `/opt/intel/compilers_and_libraries/linux/mpi/include64/mpi.h`. 

The reason is that the user is compiling with the Intel compiler which, via a `-I` flag, provides the `mpi.h` in `/opt/intel/compilers_and_libraries/linux/mpi/include64`. This resolves all instances of `#include <mpi.h>`.

Maybe in a poor choice, the user installed *both* Trilinos and another MPI installation in `/usr/local`, and so when a Trilinos header uses the double-quoted form `#include "mpi.h"`, the compiler *first* looks into `/usr/local/include` and only then into the paths listed via `-I`. Normally that would do no harm since no `mpi.h` is found, but now it is, and the conflict happens.

The problem is because we have this in `ml_epetra_utils.h`:
```
ifdef ML_MPI
#ifndef EPETRA_MPI
#define EPETRA_MPI
#endif
#include "mpi.h"         *****************
#endif
```
This should really be `#include <mpi.h>` instead of the double-quoted form. I find other instances of this bug in the following files:
```
> grep '"mpi.h"' *h
Epetra_Time.h:#include "mpi.h"
MLAPI_Workspace.h:#include "mpi.h"
ml_epetra_utils.h:#include "mpi.h"
ml_smoother.h:#include "mpi.h"
```
These are all bugs waiting to happen.

**Comment by ibaned** [comment]
@trilinos/epetra (there is no @trilinos/ml, so mentioning @trilinos/muelu instead)

**Comment by mhoemmen** [comment]
> Maybe in a poor choice, the user installed both Trilinos and another MPI installation in /usr/local

Just checking -- can the user work around this issue by installing Trilinos in a different directory?

**Comment by bangerth** [comment]
@mhoemmen : Yes, installing into a different directory works. It's more the fact that the typical user would not have been able to figure out what the problem is, and thus what the solution is. 

There is, of course, also the issue that once you have your installation in `/usr/local`, it's hard to get rid of it again, and because `/usr/local/include` is often part of `$INCLUDE`, these files will present a problem forever on that system. I might add that in deal.II, we helped this at least a little bit by putting all include files into a subdirectory -- which would here have been `/usr/local/include/deal.II` -- thus creating a namespace that we can occupy as we see fit. (In fact, the different parts of deal.II then occupy even further nested subdirectories there.) That turned out to be a good approach to avoid these sorts of problems, along with name clashes etc.

**Comment by mhoemmen** [comment]
@bangerth wrote:
> It's more the fact that the typical user would not have been able to figure out what the problem is, and thus what the solution is.

Totally understood :-)  Now that I am doing more application development, I totally empathize with most users' experience trying to install Trilinos.

> I might add that in deal.II, we helped this at least a little bit by putting all include files into a subdirectory -- which would here have been /usr/local/include/deal.II -- thus creating a namespace that we can occupy as we see fit.

Trilinos has resisted this mainly to serve our largest internal customer.  They have an ... interesting way of building Trilinos, that historically required storing Trilinos' headers in a flat directory.  I think we could change that, but it would break backwards compatibility for EVERYONE (not just that customer).

How would you recommend we deal with this issue?  Would it suffice just to use `#include <mpi.h>` instead of `#include "mpi.h"`?

**Comment by bangerth** [comment]
> Trilinos has resisted this mainly to serve our largest internal 
> customer. They have an ... interesting way of building Trilinos, that 
> historically required storing Trilinos' headers in a flat directory. I 
> think we could change that, but it would break backwards compatibility 
> for EVERYONE (not just that customer).

Well, we had the same issues with backward compatibility. It comes down 
whether you want to support a questionable design *forever*, or whether 
you are willing to make changes as long as you provide a backward 
compatible upgrade path.

In the current context, the upgrade path is this:
* Install the header files into subdirectories
* Install backward compatibility header files into the existing
   location that simply `#include` the ones in the new locations
* At some point, add `#warning` directives to these files to alert
   users that they should change their sources
* If necessary, also add the subdirectories (and not just
   `$CMAKE_INSTALL_PREFIX/include`) to the set of Trilinos
   include directories. This way the old `#include` directives
   will simply continue to work, but that has the disadvantage that
   users don't get the warning.
* Eventually drop the compatibility headers.

This has worked well for us, without complaints from users.


> How would you recommend we deal with this issue? Would it suffice just 
> to use |#include <mpi.h>| instead of |#include "mpi.h"|?

Yes, that's the easy part and should have no backward compatibility 
implications.

**Comment by mhoemmen** [comment]
@bangerth See my e-mail reply about the definition of "you" in your phrase "whether you are willing to make changes...."

Thanks for the guidance.  I will propose this fix and hope to get some buy-in from other Trilinos developers.

**Comment by mhoemmen** [comment]
@trilinos/framework

**Comment by ibaned** [comment]
I went through and made PR #1499 that I think covers all the instances of this that end up in installed headers. Its a bit shocking how many Trilinos files directly include `mpi.h`. There was also a patch needed to STK which I've sent to the STK developers.

**Comment by mhoemmen** [comment]
@ibaned you're a beast!  awesome! :D

**Comment by ibaned** [comment]
The `<mpi.h>` thing is now mostly done, with the possible exception of STK, which will get done once they do their next snapshot.
