### ISSUE TITLE
MueLu: teuchos timers for coarser levels after rebalancing drop out (most likely due to proc 0 dropping out)

### ISSUE THREAD

**Issue by pwxy** [trilinos/Trilinos#1489]
The printing of MueLu teuchos timers for coarser levels after rebalancing drop out (most likely due to proc 0 dropping out).
However, the total times are probably still correct, but would need to double-check this.
This is likely due to the same reason as issue #1471

**Comment by tawiesn** [comment]
This is connected to issue #1466 (possible negative consequences when dropping processors)
