### ISSUE TITLE
Checkin test broken w/ SEMS modules on RHEL 6

### ISSUE THREAD

**Issue by csiefer2** [trilinos/Trilinos#1491]
The checkin test script generates executables which cannot be run by hand due to path issues:

[csiefer@machine BlockedCrsMatrix]$ ./Xpetra_BlockedCrsMatrix_UnitTests.exe 
./Xpetra_BlockedCrsMatrix_UnitTests.exe: error while loading shared libraries: libmpi_f90.so.1: cannot open shared object file: No such file or directory

So when ctest fails, there is no way to debug it...

**Comment by lucbv** [comment]
@bartlettroscoe this looks like it might be caused by different module version in the sems-checkin script version the sems-env that is loaded with ```load-sems-dev-env.sh```

**Comment by bartlettroscoe** [comment]
Are you sourcing the env first as described at:

* https://github.com/trilinos/Trilinos/wiki/Policies-%7C-Safe-Checkin-Testing#reproducing-failures-manually

?

The `checkin-test-sems.sh` does not export the SEMS env into your current shell to avoid messing up your current shell.  (Note the Warning about blowing away your current modules in that section.)

**Comment by csiefer2** [comment]
Neat!
