### ISSUE TITLE
SEACAS configure & build failures on nightlies: missing matio library

### ISSUE THREAD

**Issue by william76** [trilinos/Trilinos#1494]
@gsjaardema 
@trilinos/framework 

I'm seeing some issues on the nightly board that are SEACAS/Matio related and thought we might be able to push and get them fixed...

Last Night's Nightly board:
https://testing.sandia.gov/cdash/index.php?project=Trilinos&date=2017-07-11##Nightly

### Machines Affected
- artemis.srn.sandia.gov
  - Configure error (1)
  - https://testing.sandia.gov/cdash/viewConfigure.php?buildid=2994938
- apollo.sandia.gov
  - Build failures (4)
  - https://testing.sandia.gov/cdash/viewBuildError.php?buildid=2994363

### Configure Error
The configure script on artemis seems to be failing because it cannot locate the Matio TPL:

`Processing enabled TPL: Matio (enabled by SEACASExo2mat, disable with -DTPL_ENABLE_Matio=OFF)
-- Matio_LIBRARY_NAMES='matio'
-- Searching for libs in Matio_LIBRARY_DIRS=''
-- Searching for a lib in the set "matio":
--   Searching for lib 'matio' ...
-- NOTE: Did not find a lib in the lib set "matio" for the TPL 'Matio'!
-- ERROR: Could not find the libraries for the TPL 'Matio'!
-- TIP: If the TPL 'Matio' is on your system then you can set:
     -DMatio_LIBRARY_DIRS='<dir0>;<dir1>;...'
   to point to the directories where these libraries may be found.
   Or, just set:
     -DTPL_Matio_LIBRARIES='<path-to-libs0>;<path-to-libs1>;...'
   to point to the full paths for the libraries which will
   bypass any search for libraries and these libraries will be used without
   question in the build.  (But this will result in a build-time error
   if not all of the necessary symbols are found.)
-- ERROR: Failed finding all of the parts of TPL 'Matio' (see above), Aborting!

-- NOTE: The find module file for this failed TPL 'Matio' is:
     /home/jenkins/slave/workspace/Kokkos_Trilinos_packages/MPI_RELEASE_DEV_DownStream_ETI_SERIAL-OFF_OPENMP-ON_PTHREAD-OFF_CUDA-OFF_COMPLEX-OFF/Trilinos/cmake/TPLs/FindTPLMatio.cmake
   which is pointed to in the file:
     /home/jenkins/slave/workspace/Kokkos_Trilinos_packages/MPI_RELEASE_DEV_DownStream_ETI_SERIAL-OFF_OPENMP-ON_PTHREAD-OFF_CUDA-OFF_COMPLEX-OFF/Trilinos/TPLsList.cmake

TIP: One way to get past the configure failure for the
TPL 'Matio' is to simply disable it with:
  -DTPL_ENABLE_Matio=OFF
which will disable it and will recursively disable all of the
downstream packages that have required dependencies on it, including
the package 'SEACASExo2mat' which triggered its enable.
When you reconfigure, just grep the cmake stdout for 'Matio'
and then follow the disables that occur as a result to see what impact
this TPL disable has on the configuration of Trilinos.

CMake Error at /home/jenkins/slave/workspace/Kokkos_Trilinos_packages/Trilinos/cmake/tribits/core/package_arch/TribitsProcessEnabledTpl.cmake:127 (MESSAGE):
  ERROR: TPL_Matio_NOT_FOUND=TRUE, aborting!
Call Stack (most recent call first):
  /home/jenkins/slave/workspace/Kokkos_Trilinos_packages/Trilinos/cmake/tribits/core/package_arch/TribitsGlobalMacros.cmake:1659 (TRIBITS_PROCESS_ENABLED_TPL)
  /home/jenkins/slave/workspace/Kokkos_Trilinos_packages/Trilinos/cmake/tribits/core/package_arch/TribitsProjectImpl.cmake:202 (TRIBITS_PROCESS_ENABLED_TPLS)
  /home/jenkins/slave/workspace/Kokkos_Trilinos_packages/Trilinos/cmake/tribits/core/package_arch/TribitsProject.cmake:93 (TRIBITS_PROJECT_IMPL)
  CMakeLists.txt:93 (TRIBITS_PROJECT)

-- Configuring incomplete, errors occurred!
See also "/home/jenkins/slave/workspace/Kokkos_Trilinos_packages/MPI_RELEASE_DEV_DownStream_ETI_SERIAL-OFF_OPENMP-ON_PTHREAD-OFF_CUDA-OFF_COMPLEX-OFF/BUILD/CMakeFiles/CMakeOutput.log".
See also "/home/jenkins/slave/workspace/Kokkos_Trilinos_packages/MPI_RELEASE_DEV_DownStream_ETI_SERIAL-OFF_OPENMP-ON_PTHREAD-OFF_CUDA-OFF_COMPLEX-OFF/BUILD/CMakeFiles/CMakeError.log".
CMake Error: CTEST_USE_LAUNCHERS is enabled, but the RULE_LAUNCH_COMPILE global property is not defined.
Did you forget to include(CTest) in the toplevel CMakeLists.txt ?`

### Build Errors
The build errors on apollo look like they're resulting from files that failed to compile for matio related issues and then there are 2x link errors because the .o files that would have been generated are missing.  Different systems, but could this be related?

**Missing header**:
`/home/jenkins/slave/workspace/Trilinos_apollo_gcc_4.8.4_cuda_7.5.18/MPI_RELEASE_DEV_DownStream_ETI_SERIAL-ON_OPENMP-OFF_PTHREAD-OFF_CUDA-ON_COMPLEX-OFF/Trilinos/packages/seacas/applications/mat2exo/mat2exo.C:61:48: fatal error: matio_pubconf.h: No such file or directory
 #include "matio_pubconf.h" // for MATIO_VERSION
                                                ^
compilation terminated.
`

**Version problem**:
`/home/jenkins/slave/workspace/Trilinos_apollo_gcc_4.8.4_cuda_7.5.18/MPI_RELEASE_DEV_DownStream_ETI_SERIAL-ON_OPENMP-OFF_PTHREAD-OFF_CUDA-ON_COMPLEX-OFF/Trilinos/packages/seacas/applications/exo2mat/exo2mat.C:70:2: error: #error "MatIO Version 1.5.1 or greater is required"
 #error "MatIO Version 1.5.1 or greater is required"
  ^`

**Comment by mhoemmen** [comment]
SEACAS definitely wants Matio.

**Comment by gsjaardema** [comment]
Matio is optional for seacas.

**Comment by bartlettroscoe** [comment]
The SEMS env does not provide the Matio TPL.  For example, the standard CI build for Trilinos explicitly disables Matio as shown at:

* https://testing.sandia.gov/cdash/buildSummary.php?buildid=3000706

showing:

```
Explicitly disabled TPLs on input (by user or by default):  Matio X11 GLM 3
```

This is set in the file Trilinos/cmake/std/BasicCiTestingSettings.cmake.

Please follow that example (or just include that same file).
