### ISSUE TITLE
Amesos2 *petra unit tests failing in Nightly testing

### ISSUE THREAD

**Issue by william76** [trilinos/Trilinos#1495]
@trilinos/amesos2 

As part of the effort to get the nightly testing boards for Trilinos green, I've been looking into the test failures.  
 - Last night's cdash: https://testing.sandia.gov/cdash/index.php?project=Trilinos&date=2017-07-11##Nightly

The nightly testing shows 3 tests failing in the Amesos2 test suite running on enigma that have been failing for a long time (they haven't passed since we refactored the "tracks" last month):
- **Build Name**: Linux-GCC-4.8.3-SERIAL_DEBUG_DEV_MueLu_ExtraTypes
- **Tests Failed**: https://testing.sandia.gov/cdash/viewTest.php?onlyfailed&buildid=2994621
  - Amesos2_Epetra_MultiVector_Adapter_UnitTests_MPI_4
  - Amesos2_Epetra_RowMatrix_Adapter_UnitTests_MPI_4
  - Amesos2_Tpetra_CrsMatrix_Adapter_UnitTests_MPI_4

We're really close to getting the 'red' off the nightly board.  Can someone have a look into these test failures?

@trilinos/epetra 
@trilinos/tpetra 
@trilinos/framework

**Comment by ndellingwood** [comment]
Merge PR #1532, should be fixed by @brian-kelley's. Should wait to close until nightly testing results come back clean.

**Comment by ndellingwood** [comment]
Dashboard has been clean regarding these tests with fix mentioned above, closing the issue.
