### ISSUE TITLE
Muelu build error: UnsmooshFactory

### ISSUE THREAD

**Issue by DrBooom** [trilinos/Trilinos#1498]
I did a git pull late yesterda, and despite a full re-configure and build, am still getting all sorts
of errors in building UnsmooshFactory, VariableDofLaplacianFactory, etc.  

Is there something I new need to add to my build script? 

> undefined reference to `Teuchos::RCP<Xpetra::Map<int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > > Galeri::Xpetra::CreateMap<int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >(Xpetra::UnderlyingLib, std::string const&, Teuchos::RCP<Teuchos::Comm<int> const> const&, Teuchos::ParameterList&)'

**Comment by tawiesn** [comment]
@DrBoom Thanks for reporting this issue.
Can you provide your configuration script?

**Comment by DrBooom** [comment]
See attached.

-c


Chris Luchini
ORG 1443
Sandia National Laboratory
(505) 284 3484
(505) 690 5008 Cell (505) is required.
________________________________

**Comment by tawiesn** [comment]
@DrBoom Sorry, didn't get the attachment. Could you send it to my email address rather than answering the github issue email? Attachments are dropped. Thx

**Comment by jhux2** [comment]
@trilinos/muelu

**Comment by jhux2** [comment]
@DrBooom Is this still a problem for you?

**Comment by DrBooom** [comment]
No.



Chris Luchini
ORG 1443
Sandia National Laboratory
(505) 284 3484
(505) 690 5008 Cell (505) is required.
________________________________
