### ISSUE TITLE
MueLu: dashboards failures

### ISSUE THREAD

**Issue by jhux2** [trilinos/Trilinos#150]
MueLu has a number of dashboard failures:

![screenshot](https://cloud.githubusercontent.com/assets/12970120/13185625/05ccbaea-d6f7-11e5-9d57-39e7b802f7e6.png)

@aprokop @tawiesn

**Comment by jhux2** [comment]
Interpreter tests are now fixed with commit e1a21ad and friends.

**Comment by jhux2** [comment]
Dashboard is cleaner.  Tests that involve rebalancing and that use a CUDA node are still failing.  The last output seen is
```
 Build (MueLu::RebalanceTransferFactory)
  Rebalancing restrictor
   Using original restrictor
 Computing Ac (MueLu::RebalanceAcFactory)
  Rebalancing existing Ac
   Replacing maps with a subcommunicator
```
Hierarchy::Write is also failing, but after talking with Tobias, I have an idea of how this *might* be fixed.

**Comment by jhux2** [comment]
> Hierarchy::Write is also failing, but after talking with Tobias, I have an idea of how this might be fixed.

Hopefully fixed Write with commit 2b660af.  Further delineated files written out by the underlying Scalar type.

**Comment by tawiesn** [comment]
Parts are related to #146

**Comment by tawiesn** [comment]
Most dashboard failures have been fixed. Remaining dashboard failures are related to specific platforms only and need more debugging. Closing this issue.

**Comment by crtrott** [comment]
Wasn't the purpose of this issue to get the Cuda builds non-failing?

**Comment by mhoemmen** [comment]
@crtrott It's not fair to make the MueLu developers have a clean CUDA Dashboard, until Tpetra has a clean CUDA Dashboard :-)  (We're working on it, don't worry!)

**Comment by crtrott** [comment]
I am not saying that it is fair, I just thought we might want to keep the issue open. Maybe it gets fixed via a Tpetra fix, that is fine with me.

**Comment by tawiesn** [comment]
I would propose to open a separate issue for the failing CUDA tests (with a more specific description).

**Comment by mhoemmen** [comment]
> Maybe it gets fixed via a Tpetra fix, that is fine with me.

Really hoping I can fix it in Tpetra.  It could be really hard to fix in MueLu.
