### ISSUE TITLE
Logic error thrown in Kokkos destructor

### ISSUE THREAD

**Issue by dlkarnit** [trilinos/Trilinos#1505]
@trilinos/tpetra
Reporting a logic error thrown by Kokkos as requested by the error message. Trilinos version 12.10.1

> terminate called after throwing an instance of 'std::logic_error'
>   what():  /usr/local/thirdparty/trilinos/v12.10.1/packages/teuchos/kokkoscompat/src/KokkosCompat_ClassicNodeAPI_Wrapper.hpp:265:
> 
> Throw number = 1
> 
> Throw test that evaluated to true: count < 0
> 
> Kokkos::Compat::KokkosDeviceWrapperNode<ExecutionSpace=N6Kokkos6OpenMPE, MemorySpace=N6Kokkos9HostSpaceE > destructor: count = -1 < 0 at end of destructor.  Please report this bug to the Tpetra developers.

**Comment by mhoemmen** [comment]
This usually only happens because somebody created a Node instance by hand.  Whoever is doing that, please don't :-) .  Also, RCP is not thread safe.

**Comment by dlkarnit** [comment]
I have yet to be able to create a small code to replicate the issue. Though I'm looking into other possible memory corruptions that could be related.

I'm using Belos + MueLu to solve a linear system with a multi-grid preconditioner similar to the example usage of Belos. Though I'm creating each of the Problem, Preconditioner, and solver with Teuchos::rcp( new ... ) calls. The code I'm integrating into also uses the same constructs for a separate problem, and it seems that only when both the main product and my library use the templated stack the issue arises. If I use my older Epetra/AztecOO/ML stack there is no issue.

How would one create a Node instance by hand?

**Comment by mhoemmen** [comment]
> How would one create a Node instance by hand?

Please don't :-) .  "Create a Node instance by hand" means "invoking the constructor of `node_type`".

My guess is that you have an example code in main().  RCP automatically invokes destructors on scope exit, but this could be bad if `Kokkos::finalize` or `MPI_Finalize` have already been called.  If your code lives in main(), try this:
```
int main (...) {
  // MPI_Init or Teuchos::GlobalMPISession go here
  {
    // your code
  }
  // MPI_Finalize, etc., if you are calling them, go here
}
```

**Comment by dlkarnit** [comment]
If I'm constructing the trilinos objects in the scope of another object, would it be a wise practice to initialize those RCP objects to Teuchos::null in my destructor? Or better to leave them alone in the destructor?

Example:
  Foo() : vSolver( Teuchos::rcp( new Solver() ) ) {}
~Foo() { vSolver = Teuchos::null }

**Comment by mhoemmen** [comment]
You may leave them alone in the destructor.  `~Foo()` will automatically invoke RCP's destructor, which will reduce the reference count by one.

**Comment by mhoemmen** [comment]
I'm closing this until I see code that manifests the issue.  Please feel free to reopen at that point.

**Comment by dlkarnit** [comment]
I have not been able to reproduce this case yet in a code segment that is shareable. However, I have experimented with my code and found that I can prevent the issue if I construct my Tpetra::Map in a different way:

Old way in Foo constructor (creates error)
Foo() : vMap( Teuchos::rcp(new Map( size, idxBase, comm )) ) {}

New way (error not thrown at exit)
Foo() : vMap( Tpetra::createLocalMap<Ordinal,Ordinal>( size, comm )) ) {}

This may be an acceptable workaround for now, but by its naming will createLocalMap() not work if the comm was a global MPI communicator (this map would need to be my global problem map)?

For reference, we define the Map type in the following way in a forward declaration in our class header:
typedef int Ordinal
typedef Tpetra::DefaultPlatform::DefaultPlatformType::NodeType Node
typedef Tpetra::Map<Ordinal,Ordinal,Node> Map

class Foo {
 private:
  Teuchos::RCP< const Map > vMap
}

**Comment by mhoemmen** [comment]
You don't need to supply the `Node` template parameter.  Try this:
```
typedef Tpetra::Map<Ordinal, Ordinal> Map;
```

**Comment by mhoemmen** [comment]
The `createLocalMap` function creates a replicated Map over the given communicator.  This probably not what you want.

**Comment by mhoemmen** [comment]
My guess is that some instance of your class Foo is being allowed to persist past Kokkos::finalize() or MPI_Finalize().  Otherwise, I'm not sure what else you could be doing wrong.  What solvers are you using?  Also, do you have this issue with the develop version of Trilinos?
