### ISSUE TITLE
MueLu_Navier2DBlockedReuseAggs_MPI_4 failing nightly testing

### ISSUE THREAD

**Issue by william76** [trilinos/Trilinos#1507]
@trilinos/muelu 

`MueLu_Navier2DBlockedReuseAggs_MPI_4` started failing in the nightlies about 3 nights ago in the `Linux-GCC-5.2.0-OPENMPI_1.10.0_RELEASE_DEV_MueLu_NO_SERIAL` build on geminga. 

**Links**:
- Error Messages: https://testing.sandia.gov/cdash/testDetails.php?test=40052062&build=3004895
- Nightly build: https://testing.sandia.gov/cdash/index.php?project=Trilinos&parentid=3004715

**Comment by tawiesn** [comment]
Checkin test script is running...

**Comment by lucbv** [comment]
@tawiesn it seems that the issue does not show up on CDash this morning, should this issue be closed?

**Comment by tawiesn** [comment]
Can be closed. Btw: it should automatically close once the patch is 
merged into the master branch.

Tobias
