### ISSUE TITLE
Tpetra: Add symbolic & numeric analysis phases to KokkosSparse::CrsMatrix

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#151]
This would let us use TPLs like the MKL inspector-executor interface, that have separate analysis and apply phases.

**Comment by mhoemmen** [comment]
#147 needs this for a clean implementation.  My initial experiments just hack things into Tpetra::CrsMatrix, but the point is to put this in KokkosKernels.

**Comment by mhoemmen** [comment]
> What is symbolic and numeric phase for a matrix ?

It's a bit confusing to use those words when there's no "apply."  "Symbolic" here means "setup that does not depend on the values in the matrix," and "numeric" means "setup that _does_ depend on the values."

**Comment by srajama1** [comment]
Still confusing. What does setup here mean ? Sorry if this was something obvious.

**Comment by mhoemmen** [comment]
> What does setup here mean ?

https://software.intel.com/en-us/node/590017

**Comment by mhoemmen** [comment]
Discussion of KokkosKernels handles shows that this properly belongs in the "handle," not in KokkosSparse::CrsMatrix.
