### ISSUE TITLE
Zoltan: remove generated autoconf files from source?

### ISSUE THREAD

**Issue by nschloe** [trilinos/Trilinos#1512]
On the Debian build, we currently cannot advance the standard version of Trilinos since some build artifacts are in the source tree, notably
```
packages/zoltan/config/config.guess
packages/zoltan/config/config.sub
```
Is anyone still building Zoltan with autotools at all? If not, more files could go.

---

From https://www.debian.org/doc/packaging-manuals/upgrading-checklist.txt:
> 4.3
> "config.sub" and "config.guess" should be updated at build time or replaced with the versions from autotools-dev.

**Comment by aprokop** [comment]
@trilinos/zoltan @kddevin

**Comment by kddevin** [comment]
Sorry, @nschloe ; I am just seeing this issue now.  
https://github.com/trilinos/Trilinos/wiki/GitHub-Notifications

Zoltan is still released as a standalone package, and the standalone package uses autotools to build.  I am not an autotools expert, so I do not know how to fix this problem while allowing autotools to continue working.  If there is a way to make autotools work without these files, please let me know.  Thanks.

**Comment by nschloe** [comment]
The two files I mentioned are system-dependent and shipped by many Linux distros. In Debian/Ubuntu etc. you'll find them in `/usr/share/misc/`. Quoting from https://wiki.debian.org/AutoTools/autoconf:

> In general you are much better off building against the current versions of these files than the ones shipped with the tarball.

(The "current versions" are the ones in `/usr/share/misc/`.) Perhaps a good suggestion would be to rename `packages/zoltan/config/config.*` into `packages/zoltan/config/config.*.fallback` or so that the user can use if the system doesn't provide its own configs. What do you think?

**Comment by kddevin** [comment]
With just renaming those files, configure/make does not work. 
It appears autoreconf is then needed to get the system version of the files.
And autoreconf overwrites the existing files with the system version (which, on both my mac and my linux workstation, are identical to the existing versions).
Maybe there is some other magic needed for configure/make to just work?

**Comment by nschloe** [comment]
I've read up on autotools and found the following:

  * Most tarballs out there ship with autoconf files (like Zoltan does). This allows the user to to skip the step.
  * Debian guidelines recommend _not_ ship those files and let the user run `autoconf` (https://wiki.debian.org/Autoreconf):

    > Autoreconfing on build is good practice in Debian. There used to be good reasons to stick with the autotools files shipped in the upstream tarball (mostly incompatibility with newer versions), but these days good forward compatibility and the advantages of getting the latest updates for new architectures or other fixes means that autoreconfing on build should be the default in packages. [...]

Since those files aren't directly used in a CMake build, I'll simply ignore Debian rule 4.3 (see original post) and hope that the reviewers aren't too picky. This means nothing needs to change on the Zoltan side. In light of the above autoreconf guideline, perhaps you want to consider adopting this practice at some point though.

**Comment by kddevin** [comment]
Great!  Thanks, @nschloe
