### ISSUE TITLE
Building Trilinos/ROL takes 60GB of memory

### ISSUE THREAD

**Issue by dridzal** [trilinos/Trilinos#1514]
@trilinos/framework , if I build ROL with all its dependencies using

`  make -j20`

the maximum memory use for compiling/linking is more than 60GB.  In other words, 3GB per build process.  This is with GCC 4.8.4 and 6.1.0.  This has been getting worse; the high-end CEE LAN blades used to be able to compile ROL (just a few weeks ago) and now they can't (with make -j20).  The culprit are ROL's optional dependencies, specifically the new linear algebra and solver stack.

**Comment by ibaned** [comment]
@trilinos/rol

**Comment by mhoemmen** [comment]
@dridzal Could you please clarify that bit about "ROL's optional dependencies"?  I had thought ROL always had an optional dependency on the new linear algebra and solver stack.  I'm asking because I want to make sure this is about "adding a new dependency," and not about something that may have changed in the new stack suddenly causing larger build times.

**Comment by bartlettroscoe** [comment]
If ROL were to switch to using Stratimikos for these examples with ETI enabled, then my guess is that these build problems would go away.

@dridzal, if you have a few minutes, we could look over what might be involved in switching these ROL examples (at least the most problematic ones) to use Stratimikos.

**Comment by dridzal** [comment]
A few clarifications.

1) @mhoemmen : Unfortunately, this is not about adding a new dependency.  We haven't changed anything in how we use Tpetra, Amesos2, Ifpack2, MueLu, etc.  @dpkouri has informed me that within the last few weeks the memory requirements for building went up significantly.  So I think that this is in fact a case of the new stack suddenly causing larger build times.  He used to be able to build ROL with all its dependencies on his CEE LAN blade using make -j40, and now we run out of memory with make -j20.  On my workstation, memory use for make -j20 is more than 60GB.  I don't remember seeing anything close to this in the past.

How can I help you diagnose the issue?  I'm willing to run a bunch of builds with different git checkout points, but I would need some help in picking the appropriate ones.

2) @bartlettroscoe : We use ETI in our standalone builds.  Also, I hope that Trilinos' automated testing (checkin scripts, test harness scripts, etc.) use ETI.  Please confirm.

3) Our linear solver class is trivial, and simply includes Amesos2, Ifpack2 and MueLu headers, in addition to Tpetra.  How would the use of Stratimikos help?  Wouldn't we have to include the same files anyway?  For some parameter list options they are all used simultaneously.

**Comment by dridzal** [comment]
Another data point:  My Intel 17.0.1 build is taking approximately 100GB of memory with make -j20.

**Comment by dridzal** [comment]
Hmm, it looks like ETI is disabled by default for the builds that are submitted to CDash ... this is strange.  @bartlettroscoe , could you please verify this?  I searched through the 'Notes' on CDash for my builds and they first say

Trilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=OFF

and then

Trilinos_ENABLE_EXPLICIT_INSTANTIATION-ADVANCED:INTERNAL=1

I'm not sure what the difference is.  In any case, what is the default ETI policy for the checkin/cdash test scripts?

**Comment by mhoemmen** [comment]
@dridzal wrote:
> How can I help you diagnose the issue? I'm willing to run a bunch of builds with different git checkout points, but I would need some help in picking the appropriate ones.

Thanks for the offer of help!  If you still have the issue after resolving whether ETI is actually enabled, then you would have to bisect between "last known good" and "when you noticed it went bad," to find some range of possibly relevant commits.

This could relate to #1300 or #1444.

**Comment by mhoemmen** [comment]
@dridzal wrote:
> How would the use of Stratimikos help?

I think what Ross is trying to say, is that in general, hiding solver package includes from ROL is a good idea for reducing build times.  For example, if you know that an example needs a solver, and the example is not templated (examples really shouldn't be; they need to build, right?), then you can wrap all solver calls in your own interface, that is declared in a .hpp file and defined in a .cpp file.  That way, you'll build solvers (even if ETI is OFF) in a separate source file from where you use the solvers.

**Comment by bartlettroscoe** [comment]
> I think what Ross is trying to say, is that in general, hiding solver package includes from ROL is a good idea for reducing build times.

Exactly!  Thanks @mhoemmen!

I predict you will see a huge reduction in build times and memory consumption for these examples if you use a factory like Stratimikos::DefaultLinearSolverBuilder.  And the examples should be quite a bit shorter as well.

**Comment by mhoemmen** [comment]
Using Stratimikos is good.  However, even if you choose not to use Stratimikos, it would still pay to hide solver includes behind an opaque interface.  This would have the effect of protecting your example from whether or not (the rest of) Trilinos uses ETI.

**Comment by dridzal** [comment]
I've confirmed that my build, which was a slight modification of the standard CI build did not use ETI.  It was a typo in the SET_DEFAULT( EXTRA_CONFIGURE_OPTIONS ) block of one of the setup files.  I've fixed this, and ... **with ETI the memory footprint is the same, 60GB !!!**  Check this link to confirm that all relevant packages have ETI enabled:

https://testing.sandia.gov/cdash/viewNotes.php?buildid=3010054##note3

I would love to learn how to enforce ETI in my solver class, especially considering that the global Trilinos option doesn't seem to help.  The solver class is really, really simple, see:

https://github.com/trilinos/Trilinos/blob/develop/packages/rol/example/PDE-OPT/TOOLS/solver.hpp

This solver class is used by 20+ examples in ROL.  Who can give me instructions on how to do this?

**Comment by mhoemmen** [comment]
First, all the solvers should implement Trilinos::Details::LinearSolver (see teuchos/remainder/src/).  If they don't, then we need to fix that.  Your Solver class then only needs one of these:
```
Teuchos::RCP<Trilinos::Details::LinearSolver<Tpetra::MultiVector<...>, Tpetra::Operator<...>, typename Tpetra::MultiVector<...>::mag_type> solverImpl_;
```
You may even forward declare LinearSolver, if you don't want to include its header.

Second, does your solver class really need to be templated?  If not, then you can hide the complete implementation of your class' methods in a .cpp file.  If so, then surely you don't intend to support general `Real` types, but have some subset of Real types that you mean to support.  In that case, use C++11 `extern template` to avoid re-instantiating your Solver class.

**Comment by dridzal** [comment]
I don't understand why this will reduce the memory footprint.  Compiling any single example of the 20+ examples that use the solver class takes about 3GB of RAM.  Times 20 gives you 60GB.  There is no re-instantiation ... I think, so 3GB is the minimum for the new solver stack.  Or are you saying that this is really a combined compile/cmake issue, where we should build a single object file that is shared by a bunch of executables (and have this done accordingly in our cmake system)?  Just for reference, in ROL we never build an object file, it's all templated headers.  I guess we could settle on 'double' for the scalar type ...

**Comment by dridzal** [comment]
I'll work on having an explicit instance of this class.

Still, it is worrisome that a single new solver stack object takes 3GB of RAM to compile.  It may be useful to have a simple file that includes Tpetra, MueLu, Amesos2, Ifpack2, and to track its memory use and compile time.  What we believe happened in the last month is that the memory footprint went from about 1GB to 3GB for this single object.  This should be easy to test.  Continuously tracking the memory use and compile time will be harder. @mhoemmen @bartlettroscoe Do we have mechanisms for this type of testing?

**Comment by mhoemmen** [comment]
The more stuff you include and build in a single .cpp file, the more memory you will take in that file.  The point is to build less code per .cpp file.  That's why we went through so much effort splitting up instantiations into separate .cpp files.  "[A] simple file that includes Tpetra, MueLu, Amesos2, Ifpack2" is exactly the problem ;-) .  You can drive all those solvers from MueLu anyway, so there's actually no reason to include anything other than MueLu's basic interface.

**Comment by dridzal** [comment]
Sure, so can you point me to an example of how to organize my includes to minimize object code bloat -- beyond having an explicit instance, which I'm working on now?  If I, as a Trilinos developer, can't figure out a "good" way to use these solvers, then how can we ever expect end users to figure it out on their own.  Just to be clear, I need:

(1) run-time switching between different solvers, because for certain parts of the optimization algorithm I may want multigrid, for others I may be able to afford a full factorization;

(2) reuse of factorizations when I can afford to build them.

Is there an example where MueLu drives all this?  I'm OK with using Stratimikos as well, if it solves the ETI issues and is sufficiently flexible for my needs.

**Comment by mhoemmen** [comment]
I'm kinda busy now but send me a P/T and give me a schedule, and I can work with you on this.

**Comment by dridzal** [comment]
By splitting solver.hpp into (1) solver.hpp without the Trilinos solver includes, (2) solver_def.hpp with the includes, and (3) solver.cpp with ETI for <double>, I reduced the compiler memory footprint from 60GB to less than 30GB.  Thanks to @ambrad and @mhoemmen for help!

**Comment by mhoemmen** [comment]
Thanks @ambrad ! :D
