### ISSUE TITLE
build tpetra without tpetraclassic?

### ISSUE THREAD

**Issue by nschloe** [trilinos/Trilinos#1518]
To work around the effect of #933, is it possible to build Trilinos with Tpetra, but not TpetraClassic? Right now these two seem to be tied together.
```
   ***
   *** ERROR: Setting Trilinos_ENABLE_Tpetra=OFF which was 'ON' because Tpetra has a required library dependence on disabled package TpetraClassic!
   ***
```

**Comment by mhoemmen** [comment]
No.  Just leave it.  "TpetraClassic" is just a couple header and source files.  I haven't had time to merge it with TpetraCore, and nobody else offered to help.

**Comment by mhoemmen** [comment]
@trilinos/tpetra
