### ISSUE TITLE
Intrepid2 Kokkos-View-ization

### ISSUE THREAD

**Issue by bathmatt** [trilinos/Trilinos#152]
I am adding a github issue for the intrepid2 work for more simplicity of tracking.  

Summarizing the email below.  The initial step is to remove the two MD fields in intrepid2 and replace them with runtime rank kokkos views.  @etphipp has a prototype dimension structure which handles FAD objects.  

I'm adding all the poeple who have be involved in this in the past like
@eric-c-cyr @etphipp @crtrott @kyungjoo-kim @rppawlo 

Here are some facts which led us to where we are today.
1: Intrepid2 has a lot of its functionality which uses run time ranked arrays.

2: Intrepid2 has two different multi-dimensional arrays which are sort of interchangeable (The API between these two are not identical)
2A: Intrepid_FieldContainer.  This uses an ArrayRCP to store data and tracks dimensions and ranks and provides a multi->1D array. This can't be use in Kokkos functions
2B: Intrepid_FieldContainer_Kokkos, This uses a pointer and special code to allocate and reference data, but this does NOT use a kokkos::view under the hood.  This partially works with Kokkos, however, if you have a Intrepid_FC_K<Fad> this won't work on kokkos,

3: Phalanx has a MDField which wraps a true kokkos view, this should work on both CPU/GPU and with kokkos functions.  It should work with Kokkos, however, if it is using Fads, you need to take care to define the size when you great the MDField.  If not you will get an empty MDField becuase the view length is based on the Fad derivative length.

4: Intrepid2 uses arrays (field containers or some other MD array) of Fads for performing calculations like grads.  However, with either Kokkos:View, I_FC, or MDFields, this code will need to be modified so one defines the Fad length at decl.  The MDField could be used for this, however, the other FC won't perform on the GPU and can cause deadlocks due to allocations.

5: The Intrepid FC types don't roll the FAD derivative lengths into the view dimension.  This can make things slow

6:  ArrayWrappers.  These allow, in theory, one to send in a static sized array and use it in a dynamic sized array.  It often copies data to temps in/out of parallel regions.  These make it harder to debug and may not be needed.

7: We use the kokkos execution space based on the (first) array type passed into the function memory space

So, where do we go from here?  Here is how I see things.  Please

1: I still believe that we need to remove the Intrepid_FC classes and replace them with something like Phalanx::MDField, or better yet, Kokkos::MDView, which is a multi-dimensional array.

2: I think we need to remove all the array wrappers, we need to default to Kokkos::DefaultSpace

3: We need to make everything copy by value in Views,

4: We need to go through the 100 of basis types and fix up the Fad classes to make sure the length is known when we allocate temps.

This is a big undertaking, thankfully Intrepid2 has good test coverage.  I k now there will be some pushback on someof this, but we need to do something IMHO.  We need to figure how to move forward.

Matt

**Comment by bathmatt** [comment]
adding @ndellingwood

**Comment by bathmatt** [comment]
@ndellingwood is developing the Kokkoks runtime rank view, It should be ready by nexgt week.

@kyungjoo-kim will remove the [] operator from the intrepid code except cases where it is full vector operations.

@bathmatt will provide his first pass of the [] operator removal

@mperego @rppawlo will test this code in albany/drekar.

This should be done by next week

**Comment by rppawlo** [comment]
I think we also need @etphipp to verify sacado/fad works correctly through runtime rank view?

**Comment by etphipp** [comment]
Yes.

-Eric

On Feb 24, 2016, at 10:35 AM, rppawlo <notifications@github.com<mailto:notifications@github.com>> wrote:


I think we also need @etphipp<https://github.com/etphipp> to verify sacado/fad works correctly through runtime rank view?

-

**Comment by bathmatt** [comment]
I'm attaching a patch to get trilinos to compile and run the intrepid2 tests w/ the [] operator disabled.  In this example I have [] assert false.  I had to disable all the   switch(compEngine) blas routines.  
[operator.patch.txt](https://github.com/trilinos/Trilinos/files/145395/operator.patch.txt)

**Comment by mperego** [comment]
Hi,

I created the team Intrepid2, so if you do @trilinos/intrepid2 in your comment, Kyungjoo and I will receive emails. I can add some of you in the team if you like to.

Mauro

**Comment by rppawlo** [comment]
Action Plan:
1. 3/9: Kokkos dynamic rank views in Trilinos (Nathan and Christian)
2. 3/16: 
  - Phalanx switched to dynamic rank view and panzer calls to intrepid use kokkos views. (Roger)
  - Intrepid to integrate Matt's patch (Kyungjoo)

**Comment by mperego** [comment]
The deadlines look optimistic to me, so we do not promise to meet them.. but we'll try.

**Comment by rppawlo** [comment]
Thanks Mauro! Was just taking a stab at the dates. Feel free to edit the plan and add more details.

**Comment by mperego** [comment]
What's the status of the Drekar/Charon when Matt's patch is applied?

**Comment by rppawlo** [comment]
It is building now.  Should have results in about 2 hours.

**Comment by mperego** [comment]
Great, thanks!

**Comment by rppawlo** [comment]
Everything compiled but got a ton of failures in charon tests. Working on fixes now.

**Comment by mperego** [comment]
Thanks. Are these run on cpu?

**Comment by rppawlo** [comment]
yes - this is failing on cpu, not even gpu. Charon uses bracket ops (removed) and intrepid containers (which we also want to remove) in a bunch of physics operators. I am working on cleaning them up now.

**Comment by bathmatt** [comment]
Also, I ran the intrepid2 tests with the patch on cuda and they pass.

**Comment by mperego** [comment]
Great. Thanks.

**Comment by rppawlo** [comment]
I am down to one failing charon test. Will try to get it wrapped up tomorrow so we can push Matt's patch.

**Comment by rppawlo** [comment]
Charon2 is fixed. I started removing all use of intrepid container objects but without the experimental view and Eric P's new factory, this was going to be a ton of work. So I backed off and just removed all bracket operator use on Intrepid FieldContainer objects and everything is working. Will check the Panzer and Drekar tests tomorrow and update.

**Comment by rppawlo** [comment]
I just ran the Drekar tests and they also pass. So I think we are good to go on pushing Matt's patch to Intrepid2. Matt - in your patch you put an assert in the bracket operator to trigger a runtime failure.  Alternatively, should we just remove the bracket operator entirely at this point so that this becomes a compile time error instead? Much easier to track down.

**Comment by mperego** [comment]
Thanks Roger for testing this. 
I agree with you that it is better to remove entirely the bracket operator. 
After we agree on this I can commit the patch, unless Matt prefers to do so himself.

**Comment by bathmatt** [comment]
I dont recall why I went with the assert, but I am o.k, with removing it
completely.  We will have to remove all the blas code then and not just if
around it.

**Comment by mhoemmen** [comment]
I changed the title to try to make this issue's purpose more clear in the Kanban view.  Please feel free to change again if it's not right.

**Comment by mperego** [comment]
If we remove entirely the bracket operator we got several compilation errors in Intrepid2_FunctionSpaceToolsDef.hpp related to BLAS (case COMP_ENGINE_MAX). Are we sure we want to entirely remove the BLAS code as Matt suggested? Any reason why we want to keep the BLAS code?

**Comment by bathmatt** [comment]
I think the BLAS routines should be moved to Kokkos Kernels, as they are
general contraction operations.  Then we can have optimized kernels in the
future.

**Comment by mperego** [comment]
OK, I'll remove the BLAS routines if nobody objects.
Matt, what is COMP_ENGINE_MAX? It seems like you substituted COMP_BLAS with COMP_ENGINE_MAX but not everywhere. Should I get rid of them?

**Comment by bathmatt** [comment]
I did do that, it was a hack to disable it, I mentioned that I just if'ed them out and we should remove them if we are going to remove the blas routines.

Long term I still think these should be in kokkos kernels.

**Comment by kyungjoo-kim** [comment]
BLAS can be removed for now. In evaluation for lower order elements, BLAS cannot be effectively used and for Matt's use case (single particle evaluation), the BLAS cannot be used effectively either. In terms of performance, no one actually feel difference. COMP_ENGINE_MAX is an enum parameter to set the upper bound of the enum space. You can leave COMP_ENGINE_MAX in the routine.

In the very long long term, Teuchos::BLAS and LAPACK classes should be unified in Kokkos kernels possibly with considering different use cases (small problem sizes, large problem sizes, team interface etc.)

**Comment by bathmatt** [comment]
@srajama1 Adding Siva since there is talk (mostly by me) in adding the contraction routines to Kokkos Kernels and he is now the owner of that package.

**Comment by mhoemmen** [comment]
> In the very long long term, Teuchos::BLAS and LAPACK classes should be unified in Kokkos kernels possibly with considering different use cases (small problem sizes, large problem sizes, team interface etc.)

Maybe not _quite_ so long term.  Tpetra has its own small dense BLAS and LAPACK - style routines for BlockCrsMatrix.  The interface will likely evolve to allow for outer loop vectorization.  My guess is that the resulting evolution will make it work better on GPUs too (where it will become a "single thread" interface).

**Comment by mperego** [comment]
I removed the bracket operators and the BLAS routines (see attached patch including Matt patch).
The enum COMP_BLAS is still there and at the moment when using COMP_CPP and COMP_BLAS the same code is executed. This is a bit confusing, but if we want to avoid this and throw an error when COMP_BLAS is used we need to replace  COMP_BLAS with COMP_CPP in several Intrepid2 and panzer tests. This is doable but we may want to keep tests using COMP_BLAS for when we will resuscitate BLAS..

Roger, would you mind checking again Drekar and Charon for compilation errors?

[intrepid2_patch.txt](https://github.com/trilinos/Trilinos/files/163837/intrepid2_patch.txt)

**Comment by bathmatt** [comment]
I think that COMP_BLAS should throw an error and we should remove those tests.

**Comment by srajama1** [comment]
From the KokkosKernels perspective, this was going to be part of KokkosKernels. We would still like to consider integrating it when ready.

**Comment by mperego** [comment]
OK, I disabled all the intrepid tests using COMP_BLAS (but I did not remove them) and now COMP_BLAS will throw a runtime error.
Here is the updated patch.   I will commit it when Roger is OK with that.

[intrepid2_patch2.txt](https://github.com/trilinos/Trilinos/files/164074/intrepid2_patch2.txt)

**Comment by rppawlo** [comment]
If you make COMP_BLAS throw, then we will have to fix panzer tests and update the patch with those fixes. If you make COMP_BLAS default to to same as COMP_CPP then you could just push the patch (after I test/verify against drekar and charon). Either way is fine. @mperego does your new uploaded patch contains Matt's original patch of do I have to apply both separately?

**Comment by mperego** [comment]
Hi Roger,
I tested Panzer and all tests run correctly (-D Panzer_ENABLE_EXAMPLES:BOOL=ON, -D Panzer_ENABLE_TESTS:BOOL=ON). If compEngine==COMP_BLAS, an error get thrown any time compEngine is checked to be valid with 
TEUCHOS_TEST_FOR_EXCEPTION(  ~isValidCompEngine(compEngine) , .... ).

Please apply the updated patch below (I forgot to disable intrepid2 examples using BLAS in the one before).
It includes Matt's original patch, so you only need to apply this one. Thanks!

[intrepid2_patch3.txt](https://github.com/trilinos/Trilinos/files/164253/intrepid2_patch3.txt)

**Comment by rppawlo** [comment]
Hi Mauro,
Just pushed some minor changes to drekar and charon. All test are passing. Please feel free to push the changes. We are good to go!

**Comment by mperego** [comment]
Changes pushed! Mauro

**Comment by bathmatt** [comment]
@ndellingwood what is the status on the Kokkos multi-rank view?  Is there a ticket on the kokkos site to track this? I didn't see one.

**Comment by ndellingwood** [comment]
@bathmatt I am still working on the subview functionality for the multi-rank view (aka dynamic rank view) and expanding some of the subview functionality within the Experimental View for this, planning to have something tested this week within Kokkos (hopefully by Thursday). 

Here is the ticket link on the Kokkos site, most recent discussion was following push to develop branch of initial prototype without the subview functionality. 
[https://github.com/kokkos/kokkos/issues/189](url)

**Comment by bathmatt** [comment]
Is the plan to remove completely the intrepid field container once the kokkos run time rank view is working?  There are a few functions that are not in the kokkos view that are in the I2-FC, it might be good to keep it for the middle term and just use a Kokkos multi rank view under it and completely remove I2FC_Kokkos.  

Then add tests for the raw kokkos multi rank view.

Thoughts.?

**Comment by mperego** [comment]
About the temporary directory.. why you guys don't like branches? Likely, nobody except us is going to modify Intrepid2 or Phalanx, so a branch would be very easy to mantain..

**Comment by mperego** [comment]
I was just talking about this with Brent. It seems a reasonable option to me. Thanks.

**Comment by rppawlo** [comment]
Trilinos has a rule that we don't create branches in the main Trilinos 
repo.  Can you imagine if every developer (50+) were constantly dumping 
all their issue branches into the repo? We would be flooded with 
branches. There's no need for it anyway.  With github, you just fork the 
repo and you have your own copy where you can add as many branches as 
you like. If you would like me to fork and set up a branch for us all to 
use for the reffactor work, let me know.

-Roger

**Comment by mperego** [comment]
@rppawlo, thanks for offering, I think it would be nice to fork and have a branch for the refactor development. I can do that if you prefer.  
Is everybody OK with this? I do not want to force this.. if somebody is not at ease with working on a branch it's fine with me.

**Comment by ndellingwood** [comment]
The dynamic rank view with subview functionality is now available in the kokkos develop branch. 

The DynRankView code is located in kokkos/containers/src/Kokkos_DynRankView.hpp
Sample usage available in the unit tests kokkos/containers/src/TestDynViewAPI.hpp

A couple comments, including changes from Kokkos::View:

 1. Max rank of a DynRankView is 7
 2. The rank of the DynRankView is returned by the function rank()
 3. subdynrankview is the name for the function to create 'subviews' of dynamic rank views. 
 4. Every subdynrankview is returned with LayoutStride

**Comment by ndellingwood** [comment]
Enhancement for `subdynrankview` in `DynRankView` in Kokkos develop branch - 

Relaxed assumption that number of arguments to a `subdynrankview` must equal
the rank of the source `DynRankView` - a `subdynrankview` can now accept
greater number of arguments than the source `DynRankView`'s rank, the
additional are ignored.

**Comment by kyungjoo-kim** [comment]
Intrepid2 and Panzer are converted to DynRankView. Trilinos nightly test passes with the refactored version. So, I am closing this.
