### ISSUE TITLE
Tpetra: resumeFill+expertStaticFillComplete change triangular status

### ISSUE THREAD

**Issue by aprokop** [trilinos/Trilinos#1523]
@trilinos/tpetra @csiefer2 
```c++
    // construct A_crs_new
    std::cout << "A_crs_new is lower triangular: " << A_crs_new->isLowerTriangular() << std::endl;
    A_crs_new->resumeFill();
    A_crs_new->expertStaticFillComplete(A_crs_->getDomainMap(), A_crs_->getRangeMap());
    std::cout << "A_crs_new is lower triangular: " << A_crs_new->isLowerTriangular() << std::endl;
```
results in
```
A_crs_new is lower triangular: 1
A_crs_new is lower triangular: 0
```

I would have assumed that calling `expertStaticFillComplete` would just modify the importers/exporters, and not touch the internal state of the graph/matrix. But this does not seem to be the case.

I think the problem is that `resumeFill` resets `lowerTriangular_` and `upperTriangular_`, however it only calls `computeGlobalConstants()` and not `computeLocalConstants` where those variables are set.

Calling `expertStaticFillComplete` with a parameter list that has "compute global constants" set to false *does* call `computeLocalConstants`, however, it is shortcircuted by these lines in the function:
```c++
    // Short circuit
    if(haveGlobalConstants_) return;
    ...
    if (! haveLocalConstants_) {
```
The only way I could make it work is by commenting the first one, and resetting `haveLocalConstants_` in `expertStaticFillComplete`.

This seems like a real bug.

**Comment by mhoemmen** [comment]
Hm... Tpetra's support of post-fillComplete structure changes has always been iffy.  Does MueLu use any of that at all?  I would love to get rid of it and just force resumeFill not to reset any constants if the matrix has a static graph (which it does if fillComplete was called on it at least once before).

**Comment by mhoemmen** [comment]
@aprokop If you make those changes, do all the tests pass, including downstream tests?

**Comment by aprokop** [comment]
@mhoemmen No. This allowed passing of Ifpack2 tests, but crashed Nalu during Tpetra matrix assembly.

**Comment by csiefer2** [comment]
As you noted, ESFC triggers recomputation of the constants, etc.

**Comment by mhoemmen** [comment]
@csiefer2 How would you propose fixing this?  What would make sense in the context of ESFC?  If the matrix or graph has been fill complete before, then the structure should be fixed.

**Comment by csiefer2** [comment]
Do we actually enforce that now?  What, exactly does resumeFill allow you to do?  I never use it.

**Comment by mhoemmen** [comment]
"Enforce" would be a strong word.  MueLu used to depend on the "don't optimize storage" case of Crs*, and I think it still does, but I'm not even sure how that works, given that the column Map is fixed at first fill complete.

**Comment by csiefer2** [comment]
As per the doxygen, resumeFill allows you to change structure.

So it really should nuke all the constants.

**Comment by mhoemmen** [comment]
@csiefer2 wrote:
> So it really should nuke all the constants.

That would break the "reuse graph, change values" common use case.

**Comment by mhoemmen** [comment]
btw `CrsMatrix::resumeFill` does not clear either local or global constants if `isStaticGraph()` returns true, that is, if `myGraph_` is null.  However, `myGraph_` never seems to become _not_ null.  This should imply that it is possible to modify the graph after first fill complete, if the matrix owns its graph.  However, `CrsGraph::resumeFill` only clears local and global constants.  It does not reset any Maps, or the Import or Export objects (if applicable).  Thus, I don't think it's reasonable to say that structure changes after first fillComplete work as expected.

**Comment by mhoemmen** [comment]
#2630 means that CrsGraph and CrsMatrix will no longer know about their local triangular status.  However, that doesn't fix other local constants, like what `getNodeMaxNumEntries()` returns.

**Comment by mhoemmen** [comment]
PR #2696 may touch on this issue a bit.
