### ISSUE TITLE
Anyone using YAML literal block scalars?

### ISSUE THREAD

**Issue by ibaned** [trilinos/Trilinos#1526]
@trilinos/muelu 

I'm assuming that aside from Albany, MueLu is the only active user of Teuchos YAML ParameterList functionality.

Assuming this is true, I'm wondering whether MueLu makes any use of the "literal scalar" feature, which you can see below is being tested in Teuchos:

https://github.com/trilinos/Trilinos/blob/master/packages/teuchos/parameterlist/test/yaml/Match4.yaml#L4
```yaml
%YAML 1.1
---
Ninja Input:
  meshInput: |-

    mesh
      brick
       zmin = -1.0
       xmin = -1.0
       ymin = -1.0
       numz 1
         zblock 1 2.0 interval 8
       numx 1
         xblock 1 2.0 interval 20
       numy 1
         yblock 1 2.0 interval 20
      end
      set assign
         sideset, ilo, 1
         sideset, jlo, 2
         sideset, klo, 3
         sideset, ihi, 4
         sideset, jhi, 5
         sideset, khi, 6
      end
     user defined geometry transformation
     '
       double r = sqrt(inxcoord*inxcoord +inycoord*inycoord );
       double theta = atan2(inycoord,inxcoord); 
       if(r > 0.5)
       {
         theta = theta + (3.14159 / 4.0)*((r-0.5)/0.5);
         outxcoord = r*cos(theta);
         outycoord = r*sin(theta);
         outzcoord = outzcoord;
       }
     '
     end
    end
  mu0: 1.0
...
```

The reason for asking is I'm considering replacing the underlying YAML parser, and supporting features like these makes the parser significantly more complex.

**Comment by tawiesn** [comment]
@csiefer2 might know more.

**Comment by brian-kelley** [comment]
@ibaned That's a sample of an ALEGRA input deck, quoted verbatim in a multi-line string. That feature isn't used anywhere in MueLu, but I think ALEGRA and Drekar would need it.

**Comment by ibaned** [comment]
Thanks @brian-kelley, I'll follow up with developers of those codes.

**Comment by ibaned** [comment]
Okay, it looks like we probably want to keep this.
