### ISSUE TITLE
MueLu: problem with user parameter handling in MueLu Scaling Driver

### ISSUE THREAD

**Issue by tawiesn** [trilinos/Trilinos#1530]
Trying to set user parameters through the command line for MueLu_Driver results in errors like

> ./MueLu_Driver.exe : Error, the 1st option '--nx=10' was not recognized (use --help)!

The problem is, that the command line processor is defined in main, but the problem-specific parameters are set in the main_ routine. Nevertheless, the program runs fine, but the error message is misleading.

**Comment by pwxy** [comment]
This is no rush as the MueLu_Driver runs fine (other than the error).  I'll just ignore the error.

**Comment by aprokop** [comment]
@tawiesn Wait, it should work. We disable throw on unrecognized options in `main`.

**Comment by aprokop** [comment]
Oh, wait, I did not notice that the Driver was rewritten.

**Comment by aprokop** [comment]
I think the fix is simple: add
```c++
    clp.recogniseAllOptions(false);
```
in `MueLu_Test_ETI.hpp` before the `parse` command. I'll do a quick PR.

**Comment by tawiesn** [comment]
@aprokop: i've tried it and it makes the "error" to a "warning", but the output is still there. It seems the problem is that we have to add additional options after we have called the parse routine in the outer main routine (from MueLu_Test_ETI.hpp). Not sure what the best solution would be.

**Comment by aprokop** [comment]
The output can be disabled by changing `parse` to take in the 3rd `NULL` argument.

**Comment by aprokop** [comment]
Can we close this?

**Comment by pwxy** [comment]
Haven't had the chance to test this yet, but Andrey is always right.  Thanks Andrey.
