### ISSUE TITLE
Thyra::get_Epetra_MultiVector can hang in parallel if compiled with TEUCHOS_DEBUG

### ISSUE THREAD

**Issue by overfelt** [trilinos/Trilinos#1531]
Thyra in Trilinos 12.11 (Dev) can hang when compiled with TEUCHOS_DEBUG defined and run on 4 processors.  The following gtest code demonstrates the issue:
```C++
#include <iostream>

#include <gtest/gtest.h>

#include <Teuchos_RCP.hpp>
#include <Teuchos_DefaultComm.hpp>
#include <Epetra_MpiComm.h>
#include <Epetra_Map.h>
#include <Thyra_Version.hpp>
#include <Thyra_VectorSpaceFactoryBase.hpp>
#include <Thyra_EpetraThyraWrappers.hpp>
#include <Thyra_DefaultSpmdVectorSpace_decl.hpp>
#include <Thyra_DefaultSpmdVector_decl.hpp>
#include <Thyra_MultiVectorBase_decl.hpp>
#include <Thyra_ScalarProdVectorSpaceBase_decl.hpp>
#include <Thyra_DefaultSpmdMultiVector_decl.hpp>

/***
  If Thyra is compiled with TEUCHOS_DEBUG defined then the following with hang in a
  collective MPI communication if run on four processors.  
*/
TEST(TheraTest, DISABLED_HangingInParallelDebug)
{
   std::cout<<Thyra::Thyra_Version()<<std::endl;
#ifdef HAVE_MPI
   const Epetra_MpiComm epetra_comm(MPI_COMM_WORLD);
#else
   const Epetra_SerialComm epetra_comm();
#endif
   Teuchos::RCP<const Teuchos::Comm<Teuchos_Ordinal>> comm = Teuchos::DefaultComm<Teuchos_Ordinal>::getComm();
   const int num_procs = epetra_comm.NumProc();
   const int my_pid    = epetra_comm.MyPID();
  // Some processors have to have data and some not.
   const int localDim  = num_procs==1 ? 1 : my_pid%2; 
   const int globalDim = num_procs==1 ? 1 : num_procs/2; 
   Teuchos::RCP<const Epetra_Map>   epetra_map; 

   epetra_map = Teuchos::rcp(new Epetra_Map(globalDim,localDim,0,epetra_comm));
   Teuchos::RCP<Thyra::DefaultSpmdVectorSpace<double>> SPMD =    Thyra::DefaultSpmdVectorSpace<double>::create();
   SPMD->initialize(comm, localDim, globalDim);
   Teuchos::RCP<const Thyra::MultiVectorBase<double>> spmd = 
      Teuchos::rcp(
         new Thyra::DefaultSpmdMultiVector<double>(
            SPMD,
            Teuchos::rcp_dynamic_cast<const Thyra::ScalarProdVectorSpaceBase<double>>(
               SPMD->smallVecSpcFcty()->createVecSpc(1),true)
            )
        );
   Thyra::get_Epetra_MultiVector(*epetra_map,*spmd);
}
```

**Comment by ibaned** [comment]
@trilinos/thyra

**Comment by mhoemmen** [comment]
@overfelt I edited your post just to change the single backquotes to triple backquotes, so your post would format source code correctly.

**Comment by maherou** [comment]
@micahahoward has asked that we elevate the priority of this issue.  I have assigned it to @bartlettroscoe  for the analysis phase, at least.  I will also add this issue to the SART project board, in the backlog.

**Comment by micahahoward** [comment]
Can we revisit the status of this?

**Comment by bartlettroscoe** [comment]
I will try to get this this early next week.

**Comment by micahahoward** [comment]
@bartlettroscoe, @maherou, H=how's it going on this?  Our team would greatly appreciate this being fixed.

**Comment by mhoemmen** [comment]
@bartlettroscoe If you're too busy I can do it, don't worry :-) .  I was occupied by #1860 but may have a fix for that now, so please feel free to delegate to me.

**Comment by bartlettroscoe** [comment]
@mhoemmen,

> @bartlettroscoe If you're too busy I can do it, don't worry :-) . I was occupied by #1860 but may have a fix for that now, so please feel free to delegate to me.

Wow, that would be so fantastic.  I am trying to avoid being the bottleneck in too many activities so having some help with this would be great.  I have been pushing trying to get things in place for an upgrade of CMake/CTest/CDash upgrade that will allow us to effectively test Trilinos on the ATDM machines and have it posed and send out CDash emails so that Trilinos developers can be alerted in a targeted way and respond to failures quickly.

Thanks!

**Comment by mhoemmen** [comment]
@bartlettroscoe let me at it :-) no worries!  i will reassign to myself.

**Comment by mhoemmen** [comment]
Oops, I duplicated this issue in #1941.  I fixed this in develop.  Thanks to @overfelt for contributing the unit test; my commit https://github.com/trilinos/Trilinos/commit/646ca228903cb8d55f3d8038c3c0332cdd23512a added the unit test (with minor modifications) to Thyra.
