### ISSUE TITLE
Tpetra: Add CrsGraph & CrsMatrix constructors that take 4 Maps and a local graph / matrix

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#1536]
@trilinos/tpetra Requested by @aprokop .  See #1525.

@aprokop , at the point you would want to call these constructors, would you also happen to have the Import and Export objects if they are needed?  If so, the constructor should take them, to avoid reconstruction.

**Comment by aprokop** [comment]
@mhoemmen No, I do not construct import/export. The only thing I have are 4 maps: 2 permuted ones (row and column) and 2 original ones (domain, range). I would hope Tpetra would take care of everything else.

Do you want me to do a PR (WIP) for this issue? I would simply cherry-pick some commits from #1525.

**Comment by mhoemmen** [comment]
@aprokop wrote:
> Do you want me to do a PR (WIP) for this issue?

Could you please?  Thanks :-) !  It should be easy to add a test: Come up with an example with four distinct Maps, then build two matrices, one with the old (rowMap, colMap, local matrix) constructor and one with the new constructor.  Then, fill complete both, and test sameness (not pointer equality, we don't necessarily promise that) of Maps.

**Comment by aprokop** [comment]
@mhoemmen I cannot find a unit test for the existing constructor (2 maps + local matrix). Is there one? My hope was to copy-paste that one.

**Comment by mhoemmen** [comment]
The closest thing would be Lesson07, but I think it exercises the 2 Maps + three arrays constructor for CrsMatrix, not the 2 Maps + `local_matrix_type` constructor.

**Comment by aprokop** [comment]
Pushed to upstream. Thanks @mhoemmen.
