### ISSUE TITLE
Tpetra: CUDA 7.5 build error with Kokkos lambda

### ISSUE THREAD

**Issue by brian-kelley** [trilinos/Trilinos#1537]
@trilinos/tpetra
I am working on a Tpetra CrsMatrix addition kernel using Kokkos. I am trying to get the algorithm working on geminga with CUDA enabled. Building Tpetra fails however (sortCrsEntries in Tpetra_Import_Util2.hpp):
~~~~
/home/bmkelle/MatrixAddWork/Trilinos/packages/tpetra/core/src/Tpetra_Import_Util2.hpp(1164): error: expected a "{" introducing a lambda body
/home/bmkelle/MatrixAddWork/Trilinos/packages/tpetra/core/src/Tpetra_Import_Util2.hpp(1164): error: expected a ")"
/home/bmkelle/MatrixAddWork/Trilinos/packages/tpetra/core/src/Tpetra_Import_Util2.hpp(1185): warning: parsing restarts here after previous syntax error
/home/bmkelle/MatrixAddWork/Trilinos/packages/tpetra/core/src/Tpetra_Import_Util2.hpp(1186): error: identifier "sk" is undefined
/home/bmkelle/MatrixAddWork/Trilinos/packages/tpetra/core/src/Tpetra_Import_Util2.hpp(1186): error: identifier "itemp" is undefined
~~~~
This is with CUDA 7.5.18, so I'm not surprised that a Kokkos lambda fails to compile, but I know it should be possible to build Tpetra with that version. Should this be converted to a functor?
[Here is my configure script](https://gist.github.com/brian-kelley/d3a6070f21f5fb0e91ac42c165b186c4) and [here is the set of modules loaded](https://gist.github.com/brian-kelley/f95e0c8266648a1292dc6d7387fd7e73). The exact build command was:
~~~~
make -j20 KOKKOS_DEVICES=Cuda
~~~~

**Comment by mhoemmen** [comment]
Could you please upgrade to CUDA 8 and try again?

**Comment by mhoemmen** [comment]
In general, we are phasing out support for CUDA 7.5.

**Comment by ibaned** [comment]
Also, be sure to set the following in your CMake configuration:
```
-DKokkos_ENABLE_Cuda_Lambda:BOOL=ON
```
If Tpetra is starting to rely on lambdas, we may want to add a CMake check to ensure that boolean is on when Tpetra is built with CUDA support.

**Comment by ibaned** [comment]
Looking at your script you've thrown `-DKOKKOS_CUDA_USE_LAMBDA=1` into `CMAKE_CXX_FLAGS`, which is a dubious way of trying to achieve the same effect.

**Comment by mhoemmen** [comment]
> If Tpetra is starting to rely on lambdas, we may want to add a CMake check to ensure that boolean is on when Tpetra is built with CUDA support.

I think that makes sense.  We already have been requiring CUDA 7.5, and Sierra only tests with CUDA >= 8.0.

**Comment by brian-kelley** [comment]
I switched to CUDA 8.0.44, and now there's a different error on the same lambda:
~~~~
/home/bmkelle/MatrixAddWork/Trilinos/packages/kokkos/core/src/Cuda/Kokkos_CudaExec.hpp(287): error: The closure type for a lambda ("lambda [](size_t)->void") cannot be used in the template argument type of a __global__ function template instantiation, unless the lambda is defined within a __device__ or __global__ function, or the lambda is a 'extended lambda' and the flag --expt-extended-lambda is specified
          detected during:
            instantiation of "Kokkos::Impl::cuda_parallel_launch_local_memory" based on template argument <Kokkos::Impl::ParallelFor<lambda [](size_t)->void, Kokkos::RangePolicy<Kokkos::CudaSpace::execution_space, size_t>, Kokkos::CudaUVMSpace::execution_space>>
(287): here
            instantiation of "Kokkos::Impl::CudaParallelLaunch<DriverType, false>::CudaParallelLaunch(const DriverType &, const dim3 &, const dim3 &, int, cudaStream_t) [with DriverType=Kokkos::Impl::ParallelFor<lambda [](size_t)->void, Kokkos::RangePolicy<Kokkos::CudaSpace::execution_space, size_t>, Kokkos::CudaUVMSpace::execution_space>]"
/home/bmkelle/MatrixAddWork/Trilinos/packages/kokkos/core/src/Cuda/Kokkos_Cuda_Parallel.hpp(366): here
            instantiation of "void Kokkos::Impl::ParallelFor<FunctorType, Kokkos::RangePolicy<Traits...>, Kokkos::Cuda>::execute() const [with FunctorType=lambda [](size_t)->void, Traits=<Kokkos::CudaSpace::execution_space, size_t>]"
/home/bmkelle/MatrixAddWork/Trilinos/packages/kokkos/core/src/Kokkos_Parallel.hpp(190): here
            instantiation of "void Kokkos::parallel_for(const ExecPolicy &, const FunctorType &, const std::string &, Kokkos::Impl::enable_if<<expression>, void>::type *) [with ExecPolicy=Kokkos::RangePolicy<Kokkos::CudaSpace::execution_space, size_t>, FunctorType=lambda [](size_t)->void]"
/home/bmkelle/MatrixAddWork/Trilinos/packages/tpetra/core/src/Tpetra_Import_Util2.hpp(1192): here
~~~~

**Comment by mhoemmen** [comment]
@brian-kelley I'll send you my `do-configure` script for CUDA builds.  What host compiler are you using?

**Comment by brian-kelley** [comment]
@mhoemmen I'm using GCC 4.9.3 with OpenMPI 2.0.1.

**Comment by mhoemmen** [comment]
@jhux2 I would prefer not to post it unredacted but I'll be happy to e-mail it to you.

**Comment by ibaned** [comment]
try only using one dash in front: `-expt-extended-lambda`. this is a really weird inconsistency with CUDA. later versions accept the double dash, but some versions of `nvcc_wrapper` don't, anyway its a mess

**Comment by brian-kelley** [comment]
@mhoemmen I have the checkin test script doing a configure/build/test based on your script (it's in the build right now, so that's a good sign). @ibaned If that fails during the build or at runtime I'll try your suggestion with my own configure script.

**Comment by mhoemmen** [comment]
@brian-kelley Note that my CUDA build turns off the Serial Node.  You could also try modifying my build to enable the Serial Node as well as the Cuda Node, to see if that manifests the error.

**Comment by brian-kelley** [comment]
@mhoemmen I think your script is working. I now get a build error in my own functor where Kokkos and Tpetra each have their own std::complex wrapper which are incompatible with each other (I'm trying to add them). So fixing that's up to me, and I think everything else is working. Thanks!

**Comment by mhoemmen** [comment]
@brian-kelley wrote:
> ... where Kokkos and Tpetra each have their own std::complex wrapper which are incompatible with each other ....

Could you clarify?  Tpetra should just use Kokkos::complex.

**Comment by brian-kelley** [comment]
@mhoemmen The exact error was:
~~~~
/home/bmkelle/MatrixAddWork/Trilinos/packages/tpetra/core/ext/TpetraExt_MatrixMatrix_def.hpp(1045): error: no operator "+=" matches these operands
            operand types are: Tpetra::std_complex0double0 += Kokkos::complex<double>
~~~~
I haven't really looked into it yet since I'm now profiling and modifying the same code on KNL.

**Comment by mhoemmen** [comment]
@brian-kelley Here are the rules for complex:

1. Never use `std::complex` inside a `Kokkos::parallel_*`.
2. Use `impl_scalar_type` (in this case, `Kokkos::complex`) not `scalar_type` / `Scalar`.
3. You may assume that `Kokkos::complex` and `std::complex` share the same bit representation.

**Comment by brian-kelley** [comment]
@mhoemmen Yes, I think just changing that to impl_scalar_type will fix it.
