### ISSUE TITLE
Panzer: Add unique identifiers to worksets

### ISSUE THREAD

**Issue by eric-c-cyr** [trilinos/Trilinos#1539]
It would be good to have a unique identifier for each workset. This would be constructed from the WorksetDescriptor to be locally unique (with a set of Worksets defined by the descriptor). If you want a globally unique set of worksets, they could be constructed by a unordered_map.

**Comment by eric-c-cyr** [comment]
Is it clear how to convert in both directions Kokkos::DynRankView <=> PHX::MDFields?

**Comment by eric-c-cyr** [comment]
Also, I'm refactoring the PointValues2 class some to be more consistent with BasisValues2 and IntegrationValues2. As part of that I'm going to collapse the NODE tag into the BASIS tag. Anyone see a problem with this? Clearly this will require testing.

**Comment by eric-c-cyr** [comment]
In retrospect, I don't have to do change NODE to BASIS, though I could if people think its a good idea.

**Comment by rppawlo** [comment]
I like the idea of changing node to basis. One less branch for possible divergence/code duplication.

**Comment by eric-c-cyr** [comment]
Alright @rppawlo, my next merge commit will do this. Basically, NODE will be aliased to BASIS. We can do the sed script to totally eliminate it after that.

**Comment by eric-c-cyr** [comment]
There are a few things to be done first before the core of this issue:

- [ ] Add point descriptor
- [ ] Convert point values to be more like basis values (no longer dependent on a templated array type, going straight to MDField)
- [ ] Add point values to workset for evaluation of basis points
- [ ] Add unique identifier to workset
