### ISSUE TITLE
Intrepid2 test uses BasisSet and shouldn't

### ISSUE THREAD

**Issue by bathmatt** [trilinos/Trilinos#154]

**Comment by kyungjoo-kim** [comment]
All the modification for high order assembly is wrapped by a macro INTREPID_USING_EXPERIMENTAL_HIGH_ORDER. If you don't turn it on, all tests will be bypass the unit tests for the high order assembly.

**Comment by bathmatt** [comment]
Then why is it trying to compile this and failing?

**Comment by kyungjoo-kim** [comment]
Sorry I forgot the wrap on the help functions on the  test 04. It is fixed now. I checked that Intrepid2 pass all the tests on my machine without the high order macro.
