### ISSUE TITLE
PyTrilinos: compiling with conda: ../../util/copyWithCMakeSubstitutions.py: not found

### ISSUE THREAD

**Issue by looooo** [trilinos/Trilinos#1540]
reported problem:
```
/bin/sh: ../../util/copyWithCMakeSubstitutions.py: not found
```
https://github.com/trilinos/Trilinos/blob/master/packages/PyTrilinos/src/scripts/CMakeLists.txt#L46
The file `copyWithCMakeSubstitutions.py` was already created, so I think the path is wrong somehow.

Maybe this is conda specific. This is the first line of my `copyWithCMakeSubstitutions.py`:

```
!# /home/lo/conda/conda-bld/trilinos_1501156568034/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/bin/python2.7
```

Running `./copyWithCMakeSubstitutions.py` manually result in:
```./util/copyWithCMakeSubstitutions.py
bash: ./util/copyWithCMakeSubstitutions.py: /home/lo/conda/conda-bld/trilinos_1501156568034/_b_env_placehold_placehold_p: Defekter Interpreter: File or directory not found
```
To me it seems like the path to the interpreter is too long.

**Comment by looooo** [comment]
This patch solves my issue. Maybe someone else can test it.
https://github.com/looooo/conda_recipes/blob/master/trilinos/python.patch

**Comment by aprokop** [comment]
@wfspotz

**Comment by wfspotz** [comment]
Interesting. I have been working on a PyTrilinos installer on conda-forge:

https://github.com/wfspotz/staged-recipes/tree/master/recipes/pytrilinos

I developed a very similar patch, although mine also fixes a test script.

**Comment by looooo** [comment]
thanks for the information. I will try the conda-forge recipe. Was the PyTrilinos recipe allready accepted as a conda-forge feedstock?

**Comment by wfspotz** [comment]
It has been accepted now, although the Linux version is not working. I got it to work prior to the pull request acceptance, but now it (Circe-CI) is failing, and I can't get it to report why.

**Comment by looooo** [comment]
The package is build but the upload is not working. Maybe try to re-render the feedstock.
