### ISSUE TITLE
Framework: Upgrade the buld Linux-GCC-4.7.2-CONTINUOUS_MPI_OPT_DEV_SHARED to GCC 4.8.4 or disable

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#1541]
**CC:** @trilinos/framework 

**Description:**

The build `Linux-GCC-4.7.2-CONTINUOUS_MPI_OPT_DEV_SHARED` with configure output shown at:

* https://testing.sandia.gov/cdash/viewConfigure.php?buildid=3022476

is still using GCC 4.7.2 shown by:

```
-- CMAKE_C_COMPILER_ID='GNU'
-- CMAKE_C_COMPILER_VERSION='4.7.2'
-- CMAKE_CXX_COMPILER_ID='GNU'
-- CMAKE_CXX_COMPILER_VERSION='4.7.2'
```

Trilinos is no longer supports C++11 builds of Trilinos with GCC versions less than 4.8.4 (see #1453).  Therefore, this build needs to be upgraded to GCC 4.8.4.  Until this build can be updated, it should be disabled.  See history in https://github.com/trilinos/Trilinos/issues/1304#issuecomment-318357060.

**Comment by jwillenbring** [comment]
@william76 Can you take a look at doing this? I know we are trying to also move the build and have not yet, but the 4.7.2 build isn't helping us anymore. We could just temporarily update the existing build to 4.8.4 otherwise too.

**Comment by bartlettroscoe** [comment]
Since the CI build `Linux-GCC-4.8.4-MPI_RELEASE_DEBUG_SHARED_PT_CI` run on `ceerws1113`  is covering a CI build, you could disable this other build until it gets updated.  I don't think there is a single example of a case where the `Linux-GCC-4.7.2-CONTINUOUS_MPI_OPT_DEV_SHARED` build caught a problem that the `Linux-GCC-4.8.4-MPI_RELEASE_DEBUG_SHARED_PT_CI` build did not.

**Comment by mhoemmen** [comment]
ping?

**Comment by bmpersc** [comment]
@mhoemmen I don't think we've had a 4.7.2 build continuous build for quite some time. It looks like it was changed to 4.9.3 back in august. So I think this should just be closed. Do you have any specific concerns with the 4.7.2 builds anymore?

**Comment by mhoemmen** [comment]
@bmpersc There is a GCC 4.7.2 build on the Dashboard, on ascic114, listed under the Experimental builds.  How can I get rid of that one?
