### ISSUE TITLE
Zoltan2 CUDA build error

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#1546]
@trilinos/zoltan2 

I get the following build error with CUDA 8.0 and GCC 4.8.4:
```
.../Trilinos/packages/zoltan2/test/helpers/GeometricGenerator.hpp: In constructor ‘GeometricGen::GeometricGenerator<T1, T2, T3, T4>::GeometricGenerator(Teuchos::ParameterList&, const Teuchos::RCP<const Teuchos::Comm<int> >&)’:
.../Trilinos/packages/zoltan2/test/helpers/GeometricGenerator.hpp:1812:1: error: for statement expected before ‘case’
       case 1:
 ^
.../Trilinos/packages/zoltan2/test/helpers/GeometricGenerator.hpp:1820:1: error: for statement expected before ‘case’
       case 2:
 ^
.../Trilinos/packages/zoltan2/test/helpers/GeometricGenerator.hpp:1828:1: error: for statement expected before ‘case’
       case 3:
 ^
```

**Comment by mndevec** [comment]
Thanks for the report Mark.
Does the configuration enable OpenMP in Zoltan2?

**Comment by mhoemmen** [comment]
@mndevec wrote:
> Thanks for the report Mark.

Gladly! :-)

> Does the configuration enable OpenMP in Zoltan2?

Not explicitly, but it looks like Zoltan2's OpenMP support got turned on implicitly.  This is a CUDA build with _only_ the CUDA Node type enabled, but the host compiler has OpenMP turned on.  See full list of related CMake variables below.  
```
KokkosKernels_INST_EXECSPACE_OPENMP:BOOL=ON
Kokkos_ENABLE_OpenMP:BOOL=ON
OpenMP_CXX_FLAGS:STRING=-fopenmp
Stokhos_ENABLE_OpenMP:BOOL=ON
TpetraClassic_ENABLE_OpenMPNode:BOOL=OFF
Trilinos_ENABLE_OpenMP:BOOL=ON
Zoltan2_ENABLE_OpenMP:BOOL=ON
Tpetra_INST_OpenMP:BOOL=OFF
```

**Comment by mhoemmen** [comment]
Alas, this is blocking #1569.  @tjfulle would very much like to test downstream but it's a bit hard to make sure that all the tests build and pass without Zoltan2.

**Comment by mhoemmen** [comment]
A work-around that lets us test CUDA would be acceptable.

**Comment by mndevec** [comment]
Mark, I am unable to reproduce the error on white with cuda 8 and gcc 5.4. White does not have gcc 4.8 compiler. Which machine are you running it on?

I will try to compile it again on hansen. In the meantime, could you comment out the pragma lines and see if that helps for now?

**Comment by mndevec** [comment]
Mark, I believe this is an issue with NVCC openmp parsing. I added curly braces around of pragmas. 
Let me know if it still fails for you.

**Comment by mhoemmen** [comment]
Thanks @mndevec !  I'll give this a try.

**Comment by mhoemmen** [comment]
It builds now -- thanks @mndevec !
