### ISSUE TITLE
Panzer:  Forward Declarations in panzer Namespace

### ISSUE THREAD

**Issue by jmgate** [trilinos/Trilinos#1548]
Ensure forward declarations in header files are inside the `panzer` namespace.  Also ensure they're actually needed when included. @trilinos/panzer

**Comment by jmgate** [comment]
@rppawlo, @eric-c-cyr, in working on this task I've found a handful of

```c++
using namespace Sacado::mpl::placeholders;
```

in the global namespace in our files.  Questions:

1. Do we want these `using namespace` directives in our code?  I've always heard that was a bad thing.  I could replace them with particular `using Sacado::mpl::placeholders::thing`s for whatever we actually need to use.
1. If we do, I assume we want those directives within the `panzer` namespace, correct?

**Comment by eric-c-cyr** [comment]
In general, I'm okay if they are not in a user header file (the injection into the global namespace is not practically realized). Though sometimes in template meta programming you need these. So if it builds without the using statement, I'd say its fine to remove it.

**Comment by jmgate** [comment]
@eric-c-cyr, I was able to take out the `using`s and everything compiled and ran just fine.
