### ISSUE TITLE
Match Ifpack2 parameters to the Ifpack2 Thyra adapter parameters (or other way)

### ISSUE THREAD

**Issue by srajama1** [trilinos/Trilinos#155]
As the subject says the parameters don't match. Overlap vs "schwarz : overlap". "Prec Type" and "Ifpack2 Settings" are not recognized in Ifpack2, but just by the adapter.

I don't see a good reason why they don't match. 

Furthermore, users are setting "Prec Type" to RILUK whereas it appears what is expected is for them to set it to Schwarz.  The thyra adapter assumes whatever they set for "Prec Type" is going to be a Schwarz method. Lots of inconsistenices here.

@trilinos/ifpack2 @mhoemmen @eric-c-cyr 

Needed for`<unnamed project>` milestone.

**Comment by aprokop** [comment]
An example from an input deck in Drekar:
```
<ParameterList name="Ifpack2">
    <Parameter name="Prec Type" type="string" value="SCHWARZ"/>
    <Parameter name="Overlap"   type="int"    value="0"/>   <!-- ignored due to presence of "schwarz: overlap level" below -->
    <ParameterList name="Ifpack2 Settings">
        <Parameter      name="schwarz: overlap level"       type="int"      value="1"/>
        <Parameter      name="schwarz: combine mode"        type="string"   value="Zero"/>
        <Parameter      name="subdomain solver name"        type="string"   value="RILUK"/>

        <Parameter      name="schwarz: use reordering"      type="bool"     value="0"/>
        <ParameterList  name="schwarz: reordering list">
            <Parameter  name="order_method"                 type="string"   value="rcm"/>
        </ParameterList>
    </ParameterList>
</ParameterList>
```

It is very subtle. For instance, the `Overlap` parameter is ignored if `schwarz:overlap level` is present in the `Ifpack2 Settings`. Some of the parameters are not even registered with validator.

I would also like to see it resolved as a user.

**Comment by jhux2** [comment]
> As the subject says the parameters don't match. Overlap vs "schwarz : overlap". "Prec Type" and "Ifpack2 Settings" are not recognized in Ifpack2, but just by the adapter.
> 
> I don't see a good reason why they don't match.
> 
> Furthermore, users are setting "Prec Type" to RILUK whereas it appears what is expected is for them to set it to Schwarz. The thyra adapter assumes whatever they set for "Prec Type" is going to be a Schwarz method. Lots of inconsistenices here.

The adapter settings should change, IMO.   Sierra, for example, bypasses the Thyra examples entirely.

In fact, why should the Thyra adapters be translating parameters, or do any validation of Ifpack2 parameters -- shouldn't Thyra pass them directly to Ifpack2 to validate?

**Comment by srajama1** [comment]
I saw a variation of the Drekar i/p deck and assumed it will do something, when in fact it didn't do that. That is the reason for this issue.

Totally agree with the view the view that the adapters need to change. Mark has the most changes in these factories. I'll wait for him to respond.

I don't know what does it mean to set preconditioner type to RILUK in an MPI mode. Is it block jacobi with RILUK locally ? We should avoid these implicit usage.

**Comment by jhux2** [comment]
> I don't know what does it mean to set preconditioner type to RILUK in an MPI mode. Is it block jacobi with RILUK locally ? We should avoid these implicit usage.

Yes, it means additive Schwarz with RILUK subdomain solves.  Using the Ifpack2 parameter settings as Andrey showed in the sample input deck, this is explicit.

**Comment by aprokop** [comment]
I don't think that's right. If you set `Prec Type` to RILUK, it bypasses Additive Schwarz. Instead, inside `RILUK` (or rather `IlukGraph`) it constructs an overlapped graph through `createOverlapGraph` routine.

**Comment by jhux2** [comment]
> I don't think that's right. If you set Prec Type to RILUK, it bypasses Additive Schwarz. Instead, inside RILUK (or rather IlukGraph) it constructs an overlapped graph through createOverlapGraph routine.

But isn't that the moral equivalent of additive Schwarz, even though it doesn't use the Schwarz?

**Comment by srajama1** [comment]
Thanks, Andrey. That is what I was looking for. Why we support that mode is still a mystery though.

I am guessing  "Overlap" is for this usecase and  "schwarz: overlap" is for the other use case ?

**Comment by aprokop** [comment]
> But isn't that the moral equivalent of additive Schwarz, even though it doesn't use the Schwarz?

It is, but it is an alternative code path, and as Siva, I have trouble figuring out why we have both.

> I am guessing "Overlap" is for this use case and "schwarz: overlap" is for the other use case ?

Probably? We really need more clarity, as I cannot answer any of these questions without looking at the code.

**Comment by srajama1** [comment]
@mhoemmen : Any thoughts ?

**Comment by csiefer2** [comment]
Historical Perspective:  Nobody used the Thyra wrappers for Ifpack2 when it was initially developed.  They were not implemented by the primary Ifpack2 developers.  Therefore, it is no surprise that the Thyra options are completely inconsistent with the Ifpack2 options.

My opinion:  Forcing the Thyra options to match Ifpack2's and modifying Drekar tests/examples accordingly seems to be the minimum effort approach.

**Comment by eric-c-cyr** [comment]
Yes, I agree with Chris. Lets do whats right for Ifpack2

**Comment by jhux2** [comment]
Siva,
   How quickly do you need this resolved?
Jonathan

**Comment by srajama1** [comment]
I am looking at the code to see if I can give Matt B. a starting deck so he can test something.

It appears from the code
<Parameter name="Prec Type" type="string" value="RILUK"/>
will create the overlap graph. However,

<Parameter name="Prec Type" type="string" value="SGS"/>
has no option to create the overlap graph. How do you use Muelu with SGS with overlap of 1.

If I have that option then he can start somewhere and we can clean this up and request him to change his input deck.

**Comment by aprokop** [comment]
@srajama1
Something like this:
```
<ParameterList name="Ifpack2">
    <Parameter name="Prec Type" type="string" value="SCHWARZ"/>
    <Parameter name="Overlap"   type="int"    value="0"/>   <!-- ignored -->
    <ParameterList name="Ifpack2 Settings">
        <Parameter      name="schwarz: overlap level"           type="int"      value="1"/>
        <Parameter      name="schwarz: combine mode"        type="string"   value="Zero"/>
        <Parameter      name="subdomain solver name"        type="string"   value="RELAXATION"/>
        <ParameterList name="subdomain solver parameters">
            <Parameter  name="relaxation: type" type="string" value="Symmetric Gauss-Seidel"/>
        </ParameterList>
    </ParameterList>
</ParameterList>
```

**Comment by srajama1** [comment]
Thanks. That looks reasonable and may even work with Thyra. I will start with that.

**Comment by bartlettroscoe** [comment]
Is there no PL valuation going on in this subclass?  I don't remember writing an Ifpack2 Thyra adapter.

**Comment by srajama1** [comment]
May be a stupid question : What is PL valuation ? 

See Chris's comments above. This was not written by Ifpack2 developers or thyra developers for that case.

**Comment by bartlettroscoe** [comment]
> What is PL valuation ? 

"PL validation" = "ParameterList Validation".  See item "GCG 17: Fully validate all parameters and sublists in accepted Teuchos::ParameterList objects using validatePamaters(...) and other means" in the document:

    http://web.ornl.gov/~8vt/TrilinosCodingDocGuidelines.pdf

(NOTE: That effort kind of died when there was some minority push back, like what happens with all Trilinos improvement efforts.)

All of the subclasses I wrote that derive from Teuchos::ParameterListAccepter fully validate their inputs (at least for the sublists and parameters that these subclasses control).  See slides 17-23 in the presentation:

    http://web.ornl.gov/~8vt/StratimikosOverview_HPCSW2008.pdf

Is no other software in Trilinos validating their PLs? This is a major usability issue (ccing @wfspotz).

**Comment by srajama1** [comment]
Ok, didn't realize it was a typo. We do validate in different packages, just not consistently.

**Comment by bartlettroscoe** [comment]
Sorry, "validation" not "valuation".  Don't know how I missed that :-)

**Comment by mhoemmen** [comment]
@bartlettroscoe There was a big debate circa 2011 about a common interface for ParameterList parsing.  We agreed to disagree.  Not everybody likes the semantics of ParameterListAccepter.  For example, taking and returning the ParameterList by RCP implies that implementations keep the original one, which implies statefulness that not all implementations want to have.

**Comment by bartlettroscoe** [comment]
> There was a big debate circa 2011 about a common interface for ParameterList parsing. We agreed to disagree.

I don't remember such a conversation.  When did this discussion take place?  Is it documented on an email list?  Is it documented in a Bugzilla ticket?

> Not everybody likes the semantics of ParameterListAccepter. For example, taking and returning the ParameterList by RCP implies that implementations keep the original one, which implies statefulness that not all implementations want to have. 

The semantics of Teuchos::ParameterListAccepter were modeled after how NOX uses parameter lists.  Since NOX had them first and since those semantics have some advantages, I decided to model Teuchos::ParameterListAccepter after NOX usage.

The people who really suffer with the mess of different PL semantics, lack of validation, etc. are the users.  For many users, the PL XML file and the semantic usage of PLs is the primary way they interact with Trilinos.  Those people are seeing very bad situation right now I suspect.

I think this conversation needs to be opened up again.  @wfspotz, what do you think about this and the User Experience lead?

**Comment by mhoemmen** [comment]
> > There was a big debate circa 2011 about a common interface for ParameterList parsing. We agreed to disagree.
> I don't remember such a conversation. When did this discussion take place? Is it documented on an email list? Is it documented in a Bugzilla ticket?

It was a spring Trilinos developers' meeting.  Jeremie et al. were there.  It's not even correct to say we "agreed to disagree"; we simply came to no agreement.

**Comment by mhoemmen** [comment]
> I think this conversation needs to be opened up again. @wfspotz, what do you think about this and the User Experience lead?

Let's not talk too much.  Last time we had a big debate, it got nowhere.  I can argue semantics for days without sleep ;-P  I'm willing to accept ParameterListAccepter semantics, as long as they don't actually require keeping _the_ _original_ input or valid PL (i.e., can (re)create either on demand).  PL is a stateful thing and RCP<PL> is a thread scalability bottleneck (as would be std::shared_ptr<PL>).
