### ISSUE TITLE
Cannot disable Fortran compiler

### ISSUE THREAD

**Issue by slicer69** [trilinos/Trilinos#1550]
When trying to build Trilinos, I attempted to disable the Fortran compiler, using the example in the build documentation. When I run

mkdir build
cd build
cmake -DTrilinos_ENABLE_FORTRAN=OFF ../Trilinos/

I get the following error saying the Fortran compiler could not be found and cmake exits. This test should be skipped since I explicitly disabled the Fortran option.

-- The Fortran compiler identification is unknown
CMake Error at cmake/tribits/core/package_arch/TribitsGlobalMacros.cmake:1773 (ENABLE_LANGUAGE):
  No CMAKE_Fortran_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "FC" or the CMake cache entry CMAKE_Fortran_COMPILER to the full
  path to the compiler, or to the compiler name if it is in the PATH.
Call Stack (most recent call first):

**Comment by jhux2** [comment]
@slicer69 cmake is case sensitive.  The correct option is ```-DTrilinos_ENABLE_Fortran:BOOL=OFF```.   Which build documentation were you looking at?   It may need to be fixed.

**Comment by slicer69** [comment]
I copied the Fortran option from the INSTALL.rst file in the Trilinos documentation. It's under section 3 "Useful Options". https://github.com/trilinos/Trilinos/blob/master/INSTALL.rst

**Comment by ibaned** [comment]
@slicer69 I've just pushed commit c87326b6a58f587b72e0c50bb8fb662c54a5a7c9 to the develop branch which should fix the typo in the documentation. I believe one other person was bitten by this before you...
Thanks for pointing this out!

I'm going to close this issue assuming the new option worked for you and the documentation is fixed. If part of this isn't quite resolved, please reopen the issue.

**Comment by slicer69** [comment]
I tested the case-sensitive "disable Fortran" option you provided and can confirm it works. Trilinos now compiles for me. Thank you.
