### ISSUE TITLE
Look for SuiteSparse shared libraries too?

### ISSUE THREAD

**Issue by ilovezfs** [trilinos/Trilinos#1551]
https://github.com/trilinos/Trilinos/blob/f0350316239aaf41e8e6b82378612aaedf9cc72c/cmake/TPLs/FindTPLCholmod.cmake#L59

Currently Trilinos only looks for the static libraries from SuiteSparse, but the `make install` target in SuiteSparse does not install the static libraries, only the shared libraries.

In Homebrew, we're hacking around this for Trilinos by adding this to the SuiteSparse formula:
```
lib.install Dir["**/*.a"]
```

But it would be good if Trilinos were able to build with a stock SuiteSparse installation.

(I have also contracted SuiteSparse upstream to request that `make install` install the static libraries too.)

**Comment by mhoemmen** [comment]
@trilinos/framework
