### ISSUE TITLE
sierra::demangle

### ISSUE THREAD

**Issue by VictorEijkhout** [trilinos/Trilinos#1552]
```
build@build-BLDCHROOT:lib> ls *.so
libIoex.so           libbelos.so             libisorropia.so         libnemesis.so        libstk_mesh_fixtures.so     libstkclassic_rebalance.so               libstratimikosaztecoo.so    libthyraepetra.so
libIoexo_fac.so      libbelosepetra.so       libkokkosalgorithms.so  libnox.so            libstk_search.so            libstkclassic_rebalance_utils.so         libstratimikosbelos.so      libthyraepetraext.so
libIofx.so           libbelostpetra.so       libkokkoscontainers.so  libnoxepetra.so      libstk_search_util_base.so  libstkclassic_search.so                  libstratimikosifpack.so     libthyratpetra.so
libIogn.so           libdpliris.so           libkokkoscore.so        libnoxlapack.so      libstk_topology.so          libstkclassic_search_util.so             libstratimikosml.so         libtpetra.so
libIohb.so           libepetra.so            libkokkostsqr.so        libpamgen.so         libstk_unit_test_utils.so   libstkclassic_util_diag.so               libsupes.so                 libtpetraclassic.so
libIonit.so          libepetraext.so         libkomplex.so           libpamgen_extras.so  libstk_util_diag.so         libstkclassic_util_env.so                libsuplib.so                libtpetraclassiclinalg.so
libIopg.so           libexoIIv2for32.so      libloca.so              libphalanx.so        libstk_util_env.so          libstkclassic_util_parallel.so           libsuplib_c.so              libtpetraclassicnodeapi.so
libIoss.so           libexodus.so            liblocaepetra.so        libpytrilinos.so     libstk_util_parallel.so     libstkclassic_util_unit_test_support.so  libsuplib_cpp.so            libtpetraext.so
libIotr.so           libexodus_for.so        liblocalapack.so        librtop.so           libstk_util_registry.so     libstkclassic_util_util.so               libteko.so                  libtpetrainout.so
libModeLaplace.so    libgaleri-epetra.so     liblocathyra.so         librythmos.so        libstk_util_use_cases.so    libstokhos.so                            libteuchoscomm.so           libtpetrakernels.so
libamesos.so         libgaleri-xpetra.so     libmapvarlib.so         libsacado.so         libstk_util_util.so         libstokhos_amesos2.so                    libteuchoscore.so           libtpi.so
libamesos2.so        libgtest.so             libml.so                libshards.so         libstkclassic_algsup.so     libstokhos_ifpack2.so                    libteuchoskokkoscomm.so     libtriutils.so
libanasazi.so        libifpack.so            libmoocho.so            libshylu.so          libstkclassic_expreval.so   libstokhos_muelu.so                      libteuchoskokkoscompat.so   libxpetra-sup.so
libanasaziepetra.so  libifpack2-adapters.so  libmoochothyra.so       libstk_expreval.so   libstkclassic_io.so         libstokhos_sacado.so                     libteuchosnumerics.so       libxpetra.so
libanasazitpetra.so  libifpack2.so           libmuelu-adapters.so    libstk_io.so         libstkclassic_io_util.so    libstokhos_tpetra.so                     libteuchosparameterlist.so  libzoltan.so
libaprepro_lib.so    libintrepid.so          libmuelu-interface.so   libstk_io_util.so    libstkclassic_mesh_base.so  libstratimikos.so                        libteuchosremainder.so      libzoltan2.so
libaztecoo.so        libio_info_lib.so       libmuelu.so             libstk_mesh_base.so  libstkclassic_mesh_fem.so   libstratimikosamesos.so                  libthyracore.so
build@build-BLDCHROOT:lib> for s in *.so ; do nm $s | grep -i demangle ; done | grep -i sierra
                 U _ZN6sierra8demangleB5cxx11EPKc

```

Here's the culprit:

```
libstk_util_diag.so
                 U _ZN6sierra8demangleB5cxx11EPKc
```

Who was supposed to put that symbol in a library?

The log file is 40M. Have you increased the size limit on attachments?

Victor.

**Comment by VictorEijkhout** [comment]
Anyway. There's the log file, zipped.

[trilinos.zip](https://github.com/trilinos/Trilinos/files/1185174/trilinos.zip)

**Comment by ibaned** [comment]
@trilinos/stk 

@VictorEijkhout is this coming from an actual compilation or link error? what is the problem caused by the symbol being left undefined?

**Comment by VictorEijkhout** [comment]
On Jul 29, 2017, at 2:41 PM, Dan Ibanez <notifications@github.com<mailto:notifications@github.com>> wrote:

what is the problem caused by the symbol being left undefined?

It trips up the installation of dealii. At some point during the deal installation it tries to link an application, which fails due to the undefined symbol.

Victor.

**Comment by mhoemmen** [comment]
Just curious -- does deal.II need STK?

**Comment by VictorEijkhout** [comment]
On Jul 29, 2017, at 9:43 PM, Mark Hoemmen <notifications@github.com<mailto:notifications@github.com>> wrote:

Just curious -- does deal.II need STK?

I have no idea.

In fact, I have no idea why most of the parts of my triilinos install are there, except that what I’m installing is the sum total of all user requests plus their dependencies.

Victor.

**Comment by mhoemmen** [comment]
@VictorEijkhout Try turning off STK (`Trilinos_ENABLE_STK:BOOL=OFF`) for now.

**Comment by VictorEijkhout** [comment]
Is this issue going on the abandoned / will not be fixed list? Since all my installations are system-wide it's kinda annoying (read: non-trivial amount of work) to have to regenerate packages to get around bugs.

**Comment by ibaned** [comment]
I just looked in an installation that I have, and this symbol is defined:

```
install/gcc/Trilinos/lib$ for s in *.so ; do nm $s | grep -i demangle ; done | grep -i sierra
0000000000023430 T _ZN6sierra8demangleB5cxx11EPKc
```

Can you try with the latest develop branch? STK did a recent snapshot, maybe something got fixed.

**Comment by VictorEijkhout** [comment]
On Aug 29, 2017, at 1:41 PM, Dan Ibanez <notifications@github.com<mailto:notifications@github.com>> wrote:


Can you try with the latest develop branch? STK did a recent snapshot, maybe something got fixed.


Why is it so hard to install your software……

So I’m trying the github version, and now STK bombs on this:

/admin/build/rpms/BUILD/trilinos-git/packages/stk/stk_util/stk_util/environment/RuntimeMessage.cpp(47): catastrophic error: cannot open source file "boost/unordered/detail/buckets.hpp"
  #include "boost/unordered/detail/buckets.hpp"  // for iterator, etc

This file seems to be missing from my boost 1.64 installation. What gives?

Victor.

**Comment by ibaned** [comment]
That line of code just has the following:
```cpp
#include <unordered_map>
```
which is a [standard C++11 include](http://en.cppreference.com/w/cpp/container/unordered_map), but it looks like Boost also has a look-alike under `boost/tr1/tr1/unordered_map`. The first problem is that when looking for `unordered_map`, the compiler is finding the Boost one instead of the standard C++ header.

The second problem is that between Boost versions 1.63 and 1.64, the file `boost/unordered/detail/buckets.hpp` was removed. This indicates that the `unordered_map` file the compiler is finding is not only the wrong one (Boost), but on top of that is from an older Boost version. This sounds increasingly like an issue with your environment / install of Boost.

It would help if you attach the full Trilinos CMake configuration settings used.

@trilinos/framework @bmpersc

**Comment by jhux2** [comment]
@trilinos/stk @khpierson Perhaps the STK team can help out here.

**Comment by khpierson** [comment]
I've confirmed what Dan mentioned above that we are expecting to include the standard C++11 header file, <unordered_map> for the file RuntimeMessage.cpp. The demangle symbol is within the sierra namespace so I'm not sure how that could cause trouble with Deal.II

**Comment by VictorEijkhout** [comment]
"when looking for unordered_map, the compiler is finding the Boost one instead of the standard C++ header."

Since you guys make the compile lines, that's your problem, right?

"This indicates that the unordered_map file the compiler is finding is not only the wrong one (Boost), but on top of that is from an older Boost version."

I don't see how you conclude this.

```
staff.stampede2(15)$ pwd
/opt/apps/intel17/boost/1.64
staff.stampede2(16)$ find include -type f -name unordered\* -exec grep buckets {} \; -print
//! \c bucket_traits<>, \c power_2_buckets<> and \c cache_begin<>.
      |  (std::size_t(packed_options::power_2_buckets)*hash_bool_flags::power_2_buckets_pos)
//! \c bucket_traits<>, \c power_2_buckets<> and \c cache_begin<>.
      |  (std::size_t(packed_options::power_2_buckets)*hash_bool_flags::power_2_buckets_pos)
include/boost/intrusive/unordered_set.hpp```

Oh, wait, you're looking at the wrong line. Your file has:

`
#include "boost/unordered/detail/buckets.hpp"  // for iterator, etc
#include "boost/unordered/unordered_map.hpp"
`

So you're explicitly including a boost 1.63 file without assertaining that you have the right version of boost.

**Comment by ibaned** [comment]
Making progress... I found the version of the code that did have those lines, but it was changed in January 2016:

https://github.com/trilinos/Trilinos/commit/578fdd5435a74b189ccefccceaa809b8d07fa6c3

I'm not sure how you got your "GitHub version", but its old. The current master version of Trilinos doesn't include those headers anymore.

**Comment by VictorEijkhout** [comment]
On Sep 1, 2017, at 6:23 PM, Dan Ibanez <notifications@github.com<mailto:notifications@github.com>> wrote:

I'm not sure how you got your "GitHub version", but its old.

Cloned yesterday…..

Yep. Updated the repository and it’s still there.

root@build-BLDCHROOT:trilinos-git # git pull
Auto packing the repository for optimum performance. You may also
run "git gc" manually. See "git help gc" for more information.
Counting objects: 925299, done.
Delta compression using up to 28 threads.
Compressing objects: 100% (183400/183400), done.
Writing objects: 100% (925299/925299), done.
Total 925299 (delta 757767), reused 892983 (delta 725631)
Removing duplicate objects: 100% (256/256), done.
Checking connectivity: 925299, done.
Already up-to-date.
root@build-BLDCHROOT:trilinos-git # ls
checkin-test.py       cmake           commonTools    CTestConfig.cmake  doc      LICENSE   PackagesList.cmake              ProjectName.cmake  README.md      sampleScripts  sparse_checkout.sh  Version.cmake
clone_extra_repos.py  CMakeLists.txt  Copyright.txt  demos              INSTALL  packages  project-checkin-test-config.py  README             RELEASE_NOTES  SIERRA         TPLsList.cmake
root@build-BLDCHROOT:trilinos-git # grep bucket packages/stk/stk_util/stk_util/environment/RuntimeMessage.cpp
#include "boost/unordered/detail/buckets.hpp"  // for iterator, etc

Victor.

**Comment by VictorEijkhout** [comment]
On Sep 1, 2017, at 6:23 PM, Dan Ibanez <notifications@github.com<mailto:notifications@github.com>> wrote:

I'm not sure how you got your "GitHub version", but its old.

Or do you want to tell me that this page is incorrect?

https://trilinos.org/oldsite/publicRepo/index.html

Oh, wait, it says “oldsite”. Cute. There is nothing on the actual page that indicates that it’s out of date.

Forgive me for being sarcastic, but I just love wasting time this way.

Victor.

**Comment by VictorEijkhout** [comment]
On Sep 1, 2017, at 6:23 PM, Dan Ibanez <notifications@github.com<mailto:notifications@github.com>> wrote:

I'm not sure how you got your "GitHub version", but its old.

I’m willing to bet that your ticket system will throw away the attached screen shot, but it is showing your “oldsite” as top search result in google.

Victor.

[cid:C520228D-5FC3-46C0-BF8F-906DC1779532@attlocal.net]

**Comment by VictorEijkhout** [comment]
On Sep 1, 2017, at 6:23 PM, Dan Ibanez <notifications@github.com<mailto:notifications@github.com>> wrote:

I'm not sure how you got your "GitHub version", but its old.

I’m willing to bet that your ticket system will throw away the screen shot, but it is showing your “oldsite” as top search result in google.

Victor.

**Comment by aprokop** [comment]
@trilinos/framework @jwillenbring You should be aware of this issue. Can we add a disclaimer to [old Trilinos site](https://trilinos.org/oldsite/publicRepo/index.html)?

**Comment by VictorEijkhout** [comment]
On Sep 1, 2017, at 6:37 PM, Andrey Prokopenko <notifications@github.com<mailto:notifications@github.com>> wrote:

Can we add a disclaimer to old Trilinos site<https://trilinos.org/oldsite/publicRepo/index.html>?

Or at least remove that old repository, for F!’s sake.

Victor.

**Comment by VictorEijkhout** [comment]
Ok, repository.

-- Phalanx_example_finite_element_assembly: NOT added test because Phalanx_ENABLE_TESTS='OFF'.
CMake Error at cmake/tribits/core/package_arch/TribitsAddExecutable.cmake:435 (MESSAGE):
  ERROR: 'phalanx_unit_test_main' in TESTONLYLIBS not a TESTONLY lib! If this
  a regular library in this SE package or in an dependent upstream SE package
  then TriBITS will link automatically to it.  If you remove this and it does
  not link, then you need to add a new SE package dependency to this SE
  package's dependencies file
  /admin/build/rpms/BUILD/trilinos-git/packages/phalanx/cmake/Dependencies.cmake
Call Stack (most recent call first):
  cmake/tribits/core/package_arch/TribitsAddExecutableAndTest.cmake:68 (TRIBITS_ADD_EXECUTABLE)
  cmake/tribits/core/package_arch/TribitsAddExecutableAndTest.cmake:211 (TRIBITS_ADD_EXECUTABLE_WRAPPER)
  packages/phalanx/example/FiniteElementAssembly/CMakeLists.txt:68 (TRIBITS_ADD_EXECUTABLE_AND_TEST)

Note that of course I’m not specifying anything about TESTONLYLIBS.

My cmake line. Say when….

cmake -VV \
  -D BUILD_SHARED_LIBS:BOOL=ON \
  -D Trilinos_VERBOSE_CONFIGURE=OFF \
  -D CMAKE_VERBOSE_MAKEFILE=ON \
  -D Trilinos_ENABLE_ALL_PACKAGES:BOOL=OFF \
  -D Trilinos_ASSERT_MISSING_PACKAGES=OFF \
  -D Trilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=OFF \
  -D Trilinos_ENABLE_TESTS:BOOL=OFF \
  -D Trilinos_ENABLE_EXAMPLES:BOOL=ON \
  -D Trilinos_ENABLE_Export_Makefiles:BOOL=ON \
  -D Trilinos_ENABLE_Fortran:BOOL=ON \
  \
  -D CMAKE_INSTALL_PREFIX:PATH=%{INSTALL_DIR} \
  -D CMAKE_BUILD_TYPE:STRING=RELEASE \
  -D CMAKE_C_FLAGS:STRING="${COPTFLAGS} ${MKLFLAG}" \
  -D CMAKE_CXX_FLAGS:STRING="${COPTFLAGS} ${MKLFLAG} -DMPICH_SKIP_MPICXX" \
  -D Trilinos_EXTRA_LINK_FLAGS="${TACC_PYTHON_LIB}/libpython2.7.so" \
  -D Trilinos_EXTRA_LD_FLAGS="${TACC_PYTHON_LIB}/libpython2.7.so" \
  \
  -D BLAS_INCLUDE_DIRS:PATH="${TACC_MKL_INC}" \
  -D BLAS_LIBRARY_DIRS:PATH="${TACC_MKL_LIB}" \
  -D BLAS_LIBRARY_NAMES:STRING="mkl_intel_lp64;mkl_sequential;mkl_core;pthread" \
  -D LAPACK_INCLUDE_DIRS:PATH="${TACC_MKL_INC}" \
  -D LAPACK_LIBRARY_DIRS:PATH="${TACC_MKL_LIB}" \
  -D LAPACK_LIBRARY_NAMES:STRING="mkl_intel_lp64;mkl_sequential;mkl_core;pthread" \
  \
  -D TPL_ENABLE_MPI:BOOL=ON \
  -D MPI_EXEC:FILEPATH="/opt/apps/xalt/0.6/bin/ibrun" \
  -D TPL_ENABLE_GLM=OFF \
  -D TPL_ENABLE_Matio=OFF \
  \
  -D TPL_ENABLE_Boost:BOOL=ON \
  -D Boost_INCLUDE_DIRS:PATH=$TACC_BOOST_INC      \
  -D Boost_LIBRARY_DIRS:PATH=$TACC_BOOST_LIB      \
  -D TPL_ENABLE_BoostLib:BOOL=ON \
  -D BoostLib_INCLUDE_DIRS:PATH=$TACC_BOOST_INC      \
  -D BoostLib_LIBRARY_DIRS:PATH=$TACC_BOOST_LIB      \
  \
  -D TPL_ENABLE_HDF5:BOOL=${HAS_HDF5} \
  -D HDF5_INCLUDE_DIRS:PATH=$TACC_HDF5_INC    \
  -D HDF5_LIBRARY_DIRS:PATH=$TACC_HDF5_LIB    \
  -D TPL_ENABLE_Netcdf:BOOL=${HAS_NETCDF} \
  -D Netcdf_INCLUDE_DIRS:PATH=$TACC_NETCDF_INC    \
  -D Netcdf_LIBRARY_DIRS:PATH=$TACC_NETCDF_LIB    \
  \
  -D Trilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=ON \
  \
  -D Trilinos_ENABLE_Amesos:BOOL=ON \
  -D Amesos2_ENABLE_Basker:BOOL=ON \
  -D Trilinos_ENABLE_Anasazi:BOOL=ON \
  -D Trilinos_ENABLE_AztecOO:Bool=ON \
  -D Trilinos_ENABLE_Belos:BOOL=ON \
  -D Trilinos_ENABLE_Epetra:Bool=ON \
  -D Trilinos_ENABLE_EpetraExt:Bool=ON \
  -D                 Epetra_ENABLE_TESTS:BOOL=ON \
  -D Trilinos_ENABLE_FEI:Bool=ON \
  -D Trilinos_ENABLE_Ifpack:Bool=ON \
  -D Trilinos_ENABLE_Intrepid:BOOL=ON \
  -D                 Intrepid_ENABLE_TESTS:BOOL=ON \
  -D Trilinos_ENABLE_Issoropia:BOOL=ON \
  -D Trilinos_ENABLE_Kokkos:BOOL=ON \
  -D Trilinos_ENABLE_ML:BOOL=ON \
  -D Trilinos_ENABLE_MOOCHO:BOOL=ON \
  -D Trilinos_ENABLE_MueLu:BOOL=${HAS_MUELU} \
  -D                 MueLu_ENABLE_Tutorial:BOOL=OFF \
  -D Trilinos_ENABLE_NOX=ON \
  -D                 NOX_ENABLE_TESTS:BOOL=OFF \
  -D Trilinos_ENABLE_Pamgen:Bool=ON \
  -D Trilinos_ENABLE_Panzer:Bool=ON \
  -D Trilinos_ENABLE_Phalanx:BOOL=ON \
  -D Phalanx_EXPLICIT_TEMPLATE_INSTANTIATION=ON \
  -D Trilinos_ENABLE_Rythmos:BOOL=ON \
  -D Trilinos_ENABLE_Sacado:Bool=ON \
  -D Trilinos_ENABLE_SEACAS:BOOL=${HAS_SEACAS} \
  -D Trilinos_ENABLE_SEACASIoss:BOOL=${HAS_SEACAS} \
  -D Trilinos_ENABLE_SEACASBlot:BOOL=${HAS_SEACAS} \
  -D Trilinos_ENABLE_SECONDARY_STABLE_CODE:BOOL=ON \
  -D Trilinos_ENABLE_Shards:BOOL=ON \
  -D Trilinos_ENABLE_ShyLU:BOOL=ON \
  -D Trilinos_ENABLE_STK:BOOL=${HAS_STK} \
  -D Trilinos_ENABLE_Stokhos:BOOL=ON \
  -D Trilinos_ENABLE_Stratimikos:BOOL=ON \
  -D Trilinos_ENABLE_Teko:BOOL=ON \
  -D Trilinos_ENABLE_Teuchos:BOOL=ON \
  -D Trilinos_ENABLE_Tpetra:BOOL=ON \
  -D Trilinos_ENABLE_TriKota:BOOL=ON \
  -D Trilinos_ENABLE_Zoltan:BOOL=ON \
  \
  -D Trilinos_ENABLE_PyTrilinos:Bool=${HAS_PYTHON} \
  -D CMAKE_PYTHON_INCLUDE_DIR:PATH="${TACC_PYTHON_INC}" \
  -D CMAKE_PYTHON_LIBRARIES:STRING="${TACC_PYTHON_LIB}" \
  -D PyTrilinos_DOCSTRINGS:BOOL=OFF \
  -D SWIG_EXECUTABLE:FILEPATH=${TACC_SWIG_DIR}/bin/swig \
  \
  ${TRILINOS_LOCATION}/trilinos-${VERSION} \

**Comment by rppawlo** [comment]
> -- Phalanx_example_finite_element_assembly: NOT added test because Phalanx_ENABLE_TESTS='OFF'. CMake Error at cmake/tribits/core/package_arch/TribitsAddExecutable.cmake:435 (MESSAGE): ERROR: 'phalanx_unit_test_main' in TESTONLYLIBS not a TESTONLY lib! If this a regular library in this SE package or in an dependent upstream SE package then TriBITS will link automatically to it. If you remove this and it does not link, then you need to add a new SE package dependency to this SE package's dependencies file /admin/build/rpms/BUILD/trilinos-git/packages/phalanx/cmake/Dependencies.cmake Call Stack (most recent call first): cmake/tribits/core/package_arch/TribitsAddExecutableAndTest.cmake:68 (TRIBITS_ADD_EXECUTABLE) cmake/tribits/core/package_arch/TribitsAddExecutableAndTest.cmake:211 (TRIBITS_ADD_EXECUTABLE_WRAPPER) packages/phalanx/example/FiniteElementAssembly/CMakeLists.txt:68 (TRIBITS_ADD_EXECUTABLE_AND_TEST) Note that of course I’m not specifying anything about TESTONLYLIBS.

@VictorEijkhout - I will push a fix to Trilinos development branch shortly. To get past this now, you can either enable the phalanx tests (Phalanx_ENABLE_TESTS=ON) or disable the phalanx examples (Phalanx_ENABLE_EXAMPLES=OFF). Examples currently require tests. Sorry for the trouble.

@bartlettroscoe - a couple of the examples in phalanx use a test-only library. I was under the impression that "tests" and "examples" were treated the same by tribits underneath - it was only the name of the directory and separate enable/disable flags. Can we make test-only libraries be available for examples too? The error above was triggered by enabling the examples but not the tests. I guess we don't have a build that tests this configuration.

**Comment by bartlettroscoe** [comment]
@rppawlo,

> I was under the impression that "tests" and "examples" were treated the same by tribits underneath - it was only the name of the directory and separate enable/disable flags. Can we make test-only libraries be available for examples too? The error above was triggered by enabling the examples but not the tests. I guess we don't have a build that tests this configuration.

This many need a little tweaking.  Some parts of TriBITS lump tests and examples together as the same thing.  This may be a case where there is some inconsistency.

It think we need to better define these concepts a little more and better deal with test execs, example execs vs. other execs a little more explicitly along the lines of:

* https://docs.google.com/document/d/1WKs8rJhI3037yKGnEVMhIx9dPN7a7uFRM5isdNAhAXI/edit#bookmark=id.9tkoljf98q9h

Until then, we may need to hack things a little to address this case.  I think that should not be too hard.

**Comment by rppawlo** [comment]
Phalanx fix was pushed in https://github.com/trilinos/Trilinos/commit/d7c00d45f0e2afe1cf19c70159cd589be34db8b8

**Comment by VictorEijkhout** [comment]
And with that everything compiles again.

Can you maybe send me heads-up when you release a new version?

Victor.

On Sep 5, 2017, at 5:11 PM, Roger Pawlowski <notifications@github.com<mailto:notifications@github.com>> wrote:


Phalanx fix was pushed in d7c00d4<https://github.com/trilinos/Trilinos/commit/d7c00d45f0e2afe1cf19c70159cd589be34db8b8>

**Comment by VictorEijkhout** [comment]
I see that 12.12 was released in September. Does that include the fix for this issue?

**Comment by rppawlo** [comment]
The commit d7c00d4 did not make it into the 12.12 release.

**Comment by VictorEijkhout** [comment]
On Dec 1, 2017, at 11:11 AM, Roger Pawlowski <notifications@github.com<mailto:notifications@github.com>> wrote:

The commit d7c00d4<https://github.com/trilinos/Trilinos/commit/d7c00d45f0e2afe1cf19c70159cd589be34db8b8> did not make it into the 12.12 release.

Time for another update? It’s been two months.

Anyway. Is there an announce mailing list for releases?

Victor.
