### ISSUE TITLE
Albany slower after Trilinos changes on 27 July 2017

### ISSUE THREAD

**Issue by ibaned** [trilinos/Trilinos#1553]
Cross-posting gahansen/Albany#159

Repeating content for convenience (@ikalash wrote):

It appears some commits to develop branch Trilinos on 7/27/17, I believe most likely to Tpetra, caused my CISM-Albany nightly tests to run much slower, e.g.:

7/28/17:
dome_5years | Passed | 13s 750ms
ross_diagnostic | Passed | 2m 51s 170ms
halfar_100years | Passed | 18m 58s 550ms
confined-shelf_diagnostic | Passed | 11s 670ms
circular-shelf_diagnostic | Passed | 8s 750ms

7/27/17:
dome_5years | Passed | 10s 400ms
ross_diagnostic | Passed | 2m 18s 660ms
halfar_100years | Passed | 16m 9s 980ms
confined-shelf_diagnostic | Passed | 9s 310ms
circular-shelf_diagnostic | Passed | 7s 90ms

@trilinos/tpetra

Edit: referenced the wrong Albany issue number

**Comment by mhoemmen** [comment]
@ibaned Could you post a range of commits on develop?  Merges make that a little bit challenging.  A Kokkos merge and MueLu changes happened in the date range, so those could also be issues.

**Comment by ibaned** [comment]
I'll work with @ikalash to get you that info ASAP

**Comment by mhoemmen** [comment]
Thanks @ibaned !  I've been making changes to Tpetra recently to simplify the insides, and don't expect big performance changes, but there's always the possibility of surprise :-) .

**Comment by mhoemmen** [comment]
Any scoop?  Also, is this at all related to #1088?

**Comment by ibaned** [comment]
@mhoemmen sorry for not keeping you updated. The latest thinking by @ikalash and myself is that the slowdown was caused by the latest Kokkos snapshot, so Tpetra may be off the hook. I still need to replicate her timings on my machine before I can say with certainty though.

I'm sure you know this feeling, but these codes just take so long to compile...  in a few more hours I can start running my "before" case.

**Comment by mhoemmen** [comment]
@ibaned wrote:
> I'm sure you know this feeling, ....

Very much so ;-) .

> The latest thinking by @ikalash and myself is that the slowdown was caused by the latest Kokkos snapshot, so Tpetra may be off the hook.

Tpetra does not use any new features that might be in the latest snapshot, so I think you could just revert the snapshot commit and try again.  Does Albany have a performance dashboard?  I'm asking because Tpetra has been getting some performance improvements for threads and GPUs, and I want to make sure that we don't cause issues in Albany.  Even if there's no performance dashboard, I still very much appreciate these timely reports that refer to a narrow range of commits :-) .

**Comment by ibaned** [comment]
I'm almost done gathering data, but at this point its essentially confirmed that the Kokkos snapshot on its own caused the slowdown. A few answers below anyways:

> I think you could just revert the snapshot commit and try again

Its only slightly more complex, because the snapshot comes with several commits to Trilinos as well due to `Experimental` namespace changes. I've figured it out anyway.

> Does Albany have a performance dashboard?

Not as such, we have regular CDash boards on which test times can be observed.

http://my.cdash.org/index.php?project=Albany&date=
http://cdash.sandia.gov/CDash-2-3-0/index.php?project=Albany&date=

I believe if you select "Test Time" under "Display graphs:" on this page

http://cdash.sandia.gov/CDash-2-3-0/testDetails.php?test=3038758&build=57142

You should see a shift in the average test time that happens after July 17th (CDash unfortunately mixes data points across all builds, I wish they could track it per-build).

> I still very much appreciate these timely reports that refer to a narrow range of commits

We'll make every effort to provide detailed information including profiling to whomever we determine might help us regain performance.

**Comment by ibaned** [comment]
I think I'll go ahead an close this. Detailed reports will show up in gahansen/Albany#159, after which a Kokkos issue will probably be opened.

**Comment by mhoemmen** [comment]
> We'll make every effort to provide detailed information including profiling to whomever we determine might help us regain performance.

Thanks @ibaned !  What you've already been doing is the best thing -- just a heads-up that "hey, the test times are huge now" is super helpful :-) .
