### ISSUE TITLE
Change LOCA Stepper start/end time at runtime

### ISSUE THREAD

**Issue by ibaned** [trilinos/Trilinos#1557]
@trilinos/nox 

This question is from @lxmota: is there a straightforward way to change a LOCA Stepper's start and end time via C++ interfaces at runtime, so the continuation stepper/solver can be reused over a different range?

**Comment by etphipp** [comment]
Not really.  You can call the reset() method on the stepper, which will allow you to set a new start and stop value in the parameter list, but that isn't much different than creating a new stepper from scratch.

**Comment by ibaned** [comment]
Would it be possible to add this as a feature?

**Comment by lxmota** [comment]
We need to make progress on projects that have deliverables. I'll create a branch and I'll add the interface to access the stepper and the start and end times.
