### ISSUE TITLE
const on stk::util::ParameterList::begin() and end()

### ISSUE THREAD

**Issue by jmgate** [trilinos/Trilinos#1558]
Pretty sure the following lines in `ParameterList.hpp`

```
ParameterMapType::const_iterator begin() {return parameterData.begin();}
ParameterMapType::const_iterator end() {return parameterData.end();}
```

need to become

```
ParameterMapType::const_iterator begin() const {return parameterData.begin();}
ParameterMapType::const_iterator end() const {return parameterData.end();}
```

I'm being forced to work with a non-`const` `ParameterList` when it really should be `const` in order to get the code to compile.  For instance

```
void foo(const stk::util::ParameterList& params)
{
  using PIter = stk::util::ParameterMapType::const_iterator;
  for (PIter i = params.begin(); i != params.end(); ++i)
  {
    // Do stuff with i.
  }
}
```

results in

```
error: passing 'const stk::util::ParameterList' as 'this' argument discards qualifiers [-fpermissive]
for (PIter i = params.begin(); i != params.end(); ++i)
                            ^
```

**Comment by mhoemmen** [comment]
@trilinos/stk

**Comment by jmgate** [comment]
Does anyone know if @trilinos/stk actually uses Trilinos' issue tracker?  Should I be filing this issue elsewhere?

**Comment by mhoemmen** [comment]
@jmgate They do pay attention to Trilinos' issue tracker, but don't necessarily use it for new issues.  Also, GitHub notifications have been weird lately.  I'll send you a link to their issue tracker via work e-mail.  Thanks!

**Comment by jmgate** [comment]
Closing due to lack of response.
