### ISSUE TITLE
ROL passes zero vector to Jacobian methods

### ISSUE THREAD

**Issue by wil-england** [trilinos/Trilinos#1561]
I have written a constraint class inheriting from `ROL::StdConstraint< real >` which implements both `applyJacobian` and `applyAdjointJacobian`. However, the effect of my constraints are not being reported to the algorithm due to the test vector passed to me by ROL (with which I multiply my Jacobian) is a vector of all zeros. It may be worth noting that our problem currently has ~20k constraints. I have verified that the test vector is zero by taking the dot product of the test vector with itself. Here's my dot product code for verification:

```
        auto dot = []( const std::vector< real > &a, const std::vector< real > &b ){
            assert( a.size() == b.size() );
            
            real dot = 0.0f;

            for( unsigned int i = 0; i < a.size(); i++ ){
                dot += a[i] * b[i];
            }

            return dot;
        };
```
I cloned the develop branch yesterday (July 31), so I should be at the most up to date version. I'm assuming this to be a bug. Any help would be appreciated.

Thanks,
Wil

**Comment by ibaned** [comment]
@trilinos/rol

**Comment by dridzal** [comment]
@dpkouri and @dridzal are looking into this.

**Comment by dridzal** [comment]
@wil-england Have you created an instance of OptimizationProblem?  If so, could you please run the check method and report the results?  (Here we've assumed that you are using ROL::StdVector.)

**Comment by dridzal** [comment]
@wil-england , we've examined the output that you emailed, and it appears fine for the most part.  The range of finite difference steps may not be ideal for this problem setup but we do see the expected decrease / increase in the absolute error for the various quantities.  We also see that the Jacobian checks are passing, which means that ROL is not zeroing the vector inadvertently within these methods.  This probably means that the "wiring" between your code and ROL is OK.

It remains to verify that the algorithm itself doesn't choose a zero vector for your particular problem.  This can happen for many reasons, but we would really have to debug the problem carefully.  I wonder if there is a way to generate a "related" problem of reasonable size that we could implement in ROL directly?  For example, in ROL, in addition to "basic" problems with inequality constraints, we could generate an elasticity topology optimization problem with stress constraints that may be closer to your use case.  We have the required infrastructure in the example/PDE-OPT directory.
