### ISSUE TITLE
BOOST detection not working

### ISSUE THREAD

**Issue by dridzal** [trilinos/Trilinos#1564]
I'm getting a CMake error:

CMake Error at /projects/sems/install/rhel6-x86_64/sems/utility/cmake/3.5.2/share/cmake-3.5/Modules/FindBoost.cmake:428 (message):
  ERROR: Boost_ROOT is not the correct spelling.  The proper spelling is
  BOOST_ROOT.

I have not set Boost_ROOT nor BOOST_ROOT.  I'm using 

-D Boost_INCLUDE_DIRS=/projects/sems/install/rhel6-x86_64/sems/tpl/boost/1.63.0/intel/17.0.1/base/include

This appears to be a CMake or Tribits bug.  @bmpersc @bartlettroscoe

**Comment by ibaned** [comment]
Please post your full configure command

**Comment by dridzal** [comment]
EXTRA_ARGS=$@

cmake \
-D CMAKE_BUILD_TYPE:STRING=RELEASE \
-D TPL_ENABLE_MPI:BOOL=ON \
-D BUILD_SHARED_LIBS:BOOL=ON \
-D Trilinos_ENABLE_DEBUG:BOOL=ON \
-D Trilinos_ENABLE_DEBUG_SYMBOLS:BOOL=ON \
-D TPL_ENABLE_Boost=ON \
-D Boost_INCLUDE_DIRS=/projects/sems/install/rhel6-x86_64/sems/tpl/boost/1.63.0/intel/17.0.1/base/include \
-D Trilinos_ENABLE_ROL:BOOL=ON \
-D Trilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=ON \
-D Trilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON \
-D Trilinos_ENABLE_TESTS:BOOL=OFF \
-D Trilinos_ENABLE_EXAMPLES:BOOL=OFF \
-D ROL_ENABLE_TESTS:BOOL=ON \
-D ROL_ENABLE_EXAMPLES:BOOL=ON \
-D ROL_ENABLE_TIMERS:BOOL=ON \
-D CMAKE_INSTALL_PREFIX:PATH=/home/dridzal/development/ROL-Trilinos/build/intel-17.0.1-sems/install \
$EXTRA_ARGS \
../../../ROL-Trilinos

**Comment by dridzal** [comment]
For the environment, I'm using

source ../../cmake/load_sems_dev_env.sh "sems-intel/17.0.1" "sems-openmpi/1.10.1"

**Comment by ibaned** [comment]
Are there any `$EXTRA_ARGS` ?

**Comment by dridzal** [comment]
No, there are not.

**Comment by bartlettroscoe** [comment]
Strange, I have never seen that before.  The var they are talking about `Boost_ROOT` is likely and env var.  What does your env show?  Do:

```
$ set | grep -i boost
```

What does that return?

**Comment by dridzal** [comment]
Nothing.

bash-4.1$ set | grep -i boost
bash-4.1$

**Comment by ibaned** [comment]
I would remove at least the `CMakeCache.txt` file (preferably the whole build directory) and try again
