### ISSUE TITLE
Tpetra: pack/unpack unit testing

### ISSUE THREAD

**Issue by tjfulle** [trilinos/Trilinos#1568]
@trilinos/tpetra 

A unit test should be written that packs from a non-const graph matrix and unpacks in to a const-graph matrix.  This functionality is used in `globalAssemble` if the original map is not one-to-one (as is common in finite elements).  

Several @trilinos/rol examples broke with recent work in @trilinos/tpetra where `CrsMatrix` pack/unpack procedures were refactored to use `PackTraits` to serialize sparse matrix communication.  Only the case of const-graph matrices were refactored making the serialization for the const-graph and nonconst-graph incompatible (the inconsistency has since been addressed).

**Comment by mhoemmen** [comment]
Thanks @tjfulle !
