### ISSUE TITLE
Add a CMake option & test for whether MPI is CUDA aware

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#1571]
@trilinos/tpetra @trilinos/framework 

Add a CMake option, and a configure-time test, for whether MPI is CUDA aware (edited 13 Aug 2017 from "MPI supports CUDA").  "MPI is CUDA aware" (edited 13 Aug 2017 from "MPI supports CUDA") means that the MPI implementation knows how to read from and write to CUDA buffers, that is, memory allocated using `cudaMalloc` (in Kokkos, a View with memory space `Kokkos::CudaSpace`).  See #1088 for justification and discussion.

OpenMPI provides a command-line test as of 1.7.3:
```
$ ompi_info --parsable --all | grep mpi_built_with_cuda_support:value
mca:mpi:base:param:mpi_built_with_cuda_support:value:true
```
and an API as of 2.0.0: https://www.open-mpi.org/faq/?category=runcuda#mpi-cuda-aware-support

We need a CMake option as well as a test, in order to support cross-compilation.  Otherwise, users building on a different platform than where they plan to run would have no way to tell Trilinos that the MPI implementation on which they plan to run is CUDA aware (edited 13 Aug 2017: "supports CUDA").

**Comment by ibaned** [comment]
can we call it "CUDA-aware MPI" since that [seems to be](https://devblogs.nvidia.com/parallelforall/introduction-cuda-aware-mpi/) de facto terminology for it already?

**Comment by mhoemmen** [comment]
@ibaned wrote:
> can we call it "CUDA-aware MPI" since that seems to be de facto terminology for it already?

Sounds good!

**Comment by mhoemmen** [comment]
I have a #1088 fix that I won't be able to push until this option exists, so I can work on it.  I also have two different CUDA builds set up, one with a CUDA-aware MPI, and the other with a "CUDA-ignorant" MPI.  I might want yet another MPI that is not OpenMPI, just so I can test the fall-back of `ompi_info` not existing or not returning useful information.

**Comment by mhoemmen** [comment]
@ibaned Would you like to review my code and or help me with this?  If not, that's OK.

**Comment by ibaned** [comment]
@mhoemmen I could probably do a review. just post here when its ready. Another thing to think about `ompi_info` being in `PATH` but Trilinos is being linked to a different MPI. In other words, only use the `ompi_info` in the `MPI_DIR` that I think Trilinos already figures out... not sure if we derive `MPI_DIR` correctly when just compiler wrappers are given... anyway just thoughts

**Comment by mhoemmen** [comment]
@ibaned Thanks for reminding me!  I think it should suffice to use `MPI_BIN_DIR` to find `ompi_info`.  That's where OpenMPI installs it.  If both `MPI_BIN_DIR` and `MPI_BASE_DIR` are empty, then I may search `$PATH` for `ompi_info`.

**Comment by mhoemmen** [comment]
@ibaned PR #1602 proposes a fix.

My only concern is that it currently forces Tpetra to decide whether MPI is CUDA aware at configure time.  Some MPI implementations, like MVAPICH (see http://mvapich.cse.ohio-state.edu/userguide/gdr/2.2/ ), let users control this at run time, by setting an environment variable.  This means that Tpetra may also need run-time environment variable control.  However, we can always add that feature later.  The CMake option is still useful, because it could determine the environment variable's default value.

**Comment by mhoemmen** [comment]
I pushed a fix to develop.  Thanks @ibaned ! :D
