### ISSUE TITLE
SEGFAULT with Teuchos parameterlist

### ISSUE THREAD

**Issue by RiccardoRossi** [trilinos/Trilinos#1576]
Hi All,

i would like to point out a segfault which happens when using in debugmode the teuchos parameterlist

here goes the reproducer. NOTE:  the flags  -D_DEBUG -D_GLIBCXX_DEBUG have to be included to trigger the segfault (they activate the debug mode in the stdlib)

     #include "Teuchos_ParameterList.hpp"
     #include <iostream>
      //COMPILE WITH: -- the -D_DEBUG -D_GLIBCXX_DEBUG triggers a segfault!!!
      // g++ -std=c++11 -fPIC -O0 -D_DEBUG -D_GLIBCXX_DEBUG -g -o a.out main.cpp -I/usr/include/trilinos -L/usr/lib/x86_64-linux-gnu/ -ltrilinos_teuchosparameterlist -ltrilinos_teuchoscore
      
      int main() {
           std::cout << "Hello World!" << std::endl;
           Teuchos::ParameterList a;
           a.set(std::string("aaa"),std::string("bbb"));
            return 0;
      }

**Comment by mhoemmen** [comment]
Hi @RiccardoRossi -- thanks for reporting this!  What version of Trilinos are you using?

**Comment by RiccardoRossi** [comment]
Hi,

Honestly I am not sure. It is the one package with Ubuntu 16.04

Regards
Riccardo

**Comment by ibaned** [comment]
@nschloe could probably tell us which one that is.

**Comment by RiccardoRossi** [comment]
I think it is s 12.4.2

https://launchpad.net/ubuntu/xenial/+source/trilinos

Cheers
Riccardo

On Aug 4, 2017 10:47 PM, "Dan Ibanez" <notifications@github.com> wrote:

@nschloe <https://github.com/nschloe> could probably tell us which one that
is.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/trilinos/Trilinos/issues/1576#issuecomment-320349533>,
or mute the thread

**Comment by nschloe** [comment]
Yup, it's 12.4.2. @RiccardoRossi Can try out [the nightly PPA](https://launchpad.net/~nschloe/+archive/ubuntu/trilinos-nightly) and see if the error still occurs?

**Comment by RiccardoRossi** [comment]
Hi Nico,

I ll do on Monday.

Regards
Riccardo

**Comment by RiccardoRossi** [comment]
Hi,
no joy unfortunately. 

i installed the latest ppa on my machine, here is the output of my command line, just to prove that i am correctly linking the updated version

rrossi@Latitude-E5450:~/scratch/teuchos_test$ ls
main.cpp
rrossi@Latitude-E5450:~/scratch/teuchos_test$ g++ -std=c++11 -fPIC -O0 -D_DEBUG -D_GLIBCXX_DEBUG -g -o a.out main.cpp -I/usr/include/trilinos -L/usr/lib/x86_64-linux-gnu/ -ltrilinos_teuchosparameterlist -ltrilinos_teuchoscore
rrossi@Latitude-E5450:~/scratch/teuchos_test$ ./a.out 
Hello World!
Segmentation fault (core dumped)
rrossi@Latitude-E5450:~/scratch/teuchos_test$ ldd a.out 
	linux-vdso.so.1 =>  (0x00007ffe697cd000)
	libtrilinos_teuchosparameterlist.so.12 => /usr/lib/x86_64-linux-gnu/libtrilinos_teuchosparameterlist.so.12 (0x00007f2e4dd0f000)
	libtrilinos_teuchoscore.so.12 => /usr/lib/x86_64-linux-gnu/libtrilinos_teuchoscore.so.12 (0x00007f2e4daad000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f2e4d72a000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f2e4d514000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f2e4d14a000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f2e4ce40000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f2e4cc23000)
	libtrilinos_kokkoscore.so.12 => /usr/lib/x86_64-linux-gnu/libtrilinos_kokkoscore.so.12 (0x00007f2e4c9d0000)
	libmpi_cxx.so.1 => /usr/lib/libmpi_cxx.so.1 (0x00007f2e4c7b4000)
	libmpi.so.12 => /usr/lib/libmpi.so.12 (0x00007f2e4c4de000)
	/lib64/ld-linux-x86-64.so.2 (0x000055a3fbed3000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f2e4c2d9000)
	libibverbs.so.1 => /usr/lib/libibverbs.so.1 (0x00007f2e4c0ca000)
	libopen-rte.so.12 => /usr/lib/libopen-rte.so.12 (0x00007f2e4be50000)
	libopen-pal.so.13 => /usr/lib/libopen-pal.so.13 (0x00007f2e4bbb2000)
	libhwloc.so.5 => /usr/lib/x86_64-linux-gnu/libhwloc.so.5 (0x00007f2e4b978000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f2e4b770000)
	libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007f2e4b56c000)
	libnuma.so.1 => /usr/lib/x86_64-linux-gnu/libnuma.so.1 (0x00007f2e4b361000)
	libltdl.so.7 => /usr/lib/x86_64-linux-gnu/libltdl.so.7 (0x00007f2e4b157000)
rrossi@Latitude-E5450:~/scratch/teuchos_test$ ls /usr/lib/x86_64-linux-gnu/libtrilinos_
Display all 132 possibilities? (y or n)
rrossi@Latitude-E5450:~/scratch/teuchos_test$ ls /usr/lib/x86_64-linux-gnu/libtrilinos_teuchosparameterlist.so*
/usr/lib/x86_64-linux-gnu/libtrilinos_teuchosparameterlist.so
/usr/lib/x86_64-linux-gnu/libtrilinos_teuchosparameterlist.so.12
/usr/lib/x86_64-linux-gnu/libtrilinos_teuchosparameterlist.so.12.11
rrossi@Latitude-E5450:~/scratch/teuchos_test$ ls -l /usr/lib/x86_64-linux-gnu/libtrilinos_teuchosparameterlist.so.12
lrwxrwxrwx 1 root root 41 jul 20 10:59 /usr/lib/x86_64-linux-gnu/libtrilinos_teuchosparameterlist.so.12 -> libtrilinos_teuchosparameterlist.so.12.11

**Comment by bartlettroscoe** [comment]
@RiccardoRossi,

Did you build Trilinos with `-D_GLIBCXX_DEBUG` (using [`-DTrilinos_ENABLE_CHECKED_STL=ON`](https://trilinos.org/docs/files/TrilinosBuildReference.html#enabling-runtime-debug-checking))?  If not, you can expect segfaults.  All C++ software that uses the standard C++ library must all be built with `-D_GLIBCXX_DEBUG` enabled or you will get segfaults.  Note the warning "This option is disabled by default because to enable it by default can cause runtime segfaults when linked against C++ code that was compiled without -D_GLIBCXX_DEBUG." at:

* https://trilinos.org/docs/files/TrilinosBuildReference.html#enabling-runtime-debug-checking

Think about what is happening when you set `-D_GLIBCXX_DEBUG`.  See, for example:

* https://gcc.gnu.org/bugzilla/show_bug.cgi?id=53324

Please let me know if you have any further questions about this.

**Comment by RiccardoRossi** [comment]
@bartlettroscoe , you are right. 
My apologies, i assumed i could transparently add the compile option, but it is not the case.

closing this and ...sorry for the noise

**Comment by bartlettroscoe** [comment]
>  i assumed i could transparently add the compile option, but it is not the case.

Don't worry, some of us were initially confused about this about 10 years ago when we first saw this issue with `-D_GLIBCXX_DEBUG`.

For many compile options, you can get away with mixing and matching them in different translation units.  However, macro defines often have to be consistent in all translation units since it can lead to inconsistent type and forward declarations (like is the case wtih `-D_GLIBCXX_DEBUG` here).
