### ISSUE TITLE
Trilinos compilation error due to Kokkos on Ride with CUDA KokkosNode

### ISSUE THREAD

**Issue by ikalash** [trilinos/Trilinos#1577]
My nightly Trilinos build on ride which uses a CUDA KokkosNode is failing, it looks like due to compilation errors coming from Kokkos: 

/home/projects/albany/repos/Trilinos/packages/kokkos/core/src/impl/Kokkos_ViewMapping.hpp(2905): error: static assertion failed with "View assignment must have compatible spaces"
          detected during:
            instantiation of "void Kokkos::Impl::ViewMapping<DstTraits, SrcTraits, std::enable_if<<expression>, void>::type>::assign(Kokkos::Impl::ViewMapping<DstTraits, SrcTraits, std::enable_if<<expression>, void>::type>::DstType &, const Kokkos::Impl::ViewMapping<DstTraits, SrcTraits, std::enable_if<<expression>, void>::type>::SrcType &, const Kokkos::Impl::ViewMapping<DstTraits, SrcTraits, std::enable_if<<expression>, void>::type>::TrackType &) [with DstTraits=Kokkos::ViewTraits<double *******, Kokkos::LayoutStride, Kokkos::Serial>, SrcTraits=Kokkos::ViewTraits<double *******>]"

/home/projects/albany/repos/Trilinos/packages/kokkos/containers/src/Kokkos_DynRankView.hpp(816): error: static assertion failed with "Incompatible DynRankView copy construction"
          detected during:
            instantiation of "Kokkos::Experimental::DynRankView<DataType, Properties...>::DynRankView(const Kokkos::Experimental::DynRankView<RT, RP...> &) [with DataType=double, Properties=<Kokkos::LayoutStride, Kokkos::Serial>, RT=double, RP=<Kokkos::LayoutStride, Kokkos::Device<Kokkos::CudaUVMSpace::execution_space, Kokkos::CudaUVMSpace::memory_space>, Kokkos::MemoryManaged>]"
/home/projects/albany/repos/Trilinos/packages/intrepid2/refactor/src/Cell/Intrepid2_CellToolsDefJacobian.hpp(162): here

**Comment by ibaned** [comment]
This is a duplicate of #1572, @mperego is working on fixing this today.

**Comment by ibaned** [comment]
Its actually an Intrepid2 issue

**Comment by ikalash** [comment]
Aah, OK.  I will close this duplicate in that case.
