### ISSUE TITLE
Issue and Pull Request Templates?

### ISSUE THREAD

**Issue by jmgate** [trilinos/Trilinos#1583]
@trilinos/framework, has Trilinos ever considered adding `ISSUE_TEMPLATE.md` and `PULL_REQUEST_TEMPLATE.md` files to the repository to attempt to standardize the information we get in an issue or pull request?  If you like, I can mock some up (I have for GitLab, [here](https://gitlab.sandia.gov/jmgate/testingTemplates)), but it occurred to me that this may have come up before and was decided against for some reason.

**Comment by bartlettroscoe** [comment]
It was discussed and was agreed this was a good idea awhile ago.  It is just no one ever pulled the trigger on it.

**Comment by jmgate** [comment]
Shall I go ahead and mock something up and then submit a pull request for you guys to take a look at?

**Comment by allevin** [comment]
The instructions for the PULL_REQUEST_TEMPLATE.md will become important when the Pull Request Automated tester comes online.  I can provide an example of what the SST provides for our templates if desired.

**Comment by jmgate** [comment]
Reopening this issue per @maherou's suggestion.  I'll whip up some example templates and we can iterate on the design.

**Comment by jmgate** [comment]
An initial cut of these templates have made it into `develop` via #1822, though they won't be usable until they make it into `master`.  I'll leave this issue open until the next `develop` to `master` update.

**Comment by jmgate** [comment]
These changes have made it into `master`.  Closing&hellip;

**Comment by bartlettroscoe** [comment]
@jmgate, can we update this to mention that the commit messages on the feature branch `<branchName>` should reference the GitHub Issue ID?  That way, they will get linked back to the original GitHub Issue on GitHub.

The PR is just a mechanism for reviewing the changes and getting them merged but the real tracability should be to the original GitHub Issue.

**Comment by jmgate** [comment]
Good thought @bartlettroscoe.  I do this myself, and just assumed others would, but you're right, it should definitely be spelled out.
