### ISSUE TITLE
Tpetra Dependency to KokkosKernels::Impl namespace

### ISSUE THREAD

**Issue by mndevec** [trilinos/Trilinos#1588]
Impl namespace of Kokkoskernels is intended to be used for internal development purposes. The interface of them as well as their existence are not promised. As a result, the changes to them are not tested for external libraries.

However, there seem to be dependencies to Impl namespace functions in Tpetra. One of them was in multivector and we encountered a problem explained: https://github.com/kokkos/kokkos-kernels/issues/42 

Kokkoskernels has some temporary fixes for targeted August 20 release for such issues. However, it might be better to refactor Tpetra to remove Impl namespace dependencies. 
@kddevin

**Comment by mhoemmen** [comment]
@mndevec Almost all of those kernels came from Tpetra and were imported into the new package, so I wouldn't consider this a defect, merely an accident of history as Tpetra products got removed from Tpetra and made into a separate product.  Nevertheless, I'll be happy to accept a PR that removes this dependency.

**Comment by mndevec** [comment]
Mark, I understand how this happened with the move of kernels out of Tpetra. Yet, it will be better to remove these dependencies for durability of the package.

**Comment by kddevin** [comment]
@mndevec How urgent is this request?  Is it something we should keep in mind in Fy18 as we plan the Tpetra refactor?  Or is it something that needs to be addressed more quickly?  (You mentioned an Aug 20 date.)
Thanks!

**Comment by mndevec** [comment]
This is not an urgent issue, there is no runtime or compile time failures caused by this currently.
 
As Mark pointed out, the issue is because of the move of kernels out of Tpetra. The namespace Impl is intended to be private in the package. However, currently there are Impl functions in KokkosKernels that is not used anywhere in the KokkosKernels, but only used by Tpetra. 

Couple of those Impl functions created errors when KokkosKernels were being refactored. They were only noticed when we integrate KokkosKernels to Trilinos. 

It will be better to identify such uses and move them back to Tpetra in order not to experience these issues.

**Comment by kddevin** [comment]
Clarification:  Needed before Q1 FY18 KokkosKernels release.  The next update is around October or November timeframe. We have an ECP milestone for release of v 1.0 in Q1 FY 2018.
