### ISSUE TITLE
Cleanup Ifpack2 RILUK code

### ISSUE THREAD

**Issue by srajama1** [trilinos/Trilinos#1589]
This is primarily concerned with the confusing experimental piece of code that is in Ifpack2's RILUK. This code can be removed.

**Comment by aprokop** [comment]
@srajama1 There are two defines, `IFPACK2_ILUK_EXPERIMENTAL` and `IFPACK2_HTS_EXPERIMENTAL`. Are you saying that all the code that is in those defines can be removed? This would get rid of Basker, for example.

**Comment by ambrad** [comment]
@srajama1, @aprokop, HTS is explicitly included in RILUK only in support of Basker; the ifdefs for HTS are nested inside those for Basker. We propose to remove Basker (and so HTS with it) from RILUK; Basker was there only for experiments a while ago. Once that is done, as a nice side effect, HTS will be in LocalSparseTriangularSolver only.

**Comment by aprokop** [comment]
@ambrad Thanks for the explanation! Out of curiosity, what's the fate of Basker?

**Comment by ambrad** [comment]
@srajama1 can comment on this more. As I understand it, Basker is highly effective for its intended target of complete factorizations, especially for matrices having a certain structure. It is and will remain available in ShyLU, with I think an Amesos2 interface. But it isn't the best method for a multithreaded *incomplete* factorization, for which it wasn't designed in the first place.

**Comment by srajama1** [comment]
@ambrad summarized it well. It works well as complete factorization especially for problems with BTF structure. The experiment to make it work as ILU(T) was not as effective and should be removed from Ifpack2.

**Comment by aprokop** [comment]
@srajama1 What's BTF?

**Comment by aprokop** [comment]
I have a patch in-progress, will submit a PR soon.

**Comment by ambrad** [comment]
Thanks @aprokop. BTW, BTF = block triangular form. A typical matrix has a range of very small to very large blocks on the diag and dependencies on these blocks that are a tree (and thus give a block tri rather than a general matrix). Rather than factorize such a matrix monolithically, Basker orchestrates threading over factorizations of each block, then doing a solve with the triangular structure.

**Comment by aprokop** [comment]
Pushed in c0d440c2c7.
