### ISSUE TITLE
ROL_test_sol_checkAlmostSureConstraint_MPI_1 Timeout

### ISSUE THREAD

**Issue by ibaned** [trilinos/Trilinos#1596]
I'm trying to use the checkin script and getting a ROL test timeout:
```
        Start 2006: ROL_adapters_epetra_test_vector_EpetraMultiVectorInterface_MPI_4
2153/2311 Test #2066: ROL_test_sol_checkAlmostSureConstraint_MPI_1 ........................................................***Timeout 300.09 sec
```
Positive my change can't affect ROL...

@trilinos/rol @trilinos/framework

**Comment by dridzal** [comment]
This is strange error that we've been trying to debug for some time now.  The algorithm behaves differently with one or two compiler versions.  It works fine for most compiler versions.  Can you run this test separately and paste the output below?  The last 10 or so lines of output should suffice (after the algorithm starts).  Thanks.

**Comment by bartlettroscoe** [comment]
@ibaned,

This test is shown as currently passing in the standard CI build at:

* https://testing.sandia.gov/cdash/viewTest.php?onlypassed&buildid=3048656

and it passes in under 2 sec.

That suggests that the test might have some memory issues and might be taking advantage of some some undefined behavior.

I saw you did a forced push in your commit:

```
commit 51407400ba747c122287c0cb2bc9722ed3b8b19b
Author:     Dan Ibanez <daibane@sandia.gov>
AuthorDate: Thu Aug 10 09:19:26 2017 -0600
Commit:     Dan Ibanez <daibane@sandia.gov>
CommitDate: Thu Aug 10 13:12:40 2017 -0600

    Teuchos: raise Parser sub-package to PS status
    
    This will trigger regular testing which provides
    more vetting for this sub-package to be eventually
    used by other Trilinos packages.
    
    Build/Test Cases Summary
    Enabled Packages: Teuchos
    Disabled Packages: PyTrilinos,Claps,TriKota
    Enabled all Forward Packages
    0) MPI_RELEASE_DEBUG_SHARED_PT => FAILED: passed=2310,notpassed=1 => Not ready to push! (218.23 min)
    WARNING: Forced the push!
```

That is okay in this case.  But in general, it is dangerous to to use that option.

Instead, it is better to disable that test locally as described at:

* https://github.com/trilinos/Trilinos/wiki/Policies-|-Safe-Checkin-Testing#disable_already_failing

That way we can see what test got disabled and you don't need to use `--force-push` as a habit.

@dridzal,

If this test is known to fail randomly, then is should be removed from the pre-push test suite so that it does not trip up other people.

**Comment by ibaned** [comment]
Well, I just ran it 5 more times from the build generated by the checkin test, and there is non-deterministic behavior. The very first run actually passed in 25 seconds, while the four runs after that failed in around 280 seconds. Here is a tarball of output text from both runs: 
[rol_runs.tar.gz](https://github.com/trilinos/Trilinos/files/1216260/rol_runs.tar.gz)

@bartlettroscoe the link you sent actually shows it taking 25 seconds, not 2 seconds, which is consistent with my first, successful run. (https://testing.sandia.gov/cdash/testDetails.php?test=40310813&build=3048656)

I recommend this test be removed from pre-push testing until this is figured out.

Does ROL use its own threading outside Kokkos? Does it use non-deterministic random number generators? I'm surprised to see non-deterministic behavior in a test with no parallism, threaded or MPI.

**Comment by bartlettroscoe** [comment]
@ibaned,

> @bartlettroscoe the link you sent actually shows it taking 25 seconds, not 2 seconds, which is consistent with my first, successful run. (https://testing.sandia.gov/cdash/testDetails.php?test=40310813&build=3048656)

You are correct.  Sorry.  I grepped the wrong test.

> I recommend this test be removed from pre-push testing until this is figured out.

I agree.

@dridzal, we can remove this test only for the checkin-test.py script.  That way, these tests will show up in other CDash builds (including all local builds) but will not impact the robustness of the pre-push testing.

**Comment by dridzal** [comment]
This example does not use a nondeterministic random number generator.  @bartlettroscoe , please feel free to disable this test for the checkin-test.py script in the develop branch.

**Comment by ibaned** [comment]
Confirmation of instability by the CI system:
https://testing.sandia.gov/cdash/testDetails.php?test=40585145&build=3048731

**Comment by bartlettroscoe** [comment]
I just pushed the commit:

```
commit 228e44d5918a2d700ef0c454f2feb6c012166091
Author: Roscoe A. Bartlett <rabartl@sandia.gov>
Date:   Fri Aug 11 08:47:07 2017 -0600

    Disable failing test ROL_test_sol_checkAlmostSureConstraint_MPI_1 in CI build (#1596, #1304)
    
    This test started failing after being triggered by a simple change to Teuchos
    that should not have impacted this.  This test is being disabled for the
    standard CI build until it can be fixed.  However, it will run in all other
    builds, local and on CDash.

M       cmake/std/BasicCiTestingSettings.cmake
```

I tested the configure with the checkin-test-sems.sh build and it shows:

```
-- Setting ROL_test_sol_checkAlmostSureConstraint_MPI_1_DISABLE='ON' by default for standard PT CI build

-- ROL_test_sol_checkAlmostSureConstraint_MPI_1: NOT added test because ROL_test_sol_checkAlmostSureConstraint_MPI_1_DISABLE='ON'!
```

@dridzal,

Once this test can be fixed, it can be re-enabled for CI testing.

**Comment by bartlettroscoe** [comment]
NOTE: the standard CI build has that test failing and not just timing out as shown by:

* https://testing.sandia.gov/cdash/testDetails.php?test=40585145&build=3048731

**Comment by ibaned** [comment]
Yep. when this test goes wrong it outputs the wrong answer, and takes close to the timeout time to do so. I ran it on a more heavily loaded machine which I guess pushed it up from 280 seconds to the timeout of 300 seconds.

**Comment by bartlettroscoe** [comment]
Note, to fix this, someone needs to **first** revert the disable commit in your local `develop` branch with:

```
$ git pull
$ git revert 228e44d5918a2d700ef0c454f2feb6c012166091
```

then add the new commits and push.

**Comment by dridzal** [comment]
We are ready to re-enable this test, but I don't know how to fit this into our current workflow where ROL develop and Trilinos develop are merged automatically.  @bartlettroscoe , do I have to perform the merge without enabling the test, then go into Trilinos develop, run git revert, and then merge ROL develop and Trilinos develop again?

**Comment by bartlettroscoe** [comment]
@dridzal,

> We are ready to re-enable this test, but I don't know how to fit this into our current workflow where ROL develop and Trilinos develop are merged automatically. @bartlettroscoe , do I have to perform the merge without enabling the test, then go into Trilinos develop, run git revert, and then merge ROL develop and Trilinos develop again?

Just run the command:

```
$ git revert 228e44d5918a2d700ef0c454f2feb6c012166091
```

in your local git repo just like any regular commit.  The checkin-test-sems.sh script will then enable that test and will confirm if that test is working or not and once your final sync process pushes to the Trilinos GitHub 'develop' branch, it will get enabled automatically in the post-push CI build linked to from:

* https://github.com/trilinos/Trilinos/wiki/Policies--%7C-Testing#post_push_ci_testing

**Comment by dridzal** [comment]
I see;  this is because my ROL-Trilinos repo has the full history of the Trilinos repo, and commit

`228e44d5918a2d700ef0c454f2feb6c012166091`

is known to it, correct?  Do I need to run git push after reverting?

**Comment by bartlettroscoe** [comment]
> I see; this is because my ROL-Trilinos repo has the full history of the Trilinos repo, and commit
> 
> 228e44d5918a2d700ef0c454f2feb6c012166091
> 
> is known to it, correct?

Yup.  That is he git distributed model.  History is replicated in all repos for branches in those repos.

> Do I need to run git push after reverting?

Yes.  But just push with the checkin-test-sems.sh script as you normally would.  And rebasing is just fine.

**Comment by dridzal** [comment]
This revert will happen in the ROL-Trilinos repo, so I can just push, I think (I already know that all tests are passing).  The pre-push testing for Trilinos will happen next time I merge.

**Comment by dridzal** [comment]
This test now passes in the CI build.
