### ISSUE TITLE
missing Kokkos_OpenMPNode in xpetra

### ISSUE THREAD

**Issue by lucbv** [trilinos/Trilinos#1599]
@trilinos/xpetra @trilinos/muelu 
While working on an unrelated (#1597) pull request I discovered that Xpetra does not compile if the following configuration is chosen:
```
-D Trilinos_ENABLE_Kokkos=OFF \
-D Trilinos_ENABLE_Tpetra=OFF \
-D Trilinos_ENABLE_OpenMP=ON \
```
This might happen if you want openmp with the Epetra stack.
The problem is that in ```xpetra/src/FakeKokkos``` a class is missing for ```Kokkos_OpenMPWrapperNode``` which then create problems with typedef of EpetraNode.
A simple fix is to create said class.

**Comment by mhoemmen** [comment]
@lucbv I've seen something like this too.

**Comment by lucbv** [comment]
As far as I can see MueLu now compiles just fine with Epetra only and OpenMP enabled so I will close this issue.
Thanks @tawiesn
