### ISSUE TITLE
Panzer: Build failures with AdaptersIOSS on/Zoltan2 off

### ISSUE THREAD

**Issue by eric-c-cyr** [trilinos/Trilinos#1601]
I get a reasonable build failure for this case (can't find a Zoltan2 file). If a user is not using Zoltan2, can we disable the building of AdaptersIOSS? What is the right approach here?

**Comment by eric-c-cyr** [comment]
Also the file it can't find is: Zoltan2_findUniqueGids.hpp

**Comment by rppawlo** [comment]
about to push fix

**Comment by rppawlo** [comment]
Should be fixed.
