### ISSUE TITLE
Amesos_Superlu fails during compilation

### ISSUE THREAD

**Issue by anates** [trilinos/Trilinos#1612]
Compilation using GCC-6.3.0 with the current version of SuperLU and Trilinos, I am getting the errors

> ~/Downloads/Trilinos-master/packages/amesos/src/Amesos_Superlu.cpp: In element function »virtual int Amesos_Superlu::NumericFactorization()«:
> ~/Downloads/Trilinos-master/packages/amesos/src/Amesos_Superlu.cpp:484:22: Error: »SLU::mem_usage_t*« can not be converted from »SLU::GlobalLU_t*« for argument »19« to »void SLU::dgssvx(SLU::superlu_options_t*, SLU::SuperMatrix*, int*, int*, int*, char*, double*, double*, SLU::SuperMatrix*, SLU::SuperMatrix*, void*, int, SLU::SuperMatrix*, SLU::SuperMatrix*, double*, double*, double*, double*, SLU::GlobalLU_t*, SLU::mem_usage_t*, SLU::SuperLUStat_t*, int*)« 
>              &Ierr[0] );
>                       ^
> ~/Downloads/Trilinos-master/packages/amesos/src/Amesos_Superlu.cpp: In element function »virtual int Amesos_Superlu::Solve()«:
> /home/rolandar/Downloads/Trilinos-master/packages/amesos/src/Amesos_Superlu.cpp:615:18: Error »SLU::mem_usage_t*« can not be converted from »SLU::GlobalLU_t*« for argument »19« to »void SLU::dgssvx(SLU::superlu_options_t*, SLU::SuperMatrix*, int*, int*, int*, char*, double*, double*, SLU::SuperMatrix*, SLU::SuperMatrix*, void*, int, SLU::SuperMatrix*, SLU::SuperMatrix*, double*, double*, double*, double*, SLU::GlobalLU_t*, SLU::mem_usage_t*, SLU::SuperLUStat_t*, int*)« 
>              &Ierr);
Is that a known bug, or did I do something wrong?

**Comment by bavier** [comment]
This is a known limitation.  See https://github.com/trilinos/Trilinos/pull/411

**Comment by anates** [comment]
Any suggestion for a fix? Should I exclude SuperLu, or Amesos?

**Comment by mhoemmen** [comment]
@trilinos/amesos

**Comment by bavier** [comment]
@anates You could apply the patch in #411 locally.

**Comment by anates** [comment]
Added that patch, did not fix the problem.

**Comment by anates** [comment]
Fixed it by directly applying the #define-directives in the two cpp-files.

**Comment by tuckerhartland** [comment]
@anates I am now having the same issue. From this conversation I do not understand which #define-directives should be applied to which two cpp-files.
