### ISSUE TITLE
Issues with TentativePFactory for "use kokkos refactor"=true  on KNL?

### ISSUE THREAD

**Issue by pwxy** [trilinos/Trilinos#1613]
I built drekar for develop Trilinos (cloned repo early Mon Aug 14 morning).

I built on ellis for KNL with intel 17 compiler 
with the following cmake options
```
-D Tpetra_ENABLE_MMM_Timings=ON \

-D MueLu_ENABLE_Experimental:BOOL=ON \
-D MueLu_ENABLE_Kokkos_Refactor:BOOL=ON \

-D Xpetra_ENABLE_Experimental:BOOL=ON \
-D Xpetra_ENABLE_Kokkos_Refactor:BOOL=ON \
```

the MueLu setup time for the drekar run was 14.6 sec for 1 MPI with 16 OMP threads.

I then added:

`<Parameter name="use kokkos refactor"   type="bool"  value="true"/>`

to the MueLu parameter list

and the MueLu setup time increased to 3557s, or 244x slower

Here are all the MueLu setup timers that are over 100s:

```
 3557.00000  MueLu: N5MueLu9HierarchyIdixN6Kokkos6Compat23KokkosDeviceWrapperNodeINS1_6OpenMPENS1_9HostSpaceEEEEE: Setup (total)
 3557.00000  MueLu: N5MueLu9HierarchyIdixN6Kokkos6Compat23KokkosDeviceWrapperNodeINS1_6OpenMPENS1_9HostSpaceEEEEE: Setup (total, level=1)
 3557.00000  MueLu: N5MueLu10RAPFactoryIdixN6Kokkos6Compat23KokkosDeviceWrapperNodeINS1_6OpenMPENS1_9HostSpaceEEEEE: Computing Ac (total)
 3557.00000  MueLu: N5MueLu18RepartitionFactoryIdixN6Kokkos6Compat23KokkosDeviceWrapperNodeINS1_6OpenMPENS1_9HostSpaceEEEEE: Build (total)
 3557.00000  MueLu: N5MueLu24RebalanceTransferFactoryIdixN6Kokkos6Compat23KokkosDeviceWrapperNodeINS1_6OpenMPENS1_9HostSpaceEEEEE: Build (total, level=1)
 3557.00000  MueLu: N5MueLu18RepartitionFactoryIdixN6Kokkos6Compat23KokkosDeviceWrapperNodeINS1_6OpenMPENS1_9HostSpaceEEEEE: Build (total, level=1)
 3557.00000  MueLu: N5MueLu24RebalanceTransferFactoryIdixN6Kokkos6Compat23KokkosDeviceWrapperNodeINS1_6OpenMPENS1_9HostSpaceEEEEE: Build (total)
 3556.00000  MueLu: N5MueLu10RAPFactoryIdixN6Kokkos6Compat23KokkosDeviceWrapperNodeINS1_6OpenMPENS1_9HostSpaceEEEEE: Computing Ac (total, level=1)
 3554.00000  MueLu: N5MueLu24TentativePFactory_kokkosIdixN6Kokkos6Compat23KokkosDeviceWrapperNodeINS1_6OpenMPENS1_9HostSpaceEEEEE: Build (total)
 3554.00000  MueLu: N5MueLu24TentativePFactory_kokkosIdixN6Kokkos6Compat23KokkosDeviceWrapperNodeINS1_6OpenMPENS1_9HostSpaceEEEEE: Build (total, level=1)
 3391.00000  MueLu: N5MueLu24TentativePFactory_kokkosIdixN6Kokkos6Compat23KokkosDeviceWrapperNodeINS1_6OpenMPENS1_9HostSpaceEEEEE: Stage 1 (LocalQR) (sub, total)
 3391.00000  MueLu: N5MueLu24TentativePFactory_kokkosIdixN6Kokkos6Compat23KokkosDeviceWrapperNodeINS1_6OpenMPENS1_9HostSpaceEEEEE: Build (level=1)
 3391.00000  MueLu: N5MueLu24TentativePFactory_kokkosIdixN6Kokkos6Compat23KokkosDeviceWrapperNodeINS1_6OpenMPENS1_9HostSpaceEEEEE: Build
 3391.00000  MueLu: N5MueLu24TentativePFactory_kokkosIdixN6Kokkos6Compat23KokkosDeviceWrapperNodeINS1_6OpenMPENS1_9HostSpaceEEEEE: Stage 1 (LocalQR) (sub, total, level=1)

  163.10000  MueLu: N5MueLu34UncoupledAggregationFactory_kokkosIixN6Kokkos6Compat23KokkosDeviceWrapperNodeINS1_6OpenMPENS1_9HostSpaceEEEEE: Build (total)
  163.00000  MueLu: N5MueLu34UncoupledAggregationFactory_kokkosIixN6Kokkos6Compat23KokkosDeviceWrapperNodeINS1_6OpenMPENS1_9HostSpaceEEEEE: Build (total, level=0)
  161.10000  MueLu: N5MueLu26CoalesceDropFactory_kokkosIdixN6Kokkos6Compat23KokkosDeviceWrapperNodeINS1_6OpenMPENS1_9HostSpaceEEEEE: Build (total)
  161.10000  MueLu: N5MueLu26CoalesceDropFactory_kokkosIdixN6Kokkos6Compat23KokkosDeviceWrapperNodeINS1_6OpenMPENS1_9HostSpaceEEEEE: Build (total, level=0)
  160.90000  MueLu: N5MueLu26CoalesceDropFactory_kokkosIdixN6Kokkos6Compat23KokkosDeviceWrapperNodeINS1_6OpenMPENS1_9HostSpaceEEEEE: Build (level=0)
  160.90000  MueLu: N5MueLu26CoalesceDropFactory_kokkosIdixN6Kokkos6Compat23KokkosDeviceWrapperNodeINS1_6OpenMPENS1_9HostSpaceEEEEE: Build
```

Edit (@aprokop): added quoting

**Comment by jhux2** [comment]
@pwxy Something appears to be missing from your comment "I then added ...".

**Comment by aprokop** [comment]
@jhux2 "use kokkos refactor" set to true was added (by @pwxy )

**Comment by aprokop** [comment]
@jhux2 Do we have any performance results in MueLu team after @tawiesn refactored the `TentativePFactory`?

**Comment by jhux2** [comment]
@jjellio has timings for scalar PDEs.  Perhaps he can comment.

**Comment by jhux2** [comment]
@pwxy @aprokop Btw, we know that the QR is not optimized.  I'll bet that @jjellio did not see this, precisely because he was running the scalar PDE case.  Batched QR is something that might be provided by KokkosKernels.

**Comment by jjellio** [comment]
We saw poor performance of TentativeP w/OpenMP. Chris patched this in June, but the patched version was still ~3x slower than the previous (non Kokkos) version of TentativeP.

The performance with "use kokkos refactor=ON"  was so slow that I had to disable it to get complete results. The hit was about 1000x over the non kokkos version.  With csiefert's patch, the overhead drops to around 3x, but still enough that it can cause problems.

**Comment by tawiesn** [comment]
@jjellio @pwxy Did you test scalar problems or vector-based problems?

**Comment by tawiesn** [comment]
@aprokop I did not refactor the TentativePFactory. I just added the vector case to the kokkos version of TentativePFactory. I wrote my own tiny stupid slow QR decomposition using Kokkos in order to validate the correctness of the results. I did not do any performance tests as the results are clear to be frustrating. Before putting more effort in the MueLu kernels it would make more sense to push KokkosKernels forward to provide all the basic algorithms that we and others might need. Imho everything else would be a waste of time.

**Comment by aprokop** [comment]
I will work on profiling and optimizing the `TentativePFactory` this week. The funny thing is that even with a single thread OpenMP is 3x slower for scalar. Should not be too hard to at least get parity for single thread per MPI rank.

**Comment by jjellio** [comment]
@tawiesn, I tested scalar: Laplace3D / Brick3D. GO = long long int, LO = int, SC = double.

If you cannot access the website where I've uploaded all of my data/figures, I can tar and send it to you. (It is served from my SRN workstation). I have 2 identical studies, one with use kokkos refactor = ON and one with it off.  The two studies use a patch by csiefert that improved the performance significantly, but it still measured 3x over the non refactor case.

I'd take the results I have with a grain of salt - We saw extremely variations in performance. Since then, I have worked to reduce that. The work is entirely on the system/OS end. (E.g., how you compile/run the app. My OpenMP environment has actually stayed the same though.) For a 1024 node run (65k MPI procs), I measured a 5x runtime improvement using different job launch options + build settings. 

I've asked @jhux2 about rerunning the muelu study. Reducing the noise will make it much clearer where thread scaling issues are (currently they are dominated by the noise).

**Comment by aprokop** [comment]
@jjellio FYI: I'm currently working on optimizing the scalar MueLu/Kokkos which should improve performance. If you are all set up, please give `kokkos` branch from `aprokop/Trilinos` a whirl on NERSC.

**Comment by aprokop** [comment]
I've looked at the current implementation of the block branch of the Tentative P factory. It is quite suboptimal, and used dense matrix-matrix multiplications instead of utilizing properties of Householder rotations. So, instead of n^3 complexity we get n^4. I have a fix in progress. It will be merged later with other improvements that are currently in the kokkos branch in aprokop/Trilinos.

**Comment by mhoemmen** [comment]
@aprokop wrote:
> ... [A]s what I have right now is a texbook implementation for rectangular QR ....

I could use that for other reasons -- nice!

**Comment by aprokop** [comment]
@mhoemmen The only minor caveat is what we do for fat matrices, this is is multigrid specific. Square and tall are textbook.

**Comment by aprokop** [comment]
@jjellio The scalar case (which I assume you meant when talking about 3x slower) is now much improved:
```
timer name                                                           old        new      ratio
MueLu: RAPFactory: Computing Ac (level=1)                          2.539      1.034       0.41
MueLu: Ifpack2Smoother: Setup Smoother (level=0)                   0.888      0.824       0.93
MueLu: RAPFactory: Computing Ac (level=2)                          0.684      0.180       0.26
MueLu: SaPFactory_kokkos: Prolongator smoothing (level=1)          0.631      0.640       1.01
MueLu: TentativePFactory_kokkos: Build (level=1)                   0.452      0.123       0.27
MueLu: Ifpack2Smoother: Setup Smoother (level=1)                   0.214      0.207       0.97
MueLu: UncoupledAggregationFactory_kokkos: Build (level=0)         0.155      0.072       0.47
MueLu: CoordinatesTransferFactory_kokkos: Build (level=1)          0.086      0.029       0.34
MueLu: SaPFactory_kokkos: Prolongator smoothing (level=2)          0.083      0.083       1.01
MueLu: UncoupledAggregationFactory_kokkos: Build (level=1)         0.056      0.039       0.70
```

@pwxy The block case is much improved, tut it's still extremely slow for both tentative factory and coalesce drop factory compared to the non-Kokkos variant (about 20x slowdown for Tentative factory, and worse for CoalesceDrop), and not suitable for human consumption at the moment. If you need to run it soon, I could spend more time on it.
```
timer name                                                           old        new      ratio                                                                
MueLu: TentativePFactory_kokkos: Build (level=1)                  11.677      0.379       0.03                                                                
MueLu: CoalesceDropFactory_kokkos: Build (level=0)                 8.007      7.958       0.99                                                                
MueLu: RAPFactory: Computing Ac (level=1)                          1.331      0.322       0.24                                                                
MueLu: Ifpack2Smoother: Setup Smoother (level=0)                   0.287      0.282       0.98                                                                
MueLu: CoalesceDropFactory_kokkos: Build (level=1)                 0.233      0.235       1.01                                                                
MueLu: TentativePFactory_kokkos: Build (level=2)                   0.184      0.009       0.05                                                                
MueLu: SaPFactory_kokkos: Prolongator smoothing (level=1)          0.111      0.104       0.94                                                                
MueLu: RAPFactory: Computing Ac (level=2)                          0.044      0.010       0.24 
```
