### ISSUE TITLE
Trilinos compilation error due to missing aprepro.h header

### ISSUE THREAD

**Issue by ikalash** [trilinos/Trilinos#1614]
I just pulled a recent develop Trilinos and am getting the following compilation error: 

/home/ikalash/nightlyAlbanyTests/Results/Trilinos/packages/stk/stk_util/stk_util/parallel/mpi_filebuf.cpp:43:21: fatal error: aprepro.h: No such file or directory
 #include <aprepro.h>
                     ^
compilation terminated.

I believe this is due to commit e15b6358a6aa24d080ef9840816d1c3c47df5fd8 by @gsjaardema .

**Comment by bmpersc** [comment]
@ikalash this is related to the update of stk and seacas I did earlier today. I will look into it. Your report doesn't state this, but I'm assuming you are getting this when you build against an installed Trilinos. Is this correct?

**Comment by ikalash** [comment]
No, I encountered this while building a new Trilinos after pulling the develop branch.

**Comment by bmpersc** [comment]
@ikalash I think I see the problem, there was a very unusual preprocessor protection put in around the include of the aprepro headers "#if !defined(NOT_HAVE_STK_SEACASAPREPRO_LIB)" I can't tell why and it seems the necessary define is never set anywhere so the aprepro headers are still included always, which was the previous behavior. Aprepro is an optional dependency of stk_util so I'm guessing that you don't have it enabled. I will need to talk with the STK folks about this before I can figure out what the right solution is. In the mean time you should be able to get around this by enabling the SEACASAprepro_lib subpackage.

**Comment by ibaned** [comment]
The Kokkos team is trying to do a promotion into Trilinos today... is it possible in the future to use the `checkin-test-sems.sh` script to push things like SEACAS and STK snapshots? Kokkos does this.

**Comment by bmpersc** [comment]
@ibaned This isn't the right place to discuss the details of the checkin test script, but the answer is a strong no and it wouldn't have caught this anyway since aprepro had changed it would have been enabled by that tool anyway.

**Comment by ikalash** [comment]
@bmpersc : thanks.  I just tried it out and adding -DTrilinos_ENABLE_SEACASAprepro_lib:BOOL=ON does fix the compilation error I was seeing.  I will add it for now to the Albany nightly Trilinos test scripts so the nightlies don't fail.

**Comment by crtrott** [comment]
I also just ran into this thing ..

**Comment by bmpersc** [comment]
@ikalash @crtrott This issue has been fixed on the develop branch. There was an issue with headers being out of order for this file which caused it to still depend on aprepro when it wasn't enabled. The most recent sync from STK has pulled over the fix. Please give it a try and let me know if you are still having issues when aprepro is disabled.

**Comment by bmpersc** [comment]
Changed labels to better reflect where the issue actually was.

**Comment by mhoemmen** [comment]
Thanks @bmpersc ! :D
