### ISSUE TITLE
Zoltan2 with parmetis

### ISSUE THREAD

**Issue by anates** [trilinos/Trilinos#1621]
Cmake reports 
```
CMake Error at packages/zoltan2/CMakeLists.txt:8 (MESSAGE):
  Zoltan2 requires ParMETIS_version 4.0.3 or later.  Upgrade or set
  TPL_ENABLE_ParMETIS OFF or set Zoltan2_ENABLE_ParMETIS OFF.
```
even though I am using the latest version of ParMETIS. How can I fix that?
Thanks!

**Comment by ibaned** [comment]
@trilinos/zoltan2

**Comment by kddevin** [comment]
Make sure CMake is looking at the expected version of ParMETIS by specifying the paths to ParMETIS' libraries and include files; for example, give CMake the following arguments:
-D Zoltan2_ENABLE_ParMETIS:BOOL=ON \
-D ParMETIS_LIBRARY_DIRS:FILEPATH="/Users/anybody/InstalledSoftware/ParMETIS_4.0.3/32bit" \
-D ParMETIS_INCLUDE_DIRS:FILEPATH="/Users/anybody/InstalledSoftware/ParMETIS_4.0.3/32bit" \
