### ISSUE TITLE
Failing MueLu ParameterList test

### ISSUE THREAD

**Issue by ibaned** [trilinos/Trilinos#1625]
https://testing.sandia.gov/cdash/testDetails.php?test=40748053&build=3062363

@trilinos/muelu

**Comment by aprokop** [comment]
Introduced in 5eeea4070a37f328a862229401765a7454cc0494. Running the checkin script should have caught this. The problem of introducing a new parameter in Ifpack2 is that MueLu has tests with gold output which dump the parameter values in all smoothers. Thus, any update in Ifpack2 parameters requires updating MueLu's gold files. Not a big deal, though.

**Comment by ibaned** [comment]
@trilinos/ifpack2 to make sure they're aware.

It does look simple to fix, but it will block other people's checkin-based pushes till fixed.

**Comment by aprokop** [comment]
I'm working on this. Should be easy to fix but then I had tests hang for no apparent reason this week, so who knows.

**Comment by aprokop** [comment]
The hang is still there, but it's a separate issue (#1626). The checkin is running.

**Comment by aprokop** [comment]
Pushed in a93e979917b2c9e0869d8009897479672f6a553e.
