### ISSUE TITLE
MueLu: enabling timer synchronization hangs some interface tests

### ISSUE THREAD

**Issue by aprokop** [trilinos/Trilinos#1626]
@trilinos/muelu 

When MueLu is configured with `-D MueLu_ENABLE_TIMER_SYNCHRONIZATION=ON`, we add barriers for each before and after each factory `Build()` call. This is done in `SingleLevelFactory` and `TwoLevelFactory`. The idea is to make sure the factory timers do not affect each other.

For some reason, this no longer works with some of the interface tests. Two standard tests hang. Not sure which input decks they are.

This needs immediate attention as this may mean that timer sync is not as robust as expected. This is news to me.

**Comment by aprokop** [comment]
Only reuse input decks fail.

**Comment by aprokop** [comment]
No idea what's going on. The only reuse tests that pass are full reuse and reuse-RP-1. The difference between reuse-RP-1 and reuse-RP-2 is that RP-2 does implicit rebalancing. Also, reuse-RP-2 can be made to pass if we don't restrict subcommunicators.

So, there is something about rebalancing/subcommunicators/implicit that makes the hang.

**Comment by tawiesn** [comment]
@lucbv This might be something we have to consider when working on #1466
