### ISSUE TITLE
MueLu: Remove optional Isorropia dependency?

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#1627]
@trilinos/muelu 
@aprokop 
Fixing of #1414 suggests that MueLu can remove its optional library dependency on Isorropia (see Line 3 of https://github.com/trilinos/Trilinos/blob/develop/packages/muelu/cmake ).  Is this the case?  Thanks!

**Comment by aprokop** [comment]
@mhoemmen No, I think you still can use Isorropia with Epetra interface. I don't know of any users of this interface, though, but @tawiesn may know.

**Comment by tawiesn** [comment]
@mhoemmen We cannot remove the Isorropia dependency. @aprokop is right: we still can use Isorropia with the Epetra stack and i actually use it for different projects.

**Comment by mhoemmen** [comment]
@aprokop @tawiesn Thanks for the answers!  I didn't realize MueLu used Isorropia through its Epetra interface.  I'll close this issue then.
