### ISSUE TITLE
Incomplete type in Teuchos with Amesos and SuperLU

### ISSUE THREAD

**Issue by anates** [trilinos/Trilinos#1635]
When compiling Trilinos with Amesos2 and/or SuperLU, I get:
```
~/Downloads/Trilinos/Trilinos/packages/teuchos/core/src/Teuchos_as.hpp:2857:61: error: incomplete type 'Teuchos::ValueTypeConversionTraits<std::complex<double>, Amesos2::PMKL::_DOUBLE_COMPLEX_t>' used in nested name specifier
   return ValueTypeConversionTraits<TypeTo,TypeFrom>::convert(t);
```
Is there a fix for that?

**Comment by ibaned** [comment]
@trilinos/amesos2

**Comment by aprokop** [comment]
Does adding `-D Teuchos_ENABLE_COMPLEX=ON` make a difference?

**Comment by srajama1** [comment]
Can you add your configure options ?

**Comment by anates** [comment]
Can be closed, no longer an issue (I think I could fix it with a clean rebuild)

**Comment by anates** [comment]
Can be closed, no longer an issue (I think I could fix it with a clean rebuild)

**Comment by mhoemmen** [comment]
Thanks for the info!
