### ISSUE TITLE
Zoltan id type

### ISSUE THREAD

**Issue by gsjaardema** [trilinos/Trilinos#1637]
If I am building against and linking to a zoltan library, is there a way to determine what the ZOLTAN_ID_TYPE was during the build and installation of the library.

It looks like the ZOLTAN_ID_TYPE is dependent upon the compiler defines and that the value isn't written to a configuration file or include file anywhere.  It appears in zoltan_types.h, but its value depends on the compile flags (whether `UNSIGNED_INT_GLOBAL_IDS`, `UNSIGNED_LONG_GLOBAL_IDS` or `UNSIGNED_LONG_LONG_GLOBAL_IDS` is defined.

What I need is a way to determine while compiling my code what size to use for ZOLTAN_ID_TYPE without knowing the compiile flags used for the zoltan library.  The library itself was built with a specific setting for this, so I can't just define it as I see fit later on, but I don't see anything in any include files that can tell me what it was set to.

Hopefully I am just overlooking something obvious.

Thanks,
@gdsjaar

**Comment by mhoemmen** [comment]
@trilinos/zoltan @trilinos/zoltan2

**Comment by gsjaardema** [comment]
Never mind.  I see Zoltan_config.h.  I was only looking at the small z includes and missed it.
