### ISSUE TITLE
Teuchos: timers seem to overflow somehow

### ISSUE THREAD

**Issue by aprokop** [trilinos/Trilinos#1639]
In a run, we got the following results in the final `summarize()` call for Teuchos timers:

```
Belos: ICGS[2]: Ortho (Inner Product) -8613 (2.173e+04) 114.9 (2.173e+04)  617.8 (2.173e+04) 0.00529 (2.173e+04)
...
MueLu: Hierarchy: Setup (total)           -6721 (600)       1532 (676.1)       2193 (992)        2.266 (676.1)
```
So, somehow, the times become negative. More investigation shows that for instance for the MueLu hierarchy setup timers, they accumulate till about 406 seconds, and go negative the next setup. 

This sounds like an integer overflow problem though totally unclear how integers are involved.

The run was done on 1152 processors.

**Comment by aprokop** [comment]
@trilinos/teuchos @jhux2

**Comment by mhoemmen** [comment]
`Teuchos::Time` uses `double` for times, but `int` for call counts.  Could the latter matter?

**Comment by jhux2** [comment]
@aprokop Are you in a position where you could run Nalu to try to duplicate?  While I can't see how this might be, I'm worried this is due to either the cluster I'm running on or my local module environment.

**Comment by aprokop** [comment]
@jhux2 Probably not. I could try, but not at the core counts you ran. And it's unclear how to reproduce the problem. One thing I wonder about is whether it somehow ends up using `clock()` which *will* overflow with time. It shouldn't and the code in `Teuchos_Time.cpp` indicates that it should use `MPI_Wtime()` if MPI is enabled and initialized(), but I wonder.

**Comment by aprokop** [comment]
@mhoemmen I don't think so. The negative time is only for the minimum of local times, so I assume that there is a single processor that goes negative.

**Comment by aprokop** [comment]
@jhux2 Can you please provide more info about the environment the run was done in? Specifically, mpi and gcc versions.

I found [this](https://bugzilla.redhat.com/show_bug.cgi?id=1473440) and [this](https://github.com/open-mpi/ompi/issues/3003) which seems to indicate some bugs in OpenMPI `MPI_Wtime` implementations.

**Comment by jhux2** [comment]
@aprokop wrote:
> @jhux2 Can you please provide more info about the environment the run was done in? Specifically, mpi and gcc versions.

```
> icc --version
icc (ICC) 17.0.0 20160721
Copyright (C) 1985-2016 Intel Corporation.  All rights reserved.

> mpiexec --version
mpiexec (OpenRTE) 1.10.5
```

**Comment by jhux2** [comment]
> I found this and this which seems to indicate some bugs in OpenMPI MPI_Wtime implementations.

Well, that describes my case exactly, and it's the same version.  Nice catch!

**Comment by aprokop** [comment]
@jhux2 Is it possible to try with a different version?

**Comment by jhux2** [comment]
> @jhux2 Is it possible to try with a different version?

Yep, that's the plan.

**Comment by jhux2** [comment]
I reran the same executable on another cluster (Broadwells, not Haswells), and the timers are sensible for those runs.  @aprokop I'll send the logs to you.

**Comment by aprokop** [comment]
OK, the probable cause for negative timers is identified. Most likely reason is a bug in `MPI_Wtime` for some OpenMPI versions. Specific versions known to be affected (from the corresponding linked bugs): 1.10.5, 1.10.6, 2.0.2. In general, 1.10.0 through 1.10.6 versions seem problematic, see [this comment](https://github.com/open-mpi/ompi/issues/3003#issuecomment-298894576).
