### ISSUE TITLE
Request to expose Zoltan_get_global_id_type() in public API

### ISSUE THREAD

**Issue by gsjaardema** [trilinos/Trilinos#1640]
I would like to request that the function `Zoltan_get_global_id_type()` be exposed in the public API.  This function is currently defined in `packages/zoltan/src/zz/zz_util.c`, but is not declared in any of the zoltan public include files.  

It is useful to me in detecting whether the library I am linking to was compiled with the same setting for the `ZOLTAN_ID_TYPE` as was active during the build of my application or as a sanity check that the include files I am reading are compatible with the link library.

In my code, I can do:
```
    int lib_global_id_type_size = Zoltan_get_global_id_type(nullptr);
    if (lib_global_id_type_size != sizeof(ZOLTAN_ID_TYPE)) {
      std::ostringstream errmsg;
      errmsg << "ERROR: The compile-time ZOLTAN_ID_TYPE size (" << sizeof(ZOLTAN_ID_TYPE) 
	     << ") does not match the run-time ZOLTAN_ID_TYPE size (" << lib_global_id_type_size 
	     << "). There is an error in the build/link procedure for this application.\n";
      std::cerr << errmsg.str();
      exit(EXIT_FAILURE);
    }
```
The `ZOLTAN_ID_TYPE` is a global typedef in affect at the time of compilation based on settings in the `zoltan_types.h` include file while the value returned from `Zoltan_get_global_id_type` is the size of the `ZOLTAN_ID_TYPE` which was active at the time the library was compiled. 

Hopefully these two values match, but if they don't, then I want to detect it at runtime and output a somewhat helpful error instead of trying to debug some weird downstream corruption.  I am currently "manually" prototyping the function and declaring it external in my code, but it would be better for it to be officially in the zoltan API.

Thanks.

@trilinos/zoltan

**Comment by kddevin** [comment]
Sorry @gsjaardema ; I am just seeing this issue now.
https://github.com/trilinos/Trilinos/wiki/GitHub-Notifications

Are you still interested in this change?  If so, I think it would be easy to move the function for you.  Just let me know.  Thanks.

**Comment by gsjaardema** [comment]
Yes. Still interested.

Thanks.
.. greg

**Comment by kddevin** [comment]
Done.  @gsjaardema , please reopen this issue if you have any problems.
