### ISSUE TITLE
MueLu::ParameterListInterpreter::ParameterListInterpreter seems to take a lot more time than expected

### ISSUE THREAD

**Issue by pwxy** [trilinos/Trilinos#1646]
MueLu::CreateXpetraPreconditioner calls both MueLu::HierarchyManager::SetupHierarchy and MueLu::ParameterListInterpreter::ParameterListInterpreter

I'm running Chebyshev smoother, and I thought that the smoothers were being constructed by MueLu::HierarchyManager::SetupHierarchy rather than MueLu::ParameterListInterpreter::ParameterListInterpreter.  However, I saw that several levels down the stack trace, MueLu::ParameterListInterpreter::ParameterListInterpreter calls  MueLu::ParameterListInterpreter::UpdateFactoryManager_Smoothers, which for presmoothing, calls:

        preSmoother = rcp(new SmootherFactory(rcp(new TrilinosSmoother(preSmootherType, preSmootherParams, overlap))));

So it appears that MueLu::ParameterListInterpreter::ParameterListInterpreter is constructing the smoothers?

I've noticed that time spent in MueLu::ParameterListInterpreter::ParameterListInterpreter is rather large, and most of this time is due to the construction of the presmoother (I have both pre- and post- smoothing).

**Comment by aprokop** [comment]
@pwxy News to me too. Was added relatively recently (in April). Does not sound right.

**Comment by aprokop** [comment]
@trilinos/muelu

**Comment by tawiesn** [comment]
@pwxy Could you check whether there is a similar problem using the extended input deck rather than the simplified one?

**Comment by tawiesn** [comment]
@csiefer2

**Comment by pwxy** [comment]
@tawiesn I cannot remember what the extended input deck looks like.  The following is my current input deck (which I'm sure is the simplified one).  How do I change this to the extended input deck?

              <ParameterList name="MueLu-Tpetra">

                <Parameter name="verbosity"                               type="string"   value="high"/>
              
                <Parameter name="number of equations"                     type="int"      value="1"/>
              
                <Parameter name="max levels"                	            type="int"      value="10"/>

                <Parameter name="multigrid algorithm"                     type="string"   value="sa"/>
                <Parameter name="sa: use filtered matrix"                 type="bool"     value="true"/>
              
                <Parameter name="coarse: max size"                        type="int"      value="1000"/>
              
                <Parameter name="transpose: use implicit"                 type="bool"     value="false"/>

                
                <Parameter name="aggregation: type"                       type="string"   value="uncoupled"/>
                <Parameter name="aggregation: drop scheme"                type="string"   value="classical"/>
                <Parameter name="aggregation: drop tol"                   type="double"   value="0.0"/>
              
                
                <Parameter name="smoother: pre or post"                   type="string"   value="both"/>

                <Parameter name="smoother: type"                          type="string"   value="CHEBYSHEV"/>
                <ParameterList name="smoother: params">
                  <Parameter name="chebyshev: degree"                    type="int"      value="2"/>>
                  
                  <Parameter name="chebyshev: ratio eigenvalue"          type="double"   value="20"/>
                  <Parameter name="chebyshev: min eigenvalue"            type="double"   value="1.0"/>
                  <Parameter name="chebyshev: zero starting solution"    type="bool"     value="true"/>
                  <Parameter name="chebyshev: eigenvalue max iterations" type="int"      value="15"/>
                </ParameterList>

                
                <Parameter name="repartition: enable"                     type="bool"     value="true"/>
                <Parameter name="repartition: partitioner"                type="string"   value="zoltan2"/>
                 <ParameterList name="repartition: params">
                    <Parameter name="algorithm" type="string" value="multijagged"/>
                 </ParameterList> 
                <Parameter name="repartition: start level"                type="int"      value="2"/>
                <Parameter name="repartition: min rows per proc"          type="int"      value="1024"/>
                <Parameter name="repartition: max imbalance"              type="double"   value="1.327"/>
                <Parameter name="repartition: remap parts"                type="bool"     value="true"/>
                <Parameter name="repartition: rebalance P and R"          type="bool"     value="true"/>
              
              </ParameterList>

**Comment by tawiesn** [comment]
@pwxy I've checked the code paths and it is the same for the extended style input deck. Nevertheless, as @aprokop already has pointed out, the problematic code just creates an MueLu::Ifpack2Smoother object and sets the parameter lists.

**Comment by pwxy** [comment]
I've added the following two teuchos timers (there are two constructors) so we can keep an eye on it:
MueLu: ParameterListInterpreter: ParameterListInterpreter1
MueLu: ParameterListInterpreter: ParameterListInterpreter2

**Comment by aprokop** [comment]
@pwxy Can you please rename the timers to something more clear? Maybe `MueLu: ParameterListInterpreter: ParameterListInterpreter (ParameterList)" and `MueLu: ParameterListInterpreter: ParameterListInterpreter (XML)`, or something similar?

**Comment by pwxy** [comment]
@aprokop thanks for the advice; I have followed your suggestion.  Depending on the test case, the ParameterListInterpreter constructor times can be significant.  Especially for problems that are not large, this time can be larger than the time to construct the MueLu hierarchy.

**Comment by aprokop** [comment]
@pwxy  Thanks! Do you have a specific reproducer?

**Comment by jhux2** [comment]
> Depending on the test case, the ParameterListInterpreter constructor times can be significant. Especially for problems that are not large, this time can be larger than the time to construct the MueLu hierarchy.

I assume it's the XML constructor that's slow?

**Comment by pwxy** [comment]
@aprokop you expect too much.

I can reproduce the problem with drekar on a single Haswell compute node (32 cores).
I have been trying to reproduce the problem with the MueLu driver, but not succeeding.


I'm running the drekar 3D Poisson problem (27-pt stencil) with 128^3 elements with 32 MPI processes (MPI-only) on a single Haswell node (Intel 17 compiler).
I tried to run as similar problem as possible with MueLu_Driver.exe

Two things to note below:
1. for drekar run, "MueLu: ParameterListInterpreter (ParameterList)" time is larger than "MueLu: Hierarchy: Setup (total)"
2. although drekar time for "MueLu: Hierarchy: Setup (total)" is 35% higher than for MueLu_Driver.exe, the drekar time for "MueLu: ParameterListInterpreter (ParameterList)" is a factor of 31x times MueLu_Driver.exe



The following is the output for drekar:

---                            Multigrid Summary                             ---
--------------------------------------------------------------------------------
Number of levels    = 4
Operator complexity = 1.04
Smoother complexity = 1.08
Cycle type          = V


And then timings:

p= 0 |                                                   TimeMonitor results over 32 processors
p= 0 | Timer Name                                        MinOverProcs           MeanOverProcs           MaxOverProcs
p= 0 | MueLu: Hierarchy: Setup (total)                   0.6432 (3)             0.6447 (3.094)          0.6601 (4)  
p= 0 | MueLu: ParameterListInterpreter (ParameterList)   0.8056 (1)             0.8056 (1)              0.8056 (1)  



I tried to run as similar problem as possible with MueLu_Driver.exe

MueLu_Driver.exe --matrixType="Brick3D" --nx=129 --ny=129 --nz=129 --mx=4 --my=4 --mz=2 --xml=scaling.xml

---                            Multigrid Summary                             ---
--------------------------------------------------------------------------------
Number of levels    = 4
Operator complexity = 1.05
Smoother complexity = 1.08
Cycle type          = V

level     rows       nnz  nnz/row  c ratio  procs
  0    2146689  57066625    26.58               32
  1      85184   2441472    28.66    25.20      32
  2       4096    135200    33.01    20.80       4
  3        180      5200    28.89    22.76       1


                                                   TimeMonitor results over 32 processors
Timer Name                                         MinOverProcs    MeanOverProcs     MaxOverProcs

MueLu: Hierarchy: Setup (total)                    0.4674 (3)      0.4690 (3.125)    0.4812 (4)  
MueLu: ParameterListInterpreter (ParameterList)    0.0261 (1)      0.0261 (1)        0.0261 (1)  





drekar MueLu parameters:

              <ParameterList name="MueLu-Tpetra">

                <Parameter name="verbosity"                               type="string"   value="high"/>
              
                <Parameter name="number of equations"                     type="int"      value="1"/>
              
                <Parameter name="max levels"                	            type="int"      value="10"/>

                <Parameter name="multigrid algorithm"                     type="string"   value="sa"/>
                <Parameter name="sa: use filtered matrix"                 type="bool"     value="true"/>
              
                <Parameter name="coarse: max size"                        type="int"      value="1000"/>
              
                <Parameter name="transpose: use implicit"                 type="bool"     value="false"/>

                
                <Parameter name="aggregation: type"                       type="string"   value="uncoupled"/>
                <Parameter name="aggregation: drop scheme"                type="string"   value="classical"/>
                <Parameter name="aggregation: drop tol"                   type="double"   value="0.0"/>
              
                
                <Parameter name="smoother: pre or post"                   type="string"   value="both"/>

                <Parameter name="smoother: type"                          type="string"   value="CHEBYSHEV"/>
                <ParameterList name="smoother: params">
                  <Parameter name="chebyshev: degree"                    type="int"      value="2"/>>
                  
                  <Parameter name="chebyshev: ratio eigenvalue"          type="double"   value="20"/>
                  <Parameter name="chebyshev: min eigenvalue"            type="double"   value="1.0"/>
                  <Parameter name="chebyshev: zero starting solution"    type="bool"     value="true"/>
                  <Parameter name="chebyshev: eigenvalue max iterations" type="int"      value="15"/>
                </ParameterList>

                
                <Parameter name="repartition: enable"                     type="bool"     value="true"/>
                <Parameter name="repartition: partitioner"                type="string"   value="zoltan2"/>
                 <ParameterList name="repartition: params">
                    
                    <Parameter name="algorithm" type="string" value="multijagged"/>
                    
                    
                    <Parameter name="mj_premigration_option" type="int" value="1"/>
                    <Parameter name="mj_premigration_coordinate_count" type="int" value="1000"/>
                    <Parameter name="timer_type" type="string" value="no_timers"/>
                 </ParameterList> 
                <Parameter name="repartition: start level"                type="int"      value="2"/>
                <Parameter name="repartition: min rows per proc"          type="int"      value="1024"/>
                <Parameter name="repartition: max imbalance"              type="double"   value="1.327"/>
                <Parameter name="repartition: remap parts"                type="bool"     value="true"/>
                <Parameter name="repartition: rebalance P and R"          type="bool"     value="true"/>
              
              </ParameterList> 





scaling.xml for MueLu_Driver.exe

<ParameterList name="MueLu">

  

  
    <Parameter        name="verbosity"                            type="string"   value="high"/>

    <Parameter        name="coarse: max size"                     type="int"      value="1000"/>

    <Parameter        name="multigrid algorithm"                  type="string"   value="sa"/>

    
    <Parameter        name="transpose: use implicit"              type="bool"     value="false"/>

    
    <Parameter        name="max levels"                	        type="int"      value="10"/>
    <Parameter        name="number of equations"                  type="int"      value="1"/>
    <Parameter        name="sa: use filtered matrix"              type="bool"     value="true"/>
    

  
    <Parameter        name="aggregation: type"                    type="string"   value="uncoupled"/>
    <Parameter        name="aggregation: drop scheme"             type="string"   value="classical"/>
    <Parameter        name="aggregation: drop tol"                type="double"   value="0.0"/>
    
    

  
    <Parameter name="smoother: pre or post"                   type="string"   value="both"/>

    <Parameter        name="smoother: type"                       type="string"   value="CHEBYSHEV"/>
    <ParameterList    name="smoother: params">
      <Parameter      name="chebyshev: degree"                    type="int"      value="2"/>>
      <Parameter      name="chebyshev: ratio eigenvalue"          type="double"   value="20"/>
      <Parameter      name="chebyshev: min eigenvalue"            type="double"   value="1.0"/>
      <Parameter      name="chebyshev: zero starting solution"    type="bool"     value="true"/>
      <Parameter name="chebyshev: eigenvalue max iterations" type="int"      value="15"/>
    </ParameterList>

  
    <Parameter        name="repartition: enable"                  type="bool"     value="true"/>
    <Parameter        name="repartition: partitioner"             type="string"   value="zoltan2"/>
    <Parameter        name="repartition: start level"             type="int"      value="2"/>
    <Parameter        name="repartition: min rows per proc"       type="int"      value="1024"/>
    <Parameter        name="repartition: max imbalance"           type="double"   value="1.327"/>
    <Parameter        name="repartition: remap parts"             type="bool"     value="true"/>
    <Parameter name="repartition: rebalance P and R"          type="bool"     value="true"/>
    <ParameterList name="repartition: params">
       <Parameter name="algorithm" type="string" value="multijagged"/>
       <Parameter name="mj_premigration_option" type="int" value="1"/>
       <Parameter name="mj_premigration_coordinate_count" type="int" value="1000"/>
       <Parameter name="timer_type" type="string" value="no_timers"/>
    </ParameterList> 

</ParameterList>
