### ISSUE TITLE
MueLu: Kokkos_Refactor option should check for upstream dependencies

### ISSUE THREAD

**Issue by jhux2** [trilinos/Trilinos#1652]
@trilinos/muelu 

The MueLu cmake option `MueLu_ENABLE_Kokkos_Refactor` should include logic that checks that certain upstream dependencies and other cmake options are enabled.

- [ ] `-D MueLu_ENABLE_Experimental:BOOL=ON`
- [ ] `-D MueLu_ENABLE_Kokkos_Refactor:BOOL=ON`
- [ ] `-D Xpetra_ENABLE_Experimental:BOOL=ON`
- [ ] `-D Xpetra_ENABLE_Kokkos_Refactor:BOOL=ON`

**Comment by lucbv** [comment]
@jhux2 should we also think of testing with ```-D KokkosKernels_ENABLE_Experimental:BOOL=ON``` as shown in #1660 ?
I can look into setting up a nightly on my machine with this option turned on to hedge against changes that appear in kokkos/kokkos-kernels experimental and that will likely eventually impact our kokkos refactor.

**Comment by lucbv** [comment]
By the way @csiefer2 asked on Monday what was the status of kokkos-kernels_Experimental:
1. Graph algorithm are still in the experimental namespace especially coloring
2. spgemm is still experimental, maybe because it relies on some of the above graph algorithms

**Comment by mhoemmen** [comment]
Would it make sense to ask kokkos-kernels to use subpackages, and mark some of them as experimental?  This "one experimental flag" thing looks like it could easily lead to confusion and breakage (it already has ;-) ).  Subpackages could be marked EX until they are ready, and they could have useful names like KokkosKernelsSpgemm etc.

**Comment by jhux2** [comment]
> Would it make sense to ask kokkos-kernels to use subpackages, and mark some of them as experimental? This "one experimental flag" thing looks like it could easily lead to confusion and breakage (it already has ;-) ). Subpackages could be marked EX until they are ready, and they could have useful names like KokkosKernelsSpgemm etc.

@mhoemmen That's a good idea.

**Comment by jhux2** [comment]
> should we also think of testing with -D KokkosKernels_ENABLE_Experimental:BOOL=ON as shown in #1660 ?
> I can look into setting up a nightly on my machine with this option turned on to hedge against changes that appear in kokkos/kokkos-kernels experimental and that will likely eventually impact our kokkos refactor.

@lucbv I agree, that should be tested somewhere.
