### ISSUE TITLE
find_package option COMPONENTS ineffective because of hard-coded includes in TrilinosConfig.cmake

### ISSUE THREAD

**Issue by jwuttke** [trilinos/Trilinos#1655]
CMake's find_package takes an option COMPONENTS. Usage with Trilinos seems to be documented nowhere, but TrilinosConfig.cmake clearly is intended to support commands like

    find_package(Trilinos REQUIRED COMPONENTS Epetra Belos Ifpack)

However, at the bottom of TrilinosConfig.cmake there is a long list that includes all Trilinos subproject CMake files. This overwrites the component selection, and makes it ineffective: the client application will depend on _all_ of Trilinos, not just on the selected components.

**Comment by ibaned** [comment]
@trilinos/framework
