### ISSUE TITLE
Automatically document and manage the supported TPLs for each Trilinos package

### ISSUE THREAD

**Issue by tawiesn** [trilinos/Trilinos#166]
A central place where all supported TPLs (including version) are listed for each of the Trilinos package would be nice. Ideally, Tribits would allow to manage version requirements of TPLs (and avoid version conflicts).
See also discussion in #160

**Comment by crtrott** [comment]
Yeah we had that discussion, recently in a leaders meeting and I had a feeling that there was some reluctance to go there. I personally am all in favor of it (at least in the sense of: "these versions are certified, others might work but no guarantees").

**Comment by tawiesn** [comment]
I guess it is also necessary for the "ACM TOMS Replicated Computational Results Initiative"...

**Comment by crtrott** [comment]
I don't think so. For that you only need to specify what you actually used in the results you report. At least that would be my guess.

**Comment by tawiesn** [comment]
In my understanding, this includes all information about your hardware and your software (OS, compilers,...), specifically the Trilinos version (ideally the SHA1 string) as well as all TPLs (including the version number) that you have used. If Tribits could report the exact version numbers of the TPLs that have been used (and therefore are working), this could be the first step to collect all these reports and generate a list of "certified" TPL versions.

**Comment by nschloe** [comment]
For reference, this is [an old Trilinos issue](https://software.sandia.gov/bugzilla/show_bug.cgi?id=5893), and also has a tracker [over on TriBits](https://github.com/TriBITSPub/TriBITS/issues/13). Needless to say, the absence of version checking has bitten me more than once.

**Comment by jwillenbring** [comment]
One issue with this is that not all TPLs are set up to report their version number. This would not have to be automatically generated for the TOMS RCR initiative, but certainly it would be helpful.
