### ISSUE TITLE
MueLu: Build error with experimental kokkos-kernels option on

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#1660]
@trilinos/muelu @trilinos/xpetra

@DrBooom reports:

With these three CMake options turned on:
```
  -D KokkosKernels_ENABLE_Experimental:BOOL=ON \
  -D MueLu_ENABLE_Kokkos_Refactor=ON \
  -D Xpetra_ENABLE_Kokkos_Refactor=ON \
```
I get this error:
```
In file included from /p/home/cbluchi/Trilinos/packages/tpetra/core/ext/TpetraExt_MatrixMatrix.cpp(49):
/p/home/cbluchi/Trilinos/packages/tpetra/core/ext/TpetraExt_MatrixMatrix_def.hpp(62): catastrophic error: cannot open source file "KokkosKernels_SPGEMM.hpp"
  #include "KokkosKernels_SPGEMM.hpp"
                                     ^
```
I don't get this build error with the options disabled.

**Comment by crtrott** [comment]
That is a tpetra issue not a Xpetra or MueLu issue, the include in the tpetra file needs to be fixed.

**Comment by jhux2** [comment]
Maybe related to this?  https://github.com/kokkos/kokkos-kernels/issues/53

**Comment by crtrott** [comment]
Yeah the file was renamed to KokkosSparse_spgemm.hpp i believe , and apparently we didn't catch this include.

**Comment by crtrott** [comment]
Also maybe this should now be enabled by default ...

**Comment by mhoemmen** [comment]
it's a kokkos-kernels issue, since kokkos-kernels broke backwards compatibility.  would have been nice if Trilinos had a nightly test for this though :)

**Comment by crtrott** [comment]
Yeah but now it is a Tpetra issue, because it is what needs to change ;-), and yeah technically there are tests but apparently -D KokkosKernels_ENABLE_Experimental:BOOL=ON is not set by any of them.

**Comment by mndevec** [comment]
Sorry, I was not aware the call was wrapped with experimental flags. My commit should fix this now, and I removed experimental flags. 
It will compile as default now.

**Comment by mhoemmen** [comment]
Thanks @mndevec and @crtrott !

@mndevec wrote:
> It will compile as default now.

Does that mean that Trilinos uses your sparse matrix-matrix multiply by default now?  Just checking :-) .

**Comment by mndevec** [comment]
Yes, only when the execution space is openmp.

**Comment by aprokop** [comment]
Can confirm @mndevec that that's what we getting in MueLu.

**Comment by mhoemmen** [comment]
@mndevec Thanks for clarifying!
