### ISSUE TITLE
MueLu: unit tests ETI needs to guard kokkos code for Epetra only

### ISSUE THREAD

**Issue by lucbv** [trilinos/Trilinos#1663]
f46f6db is adding kokkos::initialize and kokkos::finalize to the unit test ETI macro, but this seems wrong in the case of [Epetra only instantiation.](https://testing.sandia.gov/cdash/index.php?subproject=MueLu&project=Trilinos) I think that these should be guarded as something like:
```
#ifdef HAVE_MUELU_TPETRA
kokkos::initialize()
#endif

...

#ifdef HAVE_MUELU_TPETRA
kokkos::finalize()
#endif
```
or are there some cases where `Tpetra` might be on but we still do not want `kokkos`?
I will add these guard and build with Epetra only to check that it fixes things...

**Comment by aprokop** [comment]
@lucbv I think you are right. If you look at `MueLu_UnitTests.cpp` in the same dir, it hides `Kokkos::initialize()` behind `#ifdef HAVE_MUELU_KOKKOSCORE`. I think this should be sufficient for ETI too. I think it's better than `HAVE_MUELU_TPETRA`.

**Comment by lucbv** [comment]
OK, I added the `#ifdef HAVE_MUELU_KOKKOSCORE` guard and the `-DTrilinos_ENABLE_Kokkos=OFF`, `-DTrilinos_ENABLE_Tpetra=OFF` builds and runs the tests fine.
I am running the checkin-script now.

**Comment by aprokop** [comment]
Thanks @lucbv . Sorry for trouble. Apparently, our checkin script does not catch that.

**Comment by lucbv** [comment]
The Epetra only build is clean this morning so we should be good
