### ISSUE TITLE
MueLu: move Xpetra-specific Belos adapter files to Belos

### ISSUE THREAD

**Issue by tawiesn** [trilinos/Trilinos#1668]
We should move the following files 

> BelosOperatorT.hpp
> BelosXpetraAdapter.hpp
> BelosXpetraAdapterMultiVector.hpp
> BelosXpetraAdapterOperator.hpp

in `muelu/adapters/belos` to a new `xpetra` folder in Belos.

This would allow to use preconditioners derived from `Xpetra::Operator<>` directly with Belos.

**Comment by aprokop** [comment]
@trilinos/xpetra 

Maybe it even makes sense to move `BelosOperatorT.hpp` to Belos itself.

**Comment by tawiesn** [comment]
@trilinos/belos

**Comment by mhoemmen** [comment]
Not a bad idea.  This would have the side effect of making Stratimikos depend optionally on Xpetra; is that OK?

**Comment by srajama1** [comment]
I support this as well. Currently ShyLU will depend on MueLU just to use the Belos Xpetra adapters. We would rather not have it.

**Comment by lucbv** [comment]
@mhoemmen I am cleaning up a little issues with the MueLu label on them.
It looks to me that this one has been taken care of as part of the work done in PR #2483.
This also means based on @srajama1 comment that ShyLU no longer needs a MueLu dependency, a quick grep shows that the only place where ShyLU uses MueLu is in Frosch. Should we start an issue to fix that?

**Comment by mhoemmen** [comment]
@lucbv Better yet, if we're going to do stuff w/ Belos and Xpetra, why don't we remove the Xpetra specializations of MultiVecTraits and OperatorTraits, and instead make wrapper subclasses of Belos::MultiVec and Belos::Operator that wrap Xpetra objects?  That would avoid instantiating Belos yet again for all possible Xpetra template parameter combinations.

**Comment by lucbv** [comment]
@mhoemmen as the adapter have actually been moved to Belos, I feel that it is appropriate to close this issue.
If more work needs to be done in Belos to improve templating and compile time, then we should open a new issue in Belos to keep track of this.

**Comment by mhoemmen** [comment]
@lucbv New issue: https://github.com/trilinos/Trilinos/issues/3415
