### ISSUE TITLE
Xpetra: add more features to the refactor branch

### ISSUE THREAD

**Issue by aprokop** [trilinos/Trilinos#1669]
@trilinos/xpetra 

Need:
- [x] `Map::getLocalMap` (added in 77fb5574fc24fbe9eebbe1c54e49289e70877a39)
- [ ] `CrsMatrix`  `(local_matrix, map, map, map, map)` constructor

**Comment by mhoemmen** [comment]
@aprokop Woah, are you planning to wrap Tpetra's LocalMap?

**Comment by aprokop** [comment]
@mhoemmen Maybe. So far, I only need it for checking whether row and column are compatible, i.e. whether `colGIDs = [rowGIDs, ghosts]`. I do that in a Kokkos `parallel_for` region (see [here](https://github.com/trilinos/Trilinos/blob/fb606915ba83fcb30968e0a6d4847fe9c13eb139/packages/muelu/src/Transfers/Smoothed-Aggregation/MueLu_TentativePFactory_kokkos_def.hpp#L935)).

**Comment by mhoemmen** [comment]
@aprokop I wish Kokkos had specialized `bool` reductions that could terminate early if they find what they seek....

**Comment by tawiesn** [comment]
@aprokop What is the refactor branch?

**Comment by aprokop** [comment]
@tawiesn That's what I call the code behind `HAVE_MUELU_KOKKOS_REFACTOR`. Not a branch per say.

**Comment by tawiesn** [comment]
@aprokop Got it.

**Comment by aprokop** [comment]
@mhoemmen Should the `isSameMap` check be added to Tpetra? It seems that Tpetra is the right place for it. It may also be faster for applications, as Tpetra may not need to do the same looping. For instance, for matrices constructed with just a row map, it is automatically guaranteed to be true. For others, there may already be some checking during `fillComplete` (not sure if that's 100% true, though). In general, this check is nice in the sense that having it true means same local indices for rows and columns will have the same global indices. This may also benefit Ifpack2 smoothers which rely on figuring out the diagonal.

**Comment by mhoemmen** [comment]
@aprokop I think it may make sense for a CrsGraph to remember that its column Map was constructed rather than given.  The whole way Epetra or Tpetra does Import for mat-vecs is a little bit funny to me, though.  I see the "column Map" as an artificial construct that forces every mat-vec communication through the most general use case of Import.

It might be better for CrsGraph and CrsMatrix to distinguish explicitly between the most common use case, and more general use cases.  The most common case has no permutes and remotes only at the end on each process (common case); this does not require copying the source vector.  More general cases require permuting and therefore copying the source vector.  This decision can be local to each process.

"Distinguish explicitly" (first sentence of previous paragraph) means that for the common case, it would make sense to tie the column Map to the domain Map somehow.  For example, Import could have a special case for boundary exchange, in which it stores the column Map implicitly.  Users could always construct an explicit column Map if they want, but the implicit representation could convert between global and local indices.

**Comment by aprokop** [comment]
> It might be better for CrsGraph and CrsMatrix to distinguish explicitly between the most common use case, and more general use cases.

No chance of that happening in the near-term future, is there?

**Comment by mhoemmen** [comment]
@aprokop wrote:
> No chance of that happening in the near-term future, is there?

I do have some plans to add Import interfaces for supporting common boundary exchange use cases, where users already know who owns what (this would skip the expensive `Map::getRemoteIndexList` call in Import's constructor).  It would also make sense to merge `CrsGraph::makeColMap` and `CrsGraph::makeImportExport` into a single function.  The latter would be the natural place to add this feature.

In the meantime, would it make sense for the Import to remember that CrsGraph constructed it along with the column Map?  We could do this by adding an Import constructor with a `bool` input argument.  This would have the additional advantage of speeding up the local part of Import's constructor (e.g., no permutes so no need to set them up).

**Comment by aprokop** [comment]
> In the meantime, would it make sense for the Import to remember that CrsGraph constructed it along with the column Map?

Maybe? I think Import is less important in this context compared to column map. For us, it's the fact of whether we need to go to GIDs is crucial, which only relies on row and column maps, and not on Import which depends on domain map.

**Comment by mhoemmen** [comment]
@aprokop wrote:
> . . . it's the fact of whether we need to go to GIDs is crucial, which only relies on row and column maps . . . .

That's a good point.  The Import feature would be more useful for #385.  The thing you're talking about is really a property of the CrsGraph, not a property of the Import.  It could be computed lazily, and it is local to each MPI process.

**Comment by aprokop** [comment]
> The thing you're talking about is really a property of the CrsGraph, not a property of the Import. It could be computed lazily, and it is local to each MPI process.

Yes. My thinking is that you add a tri-state (UNKNOWN, FALSE, TRUE) mutable variable to the CrsGraph, lets call it `matchingMaps_`. If you construct a CrsMatrix with just a row, it's automatically set to TRUE. If you provide a column map, it's set to UNKNOWN. We add a public function to `CrsGraph`
```c++
bool matchingMap() const {
  if (matchingMaps_ == UNKNOWN) {
     // Execute matching kernel
     // Set matchingMaps_ to TRUE or FALSE)
  }   
  return matchnigMaps_;
} 
```
I think that while in our case we only check matching for the case numRows <= numCols, it still makes sense even for numRows > numCols.

**Comment by mhoemmen** [comment]
@aprokop I just spent a good hour last week explaining the "statefulness" of `Tpetra::Crs*` to a room that wants to strip it away....  On the other hand, this feature looks useful.  

Could it make sense for this function to belong to the preconditioner, instead of to the CrsGraph?  That would lose the advantage of knowing that it's `TRUE` a priori, though.

**Comment by aprokop** [comment]
> That would lose the advantage of knowing that it's TRUE a priori, though.

Exactly the problem. Preconditioner has no idea, which will mean that in MueLu we will have to **always** do the computations to figure things out. While it's not as expensive as uncoditionally using GID2LID conversions, it does cost, and should not be necessary.

**Comment by mhoemmen** [comment]
@aprokop wrote:
> Maybe I should have been in that room.

Let's talk offline about that.  Send me some e-mail so I don't forget.

I think it makes sense to make this a property of CrsGraph.  It's a local property too.  Is this something for which you might like to submit a pull request?  I would certainly welcome it :-) .

**Comment by aprokop** [comment]
@mhoemmen Will do.

**Comment by aprokop** [comment]
OK, the priority on adding `getLocalMap` increased as I found another place (in Tentative P) where would need it for `getGlobalElement`. I also need to introduce `isGlobalElement` to Tpetra's `LocalMap`.

**Comment by mhoemmen** [comment]
@aprokop wrote:
> I also need to introduce isGlobalElement to Tpetra's LocalMap.

I'm not a fan of `isGlobalElement` (or `isLocalElement`) since it is redundant with `getGlobalElement` and throws away useful information, namely the returned global index if it is valid.

**Comment by aprokop** [comment]
> I'm not a fan of isGlobalElement (or isLocalElement) since it is redundant with getGlobalElement and throws away useful information, namely the returned global index if it is valid.

@mhoemmen I agree with you, but then it becoms quite painful:
```c++
auto localMap = map->getLocalMap();
bool isGlobal = (getLobalElement(GID) !=
  Tpetra::Details::OrdinalTraits<typename decltype(localMap)::local_ordinal_type>::invalid();
```

**Comment by mhoemmen** [comment]
@aprokop ha, good point ;-) .  Users just need to realize that `is*Element` costs the same as `get*Element`.
