### ISSUE TITLE
Add Wiki page about GitHub notifications

### ISSUE THREAD

**Issue by maherou** [trilinos/Trilinos#1674]
GitHub notifications are essential for communication, especially for large projects.  However, setting up your notifications and dealing with troubleshooting can be challenging.  The wiki page:

https://github.com/trilinos/Trilinos/wiki/GitHub-Notifications

 attempts to address the challenges.

**Comment by maherou** [comment]
@jgfouca, @jmgate, @jwillenbring, @kddevin: I have added the wiki page https://github.com/trilinos/Trilinos/wiki/GitHub-Notifications to describe how to deal with GitHub issues.

Please take a moment to review it and edit or comment on it.

**Comment by jmgate** [comment]
Looks good to me&mdash;thanks @maherou.

**Comment by jhux2** [comment]
@maherou  Are alternatives to email notification in scope for posting to the wiki?

**Comment by bartlettroscoe** [comment]
@maherou, I made a small edit to point out the link https://github.com/notifications/participating.  That is a better set of notification, at lest for my experience.

**Comment by maherou** [comment]
@jhux2: Yes, please edit the wiki page with your  information.  If the title needs to be modified, please do so.
