### ISSUE TITLE
Get Trilinos working on ECP ATS-2 systems once a workable system is deployed

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#1675]
**Next Action Status:**

Waiting for a working ATS-2 system prototype to be provided at Sandia (current estimate is fall 2017) ...

**Related:** #1208, #1191, #1216

**CC:** @mhoemmen, @trilinos/framework, @nmhamster 

**Description:**

This story is to drive the work to get Trilinos to work on ECP ATS-2 systems once a working ATS-2 system prototype once a system is make available.

This is a follow on story to closed stories #1191, #1208, #1216 etc. that tried to get Trilinos working on an earlier prototype on 'ride' that ended up failing due to problems with the compiler suite creating working mixed-language programs between C++, C, and Fortran code (actually even just between C++ and C code).

**Comment by bartlettroscoe** [comment]
We will check with the advanced technology test bed team in fall 2017 periodically to see a prototype system will be ready for us to start using.

**Comment by crtrott** [comment]
Just as a side note: the ATS-2 system will probably use pretty much the same software stack as the current ride and white systems. So on the day that thing is delivered you probably will encounter the same issues on both machines. In that sense the more important thing here is to wait for another software stack update on ride/white and try to fix it there.

**Comment by bartlettroscoe** [comment]
FYI: #2454

**Comment by bartlettroscoe** [comment]
Trilinos has been worked and tested on ATS-2 and posting builds to CDash for more than a year.  (The XL builds are currently broken but that is another issue).  Closing as complete (a long time ago).
