### ISSUE TITLE
MueLu: failing Schur complement test

### ISSUE THREAD

**Issue by jhux2** [trilinos/Trilinos#1677]
@trilinos/muelu 

Since commit 66d4b5b44e13980798f0614ef4d6979c3982525f that fixed #1660, the MueLu test `SchurConstructor2x2` has started to fail.  I've verified this by reverting the change to the file TpetraExt_MatrixMatrix_def.hpp.  Dashboard results can be found [here](https://testing.sandia.gov/cdash/index.php?project=Trilinos&subproject=MueLu&filtercount=1&showfilters=1&field1=site&compare1=63&value1=geminga&date=2017-09-01##Nightly).

**Comment by jhux2** [comment]
@mndevec @tawiesn

**Comment by tjfulle** [comment]
Thanks @jhux2!  My git bisect foo is very low and I've been bisecting for this commit all morning :)

**Comment by aprokop** [comment]
As a side note: could we please start using `checkin` script for kokkos-kernels pushes? Pretty please 🙏

**Comment by mndevec** [comment]
Oh sorry about this, I was testing within tpetra only. I will bring back the experimental flag.

**Comment by mndevec** [comment]
I reverted back the experimental flag. I am not sure what is causing the Schur complement test fail yet.

**Comment by aprokop** [comment]
Thanks @mndevec!

**Comment by mhoemmen** [comment]
@mndevec (just in case your notifications require by-name mention)

**Comment by mndevec** [comment]
I did not track down the issue. The tests in tpetra and kokkoskernels passes. 
It might be somewhere along the integration.

**Comment by mhoemmen** [comment]
If you change sparse matrix-matrix multiply in Tpetra, you need to test downstream through MueLu.

**Comment by mndevec** [comment]
I am not sure if this is ever tested before. @csiefer2 set up a nightly test previously on his machine with kokkoskernels experimental flag. 

@csiefer2 , do you have any intuition about this test failure? When Kokkoskernels experimental is enabled, the tests in tpetra passes, but the above muelu test fails.

**Comment by lucbv** [comment]
@mndevec I think that the test in question currently has a few lines of code commented out because of this failure. If you remove the comments the test will fail on our nightly builds that do not have kokkoskernels experimental flag on.
So this problem is already inside the standard stack, not in the experimental one... @jhux can you confirm that we are talking about the last check in `muelu/test/unit-tests/SchurComplementFactory.cpp:216`?

**Comment by csiefer2** [comment]
This nightly has not been properly configured for quite some time.  Will reconfigure to do what you're asking about.
