### ISSUE TITLE
Teuchos: how to debug with TEUCHOS_STANDARD_CATCH_MACROS

### ISSUE THREAD

**Issue by aprokop** [trilinos/Trilinos#1679]
@teuchos @bartlettroscoe 

Typically, writing a test involves wrapping the code in the macro like this:
```c++
bool success = true;
bool verbose = true;
try {
  // your code
}
TEUCHOS_STANDARD_CATCH_STATEMENTS(verbose, std::cerr, success);
return ( success ? EXIT_SUCCESS : EXIT_FAILURE );
```
This works fine. However, when you have a bug in the code which throws an exception, you cannot use a debugger in the standard mode to get the backtrace as the exception is going to be caught by Teuchos.

The only workaround I'm aware is to try doing something with `catch throw` in gdb. However, this seems quite hard.

I wonder if it's possible for Teuchos to address this issue. One thing that comes to mind is that we could add an additional parameter to the macro or create a new macro with extra argument. If that parameter is true, we don't catch *any* exceptions. If it's false, we exhibit the standard behavior.

**Comment by mhoemmen** [comment]
@trilinos/teuchos The `TEUCHOS_TEST_FOR_EXCEPT*` deliberately include a function call inside, so that you can set a breakpoint on the function in your debugger.  Were you thinking about something like this?

**Comment by aprokop** [comment]
Maybe? Could you please elaborate on how this is applicable to this situation?

**Comment by bartlettroscoe** [comment]
@aprokop,

Please take a look at:

* https://trilinos.org/docs/dev/packages/teuchos/doc/html/group__TestForException__grp.html#gaadb9556c5c1ba7da1c141e7529a8ebdf

It shows the function `Teuchos::TestForException_break()` being called (and its Doxygen documentation describes it purpose).  You set a breakpoint on that and the debugger will pause just before it throws.  More advice and details can be found in section "5.11.7 Exception handling and debugging" in:

* https://trilinos.org/docs/dev/packages/teuchos/doc/html/TeuchosMemoryManagementSAND.pdf

Note the `throwNumber` argument if you need to catch the nth throw in case you don't want to break on the first throw.

Please let me know if that does not work for you.

**Comment by bartlettroscoe** [comment]
@aprokop, 

Also, if you have a working version of BinUtils installed on your machine that is compatible with your C++ compiler, you can enable BinUtils and get stack traces when thrown using TEUCHOS_TEST_FOR_EXCEPTION() and caught by  TEUCHOS_STANDARD_CATCH_STATEMENTS().  See "Stack Tracing" at:

* https://trilinos.org/docs/dev/packages/teuchos/doc/html/index.html
