### ISSUE TITLE
Intrepid2 complete edge/face basis sets

### ISSUE THREAD

**Issue by bathmatt** [trilinos/Trilinos#168]
@trilinos/intrepid2 

Currently Intrepid2 only supports the incomplete basis elements for edge and face.  At some point in the near future we will need the complete set (N2^e_n, N2^f_n) elements for solving EM problems.  This will give us true order for EM problem using PIC.  We will need them Tets, for Hex elements we use fully regular meshes so Nc^e/Nc^f are sufficient.

[femtable.pdf](https://github.com/trilinos/Trilinos/files/155525/femtable.pdf)

**Comment by mperego** [comment]
@bathmatt Is this feature still needed?

**Comment by mperego** [comment]
My understandind is that the complete edge and face FE  are not needed at this point. So I'm closing the issue. @bathmatt feel free to reopen.
