### ISSUE TITLE
MueLu: catch-all for KokkosRefactor branch tasks

### ISSUE THREAD

**Issue by aprokop** [trilinos/Trilinos#1681]
- [ ] Introduce a performance monitoring framework to monitor performance results
   Could be similar to interface test. Could use performance file structure.
- [ ] Implement new smoothed prolongator construction [#1743]
- [ ] Kokkosify AmalgamationInfo
  It should be the **only** place to do node <-> dof transformations
- [ ] Optimize block CoalesceDrop
- [ ] Get rid of `ArrayRCP` in UncoupledAggregation
- [ ] Replace LWGraph construction by a wrapper?
- [ ] Add a single value set function specialized on the device.
   This should allow us to skip initializing even rows in crs graph.
- [ ] Add `RandomAccessTraits` when applicable
- [ ] Check Chebyshev smoother setup difference between Serial and OMP_NUM_THREADS=1
- [ ] Use `KOKKOS_FORCEINLINE_FUNCTION`?
  I'm not sure when to use it instead of regular `KOKKOS_INLINE_FUNCTION`.
- [ ] Optimize block Tentative P
  Even after the rewrite, the Tentative P is dog slow compared to regular. Is it because of shared memory?
- [ ] Try optimizing `GetOverlappedDiagonal`
  Would Tpetra's `getLocalDiagOffsets` with the new `StaticCrsGraph::rowConst()` be faster? It would not need to create a subview...
- [x] Distance Laplacian functor
- [x] Parallelize loops in `Aggregates_kokkos::GetGraph()`
- [x] Use `Aggregates::GetGraph()` in CoordinatesTransferFactory
- [x] Bypass amalgamation for `blkSize=1` in CoordinatesTransferFactory
- [x] Get rid of `ArrayRCP` in Aggregates
- [x] Get rid of subview creation in `LWGraph_kokkos::getNeighborVertices`?
- [x] Use `ViewAllocateWithoutInitializing`?
   See kokkos/kokkos#1073
- [x] Add `FIXME_KOKKOS` comments to code to indicate things to look at.
- [x] Fix unit tests
   See #1686

**Comment by aprokop** [comment]
The latest.

Includes:
- Parallelize loops in Aggregates_kokkos::GetGraph()
- Use Aggregates::GetGraph() in CoordinatesTransferFactory
- Bypass amalgamation for blkSize=1 in CoordinatesTransferFactory

Result (non-Kokkos vs Kokkos):
- UncoupledAggregation slightly up due to explicit `Aggregates::ComputeAggregateSizes` call
- Tentative slightly down
- CoordinatesTransfer down

![old_vs_new](https://user-images.githubusercontent.com/7297887/30001590-71815f24-9060-11e7-8d8f-1c920482c4e4.png)

**Comment by aprokop** [comment]
The latest.

Includes:

- Get rid of subview creation in LWGraph_kokkos::getNeighborVertices
- Use ViewAllocateWithoutInitializing
- Misc optimizations in CoordinatesTransferF

Result (non-Kokkos vs Kokkos):

- UncoupledAggregation is now on parity with serial version
- CoordinatesTransfer is significantly down

non-Kokkos: 32.57s
Kokkos: 34.46
Slowdown: 1.79s (5.5%)

**Comment by aprokop** [comment]
Here is a quick comparison of timers:
```
timer name                                                        file 1     file 2      ratio
MueLu: RAPFactory: Computing Ac (level=1)                          9.191      9.837       1.07
MueLu: Ifpack2Smoother: Setup Smoother (level=0)                   5.900      7.733       1.31
MueLu: SaPFactory_kokkos: Prolongator smoothing (level=1)          5.458      5.906       1.08
MueLu: CoalesceDropFactory_kokkos: Build (level=0)                 3.196      3.534       1.11
MueLu: Ifpack2Smoother: Setup Smoother (level=1)                   1.827      1.795       0.98
MueLu: RAPFactory: Computing Ac (level=2)                          1.798      1.928       1.07
MueLu: FilteredAFactory: Matrix filtering (level=0)                1.699        nan        nan
MueLu: TentativePFactory_kokkos: Build (level=1)                   0.775      1.022       1.32
MueLu: SaPFactory_kokkos: Prolongator smoothing (level=2)          0.585      0.664       1.13
MueLu: UncoupledAggregationFactory_kokkos: Build (level=0)         0.425      0.446       1.05
MueLu: CoalesceDropFactory_kokkos: Build (level=1)                 0.374      0.920       2.46
MueLu: FilteredAFactory: Matrix filtering (level=1)                0.356        nan        nan
MueLu: UncoupledAggregationFactory_kokkos: Build (level=1)         0.251      0.222       0.88
MueLu: CoordinatesTransferFactory_kokkos: Build (level=1)          0.119      0.221       1.86
MueLu: Ifpack2Smoother: Setup Smoother (level=2)                   0.106      0.099       0.93
```
Here is the problem: Ifpack2's Chebyshev eigenvalue estimation vastly differs between a serial node and OpenMP with a single thread.
```
old.log:Ifpack2::Details::Chebyshev::computeInitialGuessForPowerMethod          0.0689 (1)
old.log:Ifpack2::Details::Chebyshev::powerMethodWithInitGuess                   5.2494 (1)
new.log:Ifpack2::Details::Chebyshev::computeInitialGuessForPowerMethod          0.0827 (1)
new.log:Ifpack2::Details::Chebyshev::powerMethodWithInitGuess                   6.3838 (1)
```
I have no explanation for this. @mhoemmen Any idea? This is with a single MPI rank and the following OpenMP environment variables:
```
OMP_PROC_BIND=spread
OMP_PLACES=threads
OMP_NUM_THREADS=1
```

**Comment by mhoemmen** [comment]
@aprokop It's not obvious to me why the initial guess computation should be so much slower.  This could be a Kokkos issue, since Tpetra just defers to Kokkos' pseudorandom number generator.

We've seen before that `Ifpack2::Chebyshev`'s power method is sensitive to the pseudorandom number generator, so it's possible that the OpenMP case is unlucky.  How do the iteration counts compare?

**Comment by aprokop** [comment]
> It's not obvious to me why the initial guess computation should be so much slower. This could be a Kokkos issue, since Tpetra just defers to Kokkos' pseudorandom number generator.

@mhoemmen I'm not so much worried about `computeInitialGuessForPowerMethod` but rather about `powerMethodWithInitGuess` which should just be matvects and residuals.

> We've seen before that Ifpack2::Chebyshev's power method is sensitive to the pseudorandom number generator, so it's possible that the OpenMP case is unlucky. How do the iteration counts compare?

This is not an iterative method, it does not have a convergence based on tolerance. Rather, it does a fixed number of iterations. The only early exit criteria if norm somehow becomes zero, but that is certainly not the case here. So I don't see how pseudorandom generator could affect things.

**Comment by mhoemmen** [comment]
@aprokop wrote:
> This is not an iterative method, it does not have a convergence based on tolerance. Rather, it does a fixed number of iterations. The only early exit criteria if norm somehow becomes zero, but that is certainly not the case here. So I don't see how pseudorandom generator could affect things.

Hm, that's weird.  I don't think the BLAS gets called at all; it's all kokkos-kernels stuff.

**Comment by aprokop** [comment]
The latest.

Includes:
- Distance Laplacian for scalar
- Get rid of `ArrayRCP` in Aggregates (for `isRoot_`)
- Reenabled block tentative prolongator and coalescedrop. Completely unoptimized.

No real changes in timings as this was mostly a new feature thing.

Spent some time tracking vanishing changes in timings. For some reason, timers misbehaved in the middle of day, getting RAPFactory for level 0 up to 13seconds. Running in the evening seemed to normalize things, and even run slightly faster.

Another issue: cannot push to upstream as KokkosRefactor unit tests fail (#1686).

non-Kokkos: 30.39s
Kokkos: 32.95
Slowdown: 2.56s (8.4%)

```
timer name                                                        file 1     file 2      ratio
MueLu: RAPFactory: Computing Ac (level=1)                          8.359      8.782       1.05
MueLu: Ifpack2Smoother: Setup Smoother (level=0)                   5.935      7.258       1.22 (!)
MueLu: SaPFactory_kokkos: Prolongator smoothing (level=1)          5.111      5.698       1.11
MueLu: CoalesceDropFactory_kokkos: Build (level=0)                 2.662      3.419       1.28 (!)
MueLu: Ifpack2Smoother: Setup Smoother (level=1)                   1.779      1.746       0.98
MueLu: RAPFactory: Computing Ac (level=2)                          1.776      1.892       1.07
MueLu: FilteredAFactory: Matrix filtering (level=0)                1.480        nan        nan
MueLu: TentativePFactory_kokkos: Build (level=1)                   0.763      1.052       1.38 (!)
MueLu: SaPFactory_kokkos: Prolongator smoothing (level=2)          0.625      0.652       1.04
MueLu: UncoupledAggregationFactory_kokkos: Build (level=0)         0.410      0.469       1.14
MueLu: CoalesceDropFactory_kokkos: Build (level=1)                 0.347      0.954       2.75 (!)
MueLu: FilteredAFactory: Matrix filtering (level=1)                0.256        nan        nan
MueLu: UncoupledAggregationFactory_kokkos: Build (level=1)         0.254      0.226       0.89
MueLu: CoordinatesTransferFactory_kokkos: Build (level=1)          0.109      0.207       1.90 (!)
MueLu: Ifpack2Smoother: Setup Smoother (level=2)                   0.106      0.098       0.93
```

**Comment by aprokop** [comment]
Just for fun, ran 4 MPI ranks vs 1 MPI ranks with 4 OpenMP threads

```
timer name                                                           mpi     openmp      ratio
MueLu: RAPFactory: Computing Ac (level=1)                          6.353      8.564       1.35 (!)
MueLu: Ifpack2Smoother: Setup Smoother (level=0)                   4.038      3.671       0.91
MueLu: SaPFactory_kokkos: Prolongator smoothing (level=1)          3.720      5.145       1.38 (!)
MueLu: RAPFactory: Computing Ac (level=2)                          2.007      2.011       1.00
MueLu: Ifpack2Smoother: Setup Smoother (level=1)                   1.609      0.899       0.56
MueLu: CoalesceDropFactory_kokkos: Build (level=0)                 1.482      1.892       1.28 (!)
MueLu: RAPFactory: Computing Ac (level=3)                          1.092      0.098       0.09
MueLu: SaPFactory_kokkos: Prolongator smoothing (level=2)          1.060      0.575       0.54
MueLu: FilteredAFactory: Matrix filtering (level=0)                0.885        nan        nan
MueLu: Ifpack2Smoother: Setup Smoother (level=2)                   0.798      0.078       0.10
MueLu: SaPFactory_kokkos: Prolongator smoothing (level=3)          0.726      0.034       0.05
MueLu: TentativePFactory_kokkos: Build (level=1)                   0.607      0.706       1.16 (!)
MueLu: RepartitionFactory: Build (level=3)                         0.519      0.001       0.00
MueLu: UncoupledAggregationFactory_kokkos: Build (level=0)         0.317      0.370       1.17
MueLu: UncoupledAggregationFactory_kokkos: Build (level=1)         0.260      0.241       0.93
```

![mpi4_vs_openmp4_filter](https://user-images.githubusercontent.com/7297887/30040576-0d79cdae-91af-11e7-9036-e237f710b77d.png)

Not sure what's going on with the matrix-matrix multiply, the time does not change with 4 threads. Does it really use the new threaded version?

**Comment by csiefer2** [comment]
@aprokop Rebuild with -DTpetra_ENABLE_MMM_Timings: If you see timers with "OpenMP" in them, then yes, you're getting the OpenMP multiply.

The build control for that has been in various states of disarray for the last two weeks... In theory it should be OK now (but somebody should check).

**Comment by aprokop** [comment]
Things to do to merge the current changes upstream:
- Merge `Xpetra::Map::getLocalMap()` (#1661)
- Merge `Xpetra::TpetraCrsMatrix::getLocalMatrix`
- Add `Kokkos::StaticCrsGraph::rowConst()` unit tests

**Comment by aprokop** [comment]
Making unit tests pass is really hard. Spent a day today on this, and am still confused. The remaining test is the TentativeP in unit tests Kokkos when running with Epetra. The test tests `||fine_nullspace - P*coarse_nullspace||`. It fails due to a too large norm. But dumping the matrix and vectors shows that everything is fine. In fact, dumping and reading the matrix back makes the test pass.

I think the issue is somewhere with Xpetra/Epetra `expertStaticFillComplete` routine. Not sure where, though, and eyeballing the code did not reveal anything particularly stupid. The import and export seem to be constructed correctly. There is a lot of state logic in `Epetra_CrsMatrix.cpp`, but nothing stands out.

**Comment by aprokop** [comment]
OK, the failing Epetra issue was identified: #1711.

**Comment by aprokop** [comment]
Currently failing tests on CUDA:
```
The following tests FAILED:            
         18 - MueLu_UnitTestsEpetra_MPI_1 (Failed)                             
         19 - MueLu_UnitTestsEpetra_MPI_4 (Failed)                             
         24 - MueLu_UnitTestsTpetra_kokkos_MPI_1 (Failed)                      
         25 - MueLu_UnitTestsTpetra_kokkos_MPI_4 (Failed)                      
         47 - MueLu_BlockedTransfer_Tpetra_MPI_4 (Failed)                      
         52 - MueLu_Navier2DBlocked_Epetra_MPI_4 (Failed)                      
         53 - MueLu_Navier2DBlocked_xml_format_MPI_4 (Failed)                  
         54 - MueLu_Navier2DBlocked_xml_format2_MPI_4 (Failed)                 
         55 - MueLu_Navier2DBlocked_xml_blockdirect_MPI_4 (Failed)             
         56 - MueLu_Navier2DBlocked_xml_bgs1_MPI_4 (Failed)                    
         57 - MueLu_Navier2DBlocked_xml_bs1_MPI_4 (Failed)                     
         58 - MueLu_Navier2DBlocked_xml_bs2_MPI_4 (Failed)                     
         59 - MueLu_Navier2DBlocked_xml_sim1_MPI_4 (Failed)                    
         60 - MueLu_Navier2DBlocked_xml_sim2_MPI_4 (Failed)                    
         61 - MueLu_Navier2DBlocked_xml_uzawa1_MPI_4 (Failed)                  
         62 - MueLu_Navier2DBlocked_xml_indef1_MPI_4 (Failed)                  
         65 - MueLu_Navier2DBlocked_BraessSarazin_MPI_4 (Failed)               
         66 - MueLu_Navier2DBlockedReuseAggs_MPI_4 (Failed)                    
         67 - MueLu_Navier2DBlocked_Simple_MPI_4 (Failed) 
```

**Comment by aprokop** [comment]
After couple fixes:
```
         24 - MueLu_UnitTestsTpetra_kokkos_MPI_1 (Failed)                      
         25 - MueLu_UnitTestsTpetra_kokkos_MPI_4 (Failed)                      
         47 - MueLu_BlockedTransfer_Tpetra_MPI_4 (Failed) 
```

**Comment by mhoemmen** [comment]
Could `! haveGlobalConstants_` relate to @csiefer2 's optimization of telling fillComplete not to compute global constants?

**Comment by aprokop** [comment]
@mhoemmen Possibly, however at this point I expect that there is something special about blocked matrices layers in MueLu and Xpetra, rather than something in Tpetra, as all other tests pass.

**Comment by aprokop** [comment]
@tawiesn Tobias, would you help time to help me figure this one out?

**Comment by aprokop** [comment]
@mhoemmen Thanks to pointing to the right direction, though. I see a lot of churn regarding that in the Xpetra's matrix-matrix multiply, so maybe this is a corner case somehow.

**Comment by aprokop** [comment]
OK, fixed the block matrix-matrix. Out of three places to add `computeGlobalConstants()` to, it was added only to one.

All the tests pass now, both on CUDA and OpenMP. The branch is ready to merge, and only waiting for the Kokkos snapshot to introduce `rowConst()` to `StaticCrsGraph`.

**Comment by aprokop** [comment]
Just ran the checkin script without push to make sure everything is tip top... It's not. Stokhos.

**Comment by aprokop** [comment]
Was a bit too hasty: the QR decomposition in TentativePFactory_kokkos is really a mix of Scalar and double. Stokhos scalars and doubles do not mingle well together. Will need to figure things out, I guess.

**Comment by aprokop** [comment]
OK, current version pushed upstream.

@csiefer2 @jhux2 @trilinos/muelu All tests including kokkos passed in the checkin script. Please add `-D MueLu_ENABLE_Kokkos_Refactor=ON` and `-D Xpetra_ENABLE_Kokkos_Refactor=ON` from now on.
