### ISSUE TITLE
Phalanx build error with Intel compiler

### ISSUE THREAD

**Issue by ibaned** [trilinos/Trilinos#1687]
Nightly builds of Albany using this SEMS Intel compiler:
```
/projects/sems/install/rhel6-x86_64/sems/compiler/intel/17.0.1/openmpi/1.8.7/bin/mpicxx
```
are producing the following error while compiling Trilinos:
```
Trilinos/packages/phalanx/src/Phalanx_DataLayout_DynamicLayout.hpp(89): error #809: exception specification for virtual function "PHX::Layout::~Layout" is incompatible with that of overridden function "PHX::DataLayout::~DataLayout"
```
@trilinos/phalanx

**Comment by rppawlo** [comment]
@ibaned Can you send me a list of the sems modules you loaded and a corresponding configure script.

**Comment by rppawlo** [comment]
@ibaned Fixes are in. derived dtors needed noexcept declaration. checkin-test script is running.

**Comment by ibaned** [comment]
@rppawlo thanks, I was getting you the configuration but I guess you're all set.

**Comment by rppawlo** [comment]
Changes pushed. Moving to in_review. Will close if Albany tests pass tonight.

**Comment by rppawlo** [comment]
> I was getting you the configuration but I guess you're all set.

yeah - sorry - was having trouble with the config, but finally figured it out...

**Comment by ibaned** [comment]
Unfortunately the dashboard in question uses the Trilinos master branch, so unless we do some manual overriding we'll have to wait for Trilinos to merge develop into master.

**Comment by rppawlo** [comment]
@ibaned - I'm fine with leaving it open until verified on master.

**Comment by ibaned** [comment]
There has finally been a merge to master (~400 commits, about a month of lag). Tomorrow's dashboard should confirm.

**Comment by ibaned** [comment]
Sorry this took so long to confirm, there was another build error due to using a non-C++11-compliant Intel compiler. This issue is definitely fixed, closing.
