### ISSUE TITLE
Tpetra: Add ExecutionSpaceCanAccessMemorySpace type trait

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#1697]
@trilinos/tpetra

Kokkos has some Impl namespace type traits for determining whether an execution space can access a memory space.  They are in the Impl namespace, though, and therefore not OK for external use.  They also have a quirk: you have to use the execution space's memory space for the first argument, not the execution space itself.  See https://github.com/kokkos/kokkos/issues/178 .

This suggests that Tpetra needs the following type trait class, to be added to the `Tpetra::Details` namespace.
```
template<class ExecSpace, class MemSpace>
struct ExecutionSpaceCanAccessMemorySpace {
  // Let either template argument be a Kokkos::Device, 
  // execution space, or memory space.
  typedef typename ExecSpace::execution_space execution_space;
  typedef typename MemSpace::memory_space memory_space;

#ifdef KOKKOS_ENABLE_CUDA
  static constexpr bool exec_space_is_cuda =
    std::is_same<execution_space, Kokkos::Cuda>::value;
  static constexpr bool mem_space_is_host_accessible =
    ! std::is_same<memory_space, Kokkos::CudaSpace>::value;
  static constexpr bool mem_space_is_cuda_accessible =
    std::is_same<memory_space, Kokkos::CudaSpace>::value ||
    std::is_same<memory_space, Kokkos::CudaUVMSpace>::value ||
    std::is_same<memory_space, Kokkos::CudaHostPinnedSpace>::value;
#else
  static constexpr bool exec_space_is_cuda = false;
  static constexpr bool mem_space_is_host_accessible = true;
  static constexpr bool mem_space_is_cuda_accessible = false; // trivially
#endif // KOKKOS_ENABLE_CUDA

  static constexpr bool value = 
    std::is_same<
      typename execution_space::memory_space,
      memory_space>::value ||
    (! exec_space_is_cuda && mem_space_is_host_accessible) ||
    (exec_space_is_cuda && mem_space_is_cuda_accessible);
};
```
This will need revision if other non-CUDA, non-host memory spaces show up that aren't host or device accessible.

**Comment by mndevec** [comment]
@mhoemmen  @srajama1 @crtrott @kyungjoo-kim @ambrad 

This is needed by kokkoskernels as well. I requested to take it out of Impl namespace: 
kokkos: https://github.com/kokkos/kokkos/issues/1092

Do you have plan to implement this in Tpetra?

**Comment by mhoemmen** [comment]
@mndevec I would rather that Kokkos implement it.  If Kokkos doesn't implement it, I might end up implementing it myself and putting it in `Tpetra::Details`.  However, it really does not belong in a public Tpetra namespace, because that would imply an incorrect coupling of Tpetra to Kokkos develop HEAD (rather than to the currently snapshotted version of Kokkos in Trilinos).  Note that the above implementation is incomplete; it doesn't know anything about `HBWSpace`, for example.

**Comment by kddevin** [comment]
This is a Kokkos issue.  Closing

**Comment by mhoemmen** [comment]
I moved this issue to Kokkos.  The original Kokkos issue ( https://github.com/kokkos/kokkos/issues/178 ) was closed without being finished, so I opened a new issue (I don't have permissions currently to reopen closed Kokkos issues).
