### ISSUE TITLE
Teuchos: TeuchosParser_Parser_UnitTests_MPI_1 succeeds on amd64, but fails on ppc64el

### ISSUE THREAD

**Issue by nschloe** [trilinos/Trilinos#1698]
Until recently, all tests that succeeded on amd64 also succeeded on ppc64el, but now `TeuchosParser_Parser_UnitTests_MPI_1` fails on ppc64el. Full details [here](https://launchpadlibrarian.net/334980880/buildlog_ubuntu-zesty-ppc64el.trilinos_12.13~git20170829-00ed31d9-1zesty1_BUILDING.txt.gz).
```
 75/980 Test  #75: TeuchosParser_Parser_UnitTests_MPI_1 ................................................................***Failed    2.09 sec
--------------------------------------------------------------------------
[[45987,1],0]: A high-performance Open MPI point-to-point messaging module
was unable to find any relevant network interfaces:

Module: OpenFabrics (openib)
  Host: bos01-ppc64el-023

Another transport will be used instead, although this may result in
lower performance.
--------------------------------------------------------------------------
Teuchos::GlobalMPISession::GlobalMPISession(): started processor with name bos01-ppc64el-023 and rank 0!

***
*** Unit test suite ...
***


Sorting tests by group name then by the order they were added ... (time = 3.78e-06)

Running unit tests ...

0. Parser_finite_automaton_UnitTest ... 
 
 p=0: *** Caught standard std::exception of type 'std::logic_error' :
 
  /<<PKGBUILDDIR>>/packages/teuchos/parser/src/Teuchos_FiniteAutomaton.cpp:87:
  
  Throw number = 1
  
  Throw test that evaluated to true: !(symbol < get_ncols(fa.table))
  
  Error!
 [FAILED]  (0.000373 sec) Parser_finite_automaton_UnitTest
```

**Comment by ibaned** [comment]
Hmm... I'm responsible for this code, but I might not be able to figure this out without access to a machine of this architecture...  @nschloe is there a cloud service that could provide one?

@trilinos/framework do we have `ppc64el` machines?

**Comment by ibaned** [comment]
so I wasn't familiar with the architecture codes, but I guess Power 8 is in this category? If so I should have a machine I can test on.

**Comment by ibaned** [comment]
I've replicated the issue, will now debug it.

**Comment by ibaned** [comment]
subtle issue related to `char = unsigned char` on this architecture, versus `signed char` on most others. Fix is in PR #1700, which I'll kick off the merge process for right away.

**Comment by ibaned** [comment]
Fix is in develop branch now.

**Comment by ibaned** [comment]
I'll close this assuming that it fixes the problem (confirmed on our POWER8 machine), but please reopen it if it doesn't actually fix it.

**Comment by nschloe** [comment]
Thanks!
