### ISSUE TITLE
Panzer does instantiate "long long" global ordinal even if Tpetra doesn't

### ISSUE THREAD

**Issue by crtrott** [trilinos/Trilinos#170]
Panzer should check Tpetra macros for whether to use long long as global ordinal or not. If Tpetra does not enable it don't try to instantiate tpetra on it. 

@trilinos/panzer

**Comment by bathmatt** [comment]
What is the flag in tpetra...  CMakeLists.txt:IF(Teuchos_ENABLE_LONG_LONG_INT)
is in the cmake file

**Comment by crtrott** [comment]
Its Tpetra_INST_INT_LONG_LONG

**Comment by bathmatt** [comment]
Fixed 23d295ffb3759a4ff22532faba14b24fce6d3d37
