### ISSUE TITLE
Panzer:  Unused Parameter Warnings

### ISSUE THREAD

**Issue by jmgate** [trilinos/Trilinos#1702]
@eric-c-cyr, @rppawlo, I've seen plenty of `-Wunused-parameter` warnings that I thought were due to compiling with `-Wpedantic`.  After removing that flag, I'm still seeing them&mdash;apparently gcc's unused parameter warnings now show up with `-Wall -Wextra`.  #1644 reminded me of this, and there are some possible solutions in that discussion.  Should we see about doing something like

```c++
#define PANZER_UNUSED(x) (void)x
```

which we can then use like

```c++
foo(type1 arg1, type2 arg2)
{
  PANZER_UNUSED(arg1)
  ...
}
```

That sound good to you two?
@trilinos/panzer

**Comment by eric-c-cyr** [comment]
I'm not sure I'm in love with this. Why would the compiler complain about unused arguments? How does this work in a world of overloading and virtual functions. Unused arguments would seem to be a design feature of the language.

**Comment by rppawlo** [comment]
I really don't like this. It's just adding to code complexity. now users have to ewaste time learning another macro. Unless I'm missing something, we can just write the parameter in the declaration for documentation in doxygen and leave it out in the definition to get rid of the compiler warning. I do this all the time in phalanx and it is warning free with -Wall -pedantic

decl:
```void foo(int i);```

impl:
```void foo(int ){...}```

**Comment by ibaned** [comment]
This is very closely related to #1644, in which ROL had unused variable warnings and chose the macro approach. Personally, @rppawlo's solution seems better to me, no special new macros in each package.

**Comment by ibaned** [comment]
@eric-c-cyr unused arguments in a particular implementation are equivalent to declaring variables and never using them. as @rppawlo points out you can omit the name in just the implementations (e.g. overloads or overrides) that don't use it.

**Comment by bartlettroscoe** [comment]
@rppawlo 

> Unless I'm missing something, we can just write the parameter in the declaration for documentation in doxygen and leave it out in the definition to get rid of the compiler warning.

Do you have an example for us to look at?  How does Doxygen show the protoype with variable names in the Doxygen output?  How does Doxygen know the correct order of the parameters?

**Comment by rppawlo** [comment]
in the DAG_Manager in Phalanx there is an example of a deprecated function where one veriable is no longer used.

declaration:
```
    void writeGraphvizFile(const std::string filename,
			   bool writeEvaluatedFields,
			   bool writeDependentFields,
			   bool debugRegisteredEvaluators) const;
```

definition:
```
template<typename Traits>
void PHX::DagManager<Traits>::
writeGraphvizFile(const std::string filename,
		  bool writeEvaluatedFields,
		  bool writeDependentFields,
		  bool ) const
{
  writeGraphvizFileNew(filename,writeEvaluatedFields,writeDependentFields);    
}
```

I had to remove the unused parameter from the definition to suppress the unused warning. Doxygen still pulled out the names from the declaration. Here's the doxygen from Trilinos.org:

![screen shot 2017-09-07 at 9 24 43 am](https://user-images.githubusercontent.com/2109877/30165689-f5f11258-93ae-11e7-9f26-8ad2098d6a1a.png)

**Comment by jmgate** [comment]
Nice!  This (omitting the variable names in the `impl` file) does seem like a much cleaner solution.

**Comment by jmgate** [comment]
What would we do about implicitly inline functions?  For instance,

```c++
class Foo
{
  /**
   *  Doxygen goes here.
   */
  returnType bar(type arg)
  {
    // do something, but don't use arg
  } // end of bar()
}; // end of class Foo
```

We want `arg` in there for the sake of the Doxygen.  Would we have to switch this to

```c++
class Foo
{
  /**
   *  Doxygen goes here.
   */
  returnType bar(type arg);
}; // end of class Foo

inline
returnType Foo::bar(type /* arg */)
{
  // do something, but don't use arg
} // end of Foo::bar()
```

**Comment by rppawlo** [comment]
Splitting the definition from the declaration is probably the best choice, but I think both use cases are valid. Do we really need arg in there for the sake of doxygen? We usually list the function parameters in order in doxygen so it's usually not too hard to match them up:

```
//! class Foo
class Foo
{
public:
  /** \brief bar
   *
   *  \param[in] arg1 - ...
   *  \param[in] ??? - Second argument is unused in this specific implementation
   *  \param[in] arg3 - ...
   */
  returnType bar(int arg1, int , double arg3)
  {
    // do something
  } 
};
```

Here's the output. Is this hard to figure out?

![screen shot 2017-09-07 at 2 33 11 pm](https://user-images.githubusercontent.com/2109877/30179165-744759e4-93d9-11e7-956e-ebcba1d1efcc.png)

**Comment by jmgate** [comment]
That seems like it'd be fine.

**Comment by jmgate** [comment]
At this point I've cleaned up all 5201 `unused-parameter` warnings in Panzer.  Merging soon.
