### ISSUE TITLE
Tpetra test depends on Epetra header file

### ISSUE THREAD

**Issue by egboman** [trilinos/Trilinos#171]
When I build Trilinos with Tpetra and tests enabled, but without Epetra, I get the error:

/home/egboman/trilinos/Trilinos/packages/tpetra/core/example/advanced/Benchmarks/localView.cpp:90:31: fatal error: Epetra_SerialComm.h: No such file or directory
compilation terminated.

It looks like the line including that header file is not properly guarded by 
#ifdef HAVE_TPETRACORE_EPETRA

**Comment by mhoemmen** [comment]
Hi Erik -- unfortunately I'm not able to fix this right now.  Your assumption about the fix is correct.  If you could send me a pull request I could approve it.  Otherwise, it may have to wait a few days.  Thanks for reporting though!

**Comment by egboman** [comment]
No rush, a simple work-around was to enable Epetra.

**Comment by mhoemmen** [comment]
I was able to manifest this bug by running the check-in test script, enabling Tpetra, and disabling Epetra.

.../Trilinos/packages/tpetra/core/example/advanced/Benchmarks/localView.cpp:90:10: fatal error: 'Epetra_SerialComm.h' file not found
#include "Epetra_SerialComm.h"
         ^
1 error generated.

**Comment by mhoemmen** [comment]
Fix written.  Build passes with Epetra disabled.  Now testing with Epetra enabled just to make sure.

**Comment by mhoemmen** [comment]
Build passes with Epetra enabled.  Now running check-in test script.

**Comment by egboman** [comment]
Mark: Thanks for quick bug fix!

**Comment by mhoemmen** [comment]
@egboman Good warm-up for testing my current temporary testing rig.
