### ISSUE TITLE
Stokhos_KokkosCrsMatrixUQPCEUnitTest_Serial_MPI_1 failing for clean builds

### ISSUE THREAD

**Issue by jwillenbring** [trilinos/Trilinos#1710]
@trilinos/stokhos 
CC: @trilinos/framework 

The clean builds

[https://testing.sandia.gov/cdash/viewTest.php?onlyfailed&buildid=3097231](https://testing.sandia.gov/cdash/viewTest.php?onlyfailed&buildid=3097231)

and

[https://testing.sandia.gov/cdash/viewTest.php?onlyfailed&buildid=3096601](https://testing.sandia.gov/cdash/viewTest.php?onlyfailed&buildid=3096601)

Are showing a failure for test Stokhos_KokkosCrsMatrixUQPCEUnitTest_Serial_MPI_1  since it was reenabled for the continuous build.

**Comment by tjfulle** [comment]
CC: @etphipp

**Comment by mhoemmen** [comment]
Argh, I _just_ approved #1665, but that was probably after those clean builds started, right?

**Comment by etphipp** [comment]
I believe those build don't have the commit I pushed to fix that test for the CI builds.  Looking at the configure output, HEAD is at:

--------------------------------------------------------------------------------
*** Base Git Repo: Trilinos
7791da2 [Wed Sep 6 18:38:24 2017 -0600] <rabartl@sandia.gov>
Disable failing test Stokhos_KokkosCrsMatrixUQPCEUnitTest_Serial_MPI_1 for CI bu
 --------------------------------------------------------------------------------

The next commit in the develop branch is my fix for that failing test.  So I think it will be resolved once that commit is pulled into the build.

I don't really know what the "clean" builds are and the build log says there are 0 git updates.  Why did it not pull in all of the updates before the build started?

**Comment by etphipp** [comment]
Sorry about the formatting on that.  I should have previewed it before commenting.

**Comment by ibaned** [comment]
@etphipp I just edited it for you. Just put three backticks before and after the terminal text.

**Comment by etphipp** [comment]
I didn't realize you could edit a previous comment (although now I see the little pencil).  Learn something new every day!

**Comment by etphipp** [comment]
As I suspected, this test passed once the git update pulled in my changes to fix the test (Thursday I think), and the "clean" builds have been clean.  So I'm closing this.
