### ISSUE TITLE
Tpetra::Map: Make isContiguous() accurate instead of conservative

### ISSUE THREAD

**Issue by aprokop** [trilinos/Trilinos#1715]
In the Tpetra::Map constructor based on the element list (both Kokkos and Teuchos version), `contiguous_` is unconditionally set to false. We could add a check first whether it is locally contigous (`lastContiguousGID_ - firstContiguousGID_ == numLocal-1`) with a single global reduction to check the global contiguity.

I don't think this check would save much, probably only for non-savvy users that somehow construct contiguous maps based on element lists. Plus, there is a bunch of optimizations in `LocalMap` based on `firstContiguousGID_` and friends.

Feel free to close if you also think there are not situations where this would really help.

**Comment by mhoemmen** [comment]
It _could_ be helpful for `contiguous_` to be accurate instead of conservative.  I care more about that than about an optimization that users could take themselves by just reading the documentation a little bit.  The noncontiguous constructor does an all-reduce anyway, so you could just pass along contiguity information through there without an extra communication step.

**Comment by aprokop** [comment]
@mhoemmen Cool, I think I could do this.

As a side note, now that I started optimizing stuff for MueLu, it would be super helpful to me if there was a list of Tpetra stuff that's known to be inefficient. If some of that could severely affect MueLu or some Ifpack2 smoothers, I could maybe fix those. One of the things I've encountered today is that getting a matrix diagonal takes forever relatively speaking. I wonder if replacing Unmanaged subviews with the newly introduced rowConst() in the StaticCrsGraph could help that.

**Comment by mhoemmen** [comment]
@aprokop wrote:
> ... [N]ow that I started optimizing stuff for MueLu, it would be super helpful to me if there was a list of Tpetra stuff that's known to be inefficient.

I'll e-mail you a list.  I can think of two things in particular that could affect fillComplete MPI scaling.  MueLu does a lot of expertStaticFillComplete, though, so it might not be such a big deal.  If you want to do overlapping domain decomposition smoothers, though, it could matter a lot.

**Comment by mhoemmen** [comment]
@csiefer2 @jhux2 this didn't actually get fixed btw
