### ISSUE TITLE
Undefined LAPACK symbols on OS X 10.12 Sierra

### ISSUE THREAD

**Issue by plindsa** [trilinos/Trilinos#1718]
I'm a new user trying to build Albany on a MacBook Pro running OS X Sierra. When building Albany (and Trilinos with tests enabled, oddly enough), I get the following error:

Undefined symbols for architecture x86_64:
"dggsvd", referenced from:
Epetra_LAPACK::GGSVD(char, char, char, int, int, int, int*, int*, double*, int, double*, int, double*, double*, double*, int, double*, int, double*, int, double*, int*, int*) const in libepetra.a(Epetra_LAPACK.cpp.o)
"sggsvd", referenced from:
Epetra_LAPACK::GGSVD(char, char, char, int, int, int, int*, int*, float*, int, float*, int, float*, float*, float*, int, float*, int, float*, int, float*, int*, int*) const in libepetra.a(Epetra_LAPACK.cpp.o)

I’ve tried a few things based on solutions other people having similar problems. The closest one I found was another user trying to build Albany on a mac (https://trilinos.org/pipermail/trilinos-users/2016-March/005397.html). Evidently, the work-around there was to use
-D BUILD_SHARED_LIBS:BOOL=OFF
but I tried that myself and it didn’t work for me. I also tried using g++ and clang++ vs. gcc when compiling, which I did using export CXX, but that didn't help either. Finally, I tried pointing to my Lapack install directory using
-D LAPACK_LIBRARY_DIRS:PATH="${LAPACK_ROOT}"
but that also was no good. Any help or advice on how to proceed would be appreciated.

**Comment by plindsa** [comment]
FYI: I originally posted this on the Albany page and was redirected here.

**Comment by ibaned** [comment]
I'm also going to rename the issue to more closely reflect what the linker error is, and mention @trilinos/epetra

**Comment by plindsa** [comment]
Thanks!

**Comment by Yatagarasu50469** [comment]
Salutations plindsa. I realize that this comment may come far too late to be of any use for yourself, however in my experience the error you mention regarding dggsvd on OS X can be fixed by installing the open blas package.
