### ISSUE TITLE
Albany Ifpack2 build errors

### ISSUE THREAD

**Issue by ibaned** [trilinos/Trilinos#1722]
The nightly Albany builds say:
```
TrilinosInstall/include/Ifpack2_BlockTriDiContainer_def.hpp:1737:100: error: wrong number of template arguments (1, should be 5)
TrilinosInstall/include/Ifpack2_BlockTriDiContainer.hpp:2
TrilinosInstall/include/Ifpack2_ContainerFactory_decl.hpp:51
TrilinosInstall/include/Ifpack2_ContainerFactory.hpp:1
TrilinosInstall/include/Ifpack2_BlockRelaxation_decl.hpp:52
TrilinosInstall/include/Ifpack2_BlockRelaxation.hpp:1
TrilinosInstall/include/Ifpack2_Details_OneLevelFactory_def.hpp:54
TrilinosInstall/include/Ifpack2_Details_OneLevelFactory.hpp:2
TrilinosInstall/include/Thyra_Ifpack2PreconditionerFactory_def.hpp:51
TrilinosInstall/include/Thyra_Ifpack2PreconditionerFactory.hpp:2
TrilinosInstall/include/Piro_InvertMassMatrixDecorator_Def.hpp:57
TrilinosInstall/include/Piro_InvertMassMatrixDecorator.hpp:165
TrilinosInstall/include/Piro_VelocityVerletSolver_Def.hpp:49
TrilinosInstall/include/Piro_VelocityVerletSolver.hpp:130
TrilinosInstall/include/Piro_SolverFactory_Def.hpp:50
TrilinosInstall/include/Piro_SolverFactory.hpp:97
Albany/src/Albany_SolverFactory.cpp:24
```

@trilinos/ifpack2 

@ambrad I remember mention of Ifpack2 changes in the Kokkos promotion discussion. Could this be at all related?

I'm assuming that this is due to Trilinos changes and not Albany ones, but I could be wrong about that.

**Comment by ambrad** [comment]
@ibaned, is this in a no-ETI build? I'm thinking the integration tests of various sorts all use ETI.

**Comment by jhux2** [comment]
Non ETI builds are also an issue in #1707.  @ibaned Non-ETI is standard for Albany?

**Comment by ambrad** [comment]
@jhux2, Albany tests both. You can see the Albany dashboard here: http://my.cdash.org/index.php?project=Albany

I'm working on reproducing this build failure and will report back when I can.

**Comment by ikalash** [comment]
@ambrad : yes, this is a non-ETI build (my nightly builds actually).  We cannot use ETI (unfortunately) b/c we use DTK which cannot be compiled at the present time with ETI.

**Comment by mhoemmen** [comment]
@ikalash I have a suspicion why you might think that DTK can't be built with ETI ON.  I'll send you an e-mail to see if we can fix that.

**Comment by tjfulle** [comment]
@mhoemmen , please cc me - I'd like to use ETI with DTK too

**Comment by mhoemmen** [comment]
@tjfulle Done! :-)

**Comment by ikalash** [comment]
@mhoemmen : thanks for the email.  I'll reply - I can try your fix when I return to the office next week from Germany.

**Comment by ikalash** [comment]
@mhoemmen : it may be worth including @rppawlo and @sslattery in discussion about your proposed fix - they are DTK developers.

**Comment by ibaned** [comment]
Hang on a sec. The build that I was looking at was @mperego 's, and I think it has ETI on. Other builds failed including @ikalash 's, but I'd like to focus on this one.
Furthermore, Trilinos itself compiled and installed okay, but compiling Albany failed as seen above. Here is the Trilinos configuration:

http://my.cdash.org/viewConfigure.php?buildid=1285722

**Comment by ibaned** [comment]
For completeness, here is the Trilinos build:
http://my.cdash.org/index.php?project=Albany&subproject=JengaTrilinosDev
and the Albany build:
http://my.cdash.org/index.php?project=Albany&subproject=JengaAlbany

So unless this has ETI off, I don't think that is the cause of this. Rather, its something thats not tested by compiling Trilinos libraries alone.

**Comment by ambrad** [comment]
Hrmmm. The fact that the build error sees code in the _def.hpp file implies that, whether ETI is on or off, something outside of Trilinos is pulling the _def.hpp file into the Albany-side translation unit. Right?

**Comment by ibaned** [comment]
The generated `Ifpack2_BlockTriDiContainer.hpp` contains these lines:

```
#include "Ifpack2_BlockTriDiContainer_decl.hpp"
#include "Ifpack2_BlockTriDiContainer_def.hpp"
```

**Comment by ambrad** [comment]
Yes, that implies ETI is off. Thanks for the info.

**Comment by ibaned** [comment]
@mhoemmen @ikalash please include me in the DTK discussion as well

@mhoemmen @ambrad is there a simple guide to turning ETI on over most of Trilinos? I suspect most of my builds have it off, and I'll need to explain the transition to other Albany developers.

**Comment by ambrad** [comment]
I'm not sure what the official way is, but I use this pattern:
```
    -D Trilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON \
    -D Teuchos_ENABLE_COMPLEX:BOOL=On \
    -D Teuchos_ENABLE_LONG_LONG_INT:BOOL=On \
    -D Tpetra_INST_INT_LONG_LONG=Off \
    -D Tpetra_INST_INT_LONG:BOOL=On \
    -D Tpetra_INST_COMPLEX_DOUBLE:BOOL=On \
```

**Comment by mhoemmen** [comment]
@ibaned wrote:
> is there a simple guide to turning ETI on over most of Trilinos?

  1. Turn on ETI: `-D Trilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON`
  2. Make sure that the `Scalar`, `GlobalOrdinal`, and `Node` types you want are enabled.

You have to do (2) regardless of ETI (please don't be sloppy about that!), but your application definitely won't link if ETI is ON and you don't enable what you want.  For example, if you want double complex arithmetic:
```
-D Teuchos_ENABLE_COMPLEX:BOOL=ON
-D Trilinos_ENABLE_COMPLEX_DOUBLE:BOOL=ON
```
(NOTE: @ambrad If you set `Tpetra_INST_COMPLEX_DOUBLE` but don't set `Trilinos_ENABLE_COMPLEX_DOUBLE`, you won't get the benefit of ETI for kokkos-kernels.)

If you want `GlobalOrdinal = long` to work, and you don't need `GlobalOrdinal = long long`:
```
-D Tpetra_INST_INT_LONG:BOOL=ON
-D Tpetra_INST_INT_LONG_LONG:BOOL=ON
```

**Comment by ibaned** [comment]
Thanks! Also, `float` is off by default right? If it even exists? So if I don't enable complex I should just get `double` for my `Scalar` types.

**Comment by ibaned** [comment]
> The struct `Side` was conflicting with a struct in Albany

Wow, that is a subtle issue. Thanks for figuring it out, @ambrad !

**Comment by ambrad** [comment]
@ibaned, yes, `float` is off by default, and so is `complex<float>`.

**Comment by ambrad** [comment]
The check-in script is merrily doing its thing. The fix confirmed to work in the Albany build I used to reproduce the error.

**Comment by ibaned** [comment]
The public dashboard confirms this is fixed. Closing this issue.
