### ISSUE TITLE
Be able to annotate commit with test results from multiple builds

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#1725]
@trilinos/framework 

Here are the relevant parts of the #1304 discussion that led to this:

@tjfulle wrote:
> @bartlettroscoe, this may be addressed elsewhere, but is there a best practice for the case that I want to test on multiple machines before pushing (or opening a PR)? For example, with Tpetra, I want to make sure that the standard checkin tests pass on my RHEL blade (obviously), but also different builds on different architectures. In this case, I may push to a branch on my fork and then update and run tests on the several different machines from that branch. The only way (that I know of) to then report test results is to amend the last commit manually with test results and force push. Perhaps there is a better way?

I wrote:
> @tjfulle I like your thinking :-) . Right now, one must add text manually to the commit message, explaining what tests passed where. We don't necessarily want to annotate every commit with all the information needed to replicate a test, but some brief mention that (e.g.,) it was tested with CUDA in a debug build could be nice.

@bartlettroscoe wrote:
> That would not be too hard to do with crafty usage of the checkin-test.py script. You could run the `checkin-test.py` script on each machine separately (e.g. with `--local-do-all`) for special `--extra-st-builds=<specialBuildNamei>` and then you could copy a subset of the `<specialBuildNamei>/*.out` files and all of the `<specialBuildNamei>/*.success` files to your CEE LAN machine and then the `checkin-test-sems.sh` script could be run with the full list of `--extra-st-builds=<specialBuildName1>,<specialBuildName2>,...` and it would correctly list those extra builds and would amend the top commit message with all of those builds and would also archive the details of those builds to the `trilinos-checkin-tests` email list on push. If you combine the moving of a branch and remote run approach demonstrated in `remote-pull-test-push.sh` and combine that with the aggregation of multiple runs of the `checkin-test.py` script in `checkin-test-crf450-cmake-2.8.11.sh` and add some `scp` commands to copy files back, then you basically have it. One could even write some reusable utility scripts to help drive a process like this so many developers could use it.

**Comment by bartlettroscoe** [comment]
@mhoemmen  and @tjfulle,

Let me now how urgent this is?  In any case, I could I outline in detail what this super script would look like and then one of you could try fleshing it out and testing it and seeing how it goes?  If we are really fancy, we could even launch the different builds in parallel on the different machines and then wait for them before doing the copies back and doing the final analysis and push (if everything passed).  That should be pretty easy to do with bash scripts.  Could be fun.

**Comment by mhoemmen** [comment]
@bartlettroscoe wrote:
> How urgent this is?

It could be useful for @crtrott , to do e.g., Kokkos promotion.  Right now, he has to do testing on multiple platforms in ad-hoc fashion.  Any record of where he tested is entirely manual and ad hoc.  Having some kind of documentation embedded in the snapshot commit could help.

On the other hand, I think the people who are doing a lot of snapshots should weigh in first and express the urgency.  I mainly just wanted to document the feature request as an idea (@tjfulle's idea, in fact!).

**Comment by tjfulle** [comment]
@bartlettroscoe, if you sent me the outline, I could put something together at the start of the next FY.  I started putting something together but I wasn't sure how to have remote ssh processes communicate back the test results.  I'm swamped right now and put it on the back burner.

**Comment by bartlettroscoe** [comment]
@tjfulle,

> @bartlettroscoe, if you sent me the outline, I could put something together at the start of the next FY. I started putting something together but I wasn't sure how to have remote ssh processes communicate back the test results. I'm swamped right now and put it on the back burner.

Okay, sometime after the start of FY18 ping me again and I can do some experimentation to see what it will take to get this to work.  It should not be too bad.  I kind of like the idea of layering this on top if the checkin-test.py script. That script already supports so many use cases that I fear adding a lot of more features to it.  But a couple little features might be added that could better support a workflow like this (and topic-branch workflows in general).  Adding these few features is likely not a lot of work and should not add too much complexity to checkin-test.py.  I just don't want to add remote calls and things of that nature, at least not at this point.

**Comment by mhoemmen** [comment]
Thanks @bartlettroscoe ! :-D  The main customers should be anyone doing snapshotting, esp. Kokkos, so I think the Kokkos developers should really drive this.
