### ISSUE TITLE
Indexing bugs in Tpetra::Details::Blas::Default::gemm

### ISSUE THREAD

**Issue by etphipp** [trilinos/Trilinos#1733]
While using DGKS orthogonalization for GMRES in Belos, a collaborator of mine has run into some seg faults in Tpetra::Details::Blas::Default::gemm().  Examining that code, I believe the indexing is incorrect.  Consider first the case C = A*B.  Then, according to the code, we have:
```
m = static_cast<IndexType> (A.dimension_0 ());
n = static_cast<IndexType> (A.dimension_1 ());
k = static_cast<IndexType> (C.dimension_1 ());
```
Thus we must have A is m x n, B is n x k and C is m x k.  But then for the multiply code we have (removing some of the extraneous details):
```
      for (IndexType j = 0; j < n; ++j) {
        for (IndexType l = 0; l < k; ++l) {
          auto temp = alpha*B(l,j);
          for (IndexType i = 0; i < m; ++i) {
            C(i,j) = C(i,j) + temp*A(i,l);
          }
        }
      }
```
Given the definitions of n and k above, the bounds for the j and l loops are wrong.  It should be:
```
      for (IndexType j = 0; j < k; ++j) {
        for (IndexType l = 0; l < n; ++l) {
          auto temp = alpha*B(l,j);
          for (IndexType i = 0; i < m; ++i) {
            C(i,j) = C(i,j) + temp*A(i,l);
          }
        }
      }
```
A similar error occur with C = A^T * B, C = A * B^T and C = A^T * B^T.  In his code, we switched the loop bounds for C = A * B and and C = A^T * B, and got past the seg faults in GMRES (since I believe the other two aren't cases aren't called).  However it would probably be simpler just to switch how n and k are defined at the beginning of the function.   That is also a little more natural (I think) to make C m x n.

What is shocking to me is no one else has run into this, and I really don't understand how that is possible.

**Comment by etphipp** [comment]
CC:  @trilinos/tpetra @mhoemmen

**Comment by mhoemmen** [comment]
@etphipp It's not "shocking"; it's just that this code was meant as a fall-back replacement for the BLAS.  It's possible that not all cases get tested.  Conventional Scalar types don't exercise this code; they defer to the usual BLAS library.

**Comment by mhoemmen** [comment]
@etphipp Please send me a patch or PR and I'll fix it.

**Comment by etphipp** [comment]
You're right.  I realized over lunch that this code is probably never called by anybody except Stokhos.  Are there no tests for it?

We're working on a patch now.  Previously we didn't fix all 4 use cases.

**Comment by mhoemmen** [comment]
@etphipp wrote:
> Are there no tests for it?

MultiVector exercises the top-level GEMM interface, but there may not be tests for this level.  I can write a test for it.

**Comment by etphipp** [comment]
Attached is a patch, where we just renamed n and k.
[git_diff.txt](https://github.com/trilinos/Trilinos/files/1300947/git_diff.txt)

**Comment by mhoemmen** [comment]
@etphipp Thanks!  I found some other bugs in the routine -- it turns out that m and n need to come from C, not A.  I fixed the bugs, and added a test that exercises various dimensions and transpose combinations, comparing Tpetra::Details::Blas::Default::gemm and Tpetra::Details::Blas::gemm against Teuchos::BLAS::GEMM.  The test passes.  I am running the remote check-in test script now.

**Comment by mhoemmen** [comment]
I pushed a fix to develop.  Thanks @etphipp !
