### ISSUE TITLE
Amesos2: Examples in amesos2/example assume LO=int, GO=int

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#1734]
@trilinos/amesos2

**Comment by mhoemmen** [comment]
I first tested locally by building Amesos2 with `Tpetra_INST_INT_INT:BOOL=OFF`; it built and passed tests.  I then ran the remote check-in test script, which passed tests and pushed to develop.

**Comment by ndellingwood** [comment]
@mhoemmen The CMakeLists.txt will need to be modified as well to update/remove guards to enable the tests for various LO/GO combos, e.g.
```
IF (Tpetra_INST_INT_INT)
TRIBITS_ADD_EXECUTABLE(
  QuickSolve
  SOURCES quick_solve
  )
ENDIF ()

```

Would you like me to do this? I have access to sems modules on kokkos-dev for testing, but it's not properly setup so I would not be able to push changes with the checkin script (only test locally).

**Comment by mhoemmen** [comment]
@ndellingwood I would certainly welcome this; it would help improve build times quite a bit if we could disable `GO=int` (which is really just dead weight).  I would recommend doing this:

  1. Set `Tpetra_INST_INT_INT:BOOL=OFF`
  2. Attempt to build Amesos2 with as many TPLs enabled as possible
  3. Fix all build errors that can be fixed, by looking for `typedef int GO` etc. and replacing it with `typedef Tpetra::Map<>::global_ordinal_type`.
  4. Disable any tests that still fail to build

The trick is that some TPLs (MUMPS, perhaps?) insist on `GO=int`.  I'm not sure why, since the global indices could be copied in and out and even range-checked, but that's how it is.
