### ISSUE TITLE
Trilinos does not find Mumps

### ISSUE THREAD

**Issue by anates** [trilinos/Trilinos#1738]
When setting up Trilinos using cmake, it can not find the mumps-libraries. When setting them manually in the according file, they are deleted when rerunning cmake, and replaced with "_MUMPS_cmumps_LIBRARY-NOTFOUND" (and similar). Is that an error in Trilinos?

**Comment by mhoemmen** [comment]
@anates wrote:
> When setting them manually in the according file, ....

How did you do that?  In particular, what CMake options did you use?

**Comment by anates** [comment]
Modified CMakeCache, but on second thought I think that does not help anyway. Somehow the MUMPS-options did not show up in CMake-Gui. They showed up when I added the necessary keys by hand.

**Comment by mhoemmen** [comment]
@anates Does it work now?  If not, what were the keys that you modified, and what are their values?

**Comment by mhoemmen** [comment]
@anates Also, modifying CMakeCache.txt is not a good idea :-) .  Please either use the CMake GUI, or run `cmake` directly with the options you want.

**Comment by anates** [comment]
@mhoemmen Added the entry "TPL_MUMPS_LIBRARY_DIRS" and set it accordingly. Afterwards it worked fine

**Comment by mhoemmen** [comment]
@anates I'm glad it works now!  Trilinos' preference is that users set `MUMPS_LIBRARY_DIRS` first, and then only set `TPL_MUMPS_LIBRARY_DIRS` if that doesn't work.  The same holds for any third-party library, e.g., BLAS and LAPACK.
