### ISSUE TITLE
Tpetra: Document 3-Map finite-element global assembly use pattern

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#174]
@trilinos/tpetra @amklinv The three Maps in question refer to mesh points.  This is for a finite-element code where elements are uniquely owned by processes, but mesh points or other discretization goodies associated with elements may be shared by multiple processes.  In the text below, I'll assume that degrees of freedom live on mesh points, but the same considerations apply for degrees of freedom that live on edges.
1. Uniquely owned (nonoverlapping Map), with mesh points that my MPI process owns
2. Overlapping Map, with mesh points belonging to elements that my MPI processes owns
3. Overlapping Map, with mesh points connected to points in (1) or (2)

Map (3) is the column Map of the sparse graph / matrix.  Use replaceColumnMap if necessary.  We will fill out this pattern in more detail in discussion of this issue. It has already proven useful for at least three different applications, two of which use BlockCrsMatrix, and two of which use CrsMatrix.

**Comment by mhoemmen** [comment]
Hey @csiefer2 -- does your recent commit ef97b4c93095c71b0f8f06bdc11adf3802e44762 relate to this in any way?  (Mainly trying to save some effort, if it fixes this issue.)  Thanks!

**Comment by csiefer2** [comment]
No.  That test only works correctly in serial.

**Comment by mhoemmen** [comment]
@csiefer2 Cool, no worries :-)
