### ISSUE TITLE
Discuss, refine, and document subteam/subproject development branches

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#1740]
**CC:** @dridzal, @jwillenbring, @maherou

**Description:**

This story is to document a discussion about the subteam/subproject development workflow that I helped the ROL team to set up and how to generalize it and document it for the benefit of other Trilinos development subteams.

**Definition of Done:**

ToDo: Fill in once discussion is farther along so we can better scope this out

**Tasks:**

* Have initial discussion ...
* Decide on concrete "definition of done" and set of tasks to complete ...
* ???

**Comment by bartlettroscoe** [comment]
The below email thread was the motivation for this issue and provide some background.  (I had the permission from all of the participants in this email thread to post it).

I will respond to Denis' questions in the next comment.

----

From: Ridzal, Denis 
Sent: Wednesday, September 13, 2017 12:01 PM
To: Bartlett, Roscoe A
Cc: Heroux, Michael A ; Willenbring, James M 
Subject: Re: Subteam git workflows for TUG?
 
A github issue on subteam workflows sounds good.  Go ahead,

Denis
 
----

From: Bartlett, Roscoe A
Sent: Wednesday, September 13, 2017 9:54
To: Ridzal, Denis
Cc: Heroux, Michael A; Willenbring, James M
Subject: RE: Subteam git workflows for TUG? 
 
Denis,
 
I have opinions on all of this.  We can discuss here in an email chain or we can create a Trilinos GitHub issue so that we can archive it and other developers can see the conversation (i.e. document the requirements, right Mike :-)).
 
-Ross

----
 
From: Ridzal, Denis 
Sent: Wednesday, September 13, 2017 11:46 AM
To: Bartlett, Roscoe A
Cc: Heroux, Michael A ; Willenbring, James M 
Subject: Re: Subteam git workflows for TUG?
 
Hi Ross,
 
The new workflow is great.  It has increased the productivity of the ROL team significantly, allowing us to go "deep" into some of the new features, including changing interfaces, without having to worry about breaking the Trilinos CI process.  Most importantly, it has enabled developers to push a lot more frequently -- this is something that has me worried with the PR workflow, because of the sheer volume of potential pull requests.  In contrast, the subteam model should scale.
 
In any case, I think that this is worth documenting and demonstrating to the Trilinos community. 
 
One of the things we haven't defined yet is the frequency of merges with Trilinos.  I've been doing this manually, with the script that you and I developed, depending on the type and volume of changes I see in the commits.  For example, if I know that the team only touched a few files and the changes are mostly cosmetic, there is no urgency to merge.  For a subteam it may even make sense to leave the frequency of merges "undefined", within reason.
 
We should also discuss dealing with broken CI builds despite the success of the pre-push testing that is part of the sync process.  As we've seen, this can happen, and it did happen to ROL due to a nasty non-deterministic memory leak.  But we have a pretty good handle on the process now.

Finally, we need to think about how this will all work with the PR model.

Let me know how you would like to proceed,
 
Denis

----

From: Bartlett, Roscoe A
Sent: Wednesday, September 13, 2017 8:49
To: Ridzal, Denis
Cc: Heroux, Michael A; Willenbring, James M
Subject: Subteam git workflows for TUG? 
 
Hello Denis,
 
Assuming the ROL project/subteam git workflow we worked out is going well for the ROL team, should we document this and demonstrate it to the rest of the Trilinos development team at this year’s TUG on developer day?  In particular, is this making the development workflow for rank-and-file ROL developers any more productive and/or less painful?
 
Thanks,
 
-Ross

**Comment by bartlettroscoe** [comment]
Responding to @dridzal's questions from his above-listed email from 9/13/2017:

> The new workflow is great. It has increased the productivity of the ROL team significantly, allowing us to go "deep" into some of the new features, including changing interfaces, without having to worry about breaking the Trilinos CI process. Most importantly, it has enabled developers to push a lot more frequently -- this is something that has me worried with the PR workflow, because of the sheer volume of potential pull requests. In contrast, the subteam model should scale.

But if people use topic branches, then the PR workflow scales just fine (because subteam members will be frequently be pushing and pulling to the same topic branch).  It is just that using topic branches requires more knowledge and comfort with git than the subteam repo/branch workflow we came up with for ROL that is being discussed here.

> In any case, I think that this is worth documenting and demonstrating to the Trilinos community.

I send @jwillenbring an email suggesting a 30-60 minute session titled "Sub-team workflows for increased team productivity, tight team integration and scalable testing" for the 2017 TUG developer day next month.  Hopefully we can work that into the schedule.

> One of the things we haven't defined yet is the frequency of merges with Trilinos. I've been doing this manually, with the script that you and I developed, depending on the type and volume of changes I see in the commits. For example, if I know that the team only touched a few files and the changes are mostly cosmetic, there is no urgency to merge. For a subteam it may even make sense to leave the frequency of merges "undefined", within reason.

I think the team should define how frequently they integrate each way.  By my opinion (and my experience) is that doing the integration every 24 hours is best for a case like this.  We just need to make some simple modifications to the listed workflow commands to automate that smoothly (and avoid creating and pushing an explicit merge commit when there is nothing to new to push).

> We should also discuss dealing with broken CI builds despite the success of the pre-push testing that is part of the sync process. As we've seen, this can happen, and it did happen to ROL due to a nasty non-deterministic memory leak. But we have a pretty good handle on the process now.

We have not seen too much of this really.  But if it does happen, we just disable the problematic test in the main Trilinos GitHub 'develop' branch (for the standard CI build only, not other builds) and then that gets merged back to the ROL branch of Trilinos.  That way ROL developers will still enable and run the test locally in their own development to help protect it and can deal with occasional failures if they expect them.  It is just that we can't have these tests part of a massive automated testing process like with the checkin-test-sems.sh script (or with automated PR testing that will come from #1155).

> Finally, we need to think about how this will all work with the PR model.

So this is where, ironically, the new PR process will make it harder for people to use workflows like the subteam workflow for ROL that we put together and still automate pushes back to the main Trilinos GitHub 'develop' branch.  Currently, you just call `./checkin-test-sems.sh --do-all --push --no-rebase` and you are done.  With the new PR process, you will need to push your branch to the main Trilinos GitHub repo or our fork of Trilinos (and here I mean a true GitHub fork, not what we set up for the ROL Trilinos repo).  That part can be automated easily.  However, then, someone currently would need to manually create a new GitHub PR issue merging against the 'develop' branch.  However, the GitHub API does support automated creation of PRs and adding comments to PRs and Issues.  But you need a command-line tool like `hub` to accomplish this as described at:

* https://github.com/github/hub/issues/1219
* https://hub.github.com/

But that is a more complex dependency to install and SEMS would need to add `hub` to their env so that every Trilinos developer needing to automate these workflows could use them.

And if you don't like tools, there are raw bash scripts like:

* https://gist.github.com/devongovett/10399980

Therefore, I think we can automate the PR and testing and merge request so I am not worried about that.

Another issue to consider is what about code reviews?  With the subteam workflow, where and when would code reviews be conducted?  Going forward, it would be nice if we could advocate workflows that allow for and make code reviews easier to perform and then encourage developers to do code reviews.  With GitHub, the best way to conduct a code review is through a PR.  But if the PR is done in the private ROL Trilinos GitHub repo, is that go enough or do we need to be using this main Trilinos GitHub repo for these PRs for subteam development?  That is a more complex topic that we can put to the side for now or we can discuss this in a later comment.

**Comment by jmgate** [comment]
> But you need a command-line tool like hub to accomplish this&hellip;

I don't think you actually need `hub`.  I wrote a `bash` script a few weeks ago that uses the [GitHub Pull Request API](https://developer.github.com/v3/pulls/#create-a-pull-request) to automatically create a PR against Trilinos `develop` from a PR that had already been accepted and merged into a Trilinos fork&mdash;no `hub` needed.  The heart of the script is a simple API call:
```bash
curl -i -H 'Authorization: token <insertTokenHere>' \
  -d '{"title": "<insertTitleHere>", \
       "body":  "<insertBodyHere>",  \
       "head":  "<insertHeadHere>",  \
       "base":  "<insertBaseHere>"}' \
  https://api.github.com/repos/trilinos/Trilinos/pulls
```

**Comment by bartlettroscoe** [comment]
@jmgate,

> I don't think you actually need hub. I wrote a bash script a few weeks ago that uses the GitHub Pull Request API to automatically create a PR against Trilinos develop from a PR that had already been accepted and merged into a Trilinos fork—no hub needed. 

That sounds great.  I think that someone would need to commit some standard scripts for this in the Trilinos git repo so that people could use them to automate the integration of branches into Trilinos.

**Comment by jmgate** [comment]
Sounds good.  Should be easy enough to whip up.  Do we plan on discussing this at TUG, perhaps in a breakout session?

**Comment by bartlettroscoe** [comment]
> Do we plan on discussing this at TUG, perhaps in a breakout session?

I put in a suggested 30-60 minute session on this topic for developers day on Wednesday 10/25.  I think @jwillenbring has to organize the schedule.

**Comment by bartlettroscoe** [comment]
So it looks like I did present some slides on the ROL subteam workflow I helped them set up at the 2017 TUG Developer's day.  Unfortunately, I did not put those through R&A so I did not publish them I can can't point to them here.  I will document the subteam/subproject workflow as part of my "Design Patterns" short book I am working on and will complete this FY.

**Comment by bartlettroscoe** [comment]
Closing as complete.
