### ISSUE TITLE
Amesos2: TrilinosSS optional or required?

### ISSUE THREAD

**Issue by nschloe** [trilinos/Trilinos#1742]
In `packages/amesos2/cmake/Dependencies.cmake` one finds
```
SET(LIB_REQUIRED_DEP_PACKAGES Teuchos Tpetra TrilinosSS)
```
which suggests TrilinosSS is required to build Amesos2. However, in `packages/amesos2/src/CMakeLists.txt` one finds
```
IF (${PACKAGE_NAME}_ENABLE_TrilinosSS)
   # ...
ENDIF()
```
which suggests it's optional.

Which one is it?

(Btw, the conditional could perhaps rather be `${PROJECT_NAME}_ENABLE_TrilinosSS`.)

**Comment by aprokop** [comment]
@trilinos/amesos2

**Comment by srajama1** [comment]
It is required, the check is redundant.

**Comment by nschloe** [comment]
Thanks for the reply.

For the Debian package, I'll have to make a case for installing TrilinosSS. Can Amesos2 work with SuiteSparse (from upstream)? If not, what are the differences? If this has been written up somewhere, a link will do.
