### ISSUE TITLE
New Stokhos build failures in "clean" builds

### ISSUE THREAD

**Issue by etphipp** [trilinos/Trilinos#1744]
The dashboard is showing new stokhos build failures in the "clean" builds, e.g.,

https://testing.sandia.gov/cdash/viewBuildError.php?buildid=3109333

It looks to me it is due to this commit:

https://github.com/trilinos/Trilinos/commit/6b8439299be2e20a495b4467de05ac0d4ca7f293

The build failures occur in Stokhos' instantiations of Ifpack2 on its embedded UQ types, and appear to be arising from this code in Shylu:

```
template <typename T> inline T& conjugate (T& v) {
  v = T(v.real(), -v.imag());
  return v;
}
template <> inline double& conjugate (double& v) { return v; }
template <> inline float& conjugate (float& v) { return v; }
```

So this code will only work with float, double, and complex scalar types.  Why not just use Kokkos::Details::ArithTraits<T>::conj(), which already has all of the proper specializations?

CC:  @trilinos/shylu @ambrad

**Comment by ambrad** [comment]
Thanks @etphipp. I'll look into that. For now, to keep the builds that run ST code clean, I'll push a commit that moves HTS back to EX.

**Comment by ambrad** [comment]
Check-in script running.

**Comment by ambrad** [comment]
CDash looks clean after I fixed HTS for Stokhos and repromoted to ST.

**Comment by etphipp** [comment]
Awesome, thanks!

**Comment by ambrad** [comment]
Thanks for reporting!
