### ISSUE TITLE
Define labels and rules for Trilinos application issues and metrics

### ISSUE THREAD

**Issue by ibaned** [trilinos/Trilinos#1745]
Please see the discussion between https://github.com/trilinos/Trilinos/issues/1304#issuecomment-329885910 and https://github.com/trilinos/Trilinos/issues/1304#issuecomment-329918877 where I propose the following:

> create a few extra issues labels besides "bug", namely "compile error (Trilinos)", "compile error (application)", "compile warning (Trilinos)", "compile warning (application)", "test failure (Trilinos)", "test failure (application)". Then we can collect statistics on how many issues with each label were opened in a particular period of time. I would also expand "(Trilinos)" to be either "(Trilinos/develop)" or "(Trilinos/master)"

Note @bartlettroscoe 's observation:

> before we define any more labels I think we need to better organize them along the lines of #1619.

@maherou @jwillenbring

**Comment by ibaned** [comment]
I just realized we can reduce the combinatorial explosion by just having two categories of labels:
1. `compile warning`, `compile error`, `test failure`
2. `Trilinos develop`, `Trilinos master`, `application`

**Comment by bartlettroscoe** [comment]
We will need to categorize these them according to #1619. Perhaps something like:

* `app error type: compile warning`, `app error type: compile error`, `app error type: test failues`
* `error location: Trilinos develop`, `error location: Trilinos master`, `error location: application`

?

We just need a convention (i.e. '/' or ':' separators) and then apply it consistently.

**Comment by ibaned** [comment]
I would go with `error type` instead of `app error type`, since it doesn't necessarily have to be reported by an application, it could just be a user compiling Trilinos in a non-CI configuration.

**Comment by bartlettroscoe** [comment]
@jhux2,

Can we change package label prefix from `packages: MueLu` to `pkg: Muelu`?  Makes the label names shorter and (in my opinion) just as clear.  Make a difference when you have a lot of labels like in [ATDM Trilinos Issue queries](https://github.com/trilinos/Trilinos/labels/ATDM).
