### ISSUE TITLE
Set up Trilinos builds to test new all-at-once CMake/CTest/CDash feature

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#1746]
**Next Action Status:**

A single all-at-once build from ceerws1113 been going on for a few weeks.  Next: Set up dual submits to testing.sandia.gov/cdash and testing-vm.sandia.gov/cdash/ to help test new site with lots of data then set up a few more all-at-once builds going to different tracks ...

**CC:** @trilinos/framework 

**Description:**

This story is to track effort to set up new automated Trilinos builds to provide data to help test the new all-at-once configure, build, test, and submit feature in CMake/CTest and CDash.  For more details, see:

* https://gitlab.kitware.com/snl/project-1/issues/8
* https://gitlab.kitware.com/snl/project-1/issues/33

The detailed evaluation of this version of CMake/CTest and CDash will take place in https://gitlab.kitware.com/snl/project-1/issues/33.x

**Comment by bartlettroscoe** [comment]
I am already working on this.  I am setting up an all-at-once CI build that will submit to the new testing-vm.sandia.gov/CDash/ and the old testing.sandia.gov/cdash/ site.

**Comment by bartlettroscoe** [comment]
@jwillenbring,

In https://gitlab.kitware.com/snl/project-1/issues/33#note_318230 you commented that it was a good idea for the Trilinos framework team to set up a few all-at-once Experimental builds to post to the evaluation site testing-vm.sandia.gov/CDash/.  To see how to do that, just look at the new files I just posted to Trilinos/cmake/ctest/drivers/sems_ci/ that are now doing all-at-once builds submitting every day to the new and old sites.  See, for example:

* https://testing-vm.sandia.gov/CDash/index.php?project=Trilinos&filtercount=1&showfilters=1&field1=buildstamp&compare1=61&value1=20170918-0700-Experimental

* https://testing.sandia.gov/cdash/index.php?project=Trilinos&display=project&filtercount=1&showfilters=1&field1=buildstamp&compare1=61&value1=20170918-0700-Experimental

Both of these were submitted to from the **same exact CTest -S process**.

I am turning this over to you to assign to the right Trilinos Framework team member.

**Comment by bartlettroscoe** [comment]
FYI:

Note that one major disadvantage of moving from the package-by-package configure, build, test, and submit approach currently being used compared to the all-at-once approach that we are going to move to is that a configure failure in a single package in the packages-by-package appraoch will not bring down all builds and tests.  For example, two days ago, a configure failure in the ShyLU package broke in every "Clean" build and 4 of the 9 "Nightly" builds as shown at:

* https://testing.sandia.gov/cdash/index.php?project=Trilinos&date=2017-09-27

But since the current package-by-package approach was used, ShuLU (an ST package) got disabled in all downstream packages this still allowed most of Trilinos to still get tested (i.e. all of the PT packages and code downstream from ShyLU and all of the ST packages and code upstream of ShyLU still got testing).  For the all-at-once approach, it would just skip the build and running tests for **every** Trilinos package!

So what moving to the all-at-once approach means is that we (i.e. the Trilinos Framework team and the Trilinos developers) are going to need to be much more diligent about detecting problems like this early and then addressing them ASAP.  For example, this might necessitate setting up a second post-push ST build of Trilinos posting to CDash to help catch problems like this during the day before going into nighty testing.  That way, the current standard post-push PT CI build protects PT code and packages and allows other developers to push, but other post-push ST CI build would help catch catastrophic problems that could otherwise blow up nightly testing.

**Comment by bartlettroscoe** [comment]
Now that it seems that testing-vm.sandia.gov/cdash/ is accessible from outside SNL web and we can submit to it from inside the SRN without having to set http_proxy="" (see https://gitlab.kitware.com/snl/project-1/issues/39#note_327897), it occurred to me that we should set up Trilinos/CTestConfig.cmake to do a dual submit to testing.sandia.gov/cdash/ and testing-vm.sandia.gov/cdash/ with the existing package-by-package approach, in addition to the all-at-once submits that I am doing (and need to set up more to give me more confidence).  This will involve an extra set of curl copies of the XML files to the seconds CDash site as well so it should not slow down the ctest clients much, if at all.  And all of the same data will still be going to the old Trilinos CDash site.  But there may be an issue with external machines submitting to testing-vm.sandia.gov (see https://gitlab.kitware.com/snl/project-1/issues/39#note_327905) but I don't know if that is a big problem since the majority of Trilinos testing is running on SNL machines in the SNL network.

Anyone on the @trilinos/framework list see a problem with changing Triilnos/CTestConfig.cmake to do a dual submit?  Please let me know today if anyone sees a problem with this.

Just checking before I flip the switch and set up Trilinos/CTestConfig.cmake to start doing dual submits ...

**Comment by bartlettroscoe** [comment]
Okay, given there has been no pushback from anyone, I will go ahead and set up Trilinos builds to do dual submits to testing.sandia.gov/cdash/ and testing-vm.sandia.gov/cdash/.

**Comment by jwillenbring** [comment]
@bartlettroscoe I think it is a good idea to set up the dual submits.

**Comment by bartlettroscoe** [comment]
Okay, I just pushed the commit 0c7793cf10718d9fc379501613fbbc4c3ff0ffc4:

```
commit 0c7793cf10718d9fc379501613fbbc4c3ff0ffc4
Author: Roscoe A. Bartlett <rabartl@sandia.gov>
Date:   Tue Oct 10 14:23:47 2017 -0600

    Set up dual submits to also submit to testing-vm.sandia.gov/cdash/ (#1746)
    
    This will help to get data up on testing-vm.sandia.gov/cdash/ so we can
    evaluate if CDash is working as it should and it will also see if we have
    submit problems to testing-vm.sandia.gov/cdash/.
    
    Build/Test Cases Summary
    Enabled Packages: Teuchos
    Disabled Packages: PyTrilinos,Claps,TriKota
    0) MPI_RELEASE_DEBUG_SHARED_PT => passed: passed=128,notpassed=0 (2.70 min)

diff --git a/CTestConfig.cmake b/CTestConfig.cmake
index 5aead48..f07dc99 100644
--- a/CTestConfig.cmake
+++ b/CTestConfig.cmake
@@ -15,4 +15,9 @@ IF (CTEST_DROP_METHOD STREQUAL "http" OR CTEST_DROP_METHOD STREQUAL "https")
   SET_DEFAULT_AND_FROM_ENV(CTEST_DROP_LOCATION "/cdash/submit.php?project=Trilinos")
   SET_DEFAULT_AND_FROM_ENV(CTEST_TRIGGER_SITE "")
   SET_DEFAULT_AND_FROM_ENV(CTEST_DROP_SITE_CDASH TRUE)
+  # Temp secondary submit to experimental CDash site (see #1746)
+  SET_DEFAULT_AND_FROM_ENV(TRIBITS_2ND_CTEST_DROP_SITE
+    "testing-vm.sandia.gov")
+  SET_DEFAULT_AND_FROM_ENV(TRIBITS_2ND_CTEST_DROP_LOCATION
+    "/CDash/submit.php?project=Trilinos")
 ENDIF()
```

I tested this out locally on my machine first using:

```
$ cd ~/Trilinos.base/BUILDS/GCC-4.8.4/
$ rm -r CMake*
$ ./do-configure -DTrilinos_ENABLE_Teuchos=ON &> configure.out
$ time make dashboard &> make.dashboard.out
```

That submitted to:

* https://testing.sandia.gov/cdash/index.php?project=Trilinos&display=project&filtercount=1&showfilters=1&field1=buildstamp&compare1=61&value1=20171010-2224-Experimental

and

* https://testing-vm.sandia.gov/cdash/index.php?project=Trilinos&date=2017-10-10&filtercount=1&showfilters=1&field1=buildstamp&compare1=61&value1=20171010-2224-Experimental

Tomorrow, we should hopefully see all of the Trilinos builds from the 'develop' branch also showing up on testing-vm.sandia.gov/ ...

Now I will see about getting some more all-at-once builds submitting nightly to testing-vm.sandia.gov.  Once that is done and has been running for a few days, I will feel good about doing a manual inspection of the site.

We will also see if any sites have trouble submitting to testing-vm.sandia.gov.  That will be very educational.

**Comment by bartlettroscoe** [comment]
The builds are now being mirrored on testing-vm.sandia.gov as shown by:

* https://testing-vm.sandia.gov/CDash/index.php?project=Trilinos&date=2017-10-11

However, this resulted in a bunch of emails getting sent out for failed builds that looked like:

```
> From: CDash [mailto:admin@cdash.org]
> Sent: Wednesday, October 11, 2017 1:52 AM
> To: Bartlett, Roscoe A <rabartl@sandia.gov>
> Subject: [EXTERNAL] FAILED (b=2): Trilinos - Linux-gcc-4.8.4-
> MPI_Release_gcc_4.8.4_openmpi_1.8.7_DEV - Clean
> 
> A submission to CDash for the project Trilinos has build errors.
> You have been identified as one of the authors who have checked in changes
> that are part of this submission or you are listed in the default contact list.
> 
> Details on the submission can be found at
> https://localhost/CDash/buildSummary.php?buildid=3109033
> 
> Project: Trilinos
> Site: ascic115
> Build Name: Linux-gcc-4.8.4-MPI_Release_gcc_4.8.4_openmpi_1.8.7_DEV
> Build Time: 2017-10-11T04:56:06 UTC
> Type: Clean
> Errors: 2
> 
> 
> *Error*
> 
> 
> -CDash on localhost
```

I turned off the emails in the project settings for the "Trilinos" project so we should not be getting emails on this (at least for now).  I asked Kitware see if they can fix the "localhost" URL shown in the above email to be "testing-vm.sandia.gov" like it should be.

**Comment by jwillenbring** [comment]
@bartlettroscoe 

Are you OK with closing this ticket?

**Comment by bartlettroscoe** [comment]
> Are you OK with closing this ticket?

@jwillenbring, yes.  As part of #1761, I switched every Trilinos build that uses the TRIBITS_CTEST_DRIVER() to use do an all-at-once configure, build, test, and submit by default.

Closing as complete.
