### ISSUE TITLE
ShyLU: Fishy-looking HTS build warning (Clang 3.9)

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#1748]
@trilinos/shylu @ambrad 

This build warning in HTS in ShyLU looks fishy:
```
.../Trilinos/packages/shylu/hts/src/shylu_hts_impl_def.hpp:384:15: warning: destination for this 'memcpy' call is a pointer to dynamic class 'OnDiagTri'; vtable pointer will be overwritten
```
Is it an actual bug or just a spurious warning?

**Comment by ambrad** [comment]
Hrmmm, that's interesting! I'll take a look.

**Comment by ambrad** [comment]
@mhoemmen, is this on the cdash? Or could you send some more warning output? Also, what compiler? Thanks.

**Comment by ambrad** [comment]
Oh, 3.9, in the title. Cool.

**Comment by ambrad** [comment]
Reproduced. I'm going to clean up all the clang warnings. Thanks @mhoemmen!
