### ISSUE TITLE
Amesos2 tests FTBFS with MUMPS

### ISSUE THREAD

**Issue by bavier** [trilinos/Trilinos#175]
With the following configure script at commit f95a33e826e1f13f080cba89676daf5772dcdc16
```
cmake \
  -DCMAKE_CXX_COMPILER=mpic++ \
  -DCMAKE_C_COMPILER=mpicc \
  -DCMAKE_Fortran_COMPILER=mpifort \
  -DBUILD_SHARED_LIBS:BOOL=YES \
  -DTrilinos_ENABLE_Amesos2:BOOL=YES \
  -DTPL_ENABLE_MUMPS:BOOL=YES \
  -DMUMPS_LIBRARY_NAMES='dmumps;mumps_common;scalapack;lapack;ptscotch;scotch;scotcherr;metis;ptesmumps;esmumps;pord' \
  -DTPL_ENABLE_MPI:BOOL=YES \
  -DAmesos2_ENABLE_MUMPS:BOOL=YES \
  -DAmesos2_ENABLE_TESTS:BOOL=YES \
  ..
```
I get the following failure when building amesos2/test/solvers/Solver_Test.cpp:
```
In file included from /ptmp/Trilinos/packages/amesos2/src/Amesos2_MUMPS.hpp:49:0,
                 from /ptmp/Trilinos/packages/amesos2/src/Amesos2_Factory.hpp:120,
                 from /ptmp/Trilinos/packages/amesos2/src/Amesos2.hpp:45,
                 from /ptmp/Trilinos/packages/amesos2/test/solvers/Solver_Test.cpp:72:
/ptmp/Trilinos/packages/amesos2/src/Amesos2_MUMPS_def.hpp: In instantiation of 'int Amesos2::MUMPS< <template-parameter-1-1>, <template-parameter-1-2> >::ConvertToTriplet() [with Matrix = Tpetra::CrsMatrix<std::complex<double>, long long int, long long int, Kokkos::
Compat::KokkosDeviceWrapperNode<Kokkos::Serial>, false>; Vector = Tpetra::MultiVector<std::complex<double>, long long int, long long int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial>, false>]':
/ptmp/Trilinos/packages/amesos2/src/Amesos2_MUMPS_def.hpp:404:27:   required from 'bool Amesos2::MUMPS< <template-parameter-1-1>, <template-parameter-1-2> >::loadA_impl(Amesos2::EPhase) [with Matrix = Tpetra::CrsMatrix<std::complex<double>, long long int, long long
int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial>, false>; Vector = Tpetra::MultiVector<std::complex<double>, long long int, long long int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial>, false>]'
/ptmp/Trilinos/packages/amesos2/src/Amesos2_SolverCore_def.hpp:512:18:   required from 'void Amesos2::SolverCore<ConcreteSolver, Matrix, Vector>::loadA(Amesos2::EPhase) [with ConcreteSolver = Amesos2::MUMPS; Matrix = Tpetra::CrsMatrix<std::complex<double>, long long
 int, long long int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial>, false>; Vector = Tpetra::MultiVector<std::complex<double>, long long int, long long int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial>, false>]'
/ptmp/Trilinos/packages/amesos2/src/Amesos2_SolverCore_def.hpp:105:8:   required from 'Amesos2::Solver<Matrix, Vector>& Amesos2::SolverCore<ConcreteSolver, Matrix, Vector>::preOrdering() [with ConcreteSolver = Amesos2::MUMPS; Matrix = Tpetra::CrsMatrix<std::complex<
double>, long long int, long long int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial>, false>; Vector = Tpetra::MultiVector<std::complex<double>, long long int, long long int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial>, false>]'
/ptmp/Trilinos/packages/amesos2/test/solvers/Solver_Test.cpp:1610:1:   required from here
/ptmp/Trilinos/packages/amesos2/src/Amesos2_MUMPS_def.hpp:420:19: error: cannot convert 'Amesos2::MUMPS<Tpetra::CrsMatrix<std::complex<double>, long long int, long long int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial>, false>, Tpetra::MultiVector<std::co
mplex<double>, long long int, long long int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial>, false> >::local_ordinal_type* {aka long long int*}' to 'int*' in assignment
     mumps_par.irn = (local_ordinal_type*)malloc(mumps_par.nz *sizeof(local_ordinal_type));
                   ^
/ptmp/Trilinos/packages/amesos2/src/Amesos2_MUMPS_def.hpp:421:19: error: cannot convert 'Amesos2::MUMPS<Tpetra::CrsMatrix<std::complex<double>, long long int, long long int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial>, false>, Tpetra::MultiVector<std::co
mplex<double>, long long int, long long int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial>, false> >::local_ordinal_type* {aka long long int*}' to 'int*' in assignment
     mumps_par.jcn = (local_ordinal_type*)malloc(mumps_par.nz * sizeof(local_ordinal_type));
                   ^
```

**Comment by bavier** [comment]
BTW:
```
$ gcc --version
gcc (GCC) 5.3.0
```
But I've seen the same with `gcc 4.9.0`

**Comment by jdbooth** [comment]
Hi.
I am guessing you are not building MUMPS with INT_64 and using Tpetra with long long type.
However, how mumps is built only allows you to use INT_64 or not.  Right now, it is assumed to not use INT_64 because no one wanted support for it and would have to add checking into the TPL in Tribits.

There are several ways to fix this, and I am open to any of these:

1. Assert at build that you only build with Tperta ETI matching MUMPS (Disabling Epetra if not matching)
2. Check at run time and throw an error if you try to use a Matrix of wrong type.

Let me know and I will fix and push.
Sorry for the error.

Joshua Booth

**Comment by bavier** [comment]
I think option 1 would be preferable; better to catch errors earlier.

I occurs to me that not as much attention was paid to index type compatibility in Amesos2.  Other solvers "work" because they do casting while copying from the input index type to the expected/supported index type.  The same could be done for the MUMPS interface, e.g. using `MUMPS_INT` instead of `local_ordinal_type`.

**Comment by jdbooth** [comment]
Great.  I will do the first. I will push a patch this weekend.

I considered using MUMPS_INT.  However, just like your case, casting from long long to say int (MUMPS_INT) may result in a slight error even using Teuchos::as not in debug mode.  I would rather the compiler yell at me than have MUMPS yell or give me the wrong answer. 
The other option to for Amesos2 to check index bounds than cast if max index < index of the supportive type. However, this is a big question of why someone would use such a large ordinal type when they don't need it.

**Comment by jdbooth** [comment]
BTW, 

What ETI options are you compiling with so I can check the patch?

**Comment by bavier** [comment]
Just the default ETI options (LO: int, GO: int|long long, Scalar: int|long long|double).

With casting, do you mean range errors? or are there other concerns with Teuchos::as?

An organization that chooses to distribute a pre-built Trilinos library for users might opt to compile against an INT_64 mumps library in order to cover a greater number of users needs, if the support machinery were in place.  Of course, they might also choose to offer multiple configurations, built with differing ETI support.  But when possible, limiting the number of necessary configurations seems worthwhile to me.  I'm guessing the Trilinos devs have discussed such things; pardon me if I'm not up-to-date on the discussion.

**Comment by jdbooth** [comment]
Thanks for the info.  However, that does not match the above error.  The error above is using local ordinal type of long long which is not default ETI and one of the reason I am still going to push a fix since you make a valid point that we should take care of it.
Yes,  I was talking about a range error from casting from long long to int.

**Comment by mhoemmen** [comment]
Given all the drama we've had with build configurations, I would actually prefer a fully run-time approach.  If the input matrix doesn't have the right data type(s), Amesos2 could attempt to convert to the solver's support data types, and throw an exception with a helpful error message if that doesn't work.

**Comment by jdbooth** [comment]
Hello.
I pushed a fix:commit ec0d347f0d66fd50faaf328078fa7964adbcedf6
It will try to convert.  If it cannot due to ordinal type overflow, it will throw a run time exception.
Hope this helps, and I will close up the issue.

**Comment by mhoemmen** [comment]
The check looks OK to me. Thanks @jdbooth !

**Comment by bavier** [comment]
> Thanks for the info. However, that does not match the above error. The error above is using local ordinal type of long long which is not default ETI

Perhaps, but I have reported the situation as I know it.  I'm assuming there is a further issue with ETI macros in amesos2/test/solvers/Solver_Test.cpp.
