### ISSUE TITLE
Code gets stuck within Tpetra's doImport

### ISSUE THREAD

**Issue by searhein** [trilinos/Trilinos#1752]
I am implementing a new subpackage for ShyLU, which I have not yet pushed to the repository. Since last week, after pulling from the develop branch of the repository, my code gets stuck within the doImport() method of a Tpetra::CrsMatrix, which I call through Xpetra. 
The code does not crash, it just gets completely stuck within the import.

I am able to narrow down the corresponding commit, which results in this issue, between ce22a7edf97af24ca744897374e6d2c5106e7471 and
80110046ffaf6b583bfeab39007b42791d490bb9 since the exactly same code runs perfectly on commit 80110046ffaf6b583bfeab39007b42791d490bb9 and gets stuck on commit ce22a7edf97af24ca744897374e6d2c5106e7471.

**Comment by aprokop** [comment]
@trilinos/tpetra @trilinos/shylu @trilinos/xpetra

**Comment by mhoemmen** [comment]
@searhein Could you please specify your build options?  Commit https://github.com/trilinos/Trilinos/commit/80110046ffaf6b583bfeab39007b42791d490bb9 mainly relates to CUDA builds, though it does have effects for non-CUDA builds.  It's possible that in a CUDA build, the changes make users' incorrect use of UVM without intervening fences more likely to cause issues.

**Comment by mhoemmen** [comment]
@searhein Also, I would be happy to test out your code if you wouldn't mind sharing it.

**Comment by searhein** [comment]
@mhoemmen My configuration for Trilinos is
```
cmake \
    -D CMAKE_BUILD_TYPE:STRING=RELEASE \
    -D CMAKE_INSTALL_PREFIX:STRING="$INSTALL_DIR" \
    -D CMAKE_C_FLAGS:STRING="-DH5_HAVE_PARALLEL" \
    -D CMAKE_CXX_FLAGS:STRING="-DH5_HAVE_PARALLEL" \
    -D PYTHON_EXECUTABLE:STRING="/usr/bin/python" \
    -D CMAKE_VERBOSE_MAKEFILE:BOOL=OFF \
    -D Trilinos_ASSERT_MISSING_PACKAGES:BOOL=ON \
    -D Trilinos_ENABLE_Fortran:BOOL=ON \
    -D Trilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON \
    -D Trilinos_ENABLE_Anasazi:BOOL=OFF \
    -D Trilinos_ENABLE_Amesos:BOOL=ON \
    -D Trilinos_ENABLE_Amesos2:BOOL=ON \
    -D Trilinos_ENABLE_AztecOO:BOOL=OFF \
    -D Trilinos_ENABLE_Belos:BOOL=ON \
    -D Trilinos_ENABLE_Epetra:BOOL=ON \
    -D Trilinos_ENABLE_EpetraExt:BOOL=ON \
    -D Trilinos_ENABLE_Galeri:BOOL=ON \
    -D Trilinos_ENABLE_Ifpack:BOOL=ON \
    -D Trilinos_ENABLE_Ifpack2:BOOL=OFF \
    -D Trilinos_ENABLE_Isorropia:BOOL=OFF \
    -D Trilinos_ENABLE_ML:BOOL=ON \
    -D Trilinos_ENABLE_MueLu:BOOL=ON \
    -D Trilinos_ENABLE_Pamgen:BOOL=OFF \
    -D Trilinos_ENABLE_Sacado:BOOL=OFF \
    -D Trilinos_ENABLE_Shards:BOOL=OFF \
    -D Trilinos_ENABLE_ShyLU:BOOL=ON \
    -D Trilinos_ENABLE_ShyLU_DDOS:BOOL=ON \
    -D Trilinos_ENABLE_ShyLU_DDOSXpetra:BOOL=ON \
    -D Trilinos_ENABLE_ShyLU_DDFROSch:BOOL=ON \
    -D ShyLU_DD_ENABLE_TESTS:BOOL=ON \
    -D Trilinos_ENABLE_Stratimikos:BOOL=OFF \
    -D Trilinos_ENABLE_Teuchos:BOOL=ON \
    -D Trilinos_ENABLE_Teko:BOOL=OFF \
    -D Trilinos_ENABLE_Thyra:BOOL=OFF \
    -D Trilinos_ENABLE_Tpetra:BOOL=ON \
    -D Trilinos_ENABLE_Xpetra:BOOL=ON \
    -D Trilinos_ENABLE_Zoltan:BOOL=ON \
    -D Trilinos_ENABLE_Zoltan2:BOOL=ON \
    -D TPL_ENABLE_MPI:BOOL=ON \
    -D ML_ENABLE_METIS:BOOL=ON \
    -D ML_ENABLE_ParMETIS:BOOL=ON \
    -D ML_ENABLE_TESTS:BOOL=ON \
    -D TPL_ENABLE_METIS:BOOL=ON \
    -D METIS_LIBRARY_DIRS:PATH=$PARMETIS/lib \
    -D METIS_INCLUDE_DIRS:PATH=$PARMETIS/include \
    -D TPL_ENABLE_ParMETIS:BOOL=ON \
    -D ParMETIS_LIBRARY_DIRS:PATH=$PARMETIS/lib  \
    -D ParMETIS_INCLUDE_DIRS:PATH=$PARMETIS/include \
    -D TPL_ENABLE_BLAS:BOOL=ON \
    -D TPL_BLAS_LIBRARIES:STRING='-framework Accelerate' \
    -D TPL_ENABLE_LAPACK:BOOL=ON \
    -D TPL_LAPACK_LIBRARIES:STRING='-framework Accelerate' \
    -D TPL_ENABLE_UMFPACK:BOOL=ON \
    -D TPL_UMFPACK_LIBRARIES:STRING="$UMFPACK/lib/libumfpack.a;$UMFPACK/lib/libamd.a;" \
    -D UMFPACK_INCLUDE_DIRS:PATH=$UMFPACK/include/ \
    -D TPL_ENABLE_Boost:BOOL=ON \
    -D TPL_Boost_INCLUDE_DIRS:PATH=$BOOST/include \
    -D EpetraExt_USING_HDF5:BOOL=ON \
    -D TPL_ENABLE_HDF5:BOOL=ON \
    -D HDF5_LIBRARY_DIRS:PATH=$HDF5/lib \
    -D HDF5_INCLUDE_DIRS:PATH=$HDF5/include \
    -D TPL_ENABLE_MUMPS:BOOL=ON \
    -D Amesos_ENABLE_MUMPS:BOOL=ON \
    -D Amesos2_ENABLE_MUMPS:BOOL=OFF \
    -D HAVE_AMESOS_MPI_C2F:BOOL=ON \
    -D MUMPS_INCLUDE_DIRS:FILEPATH="$MUMPS/include" \
    -D MUMPS_LIBRARY_DIRS:FILEPATH="$MUMPS/lib" \
    -D MUMPS_LIBRARY_NAMES:STRING="dmumps;pord" \
    -D Amesos_ENABLE_SCALAPACK:BOOL=ON \
    -D SCALAPACK_INCLUDE_DIRS:FILEPATH="$SCALAPACK/SRC" \
    -D SCALAPACK_LIBRARY_DIRS:FILEPATH="$SCALAPACK" \
    -D SCALAPACK_LIBRARY_NAMES:STRING="scalapack" \
    -D Amesos_ENABLE_BLACS:BOOL=ON \
    -D BLACS_INCLUDE_DIRS:FILEPATH="$BLACS/SRC/MPI" \
    -D BLACS_LIBRARY_DIRS:FILEPATH="$BLACS/LIB" \
    -D BLACS_LIBRARY_NAMES:STRING="blacsCinit_MPI-MACOS-0.a;blacsF77init_MPI-MACOS-0.a;blacs_MPI-MACOS-0.a" \
    -D Trilinos_EXTRA_LINK_FLAGS:STRING="/opt/local/lib/mpich-gcc48/libmpifort.a" \
    $BASE_DIR
```

I am compiling on my Macbook.

On commit 80110046ffaf6b583bfeab39007b42791d490bb9, my code still runs through perfectly. For commit ce22a7edf97af24ca744897374e6d2c5106e7471, it doesn't work anymore.

Hopefully, I can push my code to the repository today, and you will find it in the sub package ShyLU/FROSch. However, I will disable the Tpetra test in which the issue occurs.

**Comment by mhoemmen** [comment]
@searhein I can't speak for the ShyLU management, but I would be much happier if you were to submit your code in the form of a pull request, rather than just pushing it.  I would be happy to try it out, and would be even happier if we could fix the issue (mine, yours, or both) before the code actually gets added to the repo.

Just curious -- have you tried this on other platforms, and do you encounter the same issue there?

**Comment by srajama1** [comment]
This is a new experimental package that is being added. It works fine with Epetra which will be enabled by default. The Tpetra portion is hanging, but needs to be disbaled. A PR is good, but not absolutely needed.

**Comment by srajama1** [comment]
Thinking one more time, a PR will be better, as you are not only changing ShyLU but also Ifpack2, Amesos2 dependencies.

**Comment by mhoemmen** [comment]
@searhein It's totally up to you and the ShyLU team how the code shows up, but I would be happy to review it :-) .

**Comment by ndellingwood** [comment]
If submitted as a PR @mhoemmen can pull the PR to test if he wants to try it out before a commit (he mentioned interest in testing in earlier message); here's the git commands for reference for anyone that hasn't used them but may find them useful:

For example, say @searhein submits the commit as PR #xyz 
```
git fetch origin pull/xyz/head:pr-xyz
git checkout pr-xyz
```
This assumes `origin` is a remote for the Trilinos repo that the PR was submitted to, not the user's fork, and a local branch is created from the PR called pr-xyz.

**Comment by searhein** [comment]
Ok, I will do a PR then.

**Comment by searhein** [comment]
I have just submitted my pull request #1759. Unfortunately, it is rather large.

**Comment by mhoemmen** [comment]
@searhein It would be helpful if you could summarize for me what files relate to Tpetra.  Thanks!

**Comment by searhein** [comment]
@mhoemmen In fact, Tpetra is used through Xpetra almost in the whole code. However, running
the test in
`/packages/shylu/shylu_dd/frosch/test/TestLaplacian_Tpetra`
e.g., with 
`mpirun -n 8 ./ShyLU_DDFROSch_frosch_laplacian_tpetra.exe`,
the code gets stuck in line 90 of the file
`packages/shylu/shylu_dd/frosch/src/Tools/FROSch_Tools_def.hpp`, i.e., performing
`matrix->doImport(*tmpMatrix,*gather,Xpetra::ADD);`.

Thanks for working on fixing that issue.

**Comment by srajama1** [comment]
FYI : This change is going in ShyLU this week with Tpetra options disabled. That said it would be a lot of help to resolve this issue soon as we are planning application integration within the next few weeks.

**Comment by kddevin** [comment]
@mhoemmen @tjfulle do either of you have time this week to look into this issue with @searhein?
@searhein would it be possible for you to create a stripped down test that does your import (e.g., with the same  maps, matrices, etc.) without all the rest of the ShyLU details?

**Comment by mhoemmen** [comment]
@kddevin If @searhein has time to work on a stripped-down test, I'll be happy to help.  It would also be nice to see the results of running in a debug build with the CMake options `Teuchos_ENABLE_DEBUG:BOOL=ON` and `Kokkos_ENABLE_DEBUG:BOOL=ON` both set.

**Comment by tjfulle** [comment]
@kddevin, I can help too.

**Comment by searhein** [comment]
@kddevin @mhoemmen @tjfulle I just pushed another test 
`packages/shylu/shylu_dd/frosch/test/TestImport_Tpetra`
to my PR which also gets stuck with this issue. Does this help?

**Comment by mhoemmen** [comment]
@searhein Yes, thank you.  Please be a bit patient as we are a bit overwhelmed these days.

**Comment by mhoemmen** [comment]
@searhein I'm looking at the test you added:

https://github.com/searhein/Trilinos/blob/25728b63a8e1ef8237ac6df37e19da45984f61a0/packages/shylu/shylu_dd/frosch/test/TestImport_Tpetra/main.cpp

and noticed the following issues:

1. The test mixes Epetra and Tpetra objects, and uses them through Xpetra.  I'm not sure if we could characterize this solely as a "Tpetra issue."  Does Xpetra test simultaneous use of Epetra and Tpetra?  Furthermore, Galeri has an Xpetra interface, so you should not need to copy from Epetra to Xpetra objects.  The MueLu developers have examples that use Galeri to create Xpetra objects directly.  

2. I'm looking at line 127: 
```
 K = Xpetra::MatrixFactory<SC,LO,GO,NO>::Build(overlappingMap,2*tmpMatrix->getGlobalMaxNumRowEntries());
```
The overlapping Map comes from the following function call on line 124:
```
FROSch::ExtendOverlapByOneLayer<SC,LO,GO,NO>(K,overlappingMap);
```
From the name of this function, it looks like this computes the Map for the algebraic equivalent of single level of mesh overlap.  In that case, where does the constant `2*tmpMatrix->getGlobalMaxNumRowEntries()` come from?  That argument of Build is supposed to be an upper bound on the number of entries stored in a row on any one process.  See the `Xpetra::MatrixFactory` header file here:
  
https://github.com/trilinos/Trilinos/blob/f0350316239aaf41e8e6b82378612aaedf9cc72c/packages/xpetra/sup/Matrix/Xpetra_MatrixFactory.hpp

It's a sparse matrix, right?  Suppose that the matrix is N x N, and you have P processes.  That constant is 2*N.  You've just asked Xpetra to create a matrix that has 2*N*N/P space on _each_ _process_.  The reason this might not cause trouble until the Export operation, is that `Tpetra::CrsMatrix` currently allocates lazily.  It doesn't actually allocate until you insert entries.  Insertion in this case happens at the Export.

Could you please try this again, but use zero (0) as the second argument of `MatrixFactory::Build`?

**Comment by mhoemmen** [comment]
@searhein Another interesting part of the test you wrote, is that you construct an Export and use it in reverse mode, in doImport.  Xpetra folks, that should be OK, right?  @trilinos/xpetra

**Comment by mhoemmen** [comment]
@searhein Could you please point me to the implementation of `FROSch::ExtendOverlapByOneLayer`?  I'm hoping that this does what, say, Ifpack2 or Ifpack do when they implement overlap for additive Schwarz.

**Comment by srajama1** [comment]
If this would be hard to track down the root cause, is rolling back the commit that caused the issue an option ? @searhein has given a commit that works and another where it doesn't.

**Comment by mhoemmen** [comment]
It would be nice to see the implementation of `ExtendOverlapByOneLayer`.  The Tpetra commits in question pass all tests with the check-in test script, all the way downstream.  This includes Ifpack2 tests, that should exercise overlapping additive Schwarz.

**Comment by searhein** [comment]
@mhoemmen Let me comment first comment the two issues you mentioned:

1. Since I am more familiar with Epetra and since I wanted to obtain exactly the same results as in the Epetra test, I used the Epetra maps and matrices from Galeri and converted them to Tpetra in the test. However, afterwards I solely use Tpetra objects.
2. You are right, `FROSch::ExtendOverlapByOneLayer` computes the Map for the algebraic equivalent of single level of mesh overlap. Therefore, it should be more or less the same which is also done in Ifpack or Ifpack2. I am sorry, but I don't understand your point with respect to the second argument of `MatrixFactory::Build`. Let me first say that, using 0 as the second argument, did not resolve the issue. Also, `2*tmpMatrix->getGlobalMaxNumRowEntries()` should clearly an upper bound for the number of nonzeros per row in the matrix. The matrix is sparse and it is basically the discretisation of a finite difference scheme. In the documentation `https://trilinos.org/docs/dev/packages/xpetra/doc/html/classXpetra_1_1CrsMatrix.html`, I found that `getGlobalMaxNumRowEntries()`
> Returns the maximum number of entries across all rows/columns on all nodes.

The function call should therefore return something like 7. For the special case in this example even `tmpMatrix->getGlobalMaxNumRowEntries()` should be a sufficient `maxNumEntriesPerRow`.

The implementation of `ExtendOverlapByOneLayer` can be found in the file
`packages/shylu/shylu_dd/frosch/src/Tools/FROSch_Tools_def.hpp`.

**Comment by mhoemmen** [comment]
Hi @searhein !  I took a look at the implementation of `ExtendOverlapByOneLayer`, in the file you mentioned.  I noticed that line 271 appears to have a bug:

https://github.com/searhein/Trilinos/blob/25728b63a8e1ef8237ac6df37e19da45984f61a0/packages/shylu/shylu_dd/frosch/src/Tools/FROSch_Tools_def.hpp#L271

This line calls fillComplete with no arguments, on the overlapping matrix.  This is incorrect.  In both Epetra and Tpetra, if the row Map is not the same as the domain and range Maps, then you must pass the domain and range Maps as arguments to FillComplete resp. fillComplete.  Otherwise, the matrix will use the row Map as the domain and range Maps.  This is wrong, because the domain and range Maps must always be one to one.

Besides this correctness issue, the function for computing the overlapping matrix could be a lot simpler.  You do not actually need to read the graph or matrix entries, as long as the graph or matrix has a column Map and Import object.  For a Tpetra example using a CrsGraph, please refer to `Trilinos/packages/ifpack2/src/Ifpack2_CreateOverlapGraph.hpp`.  There is a somewhat less elegant efficient CrsMatrix example in the constructor of `Ifpack2::OverlappingRowMatrix`, in `Trilinos/packages/ifpack2/src/Ifpack2_OverlappingRowMatrix_def.hpp` (search for "The big import loop").  Epetra has comparable examples in the Ifpack package.  For an `Epetra_CrsGraph` example, see `Trilinos/packages/ifpack/src/Ifpack_OverlapGraph.cpp`.

There are other inefficiencies in this file as well.  For example, BuildUniqueMap should just use CreateOneToOne with Epetra, and createOneToOne with Tpetra.  If Xpetra lacks an interface to these functions, then it would make sense to write one, rather than trying to work around it.  Your approach in this function will have memory efficiency problems if the input `map` is sparse, that is, if it has many fewer indices than the `linearMap`.  Also, `linearMap` needs to have the same index base as `map`.

I wish I had more free time to help you out here.  We really do appreciate contributions like this.  I don't mean to put you down; I really just want to make sure that both your code and my code are doing the right thing :-) .

**Comment by mhoemmen** [comment]
@searhein I'll close this issue for now, but please could you reopen it if you fix the code and find that it still hangs?  Thanks!

**Comment by searhein** [comment]
@mhoemmen Thank you a lot for looking into that issue and for your suggestions on optimizing my code. I just took a look at `packages/ifpack2/src/Ifpack2_CreateOverlapGraph.hpp`, and I agree that it would be a good idea to use this approach instead of mine.

With respect to my function `BuildUniqueMap`, I would also like to implement your suggestion. Unfortunately, I could only find `createOneToOne` for Tpetra but not `CreateOneToOne` for Epetra. Could you please refer me to where it can be found in Trilinos?

I just changed
`overlappingMatrix->fillComplete();`
to
`overlappingMatrix->fillComplete(tmpMatrix->getDomainMap(),tmpMatrix->getRangeMap());`
(cf. a7c644db1ee8ad96d7eb02dabff42505ce9cb08d)
which should fix the bug you mentioned. However, unfortunately this does not change the behavior of the code at all. The Epetra code still goes through the Import and the Tpetra version still hangs.

**Comment by mhoemmen** [comment]
@searhein wrote:
> Unfortunately, I could only find createOneToOne for Tpetra but not CreateOneToOne for Epetra. Could you please refer me to where it can be found in Trilinos?

In Epetra it's called `IsOneToOne`.  It's a method on `Epetra_BlockMap`, inherited by `Epetra_Map`.
```
$ cd Trilinos/packages/epetra/src
$ grep -R "OneToOne"
Epetra_BlockMap.cpp:1070:bool Epetra_BlockMap::IsOneToOne() const {
...
```

> The Epetra code still goes through the Import and the Tpetra version still hangs.

Have you tried a debug build?  That may give you better diagnostics.  Set the following CMake options:
```
-D CMAKE_BUILD_TYPE:STRING=DEBUG
-D Kokkos_ENABLE_DEBUG:BOOL=ON
-D Teuchos_ENABLE_DEBUG:BOOL=ON
```
If you have pulled Trilinos very recently, you could also try setting the `TPETRA_VERBOSE` environment variable to "1" or "TRUE".

**Comment by searhein** [comment]
@mhoemmen I compiled Trilinos with all the options you told me. 
Unfortunately, when the code gets stuck within the Import, I don't get any output. What do you suggest to do?

**Comment by mhoemmen** [comment]
@searhein Run it in a debugger, or edit Tpetra to enable debugging output.

**Comment by kddevin** [comment]
@mhoemmen @tjfulle 
I built @searhein 's test and was able to reproduce the hang on my workstation.  The hang occurs in doTransferNew's call to doReversePostsAndWaits (line 1197).    Here's the output with the debug variable set to true; all processors report the same.

>>> DistObject::doTransferNew: remoteLIDs.size() = 48
>>> 1. checkSizes
>>> 2. copyAndPermuteNew
>>> 3. Allocate num{Ex,Im}portPacketsPerLID
>>> 4. packAndPrepareNew
>>> (Proc 2) 5.0. Before packAndPrepareNew, exports_.dimension_0()=0
>>> (Proc 2) 5.0. After packAndPrepareNew, exports_.dimension_0()=3936
>>> 7.0. Reverse mode
>>> 7.1. Variable # packets / LID: first comm
Proc 2: Reallocate (if needed) imports_ from 0 to 3936
Proc 2: Finished reallocating imports_
>>> 7.3. Second comm

If I change useNewInterface() in CrsMatrix to return false, the test program runs without the hang.  Can you describe the different between doTransferNew() and doTransfer() in DistObject?  Is there anything about the overlapped maps that might cause problems for doTransferNew?  Thanks!

**Comment by kddevin** [comment]
@searhein Can you describe your test problem?  It looks like an 8x8x8 Galeri mesh distributed over 2x2x2 processors.  What, then, does the FROSch call before the import do?  
I'm wondering if we can construct maps by-hand so that we can have a test similar to this one in Tpetra, without adding a dependence on FROSch and Xpetra.  We'd want the maps to be the same as yours.  Thanks.

**Comment by mhoemmen** [comment]
@kddevin I was at a workshop all day; I just got back tonight.  I'll send you an e-mail.  Thanks for working on this!

**Comment by tjfulle** [comment]
@kddevin @mhoemmen 

Can I help out with this?  I could work on replicating the problem this afternoon, but don't want to duplicate effort.

**Comment by searhein** [comment]
@kddevin Thank you for looking into this issue. 

Actually, I only compute a map that overlaps in one layer and then I do an import from the unique to the overlapping map. 
I can build a test which does not depend on FROSch and Xpetra. Do you need the test to fix this issue 
or would it be enough to create the test sometime during the next days?

**Comment by mhoemmen** [comment]
@tjfulle wrote:
> Can I help out with this? I could work on replicating the problem this afternoon, but don't want to duplicate effort.

I have a lot of urgent things to do this week not Trilinos-related, so please feel free; thanks! :-D

**Comment by tjfulle** [comment]
@mhoemmen, okay.  @searhein , I'll start digging in to this today.  A standalone test would be great to easily reproduce the error.

**Comment by kddevin** [comment]
I'll try to write a quick Tpetra-only test.

**Comment by tjfulle** [comment]
@kddevin thanks!  I'm pretty swamped today, I have most of tomorrow to look at this

**Comment by kddevin** [comment]
@searhein 
Does your code work if you use an importer instead of an exporter in the import?
Your test does not hang when I do
    Teuchos::RCP<Xpetra::Import<LO,GO,NO> > imgather = Xpetra::ImportFactory<LO,GO,NO>::Build(uniqueMap, overlappingMap);
    TeuchosComm->barrier(); if (TeuchosComm->getRank()==0) std::cout << "BEFORE IMPORT WITH IMPORTER\n";
    K->doImport(*tmpMatrix,*imgather,Xpetra::ADD);
    TeuchosComm->barrier(); if (TeuchosComm->getRank()==0) std::cout << "AFTER IMPORT WITH IMPORTER\n";
However, your test does not check the result of the import, so I do not know whether the correct matrix is produced.

@tjfulle @mhoemmen 
The attached program is a tpetra-only test.  It exhibits the hang in the same way that the shylu test does.  It does not use overlap maps; rather, it tries the import using two different one-to-one maps.   
-  With this test and useNewInterface=true, doImport works as expected with the importer, and hangs with the exporter
-  With this test and useNewInterface=false, neither doImport hangs, but neither case gives the expected results; the resulting matrices have no nonzeros.
Am I doing something wrong in the test?
[test_doImport.txt](https://github.com/trilinos/Trilinos/files/1358081/test_doImport.txt)

**Comment by tjfulle** [comment]
Thanks @kddevin !  I'll start working on this.

**Comment by mhoemmen** [comment]
@kddevin wrote:
> However, your test does not check the result of the import, so I do not know whether the correct matrix is produced.

This actually worries me a lot.  Reverse mode was never meant to be fully general.  I've seen really old FIXMEs in Tpetra that reflect copy-and-paste from Epetra, that talk about this.  @DrBooom knows what I'm talking about here (it's hard to explain in a comment).  What worries me is that Epetra might still be wrong here, but may not be hanging.

**Comment by tjfulle** [comment]
I've reproduced what @searhein reported using @kddevin's example.  I've narrowed down the problem to just a handful of potential sources.  I'll update when I have something a little more concrete

**Comment by tjfulle** [comment]
The example that @kddevin wrote gets hung up at a call to `doReverseWaits()` around [line 2906 of Tpetra_Distributor.hpp](https://github.com/trilinos/Trilinos/blob/develop/packages/tpetra/core/src/Tpetra_Distributor.hpp#L2906).  I haven't dug much further to determine what is going on from there down, or to determine what are the differences in the state of `Tpetra::CrsMatrix` between using the new interface vs. old.  

@mhoemmen, do you have any idea why it would hang at this point with the new interface but not the old (of course, the old will get to `doReverseWaits` through a different code path, but it is still called)?

**Comment by tjfulle** [comment]
The code stalls on [line 625 of Tpetra_Distributor.cpp](https://github.com/trilinos/Trilinos/blob/develop/packages/tpetra/core/src/Tpetra_Distributor.cpp#L625).  The underlying cause of the stall is likely in `doReversePosts` called on [line 2904 of Tpetra_Distributor.hpp](https://github.com/trilinos/Trilinos/blob/develop/packages/tpetra/core/src/Tpetra_Distributor.hpp#L2904)

**Comment by mhoemmen** [comment]
@tjfulle I'm not convinced that Epetra is actually correct for this case, since Epetra and Tpetra have a common origin here.  I've changed this code quite a bit in Tpetra over the years, so it's likely that Tpetra hangs where Epetra might just let stuff through.

Reverse-mode Import / Export wasn't written to be fully general.  One way to figure out whether this is the issue, would be to look at whether Distributor in forward mode (this is critical) enters what the comments call the "slow path," on at least one MPI process.

**Comment by mhoemmen** [comment]
Whether Distributor enters the "slow path" is a function of the source and target Maps in the Import or Export object.

**Comment by tjfulle** [comment]
@mhoemmen, I just wrote just about as simple an example I could come up with that demonstrates the problem.  (The identity matrix, 2 rows per process, one row shared with a neighboring process).  In the version of Tpetra that does not stall, Distributor in forward mode uses the "fast" path an reverse mode uses the "slow" path.  In the version of Tpetra where a hang occurs during the reverse mode import, it appears that Distributor is using the "fast" path.

**Comment by tjfulle** [comment]
@mhoemmen, the problem seems to be in the 4 argument, Kokkos version, of `Distributor::doPosts` if `Distributor::indicesTo_` is not empty.  If I bypass the problematic Kokkos version by doing the following at the beginning of the 4 argument, Kokkos version, of `Distributor::doPosts`:

```c++
      if (!indicesTo_.empty())
      {
        using Teuchos::arcp;
        typedef typename ExpView::non_const_value_type Packet;
        return doPosts(
            arcp<const Packet>(exports.ptr_on_device(), 0, exports.size(), false),
            numExportPacketsPerLID,
            arcp<Packet>(imports.ptr_on_device(), 0, imports.size(), false),
            numImportPacketsPerLID);
      }
```

my simple test passes.  @kddevin's more complicated test also passes.

Do you have any ideas why the Kokkos version of `doPosts` would cause the hang for the case that `Distributor::indicesTo` is not empty?

**Comment by mhoemmen** [comment]
@tjfulle Thanks for working on debugging this!

> the problem seems to be in the 4 argument, Kokkos version, of `Distributor::doPosts` if `Distributor::indicesTo_` is not empty.

The case where `Distributor::indicesTo_` is nonempty on a process, is exactly the case when that process takes the "slow path" in `doPosts`.  See Doxygen documentation for `indicesTo_`:

> This array is only used if export data are not blocked (laid out) by process rank, that is, if we need to use a send buffer.  Otherwise, this array has no entries.  (In fact, Distributor currently uses this in both overloads of doPosts() to test whether data are laid out by process.)

The two implementations of 4-argument `doPosts` are almost exactly the same.  My guess is that there is something wrong with how Views got set up, but it's hard to imagine what could have gone wrong in a non-CUDA build.  My only suggestion is to turn on debug output in the `Kokkos::View` version of 4-argument `doPosts` (see e.g., `debug_` in that code), and figure out where it's crashing.  You may find it useful to change Distributor in order to imitate what some other code in Tpetra has started doing, namely using `Tpetra::Details::Behavior` to read the `TPETRA_VERBOSE` environment variable and use that to set `debug_`.

**Comment by tjfulle** [comment]
Thanks @mhoemmen .  I've been running with `debug_` on, though using `Tpetra::Details::Behavior` would be preferable to hardcoding the flag.  The biggest pain, so far, is that there is no crash, the code just hangs. and it's still unclear where the hang is originating.  But, with the hack to workaround the hang, I am relatively confident I have the source narrowed down to a few tens of lines.

**Comment by mhoemmen** [comment]
@tjfulle wrote:
> ... [U]sing `Tpetra::Details::Behavior` would be preferable to hardcoding the flag ...

I have you to thank for implementing `Environment` :-) .  I started with that, then realized that I needed it to be more lightweight, as well as reëntrant (for use with task parallelism on host).

If you find it helpful for debugging, please feel free to change Distributor so that it uses `Behavior::verbose()` to set the default value of `debug_`.

**Comment by tjfulle** [comment]
Found it!  [This loop](https://github.com/trilinos/Trilinos/blob/develop/packages/tpetra/core/src/Tpetra_Distributor.hpp#L2825) prepares messages to be sent.  But, [numPacketsTo_p](https://github.com/trilinos/Trilinos/blob/develop/packages/tpetra/core/src/Tpetra_Distributor.hpp#L2824) is never incremented as it is in the [similar loop](https://github.com/trilinos/Trilinos/blob/develop/packages/tpetra/core/src/Tpetra_Distributor.hpp#L1840) in the `Teuchos::Array` version of the 4 argument `doPosts`.  This causes `Distributor` to *not* send any information for this code path.  Then, `doWaits` just sits and hangs waiting on nonexistent messages.  Incrementing `numPacketsTo_p` as in the `Teuchos::Array` version of `doPosts` fixes the issue of hanging on my simple test and on @kddevin's test.  @mhoemmen, was there a reason that `numPacketsTo_p` was not incremented, or perhaps it was a victim of copy/paste/convert to kokkos?

I'm not sure this code path is ever actually tested.  I've been working on an older commit to isolate the problem (and have not been building tests).  I'm going to checkout the current HEAD, put in the fix, convert my simple example to a proper test, and run the checkin script.  I'll open a PR with the fix and test later this morning.

**Comment by tjfulle** [comment]
To add to my last comment, the "slow" path of the Kokkos version of 4 argument `doPosts` is definitely *not* tested by Tpetra  (with my current setup, Darwin and `OpenMP` node type).  Adding `TEUCHOS_TEST_FOR_EXCEPTION(true, ...)` unconditionally to that code path results in 100% of Tpetra tests passing.

**Comment by mhoemmen** [comment]
@tjfulle : I just got out of some meetings.  Thanks for working on this!  Either (Teuchos or Kokkos) version of 4-argument doPosts would only be exercised by CrsGraph, CrsMatrix, BlockCrsMatrix, or CooMatrix.  We've tested the `Teuchos::Array*` version of 4-argument `doPosts` pretty thoroughly in practice, even the slow path (hence the tag stuff in there).

My eventual goal is to have a single version of `doPosts` that takes raw `char*` buffers.  If we move towards that goal as a result of fixing this, I'm all for it :-) .

**Comment by searhein** [comment]
@kddevin @tjfulle @mhoemmen 
I was now able to fix my code introducing additional exporters and importers in some parts of the code, where the reverse mode hung; see #1834.
The code runs through now and gives me the correct result. However, in order to reduce communication cost, it would be nice if I could remove those additional exporters and importers as soon as the issue is fixed. Thanks!

**Comment by tjfulle** [comment]
@searhein, I am running the checkin script right now and should have a PR open very soon with a fix.

**Comment by mhoemmen** [comment]
@searhein I'm curious why you need reverse mode; would you mind explaining?

**Comment by mhoemmen** [comment]
@tjfulle I'm reviewing your PR right now.  Thanks!

**Comment by searhein** [comment]
@mhoemmen I need to communicate in both ways with the same maps. However, I would like to create the Import/Export object only once.

**Comment by tjfulle** [comment]
The only PR I have open is for a different issue.  It just adds a test for pack/unpack.  I'm still running the checkin script for this issue.  A PR is eminent.

**Comment by mhoemmen** [comment]
@tjfulle ah sorry, that was the PR coming from the check-in test script, in your fork :) .

**Comment by mhoemmen** [comment]
@searhein Thanks for the explanation!

**Comment by tjfulle** [comment]
@mhoemmen, I pushed to that branch as an intermediate, I am now running the full checkin script on my blade.  But, time spent looking at the commit is not lost, since I'll open a PR based on it soon.

There is only a 1 line code change, but I updated a lot of the debug statements to be more informative, so it appears there are more changes that there really are.

But, PR #1769 is still open :)

**Comment by mhoemmen** [comment]
@tjfulle I'm working on #1769 now :) .

**Comment by tjfulle** [comment]
@mhoemmen, PR #1838 fixes the hang for the test case I added.  It also fixes the hang in @kddevin's test she posted here.

@searhein, could you check your code against PR #1838 to see if it fixes the hang you are experiencing.

**Comment by mhoemmen** [comment]
@tjfulle I hereby approve #1838.  Please feel free to push if it builds and passes tests for you.  Don't worry about the CUDA build for now; this should be independent of that.  Thanks! :-D

**Comment by tjfulle** [comment]
@searhein, this should now be fixed.  When you get a chance, if you could check your code and close this issue if it is fixed.

**Comment by searhein** [comment]
@tjfulle I can confirm that #1838 fixed this issue for my code. 
@kddevin @mhoemmen @tjfulle Thank you a lot for fixing this :-)
