### ISSUE TITLE
Teuchos:  Potential C++11 Non-compliance issues

### ISSUE THREAD

**Issue by csiefer2** [trilinos/Trilinos#1756]
From here: http://en.cppreference.com/w/cpp/language/destructor

As any other function, a destructor may terminate by throwing an exception (this usually requires it to be explicitly declared noexcept(false)) (since C++11)

The destructor for Teuchos::RawWorkspace throws an exception without a noexcept(false) declaration.

This causes Visual Studio to whine.

Is this worth fixing?

**Comment by aprokop** [comment]
@trilinos/teuchos

**Comment by mhoemmen** [comment]
Is this a duplicate of #1303?

**Comment by mhoemmen** [comment]
@csiefer2 wrote:
> This causes Visual Studio to whine.

Does this mean "emit a warning" or "refuse to build"?

**Comment by csiefer2** [comment]
@mhoemmen : "Emit a warning"

And yeah, this is probably a dupe.

**Comment by mhoemmen** [comment]
@csiefer2 wrote:
> And yeah, this is probably a dupe.

No worries! :-) Just wanted to reference that issue.
