### ISSUE TITLE
MueLu/Tpetra local-ordinal/offset type errornous conversion issues

### ISSUE THREAD

**Issue by mndevec** [trilinos/Trilinos#1760]
I am having issues whenever I "serially" run experiments with large matrices that have larger than 2B nonzeroes.  For example, I am running MueLu test driver, with 200M rows and 5.4B rows, which should be okay for single rank, as local ordinals are int, and offset type is size_t. This segfaults without printing anything, which suggests overflow issues as early as during input generation. 

I am trying to trackdown the issue using the compile flag -Wconversion to capture where the local ordinal types are used instead of offset types. Many of the warnings are over cautious, but still there are various errors that arise from the confusion of LO and offset_type, possibly causing segfaults in this case. 

This conflicts with the use of separate types for offset and local ordinals. That would be good to fix these issues, and if possible to have a "stress" test for such cases. 
@kddevin

**Comment by aprokop** [comment]
@trilinos/muelu 

@mndevec Yes, I don't think we are careful enough not to mix `LocalOrdinal` and `size_t`. We don't have any drivers/testing supporting this regime, so it's no surprise that it fails. I can work with you to iron out the issues here. Are you running the regular MueLu or the Kokkos-refactor "branch"?

**Comment by mhoemmen** [comment]
@mndevec Even Kokkos team parallelism isn't so particular about using 64-bit types where appropriate.  I would be very nervous about problems with more than 2B things on a process.

**Comment by aprokop** [comment]
Is this mode is something that a lot of people care about, or is going to become important in the future? Because when you say MueLu, you are talking *all* upstream packages from it (Ifpack2, Xpetra, ...)

**Comment by lucbv** [comment]
@mndevec did the 200M rows test case work eventually? I am currently working on a test case at 20M but will eventually move on to something at a little more than 100M. It would be nice to be sure that these work decently well.

**Comment by kddevin** [comment]
From the discussion in #674, I thought this use case was supported, so we made changes in Zoltan2 to support offset_type that is not defined to be local_ordinal. 
Should we just be using local_ordinal for all local indexing?  If so, should we remove offset_type?

**Comment by mndevec** [comment]
@aprokop I was running regular MeuLu without the refactor branch.
@lucbv , it does not run on a single rank, I was able to run it with 4 ranks, but then it fails when I try to write the matrices. 

If we are going through the route of separate offset and local_ordinal type, we should be able to handle such large cases. Otherwise, we are paying the price of 2 template parameters, and possibly slowing down because of 64-bit integers, but still do not support the large matrices.

**Comment by mndevec** [comment]
@kddevin : below is how I generate this error. 
./MueLu_Driver.exe --nx=570 --ny=570 --nz=570   --matrixType="Brick3D" --xml=../rap.xml

rap.xml is as below.
```
<ParameterList name="MueLu">
  <Parameter        name="verbosity"                type="string"   value="high"/>
  <Parameter        name="max levels"               type="int"      value="2"/>

  <Parameter        name="transpose: use implicit"  type="bool"     value="true"/>

  <Parameter        name="smoother: pre or post"    type="string"   value="none"/>
  <Parameter        name="coarse: type"             type="string"   value="none"/>

  <Parameter        name="repartition: enable"      type="bool"     value="false"/>
  <Parameter        name="aggregation: type"        type="string"   value="uncoupled"/>
  <ParameterList name="export data">
    <Parameter name="A" type="string" value="{0,1,2,3}" />
    <Parameter name="P" type="string" value="{0,1,2,3}" />
    <Parameter name="R" type="string" value="{0,1,2,3}" />
  </ParameterList>

</ParameterList>


```

**Comment by mhoemmen** [comment]
@kddevin wrote:
> From the discussion in #674, I thought this use case was supported, so we made changes in Zoltan2 to support offset_type that is not defined to be local_ordinal.

That is still the right thing to do, but if we really want to support this use case, I think we need some more comprehensive tests at all levels of the stack.

**Comment by csiefer2** [comment]
As an aside, Windows testing has revealed pretty pervasive size_t/int issues floating across the stack.

**Comment by kddevin** [comment]
@csiefer2 Please describe.

**Comment by csiefer2** [comment]
Visual studio reports a ton of warnings like this:

Warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data

Usually this is either due to (a) explicit use of ints or (b) where "int" is the actual type that LocalOrdinal represents.

Look for "TRILINOS-WIN1" on Cdash

**Comment by mndevec** [comment]
@csiefer2 those warnings are visible with gcc & -Wconversion flag.

As you said there are many of (a) and (b) situations. 
There exists many (c) where it is in fact safe to do this assignment as below where we know that row_size is Local Ordinal. But this is unfortunately making the fixes more difficult.
```
LO row_size = rowPtr[i+1] - rowPtr[i];
```

**Comment by mhoemmen** [comment]
@mndevec Do you still get the warnings if you cast explicitly?
```
const LO row_size = static_cast<LO> (rowPtr[i+1] - rowPtr[i]);
```

**Comment by mndevec** [comment]
I think, you don't get warning with explicit casting.

**Comment by mhoemmen** [comment]
@mndevec I would recommend using an explicit cast for situations like this.  It helps the reader see that you're casting, and it's a good opportunity to add a comment justifying the cast.  In this case, it's perfectly justified, assuming that rows never have enough duplicates to exceed the bounds of `LO`.

**Comment by csiefer2** [comment]
@mndevec @mhoemmen  I've been scattering explicit casts throughout Trilinos to suppress those warnings and to make it obvious to the viewer that we're playing fast and loose with types.

They do seem to suppress the warnings.

**Comment by mhoemmen** [comment]
@csiefer2 I wouldn't call this case "playing fast and loose with types"; we can prove in this case that the cast is correct, given a modest assumption of not too many duplicate entries in a row.  But yes, in general, making casts explicit is good :-) .

**Comment by lucbv** [comment]
Would it make sense to have a build with -Wconversion flag on so that these conversions can be tracked more easily and eventually fixed if needed?

**Comment by csiefer2** [comment]
@lucbv Yes.  We should add one on geminga.

**Comment by jhux2** [comment]
> @lucbv Yes. We should add one on geminga.

@csiefer2 geminga is heavily loaded already.  I'd suggest enigma.

**Comment by csiefer2** [comment]
@jhux2 Fine by me.
