### ISSUE TITLE
Upgrade minimum required version of CMake to allow for TriBITS refactorings

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#1761]
**CC:** @trilinos/framework 

## Description

This story is to drive the upgrade of the minimum version of CMake required to configure Trilinos.  Currently the minimum version is 2.8.11 which was first tagged way back May 15, 2013 (i.e. more than 4 years ago).  Upgrading the minimum version of CMake will allow us to take advantage of newer CMake features to refactor and simplify a lot of code in TriBITS.

The reason that this issue is being listed in the Trilinos GitHub repo and not the TriBITS repo is that Trilinos is the TriBITS customer that limits the upgrades of CMake.  The other projects where TriBITS is used like CASL VERA and ATDM could upgrade CMake much easier (and really could almost track the most current CMake version).

## Tasks

1. Make annoucement to trilinos-users and trilinos-developers to upgrade min version to 3.10 **[Done]**
2. Change all Trilinos jobs posting to CDash to use CMake 3.10+
    - Change all SEMS-based modules to use CMake 3.10.3 **[Done]**
    - Upgrade the windows builds to use CMake 3.10+ [installed, not tested due to other issues]
    - Upgrade ATDM Trilinos builds on 'mutrino' to use CMake 3.10+ ... Merged in PR #3051 **[Done]**
3. Change the minimum version of CMake to 3.10+ in Trilinos/CMakeLists.txt **[Done]**
4. Switch the mode of Trilinos to the all-at-once mode for configure, build, test, and submit **[Done]**
5. Watch for and help address developer and user issues with transition to CMake 3.10+ ... **IN PROGRESS ...**

**Comment by ibaned** [comment]
What should the new minimum version be? My vote is for 3.0.1 or newer, because that was really the beginning of "modern CMake" as it is now seen in tutorials throughout the web. The benefits of exported target properties are amazing. Also that version was released in 2014.

**Comment by mhoemmen** [comment]
I'm all for doing this.  Does changing the minimum required CMake version in Trilinos improve configure times?  I've heard that newer CMake versions go into a backwards compatibility mode if the minimum required version is low, but I'm not sure how that effects configure times.

**Comment by bartlettroscoe** [comment]
> Would changing the minimum required CMake version in Trilinos improve configure times? I've heard that newer CMake versions go into a backwards compatibility mode if the minimum required version is low, but I'm not sure how that effects configure times.

Yes and no.  A while back Brad King at Kitware identified a major performance gain when going with CMake 3.3 policies.  So now TriBITS will automatically turn on CMake 3.3 policies when it detects CMake version 3.3 or above.  So we get CMake 2.8.11 backward compatibility but we get CMake 3.3+ performance.  But there may be other issues like this that we may benefit from.

Many other features have been added to CMake since version 3.0 (some that our contracts payed for) and I need to have lots of conditional logic in TriBITS to work with this.  Once CMake 3.10 comes out, I would like to upgrade to that.  I know this is a major departure for Trilinos but if we want to take advantage of new CMake features (and avoid having to constantly add stuff or fix stuff in TriBITS only to have it fixed in CMake later), then we need a much more aggressive upgrade schedule.  My view is that CMake is easier to configure and build from source on any target platform than any software you would configure and build with CMake.  We already have an install-cmake.py script in TriBITS (and therefore in Trilinos) so people can just use that to download and build CMake from source or download the binaries off of the Kitware site.

External Trilinos projects and customers are the the limited factor here.  Internal SNL projects will have no problem going with whatever version of CMake we pick (and upgrading it frequently).  Those projects are the ones the pay the bills.  This more aggressive upgrade schedule will not happen all of the time, only in time periods where we need new features in CMake so that we can avoid having to add them in TriBITS (which is expensive in human and computer time).  I get **lots** of criticism for adding features to TriBITS that could be added to CMake.  But unless we can force a very aggressive upgrade schedule for CMake, we just can't wait for 2+ years to add new features to our system that we need now.

**Comment by ibaned** [comment]
> Once CMake 3.10 comes out, I would like to upgrade to that.

A bold plan, but I can understand the rationale in terms of clearing the conditionals out of TriBITS.
Are there specific features that even non-TriBITS users ought to be aware of?

**Comment by rppawlo** [comment]
@ibaned - cmake 3.9 is important if you use ninja. From the release notes:

> The Ninja generator has loosened the dependencies of object compilation. Object compilation now depends only on custom targets and custom commands associated with libraries on which the object’s target depends and no longer depends on the libraries themselves. Source files in dependent targets may now compile without waiting for their targets’ dependencies to link.

This didn't make much difference if you only need a few Trilinos packages, but for apps like Drekar that require 45+ packages, it is significant.

**Comment by bartlettroscoe** [comment]
Also, CMake 3.7+ is needed in order to generate the dummy makefiles for Ninja that I think @rppawlo is using.  This was a new feature that was added to TriBITS (see TriBITSPub/TriBITS#166) that is not present in CMake (Kitware did not want to add that feature to CMake proper, for whatever reason).  I think it is useful to be able to just configure, then `cd` into a directory and then just type `make` and only build the targets in that directory.  And it is super useful when building and running tests in an iterative manner.  That is a big usability feature for me personally (and I don't think I would use Ninja without that).  @rppawlo  can comment if that is a sufficiently useful feature or not over just raw CMake + Ninja.

**Comment by rppawlo** [comment]
> Also, CMake 3.7+ is needed in order to generate the dummy makefiles for Ninja that I think @rppawlo is using. This was a new feature that was added to TriBITS (see TriBITSPub/TriBITS#166) that is not present in CMake (Kitware did not want to add that feature to CMake proper, for whatever reason). I think it is useful to be able to just configure, then cd into a directory and then just type make and only build the targets in that directory. And it is super useful when building and running tests in an iterative manner. That is a big usability feature for me personally (and I don't think I would use Ninja without that). @rppawlo can comment if that is a sufficiently useful feature or not over just raw CMake + Ninja.

Yes - this is extremely useful for development.

**Comment by ibaned** [comment]
I see, thank you both for the details.  I guess I should start experimenting with Ninja.

**Comment by bartlettroscoe** [comment]
> Are there specific features that even non-TriBITS users ought to be aware of?

With CMake 3.10, CMake projects will be able to define subprojects and submit them to CDash and display results subproject-by-subproject with much less specialized infrastructure (and no hacking of CTest XML files).  But you would not get the rest of the advantages of an explicit package-based architecture like with TriBITS.

**Comment by bartlettroscoe** [comment]
> I see, thank you both for the details. I guess I should start experimenting with Ninja.

If you build any Fortran, you will need Kitware's fork of Fortran.

I just tried SPARC (which has C, C++, and Fortran) and CMake + Ninja (with Kitware Fortran enhancemetns) and it worked great.

**Comment by ibaned** [comment]
> define subprojects and submit them to CDash and display results subproject-by-subproject with much less specialized infrastructure

That is even more directly interesting to me, I'd like to try this out once its available.

> Kitware's fork of Fortran

I'm going to assume you mean Ninja?

**Comment by bartlettroscoe** [comment]
> > Kitware's fork of Fortran
>
> I'm going to assume you mean Ninja?

Yes, Kitware's fork of Ninja to support Fortran.

**Comment by rppawlo** [comment]
Just to follow up with some concrete timings on the ninja support. When I build all of Trilinos, Drekar and another app with all relevant tests for my projects, ninja with cmake 3.9 took 22 minutes to build from scratch in a single TriBITS build. Changing to the make generator, it took 55 minutes. If I repeat for just the phalanx package (depends only on Teuchos, Kokkos, KokkosContainers and Sacado) the difference was negligible.

**Comment by bartlettroscoe** [comment]
@rppawlo,

> Just to follow up with some concrete timings on the ninja support. When I build all of Trilinos, Drekar and another app with all relevant tests for my projects, ninja with cmake 3.9 took 22 minutes to build from scratch in a single TriBITS build. Changing to the make generator, it took 55 minutes. 

How may cores `<N>` did you use with `make NP=<N>` (or just `ninja -j<N>`)?

**Comment by rppawlo** [comment]
my whole workstation - 72 cores with hyperthreads. I ran "make -j72" for make and "ninja" with no core specification. Ninja automatically detects the number of cores and throttles jobs to fill the entire machine.

**Comment by bartlettroscoe** [comment]
> my whole workstation - 72 cores with hyperthreads. I ran "make -j72" for make and "ninja" with no core specification. Ninja automatically detects the number of cores and throttles jobs to fill the entire machine.

Wow, those are a lot of cores!  That is a cool feature of ninja.  We got Kitware to add something like that for ctest also so that it will not overload the machine running tests in parallel (we use it in CASL VERA testing) (try out the `--test-load <max_system_load>` option with CTest).

**Comment by jwillenbring** [comment]
@trilinos/framework 
@bartlettroscoe It seems there is a difference between issues such as using 3.10 for the new-stye submits, and the needing an upgraded version for refactoring TriBITS. For example, we could have a minimum version (informal) for submitting to CDash, while possibly having a lower minimum version for general Trilinos builds. If people want to use ninja, they will need a minimum version, but if not, they won't, unless that prevents additional refactoring. What version would allow you to refactor TriBITS to remove code that can be based on the latest CMake functionality?

**Comment by bartlettroscoe** [comment]
>  What version would allow you to refactor TriBITS to remove code that can be based on the latest CMake functionality?

Not sure until we get into the guts of the refactoring.

Another approach would be to do a survey of Trilinos Developers and User and see what the more recent version of CMake that people have access to and then use that to see how high we can go.   Then we can list out the new CMake features that are at our disposal in that CMake version and see how we could use them to gut and simplify the internals of TriBITS.

By biggest concern is all of the if statements, additional automated testing, and additional documentation needed to support TriBITS features for different versions of CMake.  And then we have the problem of, what if we need CMake to add a new feature that we need to use very soon so that we can avoid having to write a bunch of code in TriBITS to handle this otherwise.  One example was timing and having to having to implement some factional number math in TriBITS using just integer support in CMake with `MATH(EXPR ...)`.  If you want to see code for that in TriBITS that deals with this, take a look at:

* https://github.com/TriBITSPub/TriBITS/blob/552e8c755f316b2db443ea59fe0cfc529d5d6f98/tribits/core/package_arch/TribitsAddTestHelpers.cmake#L89 
* https://github.com/TriBITSPub/TriBITS/blob/552e8c755f316b2db443ea59fe0cfc529d5d6f98/tribits/core/utils/TimingUtils.cmake

We needed that for timing parts of the configure (in an important code performance effort) and scaling test timeouts (both of which were critical for CASL).  If we would have had a contract with Kitware at ORNL at the time, we would have just paid them to add floating point number support to `MATH(EXPR ...)` and a raw time function and then directly used that.  For CASL, this would have saved me a lot of time and extra CMake code and this would have worked fine since our dev env provides whatever version of CMake that we want.  In this case, we could have handled updating TriBITS in Trilinos it by just not supporting those features in older versions of CMake (since Trilinos itself may not need those features).  But now we want to rip that code out of TriBITS and use better implementations in CMake (that Kitware has not implemented yet as in this case).  How can we do that?  If we pay Kitware to add a raw system timing function and floating point number support in `MATH(EXPR ...)`, then how long will it be before we can rip out that code in TriBITS and just use CMake?  Would it be 1 year?  2 years?  4 years?  What is the value of that?

If we can't use new features in CMake so that we can rip out code in TriBITS and avoid having to write new code in TriBITS in the first place to do what we need, then we will likely just go back to the mode where we don't pay Kitware to add new features to CMake and CTest because it is too hard to actually use them in any reasonable time-frame.  But then we will be back to adding code to TriBITS to fill-in for missing features and patch behavior of CMake that is not good for us (e.g. #1427).  (And then people will go on complaining that TriBITS is too complex and we should, ironically, just be using new CMake features.)

**Comment by bartlettroscoe** [comment]
FYI: The default CMake for Travis CI is now up to cmake-3.9.2.  See TriBITSPub/TriBITS#240.

**Comment by jwillenbring** [comment]
I think it would make sense to see what new features will allow important refactoring to take place, and then line it up with that. That would allow a meaningful cost/value analysis. Perhaps some refactoring could prioritized higher because the jump would be less, then another jump could again me made. When we jump, we should encourage affected users to move to the latest to avoid another likely jump.

**Comment by bartlettroscoe** [comment]
@jwillenbring note that if the auto PR testing (i.e. #1155) is implemented to use CMake 3.10 (in order to do do all-at-once submits) then it will allow CMake code to sneak in that actually breaks with older versions of CMake.  Therefore, nightly builds and customers using older versions of CMake will be more likely to get broken configures or builds.   This is yet another motivator for upgrading the minimum CMake version to a pretty recent version.  Another example is #2160.  How can we pull the trigger on this?

**Comment by ibaned** [comment]
It would be very helpful, though not strictly necessary, to get SEMS and the testbed teams to install CMake 3.10 modules.

**Comment by bartlettroscoe** [comment]
> It would be very helpful, though not strictly necessary, to get SEMS and the testbed teams to install CMake 3.10 modules.

@ibaned, ATDM is going to be using CMake 3.10+ going forward and will be updating CMake frequently as new features are added that we can use.  For example, CMake 3.11 (when it is released) will provide much better parallel scaling with `ctest -j<N>` and provide better automatic support for the usage of response files to deal with commandline-too-long errors among other improvements.

I honestly don't know what important Trilinos customers will be holding back the upgrade of the minimum supported version of CMake.  What version of CMake is Albany using for example?

**Comment by ibaned** [comment]
@bartlettroscoe Albany doesn't specify CMake versions strictly, but I know we've had to compile our own CMake in the past because the CEE machines and testbeds didn't have a new enough CMake. I think one of the testbeds still has 3.6 or less as its newest module version. The projects I work on won't be too upset if we require the latest version, our only pain point is having to compile CMake when modules aren't available, but we're willing to do that. I'm just suggesting that putting these modules up early (e.g. within a month of Kitware's release) will make this easier for everyone.

**Comment by bartlettroscoe** [comment]
FYI: Just got pinged by @prwolfe about header-only libraries with TriBITS.  Supporting that cleanly would require a upgrade of CMake to a least 3.0.  The is the first version of CMake that supports the `add_library( ... INTERFACE ... )` as shown at:

* https://cmake.org/cmake/help/v3.0/command/add_library.html

This would also allow the refactoring of TriBITS to use the newer CMake features of `target_include_directories()`, etc.  That would reduce a lot of TriBITS code.

**Comment by prwolfe** [comment]
What I was doing that I pinged @bartlettroscoe was attempting to set up a build of stk for a PR.  While he did provide a work-around it is less than elegant.

I also went and looked and the default came on RHEL6 is 2.8.12.  A consideration for supporting some customers, but not a large one considering both that make is a fairly robust build and that RPMs for it up to 3.11 are readily available through yum.

I think the biggest questions are
* when can seems support what - they are currently at 3.5.2 and below, so that might be our target
* when can the Framework team prioritize this. That might take some time and I would not give it top priority at the moment.

**Comment by bartlettroscoe** [comment]
@trilinos/framework, 

With the impending upgrade to the new CDash version and now all of the CI and auto PR builds using CMake 3.11.1+, are we in a position to upgrade the minimum version of CMake to at least 3.10 (which is the first version to support the all-at-once configure, build, test, and submit features)?

This would help to address issues like #3118 and #2162.

**Comment by bartlettroscoe** [comment]
FYI: From @william76:

> I asked about CMake 3.10.3 in the SEMS meeting this afternoon and the response is that SEMS has CMake 3.10.3 available on RHEL6, 7, TOSS3, and Darwin 10.11 and 10.12.

I think this means we can switch all of the Trilinos automated builds over to CMake 3.10.0+.

**Comment by bartlettroscoe** [comment]
FYI:

@jwillenbring checked the the Windows builds are currently using CMake 3.8.1 so they need to be upgraded to CMake 3.10+.

**Comment by jwillenbring** [comment]
I sent the following message to the trilinos-users mail list, and a slightly more detailed version of this message to the trilinos-developers list:

All,
 
We are planning to increase the required minimum version of CMake for building Trilinos to 3.10 on or after August 14th.
 
There are several reasons to update to 3.10, multiple having to do with performance, one to avoid an error, and the newer version also supports the newer single configure, build, test CDash submissions that make building Trilinos for nightly testing much faster. In addition, the increase to 3.10 will allow some TriBITS refactoring to be done to take advantage of some functionality now available in CMake that TriBITS has done itself to this point.
 
A more comprehensive discussion of the benefits and further information can be found in issue 1761:
 
https://github.com/trilinos/Trilinos/issues/1761
 
If you anticipate significant difficulties due to this version increase, please contact the Framework team by mentioning @trilinos/framework in the GitHub issue linked above (preferred), or by sending a message to the trilinos-framework@software.sandia.gov mail list. SEMS now has CMake version 3.10.3 available for Linux and Mac on the NFS Mount. CMake can also be downloaded and installed from the CMake website:
 
https://cmake.org/download/
 
If you are upgrading your version of CMake, we recommend going to the latest version, which is currently 3.12.0.
 
Thanks
 
Jim

**Comment by jwillenbring** [comment]
> @jwillenbring checked the the Windows builds are currently using CMake 3.8.1 so they need to be upgraded to CMake 3.10+.

I installed CMake 3.12.0 on the Windows machine, but have not been able to test it due to other issues on that platform. I don't want to ignore this, but I also don't want this to be an impediment that significantly delays the version increase.

**Comment by bartlettroscoe** [comment]
FYI: Realized that we also need to upgrade the ATDM Trilinos builds on 'mutrino' to use CMake 3.10+.  I added that to the above "task" list and I am working on that now.

What about getting the other SEMS-based Trilinos builds to use the new SEMS CMake 3.10.3 module?

**Comment by bartlettroscoe** [comment]
FYI: With the merge of PR #3051, the ATDM Trilinos builds on 'mutrino' are now using CMake 3.11.4 (I was a bit afraid to use CMake 3.12.0).

**Comment by bartlettroscoe** [comment]
FYI: You can see the switch to the all-at-once approach for the post-push CI build shown [here](https://testing-vm.sandia.gov/cdash/index.php?project=Trilinos&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=4&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Linux-GCC-4.8.4-MPI_RELEASE_DEBUG_SHARED_PT_OPENMP_CI&field2=groupname&compare2=61&value2=Continuous&field3=buildstarttime&compare3=84&value3=now&field4=buildstarttime&compare4=83&value4=2018-08-10) starting on 8/12/2019.  Notice the drop in configure, build and test times for the first from-scratch builds on 8/11/2018 to 8/12/2018 shown below.

| Build Stamp | Mode | Configure Time | Build Time | Test Time |
| :-- | :-- | --: | --: | --: |
| `20180811-1000-Continuous` | Package-by-Package | 5m 30s | 2h 59m 4s | 25m 42s | 
| `20180812-1000-Continuous` | All-at-once | 2m 22s | 1h 57m 59s | 17m 16s |

And check out the rebuild and retest times for intermediate CI iteration for Build Time Stamp `20180813-1412-Continuous`:

* Number Labels: 43 (triggered by change to Teuchos shown [here](https://testing-vm.sandia.gov/cdash/viewNotes.php?buildid=3828471#!#note3))
* Configure Time: 3m 18s
* Build Time: 9m 4s
* Test Time: 15m 35s

That is fast.

**Comment by bartlettroscoe** [comment]
@jwillenbring, from the task:

3. Change the minimum version of CMake to 3.10+ in Trilinos/CMakeLists.txt [target date Aug 14]

today is the target date to change the min CMake version to 3.10.0.  Can we make this switch?  It is a single-line change to `Trilinos/CMakeLists.txt`. I can then make that the minimum version for TriBITS as well.

**Comment by mhoemmen** [comment]
FYI @micahahoward

**Comment by bartlettroscoe** [comment]
Hello @trilinos/framework team.  Anyway I can do to move this along and make CMake 3.10 the min required for TriBITS (and therefore Trilinos)?

Doing so would make it super easy to have TriBITS use the new "DISABLED" test property and finish TriBITSPub/TriBITS#173.  Otherwise, I have to re-implement this branch to support both the old and new implementations.  This would really ATDM help by making obvious what tests are disabled by showing them on CDash.

**Comment by bartlettroscoe** [comment]
FYI: It would also be really nice to rip out the TriBITS support for C++11 and just use the new raw CMake support defined at:

* https://cmake.org/cmake/help/v3.10/variable/CMAKE_CXX_STANDARD.html#variable:CMAKE_CXX_STANDARD
* https://cmake.org/cmake/help/v3.10/prop_tgt/CXX_STANDARD.html#prop_tgt:CXX_STANDARD

But we can't do that until Trilinos no longer requires an updated version of CMake since those options don't exist in CMake 2.8.11.

**Comment by bartlettroscoe** [comment]
FYI: I created PR #3513 to update all of the CMake versions to 3.10+.  But note there are a few references to older CMake versions that don't use SEMS and those are:

```
$ find cmake/ctest/ -type f -exec grep -nH cmake {} \; \
    grep -v "[.]cmake" | grep "\(2[.]8\|3[.]\)" | grep -v "3[.]10[.]3" | grep -v "3[.]11[.]" | sort

cmake/ctest/drivers/apollo/jenkins_driver.sh:39:module load cmake/2.8.11
cmake/ctest/drivers/artemis/jenkins_driver.sh:39:module load cmake/2.8.11
cmake/ctest/drivers/ictinus/cron_driver.sh:29:export PATH=/Users/jmwille/install/git/bin:/Users/jmwille/install/cmake-2.8.4/bin:/Users/jmwille/install/gcc-4.4.6/openmpi-1.4.3/bin:/
cmake/ctest/drivers/perseus/jenkins_driver.sh:39:module load cmake/2.8.11
cmake/ctest/drivers/windows/create_windows_package.bat:15:set CMAKE_DIR=%SEMS_DIR%\utility\cmake\3.8.1\bin
cmake/ctest/drivers/windows/task_driver_windows.bat:8:set CTEST_EXE=%SEMS_DIR%\utility\cmake\3.8.1\bin\ctest.exe
```

@william76 and @jwillenbring, are these builds that are still running?  Is the above windows build the one that the Framework team is running?  If so, that will need to be updated.

**Comment by csiefer2** [comment]
I would highly appreciate if the sems updated sems-cmake/3.10.3 to be the default sems-cmake as part of this change.

**Comment by csiefer2** [comment]
> Is the above windows build the one that the Framework team is running? If so, that will need to be updated.

You presume that the windows build is actually *running*.  There are multiple tickets about it not running...

**Comment by bartlettroscoe** [comment]
> I would highly appreciate if the sems updated sems-cmake/3.10.3 to be the default sems-cmake as part of this change.

@csiefer2, do you mean the version loaded with `Trilinos/cmake/load_sems_dev_env.sh`?  Otherwise, there is no such thing as a "standard" SEMS CMake version otherwise as far as I know.

**Comment by bartlettroscoe** [comment]
> You presume that the windows build is actually running. There are multiple tickets about it not running...

Then I guess we can't break it :-)

**Comment by csiefer2** [comment]
> @csiefer2, do you mean the version loaded with `Trilinos/cmake/load_sems_dev_env.sh`? Otherwise, there is no such thing as a "standard" SEMS CMake version otherwise as far as I know.

Typing "module load sems-cmake" will load 3.5.2

**Comment by csiefer2** [comment]
> Then I guess we can't break it :-)

LOL

**Comment by bartlettroscoe** [comment]
FYI: Just talked with @jwillenbring today and it seems were are on track for switching the min version of CMake for Trilinos and TriBITS to 3.10.0 starting 10/10/2018.

**Comment by bartlettroscoe** [comment]
> @prwolfe @rrdrake @micahahoward

FYI: On every configuration where the ATDM Trilinos configuration is supported, it is using CMake 3.11+.

**Comment by bartlettroscoe** [comment]
FYI: In TriBITS 'master' commit TriBITSPub/TriBITS@a5d1ece0c4aa86259569d62f2380fa106c96865e, I updated the Travis CI build to use CMake 3.10.3 and it is showing CMake 3.10.3 in theTavis CI build on 'master' at:

* https://travis-ci.org/TriBITSPub/TriBITS/builds/436229452
* https://testing-vm.sandia.gov/cdash/index.php?project=TriBITS&parentid=3999313&filtercount=1&showfilters=1&field1=buildstarttime&compare1=83&value1=2%20weeks%20ago

Now all that is left to do is wait till 10/10/2018 and pull the trigger on updating the min version of CMake in TriBITS and Trilinos to 3.10.

**Comment by bartlettroscoe** [comment]
Today is the day!  I am starting the work right now to make CMake 3.10+ required for TriBITS and Trilinos.  I will post a Trilinos PR shortly.

**Comment by bartlettroscoe** [comment]
I just posted PR #3590 that switches to min CMake 3.10 and turns on TriBITS CTest -S all-at-once mode by default.  Just need to have the PR approved, PR testing completed, and then be merged and then we can send out an email announcing the update.

**Comment by mhoemmen** [comment]
YAY

**Comment by bartlettroscoe** [comment]
The PR #3590 was reviewed and approved, just passed PR testing (of all Trilinos packages) and was auto-merged.

Now I just need to send out email announcing the transition to CMake 3.10+ is complete and then watch and look for failures on CDash and respond to people who say they can't configure anymore because they don't have CMake 3.10+ installed on their systems :-)

**Comment by bartlettroscoe** [comment]
I just sent the following two emails announcing this transition is complete.  Now I will put this Issue "in review" and see how it goes.

----

From: Bartlett, Roscoe A 
Sent: Wednesday, October 10, 2018 6:43 PM
To: 'trilinos-developers@trilinos.org' <trilinos-developers@trilinos.org>
Subject: RE: upgrading minimum required version of CMake for Trilinos

Hello Trilinos Developers,

The transition for Trilinos to require CMake 3.10+ on the ‘develop’ branch is now complete.  All Trilinos developers and users will now need to use CMake 3.10+ in order to configure, build, install, and test Trilinos.

If you have problems with this, please add a comment to:

    https://github.com/trilinos/Trilinos/issues/1761

and we will try to help you.

Thanks,

-Ross

----

From: Bartlett, Roscoe A 
Sent: Wednesday, October 10, 2018 6:44 PM
To: 'trilinos-users@trilinos.org' <trilinos-users@trilinos.org>
Subject: RE: upgrading minimum required version of CMake for Trilinos

Hello Trilinos Users,

The transition for Trilinos to require CMake 3.10+ on the ‘develop’ branch is now complete.  All Trilinos developers and users will now need to use CMake 3.10+ in order to configure, build, install, and test Trilinos.

Cheers,

-Ross

**Comment by bartlettroscoe** [comment]
@trilinos/framework,

Looks like something strange is happening with the "Clean" builds after making this change.  It looks like they are trying to enable PyTrilinos.  Why is that?  None of the other builds that I can see are having problems like this.

**Comment by wfspotz** [comment]
I don't think I changed any `CMakeLists.txt` files upstream of `packages/PyTrilinos/CMakeLists.txt`.

**Comment by bartlettroscoe** [comment]
> I don't think I changed any CMakeLists.txt files upstream of packages/PyTrilinos/CMakeLists.txt.

@wfspotz, I don't think the problem is in any CMakeLists.txt file.  My guess is that the problem is in the CTest -S driver code.  That code may not work for the all-at-once approach or something.  Someone in the @trilinos/framework team will need to look into this.

**Comment by prwolfe** [comment]
I did some digging.

- Previously we were not building PyTrilinos for the clean builds
- Currently we are setting PyTrilinos to disabled.
- Something is overriding that and setting Trillions_ENABLE_ALL_PACKAGES=ON (I did not find this)

We do have modules to give us swig and bumpy if we want to be building this, but I expect this is just because we went to all-at-once instead of the multiple configures and builds. That said I don't see where the variable comes from but the note in the log says

> Setting Trilinos_ENABLE_ALL_PACKAGES=ON since Trilinos_PACKAGES_USER_SELECTED=''

so it's happening in test before we get to cmake (it's on the make command line).

**Comment by bartlettroscoe** [comment]
@prwolfe, can you point me to the Jenkins driver jobs for these builds?  If I can see the TRIBITS_CTEST_DRIVER() output I can see what is happening.  Also, where does that driver code live for these "Clean" builds?

**Comment by prwolfe** [comment]
Jenkins is at https://ascic-jenkins.sandia.gov/job/trilinos-folder/job/Trilinos_generic_nightly/, but these are triggered by a pipeline.
The driver called is cmake/ctest/drivers/parameterized/ctest_linux_nightly_generic.cmake

**Comment by bartlettroscoe** [comment]
> Jenkins is at https://ascic-jenkins.sandia.gov/job/trilinos-folder/job/Trilinos_generic_nightly/, but these are triggered by a pipeline.

How do you tell which job output corresponds to the "Clean" builds?  All of those builds have time stamps of yesterday.

**Comment by prwolfe** [comment]
Only 7 of them are from yesterday - I just dig a bit. 3662 3659 and 3657 were the clean builds from last night.

**Comment by bartlettroscoe** [comment]
From looking at:

* https://ascic-jenkins.sandia.gov/job/trilinos-folder/job/Trilinos_generic_nightly/3662/console

I think this is a bug in `TRIBITS_CTEST_DRIVER()` for the all-at-once approach.  It needs to explicitly set disables for the list of packages provided in `${PROJECT_NAME}_EXCLUDE_PACKAGES` when enabling all of the packages (i.e. the black-list approach instead of the white-list approach).  This is a use case that I must not have tested.  I will add unit tests for this use case in TriBITS, fix the code, and then create a Trilinos PR with the updated snapshot of TriBITS.

**Comment by bartlettroscoe** [comment]
FYI: https://github.com/TriBITSPub/TriBITS/issues/269

**Comment by prwolfe** [comment]
@william76 - just an FYI as I know you are working the PyTrilinos showing up in clean issue from the other direction.

**Comment by william76** [comment]
@prwolfe 
Thanks, I haven't really had much time to look at it today...

It looks like fixing the issue in TriBITS that @bartlettroscoe mentioned above should fix it...?

**Comment by bartlettroscoe** [comment]
> It looks like fixing the issue in TriBITS that @bartlettroscoe mentioned above should fix it...?

PR #3610 should fix this.

@prwolfe and @william76, if one of you can approve PR #3610, then after PR testing passes (hopefully with no random failures), then it will merge automatically later tonight and should then be in place for testing tomorrow.

**Comment by bartlettroscoe** [comment]
@trilinos/framework 

FYI: The PR #3610 was auto-merged last night (after the first PR testing iteration!) and today the "Clean" builds are 100% passing as shown [here](https://testing.sandia.gov/cdash-dev-view/index.php?project=Trilinos&date=2018-10-12&filtercount=1&showfilters=1&field1=groupname&compare1=61&value1=Clean).

I noticed that a one other build [today](https://testing.sandia.gov/cdash-dev-view/index.php?project=Trilinos&date=2018-10-12&filtercount=1&showfilters=1&field1=site&compare1=63&value1=) is now behaving differently with the all-at-once mode.  The build `Linux-GCC-4.9.3-openmpi-1.8.7_Debug_DEV_Werror` posting the the "Experimental" CDash group shown at:

* https://testing.sandia.gov/cdash-dev-view/viewConfigure.php?buildid=4042789

is failing to configure with a Sundance configure failure.  Before, Sundance was also failing to configure but since this build was using the package-by-package approach, that error did not occur until Sundance was processed.  But now with all of the packages being configured together, this single configure failure brings down all of the builds for all of the packages.  To fix this, I will just remove Sundance from the list of extra repos that are pulled in.

The other configure failures showing up today so far look to have nothing to do with CMake version or the all-at-once mode change.

All of this looks good to me.  Can we close this issue?

**Comment by bartlettroscoe** [comment]
@trilinos/framework 

I have not heard of any issue recently about this upgrade of the minimum version of CMake to 3.10.0.  Therefore, I think it is safe to close this issue.
