### ISSUE TITLE
Tpetra BCRS: Replace LittleBlock and LittleVector with unmanaged LayoutRight Kokkos::View

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#177]
@trilinos/tpetra @trilinos/ifpack2 
@crtrott @kyungjoo-kim @amklinv 

In Tpetra::Experimental::BlockCrsMatrix, replace LittleBlock and LittleVector with *unmanaged* LayoutRight `Kokkos::View` (of rank 2 resp. 1).  Please retain the typedefs little_block_type, const_little_block_type, little_vec_type, and const_little_vec_type, but use `Kokkos::View` for these instead of LittleBlock resp. LittleVector.

You _must_ use LayoutRight, because users' code explicitly assumes LayoutRight.  Later we can relax this assumption, but for now please retain it.  Please specify LayoutRight explicitly in the View types, because otherwise it will have the wrong layout with Cuda (whose default layout is LayoutLeft).

Please note that this will affect Ifpack2 as well as Sierra Aero (please contact the relevant developers of the latter to ensure that we don't break their code).  Some Ifpack2 solvers (in particular, block ILU(k)) use these classes and depend on the particular form of their constructors.  For example, LittleBlock's constructor takes two strides -- a row stride and a column stride.  Thus, this is not an entirely trivial change in Ifpack2.  However, all use of these classes in Tpetra and Ifpack2 assumes unit-stride LittleVector and row-major LittleBlock, so you may make this assumption when modifying code.

These changes will have the following beneficial effects:

1. Less code to compile (four classes per (Scalar, LocalOrdinal) combination, as well as templated BLAS 1, 2, and 3 functions)
2. Simplify transition of Tpetra BlockCrsMatrix to a completely Kokkos-based implementation, thus facilitating good manycore performance 

They incur the risk of slightly more struct copy overhead (`Kokkos::View` has a bit more state than LittleBlock and LittleVector) in computational kernels, but kernels might not want to pass structs around anyway for best performance.

**Comment by crtrott** [comment]
I am working on this. From what I can see the three things which change are:

(i) no stride support at the moment (but stride 1 is hardcoded in all kinds of places)
(ii) getRawPtr() doesn't exist as member function anymore and must be replaced by ptr_on_device()
(iii) getBlockSize() goes away and must be replaced by dimension_0()
(iv) the constructor changes from (ptr,blocksize,stride) to (ptr,blocksize).

I got the Tpetra tests passing with this change. You can look at the changes in the ct branch on crtrott/Trilinos. I will do a merge request against crtrott/Trilinos/master when I have the ifpack2 issues resolved.

**Comment by mhoemmen** [comment]
> (i) no stride support at the moment (but stride 1 is hardcoded in all kinds of places)

That's OK.  Sierra Aero probably assumes unit stride if it uses LittleBlock at all.

> (iv) the constructor changes from (ptr,blocksize,stride) to (ptr,blocksize).

Watch this one -- it may be _syntactically_ correct to pass extra arguments into Kokkos::View's constructor, but they get ignored.  That may lead to tricky bugs later if we change the current layout.

> I will do a merge request against crtrott/Trilinos/master when I have the ifpack2 issues resolved.

Talk to Sierra Aero first.  They may depend on LittleBlock, and/or depend on the little_block_type / little_vector_type typedefs to have the old constructors and methods.  Also, if you need help with Ifpack2 block ILU(k), @jhu, @aprokop, and @csiefer2 know about it.  It should be a tedious but straightforward code replacement job for now.

**Comment by mhoemmen** [comment]
I removed the "help wanted" tag, because the bug is assigned.

**Comment by crtrott** [comment]
I pushed the changes to Ifpack2 to the ct branch. With that all of LittleVector usage is removed except in the unit test which tests LittleVector. Next I'll do LittleBlock.

**Comment by crtrott** [comment]
Ok I removed LittleBlock usage as well. This should address this issue inside of Trilinos. Now we need to make sure it works in Sparc/Aero.

**Comment by mhoemmen** [comment]
> Now we need to make sure it works in Sparc/Aero.

The former doesn't actually use LittleBlock or LittleVector.  Both, however, assume that the input of replace / sumInto is row-major.

**Comment by mhoemmen** [comment]
@crtrott -- thanks so much for working on this!  Does this actually close the issue here in Trilinos?

**Comment by mhoemmen** [comment]
@crtrott @amklinv Still working on this.  @crtrott 's patch causes the Ifpack2 RBILUK unit tests to fail.  That's probably RBILUK's fault for not doing fences for UVM happiness.  I'm working on diagnosing the issue.

**Comment by mhoemmen** [comment]
I think I get what's wrong.  Ifpack2 RBILUK compute() has some code that worked with LittleBlock and LittleVector, where it uses these classes to wrap (in a way comparable to Kokkos::MemoryUnmanaged) a Teuchos::Array (of host memory -- a temporary workspace).  The problem is that little_block_type etc. are now Kokkos::View with the device's memory space.  Thus, wrapping a Teuchos::Array won't work.  In particular, the Kokkos::deep_copy complains bitterly (throws std::runtime_error).  It rightfully should, since the data don't actually live in the claimed memory space.

Possible fixes:
  1. Use an actual owning Kokkos::View, instead of trying to wrap Teuchos::Array host memory
  2. Use Tpetra::Experimental::COPY instead of Kokkos::deep_copy

The second proposed fix is a hack, because the memory space lies in this case.  I'll try the first.

**Comment by mhoemmen** [comment]
The first proposed fix worked!  I'll work on getting that into the commit.

**Comment by mhoemmen** [comment]
@amklinv @crtrott I got the changes integrated in.  I'm running the check-in tests with CUDA now.
