### ISSUE TITLE
Tpetra: Create methods to test runtime sized scalar types

### ISSUE THREAD

**Issue by tjfulle** [trilinos/Trilinos#1770]
This issue is to discuss and implement methods to test runtime sized scalar types as used in @trilinos/stokhos, without having to build all the way through to Stokhos.

@trilinos/tpetra 
@mhoemmen 
@etphipp

**Comment by mhoemmen** [comment]
@tjfulle suggested creating a "fake Stokhos" Scalar type that has run-time size, say using `std::vector`.  We only need it for tests, so we don't have to add it to the ETI system; we could just do the instantiations by hand for the tests that need them.

**Comment by mhoemmen** [comment]
@etphipp The only issue with my above suggestion is that we might need some kind of `Kokkos::View` specializations to handle the run-time Scalar type.

**Comment by etphipp** [comment]
We could also move the Stokhos scalar types into another package with minimal dependencies that you could use directly in Tpetra tests.

**Comment by etphipp** [comment]
Actually, come to think of it, that probably won't work since the dynamically sized scalar type depends on other things in Stokhos.

**Comment by etphipp** [comment]
For whatever scalar type you use, you shouldn't technically need a View specialization.  It will just be wicked slow if you don't have one, and you will be limited in how large of view's you can allocate on the GPU.

**Comment by etphipp** [comment]
Sacado's DFad is a dynamically sized scalar type that could be used as well.  Sacado only has dependencies on Teuchos and Kokkos.

**Comment by tjfulle** [comment]
Minimally, Tpetra should test the capability, otherwise the capability is a bug according to item 2 in the [Trilinos Testing Policy](https://github.com/trilinos/Trilinos/wiki/Trilinos-Testing-Policy).

**Comment by mhoemmen** [comment]
@etphipp wrote:
> Sacado's DFad is a dynamically sized scalar type that could be used as well. Sacado only has dependencies on Teuchos and Kokkos.

Would it be weird for Tpetra to have an optional test dependency on Sacado?

**Comment by mhoemmen** [comment]
@etphipp Just to clarify: If I remember right, Stokhos does all the instantiations and testing for Tpetra and downstream solver packages, for both Sacado and Stokhos Scalar types.  Is that right?  If so, then that might make it hard for Tpetra to depend optionally on Sacado.

**Comment by etphipp** [comment]
No, that's not exactly right.  Stokhos does all instantiations and testing for Tpetra and downstream packages for Stokhos scalar types.  There currently is no use of Sacado scalar types in Tpetra (or downstream), although there could be.  It just isn't something a customer has needed.

**Comment by mhoemmen** [comment]
@etphipp Would you object to us adding an optional test dependency of Tpetra on Sacado, so that Tpetra can test with Sacado Scalar types?

**Comment by etphipp** [comment]
Sure, that would be fine.

**Comment by tjfulle** [comment]
@etphipp, if Sacado was an optional test dependency, are there tests in `Stokhos_TpetraCrsMatrixUQPCEUnitTest.hpp` that can be copied to Tpetra with minimal modification?  Tests like `VectorAdd`, `VectorDot`, `MatrixVectorMultiply`, etc. don't seem to use anything in the Stokhos namespace - except that each uses the function `build_cijk` which does (use stuff from the Stokhos namespace).  If `build_cijk` could be modified to not use Stokhos (for these specialized tests), it seems they could be copied over to Tpetra.

**Comment by mhoemmen** [comment]
@tjfulle , @etphipp , and I had a meeting this past week to discuss this issue.  @etphipp suggested a temporary work-around to reduce test turn-around time:

  - Set `Stokhos_ENABLE_MueLu:BOOL=OFF` to disable MueLu instantiations in Stokhos, which take much of the build time
  - Disable the `MP::Vector` instantiations, which take a long time (because there are multiple Scalar types, one for each compile-time length)

We agreed to take this approach for now.  In the long term, @etphipp said that it should be possible to rearrange dependencies so that Tpetra depends optionally on Sacado.  That way, Tpetra could test Sacado types without needing to wait on all the downstream package instantiations.

**Comment by tjfulle** [comment]
Thanks for the summary @mhoemmen!  Should we close this, or maybe change the status to backlog?

**Comment by mhoemmen** [comment]
@tjfulle I changed its status to "Tpetra-backlog".  Let's leave it open for now.  (It's OK for some issues to stay open for a while.)  I wouldn't call this a SART issue necessarily, so I'm not sure if it belongs on the backlog there.  Thanks!
