### ISSUE TITLE
"make install" no longer appears to install TrilinosConfig.cmake

### ISSUE THREAD

**Issue by etphipp** [trilinos/Trilinos#1774]
It appears to me that "make install" no longer installs TrilinosConfig.cmake in install_path/lib/cmake/Trilinos as it used to.  In that directory I only have a file called TrilinosConfigVersion.cmake.  Is this intentional somehow?  How are users of Trilinos supposed to link Trilinos into their application with cmake?

**Comment by etphipp** [comment]
Never mind.  This was caused by "user error".

**Comment by bmpersc** [comment]
@trilinos/framework 
@etphipp that is not intentional. Those files should be getting installed. The approved and expected method to link Trilinos would be to use the cmake find_package(...) or the makefile includes.
