### ISSUE TITLE
Stokhos: Failing test in CUDA build

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#1776]
@trilinos/stokhos @trilinos/tpetra 

This is a summary of some e-mails I've been exchanging with @etphipp .

The `Stokhos_TpetraCrsMatrixUQPCEUnitTest_Cuda` fails (in a CUDA build only).

When I ran cuda-gdb on this test with a single MPI process, I got this:
```
0. Tpetra_CrsMatrix_PCE_DS_int_int_CudaWrapperNode_VectorAdd_UnitTest ... [Passed] (0.0738 sec)
1. Tpetra_CrsMatrix_PCE_DS_int_int_CudaWrapperNode_VectorDot_UnitTest ... [Passed] (0.0426 sec)
2. Tpetra_CrsMatrix_PCE_DS_int_int_CudaWrapperNode_MultiVectorAdd_UnitTest ... [Passed] (0.0501 sec)
3. Tpetra_CrsMatrix_PCE_DS_int_int_CudaWrapperNode_MultiVectorDot_UnitTest ... [Passed] (0.0385 sec)
4. Tpetra_CrsMatrix_PCE_DS_int_int_CudaWrapperNode_MultiVectorDotSub_UnitTest ... [Passed] (0.0373 sec)
5. Tpetra_CrsMatrix_PCE_DS_int_int_CudaWrapperNode_MatrixVectorMultiply_UnitTest ... [Passed] (0.0911 sec)
6. Tpetra_CrsMatrix_PCE_DS_int_int_CudaWrapperNode_MatrixMultiVectorMultiply_UnitTest ... [Passed] (0.0957 sec)
7. Tpetra_CrsMatrix_PCE_DS_int_int_CudaWrapperNode_Flatten_UnitTest ...
Program received signal SIGBUS, Bus error.
0x00000000007e3dd1 in Stokhos::create_flat_map<int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Cuda, Kokkos::CudaUVMSpace> > (map=..., block_size=10)
    at /scratch/prj/Trilinos/Trilinos/packages/stokhos/src/sacado/kokkos/vector/tpetra/Stokhos_Tpetra_Utilities_MP_Vector.hpp:81
81              flat_element_list[i*block_size+j] = element_list[i]*block_size+j;
```
Here, `element_list` is the result of `Tpetra::Map::getNodeElementList()`.  That is _supposed_ to return host memory, but it actually returns a `HostMirror` of a `CudaUVMSpace` View, which is (surprise!) `CudaUVMSpace` View.

When I fixed that issue (#1775), the test got a bit further:
```
0. Tpetra_CrsMatrix_PCE_DS_int_int_CudaWrapperNode_VectorAdd_UnitTest ... [Passed] (0.0611 sec)
1. Tpetra_CrsMatrix_PCE_DS_int_int_CudaWrapperNode_VectorDot_UnitTest ... [Passed] (0.0395 sec)
2. Tpetra_CrsMatrix_PCE_DS_int_int_CudaWrapperNode_MultiVectorAdd_UnitTest ... [Passed] (0.049 sec)
3. Tpetra_CrsMatrix_PCE_DS_int_int_CudaWrapperNode_MultiVectorDot_UnitTest ... [Passed] (0.0372 sec)
4. Tpetra_CrsMatrix_PCE_DS_int_int_CudaWrapperNode_MultiVectorDotSub_UnitTest ... [Passed] (0.0365 sec)
5. Tpetra_CrsMatrix_PCE_DS_int_int_CudaWrapperNode_MatrixVectorMultiply_UnitTest ... [Passed] (0.0886 sec)
6. Tpetra_CrsMatrix_PCE_DS_int_int_CudaWrapperNode_MatrixMultiVectorMultiply_UnitTest ... [Passed] (0.0942 sec)
7. Tpetra_CrsMatrix_PCE_DS_int_int_CudaWrapperNode_Flatten_UnitTest ... [Passed] (0.202 sec)
8. Tpetra_CrsMatrix_PCE_DS_int_int_CudaWrapperNode_SimpleCG_UnitTest ... [Passed] (3.33 sec)
9. Tpetra_CrsMatrix_PCE_DS_int_int_CudaWrapperNode_SimplePCG_Muelu_UnitTest ...
CUDA Exception: Warp Out-of-range Address

Program received signal CUDA_EXCEPTION_5, Warp Out-of-range Address.
[Switching focus to CUDA kernel 0, grid 1277, block (0,0,0), thread (0,0,0), device 0, sm 14, warp 0, lane 0]
0x000000001b12d980 in void Kokkos::Impl::cuda_parallel_launch_local_memory<Kokkos::Impl::ParallelFor<Tpetra::Details::Blas::Impl::Fill<Kokkos::View<Sacado::UQ::PCE<Stokhos::DynamicStorage<int, double, Kokkos::Cuda> >**, Kokkos::LayoutLeft, Kokkos::Cuda, void>, Sacado::UQ::PCE<Stokhos::DynamicStorage<int, double, Kokkos::Cuda> >, Kokkos::Cuda, int, 2>, Kokkos::RangePolicy<Kokkos::Cuda, int>, Kokkos::Cuda>, 1024u, 1u>(Kokkos::Impl::ParallelFor<Tpetra::Details::Blas::Impl::Fill<Kokkos::View<Sacado::UQ::PCE<Stokhos::DynamicStorage<int, double, Kokkos::Cuda> >**, Kokkos::LayoutLeft, Kokkos::Cuda, void>, Sacado::UQ::PCE<Stokhos::DynamicStorage<int, double, Kokkos::Cuda> >, Kokkos::Cuda, int, 2>, Kokkos::RangePolicy<Kokkos::Cuda, int>, Kokkos::Cuda>)<<<(1,1,1),(1,256,1)>>> ()
```

`Tpetra::Details::Blas::fill` does _not_ do `Kokkos::deep_copy(X,alpha)` (because @jjellio reported thread scaling issues when it did).  Instead, it uses a custom functor.  Line 151 of `tpetra/core/src/Tpetra_Details_fill.hpp` actually does the assignment of `alpha` to `X(i,j)`.

I'm not sure what happens in that assignment if `alpha` does not have the same run-time size as `X(i,j)` (some Stokhos Scalar types have run-time size).

**Comment by etphipp** [comment]
The operator=() should handle that.  The likely case is that X is not dimensioned correctly.

**Comment by mhoemmen** [comment]
@etphipp wrote:
> The likely case is that X is not dimensioned correctly.

How can I check this in a generic way?  Would I need to write a trait class for the run-time dimension of a Scalar type?

**Comment by mhoemmen** [comment]
@etphipp Ah, `Sacado::UQ::PCE` has a `size()` method.  I can write a trait class for this (or just use PackTraits, already in Tpetra).

**Comment by etphipp** [comment]
Hold on, let's just figure out what is wrong first.  A traits class or specialization shouldn't be necessary.

**Comment by etphipp** [comment]
How are you getting cuda-gdb to stop at this error?  When I run it in cuda-gdb it goes right past it.  With cuda-memcheck it prints the error, but doesn't stop.

**Comment by mhoemmen** [comment]
@etphipp I did an `MPI_DEBUG` build and set the CMake options `Kokkos_ENABLE_DEBUG:BOOL=ON` and `Teuchos_ENABLE_DEBUG:BOOL=ON`.  The Kokkos option may make some effort at catching CUDA kernel issues.

**Comment by etphipp** [comment]
I believe I figured out what is going wrong.  I have a fix committed to my local clone and the checkin test script is running for the push.  My fix creates specializations for the fill() function for UQ::PCE and MP::Vector scalar types.  It fixes the correctness issue here for UQ::PCE and also will improve performance for both scalar types.

It is bothersome that a specialization for such a simple kernel is needed for the UQ::PCE scalar type, but is due to how I handle the constant (alpha in this case).  The way I'm doing that really isn't safe and I should probably take the special logic there.

**Comment by jjellio** [comment]
@mhoemmen I have some updated data regarding Scale and Fill.

I need to digest it though. It looks like a HT issue. As for putScalar vs Scale, I now have data for four cases:

fill w/zero
fill w/a random scalar (not one or zero)
scale w/one
scale w/a random scalar (not one or zero)

Scale (MKL scal) was optimizing the case of scaling by 1.0 (giving excellent performance)
Scale given non trivial floating point values  is similar in performance to fill, but scale is still out performing it for large data. HTs are also an issue

I have *not* pulled your patch. I am still in the base line phase, but I have made substantial progress on KNL reproducibility that I will present in the near future.

**Comment by mhoemmen** [comment]
@etphipp I'm curious why `Kokkos::deep_copy(X,alpha)` works, but the `Fill` functor does not.  My guess is that you've overloaded `Kokkos::deep_copy`'s back-end to do the right thing :-) .

**Comment by mhoemmen** [comment]
@jjellio wrote:
> Scale (MKL scal) was optimizing the case of scaling by 1.0 (giving excellent performance)

`KokkosBlas::scal` may not necessarily optimize fully for this case.  See here:

https://github.com/trilinos/Trilinos/blob/6fe9075113212ca8f70bdbb4418865955307474c/packages/kokkos-kernels/src/blas/impl/KokkosBlas1_scal_impl.hpp#L111

The kernel is correct for `alpha = 1`, but it does an assignment that the compiler may not know to optimize out.

**Comment by mhoemmen** [comment]
@etphipp Does your commit to develop make the Stokhos test in question pass with CUDA for you?  Thanks for working on this! :-)

**Comment by etphipp** [comment]
According to my testing, it makes the test in question pass on CUDA.  It works because I already have an overload of deep_copy() that does the right thing.

**Comment by etphipp** [comment]
I should add an overload that takes the execution space as an argument though.

**Comment by mhoemmen** [comment]
@etphipp 's commit fixed the issue in develop; yay! :-D

**Comment by mhoemmen** [comment]
@etphipp wrote:
> I should add an overload that takes the execution space as an argument though.

This is now issue #1778 :-) .
