### ISSUE TITLE
Shylu Tacho required test dependence on metis causing configure errors

### ISSUE THREAD

**Issue by bmpersc** [trilinos/Trilinos#1780]
@trilinos/shylu @kyungjoo-kim The recent changes to ShyLU Tacho to require metis for tests is causing configure errors in our clean testing. The reason why is that we currently don't have a metis to build against on those machines. I noticed that metis was only an optional dependency for the library so I'm wondering if this being required for tests was just an oversight or if it really is necessary for all the Tacho tests at this point.

**Comment by srajama1** [comment]
Can metis be added to that machine ?

**Comment by kyungjoo-kim** [comment]
@bmpersc  You are right. In the code, the test can proceed without metis. In that case, it uses amd provided by trilinos-ss package (cholmod). When metis is available, metis gets used first.

The reason that we put metis as required tpl is because tacho performs best with metis and all performance benchmark is done with metis. This cause less confusion when someone reproduces the same performance test (for example, in sierra build, I can make sure they also use metis with tacho).

So, it is okay to put metis as optional dependence but I would like to put it as a required tpl for the case that other research groups test tacho to reproduce the performance.

**Comment by srajama1** [comment]
What you want is required for testing performance. This is what required dependence is supposed to do. I believe that is fine. 

We can turn the performance test off if metis is not present. However, it would be better to install metis so we keep track of performance. I would like this to be integrated w/ the framework developed my @MicheldeMessieres for performance testing.

**Comment by bmpersc** [comment]
@srajama1 we can add metis, but that would take longer than I'd be okay with leaving this configure error for. There is also the issue that we really can't even look into doing that until next week due to other priorities, IE the 12.12. release.

**Comment by bmpersc** [comment]
@srajama1 @kyungjoo-kim would a good immediate path forward be to make metis an optional test dependency and disable the performance test(s) when metis is not available as you suggest. Followed by us getting metis available for the nightly testing so that we can have the performance tests run as part of the nightly testing? That would solve the immediate issue of the test failures and provide a path forward for the long term.

**Comment by kyungjoo-kim** [comment]
@bmpersc okay. I will change it as optional dependence. Let me know when metis is available in the test machine later.

**Comment by srajama1** [comment]
@bmpersc : When we say long term, especially for performance tests, it has always been put in the back burner. How about leaving the tests failing as a reminder ?

**Comment by bmpersc** [comment]
@srajama1 that really isn't an option as this is failing on the clean builds. Those really can't have a reminder failure in them. I will file a ticket so we can at least have that much accountability and then I guess I'd ask you to keep our feet to the fire on this so we don't let it sit forever.

**Comment by kyungjoo-kim** [comment]
@bmpersc Now the metis is optional. Please test the clean build and let me know if you still have a problem.

**Comment by bmpersc** [comment]
@kyungjoo-kim Things have been working since your change so I would say this is fixed. There is still the issue of adding metis and mtmetis as tpls, but that is being tracked else where so I am going to close this.
