### ISSUE TITLE
Add metis tpl to Trilinos testing

### ISSUE THREAD

**Issue by bmpersc** [trilinos/Trilinos#1782]
@trilinos/framework The @trilinos/shylu team needs metis to be a tpl for testing to be able to properly test all of their code. The lack of metis actually caused a configure error which was reported in ticket #1780. An immediate solution was to make the requirement of metis optional with the caveat that we would get a metis tpl setup so that we can eventually run the tests.

@trilinos/shylu can you provide the version of metis you would prefer to have available please?

**Comment by srajama1** [comment]
I would like this to be prioritized. Like I mentioned in #1780 I would rather not let this sit and we see a performance regression. Installing metis is quite easy. If you give us access to the machine, we can do it for the framework team.

@jwillenbring

**Comment by kyungjoo-kim** [comment]
The latest version of metis is 5.1.0. Would you please install mtmetis 0.6.0 (multithreaded metis) ? We do not use the multi-threaded version yet but it will be likely to be used very soon.

**Comment by bmpersc** [comment]
@srajama1, @kyungjoo-kim  The @trilinos/framework team just had a discussion about this and we decided that all of these TPLS are reasonable for us to provide. The question is will SEMS be willing to support some or all or will Trilinos need to do that. I will have a conversation with @dmvigi to see what SEMS is willing to do. After that we will have a much better idea of when these will be available.

**Comment by srajama1** [comment]
Checking to see the results of this conversation with @dmvigi

**Comment by bmpersc** [comment]
@srajama1, 
  I apologize for not responding sooner. I clearly recall writing a response to this on Monday, but apparently it didn't save properly. 

SEMS is willing to support these TPLs with the caveat that if they are issues in the build beyond simple things that SEMS will not support them. Basically if there are things like having to modify the makefiles or code SEMS doesn't want to support that. I am currently looking at these TPLs and I don't think that will be the case for most of the previously requested TPLS.

I do have two questions about how this interacts with the previous request to have umfpack installed. Looking at SuiteSparse there are interdependencies between umfpack and amd as well as what is reported to be a "modified" version of metis 5.1.0. First, I'm wondering if the version of metis in SuiteSparse would be an acceptable version or not? Second, I'm trying to decide if it makes sense to just install all of SuiteSparse and make modules for each piece separately. However, it is unclear if the interdependencies might cause issues for people wanting to use the parts separately. Do you have an opinion or insight on that concern?

**Comment by srajama1** [comment]
@bmpersc: I need to understand this question better. Let me talk to you Monday in person.

**Comment by bmpersc** [comment]
@srajama1, @dmvigi and I had a conversation about this and decided that we will install all of SuiteSparse minus metis, but give each of them separate modules.

**Comment by srajama1** [comment]
@bmpersc : Ping

**Comment by william76** [comment]
@srajama1 I checked in with @bmpersc and he said that SuiteSparse was set up and installed along with metis... I can see that they're on NFS using a `module avail` on a RHEL7 system as:
- `sems-SuiteSparse/5.3.0/base`
- `sems-metis/5.1.0/base`

Is that what was needed by this?  If that's sufficient to close this issue, would we also want to close out #1255 and #1826 too?

@bmpersc FYI

**Comment by srajama1** [comment]
We can check this in a nightly test by enabling the optional dependency and see if everything works. Can you enabe TPLs this to a nightly in Trilinos testing ? @william76   I really appreciate your quick follow up on these issues. As you can see it has been sitting there for quite a while.

**Comment by srajama1** [comment]
@trilinos/framework
