### ISSUE TITLE
MueLu: DefaultFactory Manager does weird stuff

### ISSUE THREAD

**Issue by csiefer2** [trilinos/Trilinos#1783]
... at least when interacting with BlockedCrsMatrix.

We should investigate.

**Comment by jhux2** [comment]
@trilinos/muelu

**Comment by aprokop** [comment]
A better description is required 😕

**Comment by csiefer2** [comment]
How about "I have to manually override almost every factory because the default management doesn't work" ?

**Comment by tawiesn** [comment]
@csiefer2 You know that you can create a new BlockedDefaultFactoryManager class. You do this once and you're good for the rest of your life. However, it's not clear what the defaults should be if you have different kinds of problems...
