### ISSUE TITLE
ShyLU: Build error in Tacho with complex enabled

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#1784]
@trilinos/shylu 

ZSYTRF takes 8 arguments; the code gives it 6 arguments.  I'm seeing this error with the MKL TPL enabled, but if you look at the code, it calls ZSYTRF in the same way when the MKL TPL is not enabled.  Here is the build error:
```
[ 20%] Building CXX object packages/shylu/tacho/core/example/CMakeFiles/Tacho_ExampleCholPardiso.dir/Tacho_ExampleCholPardiso.cpp.o
In file included from .../Trilinos/packages/shylu/tacho/core/example/Tacho_ExampleCholPardiso.cpp:10:
In file included from .../Trilinos/packages/shylu/tacho/core/src/TachoExp_NumericTools.hpp:14:
In file included from .../Trilinos/packages/shylu/tacho/core/src/TachoExp_Chol_External.hpp:8:
.../Trilinos/packages/shylu/tacho/core/src/TachoExp_Lapack_External.hpp:150:9: error: no matching function for call to 'csytrf_'
        F77_FUNC_CSYTRF(&uplo,
        ^~~~~~~~~~~~~~~
.../Trilinos/packages/shylu/tacho/core/src/TachoExp_Lapack_External.hpp:64:25: note: expanded from macro 'F77_FUNC_CSYTRF'
#define F77_FUNC_CSYTRF F77_BLAS_MANGLE(csytrf,CSYTRF)
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.../Trilinos/CHECKIN-CLANG-3.9.0/MPI_DEBUG/packages/shylu/tacho/core/src/ShyLUTacho_config.h:35:37: note: expanded from macro 'F77_BLAS_MANGLE'
# define F77_BLAS_MANGLE(name,NAME) name ## _
                                    ^~~~~~~~~
<scratch space>:141:1: note: expanded from here
csytrf_
^~~~~~~
.../intel/mkl/include/mkl_lapack.h:7532:6: note: candidate function not viable: requires 8 arguments, but 6 were provided
void csytrf_( const char* uplo, const MKL_INT* n, MKL_Complex8* a,
     ^
In file included from .../Trilinos/packages/shylu/tacho/core/example/Tacho_ExampleCholPardiso.cpp:10:
In file included from .../Trilinos/packages/shylu/tacho/core/src/TachoExp_NumericTools.hpp:14:
In file included from .../Trilinos/packages/shylu/tacho/core/src/TachoExp_Chol_External.hpp:8:
.../Trilinos/packages/shylu/tacho/core/src/TachoExp_Lapack_External.hpp:192:9: error: no matching function for call to 'zsytrf_'
        F77_FUNC_ZSYTRF(&uplo,
        ^~~~~~~~~~~~~~~
.../Trilinos/packages/shylu/tacho/core/src/TachoExp_Lapack_External.hpp:65:25: note: expanded from macro 'F77_FUNC_ZSYTRF'
#define F77_FUNC_ZSYTRF F77_BLAS_MANGLE(zsytrf,ZSYTRF)
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.../Trilinos/CHECKIN-CLANG-3.9.0/MPI_DEBUG/packages/shylu/tacho/core/src/ShyLUTacho_config.h:35:37: note: expanded from macro 'F77_BLAS_MANGLE'
# define F77_BLAS_MANGLE(name,NAME) name ## _
                                    ^~~~~~~~~
<scratch space>:141:1: note: expanded from here
zsytrf_
^~~~~~~
.../intel/mkl/include/mkl_lapack.h:26436:6: note: candidate function not viable: requires 8 arguments, but 6 were provided
void zsytrf_( const char* uplo, const MKL_INT* n, MKL_Complex16* a,
     ^
2 errors generated.
```

**Comment by kyungjoo-kim** [comment]
How do you get this error ? The LDL factorization is a place holder for my future work and it is not used anywhere in Tacho nor Trilinos.

**Comment by kyungjoo-kim** [comment]
Could you try again ?

**Comment by mhoemmen** [comment]
@kyungjoo-kim wrote:
> How do you get this error ?

I enabled all packages forward of Tpetra, regardless of their PT, ST, EX status.  I also enabled the MKL TPL, though it should not matter in this case.

The only reason it should compile with the MKL TPL disabled, is because the extern declaration of the LAPACK function is wrong and matches how you were calling the function.  When the MKL TPL is enabled, MKL's header file gets included, which catches the syntax issue.

**Comment by kyungjoo-kim** [comment]
@mhoemmen  Does the commit fix the problem ?

**Comment by mhoemmen** [comment]
I get this CMake error now:
```
-- Configuring done
CMake Error: install(EXPORT "Amesos2" ...) includes target "amesos2" which requires target "shylutacho" that is not in the export set.
```

**Comment by kyungjoo-kim** [comment]
@bmpersc @jwillenbring @bartlettroscoe 

I also saw the same error when using check-in-script. In my case, I enable secondary tests as Tacho is "ST". If you are testing "PT" without "ST" enabled and see this error, it is a bit more weird as Tacho should be disabled. In my code, the script reports it as an error but build directory is successfully created. 

We probably need to figure out this more.

**Comment by mhoemmen** [comment]
@kyungjoo-kim I test everything downstream of Tpetra; this includes PT, ST, and EX packages.  Oddly enough, the build works fine.  It looks like you fixed the Tacho build issue.

**Comment by mhoemmen** [comment]
@kyungjoo-kim Amesos2 is PT, but it has an optional library dependency on ShyLUTacho, which is ST.  Is that OK?  Can PT packages depend optionally on non-PT packages?

**Comment by kyungjoo-kim** [comment]
@mhoemmen I think that it should be okay. That is what "optional" mean in my opinion but I do not know if that is feasible or not. @srajama1 However, Amesos2 has dependence on several shylu subpackages on EX and ST state e.g., Basker. So, it should be fine. 

Yes, I fixed the compiling issue on Tacho due to the mismatched function declaration. The cmake error is weird.

**Comment by srajama1** [comment]
@bartlettroscoe : Can you comment on couple of issues raised above. 

Can PT packages depend on non-PT packages ? I guess the answer is Yes. We have dependencies to even EX already there so this should work.

There is also the weird configure error that I have no idea what it is. May be that should be a separate issue.

**Comment by mhoemmen** [comment]
@kyungjoo-kim I'll open a separate issue for the CMake error, and close this one.  Thanks for the fix! :-)

**Comment by mhoemmen** [comment]
@kyungjoo-kim I opened a new issue, #1788, for the CMake error.  Thanks!

**Comment by bartlettroscoe** [comment]
> Can PT packages depend optionally on non-PT packages?

Yes.  See:

* https://tribits.org/doc/TribitsDevelopersGuide.html#tribits-dependency-handling-behaviors

What is means is that an PT package can have parts that depend on non-PT SE packages and TPLs that are not of the highest priority to be tested.  So in our CI build, for example, non-PT SE packages and TPLs are are disabled.  But in Nightly builds, we enable all ST packages and code so we get a broader set of testing.  We never enable EX packages in any offical automated testing going to the "Clean" or "Nightly" dashboard.  But anyone can set up extra "Specialized" builds to test anything they want, including EX SE Packages.  But all of this needs to be document (i.e. we need to get #1293 done).

But for the standard CI build, only PT code is allowed.  (By definition, all PT SE Packages and TPLs are turned on for the standard CI build.  That is the definition of PT SE packages and TPLs in Triinos.)

NOTE: Do not confuse the testing category (PT, ST, EX) with the maturity of the code (which we have not codified yet in the TriBITS system).  See:

* http://trac.trilinos.org/wiki/TribitsLifecycleModelOverview
