### ISSUE TITLE
Tpetra does not compile if Kokkos::Serial is disabled.

### ISSUE THREAD

**Issue by etphipp** [trilinos/Trilinos#1786]
If Kokkos::Serial is disabled (via -D Kokkos_ENABLE_Serial=OFF) then Tpetra fails to compile:

```
/home/etphipp/project/Trilinos/Trilinos/packages/tpetra/core/src/Tpetra_Details_fill.hpp(180): error: namespace "Kokkos" has no member "Serial"
              Kokkos::Serial,
```
@trilinos/tpetra

**Comment by jhux2** [comment]
@etphipp I think @mhoemmen is fixing this now.  @rstumin reported the same thing.

**Comment by mhoemmen** [comment]
@jhux2 It would be really nice if we could let Kokkos enable `Kokkos::Serial` but set `Tpetra_INST_SERIAL=OFF`.  Unfortunately, MueLu doesn't seem to build in that  case :-) .

**Comment by mhoemmen** [comment]
Commit 9ee61e8f10e145d80d0eb2a36a94d76c0e05f134 fixes this.

**Comment by aprokop** [comment]
> It would be really nice if we could let Kokkos enable Kokkos::Serial but set Tpetra_INST_SERIAL=OFF. Unfortunately, MueLu doesn't seem to build in that case :-) .

@mhoemmen Could you elaborate on that? I think there are CDash tests that disable Tpetra's Serial instantiation. Like [this](https://testing.sandia.gov/cdash/buildSummary.php?buildid=3129870).

**Comment by mhoemmen** [comment]
@aprokop I'll try it again and see if it still gives me trouble.

**Comment by mhoemmen** [comment]
@aprokop I'm having network troubles or I'd test it tonight.  Not sure what's up....

**Comment by mhoemmen** [comment]
@aprokop I remember now!  It was #1574 .  I'm testing now on my workstation; I'll try again on ride pretty soon (will need to do so for other issues).

**Comment by mhoemmen** [comment]
@aprokop It breaks, but because I have `GO=int` turned off; `muelu/test/unit_tests/MueLu_Test_ETI.hpp` expects the `double, int, int` instantiation (lines 114, 137, 139, and 141 should have `&&` instead of `||`).

**Comment by mhoemmen** [comment]
@aprokop Actually it's not so much about that, it's about `Xpetra::EpetraNode`.  The code appears to assume that Tpetra _always_ instantiates either for OpenMP or Serial.  I'll file a separate issue.

**Comment by mhoemmen** [comment]
@aprokop Again, never mind :-) .  I still get the link errors I see in #1574, no matter how I mess with `MueLu_Test_ETI.hpp`, even if I disable MueLu's tutorial.  I'll just give up and let y'all fix it if you want.

**Comment by aprokop** [comment]
@mhoemmen Do you have a link to the failing dashboard, or a configure script that you use?
