### ISSUE TITLE
Panzer not compiling once installed

### ISSUE THREAD

**Issue by bathmatt** [trilinos/Trilinos#1789]
2b7a0a7d packages/panzer/disc-fe/src/Panzer_IntrepidBasisFactory.hpp (Mauro Perego       2017-09-26 17:17:11 -0600  50) #include "../../../intrepid2/refactor/src/Discretization/Basis/Intrepid2_HVOL_C0_FEM.hpp"

Once trilinos is installed you can no longer do a direct include of a path in Trillions

Pull request 1777 messed this up. 

Can we fix asap

@eric-c-cyr @rppawlo @mperego

**Comment by mperego** [comment]
@bathmatt Argh.. sorry. that's Eclipse that messed it up and I did not noticed it. I'll fix this in a moment.

**Comment by jmgate** [comment]
@mperego, @bathmatt is pushing a fix already.

**Comment by bathmatt** [comment]
I think I just pushed a fix
   0b86201..427e01d  develop -> develop

**Comment by mperego** [comment]
@bathmatt @jmgate   Thanks! sorry about that.

**Comment by jmgate** [comment]
@bathmatt, did your push fix this?  Can we close?

**Comment by jmgate** [comment]
@bathmatt, just curious, but are you replying to notification emails and those replies aren't making it back to GitHub issues?  Closing&hellip;
