### ISSUE TITLE
provide xz release tarballs

### ISSUE THREAD

**Issue by nschloe** [trilinos/Trilinos#1792]
First of all congratulations on the 12.12.1 release!

When I spotted the tarballs this morning in [the release folder](http://trilinos.csbsju.edu/download/files/) I wondered if you could provide xz-compressed tarballs instead of bzip2-compressed ones. xz has a higher compression ration and unpacks faster; for Trilinos 12.12.1, the file size goes down from **80MB (bz2)** to **63 MB (xz)**. xz has in fact obsoleted bzip2. The Linux kernel sources are distributed in gz and xz since 2013 (https://www.kernel.org/happy-new-year-and-good-bye-bzip2.html).

![1](https://user-images.githubusercontent.com/181628/31010953-f5e328c2-a50c-11e7-8a79-a55725a80db0.png)

![2](https://user-images.githubusercontent.com/181628/31010962-fa657c9c-a50c-11e7-9002-1ca6b17290ec.png)

(Images from https://www.rootusers.com/gzip-vs-bzip2-vs-xz-performance-comparison/.)

**Comment by ibaned** [comment]
@trilinos/framework
