### ISSUE TITLE
Parser code cannot parse simple example

### ISSUE THREAD

**Issue by bathmatt** [trilinos/Trilinos#1794]
@ibaned 
it looks like there is some issues with the new parser stuff.

```
My Awesome Problem:
  Physics:
    eblock-0_0:
      Electrostatic:

  User Data:
    Random Key: 123456789

```

doesn't seem to parse.  I get this

```
*********** Caught Exception: Begin Error Report ***********
error: Parser failure at line 6 column 3 of Langmuir.yaml
  User Data:
 ^
Expected one of {INDENT}
Got: DEDENT
Parser was in state 69
```
I can work to get this resolved if you'd like.  What do you need from me?

**Comment by ibaned** [comment]
The key `Electrostatic` has an empty value. This makes it ambiguous what the type is supposed to be. Is it an empty string Parameter? An empty ParameterList?

It seems this is allowed by YAML, the spec says "both the implicit key and the value following it may be empty". So at least I should document it as a difference between the Teuchos Language and the spec.

I need to know what type you expect Electrostatic to be in the ParameterList before I can consider how to resolve this.

**Comment by ibaned** [comment]
Via email @bathmatt explained that this translates to an empty parameterlist. Working to fix this in the code.

**Comment by ibaned** [comment]
PR #1799 should fix this

**Comment by ibaned** [comment]
As far as I know this particular issue (parameter with empty value should be an empty ParameterList) should be fixed now.
