### ISSUE TITLE
Trilinos build error on VS2017

### ISSUE THREAD

**Issue by yiyangzhang37** [trilinos/Trilinos#1795]
Hello guys. Not sure if this is the right place to post such problems...

I am trying to build Trilinos on Windows 10 with VS2017. Things seem to be weird as I get a lot of errors like

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2065	'arg_data_ptr': undeclared identifier	kokkoscore	C:\ProgramData\Trilinos-master\packages\kokkos\core\src\impl\Kokkos_ViewMapping.hpp	2419	
```
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	C3646	'assign': unknown override specifier	kokkoscore	C:\ProgramData\Trilinos-master\packages\kokkos\core\src\impl\Kokkos_ViewMapping.hpp	2386
```	
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2668	'Kokkos::atomic_increment': ambiguous call to overloaded function	kokkoskernels	C:\ProgramData\Trilinos-master\packages\kokkos\core\src\impl\Kokkos_TaskQueue.hpp	229	
```
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2953	'Kokkos::Impl::FunctorAnalysis<PatternInterface,Policy,Functor>::has_final_function<F,>': class template has already been defined	kokkoskernels	C:\ProgramData\Trilinos-master\packages\kokkos\core\src\impl\Kokkos_FunctorAnalysis.hpp	560	
```
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	C3646	'pointer_type': unknown override specifier	kokkoskernels	C:\ProgramData\Trilinos-master\packages\kokkos\core\src\Kokkos_View.hpp	568	
```
What should I do?

**Comment by mhoemmen** [comment]
Kudos for attempting a Visual Studio build!  There are three issues here:

  1. I'm not sure if Visual Studio correctly implements enough of C++ to build Kokkos.
  2. I don't think Kokkos is tested with Visual Studio.
  3. Kokkos may include compiler-specific idioms and may lack Visual Studio specializations of those idioms.

Regarding (1), I have heard that VS 2015 R3 actually implements Substitution Failure Is Not An Error (as required by C++98) correctly.  I have also heard that MueLu builds under VS, but only with the Epetra back-end, not with Kokkos and Tpetra.  @csiefer2 could tell you more about this.  For now, I would recommend turning off the Kokkos package in your Visual Studio build.  You may have to turn off other packages as well.

Regarding (2) and (3), I'm sure the Kokkos team would welcome reports of regular testing, as well as small patches to fix and optimize for Visual Studio.  Please post Kokkos-specific issues and pull requests to Kokkos' GitHub page: https://github.com/kokkos/kokkos/  (pull requests for both Kokkos and Trilinos should be made against the `develop` branch).

**Comment by jwillenbring** [comment]
@mhoemmen is correct. The only way I know of to build Kokkos on Windows is with the Intel compilers.

**Comment by jtceleron** [comment]
Thank you guys. I found a similar issue someone posted around 2013... After 4 years, it looks like things don't go better....

**Comment by csiefer2** [comment]
We currently nightly test the Epetra stack through MueLu with VS2015.  We do not test Kokkos at present for the reasons @mhoemmen cites above.
