### ISSUE TITLE
Tpetra: In a CUDA build, check that "--expt-extended-lambda" is in CMAKE_CXX_FLAGS

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#1797]
@trilinos/tpetra 
@crtrott @ibaned 
In a CUDA build, check that `--expt_extended-lambda` is in `CMAKE_CXX_FLAGS`, as Tpetra and downstream packages require.

**Comment by mhoemmen** [comment]
I'm running the remote check-in test script for this fix now.  I first tested it locally in the following ways:
  - CUDA build, correctly included the flag in `Trilinos_CXX11_FLAGS` (it ends up in `CMAKE_CXX_FLAGS` anyway, probably due to TriBITS logic)
  - CUDA build, verify that Tpetra reports an error if the flag is missing
  - Non-CUDA build (which does not check for the flag)

**Comment by mhoemmen** [comment]
I just pushed a fix to develop.

**Comment by ibaned** [comment]
@mhoemmen note that this flag also exists with only one leading dash: `-expt-extended-lambda`

**Comment by mhoemmen** [comment]
@ibaned Ooo, good point; thanks!  I'll fix this.

**Comment by mhoemmen** [comment]
Running check-in tests now!

**Comment by mhoemmen** [comment]
@ibaned I just pushed the fix to develop.  The code now accepts that flag with either one or two initial hyphens.  Thanks!!! :-D
