### ISSUE TITLE
FEI has duplicate files with HYPRE

### ISSUE THREAD

**Issue by nschloe** [trilinos/Trilinos#18]
While working on a Debian/Ubuntu package for Trilinos, I sometimes bump into the funniest issues. This here is the fact that the existing package [HYPRE](http://acts.nersc.gov/hypre/) and Trilinos' FEI have header files with the exact same names. Specifically, the following files are already installed by HYPRE:

```
$ dpkg -L libhypre-dev | grep .h | grep fei
/usr/include/cfei_hypre.h
/usr/include/fei_defs.h
/usr/include/cfei-hypre.h
/usr/include/hypre_cfei.h
$
```

At least `fei_defs.h` is also present in FEI. This makes it impossible to co-install both packages on the same system.

**Comment by bartlettroscoe** [comment]
I forwarded this to an HYPRE developer who is on the same [IDEAS project](https://ideas-productivity.org ) with me.  While the global package name "FEI" is a little too generic for a global namespace, this is really a HYPRE defect.  HYPRE needs to namespace all of its installed header files and global symbols with "hypre_".

**Comment by bartlettroscoe** [comment]
Improving the interoperability between HYPRE and Trilinos is in the SCOPE of the IDEAS project.  Therefore, I created an [issue in that system](https://ideas-productivity.atlassian.net/browse/SDK-54) to track this there as well (but non-IDEAS members can't read those issues).  A HYPRE developer said they have added an issue in their issue tracking system to get this done.

**Comment by bartlettroscoe** [comment]
Nico,

Can you try `--without-fei` with hypre?

----

From: Yang, Ulrike Meier [mailto:yang11@llnl.gov] 
Sent: Friday, December 11, 2015 6:50 PM
To: Bartlett, Roscoe A.
Subject: RE: [Trilinos] FEI has duplicate files with HYPRE (#18)

Hi Ross,
Btw I forgot to mention that if you configure hypre without the fei,  ( configure –without-fei ) it will ignore the FEI stuff in hypre , so this might work for you guys in the meantime, until we get this fixed.
Thanks
Ulrike

**Comment by nschloe** [comment]
Well, this has to go into the Debian package and then we can have those packages co-installable.

**Comment by bartlettroscoe** [comment]
Need to get HYPE developers involved in this discussion.  Done know if Ulrike has a GitHub account.

**Comment by mhoemmen** [comment]
I am CC'ing @amklinv since Alicia has been reviving Trilinos / Hypre interop.

**Comment by ulrikeyang** [comment]
One comment on --without-fei, this will deactivate the LinSysCore interface in hypre, which people use to connect through the FEI . So if you want to use this, then --without-fei is not a good option. If you don't, your problems should go away. Regarding this LinSysCore interface: we actually don't like it and would prefer to have a better option. One of the problems with it is that it requires us to manually include any new options we add to our AMG solver, and we are really bad about this, since we generally ignore this interface. So, if there are some better future options to get hypre connected with the FEI,  we (and the few customers we have who still use the FEI with hypre) would be really happy.

**Comment by eric-c-cyr** [comment]
Exactly what is it your customers use FEI for?

**Comment by ulrikeyang** [comment]
They use it to generate a linear system using finite elements, which is then solved by hypre. hypre actually now allows to generate finite elements also through its semi-structured interface, but not all finite element options are available. FEI has more.

**Comment by eric-c-cyr** [comment]
From an interface perspective, does the user enter their local stiffness matrix and load vector? Then FEI puts them all together?
