### ISSUE TITLE
CMake warning : Unparsed arguments

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#1800]
@trilinos/amesos2 

I just started getting the following warning when configuring Amesos2.  It's a CUDA build, but that doesn't appear to matter here.
```
Processing enabled package: Amesos2 (Libs, Tests, Examples)
CMake Warning at cmake/tribits/core/package_arch/TribitsGeneralMacros.cmake:283 (MESSAGE):
  Arguments are being passed in but not used.  UNPARSED_ARGUMENTS =
  HEADERS;.../Trilinos/CHECKIN-CUDA-8.0/MPI_DEBUG/packages/amesos2/src/KLU2/Source/Amesos2_config.h;klu2_analyze_given.hpp;klu2_factor.hpp;klu2_refactor.hpp;klu2_analyze.hpp;klu2_free_numeric.hpp;klu2_scale.hpp;klu2_defaults.hpp;klu2_free_symbolic.hpp;klu2_solve.hpp;klu2_diagnostics.hpp;klu2.hpp;klu2_sort.hpp;klu2_dump.hpp;klu2_kernel.hpp;klu2_tsolve.hpp;klu2_extract.hpp;klu2_memory.hpp
Call Stack (most recent call first):
  cmake/tribits/core/package_arch/TribitsAddExecutableAndTest.cmake:165 (TRIBITS_CHECK_FOR_UNPARSED_ARGUMENTS)
  packages/amesos2/src/KLU2/Source/examples/CMakeLists.txt:1 (TRIBITS_ADD_EXECUTABLE_AND_TEST)
```

**Comment by searhein** [comment]
I see this for Belos as well

> CMake Warning at cmake/tribits/core/package_arch/TribitsGeneralMacros.cmake:283 (MESSAGE):
>   Arguments are being passed in but not used.  UNPARSED_ARGUMENTS =
>   Ifpack2BelosCopyFiles
> Call Stack (most recent call first):
>   cmake/tribits/core/package_arch/TribitsAddTest.cmake:762 (TRIBITS_CHECK_FOR_UNPARSED_ARGUMENTS)
>   packages/ifpack2/test/belos/CMakeLists.txt:281 (TRIBITS_ADD_TEST)

**Comment by srajama1** [comment]
Fixed the Amesos2 one.

**Comment by srajama1** [comment]
@trilinos/belos

**Comment by hkthorn** [comment]
Not an issue in Belos, the issue is in @trilinos/ifpack2:

(TRIBITS_CHECK_FOR_UNPARSED_ARGUMENTS)
packages/ifpack2/test/belos/CMakeLists.txt:281 (TRIBITS_ADD_TEST)
