### ISSUE TITLE
Panzer:  buildDomainContainer() for Write_GED

### ISSUE THREAD

**Issue by jmgate** [trilinos/Trilinos#1802]
Panzer's `LinearObjFactory` has a `buildDomainContainer()` routine that returns a `ReadOnlyVector_GlobalEvaluationData` container.  We need an equivalent routine that returns a `Write_GlobalEvaluationData` instead.

Interested parties:  @trilinos/panzer, @eric-c-cyr, @ssmabuza

**Comment by jmgate** [comment]
Also be sure to remove the `initializeData()` line in the `ghostToGlobal()` routine in `EpetraVector_Write_GlobalEvaluationData`.

**Comment by jmgate** [comment]
Removed the unintended `initializeData()` from the `ghostToGlobal()` routine, and all is well.

**Comment by jmgate** [comment]
Made requisite changes to Panzer&mdash;testing passes.  Next up:  corresponding changes to applications.

**Comment by jmgate** [comment]
Straightforward updates made to Drekar&mdash;tests pass.  Looking into additional refactoring needed in Drekar.

**Comment by jmgate** [comment]
Refactored Drekar's `simplex_lpfl` test to use the new way of doing things.  Looks like we're going to need a `BlockedVector_Write_GlobalEvaluationData` and all the associated accoutrements.  Huzzah!

**Comment by jmgate** [comment]
Created the `BlockedVector_Write_GlobalEvaluationData` and made the associated changes in the `BlockedEpetraLinearObjFactory`, but unfortunately the `simplex_lpfl` test is now failing.  Debugging&hellip;

**Comment by jmgate** [comment]
Turns out it was just a matter of vectors being used uninitialized.  `simplex_lpfl` is passing now.  Next up are a handful of other Drekar files that need to be refactored to the new way of doing things.

**Comment by jmgate** [comment]
Looks like Panzer's `EpetraVector_Write_GlobalEvaluationData` was duplicated in Drekar as `EpetraVector_Write_GED`; similarly `WriteVector_GlobalEvaluationData` as `WriteVector_GED`.  These Drekar classes need to be ripped out, and the code that uses them needs to be refactored to use Panzer.

**Comment by jmgate** [comment]
@eric-c-cyr, can we just make it such that these `build.*DomainContainer()` routines initialize the owned vector to zero to begin with?

**Comment by eric-c-cyr** [comment]
To be clear, you are saying when a user calls setOwnedVector? 

If so, then for the Write ones I think so... for the read ones no.  Caveat for the write ones, do you think a user would write a bunch of stuff to them first stuff it into a Write GED and then fill in the ghosted vector? Would they be upset if it didn't work that way?

**Comment by jmgate** [comment]
@eric-c-cyr, not sure.  It might be worthwhile to find a time for you, me, and @ssmabuza to sit down and work through the stuff he's put in Drekar using these `GlobalEvaluationData`s.  I'm having a hard time making heads or tails of it.  I'd say office hours next week, but it looks like that meeting was canceled&mdash;is that right?

**Comment by eric-c-cyr** [comment]
The office hours are on, I just haven't set an email for this (I've reserved a room already)

**Comment by jmgate** [comment]
Gotcha.  I'll try to understand all of Sibu's changes between now and then, and hopefully have an idea of what needs to change.

**Comment by ssmabuza** [comment]
@jmgate and @er The `drekar::WriteVector_GED` is a placeholder for the final Panzer implementation. We needed it to make sure all was well in the calculations with it is. I have more routines that use it. I use the  `panzer::BlockedEpetraLinearObjFactory` to create the owned vector which I zero out and stuff into the `drekar::WriteVector_GED` object. This could be eliminated by using the owned map already in `drekar::WriteVector_GED`.

**Comment by ssmabuza** [comment]
@jmgate and @er The `drekar::WriteVector_GED` is a placeholder for the final Panzer implementation. We needed it to make sure all was well in the calculations done using it, which they are. I have more routines that use it. I use the  `panzer::BlockedEpetraLinearObjFactory` to create the owned vector which I zero out and stuff into the `drekar::WriteVector_GED` object. This could be eliminated by using the owned map already in `drekar::WriteVector_GED`.

**Comment by jmgate** [comment]
I think I have all the necessary changes made to Drekar.  Building and testing now.

**Comment by jmgate** [comment]
I'm afraid I'm running into segfaults in the midst of an Epetra `Export()` in `EpetraVector_Write_GlobalEvaluationData::ghostToGlobal()`.

**Comment by jmgate** [comment]
I wound up pushing all the changes to Panzer, along with the associated changes to Drekar that worked.  I was never able to get @ssmabuza's stuff refactored to use the new way and work.  I suspect there is still some mismatch between maps somewhere, but I'm afraid I can't make heads or tails of the code and where things are going wrong.  I submitted an issue to the Drekar GitLab stating that those files should be refactored at some point, using the `simplex_lpfl` test as an example.
