### ISSUE TITLE
YAML: several places don't accept comments

### ISSUE THREAD

**Issue by bathmatt** [trilinos/Trilinos#1807]
It looks like the # sign is no longer a comment

```
*********** Caught Exception: Begin Error Report ***********
error: Parser failure at line 2 column 22 of Particle_interactions.yaml
My Awesome Problem: #other
```

**Comment by ibaned** [comment]
This is a documented difference, comments need to be on their own line. If we really need to change that I'll need an entire file as a a test case not just one line

**Comment by bathmatt** [comment]
Question, is there a way to, in the short term, build with the old yaml-cpp?  It seems that this is the default now.  

I'll email you file off gitlab as well.

**Comment by ibaned** [comment]
No compile option for that right now. One could be added but that is also work required.

**Comment by bathmatt** [comment]
Also, I tried 
#Hi
as my first line, 

*********** Caught Exception: Begin Error Report ***********
error: Parser failure at line 1 column 2 of Particle_interactions.yaml
# Hi

**Comment by bathmatt** [comment]
Also, there is an issue with blankish lines.  So, lines that have white space only in them.  

Also @ibaned  did you get my emailed file?  It hasn't gone through R&A so I don't wanna put it up on github

**Comment by ibaned** [comment]
@bathmatt I did get your emailed file.

@lxmota also asked about blank-ish lines in gahansen/Albany#186 .
I think to think hard about this one... leading whitespace is handled deep in the context-sensitive hack to the parser, not at the grammar level...

I think I'll fix the comments first.

**Comment by bathmatt** [comment]
Thanks...  I'll continue to test and merge and submit then.

**Comment by ibaned** [comment]
@bathmatt fixes for comments are up in #1812

**Comment by bathmatt** [comment]
Testing..  will this cure the blank line issue?

**Comment by bathmatt** [comment]
This looks like it resolves the comment issues.  Will open one for the blank lines

**Comment by bathmatt** [comment]
Sorry, still have an issue with a comment, not sure what this is.  If one indents that line it runs.
```
  Particle Dump:
    File Name: beam_emit2.h5part
    Particle Stride: 1
    Stride: 4
#   Stride Time: 5.0e-12
```

**Comment by bathmatt** [comment]
@ibaned any updates?

**Comment by ibaned** [comment]
The Kokkos event I'm at has my hands pretty well tied...

**Comment by ibaned** [comment]
Pull request #1851 should have fixed the non-aligned comment problem. Please reopen this issue if that symptom is still happening.

**Comment by bathmatt** [comment]
Dan @ibaned Sorry, I only get github issues on my gmail and you kknow how well that works here 😢

**Comment by ibaned** [comment]
Thats fine, I had that too and redirected them to my Sandia email. Hope this patch helped, let me know if anything else comes up.
