### ISSUE TITLE
MueLu: UtilitiesBase::Distance2 signature

### ISSUE THREAD

**Issue by lucbv** [trilinos/Trilinos#1813]
@jhux2 the signature of UtilitiesBase::Distance2 changed from taking an input `Multivector` to an `input Array<ArrayRCP<Scalar> >`, this causes an error in the [KOKKOS_REFACTOR_OPENMP build](https://testing.sandia.gov/cdash/viewBuildError.php?buildid=3144095).
It would be easy enough to overload with the `Multivector` signature, we could also add one with a `Kokkos::View` if that helps for the kokkos refactor?

**Comment by jhux2** [comment]
@lucbv I'll have a look.

**Comment by jhux2** [comment]
`Distance2` isn't used in MueLu's Kokkos-refactor code path, so I'm removing it from Utilities.  Checkin script is running.

**Comment by jhux2** [comment]
If the `KOKKOS_REFACTOR_OPENMP` build is clean tomorrow, this issue can be closed.

**Comment by lucbv** [comment]
The build is clean, thanks for taking care of this!
