### ISSUE TITLE
Trouble inspecting Teuchos::SerialDenseMatrix in gdb

### ISSUE THREAD

**Issue by jeff788** [trilinos/Trilinos#1817]
@trilinos/teuchos
@bartlettroscoe 

Is there a good way to inspect a Teuchos::SerialDenseMatrix in gdb? I'm having an issue with an LU factorization with LAPACK on a 6x6 SerialDenseMatrix "A", and I'm trying to diagnose the problem by inspecting the input matrix. When I try to inspect any elements of the matrix this is what happens:

(gdb) p A
$30 = {<Teuchos::CompObject> = {
    _vptr.CompObject = 0x7ffff756e708 <vtable for Teuchos::SerialDenseMatrix<int, double>+16>, 
    flopCounter_ = 0x0}, <Teuchos::Object> = {
    _vptr.Object = 0x7ffff756e730 <vtable for Teuchos::SerialDenseMatrix<int, double>+56>, 
    static tracebackMode = -1, label_ = ""}, <Teuchos::BLAS<int, double>> = {
    _vptr.BLAS = 0x7ffff756e770 <vtable for Teuchos::SerialDenseMatrix<int, double>+120>}, 
  numRows_ = 6, numCols_ = 6, stride_ = 6, valuesCopied_ = true, values_ = 0x81fa9d70}
(gdb) p A(0,0)
Invalid data type for function to be called.
(gdb) p A.values()
./mesh_transfer.sh: line 2:  1692 Segmentation fault      gdb /home/burg137/Projects/FY2018/NRAP/E4D/e4d_tools/MeshTransfer/bin/dream2tetgen

I also get a Segmentation fault if I try to print out the size of an ArrayRCP  with ArrayRCP::size(), while I can inspect individual elements in the ArrayRCP with the [] accessor.

Thanks,

Jeff

**Comment by bartlettroscoe** [comment]
@jeff788,

My personal experience with GDB is that I have not been able to use 'print any_cxx_func()` for an C++ function for many years (perhaps ever).  All that I have been able to to do is print raw data.  So to get the size, you will need to print the difference of the two pointers into a Teuchos::RCP, for example.   Does you GDB allow you to print any C++ function?

My advice is to use a debugger that works, like TotalView or just use trusty 'std::ostream' statements in C++ code.  Or just get used to debugging raw code and printing raw data.  But for debugging matrices, I would just print them out in C++ and avoid the debugger until I had to use it for some reason.

Have other Teuchos or Trilinos developers had a different experience with GDB than what I described above?

**Comment by DrBooom** [comment]
Use DDT or if you like debuggers that crash, TotalView. Chasing pointers is much easier in TotalView, so the crash rate may be tolerable.


Chris Luchini
ORG 1443
Sandia National Laboratory
(505) 284 3484
(505) 690 5008 Cell (505) is required.
________________________________

**Comment by jeff788** [comment]
I usually use gdb for pretty simple things for a long time, so I guess I didn't realize how far behind these other debuggers it is. I guess I'll get myself on the learning curve. Thanks for the quick responses!

**Comment by bartlettroscoe** [comment]
@jeff788, okay to close this GitHub Issue?

**Comment by jeff788** [comment]
Yes, thanks for your time.
