### ISSUE TITLE
kokkos-kernels vs kokkoskernels

### ISSUE THREAD

**Issue by nschloe** [trilinos/Trilinos#1818]
There is a discrepancy in files names for the new Kokkos kernels:

  * The package directory is called `kokkos-kernels`.
  * The library file name is `kokkoskernels.so`.

This creates some problems on the Debian side. I'd be great if this could be made consistent one way or the other. For comparison, check `trilinoscouplings`.

**Comment by aprokop** [comment]
@trilinos/framework @trilinos/kokkos-kernels

**Comment by srajama1** [comment]
The package name is KokkosKernels (to match Trilinos style) in Trilinos, but kokkos-kernels in Kokkos organization (to match with kokkos-tools etc). This is a problem living in two places. The library name matches Trilinos package name. We didn't think the directory name need to match the package name. Is that an assumption you are making ?

**Comment by nschloe** [comment]
> We didn't think the directory name need to match the package name. Is that an assumption you are making ?

For the Debian package, we derive the package name from the directory name (`kokkos-kernels`), and the package name has to match the library name (`libtrilinos-kokkos-kernels.so`). 

> The library name matches Trilinos package name.

I see: The directory is called `kokkos-kernels` because in the Kokkos orga, you're using dashes, but the library is called `kokkoskernels` (without the dash) to match Trilinos conventions. Well, one could argue that it's also a Trilinos convention not to use dashes in the directory names, cf. `meshinggenie` and `trilinoscouplings` (in fact `kokkos-kernels` is the first package with a dash). Then again, it wouldn't be the first inconsistency (cf. `ThreadPool`, `PyTrilinos`).

If you have a good idea of how to resolve this, let me know. Otherwise I'll have to try and work around it.

**Comment by bmpersc** [comment]
@nschloe, there is no required convention that I'm aware of. We've normally let people decide what their directories will be called. On the plus side that is also true for their library names too, so the Kokkos Kernels team could decide to change their library name to address this issue.

Forgive me, but I'm largely ignorant of how you are doing these builds and distributions for debian. I'm curious how you currently handle this for the packages with subpackage libraries or multiple libraries. Surely you have been installing teuchos and tpetra. All of the subpackages would not follow the pattern of being named after the package directory's name. Can you explain how you are handling those now?

**Comment by nschloe** [comment]
@bmpersc A Debian exception is added for each of the packages that don't conform to this rule (like, as you mentioned, packages with subpackages, and some other ones like pliris with `libdpliris` etc.). See [here](https://anonscm.debian.org/cgit/debian-science/packages/trilinos.git/tree/debian/lintian-override.in) if you're interested.

**Comment by srajama1** [comment]
Let me bring it up with other developers and we will go with the consensus.

**Comment by nschloe** [comment]
@srajama1 Any news on this yet?

**Comment by srajama1** [comment]
Sorry, forgot to respond. The team decided to keep it the way it is. Please use your workaround.
