### ISSUE TITLE
Implement Project-Wide Issue Management System

### ISSUE THREAD

**Issue by jwillenbring** [trilinos/Trilinos#182]
@maherou @bartlettroscoe @trilinos/framework

We need to implement a project-wide issue management system. It must work for both development-funded efforts, which are being required to apply more rigor to their issue tracking efforts, and for research-funded efforts, which will have more flexibility in use of the issue tracker. The system should have the following characteristics:

Usable: The system should not impose a heavy burden on Trilinos developers. Developers are familiar with a basic issue tracking system, and generally comfortable with using one. The extra requirements for the system should not require large additional time investments. For example, when filing or accepting a ticket, applying labels, estimating effort, assigning, etc shouldn't take more than a few extra minutes.

Well-defined: The process should be documented. Because of the traceability requirement listed below, it is important that certain parts of the process be followed carefully.

Traceable: A primary objective of the new issue management system is that customer requirements be traceable all the way to implementation and delivery. Requirements should be translated into specific issues in an epic-story-task hierarchy to support this traceability for large deliverables.

Visible: Current status should be easily visible for stakeholders, including customers, users, developers, and management.

**Comment by bartlettroscoe** [comment]
The requirement "traceable all the way to implementation" implies that each Trilinos git commit that relates to a requirement have the GitHub Issue number listed in it.  Without that, you can't trace all the way to specific code changes/additions.

**Comment by jwillenbring** [comment]
Your point is well taken. I maybe should clarify the traceability requirements at a finer granularity.

**Comment by bartlettroscoe** [comment]
>  I maybe should clarify the traceability requirements at a finer granularity.

I think that we should strongly recommend that every Trilinos commit reference some issue/ticket number.  It would be best if these were Trilinos GitHub Issues but sometimes I think it is okay to reference other issue tracking sites (and you can reference other GitHub sites with `<user-or-org>/<repo-name>#1234`).  We need to put this front and center.

Given the meeting we had yesterday, is this story not already in progress?

**Comment by dridzal** [comment]
.... every Trilinos commit reference some issue/ticket number


How do we incorporate new research code for which (a) we cannot disclose the customer's identity and (b) we cannot directly discuss the reason for the code's existence (but it's ok to have it out there)?  Should we have an umbrella ticket called 'Other' or 'Miscellaneous'?  This doesn't seem very useful though.  I think that the proposed recommendation is a little dangerous.  More generally, what if some customers don't want the progress for their task tracked on github?


________________________________

**Comment by bartlettroscoe** [comment]
> How do we incorporate new research code for which (a) we cannot disclose the customer's identity and (b) we cannot directly discuss the reason for the code's existence (but it's ok to have it out there)?  Should we have an umbrella ticket called 'Other' or 'Miscellaneous'?  This doesn't seem very useful though.  I think that the proposed recommendation is a little dangerous.  More generally, what if some customers don't want the progress for their task tracked on github?

Good questions.  This is one of the challenges with mixing pure research code with more mature code.  One thing to note is that if you are committing this code directly to the Trilinos 'master' branch, then you are not hiding it very well from the competition.  In that case, you should do it on a branch and use a private repo either on SSG or  BitBucket.  We will likely need policies on this based on the maturity level of the package/code.  But, IMHO, is unacceptable to make what appear to be random changes to a mature piece of software that many people depend on because we are doing "research".  However, at the same time, I believe it is possible to do research with/on a mature piece of software if the the right practices (and software partitioning) are used.  I can think of various ways to handle this in a reasonable way.  We should discuss this (or at least bring this up) at the next Trilinos Leaders meeting on Tuesday. I have added a note to my list of topics to bring up.

**Comment by bmpersc** [comment]
Last I checked Bitbucket has not been approved for storing Sandia software.

**Comment by mhoemmen** [comment]
> How do we incorporate new research code for which (a) we cannot disclose the customer's identity and (b) we cannot directly discuss the reason for the code's existence (but it's ok to have it out there)?

Add a Github issue which is the pure feature request -- e.g., "implement bubble sort" -- with no further details.  Reference said issue in the commit.

If your code is public, then your algorithms are public.  The contrapositive holds.

**Comment by bartlettroscoe** [comment]
@jwillenbring, is this not basically done?  Trilinos now has a JIRA site where internal customer issues are being tracked. 

Anyone have anything against closing this Issue?  Just trying to clean out our issues some.
