### ISSUE TITLE
Update 12.12 tarball

### ISSUE THREAD

**Issue by wfspotz** [trilinos/Trilinos#1820]
I have pushed three commits cherry-picked from the `develop` branch to the `trilinos-release-12-12-branch`. These changes fix Python 2/3 compatibility issues with the PyTrilinos documentation string generation scripts. When convenient, these should be converted into a new tarball for the 12.12 release.

**Comment by aprokop** [comment]
@trilinos/framework @bmpersc @jwillenbring
