### ISSUE TITLE
Fill out CONTRIBUTING.md

### ISSUE THREAD

**Issue by jmgate** [trilinos/Trilinos#1823]
A the moment, `CONTRIBUTING.md` just has some placeholder text in it.  We need to fill it out such that potential contributors understand what is expected when interacting with Trilinos.  I can take a crack at this, but I won't be able to start on it till late next week.

@jwillenbring, @bmpersc, any requests as to content?

@trilinos/framework

**Comment by maherou** [comment]
@jmgate: Please start a draft as you have time.  No need to wait.

**Comment by jmgate** [comment]
An initial cut of the `CONTRIBUTING.md` file has made it into `develop`.  When creating a new issue, GitHub provides a link to this file, though that will still contain the placeholder text until these changes make it into `master`.  Users have the ability to select the `develop` branch from the drop-down menu, revealing the actual contents, but they won't know to do that.  I'll leave this issue open until the next `develop` to `master` update.

**Comment by jmgate** [comment]
These changes have made it into `master`.  Closing&hellip;
