### ISSUE TITLE
ShyLU_Node Configure Failures - Looking for TPL_METIS?

### ISSUE THREAD

**Issue by william76** [trilinos/Trilinos#1826]
@trilinos/shylu 
@searhein 

Nightly testing is broken starting with Saturday night tests... Looks like configure issues with ShyLU_Node trying to load METIS (?)
- https://testing.sandia.gov/cdash/viewConfigure.php?buildid=3149030

### Relevant Commits 
- https://github.com/trilinos/Trilinos/commit/f57ee58221643a7802da6e1e33b75a9b31fe35bb ShyLU: Fixing some variable names
- https://github.com/trilinos/Trilinos/commit/34af86b5f561ca3ffa620fcdb9586c7f9b671f2e Merge branch 'develop' of https://github.com/trilinos/trilinos into develop

### Error messages
```
-- Searching for a lib in the set "metis":
--   Searching for lib 'metis' ...
-- NOTE: Did not find a lib in the lib set "metis" for the TPL 'METIS'!
-- ERROR: Could not find the libraries for the TPL 'METIS'!
-- TIP: If the TPL 'METIS' is on your system then you can set:
     -DMETIS_LIBRARY_DIRS='<dir0>;<dir1>;...'
   to point to the directories where these libraries may be found.
   Or, just set:
     -DTPL_METIS_LIBRARIES='<path-to-libs0>;<path-to-libs1>;...'
   to point to the full paths for the libraries which will
   bypass any search for libraries and these libraries will be used without
   question in the build.  (But this will result in a build-time error
   if not all of the necessary symbols are found.)
-- ERROR: Failed finding all of the parts of TPL 'METIS' (see above), Aborting!

-- NOTE: The find module file for this failed TPL 'METIS' is:
     /scratch/trilinos/workspace/trilinos-folder/Trilinos_generic_nightly/SERIAL_Release_gcc_4.9.3__DEV/Trilinos/cmake/TPLs/FindTPLMETIS.cmake
   which is pointed to in the file:
     /scratch/trilinos/workspace/trilinos-folder/Trilinos_generic_nightly/SERIAL_Release_gcc_4.9.3__DEV/Trilinos/TPLsList.cmake

TIP: One way to get past the configure failure for the
TPL 'METIS' is to simply disable it with:
  -DTPL_ENABLE_METIS=OFF
which will disable it and will recursively disable all of the
downstream packages that have required dependencies on it, including
the package 'ShyLU_NodeTacho' which triggered its enable.
When you reconfigure, just grep the cmake stdout for 'METIS'
and then follow the disables that occur as a result to see what impact
this TPL disable has on the configuration of Trilinos.

CMake Error at /scratch/trilinos/workspace/trilinos-folder/Trilinos_generic_nightly/Trilinos/cmake/tribits/core/package_arch/TribitsProcessEnabledTpl.cmake:127 (MESSAGE):
  ERROR: TPL_METIS_NOT_FOUND=TRUE, aborting!
Call Stack (most recent call first):
  /scratch/trilinos/workspace/trilinos-folder/Trilinos_generic_nightly/Trilinos/cmake/tribits/core/package_arch/TribitsGlobalMacros.cmake:1681 (TRIBITS_PROCESS_ENABLED_TPL)
  /scratch/trilinos/workspace/trilinos-folder/Trilinos_generic_nightly/Trilinos/cmake/tribits/core/package_arch/TribitsProjectImpl.cmake:202 (TRIBITS_PROCESS_ENABLED_TPLS)
  /scratch/trilinos/workspace/trilinos-folder/Trilinos_generic_nightly/Trilinos/cmake/tribits/core/package_arch/TribitsProject.cmake:93 (TRIBITS_PROJECT_IMPL)
  CMakeLists.txt:93 (TRIBITS_PROJECT)


-- Configuring incomplete, errors occurred!
See also "/scratch/trilinos/workspace/trilinos-folder/Trilinos_generic_nightly/SERIAL_Release_gcc_4.9.3__DEV/BUILD/CMakeFiles/CMakeOutput.log".
See also "/scratch/trilinos/workspace/trilinos-folder/Trilinos_generic_nightly/SERIAL_Release_gcc_4.9.3__DEV/BUILD/CMakeFiles/CMakeError.log".
CMake Error: CTEST_USE_LAUNCHERS is enabled, but the RULE_LAUNCH_COMPILE global property is not defined.
Did you forget to include(CTest) in the toplevel CMakeLists.txt ?
```

**Comment by kyungjoo-kim** [comment]
I thought that metis is already installed in the trilinos test as discussed in #1782.

**Comment by william76** [comment]
@bmpersc 
This commit is where the METIS dependence is getting added in.
https://github.com/trilinos/Trilinos/commit/28de7d52196372af73df22361e5fe4fc161c2232

**Comment by bmpersc** [comment]
@kyungjoo-kim, #1782 only said that we were going to look into setting it up either through SEMS or in a Trilinos area on the SEMS NFS. We have not actually gotten any of the TPLs built at this point. In fact I haven't even had a chance to do the due diligence necessary to bring the request to SEMS after vetting it for the concerns that they have for supporting any TPLs. The general request was made months ago, but recently some concerns that SEMS has were brought to our attention.

Before any TPLs are made required we should have at least made sure that the TPLs are working  and that we can submit tests with them enabled.

**Comment by kyungjoo-kim** [comment]
Okay. I will change metis as optional. Please let me know metis is available on the nightly test systems.

**Comment by william76** [comment]
@kyungjoo-kim @bmpersc 

Can we close out this issue?

**Comment by srajama1** [comment]
I would like to keep this open until #1782 is done.

**Comment by william76** [comment]
I can see that #1782 is still open as well as this one...

@srajama1 @bmpersc @jwillenbring Do you guys know if #1782 ever got done but the issue didn't get closed? It's been around since 2017 so it's a pretty old issue. ;)

**Comment by srajama1** [comment]
@william76 This was kept open to make sure we don't forget installing METIS on test systems. Is it installed now ? I know SEMS team is under staffed, but I also worry if I close it will never get addressed. Now at least we came back to it after an year :(

**Comment by william76** [comment]
@srajama1 ok. I'll ask and find out...

**Comment by william76** [comment]
Closing out an old issue that's probably been fixed or is no longer relevant.

**Comment by srajama1** [comment]
Is METIS enabled in some testing now ? The issue has been open for 3 years because we have not been testing with it.

**Comment by srajama1** [comment]
@william76 : I am reopening because of my question above. Please close it if you think the testing is addressed.
