### ISSUE TITLE
MueLu timer labels are mangled

### ISSUE THREAD

**Issue by jjellio** [trilinos/Trilinos#1828]
On a new build of MueLu, I am seeing Teuchos Timer labels that appear mangled:

E.g.,
MueLu: N5MueLu10RAPFactoryIdixN6Kokkos6Compat23KokkosDeviceWrapperNodeINS1_6OpenMPENS1_9HostSpaceEEEEE: Computing Ac

Is this intended? It would appear the above is trying to show something like
MueLu: MueLu::RAPFactory<ExecutionSpace>: Computing Ac

Is this type of output intended? Is there a way to control it? (E.g., use timer labels that are consistent with prior runs)

@jhux2 @csiefer2 @trilinos/muelu

**Comment by jhux2** [comment]
@jjellio Assume this is on Cori.  Anywhere else this can be reproduced?

**Comment by jjellio** [comment]
No, this is Onyx. I haven't pulled a new Trilinos on Cori since mid march.

csiefert is getting this on Onyx

**Comment by jhux2** [comment]
The mangling isn't intended behavior btw.

**Comment by jjellio** [comment]
My guess, is that Teuchos::demangleName() is failing in some way.

Look at MueCentral/MueLu_Describable.cpp,

It wants to form a ShortClassName, it does this by demangling, then removing '::' and '<' '>'

The down side, is that since those are removed, you can't demangle the failed demangled name! E.g., c++filt is not able to parse the mangled name because pieces are removed. Which means, I can't undo the transform once I have the Teuchos timers (I can't pass in the string I posted and demangle it correctly).

I can probably work out some regex's, but in the long term this will make tracking hard.

**Comment by csiefer2** [comment]
This particular platform does *not* support shared libraries.  Dunno if that matters, but it is different.

**Comment by jjellio** [comment]
It should be nearly identical to Cori.

**Comment by jhux2** [comment]
I just checked the dashboard, found no timer mangling anywhere.

**Comment by jhux2** [comment]
> It should be nearly identical to Cori.

But on Cori, this doesn't happen, right?

**Comment by jjellio** [comment]
It has never happened that I recall on Cori.

It is possible the configure on Onyx is wrong (I have emailed csiefert the Cmake voodoo I use). On these machines you do need to set some CMake variables directly, because the compiler cannot perform compileAndRun() tests (the target ARCH is not the same as the compiling architecture)

On Cori, I have to set:
-D HAVE_GCC_ABI_DEMANGLE:BOOL=TRUE

Need to verify that is TRUE on this build.

Regardless of the above, it would be nice to have a graceful failure, e.g., if demangling is not working, then set ClassShortName to something else.

**Comment by csiefer2** [comment]
Rebuilding with this option.

**Comment by jjellio** [comment]
The top of my Cray scripts has:

The CXX flags are not too important, because craype-haswell or craype-mic-knl will append them. But if you set them this way, you will get all kinds of warnings if you accidentally have the wrong modules loaded when you try to compile. E.g., the compiler line will see CC -xMIC-AVX512 -xAVX2, the latter added by craype. ICC will then have a fit that you are providing 2 optimization flags.
```
-D Trilinos_LINK_SEARCH_START_STATIC:BOOL=ON
-D MPI_USE_COMPILER_WRAPPERS=OFF
-D CMAKE_CXX_COMPILER="CC"
-D CMAKE_C_COMPILER="cc"
-D CMAKE_CXX_FLAGS="-xMIC-AVX512 -mkl=parallel -g1"
-D CMAKE_C_FLAGS="-xMIC-AVX512 -mkl=parallel -g1"
-D CMAKE_Fortran_FLAGS="-xMIC-AVX512 -mkl=parallel -g1"
-D CMAKE_EXE_LINKER_FLAGS="-xMIC-AVX512 -mkl=parallel "
-D CMAKE_Fortran_COMPILER="ftn"
-D HAVE_GCC_ABI_DEMANGLE:BOOL=TRUE
-D Trilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON
-D Trilinos_ENABLE_DEBUG:BOOL=OFF
-D Trilinos_ENABLE_INSTALL_CMAKE_CONFIG_FILES:BOOL=ON
-D CMAKE_BUILD_TYPE:STRING=RELEASE
-D CMAKE_VERBOSE_MAKEFILE:BOOL=OFF
-D Trilinos_ENABLE_ALL_PACKAGES:BOOL=OFF
-D Trilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=ON
-D Trilinos_ENABLE_TESTS:BOOL=OFF
-D Trilinos_ENABLE_EXAMPLES:BOOL=OFF
-D BUILD_SHARED_LIBS:BOOL=OFF
-D Trilinos_SET_INSTALL_RPATH=OFF
-D DART_TESTING_TIMEOUT:STRING=200
-D Trilinos_ENABLE_CXX11=ON

```

**Comment by jhux2** [comment]
There's also a Teuchos cmake option called "Teuchos_ENABLE_GCC_DEMANGLE".

**Comment by csiefer2** [comment]
Yeah, and that gets set correctly without manual intervention.

**Comment by aprokop** [comment]
I remember having this problem before: 34839a8019f6ef80f6ec5e3caa277426f458e1c3. Could this be a similar issue.?

**Comment by jjellio** [comment]
You should make sure that Cmake picks up CC, cc, and ftn as the compilers, not icpc icc and ifort.

One thing that can happen on the Cray machines, is that you have different standard c++ libs... if that get's messed up, really weird things happen. You can get an idea of what Cray is doing, by, CC -craype-verbose (or it may be ---craype-verbose), it will dump the actual compiler line that is used... they are usually quite long.

**Comment by jjellio** [comment]
Manually setting HAVE_GCC_ABI_DEMANGLE=TRUE, fixed this (which was my experience on other Cray systems).

I don't know precisely why, but I assume it is due to cross compiling and the fact that CMake cannot perform runtime tests.

On the flip side, I was able to decode the odd mangling with regular expressions.

I suppose this can be closed, unless the MueLu team wants to work on graceful failure. (feel free to reopen)

**Comment by jhux2** [comment]
@jjellio Thanks for confirming how to fix this.
