### ISSUE TITLE
Investigate why windows tests stop submitting

### ISSUE THREAD

**Issue by bmpersc** [trilinos/Trilinos#1830]
@trilinos/framework The windows testing has stopped submitting for no discernible reason. The root cause was that the jenkins process stopped, but there was no indication of why. The method I'd put in place to ensure that the process stays running didn't help here and now seems to no longer exist on the machine. We need to investigate why.

**Comment by bmpersc** [comment]
@csiefer2 reported that the windows testing stopped running again recently. I'm sure it has something to do with the VM being spun down and then back up which is something we can't control, but kills the jenkins agent process. I assumed that the OS would restart, but that doesn't seem to be the case so the task I setup to restart the jenkins agent doesn't seem to get a chance to run. I'll see if there is a reasonable way to setup a service instead of what we have. If that doesn't seem feasible I'll look into some kind of daily shutdown and restart of the jenkins agent which I am pretty sure will solve it, but runs the risk of shutting down while a job is in process.

**Comment by lucbv** [comment]
@bmpersc we can actually see some reporting on the CDash but the build deactivates Teuchos which means that no packages are enabled downstream and no code builds, see [here](https://testing.sandia.gov/cdash/buildSummary.php?buildid=3166596)

**Comment by bmpersc** [comment]
@lucbv The reason why teuchos was disabled was because there was a compile error when testing it which currently disables it for all downstream packages. You can see the error [here](https://testing.sandia.gov/cdash/viewBuildError.php?buildid=3166528). Since that is behaving as expected with respect to this issue I don't think that we should reopen this. However, another issue filed against Teuchos and ML may make sense. @csiefer2 should chime in on that as I believe he was taking a look at the build this morning.

**Comment by bmpersc** [comment]
Not sure why this is still open. The windows testing is working as expected at this point.
