### ISSUE TITLE
ShyLU_Node Build Errors in Nightly

### ISSUE THREAD

**Issue by william76** [trilinos/Trilinos#1841]
@trilinos/shylu 
@kyungjoo-kim 

There are compilation errors on the nightly clean build track:
- CDash: https://testing.sandia.gov/cdash/index.php?project=Trilinos&date=2017-10-11
- Example from Linux-gcc-4.9.3-SERIAL_Release_gcc_4.9.3__DEV: 
    https://testing.sandia.gov/cdash/viewBuildError.php?buildid=3156986

```
/scratch/trilinos/workspace/trilinos-folder/Trilinos_generic_nightly/SERIAL_Release_gcc_4.9.3__DEV/Trilinos/packages/shylu/shylu_node/tacho/src/TachoExp_Util.cpp:29:31: error: ‘ordinal_type’ does not name a type
   void getTimePerThread(const ordinal_type nthreads, 
                               ^
```

This looks like it might be the commit that added the error: https://github.com/trilinos/Trilinos/commit/3f64f4428cee8974d33d50e0ed8a0fc57cd0a5c9

**Comment by william76** [comment]
I did a bit of checking... ordinal_type isn't defined in TachoExp_Util.cpp, but it is defined in TachoExp_Util.hpp

Should TachoExp_Util.hpp be included into TachoExp_Util.cpp?

**Comment by kyungjoo-kim** [comment]
Oh.... I thought that I already pushed about this.

**Comment by kyungjoo-kim** [comment]
this should fix the problem.
