### ISSUE TITLE
Tpetra::MatrixMarket::Reader can't read graphs (pattern only)

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#185]
@trilinos/tpetra @egboman 

Moved from Bugzilla Bug 6130: https://software.sandia.gov/bugzilla/show_bug.cgi?id=6130

Bug posted by @egboman .  Original text:

I need to read MatrixMarket files with no values (pattern only) into Tpetra for Zoltan2 testing. Ideally, I would like to get a CrsGraph returned from the Tpetra::MatrixMarket::Reader. I don't see how to do this?

A work-around would be for Tpetra::MatrixMarket::Reader to create a CrsMatrix with explicit zeros. Then I could extract the graph from the matrix.

**Comment by srajama1** [comment]
This is not super important for Zoltan2 testing. We have enough matrices with values. As long as pattern only gives a reasonable error it is ok.

**Comment by egboman** [comment]
It's not urgent but still needed to run experiments with pattern-only matrices/graphs.

**Comment by mhoemmen** [comment]
> Ideally, I would like to get a CrsGraph returned from the Tpetra::MatrixMarket::Reader. I don't see how to do this?

That's because it doesn't exist :-)  The right thing to do would be to provide readSparseGraph and writeSparseGraph.  It can share implementation details with the sparse matrix code.

**Comment by mhoemmen** [comment]
> This is not super important for Zoltan2 testing. We have enough matrices with values. As long as pattern only gives a reasonable error it is ok.

Thanks for the priority clarification :-)  Pattern input files currently throw an exception when the header is read.  See lines 1080-1088 of tpetra/core/inout/MatrixMarket_Tpetra.hpp.

**Comment by mhoemmen** [comment]
This has been subsumed into #345 (which covers both Reader and Writer).  Thanks all!

**Comment by mmwolf** [comment]
There still seem to be bugs in the sparse graph reading functionality.  Some of the readSparseGraphFile functions call readSparseGraph incorrectly.  They pass fname of type std::string as the first argument to a function readSparseGraph that accepts std::ifstream instead.

**Comment by mmwolf** [comment]
sorry, wrong issue.
