### ISSUE TITLE
Clean up panzer indexer memory

### ISSUE THREAD

**Issue by bathmatt** [trilinos/Trilinos#1853]
It looks like Panzer has two copies of the indexer data.  Is this the case?

Do they both exist at the same time?  Can we just use the kokkos one or use the std::vector for just a temp and clean it out if it is not done yet
```
private:
   std::vector<std::vector<LocalOrdinalT> > localIDs_;
   Kokkos::View<const LocalOrdinalT**,PHX::Device> localIDs_k_;
```

@rppawlo @jmgate

**Comment by jmgate** [comment]
@trilinos/panzer

**Comment by rppawlo** [comment]
this is a question for @eric-c-cyr .

**Comment by eric-c-cyr** [comment]
We should probably just use the Kokkos one. This is a legacy of transition. I'm not sure what effect it would have to stop using the localIDs_ and use only localIDs_k_. @jmgate could you comment out the localIDs_ and see what kind of problem this would be? (just build panzer for now)

**Comment by jmgate** [comment]
Looks like we have 66 usages of the `std::vector` version of `getElementLIDs()` in panzer, with another 19 in Drekar.  These would all need to be switched over the the `Kokkos::View` version.  I'm not going to have time to make this switch any time soon.

**Comment by jmgate** [comment]
Panzer:
```
disc-fe/src/evaluators/Panzer_ScatterResidual_Epetra_impl.hpp
disc-fe/src/evaluators/Panzer_ScatterDirichletResidual_Epetra_Hessian_impl.hpp
disc-fe/src/evaluators/Panzer_GatherSolution_Epetra_Hessian_impl.hpp
disc-fe/src/evaluators/Panzer_GatherTangent_Tpetra_impl.hpp
disc-fe/src/evaluators/Panzer_ScatterResidual_BlockedEpetra_Hessian_impl.hpp
disc-fe/src/evaluators/Panzer_ScatterDirichletResidual_Tpetra_impl.hpp
disc-fe/src/evaluators/Panzer_ScatterDirichletResidual_BlockedEpetra_Hessian_impl.hpp
disc-fe/src/evaluators/Panzer_ScatterDirichletResidual_BlockedEpetra_impl.hpp
disc-fe/src/evaluators/Panzer_ScatterResidual_Tpetra_impl.hpp
disc-fe/src/evaluators/Panzer_GatherTangent_Epetra_impl.hpp
disc-fe/src/evaluators/Panzer_GatherSolution_Epetra_impl.hpp
disc-fe/src/evaluators/Panzer_GatherSolution_BlockedEpetra_Hessian_impl.hpp
disc-fe/src/evaluators/Panzer_ScatterResidual_BlockedEpetra_impl.hpp
disc-fe/src/evaluators/Panzer_GatherTangent_BlockedEpetra_impl.hpp
disc-fe/src/evaluators/Panzer_ScatterDirichletResidual_Epetra_impl.hpp
disc-fe/src/evaluators/Panzer_GatherSolution_BlockedEpetra_impl.hpp
disc-fe/src/evaluators/Panzer_ScatterResidual_Epetra_Hessian_impl.hpp
disc-fe/src/responses/Panzer_ResponseScatterEvaluator_Functional.hpp
disc-fe/src/responses/Panzer_ResponseScatterEvaluator_Probe.hpp
dof-mgr/test/dofmngr_test/tFilteredUGI.cpp
dof-mgr/src/Panzer_UniqueGlobalIndexer_Utilities_impl.hpp
dof-mgr/src/Panzer_UniqueGlobalIndexer.hpp
```

Drekar:
```
drekar_mhd/src/blk_precs/DrekarMHD_BlkPrec_MHD2DVankaFactory_impl.hpp
drekar/test/afc_tests/simplex_lpfl.cpp
drekar/src/core/utilities/Drekar_FieldValue_EulerEqns_RhoP.cpp
drekar/src/core/utilities/Drekar_Driver.cpp
drekar/src/core/utilities/Drekar_FieldValue_EulerEqns_KineticEnergy.cpp
drekar/src/core/utilities/Drekar_FieldValue_EulerIdealEoS_Pressure.cpp
drekar/src/core/utilities/Drekar_AFC_Utilities.cpp
drekar/src/core/utilities/Drekar_AFC_KSBLimiter.cpp
drekar/src/core/utilities/Drekar_GlobalIndexer_FieldCopy.cpp
drekar/src/core/utilities/Drekar_FieldValue_Identity.cpp
```

**Comment by bathmatt** [comment]
How about we deprecate that function, and change the syntax to returning a copy and not a ref, and build it on the fly?   Then we fix up the other functions as needed if they are called often.  Lots of places it is called like this anyway.

      LIDs = globalIndexer_->getElementLIDs(cellLocalId);

of the 66, 35 return a ref,

**Comment by bathmatt** [comment]
Crap, clicked the wrong button

**Comment by bathmatt** [comment]
@jmgate I'll take care of trilinos if you can do drekar and charon?  does that work?

**Comment by jmgate** [comment]
I can volunteer to take care of Charon.  Anyone else want Drekar?

**Comment by eric-c-cyr** [comment]
I'm not super happy about the change to getLocalIDs. I like the lazy evaluation syntax, if we want to clean up the memory we should build lazily from the internal Kokkos view.

**Comment by eric-c-cyr** [comment]
After some thought, lets go ahead and do Matt's proposed changes. I'm not in love with the performance hit a non Kokkos person would see, but it does seem sensible to control the memory required. I think in most cases we want to switch to the version in the Workset anyway: "cell_local_ids_k", all the evaluators should probably use that one instead.

@bathmatt Is there concrete data on this being a memory issue, or is it just seemingly low hanging fruit.

**Comment by eric-c-cyr** [comment]
Looking at Drekar, changing to copy the vector has really little effect. For instance the "Vanka" one doesn't appear to be compiled. The ones in Driver are already slow (they copy anyway, unless some move constructor magic happens), the two in FieldCopy just need the reference removed, it will be a little slower then a proper change to the Kokkos version. I imagine Charon has little to nothing in regard to getElementLIDs. The biggest changes are in the Panzer evaluators for sure.

**Comment by rppawlo** [comment]
> I'm not in love with the performance hit a non Kokkos person would see, but it does seem sensible to control the memory required.

@eric-c-cyr - I know you are going to cringe at this suggestion, but if we are going to change to the kokkos version, it might make sense to template this object on the memory space. That way the dof manager could be used in any memory space, regardless of which space phalanx is configured for. I'm thinking about mixed OpenMP and CUDA kernels on the same node.

**Comment by eric-c-cyr** [comment]
Hey, everyone is doing it and cool-aid is delicious

**Comment by bathmatt** [comment]
@rppawlo do you see a time where tpetra will not require UVM?  Furthermore, do you see a time when panzer wouldn't require UVM?  I think that using the default memory space should be o.k. as long as we are using UVM.

**Comment by eric-c-cyr** [comment]
The DOFManager could do this separately, there is really no reason for it to behave the same as the rest of panzer.

**Comment by bathmatt** [comment]
So, I removed the std::vector reference from this branch.

https://github.com/trilinos/Trilinos/tree/panzer-indexer-no-vector

Not sure how to link a branch :).. I fixed all the panzer sutff and only in one place did I need to do something other than replace something like

std::vector<int> LIDS & = 

with 

Kokkos::View<const int*> LIDS = 

That was in scatter resid eptra impl.  

I can fix drekar if needed and we can remove this. 

Also, on the old impl.  a vector<vector<int which is length small>> is trashing memory to use, becaue you have all this pointer derefing.  The kokkos view should be faster.

Can you look at the branch and comment?  Haven't started a PR yet,

**Comment by jmgate** [comment]
Created PR #1858 for the sake of code review.

**Comment by rppawlo** [comment]
> @rppawlo do you see a time where tpetra will not require UVM? Furthermore, do you see a time when panzer wouldn't require UVM?

I think Tpetra is working towards this in FY18. For Panzer, I don't see it happening for a few years. I would like to reserve the option to drop UVM if it doesn't get any faster in future cuda releases. I will ask Christian tomorrow about this. I'm currently starting an evaluation of the single parallel_for for all evaluators in the dag and, if we see promise in this, then I don't know how to avoid massive boilerplate without requiring UVM. Will know more by the end of the week on that front.

**Comment by jmgate** [comment]
Just curious, but who actually uses Panzer's Hessian support?  We have a tendency to forget about it when making sweeping changes.

Also interesting to note, when a merge commit is create via a pull request, the author of the commit is the person who created the pull request, not necessarily the person who did the work, or the person who clicked the "Merge" button.  Sorry @bathmatt&mdash;didn't mean to take credit for all your work.
