### ISSUE TITLE
Ifpack - no replacement for deprecated functions

### ISSUE THREAD

**Issue by prwolfe** [trilinos/Trilinos#1855]
Ifpack::set_parameters is set as deprecated but used in a number of places.  I did not find a suitable replacement strategy. The commit that did this is several years old.  Anyone know what's going on?

**Comment by mhoemmen** [comment]
There's no replacement strategy as far as I know.  Perhaps other @trilinos/ifpack2 developers would like to comment.

**Comment by prwolfe** [comment]
Sierra uses this in only one product.  Should I ask about us moving to ifpack2?  I was under the impression that trilinos was not ready for that yet.

**Comment by mhoemmen** [comment]
@prwolfe Moving to Ifpack2 would require Sierra to use Tpetra instead of Epetra.  I think a better approach would be to remove the deprecated warnings.  If nobody objects, I'll just do that.

**Comment by mhoemmen** [comment]
@jhux2 @csiefer2 Is this OK?

**Comment by csiefer2** [comment]
No objection here.

**Comment by jhux2** [comment]
Fine w/ me.

**Comment by mhoemmen** [comment]
I'm running the check-in test script for this fix now.

**Comment by mhoemmen** [comment]
@prwolfe I just pushed the fix to Trilinos develop.  It's not in master yet.

**Comment by prwolfe** [comment]
Dashboards look nice today.  - Thanks!
