### ISSUE TITLE
Tpetra::DistObject CUDA MPI thing

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#1860]
@trilinos/tpetra 
See discussion here:
https://github.com/gahansen/Albany/issues/182

**Comment by kddevin** [comment]
@mhoemmen 
Is it correct that telling the code that we had CUDA-aware MPI resolved the problem?

The Tpetra team had discussed supporting only CUDA-aware MPI for GPUs going forward.  @crtrott said CUDA-aware MPI is provided on our platforms.

Does this requirement allow us to remove the less-tested code and use only the better execution path?  Are there any gotchas with this new requirement beyond modifying CMake to detect insufficient MPI?

**Comment by mhoemmen** [comment]
@kddevin wrote:
> Is it correct that telling the code that we had CUDA-aware MPI resolved the problem?

That resolved the issue for Albany.  However, the unit test I'm working on in Tpetra fails regardless of whether Tpetra is allowed to assume that MPI is CUDA aware.  I also discovered that the entire thread-parallel CrsMatrix pack and unpack code path was unexpectedly completely untested in Trilinos (all the way downstream).  This is also a critical code path for best performance (where the CrsMatrix was constructed with a constant CrsGraph, the so-called "static graph" case) and will certainly persist in any Tpetra refactoring efforts, so we need to test it well.

> The Tpetra team had discussed supporting only CUDA-aware MPI for GPUs going forward.

It's reasonable to assume this, yes.  However, it may still be useful for performance reasons to have an option to communicate only to/from host buffers.  Micah Howard tells me that MPI implementations currently perform poorly with CUDA buffers (even CudaSpace, not CudaUVMSpace).  We will need to benchmark this to verify, but it suggests that we may still want an option to communicate on host.

**Comment by mhoemmen** [comment]
I may be closer to figuring this out, or at least to figuring out _something_ that's wrong.  For CrsMatrix, I found a case where the `exports_` array has sync states (0,0) on entry to `packAndPrepareNew`, but sync states (1,1) on exit from `packAndPrepareNew`.  This means that data on host and device have both been modified without intervening syncs.

**Comment by mhoemmen** [comment]
I think I get it.  

For the non-static case, `packAndPrepareNew` packs on host; when `commOnHost` is `true`, then `exports_` somehow isn't getting copied back up to device (but the packet counts are; this explains why we've been setting "`numBytes is nonzero but the number of entries to unpack in the row is zero" errors).  

For the static case, the opposite happens: `packAndPrepareNew` packs on device, so when `commOnHost` is `false`, `exports_` is on device but Distributor is communicating host data.  This would explain why forcing Tpetra to assume that MPI is CUDA aware fixes the issue for Albany. 

The two issues are related.  I think we can fix both at the same time.  My plan is to pass the `commOnHost` flag into `packAndPrepareNew`.  This would tell `packAndPrepareNew` where to leave the packed data, on host or on device.  That would have the additional advantage of avoiding unnecessary sync operations.  For example, if `commOnHost` is `false` but `packAndPrepareNew` wants to pack on host anyway, then we wouldn't have to sync back and forth in `DistObject::doTransferNew`.

I have to leave now, but I should be able to fix this issue pretty soon, if this is really the cause.

**Comment by tjfulle** [comment]
@mhoemmen, I'm confused how the new thread parallel pack/unpack was tested.  I wrote the tests to intentionally fail and they only passed when the thread parallel pack/unpack were done.  Sacado and ROL both also used the new pack/unpack and exposed a few issues that had to be resolved.  Unless you mean that a code path through  `packAndPrepareNew` wasn't tested?

**Comment by tjfulle** [comment]
Errr, my last comment meant to say I'm confused how the pack/unpack *wasn't* tested

**Comment by mhoemmen** [comment]
@tjfulle I'm puzzled too, but that Albany182 test is helping me figure things out.  Don't worry :-) .

**Comment by mhoemmen** [comment]
@tjfulle To be more precise: `packAndPrepareNew` -> `packNew` picks whether to use the thread-parallel implementation of packing, based on whether the graph is static (constant).  That doesn't mean the same thing as "the matrix is fill complete"; it means "the matrix was created with a constant `CrsGraph`."  The latter doesn't get exercised so often in this tests.  It's also excessively restrictive; the right predicate is "the matrix is fill compete, or it was fill completed once before, or the matrix has a constant `CrsGraph`."

**Comment by crtrott** [comment]
I am still not sure where the assertion that performance is bad with CUDA allocations is coming from. I wrote a small benchmark code and that guy is fine (there are two comm modes, one testing inter node communication (0) and one intranode communication (1):

This is the result:

| Mode | MessageSize | CudaSpace BW | CudaUVMSpace BW | OpenMP BW |
|----|----|----|----|----|
| inter | 1kB | 0.028 | 0.018 | 0.043 |
| intra | 1kB | 0.044 | 0.022 | 1.1 |
| inter | 10kB | 0.27 | 0.17 | 0.40 |
| intra | 10kB | 0.44 | 0.22 | 3.3 |
| inter | 100kB | 1.8 | 1.1 | 1.8 |
| intra | 100kB | 4.2 | 1.9 | 7.1 |
| inter | 1MB | 5.6 | 3.0 | 4.0 |
| intra | 1MB | 25.6 | 2.9 | 7.4 |
| inter | 10MB | 6.4 | 3.9 | 4.0 |
| intra | 10MB | 53.3 | 3.0 | 8.1 |

As you can see the BW is generally ok with CudaSpace. Some of that might now be better with the CUDA 9 driver. To run I did:
```
mpirun -np 4 --npersocket 1 ./test.host 12800000 1000 1 --ndevices=2
```
The first free arguments are: N (10xmessage elements) repeats and comm-mode. 

```c++
#include "mpi.h"
#include "Kokkos_Core.hpp"
#include <utility>
#include <sstream>
#include <iostream>

int main (int argc, char* argv[])
{
  MPI_Init (&argc, &argv);
  Kokkos::initialize(argc,argv);
  int myRank = 0;
  int numProcs = 0;
  int R = atoi(argv[2]);
  int N = atoi(argv[1]);
  int comm_mode = atoi(argv[3]); // 0: send to half numProcs, 1: send to neighbor)
  MPI_Comm_rank (MPI_COMM_WORLD, &myRank);
  MPI_Comm_size (MPI_COMM_WORLD, &numProcs);

  const int lclVecLen = N;//100000000;
  const int msgLen = lclVecLen / 10;

  Kokkos::View<double*> x ("x", lclVecLen);
  Kokkos::deep_copy (x, static_cast<double> (myRank));

  Kokkos::View<double*> x_start (x, std::make_pair (0, msgLen));
  Kokkos::View<double*> x_end (x, std::make_pair (lclVecLen - msgLen, lclVecLen));

  const int otherRank = comm_mode==0?((myRank+numProcs/2)%numProcs):
                                     (myRank%2==1?myRank-1:myRank+1);
  const int tag = 42;

  printf("Message from %i send to %i numProcs: %i\n",myRank,otherRank,numProcs);
  Kokkos::Timer timer;
  double time_mpi = 0.0;
  for(int k=0; k<R; k++) {
    Kokkos::Timer timer_mpi;
    MPI_Request reqs[2];
    MPI_Isend (x_start.data (), msgLen, MPI_DOUBLE, otherRank, tag, MPI_COMM_WORLD, &reqs[0]);
    MPI_Irecv (x_end.data (), msgLen, MPI_DOUBLE, otherRank, tag, MPI_COMM_WORLD, &reqs[1]);
  //  printf("Wait %i from %i %i %i\n",k,myRank,otherRank,numProcs);

    MPI_Status statuses[2];
    MPI_Waitall (2, reqs, statuses);
    time_mpi += timer_mpi.seconds();

    const double expectedLclSum =
      (msgLen * static_cast<double> (otherRank)) +
      (lclVecLen - msgLen) * static_cast<double> (myRank);

  //  printf("My Rank: %i, Expected Sum: %e\n",myRank,expectedLclSum);
    double lclSum = 0.0;
    Kokkos::parallel_reduce (lclVecLen, KOKKOS_LAMBDA (const int i, double& lsum) { lsum += x(i); x(i)=(k+2)*myRank; }, lclSum);
    if (lclSum != expectedLclSum * (k+1)) {
      std::ostringstream os;
      os << "Proc " << myRank << ": lclSum = " << lclSum << " != expectedLclSum = " << expectedLclSum << std::endl;
      std::cerr << os.str ();
    }
  }
  double time = timer.seconds();
  printf("Time: %lf TimeMPI: %lf Size: %lfMB  BW: %lfGB/s Latency %lfus\n",time,time_mpi,1.0*msgLen*8/1024/1024, 1.0*msgLen*8*2*R/time_mpi/1024/1024/1024,time_mpi/R*1000*1000);
  Kokkos::finalize();
  MPI_Finalize ();
  return 0;
}
```

**Comment by mhoemmen** [comment]
@crtrott wrote:
> I am still not sure where the assertion that performance is bad with CUDA allocations is coming from.

That's what Micah said, but I'm sure he would be happy to see this corrected :-) .

**Comment by mhoemmen** [comment]
This got auto-closed; I'm still working on verifying the fix in Albany.

**Comment by mhoemmen** [comment]
@bathmatt found that this fixes the issue in his code (issue 137 in his tracker), and closed that issue.  Thus, I'm closing this issue, though I would still like to verify in Albany.
