### ISSUE TITLE
Panzer: Modifications to panzer::Traits

### ISSUE THREAD

**Issue by seamill** [trilinos/Trilinos#1865]
After a conversation with @rppawlo, we have decided to update the panzer::Traits interface.

There are three changes that will affect downstream code:

1. Make EvalData constant:

Currently we have:
```c++
typedef panzer::Workset& EvalData;
```

New version:
```c++
using EvalData = const panzer::Workset&;
```

2. Make SetupData a const reference with const worksets:

Currently we have:
```c++
struct SD { 
  Teuchos::RCP< std::vector<panzer::Workset> > worksets_;
  Teuchos::RCP<const std::vector<Intrepid2::Orientation> > orientations_;
};
typedef SD SetupData;
```

New version:
```c++
struct SD { 
  Teuchos::RCP<const std::vector<panzer::Workset> > worksets_;
  Teuchos::RCP<const std::vector<Intrepid2::Orientation> > orientations_;
};
using SetupData = const SD&;
```

3. PreEvalData becomes a reference, and gedc becomes an RCP

Currently we have:
```c++
typedef struct {
  GlobalEvaluationDataContainer gedc;

  std::string first_sensitivities_name;
  std::string second_sensitivities_name;
} PreEvalData;
```

New version:
```c++
struct PED {
  Teuchos::RCP<GlobalEvaluationDataContainer> gedc;
  std::string first_sensitivities_name;
  std::string second_sensitivities_name;
} ;
using PreEvalData = const PED&;
```

The include for ``GlobalEvaluationDataContainer`` will be removed from ``Panzer_Traits.hpp`` and replaced with forward declaration.

**Comment by seamill** [comment]
Interested parties @rppawlo @eric-c-cyr @jmgate @bathmatt

**Comment by jmgate** [comment]
Minor suggestion:  C++11 makes it such that you don't need spaces between closing angle brackets in nested templates, for instance
```c++
Teuchos::RCP<const std::vector<panzer::Workset>> worksets_;
Teuchos::RCP<const std::vector<Intrepid2::Orientation>> orientations_;
```

**Comment by seamill** [comment]
This issues looks to be done. Closing...
