### ISSUE TITLE
No Trilinos CI build showing up on testing.sandia.gov/cdash/ 10/20/2017

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#1880]
**CC:** @trilinos/framework 

**Description:**

Looks like neither the CI build running on ceerws1113 or  sadl30906  are showing up today on:

* https://testing.sandia.gov/cdash/index.php?project=Trilinos&date=2017-10-20

but they showed up yesterday well before now as shown at:

* https://testing.sandia.gov/cdash/index.php?project=Trilinos&date=2017-10-20

The CI build coming from ceerws1113 was showing the submit failures:

```
Submit files (using http)
   Using HTTP submit method
   Drop site:http://testing.sandia.gov/cdash/submit.php?project=Trilinos
   Submission failed: Checksum failed for file.  Expected f5c77b6d2121b1525367c745a4ba7c0a but got d41d8cd98f00b204e9800998ecf8427e.
   Submit failed, waiting 120 seconds...
```

**Comment by bartlettroscoe** [comment]
I have an email out to Kitware contractors about why we may be getting these "checksum" submit failures.

**Comment by bartlettroscoe** [comment]
FYI:

Zack G. from Kitware found the problem:

> I'm not sure what the root underlying cause is, but the disk got full on testing.sandia.gov.  More specifically, CDash's backup directory was the culprit.  This was causing uploaded XML files to only partially get written, which resulting in the checksum errors that you noticed.
>
> To alleviate this, I just deleted all XML files in the backup directory older than 7 days.  This should give us some breathing room for the time being.

I am pretty sure this means that no CDash results would have been posted to that site anymore.

I just restarted the CI server on ceerws1113 and it is already submitting again as shown by:

* https://testing.sandia.gov/cdash/index.php?project=Trilinos&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=66&value1=-MPI_RELEASE_DEBUG_SHARED_PT_CI&field2=buildstamp&compare2=65&value2=20171020-1807

and

* https://testing-vm.sandia.gov/cdash/index.php?project=Trilinos&filtercombine=and&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=66&value1=-MPI_RELEASE_DEBUG_SHARED_PT_CI&field2=buildstamp&compare2=65&value2=20171020-1807

Putting this in review.

**Comment by jwillenbring** [comment]
Since @bartlettroscoe put this in review more than a year ago, and we have been seeing results in CDash, I am going to close this issue.
