### ISSUE TITLE
Please remove GCC 4.7.2 builds from Dashboard

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#1883]
@trilinos/framework (Or, disable packages downstream from Kokkos, that require GCC >= 4.8.4.)

Thanks!

**Comment by mhoemmen** [comment]
**bump**
I'm getting spurious build failures on ascic141 with the `Linux-GCC-4.7.2-openmpi-1.6.5_Debug_DEV_Werror` build.  The reported build error is clearly wrong and likely a compiler bug.  Could someone please disable Kokkos and downstream packages for this build, or show me how to do it?  Thanks!

**Comment by jwillenbring** [comment]
All GCC 4.7.2 build should be absent from the dashboard starting tomorrow. If not, please reopen the ticket. Thanks for your patience.
