### ISSUE TITLE
myRank shadow warning in Tpetra_CrsMatrix_def.hpp

### ISSUE THREAD

**Issue by rrdrake** [trilinos/Trilinos#1887]
There seems to be a new Trilinos warning coming from a Tpetra header file:
```
Tpetra_CrsMatrix_def.hpp:7391:19: error: declaration of 'myRank' shadows a previous local [-Werror=shadow]
         const int myRank = comm.getRank ();
```

**Comment by mhoemmen** [comment]
@rrdrake I'll fix it :-) .  Looks legit; I already have `myRank` printed out in `*prefix`, so I should just use that.

btw this code is part of our larger effort to improve run-time control of Tpetra.  It's a lot easier to tell users to set an environment variable (`TPETRA_VERBOSE`, in this case), than it is to ask them to rebuild or to run in a debugger.  The general experience of MPI + CUDA + threads + `$FUTURE_NONEUCLIDEAN_HORRORS`, is that `printf` debugging works everywhere and almost always rewards the patient.

**Comment by mhoemmen** [comment]
I'm running the remote check-in test script now with the fix.

**Comment by mhoemmen** [comment]
I just pushed a fix to develop: https://github.com/trilinos/Trilinos/commit/e901fb31262beba91ef113913801505530e2017a

Thanks for reporting!

**Comment by rrdrake** [comment]
Thanks @mhoemmen !  I'll watch for it on master.
