### ISSUE TITLE
Tpetra: Add robust calculation mode

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#189]
@trilinos/tpetra

Moved from Bugzilla Bug 241: https://software.sandia.gov/bugzilla/show_bug.cgi?id=241

Original text by @maherou on 15 Feb 2003:

In some form the following features should be added:
- Guards against over/underflow in key kernels.  Clearly in the two-norm, but 
  perhaps elsewhere if possible.
- Quad-precision accumulator for sums.
- Scale-invariant global sums.  Sum quantities should be bit-wise identical 
  independent of the number of processors used, with perhaps a prescribed maximum 
  processor count to aid implementation.

**Comment by mhoemmen** [comment]
This may build upon James Elliott's work on reproducible floating-point summation.

**Comment by ibaned** [comment]
In case it can be of any use as another reference, a Kokkos-based and MPI-scalable implementation of reproducible summation can also be found here:
https://github.com/ibaned/omega_h2/blob/master/src/repro.cpp

**Comment by mhoemmen** [comment]
Thanks @ibaned !  I didn't realize you had an interest in this!

One of James' goals is to make this work for atomic += as well, in an O(1) memory-scalable and time-scalable way.  He uses an entirely different approach for that.  If you're interested, just let me know and I'll put you in touch with him.

**Comment by ibaned** [comment]
bitwise reproducibility is crucial to mesh adaptation because mesh connectivity is modified based on whether values are above or below a fixed threshold, so yes if there is work in this area I am interested.

**Comment by mhoemmen** [comment]
@ibaned I just sent you and James an e-mail.  Thanks!
