### ISSUE TITLE
Panzer: issues with  pthread/multiple execution spaces

### ISSUE THREAD

**Issue by rppawlo** [trilinos/Trilinos#1903]
Reported in kokkos:
https://github.com/kokkos/kokkos/issues/1186

**Comment by ibaned** [comment]
Only `Kokkos::Threads` needs to be handled correctly in order for Kokkos+Trilinos integration testing to pass.

**Comment by rppawlo** [comment]
Mark, Christian and I looked a this. It is an inconsistency between node types for panzer and phalanx. Phalanx depends on kokkos and uses the kokkos default node type if a node type is not specified in configure. Panzer depends on Tpetra and uses Tpetra default node type. This node type must be consistent between panzer and phalanx. This particular configure enables the Thread and Serial Kokkos nodes but explicitly disables serial node type in Tpetra. I need to add a panzer configure time check to make sure the nodes are consistent. In the meantime, you can add Phalanx_KOKKOS_DEVICE_TYPE="THREAD" for that particular configure.

**Comment by rppawlo** [comment]
This one still needs to be addressed. Removing marked for closure label.
