### ISSUE TITLE
Zoltan2: Use MPI_Alltoallv for all-to-all, instead of hand-rolling it from sends and receives

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#1904]
@trilinos/zoltan2 

See `Trilinos/packages/zoltan2/src/util/Zoltan2_AlltoAll.[ch]pp`.  If necessary, add a Teuchos wrapper for `MPI_Alltoallv`.

**Comment by mhoemmen** [comment]
nope, not gonna let this autoclose

**Comment by mhoemmen** [comment]
I can't add a "WONTFIX" label; y'all ought to do that : - )

**Comment by jhux2** [comment]
@egboman Not sure if this is still relevant.

**Comment by egboman** [comment]
Not sure. There was a reason Zoltan implemented it this way, but can't remember why anymore. I will close this as it is "just" a performance issue, not a correctness bug.

**Comment by egboman** [comment]
Please reopen if needed.
