### ISSUE TITLE
Show users how to build with warnings as errors, but excluding deprecated warnings as errors

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#1905]
@bartlettroscoe @trilinos/framework @jwillenbring

**Comment by bartlettroscoe** [comment]
Here is how you do it (learned from SPARC):

```
 -Werror -Wno-error=deprecated-declarations 
```

Cool, right?

**Comment by mhoemmen** [comment]
@bartlettroscoe Neat! :-D

@rrdrake @prwolfe

**Comment by mhoemmen** [comment]
I added a page to the Trilinos wiki with this explanation:  https://github.com/trilinos/Trilinos/wiki/Building-with-warnings-as-errors,-excluding-deprecated-warnings

Please feel free to move it to wherever it may belong.  Thanks Ross! :-D
