### ISSUE TITLE
MueLu: TripleMatrixMultiply build error

### ISSUE THREAD

**Issue by ibaned** [trilinos/Trilinos#1906]
A nightly build of Trilinos develop by the Albany team failed with this error:
```
Trilinos/packages/muelu/src/Interface/../Misc/MueLu_RAPFactory_def.hpp:230:11: error: 'TripleMatrixMultiply' has not been declared
```

http://my.cdash.org/viewBuildError.php?buildid=1312380

@trilinos/muelu

**Comment by ibaned** [comment]
@cgcgcg

**Comment by lucbv** [comment]
@ibaned , Christian is travelling for the next week, I am having a look, it does not seem to bad.

**Comment by cgcgcg** [comment]
@lucbv Thanks, I would really appreciate that! If it's tricky just revert it, then I'll have a look once I'm back..

**Comment by lucbv** [comment]
@ibaned I pushed a commit that should fix this problem. I will close this issue tomorrow if the nightly comes back clean.

**Comment by william76** [comment]
@lucbv 

Is this related to / or the same bug that caused the TpetraCore_MatrixMatrix_UnitTests test failure on the Trilinos CDash 'Clean' track from last night?

https://testing.sandia.gov/cdash/testDetails.php?test=42290438&build=3183867

**Comment by lucbv** [comment]
@william76 I am not sure here, the previous error was at the level of Xpetra/MueLu which I am more familiar with.

**Comment by mhoemmen** [comment]
@william76 It looks like this issue is unrelated to that one.

**Comment by mhoemmen** [comment]
It looks like this has been fixed in develop, so I'm closing this issue.  Please reopen if needed.  Thanks for the fix!
