### ISSUE TITLE
MueLu: TpetraCore_MatrixMatrix_UnitTests Failed on CDash

### ISSUE THREAD

**Issue by william76** [trilinos/Trilinos#1907]
@trilinos/muelu 
@trilinos/tpetra 

Possibly relates to #1906 ?

TpetraCore_MatrixMatrix_UnitTests Failed on CDash last night...
- CDash: https://testing.sandia.gov/cdash/index.php?project=Trilinos##Clean
- Output: https://testing.sandia.gov/cdash/testDetails.php?test=42290438&build=3183867

@mhoemmen had a quick look at it for me, here's his assessment:

> These tests work by reading parameters from a list stored in a file.  It looks like for this particular test, the parameters insist on having exactly 4 MPI processes.  However, the CMakeLists.txt file for the test (see tpetra/core/test/MatrixMatrix/CMakeLists.txt, top of file) doesn't specify a particular number of MPI processes, so CTest will just run with whatever number of processes it feels like using.
> p=0: *** Caught standard std::exception of type 'std::runtime_error' :
>
>  Test requires exactly 4 MPI ranks.
> [FAILED]  (0.106 sec) Tpetra_MatMat_double_int_int_Kokkos_Compat_KokkosSerialWrapperNode_operations_test_UnitTest
> Location: . . . /SERIAL_Release_gcc_4.9.3__DEV/Trilinos/packages/tpetra/core/test/MatrixMatrix/MatrixMatrix_UnitTests.cpp:767

**Comment by william76** [comment]
If all we need to do is set the # of processes to 4, can get the fix in...

**Comment by mhoemmen** [comment]
Thanks @william76 ! :-D  We should check with @trilinos/muelu folks (e.g., @csiefer2 @jhux2 @lucbv ) to make sure that this doesn't silently exclude some tests in that executable.  If not, then I think we can close this issue.

**Comment by william76** [comment]
Now that the nightlies are back up, it looks like this is still failing in the nightly tests... My edit in #1908 doesn't seem to have fixed it.

CMakeLists.txt file: https://github.com/trilinos/Trilinos/blob/develop/packages/tpetra/core/test/MatrixMatrix/CMakeLists.txt

Last Night's CDash: https://testing.sandia.gov/cdash/testDetails.php?test=42396227&build=3193312
```
p=0: *** Caught standard std::exception of type 'std::runtime_error' :
 
  Test requires exactly 4 MPI ranks.
 [FAILED]  (0.101 sec) Tpetra_MatMat_double_int_longlong_Kokkos_Compat_KokkosSerialWrapperNode_operations_test_UnitTest
 Location: /scratch/trilinos/workspace/trilinos-folder/Trilinos_generic_nightly/SERIAL_Release_gcc_4.9.3__DEV/Trilinos/packages/tpetra/core/test/MatrixMatrix/MatrixMatrix_UnitTests.cpp:767
```

I think @csiefer2 was having a look at this earlier this week (?)

@bartlettroscoe, is adding the NUM_MPI_PROCS 4 here the right thing to set the test to run with 4 processes?  A later test in the CMakeLists.txt file was using NUM_MPI_PROCS 1 so I ran with that...
```
TRIBITS_ADD_EXECUTABLE_AND_TEST(
  MatrixMatrix_UnitTests
  SOURCES
  MatrixMatrix_UnitTests.cpp
  ${TEUCHOS_STD_UNIT_TEST_MAIN}
  ARGS "--matnames-file=\"matrixsystems.xml\" --v"
  NUM_MPI_PROCS 4
  )
```

**Comment by csiefer2** [comment]
Fix pushed

**Comment by mhoemmen** [comment]
@william76 :
  1. Does the test pass for you when you run it (via ctest) on your machine? 
  2. Try changing the test so that those exception messages print the actual number of MPI processes.
  3. If the actual number of MPI processes is greater than 4, we could use `Teuchos::Comm::split` to make a subset communicator with 4 processes (the first 4 in the communicator, to ensure consistency with Teuchos unit test framework expectations for Process 0 printing), then run with that.

**Comment by csiefer2** [comment]
I think I fixed this yesterday, but the nightlies didn't update correctly.  @bmpersc is aware and is filing an issue.

**Comment by jhux2** [comment]
:no_mouth:

**Comment by csiefer2** [comment]
❓

**Comment by csiefer2** [comment]
Stick a fork in this one... :grinning:
