### ISSUE TITLE
Testing gap exists for Epetra64

### ISSUE THREAD

**Issue by rhoope** [trilinos/Trilinos#1909]
I don't think there is any automated testing for builds based on Epetra64.

**Comment by aprokop** [comment]
@rhoope I think you are right. I believe @srajama1 mentioned that Epetra64 may not be properly supported especially going forward.

**Comment by mhoemmen** [comment]
@trilinos/epetra

**Comment by rhoope** [comment]
@kddevin Karen, I find this old Issue and thought I'd dust it off to capture the need to build and test Epetra64 as we discussed.  I'll follow up with more details shortly.

**Comment by kddevin** [comment]
@jwillenbring would it be difficult for someone in the frameworks team to add at least one Epetra64 test to the nightly testing?  Some SNL users are still using it, and had been developing their own patches as it fell into disrepair.
@trilinos/framework

**Comment by srajama1** [comment]
@rhoope : I am curious, why use Epetra64 and not Tpetra ?

**Comment by rhoope** [comment]
@srajama1 At the time (a couple of years ago), Aleph wanted to get to >2 billion mesh entities as quickly as possible.  We use a lot of the Epetra solver stack and found Eeptra64 to be the shortest path requiring the least amount of change to the code.  However, we had to address some gaps, which are are reflected in this MR.  We do plan to adopt Tpetra in the near future but didn't want to lose this work.

**Comment by srajama1** [comment]
@rhoope Thanks for explaining your point of view. Personally, I feel like we shouldn't have done Epetra64. It was an intermediate step for exactly cases like yours. However, this has created some technical debt to maintain it long term.

**Comment by rhoope** [comment]
@srajama1 I agree with that.  FWIW, we've been rolling our Epetra64 patches over with each update of our version of Trilinos and thought it worthwhile to formally capture them in Trilinos proper.  Hopefully, this only adds minimal effort to maintain the subset of Epetra that we've got working.

**Comment by srajama1** [comment]
@rhoope Agreed. We will do the best to support your needs. The first step is what you said above - a nightly build that enables the option.

**Comment by kddevin** [comment]
@ZUUL42 would it be difficult for someone in the frameworks team to add at least one Epetra64 test to the nightly testing? Some SNL users are still using it, and had been developing their own patches as it fell into disrepair.  Thanks!

**Comment by kddevin** [comment]
@trilinos/framework Just checking whether this issue can be addressed for our SNL users.  Thanks.
