### ISSUE TITLE
Teuchos_StandardParameterEntryValidators throw on normal execution

### ISSUE THREAD

**Issue by jclause** [trilinos/Trilinos#1910]
Standard probing of parameterLists results in a lot of code that throws during the course of normal execution, e.g., testing whether a parameter was specified and then catching to prescribe a default. 

See Ifpack2_AdditiveSchwarz_def.hpp:903 for an example

This is a bad practice that results in a library that is difficult to use and debug within an application. Do not throw unless it is an exceptional event.

**Comment by aprokop** [comment]
@trilinos/teuchos

**Comment by mhoemmen** [comment]
@aprokop @ibaned This might be more accurately an issue with Ifpack2 (or other packages).  ParameterList doesn't _require_ using exceptions for control flow.
