### ISSUE TITLE
CEE machines hang in Trilinos configure

### ISSUE THREAD

**Issue by ibaned** [trilinos/Trilinos#1912]
@trilinos/framework 

All of our nightly Trilinos builds on any CEE hardware are hanging at this point in the CMake configuration process:

```
-- Performing Test FINITE_VALUE_HAVE_STD_ISINF
-- Performing Test FINITE_VALUE_HAVE_STD_ISINF - Success
-- Found Doxygen: /usr/bin/doxygen (found version "1.6.1")
```

Attempts to manually configure Trilinos on CEE hardware also hang after that line of output. This is really preventing me from getting any work done.

**Comment by mhoemmen** [comment]
@prwolfe @rrdrake Do you see this?  This is weird.

**Comment by ibaned** [comment]
Sorry I didn't post an update, here it is:
The issue came down to a mounted directory called `/ml_cap` that was being queried and hung indefinitely when queried.
I sent in a ticket to CEE and they fixed the problem, at least on the machines relevant to me.
