### ISSUE TITLE
Kokkos' CMake may have changed, requiring new options with CUDA builds

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#1919]
See https://github.com/kokkos/kokkos/issues/1197 .  Work-around: set CMake option `Kokkos_ENABLE_Cuda:BOOL=ON` explicitly.

@trilinos/framework @trilinos/tpetra

**Comment by crtrott** [comment]
This needs to get fixed again. This was a breakdown in testing procedure where the test script caught the issue, but the workaround was put in instead of tracking down the root cause .., we will fix this with a local fix in Trilinos later tonight.

**Comment by mhoemmen** [comment]
@crtrott It's cool, I just wanted to document the work-around :-) .

**Comment by crtrott** [comment]
Issued a pull request, can you check it out? Looks like it solves the issue for me.

**Comment by mhoemmen** [comment]
@crtrott wrote:
> Issued a pull request, can you check it out? Looks like it solves the issue for me.

I just reviewed it; thanks!  I'm happy for the fix, but it worries me a bit that `KOKKOS_HAVE_CUDA_TPL` and `TPL_ENABLE_CUDA` don't appear to be connected.  Which one are we supposed to use?  Does setting one not set the other by default?

**Comment by ndellingwood** [comment]
@crtrott @mhoemmen When PR #1922 goes through the following line should be removed from configure-testbeds-jenkins-all (I can do this, adding message for reference and so hopefully I get Github notification as this issue gets closed):
https://github.com/trilinos/Trilinos/blob/e18e10f5ec99763e7203dedcf988a1a7ea54f138/sampleScripts/Sandia-SEMS/configure-testbeds-jenkins-all#L61

This was the workaround I added to get the integration testing up and running based on configure output message, didn't realize it masked this issue.

**Comment by ndellingwood** [comment]
Matching PR in Kokkos: 
[kokkos PR 1201](https://github.com/kokkos/kokkos/pull/1201)

**Comment by ibaned** [comment]
@ndellingwood thanks for pointing this out. I'm using the checkin script to merge @crtrott 's fixes now, including #1922, and I've added a commit which removes that line from the Jenkins script.

**Comment by ndellingwood** [comment]
@ibaned thanks!

**Comment by mhoemmen** [comment]
@ibaned patched this in Trilinos:develop; thanks!
