### ISSUE TITLE
Tpetra: Rename TpetraKernels subpackage to KokkosKernels package (post copyright)

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#192]
@trilinos/tpetra @mndevec 

This was originally Bugzilla Bug 6439: https://software.sandia.gov/bugzilla/show_bug.cgi?id=6439

Original text posted by me on 20 Oct 2015:

TpetraKernels, a subpackage of Tpetra, is a temporary parking spot for code that will go into the (not yet existing) KokkosKernels package.  I named it "TpetraKernels" only because I thought that TriBITS restricted subpackage names to start with the package name.  It looks like this requirement doesn't exist, at least not anymore.  It would be better to rename this subpackage to KokkosKernels, so that when KokkosKernels becomes its own package, users won't have to change their CMake configuration scripts.

**Comment by srajama1** [comment]
I will file the copyright for the package.

**Comment by mhoemmen** [comment]
> I will file the copyright for the package.

Thanks! :-)  btw TriBITS supposedly allows us to call this "KokkosKernels" even if it's just a subpackage of Tpetra.  It would make sense to do this by Trilinos 13 so that we can introduce the package without breaking backwards compatibility.
