### ISSUE TITLE
Kokkos: Serial is_initialized fix caused issues for OpenMP/Serial builds 

### ISSUE THREAD

**Issue by crtrott** [trilinos/Trilinos#1920]
A fix was made to Kokkos outside normal procedures (i.e. get it into kokkos/develop, and then merge it into Trilinos at integration) which unfortunately caused other issues if both OpenMP and Serial are in use. This fixes that. See kokkos/kokkos#1199

**Comment by mhoemmen** [comment]
Awesome; thanks! :-D I noticed earlier today that `Kokkos::initialize` wasn't initializing nondefault execution spaces; this must be the fix for that.
