### ISSUE TITLE
Ifpack2,Tpetra: Some harmless but fixable CUDA build warnings

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#1926]
@trilinos/ifpack2 @trilinos/tpetra 

`warning: calling a constexpr __host__ function from a __host__ __device__ function is not allowed.`  Warning is harmless because this is host code calling the function in question anyway.  See:
  - `Ifpack2_DenseContainer_def.hpp`, line 576
  - `Ifpack2_BandedContainer_def.hpp`, lines 373 and 508
  - `Tpetra_Experimental_BlockView.hpp`, lines 624, 1250, and 1256

**Comment by brian-kelley** [comment]
@mhoemmen I fixed the warnings in Ifpack2 but couldn't replicate the BLockView ones. The Ifpack2 warnings just needed some things to be casted to impl_scalar_type before multiplication.

**Comment by mhoemmen** [comment]
Thanks @brian-kelley ! :D I'll close this for now.
