### ISSUE TITLE
Failing Tpetra and Xpetra tests in CI build from commits pushed on 10/31/2017

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#1929]
**Next Action Status:**

Decide if to fix or backout the commits ...

**CC:** @trilinos/framework, @trilinos/tpetra, @trilinos/xpetra, @DrBooom 

**Description:**

After the push of the commits:

```
7ba1c78:  Tpetra: put CheckImportValidity blocks in each of the Import constructors.
Author: Chris Luchini <cbluchi@sandia.gov>
Date:   Tue Oct 31 13:30:01 2017 -0600

M	packages/tpetra/core/src/Tpetra_Import_def.hpp

f66ede7:  Tpetra: Clean up the CheckImportValidity routine
Author: Chris Luchini <cbluchi@sandia.gov>
Date:   Tue Oct 31 13:07:12 2017 -0600

M	packages/tpetra/core/src/Tpetra_Import_Util.hpp
```

shown at:

* https://testing-vm.sandia.gov/cdash/viewNotes.php?buildid=3139970#!#note1

we are now seeing 7 failing Tpetra tests and 2 failing Xpetra tests as shown at:

* https://testing-vm.sandia.gov/cdash/index.php?project=Trilinos&parentid=3139969

This corresponds to the logged push:

```
Tue Oct 31 13:34:22 MDT 2017

commit 7ba1c78b3d8208635bead45a867d1c2038d15f87
Author:     Chris Luchini <cbluchi@sandia.gov>
AuthorDate: Tue Oct 31 13:30:01 2017 -0600
Commit:     Chris Luchini <cbluchi@sandia.gov>
CommitDate: Tue Oct 31 13:30:17 2017 -0600

    Tpetra: put CheckImportValidity blocks in each of the Import constructors.

Commits pushed:
7ba1c78 Tpetra: put CheckImportValidity blocks in each of the Import constructors.
f66ede7 Tpetra: Clean up the CheckImportValidity routine
```

(Does not look like checkin-test-sems.sh script was used to test and push.)

**Comment by bartlettroscoe** [comment]
@DrBooom,

Since these failing tests will stop other people from pushing using the checkin-test-sems.sh script as described at:

* https://github.com/trilinos/Trilinos/wiki/Policies-%7C-Safe-Checkin-Testing

we should likely back out these two commits ASAP so that the failures can be fixed offline.  If you don't hear from you in the next hour, I will back out these commits and update this issue with instructions on how to test locally and fix this and then push again with the checkin-test-sems.sh script.

**Comment by mhoemmen** [comment]
@bartlettroscoe If it blocks people, please feel free to revert the commits.  This thing is a work in progress.

**Comment by rppawlo** [comment]
So I just ran the checkin test script this morning and got two panzer failures that blocked a push. The failure is:

```
0init Invalid importer
p=0 | *********** Caught Exception: Begin Error Report ***********
p=0 | /home/rppawlo/CHECKIN/Trilinos/packages/tpetra/core/src/Tpetra_Import_def.hpp:147:
p=0 |
p=0 | Throw number = 1
p=0 |
p=0 | Throw test that evaluated to true: !isvalid
p=0 |
p=0 | Malformed importer constructed
p=0 | ************ Caught Exception: End Error Report ************
```

Is this possibly related to this issue?

**Comment by bartlettroscoe** [comment]
> Is this possibly related to this issue?

That is possible.  We did not get a complete CI build last night because of #1932 so we don't know if this broke Panzer or not as well.

Let's just backout these two commits.  I will just run the Tpetra test suite so that this goes fast.

**Comment by bartlettroscoe** [comment]
@csiefer2,

When I try to rever the commit f66ede7, I am getting a merge conflict:

```
<<<<<<< HEAD                                                                                                                                                                        
  if(!global_is_valid) {                                                                                                                                                            
    std::cerr<<os.str()<<std::flush;                                                                                                                                                
    Importer.print(std::cout);                                                                                                                                                      
  }                                                                                                                                                                                 
                                                                                                                                                                                    
=======                                                                                                                                                                             
>>>>>>> parent of f66ede7... Tpetra: Clean up the CheckImportValidity routine                     
```

It looks like I should keep what is on HEAD (which was added in commit 3f2cc71).  Unless you tell me not to, I will keep that block of code in the conflict and test (just Tpetra for speed) and push.

**Comment by csiefer2** [comment]
I bumped off the offending commit ---- that code wasn't ready for "prime time" yet.

**Comment by bartlettroscoe** [comment]
> I bumped off the offending commit ---- that code wasn't ready for "prime time" yet.

I just ran:

```
$ ./checkin-test-sems.sh --no-enable-fwd-packages --do-all --push
```

and just pushed the commit b62fa0c8d651c20:

```
commit b62fa0c8d651c2061e39bf38c632286d898e6fd4
Author: Roscoe A. Bartlett <rabartl@sandia.gov>
Date:   Wed Nov 1 09:06:03 2017 -0600

    Revert 'not-ready-for-prime-time' commits to Tpetra::Import
    
    This commit squashes the reverts:
    
    Revert "Tpetra: put CheckImportValidity blocks in each of the Import constructors."
    
    This reverts commit 7ba1c78b3d8208635bead45a867d1c2038d15f87.
    
    Revert "Tpetra: Clean up the CheckImportValidity routine"
    
    This reverts commit f66ede7407773d2557ee684eb8020beaa9a0c994.
    
    I resolved the merge conflict by removing the new block of code added in
    commit:
    
      3f2cc71 "Tpetra: Improving debugging info for importers"
    
    These were just debug print statements so I think these can be removed.
    
    Build/Test Cases Summary
    Enabled Packages: TpetraCore
    Disabled Packages: PyTrilinos,Claps,TriKota
    0) MPI_RELEASE_DEBUG_SHARED_PT => passed: passed=136,notpassed=0 (4.19 min)

M       packages/tpetra/core/src/Tpetra_Import_Util.hpp
```

Please take a look at that and make sure this is as it should be.

I will restart the CI server on ceerws1113 (and I will get to the bottom of #1932).

**Comment by DrBooom** [comment]
Looks like I missed the flames. Note to self, don't push at 4pm

**Comment by bartlettroscoe** [comment]
Everything passed in the restarted CI build shown at:

* https://testing.sandia.gov/cdash/index.php?project=Trilinos&parentid=3194851&filtercount=3&showfilters=1&field1=groupname&compare1=61&value1=Continuous&field2=buildstarttime&compare2=84&value2=now&filtercombine=and
