### ISSUE TITLE
ShyLU_Node and ShyLU_DD configure failures after TriBITS update

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#1947]
**CC:** @trilinos/shylu 

**Description:**

After my TriBITS update in the commit 9403c2a (which added stronger checking for correct usage of TriBITS, see TriBITSPub/TriBITS#200 and TriBITSPub/TriBITS#232), the ShyLU_Node and ShyLU_DD packages showed configure failures for all of the builds today as shown at:

* https://testing.sandia.gov/cdash/index.php?project=Trilinos&date=2017-11-03&display=project&filtercount=3&showfilters=1&filtercombine=and&field1=subprojects&compare1=93&value1=ShyLU_Node&field2=subprojects&compare2=93&value2=ShyLU_DD&field3=subprojects&compare3=93&value3=ShyLU

These show the configure failures like:

```
Processing enabled package: ShyLU_Node (HTS, Tacho, Tests, Examples)
CMake Error at /scratch/trilinos/workspace/trilinos-folder/Trilinos_generic_nightly/Trilinos/cmake/tribits/core/package_arch/TribitsPackageMacros.cmake:744 (MESSAGE):
  Must call TRIBITS_PACKAGE_DECL(), TRIBITS_PROCESS_SUBPACKAGES()and
  TRIBITS_PACKAGE_DEF before TRIBITS_PACKAGE_POSTPROCESS().  Because this
  package has subpackages you cannot use TRIBITS_PACKAGE() you must call
  these in the following order: TRIBITS_PACKAGE_DECL
  TRIBITS_PROCESS_SUBPACKAGES TRIBITS_PACKAGE_DEF TRIBITS_PACKAGE_POSTPROCESS
  in file:
  /scratch/trilinos/workspace/trilinos-folder/Trilinos_generic_nightly/SERIAL_Release_gcc_4.9.3__DEV/Trilinos/packages/shylu/shylu_node/CMakeLists.txt
Call Stack (most recent call first):
  packages/shylu/shylu_node/CMakeLists.txt:23 (TRIBITS_PACKAGE_POSTPROCESS)
```

The fix is trivial and I am working to test and push it now.

**Comment by bartlettroscoe** [comment]
As shown at:

* https://testing.sandia.gov/cdash/viewTest.php?onlyfailed&buildid=3195171

the tests `ShyLU_NodeTacho_Tacho_TestSerial_double_MPI_1` and `ShyLU_NodeTacho_Tacho_TestSerial_dcomplex_MPI_1` are already failing so I will disable them in my local testing and push.

**Comment by bartlettroscoe** [comment]
This has been fixed with the push shown below.

Putting into review.

@ccober6, can you confirm that your configure of Trilinos is now working?

```
DID PUSH: Trilinos: crf450.srn.sandia.gov

Fri Nov  3 14:16:42 MDT 2017

Enabled Packages: ShyLU_DD, ShyLU_Node
Disabled Packages: PyTrilinos,Claps,TriKota

Build test results:
-------------------
0) MPI_RELEASE_DEBUG_SHARED_PT => Test case MPI_RELEASE_DEBUG_SHARED_PT was not run! => Does not affect push readiness! (-1.00 min)
1) MPI_RELEASE_DEBUG_SHARED_ST => passed: passed=2,notpassed=0 (0.02 min)

*** Commits for repo :
  e2b8a39 ShyLU: Add missing TRIBITS_PACKAGE_DEF() calls (TriBITSPub/TriBITS#200)
  eb466a8 Enable ST code in ST extrab builds

1) MPI_RELEASE_DEBUG_SHARED_ST Results:
---------------------------------------

  passed: Trilinos/MPI_RELEASE_DEBUG_SHARED_ST: passed=2,notpassed=0
  
  Fri Nov  3 14:16:36 MDT 2017
  
  Enabled Packages: ShyLU_DD, ShyLU_Node
  Disabled Packages: PyTrilinos,Claps,TriKota
  Hostname: crf450.srn.sandia.gov
  Source Dir: /home/rabartl/Trilinos.base/Trilinos/cmake/tribits/ci_support/../../..
  Build Dir: /home/rabartl/Trilinos.base/BUILDS/CHECKIN/MPI_RELEASE_DEBUG_SHARED_ST
  
  CMake Cache Varibles: -DTrilinos_TRIBITS_DIR:PATH=/home/rabartl/Trilinos.base/Trilinos/cmake/tribits -DTrilinos_ENABLE_TESTS:BOOL=ON -DTrilinos_TEST_CATEGORIES:STRING=BASIC -DTrilinos_ALLOW_NO_PACKAGES:BOOL=OFF -DDART_TESTING_TIMEOUT:STRING=300.0 -DTPL_ENABLE_MPI=ON -DCMAKE_BUILD_TYPE=RELEASE -DTrilinos_ENABLE_DEBUG=ON -DBUILD_SHARED_LIBS=ON -DTrilinos_ENABLE_SECONDARY_TESTED_CODE=ON -DTrilinos_ENABLE_COMPLEX=OFF -DIfpack2_Cheby_belos_MPI_1_DISABLE=ON -DTrilinos_ENABLE_ShyLU_DD:BOOL=ON -DTrilinos_ENABLE_ShyLU_Node:BOOL=ON -DTrilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=ON -DTrilinos_ENABLE_ALL_FORWARD_DEP_PACKAGES:BOOL=OFF -DTrilinos_ENABLE_PyTrilinos:BOOL=OFF -DTrilinos_ENABLE_Claps:BOOL=OFF -DTrilinos_ENABLE_TriKota:BOOL=OFF
  Make Options: -j16 
  CTest Options: -j16 -E '(ShyLU_NodeTacho_Tacho_TestSerial_double_MPI_1|ShyLU_NodeTacho_Tacho_TestSerial_dcomplex_MPI_1)'
  
  Pull: Not Performed
  Configure: Not Performed
  Build: Not Performed
  Test: Passed (0.02 min)
  
  100% tests passed, 0 tests failed out of 2
  
  Label Time Summary:
  ShyLU_Node    =   1.39 sec (2 tests)
  
  Total Test time (real) =   1.29 sec
  
  Total time for MPI_RELEASE_DEBUG_SHARED_ST = 0.02 min
```

**Comment by ccober6** [comment]
Got through the configure!  It is now compiling.  Let you know how it goes.

**Comment by bartlettroscoe** [comment]
I should have tried to test ST packages in addition to PT packages when I pushed these TriBITS changes.   That was bad because these types of errors in the usage of TriBITS are most likely to be in non-PT packages.  That was sloppy on my part.  I forget that with the SEMS env, you can actually build and test quite a few ST packages and many of these packages are tested in "Clean" and "Nightly" Trilinos builds shown on CDash.  And people are using these packages as well.

Given the usage of some of these ShyLU subpackage by ATDM, we should likely elevate some of them to PT so that they are properly protected by everyone.

**Comment by ccober6** [comment]
Add Roger @rppawlo 

Well I get a couple errors like

/Users/ccober/myOffice/Trilinos/packages/shylu/shylu_node/tacho/src/TachoExp_Blas_External.hpp:71:8: error: 
      conflicting types for 'sgemm_'
  void F77_BLAS_MANGLE(sgemm,SGEMM)( const char*, const char*,
       ^
and

/Users/ccober/myOffice/Trilinos/packages/shylu/shylu_node/tacho/src/TachoExp_Blas_External.hpp:78:8: error: 
      conflicting types for 'dgemm_'
  void F77_BLAS_MANGLE(dgemm,DGEMM)( const char*, const char*,
       ^

Thoughts?

**Comment by bartlettroscoe** [comment]
> Well I get a couple errors like ...

That should be unrelated to the TriBITS changes merged into Trilinos.  What was the last version of Trilinos where this worked?

**Comment by ccober6** [comment]
Yeah, I do not know.  This brings me to my next lesson in learning git.  Can you point me to a tutorial?

**Comment by bartlettroscoe** [comment]
> Yeah, I do not know. This brings me to my next lesson in learning git. Can you point me to a tutorial?

Try looking at:

```
git reflog -v
```

That will show `HEAD` for recent history.  You might get lucky and see it from that.  Otherwise, again, if you did not record that version somehow, it will be hard to know.

**Comment by bartlettroscoe** [comment]
There is always `git bisect`.  To bisect cleanly with Trilinos, you really need to bisect on known-tested commits.  Turns out we know what commits are tested because of the usage of checkin-test.py See:

* https://tribits.org/doc/TribitsDevelopersGuide.html#using-git-bisect-with-checkin-test-py-workflows

Not claiming that is easy to do but it is a guaranteed way to find the range of commits (usually less than 10 of them) when a defect was first introduced.

**Comment by rppawlo** [comment]
> Add Roger @rppawlo
> 
> Well I get a couple errors like
> 
> /Users/ccober/myOffice/Trilinos/packages/shylu/shylu_node/tacho/src/TachoExp_Blas_External.hpp:71:8: error:
> conflicting types for 'sgemm_'
> void F77_BLAS_MANGLE(sgemm,SGEMM)( const char*, const char*,
> ^
> and
> 
> /Users/ccober/myOffice/Trilinos/packages/shylu/shylu_node/tacho/src/TachoExp_Blas_External.hpp:78:8: error:
> conflicting types for 'dgemm_'
> void F77_BLAS_MANGLE(dgemm,DGEMM)( const char*, const char*,
> ^
> 
> Thoughts?

@ccober6 - none of our testing relies on shylu at this point. You should be able to disable for the time being to make progress. 

cc'ing shylu team - @srajama1 @kyungjoo-kim @trilinos/shylu

**Comment by srajama1** [comment]
github notifications are being weird again. I didn't get any notifications from github in the last few days and came to check on the website. May be @kyungjoo-kim has the same problem as well.

**Comment by kyungjoo-kim** [comment]
The error may happen when a cpp file includes the tacho blas layer (separated from teuchos) and teuchos blas wrapper header or other BLAS interface declared in other header files (I dont know which header is duplicated as I do not see the full error message). If this is not urgent, I will fix this problem later.
