### ISSUE TITLE
Amesos2 SuperLUDist configure error in Morgan

### ISSUE THREAD

**Issue by srajama1** [trilinos/Trilinos#195]
[ 26%] Building CXX object packages/amesos/src/CMakeFiles/amesos.dir/Amesos_Superludist.cpp.o
/home/projects/sparc/tpls/Trilinos/packages/amesos/src/Amesos_Superludist.cpp(448): error: argument of type "int" is incompatible with parameter of type "LUstruct_t *"
      LUstructInit(NumGlobalRows_, NumGlobalRows_, &PrivateSuperluData_->LUstruct_);
                                   ^

/home/projects/sparc/tpls/Trilinos/packages/amesos/src/Amesos_Superludist.cpp(448): error #140: too many arguments in function call
      LUstructInit(NumGlobalRows_, NumGlobalRows_, &PrivateSuperluData_->LUstruct_);
                                                   ^

/home/projects/sparc/tpls/Trilinos/packages/amesos/src/Amesos_Superludist.cpp(485): error: identifier "DOUBLE" is undefined
          DOUBLE
          ^

/home/projects/sparc/tpls/Trilinos/packages/amesos/src/Amesos_Superludist.cpp(494): error: identifier "EXTRA" is undefined
          EXTRA
          ^

compilation aborted for /home/projects/sparc/tpls/Trilinos/packages/amesos/src/Amesos_Superludist.cpp (code 2)
make[2]: *** [packages/amesos/src/CMakeFiles/amesos.dir/Amesos_Superludist.cpp.o] Error 2
make[1]: *** [packages/amesos/src/CMakeFiles/amesos.dir/all] Error 2
make: *** [all] Error 2

**Comment by srajama1** [comment]
Subsequent update from Micah

Sure enough, it failed.  Is this something that should be fixed with the SuperLU-DIST configure/build?

Thanks,
Micah


From: "Rajamanickam, Sivasankaran (-EXP)" <srajama@sandia.gov>
Date: Monday, March 7, 2016 at 12:28 PM
To: Micah Howard <mhoward@sandia.gov>
Subject: Re: amesos build error in KNL

I don't have access to Morgan. I can access compton or you can just e-mail me the file.

I am looking for these two lines in the configure output.

-- Performing Test HAVE_SUPERLUDIST_LUSTRUCTINIT_2ARG
-- Performing Test HAVE_SUPERLUDIST_LUSTRUCTINIT_2ARG - Success

Thanks
Siva

**Comment by srajama1** [comment]
@jdbooth @trilinos/amesos2

**Comment by nmhamster** [comment]
What SuperLU version are you guys expecting to find? We are running 4.3 on Morgan KNL.

**Comment by srajama1** [comment]
This was reported by Micah on the version you built.

We do a configure time test for SuperLU-Dist version and that compile fails due to some spurious errors which means Amesos2 assumes a wrong version of SuperLU_Dist.

**Comment by nmhamster** [comment]
But you are expecting 4.3? The error looks like it may be expecting something like 5.0. I remember we had this in reverse before.

**Comment by srajama1** [comment]
This is with 4.3 and we can handle 4.3, but because the compile time test failed, Amesos2 thinks it has earlier version of SuperLU-Dist. CMake deletes these temp files so it is a pain to debug.

**Comment by srajama1** [comment]
Josh has a fix.

**Comment by srajama1** [comment]
The problem is with zlib in KNL. Once the right modules are loaded and linked with special zlib things work.
