### ISSUE TITLE
Intrepid2: Uses Kokkos::Cuda when Kokkos_ENABLE_Cuda is OFF

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#1978]
I built with CUDA enabled (`TPL_ENABLE_CUDA:BOOL=ON`), but `Kokkos_ENABLE_Cuda:BOOL=OFF` and `Tpetra_INST_CUDA:BOOL=OFF`.  (A user requested this to work: see #1939.)  This resulted in an Intrepid2 build error:
```
.../Trilinos/packages/intrepid2/unit-test/Discretization/FunctionSpaceTools/Cuda/test_00.cpp: In function ‘int main(int, char**)’:
.../Trilinos/packages/intrepid2/unit-test/Discretization/FunctionSpaceTools/Cuda/test_00.cpp:57:72: error: ‘Cuda’ is not a member of ‘Kokkos’
   const int r_val = Intrepid2::Test::FunctionSpaceTools_Test00<double, Kokkos::Cuda>(verbose);
                                                                        ^
```

@trilinos/intrepid2 

## Possible Solution

The most likely solution is that Intrepid2 needs to test `Kokkos_ENABLE_Cuda`, not `TPL_ENABLE_CUDA`, when deciding whether to use `Kokkos::Cuda` etc.

## Related Issues

Related to #1939 and #1960.

**Comment by mperego** [comment]
@mhoemmen That test is enabled when Kokkos_ENABLE_Cuda_UVM is ON.
Is it possible that Kokkos_ENABLE_Cuda is off but Kokkos_ENABLE_Cuda_UVM is on? Tha would be weird.

**Comment by mhoemmen** [comment]
@mperego wrote:
> Is it possible that `Kokkos_ENABLE_Cuda` is off but `Kokkos_ENABLE_Cuda_UVM` is on? Tha would be weird.

It _is_ weird, but that is exactly what happened ;-) .  The whole use case of #1939 is a bit unusual: the user wants to build Trilinos with the CUDA TPL, while not enabling CUDA in Kokkos.

The only change I would suggest to Intrepid2, is that code that uses `Kokkos::Cuda` (or any CUDA-related memory space or Kokkos feature) _at_ _all_, should test the `Kokkos_ENABLE_Cuda` CMake option or the `KOKKOS_ENABLE_CUDA` macro.  The code in question may also need to test other CMake options or macros.

**Comment by mperego** [comment]
OK, I see. Hopefully commit  498f603 fixed this. Closing..

**Comment by mhoemmen** [comment]
Thanks @mperego !
