### ISSUE TITLE
MiniTensor: Minimizer recovery can trigger FPEs

### ISSUE THREAD

**Issue by ibaned** [trilinos/Trilinos#1979]
@lxmota (PS - a Trilinos organization team for "minitensor" should be created)

## Expectations

When `Minimizer` fails (due to the functional gradient computation failing for example), it should not trigger floating-point exceptions.

## Current Behavior

If the functional gradient method fails but returns an "uninitialized" gradient vector, the gradient vector actually contains all `NaN` values. The `Minimizer` code then goes and takes the norm of this vector, which passes a `NaN` value as the input to `std::sqrt`, which triggers a floating point exception.
https://github.com/trilinos/Trilinos/blob/master/packages/minitensor/src/MiniTensor_Solvers.t.h#L325

## Motivation and Context

This is causing floating point exceptions in the Intel nightly tests of the Albany application

## Definition of Done

 - [ ] All Albany tests involving MiniTensor `Minimizer` need to run without triggering floating point exceptions in that code.

## Possible Solution

Either functionals in Albany need to zero their values before returning from failure, or `Minimizer` needs to stop taking norms of uninitialized values, or possibly zero those values before taking norms in case of failure.

## Steps to Reproduce

Run the `CrystalPlasticity_MultiFamily` test with an Intel build of Albany, with floating point exceptions (FPE) enabled.

**Comment by ibaned** [comment]
Note that we did work around this:
https://github.com/gahansen/Albany/commit/3f77b2f16ed4695582cc8c1402c09bfc0b5b3d52
I just think in general we should discuss the "right" way to exit after failure.

**Comment by lxmota** [comment]
@ibaned @gahansen I agree that we should discuss this.

I use FPEs as a useful tool for debugging in and I prefer that code fails with an FPE close to where the problem occurred. If I mask it or try to recover from it then that obscures what the failure actually is. This is why I like it when FPEs are always caught and I dislike it when they are ignored and NaNs are propagated everywhere. Then it's difficult to find where the problem occurred.

In this particular case of the CP model, I think that zeroing out the vector as you did is most probably the right think to do. @jwfoulk and @calleman21 should chime in about that commit:

https://github.com/gahansen/Albany/commit/3f77b2f16ed4695582cc8c1402c09bfc0b5b3d52
