### ISSUE TITLE
Reducing dependencies between Teuchos sub packages

### ISSUE THREAD

**Issue by mperego** [trilinos/Trilinos#1980]
@jwillenbring  @hkthorn, I was trying to reduce to a minimum the dependencies of Intrepid2 and I found that I need to build most of Teuchos in order to use LAPACK wrappers.

In fact Intrepid2 requires TeuchosNumerics, but TeuchosNumerics requires  TeuchosComm which in turn requires TeuchosParameterList that requires TeuchosParser.

I think the reason why TeuchosNumerics depends on TeuchosComm is because of the MatrixMarket stuff.
Would it be possible to move MatrixMarket in another sub package so that one does not have to build most of Teuchos to use LAPACK wrappers?

I understand it's low priority.. :-)

**Comment by ibaned** [comment]
@trilinos/teuchos 

Maybe an optional dependency from TeuchosNumerics to TeuchosComm?

**Comment by mhoemmen** [comment]
I'm OK with you creating a new subpackage for the Matrix Market stuff.  As far as I know, the only customer right now of that is Tpetra, but now it's part of the public interface of Teuchos.  We could move it to Tpetra, and deprecate in Teuchos, or we could make a new subpackage in Teuchos and put it there, or both.

**Comment by mperego** [comment]
@jwillenbring @kddevin I understand this has low priority but I'd like to keep this issue alive. Any reason for having the MatrixMarket in Teuchos instead of having it in Tpetra?

**Comment by mhoemmen** [comment]
@mperego wrote:
> Any reason for having the MatrixMarket in Teuchos instead of having it in Tpetra?

Hi there! : - )  That's where I put it originally.  I don't work on Trilinos any more, but my guess is that nobody bothered to move it.  The code that lives in Teuchos doesn't depend on Tpetra; you could use it for (say) Epetra or PETSc or something else.

**Comment by kddevin** [comment]
Tpetra has MatrixMarket readers and writers.    The new reader developed in #8472 does not rely on Teuchos' MatrixMarket stuff; it also scales much better than the old version.  @mperego I can show you how to use it.
