### ISSUE TITLE
tpetra classic Kokkos_ConfigDefs.hpp build error in Sierra

### ISSUE THREAD

**Issue by rrdrake** [trilinos/Trilinos#1981]
When trying a Trilinos integration into Sierra, I am getting the following error when building Sierra.  Am I missing something obvious? 

Recall that we configure and install Trilinos then build against that install, except that we define the configure CPP macros ourselves.  The Trilinos build worked, but the Sierra build is not.

This is using GCC 4.9.3.

Thanks,

-rich

> In file included from TPLs_src/Trilinos/packages/tpetra/classic/NodeAPI/Kokkos_DefaultNode.hpp:45:0,
>                  from TPLs_src/Trilinos/packages/tpetra/classic/NodeAPI/Kokkos_DefaultNode.cpp:42:
> TPLs_src/Trilinos/packages/tpetra/classic/src/Kokkos_ConfigDefs.hpp:55:30: error: template declaration of 'Kokkos::Compat::TPETRA_DEPRECATED Kokkos::Compat::NodeDevice'
>      struct TPETRA_DEPRECATED NodeDevice {
>                               ^
> TPLs_src/Trilinos/packages/tpetra/classic/src/Kokkos_ConfigDefs.hpp:56:7: error: expected primary-expression before 'typedef'
>        typedef typename Node::device_type device_type;
>        ^
> TPLs_src/Trilinos/packages/tpetra/classic/src/Kokkos_ConfigDefs.hpp:56:7: error: expected '}' before 'typedef'
> TPLs_src/Trilinos/packages/tpetra/classic/src/Kokkos_ConfigDefs.hpp:59:1: error: expected declaration before '}' token
>  }

@trilinos/tpetra
@jwillenbring

**Comment by jhux2** [comment]
@trilinos/tpetra

**Comment by mhoemmen** [comment]
@rrdrake What's a `Kokkos::Compat::TPETRA_DEPRECATED`?  It looks like the macro is not getting defined correctly in the Jamfile.

**Comment by rrdrake** [comment]
@mhoemmen That was it.  I defined TPETRA_DEPRECATED and the error goes away.  Thanks!

**Comment by mhoemmen** [comment]
@rrdrake Wait a second, does this mean that Sierra would _never_ see Trilinos' deprecated warnings, even if we enabled them?

At the very least, this means that Tpetra has never used a deprecated macro since Sierra first enabled Tpetra.  The deprecated macros come from TriBITS and are package-specific.  (This means that you can enable or disable deprecated warnings per package.)

**Comment by rrdrake** [comment]
@mhoemmen Well a grep of all the bjam files for the word DEPRECATED shows

> dev/TpetraCore/Jamfile:    <define>"TPETRA_DEPRECATED=''"
> dev/TpetraCore/Jamfile:    <cdefine>"'TPETRA_DEPRECATED_MSG(MSG)'"

To get the builds working for Trilinos master, I had to add

> dev/TpetraClassic/Jamfile:    <define>"'TPETRA_DEPRECATED='"

**Comment by mhoemmen** [comment]
@rrdrake Ah, I think I get it.  That macro wasn't used in the TpetraClassic _subpackage_ before.  Thanks! :-D
