### ISSUE TITLE
Panzer: enforce Intrepid2_ENABLE_KokkosDynRankView requirement during CMake configure

### ISSUE THREAD

**Issue by CamelliaDPG** [trilinos/Trilinos#1982]
Panzer will not build properly if `Intrepid2_ENABLE_KokkosDynRankView` is set to `OFF` during CMake configure, but the configure succeeds if it is set that way.  It would be better if the configure failed with an error indicating the requirement.

@trilinos/@panzer

**Comment by jhux2** [comment]
@trilinos/panzer

**Comment by mperego** [comment]
@CamelliaDPG That's an old option used while refactoring Intrepid2. 
Now Intrepid2 only supports Kokkos::DynRankView containers, so we should get rid of that option.
Looking at the code, it seems to me that Panzer uses that option only to decide whether to build or not a few tests. What error do you get if `Intrepid2_ENABLE_KokkosDynRankView` is `OFF`?

**Comment by mperego** [comment]
Commit  34d1aaa should have fixed this by removing that option. I'm closing the issue.
