### ISSUE TITLE
New compilation error in stratimikos Thyra_Amesos2LinearOpWithSolveFactory.cpp

### ISSUE THREAD

**Issue by rrdrake** [trilinos/Trilinos#1983]
I'm getting a new error when compiling Trilinos with GCC 4.7.3

```
from Thyra_Amesos2LinearOpWithSolveFactory.cpp:44

Teuchos_RCP.hpp: In instantiation of ‘Teuchos::RCP<T>::RCP(const Teuchos::RCP<T2>&)
    [with T2 = const Thyra::LinearOpSourceBase<float>; T = const Thyra::LinearOpSourceBase<double>]’

Teuchos_RCP.hpp:289:38: error: cannot convert ‘const Thyra::LinearOpSourceBase<float>*’ to ‘const Thyra::LinearOpSourceBase<double>*’ in initialization
```
Full log: [trilinos_build_error.txt](https://github.com/trilinos/Trilinos/files/1464203/trilinos_build_error.txt)

@trilinos/stratimikos
@trilinos/amesos2

**Comment by rrdrake** [comment]
If it helps, the same file fails to compile with Intel 17:

> Teuchos_RCP.hpp(288): error: a value of type "const Thyra::LinearOpSourceBase<float> *"
> cannot be used to initialize an entity of type "const Thyra::LinearOpSourceBase<double> *"
>    : ptr_(r_ptr.get()), // will not compile if T is not base class of T2

**Comment by mhoemmen** [comment]
Trilinos requires at least GCC 4.8.4 for anything downstream of Kokkos, which Amesos2 is (at least optionally, assuming that Tpetra is enabled).

**Comment by rrdrake** [comment]
Very good.  I can do that.  What about Intel 17?  Is that a different issue?

**Comment by rrdrake** [comment]
For GCC 4.9.2, I get

```
Teuchos_RCP.hpp:289:38: error: cannot convert 'const Thyra::LinearOpSourceBase<float>*' to 'const Thyra::LinearOpSourceBase<double>*' in initialization
     node_(r_ptr.access_private_node())
```

and a little later

```
Teuchos_RCP.hpp:289:38: error: cannot convert 'const Thyra::LinearOpSourceBase<double>*' to 'const Thyra::LinearOpSourceBase<float>*' in initialization
```

**Comment by mhoemmen** [comment]
@rrdrake Intel 17 needs to work.  Also, those build errors look like legit bugs.  Thanks for reporting!

**Comment by mhoemmen** [comment]
"Well, _here's_ your problem":

https://github.com/trilinos/Trilinos/blob/34d1aaae0b563cf625387495940f0c8fdee9f069/packages/stratimikos/adapters/amesos2/src/Thyra_Amesos2LinearOpWithSolveFactory_def.hpp#L340

`fwdOpSrc` (no underscore) is templated on `Scalar`, which is `float` in your case.
```
  RCP<const LinearOpSourceBase<double> > _fwdOpSrc = amesos2Op->extract_fwdOpSrc();
  if(fwdOpSrc) *fwdOpSrc = _fwdOpSrc;
```

It may be enough to change `double` to `Scalar` here, but I'm not sure whether that will work with the Amesos2 operator.

**Comment by mhoemmen** [comment]
OK, this _should_ be fine, since `extract_fwdOpSrc` for Amesos2 returns something templated on `Scalar`:

https://github.com/trilinos/Trilinos/blob/34d1aaae0b563cf625387495940f0c8fdee9f069/packages/stratimikos/adapters/amesos2/src/Thyra_Amesos2LinearOpWithSolve_decl.hpp#L112

The method's _documentation_ is wrong (uses only `double`), but the syntax looks OK.

**Comment by mhoemmen** [comment]
@rrdrake I just pushed a fix to the develop branch, in commit https://github.com/trilinos/Trilinos/commit/efd9284bfe8dc4f9bfc7e41fcab441da70abe08c .  Please feel free to reopen if this is still an issue for you.  Thanks!

**Comment by rrdrake** [comment]
Thanks @mhoemmen !
