### ISSUE TITLE
MueLu: Failing sparse matrix-matrix multiply test: "RAP" not recognized

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#1984]
Tpetra's sparse matrix-matrix multiply test is failing, in a build with kokkos-kernels' "experimental" option enabled.  It looks like the test doesn't recognize the "RAP" option for the operation.  RAP likely stands for the matrix triple product, so I have assigned this issue to @cgcgcg .  Thanks!

Here is an example of a failing test:

https://testing.sandia.gov/cdash/testDetails.php?test=42674607&build=3214083

In particular:
```
 p=0: *** Caught standard std::exception of type 'std::runtime_error' :
 
  .../RELEASE_DEV_KokkosKernels_Experimental/Trilinos/packages/tpetra/core/test/MatrixMatrix/MatrixMatrixKernels_UnitTests.cpp:819:
  
  Throw number = 2
  
  Throw test that evaluated to true: op != "multiply" && op != "add"
  
  Unrecognized Matrix Operation: RAP
 [FAILED]  (0.535 sec) Tpetra_MatMatKernels_double_int_int_Kokkos_Compat_KokkosSerialWrapperNode_operations_test_UnitTest
 Location: .../RELEASE_DEV_KokkosKernels_Experimental/Trilinos/packages/tpetra/core/test/MatrixMatrix/MatrixMatrixKernels_UnitTests.cpp:768
 

The following tests FAILED:
    0. Tpetra_MatMatKernels_double_int_int_Kokkos_Compat_KokkosOpenMPWrapperNode_operations_test_UnitTest ... 
    1. Tpetra_MatMatKernels_double_int_int_Kokkos_Compat_KokkosSerialWrapperNode_operations_test_UnitTest ... 
```

@trilinos/muelu @trilinos/xpetra @trilinos/tpetra 

## Possible Solution

It looks like the test either needs to exercise the RAP operation, or exclude it.  If RAP lives in Tpetra, it would be good for the RAP test to live in Tpetra as well.  It doesn't have to be in this particular test, though.

**Comment by cgcgcg** [comment]
That's indeed the triple matrix product. I don't remember seeing the failure on the dashboard before, but looking at the code, I don't see how it could have passed in debug mode. Funky.

**Comment by cgcgcg** [comment]
Ok, I think I got it.

**Comment by mhoemmen** [comment]
Thanks @cgcgcg !
