### ISSUE TITLE
Teuchos: build failures due to removal of std header includes from Teuchos_Config

### ISSUE THREAD

**Issue by rppawlo** [trilinos/Trilinos#1988]
Seeing lots of failures in trilinos builds for drekar this morning.

Will put up a PR shortly with a bunch of fixes. This affects many packages.

**Comment by rppawlo** [comment]
@mhoemmen

**Comment by ibaned** [comment]
Albany is seeing this too, our build with the Cray compiler failed.

http://my.cdash.org/viewBuildError.php?buildid=1323314

It looks like `Teuchos_CommandLineProcessor.hpp` needs to include`<vector>`, I guess `<numeric>` was hiding this before.

**Comment by ibaned** [comment]
@rppawlo please let me know if you put up a PR, I'd like to grab that if its available.

**Comment by rppawlo** [comment]
Still building - finding more issues in panzer at the moment. It should be up in the next 15 minutes

**Comment by rppawlo** [comment]
@ibaned - PR is up, #1989 . I might have a few more as we build more apps like Charon.

**Comment by mhoemmen** [comment]
Well, I had to do this somehow.  @prwolfe has been wanting this for years.  Should `Teuchos_ConfigDefs.hpp` really include every single possible header file?

**Comment by mhoemmen** [comment]
@ibaned wrote:
> It looks like Teuchos_CommandLineProcessor.hpp needs to include<vector>, I guess <numeric> was hiding this before.

Huh, I tested TeuchosCore and everything downstream from it in Trilinos.

**Comment by ibaned** [comment]
@mhoemmen this only fails for Albany with the Cray compiler. I think different compilers have different amounts of tolerance for not including STL headers, it may be that GCC includes `<vector>` from some other STL header thats already included. I don't know how many configurations @rppawlo sees failures in.

**Comment by rppawlo** [comment]
@mhoemmen - not complaining. It's great that you did this! Hoping it drops compile times. I've got the checkin test script running now for PR. I put this issue up so that multiple people don't spend time fixing the same issues.

**Comment by ibaned** [comment]
Yea, I agree this is a good move.

> I put this issue up so that multiple people don't spend time fixing the same issues.

Which was definitely also a good move, because I was about to try fixing the same issues.

**Comment by rppawlo** [comment]
I'm running gcc 7.2 and they recently cleaned out stl includes so this might only be needed for more recent compilers than we test with sems.

**Comment by mhoemmen** [comment]
@rppawlo Huh, that's weird.  I looked at your PR and it looks fine to me.

C++14 / 17 may have changed what standard headers include what other standard headers.

**Comment by ibaned** [comment]
@trilinos/framework should probably add a build (not sure if `Specialized` or `Clean`) that uses GCC 7.2. Several Albany (and apparently Drekar) developers have adopted this compiler, and it will only become more popular over time.

**Comment by mhoemmen** [comment]
@rppawlo I approved your PR.  Thanks for the fixes.

**Comment by ibaned** [comment]
@mhoemmen : I think @rppawlo was already running the checkin script which would have merged his PR. We need to be careful not to doubly merge things.
@rppawlo : since @mhoemmen just merged it manually, can you please kill your checkin script?

**Comment by rppawlo** [comment]
Thanks for the heads up. I just killed the checkin-test script. Thanks for merging too!

**Comment by jwillenbring** [comment]
@ibaned I agree we will need a GCC 7.2 build. Generally we like to wait until we have something beyond the .0 release. If you see 7.2.1 come out, please file a ticket to add a build, or to SEMS to add a compiler to the NFS mount.

**Comment by ibaned** [comment]
@jwillenbring I think that policy needs revisiting. According to [this page](https://gcc.gnu.org/releases.html), there have been no three-number releases for major versions 5, 6, or 7.

**Comment by ibaned** [comment]
@jwillenbring please see "Version Numbering Scheme for GCC 5 and Up" on [this page](https://gcc.gnu.org/develop.html). The patch number is now just for internal GCC developers to denote stable versus experimental, all releases to the public appear to be two-number.
