### ISSUE TITLE
BelosSolverManager.hpp update broke build.

### ISSUE THREAD

**Issue by bathmatt** [trilinos/Trilinos#199]
@amklinv 
Your latest push broke the build

[ 65%] Building CXX object packages/belos/src/CMakeFiles/belos.dir/Belos_Details_registerLinearSolverFactory.cpp.o
[ 68%] Built target ml
In file included from <https://jenkins-srn.sandia.gov:8443/job/Drekar-opt/ws/Trilinos/packages/belos/src/BelosSolverFactory.hpp>:47:0,
                 from <https://jenkins-srn.sandia.gov:8443/job/Drekar-opt/ws/Trilinos/packages/belos/src/Belos_Details_LinearSolverFactory.hpp>:48,
                 from <https://jenkins-srn.sandia.gov:8443/job/Drekar-opt/ws/Trilinos/packages/belos/src/Belos_Details_registerLinearSolverFactory.cpp>:43:
<https://jenkins-srn.sandia.gov:8443/job/Drekar-opt/ws/Trilinos/packages/belos/src/BelosSolverManager.hpp>:143:20: error: expected nested-name-specifier before ‘StatusTestCombo’
     const typename StatusTestCombo<ScalarType,MV,OP>::ComboType &comboType =
                    ^
<https://jenkins-srn.sandia.gov:8443/job/Drekar-opt/ws/Trilinos/packages/belos/src/BelosSolverManager.hpp>:143:35: error: expected ‘,’ or ‘...’ before ‘<’ token
     const typename StatusTestCombo<ScalarType,MV,OP>::ComboType &comboType =
                                   ^
make[2]: *** [packages/belos/src/CMakeFiles/belos.dir/Belos_Details_registerLinearSolverFactory.cpp.o] Error 1
make[1]: *** [packages/belos/src/CMakeFiles/belos.dir/all] Error 2
make: *** [all] Error 2

**Comment by amklinv** [comment]
Sorry!  I'm pushing the fix right now.

**Comment by amklinv** [comment]
There was a missing include file; it should be fixed now.  Sorry for the inconvenience.  Can you please try it again and close out the issue if it works for you?

**Comment by bathmatt** [comment]
fixed
