### ISSUE TITLE
Trilinos compilation error due to TriKota

### ISSUE THREAD

**Issue by ikalash** [trilinos/Trilinos#1993]
I built Trilinos with TriKota as a part of Albany nightly testing.  Last night, I got the following compilation error due to TriKota: 

```/home/ikalash/nightlyAlbanyTests/Results/Trilinos/packages/TriKota/Dakota/src/dakota_data_types.hpp:56:14: error: ‘deque’ in namespace ‘std’ does not name a template type
 typedef std::deque<bool> BoolDeque; // See Meyers' Effective STL #18
              ^~~~~
/home/ikalash/nightlyAlbanyTests/Results/Trilinos/packages/TriKota/Dakota/src/dakota_data_types.hpp:59:21: error: ‘BoolDeque’ was not declared in this scope
 typedef std::vector<BoolDeque>      BoolDequeArray;
                     ^~~~~~~~~
/home/ikalash/nightlyAlbanyTests/Results/Trilinos/packages/TriKota/Dakota/src/dakota_data_types.hpp:59:30: error: template argument 1 is invalid
 typedef std::vector<BoolDeque>      BoolDequeArray;
                              ^
/home/ikalash/nightlyAlbanyTests/Results/Trilinos/packages/TriKota/Dakota/src/dakota_data_types.hpp:59:30: error: template argument 2 is invalid
[ 26%] Building CXX object packages/TriKota/Dakota/packages/external/DDACE/src/CMakeFiles/ddace.dir/Random/NormalDistribution.cpp.o
[ 26%] Building CXX object packages/TriKota/Dakota/packages/external/DDACE/src/CMakeFiles/ddace.dir/Random/PseudoRandomTestsOnly.cpp.o
/home/ikalash/nightlyAlbanyTests/Results/Trilinos/packages/TriKota/Dakota/src/dakota_data_types.hpp:127:14: error: ‘set’ in namespace ‘std’ does not name a template type
 typedef std::set<Real>                 RealSet;'''

I am getting Dakota as follows:

wget -nv --no-check-certificate https://dakota.sandia.gov/sites/default/files/distributions/public/dakota-6.5-public.src.tar.gz -v

Should I be using a different dakota?

**Comment by mhoemmen** [comment]
Uh oh... taking header files out of Teuchos_ConfigDefs.hpp may have broken Dakota.  It wouldn't have broken Dakota as a stand-alone product, since they snapshot in (and patch) their own Teuchos, but it might have broken Dakota built as TriKota.

@briadam help what do I do?

**Comment by briadam** [comment]
Hmm, looks like a solid Dakota bug to me.  Setting aside the fact that we really should separate Dakota's headers into those that include std libraries vs. those that require Teuchos, it looks like there are several data types in that header that don't have proper standard library includes.  All of them need to be added to dakota_data_types.hpp or possibly dakota_system_defs.hpp.  Should be an easy patch, but we may have to lean on you all for acceptance testing unless I can get Dakota to build with current Teuchos.

**Comment by ikalash** [comment]
Once there is a patch to Dakota, I'm happy to switch my nightly builds to use the version of Dakota with the patch.  Just let me know when the patch is pushed and what Dakota version has it.

**Comment by briadam** [comment]
I just pushed a fixed to Dakota's devel branch, which is available by anonymous clone from https://software.sandia.gov/git/dakota.  Assuming tests pass, it should get promoted to the master branch overnight.  I'm also including it here if you prefer to include a patch step in your build flow: https://gist.github.com/briadam/aa43d6e6c6944472bb9502f403bb64ff

**Comment by juan42** [comment]
This triggers a PECOS issue during the TriKota build as well. It is easily fixable by adding the missing includes in related headers.

**Comment by briadam** [comment]
@juan42 Makes sense; thanks.  I'll post back when addressed.

**Comment by mhoemmen** [comment]
Thanks @briadam ! :-D

**Comment by briadam** [comment]
Okay I just updated pecos devel branch and dakota's submodule SHA1 to pull it.  I only found one missing header in pecos for std::list.  

'''
diff --git a/src/pecos_data_types.hpp b/src/pecos_data_types.hpp
index f29d8f5..4832551 100644
--- a/src/pecos_data_types.hpp
+++ b/src/pecos_data_types.hpp
@@ -26,6 +26,7 @@
 
 #include <algorithm>  // for std::find
 #include <complex>
+#include <list>
 #include <map>
 #include <set>
 #include <string>
'''


Let me know if problems remain.

**Comment by briadam** [comment]
Actually right after pushing I realized there are probably downstream files in pecos that break.  Might require more work.  Let me see if a make -k will ferret them out as I don't have a Dakota against external Trilinos handy right now.

**Comment by briadam** [comment]
Decided to stop whining and build/install Trilinos and Dakota against it.  I think I found the one remaining include issue and pushed a fix, but again, holler if issues.

**Comment by mhoemmen** [comment]
@briadam Thanks! :D

**Comment by rhoope** [comment]
@briadam One more old issue related to TriKota.  Can we close this one too?

**Comment by briadam** [comment]
Seems so, since over two years old. Will need @ikalash or a maintainer to close, it seems.

**Comment by ikalash** [comment]
Yes this can be closed.  Sorry for not doing it earlier!
