### ISSUE TITLE
MueLu: Move PerfUtils::PrintMatrixInfo stuff to Extreme output (rather than high)

### ISSUE THREAD

**Issue by csiefer2** [trilinos/Trilinos#1997]
MPI-P results suggest that these guys represent around 20% of the total number of call locations in the MueLu driver (setup only) when run with high verbosity --- we get load balance and comm info for P and Ac.

For example:
    P size =  1700 x 204
     P Load balancing info
     P   # active processes: 2/2
     P   # rows per proc   : avg = 8.50e+02,  dev =   0.0%,  min =   +0.0%,  max =   +0.0%
     P   #  nnz per proc   : avg = 2.40e+03,  dev =   0.0%,  min =   +0.0%,  max =   +0.0%
     P Communication info
     P   # num export send : avg =     0.00,  dev =   0.00,  min =    0.0 ,  max =    0.0
     P   # num import send : avg = 1.70e+01,  dev =   0.0%,  min =   +0.0%,  max =   +0.0%
     P   # num msgs        : avg =     1.00,  dev =   0.00,  min =    1.0 ,  max =    1.0
     P   # min msg size    : avg = 1.70e+01,  dev =   0.0%,  min =   +0.0%,  max =   +0.0%
     P   # max msg size    : avg = 1.70e+01,  dev =   0.0%,  min =   +0.0%,  max =   +0.0%

Can we just limit this output to verb extreme by default?

**Comment by jhux2** [comment]
@csiefer2 I agree with moving the matrix statistics to one louder.  @tawiesn, @aprokop and I started a document to categorize what should go where.  I'll find it and share with you.

There's a certain amount of info in the multigrid summary (e.g., active processes) that was probably already known but just thrown away. MueLu should really keep it, rather than regenerating.

**Comment by aprokop** [comment]
@csiefer2 Does MPI-P show the total amount of time spent in those calls? I assume that's a lot less than 20%.

**Comment by csiefer2** [comment]
@aprokop I got data from a desktop run w/ 2 ranks.  The timers are basically worthless.

I like @jhux2's idea about being more intentional about output.

**Comment by csiefer2** [comment]
This immediate task is done.
