### ISSUE TITLE
shylu build failure:  gtest/gtest.h: No such file or directory

### ISSUE THREAD

**Issue by nschloe** [trilinos/Trilinos#1999]
Since recently, I'm getting build failures like
```
/path/to/packages/shylu/shylu_node/tacho/unit-test/Tacho_TestSerial_double.cpp:1:25:
 fatal error: gtest/gtest.h: No such file or directory
 #include <gtest/gtest.h>
                         ^
```
on master ([full details](https://launchpadlibrarian.net/345861590/buildlog_ubuntu-zesty-amd64.trilinos_12.13~git201711150649-efee3717-1zesty1_BUILDING.txt.gz)). Installing `libgtest-dev` probably fixes this, but I guess this sort of compile error wants to be intercepted by CMake; see [`FindGTest`](https://cmake.org/cmake/help/v3.0/module/FindGTest.html).

**Comment by jhux2** [comment]
@trilinos/shylu

**Comment by kyungjoo-kim** [comment]
This is weird. As far as I see from the cmake output, 
- Gtest is explicitly disabled
- So Tacho test/examplesa are also disabled even if the package is enabled
- However, the error says that it attempts to compile the unit tests.
- This seems to be a cmake error.

```
Explicitly disabled packages on input (by user or by default):  Gtest 

-- Setting ShyLU_NodeTacho_ENABLE_TESTS=OFF because ShyLU_NodeTacho has a required test/example dependence on disabled package Gtest
-- Setting ShyLU_NodeTacho_ENABLE_EXAMPLES=OFF because ShyLU_NodeTacho has a required test/example dependence on disabled package Gtest

Final set of enabled SE packages:   ShyLU_NodeTacho, etc.
```

**Comment by kyungjoo-kim** [comment]
@bartlettroscoe Could you look at this problem ? I think that tribits should set the cmake variable ``ShyLU_NodeTacho_ENABLE_TESTS:BOOL=OFF`` but it does not.

**Comment by bartlettroscoe** [comment]
> @bartlettroscoe Could you look at this problem ? I think that tribits should set the cmake variable `ShyLU_NodeTacho_ENABLE_TESTS:BOOL=OFF` but it does not.

This output also shows:

```
-- Setting ShyLU_Node_ENABLE_TESTS=ON
```

What is happening is a result of the behavior described at:

* https://tribits.org/doc/TribitsDevelopersGuide.html#tribits-add-test-directories

which will try to enable tests if either `${PACKAGE_NAME}_ENABLE_TESTS` or `${PARENT_PACKAGE_NAME}_ENABLE_TESTS` are `TRUE`.  This has the current implementation:

```
MACRO(TRIBITS_ADD_TEST_DIRECTORIES)

  IF(${PACKAGE_NAME}_ENABLE_TESTS OR ${PARENT_PACKAGE_NAME}_ENABLE_TESTS)
    FOREACH(TEST_DIR ${ARGN})
      TRIBITS_TRACE_FILE_PROCESSING(PACKAGE  ADD_SUBDIR
        "${CMAKE_CURRENT_SOURCE_DIR}/${TEST_DIR}/CMakeLists.txt")
      ADD_SUBDIRECTORY(${TEST_DIR})
    ENDFOREACH()
  ENDIF()

ENDMACRO()
```

This allows you to say, for example:

```
-DTrilinos_ENABLE_Teuchos=ON \
-DTeuchos_ENABLE_TESTS=ON \
```

and get all of tests in the eanbled Teuchos subpackages to be turned on.  But we can see where this logic has a flaw.  If you set:

```
-DTrilinos_ENABLE_Teuchos=ON \
-DTeuchos_ENABLE_TESTS=ON \
-DTeuchosNumerics_ENABLE_TESTS=OFF \
```

it will still try to enable the subpackage `TeuchosNumerics` tests which is what is happening here for ShyLU_Node.  This is not good behavior.

So the way to fix this is to change the implementation to:

```
MACRO(TRIBITS_ADD_TEST_DIRECTORIES)

  IF (NOT "${${PACKAGE_NAME}_ENABLE_TESTS}" STREQUAL ""
    AND
    NOT ${PACKAGE_NAME}_ENABLE_TESTS
    )
    # Explicitly disabled this (sub)package's tests!
    SET(${PACKAGE_NAME}_ADD_TEST_DIRECTORIES FALSE)
  ELSEIF (${PACKAGE_NAME}_ENABLE_TESTS OR ${PARENT_PACKAGE_NAME}_ENABLE_TESTS)
    # Parent package's tests or this (sub)package's tests are enabled
    SET(${PACKAGE_NAME}_ADD_TEST_DIRECTORIES TRUE)
  ELSE()
    # Neither parent package's tests or this (sub)package's tests are enabled
    SET(${PACKAGE_NAME}_ADD_TEST_DIRECTORIES FALSE)
  FALSE()

  IF (${PACKAGE_NAME}_ADD_TEST_DIRECTORIES)
    FOREACH(TEST_DIR ${ARGN})
      TRIBITS_TRACE_FILE_PROCESSING(PACKAGE  ADD_SUBDIR
        "${CMAKE_CURRENT_SOURCE_DIR}/${TEST_DIR}/CMakeLists.txt")
      ADD_SUBDIRECTORY(${TEST_DIR})
    ENDFOREACH()
  ENDIF()

ENDMACRO()
```

I will create a TriBITS GitHub issue to fix this.

Does this issue just need to get fixed on the 'develop' (and then 'master') version of Trilinos?

**Comment by bartlettroscoe** [comment]
In the meantime, you if set `-DShyLU_Node_ENABLE_TESTS=OFF`, you will avoid this problem.  Otherwise, the fix can be snapshotted and merged to Trilinos 'develop' soon.

**Comment by kyungjoo-kim** [comment]
@bartlettroscoe Thank you for the explanation. 

@nschloe Following the advice from @bartlettroscoe, would you be okay with ``-DShyLU_Node_ENABLE_TESTS=OFF`` for now ? The fix will be placed soon.

**Comment by nschloe** [comment]
There's no particular urgency for me, so I'll just wait for the fix to hit
master.

**Comment by kyungjoo-kim** [comment]
@bartlettroscoe  Did we fix the tribit issue ?

**Comment by bartlettroscoe** [comment]
> @bartlettroscoe Did we fix the tribit issue ? If so, do we have a reference PR number ?

@kyungjoo-kim, shoot, it looks like I forgot to follow up on this.  This is a another example of where the current logic for handling tests for packages and subpackages is not correct.

I will create a TriBITS issue right now that addresses this problem once and for all for all use cases (hopefully) and will be more logical (hopefully).

**Comment by bartlettroscoe** [comment]
FYI: I created TriBITSPub/TriBITS#268 to address this and related problems for test/example enable/disable logic once and for all.

How urgent is it to resolve this issue?  I would assume this is not a problem for Trilinos testing and most customers since they would not be disabling GTest, and if they were, they would not care to be enabling tests in Trilinos.

@nschloe, so why would you want to enable tests in Trilinos but not enable GTest?  There are a lot of tests in Trilinos that will not be built and run if you disable the GTest package.  Is it just because you don't want to install GTest?
