### ISSUE TITLE
MueLu: build failures on nightly track

### ISSUE THREAD

**Issue by jhux2** [trilinos/Trilinos#2001]
There are nightly build failures on the MueLu dashboard.  The issue actually appears to be upstream in Xpetra, and is due to implicit dependence on standard headers that were recently removed from Teuchos_Configdefs.hpp.  The fix should be straightforward.

**Comment by jhux2** [comment]
"I'm sorry, Dave, I'm afraid I can't do that."

**Comment by jhux2** [comment]
After fixing this, I discovered that I needed to add an include of <set> to a MueLu unit test header file and MueLu_BlockedPFactory.  Checkin script is running.

**Comment by jhux2** [comment]
Nightly tests are clean.  Closing.

**Comment by mhoemmen** [comment]
@jhux2 -- just curious; how come I didn't see those?  I totally ran the check-in test script and also build everything downstream by hand.  Did these depend on some nondefault CMake options?

**Comment by jhux2** [comment]
@mhoemmen These are in the MueLu nightly and specialized tracks, so it's very likely the default checkin configurations wouldn't have caught these.
