### ISSUE TITLE
Question: can checkin script verify current branch is "develop" before configure/build?

### ISSUE THREAD

**Issue by jhux2** [trilinos/Trilinos#2003]
I invoke the checkin process via the script "checkin-test.py".  When I ran it today, I was accidentally on the master branch, so the push failed.

Does the checkin script have an option for verfiying that the current branch is `develop` prior to configuring and building?  This would have saved me a configure/build cycle.

@trilinos/framework 
@bartlettroscoe

**Comment by bartlettroscoe** [comment]
@jhux2,

> Does the checkin script have an option for verfiying that the current branch is develop prior to configuring and building?

It does not and I am not sure we want to hard-code that.  The script is designed to push to any tracking branch (including to a Trilinos release branch).  My suggestion is to delete your local 'master' branch so you can't make this mistake like is suggested at the bottom of:

* https://github.com/trilinos/Trilinos/wiki/VC-%7C-Initial-Git-Setup

and on:

* https://github.com/trilinos/Trilinos/wiki/VC-%7C-'develop'-'master'-workfow-cheat-sheet

But if you want to ensure that you are always on the 'develop' branch when you run the checkin-test-sems.sh script (or your local checkin-test.py driver script), you can write your own very short wrapper script that checks that your Trilinos repo is on the 'develop' branch and then calls the checkin-test.py driver script.  I can write that script for you if you want.  It is only a few lines of bash shell code.

**Comment by jhux2** [comment]
@bartlettroscoe Thanks for the information.  I'll go ahead and wrap the checkin script, I just wanted to check first if there was such an option.

**Comment by jhux2** [comment]
For the record:
```
#!/bin/bash

BRANCH=`cd .. && git rev-parse --abbrev-ref HEAD`

if [ $BRANCH == "develop" ]; then
  ../checkin-test.py --ctest-timeout=1200 --do-all -j 50 --push
else
  echo "You're on branch \"$BRANCH\".  Switch to \"develop\" first."
fi
```
