### ISSUE TITLE
Make failed at [ 99%] Built target Stokhos_TpetraCrsMatrixMPVectorUnitTest_Serial

### ISSUE THREAD

**Issue by lkkevin** [trilinos/Trilinos#2005]
Hi,

I am trying to build Trilinos 12.12.1 for Peridigm on CentOS 7.4. The "make -j 2" failed at 99%] Built target Stokhos_TpetraCrsMatrixMPVectorUnitTest_Serial. I have been working on this issue for a couple day but could not figure out. Please help. Thanks.

#------ These are the prerequisites that i installed on my VM: -----#
boost_1_65_1 , cmake-3.10.0-rc5, hdf5-1.10.1, matio-1.5.11, netcdf-c-4.5.0, openmpi-3.0.0, blas 3.8.0, lapack 3.8.0.

#------ This is the CMakeError.log ------#
Determining if the pthread_create exist failed with the following output:
Change Dir: /root/Downloads/trilinos-12.12.1-Source/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/gmake" "cmTC_6fe30/fast"
/usr/bin/gmake -f CMakeFiles/cmTC_6fe30.dir/build.make CMakeFiles/cmTC_6fe30.dir/build
gmake[1]: Entering directory `/root/Downloads/trilinos-12.12.1-Source/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_6fe30.dir/CheckSymbolExists.c.o
/opt/mpich/bin/mpicc   -O3 -DNDEBUG   -o CMakeFiles/cmTC_6fe30.dir/CheckSymbolExists.c.o   -c /root/Downloads/trilinos-12.12.1-Source/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c
Linking C executable cmTC_6fe30
/usr/local/bin/cmake -E cmake_link_script CMakeFiles/cmTC_6fe30.dir/link.txt --verbose=1
/opt/mpich/bin/mpicc   -O3 -DNDEBUG    -rdynamic CMakeFiles/cmTC_6fe30.dir/CheckSymbolExists.c.o  -o cmTC_6fe30
/usr/bin/ld: CMakeFiles/cmTC_6fe30.dir/CheckSymbolExists.c.o: undefined reference to symbol 'pthread_create@@GLIBC_2.2.5'
/usr/lib64/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
gmake[1]: *** [cmTC_6fe30] Error 1
gmake[1]: Leaving directory `/root/Downloads/trilinos-12.12.1-Source/build/CMakeFiles/CMakeTmp'
gmake: *** [cmTC_6fe30/fast] Error 2

File /root/Downloads/trilinos-12.12.1-Source/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */
#include <pthread.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef pthread_create
  return ((int*)(&pthread_create))[argc];
#else
  (void)argc;
  return 0;
#endif
}

Determining if the function pthread_create exists in the pthreads failed with the following output:
Change Dir: /root/Downloads/trilinos-12.12.1-Source/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/gmake" "cmTC_59d00/fast"
/usr/bin/gmake -f CMakeFiles/cmTC_59d00.dir/build.make CMakeFiles/cmTC_59d00.dir/build
gmake[1]: Entering directory `/root/Downloads/trilinos-12.12.1-Source/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_59d00.dir/CheckFunctionExists.c.o
/opt/mpich/bin/mpicc   -DCHECK_FUNCTION_EXISTS=pthread_create -O3 -DNDEBUG   -o CMakeFiles/cmTC_59d00.dir/CheckFunctionExists.c.o   -c /usr/local/share/cmake-3.10/Modules/CheckFunctionExists.c
Linking C executable cmTC_59d00
/usr/local/bin/cmake -E cmake_link_script CMakeFiles/cmTC_59d00.dir/link.txt --verbose=1
/opt/mpich/bin/mpicc  -DCHECK_FUNCTION_EXISTS=pthread_create -O3 -DNDEBUG    -rdynamic CMakeFiles/cmTC_59d00.dir/CheckFunctionExists.c.o  -o cmTC_59d00 -lpthreads
/usr/bin/ld: cannot find -lpthreads
collect2: error: ld returned 1 exit status
gmake[1]: *** [cmTC_59d00] Error 1
gmake[1]: Leaving directory `/root/Downloads/trilinos-12.12.1-Source/build/CMakeFiles/CMakeTmp'
gmake: *** [cmTC_59d00/fast] Error 2
Performing C++ SOURCE FILE Test HAVE_TEUCHOS_LAPACKLARND failed with the following output:
Change Dir: /root/Downloads/trilinos-12.12.1-Source/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/gmake" "cmTC_d5eb7/fast"
/usr/bin/gmake -f CMakeFiles/cmTC_d5eb7.dir/build.make CMakeFiles/cmTC_d5eb7.dir/build
gmake[1]: Entering directory `/root/Downloads/trilinos-12.12.1-Source/build/CMakeFiles/CMakeTmp'
Building CXX object CMakeFiles/cmTC_d5eb7.dir/src.cxx.o
/opt/mpich/bin/mpicxx    -O2 -std=c++11 -pedantic -ftrapv -Wall -Wno-long-long -std=c++11 -DHAVE_TEUCHOS_LAPACKLARND -O3 -DNDEBUG   -o CMakeFiles/cmTC_d5eb7.dir/src.cxx.o -c /root/Downloads/trilinos-12.12.1-Source/build/CMakeFiles/CMakeTmp/src.cxx
/root/Downloads/trilinos-12.12.1-Source/build/CMakeFiles/CMakeTmp/src.cxx: In function ‘int main()’:
/root/Downloads/trilinos-12.12.1-Source/build/CMakeFiles/CMakeTmp/src.cxx:12:38: warning: narrowing conversion of ‘0.0’ from ‘double’ to ‘int’ inside { } [-Wnarrowing]
   int seed[4] = { 0.0, 0.0, 0.0, 1.0 };
                                      ^
/root/Downloads/trilinos-12.12.1-Source/build/CMakeFiles/CMakeTmp/src.cxx:12:38: warning: narrowing conversion of ‘0.0’ from ‘double’ to ‘int’ inside { } [-Wnarrowing]
/root/Downloads/trilinos-12.12.1-Source/build/CMakeFiles/CMakeTmp/src.cxx:12:38: warning: narrowing conversion of ‘0.0’ from ‘double’ to ‘int’ inside { } [-Wnarrowing]
/root/Downloads/trilinos-12.12.1-Source/build/CMakeFiles/CMakeTmp/src.cxx:12:38: warning: narrowing conversion of ‘1.0e+0’ from ‘double’ to ‘int’ inside { } [-Wnarrowing]
Linking CXX executable cmTC_d5eb7
/usr/local/bin/cmake -E cmake_link_script CMakeFiles/cmTC_d5eb7.dir/link.txt --verbose=1
/opt/mpich/bin/mpicxx    -O2 -std=c++11 -pedantic -ftrapv -Wall -Wno-long-long -std=c++11 -DHAVE_TEUCHOS_LAPACKLARND -O3 -DNDEBUG    -rdynamic CMakeFiles/cmTC_d5eb7.dir/src.cxx.o  -o cmTC_d5eb7 -Wl,-rpath,/opt/lib/LAPACK /opt/lib/LAPACK/liblapack.so
CMakeFiles/cmTC_d5eb7.dir/src.cxx.o: In function `main':
src.cxx:(.text.startup+0x22): undefined reference to `dlarnd_'
collect2: error: ld returned 1 exit status
gmake[1]: *** [cmTC_d5eb7] Error 1
gmake[1]: Leaving directory `/root/Downloads/trilinos-12.12.1-Source/build/CMakeFiles/CMakeTmp'
gmake: *** [cmTC_d5eb7/fast] Error 2

Return value: 1
Source file was:

#define F77_BLAS_MANGLE(name,NAME) name ## _

#define DLARND_F77   F77_BLAS_MANGLE(dlarnd,DLARND)

extern "C" { double DLARND_F77(const int* idist, int* seed); }

int main()
{

  const int idist = 1;
  int seed[4] = { 0.0, 0.0, 0.0, 1.0 };

  double val = DLARND_F77(&idist, seed);

  return (val < 0.0 ? 1 : 0);
}

Performing C++ SOURCE FILE Test HAVE_CXX_PRAGMA_WEAK failed with the following output:
Change Dir: /root/Downloads/trilinos-12.12.1-Source/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/gmake" "cmTC_32f82/fast"
/usr/bin/gmake -f CMakeFiles/cmTC_32f82.dir/build.make CMakeFiles/cmTC_32f82.dir/build
gmake[1]: Entering directory `/root/Downloads/trilinos-12.12.1-Source/build/CMakeFiles/CMakeTmp'
Building CXX object CMakeFiles/cmTC_32f82.dir/src.cxx.o
/opt/mpich/bin/mpicxx    -O2 -std=c++11 -pedantic -ftrapv -Wall -Wno-long-long -std=c++11 -DHAVE_CXX_PRAGMA_WEAK -O3 -DNDEBUG   -o CMakeFiles/cmTC_32f82.dir/src.cxx.o -c /root/Downloads/trilinos-12.12.1-Source/build/CMakeFiles/CMakeTmp/src.cxx
Linking CXX executable cmTC_32f82
/usr/local/bin/cmake -E cmake_link_script CMakeFiles/cmTC_32f82.dir/link.txt --verbose=1
/opt/mpich/bin/mpicxx    -O2 -std=c++11 -pedantic -ftrapv -Wall -Wno-long-long -std=c++11 -DHAVE_CXX_PRAGMA_WEAK -O3 -DNDEBUG    -rdynamic CMakeFiles/cmTC_32f82.dir/src.cxx.o  -o cmTC_32f82
CMakeFiles/cmTC_32f82.dir/src.cxx.o: In function `main':
src.cxx:(.text.startup+0x1c): undefined reference to `A::theFunction()'
collect2: error: ld returned 1 exit status
gmake[1]: *** [cmTC_32f82] Error 1
gmake[1]: Leaving directory `/root/Downloads/trilinos-12.12.1-Source/build/CMakeFiles/CMakeTmp'
gmake: *** [cmTC_32f82/fast] Error 2

Source file was:

#include <iostream>

namespace A {
// theFunction never gets defined, because we
// don't link with a library that defines it.
// That's OK, because it's weak linkage.
#pragma weak theFunction
extern void theFunction ();
}

int main() {
  std::cout << "Hi!  I am main." << std::endl;
  if (A::theFunction != NULL) {
    // Should never be called, since we don't link
    // with a library that defines A::theFunction.
    A::theFunction ();
  }
  return 0;
}

Determining if the function dggsvd3 exists failed with the following output:
Change Dir: /root/Downloads/trilinos-12.12.1-Source/build/CMakeFiles/CMakeTmp
Run Build Command:"/usr/bin/gmake" "cmTC_a3af9/fast"
/usr/bin/gmake -f CMakeFiles/cmTC_a3af9.dir/build.make CMakeFiles/cmTC_a3af9.dir/build
gmake[1]: Entering directory `/root/Downloads/trilinos-12.12.1-Source/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_a3af9.dir/CheckFunctionExists.c.o
/opt/mpich/bin/mpicc   -DCHECK_FUNCTION_EXISTS=dggsvd3 -O3 -DNDEBUG   -o CMakeFiles/cmTC_a3af9.dir/CheckFunctionExists.c.o   -c /usr/local/share/cmake-3.10/Modules/CheckFunctionExists.c
Linking C executable cmTC_a3af9
/usr/local/bin/cmake -E cmake_link_script CMakeFiles/cmTC_a3af9.dir/link.txt --verbose=1
/opt/mpich/bin/mpicc  -DCHECK_FUNCTION_EXISTS=dggsvd3 -O3 -DNDEBUG    -rdynamic CMakeFiles/cmTC_a3af9.dir/CheckFunctionExists.c.o  -o cmTC_a3af9  -L/opt/lib/BLAS -Wl,-rpath,/opt/lib/LAPACK:/opt/lib/BLAS /opt/lib/LAPACK/liblapack.so -lblas
CMakeFiles/cmTC_a3af9.dir/CheckFunctionExists.c.o: In function `main':
CheckFunctionExists.c:(.text.startup+0xc): undefined reference to `dggsvd3'
collect2: error: ld returned 1 exit status
gmake[1]: *** [cmTC_a3af9] Error 1
gmake[1]: Leaving directory `/root/Downloads/trilinos-12.12.1-Source/build/CMakeFiles/CMakeTmp'
gmake: *** [cmTC_a3af9/fast] Error 2

Determining if the function DGGSVD3 exists failed with the following output:
Change Dir: /root/Downloads/trilinos-12.12.1-Source/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/gmake" "cmTC_1a133/fast"
/usr/bin/gmake -f CMakeFiles/cmTC_1a133.dir/build.make CMakeFiles/cmTC_1a133.dir/build
gmake[1]: Entering directory `/root/Downloads/trilinos-12.12.1-Source/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_1a133.dir/CheckFunctionExists.c.o
/opt/mpich/bin/mpicc   -DCHECK_FUNCTION_EXISTS=DGGSVD3 -O3 -DNDEBUG   -o CMakeFiles/cmTC_1a133.dir/CheckFunctionExists.c.o   -c /usr/local/share/cmake-3.10/Modules/CheckFunctionExists.c
Linking C executable cmTC_1a133
/usr/local/bin/cmake -E cmake_link_script CMakeFiles/cmTC_1a133.dir/link.txt --verbose=1
/opt/mpich/bin/mpicc  -DCHECK_FUNCTION_EXISTS=DGGSVD3 -O3 -DNDEBUG    -rdynamic CMakeFiles/cmTC_1a133.dir/CheckFunctionExists.c.o  -o cmTC_1a133  -L/opt/lib/BLAS -Wl,-rpath,/opt/lib/LAPACK:/opt/lib/BLAS /opt/lib/LAPACK/liblapack.so -lblas
CMakeFiles/cmTC_1a133.dir/CheckFunctionExists.c.o: In function `main':
CheckFunctionExists.c:(.text.startup+0xc): undefined reference to `DGGSVD3'
collect2: error: ld returned 1 exit status
gmake[1]: *** [cmTC_1a133] Error 1
gmake[1]: Leaving directory `/root/Downloads/trilinos-12.12.1-Source/build/CMakeFiles/CMakeTmp'
gmake: *** [cmTC_1a133/fast] Error 2

Determining if the function DGGSVD3_ exists failed with the following output:
Change Dir: /root/Downloads/trilinos-12.12.1-Source/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/gmake" "cmTC_6f85a/fast"
/usr/bin/gmake -f CMakeFiles/cmTC_6f85a.dir/build.make CMakeFiles/cmTC_6f85a.dir/build
gmake[1]: Entering directory `/root/Downloads/trilinos-12.12.1-Source/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_6f85a.dir/CheckFunctionExists.c.o
/opt/mpich/bin/mpicc   -DCHECK_FUNCTION_EXISTS=DGGSVD3_ -O3 -DNDEBUG   -o CMakeFiles/cmTC_6f85a.dir/CheckFunctionExists.c.o   -c /usr/local/share/cmake-3.10/Modules/CheckFunctionExists.c
Linking C executable cmTC_6f85a
/usr/local/bin/cmake -E cmake_link_script CMakeFiles/cmTC_6f85a.dir/link.txt --verbose=1
/opt/mpich/bin/mpicc  -DCHECK_FUNCTION_EXISTS=DGGSVD3_ -O3 -DNDEBUG    -rdynamic CMakeFiles/cmTC_6f85a.dir/CheckFunctionExists.c.o  -o cmTC_6f85a  -L/opt/lib/BLAS -Wl,-rpath,/opt/lib/LAPACK:/opt/lib/BLAS /opt/lib/LAPACK/liblapack.so -lblas
CMakeFiles/cmTC_6f85a.dir/CheckFunctionExists.c.o: In function `main':
CheckFunctionExists.c:(.text.startup+0xc): undefined reference to `DGGSVD3_'
collect2: error: ld returned 1 exit status
gmake[1]: *** [cmTC_6f85a] Error 1
gmake[1]: Leaving directory `/root/Downloads/trilinos-12.12.1-Source/build/CMakeFiles/CMakeTmp'
gmake: *** [cmTC_6f85a/fast] Error 2

#----- and this is when the"make -j2" kicked out -----#
.......
[ 99%] Linking CXX executable Stokhos_KokkosCrsMatrixMPVectorUnitTest_Serial.exe
[ 99%] Built target Stokhos_KokkosCrsMatrixMPVectorUnitTest_Serial
Scanning dependencies of target Stokhos_KokkosViewMPVectorUnitTest_Serial
[ 99%] Building CXX object packages/stokhos/test/UnitTest/CMakeFiles/Stokhos_KokkosViewMPVectorUnitTest_Serial.dir/Stokhos_KokkosViewMPVectorUnitTest_Serial.cpp.o                                                                                                                                              
In file included from /root/Downloads/trilinos-12.12.1-Source/packages/muelu/adapters/tpetra/MueLu_CreateTpetraPreconditioner.hpp:10:0,
                 from /root/Downloads/trilinos-12.12.1-Source/packages/stokhos/test/UnitTest/Stokhos_TpetraCrsMatrixMPVectorUnitTest.hpp:77,
                 from /root/Downloads/trilinos-12.12.1-Source/packages/stokhos/test/UnitTest/Stokhos_TpetraCrsMatrixMPVectorUnitTest_Serial.cpp:46:
/root/Downloads/trilinos-12.12.1-Source/packages/xpetra/src/CrsMatrix/Xpetra_TpetraBlockCrsMatrix.hpp: In instantiation of ‘void Xpetra::TpetraBlockCrsMatrix<Scalar, LocalOrdinal, GlobalOrdinal, Node>::getLocalDiagOffsets(Teuchos::ArrayRCP<long unsigned int>&) const [with Scalar = Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::Serial> >; LocalOrdinal = int; GlobalOrdinal = int; Node = Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial>]’:
/root/Downloads/trilinos-12.12.1-Source/packages/stokhos/test/UnitTest/Stokhos_TpetraCrsMatrixMPVectorUnitTest_Serial.cpp:71:1:   required from here
/root/Downloads/trilinos-12.12.1-Source/packages/xpetra/src/CrsMatrix/Xpetra_TpetraBlockCrsMatrix.hpp:343:7: warning: ‘void Tpetra::Experimental::BlockCrsMatrix<S, LO, GO, N>::getLocalDiagOffsets(Teuchos::ArrayRCP<long unsigned int>&) const [with Scalar = Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::Serial> >; LO = int; GO = int; Node = Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial>]’ is deprecated (declared at /root/Downloads/trilinos-12.12.1-Source/packages/tpetra/core/src/Tpetra_Experimental_BlockCrsMatrix_def.hpp:1062) [-Wdeprecated-declarations]
       mtx_->getLocalDiagOffsets(offsets);
       ^
[ 99%] Linking CXX executable Stokhos_KokkosViewMPVectorUnitTest_Serial.exe
[ 99%] Built target Stokhos_KokkosViewMPVectorUnitTest_Serial
Scanning dependencies of target Stokhos_SacadoMPVectorCommTests
[ 99%] Building CXX object packages/stokhos/test/UnitTest/CMakeFiles/Stokhos_SacadoMPVectorCommTests.dir/Stokhos_SacadoMPVectorCommTests.cpp.o
[ 99%] Linking CXX executable Stokhos_SacadoMPVectorCommTests.exe
[ 99%] Built target Stokhos_SacadoMPVectorCommTests
Scanning dependencies of target Stokhos_SDMUtilsUnitTest
[ 99%] Building CXX object packages/stokhos/test/UnitTest/CMakeFiles/Stokhos_SDMUtilsUnitTest.dir/Stokhos_SDMUtilsUnitTest.cpp.o
[ 99%] Linking CXX executable Stokhos_SDMUtilsUnitTest.exe
CMakeFiles/Stokhos_SDMUtilsUnitTest.dir/Stokhos_SDMUtilsUnitTest.cpp.o: In function `void Stokhos::CPQR_Householder<int, double>(Teuchos::SerialDenseMatrix<int, double> const&, Teuchos::SerialDenseMatrix<int, double>&, Teuchos::SerialDenseMatrix<int, double>&, Teuchos::Array<int>&)':
Stokhos_SDMUtilsUnitTest.cpp:(.text._ZN7Stokhos16CPQR_HouseholderIidEEvRKN7Teuchos17SerialDenseMatrixIT_T0_EERS5_S8_RNS1_5ArrayIS3_EE[_ZN7Stokhos16CPQR_HouseholderIidEEvRKN7Teuchos17SerialDenseMatrixIT_T0_EERS5_S8_RNS1_5ArrayIS3_EE]+0x16c): undefined reference to `dgeqpf_'
collect2: error: ld returned 1 exit status
make[2]: *** [packages/stokhos/test/UnitTest/Stokhos_SDMUtilsUnitTest.exe] Error 1
make[1]: *** [packages/stokhos/test/UnitTest/CMakeFiles/Stokhos_SDMUtilsUnitTest.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
In file included from /root/Downloads/trilinos-12.12.1-Source/build/packages/muelu/src/MueLu_VariableDofLaplacianFactory.hpp:2:0,
                 from /root/Downloads/trilinos-12.12.1-Source/packages/muelu/src/Interface/MueLu_FactoryFactory_decl.hpp:146,
                 from /root/Downloads/trilinos-12.12.1-Source/build/packages/muelu/src/Interface/MueLu_FactoryFactory.hpp:1,
                 from /root/Downloads/trilinos-12.12.1-Source/packages/muelu/src/Interface/MueLu_ParameterListInterpreter_def.hpp:73,
                 from /root/Downloads/trilinos-12.12.1-Source/build/packages/muelu/src/Interface/MueLu_ParameterListInterpreter.hpp:2,
                 from /root/Downloads/trilinos-12.12.1-Source/packages/muelu/adapters/tpetra/MueLu_CreateTpetraPreconditioner.hpp:22,
                 from /root/Downloads/trilinos-12.12.1-Source/packages/stokhos/test/UnitTest/Stokhos_TpetraCrsMatrixMPVectorUnitTest.hpp:77,
                 from /root/Downloads/trilinos-12.12.1-Source/packages/stokhos/test/UnitTest/Stokhos_TpetraCrsMatrixMPVectorUnitTest_Serial.cpp:46:
/root/Downloads/trilinos-12.12.1-Source/packages/muelu/src/Interface/../Graph/MueLu_VariableDofLaplacianFactory_def.hpp: In member function ‘void MueLu::VariableDofLaplacianFactory<Scalar, LocalOrdinal, GlobalOrdinal, Node>::Build(MueLu::VariableDofLaplacianFactory<Scalar, LocalOrdinal, GlobalOrdinal, Node>::Level&) const [with Scalar = Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::Serial> >; LocalOrdinal = int; GlobalOrdinal = int; Node = Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial>; MueLu::VariableDofLaplacianFactory<Scalar, LocalOrdinal, GlobalOrdinal, Node>::Level = MueLu::Level]’:
/root/Downloads/trilinos-12.12.1-Source/packages/muelu/src/Interface/../Graph/MueLu_VariableDofLaplacianFactory_def.hpp:256:16: warning: ‘blockRow’ may be used uninitialized in this function [-Wmaybe-uninitialized]
     amalgRowPtr[blockRow+1] = newNzs;
                ^
[ 99%] Linking CXX executable Stokhos_TpetraCrsMatrixMPVectorUnitTest_Serial.exe
[ 99%] Built target Stokhos_TpetraCrsMatrixMPVectorUnitTest_Serial
make: *** [all] Error 2
You have mail in /var/spool/mail/root

**Comment by etphipp** [comment]
Does your LAPACK library not have dgeqpf?

**Comment by lkkevin** [comment]
@egboman - Hi Erick, i dont know.  I am using the latest LAPACK version.  How can i find down if LAPACK has dgeqpf?  Thanks.

#---- I followed the below instruction to build BLAS and LAPACK ----#
2. MPI Compilers
MPI, message passing interface, whose common distribution in PCs is called MPICH. If your
operation system doesn’t have it, go through the following installation procedures.
(1) Download the release distribution from http://www.mpich.org/downloads/, and unpack it to your
source directory, say /home/you/sources/mpich.
(2) Choose an installation directory, for example: mkdir /home/you/mpich
(3) Choose a build directory, for example: mkdir /home/you/sources/mpich/build
(4) Configure MPICH
Specify the installation directory, and running the configure script in the source directory:
cd /home/you/sources/mpich/build
../configure \
--prefix=/home/you/mpich 2>&1 | tee c.txt (for bash and sh)
--prefix=/home/you/mpich |& tee c.txt (for csh and tcsh)
the \ means that this is in fact one line. The file config.log is created by configure and contains a
record of the tests that configure performed. Note that it is normal for some tests recorded in
config.log to fail. Go ahead if your terminal shows configuration completed.
(5) Build MPICH
make 2>&1 | tee m.txt (for bash and sh)
make |& tee m.txt (for csh and tcsh)
The building process is recorded in m.txt.
(6) Install MPICH
make install |& tee mi.txt
This should succeed. You can also type make installcheck to make sure the installation is done (It's
optional and typically unnecessary).
(7)Add the bin and lib subdirectory of the installation directory to your path
export PATH=/home/you/mpich/bin:$PATH
export LIBPATH=/home/you/mpich/lib:$LIBPATH
for bash, or
PATH=/home/you/mpich/bin:$PATH
export PATH
LIBPATH=/home/you/mpich/lib:$LIBPATH
export LIBPATH
for sh, or
setenv PATH /home/you/mpich/bin:$PATH
setenv LIBPATH /home/you/mpich/lib:$LIBPATH
for csh and tcsh
(8)Final check
which mpicc
which mpiexec
All should refer to the bin subdirectory of your installation directory and MPICH is built
successfully.
3. BLAS and LAPACK
Building BLAS and LAPACK for ASPECT is a bit tricky. Because ASPECT defaults to a
dynamically linked executable, the BLAS and LAPACK for it must be compiled into shared
libraries, with libblas.so and liblapack.so object files, rather than the common static libblas.a and
liblapack.a. Note that this is very important: If you build dynamic Trilinos in Section 5 with static
libblas.a and liblapack.a, it will fail with the bad value error.
(1)BLAS
(a)Download blas.tgz from http://www.netlib.org/blas/ and unpack it to your library directory, say
/home/you/lib/BLAS.
(b)Build libblas.so
cd /home/you/lib/BLAS
gfortran -shared -O2 *.f -o libblas.so -fPIC
You will have libblas.so compiled in your BLAS directory. Optionally, you can add the BLAS
library directory to your path.
For example, for bash, add it in .bashrc:
export LIBPATH=/home/you/mpich/lib:/home/you/lib/BLAS/libblas.so:$LIBPATH
and run source .bashrc in the terminal.
(2)LAPACK
(a)Download lapack-3.x.y.tgz from http://www.netlib.org/lapack/ and unpack it to /home/you/lib/
LAPACK.
(b)Build liblapack.so
(i)Get the copy of make.inc
cd /home/you/lib/LAPACK
cp make.inc.example make.inc
(ii)Add -fPIC to OPTS & NOOPT in make.inc
(iii)Change the lib names in make.inc to .so
BLASLIB = ../../librefblas.so
LAPACKLIB = liblapack.so
(iv)In ./SRC, change the following lines of Makefile from
../$(LAPACKLIB): $(ALLOBJ) $(ALLXOBJ)
$(ARCH) $(ARCHFLAGS) $@ $(ALLOBJ) $(ALLXOBJ)
$(RANLIB) $@
to
../$(LAPACKLIB): $(ALLOBJ)
$(LOADER) $(LOADOPTS) -shared -Wl,-soname,liblapack.so -o $@ $(ALLOBJ) ../lib
refblas.so
Note that at front of the second line is a tab space, and the last item is librefblas.so.
(v)In ./BLAS/SRC, change the Makefile from
$(BLASLIB): $(ALLOBJ)
$(ARCH) $(ARCHFLAGS) $@ $(ALLOBJ)
$(RANLIB) $@
to
$(BLASLIB): $(ALLOBJ)
$(LOADER) $(LOADOPTS) -z muldefs -shared -Wl,-soname,librefblas.so -o $@ $(AL
LOBJ)
Note that at front of the second line is a tab space, and the last item is $(ALLOBJ).
(vi)Back to LAPACK directory
make blaslib
make lapacklib
You will have librefblas.so and then liblapack.so compliled in your LAPACK directory.
(vii)Optionally, you can also add the LAPACK library directory to your path.
For example, for bash, add it in .bashrc:
export LIBPATH=/home/you/mpich/lib:/home/you/lib/BLAS/libblas.so:/home/you/lib/
LAPACK/liblapack.so:$LIBPATH
and run source .bashrc in the terminal.

**Comment by etphipp** [comment]
You can try "nm", but that won't work if your lapack library has the symbols stripped out.  It looks like that function has been deprecated

http://www.netlib.org/lapack/lapack-3.1.1/html/dgeqpf.f.html

so I should probably just remove it.

**Comment by etphipp** [comment]
For the time being, you can just disable Stokhos, since Peridigm doesn't use it.

**Comment by lkkevin** [comment]
@etphipp - I'll try as you suggested and report back.  Thank you very much.

**Comment by mhoemmen** [comment]
@etphipp I filed https://github.com/trilinos/Trilinos/issues/2007 for removing use of the deprecated LAPACK function; thanks!

**Comment by etphipp** [comment]
I removed dgeqpf in Stokhos in the development branch.

**Comment by mhoemmen** [comment]
Thanks @etphipp !
