### ISSUE TITLE
Framework: Windows did not post to cdash again

### ISSUE THREAD

**Issue by csiefer2** [trilinos/Trilinos#2006]
Again.

**Comment by bmpersc** [comment]
@csiefer2, It looks like the VM was stopped and for some reason this time the startup script immediately quit. What is odd is that the VM had been stopped and brought up several times in the weeks leading up to this and it successfully started the jenkins agent so I'm not sure what happened. Manually starting the jenkins agent has brought the slave back up and the job is currently running so there should be windows results available later today. 

Please keep letting us know when this happens.
