### ISSUE TITLE
Stokhos,Teuchos: Remove use of deprecated LAPACK function dgeqpf

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#2007]
LAPACK function `dgeqpf` (presumably also xgeqpf for other x) was deprecated in LAPACK 3.1.1.  This means we shouldn't use it any more, or at least should make its use optional.

@trilinos/stokhos @trilinos/teuchos

**Comment by lkkevin** [comment]
@mhoemmen - great, thanks again Eric and Mark.

**Comment by etphipp** [comment]
I removed dgeqpf from Stokhos.
