### ISSUE TITLE
Sacado: Derivative of std::pow produces floating point exception

### ISSUE THREAD

**Issue by xamhn** [trilinos/Trilinos#2008]
@trilinos/sacado

## Expectations

For power-functions with variable exponent and variable base the partial derivative wrt to the base should also work for negative values of the evaluation point, i.e. e.g. df/dx | x=-1 should work. 

## Current Behavior

Given a function f = x^y. Then df/dx for x <= 0 produces a floating point exception. This is possibly because for a derivative df/d**y** the function is rewritten as f = exp(y*ln x) whose derivative df/d**x** obviously produces a floating point exception for x <= 0.

## Steps to Reproduce

Snippet 1 (with error):
```
  int num_deriv = 2;
  double base_d = -1.0;
  double expo_d = 2.0;
  Sacado::Fad::DFad<double> base(num_deriv,0,base_d);
  Sacado::Fad::DFad<double> expo(num_deriv,1,expo_d);
  Sacado::Fad::DFad<double> result;

  result = std::pow(base,expo);

  double val = result.val();
  std::cout << "value: " << val << std::endl;

  double deriv = result.dx(0);
  std::cout << "derivative: " << deriv << std::endl;
```
Produces:
```
[ 0]: sigfpe_handler(int)  (baci.cpp:50 (discriminator 6))
[ 1]: 
[ 2]: log
[ 3]: Sacado::Fad::Expr<Sacado::Fad::PowerOp<Sacado::Fad::Expr<Sacado::Fad::GeneralFad<double, Sacado::Fad::DynamicStorage<double, double> >, Sacado::Fad::ExprSpecDefault>, Sacado::Fad::Expr<Sacado::Fad::GeneralFad<double, Sacado::Fad::DynamicStorage<double, double> >, Sacado::Fad::ExprSpecDefault> >, Sacado::Fad::ExprSpecDefault>::fastAccessDx(int) const  (Sacado_Fad_Ops.hpp:643)
[ 4]: Sacado::mpl::enable_if_c<Sacado::mpl::is_convertible<Sacado::Fad::Expr<Sacado::Fad::PowerOp<Sacado::Fad::Expr<Sacado::Fad::GeneralFad<double, Sacado::Fad::DynamicStorage<double, double> >, Sacado::Fad::ExprSpecDefault>, Sacado::Fad::Expr<Sacado::Fad::GeneralFad<double, Sacado::Fad::DynamicStorage<double, double> >, Sacado::Fad::ExprSpecDefault> >, Sacado::Fad::ExprSpec<Sacado::Fad::PowerOp<Sacado::Fad::Expr<Sacado::Fad::GeneralFad<double, Sacado::Fad::DynamicStorage<double, double> >, Sacado::Fad::ExprSpecDefault>, Sacado::Fad::Expr<Sacado::Fad::GeneralFad<double, Sacado::Fad::DynamicStorage<double, double> >, Sacado::Fad::ExprSpecDefault> > >::type>::value_type, double>::value&&(Sacado::Fad::ExprLevel<Sacado::Fad::Expr<Sacado::Fad::PowerOp<Sacado::Fad::Expr<Sacado::Fad::GeneralFad<double, Sacado::Fad::DynamicStorage<double, double> >, Sacado::Fad::ExprSpecDefault>, Sacado::Fad::Expr<Sacado::Fad::GeneralFad<double, Sacado::Fad::DynamicStorage<double, double> >, Sacado::Fad::ExprSpecDefault> >, Sacado::Fad::ExprSpec<Sacado::Fad::PowerOp<Sacado::Fad::Expr<Sacado::Fad::GeneralFad<double, Sacado::Fad::DynamicStorage<double, double> >, Sacado::Fad::ExprSpecDefault>, Sacado::Fad::Expr<Sacado::Fad::GeneralFad<double, Sacado::Fad::DynamicStorage<double, double> >, Sacado::Fad::ExprSpecDefault> > >::type>::value_type>::value==Sacado::Fad::ExprLevel<double>::value), Sacado::Fad::GeneralFad<double, Sacado::Fad::DynamicStorage<double, double> >&>::type Sacado::Fad::GeneralFad<double, Sacado::Fad::DynamicStorage<double, double> >::operator=<Sacado::Fad::PowerOp<Sacado::Fad::Expr<Sacado::Fad::GeneralFad<double, Sacado::Fad::DynamicStorage<double, double> >, Sacado::Fad::ExprSpecDefault>, Sacado::Fad::Expr<Sacado::Fad::GeneralFad<double, Sacado::Fad::DynamicStorage<double, double> >, Sacado::Fad::ExprSpecDefault> > >(Sacado::Fad::Expr<Sacado::Fad::PowerOp<Sacado::Fad::Expr<Sacado::Fad::GeneralFad<double, Sacado::Fad::DynamicStorage<double, double> >, Sacado::Fad::ExprSpecDefault>, Sacado::Fad::Expr<Sacado::Fad::GeneralFad<double, Sacado::Fad::DynamicStorage<double, double> >, Sacado::Fad::ExprSpecDefault> >, Sacado::Fad::ExprSpec<Sacado::Fad::PowerOp<Sacado::Fad::Expr<Sacado::Fad::GeneralFad<double, Sacado::Fad::DynamicStorage<double, double> >, Sacado::Fad::ExprSpecDefault>, Sacado::Fad::Expr<Sacado::Fad::GeneralFad<double, Sacado::Fad::DynamicStorage<double, double> >, Sacado::Fad::ExprSpecDefault> > >::type> const&)  (Sacado_Fad_GeneralFad.hpp:266 (discriminator 2))

```

Snippet 2 (no error because exponent not variable):
```
  int num_deriv = 2;
  double base_d = -1.0;
  double expo_d = 2.0;
  Sacado::Fad::DFad<double> base(num_deriv,0,base_d);
  Sacado::Fad::DFad<double> result;

  result = std::pow(base,expo_d);

  double val = result.val();
  std::cout << "value: " << val << std::endl;

  double deriv = result.dx(0);
  std::cout << "deriv: " << deriv << std::endl;
```

Produces:
```
value: 1
derivative: -2 
```

## Your Environment

- **Trilinos version:**  Release 12.12.1
- **Relevant configure flags or configure script:**     

```
    -D CMAKE_BUILD_TYPE:STRING="RELEASE" \
    -D CMAKE_CXX_COMPILER:FILEPATH="$MPIDIR/bin/mpic++" \
    -D CMAKE_C_COMPILER:FILEPATH="$MPIDIR/bin/mpicc" \
    -D CMAKE_Fortran_COMPILER:FILEPATH="$MPIDIR/bin/mpif90" \
    -D CMAKE_INSTALL_PREFIX:STRING="$TRILINOSDIR" \
    -D CMAKE_CXX_FLAGS:STRING="-Wall -O3 -ftemplate-depth=80 -std=c++11" \
    -D CMAKE_C_FLAGS:STRING="-Wall -O3 -Wconversion" \
```

- **Operating system and version:**  Fedora release 22
- **Compiler and TPL versions:**  gcc version 5.3.1 20160406 (Red Hat 5.3.1-6) (GCC)

**Comment by etphipp** [comment]
std::pow(x,y) is only defined for x < 0 with integral y:

http://en.cppreference.com/w/cpp/numeric/math/pow

presumably because x^y is only defined (as a real number) for integral and some rational y if x < 0.  Thus it appears to me that x^y is not differentiable with respect to y if x < 0.  How would you propose to compute the derivative with respect to y if x < 0?

**Comment by mwgee** [comment]
Its the derivative with respect to x that fails when y is a Saccado type, please see Snippet 1.  Also, this used to work previously (that is, older Trilinos releases and/or before introducing the c++11 flag).

**Comment by etphipp** [comment]
The problem though is that if z = x^y and is a Fad, derivatives with respect to y must be included in the computation of z, unless the derivative components of y are all zero.  So as far as I can tell, the only reasonable way I could implement z = x^y with x < 0 is to loop through all of the derivative components of y and check they are zero.  That will be expensive though, so I am not entirely convince I want to do that.

If you don't want derivatives with respect to y, do you have to make y a Fad?  Or if you must, but know that you don't want derivatives w.r.t. y included, could you do something like this:
```
Fad x = ...
Fad y = ...
Fad z = pow(x, y.val());
```

Do you have some rough idea of when this worked before?  As far as I can recall, Sacado has always used the formula z = exp(y*log(x)) when y is a Fad so I don't see how it could have ever worked for x < 0.

**Comment by xamhn** [comment]
Thank you for your ideas on the topic. I think we'll do something like this when we need all the derivatives wrt to x:
`Fad z = pow(x, y.val());`

**Comment by bartgol** [comment]
@etphipp pinging on this issue. We are experiencing this problem in Albany as well, where we have something like
```
Fad x = 0.0;
double a = 2.0;
Fad f = pow(x,a).
```

The FPE is thrown with a Fad that has val=0, and dx(i)=0 for all i. Now, the `if_then_else` logic should simply return 0. However, it still throws, and I _think_ it is because the constructor of f from the expression on the rhs calls `dx(i)` on the rhs, whose implementation (via the FAD_BINARYOP_MACRO) is simply a call to the `if_then_else` function. But the inputs to the `if_then_else` still need (I think) to be evaluated by the compiler. That's where the FPE gets thrown, even if the result of the third input of the `if_then_else` would get thrown away.

Have you ever noticed issues doing `pow(Fad(0.0),2.0)`? Obviously, that's not a very interesting operation, but for some inputs we happen to get it.

**Comment by etphipp** [comment]
The problem here is `if_then_else(cond,a,b)`.  Being a function, `a` and `b` are always evaluated, regardless of what the value of `cond` is.  So in this case, the else condition is evaluated and generates an FPE, even though it isn't used.

Originally, Sacado just used the ternary operator `cond ? a : b`, in which case I believe b would not be evaluated if `cond == false`.  This was changed for Sierra, which uses stk::simd with Sacado, and so they wanted `if_then_else` for their simd evaluations.

How important is this?  A way to fix it would be to only use `if_then_else` if scalar type inside Fad is something like simd.

**Comment by bartgol** [comment]
Sorry, I forgot to answer. I'm not sure how important it is. I mean, if you disable FPEs, the code works fine. The FPE is in a branch that does not get executed (though, as you said, it _does_ need to be evaluated, which is what generates the issue).

I do not fully understand all the logic in Sacado, but isn't it possible to avoid the `if_then_else` construct for the case where neither of the two input expressions is an expression (i.e., they are both value types)? For that case, we could simply use the `cond ? a : b` operator inside the FAD_BINARYOP_MACRO, no?

**Comment by etphipp** [comment]
I added a PR that should address the FPE issue with pow():

https://github.com/trilinos/Trilinos/pull/4380
