### ISSUE TITLE
Zoltan2 call with zero global elements

### ISSUE THREAD

**Issue by kuberry** [trilinos/Trilinos#2010]
If all processors in the communicator have zero elements, then the wrong number of global parts is calculated in PartitioningSolution.
Around line 1267 of PartitioningSolution the number of parts is calculated as below. When global element count is 0, number of parts is calculated as INT_MAX. Something like the commented code is needed to fix this issue.
```c++
  for (size_t i = 0; i < len; i++) {
    if (partList[i] < lMin) lMin = partList[i];
    if (partList[i] > lMax) lMax = partList[i];
  }
  //if (len == 0){
  //  lMax = 0; lMin = 0;
  //}
  Teuchos::reduceAll<int, part_t>(*comm_, Teuchos::REDUCE_MIN, 1, &lMin, &gMin);
  Teuchos::reduceAll<int, part_t>(*comm_, Teuchos::REDUCE_MAX, 1, &lMax, &gMax);
```
@mndevec @kddevin @egboman @srajama1

**Comment by mhoemmen** [comment]
@trilinos/zoltan2
