### ISSUE TITLE
STKUnit_tests_util_parallel_UnitTest_MPI_4 failing almost everywhere (including ATTB machine)

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#202]
The test STKUnit_tests_util_parallel_UnitTest_MPI_4 is failing on all but one build on one automated test platform as shown in [this CDash query](http://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&date=&limit=200&filtercount=3&showfilters=1&limit=200&filtercombine=and&field1=testname/string&compare1=65&value1=STKUnit_tests_util_parallel_UnitTest&field2=buildstarttime/date&compare2=83&value2=2016-03-08&field3=buildstarttime/date&compare3=84&value3=2016-03-11).  I am also here to report that it also fails on the Advanced Technology Test Best machine hansen (which is an important platform for obvious reasons).

In fact, this test has been failing for as far back as we have data (currently 2016-02-05) as shown in [this query](http://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&date=&limit=200&filtercount=3&showfilters=1&limit=200&filtercombine=and&field1=testname/string&compare1=65&value1=STKUnit_tests_util_parallel_UnitTest&field2=buildstarttime/date&compare2=83&value2=2016-01-01&field3=buildstarttime/date&compare3=84&value3=2016-03-11).

Who is responsible for STK under Trilinos?

CC: @trilinos/framework

**Comment by alanw0** [comment]
STKUnit_tests_util is building and working these days. I don't know why I never saw this github issue, but the code appears to be resolved.
