### ISSUE TITLE
ShyLU_Node: tacho_ExamplePerfTest.cpp failing build in nightly Clean track

### ISSUE THREAD

**Issue by william76** [trilinos/Trilinos#2021]
Getting a failure for the past 6 days in packages/shylu/shylu_node/tacho/example/Tacho_ExamplePerfTest.cpp

Details
-------
https://testing.sandia.gov/cdash/viewBuildError.php?buildid=3241460

(Possible) Relevant Commits
-----------------------------
2a6ee2c5a0049e1da5ee4bc121ff6ce8f62c8b5e
b61cd068125e7d00a6ee2b262df052e55323694b

@trilinos/shylu 

@kyungjoo-kim

**Comment by kyungjoo-kim** [comment]
Sorry. I forgot that metis is not installed in test machines yet.

**Comment by william76** [comment]
ok.  Have you checked in a fix and/or backed out the commits that broke the Clean builds?

**Comment by kyungjoo-kim** [comment]
I forgot to reference in the commit.

``9076e32``

**Comment by william76** [comment]
Builds were clean last night so I'll close this issue out.
