### ISSUE TITLE
Missing include in Intrepid2_CellTools_Serial.hpp

### ISSUE THREAD

**Issue by Rombur** [trilinos/Trilinos#2023]
I am using several functions of  `CellTools::Serial` in my Kokkos kernels. However, my code does not compile if I don't include `#include <Shards_CellTopologyManagedData.hpp>` **before**  `Intrepid2_CellTools_Serial.hpp`. `Shards` objects are used in multiple functions implemented in this file but there isn't any include of shards headers. I am not sure which header should be included in this file but `Shards_CellTopologyManagedData.hpp` works for me.

**Comment by lucbv** [comment]
@trilinos/intrepid2

**Comment by mperego** [comment]
@Rombur @lucbv I included `Shards_CellTopology.hpp` to the `Intrepid2_CellTools_Serial.hpp`  file. This should fix the issue. Let me know if this is not the case. Thanks!
