### ISSUE TITLE
MueLu: refactor verbosity levels

### ISSUE THREAD

**Issue by jhux2** [trilinos/Trilinos#2030]
This issue is to suggest changes related to what information that MueLu emits at different verbosity levels.  Here's a possible set of categories:

- NONE
This is the default “production user” mode
No output besides errors
- LOW 
Multigrid Summary
Input Parameters
Warnings (that don’t require communication?)
- MEDIUM 
All of the factory names
Any factory information which we have already calculated for setup (e.g. # rows in Ac, SA eigenvalue estimate) and that doesn’t require additional communication
“No keep flag” warnings (no comm required for these, but we don’t want to see them at LOW).
- HIGH
In my mind this is the most similar to “ML output” 10.
Any “key” factory-specific information which requires additional communication to send (e.g. aggregate statistics)
- EXTREME
Matrix comm stats / balancing stats

@trilinos/muelu

**Comment by jhux2** [comment]
See issue #1997 for one change that @csiefer2 already made.

**Comment by aprokop** [comment]
- Any "print:" input deck variable should go to LOW. A user has explicitly requested to print messages, we should follow his wishes. At the minimum, this means "print initial parameters" and "print unused parameters". The "repartition: print partition distribution" is debatable.
- Should hierarchy setup time (just one timer) go to LOW?
- I would merge your HIGH and EXTREME, and keep EXTREME to its original meaning which was HIGH + output from TPLs/other packages that we use.

**Comment by jhux2** [comment]
> I would merge your HIGH and EXTREME, and keep EXTREME to its original meaning which was HIGH + output from TPLs/other packages that we use.

@aprokop The main sticking point is that without adding a new category, this suggestion does not give a way to separate the "heavy" matrix statistics communication from other communication.

**Comment by aprokop** [comment]
But you did mention "Any “key” factory-specific information which requires additional communication to send (e.g. aggregate statistics)" in high? And matrix statistics communication is no heavier than that?

**Comment by jhux2** [comment]
> But you did mention "Any “key” factory-specific information which requires additional communication to send (e.g. aggregate statistics)" in high? And matrix statistics communication is no heavier than that?

@aprokop I would argue yes.  There are matrix statistics for A, Ptent, P, and possibly R, versus a single aggregation structure.

**Comment by aprokop** [comment]
If you don't have the exact definitions for levels, I think this effort would be no better in the long term than what we currently have. To improve status quo (beyond immediate moving of some output to higher levels), it would require coming up with precise definitions so that it is no brainer where to put code in.

**Comment by jhux2** [comment]
Closing as wontfix, others are welcome to reopen if they want to tackle.
