### ISSUE TITLE
Change trilinos-autotester avatar

### ISSUE THREAD

**Issue by aprokop** [trilinos/Trilinos#2037]
@trilinos/framework 

## Expectations

It should be immediately clear (from Github Notifications board) that the comment was made by the auto-tester. This would speed up going through issues.

## Current Behavior

Going to the issue and expecting some comment from a developer and instead getting comments from testing framework I may not want to look at.

## Definition of Done

The avatar for auto-tester makes it immediately clear that it is done by a Trilinos bot.

## Possible Solution

[Here](http://www.mediacurrent.com/sites/default/files/styles/article_full_width_600_/public/fix_testbot.png?itok=5Rf7leiB)

## Your Environment

- **Relevant repo SHA1s:**  
- **Relevant configure flags or configure script:**  
- **Operating system and version:**  
- **Compiler and TPL versions:**  

## Related Issues

* Blocks 
* Is blocked by 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of

**Comment by william76** [comment]
I like this idea.  I did something similar for the BSSw autotester.

I like the robot icon, we could also use one of the square trilinos logos: https://github.com/trilinos/Logos such as:
- https://github.com/trilinos/Logos/blob/master/Trilinos_logo_square.jpg ... that whitespace border would need trimming though.

I think @jwillenbring would be the one to make the change though.

**Comment by jwillenbring** [comment]
I added the square logo as the avatar for the trilinos-autotester entity account. I am closing this ticket.
