### ISSUE TITLE
Belos: Accept "Num Blocks" as a default parameter in PesudoBlockCG and PseudoBlockTFQMR SolMgrs

### ISSUE THREAD

**Issue by sayerhs** [trilinos/Trilinos#2040]
Currently, both these classes throw an error in `setParameters` method because "Num Blocks" is not a valid parameter. However, this is useful for GMRES solvers. 

## Expectations

Belos SolverManager should not error if `Num Blocks` is present in the ParameterList. 

## Current Behavior

```
terminate called after throwing an instance of 'Teuchos::Exceptions::InvalidParameterName'
  what():  Error, the parameter {name="Num Blocks",type="int",value="50"}
in the parameter (sub)list "ANONYMOUS"
was not found in the list of valid parameters!

The valid parameters and types are:
  {
    "Convergence Tolerance" : double = 1e-08
    "Implicit Tolerance Scale Factor" : double = 10
    "Maximum Iterations" : int = 1000
    "Verbosity" : int = 0
    "Output Style" : int = 0
    "Output Frequency" : int = -1
    "Output Stream" : Teuchos::RCP<std::ostream> = Teuchos::RCP<std::ostream>{ptr=0x3a7b780,node=0x4030df0,strong_count=2,weak_count=0}
    "Explicit Residual Test" : bool = 0
    "Implicit Residual Scaling" : string = Norm of Preconditioned Initial Residual
    "Explicit Residual Scaling" : string = Norm of Initial Residual
    "Timer Label" : string = Belos
  }
```

## Motivation and Context

Reusing a `Teuchos::ParameterList` currently causes errors even though some other part of Belos/GMRES is adding "Num Blocks" parameter to the ParameterList. 

## Possible fix

As with MINRES (from `belos/ReleaseNotes.txt`) 

```
* MINRES: "Num Blocks" parameter now allowed for compatibility with
  other Belos solvers (10 Apr 2014)

Many Belos solvers based on GMRES have a "Num Blocks" parameter.  This
gives the restart length.  (The name refers to the amount of vector
storage, as a multiple of the solver's block size, but it really means
"restart length.")  Thus, a reasonable default ParameterList for Belos
may have the "Num Blocks" parameter in it.  However, MINRES did not
accept this parameter, and threw an exception if given it.  This makes
sense, because its MINRES does not restart.  However, it causes
trouble for users who might want to reuse a ParameterList for
different Belos solvers.  We changed MINRES so that it accepts, but
ignores, the "Num Blocks" parameter.
```

**Comment by aprokop** [comment]
@trilinos/belos

**Comment by mhoemmen** [comment]
This is a design question.  Some people would argue that solvers should reject parameters that they don't understand, in order to detect spelling mistakes, etc.  @hkthorn , what do you think?

**Comment by sayerhs** [comment]
@mhoemmen Thanks for raising the _design_ aspect. I fully agree that the solvers should reject parameters they don't understand or support. 

In the example reported above, the "Num Blocks" parameter was not added by the user (Nalu is the specific application here). It was added by GMRES in the first call during SolverManager construction. So reusing a `Teuchos::RCP<Techos::ParameterList>` stored in user code again with `setParameters` is causing an error. I feel that the solvers should not be adding additional entries to user-owned `ParameterList`. This is unfortunate considering that the method signature is:

```
    //! Set the parameters the solver manager should use to solve the linear problem.
    void setParameters( const Teuchos::RCP<Teuchos::ParameterList> &params );
```

but the `const` doesn't really seem apply to `Techos::ParameterList`. A cleaner solution would be for Belos solvers to make a local copy of the parameterList before injecting their own defaults into this.

**Comment by mhoemmen** [comment]
@sayerhs wrote:
> but the const doesn't really seem apply to Techos::ParameterList

`RCP<T>` means "pointer to nonconst T."  `RCP<const T>` means "pointer to const T."  Thus, `RCP<ParameterList>` means that the function reserves the right to modify the input ParameterList.  Whether or not that is a good idea, it is a decision made years before I started working on Trilinos.

This is tangential to your original issue.  Could you please specify here exactly which solvers you attempt to call?  It sounds like you are trying to call one solver that does accept "Num Blocks", and then another solver which does not accept "Num Blocks".  Is that correct?

**Comment by hkthorn** [comment]
@sayerhs @mhoemmen 

I'm confused by the statement:  
_It was added by GMRES in the first call during SolverManager construction._

When used directly, neither Belos::BlockGmres not Belos::PseudoBlockGmres add any parameters to the parameter list passed in during the solver manager constructor.  While Mark is correct, there is no explicit contract between the user and the solver that this parameter list is not modified, neither of these solvers change the passed in solver.  Rather, they have an internal parameter list that keeps track of the current parameters that the solver is using.  They can be accessed through the solver manager by calling getCurrentParameters().  For example, I modified an Epetra GMRES solver test (BlockGmresEpetraGaleriEx.cpp) to print out the parameter list before and after the solve and removed the "Num Blocks" and "Block Size" parameters to make sure they weren't added to the parameter list.  Here is what I saw:

Belos list before solve: 
Maximum Iterations = 999   [unused]
Maximum Restarts = 15   [unused]
Convergence Tolerance = 1e-05   [unused]
Orthogonalization = DGKS   [unused]
Verbosity = 49   [unused]


Dimension of matrix: 1000
Number of right-hand sides: 1
Block size used by solver: 1
Max number of restarts allowed: 15
Max number of Gmres iterations per linear system: 999
Relative residual tolerance: 1e-05


Belos::StatusTestGeneralOutput: Passed
  (Num calls,Mod test,State test): (28, 1, Passed)
   Passed.......OR Combination -> 
     OK...........Number of Iterations = 27 < 999
     Converged....(2-Norm Res Vec) / (2-Norm Prec Res0)
                  residual [ 0 ] = 6.92615e-06 < 1e-05

================================================================================

                      TimeMonitor results over 1 processor

Timer Name                                        Global time (num calls)    
--------------------------------------------------------------------------------
Belos: DGKS[2]: Ortho (Inner Product)             0.000692 (54)              
Belos: DGKS[2]: Ortho (Norm)                      6.6e-05 (82)               
Belos: DGKS[2]: Ortho (Update)                    0.000827 (54)              
Belos: DGKS[2]: Orthogonalization                 0.003224 (28)              
Belos: Operation Op*x                             0.001322 (29)              
Belos: Operation Prec*x                           0 (0)                      
Belos: PseudoBlockGmresSolMgr total solve time    0.008963 (1)               
Epetra_CrsMatrix::Multiply(TransA,X,Y)            0.001354 (30)              
================================================================================
Belos list after solve: 
Maximum Iterations = 999
Maximum Restarts = 15
Convergence Tolerance = 1e-05
Orthogonalization = DGKS
Verbosity = 49

So, the list is not changed if the solver managers are used directly.  Now are the solver manager objects being created the the Belos::SolverFactory inside Nalu?  I'm not as familiar with whether the solver factory modifies the input parameter list to include the valid parameters for the particular solver being created.

**Comment by sayerhs** [comment]
@hkthorn Yes, Nalu uses Belos::SolverFactor. See [Nalu/src/LinearSolver.C](https://github.com/NaluCFD/Nalu/blob/master/src/LinearSolver.C#L147).
