### ISSUE TITLE
Look into adding pull request testing to STK/SEACAS integration

### ISSUE THREAD

**Issue by bmpersc** [trilinos/Trilinos#2044]
@trilinos/framework 

## Expectations
Instead of directly pushing to the develop branch after local tests pass have the integration issue a pull request so that the PR testing will be done as well.

## Current Behavior
The integration currently runs a set of tests and if those tests pass pushes to the develop branch directly. This was the pattern all developers used when this tool was created.

## Motivation and Context
With the impending switch to use PR's for all contributions the automated things should also switch to this. Worst case is that is really is unneeded, best case is that it provides additional testing and protections.

## Possible Solution
The tools we are using already know how to push to a github repo, we need to switch that to use a fork, either from someone on the framework team or create one special for this. From there we then need to have an automated way to issue the pull request from the existing tool. Using the github api it may already be possible to issue a pull request from a script. If so this should be pretty easy to do. I will need to look into what is possible with the github api for this.

**Comment by jmgate** [comment]
It's definitely possible using the GitHub API.  For example, here are two scripts I've whipped up that use the pull request API:  [submitPR](https://github.com/trilinos/Trilinos/files/1528279/submitPR.txt) and [mergeRequests](https://github.com/trilinos/Trilinos/files/1528280/mergeRequests.txt).  If you need any help with the API, let me know.
