### ISSUE TITLE
Tpetra: New finite-element assembly example breaks Sierra builds

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#2045]
Tpetra's new finite-element assembly example breaks Sierra builds, because it uses `GlobalOrdinal=long long` unconditionally.  Sierra disables `long long` in favor of `long`.

Tpetra developers should never assume that any particular GlobalOrdinal type is enabled.  They should always check macros and/or CMake variables to do so.

If the example does not need a particular GlobalOrdinal type, use the default type.  Ditto for the LocalOrdinal type.  For example:
```
typedef typename Tpetra::Map<>::local_ordinal_type LO;
typedef typename Tpetra::Map<>::global_ordinal_type GO;
```
Prefer this pattern if at all possible.

@trilinos/tpetra @prwolfe 

## Motivation and Context

Sierra uses `GlobalOrdinal=long`.  Requiring Sierra to enable `long long` just for this one example would waste build time and library size.  Some Sierra products already push linkers' 32-bit limit for executable size.

## Definition of Done

Either use the above pattern to get the local and global ordinal types, or protect the example with macros and/or CMake options.  I prefer the former.

**Comment by william76** [comment]
@mhoemmen looks like the those builds were fixed by the changes from yesterday.  I'm ok with closing out this ticket if you are :)

**Comment by mhoemmen** [comment]
Thanks @william76 ! :D

**Comment by mhoemmen** [comment]
@prwolfe
