### ISSUE TITLE
Error linking ThyraEpetraAdapters_TestThyraDebugHang.exe

### ISSUE THREAD

**Issue by ndaman** [trilinos/Trilinos#2046]
@mhoemmen 

## Expectations

I am trying to build Trilinos with the options listed [here](https://peridigm.sandia.gov/content/trilinos) on a Fedora Linux VM (gcc 7.2.1).

## Current Behavior

While linking ThyraEpetraAdapters_TestThyraDebugHang.exe I get the following error:

```
[ 86%] Linking CXX executable ThyraEpetraAdapters_TestThyraDebugHang.exe
CMakeFiles/ThyraEpetraAdapters_TestThyraDebugHang.dir/TestThyraDebugHang.cpp.o: In function `ThyraEpetraMultiVector_HangingInParallelDebug_UnitTest::runUnitTestImpl(Teuchos::basic_FancyOStream<char, std::char_traits<char> >&, bool&) const':
TestThyraDebugHang.cpp:(.text+0xad3): undefined reference to `Thyra::DefaultSpmdVectorSpace<double>::initialize(Teuchos::RCP<Teuchos::Comm<long> const> const&, long, long, bool)'
collect2: error: ld returned 1 exit status
```

**Comment by mhoemmen** [comment]
@ndaman Sorry for the late reply!  Is this still an issue for you?

**Comment by teja781** [comment]
Sorry to resurrect an old thread, but I am having the exact same issue. (Also using the same instructions to install peridigm). I am running centos-6.9 with gcc-6.1.0. Any updates/fixes for this?

Thanks

**Comment by mhoemmen** [comment]
What version of Trilinos is this?

**Comment by teja781** [comment]
Version 12.12

**Comment by mhoemmen** [comment]
@trilinos/thyra

**Comment by teja781** [comment]
I am sorry, but I thought that was the latest version. I pulled it from the Trilinos github page.

**Comment by mhoemmen** [comment]
@teja781 When you say "the latest version," do you mean "the current master branch of Trilinos"?

**Comment by teja781** [comment]
Just tried it with the 'develop' branch. I am getting the same error.

**Comment by teja781** [comment]
Are there any updates on this?

**Comment by mhoemmen** [comment]
@teja781 No.  Thyra Dashboard looks clean.  What happens if you omit the `CMAKE_CXX_FLAGS` option?   I'm curious if there's some funny interaction between enabling C++11 (which Trilinos requires) and disabling `long long`.

**Comment by teja781** [comment]
Omitting the CMAKE_CXX_FLAGS didn't make a difference. I am getting the same error.

**Comment by mhoemmen** [comment]
@teja781 What happens if you purge the `long long` flag?  There's no need to disable `long long` support in Trilinos any more, since the relevant parts of Trilinos now require C++11 (which comes with `long long`).

**Comment by teja781** [comment]
I removed the flag that was disabling long long. Still no difference.

**Comment by aroudgar** [comment]
I have exactly the same issue

**Comment by bartlettroscoe** [comment]
Is there an env/machine set up at SNL where I can easily reproduce this build failure?

**Comment by srajama1** [comment]
@rppawlo

**Comment by aroudgar** [comment]
Here is my env setup:
gcc/7.3.0
openmpi/3.1.2
hdf5-mpi/1.8.18 
netcdf-mpi/4.6.1 
cmake/3.12.3 
boost-mpi/1.68.0  
imkl/2018.3.222

cmake -D CMAKE_INSTALL_PREFIX:PATH=<PATH> \
-D CMAKE_CXX_FLAGS:STRING="-O2 -std=c++11 -pedantic -ftrapv -Wall -Wno-long-long" \
-D CMAKE_BUILD_TYPE:STRING=RELEASE \
-D Trilinos_WARNINGS_AS_ERRORS_FLAGS:STRING="" \
-D Trilinos_ENABLE_ALL_PACKAGES:BOOL=OFF \
-D Trilinos_ENABLE_Teuchos:BOOL=ON \
-D Trilinos_ENABLE_Shards:BOOL=ON \
-D Trilinos_ENABLE_Sacado:BOOL=ON \
-D Trilinos_ENABLE_Epetra:BOOL=ON \
-D Trilinos_ENABLE_EpetraExt:BOOL=ON \
-D Trilinos_ENABLE_Ifpack:BOOL=ON \
-D Trilinos_ENABLE_AztecOO:BOOL=ON \
-D Trilinos_ENABLE_Amesos:BOOL=ON \
-D Trilinos_ENABLE_Anasazi:BOOL=ON \
-D Trilinos_ENABLE_Belos:BOOL=ON \
-D Trilinos_ENABLE_ML:BOOL=ON \
-D Trilinos_ENABLE_Phalanx:BOOL=ON \
-D Trilinos_ENABLE_Intrepid:BOOL=ON \
-D Trilinos_ENABLE_NOX:BOOL=ON \
-D Trilinos_ENABLE_Stratimikos:BOOL=ON \
-D Trilinos_ENABLE_Thyra:BOOL=ON \
-D Trilinos_ENABLE_Rythmos:BOOL=ON \
-D Trilinos_ENABLE_MOOCHO:BOOL=ON \
-D Trilinos_ENABLE_TriKota:BOOL=OFF \
-D Trilinos_ENABLE_Stokhos:BOOL=ON \
-D Trilinos_ENABLE_Zoltan:BOOL=ON \
-D Trilinos_ENABLE_Piro:BOOL=ON \
-D Trilinos_ENABLE_Teko:BOOL=ON \
-D Trilinos_ENABLE_SEACASIoss:BOOL=ON \
-D Trilinos_ENABLE_SEACAS:BOOL=ON \
-D Trilinos_ENABLE_SEACASBlot:BOOL=ON \
-D Trilinos_ENABLE_Pamgen:BOOL=ON \
-D Trilinos_ENABLE_EXAMPLES:BOOL=OFF \
-D Trilinos_ENABLE_TESTS:BOOL=ON \
-D TPL_ENABLE_HDF5:BOOL=ON \
-D HDF5_INCLUDE_DIRS:PATH="path to hdf5 include" \
-D HDF5_LIBRARY_DIRS:PATH="path to hdf5 lib" \
-D TPL_ENABLE_Netcdf:BOOL=ON \
-D TPL_Netcdf_Enables_Netcdf4:BOOL=ON \
-D Netcdf_INCLUDE_DIRS:PATH="path to netcdf include" \
-D Netcdf_LIBRARY_DIRS:PATH="path to netcdf lib" \
-D TPL_ENABLE_MPI:BOOL=ON \
-D TPL_ENABLE_Boost:BOOL=ON \
-D Boost_INCLUDE_DIRS:PATH=" path to boost include" \
-D Boost_LIBRARY_DIRS:PATH="path to boost lib" \
-D CMAKE_VERBOSE_MAKEFILE:BOOL=OFF \
-D Trilinos_VERBOSE_CONFIGURE:BOOL=OFF \
-D TPL_ENABLE_MKL=ON \
-D MKL_INCLUDE_DIRS="path to mkl include " \
-D MKL_LIBRARY_DIRS="path to mkl lib" \
-D TPL_BLAS_LIBRARIES:STRING="-lmkl_intel_ilp64 -lmkl_sequential -lmkl_core -lpthread -lm -ldl" \
-D TPL_LAPACK_LIBRARIES:STRING="-lmkl_intel_ilp64 -lmkl_sequential -lmkl_core -lpthread -lm -ldl" \
-DTPL_ENABLE_Matio=OFF \
-DX11_LIBRARY_DIRS="$NIXUSER_PROFILE/lib" \
-DX11_INCLUDE_DIRS="$NIXUSER_PROFILE/include" \
../

**Comment by mhoemmen** [comment]
> `-D CMAKE_CXX_FLAGS:STRING="-O2 -std=c++11 -pedantic -ftrapv -Wall -Wno-long-long"`

1. Please remove `-Wno-long-long`.  C++11 has `long long`, so we don't need or want this flag any more.
2. Please remove `-ftrapv` unless you have a good reason to leave it there.
3. Normally, the DEBUG vs. RELEASE build choice selects `-O2` or `-g` as appropriate, so you don't need to specify `-O2`.

**Comment by bartlettroscoe** [comment]
Also don't need `-std=c++11` .  That should get set automatically.  

What are:
```
gcc/7.3.0
openmpi/3.1.2
hdf5-mpi/1.8.18
netcdf-mpi/4.6.1
cmake/3.12.3
boost-mpi/1.68.0
imkl/2018.3.222
```
?  Where do those come from?  Do I need to build from source? What is `imkl/2018.3.222`?

Do you get this if you try to build with the SEMS modules?  That is something easy that I could try.  Otherwise, don't know how to reproduce from this info so far.

**Comment by rppawlo** [comment]
In looking at the original output at the top of this post, the missing instantiation has the following object:
```
Teuchos::Comm<long>
```
As far as I know, there is no support for Comm with a long type - it must always be int. Looks like that test is putting an incorrect type into the comm.

**Comment by mhoemmen** [comment]
@rppawlo I thought Thyra used to use some weird unsigned long type in Comm -- did that change?

**Comment by rppawlo** [comment]
@mhoemmen - that sounds vaguely familiar. Thyra hasn't changed in a while. For some reason I thought we were using ETI to build only the int version of Tuechos::Comm, but I just took a look and that is not the case. Back to the drawing board...
