### ISSUE TITLE
Test Zoltan2_orderingTestDriverExample_MPI_1 failing when trying to enable Scotch TPL

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#2052]
**CC:** @trilinos/zoltan2

## Description:

The test `Zoltan2_orderingTestDriverExample_MPI_1` fails when trying to enable the SEMS Scotch TPL (see #2051).  It appears that this test never runs in automated testing on CDash from looking at the query:

* https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&date=2017-12-05&filtercount=2&showfilters=1&filtercombine=and&field1=testname&compare1=65&value1=Zoltan2_orderingTestDriverExample&field2=buildstarttime&compare2=84&value2=now

My guess is that is because Zoltan2 is never tested with Scotch enabled in any automated builds of Trilinos that post to CDash.  Therefore this failing test is not really a regression because it is never run.

* Related to: #1400, #2051

**Comment by mhoemmen** [comment]
@prwolfe @rrdrake

**Comment by bartlettroscoe** [comment]
This test is disabled in the CI build that uses the files under Trilinos/cmake/std/ (which is different form the CI build that the Trilinos Framework team runs).  You can see this test being disabled in the initial CI build this morning at:

* https://testing.sandia.gov/cdash/index.php?project=Trilinos&parentid=3259601

Looking at the configure output for Zoltan2 at:

* https://testing.sandia.gov/cdash/viewConfigure.php?buildid=3259684

you can see that test getting disabled at configure time showing:

```
-- Zoltan2_orderingTestDriverExample_MPI_1: NOT added test because Zoltan2_orderingTestDriverExample_MPI_1_DISABLE='ON'!
```

If someone wants to fix this failing test, they can first revert this commit 015cce4 locally using:

```
$ git revert 015cce4
```

then they can reproduce the failing test by following the setup [here](https://github.com/trilinos/Trilinos/wiki/Policies-%7C-Safe-Checkin-Testing) and then using:

```
$ ./checkin-test-sems.sh --enable-all-packages=off --no-enable-fwd-packages \
  --enable-packages=Zoltan2 --local-do-all
```

Let me know if anyone has questions on this.
