### ISSUE TITLE
KokkosContainers_UnitTest_MPI_1 Time Out on Shepard using GCC 4.8.4

### ISSUE THREAD

**Issue by nmhamster** [trilinos/Trilinos#206]
KokkosContainers_UnitTest_MPI_1 test is timing out on Shepard using GCC 4.8.4.

To reproduce:

- `module load devpack/openmpi/1.10.0/gcc/4.8.4/cuda/7.5.18`
- Configure Trilinos
- `make`
- `make test`

**Comment by crtrott** [comment]
Is it possibly a thread scaling issue (i.e. runtime increases with number of threads?), or an issue of binding? Most of the tests are hardcoded to a low number of threads, but I believe some of the container tests use all available (i.e. OMP_NUM_THREADS) threads. If you have the thing open it would be nice if you could just run it with OMP_NUM_THREADS=2 again. That said if it is a scaling issue we need to resolve that.

**Comment by nmhamster** [comment]
`OMP_NUM_THREADS=2 make test` doesn't seem to have fixed it (still seems to hang then timeout).

**Comment by crtrott** [comment]
can you post (or put) your configure script somewhere?

**Comment by nmhamster** [comment]
Attached to this comment. Note - I backed off on the HSW optimization flags and the test still fails. I also checked with Intel 16.1 and am seeing the output below. This is on Shepard but I can also replicate on Hansen as well.

```
99% tests passed, 2 tests failed out of 600

Label Time Summary:
Amesos       =   4.58 sec (8 tests)
Amesos2      =   4.01 sec (9 tests)
AztecOO      =   4.69 sec (11 tests)
Belos        =  39.12 sec (54 tests)
Epetra       =  26.89 sec (52 tests)
EpetraExt    =   5.96 sec (10 tests)
Ifpack       =  22.05 sec (41 tests)
Ifpack2      =  11.06 sec (25 tests)
Intrepid     =   7.17 sec (24 tests)
Kokkos       = 1658.35 sec (9 tests)
ML           =  10.18 sec (16 tests)
MueLu        =  70.73 sec (25 tests)
SEACAS       =   0.70 sec (3 tests)
STK          =   1.04 sec (2 tests)
Shards       =   0.20 sec (1 test)
Teuchos      =  45.99 sec (118 tests)
Tpetra       =  39.32 sec (90 tests)
Zoltan       = 508.25 sec (26 tests)
Zoltan2      =  48.03 sec (81 tests)

Total Test time (real) = 2521.68 sec

The following tests FAILED:
	  7 - KokkosContainers_UnitTest_MPI_1 (Timeout)
	113 - TeuchosNumerics_BLAS_ROTG_test_MPI_1 (Failed)
```

[do-configure-devpack-gcc-4.8.4.sh.gz](https://github.com/trilinos/Trilinos/files/169654/do-configure-devpack-gcc-4.8.4.sh.gz)

**Comment by mhoemmen** [comment]
Failure of TeuchosNumerics_BLAS_ROTG_test_MPI_1 here:
https://github.com/trilinos/Trilinos/issues/211

**Comment by nmhamster** [comment]
`module use /home/projects/x86-64-haswell/nvidia/modulefiles`

**Comment by crtrott** [comment]
its x86-64-haswell-nvidia

**Comment by nmhamster** [comment]
Is running correctly with my latest VOTD using GCC 4.8.4 and Intel 16.1

**Comment by mhoemmen** [comment]
Re. #211 -- I just approved @bartlettroscoe 's pull request, temporarily disabling the test.

**Comment by crtrott** [comment]
Mark why did you do that. We just closed the issue since it was not actually the case? Can anybody actually reproduce the issue currently?

**Comment by crtrott** [comment]
Oh I see this is the BLAS_ROTG ok never mind.

**Comment by mhoemmen** [comment]
> Oh I see this is the BLAS_ROTG ok never mind.

:-D  Yeah, don't worry, I didn't fiddle w/ Kokkos.  I just approved Ross' changes to the Teuchos' DefaultBLASImpl ROTG test.
