### ISSUE TITLE
Add sems-scotch/6.0.3/nopthread_64bit_parallel TPL to automated PR builds of Trilinos

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#2065]
**CC:** @trilinos/framework, @trilinos/zoltan, @trilinos/zoltan2, @trilinos/shylu 

## Motivation and Context

It would be advantageous to add testing of Trilinos with the Scotch TPL to the automated PR testing builds (and perhaps other builds) that the Trilinos Framework team runs.  Scotch is an important TPL used by several customers and developers.  It is directly used in the Trilinos packages Zoltan, Zoltan2, and ShyLU as shown by:

```
$ find . -name Dependencies.cmake -exec grep -nHi scotch {} \;
...
./packages/zoltan2/cmake/Dependencies.cmake:6:SET(LIB_OPTIONAL_DEP_TPLS METIS PaToH ParMETIS PuLP Scotch AMD CCOLAMD OVIS TopoManager rcalib)
./packages/zoltan2/cmake/Dependencies.cmake:8:SET(TEST_OPTIONAL_DEP_TPLS METIS PaToH ParMETIS PuLP Scotch AMD CCOLAMD OVIS TopoManager rcalib)
./packages/shylu/shylu_node/basker/cmake/Dependencies.cmake:5:SET(LIB_REQUIRED_DEP_TPLS Scotch)
./packages/shylu/shylu_node/basker/cmake/Dependencies.cmake:7:SET(TEST_REQUIRED_DEP_TPLS Scotch)
./packages/shylu/shylu_node/tacho/cmake/Dependencies.cmake:6:SET(LIB_OPTIONAL_DEP_TPLS METIS Scotch Cholmod HWLOC HYPRE MKL LAPACK BLAS Pthread QTHREAD VTune)
./packages/zoltan/cmake/Dependencies.cmake:6:SET(LIB_OPTIONAL_DEP_TPLS MPI METIS ParMETIS PaToH Scotch Zlib CCOLAMD OVIS)
```

Story #2051 demonstrated that the BASIC tests in the PT packages in Trilinos pass using the SEMS-provided TPL module `sems-scotch/6.0.3/nopthread_64bit_parallel`.  In fact, the CI Build linked to from:

* https://github.com/trilinos/Trilinos/wiki/Policies--%7C-Testing#post_push_ci_testing

now enables that Scotch TPL.  Since the automated PR builds of Trilinos do not enable Scotch, branches that pass the automated PR testing may break that other TPL build which enables Scotch.  Therefore, to help protect that CI build and Trilinos developers and customers that rely on Scotch in Trilinos, it would be good to add Scotch to the list of enabled TPLs in the automated PR builds (and perhaps in other builds as well using the SEMS env).

## Definition of Done

* [ ] At least one of the automated PR builds of Trilinos enables the sems-scotch/6.0.3/nopthread_64bit_parallel TPL.

## Related Issues

* Blocks 
* Is blocked by 
* Follows 
* Precedes 
* Related to: #2051, #1400
* Part of 
* Composed of

**Comment by mhoemmen** [comment]
@rrdrake @prwolfe
