### ISSUE TITLE
Duplicate local variable name creates shadow warning in TpetraExt_MatrixMatrix_def.hpp

### ISSUE THREAD

**Issue by prwolfe** [trilinos/Trilinos#2069]
@trilinos/tpetra

## Expectations

The new matrix Bk at line 2352 shadows the old one (a local matrix) at line 2422 and this fails when warnings as errors is enabled.  Since these have drastically different types I expect that the local one could be renamed. Re-scoping the outer matrix does not appear to be simple.

## Current Behavior

All builds with warning-as-error on show this failure. See https://testing.sandia.gov/cdash/viewBuildError.php?buildid=3266059 as an example.

**Comment by mhoemmen** [comment]
I just poked the MueLu developers through e-mail.  They may be working on this part of the code actively so I asked if I should wait or just fix it.

**Comment by csiefer2** [comment]
@mhoemmen Thanks for the poke.  Evidently assignments don't generate correct emails to me, only "@" mentions.

@prwolfe The link you sent does not show any warnings in Tpetra, but the dashboard looks hosed at present.  I will look into this.

**Comment by csiefer2** [comment]
Checkin script running.

**Comment by mhoemmen** [comment]
Thanks @csiefer2 ! :D

**Comment by prwolfe** [comment]
Hmm, I am still seeing this today.  Looks like there is at least one more of these.  I will send you a pull request.

**Comment by csiefer2** [comment]
Well shoot.

**Comment by prwolfe** [comment]
Looks good today - Thanks!
