### ISSUE TITLE
build of Kokkos_Sparse_MV_impl_spmv_Serial.cpp.o fails if you use nvcc and have cuda disabled

### ISSUE THREAD

**Issue by bathmatt** [trilinos/Trilinos#208]
If I don't configure with cuda but still have OMPI_CXX=nvcc_wrapper I get the following. This is on hansen

[ 66%] Building CXX object packages/tpetra/kernels/src/CMakeFiles/tpetrakernels.dir/impl/Kokkos_Sparse_MV_impl_spmv_Serial.cpp.o
/home/mbetten/Trilinos/Trilinos/packages/tpetra/kernels/src/impl/Kokkos_Sparse_impl_spmv.hpp(885): error: namespace "Kokkos" has no member "shfl_down"

**Comment by mhoemmen** [comment]
@trilinos/tpetra @crtrott 

It's a little weird to build with CUDA off but use nvcc_wrapper as the compiler.  Is that a use case you care about?  Just curious.

**Comment by nmhamster** [comment]
@mhoemmen This should still work though right?

**Comment by mhoemmen** [comment]
> This should still work though right?

@nmhamster Yes, there's just some missing or wrong macro.  Should be easy to fix.

**Comment by mhoemmen** [comment]
@bathmatt Is this the current version of the code (master, not release branch)?  I'm looking at line 885 of tpetra/kernels/src/impl/Kokkos_Sparse_impl_spmv.hpp.  Note that it is protected by `#ifdef __CUDA_ARCH__` ... `#endif` (lines 883-894).  Thus, the compiler shouldn't actually see this if CUDA is off (so that all code is host code), right?

**Comment by crtrott** [comment]
No the problem is that if you compile with nvcc_wrapper you do a pass for device compilation. I.e. you do actually compile with __CUDA_ARCH__ defined. The Kokkos shfl wrappers on the other hand are only defined if both __CUDA_ARCH__ and KOKKOS_HAVE_CUDA are defined.

**Comment by bathmatt** [comment]
I came across it by mistake, and I'm guessing others will as well.  change
a config but not unset the ompi_cxx var.

Is it a use case I care about, not really, just reporting things as I see
them

**Comment by mhoemmen** [comment]
> The Kokkos shfl wrappers on the other hand are only defined if both CUDA_ARCH and KOKKOS_HAVE_CUDA are defined.

Then it would only make sense to use them if both are defined, right?  Just checking my common sense after a hard last few days :-)

**Comment by crtrott** [comment]
Yes.
