### ISSUE TITLE
New test TeuchosCore_testTeuchosTestForTermination failing in clean build Linux-gcc-4.9.3-SERIAL_Release_gcc_4.9.3__DEV

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#2092]
**CC:** @trilinos/framework, @trilinos/teuchos 

## Description:

The new test `TeuchosCore_testTeuchosTestForTermination` added yesterday (see #2089) is failing in the clean build `Linux-gcc-4.9.3-SERIAL_Release_gcc_4.9.3__DEV` shown at:

* https://testing.sandia.gov/cdash/testDetails.php?test=43561818&build=3286245

What is strange is that the test STDOUT is printing:

```
Teuchos::GlobalMPISession::GlobalMPISession(): started serial run
/scratch/trilinos/workspace/trilinos-folder/Trilinos_generic_nightly/SERIAL_Release_gcc_4.9.3__DEV/Trilinos/packages/teuchos/core/test/MemoryManagement/testTeuchosTestForTermination.cpp:63:

Terminate test that evaluated to true: GlobalMPISession::getRank() == terminate_on_procid

Bingo, we are terminating on procid == terminate_on_procid = 0!

terminate called without an active exception
```

but "Fail Reason" says: "Required regular expression found.Regex=[Bingo, we are terminating on procid == terminate_on_procid = 0"

But if you look at that STDOUT, that output is being printed!  What the heck?

The only other build so far that is showing this same failure is the Experimental build ` Linux-GCC-4.9.3-RELEASE_DEV_KokkosKernels_Experimental` (which is also a serial build) with the test results shown at:

* https://testing.sandia.gov/cdash/testDetails.php?test=43561320&build=3286162

And that test is exactly the same!

## Related Issues

* Related to: #1303, #2089

**Comment by ibaned** [comment]
could this have to do with the fact that `TEUCHOS_TEST_FOR_TERMINATION` actually prints to `stderr`, not `stdout` ?

**Comment by bartlettroscoe** [comment]
> could this have to do with the fact that `TEUCHOS_TEST_FOR_TERMINATION` actually prints to `stderr`, not `stdout` ?

Perhaps.  It might be that MPI handling of STDOUT and STDERR is different than the raw C++ compiler runtime and that might confuse the built-in ctest check for PASS_REGULAR_EXPRESSION.  That is the only difference that I can think of with running this test with `mpirun` vs. just running the raw executable.

I am trying to reproduce this now.

**Comment by bartlettroscoe** [comment]
I can reproduce the failure locally with a SERIAL build.  I bet that using TRIBITS_ADD_ADVANCED_TEST() vs. raw CTest to grep the output will fix the problem.

**Comment by bartlettroscoe** [comment]
>  I bet that using TRIBITS_ADD_ADVANCED_TEST() vs. raw CTest to grep the output will fix the problem.

Yup, that fixed this problem.  I will add a detailed comment in the test CMakeLists.txt file and describing what is happening and why this change was made.

**Comment by bartlettroscoe** [comment]
Commit is pushed.  Should be cleaned up tomorrow.

PUtting into review.
