### ISSUE TITLE
configure looks for x11 libraries, but the final binaries don't use it

### ISSUE THREAD

**Issue by yurivict** [trilinos/Trilinos#2095]
Without x11 libraries the build fails:
```
Processing enabled TPL: X11 (enabled by SEACASSVDI, disable with -DTPL_ENABLE_X11=OFF)
-- X11_LIBRARY_NAMES='X11'
-- Searching for libs in X11_LIBRARY_DIRS=''
-- Searching for a lib in the set "X11":
--   Searching for lib 'X11' ...
-- NOTE: Did not find a lib in the lib set "X11" for the TPL 'X11'!
-- ERROR: Could not find the libraries for the TPL 'X11'!
-- TIP: If the TPL 'X11' is on your system then you can set:
```

Please either use them, or don't search for them.

```-DTPL_ENABLE_X11=OFF``` should either both search for and use x11, or not search and not use x11.

**Comment by lucbv** [comment]
@yurivict if you are unabling a package that needs the X11 library such as SEACAS, CMake will try to find it. The fact that CMake cannot find the X11 library is easily fixed by specifying the path to that library in the variables `X11_LIBRARY_DIRS=''` as you can see in the output of CMake.

**Comment by yurivict** [comment]
@lucbv Thanks for the clue, this fixed this problem.
