### ISSUE TITLE
Installs stray executable: bin/sphgen

### ISSUE THREAD

**Issue by yurivict** [trilinos/Trilinos#2097]
It looks like something that is used to generate documentation.

Please, review the list of files installed into ```bin/``` and make sure they are all really needed:
```
bin/aprepro
bin/cth_pressure_map
bin/exomatlab
bin/io_info
bin/io_shell
bin/shell_to_hex
bin/skinner
```

**Comment by mhoemmen** [comment]
@alanw0 @trilinos/framework @gsjaardema

**Comment by mhoemmen** [comment]
@yurivict I would consider best practice for installing Trilinos, to be to set `CMAKE_INSTALL_PREFIX` and install Trilinos in its own subdirectory.

**Comment by yurivict** [comment]
> set CMAKE_INSTALL_PREFIX and install Trilinos in its own subdirectory.

Can't do this in a standard package. Besides, all the above executables are obviously stray, they belong to random bundled dependencies. You can't just install them all again.

**Comment by mhoemmen** [comment]
@yurivict Regarding how to configure Trilinos for package systems, you may wish to talk to Nico Schlömer ( @nschloe ).  I think Nico has worked on Trilinos installation for Fedora or some other kind of package system before.

**Comment by nschloe** [comment]
> all the above executables are obviously stray

Those executables are coming from seacas I think, and are actually useful tools. @gdsjaar might be able to give more details. 

> set CMAKE_INSTALL_PREFIX and install Trilinos in its own subdirectory.

Yep, that should work.

**Comment by yurivict** [comment]
> set CMAKE_INSTALL_PREFIX and install Trilinos in its own subdirectory.

You should understand that my task isn't just "install trilinos". I need to create the official FreeBSD port for Trilinos. Having its own prefix isn't allowed. Not one other package does this. For my own purposes, I surely could use a separate prefix. But everything should be installed from packages.

**Comment by nschloe** [comment]
> I need to create the official FreeBSD port for Trilinos.

Alright, nice. I'm the Debian maintainer of Trilinos, and first off I'd like to let you know that I've been through the same ordeal that you have. Many of the initial papercuts should be removed such that we have a (more or less) stable Debian port, but it's good to have someone like you take a second look.

You might want to check out [the Debian rules](https://anonscm.debian.org/cgit/debian-science/packages/trilinos.git/tree/debian/rules#n90) for the build; some of the CMake options may be useful for you as well.

> Having its own prefix isn't allowed.

Same for Debian.

Referring to the original post, I don't see anything wrong with the executables. Everything installs into `/usr/bin`, right?

**Comment by yurivict** [comment]
> You might want to check out the Debian rules for the build

Thank you for this, I will certainly look.

> Referring to the original post, I don't see anything wrong with the executables. Everything installs into /usr/bin, right?

```sphgen``` is a separate "sphere generation" project from UCSF. One day, if it will become a separate port, there will be a conflict. It should be renamed into ```trilinos-sphgen``` to avoid this. UCSF Chimera also uses ```sphgen```, and might be installing it too.

**Comment by nschloe** [comment]
I see. Well, all of the binaries you mention are coming from the SEACAS package which also has its own repo (https://github.com/gsjaardema/seacas). I'd say file a bug over there and you'll get helped faster. 

As a side note, one feature of Trilinos is that the main repo is just a collection of packages, some developed there, some pulled in from somewhere else (like SEACAS and Kokkos). Why the sources are copied over and checked in instead of git-submoduling them, I don't know.

**Comment by mhoemmen** [comment]
Thanks @nschloe for the quick answer at a quiet time of year! :-D

> Why the sources are copied over and checked in instead of git-submoduling them, I don't know.

@bartlettroscoe or @jwillenbring might be able to say more.  If I remember right, this decision might not entirely have been theirs to make.
