### ISSUE TITLE
Please have a more reasonable default for the docs and examples directories

### ISSUE THREAD

**Issue by yurivict** [trilinos/Trilinos#2098]
Currently, it installs examples into ```lib/cmake/tribits/examples/```, docs into ```lib/cmake/tribits/doc```, and they aren't even cmake-related.

Please change the examples directory to ```share/examples/Trilinos```.
Please change the docs directory to ```share/doc/Trilinos```.

**Comment by mhoemmen** [comment]
We need more information to interpret this.  What's it?  What are your CMake options?  Please reopen and add the necessary information.
