### ISSUE TITLE
Configuration fails: CMake Error: CMake can not determine linker language for target: blotlib

### ISSUE THREAD

**Issue by yurivict** [trilinos/Trilinos#2100]
This error occurs when ```-DTPL_ENABLE_Netcdf=ON```:

```
-- Configuring done
CMake Error: CMake can not determine linker language for target: blotlib
CMake Error: CMake can not determine linker language for target: blotlib
CMake Error in packages/seacas/applications/blot/CMakeLists.txt:
  Exporting the target "blotlib" is not allowed since its linker language
  cannot be determined
```

Version: 12-12-1 on FreeBSD 11.1

**Comment by aprokop** [comment]
@trilinos/seacas

**Comment by mhoemmen** [comment]
@yurivict You can turn off packages if they give you trouble.  Trilinos is not a single piece of software; it's > 60 pieces of software with a common build and test infrastructure.

**Comment by gsjaardema** [comment]
This has been fixed. I don't remember which commit, but it was several months ago...
