### ISSUE TITLE
Please consider moving all installed headers into include/Trilinos

### ISSUE THREAD

**Issue by yurivict** [trilinos/Trilinos#2102]
```Trilinos``` installs a lot of headers, and it would be reasonable to have a dedicated directory for them, instead of having them add to already large number of headers in ```include/```.

**Comment by jmgate** [comment]
@yurivict, it looks like you've filed quite a few issues against Trilinos in the last day.  You're more likely to get a timely response if you read, fill out, and follow the instructions in the issue template that automatically populates the issue description field.  With the limited information you've included in these issues, it's hard for us to tell what you're trying to do and why.

**Comment by yurivict** [comment]
@jmgate I am trying to create a FreeBSD port for Trilinos, version 12-12-1.
I created the individual bug reports for individual issues that I identified in the process.
In this particular case, when one package installs too many header files, it's always advisable for them to be in a dedicated folder. This is easy to do with cmake.

Please don't hesitate to ask any additional questions, I would be happy to provide any information.

**Comment by jmgate** [comment]
@yurivict, I'm just trying to educate you on our [contributing guidelines](https://github.com/trilinos/Trilinos/blob/master/CONTRIBUTING.md).  When you created any of these issues, did the the text below appear in the description field, such that you had to delete it all before typing in your issue description?  If not, then something's wrong with GitHub or our templates, and we'll need to look into that.

```
<!--- Provide a general summary of the issue in the Title above. -->

<!---
Note that anything between these delimiters is a comment that will not appear
in the issue description once created.  Click on the Preview tab to see what
everything will look like when you submit.
-->

<!---
Feel free to delete anything from this template that is not applicable to the
issue you are submitting.
-->

<!---
Replace <teamName> below with the appropriate Trilinos package/team name.
-->
@trilinos/<teamName>

<!---
Assignees:  If you know anyone who should likely tackle this issue, select them
from the Assignees drop-down on the right.
-->

<!---
Lables:  Choose any applicable package names from the Labels drop-down on the
right.  Additionally, choose a label to indicate the type of issue, for
instance, bug, build, documentation, enhancement, etc.
-->

## Expectations
<!---
Tell us what you think should happen, how you think things should work, what
you would like to see in the documentation, etc.
-->

## Current Behavior
<!---
Tell us how the current behavior fails to meet your expectations in some way.
-->

## Motivation and Context
<!---
How has this expectation failure affected you?  What are you trying to
accomplish?  Why do we need to address this?  What does it have to do with
anything?  Providing context helps us come up with a solution that is most
useful in the real world.
-->

## Definition of Done
<!---
Tell us what needs to happen.  If necessary, give us a task lisk along the
lines of:                                                   
- [ ] First do this.
- [ ] Then do that.
- [ ] Also this other thing.
-->

## Possible Solution
<!---
Not obligatory, but suggest a fix for the bug or documentation, or suggest
ideas on how to implement the addition or change.
-->

## Steps to Reproduce
<!---
Provide a link to a live example, or an unambiguous set of steps to reproduce
this issue.  Include code to reproduce, if relevant. 
1. Do this.
1. Do that.
1. Shake fist angrily at computer.
-->

## Your Environment
<!---
Include relevant details about your environment such that we can replicate this
issue.
-->
- **Relevant repo SHA1s:**  
- **Relevant configure flags or configure script:**  
- **Operating system and version:**  
- **Compiler and TPL versions:**  

## Related Issues
<!---
If applicable, let us know how this bug is related to any other open issues:
-->
* Blocks 
* Is blocked by 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of 

## Additional Information
<!---
Anything else that might be helpful for us to know in addressing this issue:
* Configure log file:  
* Build log file:  
* Test log file:  
* When was the last time everything worked (date/time; SHA1s; etc.)?
* What did you do that made the bug rear its ugly head?
* Have you tried turning it off and on again?
-->
```

**Comment by yurivict** [comment]
Yes, I deleted the template and replaced it with the pieces of information that are relevant.

For example, for this include files issue, what other information do you really need? Do you think, for example, that test logs will help? Every time I tried to include the minimum of useful information relevant to the issue. Sorry if some information was still missing. :-)

**Comment by mhoemmen** [comment]
@yurivict It would be good to install Trilinos, including both header files and libraries, in a separate directory.  Just set the `CMAKE_INSTALL_PREFIX` CMake option.  Is there a BSD-specific reason why you would not want to do that?

**Comment by yurivict** [comment]
>  Is there a BSD-specific reason why you would not want to do that?

Yes, BSD package can't install into a separate prefix directory. The common practice is to install everything into the same prefix, but packages installing a lot of headers should install then into their own headers sub-folder.

This is a also a very good practice on all platforms, and many packages do this. Otherwise, install/ folder will end up having a million files.

**Comment by mhoemmen** [comment]
@nschloe , would you happen to know about configuring Trilinos as a BSD package?

**Comment by nschloe** [comment]
> Trilinos installs a lot of headers, and it would be reasonable to have a dedicated directory for them, instead of having them add to already large number of headers in include/.

You want `-DTrilinos_INSTALL_INCLUDE_DIR:PATH=include/trilinos/`.

**Comment by mhoemmen** [comment]
@nschloe wrote:
> ... I agree with @yurivict that the headers should have been put in a more hierarchical structure in the first place.

Kokkos was actually the first Trilinos package (back when it was a real Trilinos package and not snapshotted in) that created a subdirectory in Trilinos' header installation directory.  That caused a bit of grief with Sierra before Brent sprinkled fairy dust over everything and made it happy.
