### ISSUE TITLE
Panzer tet second order HGrad basis broke

### ISSUE THREAD

**Issue by bathmatt** [trilinos/Trilinos#2112]
Looking at this chunk of code it is clear that there is a bug, the last line should be TET_C2_...

``` 
  else if ( (basis_type == "HGrad") && (cell_type == "Tetrahedron") && (basis_order == 1) )
      basis = Teuchos::rcp( new Intrepid2::Basis_HGRAD_TET_C1_FEM<ExecutionSpace,OutputValueType,PointValueType> );

    else if ( (basis_type == "HGrad") && (cell_type == "Tetrahedron") && (basis_order == 2) )
      basis = Teuchos::rcp( new Intrepid2::Basis_HGRAD_TET_C1_FEM<ExecutionSpace,OutputValueType,PointValueType> );
```

@trilinos/<teamName>

## Your Environment

- **Relevant repo SHA1s:**  
- **Relevant configure flags or configure script:**  
- **Operating system and version:**  
- **Compiler and TPL versions:**  

## Related Issues

* Blocks 
* Is blocked by 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of

**Comment by bathmatt** [comment]
@rppawlo @eric-c-cyr how do you do the new merge request stuff?  No idea.

**Comment by bathmatt** [comment]
@jmgate add you and adding a patch
[p.txt](https://github.com/trilinos/Trilinos/files/1601477/p.txt)

**Comment by rppawlo** [comment]
@bathmatt - fork trilinos, push your change to your fork and then create a PR against the development branch of main repo. The testing will automatically launch. Just wait for the results.

Do you want me to push a fix for the above issue?

**Comment by bathmatt** [comment]
fork, i.e, hit the fork button up top?
or git branch?

**Comment by rppawlo** [comment]
Yes - fork your own copy and push a branch up to that. We try to not clutter up the main repo with branches (although you could do that as well as long as you delete the branch). We could try over skype if you want.
