### ISSUE TITLE
KokkosKernels: build failure when enabling double, complex<double>, and shared libraries

### ISSUE THREAD

**Issue by jhux2** [trilinos/Trilinos#2115]
Xpetra and KokkosKernels builds started failing on the MueLu nightly test machine "geminga" on December ~~14th~~ 16th, but I only noticed today.  As a result, MueLu isn't being tested with CUDA. Here's the dashboard [link](https://testing.sandia.gov/cdash/index.php?project=Trilinos&parentid=3278400&filtercount=3&showfilters=1&field1=buildstamp&compare1=61&value1=20171216-1441-Experimental&filtercombine=and).

**Comment by jhux2** [comment]
Some interesting facts:

1) The build is failing with the cryptic message
`make[2]: *** [packages/kokkos-kernels/src/libkokkoskernels.so.12.13] Error 127`.

2) There are 1248 object files total, and they consume about 202MB total.  So there shouldn't be any issues creating the library, I'd think.

**Comment by jhux2** [comment]
The last day that KokkosKernels built on geminga was December 13, SHA1 1e886f7.  Here's the [link](https://testing.sandia.gov/cdash/index.php?project=Trilinos&parentid=3269384&filtercount=3&showfilters=1&field1=buildstamp&compare1=61&value1=20171211-1445-Experimental&filtercombine=and).  Using the same modules and cmake configure line as the failing build, I was able to build KK locally with 1e886f7.  In this case, there are 444 object files, totaling 76MB.

**Comment by jhux2** [comment]
@trilinos/kokkos-kernels

**Comment by jhux2** [comment]
On December 16th, a new version ofKokkosKernels was snapshotted into Trilinos.

**Comment by jhux2** [comment]
Steps to reproduce with a recent `develop` branch:

```
module load sems-env
module load kokkos-env
module load sems-cmake/3.5.2
module load sems-gcc/5.3.0
module load sems-python/2.7.9
module load kokkos-cuda/8.0.44
module load kokkos-nvcc_wrapper/1
module load kokkos-openmpi/1.8.7/cuda
module load sems-superlu/4.3
```

```
cmake \
  -D BUILD_SHARED_LIBS:BOOL=ON \
  -D CMAKE_BUILD_TYPE:STRING=RELEASE \
  -D CMAKE_VERBOSE_MAKEFILE:BOOL=OFF \
  -D Kokkos_ENABLE_Cuda_Lambda:BOOL=ON \
  -D Kokkos_ENABLE_Cuda_UVM:BOOL=ON \
  -D Kokkos_ENABLE_Pthread:BOOL=OFF \
  -D MPI_BASE_DIR=${SEMS_OPENMPI_ROOT} \
  -D MPI_EXEC_POST_NUMPROCS_FLAGS:STRING='--bind-to-socket' \
  -D MueLu_INST_DOUBLE_INT_LONGINT:BOOL=ON \
  -D Teuchos_ENABLE_COMPLEX:BOOL=OFF \
  -D Tpetra_INST_COMPLEX_DOUBLE:BOOL=OFF \
  -D Tpetra_INST_CUDA:BOOL=ON \
  -D Tpetra_INST_OPENMP:BOOL=OFF \
  -D Tpetra_INST_PTHREAD:BOOL=OFF \
  -D Tpetra_INST_SERIAL:BOOL=ON \
  -D TPL_ENABLE_BLAS:BOOL=ON \
  -D TPL_ENABLE_CUDA:STRING=ON \
  -D TPL_ENABLE_CUSPARSE:BOOL=ON \
  -D TPL_ENABLE_HWLOC:STRING=OFF \
  -D TPL_ENABLE_LAPACK:BOOL=ON \
  -D TPL_ENABLE_Matio=OFF \
  -D TPL_ENABLE_MPI:BOOL=ON \
  -D Trilinos_ALLOW_NO_PACKAGES:BOOL=ON \
  -D Trilinos_CXX11_FLAGS:STRING='-std=c++11 -expt-extended-lambda' \
  -D Trilinos_DISABLE_ENABLED_FORWARD_DEP_PACKAGES=ON \
  -D Trilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=ON \
  -D Trilinos_ENABLE_COMPLEX:BOOL=ON \
  -D Trilinos_ENABLE_CXX11=ON \
  -D Trilinos_ENABLE_DEPENDENCY_UNIT_TESTS:BOOL=OFF \
  -D Trilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON \
  -D Trilinos_ENABLE_KokkosKernels:BOOL=ON \
  -D Trilinos_ENABLE_OpenMP:BOOL=OFF \
  -D Trilinos_ENABLE_SECONDARY_TESTED_CODE:BOOL=ON \
  -D Trilinos_ENABLE_TESTS:BOOL= \
  -D Trilinos_ENABLE_Teuchos:BOOL= \
  ../Trilinos
```

**Comment by jhux2** [comment]
The combination of enabling scalar types `double` and `complex<double>` plus shared libraries triggers the error.  Either disabling `complex` or disabling shared libraries allows the build to finish successfully.   (I'll disable `complex` on the MueLu test machine geminga.)

**Comment by jhux2** [comment]
This doesn't depend on the gcc version; I see the same error using module `sems-gcc/4.9.3`.

**Comment by srajama1** [comment]
@mndevec @crtrott

**Comment by srajama1** [comment]
@crtrott: Any clues on what could be the reason for this failure ?

**Comment by srajama1** [comment]
@jhux2 : Please see https://github.com/kokkos/kokkos-kernels/issues/141

Can you add to the nightlies until we make this always on

-D CMAKE_CXX_USE_RESPONSE_FILE_FOR_OBJECTS:BOOL=ON \

**Comment by jhux2** [comment]
@srajama1 Thanks, I will try this and report back tomorrow.

**Comment by jhux2** [comment]
@srajama1 After I added the option `-DCMAKE_CXX_USE_RESPONSE_FILE_FOR_OBJECTS:BOOL=ON` , Kokkos itself doesn't compile.   You can see the failure [here](https://testing.sandia.gov/cdash/buildSummary.php?buildid=3321247).  The error message is

```
g++: fatal error: cannot specify -o with -c, -S or -E with multiple files
compilation terminated.
make[2]: *** [packages/kokkos/core/src/libkokkoscore.so.12.13] Error 1
make[2]: Leaving directory `/data/jhu/trilinos-test/OPENMPI-1.8.7_RELEASE_KOKKOS-REFACTOR_EXPERIMENTAL_CUDA-8.0.44/BUILD'
make[1]: *** [packages/kokkos/core/src/CMakeFiles/kokkoscore.dir/all] Error 2
make[1]: Leaving directory `/data/jhu/trilinos-test/OPENMPI-1.8.7_RELEASE_KOKKOS-REFACTOR_EXPERIMENTAL_CUDA-8.0.44/BUILD'
make: *** [all] Error 2
```

I verified (by hand) that removing this option allows the Kokkos build to go through.  One thing that's weird is that I see this in my link line, regardless of whether I use the option you suggested:  `-Wl,-rpath,::::::::::::::`.

To reproduce:

```
module load sems-env
module load kokkos-env
module load sems-cmake/3.5.2
module load sems-gcc/5.3.0
module load sems-boost/1.58.0/base
module load sems-python/2.7.9
module load sems-zlib/1.2.8/base
module load kokkos-cuda/8.0.44 
module load kokkos-nvcc_wrapper/1
module load kokkos-openmpi/1.8.7/cuda
module load sems-superlu/4.3
module load sems-hdf5/1.8.12/parallel
```

```cmake
cmake \
-DCMAKE_CXX_USE_RESPONSE_FILE_FOR_OBJECTS:BOOL=ON \
-DTrilinos_TRIBITS_DIR=/data/jhu/trilinos-test/trilinos/cmake/tribits \
-DCTEST_USE_LAUNCHERS:BOOL=1 \
-DTrilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=ON \
-DTrilinos_WARNINGS_AS_ERRORS_FLAGS:STRING= \
-DTrilinos_ALLOW_NO_PACKAGES:BOOL=ON \
-DTrilinos_DISABLE_ENABLED_FORWARD_DEP_PACKAGES=ON \
-DTrilinos_DEPS_XML_OUTPUT_FILE:FILEPATH= \
-DTrilinos_ENABLE_SECONDARY_TESTED_CODE:BOOL=ON \
-DTrilinos_EXTRAREPOS_FILE:STRING=/data/jhu/trilinos-test/trilinos/cmake/ExtraRepositoriesList.cmake \
-DTrilinos_IGNORE_MISSING_EXTRA_REPOSITORIES:BOOL=ON \
-DTrilinos_ENABLE_KNOWN_EXTERNAL_REPOS_TYPE:STRING=Experimental \
-DTrilinos_ENABLE_TESTS:BOOL= \
-DTrilinos_ENABLE_Gtest:BOOL= \
-DTrilinos_ENABLE_Gtest:BOOL=OFF \
-DCMAKE_BUILD_TYPE:STRING=RELEASE \
-DTrilinos_ENABLE_COMPLEX:BOOL=ON \
-DBUILD_SHARED_LIBS:BOOL=ON \
-DTrilinos_ENABLE_CXX11:BOOL=ON \
-DTrilinos_CXX11_FLAGS:STRING='-std=c++11 -expt-extended-lambda' \
-DCMAKE_CXX_FLAGS:STRING='-Wall -Wno-unknown-pragmas -Wno-unused-but-set-variable -Wno-inline -Wshadow' \
-DTrilinos_ENABLE_Fortran:BOOL=OFF \
-DTPL_ENABLE_CUDA:BOOL=ON \
-DTPL_ENABLE_CUSPARSE:BOOL=ON \
-DTPL_ENABLE_HWLOC:BOOL=OFF \
-DKokkos_ENABLE_Cuda:BOOL=ON \
-DKokkos_ENABLE_Cuda_UVM:BOOL=ON \
-DKokkos_ENABLE_Cuda_Lambda:BOOL=ON \
-DCMAKE_VERBOSE_MAKEFILE:BOOL=ON \
-DTPL_ENABLE_MPI:BOOL=ON \
-DMPI_BASE_DIR:PATH=/projects/sems/install/rhel6-x86_64/kokkos/compiler/gcc/5.3.0/openmpi/1.8.7/cuda/8.0.44 \
-DTrilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON \
-DTeuchos_ENABLE_LONG_LONG_INT:BOOL=OFF \
-DTpetra_INST_INT_LONG_LONG:BOOL=OFF \
-DTeuchos_ENABLE_COMPLEX:BOOL=OFF \
-DTpetra_INST_COMPLEX_DOUBLE:BOOL=OFF \
-DTpetra_INST_COMPLEX_FLOAT:BOOL=OFF \
-DTpetra_INST_SERIAL=ON \
-DTrilinos_ENABLE_DEPENDENCY_UNIT_TESTS:BOOL=OFF \
-DTeuchos_GLOBALLY_REDUCE_UNITTEST_RESULTS:BOOL=ON \
-DTPL_ENABLE_SuperLU:BOOL=ON \
-DSuperLU_INCLUDE_DIRS:PATH=/projects/sems/install/rhel6-x86_64/sems/tpl/superlu/4.3/gcc/5.3.0/base/include \
-DSuperLU_LIBRARY_DIRS:PATH=/projects/sems/install/rhel6-x86_64/sems/tpl/superlu/4.3/gcc/5.3.0/base/lib \
-DMueLu_ENABLE_Experimental:BOOL=ON \
-DMueLu_ENABLE_Kokkos_Refactor:BOOL=ON \
-DXpetra_ENABLE_Experimental:BOOL=ON \
-DXpetra_ENABLE_Kokkos_Refactor:BOOL=ON \
-DTrilinos_ENABLE_Kokkos:BOOL=ON \
/data/jhu/trilinos-test/OPENMPI-1.8.7_RELEASE_KOKKOS-REFACTOR_EXPERIMENTAL_CUDA-8.0.44/Trilinos
```

**Comment by bartlettroscoe** [comment]
I wonder if the implementation of `-DCMAKE_CXX_USE_RESPONSE_FILE_FOR_OBJECTS:BOOL=ON` with CMake 3.5.2 does not work with GCC 5.3.0.  Can you try a more recent version of CMake and see if it fixes the problem?  If it does not, then we can bring in Kitware to look into this.  I am sure that GCC did not remove support for response files so this must just be an issue with CMake support for the feature with that compiler.

**Comment by jhux2** [comment]
> Can you try a more recent version of CMake and see if it fixes the problem?

@bartlettroscoe Thanks for the suggestion.  What version of cmake would you suggest I use?

**Comment by bartlettroscoe** [comment]
I would try CMake 3.10.0 to be safe.  If this does not work with that version of CMake, then we can ask Kitware to fix it.

**Comment by jhux2** [comment]
@bartlettroscoe Ok, I just tested with cmake version 3.10.1.  I get the same error as before when the option `-DCMAKE_CXX_USE_RESPONSE_FILE_FOR_OBJECTS:BOOL=ON` is included on the configure line.

**Comment by bartlettroscoe** [comment]
> Ok, I just tested with cmake version 3.10.1. I get the same error as before when the option -DCMAKE_CXX_USE_RESPONSE_FILE_FOR_OBJECTS:BOOL=ON is included on the configure line.

I will try to reproduce myself and go from there ...

**Comment by crtrott** [comment]
Did you actually wipe your build directory after adding that RESPONSE FILE CMake option.

**Comment by jhux2** [comment]
> Did you actually wipe your build directory after adding that RESPONSE FILE CMake option.

@crtrott Yes.

**Comment by srajama1** [comment]
@jhux2 : If kitware cannot quickly get this fixed we have a workaround to generate different libraries for different instantiations of the types. It is a crude fix and might break again when the path length increases or the number of files increase again. Another option is to use wildcards (*.o). I am not sure if we can do that with TriBITS or CMake. 

Sorry for the trouble ! We do not test CUDA and complex enabled at the same time. Is this important ? We can add the test then. It is painful in terms of compilation times though.

**Comment by jhux2** [comment]
@srajama1 No worries.  We don't have a specific requirement to test CUDA and double+complex together, so for the moment I've just disabled complex.  But this seems like something an application could eventually run into.

**Comment by bartlettroscoe** [comment]
@jhux2,

Is there an env var you have to use to use `nvcc_wrapper` with the reproducability instructions shown at [above](https://github.com/trilinos/Trilinos/issues/2115#issuecomment-356382142)?  Actually, what is the ctest -S driver script that is being used for this build?  And what is the top-level driver script you are using in your cron job?

I see this is a CUDA build.  I am wondering if `nvcc_wrapper` and/or `nvcc` is not set up to work correctly with response `*.rsp` files?

NOTE: I did a build GCC 5.3.0 (which I will post the details of soon) that worked just fine with Kokkos.  This is why I suspect this is a problem with `nvcc_wrapper` and/or `nvcc`.  We can fix a problem with the former but not the latter.

**Comment by mhoemmen** [comment]
@jhux2 Sierra will want complex for all their builds, including CUDA builds.

**Comment by bartlettroscoe** [comment]
I did a basic build of Kokkos with basic GCC 5.3.0 with `-DCMAKE_CXX_USE_RESPONSE_FILE_FOR_OBJECTS=ON` and it passed the build and the tests (see details below).  This shows there is no problem with GCC 5.3.0 with `-DCMAKE_CXX_USE_RESPONSE_FILE_FOR_OBJECTS=ON` and CMake.

As I stated above, my guess is is that the problem is with `nvcc_wrapper` and/or `nvcc` handling of response files.

I did some Googling and at one point I think I found a reference (that I can't find now) that said that `*.rsp` files are passed through from `nvcc` to the host compiler along with other `*.o` files.  But then I find this commit baout disabling support for response files for CUDA:

* https://gitlab.kitware.com/cmake/cmake/commit/8fc2f5cea9fb348977a5c83ec6e82695764d360b

But that muight just be for the direct compilation of the device code and not the `nvcc` wrapper itself.

This is going to need some more detailed invesitation.

<details>

<summary>
<b>DETAILED NOTES</b> (Click to expand)
</summary>

Trying to reproduce build failure on crf450 ...

Using `do-configure` script:

```
#!/bin/bash
cmake \
-DTPL_ENABLE_MPI=ON \
-DCMAKE_BUILD_TYPE=RELEASE \
-DTrilinos_ENABLE_DEBUG=ON \
-DBUILD_SHARED_LIBS=ON \
-DTrilinos_ENABLE_SECONDARY_TESTED_CODE=OFF \
-DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/MpiReleaseDebugSharedPtSettings.cmake,cmake/std/BasicCiTestingSettings.cmake \
-DTrilinos_ENABLE_DEBUG_SYMBOLS=ON \
-DTrilinos_ENABLE_EXPLICIT_INSTANTIATION=ON \
-DTrilinos_ENABLE_CONFIGURE_TIMING=ON \
-DTrilinos_ENABLE_TESTS=ON \
-DTrilinos_TRACE_ADD_TEST=ON \
"$@" \
../../../Trilinos
```

Then running:

```
$ cd $HOME/Trilinos.base/BUILDS/GCC-5.3.0/MPI_RELEASE_DEBUG_SHARED_PT/

$ rm -r CMake*

$ source ~/Trilinos.base/Trilinos/cmake/load_sems_dev_env.sh sems-gcc/5.3.0

$ module list
Currently Loaded Modulefiles:
  1) sems-env                                     8) sems-zlib/1.2.8/base
  2) sems-python/2.7.9                            9) sems-hdf5/1.8.12/parallel
  3) sems-cmake/3.5.2                            10) sems-netcdf/4.4.1/exo_parallel
  4) sems-git/2.10.1                             11) sems-parmetis/4.0.3/parallel
  5) sems-gcc/5.3.0                              12) sems-scotch/6.0.3/nopthread_64bit_parallel
  6) sems-openmpi/1.6.5                          13) sems-superlu/4.3/base
  7) sems-boost/1.63.0/base

$ time ./do-configure \
  -DCMAKE_CXX_USE_RESPONSE_FILE_FOR_OBJECTS=ON \
  -DTrilinos_ENABLE_Kokkos=ON \
  &> configure.out

real    0m9.719s
user    0m4.850s
sys     0m2.287s

$ time make VERBOSE=1 -j16 &> make.out
```

This completed the build and I say in the build output:

`[ 19%] Linking CXX shared library libkokkoscore.so
cd /ascldap/users/rabartl/Trilinos.base/BUILDS/GCC-5.3.0/MPI_RELEASE_DEBUG_SHARED_PT/packages/kokkos/core/src && /ascldap/users/projects/sems/install/rhel6-x86_64/sems/utility/cmake/3.5.2/bin/cmake -E cmake_link_script CMakeFiles/kokkoscore.dir/link.txt --verbose=1
/projects/sems/install/rhel6-x86_64/sems/compiler/gcc/5.3.0/openmpi/1.6.5/bin/mpicxx  -fPIC  -pedantic -Wall -Wno-long-long -Wwrite-strings  -g -std=c++11 -O3 -DNDEBUG  -shared -Wl,-soname,libkokkoscore.so.12 -o libkokkoscore.so.12.13 @CMakeFiles/kokkoscore.dir/objects1.rsp /usr/lib64/libdl.so -Wl,-rpath,:::::::::::::: 
cd /ascldap/users/rabartl/Trilinos.base/BUILDS/GCC-5.3.0/MPI_RELEASE_DEBUG_SHARED_PT/packages/kokkos/core/src && /ascldap/users/projects/sems/install/rhel6-x86_64/sems/utility/cmake/3.5.2/bin/cmake -E cmake_symlink_library libkokkoscore.so.12.13 libkokkoscore.so.12 libkokkoscore.so
make[2]: Leaving directory `/home/rabartl/Trilinos.base/BUILDS/GCC-5.3.0/MPI_RELEASE_DEBUG_SHARED_PT'`

Note the argument `@CMakeFiles/kokkoscore.dir/objects1.rsp`.

And I ran the tests and they returned all pased:

```
$ time ctest -j16

[...]

100% tests passed, 0 tests failed out of 23

Label Time Summary:
Kokkos    =  30.66 sec (23 tests)

Total Test time (real) =  14.63 sec

real    0m14.636s
user    0m26.989s
sys     0m1.277s
```

This shows that the problem wit then handling of response files `*.rsp` is not due to gCC 5.3.0.
</details>

**Comment by bartlettroscoe** [comment]
> The combination of enabling scalar types `double` and `complex<double>` plus shared libraries triggers the error.  Either disabling `complex` or disabling shared libraries allows the build to finish successfully.   (I'll disable `complex` on the MueLu test machine geminga.)

@jhux2,

It sounds like your build should be fixed again by disabling complex and it looks like that is the case looking at the build from yesterday:

* https://testing.sandia.gov/cdash/index.php?project=Trilinos&parentid=3322990

@mhoemmen, @prwolfe, and @rrdrake 

How soon will SIERRA need CUDA builds of Trilinos with Complex enabled? 

I sent out an email to the ATDM PIs to see if an CUDA + COMPLEX build is important for ATDM now or in the near future.

**Comment by mhoemmen** [comment]
@bartlettroscoe Sierra always builds with complex enabled.  CUDA is not dreadfully urgent, though this likely would block Trilinos promotion.  However, they do enable `Scalar=float, double, complex<double>`, so it's possible that they might see this error without CUDA enabled.

**Comment by jhux2** [comment]
> Is there an env var you have to use to use nvcc_wrapper with the reproducability instructions shown at above? Actually, what is the ctest -S driver script that is being used for this build? And what is the top-level driver script you are using in your cron job?

@bartlettroscoe The test script is in `trilinos/cmake/ctest/drivers/geminga/cron_driver.sh`.  I don't see any relevant environmental variables there.

**Comment by jhux2** [comment]
@bartlettroscoe The `cron_driver.sh` script echos the environment just before running the tests.  It's attached.
[geminga-env.txt](https://github.com/trilinos/Trilinos/files/1623623/geminga-env.txt)

**Comment by bartlettroscoe** [comment]
Okay, there it is on line 107:

```
OMPI_CXX=nvcc_wrapper
```

That means that the comandline being passedt to `mpicxx` through to `g++` is being filtered through `nvcc_wrapper` before it is getting passed to `g++`.  That is where we need to focus.

I will try to reproduce this failure for myself and see if I can figure out that is happening.  But I may not get to that till Friday or after.

BTW, I got the feedback that there is a new ATDM APP that needs Complex enabled with CUDA (and I would also assume with ETI as well).

**Comment by bartlettroscoe** [comment]
FYI: The ATDM placholder issue for this is:

* https://software-srn.sandia.gov/jira/browse/ATDV-91

This keeps this on our radar.

**Comment by bartlettroscoe** [comment]
Here is what happens to the commadline for a compile and or library creation.

CMake => Makefile => mpicxx => nvcc_wrapper => nvcc => g++

So we need to reproduce the failure shown [above](https://github.com/trilinos/Trilinos/issues/2115#issuecomment-356382142) and then figure out how to get each of these above wrapper to print their commandlines. 

Looking at the current implementation of kokkos/bin/nvcc_wrapper, we see handling of object files like:

```
  #Handle object files: -x cu applies to all input files, so give them to linker, except if only linking
  *.a|*.so|*.o|*.obj)
    object_files="$object_files $1"
    object_files_xlinker="$object_files_xlinker -Xlinker $1"
    ;;
```

but we don't see anything for handling `*.rsp` files.

@crtrott,

Do you have an idea of how `nvcc_wrapper` could be modified to correctly handle `*.rsp` files?  It seems likely that that might be the problem with the CUDA build with `-DCMAKE_CXX_USE_RESPONSE_FILE_FOR_OBJECTS=ON`.

**Comment by bartlettroscoe** [comment]
@jhux2,

@crtrott says that the problem with your build is likely that you are using an old version of `nvcc_wrapper` instead of using the one in Trilinos/packages/kokkos/.  It seems from looking above [here](https://github.com/trilinos/Trilinos/issues/2115#issuecomment-356382142) and [here](https://github.com/trilinos/Trilinos/issues/2115#issuecomment-357024149) that you are using an older version of `nvcc_wrapper` from the fact that you are loading the module:

```
module load kokkos-nvcc_wrapper/1
```

and the env var being used is:

```
OMPI_CXX=nvcc_wrapper
```

Can you please try not loading that module and just setting `OMPI_CXX` to the version of `nvcc_wrapper` at `Trilinos/packages/kokkos/bin/nvcc_wrapper`?  @crtrott says that this is working for him with CUDA + COMPLEX + ETI + `-DCMAKE_CXX_USE_RESPONSE_FILE_FOR_OBJECTS=ON`.

**Comment by ndellingwood** [comment]
@jhux2 just checking in about the issue and if the suggestion above about using the nvcc_wrapper from Kokkos helped?

**Comment by jhux2** [comment]
@ndellingwood Thank you for the reminder to update this issue.  Yes, setting OMPI_CXX to the `nvcc_wrapper` in Trilinos itself (versus using the SEMS module) seems to have fixed the issue.  Note that I also have `complex` enabled and `CMAKE_CXX_USE_RESPONSE_FILE_FOR_OBJECTS=ON`.  The build is [here](https://testing.sandia.gov/cdash/buildSummary.php?buildid=3373023).

**Comment by bartlettroscoe** [comment]
@jhux2,

Does this mean that this problem has been resolved?  Can this issue be closed?

**Comment by srajama1** [comment]
@bartlettroscoe : It depends on the nvcc_wrapper used by our ATDM apps. I assume there is nothing that forces them to use the "old" nvcc_wrapper that causes these failures. This issue can be closed in that case.
 
I would like a mechanism to avoid this problem altogether. We should be able to link  as many files as we want without this silliness. That is a just a feature request and not a bug if both applications use the "new" nvcc_wrapper.

**Comment by jhux2** [comment]
> Does this mean that this problem has been resolved? Can this issue be closed?

@bartlettroscoe Yes, this is resolved as far as I'm concerned.

**Comment by bartlettroscoe** [comment]
> It depends on the nvcc_wrapper used by our ATDM apps. I assume there is nothing that forces them to use the "old" nvcc_wrapper that causes these failures. This issue can be closed in that case.

From talking with @crtrott last week, the only safe version of `nvcc_wrapper` anyone should ever be using is the version in Trilinos at any point in time under `Trilinos/packages/kokkos/bin/nvcc_wrapper`.  Whoever created an `nvcc_wrapper` module should delete it right away and tell people to **always** use 
`Trilinos/packages/kokkos/bin/nvcc_wrapper`.  Otherwise, problems like this are going to keep happening.

**Comment by srajama1** [comment]
@nmhamster : This issue is closed, but just to let you know about the nvcc_wrapper issue.

**Comment by nmhamster** [comment]
@srajama1 - I always use the Trilinos packages `nvcc_wrapper`. Where is the `nvcc_wrapper` module, is it on geminga machine?

**Comment by srajama1** [comment]
I guessed it is part of our module system. I might be wrong.

**Comment by jhux2** [comment]
> I always use the Trilinos packages nvcc_wrapper. Where is the nvcc_wrapper module, is it on geminga machine?

It was part of the local geminga environment;  I've since deleted it.
