### ISSUE TITLE
kokkos-kernels: Build error when MKL TPL is enabled

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#2116]
```
.../Trilinos/packages/kokkos-kernels/src/sparse/impl/KokkosSparse_spgemm_mkl_impl.hpp:165:24: error: use of undeclared identifier 'valuesA'
    value_type *a_ew = valuesA.ptr_on_device();
                       ^
.../Trilinos/packages/kokkos-kernels/src/sparse/impl/KokkosSparse_spgemm_mkl_impl.hpp:166:24: error: use of undeclared identifier 'valuesB'
    value_type *b_ew = valuesB.ptr_on_device();
                       ^
```
This tracks progress on https://github.com/kokkos/kokkos-kernels/issues/135 .

@trilinos/kokkos-kernels 

## Expectations

Trilinos needs to build correctly when the MKL TPL is enabled.

## Motivation and Context

MKL provides many useful computational kernels, but we can't use them in Trilinos if Trilinos won't build.

**Comment by mhoemmen** [comment]
@mndevec What commit fixed this?

**Comment by mndevec** [comment]
@mhoemmen ,
This should be fixed with below two commits: 

https://github.com/trilinos/Trilinos/commit/6ab30362499394c06a019be52ee6a243a379dd35
https://github.com/trilinos/Trilinos/commit/00358dc5852542bb64ec261e84d5d7df8b480f25

**Comment by mhoemmen** [comment]
@mndevec Thanks!  (FYI it's nice to put issue tracking numbers in commits)
