### ISSUE TITLE
Efficient concatenation of vectors in Tpetra

### ISSUE THREAD

**Issue by khpierson** [trilinos/Trilinos#2117]
Hi,

I have been finding and removing inefficient standard library patterns from SIERRA and wanted to mention one pattern that exists within Tpetra. 

Given 2 standard vectors sameGIDs1 and unionTgtGIDs:
**std::copy (sameGIDs1.begin (), sameGIDs1.end (), std::back_inserter (unionTgtGIDs));**
is equivalent to the more efficient insert method:
**unionTgtGIDs.insert( unionTgtGIDs.end(), sameGIDs1.begin (), sameGIDs1.end ());**
The second method can determine the amount of memory required and allocate it once vs. the first method with back_inserter has to use push_back and possibly multiple allocations.

I've included the list below and I would be happy to provide a patch if it helps,

Thanks,
-Kendall Pierson
khpiers@sandia.gov

TPLs_src/Trilinos/packages/tpetra/core/src/Tpetra_Import_def.hpp:      std::copy (sameGIDs1.begin (), sameGIDs1.end (), std::back_inserter (unionTgtGIDs));
TPLs_src/Trilinos/packages/tpetra/core/src/Tpetra_Import_def.hpp:      std::copy (sameGIDs2.begin (), sameGIDs2.end (), std::back_inserter (unionTgtGIDs));
TPLs_src/Trilinos/packages/tpetra/core/src/Tpetra_MultiVectorFiller.hpp:      std::copy (rows.begin(), rows.end(), std::back_inserter (sourceIndices_[column]));
TPLs_src/Trilinos/packages/tpetra/core/src/Tpetra_MultiVectorFiller.hpp:      std::copy (values.begin(), values.end(), std::back_inserter (sourceValues_[column]));
TPLs_src/Trilinos/packages/tpetra/core/src/Tpetra_MultiVectorFiller.hpp:        std::copy (rowIter, rowIterNext, std::back_inserter (sourceIndices_[j]));
TPLs_src/Trilinos/packages/tpetra/core/src/Tpetra_MultiVectorFiller.hpp:        std::copy (valIter, valIterNext, std::back_inserter (sourceValues_[j]));
TPLs_src/Trilinos_flat_headers/include/Tpetra_Import_def.hpp:      std::copy (sameGIDs1.begin (), sameGIDs1.end (), std::back_inserter (unionTgtGIDs));
TPLs_src/Trilinos_flat_headers/include/Tpetra_Import_def.hpp:      std::copy (sameGIDs2.begin (), sameGIDs2.end (), std::back_inserter (unionTgtGIDs));
TPLs_src/Trilinos_flat_headers/include/Tpetra_MultiVectorFiller.hpp:      std::copy (rows.begin(), rows.end(), std::back_inserter (sourceIndices_[column]));
TPLs_src/Trilinos_flat_headers/include/Tpetra_MultiVectorFiller.hpp:      std::copy (values.begin(), values.end(), std::back_inserter (sourceValues_[column]));
TPLs_src/Trilinos_flat_headers/include/Tpetra_MultiVectorFiller.hpp:        std::copy (rowIter, rowIterNext, std::back_inserter (sourceIndices_[j]));
TPLs_src/Trilinos_flat_headers/include/Tpetra_MultiVectorFiller.hpp:        std::copy (valIter, valIterNext, std::back_inserter (sourceValues_[j]));

@trilinos/<teamName>

## Your Environment

- **Relevant repo SHA1s:**  
- **Relevant configure flags or configure script:**  
- **Operating system and version:**  
- **Compiler and TPL versions:**  

## Related Issues

* Blocks 
* Is blocked by 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of

**Comment by jhux2** [comment]
@trilinos/tpetra
@khpierson Thanks for reporting this!

**Comment by mhoemmen** [comment]
@khpierson Thanks! :-D  btw we're planning to thread-parallelize Import setUnion, because @jjellio and @csiefer2 report that it's the next sequential bottleneck in sparse matrix-matrix multiply.  This means that we'll revisit that code soon.  We should still take the easy optimization for now, though!

**Comment by mhoemmen** [comment]
@tjfulle

**Comment by mhoemmen** [comment]
@khpierson I just had a chat with @tjfulle ; he has good ideas about how to simplify this code while at the same time improving performance.  This would also address the issue you pointed out.  Thanks!

**Comment by mhoemmen** [comment]
@khpierson One more question: How do you feel about the following pattern?
```
std::vector<int> output;
output.reserve (upperBound);
std::copy (input.begin (), input.end (), std::back_inserter (output));
```
We use that in Tpetra (including in the code you found), because it means that `output.size()` always returns the correct value.  The only trouble is that this pattern triggers (as a false positive, I suspect) your pattern-matching script.

**Comment by khpierson** [comment]
Mark,
That's a good solution as well and I'm fine with that to close out this issue.
-Kendall

**Comment by mhoemmen** [comment]
@khpierson MultiVectorFiller will likely go away at some point.  I can explain why offline.  Thanks so much for looking into this! :-D
