### ISSUE TITLE
KOKKOS_ARCH is not taken when I recompile after cmake file is touched in Trilinos.

### ISSUE THREAD

**Issue by kyungjoo-kim** [trilinos/Trilinos#2124]
## Summary of the problem
I configured the Trilinos with KOKKOS_ARCH and the setting is recorded in CMakeCache.txt, e.g.,
```
KOKKOS_ARCH:STRING=Power8,Pascal60
```
The code is compiled. Next if I changed a cmake file and typed ``make`` again, I would get the following error.
```
-- NOT using the legacy tribits build because KOKKOS_ARCH *is* set
CMake Error at packages/kokkos/cmake/kokkos_settings.cmake:20 (message):
  Power8,Pascal60 is not an accepted value for KOKKOS_ARCH.  Please pick from
  these choices: None
```

## Expectation
Before KOKKOS_ARCH update, cmake configure is automatically invoked if I touched a cmake file in Trilinos. Now I have to manually delete cmake files in the build directory and reconfigure myself.

## How to reproduce
1. You can start the problem with any configuration with setting KOKKOS_ARCH. 
2. Then change (or touch) any cmake file with an empty line.  
3. Type ``make`` in the build directory and you can see what I see.

**Comment by ibaned** [comment]
@crtrott @bartlettroscoe

**Comment by ibaned** [comment]
@kyungjoo-kim I confirmed this issue and put some fixes in this Kokkos pull request: kokkos/kokkos#1361

**Comment by ibaned** [comment]
That PR was merged, so this should be fixed once the next Kokkos snapshot is in, currently planned for the mid to late February.
