### ISSUE TITLE
Trilinos build error with OpenMP and CUDA KokkosNode

### ISSUE THREAD

**Issue by ikalash** [trilinos/Trilinos#2133]
The Albany nightly testing caught a build error in Trilinos starting last night with an OpenMP and CUDA KokkosNode:

/.../repos/Trilinos/packages/kokkos/core/unit_test/UnitTest_PushFinalizeHook.cpp(136): error: no operator "<<" matches these operands

Please see: http://cdash.sandia.gov/CDash-2-3-0/viewBuildError.php?buildid=65097 for more detailed output.

**Comment by mhoemmen** [comment]
@ikalash I'll take care of it -- thanks for pointing this out!

**Comment by ikalash** [comment]
Great, thanks @mhoemmen !

**Comment by mhoemmen** [comment]
@ikalash Some compilers implement ``operator<<(std::ostream&, const std::ostringstream&)`; others don't.  Oops ;-) .  I'm fixing it now.

**Comment by mhoemmen** [comment]
@ikalash Fixed in develop; thanks! :D

**Comment by mhoemmen** [comment]
This will also be fixed in Kokkos: https://github.com/kokkos/kokkos/pull/1325

**Comment by ikalash** [comment]
All is good in the Albany dashboard.  Thanks again for fixing it, @mhoemmen !

**Comment by mhoemmen** [comment]
Thanks for reporting @ikalash ! :D
