### ISSUE TITLE
Phalanx:  Evaluator Usage Script

### ISSUE THREAD

**Issue by jmgate** [trilinos/Trilinos#2134]
@trilinos/phalanx

## Expectations

It'd be great to have a script that could pull out and aggregate the Phalanx `Evaluator` usage from the `TimeMonitor` results we output in application code.  Some desired features:
- [x] Sort based on the number of calls.
- [x] Sort based on run time.
- [x] Aggregate results where the same `Evaluator` (e.g. `Constant`) is instantiated with different names.
- [x] Aggregate results for multiple evaluation types; that is, combine Residual, Jacobian, etc.
- [x] Also display and sort by total run time / number of calls.

## Current Behavior

No such script exists.

## Motivation and Context

We're trying to figure out a way to prioritize the refactoring of `Evaluator`s, and such summary statistics could be useful in that prioritization.

## Related Issues

* Related to #1575

**Comment by jmgate** [comment]
And is there any additional functionality that might be useful to you?

**Comment by rppawlo** [comment]
Probably not anymore. I just recently added the printing of the evaluation type, the "[panzer::Traits::Residual]", to phalanx. Prior to December, it was up to the user to differentiate the evaluation type. That's why that string is tacked onto the end of many evaluators.

**Comment by jmgate** [comment]
Ah, so as we work on refactoring `Evaluator`s, it's safe to remove that `typeAsString` from the name?

**Comment by rppawlo** [comment]
> Ah, so as we work on refactoring Evaluators, it's safe to remove that typeAsString from the name?

yes

**Comment by jmgate** [comment]
The script now lives in `phalanx/scripts/evaluatorUsage`.
