### ISSUE TITLE
Tpetra: Tpetra::CrsGraph::computeLocalConstants is not threaded

### ISSUE THREAD

**Issue by csiefer2** [trilinos/Trilinos#2144]
And yes, it does take a "real" amount of time (since it loops over the entire matrix) as demonstrated by James' data.

The code is under a page long and I suspect could be turned into a Kokkos::parallel_reduce with only a little bit of effort (note: a custom join will likely be needed).

@tjfulle @mhoemmen @jjellio @jhux2

**Comment by mhoemmen** [comment]
@csiefer2 would you consider lazy evaluation of these instead, esp. if we go to lazy evaluation + collective semantics for `getGlobalNum*`?

**Comment by csiefer2** [comment]
I'd rather not.  nodeMaxNumRowEntries is actually pretty important.

You could lazy the triangular guys if you'd like, however.

**Comment by mhoemmen** [comment]
@csiefer2 wrote:
> nodeMaxNumRowEntries is actually pretty important.

What if it were computed lazily and cached?  Would that be bad?

**Comment by csiefer2** [comment]
Probably not.  But is there a compelling reason to make this lazy?

I mean, there's no communication in this routine.

**Comment by mhoemmen** [comment]
@csiefer2 Computing it from user input requires a Kokkos::parallel_reduce, possibly on GPU.

**Comment by csiefer2** [comment]
So?  I was under the impression that parallel_reduce was pretty speedy.

(Also, you don't need to @csiefer2 me more than once --- I get email notifications after the first one)

**Comment by mhoemmen** [comment]
> So? I was under the impression that parallel_reduce was pretty speedy.

Latency for GPU kernel launch is O(1) microseconds, maybe better now but still not trivial.

**Comment by mhoemmen** [comment]
PR #2696, once merged, will fix this, via the new `Tpetra::Details::determineLocalTriangularConstants` function.

**Comment by mhoemmen** [comment]
I merged #2696.  That fixes this issue in develop.
