### ISSUE TITLE
ROL_ScaledThyraVector.hpp is missing from CMakeLists.txt

### ISSUE THREAD

**Issue by etphipp** [trilinos/Trilinos#2145]
ROL_ScaledThyraVector.hpp is missing from rol/adapters/thyra/src/CMakeLists.txt and hence is not installed during 'make install'.  

@trilinos/rol

**Comment by etphipp** [comment]
It would be idea if this could be fixed quickly.

**Comment by dridzal** [comment]
We have an unrelated bug in the private ROL repo that is preventing us from pushing into the Trilinos repo.  I may have to disable the test exhibiting this bug, and fix rol/adapters/thyra/src/CMakeLists.txt.  Stay tuned.

**Comment by etphipp** [comment]
Denis told me to push the change to Trilinos, which I just did.  Hopefully it won't be lost when ROL in Trilinos is updated.
