### ISSUE TITLE
Teuchos:  TimeMonitor Aggregator?

### ISSUE THREAD

**Issue by jmgate** [trilinos/Trilinos#2159]
@trilinos/teuchos 

## Question
I recently wrote this [evaluatorUsage](https://github.com/trilinos/Trilinos/blob/develop/packages/phalanx/scripts/evaluatorUsage) script to scrub the TimeMonitor results from an application run (or a bunch of app runs via `ctest`), grab the lines pertaining to Phalanx `Evaluator`s, aggregate the number of calls and run time, and output a list sorted by either the total number of calls, total run time, or average run time per call.  Right now this script is specific to Phalanx `Evaluator`s, but is there any use for it from a general `Teuchos::TimeMonitor` perspective?  Generalizing it would be straightforward enough, but if there's not really a use case for it outside what we wanted to do with Phalanx, I won't bother.

## Motivation and Context
Basically we wanted some means of quantifying which `Evaluator`s were most significant when deciding which ones should be refactored first to clean things up in terms of run time and memory usage.  Such a script may have more general profiling use to the Trilinos community, but I figured somebody from Teuchos would know better than I.

## Sample Output
[panzerEvaluatorUsage.txt](https://github.com/trilinos/Trilinos/files/1633088/panzerEvaluatorUsage.txt)
```
Avg. Time    │ Total        │ Total #  │ 
per Call     │ Run Time     │ of Calls │ Evaluator Name
━━━━━━━━━━━━━┿━━━━━━━━━━━━━━┿━━━━━━━━━━┿━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
8.556789e-03 │ 1.625790e-01 │       19 │ [panzer::Traits::Jacobian] Integrator_DivBasisTimesScalar
5.722842e-03 │ 5.436700e-02 │        9 │ [panzer::Traits::Jacobian] DOFDiv
1.083474e-03 │ 1.029300e-02 │        9 │ [panzer::Traits::Jacobian] Sine Source
7.913750e-04 │ 6.331000e-03 │        8 │ [panzer::Traits::Jacobian] PointValues_Evaluator
7.885750e-04 │ 6.308600e-03 │        8 │ [panzer::Traits::Jacobian] BasisValues_Evaluator
3.712769e-04 │ 3.861280e-02 │      104 │ [panzer::Traits::Jacobian] Integrator_BasisTimesVector (Eval, panzer::Traits::Jacobian)
2.578115e-04 │ 1.340620e-02 │       52 │ [panzer::Traits::Jacobian] Integrator_CurlBasisDotVector
2.274519e-04 │ 1.182750e-02 │       52 │ [panzer::Traits::Jacobian] DOFCurl
1.789368e-04 │ 1.699900e-03 │        9 │ [panzer::Traits::Jacobian] SCATTER_PHI Scatter Residual (Jacobian)
1.784000e-04 │ 1.784000e-04 │        1 │ [panzer::Traits::Jacobian] Normals
1.489500e-04 │ 2.979000e-04 │        2 │ [panzer::Traits::Residual] Normals
1.229368e-04 │ 1.167900e-03 │        9 │ [panzer::Traits::Jacobian] SCATTER_GRADPHI_FIELD Scatter Residual (Jacobian)
1.114288e-04 │ 8.914300e-04 │        8 │ [panzer::Traits::Jacobian] DOF_PointValues
9.849231e-05 │ 5.121600e-03 │       52 │ [panzer::Traits::Jacobian] Simple Source
9.207500e-05 │ 1.841500e-03 │       20 │ [panzer::Traits::Jacobian] SCATTER_U Scatter Residual Epetra (Jacobian)
7.169100e-05 │ 2.867640e-02 │      400 │ [panzer::Traits::Jacobian] SCATTER_TEST_TEMPERATURE Scatter Residual (Jacobian)
6.219875e-05 │ 4.975900e-04 │        8 │ [panzer::Traits::Jacobian] Dirichlet Residual Edge Basis Evaluator
4.994500e-05 │ 4.994500e-04 │       10 │ [panzer::Traits::Jacobian] Dummy Scatter
```

## Definition of Done
- [ ] Let me know if a general TimeMonitor aggregation script is useful to the Trilinos community.
- [ ] If so, I'll generalize the Phalanx one.
- [ ] Then we can all do a little happy dance.

## Related Issues
* Related to #2134

**Comment by mhoemmen** [comment]
@jmgate `Teuchos::TimeMonitor` output has some options to filter based on an initial string.  Would this be useful?  See https://github.com/trilinos/Trilinos/blob/master/packages/teuchos/comm/src/Teuchos_TimeMonitor.hpp and grep for "filter".

**Comment by jhux2** [comment]
@jmgate FYI, @jjellio has been developing scripts to post-process and plot timer data.  You may want to touch base with him.
