### ISSUE TITLE
Unable to Specify --map-by numa:PE=4 in Trilinos Configuration for MPI Tests

### ISSUE THREAD

**Issue by nmhamster** [trilinos/Trilinos#216]
@bartlettroscoe I have been specifying `-D MPI_EXEC_POST_NUMPROCS_FLAGS:STRING="--map-by numa:PE=4"` in my Trilinos configuration but it appears that this is being passed to `mpirun` or `mpiexec` as a single argument (i.e. not two arguments).

I'd like to be able to run the Trilinos test in a sensible binding mode for OpenMP on `hansen`, `shiller` and `shepard`. 

So far I have backed off to `--bind-to-socket` (a single argument) but it would be better to not have MPI ranks conflicting if we can avoid that (and use the true mapping option).

**Comment by etphipp** [comment]
Did you try this:

-D MPI_EXEC_POST_NUMPROCS_FLAGS:STRING="--map-by;numa:PE=4"

i.e., use a ; instead of a space?  CMake separates multiple arguments with a ;.

-Eric

**Comment by bartlettroscoe** [comment]
Eric is correct.  See:

https://trilinos.org/docs/files/TrilinosBuildReference.html#configuring-with-mpi-support

which states:

```
-D MPI_EXEC_POST_NUMPROCS_FLAGS="arg1;arg2;...;argn"
```

**Comment by bartlettroscoe** [comment]
Si, I am assigning this back to you to try:

```
-D MPI_EXEC_POST_NUMPROCS_FLAGS:STRING="--map-by;numa:PE=4"
```

**Comment by nmhamster** [comment]
Works for me. Thanks for the info.
