### ISSUE TITLE
Tpetra: OpenMP tests broken / Albany Cuda Tests Broken

### ISSUE THREAD

**Issue by cgcgcg** [trilinos/Trilinos#2161]
It seems that 92da795247f88f116b97a48441c018053abe0eca broke the MueLu OpenMP tests:
https://testing.sandia.gov/cdash/index.php?project=Trilinos&date=2018-01-16&subproject=MueLu

@trilinos/tpetra 

@csiefer2 is on travel. Were you involved in this, @tjfulle , and able to easily fix this?

**Comment by ikalash** [comment]
It's possible this issue is being manifested in the following Albany issue that shows up with MueLu and OpenMP or CUDA KokkosNode: 

https://github.com/gahansen/Albany/issues/245

**Comment by mhoemmen** [comment]
@ikalash -- @mndevec might have been involved a bit, but I think @csiefer2 did the Tpetra work.  We can revert this if it's urgent.

**Comment by mhoemmen** [comment]
@kddevin See this and also https://github.com/NaluCFD/Nalu/issues/294

**Comment by kddevin** [comment]
@csiefer2 is on business travel with meetings all day; perhaps he'll be able to comment tonight.
@ikalash , @cgcgcg :  I see you are both experiencing runtime errors.  How urgent is getting a fix or reversion in place?  Can it wait until @csiefer2 returns next week?
Thanks, all!

**Comment by ikalash** [comment]
@mhoemmen : it is not super urgent, but we are striving for a clean Albany dashboard for the purpose of automatically promoting certain branches, so it would be great to have this fixed soon (this week?).

**Comment by ibaned** [comment]
I vote for reverting this. I'm trying to carefully monitor performance regression of Tpetra+Kokkos operations, and I don't feel comfortable doing that with incorrect code under the hood.

**Comment by bathmatt** [comment]
I started seeing issue today with openmp on my code as well. well last night actually, Looks like it is this.  I vor for a revert as well.

**Comment by kddevin** [comment]
Thanks, @ikalash and @ibaned.
I'd like to give @csiefer2 a chance to comment before deciding.  
Perhaps he'll know what the problem is, and we'll save the noise of a reversion.

**Comment by bathmatt** [comment]
I confirmed that this checkin broke EMPIRE as well, I would say since we don't have testing in place insulating us from broken trilinos issues that we revert by COB today since it is easy to revert a revert and fix.

**Comment by bathmatt** [comment]
If I don't hear otherwise in the next few minutes I'm going to push a revert so we can have it working for folks tomorrow on our systems.

**Comment by bathmatt** [comment]
dir-Trilinos (gcc) 4 $ git log
commit d86ccdc8c4148776c46a2bcaf1c502c275b4a6c7
Author: Matt Bettencourt <mbetten@sandia.gov>
Date:   Tue Jan 16 15:10:37 2018 -0700

    Revert "Tpetra: Abstracting out the matrix merge functionality needed for interfacing to KokkosKernels"
    
    This reverts commit 92da795247f88f116b97a48441c018053abe0eca.

**Comment by mhoemmen** [comment]
Thanks @bathmatt !

**Comment by bathmatt** [comment]
BTW, There was an error I was seeing with the serial backend, memory corruption, which also went away with this revert.  Can we make sure we look beyond the threaded versions on this?

@mhoemmen  your bug name says causing diffs, is this openmp/cuda or serial?

**Comment by ikalash** [comment]
On the Albany side, it looks like everything is good with OpenMP but there is still a seg fault with a CUDA KokkosNode (for the same test using MueLu where we had OpenMP issues as well last night).  Here is the output: 

http://cdash.sandia.gov/CDash-2-3-0/testDetails.php?test=3406666&build=65637

The analog of this issue in Albany can be found here: https://github.com/gahansen/Albany/issues/245

**Comment by mhoemmen** [comment]
@bathmatt I didn't name the bug, but see this comment: https://github.com/NaluCFD/Nalu/issues/294#issuecomment-356659602

**Comment by csiefer2** [comment]
This issue is separate from the Nalu one.  That one has to do with switching kernels, this one is related to a code cleanup checkin.

I'll get a build started to try to figure out what is wrong.

**Comment by ikalash** [comment]
@csiefer2 : let me know if you'd like me to test things on the Albany side.

**Comment by csiefer2** [comment]
Seems to be an incorrect use of RCPs on my part.  Code passes MueLu unit tests on OpenMP & CUDA (the problematic SchurComplementFactory aside).

Checkin script is running.

**Comment by mhoemmen** [comment]
@csiefer2 thanks for working on this! :D

**Comment by ikalash** [comment]
@csiefer2 : I just tested Albany on Ride with an up-to-date develop branch of Trilinos, and unfortunately the same test still fails.  There is also now another MueLu test that has a seg fault.  You will find the verbose output here:

http://cdash.sandia.gov/CDash-2-3-0/viewTest.php?onlyfailed&buildid=65703

**Comment by csiefer2** [comment]
Yeah, that's Matrix-Matrix related   Sadly, the MueLu tests all pass w/ Cuda, so I need to get a Cuda build of Albany started.  @ikalash Can you send me Albany's module list for ride?

**Comment by ikalash** [comment]
@csiefer2 : you will find them here https://github.com/gahansen/Albany/blob/master/doc/dashboards/ride.sandia.gov/ride_modules_cuda.sh .  The Trilinos and Albany configure options can be found here: https://github.com/gahansen/Albany/blob/master/doc/dashboards/ride.sandia.gov/ctest_nightly.cmake.frag .  The tests run in the rhel7G queue.  

P.S. I'm actually visiting CSRI next week, so we could talk in person about this then.  I'll be sitting in CSRI/144.

**Comment by csiefer2** [comment]
I just pushed a GCC 7.2.0-specific workaround into the code, switching the code path to make the troublesome error disappear (at least in the Trilinos tests).

This does *not* address the Albany issue.

**Comment by cgcgcg** [comment]
Seems to be all fixed.

**Comment by csiefer2** [comment]
This issue is suppressed via a change in code path.  The underling problem is still in the code (if you use the right options).

**Comment by ikalash** [comment]
Any progress on this issue, @csiefer2 ?

**Comment by mhoemmen** [comment]
@ikalash I think what @csiefer2 meant, is that the tests are now passing.  The code that appears to be causing the issue no longer builds by default.  He kept the issue open because he wants to fix that code, but the tests are now passing.

A couple Tpetra tests are timing out, but this is because the platform running them is configured incorrectly.  See, for example, https://testing.sandia.gov/cdash/testDetails.php?test=44513422&build=3375788 

```
0. Tpetra_MatMat_double_int_int_Kokkos_Compat_KokkosOpenMPWrapperNode_operations_test_UnitTest ... Teuchos::GlobalMPISession::GlobalMPISession(): started processor with name ascic157 and rank 1!
Teuchos::GlobalMPISession::GlobalMPISession(): started processor with name ascic157 and rank 2!
Tpetra sparse matrix-matrix multiply: operations_test
 Get parameters from XML file
Kokkos::OpenMP::initialize WARNING: You are likely oversubscribing your CPU cores.
                                    Detected: 88 cores per node.
                                    Detected: 4 MPI_ranks per node.
                                    Requested: 44 threads per process.
Kokkos::OpenMP::initialize WARNING: You are likely oversubscribing your CPU cores.
                                    Detected: 88 cores per node.
                                    Detected: 4 MPI_ranks per node.
                                    Requested: 44 threads per process.
Kokkos::OpenMP::initialize WARNING: You are likely oversubscribing your CPU cores.
                                    Detected: 88 cores per node.
                                    Detected: 4 MPI_ranks per node.
                                    Requested: 44 threads per process.
Kokkos::OpenMP::initialize WARNING: You are likely oversubscribing your CPU cores.
                                    Detected: 88 cores per node.
                                    Detected: 4 MPI_ranks per node.
                                    Requested: 44 threads per process.
```

**Comment by ikalash** [comment]
@mhoemmen : I was actually referring to the status of this Albany issue which currently only occurs with CUDA https://github.com/gahansen/Albany/issues/245 .  Perhaps this Trilinos one is not the right one to comment on, my apologies.

**Comment by mhoemmen** [comment]
@ikalash No worries!

**Comment by csiefer2** [comment]
@ikalash Let's keep this issue as the canonical place for GCC 7.2.0/OpenMP / Albany Cuda wonkyness.

**Comment by ikalash** [comment]
Ok, sounds good.  Any progress on the issue?

**Comment by csiefer2** [comment]
Not really.  The inability of debugging tools to function correctly has hampered progress.

**Comment by crtrott** [comment]
I opened an issue on this #2331. I will fix the CUDA issue. It actually makes Tpetra Unit tests fail ..

**Comment by ikalash** [comment]
@crtrott, @csiefer2: Christian, I think you fixed the tests in Albany finally with your commit!  Thanks!!
