### ISSUE TITLE
syntax error in Ifpack_SPARSKIT.cpp ?

### ISSUE THREAD

**Issue by SilverLinings89** [trilinos/Trilinos#2167]
I tried building Trilinos with Sparskit support and got the error 

> trilinos-12.4.2-Source/packages/ifpack/src/Ifpack_SPARSKIT.cpp:315:11: error: ‘endl’ was not declared in this scope

I checked the source and it is still this way in the latest version. simply putting either using namespace std or std::endl for all cases fixes this. Building seems to work now.
 

@trilinos/ifpack

## Current Behavior

Build aborts.

## Possible Solution

I checked the source and it is still this way in the latest version. simply putting either using namespace std or std::endl for all cases fixes this. Building seems to work now.

## Steps to Reproduce

I dont actually have a lot of experience with this library and I don't know if this is an unusual case because in other cases some file would be loaded that sets the namespace, but in my case it happened.

## Your Environment

- Ubuntu 16.04
- Gnu

**Comment by jhux2** [comment]
@SilverLinings89 I've pushed a patch to the develop branch. Please try it out and let me know if it fixes the issue you reported.
