### ISSUE TITLE
ROL_Ptr.hpp std::is_pointer compile error

### ISSUE THREAD

**Issue by ibaned** [trilinos/Trilinos#2175]
@trilinos/rol
@trilinos/phalanx 

## Expectations

ROL headers should not cause compile errors when included in applications such as Albany.

## Current Behavior

Building Albany gives the following compile error from `ROL_Ptr.hpp`:
```
build/TrilinosInstall/include/ROL_Ptr.hpp:71:8: error: partial specialization of 'struct std::is_pointer <Teuchos::RCP<PHX::DataLayout>>' after instantiation of 'struct std::is_pointer Teuchos::RCP<PHX::DataLayout>>' [-fpermissive]
```
https://my.cdash.org/viewBuildError.php?buildid=1353633

## Motivation and Context

Albany cannot be compiled due to this error, including for nightly testing.

## Definition of Done

This compile error should be fixed

**Comment by ibaned** [comment]
The code in question:
```cpp
namespace std {

template<class T>
struct is_pointer<ROL::Ptr<T>> : public std::true_type { };

}
```
In general, I think specializing `std::is_pointer` is bad design. Why not just define `ROL::is_pointer`? We wouldn't want to break downstream code that assumes normal behavior of `std::is_pointer`. Note that `std::is_pointer` isn't even true for `std::shared_ptr` and others, so this really changes its meaning too much.

**Comment by ibaned** [comment]
It looks like this has nothing to do with Phalanx, sorry for spamming the Phalanx team.

**Comment by dridzal** [comment]
I absolutely agree with @ibaned .  @gregvw , could you please comment on this?  This is somewhat urgent.

**Comment by gregvw** [comment]
This is vestigial code from initial experimentation that slipped through the cracks and needs to be removed. Pushed fix

**Comment by ibaned** [comment]
@gregvw Thank you!
I don't see a commit in the Trilinos master branch though.
Does ROL live in a separate repository and get snapshotted into Trilinos?

**Comment by dridzal** [comment]
ROL is in a separate repo, HOWEVER it is not snapshotted, it is merged.  I was about to start a test cycle to sync and merge. @ibaned , Is it safe to do so, or have you already pushed a fix in the Trilinos repo?  This would cause a merge conflict.

**Comment by ibaned** [comment]
@dridzal I didn't push anything directly, I just opened PR #2177. If you're going to do a test/sync/merge, then lets just ignore that PR and we should be fine.

**Comment by dridzal** [comment]
Sounds good.  I’ll start the process.

**Comment by dridzal** [comment]
The fix by @gregvw should be in.  Please let us know if this takes care of the Albany issue.

**Comment by ibaned** [comment]
@dridzal @gregvw thank you, Albany seems to be compiling again
