### ISSUE TITLE
MueLu: Build error in research code

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#2181]
https://testing.sandia.gov/cdash/viewBuildError.php?buildid=3345116

@trilinos/muelu

**Comment by lucbv** [comment]
@mhoemmen  I pushed something around the time you submitted this issue, can you check and see if things are building correctly for you now?

**Comment by lucbv** [comment]
@mhoemmen the dashboard looks clean this morning so I will close this issue, thanks for letting us know!

**Comment by mhoemmen** [comment]
Thanks @lucbv !
