### ISSUE TITLE
Panzer scatter residual not parallel_for-ish

### ISSUE THREAD

**Issue by bathmatt** [trilinos/Trilinos#2182]
The scatter jacobian uses a parallel for, but not the resid or tangent, can we look into fixing this?  I can try to do this soon but if anyone else is working on this that would be great, @rppawlo @jmgate ??

**Comment by bathmatt** [comment]
BTW, is this well tested so if I do "fix" it I know I don't break it??

**Comment by bathmatt** [comment]
Same thing for the gather operation...

**Comment by jmgate** [comment]
`parallel_for`ing all of Panzer's `Evaluator`s is part of planned, ongoing work, but there's no telling when I'll get to the ones you care about.  Top priority are the integrators, followed by the gathers/scatters.  [This](https://github.com/trilinos/Trilinos/blob/master/packages/panzer/disc-fe/src/evaluators/Panzer_Integrator_BasisTimesScalar_impl.hpp) is an example of one that's already been updated, in case you want to tackle some yourself.  There should be plenty of testing in place to catch when you break something.

**Comment by rppawlo** [comment]
@bathmatt I assume you want Tpetra scatters - do you want both regular and Blocked? Probably not Hessians? What is the time frame you need this by?

**Comment by bathmatt** [comment]
I pushed a branch, making a MR
