### ISSUE TITLE
Muelu/XPetra Test Link Failure

### ISSUE THREAD

**Issue by nmhamster** [trilinos/Trilinos#2183]
@trilinos/muelu - any ideas on this one? Its Trilinos VOTD compiled using GCC 7.2.0.

```
CMakeFiles/MueLu_Driver.dir/Driver.cpp.o: In function `Xpetra::EpetraOperator<long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::getDomainMap() const':
/ascldap/users/sdhammo/git/trilinos-github-repo/packages/xpetra/src/Operator/Xpetra_EpetraOperator.hpp:77: undefined reference to `Teuchos::RCP<Xpetra::Map<int, long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > const> const Xpetra::toXpetra<long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >(Epetra_BlockMap const&)'
CMakeFiles/MueLu_Driver.dir/Driver.cpp.o: In function `Xpetra::EpetraOperator<long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::getRangeMap() const':
Driver.cpp:(.text._ZNK6Xpetra14EpetraOperatorIlN6Kokkos6Compat23KokkosDeviceWrapperNodeINS1_6SerialENS1_9HostSpaceEEEE11getRangeMapEv[_ZNK6Xpetra14EpetraOperatorIlN6Kokkos6Compat23KokkosDeviceWrapperNodeINS1_6SerialENS1_9HostSpaceEEEE11getRangeMapEv]+0x44): undefined reference to `Teuchos::RCP<Xpetra::Map<int, long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > const> const Xpetra::toXpetra<long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >(Epetra_BlockMap const&)'
collect2: error: ld returned 1 exit status
make[2]: *** [packages/muelu/test/scaling/MueLu_Driver.exe] Error 1
make[1]: *** [packages/muelu/test/scaling/CMakeFiles/MueLu_Driver.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

**Comment by lucbv** [comment]
@nmhamster I have been looking into it a bit yesterday, this looks like it could be related to a missing specialization? I will put some more time into it today, this have been crashing my clang nightly build and the CUDA kokkos refactor nightly build for sometime...

**Comment by nmhamster** [comment]
@lucbv - thank you for the speedy response. Its killing my apps bring up on some new machines so I'm going to revert back for a few days. If you can let me know when I should test again, I'd be happy to kick the tires. 👍

**Comment by lucbv** [comment]
@nmhamster can you give it a try now? This last commit should have fixed things.

**Comment by nmhamster** [comment]
@lucbv - compiled for me. Thank you!

**Comment by nmhamster** [comment]
@lucbv / @trilinos/muelu - will close this issue. I appreciate your very quick response and fixes guys. Thank you.

**Comment by cgcgcg** [comment]
@luc Is this build error related: https://testing.sandia.gov/cdash/viewBuildError.php?buildid=3351042 ? Looks like there might be some other instantiation issues in that file..

**Comment by lucbv** [comment]
@cgcgcg  Yes that is a possibility, I did not do a CUDA build yesterday for sake of time but I will look at it and hopefully find why this one is different?

**Comment by cgcgcg** [comment]
Oh, I think that might have been failing for a while, but I figured since you fixed the other one already ;-)
