### ISSUE TITLE
Compilation error for missing operator >=  for Kokkos_Views when called by Tpetra_MultiVector

### ISSUE THREAD

**Issue by mperego** [trilinos/Trilinos#219]
It's probably related with new Kokkos Views. See my configuration script and error that I get.

Thanks!

Mauro

[do-trilinos-experimental.txt](https://github.com/trilinos/Trilinos/files/176892/do-trilinos-experimental.txt)
[error.txt](https://github.com/trilinos/Trilinos/files/176893/error.txt)

**Comment by hcedwar** [comment]
the erroroneous statement
 `if (src.getDualView ().modified_device >= src.getDualView ().modified_host) {`
should be
 `if (src.getDualView ().modified_device() >= src.getDualView ().modified_host() ) {`

**Comment by mperego** [comment]
Thanks! I'm testing this now, then I'll commit the change.

**Comment by mperego** [comment]
Bug fixed. Thanks again.
Mauro
