### ISSUE TITLE
Can't clone from 'nightly' Trilinos repo on SON Jenkins build farm

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#2190]
**CC:** @trilinos/framework, @jwillenbring, @bmpersc 

## Description

As described in more detail in:

* https://software-sandbox.sandia.gov/jira/browse/TRIL-171

It seems that jobs submitted to the SON Jenkins build farm from the site `jenkins-son.sandia.gov` cannot clone from the repo `software.sandia.gov:/space/git/nightly/Trilinos`.  There are no Trilinos jobs running from Jenkins site that clone from `software.sandia.gov:/space/git/nightly/Trilinos`, they all clone from this GitHub site (see https://software-sandbox.sandia.gov/jira/browse/TRIL-171?focusedCommentId=19762&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-19762).

Could the problem be that the entity account 'jenkins' has not been given access to the Trilinos repo on SSG as per:

* https://sems.sandia.gov/confluence/display/SEMSKB/Jenkins%3A+Setting+up+repository+access+in+a+job

?

Note that once you are running in a script that that process can't clone either (as I showed in the experiment documented in https://software-sandbox.sandia.gov/jira/browse/TRIL-171?focusedCommentId=19778&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-19778).

## Defintion of Done

* The outer Jenkins process and the inner script (i.e. ctest- S script) can clone from `software.sandia.gov:/space/git/nightly/Trilinos`

**Comment by jwillenbring** [comment]
@bartlettroscoe Please see the job https://jenkins-son.sandia.gov/view/Trilinos/job/trilinos_clone_example/ for an example clone on the SON. The job configuration outside of the clone isn't relevant, so please ignore.

Thanks to @bmpersc for supplying this example.

**Comment by bartlettroscoe** [comment]
Okay, I see that the outer Jenkins clone set the "Credential" as "jenkins (Jenkins-SON SSH Master)".   I modified this job to clone Trilinos again on the inner job and that seemed to work as well.  I will give that a try.

**Comment by bartlettroscoe** [comment]
Going to remove the "ATDM" label from this since we are getting by with cloning from github for now.

**Comment by bartlettroscoe** [comment]
> @bartlettroscoe Is this an issue that can be closed?

@jwillenbring, yea, we can close this.  Cloning/updating directly from the main GitHub repo has been pretty robust in that ATDM Trilinos nightly builds.  To make sure we are testing the same version each day, we will just add an 'atdm-nightly' branch and then update that every day at the same time and then all of the ATDM Trilinos nightly builds will pull from that each day.
