### ISSUE TITLE
Build error on Ride + CUDA Kokkos node due to issues in TpetraExt_MatrixMatrix_ExtraKernels_def.hpp

### ISSUE THREAD

**Issue by ikalash** [trilinos/Trilinos#2193]
The Albany CUDA build failed last night due to issues in TpetraExt_MatrixMatrix_ExtraKernels_def.hpp :  

http://cdash.sandia.gov/CDash-2-3-0/viewBuildError.php?buildid=66026

```
/.../repos/Trilinos/packages/tpetra/core/ext/TpetraExt_MatrixMatrix_ExtraKernels_def.hpp(979): error: no instance of overloaded function "Tpetra::MatrixMatrix::add" matches the argument list
```

Can someone please look into and resolve the problem? 

@trilinos/tpetra

**Comment by mhoemmen** [comment]
@csiefer2

**Comment by mhoemmen** [comment]
See also https://github.com/trilinos/Trilinos/issues/2183#issuecomment-360855119 .
@lucbv

**Comment by csiefer2** [comment]
Weird. It built on white and artemis.

**Comment by ikalash** [comment]
It looks like there is now a compilation error having to do with TpetraExt_MatrixMatrix_ExtraKernels_def.hpp in the Albany OpenMP build on my workstation: 
```
/home/ikalash/nightlyAlbanyTests/Results/Trilinos/packages/tpetra/core/ext/TpetraExt_MatrixMatrix_ExtraKernels_def.hpp:979:28: error: no matching function for call to ‘add(Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 4, Kokkos::OpenMP> >&, bool, const Tpetra::CrsMatrix<Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 4, Kokkos::OpenMP> >, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP> >&, Sacado::MP::UnaryMinusOp<Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 4, Kokkos::OpenMP> > >, bool, Tpetra::CrsMatrix<Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 4, Kokkos::OpenMP> >, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP> >&, Tpetra::CrsMatrix<Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 4, Kokkos::OpenMP> >, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP> >&, Teuchos::RCP<const Tpetra::Map<int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP> > >, Teuchos::RCP<const Tpetra::Map<int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP> > >, const Teuchos::RCP<Teuchos::ParameterList>&)’
   Tpetra::MatrixMatrix::add(one,false,*Bview.origMatrix,-omega,false,*AB,C,AB->getDomainMap(),AB->getRangeMap(),params);
```

**Comment by mhoemmen** [comment]
@ikalash @csiefer2 @etphipp Looks like we need to add a new instantiation for that Sacado type to Stokhos (which is where all the instantiations go).  Let me see if I can figure it out now.

**Comment by mhoemmen** [comment]
Hm, TpetraExt_MatrixMatrix_ExtraKernels_def.hpp line 979 refers to one of the `Tpetra::MatrixMatrix::add` overloads that the `TPETRA_MATRIXMATRIX_INSTANT` macro includes:

https://github.com/trilinos/Trilinos/blob/a138b300a0e8273bd914be5f7d30629a0ca693e0/packages/tpetra/core/ext/TpetraExt_MatrixMatrix_def.hpp#L3809

I don't see that Trilinos uses that macro anywhere else:
```
$ git grep "TPETRA_MATRIXMATRIX_INSTANT" *
packages/tpetra/core/ext/TpetraExt_MatrixMatrix.cpp:  TPETRA_INSTANTIATE_SLGN(TPETRA_MATRIXMATRIX_INSTANT)
...
packages/tpetra/core/ext/TpetraExt_MatrixMatrix_def.hpp:#define TPETRA_MATRIXMATRIX_INSTANT(SCALAR,LO,GO,NODE) \
```
@ikalash , have you just started running Sacado types through MueLu?  Is that a new thing for Albany?

**Comment by ikalash** [comment]
@mhoemmen : if we have, I am not aware of it.  @ibaned may know more than me.

**Comment by csiefer2** [comment]
FYI - the magic stokhos rebase scripts don't seem to do anything for this (though it looks like someone missed the rebase stuff on BlackBox).  Will bug @etphipp

**Comment by etphipp** [comment]
Because of the way Tpetra::MatrixMatrix::add() is declared, you need to cast `-omega` to the right type, i.e., replace
```
Tpetra::MatrixMatrix::add(one,false,*Bview.origMatrix,-omega,false,*AB,C,AB->getDomainMap(),AB->getRangeMap(),params);
```
with
```
Tpetra::MatrixMatrix::add(one,false,*Bview.origMatrix,Scalar(-omega),false,*AB,C,AB->getDomainMap(),AB->getRangeMap(),params);
```

**Comment by csiefer2** [comment]
Checkin script baking on both this & blackbox fix.

**Comment by ibaned** [comment]
@csiefer2 you can put up pull requests and use the automatic pull request testing system if thats more convenient for you

**Comment by csiefer2** [comment]
That may be the first time I've heard "convenient" and "pull request" in the same sentence 😛

**Comment by csiefer2** [comment]
Pushed. @ikalash Feel free to close if Albany builds tonight

**Comment by ikalash** [comment]
Thanks, @csiefer2 !  I'll know by tomorrow morning if your fix solves the issues for Albany from the nightlies.

**Comment by mhoemmen** [comment]
Thanks @csiefer2 ! :D

**Comment by ikalash** [comment]
This issue is resolved - thanks for fixing it @csiefer2 !  There is still a MueLu + CUDA issue, though, namely https://github.com/trilinos/Trilinos/issues/2161 .
