### ISSUE TITLE
Tacho: Build failure in TachoExp_Blas_Team.hpp

### ISSUE THREAD

**Issue by ccober6** [trilinos/Trilinos#2195]
On my Mac, I am getting many failures like the following

/Users/ccober/myOffice/Trilinos/packages/shylu/shylu_node/tacho/src/TachoExp_Blas_Team.hpp:629:29: error: 
      default initialization of an object of const type 'const
      Tacho::Experimental::Conjugate' without a user-provided default
      constructor
            const Conjugate cjB;
                            ^
                               {}
/Users/ccober/myOffice/Trilinos/packages/shylu/shylu_node/tacho/src/TachoExp_Blas_Team.hpp:643:29: error: 
      default initialization of an object of const type 'const
      Tacho::Experimental::NoConjugate' without a user-provided default
      constructor
          const NoConjugate cjA;          
                            ^
                               {}

@trilinos/shylu  @kyungjoo-kim  It seems you are the only author of this file.  Can you help?  I have built from scratch and still see this error.  Thanks for the help.

## Expectations
This built prior to my recent pull.

## Current Behavior
Fails to build on Mac

## Your Environment
- **Relevant configure flags or configure script:**  
[build.txt](https://github.com/trilinos/Trilinos/files/1668944/build.txt)

- **Operating system and version:**  
Mac OS X 10.11.6

## Additional Information

* Configure log file:  
[configure.log](https://github.com/trilinos/Trilinos/files/1668947/configure.log)

* Build log file:  
[make.log](https://github.com/trilinos/Trilinos/files/1668948/make.log)

**Comment by mhoemmen** [comment]
@trilinos/shylu

**Comment by srajama1** [comment]
@ccober6 : Appears to be a default constructor issue. We will take care of this.

**Comment by kyungjoo-kim** [comment]
@ccober6 when the default constructor is not provided, a compiler should be able to create a default constructor that is automatically defined. what compiler do you use ? I will write the default constructor in my code so that this problem would not occur in the next time. 

FYI: on my linux machine (gcc 4.8.4), this build failure is not reproduced.

**Comment by kyungjoo-kim** [comment]
@ccober6 could you update the develop branch and re-test the code ? I do not have sems environments on my mac and I cannot check myself if this resolves your issue.

**Comment by ccober6** [comment]
clang is the compiler.

So I pulled on the develop branch, rebuilt from scratch, and still got the same errors.

Did a little searching and found https://stackoverflow.com/questions/28337951/clang-compile-error-with-default-initialization, which may shed some light on this.

FYI, I also can build on the CEE LAN, but that is with gcc.

**Comment by ccober6** [comment]
The suggested changes from @kyungjoo-kim compiled!  @kyungjoo-kim you should be able to make those changes and push.

**Comment by kyungjoo-kim** [comment]
Thank you for confirming that this issue is resolved. As @ccober6 pointed out, C++ standard state that 
```
If a program calls for the default initialization of an object of a const-qualified type T, 
T shall be a class type with a user-provided default constructor.
```
Very useful information to prevent further mistakes regarding to this type of errors.
