### ISSUE TITLE
Tpetra: Request for makeOptimizedColMapAndImport variant that lets users supply ownership (PID) of column Map entries on each process

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#2198]
@alanw0 requested a version of `Tpetra::Details::makeOptimizedColMap` that would let users supply PID (ownership) information for the input column Map.  This would avoid getRemoteIndexList calls, that may require expensive rounds of communication.

This differs from the existing `makeOptimizedColMapAndImport`, that optionally lets users specify an input Import object.  It is more expensive to construct an Import object than just to use existing PID information.  Furthermore, the current implementation of `makeOptimizedColMapAndImport` does not optimize for the case where users provide an input Import object.

This also differs from the existing Import constructor that takes ownership (PID) information as input, since that does not offer a way to optimize the column Map.

The new function would look like this:

Input:
  - Domain Map
  - Unoptimized column Map (BUT SEE CORRECTION IN COMMENT BELOW)
  - PIDs for unoptimized column Map on each process (i.e., for each GID in the column Map on my process, the corresponding PID of that GID in the input _domain_ Map).

Output:
  - Optimized column Map
  - Import from input domain Map, to output optimized column Map

"Optimized" here means that the column Map groups together "remote" GIDs (those that aren't in the domain Map on my process) by owning PID.  This lets `Tpetra::Distributor` avoid an extra buffer pack/unpack step when executing a communication pattern, esp. for sparse matrix-vector multiplies.

Users would use this interface like this:
  1. Preconstruct unoptimized column Map
  2. Use the above interface to get optimized column Map and Import
  3. Give optimized column Map to CrsGraph constructor
  4. Fill graph (possibly using Export for shared->owned edge communication)
  5. Call expertStaticFillComplete on the CrsGraph, giving that method the above Import object

It would be nicer if CrsGraph had a constructor taking the Import, so that users could construct a fill-complete CrsGraph with a given Import in one step.  This would be a separate feature request, though.

@trilinos/tpetra 

## Expectations

Users want to construct an optimized column Map and Import object by using the ownership (PID) information that they already have, rather than expensively recomputing it.  Nalu has already reported difficulties running at very large scales, due to the memory costs of arbitrary communication patterns that result from expensively recomputing ownership information.

Nalu cares about this because of the ECP ExaWind project.

## Current Behavior

The current Tpetra interface offers no way to use existing ownership information to compute an optimized column Map.

## Motivation and Context

Nalu needs to scale to very large MPI process counts.  Nalu already has ownership (PID) information from its mesh (STK).  @alanw0 has reported that when Nalu constructs its own unoptimized column Map, matrix assembly goes faster (e.g., because Nalu can use local indices), but sparse matrix-vector multiplies go slower (see above for the reason why).

## Definition of Done

- [ ] Add new function with above inputs and outputs
- [ ] Add test for that function
- [ ] Optimize that function by using / imitating `makeOptimizedColMapAndExport` implementation

**Comment by mhoemmen** [comment]
@alanw0 I'll think outside the box a bit and suggest the following revision to the list of inputs:

  - Domain Map
  - GIDs that need to go into the column Map on each process
  - PIDs of the above GIDs

Why construct the unoptimized column Map (and pay for the resulting MPI collectives) when you don't need it?

**Comment by mhoemmen** [comment]
At today's Tpetra meeting, we decided that the interface should be an Import constructor.  The Import's target Map would be the optimized column Map.  The constructor would take three arguments: the source Map, the array of remote GIDs (would be in the unoptimized column Map on the calling process), and the array of corresponding PIDs.

@alanw0 may not have much time to help, but may be interested.

**Comment by csiefer2** [comment]
This sounds like one of the key pieces of the TAFC (transferAndFillComplete)

**Comment by mhoemmen** [comment]
@csiefer2 yup :D the point is to expose the interface to users :-)

**Comment by mhoemmen** [comment]
Fixed in develop by PR #2512, which I just merged.

**Comment by kddevin** [comment]
@mhoemmen 
For better or worse, most Trilinos test builds run with at most four MPI processes.  That is, CMake's MPI_EXEC_MAX_NUMPROCS is four.  
It appears, then, that this test is not run for MPI builds.  For example, it is not listed among the tests here:
https://testing.sandia.gov/cdash/viewTest.php?buildid=3505241

Can this test be made to run on four ranks so that it will be exercised regularly?  Or is there something special about five ranks that exhibits the issue?

**Comment by mhoemmen** [comment]
@kddevin It does pass tests with 5 MPI processes.  We could come up with an example that runs on 4 MPI processes, though.

**Comment by mhoemmen** [comment]
@kddevin I agree.  I will file an issue to add more tests for that function, and separate them out into those that work for 2 or 4 MPI processes, and those that require more.

**Comment by kddevin** [comment]
Thanks, @mhoemmen 
Probably best not to have tests that don't get exercised regularly.

**Comment by mhoemmen** [comment]
@kddevin I just filed a separate issue https://github.com/trilinos/Trilinos/issues/2564 , so I will close this issue and direct future discussion there.  Thanks!
