### ISSUE TITLE
Missing Sacado test dependency

### ISSUE THREAD

**Issue by jwillenbring** [trilinos/Trilinos#221]
@etphipp 

When building Sacado for a nightly no-C++11 build with optional packages off, the following error occurred:

/jenkins/slave/workspace/Trilinos_XYCE_MPI/MPI_OPT_DEV_XYCE/Trilinos/packages/sacado/test/UnitTests/ConversionTests.cpp:30:39: error: Teuchos_UnitTestHarness.hpp: No such file or directory
/jenkins/slave/workspace/Trilinos_XYCE_MPI/MPI_OPT_DEV_XYCE/Trilinos/packages/sacado/test/UnitTests/ConversionTests.cpp:31:42: error: Teuchos_UnitTestRepository.hpp: No such file or directory
/jenkins/slave/workspace/Trilinos_XYCE_MPI/MPI_OPT_DEV_XYCE/Trilinos/packages/sacado/test/UnitTests/ConversionTests.cpp:32:40: error: Teuchos_GlobalMPISession.hpp: No such file or directory
/jenkins/slave/workspace/Trilinos_XYCE_MPI/MPI_OPT_DEV_XYCE/Trilinos/packages/sacado/test/UnitTests/ConversionTests.cpp:33:38: error: Teuchos_TestingHelpers.hpp: No such file or directory
/jenkins/slave/workspace/Trilinos_XYCE_MPI/MPI_OPT_DEV_XYCE/Trilinos/packages/sacado/test/UnitTests/ConversionTests.cpp:53: error: expected constructor, destructor, or type conversion before ‘(’ token
/jenkins/slave/workspace/Trilinos_XYCE_MPI/MPI_OPT_DEV_XYCE/Trilinos/packages/sacado/test/UnitTests/ConversionTests.cpp:70: error: template declaration of ‘bool test_ad_conversions’
/jenkins/slave/workspace/Trilinos_XYCE_MPI/MPI_OPT_DEV_XYCE/Trilinos/packages/sacado/test/UnitTests/ConversionTests.cpp:70: error: ‘Teuchos’ has not been declared
...

The full context can be seen here:

http://testing.sandia.gov/cdash/viewBuildError.php?buildid=2380725

I have a simple fix that I have tested which is to add TeuchosCore as a required test dependence for Sacado. I did not investigate if it would be possible to refactor the testing to optionally use Teuchos. It seems very likely that this case isn't commonly exercised, as Teuchos is an optional library dependence for Sacado, and Teuchos is included in the vast majority of Trilinos builds.

I plan to issue a pull request for this simple fix later today.

**Comment by etphipp** [comment]
These tests just require Teuchos for use of the unit test harness.  I don't want to make TeuchosCore a required dependency.  Instead I will disable these tests if Teuchos is not enabled.

**Comment by etphipp** [comment]
I believe 0ab9e11 fixed this.  If not, please reopen.

**Comment by jwillenbring** [comment]
Thanks.

**Comment by jwillenbring** [comment]
Ifdef'ing the code should resolve this issue. Please add the optional test dependence on TeuchosCore to the Dependencies.cmake file too.

**Comment by etphipp** [comment]
Actually I didn't ifdef the code, I disabled the whole test in CMake (and many others).  Since Sacado already has an optional library dependency on Teuchos, why do I need to add an optional test dependency too?  At any rate I went ahead and made the change.

**Comment by jwillenbring** [comment]
I thought that since the library has an optional dependence on Teuchos, it would still make sense to list an optional test dependence on TeuchosCore, since it is a subset of Teuchos and could be available when all of Teuchos is not. I will not push further if that doesn't make sense.
