### ISSUE TITLE
SuperLU support (continuation of ticket 1958)

### ISSUE THREAD

**Issue by VictorEijkhout** [trilinos/Trilinos#2220]
I have downloaded SuperLU (sequential, I think) 5.2.1 (even though the dot-h files claim to be 4.1, but that's software project management for you) which has a prototype with 22 parameters:

```
dgssvx(superlu_options_t *, SuperMatrix *, int *, int *, int *,
       char *, double *, double *, SuperMatrix *, SuperMatrix *,
       void *, int, SuperMatrix *, SuperMatrix *,
       double *, double *, double *, double *,
       GlobalLU_t *, mem_usage_t *, SuperLUStat_t *, int *);
```

while the amesos file has 21:

```
    dgssvx( &(SLUopt), &(data_->A),
            &perm_c_[0], &perm_r_[0], &etree_[0], &equed_, &R_[0],
            &C_[0], &(data_->L), &(data_->U), NULL, 0,
            &(data_->B), &(data_->X), &rpg, &rcond, &ferr_[0],
            &berr_[0], &(data_->mem_usage), &SLU_stat,
            &Ierr[0] );
```

So the question is, do I downgrade or do you upgrade?

V.

**Comment by ndellingwood** [comment]
@VictorEijkhout Could you give me more info about your configuration? A configuration file and your configure output? Also, how up-to-date is your version of Trilinos? Commit with sha 01268424926a5a2cf0a281299d7060e9b3ae9fb3 includes PR #1643 which added the SuperLU 5 support (tested with 5.0 and 5.1.1 at that time). 

I was able to configure/build Amesos using SuperLU/5.2.1 with gcc/5.4 and cmake/3.6.2. 
From the output, it looks like something is going wrong at configuration and a cmake variable is not getting set to use the SuperLU5 API, rather than the previous API - hence the missing 22nd parameter which should be of type `GlobalLU_t *`

**Comment by VictorEijkhout** [comment]
On Feb 6, 2018, at 5:03 PM, ndellingwood <notifications@github.com<mailto:notifications@github.com>> wrote:

From the output, it looks like something is going wrong at configuration and a cmake variable is not getting set to use the SuperLU5 API

That sounds like a reasonable diagnosis. If you dictate me what the name of the variable is and the appropriate value, I’ll rerun my configure.

Victor.

**Comment by ndellingwood** [comment]
Here's my stripped down config file - 

```
#!/bin/bash

export SRCDIR=/Users/ndellin/Research/trilinos-dev/Trilinos

BLAS_PATH=/Users/ndellin/Research/TPL/BLAS-3.6.0
LAPACK_PATH=/Users/ndellin/Research/TPL/lapack-3.6.1

SLU_VERSION=5.2.1
SUPERLU_PATH=/Users/ndellin/Research/TPL/SuperLU_${SLU_VERSION}

export INSTALL_LOCATION=${PWD}/install

rm -rf CMakeCache.txt CMakeFiles

cmake \
\
-D CMAKE_INSTALL_PREFIX:PATH="${INSTALL_LOCATION}" \
-D CMAKE_CXX_FLAGS:STRING="-g" \
-D CMAKE_MAKE_PROGRAM="make" \
-D CMAKE_BUILD_TYPE:STRING=RELEASE \
-D CMAKE_VERBOSE_MAKEFILE:BOOL=TRUE \
-D BUILD_SHARED_LIBS:BOOL=OFF \
-D Trilinos_VERBOSE_CONFIGURE:BOOL=OFF \
-D TPL_ENABLE_MPI:BOOL=OFF \
  -D CMAKE_CXX_COMPILER:FILEPATH="`which mpicxx`" \
  -D CMAKE_C_COMPILER:FILEPATH="`which mpicc`" \
  -D CMAKE_Fortran_COMPILER:FILEPATH="`which mpifort`" \
-D TPL_ENABLE_BLAS:STRING=ON \
  -D BLAS_LIBRARY_DIRS:FILEPATH=${BLAS_PATH} \
  -D BLAS_LIBRARY_NAMES="blas" \
-D TPL_ENABLE_LAPACK:STRING=ON \
  -D LAPACK_INCLUDE_DIRS:FILEPATH="${LAPACK_PATH}/SRC" \
  -D LAPACK_LIBRARY_DIRS:FILEPATH=${LAPACK_PATH} \
  -D LAPACK_LIBRARY_NAMES="lapack" \
-D TPL_ENABLE_SuperLU:BOOL=ON \
  -D SuperLU_INCLUDE_DIRS:FILEPATH="${SUPERLU_PATH}/SRC" \
  -D SuperLU_LIBRARY_DIRS:FILEPATH="${SUPERLU_PATH}/SRC" \
  -D SuperLU_LIBRARY_NAMES="superlu_${SLU_VERSION}" \
\
-D Trilinos_ENABLE_EXAMPLES:BOOL=OFF \
-D Trilinos_ENABLE_TESTS:BOOL=OFF \
-D Trilinos_ENABLE_COMPLEX_DOUBLE:BOOL=ON \
-D Trilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=OFF \
-D Trilinos_ENABLE_Amesos:BOOL=ON \
  -D Amesos_ENABLE_SuperLU:BOOL=ON \
  -D Amesos_ENABLE_TESTS:BOOL=ON \
  -D Amesos_ENABLE_EXAMPLES:BOOL=ON \
\
-D Trilinos_ENABLE_CHECKED_STL:BOOL=OFF \
-D Trilinos_ENABLE_OpenMP:BOOL=OFF \
-D Trilinos_ENABLE_EXPLICIT_INSTANTIATION=ON \
-D Trilinos_ENABLE_Epetra=ON \
  -D Epetra_ENABLE_EXAMPLES:BOOL=OFF \
  -D Epetra_ENABLE_TESTS:BOOL=OFF \
${SRCDIR}
```

If SuperLU5 is correctly recognized the configure output should show the following:
```
-- Performing Test Trilinos_ENABLE_SuperLU5_API
-- Performing Test Trilinos_ENABLE_SuperLU5_API - Success
```

**Comment by VictorEijkhout** [comment]
On Feb 6, 2018, at 5:46 PM, ndellingwood <notifications@github.com<mailto:notifications@github.com>> wrote:


If SuperLU5 is correctly recognized the configure output should show the following:

-- Performing Test Trilinos_ENABLE_SuperLU5_API
-- Performing Test Trilinos_ENABLE_SuperLU5_API - Success

No such luck.

Is there an explicit parameter that I can set to force SLU 5 to be recognized?

Configure “line” attached.

Victor.

**Comment by ndellingwood** [comment]
@VictorEijkhout Could you attach or paste your configure line again? It's not available on the Github message. If a text file, sometimes it's necessary to add .txt 

There is not an explicit parameter, the use of SuperLU 5.x is tested at configuration by CMake using `CHECK_SUPERLU_GLOBALLU_T_ARG`; if the sample code with the newer API compiles properly (functions expecting `GlobalLU_t*` argument) then a variable is set for the appropriate packages enabling macros.

**Comment by ndellingwood** [comment]
Oops, copied wrong CMake command above - I meant configuration is tested by using `CHECK_C_SOURCE_COMPILES`. What I pasted above, `CHECK_SUPERLU_GLOBALLU_T_ARG`, refers to the name of the CMake function internally tested.

**Comment by VictorEijkhout** [comment]
On Feb 7, 2018, at 6:06 PM, ndellingwood <notifications@github.com<mailto:notifications@github.com>> wrote:


@VictorEijkhout<https://github.com/victoreijkhout> Could you attach or paste your configure line again? It's not available on the Github message.

Beats me why people use this git stuff. I’ve yet to have the first positive experience with it. Is it just because Linus uses it?

cmake -VV \
  -D BUILD_SHARED_LIBS:BOOL=ON \
  -D Trilinos_VERBOSE_CONFIGURE=OFF \
  -D CMAKE_VERBOSE_MAKEFILE=ON \
  -D Trilinos_ENABLE_ALL_PACKAGES:BOOL=OFF \
  -D Trilinos_ASSERT_MISSING_PACKAGES=OFF \
  -D Trilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=OFF \
  -D Trilinos_ENABLE_TESTS:BOOL=OFF \
  -D Trilinos_ENABLE_EXAMPLES:BOOL=ON \
  -D Trilinos_ENABLE_Export_Makefiles:BOOL=ON \
  -D Trilinos_ENABLE_Fortran:BOOL=ON \
  \
  -D CMAKE_INSTALL_PREFIX:PATH=%{INSTALL_DIR} \
  -D CMAKE_BUILD_TYPE:STRING=RELEASE \
  -D CMAKE_C_FLAGS:STRING="${COPTFLAGS} ${MKLFLAG}" \
  -D CMAKE_CXX_FLAGS:STRING="${COPTFLAGS} ${MKLFLAG} -DMPICH_SKIP_MPICXX" \
  -D Trilinos_EXTRA_LINK_FLAGS="${TACC_PYTHON_LIB}/libpython2.7.so" \
  -D Trilinos_EXTRA_LD_FLAGS="${TACC_PYTHON_LIB}/libpython2.7.so" \
  \
  -D BLAS_INCLUDE_DIRS:PATH="${TACC_MKL_INC}" \
  -D BLAS_LIBRARY_DIRS:PATH="${TACC_MKL_LIB}" \
  -D BLAS_LIBRARY_NAMES:STRING="mkl_intel_lp64;mkl_sequential;mkl_core;pthread" \
  -D LAPACK_INCLUDE_DIRS:PATH="${TACC_MKL_INC}" \
  -D LAPACK_LIBRARY_DIRS:PATH="${TACC_MKL_LIB}" \
  -D LAPACK_LIBRARY_NAMES:STRING="mkl_intel_lp64;mkl_sequential;mkl_core;pthread" \
  \
  -D TPL_ENABLE_MPI:BOOL=ON \
  -D MPI_EXEC:FILEPATH="/opt/apps/xalt/0.6/bin/ibrun" \
  -D TPL_ENABLE_GLM=OFF \
  -D TPL_ENABLE_Matio=OFF \
  \
  -D TPL_ENABLE_Boost:BOOL=ON \
  -D Boost_INCLUDE_DIRS:PATH=$TACC_BOOST_INC      \
  -D Boost_LIBRARY_DIRS:PATH=$TACC_BOOST_LIB      \
  -D TPL_ENABLE_BoostLib:BOOL=ON \
  -D BoostLib_INCLUDE_DIRS:PATH=$TACC_BOOST_INC      \
  -D BoostLib_LIBRARY_DIRS:PATH=$TACC_BOOST_LIB      \
  \
  -D TPL_ENABLE_HDF5:BOOL=${HAS_HDF5} \
  -D HDF5_INCLUDE_DIRS:PATH=$TACC_HDF5_INC    \
  -D HDF5_LIBRARY_DIRS:PATH=$TACC_HDF5_LIB    \
  -D TPL_ENABLE_Netcdf:BOOL=${HAS_NETCDF} \
  -D Netcdf_INCLUDE_DIRS:PATH=$TACC_NETCDF_INC    \
  -D Netcdf_LIBRARY_DIRS:PATH=$TACC_NETCDF_LIB    \
  \
  -D Trilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=ON \
  \
  -D Trilinos_ENABLE_Amesos:BOOL=ON \
  -D Amesos2_ENABLE_Basker:BOOL=ON \
  -D Trilinos_ENABLE_Anasazi:BOOL=ON \
  -D Trilinos_ENABLE_AztecOO:Bool=ON \
  -D Trilinos_ENABLE_Belos:BOOL=ON \
  -D Trilinos_ENABLE_Epetra:Bool=ON \
  -D Trilinos_ENABLE_EpetraExt:Bool=ON \
  -D                 Epetra_ENABLE_TESTS:BOOL=ON \
  -D Trilinos_ENABLE_FEI:Bool=ON \
  -D Trilinos_ENABLE_Ifpack:Bool=ON \
  -D Trilinos_ENABLE_Intrepid:BOOL=ON \
  -D                 Intrepid_ENABLE_TESTS:BOOL=ON \
  -D Trilinos_ENABLE_Issoropia:BOOL=ON \
  -D Trilinos_ENABLE_Kokkos:BOOL=ON \
  -D Trilinos_ENABLE_ML:BOOL=ON \
      -D ML_ENABLE_SuperLU:BOOL=OFF \
  -D Trilinos_ENABLE_MOOCHO:BOOL=ON \
  -D Trilinos_ENABLE_MueLu:BOOL=${HAS_MUELU} \
  -D                 MueLu_ENABLE_Tutorial:BOOL=OFF \
  -D Trilinos_ENABLE_NOX=ON \
  -D                 NOX_ENABLE_TESTS:BOOL=OFF \
  -D Trilinos_ENABLE_Pamgen:Bool=ON \
  -D Trilinos_ENABLE_Panzer:Bool=ON \
  -D Trilinos_ENABLE_Phalanx:BOOL=ON \
      -D Phalanx_EXPLICIT_TEMPLATE_INSTANTIATION=ON \
      -D Phalanx_ENABLE_EXAMPLES=OFF \
  -D Trilinos_ENABLE_Rythmos:BOOL=ON \
  -D Trilinos_ENABLE_Sacado:Bool=ON \
  -D Trilinos_ENABLE_SEACAS:BOOL=${HAS_SEACAS} \
      -D Trilinos_ENABLE_SEACASIoss:BOOL=${HAS_SEACAS} \
      -D Trilinos_ENABLE_SEACASBlot:BOOL=${HAS_SEACAS} \
  -D Trilinos_ENABLE_SECONDARY_STABLE_CODE:BOOL=ON \
  -D Trilinos_ENABLE_Shards:BOOL=ON \
  -D Trilinos_ENABLE_ShyLU:BOOL=ON \
  -D Trilinos_ENABLE_STK:BOOL=${HAS_STK} \
  -D TPL_ENABLE_SuperLU:BOOL=ON \
      -D SuperLU_INCLUDE_DIRS:PATH="${TACC_SUPERLUSEQ_DIR}/include" \
      -D SuperLU_LIBRARY_DIRS:PATH="${TACC_SUPERLUSEQ_LIB}" \
      -D SuperLU_LIBRARY_NAMES="superlu" \
  -D Trilinos_ENABLE_Stokhos:BOOL=ON \
  -D Trilinos_ENABLE_Stratimikos:BOOL=ON \
  -D Trilinos_ENABLE_Teko:BOOL=ON \
  -D Trilinos_ENABLE_Teuchos:BOOL=ON \
  -D Trilinos_ENABLE_Tpetra:BOOL=ON \
  -D Trilinos_ENABLE_TriKota:BOOL=ON \
  -D Trilinos_ENABLE_Zoltan:BOOL=ON \
  \
  -D Trilinos_ENABLE_PyTrilinos:Bool=${HAS_PYTHON} \
  -D CMAKE_PYTHON_INCLUDE_DIR:PATH="${TACC_PYTHON_INC}" \
  -D CMAKE_PYTHON_LIBRARIES:STRING="${TACC_PYTHON_LIB}" \
  -D PyTrilinos_DOCSTRINGS:BOOL=OFF \
  -D SWIG_EXECUTABLE:FILEPATH=${TACC_SWIG_DIR}/bin/swig \
  \
  ${TRILINOS_LOCATION}/trilinos-${VERSION} \
  | tee /admin/build/admin/rpms/stampede2/SPECS/trilinos-${VERSION}-cmake.log 2>&1



Victor.

**Comment by ndellingwood** [comment]
@VictorEijkhout Here's the line with the work-around flags appended to your original:

`-D CMAKE_CXX_FLAGS:STRING="${COPTFLAGS} ${MKLFLAG} -DMPICH_SKIP_MPICXX -DHAVE_AMESOS_SUPERLU5_API -DHAVE_AMESOS2_SUPERLU5_API -DHAVE_IFPACK2_SUPERLU5_API" \`

**Comment by VictorEijkhout** [comment]
I think this was ultimately down to a confusion on my part. Left hand not knowing what the right hand was doing. Sorry for the trouble.

Now I'm stuck on the following:

```
/opt/apps/gcc/7.1.0/lib/gcc/x86_64-pc-linux-gnu/7.1.0/../../../../x86_64-pc-linux-gnu/bin/ld: /home1/apps/gcc7_1/superlu_seq/5.2.1/lib/libsuperlu.a(util.o)(.text+0x7): unresolvable R_X86_64_NONE reloc
ation against symbol `stderr@@GLIBC_2.2.5'
/opt/apps/gcc/7.1.0/lib/gcc/x86_64-pc-linux-gnu/7.1.0/../../../../x86_64-pc-linux-gnu/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
make[2]: *** [packages/amesos/src/libamesos.so.12.13] Error 1```

I think this has something to do with the fPIC option but here are the superlu compile lines:

```
gcc -fPIC -O2  -DUSE_VENDOR_BLAS -c sutil.c
gcc -fPIC -O2  -DUSE_VENDOR_BLAS -c util.c
gcc -fPIC -O2  -DUSE_VENDOR_BLAS -c dutil.c
gcc -fPIC -O2  -DUSE_VENDOR_BLAS -c cutil.c
gcc -fPIC -O2  -DUSE_VENDOR_BLAS -c zutil.c
```

Any ideas?

**Comment by mhoemmen** [comment]
@trilinos/amesos @trilinos/amesos2

**Comment by srajama1** [comment]
It appears to be a static library vs dynamic library issue.

Please see this.
https://stackoverflow.com/questions/19768267/relocation-r-x86-64-32s-against-linking-error

Can you confirm the static library (superlu in this case) is position independent ?

**Comment by VictorEijkhout** [comment]
On Mar 20, 2018, at 3:34 PM, Siva Rajamanickam <notifications@github.com<mailto:notifications@github.com>> wrote:


Can you confirm the static library (superlu in this case) is position independent ?


I assume you are referring to the top answer? Note that the compile lines I gave all have the “-fPIC” option.

I ran the commands in that answer and “if the output is empty” is certainly not true.

# readelf --relocs util.o | egrep '(GOT|PLT|JU?MP_SLOT)' | wc -l
85

The actual output is full of stuff like:

0000000006ca  005b00000004 R_X86_64_PLT32    0000000000000000 superlu_malloc - 4
0000000006dd  005b00000004 R_X86_64_PLT32    0000000000000000 superlu_malloc - 4
000000000749  005c00000004 R_X86_64_PLT32    0000000000000000 sprintf - 4
000000000751  004100000004 R_X86_64_PLT32    0000000000000000 superlu_abort_and_exit - 4
000000000781  005c00000004 R_X86_64_PLT32    0000000000000000 sprintf - 4
000000000789  004100000004 R_X86_64_PLT32    0000000000000000 superlu_abort_and_exit - 4
0000000007c1  004a00000004 R_X86_64_PLT32    0000000000000000 printf - 4
0000000007e8  004a00000004 R_X86_64_PLT32    0000000000000000 printf - 4
000000000840  004a00000004 R_X86_64_PLT32    0000000000000000 printf - 4
000000000878  004a00000004 R_X86_64_PLT32    0000000000000000 printf - 4
000000000898  004d00000004 R_X86_64_PLT32    0000000000000000 superlu_free - 4
0000000008a1  004d00000004 R_X86_64_PLT32    0000000000000000 superlu_free - 4

Now the error msg was:

unresolvable R_X86_64_NONE relocation against symbol `stderr@@GLIBC_2.2.5’

and I see a discrepancy between NONE and PLT32. Any idea if that’s significant?

Victor.

**Comment by ndellingwood** [comment]
@VictorEijkhout Are you building your own SLU5.2.1 or using a module? I'm going to post some CMake instructions to build SLU5.2.1 that worked for me with shared libs enabled, hopefully this will help if you're willing to build SLU.

**SuperLU_5.2.1:**
1. In the base directory, create a build directory (e.g. PATH/SuperLU_5.2.1/build)
2. Define your install location (I used variable INSTALL_LOCATION), then run the following configure line (or place in a configure script):
(Tested on MacOSX)
```
cmake \
\
-D CMAKE_INSTALL_PREFIX:PATH="${INSTALL_LOCATION}" \
-D CMAKE_BUILD_TYPE:STRING=RELEASE \
-D CMAKE_C_COMPILER:FILEPATH="`which gcc`" \
-D CMAKE_Fortran_COMPILER:FILEPATH="`which gfortran`" \
-D CMAKE_C_FLAGS:STRING="-g -std=c99 -DNDEBUG -fPIC" \
-D CMAKE_Fortran_FLAGS:STRING="-shared" \
../
```

* On the Mac I had issues using `-D BUILD_SHARED_LIBS:BOOL=ON` because some shared libs were not found, however on a Linux system you may be able to just add this to the link line and ignore the `*FLAGS` lines above, though I haven't tried yet. 

Optionally, if you want SLU to link to your own BLAS (built properly for shared library support) you can add the following lines:
```
-D enable_blaslib:BOOL=OFF \
-D TPL_BLAS_LIBRARIES:FILEPATH="PATH_TO_BLASLIB/libblas.{a,so,dylib}" \
```

3. make install


**Trilinos**:
I was able to build Trilinos with Amesos and SuperLU5.2.1 and shared libraries by linking to SLU built as above and a custom build of BLAS (it appears I do not have a dylib of BLAS on the Mac) using the following configure script with appropriate paths defined:
```
cmake \
\
-D CMAKE_INSTALL_PREFIX:PATH="${INSTALL_LOCATION}" \
-D CMAKE_CXX_FLAGS:STRING="-g" \
-D CMAKE_BUILD_TYPE:STRING=RELEASE \
-D CMAKE_VERBOSE_MAKEFILE:BOOL=TRUE \
-D BUILD_SHARED_LIBS:BOOL=ON \
-D Trilinos_VERBOSE_CONFIGURE:BOOL=OFF \
-D TPL_ENABLE_MPI:BOOL=OFF \
  -D CMAKE_CXX_COMPILER:FILEPATH="`which g++`" \
  -D CMAKE_C_COMPILER:FILEPATH="`which gcc`" \
  -D CMAKE_Fortran_COMPILER:FILEPATH="`which gfortran`" \
-D TPL_ENABLE_BLAS:STRING=ON \
  -D BLAS_INCLUDE_DIRS:FILEPATH="${BLAS_PATH}/../BLAS/SRC" \
  -D BLAS_LIBRARY_DIRS:FILEPATH=${BLAS_PATH}/lib \
  -D BLAS_LIBRARY_NAMES="blas" \
-D TPL_ENABLE_LAPACK:STRING=ON \
  -D LAPACK_INCLUDE_DIRS:FILEPATH="${LAPACK_PATH}/../SRC" \
  -D LAPACK_LIBRARY_DIRS:FILEPATH=${LAPACK_PATH}/lib \
  -D LAPACK_LIBRARY_NAMES="lapack" \
-D TPL_ENABLE_SuperLU:BOOL=ON \
  -D SuperLU_INCLUDE_DIRS:FILEPATH="${SUPERLU_PATH}/include" \
  -D SuperLU_LIBRARY_DIRS:FILEPATH="${SUPERLU_PATH}/lib" \
  -D SuperLU_LIBRARY_NAMES="superlu" \
\
-D Trilinos_ENABLE_EXAMPLES:BOOL=OFF \
-D Trilinos_ENABLE_TESTS:BOOL=OFF \
-D Trilinos_ENABLE_COMPLEX_DOUBLE:BOOL=ON \
-D Trilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=OFF \
-D Trilinos_ENABLE_Amesos:BOOL=ON \
  -D Amesos_ENABLE_SuperLU:BOOL=ON \
  -D Amesos_ENABLE_TESTS:BOOL=ON \
  -D Amesos_ENABLE_EXAMPLES:BOOL=ON \
\
-D Trilinos_ENABLE_OpenMP:BOOL=OFF \
-D Trilinos_ENABLE_EXPLICIT_INSTANTIATION=ON \
${SRCDIR}
```

Hopefully this helps.

**Comment by srajama1** [comment]
Sorry, that error is beyond my level compiler knowledge ! As @ndellingwood says recompiling SuperLU is not that hard. 

@nmhamster : Any clue on this relocatable code errors ?

**Comment by nmhamster** [comment]
@srajama1 - so relocatable code can cause the error but very often the problem is that libraries are not correctly put on the link line. 

Before we get too far, can you try setting:

```
-D CMAKE_Fortran_FLAGS:STRING="-fPIC"
```

(it is currently set to `-shared` which is only useful for actual linking of shared libraries).

**Comment by srajama1** [comment]
We are not able to reproduce the problem.  @VictorEijkhout has to try it.

Will Spack resolve such issues ?

**Comment by VictorEijkhout** [comment]
On Mar 21, 2018, at 5:16 PM, Si Hammond <notifications@github.com<mailto:notifications@github.com>> wrote:


-D CMAKE_Fortran_FLAGS:STRING="-fPIC”

That doesn’t seem to help.

[ 51%] Linking CXX shared library libamesos.so
cd /tmp/trilinos-build/packages/amesos/src && /opt/apps/cmake/3.10.2/bin/cmake -E cmake_link_script CMakeFiles/amesos.dir/link.txt --verbose=1
/home1/apps/intel/compilers_and_libraries_2018.0.128/linux/mpi/intel64/bin/mpicxx -fPIC  -pedantic -Wall -Wno-long-long -Wwrite-strings   -g -march=broadwell -mtune=knl -O2  -DMPICH_SKIP_MPICXX -DHAVE
_AMESOS_SUPERLU5_API -DHAVE_AMESOS2_SUPERLU5_API -DHAVE_IFPACK2_SUPERLU5_API -std=c++11 -O3 -DNDEBUG  -shared -Wl,-soname,libamesos.so.12 -o libamesos.so.12.13 CMakeFiles/amesos.dir/Amesos_Status.cpp.
o CMakeFiles/amesos.dir/Amesos_Control.cpp.o CMakeFiles/amesos.dir/Amesos_Support.cpp.o CMakeFiles/amesos.dir/Amesos_Klu.cpp.o CMakeFiles/amesos.dir/Amesos.cpp.o CMakeFiles/amesos.dir/Amesos_Superlu.c
pp.o CMakeFiles/amesos.dir/CrsMatrixTranspose.cpp.o CMakeFiles/amesos.dir/Amesos_Lapack.cpp.o  -L/opt/intel/compilers_and_libraries_2017.4.196/linux/mkl/lib/intel64 -Wl,-rpath,/tmp/trilinos-build/pack
ages/epetraext/src:/tmp/trilinos-build/packages/common/auxiliarySoftware/SuiteSparse/src:/tmp/trilinos-build/packages/triutils/src:/tmp/trilinos-build/packages/epetra/src:/tmp/trilinos-build/packages/
teuchos/kokkoscomm/src:/tmp/trilinos-build/packages/teuchos/kokkoscompat/src:/tmp/trilinos-build/packages/teuchos/remainder/src:/tmp/trilinos-build/packages/teuchos/numerics/src:/tmp/trilinos-build/pa
ckages/teuchos/comm/src:/tmp/trilinos-build/packages/teuchos/parameterlist/src:/tmp/trilinos-build/packages/teuchos/parser/src:/opt/intel/compilers_and_libraries_2017.4.196/linux/mkl/lib/intel64:/tmp/
trilinos-build/packages/teuchos/core/src:/tmp/trilinos-build/packages/kokkos/core/src: ../../epetraext/src/libepetraext.so.12.13 ../../common/auxiliarySoftware/SuiteSparse/src/libtrilinosss.so.12.13 /
home1/apps/gcc7_1/superlu_seq/5.2.1/lib/libsuperlu.a ../../triutils/src/libtriutils.so.12.13 ../../epetra/src/libepetra.so.12.13 ../../teuchos/kokkoscomm/src/libteuchoskokkoscomm.so.12.13 ../../teucho
s/kokkoscompat/src/libteuchoskokkoscompat.so.12.13 ../../teuchos/remainder/src/libteuchosremainder.so.12.13 ../../teuchos/numerics/src/libteuchosnumerics.so.12.13 ../../teuchos/comm/src/libteuchoscomm
.so.12.13 ../../teuchos/parameterlist/src/libteuchosparameterlist.so.12.13 ../../teuchos/parser/src/libteuchosparser.so.12.13 -lmkl_intel_lp64 -lmkl_sequential -lmkl_core -lpthread -lmkl_intel_lp64 -l
mkl_sequential -lmkl_core -lpthread ../../teuchos/core/src/libteuchoscore.so.12.13 ../../kokkos/core/src/libkokkoscore.so.12.13 /usr/lib64/libdl.so -lm
/opt/apps/gcc/7.1.0/lib/gcc/x86_64-pc-linux-gnu/7.1.0/../../../../x86_64-pc-linux-gnu/bin/ld: /home1/apps/gcc7_1/superlu_seq/5.2.1/lib/libsuperlu.a(util.o)(.text+0x7): unresolvable R_X86_64_NONE reloc
ation against symbol `stderr@@GLIBC_2.2.5'
/opt/apps/gcc/7.1.0/lib/gcc/x86_64-pc-linux-gnu/7.1.0/../../../../x86_64-pc-linux-gnu/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
make[2]: *** [packages/amesos/src/libamesos.so.12.13] Error 1
make[2]: Leaving directory `/tmp/trilinos-build'
make[1]: *** [packages/amesos/src/CMakeFiles/amesos.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs….

I’ll try rebuilding superlu next with your provided instructions.

Victor.
