### ISSUE TITLE
Tpetra build failure on trappist

### ISSUE THREAD

**Issue by lucbv** [trilinos/Trilinos#2222]
I had a build error on trappist last night for the [clang](https://testing.sandia.gov/cdash/viewBuildError.php?buildid=3372455) and [Intel](https://testing.sandia.gov/cdash/viewBuildError.php?buildid=3372296) builds, gcc seems fine.

@trilinos/tpetra 

## Expectations
We should fix these builds as they are useful for mac users (clang) and on hpc (intel)

## Current Behavior
Tptra fails to build

## Definition of Done
- [ ] clang build successful.
- [ ] Intel build successful.

## Steps to Reproduce
See the above link to the dashboard builds that failed

**Comment by mhoemmen** [comment]
@lucbv Did this just start happening last night?

**Comment by ikalash** [comment]
We saw the same thing in the Albany dashboard, starting last night: 

http://cdash.sandia.gov/CDash-2-3-0/viewBuildError.php?buildid=66533

**Comment by lucbv** [comment]
@mhoemmen the Intel build has other issues preventing it to build (although not seen this morning) but the clang build was fine, it actually prompted us to look into some parameter list that are failing.

**Comment by ikalash** [comment]
For Albany, it looks like it happened with an intel and gcc compiler.

**Comment by jhux2** [comment]
@lucbv Did you try backing out the two git updates that occurred to see if those triggered the Clang errors?

**Comment by mhoemmen** [comment]
Hm, what about this commit?  

https://github.com/trilinos/Trilinos/commit/d2683f3d221e2220c1792c55f3f7bb547f5d8eb4

**Comment by mhoemmen** [comment]
@mhoemmen I've been at a workshop all week so I haven't had a chance to get to this.  I haven't changed Tpetra in a week at least.  As mentioned in the comment above, I think I have an idea what happened, and I hope to find a bit of time today to fix it.  On the other hand, #2221 and other issues make it harder to test downstream, so this may need to be a force push.

**Comment by mhoemmen** [comment]
Hm, Clang 3.9.0 builds Tpetra for me.

**Comment by mhoemmen** [comment]
That was with ETI ON.  I will retry with ETI OFF.  `Tpetra_Import_Util.hpp` including `Tpetra_Vector.hpp` may have caused a circular dependency with ETI OFF (since that includes different header files); I'll test this.

**Comment by lucbv** [comment]
@mhoemmen the MueLu dashboard is now clean and I spent some time trying to reproduce the error but did not manage to do it, neither did @cgcgcg , this is a little strange.
@ikalash do you still see the same error on the Albany dashboard?

**Comment by mhoemmen** [comment]
I can replicate with Clang 3.9.0, with ETI OFF.  The problem appears to be this commit:

https://github.com/trilinos/Trilinos/commit/d2683f3d221e2220c1792c55f3f7bb547f5d8eb4

The commit added a new `Tpetra_Vector.hpp` include in `Tpetra_Import_Util.hpp`.  The include is needed because it's actually used in a new function `getTwoTransferOwnershipVector` in the header file; a forward declaration or a "decl" include would not suffice.

I have pushed a revert of that commit.  It appears that nothing uses the new function yet.

This should be easy to fix: split off the function into a new file and use ETI for that file.

**Comment by mhoemmen** [comment]
@lucbv Please feel free to close if the trappist build works.  
@ikalash Thanks for reporting!

**Comment by lucbv** [comment]
@mhoemmen thanks for getting to the bottom of this. I felt uncomfortable closing the issue not knowing what actually happened...

**Comment by mhoemmen** [comment]
@lucbv I'll leave it open, then, until we've verified that the build works.  The cause is the commit in question; reverting it fixed the issue for me.

**Comment by lucbv** [comment]
@mhoemmen I have inspected my dashboard more closely and I see that Tpetra had 9 build errors last night and ctest turned it off for the MueLu tests which is why I did not see the errors right away...

**Comment by ikalash** [comment]
Still seeing build errors on the Albany dashboard: http://cdash.sandia.gov/CDash-2-3-0/viewBuildError.php?buildid=66589

**Comment by lxmota** [comment]
I can confirm that reverting https://github.com/trilinos/Trilinos/commit/d2683f3d221e2220c1792c55f3f7bb547f5d8eb4 fixes the build errors at least for one of my Albany gcc builds. Let's see what happens with the Albany CDash overnight.

**Comment by csiefer2** [comment]
Unreverted and maybe fixed?  Please comment on the nightlies this evening

**Comment by lxmota** [comment]
Will do.

**Comment by mhoemmen** [comment]
Thanks @csiefer2 !  Sorry to revert -- it looked pretty straightforward to fix but I only just got back from work travel tonight and didn't have a lot of time over there to do more than verify the issue.

**Comment by lucbv** [comment]
@csiefer2 @mhoemmen the dashboard is back to normal, I will wait for @ikalash to confirm that things look good on the Albany dashboard before closing this issue.
Thanks!

**Comment by ikalash** [comment]
Albany CDash Trilinos is back up too.  Thanks for fixing this!

**Comment by lxmota** [comment]
Irina already commented, but I confirm that the Albany CDash is back.

**Comment by mhoemmen** [comment]
Thanks all!
