### ISSUE TITLE
MueLu: trouble when building the tutorial

### ISSUE THREAD

**Issue by mayrmt** [trilinos/Trilinos#2223]
I get an error when building the MueLu tutorial. Can anybody in @trilinos/muelu build the tutorial?

## Expectations
Being able to build the MueLu tutorial.

## Current Behavior
Following the step in the ```muelu/doc/Tutorial/README``` doesn't work for me. 

Executing ```muelu/doc/Tutorial/tex/prepareTexTutorial.py``` results in the error 
```
./prepareTexTutorial.py
Prepare files...
Split source files in src folder for inclusion in pdf...
Run test examples to include results in pdf...
Traceback (most recent call last):
  File "./prepareTexTutorial.py", line 158, in <module>
    splitfileintofragments('s1_easy.txt_3.fragment','--------------------------------------------------------------------------------')
  File "./prepareTexTutorial.py", line 80, in splitfileintofragments
    file = open( inputfile )
IOError: [Errno 2] No such file or directory: 's1_easy.txt_3.fragment'
```
The directory does not contain a file ```s1_easy.txt_3.fragment```, though I don't know why. Isn't it supposed to be created when configure/build MueLu?

## Steps to Reproduce

I followed the steps described in ```muelu/doc/Tutorial/README```:
1. Build MueLu with tests and examples enabled.
2. Run ```muelu/doc/Tutorial/tex/prepareTexTutorial.py```

**Comment by cgcgcg** [comment]
That step goes through for me. Are you running in your build directory?

**Comment by mayrmt** [comment]
Yes, as instructed in ```muelu/doc/Tutorial/README```.

Which tests did you enable? All Trilinos tests or MueLu tests only?

**Comment by cgcgcg** [comment]
I don't think that you need to enable any tests. I'll check it, but I believe that all I had to do was to go to muelu/doc/Tutorial and build both in src and in tex. However, the tutorial can get disabled when you don't have some standard instantiations.

**Comment by cgcgcg** [comment]
Yep, works as advertised for me. Maybe run configure and see what the tutorial message says. From what it looks like, the examples in doc/Tutorial/src need to be compiled, but that should happen automatically.

**Comment by lucbv** [comment]
@mayrmt I think that you need to have Tpetra on at least, so if you have an Epetra only build it won't work. If you look at line 93 and below in MueLu's CMakeList.txt file, you should be able to assert that you have the required options on.

**Comment by mayrmt** [comment]
I figured it out. Thanks!
