### ISSUE TITLE
Tempus: update TSC documention for TSCS ordering issue

### ISSUE THREAD

**Issue by sconde** [trilinos/Trilinos#2228]
Using Time Step Control Strategy (TSCS) allows for applications to define their very own time step control strategy and add it to a vector of strategies and the Time Step Control will iterate and call each strategy. Essentially, this could be an `and` case if each strategies does a `min` with the step size `dt = metaData->getDt()` and a new computed step size `dt_new` before updating the step size with `metaData->setDt( DT )`.

If the application wanted an `or` case, they can just appropriately update the `metaData->setDt(dt)`. The TSC, after calling all the TSCS, gets the updated `dt` by calling `metaData->getDt()`.

Note the ordering in the `Time Step Control Strategy List` (is important). A final TSCS that is called last can get just negate all previous TSCS updates.

The documentation needs to be updated to make this clear.

@trilinos/tempus

**Comment by sconde** [comment]
@ccober6 @rppawlo @ikalash just wanted to start a discussion on this topic

**Comment by ccober6** [comment]
@sconde I think we should wait on this until we refactor the TSC, and document the refactor.  Are you OK with closing this?
