### ISSUE TITLE
Add Tempus to `trilinos.org`

### ISSUE THREAD

**Issue by sconde** [trilinos/Trilinos#2229]
Tempus is not one of the options listed.

@jmgate said he will take care of this!

@trilinos/tempus

**Comment by jmgate** [comment]
This page has been created at https://trilinos.org/packages/tempus/.  @ccober6, you'll want to log in at the bottom-left of the page and then edit the description to your heart's content.  Reassigning to you.  If you're unable to log in, I imagine someone from the framework team might need to create an account for you.

**Comment by ccober6** [comment]
This has been on my list, but I was under the impression that whatever does up on this needs to go through R&A?!  Is this right?

**Comment by jmgate** [comment]
I'd guess that's a good question for @jwillenbring.

**Comment by ccober6** [comment]
@jwillenbring, can I get login access to https://trilinos.org/wordpress/wp-login.php, so I can add a Tempus package description?  Thanks, Curt

**Comment by jwillenbring** [comment]
@ccober6 let me know if you did not get an email with login info for Trilinos.org.

**Comment by jwillenbring** [comment]
@ccober6 we could get access to the site for a DC, or you could set up a protected page and DC with the password.

**Comment by ccober6** [comment]
Tempus is now on trilinos.github.io (https://trilinos.github.io/tempus.html)!
