### ISSUE TITLE
Zoltan2:  Transfer number-of-message metrics from HOMME to Zoltan2

### ISSUE THREAD

**Issue by kddevin** [trilinos/Trilinos#223]
@mndevec has implemented metrics measuring the number of messages (neighbors) based on a graph.  These metrics should be transferred into Zoltan2's EvaluatePartition class.

Some ideas:
-  Add these metrics to Zoltan2's GraphMetricValues class
-  Create a new class for these metrics
  Choice will depend upon how we can reuse the GraphModel constructed by or passed to EvaluatePartition.

@trilinos/zoltan2

**Comment by kddevin** [comment]
This issue would benefit from a solution to #537

**Comment by mndevec** [comment]
My latest push (76a5ad47e4436052bbf8ea9c83dbe91161ea0737) should fix this issue. 

I am using tpetra matrix for message metrics, which is defined as below. 
```c++
typedef Tpetra::CrsMatrix<t_scalar_t, local_part_type, global_part_type, t_node_t> tcrsMatrix_t;
```
Iocal_part_type and global_part_type both should be part_t, but tpetra does not instantiate int,int,double that was causing the problem. Current fix is to define local_part_type and global_part_type as local and global ordinal types. 

This solves the problem, but if distributed directory is implemented, the implementation would use that.
@kddevin

**Comment by mhoemmen** [comment]
> but tpetra does not instantiate int,int,double that was causing the problem.

It does if you _ask_ ;-)  Instantiations cost build time and library size, though.  If I had my way, I would get rid of all GlobalOrdinal types other than `long long`, and only let users choose the LocalOrdinal type.

**Comment by kddevin** [comment]
Mehmet completed this work.
