### ISSUE TITLE
Nightly Clean Track Failure in PanzerAdaptersSTK_CurlLaplacianExample-ConvTest-Quad-Order-1 

### ISSUE THREAD

**Issue by william76** [trilinos/Trilinos#2233]
The test PanzerAdaptersSTK_CurlLaplacianExample-ConvTest-Quad-Order-1 failed on the nightly testing for 2/12/18.

Link to CDash Test Output
---------------------------
- https://testing.sandia.gov/cdash/testDetails.php?test=44583711&build=3381644

Possible Commit(s) Causing Error
----------------------------------
- 65a90273205b65f378220e2b95c50fb0c9b0b254
  - The test failed on Sunday (2/12) but passed on Saturday (2/11).  
  - This was the only commit from 2/11 so it's the most suspicious.
  - Committed by @mayrmt 

The failing test is a @trilinos/panzer but the commit was to @trilinos/muelu so I'm not sure if they're related or not so mentioning both teams.

**Comment by jmgate** [comment]
Looks like a bad read of the Exodus file&mdash;probably unrelated to the MueLu commit.  I just did a clean build and test on my local RHEL7 machine at commit 65a9027 and everything ran just fine.  Perhaps this failure was just a fluke?

**Comment by william76** [comment]
Looks like that's probably what happened, the test didn't fail in the nightlies last night...  I'll go ahead and close this issue.  If it pops back up tomorrow I can always reopen it ;)
