### ISSUE TITLE
PanzerMiniEM_MiniEM-BlockPrec_RefMaxwell_MPI_{1,4} Failing

### ISSUE THREAD

**Issue by jmgate** [trilinos/Trilinos#2235]
@trilinos/panzer

## Expectations
All of Panzer's tests should pass.

## Current Behavior
I'm currently seeing `PanzerMiniEM_MiniEM-BlockPrec_RefMaxwell_MPI_1` and `4` fail on my local RHEL7 machine.

## Motivation and Context
Just wanted to make sure my Trilinos was up-to-date, but now I'm seeing some tests fail.  Looks like these were only just added, so perhaps they're not thoroughly vetted yet.

## Steps to Reproduce
1. Configure Trilinos with [this script](https://github.com/trilinos/Trilinos/files/1717465/configureTrilinos.txt).
1. `cd` to `path/to/build/dir/packages/panzer`.
1. `make`
1. `ctest` (results:  [ctest1802121208470570265.log](https://github.com/trilinos/Trilinos/files/1717474/ctest1802121208470570265.log))

## Your Environment

- **Relevant repo SHA1s:**  92cc148
- **Relevant configure flags or configure script:**  See linked configure script above.
- **Operating system and version:**  RHEL7
- **Compiler and TPL versions:**  cmake-3.6.1, gcc-6.2.0, hdf5-1.10.0-patch1, netcdf-4.4.1, netcdf-cxx4-4.3.0, openmpi-2.0.0, parmetis-4.0.3, SuperLU_5.2.1, zlib-1.2.8

**Comment by cgcgcg** [comment]
Thanks for letting me know. Weird, I pushed with the checkin script, so I'll check your log file. I'll revert the commit that adds those tests if I can't fix that by tonight..

**Comment by jmgate** [comment]
Check my config script as well&mdash;I'm not sure what config options the checkin script uses.  If it has to wait till tomorrow or the next day, it's not the end of the world&hellip;

**Comment by cgcgcg** [comment]
Could you pull and check if things are fixed for you? It worked on my machine with your config script, but better be sure..

**Comment by jmgate** [comment]
I can, but it'll be Thursday at the earliest&mdash;my machine's packed up for the repainting/recarpeting working going on in CSRI.

**Comment by cgcgcg** [comment]
That's fine, it's not urgent. The builds on the dashboard look good.

**Comment by jmgate** [comment]
I can confirm these tests are passing with the latest `develop`.  Thanks @cgcgcg.
