### ISSUE TITLE
Zoltan2:  transfer new MappingProblem and MappingSolution interface into HOMME

### ISSUE THREAD

**Issue by kddevin** [trilinos/Trilinos#224]
Once Zoltan2's new MappingProblem and MappingSolution interface stabilize, we'll need to update HOMME to use them.

**Comment by mndevec** [comment]
@kddevin 
After my latest push (76a5ad47e4436052bbf8ea9c83dbe91161ea0737), I made a push to HOMME that adopts new interface for mapping problem (d38eb731d9bcc2d73007b15590aaeaaedf1c6364 in ACME). 
Old interface is still there for correctness tests. I am closing the issue, let me know if more needs to be done about this.
