### ISSUE TITLE
Zoltan / parmetis test failures

### ISSUE THREAD

**Issue by jwillenbring** [trilinos/Trilinos#225]
@trilinos/zoltan 

I was trying to set up a nightly no-C++11 build using a version of parmetis installed on the SEMS NFS mount. When I run the Zoltan tests, many of the parmetis tests fail.

http://testing.sandia.gov/cdash/viewTest.php?onlyfailed&buildid=2380727

I was able to reproduce these failures on a machine that has access to the NFS mount using the following cmake arguments:

EXTRA_ARGS=$@

cmake \
-DTrilinos_ENABLE_TESTS:BOOL=ON \
-DTrilinos_DISABLE_ENABLED_FORWARD_DEP_PACKAGES=ON \
-DTrilinos_ENABLE_SECONDARY_TESTED_CODE:BOOL=ON \
-DTrilinos_ENABLE_SECONDARY_STABLE_CODE:BOOL=ON \
-DTrilinos_ENABLE_Teuchos:BOOL= \
-DCMAKE_BUILD_TYPE:STRING=RELEASE \
-DTrilinos_ENABLE_CXX11=OFF \
-DCMAKE_CXX_FLAGS='-O3 -fPIC' \
-DCMAKE_C_FLAGS='-O3 -fPIC' \
-DParMETIS_LIBRARY_DIRS=/projects/install/rhel6-x86_64/sems/tpl/parmetis/4.0.3/gcc/4.4.7/openmpi/1.8.7/lib \
-DParMETIS_INCLUDE_DIRS=/projects/install/rhel6-x86_64/sems/tpl/parmetis/4.0.3/gcc/4.4.7/openmpi/1.8.7/include \
-DTPL_ENABLE_MPI:BOOL=ON \
-DMPI_BASE_DIR:PATH=/projects/install/rhel6-x86_64/sems/compiler/gcc/4.4.7/openmpi/1.8.7 \
-DEpetraExt_BUILD_BTF=O \
-DTeuchos_ENABLE_COMPLEX=ON \
-DNOX_ENABLE_LOCA=ON \
-DTPL_ENABLE_ParMETIS:BOOL=ON \
-DTrilinos_ENABLE_ALL_OPTIONAL_PACKAGES=OFF \
-DTrilinos_ENABLE_ALL_PACKAGES:BOOL=OFF \
-DTrilinos_ENABLE_Zoltan:BOOL=ON \
$EXTRA_ARGS \
../Trilinos

It is possible, even likely, these errors have something to do with the version of parmetis I am using, the specific installation of parmetis I am using, or random error on my part. Please advise.

**Comment by kddevin** [comment]
I'll take a look, Jim.
Which SEMS modules do you load?  (Are the modules listed in CDASH?)
What's your timeframe for getting this working?
The tests run without problem, but don't get our accepted answers.  This can happen if the system's random number generator is different from our test system, as ParMETIS uses the system's random number generator.  I'll check for that if I can reproduce the problem.
Karen

**Comment by jwillenbring** [comment]
module load cmake/2.8.12
module load gcc/4.4.7/openmpi/1.8.7
module load parmetis/4.0.3/gcc/4.4.7/openmpi/1.8.7

In reproducing the error, I didn't actually load these modules because I had cmake in my path, and the cmake arguments took care of the rest. I would like to potentially resolve these issues prior to moving this build from experimental to nightly. If you are OK with letting the failures through, we could reevaluate that. Another option would be to turn off parmetis, but I would like to avoid that if we can. I have no specific timeline, other than wanting to secure this specific configuration (long-term, and with C++11 sneaking into packages on occasion, I see this build as important) for a group that wants it to work. What is a reasonable timeline for you? Is two or three weeks reasonable?

**Comment by kddevin** [comment]
@jwillenbring 
The SEMS ParMETIS installation uses 64-bit indices in ParMETIS, while the Zoltan tests were generated using ParMETIS with 32-bit indices.  This difference might explain why ParMETIS is returning different results to Zoltan.  Are there 32-bit ParMETIS installations in SEMS that I may test against?

**Comment by kddevin** [comment]
Jim:  I did a side-by-side comparison in my environment, using the same compilers, MPI, etc., and varying only whether 32-bit or 64-bit ParMETIS was used.  The 32-bit results match our accepted answers; the 64-bit results are reasonable but do not exactly match our accepted answers. The differences are likely in ParMETIS and, thus, out of our control.  I hesitate to store both 32-bit and 64-bit answer files in the repo.  If you can use a 32-bit SEMS build, that would solve the problem.  Let me know, though, if the users you are supporting require 64-bit.

**Comment by jwillenbring** [comment]
Karen,

I received word from uses that in this case it would be reasonable to turn off ParMetis for this test. It isn't an ideal solution, but it is acceptable, and they agree that this issue really is more of a platform dependent ParMetis issue. Thanks for looking into this. I will close the ticket.

**Comment by kddevin** [comment]
@jwillenbring 
In case you care (although not caring is fine, too :) :  the Zoltan tests with ParMETIS now pass regardless of whether ParMETIS is built with 32-bit or 64-bit indices.  See #475

**Comment by jwillenbring** [comment]
Thanks, @kddevin .
