### ISSUE TITLE
Trilinos CDash site not sending out emails since 1/30/2018?

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#2255]
**CC:** @trilinos/framework, @zackgalbreath 

## Description

It looks like the Trilinos CDash site is no longer sending out any CDash error emails.  I have not gotten a CDash error email since 1/30/2018.  The standard CI build shown at:

* https://testing.sandia.gov/cdash/index.php?project=Trilinos&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=66&value1=-MPI_RELEASE_DEBUG_SHARED_PT_CI&field2=groupname&compare2=61&value2=Continuous&field3=buildstarttime&compare3=84&value3=now

has been falling since 20:03 UTC 2/15/2018.  Yet, I did not receive any CDash error emails for these failures.

This is also breaking all of the “Clean” builds as shown at:

* https://testing.sandia.gov/cdash/index.php?project=Trilinos&date=2018-02-18

This likely also explains why the PR testing is failing right now (but we can’t see why).

Is there a way to verify that the CDash site attempted to send out CDash error emails?  I looked at the CDash log file and I could not find any records of any emails getting sent out.

**Comment by zackgalbreath** [comment]
> Is there a way to verify that the CDash site attempted to send out CDash error emails? I looked at the CDash log file and I could not find any records of any emails getting sent out.

I didn't see anything useful there either.  Here's some other spots to check for clues: 

* /php_error_log/php_errors.log
* /var/log/syslog
* /var/log/httpd/error.log

(I don't have read access to these files)

**Comment by jwillenbring** [comment]
I pinged John P and he replied with:

> There were some stuck email messages.  I restarted sendmail, and it look like the mail is flowing.  Please let me know if the problem comes back.

I then got a huge flood of emails.

**Comment by bartlettroscoe** [comment]
@zackgalbreath,

Is there some way to get CDash (perhaps in our upgraded version) to provide a single log entry line for each email perhaps just with the email address the email is sent too and the email summary line.  That would tell us a lot I suspect.

**Comment by bartlettroscoe** [comment]
FYI: I added issue:

* https://gitlab.kitware.com/snl/project-1/issues/53

to make sure that future versions of CDash that we use will log CDash emails (at least one short line per email).  This will help to make sure that CDash is sending out the emails that it should.

I am now closing this issue.
