### ISSUE TITLE
Ifpack2::ILUT prints to std::cerr on zero pivot

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#2256]
On encountering a zero pivot, `Ifpack2::ILUT::compute` prints directly to `std::cerr`.  This is bad because it could print on all processes, or at least on all processes that encounter a zero pivot.

https://github.com/trilinos/Trilinos/blob/8c36a5b95fcd369ef4b98a3a3030e6cf9679fd27/packages/ifpack2/src/Ifpack2_ILUT_def.hpp#L729

@trilinos/ifpack2 

Suggested fix: Collect local error messages, and return them via a method that users could call after `compute` finishes.  We don't want to force synchronization in order to detect and print errors globally.

**Comment by mhoemmen** [comment]
@tjfulle this comes from your e-mail today :)

**Comment by aprokop** [comment]
Should this not be a user's choice through a parameter? I.e., make some parameter ("fix zero pivots"?) true by default and allow a user to set it. If it's false, throw.

**Comment by mhoemmen** [comment]
@aprokop "Throw" is bad because it's a local phenomenon.  ILUT always fixes zero pivots if you give it threshold parameters.  In fact, I'm surprised that the threshold parameters aren't nonzero by default.

**Comment by aprokop** [comment]
> ILUT always fixes zero pivots if you give it threshold parameters.

Why? This it not a textbook ILUT, is it?

**Comment by mhoemmen** [comment]
@aprokop Trilinos' ILUT is definitely not the same as Saad's ILUT; the parameters don't mean the same things.  "Fixes zero pivot" means "replaces with some value."

**Comment by mhoemmen** [comment]
This is still broken in master: https://github.com/trilinos/Trilinos/blob/a6d3274e2f75876e7d682e34f92b12dded96f014/packages/ifpack2/src/Ifpack2_ILUT_def.hpp#L645

**Comment by mhoemmen** [comment]
@jhux2
