### ISSUE TITLE
cuda build of Kokkos_Sparse_MV_impl_spmv takes 25 minutes for 1 file.

### ISSUE THREAD

**Issue by bathmatt** [trilinos/Trilinos#226]
Can we split up the build of this file?  This is all on hansen with 
-bash-4.1$ module load devpack/openmpi/1.10.0/gcc/4.8.4/cuda/7.5.18

The build of 
[ 66%] Building CXX object packages/tpetra/kernels/src/CMakeFiles/tpetrakernels.dir/impl/Kokkos_Sparse_MV_impl_spmv_Cuda.cpp.o
[ 66%] Building CXX object packages/tpetra/kernels/src/CMakeFiles/tpetrakernels.dir/impl/Kokkos_Sparse_MV_impl_spmv_Serial.cpp.o

is very slow under cuda/debug (not -G though).  By very slow, 25 minutes.

-bash-4.1$ time make -j
[  0%] Built target kokkoscore
[  0%] Built target kokkosalgorithms
[  0%] Built target kokkoscontainers
[ 33%] Built target teuchoscore
[ 66%] Built target teuchosparameterlist
[ 66%] Built target teuchoscomm
[ 66%] Building CXX object packages/tpetra/kernels/src/CMakeFiles/tpetrakernels.dir/impl/Kokkos_Sparse_MV_impl_spmv_Cuda.cpp.o
[ 66%] Building CXX object packages/tpetra/kernels/src/CMakeFiles/tpetrakernels.dir/impl/Kokkos_Sparse_MV_impl_spmv_Serial.cpp.o
[ 66%] Linking CXX static library libtpetrakernels.a
[100%] Built target tpetrakernels

real	24m16.402s
user	29m35.614s
sys	0m58.005s

**Comment by bathmatt** [comment]
@mhoemmen Adding Mark.

**Comment by bathmatt** [comment]
Here are the built file sizes..  Big but not huge

154M Kokkos_Sparse_MV_impl_spmv_Cuda.cpp.o  
108K Kokkos_Sparse_MV_impl_spmv_OpenMP.cpp.o   
55M Kokkos_Sparse_MV_impl_spmv_Serial.cpp.o  
108K Kokkos_Sparse_MV_impl_spmv_Threads.cpp.o

**Comment by srajama1** [comment]
If I remember correctly, @crtrott has a plan to make this file build faster. Adding @mndevec as well.

**Comment by nmhamster** [comment]
We are also working on making the file system and builds more efficient on Hansen. This is taking a while due to hardware compatibility problems but .. the templating and build systems can do a lot to help here.

**Comment by mhoemmen** [comment]
Plan is to break up these files more.  Also, @crtrott mentioned something a while back about extra instantiations (that we don't need) in these files.  I think we can strip those out first, then work on breaking up the instantiations into more files, using either Tpetra's approach (hand-rolled CMake logic to generate files) or MueLu's approach (more script-y).

**Comment by etphipp** [comment]
There used to be a KOKKOS_FAST_COMPILE option for this code.  Does that option still exist?

-Eric

On Mar 17, 2016, at 7:15 PM, Mark Hoemmen <notifications@github.com<mailto:notifications@github.com>> wrote:


Plan is to break up these files more. Also, @crtrott<https://github.com/crtrott> mentioned something a while back about extra instantiations (that we don't need) in these files. I think we can strip those out first, then work on breaking up the instantiations into more files, using either Tpetra's approach (hand-rolled CMake logic to generate files) or MueLu's approach (more script-y).

-

**Comment by crtrott** [comment]
While it still exists it doesn't pass all tests currently. So something is broken due to lack of testing.

**Comment by mhoemmen** [comment]
I'm working on this.  Will post some patches tonight or early tomorrow.

**Comment by mhoemmen** [comment]
This bug depends on #231.  #232 is in the same spirit, though fixing it would only improve Tpetra build time, not KokkosKernels build time.

**Comment by mhoemmen** [comment]
This is subsumed in #340.

**Comment by mhoemmen** [comment]
I'm closing this because it is subsumed in #340.  Fixes for #231 and #232 likely helped.

**Comment by srajama1** [comment]
@bathmatt : Can you confirm fixes for #231 and #232 helped you ?

**Comment by bathmatt** [comment]
It is down to 6.5 minutes, definite progress.

On Wed, May 18, 2016 at 4:51 AM, Siva Rajamanickam <notifications@github.com

**Comment by srajama1** [comment]
Thanks !

**Comment by mhoemmen** [comment]
YAY :-D
