### ISSUE TITLE
Write debug data to files in advanced XML mode

### ISSUE THREAD

**Issue by mayrmt** [trilinos/Trilinos#2260]
@trilinos/muelu 

## Expectations
Allow to write "Nullspace" and "Coordinates" to files in the advanced xml input deck (as it is possible for the simple xml input deck)

## Current Behavior
The advanced xml input deck allows to write "Matrices", "Restrictors", and "Prolongators" only.

## Motivation and Context
Catching up with capabilities of simple xml input deck...

## Possible Solution
Add code to process input parameter list in ```MueLu_ParameterListInterpreter```

**Comment by mayrmt** [comment]
Writing data to files via the simple xml input deck requires a xml sublist like

```
<ParameterList name="export data">
  <Parameter name="A" type="string" value="{0,1}"/>
  <Parameter name="P" type="string" value="{0,1}"/>
  <Parameter name="R" type="string" value="{0,1}"/>
</ParameterList>
```
while the advanced xml deck sublist uses different names
```
<ParameterList name="DataToWrite">
  <Parameter name="Matrices" type="string" value="{0,1}"/>
  <Parameter name="Prolongators" type="string" value="{0,1}"/>
  <Parameter name="Restrictors" type="string" value="{0,1}"/>
</ParameterList>
```

@trilinos/muelu Are there any opinions on unifying these names?

**Comment by aprokop** [comment]
I think this is certainly a good idea. Regarding your question about the difference in names, this is mostly historical. `export data` has similar style to the rest of the easy decks, and most parameters there were from ML, meaning lower cases and spaces.

**Comment by mayrmt** [comment]
I was more thinking about the names "A" vs. "Matrices", "R" vs. "Restrictors", and "P" vs. "Prolongators". Using the single letters would be consistent with the rest of MueLu, though spelling them out might be more descriptive.

**Comment by aprokop** [comment]
Hmm, I see. I think we could unify those. Have to do it carefully, though, and deprecate the old names (whichever ones we choose). I'm definitely not a fan of "Matrices". At least, call them "Level matrices" or "Level operators".

**Comment by mayrmt** [comment]
I was thinking of using "A", "R", and "P" in the advanced xml input deck as well since we use these letters throughout MueLu all the time.

**Comment by jhux2** [comment]
@mayrmt I'm fine with either way.

**Comment by mayrmt** [comment]
I'll change the parameter names to "A", "R", and "P" and issue a warning about deprecation of the old parameter names.

**Comment by mayrmt** [comment]
There are three xml files 
- ```muelu/test/scaling/conchas_milestone_zoltan.xml```
- ```muelu/test/scaling/conchas_milestone_zoltan2.xml```
- ```muelu/test/scaling/conchas_milestone_zoltan2_complex.xml```
that refer to the parameter list ```DataToWrite```, however it is commented in each file. Should I remove or update the ```DataToWrite``` sections in these files to avoid confusion in case, somebody looks at them as a reference?

**Comment by mayrmt** [comment]
Has been addressed in PR #2261. Closing.

**Comment by mayrmt** [comment]
I'm reopening this issue since there is still something wrong when trying to write data on coarser levels.

**Comment by mayrmt** [comment]
Changes have been reverted. Closing.
