### ISSUE TITLE
MueLu: identify duplicates at region interfaces on coarse levels

### ISSUE THREAD

**Issue by mayrmt** [trilinos/Trilinos#2262]
## Expectations
We want to identify pairs of GIDs on coarse levels that refer to the same point on region interfaces.

## Current Behavior
We do not identify pairs of GIDs, but rather rely on knowing the coarsening of both regions attached to an interface, so we can figure out the mapping by integer arithmetic.

## Motivation and Context
To enable transferring vectors from regional to composite layout (and vice versa), we need to identify at region interfaces which GIDs in the region layout refer to which GID in the composite layout. This identification must not rely on _a priori_ knowledge and assumptions about the coarsening. 

## Definition of Done
- [x] recursively identify interface GIDs on coarse levels
- [x] form coarse level maps in composite, quasiRegional and regional layout
- [x] allow for multi-level case with recursive V-cycle implementation

## Possible Solution
1. Inject coarse GIDs from region layout into fine level.
2. Move to composite layout with a combineMode _Minimum_.
3. Identify mapping by looking at aggregates

## Environment
I'll work on this in branch ```mayrmt-regions-multigrid``` in [my fork](https://github.com/mayrmt/Trilinos) and will share via a pull request.

## Interested Parties
@lucbv @rstumin

**Comment by lucbv** [comment]
@mayrmt, you should be able to use the structured aggregation now. It works in coupled mode only at the moment.
I will start working on the uncoupled mode soon (hopefully tomorrow), I do no think that it should be too long to implement although a bug can always block things...
I'll keep you posted on my progress.

**Comment by mayrmt** [comment]
@lucbv, I think I have to wait for the uncoupled version to actually be able to use it. The coupled version will not recognize the region interfaces. Though, for my current task, I'm fine with the uncoupled 'unstructured' aggregation.

**Comment by mayrmt** [comment]
Status update: Using aggregates and existing composite-to-region and region-to-composite mappings on the fine level, I can generated composite, quasiRegional, and regional maps on the coarse grid of a two-level-problem.

Next steps: restructure data structures to allow for multilevel case and recursively building coarse level maps

**Comment by mayrmt** [comment]
@lucbv @rstumin I have a working recursive implentation of a V-cycle for one-dimensional problems with perfect region-to-processor mapping.

To go to two-dimensional problems, we need the uncoupled structured aggregation (#2230).

**Comment by mayrmt** [comment]
Currently, we have this imitation: The number of nodes per region needs to be 
    numNodesPerRegion = 3^{L-1} * k + 1
with L ... number of levels, k = 1,2,3,...
```mk1DRegionFile.m``` provides some utilities to create caseFiles that respect this rule.

I suppose that this limitation is due to using the smothed-aggregation tentative prolongator for regions instead of using a region-tailored prolongator. I hope this become less of a problem as soon as we incorporate changes from #2230, @lucbv.

**Comment by mayrmt** [comment]
Done for one-dimensional problems. Closing. For two-dimensional problems, see #2305.

**Comment by mayrmt** [comment]
Reopening to explore a different strategy porposed by @lucbv.

Idea: We know all GIDs of fine-level interface nodes and can use them to identify corresponding coarse GIDs of interface nodes by looking at the prolongator: Look at row fineGID and find column index of non-zero entry, which gives the coarseGID. This gives pairs of <fineGID,coarseGID> at the interface, which can then be used identify the duplicated coarse GIDs.

**Comment by mayrmt** [comment]
@rstumin I included @lucbv's uncoupled structured aggregation. It seems to work for 1D problems with 2 levels. 
- The restriction on the number of levels is due to limitations in my code. That's not related to the uncoupled structured aggregation.
- Using the uncoupled structured aggregation for 2D problems is the next step. Though, I'll have a couple of questions, in particular, are there any requirements on the matrix layout/structure/numbering scheme?

My current code can be found at [my Trilinos fork](https://github.com/mayrmt/Trilinos/tree/mayrmt-regions-multigrid).

I'll continue to work on this next week.

**Comment by mayrmt** [comment]
Using @lucbv's idea of a prolongator-based strategy to identify interface pairs on the coarse level, we can now
- remove the aggregate-based approach
- revert changes to central MueLu routines introduced in #9d40e20a1f70ad80bae8faae88a0135a43c5515a

I'll clean this up, so we get ready to merge back to develop.

**Comment by mayrmt** [comment]
Closing this issue as this has been addressed in PR #2708.
