### ISSUE TITLE
MueLu: why is printing a Level protected with compile-time guard?

### ISSUE THREAD

**Issue by jhux2** [trilinos/Trilinos#2263]
Is there a good reason that printing a level is protected by a compile-time flag?

in `MueLu_VerbosityLevel.hpp`:
```
  void Level::print(std::ostream& out, const VerbLevel verbLevel) const {
    if (!(verbLevel & Debug))
      return; 
```

`Debug` is part of `Extreme` verbosity only if `HAVE_MUELU_DEBUG` is defined.

@trilinos/muelu

**Comment by aprokop** [comment]
I don't recall exactly why I put it in. But this is a developer only print as it prints the internal structure of the levels. If a user call `Hierarchy::print` (and I don't know why that is exposed) we don't want to show our dirty laundry.

**Comment by jhux2** [comment]
@aprokop Would you (or anyone else) object if I were to change the verbosity check to Extreme?  Right now, getting the level information requires recompilation.

**Comment by aprokop** [comment]
I don't really care. Is recompilation required only because we don't support `debug` as an input deck parameter? You could also add an extra hidden parameter to the input deck to output this information.

**Comment by jhux2** [comment]
@aprokop Thanks, you've answered my question.

**Comment by lucbv** [comment]
@jhux, sorry for this late comment but couldn't we trigger this thing with an environment variable, this way you can still turn it on/off but without worrying about recompiling.

**Comment by mhoemmen** [comment]
@lucbv I edited your comment so poor "jhux" doesn't get notifications meant for @jhux2 :-) 

If you're going for an environment variable approach, would you consider `MUELU_DEBUG` / `MUELU_VERBOSE`?  It could be nice to be consistent with these.

**Comment by lucbv** [comment]
@mhoemmen thanks for that catch, I liked debugging in Tpetra using the environment variable, I think it makes more sense than recompiling, especially if you can come up with a system that is flexible enough to allow partial print outs depending on the issue at hand.

**Comment by aprokop** [comment]
Environment variables are nice until you try to reproduce your results and/or compare two different runs.

**Comment by mhoemmen** [comment]
Environment variables are nice for debugging when you can't recompile ;-)

The debate isn't so much about environment variables, it's about run-time vs. compile-time options.  For some coarse-grained printing option, I don't see why we need to recompile all of Trilinos to change it.
