### ISSUE TITLE
MueLu: forcing MueLu to keep data for export to files

### ISSUE THREAD

**Issue by mayrmt** [trilinos/Trilinos#2268]
@trilinos/muelu 

## Current Behavior
The sublist ```export data``` in the simple XML interface forces MueLu to keep data for printing. However, when looking at the content of a single ```MueLu::Level```, I'm confused by multiple instances of data that has been kept.

## Motivation and Context
The easy XML input allows to fill the parameter list
```
<ParameterList name="export data">
  <Parameter name="A" type="string" value="{0,1}"/>
  <Parameter name="R" type="string" value="{0,1}"/>
  <Parameter name="P" type="string" value="{0,1}"/>
  <Parameter name="Nullspace" type="string" value="{0,1,2}"/>
  <Parameter name="Coordinates" type="string" value="{0,1,2}"/>
</ParameterList>
```
which forces MueLu to keep certain data and to print this data to files. When selecting "A" and "Nullspace" in ```export data```, a level contains this data:
```
LevelID = 0                     
  data name             gen. factory addr.  req    keep   type             data            req'd by            
  --------------------  ------------------  -----  -----  ---------------  --------------  --------------------
  A                     0x266dda0           0      Keep   unknown          not available                       
  Nullspace             0x266ec20           0      Keep   unknown          not available                       
  A                     NoFactory           0      User   Matrix           available                           
  Nullspace             NoFactory           0      User   Vector           available                           
  PostSmoother          NoFactory           0      Final  SmootherBase     available                           
  PreSmoother           NoFactory           0      Final  SmootherBase     available   
```

```A``` and ```Nullspace``` occur twice, however with different generating factories. The ones generated by ```NoFactory``` are marked as ```available``` while the ones generated by ```0x266dda0``` and ```0x266ec20``` are ```not available```.

Why is that? Which instance of the ```Nullspace``` can be accessed after ```SetupHierarchy()``` has been called?

My motivation to look at this is that I want to force MueLu to keep the aggregates around since I need them after the setup of the hierarchy (#2262). I'm looking at the ```Nullspace``` only to understand the concept of keeping stuff.

## Related Issues
* Blocks #2262 
* Related to #2260

**Comment by lucbv** [comment]
@mayrmt it is likely that the `A` generated by `NoFactory` is the `A` passed in by the user to create the hierarchy, the other `A` could be generated and used internally by MueLu during the creation of the next coarse level.

**Comment by mayrmt** [comment]
@lucbv That sounds reasonable. I verified that assumption with the ```Nullspace```. When I don't pass in the nullspace on the fine level, such that MueLu generates it itself, it is listed only once on each level.

**Comment by tawiesn** [comment]
@mayrmt Lucbv is right. Introducing a flexible keep mechanism in the extended xml input deck was always on my list. The main problem with the existing "export data" list is that there is no way to specify which ´A´ (that is "

**Comment by mayrmt** [comment]
> An alternative idea could be to get rid of the export data struct and introduce a general boolean keep property in the xml block for each factory (similar to the name property that you need for each factory block).

This sounds to be suitable for the extended input deck, where I have one xml-block per factory.

> why do you want/need to keep data? Just for debugging purposes?

@tawiesn, I need the aggregates in a prototyping code outside of MueLu, so I need to keep them to be able to access them after SetupHierarchy().

**Comment by tawiesn** [comment]
> 

@tawiesn,  I need the aggregates in a prototyping code outside of MueLu, so I need  to keep them to be able to access them after SetupHierarchy().
--

**Comment by mayrmt** [comment]
I have a standalone driver, that builds a hierarchy. I'd like to create and setup the hierarchy and then loop over the hierarchy and access the aggregates on each level.

Though, I think I also could write them to a file and read them in again.

**Comment by jhux2** [comment]
> it is likely that the A generated by NoFactory is the A passed in by the user to create the hierarchy, the other A could be generated and used internally by MueLu during the creation of the next coarse level.

@lucbv We saw two instances of `A` on level 0.  If I remember correctly, there's nothing in @mayrmt's driver that should trigger a second instance of `A` there.

**Comment by tawiesn** [comment]
@jhux2 @lucbv Are you calling Keep for the "A" generated by RAPFactory? This would explain what you observed: 0x266dda0 was the RAPFactory. You called Keep, that is, if A would have been generated by RAPFactory (0x266dda0) on the finest level it would have been available. But, of course, it is not created on level zero. That is, why you see the line, that A "would" be kept, but it is not available. The "A" generated by NoFactory is the A provided by the user through the input deck.

**Comment by jhux2** [comment]
> Are you calling Keep for the "A" generated by RAPFactory? This would explain what you observed: 0x266dda0 was the RAPFactory. You called Keep, that is, if A would have been generated by RAPFactory (0x266dda0) on the finest level it would have been available. But, of course, it is not created on level zero. That is, why you see the line, that A "would" be kept, but it is not available. The "A" generated by NoFactory is the A provided by the user through the input deck.

@tawiesn Thank you for the explanation!  @mayrmt is not asking that A be kept on level 0.  As I recall, the A that he provided was available, but the other one was not.   This was really just a side observation while trying to keep the aggregates.

**Comment by mayrmt** [comment]
> @mayrmt is not asking that A be kept on level 0. As I recall, the A that he provided was available, but the other one was not. This was really just a side observation while trying to keep the aggregates.

I double-checked that:
- If not keeping the matrix on the fine level, then there's only one ```A``` provided by the ```User``` on the fine level.
- If keeping the matrix on the fine level, then there are two ```A```'s
  - one provided by the ```User``` with ```data``` being ```available``` 
  - one generated by ```0x266dda0``` with ```data``` being ```not available```.

**Comment by tawiesn** [comment]
@mayrmt I would need to double-check the code of the Keep mechanism in the extended input deck. But i'm very sure, that the 0x266dda0 in your case was the RAPFactory. That is the only factory which produces A (unless you do something very special with different A-Factories, such as SubBlockAFactory. But then you probably would see more dangling A's). On the finest level we would not need an RAPFactory, but it is the default A factory and when you mark the variable A to be kept (without providing an A Factory, you should get an instance of RAPFactory). If you don't keep A on the finest level there is no A factory and even if there would be one, it would not show up in the list as there is no A kept or requested on the finest level.

What do you see on the coarser levels? On the coarser levels we have always a RAPFactory instance (only one for all levels), but the result "A" of the RAPFactory is automatically mapped to be generated by NoFactory. This is the case for the variables "A", "P" and "R" as those are special in the sense that we need them always during the iteration phase through all multigrid levels in the V-cycle. I do not remember the details, but i guess that the "Export data" functionality in the extended XML format only supports "A", "P" and "R" generated by the default factories (or NoFactory) as they are always guaranteed to exist. What is missing? For the most general "Export data" functionality we would need to be able to specify which data to keep on a factory base. This would be necessary for all variables (except "A", "P" and "R" generated by the default and/or NoFactory).

**Comment by lucbv** [comment]
@mayrmt are you trying to keep the aggregates in order to compute the mapping of interface GID pairs from fine to coarse level?

**Comment by mayrmt** [comment]
@lucbv Yes, exactly for that (cf. #2262)

**Comment by lucbv** [comment]
@mayrmt then why not use the prolongator for this part? It might be easier to extract since it does not get destroyed after setup.

**Comment by mayrmt** [comment]
@lucbv, from the prolongator, I can extract information about which fine points belongs to a certain aggregate/coarse point on the coarser level --- so its a mapping of a bunch of fine points (finePoint1, finePoint2, ..., finePointN) to a single coarsePoint). Though, I cannot identify the particular finePoint that is the injection of the coarse point on the fine level, i.e. the root point of the aggregate on the fine level. I was thinking to do that using the ```IsRoot()``` method of the aggregates. That's why I need the aggregates.

**Comment by lucbv** [comment]
I am not sure that the root node is in anyway injected, I think it get the same treatment as every other point. I think that isRoot is mainly used to plot aggregates.

**Comment by tawiesn** [comment]
@mayrmt @lucbv is correct. Assuming that you are using the standard TentativePFactory, root nodes are not injected. We use root nodes within the Aggregation routine only for administrative purposes. They have absolute no meaning for the tentative prolongation operator (or the smoothed ones).

You would need to write a new prolongation factory which does something like injection for a root node and builds the weights for the remaining entries corresponding to the non-root nodes in the prolongator. That sounds more like classical AMG or geometric multigrid rather than aggregation-based AMG, right?
