### ISSUE TITLE
Teuchos: Add CMake test to set HAVE_TEUCHOS_KOKKOS_PROFILING

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#2273]
See #2271, in particular my comment here: https://github.com/trilinos/Trilinos/pull/2272#issuecomment-367517327

Teuchos actually does define a CMake option (`Teuchos_KOKKOS_PROFILING`) that controls `HAVE_TEUCHOS_KOKKOS_PROFILING`, but the default value of the CMake option is `OFF`.  It doesn't check Kokkos' CMake options at all.  We need Teuchos to enable this automatically by default, if the Kokkos package is enabled and if Kokkos profiling is enabled.

@trilinos/teuchos 

## Motivation and Context

Lots of Trilinos packages use Teuchos timers.  We want those packages to get the advantage of Kokkos profiling, without needing to change their existing Teuchos timer infrastructure.  We also want this capability to exist by default; users shouldn't have to set nondefault CMake options to get it.

## Definition of Done

- [ ] Make Teuchos' CMake logic enable `Teuchos_KOKKOS_PROFILING` by default, if the Kokkos package is enabled and if Kokkos profiling is enabled.
- [ ] Test that the Teuchos code that uses Kokkos profiling hooks actually builds and runs correctly, since it hasn't been building or running by default.

## Related Issues
* Related to #2271

**Comment by bartlettroscoe** [comment]
Seems like this should be a one-line change in a Teuchos CMakeLists.txt file.  No?

**Comment by mhoemmen** [comment]
@bartlettroscoe wrote:
> Seems like this should be a one-line change in a Teuchos CMakeLists.txt file. No?

2 lines (need `ASSERT_DEFINED(KOKKOS_ENABLE_PROFILING)` too) ;-)

**Comment by mhoemmen** [comment]
PR #2314 has a fix for this issue.

**Comment by mhoemmen** [comment]
Fixed now in develop, via PR #2314.
