### ISSUE TITLE
Test MueLu_UnitTestsEpetra_MPI_1 failing on ATDM builds on shiller

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#2274]
**CC:** @trilinos/muelu 

## Description

The test `MueLu_UnitTestsEpetra_MPI_1` is showing several failed ATDM build of Trilinos as shown at:

* https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&date=2018-02-22&filtercount=2&showfilters=1&filtercombine=and&field1=testname&compare1=65&value1=MueLu_UnitTestsEpetra&field2=status&compare2=61&value2=Failed

which currently shows:

| Site | Build Name | Test Name | Status | Time | Details | Build Time |
|------|------------|-----------|--------|------|---------|------------|
| hansen/shiller | Trilinos-atdm-hansen-shiller-gnu-debug-serial | MueLu_UnitTestsEpetra_MPI_1 | Failed | 15.75 | Completed (Failed) | 2018-02-22T08:06:46 UTC |
| ascic144 | Linux-intel-17.0.1-MPI_Release_intel_17.0.1_openmpi_1.8.7_DEV | MueLu_UnitTestsEpetra_MPI_1 | Failed | 6.22 | Completed (Failed) | 2018-02-22T08:42:53 UTC |
| hansen/shiller | Trilinos-atdm-hansen-shiller-gnu-opt-serial | MueLu_UnitTestsEpetra_MPI_1 | Failed | 5.91 | Completed (Failed) | 2018-02-22T09:41:15 UTC |
| hansen/shiller | Trilinos-atdm-hansen-shiller-intel-debug-serial | MueLu_UnitTestsEpetra_MPI_1 | Failed | 21.81 | Completed (Failed) | 2018-02-22T11:36:23 UTC |

Looking at these failing tests it looks like they are due to a bad floating-point equality comparison like shown at:

* https://testing.sandia.gov/cdash/testDetails.php?test=44832397&build=3400210

which shows:

```
 diagVec->norm1() = 2.50000000000000071e+01 == diagVec->getGlobalLength() = 25 : FAILED ==> /home/jenkins/hansen/workspace/Trilinos-atdm-hansen-shiller-gnu-debug-serial/SRC_AND_BUILD/Trilinos/packages/muelu/test/unit_tests/StructuredAggregationFactory.cpp:339
```

In general, you can't do an equality comparison of computed floating-point numbers.  You can't expect every digit to match.  Instead please use [TEST_FLOATING_EQUALITY](https://trilinos.org/docs/dev/packages/teuchos/doc/html/group__Teuchos__UnitTestAssertMacros__grp.html#gaa60899c51ae9ffa9e76ca5cb41d7a0eb).

## Steps to Reproduce

Instructions to reproduce this on hansen or shiller can be found at:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md

**Comment by lucbv** [comment]
@bartlettroscoe I looked at the tests this morning and the changes made to the unit test seem to have fixed this issue.

**Comment by bartlettroscoe** [comment]
> I looked at the tests this morning and the changes made to the unit test seem to have fixed this issue.

@lucbv, thanks.  Let's keep this open and put it in review until we confirm it when the automated builds run again.

**Comment by bartlettroscoe** [comment]
As shown in the CDash query:

* https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&date=2018-02-28&limit=0&filtercount=1&showfilters=1&field1=testname&compare1=61&value1=MueLu_UnitTestsEpetra_MPI_1

this test passed in all of the build (except Linux-CLANG-3.8.1-OPENMPI_1.10.1_RELEASE_DEV_MueLu_clang). In particular, the test passed for all of the current ATDM builds:

| Site | Build Name | Test Name | Status | Time | Details | Build Time |
|------|------------|-----------|--------|------|---------|------------|
| hansen/shiller | Trilinos-atdm-hansen-shiller-gnu-debug-openmp | MueLu_UnitTestsEpetra_MPI_1 | Passed | 10.5 | Completed | 2018-02-28T14:09:17 UTC |
| hansen/shiller | Trilinos-atdm-hansen-shiller-gnu-debug-serial | MueLu_UnitTestsEpetra_MPI_1 | Passed | 10.81 | Completed | 2018-02-28T08:08:05 UTC |
| hansen/shiller | Trilinos-atdm-hansen-shiller-gnu-opt-openmp | MueLu_UnitTestsEpetra_MPI_1 | Passed | 4.47 | Completed | 2018-02-28T20:50:02 UTC |
| hansen/shiller | Trilinos-atdm-hansen-shiller-gnu-opt-serial | MueLu_UnitTestsEpetra_MPI_1 | Passed | 3.53 | Completed | 2018-02-28T09:45:30 UTC |
| hansen/shiller | Trilinos-atdm-hansen-shiller-intel-debug-openmp | MueLu_UnitTestsEpetra_MPI_1 | Passed | 4.76 | Completed | 2018-02-28T18:21:49 UTC |
| hansen/shiller | Trilinos-atdm-hansen-shiller-intel-debug-serial | MueLu_UnitTestsEpetra_MPI_1 | Passed | 3.98 | Completed | 2018-02-28T12:03:18 UTC |
| hansen/shiller | Trilinos-atdm-hansen-shiller-intel-opt-openmp | MueLu_UnitTestsEpetra_MPI_1 | Passed | 4.14 | Completed | 2018-02-28T18:57:49 UTC |
| hansen/shiller | Trilinos-atdm-hansen-shiller-intel-opt-serial | MueLu_UnitTestsEpetra_MPI_1 | Passed | 3.82 | Completed | 2018-02-28T16:33:01 UTC |
| sems-rhel6 | Trilinos-atdm-sems-gcc-7-2-0 | MueLu_UnitTestsEpetra_MPI_1 | Passed | 10.48 | Completed | 2018-02-28T15:28:38 UTC |

I am closing as complete.

Thanks for fixing this @lucbv!
