### ISSUE TITLE
Build error in MueLu unit tests

### ISSUE THREAD

**Issue by ikalash** [trilinos/Trilinos#2294]
In the Albany CDash, I noticed Trilinos failed to build on one platform, Cori, due to MueLu tests: 

https://my.cdash.org/viewBuildError.php?buildid=1373917

I can just turn this off for Albany b/c we do not really need them, but I wanted to report the problem.

@trilinos/muelu

**Comment by jhux2** [comment]
@ikalash I don't see any information indicating what happened.  Do you have local access to the test machine to see if there might be more helpful output?  I suspect it might be related to this commit 48c2daa6.

**Comment by ikalash** [comment]
@jhux: You will find the detailed log with the error attached.  The configure options can be found here: https://my.cdash.org/viewConfigure.php?buildid=1373917 .  This is on the NERSC C
[muelu_err.txt](https://github.com/trilinos/Trilinos/files/1753421/muelu_err.txt)
ori machine (similar to Edison).

**Comment by jhux2** [comment]
@ikalash Based on the error log attached to this issue, I believe this was fixed by the same patch that fixed #2340.  If you still see problems, please reopen.

**Comment by ikalash** [comment]
Sounds good.  Will do.
