### ISSUE TITLE
Can the checkin script be used to test/push a branch to fork of Trilinos

### ISSUE THREAD

**Issue by jhux2** [trilinos/Trilinos#2295]
Question: Can the checkin script be used to test and push a branch on a fork of Trilinos, and if so, what's the procedure for setting this up?

__Context__
I would like to use the checkin script to test changes in a local branch within my fork of Trilinos.  If all tests pass, ideally the script would then automatically push the branch to my fork.   After that, I would issue a pull request against trilinos/Trilinos.

@trilinos/framework @bartlettroscoe

**Comment by bartlettroscoe** [comment]
> Can the checkin script be used to test and push a branch on a fork of Trilinos, and if so, what's the procedure for setting this up?

The simple answer is yes.  It is just that you might need to write a little script to call the checkin-test-sems.sh script in this case.  I can write up a little wiki howto on the Trilinos GitHub wiki if you would be willing to review it. 

Sound good?

**Comment by lucbv** [comment]
@jhux2, I think that if your local branch is already tracking a remote branch on your personal fork then it probably does what you want.
@bartlettroscoe: it would be nice to have the checkin script automatically create the remote branch on the fork when asked to do `--push`, maybe with a flag like `--push-upstream`?
