### ISSUE TITLE
Tpetra::MatrixMatrix::jacobi_A_B_newmatrix_LowThreadGustavsonKernel assumes POD scalar types

### ISSUE THREAD

**Issue by etphipp** [trilinos/Trilinos#2301]
The OpenMP-specific Tpetra::MatrixMatrix::jacobi_A_B_newmatrix_LowThreadGustavsonKernel() implementation make clear POD scalar type assumptions, e.g.,
```
u_scalar_view_t Cvals((typename u_scalar_view_t::data_type)malloc(u_scalar_view_t::shmem_size(CSR_alloc)),CSR_alloc);
```
This causes a seg fault in Stokhos' Stokhos_TpetraCrsMatrixUQPCEUnitTest_OpenMP unit test that ultimately calls this function through MueLu using the UQ::PCE scalar type.  The reason is of course that the memory allocated for u_scalar_view_t is never properly initialized.

My basic question is, why do it this way?  Why not just use a simpler view allocation that already has all of the proper specializations to make sure the memory is properly initialized, e.g.,
```
scalar_view_t Cvals(Kokkos::ViewAllocateWithoutInitializing("scalar_view_t"),CSR_alloc);
```
As a spot check, I tried the changes in the attached patch on Stokhos and it appears to work fine.
[tpetra_pod_patch.txt](https://github.com/trilinos/Trilinos/files/1759318/tpetra_pod_patch.txt)

@trilinos/tpetra @trilinos/muelu @trilinos/stokhos

**Comment by etphipp** [comment]
To be clear, my question was not intended to be critical (which is does kind of sound like).  I was just wondering if there was some reason calling raw malloc was required/preferred rather than a normal view allocation.

**Comment by jhux2** [comment]
@csiefer2

**Comment by etphipp** [comment]
The code that calls this takes a parameter list and chooses this algorithm by default on OpenMP.  How would I change that in the MueLu xml file?

**Comment by csiefer2** [comment]
@etphipp Because that's the way the Kokkos guys told me to do it :)

If your patch works, feel free to push it.  I have no objection...

**Comment by etphipp** [comment]
I'm reluctant to push a change to this right before travel, so I looked into changing this test to use the MSAK implementation of Jacobi to hopefully get the test passing in the short term.  By doing a stack trace I determined I could do that by adding this parameter list to muelu's xml file:
```
<ParameterList name="matrixmatrix: kernel params">
  <Parameter name="openmp: algorithm" type="string" value="MSAK"/>
</ParameterList>
```
However that causes an exception to be thrown in the Matrix-Matrix multiply code:
```
p=0: *** Caught standard std::exception of type 'std::runtime_error' :
 
  Invalid SPGEMMAlgorithm name
```
It looks to me that both the jacobi and multiply kernels are using the same parameter list to determine their algorithm choice, and "MSAK" is not a valid choice for the multiply kernel.  Is it possible to somehow specify different parameter lists for each kernel? (MueLu's parameter list hierarchy has always been a mystery to me.)

**Comment by mndevec** [comment]
@etphipp 
Can you try giving "SPGEMM_KK_MEMSPEED" instead of MSAK?

**Comment by mndevec** [comment]
I saw the below part of the message now. This parameter would work with matrix multiply but I am not sure for jacobi part of it.

**Comment by etphipp** [comment]
Yeah, that's the problem.  The Jacobi code only accepts LTG and MSAK.

**Comment by mhoemmen** [comment]
@etphipp I'm closing, but please reopen if this is still an issue.  Thanks!
