### ISSUE TITLE
[Tpetra/Kokkos]  How to extract Kokkos::View from Tpetra Canonical Class Object (CrsMatrix/Vector)

### ISSUE THREAD

**Issue by keitat** [trilinos/Trilinos#2304]
I am looking for an example that describes a way to extract Kokkos::View from Tpetra's class objects.  This is very important for implementing some SUNDIAL's vector operations not supported by Tpetra.

(*) I think I do not belong to any member lists of Trillinos and its sub-packages. For this reason, I cannot put any tags to my submission.  Please let me in.

**Comment by aprokop** [comment]
@trilinos/tpetra

**Comment by mhoemmen** [comment]
@keitat Read the Tpetra tutorial in `Trilinos/packages/tpetra/core/example/Lesson*` first.  You can also find the text in the online (trilinos.org) Doxygen documentation.  If you have questions after that, please feel free to post them.
