### ISSUE TITLE
Teuchos Yaml Parser with duplicate names

### ISSUE THREAD

**Issue by bathmatt** [trilinos/Trilinos#2306]
Should this be allowed or should it throw an error

```
Foo:
  Bar: 
    Val:1
  Bar:
    Val:2
```

When I ask for Bar in the PL I get one entry, Val=2

Shouldn't this throw an error?
@ibaned

**Comment by ibaned** [comment]
Yea, I guess this is a lack of error checking. I'm probably calling an API in `ParameterList` that overwrites previous values. Its not technically a bug, but the code would be more user-friendly if it threw an error.

**Comment by bathmatt** [comment]
Can we add a feature req for this :).  
Thanks!  I know yaml-cpp puked..

**Comment by bathmatt** [comment]
Oh, and thanks for the new yaml cpp parser that now keeps order of entries.  The old one did not!  That allows us to have order dependent parsing

**Comment by ibaned** [comment]
@bathmatt this should be fixed now in the Trilinos develop branch, please let me know if you can confirm the fix.

**Comment by bathmatt** [comment]
Thanks!!

```
*********** Caught Exception: Begin Error Report ***********
Error Type: Generic exception type thrown
error: Parser failure at line 44 column 4 of foo.yaml
  Output:
  ^

/home/mbetten/Trilinos/Trilinos/packages/teuchos/parameterlist/src/Teuchos_YamlParser.cpp:178:

Throw number = 1

Throw test that evaluated to true: list.isParameter(name_in)

Parameter "Time Stepping" already exists in list "ANONYMOUS"


```
