### ISSUE TITLE
Component "Pike" not found

### ISSUE THREAD

**Issue by ecurtin2** [trilinos/Trilinos#2307]
Hello, 

I'm trying to build the demo in $TRILINOS_DIR/demos/buildAgainstTrilinos/build

I built trilinos by going into $TRILINOS_DIR and executing the following do-make.sh in that directory.
gcc/g++/gfortan versions are all 5.4.0

```
mkdir build
cd build
cmake -Bbuild .. \
-DCMAKE_C_COMPILER=/usr/bin/gcc \
-DCMAKE_CXX_COMPILER=/usr/bin/g++ \
-DCMAKE_Fortran_COMPILER=/usr/bin/gfortran \
-DTrilinos_ENABLE_ALL_PACKAGES=ON \
-DCMAKE_INSTALL_PATH=/home/evan/local \
-DCMAKE_INSTALL_PREFIX=/home/evan/local \

make -j3 install
wait
cd ..
```

When I try to run the do-cmake in   $TRILINOS_DIR/demos/buildAgainstTrilinos/build

```
rm CMakeCache.txt

cmake \
 -D Trilinos_PREFIX:PATH=/home/evan/local \
 -D CMAKE_VERBOSE_MAKEFILE:BOOL=ON \
 ..
```
I get the following error:

```
CMake Warning at /home/evan/local/lib/cmake/Trilinos/TrilinosConfig.cmake:158 (MESSAGE):
  Component "Pike" NOT found.
Call Stack (most recent call first):
  CMakeLists.txt:11 (FIND_PACKAGE)


CMake Error at /home/evan/local/lib/cmake/Trilinos/TrilinosConfig.cmake:221 (include):
  include could not find load file:

    /home/evan/local/lib/cmake/Trilinos/../Pike/PikeConfig.cmake
Call Stack (most recent call first):
  CMakeLists.txt:11 (FIND_PACKAGE)



Found Trilinos!  Here are the details: 
   Trilinos_DIR = /home/evan/local/lib/cmake/Trilinos
   Trilinos_VERSION = 12.13
   Trilinos_PACKAGE_LIST = Pike;TrilinosCouplings;       **[...Long list of packages]**
   Trilinos_LIBRARIES = trilinoscouplings;stokhos_muelu;  **[...Long List of packages]**
   Trilinos_INCLUDE_DIRS = /home/evan/local/include
   Trilinos_LIBRARY_DIRS = /home/evan/local/lib
   Trilinos_TPL_LIST = DLlib;X11;Matio;Netcdf;Boost;LAPACK;BLAS;Pthread
   Trilinos_TPL_INCLUDE_DIRS = 
   Trilinos_TPL_LIBRARIES = 
   Trilinos_TPL_LIBRARY_DIRS = 
   Trilinos_BUILD_SHARED_LIBS = FALSE
End of Trilinos details

-- Checking if MPI is enabled in Trilinos:
-- Checking if MPI is enabled in Trilinos: MPI NOT ENABLED
-- Looking for Epetra:
-- Looking for Epetra: -- found, compiling with -DMYAPP_EPETRA
-- Configuring incomplete, errors occurred!
See also "/home/evan/local/Trilinos/demos/buildAgainstTrilinos/build/CMakeFiles/CMakeOutput.log".


```

**Comment by mhoemmen** [comment]
@trilinos/framework

**Comment by ecurtin2** [comment]
I also tried to recompile after installing libtrilinos-pike-dev from apt (and pike the scripting language!) but the result was the same.

**Comment by mhoemmen** [comment]
Work-around: Do you need Pike?  If not, disable it for now: `Trilinos_ENABLE_Pike:BOOL=OFF`

**Comment by mhoemmen** [comment]
> I also tried to recompile after installing libtrilinos-pike-dev from apt

Oh.... don't do that if you also plan to build Pike in Trilinos.  Well, I suppose you could, but the idea is that Pike is a package in Trilinos.

**Comment by mhoemmen** [comment]
@ecurtin2 wrote:
> and pike the scripting language!

That's a different thing.  Pike is a Trilinos package.  It is not "pike" the scripting language.

**Comment by ecurtin2** [comment]
> Work-around: Do you need Pike? If not, disable it for now: Trilinos_ENABLE_Pike:BOOL=OFF

 I don't think I need pike so that will do. 

> That's a different thing. Pike is a Trilinos package. It is not "pike" the scripting language.

Yeah I assumed as much. I just accidentally got the wrong one.

> Oh.... don't do that if you also plan to build Pike in Trilinos. Well, I suppose you could, but the idea is that Pike is a package in Trilinos.

I'll remove it then. I'm a little confused because I thought not having it would either trigger an error at building time or cause trilinos to download it itself. I'm not sure if it managed to download & build pike and there's something with the linker path? 

Do I disable pike when I build trilinos or when I link to it?

**Comment by mhoemmen** [comment]
@ecurtin2 wrote:
> Do I disable pike when I build trilinos or when I link to it?

Only disable Pike when configuring (i.e., running CMake on) Trilinos.

btw please use CMake `FIND_PACKAGE` or Trilinos' `Makefile.export.*` files to link to Trilinos; that will get the library order right for you.  Otherwise, you'll have troubles in applications that use Trilinos, if you update Trilinos and the set of enabled packages or third-party libraries (TPLs) changes.  NEVER NEVER NEVER hard-code the Trilinos library order!!!!!!!!!!

> I'm a little confused because I thought not having it would either trigger an error at building time or cause trilinos to download it itself.

Think of Trilinos like a Linux distribution.  It's a collection of >60 packages.  You don't need to enable all the packages in order to build Trilinos.

Trilinos does not download any source code, ever.

**Comment by ecurtin2** [comment]
Thanks for your input! 

I've gotten this to work for what I need. I decided to just try to install the things I suspect that I may need for my project. Here's what I did:

$TRILINOS_DIR/do-cmake
```
cmake $TRILINOS_DIR \
-DCMAKE_INSTALL_PATH:PATH=/home/evan/local/ \
-DTrilinos_ENABLE_Epetra:BOOL=ON \
-DTrilinos_ENABLE_Tpetra:BOOL=ON \
-DTrilinos_ENABLE_Teuchos:BOOL=ON \
-DTrilinos_ENABLE_Kokkos:BOOL=ON \
-DTrilinos_ENABLE_Thyra:BOOL=ON \
-DTrilinos_ENABLE_Anasazi:BOOL=ON \
-DTrilinos_ENABLE_Pike:BOOL=OFF \
```
Made a build directory $TRILINOS_DIR/build then ran this file within:
```
mkdir build
cd build
../do-cmake
make 
make install
```
Now when trying to run build the $TRILINOS_DIR/demo/buildAgainstTrilinos example, 
I got compiler errors with the C++ version. Simple fix to add -std=c++11. After doing so, there is still a compiler error

```
/usr/bin/cmake -H/home/evan/local/Trilinos/demos/buildAgainstTrilinos -B/home/evan/local/Trilinos/demos/buildAgainstTrilinos/build --check-build-system CMakeFiles/Makefile.cmake 0
/usr/bin/cmake -E cmake_progress_start /home/evan/local/Trilinos/demos/buildAgainstTrilinos/build/CMakeFiles /home/evan/local/Trilinos/demos/buildAgainstTrilinos/build/CMakeFiles/progress.marks
make -f CMakeFiles/Makefile2 all
make[1]: Entering directory '/home/evan/local/Trilinos/demos/buildAgainstTrilinos/build'
make -f src/CMakeFiles/myappLib.dir/build.make src/CMakeFiles/myappLib.dir/depend
make[2]: Entering directory '/home/evan/local/Trilinos/demos/buildAgainstTrilinos/build'
cd /home/evan/local/Trilinos/demos/buildAgainstTrilinos/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/evan/local/Trilinos/demos/buildAgainstTrilinos /home/evan/local/Trilinos/demos/buildAgainstTrilinos/src /home/evan/local/Trilinos/demos/buildAgainstTrilinos/build /home/evan/local/Trilinos/demos/buildAgainstTrilinos/build/src /home/evan/local/Trilinos/demos/buildAgainstTrilinos/build/src/CMakeFiles/myappLib.dir/DependInfo.cmake --color=
Scanning dependencies of target myappLib
make[2]: Leaving directory '/home/evan/local/Trilinos/demos/buildAgainstTrilinos/build'
make -f src/CMakeFiles/myappLib.dir/build.make src/CMakeFiles/myappLib.dir/build
make[2]: Entering directory '/home/evan/local/Trilinos/demos/buildAgainstTrilinos/build'
[ 25%] Building CXX object src/CMakeFiles/myappLib.dir/src_file.cpp.o
cd /home/evan/local/Trilinos/demos/buildAgainstTrilinos/build/src && /usr/bin/c++   -DMYAPP_EPETRA -I/home/evan/local/Trilinos/demos/buildAgainstTrilinos/src/. -I/home/evan/local/Trilinos/demos/buildAgainstTrilinos/src/./src_subdirTBD -I/usr/local/include  -std=c++11 -O3 -DNDEBUG -std=c++14   -o CMakeFiles/myappLib.dir/src_file.cpp.o -c /home/evan/local/Trilinos/demos/buildAgainstTrilinos/src/src_file.cpp
/home/evan/local/Trilinos/demos/buildAgainstTrilinos/src/src_file.cpp: In function ‘int buildDemo::src_file(std::__cxx11::string&, Teuchos::Comm<int>&)’:
/home/evan/local/Trilinos/demos/buildAgainstTrilinos/src/src_file.cpp:7:68: error: invalid initialization of reference of type ‘const Teuchos::Ptr<Teuchos::ParameterList>&’ from expression of type ‘Teuchos::ParameterList*’
   Teuchos::updateParametersFromXmlFileAndBroadcast(infile, &p, comm);
                                                                    ^
In file included from /home/evan/local/Trilinos/demos/buildAgainstTrilinos/src/src_file.cpp:2:0:
/usr/local/include/Teuchos_XMLParameterListHelpers.hpp:79:6: note: in passing argument 2 of ‘void Teuchos::updateParametersFromXmlFileAndBroadcast(const string&, const Teuchos::Ptr<Teuchos::ParameterList>&, const Teuchos::Comm<int>&, bool)’
 void updateParametersFromXmlFileAndBroadcast(
      ^
src/CMakeFiles/myappLib.dir/build.make:65: recipe for target 'src/CMakeFiles/myappLib.dir/src_file.cpp.o' failed
make[2]: *** [src/CMakeFiles/myappLib.dir/src_file.cpp.o] Error 1
make[2]: Leaving directory '/home/evan/local/Trilinos/demos/buildAgainstTrilinos/build'
CMakeFiles/Makefile2:90: recipe for target 'src/CMakeFiles/myappLib.dir/all' failed
make[1]: *** [src/CMakeFiles/myappLib.dir/all] Error 2
make[1]: Leaving directory '/home/evan/local/Trilinos/demos/buildAgainstTrilinos/build'
Makefile:97: recipe for target 'all' failed
make: *** [all] Error 2
```
Here's the actual error
`invalid initialization of reference of type ‘const Teuchos::Ptr<Teuchos::ParameterList>&’ from expression of type ‘Teuchos::ParameterList*’`

So something seems to be off for the demo. However, I was successfully able to build and run 
the [anasazi example](https://trilinos.org/docs/dev/packages/anasazi/doc/html/BlockDavidson_2BlockDavidsonEpetraEx_8cpp-example.html)

Using the [CMakeFindPackageTrilinosExample](https://github.com/trilinos/Trilinos_tutorial/wiki/CMakeFindPackageTrilinosExample)


So, thanks!

**Comment by mhoemmen** [comment]
The Trilinos demos in that directory are super old and best ignored.  I forgot to mention that the first time.  Not sure why they don't go through nightly testing -- all the other packages do.  Glad it works for you!  May I close the issue?

**Comment by ecurtin2** [comment]
Yeah I've gotten what I need, so might as well close it. I don't care if the demo compiles, I just wanted to use the eigensolvers!

**Comment by mhoemmen** [comment]
@ecurtin2 Thanks!  Please feel free to post a new issue if you have further questions!
