### ISSUE TITLE
Framework: Windows Testing Not Posting to Dashboard

### ISSUE THREAD

**Issue by csiefer2** [trilinos/Trilinos#2309]
Again. @bmpersc

**Comment by bmpersc** [comment]
@csiefer2, this is still related to the jenkins rebuild. I do need to do something to the machine to fix it, I know what it is and it shouldn't be hard to fix.

**Comment by bmpersc** [comment]
@csiefer2, I have updated the machine for the jenkins rebuild and it is back up and running a job. Please let us know if you see this happen again.
