### ISSUE TITLE
Issues to be address before making automated PR testing and merging mandatory

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#2312]
**CC:** @trilinos/framework, @rppawlo, @maherou, @srajama1

## Description:

There has been recent discussion about when the time to make automated PR testing and merging system being developed by the @trilinos/framework team mandatory.  From my own experience and conversations with other people, the following issues would need to be addressed before that can occur:

* Update and streamline the builds used by the automated PR testing system (to make sure that we are getting the needed testing, having the builds not take too many computer resoruces, and getting the biggest bang for our buck in protecting important functionality.) (see #2317)
  * **STATUS:** ???
* Post all build results to CDash to see exactly what is getting tested and what the failures are (and allow it to be reviewed before the final merge). 
  * Complete the upgrade of the new CDash version that supports all-at-once configure, build, test, and submit (see https://gitlab.kitware.com/snl/project-1/issues/33). 
    * **STATUS:** Currently, the PR build results are being submitted to the trial testing-vm.sandia.gov/cdash site and the Framework team is okay with the stability of that site for managing PR builds so this is not currently considered an impediment.
  * Upgrade the minimum version of CMake used by Trilinos from 2.8.11 to 3.10 in order to take advantage of all-at-once configure, build, test, and submit to new CDash version.  (Also, once the auto PR testing is using CMake 3.10 it will allow CMake code in packages that does not work with older versions of CMake and therefore will destabilize other builds of Trilinos unless we force the upgrade).
    * **STATUS:** This can be done later.  For now, this might allow CMakeLists.txt files to get pushed that will break the configure of Trilinos with older CMake versions but the current post-push CI build and other nightly builds would catch that.
* Make it easy and obvious how to reproduce the exact auto PR builds and results shown on CDash and to allow people to run these locally even **before** they post their PR if they would like (e.g. #2295)
 (Which includes making the env and/or machine accessible to all Trilinos developers, see https://github.com/trilinos/Trilinos/issues/2317#issuecomment-369987520.) 
  * **STATUS:** ???
* Auto-merge with final staged testing before merge to ‘develop’ (i.e. avoid violations of the [additive test assumption of branches](https://docs.google.com/document/d/1uVQYI2cmNx09fDkHDA136yqDTqayhxqfvjFiuUue7wo/edit#bookmark=id.d1jneh8ubsyn) that resulted #2264).
  * **STATUS:** Currently plan is to mark older PRs as "Stale" but not strictly guarantee stability of 'develop' due to violations of the "additive test assumption of branches"?
* Auto wiping the build directory when requested so that it will deal with cases where you need to build from scratch (e.g. when Panzer files get update such as described in https://github.com/trilinos/Trilinos/issues/1304#issuecomment-355786180 and https://github.com/trilinos/Trilinos/issues/1304#issuecomment-356053919).
  * **STATUS:** Currently a complete build from scratch with each PR build is being done to address this.  With this implementation, this is not an impediment.
* Address cases where no packages get enabled and therefore no tests are run.  Will the auto PR system mark them as "passed" and allow the PR to be merged?
  * **STATUS:** ???
* Document the PR and auto testing process so people can understand how to use it correctly and understand why it is firing off tests in some cases and not in other cases.
  * **STATUS:** ???
* Ensure the current testing infrastructure will scale when everyone is required to use topic branches for pushing anything (even documentation changes).  For example, will this scale when there are 20 active PRs being edited at the same time?  When there are more and more topic branches, how long with the lags be before things get tested and eventually merged?
  * **STATUS:** This will be addressed by "Update and streamline the builds used by the automated PR testing system" above?

Other issues that should be resolve (quickly) after initial adoption:
* Remove manual updates of the list of packages from mapping of directories to packages. (e.g. use self-maintaining existing code in TriBITS tools for that?).  If you don’t things will not get tested correctly without manual intervention to constantly keep that manual list up to date.

The motivation for this issue was conversations with @rppawlo, @jwillenbring and the [2018-02-28 Trilinos Planning meeting](https://docs.google.com/document/d/1JClLSR3n79XJT_yLPPoQv_e3rJToHxl8fUzRYojtY5Y/edit)

## Related Issues

* Related to: #1154, #1304 
* Composed of: #2317 

## Tasks:

1. Define the set of builds to be used in the auto PR system with a working group (#2317).  See #2317 ...
1. Complete and robustify the submitting of results to CDash (there is a start to this but it is having problems, see https://github.com/trilinos/Trilinos/pull/2310#issuecomment-369390502).
1. ???

**Comment by dridzal** [comment]
We would also need an automated way to generate PRs after testing as part of subteam workflows, like for ROL.  It’s probably OK to have the final review/merge done manually, but creating and issuing the PR needs to be part of scripts.

**Comment by jmgate** [comment]
It'd be nice if there was a way to detect that a PR doesn't have any code changes (e.g., documentation-only changes), but I can't think of a robust way to do this unless we have the PR submitter include some flag in the title or description that we can search for.  If we could detect that, it could reduce the total amount of testing we're doing, but I also don't know what the frequency of non-code-change PRs would be&mdash;I'd imagine it'd be relatively low.  Perhaps the potential test time savings aren't worth the time to develop such a feature.

**Comment by jmgate** [comment]
> creating and issuing the PR needs to be part of scripts.

That's very doable using the GitHub API.  If you have something specific in mind, I can point you to some examples, or potentially help you develop the scripts you need.

**Comment by lucbv** [comment]
@jmgate you probably do not want to allow for a flag that will result in an auto-merge without checking things before. You really want to have a robust way to detect that nothing will touch the code base before merging...

**Comment by jmgate** [comment]
Good point.  Writing such a feature would be possible, but it'd be a heck of a time investment.

**Comment by bartlettroscoe** [comment]
> It'd be nice if there was a way to detect that a PR doesn't have any code changes (e.g., documentation-only changes), but I can't think of a robust way to do this unless we have the PR submitter include some flag in the title or description that we can search for. If we could detect that, it could reduce the total amount of testing we're doing, but I also don't know what the frequency of non-code-change PRs would be—I'd imagine it'd be relatively low. Perhaps the potential test time savings aren't worth the time to develop such a feature.

For the foreseeable future, package-based change detection and testing of downstream packages (which is what is currently implemented by the checkin-test.py script, the post-push CI server, and the auto PR testing) is about the best we can do.  That is pretty safe given how TriBITS manages package dependencies (and years of experience with the checkin-test.py script and the post-push CI server in Trilinos have shown that to be true).  Any file might be pulled into a test somehow (and many are in many packages) so there is no universal way to determine what changed files will impact the build or the tests.

**Comment by bartlettroscoe** [comment]
> > creating and issuing the PR needs to be part of scripts.
>
> That's very doable using the GitHub API. If you have something specific in mind, I can point you to some examples, or potentially help you develop the scripts you need.

The "auto merge, test, and push" feature (that avoids violations of the "additive test assumption of branches") listed above that should allow these PRs to be tested and pushed without requiring a manual review (or the script should set it the PR that way).  In the case of the ROL subteam workflow, it makes no sense for anyone to manually review these PRs.  But if @dridzal is okay with doing a manual rubber-stamp review of the PR, then that is fine with me.

Does the auto push of a topic branch and auto creation of a PR branch need to be implemented before we make the auto PR testing and merging mandatory?  If so, we need to add that to the list above.

**Comment by jmgate** [comment]
I wouldn't think so.  It sounds like a nicety that could come later for those who want to use it.

**Comment by bartlettroscoe** [comment]
I just realized two other requirements that need to be added (that are a result of needing to display results on CDash):

* Complete the upgrade of the new CDash version that supports all-at-once configure, build, test, and submit (see https://gitlab.kitware.com/snl/project-1/issues/33).
* Upgrade the minimum version of CMake used by Trilinos from 2.8.11 to 3.10 in order to take advantage of all-at-once configure, build, test, and submit to new CDash version.  (Also, once the auto PR testing is using CMake 3.10 it will allow CMake code in packages that does not work with older versions of CMake and therefore will destabilize other builds of Trilinos unless we force the upgrade).

**Comment by bartlettroscoe** [comment]
I spoke with @jwillenbring yesterday and it seems the current plan to address:

* Auto wiping the build directory when requested so that it will deal with cases where you need to build from scratch ...

is to simply build from scratch with every auto PR build.  This will likely increase the average 

Also, it seems that the plan for CDash submits is to use the trilinos-vm.sandia.gov/cdash/ site (currently under evaluation) as the production site for submitting PR testing results.  That would mean that we don't need to do the CDash upgrade before making the auto PR testing process mandatory.  But it also means that we need to be careful while doing the evaluation and fixing more defects as it will bring down the CDash site being used for displaying build and test results from auto PR testing.

**Comment by jmgate** [comment]
> is to simply build from scratch with every auto PR build.

Oh dear.  First could we try something like the following?
*  Try a build.
*  If it fails because it can't find a file, wipe the build directory and try to build from scratch.
*  If it fails for the same reason, then report the failure.

Admittedly, this is what I do manually when updating and building on my own machine.  We'd have to figure out what to teach it to look for in the output from `make`, but if the potential upside is saving a whole heck of a lot of build time, I'd say it's worth the effort.

**Comment by bartlettroscoe** [comment]
I am actually okay with building from scratch everytime.  Yes it takes longer but it is a more robust build.   Just throw an extra $40K of hardware at it.  Use ninja for the build tool and use `ninja -j64` to build.  You can always get around expensive builds and test suites by throwing hardware at it.

**Comment by bartlettroscoe** [comment]
@trilinos/framework,

Is the auto PR system not posting to CDash anymore?  There are no PR builds posted at:

* https://testing-vm.sandia.gov/cdash/index.php?project=Trilinos&filtercombine=and&filtercombine=and&filtercount=2&showfilters=1&filtercombine=and&field1=groupname&compare1=61&value1=Pull%20Request&field2=buildstarttime&compare2=84&value2=now

since 3/21/2018 but I know several PRs today (e.g. #2447 and #2449) said that the builds passed but no results are shown on CDash.

**Comment by bartlettroscoe** [comment]
@jwillenbring,

Thanks for adding the page:

* https://github.com/trilinos/Trilinos/wiki/Pull-Request-Testing-Interface

 I read over it and made a few small improvements with the diffs shown [here](https://github.com/trilinos/Trilinos/wiki/Pull-Request-Testing-Interface/_compare/f6061d3158ad8950a1a953f961342b0729a1e5d0...faf707bd88343b7117df9d96ea6d57020669f552).  I think what is there now is good enough to explain how this system works and for people to be able to use it.  But a longer more detailed reference description on a different wiki page or an FAQ about the PR testing process might be good to have at some point for people that need to know things like:

* Why does the PR tester run three failing builds of my PR even when on new commits are pushed?
* What assumptions or assurances are being made such that this auto PR testing process will result in these builds passing on the updated 'develop' branch?  (The answer to that question is **not** obvious to most people and the current system does not guarantee that as we have seen.)
* Is it possible for another PR that gets merged to break my PR testing? (The answer to that with the current implementation is yes, and the situations that can cause that need to be explained which goes back to the previous question.)

Also note that the auto PR tester has all the info needed to construct the URL to the results on CDash even before it gets run.  That is because for the PR CDash build name `PR-<pr-id>-test-Trilinos_pullrequest_<build-name>-<build-num>`, the auto PR tester knows `<pr-id>`, `<build-name>`, and `<build-num>` because it prints out all of that info in comments like:

* https://github.com/trilinos/Trilinos/pull/2442#issuecomment-375801138

Therefore, why not just stick the CDash link in there.  For that particular PR build, the CDash URL is [this](https://testing-vm.sandia.gov/cdash/index.php?project=Trilinos&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=PR-2457-test-Trilinos_pullrequest_gcc_4.8.4-122&field2=buildstarttime&compare2=84&value2=now).  That would make it trivial for developers to find results on CDash.

Can @allevin just add that to the PR comments added by the auto PR tester script?
