### ISSUE TITLE
Broken stokhos library build with untested push to Muelu on 3/1/2018

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#2315]
**CC:** @trilinos/framework, @trilinos/stokhos, @trilinos/muelu, @rstumin

## Next Action Status:

Commit 5585e8c was reverted in pushed commit 5ee27ba3b.  Next: Someone help @rstumin to put commit 5585e8c on a rebased topic branch and create PR once errors are resolved?

## Description

The current CI iteration running right now shown at:

* https://testing-vm.sandia.gov/cdash/index.php?project=Trilinos&parentid=3341376

is showing build failures for the Stokhos libraires (not tests or examples).

The only changes pulled in this CI iteration are shown at:

* https://testing-vm.sandia.gov/cdash/viewNotes.php?buildid=3341378#!#note1

and are:

```
5585e8c:  inject null space now.
Author: rstumin <rstumin@sandia.gov>
Date:   Thu Mar 1 13:38:21 2018 -0700

M	packages/muelu/src/Transfers/SemiCoarsen/MueLu_SemiCoarsenPFactory_decl.hpp
M	packages/muelu/src/Transfers/SemiCoarsen/MueLu_SemiCoarsenPFactory_def.hpp
```

**Comment by bartlettroscoe** [comment]
CC: @trilinos/stokhos 

Since this is a library build failure, this just be backed out immediately.  This will take down practically everyone's build (including all of the auto PR builds) that builds Stokhos or any packages that depend on Stokhos upstream or downstream.

I will back out this commit immediately and push with the checkin-test-sems.sh script.

**Comment by bartlettroscoe** [comment]
I just pushed the commit:

```
commit 5ee27ba3b0e6e043d4979157f80fb08d877cc325
Author: Roscoe A. Bartlett <rabartl@sandia.gov>
Date:   Thu Mar 1 14:33:23 2018 -0700

    Revert "inject null space now." (#2315)
    
    This reverts commit 5585e8cdbc10ee28cae85c240138fabf27289778.
    
    This commit breaks the Stokhos library build.
    
    Build/Test Cases Summary
    Enabled Packages: MueLu
    Disabled Packages: PyTrilinos,Claps,TriKota
    0) MPI_RELEASE_DEBUG_SHARED_PT => passed: passed=80,notpassed=0 (13.32 min)

M       packages/muelu/src/Transfers/SemiCoarsen/MueLu_SemiCoarsenPFactory_decl.hpp
M       packages/muelu/src/Transfers/SemiCoarsen/MueLu_SemiCoarsenPFactory_def.hpp
```

Therefore, the next CI iteration should not show this failure.

Can someone on the @trilinos/muelu team work with @rstumin to help set up a topic branch and create a PR for this commit?  That will test it and then it can be safely merged to 'develop' once the automated builds and tests pass?

**Comment by william76** [comment]
@bartlettroscoe thanks for posting the issue and reverting that commit :D 

Sadly, it looks like that commit caused my PR #2313 to fail the auto-tester though but I can trigger a re-test I think ;)

**Comment by bartlettroscoe** [comment]
> Sadly, it looks like that commit caused my PR #2313 to fail the auto-tester though but I can trigger a re-test I think ;)

@william76, just rebase your branch on top of `develop` and force push.  That will trigger another round of testing.

**Comment by bartlettroscoe** [comment]
The current CI build shows clean.  See:

* https://testing-vm.sandia.gov/cdash/index.php?project=Trilinos&parentid=3341383

See the `-3` by the `0` in the "Build | Error" column.

Now this can be fixed in a calm and relaxed way offline.

**Comment by mhoemmen** [comment]
@bartlettroscoe Not sure if Ray gets these notifications; he might need a separate e-mail or phone call.

**Comment by lucbv** [comment]
@mhoemmen @bartlettroscoe plus Ray is going to parallel processing so he probably won't be working on this for some time.

**Comment by bartlettroscoe** [comment]
> Ray is going to parallel processing so he probably won't be working on this for some time.

No hurry. The commit has been reverted so fixing it can be done anytime someone gets around to it and test and push it.

**Comment by mhoemmen** [comment]
I sent Ray an e-mail just in case.  Thanks Ross!

**Comment by rstumin** [comment]
?Yup. I saw that I screwed up. Sorry about that. I'm getting a little slow witted in my waning years.

________________________________

**Comment by mhoemmen** [comment]
@rstumin Awww Ray, I think what happened is that Stokhos wasn't getting enabled for you.  It's an honest mistake.  Trilinos doesn't exactly make things easy sometimes ;-) .

**Comment by lucbv** [comment]
@rstumin PR #3422 has been merged, let us wait until tomorrow's nightly tests are run and if it all looks good we should be able to close this issue!
