### ISSUE TITLE
Anasazi::MultiVecTraits::CloneView signatures have inconsistent const qualifiers.

### ISSUE THREAD

**Issue by ecurtin2** [trilinos/Trilinos#2323]
Hello, 

# Problem 

I've been working on implementing Anasazi::MultiVecTraits for a non-trilinos datatype. 

Most of the interface seems reasonable, but there is an inconsistency between the 4 clone view interfaces.  These are declared in `AnasaziMultiVecTraits.hpp` starting at line 171

```
    static Teuchos::RCP<MV> CloneViewNonConst( MV& mv, const std::vector<int>& index )

    static Teuchos::RCP<MV> CloneViewNonConst( MV& mv, const Teuchos::Range1D& index )

    static Teuchos::RCP<const MV> CloneView( const MV& mv, const std::vector<int>& index )

    static Teuchos::RCP<MV> CloneView( MV& mv, const Teuchos::Range1D& index )
```
The signature of the 4th matches the 2nd. The naming and presence of the `std::vector<>` versions implies the 4th should use a const MV&. Currently the `Teuchos::Range1D` version does not parallel the `std::vector<>`. 

# Proposed Solution

The signature of (AnasaziMultiVecTraits.hpp line 201)

` static Teuchos::RCP<MV> CloneView( MV& mv, const Teuchos::Range1D& index )
`

should be changed to 

`static Teuchos::RCP<` **const** `MV> CloneView(`**const** `MV& mv, const Teuchos::Range1D& index )`

# Note 

I was concerned of possible conflict with the adapters made for the other trilinos packages. It looks like the `tpetra/src/AnasaziTpetraAdapter.hpp` line 320 has the signature I expect:

```
static Teuchos::RCP<const MV>
CloneView (const MV& mv, const Teuchos::Range1D& index)
```

So does the thrya adapter (`Trilinos/packages/anasazi/thyra/src/AnasaziThyraAdapter.hpp` line 238):

```
    static Teuchos::RCP<const TMVB> 
    CloneView (const TMVB& mv, const Teuchos::Range1D& index)

```

@trilinos/anasazi

**Comment by mhoemmen** [comment]
@ecurtin2 Thanks for reporting!  btw I would recommend taking the run-time polymorphism approach in Anasazi, by wrapping your MV class in a subclass of `Anasazi::MultiVec`, and your OP class in a subclass of `Anasasi::Operator`.  Anasazi already specializes the two traits classes for those two interfaces.

**Comment by ecurtin2** [comment]
Thanks for the suggestions! I'll take a look at doing it that way, to be honest I was a little confused from the documentation. I was under the impression that the traits was the preferred way to go. (I'm also not very experienced in C++ compared to python). 

Is there a specialization that exists for something like MV class = std::vector<std::Container-Like> ? I was basically trying to implement one myself so that you could take any vector-like object that supports stl-style   iteration, and that way I could avoid having to learn the internals of the various trilinos matrix/vector packages. 

I think this would be really nice so that you could do quick prototyping by using anasazi algorithms on a commonly understood interface, especially if say MV class = std::vector<std::vector<ScalarType>> is good enough for your problem. 

Anyways, I'll probably try doing this tomorrow as an exercise anyways.

**Comment by mhoemmen** [comment]
> I was under the impression that the traits was the preferred way to go.

My impression is that Heidi didn't mean for there to be a "preferred way."  Some people want to write subclasses, and others want to specialize traits.  Anasazi supports both use cases.

I'm not a fan of the traits approach in this case, where the operations are coarse grained enough that users should not worry about the overhead of run-time dispatch.  The traits approach makes it hard to add new linear algebra operations for Anasazi (or Belos) solvers to use.  However, it's allowed.

**Comment by mhoemmen** [comment]
@ecurtin2 wrote:
> Is there a specialization that exists for something like MV class = std::vector<std::Container-Like> ?

Anasazi's tests have a subclass of `Anasazi::MultiVec` that does this.  See Trilinos/packages/anasazi/test/MVOPTester/MyMultiVec.hpp.

**Comment by mhoemmen** [comment]
https://github.com/trilinos/Trilinos/pull/2329 has the fix for this issue.  Thanks @ecurtin2 ! :D
