### ISSUE TITLE
Tpetra: MatrixMatrix multiply bug: trying to dereference a captured pointer to a matrix

### ISSUE THREAD

**Issue by crtrott** [trilinos/Trilinos#2331]
This is in TpetraExt_MatrixMatrix_def.hpp lines 3700 and following. There is an attempt being made to dereference Ik-> in the parallel kernels. When those run on GPUs it crashes. Also there is no abort check for Ik being NULL ...
I am going to fix the dereference issue ...

**Comment by crtrott** [comment]
Ah and I am gonna merge the fix into the kokkos-develop branch for the integration ..

**Comment by crtrott** [comment]
Btw: it was pretty straightforward to identify the bug by running the KokkosTools KernelLogger thingy:

```
export KOKKOS_PROFILE_LIBRARY=/home/crtrott/Kokkos/kokkos-tools/src/tools/kernel-logger/kp_kernel_logger.so
mpirun -np 2 ./TpetraCore_ImportExport2_UnitTests.exe

## TONS OF OUTPUT
KokkosP: Execution of kernel 5468 is completed.
KokkosP: Executing parallel-for kernel on device 0 with unique execution identifier 5469
KokkosP: Kokkos::View::initialization
KokkosP: Execution of kernel 5140 is completed.
KokkosP: Executing parallel-for kernel on device 0 with unique execution identifier 5141
KokkosP: Kokkos::View::initialization
KokkosP: Execution of kernel 5469 is completed.
KokkosP: Executing parallel-scan kernel on device 0 with unique execution identifier 5470
KokkosP: Tpetra_MatrixMatrix_merge_matrices_buildRowptr
KokkosP: Execution of kernel 5141 is completed.
KokkosP: Executing parallel-scan kernel on device 0 with unique execution identifier 5142
KokkosP: Tpetra_MatrixMatrix_merge_matrices_buildRowptr
terminate called after throwing an instance of 'std::runtime_error'
  what():  cudaDeviceSynchronize() error( cudaErrorIllegalAddress): an illegal memory access was encountered /mnt/netapp/OHPC_home/crtrott/Trilinos/packages/kokkos/core/src/Cuda/Kokkos_Cuda_Impl.cpp:119
Traceback functionality not available
```

The tool tells you when it enters and exists a Kernel with its kernel name. Since Chris named the kernel it was pretty straightforward to find the culprit. The cudaErrorIllegalAddress meant it most likely accessed host memory.

**Comment by mhoemmen** [comment]
Thanks @crtrott for finding and fixing this!  @csiefer2 is out of commission this week so I'm sure he would appreciate this.

**Comment by csiefer2** [comment]
Could this relate to #2169 ?

**Comment by mhoemmen** [comment]
I should close this issue, since I merged Christian's changes.  There's another open issue, #2334, that may be relevant; I have a PR (#2335) open for that.
