### ISSUE TITLE
Tpetra: Fix BlockCrs benchmark incorrect use of default execution space in Kokkos::parallel_*

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#2347]
The BlockCrs benchmark uses an integer for the range in `Kokkos::parallel_*` in some places.  It should instead use a `Kokkos::RangePolicy` with the correct execution space.  This matters (e.g., could cause run-time or compile-time errors) if Tpetra's default execution space != Kokkos' default execution space.

@trilinos/tpetra @kyungjoo-kim

**Comment by kyungjoo-kim** [comment]
@mhoemmen 

Do we have a case that Tpetra default exec space is not equal to kokkos default space ? 

If someone creates a kokkos local matrix object and harnesses it with a tpetra distributed object assuming both have the same default exec space, is this wrong or not guarantted ?

**Comment by mhoemmen** [comment]
@kyungjoo-kim wrote:
> Do we have a case that Tpetra default exec space is not equal to kokkos default space ?

Yes.  @rppawlo can tell you more, if I remember correctly.  CASL VERA (if I remember right) builds with CUDA ON in Kokkos, but OFF in Tpetra and downstream.  (I advised against this, but they insisted.)

Sierra has in the past built with OpenMP enabled in Kokkos, but Serial as the default execution space in Trilinos.

**Comment by mhoemmen** [comment]
> If someone creates a kokkos local matrix object and harnesses it with a tpetra distributed object assuming both have the same default exec space, is this wrong or not guarantted ?

I don't know what you mean by this; could you give an example?

**Comment by mhoemmen** [comment]
I fixed this issue in develop with the push seen above.

**Comment by kyungjoo-kim** [comment]
```
// in the BlockCrs example, I use the following local object to perform node-parallel 
// local object construction
typename Tpetra::CrsGraph<>::local_graph_type;
typename Tpetra::CrsMatrix<>::local_matrix_type;
typename Tpetra::MultiVector<value_type>::dual_view_type;
// since I cannot assume that tpetra and kokkos has the same default execution space,
// I cannot write an tpetra-independent code without templating tpetra default exec space
// like using the following
typedef Kokkos::StaticCrsGraph<local_ordinal> local_graph_type;
typedef KokkosSparse::CrsMatrix<value_type,local_ordinal> local_matrix_type;
typedef Kokkos::DualView<value_type**,Kokkos::LayoutLeft> dual_view_type;

// this is something new to me. so, the good practice of using tpetra is to always get 
// necessary default template parameters from tpetra and not to use kokkos default parameters.
// if i want to use kokkos default space parameters, I need to explicitly do mirroring.  
```
