### ISSUE TITLE
test failures compiling 12.12.1 w/ intel compilers 2018.1

### ISSUE THREAD

**Issue by nolta** [trilinos/Trilinos#2357]
## Description

I'm getting the following test failures with trilinos 12.12.1 compiled with the intel 2018.1 compilers on 
a skylake box running centos 7.4:

```
$ ctest -j40
...
The following tests FAILED:
	1188 - Belos_resolve_gmres_hb_1_MPI_4 (Failed)
	1800 - NOX_Thyra_Heq_MPI_1 (Failed)
	2043 - Stokhos_TpetraCrsMatrixUQPCEUnitTest_Serial_MPI_4 (Failed)
	2050 - Stokhos_TpetraCrsMatrixMPVectorUnitTest_Serial_MPI_4 (Failed)
	2217 - Piro_MatrixFreeDecorator_UnitTests_MPI_4 (Failed)
```

Output of `ctest -VV` here: https://gist.github.com/nolta/b18e12c79fb7f7a93937a33060229849

Not sure if these are known issues, or intel compiler bugs, or a misconfigured build.

## Your Environment

- **Relevant repo SHA1s/versions:**  Trilinos 12.12.1
- **Relevant configure flags or configure script:**

```
cmake .. -DCMAKE_INSTALL_PREFIX="$prefix" \
    -DBLAS_LIBRARY_DIRS="$MKLROOT/lib/intel64" \
    -DBLAS_LIBRARY_NAMES="mkl_rt" \
    -DBUILD_SHARED_LIBS=ON \
    -DBoostLib_INCLUDE_DIRS="$BOOST_ROOT/include" \
    -DBoostLib_LIBRARY_DIRS="$BOOST_ROOT/lib" \
    -DBoost_INCLUDE_DIRS="$BOOST_ROOT/include" \
    -DCMAKE_CXX_FLAGS="-march=native" \
    -DHDF5_INCLUDE_DIRS="$HDF5_MPI_ROOT/include" \
    -DHDF5_LIBRARY_DIRS="$HDF5_MPI_ROOT/lib" \
    -DLAPACK_LIBRARY_DIRS="$MKLROOT/lib/intel64" \
    -DLAPACK_LIBRARY_NAMES="mkl_rt" \
    -DMKL_INCLUDE_DIRS="$MKLROOT/include" \
    -DMKL_LIBRARY_DIRS="$MKLROOT/lib/intel64" \
    -DMKL_LIBRARY_NAMES="mkl_rt" \
    -DNetcdf_INCLUDE_DIRS="$NETCDF_MPI_ROOT/include" \
    -DNetcdf_LIBRARY_DIRS="$NETCDF_MPI_ROOT/lib" \
    -DTPL_ENABLE_HDF5=ON \
    -DTPL_ENABLE_MKL=ON \
    -DTPL_ENABLE_MPI=ON \
    -DTrilinos_ENABLE_ALL_PACKAGES=ON \
    -DTrilinos_ENABLE_EXPLICIT_INSTANTIATION=ON \
    -DTrilinos_ENABLE_SECONDARY_TESTED_CODE=OFF \
    -DTrilinos_ENABLE_TESTS=ON
```

- **Operating system and version:** Centos 7.4 / Skylake Xeon
- **Compiler and TPL versions:**
    + intel 2018.1 compilers, MKL, & MPI
    + boost 1.66.0
    + hdf5 1.8.20
    + netcdf 4.6.0

## Related Issues

-  The `NOX_Thyra_Heq_MPI_1` failure appears to be #2247.
- `Belos_resolve_gmres_hb_1_MPI_4` and `Piro_MatrixFreeDecorator_UnitTests_MPI_4` failed in https://github.com/trilinos/Trilinos/issues/2320#issuecomment-370053022.
- `Stokhos_TpetraCrsMatrixUQPCEUnitTest_Serial_MPI_4` may be #2254.

**Comment by mhoemmen** [comment]
Trilinos 12.12 is at least three years old.  Have you tried the latest version of Trilinos, in the master branch?
