### ISSUE TITLE
MueLu_ParameterListInterpreterTpetraHeavy_MPI_1 newly failing in Trilinos-atdm-sems-gcc-7-2-0 build on 3/12/2018

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#2365]
**CC:** @trilinos/muelu, @fryeguy52

## Description

The test `MueLu_ParameterListInterpreterTpetraHeavy_MPI_1` failed today in the build `Trilinos-atdm-sems-gcc-7-2-0` shown at:

* https://testing-vm.sandia.gov/cdash/index.php?project=Trilinos&parentid=3363069
* https://testing-vm.sandia.gov/cdash/viewTest.php?onlydelta&buildid=3363585

The failing test shows:

```
...
Testing: MLParameterListInterpreter/MLpgamg1.xml
Binary files Output/MLpgamg1_tpetra.gold_filtered and Output/MLpgamg1_tpetra.out_filtered differ
MLParameterListInterpreter/MLpgamg1.xml : failed
Testing: MLParameterListInterpreter/MLpgamg2.xml
...
```

## Steps to Reproduce

Using the `do-configure` script:

```
#!/bin/bash
cmake \
-DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/sems/atdm/SEMSATDMSettings.cmake,cmake/std/MpiReleaseDebugSharedPtSettings.cmake,cmake/std/BasicCiTestingSettings.cmake \
-DDART_TESTING_TIMEOUT:STRING=300.0 \
-DTrilinos_ENABLE_TESTS:BOOL=ON \
"$@" \
$TRILINOS_DIR
```

Anyone should be able to reproduce these failures on any SNL COE RHEL6 machine as shown below:

```
$ cd <some_build_dir>/

$ source $TRILINOS_DIR/cmake/std/sems/atdm/load_atdm_7.2_dev_env.sh

$ ./do-configure -DTrilinos_ENABLE_MueLu=ON

$ make -j16

$ ctest -VV -R MueLu_ParameterListInterpreterTpetraHeavy_MPI_1
```

**Comment by jhux2** [comment]
It appears there were no git updates when this failure happened.  So I'm not sure how we can effectively diagnose this.  Any suggestions appreciated ....

**Comment by bartlettroscoe** [comment]
> It appears there were no git updates when this failure happened. So I'm not sure how we can effectively diagnose this. Any suggestions appreciated ....

The version tested as shown at:

* https://testing-vm.sandia.gov/cdash/viewConfigure.php?buildid=3363585

was:

```
756946d [Fri Mar 9 22:32:55 2018 -0700] <crtrott@sandia.gov>
Merge pull request #2363 from trilinos/additive-schwarz-test-for-testing-at-a-la
```

That version does appear to be a few days old.  As shown at:

* https://jenkins-srn.sandia.gov/view/Trilinos%20ATDM/job/Trilinos-atdm-sems-gcc-7-2-0/configure

and `Trilinos_REPOSITORY_LOCATION='software.sandia.gov:/space/git/nightly/Trilinos'` at:

* https://jenkins-srn.sandia.gov/view/Trilinos%20ATDM/job/Trilinos-atdm-sems-gcc-7-2-0/66/consoleText

this build is using the `software.sandia.gov:/space/git/nightly/Trilinos` repo of Trilinos.  Perhaps the process that the Trilinos Framework team runs that updates that `nightly` repo is broken?

I will switch over to the github.com/trilinos/Trilinos.git and 'develop' branch for now to make sure we are testing the most up-to-date version.

As you noted, indeed there were no updates reported this iteration from the prior day as shown at:

* https://testing-vm.sandia.gov/cdash/viewNotes.php?buildid=3363585#!#note1

Therefore Could this be a random failure?

Let's see what happens tomorrow.

**Comment by bartlettroscoe** [comment]
The test went from passing to failing this morning as shown at:

* https://testing-vm.sandia.gov/cdash/viewTest.php?onlydelta&buildid=3365662

Perhaps this was just some type of fluke?

I will close this issue and we will just watch to see what happens in the future.
