### ISSUE TITLE
Teuchos YAML PL parsing and aprepro

### ISSUE THREAD

**Issue by bathmatt** [trilinos/Trilinos#2367]
Is there a way to have the teuchos yaml parser take either a int or a double?  In theXML parser this is automatic, but with the YAML parser it is based on if the value has a . in it.  So 1 is an int and 1.0 is a double.  

Here is the problem, Aprepro will strip off all the .0 if you have a macro expansion.

What I want is basically to be able to say in my code

```
  valid_pl.set<Teuchos::any>("Weight",1.0,"Macro particle weight");
      pl.validateParametersAndSetDefaults(valid_pl);
```

meaning validate that the name Weight is there, set it to 1.0 if it isn't.  I see the option to pass a validator into the setting of the valid_pl, is there one that does this already?

@ibaned I'm guessing you've looked at this the latest so pinging you on it.

**Comment by rppawlo** [comment]
Talked to MAtt about this but wanted to post for wider audience. There is a PL valiadator. Here is an example from the unit test suite. Maybe a little verbose.

```
  // Create a validator for the parameter "Line Search"->"Polynomial"->"Max Iters"
  // that accepts an 'int', a 'double' or a 'std::string' value!
  typedef Teuchos::AnyNumberParameterEntryValidator::AcceptedTypes AcceptedTypes;
  Teuchos::RCP<Teuchos::AnyNumberParameterEntryValidator>
    linesearchMaxItersValiator = rcp(
      new Teuchos::AnyNumberParameterEntryValidator(
        Teuchos::AnyNumberParameterEntryValidator::PREFER_INT, // Not used here!
        AcceptedTypes(false).allowInt(true).allowDouble(true).allowString(true)
        )
      );
  PL_Main_valid.sublist("Line Search").sublist("Polynomial").set(
    "Max Iters",3
    ,"The maximum number of inner linear search iterations allowed."
    ,linesearchMaxItersValiator
    );
```
