### ISSUE TITLE
Tpetra: (FEM Assembly Example) Add command-line options

### ISSUE THREAD

**Issue by william76** [trilinos/Trilinos#2368]
@trilinos/tpetra 
@william76

## Current Behavior
Currently the FEM Assembly examples do not take command line arguments.

## Expectations
Implement command-line options for the [Tpetra Finite Element Mesh Assembly examples][1].

## Definition of Done
- [ ] Implement command line options handler using [Teuchos::CommandLineProcessor][2].

### Implement the following command line parameters
- [ ]  -x, --num_elements_x
  - Number of elements on the X axis of the 2D mesh
- [ ]  -y, --num_elements_y
  - Number of elements on the Y axis of the 2D mesh 
- [ ] -v, --verbose
  - Enable verbose output mode.
- [ ] -t, --timing
  - Report timing information at end of run.

@mhoemmen This is what I've got for the options to add... is there anything else that we should put in as options to the application?  Any "standard" options for apps?

[1]: https://github.com/trilinos/Trilinos/tree/develop/packages/tpetra/core/example/Finite-Element-Assembly
[2]: https://trilinos.org/docs/dev/packages/teuchos/doc/html/classTeuchos_1_1CommandLineProcessor.html

**Comment by mhoemmen** [comment]
@william76 If you call `Tpetra::initialize`, you'll also get Kokkos' standard options.
