### ISSUE TITLE
Tpetra: (FEM Assembly Example) Reconfigure examples to use common main

### ISSUE THREAD

**Issue by william76** [trilinos/Trilinos#2369]
@trilinos/tpetra 
@william76

FEM Assembly examples currently are each self-contained programs, containing their own main().  In pull request #2313 @mhoemmen requested that I look into using a common main for each example.

Let's look into this and see if it makes sense to do that with this example.

My thoughts: However we do this, I like the idea of keeping as much stand-alone qualities as possible since it's an example that people might use.

@mhoemmen mentioned there is already infrastructure in Trilinos to provide a 'main' that we might use.

## Definition of Done
- [ ] If we implement, use a Trilinos testing common main body to launch the examples.
  - [ ] Modify examples to pull code out of `main()` and put into a function or method.
- [ ] Testing on a GPU platform
- [ ] MPI testing

**Comment by mhoemmen** [comment]
@william76 See my comments here https://github.com/trilinos/Trilinos/issues/2370#issuecomment-372531179 which I will repeat verbatim below:

The common main function shouldn't be an issue. On the other hand, I think I know the problem: `RCP<Tpetra::Map<...>>`. That's created at a scope such that the RCP's reference count goes to zero after `Tpetra::finalize` gets called. You don't want any `Kokkos::View` objects (such as might live in the Tpetra::Map) to outlive the `Kokkos::finalize` call.

Best way to do this is to lift the example code out of main into its own function.

**Comment by mhoemmen** [comment]
In general, even without Kokkos, you don't want any Tpetra distributions or distributed objects to outlive `MPI_Finalize`.  For example, they may create and store MPI objects that should be freed before `MPI_Finalize` is called.
