### ISSUE TITLE
FEM Assembly Example: Fix CUDA Error Messages

### ISSUE THREAD

**Issue by william76** [trilinos/Trilinos#2370]
@trilinos/tpetra

## Current Behavior
When running FEM Assembly examples on a GPU system (Power8, Pascall100 nodes), the output contains the following error messages at the end of a run when using 4 nodes:

```
Kokkos::Cuda::Cuda instance constructor : ERROR device not initialized
Kokkos::Cuda::Cuda instance constructor : ERROR device not initialized
Kokkos::Cuda::Cuda instance constructor : ERROR device not initialized
Kokkos::Cuda::Cuda instance constructor : ERROR device not initialized
Kokkos::Cuda::Cuda instance constructor : ERROR device not initialized
Kokkos::Cuda::Cuda instance constructor : ERROR device not initialized
End Result: TEST PASSED
Kokkos::Cuda::Cuda instance constructor : ERROR device not initialized
Kokkos::Cuda::Cuda instance constructor : ERROR device not initialized
```

When running on 1 core, the message is still there but only one of them.

The test still passes, but these error messages show up.

@mhoemmen @jhux2 @csiefer2 @crtrott 
I don't have a lot of experience running on the GPU systems, have any of you guys seen this before?  Any suggestions?

## Code Location
The code examples are generally the same, but the [fem_assembly_TotalElementLoop_SP.cpp][1] file is an exemplar of how they are all laid out currently.

[1]: https://github.com/trilinos/Trilinos/blob/develop/packages/tpetra/core/example/Finite-Element-Assembly/fem_assembly_TotalElementLoop_SP.cpp

## Motivation and Context
The example(s) need to run cleanly on GPU systems.

## Definition of Done
- [ ] `Kokkos::Cuda::Cuda instance constructor : ERROR device not initialized` should go away on CUDA platforms.

## Your Environment
On White:
```
module load devpack/openmpi/1.10.4/gcc/5.4.0/cuda/8.0.44
export TRILINOS_HOME=<path to my Trilinos clone>
export OMPI_CXX=${TRILINOS_HOME}/packages/kokkos/bin/nvcc_wrapper
export CUDA_LAUNCH_BLOCKING=1
export CUDA_MANAGED_FORCE_DEVICE_ALLOC=1
export OMP_NUM_THREADS=4
export OMP_PROC_BIND=spread
```
It's possible that this is the wrong environment for running on the machine correctly which might be causing the messages too ??

## Related Issues
* Related to #2369 -- common main might affect or take care of this??

**Comment by mhoemmen** [comment]
@william76 The common `main` function shouldn't be an issue.  On the other hand, I think I know the problem: `RCP<Tpetra::Map<...>>`.  That's created at a scope such that the RCP's reference count goes to zero _after_ `Tpetra::finalize` gets called.  You don't want any `Kokkos::View` objects (such as might live in the `Tpetra::Map`) to outlive the `Kokkos::finalize` call.

Best way to do this is to lift the example code out of `main` into its own function.

**Comment by william76** [comment]
Ahhh... cool.  Thanks!

**Comment by mhoemmen** [comment]
@william76 I just opened an issue for `Tpetra::Map` to print a helpful message in this case.  See https://github.com/trilinos/Trilinos/issues/2372

**Comment by william76** [comment]
@mhoemmen 

Thanks!  I tested it out on White for just the StaticProfile TotalElementLoop example and the error messages went away!

I'll update the other examples to move the work into a separate function and shoot to get a PR in for this before COB today...

**Comment by mhoemmen** [comment]
Thanks @william76 !  Glad it helps!

**Comment by william76** [comment]
Closing this issue.
