### ISSUE TITLE
Tpetra::Map: Destructor should print warning message if Kokkos or MPI finalized

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#2372]
See discussion here: https://github.com/trilinos/Trilinos/issues/2370#issuecomment-372531179

It's a common error for users' examples to let `Tpetra::Map` instances outlive `Kokkos::finalize` or `MPI_Finalize`.  `Tpetra::Map`'s destructor should warn users about this.  This will avoid users being confused about error or warning messages.

@trilinos/tpetra 

## Expectations

  - `Tpetra::Map`'s destructor should print a helpful warning message, on one MPI process in the communicator only, if `Kokkos::finalize` has already been called.
  - `Tpetra::Map`'s destructor should print a helpful warning message if `MPI_Finalize` has already been called.

## Current Behavior

If `Kokkos::finalize` has already been called, `Tpetra::Map`'s destructor may emit error / warning messages like this:
```
Kokkos::Cuda::Cuda instance constructor : ERROR device not initialized
```
This error message does not explicitly state the problem (which is actually user error) or how to fix it.  Furthermore, every MPI process in the communicator will print this message.

## Motivation and Context

Users and developers often write short example codes in which they instantiate a `Tpetra::Map` (or `RCP<Tpetra::Map>` etc.) in `main()`'s scope.  They don't always realize that the Map may outlive Kokkos and MPI.  For example, the following code is incorrect:
```
#include <cstdlib>
#include "Tpetra_Core.hpp"
#include "Tpetra_Map.hpp"

int main (int argc, char* argv[]) {
  Tpetra::initialize (&argc, &argv);
  // ... get command-line arguments ...
  // Line of code below is WRONG, since Map will outlive Tpetra::finalize.
  Teuchos::RCP<const Tpetra::Map<> > map (new Tpetra::Map<> (...));
  // ... example code follows ...
  Tpetra::finalize ();
  return EXIT_SUCCESS;
}
```
I suggest fixing this by breaking out the example code into a separate function.  This is good for encapsulation anyway.
```
#include <cstdlib>
#include "Tpetra_Core.hpp"
#include "Tpetra_Map.hpp"

void example (...) {
  Teuchos::RCP<const Tpetra::Map<> > map (new Tpetra::Map<> (...));
  // ... example code follows ...
}

int main (int argc, char* argv[]) {
  Tpetra::initialize (&argc, &argv);
  // ... get command-line arguments ...
  example (...);
  Tpetra::finalize ();
  return EXIT_SUCCESS;
}
```

## Definition of Done

See above.

## Possible Solution

See above.

## Steps to Reproduce

See above example.

## Related Issues
* Related to #2370

**Comment by mhoemmen** [comment]
OK, thankfully the PR testing for #2412 actually exercised Tpetra.  #2413 should fix this.

**Comment by mhoemmen** [comment]
Fixed in Trilinos:develop, by PR #2413 that I just merged.  Thanks all!

**Comment by dridzal** [comment]
@mhoemmen @bartlettroscoe 
I'm not calling Tpetra::initialize or Tpetra::finalize.  I'm using

`  Teuchos::GlobalMPISession mpiSession(&argc, &argv);`

which was supposed to handle the communication startup / cleanup (or so I was told some years ago).  Now I get the warning message from Tpetra.  All my test code is within a try{} block, i.e., the maps are created in the try{} scope, *not* at the main() level.  However, they are not in an auxiliary function.  Is the warning the correct behavior?

**Comment by mhoemmen** [comment]
@dridzal Please be a bit patient and I will refine the error message so that it does not appear in your case.

**Comment by mhoemmen** [comment]
@bathmatt I have a follow-on commit done, and am testing various combinations of (MPI ON/OFF, DEBUG/RELEASE).

**Comment by mhoemmen** [comment]
I have tested `SERIAL_RELEASE` with Clang 3.9, and `MPI_DEBUG` and `MPI_RELEASE` with GCC 4.9.3.  Tpetra builds warning-free and passes tests with all three builds.

**Comment by mhoemmen** [comment]
@dridzal @bathmatt The commit I just pushed to develop should satisfy the requirement.  Please open a new issue if you have any further concerns.

**Comment by bartlettroscoe** [comment]
If there is some Kokkos initialization/finalization functions that needs to be called in the constructor and destructor of `Teuchos::GlobalMPISession` then lets add it.  But from looking at the code, is that not already the case?  What needs to be done to address this?  (Note that we can do dependency injection if we need to like I did for the Teuchos::CommandlineProcessor.)
