### ISSUE TITLE
ShyLU subpackage testing - migrate to PT testing

### ISSUE THREAD

**Issue by ndellingwood** [trilinos/Trilinos#2375]
@trilinos/shylu 
All subpackages in ShyLU are currently either ST or EX tested; testing in Basker, Tacho, BDDC, and FROSch should be expanded and packages migrated to PT testing. 

## Motivation and Context

Applications and packages outside of ShyLU are using some of these sub-packages, more robust testing necessary for quality assurance.

**Comment by bartlettroscoe** [comment]
CC: @micahahoward, @srajama1 

Are some ShyLU packages not being used by SPARC?  Looking at some of the SPARC build scripts for Trilinos, you see:

```
do-cmake_trilinos_ats1-hsw_intel_mpich.sh:119:   -D Trilinos_ENABLE_ShyLU=ON \
do-cmake_trilinos_ats1-hsw_intel_mpich.sh:120:   -D Trilinos_ENABLE_ShyLU_DDCore=ON \
do-cmake_trilinos_ats1-hsw_intel_mpich.sh:121:   -D Trilinos_ENABLE_ShyLU_NodeHTS=ON \
do-cmake_trilinos_ats1-knl_intel_mpich.sh:119:   -D Trilinos_ENABLE_ShyLU=ON \
do-cmake_trilinos_ats1-knl_intel_mpich.sh:120:   -D Trilinos_ENABLE_ShyLU_DDCore=ON \
do-cmake_trilinos_ats1-knl_intel_mpich.sh:121:   -D Trilinos_ENABLE_ShyLU_NodeHTS=ON \
do-cmake_trilinos_ride-gpu_gcc_cuda_openmpi.sh:134:   -D Trilinos_ENABLE_ShyLU=OFF \
do-cmake_trilinos_ride-gpu_gcc_cuda_openmpi.sh:135:   -D Trilinos_ENABLE_ShyLUCore=OFF \
do-cmake_trilinos_ride-gpu_gcc_cuda_openmpi.sh:136:   -D Trilinos_ENABLE_ShyLUHTS=OFF \
do-cmake_trilinos_cee-cpu_gcc_openmpi_openmp.sh:129:   -D Trilinos_ENABLE_ShyLU=ON \
do-cmake_trilinos_cee-cpu_gcc_openmpi_openmp.sh:130:   -D Trilinos_ENABLE_ShyLU_DDCore=ON \
do-cmake_trilinos_cee-cpu_gcc_openmpi_openmp.sh:131:   -D Trilinos_ENABLE_ShyLU_NodeHTS=ON \
do-cmake_trilinos_cts1-bdw_intel_openmpi.sh:129:   -D Trilinos_ENABLE_ShyLU=ON \
do-cmake_trilinos_cts1-bdw_intel_openmpi.sh:130:   -D Trilinos_ENABLE_ShyLU_DDCore=ON \
do-cmake_trilinos_cts1-bdw_intel_openmpi.sh:131:   -D Trilinos_ENABLE_ShyLU_NodeHTS=ON \
do-cmake_trilinos_ellis-knl_intel_openmpi.sh:129:   -D Trilinos_ENABLE_ShyLU=ON \
do-cmake_trilinos_ellis-knl_intel_openmpi.sh:130:   -D Trilinos_ENABLE_ShyLU_DDCore=ON \
do-cmake_trilinos_ellis-knl_intel_openmpi.sh:131:   -D Trilinos_ENABLE_ShyLU_NodeHTS=ON \
do-cmake_trilinos_cee-gpu_cuda_gcc_openmpi.sh:144:   -D Trilinos_ENABLE_ShyLU=OFF \
do-cmake_trilinos_cee-gpu_cuda_gcc_openmpi.sh:145:   -D Trilinos_ENABLE_ShyLUCore=OFF \
do-cmake_trilinos_cee-gpu_cuda_gcc_openmpi.sh:146:   -D Trilinos_ENABLE_ShyLUHTS=OFF \
do-cmake_trilinos_shiller-gpu_gcc_cuda_openmpi.sh:144:   -D Trilinos_ENABLE_ShyLU=OFF \
do-cmake_trilinos_shiller-gpu_gcc_cuda_openmpi.sh:145:   -D Trilinos_ENABLE_ShyLUCore=OFF \
do-cmake_trilinos_shiller-gpu_gcc_cuda_openmpi.sh:146:   -D Trilinos_ENABLE_ShyLUHTS=OFF \
do-cmake_trilinos_shiller-hsw_intel_openmpi.sh:129:   -D Trilinos_ENABLE_ShyLU=ON \
do-cmake_trilinos_shiller-hsw_intel_openmpi.sh:130:   -D Trilinos_ENABLE_ShyLU_DDCore=ON \
do-cmake_trilinos_shiller-hsw_intel_openmpi.sh:131:   -D Trilinos_ENABLE_ShyLU_NodeHTS=ON \
do-cmake_trilinos_tlcc2-snb_intel_openmpi.sh:129:   -D Trilinos_ENABLE_ShyLU=ON \
do-cmake_trilinos_tlcc2-snb_intel_openmpi.sh:130:   -D Trilinos_ENABLE_ShyLU_DDCore=ON \
do-cmake_trilinos_tlcc2-snb_intel_openmpi.sh:131:   -D Trilinos_ENABLE_ShyLU_NodeHTS=ON \
do-cmake_trilinos_cee-cpu_intel_mpich_openmp.sh:129:   -D Trilinos_ENABLE_ShyLU=ON \
do-cmake_trilinos_cee-cpu_intel_mpich_openmp.sh:130:   -D Trilinos_ENABLE_ShyLU_DDCore=ON \
do-cmake_trilinos_cee-cpu_intel_mpich_openmp.sh:131:   -D Trilinos_ENABLE_ShyLU_NodeHTS=ON \
```
@micahahoward, is this correct?

If so, these subpackages must to be elevated to PT or they will not get tested in future ATDM Trilinos builds. 

FYI: These new "ATDM" builds for Trilinos are initially being set up to support EMPIRE but as soon as EMPIRE is coverted on all platforms, these configurations will be enhanced to also support SPARC.  For more details, see:

* https://software-sandbox.sandia.gov/jira/browse/TRIL-171
* https://snl-wiki.sandia.gov/display/CoodinatedDevOpsATDM/ATDM+Builds+of+Trilinos

**Comment by srajama1** [comment]
@bartlettroscoe : We are working on the PT testing thing. It is going to take some time. This is more towards future requirements than current requirements. EMPIRE will need ShyLU in the short term though.

**Comment by bartlettroscoe** [comment]
> We are working on the PT testing thing. It is going to take some time. This is more towards future requirements than current requirements. EMPIRE will need ShyLU in the short term though.

@srajama1, thanks for the update.  As soon as EMPIRE starts using ShyLU, we will need to just about immediately turn on the ShyLU subpackages used by EMPIRE in our ATDM builds of Trilinos.  Therefore, it would be good to get the builds and basic test issues with these packages worked out before that happens.  But note that you can be very selective what you enable and what tests you run.  You only need to enable and test what EMPIRE and SPARC are using, not everything in ShyLU.

CC: @bathmatt

**Comment by micahahoward** [comment]
This is correct - we haven't been turning on ShyLU for our CUDA platforms.

**Comment by searhein** [comment]
I have started to work on tests for FROSch in ShyLU_DD; see the pull request #2507.
