### ISSUE TITLE
Zoltan2 Compilation Issue on POWER8 w/ CUDA 7.5

### ISSUE THREAD

**Issue by nmhamster** [trilinos/Trilinos#238]
@trilinos/zoltan2 I am getting this error with a Trilinos VOTD on `white.sandia.gov`. It looks like there may be a preprocessor issue. Have you guys seen something like this before?

```
/ascldap/users/sdhammo/git/trilinos-github-repo/packages/zoltan2/src/algorithms/partition/Zoltan2_AlgMultiJagged.hpp: In member function ‘void Zoltan2::AlgMJ<mj_scalar_t, mj_lno_t, mj_gno_t, mj_part_t>::mj_1D_part(mj_scalar_t*, mj_scalar_t, mj_part_t, mj_part_t, mj_scalar_t*, mj_part_t, std::vector<mj_part_t>&)’:
/ascldap/users/sdhammo/git/trilinos-github-repo/packages/zoltan2/src/algorithms/partition/Zoltan2_AlgMultiJagged.hpp:2838:1: error: expected primary-expression before ‘}’ token
 #endif
 ^
/ascldap/users/sdhammo/git/trilinos-github-repo/packages/zoltan2/src/algorithms/partition/Zoltan2_AlgMultiJagged.hpp: In member function ‘void Zoltan2::AlgMJ<mj_scalar_t, mj_lno_t, mj_gno_t, mj_part_t>::mj_get_new_cut_coordinates(const size_t&, const mj_part_t&, const mj_scalar_t&, const mj_scalar_t&, const mj_scalar_t&, const mj_scalar_t&, mj_scalar_t*, const mj_scalar_t*, const mj_scalar_t*, bool*, mj_scalar_t*, mj_scalar_t*, mj_scalar_t*, mj_scalar_t*, mj_scalar_t*, mj_scalar_t*, mj_scalar_t*, mj_scalar_t*, mj_scalar_t*, mj_part_t*, mj_part_t&)’:
/ascldap/users/sdhammo/git/trilinos-github-repo/packages/zoltan2/src/algorithms/partition/Zoltan2_AlgMultiJagged.hpp:3800:1: error: expected primary-expression before ‘}’ token
 #endif
 ^
/ascldap/users/sdhammo/git/trilinos-github-repo/packages/zoltan2/test/helpers/GeometricGenerator.hpp: In constructor ‘GeometricGen::GeometricGenerator<T1, T2, T3, T4>::GeometricGenerator(Teuchos::ParameterList&, const Teuchos::RCP<const Teuchos::Comm<int> >&)’:
/ascldap/users/sdhammo/git/trilinos-github-repo/packages/zoltan2/test/helpers/GeometricGenerator.hpp:1825:1: error: for statement expected before ‘case’
       case 1:
 ^
/ascldap/users/sdhammo/git/trilinos-github-repo/packages/zoltan2/test/helpers/GeometricGenerator.hpp:1833:1: error: for statement expected before ‘case’
       case 2:
 ^
/ascldap/users/sdhammo/git/trilinos-github-repo/packages/zoltan2/test/helpers/GeometricGenerator.hpp:1841:1: error: for statement expected before ‘case’
       case 3:
 ^
/ascldap/users/sdhammo/git/trilinos-github-repo/packages/zoltan2/test/helpers/GeometricGenerator.hpp: In instantiation of ‘GeometricGen::GeometricGenerator<T1, T2, T3, T4>::GeometricGenerator(Teuchos::ParameterList&, const Teuchos::RCP<const Teuchos::Comm<int> >&) [with scalar_t = double; lno_t = int; gno_t = int; node_t = Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Cuda>]’:
/ascldap/users/sdhammo/git/trilinos-github-repo/packages/zoltan2/test/helpers/UserInputForTests.hpp:885:116:   required from here
/ascldap/users/sdhammo/git/trilinos-github-repo/packages/zoltan2/test/helpers/GeometricGenerator.hpp:1695:21: warning: non-constant array new length must be specified without parentheses around the type-id [-Wvla]
       this->coords[i] = new scalar_t[myPointCount];
                     ^
/ascldap/users/sdhammo/git/trilinos-github-repo/packages/teuchos/numerics/src/Teuchos_SerialDenseMatrix.hpp: In instantiation of ‘Teuchos::SerialDenseMatrix<OrdinalType, ScalarType>& Teuchos::SerialDenseMatrix<OrdinalType, ScalarType>::operator=(const Teuchos::SerialDenseMatrix<OrdinalType, ScalarType>&) [with OrdinalType = int; ScalarType = double]’:
/ascldap/users/sdhammo/git/trilinos-github-repo/packages/galeri/src-xpetra/Galeri_Elasticity3DProblem.hpp:219:4:   required from ‘Teuchos::RCP<Matrix> Galeri::Xpetra::Elasticity3DProblem<Scalar, LocalOrdinal, GlobalOrdinal, Map, Matrix, MultiVector>::BuildMatrix() [with Scalar = double; LocalOrdinal = int; GlobalOrdinal = int; Map = Tpetra::Map<int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Cuda> >; Matrix = Tpetra::CrsMatrix<>; MultiVector = Tpetra::MultiVector<double, int, int>]’
/tmp/tmpxft_0000f6a0_00000000-4_AlltoAll.cudafe1.stub.c:12:27:   required from here
/ascldap/users/sdhammo/git/trilinos-github-repo/packages/teuchos/numerics/src/Teuchos_SerialDenseMatrix.hpp:659:11: warning: non-constant array new length must be specified without parentheses around the type-id [-Wvla]
         values_ = new ScalarType[newsize];
           ^
/ascldap/users/sdhammo/git/trilinos-github-repo/packages/teuchos/numerics/src/Teuchos_SerialDenseMatrix.hpp:679:11: warning: non-constant array new length must be specified without parentheses around the type-id [-Wvla]
           values_ = new ScalarType[newsize];
           ^
make[2]: *** [packages/zoltan2/test/unit/CMakeFiles/Zoltan2_AlltoAll.dir/util/AlltoAll.cpp.o] Error 1
make[1]: *** [packages/zoltan2/test/unit/CMakeFiles/Zoltan2_AlltoAll.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by etphipp** [comment]
Yes, I've run into this before.  NVCC seems to have trouble correctly parsing the OpenMP pragmas.  You can work around it by disabling OpenMP in Zoltan2:

-D Zoltan2_ENABLE_OpenMP=OFF

(I think that's right; I don't have my configure script in front of me).

This is something that should be reported to NVIDIA.

-Eric

On Mar 21, 2016, at 5:33 PM, Si Hammond <notifications@github.com<mailto:notifications@github.com>> wrote:


@trilinos/zoltan2<https://github.com/orgs/trilinos/teams/zoltan2> I am getting this error with a Trilinos VOTD on white.sandia.gov<http://white.sandia.gov>. It looks like there may be a preprocessor issue. Have you guys seen something like this before?

/ascldap/users/sdhammo/git/trilinos-github-repo/packages/zoltan2/src/algorithms/partition/Zoltan2_AlgMultiJagged.hpp: In member function ‘void Zoltan2::AlgMJ<mj_scalar_t, mj_lno_t, mj_gno_t, mj_part_t>::mj_1D_part(mj_scalar_t*, mj_scalar_t, mj_part_t, mj_part_t, mj_scalar_t*, mj_part_t, std::vector<mj_part_t>&)’:
/ascldap/users/sdhammo/git/trilinos-github-repo/packages/zoltan2/src/algorithms/partition/Zoltan2_AlgMultiJagged.hpp:2838:1: error: expected primary-expression before ‘}’ token
 #endif
 ^
/ascldap/users/sdhammo/git/trilinos-github-repo/packages/zoltan2/src/algorithms/partition/Zoltan2_AlgMultiJagged.hpp: In member function ‘void Zoltan2::AlgMJ<mj_scalar_t, mj_lno_t, mj_gno_t, mj_part_t>::mj_get_new_cut_coordinates(const size_t&, const mj_part_t&, const mj_scalar_t&, const mj_scalar_t&, const mj_scalar_t&, const mj_scalar_t&, mj_scalar_t*, const mj_scalar_t*, const mj_scalar_t*, bool*, mj_scalar_t*, mj_scalar_t*, mj_scalar_t*, mj_scalar_t*, mj_scalar_t*, mj_scalar_t*, mj_scalar_t*, mj_scalar_t*, mj_scalar_t*, mj_part_t*, mj_part_t&)’:
/ascldap/users/sdhammo/git/trilinos-github-repo/packages/zoltan2/src/algorithms/partition/Zoltan2_AlgMultiJagged.hpp:3800:1: error: expected primary-expression before ‘}’ token
 #endif
 ^
/ascldap/users/sdhammo/git/trilinos-github-repo/packages/zoltan2/test/helpers/GeometricGenerator.hpp: In constructor ‘GeometricGen::GeometricGenerator<T1, T2, T3, T4>::GeometricGenerator(Teuchos::ParameterList&, const Teuchos::RCP<const Teuchos::Comm<int> >&)’:
/ascldap/users/sdhammo/git/trilinos-github-repo/packages/zoltan2/test/helpers/GeometricGenerator.hpp:1825:1: error: for statement expected before ‘case’
       case 1:
 ^
/ascldap/users/sdhammo/git/trilinos-github-repo/packages/zoltan2/test/helpers/GeometricGenerator.hpp:1833:1: error: for statement expected before ‘case’
       case 2:
 ^
/ascldap/users/sdhammo/git/trilinos-github-repo/packages/zoltan2/test/helpers/GeometricGenerator.hpp:1841:1: error: for statement expected before ‘case’
       case 3:
 ^
/ascldap/users/sdhammo/git/trilinos-github-repo/packages/zoltan2/test/helpers/GeometricGenerator.hpp: In instantiation of ‘GeometricGen::GeometricGenerator<T1, T2, T3, T4>::GeometricGenerator(Teuchos::ParameterList&, const Teuchos::RCP<const Teuchos::Comm<int> >&) [with scalar_t = double; lno_t = int; gno_t = int; node_t = Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Cuda>]’:
/ascldap/users/sdhammo/git/trilinos-github-repo/packages/zoltan2/test/helpers/UserInputForTests.hpp:885:116:   required from here
/ascldap/users/sdhammo/git/trilinos-github-repo/packages/zoltan2/test/helpers/GeometricGenerator.hpp:1695:21: warning: non-constant array new length must be specified without parentheses around the type-id [-Wvla]
       this->coords[i] = new scalar_t[myPointCount];
                     ^
/ascldap/users/sdhammo/git/trilinos-github-repo/packages/teuchos/numerics/src/Teuchos_SerialDenseMatrix.hpp: In instantiation of ‘Teuchos::SerialDenseMatrix<OrdinalType, ScalarType>& Teuchos::SerialDenseMatrix<OrdinalType, ScalarType>::operator=(const Teuchos::SerialDenseMatrix<OrdinalType, ScalarType>&) [with OrdinalType = int; ScalarType = double]’:
/ascldap/users/sdhammo/git/trilinos-github-repo/packages/galeri/src-xpetra/Galeri_Elasticity3DProblem.hpp:219:4:   required from ‘Teuchos::RCP<Matrix> Galeri::Xpetra::Elasticity3DProblem<Scalar, LocalOrdinal, GlobalOrdinal, Map, Matrix, MultiVector>::BuildMatrix() [with Scalar = double; LocalOrdinal = int; GlobalOrdinal = int; Map = Tpetra::Map<int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Cuda> >; Matrix = Tpetra::CrsMatrix<>; MultiVector = Tpetra::MultiVector<double, int, int>]’
/tmp/tmpxft_0000f6a0_00000000-4_AlltoAll.cudafe1.stub.c:12:27:   required from here
/ascldap/users/sdhammo/git/trilinos-github-repo/packages/teuchos/numerics/src/Teuchos_SerialDenseMatrix.hpp:659:11: warning: non-constant array new length must be specified without parentheses around the type-id [-Wvla]
         values_ = new ScalarType[newsize];
           ^
/ascldap/users/sdhammo/git/trilinos-github-repo/packages/teuchos/numerics/src/Teuchos_SerialDenseMatrix.hpp:679:11: warning: non-constant array new length must be specified without parentheses around the type-id [-Wvla]
           values_ = new ScalarType[newsize];
           ^
make[2]: *** [packages/zoltan2/test/unit/CMakeFiles/Zoltan2_AlltoAll.dir/util/AlltoAll.cpp.o] Error 1
make[1]: *** [packages/zoltan2/test/unit/CMakeFiles/Zoltan2_AlltoAll.dir/all] Error 2
make: *** [all] Error 2

**Comment by nmhamster** [comment]
@etphipp thanks! I am trying to be brave and do a build of OpenMP and CUDA on POWER all at the same time. I will re-cmake-configure and make again.

**Comment by nmhamster** [comment]
@etphipp this is working and compiling now (and giving the same results as my serial + CUDA build). I have put some small reproducers through `nvcc` and it looks to be handling them OK. I'll keep trying to get `nvcc` to misbehave and if I find a case I'll file it. Thanks for your help!
