### ISSUE TITLE
Sacado test link error with RDC

### ISSUE THREAD

**Issue by ibaned** [trilinos/Trilinos#2380]
@trilinos/sacado 

This was already emailed to @etphipp , I just thought it might be better tracked as an issue.

## Expectations
Sacado tests should link without error with RDC enabled.

## Current Behavior
In the file packages/sacado/test/tradoptest/CMakeLists.txt there is this code:
 
```cmake
  ADD_CUSTOM_COMMAND(
    OUTPUT ${CMAKE_CURRENT_BINARY_DIR}/radops2_ADC.cpp
    COMMAND ${CMAKE_COMMAND} -E copy ${CMAKE_CURRENT_SOURCE_DIR}/../../src/Sacado_radops2.cpp ${CMAKE_CURRENT_BINARY_DIR}/radops2_ADC.cpp
    DEPENDS ${CMAKE_CURRENT_SOURCE_DIR}/../../src/Sacado_radops2.cpp
    )
 
TRIBITS_ADD_EXECUTABLE_AND_TEST(
  hesopcheck_ADC
  SOURCES hesopcheck_ADC.cpp radops2_ADC.cpp
  ARGS
  COMM serial mpi
  NUM_MPI_PROCS 1
  PASS_REGULAR_EXPRESSION "OK"
  )
```
 
The problem we’re getting is that NVIDIA’s linker see duplicate symbols, because “Sacado_radops2.cpp” exists both inside “libsacado.a” and as radops2_ADC.cpp in the test, so we get many different link errors of this flavor:
 
```
../../src/libsacado.a(Sacado_radops2.cpp.o):(.bss+0x5f00): multiple definition of `Sacado::Rad2d::ADvari::adc'
CMakeFiles/Sacado_hesopcheck_ADC.dir/radops2_ADC.cpp.o:(.bss+0x5f00): first defined here
```

## Motivation and Context

Trying to get a clean build of Trilinos with RDC and tests on.

**Comment by etphipp** [comment]
This should be resolved now.  I had to remove linking of libsacado.a to the test, which required creating the executable with raw cmake instead of tribits.  It seems to work and should resolve the duplicate symbol errors seen with RDC on.  I'm going to close this issue, but it can be reopened if it is still an issue.

**Comment by ibaned** [comment]
Awesome, thanks @etphipp !

@bartlettroscoe is there an easier way in TriBITS to add an executable which does not link to the package's libraries?

**Comment by bartlettroscoe** [comment]
> @bartlettroscoe is there an easier way in TriBITS to add an executable which does not link to the package's libraries?

Add the exectuable before the libraries get added.  That will do it.  Otherwise, no, not at this time.  But that would be a nice feature to allow and seems like the right thing to allow if desired (see TriBITSPub/TriBITS#40).
