### ISSUE TITLE
Teuchos::as<LO> not usable in parallel_for

### ISSUE THREAD

**Issue by ctanis** [trilinos/Trilinos#2382]
PackageName: Tpetra

I am building Trilinos from master, and I get an error in TpetraExtMatrixMatrix_def.hpp line 2901  stating that Teuchos::as (a host function) cannot be called from a device function.  

This is probably due to my Trilinos build configuration, which is attached.  I had a previous version of Trilinos building and working using mostly the same build script.

@trilinos/<teamName>

## Motivation and Context

I cannot compile Trilinos, checked out fresh from master.

[do-config.txt](https://github.com/trilinos/Trilinos/files/1812278/do-config.txt)

**Comment by mhoemmen** [comment]
Fix is in develop: https://github.com/trilinos/Trilinos/issues/2334

Thanks for reporting, though!

**Comment by mhoemmen** [comment]
Hm, I checked both develop and master based on @micahahoward 's e-mail today, and found this:

I’m seeing a line of code, not fixed (calls `Teuchos::as<LO>`), in both develop and master.  Here is develop:

https://github.com/trilinos/Trilinos/blob/8f3d44083a943255c69816d97f19837f07ac78f5/packages/tpetra/core/ext/TpetraExt_MatrixMatrix_def.hpp#L2901

and here is master: 

https://github.com/trilinos/Trilinos/blob/430bf2ab671267200b966275bebb9b8b07322fa4/packages/tpetra/core/ext/TpetraExt_MatrixMatrix_def.hpp#L2901

**Comment by mhoemmen** [comment]
I am working on this now.  Not sure why the CUDA build worked before.

**Comment by mhoemmen** [comment]
@micahahoward I just merged a possible fix (PR #2386).  Had to stay up late on short notice to help get a paper in shape for tomorrow morning, so I may not have gotten this done in time for the nightly tests.

**Comment by mhoemmen** [comment]
@micahahoward If you want to cherry-pick, the SHA1 is  8f5639ba72d2f98aea97543f4f66ffd898badb92.

**Comment by mhoemmen** [comment]
Dashboard is clean.  PR #2386 fixed this.  Thanks all!
