### ISSUE TITLE
Test PanzerAdaptersSTK_MixedPoissonExample-ConvTest-Hex-Order-3 randomly failing and timing out in some GCC and Intel serial builds

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#2383]
**CC:** @fryeguy52

## Description

The test `PanzerAdaptersSTK_MixedPoissonExample-ConvTest-Hex-Order-3` looks to be randomly failing in some ATDM bulids and timing out in other ATDM builds of Trilinos.  You can see all of the builds on hansen where this test either failed or timed out in the last 2 weeks at:

* https://testing-vm.sandia.gov/cdash/queryTests.php?project=Trilinos&date=2018-03-14&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=6&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-hansen-shiller-&field2=testname&compare2=61&value2=PanzerAdaptersSTK_MixedPoissonExample-ConvTest-Hex-Order-3&field3=buildstarttime&compare3=84&value3=2018-03-15&field4=buildstarttime&compare4=83&value4=2018-03-01&field5=buildname&compare5=64&value5=-cuda-&field6=status&compare6=61&value6=failed

That shows the test failing wtih the builds `Trilinos-atdm-hansen-shiller-gnu-debug-serial` and `Trilinos-atdm-hansen-shiller-gnu-opt-serial` and timing out with the build `Trilinos-atdm-hansen-shiller-intel-debug-serial`.

One error for the build `Trilinos-atdm-hansen-shiller-gnu-debug-serial` for example at:

* https://testing-vm.sandia.gov/cdash/testDetails.php?test=44093773&build=3358992

shows:

```
libgomp: Invalid value for environment variable OMP_NUM_THREADS

libgomp: Invalid value for environment variable OMP_NUM_THREADS

libgomp: Invalid value for environment variable OMP_NUM_THREADS

libgomp: Invalid value for environment variable OMP_NUM_THREADS
Teuchos::GlobalMPISession::GlobalMPISession(): started processor with name hansen02 and rank 0!
Teuchos::GlobalMPISession::GlobalMPISession(): started processor with name hansen02 and rank 1!
Teuchos::GlobalMPISession::GlobalMPISession(): started processor with name hansen02 and rank 2!
Teuchos::GlobalMPISession::GlobalMPISession(): started processor with name hansen02 and rank 3!
p=0 | CubeHexMesh: Building sub cells

libgomp: Thread creation failed: Resource temporarily unavailable
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpiexec detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[54941,1],1]
  Exit code:    1
--------------------------------------------------------------------------
```

It looks like we are sestting the value of OMP_NUM_THREADS incorrectly.

**Comment by bartlettroscoe** [comment]
I have not mentioned the Panzer team yet because looking at this some I think the problem might just be that we need to unset `OMP_NUM_THREADS` when not doing an OpenMP build.

I am going to try to experiment with unsetting `OMP_NUM_THREADS` and see if the warnings and timeouts go away.

**Comment by rppawlo** [comment]
There is a race condition on the output file in this test directory as well that showed up in last nights debug testing. Will fix that today.

**Comment by rppawlo** [comment]
Darn - I take that back - the race is only on the curl problem. The Mixed basis is something else...

**Comment by bartlettroscoe** [comment]
From looking at [this query](https://testing-vm.sandia.gov/cdash/queryTests.php?project=Trilinos&date=2018-06-07&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=17&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-&field2=status&compare2=62&value2=passed&field3=status&compare3=62&value3=notrun&field4=buildname&compare4=62&value4=Trilinos-atdm-mutrino-intel-debug-openmp&field5=buildname&compare5=62&value5=Trilinos-atdm-mutrino-intel-opt-openmp&field6=buildname&compare6=62&value6=Trilinos-atdm-white-ride-cuda-debug-pt-all-at-once&field7=buildname&compare7=62&value7=Trilinos-atdm-serrano-intel-debug-openmp&field8=buildname&compare8=62&value8=Trilinos-atdm-serrano-intel-opt-openmp&field9=buildname&compare9=62&value9=Trilinos-atdm-chama-intel-opt-openmp&field10=buildname&compare10=62&value10=Trilinos-atdm-chama-intel-debug-openmp-panzer&field11=buildname&compare11=62&value11=Trilinos-atdm-chama-intel-debug-openmp&field12=buildname&compare12=62&value12=Trilinos-atdm-chama-intel-opt-openmp-panzer&field13=testname&compare13=61&value13=PanzerAdaptersSTK_MixedPoissonExample-ConvTest-Hex-Order-3&field14=site&compare14=62&value14=ride&field15=buildstarttime&compare15=84&value15=2018-06-07&field16=buildstarttime&compare16=83&value16=2018-05-07&field17=site&compare17=62&value17=serrano), this test `PanzerAdaptersSTK_MixedPoissonExample-ConvTest-Hex-Order-3` only timed out 4 times in the builds `Trilinos-atdm-rhel6-gnu-debug-openmp` and `Trilinos-atdm-rhel6-gnu-debug-serial` between 5/7 and 5/11/2018 and not since 5/11/2018.  This makes me think these were system issues on that 'sems-rhel6' machine for those few days (perhaps other Jenkins jobs running and overloading the machine?).

Therefore, since there have been no failures or timeouts of this test (which we know to be an expensive test) since 5/11/2018 in the promoted builds, I think it is safe to close this issue.

Closing as complete.

NOTE: If this CDash `queryTests.php` page had a `Group` filter, then it would be easy to query just the promoted "ATDM" CDash Group builds.  This will get done in https://gitlab.kitware.com/snl/project-1/issues/55.

**Comment by bartlettroscoe** [comment]
Closing as complete for real this time :-)
