### ISSUE TITLE
Building Trilinos on Power 8+ CUDA environment

### ISSUE THREAD

**Issue by keitat** [trilinos/Trilinos#2392]
I am curious if anybody can share the experience of building Trillions (2nd generation packages) on Power 8 + CUDA environment.  I have been struggling to build and run Tpetra examples on IBM testbed platforms.

**Comment by nmhamster** [comment]
@keitat - it works. How can we help? :)

**Comment by keitat** [comment]
Can I get your version of CMAKE script?

**Comment by nmhamster** [comment]
Are you using white/ride and the developer packs?

**Comment by keitat** [comment]
I am using 12.12.1 on white/ride.

**Comment by keitat** [comment]
I need to use Tpetra/Kokkos with CUDA enabled.

**Comment by jhux2** [comment]
@keitat You can get configure options one of two ways.

  1. from the [ATDM dashboard](https://testing.sandia.gov/cdash/index.php?project=Trilinos&filtercount=1&showfilters=1&field1=buildname&compare1=63&value1=-atdm-).

  2. Follow the directions in the section "Steps to Reproduce" in issue#2319.  @bartlettroscoe has done a nice job of making it easy to build Trilinos on various testbeds, including Ride, using the same configuration as the ATDM apps need.

**Comment by bartlettroscoe** [comment]
More information on the ATDM builds of Trilinos can be found at:

* https://snl-wiki.sandia.gov/display/CoodinatedDevOpsATDM/ATDM+Builds+of+Trilinos

If you can't get to that site, the basic instructions are in:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md

Please let me know if you find any typos or other problems with that documentation or this process.

**Comment by keitat** [comment]
```
source ../Trilinos/cmake/std/atdm/load-env.sh  kt.job.batch
Error, hostname = 'ride6' not recognized as a known ATDM system name!
Error, could not determine known system, aborting env loading

```

It appears ride is not recognized as an ATDM system.

**Comment by bartlettroscoe** [comment]
> It appears ride is not recognized as an ATDM system.

Are you on the 'master' branch or the 'develop' branch?  Ride is supported on the 'develop' branch.  Don't know when the 'master' branch gets updated.

**Comment by ndellingwood** [comment]
@keitat replacing `kt.job.batch` with `cuda-opt` as the jobname should hopefully fix this for you, I just tried it out on Ride, and also had hostname as ride6.
Also, if you want a debug build with Cuda, `cuda-debug` should be used as the jobname. 

Other jobname examples are listed about mid-way through the Quick Start guide from Ross's second link above. 

Sample output:
```
-bash-4.2$ source ../../cmake/std/atdm/load-env.sh cuda-opt
Hostname 'ride6' matches known ATDM host 'ride' and system 'ride'
ATDM_CONFIG_TRILNOS_DIR = /home/ndellin/trilinos/Trilinos
Setting default compiler and build options for JOB_NAME='cuda-opt'
Using white/ride compiler stack CUDA to build RELEASE code with Kokkos node type CUDA

```

**Comment by bartlettroscoe** [comment]
The supported keywords for builds is documented at:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#quick-start

You can't pick some arbitrary job name.  It has to have these keywords in the name.  That is how the system works.

**Comment by keitat** [comment]
Switched to GitHub version.  It is working fine.
