### ISSUE TITLE
MueLu Breaking CUDA Builds

### ISSUE THREAD

**Issue by nmhamster** [trilinos/Trilinos#2395]
Latest from Shiller with developer pack for HSW/CUDA9.0.

```
[ 94%] Building CXX object packages/muelu/src/CMakeFiles/muelu.dir/Utils/ExplicitInstantiation/MueLu_AggregationExportFactory.cpp.o
nvcc fatal   : Unknown option 'Wno-unused-local-typedefs'
make[2]: *** [packages/muelu/src/CMakeFiles/muelu.dir/build.make:63: packages/muelu/src/CMakeFiles/muelu.dir/Utils/ExplicitInstantiation/MueLu_AggregationExportFactory.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:14374: packages/muelu/src/CMakeFiles/muelu.dir/all] Error 2
```

**Comment by nmhamster** [comment]
@trilinos/muelu FYI

**Comment by nmhamster** [comment]
This seems to fix it for now:

```
#IF ((CMAKE_CXX_COMPILER_ID MATCHES "GNU") AND (CMAKE_CXX_COMPILER_VERSION VERSION_GREATER "4.7"))
#  SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wno-unused-local-typedefs")
#ENDIF()
```

I realize this is not good, perhaps we could do a "if building CUDA then ignore"

**Comment by jhux2** [comment]
@nmhamster Shouldn't `CMAKE_CXX_COMPILER_ID MATCHES "GNU"` prevent cmake from adding this option?

**Comment by nmhamster** [comment]
It seems as though nvcc_wrapper identifies the compiler as GCC but then when compiling the code nvcc is invoked, as expected and the flag fails. We may be able to extract this via nvcc_wrapper if needed but I worry that is unscalable.

**Comment by jhux2** [comment]
@nmhamster Fix has been pushed.  I verified that if CUDA is enabled, `-Wno-unused-local-typedefs` is not appended to `CMAKE_CXX_FLAGS`.  Closing this issue, please reopen if necessary.

**Comment by mhoemmen** [comment]
I changed the title for easier searching.
