### ISSUE TITLE
remove or fix the broken cuda/panzer test

### ISSUE THREAD

**Issue by bathmatt** [trilinos/Trilinos#2399]
mySourceTerm.cpp doesn't compile under cuda, can it be removed or fixed.  This is an old issue @jmgate can you please resolve?  Its your code.
Thanks

**Comment by bathmatt** [comment]
This may be something to do with lambda and not always supporting them under cuda..

**Comment by bathmatt** [comment]
sure, we can disable...  Not sure why it is failing, just is.. 

It also looks like mini-EM doesn't run on cuda, I'm trying to track down an issue with empire and it looks like there are several, but mini-em also shows the problem, trying to reproduce on stiller now

**Comment by jmgate** [comment]
Very good&mdash;working on it.  Was in the midst of a big Trilinos rebuild though, so it'll be a little while.

**Comment by bathmatt** [comment]
Once this is done, @jmgate can you add the examples to the trillions build and test?

**Comment by jmgate** [comment]
Sorry, @bathmatt, what do you mean?  #2402 removed this example from Trilinos' build and test&mdash;you want me to turn it back on?

**Sidenote:**  Does anyone know why GitHub's keywords (closes, resolves, etc.) in PRs only close issues some of the time?
