### ISSUE TITLE
duplicate TPL adapters

### ISSUE THREAD

**Issue by nschloe** [trilinos/Trilinos#24]
In Trilinos, TriBits takes care of some of the TPL integration via the files in

```
cmake/tribits/common_tpls/FindTPL*.cmake
```

Their counterparts in

```
cmake/TPLs/FindTPL*.cmake
```

are redundant and should probably be removed.

**Comment by mhoemmen** [comment]
@bartlettroscoe @bmpersc 

Hi Ross and Brent -- just tagging you on this.
