### ISSUE TITLE
Add  InvRowSums method to Tpetra 

### ISSUE THREAD

**Issue by ikalash** [trilinos/Trilinos#240]
It looks like Epetra has an InvRowSums method, but not Tpetra.  Would it be possible to add the InvRowSums method to Tpetra?  It will faciliate some scaling implementations in Albany.

**Comment by mhoemmen** [comment]
Fixed in master, a while back.  See `Trilinos/packages/ifpack2/example/RelaxationWithEquilibration.cpp`.  It computes row and column one norms, and gives you a way to scale a matrix by them.
