### ISSUE TITLE
ShyLU : Create user guide

### ISSUE THREAD

**Issue by srajama1** [trilinos/Trilinos#2401]
@trilinos/shylu 

@ndellingwood will take the first pass to create a template. The rest of us will fill it in.

**Comment by searhein** [comment]
Do we already have a template? If so, I would start working on the the FROSch part of the user guide.

**Comment by srajama1** [comment]
@ndellingwood : Yes, two weeks is good time for me. Thanks for taking the initiative on creating the documentation.

**Comment by ndellingwood** [comment]
Here's the link to the documentation directory in ShyLU [shylu/doc/intro](https://github.com/trilinos/Trilinos/tree/master/packages/shylu/doc/intro). Each package has a tex file for its chapter, file name formatted as `ShyLU_Intro_{PackageName}.tex`

**Comment by crdohrm** [comment]
Next two to three weeks should work for me.
