### ISSUE TITLE
Test TeuchosNumerics_LAPACK_test_MPI_1 fails in all 'debug' builds on power8 'ride'

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#2410]
**CC:** @trilinos/teuchos 

## Next Action Status:

PR #2447 was merged on 3/23/2018 which disabled the test.   PR #4064 which enables the whole test `TeuchosNumerics_LAPACK_test_MPI_1` but disables the single unit test for `STEQR()` merged to 'develop' on 12/18/2018.  Next: Watch for test running and passing (minus `STEQR()` unit test) on 'release-debug' and 'opt' builds on 'white', 'ride', and 'waterman' on 12/19/2018 ...

## Description

The test `TeuchosNumerics_LAPACK_test_MPI_1` segfaults on the 'debug' builds `Trilinos-atdm-white-ride-cuda-debug` and `Trilinos-atdm-white-ride-gnu-debug-openmp` on 'ride' and 'white' but passes in all of the 'opt' builds on these same machines as well as for all of the builds on `hansen` as shown this morning in:

* https://testing-vm.sandia.gov/cdash/queryTests.php?project=Trilinos&date=2018-03-17&filtercombine=and&filtercombine=and&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-&field2=testname&compare2=61&value2=TeuchosNumerics_LAPACK_test_MPI_1

The failing tests all show segfaults showing the output:

```
Teuchos in Trilinos 12.13 (Dev)

GESV test ... passed!
LAPY2 test ... passed!
--------------------------------------------------------------------------
mpiexec noticed that process rank 0 with PID 16320 on node white24 exited on signal 11 (Segmentation fault).
--------------------------------------------------------------------------
```

What is interesting is that this test only failed in all of the Trilinos builds that were done yesterday in the query:

* https://testing-vm.sandia.gov/cdash/queryTests.php?project=Trilinos&date=2018-03-16&filtercombine=and&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-&field2=testname&compare2=61&value2=TeuchosNumerics_LAPACK_test_MPI_1&field3=status&compare3=62&value3=passed

May this be the same error reported in #1208 that we basically gave up on?

## Steps to Reproduce

Following the instructions at:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#ridewhite

one can reproduce this failing test by enabling the Teuchos package for the builds `gnu-debug-openmp` or `cuda-debug` and running the failing test.

## Related issues

* Related to: #1208?

**Comment by bartlettroscoe** [comment]
What is strange about this is that we see only 1 failing Belos test and 2 failing Anasazi tests for the build `Trilinos-atdm-white-ride-gnu-debug-openmp` shown at:

* https://testing-vm.sandia.gov/cdash/index.php?project=Trilinos&parentid=3373978

and only the one Belos test looks to be segfaulting.  But with the corresponding build `Trilinos-atdm-white-ride-gnu-opt-openmp` shown at:

* https://testing-vm.sandia.gov/cdash/index.php?project=Trilinos&parentid=3373731

there are 8 failing Belos tests and 50 failing Anasazi tests which a lot of them are segfaults but this this test `TeuchosNumerics_LAPACK_test_MPI_1` is not failing in that build.

Again, I suspect this might be related to to #1208 that concluded that this compiler on this system is just broken when it comes to producing mixed-language programs.

**Comment by bartlettroscoe** [comment]
Note that this test actually passes in all of the `opt` builds as well as on white/ride as well as shown at:

* https://testing-vm.sandia.gov/cdash/testSummary.php?project=1&name=TeuchosNumerics_LAPACK_test_MPI_1&date=2018-03-23

So that compiler defect analyzed in #1208 does not seem to be impacting this test when compiler optimizations are turned on.

**Comment by bartlettroscoe** [comment]
Since this test is passing in all of the other builds, including all of the `opt` builds for each compiler on each machine, I think disabling this test for these `debug` builds on white/ride is not a bad thing.

Do any of you @trilinos/teuchos developers have a problem with that?

I will create a PR that disables this test for just the builds where it fails which are:

* `Trilinos-atdm-white-ride-cuda-debug`
* `Trilinos-atdm-white-ride-gnu-debug-openmp`

I will create a PR for this.

**Comment by bartlettroscoe** [comment]
I created PR #2447 that disables this test for just these builds.  

Can some @trilinos/teuchos developer please approve this PR?  Otherwise, since this is not really changing Trilinos at all (just the ATDM Trilinos test drivers), it can't possibly break Trilinos so I will merge in a few hours.  I just want to see what the auto PR tester does for a PR like this.  I suspect that because it touches a `*.cmake` file that will result in all of Trilinos getting tested (which actually will not be testing anything because that PR does not impact any of the auto PR builds, at least not yet).

**Comment by bartlettroscoe** [comment]
The PR #2447 has been merged.  These failures should go away tomorrow.  Putting in review.

**Comment by bartlettroscoe** [comment]
The test `TeuchosNumerics_LAPACK_test_MPI_1` is newly missing from the builds `Trilinos-atdm-white-ride-cuda-debug` and `Trilinos-atdm-white-ride-gnu-debug-openmp` as shown at:

* https://testing-vm.sandia.gov/cdash/viewTest.php?onlyfailed&buildid=3389503

and

* https://testing-vm.sandia.gov/cdash/viewTest.php?onlyfailed&buildid=3389489

And this test is shown passing in all of the remaining builds in:

* https://testing-vm.sandia.gov/cdash/queryTests.php?project=Trilinos&date=2018-03-24&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-&field2=testname&compare2=61&value2=TeuchosNumerics_LAPACK_test_MPI_1

Therefore, closing this as complete.

**Comment by bartlettroscoe** [comment]
Closing as complete for real (I seems to always forget to click that "Close and comment" button).

**Comment by bartlettroscoe** [comment]
As part the updated process listed at:

* https://snl-wiki.sandia.gov/display/CoodinatedDevOpsATDM/ATDM+Builds+of+Trilinos#ATDMBuildsofTrilinos-Addressingfailures

I assigned the labels "Disabled Tests" and "Stalled" so I am reopening this issue. That way, people can be reminded that this is still a problem (we just avoided it by disabling tests for the ATDM builds).

**Comment by bartlettroscoe** [comment]
Given the updated NetLIB BLAS and LAPACK being used on 'white' and 'ride' (see #2454) I tried re-enabling the test `TeuchosNumerics_LAPACK_test_MPI_1` for the 'debug' builds on 'white' and 'ride'.  I tried this with the commit 7958ac7b913e0efc083f738663489f134056b328 I made locally and on 'white' I ran:

```
$ bsub -x -I -q rhel7F -n 16 \
   ./checkin-test-atdm.sh cuda-debug gnu-debug-openmp \
   --enable-packages=Teuchos --local-do-all
```

that returned:

```
FAILED (NOT READY TO PUSH): Trilinos: white22

Sat May  5 17:14:03 MDT 2018

Enabled Packages: Teuchos

Build test results:
-------------------
0) MPI_RELEASE_DEBUG_SHARED_PT => Test case MPI_RELEASE_DEBUG_SHARED_PT was not run! => Does not affect push readiness! (-1.00 min)
1) cuda-debug => FAILED: passed=130,notpassed=1 => Not ready to push! (1.49 min)
2) gnu-debug-openmp => FAILED: passed=130,notpassed=1 => Not ready to push! (0.97 min)
```

The failing tests were:

```
$ find . -maxdepth 2 -name ctest.out -exec grep -H "[(]Failed[)]" {} \;
./gnu-debug-openmp/ctest.out:   119 - TeuchosNumerics_LAPACK_test_MPI_1 (Failed)
./cuda-debug/ctest.out: 119 - TeuchosNumerics_LAPACK_test_MPI_1 (Failed)
```

The failing test output for the build `gnu-debug-openmp/` showed:

```
Teuchos in Trilinos 12.13 (Dev)

GESV test ... passed!
LAPY2 test ... passed!
--------------------------------------------------------------------------
mpiexec noticed that process rank 0 with PID 44747 on node white22 exited on signal 11 (Segmentation fault).
--------------------------------------------------------------------------
```

That is identical to the failure output reported [above](https://github.com/trilinos/Trilinos/issues/2410#issue-306176566) when this Issue was first created.

Also, I verified in the configure output that the new NetLIB BLAS and LAPACK installs are indeed being used as it showed:

```
Processing enabled TPL: BLAS (enabled explicitly, disable with -DTPL_ENABLE_BLAS=OFF)
-- BLAS_LIBRARY_NAMES='blas blas_win32'
-- TPL_BLAS_LIBRARIES='-L/home/projects/pwr8-rhel73-lsf/netlib/3.8.0/gcc/5.4.0/lib;-lblas;-lgfortran;-lgomp;-lm'
Processing enabled TPL: LAPACK (enabled explicitly, disable with -DTPL_ENABLE_LAPACK=OFF)
-- LAPACK_LIBRARY_NAMES='lapack lapack_win32'
-- TPL_LAPACK_LIBRARIES='-L/home/projects/pwr8-rhel73-lsf/netlib/3.8.0/gcc/5.4.0/lib;-llapack;-lgfortran;-lgomp'
```

So whatever is causing this test to fail did not get fixed by updating BLAS and LAPACK.

Perhaps there is a real defect in the Teuchos LAPACK wrappers and/or the test code for this test?

**Comment by nmhamster** [comment]
@bartlettroscoe - to re-comment as well, the OpenBLAS tests for the packages we install (fairly limited number) do also all pass and do have C to FORTRAN calling included. That’s what makes me wonder if this might be a deeper issue too.

**Comment by fryeguy52** [comment]
This test is also failing on both debug builds on waterman, [shown here](https://testing-vm.sandia.gov/cdash/queryTests.php?project=Trilinos&date=2018-08-20&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-waterman-&field2=testname&compare2=61&value2=TeuchosNumerics_LAPACK_test_MPI_1&field3=buildstarttime&compare3=84&value3=now) those builds are:

- Trilinos-atdm-waterman-gnu-debug-openmp
- Trilinos-atdm-waterman-cuda-9.2-debug

They fail with similar output:
```
Teuchos in Trilinos 12.13 (Dev)

GESV test ... passed!
LAPY2 test ... passed!
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpiexec noticed that process rank 0 with PID 0 on node waterman1 exited on signal 11 (Segmentation fault).
--------------------------------------------------------------------------
```
Should we disable `TeuchosNumerics_LAPACK_test_MPI_1 ` for these builds as well?

**Comment by hkthorn** [comment]
@fryeguy52 @bartlettroscoe Please let me know if the LAPACK test is still failing after the OpenMPI version is changed for the ATDM waterman testing.

**Comment by bartlettroscoe** [comment]
@hkthorn, as shown [here](https://testing-vm.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=and&date=2018-08-28&filtercombine=and&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-waterman&field2=status&compare2=62&value2=passed&field3=status&compare3=62&value3=notrun), the test is still failing.    It would be nice to get to the bottom of this test failure at some point.  NOTE: The same failure is happening on 'white' and 'ride' as well, so we had it disabled there.

**Comment by nmhamster** [comment]
@hkthorn / @bartlettroscoe - can we run one of these tests in a debugger (gdb) an see where the code is failing? It would be really good if we could get a stack trace for the segmentation-fault if possible. I am not sure if the rounding modes on the platform factor into this or not.

**Comment by bartlettroscoe** [comment]
@nmhamster said:

> can we run one of these tests in a debugger (gdb) an see where the code is failing? 

That should be possible with the build `gnu-debug-openmp` for example.

**Comment by hkthorn** [comment]
Ok, so in looking at the failure of #3338, it is clear that there is an issue with the _STEQR routine in LAPACK, similar to the issue on waterman.  I have gone over the test of this routine and it is sane.  The next thing to do is to run it through a debugger.  The LAPACK tests are so limited at this time, they only test 3 routines.  They should be expanded in the near future to test more routines and in a way that is more informative when they fail.  Given that they are essential to many iterative solvers in Trilinos, it should be a priority.

**Comment by hkthorn** [comment]
@bartlettroscoe @nmhamster I have the gnu-debug-openmp build with the Teuchos LAPACK test ready to debug.  However gdb is telling me that it doesn't have the required debuginfo package:

Missing separate debuginfos, use: debuginfo-install glibc-2.17-222.el7.ppc64le numactl-libs-2.0.9-7.el7.ppc64le

I have minimized the test of the STEQR method to a simple diagonal matrix and still get a seg fault.  So, there is not much more I can do without the debugging symbols because the LAPACK method is being fed the correct arguments.

**Comment by hkthorn** [comment]
@trilinos/teuchos @mhoemmen @bartlettroscoe 

I have been expanding the Teuchos LAPACK test on ride to poke around the edges of this issue.  I have added about 10 more LAPACK routines to the test, some with character arguments and work vectors and they are executing without segfaults on this platform.  

So, I did a little more digging on the _STEQR method in the LAPACK library.  It turns out it is considered an auxiliary routine, not a primary routine.  So, it is used by other methods to compute eigenvalues and eigenvectors.  Of course, it can be used by itself.   But auxiliary methods can be tricky in that you have to ensure you are passing in the right arguments.  I can replace the call with one to _SPEQR and the code works again.

**Comment by bartlettroscoe** [comment]
CC: @etphipp, @nmhamster 

@hkthorn said:

> So, I did a little more digging on the _STEQR method in the LAPACK library. It turns out it is considered an auxiliary routine, not a primary routine. So, it is used by other methods to compute eigenvalues and eigenvectors. Of course, it can be used by itself. But auxiliary methods can be tricky in that you have to ensure you are passing in the right arguments. I can replace the call with one to _SPEQR and the code works again.

@hkthorn, on the side, @etphipp has been experimenting with STEQR and found that if he built it along side Stokhos, it worked.  I am not sure what that suggests but that is not good.

Can we create a PR with your changes including calling _SPEQR on this machine and get the LAPCK tests re-enabled?  (I can help to put in specializations to falling _SPEQR instead of STEQR on this machine

I am going to remove the "Disabled Tests" label so that this issue shows up in the main list of ATDM issues again.

**Comment by etphipp** [comment]
What is SPEQR?  I can't find documentation on such a method nor find it in the LAPACK library itself.

**Comment by bartlettroscoe** [comment]
@etphipp said:

> What is SPEQR? I can't find documentation on such a method nor find it in the LAPACK library itself.

@hkthorn, was `_SPEQR` in your [above](https://github.com/trilinos/Trilinos/issues/2410#issuecomment-427129718) comment a typo?  Did you mean `_STEQR`?

**Comment by bartlettroscoe** [comment]
@hkthorn, do you have your expanded LAPACK test suite on a branch?  Can we see about getting that merged into the main Trilinos 'develop' branch?

We might consider a workaround where we convert this DSPEQR() into C code with f2c and then build it with C++ inside of Teuchos, just for these IBM Power platforms.

@nmhamster, @etphipp, and @hkthorn, what do you think about that idea?

**Comment by mhoemmen** [comment]
> We might consider a workaround where we convert this DSPEQR() into C code with f2c and then build it with C++ inside of Teuchos, just for these IBM Power platforms.

If we're going to do that, we could just do it for the whole LAPACK library, no?

**Comment by bartlettroscoe** [comment]
@mhoemmen said:

> If we're going to do that, we could just do it for the whole LAPACK library, no? That would be easier to set up.

If we do that, we might as well just build and install [CLAPACK](https://www.netlib.org/clapack/) with [CBLAS](https://www.netlib.org/clapack/cblas/) built with C++ to eliminate any mixed-language issues.

**Comment by mhoemmen** [comment]
> If we do that, we might as well just build and install [CLAPACK](https://www.netlib.org/clapack/) with [CBLAS](https://www.netlib.org/clapack/cblas/) built with C++ to eliminate any mixed-language issues.

I agree that we shouldn't waste too much time dealing with a broken LAPACK library on a particular platform.

**Comment by bartlettroscoe** [comment]
I think we should just try downloading:

* https://github.com/NIRALUser/CLAPACK/blob/master/SRC/dsteqr.c

renaming it to dsteqr.cpp, building it with C++ in Teuchos with on 'white'/'ride' and see if it fixes the problem.  The work that @kruger did in #1208 suggested that even C++ to C mixed language calls were broken in some cases in the Power8 with GCC.

**Comment by hkthorn** [comment]
> What is SPEQR? I can't find documentation on such a method nor find it in the LAPACK library itself.

Sorry, wrong letters.  I was using _PTEQR, instead of _SPEQR.  It has the same call sequence, but _PTEQR is meant to be called by the users and is not an auxiliary routine for LAPACK.

**Comment by mhoemmen** [comment]
@hkthorn I'm curious if this is a degenerate case -- say zero rows.  Some BLAS implementations care about LDA > 0 even for zero-sized matrices.

**Comment by mhoemmen** [comment]
@hkthorn Huh, that actually suggests the BLAS or LAPACK is broken.  XERBLA (did I mention how much I like saying that word?) is supposed to catch LDA = 0 etc.

**Comment by hkthorn** [comment]
@mhoemmen The _STEQR performed correctly when being passed an LDA of zero.  I tested the corner case just to see how far the method got, if it performed any sanity checking or if it just barfed immediately.  The use cases in Trilinos all pass in an LDA of one because they are not looking to compute the eigenvectors, just the values, so that is all that is needed.

-----<snip>----
      ELSE IF( ( LDZ.LT.1 ) .OR. ( ICOMPZ.GT.0 .AND. LDZ.LT.MAX( 1,
     $         N ) ) ) THEN
         INFO = -6
      END IF
      IF( INFO.NE.0 ) THEN
         CALL XERBLA( 'DSTEQR', -INFO )
         RETURN
      END IF
-----<snap>----

**Comment by bartlettroscoe** [comment]
@hkthorn and @mhoemmen, thanks for pushing on this.  I think if we can resolve this issue with _STEQR then a bunch of failing tests in the candidate CUDA PR build (#2464) will get fixed (see #3542, #3552).

> I have extended the LAPACK test locally to exercise more of the Teuchos::LAPACK functions and I have no problem checking it in. While the tests check for numerical failure of the routines, they don't capture seg faults, which is what is happening in this instance.

@hkthorn, please go ahead and create a PR with the extended LAPACK test suite as long as they pass the PR builds.  What doe you mean by "they don't capture seg faults"?  This LAPACK executable already segfaults on 'white', 'ride', and 'waterman' so in that sense, it already expose the seg fault problem.

**Comment by hkthorn** [comment]
@bartlettroscoe I was saying that it would be nice to trap the seg fault with the test and report that back.  With the modest improvements to the number of LAPACK tests, I was poking around to see if other LAPACK routines cause a seg fault on those platforms.  They don't, so I looked at using a different LAPACK method that accomplishes what the Belos CG condition estimate computation needs.  It has no issue running on those platforms.  I will submit the PR, as you ask.

**Comment by bartlettroscoe** [comment]
> I was saying that it would be nice to trap the seg fault with the test and report that back. 

The only way that I know to "trap" a segfault is to run a different process and then grep the output and/or check the return code to verify that a segfault occurred.  But since segfaults are usually caused by undefined behavior, such a test would not be portable.  The problem is the raw usage of memory.

**Comment by jjellio** [comment]
@hkthorn 
One option would be to dump the 'core', and then print a backtrace using it.

You could follow this:
https://serverfault.com/questions/61659/can-you-get-any-program-in-linux-to-print-a-stack-trace-if-it-segfaults

Its a linux-only solution, but it does give you the ability to debug something postmortem.

**Comment by bartlettroscoe** [comment]
FYI: I added the new label "ATDM Env Issue" since this is caused by problems with the env on the IBM Power machines as far as we can tell.

**Comment by bartlettroscoe** [comment]
PR #4064 which enables the whole test `TeuchosNumerics_LAPACK_test_MPI_1` but disables the single unit test for `STEQR()` merged to 'develop' on 12/18/2018.  Next: Watch for test running and passing (minus `STEQR()` unit test) on 'release-debug' and 'opt' builds on 'white', 'ride', and 'waterman' on 12/19/2018 ...

Putting 'in review' awaiting results on CDash ...

**Comment by bartlettroscoe** [comment]
The test `TeuchosNumerics_LAPACK_test_MPI_1` is now running and passing in all of the the 'debug' builds on 'white', 'ride', and 'waterman' as shown today in [this query](https://testing.sandia.gov/cdash-dev-view/queryTests.php?project=Trilinos&date=2018-12-19&filtercount=2&showfilters=1&filtercombine=or&field1=block&field1count=2&field1field1=buildname&field1compare1=65&field1value1=Trilinos-atdm-white-ride-&field1field2=testname&field1compare2=61&field1value2=TeuchosNumerics_LAPACK_test_MPI_1&field2=block&field2count=2&field2field1=buildname&field2compare1=65&field2value1=Trilinos-atdm-waterman-&field2field2=testname&field2compare2=61&field2value2=TeuchosNumerics_LAPACK_test_MPI_1) (note the usage of the experimental OR-block filter).  For example, we can see this test newly passing in the build [Trilinos-atdm-white-ride-cuda-9.2-debug](https://testing.sandia.gov/cdash-dev-view/testDetails.php?test=62007766&build=4325513) with test results showing:

```
GESV test ... passed!
LAPY2 test ... passed!
LAMCH test ... [ Double-precision eps = 1.11022e-16, single-precision eps = 5.96046e-08 ] passed!
POTRF test ... passed!
POCON test ... passed!
POTRI test ... passed!
TRTRI test ... passed!
ILAENV test ... passed!
STEQR test ... SKIPPED!
End Result: TEST PASSED
```

Note `STEQR test ... SKIPPED!` in the output.

As of right now, all of the 'debug' builds (but not the 'release-debug' builds) on 'white', 'ride', and 'waterman' have already posted to CDash and we can see this test running and passing in 32 of the ATM Trilinos builds in [this query](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&date=2018-12-19&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=3&showfilters=1&filtercombine=and&field1=groupname&compare1=62&value1=Experimental&field2=buildname&compare2=65&value2=Trilinos-atdm-&field3=testname&compare3=61&value3=TeuchosNumerics_LAPACK_test_MPI_1).

And there are no more disables for this test in any of the ATDM Trilinos builds as shown on 'develop' just now by the commands:

```
$ git log-short --name-status -1
b0fd3c1 "Merge Pull Request #4083 from mhoemmen/Trilinos/Fix-4080"
Author: trilinos-autotester <trilinos-autotester@trilinos.org>
Date:   Wed Dec 19 06:39:32 2018 -0700 (47 minutes ago)

$ find cmake/std/atdm/ -name "*.cmake" -exec grep -nH TeuchosNumerics_LAPACK_test_MPI_1 {} \;
[empty]
```

Therefore, I think this is sufficient evidence that this test is running and passing in every ATM Trilinos build, including all of the 'debug' builds on 'white', 'ride', and 'waterman'.  The only thing that is not running is the `STEQR()` unit test and that unit test is only disabled on the IBM Power8 'white/ride'and Power9 'waterman' machines.

I have added the "Disabled Tests" label but I actually think now that we have got Trilinos to stop using this LAPACK `STEQR()` function that we should actually close this issue.  Agree?
