### ISSUE TITLE
Tpetra::Details::computeOffsets*: Missing fence for UVM

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#2416]
@bathmatt reported an issue with `Tpetra::Details::computeOffsetsFromCounts` on CUDA:

https://github.com/trilinos/Trilinos/blob/a60ff45d9f0180d8782904546eb10165d15031af/packages/tpetra/core/src/Tpetra_Details_computeOffsets.hpp#L373

Note that the function returns an entry of a `CudaUVMSpace` array on host, without an intervening fence.  `Tpetra::Details::computeOffsetsFromConstantCount` has the same issue.  @bathmatt says that changing the following line:

https://github.com/trilinos/Trilinos/blob/a60ff45d9f0180d8782904546eb10165d15031af/packages/tpetra/core/src/Tpetra_Details_computeOffsets.hpp#L371

to say `if (std::is_same<Kokkos::HostSpace,` fixes the issue.  The following line in `computeOffsetsFromConstantCount` would need to change accordingly:

https://github.com/trilinos/Trilinos/blob/a60ff45d9f0180d8782904546eb10165d15031af/packages/tpetra/core/src/Tpetra_Details_computeOffsets.hpp#L461

@trilinos/tpetra

**Comment by mhoemmen** [comment]
working on this

**Comment by tjfulle** [comment]
@mhoemmen, let me know if I can help!

**Comment by mhoemmen** [comment]
Thanks @tjfulle !  It's an easy fix; I'm testing now.

**Comment by mhoemmen** [comment]
A good fix will reuse the existing `Tpetra::Details::getEntryOnHost` function :-) .  It uses fences if needed, and also has an optimization for avoiding a host memory allocation (as `Kokkos::create_mirror_view` may do).

**Comment by mhoemmen** [comment]
Fixed in PR #2425.  Thanks all!
