### ISSUE TITLE
Xpetra library build failures breaking all ATDM CUDA builds

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#2420]
**CC:** @trilinos/xpetra, @csiefer2, @rppawlo 

## Description

The Xpetra libraries failed to build with the CUDA builds on 'shiller', 'white', and 'ride' this morning as shown at:

* https://testing-vm.sandia.gov/cdash/index.php?project=Trilinos&date=2018-03-20&filtercombine=and&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=63&value1=-atdm-&field2=buildname&compare2=63&value2=-cuda-

with build failure details shown at:

* https://testing-vm.sandia.gov/cdash/viewBuildError.php?buildid=3380783

This showed errors starting out with:

```
/home/rabartl/WHITE/ATDM_Driver/Trilinos-atdm-white-ride-cuda-debug/SRC_AND_BUILD/Trilinos/packages/xpetra/src/MultiVector/Xpetra_MultiVectorFactory.hpp(156): error: object of abstract class type "Xpetra::TpetraMultiVector<double, int, int, Xpetra::EpetraNode>" is not allowed:
            pure virtual function "Xpetra::MultiVector<Scalar, LocalOrdinal, GlobalOrdinal, Node>::isSameSize [with Scalar=double, LocalOrdinal=int, GlobalOrdinal=int, Node=Xpetra::EpetraNode]" has no overrider

...
```

and

```
/home/rabartl/WHITE/ATDM_Driver/Trilinos-atdm-white-ride-cuda-debug/SRC_AND_BUILD/Trilinos/packages/xpetra/src/MultiVector/Xpetra_MultiVectorFactory.hpp(156): error: object of abstract class type "Xpetra::TpetraMultiVector<double, int, int, Xpetra::EpetraNode>" is not allowed:
            pure virtual function "Xpetra::MultiVector<Scalar, LocalOrdinal, GlobalOrdinal, Node>::isSameSize [with Scalar=double, LocalOrdinal=int, GlobalOrdinal=int, Node=Xpetra::EpetraNode]" has no overrider
...
```

Looking at the new commits pulled in these builds today at:

* https://testing-vm.sandia.gov/cdash/viewNotes.php?buildid=3380783#!#note1

the likely breaking commit is from the set of commits:

```
cd1628f:  Tpetra: Fixing merge issue in MultiVector
Author: Chris Siefert <csiefer@sandia.gov>
Date:   Mon Mar 19 14:24:46 2018 -0600

M	packages/tpetra/core/src/Tpetra_MultiVector_decl.hpp
M	packages/tpetra/core/src/Tpetra_MultiVector_def.hpp

009fafc:  Xpetra: Updates to BlockedMultiVector
Author: Chris Siefert <csiefer@sandia.gov>
Date:   Mon Mar 19 13:29:33 2018 -0600

M	packages/xpetra/src/BlockedMultiVector/Xpetra_BlockedMultiVector.hpp

d9771e2:  Tpetra: Adding Stokhos-compatible size checker to MultiVector
Author: Chris Siefert <csiefer@sandia.gov>
Date:   Thu Feb 22 12:49:18 2018 -0700

M	packages/tpetra/core/src/Tpetra_MultiVector_decl.hpp
M	packages/tpetra/core/src/Tpetra_MultiVector_def.hpp
```

## Steps to Reproduce

Anyone with access to the machines 'white', 'ride', 'shiller' or 'hansen' should be able to reproduce these build failures using the `cuda-opt` or `cuda-debug` builds as described at:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md

More specifically, after cloning Trilinos on any of these four machines, do:

```
$ cd <some_build_dir>/

$ source $TRILINOS_DIR/cmake/std/atdm/load-env.sh cuda-opt

$ cmake \
  -GNinja \
  -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
  -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_Xpetra=ON \
  $TRILINOS_DIR

$ make NP=16
```

**Comment by bartlettroscoe** [comment]
@csiefer2, 

Looking at the diffs for these commits, it seems likely the commits associated with the push:

```
commit cd1628f8f081a7c977839a636574f6194b0a9a03
Author: Chris Siefert <csiefer@sandia.gov>
Date:   Mon Mar 19 14:24:46 2018 -0600

    Tpetra: Fixing merge issue in MultiVector
    
    Build/Test Cases Summary
    Enabled Packages: MueLu, TpetraCore, Xpetra
    Disabled Packages: PyTrilinos,Claps,TriKota,Tempus,Rythmos,ROL
    Enabled all Forward Packages
    0) MPI_RELEASE_DEBUG_SHARED_PT => passed: passed=1234,notpassed=0 (139.22 min)
    Other local commits for this build/test group: 009fafc, 673c7e0, 7919c39, 3c623a6, fa8abf2, d9771e2, fe44041
```

are the cause of these CUDA failures.  Could you see if you can reproduce these build failures on one of the machines and see about getting this fixed?  Otherwise, let me know and I can likely back out these commits pretty quickly (I am testing the reverts right now).

I think that the Panzer developers (@rppawlo and @bathmatt) have been trying to resolve some runtime issues with CUDA for EMPIRE and I think these build failures might set them back.  Therefore, I think getting this fixed or backing out the commits is somewhat urgent.

(BTW: Thanks for using the checkin-test-sems.sh script since it shows exactly the commits that are grouped together and need to be backed out (or fixed).  But using a topic branch to merge these in would make backing them out even easier.  I will provide better instructions on using the checkin-test-sems.sh script with the new topic branch and PR testing workflow.)

**Comment by bartlettroscoe** [comment]
The PR #2421 reverts the breaking commits and I verified that it fixes the build of Xpetra for the CUDA builds.

Therefore, someone just needs to let the auto PR testing run and then click 'merge' and this will fix the CUDA build.  Then @csiefer2 can fix the CUDA build problems offline in a relaxed way.

**Comment by ikalash** [comment]
I think we encountered the same problem on the Cori and Edison NERSC machines in Albany nightly testing: https://my.cdash.org/viewBuildError.php?buildid=1386990 .  It is curious that the problem only showed up there, not the other Albany nightlies.  Maybe it is due to slightly different configuration options?

**Comment by ikalash** [comment]
It also happened on Ride Albany nightlies: http://cdash.sandia.gov/CDash-2-3-0/viewBuildError.php?buildid=68364 .

**Comment by csiefer2** [comment]
Gotta love really configuration-specific bugs...

**Comment by csiefer2** [comment]
Huh.  Weird.  These errors are all namespacing issues and aren't directly related to the code I touched.

**Comment by csiefer2** [comment]
Xpetra builds just fine on my first attempt.  Now to figure out why Ross' build is different...

**Comment by csiefer2** [comment]
@bartlettroscoe Your configure script does not work on ride
CMake Error at cmake/std/atdm/ATDMDevEnv.cmake:186 (MESSAGE):
  Error: ToDo: Implement default HDF5 libs
Call Stack (most recent call first):
  cmake/tribits/core/package_arch/TribitsGlobalMacros.cmake:182 (INCLUDE)
  cmake/tribits/core/package_arch/TribitsProjectImpl.cmake:96 (TRIBITS_READ_IN_OPTIONS_FROM_FILE)
  cmake/tribits/core/package_arch/TribitsProject.cmake:93 (TRIBITS_PROJECT_IMPL)
  CMakeLists.txt:90 (TRIBITS_PROJECT)

**Comment by bartlettroscoe** [comment]
@csiefer2,

Can you please provide the exact commands that you typed?  Also, are you using bash or csh?  I think you need to use bash for this to work.

**Comment by csiefer2** [comment]
source ../Trilinos/cmake/std/atdm/load-env.sh intel-opt-openmp

cmake \
  -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
  -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_Xpetra=ON \
  ../Trilinos

**Comment by csiefer2** [comment]
It doesn't work on white either:

Error, hostname = 'white11' not recognized as a known ATDM system name!

**Comment by bartlettroscoe** [comment]
@csiefer2,

Sorry, I made a copy-and-paste error in the `Steps to Reproduce` section listing ` intel-opt-openmp` when it should have been `cuda-opt` or `cuda-debug`.  (There is no `intel` compiler build supported on that system.)

Using `cuda-opt` I reproduced this with:

```
$ echo $SHELL
bash

$ cd Trilinos/

$ git pull
...

$ git log-short --name-status -1
6f87587 "Change default ot --no-rebase for topic-branch workflows (#1155)"
Author: Roscoe A. Bartlett <rabartl@sandia.gov>
Date:   Mon Mar 19 19:32:20 2018 -0600 (14 hours ago)

M       project-checkin-test-config.py

$ mkdir BUILD/
$ cd BUILD/

$ source ../cmake/std/atdm/load-env.sh cuda-opt
Hostname 'ride6' matches known ATDM host 'ride' and system 'ride'
ATDM_CONFIG_TRILNOS_DIR = /home/rabartl/Trilinos.base/Trilinos
Setting default compiler and build options for JOB_NAME='cuda-opt'
Using white/ride compiler stack CUDA to build RELEASE code with Kokkos node type CUDA

$ module list
Currently Loaded Modulefiles:
  1) ninja/1.7.2
  2) cuda/8.0.44
  3) numa/2.0.11
  4) papi/5.5.0
  5) zlib/1.2.8
  6) mpfr/3.1.5
  7) mpc/1.0.3
  8) gmp/6.1.0
  9) isl/0.17.1
 10) cloog/0.18.4
 11) gcc/5.4.0
 12) java/ibm/sdk/8.0.0
 13) openmpi/1.10.4/gcc/5.4.0/cuda/8.0.44
 14) pnetcdf/1.6.1/openmpi/1.10.4/gcc/5.4.0/cuda/8.0.44
 15) hdf5/1.8.17/openmpi/1.10.4/gcc/5.4.0/cuda/8.0.44
 16) netcdf/4.4.1/openmpi/1.10.4/gcc/5.4.0/cuda/8.0.44
 17) cgns/3.2.1/openmpi/1.10.4/gcc/5.4.0/cuda/8.0.44
 18) openblas/0.2.19/gcc/5.4.0
 19) superlu/4.3.0/gcc/5.4.0
 20) boost/1.60.0/openmpi/1.10.4/gcc/5.4.0/cuda/8.0.44
 21) metis/5.0.1/gcc/5.4.0
 22) parmetis/4.0.3/openmpi/1.10.4/gcc/5.4.0/cuda/8.0.44
 23) yaml-cpp/20170104
 24) curl/7.47.1
 25) cmake/3.10.2
 26) tcl/8.5.19
 27) perl/5.22.1
 28) openssl/1.0.2j
 29) git/2.10.1
 30) valgrind/3.11.0
 31) devpack/openmpi/1.10.4/gcc/5.4.0/cuda/8.0.44

$ time cmake \
   -GNinja \
   -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
   -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_Xpetra=ON \
   .. &> configure.out

real    0m59.442s
user    0m40.143s
sys     0m11.583s

$ cd packages/xpetra/sup/

$ make help-objects | grep Xpetra_ThyraUtils
  CMakeFiles/xpetra-sup.dir/Utils/Xpetra_ThyraUtils.cpp.o

$ make NP=16 CMakeFiles/xpetra-sup.dir/Utils/Xpetra_ThyraUtils.cpp.o
...

[1/1] Building CXX object packages/xpetra/sup/CMakeFiles/xpetra-sup.dir/Utils/Xpetra_ThyraUtils.cpp.o
FAILED: packages/xpetra/sup/CMakeFiles/xpetra-sup.dir/Utils/Xpetra_ThyraUtils.cpp.o 
/home/projects/pwr8-rhel73-lsf/openmpi/1.10.4/gcc/5.4.0/cuda/8.0.44/bin/mpicxx   -I. -I../packages/xpetra/sup/Matrix -I../packages/xpetra/sup/StridedMap -I../packages/xpetra/sup/Cloner -I../packages/xpetra/sup/Utils -Ipackages/xpetra/sup -I../packages/xpetra/src/CrsGraph -I../packages/xpetra/src/CrsMatrix -I../packages/xpetra/src/BlockedCrsMatrix -I../packages/xpetra/src/DistObject -I../packages/xpetra/src/Export -I../packages/xpetra/src/Headers -I../packages/xpetra/src/Import -I../packages/xpetra/src/Map -I../packages/xpetra/src/BlockedMap -I../packages/xpetra/src/MultiVector -I../packages/xpetra/src/BlockedMultiVector -I../packages/xpetra/src/BlockedVector -I../packages/xpetra/src/Operator -I../packages/xpetra/src/Platform -I../packages/xpetra/src/RowGraph -I../packages/xpetra/src/RowMatrix -I../packages/xpetra/src/Utils -I../packages/xpetra/src/Utils/ForwardDeclaration -I../packages/xpetra/src/Vector -Ipackages/xpetra/src -I../packages/thyra/adapters/tpetra/src -I../packages/thyra/adapters/epetra/src -I../packages/thyra/core/src -I../packages/thyra/core/src/interfaces/operator_vector/fundamental -I../packages/thyra/core/src/interfaces/operator_vector/extended -I../packages/thyra/core/src/support/operator_vector/client_support -I../packages/thyra/core/src/support/operator_vector/adapter_support -I../packages/thyra/core/src/interfaces/operator_solve/fundamental -I../packages/thyra/core/src/interfaces/operator_solve/extended -I../packages/thyra/core/src/support/operator_solve/client_support -I../packages/thyra/core/src/interfaces/nonlinear/model_evaluator/fundamental -I../packages/thyra/core/src/support/nonlinear/model_evaluator/client_support -I../packages/thyra/core/src/interfaces/nonlinear/solvers/fundamental -I../packages/thyra/core/src/support/nonlinear/solvers/client_support -Ipackages/thyra/core/src -I../packages/thyra/core/example/operator_vector -I../packages/rtop/src -I../packages/rtop/src/interfaces -I../packages/rtop/src/support -I../packages/rtop/src/ops_lib -I../packages/rtop/src/lapack -Ipackages/rtop/src -I../packages/teuchos/numerics/src -I../packages/teuchos/comm/src -I../packages/teuchos/parameterlist/src -I../packages/teuchos/parser/src -Ipackages/teuchos/core/src -I../packages/teuchos/core/src -Ipackages/kokkos/core/src -I../packages/kokkos/core/src -I/ascldap/users/projects/pwr8-rhel73-lsf/cuda/8.0.44/include -I/ascldap/users/projects/pwr8-rhel73-lsf/boost/1.60.0/openmpi/1.10.4/gcc/5.4.0/cuda/8.0.44/include -Ipackages/epetra/src -I../packages/epetra/src -Ipackages/teuchos/kokkoscomm/src -I../packages/teuchos/kokkoscomm/src -Ipackages/teuchos/kokkoscompat/src -I../packages/teuchos/kokkoscompat/src -I../packages/teuchos/remainder/src -Ipackages/teuchos/remainder/src -I../packages/tpetra/core/ext -Ipackages/tpetra/core/ext -I../packages/tpetra/core/inout -Ipackages/tpetra/core/inout -I../packages/tpetra/core/src -I../packages/tpetra/core/src/kokkos_refactor -Ipackages/tpetra/core/src -I../packages/tpetra/classic/LinAlg -I../packages/tpetra/classic/NodeAPI -Ipackages/tpetra/classic/NodeAPI -Ipackages/tpetra/classic/src -I../packages/tpetra/classic/src -Ipackages/kokkos-kernels/src -I../packages/kokkos-kernels/src -I../packages/kokkos-kernels/src/impl -I../packages/kokkos-kernels/src/impl/tpls -I../packages/kokkos-kernels/src/blas -I../packages/kokkos-kernels/src/blas/impl -I../packages/kokkos-kernels/src/sparse -I../packages/kokkos-kernels/src/sparse/impl -I../packages/kokkos-kernels/src/graph -I../packages/kokkos-kernels/src/graph/impl -I../packages/kokkos-kernels/src/batched -I../packages/kokkos-kernels/src/batched/impl -I../packages/kokkos-kernels/src/common -Ipackages/kokkos/algorithms/src -I../packages/kokkos/algorithms/src -Ipackages/kokkos/containers/src -I../packages/kokkos/containers/src -I../packages/thyra/adapters/epetraext/src/model_evaluator -I../packages/thyra/adapters/epetraext/src/transformer -Ipackages/epetraext/src -I../packages/epetraext/src -I../packages/epetraext/src/transform -I../packages/epetraext/src/inout -I../packages/epetraext/src/coloring -I../packages/epetraext/src/model_evaluator -I../packages/epetraext/src/block -I../packages/epetraext/src/restrict -Ipackages/triutils/src -I../packages/triutils/src --std=c++11 -expt-extended-lambda -arch=sm_37   -O3 -DNDEBUG -MD -MT packages/xpetra/sup/CMakeFiles/xpetra-sup.dir/Utils/Xpetra_ThyraUtils.cpp.o -MF packages/xpetra/sup/CMakeFiles/xpetra-sup.dir/Utils/Xpetra_ThyraUtils.cpp.o.d -o packages/xpetra/sup/CMakeFiles/xpetra-sup.dir/Utils/Xpetra_ThyraUtils.cpp.o -c ../packages/xpetra/sup/Utils/Xpetra_ThyraUtils.cpp
../packages/xpetra/src/MultiVector/Xpetra_MultiVectorFactory.hpp(156): error: object of abstract class type "Xpetra::TpetraMultiVector<double, int, int, Xpetra::EpetraNode>" is not allowed:
            pure virtual function "Xpetra::MultiVector<Scalar, LocalOrdinal, GlobalOrdinal, Node>::isSameSize [with Scalar=double, LocalOrdinal=int, GlobalOrdinal=int, Node=Xpetra::EpetraNode]" has no overrider
...
```

Let me know if you have any trouble reproducing with the job keys `cuda-opt` or `cuda-debug`.

P.S. I will add better error handling when selecting a compiler that is not supported on a system.

**Comment by csiefer2** [comment]
Still no dice on white (probably related to the machine upgrade), but configure works on ride.  Building now...

**Comment by bartlettroscoe** [comment]
> Still no dice on white (probably related to the machine upgrade)

We will see what happens with automated testing on 'white' tomorrow and then go from there.

> Building now...

Okay.  Sorry for the typo.

**Comment by csiefer2** [comment]
Xpetra builds fine on ride using your script.

I'm at a bit of a loss now.

**Comment by ikalash** [comment]
There was a failure in the Albany Ride build too.  You will find the configure options here starting in line 161: 
https://github.com/gahansen/Albany/blob/master/doc/dashboards/ride.sandia.gov/ctest_nightly.cmake.frag .  The modules loaded are here: https://github.com/gahansen/Albany/blob/master/doc/dashboards/ride.sandia.gov/ride_modules_cuda.sh .

**Comment by bartlettroscoe** [comment]
> Xpetra builds fine on ride using your script.

@csiefer2,

That is very strange.  What version of Trilinos did you test; the exact SHA1?  Can you provide the exact commands and output that I showed in detail [above](https://github.com/trilinos/Trilinos/issues/2420#issuecomment-374650516)?  If you type the exact same commands and in the same order (and show the relevant output), then we should be able to see what is happening.

We need to get the bottom of why the ATDM Trilinos Jenkins jobs, the Albany Jenkins jobs and my own account all produce the same errors but your account does not.  It has to be either an env issue or a Trilinos version issue.  There is not really much else that can go wrong with these simple commands.

**Comment by csiefer2** [comment]
@ikalash I looked at the Albany errors and via hand-inspection I might have figured out what was going on... Checkin script is running on that...

**Comment by ikalash** [comment]
@csiefer2  That's great.  I will check tomorrow if the builds are back to normal.

**Comment by csiefer2** [comment]
@bartlettroscoe Ah, I was building off of master... This bites me every time I build on a new machine...

**Comment by bartlettroscoe** [comment]
> Ah, I was building off of master... This bites me every time I build on a new machine...

@csiefer2, okay, that is good to know.  I was thinking we were in the Twilight Zone for a minute there :-)

Let me know if you have any trouble reproducing the build failure there now.

FYI: You can also us the checkin-test-atdm.sh wrapper to test your locally changes for the ATDM builds as described at:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#ridewhite

But just don't push to 'develop' directly from those machines.  It is better to test with the checkin-test-sems.sh from a SEMS machine.  (NOTE: I think if you post a PR branch right now the PR builds will fail due to an existing Amesos2 build failure but you should to that in any case as that is now the preferred way to test and push to Trilinos.)

**Comment by jhux2** [comment]
>  Ah, I was building off of master... This bites me every time I build on a new machine...
> 
@csiefer2 See issue #2003 for a script work around.

**Comment by csiefer2** [comment]
@bartlettroscoe Issue now reproducible on ride.  And my "by inspection" patch seems to fix the error.  That's been pushed to develop, so if you could test things on your side and see if things are fixed to your satisfaction, that would be great.

@jhux2 Cool!

**Comment by bartlettroscoe** [comment]
>  Issue now reproducible on ride. And my "by inspection" patch seems to fix the error. That's been pushed to develop, so if you could test things on your side and see if things are fixed to your satisfaction, that would be great.

Thanks @csiefer2.  I will close PR #2421 and put this Issue in review and close tomorrow after getting a clean build on CDash.

**Comment by bartlettroscoe** [comment]
> > Ah, I was building off of master... This bites me every time I build on a new machine...
> 
> See issue #2003 for a script work around.

@csiefer2 and @jhux2,

One thing that helps me with this a lot is to use the git command prompt script `git-prompt.sh` as described at:

* https://github.com/trilinos/Trilinos/wiki/VC-%7C-Initial-Git-Setup

Then can see which branch your are on in the command prompt like:

```
[rabartl@ride6 Trilinos (develop)]$ 
```

If I was on 'master', I would see:

```
[rabartl@ride6 Trilinos (master)]$ 
```

Very helpful for topic-branch workflows.

**Comment by csiefer2** [comment]
Nice tool...  for bash users...

**Comment by bartlettroscoe** [comment]
> Nice tool... for bash users...

The tide to bash is pretty strong at this point.  Kind of like the tide from CVS to git ...

**Comment by jhux2** [comment]
> One thing that helps me with this a lot is to use the git command prompt script git-prompt.sh as described at:

Yep, I use this all the time.

**Comment by csiefer2** [comment]
LOL!  And I still use CVS too.  Go figure :)

**Comment by ikalash** [comment]
@csiefer2 : I just checked and everything is back to normal with the Albany tests, so this issue has indeed been resolved.

**Comment by bartlettroscoe** [comment]
The CUDA builds on hansen that ran later in the day were also now cleaned up as shown by the build and test results for Xpetra and MueLu at:

* https://testing.sandia.gov/cdash/index.php?project=Trilinos&date=2018-03-20&filtercount=4&showfilters=1&filtercombine=and&field1=buildname&compare1=63&value1=-atdm-hansen-shiller-&field2=buildname&compare2=64&value2=-panzer&field3=subprojects&compare3=93&value3=Xpetra&field4=subprojects&compare4=93&value4=MueLu

And the CUDA builds and tests for Xpetra and MueLu on 'white' and 'ride' were clean today as shown at:

* https://testing.sandia.gov/cdash/index.php?project=Trilinos&date=2018-03-21&filtercount=4&showfilters=1&filtercombine=and&field1=buildname&compare1=63&value1=-atdm-white-ride-&field2=buildname&compare2=64&value2=-panzer&field3=subprojects&compare3=93&value3=Xpetra&field4=subprojects&compare4=93&value4=MueLu

Therefore, I think this is safe to close now.

Thanks for fixing so quickly @csiefer2!
