### ISSUE TITLE
Framework:  Add a GPU test into nightlies

### ISSUE THREAD

**Issue by william76** [trilinos/Trilinos#2423]
@trilinos/framework 

Add GPU testing into a nightly build under the Experimental track to run on a testbed.

## Motivation and Context
Nightly tests currently don't run a GPU build consistently... we'd like to move towards getting a GPU based test into the Nightly Clean track eventually and possibly even into the Pull Request test suite.  The first step towards this is to work up a test in the Experimental track that can run the suite on a testbed machine with GPUs and get the errors cleaned up.

## Definition of Done
- [ ] Add GPU test on White (?)

@jwillenbring - per our discussion this morning, I'm adding the issue to track this.

**Comment by william76** [comment]
I've already started building and running tests on White for work I'm doing with Tpetra, so I have some scripts and configurations that work with the CUDA compilers.  

Building on the testbeds don't sound too complicated, there's no special environment for that... but running the jobs using the queueing system might be a challenge since we'll need to have jenkins block until the job finishes.  I have some ideas on that... but haven't tried anything out yet.

**Comment by bmpersc** [comment]
@william76 SEMS already has examples of using the testbed's queue while still having the jenkins job wait for the results so that issue is already solved. The biggest issue is that there is no good way to tie the jenkins timeout of a job to when the testbed's queuing system actually starts running the job. Basically if a job waits in the testbed's queue for a long time that can cause an issue where jenkins will report a failure due to timeout when the job would have succeeded if it had been allowed to complete. This hasn't been much of an issue for the existing nightly tests, but it might be more problematic for tests that run more frequently.

**Comment by bartlettroscoe** [comment]
FYI: Jobs run with `bsub` on 'white' are currently being prematurely terminated before they complete.  The Test Beds team knows about this and is working on this.  For more details, see:

* https://software-sandbox.sandia.gov/jira/browse/TRIL-198

> Basically if a job waits in the testbed's queue for a long time that can cause an issue where jenkins will report a failure due to timeout when the job would have succeeded if it had been allowed to complete.

You can address that by passing the real timeout into the `bsub` or 'srun` commands and then just have the Jenkins job terminate the build if it does not start and complete by the end of the testing day.  To see an example of this, take a look at:

* https://jenkins-son.sandia.gov/view/Trilinos%20ATDM/job/Trilinos-atdm-hansen-shiller-cuda-opt/configure

the associated scripts that it calls, and more info at:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/ctest/drivers/atdm/README.md

**Comment by william76** [comment]
@trilinos/framework 
@jwillenbring 
With the GPU test running in the PR testing and Dev->Master jobs, should we consider this issue complete?

**Comment by william76** [comment]
Closing out an old issue that's probably been fixed or is no longer relevant.

**Comment by bartlettroscoe** [comment]
We have a bunch of these in the ATDM Trilinos builds.
