### ISSUE TITLE
MueLu: uncoupled aggregation kokkos refactor

### ISSUE THREAD

**Issue by lucbv** [trilinos/Trilinos#2430]
@trilinos/muelu 

## Expectations
Aggregation algorithm need to be refactored to run efficiently on new architectures

## Current Behavior
aggregation runs on new platform but large parts of the code are still serial

## Motivation and Context
This will be useful for simulation on advanced platform coming in production.

## Definition of Done
- [ ] rewrite aggregation algorithms using kokkos
- [ ] check that the new algorithms compile with both OpenMP and CUDA nodes
- [ ] verify that the aggregates created using these algorithm are reasonable for MueLu's use

## Possible Solution
pull request xxx is submitted with a proposed implementation that should scale reasonable well at least with OpenMP.

**Comment by lucbv** [comment]
@jhux2, @aprokop I am working on PR #2136 and in it I rely on the `MueLu_LWGraph_kokkos` to provide `maxNumRowEntries_` and I use that value to create some scratch view.
On CPU this was fine but on GPU it leads to very large memory allocations that fail in L0 cache.
I double checked the value returned by `maxNumRowEntries_` and it is larger than the number of rows. My best bet is that it actually returns the total number of edges on the graph.

I will work on fixing this in my PR but if either of you is using this functionality, beware of its behavior!

**Comment by aprokop** [comment]
@lucbv I'll start looking at your work on the Kokkos refactor. Give me a couple days to catch up on your work. I also need to remember how the code is organized. Is #2136 the only PR I should be looking at, or is there more work around?

**Comment by lucbv** [comment]
At this point this is the only PR but it has a good deal of changes in it and at this point I already have some changes to make for @jhux2, we have identified some issues in Phase2b that need to be resolved.
So far the code compiles and run on KNL (despite bugs to be fixed) and compiles on Power+GPU but does not run because of the bug I mentioned above.
I can post another message when I am done fixing the issues we discovered with @jhux2, that would be a good time to have a fresh set of eyes looking at it.

**Comment by aprokop** [comment]
@lucbv How long do you think it would take?

**Comment by lucbv** [comment]
@aprokop it depends a little on my schedule, this week I am busy on another project but I can get my part done early next week and we can coordinates with @jhux2 for the review.
Does that work for you?

**Comment by aprokop** [comment]
@lucbv Sure. I am looking at other phases right now.

**Comment by jhux2** [comment]
@lucbv Can this updated and/or closed?

**Comment by lucbv** [comment]
I think I will close this issue and reopen a new one as this is all quite stale now and the code base changed significantly enough to make a merge of the old work easy.
