### ISSUE TITLE
Header in Tpetra example code

### ISSUE THREAD

**Issue by keitat** [trilinos/Trilinos#2438]
I just found that I cannot build an example program of Teprta (with Kokkos) as the Kokkos_Core header is missing.   In fact, my include directory of Trilinos build does not include it.  Am I missing something?

See Trilinos/packages/tpetra/core/example/Lesson07-Kokkos-Fill/05_solve.cpp
 `#include <Kokkos_Core.hpp>`

**Comment by keitat** [comment]
I see the build process successfully create an executable, but I am not sure how to build from library version of Trilinos as I cannot find the header from my Trilinos build.

**Comment by keitat** [comment]
It appears I do not have to include Kokkos_Core.hpp to get object file.  Now I am struggling with building a full CMakeList.txt file so that it can work with my own Trilinos build.  Do you have any examples?

**Comment by keitat** [comment]
Here is what I have:

[ 50%] Building CXX object CMakeFiles/tpetra_example.dir/tpetra_example.cpp.o
In file included from /ascldap/users/knteran/Trilinos_LIB/include/KokkosCompat_ClassicNodeAPI_Wrapper.hpp:5:0,
                 from /ascldap/users/knteran/Trilinos_LIB/include/Kokkos_DefaultNode.hpp:47,
                 from /ascldap/users/knteran/Trilinos_LIB/include/Tpetra_ConfigDefs.hpp:46,
                 from /ascldap/users/knteran/Trilinos_LIB/include/Tpetra_CrsMatrix_decl.hpp:53,
                 from /ascldap/users/knteran/Trilinos_LIB/include/Tpetra_CrsMatrix.hpp:1,
                 from /ascldap/users/knteran/examples/tpetra_example.cpp:9:
/ascldap/users/knteran/Trilinos_LIB/include/KokkosCompat_View.hpp:58:27: fatal error: Kokkos_Core.hpp: No such file or directory
compilation terminated`
`

**Comment by mhoemmen** [comment]
@keitat The examples build and run with nightly tests on the Dashboard.  If you just want to build and run them, you could set `Tpetra_ENABLE_EXAMPLES:BOOL=ON`.

**Comment by mhoemmen** [comment]
What I mean, is that if you are building Trilinos from source anyway, then all you need to do is turn on Tpetra's examples in your Trilinos build.  Then, the examples will build.  You can modify their source code in place if you want to experiment.

**Comment by keitat** [comment]
Another problem is that Kokkos_Core.h is not copied to the install directory after "make install".  I am not sure why this is happening.

**Comment by keitat** [comment]
`cmake -GNinja -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake -DTrilinos_ENABLE_KOKKOS=ON   -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_Tpetra=ON  -DTPL_ENABLE_CUDA:BOOL=ON -DTrilinos_ENABLE_CUDA:BOOL=ON -DTRILINOS_ENABLE_BELOS:BOOL=ON -DTrilinos_ENABLE_Ifpack2:BOOL=ON -DKOKKOS_DEVICE_ARCH=Pascal60  -DTrilinos_INSTALL_INCLUDE_DIR=/ascldap/users/knteran/Trilinos_LIB/include  -D Trilinos_INSTALL_EXAMPLE_DIR=/ascldap/users/knteran/Trilinos_LIB/Examples -D Trilinos_INSTALL_RUNTIME_DIR=/ascldap/users/knteran/Trilinos_LIB/Examples/bin  -DTrilinos_INSTALL_LIB_DIR=/ascldap/users/knteran/Trilinos_LIB/lib  -DCMAKE_INSTALL_PREFIX=/ascldap/users/knteran/Trilinos_LIB  ../Trilinos`

**Comment by mhoemmen** [comment]
@keitat Did you mean `Kokkos_Core.hpp`?

**Comment by mhoemmen** [comment]
There are two sources of information for you:

  1. Any of various Trilinos tutorials I and others have given, that show how `FIND_PACKAGE(Trilinos ...)` works.  You can find slides on trilinos.org (don't mind the certificate warning).  I'll also e-mail you some slides if I can find them locally.

  2. `tpetra/doc/FAQ.txt` (SERIOUSLY READ THIS I spent a lot of time on it)

**Comment by jhux2** [comment]
@trilinos/tpetra

**Comment by keitat** [comment]
I will close the issue.  I am still concerned with the failure of "make install" (failed to copy Kokkos_Core.h).  I will report this with another issue ticket.

**Comment by kddevin** [comment]
Hi, @keitat 

I'm trying to understand the issue you are seeing.  As shown below, I did a build of Trilinos using (roughly) your CMake command, and Kokkos_Core.hpp was installed as expected in $CMAKE_INSTALL_PREFIX/include.  Do you follow the same steps? 

% cmake \
-D Trilinos_ENABLE_KOKKOS=ON   \
-D Trilinos_ENABLE_TESTS=ON \
-D Trilinos_ENABLE_Tpetra=ON  \
-D TRILINOS_ENABLE_BELOS:BOOL=ON \
-D Trilinos_ENABLE_Ifpack2:BOOL=ON \
-D CMAKE_INSTALL_PREFIX=/tmp/Trilinos_LIB \
\
-D Trilinos_ENABLE_Fortran:BOOL=OFF \
../ 
% make -j 6 
% make install
% ls /tmp/Trilinos_LIB/include/Kokkos_Core*
/tmp/Trilinos_LIB/include/Kokkos_Core.hpp       /tmp/Trilinos_LIB/include/Kokkos_Core_fwd.hpp

As I was experimenting, I did see that changing the CMAKE_INSTALL_PREFIX of an existing build would not correctly change the installation directory.  In that case, throwing away the existing build and rebuilding from scratch fixed the installation directory.

BTW:  CMake is case-sensitive, so the following lines aren't doing anything in CMake; in your build, Kokkos and Belos are enabled only because other packages depend on them.
-D Trilinos_ENABLE_KOKKOS=ON   
-D TRILINOS_ENABLE_BELOS:BOOL=ON 
Kokkos is required by Tpetra, so it will be enabled whenever you build Tpetra.  To specify that you want Belos, use
-D Trilinos_ENABLE_Belos:BOOL=ON

**Comment by keitat** [comment]
I applied the following option and found that Kokkos_Core.hpp was not copied properly.   I think the availability of other "INSTALL" options is really confusing.  Let me try -DCMAKE_INSTALL_PREFIX only to see if it works.

` -D Trilinos_INSTALL_EXAMPLE_DIR=/home/knteran/Trilinos_LIB/Examples -D Trilinos_INSTALL_RUNTIME_DIR=/home/knteran/Trilinos_LIB/Examples/bin  -DTrilinos_INSTALL_LIB_DIR=/home/knteran/Trilinos_LIB/lib  -DCMAKE_INSTALL_PREFIX=/home/knteran/Trilinos_LIB`

**Comment by kddevin** [comment]
@keitat When I build with the following command, I still get Kokkos_Core.hpp installed correctly.  
The first thing I try with unexplainable problems like this one is deleting my build directory and trying again with a fresh build, just in case something got corrupted.  Have you tried that?

cmake \
-D Trilinos_ENABLE_KOKKOS=ON   \
-D Trilinos_ENABLE_TESTS=ON \
-D Trilinos_ENABLE_Tpetra=ON  \
-D TRILINOS_ENABLE_BELOS:BOOL=ON \
-D Trilinos_ENABLE_Ifpack2:BOOL=ON \
-D CMAKE_INSTALL_PREFIX=/tmp/Trilinos_LIB \
-D Trilinos_INSTALL_INCLUDE_DIR=/tmp/Trilinos_LIB/include  \
-D Trilinos_INSTALL_EXAMPLE_DIR=/tmp/Trilinos_LIB/Examples \
-D Trilinos_INSTALL_RUNTIME_DIR=/tmp/Trilinos_LIB/Examples/bin  \
-D Trilinos_INSTALL_LIB_DIR=/tmp/Trilinos_LIB/lib  \
-D Trilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON \
-D Trilinos_ENABLE_Fortran:BOOL=OFF \
../

**Comment by keitat** [comment]
On Ride, I tried following:

I did follow the guide there:
https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#quick-start

(On my build directory)
```
source ../Trilinos/cmake/std/atdm/load-env.sh cuda-opt

cmake \
-GNinja \
-DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
-D Trilinos_ENABLE_KOKKOS=ON\
-D Trilinos_ENABLE_TESTS=ON \
-D Trilinos_ENABLE_Tpetra=ON \
-D TRILINOS_ENABLE_BELOS:BOOL=ON \
-D Trilinos_ENABLE_Ifpack2:BOOL=ON \
-D CMAKE_INSTALL_PREFIX=/tmp/Trilinos_LIB \
-D Trilinos_INSTALL_INCLUDE_DIR=/tmp/Trilinos_LIB/include \
-D Trilinos_INSTALL_EXAMPLE_DIR=/tmp/Trilinos_LIB/Examples \
-D Trilinos_INSTALL_RUNTIME_DIR=/tmp/Trilinos_LIB/Examples/bin \
-D Trilinos_INSTALL_LIB_DIR=/tmp/Trilinos_LIB/lib \
-D Trilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON \
-D Trilinos_ENABLE_Fortran:BOOL=OFF \
../Trilinos

make NP=16
make install
```

Then, I typed `ls /tmp/Trilinos_LIB/include/Kokkos_C*` to get:

`/tmp/Trilinos_LIB/include/Kokkos_ConfigDefs.hpp`

Something must be wrong.....

**Comment by mhoemmen** [comment]
@keitat Don't use all-caps for `TRILINOS_ENABLE_BELOS` -- it should be `Trilinos_ENABLE_Belos`.  Otherwise, not sure what's going on.  Why not just do `CMAKE_INSTALL_PREFIX` and leave off the `TRILINOS_INSTALL_*` options?  That usually works for me.

**Comment by keitat** [comment]
@mhoemmen  It is working.  I did see  `Kokkos_Core.hpp` in the install directory.

   I think the culprits are `TRILINOS_INSTALL_*` options.  It will be great if this is documented somewhere.

**Comment by zhangkmsjtu** [comment]
> 

/opt/Trilinos-13-4-0/packages/seacas/libraries/ioss/src/Ioss_CodeTypes.h:61:10: fatal error: Kokkos_Core.hpp: 没有那个文件或目录
   61 | #include <Kokkos_Core.hpp> // for Kokkos::complex
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [packages/seacas/libraries/ioss/src/CMakeFiles/Ioss.dir/build.make:76：packages/seacas/libraries/ioss/src/CMakeFiles/Ioss.dir/Ioss_Assembly.C.o] 错误 1
make[1]: *** [CMakeFiles/Makefile2:3544：packages/seacas/libraries/ioss/src/CMakeFiles/Ioss.dir/all] 错误 2
make: *** [Makefile:166：all] 错误 2
