### ISSUE TITLE
Bug in Stratimikos ignoring "Convergence Tolerance" parameter for Belos/AztecOO 

### ISSUE THREAD

**Issue by ikalash** [trilinos/Trilinos#2441]
In running Albany, I have come across what I believe is a bug in the Stratimikos processing of the parameter list for the solver (Belos or AztecOO).  It appears the parameter "Convergence Tolerance" under the solver sublist (e.g., Belos -> Block GMRES, or Belos -> Block CG or AztecOO -> GMRES) gets ignored, and instead a default value gets used.  To take my input file as a concrete example, even though I set "Convergence Tolerance to 1.0e-12 (in bold below), the value that is used for the BlockGmres solver is 1e-4.    

 Stratimikos Linear Solver:
            Stratimikos:
              Linear Solver Type: Belos
              Linear Solver Types:
                Belos:
                  VerboseObject:
                    Verbosity Level: high
                  Solver Type: Block GMRES
                  Solver Types:
                    Block GMRES:
                      **Convergence Tolerance: 1.0e-12**
                      Output Frequency: 1
                      Output Style: 1
                      Verbosity: 33
                      Maximum Iterations: 200
                      Block Size: 1
                      Num Blocks: 200
                      Flexible Gmres: false

I dug a little bit into it and stratimikos/adapters/belos/src/Thyra_BelosLinearOpWithSolve_def.hpp is getting the right value for defaultTol_, but then it must be getting overwritten somewhere b/w this file and the BelosGmresSolver.  It's not clear to me where the 1.0e-4 value is coming from, but I did not dig that deep.  I observed this problem with Belos and AztecOO being called through Stratimikos (though they have different default values).

Mentioning @amota and @jwfoulk , who are interested in this from the Albany side.  Paul Lin has confirmed that this happens in Drekar as well so the issue is not specific to Albany.  I believe a few years ago, the Convergence Tolerance was being read in correctly from the input file.  

@trilinos/stratimikos @trilinos/belos @trilinos/aztecoo

**Comment by rppawlo** [comment]
If you are using nox, it will override the convergence tolerance since it may adjust the tolerance as the solve progresses depending on algorithm used.

**Comment by ikalash** [comment]
@rppawlo : yes, this is what Paul called to my attention - that we can specify the convergence tolerance through the Newton sublist under NOX, e.g., 

 Newton:
          Forcing Term Method: Constant
          Rescue Bad Newton Solve: true
          **Linear Solver:
            Tolerance: 1.0e-14**

This is definitely a workaround for Albany/Drekar that I am using now.  But is this the intended behavior for NOX + Stratimikos though?  I can see this causing a lot of confusion (as it did for me).  It seems to me it would make sense for the solver to use the convergence tolerance specified in the Belos / AztecOO sublist, and only go to the NOX default if that option is not found.  I worry that users will think they are using a certain tolerance based on their Belos/AztecOO PL options when really it gets ignored and over-written with the NOX one.

**Comment by ikalash** [comment]
@rppawlo : thanks for the note.  I think this is not critical for us, but a solution such as the one you propose might be a good option long term to prevent confusion.  Lets keep the discussion going in this issue.  It sounds like the thyra refactor might be a good time to revisit this.
