### ISSUE TITLE
checkin-test-sems.sh complex config broken

### ISSUE THREAD

**Issue by MicheldeMessieres** [trilinos/Trilinos#2468]
For the MPI_RELEASE_DEBUG_SHARED_PT_COMPLEX.config in checkin-test-sems.sh, I believe we want to add cmake/std/sems/SEMSDevEnv.cmake. I think this config was accidentally skipped when the others were updated?

@trilinos/<teamName>

## Expectations

Complex should work like the regular sems.

## Current Behavior

I'll get config errors for Boost as the DIR is not set (for complex only, not the regular sems)

## Definition of Done

Complex SEMS will configure.
## Possible Solution

Modify -DTrilinos_CONFIGURE_OPTIONS_FILE for MPI_RELEASE_DEBUG_SHARED_PT_COMPLEX.config to include cmake/std/sems/SEMSDevEnv.cmake.

## Steps to Reproduce

./checkin-test-sems.sh \
  --default-builds= --extra-builds=MPI_RELEASE_DEBUG_SHARED_PT_COMPLEX  \
  --no-enable-fwd-packages --enable-packages=Teuchos --local-do-all --no-enable-fwd-packages

will generate config output:
CMake Error at cmake/tribits/core/package_arch/TribitsProcessEnabledTpl.cmake:144 (MESSAGE):
  ERROR: TPL_Boost_NOT_FOUND=TRUE, aborting!

## Your Environment

- **Relevant repo SHA1s:**  
- **Relevant configure flags or configure script:**  
- **Operating system and version:**  
- **Compiler and TPL versions:**  

## Related Issues

* Blocks 
* Is blocked by 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of

**Comment by MicheldeMessieres** [comment]
@bartlettroscoe If this should be fixed, please let me know if you'd like me to setup a PR for that.

**Comment by bartlettroscoe** [comment]
@MicheldeMessieres, I don't think there is any automated testing that is posting to CDash that protects the build `MPI_RELEASE_DEBUG_SHARED_PT_COMPLEX` like protects the `--default-builds=MPI_RELEASE_DEBUG_SHARED_PT` build.  

If you don't mind, can you create a PR that fixes this and verify that it fixes it for you?

**Comment by MicheldeMessieres** [comment]
@bartlettroscoe Thanks. I've already confirmed that resolves the issue and will setup a PR.

**Comment by MicheldeMessieres** [comment]
@bartlettroscoe PR is up #2469.  Confirmed that works.
