### ISSUE TITLE
The dependency target "MeshingGenie_libs" of target "Trilinos_libs" does not exist.

### ISSUE THREAD

**Issue by nschloe** [trilinos/Trilinos#247]
When configuring with
```
  -DTrilinos_ENABLE_MeshingGenie:BOOL=ON
```
I'm getting
```
-- Configuring done
CMake Error at cmake/tribits/core/package_arch/TribitsGlobalMacros.cmake:2255 (ADD_DEPENDENCIES):
  The dependency target "MeshingGenie_libs" of target "Trilinos_libs" does
  not exist.
```

**Comment by jwillenbring** [comment]
@kddevin What is the status of MeshingGenie? It is not in the official list of released packages. I am not sure if this should be used or if it is actively worked on.

**Comment by jwillenbring** [comment]
Thanks to @kddevin we determined that MeshingGenie is obsolete, and will be removed from Trilinos in the future. Since it is experimental code anyway, I am going to close the bug. The specific comment from the primary MeshingGenie developer was that at this point it isn't worth the maintenance.

**Comment by nschloe** [comment]
> will be removed from Trilinos in the future.

Shall we file a separate bug for this or are you keeping track some other way?

**Comment by jwillenbring** [comment]
I think filing a new ticket would be appropriate.
