### ISSUE TITLE
Tpetra: couple of issues with (Multi)Vector cloning

### ISSUE THREAD

**Issue by bartgol** [trilinos/Trilinos#2470]
@trilinos/Tpetra

## Motivation and Context

The current MultiVectorCloner ends its 'clone' method with a call to Tpetra::deep_copy. However, the first aragument appears to be an RCP<dst_mv_type>, while Tpetra::deep_copy expects two MV.

Moreover, the MultiVector and Vector classes declare a method 'clone', which they never implement. The comments above the MV clone declaration indeed specify to not rely on the method, since it may disappear. However, seeing a declaration that is not defined is misleading, I think

## Definition of Done

Fix for the clone method of MVCloner (dereferencing the ptr to the destination MV fixes it on my machine) and remove undefined methods.

## Possible Solution

 See above.
## Steps to Reproduce

Just try to call MultiVectorCloner<...>::clone.

## Your Environment

- **Relevant repo SHA1s:**  f72b5b9
- **Relevant configure flags or configure script:**  
- **Operating system and version:**  RHEL 7
- **Compiler and TPL versions:**  gcc 7.2.0

**Comment by mhoemmen** [comment]
If I remember right, the `clone` methods exist mainly because of early MueLu + Stokhos work that needed a way to get "GPU"-enabled Tpetra classes through a not-yet-GPU-ready MueLu.  I'm not a fan of them but they preexisted my work on Tpetra so I had to maintain them.  Such is life.

**Comment by mhoemmen** [comment]
@bartgol Do you actually use the `clone` method?  Does its current state block your work?

**Comment by bartgol** [comment]
I do, but I fixed the clone method of MVCloner to dereference Y before forwarding it to Tpetra::deep_copy. It's not a big deal, but I thought you guys should know.

As for the clone methods, I'm not advocating for them to be eliminated. And I'm not really sure what their role is. But if they must stay in the declaration, they should probably either have an implementation or a comment explaining the impl is omissed on purpose.

My 2 cents.

**Comment by mhoemmen** [comment]
@bartgol You mentioned fixing the clone method; would you happen to have a patch or pull request?  Thanks!

**Comment by bartgol** [comment]
Uhm, not yet, but I can set it up. Will do it tomorrow.

**Comment by mhoemmen** [comment]
@bartgol Your PR passed pull request testing; I just merged it.  Thanks! :-D 

(fixed in develop)
