### ISSUE TITLE
Test Piro_MatrixFreeDecorator_UnitTests_MPI_4 failing in several ATDM builds

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#2474]
**CC:** @trilinos/piro, @rppawlo (Trilinos Nonlinear Solvers Product Area Lead)

## Next Action Status

Commit  6682bfc pushed on 3/30/2018 disabled this test for the builds were it was failing at the time.  Merge of PR #3750 on 10/27/2018 resulted in this test Piro_MatrixFreeDecorator_UnitTests_MPI_4 newly passing in the 'waterman' release-debug builds starting 10/28/2018.  PR #3866 merged to 'develop' on 11/13/2018 that should re-enable this test on all platforms.   Next: Check [this test in all builds for 11/14/2018](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&date=2018-11-14&filtercombine=and&filtercombine=and&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-&field2=testname&compare2=61&value2=Piro_MatrixFreeDecorator_UnitTests_MPI_4) the day after on 11/15/2018 to ensure they all ran and passed ...

## Description

As shown in the query for all builds today:

* https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&date=2018-03-28&limit=0&filtercount=1&showfilters=1&field1=testname&compare1=61&value1=Piro_MatrixFreeDecorator_UnitTests_MPI_4

the test `Piro_MatrixFreeDecorator_UnitTests_MPI_4` fails in the new ATDM builds:

* `Trilinos-atdm-hansen-shiller-gnu-opt-openmp`
* `Trilinos-atdm-hansen-shiller-gnu-opt-serial`
* `Trilinos-atdm-white-ride-cuda-opt`
* `Trilinos-atdm-white-ride-gnu-opt-openmp`

It does not fail in any other builds.

The test output shows failures like:

```
[...]

4. Piro_MatrixFreeDecorator_DefaultJacobian_UnitTest ... 
 nonnull(jacobian) = 1 == true : passed
 jacobian->domain()->isCompatible(*expectedJacobian->domain()) = 1 == true : passed
 jacobian->range()->isCompatible(*expectedJacobian->range()) = 1 == true : passed
 Comparing actual == expected ... 
 Error, relErr(actual[3],expected[3]) = relErr(-1.16415e-10,0) = 0.999998 <= tol = 1e-05: failed!
 Comparing actual == expected ... 
 Error, relErr(actual[3],expected[3]) = relErr(-1.16415e-10,0) = 0.999998 <= tol = 1e-05: failed!
 Comparing actual == expected ... 
 Error, relErr(actual[3],expected[3]) = relErr(-1.16415e-10,0) = 0.999998 <= tol = 1e-05: failed!
 Comparing actual == expected ... passed
 [FAILED]  (0.00349 sec) Piro_MatrixFreeDecorator_DefaultJacobian_UnitTest
 Location: /home/jenkins/hansen/workspace/Trilinos-atdm-hansen-shiller-gnu-opt-openmp/SRC_AND_BUILD/Trilinos/packages/piro/test/Piro_MatrixFreeDecorator_UnitTests.cpp:330

[...]

The following tests FAILED:
    4. Piro_MatrixFreeDecorator_DefaultJacobian_UnitTest ... 
    5. Piro_MatrixFreeDecorator_DefaultJacobian_ModelSupportsW_UnitTest ... 
    6. Piro_MatrixFreeDecorator_DynamicJacobian_UnitTest ... 

Total Time: 0.0958 sec

Summary: total = 8, run = 8, passed = 5, failed = 3

End Result: TEST FAILED
```

These don't segfault or crash in any of these builds.  These look to just be numerical erros.

## Steps to Reproduce

In order to reproduce, just enable the log onto the machines `hansen`, `shiller`, `white` or `ride` and run the builds shown above using the instructions provided at:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md

Just enable the package `-DTrilinos_ENABLE_Piro=ON` and run the tests as described.  See specific instructions for these machines at:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#specific-instructions-for-each-system

**Comment by mhoemmen** [comment]
This could also be a UVM or failure-to-sync-between-host-and-device issue.

**Comment by bartlettroscoe** [comment]
> This could also be a UVM or failure-to-sync-between-host-and-device issue.

@mhoemmen, but it also fails in non cuda builds as well.

**Comment by bartlettroscoe** [comment]
Looking at the the history of this test `Piro_MatrixFreeDecorator_UnitTests_MPI_4` the build `Trilinos-atdm-hansen-shiller-gnu-opt-serial` shown in the query:

* https://testing-vm.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-hansen-shiller-gnu-opt-serial&field2=testname&compare2=61&value2=Piro_MatrixFreeDecorator_UnitTests_MPI_4&field3=buildstarttime&compare3=84&value3=now

it looks like this test went from passing on 2018-02-22 to failing on 2018-02-28.  Not sure why there is a 6 day gap in the testing.  We would have to research that.

@trilinos/piro developers, do you have a problem with disabling this test for just the ATDM builds were it is failing?  Then someone can enable this test on one of these systems and try to debug why it is failing.  Then we can promote these builds to the "ATDM" CDash Track/Group so that they can be maintained as clean. 

Unless there is an objection, I will disable this test in these builds these tomorrow as some point and update this issue.

**Comment by bartlettroscoe** [comment]
No response for @trilinos/piro developers.  Therefore, I will go ahead and disable this test in these builds.

**Comment by bartlettroscoe** [comment]
I pushed commit 6682bfc that should disable this test on the platforms were it is failing.

@rppawlo, does Piro fall into your Product area?  Who should I assign this issue to to debug this failing test?  It looks like the only person in the team @trilinos/piro is @agsalin (who is our manager now so likely will not have time to fix this :-) ).

**Comment by rppawlo** [comment]
PIRO is in active use by Albany, so maybe @ikalash or @mperego could take a look?

**Comment by ikalash** [comment]
We use the matrix free decorator in Albany (for mass lumping for explicit time integration) so I would like to understand what is going on here.  I am OOO Mon.-Tues. this week and part of the day Wed.  I could look at this but it probably would not be until Friday or next week.  @mperego, if you have time to look at it before then, please go ahead.

**Comment by bartlettroscoe** [comment]
Should we add @ikalash and @mperego to the @trilinos/piro group?

**Comment by bartlettroscoe** [comment]
These Piro tests were now shown at failing in automated testing yesterday at shown at:

* https://testing-vm.sandia.gov/cdash/queryTests.php?project=Trilinos&date=2018-04-02&filtercombine=and&filtercount=4&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-&field2=status&compare2=62&value2=Passed&field3=buildname&compare3=62&value3=Trilinos-atdm-white-ride-cuda-opt&field4=buildname&compare4=62&value4=Trilinos-atdm-white-ride-gnu-opt-openmp

And it was shown missing in the build ??? on 3/31/2018 as shown at:

* https://testing-vm.sandia.gov/cdash/viewTest.php?buildid=3405983

This is pretty good evidence that this issue has been resolved.

I am going to keep this open and mark it with the new label "Disabled Tests".

**Comment by bartlettroscoe** [comment]
I have marked this with "Disabled Tests" label so that we can filter this out of our queries.

**Comment by ikalash** [comment]
@bartlettroscoe : reel free to add me to the @trilinos/piro group.

**Comment by bartlettroscoe** [comment]
@ikalash said:

> @bartlettroscoe : reel free to add me to the @trilinos/piro group.

@trilinos/framework, can someone please add @ikalash to the @trilinos/piro team?  I don't have the permissions to do so.

**Comment by fryeguy52** [comment]
This test is failing on the serrano and mutrino builds as well.  @bartlettroscoe should we also disable the test on these platforms?

`serrano`
https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&date=2018-06-13&filtercount=4&showfilters=1&filtercombine=and&field1=testname&compare1=63&value1=Piro_MatrixFreeDecorator_UnitTests_MPI_4&field2=buildname&compare2=63&value2=Trilinos-atdm-&field3=site&compare3=63&value3=serrano&field4=buildstarttime&compare4=83&value4=6-6-2018

`mutrino`
https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&date=2018-06-13&filtercount=4&showfilters=1&filtercombine=and&field1=testname&compare1=63&value1=Piro_MatrixFreeDecorator_UnitTests_MPI_4&field2=buildname&compare2=63&value2=Trilinos-atdm-&field3=site&compare3=63&value3=mutrino&field4=buildstarttime&compare4=83&value4=6-6-2018

**Comment by bartlettroscoe** [comment]
From looking at these test failures on 'serrano' such as at:

* https://testing.sandia.gov/cdash/testDetails.php?test=49401718&build=3631824

we are seeing the same type of output:

```
4. Piro_MatrixFreeDecorator_DefaultJacobian_UnitTest ... 
 nonnull(jacobian) = 1 == true : passed
 jacobian->domain()->isCompatible(*expectedJacobian->domain()) = 1 == true : passed
 jacobian->range()->isCompatible(*expectedJacobian->range()) = 1 == true : passed
 Comparing actual == expected ... 
 Error, relErr(actual[3],expected[3]) = relErr(-1.16415e-10,0) = 0.999998 <= tol = 1e-05: failed!
 Comparing actual == expected ... 
 Error, relErr(actual[3],expected[3]) = relErr(-1.16415e-10,0) = 0.999998 <= tol = 1e-05: failed!
 Comparing actual == expected ... 
 Error, relErr(actual[3],expected[3]) = relErr(-1.16415e-10,0) = 0.999998 <= tol = 1e-05: failed!
 Comparing actual == expected ... passed
 [FAILED]  (0.00358 sec) Piro_MatrixFreeDecorator_DefaultJacobian_UnitTest
 Location: /gpfs1/jenkins/serrano-slave/workspace/Trilinos-atdm-serrano-intel-debug-openmp/SRC_AND_BUILD/Trilinos/packages/piro/test/Piro_MatrixFreeDecorator_UnitTests.cpp:330

...

The following tests FAILED:
    4. Piro_MatrixFreeDecorator_DefaultJacobian_UnitTest ... 
    5. Piro_MatrixFreeDecorator_DefaultJacobian_ModelSupportsW_UnitTest ... 
    6. Piro_MatrixFreeDecorator_DynamicJacobian_UnitTest ... 

Total Time: 0.0971 sec

Summary: total = 8, run = 8, passed = 5, failed = 3

End Result: TEST FAILED
```

And the output for this test on 'mutrino' looks the same as shown at:

* https://testing.sandia.gov/cdash/testDetails.php?test=49405803&build=3631961

and

* https://testing.sandia.gov/cdash/testDetails.php?test=49402189&build=3631894

That is the same as reported above so yes, lets disable this test on those builds as well.

@fryeguy52, can you please follow the example in commit 6682bfc to disable this test in these 'serrano' and 'mutrino' builds and then create a Trilinos PR for this?

**Comment by bartlettroscoe** [comment]
Looks like we are now also seeing these failures with the Intel builds on 'hansen' as well as shown in [this query](https://testing-vm.sandia.gov/cdash/queryTests.php?project=Trilinos&date=2018-08-03&filtercombine=and&filtercombine=and&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-&field2=status&compare2=62&value2=passed&field3=status&compare3=62&value3=notrun&field4=testname&compare4=65&value4=Piro_&field5=groupname&compare5=61&value5=ATDM).  For example, the test in the build `Trilinos-atdm-hansen-shiller-intel-debug-serial` at:

* https://testing-vm.sandia.gov/cdash/testDetails.php?test=51602564&build=3793152

showed:

```
[...]

4. Piro_MatrixFreeDecorator_DefaultJacobian_UnitTest ... 
 nonnull(jacobian) = 1 == true : passed
 jacobian->domain()->isCompatible(*expectedJacobian->domain()) = 1 == true : passed
 jacobian->range()->isCompatible(*expectedJacobian->range()) = 1 == true : passed
 Comparing actual == expected ... 
 Error, relErr(actual[3],expected[3]) = relErr(-1.16415e-10,0) = 0.999998 <= tol = 1e-05: failed!
 Comparing actual == expected ... 
 Error, relErr(actual[3],expected[3]) = relErr(-1.16415e-10,0) = 0.999998 <= tol = 1e-05: failed!
 Comparing actual == expected ... 
 Error, relErr(actual[3],expected[3]) = relErr(-1.16415e-10,0) = 0.999998 <= tol = 1e-05: failed!
 Comparing actual == expected ... passed
 [FAILED]  (0.00189 sec) Piro_MatrixFreeDecorator_DefaultJacobian_UnitTest
 Location: /home/jenkins/hansen/workspace/Trilinos-atdm-hansen-shiller-intel-debug-serial/SRC_AND_BUILD/Trilinos/packages/piro/test/Piro_MatrixFreeDecorator_UnitTests.cpp:330

[...]

The following tests FAILED:
    4. Piro_MatrixFreeDecorator_DefaultJacobian_UnitTest ... 
    5. Piro_MatrixFreeDecorator_DefaultJacobian_ModelSupportsW_UnitTest ... 
    6. Piro_MatrixFreeDecorator_DynamicJacobian_UnitTest ... 

Total Time: 0.0502 sec

Summary: total = 8, run = 8, passed = 5, failed = 3
```

The other three builds showed the same failures.

**Comment by bartlettroscoe** [comment]
I created PR #3252 to disable this test in the Intel builds on hansen/shiller.

@fryeguy52 or @rppawlo, could you please approve the PR #3252 so that I can merge it?

**Comment by fryeguy52** [comment]
This is also failing on the new waterman opt builds. However it does pass the debug builds  shown [here](https://testing-vm.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-waterman&field2=testname&compare2=61&value2=Piro_MatrixFreeDecorator_UnitTests_MPI_4)

should we disable the test for these builds as well?

**Comment by bartlettroscoe** [comment]
@mperego, looks like the merge of PR #3688 did not fix the `Piro_MatrixFreeDectorator_UnitTests_MPI_4` tests in the builds `Trilinos-atdm-waterman-cuda-9.2-release-debug`and `Trilinos-atdm-waterman-gnu-release-debug-openmp` shown [here](https://testing.sandia.gov/cdash-dev-view/queryTests.php?project=Trilinos&date=2018-10-22&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-waterman-&field2=status&compare2=62&value2=passed).  Now for the build `rilinos-atdm-waterman-gnu-release-debug-openmp`, for example, shown [here](https://testing.sandia.gov/cdash-dev-view/testDetails.php?test=57307358&build=4078976) we are seeing the failure:

```
Running unit tests ...

0. Piro_MatrixFreeDecorator_JacobianOperatorInitialization_UnitTest ... [Passed] (0.00325 sec)
1. Piro_MatrixFreeDecorator_JacobianOperatorAppliesWithCoefs_UnitTest ... [Passed] (0.00306 sec)
2. Piro_MatrixFreeDecorator_JacobianOperatorAppliesToMv_UnitTest ... [Passed] (0.00458 sec)
3. Piro_MatrixFreeDecorator_DefaultResidual_UnitTest ... [Passed] (0.00146 sec)
4. Piro_MatrixFreeDecorator_DefaultJacobian_UnitTest ... [Passed] (0.00385 sec)
5. Piro_MatrixFreeDecorator_DefaultJacobian_ModelSupportsW_UnitTest ... [Passed] (0.00324 sec)
6. Piro_MatrixFreeDecorator_DynamicJacobian_UnitTest ... 
 [FAILED]  (0.0715 sec) Piro_MatrixFreeDecorator_DynamicJacobian_UnitTest
 Location: /home/jenkins/waterman/workspace/Trilinos-atdm-waterman-gnu-release-debug-openmp/SRC_AND_BUILD/Trilinos/packages/piro/test/Piro_MatrixFreeDecorator_UnitTests.cpp:383
 
7. Piro_MatrixFreeDecorator_ResidualAliasing_UnitTest ... [Passed] (0.00155 sec)

The following tests FAILED:
    6. Piro_MatrixFreeDecorator_DynamicJacobian_UnitTest ... 

Total Time: 0.0928 sec

Summary: total = 8, run = 8, passed = 7, failed = 1

End Result: TEST FAILED
```

It looks the same for the build `Trilinos-atdm-waterman-cuda-9.2-release-debug` shown [here](https://testing.sandia.gov/cdash-dev-view/testDetails.php?test=57312435&build=4078332).

NOTE: If you change this test over to use the parallel Teuchos unit test driver (see `Teuchos_StandardParallelUnitTestMain.cpp ` [here](https://trilinos.org/docs/dev/packages/teuchos/doc/html/group__Teuchos__UnitTest__grp.html)), then it will report which MPI process is failing.




I have removed the `Disabled Tests` label for now since we are using this issue to address these new failures on 'waterman'.

**Comment by mperego** [comment]
Thanks @bartlettroscoe, I'll look into this. My guess is that the tolerance is still too tight, even if the change made should have fixed the issue of computing a relative error with respect to an expected solution that is zero.

**Comment by mperego** [comment]
@bartlettroscoe Sorry it me a while also because I had to get an account on Waterman

**Comment by bartlettroscoe** [comment]
Merge of PR #3750 on 10/27/2018 resulted in this test `Piro_MatrixFreeDecorator_UnitTests_MPI_4` newly passing in the 'waterman' `release-debug` builds starting 10/28/2018 as shown [here](https://testing.sandia.gov/cdash-dev-view/queryTests.php?project=Trilinos&date=2018-10-26&filtercount=4&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-waterman-&field2=buildname&compare2=63&value2=release-debug&field3=testname&compare3=61&value3=Piro_MatrixFreeDecorator_UnitTests_MPI_4&field4=buildstarttime&compare4=83&value4=2018-10-20).  

However, there are still several builds where this test is currently disabled as shown by:

```
$ cd Trilinos/

$ find cmake/std/atdm/ -type f -exec grep -nH Piro_MatrixFreeDecorator_UnitTests_MPI_4 {} \;
cmake/std/atdm/waterman/tweaks/CUDA-9.2-RELEASE-CUDA-POWER9-VOLTA70.cmake:2:ATDM_SET_ENABLE(Piro_MatrixFreeDecorator_UnitTests_MPI_4_DISABLE ON)
cmake/std/atdm/waterman/tweaks/GNU-RELEASE-OPENMP-POWER9.cmake:2:ATDM_SET_ENABLE(Piro_MatrixFreeDecorator_UnitTests_MPI_4_DISABLE ON)
cmake/std/atdm/serrano/tweaks/INTEL-DEBUG-OPENMP-BDW.cmake:5:ATDM_SET_ENABLE(Piro_MatrixFreeDecorator_UnitTests_MPI_4_DISABLE ON)
cmake/std/atdm/serrano/tweaks/INTEL-RELEASE-OPENMP-BDW.cmake:5:ATDM_SET_ENABLE(Piro_MatrixFreeDecorator_UnitTests_MPI_4_DISABLE ON)
cmake/std/atdm/shiller/tweaks/INTEL-DEBUG-SERIAL-HSW.cmake:11:ATDM_SET_ENABLE(Piro_MatrixFreeDecorator_UnitTests_MPI_4_DISABLE ON)
cmake/std/atdm/shiller/tweaks/INTEL-RELEASE-OPENMP-HSW.cmake:2:ATDM_SET_ENABLE(Piro_MatrixFreeDecorator_UnitTests_MPI_4_DISABLE ON)
cmake/std/atdm/shiller/tweaks/INTEL-RELEASE-SERIAL-HSW.cmake:2:ATDM_SET_ENABLE(Piro_MatrixFreeDecorator_UnitTests_MPI_4_DISABLE ON)
cmake/std/atdm/shiller/tweaks/GNU-RELEASE-OPENMP-HSW.cmake:2:ATDM_SET_ENABLE(Piro_MatrixFreeDecorator_UnitTests_MPI_4_DISABLE ON)
cmake/std/atdm/shiller/tweaks/GNU-RELEASE-SERIAL-HSW.cmake:8:ATDM_SET_ENABLE(Piro_MatrixFreeDecorator_UnitTests_MPI_4_DISABLE ON)
cmake/std/atdm/shiller/tweaks/INTEL-DEBUG-OPENMP-HSW.cmake:7:ATDM_SET_ENABLE(Piro_MatrixFreeDecorator_UnitTests_MPI_4_DISABLE ON)
cmake/std/atdm/mutrino/tweaks/ALL_BUILDS.cmake:2:ATDM_SET_ENABLE(Piro_MatrixFreeDecorator_UnitTests_MPI_4_DISABLE ON)
cmake/std/atdm/ride/tweaks/CUDA-9.2-RELEASE-CUDA-POWER8-KEPLER37.cmake:5:ATDM_SET_ENABLE(Piro_MatrixFreeDecorator_UnitTests_MPI_4_DISABLE ON)
cmake/std/atdm/ride/tweaks/GNU-RELEASE-OPENMP-POWER8.cmake:2:ATDM_SET_ENABLE(Piro_MatrixFreeDecorator_UnitTests_MPI_4_DISABLE ON)
```

@mperego, should we go ahead and remove all of these disables and see if this test is fixed in all of these builds as well?

**Comment by mperego** [comment]
@bartlettroscoe  Yes, I think we should give it a try. Thanks.

**Comment by bartlettroscoe** [comment]
> @bartlettroscoe Yes, I think we should give it a try. Thanks.

@mperego, okay, I will remove all of the disables for the test `Piro_MatrixFreeDecorator_UnitTests_MPI_4` and we will see what happens.

**Comment by bartlettroscoe** [comment]
> > should we go ahead and remove all of these disables and see if this test is fixed in all of these builds as well?
>
> Yes, I think we should give it a try. Thanks.

@mperego, can you please review and approve PR #3866 that removes all of these disables for this test for the ATDM Trilinos build?

**Comment by mperego** [comment]
@bartlettroscoe  I see PR #3866 has been already approved and merged. It looks good to me, Thanks for doing that.

**Comment by bartlettroscoe** [comment]
PR #3866 merged to 'develop' on 11/13/2018 that should re-enable this test on all platforms.   Next: Check [this test in all builds for 11/14/2018](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&date=2018-11-14&filtercombine=and&filtercombine=and&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-&field2=testname&compare2=61&value2=Piro_MatrixFreeDecorator_UnitTests_MPI_4) the day after on 11/15/2018 to ensure they all ran and passed ...

Putting "in review".

**Comment by bartlettroscoe** [comment]
Looking at the testing results for this test from 11/15/2018 [here](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&date=2018-11-15&filtercombine=and&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-&field2=testname&compare2=61&value2=Piro_MatrixFreeDecorator_UnitTests_MPI_4) it shows that this test ran and passed in 38 different ATDM Trilinos builds.  The set of ATDM Trilinos builds on 11/15/2018 [here](https://testing.sandia.gov/cdash-dev-view/index.php?project=Trilinos&date=2018-11-15&filtercount=1&showfilters=1&field1=buildname&compare1=65&value1=Trilinos-atdm-) totaled to 31 + 11 = 42.  But three of those builds in the "Specialized" Group did not submit test results (which are known issues) and the build `Trilinos-atdm-mutrino-intel-opt-openmp-KNL-panzer` does not enable Piro tests.  So that gives 42 - 4 = 38 ATDM Trilinos builds that should have submitted test results for Piro.  So that means that all of the builds that enabled Piro tests ran this test and this test passed.

Looks like this is finally complete.  Closing as complete!
