### ISSUE TITLE
Tempus: SolutionHistory::initWorkingState bug?

### ISSUE THREAD

**Issue by bartgol** [trilinos/Trilinos#2481]
@trilinos/Tempus

## Current Behavior

If `storageLimit_=1`, I think this routine has a bug. At line 249 of Tempus_SolutionHistory_impl.hpp, we try to get the current state. But if storageLimit_=1, the line above just erased the only state in the history, and the getCurrentState will read out of bounds. Valgrind reports me that I indeed have a read out of bounds, and gdb also tells me I crash there.

## Motivation and Context

I am not interested in keeping the history, so I set the `Storage Type` to `Keep Newest`, which automatically sets `storageLimit_` to 1. This creates the bug though. Changing the storage type to `Static` and asking for storage limit >=2 fixes the problem, but I still think the class should handle the case storageLimit_=1 differently.

## Definition of Done

Allow storage limit 1 without crashing, I guess.

## Possible Solution

I'm not really familiar with Tempus internal solution handling, in particular I'm not sure what that routine is supposed to do. However, I guess the if statement at line 245 could be changed into 
`if (getNumStates() < storageLimit_ || getNumStates()==1)`
Again, not 100% sure if this is the right logic, so some Tempus people should check it. 

## Steps to Reproduce

Just try too run a test with BackwardEuler, setting Storage Type to `Keep Newest`.

## Your Environment

- **Relevant repo SHA1s:**  6bbc3d6
- **Relevant configure flags or configure script:**  
- **Operating system and version:**  RHEL7
- **Compiler and TPL versions:**  gcc 7.2.0

**Comment by ccober6** [comment]
So storageLimit_=1 is a special case that we have not used or tested a lot, however it should not crash and should be fixed.  The primary driver for it is to save memory, i.e., roughly half as much as storageLimit_=2.   However, the memory savings can only be realized for some Steppers.
 * Explicit Steppers, e.g., Forward Euler and 1-stage explicit RK
 * **_Linear_** implicit Steppers, e.g., Backward Euler and 1-stage implicit RK
   * For **_non-linear_** problems, we need to form \dot{x} for each non-linear iteration and therefore need both x_{n} and x_{n-1}.
We have not optimized these Steppers, yet, to take advantage of the memory savings in these situations.

A few other notes:
 * If storageLimit_=1, most Steppers would need to allocate temporary memory anyways to handle the general situations.
 * If storageLimit_=1, on a step failure you can not restart from the SolutionHistory.  You would need to restart from file or initial conditions.
 * Steppers need to be tested to see if they work with storageLimit_=1, and those that do not pass have a pre-condition added.  This may be many/most of them.

**Comment by ccober6** [comment]
@bartgol which Stepper are you using, and is memory an issue?

**Comment by bartgol** [comment]
@ccober6 sorry for the late reply.

I am using Backward Euler. I was not aware of the distinction between linear and nonlinear, I thought the solution history was going to be updated only when the step was completed successfully (i.e., for nonlinear problems, only upon NOX convergence).

Anyhow, memory storage is not an issue for me. I came across this bug randomly: I was getting huge memory footprint (due to my mistake setting another parameter), and while digging I tried to set the storage type to something different than the default, and that's when the segfaults started to happen.

I have already switched to storage type 'Static', with limit 2, which is good enough to avoid the bug.
I just wanted to report this to your team, since I think it may need to be fixed (or else prevent users from having a 1-sized history storage). I would love to contribute, but I haven's spent enough time understanding the logic behind the state history to be able to craft a solution. My naive quick-and-dirty solution would be to always have storage limit >=2... But that would make Storage Type 'Keep Newest' useless, and I'm sure you guys had a reason for having that type...

**Comment by ccober6** [comment]
Did a few things with #2722 to address this issue:
 * Fixed bug that allowed SolutionHistory is delete the last State, and then immediately tried to assess the last State?!
 * Added asserts to Steppers to ensure that they had enough States to actually complete the timestep.
 * Changed the default storage type to Undo, as this ensures at least two States are available.

**Comment by ccober6** [comment]
Closing but please feel free to reopen, if this does not cover the major issues.
