### ISSUE TITLE
Trilinos compilation issue on some platforms due to Zoltan2

### ISSUE THREAD

**Issue by ikalash** [trilinos/Trilinos#2484]
Trilinos did not compile in a number of Albany builds last night due to what appears to be an issue in zoltan2:

```
repos/Trilinos/packages/zoltan2/src/algorithms/order/Zoltan2_AlgND.hpp:549:3: error: no matching function for call to 'Zoltan2::GraphModel >, Tpetra::RowGraph > > >::getEdgeList(Teuchos::ArrayView&, Teuchos::ArrayView&, Teuchos::ArrayView >&)'
```

(https://my.cdash.org/viewBuildError.php?buildid=1392503 ).  Curiously, it did not happen in all Albany Trilinos builds on all platforms, perhaps due to different configuration options?  

@trilinos/zoltan2

**Comment by kddevin** [comment]
@mmwolf Do you have time to look at this issue?  Thanks.

**Comment by mmwolf** [comment]
I'll look at this.  I don't understand this error but this specific Zoltan2 line had unexpected behavior when I was writing this code.

**Comment by kddevin** [comment]
I am happy to look at it together if you like.  Maybe eIDs should have type ArrayView<const gno_t>?

**Comment by ikalash** [comment]
@mmwolf: I just checked last night's nightlies for Albany, and everything is back to normal.  Thanks for fixing the issue!
