### ISSUE TITLE
PyTrilinos: Syntax error during compile

### ISSUE THREAD

**Issue by emprice** [trilinos/Trilinos#2490]
## Current Behavior

I configured Trilinos as follows: 

```
PATH=/home/eprice/software/swig/bin:/home/eprice/software/gcc/bin:/home/eprice/software/binutils/bin:$PATH CC=/home/eprice/software/gcc/bin/gcc CXX=/home/eprice/software/gcc/bin/g++ HDF5_ROOT=/home/eprice/software/hdf5 /home/eprice/software/cmake/bin/cmake -DTPL_ENABLE_MPI=ON -DMPI_BASE_DIR=/home/eprice/software/mpich -DTrilinos_ENABLE_ALL_PACKAGES=ON -DTPL_ENABLE_Matio=OFF -DCMAKE_INSTALL_PREFIX=/home/eprice/software/trilinos -DBUILD_SHARED_LIBS=ON -DPYTHON_EXECUTABLE=/home/eprice/virtpy2/bin/python -DBLAS_LIBRARY_DIRS=/home/eprice/software/lapack/lib -DLAPACK_LIBRARY_DIRS=/home/eprice/software/lapack/lib -DBoost_INCLUDE_DIRS=/home/eprice/software/boost/include -DNetCDF_INCLUDE_DIRS=/home/eprice/software/netcdf/include -DNetCDF_LIBRARIES=/home/eprice/software/netcdf/lib/libnetcdf.so -DNetCDF_NEEDS_HDF5=ON -DNetCDF_PARALLEL=OFF -DBoostLib_LIBRARY_DIRS=/home/eprice/software/boost/lib ..
```

I get the following unexpected error during `make`:

```
[ 97%] Swig source /home/eprice/src/Trilinos-trilinos-release-12-12-1/packages/PyTrilinos/src/Domi.i
/home/eprice/src/Trilinos-trilinos-release-12-12-1/build/packages/PyTrilinos/doc/Doxygen/Tpetra_dox.i:14798: Error: Syntax error in input(1).
make[2]: *** [packages/PyTrilinos/src/DomiPYTHON_wrap.cpp] Error 1
make[1]: *** [packages/PyTrilinos/src/CMakeFiles/PyTrilinos_Domi.dir/all] Error 2
make: *** [all] Error 2
```

## Motivation and Context

I am compiling Trilinos as part of a larger software package, FEniCS. I can't move forward until the issue is resolved.

## Your Environment

I downloaded Trilinos directly from the Releases page: Trilinos-trilinos-release-12-12-1
Operating system: CentOS 6.9 x86_64
Compiler versions: gcc 6.3.0, using MPICH 3.2.1

## Additional Information

I don't have root privileges on this machine (which is why my configure is so complicated -- I have local installs of a lot of my software). So any debugging/reconfiguring needs to be done in such a way that only my local installations are affected.

**Comment by wfspotz** [comment]
@emprice Is this a parallel build? I see references to Tpetra and Domi, but the combination of issues doesn't quite make sense.

Also, `/home/eprice/src/Trilinos-trilinos-release-12-12-1/build/packages/PyTrilinos/doc/Doxygen/Tpetra_dox.i` is a generated file. Can you attach it so I can look at it?

**Comment by wfspotz** [comment]
@emprice Also, as a temporary workaround, you can set `PyTrilinos_DOCSTRING` to `OFF` when you configure. This only impacts the interactive help facility for PyTrilinos. I would like to figure out the problem, though.
