### ISSUE TITLE
FEI_fei_ubase_MPI_X failing due to jumbled output breaking pass/fail grep

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#2506]
**CC:** @trilinos/fei, @trilinos/framework 

The test `FEI_fei_ubase_MPI_4` failed in the standard CI build just now s shown at:

* https://testing.sandia.gov/cdash/testDetails.php?test=46227718&build=3482611

which showed:

```
Exit Value: 0
Required regular expression not found.Regex=[End Result: TEST PASSED<br /> ]

...

Teuchos::GlobalMPISession::GlobalMPISession(): started processor with name ceerws1113 and rank 0!

***
*** Unit test suite ...
***


Sorting tests by group name then by the order they were added ... (time = 0.000279)

Running unit tests ...

[...]


Total Time: 0.00781 sec

Summary: total = 54, run = 54, passed = 54, failed = 0

End ReTeuchos::GlobalMPISession::GlobalMPISession(): started processor with name ceerws1113 and rank 1!
skipping test of fei::DirichletBCManager::finalizeBCEqn, which only runs on 1 proc.
test Eqns_unit.feiInitSlave only runs on 2 procs. returning.
Teuchos::GlobalMPISession::GlobalMPISession(): started processor with name ceerws1113 and rank 2!
skipping test of fei::DirichletBCManager::finalizeBCEqn, which only runs on 1 proc.
test Eqns_unit.feiInitSlave only runs on 2 procs. returning.
Teuchos::GlobalMPISession::GlobalMPISession(): started processor with name ceerws1113 and rank 3!
skipping test of fei::DirichletBCManager::finalizeBCEqn, which only runs on 1 proc.
test Eqns_unit.feiInitSlave only runs on 2 procs. returning.
sult: TEST PASSED
```

The problem is that the startup banner from the non-root processes got in the way of `End Result: TEST PASSED`.

**Comment by bartlettroscoe** [comment]
This can be fixed by passing in `--suppress-startup-banner`.  I will create a PR that adds this option.

**Comment by bartlettroscoe** [comment]
This happened again as shown at:

* https://testing.sandia.gov/cdash/testDetails.php?test=46492148&build=3496113

and it sent out another CDash error email.

We need to get this fixed.

**Comment by bartlettroscoe** [comment]
CC: @trilinos/framework,

This test strikes again, bringing down another PR build iteration shown in https://github.com/trilinos/Trilinos/pull/4834#issuecomment-489717856 with output in:

* https://testing.sandia.gov/cdash/testDetails.php?test=77296913&build=4999484

showing jumbled output:

```
End Teuchos::GlobalMPISession::GlobalMPISession(): started processor with name tr-test-0.novalocal and rank 1!
skipping test of fei::DirichletBCManager::finalizeBCEqn, which only runs on 1 proc.
test Eqns_unit.feiInitSlave only runs on 2 procs. returning.
test Eqns_unit.feiInitSlave only runs on 2 procs. returning.
test Eqns_unit.feiInitSlave only runs on 2 procs. returning.
Result: TEST PASSED
```

It is looking for "End Result: TEST PASSED".

**Comment by bartlettroscoe** [comment]
@trilinos/framework, @alanw0 

And a the PR iteration https://github.com/trilinos/Trilinos/pull/6045#issuecomment-538617025 got killed due to jumbled parallel output messing up pass check in test [`FEI_fei_ubase_MPI_2`](https://testing.sandia.gov/cdash/testDetails.php?test=90914638&build=5736020)

with output showing:

```
End Resultskipping test of fei::DirichletBCManager::finalizeBCEqn, which only runs on 1 proc.
: TEST PASSED
```

The pass criteria is:

```
Required regular expression not found.Regex=[End Result: TEST PASSED<br /> ]
Processors	2
```

The problem is this code:

* https://github.com/trilinos/Trilinos/blob/develop/packages/fei/unit_tests_base/fei_UBase_DirBC.cpp#L136

which shows:

```
    FEI_COUT << "skipping test of fei::DirichletBCManager::finalizeBCEqn, which only"
     << " runs on 1 proc." << FEI_ENDL;
```

That needs to be changed to:

```
    out << "skipping test of fei::DirichletBCManager::finalizeBCEqn, which only"
     << " runs on 1 proc." << FEI_ENDL;
```

**Comment by alanw0** [comment]
@bartlettroscoe thanks for the diagnosis. For some reason I wasn't aware that this issue had been lodged in GitHub a long time ago, sorry about that. I've just added a pull-request to try to fix this.

**Comment by bartlettroscoe** [comment]
Thanks @alanw0!  I also pushed commit 7f17447 to your PR #6050 that should address the original error reported in this issue.

The more of these randomly failing tests we can address, the better for everyone (and especially the PR testers).
