### ISSUE TITLE
No CI build from ceerws1113 on 4/5/2018

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#2513]
## Next Action Status

Watch for CI build starting up okay on 4/6/2018 ...

## Description:

The CI server on ceerws1113 never ran today and therefore never submitted to the CDash sites.  I went on to the machine ceerws1113 and saw:

```
[rabartl@ceerws1113 SEMSCIBuild]$ ls -l
total 4276
drwx------  6 rabartl rabartl    4096 Apr  4 17:08 BUILD
lrwxrwxrwx  1 rabartl rabartl      52 May 11  2017 kill-pstree.py -> ../Trilinos/TriBITS/common_tools/test/kill-pstree.py
drwx------ 11 rabartl rabartl    4096 Mar 27 10:31 Trilinos
-rw-------  1 rabartl rabartl 1687399 Apr  4 04:00 trilinos_ci_server.last.out
-rw-------  1 rabartl rabartl 2681250 Apr  4 18:01 trilinos_ci_server.out
```

That shows that the cron job never even fired off or the time stamps for the files `trilinos_ci_server.out` would be for today.

## Related Issues:

* Related issues: #1304

**Comment by bartlettroscoe** [comment]
My guess is that this was an outage of the CEE LAN.  Therefore, I expect this CI server to run just fine tomorrow.  But I will go ahead and start it so we see if there are any failures.  (Murphy's law for software testing says that there will be failures.)

**Comment by bartlettroscoe** [comment]
The restarted build is running and submitting as shown at:

* https://testing.sandia.gov/cdash/index.php?project=Trilinos&parentid=3484290

(NOTE: the new testing-vm CDash site is down due to a downgrade of PHP.)

**Comment by bartlettroscoe** [comment]
The CI build started up just fine this morning as shown at:

* https://testing.sandia.gov/cdash/index.php?project=Trilinos&parentid=3485747&filtercount=3&showfilters=1&field1=groupname&compare1=61&value1=Continuous&field2=buildstarttime&compare2=84&value2=now&filtercombine=and

Whatever caused this problem did not occur today

Closing as complete.

**Comment by mhoemmen** [comment]
@bartlettroscoe There was a CEE LAN outage yesterday, so yes :)  It's back now.
