### ISSUE TITLE
Tpetra: Fix Type-2 FEM Assembly Example

### ISSUE THREAD

**Issue by william76** [trilinos/Trilinos#2516]
@trilinos/tpetra 

Modify the Local Element Loop example in-line with @mhoemmen comments from our meeting on 3/29(

My notes:
- fillComplete on overlapping matrix needs to provide domain and range map.
  - fillComplete has overlapped row map but domain/range map are one-to-one.
  - Owned graph does not require them, though row-map is used as a domain map by default (but might be good to include them anyway).
- Clean up memory  (I don't remember what memory he was referring to, will have to look and see)
- crsGraph construction:
  - fill owned with owned
  - fill shared with shared
  - then export
- BUG: need to have both domain and range maps.  
  - @mhoemmen I'll probably have to sync up with you on this to make sure I'm following what we want to do here.

Mark's notes from 3/27 and Karen's notes from 3/29 will have some useful information in them.

**Comment by william76** [comment]
Closing out an old issue that's probably been fixed or is no longer relevant.

**Comment by mhoemmen** [comment]
I think this did get fixed, thanks to @csiefer2 et al.
