### ISSUE TITLE
Zoltan2 serial build error

### ISSUE THREAD

**Issue by jwillenbring** [trilinos/Trilinos#252]
@trilinos/zoltan2 

I tried to build Zoltan2 using the following cmake arguments:

cmake \
-DTrilinos_ENABLE_TESTS:BOOL=ON \
-DTrilinos_ENABLE_ALL_PACKAGES:BOOL=OFF \
-DTrilinos_ENABLE_Zoltan2=ON \
../Trilinos

I got the following error:

[ 92%] Building CXX object packages/zoltan2/test/unit/CMakeFiles/Zoltan2_Mapping.dir/problems/Mapping.cpp.o
In file included from /scratch1/jmwille/TrilinosTest/Trilinos/packages/zoltan2/src/problems/Zoltan2_MappingProblem.hpp:60:0,
                 from /scratch1/jmwille/TrilinosTest/Trilinos/packages/zoltan2/test/unit/problems/Mapping.cpp:55:
/scratch1/jmwille/TrilinosTest/Trilinos/packages/zoltan2/src/algorithms/partition/Zoltan2_TaskMapping.hpp: In function ‘void Zoltan2::getCoarsenedPartGraph(const Zoltan2::Environment*, const Teuchos::Comm<int>*, const Zoltan2::GraphModel<typename Adapter::base_adapter_t>*, part_t, const part_t*, Teuchos::ArrayRCP<T>&, Teuchos::ArrayRCP<T>&, Teuchos::ArrayRCP<Packet>&)’:
/scratch1/jmwille/TrilinosTest/Trilinos/packages/zoltan2/src/algorithms/partition/Zoltan2_TaskMapping.hpp:298:24: error: ‘getRawMpiComm’ is not a member of ‘Teuchos’
make[2]: *** [packages/zoltan2/test/unit/CMakeFiles/Zoltan2_Mapping.dir/problems/Mapping.cpp.o] Error 1
make[1]: *** [packages/zoltan2/test/unit/CMakeFiles/Zoltan2_Mapping.dir/all] Error 2
make: *** [all] Error 2

It looks like Zoltan2 is making a call to Teuchos that requires MPI to be enabled, but this is a serial build. I produced this error on a RHEL6 machine, using GCC 4.7.2, and specifically the SEMS NFS module:

module load gcc/4.7.2/base

**Comment by mndevec** [comment]
Sorry about this, my latest commit should fix this issue.

**Comment by jwillenbring** [comment]
Sorry I forgot to report back. Your change did fix the issue.

**Comment by mndevec** [comment]
No problem, sorry about the bug again.
