### ISSUE TITLE
Ifpack2: Thyra adapter sets overlap parameter for relaxtion preconditioners

### ISSUE THREAD

**Issue by cgcgcg** [trilinos/Trilinos#2521]
@trilinos/ifpack2 

## Current Behavior
The Ifpack2 Thyra adapter sets the parameter "schwarz: overlap level" independent of the requested preconditioner. For "relaxation" this fails, since "schwarz: overlap level" is not a valid parameter.

## Possible Solution
Changing https://github.com/trilinos/Trilinos/blob/ef00b09e946db5a4d1bf8e88fdbbac8c1d539959/packages/ifpack2/adapters/thyra/Thyra_Ifpack2PreconditionerFactory_def.hpp#L175
 to 
```
if (constParamList->isType<int> ("Overlap") && ! packageParamList.is_null () && ! packageParamList->isType<int> ("schwarz: overlap level") && preconditionerType != "relaxation") {
```
fixes the issue for "relaxation", but it is possible that there are other preconditioners that don't like the parameter either.

**Comment by cgcgcg** [comment]
@mhoemmen I'm happy to put this fix in, but would like to hear your opinion first..

**Comment by mhoemmen** [comment]
@cgcgcg Why not just have it check whether `preconditionerType` is one of the various aliases for AdditiveSchwarz?  (See Ifpack2's factory for the meaning of "various aliases.")

**Comment by cgcgcg** [comment]
@mhoemmen Is that the only one that takes the overlap argument? Then I will do that. Thanks :-)

**Comment by mhoemmen** [comment]
@cgcgcg wrote:
> Is that the only one that takes the overlap argument?

Please check Ifpack2 to be sure, but I think so.

**Comment by mhoemmen** [comment]
@cgcgcg Ifpack2's factory upper-cases the entire input preconditioner name before comparisons, so your check should do the same.  See e.g., lines 66-73 of `Ifpack2_Details_Factory_def.hpp`:

https://github.com/trilinos/Trilinos/blob/a27130bc4f5d7dba02be3cb976d1edc8653f941b/packages/ifpack2/src/Ifpack2_Details_Factory_def.hpp#L66
