### ISSUE TITLE
  TEUCHOS_UNREACHABLE_RETURN(Teuchos::null) still throws a warning in cuda.

### ISSUE THREAD

**Issue by bathmatt** [trilinos/Trilinos#2524]
Even with this call at the end of a function I get warnings in cuda.  Not sure on the magic that is needed but ...

```
/home/mbetten/Trilinos/EMPIRE/src/PIC/InjectionBCs.hpp(289): warning: missing return statement at end of non-void function "empire::pic::createInjectionBC(const empire::pic::ElementalParticleData<MESH_TRAITS> &, const Teuchos::RCP<panzer::UniqueGlobalIndexerBase> &, const panzer_stk::STK_Interface &, const std::__cxx11::string &, const Teuchos::ParameterList &) [with MESH_TRAITS=empire::TetSecondOrder]"
```

but this is the end of that function

```
  TEUCHOS_UNREACHABLE_RETURN(Teuchos::null);
}


```

**Comment by jhux2** [comment]
@bartlettroscoe

**Comment by bartlettroscoe** [comment]
@bathmatt, what CUDA version is this?  How can I reproduce this?

That macro was added with an explicit check for `__NVCC__` in the commit 8e3a5f454b69079c8eac784437ed59b9a415e0a7:

```
commit 8e3a5f454b69079c8eac784437ed59b9a415e0a7
Author: Roscoe A. Bartlett <rabartl@sandia.gov>
Date:   Mon Mar 20 18:58:28 2017 -0600

    Teuchos: Skip return only for NVCC (#1133, #1140)
    
    After talking with Roger P. I have changed this to only remove the return
    statement for __NVCC__.  This is because only __NVCC__ warns about the
    unreachable return but having that return statement leads to safer code by
    avoiding undefined behavior in case a function is modified in such a way that
    this return is no longer unreachable.  In that case, we want it to return
    something to avoid undefined behavior.
    
    I also improved the documentation some.

M       packages/teuchos/core/src/Teuchos_CompilerCodeTweakMacros.hpp
```

**Comment by bartlettroscoe** [comment]
@trilinos/teuchos

**Comment by ibaned** [comment]
@bartlettroscoe I have an equivalent macro in a library of mine, and the logic is to only omit the return if `__clang__` is defined. So far that builds without warnings with CUDA 8 and 9, also with Clang and GCC.

**Comment by bartlettroscoe** [comment]
> @bartlettroscoe I have an equivalent macro in a library of mine, and the logic is to only omit the return if __clang__ is defined. So far that builds without warnings with CUDA 8 and 9, also with Clang and GCC.

@ibaned,

Does the NVCC compiler define the macro `__clang__`?  I guess we can try that.   But it would be good to reproduce the warning that @bathmatt mentions above to make sure that this change will fix this first.

@bathmatt, how can I reproduce the warning you are seeing?

**Comment by bartlettroscoe** [comment]
@bathmatt, can you please let me what machine and build of Trilinos you saw these warnings in?

**Comment by bathmatt** [comment]
My machine, and I think ride, but I know my machine.  It is gcc5.3 and cuda9.1

also, ever since sandia blocked gmail access I no longer really see any github issues.  our mail system is so jacked I don't wanna move to it.

**Comment by mhoemmen** [comment]
@bathmatt i just treat github like work facebook and poll the web site for notifications :(

**Comment by prwolfe** [comment]
@mhoemmen - I also treat GitHub like work Facebook and forget about it regularly ;_>. Bit me today.
