### ISSUE TITLE
Add the ability to have longs in yaml decks

### ISSUE THREAD

**Issue by bathmatt** [trilinos/Trilinos#2529]
Moving email thread to github

Currently if I have a param in a yaml deck

foo: 1234567890
it errors out.  Here is a discussion from Paul Lin and @ibaned and @rppawlo  

My preferred solution is to see if it is > INT_MAX and then read it as a long and then let me grab it that way and use a filter for the long/int stuff.

Thoughts

```

Yuck. I don’t like any of the solutions. Least favorite is the string thing – it feels like a hack and will probably confuse users. I like the tag better than the string, but then we need to again train users on something that feels hackish. For the INT_MAX solution, we do have a validator object that we can tell it the numeric types to accept and then it automatically converts it to the right type. So we could allow for int, long and  long long types and the validator can convert automagically to long long. I feel uneasy about this but after 14 years of PL use and this being the first time this issue crops up probably means it won’t happen much. This might be one question to take to the larger community?

 

Matt – any preference since EMPIRE is the code in question?

 

Roger

 

From: "Ibanez, Daniel Alejandro" <daibane@sandia.gov>
Date: Monday, April 9, 2018 at 9:40 AM
To: Roger Pawlowski <rppawlo@sandia.gov>, Paul Lin <ptlin@sandia.gov>
Subject: Re: Teuchos ParameterLists should not have any trouble with type long (64-bit integer) ?

 

Yea, 64-bit integers definitely have use cases in our input files…

Without changing the code, you can make it a string type by putting single or double quotes around the value.

 

Count: ‘2467430400’

 

I could change the code so the type will be “long long” if the value is bigger than INT_MAX, but then the type depends on the value

I could also add something like int64 as a tag name:

 

Count: !!int64 2467430400

 

Let me know what you think,

 

Dan

 

From: "Pawlowski, Roger P" <rppawlo@sandia.gov>
Date: Monday, April 9, 2018 at 5:49 AM
To: "Lin, Paul" <ptlin@sandia.gov>
Cc: "Ibanez, Daniel Alejandro" <daibane@sandia.gov>
Subject: Re: Teuchos ParameterLists should not have any trouble with type long (64-bit integer) ?

 

Looks like the yaml language doesn’t support the concept of long. They suggest using a string in the link below. You will have to explicitly tell the yaml parser the type in the input file.

 

https://stackoverflow.com/questions/36191276/yaml-how-to-cast-value-to-long-in-yaml-fil?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa

 

http://yaml.org/type/int.html

 

Also pinging Dan for his recommendation.

 

Roger

 

From: Paul Lin <ptlin@sandia.gov>
Date: Monday, April 9, 2018 at 7:35 AM
To: Roger Pawlowski <rppawlo@sandia.gov>
Cc: Paul Lin <ptlin@sandia.gov>
Subject: Re: Teuchos ParameterLists should not have any trouble with type long (64-bit integer) ?

 

Hello Roger,

Actually I didn't use decimal notation; I gave "Count" an integer:



  Initial Particle Conditions:
    Electrons:
      All: # Fill the full domain
        Fill Pattern: Random in Element
        Type: e-
        Temperature: 1150000.0
        Count: 2467430400
        Density: 1e16



But it assumed it was a decimal.

I'll play around with it myself so that you need not waste your time.
I'll look at the yaml parser again.

thanks
-paul

 
```

**Comment by rppawlo** [comment]
Maybe jump to "long long" instead of "long" for type if greater than INT_MAX?

@pwxy

**Comment by ibaned** [comment]
@rppawlo agreed about `long long`

**Comment by bartlettroscoe** [comment]
On some platforms, `long int` is no larger than `int` is you have to go to `long long int` if you want to guarantee a 64 bit `int`.

Is there any impediment to switching from `int` to `long long int` other than having to update a bunch code that does `getParameter<int>(....)`?  And not that we can put in automatic conversions from `long long int` to `int` if we want.  There are special PL validators in Teuchos that can do this sort of thing.  

I think that means that the YAML just needs to store ints implicitly as `long long int`.

**Comment by mhoemmen** [comment]
I like the automatic conversions idea.  We could generalize so it works for any output integer type.

**Comment by ibaned** [comment]
@bartlettroscoe I'm fine interpreting all integral values as `long long` if we're okay dealing with the downstream breakage. I suspect there will be a lot of such breakage though in apps like Albany and also those @bathmatt is involved with. Both that and value-dependent typing are pretty straightforward for me to implement, so all I need is consensus on a direction.

**Comment by mhoemmen** [comment]
@ibaned Would it break if YAML added a custom ParameterList thingie that interpreted all `long long` as any desired integer type?

**Comment by ibaned** [comment]
@mhoemmen thats not really something I can do within the YAML parser itself, that has to be supported in `Teuchos::ParameterList` itself and/or through validators. For me personally it sounds fine to have safety-checked conversions between integer types in the `get` functions.

**Comment by bathmatt** [comment]
Stupid idea but -D Teuchos_ParameterListIntegerType="long long"
at configure?  I hate crap like this but it gives time to fix the other codes.

**Comment by bartlettroscoe** [comment]
> @mhoemmen thats not really something I can do within the YAML parser itself, that has to be supported in Teuchos::ParameterList itself and/or through validators. For me personally it sounds fine to have safety-checked conversions between integer types in the get functions.

One simple thing to do do is to add `long long int` as one of the input and preferred output types to the subclass [Teuchos::AnyNumberParameterEntryValidator](https://trilinos.org/docs/dev/packages/teuchos/doc/html/classTeuchos_1_1AnyNumberParameterEntryValidator.html).

Another idea is to add some smart specialization logic to the Teuchos const parameter get function that automatically allow the conversion from one type to another using the `Teuchos::asSafe<>()` function.   And we might just do this for certain classes of types.  For example, `Teuchos::getParameter<int>(pl, name)` could accept any integral type `long int`, `long long int`, etc. and then use `Teuchos::asSafe<int>(actual-type-val)` to convert it.  If there was a conversion problem (like the actual value can't be represented in `int`) then it would throw an exception.  That way, each consumer object would not have to use the `Teuchos::AnyNumberParameterEntryValidator` object for validating.

**Comment by ibaned** [comment]
I like @bartlettroscoe 's two proposed ideas, as pre-requisites to changing all integral values to be of type `long long`.

**Comment by ibaned** [comment]
Slight wrench in the works for the second idea: `getParameter` and friends return a reference, not a value. If we are going to convert the type in that function, it needs to return a value.

**Comment by bartlettroscoe** [comment]
> Slight wrench in the works for the second idea: `getParameter` and friends return a reference, not a value. If we are going to convert the type in that function, it needs to return a value.

Good point.  Hopefully we can change the return from a `const <type>&` to `<type>` without breaking any backward compatibility.  It is crazy to think that someone would create a pointer or reference data member to what comes out of `Teuchos::getParameter<>()`.  Making this change will fix that!

**Comment by ibaned** [comment]
I know in my own code I've done things like
```cpp
std::string const& name = getParameter<std::string>(...);
```
to avoid the tiny overhead of making a copy of the string. Hopefully apps don't do much of this.

**Comment by bartlettroscoe** [comment]
> `std::string const& name = getParameter<std::string>(...);`

That will still work.   A const reference can hold on to a temp value.  What will **not** work after this refactoring is:

```
const std::string  * name = &getParameter<std::string>(...);
```

**Comment by ibaned** [comment]
Oh okay, I think I'm okay with those outcomes.

**Comment by bartlettroscoe** [comment]
I just realized that we can't change the return type from a reference to return-by-value for all types for the Teuchos::ParameterList since there are some big objects managed in a Teuchos::ParameterList.

Instead, we need to find a way to selectively return some types by value (like simple integral and floating-point types with conversions) and return everything else (that does not require conversions) by reference.  I think with C++11 that will be possible.

The other way around this, as I mention [above](https://github.com/trilinos/Trilinos/issues/2529#issuecomment-380257577), is to add `long long int` to the set of types to [Teuchos::AnyNumberParameterEntryValidator](https://trilinos.org/docs/dev/packages/teuchos/doc/html/classTeuchos_1_1AnyNumberParameterEntryValidator.html) and then update the parameter valuation of the classes that expect `int` prameters to do this conversion automatically at validation time.  That will require more grunt work but I think that might be the better solution.  And it will have the side-effect of adding proper PL validation to some software that might otherwise be missing it in Trilinos.

**Comment by ibaned** [comment]
@bartlettroscoe is there a good example of using validators to get all your parameters?

**Comment by pwxy** [comment]
So it sounds like this is going to be really hard to fix on the Trilinos side, and there will not be any resolution for a while?

**Comment by ibaned** [comment]
I've put up a new pull request with a less drastic but still functional solution: values that don't fit in `int` are returned as `long long` by the YAML reader, and the `AnyNumber` validator supports `long long`: #2614

**Comment by ibaned** [comment]
Okay, there was unanimous approval on that PR and it was merged.

@bathmatt @pwxy let me know if this solution works out for your application, and feel free to ask more questions about how to use it.

**Comment by pwxy** [comment]
@ibaned thanks for the fix

**Comment by bathmatt** [comment]
So, I'm trying this and I can't figure out how to get the long long version of the variable?

I can validate it.

```
  long long one=1;
  {
    Teuchos::ParameterList valid_pl;
    valid_pl.set("Sub", one, "", Teuchos::RCP<Teuchos::AnyNumberParameterEntryValidator>(new Teuchos::AnyNumberParameterEntryValidator()));
    TEST_NOTHROW(pl->validateParametersAndSetDefaults(valid_pl));
    std::cout << pl->get<long long>("Sub"); /// This excepts.
  }


```

**Comment by bathmatt** [comment]
Or, does it promote it to a double?  
If i get it as a double that works,

**Comment by rppawlo** [comment]
I think you need to build the validator like this:

```
Teuchos::AnyNumberParameterEntryValidator::AcceptedTypes intTypes;
intTypes.allowInt(true);
intTypes.allowLongLong(true);

RCP<Teuchos::AnyNumberParameterEntryValidator> intValidator =
  Teuchos::rcp( new Teuchos::AnyNumberParameterEntryValidator(
  Teuchos::AnyNumberParameterEntryValidator::PREFER_LONG_LONG, intTypes) );
```

**Comment by bartlettroscoe** [comment]
A more direct way of add that that validator is the function [setLongLongParameter()](https://trilinos.org/docs/dev/packages/teuchos/doc/html/classTeuchos_1_1ParameterList.html#a37c0ec92ab05054c79fd36e04b2b70ca).

You use it like:

```
Teuchos::setLongLongParameter("<paramName>", <defaultVal>, "<docString>", &<paramListInOut>,
   Teuchos::AnyNumberParameterEntryValidator::AcceptedTypes().allowInt(true).allowLongLong(true)
   );
```

You can leave off the last argument and it will accept all supported types if you want (i.e. double, string, int, long int).

Nice, right?
