### ISSUE TITLE
Teuchos::Time screwing up OpenMP/Threads performance

### ISSUE THREAD

**Issue by etphipp** [trilinos/Trilinos#253]
I recently wrote a performance test in Sacado that tests the performance of a Kokkos kernel using Sacado.  I used Teuchos::Time to measure the time the kernel took to run and was seeing very bad performance on CPUs using both the OpenMP and Threads execution spaces in Kokkos.  For a single Sandy Bridge socket I was expecting my kernel to get about 9 GFLOP/s, and using 8 threads I was only seeing about 1 GFLOP/s.  Furthermore, using the Serial execution space, I was seeing about 3 GFLOP/s.  However I was seeing the level of expected throughput on KNC (using OpenMP) and Cuda.  Purely by accident, I changed the timer from Teuchos::Time to Kokkos::Impl::Timer and suddenly my CPU performance jumped up to about what I expected.  This behavior was reproducible on two different machines (my local development machine and Shannon) and with multiple compilers (GCC 4.9.3 and Intel 15.0.3).  Has anyone else seen this before or have an idea why Teuchos::Time might be screwing up performance on CPUs with OpenMP or Threads?  Teuchos::Time doesn’t have any threaded code in it, does it?  I’m a little bit concerned the impact this might have based on the pervasive usage of Teuchos::TimeMonitor throughout Trilinos.

**Comment by etphipp** [comment]
Looking inside Teuchos::Time, I suspect it is this code that is causing the problem:

```
double Time::wallTime()
{
  /* KL: warning: this code is probably not portable! */
  /* HT: have added some preprocessing to address problem compilers */
        /* RAB: I modifed so that timer will work if MPI support is compiled in but not initialized */

#ifdef HAVE_MPI

        int mpiInitialized;
        MPI_Initialized(&mpiInitialized);

        if( mpiInitialized ) {

                return(MPI_Wtime());

        }
        else {

                clock_t start;

                start = clock();
                return( (double)( start ) / CLOCKS_PER_SEC );

        }
```

My performance test is serial, but I had MPI enabled in my build, so effectively I was timing my kernel, plus MPI initialization time!

Is there some other way we can ensure the timer works in this setting without adding MPI initialization inside the routine that is queried to measure time?

**Comment by etphipp** [comment]
Ross says,

You could add a static function Teuchos::Time::initializeTimer() and the call that in main().  In fact, we could make the Teuchos::CommandlineProcessor call that automatically on startup.

**Comment by bartlettroscoe** [comment]
NOTE: The code:

```
        int mpiInitialized;
        MPI_Initialized(&mpiInitialized);

        if( mpiInitialized ) {

                return(MPI_Wtime());

        }
       else {
            …
       }
```

is not initializing MPI.  It is just querying to see seeing if MPI is initialized.  Perhaps that is an expensive operation?

@etphipp, If you comment out that check, what does the timers look like for your exact use case?  Do you get compatible timings with Kokkos:::Timer?  Is Kokkos::Timer measuring wallclock time or CPU time?  I think you want wallclock time in general.

Assuming that `MPI_Initialized()` does bad things in a threaded program, here are the options:

1. Stop using MPI_Wtime() and go with the more portable implementation.  You could just go with the Kokkos Timer implementation but we would have to see what time resolution that gives you.
2. Add a debug-mode check to assert that MPI is initialized and if not, thown or abort.  This is handled automatically by Teuchos::GlobalMPISession.  Is your timing code using Teuchos::GlobalMPISession in main()?
3. If KokkosCore is enabled, just use Kokkos::Impl::Timer funtions for the guts of Teuchos::Time.

Assuming that MPI_Wtime() is a good implementation ([which it seems to be](http://stackoverflow.com/questions/17349703/difference-between-clock-and-mpi-wtime)), then I would go with option-2.  This means that if you are buliding with MPI then you must call MPI_init() at the beginning of your program.  That will break backward compatibility but at least it may avoid bad timing in a threaded program.  As the selected timer implementation is portable and has good resolution and measures real wallclock time, then I don't really care what gets used.

Other options?

Other opinions?

**Comment by etphipp** [comment]
So its not the MPI_Initialized calls.  I commented out those lines out and got the same, bad timings.

I instead commented out the whole #ifdef HAVE_MPI block, which falls down to a block of code that uses gettimeofday().  That code gave me results similar to what Kokkos gives me.  I looked in the implementation of the Kokkos timer and it uses gettimeofday() as well.

**Comment by bartlettroscoe** [comment]
> So its not the MPI_Initialized calls. I commented out those lines out and got the same, bad timings.

So what you are saying is that MPI_Wtime() is doing some bad with threads?

Do you know what the timer resolution is for that implementation?  I used to have a program that would determine that automatically but I can't seem to find it right away in Teuchos.

But note that there is a discussion in kokkos/kokkos#234 about what timer should really be used.  Note that I am okay with just using the Kokkos::Impl::Timer if KokkosCore is enabled.  But it is such a small amount of code, that seems unnecessary.  It is nice to also have the ifdefs for other timers on other platforms where Kokkos does not work (e.g. MS Windows).

Therefore, we might wait to see how kokkos/kokkos#234 resolves, and then decide what to to with Teuchos::Time.  Sound reasonable?

**Comment by etphipp** [comment]
No, it looks like it is the call to clock(), I guess.  MPI isn't initialized, so MPI_Wtime() isn't called.

**Comment by bathmatt** [comment]
have you run it through vtune?  You might try that to see where the
bottleneck really is.

**Comment by etphipp** [comment]
I tried that once when I was trying to figure out what was going wrong.  VTune wasn't helpful.

**Comment by jhux2** [comment]
> I recently wrote a performance test in Sacado that tests the performance of a Kokkos kernel using Sacado. I used Teuchos::Time to measure the time the kernel took to run and was seeing very bad performance on CPUs using both the OpenMP and Threads execution spaces in Kokkos. For a single Sandy Bridge socket I was expecting my kernel to get about 9 GFLOP/s, and using 8 threads I was only seeing about 1 GFLOP/s. Furthermore, using the Serial execution space, I was seeing about 3 GFLOP/s. However I was seeing the level of expected throughput on KNC (using OpenMP) and Cuda. Purely by accident, I changed the timer from Teuchos::Time to Kokkos::Impl::Timer and suddenly my CPU performance jumped up to about what I expected. This behavior was reproducible on two different machines (my local development machine and Shannon) and with multiple compilers (GCC 4.9.3 and Intel 15.0.3). Has anyone else seen this before or have an idea why Teuchos::Time might be screwing up performance on CPUs with OpenMP or Threads? Teuchos::Time doesn’t have any threaded code in it, does it? I’m a little bit concerned the impact this might have based on the pervasive usage of Teuchos::TimeMonitor throughout Trilinos.

@etphipp How did you end up working around this?
