### ISSUE TITLE
Intrepid2 Build errors with Intel 

### ISSUE THREAD

**Issue by crtrott** [trilinos/Trilinos#254]
I get tons of errors like this with Intrepid2 using the Intel 15.0.2 compiler. This is a non-threaded build, using the sampleScripts/Sandia-SEMS/configure-all script with the addition of enabling Intrepid2. 
Might be a non-standard conform usage of initializer lists which gcc allows, but intel doesn't.  

/home/crtrott/Trilinos/packages/intrepid/src/Shared/MiniTensor/Intrepid_MiniTensor_Solvers.h: In instantiation of \u2018bool Intrepid::_GLOBAL__N__42_tmpxft_0000a64b_00000000_7_test_02_cpp1_ii_main::solveFN(FN&, const Intrepid::Vector<T, N>&) [with FN = Intrepid::_GLOBAL__N__42_tmpxft_0000a64b_00000000_7_test_02_cpp1_ii_main::SquareRootNLS<double>; T = double; unsigned int N = 2u]\u2019:
/home/crtrott/Trilinos/packages/intrepid/test/Shared/MiniTensor/test_02.cc:1017:51:   required from here
/home/crtrott/Trilinos/packages/intrepid/src/Shared/MiniTensor/Intrepid_MiniTensor_Solvers.h:328:8: error: too many braces around initializer for \u2018double\u2019 [-fpermissive]
/home/crtrott/Trilinos/packages/intrepid/src/Shared/MiniTensor/Intrepid_MiniTensor_Solvers.h:328:8: error: invalid conversion from \u2018<brace-enclosed initializer list>\u2019 to \u2018double\u2019 [-fpermissive]
/home/crtrott/Trilinos/packages/intrepid/src/Shared/MiniTensor/Intrepid_MiniTensor_Solvers.h:328:8: error: aggregate value used where a float was expected
/home/crtrott/Trilinos/packages/intrepid/src/Shared/MiniTensor/Intrepid_MiniTensor_Solvers.h:328:8: error: too many braces around initializer for \u2018double\u2019 [-fpermissive]
/home/crtrott/Trilinos/packages/intrepid/src/Shared/MiniTensor/Intrepid_MiniTensor_Solvers.h:328:8: error: invalid conversion from \u2018<brace-enclosed initializer list>\u2019 to \u2018double\u2019 [-fpermissive]
/home/crtrott/Trilinos/packages/intrepid/src/Shared/MiniTensor/Intrepid_MiniTensor_Solvers.h:328:8: error: aggregate value used where a float was expected
/home/crtrott/Trilinos/packages/intrepid/src/Shared/MiniTensor/Intrepid_MiniTensor_Solvers.h:328:8: error: too many braces around initializer for \u2018double\u2019 [-fpermissive]
/home/crtrott/Trilinos/packages/intrepid/src/Shared/MiniTensor/Intrepid_MiniTensor_Solvers.h:328:8: error: invalid conversion from \u2018<brace-enclosed initializer list>\u2019 to \u2018double\u2019 [-fpermissive]
/home/crtrott/Trilinos/packages/intrepid/src/Shared/MiniTensor/Intrepid_MiniTensor_Solvers.h:328:8: error: aggregate value used where a float was expected
/home/crtrott/Trilinos/packages/intrepid/src/Shared/MiniTensor/Intrepid_MiniTensor_Solvers.h:328:8: error: too many braces around initializer for \u2018double\u2019 [-fpermissive]
/home/crtrott/Trilinos/packages/intrepid/src/Shared/MiniTensor/Intrepid_MiniTensor_Solvers.h:328:8: error: invalid conversion from \u2018<brace-enclosed initializer list>\u2019 to \u2018double\u2019 [-fpermissive]

@trilinos/intrepid2

**Comment by kyungjoo-kim** [comment]
Hi Christian,


    The minitensor is developed and maintained by Alejandro Mota and I CC'ed him in this message. BTW, which code use mini tensor ? Mini tensor is supposed to be activated with Intrepid_ENABLE_Boost and by default this cmake flag is not set up.


Hi Alejandro,


    It is reported that the code does not comply C++ standards. Would you please to squeeze time to fix or bypass this problem for intel compilers ?


Best,

Kyungjoo


________________________________

**Comment by crtrott** [comment]
Actually it is Intrepid not Intrepid2: furthermore I noticed that I had OMPI_CXX still set to use nvcc_wrapper, so it was probably Cuda 7.5 + GCC 4.7.2. I will close this for now, since that is a combination we do not like anyway.
