### ISSUE TITLE
-D Kokkos_ARCH is not correct... and we have no error that makes this clear

### ISSUE THREAD

**Issue by csiefer2** [trilinos/Trilinos#2545]
We're supposed to set -D KOKKOS_ARCH on configure, but if one screws up and does -D Kokkos_ARCH, stuff woofs much later in configure without this mistake being obvious.

Can we catch this somewhere in Kokkos (or Trilinos) configure and tell the user exactly what to do.

@ibaned @crtrott

**Comment by ibaned** [comment]
@csiefer2 yep, I'll get an error message in there. The new task is in the Kokkos repo, kokkos/kokkos#1555

**Comment by csiefer2** [comment]
@ibaned Cool, thanks!

**Comment by ibaned** [comment]
I'll close this one, progress can be tracked in the Kokkos one.
