### ISSUE TITLE
Framework:  Configure does not issue warning if package is both ON and OFF

### ISSUE THREAD

**Issue by csiefer2** [trilinos/Trilinos#2578]
If you explicitly turn a package both ON and OFF during configure, cmake happily lets you do that without warning you that this might not be what you intended.

Can this be fixed in TriBITS / Trilinos?

@jwillenbring @bartlettroscoe

**Comment by bartlettroscoe** [comment]
@csiefer2, can you give a concrete example that we can reproduce?

Note:

* https://tribits.org/doc/TribitsDevelopersGuide.html#disables-trump-enables-where-there-is-a-conflict
* https://tribits.org/doc/TribitsDevelopersGuide.html#project-name-disable-enabled-forward-dep-packages
* https://tribits.org/doc/TribitsDevelopersGuide.html#conflicting-explicit-enable-and-disable
* https://tribits.org/doc/TribitsBuildReference.html#disable-a-package-and-all-its-dependencies

Do any of these explain the behavior you are seeing?

CC: @fryeguy52

**Comment by csiefer2** [comment]
This is actually a non-issue.  I miscaptialized an option and configure exited with an error before it could tell me my option was unused.

Closing.
