### ISSUE TITLE
Teuchos: Geminga Cuda builds failing

### ISSUE THREAD

**Issue by csiefer2** [trilinos/Trilinos#2589]
`packages/teuchos/core/src/Teuchos_CommandLineProcessor.cpp(213): error: identifier "OPT_LONG_LONG_INT" is undefined`

https://testing.sandia.gov/cdash/viewBuildError.php?buildid=3513020

Any ideas, Teuchos team?

@jhux2

**Comment by mhoemmen** [comment]
@csiefer2 Does that configure set `Teuchos_ENABLE_LONG_LONG_INT:BOOL=OFF`?  If so, @ibaned and I might be able to help.  Best practice is not to set that CMake option, but we still don't want builds to break if it's OFF.

**Comment by jhux2** [comment]
@trilinos/teuchos

**Comment by bartlettroscoe** [comment]
Just as a frame of reference, the ATDM CUDA builds on hansen, white, and ride passed last night as shown at:

* https://testing-vm.sandia.gov/cdash/index.php?project=Trilinos&date=2018-04-19&filtercombine=and&filtercombine=and&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=63&value1=-atdm-&field2=subprojects&compare2=93&value2=Teuchos&field3=groupname&compare3=61&value3=ATDM

Don't know if this is the same version of Trilinos or not.

**Comment by jhux2** [comment]
> Does that configure set Teuchos_ENABLE_LONG_LONG_INT:BOOL=OFF? If so, @ibaned and I might be able to help. Best practice is not to set that CMake option, but we still don't want builds to break if it's OFF.

@mhoemmen Yes, `Teuchos_ENABLE_LONG_LONG_INT:BOOL=OFF`.

<details>

```
/projects/sems/install/rhel6-x86_64/sems/utility/cmake/3.5.2/bin/cmake
-DTrilinos_TRIBITS_DIR=/data/jhu/trilinos-test/trilinos/cmake/tribits
-DCTEST_USE_LAUNCHERS:BOOL=1
-DTrilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=ON
-DTrilinos_WARNINGS_AS_ERRORS_FLAGS:STRING=
-DTrilinos_ALLOW_NO_PACKAGES:BOOL=ON
-DTrilinos_DISABLE_ENABLED_FORWARD_DEP_PACKAGES=ON
-DTrilinos_DEPS_XML_OUTPUT_FILE:FILEPATH=
-DTrilinos_ENABLE_SECONDARY_TESTED_CODE:BOOL=ON
-DTrilinos_EXTRAREPOS_FILE:STRING=/data/jhu/trilinos-test/trilinos/cmake/ExtraRepositoriesList.cmake
-DTrilinos_IGNORE_MISSING_EXTRA_REPOSITORIES:BOOL=ON
-DTrilinos_ENABLE_KNOWN_EXTERNAL_REPOS_TYPE:STRING=Experimental
-DTrilinos_ENABLE_TESTS:BOOL=
-DTrilinos_ENABLE_Kokkos:BOOL=
-DTrilinos_ENABLE_Gtest:BOOL=OFF
-DCMAKE_BUILD_TYPE:STRING=RELEASE
-DTrilinos_ENABLE_COMPLEX:BOOL=OFF
-DCMAKE_CXX_USE_RESPONSE_FILE_FOR_OBJECTS:BOOL=ON
-DBUILD_SHARED_LIBS:BOOL=ON
-DTrilinos_ENABLE_CXX11:BOOL=ON
-DTrilinos_CXX11_FLAGS:STRING='-std=c++11 -expt-extended-lambda'
-DCMAKE_CXX_FLAGS:STRING='-Wall -Wno-unknown-pragmas
-Wno-unused-but-set-variable -Wno-inline -Wshadow'
-DTrilinos_ENABLE_Fortran:BOOL=OFF
-DTPL_ENABLE_CUDA:BOOL=ON
-DTPL_ENABLE_CUSPARSE:BOOL=ON
-DTPL_ENABLE_HWLOC:BOOL=OFF
-DKokkos_ENABLE_Cuda:BOOL=ON
-DKokkos_ENABLE_Cuda_UVM:BOOL=ON
-DKokkos_ENABLE_Cuda_Lambda:BOOL=ON
-DTrilinos_ENABLE_Epetra:BOOL=OFF
-DTrilinos_ENABLE_ShyLU_Node:BOOL=OFF
-DCMAKE_VERBOSE_MAKEFILE:BOOL=ON
-DTPL_ENABLE_MPI:BOOL=ON
-DMPI_BASE_DIR:PATH=/projects/sems/install/rhel6-x86_64/kokkos/compiler/gcc/5.3.0/openmpi/1.8.7/cuda/8.0.44
-DTrilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON
-DTeuchos_ENABLE_LONG_LONG_INT:BOOL=OFF
-DTpetra_INST_INT_INT:BOOL=ON
-DTpetra_INST_INT_LONG:BOOL=ON
-DTpetra_INST_INT_LONG_LONG:BOOL=OFF
-DTpetra_INST_COMPLEX_DOUBLE:BOOL=OFF
-DTpetra_INST_COMPLEX_FLOAT:BOOL=OFF
-DTpetra_INST_SERIAL=ON
-DKOKKOS_ARCH=SNB Kepler35
-DTrilinos_ENABLE_DEPENDENCY_UNIT_TESTS:BOOL=OFF
-DTeuchos_GLOBALLY_REDUCE_UNITTEST_RESULTS:BOOL=ON
-DTPL_ENABLE_SuperLU:BOOL=ON
-DSuperLU_INCLUDE_DIRS:PATH=/projects/sems/install/rhel6-x86_64/sems/tpl/superlu/4.3/gcc/5.3.0/base/include
-DSuperLU_LIBRARY_DIRS:PATH=/projects/sems/install/rhel6-x86_64/sems/tpl/superlu/4.3/gcc/5.3.0/base/lib
-DTPL_ENABLE_AmgX=ON
-DAmgX_LIBRARY_DIRS=/usr/local/amgx/lib
-DAmgX_INCLUDE_DIRS=/usr/local/amgx/include
-DMueLu_ENABLE_Experimental:BOOL=ON
-DMueLu_ENABLE_Kokkos_Refactor:BOOL=ON
-DXpetra_ENABLE_Experimental:BOOL=ON
-DXpetra_ENABLE_Kokkos_Refactor:BOOL=ON
-DTrilinos_ENABLE_Teuchos:BOOL=ON
-GUnix Makefiles
/data/jhu/trilinos-test/OPENMPI-1.8.7_RELEASE_AMGX_CUDA-8.0.44/Trilinos
```

<\details>

**Comment by ibaned** [comment]
Yep, this has to do with turning `long long` off. I put up a "fix" in #2591, but I recommend that you remove any instances of `Teuchos_ENABLE_LONG_LONG_INT` from your configuration. If you want to prevent Tpetra from instantiating things with `long long`, @mhoemmen can describe how to do that, but the only reason to disable it in Teuchos was to support C++98.

**Comment by csiefer2** [comment]
Relevant PR aging gracefully in the bowels of the autotester.  Will close tomorrow if I fixed things.

**Comment by ibaned** [comment]
@csiefer2 are you not going to remove `Teuchos_ENABLE_LONG_LONG_INT=OFF` from the test configuration?

**Comment by ibaned** [comment]
Oh, my bad, I misinterpreted your earlier comment. I hope the autotester approves it soon.

**Comment by mhoemmen** [comment]
`Tpetra_INST_INT_LONG_LONG:BOOL=OFF` achieves the desired effect.  Tpetra will enable `GO=long` as well as `GO=int` in that case.

**Comment by ibaned** [comment]
I'm assuming this can be closed as both ways to fix it are in. Please comment otherwise
