### ISSUE TITLE
ninja and nvcc_wrapper

### ISSUE THREAD

**Issue by bathmatt** [trilinos/Trilinos#259]
This was emailed about but making a formal bug report.
@bartlettroscoe @crtrott 

If one configures trilinos to use ninja and build with cuda/nvcc_wrapper the compile fails with building dependencies.

Not sure where the issue is, 

/projects/install/rhel6-x86_64/sems/compiler/gcc/4.9.2/openmpi/1.10.1/bin/mpicxx    -I. -Ipackages/kokkos/core/src -I/home/mbetten/Trilinos/Trilinos/packages/kokkos/core/src -I/usr/local/cuda/include -std=c++11 -g -O0 -MMD -MT packages/kokkos/core/src/CMakeFiles/kokkoscore.dir/impl/Kokkos_Core.cpp.o -MF packages/kokkos/core/src/CMakeFiles/kokkoscore.dir/impl/Kokkos_Core.cpp.o.d -o packages/kokkos/core/src/CMakeFiles/kokkoscore.dir/impl/Kokkos_Core.cpp.o -c /home/mbetten/Trilinos/Trilinos/packages/kokkos/core/src/impl/Kokkos_Core.cpp
g++: error: packages/kokkos/core/src/CMakeFiles/kokkoscore.dir/impl/Kokkos_Core.cpp.o.d: No such file or directory
[66/4434] Building C object packages/zoltan/src/CMakeFiles/zoltan.dir/coloring/coloring.c.o

**Comment by crtrott** [comment]
Probably -MT is not handled correctly. Try add -MT to known shared arguments with an argument (i.e. the line which has -o).

**Comment by bathmatt** [comment]
That fixes it, Christian, can you add that to kokkos version of nvcc_wrapper?  I don't think I have push privileges.

**Comment by crtrott** [comment]
I committed it to Kokkos develop, and also pushed it as a standalone patch to Trilinos.
