### ISSUE TITLE
Epetra: adding IntMultiVector to mirror the IntVector object

### ISSUE THREAD

**Issue by lucbv** [trilinos/Trilinos#2590]
@trilinos/epetra 
@csiefer2 @mhoemmen 

## Expectations
Implementation of a `IntMultiVector` class that allows for the storage of multiple indices in the same object instead of using arrays of `IntVector` which is a more sketchy...

## Current Behavior
Currently such object does not exist and that leads to funny code with multiple `IntVectors` stored in Arrays or `std::vector`. Also this would use significantly less storage than the equivalent `MultiVector` in the case of `int` data

## Motivation and Context
The implementation of overlapping aggregates in MueLu requires to store multiple indices per node and it was done in the case of non-overlapping aggregates done with IntVector.

## Definition of Done
The implementation of an `IntMultiVector` class that mirrors the capabilities of the `IntVector` class.

## Possible Solution
see above

## Related Issues
* Blocks #2577

**Comment by mhoemmen** [comment]
@lucbv It's a good idea.  You could work around for now through an Epetra-specific Xpetra thing, but that wouldn't be much less work than just implementing this in Epetra.

No one has specified the compiler requirements for Epetra.  Epetra depends _optionally_ on Teuchos, and Teuchos requires C++11.  Adherence to Epetra style would call for avoiding C++ >= 11 constructs, but Trilinos' Dashboard doesn't test with earlier compilers, so I don't think you should have to either.

**Comment by lucbv** [comment]
#2603 is now merged and no more tests are failing on the dashboard so work is now completed!
