### ISSUE TITLE
Elevate all packages and SE packages used by ATDM APPs to Primary Tested

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#2597]
**CC:** @trilinos/framework, @fryeguy52 

**Blocked By:** #4219, #4272 

## Description:

Currently, it seems that some of the subpackages used by the ATDM EMPIRE APP are labeled Secondary Tested (ST).  Since ST is enabled by default with Trilinos in the EMPIRE Trilinos configuration, this makes sense that that would have happened.  However, by definition, anything being used by ATDM APPs should be treated as Primary Tested (see [here](http://trac.trilinos.org/wiki/TribitsLifecycleModelOverview#test_categories)).

Therefore, this story is to identify which Trilinos subpackages are really being used by ATDM that are currently categorized as ST and elevate them to PT.

**Comment by mhoemmen** [comment]
@micahahoward @prwolfe

**Comment by bartlettroscoe** [comment]
I am going to wait to work on this until after we get that ATDM Trilinos builds updated to support SPARC (see [TRIL-212](https://software-sandbox.sandia.gov/jira/browse/TRIL-212)).

**Comment by mhoemmen** [comment]
@bartlettroscoe getting stuff done :D

**Comment by bartlettroscoe** [comment]
FYI: First specific enable needed is given in #4219.
