### ISSUE TITLE
Set up "Specialized" ATDM CUDA build of Trilinos that enables RDC

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#2598]
**CC**:  @trilinos/kokkos, @trilinos/kokkos-kernels, @trilinos/shylu, @trilinos/framework 

## Description

The current ATDM CUDA builds of Trilinos do not set `Kokkos_ENABLE_Cuda_Relocatable_Device_Code=ON` (see discussion in #2464 and #2580).  However, this is needed for task-based algorithms like in ShyLU_NodeTacho and the ATDM codes may take advantage of this in the future (more likely in SPARC than EMPIRE it would seem).

Therefore, this story is to set up a new nightly build of some CUDA configuration of Trilinos that enables `Kokkos_ENABLE_Cuda_Relocatable_Device_Code=ON`  so that the Trilinos developers can work to get this build cleaned up and ready for the ATDM customers to use on the ATDM platforms.

Internal SNL conversations about this topic are in companion issue:

* https://sems-atlassian-son.sandia.gov/jira/browse/TRIL-262

ToDo: Define targeted platforms and base build configurations, etc. 

## Related Issues

* Related to: #2464, #2580

**Comment by bartlettroscoe** [comment]
@bathmatt, @michaahoward, @rppawlo 

FYI: I just talked with @crtrott about `Kokkos_ENABLE_Cuda_Relocatable_Device_Code=ON`.  The next update of Kokkos into Trilinos will include an updated `nvcc_wapper` that has a new option `--remove-duplicate-link-files` that is needed to get RDC to work.  In fact, Sierra/Aria is already using this updated Kokkos and `nvcc_wrapper` to use RDC with Aria.  They are in fact using virtual functions in C++ on the GPU!

@micahahoward, this means that if SPARC is ever going to take advantage of DRC then it will need to remove the circular dependencies between its libraries.  (But as the prototype SPARC TriBITS system did, there is currently zero downside to just creating on big SPARC library.)

@micahahoward and @bathmatt, if there is any urgency in turning on DRC for SPARC or EMPIRE, then we should get some "Specialized" ATDM CUDA 9.2 builds stood up that test this and then get the Trilinos developers to clean up the test suite.

**Comment by mhoemmen** [comment]
@bartlettroscoe SPARC is currently working on removing the circular dependencies between its libraries.

**Comment by micahahoward** [comment]
@bartlettroscoe What @mhoemmen said is true.  We're getting much closer and this is being driven by a desire to turn on RDC.  No ETA on when that will be but possibly before the end of the calendar year.

**Comment by bartlettroscoe** [comment]
@bathmatt and @rppawlo,

Judging from the conversation in:

* https://cee-gitlab.sandia.gov/EM-Plasma/EMPIRE-PIC/issues/79

does this mean that we need to start working on turning on RDC for CUDA?

**Comment by rppawlo** [comment]
yes - we will need it very soon. @bathmatt has a branch that requires RDC for empire. We've been using RDC in phalanx for the past year. This week I started working on cleaning up issues in higher level Trilinos packages. We will need the PR testing to exercise builds with RDC both enabled and disabled. I've found in some cases we need to ifdef special code for RDC (unless we want to force all of Trilinos to always require RDC which is probably not a good thing).

**Comment by mhoemmen** [comment]
Does one part of a code building with RDC on force all of the code to build with RDC on?

**Comment by rppawlo** [comment]
> Does one part of a code building with RDC on force all of the code to build with RDC on?

Do you mean for all TPLs or for separate packages in Trilinos? Right now, we have to configure and build all of Trilinos with RDC enabled. We have been linking to 11 TPLs that are not built with RDC and they all seem to work fine. It's possible we are just getting lucky though. @crtrott ?

**Comment by ibaned** [comment]
@mhoemmen the RDC-requiring object and all downstream uses of that object must be linked with NVIDIA's linker with RDC enabled. If you link to it, you need to also turn on RDC.

**Comment by ibaned** [comment]
Conversely, upstream things (like TPLs) don't even need to be built with nvcc, let alone RDC.

**Comment by mhoemmen** [comment]
Thanks @ibaned :-)  This looks a bit like the option enabling device lambdas, then.  It flows downstream unconditionally.

**Comment by bartlettroscoe** [comment]
FYI: There has been some recent discussion on enabling RDC for CUDA builds for ATDM.  See (and please comment in):

* https://sems-atlassian-son.sandia.gov/jira/browse/TRIL-262

**Comment by bartlettroscoe** [comment]
FYI: I will go ahead and set up some nightly "Specialized" ATDM Trilinos CUDA 9.2 RDC builds on 'white'/'ride' and 'waterman'.  If you want to get updates on this, add yourself as a watcher to  [TRIL-262](https://sems-atlassian-son.sandia.gov/jira/browse/TRIL-262).

**Comment by bartlettroscoe** [comment]
FYI: PR #4481 is up and ready to be approved.  This will allow us to set up some nightly builds with RDC enabled.  After those builds are up and running each day, we will post ATDM Trilinos GitHub issues to for the new failures.

@rppawlo, can you review and approve PR #4481?

**Comment by bartlettroscoe** [comment]
The branch PR #4481 merged earlier today and I just set up the Jenkins SON builds on 'white':

* https://jenkins-son.sandia.gov/view/Trilinos%20ATDM/job/Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-rdc-release-debug/
* https://jenkins-son.sandia.gov/view/Trilinos%20ATDM/job/Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-rdc-release-debug-pt/

and the following Jenkins SRN builds on 'ride' and 'waterman':

* https://jenkins-srn.sandia.gov/view/Trilinos%20ATDM/job/Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-rdc-release-debug/
* https://jenkins-srn.sandia.gov/view/Trilinos%20ATDM/job/Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-rdc-release-debug-pt/
* https://jenkins-srn.sandia.gov/view/Trilinos%20ATDM/job/Trilinos-atdm-waterman-cuda-9.2-rdc-release-debug/

These should run tomorrow and post to the CDash "Specialize" group.

Since this Issue was only to set up these builds, I will put in review to see that they show up correctly for a few days then close.

**Comment by bartlettroscoe** [comment]
FYI: Set up new CUDA RDC 'shared' lib builds after the merge of the PR #4523 and the new Jenkins builds:

* https://jenkins-srn.sandia.gov/view/Trilinos%20ATDM/job/Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-rdc-shared-release-debug/
* https://jenkins-srn.sandia.gov/view/Trilinos%20ATDM/job/Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-rdc-shared-release-debug-pt/
* https://jenkins-srn.sandia.gov/view/Trilinos%20ATDM/job/Trilinos-atdm-waterman-cuda-9.2-rdc-shared-release-debug/

These should run tomorrow 2/19/2019.

**Comment by bartlettroscoe** [comment]
FYI: As shown [here](https://testing.sandia.gov/cdash-dev-view/index.php?project=Trilinos&date=2019-03-01&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-&field2=buildname&compare2=63&value2=rdc) there are several CUDA RDC builds set up on several different machines.  There are static and shared CUDA RDC running on 'white', 'ride', and 'waterman'.  All of these shown build errors and the build errors are shown in difference packages.  We will triage these failures and set up new ATDM Trilinos GitHub issues for these.

This current story is just to set up these RDC builds which is now complete.

**Comment by bartlettroscoe** [comment]
@srajama1, where was the original GitHub Issue for RDC support that I added almost a year ago based on requests from the ATDM APP teams looking ahead to their future needs.

**Comment by srajama1** [comment]
The original issue was to setup a build, which was setup 18/17 days ago, and then Trilinos developers are actively helping clean up the build. It took an year to setup the build. Am I reading this right ?

**Comment by bartlettroscoe** [comment]
@srajama1 

>  It took an year to setup the build. Am I reading this right ?

Yes.  This was "it would be nice if ..." a year ago but was not stated as urgent (and there were higher priorities).  But more recently this has been stated as higher priority which is why we set these up builds.   My point with CCing you on this issue was to point out (as stated at several ATDM PI Meetings going back to at least April 2018) that the long-term desire was to turn on RDC for ATDM.  The matter of urgency and priority is another story.  (We sometimes create backlog items for things that have been requested that we don't plan to work right away so we can capture the initial request and keep a memory of it and flesh it out over time. That is not an unusual project management practice.)  Make sense?
