### ISSUE TITLE
MueLu: delete ShiftedLaplacian interface?

### ISSUE THREAD

**Issue by jhux2** [trilinos/Trilinos#2608]
Would anyone object if I delete the ShiftedLaplacian interface?  I know of no current users.  The interface isn't maintained, and takes well over 5 minutes to compile.

@trilinos/muelu

**Comment by cgcgcg** [comment]
Instead of outright deleting it, maybe just don't compile it by default? Or is it actually broken?

**Comment by jhux2** [comment]
> Instead of outright deleting it, maybe just don't compile it by default? Or is it actually broken?

It's not broken, as the Helmholtz tests exercise the interface, but it's badly in need of a redesign.  One option would be to guard it with an experimental flag.

**Comment by jhux2** [comment]
closing as fixed by PR #3047.
