### ISSUE TITLE
12.12 download points to oldsite

### ISSUE THREAD

**Issue by VictorEijkhout** [trilinos/Trilinos#2616]
A while ago I had no end of problems with trilinos because there was an "oldsite" which was fully functional except that it was 2 years out of date.

Now I notice that the 12.12.1 download points to the oldsite. Is this correct? Are you just trying to confuse me?

Victor.

**Comment by jmgate** [comment]
@trilinos/framework

**Comment by jhux2** [comment]
Closing in favor of #3900.
