### ISSUE TITLE
Ifpack+Belos wrong convergence

### ISSUE THREAD

**Issue by SG38** [trilinos/Trilinos#2618]
## Configuration
Trilinos 12.12.1
Modules: Ifpack, Belos, Epetra

## Description
Using Ifpack(IC, fillins=4) + Belos(PseudoBlockCG, tol=1.e-5) to solve A.x = b, where A is symmetric sparse and definite positive; b is a dense vector and the most important is that x is initialized with the Epetra_MultiVector Random() procedure. 

The Belos solving stops after 2 iterations saying that convergence is correct with an error < 1.e-5. 
However, checking the real error |A.x - b| / norm2(b) < 1.e-5  fails. Depending on the dimension of the problem, the real error can be very high.

@trilinos/Ifpack

## Question
Is it a bug or am I doing something wrong? What is the explanation? Note that MueLu + Belos gives a correct solution with X0=Rand[-1,1].

## Current Behavior
The internal residual value must reflect the error calculs. That is always true except when LHS is initialised by the Random() procedure of MultiVector.

**Comment by aprokop** [comment]
@SG38 Check $|Ax-b|/|Ax_0-b|$.

**Comment by aprokop** [comment]
@trilinos/belos

**Comment by SG38** [comment]
@aprokop Multiplying initial guess x0 by |A*x0-b| fixes the issue. I have checked that A*x-b < tol.
@mhoemmen The PseudoBlockCG is not sensitive to right and left preconditioning strategy.

I am looking for an initial guess that can reduce the iterations. This initial guess works fine with MueLu. Maybe somebody can advise me a way to set the initial guess LHS?

**Comment by hkthorn** [comment]
@SG38 I'm confused.  If modifying/scaling the initial guess fixes the issue, then the solver IS using the initial guess (LHS).  By default the pseudo block CG solver uses the initial residual as the scaling factor for determining convergence.  That is what @aprokop is speaking to above.  If you want something else, like the norm of the RHS or no scaling whatsoever, then you can set the "Implicit Residual Scaling" parameter in the parameter list that you use to create the pseudo block CG solver.  The suggested options are:

"Norm of Initial Residual" [default]
"Norm of RHS"
"None"

Maybe changing the residual scaling to "Norm of RHS" will give a converged solution that conforms to your expectations of the solver to the given tolerance, regardless of the preconditioner.

**Comment by SG38** [comment]
@hkthorn Thank you. "Norm of RHS" is better when using LHS0 = MultiVector::Random
