### ISSUE TITLE
NOX tests timing out in ATDM configuration RHEL6 builds

### ISSUE THREAD

**Issue by fryeguy52** [trilinos/Trilinos#2628]
@trilinos/nox 

## Description
There are 4 NOX tests that are failing due to timeout in the ATDM configuration when building on RHEL6 with the sems environment.  They have been failing in this way since 4/18/18. The test are:

NOX_LOCA_BrusselatorHopf_MPI_2
NOX_LOCA_BrussXYZT_BlockDiagonal_MPI_2
NOX_LOCA_TcubedTP_MPI_2
NOX_LOCA_TcubedTP_stratimikos_MPI_2

3 others are failing due to timeout intermittently, about every other day:
NOX_LOCA_BrussXYZT_Sequential_MPI_2
NOX_LOCA_BrussXYZT_SequentialOPS_MPI_2
NOX_LOCA_BrussXYZT_SequentialIPS_MPI_2

All of these timeout failures are using the sems environment it is most common on gnu builds but does happen with intel builds as well.  All of them are using openmp.
## Steps to Reproduce

- go to a rhel6 machine that has the sems environment.  (CEE machines have sems modules mounted)
- clone Trilinos and then run the following:

```
$ cd <some_build_dir>/

$ source $TRILINOS_DIR/cmake/std/atdm/load-env.sh gnu-opt-openmp

$ cmake \
  -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
  -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_NOX=ON \
  $TRILINOS_DIR

$ make -j16

$ ctest -j16 
```

## Possibly helpful CDASH links:
[GNU opt openmp build failures](https://testing-vm.sandia.gov/cdash/queryTests.php?project=Trilinos&date=2018-04-24&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=4&showfilters=1&filtercombine=and&field1=buildname&compare1=63&value1=-atdm-rhel6-gnu-opt-openmp&field2=testname&compare2=63&value2=NOX_LOCA_&field3=buildstarttime&compare3=84&value3=now&field4=status&compare4=63&value4=Failed)

**Comment by bartlettroscoe** [comment]
The following queries provide some more information:

* https://testing-vm.sandia.gov/cdash/queryTests.php?project=Trilinos&date=2018-04-24&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=6&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm&field2=testname&compare2=63&value2=NOX_LOCA_&field3=buildstarttime&compare3=84&value3=2018-04-25&field4=status&compare4=63&value4=Failed&field5=buildname&compare5=62&value5=Trilinos-atdm-white-ride-gnu-opt-openmp&field6=buildname&compare6=62&value6=Trilinos-atdm-white-ride-cuda-opt

* https://testing-vm.sandia.gov/cdash/queryTests.php?project=Trilinos&date=2018-04-24&filtercombine=and&&filtercount=1&showfilters=1&field1=testname&compare1=61&value1=NOX_LOCA_BrusselatorHopf_MPI_2

* https://testing-vm.sandia.gov/cdash/queryTests.php?project=Trilinos&date=2018-04-24&filtercombine=and&&filtercount=1&showfilters=1&field1=testname&compare1=61&value1=NOX_LOCA_BrussXYZT_BlockDiagonal_MPI_2

* https://testing-vm.sandia.gov/cdash/queryTests.php?project=Trilinos&date=2018-04-24&filtercombine=and&&filtercount=1&showfilters=1&field1=testname&compare1=61&value1=NOX_LOCA_BrussXYZT_Sequential_MPI_2

* https://testing-vm.sandia.gov/cdash/queryTests.php?project=Trilinos&date=2018-04-24&filtercombine=and&&filtercount=1&showfilters=1&field1=testname&compare1=61&value1=NOX_LOCA_BrussXYZT_SequentialIPS_MPI_2

* https://testing-vm.sandia.gov/cdash/queryTests.php?project=Trilinos&date=2018-04-24&filtercombine=and&&filtercount=1&showfilters=1&field1=testname&compare1=61&value1=NOX_LOCA_TcubedTP_MPI_2

* https://testing-vm.sandia.gov/cdash/queryTests.php?project=Trilinos&date=2018-04-24&filtercombine=and&&filtercount=1&showfilters=1&field1=testname&compare1=61&value1=NOX_LOCA_TcubedTP_stratimikos_MPI_2

@fryeguy52,

What do the totality of those queries seem to indicate?  What trends to you see?

**Comment by fryeguy52** [comment]
The specific builds that seem to be effected are:
- Trilinos-atdm-rhel6-gnu-debug-openmp
- Trilinos-atdm-rhel6-gnu-opt-openmp
- Trilinos-atdm-white-ride-cuda-debug-all-at-once 

After looking more closely, a few more observations:
- it seems that this test usually runs in less than 1 minute on other builds but for these builds even when it passes it takes 9+ minutes to complete
- any NOX_LOCA tests that are timing out in our configuration are using openmp
- these are not showing up on either shiller/hansen or white ride builds

**Comment by etphipp** [comment]
These tests all use Epetra (and not Tpetra).  Two questions:

1. Is Epetra actually configured to use OpenMP?
2. If so, are the threads being bound properly so that the machine is not being oversubscribed (where each MPI rank is trying to use all of the threads on the machine)?

**Comment by bartlettroscoe** [comment]
@fryeguy52,

If you look at the three failures on `Trilinos-atdm-white-ride-cuda-debug-all-at-once`, they are failures, not timeouts, and they are all on the same day and build at 2018-04-12T06:40:45.   Two of those tests showed the error:

```
--------------------------------------------------------------------------
While computing bindings, we found no available cpus on
the following node:

  Node:  ride7

Please check your allocation.
--------------------------------------------------------------------------
```

The other test was a setgfault late into running the test:

```
================================================================
Anasazi Eigensolver starting with block size 1


       Condition number estimate of preconditioner is 1.431e+02
[ride14:28030] *** Process received signal ***
[ride14:28030] Signal: Segmentation fault (11)
[ride14:28030] Signal code: Address not mapped (1)
[ride14:28030] Failing at address: 0x10038a00020
[ride14:28030] [ 0] [0x100000050478]
[ride14:28030] [ 1] [0x3ff0000000000000]
[ride14:28030] *** End of error message ***
--------------------------------------------------------------------------
mpiexec noticed that process rank 0 with PID 28030 on node ride14 exited on signal 11 (Segmentation fault).
--------------------------------------------------------------------------
```

These same failures did **not** occur for the identical build on 'white' that day.

Given all of this, I think the failures on 'ride' for the build `Trilinos-atdm-white-ride-cuda-debug-all-at-once` are a problem with that node on 'ride' where these ran.

**Comment by bartlettroscoe** [comment]
@trilinos/nox,

Should we disable Epetra support in NOX for ATDM?  Do the ATDM APPs need Epetra support in NOX?  Should we set `NOX_ENABLE_Epetra=OFF`?

**Comment by etphipp** [comment]
They can use Epetra and NOX, so I wouldn’t do that quite yet.

**Comment by wfspotz** [comment]
I am implementing the NOX solvers in ATDM, and I have been developing them to support Epetra and Tpetra

**Comment by rppawlo** [comment]
I don't think we can actually disable epetra in panzer. That will take some work.

**Comment by bartlettroscoe** [comment]
> There is an Epetra CMake option to disable use of OpenMP.

It does not look like Epetra has a way to disable OpenMP just for Epetra as shown at:

* https://github.com/trilinos/Trilinos/blob/a0d5f35011ce97bb3d9a6ccf3f22c0c8dba00676/packages/epetra/src/CMakeLists.txt#L13

It is just hard-coded to use `${PROJECT_NAME}_ENABLE_OpenMP`.

We could add a proper `Epetra_ENABLE_OpenMP` option to allow us to turn off OpenMP for Epetra.  Should we do that?

**Comment by fryeguy52** [comment]
I rebuilt the same version as yesterday and ran the tests on `ceerws1113` (rhel6 cee machine) with `ATDM_CONFIG_CTEST_PARALLEL_LEVEL=4`.  The same tests timed out as yesterday. This is what I did:
```
source $TRILINOS_DIR/cmake/std/atdm/load-env.sh gnu-opt-openmp 
cmake -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_NOX=ON $TRILINOS_DIR
```

test result summary:
```
95% tests passed, 5 tests failed out of 105

Label Time Summary:
NOX    = 7156.33 sec (105 tests)

Total Test time (real) = 1047.22 sec

The following tests FAILED:
	 71 - NOX_LOCA_TcubedTP_MPI_2 (Timeout)
	 72 - NOX_LOCA_TcubedTP_stratimikos_MPI_2 (Timeout)
	 77 - NOX_LOCA_BrusselatorHopf_MPI_2 (Timeout)
	 80 - NOX_LOCA_BrussXYZT_Sequential_MPI_2 (Timeout)
	 84 - NOX_LOCA_BrussXYZT_BlockDiagonal_MPI_2 (Timeout)
Errors while running CTest
```

**Comment by bartlettroscoe** [comment]
@fryeguy52, what happens when you run just:

```
$ ctest -R NOX_LOCA_TcubedTP_stratimikos_MPI_2 
```

for example?  Does that one test run all by itself timeout?  What about the other tests?

**Comment by fryeguy52** [comment]
run individually they all pass:

```
1/1 Test #72: NOX_LOCA_TcubedTP_stratimikos_MPI_2 ...   Passed    6.40 sec

1/1 Test #71: NOX_LOCA_TcubedTP_MPI_2 ..........   Passed    4.15 sec

1/1 Test #77: NOX_LOCA_BrusselatorHopf_MPI_2 ...   Passed    1.04 sec

1/1 Test #80: NOX_LOCA_BrussXYZT_Sequential_MPI_2 ...   Passed    1.12 sec

1/1 Test #84: NOX_LOCA_BrussXYZT_BlockDiagonal_MPI_2 ...   Passed    4.83 sec
```
if I just run `ctest` with no -j then everything passes:
```
100% tests passed, 0 tests failed out of 105

Label Time Summary:
NOX    =  72.56 sec (105 tests)
```

with `ctest -j4`:

```
Test  #84: NOX_LOCA_BrussXYZT_BlockDiagonal_MPI_2 ......................***Timeout 600.06 sec
```

**Comment by mhoemmen** [comment]
@bartlettroscoe wrote:
> We could add a proper Epetra_ENABLE_OpenMP option to allow us to turn off OpenMP for Epetra. Should we do that?

It's worth trying, at least to see if that fixes the tests.

**Comment by bartlettroscoe** [comment]
> if I just run ctest with no -j then everything passes
> ...
> running all tests with ctest -j4:
> [timeouts]

Wow, that is unfortunate.  Even with all other thread bounds to the same core, I don't see how a test that takes 4.8s to complete can timeout at 10 minutes!  

Let's try disabling OpenMP in Epetra and see what happens.

@fryeguy52, I will create a branch of Trilinos that disables OpenMP for our ATDM builds and then point you to it to test.

**Comment by bartlettroscoe** [comment]
> A simple solution is to not have mpirun bound the MPI ranks to cores by adding the configure option:

@etphipp,  Thanks!  That did the trick for me too.  The PR #2638 applies this fix and I verified that it fixed the NOX tests.    Can you go ahead and approve the PR?

Is this an initial solution to the OpenMP binding problem described in #2422, to allow us to enable OpenMP in an auto PR build?

**Comment by etphipp** [comment]
Great!  I approved the PR.

> Is this an initial solution to the OpenMP binding problem described in #2422, to allow us to enable OpenMP in an auto PR build?

I suppose its an initial solution, but I don't see it being an ideal one.  Ideally ctest would correctly bind MPI ranks to separate cores when launching multiple tests simultaneously, and respect the number of threads each test is using.

**Comment by bartlettroscoe** [comment]
After the merge of PR #2638, there are no more timeouts at all in these ATDM Trilinos RHEL6 builds.  for example, you can see all the newly passing tests for the build `Trilinos-atdm-rhel6-gnu-debug-openmp` today at:

* https://testing-vm.sandia.gov/cdash/index.php?project=Trilinos&parentid=3464120

See the `+7' superscript on top of the `105` passing tests for NOX?

Now there is just one failing Teko test and then all of these builds can be promoted to the "ATDM" CDash Track/Group.

Closing this issue as complete!
