### ISSUE TITLE
Tpetra: Deprecate & remove get*NumDiags & is{Lower,Upper}Triangular

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#2630]
@trilinos/tpetra 

Deprecate and remove the following functions from RowGraph, RowMatrix, CrsGraph, and CrsMatrix:
  - `isLowerTriangular`
  - `isUpperTriangular`
  - `getGlobalNumDiags` 
  - `getNodeNumDiags`

## Progress

We've finished deprecating the functions.  We have work-arounds in Ifpack2 and Tpetra, for getting the functionality without triggering the deprecation warnings.  We've also wrapped the deprecated functions in `#ifdef TPETRA_ENABLE_DEPRECATED_CODE ... #endif`.  The only thing remaining is to remove the deprecated functions.  This must wait until the next Trilinos major release.

## Motivation and Context

The first call of `CrsGraph::fillComplete` for a given graph instance, invokes `CrsGraph::computeLocalConstants`.  In order to compute what `getNodeNumDiags`, `getGlobalNumDiags`, and `is{Lower,Upper}Triangular()` need, `computeLocalConstants` must read all the entries in the matrix.  This takes significant time, as @alanw0 reported in #2565.  It's only rarely that downstream code needs to know this information.

Tpetra developers deem `nodeMaxNumRowEntries_` necessary for ML/MueLu "getrow" implementations, to preallocate buffers.  Tpetra developers are not sure if `getGlobalMaxNumRowEntries` is actually necessary.

## Related Issues
* Related to #2565

**Comment by csiefer2** [comment]
Claiming MueLu/Xpetra

**Comment by csiefer2** [comment]
I have Xpetra & MueLu purged on my machine and the tests all work  

@kddevin Can you take care of this one (and push separately)?  

zoltan2/test/unit/models/GraphModel.cpp

**Comment by kddevin** [comment]
@csiefer2 Zoltan2 is done.  See PR #2634 waiting for your review.

**Comment by csiefer2** [comment]
#2635 awaiting review & merge

**Comment by mhoemmen** [comment]
@kddevin I jumped the gun a bit and merged #2634 for you :)

**Comment by mhoemmen** [comment]
@csiefer2 I reviewed & approved #2635; looks good!

**Comment by mhoemmen** [comment]
@csiefer2 I'm weirdly not able to push the merge button on #2635 despite it having been tested.

**Comment by mhoemmen** [comment]
@csiefer2 Never mind, there's just a delay after the review until the system sees it.  I just merged #2635; thanks! :D

**Comment by mhoemmen** [comment]
I'm purging these function calls (not the functions themselves) from Tpetra.

**Comment by mhoemmen** [comment]
PR #2644 starts this process in Tpetra.

**Comment by mhoemmen** [comment]
I'm not quite ready for a new PR, but here's what I've done thus far:

  - Add Tpetra::Details::determineLocalTriangularStructure, a thread-parallel version of what computeLocalConstants does
  - Ifpack2::LocalSparseTriangularSolver: Forbid "reverse U" & HTS (see #2647)
  - Ifpack2::LocalSparseTriangularSolver: Don't call `get{Node,Global}NumDiags` or `is{Lower,Upper}Triangular`
  - Ifpack2::LocalSparseTriangularSolve: Don't call `CrsMatrix::localSolve` (part of #581)
  - Use the new `Tpetra::Details::determineLocalTriangularStructure` function in `Tpetra::CrsGraph::computeLocalTriangularProperties`

Next step is to fix #2565 by adding an option to CrsGraph and CrsMatrix fillComplete, to bypass computing `nodeNumDiags_` and `is{Lower,Upper}Triangular`.  `Crs{Graph,Matrix}::expertStaticFillComplete` already has a "compute global constants" option to skip computing global constants; this would be a "compute local constants" option.

@csiefer2 @jhux2 Would it make sense to add the "compute global constants" option to regular fillComplete, not just expertStaticFillComplete?  I think so but just wanted to ask.

**Comment by csiefer2** [comment]
@mhoemmen No objection here, so long as it is on by default.

**Comment by tjfulle** [comment]
@mhoemmen , can the call to `[getGlobalNumDiags](https://github.com/trilinos/Trilinos/blob/develop/packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp#L6026)` in `CrsMatrix::describe` be lifted?  It flooded the Albany dashboard with warnings.  Also, the call to [`getNodeNumDiags`](https://github.com/trilinos/Trilinos/blob/develop/packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp#L727) added to the deluge.

**Comment by mhoemmen** [comment]
@tjfulle Yes, please feel free to work on that if you have time.  If not, no worries :D .  I was in meetings all yesterday afternoon.

**Comment by tjfulle** [comment]
@mhoemmen, OK.  The warnings all seem to pop up when Amesos2 is enabled.  The warnings emanating from `CrsMatrix::describe` are easy enough to silence, just remove the call to `getGlobalNumDiags`.  A recursive grep of `packages/src/amesos2` for `getNodeNumDiags` turns up nothing, so it must be being called indirectly and I haven't found out from where (yet).

**Comment by mhoemmen** [comment]
@tjfulle wrote:
> A recursive grep of packages/src/amesos2 for getNodeNumDiags turns up nothing, so it must be being called indirectly and I haven't found out from where (yet).

We will have a lot of those warnings for a while.  We discussed some ways to remove some of them yesterday, but we won't be able to avoid others.

**Comment by mhoemmen** [comment]
Progress:
  - @tjfulle added PR #2667 to remove `getGlobalNumDiags` call from `CrsMatrix::describe`
  - It passed PR testing & @mhoemmen merged it

**Comment by mhoemmen** [comment]
Progress: I added PR #2696 to fix #2565 and work on #581.  As part of the latter, the PR adds a Tpetra function (`Tpetra::Details::determineLocalTriangularProperties`) that computes the same information that `getNodeNumDiags`, `isLowerTriangular`, and `isUpperTriangular` provide.  This will make it easier for Trilinos code to remove calls to the deprecated methods.

**Comment by mhoemmen** [comment]
Merged PR #2696 today.

**Comment by ibaned** [comment]
Albany builds have several warnings about these functions still being called, and because of bugs in the CDash system, those warnings are obscuring some other build errors that we have. Is there a plan to get all of these calls out of Trilinos?

**Comment by mhoemmen** [comment]
@ibaned Yes.  I spent some effort masking them in Tpetra.  I think we'll need to do the same in downstream packages that call deprecated methods (those are usually subclasses of `Tpetra::RowMatrix`).  For Ifpack2's RowMatrix subclasses, I think we can safely remove the deprecated methods.  Not sure about other downstream packages.

**Comment by ibaned** [comment]
Thanks, that makes sense

**Comment by mhoemmen** [comment]
@trilinos/tpetra Progress: PR #2873.

**Comment by mhoemmen** [comment]
@trilinos/tpetra @trilinos/ifpack2 Progress: I just merged PR #2873 into develop:

  - Ifpack2 is now free of calls to deprecated Row{Graph,Matrix} methods is{Lower,Upper}Triangular and get{Node,Global}NumDiags
  - Ifpack2's subclasses of Row{Graph,Matrix} are now syntactically forbidden from overriding the deprecated methods
  - For Ifpack2's subclasses of Row{Graph,Matrix}, any calls to the deprecated methods now throw `std::logic_error`
