### ISSUE TITLE
'No such file: klu2_simple.h' during installation testing

### ISSUE THREAD

**Issue by bavier** [trilinos/Trilinos#264]
Doing installation testing via `Trilinos_INSTALLATION_DIR` for several packages leads to errors during `make` about a missing `klu2_simple.h`.  For example:
```
cmake \
    -DCMAKE_VERBOSE_MAKEFILE:BOOL=NO \
    -DTrilinos_INSTALLATION_DIR=/ptmp/trilinos-install \
    -DTrilinos_ENABLE_Ifpack2:BOOL=YES \
    -DTrilinos_ENABLE_TESTS:BOOL=YES \
    -DTrilinos_ENABLE_OpenMP:BOOL=YES \
    /ptmp/Trilinos
```
This seems to be because there is an executable `klu2_simple` declared in Amesos2 that is not installed, and cmake attempts to build it during installation testing, but the needed klu2_simple.h header is not installed.

Declaring `klu2_simple` as an example, which seems appropriate, fixes the issue.  See the attached patch.

[0001-Amesos2-Build-klu2_simple-as-an-example.txt](https://github.com/trilinos/Trilinos/files/202983/0001-Amesos2-Build-klu2_simple-as-an-example.txt)

**Comment by jwillenbring** [comment]
@trilinos/amesos2 should be CC'ed on this.

**Comment by srajama1** [comment]
Thanks for the patch. We'll push it. Josh, can you take care of this ?

**Comment by jdbooth** [comment]
Yes, I on it.

**Comment by jdbooth** [comment]
Have tested and pushed the patch, commit: 13c8824e4173dcc9336f933f12425dbeec868192
Seems to be working fine.

**Comment by bavier** [comment]
Commit 13c8824e4173dcc9336f933f12425dbeec868192 does not include the creation of the "examples" directory that was in the attached patch.  This might break configuration for others pulling that commit.

**Comment by jdbooth** [comment]
A patch was applied to fix this 15 minutes after the first push.
