### ISSUE TITLE
MueLu: should MMKernelDriver.cpp use KokkosKernel's interface to MKL?

### ISSUE THREAD

**Issue by jhux2** [trilinos/Trilinos#2641]
KokkosKernels provides an interface to MKL.  Would it make sense for the MMKernelDriver test to use that, rather than direct calls to MKL?

@csiefer2 @srajama1

**Comment by csiefer2** [comment]
The point of this exercise was to not have to bludgeon to KokkosKernels build system until we could get ViennaCL to work correctly.

Moreover, the point of this test is to provide a way to bake Tpetra kernels off against KK ones.  Which cannot, by definition, happen in KokkosKernels.

**Comment by srajama1** [comment]
Kokkoskernels has an interface to ViennaCL for testing purposes. We didn't see a reason to expose it to users from our experiments. I am not sure why you needed that interface. The MKL interface in Kokkoskernels is for long term.

Long term, I also don't like the idea of different packages in Trilinos calling MKL (or any TPL) directly. This causes lot of TPL versioning issues. We are committed to maintaining MKL TPL interface for BLAS and sparse use cases. 

There needs to be a notional owner package for every TPL. AmgX -> MueLU, direct solvers -> Amesos2, graph algorithms -> Zoltan2. This just allows us to keep some sanity w.r.t TPLs.

**Comment by csiefer2** [comment]
FYI, this is Experimental-guarded testing code for our own testing purposes.

**Comment by srajama1** [comment]
Understood. As long as it is guarded w/ custom experimental guards and not Trilinos level TPL guards they should be fine. I don't want to enable MKL at Trilinos level (say for ATDM apps) and run into a versioning issue. 

Wearing the Kokkos Kernels hat, I wish you used it, filed issues on it  etc :) (take off that hat).

**Comment by jhux2** [comment]
Question answered, closing.
