### ISSUE TITLE
Ifpack2::LocalSparseTriangularSolver: "trisolver: reverse U" option is untested; remove or test

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#2647]
@trilinos/ifpack2 @trilinos/tpetra @kddevin @csiefer2 @jhux2 @kyungjoo-kim @ambrad 

As part of the urgent Tpetra task #2630, I will need to change some code in `Ifpack2::LocalSparseTriangularSolver`.  I noticed that this class has a "trisolver: reverse U" option.  However, that option is completely untested anywhere in Trilinos.  I'm not convinced that it would work unless using the HTS solver option, but the option does not test whether HTS is enabled.  Furthermore, I don't think HTS is tested by default in Ifpack2.

We need to do exactly one of the following:

  1. Prove by adding a test to Ifpack2, that "trisolver: reverse U" works whether or not HTS is enabled.
  2. Confirm that "trisolver: reverse U" only works if HTS is enabled, and add a test for this option in that case.
  3. Remove the option from `Ifpack2::LocalSparseTriangularSolver`.

I would be happy to do (3).  There's no judgment in removing code that people don't have time to maintain.  We can always go back later and optimize sparse triangular solves.  I just really need to know whether this is dead code.

**Comment by jhux2** [comment]
I think @aprokop added this feature for the Exawind project.

**Comment by ambrad** [comment]
@mhoemmen, I believe @aprokop can tell you about the reverse-U option. Tbc, it's orthogonal to HTS and was put in LSTS for another project after HTS; in fact, if HTS is used, there's no point in reversing U. Within LSTS, HTS is managed through a few lines of code that call the HtsImpl wrapper.

**Comment by ambrad** [comment]
Sure, makes sense.

**Comment by mhoemmen** [comment]
PR #2696 adds a run-time check for the forbidden case mentioned above.
