### ISSUE TITLE
Make GNU ATDM Trilinos builds use 'gold' as the linker

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#2686]
**CC:** @bathmatt, @fryeguy52 

## Description 

The EMPIRE configuration just recently switched to using `gold` as the default linker for GNU builds (see https://gitlab.sandia.gov/EM-Plasma/BuildScripts/issues/31).  To do this with recent GCC versions, one just needs to pass in the linker option `-fuse-ld=gold`.

This story is to make that ATDM Trilinos GNU configurations use `gold` as the linker by adding this option.

**Comment by bartlettroscoe** [comment]
@bathmatt, what machines do you want this on?  What machine did you notice this on that triggered the creation of duplicate #3533?

**Comment by bathmatt** [comment]
We use it everywhere but the IBMs.  TLCC CEE shiller, ...

**Comment by bartlettroscoe** [comment]
@bathmatt,

I can't seem to find any commits in EM-Plasma/BuildScripts repo that set the gold linker.  I pulled the updated version of the repo (last modified 8/2/2018) and there is no hits on:

```
$  git log -Sgold
```

or

```
$ git log --grep="gold"
```

How is the EMPIRE build of Trilinos setting up to use the gold linker?
