### ISSUE TITLE
Get Trilinos building with CMake + Ninja + Fortran

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#269]
This story is to get all of Trilinos building with CMake + Ninja with Fortran turned on.  There is a branch of Ninja and CMake that supports projects with Fortran code.  This story will track efforts to get Trilinos and CMake + Ninja + Fortran working.

CC: @nmhamster. @bathmatt

**Comment by bartlettroscoe** [comment]
This story is already in progress.  Currently there is a problem with Ninja rebuilding every Fortran file after every minor reconfigure.  Details will be forthcoming.

**Comment by bradking** [comment]
So far we've found that `ninja -d explain` shows many lines like:

    ninja explain: output packages/epetra/src/CMakeFiles/epetra.dir/Epetra_dcrsmm.f-pp.f older than most recent input /home/mbetten/Trilinos/builds/build_for_panzer/gcc/debug (1459543581 vs 1459543674)

This looks like a dependency on a directory instead of a file.  We need to figure out why that dependency appears.

**Comment by bartlettroscoe** [comment]
I think this is a CUDA build. Is that right @bathmatt?

**Comment by bartlettroscoe** [comment]
I have replacing this story with the larger epic/milestone "Get Trilinos building with CMake + Ninja + Fortran".
