### ISSUE TITLE
Ifpack2: Add nonsymmetric equilibration option

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#2695]
Requested by Fuego.  Fuego needs to solve turbulent kinetic equations.  They look like advection-diffusion problems with badly scaled source terms.  Reports are that symmetric Gauss-Seidel NaNs out and Jacobi works better.  This makes sense if the off-diagonal terms are large.  The equations normally don't take many iterations to solve, but are either taking a long time or NaN-ing out.

Here are some options:

  1. Set a lower bound on diagonal entry magnitude
  2. Reorder the equations
  3. Nonsymmetric equilibration
  4. Try an ILU variant (best combined with (2))

For (1), first set "relaxation: fix tiny diagonal entries" to true, then set "relaxation: min diagonal value" to some appropriate small positive but nonzero value.  This may not help if the issue is large off-diagonal entries.

For (2), Ifpack2::Relaxation (implements Jacobi and (symmetric) Gauss-Seidel) already has a "relaxation: local smoothing indices" option for accepting a precomputed reordering.  It requires a user-supplied reordering via `Teuchos::ArrayRCP<int>` (actually `Teuchos::ArrayRCP<LO>`).  If you want Ifpack2 to compute a reordering for you, currently you need to use Ifpack2::Relaxation as the subdomain solver for Ifpack2::AdditiveSchwarz, and set AdditiveSchwarz's "schwarz: use reordering" parameter to true.

For (3), it would be more efficient for the application to do equilibration as a pre- and post-solve step.  Ifpack2 does not currently implement this feature.  This would be useful to implement, so I'm posting the feature request here, along with context.

For (4), Ifpack2 implements both ILU(k) and ILUT.  This is best combined with reordering (see (2)).

@trilinos/ifpack2

**Comment by jhux2** [comment]
@mhoemmen Are these M matrices?

**Comment by mhoemmen** [comment]
@jhux2 Probably not.  They don't know.

They have the option to force symmetry with respect to boundary conditions, but otherwise they aren't even symmetric.  They _are_ using GMRES with these preconditioners, though.

**Comment by mhoemmen** [comment]
@jhux2 These matrices show up as part of a segregated solve.  They solve x, y, z momentum equations first (separately), then a Poisson equation, then this equation.

**Comment by mhoemmen** [comment]
Equilibration doesn't properly belong in Ifpack2; it's a preprocessing and postprocessing step for the entire linear solve.  PR #2840 (merged) adds row and column one-norm computation and left and right scaling to Tpetra::CrsMatrix.  PR #2820 (merged) adds an Ifpack2 example that demonstrates equilibration in a complete Belos + Ifpack2 linear solve.  The two PRs fix this issue.
