### ISSUE TITLE
Panzer: CurlLaplacianExample-ConvTest randomly failing

### ISSUE THREAD

**Issue by rppawlo** [trilinos/Trilinos#271]
On my workstation, this test occasionally fails. Probably a race condition on the output check.

**Comment by rppawlo** [comment]
adding @eric-c-cyr

**Comment by rppawlo** [comment]
Looks like it's a race condition in the parsing of output.  Below is the test output:

opening "MPE-ConvTest-05"
Test Failed:
invalid literal for float(): 0.00970975ALL PASSED: EpetraALL PASSED: Epetra

--------------------------------------------------------------------------------

**Comment by rppawlo** [comment]
We can't rely on screen output for checking test convergence when multiple MPI processes are writing at the same time.   We need to change this to write to a file and have the convergence tester read that file. Since Panzer will be changed from ST to PT in Trilinos soon this needs to be fixed soon.

@eric-c-cyr @jmgate

**Comment by jmgate** [comment]
Oh good, I was seeing this test randomly fail too but could never reproduce the error when I tried so I thought I was just losing my mind :)

Forgive my ignorance, but what are ST and PT?

@trilinos/panzer

**Comment by mhoemmen** [comment]
@rppawlo wrote:
> We can't rely on screen output for checking test convergence when multiple MPI processes are writing at the same time. We need to change this to write to a file and have the convergence tester read that file.

You may find Tpetra::Details::gathervPrint handy.  It lives in tpetra/core/src/Tpetra_Details_gathervPrint.hpp.  It takes a string on each MPI process in a communicator, and outputs the result of each in turn (deterministically) to an output stream only valid on Process 0 in the communicator.  It's also memory scalable :-D

**Comment by mhoemmen** [comment]
@jmgate wrote:
> Forgive my ignorance, but what are ST and PT?

PT ("primary tested") is a label for packages that Trilinos builds and tests by default.  They may not depend on any TPLs other than MPI (optionally), the BLAS, and LAPACK.  In the check-in test script, only PT packages get enabled, _even if_ you changed something in a non-PT package.

ST ("secondary tested") is a label for packages that require TPLs other than MPI, the BLAS, or LAPACK, but which Trilinos nevertheless wants to test regularly.  If you want to test ST packages in the check-in test script, you must use --st-extra-builds or --extra-builds to identify those packages explicitly.

**Comment by jmgate** [comment]
Thanks @mhoemmen.  @rppawlo, when is the planned transition from ST to PT for Panzer?

**Comment by rppawlo** [comment]
not sure of the exact timeline. it is being tracked in #410 @bartlettroscoe has commented on it the past few days so it is being actively worked. @bartlettroscoe - do you know when you will be changing the PT code?

**Comment by rppawlo** [comment]
Also - in #410, PT is being expanded to include more TPLs than just MPI, BLAS and LAPACK.

**Comment by bartlettroscoe** [comment]
I just need to test on a few platforms and then it is ready to push.  I will ask for review before first.  I will send out an email.

**Comment by rppawlo** [comment]
Should be fixed now. Moving to "In Review". Will watch the test over the next few days to see if issues clear up.
