### ISSUE TITLE
Improvement with teampolicy in Ifpack2 BlockTridiContainer (block line smoother)

### ISSUE THREAD

**Issue by kyungjoo-kim** [trilinos/Trilinos#2714]
Ifpack2 block tridi container developed using kokkos kernels with SIMD type, which provides good performance on knl, by @ambrad. A new version using a team policy is developed to improve performance on GPUs. This issue is to track the development progress. 

@srajama1 @mhoemmen @ndellingwood @micahahoward  

## Expectations

Improved performance than previous version.

## Current Behavior

The master branch code works for all architectures using kokkos range policy; however, the code is not necessary to be performant on GPUs. In my trilinos fork, the team policy version is added. 

## Motivation and Context

On GPUs, important thing is to find and add more fine-grained parallelism. Using hierarchical parallelism within tiny block computations, it can gain additional performance.   

## Your Environment

Using the following git repositories and commit ids, you can (probably) compile unit test ``Ifpack2_BlockTriDiContainerUnitAndPerfTests.exe``.

On white, it is tested with ``module load devpack/openmpi/1.10.4/gcc/5.4.0/cuda/8.0.44``
On bowman, I use intel 18.
```
module load devpack/openmpi/1.10.4/intel/17.0.098
module swap intel/compilers/17.0.098 intel/compilers/18.2.199
```

Commit ids.

```
Trilinos
=====
[kyukim @white11] src > git remote -v
origin	ssh://git@github.com/kyungjoo-kim/Trilinos.git (fetch)
origin	ssh://git@github.com/kyungjoo-kim/Trilinos.git (push)
upstream	ssh://git@github.com/trilinos/Trilinos.git (fetch)
upstream	ssh://git@github.com/trilinos/Trilinos.git (push)

[kyukim @white11] src > git branch
* line-gpu
  master

[kyukim @white11] src > git log 
      1 commit 206c5206a3400a34b121e633dd2f9999b3a86d07
      2 Merge: 546403b f3daf35
      3 Author: Kyungjoo Kim <kyukim@sandia.gov>
      4 Date:   Wed May 9 22:43:08 2018 -0600
      5 
      6     Merge remote-tracking branch 'upstream/develop' into line-gpu
      7     
      8     Conflicts:
      9             packages/ifpack2/src/Ifpack2_BlockTriDiContainer_def.hpp
     10 
     11 commit 546403bdbc78578d9442b3e2d265a34b41cf8b49
     12 Author: Kyungjoo Kim <kyukim@sandia.gov>
     13 Date:   Wed May 9 22:34:24 2018 -0600
     14 
     15     Ifpack2 - fix cuda multi node case (pass ctest)
     16     
     17       md range policy on cuda does not work

KokkosKernels
===========
[kyukim @white11] master > git branch 
  develop
* fix-simd-with-cuda
  master

[kyukim @white11] master > git log 
      1 commit 58f17be721d37c509c80e878f8a88c1b08814376
      2 Author: Kyungjoo Kim <kyukim@apollo.sandia.gov>
      3 Date:   Wed May 9 10:33:48 2018 -0600
      4 
      5     KokkosBatched - pass spot check

Kokkos
=====

[kyukim @white11] master > git branch 
* develop
  master
[kyukim @white11] master > git log 
      1 commit d5e6eaf1bad6c41b33a1786db32c1bb025887ae4
      2 Merge: 55806d3 17d4107
      3 Author: Christian Trott <crtrott@sandia.gov>
      4 Date:   Fri May 4 18:52:37 2018 -0700
      5 
      6     Merge pull request #1608 from kokkos/later-cuda-fix1
      7     
      8     Fix the first part of #1607
```

**Comment by kyungjoo-kim** [comment]
Passed the unit test on apollo. I probably need to prepare for this PR after @micahahoward reproduced the same thing on waterman.  

@crtrott when do we plan to promote kokkos and kokkoskernels ? 

```
[kyukim @apollo] unit_tests > ctest
Test project /home/kyukim/Work/lib/trilinos/build/apollo/ifpack-kyukim-release/packages/ifpack2/test/unit_tests
      Start  1: Ifpack2_unit_tests_MPI_4
 1/14 Test  #1: Ifpack2_unit_tests_MPI_4 ............................   Passed  101.08 sec
      Start  2: Ifpack2_AdditiveSchwarz_MPI_4
 2/14 Test  #2: Ifpack2_AdditiveSchwarz_MPI_4 .......................   Passed   54.90 sec
      Start  3: Ifpack2_RBILUK_MPI_4
 3/14 Test  #3: Ifpack2_RBILUK_MPI_4 ................................   Passed   17.68 sec
      Start  4: Ifpack2_ChebyshevConvergence_MPI_4
 4/14 Test  #4: Ifpack2_ChebyshevConvergence_MPI_4 ..................   Passed  183.91 sec
      Start  5: Ifpack2_AdditiveSchwarzBug5963_MPI_2
 5/14 Test  #5: Ifpack2_AdditiveSchwarzBug5963_MPI_2 ................   Passed    2.77 sec
      Start  6: Ifpack2_RILUKSingleProcessUnitTests_MPI_1
 6/14 Test  #6: Ifpack2_RILUKSingleProcessUnitTests_MPI_1 ...........   Passed   11.63 sec
      Start  7: Ifpack2_BlockTriDiContainerUnitAndPerfTests_MPI_4
 7/14 Test  #7: Ifpack2_BlockTriDiContainerUnitAndPerfTests_MPI_4 ...   Passed  1343.68 sec
      Start  8: Ifpack2_SolverFactory_MPI_1
 8/14 Test  #8: Ifpack2_SolverFactory_MPI_1 .........................   Passed    2.25 sec
      Start  9: Ifpack2_LocalSparseTriangularSolver_MPI_4
 9/14 Test  #9: Ifpack2_LocalSparseTriangularSolver_MPI_4 ...........   Passed  397.59 sec
      Start 10: Ifpack2_LocalSparseTriangularSolver2_MPI_4
10/14 Test #10: Ifpack2_LocalSparseTriangularSolver2_MPI_4 ..........   Passed   14.08 sec
      Start 11: Ifpack2_ContainerFactory_MPI_1
11/14 Test #11: Ifpack2_ContainerFactory_MPI_1 ......................   Passed    1.49 sec
      Start 12: Ifpack2_Issue234_MPI_1
12/14 Test #12: Ifpack2_Issue234_MPI_1 ..............................   Passed    1.38 sec
      Start 13: Ifpack2_Issue762_MPI_1
13/14 Test #13: Ifpack2_Issue762_MPI_1 ..............................   Passed    2.15 sec
      Start 14: Ifpack2_SGSMT_compare_with_Jacobi_MPI_4
14/14 Test #14: Ifpack2_SGSMT_compare_with_Jacobi_MPI_4 .............   Passed   13.69 sec

100% tests passed, 0 tests failed out of 14

Label Time Summary:
Ifpack2    = 2148.28 sec (14 tests)

Total Test time (real) = 2148.31 sec
```

**Comment by micahahoward** [comment]
@kyungjoo-kim, I'll start testing your changes ASAP.

**Comment by kyungjoo-kim** [comment]
@micahahoward I already fixed the ambiguous name "Vector" with "KokkosBatched::Experimental::Vector". This should compiles with sparc as it is.

**Comment by micahahoward** [comment]
@kyungjoo-kim, below is the results from ifpack2 unit testing on Waterman.  The bad news is that the solver is still incorrect in my app code :(

```
waterman1 $ ctest
Test project <redacted>/packages/ifpack2/test/unit_tests
      Start  1: Ifpack2_unit_tests_MPI_4
 1/15 Test  #1: Ifpack2_unit_tests_MPI_4 ............................   Passed   41.13 sec
      Start  2: Ifpack2_AdditiveSchwarz_MPI_4
 2/15 Test  #2: Ifpack2_AdditiveSchwarz_MPI_4 .......................   Passed   12.71 sec
      Start  3: Ifpack2_RBILUK_MPI_4
 3/15 Test  #3: Ifpack2_RBILUK_MPI_4 ................................   Passed    5.75 sec
      Start  4: Ifpack2_ChebyshevConvergence_MPI_4
 4/15 Test  #4: Ifpack2_ChebyshevConvergence_MPI_4 ..................   Passed   12.91 sec
      Start  5: Ifpack2_AdditiveSchwarzBug5963_MPI_2
 5/15 Test  #5: Ifpack2_AdditiveSchwarzBug5963_MPI_2 ................   Passed    2.20 sec
      Start  6: Ifpack2_RILUKSingleProcessUnitTests_MPI_1
 6/15 Test  #6: Ifpack2_RILUKSingleProcessUnitTests_MPI_1 ...........   Passed    3.71 sec
      Start  7: Ifpack2_BlockTriDiContainerUnitAndPerfTests_MPI_4
 7/15 Test  #7: Ifpack2_BlockTriDiContainerUnitAndPerfTests_MPI_4 ...   Passed  624.29 sec
      Start  8: Ifpack2_BlockRelaxationPerformance_MPI_1
 8/15 Test  #8: Ifpack2_BlockRelaxationPerformance_MPI_1 ............   Passed    8.31 sec
      Start  9: Ifpack2_SolverFactory_MPI_1
 9/15 Test  #9: Ifpack2_SolverFactory_MPI_1 .........................   Passed    1.57 sec
      Start 10: Ifpack2_LocalSparseTriangularSolver_MPI_4
10/15 Test #10: Ifpack2_LocalSparseTriangularSolver_MPI_4 ...........   Passed  368.47 sec
      Start 11: Ifpack2_LocalSparseTriangularSolver2_MPI_4
11/15 Test #11: Ifpack2_LocalSparseTriangularSolver2_MPI_4 ..........   Passed   28.44 sec
      Start 12: Ifpack2_ContainerFactory_MPI_1
12/15 Test #12: Ifpack2_ContainerFactory_MPI_1 ......................   Passed    1.34 sec
      Start 13: Ifpack2_Issue234_MPI_1
13/15 Test #13: Ifpack2_Issue234_MPI_1 ..............................   Passed    1.18 sec
      Start 14: Ifpack2_Issue762_MPI_1
14/15 Test #14: Ifpack2_Issue762_MPI_1 ..............................   Passed    1.30 sec
      Start 15: Ifpack2_SGSMT_compare_with_Jacobi_MPI_4
15/15 Test #15: Ifpack2_SGSMT_compare_with_Jacobi_MPI_4 .............   Passed    6.73 sec

100% tests passed, 0 tests failed out of 15

Label Time Summary:
Ifpack2    = 1120.05 sec (15 tests)

Total Test time (real) = 1120.11 sec
```

**Comment by kyungjoo-kim** [comment]
@micahahoward This is a good news that at least we are on the same page now. Do you mean that some sparc unit tests fail or in general it does not converge to the solution at all ? Are in the same situation on KNL (ifpack2 test passes but the sparc does not converge) ?

**Comment by micahahoward** [comment]
@kyungjoo-kim When I run my app code test on KNL with the BlockTriDi solver, the test passes.  When I run my test on Waterman with the Belos/Ifpack2 solver, the test passes.  But when I run my test on Waterman with the BlockTriDi solver the test does not pass.

I'll find you this afternoon so we can discuss.

**Comment by micahahoward** [comment]
@kyungjoo-kim I'll be in after 1pm.

I spoke too soon on KNL.  I need to test your branches on KNL.  I was speaking about what's in Trilinos/master passing on KNL.

**Comment by srajama1** [comment]
This has exposed a disconnect between the Ifpack2 tests and the app.

**Comment by ambrad** [comment]
It's possible that it's an arithmetic ordering issue is leading to diffs w.r.t. app gold files. However, I see that there is at least one detail to which the Trilinos unit tests are not sufficiently sensitive: the particular diagonal padding that the app uses.

On lines 1754-1770, linked here:
https://github.com/trilinos/Trilinos/blob/f3daf35d420017383a27c747ee4f0af36cd0670a/packages/ifpack2/src/Ifpack2_BlockTriDiContainer_def.hpp#L1754
one sees two versions of this padding. In the first version, the diag is padded before the LU factorization. In the second version, `Serial_LU_Internal_Unblocked_invoke` is called, which adds padding as necessary as the factorization proceeds. The two are mathematically different. The app does the second.

I see that the Ifpack2 unit test does not check for this app-specific padding. It is activated by calling
```c++
    BlockTriDiContainer<MatrixType, LocalScalarType>::compute (const ComputeParameters& in)
```
with `in.addRadiallyToDiagonal > 0`. You could test that directly by comparing `Serial_LU_Internal_Unblocked_invoke`'s output with > 0 padding with the new impl's output. You might even keep `Serial_LU_Internal_Unblocked_invoke` around to test that this specific padding approach is never removed, particularly if it resolves the app test failures.

However, again, it is worth pointing out that a generic change in order of ops tends to lead to gold-file diffs in apps.

**Comment by micahahoward** [comment]
@ambrad - the problem in the app code was pretty catastrophic, not just small diffs.

HOWEVER, good news: @kyungjoo-kim's change in kokkos-kernels today appears to have fixed this - a getting a clean diff now.  Still need to do some more testing with this but I think the problem has been fixed!

**Comment by kyungjoo-kim** [comment]
It is good news. Finally, it is done. All we need to do is to prepare for PR. Have good night ~

**Comment by mhoemmen** [comment]
@kyungjoo-kim @micahahoward @ambrad Awesome! :D

**Comment by kyungjoo-kim** [comment]
this PR should go after kokkos promotion; kokkos/kokkos#1620
