### ISSUE TITLE
Sacado: Remove calls to deprecated Kokkos::View methods

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#2717]
Kokkos will soon deprecate the following Kokkos::View methods:
  1. `ptr_on_device()`: replace with `data()`
  2. `dimension(N)` (for N = 0, 1, 2, ..., 7): replace with `extent(N)`
  3. `dimension_N()` (for N = 0, 1, 2, ..., 7): replace with `extent(N)`
  4. `is_contiguous()`: replace with `span_is_contiguous()`
  5. `capacity()`: replace with `span()`

Sierra is already seeing build errors with its Trilinos integration build, since Sierra doesn't define `KOKKOS_ENABLE_DEPRECATED_CODE`.  If that macro is not defined, code that uses the above methods will not build.

I tried straightforwardly replacing `ptr_on_device` with `data` and `dimension_N` with `extent(N)`, but got build errors like this:
```
.../Trilinos/packages/sacado/src/KokkosExp_View_Fad.hpp:1073:19: error: ‘Kokkos::Impl::ViewMapping<Kokkos::ViewTraits<Sacado::Fad::SFad<Sacado::Fad::SFad<double, 3>, 5>**, Kokkos::LayoutLeft, Kokkos::OpenMP>, void>::offset_type’ has no member named ‘extent’
       ( Rank == 0 ? m_offset.extent(0) :
```
The `m_offset` instance field is a `ViewMapping` specialization.  I'm curious if `Kokkos::View`'s internals have since moved on from an implementation detail, upon which the Sacado specialization of `Kokkos::View` depends.

@trilinos/sacado @micahahoward @rrdrake @prwolfe @etphipp

**Comment by etphipp** [comment]
> The m_offset instance field is a ViewMapping specialization. I'm curious if Kokkos::View's internals have since moved on from an implementation detail, upon which the Sacado specialization of Kokkos::View depends.

No, the issue is that while Kokkos::View uses extent, Kokkos::ViewOffset still uses dimension, so you can't do a simple search-and-replace.

**Comment by mhoemmen** [comment]
@etphipp so how do we do it then? :)

**Comment by etphipp** [comment]
What I meant was you can't replace every instance of dimension with extent.  

I will take care of this.

**Comment by etphipp** [comment]
Does Kokkos (in Trilinos) even itself compile with deprecated code disabled?  I disabled it in my Trilinos config and get a build error in Kokkos:
```
/home/etphipp/Trilinos/Trilinos/packages/kokkos/core/src/impl/Kokkos_Core.cpp: In function ‘void Kokkos::Impl::{anonymous}::initialize_internal(const Kokkos::InitArguments&)’:
/home/etphipp/Trilinos/Trilinos/packages/kokkos/core/src/impl/Kokkos_Core.cpp:100:54: error: no matching function for call to ‘Kokkos::OpenMP::initialize(const int&, const int&)’
       Kokkos::OpenMP::initialize(num_threads,use_numa);
                                                      ^
/home/etphipp/Trilinos/Trilinos/packages/kokkos/core/src/impl/Kokkos_Core.cpp:100:54: note: candidate is:
In file included from /home/etphipp/Trilinos/Trilinos/packages/kokkos/core/src/Kokkos_Core.hpp:57:0,
                 from /home/etphipp/Trilinos/Trilinos/packages/kokkos/core/src/impl/Kokkos_Core.cpp:44:
/home/etphipp/Trilinos/Trilinos/packages/kokkos/core/src/Kokkos_OpenMP.hpp:120:15: note: static void Kokkos::OpenMP::initialize(int)
   static void initialize( int thread_count = -1 );
               ^
/home/etphipp/Trilinos/Trilinos/packages/kokkos/core/src/Kokkos_OpenMP.hpp:120:15: note:   candidate expects 1 argument, 2 provided
```
It looks to me that the version of Kokkos::OpenMP::initialize() that is being called in Kokkos_Core.cpp is deprecated.

How did you get to even building Sacado with this disabled to see where the errors are?

**Comment by mhoemmen** [comment]
@etphipp I didn't actually try disabling it -- I just started systematically removing use of the deprecated functions.

I remember that Kokkos has deprecated the individual execution space initialize functions.

**Comment by etphipp** [comment]
So I guess all I can do at this point is grep around in the code and hope I get them all.

**Comment by etphipp** [comment]
Can this be closed now?

**Comment by mhoemmen** [comment]
Thanks @etphipp !  Yes, I'll close it.  See #2735 for discussion of Kokkos promotion issues.
