### ISSUE TITLE
Intrepid: Remove calls to deprecated Kokkos::View methods

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#2719]
Kokkos will soon deprecate the following `Kokkos::View` methods:
  1. `ptr_on_device()`: replace with `data()`
  2. `dimension(N)` (for N = 0, 1, 2, ..., 7): replace with `extent(N)`
  3. `dimension_N()` (for N = 0, 1, 2, ..., 7): replace with `extent(N)`
  4. `is_contiguous()`: replace with `span_is_contiguous()`
  5. `capacity()`: replace with `span()`

Sierra is already seeing build errors with its Trilinos integration build, since Sierra doesn't define `KOKKOS_ENABLE_DEPRECATED_CODE`.  If that macro is not defined, code that uses the above methods will not build.

@trilinos/intrepid @trilinos/intrepid2 @prwolfe @rrdrake

**Comment by mperego** [comment]
Thanks @mhoemmen, I'll look into that.

**Comment by ndellingwood** [comment]
@mperego @kyungjoo-kim Also the `View`'s and `DynRankView`'s that use more args than the rank with indexing will need to have the use of `operator(args...)` i.e. `v(i,...);` replaced by `access(args...)` i.e. `v.access(i,...)`. The `access` functions still need to be added to Sacado so this should not be done yet in Intreprid2, but will be needed for the kokkos promotion after the upcoming promotion (roughly sometime in mid-late to June I think), which is when decprecated code should be disabled by default. I'm out of town the next few days but will help when back. 
Thanks @mhoemmen for helping with changes and notification!

**Comment by mhoemmen** [comment]
No problem y'all :D

**Comment by mperego** [comment]
I started working on the Kokkos promotion branch and fixed the issues pointed out by @mhoemmen .
I haven't fixed that the issue with "access" as per @ndellingwood comment.

**Comment by ndellingwood** [comment]
@mperego I checked with Eric, we shouldn't have to add `access` methods to Sacado since the API multi-index call will go through the Kokkos View's operator or access methods and route to the operator's in Sacado's ViewMapping specialization as appropriate.

**Comment by ndellingwood** [comment]
@mperego I made the first round of adding `access` method use to Views that may take different number of args than the rank. This mostly affected various Basis files and some others in the Shared directory. I only had one compile failure prior to the changes, so it's possible some of these codes are tested more fully by other packages like Panzer. I'll build with other packages using Intrepid2 to see what I missed.

**Comment by mperego** [comment]
@ndellingwood Thanks for working on that! I tried to build all Intrepid2 forward dependency packages, but I get many errors from Seacas and Shylu. Should we wait until those packages will be fixed?

**Comment by mperego** [comment]
@ndellingwood @mhoemmen I think Intrepid2 is fine now. Closing the issue.

**Comment by mhoemmen** [comment]
Thanks @mperego ! :D
