### ISSUE TITLE
Panzer unsafe macro definitions

### ISSUE THREAD

**Issue by rppawlo** [trilinos/Trilinos#272]
The STK adapters use some unsafe macros such as HAVE_IOSS, HAVE_TEKO, HAVE_MUELU for optional package support. These need to be protected with package specific macros: PANZER_HAVE_TEKO. This is a hold over form naming convetions from the autotools days...

**Comment by rppawlo** [comment]
adding @eric-c-cyr

**Comment by eric-c-cyr** [comment]
This is some sed work.

**Comment by eric-c-cyr** [comment]
I'm closing this as the rhel6 CI tests passed. Let me know if more is needed.
