### ISSUE TITLE
Seacas: Remove calls to deprecated Kokkos::View methods

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#2720]
Tracking issue filed in Seacas repository: https://github.com/gsjaardema/seacas/issues/106

@trilinos/seacas @micahahoward @prwolfe @rrdrake

**Comment by gsjaardema** [comment]
This should now be fixed.

**Comment by mhoemmen** [comment]
btw, is `KOKKOS_ENABLE_DEPRECATED_CODE` still defined in your Seacas build?  If not, then you've verified the fix and I'll close this issue :D Thanks!

**Comment by gsjaardema** [comment]
There are no instances of `KOKKOS_ENABLE_DEPRECATED_CODE` existing in SEACAS code.
