### ISSUE TITLE
Teko header Teko_DiagonalPreconditionerFactory.hpp missing include

### ISSUE THREAD

**Issue by bavier** [trilinos/Trilinos#273]
Using `#include <Teko_DiagonalPreconditionerFactory.hpp>` with an installed Trilinos, e.g. when building Teko tests via installation testing, leads to the following error:
```
[  9%] Building CXX object packages/teko/tests/CMakeFiles/Teko_DiagonalPreconditionerFactory.dir/unit_tests/tDiagonalPreconditionerFactory.cpp.o
In file included from /ptmp/Trilinos/packages/teko/tests/unit_tests/tDiagonalPreconditionerFactory.cpp:67:0:
/ptmp/trilinos-install/lib/cmake/Teko/../../../include/trilinos/Teko_DiagonalPreconditionerFactory.hpp:53:41: fatal error: Tpetra/Teko_TpetraHelpers.hpp: No such file or directory
 #include "Tpetra/Teko_TpetraHelpers.hpp"
                                         ^
compilation terminated.
```

I would suggest the following patch, since the declarations in Teko_TpetraHelpers.hpp are not needed in Teko_DiagonalPreconditionerFactory.hpp:
```
--- a/packages/teko/src/Teko_DiagonalPreconditionerFactory.hpp
+++ b/packages/teko/src/Teko_DiagonalPreconditionerFactory.hpp
@@ -50,7 +50,6 @@
 // Teko includes
 #include "Teko_PreconditionerState.hpp"
 #include "Teko_PreconditionerFactory.hpp"
-#include "Tpetra/Teko_TpetraHelpers.hpp"
 
 class EpetraExt_PointToBlockDiagPermute; 
 
```

**Comment by bavier** [comment]
A related issue is the use of the `Tpetra/` prefix on the `Teko_TpetraHelpers.hpp` include in `packages/teko/tests/src/Tpetra/tTpetraOperatorWrapper.cpp`, `packages/teko/tests/src/tBlockJacobiPreconditionerFactory_tpetra.cpp`, and `packages/teko/tests/src/tDiagonalPreconditionerFactory_tpetra.cpp`.  Building these tests in installation testing mode leads to similar "No such file or directory" errors.  Removing the `Tpetra/` prefix is enough to fix it.

**Comment by jwillenbring** [comment]
CC: @trilinos/teko
