### ISSUE TITLE
Epetra: Epetra_IntMultiVectorDistributed_test failing in nightly clean build

### ISSUE THREAD

**Issue by william76** [trilinos/Trilinos#2743]
@trilinos/epetra 

The test [Epetra_IntMultiVectorDistributed](https://testing-vm.sandia.gov/cdash/testDetails.php?test=46495883&build=3509186) is failing on nightly Clean testing.

### Test output
```
Epetra in Trilinos 12.13 (Dev)

Processor 0 of 1 is alive.
Non zero error code 1, file: /scratch/trilinos/workspace/trilinos-folder/Trilinos_generic_nightly@2/SERIAL_Release_gcc_4.9.3__DEV/Trilinos/packages/epetra/test/IntMultiVectorDistributed/cxx_main.cpp, line: 168
Non zero error code 1, file: /scratch/trilinos/workspace/trilinos-folder/Trilinos_generic_nightly@2/SERIAL_Release_gcc_4.9.3__DEV/Trilinos/packages/epetra/test/IntMultiVectorDistributed/cxx_main.cpp, line: 170
Non zero error code 1, file: /scratch/trilinos/workspace/trilinos-folder/Trilinos_generic_nightly@2/SERIAL_Release_gcc_4.9.3__DEV/Trilinos/packages/epetra/test/IntMultiVectorDistributed/cxx_main.cpp, line: 172
```

@lucbv had the most recent commit to [epetra/test/IntMultiVectorDistributed/cxx_main.cpp](https://github.com/trilinos/Trilinos/blob/develop/packages/epetra/test/IntMultiVectorDistributed/cxx_main.cpp).

**Comment by lucbv** [comment]
@william76 I replicated the issue on my local machine and this one should be an easy fix: this test should simply not run in serial due to the nature of the test: checking for `MyPID() == 2` and such just plainly won't work with `comm serial`.
I added you as reviewer on PR #2745 which should fix this.

**Comment by lucbv** [comment]
@william76 the dashboard is now clean, I'm closing this. Thanks for pointing it out to me!
