### ISSUE TITLE
Teuchos: Add .data() method to Array*, for std::vector and Kokkos::View compatibility

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#2749]
`std::vector` and `Kokkos::View` both have a `.data()` instance method, that returns a raw pointer to the object's data.  Teuchos memory management classes have a `.getRawPtr()` method that returns the same thing.  It would be nice if `Teuchos::Array`, `Teuchos::ArrayRCP`, and `Teuchos::ArrayView` also had a `.data()` method.  That would make them compile-time interchangeable with a lot of code that uses `std::vector`.

@trilinos/teuchos

**Comment by bartlettroscoe** [comment]
Sounds good to me.  We just need to add some unit tests.  It would not take much.  You basically have `::data()` call `::getRawPtr()` and then add a few unit tests for each class for the major use cases (is null, is non-null, etc.).

**Comment by mhoemmen** [comment]
@bartlettroscoe Thanks!  Yup, that's the idea.
