### ISSUE TITLE
Panzer: Use subviews for Intrepid2 calls

### ISSUE THREAD

**Issue by rppawlo** [trilinos/Trilinos#275]
The last workset is usually not full so we need to change the call to use a subview. This will avoid having to disable the debug inf check in Intrepid. When all panzer code calling intrepid is changed over to subviews, then we can close this ticket by reactivating the debug inf check in Intrepid2.

**Comment by mperego** [comment]
@rppawlo is this issue still relevant?

**Comment by rppawlo** [comment]
@mperego - we can close this.
