### ISSUE TITLE
Teuchos: TimeMonitor::mergeCounterNames() requires sorted lists

### ISSUE THREAD

**Issue by rppawlo** [trilinos/Trilinos#2757]
The current implementation of mergeCounterNames requires that localNames and globalNames Arrays be sorted (a requirement due to internally using std::set_union and std::set_intersection). For the StackedTimer, the ordering is important information and we would like to preserve that ordering. Could the mergeCounterNames be modified to take a "bool arraysAreSorted" flag and if they are not sorted, fall back on a brute force merge? Without this, we are seeing some timer labels repeated in the Stacked Timer levels when running with multiple MPI processes.

@mhoemmen - I think this is your code. Is this something you could do? Can send a P/T if necessary.

@trilinos/teuchos 
@bathmatt

**Comment by mhoemmen** [comment]
@rppawlo I'm not a fan of the brute-force merge for a huge number of timers, like what we see in MueLu.  Could we instead keep the pairwise communication pattern, but use an ordered merge?  It would kinda still be brute force per process but not globally.

**Comment by rppawlo** [comment]
If I understand you correctly, I think that is what we were intending. Wanted to keep the current process in place but just extend for non-sorted vectors. So really just pass the bool for isSorted down into mergeCounterNamesPair and instead of calling stl algorithms, do the merge preserving the order there. Is this what you mean?

**Comment by bathmatt** [comment]
Roger saying bruit force means, not using std::function but for i=0..n do blank I think.

**Comment by rppawlo** [comment]
yes - what @bathmatt said.

**Comment by mhoemmen** [comment]
@rppawlo wrote:
> So really just pass the bool for isSorted down into mergeCounterNamesPair and instead of calling stl algorithms, do the merge preserving the order there. Is this what you mean?

Yes :-)

**Comment by mhoemmen** [comment]
We could even preserve 2N log (2N) (for N the max number of timers on any one process) per pair, by keeping an integer permutation array.  Not sure if worth it, though.

**Comment by mhoemmen** [comment]
I would be happy to help but I've got a lot of stuff on my plate right now.  I don't think this is very hard, esp. now that y'all are looking at this code for StackedTimer.  If you have trouble, though, I can help out.

**Comment by bathmatt** [comment]
Fixing in new branch, of coarse there is no testing for the existing code, only going to test the new function I'm writing.  

ir-teuchos (gcc) 368 $ find . -name \*pp -exec grep -l mergeCounter {} \; |grep test
dir-teuchos (gcc) 369 $
