### ISSUE TITLE
Ifpack2: Document FastILU (and friends) and make options more Ifpack2-like

### ISSUE THREAD

**Issue by csiefer2** [trilinos/Trilinos#2765]
This issue is to serve as a reminder to help make the Ifpack2 interface to FastILU/FastIC/FastILDL smell more like full-fledged members of Ifpack2.

@jhux2

**Comment by csiefer2** [comment]
This also needs to include adding Teuchos timers...

**Comment by mhoemmen** [comment]
Do those have their own triangular solves or would they just defer to LocalSparseTriangularSolver?

**Comment by csiefer2** [comment]
They call ShyLU

**Comment by brian-kelley** [comment]
@csiefer2 added Teuchos timers in May. The Ifpack2 files have doxygen annotations and the user's guide has brief descriptions of the parameters.

Should I improve the names of the options, e.g. change "sweeps" to "FastILU/ILDL/IC: sweeps"? Add more detail to user's guide? Does the code need improvements to conform to the Preconditioner interface?
