### ISSUE TITLE
Teuchos: StackedTimer shadow declaration warning

### ISSUE THREAD

**Issue by csiefer2** [trilinos/Trilinos#2776]
Trilinos/packages/teuchos/comm/src/Teuchos_StackedTimer.hpp: In constructor ‘Teuchos::StackedTimer::LevelTimer::LevelTimer(int, const char*, Teuchos::StackedTimer::LevelTimer*, bool)’:
Trilinos/packages/teuchos/comm/src/Teuchos_StackedTimer.hpp:192:26: warning: declaration of ‘start’ shadows a member of 'this' [-Wshadow]

**Comment by bathmatt** [comment]
fixed and part of already running PR

**Comment by csiefer2** [comment]
Awesome sauce.
