### ISSUE TITLE
Replace existing GCC 4.8.4 auto PR serial Kokkos build with updated GCC 4.8.4 + OpenMPI 1.10.1 + OpenMP configuration

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#2788]
CC: @trilinos/framework 

## Description

This story is to solicit a review of the GCC 4.8.4 + OpenMPI 1.10.1 + OpenMP build which is currently submitting to CDash shown at:

* https://testing-vm.sandia.gov/cdash/index.php?project=Trilinos&date=2018-05-20&filtercombine=and&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=GCC-4.8.4-OpenMPI-1.10.1-MpiReleaseDebugSharedPtOpenMP&field2=buildstarttime&compare2=84&value2=now

merged in PRs #2694 and #2851 and then to consider swapping out the existing GCC 4.8.4 auto PR build with this build.

This build 100% matches the agreed-upon GCC 4.8.4 PR build described in #2317 and #2462 .  And this build also uses ninja as well, and therefore adds that testing to PR testing (and greatly speeds up the build).  This would be a PR build that tests Trilinos with OpenMP enabled and an updated version of OpenMPI compared to the existing auto PR builds.

The key files to review and be used in the auto PR tester are:

* [GCC-4.8.4-OpenMPI-1.10.1-MpiReleaseDebugSharedPtOpenMP_env.sh](https://github.com/trilinos/Trilinos/blob/develop/cmake/std/GCC-4.8.4-OpenMPI-1.10.1-MpiReleaseDebugSharedPtOpenMP_env.sh): Just source this to load env
* [GCC-4.8.4-OpenMPI-1.10.1-MpiReleaseDebugSharedPtOpenMP.cmake](https://github.com/trilinos/Trilinos/blob/develop/cmake/std/GCC-4.8.4-OpenMPI-1.10.1-MpiReleaseDebugSharedPtOpenMP.cmake): Just include this in the CMake configure `-C <base-path>` and enable any packages you want

Hopefully the auto PR testing infrastructure will allow these two files to be plugged in pretty easily.

The other files that are also of some interest (but don't need to be used in auto PR testing) are:

* [ctest_std_driver.cmake](https://github.com/trilinos/Trilinos/blob/develop/cmake/ctest/drivers/sems_ci/ctest_std_driver.cmake): Generic ctest -S driver for any build using this model
* [ctest_std_driver.sh](https://github.com/trilinos/Trilinos/blob/develop/cmake/ctest/drivers/sems_ci/ctest_std_driver.sh):  Generic bash/Jenkins driver for any build using this model
* [ctest_GCC-4.8.4-OpenMPI-1.10.1-MpiReleaseDebugSharedPtOpenMP.sh](https://github.com/trilinos/Trilinos/blob/develop/cmake/ctest/drivers/sems_ci/ctest_GCC-4.8.4-OpenMPI-1.10.1-MpiReleaseDebugSharedPtOpenMP.sh): Specific Jenkins driver

These files shows how easy it is to set up a system based on `<build_name>` with a env script `<build_name>_env.sh` and set of CMake settings `<build_name>.cmake` and then drive everything from local builds to ctest -S/Jenkins drivers.  Hopefully the auto PR system can be set up this way to make it easy to add new auto PR builds and also make it easy for developer to reproduce these builds.

**Comment by bartlettroscoe** [comment]
@trilinos/kokkos, @bathmatt, @micahahoward,

This would give some stronger testing for threaded features in Trilinos auto PR testing and satisfies the requirements for the GCC 4.8.4 build described in #2317.

**Comment by prwolfe** [comment]
The changes merged in #2943 did not include changing the openmpi version and so failed in production.  I'm sorry that my testing did not catch this (and the PR testing won't due to the bootstrapping issue.) I have disabled that in Jenkins for the moment while Jim and I evaluate if we should change just this PR or all of them and if the OpenMP options could be changed to allow 1.6.5 testing (I prefer not.)

**Comment by bartlettroscoe** [comment]
> I evaluate if we should change just this PR or all of them and if the OpenMP options could be changed to allow 1.6.5 testing (I prefer not

My experimentation is that you just can't do OpenMP testing with OpenMPI 1.6.5 or 1.8.7.  You can only use OpenMPI 1.10.1. But just enable OpenMP for now with the  GCC 4.8.4 build with OpenMPI 1.10.1 because it is 100% working as shown at:

* https://testing-vm.sandia.gov/cdash/index.php?project=Trilinos&parentid=3632672&filtercount=4&showfilters=1&field1=groupname&compare1=61&value1=Continuous&field2=buildstarttime&compare2=84&value2=now&field3=buildstarttime&compare3=83&value3=4%20weeks%20ago&filtercombine=and

**Comment by mhoemmen** [comment]
OpenMPI 1.6.5 is way too old.  OpenMPI doesn't even support 1.10.x any more -- the oldest version they support is 2.1.

**Comment by bartlettroscoe** [comment]
The Trilinos Framework team duplicated these settings in their own `*.cmake` configuration files.  Therefore, closing this.
