### ISSUE TITLE
Epetra requires C++11 now; update documentation

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#2795]
I merged the following pull request that fixes GLIBCXX debug checking for deal.II's tests:

https://github.com/trilinos/Trilinos/pull/2783

This pull request introduces a modest C++11 requirement into Epetra.  Please see discussion there for rationale.  In particular, no one could come up with a current use case demanding that Epetra be built with a C++98 compiler.  Even the Epetra-only MueLu build for Windows requires Teuchos, which in turn requires C++11.  More importantly, we have no idea if Epetra builds with a C++98 compiler, since we have not tested this use case for a long time.

@trilinos/epetra @trilinos/framework @trilinos/muelu @maherou @trilinos/tpetra 

If y'all have a problem with that, now might be a good time to say something.  Otherwise, I hereby declare that Epetra now requires C++11.  Next step is to update Epetra's documentation to make this clear.

**Comment by csiefer2** [comment]
However, if your aggressive C++11-isms break the VisualStudio tests, your commits will be reverted.

**Comment by mhoemmen** [comment]
@csiefer2 cool, no problem :) the issue is not new std::vector methods but SFINAE etc.

**Comment by mhoemmen** [comment]
@hkthorn is this OK?

**Comment by csiefer2** [comment]
See this for what you (notionally) can and cannot do:
https://msdn.microsoft.com/en-us/library/hh567368.aspx

**Comment by hkthorn** [comment]
@mhoemmen Thanks for asking!  Xyce has frozen our compatible version of Trilinos to 12.12.  After that release, we did not strongly suggest that the Trilinos packages we use be C++98 compliant.  We are awaiting the support of C++11 compliant compilers on COE platforms before we update our Trilinos version.  That's long-winded, but we will not be impacted by Epetra requiring C++11.

**Comment by mhoemmen** [comment]
Thanks @hkthorn for the quick update! :D
