### ISSUE TITLE
MueLu unit test fail on exit under MPICH3.2

### ISSUE THREAD

**Issue by prwolfe** [trilinos/Trilinos#2799]
The unit tests MueLu_UnitTestsEpetra_MPI_1, MueLu_UnitTestsEpetra_MPI_4, MueLu_UnitTestsTpetra_MPI_1, and MueLu_UnitTestsTpetra_MPI_4 all run to completion and at exit fail with 

> WARNING: Tpetra::Map destructor (~Map()) is being called after Kokkos::finalize() has been called.  > This is user error!  There are two likely causes: 
>   1. You have a static Tpetra::Map (or RCP or shared_ptr of a Map)
>   2. You declare and construct a Tpetra::Map (or RCP or shared_ptr of a Tpetra::Map) at the same scope in main() as Kokkos::finalize() or Tpetra::finalize().

> Don't do either of these!  Please refer to GitHib Issue #2372.

I do not see these under openmpi builds.

@trilinos/muelu 

## Steps to Reproduce

This can be see from my test builds of the new PR template at https://testing-vm.sandia.gov/cdash/testDetails.php?test=45860155&build=3464065 and can be re-created by doing

```
source ${TrilinosSource}/cmake/std/sems/PullRequestIntel17.0.1TestingEnv.sh
cmake -C ${TrilinosSource}/cmake/std/PullRequestLinuxIntelTestingSettings.cmake -DTrilinos_ENABLE_MueLu=ON ${TrilinosSource}
cd pacakges/muelu/test/unit_tests
make
```
 Note that I am also seeing this in zoltan2. Not sure if this is a shared issue or not. I am building in debug now to try and find the issue.

**Comment by mhoemmen** [comment]
My suspicion is that some MultiVector was getting stashed away in a static ParameterList.  We looked at this today but some experimentation with the debugger didn't help.

**Comment by prwolfe** [comment]
As Mark said we are at a bit of a loss.  The debugger said the RCPNode in question was created during a call to create an Array of ints (see GeneralGeometriPFactory.cpp line 939), but as far as I can see that never would up in a tpetra map.

I need a clean set of tests in order to enable this build on the PR testing, so I will likely disable this test in our Pull Request testing when I get to that point early next week.  If there is anything additional I can do to help track this down please let me know.

**Comment by mhoemmen** [comment]
We could always disable the messages, but this looks like some process crashed or had a problem.

**Comment by lucbv** [comment]
I can look at GeneralGeometriPFactory and see if I can find something suspicious. @mhoemmen if you have a configuration that I should use and any extra info such as debugger output let me know.

**Comment by mhoemmen** [comment]
@lucbv please talk to @prwolfe for configuration details; thanks!

**Comment by prwolfe** [comment]
@lucbv - the instructions are in this issue under "Step to Reproduce".  I didn't find any way to get useful info out of the debugger, so you are on your own there.

**Comment by mhoemmen** [comment]
Hm, I wonder if creating a Tpetra Node instance by hand (rather than letting `Tpetra::Map` manage the NOde instance) could cause this issue.
