### ISSUE TITLE
Amesos: reference guide is out-of-date

### ISSUE THREAD

**Issue by jhux2** [trilinos/Trilinos#2801]
@trilinos/amesos 

The Amesos 2.0 Reference Guide in `amesos/doc/AmesosReferenceGuide` has out-of-date configure and build instructions.  This may confuse users - see #2770. Other parts may be out of date as well.  

Possible resolutions:

1. Delete the guide.
1. Put a warning at the beginning that parts of the guide are invalid.
1. Update the incorrect parts of the guide.

**Comment by srajama1** [comment]
@jhux2 I didn't know such guide existed ! We will do something. I am leaning towards 2.

**Comment by davoodansari** [comment]
Yes the guide is very much outdated. I tried to follow instructions from the guide and all solver parameters seem to have changed :) An updated guide will certainly help.
