### ISSUE TITLE
MueLu/Ifpack2/Tpetra: Fix issues with RCPs associated with Teuchos::TimeMonitor and Kokkos profiling tool integration

### ISSUE THREAD

**Issue by csiefer2** [trilinos/Trilinos#2804]
Fix issues with RCPs associated with Teuchos::TimeMonitor and Kokkos profiling tool integration.

As per @mhoemmen :

FYI, @ibaned pointed out a difficulty over the phone today: Kokkos Profiling expects that regions always form a tree -- any two regions are either disjoint, or one fully encloses the other. However, MueLu's use of RCP to handle TimeMonitor breaks this assumption. For example:

RCP<TimeMonitor> mon = rcp (new TimeMonitor (*TimeMonitor::getNewCounter ("A")));
code_A_to_time ();
mon =  rcp (new TimeMonitor (*TimeMonitor::getNewCounter ("B")));
code_B_to_time ();
// ... etc. ...

The problem is that the right-hand side of mon = rcp (new TimeMonitor (...)); gets evaluated first, and creates the second TimeMonitor, before the first TimeMonitor's destructor gets called. This means that the second TimeMonitor instance overlaps in time with the first one. @ibaned noticed that this can result in timing differences in practice -- just a few nanoseconds, but it breaks the tree invariant and thus causes some regions to have artificially small timings.

**Comment by ibaned** [comment]
@trilinos/tpetra @trilinos/muelu @trilinos/ifpack2

**Comment by ibaned** [comment]
To elaborate, the issues this could cause range from crashing the timer system to having undetectable incorrect timings where the time spent in the second timer goes from the correct value to near zero and the first timer doubles in size. I'll try to add least add some error checking so we eliminate the class of issues where times are just silently wrong.

**Comment by aprokop** [comment]
Can we get a feedback of printing the names of timers that overlap?

**Comment by rppawlo** [comment]
FYI, we hit this exact issue last week with the StackedTimer - but it is programmed to throw on detecting overlapped timers (they were coming from TimeMonitor usage). There's two unit tests in teuchos/comm for StackedTimer to catch this and print a warning message that explains the use case starting on this line:

https://github.com/trilinos/Trilinos/blob/ec9cba59fa400b1454feb1458794245ba775b3eb/packages/teuchos/comm/test/StackedTimer/stacked_timer.cpp#L244

**Comment by srajama1** [comment]
@csiefer2 @jhux2 This issue might cause some pain in profiling in FY19 for milestones (I am told). Can you please prioritize this.

**Comment by jhux2** [comment]
@srajama1 Can you be more specific?  (Maybe take this offline.)

**Comment by srajama1** [comment]
@jhux2 Let us take this offline.

**Comment by jhux2** [comment]
@DrBooom You mentioned that you had hit this issue.  Could you provide an update?
