### ISSUE TITLE
Panzer: Add gid generator for edge and face entities

### ISSUE THREAD

**Issue by rppawlo** [trilinos/Trilinos#281]
Given node gids and element connectivity, add a function to generate edge and face gids. This will allow more flexibility in connecting to less capable mesh databases.

Required functionality has been added to zoltan. Just need to add this to panzer dof manager library.

@trilinos/panzer

**Comment by eric-c-cyr** [comment]
The idea here is to write a new ConnManager that takes a user defined ConnManager that can provide element to node lists. This new ConnManager will then use those to generate the appropriate edges and faces. This will be based on the Zoltan2::findUniqueGIDs function @kddevin wrote. This function will take two nodes and produce unique edge ids with assumed low to high ordering of node ids. For faces, three nodes will be used to produce a unique face number. Uniqueness of specification will be assumed by always taking the lowest node id, and then taking its two neighbors. The ordering will be guaranteed to be smallest to largest.

In terms of testing the CartesianConnManager can be used to generate a nodal conn manager.

**Comment by gsjaardema** [comment]
Won't the face numbering fail for some quad faces that share 3 of their 4 nodes?  This "slit" is common in many meshes.  An example is a mesh of a tire tread which includes "sipes" which are thin slits.

**Comment by eric-c-cyr** [comment]
If I understand what your are saying than possibly it would. However, from a global unknown numbering perspective, sharing a face for an HDIV basis probably wouldn't make sense there anyway. I'm not sure would high order degrees of freedom would apply. If all you are interested in is nodal numbering (from the DOFManager perspective) then this wouldn't cause real problems. The question I have is the general capability more valuable then the slit is common? Can we back burner this question in an effort to support the de Rham complex need for EMPIRE?

**Comment by eric-c-cyr** [comment]
If we are concerned about this case, we could just do all four nodes on the face. The face would be over specified. But that would be fine. If you have a mixed mesh, you could always include a -1 node for triangles to make sure the data structures are sized correctly. I think this would be a fine solution in this case, with only nominal waste. @gsjaardema what do you think?

**Comment by gsjaardema** [comment]
That is what I do in my "skinner" and face generation code.  Not sure if
you need the generality for your case but just thought I would mention it

.. Greg

**Comment by eric-c-cyr** [comment]
@rppawlo This needs to be sent to Carlton for closure.
