### ISSUE TITLE
SEACAS tests failing in ATDM builds on mutrino

### ISSUE THREAD

**Issue by fryeguy52** [trilinos/Trilinos#2815]
CC: @bartlettroscoe, @trilinos/seacas

## Next Action Status

Switching from 'salloc' to 'sbatch' eliminated all but one of the failing tests and the remaining failing test `SEACASExodus_exodus_unit_tests` was disabled in commit d12ca4ebe37d9712574fa8e98fa25eca5acb5422 merged to 'develop' in PR #3011 on 6/26/2018.

## Summary

The following tests are failing in the nightly jenkins jobs of the ATDM configuration on mutrino

[SEACASAprepro_aprepro_command_line_include_test](https://testing.sandia.gov/cdash/testDetails.php?test=48123101&build=3591754)
[SEACASAprepro_aprepro_command_line_vars_test](https://testing.sandia.gov/cdash/testDetails.php?test=48123100&build=3591754)
[SEACASAprepro_aprepro_unit_test](https://testing.sandia.gov/cdash/testDetails.php?test=48123098&build=3591754)
[SEACASAprepro_lib_aprepro_lib_array_test](https://testing.sandia.gov/cdash/testDetails.php?test=48123102&build=3591754)
[SEACASAprepro_lib_aprepro_lib_unit_test](https://testing.sandia.gov/cdash/testDetails.php?test=48123103&build=3591754)
[SEACASExodus_exodus_unit_tests](https://testing.sandia.gov/cdash/testDetails.php?test=48363282&build=3591754)

The list of failures can be seen [here](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&date=2018-05-23&limit=0&filtercount=2&showfilters=1&filtercombine=and&field1=testname&compare1=63&value1=SEACASA&field2=site&compare2=61&value2=mutrino) on CDash

They are failing in both
[Trilinos-atdm-mutrino-intel-opt-openmp](https://testing.sandia.gov/cdash/index.php?project=Trilinos&parentid=3590846)
[Trilinos-atdm-mutrino-intel-debug-openmp](https://testing.sandia.gov/cdash/index.php?project=Trilinos&parentid=3591410)

It looks like they all have something like this in the error output:
```
TEST_2

Running: "diff" "-w" "/lscratch1/jenkins/mutrino-slave/workspace/Trilinos-atdm-mutrino-intel-opt-openmp/SRC_AND_BUILD/Trilinos/packages/seacas/libraries/aprepro_lib/test_standard.out" "/lscratch1/jenkins/mutrino-slave/workspace/Trilinos-atdm-mutrino-intel-opt-openmp/SRC_AND_BUILD/BUILD/packages/seacas/libraries/aprepro_lib/test.output"

--------------------------------------------------------------------------------

diff: /lscratch1/jenkins/mutrino-slave/workspace/Trilinos-atdm-mutrino-intel-opt-openmp/SRC_AND_BUILD/BUILD/packages/seacas/libraries/aprepro_lib/test.output: No such file or directory

--------------------------------------------------------------------------------

TEST_2: Return code = 2
TEST_2: Pass criteria = Zero return code [FAILED]
TEST_2: Result = FAILED
```

## Steps to Reproduce

on mutrino clone Trilinos and run the following. This will automatically set up the environment.
```
$ cd <some_build_dir>/

$ source $TRILINOS_DIR/cmake/std/atdm/load-env.sh intel-opt-openmp

$ cmake \
  -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
  -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_SEACAS=ON \
  $TRILINOS_DIR

$ make -j16

$ salloc -N 1 -p standard -J $JOB_NAME ctest -j16
```

## Environment

This is set up automatically in the instructions to reproduce above

**Comment by mhoemmen** [comment]
@micahahoward

**Comment by bartlettroscoe** [comment]
CC: @gsjaardema, @kddevin (Data Services Product Lead)

FYI: After the update to use 'sbatch' instead of 'salloc' on 'mutrino' 4 days ago (see PR #2964 and  commit ff791f8edcf3bb6015b8b6f1744d7d95768a068f), there is only one remaining failing SEACAS test since then which is `SEACASExodus_exodus_unit_tests` as shown in [this query](https://testing-vm.sandia.gov/cdash/queryTests.php?project=Trilinos&date=2018-06-18&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=7&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-&field2=status&compare2=62&value2=passed&field3=status&compare3=62&value3=notrun&field4=site&compare4=61&value4=mutrino&field5=testname&compare5=65&value5=SEACAS&field6=buildstarttime&compare6=84&value6=2018-06-19&field7=buildstarttime&compare7=83&value7=2018-06-16). 
 This test fails in both the `Trilinos-atdm-mutrino-intel-debug-openmp` and `Trilinos-atdm-mutrino-intel-opt-openmp` builds.  In both of these builds the test output (for example shown [here]()) shows output that starts with:

```
TEST_0

Running: "/bin/bash" "/lscratch1/jenkins/mutrino-slave/workspace/Trilinos-atdm-mutrino-intel-debug-openmp/SRC_AND_BUILD/BUILD/packages/seacas/libraries/exodus/test/testall"

  Writing output to file "/lscratch1/jenkins/mutrino-slave/workspace/Trilinos-atdm-mutrino-intel-debug-openmp/SRC_AND_BUILD/BUILD/packages/seacas/libraries/exodus/test/exodus_unit_tests.out"

--------------------------------------------------------------------------------

testwt - single precision write test...
Mon Jun 18 11:53:16 2018: [unset]:_pmi_alps_init:alps_get_placement_info returned with error -1
Mon Jun 18 11:53:16 2018: [unset]:_pmi_init:_pmi_alps_init returned -1
Exodus Library Warning/Error: [ex_put_name]
	ERROR: element block id 10 not found in file id 65536
...
```

and then ends with:

```
45a891,892
> Mon Jun 18 11:54:26 2018: [unset]:_pmi_alps_init:alps_get_placement_info returned with error -1
> Mon Jun 18 11:54:27 2018: [unset]:_pmi_init:_pmi_alps_init returned -1
46a894,895
> Mon Jun 18 11:54:30 2018: [unset]:_pmi_alps_init:alps_get_placement_info returned with error -1
> Mon Jun 18 11:54:30 2018: [unset]:_pmi_init:_pmi_alps_init returned -1

--------------------------------------------------------------------------------

TEST_1: Return code = 1
TEST_1: Pass criteria = Zero return code [FAILED]
TEST_1: Result = FAILED

================================================================================

OVERALL FINAL RESULT: TEST FAILED (SEACASExodus_exodus_unit_tests)
```

@gsjaardema, any idea what might be happening here? 

Do you mind if we temporarily disable this test so that we can promote this build?

**Comment by bartlettroscoe** [comment]
FYI: This appears to be the only platform with builds submitting to CDash where this test is failing out of 38 builds where this test is run as shown across all builds yesterday [here](https://testing-vm.sandia.gov/cdash/testSummary.php?project=1&name=SEACASExodus_exodus_unit_tests&date=2018-06-17).  Therefore, disabling this test in this one build does not seem like it would result in the loss of that much testing (and this test is failing anyway so it is providing no value to the test suite on this platform).

**Comment by gsjaardema** [comment]
The `ex_put_name` Warning/Error is expected from `testwt`.  The other errors with `[unset]:_pmi...` are not expected.  I am fine with disabling this test on this platform/build.

**Comment by bartlettroscoe** [comment]
@gsjaardema said:

> I am fine with disabling this test on this platform/build.

@fryeguy52, can you please put in a targeted disable for this test in the (new) files:

```
cmake/std/atdm/mutrino/tweaks/INTEL-RELEASE-OPENMP.cmake
cmake/std/atdm/mutrino/tweaks/INTEL-DEBUG-OPENMP.cmake
```

as mentioned in:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md

and:

* https://snl-wiki.sandia.gov/display/CoodinatedDevOpsATDM/ATDM+Builds+of+Trilinos#ATDMBuildsofTrilinos-Addressingfailures

and from looking at other examples?

NOTE: If that documentation is sufficient, let's work on improving it.

**Comment by bartlettroscoe** [comment]
FYI: Test `SEACASExodus_exodus_unit_tests` disabled in commit d12ca4ebe37d9712574fa8e98fa25eca5acb5422 merge to 'develop' in PR #3011 on 6/26/2018.

As evidence of this, you can see that this test was missing in the SEACAS tests on 'mutrino' yesterday in [this query](https://testing-vm.sandia.gov/cdash/queryTests.php?project=Trilinos&date=2018-07-12&filtercombine=and&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-mutrino-&field2=testname&compare2=65&value2=SEACAS).

Marking this with "Disabled Tests" label.
