### ISSUE TITLE
ROL:  Error Building Drekar

### ISSUE THREAD

**Issue by jmgate** [trilinos/Trilinos#2819]
@trilinos/rol 

## Current Behavior
I'm unable to build Drekar at the moment due to the following error:
```
In file included from /workspace/Trilinos/DrekarBase/drekar/src/core/optimization/Drekar_ROLStatusTest.hpp:12:0,
                 from /workspace/Trilinos/DrekarBase/drekar/src/core/optimization/Drekar_ROLStatusTest.cpp:11:
/workspace/Trilinos/packages/rol/src/status/ROL_StatusTest.hpp:68:34: error: expected ‘)’ before ‘&’ token
   StatusTest( ROL::ParameterList &parlist ) {
                                  ^
```

## Possible Solution
Should `ROL_StatusTest.hpp` include whatever file `ROL::ParameterList` is defined in?

It's entirely possible this isn't a problem with ROL, but with my configuration of Drekar.

## Steps to Reproduce
1.  Check out Trilinos commit e6025ce and DrekarBase commit dd5c80e.
1.  Configure Trilinos with [this script](https://github.com/trilinos/Trilinos/files/2037028/configureTrilinos.txt).
1.  Build and see [this output](https://github.com/trilinos/Trilinos/files/2037051/make1805241451424274832.log).

## Interested Parties
@eric-c-cyr, @rppawlo, either of you seeing this?

**Comment by dridzal** [comment]
@gregvw --- please chime in.

**Comment by gregvw** [comment]
@dridzal -- Yes, apparently it got its dependency satisfied indirectly before. Going to push a fix and make a script that searches for unmet dependencies.

**Comment by dridzal** [comment]
Started ROL/Trilinos sync based on @gregvw 's fix in the ROL repo.

**Comment by dridzal** [comment]
@jmgate -- has this issue been resolved?  See https://github.com/trilinos/Trilinos/pull/2821.

**Comment by jmgate** [comment]
I'm sorry, @dridzal, I'm out of the country till June 5th and won't be able to test this until then.  Perhaps @rppawlo or @eric-c-cyr could try building Drekar with ROL on and let you know.

**Comment by dridzal** [comment]
No rush.  Let's keep it open until it's properly tested.

**Comment by jmgate** [comment]
Thanks @dridzal and @gregvw&mdash;looks like I'm up and running again.
