### ISSUE TITLE
NOX_Playa_Group.cpp Make Error

### ISSUE THREAD

**Issue by xiaozhaolook** [trilinos/Trilinos#2829]
@trilinos/<teamName>

## Your Environment

- **Relevant repo SHA1s:**  
- **Relevant configure flags or configure script:**  
- **Operating system and version:**  
- **Compiler and TPL versions:**  

## Related Issues

* Blocks 
* Is blocked by 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of

**Comment by mhoemmen** [comment]
@xiaozhaolook Please post more information, such as the build error itself (or a sample, if too long).
