### ISSUE TITLE
Using Teuchos to send a data stored in Kokkos::View

### ISSUE THREAD

**Issue by keitat** [trilinos/Trilinos#2835]
I am looking for an example of message passing using Teuchos and Kokkos::View.  Is there any example available in the Trillions source or document?

**Comment by mhoemmen** [comment]
@keitat Do you mean using the Teuchos Comm wrappers to do MPI communication?  If so, then include `Teuchos_CommHelpers.hpp`.  Look in `Tpetra_Distributor.[ch]pp` for examples.

**Comment by keitat** [comment]
Thanks.  I am writing a message passing code in which Kokkos::View is used for data container.    I will look into these two source files.

**Comment by mhoemmen** [comment]
`Tpetra::Distributor` uses Teuchos Comm wrappers that take `Kokkos::View`.
