### ISSUE TITLE
Tpetra: Eliminate CUDA as direct TPL

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#2836]
It should only come in through Kokkos.

@trilinos/tpetra

**Comment by mhoemmen** [comment]
I read Tpetra's CMake logic a bit, in particular [this file](https://github.com/trilinos/Trilinos/blob/1f66625b666138226fb6412fa19afcc35402b61d/packages/tpetra/CMakeLists.txt#L59).  I also reread #1939.  This made me reevaluate this issue. 

  1. Tpetra developers decided to [eliminate the `Node` template parameter](https://github.com/trilinos/Trilinos/wiki/Deprecation1) by FY19.  This means that the `INST` macros will become less relevant.  However, users still want to enable or disable Tpetra's support for CUDA, OpenMP, etc., independently of Kokkos' support for those back-ends.  (See #1939.)  This suggests we may want to keep `Tpetra_ENABLE_CUDA`, and that we may even want to add `Tpetra_ENABLE_OpenMP`, etc.
  2. Tpetra uses `Tpetra_ENABLE_CUDA` to check its own CUDA requirements, that may be more strict than Kokkos'.  (For example, Tpetra requires CUDA lambda support, and thus needs at least CUDA 7.5, though we only have Dashboard tests for CUDA >= 8.0.)
  3. Tpetra uses `Tpetra_ENABLE_CUDA` to decide whether to check MPI for CUDA support.  Kokkos is explicitly MPI-agnostic.

I think the following would make sense:

  1. Make `Tpetra_ENABLE_CUDA_DEFAULT` depend only on `Kokkos_ENABLE_Cuda`, not on `TPL_ENABLE_CUDA`.  Let Kokkos be responsible for a sane build configuration (e.g., users should not be allowed to set `Kokkos_ENABLE_Cuda=ON` if `TPL_ENABLE_CUDA=OFF`).
  2. Remove TpetraCore's explicit dependence on the CUDA TPL.
  3. Retain the `Tpetra_ENABLE_CUDA` CMake option for future use, as discussed above.

@trilinos/tpetra any thoughts?

**Comment by kddevin** [comment]
We decided to add Tpetra_ENABLE_<platform> for each platform supported by Kokkos_ENABLE_<platform>, using the same spelling and capitalization as the Kokkos flag.
By default, if the Tpetra flags are not set by the user, the Tpetra flags would have the values of the Kokkos flags.
We will deprecate the Tpetra_INST_<platform> flags, targeting FY19 Q1.

**Comment by mhoemmen** [comment]
@csiefer2 this looks relevant

**Comment by kyungjoo-kim** [comment]
@csiefer2 I would close this issue. The flag gives us the choice to disable CUDA even if Kokkos enables CUDA. No reason to remove the flag.

**Comment by tasmith4** [comment]
@kyungjoo-kim @csiefer2 did we ever deprecate the Tpetra_INST_ flags, as per @kddevin's comment above (I suspect not)?  If not, do we still want to?

**Comment by csiefer2** [comment]
We did not deprecate the Tpetra_INST_CUDA guys.  Heck, I still use them (because configure files get cut & paste forever).

We should probably toss sorting this out on the backlog.
