### ISSUE TITLE
Tpetra::CrsMatrix::rightScale should take a column Map Vector, but takes a row Map Vector instead

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#2844]
@trilinos/tpetra

**Comment by mhoemmen** [comment]
PR #2840 will fix this issue.

**Comment by mhoemmen** [comment]
Thanks @william76 ! :D

**Comment by william76** [comment]
@mhoemmen strange... I didn't do anything to this issue but Github says I closed it...  

I was able to get the develop -> master promotion done this morning, could that be triggering some issue closing?

**Comment by mhoemmen** [comment]
@william76 Yup, I think that should automatically close issues, if the commit says something like "Fix `#${ISSUE_NUMBER}`".

**Comment by william76** [comment]
neat!
