### ISSUE TITLE
Zoltan2_simplePamgenTest_MPI_3 test fails in Intel PR build

### ISSUE THREAD

**Issue by prwolfe** [trilinos/Trilinos#2848]
When establishing the Intel PR build this test routinely fails.  The reported error is

> ***
> *** Warning! The following Teuchos::RCPNode objects were created but have
> *** not been destroyed yet.  A memory checking tool may complain that these
> *** objects are not destroyed correctly.
> ***
> *** There can be many possible reasons that this might occur including:
> ***
> ***   a) The program called abort() or exit() before main() was finished.
> ***      All of the objects that would have been freed through destructors
> ***      are not freed but some compilers (e.g. GCC) will still call the
> ***      destructors on static objects (which is what causes this message
> ***      to be printed).
> ***
> ***   b) The program is using raw new/delete to manage some objects and
> ***      delete was not called correctly and the objects not deleted hold
> ***      other objects through reference-counted pointers.
> ***
> ***   c) This may be an indication that these objects may be involved in
> ***      a circular dependency of reference-counted managed objects.
> ***
> 
> ***
> *** Warning! The following Teuchos::RCPNode objects were created but have
> *** not been destroyed yet.  A memory checking tool may complain that these
> *** objects are not destroyed correctly.
> ***
> *** There can be many possible reasons that this might occur including:
> ***
> ***   a) The program called abort() or exit() before main() was finished.
> ***      All of the objects that would have been freed through destructors
> ***      are not freed but some compilers (e.g. GCC) will still call the
> ***      destructors on static objects (which is what causes this message
> ***      to be printed).
> ***
> ***   b) The program is using raw new/delete to manage some objects and
> ***      delete was not called correctly and the objects not deleted hold
> ***      other objects through reference-counted pointers.
> ***
> ***   c) This may be an indication that these objects may be involved in
> ***      a circular dependency of reference-counted managed objects.
> ***
> 
> 
> 
> ***
> *** Warning! The following Teuchos::RCPNode objects were created but have
> *** not been destroyed yet.  A memory checking tool may complain that these
> *** objects are not destroyed correctly.
> ***
> *** There can be many possible reasons that this might occur including:
> ***
> ***   a) The program called abort() or exit() before main() was finished.
> ***      All of the objects that would have been freed through destructors
> ***      are not freed but some compilers (e.g. GCC) will still call the
> ***      destructors on static objects (which is what causes this message
> ***      to be printed).
> ***
> ***   b) The program is using raw new/delete to manage some objects and
> ***      delete was not called correctly and the objects not deleted hold
> ***      other objects through reference-counted pointers.
> ***
> ***   c) This may be an indication that these objects may be involved in
> ***      a circular dependency of reference-counted managed objects.
> ***
> 
>   0: RCPNode (map_key_void_ptr=  0: RCPNode (map_key_void_ptr=0x1eb8f40)
>        Information = 0x2ec2940)
>        Information = {T=int, ConcreteT=int, p=0x2ec2940, has_ownership=0}
>        RCPNode address = 0x2ed1700
>        insertionNumber = 3703
> 
> {T=int, ConcreteT=int, p=0x1eb8f40, has_ownership=0}
>        RCPNode address = 0x1e92600
>        insertionNumber = 3739
> 

@trilinos/zoltan2 

## Current Behavior

This test runs to completion and then fails with a memory-related error. It passes on the other builds I found it in.

## Steps to Reproduce

This can be see from my test builds of the new PR template at https://testing-vm.sandia.gov/cdash/testDetails.php?test=45860155&build=3464065 and can be re-created by doing

source ${TrilinosSource}/cmake/std/sems/PullRequestIntel17.0.1TestingEnv.sh
cmake -C ${TrilinosSource}/cmake/std/PullRequestLinuxIntelTestingSettings.cmake -DTrilinos_ENABLE_Zoltan2=ON ${TrilinosSource}
cd pacakges/zoltan2/test/unit_tests
make
Note that I am also seeing this in muelu. Not sure if this is a shared issue or not

## Related Issues

* Possibly Related to 
#2799

**Comment by mhoemmen** [comment]
Hm, I wonder if creating a Tpetra Node instance by hand (rather than letting `Tpetra::Map` manage the NOde instance) could cause this issue.
