### ISSUE TITLE
Zoltan2 EvaluatePartition constructor additions

### ISSUE THREAD

**Issue by kddevin** [trilinos/Trilinos#285]
EvaluatePartition's constructor needs to accept communicators in a way analogous to PartitioningProblem.  It currently requires an RCP to a Teuchos::Comm.  It should also have interfaces that accept no communicator (and create a default communicator internally) and that accept an MPI communicator directly.  The latter is needed by STK.  See the PartitioningProblem constructor for examples.
Needed by May 1 if possible; contact @kddevin with schedule concerns.  Thanks.
@tscoffe @trilinos/zoltan2

**Comment by vjleung** [comment]
Fixed by May 1, just not closed.
