### ISSUE TITLE
Zoltan2 Problem and EvaluatePartition segfaults with NULL parameter list

### ISSUE THREAD

**Issue by kddevin** [trilinos/Trilinos#286]
Parameter list is passed as a pointer to Problem constructors and EvaluatePartition.  It is not tested for NULL before it is used.  It should be tested for NULL before being used.
Needed by May 1 if possible for next Trilinos merge.
@trilinos/zoltan2

**Comment by kddevin** [comment]
@tscoffe

**Comment by vjleung** [comment]
I thought I did that.  I will check when I get back.

Sent from my iPhone

On Apr 11, 2016, at 10:48 PM, K Devine <notifications@github.com<mailto:notifications@github.com>> wrote:


Parameter list is passed as a pointer to Problem constructors and EvaluatePartition. It is not tested for NULL before it is used. It should be tested for NULL before being used.
Needed by May 1 if possible for next Trilinos merge.
@trilinos/zoltan2<https://github.com/orgs/trilinos/teams/zoltan2>

-

**Comment by vjleung** [comment]
This is new.  ?I got the two previous messages confused with this one.


________________________________

**Comment by vjleung** [comment]
Fixed
