### ISSUE TITLE
Tpetra: Scalar=complex with CUDA is broken; hangs machine

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#287]
@trilinos/tpetra This is a result of the following Kokkos issue:

https://github.com/kokkos/kokkos/issues/238

Current work-around is to disable complex arithmetic when building Tpetra with CUDA.

**Comment by crtrott** [comment]
Fix pushed to Trilinos, need to test whether it works for Tpetra.

**Comment by crtrott** [comment]
I just tested on my machine with complex enabled for Cuda, and it did pass the Tpetra tests except for the import/export tests which always fail. Mark you might want to close this.

**Comment by mhoemmen** [comment]
Thanks Christian!  I'll close this bug now.
