### ISSUE TITLE
Ifpack2: Expose new threaded coloring Gauss-Seidel to users by default

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#288]
@trilinos/ifpack2 @kddevin @jdbooth 

Right now, enabling Ifpack2's new threaded coloring Gauss-Seidel requires enabling "experimental" CMake options (both off by default) in both KokkosKernels and Ifpack2.  It would make sense to build and make this new capability available by default, even if it is not the default Gauss-Seidel implementation.

**Comment by mhoemmen** [comment]
See #289 for the comparable issue with threaded ILU.

**Comment by srajama1** [comment]
Theoretically, we could. We are just being bit more conservative. We need add nightly tests, make sure it builds and runs well on all platforms.

Assigining to Mehmet as he wrote it. Somewhat lower priority in my mind.

**Comment by mhoemmen** [comment]
No worries :-)  Main reason for raising the issue now is to make sure I don't forget.

**Comment by mhoemmen** [comment]
Status?

**Comment by mhoemmen** [comment]
@mndevec status?

**Comment by mhoemmen** [comment]
Status as far as I can tell:

Building this requires setting CMake options TpetraKernels_ENABLE_Experimental:BOOL=ON and Ifpack2_ENABLE_Experimental:BOOL=ON.  Both are OFF by default.

Code doesn't build.  I get build errors like this:

.../Trilinos/packages/ifpack2/src/Ifpack2_Relaxation_def.hpp:1839:45: error: `class Kokkos::Experimental::View<double**, Kokkos::LayoutLeft, Kokkos::Serial, void>` has no member named `h_view`:
```
X_colMap_host_view.ptr_on_device () != X_domainMap_host_view.h_view.ptr_on_device ()
```

**Comment by mhoemmen** [comment]
I just fixed the Ifpack2 build error, and a KokkosKernels build error (in a `ZeroVector` functor).  I also added a stripped-down unit test, based on the file that @mndevec sent me.  The test builds but segfaults.

Enable the test by setting the following CMake options:

-D TpetraKernels_ENABLE_Experimental:BOOL=ON
-D Ifpack2_ENABLE_Experimental:BOOL=ON
-D Ifpack2_ENABLE_Experimental_KokkosKernels_Features:BOOL=ON

**Comment by srajama1** [comment]
Adding myself to the assignees as this falls under delivering the solvers/preconditioners in kokkoskernels and shylu in Ifpack2.

**Comment by mhoemmen** [comment]
> Adding myself to the assignees as this falls under delivering the solvers/preconditioners in kokkoskernels and shylu in Ifpack2.

Thanks!  It's probably not hard to fix.  I mainly wanted to get the test in place before Mehmet gets back, so he can hit the ground running.

**Comment by mndevec** [comment]
Mark, my push should fix the segfault. But the test is failing because it does not converge in the given number of iterations, which is also the case for the current sequential GS as well.

**Comment by mhoemmen** [comment]
@mndevec Thanks Mehmet!  I noticed that the segfault is gone; that's already a good step :-D  It looks like the residual norm is decreasing after multiple sweeps.

Would you mind writing the following test?  Take a test matrix (say, 2-D or 3-D Poisson), measure residual norm reduction with Jacobi over k sweeps (k >> 1), then measure residual norm reduction with your new algorithm over the same number of sweeps.  It should do no worse than Jacobi.  Also, both should actually reduce the residual norm (good sanity check for Jacobi too).  Thanks!

**Comment by mhoemmen** [comment]
@mndevec just wrote the aforementioned unit test, that compares his multithreaded Gauss-Seidel against Jacobi.  I just added it to Ifpack2, and it passes.  We've pushed the changes.

Thus, the next step is to make sure that this new capability builds by default.  We should also add a test for complex matrices.

**Comment by srajama1** [comment]
We discussed this. This can be enabled to compile, it still will not be the default for now. It will be a runtime option. I need to better understand this new policy for "change in numerical behavior coming your way" to always enable it confidently.

**Comment by mhoemmen** [comment]
> We discussed this. This can be enabled to compile, it still will not be the default for now. It will be a runtime option. 

This is fine.  See above comment: "...builds by default."  I agree that it should not (yet) run by default.  There are other ways to make non-coloring Gauss-Seidel use threads (e.g., implement it using sparse triangular solve), if applications insist on it being threaded.  For now, what I really want is for this code to _build_ by default (no special CMake options needed), and to be _tested_ through the test that Mehmet just added.  The latter is done, so we just need to do the former.

**Comment by srajama1** [comment]
I am starting this conversion to "builds by default" as it is needed by Nalu as well (not urgent, just needed). I am going to test with Nalu as well to see the behavior.

**Comment by mhoemmen** [comment]
I just verified that the Ifpack2 test that exercises this option passes in a CUDA build, once I enable the CMake options that make this code build.  I'll next test builds with CUDA OFF, with and without OpenMP.  If those builds pass, I'm enabling this thing by default.  No more hiding behind configure options; we have to make this code build and run nightly.

**Comment by mhoemmen** [comment]
No code in the TpetraKernels subpackage uses the HAVE_TPETRAKERNELS_EXPERIMENTAL macro, so we don't have to change anything in TpetraKernels to enable the sparse matrix-matrix multiply code.

**Comment by mhoemmen** [comment]
Clang 3.9 build with CUDA OFF and OpenMP OFF builds without warnings, and passes all Ifpack2 tests but RBILUK and BlockRelaxationPerformance (both known to fail, and both unrelated).

**Comment by mhoemmen** [comment]
GCC 4.9.3 build with CUDA OFF and OpenMP ON builds without warnings.  Running tests now with OMP_NUM_THREADS=4.

**Comment by mhoemmen** [comment]
GCC 4.9.3 build with CUDA OFF and OpenMP ON builds without warnings.  With OMP_NUM_THREADS=4, all Ifpack2 tests pass but the aforementioned unrelated RBILUK test.

**Comment by mhoemmen** [comment]
These results suggests that I can make this code build by default; I don't need to protect it with a macro any more.

**Comment by mhoemmen** [comment]
I've left the macro in place, but it now defaults to be defined.  See packages/ifpack2/ReleaseNotes.txt for details on how to disable it at configure time.  I'm running the check-in test script now.

**Comment by mhoemmen** [comment]
I realized that I had to change CMake logic in KokkosKernels as well, to ensure that the directories implementing graph coloring and multithreaded Gauss-Seidel get included in the build.  I also had to enable the unit and performance tests.  Now I need to redo the builds and tests for the builds mentioned above.

**Comment by mhoemmen** [comment]
Argh, the tests in KokkosKernels depend on gtest.  I may have to disable the KokkosKernels tests and let Ifpack2 cover them for now.

**Comment by mhoemmen** [comment]
I may have figured out the gtest issue.  Since it's a TESTONLY library, KokkosKernels can just point to it (it lives in kokkos/tpls/gtest), and build it again.  I just copied the CMake logic from Kokkos (in particular, from kokkos/core/unit_test/CMakeLists.txt, lines 1-13) into KokkosKernels, right above the test that needs it.  CMake finished without errors.  I'm trying the build now.

**Comment by mhoemmen** [comment]
KokkosKernels' Gauss-Seidel test has a build error:
```
.../Trilinos/packages/tpetra/kernels/unit_test/graph/KokkosKernels_Test_GaussSeidel.cpp: In instantiation of ‘scalar_view_t create_x_vector(size_t, typename scalar_view_t::value_type) [with scalar_view_t = Kokkos::View<Kokkos::complex<double>*, Kokkos::LayoutRight, Kokkos::Device<Kokkos::OpenMP, Kokkos::HostSpace>, Kokkos::MemoryTraits<0u> >; size_t = long unsigned int; typename scalar_view_t::value_type = Kokkos::complex<double>]’:
.../Trilinos/packages/tpetra/kernels/unit_test/graph/KokkosKernels_Test_GaussSeidel.cpp:178:66:   required from ‘void test_gauss_seidel(KokkosKernels::Experimental::Graph::GSAlgorithm) [with scalar_t = Kokkos::complex<double>; lno_t = int; device = Kokkos::Device<Kokkos::OpenMP, Kokkos::HostSpace>]’
.../Trilinos/packages/tpetra/kernels/unit_test/graph/KokkosKernels_Test_GaussSeidel.cpp:232:3:   required from here
.../Trilinos/packages/tpetra/kernels/unit_test/graph/KokkosKernels_Test_GaussSeidel.cpp:140:68: error: no match for ‘operator/’ (operand types are ‘int’ and ‘Kokkos::ViewTraits<Kokkos::complex<double>*, Kokkos::LayoutRight, Kokkos::Device<Kokkos::OpenMP, Kokkos::HostSpace>, Kokkos::MemoryTraits<0u> >::value_type {aka Kokkos::complex<double>}’)
         static_cast <typename scalar_view_t::value_type> (RAND_MAX / max_value);
                                                                    ^
```
I think the code itself is fine.  This looks like a harmless issue with the text not accounting for complex numbers.  I'll disable the test in KokkosKernels for now, open a separate issue for that, and let the Ifpack2 test cover it for now.

**Comment by mhoemmen** [comment]
Another build error in a KokkosKernels test: #980.  Temporarily disabled for now.

**Comment by mhoemmen** [comment]
OK, I got the check-in test script through the KokkosKernels tests.  I enabled downstream packages just to make sure that the new CMake settings didn't break MueLu.  The check-in test script is in the middle of the build now.  It will take a while, so I'm going to let it go for now.

**Comment by srajama1** [comment]
Closing this issue as @mhoemmen has fixed it. Thanks Mark !

**Comment by maherou** [comment]
Is the execution DAG of this kernel deterministic?  If not, it seems to me that we should start documenting this kind of function.  Just a thought.

**Comment by srajama1** [comment]
That is precisely the reason I was asking about the user guide in #971. We need to document this well including determinism and other parameter options to KokkosKernels.

**Comment by maherou** [comment]
It seems to me that this issue should be labeled with "Results Impacting", one of the GitHub Issue labels.  Correct?

**Comment by mhoemmen** [comment]
@maherou This change is not "results impacting" because it does not affect the default behavior.  Ifpack2's Gauss-Seidel is, by default, sequential within an MPI process and deterministic.  Users must ask explicitly for the thread-parallel algorithm.

**Comment by mhoemmen** [comment]
@maherou I have changed the name of this issue to reflect that the fix does not change Ifpack2's default behavior.  It merely exposes the option of multithreaded Gauss-Seidel with coloring to users, and ensures that this option gets built and tested by default.
