### ISSUE TITLE
Kokkos include dirs in installed config file pointing into the build tree instead of the install tree

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#2883]
CC: @trilinos/kokkos, @trilinos/framework, @bathmatt, @micahahoward, @fryeguy52 

## Next Action Status

Merge of PR #2874 back on 6/6/2019 should have resolved this.  Next: Verify issue is resolved for EMPIRE ...

## Description

The last Kokkos update broke the installation of Trilinos for the EMPIRE code.  The issue is that the KokkosConfig.cmake filess seem to be pointing into the build tree instead of the install tree.  More details can be provided by @bathmath and @crtrott.

NOTE: This slipped through the EMPIRE Jenkins Pipeline testing and upgrade process for Trilinos because the same Jenkins entity account is used to build and test EMPIRE that is used to build and install Trilinos.  The issue is that no other users can access the build directories for that Jenkins entity account.

**Comment by ibaned** [comment]
I've been trying to get either a Trilinos CMake configuration that replicates this issue or the patch that @crtrott sent to @bathmatt , could someone provide either of those?

**Comment by bartlettroscoe** [comment]
CC: @trilinos/framework 

> I've been trying to get either a Trilinos CMake configuration that replicates this issue or the patch that @crtrott sent to @bathmatt , could someone provide either of those?

@ibaned, any install of Trilinos that includes should show this.  For example, for the ATDM build configuration `gnu-debug-openmp` on my RHEL6 machine crf450 I just did:

```
$ cd Trilinos.base/BUILDS/ATDM/GNU/GNU_DEBUG_OPENMP/

$  . ~/Trilinos.base/Trilinos/cmake/std/atdm/load-env.sh gnu-debug-openmp
Hostname 'crf450.srn.sandia.gov' matches known ATDM host 'sems-rhel6' and system 'rhel6'
ATDM_CONFIG_TRILNOS_DIR = /home/rabartl/Trilinos.base/Trilinos
Setting default compiler and build options for JOB_NAME='gnu-debug-openmp'
Using SEMS RHEL6 compiler stack GNU to build DEBUG code with Kokkos node type OPENMP

$ rm -r CMake*

$ time cmake -GNinja -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake -DTrilinos_ENABLE_Kokkos=ON -DCMAKE_INSTALL_PREFIX=$PWD/install ~/Trilinos.base/Trilinos &> configure.out

real    0m3.494s
user    0m2.258s
sys     0m0.877s

$ make

$ make install

$ find install -name "*.cmake" -exec grep -nH packages/kokkos {} \;
...
install/lib/cmake/KokkosCore/KokkosCoreConfig.cmake:82:SET(KokkosCore_CXX_FLAGS "    -I./ -I/ascldap/users/rabartl/Trilinos.base/Trilinos/packages/kokkos/core/src -I/ascldap/users/rabartl/Trilinos.base/Trilinos/packages/kokkos/containers/src -I/ascldap/users/rabartl/Trilinos.base/Trilinos/packages/kokkos/algorithms/src -I/ascldap/users/rabartl/Trilinos.base/Trilinos/packages/kokkos/core/src/eti --std=c++11 -g -fopenmp     -g -O0")
...
```

The installation of Trilinos can't rely on the source or build trees.  It has to stand alone.

**Comment by ibaned** [comment]
Okay, I just reproduced this and I think I know how to fix it.

**Comment by bartlettroscoe** [comment]
These include dirs need to be taken out of `KokkosCore_CXX_FLAGS` for the TriBITS build of Kokkos.  Those include dirs are handled automatically by TriBITS.  For example, in the installed file install/lib/cmake/KokkosCore/KokkosCoreConfig.cmake` you see:

```
SET(KokkosCore_INCLUDE_DIRS "${CMAKE_CURRENT_LIST_DIR}/../../../include")
```

You just need to tell the Kokkos makefile stuff not to add any include directories for the CXX flags when doing a TriBITS build.  Hopefully that is just a single variable and some if-statements to add.

**Comment by ibaned** [comment]
> You just need to tell the Kokkos makefile stuff not to add any include directories for the CXX flags when doing a TriBITS build. Hopefully that is just a single variable and some if-statements to add.

Yea, that sounds like the right way to fix this

**Comment by ibaned** [comment]
I think I've come up with a fix, and incorporated it into #2874

**Comment by bartlettroscoe** [comment]
@bathmatt,

With the merge of PR #2874, the Kokkos installation bug should be fixed in the Trilinos 'develop' branch now.

I am putting this "in review".   Also, I think all of the CUDA failures are gone now.  I will update on the status of that in #2827.  Therefore, I think you could update your copy of Trilinos now.  Just watch out for a merge conflict due to the patch for Kokkos in the EMPIRE copy of Trilinos.  That may break the merge commit.

**Comment by bartlettroscoe** [comment]
@jmgate, can you verify that this install issue has been resolved for EMPIRE after syncing Trilinos in the last 2 weeks or so?  Then we can close this issue.

**Comment by jmgate** [comment]
These changes did make it into our fork of Trilinos.  How can I verify that the install is no longer pointing into the build tree?

**Comment by bartlettroscoe** [comment]
> How can I verify that the install is no longer pointing into the build tree?

@jmgate, see the find/grep I did [above](https://github.com/trilinos/Trilinos/issues/2883#issuecomment-394733428).

**Comment by jmgate** [comment]
I did a
```bash
find . -name "*.cmake" -exec grep -nH --color "\-I.*packages/kokkos" {} \;
```

in the install directory and didn't find anything.  Is that sufficient?  This was in a Trilinos install from our nightly Jenkins pipeline.  Do you need to check an install that uses the `cmake/std/atdm` scripts?  If so, I don't know where one of those lives.

**Comment by bartlettroscoe** [comment]
@jmgate, I think the bottom line is that if you can build EMPIRE against the Trilinos installed by Jenkins and don't have any problems, then the issue is resolved.

**Comment by jmgate** [comment]
Sounds good.
