### ISSUE TITLE
MueLu: types mismatch in Driver.cpp equilibration

### ISSUE THREAD

**Issue by lucbv** [trilinos/Trilinos#2894]
@trilinos/muelu 

## Expectations
The vector and matrix Scalar types forming a linear system should be consistent.

## Current Behavior
It seems that a call to KokkosBlas::abs is done on a `Scalar` type vector and a `magnitude` type vector.

## Motivation and Context
The code is not compiling properly when `std::complex<>` is used

## Definition of Done
- [ ] MueLu Driver compiles

## Possible Solution
My guess is that in MueLu_Driver.cpp on line 167 where the call to KokkosBlas::abs() is made, the two vectors should use the same `Scalar` type. Most likely the magnitude type needs to be replaced by a Scalar type even if this means that in the case of complex numbers only the real part is non zero.

## Steps to Reproduce
Build MueLu with tests and examples on and with `Trilinos_ENABLE_Complex=ON`.

## Your Environment
See builds on cdash

**Comment by mhoemmen** [comment]
`KokkosBlas::abs` is _supposed_ to have `Scalar` input and `Kokkos::ArithTraits<Scalar>::mag_type` output.  Does that not build?

**Comment by csiefer2** [comment]
@mhoemmen Concur.  This is _supposed_ to work... will dig into this

**Comment by csiefer2** [comment]
In KokkosBlas1_abs_impl.hpp:228 V_Abs_generic checks for equivalence views of two different types with an == .  This is no bueno.
@kyungjoo-kim @ndellingwood

**Comment by csiefer2** [comment]
https://github.com/kokkos/kokkos-kernels/issues/252

**Comment by mhoemmen** [comment]
uh oh

**Comment by cgcgcg** [comment]
This seems to be fixed.
