### ISSUE TITLE
Amesos: example_AmesosFactory_HB could not read the matrix

### ISSUE THREAD

**Issue by freaklovesmango** [trilinos/Trilinos#2895]
Hi everyone,

still working with Amesos.
I've tried the ```example_AmesosFactory_HB.cpp ``` but it doesn't work.
The error message is 
```Reading matrix 'In_662_bus.rsa'Error: Cannot open file: In_662_bus.rsa Caught exception, maybe file name is incorrect```
 but this should not be the problem... the name is correct, also the sample-HB is from the package. I think that somehow the Galeri::ReadHB doesn't work properly I think...

Does anybody know how I could fix this?

**Comment by mhoemmen** [comment]
@trilinos/amesos @trilinos/amesos2
