### ISSUE TITLE
Teuchos::GlobalMPISession: Add option to save a copy of argc & argv for later?

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#291]
@bartlettroscoe I'm thinking about whether it would be a good idea for `Teuchos::GlobalMPISession` to save a copy of argc and argv for later.  This would make it easier for Kokkos, Tpetra, and downstream unit tests to control Kokkos' behavior (e.g., number of threads) via command-line arguments, without actually needing to call `Kokkos::initialize` in `GlobalMPISession`'s constructor.  "Copy" would be a deep copy, since other code may edit the original argc or argv after `GlobalMPISession`'s constructor returns, and since `Kokkos::initialize` itself wants to edit argv.

**Comment by mhoemmen** [comment]
@crtrott @trilinos/tpetra

**Comment by bartlettroscoe** [comment]
Sounds fine to me.  Whoever does it just needs to add some automated tests to make sure and protect this.  Should be pretty easy to write these tests.

**Comment by mhoemmen** [comment]
> Sounds fine to me.

Thanks Ross!

**Comment by bartlettroscoe** [comment]
Looks like there is a new warning cased by this change that is breaking the -Werror build:

   http://testing.sandia.gov/cdash/viewBuildError.php?buildid=2428587

The warning being elevated to an error is:

```
/nightly/hudson/slave/workspace/trilinos-nightly-muir/MPI_DEBUG_Werror_DEV/Trilinos/packages/teuchos/kokkoscompat/src/KokkosCompat_ClassicNodeAPI_Wrapper.cpp: In function ‘{anonymous}::CmdLineArgs {anonymous}::getCommandLineArgs()’:
/nightly/hudson/slave/workspace/trilinos-nightly-muir/MPI_DEBUG_Werror_DEV/Trilinos/packages/teuchos/kokkoscompat/src/KokkosCompat_ClassicNodeAPI_Wrapper.cpp:230:7: error: variable ‘gotLocalRank’ set but not used [-Werror=unused-but-set-variable]
cc1plus: all warnings being treated as errors
```

**Comment by mhoemmen** [comment]
I'm on it.

**Comment by mhoemmen** [comment]
Fixed!
