### ISSUE TITLE
Panzer tests randomly crashing with "out of memory" errors on CUDA 8.0 and 9.0 debug builds on 'hansen' since Kokkos and KokkosKernels update on 5/26/2018

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#2913]
CC: @trilinos/kokkos, @trilinos/panzer, @fryeguy52 

## Next Action Status

Disable these larger randomly failing Panzer tests in the `cuda-8.0-debug` and `cuda-9.0-debug` builds on 'hansen' ...

## Description

Once the consistent crashes and timeouts of Panzer tests were fixed after the last Kokkos and KokkosKernels update (see #2827), we have been seeing randomly failing Panzer tests (13 total failures so far) in the `cuda-8.0-debug` and `cuda-9.0-debug` builds on 'hansen' (but **not** 'white') as shown in the [this query](https://testing-vm.sandia.gov/cdash/queryTests.php?project=Trilinos&date=2018-06-07&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=16&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-&field2=status&compare2=62&value2=passed&field3=status&compare3=62&value3=notrun&field4=buildname&compare4=62&value4=Trilinos-atdm-mutrino-intel-debug-openmp&field5=buildname&compare5=62&value5=Trilinos-atdm-mutrino-intel-opt-openmp&field6=buildname&compare6=62&value6=Trilinos-atdm-white-ride-cuda-debug-pt-all-at-once&field7=buildname&compare7=62&value7=Trilinos-atdm-serrano-intel-debug-openmp&field8=buildname&compare8=62&value8=Trilinos-atdm-serrano-intel-opt-openmp&field9=buildname&compare9=62&value9=Trilinos-atdm-chama-intel-opt-openmp&field10=buildname&compare10=62&value10=Trilinos-atdm-chama-intel-debug-openmp-panzer&field11=buildname&compare11=62&value11=Trilinos-atdm-chama-intel-debug-openmp&field12=buildname&compare12=62&value12=Trilinos-atdm-chama-intel-opt-openmp-panzer&field13=site&compare13=62&value13=ride&field14=testname&compare14=65&value14=Panzer&field15=buildstarttime&compare15=84&value15=2018-06-08&field16=buildstarttime&compare16=83&value16=2018-06-02).  That query shows the following tests failing (not timing out):

* PanzerAdaptersSTK_CurlLaplacianExample
* PanzerAdaptersSTK_MixedPoissonExample-ConvTest-Hex-Order-1
* PanzerAdaptersSTK_MixedPoissonExample-ConvTest-Hex-Order-2
* PanzerAdaptersSTK_PoissonExample-ConvTest-Quad-Order-3
* PanzerAdaptersSTK_PoissonExample-ConvTest-Quad-Order-4
* PanzerMiniEM_MiniEM-BlockPrec_Augmentation_MPI_4

These tests all show the output:

```
terminate called after throwing an instance of 'std::runtime_error'
  what():  cudaGetLastError() error( cudaErrorMemoryAllocation): out of memory /home/jenkins/hansen/workspace/Trilinos-atdm-hansen-shiller-cuda-9.0-debug/SRC_AND_BUILD/Trilinos/packages/kokkos/core/src/Cuda/Kokkos_CudaExec.hpp:401
Traceback functionality not available

[hansen02:50161] *** Process received signal ***
[hansen02:50161] Signal: Aborted (6)
[hansen02:50161] Signal code:  (-6)
```

This error was first observed in https://github.com/trilinos/Trilinos/issues/2827#issuecomment-394457902 and in https://github.com/trilinos/Trilinos/issues/2827#issuecomment-394463525 it was stated that these failures are likely due to running several tests at the same time with `cuda -j8` vs. one-at-a-time using `ctest -j1`.  (But we can't afford to run the tests with `ctest -j1` because that would take over 6 hours to run the tests as described in https://github.com/trilinos/Trilinos/issues/2464#issuecomment-394034743 there is not enough wall-clock time on 'hansen' to get all of the testing in if we did that and that wastes the machine.)

Looking at the history for one of these tests `PanzerAdaptersSTK_MixedPoissonExample-ConvTest-Hex-Order-2` in [this query](https://testing-vm.sandia.gov/cdash/queryTests.php?project=Trilinos&date=2018-06-07&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=6&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-&field2=buildname&compare2=63&value2=cuda&field3=site&compare3=61&value3=hansen&field4=buildstarttime&compare4=84&value4=2018-06-08&field5=buildstarttime&compare5=83&value5=2018-06-02&field6=testname&compare6=61&value6=PanzerAdaptersSTK_MixedPoissonExample-ConvTest-Hex-Order-2) one can see that the test failed 4 times but otherwise the test takes upwards of 6 minutes to complete some days.  Therefore, one might assume that this is a larger test that uses more memory and therefore might cause memory exhaustion. 

## Steps to reproduce

These tests are crashing randomly as described so it may be hard to reproduce this behavior locally.  But one could follow the instructions at:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#shillerhansen

and give it a try.   But this issue really needs to be resolved by addressing how resources for various tests are assigned and that will require a more comprehensive approach as described in #2422.

**Comment by bartlettroscoe** [comment]
Given that these larger Panzer tests all run fine in the CUDA optimized builds (`cuda-8.0-opt` and `cuda-9.0-opt`) I think we should just disable these few larger Panzer tests in those debug builds on 'hansen'.

Note that these tests also seem to pass just fine on 'white' and 'ride' in the CUDA builds so this is unique to 'hansen'.  And since CUDA builds on 'hansen' and 'shiller' don't really approximate any of the ATS-1 or ATS-2 platforms, I don't know if that is such a bad thing.

**Comment by rppawlo** [comment]
Works for me.

**Comment by bartlettroscoe** [comment]
As shown in [this query](https://testing-vm.sandia.gov/cdash/queryTests.php?project=Trilinos&date=2018-06-07&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=16&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-&field2=status&compare2=62&value2=passed&field3=status&compare3=62&value3=notrun&field4=buildname&compare4=62&value4=Trilinos-atdm-mutrino-intel-debug-openmp&field5=buildname&compare5=62&value5=Trilinos-atdm-mutrino-intel-opt-openmp&field6=buildname&compare6=62&value6=Trilinos-atdm-white-ride-cuda-debug-pt-all-at-once&field7=buildname&compare7=62&value7=Trilinos-atdm-serrano-intel-debug-openmp&field8=buildname&compare8=62&value8=Trilinos-atdm-serrano-intel-opt-openmp&field9=buildname&compare9=62&value9=Trilinos-atdm-chama-intel-opt-openmp&field10=buildname&compare10=62&value10=Trilinos-atdm-chama-intel-debug-openmp-panzer&field11=buildname&compare11=62&value11=Trilinos-atdm-chama-intel-debug-openmp&field12=buildname&compare12=62&value12=Trilinos-atdm-chama-intel-opt-openmp-panzer&field13=site&compare13=62&value13=ride&field14=testname&compare14=65&value14=Panzer&field15=buildstarttime&compare15=84&value15=2018-06-22&field16=buildstarttime&compare16=83&value16=2018-06-15), in the last 5 days, after fixing the jobs on 'hansen' to run on the compute nodes instead of the login node in PR #2941 was merged on 6/14/2018, we have not seen any of these Panzer test failures showing this "out of memory"  error.

Therefore, this issue has been resolved without having to disable anything.  Closing as complete.
