### ISSUE TITLE
Test TpetraCore_MatrixMatrix_UnitTests_MPI_4 failing in all ATDM Trilinos CUDA builds starting 6/7/2018

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#2921]
CC: @trilinos/tpetra, @fryeguy52, @kddevin (Data Services Product Lead)

## Next Action Status

Merged PR #2122 looks to have fixed this.  Next: Wait for all CUDA results on 6/11/2018 and then close on 6/12/2018 ...

## Description

As shown in [this query for the test TpetraCore_MatrixMatrix_UnitTests_MPI_4 between 6/5/2018 and 6/8/2018](https://testing-vm.sandia.gov/cdash/queryTests.php?project=Trilinos&date=2018-06-07&filtercombine=and&filtercombine=and&filtercount=14&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-&field2=buildname&compare2=62&value2=Trilinos-atdm-mutrino-intel-debug-openmp&field3=buildname&compare3=62&value3=Trilinos-atdm-mutrino-intel-opt-openmp&field4=buildname&compare4=62&value4=Trilinos-atdm-white-ride-cuda-debug-pt-all-at-once&field5=buildname&compare5=62&value5=Trilinos-atdm-serrano-intel-debug-openmp&field6=buildname&compare6=62&value6=Trilinos-atdm-serrano-intel-opt-openmp&field7=buildname&compare7=62&value7=Trilinos-atdm-chama-intel-opt-openmp&field8=buildname&compare8=62&value8=Trilinos-atdm-chama-intel-debug-openmp-panzer&field9=buildname&compare9=62&value9=Trilinos-atdm-chama-intel-debug-openmp&field10=buildname&compare10=62&value10=Trilinos-atdm-chama-intel-opt-openmp-panzer&field11=site&compare11=62&value11=ride&field12=testname&compare12=61&value12=TpetraCore_MatrixMatrix_UnitTests_MPI_4&field13=buildstarttime&compare13=84&value13=2018-06-09&field14=buildstarttime&compare14=83&value14=2018-06-05), this test started failing in all of the CUDA builds:

* Trilinos-atdm-hansen-shiller-cuda-8.0-debug
* Trilinos-atdm-hansen-shiller-cuda-8.0-opt
* Trilinos-atdm-hansen-shiller-cuda-9.0-debug
* Trilinos-atdm-hansen-shiller-cuda-9.0-opt
* Trilinos-atdm-white-ride-cuda-debug
* Trilinos-atdm-white-ride-cuda-opt

starting on 6/7/2018.

The failing test output, for example, for the build `Trilinos-atdm-hansen-shiller-cuda-9.0-opt` on 'hansen' on 2018-06-07T18:36:47 UTC shown at:

* https://testing-vm.sandia.gov/cdash/testDetails.php?test=48129338&build=3591841

showed

```
p=0: *** Caught standard std::exception of type 'std::runtime_error' :
 
  Invalid SPGEMMAlgorithm name
 [FAILED]  (6.84 sec) Tpetra_MatMat_double_int_int_Kokkos_Compat_KokkosCudaWrapperNode_operations_test_UnitTest
 Location: /home/jenkins/hansen/workspace/Trilinos-atdm-hansen-shiller-cuda-9.0-opt/SRC_AND_BUILD/Trilinos/packages/tpetra/core/test/MatrixMatrix/MatrixMatrix_UnitTests.cpp:789

...

p=0: *** Caught standard std::exception of type 'std::runtime_error' :
 
  Invalid SPGEMMAlgorithm name
Tpetra sparse matrix-matrix multiply: range row test
  getIdentityMatrix
   Create row Map
   Create CrsMatrix
 [FAILED]  (0.865 sec) Tpetra_MatMat_double_int_longlong_Kokkos_Compat_KokkosCudaWrapperNode_operations_test_UnitTest
 Location: /home/jenkins/hansen/workspace/Trilinos-atdm-hansen-shiller-cuda-9.0-opt/SRC_AND_BUILD/Trilinos/packages/tpetra/core/test/MatrixMatrix/MatrixMatrix_UnitTests.cpp:789

...


The following tests FAILED:
    0. Tpetra_MatMat_double_int_int_Kokkos_Compat_KokkosCudaWrapperNode_operations_test_UnitTest ... 
    10. Tpetra_MatMat_double_int_longlong_Kokkos_Compat_KokkosCudaWrapperNode_operations_test_UnitTest ... 

Total Time: 11.1 sec

Summary: total = 20, run = 20, passed = 18, failed = 2

End Result: TEST FAILED
```

All of the other failed test runs showed about identical test output.

When the test passed for the build `Trilinos-atdm-hansen-shiller-cuda-9.0-opt` on 'hansen' on 2018-06-05T20:22:00 UTC shown at:

* https://testing-vm.sandia.gov/cdash/testDetails.php?test=47987300&build=3582617

it showed the test output:

```
Total Time: 29.4 sec

Summary: total = 20, run = 20, passed = 20, failed = 0

End Result: TEST PASSED
```

## Steps to reproduce

Following the instructions at:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md

one should be able to reproduce this failure on 'hansen', 'shiller', 'white', or 'ride'.  Given that 'white' is on the SON and is pretty unloaded, one can reproduce this as described at:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#ridewhite

with:

```
$ cd <some_build_dir>/

$ source $TRILINOS_DIR/cmake/std/atdm/load-env.sh cuda-debug

$ cmake \
  -GNinja \
  -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
  -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_Tpetra=ON \
  $TRILINOS_DIR

$ make NP=16

$ bsub -x -Is -q rhel7F -n 16 ctest -VV -R TpetraCore_MatrixMatrix_UnitTests_MPI_4
```

**Comment by mhoemmen** [comment]
The exception is thrown in kokkos-kernels: https://github.com/kokkos/kokkos-kernels/blob/1a7b524ba38fdfab6c1058065af06cbcb4a2ce6f/src/sparse/KokkosSparse_spgemm_handle.hpp#L704

**Comment by mhoemmen** [comment]
There are `SPGEMMAlgorithm` enum values that don't have a corresponding return value in that function.  See e.g., https://github.com/kokkos/kokkos-kernels/blob/1a7b524ba38fdfab6c1058065af06cbcb4a2ce6f/src/sparse/KokkosSparse_spgemm_handle.hpp#L65

**Comment by bartlettroscoe** [comment]
CC: @csiefer2,

Looking at the Updates.txt log for the first day this test started failing as shown, for example, at:

* https://testing-vm.sandia.gov/cdash/viewNotes.php?buildid=3589604#!#note0

it seems likely that the breaking change came from one of the following commits:

```
e312b35:  Tpetra: More labelling cleanup
Author: Chris Siefert <csiefer@sandia.gov>
Date:   Wed Jun 6 10:30:53 2018 -0600

M	packages/tpetra/core/ext/TpetraExt_MatrixMatrix_ExtraKernels_def.hpp

...

39d8c1b:  Tpetra: More timer cleanup
Author: Chris Siefert <csiefer@sandia.gov>
Date:   Wed Jun 6 09:43:23 2018 -0600

M	packages/tpetra/core/ext/TpetraExt_MatrixMatrix_ExtraKernels_def.hpp

...

45eec0a:  Tpetra: Timer cleanup
Author: Chris Siefert <csiefer@sandia.gov>
Date:   Tue Jun 5 17:22:22 2018 -0600

M	packages/tpetra/core/ext/TpetraExt_MatrixMatrix_Cuda.hpp
M	packages/tpetra/core/ext/TpetraExt_MatrixMatrix_ExtraKernels_def.hpp
M	packages/tpetra/core/ext/TpetraExt_MatrixMatrix_OpenMP.hpp
```

If the ATDM APPs are using Tpetra MatrixMatrix functionality, this should be fixed ASAP, or the breaking commits should be reverted by reverting the merge commit(s) and then fixing the issue offline.   

Otherwise, if the ATDM APPs are not using the matrix-matrix functionality this test should be temporarily disabled and fixed offline.

If this matrix-matrix functionality is used by MueLu (which would seem to be the case), then this change might impact the ATDM APPs.

We have been trying to clean up the promoted builds after the Kokkos and KokkosKernels update from a couple weeks ago (that triggered #2827 and #2883) so we really need to get back to green soon.

**Comment by mhoemmen** [comment]
I'll leave the Tpetra label, since this could possibly be an issue of some Tpetra test passing in the wrong algorithm name.

**Comment by bartlettroscoe** [comment]
@mhoemmen, I don't see any KokkosKernels changes pulled in the first time this test failed.  All I see are Tpetra changes.  Therefore, this is either a latent bug in KokkosKernels that was triggered by these Tpetra changes or the Tpetra changes are a problem.

Either way, this defect screams for better per-merge-'develop' automated testing that includes CUDA.

**Comment by srajama1** [comment]
Let us give some time for @csiefer2 to comment. It is Friday evening after all :).

**Comment by csiefer2** [comment]
#2922 should fix things

**Comment by bartlettroscoe** [comment]
I merged #2122.  We will watch the ATDM builds tomorrow to see if this test passes in the cuda builds.

**Comment by csiefer2** [comment]
How are we looking?  Did I fix it?

**Comment by bartlettroscoe** [comment]
> How are we looking? Did I fix it?

@csiefer2, it looks like you did.  We need to wait until all of the CUDA builds complete today before closing this but looking the build `Trilinos-atdm-hansen-shiller-cuda-8.0-debug` on 'hansen' today at:

* https://testing-vm.sandia.gov/cdash/index.php?project=Trilinos&parentid=3601955

you can see that all of the Tpetra tests are now passing along with the newly passing test `petraCore_MatrixMatrix_UnitTests_MPI_4` shown at:

* https://testing-vm.sandia.gov/cdash/viewTest.php?onlydelta&buildid=3601977

Thanks for taking care of this so quickly!

**Comment by bartlettroscoe** [comment]
As shown in:

* https://testing-vm.sandia.gov/cdash/testSummary.php?project=1&name=TpetraCore_MatrixMatrix_UnitTests_MPI_4&date=2018-06-11

the test `TpetraCore_MatrixMatrix_UnitTests_MPI_4` passed in all of the ATDM builds yesterday 6/11/2018. (The only build where it did not pass was the build `Linux-gcc-4.9.3-Sierra_MPI_release_DEV_ETI_SERIAL-ON_OPENMP-ON_PTHREAD-OFF_CUDA-OFF_COMPLEX-ON` which was a timeout which looks to be due to oversubscribing the cores on the machine; i.e. a bad setup.)

Therefore, this issue is resolved and I am closing.

@csiefer2, thanks again for taking care of this so quickly!

**Comment by bartlettroscoe** [comment]
Closing.
