### ISSUE TITLE
Test Stratimikos_test_aztecoo_thyra_driver_MPI_1 timing out in  Trilinos-atdm-hansen-shiller-gnu-debug-serial build since 5/30/2018

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#2925]
CC: @trilinos/stratimikos, @fryeguy52 

## Next Action Stauts

Test was disabled for these two builds on 'hansen' in commit 73ae19c pushed on 6/12/2018 and this test disappeared in these builds on 6/13/2018.

## Description

As shown in [this query](https://testing-vm.sandia.gov/cdash/queryTests.php?project=Trilinos&date=2018-06-11&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=11&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-&field2=status&compare2=62&value2=passed&field3=status&compare3=62&value3=notrun&field4=buildname&compare4=62&value4=Trilinos-atdm-white-ride-cuda-debug-pt-all-at-once&field5=site&compare5=62&value5=mutrino&field6=site&compare6=62&value6=serrano&field7=site&compare7=62&value7=chama&field8=site&compare8=62&value8=ride&field9=buildstarttime&compare9=84&value9=2018-06-11&field10=buildstarttime&compare10=83&value10=2018-05-20&field11=testname&compare11=65&value11=Stratimikos), the test `Stratimikos_test_aztecoo_thyra_driver_MPI_1` has been timing out in the builds `Trilinos-atdm-hansen-shiller-gnu-debug-serial` and `Trilinos-atdm-hansen-shiller-gnu-opt-serial` since 5/30/2018.  (That query also shows this is the only Stratimikos test that has failed in any of the promoted "ATDM" builds since 5/20/2018.)

[This query](https://testing-vm.sandia.gov/cdash/queryTests.php?project=Trilinos&date=2018-06-11&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-&field2=buildname&compare2=61&value2=Trilinos-atdm-hansen-shiller-gnu-debug-serial&field3=buildstarttime&compare3=84&value3=2018-06-11&field4=buildstarttime&compare4=83&value4=2018-05-20&field5=testname&compare5=61&value5=Stratimikos_test_aztecoo_thyra_driver_MPI_1) shows that the test `Stratimikos_test_aztecoo_thyra_driver_MPI_1` went from passing at under 21s every day to timing out at 10 minutes every day since 5/29/2018 (but it did pass once taking 9m 56s 930ms on 6/8/2018, the only time it did not time-out since 5/29/2018).

What changed from 5/29/2018 to 5/30/2018?  Looking at the updates pulled in for the build `Trilinos-atdm-hansen-shiller-gnu-debug-serial` with build stamp `20180530-0400-ATDM` shown at:

* https://testing-vm.sandia.gov/cdash/viewNotes.php?buildid=3558860#!#note0

it seems like only commits that could have impacted this were:

```
c9ccf7d:  Switch from srun to salloc on hansen/shiller (TRIL-209)
Author: Roscoe A. Bartlett <rabartl@sandia.gov>
Date:   Tue May 29 08:35:16 2018 -0600

M	cmake/ctest/drivers/atdm/shiller/local-driver.sh
M	cmake/std/atdm/README.md

c840658:  Switch to CMake 3.11.2, Ninja 1.8.2 and all-at-once mode on hansen/shiller (TRIL-209)
Author: Roscoe A. Bartlett <rabartl@sandia.gov>
Date:   Tue May 29 08:12:42 2018 -0600

M	cmake/ctest/drivers/atdm/shiller/local-driver.sh
M	cmake/std/atdm/shiller/environment.sh
```

There are no other commits that I could see that could impact this AztecOO test.  So it looks like moving to CMake/CTest 3.11.2 and to the all-at-once approach triggered this large increase in runtime for the test `Stratimikos_test_aztecoo_thyra_driver_MPI_1` for the build `Trilinos-atdm-hansen-shiller-gnu-debug-serial`.  This may have been a result of having more tests running while this Stratimikos test is running.

Looking in [this query](https://testing-vm.sandia.gov/cdash/queryTests.php?project=Trilinos&date=2018-06-10&filtercombine=and&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-&field2=testname&compare2=61&value2=Stratimikos_test_aztecoo_thyra_driver_MPI_1), we can see that the test `Stratimikos_test_aztecoo_thyra_driver_MPI_1` timed-out in the build `Trilinos-atdm-hansen-shiller-gnu-debug-serial` yesterday 6/10/2018 but it took upwards of 2.5 to 3.5 minutes to run in the CUDA builds.  Ohterwise, this test did not take any longer than 22s to run in all of the other ATDM builds of Trilinos.  And what is also interesting is that query showed that this test passed in 4s 460ms for the build `Trilinos-atdm-hansen-shiller-intel-debug-serial` also run on 'hansen'.  How can the same test pass on an `intel-debug-serial` build in under 5 seconds but then time out at 10 minutes for a `gnu-debug-serial` build on the same hardware with the same MPI implementation and settings?

For that matter, [this query](https://testing-vm.sandia.gov/cdash/queryTests.php?project=Trilinos&date=2018-06-10&filtercombine=and&filtercount=1&showfilters=1&field1=testname&compare1=61&value1=Stratimikos_test_aztecoo_thyra_driver_MPI_1) shows that other than the CUDA builds of Trilinos and the yet-to-be-cleaned-up 'mutrinos' build `Trilinos-atdm-mutrino-intel-debug-openmp`, this test did not take any longer than 22s to run in any of the 46 Trilinos builds where this test ran yesterday.  On some platforms, this test completed in less than 2s! 

This is very strange behavior for a test.  There must be some type of machine or system usage issue going on here.  But why would it impact a `gnu-debug-serial` build but not an `intel-debug-serial` build on the same machine?

## Steps to reproduce

Following the instructions at:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#shillerhansen

one can log on to 'hansen' or 'shiller', clone Trilinos and get on to the 'develop' branch, and then do:

```
$ cd <some_build_dir>/

$ source $TRILINOS_DIR/cmake/std/atdm/load-env.sh intel-opt-openmp

$ cmake \
  -GNinja \
  -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
  -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_Stratimikos=ON \
  $TRILINOS_DIR

$ make NP=16

$ salloc ctest -j16
```

I did this on 'shiller' but unfortunately all of the Stratimikos tests passed:

```
  100% tests passed, 0 tests failed out of 40
  
  Subproject Time Summary:
  Stratimikos    = 256.50 sec*proc (40 tests)
  
  Total Test time (real) =  20.84 sec
```

Therefore, I was not able to reproduce this behavior on 'shiller'.  Therefore, this must be some type of system issue.

**Comment by bartlettroscoe** [comment]
Now, we could invest time to see why this test is taking so long to run for this one build.  But this is a test for AztecOO for a `gnu-debug-serial` build.  I don't think any of the ATDM codes are using AztecOO or care much about it for a `gnu-debug-serial`.

Therefore, in the interest of time and since there are bigger fish to fry, I am going disable this test for these GNU builds `Trilinos-atdm-hansen-shiller-gnu-debug-serial` and `Trilinos-atdm-hansen-shiller-gnu-opt-serial` on 'hansen' and move on.

**Comment by mhoemmen** [comment]
Sierra cares that the test _builds_, but it's less important that the test _run_ on GPU platforms.

**Comment by bartlettroscoe** [comment]
> Sierra cares that the test builds, but it's less important that the test run on GPU platforms.

@mhoemmen, the build of the test will not be disabled, just the running of this test and just for the builds `Trilinos-atdm-hansen-shiller-gnu-debug-serial` and `Trilinos-atdm-hansen-shiller-gnu-opt-serial` on 'hansen' and that is it.  Sierra should build and run whatever Trilinos tests it things are necessary.

My guess is that the GNU-built executables are binding to the same cores on this machine due to the MPI arguments: `-map-by socket:PE=16 --oversubscribe`.  We have had to scrap those types of arguments on all of the other platforms in order to let the processes and the cores float around.  I guess is that we could make this timeout go away by changing these.  But that involves a lot experimentation and a lot of runtime for the entire Trilinos test suite.  And 'shiller' is down till 6/14 and 'hansen' is hammered running our builds all day.

**Comment by bartlettroscoe** [comment]
This test was shown missing for the first time yesterday in these two builds on 'hansen' at:

* https://testing-vm.sandia.gov/cdash/viewTest.php?onlyfailed&buildid=3607605
* https://testing-vm.sandia.gov/cdash/viewTest.php?onlypassed&buildid=3608796

I will mark this as "Disabled Tests" and "Stalled" to get it off of the main list.
