### ISSUE TITLE
ShyLU: Frosch tests incorrectly allow *petra objects to persist past MPI_Finalize

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#2929]
Frosch (not sure if capitalized right) tests incorrectly allow Epetra and Tpetra objects to persist past MPI_Finalize.  They also call `MPI_Comm_split` without calling `MPI_Comm_free` on the resulting communicator.  This may be causing errors that hinder progress on #2483.  Frosch tests may be failing on processes other than Process 0, but the tests do not correctly use the Teuchos unit test framework in order to catch errors on other processes.

@trilinos/tpetra @trilinos/epetra @trilinos/belos @trilinos/shylu @MicheldeMessieres

## Examples

The following test creates both Epetra and Tpetra objects at the same scope as `main()`:

https://github.com/trilinos/Trilinos/blob/1f66625b666138226fb6412fa19afcc35402b61d/packages/shylu/shylu_dd/frosch/test/TestImport_Tpetra/main.cpp#L105

Other Frosch tests also do this.

## Recommended fix

1. Never create *petra objects at the same scope as main().  Always create them in an inner scope, so they fall out of scope before `MPI_Finalize`, `Kokkos::finalize`, or `Tpetra::finalize` are called.  For example:

```c++
int main (int argc, char* argv[]) {
  MPI_Init (&argc, &argv);
  {
    Epetra_MpiComm epetraComm (MPI_COMM_WORLD);
    // ... the rest of your test goes here ...
  } 
  // no Trilinos object may exist past here --
  // no *petra object, no Belos solver, NOTHING

  MPI_Finalize ();
  return EXIT_SUCCESS;
}
```

2. Always call `MPI_Comm_free` on an `MPI_Comm` created using one of the communicator constructors like `MPI_Comm_split`.  [Here is an example](https://github.com/trilinos/Trilinos/blob/1f66625b666138226fb6412fa19afcc35402b61d/packages/shylu/shylu_dd/frosch/test/TestLaplacian_Epetra/main.cpp#L121) of a Frosch test that violates this requirement.

3. Make the tests catch errors on processes other than Process 0.  For example, do an all-reduce on a success code.  (Another option would be to rewrite the tests using the Teuchos unit test framework, and tell the test to do an all-reduce at the end.  [Here is an example.](https://github.com/trilinos/Trilinos/blob/1f66625b666138226fb6412fa19afcc35402b61d/packages/tpetra/core/test/MultiVectorFiller/CMakeLists.txt#L19))

## Motivation and Context

This blocks #2483.

## Related Issues

* Blocks #2483

**Comment by mhoemmen** [comment]
If I remember right, @searhein originally wrote these tests.  I'll be happy to work with you to show you how to change these tests.

**Comment by searhein** [comment]
@mhoemmen Thank you for pointing this out. I am currently working on a lot of new features and changes for FROSch anyway. Therefore, I am planning to submit a major pull request within the next few days. I would like to include your suggestions into that pull request. Would this be feasible?

**Comment by mhoemmen** [comment]
@searhein It would be super helpful if you could split the test fixes into a separate PR and do them first.  Otherwise, would it be OK for me to disable those tests for now?  I don't mean to create work for you -- if you plan on rewriting a lot of code anyway, then it wouldn't hurt to disable them for now and reenable them (with changes) in your PR.

**Comment by searhein** [comment]
@mhoemmen OK. If this is kind of urgent, we can disable the tests for now since I am on a conference this week and I won't be able to submit the pull request before Monday. I already did 99% of the implementation, but I still need to check some parts of the code before submitting the pull request next week. Thank you.

**Comment by mhoemmen** [comment]
@searhein Sorry about the late reply -- it turns out there was a separate issue that this one was obfuscating.  I'm awaiting test results to see if we need to disable these tests.  Thanks!
