### ISSUE TITLE
MueLu: error building RefMaxwell on CUDA when KokkosRefactor=ON

### ISSUE THREAD

**Issue by aprokop** [trilinos/Trilinos#2931]
@trilinos/muelu @cgcgcg 

## Expectations

Muelu builds using CUDA.

## Current Behavior

The build fails using CUDA 8.0 with the following errors:
```
/home/xap/code/trilinos/packages/muelu/adapters/xpetra/MueLu_RefMaxwell_def.hpp(652): error: device code does not support exception handling                                                  

/home/xap/code/trilinos/packages/muelu/adapters/xpetra/MueLu_RefMaxwell_def.hpp(676): error: device code does not support exception handling 
```

The code in question is obviously off as it does
```c++
  TEUCHOS_ASSERT_EQUALITY(P11colind(m),jNew);                                                                                                               
```
which could throw which is not possible on device.

Removing those lines makes the code compile, but a better solution is probably needed.

**Comment by cgcgcg** [comment]
@aprokop How about changing the compile guard to 
`#if def(HAVE_MUELU_DEBUG) && !def(HAVE_MUELU_CUDA)` 
for now?

**Comment by aprokop** [comment]
@cgcgcg If you are OK with it, I'm OK with it. Do you want me to test and do PR, or would your prefer to do it yourself?

**Comment by cgcgcg** [comment]
@aprokop If you want it to be changed quickly, then just do the PR, and I'll approve it. If it's not super urgent, I'll make a PR together with several other changes some time this week..
