### ISSUE TITLE
Xpetra: build error

### ISSUE THREAD

**Issue by jhux2** [trilinos/Trilinos#2944]
## Next Action Status:

Issue fixed in commit b73a7c5 pushed to 'develop'.  Next: Verify that build problem is gone for SPARC configuration ...

## Description

@micahahoward has reported errors building Trilinos master, SHA1 1f66625b66

```
In file included from /home/mhoward/codes/sparc/Trilinos/packages/xpetra/src/MultiVector/Xpetra_EpetraIntMultiVector.hpp(57),
                 from /home/mhoward/codes/sparc/Trilinos/packages/xpetra/src/MultiVector/Xpetra_MultiVectorFactory.hpp(59),
                 from /home/mhoward/codes/sparc/Trilinos/packages/xpetra/src/BlockedCrsMatrix/Xpetra_BlockedCrsMatrix.hpp(60), 
                 from /home/mhoward/codes/sparc/Trilinos/packages/xpetra/sup/Utils/Xpetra_MatrixMatrix.hpp(53),
                 from /home/mhoward/codes/sparc/Trilinos/packages/muelu/src/Utils/MueLu_Utilities_decl.hpp(76),
                 from /home/mhoward/codes/sparc/Trilinos/ats1-hsw_intel-17.0.4_mpich-7.7.0_static_opt_build/packages/muelu/src/MueLu_Utilities.hpp(1),
                 from /home/mhoward/codes/sparc/Trilinos/packages/muelu/src/MueCentral/MueLu_Level.hpp(68),
                 from /home/mhoward/codes/sparc/Trilinos/packages/muelu/src/MueCentral/MueLu_Factory.hpp(65),
                 from /home/mhoward/codes/sparc/Trilinos/packages/muelu/src/Smoothers/MueLu_SmootherPrototype_decl.hpp(52),
                 from /home/mhoward/codes/sparc/Trilinos/ats1-hsw_intel-17.0.4_mpich-7.7.0_static_opt_build/packages/muelu/src/MueLu_SmootherPrototype.hpp(1),
                 from /home/mhoward/codes/sparc/Trilinos/packages/muelu/src/Smoothers/MueLu_Amesos2Smoother_decl.hpp(56),
                 from /home/mhoward/codes/sparc/Trilinos/packages/muelu/src/Smoothers/MueLu_Amesos2Smoother_def.hpp(58),
                 from /home/mhoward/codes/sparc/Trilinos/ats1-hsw_intel-17.0.4_mpich-7.7.0_static_opt_build/packages/muelu/src/Utils/ExplicitInstantiation/MueLu_Amesos2Smoother.cpp(55):
/home/mhoward/codes/sparc/Trilinos/packages/epetra/src/Epetra_IntMultiVector.h(289): error #809: exception specification for virtual function "Epetra_IntMultiVector::~Epetra_IntMultiVector" is incompatible with that of overridden function "Epetra_Object::~Epetra_Object"
    virtual ~Epetra_IntMultiVector();
```

@trilinos/xpetra @lucbv

**Comment by jhux2** [comment]
The same error is reported to occur on all platforms.

**Comment by lucbv** [comment]
@jhux2 I do not see anything failing on any of the dashboard builds, including the ATDM builds.
What configuration is being used by SPARC for these builds?

**Comment by jhux2** [comment]
<details>
<summary>configure line</summary>

```
cmake \
   -D CMAKE_VERBOSE_MAKEFILE=FALSE \
   -D CMAKE_INSTALL_PREFIX:PATH=${TRILINOS_HOME}/${BUILD}_static_${BUILD_SUFFIX} \
   -D CMAKE_BUILD_TYPE:STRING=${BUILD_TYPE} \
   -D BUILD_SHARED_LIBS=OFF \
   -D TPL_FIND_SHARED_LIBS=OFF \
   -D Trilinos_LINK_SEARCH_START_STATIC=ON \
   -D CMAKE_SKIP_INSTALL_RPATH=ON \
   -D CMAKE_C_COMPILER="cc" \
   -D CMAKE_CXX_COMPILER="CC" \
   -D CMAKE_Fortran_COMPILER="ftn" \
   -D CMAKE_C_FLAGS="$EXTRA_C_FLAGS" \
   -D CMAKE_CXX_FLAGS="$EXTRA_CXX_FLAGS" \
   -D CMAKE_Fortran_FLAGS="$EXTRA_F_FLAGS" \
   -D CMAKE_EXE_LINKER_FLAGS="$LINK_FLAGS" \
   -D Trilinos_VERBOSE_CONFIGURE=FALSE \
   -D Trilinos_ENABLE_ALL_PACKAGES=OFF \
   -D Trilinos_ENABLE_SECONDARY_TESTED_CODE=OFF \
   -D Trilinos_ENABLE_TESTS=OFF \
   -D DART_TESTING_TIMEOUT:STRING="600" \
   -D Trilinos_ENABLE_EXPLICIT_INSTANTIATION=ON \
   -D Tpetra_INST_FLOAT=OFF \
   -D Tpetra_INST_DOUBLE=ON \
   -D Tpetra_INST_COMPLEX_FLOAT=OFF \
   -D Tpetra_INST_COMPLEX_DOUBLE=OFF \
   -D Tpetra_INST_INT_INT=ON \
   -D Tpetra_INST_INT_LONG=OFF \
   -D Tpetra_INST_INT_UNSIGNED=OFF \
   -D Tpetra_INST_INT_LONG_LONG=ON \
   -D Teuchos_ENABLE_LONG_LONG_INT=ON \
   -D Teuchos_ENABLE_COMPLEX=OFF \
   -D Zoltan_ENABLE_ULLONG_IDS=ON \
   -D Trilinos_ENABLE_OpenMP=ON \
   -D TPL_ENABLE_Pthread=OFF \
   -D Trilinos_ENABLE_Teuchos=ON \
   -D Trilinos_ENABLE_Epetra=ON \
   -D Trilinos_ENABLE_EpetraExt=ON \
   -D Trilinos_ENABLE_AztecOO=ON \
   -D Trilinos_ENABLE_Amesos=ON \
   -D Trilinos_ENABLE_Stratimikos=ON \
   -D Trilinos_ENABLE_Anasazi=ON \
   -D Anasazi_ENABLE_RBGen=ON \
   -D Trilinos_ENABLE_Ifpack=ON \
   -D Trilinos_ENABLE_ML=ON \
   -D Trilinos_ENABLE_Teko=ON \
   -D Trilinos_ENABLE_NOX=ON \
   -D Trilinos_ENABLE_Thyra=ON \
   -D Trilinos_ENABLE_Rythmos=OFF \
   -D Trilinos_ENABLE_Sacado=ON \
   -D Trilinos_ENABLE_Stokhos=OFF \
   -D Trilinos_ENABLE_Panzer=OFF \
   -D Trilinos_ENABLE_Tpetra=ON \
   -D Tpetra_INST_SERIAL=OFF \
   -D Tpetra_INST_OPENMP=ON \
   -D Trilinos_ENABLE_Belos=ON \
   -D Trilinos_ENABLE_Amesos2=ON \
   -D Amesos2_ENABLE_KLU2=ON \
   -D Trilinos_ENABLE_Ifpack2=ON \
   -D Trilinos_ENABLE_MueLu=ON \
   -D Trilinos_ENABLE_Zoltan2=ON \
   -D Trilinos_ENABLE_STKMesh=OFF \
   -D Trilinos_ENABLE_STKIO=OFF \
   -D Trilinos_ENABLE_STKTransfer=ON \
   -D Trilinos_ENABLE_STKSearch=ON \
   -D Trilinos_ENABLE_STKUtil=ON \
   -D Trilinos_ENABLE_STKTopology=OFF \
   -D Trilinos_ENABLE_ShyLU=ON \
   -D Trilinos_ENABLE_ShyLU_DDCore=ON \
   -D Trilinos_ENABLE_ShyLU_NodeHTS=ON \
   -D ShyLU_NodeHTS_ENABLE_TESTS=OFF \
   -D Trilinos_ENABLE_Kokkos=ON \
   -D Trilinos_ENABLE_KokkosCore=ON \
   -D Kokkos_ENABLE_Serial=OFF \
   -D Kokkos_ENABLE_OpenMP=ON \
   -D Kokkos_ENABLE_Pthread=OFF \
   -D Kokkos_ENABLE_Cuda=OFF \
   -D Kokkos_ENABLE_Cuda_UVM=OFF \
   -D Trilinos_ENABLE_SEACAS=ON \
   -D SEACAS_SOURCE_DIR_OVERRIDE:STRING=seacas/packages/seacas \
   -D TPL_ENABLE_X11=OFF \
   -D TPL_ENABLE_Matio=OFF \
   -D Trilinos_ENABLE_Gtest=ON \
   -D Trilinos_ENABLE_TriKota=ON \
   -D DAKOTA_ENABLE_TESTS=OFF \
   -D Trilinos_ENABLE_ROL=ON \
   -D TPL_ENABLE_MPI=ON \
   -D MPI_USE_COMPILER_WRAPPERS=OFF \
   -D MPI_BASE_DIR:PATH=${MPI_DIR} \
   -D MPI_EXEC:PATH="mpirun" \
   -D MPI_EXEC_MAX_NUMPROCS:STRING="8" \
   -D MPI_EXEC_NUMPROCS_FLAG:STRING="-np" \
   -D TPL_ENABLE_BinUtils=ON \
   -D TPL_ENABLE_BLAS=ON \
   -D BLAS_LIBRARY_DIRS:PATH="${BLAS_DIR}/mkl/lib/intel64;${BLAS_DIR}/compiler/lib/intel64" \
   -D BLAS_LIBRARY_NAMES:STRING="mkl_intel_lp64;mkl_intel_thread;mkl_core;iomp5" \
   -D TPL_ENABLE_LAPACK=ON \
   -D LAPACK_LIBRARY_DIRS:PATH="${LAPACK_DIR}/mkl/lib/intel64;${LAPACK_DIR}/compiler/lib/intel64" \
   -D LAPACK_LIBRARY_NAMES:STRING="mkl_intel_lp64;mkl_intel_thread;mkl_core;iomp5" \
   -D TPL_ENABLE_Boost=ON \
   -D Boost_INCLUDE_DIRS:PATH=${BOOST_DIR}/include \
   -D TPL_ENABLE_BoostLib=ON \
   -D BoostLib_INCLUDE_DIRS:PATH=${BOOST_DIR}/include \
   -D BoostLib_LIBRARY_DIRS:PATH=${BOOST_DIR}/lib \
   -D HDF5_ROOT:PATH=${HDF5_DIR} \
   -D HDF5_NO_SYSTEM_PATHS=ON \
   -D PNetCDF_ROOT:PATH=${PNETCDF_DIR} \
   -D TPL_ENABLE_Netcdf=ON \
   -D NetCDF_ROOT:PATH=${NETCDF_DIR} \
   -D TPL_ENABLE_CGNS=ON \
   -D CGNS_INCLUDE_DIRS:PATH="${CGNS_DIR}/include" \
   -D CGNS_LIBRARY_DIRS:PATH="${CGNS_DIR}/lib" \
   -D CGNS_LIBRARY_NAMES:STRING="cgns" \
   -D TPL_ENABLE_METIS=ON \
   -D METIS_INCLUDE_DIRS:PATH=${METIS_DIR}/include \
   -D METIS_LIBRARY_DIRS:PATH=${METIS_DIR}/lib \
   -D TPL_ENABLE_ParMETIS=ON \
   -D ParMETIS_INCLUDE_DIRS:PATH=${PARMETIS_DIR}/include \
   -D ParMETIS_LIBRARY_DIRS:PATH=${PARMETIS_DIR}/lib \
   -D TPL_ENABLE_SuperLUDist=ON \
   -D SuperLUDist_INCLUDE_DIRS:PATH=${SUPERLUDIST_DIR}/SRC \
   -D SuperLUDist_LIBRARY_DIRS:PATH=${SUPERLUDIST_DIR}/lib \
   -D SuperLUDist_LIBRARY_NAMES:STRING="superlu_dist_4.2" \
   -D Trilinos_EXTRA_LINK_FLAGS:STRING="-L${MPI_DIR}/lib -lmpich" \
   ${EXTRA_ARGS} \
   ${TRILINOS_HOME}
```
</details>

**Comment by mhoemmen** [comment]
Huh, neither of the destructors _have_ an exception specifier list.

**Comment by jhux2** [comment]
Maybe this is relevant?  https://software.intel.com/en-us/forums/intel-c-compiler/topic/676232

**Comment by jhux2** [comment]
I'm building on mutrino now to see if I can reproduce.

**Comment by jhux2** [comment]
PR pending that fixes this.

**Comment by bartlettroscoe** [comment]
Looks like the PR #2948 addresses this.

@micahahoward and @jhux2,

Does this error only manifest itself with the `SuperLUDist` TPL enabled?  That is important to know because the current ATDM Trilinos configuration (which is tracking the EMPIRE configuration of Trilinos) does **not** enable the `SuperLUDist` TPL.

**Comment by jhux2** [comment]
> Does this error only manifest itself with the SuperLUDist TPL enabled? That is important to know

@bartlettroscoe I'm not sure

**Comment by jhux2** [comment]
> Does this error only manifest itself with the SuperLUDist TPL enabled? That is important to know because the current ATDM Trilinos configuration (which is tracking the EMPIRE configuration of Trilinos) does not enable the SuperLUDist TPL.

@bartlettroscoe @micahahoward I looked into this a bit more.  SPARC is using SuperLU_dist version 4.2.  In that version, the header file `util_dist.h` defines the macro `Reduce`.  In SuperLU_dist version 5.4.0, the most current, the macro has been renamed to `SuperLU_Reduce`.

**Comment by jhux2** [comment]
@bartlettroscoe And SuperLU does not suffer from this problem, which would be why the error didn't show up on the Trilinos dashboard.

**Comment by bartlettroscoe** [comment]
>  In SuperLU_dist version 5.4.0, the most current, the macro has been renamed to SuperLU_Reduce.

Note that SEMS added the TPLs:

```
sems-superlu_dist/5.2.2/32bit_parallel                                                                                                                                              
sems-superlu_dist/5.2.2/64bit_parallel              
```

I think that means that we can add SuperLUDist to the Trilinos PR builds.  Does that version have this macro fixed as well?

@micahahoward, 

Can SPARC upgarde its version of SuperLUDist to 5.2.2 to match the SEMS version?  Updatding to 5.4.0 would likely be okay too.

**Comment by jhux2** [comment]
> I think that means that we can add SuperLUDist to the Trilinos PR builds. Does that version have this macro fixed as well?

@bartlettroscoe SuperLU_dist still has the `Reduce` macro.

**Comment by micahahoward** [comment]
We can try SuperLU-dist 5.3 but I can't spend any time figuring things out if it doesn't work for SPARC.

**Comment by jhux2** [comment]
> We can try SuperLU-dist 5.3 but I can't spend any time figuring things out if it doesn't work for SPARC.

@micahahoward If you switch versions, I wouldn't be surprised if there are namespace changes, etc. that will keep SPARC from compiling right out of the box.

**Comment by bartlettroscoe** [comment]
There is a SEMS-based build of Trilinos that EMPIRE is using shown [here](https://testing-vm.sandia.gov/cdash/index.php?project=Trilinos&date=2018-06-14&filtercount=1&showfilters=1&field1=buildname&compare1=65&value1=Trilinos-atdm-rhel6-) that uses a SEMS GCC 6.1.0 + OpenMPI 1.10.1 stack.  Therefore, if we want a single configuration of Trilinos that supports SPARC and EMPIRE, we will likely need to use that SuperLUDist version 5.2.2 on that platform.   Otherwise, we may consider some TPLs to be optional on some platforms (which I think we can do by looking for the `<TPL_NAME>_ROOT` env var and if it is not set, then we don't try to enable that TPL in the Trilinos build).  That would not be so bad in my opinion.  But it would still be nice to get Trilinos testing against SuperLUDist in PR testing and have the ATDM APPs use that version if possible.  (The more uniformity the better otherwise we need a bunch of ifdefs to deal with interface changes.)  Since SPARC is using an older version of SuperLUDist 4.2, hopefully upgrading to SuperLUDist 5.2.2 would not be a bad idea (assuming it works with SPARC).

Perhaps we can work toward building and installed SuperLUDist 5.2.2 on these platforms as we are getting ATDM Trilinos configuration stood up on these machines that support SPARC?  @micahahoward, who maintains the builds of the TPLs like SuperLUDist that SPARC is using on these various platforms?   And who can I ask these questions to so as not to take up your valuable time?

**Comment by nmhamster** [comment]
@micahahoward - you don't use the modules for SuperLUDIST on the test beds? Its OK if not, just want to check.

**Comment by micahahoward** [comment]
We did.  However, as a week ago we override this with our own.  The SuperLUDist bundled with the dev-pack was giving incorrect results on GPU systems.

**Comment by bartlettroscoe** [comment]
@micahahoward, is this issue resolved in your most current update of Trilinos?  Has SPARC accepted an updated of Trilinos since these fixing commits were made to the Trilinos 'develop' branch?

**Comment by mhoemmen** [comment]
@bartlettroscoe I'm pretty sure SPARC takes Trilinos updates from master.  Trilinos' master branch hasn't been updated for a month.

**Comment by bartlettroscoe** [comment]
@mhoemmen, has this issue been addressed yet?  Can we close this issue?

**Comment by mhoemmen** [comment]
I think this is OK; thanks Ross!
