### ISSUE TITLE
Problem in compiling Panzer_L2Projection.hpp

### ISSUE THREAD

**Issue by armarkos** [trilinos/Trilinos#2956]
I use `mpic++-mpich-clang60` compiler (from macports on 10.11.6) to compile Trilinos and I got the following error:
`/lib/script/temp/Trilinos/packages/panzer/disc-fe/src/Panzer_L2Projection.hpp:69:62: error: reference to type 'const Teuchos::RCP<panzer::WorksetContainer>' could not bind to an rvalue of type 'nullptr_t'
               const Teuchos::RCP<panzer::WorksetContainer>& worksetContainer = nullptr);`

**Comment by mhoemmen** [comment]
@trilinos/panzer @rppawlo

**Comment by rppawlo** [comment]
Fix is in PR #2962

**Comment by armarkos** [comment]
This is fixed now.
