### ISSUE TITLE
Xpetra: build error when float is enabled

### ISSUE THREAD

**Issue by Slaedr** [trilinos/Trilinos#2960]
Build failed with the following error:
```
Building CXX object packages/ifpack2/test/unit_tests/CMakeFiles/Ifpack2_AdditiveSchwarz.dir/Ifpack2_UnitTestMain.cpp.o
In file included from /home/aditya/Sources/Trilinos/packages/ifpack2/test/unit_tests/Ifpack2_UnitTestAdditiveSchwarz.cpp:60:
/home/aditya/Sources/Trilinos/packages/xpetra/src/Utils/Xpetra_Parameters.hpp: In member function ‘void Xpetra::Parameters::setCLP(Teuchos::CommandLineProcessor&)’:
/home/aditya/Sources/Trilinos/packages/xpetra/src/Utils/Xpetra_Parameters.hpp:138:48: error: ‘FLOAT_INT_LONGINT’ is not a member of ‘Xpetra’
       instOptionValues[nInstOptions] = Xpetra::FLOAT_INT_LONGINT;
                                                ^~~~~~~~~~~~~~~~~
/home/aditya/Sources/Trilinos/packages/xpetra/src/Utils/Xpetra_Parameters.hpp:138:48: note: suggested alternative: ‘FLOAT_INT_INT’
       instOptionValues[nInstOptions] = Xpetra::FLOAT_INT_LONGINT;
                                                ^~~~~~~~~~~~~~~~~
                                                FLOAT_INT_INT
```

@trilinos/Xpetra

## Expectations

Build completes.
## Current Behavior

Build fails.

## Possible Solution

Looking at line 138 of `Xpetra_Parameters.hpp`, it looks like a simple typo, though I may be wrong.

## Steps to Reproduce
Build with the configure script posted below.

## Your Environment

- Master branch, commit 4ca31cb7e8f950cfbba1a7addfec64dbb002a8e9
- Configure script:
```
cmake \
	-D CMAKE_C_COMPILER=mpicc \
	-D CMAKE_CXX_COMPILER=mpicxx \
	-D Trilinos_ENABLE_Fortran=OFF \
	-D Trilinos_ENABLE_FLOAT=ON \
	-D Trilinos_ENABLE_CXX11=ON \
	-D Trilinos_ENABLE_OpenMP=ON \
	-D Trilinos_ENABLE_THREAD_SAFE=ON \
	-D Trilinos_ENABLE_TESTS=ON \
	-D BUILD_SHARED_LIBS=ON \
	-D Trilinos_ENABLE_EXPLICIT_INSTANTIATION=ON \
	-D TPL_ENABLE_MPI=ON \
	-D TPL_ENABLE_BLAS=ON \
	-D TPL_ENABLE_LAPACK=ON \
	\
	-DTrilinos_ENABLE_Teuchos=ON \
	-DTrilinos_ENABLE_Thyra=ON \
	-DTrilinos_ENABLE_Epetra=ON \
	-DTrilinos_ENABLE_Kokkos=ON \
	-DTrilinos_ENABLE_Tpetra=ON \
	-DTpetra_INST_SERIAL:BOOL=ON \
	-DTrilinos_ENABLE_AztecOO=ON \
	-DTrilinos_ENABLE_Ifpack=ON \
	-DTrilinos_ENABLE_Ifpack2=ON \
	-DTrilinos_ENABLE_Belos=ON \
	-DTrilinos_ENABLE_MueLu=ON \
	-DTrilinos_ENABLE_ML=ON \
	\
	-DCMAKE_BUILD_TYPE=Release \
	-DCMAKE_INSTALL_PREFIX=/home/aditya/Programs/Trilinos \
	../Trilinos
``` 
- Ubuntu 18.04
- GCC 8.1, OpenMPI 3.1

## Additional Information

The build succeeds if `-D Trilinos_ENABLE_FLOAT=ON ` is removed.

**Comment by Slaedr** [comment]
Alright, thanks!

**Comment by cgcgcg** [comment]
@Slaedr Could you pull and see if this is fixed in the develop branch?

**Comment by cgcgcg** [comment]
@Slaedr It's good that it builds :-)
If you want to check that things are working, you could run `MueLu_Driver.exe` in packages/muelu/test/scaling . You might have to add `MueLu_ENABLE_TESTS=ON` to your configure script for the executable to show up. You can pass the flag `--instantiation=FLOAT_INT_INT` to make sure that floats are used.

Develop is merged into master fairly frequently, the last time was just 3 days ago..

**Comment by Slaedr** [comment]
@cgcgcg Great, thanks. MueLu actually did not build for me on the  develop branch - there was some build issue related to assignment of one type to another. So tomorrow I'll build my fork of master instead (with your fix) and see if the `MueLu_Driver.exe` works.

**Comment by cgcgcg** [comment]
@Slaedr Oh, that shouldn't happen. Can you tell me the error message?

**Comment by cgcgcg** [comment]
Ah, it's probably this one:
https://testing.sandia.gov/cdash/viewBuildError.php?buildid=3638262

**Comment by Slaedr** [comment]
Yes, these look similar to the errors I had got.

Unfortunately I did not save the errors. Now I'm away from my work computer, and building MueLu on my laptop with 8GB RAM makes it hang.

**Comment by Slaedr** [comment]
@cgcgcg  Here's the error I got. Unfortunately, I got the error even on master, after merging develop. It's in an example though; most of the source files are built.
```
Building CXX object packages/muelu/example/advanced/separatesetups/CMakeFiles/MueLu_SeparateSetups.dir/SeparateSetups.cpp.o
/home/akashi/Source-codes/Slaedr-trilinos/packages/muelu/example/advanced/multiplesolve/ReuseSequence.cpp: In instantiation of ‘int main_(Teuchos::CommandLineProcessor&, Xpetra::UnderlyingLib&, int, char**) [with Scalar = float; LocalOrdinal = int; GlobalOrdinal = int; Node = Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP>]’:
/home/akashi/Source-codes/Slaedr-trilinos/packages/muelu/example/advanced/multiplesolve/../../../test/unit_tests/MueLu_Test_ETI.hpp:157:89:   required from here
/home/akashi/Source-codes/Slaedr-trilinos/packages/muelu/example/advanced/multiplesolve/ReuseSequence.cpp:514:9: error: conversion from ‘double’ to ‘MueLu::Hierarchy<float, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP> >::ConvData’ is ambiguous
         H->Iterate(*B, *X, tol);
         ^
In file included from /home/akashi/Source-codes/Slaedr-trilinos-build/packages/muelu/src/MueLu_Hierarchy.hpp:1:0,
                 from /home/akashi/Source-codes/Slaedr-trilinos/packages/muelu/src/Interface/../Headers/MueLu.hpp:69,
                 from /home/akashi/Source-codes/Slaedr-trilinos/packages/muelu/example/advanced/multiplesolve/ReuseSequence.cpp:58:
/home/akashi/Source-codes/Slaedr-trilinos/packages/muelu/src/Interface/../MueCentral/MueLu_Hierarchy_decl.hpp:115:7: note: candidate: MueLu::Hierarchy<Scalar, LocalOrdinal, GlobalOrdinal, Node>::ConvData::ConvData(MueLu::Hierarchy<Scalar, LocalOrdinal, GlobalOrdinal, Node>::MagnitudeType) [with Scalar = float; LocalOrdinal = int; GlobalOrdinal = int; Node = Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP>; MueLu::Hierarchy<Scalar, LocalOrdinal, GlobalOrdinal, Node>::MagnitudeType = float]
       ConvData(MagnitudeType tol)             : maxIts_(10000),   tol_(tol) { }
       ^~~~~~~~
/home/akashi/Source-codes/Slaedr-trilinos/packages/muelu/src/Interface/../MueCentral/MueLu_Hierarchy_decl.hpp:114:7: note: candidate: MueLu::Hierarchy<Scalar, LocalOrdinal, GlobalOrdinal, Node>::ConvData::ConvData(MueLu::Hierarchy<Scalar, LocalOrdinal, GlobalOrdinal, Node>::LO) [with Scalar = float; LocalOrdinal = int; GlobalOrdinal = int; Node = Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP>; MueLu::Hierarchy<Scalar, LocalOrdinal, GlobalOrdinal, Node>::LO = int]
       ConvData(LO maxIts)                     : maxIts_(maxIts),  tol_(-STS::magnitude(STS::one())) { }
       ^~~~~~~~
In file included from /home/akashi/Source-codes/Slaedr-trilinos-build/packages/muelu/src/MueLu_Hierarchy.hpp:1:0,
                 from /home/akashi/Source-codes/Slaedr-trilinos/packages/muelu/src/Interface/../Headers/MueLu.hpp:69,
                 from /home/akashi/Source-codes/Slaedr-trilinos/packages/muelu/example/advanced/multiplesolve/ReuseSequence.cpp:58:
/home/akashi/Source-codes/Slaedr-trilinos/packages/muelu/src/Interface/../MueCentral/MueLu_Hierarchy_decl.hpp:267:16: note:   initializing argument 3 of ‘MueLu::ReturnType MueLu::Hierarchy<Scalar, LocalOrdinal, GlobalOrdinal, Node>::Iterate(const MultiVector&, MueLu::Hierarchy<Scalar, LocalOrdinal, GlobalOrdinal, Node>::MultiVector&, MueLu::Hierarchy<Scalar, LocalOrdinal, GlobalOrdinal, Node>::ConvData, bool, MueLu::Hierarchy<Scalar, LocalOrdinal, GlobalOrdinal, Node>::LO) [with Scalar = float; LocalOrdinal = int; GlobalOrdinal = int; Node = Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP>; MueLu::Hierarchy<Scalar, LocalOrdinal, GlobalOrdinal, Node>::MultiVector = Xpetra::MultiVector<float, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP> >; MueLu::Hierarchy<Scalar, LocalOrdinal, GlobalOrdinal, Node>::LO = int]’
     ReturnType Iterate(const MultiVector& B, MultiVector& X, ConvData conv = ConvData(),
                ^~~~~~~
```

**Comment by Slaedr** [comment]
Though we don't need it at the moment, we want to look at preconditioning in low-precision to take better advantage of the hardware. Our preconditioners tend to be coarse approximations anyway, so the hope is that lower precision will not affect convergence noticeably. I understand that casting will be an overhead, but it might be worth it. To me, one of the advantages of Kokkos/Tpetra/Ifpack2/MueLu/Belos is the (potential) ability to mix scalar types as needed in a clean and safe manner through C++ template metaprogramming.

Since I'm only getting started with Trilinos, I should probably forget about floats for now and come back later.

**Comment by mhoemmen** [comment]
@Slaedr We don't do a lot of mixed-precision testing, but I do try to maintain the capability in reserve.  If you want to do mixed-precision `apply()` for sparse matrix-vector multiply or preconditioners, then you might like to take a look at `Tpetra::CrsMatrixMultiplyOp`: https://github.com/trilinos/Trilinos/blob/master/packages/tpetra/core/src/Tpetra_CrsMatrixMultiplyOp.hpp

**Comment by Slaedr** [comment]
@mhoemmen Oh that's very cool! So you already have mixed precision capability in `CrsMatrix` and it needs to be accessed through `CrsMatrixMultiplyOp`. I'll try it out after I get my code working with Trilinos.

**Comment by mhoemmen** [comment]
@Slaedr "Mixed-precision capability" means that you can do sparse matrix-vector multiply with vectors of different precisions than the matrix.  However, you would still need to build some code infrastructure manually in order to get a mixed-precision preconditioned solve.  So, yes, but it would take some work on your part.

**Comment by Slaedr** [comment]
@mhoemmen  Oh yes, I understand. It's just nice that the C++ language aspects of implementing it are already in place, as far as sparse mat vec and triangular solves are concerned. Thanks for the tip.

**Comment by mhoemmen** [comment]
It looks like this has been fixed.  I will close for now.  Please reopen if this has not been fixed.  Thanks!  See also #4080.
