### ISSUE TITLE
Tests Belos_resolve_[cg,gmres]_hb_MPI_4 failing on ATDM builds on 'chama' and 'serrano'

### ISSUE THREAD

**Issue by fryeguy52** [trilinos/Trilinos#2965]
## Next Action Status

Tests were disabled in commits cbb56a7 and 5be802c merged to 'develop' in 6/25/2018 in PR #3011.  Commit that should fix the tests were pushed to develop in commit dcbfd13e3aad9f8be5baf9ebe964e6bc1353aea5 and PR #3098 was merged on 7/14/2018 that re-enables these tests.  Next: Watch to see that these tests are running and let run for a few weeks before closing issue on 8/15/2018 ...

## Description

The test `Belos_resolve_cg_hb_MPI_4` is failing intermittently on the `serrano` and `chama` ATDM builds.  Here is a history of that test for the effected builds.

[Trilinos-atdm-chama-intel-opt-openmp](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&date=&filtercount=3&showfilters=1&filtercombine=and&field1=testname&compare1=63&value1=Belos_resolve_cg_hb_MPI_4&field2=buildname&compare2=61&value2=Trilinos-atdm-chama-intel-opt-openmp&field3=buildstarttime&compare3=84&value3=now)
[Trilinos-atdm-chama-intel-debug-openmp](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&date=&filtercount=3&showfilters=1&filtercombine=and&field1=testname&compare1=63&value1=Belos_resolve_cg_hb_MPI_4&field2=buildname&compare2=61&value2=Trilinos-atdm-chama-intel-debug-openmp&field3=buildstarttime&compare3=84&value3=now)
[Trilinos-atdm-serrano-intel-opt-openmp](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&date=&filtercount=3&showfilters=1&filtercombine=and&field1=testname&compare1=63&value1=Belos_resolve_cg_hb_MPI_4&field2=buildname&compare2=61&value2=Trilinos-atdm-serrano-intel-opt-openmp&field3=buildstarttime&compare3=84&value3=now)
[Trilinos-atdm-serrano-intel-debug-openmp](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&date=&filtercount=3&showfilters=1&filtercombine=and&field1=testname&compare1=63&value1=Belos_resolve_cg_hb_MPI_4&field2=buildname&compare2=61&value2=Trilinos-atdm-serrano-intel-debug-openmp&field3=buildstarttime&compare3=84&value3=now)

```
Fail Reason | Required regular expression not found.Regex=[End Result: TEST PASSED<br /> ]
```

```
End Result: TEST FAILED
srun: error: ser403: task 0: Exited with exit code 1
```

[Full test output on CDash](https://testing.sandia.gov/cdash/testDetails.php?test=49643694&build=3640224)

## Definition of Done
The test is either reliably passing or we disable it for these particular builds

## Steps to Reproduce
On either `serrano` or `chama` just clone trilinos and run the following commands.  It is failing randomly so it may pass or it may not.  It appears to fail more frequently on `serrano` so it may be easier to reproduce there.
```
export JOB_NAME=Trilinos-atdm-intel-debug-openmp
export TRILINOS_DIR=<Wherever you cloned Trilinos>

source $TRILINOS_DIR/cmake/std/atdm/load-env.sh $JOB_NAME

cmake \
-DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
-DTrilinos_ENABLE_TESTS=ON \
-DTrilinos_ENABLE_Belos=ON \
$TRILINOS_DIR

make -j16
ctest -j16
```

## Your Environment
The environment will be set up automatically by running the commands given above.

**Comment by fryeguy52** [comment]
@bartlettroscoe, I just created this issue FYI

**Comment by bartlettroscoe** [comment]
CC: @trilinos/belos, @srajama1 (Linear Solver Product Lead)

A little more info about these failures ...

From looking at [this query](https://testing-vm.sandia.gov/cdash/queryTests.php?project=Trilinos&date=2018-06-18&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=64&value1=test-Trilinos_pullrequest_&field2=testname&compare2=61&value2=Belos_resolve_cg_hb_MPI_4) yesterday, the only builds where this test seems to be failing are the builds:

* `Trilinos-atdm-chama-intel-debug-openmp` on 'chama'
* `Trilinos-atdm-serrano-intel-opt-openmp` on 'serrano'

and in no other builds.  Interestingly, that query shows that this test **passes** in the other Intel builds on those machines:

* `Trilinos-atdm-chama-intel-opt-openmp` on 'chama'
* `Trilinos-atdm-serrano-intel-debug-openmp` on 'serrano'

I don't every think I have seem this behavior before (but that is why we need to be testing on 'serrano' and 'chama', because they behave differently).

Looking at the test output for this test when it fail for the [build  Trilinos-atdm-chama-intel-debug-openmp](https://testing-vm.sandia.gov/cdash/testDetails.php?test=48771067&build=3625525), it shows:

```
...

Belos::StatusTestGeneralOutput: Passed
  (Num calls,Mod test,State test): (1346, 1, Passed)
   Passed.......OR Combination -> 
     OK...........Number of Iterations = 1345 < 1805
     Converged....(2-Norm Imp Res Vec) / (2-Norm Res0)
                  residual [ 0 ] = 8.71716e-06 < 1e-05

==========================================================================================================================================

                                                  TimeMonitor results over 4 processors

Timer Name                                                    MinOverProcs      MeanOverProcs     MaxOverProcs      MeanOverCallCounts    
------------------------------------------------------------------------------------------------------------------------------------------
Belos Resolve w/ New Label: BlockCGSolMgr total solve time    0.08144 (1)       0.08145 (1)       0.08146 (1)       0.08145 (1)           
Number of iterations performed for this solve (new solver): 1345
Number of iterations performed for this solve (new solver): 1345
Number of iterations performed for this solve (new solver): 1345
Belos Resolve w/ New Label: DGKS[2]: Ortho (Inner Product)    0 (0)             0 (0)             0 (0)             0 (0)                 
Belos Resolve w/ New Label: DGKS[2]: Ortho (Norm)             0 (0)             0 (0)             0 (0)             0 (0)                 
Belos Resolve w/ New Label: DGKS[2]: Ortho (Update)           0 (0)             0 (0)             0 (0)             0 (0)                 
Belos Resolve w/ New Label: DGKS[2]: Orthogonalization        0 (0)             0 (0)             0 (0)             0 (0)                 
Belos Resolve w/ New Label: Operation Op*x                    0.03089 (1346)    0.03322 (1346)    0.03492 (1346)    2.468e-05 (1346)      
Belos Resolve w/ New Label: Operation Prec*x                  0 (0)             0 (0)             0 (0)             0 (0)                 
Belos Resolve: BlockCGSolMgr total solve time                 0.0799 (1)        0.07998 (1)       0.08001 (1)       0.07998 (1)           
Belos Resolve: DGKS[2]: Ortho (Inner Product)                 0 (0)             0 (0)             0 (0)             0 (0)                 
Belos Resolve: DGKS[2]: Ortho (Norm)                          0 (0)             0 (0)             0 (0)             0 (0)                 
------------------------------------------------------------------------------------------------------------------------------------------
Belos Resolve: DGKS[2]: Ortho (Update)                        0 (0)             0 (0)             0 (0)             0 (0)                 
Belos Resolve: DGKS[2]: Orthogonalization                     0 (0)             0 (0)             0 (0)             0 (0)                 
Belos Resolve: Operation Op*x                                 0.03008 (1346)    0.03215 (1346)    0.03389 (1346)    2.388e-05 (1346)      
Belos Resolve: Operation Prec*x                               0 (0)             0 (0)             0 (0)             0 (0)                 
Belos: BlockCGSolMgr total solve time                         0.1893 (2)        0.1893 (2)        0.1893 (2)        0.09466 (2)           
Belos: DGKS[2]: Ortho (Inner Product)                         0 (0)             0 (0)             0 (0)             0 (0)                 
Belos: DGKS[2]: Ortho (Norm)                                  0 (0)             0 (0)             0 (0)             0 (0)                 
Belos: DGKS[2]: Ortho (Update)                                0 (0)             0 (0)             0 (0)             0 (0)                 
Belos: DGKS[2]: Orthogonalization                             0 (0)             0 (0)             0 (0)             0 (0)                 
Belos: Operation Op*x                                         0.06321 (2692)    0.06632 (2692)    0.06924 (2692)    2.464e-05 (2692)      
------------------------------------------------------------------------------------------------------------------------------------------
Belos: Operation Prec*x                                       0 (0)             0 (0)             0 (0)             0 (0)                 
Epetra_CrsMatrix::Multiply(TransA,X,Y)                        0.1135 (5387)     0.1204 (5387)     0.1264 (5387)     2.235e-05 (5387)      
==========================================================================================================================================
Number of iterations performed for this solve (new solver): 1345
---------- Actual Residuals (new solver) ----------

Problem 0 : 	8.71716e-06


Dimension of matrix: 1806
Number of right-hand sides: 1
Block size used by solver: 1
Max number of CG iterations: 1805
Relative residual tolerance: 1e-05

End Result: TEST FAILED
run: error: chama178: task 0: Exited with exit code 1
```

which appears to give zero indication why this test failed.  The output for the test `Trilinos-atdm-serrano-intel-opt-openmp`  in the other build where this test also failed looks essentially identical.

If we compare this to the test output for this test for the [build Trilinos-atdm-chama-intel-opt-openmp](https://testing-vm.sandia.gov/cdash/testDetails.php?test=48765612&build=3625496) where this test passed t shows:

```
...

Belos::StatusTestGeneralOutput: Passed
  (Num calls,Mod test,State test): (1324, 1, Passed)
   Passed.......OR Combination -> 
     OK...........Number of Iterations = 1323 < 1805
     Converged....(2-Norm Imp Res Vec) / (2-Norm Res0)
                  residual [ 0 ] = 9.53246e-06 < 1e-05

==========================================================================================================================================

Number of iterations performed for this solve (new solver): 1323
Number of iterations performed for this solve (new solver): 1323
                                                  TimeMonitor results over 4 processors

Timer Name                                                    MinOverProcs      MeanOverProcs     MaxOverProcs      MeanOverCallCounts    
------------------------------------------------------------------------------------------------------------------------------------------
Belos Resolve w/ New Label: BlockCGSolMgr total solve time    0.08022 (1)       0.08023 (1)       0.08024 (1)       0.08023 (1)           
Number of iterations performed for this solve (new solver): 1323
Belos Resolve w/ New Label: DGKS[2]: Ortho (Inner Product)    0 (0)             0 (0)             0 (0)             0 (0)                 
Belos Resolve w/ New Label: DGKS[2]: Ortho (Norm)             0 (0)             0 (0)             0 (0)             0 (0)                 
Belos Resolve w/ New Label: DGKS[2]: Ortho (Update)           0 (0)             0 (0)             0 (0)             0 (0)                 
Belos Resolve w/ New Label: DGKS[2]: Orthogonalization        0 (0)             0 (0)             0 (0)             0 (0)                 
Belos Resolve w/ New Label: Operation Op*x                    0.03036 (1324)    0.03199 (1324)    0.03381 (1324)    2.416e-05 (1324)      
Belos Resolve w/ New Label: Operation Prec*x                  0 (0)             0 (0)             0 (0)             0 (0)                 
Belos Resolve: BlockCGSolMgr total solve time                 0.08269 (1)       0.08279 (1)       0.08283 (1)       0.08279 (1)           
Belos Resolve: DGKS[2]: Ortho (Inner Product)                 0 (0)             0 (0)             0 (0)             0 (0)                 
Belos Resolve: DGKS[2]: Ortho (Norm)                          0 (0)             0 (0)             0 (0)             0 (0)                 
------------------------------------------------------------------------------------------------------------------------------------------
Belos Resolve: DGKS[2]: Ortho (Update)                        0 (0)             0 (0)             0 (0)             0 (0)                 
Belos Resolve: DGKS[2]: Orthogonalization                     0 (0)             0 (0)             0 (0)             0 (0)                 
Belos Resolve: Operation Op*x                                 0.03204 (1324)    0.03308 (1324)    0.03397 (1324)    2.498e-05 (1324)      
Belos Resolve: Operation Prec*x                               0 (0)             0 (0)             0 (0)             0 (0)                 
Belos: BlockCGSolMgr total solve time                         0.2098 (2)        0.2099 (2)        0.2099 (2)        0.1049 (2)            
Belos: DGKS[2]: Ortho (Inner Product)                         0 (0)             0 (0)             0 (0)             0 (0)                 
Belos: DGKS[2]: Ortho (Norm)                                  0 (0)             0 (0)             0 (0)             0 (0)                 
Belos: DGKS[2]: Ortho (Update)                                0 (0)             0 (0)             0 (0)             0 (0)                 
Belos: DGKS[2]: Orthogonalization                             0 (0)             0 (0)             0 (0)             0 (0)                 
Belos: Operation Op*x                                         0.06263 (2648)    0.06593 (2648)    0.0688 (2648)     2.49e-05 (2648)       
------------------------------------------------------------------------------------------------------------------------------------------
Belos: Operation Prec*x                                       0 (0)             0 (0)             0 (0)             0 (0)                 
Epetra_CrsMatrix::Multiply(TransA,X,Y)                        0.1133 (5299)     0.119 (5299)      0.1246 (5299)     2.245e-05 (5299)      
==========================================================================================================================================
Number of iterations performed for this solve (new solver): 1323
---------- Actual Residuals (new solver) ----------

Problem 0 : 	9.53246e-06


Dimension of matrix: 1806
Number of right-hand sides: 1
Block size used by solver: 1
Max number of CG iterations: 1805
Relative residual tolerance: 1e-05

End Result: TEST PASSED
```

Wow, that looks almost identical.  What gives?

Seeing how you can't just look at the test output to understand why the test failed, I tried looking at the test source file:

```
Trilinos/packages/belos/epetra/test/BlockCG/test_resolve_cg_hb.cpp
```

The pass/fail result is determined by:

```
   success = ret==Belos::Converged && !badRes;

    if (success) {
      if (proc_verbose)
        std::cout << "End Result: TEST PASSED" << std::endl;
    } else {
      if (proc_verbose)
        std::cout << "End Result: TEST FAILED" << std::endl;
    }
```

From looking at the output, it seems like the solver converged.  Therefore, it must have failed due to `badRes`.  Looking at the code, this can be set to `true` in one of three different loops that do some simple floating point error comparison, none of which actually prints the pass/fail test numbers.  Therefore, it would seem to be almost impossible to see why this test is actually failing without putting in some more print statements or running this in a debugger.

Can someone on the Belos team please improve the pass/fail criteria printout so we can see what the exact floating point checks are failing?  What we are looking for is that for every floating point check determining pass/fail, we want to see

```
   rel_err(<qualitity_1_name>, <quantity_2_name>)
   = rel_err(<qualitity_1_val>, <quantity_2_val>)
   = <some_error_value>
   >  <some_tol>  [FAILED ERROR CHECK]
```

That makes it super clear what is being compared, what the values are, how far he calculated error is from the tolerance, what the tolerance is, and that this check `FAILED`.  That kind of clear output makes it obvious why a test passes for fails.

Otherwise, I think we just need to temporarily disable this test so that we can promote this build (since every other test is passing) and then this can be debugged offline.   Disabling this test makes good sense because this test is passing in the other Intel build on these machines so we are not really loosing much testing.  My guess from looking at all of this is that the error tolerance is just too tight for this test to be portable.

**Comment by bartlettroscoe** [comment]
CC: @trilinos/belos, @srajama1 (Linear Solvers Product Area Lead)

As shown in [this query](https://testing-vm.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=4&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-&field2=buildstarttime&compare2=84&value2=2018-06-21&field3=buildstarttime&compare3=83&value3=2018-06-14&field4=testname&compare4=61&value4=Belos_resolve_gmres_hb_1_MPI_4), the test `Belos_resolve_gmres_hb_1_MPI_4` appears to be randomly failing in the builds `Trilinos-atdm-serrano-intel-debug-openmp` and `Trilinos-atdm-serrano-intel-opt-openmp` on 'serrano'.  I am commentting on this failure here because these test failures look very similar to those for the failing test `Belos_resolve_cg_hb_MPI_4` on 'serrano' and 'chama' described above.   For example, the output shown [here](https://testing-vm.sandia.gov/cdash/testDetails.php?test=48874172&build=3632883) shows:

```
Belos::StatusTestGeneralOutput: Passed
  (Num calls,Mod test,State test): (215, 1, Passed)
   Passed.......OR Combination -> 
     OK...........Number of Iterations = 214 < 1029
     Converged....(2-Norm Res Vec) / (2-Norm Prec Res0)
                  residual [ 0 ] = 9.74346e-06 < 1e-05

===================================================================================================================================================

                                                       TimeMonitor results over 4 processors

Timer Name                                                             MinOverProcs      MeanOverProcs     MaxOverProcs      MeanOverCallCounts    
---------------------------------------------------------------------------------------------------------------------------------------------------
Belos Resolve w/ New Label: DGKS[2]: Ortho (Inner Product)             0.009999 (427)    0.01002 (427)     0.01006 (427)     2.347e-05 (427)       
Belos Resolve w/ New Label: DGKS[2]: Ortho (Norm)                      0.002253 (643)    0.002666 (643)    0.003064 (643)    4.147e-06 (643)       
Belos Resolve w/ New Label: DGKS[2]: Ortho (Update)                    0.006606 (427)    0.006744 (427)    0.006926 (427)    1.579e-05 (427)       
Number of iterations performed for this solve (new solver): 214
Belos Resolve w/ New Label: DGKS[2]: Orthogonalization                 0.0206 (215)      0.0207 (215)      0.02087 (215)     9.626e-05 (215)       
Number of iterations performed for this solve (new solver): 214
Number of iterations performed for this solve (new solver): 214
Belos Resolve w/ New Label: Operation Op*x                             0.002711 (216)    0.002909 (216)    0.003096 (216)    1.347e-05 (216)       
Belos Resolve w/ New Label: Operation Prec*x                           0 (0)             0 (0)             0 (0)             0 (0)                 
Belos Resolve w/ New Label: PseudoBlockGmresSolMgr total solve time    0.02568 (1)       0.02569 (1)       0.02573 (1)       0.02569 (1)           
Belos Resolve: DGKS[2]: Ortho (Inner Product)                          0.01044 (427)     0.01048 (427)     0.01051 (427)     2.454e-05 (427)       
Belos Resolve: DGKS[2]: Ortho (Norm)                                   0.002421 (643)    0.002931 (643)    0.003334 (643)    4.558e-06 (643)       
Belos Resolve: DGKS[2]: Ortho (Update)                                 0.006763 (427)    0.006925 (427)    0.007121 (427)    1.622e-05 (427)       
---------------------------------------------------------------------------------------------------------------------------------------------------
Belos Resolve: DGKS[2]: Orthogonalization                              0.02144 (215)     0.0216 (215)      0.02182 (215)     0.0001004 (215)       
Belos Resolve: Operation Op*x                                          0.002859 (216)    0.003018 (216)    0.003165 (216)    1.397e-05 (216)       
Belos Resolve: Operation Prec*x                                        0 (0)             0 (0)             0 (0)             0 (0)                 
Belos Resolve: PseudoBlockGmresSolMgr total solve time                 0.02676 (1)       0.02678 (1)       0.02679 (1)       0.02678 (1)           
Belos: DGKS[2]: Ortho (Inner Product)                                  0.07093 (1281)    0.071 (1281)      0.07106 (1281)    5.542e-05 (1281)      
Belos: DGKS[2]: Ortho (Norm)                                           0.01653 (1929)    0.019 (1929)      0.02009 (1929)    9.85e-06 (1929)       
Belos: DGKS[2]: Ortho (Update)                                         0.02351 (1281)    0.02421 (1281)    0.02526 (1281)    1.89e-05 (1281)       
Belos: DGKS[2]: Orthogonalization                                      0.1175 (645)      0.1185 (645)      0.119 (645)       0.0001837 (645)       
Belos: Operation Op*x                                                  0.01168 (648)     0.01196 (648)     0.0124 (648)      1.846e-05 (648)       
Belos: Operation Prec*x                                                0 (0)             0 (0)             0 (0)             0 (0)                 
---------------------------------------------------------------------------------------------------------------------------------------------------
Belos: PseudoBlockGmresSolMgr total solve time                         0.1382 (3)        0.1382 (3)        0.1383 (3)        0.04607 (3)           
Epetra_CrsMatrix::Multiply(TransA,X,Y)                                 0.01605 (1084)    0.01733 (1084)    0.01793 (1084)    1.598e-05 (1084)      
===================================================================================================================================================
Number of iterations performed for this solve (new solver): 214
---------- Actual Residuals (new solver) ----------

Problem 0 : 	9.74346e-06


Dimension of matrix: 1030
Number of right-hand sides: 1
Block size used by solver: 1
Number of restarts allowed: 15
Max number of Gmres iterations per restart cycle: 1029
Relative residual tolerance: 1e-05

End Result: TEST FAILED
srun: error: ser552: task 0: Exited with exit code 1
```

See, everything looks good and says "Converged", yet the test fails.  My guess is that this will also be a case where some residual check failed but that check is never printed or directly reported.  Therefore, we would have to add print statements or run this in a debugger to figure out why this is failing.

Therefore, I will disable this test along with the test `Belos_resolve_cg_hb_MPI_4` in the builds where it is failing and then we can let a Belos developer debug and fix this offline.  (I could do it but I don't have funding to do this type of work.)

**Comment by srajama1** [comment]
@hkthorn : Do you have time to check this ? Disabling CG tests makes me worry we will miss something basic.

**Comment by bartlettroscoe** [comment]
@srajama1 said:

>  Disabling CG tests makes me worry we will miss something basic.

Disabling this test in the builds were it is already failing does not loose any testing.  We are getting zero value for these tests in this builds currently.  And these tests pass for the other builds on these platforms.  And someone can still fix these tests offline even if they are temporarily disabled.

With that said, I don't think it would take very long to fix these tests to pass.   My guess is that some floating point error check is just too tight.  I just don't have the time (or funding) to do this myself right now and these failing tests are blocking the promotion of these entire builds.

**Comment by srajama1** [comment]
@bartlettroscoe : I totally understand. Go ahead and disable if you have to. My comment was to @hkthorn so we fix it and reenable the tests sooner rather than later.

**Comment by hkthorn** [comment]
@bartlettroscoe @srajama1 This issue has been fixed by commit dcbfd13.  Can I enable the tests again on Chama and Serrano?

**Comment by srajama1** [comment]
@hkthorn Thank you for taking care of these ! @bartlettroscoe is the best person to decide reenabling tests for ATDM.

**Comment by bartlettroscoe** [comment]
@hkthorn said:

> This issue has been fixed by commit dcbfd13. Can I enable the tests again on Chama and Serrano?

Sure, go ahead and give it a try.  Just create a new commit (and PR) that removes the lines that were added in commits cbb56a799fb95161e3043088635a532bf524a514 and 5be802ccd476a31f67a3a727ec74512e276997b8 (you might try to just revert those commits but sometimes that will create a conflict).  I will then review and approve the PR.

Thanks for fixing!

**Comment by bartlettroscoe** [comment]
FYI: The PR #3098 was merged today and therefore we should see these tests running starting 7/15/2018.  

I have put this Issue "in review" and if this test does not fail by 8/15/2018, we will close this issue.

**Comment by fryeguy52** [comment]
Closing because this test has passed on both `chama` and `serrano` for the past 2 months as shown in the following cdash queries:
[chama](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&date=2018-09-04&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=4&showfilters=1&filtercombine=and&field1=buildname&compare1=63&value1=Trilinos-atdm-chama&field2=testname&compare2=63&value2=Belos_resolve_cg_hb_MPI_4&field3=buildstarttime&compare3=84&value3=2018-09-12&field4=buildstarttime&compare4=83&value4=2018-07-15)
[serrano](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&date=2018-09-04&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=4&showfilters=1&filtercombine=and&field1=buildname&compare1=63&value1=Trilinos-atdm-serrano&field2=testname&compare2=63&value2=Belos_resolve_cg_hb_MPI_4&field3=buildstarttime&compare3=84&value3=2018-09-12&field4=buildstarttime&compare4=83&value4=2018-07-15)
