### ISSUE TITLE
MueLu: MUELU_KOKKOS_FACTORY macro redefinition breaking Sierra/Trilinos integration

### ISSUE THREAD

**Issue by mwglass** [trilinos/Trilinos#2967]
Why reuse the same macro name for different definitions? Please fix.

In file included from MueLu_ParameterListInterpreter.hpp:2:0,
                 from MueLu_CreateTpetraPreconditioner.hpp:22,
                 from tftk/linsolv/linsolv/Solv_BelosMueLuLinearSolver_Initialize.C:10:
MueLu_ParameterListInterpreter_def.hpp:225:0: error: "MUELU_KOKKOS_FACTORY" redefined [-Werror]
 #define MUELU_KOKKOS_FACTORY(varName, oldFactory, newFactory) \
 ^
In file included from MueLu_FactoryManager.hpp:2:0,
                 from MueLu_Hierarchy_decl.hpp:67,
                 from MueLu_TpetraOperator_decl.hpp:55,
                 from MueLu_TpetraOperator.hpp:1,
                 from tftk/linsolv/linsolv/Solv_BelosMueLuLinearSolver.h:14,
                 from tftk/linsolv/linsolv/Solv_BelosMueLuLinearSolver_Initialize.C:9:
MueLu_FactoryManager_def.hpp:88:0: note: this is the location of the previous definition
 #define MUELU_KOKKOS_FACTORY(varName, oldFactory, newFactory)   \

**Comment by mhoemmen** [comment]
@trilinos/muelu

**Comment by cgcgcg** [comment]
@mhoemmen This should be fixed by PR #2957

**Comment by mhoemmen** [comment]
@cgcgcg Thanks! :D

**Comment by cgcgcg** [comment]
Closing as fixed.
