### ISSUE TITLE
MueLu: Link to Kokkos Kernels Distance-2 Graph Coloring

### ISSUE THREAD

**Issue by william76** [trilinos/Trilinos#2970]
@trilinos/muelu 

So, apparently I can't just link to the MueLu folks directly on the Kokkos-Kernels repo... :p  

Here's a link to the PR: [kokkos-kernels #263][1]

@jhux2
@lucbv 

[1]: https://github.com/kokkos/kokkos-kernels/pull/263

**Comment by jhux2** [comment]
@csiefer2

**Comment by william76** [comment]
Closing out an old issue that's probably been fixed or is no longer relevant.
