### ISSUE TITLE
Kokkos : Filenames invalid in Windows

### ISSUE THREAD

**Issue by hillyuan** [trilinos/Trilinos#2973]
@trilinos/kokkos

File names like "Kokkos_Experimental::ROCm_ViewCopyETIInst_int64_t_double_LayoutLeft_Rank1.cpp" with character "::" in are considered invalid in Windows. Git pull fails in Windows system, even in WSL. Please consider rename those files.

**Comment by jhux2** [comment]
@hillyuan Kokkos is its own github repo, please refile this issue there.

**Comment by hillyuan** [comment]
Issues moved to Kokkos github repo
