### ISSUE TITLE
Windows Testing Failed to Post on Dashboard Again

### ISSUE THREAD

**Issue by csiefer2** [trilinos/Trilinos#2975]
@trilinos/framework

**Comment by mhoemmen** [comment]
PR testing is a little weird today as well :(

**Comment by jwillenbring** [comment]
I have been looking into this. The nightly job is unable to write to the machine. I had it rebooted yesterday and that did not help. I now requested login access (which I thought worked previously, but does not now) so I can investigate further.

**Comment by csiefer2** [comment]
Thanks for taking care of this.  Please keep me posted!

**Comment by jwillenbring** [comment]
At least some of the problem is that [Kokkos added a bunch of files with "::" in the filename](https://github.com/kokkos/kokkos/issues/1675). Testing with those removed on a fork still wasn't 100% working, but fixing this should help us to make further progress.
