### ISSUE TITLE
MueLu: include number of threads in target rows per processor computation

### ISSUE THREAD

**Issue by aprokop** [trilinos/Trilinos#2977]
@trilinos/muelu 

## Expectations
When running MueLu in hybrid MPI/OpenMP mode, the parameter `repartition: target rows per proc` should actually specify the target number of rows per thread so that there is enough computational work.

## Current Behavior
The matrix is rebalanced so that each MPI process gets that number, leading to little work per thread (like 10000/32 or the default 1000/32).

## Motivation and Context
This leads to unnecessarily high cost of coarse levels.

**Comment by aprokop** [comment]
I'm not 100% certain how to implement this. Do I need to do some traits which returns 1 by default, and `execution_space::concurrency()` for OpenMP space?

**Comment by lucbv** [comment]
@aprokop we also should investigate how mpi behaves when it needs to pass less but certainly larger messages. Is it obvious that the network will handle well going from say 16 ranks per nodes to 1 rank per node with OpenMP on the node?
The same is also true for GPUs and it is even harder to guess what will be a good work load for the GPU a priori as concurrentcy won't really be helpful at the point?

**Comment by aprokop** [comment]
Another caveat here may be that if we don't have a threaded direct solver, the coarse solve may actually be large, like `num_target_per_proc*num_threads_per_mpi`, which may be 160000 for Cori Haswell in 2x16 configuration.

**Comment by aprokop** [comment]
@lucbv 

> @aprokop we also should investigate how mpi behaves when it needs to pass less but certainly larger messages. Is it obvious that the network will handle well going from say 16 ranks per nodes to 1 rank per node with OpenMP on the node?

While true that larger messages may be slower due to additional buffer copies, I think having less work to do is more important to address. In addition, even if it is to be dynamically implemented, it should be done for Tpetra to figure out.

> The same is also true for GPUs and it is even harder to guess what will be a good work load for the GPU a priori as concurrentcy won't really be helpful at the point?

The question is open for GPU as to what number of rows per GPU is the optimal number.

**Comment by mhoemmen** [comment]
@aprokop Could you just set the `Kokkos::parallel_*` chunk size large enough?  That should be a platform-independent way to control concurrency for the strong scaling case.

**Comment by aprokop** [comment]
@mhoemmen Sorry, I don't get what you are saying.

**Comment by mhoemmen** [comment]
@aprokop Here is an example:
```c++
Kokkos::ChunkSize chunkSize (500); // for example
Kokkos::RangePolicy<execution_space, LO> range (0, N);
range.set (chunkSize);
Kokkos::parallel_for ("loop", range, closureOfYourChoice);
```

**Comment by mhoemmen** [comment]
The idea is that Kokkos won't divide the loop into parallel work units with fewer than `chunkSize` iterations, so you won't get strong scaling drama.

**Comment by aprokop** [comment]
@mhoemmen I think you may be talking about a different issue. This is about redistributing a matrix among MPI ranks during rebalancing, and specifically, about computing the number of rows that each MPI rank would get. I think what you are talking is work within the node and having some minimal work per thread.

**Comment by mhoemmen** [comment]
@aprokop Sorry :)

**Comment by jhux2** [comment]
> I'm not 100% certain how to implement this. Do I need to do some traits which returns 1 by default, and execution_space::concurrency() for OpenMP space?

@aprokop Is the idea to have some way of querying the number of threads per MPI process, which I guess `execution_space::concurrency()` does?  Call that number `NT`.  Then MueLu multiplies the value  of `repartition: target rows per proc` by NT to get the actual target value?

**Comment by aprokop** [comment]
@jhux2 Exactly.

**Comment by jhux2** [comment]
@mhoemmen Is there a canonical way to query Kokkos at runtime to find out how many threads per MPI process there are?

**Comment by mhoemmen** [comment]
@jhux2 That's the right approach for OpenMP at least.  For GPUs, that value will be an upper bound but not necessarily exact.

**Comment by aprokop** [comment]
@csiefer2 That's my thinking too.

**Comment by aprokop** [comment]
Merged in `master`.
