### ISSUE TITLE
ROL_ThyraVector.hpp needs to include Thyra_ProductVectorSpaceBase.hpp

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#2978]
Lines 99 and 175 of `ROL_ThyraVector.hpp` use a `Thyra::ProductVectorSpaceBase` method (namely `numBlocks`, but the file does not include `Thyra_ProductVectorSpaceBase.hpp`.  For example:

https://github.com/trilinos/Trilinos/blob/ffdc8c53f67747825753c378929ed752b4a3151a/packages/rol/adapters/thyra/src/vector/ROL_ThyraVector.hpp#L175

`Thyra_ProductVectorBase.hpp` forward-declares `Thyra::ProductVectorSpaceBase`, but does not include it, either directly or indirectly.  This is not a Thyra bug; Thyra conservatively prefers forward declarations to includes, as a way to reduce build time.

Our current work-around is to include `Thyra_ProductVectorSpaceBase.hpp` above the `ROL_ThyraVector.hpp` include.

@trilinos/rol @dridzal @gregvw @micahahoward

**Comment by dridzal** [comment]
@mhoemmen, thanks for finding this.  Should ROL developers fix this?

For our future reference, is there a way to know which files we need to include if you rely on forward declarations?  Some way that doesn’t involve analyzing the source code?

**Comment by mhoemmen** [comment]
@dridzal wrote:
> Should ROL developers fix this?

Yes, please.  It would be great if you could update both Trilinos and ROL repositories concurrently.

> For our future reference, is there a way to know which files we need to include if you rely on forward declarations? Some way that doesn’t involve analyzing the source code?

If you use any method or field of a `Thyra::${CLASS}`, then you need to include `${CLASS}`'s header file.  If you just handle the `${CLASS}` by pointer or reference, without calling its methods or accessing its fields, then the forward declaration suffices.  There's nothing special about this rule; Trilinos developers in other packages just tend to be loose about including a lot of header files.

**Comment by dridzal** [comment]
@mhoemmen sorry I misunderstood.  Will do.  Most likely tomorrow.

**Comment by dridzal** [comment]
@mhoemmen could you try removing the include in your code?  It should no longer be needed.
