### ISSUE TITLE
Stratimikos: catches Belos StatusTest exception, does not report it

### ISSUE THREAD

**Issue by wfspotz** [trilinos/Trilinos#2983]
@trilinos/stratimikos 

## Expectations

When a Belos status test object throws an exception, I would expect Stratimikos to both catch the exception and to report it, so that the user would have an immediate idea where to start looking for problems.

## Current Behavior
What Stratimikos _does_ report when this happens is that the solver failed to converge in 0 iterations, without reporting why no iterations were performed.

## Motivation and Context

I am adding a NOX solver to SPARC, which in turn uses Stratimikos to utilize a Belos solver. The Belos solver is throwing an exception from the `Belos::StatusTestImpResNorm` status test, which Stratimikos catches, but does not report. Hunting down where the problem was has been time consuming.

## Definition of Done

Complete the following checklist:                                                   
- [ ] Set up a test in which the `Belos::StatusTestImpResNorm` throws an exception. One way to do this would be to send in a vector with NaNs. We could also try to replicate the problem we are seeing in SPARC, but we do not completely understand that yet.
- [ ] In the Stratimikos code that catches an exception when a solver object is asked to solve the linear system, add simple logic to report the exception message.
- [ ] Verify that the exception is caught and that the error message is reported.

## Your Environment

I came upon this on the CEE LAN using a Trilinos compiled using [these instructions](https://snl-wiki.sandia.gov/display/SPAR/How+to+build+SPARC+with+external+Trilinos). But I do not think that the environment is an issue here.

## Related Issues

* Related to #1608, possibly, but only tangentially

**Comment by bartlettroscoe** [comment]
@wfspotz, what lines of code is this?  Can we use 'git blame' to see who wrote that code?  I don't remember writing code that does that.

**Comment by wfspotz** [comment]
Looks like

    packages/stratimikos/adapters/belos/src/Thyra_BelosLinearOpWithSolve_def.hpp

lines 653-658:

    12eabde6 (Roger P. Pawlowski    2014-04-01 14:51:59 -0600 653)     try {
    12eabde6 (Roger P. Pawlowski    2014-04-01 14:51:59 -0600 654)       belosSolveStatus = iterativeSolver_->solve();
    12eabde6 (Roger P. Pawlowski    2014-04-01 14:51:59 -0600 655)     }
    12eabde6 (Roger P. Pawlowski    2014-04-01 14:51:59 -0600 656)     catch (Belos::BelosError&) {
    12eabde6 (Roger P. Pawlowski    2014-04-01 14:51:59 -0600 657)       belosSolveStatus = Belos::Unconverged;
    12eabde6 (Roger P. Pawlowski    2014-04-01 14:51:59 -0600 658)     }

There are probably other blocks around that need to be addressed as well.

**Comment by wfspotz** [comment]
Also, I am happy to fix this. The only issue is if there is a "standard" way to report the error.

**Comment by rppawlo** [comment]
Here's the comment with that commit:

 stratimikos: adding try/catch block around belos adapter solve()
    
Some belos exceptions were not being caught in the stratimikos adapters - in particular the call to solve() was not wrapped in a try/catch block.  This resulted in failing the entire simulation instead of allowing for a time stepper to check the linear solve status for a failed solve so that it can cut the step and try again.  Belos exceptions are now caught and the solve status reported through the thyra linearOpWithSolve interface reports a failed solve.

**Comment by mhoemmen** [comment]
Does Stratimikos have an error code for "the solve failed for some reason other than failure to converge"?

**Comment by bartlettroscoe** [comment]
@mhoemmen said:

> Does Stratimikos have an error code for "the solve failed for some reason other than failure to converge"?

The documentation at:

* https://trilinos.org/docs/dev/packages/thyra/doc/html/classThyra_1_1LinearOpWithSolveBase.html#ac7c5b4c8553833778e88e3fb627c4009

states:

> If any progress on solving the linear systems could be achieved, then the function will return normally with the solve status. However, if no progress could be made in solving the linear systems, then an exception of type `CatastrophicSolveFailure` will be thrown. If the function returns normally, then the following postconditions apply.

Can we update the implementation to throw the exception `Thyra::CatastrophicSolveFailure` and then pass through the relevant error message?  Could NOX and other clients then be updated to look for this exception?

**Comment by wfspotz** [comment]
@bartlettroscoe I believe this would have been the preferred behavior in the SPARC development scenario outlined above.
