### ISSUE TITLE
Create and Populate Teams for the Various Product Areas

### ISSUE THREAD

**Issue by jmgate** [trilinos/Trilinos#2986]
## Expectations
Given the "Trilinos testing and APP integration workflows and processes" discussion had today (6/19/2018) between @bartlettroscoe, @kddevin, @micahahoward, @rppawlo, @mperego, @agsalin, @srajama1, and @jmgate, it sounded reasonable to create teams under the Trilinos organization corresponding to the Trilinos product areas.  Then whenever someone is triaging ATDM CDash failures, they can @mention the appropriate team.

## Current Behavior
Currently @bartlettroscoe or @fryeguy52 will look at a failing test, see what package it pertains to, look up what product area that package is a part of, find the product lead for that product area, and @mention them.  It's then the responsibility of the product lead to figure out the right person or people to put on the issue and assign them.  With product area teams, containing appropriate people capable of assessing and addressing or assigning failures, that process is simplified.

## Definition of Done                                                 
- [x] Create teams corresponding to each of the product areas.
- [x] Assign each product lead as the maintainer of their team.
- Team maintainers (product leads) can then [add whoever they deem appropriate to their team](https://help.github.com/articles/adding-organization-members-to-a-team/).
   - [ ] @trilinos/data-services (@kddevin)
   - [ ] @trilinos/discretizations (@mperego)
   - [x] @trilinos/framework (@jwillenbring)
   - [ ] @trilinos/linear-solvers (@srajama1)
   - [ ] @trilinos/nonlinear-solvers (@rppawlo)
- [ ] @bartlettroscoe, adjust whatever documentation is necessary to let ATDM CDash triagers know what teams to mention.

### Optional Steps
- Team maintainers can [rename their team or add a team description](https://help.github.com/articles/renaming-a-team/).

## Interested Parties
@jwillenbring, @maherou

**Comment by srajama1** [comment]
It is just me for linear solvers now. Let us see how worse this gets and go from there. I might get extra help based on the load. 

If possible, I recommend all of us start that way and if the load is too much we get someone to help us all.

**Comment by rppawlo** [comment]
Should we mark these teams as product areas? Don't want it to be confused as a new package. Maybe rename to "pa-nonlinear" or "product-area-nonlinear"?

**Comment by bartlettroscoe** [comment]
To make it clear that these GitHub teams are not about contacting everyone in a product area, how about `@trilinos/pa-issues-<product-area>`:  That would give:

* `@trilinos/pa-issues-data-services` (@kddevin)
* `@trilinos/pa-issues-discretizations` (@mperego)
* `@trilinos/pa-issues-framework` (@jwillenbring)
* `@trilinos/pa-issues-linear-solvers` (@srajama1)
* `@trilinos/pa-issues-nonlinear-solvers` (@rppawlo)

We would list those in the table at:

* https://snl-wiki.sandia.gov/display/TRIL/Trilinos+Product+Areas+and+Product+Leaders

instead of listing out specific "Product Represntatives".

What does everyone think about that?

**Comment by jmgate** [comment]
Sounds fine to me.  Whatever you all like as long as there's consistency.

**Comment by srajama1** [comment]
@bartlettroscoe : I don't like this team model quite that much. It is scalable, but this is quite easy to devolve into a huge list which is not what ATDM wants. Why don't we decide how to do this at the Trilinos Product leaders meeting and let you know. I appreciate the help, but we can come up with something that works for Trilinos.

**Comment by bartlettroscoe** [comment]
@srajama1 said

> @bartlettroscoe : I don't like this team model quite that much. It is scalable, but this is quite easy to devolve into a huge list which is not what ATDM wants. Why don't we decide how to do this at the Trilinos Product leaders meeting and let you know. I appreciate the help, but we can come up with something that works for Trilinos.

That is fine. All that is important from the ATDM perspective is that we list some `@mention` for each Product Area in the table on the page:

* https://snl-wiki.sandia.gov/display/TRIL/Trilinos+Product+Areas+and+Product+Leaders

and then know that when we add that `@mention` that we will be assured that someone associated with the Product Area will take over responsibility for the issue to to either a) fix the issue, b) temporarily (or permanently) disable some tests for problematic platforms or c) back out serious issues in a timely manner (in a few weeks at most).  It is not complicated (but it is time consuming).

**Comment by srajama1** [comment]
Got it ! Thanks !

**Comment by bartlettroscoe** [comment]
I think it was decided that we were not going to move forward with this approach of using GitHub teams for now right?  Therefore, should we close this?

In the meantime, I will remove that ATDM label.

**Comment by jmgate** [comment]
If the teams that were created won't be used, we should probably delete them before closing this out.

**Comment by jmgate** [comment]
@rppawlo, should the teams that were created be removed, and then should we close this issue?

**Comment by rppawlo** [comment]
@jmgate - I guess so. There was a comment above that we are not doing this.

**Comment by jmgate** [comment]
@trilinos/framework, would you mind deleting the following teams from the `trilinos` organization?
*  @trilinos/data-services 
*  @trilinos/discretizations 
*  @trilinos/linear-solvers 
*  @trilinos/nonlinear-solvers 

I'd do it myself, but I don't have the requisite permissions.

**Comment by jmgate** [comment]
Pinging for someone with appropriate permissions to delete the teams above.  Closing&hellip;
