### ISSUE TITLE
STK: Cannot build as shared library on OSX

### ISSUE THREAD

**Issue by jrood-nrel** [trilinos/Trilinos#2994]
When building with STK enabled on OSX (Sierra) as a shared library using Clang v9.0.0-apple and GCC 7.3.0, I get this error:
```
Undefined symbols for architecture x86_64:
  "stk::handle_assert(char const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_ostringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> >&)", referenced from:
      sierra::MPI::AllReduce(ompi_communicator_t*, sierra::MPI::ReduceSet const&) in MPI.cpp.o
      sierra::MPI::(anonymous namespace)::ReduceCheck::copyout(void*&) const in MPI.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [packages/stk/stk_util/stk_util/parallel/libstk_util_parallel.12.13.dylib] Error 1
make[1]: *** [packages/stk/stk_util/stk_util/parallel/CMakeFiles/stk_util_parallel.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

When building as a static library on OSX, everything works fine. Also when building either shared or static with STK enabled on Linux works fine. I used Spack to investigate this, so I install with either `trilinos+shared` or `trilinos~shared` when testing this. The easiest way to see this I think would be to use `spack install nalu-wind` on OSX Sierra to see Trilinos fail with this error. (Update: I developed a workaround for this in Spack, so it won't build as a shared library on OSX)

@trilinos/stk

**Comment by tjfulle** [comment]
@jrood-nrel, I build stk with shared libraries on macOS, but I have to apply the attached patch
[stk_diff.txt](https://github.com/trilinos/Trilinos/files/2120802/stk_diff.txt).  One of the changes in the diff fixes a missing dependency in a `CMakeLists.txt`.  I'm not sure why the build succeeds on Linux but fails on macOS (maybe having to do with differences in how each OS alphabetizes lower/upper case filenames that affects order of CMake processing?).

The other patch in the diff file is a kludge to bypass the missing `stk::handle_assert`.  I tried to come up with a "real" fix, but gave up after some time.

**Comment by mhoemmen** [comment]
@alanw0

**Comment by mhoemmen** [comment]
@tjfulle We should file a ticket for STK w/ the patch -- I'm pretty sure they would be willing to apply it from their end.

**Comment by tjfulle** [comment]
@mhoemmen, you should look at the kludge before making that assertion 😂

**Comment by tjfulle** [comment]
@mhoemmen , but I have an idea of what needs to be fixed, I just haven't had the time

**Comment by mhoemmen** [comment]
@tjfulle Let's just file a ticket, give 'em the patch, and let them sort it out ;-)

I'm not sure what the rules are these days for applying STK patches to Trilinos.  @trilinos/framework might have some idea about that.

**Comment by tjfulle** [comment]
Okay, can you email me a link where I can file a ticket?

**Comment by mhoemmen** [comment]
@tjfulle done; thanks!

**Comment by prwolfe** [comment]
stk patches should be applied in Sierra and migrated into Trillinos via the PR process.  There is a PR waiting for a newer Seacas at the moment (see #2930 )

**Comment by khpierson** [comment]
@khpierson would like to know what the status is of this issue.

Thanks!
-Kendall

**Comment by jrood-nrel** [comment]
Is there any update on this? It would be quite convenient to be able to build with STK as shared libraries on Mac again.

**Comment by mhoemmen** [comment]
@alanw0

**Comment by alanw0** [comment]
Gents, the stk update has been pushed into trilinos. Please let me know if it failed to address this issue.

**Comment by jrood-nrel** [comment]
Looks like some new undefined symbol errors now:
```
Undefined symbols for architecture x86_64:
  "stk::diag::operator<<(stk::diag::Writer&, sierra::StringBase<sierra::char_simple_traits> const&)", referenced from:
      sierra::Rsrc2::operator<<(stk::diag::Writer&, sierra::Rsrc2::Resource_ const&) in Resource2.cpp.o
  "sierra::case_strcmp(char const*, char const*)", referenced from:
      sierra::Rsrc2::Resource::match(sierra::StringBase<sierra::char_simple_traits> const&, sierra::Rsrc2::ResourceList&) const in Resource2.cpp.o
  "sierra::char_simple_traits::compare(char const*, char const*)", referenced from:
      sierra::Rsrc2::Resource::create(sierra::StringBase<sierra::char_simple_traits> const&, sierra::AnyData*) in Resource2.cpp.o
      sierra::Rsrc2::find(sierra::Rsrc2::Resource_*, sierra::StringBase<sierra::char_simple_traits> const&) in Resource2.cpp.o
      sierra::Rsrc2::Resource::match(sierra::StringBase<sierra::char_simple_traits> const&, sierra::Rsrc2::ResourceList&) const in Resource2.cpp.o
  "sierra::demangle(char const*)", referenced from:
      sierra::Rsrc2::cast_error(sierra::Rsrc2::Resource const&, sierra::AnyData const*, std::type_info const&) in Resource2.cpp.o
  "sierra::operator<<(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, sierra::StringBase<sierra::char_simple_traits> const&)", referenced from:
      sierra::Rsrc2::cast_error(sierra::Rsrc2::Resource const&, sierra::AnyData const*, std::type_info const&) in Resource2.cpp.o
      sierra::Rsrc2::not_found(sierra::StringBase<sierra::char_simple_traits> const&, sierra::StringBase<sierra::char_simple_traits> const&) in Resource2.cpp.o
      sierra::Rsrc2::Resource::create(sierra::StringBase<sierra::char_simple_traits> const&, sierra::AnyData*) in Resource2.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [packages/stk/stk_util/stk_util/util/libstk_util_util.12.13.dylib] Error 1
make[1]: *** [packages/stk/stk_util/stk_util/util/CMakeFiles/stk_util_util.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

**Comment by jrood-nrel** [comment]
I erased all the `DEPLIBS` and tried to build up the dependencies by hand to see if I could resolve all the library dependencies, but it appears the cyclic dependency will have to be removed for this to work on the Mac. I just don't understand how Linux is able to build STK so easily as shared libraries if there is a cyclic dependency.

**Comment by sethrj** [comment]
@jrood-nrel I bet that if you compile on Linux with `LDFLAGS=-Wl,--error-unresolved-symbols` you'll have a hard time building STK as well. The macOS linker by default has `-undefined error` whereas most Linux distributions allow unresolved shared symbols to be deferred. I've seen similar issues in other code packages, and indeed also on Ubuntu 20+ which adds some default linker flags  (such as  `-Wl,--as-needed`)  that can break assumptions about implicit upstream dependencies.

One solution to support shared STK builds on mac might be to set `LDFLAGS=-Wl,-undefined,dynamic_lookup.`
