### ISSUE TITLE
Framework: Autotester may be busted?

### ISSUE THREAD

**Issue by csiefer2** [trilinos/Trilinos#2995]
Been waiting 5 hours now for the testing to finish... See #2988

@trilinos/framework

**Comment by prwolfe** [comment]
Sorry I didn't see this earlier.  This is about the max time limit, but it does seem to have completed successfully.

**Comment by csiefer2** [comment]
Is the autotesting supposed to take 5 hours now?  Or is something wonky?

**Comment by jwillenbring** [comment]
The Intel build generally takes about 4.5 hours I would say. I don't see 5 as being out of line with what we would expect.

**Comment by csiefer2** [comment]
Yeah, its just that builds took 2 hours a month or two ago (because we weren't doing intel)...
