### ISSUE TITLE
Xpetra: Functionality we should expose

### ISSUE THREAD

**Issue by csiefer2** [trilinos/Trilinos#30]
We don't have any vector/multivector clone capability.

We should.

@trilinos/xpetra

**Comment by jhux2** [comment]
Agreed.

**Comment by mhoemmen** [comment]
Does that mean "change from one Kokkos device type to another"?

**Comment by jhux2** [comment]
Mark Hoemmen wrote on 11/24/2015 04:32 PM:
>
> Does that mean "change from one Kokkos device type to another"?
>
>
Chris means a deep copy to another MultiVector on the same device.
