### ISSUE TITLE
Tpetra: shadowed variable ac_status in TpetraExt_TripleMatrixMultiply_def.hpp

### ISSUE THREAD

**Issue by mmwolf** [trilinos/Trilinos#3038]
Warning (error with -Werror):

.../Trilinos/packages/tpetra/core/ext/TpetraExt_TripleMatrixMultiply_def.hpp:1647:39: error: declaration of ‘ac_status’ shadows a previous local [-Werror=shadow]
         std::vector<size_t> ac_status(maxAccol + 1, ST_INVALID);
                                       ^~~~~~~~
.../Trilinos/packages/tpetra/core/ext/TpetraExt_TripleMatrixMultiply_def.hpp:1629:21: note: shadowed declaration is here
       Array<size_t> ac_status(maxAccol+1, ST_INVALID);

@trilinos/<teamName>

## Your Environment

- **Relevant repo SHA1s:**  
- **Relevant configure flags or configure script:**  
- **Operating system and version:**  
- **Compiler and TPL versions:**  

## Related Issues

* Blocks 
* Is blocked by 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of

**Comment by cgcgcg** [comment]
@brian-kelley

**Comment by mhoemmen** [comment]
@trilinos/muelu

**Comment by brian-kelley** [comment]
@cgcgcg Fixed in #3039 . It's just a one-line change to delete the shadowing declaration.

**Comment by mhoemmen** [comment]
Fixed in develop; thanks!
