### ISSUE TITLE
Anasazi: missing header file in AnasaziStatusTestResNorm.hpp

### ISSUE THREAD

**Issue by mmwolf** [trilinos/Trilinos#3040]
I believe AnasaziStatusTestResNorm.hpp is missing the following:

#include "Teuchos_LAPACK.hpp"

So I'm getting the following error:

In file included from algorithms/helper/BKSShiftInvertHelpers.hpp:14:0,
                 from algorithms/helper/BKSShiftInvertHelpers.cpp:8:
AnasaziStatusTestResNorm.hpp: In member function ‘Anasazi::TestStatus Anasazi::StatusTestResNorm<ScalarType, MV, OP>::checkStatus(Anasazi::Eigensolver<ScalarType, MV, OP>*)’:
AnasaziStatusTestResNorm.hpp:261:7: error: ‘LAPACK’ is not a member of ‘Teuchos’
       Teuchos::LAPACK<int,MagnitudeType> lapack;
       ^~~~~~~
AnasaziStatusTestResNorm.hpp:261:23: error: expected primary-expression before ‘int’
       Teuchos::LAPACK<int,MagnitudeType> lapack;
                       ^~~
AnasaziStatusTestResNorm.hpp:264:29: error: ‘lapack’ was not declared in this scope
         MagnitudeType tmp = lapack.LAPY2(vals[i].realpart,vals[i].imagpart);

@hkthorn 

@trilinos/<teamName>

## Your Environment

- **Relevant repo SHA1s:**  
- **Relevant configure flags or configure script:**  
- **Operating system and version:**  
- **Compiler and TPL versions:**  

## Related Issues

* Blocks 
* Is blocked by 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of

**Comment by mhoemmen** [comment]
I merged PR #3089 into develop.

**Comment by hkthorn** [comment]
This has been addressed by PR# 3089, so it can be closed.
