### ISSUE TITLE
Linker problem for Trilinos on Mac

### ISSUE THREAD

**Issue by Tdub122984** [trilinos/Trilinos#3042]
I believe that I had a success build for Trilinos... I am trying to run individual tests on for different Trilinos packages to better understand Trilinos. However, every testcase come with the following: 

clang: error: linker command failed with exit code 1 (use -v to see invocation)

Any help on this would be greatly appreciated!

**Comment by mhoemmen** [comment]
Could that be related to this issue? https://github.com/trilinos/Trilinos/issues/2141  

Short answer: Try reconfiguring (rerunning CMake) with `CMAKE_CXX_USE_RESPONSE_FILE_FOR_OBJECTS=ON`.

**Comment by mhoemmen** [comment]
> `-DMPI_BASE_DIR=/Users/ER/mpi/bin`

This is probably wrong.  Your `MPI_BASE_DIR` should be the root of your MPI installation, not the subdirectory thereof that contains binaries.  That might explain why `MPI_EXEC` points to `/usr/local/bin/mpiexec`, instead of `/Users/ER/mpi/bin/mpiexec`.  Set it this way instead:
```
-D MPI_BASE_DIR=/Users/ER/mpi
```
