### ISSUE TITLE
ROL: Tests failing on clean build since 6/22 nightlies

### ISSUE THREAD

**Issue by william76** [trilinos/Trilinos#3045]
@trilinos/rol 

There have been failing tests on the [Clean][1] track since 6/22.

- Test: [ROL_example_PDE-OPT_adv-diff-react_example_02][2] (Failed) 
- Test: [ROL_example_PinT_tanks_AugmentedSystem_test][3] (Failed) 
- Test: [ROL_example_PDE-OPT_adv-diff-react_example_02_MPI_4][4] (Failed) 

The source of this would have been merged in on 6/21 before about 10pm MT.

Errors in clean builds prevent develop-to-master mergers and are a high priority to fix.

@dridzal 

[1]: https://testing.sandia.gov/cdash/index.php?project=Trilinos&date=2018-06-22
[2]: https://testing.sandia.gov/cdash/testDetails.php?test=49821765&build=3646963
[3]: https://testing.sandia.gov/cdash/testDetails.php?test=49821752&build=3646963
[4]:https://testing.sandia.gov/cdash/testDetails.php?test=49823772&build=3647061

**Comment by dridzal** [comment]
Is there a deadline for the fix?

**Comment by william76** [comment]
@dridzal Errors in clean block us from promoting develop to master so the longer the failures remain in the nightly builds the more out of date master branch will be.  So far nobody to my knowledge is asking for master to be updated but I imagine the odds of that increase over time ;)

@jwillenbring what's the expected turnaround time for fixes on the clean track?

**Comment by mhoemmen** [comment]
@micahahoward @rrdrake @prwolfe

**Comment by vbrunini** [comment]
Is there an update on this? There is a bug fix for #3017 that was merged to develop a week ago and I would like to confirm it fixes some of our build errors in sierra, but need the merge to master to happen to do that. More than 2 weeks seems like a long time to let the "clean" track have failing tests.

**Comment by mhoemmen** [comment]
@bartlettroscoe Should we just disable the failing ROL tests for now?

**Comment by bartlettroscoe** [comment]
@mhoemmen said:

> @bartlettroscoe Should we just disable the failing ROL tests for now?

These failures don't impact any of the ATDM builds yet (since we have not adding ROL testing yet).  Therefore, I don't have much say on this.  Once ROL is added to the ATDM Trilinos builds, we will need to be on top of any issues with ROL on any of the ATDM platforms.

**Comment by mhoemmen** [comment]
SPARC does depend on ROL so I would very much like to see ROL included in the ATDM tests.

**Comment by bartlettroscoe** [comment]
@mhoemmen said:

> SPARC does depend on ROL so I would very much like to see ROL included in the ATDM tests.

That is the plan, and soon.  See:

* https://software-sandbox.sandia.gov/jira/browse/TRIL-212

Just need to clean up the current ATDM builds and then can start fresh on that.

**Comment by jwillenbring** [comment]
@trilinos/rol has a fix in the works for this, but it is not scheduled to be applied until Monday.

**Comment by william76** [comment]
@trilinos/rol 
Looks like the clean track had no errors last night.  I was able to get the dev->master merge done this morning too :)  I'll go ahead and close this ticket.

Thanks!
