### ISSUE TITLE
Zoltan build failure for CUDA 8.0 Debug build on white/ride

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#3065]
CC: @trilinos/zoltan, @kddevin (Trilinos Data Services Product Lead)

## Description

The Zoltan executable `zCPPdrive` fails to link in the CUDA 8.0 debug build `Trilinos-atdm-white-ride-cuda-debug-pt-all-at-once` run on 'white' and 'ride'.  The link error output for the build this morning shown [here](https://testing-vm.sandia.gov/cdash/viewBuildError.php?buildid=3688780) on 'white' shows:

```
packages/zoltan/src/driver/CMakeFiles/zCPPdrive.dir/dr_input.c.o:(.toc+0x0): undefined reference to `Output'
packages/zoltan/src/driver/CMakeFiles/zCPPdrive.dir/dr_input.c.o:(.toc+0x8): undefined reference to `Output'
packages/zoltan/src/driver/CMakeFiles/zCPPdrive.dir/dr_input.c.o:(.toc+0x10): undefined reference to `Output'
packages/zoltan/src/driver/CMakeFiles/zCPPdrive.dir/dr_input.c.o:(.toc+0x18): undefined reference to `Output'
packages/zoltan/src/driver/CMakeFiles/zCPPdrive.dir/dr_input.c.o:(.toc+0x20): undefined reference to `Output'
packages/zoltan/src/driver/CMakeFiles/zCPPdrive.dir/dr_input.c.o:(.toc+0x28): undefined reference to `Test'
packages/zoltan/src/driver/CMakeFiles/zCPPdrive.dir/dr_input.c.o:(.toc+0x30): undefined reference to `Test'
packages/zoltan/src/driver/CMakeFiles/zCPPdrive.dir/dr_input.c.o:(.toc+0x38): undefined reference to `Test'
packages/zoltan/src/driver/CMakeFiles/zCPPdrive.dir/dr_input.c.o:(.toc+0x40): undefined reference to `Test'
packages/zoltan/src/driver/CMakeFiles/zCPPdrive.dir/dr_input.c.o:(.toc+0x48): undefined reference to `Test'
packages/zoltan/src/driver/CMakeFiles/zCPPdrive.dir/dr_input.c.o:(.toc+0x50): more undefined references to `Test' follow
packages/zoltan/src/driver/CMakeFiles/zCPPdrive.dir/dr_output.c.o:(.toc+0x0): undefined reference to `Output'
packages/zoltan/src/driver/CMakeFiles/zCPPdrive.dir/dr_gnuplot.c.o:(.toc+0x0): undefined reference to `Output'
packages/zoltan/src/driver/CMakeFiles/zCPPdrive.dir/dr_mainCPP.cpp.o:(.toc+0x8): undefined reference to `Test'
packages/zoltan/src/driver/CMakeFiles/zCPPdrive.dir/dr_mainCPP.cpp.o:(.toc+0x10): undefined reference to `Output'
packages/zoltan/src/driver/CMakeFiles/zCPPdrive.dir/dr_loadbalCPP.cpp.o:(.toc+0x8): undefined reference to `Test'
packages/zoltan/src/driver/CMakeFiles/zCPPdrive.dir/dr_migrateCPP.cpp.o:(.toc+0x0): undefined reference to `Test'
packages/zoltan/src/driver/CMakeFiles/zCPPdrive.dir/dr_mapsCPP.cpp.o:(.toc+0x0): undefined reference to `Test'
collect2: error: ld returned 1 exit status
```

## Steps to reproduce

This build error can reproduced on 'white' or 'ride' as described in the document:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md

The specific instructions for 'white' or 'ride' are given at:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#ridewhite

The one difference is that this build of all of the Primary Tested Trilinos packages (that includes more package than are being used by ATDM APPs currently) does not exclude any Trilinos packages so it uses the file `Trilinos/cmake/std/atdm/ATDMDevEnvSettings.cmake` instead of the file `ATDMDevEnv.cmake`.

After cloning Trilinos, the following commands should reproduce the build failure:

```
$ cd <some_build_dir>/

$ source $TRILINOS_DIR/cmake/std/atdm/load-env.sh cuda-debug

$ cmake \
  -GNinja \
  -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnvSettings.cmake \
  -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_Zoltan=ON \
  $TRILINOS_DIR

$ make NP=16
```

I (@bartlettroscoe) just tired this on 'white' and I was able to reproduce the same build failure shown on CDash shown above.

**Comment by kddevin** [comment]
These instructions worked perfectly.  Thank you, @bartlettroscoe

**Comment by bartlettroscoe** [comment]
With the merge of PR #3066 yesterday, this Zoltan build error is now gone as shown [here](https://testing-vm.sandia.gov/cdash/index.php?project=Trilinos&parentid=3695497).  Note the `-1` subscript by the `0` build errors for the Zoltan package.

Closing as complete.

Thanks for taking care of this @kddevin!
