### ISSUE TITLE
Clarification of resumeFill requirements for Tpetra::CrsMatrix  

### ISSUE THREAD

**Issue by keitat** [trilinos/Trilinos#3070]
Tpetra::CrsMatrix requires resumeFill() when changing its sparsity pattern. However, I have observed that there are several set...() methods requiring resumeFill() even though no changes happen in the sparsity pattern.  Could you clarify the following?

- setAllToScalar()   (I got runtime error when resumeFill() is not called.)
- add( A )  (If the input matrix A had different sparsity pattern, do I have to call resumeFill() before the call? )
- Also, Tpetra does not support operations like A+ cI (c is a scalar and I is identity).  What do you recommend for implementing this?

**Comment by mhoemmen** [comment]
You must call `resumeFill` whenever you change the CrsMatrix's values.

@keitat wrote:
> Tpetra::CrsMatrix requires resumeFill() when changing its sparsity pattern.

Generally you're not allowed to change a CrsMatrix's sparsity pattern after first fillComplete.

**Comment by mhoemmen** [comment]
@keitat wrote:
> Also, Tpetra does not support operations like A+ cI (c is a scalar and I is identity). What do you recommend for implementing this?

CrsMatrix has a method for getting the diagonal offsets.  You could start with that.

MueLu has a specialized "Jacobi" kernel that does something like `(A + omega D) * B`, where `omega` is a constant and `D` is a diagonal matrix.

**Comment by mhoemmen** [comment]
I'm closing this issue for now.  Please feel free to reopen or open a new issue if needed.  Thanks!
