### ISSUE TITLE
Tpetra: Add optional 'atomic' argument to sumIntoLocalValue(s)

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#31]
@trilinos/tpetra 

For `Tpetra::MultiVector`, `Tpetra::Vector`, and `Tpetra::CrsMatrix`, add an optional bool `atomic` argument to `sumIntoLocalValue` resp. `sumIntoLocalValues`.  If true, use `Kokkos::atomic_add` to do the `+=`; else, use `+=`.  The default value of `atomic` should depend on the class' execution space: it should be false if and only if the execution space is `Kokkos::Serial` (so that existing MPI-only users don't have to pay for atomic updates).

**Comment by srajama1** [comment]
Why would some one want to pass false with say OpenMP execution space. Won't that give you just wrong answer ?

**Comment by crtrott** [comment]
You might do coloring in the algorithm which calls sumInto. In that case you don't want to pay for atomics, if you avoid conflicts through other means.

**Comment by srajama1** [comment]
Can you Call sumInto on a sub problem with Tpetra ? The coloring has to be called by Tpetra to minimize the atomics, right ?

May be you are thinking of a case where the whole matrix has no conflicts. If that is the case, sure, go ahead. It is a very special case but reasonable. Expecting the user could coloring is not ideal. Tpetra has to color the graph and do the right thing. 

That is the primary use case for having coloring in the kernels.

**Comment by crtrott** [comment]
Yeah but sumInto is something you call inside the parallel kernel. It is not a global I work on everything function. And currently the parallelism in the assembly is not inside of Tpetra but in the application. So the application has to do the coloring. We might write another library for that, but I don't think tpetra can do it (at least I can't see the way to do that right now).

**Comment by srajama1** [comment]
Got it. I was thinking of a special case too. Given a static graph to Tpetra and a static partitioning of rows to threads, Tpetra will know exactly which rowids need atomics, right ?

**Comment by mhoemmen** [comment]
The discussion the three of us had Wednesday 25 Nov 2015 clarified the need for Tpetra sumInto to support the option of atomic updates.  In particular, Tpetra is too low a level of abstraction to know how applications want to do fill.  Example: for finite elements, knowing whether or not atomics are necessary for a particular row or matrix entry requires knowing the discretization order and the shape of elements (and thus needs a mapping from matrix entries back to element topology).  One can always build higher-level interfaces using the lower-level interface.  Furthermore, this interface will help applications gradually port to use Kokkos.  (They can start by turning on atomics everywhere, get correct answers perhaps with some performance loss, then explore using coloring or some other method to turn off atomics where they are not needed.)

**Comment by mhoemmen** [comment]
My commits on Thu 26 Nov 2015, committed tonight (Sat 28 Nov 2015), fix this issue.

**Comment by mhoemmen** [comment]
My commits on Thu 26 Nov 2015, committed tonight (Sat 28 Nov 2015), fix this issue.
