### ISSUE TITLE
Tpetra::FEMultiVector::doSourceToTarget throws error

### ISSUE THREAD

**Issue by kddevin** [trilinos/Trilinos#3101]
@trilinos/tpetra  

## Expectations
Tpetra::FEMultiVector::doSourceToTarget should update "ghost" values in the FEMultiVector from the "owning" processors' copies

## Current Behavior

It appears that doSourceToTarget is not called or tested anywhere.  When I tried to use it, I got the following error:

Throw number = 1
Throw test that evaluated to true: ! myMapSameAsTransferTgtMap
Tpetra::DistObject::doImport (forward mode): For forward-mode communication, the target DistObject's Map must be the same (in the sense of Tpetra::Map::isSameAs) as the input Export/Import object's target Map.
libc++abi.dylib: terminating with uncaught exception of type std::invalid_argument: /Users/kddevin/code/Trilinos/packages/tpetra/core/src/Tpetra_DistObject_def.hpp:456:

## Motivation and Context

Using FEMultiVector in Zoltan2 graph algorithm

## Definition of Done

Add a test exercising doSourceToTarget; here is the start of a test that can be used:
 in Trilinos branch zoltan2icesheet, file packages/zoltan2/test/temp/femv.cpp.
Fix the problem

## Steps to Reproduce

Current test is in Trilinos branch zoltan2icesheet, file packages/zoltan2/test/temp/femv.cpp.
make Zoltan2_femv
(Note:  as is, test cannot be used yet with explicit template instantiation.)

## Your Environment

- **Relevant repo SHA1s:**  
- **Relevant configure flags or configure script:**  
- **Operating system and version:**  
- **Compiler and TPL versions:**  

## Related Issues

* Blocks 
* Is blocked by 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of

**Comment by kddevin** [comment]
Added new branch fix3101 with simplified test demonstrating issue 
tpetra/core/test/FEMultiVector/Fix3101.cpp
For reproducing the bug, this test is clearer than the Zoltan2 test.

**Comment by kddevin** [comment]
Fixed by PR #3102

**Comment by mhoemmen** [comment]
Thanks @kddevin !
