### ISSUE TITLE
Failing ShyLU_DD tests in GCC 4.8.4 OpenMP CI and PR builds somehow pushed to 'develop' branch

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#3106]
@trilinos/framework, @trilinos/shylu, @searhein, @srajama1 (Trilinos Linear Solvers Product Lead)

The post-push CI build `Linux-GCC-4.8.4-MPI_RELEASE_DEBUG_SHARED_PT_OPENMP_CI` shown [here](https://testing-vm.sandia.gov/cdash/index.php?project=Trilinos&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=4&showfilters=1&filtercombine=and&field1=buildname&compare1=63&value1=-MPI_RELEASE_DEBUG_SHARED_PT&field2=groupname&compare2=61&value2=Continuous&field3=buildstarttime&compare3=84&value3=now&field4=buildstarttime&compare4=83&value4=4%20weeks%20ago) failed this morning for the first time in [this CI iteration](https://testing-vm.sandia.gov/cdash/index.php?project=Trilinos&parentid=3719977&filtercount=4&showfilters=1&field1=groupname&compare1=61&value1=Continuous&field2=buildstarttime&compare2=84&value2=now&field3=buildstarttime&compare3=83&value3=4%20weeks%20ago&filtercombine=and) due to the failing tests shown [here](https://testing-vm.sandia.gov/cdash/viewTest.php?onlyfailed&buildid=3719977) which were:

|Test Name | Status | Test Time | Details |
| :--  | :-- | :--   | :-- |
| ShyLU_DDFROSch_test_laplacian_epetra_2d_gdsw_MPI_4 | Failed | 1s 170ms | 4s 680ms | Completed (Failed) |
| ShyLU_DDFROSch_test_laplacian_epetra_2d_rgdsw_MPI_4 | Failed | 1s 170ms | 4s 680ms | Completed (Failed) |
| ShyLU_DDFROSch_test_interfacesets_2D_MPI_4 | Failed | 710ms | 2s 840ms | Completed (Failed) |
|ShyLU_DDFROSch_test_interfacepartitionofunity_MPI_4 | Failed | 700ms | 2s 800ms | Completed (Failed) |

Looking at the commits pulled this first CI iteration [here](https://testing-vm.sandia.gov/cdash/viewNotes.php?buildid=3720229#!#note2) it seems likely these failures are due to one of the commits by `Alexander Heinlein <alexander.heinlein@uni-köln.de>` (@searhein).

These failing ShyLU_DD tests did not only impact the post-push CI OpenMP build above but it also impacted the auto PR OpenMP build `PR-<pr-id>-test-Trilinos_pullrequest_gcc_4.8.4-<build-num>`.  For example, you can see this in the PR builds:

* [PR-3098-test-Trilinos_pullrequest_gcc_4.8.4-781](https://testing-vm.sandia.gov/cdash/index.php?project=Trilinos&parentid=3719867)
* [PR-3053-test-Trilinos_pullrequest_gcc_4.8.4-782](https://testing-vm.sandia.gov/cdash/index.php?project=Trilinos&parentid=3720319)

If you look, it is the same 4 failing tests.  If you look at those PR #3098 the changes in that branch don't impact ShyLU_DD or the PR builds in any way. 

https://testing-vm.sandia.gov/cdash/viewNotes.php?buildid=3720229#!#note2

**Comment by bartlettroscoe** [comment]
> @bartlettroscoe I just created a PR which disables the tests which cause trouble: #3107

@searhein, thanks for doing that.  I just approved the PR so as soon as auto PR testing completes, it should allow the merge.  (Then you can fix these offline and then post at new PR that re-enables them once you get it working.)

@trilinos/framework,

Can we do a root-cause analysis and see how these failing tests were able to get pushed to the 'develop' branch?  What this another example of a violation of the [additive test assumption of branches](https://docs.google.com/document/d/1uVQYI2cmNx09fDkHDA136yqDTqayhxqfvjFiuUue7wo/edit#bookmark=id.d1jneh8ubsyn)?  If not, what else could it be?

**Comment by jwillenbring** [comment]
@searhein Thank you for moving quickly on this. Do you know which change caused this issue (PR#) ? Then we can go and look at the PR testing for that. If not, I will go digging.

**Comment by searhein** [comment]
@jwillenbring I re-enabled the tests which cause the trouble on my branch. Otherwise, I cannot test Epetra. Then, I forgot to disable them before submitting the PR.

**Comment by srajama1** [comment]
@jwillenbring : To give you some context - I think the PR testing doesn't test configuration that ATDM tests catch.

**Comment by bartlettroscoe** [comment]
FYI: Note that these failing ShyLU_DD tests did not only impact the CI OpenMP build stated above but it also impacted the auto PR OpenMP build `PR-<pr-id>-test-Trilinos_pullrequest_gcc_4.8.4-<build-num>`.  For example, you can see this in the PR builds:

* [PR-3098-test-Trilinos_pullrequest_gcc_4.8.4-781](https://testing-vm.sandia.gov/cdash/index.php?project=Trilinos&parentid=3719867)
* [PR-3053-test-Trilinos_pullrequest_gcc_4.8.4-782](https://testing-vm.sandia.gov/cdash/index.php?project=Trilinos&parentid=3720319)

If you look, it is the same 4 failing tests.  If you look at those PR #3098 the changes in that branch don't impact ShyLU_DD or the PR builds in any way.  That is proof that these test failures were able to slip through PR testing somehow.  It would be good to know how this occurred so that we can avoid this again in the future.
