### ISSUE TITLE
Test Piro_AnalysisDriverTpetra_MPI_4 failing in ATDM builds after merge of PR #3055

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#3115]
CC: @trilinos/piro, @mperego, @fryeguy52, @rppawlo (Trilinos Nonlinear Solvers Product Lead)
 
## Next Action Status

PR #3116 was merged on 7/14/2018 which disables the test `Piro_AnalysisDriverTpetra_MPI_4` when ROL is not enabled and this test only run in the one ATDM build `Trilinos-atdm-sems-gcc-7-2-0` which does enable ROL on 7/15/2018.

## Description

As shown in [this query today](https://testing-vm.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-&field2=status&compare2=62&value2=Passed), the test `Piro_AnalysisDriverTpetra_MPI_4` is failing in many ATDM Trilinos builds.

The test output shown for, the build ` Trilinos-atdm-rhel6-gnu-debug-serial ` for example, [here](https://testing-vm.sandia.gov/cdash/testDetails.php?test=50452628&build=3722869) shows:

```
[sems-srn-rhel6-slave-02:44995] *** Process received signal ***
[sems-srn-rhel6-slave-02:44995] Signal: Segmentation fault (11)
[sems-srn-rhel6-slave-02:44995] Signal code: Address not mapped (1)
[sems-srn-rhel6-slave-02:44995] Failing at address: (nil)


Piro::PerformAnalysis() requests: ROL
ERROR: Trilinos/Piro was not configured to include 
        analysis type: ROL

Piro Analysis Finished successfully.
```

It looks like this test was added in PR #3055.

It seems this test does not work without ROL enabled.

## Steps to Reproduce

One should be able to reproduce this failure on any of the supported ATDM platforms as described in:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md

Since this error occurs in the SEMS-based 'rhel6' builds, that is likely the easiest place to reproduce this.  That would be the instructions at:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#sems-rhel6-environment

which for this case would be:

```
$ cd <some_build_dir>/

$ source $TRILINOS_DIR/cmake/std/atdm/load-env.sh gnu-debug-openmp

$ cmake \
  -GNinja \
  -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
  -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_Piro=ON \
  $TRILINOS_DIR

$ make NP=16

$ ctest -j16 \
```

**Comment by bartlettroscoe** [comment]
This test just needs to be enabled only if ROL support in Piro is enabled.  I will take care of this real quick and post a PR.

**Comment by bartlettroscoe** [comment]
PR #3116 was just merged and therefore we should see this failing test go away tomorrow.

**Comment by mperego** [comment]
Thanks @bartlettroscoe for taking care of this. We should do the same for the old EPETRA test
Piro_AnalysisDriver_MPI_4, that depends on Dakota, Moocho and ROL. Weird that it never failed.
