### ISSUE TITLE
Kokkos CMake error (fixed in kokkos:develop)

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#3118]
@trilinos/kokkos @trilinos/framework 

## Current Behavior

At least one Trilinos build on the Dashboard shows the following CMake error:
```
CMake Error at packages/kokkos/cmake/kokkos_functions.cmake:50 (string):
  Syntax error in cmake code at

    /home/jenkins/slave/workspace/Trilinos_apollo_gcc_4.9.3_cuda_8.0.44/MPI_RELEASE_DEV_DownStream_ETI_SERIAL-ON_OPENMP-OFF_PTHREAD-OFF_CUDA-ON_COMPLEX-OFF/Trilinos/packages/kokkos/cmake/kokkos_functions.cmake:50

  when parsing string

    [0-9]+\.[0-9]+\.[0-9]+$

  Invalid escape sequence \.
Call Stack (most recent call first):
  cmake/ProjectCompilerPostConfig.cmake:34 (set_kokkos_cxx_compiler)
  /home/jenkins/slave/workspace/Trilinos_apollo_gcc_4.9.3_cuda_8.0.44/Trilinos/cmake/tribits/core/package_arch/TribitsGlobalMacros.cmake:1847 (INCLUDE)
  /home/jenkins/slave/workspace/Trilinos_apollo_gcc_4.9.3_cuda_8.0.44/Trilinos/cmake/tribits/core/package_arch/TribitsProjectImpl.cmake:188 (TRIBITS_SETUP_ENV)
  /home/jenkins/slave/workspace/Trilinos_apollo_gcc_4.9.3_cuda_8.0.44/Trilinos/cmake/tribits/core/package_arch/TribitsProject.cmake:93 (TRIBITS_PROJECT_IMPL)
  CMakeLists.txt:90 (TRIBITS_PROJECT)
```
This is https://github.com/kokkos/kokkos/issues/1661 , which has been fixed in kokkos:develop by Kokkos PR https://github.com/kokkos/kokkos/pull/1662 .

## Possible Solution

Wait until the next Kokkos promotion into Trilinos.

## Related Issues
* Related to https://github.com/kokkos/kokkos/issues/1661

**Comment by ibaned** [comment]
@mhoemmen I believe this only happens for old CMake versions (< 3.0 ?) and I think @bartlettroscoe and I would rather increase our minimum required CMake version.

**Comment by mhoemmen** [comment]
@ibaned I think it's less than 3.3, but yes, it's definitely an issue only for old CMake versions.  I just wanted to note the current state in case people complain about the one configure failure on Trilinos' Dashboard ;-) .

**Comment by ibaned** [comment]
Yep, makes sense. I think if its a Trilinos dashboard build then its CMake should definitely be upgraded.

**Comment by bartlettroscoe** [comment]
@ibaned said:

>  I think if its a Trilinos dashboard build then its CMake should definitely be upgraded.

I am all for that (see #1761) .  My vote would be to upgrade the minimum version of CMake today to 3.11.1 but that would break a bunch of the Trilinos builds.  I think only the @trilinos/framework can fix those builds older versions of CMake.
