### ISSUE TITLE
Tpetra:  makeOptimizedColMapAndImport

### ISSUE THREAD

**Issue by kddevin** [trilinos/Trilinos#3129]
I propose simplifying the interface to `makeOptimizedColMapAndImport` and `makeOptimizedColMap`
Currently, `makeOptimizedColMapAndImport` returns `std::pair<map_type, RCP<import_type> >`,
and makeOptimizedColMap returns map_type.

Step 1:  change return arguments 
*  `makeOptimizedColMapAndImport` returns `std::pair<RCP<const map_type>, RCP<import_type>>`
*  `makeOptimizedColMap` returns `RCP<const map_type>`

Step 2:  remove makeImport bool from arguments of `makeOptimizedColMapAndImport`

@trilinos/tpetra 

Since this code is in `Tpetra::Details`, backward compatibility does not apply.
We should probably add a stable public interface.

## Your Environment

- **Relevant repo SHA1s:**  
- **Relevant configure flags or configure script:**  
- **Operating system and version:**  
- **Compiler and TPL versions:**  

## Related Issues

* Blocks 
* Is blocked by 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of

**Comment by mhoemmen** [comment]
FYI, as @csiefer2 pointed out over e-mail, the reason why `makeOptimizedColMapAndImport` needs to return the Import by pointer, is that CrsGraph does not construct an Import at all (`getImporter().get() == nullptr`) in the no-MPI / 1-MPI-process case.

**Comment by mhoemmen** [comment]
@kddevin I edited your bug description just to add backticks, since otherwise Markdown turns `RCP<const map_type>` into RCP.
