### ISSUE TITLE
Allow Epetra-free build of the Tpetra stack used by Albany

### ISSUE THREAD

**Issue by gahansen** [trilinos/Trilinos#313]
We have recently added the ability to build Albany without any dependence on Epetra, to simplify building the code when only the templated stack capabilities are desired.

It appears to be possible to create a specialized Epetra-free Trilinos configuration to support this build with changes to Stratimikos and Amesos2. A change in Teko is needed as a side effect.

Please see pull request #314 for the changes that were made to support the build, along with the CMake build configuration that supports this Albany build.

/cc @bartlettroscoe @rppawlo @eric-c-cyr

**Comment by bartlettroscoe** [comment]
Glen, sorry, I missed that you actually posted the PR #314 with your patches.  I looked at the changes and they look pretty good so far (will need to do more inspection and experimentation to be sure).  We can discuss the specifics of the changes in PR #314 in comments in that PR.

Are there also Issue tickets to update Amesos2 and Teko to build without Epetra?  If not, can we create those?  Then perhaps we can expand the scope of this Issue from "Make an Epetra-free build of Stratimikos work" to "Make an Epetra-free build of full Tpetra-based stack work".

**Comment by bartlettroscoe** [comment]
Okay, since the commit on PR #314 addresses Amesos2 and Teko, I will go ahead and expand the scope of this Issue ticket to "Make an Epetra-free build of the Tpetra stack used by Albany".

**Comment by ibaned** [comment]
#1023 is all we need to get this done

**Comment by ibaned** [comment]
#1023 was accepted into develop, which means this issue is resolved, assuming those commits get into master.

**Comment by bartlettroscoe** [comment]
@ibaned,

It looks like our commits pushed as part of #1023 broke the build of Stratimikos when Epetra is disabled.  For example, see:

* http://testing.sandia.gov/cdash/index.php?project=Trilinos&parentid=2733758&filtercount=3&showfilters=1&field1=buildstamp&compare1=61&value1=20170207-0400-Nightly&filtercombine=and
* http://testing.sandia.gov/cdash/index.php?project=Trilinos&parentid=2734625&filtercount=3&showfilters=1&field1=buildstamp&compare1=61&value1=20170208-0400-Nightly&filtercombine=and

I don't think we ever tested the build of the Trilinos stack of packages and tests without Epetra, did we?  I did not realize that anyone was testing the full build of Trilinos minus Epetra.  I am glad to see that someone is (but they did not set the enables/disables correctly on the outer CTest driver so we see Epetra being built).  I guess we need to test building all of Trilinos minus Epetra and fix anything that comes up.

At the very least we need to get Stratimikos to build correctly without Epetra.

I will give this a try locally and see what comes up.

**Comment by ibaned** [comment]
@bartlettroscoe  I did test one Epetra-free build. Its not just the absence of Epetra, its that this failing build also enabled ML (weird combination), and Stratimikos tries to build its ML interface but that interface requires Epetra. I just opened #1053 with a possible fix which I'm testing now.

**Comment by tjfulle** [comment]
@bartlettroscoe , Galeri tests/examples also fail to build without Epetra.  The Galeri library builds without Epetra.  See #1033

**Comment by ibaned** [comment]
@tjfulle what I did for Stratimikos was to [set TEST_REQUIRED_DEP_PACKAGES](https://github.com/trilinos/Trilinos/commit/9abecfd3c2502a2c48ce38f06f89299e35674756#diff-b0eccaf419bc7cf3c1a971a763ffc1c9R8), so its tests/examples won't build if Epetra is off but the library will.

**Comment by bartlettroscoe** [comment]
This should not be fixed as part #1053.

Putting into review to see how the builds come out tomorrow.

**Comment by bartlettroscoe** [comment]
I have not seen any failures related to this since pushing the fixing commits.  Closing.
