### ISSUE TITLE
Teuchos: Dynamic Cast Errors from XML-read Array<string>

### ISSUE THREAD

**Issue by csiefer2** [trilinos/Trilinos#3130]
A Trilinos test.  I have an XML file with lines like this:
```
  <Parameter name="avatar: decision tree files" type="Array(string)" value="{'avatar.trees'}"/>
```
I rely on the Teuchos XML reader to read that.  

I do this:
```c++
const Teuchos::Array<std::string> & tf = params_.get<const Teuchos::Array<std::string> >(paramName);
```

I get this error:

    > p=0: *** Caught standard std::exception of type 'std::logic_error' :
    > 
    >   /ascldap/users/csiefer/Trilinos/sandbox5/Trilinos/packages/teuchos/core/src/
    > Teuchos_any.hpp:361:
    > 
    >   Throw number = 1
    > 
    >   Throw test that evaluated to true: !dyn_cast_content
    > 
    >   any_cast<Teuchos::Array<std::string>>(operand): Error, cast to type
    > any::holder<Teuchos::Array<std::string>> failed but should not have and
    > the actual underlying type is
    > 'Teuchos::any::holder<Teuchos::Array<std::string> >! The problem might
    > be related to incompatible RTTI systems in static and shared libraries!

**Comment by mhoemmen** [comment]
@csiefer2 I added formatting to your bug description, since Markdown was making the HTML text disappear.

**Comment by bartlettroscoe** [comment]
@csiefer2, what are the reproducability instructions to show this behavior?  What platform are you on?  What compiler and CMake version are you using?  What is your configure script? etc.

**Comment by csiefer2** [comment]
@mhoemmen Removing the consts yields the compile error:

 error: invalid initialization of reference of type ‘Teuchos::Array<std::basic_string<char> >&’ from expression of type ‘const Teuchos::Array<std::basic_string<char> >’
   Teuchos::Array<std::string> & tf = params_.get<Teuchos::Array<std::string> >(paramName);

**Comment by csiefer2** [comment]
@bartlettroscoe My RHEL6 desktop, gcc 4.9.3 and cmake 3.7.2 in that order  If you want a self-contained example, I can do that.

**Comment by csiefer2** [comment]
Example code:

``#include <string>
#include "Teuchos_oblackholestream.hpp"
#include "Teuchos_GlobalMPISession.hpp"
#include "Teuchos_TimeMonitor.hpp"
#include "Teuchos_XMLParameterListHelpers.hpp"
#include "Teuchos_StandardCatchMacros.hpp"
#include "Teuchos_DefaultComm.hpp"

using Teuchos::RCP;
using Teuchos::rcp;
using Teuchos::Comm;
using Teuchos::outArg;
using Teuchos::MpiComm;
using Teuchos::ParameterList;

int main (int argc, char *argv[]) {
  Teuchos::oblackholestream blackHole;
  Teuchos::GlobalMPISession mpiSession (&argc, &argv, &blackHole);

  {

    RCP<const Comm<int> > comm = rcp (new MpiComm<int> (MPI_COMM_WORLD));

    ParameterList inputList;
    Teuchos::updateParametersFromXmlFile("fail.xml",outArg (inputList));
    
    ParameterList avatarParams = inputList.sublist("Avatar-MueLu");
    
    const char * paramName = "avatar: decision tree files";
    const Teuchos::Array<std::string> & tf = avatarParams.get<const Teuchos::Array<std::string> >(paramName);

    

  }

}

**Comment by csiefer2** [comment]
I might add the example code works fine if I don't use the consts...

**Comment by csiefer2** [comment]
Also, Markdown is weird.

**Comment by csiefer2** [comment]
I have a workaround for this now, so this issue does not need to be high priority.
