### ISSUE TITLE
Stratimikos::enableMueLu template parameter defaults don't match Tpetra's

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#3131]
@trilinos/stratimikos @trilinos/muelu @trilinos/thyra 

`Stratimikos::enableMueLu` is supposed to enable use of Tpetra+MueLu through Thyra.  However, `enableMueLu`'s template parameters' defaults do not match those of Tpetra.

https://github.com/trilinos/Trilinos/blob/b85258adb40e5ba84e1c31e031ac4175a2c2eee4/packages/muelu/adapters/stratimikos/Stratimikos_MueLuHelpers.hpp#L71

## Related issues

* Blocks #2548, #57

**Comment by bartlettroscoe** [comment]
What is the proper fix?

**Comment by mhoemmen** [comment]
@bartlettroscoe It depends: Does `enableMueLu` only enable use of Tpetra + MueLu, or does it also enable the Epetra + MueLu option?

**Comment by cgcgcg** [comment]
@mhoemmen When I grep for `enableMueLu`, I find only a couple of spots where the function is used:
```
packages/piro/src/Piro_InvertMassMatrixDecorator_Def.hpp
109:  Stratimikos::enableMueLu<LocalOrdinal, GlobalOrdinal, Node>(linearSolverBuilder);
118:  Stratimikos::enableMueLu(linearSolverBuilder);

packages/piro/src/Piro_TempusSolver_Def.hpp
199:    Stratimikos::enableMueLu<LocalOrdinal, GlobalOrdinal, Node>(linearSolverBuilder);
201:    Stratimikos::enableMueLu(linearSolverBuilder);

packages/piro/src/Piro_RythmosSolver_Def.hpp
373:     Stratimikos::enableMueLu<LocalOrdinal, GlobalOrdinal, Node>(linearSolverBuilder);
375:     Stratimikos::enableMueLu(linearSolverBuilder);

packages/trilinoscouplings/examples/scaling/example_Maxwell.cpp
2651:  Stratimikos::enableMueLuRefMaxwell<LO,GO,Node>(linearSolverBuilder);                // Register MueLu as a Stratimikos preconditioner strategy.

packages/muelu/test/maxwell/Maxwell3D.cpp
516:      Stratimikos::enableMueLuRefMaxwell<LocalOrdinal,GlobalOrdinal,Node>(linearSolverBuilder);                // Register MueLu as a Stratimikos preconditioner strategy.

packages/muelu/research/q2q1/Q2Q1.cpp
337:    Stratimikos::enableMueLu(linearSolverBuilder);                                          // Epetra
338:    Stratimikos::enableMueLuTpetraQ2Q1<LO,GO,NO>(linearSolverBuilder, "MueLu-TpetraQ2Q1");  // Tpetra

packages/muelu/example/advanced/stratimikos/Stratimikos.cpp
178:    Stratimikos::enableMueLu<LocalOrdinal,GlobalOrdinal,Node>(linearSolverBuilder);                // Register MueLu as a Stratimikos preconditioner strategy.
276:    // Stratimikos::enableMueLu<LocalOrdinal,GlobalOrdinal,Node>(linearSolverBuilder);                // Register MueLu as a Stratimikos preconditioner strategy.

packages/panzer/adapters-stk/src/Panzer_STK_SetupLOWSFactory_impl.hpp
193:      Stratimikos::enableMueLu(linearSolverBuilder,"MueLu");
194:      Stratimikos::enableMueLuRefMaxwell(linearSolverBuilder,"MueLuRefMaxwell");
195:      Stratimikos::enableMueLu<int,panzer::Ordinal64,panzer::TpetraNodeType>(linearSolverBuilder,"MueLu-Tpetra");
196:      Stratimikos::enableMueLuRefMaxwell<int,panzer::Ordinal64,panzer::TpetraNodeType>(linearSolverBuilder,"MueLuRefMaxwell-Tpetra");
```

From the looks of it, we use the default template arguments when we want Epetra, and explicitly template for Tpetra..

**Comment by mhoemmen** [comment]
@cgcgcg wrote:
> From the looks of it, we use the default template arguments when we want Epetra, and explicitly template for Tpetra.

Could the template parameters overlap?  For example, could `int, int, EpetraNode` map either to Epetra or to Tpetra with `GlobalOrdinal=int` and `Node=Wrapper<Serial>`?

**Comment by cgcgcg** [comment]
@mhoemmen Yes, they could overlap. We have
```
#ifdef HAVE_XPETRA_EPETRA
# ifdef EPETRA_HAVE_OMP
  typedef Kokkos::Compat::KokkosOpenMPWrapperNode EpetraNode;
# else
  typedef Kokkos::Compat::KokkosSerialWrapperNode EpetraNode;
# endif
#else
  // We can instantiate Xpetra::Tpetra objects for EpetraNode.  So this has to be defined.
  typedef Kokkos::Compat::KokkosSerialWrapperNode EpetraNode;
#endif
````

**Comment by mhoemmen** [comment]
@cgcgcg How does `Stratimikos::enableMueLu` work in the case where they overlap?  Does `enableMueLu` _only_ initialize Tpetra+MueLu, or does it _also_ initialize Epetra+MueLu?

**Comment by mhoemmen** [comment]
Here's my thinking: Tpetra is getting rid of LocalOrdinal and GlobalOrdinal template parameters anyway.  It may also get rid of Node.  This means that `enableMueLu` won't need any template parameters at all.  Would it make sense to wait for that point?

**Comment by cgcgcg** [comment]
@mhoemmen I believe that we are essentially registering the same solver twice, once with the string identifier "MueLu" (for Epetra), and once named "MueLu-Tpetra" (for Tpetra). Once we get rid of Local/GlobalOrdinal, Tpetra will always use different types than Epetra, so this problem should go away, no?

**Comment by mhoemmen** [comment]
@cgcgcg wrote:
> Once we get rid of Local/GlobalOrdinal, Tpetra will always use different types than Epetra, so this problem should go away, no?

At that point, `enableMueLu` should not need any template parameters, right?  It would just register both Epetra and Tpetra.

**Comment by cgcgcg** [comment]
@mhoemmen Not sure how the Tpetra node type will be handled, but yes, that seems correct.

**Comment by hillyuan** [comment]
I encounter compile error due to this problem, when compiling panzer with cuda. The error message looks like

> Trilinos/packages/teuchos/core/src/Teuchos_RCP.hpp(297): error: a value of type "const Tpetra::Map<MueLu::DefaultLocalOrdinal, MueLu::DefaultGlobalOrdinal, MueLu::DefaultNode> *" cannot be used to initialize an entity of type "const Tpetra::Map<panzer::LocalOrdinal, panzer::GlobalOrdinal, panzer::TpetraNodeType> *"
          detected during:
            instantiation of "Teuchos::RCP<T>::RCP(const Teuchos::RCP<T2> &) [with T=const Tpetra::Map<panzer::LocalOrdinal, panzer::GlobalOrdinal, panzer::TpetraNodeType>, T2=const Tpetra::Map<MueLu::DefaultLocalOrdinal, MueLu::DefaultGlobalOrdinal, MueLu::DefaultNode>]" 
Trilinos/packages/tpetra/core/ext/TpetraExt_MatrixMatrix_Cuda.hpp(656): here
            instantiation of "void Tpetra::MMdetails::KernelWrappers2<Scalar, LocalOrdinal, GlobalOrdinal, Kokkos::Compat::KokkosCudaWrapperNode, LocalOrdinalViewType>::jacobi_A_B_newmatrix_KokkosKernels(Scalar, const Tpetra::Vector<Scalar, LocalOrdinal, GlobalOrdinal, Kokkos::Compat::KokkosCudaWrapperNode> &, Tpetra::CrsMatrixStruct<Scalar, LocalOrdinal, GlobalOrdinal, Kokkos::Compat::KokkosCudaWrapperNode> &, Tpetra::CrsMatrixStruct<Scalar, LocalOrdinal, GlobalOrdinal, Kokkos::Compat::KokkosCudaWrapperNode> &, const LocalOrdinalViewType &, const LocalOrdinalViewType &, const LocalOrdinalViewType &, const LocalOrdinalViewType &, Tpetra::CrsMatrix<Scalar, LocalOrdinal, GlobalOrdinal, Kokkos::Compat::KokkosCudaWrapperNode> &, Teuchos::RCP<const Tpetra::Import<LocalOrdinal, GlobalOrdinal, Kokkos::Compat::KokkosCudaWrapperNode>>, const std::__cxx11::string &, const Teuchos::RCP<Teuchos::ParameterList> &) [with Scalar=MueLu::DefaultScalar, LocalOrdinal=MueLu::DefaultLocalOrdinal, GlobalOrdinal=MueLu::DefaultGlobalOrdinal, LocalOrdinalViewType=Kokkos::View<int *, Kokkos::Cuda::array_layout, Kokkos::Device<Kokkos::CudaUVMSpace::execution_space, Kokkos::CudaUVMSpace::memory_space>>]" 
Trilinos/packages/tpetra/core/ext/TpetraExt_MatrixMatrix_Cuda.hpp(437): here
            instantiation of "void Tpetra::MMdetails::KernelWrappers2<Scalar, LocalOrdinal, GlobalOrdinal, Kokkos::Compat::KokkosCudaWrapperNode, LocalOrdinalViewType>::jacobi_A_B_newmatrix_kernel_wrapper(Scalar, const Tpetra::Vector<Scalar, LocalOrdinal, GlobalOrdinal, Kokkos::Compat::KokkosCudaWrapperNode> &, Tpetra::CrsMatrixStruct<Scalar, LocalOrdinal, GlobalOrdinal, Kokkos::Compat::KokkosCudaWrapperNode> &, Tpetra::CrsMatrixStruct<Scalar, LocalOrdinal, GlobalOrdinal, Kokkos::Compat::KokkosCudaWrapperNode> &, const LocalOrdinalViewType &, const LocalOrdinalViewType &, const LocalOrdinalViewType &, const LocalOrdinalViewType &, Tpetra::CrsMatrix<Scalar, LocalOrdinal, GlobalOrdinal, Kokkos::Compat::KokkosCudaWrapperNode> &, Teuchos::RCP<const Tpetra::Import<LocalOrdinal, GlobalOrdinal, Kokkos::Compat::KokkosCudaWrapperNode>>, const std::__cxx11::string &, const Teuchos::RCP<Teuchos::ParameterList> &) [with Scalar=MueLu::DefaultScalar, LocalOrdinal=MueLu::DefaultLocalOrdinal, GlobalOrdinal=MueLu::DefaultGlobalOrdinal, LocalOrdinalViewType=Kokkos::View<int *, Kokkos::Cuda::array_layout, Kokkos::Device<Kokkos::CudaUVMSpace::execution_space, Kokkos::CudaUVMSpace::memory_space>>]" 
Trilinos/packages/tpetra/core/ext/TpetraExt_MatrixMatrix_def.hpp(2325): here
            instantiation of "void Tpetra::MMdetails::jacobi_A_B_newmatrix(Scalar, const Tpetra::Vector<Scalar, LocalOrdinal, GlobalOrdinal, Node> &, Tpetra::CrsMatrixStruct<Scalar, LocalOrdinal, GlobalOrdinal, Node> &, Tpetra::CrsMatrixStruct<Scalar, LocalOrdinal, GlobalOrdinal, Node> &, Tpetra::CrsMatrix<Scalar, LocalOrdinal, GlobalOrdinal, Node> &, const std::__cxx11::string &, const Teuchos::RCP<Teuchos::ParameterList> &) [with Scalar=MueLu::DefaultScalar, LocalOrdinal=MueLu::DefaultLocalOrdinal, GlobalOrdinal=MueLu::DefaultGlobalOrdinal, Node=MueLu::DefaultNode]" 
Trilinos/packages/tpetra/core/ext/TpetraExt_MatrixMatrix_def.hpp(435): here
            instantiation of "void Tpetra::MatrixMatrix::Jacobi(Scalar, const Tpetra::Vector<Scalar, LocalOrdinal, GlobalOrdinal, Node> &, const Tpetra::CrsMatrix<Scalar, LocalOrdinal, GlobalOrdinal, Node> &, const Tpetra::CrsMatrix<Scalar, LocalOrdinal, GlobalOrdinal, Node> &, Tpetra::CrsMatrix<Scalar, LocalOrdinal, GlobalOrdinal, Node> &, __nv_bool, const std::__cxx11::string &, const Teuchos::RCP<Teuchos::ParameterList> &) [with Scalar=MueLu::DefaultScalar, LocalOrdinal=MueLu::DefaultLocalOrdinal, GlobalOrdinal=MueLu::DefaultGlobalOrdinal, Node=MueLu::DefaultNode]" 
Trilinos/packages/xpetra/sup/Utils/Xpetra_IteratorOps.hpp(104): here
            [ 20 instantiation contexts not shown ]
            instantiation of "Teuchos::AbstractFactoryStd<T_itfc, T_impl, T_PostMod, T_Allocator>::AbstractFactoryStd(const T_PostMod &, const T_Allocator &) [with T_itfc=Thyra::PreconditionerFactoryBase<double>, T_impl=Thyra::MueLuPreconditionerFactory<double, MueLu::DefaultLocalOrdinal, MueLu::DefaultGlobalOrdinal, MueLu::DefaultNode>, T_PostMod=Teuchos::PostModNothing<Thyra::MueLuPreconditionerFactory<double, MueLu::DefaultLocalOrdinal, MueLu::DefaultGlobalOrdinal, MueLu::DefaultNode>>, T_Allocator=Teuchos::AllocatorNew<Thyra::MueLuPreconditionerFactory<double, MueLu::DefaultLocalOrdinal, MueLu::DefaultGlobalOrdinal, MueLu::DefaultNode>>]" 
Trilinos/packages/teuchos/core/src/Teuchos_AbstractFactoryStd.hpp(173): here
            instantiation of "Teuchos::RCP<const Teuchos::AbstractFactory<T_itfc>> Teuchos::abstractFactoryStd<T_itfc,T_impl>() [with T_itfc=Thyra::PreconditionerFactoryBase<double>, T_impl=Thyra::MueLuPreconditionerFactory<double, MueLu::DefaultLocalOrdinal, MueLu::DefaultGlobalOrdinal, MueLu::DefaultNode>]" 
Trilinos/packages/muelu/adapters/stratimikos/Stratimikos_MueLuHelpers.hpp(84): here
            instantiation of "void Stratimikos::enableMueLu(Stratimikos::DefaultLinearSolverBuilder &, const std::__cxx11::string &) [with LocalOrdinal=MueLu::DefaultLocalOrdinal, GlobalOrdinal=MueLu::DefaultGlobalOrdinal, Node=MueLu::DefaultNode]" 
Trilinos/packages/piro/src/Piro_RythmosSolver_Def.hpp(353): here
            instantiation of "void Piro::RythmosSolver<Scalar>::initialize(const Teuchos::RCP<Teuchos::ParameterList> &, const Teuchos::RCP<Thyra::ModelEvaluator<Scalar>> &, const Teuchos::RCP<Rythmos::IntegrationObserverBase<Scalar>> &) [with Scalar=double]" 
Trilinos/packages/panzer/adapters-stk/src/Panzer_STK_ModelEvaluatorFactory_impl.hpp(1262): here
            instantiation of "Teuchos::RCP<Thyra::ModelEvaluator<ScalarT>> panzer_stk::ModelEvaluatorFactory<ScalarT>::buildResponseOnlyModelEvaluator(const Teuchos::RCP<Thyra::ModelEvaluator<ScalarT>> &, const Teuchos::RCP<panzer::GlobalData> &, Teuchos::RCP<Piro::RythmosSolver<ScalarT>>, const Teuchos::Ptr<const panzer_stk::NOXObserverFactory> &, const Teuchos::Ptr<const panzer_stk::RythmosObserverFactory> &) [with ScalarT=double]" 
Trilinos/packages/panzer/adapters-stk/src/Panzer_STK_ModelEvaluatorFactory_impl.hpp(1172): here

It says we cannot convert panzer::LocalOrdinal, panzer::GlobalOrdinal to MueLu::DefaultLocalOrdinal, MueLu::DefaultGlobalOrdinal.

I solved those errors by the following code

```
#ifdef HAVE_PIRO_MUELU
      using local_ordinal_type = Tpetra::Map<>::local_ordinal_type;
      using global_ordinal_type = Tpetra::Map<>::global_ordinal_type;
      using node_type = Tpetra::Map<>::node_type;
      Stratimikos::enableMueLu<local_ordinal_type, global_ordinal_type, node>(linearSolverBuilder);
#endif
```

Do it a reasonable modification?

**Comment by cgcgcg** [comment]
@hillyuan Can you show your CMake configure log? I'm trying to understand under which circumstances this arises.

**Comment by hillyuan** [comment]
Thanks @cgcgcg, Log files are attached.
[log.zip](https://github.com/trilinos/Trilinos/files/5144655/log.zip)

**Comment by cgcgcg** [comment]
@hillyuan No, I'd like to see how you invoke cmake, and the resulting console output. Thanks!

**Comment by hillyuan** [comment]
OK! My cmake options are follows:

> cmake .. \
  -DCMAKE_INSTALL_PREFIX:FILEPATH="~/programs/solver/Trilinos1/install" \
  -DCMAKE_CXX_COMPILER=${HOME}/programs/solver/Trilinos1/packages/kokkos/bin/nvcc_wrapper \
  -DCMAKE_BUILD_TYPE:STRING=RELEASE \
  -DTPL_ENABLE_MPI:BOOL=ON \
  -DTPL_ENABLE_CUDA=ON \
  -DTrilinos_ENABLE_KokkosKernels=ON \
  -DKokkos_ENABLE_CUDA=ON \
  -DKokkos_ENABLE_CUDA_UVM=ON \
  -DKokkos_ENABLE_CUDA_Lambda:BOOL=ON \
  -DKokkos_ARCH_PASCAL61=ON \
  -DKokkos_ENABLE_OPENMP:BOOL=ON \
  -DTrilinos_ENABLE_OpenMP:BOOL=ON  \
  -DTrilinos_ENABLE_Cuda=ON \
  -DTPL_ENABLE_HDF5=ON  \
  -DTPL_ENABLE_HWLOC=ON  \
  -DTPL_ENABLE_Matio=OFF  \
  -DTPL_ENABLE_CGNS=OFF  \
  -DTPL_ENABLE_LAPACK=ON  \
  -DTrilinos_ENABLE_Fortran=ON \
  -DTrilinos_ENABLE_Stokhos=OFF \
  -DTrilinos_ENABLE_Tempus=ON \
  -DTrilinos_ENABLE_SEACAS=ON \
  -DTrilinos_ENABLE_Sundance=OFF \
  -DTrilinos_ENABLE_Panzer=ON  \
  -DTrilinos_ENABLE_Moertel=OFF \
  -DTrilinos_ENABLE_STK=ON  \
  -DTrilinos_ENABLE_TESTS=OFF \
  -DPiro_ENABLE_TESTS=OFF  \
  -DTempus_ENABLE_TESTS=OFF  \
  -DMoertel_ENABLE_EXAMPLES=OFF  \
  -DKokkos_ENABLE_DEPRECATED_CODE=OFF \
  -DTrilinos_ENABLE_DEPRECATED_CODE=OFF \
  -DTpetra_ENABLE_DEPRECATED_CODE=OFF \
$EXTRA_ARGS \


Its output is given in the attached file
[cmake.log](https://github.com/trilinos/Trilinos/files/5145030/cmake.log)

**Comment by cgcgcg** [comment]
I believe that `D Trilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON` might fix the issue.

**Comment by bartlettroscoe** [comment]
Because implicit template instantiation is so expensive, I don't think there are any maintained automated nightly CUDA builds of Trilinos that have `Trilinos_ENABLE_EXPLICIT_INSTANTIATION=OFF`.

**Comment by hillyuan** [comment]
> I believe that D Trilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON might fix the issue.

It works well although I still don't understand what this option mean. Thank you very much @cgcgcg @bartlettroscoe

**Comment by bartlettroscoe** [comment]
> > I believe that D Trilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON might fix the issue.
> 
> ... I still don't understand what this option mean.

@hillyuan,

For the mechanics of this, see section "GCG 28: Break up templated code into four files SomeClass decl.hpp,
SomeClass def.hpp, SomeClass.hpp, and SomeClass.cpp to support both implicit and
explicit instantiation, minimize recompilation, and avoid problems in mutually dependent (i.e.
circular) declarations" at:

* https://docs.trilinos.org/dev/packages/thyra/doc/html/ThyraCodingGuideLines.pdf

Otherwise, if you don't write templated C++ code yourself, count yourself lucky.

**Comment by brian-kelley** [comment]
@bartlettroscoe In practice, do we really support/maintain builds without ETI?

**Comment by bartlettroscoe** [comment]
> In practice, do we really support/maintain builds without ETI?

@brian-kelley, I think Sierra still uses implicit template instantiation with Trilinos but that may have changed in the last few years.  Someone would need to check.

But not that some packages like Panzer are switching over to use only ETI with no option for implicit template instantiation.

**Comment by rppawlo** [comment]
@brian-kelley - The product leads had a quick discussion about this today. According to @jwillenbring - the PR tester does build both with and without ETI. The trilinos configure default is currently to disable ETI so many external customers may still be using the no-ETI path. The change to make ETI the default is non-backwards compatible and so was never made due to disrupting user builds. We have decided to make ETI=ON the default but will need to notify applications about this and give teams an opportunity to change. The no-ETI path makes sense for applications that want to inject their own data types into Tpetra. I'm not sure we could ever give up no-ETI support completely for the solver stack.

**Comment by bartlettroscoe** [comment]
> the PR tester does build both with and without ETI.

But not for CUDA.

**Comment by rppawlo** [comment]
> But not for CUDA.

probably not. Based on Jim's comments I think only one build disables eti. The rest use it.

**Comment by vbrunini** [comment]
> @brian-kelley, I think Sierra still uses implicit template instantiation with Trilinos but that may have changed in the last few years. Someone would need to check.

Sierra no longer uses implicit instantiation, we've had ETI turned on for a year or two.

**Comment by bartlettroscoe** [comment]
> Sierra no longer uses implicit instantiation, we've had ETI turned on for a year or two.

That is great news.  With that being the case, Trilinos should change the default to ETI turned on.  I would guess that this will be the best setting for 99% of Trilinos customers.  (And for the 1% that needs new data-types with Tpetra, we should likely extend the CMake build system to support the ETI of those types as well.)

@rppawlo, can we ask the Trilinos Product Leads to make that change for Trilinos?  We can make this a one-line change in Trilinos.

**Comment by rppawlo** [comment]
@bartlettroscoe - It was decided yesterday to do this, but not until we notify both internal and external customers. Since it is a non-backwards compatible change that will most likely break tons of user build scripts we want to give people time to make changes.

**Comment by bartlettroscoe** [comment]
> Since it is a non-backwards compatible change that will most likely break tons of user build scripts we want to give people time to make changes.

@rppawlo, it sounds like most customers were already turning on ETI so the impact may not be as large as one might think.
