### ISSUE TITLE
Get Trilinos auto PR testing code to use TriBITS-based package enable logic

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#3133]
CC: @william76, @jwillenbring 

## Next Action Status

With the merge of PR  #3258 8/14/2018 this should be complete.  Next: Watch PRs over next week and ensure that right set of packages are being enabled and then close on 8/21/2018 if all looks good ...

## Description

This story is to get the Trilinos auto PR testing code to use TriBITS-based logic for determining what to enable and test based on files that are changed in the PR branch.

The benefits of making this change are:

* When the set of Primary Tested packages changes, the code will automatically adjust

* Specialized logic can be applied to determine if all packages need to be tested or not.  For example, if files are changed under `Trilinos/cmake/ctest/drivers` then that should not trigger the auto PR tester to test all of Trilinos.

**Comment by bartlettroscoe** [comment]
FYI: As described in https://github.com/trilinos/Trilinos/pull/3134#issuecomment-405724627, the PR #3134 now contains the script `/get-changed-trilinos-packages.sh` which completely generates the `packageEnables.cmake` file.   Hopefully that will be easy to plug into the Trilinos auto PR testing infrastructure.

**Comment by bartlettroscoe** [comment]
FYI: I updated PR #3134 with a complete implementation of `get-changed-trilinos-packages.sh` with specialized logic for Trilinos for what file changes should trigger a global rebuild and strong automated tests.

@william76 and @jwillenbring, can you please give PR #3134 a review?

**Comment by bartlettroscoe** [comment]
@william76 and @jwillenbring,

FYI: PR #3134 was merged and the script `Trilinos/commonTools/framework/get-changed-trilinos-packages.sh` should be ready to use in the Trilinos auto PR tester.  Please let me know if you find any issues with this.

@william76, I will assign this issue to you next since I think the next step is yours (i.e. adding a hook into the Trilinos auto PR tester).

**Comment by bartlettroscoe** [comment]
@william76 and @jwillenbring, I just realized that the script `get-changed-trilinos-packages.sh` should likely be called `get-trilinos-packages-to-test-due-to-changes.sh` or something like that.

**Comment by william76** [comment]
@bartlettroscoe 
Cool!  I'm working on setting this up with the PR system.  So far it's working in my sandbox... Quick question... where does CTest expect the `packageEnables.cmake` to be?  Can I give it a command line option that will load it from any location if I want to?

**Comment by bartlettroscoe** [comment]
> Cool! I'm working on setting this up with the PR system. So far it's working in my sandbox... Quick question... where does CTest expect the packageEnables.cmake to be? Can I give it a command line option that will load it from any location if I want to?

@william76, I don't know the answer to that.  I have never seen the ctest -S driver script and related scripts that are used to drive PR testing.  If the T[riBITS CTest -S driver code](https://tribits.org/doc/TribitsDevelopersGuide.html#tribits-ctest-driver) was being used, I could tell you with that.

**Comment by bartlettroscoe** [comment]
FYI: I talked with @william76 yesterday and he said that he has everything working on a branch using the new script `Trilinos/commonTools/framework/get-changed-trilinos-packages.sh`.  He said that he will post a PR soon to update the Trilinos PR system and get some more review before merging it.

This will help to avoid cases like PR #3211 where PR builds can crash and fail due to system issues and block a PR from getting merged that don't need to run any PR builds (because those file changes can't break PR builds).

**Comment by william76** [comment]
@bartlettroscoe @jwillenbring @prwolfe @allevin 

My testing job seems to have worked in the first run after getting my branches sorted out.  In this case, I just modified one file down in Tpetra.
- [Jenkins Console][1]
- [CDash Link][1]

I'll run some more later with some silly edits in places that shouldn't kick off a rebuild such as a test driver or something like that.

[1]: https://ascic-jenkins.sandia.gov/job/trilinos-folder/job/Trilinos_pullrequest_gcc_4.9.3_wcmclen_test/8/console
[2]: https://testing-vm.sandia.gov/cdash/index.php?project=Trilinos&display=project&filtercombine=and&filtercount=2&showfilters=1&filtercombine=and&field1=site&compare1=61&value1=ascic141&field2=buildname&compare2=61&value2=PR-3196-test-Trilinos_pullrequest_gcc_4.9.3_wcmclen_test-8

**Comment by bartlettroscoe** [comment]
FYI: PR #3218 was merged on 8/5/2018 which switched the GCC 4.9.3 and Intel 17.0.1 PR builds over to this new logic.  But the GCC 4.8.4 PR build uses a different driver script and therefore was not impacted.  I talked with @william76 and he said that @prwolfe is going to switch over remaining GCC 4.8.4 PR build to use the same version-controlled driver script merged in #3218.   There is also the follow-on PR #3239 (which just deletes some commented-out debugging code).

Once the GCC 4.8.4 PR build is updated to use the same driver script, then we will be set and we can close this issue!

**Comment by bartlettroscoe** [comment]
@william76 and @jwillenbring,

I created the PR #3258 to address the issue described [above](https://github.com/trilinos/Trilinos/issues/3133#issuecomment-411445144) and approve the PR?  The updated unit tests of  `get-changed-trilinos-packages.sh` should ensure this keeps working correctly.

**Comment by bartlettroscoe** [comment]
FYI: Getting this story completed will help to avoid PR failures due to unrelated issues like #3263 that just bit me.  But just merging #3258 would not have been enough.  We also need to get the GCC 4.8.4 PR build to use the same driver script since the randomly failing test described in #3263 seems to only impact the GCC 4.8.4 + OpenMP build.

**Comment by bartlettroscoe** [comment]
@trilinos/framework,

Can you please review and merge PR #3258 and then get the Jenkins job that runs he GCC 4.8.4 PR build to use PullRequestLinuxDriver.sh correctly?  That should complete this PR.

This would really help my work with the ATDM Trilinos builds.  An important ATDM Trilinos PR #3260 has had two failed PR iterations due to random failures (see #3263).

**Comment by bartlettroscoe** [comment]
As @william76 mentioned someone (which I can't find), it looks like the GCC 4.8.4 PR build is using the scripts `get-changed-trilinos-packages.sh` and `PullRequestLinuxDriver.sh` as shown in the latest PR testing iteration for PR #3258 shown [here](https://testing-vm.sandia.gov/cdash/viewConfigure.php?buildid=3816148) which shows:

```
loading initial cache file /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.8.4/packageEnables.cmake
-- Setting Trilinos_ENABLE_ALL_PACKAGES = ON
-- Setting Trilinos_ENABLE_TrilinosFrameworkTests = ON
-- Setting Trilinos_ENABLE_Belos = ON
-- Setting Trilinos_ENABLE_TpetraCore = ON
```

Therefore, I think the last thing to do to manually test out the updated script `PullRequestLinuxDriver.sh`  in #3258 and merge that PR (after PR testing is complete and passes).

**Comment by william76** [comment]
@bartlettroscoe whoops!  I was on the wrong tab and thought I was closing a merged PR, not an issue.  I've reopened this one.  Thanks for alerting me of the goof ;)

**Comment by bartlettroscoe** [comment]
>  I was on the wrong tab and thought I was closing a merged PR, not an issue. I've reopened this one. Thanks for alerting me of the goof ;)

@william76, the merged PRs #3134 and #3218 don't quite complete this due to the problem described [above](https://github.com/trilinos/Trilinos/issues/3133#issuecomment-411445144) and in #3265.  To fix those issues, we need to merge PR #3258, as described in the "Next Action Status" field [above](https://github.com/trilinos/Trilinos/issues/3133#issue-341899584).

**Comment by bartlettroscoe** [comment]
With the merge of PR  #3258 8/14/2018 this should be complete.  Next: Watch PRs over next week and ensure that right set of packages are being enabled and then close on 8/21/2018 if all looks good ...

**Comment by bartlettroscoe** [comment]
FYI: There was defect in the PR driver script merged in PR #3258 yesterday which broke the PR testing process.  This was fixed in the PR #3302 which was manually merged this morning.  It looks like the PR testing system is working again as shown, for example, [here](https://testing-vm.sandia.gov/cdash/index.php?project=Trilinos&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=63&value1=PR-3301-test&field2=buildstarttime&compare2=84&value2=NOW).

We will watch the PR builds over the next week to see that everything is going correctly.

**Comment by bartlettroscoe** [comment]
FYI: A positive data-point ...

The PR #3309 that only changes files for the ATDM Trilinos builds did not result in any Trilinos packages getting enabled as shown in https://github.com/trilinos/Trilinos/pull/3309#issuecomment-413590302 and on CDash [here](https://testing-vm.sandia.gov/cdash/viewConfigure.php?buildid=3839790) which showed:

```
loading initial cache file /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.8.4/packageEnables.cmake
-- NOTE: No packages are being enabled!
```

Success!

NOTE:  the first CI iteration shown in https://github.com/trilinos/Trilinos/pull/3309#issuecomment-413581580 failed due to a git fetch failure (see  https://github.com/trilinos/Trilinos/issues/3276#issuecomment-413586355) which has nothing to do with this story #3133 or any changes to the scripts as part of this.

**Comment by bartlettroscoe** [comment]
This has been in production for some time and it seems to be working correctly in every case.  I think we might want to tweak the set of files under Trilinos/cmake/ and other subdirs that trigger a global build but that can be handled in follow-on issues and PRs.

This has saved the ATDM Trilinos effort a huge amount of time and effort (by not testing all of Trilinos for every little ATDM Trilinos script change).

I am going to close this as complete.
