### ISSUE TITLE
Ifpack2 does not build with Tpetra_INST_INT_INT=OFF

### ISSUE THREAD

**Issue by kddevin** [trilinos/Trilinos#3139]
## Current Behavior
When building Ifpack2 with Tpetra_INST_INT_INT=OFF, there are multiple failures.

In Ifpack2_UnitTestBlockTriDiContainer.cpp, Tpetra data structures are created with global ordinal explicitly set to int; this causes unresolved references at link time.  See, e.g., line 348
          run_performance_test<double, int, int>(*in);

Also, in Ifpack2_UnitTestOverlappingRowMatrix.cpp, the call to Teuchos::scan near line 317 doesn't compile due to differing types for the input and output buffers; this fix is easy:
-  int nlr = Teuchos::as<int>(numLocalRows);
+  GO nlr = Teuchos::as<GO>(numLocalRows);
   Teuchos::scan(*comm,Teuchos::REDUCE_SUM,1,&nlr,&gidOffset);

## Motivation
The Tpetra team is pursuing deprecation of global_ordinal=int.  If Ifpack2 requires global_ordinal=int, please tell the Tpetra team ASAP.  

## Definition of Done
build/test Ifpack2 with Tpetra_INST_INT_INT=OFF

## Possible Solution
I offer a solution to one problem above, but fixing the harder problems is probably best done by an Ifpack2 developer.

## Steps to Reproduce'
build/test Ifpack2 with Tpetra_INST_INT_INT=OFF

## Your Environment

Trilinos develop branch, linux workstation

## Related Issues

* Blocks #2548 
* Is blocked by 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of

**Comment by mhoemmen** [comment]
@kddevin The following PR has a fix for this issue: https://github.com/trilinos/Trilinos/pull/3193
