### ISSUE TITLE
ROL: Purge use of Tpetra::*Platform

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#3146]
Tpetra will soon deprecate and remove `DefaultPlatform`, `MpiPlatform`, and `SerialPlatform`, per #3095.  ROL uses DefaultPlatform quite a bit.  This needs to go.  See below for the replacement strategy.

@trilinos/rol @dridzal 

## Possible Solution

Tests or examples that use Tpetra and do this:
```c++
#include "Teuchos_GlobalMPISession.hpp"
#include "Tpetra_DefaultPlatform.hpp"

int main (int argc, char* argv[]) {
  Teuchos::GlobalMPISession mpiSession (&argc, &argv, NULL);
  auto comm = Tpetra::DefaultPlatform::getDefaultPlatform().getComm();
  auto node = Tpetra::DefaultPlatform::getDefaultPlatform().getNode();
  // ... rest of the code ...
}
```
should do this instead:
```c++
#include "Tpetra_Core.hpp"

int main (int argc, char* argv[]) {
  Tpetra::ScopeGuard mpiSession (&argc, &argv); // inits MPI and Kokkos
  auto comm = Tpetra::getDefaultComm();
  // ... don't make Node instances any more ...
  // ... rest of the code ...
}
```

## Related Issues
* Blocks #3095, #57

**Comment by dridzal** [comment]
Including @gregvw and @dpkouri .  This change effects a fairly large number of tests, examples, and some source code.  It won't be a difficult fix, but it is a lot of work, as it can't be done in a fully automated fashion -- can it?

@mhoemmen , thanks for the heads up.  What is the timeline?  The @trilinos/rol team will need to set aside some time to handle this deprecation.  Also, one technical question:  Where we don't use Tpetra/Kokkos, will it still be OK to use

Teuchos::GlobalMPISession mpiSession (&argc, &argv, NULL);

?

**Comment by mhoemmen** [comment]
@dridzal wrote:
> What is the timeline?

I've already opened a PR to deprecate these classes (using the `TPETRA_DEPRECATED` macro).  Node will go away FY19 Q1: https://github.com/trilinos/Trilinos/wiki/Deprecation1  

> Where we don't use Tpetra/Kokkos, will it still be OK to use
> 
> `Teuchos::GlobalMPISession mpiSession (&argc, &argv, NULL);`

You're not obligated to use `Tpetra::ScopeGuard`.  All that does is initialize MPI (if available) and Kokkos.  `Tpetra::Map` initializes Kokkos if it hasn't already been initialized, so it's OK to keep using `GlobalMPISession`, even with Tpetra.

> as it can't be done in a fully automated fashion -- can it?

  - `Tpetra_DefaultPlatform.hpp` -> `Tpetra_Core.hpp`
  - `Tpetra::DefaultPlatform::DefaultPlatformType::NodeType` -> `Tpetra::Map<>::node_type`
  - etc. (you could probably deduce the rest)

I'm pretty sure you could automate this.  If not, it's just nice relaxing tedious work.  No reason why I should have the monopoly on that ;-)

**Comment by mhoemmen** [comment]
I don't see any more `Tpetra::*Platform` classes in Trilinos' snapshot of ROL, so I'm closing this issue.  Thanks all!
