### ISSUE TITLE
Belos: Provide header file(s) with forward declarations of SolverManager and LinearProblem

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#3152]
@trilinos/belos

Feature request by @jclause : Add header file(s) to Belos with forward declarations for key Belos interface classes SolverManager and LinearProblem.

## Motivation and Context

Apps want to hide declarations and definitions of Belos classes from header files and app class declarations, in order to save build time and improve encapsulation.  If apps make their own forward declarations, it makes the app brittle to things like addition or removal of template parameters (that otherwise wouldn't break the build, because of default template parameters).

## Possible Solution

Add a header file to Belos for each key interface class -- e.g., `BelosSolverManager_fwd.hpp` -- with a forward declaration for that class. 

Alternately, add a header file to Belos with forward declarations for both SolverManager and LinearProblem, so that apps could include just the one file to get all the forward declarations they might need.

**Comment by mhoemmen** [comment]
@hkthorn , would you prefer a single header file, or one header file per class?  The idea is that an app could declare a class like this:

```c++
#include "BelosSolverManager_fwd.hpp"
#include "Tpetra_MultiVector_decl.hpp"
#include "Tpetra_Operator_decl.hpp"

class LinearSolver {
public:
  using MV = Tpetra::MultiVector<>;
  using OP = Tpetra::Operator<>;

  void setMatrix (const Teuchos::RCP<const OP>& A);
  void solve (MV& X, const MV B);
private:
  std::unique_ptr<Belos::SolverManager<double, MV, OP>> solver_;
};
```

**Comment by hkthorn** [comment]
@mhoemmen Consolidate these headers, if possible, I don't want to flood the directory with new files.

**Comment by mhoemmen** [comment]
@hkthorn Cool, will do! Thanks!

I'll add a header file, `Belos_fwd.hpp`, that only includes forward declarations of `Belos::SolverManager` and `Belos::LinearProblem`, templated, but without specializations.  That should suffice for the Sierra use case, where classes like LinearSolver want to keep around a Belos solver instance and possibly also a LinearProblem instance, but only by pointer.
