### ISSUE TITLE
Piro: Compile error with Clang 6 on Linux.

### ISSUE THREAD

**Issue by lxmota** [trilinos/Trilinos#3157]
Piro: Using Clang 6.0.0 on Linux fails to compile with the following error:

In file included from /home/amota/LCM/Trilinos/packages/piro/src/Piro_NOXSolver.
cpp:43:
/home/amota/LCM/Trilinos/packages/piro/src/Piro_NOXSolver_Def.hpp:139:44: error: use 'template' keyword to treat 'get' as a dependent template name
        int iteration = optimizationParams.get<int>("Optimizer Iteration Number");
                                           ^
                                           template 
1 error generated.

@trilinos/piro 

## Expectations

Piro should compile without error.
## Current Behavior

Piro fails to compile.
## Motivation and Context

Piro failing to compile prevents Trilinos to compile and install, leading to failure of Albany nightly tests for Clang 6.0.0 under Linux.
## Steps to Reproduce

Try to compile Trilinos using Clang 6.0.0
## Your Environment

- **Relevant repo SHA1s:**  
- **Relevant configure flags or configure script:**  
- **Operating system and version:**  
- **Compiler and TPL versions:**  

## Related Issues

* Blocks 
* Is blocked by 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of 

## Additional Information

Albany nightly tests with Clang 6.0.0 started failing on Monday July 16.
For reference on why Albany tests fail: @ikalash @jewatkins

**Comment by mperego** [comment]
@lxmota There is something weird in your error message. 
Line /home/amota/LCM/Trilinos/packages/piro/src/Piro_NOXSolver_Def.hpp:139 is
       `int iteration = optimizationParams.get<int>("Optimizer Iteration Number");`
whereas in your error message you have
       `int iteration = optimizationParams.get("Optimizer Iteration Number");`
Are you building an up-to-date version of Trilinos?

**Comment by lxmota** [comment]
Ok, I double checked the last nightly Albany build with Clang. Its from Friday July 20th at midnight. The error is:

```
In file included from /home/lcm/LCM/Trilinos/packages/piro/src/Piro_NOXSolver.cpp:43:
/home/lcm/LCM/Trilinos/packages/piro/src/Piro_NOXSolver_Def.hpp:139:44: error: use 'template' keyword to treat 'get' as a dependent template name
        int iteration = optimizationParams.get<int>("Optimizer Iteration Number");
                                           ^
                                           template
1 error generated.

```

I'm not sure how the `<int>` template parameter got omitted in the original message.

**Comment by lxmota** [comment]
Once more, I'm not sure why things get truncated. One more try:

```
In file included from /home/lcm/LCM/Trilinos/packages/piro/src/Piro_NOXSolver.cpp:43:
/home/lcm/LCM/Trilinos/packages/piro/src/Piro_NOXSolver_Def.hpp:139:44: error:
use 'template' keyword to treat 'get' as a dependent template name
        int iteration = optimizationParams.get<int>("Optimizer Iteration Number");
                                           ^
                                           template
1 error generated.

```

**Comment by mhoemmen** [comment]
Sometimes GitHub truncates `<stuff in here>` unless you protect it with backquotes.

**Comment by mperego** [comment]
Thanks @lxmota for posting the error code again and @mhoemmen for the explanation.

It seems the compiler wants you to put the template keyword at line 149:
`int iteration = optimizationParams.template get<int>("Optimizer Iteration Number");`

However Trilinos is full of these getters with no template keyword. Maybe it is the `auto` that's messing things up..

@lxmota if it is not too much trouble, can you try the solution above, or to replace the `auto` at lines 135 and 137 with `const Teuchos::ParameterList&` ?

**Comment by mperego** [comment]
Closing the issue as it issue should have been resolved.
