### ISSUE TITLE
Tpetra: Improve build time & encapsulation by stripping many includes from Teuchos_ConfigDefs.hpp

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#3159]
`Tpetra_ConfigDefs.hpp` includes a lot of header files that really only belong to implementations or tests.  If we strip those out, we can save some build time and improve encapsulation.  We do need to be careful with this and test downstream; those includes have been in there a long time, and I've seen cases where I've broken applications like Albany just by removing an include from `Teuchos_ConfigDefs.hpp`.

@trilinos/tpetra 

## Related Issues
* Related to #351

**Comment by mhoemmen** [comment]
@csiefer2 in case this didn't happen (I doubt it did or would ever happen but here it is)

**Comment by tasmith4** [comment]
@csiefer2 do you mind double-checking `core/src/Tpetra_ConfigDefs.hpp`?  I didn't see anything that obviously looked like it was only for implementation or tests, so I suspect this might actually have happened without this issue being referenced in the PR.

**Comment by csiefer2** [comment]
Yup.  There's nothing here that obviously screams "I'm for a test"

Closing.
