### ISSUE TITLE
Test TeuchosCore_testTeuchosTestForTermination_2_MPI_4 randomly failing due to jumbled output regex failures

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#3163]
CC: @trilinos/teuchos

## Next Action Status

PR #3164 merged to develop on 7/21/2018 which should fix issue.  Next: Watch for any more failing tests and close on 9/21/2018 if no more failures ...

## Description

As shown in [this query](https://testing-vm.sandia.gov/cdash/queryTests.php?project=Trilinos&date=2018-07-15&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=7&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-&field2=status&compare2=62&value2=passed&field3=status&compare3=62&value3=notrun&field4=testname&compare4=61&value4=TeuchosCore_testTeuchosTestForTermination_2_MPI_4&field5=buildstarttime&compare5=84&value5=2018-07-22T04%3A00%3A00%20UTC&field6=buildstarttime&compare6=83&value6=2018-06-01T04%3A00%3A00%20UTC&field7=site&compare7=62&value7=chama), the test `TeuchosCore_testTeuchosTestForTermination_2_MPI_4` fails randomly in the builds:

* `Trilinos-atdm-hansen-shiller-cuda-8.0-opt`
* `Trilinos-atdm-hansen-shiller-cuda-9.0-debug`

on `hansen`.

As shown [here](https://testing-vm.sandia.gov/cdash/testDetails.php?test=50523574&build=3727037), for example, the test fails due to the jumbled output:

```
p=[hansen03:38807] *** Process received signal ***
[hansen03:38807] Signal: Aborted (6)
[hansen03:38807] Signal code:  (-6)
[hansen03:38807] 2: /home/jenkins/hansen/workspace/Trilinos-atdm-hansen-shiller-cuda-8.0-opt/SRC_AND_BUILD/Trilinos/packages/teuchos/core/test/MemoryManagement/testTeuchosTestForTermination.cpp:63:

Terminate test that evaluated to true: GlobalMPISession::getRank() == terminate_on_procid

Bingo, we are terminating on procid == terminate_on_procid = 2!


terminate called without an active exception
```

which breaks the required regex:

```
TEST_0: Pass criteria = Match REGEX {p=2: .*/testTeuchosTestForTermination.cpp} [FAILED]
```

because the system-generated message `[hansen03:38807] *** Process received signal ***` is printed in the middle of that line.

## Steps to reproduce

Since this error seems to only be showing up in the CUDA builds on 'hansen', one might be able to reproduce this error on 'hansen' or 'shiller' using the instructions at:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#shillerhansen

But since this is a random build that rarely fails, it may be hard to reproduce.

**Comment by bartlettroscoe** [comment]
Looking at all three failures for this test on 'hansen' in [this query](https://testing-vm.sandia.gov/cdash/queryTests.php?project=Trilinos&date=2018-07-15&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=7&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-&field2=status&compare2=62&value2=passed&field3=status&compare3=62&value3=notrun&field4=testname&compare4=61&value4=TeuchosCore_testTeuchosTestForTermination_2_MPI_4&field5=buildstarttime&compare5=84&value5=2018-07-22T04%3A00%3A00%20UTC&field6=buildstarttime&compare6=83&value6=2018-06-01T04%3A00%3A00%20UTC&field7=site&compare7=62&value7=chama), all of the test failures seem to show:

```
p=[hansen02:48221] *** Process received signal ***
```

but also show the rest of the line is printed intact for the regex `p=2: .*/testTeuchosTestForTermination.cpp`.

**Comment by bartlettroscoe** [comment]
I created PR #3164 that should address this.

I am putting this issue in review pending the merge of #3164 and feedback from weeks and months of running this test.

**Comment by mhoemmen** [comment]
@bartlettroscoe I just approved your PR #3164 -- thanks!

**Comment by bartlettroscoe** [comment]
As shown in [this query](https://testing.sandia.gov/cdash-dev-view/queryTests.php?project=Trilinos&date=2018-10-02&filtercount=7&showfilters=1&filtercombine=and&field1=groupname&compare1=61&value1=ATDM&field2=buildname&compare2=65&value2=Trilinos-atdm-&field3=testname&compare3=61&value3=TeuchosCore_testTeuchosTestForTermination_2_MPI_4&field4=status&compare4=62&value4=passed&field5=status&compare5=62&value5=notrun&field6=details&compare6=64&value6=Timeout&field7=buildstarttime&compare7=84&value7=now), this test has not failed in any promoted ATDM Trilinos since 7/16/2018.  Therefore, I think this is good evidence that this is fixed.

Closing as complete.
