### ISSUE TITLE
Amesos2 support for Tpetra Block CRS matrices

### ISSUE THREAD

**Issue by cihanuq** [trilinos/Trilinos#317]
I'd like to flag interest for direct solver support for (experimental) block matrices in Tpetra. This would be very useful for geophysical inversion applications where iterative solvers do not work (well), and where each (FEM) mesh node has multiple degrees of freedom.
There was a comment in the mailing list which suggested that there is a way to 'unroll' the block matrix and pass the resulting regular matrix to Amesos2. I could not find a way to do so, however.

**Comment by mhoemmen** [comment]
@trilinos/tpetra We have some interest in expanding the set of solvers that natively support BlockCrsMatrix.  Would you mind sharing more details about the applications of interest to you?  If not here, please feel free to e-mail us.  Thanks!

**Comment by srajama1** [comment]
One way to this is to write a new adapter in Amesos2 for BlockCrsMatrix. As Mark said, the applications driver and which solvers are of interest will help prioritizing it.

@trilinos/amesos2

**Comment by cihanuq** [comment]
@mhoemmen Just wondering, is there currently a way to "convert" (i.e. unroll) a block matrix to a regular Tpetra CrsMatrix so that I can use Amesos2 while direct support for block matrices is not there yet?

**Comment by mhoemmen** [comment]
@cihanuq Not at the moment.  The opposite direction exists.  If you would like to contribute this feature, you could look at the implementation of the `writeMatrixStrip` function in tpetra/core/src/Tpetra_Experimental_BlockCrsMatrix_Helpers_def.hpp.

**Comment by cihanuq** [comment]
@mhoemmen The fact that Amesos2, MueLu, and the ILUT preconditioner in Ifpack2 don't support block matrices made us go a different route. We now "unroll" the graph in our code and create a regular CrsMatrix if one of those features are requested by the user. Maybe the code is useful to Trilinos people so here it comes:

    typedef Tpetra::CrsGraph<LO,GO,NT> GraphType;
    typedef GraphType::map_type        MapType;

    // graph is the regular CrsGraph
    MapType cpm = BlockVector::makePointMap(*graph->getColMap(), blockSize);
    MapType rpm = BlockVector::makePointMap(*graph->getRowMap(), blockSize);

    // unfortunately we need to copy since we need an RCP...
    RCP<MapType> colPointMap(new MapType(cpm));
    RCP<MapType> rowPointMap(new MapType(rpm));
    const LO numMatrixRows = graph->getRowMap()->getNodeNumElements();
    const LO numUnrolledRows = rpm.getNodeNumElements();
    ArrayRCP<size_t> rowPtr(numUnrolledRows + 1);
    ArrayRCP<GO> colInd(graph->getNodeNumEntries() * blockSize * blockSize);

    for (LO row = 0; row < numMatrixRows; row++) {
        size_t numColumns = graph->getNumEntriesInLocalRow(row);
        Array<LO> indices(numColumns);
        graph->getLocalRowCopy(row, indices(), numColumns);
        for (int b = 0; b < blockSize; b++) {
            for (size_t c = 0; c < numColumns; c++) {
                for (int cb = 0; cb < blockSize; cb++) {
                    colInd[rowPtr[row * blockSize + b] + c * blockSize + cb] =
                        indices[c] * blockSize + cb;
                }
            }
            rowPtr[row * blockSize + b + 1] = rowPtr[row * blockSize + b]
                    + numColumns * blockSize;
        }
    }
    GraphType* unrolledGraph = new GraphType(rowPointMap, colPointMap, rowPtr, colInd);

Then create a CrsMatrix with that graph. The only thing to watch out for then is indexing when assembling (i.e. adding to) the matrix.

**Comment by mhoemmen** [comment]
btw, Map copy does not actually deep copy any arrays.  The two Maps share any data of significant size, and those data reference-count so deallocation happens safely.

**Comment by cihanuq** [comment]
@mhoemmen Does this mean I can use rcpFromRef(cpm) etc ?
