### ISSUE TITLE
MueLu: Black Box Refactor

### ISSUE THREAD

**Issue by aerappa** [trilinos/Trilinos#3170]
@trilinos/muelu

Luc is adding a structured CRS graph that we can query for coarse element information. This will simplify the current structure of Black Box, since we are currently manually computing this information.

**Comment by jhux2** [comment]
@trilinos/muelu

**Comment by lucbv** [comment]
@jhux2, thanks for the labeling, I do not know why @aerappa is not able to do the team mention?
Anyway to give more information on what is going on here: the idea is to leverage structured aggregation to generate data for BlackBoxPFactory which will reduce code duplication and also separate the symbolic and numeric phases of the transfer operator construction.
Also @aerappa will start with a more simplified approach and build more gradually than what I attempted.

**Comment by aprokop** [comment]
> @jhux2, thanks for the labeling, I do not know why @aerappa is not able to do the team mention?

Probably because he is not a Trilinos organization member?
