### ISSUE TITLE
New PanzerMiniEM test failures in ATDM Trilinos builds starting 7/21/2018

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#3182]
CC: @trilinos/panzer, @trilinos/muelu, @cgcgcg (pushed breaking commits?), @rppawlo (Trilinos Nonlinear Solvers Product Lead)

## Next Action Status

Commit 65a9d01 from PR #3205 merged on 7/30/2015 disabled all of the `PanzerMiniEM_MiniEM-BlockPrec_XXX` tests in all of the ATDM builds (no MueLu Epetra support enabled in ATDM Trilinos builds).  Next: Find out how to get the tests `PanzerMiniEM_MiniEM-BlockPrec_XXX` re-enabled for the ATDM Trilinos builds since they are important for supporting and protecting EMPIRE ...

## Description

As shown in [this query](https://testing-vm.sandia.gov/cdash/queryTests.php?project=Trilinos&date=2018-07-24&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=8&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-&field2=status&compare2=62&value2=passed&field3=status&compare3=62&value3=notrun&field4=groupname&compare4=61&value4=ATDM&field5=testname&compare5=65&value5=Panzer&field6=site&compare6=62&value6=mutrino&field7=site&compare7=62&value7=chama&field8=buildstarttime&compare8=83&value8=2018-07-10), the tests:

* PanzerMiniEM_MiniEM-BlockPrec_Augmentation_Epetra_MPI_1
* PanzerMiniEM_MiniEM-BlockPrec_Augmentation_Epetra_MPI_4
* PanzerMiniEM_MiniEM-BlockPrec_RefMaxwell_Epetra_MPI_1
* PanzerMiniEM_MiniEM-BlockPrec_RefMaxwell_MPI_1
* PanzerMiniEM_MiniEM-BlockPrec_RefMaxwell_MPI_4

started failing consistently on in the builds:

* Trilinos-atdm-hansen-shiller-cuda-8.0-debug
* Trilinos-atdm-hansen-shiller-cuda-8.0-opt
* Trilinos-atdm-hansen-shiller-cuda-9.0-debug
* Trilinos-atdm-hansen-shiller-cuda-9.0-opt
* Trilinos-atdm-hansen-shiller-gnu-debug-serial
* Trilinos-atdm-hansen-shiller-gnu-opt-serial
* Trilinos-atdm-hansen-shiller-intel-debug-serial
* Trilinos-atdm-hansen-shiller-intel-opt-serial
* Trilinos-atdm-rhel6-gnu-debug-serial
* Trilinos-atdm-rhel6-gnu-opt-serial

starting on 7/21/2018.

NOTES on other failing tests shown in that above CDash query:

* The test failure `PanzerAdaptersSTK_model_evaluator_mass_check_MPI_1` in the build `Trilinos-atdm-rhel6-gnu-debug-serial` on 'sems-rhel6' at 2018-07-20 09:35:22 with results shown [here](https://testing-vm.sandia.gov/cdash/testDetails.php?test=50855428&build=3749115) was due to a freak build failure for the Panzer executable ` PanzerAdaptersSTK_model_evaluator_mass_check` wn [here](https://testing-vm.sandia.gov/cdash/viewBuildError.php?buildid=3749115).

* The test timeout at 10 min `PanzerAdaptersSTK_MixedPoissonExample-ConvTest-Hex-Order-3` in the build `Trilinos-atdm-hansen-shiller-gnu-debug-serial` on 'hansen' on 2018-07-13T06:11:37 UTC shownn [here](https://testing-vm.sandia.gov/cdash/testDetails.php?test=50375879&build=3718473) looks to be a freak timeout if you look at [this query](https://testing-vm.sandia.gov/cdash/queryTests.php?project=Trilinos&date=2018-07-24&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-hansen-shiller-gnu-debug-serial&field2=testname&compare2=61&value2=PanzerAdaptersSTK_MixedPoissonExample-ConvTest-Hex-Order-3&field3=buildstarttime&compare3=83&value3=2018-07-10) and not related to this.

* The sites 'chama' and 'mutrino' were filtered out since the have different issues causing failures.

If you look at the git commits pulled when these tests first started failing on 7/21/2018, for example [here](https://testing-vm.sandia.gov/cdash/viewNotes.php?buildid=3752571#!#note6), it seems likely the commits merged to 'develop' on 7/20/2018 by @cgcgcg in RR #3047 by @cgcgcg are the likely trigger of these new test failures.

## Steps to reproduce

These failures should be reproducable on any SNL COE RHEL6 machine with the SEMS env or the Test Bed machines 'hansen' or 'shiller' as described at:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md

The specific instructions for a RHEL6 mahcine are given at:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#sems-rhel6-environment

After cloning Trilinos, the following commands should reproduce the test failures with:

```
$ cd <some_build_dir>/

$ source $TRILINOS_DIR/cmake/std/atdm/load-env.sh gnu-debug-serial

$ cmake \
  -GNinja \
  -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnvSettings.cmake \
  -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_PanzerMiniEM=ON \
  $TRILINOS_DIR

$ make NP=16

$ ctest -j16
```

**Comment by cgcgcg** [comment]
@bartlettroscoe I'll have a look at this once I'm back next week. If this is a pressing issue, feel free to revert.

**Comment by bartlettroscoe** [comment]
@cgcgcg, no need to revert at this point.  Next week should be fine.

**Comment by bartlettroscoe** [comment]
It looks like the commit 65a9d01 from PR #3205 merged yesterday disabled the failing `PanzerMiniEM_MiniEM-BlockPrec_XXX` tests in all of the ATDM builds.  It seems that the problem was that MueLU support for Epetra is needed in order to run these tests.

@rppawlo, are these tests important to run for ATDM Trilinos builds to protect EMPIRE?

**Comment by rppawlo** [comment]
> are these tests important to run for ATDM Trilinos builds to protect EMPIRE?

yes. The mini-em app is the mirror implementation of EMPIRE EM solver. It is meant for Trilinos devs to use to test performance improvements. We do want this running on all atdm platforms.

**Comment by bartlettroscoe** [comment]
> The mini-em app is the mirror implementation of EMPIRE EM solver. It is meant for Trilinos devs to use to test performance improvements. We do want this running on all atdm platforms.

@rppawlo, @cgcgcg, @jhux2,

We have a problem then.  `MueLu_ENABLE_Epetra` got turned off in commit eee871d803e2d0a60c60710071f920365687fdcb in order to fix the CUDA builds as described in #2319 and these tests can only be enabled when `MueLu_ENABLE_Epetra=ON`.

What do we need to do in order to get these `PanzerMiniEM_MiniEM-BlockPrec_XXX` tests running again for the ATDM builds? Should we turn `MueLu_ENABLE_Epetra` back on again and fix the build errors described in #2319 or should we update MueLu and/or Panzer to not need `MueLu_ENABLE_Epetra=ON` in order to run these tests?

**Comment by cgcgcg** [comment]
@bartlettroscoe Do you know for what reason the Epetra support for MueLu is disabled? Because Epetra itself is available on these builds.

**Comment by bartlettroscoe** [comment]
@cgcgcg said:

> Do you know for what reason the Epetra support for MueLu is disabled? Because Epetra itself is available on these builds.

Yes.  See my comment [above](https://github.com/trilinos/Trilinos/issues/3182#issuecomment-409229269).  (Looks like we had a race to post comments.)

**Comment by cgcgcg** [comment]
Oh, I remember. Well, I only added the MiniEM Epetra tests with the PR that lead to the present issue. So it's not like we tested MiniEM with Epetra ever in the past on these platforms.

**Comment by bartlettroscoe** [comment]
@cgcgcg said:

> Oh, I remember. Well, I only added the MiniEM Epetra tests with the PR that lead to the present issue. So it's not like we tested MiniEM with Epetra ever in the past on these platforms.

That makes sense.  But if if these Panzer MiniEM tests are supposed to support EMPIRE, should they not be made to work with the ATDM Trilinos configuration that targets EMPIRE?

@rppawlo, what do you think about this?  Note that there are still a few `PanzerMiniEM` tests running and passing in the various ATDM builds as shown in [this query](https://testing-vm.sandia.gov/cdash/queryTests.php?project=Trilinos&date=2018-07-30&limit=0&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-&field2=groupname&compare2=61&value2=ATDM&field3=testname&compare3=65&value3=PanzerMiniEM).  Are those remaining tests enough to protect EMPIRE?

**Comment by rppawlo** [comment]
@egphill is the best one to answer which mini-em tests we need to make sure are still passing on KNL and CUDA. For ATDM, we really only care about Tpetra versions to support CUDA via kokkos. I suspect that the Epetra support was added to do performance comparisons with Tpetra.

**Comment by egphill** [comment]
The Tpetra tests are all we need to protect EMPIRE. So it looks like PanzerMiniEM_MiniEM-BlockPrec_Augmentation_MPI_* and PanzerMiniEM_MiniEM-BlockPrec_RefMaxwell_MPI_* are what we want. The Epetra/Tpetra performance comparisons are valuable but not necessary to test.

**Comment by bartlettroscoe** [comment]
@egphill said:

> The Epetra/Tpetra performance comparisons are valuable but not necessary to test.

Okay then, I think we can close this issue and *DONE* and not worry about these tests being disabled.
