### ISSUE TITLE
Tpetra: automation for project board

### ISSUE THREAD

**Issue by lucbv** [trilinos/Trilinos#3188]
@trilinos/tpetra 

Just posting a question more than an issue here.
Is there a reason for not enabling automation in the Tpetra and TpetraRF FY18 boards?
I think that automatically moving closed issues and merged PR to the done column would make things a little cleaner.

**Comment by mhoemmen** [comment]
@lucbv We haven't been using the FY18 boards.  How does one enable automation?

**Comment by lucbv** [comment]
@mhoemmen at the top of each column is a label for the column, to the right of it you can find a `+` and a `...`
If you click on `...` it pops a menu in which you can chose the `manage automation` item

**Comment by mhoemmen** [comment]
@lucbv I can add automation for one column -- say Backlog -- that pushes closed issues and merged PDs to Done.  However, if I try to add automation to another column to do the same thing, GitHub says that I can't have that automation for the Backlog column.

**Comment by csiefer2** [comment]
There's a board?

**Comment by jhux2** [comment]
MueLu has one as well.

**Comment by csiefer2** [comment]
You learn something every day...

**Comment by csiefer2** [comment]
Where are the links to those things, btw?

**Comment by csiefer2** [comment]
Nevermind.  I found them.  They contain no content on Windows, of course, just infinitely spinning github cat logos...

**Comment by mhoemmen** [comment]
It works; thanks @lucbv ! :D  Here's what I did:

  1. Added "Done" automation to the "Done" column
  2. Created a test issue (#3201)
  3. Added #3201 to TpetraRF project
  4. Went to TpetraRF project board and added #3201 to Backlog column
  5. Closed #3201: this successfully moved the issue to the Done column in TpetraRF

**Comment by mhoemmen** [comment]
As a final test, I added automation to the Tpetra project as well (it's distinct from the TpetraRF project), added this issue to the "In Progress" column, and closed this issue (with this comment).

**Comment by mhoemmen** [comment]
Success!  This issue got moved to the Done column automatically.  Thanks all!
