### ISSUE TITLE
Shylu Core not compiling with Cuda enabled

### ISSUE THREAD

**Issue by crtrott** [trilinos/Trilinos#320]
The following set of errors occur when compiling Shylu with Cuda enabled: 

```
[ 37%] Building CXX object packages/shylu/core/src/CMakeFiles/shylu.dir/epetra/shylu_local_schur_operator.cpp.o
/home/crtrott/Trilinos/packages/tpetra/kernels/src/Kokkos_ArithTraits.hpp(572): error: more than one instance of overloaded function "isinf" matches the argument list:
            function "isinf(float)"
            function "std::isinf(float)"
            argument types are: (const float)

/home/crtrott/Trilinos/packages/tpetra/kernels/src/Kokkos_ArithTraits.hpp(578): error: more than one instance of overloaded function "isnan" matches the argument list:
            function "isnan(float)"
            function "std::isnan(float)"
            argument types are: (const float)

/home/crtrott/Trilinos/packages/tpetra/kernels/src/Kokkos_ArithTraits.hpp(842): error: more than one instance of overloaded function "isinf" matches the argument list:
            function "isinf(double)"
            function "std::isinf(double)"
            argument types are: (const double)

/home/crtrott/Trilinos/packages/tpetra/kernels/src/Kokkos_ArithTraits.hpp(848): error: more than one instance of overloaded function "isnan" matches the argument list:
            function "isnan(double)"
            function "std::isnan(double)"
            argument types are: (const double)

/home/crtrott/Trilinos/packages/tpetra/kernels/src/Kokkos_ArithTraits.hpp(978): error: more than one instance of overloaded function "isinf" matches the argument list:
            function "isinf(long double)"
            function "std::isinf(long double)"
            argument types are: (const long double)

/home/crtrott/Trilinos/packages/tpetra/kernels/src/Kokkos_ArithTraits.hpp(984): error: more than one instance of overloaded function "isnan" matches the argument list:
            function "isnan(long double)"
            function "std::isnan(long double)"
            argument types are: (const long double)
```

Typically this type of error comes from including both <math.h> and <cmath>, with the latter being the proper C++ include, while the former actually includes the C header file. Most compilers seem to have ways around including both files, but when dealing with nvcc you have two compilers and including both of those math headers often fails. Doing a very cursory search on where those includes might come from it looks like it is from Epetra:

```
$ grep "cmath" ~/Trilinos/packages/epetra/src/*
~/Trilinos/packages/epetra/src/Epetra_ConfigDefs.h:#include <cmath>
~/Trilinos/packages/epetra/src/Epetra_ConfigDefs.h:#include <cmath>
$ grep "math.h" ~/Trilinos/packages/epetra/src/*
~/Trilinos/packages/epetra/src/Epetra_ConfigDefs.h:#include <math.h>
```

**Comment by crtrott** [comment]
Mentioning teams:
@trilinos/shylu

**Comment by mhoemmen** [comment]
Could we work around by specifying the namespace explicitly?  For __CUDA_ARCH__ we want `std::isinf` (right?), and otherwise we want `::isinf`.

**Comment by jdbooth** [comment]
Confused.  Who is trying to compile Shylu with cuda and why?  The core does  not even use Tpetra, so none of the kernel calls would even have a chance to gain anything.

**Comment by crtrott** [comment]
I am doing it. And the reason is that we need to compile everything with NVCC since customers want to do that. And there are sub packages in ShyLU which do use Kokkos.

**Comment by crtrott** [comment]
And regarding namespace: we always want std::isinf, we are in C++ after all.

**Comment by srajama1** [comment]
Josh : This is just to compile everything and test relevant portions. As it goes into Epetra we need to be careful about the fix.

**Comment by srajama1** [comment]
Mark, do we have to do this for each call of isinf and other potential problems ? Any simpler way ?

**Comment by crtrott** [comment]
That is pretty much the recommended way. Also this stuff with "using std::isinf" in Epetra doesn't help.

**Comment by mhoemmen** [comment]
> Mark, do we have to do this for each call of isinf and other potential problems ? Any simpler way ?

Not really.  It's a good idea to specify the namespace of such functions anyway.  You could also use `Kokkos::Details::ArithTraits` to get safely wrapped isinf etc.  At some point we'll promote this traits class out of the Details inner namespace.  Also, don't include C headers (math.h) into C++ code; prefer C++ headers (cmath).

**Comment by srajama1** [comment]
This is in Epetra. Depending on Kokkos is not possible.

**Comment by mhoemmen** [comment]
> This is in Epetra. Depending on Kokkos is not possible.

Including both <cmath> and <math.h> in Epetra_ConfigDefs.h seems like a bad idea... Maybe we can fix it there, then insist on std::isinf etc.?
