### ISSUE TITLE
Domi Tpetra Node config issue (was: "Trilinos installation failure on Ubuntu 14.04")

### ISSUE THREAD

**Issue by fertinaz** [trilinos/Trilinos#3202]
Tyring to install Trilinos cloned from git repo on my Ubuntu 14.04 laptop. Installation basically fails at this step:
```
Byte compiling Anasazi.py
[ 95%] Built target PyTrilinos_Anasazi
[ 95%] Swig source /home/fertinaz/Trilinos/packages/PyTrilinos/src/Pliris.i
Scanning dependencies of target PyTrilinos_Pliris
[ 95%] Building CXX object packages/PyTrilinos/src/CMakeFiles/PyTrilinos_Pliris.dir/PlirisPYTHON_wrap.cpp.o
[ 95%] Linking CXX shared module PyTrilinos/_Pliris.so
Byte compiling Pliris.py
[ 95%] Built target PyTrilinos_Pliris
[ 95%] Swig source /home/fertinaz/Trilinos/packages/PyTrilinos/src/Epetra.i
Scanning dependencies of target PyTrilinos_Epetra
[ 95%] Building CXX object packages/PyTrilinos/src/CMakeFiles/PyTrilinos_Epetra.dir/EpetraPYTHON_wrap.cpp.o
[ 95%] Linking CXX shared module PyTrilinos/_Epetra.so
Byte compiling Epetra.py
[ 95%] Built target PyTrilinos_Epetra
[ 95%] Swig source /home/fertinaz/Trilinos/packages/PyTrilinos/src/Domi.i
/home/fertinaz/Trilinos/packages/tpetra/core/src/Tpetra_ConfigDefs.hpp:187: Error: CPP #error ""No default Tpetra Node type specified.  Please set the CMake option Tpetra_DefaultNode to a valid Node type."". Use the -cpperraswarn option to continue swig processing.
make[2]: *** [packages/PyTrilinos/src/DomiPYTHON_wrap.cpp] Error 1
make[1]: *** [packages/PyTrilinos/src/CMakeFiles/PyTrilinos_Domi.dir/all] Error 2
make: *** [all] Error 2
```

This is my configuration file:
```
#! /bin/sh

#Package details
base=$HOME
pkg=Trilinos
cd $base/$pkg

#Reconfigure completely from scratch
rm -rf build CMakeCache.txt CMakeFiles/

#Do not build in source
mkdir build 
cd build

cmake .. \
  -DTrilinos_ENABLE_CXX11=ON \
  -DTrilinos_ENABLE_DEBUG=ON \
  -DBUILD_SHARED_LIBS=ON     \
  -DTPL_ENABLE_MPI=ON        \
  -DTrilinos_ENABLE_ALL_PACKAGES=ON         \
  -DCMAKE_INSTALL_PREFIX=$base/$pkg/install \
  -DTPL_ENABLE_Netcdf=OFF \
  $base/$pkg

#  -DTpetra_DefaultNode:STRING=Kokkos::Compat::KokkosSerialWrapperNode \
  
# Run installer
make install
#make -j4 install 2>&1 | tee log.make.install 
```

Some other info you might find useful:
cmake version 3.9.2
mpirun (Open MPI) 1.6.5

**Comment by mhoemmen** [comment]
@wfspotz This looks related to how Domi picks a default Tpetra Node type.  I'm curious if Tpetra developers' efforts towards #57 may be related.  Is Domi part of pull request testing?

**Comment by mhoemmen** [comment]
@fertinaz If you don't need PyTrilinos, you could try disabling that package for now.  Just set the CMake option `-D Trilinos_ENABLE_PyTrilinos=OFF`.

**Comment by wfspotz** [comment]
@mhoemmen Domi is probably affected by #57. Let's talk about it.

**Comment by fertinaz** [comment]
@mhoemmen Yes I tried to re-run the installer with ` -DTrilinos_ENABLE_PyTrilinos=OFF \ ` after I started this thread. It doesn't seem to work though. This time make install fails at:
` Scanning dependencies of target muelu-adapters`

It doesn't give an error but basically hangs (after a day of parallel compilation on 4 cores). Please see log file.
[log.make.install.tar.gz](https://github.com/trilinos/Trilinos/files/2239428/log.make.install.tar.gz)

**Comment by fertinaz** [comment]
@mhoemmen Serial build has worked. Thanks

**Comment by mhoemmen** [comment]
@fertinaz I took the liberty of renaming your issue to reflect the original cause.  I could instead just close this issue and open a new one, so you don't get notifications.  Just let me know which you prefer.

**Comment by mhoemmen** [comment]
@trilinos/tpetra We need to coordinate changes due to #57 with Domi.  It's a bit tricky since Domi might not necessarily get tested by the PR tester.

**Comment by VictorEijkhout** [comment]
No action on this? For the record: I would really like the pytrilinos interface.

**Comment by mhoemmen** [comment]
@VictorEijkhout I'll need to meet with Bill Spotz on how to fix this in Domi.  Domi is not a regularly tested package in our PR testing or nightly tests, so we don't get regular feedback if we break it.  Are you able to build PyTrilinos if you turn off Domi?

**Comment by VictorEijkhout** [comment]
Nope. No dice.

```
In file included from /tmp/trilinos-build/packages/PyTrilinos/src/IFPACKPYTHON_wrap.cpp(3681):
/admin/rpms/BUILD/trilinos-git/packages/PyTrilinos/src/PyTrilinos_IFPACK_Headers.hpp(48): catastrophic error: cannot open source file "IFPACK_ConfigDefs.h"
  #include "IFPACK_ConfigDefs.h"
                                ^

compilation aborted for /tmp/trilinos-build/packages/PyTrilinos/src/IFPACKPYTHON_wrap.cpp (code 4)
make[2]: *** [packages/PyTrilinos/src/CMakeFiles/PyTrilinos_IFPACK.dir/IFPACKPYTHON_wrap.cpp.o] Error 4
make[2]: Leaving directory `/tmp/trilinos-build'
make[1]: *** [packages/PyTrilinos/src/CMakeFiles/PyTrilinos_IFPACK.dir/all] Error 2```

And I did turn on `Ifpack`.

**Comment by VictorEijkhout** [comment]
Sorry. Attached.
[trilinos-git.txt](https://github.com/trilinos/Trilinos/files/2259652/trilinos-git.txt)
There are some environment variables and other variables HAS_PYTHON and such, which you should just replace with ON.

**Comment by mhoemmen** [comment]
@VictorEijkhout That looks like a legit PyTrilinos bug.  It's possible that the code compiles fine on Mac, where the file system is not really case sensitive.  That could be how it slipped through, since PyTrilinos is not part of Trilinos' regular nightly testing.

btw, does xSDK depend on PyTrilinos?  If so, then we really need to get PyTrilinos into pull request testing.

**Comment by wfspotz** [comment]
The CI driver for PyTrilinos issue is #2570. I imagine PR testing would be different, though.

**Comment by mhoemmen** [comment]
@wfspotz Sorry, didn't realize there was a CI PyTrilinos build -- thanks!

**Comment by mhoemmen** [comment]
Preferred way to get Tpetra's default Node type is from Map: `Tpetra::Map<>::node_type`.  However, it looks in this case like Tpetra's macros aren't getting defined right.

**Comment by wfspotz** [comment]
I believe this has been addressed.  If not, we can re-open...
