### ISSUE TITLE
Status of PyTilinos with python3

### ISSUE THREAD

**Issue by philbucher** [trilinos/Trilinos#3203]
Hi @wfspotz 
I am using Trilinos in C++ on a regular basis and was now looking into PyTrilinos for rapid prototyping.
I was searching through the documentation and other issues but I couldn't fully figure out how far pytrilinos is supported by python3.5 / python3.6
The latest activity regarding this I found happened last October, do you have an updated status?
From what I saw it is also not fully supported yet in the latest release (12.12.1) right?
Thanks a lot in advance for your help!

**Comment by mhoemmen** [comment]
@trilinos/pytrilinos

**Comment by wfspotz** [comment]
@philbucher PyTrilinos is supposed to support python 3 as of 12.12. I have not worked on issues regarding differences between 3.5 and 3.6. I need to get nightly testing for PyTrilinos working (#2570) for it to really be considered robust.

Someone did find a python script that is not upgraded to python 3 (#862), but it is not an integral part of the build process. There may be other similar stragglers.

**Comment by philbucher** [comment]
thanks @wfspotz this answers my question
