### ISSUE TITLE
Upcoming release schedule

### ISSUE THREAD

**Issue by philbucher** [trilinos/Trilinos#3204]
Hi @mhoemmen (I hope you are the correct developer to address for this)
I found your latest release to be 12.12.1 if I am not mistaken.
I would like to know abt your future plans for further releases, but the website seems to be a bit outdated.
Could you please point me to a more up-to-date version?
Thanks a lot in advance and best regards

**Comment by mhoemmen** [comment]
@philbucher wrote:
> Hi @mhoemmen (I hope you are the correct developer to address for this)

I suppose I'm one of the most active ones here ;-) but @jwillenbring or @maherou would be the right people to ask about the release schedule.

Many of our users these days do their own testing against the master branch, and periodically accept "releases" just as SHA1s of master.  As a result, Trilinos developers have less incentive now to identify release candidates.  If you're using an actively developed package and don't mind interface changes now and then, then this is what I would recommend for you.

**Comment by philbucher** [comment]
@mhoemmen thanks for the fast answer, this answered my question
