### ISSUE TITLE
Epetra: What's the point of BlockMap?

### ISSUE THREAD

**Issue by bartgol** [trilinos/Trilinos#3207]
@trilinos/Epetra

## Motivation and Context

This is more of a big picture view, but its consequences have sometimes bit me when implementing functions that take `Epetra_Map&` as input. As I see it, `Epetra_Map` is just a 'special case' of `Epetra_BlockMap`, when all blocks have size one. It is useful to enforce this constraint at compile time, rather than check inside every constructor if that's the case. On the other hand, this code does not compile:
```

void f(const Epetra_Map& m) {...}
void g(const Epetra_Vector&v) {  f(v.Map()); }
```
since the `Map()` method returns a reference to `Epetra_BlockMap`, and you would have to cast `Epetra_BlockMap` down to `Epetra_Map` before calling `f`. Yes, this is possible, since `Epetra_Map` does not store any additional attribute compared to `Epetra_BlockMap`, but it is...ugly!

However, it appears to me that _all_ Epetra classes use only `Epetra_Map&`. All the matrices only accept and return `Epetra_Map`. Even the vector and multivector, which formally take a `Epetra_BlockMap` as input at construction, allocate enough space for `Map().NumMyPoints()` doubles (per vector), which means they would be _wrong_ if the element size is larger than one.

Or perhaps I am completely misunderstanding what `Epetra_BlockMap` is intended to do.

Could someone shed some light on this? Or, if my impression is right, why shouldn't we completely remove the `Epetra_BlockMap` (perhaps with a typedef for backward compatibility)?

**Comment by bartgol** [comment]
Ok, not _everything_ uses `Epetra_Map`: `Epetra_CrsGraph` seems to correctly use the block map...though `Epetra_CrsMatrix` only works with `Epetra_Map`...

**Comment by mhoemmen** [comment]
@trilinos/epetra (not sure if the at-reference worked above)

**Comment by mhoemmen** [comment]
@maherou could explain the rationale better.  The Epetra design documents may also prove useful.

**Comment by bartgol** [comment]
I guess I should have digged further. The `Epetra_VbrMatrix` class seems to be the real customer of the block map feature.

However, this raises another question: Tpetra handles the hierarchy the other way around, meaning that block objects are a not a base case of non-block ones. Why this disparity between packages? And, is there a way to make it go away? It seems overcomplicated to force all the package to be block-map aware when only one class is really using the feature...

Note: I don't want to be critique of the design, I'm just puzzled.

**Comment by mhoemmen** [comment]
Tpetra didn't have block matrices originally.  A customer specifically requested a data structure optimized for the case of small dense matrices.  `Epetra_VbrMatrix` likely will not perform well for this case; for example, it uses the BLAS to do block operations.  BLAS routines' error checking would likely be more expensive than the computation for very small blocks.  Furthermore, the customer wanted a data structure that could only be constructed in one way, the fast way (from a fill-complete CrsGraph).

**Comment by maherou** [comment]
At the start of Epetra work, block matrices were in use in some applications and the expectation was that more applications would move to that formulation.  However, instead, apps found working with block matrices to be too complicated.  Also, algebraic multigrid preconditioners were harder to tune for block matrices so, while block matrices can have better performance and smaller graphs, without a good multigrid preconditioner, block matrix formulations could not compete with point matrices.  We figured this out by the time that Tpetra was being designed, which is why it doesn’t have the same design as Epetra.  At this point with Epetra, a person could remove the Epetra_Map inheritance from Epetra_BlockMap, but we have other priorities, and Tpetra is where the forward-looking focus is now.

**Comment by bartgol** [comment]
Ok, thanks for the explanation.
