### ISSUE TITLE
Configuring with Kokkos and advanced back-ends

### ISSUE THREAD

**Issue by VictorEijkhout** [trilinos/Trilinos#3217]
Is there a KOKKOS_ARCH value for skylake and/or knights landing?

`KOKKOS_ENABLE_MEMKIND` : if I set this and then run on skylake, do I run into problems? 

Victor.

**Comment by rppawlo** [comment]
Yes. SKX for skylake and KNL for knights landing. See table 4.3 in 

https://github.com/kokkos/kokkos/wiki/Compiling

**Comment by mhoemmen** [comment]
@VictorEijkhout wrote:
> `KOKKOS_ENABLE_MEMKIND` : if I set this and then run on skylake, do I run into problems?

It should only be a problem if you try to use `Kokkos::HBWSpace`, as far as I can tell.

**Comment by mhoemmen** [comment]
That is, Kokkos doesn't appear to do any HBWSpace-specific setup, unless you actually try to use that memory space.

**Comment by mhoemmen** [comment]
And if you do try to use it, my guess is that libmemkind would raise some sort of run-time error, or otherwise fail to allocate memory.

**Comment by mhoemmen** [comment]
@VictorEijkhout FYI, best practice for Kokkos questions is to ask them directly on the kokkos repo (github.com/kokkos/kokkos/issues/new).

**Comment by jhux2** [comment]
@trilinos/kokkos

**Comment by ibaned** [comment]
This seems well-answered to me, thanks @rppawlo and @mhoemmen !
