### ISSUE TITLE
Library dependence on ${PYTHON_EXECUTABLE}

### ISSUE THREAD

**Issue by VictorEijkhout** [trilinos/Trilinos#3219]
I'm running into a really weird issue. I build trilinos, and then wrap it into an rpm, that being the mechanism we use for safely installing stuff. Now, the packaging step does some dependency analysis, and it complains about a weird token.

If you run 
```find $INSTALLATION_DIRECTORY | /usr/lib/rpm/find-requires```
you find that there is a dependency on 
```${PYTHON_EXECUTABLE}```

Now, I have no idea precisely what that means. I've run every trilinos generated file through `ldd` and this token does not show up.

Do any of you have any idea where this dependency comes from? Can you take the above find command and run it on a trilinos installation and see if you get what I get?

V.

**Comment by VictorEijkhout** [comment]
The problem seems to be that a bunch of `.py.in` files (which are cmake inputs?) contain `#!${PYTHON_EXECUTABLE}` which rpmbuild apparently trips over.

So now I'm wondering why I'm including the `packages` dir in my final distribution.

Feel free to declare this issue closed.

**Comment by wfspotz** [comment]
The `.py.in` files are python scripts that get copied to the build directory with variable substitutions for `${PYTHON_EXECUTABLE}` and similar. I imagine most or all of them are in PyTrilinos -- test and example scripts as well as a couple build-related scripts.
