### ISSUE TITLE
Panzer const basis function

### ISSUE THREAD

**Issue by bathmatt** [trilinos/Trilinos#322]
So,
I assume that the curl in a 2D system maps to a CONST basis as defined in Panzer.  This seems to work well.  

However, when we have higher order HCurl elements, we will need "higher order" const basis function.  (Is this the L2 space?)  I don't see the basis for these in intrepid, maybe I'm just missing them. 

I'm just putting this out there for future work.  

@rppawlo @eric-c-cyr @mperego @kyungjoo-kim

**Comment by mperego** [comment]
Hi Matt,
We'll look into this when we'll work on high order elements, however the curl of an HCurl function should not be a CONST in general (although I'm not sure what that means in Panzer). It is a scalar, but not a constant.

**Comment by bathmatt** [comment]
Does intrepid support Hvol?  It shows up in the docs but I don't see them, 

Panzer has a hack where it has a constant basis.  My comment was when we go higher order curl we will need higher order basis to replace the const basis in panzer.  This should be the 2D Hvol I think.

**Comment by eric-c-cyr** [comment]
I don't think so. The idea is Hvol is really HGrad with no continuity enforced. Like const there really is no equivalent version in intrepid. There were trivial things left out of intrepid. This has caused some problems. For instance there is no quadrature on a node topology. I agree this isn't difficult, but it requires a complete change of code paths for a surface integral (e.g. Neumann condition) in 1d. This kind of lack of completeness has been challenging.

**Comment by eric-c-cyr** [comment]
@mperego The Curl in 2D of the lowest 1.5 order HCurl element I think is constant. This is based on what happens in finite difference type codes and an intuitive understanding of what curl means. Moreover in 3D the curl over a face is a constant, so I think this is correct in some sense.

**Comment by mperego** [comment]
Agreed. But I think we'll need to modify this for high order.

**Comment by bathmatt** [comment]
> Agreed. But I think we'll need to modify this for high order.

I do as well, we have it for 3D though, just not for the 2D case....

I think this works well with the addition of the complete basis set, and we will need it for the lowest order elements as well, as we will have, for a tri, 6 edge elements and 3 face elements in 2D.

**Comment by eric-c-cyr** [comment]
I wonder if it would simply be linear in 2D

**Comment by bathmatt** [comment]
It should mimic the Hdiv space, just for 1 face though IMHO

**Comment by mperego** [comment]
I think issue #1462 and the subsequent pull request  #1777 addressed this.
We have the HVOL basis in Intrepid2 that extend the CONST basis to high order.The lowest order HVOL space is the space of discontinuous piece-wise constants.
In general the divergence of an element in HDIV(n) will be in HVOL(n-1), where n is the order.
In 2d we also have that the curl of an element in HCURL(n) is in HVOL(n-1).

I'm not sure how Panzer is using the HVOL basis.
Anyway, I'm going to close this issue for now. Feel free to re-open it.
