### ISSUE TITLE
Sacado: Add tests for dimension_scalar() for DynRankView specialization

### ISSUE THREAD

**Issue by rppawlo** [trilinos/Trilinos#323]
commit 

c4235bda225f895275838e9a1ea010ab8dab24eb

adds a missing specialization of the dimension_scalar function for DynRankViews. This is currently tested in Phalanx but not in sacado directly.

**Comment by rppawlo** [comment]
cc'ing @trilinos/sacado

**Comment by etphipp** [comment]
Looks like this was resolved in the above commit.
