### ISSUE TITLE
Strange  KokkosCore_UnitTest_Serial_MPI_1 test failure in build Trilinos-atdm-hansen-shiller-intel-debug-serial  on 'hansen'

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#3233]
@trilinos/kokkos, @kddevin (Trilinos Data Services Product Lead)

## Next Action Status
 
Test was disabled in PR #3455 merged in 9/17/2018 which pulled in the commit
b8e53a5 and the test was missing in this build `Trilinos-atdm-hansen-shiller-intel-debug-serial` on 9/18/2018.  Next: Revert the commit b8e53a5 on the next Kokkos snapshot ...

Fix merged to kokkos 'develop' branch in kokkos/kokkos#1729 on 8/8/2018.  Next: Disable this test in the `Trilinos-atdm-hansen-shiller-intel-debug-serial` build while waiting for next Kokkos snapshot to Trilinos ...

## Description

The test `KokkosCore_UnitTest_Serial_MPI_1` failed in the ATDM Trilinos build `Trilinos-atdm-hansen-shiller-intel-debug-serial` on 8/3/2018 as shown [here](https://testing-vm.sandia.gov/cdash/testDetails.php?test=51601654&build=3793146) showing the strange error:

```
[ RUN      ] serial.cxx11
CXX11 ( test = 'ReduceTest TeamPolicy' FAILED : 2082.71 != 2082.71
/home/jenkins/hansen/workspace/Trilinos-atdm-hansen-shiller-intel-debug-serial/SRC_AND_BUILD/Trilinos/packages/kokkos/core/unit_test/TestCXX11.hpp:354: Failure
Value of: ( TestCXX11::Test< TEST_EXECSPACE >( 4 ) )
  Actual: false
Expected: true
[  FAILED  ] serial.cxx11 (1 ms)
```

Looking at [this query](https://testing-vm.sandia.gov/cdash/queryTests.php?project=Trilinos&date=2018-08-03&filtercombine=and&filtercombine=and&filtercount=4&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-&field2=testname&compare2=61&value2=KokkosCore_UnitTest_Serial_MPI_1&field3=groupname&compare3=61&value3=ATDM&field4=buildstarttime&compare4=83&value4=2018-07-01), this is the only time this test has failed in any of the promoted ATDM builds of Trilinos since 7/1/2018.  Therefore, this is either a new test failure or it is a randomly failing test.

## Steps to Reproduce

Enable the `Kokkos` package with the build `intel-debug-serial` on 'hansen' or 'shiller' as described at:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#shillerhansen

**Comment by kddevin** [comment]
@ibaned @ndellingwood @crtrott

**Comment by bartlettroscoe** [comment]
FYI:

As I feared when I created this issue, this does not look to be a fluke as it has failed in every `Trilinos-atdm-hansen-shiller-intel-debug-serial` build since 8/3/2018 as shown in [this updated query](https://testing-vm.sandia.gov/cdash/queryTests.php?project=Trilinos&date=2018-08-03&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=4&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-hansen-shiller-intel-debug-serial&field2=testname&compare2=61&value2=KokkosCore_UnitTest_Serial_MPI_1&field3=groupname&compare3=61&value3=ATDM&field4=buildstarttime&compare4=83&value4=2018-07-01).  But it is not shown failing in any other build.

Looking at the new commits pulled in the build when this test first started failing on 8/3/2018 [here](https://testing-vm.sandia.gov/cdash/viewNotes.php?buildid=3793140#!#note6) from commit 364eae1  to 93955af, I don't see any changes to Kokkos at all.  There were changes to the ATDM Trilinos configuration scripts.  It seems that a change that was made was an explicit setting of `KOKKOS_ARCH=HSW` for Intel builds as shown on 8/3/2018 [here](https://testing-vm.sandia.gov/cdash/viewConfigure.php?buildid=3793146) which showed:

```
-- KOKKOS_ARCH='HSW'
-- NOT using the legacy tribits build because KOKKOS_ARCH *is* set
-- 
-- ****************** Kokkos Settings ******************
-- Execution Spaces
--   Device Parallel: None
--     Host Parallel: None
--       Host Serial: Serial
-- 
-- Architectures:
--     HSW
-- 
-- Enabled options
--   KOKKOS_ENABLE_SERIAL
--   KOKKOS_ENABLE_DEBUG
--   KOKKOS_ENABLE_DEPRECATED_CODE
-- 
-- Final kokkos settings variable:
--   env;KOKKOS_CMAKE=yes;KOKKOS_SRC_PATH=/home/jenkins/hansen/workspace/Trilinos-atdm-hansen-shiller-intel-debug-serial/SRC_AND_BUILD/Trilinos/packages/kokkos;KOKKOS_PATH=/home/jenkins/hansen/workspace/Trilinos-atdm-hansen-shiller-intel-debug-serial/SRC_AND_BUILD/Trilinos/packages/kokkos;KOKKOS_INSTALL_PATH=/usr/local;KOKKOS_ARCH=HSW;KOKKOS_DEVICES=Serial;KOKKOS_DEBUG=yes;KOKKOS_OPTIONS=disable_profiling,disable_dualview_modify_check
-- *****************************************************
```

but **not** on 8/2/2018 [here](https://testing-vm.sandia.gov/cdash/viewConfigure.php?buildid=3790399) which showed:

```
-- KOKKOS_ARCH=''
-- NOT using the legacy tribits build because KOKKOS_ARCH *is* set
-- 
-- ****************** Kokkos Settings ******************
-- Execution Spaces
--   Device Parallel: None
--     Host Parallel: None
--       Host Serial: Serial
-- 
-- Architectures:
--     
-- 
-- Enabled options
--   KOKKOS_ENABLE_SERIAL
--   KOKKOS_ENABLE_DEBUG
--   KOKKOS_ENABLE_DEPRECATED_CODE
-- 
-- Final kokkos settings variable:
--   env;KOKKOS_CMAKE=yes;KOKKOS_SRC_PATH=/home/jenkins/hansen/workspace/Trilinos-atdm-hansen-shiller-intel-debug-serial/SRC_AND_BUILD/Trilinos/packages/kokkos;KOKKOS_PATH=/home/jenkins/hansen/workspace/Trilinos-atdm-hansen-shiller-intel-debug-serial/SRC_AND_BUILD/Trilinos/packages/kokkos;KOKKOS_INSTALL_PATH=/usr/local;KOKKOS_DEVICES=Serial;KOKKOS_DEBUG=yes;KOKKOS_OPTIONS=disable_profiling,disable_dualview_modify_check
-- *****************************************************
```

So that is the change.  Before, for the Intel builds on hansen/shiller, no `KOKKOS_ARCH` was set and this test passed.  But setting `KOKKOS_ARCH=HSW` with this Intel build causes this test to fail.

Interestingly, I think this change to explicitly set `KOKKOS_ARCH=HSW` for the Intel builds also triggered to failure of the `Piro_MatrixFreeDecorator_UnitTests_MPI_4` tests in those Intel builds as well shown [here](https://testing-vm.sandia.gov/cdash/queryTests.php?project=Trilinos&date=2018-08-03&filtercombine=and&filtercount=4&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-&field2=status&compare2=62&value2=passed&field3=status&compare3=62&value3=notrun&field4=groupname&compare4=61&value4=ATDM).  (See #2474)

@trilinos/kokkos,

So the question is, should something change in Kokkos so that setting `KOKKOS_ARCH=HSW` avoids these failures with this Intel compiler, or should one just not set `KOKKOS_ARCH` with these Intel builds?

**Comment by mhoemmen** [comment]
If the architecture is actually Haswell, then we should set `KOKKOS_ARCH` with these Intel builds.

**Comment by ibaned** [comment]
So, what `KOKKOS_ARCH=HSW` actually does in practice is to turn on flags for vector instructions, in other words it requests vectorization. Vectorization will slightly change floating point results... I suspect whatever comparison is being done here is not tolerant enough to accept this change.

**Comment by bartlettroscoe** [comment]
Can we also improve the outputting for this test?  The output `2082.71 != 2082.71` is not very informative.  Can we have this print:

```
    rel_errr(<name1>, <name2>) = rel_err(<val1>, <val2>) = <rel_err> > <error_tol>
```

?

That would make it clear what the computed relative error was and how far off this was from the error tolerance.

**Comment by ibaned** [comment]
Interestingly to Kokkos developers, the comparison being made here is between identical `parallel_reduce` calls, with the only difference being one uses a functor and the other uses a lambda. This means that that difference affected how the code vectorized. I'm not sure yet which vectorized better.

**Comment by bartlettroscoe** [comment]
@trilinos/kokkos,

Any idea when the next Kokkos snaphsot to Trilinos will occur so that we can get the fix from kokkos/kokkos#1729?

**Comment by bartlettroscoe** [comment]
As this test is only failing in this one `Trilinos-atdm-hansen-shiller-intel-debug-serial` build out of 37 builds as shown [here](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&date=2018-09-11&filtercombine=and&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-&field2=testname&compare2=61&value2=KokkosCore_UnitTest_Serial_MPI_1), it makes sense to just disable the test for now.  (We likely should have disabled this right away once we knew this was a test defect and not a code defect.)

**Comment by bartlettroscoe** [comment]
> @bartlettroscoe its currently planned for next week...

@ibaned, we have not pulled the trigger on this disable yet.  Is this kokkos update to Trilinos about to happen?

**Comment by ibaned** [comment]
No, its once again pushed to next week, and has been continuously slipping for a month now. I would go ahead with the disable.

**Comment by bartlettroscoe** [comment]
FYI: This test was disabled in PR #3455 merged in yesterday (9/17/2018) which pulled in the commit 
b8e53a5.  You can see this test went missing today in this build as shown [here](https://testing.sandia.gov/cdash-dev-view/viewTest.php?buildid=3947074) which shows the test `KokkosCore_UnitTest_Serial_MPI_1` with status `Missing`.

I will now add the label "Disabled Tests".

@ibaned, the next time that kokkos gets synced into Trilinos, can you please revert this commit in the `kokkos_promotion` branch before it gets merged to 'develop'?

**Comment by ibaned** [comment]
Yep, I'll try to remember :)

**Comment by PhilMiller** [comment]
I'm running across this while looking for info on another bug, but figured it's worth a ping - should that test be re-enabled now? It's been . . . more than a week, so presumably that Kokkos snapshot has made its way through.

**Comment by crtrott** [comment]
Closing this: the machine doesn't even exist anymore.
