### ISSUE TITLE
Belos: BLAS error in GMRES - matrix with no entries on a rank

### ISSUE THREAD

**Issue by chochmuth** [trilinos/Trilinos#3235]
Hello,
I'm encountering a problem using Belos GMRES (Flexible GMRES too) with a matrix, that has an empty row, or several.  
cblas_dgemm BLAS routine throws the following error:
`lda must be >= MAX(K,1): lda=0 K=0ldb must be >= MAX(K,1): ldb=0 K=0BLAS error: Parameter number 9 passed to cblas_dgemm had an invalid value`
With parameter number 9(lda) standing for the number of rows. 
Is this a desired/necessary behaviour?

You can find an example for a matrix with entries on the first mpi-rank only below.
It runs fine if executed on one mpi-rank but with more than one mpi-rank i get the above error.

```
#include <mpi.h>

#include <Teuchos_XMLParameterListCoreHelpers.hpp>

#include <Xpetra_Operator.hpp>
#include <Xpetra_Matrix_fwd.hpp>
#include <Xpetra_MatrixMatrix.hpp>
#include "Xpetra_MapFactory.hpp"
#include "Xpetra_MultiVectorFactory.hpp"
#include "Xpetra_MatrixFactory.hpp"

#include <BelosOperatorT.hpp>
#include <BelosXpetraAdapter.hpp>
#include <BelosSolverFactory.hpp>

#include <Xpetra_Export.hpp>

typedef unsigned UN;
typedef double SC;
typedef int LO;
typedef int GO;
typedef KokkosClassic::DefaultNode::DefaultNodeType EpetraNode;
typedef EpetraNode NO;

using namespace std;
using namespace Teuchos;
using namespace Xpetra;
using namespace Belos;

int main(int argc, char *argv[]) {

    MPI_Init(&argc,&argv);
    
    {
        RCP<const Teuchos::Comm<int> > TeuchosComm = rcp(new MpiComm<int> (MPI_COMM_WORLD));

        RCP<Map<LO,GO,NO> > UniqueMap;
        RCP<Matrix<SC,LO,GO,NO> > K;
        
        int NumMyElements = 0;
        if (TeuchosComm->getRank()==0) {
            NumMyElements = 10;
        }
        Array<GO> uniqueMapArray(NumMyElements);
        for (LO i=0; i<uniqueMapArray.size(); i++) {
            uniqueMapArray[i] = i;
        }
        
        UniqueMap = MapFactory<LO,GO,NO>::Build(UseTpetra,-1,uniqueMapArray(),0,TeuchosComm);
        K = MatrixFactory<SC,LO,GO,NO>::Build(UniqueMap,1);
        for (LO i=0; i<UniqueMap->getNodeNumElements(); i++) {
            LO numEntries = 10-i;
            Array<GO> indicesArray(numEntries);
            Array<SC> valuesArray(numEntries);
            for (LO k=0; k<numEntries; k++) {
                indicesArray[k] = k+i;
                valuesArray[k] = 1;
            }
            K->insertGlobalValues(UniqueMap->getGlobalElement(i),indicesArray(),valuesArray());
            
        }
        K->fillComplete();
        
        
        //Solve with GMRES
        
        RCP<MultiVector<SC,LO,GO,NO> > xSolution = MultiVectorFactory<SC,LO,GO,NO>::Build(UniqueMap,1);
        RCP<MultiVector<SC,LO,GO,NO> > xRightHandSide = MultiVectorFactory<SC,LO,GO,NO>::Build(UniqueMap,1);
        
        xSolution->putScalar(0.0);
        xRightHandSide->putScalar(1.0);
        
        RCP<OperatorT<MultiVector<SC,LO,GO,NO> > > OpK = rcp(new XpetraOp<SC, LO, GO, NO>(K));
        
        RCP<LinearProblem<SC,MultiVector<SC,LO,GO,NO>,OperatorT<MultiVector<SC,LO,GO,NO> > > > belosLinearProblem(new LinearProblem<SC,MultiVector<SC,LO,GO,NO>,OperatorT<MultiVector<SC,LO,GO,NO> > >(OpK,xSolution,xRightHandSide));
        SolverFactory<SC,MultiVector<SC,LO,GO,NO>,OperatorT<MultiVector<SC,LO,GO,NO> > > belosFactory;
        RCP<ParameterList> solverParameterList = rcp(new ParameterList());
        
        solverParameterList->set("Convergence Tolerance",1.e-12);
        solverParameterList->set("Verbosity",47);
        solverParameterList->set("Output Frequency",1);
        solverParameterList->set("Output Style",1);

        RCP<SolverManager<SC,MultiVector<SC,LO,GO,NO>,OperatorT<MultiVector<SC,LO,GO,NO> > > > belosSoverManager = belosFactory.create("GMRES",solverParameterList);
        belosSoverManager->setProblem(belosLinearProblem);
        
        belosLinearProblem->setProblem(xSolution,xRightHandSide);
        belosSoverManager->solve();
        
    }
    
    MPI_Finalize();
    
    return(EXIT_SUCCESS);
}

```
@trilinos/belos Belos

**Comment by mhoemmen** [comment]
@chochmuth wrote:
> I'm encountering a problem using Belos GMRES (Flexible GMRES too) with a matrix, that has an empty row, or several.

How would you like Belos' GMRES implementation to behave in this case?  I'm guessing that you want Belos to detect this case, and report an error; is that right?

**Comment by chochmuth** [comment]
Sorry for not being clearer right away. The problem I obsereve is with a matrix that has no rows on a processor and therefore no entries. In the above example I use a matrix with the map having the following entries.
proc 0: [0,1,2,...]
proc 1: [] always empty
proc 2: [] 
.....
If I run this problem on more than 1 processor I get the BLAS error above. Would it be possible that the solver detects these nonexisting rows, because atm it still performs calculations with it.

**Comment by cgcgcg** [comment]
@chochmuth After talking to @searhein, I believe that for your use case, you want Krylov methods to be oblivious to the fact that there are empty ranks. So when this case is detected, you don't want an exception to be thrown, but maybe a warning. You want GMRES to be able to run through this case without bugging out. Is that the desired behavior?

**Comment by chochmuth** [comment]
@cgcgcg  Yes, this is the desired behaviour. Is that possible?

**Comment by cgcgcg** [comment]
I don't see why it wouldn't, it's probably a matter of simply making sure that there are entries on the rank before calling BLAS. I'd think that you'd need to be careful with the inner products and norms. Or are there other hurdles. @mhoemmen?

**Comment by mhoemmen** [comment]
I'm confused -- "empty ranks" (i.e., "some MPI processes, but not all, have zero rows in the matrix") does not mean the same thing as "some rows of the matrix are actually zero."

For the "empty ranks, but all actual rows of the matrix are nonzero" case, Tpetra should work fine.  The Epetra work-around is to create an MPI subcommunicator using `MPI_Comm_split` that only includes MPI processes with a nonzero number of rows.

**Comment by chochmuth** [comment]
@mhoemmen 
Sorry for the confusion! I encounter the issue with empty ranks. 
To make my problem clearer, think of a problem matrix on rank 0 and a preconditioner on rank 1.
`MPI_Comm_split` is probably not an option, as I need the solver to run on all ranks and I guess that this is not the case when starting with a matrix on a splitted communicator.
I have rerun my above test and it turns out that using Epetra as the underlying lib in Xpetra works fine. I only encounter the BLAS error using Tpetra.

**Comment by mhoemmen** [comment]
> To make my problem clearer, think of a problem matrix on rank 0 and a preconditioner on rank 1.

  1. Why would you want to do this?
  2. It's not clear that MueLu will work if the row Map, range Map, and row Map are not all the same.  That's a general MueLu issue, not an Epetra or Tpetra issue.
  3. Can you come up with a reproducer that does not use Xpetra, and that only uses Tpetra?  I would like to know if this is an issue with Xpetra's wrappers for Tpetra, or just a Tpetra issue.

**Comment by cgcgcg** [comment]
@mhoemmen I think @chochmuth wants this for a domain decomposition method (using Frosch) with an additive coarse grid. The problem is that the coarse solver somehow needs to know when to stop iterating. The cleaner solution would be to use subcommunicators, implement communication between fine and coarse problem, and set up the Krylov method only on the fine grid communicator.

Instead, @chochmuth is trying to set up a matrix over COMM_WORLD that does not have any entries on the ranks that are responsible for the coarse problem. While this is not as efficient, it might be easier to try this approach before going for efficiency. Does this explanation make sense?

@chochmuth Is this a reasonable description?

**Comment by mhoemmen** [comment]
@cgcgcg That somewhat makes sense.  The coarse-grid solve really should use a smaller communicator in order to improve performance and reduce synchronization.  The suboptimal use case should still work, though.

Can either of you come up with a reproducer that only uses Tpetra?

**Comment by searhein** [comment]
@mhoemmen You are right that this will a create an overhead of communication. Actually, the coarse solver is already on a smaller communicator. However, this communicator is just a part of the communicator used for the first level. I believe that the overhead should be negligible at the moment. If this becomes significant, we are definitely going to change this. 

As @cgcgcg wrote, we would prefer a solution which does not overcomplicate the implementation for the moment. Hence, leaving ranks empty on the global communicator would be our preferred strategy for now. It would be great to get this running. 

@chochmuth will post a reproducer using Tpetra later today.

**Comment by chochmuth** [comment]
@mhoemmen Here is  a reproducer that only uses Tperta.
The same BLAS error as above is thrown.

```
#include <mpi.h>

#include "BelosConfigDefs.hpp"
#include "BelosLinearProblem.hpp"
#include "BelosTpetraAdapter.hpp"
#include "BelosBlockGmresSolMgr.hpp"

#include <Tpetra_Core.hpp>
#include <Tpetra_MultiVector.hpp>
#include <Tpetra_Operator.hpp>
#include <Tpetra_CrsMatrix.hpp>

typedef unsigned UN;
typedef double SC;
typedef int LO;
typedef int GO;
typedef KokkosClassic::DefaultNode::DefaultNodeType NO;

using namespace std;
using namespace Teuchos;
using namespace Tpetra;
using namespace Belos;

int main(int argc, char *argv[]) {
    typedef Tpetra::Operator<SC>             OP;
    typedef Tpetra::MultiVector<SC>          MV;

    MPI_Init(&argc,&argv);
    
    {
        RCP<const Teuchos::Comm<int> > TeuchosComm = rcp(new MpiComm<int> (MPI_COMM_WORLD));
    
        int NumMyElements = 0;
        if (TeuchosComm->getRank()==0) {
            NumMyElements = 10;
        }
        Array<GO> uniqueMapArray(NumMyElements);
        for (LO i=0; i<uniqueMapArray.size(); i++) {
            uniqueMapArray[i] = i;
        }

        RCP<Map<LO, GO, NO> > UniqueMap = rcp(new Map<LO, GO, NO>(-1,uniqueMapArray,0,TeuchosComm));

        
        RCP<CrsMatrix<SC, LO, GO, NO> > K = rcp (new CrsMatrix<SC, LO, GO, NO> (UniqueMap,1));

        for (LO i=0; i<UniqueMap->getNodeNumElements(); i++) {
            LO numEntries = 10-i;
            Array<GO> indicesArray(numEntries);
            Array<SC> valuesArray(numEntries);
            for (LO k=0; k<numEntries; k++) {
                indicesArray[k] = k+i;
                valuesArray[k] = 1;
            }
            K->insertGlobalValues(UniqueMap->getGlobalElement(i),indicesArray(),valuesArray());
            
        }
        K->fillComplete();

        //Solve with GMRES
        RCP<MV> Solution = rcp(new MV(UniqueMap,1));
        RCP<MV> RightHandSide = rcp(new MV(UniqueMap,1));
        
        Solution->putScalar(0.0);
        RightHandSide->putScalar(1.0);
        
        RCP<LinearProblem<SC,MV,OP > > belosLinearProblem(new LinearProblem<SC,MV,OP > (K,Solution,RightHandSide));
        belosLinearProblem->setProblem();
        
        RCP<ParameterList> solverParameterList = rcp(new ParameterList());
        solverParameterList->set("Convergence Tolerance",1.e-12);
        solverParameterList->set("Verbosity",47);
        solverParameterList->set("Output Frequency",1);
        solverParameterList->set("Output Style",1);
        
        BlockGmresSolMgr<SC,MV,OP> solver( belosLinearProblem, solverParameterList );
        solver.solve();
    }
    
    MPI_Finalize();
    
    return(EXIT_SUCCESS);
}
```

**Comment by mhoemmen** [comment]
@chochmuth I made a few minor changes to your example (e.g., see #2548 and #57).  On my workstation, the test passes, but prints out the following XERBLA error several times:
```
On entry to DGEMM NTCDGEMV DGER  , parameter number  8 had an illegal value
```
This should be straightforward enough to fix.

**Comment by mhoemmen** [comment]
@chochmuth @searhein @cgcgcg Please feel free to review the following PR that fixes this issue: https://github.com/trilinos/Trilinos/pull/3249

**Comment by mhoemmen** [comment]
Thanks all!

**Comment by chochmuth** [comment]
@mhoemmen thanks for the quick fix.

**Comment by mhoemmen** [comment]
@chochmuth Thanks for reporting and for writing a reproducer! :D
