### ISSUE TITLE
PyTrilinos: Incorrect capitalization in header file

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#3245]
@trilinos/pytrilinos @wfspotz 

@VictorEijkhout reports the following PyTrilinos build error:
```
In file included from /tmp/trilinos-build/packages/PyTrilinos/src/IFPACKPYTHON_wrap.cpp(3681):
/admin/rpms/BUILD/trilinos-git/packages/PyTrilinos/src/PyTrilinos_IFPACK_Headers.hpp(48): catastrophic error: cannot open source file "IFPACK_ConfigDefs.h"
  #include "IFPACK_ConfigDefs.h"
                                ^
```
It looks like this PyTrilinos header file just needs to change the capitalization of the above include: `#include "Ifpack_ConfigDefs.h"`

## Motivation and Context

xSDK

## Related Issues
* Related to #3202

**Comment by VictorEijkhout** [comment]
On Aug 6, 2018, at 4:47 PM, Mark Hoemmen <notifications@github.com<mailto:notifications@github.com>> wrote:

just needs to change

I’ll wait until I hear that the repository has been updated.

Victor.

**Comment by wfspotz** [comment]
This and several other PyTrilinos fixes have been pushed to the `develop` branch.
