### ISSUE TITLE
Zoltan2: Zoltan2_OrderingScotch test enabled even if Scotch TPL not enabled

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#325]
@trilinos/zoltan2 
Scotch is an optional TPL dependency of Zoltan2.  Nevertheless, the Zoltan2_OrderingScotch test builds and runs unconditionally, and fails if the Scotch TPL is not enabled.  See lines 72-80 of zoltan2/test/order/CMakeLists.txt).  To fix, wrap those lines in `IF(Zoltan2_ENABLE_Scotch) ... ENDIF()`.

**Comment by egboman** [comment]
Thanks for the bug issue and proposed fix. Fixed in commit cdc4ce21bb7.

**Comment by mhoemmen** [comment]
YAY :D
