### ISSUE TITLE
STK Mesh: Linker error combining Trilinos in RELEASE mode with user code in DEBUG builds

### ISSUE THREAD

**Issue by sayerhs** [trilinos/Trilinos#3250]
*STK Mesh*: I am seeing linker errors when I attempt to link Trilinos built with `-DCMAKE_BUILD_TYPE=RELEASE` with user code that I am attempting to compile with `-DCMAKE_BUILD_TYPE=DEBUG`

```
Undefined symbols for architecture x86_64:
  "stk::mesh::Bucket::check_for_invalid_connectivity_request(stk::mesh::ConnectivityType const*) const", referenced from:
      stk::mesh::Bucket::begin_nodes(unsigned long) const in BdyIOPlanes.cpp.o
      stk::mesh::Bucket::begin_nodes(unsigned long) const in NestedRefinement.cpp.o
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
```

## Expectations

User should be able to link a RELEASE build of Trilinos with user code that is being compiled in DEBUG mode. 

## Current Behavior

STK mesh library built in release mode provides no implementation of the method `Bucket::check_for_invalid_connectivity_request` and causes errors during linking with missing symbols.

**Comment by alanw0** [comment]
Yes this should be fixed. I'll look into this.

**Comment by jhux2** [comment]
@khpierson

**Comment by alanw0** [comment]
I've pushed a fix for this to the stk repository, and there is work in progress to update stk into Trilinos. Hopefully this will be resolved soon. @prwolfe

**Comment by alanw0** [comment]
@sayerhs hopefully this is resolved now that a stk update has been put into trilinos.
