### ISSUE TITLE
Domi: Remove "Node" Template Parameter

### ISSUE THREAD

**Issue by wfspotz** [trilinos/Trilinos#3259]
@trilinos/domi 

## Expectations
Per #57, Tpetra is getting rid of the `Node` template parameter. Domi can optionally interface with Tpetra, and the `Node` template parameter was brought along to facilitate that interface, but nothing is done with it in Domi. As Tpetra is getting rid of it, Domi can get rid of it as well. As #57 progresses, we have seen some build errors associated with the `Node` template parameter in PyTrilinos, so this should be done to address that as well.

## Current Behavior
As seen in #3202, the current configuration logic for Domi is causing a build error when PyTrilinos is enabled.

## Definition of Done
- [x] Search through the Domi code base and remove the `Node` template parameter and any logic associated with the `Node` template parameter
- [x] Test that Domi builds properly from scratch
- [x] Test that all Domi tests pass
- [x] Test that PyTrilinos builds with Domi enabled properly from scratch
- [ ] Test that all PyTrilinos tests pass

## Related Issues

* Blocks #3202 
* Is a part of #57

**Comment by wfspotz** [comment]
@mhoemmen When I attempt to compile PyTrilinos, I get this error message:

    [ 91%] Swig source /Users/wfspotz/Development/Trilinos/packages/PyTrilinos/src/Domi.i
    /Users/wfspotz/Development/Trilinos/packages/tpetra/core/src/Tpetra_ConfigDefs.hpp:187: Error: CPP #error ""No default Tpetra Node type specified.  Please set the CMake option Tpetra_DefaultNode to a valid Node type."".

The problem is that I need to use the SWIG directive `%include` on a Tpetra configuration file that defines one of the `HAVE_TPETRA_DEFAULTNODE_*` macros. Which file should I do that to?

**Comment by mhoemmen** [comment]
`KokkosClassic_DefaultNode_config.h` -- it's a header file that CMake generates.  It lives in the build directory, in `packages/tpetra/classic/NodeAPI`.

**Comment by wfspotz** [comment]
Fixed with commit a4ee74f2
