### ISSUE TITLE
Ioss build error on Mac clang due to missing <numeric> include

### ISSUE THREAD

**Issue by spdomin** [trilinos/Trilinos#328]
Ioss_Decomposition.C needs a #include <numeric>

/Users/spdomin/gitHubWork/packages/Trilinos/packages/seacas/libraries/ioss/src/Ioss_Decomposition.C:560:12: error: no member named 'iota' in namespace 'std'
      std::iota(nodeGTL.begin(), nodeGTL.end(), nodeOffset + 1);
      ~~~~~^
/Users/spdomin/gitHubWork/packages/Trilinos/packages/seacas/libraries/ioss/src/Ioss_Decomposition.C:967:28: error: no member named 'accumulate' in namespace 'std'
    size_t exp_size = std::accumulate(export_conn_size.begin(), export_conn_size.end(), 0);

**Comment by gsjaardema** [comment]
Thanks.  I will add
.. Greg

**Comment by spdomin** [comment]
Yes, this must have been resolved long, long ago....
