### ISSUE TITLE
Zoltan2 test zoltanCompare may fail with Tpetra_INST_INT_INT=OFF

### ISSUE THREAD

**Issue by kddevin** [trilinos/Trilinos#3286]
@trilinos/zoltan2 

## Current Behavior

Zoltan2 test zoltanCompare may fail with Tpetra_INST_INT__INT=OFF due to differences in the way 64-bit are represented in the test’s interface to Zoltan and Zoltan2’s interface to Zoltan. Failing component tests are PHG.  The different representations of 64-bit ids lead to different hash values and different visit orders and, thus, different partitions in the test.  We will need to fix the test to use the same representation as the Zoltan2 interface.

## Steps to Reproduce

I saw this failure on mac with Tpetra_INST_INT__INT=OFF

## Your Environment

- **Relevant repo SHA1s:**  
- **Relevant configure flags or configure script:**  
- **Operating system and version:**  
- **Compiler and TPL versions:**  

## Related Issues
* Related to #3194

**Comment by mhoemmen** [comment]
@kddevin Thanks for pointing this out!  I didn't see this issue in the pull request tests -- does this require a special TPL, or is it Mac-specific?

**Comment by kddevin** [comment]
No special TPLs needed. I saw diffs on my mac; I did not try linux.
PR tests don't use Tpetra_INST_INT_INT=OFF, right?  So they would be OK.

**Comment by mhoemmen** [comment]
@kddevin I'm just not sure what settings I would need in order to run this test.

**Comment by kddevin** [comment]
@mhoemmen You don't need to worry about it.  As long as Zoltan2 isn't getting in your way with your other projects, fixing this issue is not a high priority.  I'll get to it in due time.
Thanks.

**Comment by mhoemmen** [comment]
Thanks @kddevin !

**Comment by mhoemmen** [comment]
Is this fixed?
