### ISSUE TITLE
Failing TeuchosCore tests in ATDM cuda 9.2 builds

### ISSUE THREAD

**Issue by fryeguy52** [trilinos/Trilinos#3287]
CC: @trilinos/teuchos , @jwillenbring  (Trilinos Framework Product Lead), @bartlettroscoe 
 
## Next Action Status

Caused by upgraded SLURM/MPI correctly implementing `--mca orte_abort_on_non_zero_status 0` for `srun` on white/ride.. PR #3292 merged on 8/13/2018 which removes `--mca orte_abort_on_non_zero_status 0` and tests passed on 8/14/2018 .

## Description

As shown in [this query](https://testing-vm.sandia.gov/cdash/queryTests.php?project=Trilinos&date=2018-08-11&filtercombine=and&filtercount=3&showfilters=1&filtercombine=and&field1=testname&compare1=63&value1=TeuchosCore_testTeuchosTestForTermination&field2=status&compare2=62&value2=Passed&field3=buildname&compare3=62&value3=Trilinos-atdm-white-ride-cuda-9.2-debug-pt) the tests:

* TeuchosCore_testTeuchosTestForTermination
* TeuchosCore_testTeuchosTestForTermination_0_MPI_4
* TeuchosCore_testTeuchosTestForTermination_1_MPI_4
* TeuchosCore_testTeuchosTestForTermination_2_MPI_4
* TeuchosCore_testTeuchosTestForTermination_3_MPI_4

are failing in the builds:

* Trilinos-atdm-white-ride-cuda-9.2-opt
* Trilinos-atdm-white-ride-cuda-9.2-debug

The failures are all due to timeouts and have never passed in these builds.  The longest that any of these take on the other ATDM builds is about 30 seconds

## Steps to Reproduce

One should be able to reproduce this failure on the machine <supported-atdm-machine> as described in:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md

More specifically, the commands given for the system <supported-atdm-system> are provided at:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#ridewhite

The exact commands to reproduce this issue should be:

```

$ cd <some_build_dir>/

$ source $TRILINOS_DIR/cmake/std/atdm/load-env.sh cuda-9.2-opt

$ cmake \
 -GNinja \
 -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
 -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_Teuchos=ON \
 $TRILINOS_DIR

$ make NP=16

$ bsub -x -Is -q rhel7F -n 16 ctest -j16
```

**Comment by bartlettroscoe** [comment]
It looks like this MPI implementation is not correctly terminating the MPI job when a single rank calls `abort()`.

@ibaned, going back to our detailed conversation about the behavior of MPI and `abort()` in #1303, it looks like this MPI implementation is not behaving as it should.  I think we are seeing the same problem with the test  `KokkosCore_UnitTest_PushFinalizeHook_terminate` shown for the builds [here](Trilinos-atdm-white-ride-cuda-9.2-debug) and [here](Trilinos-atdm-white-ride-cuda-9.2-opt).  (I think @fryeguy52 will create an issue for that failing test shortly.)

**Comment by ibaned** [comment]
@bartlettroscoe from the CDash output it looks like this option is being explicitly given to MPI:
```
--mca orte_abort_on_non_zero_status 0
```
which seems to turn off the desired behavior. Why is that option being given?

**Comment by bartlettroscoe** [comment]
@ibaned said:

> Why is that option being given?

See:

* https://software-sandbox.sandia.gov/jira/browse/TRIL-198?focusedCommentId=21012&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-21012

But it did not seem to do what it was supposed to (to avoid 'bsub' crashing)  so I will try turning it off.

**Comment by fryeguy52** [comment]
The issue for the test `KokkosCore_UnitTest_PushFinalizeHook_terminate` is #3291

**Comment by bartlettroscoe** [comment]
FYI: This is fixed in PR #3287

**Comment by mhoemmen** [comment]
#3292 is the PR, no?

**Comment by bartlettroscoe** [comment]
> #3292 is the PR, no?

Yup.

**Comment by bartlettroscoe** [comment]
The merge of PR #3292 seems to have fixed this issue.  For example, you can see these tests went from failing yesterday to passing today in the build `Trilinos-atdm-white-ride-cuda-9.2-debug` [here](https://testing-vm.sandia.gov/cdash/viewTest.php?onlydelta&buildid=3830707).

Closing as complete.

**Comment by bartlettroscoe** [comment]
Closing as complete for real.
