### ISSUE TITLE
Missing ETI for Amesos2Wrapper breaks linking of Ifpack2 and all downstream packages

### ISSUE THREAD

**Issue by tawiesn** [trilinos/Trilinos#329]
> This issue appears to be this commit:
> 
> https://github.com/trilinos/Trilinos/commit/4312d673edacb4b4aa82d0b0fa47b9738bfd980f#diff-4c11d37d5b774d63c2acd88a73299d88
> 
> which introduced BlockRelaxation< row_matrix , SparseContainer < row_matrix , Amesos2Wrapper<row_matrix> > > without ETI of BlockRelaxation on that set of template parameters.
> 
> -Eric
>

**Comment by tawiesn** [comment]
Here is a workaround which allows linking Ifpack2 again:
[0001-Ifpack2-workaround-for-missing-ETI-of-Amesos2Wrapper.txt](https://github.com/trilinos/Trilinos/files/245420/0001-Ifpack2-workaround-for-missing-ETI-of-Amesos2Wrapper.txt)

Alternatively, you can turn off ETI (if that is an option for you).

**Comment by etphipp** [comment]
This patch adds Amesos2 to the ETI for BlockRelaxation:

[ifpack2_amesos2_blockrelaxation.txt](https://github.com/trilinos/Trilinos/files/245449/ifpack2_amesos2_blockrelaxation.txt)

**Comment by jhux2** [comment]
Thanks for the patch, Eric.  If you aren't already in the process of doing so, I'll review and push.

Jonathan

**Comment by mhoemmen** [comment]
@jhu applied the patch, so I'm closing this issue.  Thanks @etphipp and @jhu and others!
