### ISSUE TITLE
KokkosCore test failing on new cuda 9.2 ATDM build on white/ride

### ISSUE THREAD

**Issue by fryeguy52** [trilinos/Trilinos#3291]
CC: @trilinos/kokkos , @kddevin  (Trilinos Data Services Product Lead), @bartlettroscoe 
 
## Next Action Status

Caused by upgraded SLURM/MPI correctly implementing `--mca orte_abort_on_non_zero_status 0` for `srun` on white/ride. PR #3292 merged on 8/13/2018 which removes `--mca orte_abort_on_non_zero_status 0` and test passed on 8/14/2018 .

## Description

As shown in [this query](https://testing-vm.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=and&filtercombine=and&date=2018-08-11&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-white-ride-cuda-9.2&field2=buildname&compare2=64&value2=Trilinos-atdm-white-ride-cuda-9.2-debug-pt&field3=testname&compare3=63&value3=KokkosCore_) the tests:

* KokkosCore_UnitTest_PushFinalizeHook_terminate

are failing in the builds:

* Trilinos-atdm-white-ride-cuda-9.2-opt
* Trilinos-atdm-white-ride-cuda-9.2-debug

It is failing due to timeout 

## Steps to Reproduce

One should be able to reproduce this failure on the machine `white` as described in:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md

More specifically, the commands given for the system `white` are provided at:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#ridewhite

The exact commands to reproduce this issue should be:

```
$ cd <some_build_dir>/

$ source $TRILINOS_DIR/cmake/std/atdm/load-env.sh cuda-9.2-opt

$ cmake \
 -GNinja \
 -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
 -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_Kokkos=ON \
 $TRILINOS_DIR

$ make NP=16

$ bsub -x -Is -q rhel7F -n 16 ctest -j16
```

**Comment by bartlettroscoe** [comment]
FYI: This is fixed in PR #3287

**Comment by mhoemmen** [comment]
#3287 is an issue -- I think #3292 is the PR

**Comment by bartlettroscoe** [comment]
The merge of PR #3292 seems to have fixed this issue.  For example, you can see that this test `KokkosCore_UnitTest_PushFinalizeHook_terminate` went from failing yesterday to passing today in the build `Trilinos-atdm-white-ride-cuda-9.2-debug` [here](https://testing-vm.sandia.gov/cdash/viewTest.php?onlydelta&buildid=3830693).

Closing as complete.

**Comment by bartlettroscoe** [comment]
Closing for real.
