### ISSUE TITLE
Tpetra: Triple product calls deprecated Kokkos methods

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#3293]
@trilinos/tpetra @brian-kelley 

Tpetra's sparse triple product calls deprecated Kokkos methods.  Those methods are going away soon.  If you call them, that will break Sierra's build of Trilinos.

Here is an example of code that calls these methods: https://github.com/trilinos/Trilinos/blob/b783a65a6faed6a40372d404080ba2834f6af155/packages/tpetra/core/ext/TpetraExt_TripleMatrixMultiply_def.hpp#L966

## Possible Solution

`dimension_N` -> `extent(N)`

**Comment by cgcgcg** [comment]
@brian-kelley Let me know if you have time for this, otherwise I'll take care of it at some point..

**Comment by mhoemmen** [comment]
FYI try setting `KOKKOS_ENABLE_DEPRECATED_CODE=OFF`.

**Comment by brian-kelley** [comment]
@cgcgcg @mhoemmen I’m on travel now so I could fix it by Thursday, but maybe sooner.

**Comment by cgcgcg** [comment]
@brian-kelley I don't think that this is super urgent..

**Comment by brian-kelley** [comment]
Fixed in #3324 .
