### ISSUE TITLE
build docs out-of-source

### ISSUE THREAD

**Issue by nschloe** [trilinos/Trilinos#33]
Currently, the invocation of

```
doc/build_docs.pl
```

builds the entire documentation in-source, where it's hard to get rid of once built. This presents a difficulty, for example, when compiling for Debian. The docs, like the compiled object files, should be built outside of the source tree. (Perhaps even during the `make` process?)

**Comment by bartlettroscoe** [comment]
@trilinos/framework 

Building out-of-source is likely the right thing to do.  You would also potentially be able to use information gathered at CMake configure time to help with the process.
