### ISSUE TITLE
Create GPU-capable Thyra/Tpetra adapters for linear iterative algorithms

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#330]
**Next Action Status:** 

PR #1442 implementing this merged to 'develop'.  Next: Wait for feedback from automated testing and customers ...

**CC List:** @rppawlo 

**Description:**

The current Thyra-Tpetra adaptors simply inherit from Thyra::SpmdMultiVectorBase, implementing the getNonconstLocalDataImpl() and getLocalDataImpl() methods to get data pointers to the Tpetra data. For a GPU node, this has the effect of copying the data to the host, so that Thyra (or more likely RTOp) can manipulate it there, and then copy it back (if it is modified). What we need for this work is a new Thyra-Tpetra adapter that will call native Tpetra methods on Tpetra::MultiVector.

The initial scope of this work will be to just avoid calling RTOps in the linear iterative algorithms that are in Belos and Anasazi.  In particular, the goal is to avoid copies of data and RTOps for:
- Anasazi::BlockKrylovSchur and Anasazi::BlockKrylovSchurSolverManager
- Belos::BlockGmresSolMgr via Stratimikos DefaultLinearSolverBuilder

A tentative list of arithmetic methods needed by Anasazi BKS is: 
- MVT::SetBlock(), which calls Thyra::assign()
- MVT::MvRandom(), which calls Thyra::randomize()
- MVT::MvTimesMatAddMv(), which calls MultiVectorBase::apply()
- MVT::MvNorm(), which calls Thyra::norms_2()
- MVT::MvAddMv(), which calls Thyra::linear_combination()

Belos::BlockGmresIter and BlockGmresSolMgr require similar functionality. 

It appears that the adaptor between Thyra::LinearOpBase and Tpetra::Operator is fine.

NOTE: This is the GitHub version of the Trilinos Bugzilla ticket [#5837](https://software.sandia.gov/bugzilla/show_bug.cgi?id=5837) "Create GPU-capable Thyra adaptors for Tpetra".  This work will now be tracked in this GitHub issue and only refer back to the Bugzilla ticket for historical purposes.

**Definition of Done:**

???

**Tasks:**
1. Provide complete accounting of all of the Belos MultiVector traits functions that are called for the targeted Belos GMRES solver (set up a test case for this purpose).  (Hint: Run profiler or use Teuchos Time Monitor to determine this.)
2. Determine plan for adding minimal new virtual functions to Thyra::MultiVectorBase to replace the majority of the calls to RTOps.
3. Add new pure virtual functions to the Thyra::MultiVectorBase interface assign() and linearCombination() to replace as many RTOps as possible.
4. ???

**Comment by bartlettroscoe** [comment]
It has been a while since I looked at this so I will need to see the status of this work (i.e. what I have pushed so far).

**Comment by mhoemmen** [comment]
"Done" should mean "vector entries never touch (CPU) host memory," right?  (Norm and dot product results are still allowed to touch host memory, because Belos' interface requires it.)

**Comment by bartlettroscoe** [comment]
> "Done" should mean "vector entries never touch (CPU) host memory," right?

Likely yes, but really one just wants to remove the majority of overhead the exists right now with copying vectors back and forth from the GPU to the CPU.  We will run some performance studies to measure a native Belos/Tpetra solve and a Belos/Thyra/Tpetra solve and make sure the overhead is not too much.

We will be creating an Epic (i.e. GitHub Milestone) to get a NOX Newton Line-Search globalized algorithm running on the GPU with minimal overhead using Thyra vs. raw Tpetra.

**Comment by rppawlo** [comment]
In the short term, UVM will help in the transition.

**Comment by bartlettroscoe** [comment]
@rppawlo, I updated the description and the tasks for this ticket some.  Does Alex have a GitHub account so he can be CCed on this?

**Comment by rppawlo** [comment]
@atoth1

**Comment by bartlettroscoe** [comment]
@atoth1,

At the meeting today, you said you made progress on this.  Is there any branch that you might want me to look at at some point?

**Comment by atoth1** [comment]
Yeah, I'll push the current state to my Trilinos fork in the next couple days. I'll let you know when it's up.

**Comment by bartlettroscoe** [comment]
The PR #1442 has been merged that implements this.  Putting this into review to see what happens with automated testing and see if any users have problems with this.

**Comment by bartlettroscoe** [comment]
After the push of the merged `nox-gpu` branch earlier today, it ran in the post-push CI build shown here:

* https://testing.sandia.gov/cdash/index.php?project=Trilinos&parentid=2976678

and it built with 0 warnings and the full CI build passed.

No we will see what happens in the other Nighty builds tonight and tomorrow.
