### ISSUE TITLE
Ifpack2: Build error in BlockTriDi due to wrong return type for volatile operator+=

### ISSUE THREAD

**Issue by mrtupek** [trilinos/Trilinos#3304]
Ifpack2's overloaded `operator+=` for volatile ArrayViewType in BlockTriDi needs to return void, not a volatile reference.  This is causing a build error in Sierra.

@trilinos/ifpack2

**Comment by srajama1** [comment]
@kyungjoo-kim

**Comment by kyungjoo-kim** [comment]
@mrtupek That is actually warning but you cast it as an error with Werror flag. Am I right ?

**Comment by mhoemmen** [comment]
The error went away when we replaced the return type of just the volatile overload of that operator with `void`.

**Comment by mhoemmen** [comment]
@trilinos/ifpack2

**Comment by kyungjoo-kim** [comment]
done.
