### ISSUE TITLE
ShyLU - FROsch: cerr was not declared in this scope

### ISSUE THREAD

**Issue by ZeeD26** [trilinos/Trilinos#3326]
In several files that are part of the ShyLU - FROsch package `cerr` is used without either declaring `using namespace std` or `using std::cerr`, which leads to errors on compilation.

**Comment by ZeeD26** [comment]
To be precise, the files are:
- `FROSch_SumOperator_def.hpp`
- `FROSch_HarmonicCoarseOperator_def.hpp`

**Comment by mhoemmen** [comment]
@trilinos/shylu

**Comment by searhein** [comment]
@ZeeD26, thanks for pointing this out. I created PR #3334 which should fix this bug.

**Comment by mhoemmen** [comment]
Is this fixed?

**Comment by searhein** [comment]
Yes. This should be fixed. I think that we can close the issue.
