### ISSUE TITLE
Albany build error due to missing STK header in Trilinos

### ISSUE THREAD

**Issue by ikalash** [trilinos/Trilinos#3327]
The Albany nightlies started to fail yesterday, I think due to a change in STK.  Here is the error: 

```
/.../repos/Albany/src/disc/stk/percept/stk_rebalance/GeomDecomp.cpp(23): catastrophic error: cannot open source file "stk_util/environment/ReportHandler.hpp"
```
It seems there is now a missing STK header.  Here is the error in the Albany CDash: http://cdash.sandia.gov/CDash-2-3-0/viewBuildError.php?buildid=75015 .

**Comment by mhoemmen** [comment]
@alanw0 @trilinos/stk

**Comment by spdomin** [comment]
If I may augment this thread, I would be most appreciative. Aside from the expected API changes, another issue is as follows:

[ 86%] Building CXX object packages/stk/stk_io/stk_io/CMakeFiles/stk_io.dir/IossBridge.cpp.o
/Users/naluIt/gitHubWork/nightlyBuildAndTest/Trilinos/packages/stk/stk_io/stk_io/IossBridge.cpp:40:10: fatal error: 
      'ext/alloc_traits.h' file not found
#include <ext/alloc_traits.h>

The STK resolved this issue already, however, I need another update. Does anyone know when the next update of STK in Trilinos will be? @bmpersc once was the contact for such updates.

Best

**Comment by spdomin** [comment]
@ikalash, this might help (a message from @alanw0:
 
The header ‘ReportHandler.hpp’ has moved from stk_util/environment to stk_util/util. This was done to solve a circular dependency issue among stk libraries. This means nalu will have to change include-statements from ‘#include <stk_util/environment/ReportHandler.hpp>’ to ‘#include <stk_util/util/ReportHandler.hpp>’.
 
In stk_mesh/base/FieldParallel.hpp, the functions parallel_sum/min/max used to take a vector of non-const FieldBase pointers, now they take a vector of const FieldBase pointers. This is an improvement in const-correctness, and an improvement in consistency of those stk functions. This means the vectors nalu passes to them will need to be changed from std::vector<stk::mesh::FieldBase*> to std::vector<const stk::mesh::FieldBase*>.

**Comment by alanw0** [comment]
I've been filtering trilinos-github messages to a folder, because I get about 100 of them per day and 99.9 of them aren't related to me. I'll update my filters to make sure I see the relevant stuff.

@spdomin, @prwolfe is the one who is now working on the stk updates into Trilinos. He is producing some nice scripts for automation, so the updates should start to come more frequently now. (Hopefully much more frequently than the 1/year that has been the norm recently.)

**Comment by spdomin** [comment]
I can conform that all NaluCFD rtests are clean this morning after a number of both Tpetra changes and application code modifications. Many thanks for the fast response.

**Comment by prwolfe** [comment]
@ikalash - since you confirmed this issue is resolved can we close this issue? You should open a separate one if there are additional problems.

Thanks!

**Comment by ikalash** [comment]
Yes, I will close it.  Note that STK did introduce a bug that is causing a number of Albany tests to fail.  This is in a separate issue: https://github.com/trilinos/Trilinos/issues/3377 .

**Comment by prwolfe** [comment]
Perfect - Thanks!
