### ISSUE TITLE
Teko: make Epetra dependency optional

### ISSUE THREAD

**Issue by ibaned** [trilinos/Trilinos#3328]
@trilinos/teko

## Expectations

It should be possible to install Teko without having to build Epetra, if one is using only Tpetra-stack solvers.

## Current Behavior

We have reports that Teko depends on `ThyraEpetraAdapters`, which requires building Epetra.

## Motivation and Context

Applications that use only Tpetra-stack tools would prefer not to spend time compiling the Epetra stack.

**Comment by ibaned** [comment]
@ikalash @bartgol

**Comment by ibaned** [comment]
This means also not requiring Ifpack, Amesos, AztecOO, and ML.

**Comment by bartgol** [comment]
Ideally, this would go both ways: if someone is using Epetra, he/she should not have to build Tpetra.

About Ifpack: it is listed as a required dependency, but I can't grep any Ifpack related stuff. I see Ifpack2 (properly guarded by macros), but no Ifpack. And it is puzzling to see Ifpack as a required lib, while Ifpack2 is optional, even though Tpetra is a required dependency.

I guess what we are asking is: is there a way to make teko "petra-unaware"? Perhaps having all the petra-specific stuff into an adapters folder (much like thyra)?

**Comment by ibaned** [comment]
@mhoemmen I agree
