### ISSUE TITLE
Tpetra: Add option to allocate "device" memory only when in use?

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#333]
@trilinos/tpetra Some Tpetra classes implement "DualView" semantics, where they maintain mirrored allocations in both "host" and "device" memory, and let users sync data between the two.  Here, "host" memory implies "large and slower," and "device" memory implies "small and faster" (for some meaning of "fast").  Currently, Tpetra classes that implement DualView semantics allocate on both host and device.  This won't support the use case where users want to treat device memory as a temporary workspace.

To fix this, we would need an option for device memory to stay unallocated if not in use.  Sync to device memory would allocate device memory, and sync to host memory would deallocate device memory.

Note that Kokkos::DualView would need to store both of its Views by pointer (std::shared_ptr?) rather than by value, if it wants to implement these semantics.  (DualView itself has view semantics.  If you copy the struct, and one copy allocates a View, then the other copy won't get it, unless the Views are held by pointer, rather than by value.)

**Comment by crtrott** [comment]
DualView can't store its view as pointers. Those pointers would not be valid on the Device, also it has quiet some bad performance ramifications. Tpetra can do something more clever though. Doing lazy allocation and deallocation with DualView directly might be more difficult, since the interactions with the reference counting system have to be sorted out.

**Comment by mhoemmen** [comment]
> DualView can't store its view as pointers. Those pointers would not be valid on the Device, also it has quiet some bad performance ramifications. Tpetra can do something more clever though.

I think so.  Tpetra objects already hold stuff by pointer (RCP even) and already do some lazy allocation and initialization.  Map, for example, lazily initializes the Directory (since it's expensive to initialize, and is only needed if users call getRemoteIndexList()).  Here's what I'm thinking:

1. Tpetra objects stop exposing the Kokkos::DualView directly
2. Tpetra objects implement the full DualView interface
3. Getting a View in a particular memory space may allocate if the View hasn't already been allocated
4. Tpetra objects then don't have to store the Views by pointer, since the only way to get a View is to call the appropriate method (which can allocate if necessary).

**Comment by mhoemmen** [comment]
See #364 for discussion.
