### ISSUE TITLE
MueLu_UnitTestsTpetra_MPI_4 failing (timeout) in ATDM cuda builds on waterman 

### ISSUE THREAD

**Issue by fryeguy52** [trilinos/Trilinos#3341]
CC: @trilinos/muelu , @srajama1  (Trilinos Linear Solvers Product Lead), @bartlettroscoe
 
## Next Action Status

Duplicate of #3491 which was closed on 9/27/2018.

## Description

As shown in [this query](https://testing-vm.sandia.gov/cdash/queryTests.php?project=Trilinos&date=2018-08-21&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-waterman-cuda&field2=testname&compare2=61&value2=MueLu_UnitTestsTpetra_MPI_4&field3=buildstarttime&compare3=84&value3=now) the test:

* MueLu_UnitTestsTpetra_MPI_4

is failing in the builds:

* Trilinos-atdm-waterman-cuda-9.2-opt
* Trilinos-atdm-waterman-cuda-9.2-debug

In the [cdash results for yesterday](https://testing-vm.sandia.gov/cdash/queryTests.php?project=Trilinos&date=2018-08-21&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-&field2=testname&compare2=61&value2=MueLu_UnitTestsTpetra_MPI_4) we can see that this test on cuda builds is taking 6+ minutes to complete and on non-cuda builds completes in less than 90 sec.  Waterman is the only platform where it hit the timeout but others are very close.  for example, one build on `ride` took 9:49 yesterday.

## Steps to Reproduce

One should be able to reproduce this failure on the machine waterman as described in:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md

More specifically, the commands given for the system waterman are provided at:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#waterman

The exact commands to reproduce this issue should be:

```
$ cd <some_build_dir>/

$ source $TRILINOS_DIR/cmake/std/atdm/load-env.sh cuda-debug

$ cmake \
  -GNinja \
  -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
  -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_MueLu=ON \
  $TRILINOS_DIR

$ make NP=20

$ bsub -x -Is -n 20 ctest -j20
```

**Comment by srajama1** [comment]
@trilinos/muelu

**Comment by jhux2** [comment]
This isn't surprising.  The cmake configure command for the builds in question does not enable MueLu's Kokkos code path.  I'd point you to MueLu's dashboard to look at one of its CUDA builds, but the dashboard is empty (broken?).  Try adding
```
      -DMueLu_ENABLE_Kokkos_Refactor:BOOL=ON
      -DMueLu_ENABLE_Kokkos_Refactor_Use_By_Default:BOOL=ON
      -DXpetra_ENABLE_Kokkos_Refactor:BOOL=ON
```

**Comment by rppawlo** [comment]
I was having some trouble on ride builds and the same thing is happening there. Did we lose the inclusion of some setup variables in the atdm build scripts? I thought these were added a while ago.

**Comment by bartlettroscoe** [comment]
@rppawlo, are you referring to the Kokkos refactor options in #2674?

**Comment by rppawlo** [comment]
yes. The flags above are the same ones. I just checked my atdm build on ride and they were set to off.

**Comment by bartlettroscoe** [comment]
@jhux2 said:

> Try adding
> 
> ```
>      -DMueLu_ENABLE_Kokkos_Refactor:BOOL=ON
>     -DMueLu_ENABLE_Kokkos_Refactor_Use_By_Default:BOOL=ON
>     -DXpetra_ENABLE_Kokkos_Refactor:BOOL=ON
> ```

@rppawlo and @jhux2, would it not make sense to have MueLu set these to on automatically when doing a CUDA build?  What is the purpose of having these off for CUDA builds if the tests can't pass with them turned off?

**Comment by rppawlo** [comment]
These should probably all be set to "ON" by default if kokkos is enabled. I think that's what the majority of customers would expect.

**Comment by csiefer2** [comment]
@rppawlo I'm not sure about that.  I think you only really want the KokkosRefactor stuff if you're not using SerialNode.

**Comment by jhux2** [comment]
@bartlettroscoe wrote:
> would it not make sense to have MueLu set these to on automatically when doing a CUDA build? What is the purpose of having these off for CUDA builds if the tests can't pass with them turned off?

I agree, these should be on automatically for CUDA builds.

>> I think you only really want the KokkosRefactor stuff if you're not using SerialNode.
> 
> Then we could just tie the default for each of the flags above to depend on the default node type in kokkos?

@rppawlo I think this is a reasonable approach.  However, would we ever have a case when CUDA and Serial node types are simultaneously enabled?

**Comment by rppawlo** [comment]
Cuda and Serial are almost always enabled together. The ATDM builds show this:
```
-- ****************** Kokkos Settings ******************
-- Execution Spaces
--   Device Parallel: Cuda
--     Host Parallel: None
--       Host Serial: Serial
...
-- Enabled options
--   KOKKOS_ENABLE_SERIAL
--   KOKKOS_ENABLE_CUDA
--   KOKKOS_ENABLE_CUDA_LAMBDA
--   KOKKOS_ENABLE_CUDA_UVM
--   KOKKOS_ENABLE_DEPRECATED_CODE
...
=======================
KokkosKernels ETI Types
   Devices:  <Cuda,CudaSpace>;<Cuda,CudaUVMSpace>;<Serial,HostSpace>
   Scalars:  double
   Ordinals: int
   Offsets:  int;size_t
=======================
...
-- HAVE_MUELU_SERIAL       : ON
-- HAVE_MUELU_PTHREAD      : OFF
-- HAVE_MUELU_OPENMP       : OFF
-- HAVE_MUELU_CUDA         : ON
```
The check should use the the default device space, not whether a specific space is enabled. The default device space will only be serial if no other space is enabled. @crtrott can probably comment more here.

**Comment by bartlettroscoe** [comment]
@trilinos/muelu, @sphamil (Trilinos Linear Solver Product Area Lead),

So from the experiments documented at https://github.com/trilinos/Trilinos/pull/3482#issuecomment-423775974, it looks like turning on the MueLu Kokkos Refactor options (#2674) don't help to avoid this timing out test at all; it just creates more failures.

Now what?

**Comment by fryeguy52** [comment]
shown [here](https://testing.sandia.gov/cdash-dev-view/queryTests.php?project=Trilinos&date=2018-09-22&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-white-ride-cuda&field2=buildname&compare2=64&value2=-pt&field3=site&compare3=61&value3=white&field4=testname&compare4=61&value4=MueLu_UnitTestsTpetra_MPI_4&field5=buildstarttime&compare5=83&value5=2018-09-20) this test is now also also failing intermittently on white in the builds:
* Trilinos-atdm-white-ride-cuda-9.2-opt
* Trilinos-atdm-white-ride-cuda-9.2-debug

**Comment by bartlettroscoe** [comment]
The duplicate issue #3491 was just closed with all passing tests.
