### ISSUE TITLE
Anasazi_Tpetra_MVOPTester_MPI_4 failing in ATDM cuda 9 builds on waterman 

### ISSUE THREAD

**Issue by fryeguy52** [trilinos/Trilinos#3344]
CC: @trilinos/anasazi,  @srajama1  (Trilinos Linear Solvers Product Lead), @bartlettroscoe 
 
## Description

As shown in [this query](https://testing-vm.sandia.gov/cdash/queryTests.php?project=Trilinos&date=2018-08-21&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-waterman-cuda&field2=testname&compare2=61&value2=Anasazi_Tpetra_MVOPTester_MPI_4&field3=buildstarttime&compare3=84&value3=now) the test:

* Anasazi_Tpetra_MVOPTester_MPI_4

is failing in the builds:

* Trilinos-atdm-waterman-cuda-9.2-opt
* Trilinos-atdm-waterman-cuda-9.2-debug

test output
```
The following tests FAILED:
    7. MultiVector_int_longlong_double_OPTestLocal_UnitTest ... 

Total Time: 7.62 sec

Summary: total = 8, run = 8, passed = 7, failed = 1

End Result: TEST FAILED
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpiexec detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[50974,1],2]
  Exit code:    1
```

## Steps to Reproduce

One should be able to reproduce this failure on the machine waterman as described in:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md

More specifically, the commands given for the system waterman are provided at:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#waterman

The exact commands to reproduce this issue should be:

```

$ cd <some_build_dir>/

$ source $TRILINOS_DIR/cmake/std/atdm/load-env.sh cuda-debug

$ cmake \
  -GNinja \
  -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
  -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_Anasazi=ON \
  $TRILINOS_DIR

$ make NP=20

$ bsub -x -Is -n 20 ctest -j20
```

**Comment by srajama1** [comment]
@hkthorn : One more, sorry !

**Comment by hkthorn** [comment]
@fryeguy52 @bartlettroscoe Please let me know if this is still an issue after the OpenMPI version is changed for the ATDM waterman testing.

**Comment by bartlettroscoe** [comment]
After the merge of PR #3363 last night, these Anasazi tests are no longer failing in any of the 4 'waterman' builds as shown [here](https://testing-vm.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=and&date=2018-08-28&filtercombine=and&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-waterman&field2=status&compare2=62&value2=passed&field3=status&compare3=62&value3=notrun).

**Comment by bartlettroscoe** [comment]
FYI: I added the label "ATDM Env Issue" since this turned out to be a problem with OpenMPI 3.1.0 on 'waterman' and downgrading to OpenMPI 2.1.2 fixed the problem.
