### ISSUE TITLE
stk broken in clean Linux-gcc-4.8.4-MPI_Release_gcc_4.8.4_openmpi_1.8.7_DEV build

### ISSUE THREAD

**Issue by prwolfe** [trilinos/Trilinos#3347]
Looks like the recent import of stk (commit de635abc146449dc1c4dbbea65cefda91946755e) caused failures in the Linux-gcc-4.8.4-MPI_Release_gcc_4.8.4_openmpi_1.8.7_DEV build.

Gcc 4.8.4 does not support brace-list initialization which is used in one of the unit tests. This was turned off in the PR testing, but looks like it was missed in this build. See commit 465f04753fcb8e6bf7047cc03d1cce54e254d25f for details.

@trilinos/framework 
@trilinos/stk

**Comment by alanw0** [comment]
@prwolfe I pushed an attempted fix for this. We have brace-initialization all over our code, so I'm not sure why the 4.8.4 compiler didn't like this one, except maybe because it didn't have an equals-sign...

**Comment by prwolfe** [comment]
Might be, I missed that.  I will build it locally to check.

**Comment by prwolfe** [comment]
I think this was fixed by #3361, but the affected build did not report to todays dashboard.

**Comment by prwolfe** [comment]
This built and reported clean today. Closing.
