### ISSUE TITLE
stk broken in clean Linux-gcc-4.9.3-SERIAL_Release_gcc_4.9.3__DEV builds

### ISSUE THREAD

**Issue by prwolfe** [trilinos/Trilinos#3348]
Looks like the recent import of stk (commit de635ab) caused failures in the Serial build. The vast majority of stk does not build for Serial, but stk_math does and the unit test executable says it has no main function. This uses gtest but does not include a main which works for MPI.

@trilinos/stk 

## Steps to Reproduce
I was able to reproduce this using PullRequestGCC4.9.3TestingEnv.sh and the configure line/build commands from the Serial build on the dashboard (https://testing-vm.sandia.gov/cdash/buildSummary.php?buildid=3861133)

**Comment by alanw0** [comment]
I will take a look at this, hopefully will be a quick/easy fix.

**Comment by alanw0** [comment]
@prwolfe I will push a fix for this right away, looks like a simple fix.

**Comment by alanw0** [comment]
@prwolfe ok, after some rearranging, I think I got it sorted out. It's pushed on the sierra side.

**Comment by prwolfe** [comment]
I'm betting that is why all the other packages are disabled in Serial as well.

**Comment by prwolfe** [comment]
Oh, that's what I get for being slow.

**Comment by william76** [comment]
Link to the dashboard [4.8.4 MPI, 4.9.3 SERIAL, and in the 4.8.4 MPI continuous builds][1].

[1]: https://testing-vm.sandia.gov/cdash/index.php?project=Trilinos&date=2018-08-27&filtercount=2&showfilters=1&filtercombine=or&field1=groupname&compare1=63&value1=Clean&field2=groupname&compare2=63&value2=Continuous

**Comment by prwolfe** [comment]
This was resolved by #3361 as shown on todays dashboard.
