### ISSUE TITLE
NOX:  Handling of model changes in Thyra::NOXNonlinearSolver

### ISSUE THREAD

**Issue by etphipp** [trilinos/Trilinos#335]
The Thyra::NOXNonlinearSolver has a method to update the Thyra::ModelEvaluator model used within the nonlinear solve, however that model is not propagated to the internal NOX group if the internal solver has already been setup.  I ran into this with Dakota/ROL runs where I was doing a sequence of transient solves at different parameter values.  After each transient solve, a new model is created however the same nonlinear solver is reused.  After the first transient solve, we would compute a new model and set it in the nonlinear solver, but subsequent nonlinear solves were still using the old model.  We can work around this by reseting the solver after each transient run, but it would be ideal of the NOXNonlinearSolver handled this.

@rppawlo @eric-c-cyr

**Comment by rppawlo** [comment]
@etphipp When you set the new model will it have the same structure or could the residual, Jacobian and preconditioner change shape and non-zero pattern? If it has the same structure, I can just change the underlying model pointer, but if structure changes then we should internally just rebuild the solver. I think it is probably safer from a library standpoint to assume that there is a potential structure change and rebuild the underlying solver. This does come with extra overhead of deleting and reallocating memory for the solver as oppposed to just setting a new model.

**Comment by etphipp** [comment]
In my particular case the model had the same structure.  It was just that after each solve a new model evaluator decorator was created with new internal state data (namely time integration data), so just updating the model pointer in the group would be safe.  You could add an option to the method where you set the model to control whether the solver is destroyed and recreated from scratch.

**Comment by rppawlo** [comment]
The setModel method is derived from Thyra nonlinear solver base, so adding an extra argument would require thyra changes. Instead, I'm thinking we could check whether the vector spaces for the solution and residual are compatible and if it supports W will also check if the range and domain are compatible. If compatible then it will set the model ptr instead of destroying the nox solver. If any are incompatible, the it will rebuild the nox solver. Is this ok?

**Comment by etphipp** [comment]
Sounds good to me.

**Comment by rppawlo** [comment]
@etphipp the solvers and the groups currently don't accept a new model. The assumption was that if a new model is set then you need to rebuild the solver. To add this functionality I would need to add a new method to the base classes and then add the logic to all solvers to loop over owned groups. I can do that, but it will require more work to all solvers and groups. A simpler alternative is that if we set the model on the Thyra::NOXNonlinearSolver then it will automatically rebuild the group. If that is ok, that will be much quicker to implement.

**Comment by rppawlo** [comment]
@etphipp The changes just pushed. I will leave "in review" until you can verify this works for your use case.

**Comment by etphipp** [comment]
I tested this in EMPIRE, and it appears to work.  So I think you can close this now.
