### ISSUE TITLE
Amesos: limit of dimension or nonzero-entries of the matrix?

### ISSUE THREAD

**Issue by ghtina** [trilinos/Trilinos#3350]
I had a matrix with a dimension over 2.5 Million and it works for Amesos with the Pardiso Solver, the number of nonzeros was about 200 Million). However, as I changed the Solver to the Klu solver, it didn't work anymore. The resulted vector was filled with zeros.
So my question is why and has Amesos (or one of its Solver Library) a general constraint in either the dimension or number of nonzeros of the matrix?

**Comment by srajama1** [comment]
No, there is no such limit (except 2B for int, a sequential direct solver may not be needed at this scale anyway). Klu is a simplicial (or non-supernodal) solver. In terms of performance, there are cases where it is very good and there are cases where Pardiso (which is a supernodal solver) is very good. However, you should not get zeroes back. What is this matrix ?

**Comment by freaklovesmango** [comment]
Since the matrix is really large, I unfortunately couldn't show you. I used the Epetra_CrsMatrix and the entries are correctly inserted as I printed out the matrix. However, after calling the Solver and printing out the lhs, the whole vector was filled with zeros.
