### ISSUE TITLE
STK update causes errors when building Trilinos with Clang

### ISSUE THREAD

**Issue by jrood-nrel** [trilinos/Trilinos#3351]
@trilinos/stk

Recently STK was updated and it appears that building Trilinos with STK using Clang now fails with a missing header. This has been tested with both LLVM 6.0 on Linux and Apple Clang 9.0 on OSX with this same error:
```
trilinos/packages/stk/stk_io/stk_io/IossBridge.cpp:40:10: fatal error: 'ext/alloc_traits.h' file not found
#include <ext/alloc_traits.h>
         ^~~~~~~~~~~~~~~~~~~~
```

We build Triinos develop and master nightly for our project and the results can be seen at https://my.cdash.org/index.php?project=Nalu-Wind and output for building Trilinos that shows this error can be seen in the notes for each build, but I can try to provide more information if necessary.

**Comment by jhux2** [comment]
@trilinos/stk @alanw0 @khpierson  
Not sure if they're related, but also see issues #3347 and #3348.

**Comment by alanw0** [comment]
@CamelliaDPG yes the stk team has fixed those and @prwolfe has been working to get some revised pull-requests through the Trilinos PR system. Those #includes of ext/alloc_traits.h had been added accidentally when someone used a clang tool to clean up our includes, supposedly "helping" our code base. Lesson learned, don't do that...

**Comment by jrood-nrel** [comment]
Looks like this has been fixed. Thanks!
