### ISSUE TITLE
TPetra timers not stackable, 

### ISSUE THREAD

**Issue by bathmatt** [trilinos/Trilinos#3362]
If one enables the tpetra timers you find that they are started and stopped not in a sequence.  You stop a timer when it isn't the last one started.  You are probably keeping RCPs to timers.. 

@trilinos/tpetra

## Expectations

Expect the timers to be on a stack.
## Current Behavior

I can't get timing info from tpetra, 

Here is error message 

```
 ctest -R PanzerAdaptersSTK_projection

*********************************************************************
WARNING: Overlapping timers detected!
A TimeMonitor timer was stopped before a nested subtimer was
stopped. This is not allowed by the StackedTimer. This corner case
typically occurs if the TimeMonitor is stored in an RCP and the RCP is
assigned to a new timer. To disable this warning, either fix the
ordering of timer creation and destuction or disable the StackedTimer
support in the TimeMonitor by setting the StackedTimer to null
with:
Teuchos::TimeMonitor::setStackedTimer(Teuchos::null)
*********************************************************************

```
## Steps to Reproduce

1.  Enable tpetra timers  -D  Tpetra_ENABLE_MMM_Timings=ON
1. Enable panzer tests 
1. Run panzer tests   ctest -R PanzerAdaptersSTK_projection
1. Shake fist angrily at computer.

## Your Environment

- **Relevant repo SHA1s:**  
- **Relevant configure flags or configure script:**  
- **Operating system and version:**  
- **Compiler and TPL versions:**  

## Related Issues

* Blocks 
* Is blocked by 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of

**Comment by bathmatt** [comment]
@rppawlo @mhoemmen

**Comment by mhoemmen** [comment]
This issue probably comes from code handling `Teuchos::TimeMonitor` by RCP.  This is a MueLu developers' idiom.  I don't like it and I don't write code that way, but this isn't just a Tpetra problem.

**Comment by bathmatt** [comment]
Does that tpetra flag turn on timers in muelu?  

I don't like that either

It looks like it is a tpetra timer that never stopped..

 p=0 |  Stopping timer projectionFactory.buildMassMatrix() But top level running timer is Tpetra : TAFC ImportSetup


dir-~ (gcc) 105 $ cd Trilinos/Trilinos/packages/tpetra/
dir-tpetra (gcc) 106 $ find . -name \*pp -exec grep TAFC\ ImportSetup {} \;
    MM = Teuchos::rcp(new TimeMonitor(*TimeMonitor::getNewTimer(prefix + std::string("TAFC ImportSetup"))));
^C
dir-tpetra (gcc) 107 $ find . -name \*pp -exec grep -l TAFC\ ImportSetup {} \;
./core/src/Tpetra_CrsMatrix_def.hpp



TAFC ImportSetup..

**Comment by csiefer2** [comment]
Yeah, it does that.  Because all of that stuff predates StackedTimer.

**Comment by csiefer2** [comment]
Two other points: 

1) All of those timers *do* stop (implictly on destruction), including the one you point out.
2) You only need to enable this option if you care about detailed timing of the matrix-matrix multiplication kernel.  If you don't care about that, turn those off.

**Comment by bathmatt** [comment]
It was the only timers that seem to be enabled by cmake. there are others, but they are ifdef'ed out.  I need all the timers I can get.  Any good idea on how to do this?

**Comment by mhoemmen** [comment]
I'm confused -- does this just print a warning, or does it print a warning AND refuse to dump timing information?  I thought it was only the former, in which case this is no big deal and I don't want @csiefer2 to feel troubled about it :-)  If it's the latter, we might need to talk more.

**Comment by bathmatt** [comment]
It excepts out actually.  so....  I can skip these since I don't think the do a MM in the time step, only the preconditioner setup.  I'm just grasping for any timers I can get since we are trying to track down performanceissues.

**Comment by csiefer2** [comment]
Yeah, if you're timing in the timestep, these guys won't help you.

**Comment by cgcgcg** [comment]
@bathmatt It seems the matvecs are using kokkos profiling regions, not Teuchos timers. So running with kokkos profiling enabled and the kokkos tools https://github.com/kokkos/kokkos-tools should be giving you the information you are after. I tried this on Cori, but it crashed on me, and I did not have time to investigate.
