### ISSUE TITLE
Tpetra DefaultTypes::scalar_type is always double; should it allow float?

### ISSUE THREAD

**Issue by kddevin** [trilinos/Trilinos#3366]
It is permissible to build Tpetra with Tpetra_INST_DOUBLE=OFF and Tpetra_INST_FLOAT=ON, correct?

Currently namespace DefaultTypes says the default scalar_type is double always.  If building with FLOAT but not DOUBLE is allowed, then in Tpetra_Details_DefaultTypes.hpp,  we should have something like

> #if defined(HAVE_TPETRA_INST_DOUBLE)
>   typedef double scalar_type
> #elif defined(HAVE_TPETRA_INST_FLOAT)
>   typedef float scalar_type
> #else
>   #error "too bad, so sad"
> #endif

Similar logic already exists in that file for the various ordinal types.

If, instead, we always want the default scalar type to be double, we should remove the Tpetra_INST_DOUBLE CMake option, so that users do not get compilation errors by disabling DOUBLE.

#604

**Comment by mhoemmen** [comment]
I'm almost certain that other packages assume that Tpetra always enables Scalar=double.  We should fix this in Tpetra, but my guess is that nothing downstream of Tpetra would build correctly in that case.

**Comment by kddevin** [comment]
Thanks, @mhoemmen 
I made the proposed change, which should affect no one if Tpetra  enables scalar = double. It does allow me to test with other default types, as Zoltan2 will now work without scalar = double.
I will check the PR testing tomorrow. #3368
