### ISSUE TITLE
Ifpack2: OverlappingPartitioner unit test (for BlockRelaxation) fails for me with OMP_NUM_THREADS = 2

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#338]
@trilinos/ifpack2 It doesn't fail for OMP_NUM_THREADS=1 for me.
I'm commenting out the test for now so I can fix #243.

**Comment by mhoemmen** [comment]
This may be related to #243.

**Comment by jhux2** [comment]
> This may be related to #243.

Is it safe to reenable this test?

**Comment by jhux2** [comment]
I've reenabled this test since #243 has been resolved.

**Comment by mhoemmen** [comment]
I'm not _very_ pleased with the #243 work-around.  That will need some more work.  I expect BLAS implementations to cause trouble for us in the future with respect to threads.  On the other hand, I think it's good to reimplement this test as another check for the #243 work-around and future fix.  Thanks!

**Comment by mhoemmen** [comment]
Test still fails for me.  I'm reopening this issue.

**Comment by mhoemmen** [comment]
Test fails for me with random initial guess (not current state of code) with no threads at all.  putScalar(1) (current state of the code) works.
