### ISSUE TITLE
Panzer: Add option to print dependency graph to screen

### ISSUE THREAD

**Issue by rppawlo** [trilinos/Trilinos#339]
A request from @glhenni :

Is there a way to get the DAG manager to dump the evaluator list to the screen when it's successful? The same dump it does when it's unsuccessful due to a dependency error?

The graphs are nice but having something searchable with a text editor when trying to figure out dependency problems would add give another valuable, to me, method to find the problem. You can get the *.dot files with
```
  <ParameterList name="Options">
    <Parameter name="Write Volume Assembly Graphs" type="bool" value="false"/>
    <Parameter name="Volume Assembly Graph Prefix" type="string" value="charon_"/>
  </ParameterList>
```
in the input file. It'd be nice to having something similar for just dumping the evaluators and their evaluated and dependent fields to the screen.

**Comment by rppawlo** [comment]
cc: @trilinos/panzer

**Comment by rppawlo** [comment]
the Field manager has an ostream overload to support printing. There is an option to dump to a file, but we just need to add a few lines of code to add an option to dump to screen. 

@glhenni - Do you want the BC evaluators too or just the element blocks?

**Comment by glhenni** [comment]
If it dumps the same info that gets dumped to the screen when there's a dependency error then dumping to a file is fine. I would typically redirect it to a file anyway. Something I can search and is easier to see than the giant graph is just helpful sometimes. I als need a setting available from the input file to turn it on.

The last issue I ran into was with the BCs, but I'd say it's more typical to have issues with the volumetric evaluators. I would prioritize the volumetric dump first, BCs second.

**Comment by rppawlo** [comment]
@glhenni This is completed. You can trigger by adding the following to the Options block:

```
    <ParameterList name="Options">
        <Parameter name="Write Field Manager Files" type="bool" value="true"/>
        <Parameter name="Field Manager File Prefix" type="string" value="my_file_name_prefix"/>
    </ParameterList>

```
