### ISSUE TITLE
KokkosKernels: Fix ETI

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#340]
@trilinos/tpetra 
We need to fix ETI for KokkosKernels, in order to keep build and link times down for Tpetra and downstream packages.  This is especially important for link-time optimization (LTO).

A fix would be to use the same .cpp file generation approach used in TpetraCore and Ifpack2.

**Comment by srajama1** [comment]
There is another issue opened by @bathmatt #226 that is related.

**Comment by mhoemmen** [comment]
@crtrott fixed this in kokkos-kernels a while back.
