### ISSUE TITLE
Tempus: Ensure Steppers get fully initialized.

### ISSUE THREAD

**Issue by ccober6** [trilinos/Trilinos#3400]
Several Steppers did not call some set* functions, thus
Steppers might not be fully initialized.  Biggest offender
was DIRK.

@trilinos/@tempus

## Your Environment

- **Relevant repo SHA1s:**  
- **Relevant configure flags or configure script:**  
- **Operating system and version:**  
- **Compiler and TPL versions:**  

## Related Issues

* Blocks 
* Is blocked by 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of

**Comment by Tempus** [comment]
Just a heads up, @Tempus sends me messages.

**Comment by rppawlo** [comment]
> Just a heads up, @Tempus sends me messages.

I think this was a mistake in the ticket. The cc was written @Trilinos/@Tempus when it should have been @Trilinos/tempus (note the extra "@" on Tempus).

**Comment by ccober6** [comment]
Interesting...  I put an extra "@" in there but with lower case tempus.  Sorry for the spam.
