### ISSUE TITLE
Error in package Sundance while running serial make of Trilinoss 12.12.1

### ISSUE THREAD

**Issue by aishaque** [trilinos/Trilinos#3413]
Hi, 

My system is running Ubuntu 18.04 LTS on an HP Zbook 17 G3.

I am doing a build and install for Trilinos as a prelude for installing Xyce and have followed the instruction given at https://xyce.sandia.gov/documentation/BuildingGuide.html#ubuntuPreReq.  I was able to complete the make using the sample shell script for serial build given on this page. However, when I enable the make for all packages and run the make command I encounter an error, which I have posted below. Can someone help me in eliminating this error?  

[ 89%] Building CXX object packages/piro/src/CMakeFiles/piro.dir/Piro_Epetra_PerformAnalysis.cpp.o
[ 89%] Building CXX object packages/piro/src/CMakeFiles/piro.dir/Piro_PerformAnalysis.cpp.o
[ 89%] Linking CXX static library libpiro.a
[ 89%] Built target piro
Scanning dependencies of target sundancePlaya
[ 89%] Building CXX object packages/Sundance/Playa/src/CMakeFiles/sundancePlaya.dir/EpetraPlayaOperator.cpp.o
[ 89%] Building CXX object packages/Sundance/Playa/src/CMakeFiles/sundancePlaya.dir/NOX_Playa_Group.cpp.o
/home/amir/Trilinos12.12/trilinos-12.12.1-Source/packages/Sundance/Playa/src/NOX_Playa_Group.cpp: In constructor ‘NOX::NOXPlaya::Group::Group(const Playa::Vector<double>&, const Playa::NonlinearOperator<double>&, const Playa::LinearSolver<double>&)’:
/home/amir/Trilinos12.12/trilinos-12.12.1-Source/packages/Sundance/Playa/src/NOX_Playa_Group.cpp:71:70: error: invalid new-expression of abstract class type ‘NOX::NOXPlaya::Vector’
   xVector(rcp(new NOX::NOXPlaya::Vector(initcond, precision, DeepCopy))),
                                                                      ^
In file included from /home/amir/Trilinos12.12/trilinos-12.12.1-Source/packages/Sundance/Playa/src/NOX_Playa_Group.hpp:57:0,
                 from /home/amir/Trilinos12.12/trilinos-12.12.1-Source/packages/Sundance/Playa/src/NOX_Playa_Group.cpp:51:
/home/amir/Trilinos12.12/trilinos-12.12.1-Source/packages/Sundance/Playa/src/NOX_Playa_Vector.hpp:75:7: note:   because the following virtual functions are pure within ‘NOX::NOXPlaya::Vector’:
 class Vector : public NOX::Abstract::Vector
       ^~~~~~
In file included from /home/amir/Trilinos12.12/trilinos-12.12.1-Source/packages/nox/src/NOX_Abstract_Group.H:54:0,
                 from /home/amir/Trilinos12.12/trilinos-12.12.1-Source/packages/Sundance/Playa/src/NOX_Playa_Group.hpp:53,
                 from /home/amir/Trilinos12.12/trilinos-12.12.1-Source/packages/Sundance/Playa/src/NOX_Playa_Group.cpp:51:
/home/amir/Trilinos12.12/trilinos-12.12.1-Source/packages/nox/src/NOX_Abstract_Vector.H:137:34: note: 	virtual NOX::Abstract::Vector& NOX::Abstract::Vector::random(bool, int)
   virtual NOX::Abstract::Vector& random(bool useSeed = false, int seed = 1) = 0;
                                  ^~~~~~
/home/amir/Trilinos12.12/trilinos-12.12.1-Source/packages/Sundance/Playa/src/NOX_Playa_Group.cpp:72:71: error: invalid new-expression of abstract class type ‘NOX::NOXPlaya::Vector’
   fVector(rcp(new NOX::NOXPlaya::Vector(initcond, precision, ShapeCopy))),
                                                                       ^
/home/amir/Trilinos12.12/trilinos-12.12.1-Source/packages/Sundance/Playa/src/NOX_Playa_Group.cpp:73:76: error: invalid new-expression of abstract class type ‘NOX::NOXPlaya::Vector’
   newtonVector(rcp(new NOX::NOXPlaya::Vector(initcond, precision, ShapeCopy))),
                                                                            ^
/home/amir/Trilinos12.12/trilinos-12.12.1-Source/packages/Sundance/Playa/src/NOX_Playa_Group.cpp:74:78: error: invalid new-expression of abstract class type ‘NOX::NOXPlaya::Vector’
   gradientVector(rcp(new NOX::NOXPlaya::Vector(initcond, precision, ShapeCopy))),
                                                                              ^
/home/amir/Trilinos12.12/trilinos-12.12.1-Source/packages/Sundance/Playa/src/NOX_Playa_Group.cpp: In constructor ‘NOX::NOXPlaya::Group::Group(const Playa::NonlinearOperator<double>&, const Playa::LinearSolver<double>&)’:
/home/amir/Trilinos12.12/trilinos-12.12.1-Source/packages/Sundance/Playa/src/NOX_Playa_Group.cpp:88:88: error: invalid new-expression of abstract class type ‘NOX::NOXPlaya::Vector’
   xVector(rcp(new NOX::NOXPlaya::Vector(nonlinOp.getInitialGuess(), precision, DeepCopy))),
                                                                                        ^
/home/amir/Trilinos12.12/trilinos-12.12.1-Source/packages/Sundance/Playa/src/NOX_Playa_Group.cpp:89:89: error: invalid new-expression of abstract class type ‘NOX::NOXPlaya::Vector’
   fVector(rcp(new NOX::NOXPlaya::Vector(nonlinOp.getInitialGuess(), precision, ShapeCopy))),
                                                                                         ^
/home/amir/Trilinos12.12/trilinos-12.12.1-Source/packages/Sundance/Playa/src/NOX_Playa_Group.cpp:90:94: error: invalid new-expression of abstract class type ‘NOX::NOXPlaya::Vector’
   newtonVector(rcp(new NOX::NOXPlaya::Vector(nonlinOp.getInitialGuess(), precision, ShapeCopy))),
                                                                                              ^
/home/amir/Trilinos12.12/trilinos-12.12.1-Source/packages/Sundance/Playa/src/NOX_Playa_Group.cpp:91:96: error: invalid new-expression of abstract class type ‘NOX::NOXPlaya::Vector’
   gradientVector(rcp(new NOX::NOXPlaya::Vector(nonlinOp.getInitialGuess(), precision, ShapeCopy))),
                                                                                                ^
/home/amir/Trilinos12.12/trilinos-12.12.1-Source/packages/Sundance/Playa/src/NOX_Playa_Group.cpp: In constructor ‘NOX::NOXPlaya::Group::Group(const Playa::Vector<double>&, const Playa::NonlinearOperator<double>&, const Playa::LinearSolver<double>&, int)’:
/home/amir/Trilinos12.12/trilinos-12.12.1-Source/packages/Sundance/Playa/src/NOX_Playa_Group.cpp:107:70: error: invalid new-expression of abstract class type ‘NOX::NOXPlaya::Vector’
   xVector(rcp(new NOX::NOXPlaya::Vector(initcond, precision, DeepCopy))),
                                                                      ^
/home/amir/Trilinos12.12/trilinos-12.12.1-Source/packages/Sundance/Playa/src/NOX_Playa_Group.cpp:108:71: error: invalid new-expression of abstract class type ‘NOX::NOXPlaya::Vector’
   fVector(rcp(new NOX::NOXPlaya::Vector(initcond, precision, ShapeCopy))),
                                                                       ^
/home/amir/Trilinos12.12/trilinos-12.12.1-Source/packages/Sundance/Playa/src/NOX_Playa_Group.cpp:109:76: error: invalid new-expression of abstract class type ‘NOX::NOXPlaya::Vector’
   newtonVector(rcp(new NOX::NOXPlaya::Vector(initcond, precision, ShapeCopy))),
                                                                            ^
/home/amir/Trilinos12.12/trilinos-12.12.1-Source/packages/Sundance/Playa/src/NOX_Playa_Group.cpp:110:78: error: invalid new-expression of abstract class type ‘NOX::NOXPlaya::Vector’
   gradientVector(rcp(new NOX::NOXPlaya::Vector(initcond, precision, ShapeCopy))),
                                                                              ^
/home/amir/Trilinos12.12/trilinos-12.12.1-Source/packages/Sundance/Playa/src/NOX_Playa_Group.cpp: In constructor ‘NOX::NOXPlaya::Group::Group(const Playa::NonlinearOperator<double>&, const Playa::LinearSolver<double>&, int)’:
/home/amir/Trilinos12.12/trilinos-12.12.1-Source/packages/Sundance/Playa/src/NOX_Playa_Group.cpp:125:88: error: invalid new-expression of abstract class type ‘NOX::NOXPlaya::Vector’
   xVector(rcp(new NOX::NOXPlaya::Vector(nonlinOp.getInitialGuess(), precision, DeepCopy))),
                                                                                        ^
/home/amir/Trilinos12.12/trilinos-12.12.1-Source/packages/Sundance/Playa/src/NOX_Playa_Group.cpp:126:89: error: invalid new-expression of abstract class type ‘NOX::NOXPlaya::Vector’
   fVector(rcp(new NOX::NOXPlaya::Vector(nonlinOp.getInitialGuess(), precision, ShapeCopy))),
                                                                                         ^
/home/amir/Trilinos12.12/trilinos-12.12.1-Source/packages/Sundance/Playa/src/NOX_Playa_Group.cpp:127:94: error: invalid new-expression of abstract class type ‘NOX::NOXPlaya::Vector’
   newtonVector(rcp(new NOX::NOXPlaya::Vector(nonlinOp.getInitialGuess(), precision, ShapeCopy))),
                                                                                              ^
/home/amir/Trilinos12.12/trilinos-12.12.1-Source/packages/Sundance/Playa/src/NOX_Playa_Group.cpp:128:96: error: invalid new-expression of abstract class type ‘NOX::NOXPlaya::Vector’
   gradientVector(rcp(new NOX::NOXPlaya::Vector(nonlinOp.getInitialGuess(), precision, ShapeCopy))),
                                                                                                ^
/home/amir/Trilinos12.12/trilinos-12.12.1-Source/packages/Sundance/Playa/src/NOX_Playa_Group.cpp: In copy constructor ‘NOX::NOXPlaya::Group::Group(const NOX::NOXPlaya::Group&, NOX::CopyType)’:
/home/amir/Trilinos12.12/trilinos-12.12.1-Source/packages/Sundance/Playa/src/NOX_Playa_Group.cpp:141:75: error: invalid new-expression of abstract class type ‘NOX::NOXPlaya::Vector’
   xVector(rcp(new NOX::NOXPlaya::Vector(*(source.xVector), precision, type))),
                                                                           ^
/home/amir/Trilinos12.12/trilinos-12.12.1-Source/packages/Sundance/Playa/src/NOX_Playa_Group.cpp:142:75: error: invalid new-expression of abstract class type ‘NOX::NOXPlaya::Vector’
   fVector(rcp(new NOX::NOXPlaya::Vector(*(source.fVector), precision, type))),
                                                                           ^
/home/amir/Trilinos12.12/trilinos-12.12.1-Source/packages/Sundance/Playa/src/NOX_Playa_Group.cpp:143:85: error: invalid new-expression of abstract class type ‘NOX::NOXPlaya::Vector’
   newtonVector(rcp(new NOX::NOXPlaya::Vector(*(source.newtonVector), precision, type))),
                                                                                     ^
/home/amir/Trilinos12.12/trilinos-12.12.1-Source/packages/Sundance/Playa/src/NOX_Playa_Group.cpp:144:89: error: invalid new-expression of abstract class type ‘NOX::NOXPlaya::Vector’
   gradientVector(rcp(new NOX::NOXPlaya::Vector(*(source.gradientVector), precision, type))),
                                                                                         ^
/home/amir/Trilinos12.12/trilinos-12.12.1-Source/packages/Sundance/Playa/src/NOX_Playa_Group.cpp: In member function ‘virtual NOX::Abstract::Group::ReturnType NOX::NOXPlaya::Group::computeF()’:
/home/amir/Trilinos12.12/trilinos-12.12.1-Source/packages/Sundance/Playa/src/NOX_Playa_Group.cpp:290:45: error: cannot allocate an object of abstract type ‘NOX::NOXPlaya::Vector’
     *fVector = nonlinearOp.getFunctionValue();
                                             ^
packages/Sundance/Playa/src/CMakeFiles/sundancePlaya.dir/build.make:86: recipe for target 'packages/Sundance/Playa/src/CMakeFiles/sundancePlaya.dir/NOX_Playa_Group.cpp.o' failed
make[2]: *** [packages/Sundance/Playa/src/CMakeFiles/sundancePlaya.dir/NOX_Playa_Group.cpp.o] Error 1
CMakeFiles/Makefile2:19472: recipe for target 'packages/Sundance/Playa/src/CMakeFiles/sundancePlaya.dir/all' failed
make[1]: *** [packages/Sundance/Playa/src/CMakeFiles/sundancePlaya.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2

@trilinos/<teamName>

## Your Environment

- **Relevant repo SHA1s:**  
- **Relevant configure flags or configure script:**  
- **Operating system and version:**  
- **Compiler and TPL versions:**  

## Related Issues

* Blocks 
* Is blocked by 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of

**Comment by aishaque** [comment]
I believe Xyce does not require Sundance. In fact, I am able to run make using the sample scripts for serial and parallel build given on the Xyce guidance link in my original post. Therefore Xyce should work with that build. 

I wanted to explore the full Trilinos and hence attempted the complete build. This is my first effort to do "configure/build/install" type of installation on a Linux. Hopefully, someone can guide in getting this error sorted out.

**Comment by mhoemmen** [comment]
@aishaque If you're interested in helping out, would you mind trying the latest version of Trilinos (literally the master branch of Trilinos here on GitHub)?  We may have fixed this issue.  Trilinos hasn't had a minor release in about three years, if I remember right, despite active development.

**Comment by hkthorn** [comment]
@aishaque Please include the configure script that you are using that is generating this error, as well.

**Comment by aishaque** [comment]
@hkthorn I used the following script:

#!/bin/sh
SRCDIR=$HOME/Trilinos12.12/trilinos-12.12.1-Source
ARCHDIR=$HOME/XyceLibs/Serial
FLAGS="-O3 -fPIC"
cmake \
-G "Unix Makefiles" \
-DCMAKE_C_COMPILER=gcc \
-DCMAKE_CXX_COMPILER=g++ \
-DCMAKE_Fortran_COMPILER=gfortran \
-DCMAKE_CXX_FLAGS="$FLAGS" \
-DCMAKE_C_FLAGS="$FLAGS" \
-DCMAKE_Fortran_FLAGS="$FLAGS" \
-DCMAKE_INSTALL_PREFIX=$ARCHDIR \
-DCMAKE_MAKE_PROGRAM="make" \
-DTrilinos_ENABLE_ALL_PACKAGES=ON \
-DTPL_ENABLE_AMD=ON \
-DAMD_LIBRARY_DIRS="/usr/lib" \
-DTPL_AMD_INCLUDE_DIRS="/usr/include/suitesparse" \
-DTPL_ENABLE_BLAS=ON \
-DTPL_ENABLE_LAPACK=ON \
$SRCDIR
 
It is a slight modification of the script given at https://xyce.sandia.gov/documentation/BuildingGuide.html#ubuntuPreReq, where I have removed the individual "-DTrilinos_ENABLE ..." for packages and included a single "-DTrilinos_ENABLE_ALL_PACKAGES=ON \".

**Comment by aishaque** [comment]
@hkthorn I am able to build the Trilinos using the exact sample scripts (for Ubuntu) given at  https://xyce.sandia.gov/documentation/BuildingGuide.html#ubuntuPreReq. I have also built the serial and parallel versions of Xyce. Whereas serial Xyce passed all regression tests the parallel build failed 6 regression tests.

Certification_Tests/BUG_141_SON/bug_141-empty.....EXITED WITH ERROR[sh] (Time:  71s =  73.93cs +   0vs)

Certification_Tests/BUG_520/bug520................EXITED WITH ERROR[sh] (Time:   2s =   2.22cs +   0vs)

Certification_Tests/BUG_706_SON/rc_simple_lib.....EXITED WITH ERROR[sh] (Time:   2s =   2.39cs +   0vs)

SENS/ampSensAdj_aztec.............................EXITED WITH ERROR[sh] (Time:   2s =   2.08cs +   0vs)

SENS/ampSensAdj_belos.............................EXITED WITH ERROR[sh] (Time:   1s =   2.07cs +   0vs)

SENS/rc1000TranAdjGear............................EXITED WITH ERROR[sh] (Time:   2s =   1.47cs +   0vs)

I wonder if this has anything to do with Trilinos.

**Comment by aishaque** [comment]
@mhoemmen I have downloaded the Trilinos-master zip file. It has differences from Trilinos 12.12.1 I downloaded from www.trilinoss.org. Sundance package is not included in it and there are few more packages that are different between the two. 

The serial build of Trilinos master completed without any erros. I used the following shell script for configure:
#!/bin/sh
SRCDIR=$HOME/Downloads/Trilinos-master
ARCHDIR=$HOME/Trilinos-master/Serial
FLAGS="-O3 -fPIC"
cmake \
-G "Unix Makefiles" \
-DCMAKE_C_COMPILER=gcc \
-DCMAKE_CXX_COMPILER=g++ \
-DCMAKE_Fortran_COMPILER=gfortran \
-DCMAKE_CXX_FLAGS="$FLAGS" \
-DCMAKE_C_FLAGS="$FLAGS" \
-DCMAKE_Fortran_FLAGS="$FLAGS" \
-DCMAKE_INSTALL_PREFIX=$ARCHDIR \
-DCMAKE_MAKE_PROGRAM="make" \
 -DTrilinos_ENABLE_ALL_PACKAGES=ON \
-DAMD_LIBRARY_DIRS="/usr/lib" \
-DTPL_AMD_INCLUDE_DIRS="/usr/include/suitesparse" \
-DTPL_ENABLE_BLAS=ON \
-DTPL_ENABLE_LAPACK=ON \
$SRCDIR

The parallel build failed at around 92% of the build with following message track:

/usr/include/suitesparse/SuiteSparse_config.h:62:26: note: in definition of macro ‘SuiteSparse_long’
 #define SuiteSparse_long long
                          ^~~~
packages/muelu/adapters/CMakeFiles/muelu-adapters.dir/build.make:62: recipe for target 'packages/muelu/adapters/CMakeFiles/muelu-adapters.dir/epetra/MueLu_EpetraOperator.cpp.o' failed
make[2]: *** [packages/muelu/adapters/CMakeFiles/muelu-adapters.dir/epetra/MueLu_EpetraOperator.cpp.o] Error 1
CMakeFiles/Makefile2:19585: recipe for target 'packages/muelu/adapters/CMakeFiles/muelu-adapters.dir/all' failed
make[1]: *** [packages/muelu/adapters/CMakeFiles/muelu-adapters.dir/all] Error 2
Makefile:162: recipe for target 'all' failed

I used the following shell script for configure:
#!/bin/sh
SRCDIR=$HOME/Downloads/Trilinos-master
ARCHDIR=$HOME/Trilinos-master/Parallel
FLAGS="-O3 -fPIC"
cmake \
-G "Unix Makefiles" \
-DCMAKE_C_COMPILER=mpicc \
-DCMAKE_CXX_COMPILER=mpic++ \
-DCMAKE_Fortran_COMPILER=mpif77 \
-DCMAKE_CXX_FLAGS="$FLAGS" \
-DCMAKE_C_FLAGS="$FLAGS" \
-DCMAKE_Fortran_FLAGS="$FLAGS" \
-DCMAKE_INSTALL_PREFIX=$ARCHDIR \
-DCMAKE_MAKE_PROGRAM="make" \
 -DTrilinos_ENABLE_ALL_PACKAGES=ON \
-DTPL_ENABLE_AMD=ON \
-DAMD_LIBRARY_DIRS="/usr/lib" \
-DTPL_AMD_INCLUDE_DIRS="/usr/include/suitesparse" \
-DTPL_ENABLE_BLAS=ON \
-DTPL_ENABLE_LAPACK=ON \
-DTPL_ENABLE_MPI=ON \
$SRCDIR

Since the failure seems to be due to AMD enable part and suiteparse I am running another build without these options. Will post here whether it succeeds or fails.

**Comment by mhoemmen** [comment]
@aishaque wrote:
> It has differences from Trilinos 12.12.1 I downloaded from www.trilinos.org.

As I mentioned, it's been at least three years since the 12.12.1 release. 

I think you will need to update your SuiteSparse version.

**Comment by hkthorn** [comment]
@aishaque The Xyce test failures you mention above should be directed at the Xyce team.  Xyce uses Trilinos, but they are different development efforts.  I happen to be a developer on both teams.  So I know that you should look at the output in the individual test directories for these test failures (there is a Results directory that is made after running the regression suite and it contains all output including *.out files) that will tell you what is going on and why the simulator crashed.  If this doesn't clear up your questions for Xyce, please address your questions to xyce-users Google group.  That is our forum for answering and archiving questions/issues.

**Comment by aishaque** [comment]
@mhoemmen Parallel build without SuiteSparse succeeds. I will update the SuiteSparse on my system to build with it. 
Thanks.

**Comment by aishaque** [comment]
I guess we can close this issue.
