### ISSUE TITLE
Xpetra: Don't create new Belos::{MultiVec,Operator}Traits specializations; just use Belos::{MultiVec, Operator}

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#3415]
@trilinos/muelu @trilinos/xpetra @trilinos/belos @lucbv 

Xpetra creates specializations of Belos::MultiVecTraits and Belos::OperatorTraits for Xpetra types, in order for MueLu to use Belos.  This instantiates Belos all over again for all possible template parameter combinations that Xpetra instantiates.  Xpetra could instead implement subclasses of `Belos::MultiVec<Scalar>` and `Belos::Operator<Scalar>`, and use the existing instantiations of Belos for those types.

## Motivation and Context

Goal: Only build Belos once per Scalar type.

**Comment by lucbv** [comment]
@mhoemmen is the `SolverFactorySelector` in `BelosSolverFactory_Xpetra.hpp` templated on `::Xpetra::MultiVector<SC, LO, GO, NT>` and not on the `MultiVecTraits<Scalar, Xpetra::MultiVector<Scalar,LO,GO,Node> >`?

I am trying to implement something I call `XpetraMultiVectorWrapper` but I can't really tell how Belos will access it?

**Comment by mhoemmen** [comment]
@lucbv Check out `/Trilinos/packages/belos/test/MVOPTester/` for an example.  You shouldn't have to mess with SolverFactorySelector; Belos should already define that stuff for `Belos::MultiVec<Scalar>` and `Belos::Operator<Scalar>`.

**Comment by mhoemmen** [comment]
@trilinos/muelu
