### ISSUE TITLE
Test failures in ATDM config gnu debug builds on Power8/9 machines 

### ISSUE THREAD

**Issue by fryeguy52** [trilinos/Trilinos#3417]
CC: @trilinos/tpetra, @trilinos/belos ,
@srajama1  (Trilinos Linear Solvers Product Lead)
@kddevin (Trilinos Data Services Product Lead)
@bartlettroscoe 
 
## Next Action Status

PR #3420 merged on 9/10/2018 fixed all but one test on the `gnu-debug-openmp` builds on 'white'/'ride' on 9/11/2018 (the test `TpetraCore_gemm_MPI_1` is timing out).  Next: Make the test `TpetraCore_gemm_MPI_1` run faster in that build or disable it?

## Description
As shown in [this query(white/ride)](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&date=2018-09-04&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-white-ride-gnu-debug-openmp&field2=status&compare2=62&value2=Passed&field3=buildstarttime&compare3=83&value3=2018-09-10)  and [this query(waterman)](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&date=2018-09-04&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-waterman-gnu-debug-openmp&field2=status&compare2=62&value2=Passed&field3=buildstarttime&compare3=83&value3=2018-09-10) the tests:

- Anasazi_Tpetra_BlockDavidson_Lap_test_MPI_4
- Anasazi_Tpetra_BlockKrylovSchur_Lap_test_MPI_4
- Anasazi_Tpetra_IRTR_Lap_test_MPI_4
- Anasazi_Tpetra_MVOPTester_MPI_4
- Anasazi_Tpetra_TraceMin_largest_standard_test_MPI_4
- Anasazi_Tpetra_TraceMin_smallest_proj_test_MPI_4
- Anasazi_Tpetra_TraceMin_smallest_schur_test_MPI_4
- Anasazi_Tpetra_TraceMinDavidson_largest_standard_test_MPI_4
- Belos_Issue_3235_MPI_2
- Belos_SolverFactory_MPI_4
- Belos_Tpetra_BlockGMRES_hb_test_MPI_4
- Belos_Tpetra_MultipleSolves_MPI_4
- Belos_Tpetra_MVOPTester_complex_test_MPI_4
- Ifpack2_AdditiveSchwarz_RILUK_MPI_4
- Ifpack2_Cheby_belos_MPI_1
- Ifpack2_GS_belos_MPI_1
- Ifpack2_ILUT_5w_2_MPI_1
- Ifpack2_ILUT_5w_no_diag_MPI_1
- Ifpack2_ILUT_belos_MPI_1
- Ifpack2_ILUT_hb_belos_MPI_2
- Ifpack2_ILUT_hb_belos_MPI_4
- Ifpack2_Jac_sm_belos_MPI_1
- Ifpack2_Jacobi_belos_constGraph_MPI_4
- Ifpack2_Jacobi_belos_MPI_1
- Ifpack2_Jacobi_hb_belos_MPI_1
- Ifpack2_Jacobi_hb_belos_MPI_2
- Ifpack2_RILUK_hb_belos_MPI_2
- Ifpack2_RILUK_hb_belos_MPI_4
- Ifpack2_SGS_belos_MPI_1
- Ifpack2_small_gmres_belos_MPI_1
- MueLu_Maxwell3D-Tpetra-Stratimikos_MPI_4
- MueLu_Stratimikos_MPI_4
- MueLu_Stratimikos2_MPI_4
- NOX_Tpetra_1DFEM_MPI_4
- NOX_Tpetra_Heq_MPI_4
- NOX_Tpetra_MultiVectorOpsTests_MPI_4
- PanzerAdaptersSTK_CurlLaplacianExample
- PanzerAdaptersSTK_main_driver_energy-ss
- PanzerAdaptersSTK_main_driver_energy-ss-blocked-tp
- PanzerAdaptersSTK_MixedPoissonExample
- PanzerAdaptersSTK_projection_MPI_2
- PanzerMiniEM_MiniEM-BlockPrec_Augmentation_MPI_1
- PanzerMiniEM_MiniEM-BlockPrec_Augmentation_MPI_4
- PanzerMiniEM_MiniEM-BlockPrec_RefMaxwell_MPI_1
- PanzerMiniEM_MiniEM-BlockPrec_RefMaxwell_MPI_4
- Teko_DiagonallyScaledPreconditioner_MPI_1
- Teko_testdriver_tpetra_MPI_1
- Teko_testdriver_tpetra_MPI_2
- ThyraTpetraAdapters_TpetraThyraWrappersUnitTests_MPI_4
- ThyraTpetraAdapters_TpetraThyraWrappersUnitTests_serial_MPI_1
- TpetraCore_gemm_MPI_1
- TpetraCore_MultiVector_UnitTests_MPI_4

are failing in the builds:
* Trilinos-atdm-waterman-gnu-debug-openmp
* Trilinos-atdm-white-ride-gnu-debug-openmp (on both white and ride)

many of the tests have the following output in common
```
** On entry to DGEMM parameter number  8 had an illegal value
 ** On entry to DGEMM parameter number  8 had an illegal value
 ** On entry to DGEMM parameter number  8 had an illegal value
 ** On entry to DGEMM parameter number  8 had an illegal value
--------------------------------------------------------------------------
mpiexec has exited due to process rank 0 with PID 0 on
node waterman2 exiting improperly. There are three reasons this could occur:

1. this process did not call "init" before exiting, but others in
the job did. This can cause a job to hang indefinitely while it waits
for all processes to call "init". By rule, if one process calls "init",
then ALL processes must call "init" prior to termination.

2. this process called "init", but exited without calling "finalize".
By rule, all processes that call "init" MUST call "finalize" prior to
exiting or it will be considered an "abnormal termination"

3. this process called "MPI_Abort" or "orte_abort" and the mca parameter
orte_create_session_dirs is set to false. In this case, the run-time cannot
detect that the abort call was an abnormal termination. Hence, the only
error message you will receive is this one.

This may have caused other processes in the application to be
terminated by signals sent by mpiexec (as reported here).

You can avoid this message by specifying -quiet on the mpiexec command line.
--------------------------------------------------------------------------
```
## Steps to Reproduce (white/ride)

One should be able to reproduce this failure on the machine ride/white as described in:
* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md
More specifically, the commands given for the system ride/white are provided at:
* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#ridewhite
The exact commands to reproduce this issue should be:
```
$ cd <some_build_dir>/

$ source $TRILINOS_DIR/cmake/std/atdm/load-env.sh gnu-debug-openmp

$ cmake \
  -GNinja \
  -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
  -DTrilinos_ENABLE_TESTS=ON \
  -DTrilinos_ENABLE_<PACKAGE_NAME>=ON \
  $TRILINOS_DIR

$ make NP=16

$ bsub -x -Is -q rhel7F -n 16 ctest -j16
```

(where `<PACKAGE_NAME>` is some package you want to build and run tests for.)

## Steps to Reproduce (waterman)

One should be able to reproduce this failure on the machine waterman as described in:
* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md
More specifically, the commands given for the system waterman are provided at:
* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#waterman
The exact commands to reproduce this issue should be:
```
$ cd <some_build_dir>/

$ source $TRILINOS_DIR/cmake/std/atdm/load-env.sh gnu-debug-openmp

$ cmake \
  -GNinja \
  -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
  -DTrilinos_ENABLE_TESTS=ON \
  -DTrilinos_ENABLE_<PACKAGE_NAME>=ON \
  $TRILINOS_DIR

$ make NP=20

$ bsub -x -Is -n 20 ctest -j20
```

(where `<PACKAGE_NAME>` is some package you want to build and run tests for.)

**Comment by kddevin** [comment]
@kyungjoo-kim  The two Tpetra tests that are failing are the same two that @tjfulle and I saw failing on macs.  Can you take a look at them?  Perhaps resolving the Tpetra issues will resolve the failures in the other packages.  Thank you!

**Comment by bartlettroscoe** [comment]
@fryeguy52, can you please put in the link to the posted Updates.txt file that shows which Tpetra commits likely caused this?   We looked at this on Friday and it was pretty clear which commits likely caused these failures.

**Comment by kyungjoo-kim** [comment]
@kddevin i am looking at this....

**Comment by kyungjoo-kim** [comment]
@fryeguy52 Using your ATDM script, I got the following error from white
```
CMake Error at cmake/tribits/core/package_arch/TribitsGlobalMacros.cmake:1815 (ENABLE_LANGUAGE):
  The CMAKE_C_COMPILER:

    mpicc is /home/projects/ppc64le-pwr8-nvidia/openmpi/2.1.2/gcc/7.2.0/cuda/9.0.176/bin/mpicc

  is not a full path and was not found in the PATH.

  Tell CMake where to find the compiler by setting either the environment
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.

# I typped the following and it does not find out gcc
[kyukim @white11] i3417 > /home/projects/ppc64le-pwr8-nvidia/openmpi/2.1.2/gcc/7.2.0/cuda/9.0.176/bin/mpicc
gcc: error: is: No such file or directory
gcc: error: /home/projects/ppc64le/gcc/7.2.0/bin/gcc

```

**Comment by bartlettroscoe** [comment]
> Using your ATDM script, I got the following error from white

@kyungjoo-kim, are you using bash or some other shell?  If not, you need to be.  Otherwise, if you are running bash, can you please copy and paste the commands in a comment here that you type from the initial login to 'white'?

**Comment by bartlettroscoe** [comment]
@kyungjoo-kim, note that these failures started on 9/7/2018 with the updated commits pulled shown [here](https://testing-vm.sandia.gov/cdash/viewNotes.php?buildid=3913090#!#note6).  Looking over that set of commits it seems very likely that one of the following commits has caused these failures:

```
217c7d1:  KokkosKernels - direct push commits from the KokkosKernels repo.
Author: Kyungjoo Kim (-EXP) <kyukim@bread.sandia.gov>
Date:   Mon Aug 27 13:05:10 2018 -0600

M	packages/kokkos-kernels/CMakeLists.txt
M	packages/kokkos-kernels/Makefile.kokkos-kernels
M	packages/kokkos-kernels/cmake/Dependencies.cmake
M	packages/kokkos-kernels/cmake/KokkosKernels_config.h.in
M	packages/kokkos-kernels/src/blas/KokkosBlas.hpp
M	packages/kokkos-kernels/unit_test/CMakeLists.txt

...

8a4691d:  Tpetra - revert blas test comparing kokkos blas against teuchos blas
Author: Kyungjoo Kim <kyukim@sandia.gov>
Date:   Fri Aug 10 12:23:54 2018 -0600

M	packages/tpetra/core/test/Blas/gemm.cpp
M	packages/tpetra/core/test/Blas/gemv.cpp
M	packages/tpetra/core/test/CMakeLists.txt

5d09845:  Revert "Tpetra - delete blas test"
Author: Kyungjoo Kim <kyukim@sandia.gov>
Date:   Fri Aug 10 10:53:48 2018 -0600

A	packages/tpetra/core/test/Blas/CMakeLists.txt
A	packages/tpetra/core/test/Blas/gemm.cpp
A	packages/tpetra/core/test/Blas/gemv.cpp
M	packages/tpetra/core/test/CMakeLists.txt

...

e31b635:  Tpetra - delete blas test
Author: Kyungjoo Kim <kyukim@sandia.gov>
Date:   Thu Aug 9 09:51:41 2018 -0600

D	packages/tpetra/core/test/Blas/CMakeLists.txt
D	packages/tpetra/core/test/Blas/gemm.cpp
D	packages/tpetra/core/test/Blas/gemv.cpp
M	packages/tpetra/core/test/CMakeLists.txt

...

d3c5d44:  Tpetra - remove tpetra detail blas functions and disable their testing
Author: Kyungjoo Kim <kyukim@sandia.gov>
Date:   Thu Aug 2 12:43:09 2018 -0600

D	packages/tpetra/core/src/Tpetra_Details_cublasGemm.cpp
D	packages/tpetra/core/src/Tpetra_Details_cublasGemm.hpp
D	packages/tpetra/core/src/Tpetra_Details_cublasGemv.cpp
D	packages/tpetra/core/src/Tpetra_Details_cublasGemv.hpp
D	packages/tpetra/core/src/Tpetra_Details_defaultGemm.hpp
D	packages/tpetra/core/src/Tpetra_Details_defaultGemv.hpp
D	packages/tpetra/core/src/Tpetra_Details_gemm.hpp
D	packages/tpetra/core/src/Tpetra_Details_gemv.hpp
D	packages/tpetra/core/src/Tpetra_Details_libGemm.cpp
D	packages/tpetra/core/src/Tpetra_Details_libGemm.hpp
D	packages/tpetra/core/src/Tpetra_Details_libGemv.cpp
D	packages/tpetra/core/src/Tpetra_Details_libGemv.hpp
D	packages/tpetra/core/src/Tpetra_Details_mklGemm.cpp
D	packages/tpetra/core/src/Tpetra_Details_mklGemm.hpp
D	packages/tpetra/core/src/Tpetra_Details_mklGemv.cpp
D	packages/tpetra/core/src/Tpetra_Details_mklGemv.hpp
M	packages/tpetra/core/src/Tpetra_MultiVector_def.hpp
D	packages/tpetra/core/src/kokkos_refactor/Kokkos_MV_GEMM.hpp
M	packages/tpetra/core/test/CMakeLists.txt
```

The failure of the tests `TpetraCore_gemm_MPI_1` and `TpetraCore_MultiVector_UnitTests_MPI_4` together with these changes seem like the probable cause.

**Comment by kyungjoo-kim** [comment]
@bartlettroscoe One question is why the 10 days PR test does not filter this problem ?

**Comment by kyungjoo-kim** [comment]
I am using bash. 
```
*********************************************************************
A short introduction is available at /opt/WHITE_INTRO

Reminder:

        Export Controlled Information is NOT allowed on this system.

*********************************************************************
[kyukim @white11] > cd i3417/
[kyukim @white11] i3417 > ls
CMakeCache.txt  CMakeFiles  TrilinosRepoVersion.txt
[kyukim @white11] i3417 > pwd
/home/kyukim/Work/lib/trilinos/build/white/i3417
[kyukim @white11] i3417 > export TRILINOS_DIR=/home/kyukim/Work/lib/trilinos/master
[kyukim @white11] i3417 > source $TRILINOS_DIR/cmake/std/atdm/load-env.sh gnu-debug-openmp
Hostname 'white11' matches known ATDM host 'white' and system 'ride'
ATDM_CONFIG_TRILNOS_DIR = /home/kyukim/Work/lib/trilinos/master
Setting default compiler and build options for JOB_NAME='gnu-debug-openmp'
No KOKKOS_ARCH specified so using system default
Using white/ride compiler stack GNU to build DEBUG code with Kokkos node type OPENMP and KOKKOS_ARCH=Power8
[kyukim @white11] i3417 > cmake \
>   -GNinja \
>   -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
>   -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_Panzer=ON \
>   $TRILINOS_DIR
```
This is what I typed on white. Any clue why I encounter the configure error ?

**Comment by bartlettroscoe** [comment]
@kyungjoo-kim asked:

> One question is why the 10 days PR test does not filter this problem ?

These failures are only seen on the GNU Debug OpenMP builds on the Power machines.  The PR builds do not have any Power machines.  There is no plan as of now to add Power8 or Power9 gnu-debug-openmp builds at this time.

**Comment by bartlettroscoe** [comment]
@kyungjoo-kim, I just followed the instructions on 'white' and reproduced the Tpetra tests with:

```
$ ssh white

$ cd ~/Trilinos.base/Trilinos/

$ git checkout develop

$ git pull

$ cd ~/Trilinos.base/BUILD/WHITE/GNU/GNU_DEBUG_OPENMP/

$ source ~/Trilinos.base/Trilinos/cmake/std/atdm/load-env.sh gnu-debug-openmp
Hostname 'white11' matches known ATDM host 'white' and system 'ride'
ATDM_CONFIG_TRILNOS_DIR = /home/rabartl/Trilinos.base/Trilinos
Setting default compiler and build options for JOB_NAME='gnu-debug-openmp'
No KOKKOS_ARCH specified so using system default
Using white/ride compiler stack GNU to build DEBUG code with Kokkos node type OPENMP and KOKKOS_ARCH=Power8

$ cmake \
  -GNinja \
  -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
  -DTrilinos_ENABLE_TESTS=ON \
  -DTrilinos_ENABLE_Tpetra=ON \
  ~/Trilinos.base/Trilinos

$ make NP=16

$ bsub -x -Is -q rhel7F -n 16 ctest -j16
```

which returned:

```
99% tests passed, 2 tests failed out of 171

Subproject Time Summary:
Tpetra    = 368.18 sec*proc (171 tests)

Total Test time (real) =  79.74 sec

The following tests FAILED:
	  6 - TpetraCore_gemm_MPI_1 (Failed)
	129 - TpetraCore_MultiVector_UnitTests_MPI_4 (Failed)
Errors while running CTest
```

Let's figure out why you get a different result.

**Comment by kyungjoo-kim** [comment]
The error message said that LDA or LDB is not correctly interfaced and we know that this passed on x86 architectures. This might be happend due to data layouts. @crtrott @vqd8a this error should be caught in kokkos-kernels error checking and asserts.

**Comment by kyungjoo-kim** [comment]
@bartlettroscoe let me know when you are avail. I don't think that I can configure trilinos with atdm script myself.

**Comment by bartlettroscoe** [comment]
@kyungjoo-kim said:

> @bartlettroscoe let me know when you are avail. I don't think that I can configure trilinos with atdm script myself.

I send you an email offline so hopefully you and @fryeguy52 can get together in person to this out.

**Comment by kyungjoo-kim** [comment]
@kddevin @crtrott @bartlettroscoe @fryeguy52 

I compiled and reproduced the error. After putting some print statements in KokkosKernels blas wrapper, I found very werid behaviors. The following code snippet is from 

https://github.com/kokkos/kokkos-kernels/blob/9a9845e14234eb8f8edb7c1331c9a228eb24048d/src/impl/tpls/KokkosBlas3_gemm_tpl_spec_decl.hpp#L126

Here is my printing code. 
```
    A.stride(strides); printf(" lr %d a strides %d %d\n", A_is_lr, strides[0], strides[1]); \                                                        
    const int LDA = strides[A_is_lr?0:1]; printf("LDA %d\n", LDA);       \                                                                           
    B.stride(strides); printf(" lr %d b strides %d %d\n", B_is_lr, strides[0], strides[1]); \                                                        
    const int LDB = strides[B_is_lr?0:1];                                \                                                                           
    C.stride(strides); printf(" lr %d c strides %d %d\n", C_is_lr, strides[0], strides[1]); \                                                        
    const int LDC = strides[C_is_lr?0:1];                                \                                                                           
    \                                                                                                                                                
    if(!A_is_lr && !B_is_lr && !C_is_lr ) {                             \                                                                            
      printf("not lr\n");                                               \                                                                            
      printf("A %d %d, B %d %d, C %d %d\n", A.extent(0), A.extent(1), B.extent(0), B.extent(1), C.extent(0), C.extent(1));\                          
      printf("trans %c %c, mnk %d %d %d, ld %d %d %d\n", transA[0], transB[0], M, N, K, LDA, LDB, LDC); \                                            
      dgemm_(transA,transB,&M,&N,&K,&alpha,A.data(),&LDA,B.data(),&LDB,&beta,C.data(),&LDC); \                                                       
    } 

# this is what I got 
 lr 0 a strides 1 2
LDA 2
 lr 0 b strides 1 2
 lr 0 c strides 1 1
not lr
A 2 1, B 2 1, C 1 1
trans T N, mnk 1 1 2, ld 1 2 1
 ** On entry to DGEMM parameter number  8 had an illegal value
```
Somehow LDA is changed from 2 (right value) to 1. LDA is declared as ``const int``. The value once is defined and should not be changed. I first doubt about power 8 architecture and want to blame it. But this kind of error is also revealed from mac according to @tjfulle . This might be attributed to something else. 

At this moment, I cannot "formally" fix this problem as there is no problem in the code but I will try some possible work around to avoid this.

**Comment by kyungjoo-kim** [comment]
PR is submitted and let's wait for the nightly test. @fryeguy52 As PR test cannot filter this issue, if you don't mind, could you cross-validate the PR on the ride and waterman ?

**Comment by kyungjoo-kim** [comment]
@kddevin As you already reproduce this error, could you also verify the PR #3420 fixes this issue ?

**Comment by mhoemmen** [comment]
LDA should be nonzero even if the number of rows is zero, I think.

**Comment by bartlettroscoe** [comment]
Following up from @kyungjoo-kim's commits in https://github.com/trilinos/Trilinos/pull/3420#issuecomment-420073627 ...

Some bits of data to consider:

1) Yes, the KokkosKernals tests are run and they pass on this `gnu-debug-openmp` build on 'white' as shown [here](https://testing-vm.sandia.gov/cdash/index.php?project=Trilinos&parentid=3919883).

2) The Tpetra tests also fail on Power9 'waterman' as shown [here](https://testing-vm.sandia.gov/cdash/index.php?project=Trilinos&parentid=3918291).  (Note the timing-out test `KokkosKernels_sparse_openmp_MPI_1` is not even run on 'white'/'ride' due to #168.  Therefore, these tests may actually be failing but we can't tell due to the timeout)

3) We don't see any of these failures in the `gnu-opt-openmp` builds on 'white' [here](https://testing-vm.sandia.gov/cdash/index.php?project=Trilinos&parentid=3919158) or 'waterman' [here](https://testing-vm.sandia.gov/cdash/index.php?project=Trilinos&parentid=3918749).  Why would this be?

**Comment by kyungjoo-kim** [comment]
@bartlettroscoe Thanks for checking other builds. 

1. @crtrott ``Note: Google Test filter = -openmp.gemm_double`` kokkoskernels test filter out gemm test. I don't know why but this should be enabled. 

2.  I asked @kddevin if the PR fixes the problem. (168 should be a mistake as it is an intrepid2 feature request issue).

3. this part is very interesting. opt build is okay but debug build fails. ummmmmm, @nmhamster can we look at this problem why debug build causes a compiler bug ?

**Comment by bartlettroscoe** [comment]
> `Note: Google Test filter = -openmp.gemm` double kokkoskernels test filter out gemm test. I don't know why but this should be enabled.

I think this got disabled for debug builds.  A simple `git -Sopenmp.gemm' should show who added that disable and why.

**Comment by bartlettroscoe** [comment]
Okay, so the merge of PR #3420 fixed almost all of the failing tests in the `gnu-debug-openmp` builds on 'white'/'ride' and 'waterman' shown [here](https://testing-vm.sandia.gov/cdash/index.php?project=Trilinos&parentid=3926078), [here](https://testing-vm.sandia.gov/cdash/index.php?project=Trilinos&parentid=3924977), and [here](https://testing-vm.sandia.gov/cdash/index.php?project=Trilinos&parentid=3924263), respectively.

The only remaining non-passing test on 'white'/'ride' is the timeout of the test `TpetraCore_gemm_MPI_1` shown [here](https://testing-vm.sandia.gov/cdash/testDetails.php?test=54242400&build=3926100) (which also times out on 'waterman' as shown [here](https://testing-vm.sandia.gov/cdash/testDetails.php?test=54216967&build=3924285)).  We are just really struggling with these full `-O0 -g` debug builds.  Can we make this test run faster in a full debug build or should we just disable it for this build?  We can't just let it timeout.

**Comment by kddevin** [comment]
I think that test exercises many different cases.  Maybe we can break the test into two or three tests; I'll ask someone to take a look.  What is the timeout limit?

**Comment by bartlettroscoe** [comment]
@kddevin said:

> I think that test exercises many different cases. Maybe we can break the test into two or three tests; I'll ask someone to take a look.  What is the timeout limit?

The current test timeout is 10 minutes.  Breaking a longer test into multiple tests is just fine.   That was done to resolve #3256 for example.

This might seem like a silly thing to do but it has a good technical justification.  No matter how may cores you throw at testing, you can never make the wall-clock time for testing take any less than your longest-running test.  For example, if we increased the timeout of this test to 30 minutes and it takes 25 minutes to pass on average, then we can never finish testing in less than 25 minutes, no matter how many cores we throw at it.  And many cores will sit idle while we wait for these few long-running (single MPI-process) tests to finish.  Therefore, if we keep the timeout at 10 minutes, then we can always get testing done in about 10 minutes if throw enough cores at it.

If the tests for any individual package start taking a much larger percentage of the total processor time, then we can try to make things cheaper.  You can see processor time in the "Proc Time" column in "Advanced View", for example, [here](https://testing-vm.sandia.gov/cdash-dev-view/index.php?project=Trilinos&parentid=3926078) which shows which packages are the processor hogs.  If you sort by "Proc Time" it may surprise you what packages are at the top.

**Comment by kyungjoo-kim** [comment]
In the gemm test, it tests all combinations of alpha beta (C = beta C + alpha A B) for all problem sizes, alpha/beta = {zero, one, -one, two, -two} and this generates 25 cases per problem.

We need to cover all trans cases and some non trivial problem sizes but probably we don't need to test all alpha and beta combinations for all problem sizes.

**Comment by kddevin** [comment]
Actually, this timeout problem may go away once  #3420 is included in the testing.

I ran on white just now and saw 
"TpetraCore_gemm_MPI_1" time elapsed: 00:07:00
and
100% tests passed, 0 tests failed out of 171
Subproject Time Summary:
Tpetra    = 783.41 sec*proc (171 tests)
Total Test time (real) = 420.47 sec

Fingers crossed.

**Comment by kddevin** [comment]
Hmmm, it isn't clear to me why the test would take twice as long through the automated ATDM system than when it is run "by hand" using the same environment script, configure script, and bsub instructions.  It would be great to understand what makes my environment faster, so that overall test times would be reduced.
Are all processors in the rhel7F queue the same?

**Comment by bartlettroscoe** [comment]
@kddevin, unfortunately, we do see machines where running multiple tests at the same time slows down the tests due to not spreading out over the available cores correctly and other possible issues.   See the discussion in #3256.  We are going to try to get to the bottom of this in FY19 as described in #2422.

**Comment by fryeguy52** [comment]
In today's builds on [white](https://testing-vm.sandia.gov/cdash/viewTest.php?buildid=3933261), [ride](https://testing-vm.sandia.gov/cdash/viewTest.php?buildid=3932425), and [waterman](https://testing-vm.sandia.gov/cdash/viewTest.php?buildid=3931962) the test `TpetraCore_gemm_MPI_1` has disappeared and been replaced by 4 faster running tests.  All of which pass.
```
TpetraCore_gemm_m_eq_13_MPI_1
TpetraCore_gemm_m_eq_2_MPI_1
TpetraCore_gemm_m_eq_1_MPI_1
TpetraCore_gemm_m_eq_5_MPI_1
```
This fixes the last test in this issue.

thanks @kddevin!

**Comment by bartlettroscoe** [comment]
FYI: As shown in [this CDash query](https://testing-vm.sandia.gov/cdash/viewTest.php?buildid=3933261&filtercount=1&showfilters=1&field1=testname&compare1=63&value1=gemm) the sum of the wallclock time for the 4 new tests in the build `Trilinos-atdm-white-ride-gnu-debug-openmp` adds up to almost 13 minutes.  But the longest one is 4m35s so that is very reasonable.   And note that as shown in [this CDash query](https://testing-vm.sandia.gov/cdash/index.php?project=Trilinos&parentid=3933239) the total "Proc Time" for Tpetra for this build is 24m43s.  This makes it 4th highest so not the biggest concern for test times.  The cost of the Kokkos, KokkosKernels, and Panzer test suites are all higher (and Panzer is 52m28s).
