### ISSUE TITLE
Build fails: Swig source step of building PyTrilinos fails with execvp: /bin/sh: Argument list too long

### ISSUE THREAD

**Issue by casparvl** [trilinos/Trilinos#3430]
@trilinos/pytrilinos 

## Current Behavior

I am trying to build Trilinos 12.10.1 with python support. I ran into this issue (https://github.com/trilinos/Trilinos/issues/2434) where the build fails with an error 'execvp: /bin/sh: Argument list too long'. I fixed that by setting the suggested

```
CMAKE_CXX_USE_RESPONSE_FILE_FOR_OBJECTS=ON
CMAKE_CXX_USE_RESPONSE_FILE_FOR_INCLUDES=ON
CMAKE_CXX_USE_RESPONSE_FILE_FOR_LIBRARIES=ON
```
Which works well for the compilation part. However, the 'Swig source' step triggers the same error message, and clearly, doesn't respect these CMake flags.

`[ 94%] Swig source /scratch/shared/jenkins/test/build/Trilinos/12.10.1/foss-2017b-Python-2.7.14/trilinos-12.10.1-Source/packages/PyTrilinos/src/LOCA.Epetra.Interface.i
cd /scratch/shared/jenkins/test/build/Trilinos/12.10.1/foss-2017b-Python-2.7.14/trilinos-12.10.1-Source/BUILD/packages/PyTrilinos/src && /hpc/eb/RedHatEnterpriseServer7/SWIG/3.0.12-foss-2017b-Python-2.7.14/bin/swig -python -I/scratch/sha
red/jenkins/test/build/Trilinos/12.10.1/foss-2017b-Python-2.7.14/trilinos-12.10.1-Source/BUILD/packages/PyTrilinos/doc/Doxygen -noproxydel -outdir PyTrilinos/LOCA/Epetra -c++ -I/scratch/shared/jenkins/test/build/Trilinos/12.10.1/foss-201
7b-Python-2.7.14/trilinos-12.10.1-Source/BUILD -I/scratch/shared/jenkins/test/build/Trilinos/12.10.1/foss-2017b-Python-2.7.14/trilinos-12.10.1-Source/BUILD/packages/PyTrilinos/src`
[[[cut out a few hundred lines here]]]
`-I/scratch/shared/jenkins/test/build/Trilinos/12.10.1/foss-2017b-Python-2.7.14/trilinos-12.10.1-Source/BUILD
/packages/teuchos/remainder/src -I/scratch/shared/jenkins/test/build/Trilinos/12.10.1/foss-2017b-Python-2.7.14/trilinos-12.10.1-Source/packages/teuchos/numerics/src -o /scratch/shared/jenkins/test/build/Trilinos/12.10.1/foss-2017b-Python
-2.7.14/trilinos-12.10.1-Source/BUILD/packages/PyTrilinos/src/LOCA.Epetra.InterfacePYTHON_wrap.cpp /scratch/shared/jenkins/test/build/Trilinos/12.10.1/foss-2017b-Python-2.7.14/trilinos-12.10.1-Source/packages/PyTrilinos/src/LOCA.Epetra.I
nterface.i
make[2]: execvp: /bin/sh: Argument list too long
make[2]: *** [packages/PyTrilinos/src/LOCA.Epetra.InterfacePYTHON_wrap.cpp] Error 127
make[2]: Leaving directory `/scratch/shared/jenkins/test/build/Trilinos/12.10.1/foss-2017b-Python-2.7.14/trilinos-12.10.1-Source/BUILD'
make[1]: *** [packages/PyTrilinos/src/CMakeFiles/PyTrilinos_LOCA_Epetra_Interface.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[2]: Leaving directory `/scratch/shared/jenkins/test/build/Trilinos/12.10.1/foss-2017b-Python-2.7.14/trilinos-12.10.1-Source/BUILD'`

## Possible Solution

Other then shortening the prefix on my end (which is tricky because I use EasyBuild as a build system, which produces somewhat long prefixes), is there anything that could be done on your end to fix this issue?

I can imagine even a shorter prefix is just a temporary relief, as future versions may trigger even _more_ includes. Thus, I think a more permanent solution for these excessively long command lines may be needed on your end anyway.

## Steps to Reproduce

To reproduce: pick a long enough prefix (and possibly build enough of Trilinos' components to get a long link line).

## Related Issues

* Follows up on (somewhat) related issue https://github.com/trilinos/Trilinos/issues/2434

**Comment by boegel** [comment]
@mhoemmen I tried using 12.12.1, but the download seems to be broken (see https://github.com/trilinos/Trilinos/issues/3447).

Is there a reason why a newer version isn't being tagged/releases? Is everyone supposed to just use current `master` without having a proper version assigned to it? :(

**Comment by srajama1** [comment]
@trilinos/framework

**Comment by casparvl** [comment]
@mhoemmen Thanks for the suggestion. I have to agree with @boegel here. I manage software on an HPC system, and can't offer anything that's unversioned to my users. Happy to hear you share his feelings on the importance of the need for releases, consider this message als my support for that as well.

I don't have much more time to invest in this right now, but when I pick it up in the future I hope that either @boegel's change to the EasyBlock have made the build path for Trilinos shorter, or will still try to use a shorter prefix myself. Would be great if the framework would find a more 'permanent' solution for this though...

**Comment by mhoemmen** [comment]
@casparvl Framework did a code freeze for a new minor release (12.14) this week.  I'm hopeful that you should see a new version soon.  In fact, there appears to be a tag for this release already:

https://github.com/trilinos/Trilinos/tree/trilinos-release-12-14-branch

though I don't think it's official yet.

**Comment by casparvl** [comment]
That's good news! I'll keep an eye out for an official release :)

**Comment by mhoemmen** [comment]
We can add patches to fix release issues, so if you try that branch and find any issues, please let us know!

**Comment by quentin-ag** [comment]
Has a solution, or even a workaround, been found for this issue? I am facing it now, roughly at the same stage as reported by casparvi:
```shell
make[2]: /bin/sh: Argument list too long
make[2]: *** [packages/PyTrilinos/src/CMakeFiles/PyTrilinos_LOCA_Abstract.dir/build.make:81: packages/PyTrilinos/src/LOCA.AbstractPYTHON_wrap.cpp] Error 127
make[2]: Leaving directory '/home/.../pikaur/build/trilinos/src/Trilinos-trilinos-release-13-0-1/build'
```
Enabling response files did not affect this swig issue, as expected. I also tried
```shell
ulimit -s 128000
```
which made no difference.
Does anyone have a suggestion?

**Comment by mhoemmen** [comment]
@quentin-ag Just wanted to let you know that I'm not a Trilinos developer these days.  It might help the developers to know what version of Trilinos is giving you this trouble.  I am not speaking for them, but I personally, as a user and not a developer, would very much not recommend using a version of Trilinos as old as 12.10.

**Comment by casparvl** [comment]
@quentin-ag I'm using EasyBuild to build most of my scientific software. There, they implemented a workaround. If I understand correctly what was done there, they create short symlinks for the sources and object directories (i.e. something like `/tmp/src` and `/tmp/obj`). Then change directory to `/tmp/obj` and call cmake on the sourcedir `cmake /tmp/src ...`. I _think_ that will consistently put in the short paths, while the files could be in a deeply nested prefix somewhere.

If this helps you: great, but I have to say I also agree with @mhoemmen that 12.10 is quite old now and unless you have a very specific reason for wanting to use that version (e.g. reproducing prior results or something), it might make more sense to use a newer version where (hopefully) this is fixed on the Trilinos side :)

**Comment by quentin-ag** [comment]
Thanks for the answers, @mhoemmen, @casparvl . I am having this issue with version 13.0.1. I am going to try with a shorter prefix and see if that shortens the argument list enough.

**Comment by fontanj** [comment]
@quentin-ag did you find a solution? I am also having this issue, trying to make an EasyBuild easyconfig for Trilinos version 13.2.0.

**Comment by boegel** [comment]
@quentin-ag Which version of EasyBuild are you using?
We implemented a 'hack' in the Trilinos easyblock a while ago, see https://github.com/easybuilders/easybuild-easyblocks/pull/1486, is that no longer working to circumvent this issue?

**Comment by quentin-ag** [comment]
@fontanj @boegel I did not use EasyBuilb. I was installing from the Arch User Repository (with the helper `pikaur`). I commented on this issue because I was facing exactly the same problem: a long prefix causing the error 'Argument list too long'.

I worked around the issue by manually changing to a shorter prefix – something like `/tmp/trl` I seem to recall.

**Comment by boegel** [comment]
My question was directed to @fontanj, my apologies :) (comment edited above)

**Comment by fontanj** [comment]
@boegel I am using EasyBuild v4.5.1 and yes, it seems the fix in the easyblock is not enough for Trilinos 13.2.0.

**Comment by fontanj** [comment]
@quentin-ag Thanks for the info. Maybe I can shorten the prefix even more.

**Comment by fontanj** [comment]
Shortening the build dir prefix to /tmp/Trilinos-salt resolves the "Argument list too long" error. Now investigating another error.
