### ISSUE TITLE
Framework: Autotester console output unhelpful

### ISSUE THREAD

**Issue by csiefer2** [trilinos/Trilinos#3435]
Can we make this more useful to the developer?

See this PR:
https://github.com/trilinos/Trilinos/pull/3429

We get this unhelpful output:
17) atdm-ninja_fortran/1.7.2
MPI type = sems-mpich/3.2
CDash Track = Pull Request

*** Generating set of Trilinos enables given modified packages from
*** git commit origin/develop to HEAD

TRILINOS_DIR=/scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_intel_17.0.1/Trilinos
TRILINOS_SCRIPTS_DIR=/scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_intel_17.0.1/Trilinos/cmake/std/../..
TRIBITS_DIR=/scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_intel_17.0.1/Trilinos/cmake/std/../../cmake/tribits

A) Generate the Trilinos Packages definition and depencencies XML file

Wrote the file 'TrilinosPackageDependencies.xml'

B) Get the set of changed files

Current directory: /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_intel_17.0.1/Trilinos

git diff --name-only origin/develop..HEAD > /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_intel_17.0.1/changed-files.txt

Wrote file 'changed-files.txt'

Current directory: /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_intel_17.0.1

C) Get the unfiltered list of changed Trilinos packages (including 'ALL_PACKAGES')

CHANGED_PACKAGES_FULL_LIST='MueLu'

D) Filter list of changed packages to get only the PT packages

CHANGED_PACKAGES_PT_LIST='MueLu'

E) Generate the *.cmake enables file

Wrote file 'packageEnables.cmake'
Enabled packages:
-- Setting Trilinos_ENABLE_MueLu = ON
Build name               = PR-3429-test-Trilinos_pullrequest_intel_17.0.1-836
Cur dir                  = /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_intel_17.0.1/TFW_testing_single_configure_prototype
Source dir               = /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_intel_17.0.1/Trilinos
Binary dir               = /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_intel_17.0.1/pull_request_test
Parallel level           = 18
skip_by_parts_submit     = OFF
skip_single_submit       = ON
skip_update_step         = ON
skip_upload_config_files = OFF
skip_clean_build_dir     = OFF
Subproject count         = 53
Dashboard model          = Experimental
Dashboard track          = Pull Request
Running configuration:
/projects/sems/install/rhel6-x86_64/atdm/binary-install/cmake-3.11.1-Linux-x86_64/bin/cmake
-C "/scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_intel_17.0.1/Trilinos/cmake/std/PullRequestLinuxIntelTestingSettings.cmake"
-C "/scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_intel_17.0.1/packageEnables.cmake"
-DTrilinos_ENABLE_TESTS:BOOL=ON
-G "Ninja"
/scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_intel_17.0.1/Trilinos
CTEST_DROP_LOCATION = /cdash/submit.php?project=Trilinos
CDash URL1 = https://testing-vm.sandia.gov/cdash/index.php?project=Trilinos&display=project&filtercount=3&showfilters=1&filtercombine=and&field1=site&compare1=61&value1=ascic158&field2=buildname&compare2=61&value2=PR-3429-test-Trilinos_pullrequest_intel_17.0.1-836&field3=buildstamp&compare3=61&value3=20180912-0916-Pull Request
CDash URL2 = https://testing-vm.sandia.gov/cdash/index.php?project=Trilinos&display=project&filtercount=2&showfilters=0&filtercombine=and&field1=buildname&compare1=61&value1=PR-3429-test-Trilinos_pullrequest_intel_17.0.1-836&field2=buildstamp&compare2=61&value2=20180912-0916-Pull Request
CDash URL3 = https://testing-vm.sandia.gov/cdash/index.php?project=Trilinos&filtercount=2&showfilters=0&filtercombine=and&field1=buildname&compare1=61&value1=PR-3429-test-Trilinos_pullrequest_intel_17.0.1-836&field2=buildstamp&compare2=61&value2=20180912-0916-Pull Request
Starting configure step.
Each . represents 1024 bytes of output
..................................................  Size: 50K
..................................................  Size: 100K
.................................... Size of output: 135K
configure submit error = 0
Configure suceeded.
Starting build step.
Each symbol represents 1024 bytes of output.
..................................................  Size: 49K
..................................................  Size: 99K
..................................................  Size: 149K
..................................................  Size: 199K
..................................................  Size: 249K
..................................................  Size: 299K
..................................................  Size: 349K
..................................................  Size: 400K
..................................................  Size: 449K
..................................................  Size: 499K
..................................................  Size: 549K
..................................................  Size: 599K
..................................................  Size: 649K
..................................................  Size: 699K
.......... Size of output: 709K
Build succeeded.
build submit error = 0
Starting testing step.
CMake Error at /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_intel_17.0.1/TFW_testing_single_configure_prototype/simple_testing.cmake:193 (message):
Test failed with error -1

test submit error = 0
File upload submit error = 0
Single configure/build/test failed. The error code was: 255
Build step 'Execute shell' marked build as failure
Finished: FAILURE

**Comment by william76** [comment]
The autotester message provides a link to the [CDash output][1].  That's generally going to tell you more about what happened on the job than the console output in Jenkins from CTest.  The console output from the testing tends to be more helpful when the intel compiler can't get a license or if github decided to hang up on the job... something that caused the testing job itself to woof.

Is there something else you'd like to see in the console output that CDash does not have?

@bartlettroscoe can probably elaborate more on this error message...

[1]: https://testing-vm.sandia.gov/cdash/index.php?project=Trilinos&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=63&value1=PR-3429-test&field2=buildstarttime&compare2=84&value2=NOW

**Comment by bartlettroscoe** [comment]
You mean this error message:

```
Build succeeded.
build submit error = 0
Starting testing step.
CMake Error at /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_intel_17.0.1/TFW_testing_single_configure_prototype/simple_testing.cmake:193 (message):
Test failed with error -1

test submit error = 0
File upload submit error = 0
Single configure/build/test failed. The error code was: 255
Build step 'Execute shell' marked build as failure
Finished: FAILURE
```

I don't know anything about the script `simple_testing.cmake` and I have never even seen it.  You will have to ask members of the @trilinos/framework team about that.

Otherwise, define "helpful" or "unhelpful"?
