### ISSUE TITLE
Framework: Add link to PR Test Replication to Autotester message

### ISSUE THREAD

**Issue by william76** [trilinos/Trilinos#3440]
@trilinos/framework @allevin 

It's come up that it would be tremendously helpful to the developer community if a link were provided to the wiki page: https://github.com/trilinos/Trilinos/wiki/Reproducing-PR-Testing-Errors in the test-result message the autotester kicks out.  

I think a good place for this would be right after the `CDash Test Results for PR# NNNN.` link.  Something like:

```
CDash Test Results for PR# NNNN.

Wiki: How to Reproduce PR Testing Builds and Errors
```

This would be especially useful to folks who are infrequent committers who might not be as familiar with navigation around the CDash system, etc.

**Comment by allevin** [comment]
@william76 A change has been made to the autotester. On failing results, the output should look like:

```
CDash Test Results for PR# NNNN.

Wiki: How to Reproduce PR Testing Builds and Errors
```

With the Wiki:... as a link to the wiki page as described above.

**Comment by william76** [comment]
@allevin awesome!  Thanks!

FYI @jhux2 @csiefer2 This should make it a little easier for folks to replicate autotester build failures...

**Comment by allevin** [comment]
@william76 It seems to be working.  See https://github.com/trilinos/Trilinos/pull/3452#issuecomment-422147937.  I think this issue can be closed.

**Comment by jmgate** [comment]
@allevin, it looks to be working fine, but it'd be nice to remove those two extra newlines.

**Comment by william76** [comment]
@jmgate 
I'm going to close this since @allevin won't be fixing this. He might have even taken care of that /shrug I'll have a look at a recent test failure.  If it's a big issue, it's probably best to file a new issue on that and tag @bmpersc since I think he's taken over the Autotester.
