### ISSUE TITLE
STK:  Removal of STKClassic (stk_classic) from Trilinos and STK

### ISSUE THREAD

**Issue by kddevin** [trilinos/Trilinos#3444]
@trilinos/stk @trilinos/framework 

## Expectations

Soon we will remove STKClassic (a.k.a. stk_classic) from the STK and Trilinos repos.
Users who depend on STKClassic should respond to this issue ASAP with questions and concerns.  Thanks!

## Motivation and Context

STKClassic is no longer supported; it has been replaced by the superior capabilities in STK. 
Current STKClassic users can migrate to STK capabilities.

Removing unsupported, obsolete code is necessary to maintain the Trilinos code base.

## Definition of Done

Code and build options removed from Trilinos and STK code bases.
Remove unbuilt/untested trilinoscouplings/examples/example_Poisson_stkclassic.cpp
Remove ifdef-ed out stk_classic code from trilinoscouplings/examples/example_Poisson_stk.cpp
STK/Trilinos integration and tests complete.

**Comment by prwolfe** [comment]
PR #3464 merged last night. If anyone has any issues please re-open this and comment on why.

Thanks!
