### ISSUE TITLE
download for Trilinos 12.12.1 is broken?

### ISSUE THREAD

**Issue by boegel** [trilinos/Trilinos#3447]
When I try to download Trilinos 12.12.1 via https://trilinos.org/download/, I end up with a broken link.

I considered downloading from https://github.com/trilinos/Trilinos/releases instead, but the source tarball tagged there for 12.12.1 seems to be something entirely different (e.g. `CTrilinos` is not in there).

Is the broken download via the website a known problem?
Is there another way to download the same `trilinos-12.12.1-Source.tar.gz` that was available via https://trilinos.org/download?

@trilinos/package

**Comment by aprokop** [comment]
@trilinos/framework

**Comment by boegel** [comment]
For anyone hitting this: the files can also be downloaded from https://trilinos.org/oldsite/download/files/ (same SHA256 checksum for `trilinos-12.12.1-Source.tar.gz` at least)

**Comment by mhoemmen** [comment]
FYI that release is a good three years old -- just want to make sure users are aware of that.

**Comment by boegel** [comment]
@mhoemmen Where we can we find a more recent release (with which I don't mean `master`)?

**Comment by mhoemmen** [comment]
There is no more recent release.  Trilinos hasn't been posting releases since 12.12.z.

**Comment by boegel** [comment]
@mhoemmen Are there any plans to issue a new release? I would guess this severely limits the uptake on recent Trilinos developments...

**Comment by mhoemmen** [comment]
@boegel There may be plans to submit a new release at the end of this month.  @trilinos/framework can say more.

> I would guess this severely limits the uptake on recent Trilinos developments...

Kokkos has its own release schedule that moves at a faster pace.

**Comment by mhoemmen** [comment]
Also, internal applications may not necessarily care about releases.  They track master, and only pull in updates if they are ready and if all their tests pass with the update in place.  This general approach to accepting new versions (try it, and only accept it if all your tests pass) is a good general policy.
