### ISSUE TITLE
NOX: NOX_brusselator is failing the nightly Clean test

### ISSUE THREAD

**Issue by william76** [trilinos/Trilinos#3449]
@trilinos/nox 
The NOX_brusselator is failing the nightly clean testing for the GCC 4.9.3 SERIAL build.

https://testing.sandia.gov/cdash/testDetails.php?test=54496690&build=3938535

The failures started happening on 9/14, could b8e1f86bf7a7916c9d50a9e8f71db47ec9ed81aa be the culprit?

@rppawlo

**Comment by rppawlo** [comment]
@william76 - most likely. Trying to replicate locally now.

**Comment by rppawlo** [comment]
Test came back clean last night. Closing.
