### ISSUE TITLE
Tpetra: MatrixMarket I/O for CrsGraph

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#345]
@trilinos/tpetra Tpetra::CrsGraph needs input and output (I/O) routines.  Easiest thing to do would be to adapt the existing Tpetra::CrsMatrix Matrix Market I/O to Tpetra::CrsGraph.

Motivation for this work is to make it easier to generate and use BlockCrsMatrix test problems, that have a graph structure typical of applications.  We don't need the values to exercise kernels like sparse matrix-vector multiply; we just need the graph structure.  We can save factors of tens of space if we don't have to store the values.

**Comment by amklinv** [comment]
Mark wrote the MatrixMarket writer; I will write the reader.

**Comment by mhoemmen** [comment]
Once this is done, I'll close Bugzilla Bug 6130 (link requires login):

https://software.sandia.gov/bugzilla/show_bug.cgi?id=6130

**Comment by mhoemmen** [comment]
@amklinv fixed this issue this afternoon.  Unit test passes.

**Comment by mmwolf** [comment]
There still seem to be bugs in the sparse graph reading functionality. Some of the readSparseGraphFile functions call readSparseGraph incorrectly. They pass fname of type std::string as the first argument to a function readSparseGraph that accepts std::ifstream instead

**Comment by mhoemmen** [comment]
@mmwolf Could you please submit a pull request?  Thanks!

**Comment by mhoemmen** [comment]
@mmwolf Never mind, I'm on it.

**Comment by mmwolf** [comment]
Thanks, Mark.  I had a workaround but a Tpetra solution is much appreciated.

**Comment by mhoemmen** [comment]
@mmwolf Do you have a unit test?  It looks like that code was added in by somebody else and they didn't have a chance to add in a unit test, so its compilation was never tested.

**Comment by mmwolf** [comment]
@mhoemmen I don't but I can easily extract one from my application or we can add the calls to the current test.

**Comment by mhoemmen** [comment]
@mmwolf It would please me greatly if you could extract out a unit test for me; thanks :D .

**Comment by mhoemmen** [comment]
@mmwolf Thanks for reporting!  In the meantime, I'll call this closed for now.  Please feel free to reopen if needed.
