### ISSUE TITLE
PyTrilinos: Revive PyTrilinos.Tpetra

### ISSUE THREAD

**Issue by wfspotz** [trilinos/Trilinos#3450]
@trilinos/pytrilinos 
@trilinos/tpetra 

## Expectations
When PyTrilinos and Tpetra are enabled, working Python wrappers for Tpetra should be generated

## Current Behavior
Recent changes to the Tpetra package have broken the `PyTrilinos.Tpetra` package

## Definition of Done
The Tpetra wrappers compile and the PyTrilinos test suite passes

## Possible Solution
Modifications to `packages/PyTrilinos/src/Tpetra.i` will need to be made, possibly other files, such as `PyTrilinos_Tpetra_Util.cpp`, to reflect the current state of the Tpetra package.

**Comment by wfspotz** [comment]
@mhoemmen First question: existing classes, such as `Map`, have been moved into the `Tpetra::Classes` namespace. I assume users still expect access to `Tpetra::Map` but I don't see where that comes from.

My first stab has been to wrap `Tpetra::Classes::Map` but to put it into the `PyTrilinos.Tpetra` module (no `Classes` submodule). Do you see any issues with this?

**Comment by wfspotz** [comment]
@mhoemmen Second question: when I try to compile my Tpetra wrappers, I get an error due to a `private` type:

    /Development/Trilinos/PYTPETRA/packages/PyTrilinos/src/TpetraPYTHON_wrap.cpp:8569:83: error: 'global_indices_array_type' is a private member of 'Tpetra::Classes::Map<int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >'

What is happening is that the `Map` method `getMyGlobalIndices` has a return type that is `private`. What are users expected to do? Use `auto`? I don't think this is an option for SWIG.

If that is the case, I can use a `%extend` SWIG directive to redefine the wrapper. I'm just curious if there its something easier to do.

**Comment by mhoemmen** [comment]
@wfspotz wrote:
> First question: existing classes, such as `Map`, have been moved into the `Tpetra::Classes` namespace. I assume users still expect access to `Tpetra::Map` but I don't see where that comes from.

This will continue to change, as part of the ongoing and well-announced plan for Tpetra to deprecate and remove the LocalOrdinal, GlobalOrdinal, and Node template parameters.  That should make your PyTrilinos work easier, but it means that things will be changing.  In particular, Tpetra reserves the right for `Tpetra::${CLASS}` actually to be a type alias ("templated typedef") to `Tpetra::Classes::${CLASS}`.

**Comment by mhoemmen** [comment]
@wfspotz wrote:
> My first stab has been to wrap `Tpetra::Classes::Map` but to put it into the `PyTrilinos.Tpetra` module (no `Classes` submodule). Do you see any issues with this?

This sounds fine.  Just be aware that Tpetra is a moving target for the next few months.  It has to be; Trilinos has abandoned the "quarterly minor releases, yearly major releases" schedule, and so we've had no choice but to take backwards compatibility breaks into our own hands.

**Comment by mhoemmen** [comment]
@wfspotz wrote:
> What are users expected to do? Use `auto`?

Yes, users are expected to use `auto`.  I would prefer for users to do a lot more of that; it would give Tpetra more freedom to change types underneath without breaking backwards compatibility.  Can the SWIG interface use a `decltype` there?

**Comment by wfspotz** [comment]
@mhoemmen wrote:
> Can the SWIG interface use a `decltype` there?
The problem is, within a generated function, SWIG is declaring a `result` variable and I don't have much control over that code generation. I think I have a workaround, though. Thanks.
