### ISSUE TITLE
PyTrilinos: Conflicting types in Teuchos_BLAS_wrapper.hpp

### ISSUE THREAD

**Issue by wfspotz** [trilinos/Trilinos#3456]
@trilinos/pytrilinos 
@trilinos/teuchos 
@trilinos/kokkos-kernels 

## Expectations
I expect to build PyTrilinos without compilation errors

## Current Behavior
I have a wrapper file that `#include`s the header `MLAPI_MultiVector.h` which gives the compilation error

    /Development/Trilinos/packages/teuchos/numerics/src/Teuchos_BLAS_wrappers.hpp:173:13: error: conflicting types for 'daxpy_'
    void PREFIX DAXPY_F77(const int* n, const double* alpha, const double x[], const int* incx, double y[], const int* incy);
                ^
    /Development/Trilinos/packages/teuchos/numerics/src/Teuchos_BLAS_wrappers.hpp:78:21: note: expanded from macro 'DAXPY_F77'
    #define DAXPY_F77   F77_BLAS_MANGLE(daxpy,DAXPY)
                        ^
    /Development/Trilinos/MPI/packages/teuchos/core/src/Teuchos_config.h:10:37: note: expanded from macro 'F77_BLAS_MANGLE'
     #define F77_BLAS_MANGLE(name,NAME) name ## _
                                        ^
    <scratch space>:23:1: note: expanded from here
    daxpy_
    ^
    /Development/Trilinos/packages/kokkos-kernels/src/impl/tpls/KokkosBlas1_axpby_tpl_spec_decl.hpp:49:17: note: previous declaration is here
    extern "C" void daxpy_( const int* N, const double* alpha,

## Definition of Done
I can get the PyTrilinos package to build and all of the PyTrilinos tests to pass.

## Possible Solution
I'm not sure why this conflicting type declaration is occurring, but it is clearly related to macro expansion. Based on `git blame` of `Teuchos_BLAS_wrapper.h` I'm hoping either @jwillenbring or @hkthorn might have some idea what the problem could be. PyTrilinos can present some unique configuration issues.

## Steps to Reproduce
If it gets to this, I can help someone set up their environment to build PyTrilinos.

**Comment by ibaned** [comment]
I think @trilinos/kokkos-kernels should also take a look at this, since their header provides the second of the two conflicting definitions.

**Comment by mhoemmen** [comment]
kokkos-kernels didn't hide the macro & extern definitions :(

**Comment by wfspotz** [comment]
With PyTrilinos, there is a code-generation phase and a compilation phase. If I forget something in the code-generation phase, it can muck things up. If new macros get introduced, I might need to add a `%include` swig directive.

**Comment by mhoemmen** [comment]
It looks like this is really a kokkos-kernels / Teuchos issue; it could come up in non-SWIG code.

**Comment by srajama1** [comment]
@vqd8a : This was the issue I mentioned.

**Comment by wfspotz** [comment]
If someone would like to investigate this but needs to be able to reproduce it, I would be happy to help them set up their system for building PyTrilinos, which should trigger the problem.

**Comment by wfspotz** [comment]
Just to make this issue more concrete, line 173 of `Teuchos_BLAS_wrappers.hpp` is

    void PREFIX DAXPY_F77(const int* n, const double* alpha, const double x[], const int* incx, double y[], const int* incy);

In my case, `PREFIX` is the NULL string and `DAXPY_F77` expands to `daxpy_`.

Line 49 of `KokkosBlas1_axpby_tpl_spec_decl.hpp` is

    extern "C" void daxpy_( const int* N, const double* alpha,
                                          const double* x, const int* x_inc,
                                          const double* y, const int* y_inc);

and according to @mhoemmen the definition in `KokkosBlas1_axpby_tpl_spec_decl.hpp` is not properly protected.  How hard would this be to fix?

**Comment by wfspotz** [comment]
`git blame` attributes `KokkosBlas1_axpby_tpl_spec_decl.hpp` to @crtrott.

**Comment by mhoemmen** [comment]
@kyungjoo-kim

**Comment by ndellingwood** [comment]
@kyungjoo-kim does the fix apply to Trilinos and rely on kokkos-kernels develop branch? If not depending on kokkos-kernels develop branch, then go ahead and issue PR to Trilinos' develop branch (assuming these are changes needed in Trilinos e.g. Teuchos). If the changes are directly to kokkos-kernels then issue the PR to kokkos-kernels develop branch. Thanks!

**Comment by kyungjoo-kim** [comment]
@ndellingwood no I did not fix anything yet and am looking for a branch that I can work so that I can directly put the fix in the integration.

**Comment by ndellingwood** [comment]
@kyungjoo-kim the kokkos-promotion branch is only tracking changes in Trilinos, kokkos and kokkos-kernels develop branches are still kept separate until we're final ready to complete the promotion. So if the changes are to kokkos-kernels develop branch issue the fix as a PR to kokkos-kernels. If the changes are to Trilinos, but do not rely on kokkos-kernels develop branch, then issue the PR to Trilinos and it will get merged in before the next round of integration testing.
If there are changes to both kokkos-kernels develop branch and Trilinos, you can make the changes as a patch to Trilinos and make sure to put in a PR to kokkos-kernels with the matching changes so they aren't wiped out by the snapshot when promotion is complete.

**Comment by kyungjoo-kim** [comment]
@ndellingwood never mind... @wfspotz the fix is already included in kokkoskernels. we just need to wait until integration completes.

https://github.com/kokkos/kokkos-kernels/pull/330/files
