### ISSUE TITLE
Configuration of CUDA-enabled build fails

### ISSUE THREAD

**Issue by pelesh** [trilinos/Trilinos#3469]
Configuration of a CUDA-enabled Tpetra/Kokkos build fails at the point where CMake checks for C++ compiler. The error message is:
```
  Linking CXX executable cmTC_babeb

  /usr/tce/packages/cmake/cmake-3.5.2/bin/cmake -E cmake_link_script
  CMakeFiles/cmTC_babeb.dir/link.txt --verbose=1

  /usr/tce/packages/openmpi/openmpi-2.0.0-gcc-6.1.0/bin/mpicxx
  CMakeFiles/cmTC_babeb.dir/testCXXCompiler.cxx.o -o cmTC_babeb -rdynamic

  nvcc fatal : Unknown option 'rdynamic,-fexceptions,-pthread'

  gmake[1]: *** [cmTC_babeb] Error 1
```
It seems as if Kokkos' `nvc_wrapper` does not insert `-Xlinker` flags correctly. 

I am building from current master branch on a system with following configuration:
```
$ module list

Currently Loaded Modules:
1) StdEnv   2) gcc/6.1.0   3) cuda/9.1.85   4) openmpi/2.0.0   5) cmake/3.5.2
```
The same issue occurs with different openmpi, CUDA, CMake and gcc versions. 

I am following Tpetra build instructions from `$Trilinos/packages/tpetra/doc/FAQ.txt`, and I set environment variables like this:
```
  export OMPI_CXX=${Trilinos}/packages/kokkos/bin/nvcc_wrapper
  export CUDA_LAUNCH_BLOCKING=1
  export CUDA_MANAGED_FORCE_DEVICE_ALLOC=1
```
I use following configuration script to set cmake options:
```
#!/bin/bash

cmake \
   -D CMAKE_C_COMPILER="mpicc" \
   -D CMAKE_CXX_COMPILER="mpicxx" \
   -D CMAKE_Fortran_COMPILER="mpif90" \
   \
   -D Trilinos_CXX11_FLAGS="-std=c++11 --expt-extended-lambda" \
   \
   -D Trilinos_ENABLE_OpenMP=OFF \
   -D TPL_ENABLE_Pthread=OFF \
   \
   -D Trilinos_ENABLE_Teuchos=ON \
   -D Trilinos_ENABLE_Tpetra=ON \
   -D Tpetra_INST_SERIAL=ON \
   -D Tpetra_INST_OPENMP=OFF \
   \
   -D Trilinos_ENABLE_Kokkos=ON \
   -D Trilinos_ENABLE_KokkosCore=ON \
   -D Kokkos_ENABLE_Serial=ON \
   -D Kokkos_ENABLE_OpenMP=OFF \
   -D Kokkos_ENABLE_Pthread=OFF \
   -D Kokkos_ENABLE_Cuda=ON \
   -D Kokkos_ENABLE_Cuda_UVM=ON \
   -D Kokkos_ENABLE_Cuda_Lambda=ON \
   -D Kokkos_ENABLE_Cuda_Relocatable_Device_Code=OFF \
   -D TPL_ENABLE_CUDA=ON \
   \
   -D TPL_ENABLE_MPI=ON \
   -D MPI_USE_COMPILER_WRAPPERS=ON \
   \
  -D Tpetra_INST_CUDA:BOOL=ON \
../Trilinos
```
Any advice how to get past this point would be most appreciated.

**Comment by mhoemmen** [comment]
If you disable Tpetra and just build Kokkos (`Trilinos_ENABLE_Kokkos=ON` and `Trilinos_ENABLE_Tpetra=OFF`), does it work?

**Comment by mhoemmen** [comment]
@trilinos/kokkos

**Comment by pelesh** [comment]
@keitat I tried to build @trilinos/kokkos from 12.14 branch, and I am getting the same error message. It is weird, because everything works fine when I use the same script to configure a build on my RHEL7 Linux workstation. This could be a bug in Cmake.

**Comment by mhoemmen** [comment]
@trilinos/framework

**Comment by mhoemmen** [comment]
Trilinos needs CMake 3.11 now, no?

**Comment by pelesh** [comment]
Same thing happens with CMake 3.12.1. It seems that `nvcc_wrapper` script is not handling linking flags correctly and is passing to `nvcc` flags it does not recognize. The same happens with different versions of Open MPI, gcc, and CUDA. Below is the CMake error message:
```
  The C++ compiler

    "/.../packages/openmpi/openmpi-2.0.0-gcc-6.1.0/bin/mpicxx"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /.../trilinos/build-gcc610-cuda91/CMakeFiles/CMakeTmp
    
    Run Build Command:"/usr/bin/gmake" "cmTC_b548a/fast"
    /usr/bin/gmake -f CMakeFiles/cmTC_b548a.dir/build.make CMakeFiles/cmTC_b548a.dir/build
    gmake[1]: Entering directory `/.../trilinos/build-gcc610-cuda91/CMakeFiles/CMakeTmp'
    Building CXX object CMakeFiles/cmTC_b548a.dir/testCXXCompiler.cxx.o
    /.../packages/openmpi/openmpi-2.0.0-gcc-6.1.0/bin/mpicxx     -o CMakeFiles/cmTC_b548a.dir/testCXXCompiler.cxx.o -c /.../trilinos/build-gcc610-cuda91/CMakeFiles/CMakeTmp/testCXXCompiler.cxx
    Linking CXX executable cmTC_b548a
    /.../packages/cmake/cmake-3.12.1/bin/cmake -E cmake_link_script CMakeFiles/cmTC_b548a.dir/link.txt --verbose=1
    /.../packages/openmpi/openmpi-2.0.0-gcc-6.1.0/bin/mpicxx       -rdynamic CMakeFiles/cmTC_b548a.dir/testCXXCompiler.cxx.o  -o cmTC_b548a 
    nvcc fatal   : Unknown option 'rdynamic,-fexceptions,-pthread'
    gmake[1]: *** [cmTC_b548a] Error 1
    gmake[1]: Leaving directory `/.../build-gcc610-cuda91/CMakeFiles/CMakeTmp'
    gmake: *** [cmTC_b548a/fast] Error 2
```

**Comment by mhoemmen** [comment]
Did you set `OMPI_CXX` to `nvcc_wrapper`?

**Comment by pelesh** [comment]
Yes, I did. This is how I build Trillions with CUDA support on my workstation. As you can see from the error log, the wrapper is working and `mpicxx` is using `nvcc` as the underlying compiler. It seems that at linking stage the script passes flags `-rdynamic,-fexceptions,-pthread` directly to the `nvcc`, which it does not recognize.

**Comment by mhoemmen** [comment]
Is this still 12.14 or are you using master Trilinos?  The latter is more likely to work.

**Comment by pelesh** [comment]
It is the HEAD of 12.14 branch. I'll try with master. What is puzzling to me is that everything works well on RHEL7, but not on TOSS3, even though the two are quite similar OSes.

**Comment by keitat** [comment]
I feel "-rdynamic,-fexceptions,-pthread" is related to OpenMPI.  However, it is just a guess.  I just got an account of similar machines at Sandia.  Let me see how it goes.

**Comment by mhoemmen** [comment]
I will try building Trilinos on one of your machines, and report back.  We have a lot of CUDA builds working fine on our side.  I can also try your configuration on one of our machines, just to make sure.

**Comment by pelesh** [comment]
Thanks, Mark, that would be really helpful. In the meantime, I will build Trilinos from the most recent master on an LC machine and see if it works. By the way, the build that works for me is with pretty antiquated dependencies -- gcc 4.9.2, CUDA 8.0, and openmpi 1.10. This is on my RHEL7 workstation.


I have a follow-up question on the `add` method. If I do something like this:

  auto tmp = A->add(ONE, *B, c, domainMap, rangeMap, params);

the `tmp` is an RCP to a row matrix object. If I try to assign

  RCP<CrsMatrix<...> > C = tmp;

I get a compilation error.


What is the proper way get a CrsMatrix object from the return value of `add` function?


Many thanks,

Slaven

________________________________

**Comment by mhoemmen** [comment]
@pelesh Hi Slaven!  CrsMatrix inherits from RowMatrix.  It turns out that the returned object is a CrsMatrix.  You can use `Teuchos::rcp_dynamic_cast` to convince it to be a CrsMatrix:
```c++
RCP<CrsMatrix<...>> C = Teuchos::rcp_dynamic_cast<CrsMatrix<...>> (tmp);
```

**Comment by pelesh** [comment]
@mhoemmen @keitat Same error occurs on a TOSS3 machine with most recent master and following toolchain:
```
 Currently Loaded Modules:
 ...  2) StdEnv   3) cmake/3.13.4   4) gcc/7.3.0   5) openmpi/2.0.0   6) cuda/9.2.88
```
I used this CMake configure script:
```
#!/bin/bash
#=============================================================================
# Configure Trilinos
#=============================================================================

export TRILINOS_SRC_DIR=../Trilinos
export TRILINOS_INST_DIR=$HOME/local/trilinos-master-gcc73-cuda92

CC=mpicc CXX=mpicxx cmake \
   -D BUILD_SHARED_LIBS:BOOL="1" \
   -D CMAKE_INSTALL_PREFIX:PATH=${TRILINOS_INST_DIR} \
   -D TPL_ENABLE_MPI="ON" \
   -D Trilinos_ENABLE_OpenMP:BOOL="1" \
   -D Trilinos_ENABLE_Tpetra:STRING="OFF" \
   -D TPL_ENABLE_CUDA:BOOL=ON \
   -D Kokkos_ENABLE_Cuda_UVM:BOOL=ON \
   -D Kokkos_ENABLE_Cuda_Lambda:BOOL=ON \
   -D Tpetra_INST_CUDA:BOOL=ON \
   -D Trilinos_ENABLE_TESTS:STRING="ON" \
   -D Trilinos_CXX11_FLAGS="-std=c++11 --expt-extended-lambda" \
   ${TRILINOS_SRC_DIR}
```

**Comment by pelesh** [comment]
@mhoemmen and @keitat have you been able to build Kokkos with MPI on a TOSS3 machine? I tried the same configuration on a cluster with ROCKS 7 beta OS (a derivative of CentOS7) and everything worked well. It seems this issue is specific to TOSS3. I wasn't able to reproduce it elsewhere.

**Comment by mhoemmen** [comment]
@pelesh I've been pretty swamped trying to improve GPU performance, alas.

**Comment by jmfinney-icl** [comment]
@pelesh, where you able to resolve this issue?

**Comment by jrood-nrel** [comment]
I'm going to link this to https://gitlab.kitware.com/cmake/cmake/-/issues/18558 since I've been experiencing this in another project I have. It comes from OpenMPI in my case using `mpicc -showme`. It seems to be related to whether or not only `FindMPI` in CMake is used for the compile flags, or if you are passing in `mpicc` as the CMake compiler directly for example. The latter seems to not include `-fexceptions` from OpenMPI for me.
