### ISSUE TITLE
Tpetra: Consider adding vector element-wise division function

### ISSUE THREAD

**Issue by pelesh** [trilinos/Trilinos#3471]
Please consider adding element-wise division function for Tpetra (multi)vector:
z(i) = x(i)/y(i) for all i
This function is needed for Tpetra interface to [SUNDIALS](http://github.com/LLNL/sundials), but I guess it may be useful elsewhere.

**Comment by mhoemmen** [comment]
Here is an example of how to implement this: https://github.com/trilinos/Trilinos/blob/802b9e46b0ecbd1298e149bf63608d5791ef41d8/packages/ifpack2/example/RelaxationWithEquilibration.cpp#L416

**Comment by mhoemmen** [comment]
@trilinos/tpetra This should not be an instance method; it should be a free function.
