### ISSUE TITLE
Belos: BelosMueLuAdapter.hpp includes klu2_internal.h

### ISSUE THREAD

**Issue by jappa** [trilinos/Trilinos#3477]
Including BelosMueLuAdapter.hpp in a user program results in the inclusion of klu2_internal.h.

I am using trilinos-12.12.1.

From the comments and defines in klu2_internal.h I assume this should not happen. Trace of include hierarchy listed below.

include/klu2_internal.h:8
include/klu2_defaults.hpp:41:0,
include/Amesos2_KLU2_FunctionMap.hpp:68,
include/Amesos2_KLU2_decl.hpp:57,
include/Amesos2_KLU2.hpp:47,
include/Amesos2_Factory.hpp:99,
include/Amesos2.hpp:45,
include/MueLu_Amesos2Smoother_def.hpp:56,
include/MueLu_Amesos2Smoother.hpp:2,
include/MueLu_DirectSolver_def.hpp:57,
include/MueLu_DirectSolver.hpp:2,
include/MueLu_FactoryManager_def.hpp:58,
include/MueLu_FactoryManager.hpp:2,
include/MueLu_Hierarchy_decl.hpp:67,
include/MueLu_Hierarchy.hpp:1,
include/BelosMueLuAdapter.hpp:67,

@trilinos/Belos

**Comment by mhoemmen** [comment]
@trilinos/belos @trilinos/muelu 

Try Trilinos:master.  12.12 is three years old.  If you must have a release, a new release tag (12.14) just came out:

https://github.com/trilinos/Trilinos/tree/trilinos-release-12-14-branch

though I don't think it is official yet.

**Comment by jappa** [comment]
I can confirm that this is fixed in version 12.14
