### ISSUE TITLE
the problem of teuchos

### ISSUE THREAD

**Issue by wuliwei** [trilinos/Trilinos#348]
In the development version of Trilinos, libteuchos.so does not exist anymore. It has been replace by libteuchoscomm.so, libteuchoscore.so,  libteuchosnumerics.so, libteuchosparameterlist.so, and libteuchosremainder.so. How can I do that?

**Comment by mhoemmen** [comment]
What do you mean by "How can I do that?"

Users normally link against Trilinos by using the Makefile.export.* files that the build process generates, or by using FIND_PACKAGE(Trilinos ...).  Both of these mechanisms define variables that show the list of libraries against which you must link.  You should never attempt to define those variables manually.

**Comment by wuliwei** [comment]
Hi mark,thank you. I have installed the packages and succeeded, but when I use it , there is a error about libteuchos. And I am a beginner ,so I don't know what to do to solve it.

**Comment by amklinv** [comment]
Hello Michael,

Your issue is unclear.  Do you mean you're having trouble linking against Trilinos?  If so, here's an example makefile for using Trilinos from your code:

```
TRILINOS_DIR=/your/path/to/trilinos/install
include $(TRILINOS_DIR)/include/Makefile.export.Trilinos

CXX=$(Trilinos_CXX_COMPILER)
CXX_FLAGS=$(Trilinos_CXX_COMPILER_FLAGS) $(USER_CXX_FLAGS)

INCLUDE_DIRS=$(Trilinos_INCLUDE_DIRS) $(Trilinos_TPL_INCLUDE_DIRS) 
LIBRARY_DIRS=$(Trilinos_LIBRARY_DIRS) $(Trilinos_TPL_LIBRARY_DIRS) 
LIBRARIES=$(Trilinos_LIBRARIES) $(Trilinos_TPL_LIBRARIES)

LINK_FLAGS=$(Trilinos_EXTRA_LD_FLAGS)

your_example: your_example.o
	$(CXX) $(CXX_FLAGS) $(OFILES) your_example.o -o $@ $(LINK_FLAGS) $(INCLUDE_DIRS) $(LIBRARY_DIRS) $(LIBRARIES)

.SUFFIXES:
.SUFFIXES: .cpp .o

%.o: %.cpp $(HFILES)
	$(CXX) -c $(CXX_FLAGS) $(INCLUDE_DIRS) $< -o $@

.PHONY: clean
clean:
	rm -f *.o *~
```

**Comment by wuliwei** [comment]
Hi  amklinv,
Thank you .I don't know how to describe my problem .When I run my code, there is a problem saying that **can't find ltechous**. Do you know what it means?

**Comment by amklinv** [comment]
It means you are linking the problem incorrectly.  Please don't try compiling with -ltechos.  Instead, use a makefile like the one I provided, or the one here: http://trilinos.sandia.gov/Export_Makefile_example.txt

**Comment by mhoemmen** [comment]
@wuliwei Please do not use Github for user support questions.  Use the trilinos-users e-mail list (find it on trilinos.org) for questions like that.  We have established that there is no bug in Trilinos, therefore this issue is closed.

**Comment by wuliwei** [comment]
@amklinv Thank you very much! I have use the makefile that you provided and succeeded . Would you mind giving me your e-mail address? I would like to keep in touch with you and be your friend.( ^_^ )

**Comment by wuliwei** [comment]
@mhoemmen  I'm so sorry about that . There isn't any bug in Trilinos, just my problem.  Thanks for your help.

**Comment by amklinv** [comment]
@wuliwei Please use the email address provided at https://trilinos.org/community/contact/, which goes to me and all the other Trilinos developers :-)

**Comment by wuliwei** [comment]
Ok, thank you!
