### ISSUE TITLE
Panzer: Uninitialized variable in panzer::ModelEvaluator::evalModelImpl() causing random crash

### ISSUE THREAD

**Issue by glhenni** [trilinos/Trilinos#3488]
@trilinos/panzer 

In Panzer_ModelEvaluator_impl.hpp::evalModelImpl() at or around line 1413 a boolean variable, do_fd_dfdp_, is being used uninitialized during a charon run. In parallel it means that some of the processors may have a mismatched value for this variable and it's causing seemingly random crashes with non-useful MPI error messages. The variable is only initialized via the setupModel() method within the same file. Unfortunately nothing in charon or panzer is invoking that function. 

Solutions: 1) Either an invocation of setupModel() needs to be added to panzer, or, 2) I need someone to help me understand how to invoke that call within charon.

To verify that was the cause of my random crashes I went in and initialized do_fd_dfdp_ to false within all the ctors and the crashes disappeared. From my read of the code however, I think invoking setupModel() is the correct fix.

**Comment by jmgate** [comment]
@eric-c-cyr, is `setupModel()` supposed to be called, or should `do_fd_dfdp_` be initialized to `false` in the two constructors?  I'd lean toward the latter, but perhaps the answer's both.

**Comment by jmgate** [comment]
Actually, doesn't the default constructor for `bool` initialize the value to `false`?  Pretty sure it's supposed to.

**Comment by jmgate** [comment]
Ah, apparently that's not guaranteed for an optimized build.  I'll add the initialization to false in the constructors and that should clear everything up.

**Comment by glhenni** [comment]
Negative on the C++ default initialization of bool types. In fact I don't think C++ guarantees that any primitive type will be initialized, at least local primitive types. I vaguely recall some exception for global variables. Also, valgrind complaining about it being uninitialized is what lead me to the discovery of the problem.

I did add the initialization to the ctors, and that did indeed fix the problem, but I couldn't convince myself that the failure to call setupModel() wasn't a bug in and of itself.

**Comment by rppawlo** [comment]
@glhenni - There are three ctors for the panzer ME. I think you are using the the one that supplies everything needed to fully build the ME at construction time. We had other use cases where we had to build the ME and then delay initialization until later in the process. So the other 2 ctors require that setupModel be called. The missing initialization of the bool is an error and does need to be added to all ctors. Thanks @jmgate for taking care of this.

**Comment by glhenni** [comment]
@rppawlo, @jmgate The error seems to be gone. It was a random occurrence but I've just run the nightly test suite 3 times and I didn't see any errors. I don't think I could get that many successful runs in before this change. Thanks!
