### ISSUE TITLE
Epetra lessons don't show code

### ISSUE THREAD

**Issue by davydden** [trilinos/Trilinos#3494]
PackageName: Epetra

HTML pages for Epetra Lessons (i.e. https://trilinos.org/docs/dev/packages/epetra/doc/html/Epetra_Lesson02.html) do not render the code. This works as expected for TPetra (i.e. https://trilinos.org/docs/dev/packages/tpetra/doc/html/Tpetra_Lesson01.html)

@trilinos/epetra

**Comment by mhoemmen** [comment]
@trilinos/epetra
