### ISSUE TITLE
Amesos: Compilation fails with SuperLU_DIST 5.4.0+

### ISSUE THREAD

**Issue by Sbte** [trilinos/Trilinos#3508]
@trilinos/amesos

possibly also

@trilinos/amesos2
@trilinos/ml
@trilinos/muelu

since these all make use of `LargeDiag`.

## Expectations
Amesos works with the latest versions of SuperLU_DIST

## Current Behavior
With 5.4.0 compilation fails with

```
packages/amesos/src/Amesos_Superludist.cpp(475): error: identifier "LargeDiag" is undefined
      if( RowPerm_ == "LargeDiag" ) PrivateSuperluData_->options_.RowPerm = LargeDiag;
```

with 6.0.0 it fails with more errors

```
include/superlu_dist_config.h(7): warning #47: incompatible redefinition of macro "HAVE_LAPACK" (declared at line 111 of "build/packages/epetra/src/Epetra_config.h")
  #define HAVE_LAPACK TRUE
          ^
packages/amesos/src/Amesos_Superludist.cpp(60): error: identifier "superlu_options_t" is undefined
    superlu_options_t options_;
    ^
packages/amesos/src/Amesos_Superludist.cpp(475): error: identifier "LargeDiag" is undefined
      if( RowPerm_ == "LargeDiag" ) PrivateSuperluData_->options_.RowPerm = LargeDiag;
                                                                            ^
```

Possibly there are more errors when these are resolved.

**Comment by mhoemmen** [comment]
@trilinos/amesos

**Comment by ndellingwood** [comment]
PR #3209 has a (partial) fix for this by @balay. I can quickly add pattern-match fixes for Amesos2. The issue with the PR is that it will likely break backward-compatibility with older versions of superlu_dist.
@jwillenbring @mhoemmen what versions of superlu_dist is Trilinos required to support?

**Comment by jhux2** [comment]
@ndellingwood 

> what versions of superlu_dist is Trilinos required to support?

Issue #2944 is relevant.

**Comment by Sbte** [comment]
I suppose that it should at least support the older versions pre 5.4.0, since 5.4.0 has only been released a few months ago and 6.0 a few days ago.

**Comment by mhoemmen** [comment]
@ndellingwood SPARC uses SuperLU_DIST 4.2.  Sierra doesn't appear to use SuperLU_DIST.

**Comment by jwillenbring** [comment]
@mhoemmen Is there somewhere @ndellingwood could access SuperLU_DIST 4.2?

**Comment by jwillenbring** [comment]
@ndellingwood 5.2.2 is available on the SEMS NFS mount environment. If @mhoemmen can point you to SuperLU_DIST 4.2, or confirm it for you, I think we could pass a modified patch back to @balay and he could test 5.4. Does that seem reasonable?

**Comment by mhoemmen** [comment]
@jwillenbring It's available through the various `sparc-dev` modules on some testbeds.

**Comment by ndellingwood** [comment]
@jwillenbring @mhoemmen @jhux2 I updated the PR #3209 (submitted by @balay with a fix) to guard the changes based on older (<5.4.0) vs newer versions of Superlu_Dist. Amesos compiles and unit tests pass with 4.2.0 and 5.2.2, more extensive testing will need to be done by someone with the configurations and systems needed by xsdk.

**Comment by ndellingwood** [comment]
@jwillenbring @mhoemmen I could not push the updates directly to PR #3209 so I opened PR #3532 which includes that PR along with the updates.

**Comment by ndellingwood** [comment]
PR #3209 updated and will be used for the fix and has the cleaner commit history, closing #3532.

**Comment by ndellingwood** [comment]
PR #3209 merged into develop branch to address this issue, closing the issue.
