### ISSUE TITLE
Teuchos: Improve build time by stripping many includes from Teuchos_ConfigDefs.hpp

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#351]
@trilinos/teuchos @bartlettroscoe @nmhamster 

Lines 80-105 of Teuchos_ConfigDefs.hpp include a lot of standard library header files.  Just about every Teuchos header file includes Teuchos_ConfigDefs.hpp, and many Trilinos packages include a Teuchos header file.  Thus, everybody includes all those headers.  That increases build time.

We really need to remove those includes.  I tried doing something like this in Tpetra_ConfigDefs.hpp once, and it broke a bunch of stuff downstream.  In theory, it's their fault that they relied on unnecessary upstream includes.  In practice, if we break their build, it interrupts their work and makes them grumpy.  Thus, it's important to test EVERY PACKAGE that depends on Teuchos.  We really should also test external software that depends on Teuchos or its downstream packages.  Examples include Dakota (https://dakota.sandia.gov) and Nalu (https://github.com/spdomin/Nalu).  Nevertheless, we need to brace ourselves for some disruption and complaints.

**Comment by bartlettroscoe** [comment]
A little history on this ...

The reason all of these includes were done in once place was to deal with early C++ compilers that did not have full or correct support for the C++98 standard library.  This is the file where we hacked things up to make our usage of the C++98 standard library portable.  But we have not had problems like this from about 2004 or 2005.  Therefore, it is way past time to remove these std includes from these `<Package>_ConfigDefs.hpp` files and move them down as low as we can all over Trilinos.

Note, I think this would be a good task for Tech-X to perform (@maherou and @jwillenbring  would this be a possible future Tech-X task?).  The process to address this problem is very straightforward.  You just remove one or a few of the includes from Teuchos_ConfigDefs.hpp and then fix all of the build errors in all of Trilinos.  You just need to add the includes back at the the lowest level you can.

**Comment by gsjaardema** [comment]
The clang include what you use tool can do this for you almost
automatically.  We have used it quite a bit in Sierra and the main area of
trouble is in ifdefd code.

.. Greg

**Comment by rppawlo** [comment]
This is going to break more than Trilinos. I can think of at least 5 internal application codes that are almost guaranteed to break. Can we wrap the headers to be removed with an ifdef so that the apps can recover the old behavior with a cmake flag if they can't transition immediately?

**Comment by bartlettroscoe** [comment]
> This is going to break more than Trilinos. I can think of at least 5 internal application codes that are almost guaranteed to break.  Can we wrap the headers to be removed with an ifdef so that the apps can recover the old behavior with a cmake flag if they can't transition immediately? 

Yes, that is a good idea and will be easy to do.  We can use a macro define called something like `TEUCHOS_PROVIDE_GLOBAL_STD_INCLUDES`.   For now, to maintain backward compatibility, the default can be to define this in `Teuchos_ConfigDefs.hpp` as:

```
#ifndef TEUCHOS_HIDE_DEPRECATED_CODE

#ifndef TEUCHOS_PROVIDE_GLOBAL_STD_INCLUDES
#  define TEUCHOS_PROVIDE_GLOBAL_STD_INCLUDES=1
#endif

#if TEUCHOS_PROVIDE_GLOBAL_STD_INCLUDES
#include <iostream>
...
#endif // TEUCHOS_PROVIDE_GLOBAL_STD_INCLUDES

#endif TEUCHOS_HIDE_DEPRECATED_CODE
```

Then, to do the refactoring incrementally, someone can add  `-DTEUCHOS_PROVIDE_GLOBAL_STD_INCLUDES=0` to `CMAKE_CXX_FLAGS` and clean up one Trilinos package (and its examples and tests) at a time.  Once we are done with all of Trilinos, then we can tell customers that if they want Trilinos and their application codes to build faster, then they need to set `-DTEUCHOS_PROVIDE_GLOBAL_STD_INCLUDES=0` and clean up their includes.  Therefore, it will be up to them when they refactor their codes on their own schedule.

And when we drop backward compatibility for the Trilinos 13.0 release, we can strip out all of this deprecated code as described [here](https://tribits.org/doc/TribitsDevelopersGuide.html#removing-deprecated-code-from-remaining-files).  That means that application codes will need to get this taken care of after we branch the last Trilinos 12.Y release.

Does that sound like a good plan?

**Comment by bartlettroscoe** [comment]
> The clang include what you use tool can do this for you almost automatically. 

Is it this tool:

http://include-what-you-use.org/

?

> We have used it quite a bit in Sierra and the main area of trouble is in ifdefd code.

Who should we contact on the SIERRA team for details on the usage of this tool?  What version of Clang, etc.?

**Comment by gsjaardema** [comment]
Yes, i think that is it.

**Comment by gsjaardema** [comment]
Kendall Pierson or the dev ops team would be good contacts.
..Greg

**Comment by mhoemmen** [comment]
> The process to address this problem is very straightforward. You just remove one or a few of the includes from Teuchos_ConfigDefs.hpp and then fix all of the build errors in all of Trilinos. You just need to add the includes back at the the lowest level you can.

https://www.youtube.com/watch?v=7s664NsLeFM

(Carl Sagan: If you wish to make an apple pie from scratch, you must first invent the universe.)  But thankfully Roger pointed out that this affects more than just Trilinos.  For example, Dakota depends on Teuchos.

**Comment by bartlettroscoe** [comment]
FYI: @mhoemmen has been making several commits to Trilinos associated with the Story including:

* 11f11e1 Teuchos: Remove ancient macro and typedef from Teuchos_ConfigDefs.hpp
* 5970f03 Teuchos: Move DummyDummyClass decl out of Teuchos_ConfigDefs.hpp
* 2bb3033 Teuchos: Remove memory include from Teuchos_ConfigDefs.hpp
* 3a5e4cb Teuchos: Remove fstream include from Teuchos_ConfigDefs.hpp
* 4a0efbc Teuchos: Remove climits include from Teuchos_ConfigDefs.hpp
* dbd728f Teuchos: Remove cstdio include from Teuchos_ConfigDefs.hpp
* 2491af7 Teuchos: Remove cstdarg include from Teuchos_ConfigDefs.hpp
* b7b47ad Teuchos: Remove cerrno include from Teuchos_ConfigDefs.hpp
* 0b41711 Teuchos: Remove numeric include from Teuchos_ConfigDefs.hpp
* 75f5fdb Teuchos: Remove set include from Teuchos_ConfigDefs.hpp
* fdea7ae Teuchos: Remove list include from Teuchos_ConfigDefs.hpp
* e2f1f44 Teuchos: Remove deque include from Teuchos_ConfigDefs.hpp
* e6ed37a Teuchos: Remove map & vector includes from Teuchos_ConfigDefs.hpp

@mhoemmen, are you seeing build times drop at all after making these changes?

**Comment by mhoemmen** [comment]
@bartlettroscoe I haven't measured yet, but it does seem a little snappier.  I would prefer to compare before I started this process, to after its completion, but I would welcome earlier measurements :-) .

**Comment by bartlettroscoe** [comment]
> I haven't measured yet, but it does seem a little snappier. I would prefer to compare before I started this process, to after its completion, but I would welcome earlier measurements :-) .

We can just wait until later and then checkout an older version of Trilinos before this work started and then compare the build and rebuild times to after this work is done.

**Comment by jwillenbring** [comment]
@mhoemmen  If you want to document additional actions you plan to take for this ticket, let me know and we can get @MicheldeMessieres involved. This aligns directly with current Tech-X activities. You can specify what needs to be done or investigated and review pull requests instead of doing the complete implementation.

**Comment by jwillenbring** [comment]
@MicheldeMessieres is planning to do some benchmarking. He already has some infrastructure put together for measuring build times.

**Comment by MicheldeMessieres** [comment]
@mhoemmen @jwillenbring 

This is some in-progress info on build times.

To collect build information, I modified the Cmake configuration so each object would call time with option -ftime-report and log to a file. Then parsed this file so the data can be analyzed and sorted.

To consider some of the recent include changes for Teuchos, I ran a sierra build at Nov 15 and Dec 1, using a serial gcc build with make -j1.
   Nov 15: 014ae9293ee959b4f74a5c6e7576f3e1e083d840
   Dec 1: c9926268bd1f58bb36cdce0d456bb7c29ed2203b

Ran each twice to test for reproducibility. Times are in minutes.
                      Run 1       Run 2
    Nov 15       57.57       57.56 
    Dec 1         57.01        57.02

This indicates changes between those two versions (probably the include changes but not actually verified) gives a small but measurable change (about 1% decrease in total build time). Measured per individual object the change was 1.6% decrease with standard deviation 1.2%.

Some other general info from the analysis:

There are 164 build objects dependent on muelu (out of a total 2132) and they represent 48% of the total build time.

Sorting objects by individual build time we have the following top objects:
-   MueLu_ShiftedLaplacian.cpp (58s)
-   Belos_Details_Tpetra_registerLinearSolverFactory.cpp (45s)
-   MueLu_ParameterListInterpreter.cpp (36s)
-   fei_Solver_Belos.cpp (24s)
-   MueLu_RefMaxwell.cpp (24s)
-   Belos_Details_Epetra_registerLinearSolverFactory.cpp (23s)
-   BelosEpetraOperator.cpp (23s)
-   MueLu_ReorderBlockAFactory.cpp (23s)
-   MueLu_VariableDofLaplacianFactory.cpp (23s)
-   MueLu_TentativePFactory.cpp (22s)

Some investigation of MueLu_ShiftedLaplacian.cpp:
- Includes are about 10% of the cost.
- Almost all of the cost is in makeSolverManagerFromEnum in BelosSolverFactory.hpp which also contributes about half of the 3.7GB memory for this object.
- Commenting out the code in makeSolverManagerFromEnum and running the sierra build demonstrates this is about 4.2% of the total build time.

Currently looking into some of the other top objects to get a sense of where the times come from. Some are similar reasons. Then will do further analysis of the data collected and consider tools like include what you use, templight, and method changes (such as #354).

**Comment by bartlettroscoe** [comment]
Just cleaning up the includes will likely only have minimal impact without also doing some of other stories in the epic https://github.com/trilinos/Trilinos/milestone/22.  The big ones will likely be a combination of  #1388 and #354 and just generally using forward declarations more and hiding implementation details as much as possible to reduce the size of translation units.

**Comment by mhoemmen** [comment]
@MicheldeMessieres May I ask some questions about this "sierra build"?

  1. Does it turn ETI OFF?
  2. Does it build Trilinos' tests and/or examples?

For reproducibility, could you please post the exact build configuration and GCC and MPI versions?  Thanks!

**Comment by mhoemmen** [comment]
Regarding Belos' solver factory: Turning on ETI would help the Tpetra version, but not the Epetra version.  The main issue may be that Belos itself needs to do ETI or the equivalent ("prebuilding") for its solvers.

**Comment by bartlettroscoe** [comment]
> The main issue may be that Belos itself needs to do ETI or the equivalent ("prebuilding") for its solvers.

That is #1388.

**Comment by MicheldeMessieres** [comment]
@mhoemmen Below are some notes and attachments to clarify my current working state.

I setup this build derived from ctest_linux_nightly_generic_sierra.cmake. Still not sure what would be the best 'test' case so welcome advice on what's most useful as a reference run build - originally I was just running up to muelu but looking further seems potentially useful to keep it in perspective.

ETI was on and tests/examples were off.

Attached is sierra.txt which is the exact cmake config script I used.

[sierra.txt](https://github.com/trilinos/Trilinos/files/1533223/sierra.txt)

And for completeness, this is what my configure output ignores currently which I didn't address yet:

```
  Manually-specified variables were not used by the project:

    Amesos2_CONFIGURE_OPTIONS_FILE
    METIS_INCLUDE_DIRS
    METIS_LIBRARY_DIRS
    METIS_LIBRARY_NAMES
    NOX_ENABLE_EPETRA
```

When running the build I had created time-gcc and time-g++ to create the results.txt log.
They are each files defines like this (something I pulled from https://stackoverflow.com/questions/5962285/cmake-compilation-statistics)

time-gcc
{ /contrib/gcc-4.8.5/bin/gcc -ftime-report "$@"; } 2> >(cat <(echo "/gcc $@") - >> /scr/demessie/trilinos/build/trilinosrepo/serMueLu/results.txt)

time-g++
{ /contrib/gcc-4.8.5/bin/g++ -ftime-report "$@"; } 2> >(cat <(echo "/g++ $@") - >> /scr/demessie/trilinos/build/trilinosrepo/serMueLu/results.txt)

Also for reference here is an example of a results.txt output from running the build:
[results.txt](https://github.com/trilinos/Trilinos/files/1533224/results.txt)

After analysis, the results are sorted in order of build time:
[results_sorted.txt](https://github.com/trilinos/Trilinos/files/1533230/results_sorted.txt)

The time-report categories can also be summed and sorted in order. I gave percents relative to total and there is overlap. Not sure if I can make much use of this:
[categories_sorted.txt](https://github.com/trilinos/Trilinos/files/1533228/categories_sorted.txt)

Note my total build times referenced above are the sum of usr+sys times from the log, not the wall clock time for the whole build, though that is similar.

So perhaps working on #1388 with Belos would be a good next step.

**Comment by bartlettroscoe** [comment]
> ETI was on and tests/examples were off.

The problem with not enabling tests/examples is that if templated code only uses implicit template instantiation, then much of that code may never get instantiated if tests and examples are not enabled.  The only instantiation you would get is by downstream packages that use ETI and ETI is turned on.  But if downstream packages are templated and don't use ETI, then this whole chain of code will never get instantiated (and therefore you will never see any build cost for them).

**Comment by MicheldeMessieres** [comment]
@bartlettroscoe Thanks I'll make tests/examples on standard for my test runs from now on.
