### ISSUE TITLE
Kokkos:   ‘bit_scan_reverse’ is not a member

### ISSUE THREAD

**Issue by dridzal** [trilinos/Trilinos#3510]
@trilinos/kokkos 

## Current Behavior
```
/home/dridzal/development/SYNC-PR/trilinos-fork/Trilinos/packages/kokkos/core/src/impl/Kokkos_spinwait.cpp: In function ‘void {anonymous}::kokkos_internal_yield(unsig$
/home/dridzal/development/SYNC-PR/trilinos-fork/Trilinos/packages/kokkos/core/src/impl/Kokkos_spinwait.cpp:70:15: error: ‘bit_scan_reverse’ is not a member of ‘Kokkos$
       switch (Kokkos::Impl::bit_scan_reverse((i >> 2)+1u)) {
```

## Expectations
Trilinos should build.

## Motivation and Context
Can't sync ROL and Trilinos until this is fixed.

## Steps to Reproduce
Build Trilinos using the default SEMS checkin-test (pre-push) environment.

## Your Environment
Default SEMS checkin-test environment.

**Comment by dridzal** [comment]
I don't get this error with my local build, only with the default pre-push testing environment.  I don't use OpenMP with my local build, and OpenMP seems to be the default for the pre-push testing environment.  So, this may also be a configuration issue.  Adding @trilinos/framework @bartlettroscoe to the conversation.

**Comment by bartlettroscoe** [comment]
@dridzal, the post-push CI build shown [here](https://testing-vm.sandia.gov/cdash-dev-view/index.php?project=Trilinos&filtercount=4&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Linux-GCC-4.8.4-MPI_RELEASE_DEBUG_SHARED_PT_OPENMP_CI&field2=groupname&compare2=61&value2=Continuous&field3=buildstarttime&compare3=84&value3=now&field4=buildstarttime&compare4=83&value4=8%20weeks%20ago) is clean so either the checkin-test-sems.sh script is not consistent with the post-push CI build or there is something else going on.

How can I try to reproduce this myself on my own COE RHEL6 machine?

**Comment by dridzal** [comment]
I'm not sure ... I just do:
`  ./checkin-test-sems.sh --wipe-clean --enable-packages=ROL --local-do-all`
And I also use a COE RHEL6 machine.  There were a few changes in ROL locally, but this failure is definitely in Kokkos, as shown above.

**Comment by bartlettroscoe** [comment]
@dridzal, I will try to reproduce on my CEE LAN machine with Trilinos 'develop' and report back here.

**Comment by dridzal** [comment]
Thanks, you should be able to do so.  My script does
`  git reset --hard rol-trilinos/develop`
right before calling the script.  The only difference between rol-trilinos/develop and trilinos/develop would be in a few changes in ROL, nothing Kokkos-related.

**Comment by bartlettroscoe** [comment]
@dridzal, I am testing the `rol-trilinos/develop` branch right now and will see what happens.

**Comment by bartlettroscoe** [comment]
@dridzal, I was unable to reproduce this error.  I checked out `rol-trilinos/develop` at commit:

```
commit 675eab1d74dcf3960566d2e4a6d092c1a0aac4cb
Merge: 0a31ad4 a71c453
Author: Denis Ridzal <dridzal@sandia.gov>
Date:   Tue Sep 25 16:39:11 2018 -0600

    Merge remote-tracking branch 'upstream/develop' into develop
```

and ran

```
$ ./checkin-test-sems.sh --enable-all-packages=off --enable-packages=ROL --local-do-all \
 --wipe-clean
```

and it returned a passing build and all passing tests:

```
  100% tests passed, 0 tests failed out of 348
  
  Subproject Time Summary:
  Panzer    = 1893.30 sec*proc (159 tests)
  Piro      = 101.49 sec*proc (13 tests)
  ROL       = 3516.25 sec*proc (176 tests)
  
  Total Test time (real) = 658.55 sec
```

Let's try to figure out what is going on on your machine.

**Comment by etphipp** [comment]
@dridzal, do you possibly have a stale Trilinos or Kokkos checkout?  In the current Trilinos/develop, there is no `bit_scan_reverse` call in that file.  I'm looking at
```
5faeef87a8 (HEAD -> develop, origin/develop) Merge Pull Request #3419 from cgcgcg/Trilinos/rebalancingOutput
```

**Comment by dridzal** [comment]
@etphipp yup, the issue was that several git commands failed prior to running the checkin-test script, which left the source code in a partially updated state.  @bartlettroscoe has helped me update the automated script to prevent this from happening again.  Closing the issue.
