### ISSUE TITLE
Framework: POSIX compatibility of build scripts

### ISSUE THREAD

**Issue by cgcgcg** [trilinos/Trilinos#3515]
@trilinos/framework 

## Expectations
It would be nice if the build scripts would work on all shells, and not just on bash. Examples of things that seem to create trouble are comparisons with `==` instead of `=` and usage of the variable `BASH_SOURCE`.

**Comment by csiefer2** [comment]
Evidently, I'm not the only person who doesn't use bash...

**Comment by jwillenbring** [comment]
@cgcgcg I don't see any scripts that use the BASH_SOURCE variable that are maintained and supported by @trilinos/framework. Can you point to specific scripts?

**Comment by cgcgcg** [comment]
Does this not count?
https://github.com/trilinos/Trilinos/blob/eaed9de438e8b2b21af31701102ebf5f43661a3f/cmake/load_sems_dev_env.sh#L71

**Comment by jwillenbring** [comment]
@cgcgcg That script was developed and is maintained by @bartlettroscoe

**Comment by bartlettroscoe** [comment]
@cgcgcg, sorry, we only support bash.  See the last bullet under "NOTES" at:

* https://github.com/trilinos/Trilinos/wiki/SEMS-Dev-Env

which says:

"This script can really only be used for Linux machines with the SEMS env and sh compatible shells (e.g. `bash`, sorry no `(t)csh` versions are currently available)."

I don't know of any way to write scripts like this that work with bash and (t)csh.

**Comment by cgcgcg** [comment]
@bartlettroscoe I was trying to use zsh, which I believe is sh compatible. I replaced all the "==" in `load_sems_dev_env.sh`, as well as the command to get the script name. The script seems to be working for both zsh and bash. Should I create a PR?

**Comment by bartlettroscoe** [comment]
> Should I create a PR?

@cgcgcg, yes.  Please do and I will test it out.
