### ISSUE TITLE
install gitdist with trilinos install

### ISSUE THREAD

**Issue by rppawlo** [trilinos/Trilinos#3523]
Is there any way we can get gitdist installed into the bin directory during trilinos installs? Might need a configure flag to enable/disable this capability?

@bartlettroscoe 
@bathmatt

**Comment by bartlettroscoe** [comment]
@rppawlo, yes, that should be pretty easy to do.  What should the enable/disable flag be and should it be enabled or disabled by default?

**Comment by rppawlo** [comment]
If it is installing a single file I'd probably enable by default. If it dumps a ton of extra python utility files into bin, then maybe have it off by default? 

Not sure what to call it. Some suggestions:
Trilinos_INSTALL_PythonUtils
Trilinos_INSTALL_Scripts

I wonder if we should just create a new package that just contains the python utility scripts, if we identify a large amount of scripts to install...
Trilinos_ENABLE_PythonUtils
Trilinos_ENABLE_Scripts

**Comment by mhoemmen** [comment]
@trilinos/framework

**Comment by bartlettroscoe** [comment]
> If it is installing a single file I'd probably enable by default. If it dumps a ton of extra python utility files into bin, then maybe have it off by default?

@rppawlo, gitdist is a single self-contained python script.
