### ISSUE TITLE
get atdm builds using the gold linker where it works

### ISSUE THREAD

**Issue by bathmatt** [trilinos/Trilinos#3533]
I noticed that we don't use the gold linker, it is much faster for static libs which we still use often.  Can we swap it over to that?

```
dir-~ (gcc) 29 $ cd Trilinos/Trilinos/cmake/std/atdm/
dir-atdm (gcc) 31 $ find . -type f -exec grep gold {} \;
dir-atdm (gcc) 32 $ 
```

Mutrino/ride/waterman it doesn't work, shiller cee it does.  

@trilinos/<teamName>

## Your Environment

- **Relevant repo SHA1s:**  
- **Relevant configure flags or configure script:**  
- **Operating system and version:**  
- **Compiler and TPL versions:**  

## Related Issues

* Blocks 
* Is blocked by 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of

**Comment by mhoemmen** [comment]
@trilinos/framework
