### ISSUE TITLE
Question about Tpetra::RowMatrixTransposer (was "Tpetra: RowMatrixTransposer::createTranspose not communicating rectangular matrices")

### ISSUE THREAD

**Issue by hcedwar** [trilinos/Trilinos#3535]
Tpetra: RowMatrixTransposer::createTranspose not communicating rectangular matrices.

## Current Behavior

A unit test in a CSCS application @Patrick81 has rectangular sparse matrix with numRow > numCol, first column all 1 and last column all 2.  In serial the transpose is correct.  With two processors the upper right and lower left submatrices are not communicated to their new owning process.

Let:  

- numRow = 22, 
- numCol = 10,
- numProc = 2, 
- P0 owns row [0..11), 
- P1 owns row [11,22), 
- A(0..10,0) = 1  on P0
- A(11..21,0) = 1 on P1
- A(0..10,9) = 2 on P0
- A(11..21,9) = 2 on P1

then RowMatrixTransposer result, AT = A^T

- AT(0,0..10) = 1  on P0
- AT(0,11..21) does not exist
- AT(9,0..10) does not exist
- AT(9,11..21) = 2 on P1

@trilinos/tpetra 

## Definition of Done

New 2+ processor unit test with rectangular row matrix transpose yielding correct result.

**Comment by crtrott** [comment]
Whats the configuration? Backends, compilers, etc.

**Comment by hcedwar** [comment]
This happens when a column map is defined for the original matrix A.
When assignment of the column map is removed then the correct transpose is produced.

**Comment by mhoemmen** [comment]
@hcedwar Could you actually post or send the code for the test?  The distribution of the result might not be what you expect, so the data might be there, just not on the process where you think they might be.

**Comment by crtrott** [comment]
```c++
typedef Tpetra::Operator<>::scalar_type SC;
        typedef Tpetra::Operator<SC>::local_ordinal_type LO;
        typedef Tpetra::Operator<SC, LO>::global_ordinal_type GO;

        typedef Kokkos::Compat::KokkosSerialWrapperNode serial_node;
        typedef serial_node NT;

        typedef Tpetra::CrsMatrix<SC, LO, GO, NT>             crs_mat_type;
        typedef Tpetra::Map<LO, GO, NT>                       map_type;

        auto comm = Tpetra::DefaultPlatform::getDefaultPlatform().getComm();

        auto rows_local = 5;
        auto cols_local = 11;
        auto index_base = 0;

        auto rows_global = mpi_world_size() * rows_local;
        auto cols_global = mpi_world_size() * cols_local;


        auto domain_map = Teuchos::rcp(new map_type(cols_global, cols_local, index_base, comm));
        auto row_map = Teuchos::rcp(new map_type(rows_global, rows_local, index_base, comm));
        auto col_map = Teuchos::rcp(new map_type(cols_global, index_base, comm, Tpetra::LocallyReplicated));

        // auto mat = Teuchos::rcp(new crs_mat_type(row_map, col_map, 2, Tpetra::DynamicProfile));
        auto mat = Teuchos::rcp(new crs_mat_type(row_map, 2, Tpetra::DynamicProfile));

        auto begin_i = row_map->getMinGlobalIndex();
        auto end_i   = row_map->getMaxGlobalIndex() + 1;

        GO first_col = 0;
        GO last_col  = cols_global-1;

        for(GO i = begin_i; i < end_i; ++i) {
            double value = 1.;
            mat->insertGlobalValues(i, 1, &value, &first_col);

            value = 2.;
            mat->insertGlobalValues(i, 1, &value, &last_col);
        }

        mat->fillComplete(domain_map, row_map);

        Tpetra::RowMatrixTransposer<double, LO, GO, NT> transposer(mat);
        auto mat_t = transposer.createTranspose();

        auto out = Teuchos::getFancyOStream(Teuchos::rcpFromRef(std::cout));

        std::cout << "---------------------------------" << std::endl;
        mat->describe(*out, Teuchos::EVerbosityLevel::VERB_EXTREME);
        std::cout << "---------------------------------" << std::endl;
        mat_t->describe(*out, Teuchos::EVerbosityLevel::VERB_EXTREME);
```

They said this works the way it is right now, but if the column map gets specified (commented out) it doesn't do what they think it should do.

**Comment by mhoemmen** [comment]
The column Map as specified is wrong.  You can tell because `insertGlobalValues` is inserting into columns that are not owned on some calling processes. 

Best practice in this case would be not to specify the column Map.

There are some issues with this code overspecifying template parameters, not matching template parameters (using nondefault vs. default values), using the deprecated DefaultPlatform class (just include `Tpetra_Core.hpp` and use `Tpetra::getDefaultComm()`), and calling the range Map the `row_map`.  I'll ignore those for now.

**Comment by mhoemmen** [comment]
@hcedwar @crtrott

**Comment by Patrick81** [comment]
Thanks for the reply. The code was hacked in few minutes just to provide an example with tpetra only.

Additionally:
The transpose operation for the rectangular case does not work if I do not specify the domain_map.

Best regards

**Comment by mhoemmen** [comment]
Here is a rewrite of the code using better Tpetra style:
```c++
#include "Tpetra_Core.hpp"

void some_function_whatever_you_like_to_call_it () {
  using LO = Tpetra::Operator<double>::local_ordinal_type;
  using GO = Tpetra::Operator<double>::global_ordinal_type;
  using crs_mat_type = Tpetra::CrsMatrix<double>;
  using map_type = Tpetra::Map<>;

  // This presumes that MPI has been initialized.  See Tpetra::ScopeGuard.
  auto comm = Tpetra::getDefaultComm();

  const LO rows_local = 5;
  const LO cols_local = 11;
  const GO index_base = 0;

  const GO rows_global = mpi_world_size() * rows_local;
  const GO cols_global = mpi_world_size() * cols_local;

  auto domain_map = Teuchos::rcp(new map_type(cols_global, cols_local, index_base, comm));
  auto row_map = Teuchos::rcp(new map_type(rows_global, rows_local, index_base, comm));
  auto range_map = row_map;

  auto mat = Teuchos::rcp (new crs_mat_type (row_map, 2, Tpetra::DynamicProfile));

  GO first_col = 0;
  GO last_col  = cols_global-1;

  for (LO lcl_row = 0; lcl_row < rows_local; ++lcl_row) {
    double value = 1.;
    mat->insertGlobalValues(i, 1, &value, &first_col);
    value = 2.;
    mat->insertGlobalValues(i, 1, &value, &last_col);
  }

  mat->fillComplete(domain_map, range_map);
  Tpetra::RowMatrixTransposer<double> transposer(mat);
  auto mat_t = transposer.createTranspose();
```

**Comment by mhoemmen** [comment]
@Patrick81 wrote:
> The transpose operation for the rectangular case does not work if I do not specify the domain_map.

This is correct behavior.  The Tpetra tutorial (see `Trilinos/tpetra/core/src/example/Lesson*`) explains that you must give the domain and range Map to fillComplete if the matrix is not square, or if the domain and range Maps are not both the same as the row Map.

**Comment by crtrott** [comment]
Thanks Mark :-)

**Comment by mhoemmen** [comment]
Here's a Tpetra documentation page with links to the Tpetra tutorials: https://trilinos.org/docs/dev/packages/tpetra/doc/html/index.html

**Comment by Patrick81** [comment]
Perfect thanks!

**Comment by mhoemmen** [comment]
Gladly!  If you need to reach me on short notice, I think @hcedwar knows my phone number.

**Comment by crtrott** [comment]
I am in contact with them too. But I think they are done now (its after 6 in Lugano)

**Comment by mhoemmen** [comment]
@crtrott Thanks!
