### ISSUE TITLE
Selectively use the pImpl idiom to reduce Trilinos build and rebuild times

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#354]
The selective usage of the [pImpl idiom](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&sqi=2&ved=0ahUKEwjm8Krc-tfMAhUX0GMKHQJ9BrgQFggcMAA&url=http%3A%2F%2Fc2.com%2Fcgi%2Fwiki%3FPimplIdiom&usg=AFQjCNHM-qnOOCUddXU2YBNGJYIux0hYdw&sig2=r2MKmj1MmDq8n7-cuHhY3Q&bvm=bv.122129774,d.cGc) can dramatically reduce build times for C++.  We could use this in any class where inline functions that see the implementation are not needed.  The overhead for most classes/objects is very low.

CC: @mhoemmen

**Comment by mhoemmen** [comment]
btw this doesn't work quite as well for classes with template parameters.  Any of various ETI (explicit template instantiation) approaches can help with such classes.

**Comment by bartlettroscoe** [comment]
> btw this doesn't work quite as well for classes with template parameters. Any of various ETI (explicit template instantiation) approaches can help with such classes.

Using ETI and putting all of the implementation details and lower-level includes into the XXX_def.hpp file should give the exact same advantages as using the pImpl idiom with non-templated code.   (But amazingly I can't find a StackOverflow question that explains this but I can guaranteed that it will work correctly using ETI with separate XXX_decl.hpp and XXX_def.hpp files.)  If you don't use ETI then obviously you don't get any advantages out of using the pImpl idiom with templated code.  But since ETI should become the default for Trilinos, we should get the full benefit from using this idiom.
