### ISSUE TITLE
ShyLU_DD tests build failure in targeted CUDA PR bulid Trilinos-atdm-white-ride-cuda-9.2-release-debug-pt starting 10/2/2018

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#3541]
CC: @trilinos/shylu, @srajama1 (Trilinos Linear Solvers Product Area Lead), @fryeguy52, @roeverf, @searhein 

## Description

Starting today, there are two build errors for the ShyLU_DD package in the build `Trilinos-atdm-white-ride-cuda-9.2-release-debug-pt ` on 'white' and 'ride' as shown [here](https://testing.sandia.gov/cdash-dev-view/viewBuildError.php?buildid=3998259) which shows build errors starting with:

```
/home/jenkins/white/workspace/Trilinos-atdm-white-ride-cuda-9.2-release-debug-pt/SRC_AND_BUILD/Trilinos/packages/shylu/shylu_dd/frosch/test/Thyra_Tpetra/main.cpp(104): error: "EpetraNode" is ambiguous
```

ShyLU_DD was building just fine yesterday in this build as shown [here](https://testing.sandia.gov/cdash-dev-view/viewBuildError.php?type=0&buildid=3995410).

Looking at the commits pulled today shown [here](https://testing.sandia.gov/cdash-dev-view/viewNotes.php?buildid=3998221#!#note6), it seems likely this might have been caused by one of the commits from @roeverf  to the ShyLU_DD package merged in the PR #3472 merged to 'develop' by @searhein on 10/1/2018 as shown [here](https://github.com/trilinos/Trilinos/pull/3472#event-1876847991).

This is an important build because we are targeting this build on 'white' and 'ride' as a Trilinos PR testing build (see #2464 ).

## Current Status on CDash

The current status of `ShyLU_DD` in this build and tests over the last few days can be seen in [this CDash query](https://testing.sandia.gov/cdash-dev-view/index.php?project=Trilinos&date=2019-01-22&filtercount=4&showfilters=1&filtercombine=and&field1=subprojects&compare1=93&value1=ShyLU_DD&field2=buildname&compare2=61&value2=Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-release-debug-pt&field3=site&compare3=61&value3=ride&field4=buildstarttime&compare4=83&value4=1%20week%20ago).

## Steps to reproduce

One should be able to reproduce these build errors on either 'white' or 'ride' by cloning the Trilinos git repo, checking out the 'develop' branch, creating a build directory, and then doing:

```
$ cd <some_build_dir>/

$ source $TRILINOS_DIR/cmake/std/atdm/load-env.sh cuda-9.2-release-debug

$ cmake \
  -GNinja \
  -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnvAllPtPackages.cmake \
  -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_ShyLU_DD=ON \
  $TRILINOS_DIR

$ make NP=16
```

**Comment by bartlettroscoe** [comment]
CC: @trilinos/framework 

@srajama1, this would be a blocker to adding a CUDA build to the Trilinos PR testing (see #2464).  For that reason it would be good to fix this sooner rather than later.

**Comment by srajama1** [comment]
@bartlettroscoe We will take care of this

**Comment by bartlettroscoe** [comment]
CC: @trilinos/framework 

@srajama1, 

ShyLU_DD is not currently not enabled in any of the app ATDM builds of Trilinos so we could disable ShyLU_DD from a Trilinos CUDA PR build and not loose anything (w.r.t. to ATDM).  Therefore, it is up to you if you want to include ShyLU_DD in Trilinos PR testing with a CUDA build.

**Comment by srajama1** [comment]
@bartlettroscoe : That was my first thought to say disable it in ATDM build, but if this is going to be the basis for Trilinos PR testing I would like to have ShyLU_DD part of it. This just started yesterday and I have contacted @searhein offline. We will take care of it. We have waited this long to get a CUDA build setup, let us do it the right way (all PR tested packages working).

**Comment by bartlettroscoe** [comment]
@srajama1 it occurred to me that what we should do is stand up a Trilinos CUDA PR build right now for what currently works and then keep this "Specialized" build running that enables everything.  Then as we fix things in this "Speicalized" build, we can enable them in the Trilinos CUDA PR build.  If we had done that before yesterday, these ShyLU_DD tests would have never been allowed to fail because the CUDA PR build would have stopped the merged since ShyLU_DD was clean before today.

**Comment by bartlettroscoe** [comment]
Any updates on fixing these builds errors?  Looks like they fixed the TrilinosCouplings build failures for this build.

**Comment by bartlettroscoe** [comment]
@srajama1 said:

> @bartlettroscoe We will take care of this

FYI:

**Comment by srajama1** [comment]
This is on my list, just not being able to get to it.

**Comment by srajama1** [comment]
Among other things PR #3947 should fix this. Let us see.

**Comment by srajama1** [comment]
Can someone please check if this is still failing ?

**Comment by bartlettroscoe** [comment]
https://testing.sandia.gov/cdash-dev-view/index.php?project=Trilinos&parentid=4409660

**Comment by bartlettroscoe** [comment]
Actually more errors than before.  And we are getting a bunch of failures on 'white':

* https://testing.sandia.gov/cdash-dev-view/index.php?project=Trilinos&parentid=4410122

Don't know why.

**Comment by searhein** [comment]
@bartlettroscoe I just merged PR #4204. How can I check if this resolved (part of) the errors? Thanks!

**Comment by bartlettroscoe** [comment]
> @bartlettroscoe I just merged PR #4204. How can I check if this resolved (part of) the errors? Thanks!

@searhein, I added the new standard section "Current Status on CDash" [above](https://github.com/trilinos/Trilinos/issues/3541#issue-365960768) with a link that you can click at any time to see the current and recent status of `ShyLU_DD`.  All new ATDM Trilinos GitHub issues will have that section so that Trilinos developers can check CDash whenever they want.  If you click that link later tomorrow, you should see the impact of your change.

**Comment by srajama1** [comment]
I don't think @searhein has access to the CDash links. I will check tomorrow and let you know.

**Comment by bartlettroscoe** [comment]
@srajama1 said:

> I don't think @searhein has access to the CDash links. I will check tomorrow and let you know.

The `testing.sandia.gov/cdash/` site is completely open to the internet.

**Comment by srajama1** [comment]
@bartlettroscoe Thanks ! I didn't know that.

**Comment by bartlettroscoe** [comment]
FYI: The build today shown [here](https://testing.sandia.gov/cdash-dev-view/index.php?project=Trilinos&parentid=4447521) shows the ShyLU_DD build errors gone but there are still 3 failing tests shown [here](https://testing.sandia.gov/cdash-dev-view/viewTest.php?onlyfailed&buildid=4447559).

**Comment by searhein** [comment]
@bartlettroscoe Thank you, for adding the section "Current Status on CDash". This is really helpful for working on the errors. I hope my last PR fixed some more of the errors.

**Comment by bartlettroscoe** [comment]
CC: @fryeguy52 

@searhein and @srajama1,

Looks like ShyLU_DD is not 100% clean in the build `Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-release-debug-pt` shown [here](https://testing.sandia.gov/cdash-dev-view/index.php?project=Trilinos&parentid=4451742) this morning.

Closing this issue as complete!

**Comment by srajama1** [comment]
@bartlettroscoe May be you meant "is 100% clean" based on the fact you closed the issue ?

**Comment by bartlettroscoe** [comment]
@srajama1 asked:

> May be you meant "is 100% clean" based on the fact you closed the issue ?

It is closed.  See [above](https://github.com/trilinos/Trilinos/issues/3541#issuecomment-457225544) :-)

(And I fixed fixed the typos in that comment.)
