### ISSUE TITLE
ROL tests failing in targeted CUDA PR build Trilinos-atdm-white-ride-cuda-9.2-release-debug-pt

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#3543]
CC: @trilinos/rol , @rppawlo (Trilinos Nonlinear Solvers Product Area Lead)

## Description

The ROL package has 66 failing tests in the build `Trilinos-atdm-white-ride-cuda-9.2-release-debug-pt ` on 'white' and 'ride' as shown [here](https://testing.sandia.gov/cdash-dev-view/viewTest.php?onlyfailed&buildid=3998251) which shows the failing tests:

* ROL_example_PDE-OPT_0ld_adv-diff-react_example_01_MPI_4
* ROL_example_PDE-OPT_0ld_adv-diff-react_example_02_MPI_4
* ROL_example_PDE-OPT_0ld_poisson_example_01_MPI_4
* ROL_example_PDE-OPT_0ld_stefan-boltzmann_example_03_MPI_4
* ROL_example_PDE-OPT_navier-stokes_example_01_MPI_4
* ROL_example_PDE-OPT_navier-stokes_example_02_MPI_4
* ROL_example_PDE-OPT_nonlinear-elliptic_example_01_MPI_4
* ROL_example_PDE-OPT_nonlinear-elliptic_example_02_MPI_4
* ROL_example_PDE-OPT_obstacle_example_01_MPI_4
* ROL_example_PDE-OPT_stefan-boltzmann_example_01_MPI_4
* ROL_example_PDE-OPT_stefan-boltzmann_example_03_MPI_4
* ROL_example_PDE-OPT_topo-opt_poisson_example_01_MPI_4
* ROL_example_tempus_example_parabolic_modeleval_MPI_1
* ROL_example_tempus_example_parabolic_thyravec_MPI_1
* ROL_test_elementwise_TpetraMultiVector_MPI_4

The first failing test `ROL_example_PDE-OPT_0ld_adv-diff-react_example_01_MPI_4` with detailed output shown [here](https://testing.sandia.gov/cdash-dev-view/testDetails.php?test=55725358&build=3998251) shows:

```
Total number of processors: 4
Number of nodes = 1089
Number of cells = 1024
Number of edges = 2112
Cell offsets across processors: {0, 256, 512, 768}
terminate called after throwing an instance of 'std::runtime_error'
terminate called after throwing an instance of 'std::runtime_error'
  what():  cudaGetLastError() error( cudaErrorIllegalAddress): an illegal memory access was encountered /home/jenkins/white/workspace/Trilinos-atdm-white-ride-cuda-9.2-release-debug-pt/SRC_AND_BUILD/Trilinos/packages/kokkos/core/src/Cuda/Kokkos_CudaExec.hpp:401
Traceback functionality not available
  what():  cudaGetLastError() error( cudaErrorIllegalAddress): an illegal memory access was encountered /home/jenkins/white/workspace/Trilinos-atdm-white-ride-cuda-9.2-release-debug-pt/SRC_AND_BUILD/Trilinos/packages/kokkos/core/src/Cuda/Kokkos_CudaExec.hpp:401
Traceback functionality not available


[white27:11203] *** Process received signal ***
[white27:11204] *** Process received signal ***
[white27:11203] Signal: Aborted (6)
[white27:11203] Signal code:  (-6)
[white27:11204] Signal: Aborted (6)
[white27:11204] Signal code:  (-6)
[white27:11203] [ 0] [white27:11204] [ 0] [0x3fff90070478]
[white27:11203] [ 1] [0x3fffa3f00478]
...
```

Randomly looking at the output of several of the other tests I looked at all show errors like shown above.

This is an important build because we are targeting this build on 'white' and 'ride' as a Trilinos PR testing build (see #2464 ).  Also, SPARC uses ROL and as part of https://software-sandbox.sandia.gov/jira/browse/TRIL-212 we are about to update the ATDM Trilinos configuration to test ROL on many platforms (including CUDA builds) so it is critical to get these tests cleaned up for ATDM.

## Steps to reproduce

One should be able to reproduce these build errors on either 'white' or 'ride' by cloning the Trilinos git repo, checking out the 'develop' branch, creating a build directory, and then doing:

```
$ cd <some_build_dir>/

$ source $TRILINOS_DIR/cmake/std/atdm/load-env.sh cuda-9.2-release-debug

$ cmake \
  -GNinja \
  -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
  -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_ROL=ON \
  $TRILINOS_DIR

$ make NP=16

$ bsub -x -Is -q rhel7F -n 16 ctest -j16
```

**Comment by bartlettroscoe** [comment]
@dridzal,

When we merge in the SPARC updates for that ATDM Trilinos build as part of https://software-sandbox.sandia.gov/jira/browse/TRIL-212, ROL will start getting tested on ATDM platforms.  And there will be a CUDA build running with ROL enabled (hopefully) within the next week or so so it is important to address these test failures one way or the other at some point soon.

**Comment by dridzal** [comment]
@bartlettroscoe ,

I hope that this is a simple bug in ROL's TpetraMultiVector.  This is reported as the last failing test, but all other failing tests use this functionality.  Specifically, this may have to do with elementwise reductions, so I'll ask @gregvw to look into it.  We have to revisit our use of Tpetra data structures anyway, and take care of some deprecated functionality (as suggested by @mhoemmen a few months ago in #3146).

**Comment by etphipp** [comment]
The elementwise interface for the ROL Tpetra::MultiVector adaptor will not work on CUDA, and is likely the source of these errors.

**Comment by dridzal** [comment]
@etphipp thanks, @gregvw will look into it.

**Comment by bartlettroscoe** [comment]
@dridzal, any plans to fix this in the near future?  Just wondering because we want to promote these new 'cee-rhel6' build to help support SPARC.

**Comment by bartlettroscoe** [comment]
> @dridzal, any plans to fix this in the near future? Just wondering because we want to promote these new 'cee-rhel6' build to help support SPARC.

Sorry, I mean this will become an issue when we get the 'cee-rhel6' CUDA build running for SPARC.  These failures will almost certainly be seen in that build too.

**Comment by dridzal** [comment]
This will require a bit of a redesign of our linear algebra interface.  We are working on it.  What’s the deadline?

**Comment by bartlettroscoe** [comment]
> This will require a bit of a redesign of our linear algebra interface. We are working on it. What’s the deadline?

@dridzal, if it will take more than a couple of weeks, we should likely temporary disable these tests for now.  There in no value is running tests day after day knowing/expecting them to fail.  That just wastes CPU resources and clutters up the dashboard.  Keeping this issue open with "Disabled Tests" should be enough of a reminder that this still needs to be fixed.  In fact, we will be setting up automated emails that list out open ATDM Trilinos issues to people on a regular basis here at some point.

**Comment by dridzal** [comment]
Can you disable them only for this build (if we don’t complete the redesign in the next two weeks)? We can’t lose this testing altogether.

**Comment by rppawlo** [comment]
have these been disabled yet?

**Comment by bartlettroscoe** [comment]
@rppawlo 

> have these been disabled yet?

No, they are still failing (see [here](https://testing.sandia.gov/cdash-dev-view/viewTest.php?onlyfailed&buildid=4301219)).

NOTE: As soon as we get a CUDA build going for the SPARC configuration of Trilinos (see https://sems-atlassian-son.sandia.gov/jira/browse/TRIL-221) then these ROL tests will be failing there too.  At that point we will need to fix them or disable them.

**Comment by dridzal** [comment]
We are working on a new static polymorphism implementation for vectors.  This will enable CUDA builds.  What’s your timeline?

**Comment by rppawlo** [comment]
@dridzal  and @bartlettroscoe - what is the status on this ticket?

**Comment by bartlettroscoe** [comment]
CC: @trilinos/framework and @rppawlo 

Eleven of these 13 tests are disabled in the current Trilinos PR build using:

```
set (ROL_example_PDE-OPT_0ld_adv-diff-react_example_01_MPI_4_DISABLE ON CACHE BOOL "Temporary disable for CUDA PR testing")
set (ROL_example_PDE-OPT_0ld_adv-diff-react_example_02_MPI_4_DISABLE ON CACHE BOOL "Temporary disable for CUDA PR testing")
set (ROL_example_PDE-OPT_0ld_poisson_example_01_MPI_4_DISABLE ON CACHE BOOL "Temporary disable for CUDA PR testing")
set (ROL_example_PDE-OPT_0ld_stefan-boltzmann_example_03_MPI_4_DISABLE ON CACHE BOOL "Temporary disable for CUDA PR testing")
set (ROL_example_PDE-OPT_navier-stokes_example_01_MPI_4_DISABLE ON CACHE BOOL "Temporary disable for CUDA PR testing")
set (ROL_example_PDE-OPT_navier-stokes_example_02_MPI_4_DISABLE ON CACHE BOOL "Temporary disable for CUDA PR testing")
set (ROL_example_PDE-OPT_nonlinear-elliptic_example_01_MPI_4_DISABLE ON CACHE BOOL "Temporary disable for CUDA PR testing")
set (ROL_example_PDE-OPT_nonlinear-elliptic_example_02_MPI_4_DISABLE ON CACHE BOOL "Temporary disable for CUDA PR testing")
set (ROL_example_PDE-OPT_obstacle_example_01_MPI_4_DISABLE ON CACHE BOOL "Temporary disable for CUDA PR testing")
set (ROL_example_PDE-OPT_topo-opt_poisson_example_01_MPI_4_DISABLE ON CACHE BOOL "Temporary disable for CUDA PR testing")
set (ROL_test_elementwise_TpetraMultiVector_MPI_4_DISABLE ON CACHE BOOL "Temporary disable for CUDA PR testing")
```

Note sure  about the other two tests.  This might be due to differences in the Trilinos PR configuration and this more complete CUDA configuration running on 'ride'.  (I will try to fix the Trilinos PR configuration later this week.)

Otherwise, these are still failing as shown today [here](https://testing.sandia.gov/cdash-dev-view/index.php?project=Trilinos&parentid=4665175).

**Comment by dridzal** [comment]
All tests using elementwise operations (in this case TpetraMultiVector) can be disabled for CUDA builds.  I'm actually surprised that some of them are passing.  @gregvw and I are working on a ROL refactor to address this once and for all.  @gregvw has a new static polymorphism vector prototype that works, we now need to propagate the changes to all of ROL and the dependent codes.  If all goes well, we may be able to complete the task in 4-6 weeks.

**Comment by bartlettroscoe** [comment]
@dridzal said:

> All tests using elementwise operations (in this case TpetraMultiVector) can be disabled for CUDA builds

That is really a decision that ROL and the ROL customers need to make.  Is ROL not supported for CUDA yet?  What are customers like Sierra and SPARC doing on CUDA builds?   Seems like it might be good to run some ROL tests just to make sure the ROL builds work for CUDA, even if it does not run fast, no?  Why not just disable all of the more expensive tests?  Not hard to see which ones these are.

>  @gregvw has a new static polymorphism vector prototype that works, we now need to propagate the changes to all of ROL and the dependent codes. If all goes well, we may be able to complete the task in 4-6 weeks.

Excellent!

**Comment by dridzal** [comment]
@bartlettroscoe 
It's not that ROL won't work for CUDA.  It has already been used in this capacity.  There are some more sophisticated parts of ROL, probably not used by the projects you mentioned, that are currently problematic.  The goal is to have *all* of ROL working in this setting, so that in the future these projects/codes can use more advanced features.

**Comment by bartlettroscoe** [comment]
@dridzal said

> It's not that ROL won't work for CUDA. It has already been used in this capacity.

Okay, so ROL should still be tested with CUDA and all of the tests that pass and are not otherwise problematic should be kept running in PR testing, right?

**Comment by dridzal** [comment]
Yes, correct.

**Comment by bartlettroscoe** [comment]
Defects with Primary tested code not currently used (or being tested) by ATDM is not really an ATDM issue so I am removing the "client: ATDM" label to get this off our list of active issues.
