### ISSUE TITLE
STK tests failing in targeted CUDA PR builds Trilinos-atdm-white-ride-cuda-9.2-release-debug-pt

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#3544]
CC: @trilinos/stk , @kddevin (Trilinos Data Services Product Area Lead)

## Description

The STK package has 3 failing tests in the build `Trilinos-atdm-white-ride-cuda-9.2-release-debug-pt ` on 'white' and 'ride' as shown [here](https://testing.sandia.gov/cdash-dev-view/viewTest.php?onlyfailed&buildid=3998255) which shows the failing tests:

* STKUnit_tests_stk_mesh_unit_tests_MPI_4
* STKUnit_tests_stk_ngp_unit_tests_MPI_4
* STKUnit_tests_stk_tools_unit_tests_MPI_4

The test `STKUnit_tests_stk_mesh_unit_tests_MPI_4` has output shown [here](https://testing.sandia.gov/cdash-dev-view/testDetails.php?test=55725258&build=3998255) and shows the failures:

```
*** Starting test BulkData.testFieldComm from UnitTestBulkData.cpp:2177
[white27:4867] *** An error occurred in MPI_Neighbor_alltoallv
[white27:4867] *** reported by process [2079326209,2]
[white27:4867] *** on communicator MPI COMMUNICATOR 3 CREATE FROM 0
[white27:4867] *** MPI_ERR_ARG: invalid argument of some other kind
[white27:4867] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
[white27:4867] ***    and potentially your MPI job)
[white27:04859] 1 more process has sent help message help-mpi-errors.txt / mpi_errors_are_fatal
[white27:04859] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
```

The test output for the test `STKUnit_tests_stk_ngp_unit_tests_MPI_4` shown [here](https://testing.sandia.gov/cdash-dev-view/testDetails.php?test=55725259&build=3998255) shows:

```
*** Starting test NGP_Kokkos.bucket0 from KokkosBulkDataBucketCentroidCalculation.cpp:230
[       OK ] NGP_Kokkos.bucket0 (7002379918061956201 ms)
*** Starting test NGP_Kokkos.calculate_centroid_field_with_gather_on_device_bucket from KokkosBulkDataBucketCentroidCalculation.cpp:235
[white27:4914] *** An error occurred in MPI_Neighbor_alltoallv
[white27:4914] *** reported by process [2048983041,2]
[white27:4914] *** on communicator MPI COMMUNICATOR 3 CREATE FROM 0
[white27:4914] *** MPI_ERR_ARG: invalid argument of some other kind
[white27:4914] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
[white27:4914] ***    and potentially your MPI job)
[white27:04906] 3 more processes have sent help message help-mpi-errors.txt / mpi_errors_are_fatal
[white27:04906] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
```

Finally, the output for the test `STKUnit_tests_stk_tools_unit_tests_MPI_4` shown [here](https://testing.sandia.gov/cdash-dev-view/testDetails.php?test=55725262&build=3998255) shows:

```
*** Starting test CloningMesh.cloningBulkDataNoAura_selector from UnitTestBulkDataClone.cpp:418
[       OK ] CloningMesh.cloningBulkDataNoAura_selector (0 ms)
*** Starting test CloningMesh.cloningBulkDataWithAura_selector from UnitTestBulkDataClone.cpp:427
[white27:5053] *** An error occurred in MPI_Neighbor_alltoallv
[white27:5053] *** reported by process [2059272193,2]
[white27:5053] *** on communicator MPI COMMUNICATOR 3 CREATE FROM 0
[white27:5053] *** MPI_ERR_ARG: invalid argument of some other kind
[white27:5053] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
[white27:5053] ***    and potentially your MPI job)
[white27:05045] 3 more processes have sent help message help-mpi-errors.txt / mpi_errors_are_fatal
[white27:05045] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
```

Therefore, it seems all of these tests are failing due to errors in the function `MPI_Neighbor_alltoallv()`.

This is an important build because we are targeting this build on 'white' and 'ride' as a Trilinos PR testing build (see #2464 ).  Also, EMPIRE and SPARC uses STK.  However, SPARC and EMPIRE do not enable the `STKUnit_tests` packages that has these tests.  Therefore, from the ATDM perspective, we could disable these tests for ATDM.  But since one would assume theses tests check the correct functioning of STK it would be good to get these fixed.

## Steps to reproduce

One should be able to reproduce these build errors on either 'white' or 'ride' by cloning the Trilinos git repo, checking out the 'develop' branch, creating a build directory, and then doing:

```
$ cd <some_build_dir>/

$ source $TRILINOS_DIR/cmake/std/atdm/load-env.sh cuda-9.2-release-debug

$ cmake \
  -GNinja \
  -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnvAllPtPackages.cmake \
  -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_STK=ON \
  $TRILINOS_DIR

$ make NP=16

$ bsub -x -Is -q rhel7F -n 16 ctest -j16
```

**Comment by bartlettroscoe** [comment]
CC: @mhoemmen 

@kddevin, I think these tests could be disabled in this build and it would likely not provide much of a risk to ATDM.  But you might wan to task the STK developers if whey want to fix these tests or not.

@micahahoward and @bathmatt, also, it would be up to you if you want these tests to be run as part of a Trilinos CUDA PR build.  If you don't think that these tests are important to run and pass using CUDA to protect SPARC and EMPIRE, then we can disable them in this build.

**Comment by alanw0** [comment]
@bartlettroscoe what is the MPI implementation being used here? We have had some issues with these "Neighbor" functions on certain MPI implementations. I added an ifdef that could avoid the Neighbor functions in certain circumstances so a slight modification of that might address this.

**Comment by bartlettroscoe** [comment]
> What is the MPI implementation being used here? We have had some issues with these "Neighbor" functions on certain MPI implementations. I added an ifdef that could avoid the Neighbor functions in certain circumstances so a slight modification of that might address this.

@alanw0, as shown in the configure output [here](https://testing.sandia.gov/cdash-dev-view/viewConfigure.php?buildid=3998255) which shows:

```
-- Check for working CXX compiler: /home/projects/ppc64le-pwr8-nvidia/openmpi/2.1.2/gcc/7.2.0/cuda/9.2.88/bin/mpicxx
-- Check for working CXX compiler: /home/projects/ppc64le-pwr8-nvidia/openmpi/2.1.2/gcc/7.2.0/cuda/9.2.88/bin/mpicxx -- works
```

this is using OpenMPI 2.1.2.

And note that we will be going to OpenMPI 3.1.0 (or something like that) on these machines at some point (once IBM can fix the issues I think).

**Comment by alanw0** [comment]
@bartlettroscoe ok thanks. My ifdefs already exclude OpenMPI 3.1.x, I can easily also exclude OpenMPI 2.x.y. ("Exclude" means don't use the Neighbor functions, but instead use older MPI calls which may not scale as well but should be correct.)

**Comment by mhoemmen** [comment]
@alanw0 It appears that you are confusing the OpenMPI software version 3.1.x, with `MPI_VERSION` (the version of the MPI Standard to which the MPI implementation purports to adhere).  Existence of neighborhood collectives relates to `MPI_VERSION`.

**Comment by alanw0** [comment]
@mhoemmen, nope, I'm concluding that OpenMPI 2.1.2 doesn't have correct implementations of the neighbor functions. Also, OpenMPI 3.1.x has already been demonstrated to not have correct implementations. They both purport to implement MPI_VERSION==3, but apparently not very well.

**Comment by fryeguy52** [comment]
closing because none of these tests have failed on `Trilinos-atdm-white-ride-cuda-9.2-release-debug-pt` since 2019-02-22 shown [here](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=6&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-release-debug-pt&field2=testname&compare2=65&value2=STKUnit_tests_stk_&field3=testname&compare3=66&value3=_unit_tests_MPI_4&field4=site&compare4=61&value4=white&field5=buildstarttime&compare5=84&value5=2019-04-03T00%3A00%3A00&field6=buildstarttime&compare6=83&value6=2019-02-04T00%3A00%3A00)
