### ISSUE TITLE
Failing Albany test with MueLu + semicoarsening on Waterman

### ISSUE THREAD

**Issue by ikalash** [trilinos/Trilinos#3547]
Last week I set up nightly testing of Albany on waterman.  In this build, @jewatkins and I noticed that one of our Antarctic Ice sheet problems that uses MueLu + semicoarsening is failing, it appears within MueLu: 

http://cdash.sandia.gov/CDash-2-3-0/testDetails.php?test=3986370&build=76649

The test passed on Ride.  Could someone have a look at this?  You can see the options in the input file here:

https://github.com/gahansen/Albany/blob/master/tests/small/LandIce/FO_AIS/inputMueLuShort3.xml

The following modules are used:
```
module purge 
module load git
module load devpack/20180517/openmpi/2.1.2/gcc/7.2.0/cuda/9.2.88
module load yamlcpp/0.5.3/gcc/7.2.0
module unload cmake 
module load cmake 
module list
#FIXME: the following needs needs to be changed to point to your Trilinos!
#export OMPI_CXX=${jenkins_trilinos_dir}/packages/kokkos/config/nvcc_wrapper
export CUDA_MANAGED_FORCE_DEVICE_ALLOC=1
export CUDA_LAUNCH_BLOCKING=1
```
I seem to recall a similar error for this test case awhile ago on Ride.

@trilinos/muelu

**Comment by jhux2** [comment]
@rstumin @trilinos/muelu

**Comment by jhux2** [comment]
@ikalash Is the test on ride also CUDA-based?

**Comment by ikalash** [comment]
@jhux2 yes it's CUDA based.  Here's the output there: http://cdash.sandia.gov/CDash-2-3-0/testDetails.php?test=3986767&build=76620 .  One difference (besides Ride being P100 vs. Volta) is we don't have CUDA-aware MPI on in the Ride build, though probably that's not the issue.  @rstumin this test case is using the short PL syntax for MueLu.  Could that be part of the problem?  I'm not sure why it would show up on Volta and not Ride.  @jwatkin: do you have Albany built/running on quetzal, your Volta machine?  If so maybe you could see what happens with the test there just to get another data point.  The environment isn't entirely the same as waterman, of course.

**Comment by jewatkins** [comment]
It's currently running okay on the Titan V (although its very slow). I'm not sure how old the build is though.

**Comment by jhux2** [comment]
@ikalash Could you let me know if this is still a problem?

**Comment by ikalash** [comment]
Sorry for not following up on this.  Our waterman nightlies are clean finally (http://cdash.sandia.gov/CDash-2-3-0/index.php?project=Albany&subproject=IKTWatermanAlbanyCUDA&date=20190108) so it seems the problem has been resolved.  Please feel free to close.

**Comment by jhux2** [comment]
Closing as resolved.
