### ISSUE TITLE
Tpetra: Remove configure warning for unsigned long GO type 

### ISSUE THREAD

**Issue by rppawlo** [trilinos/Trilinos#355]
@trilinos/tpetra 

When unsigned long GO is enabed in tpetra, a long warning message about it being an unsupported type is printed during configure. unsigned long GO is required for DTK and DTK users have been worried when they see this warnings. After talking to @mhoemmen at developers meeting we decided to remove the warning for now.

**Comment by kddevin** [comment]
I, too, thought unsigned GOs (e.g., size_t) were OK to use, at least when ETI is OFF.  Is that true?
I know unsigned LOs are bad, but I thought GOs were OK.

**Comment by ibaned** [comment]
Sorry to intrude, but could someone post possible rationale for signed LOs and GOs ? I'm at a point where I should decide which to use by default (ETI) in some new code. I was leaning towards unsigned for both, but maybe I'm missing something important.

**Comment by mhoemmen** [comment]
@ibaned USE SIGNED LO AND GO.  USE ONLY SIGNED LO AND GO.  PLEASE PLEASE.

**Comment by ibaned** [comment]
I suppose compatibility with what Trilinos codes prefer is a strong reason in and of itself. I'll leave this thread alone and go change my typedefs.
