### ISSUE TITLE
TrilinosCouplings_ml_nox_1Delasticity_example_MPI_4 test failing in Trilinos-atdm-white-ride-cuda-9.2-debug-pt build

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#3551]
CC: @trilinos/trilinoscouplings , @jwillenbring (Trilinos Framework Product Area Lead), @fryeguy52 

## Next Action Status

PR #3568 merged on 10/5/2018 fixed this test as shown in the build on 10/6/2018.

## Description

The test `TrilinosCouplings_ml_nox_1Delasticity_example_MPI_4` is failing in the build `Trilinos-atdm-white-ride-cuda-9.2-debug-pt ` on 'white' and 'ride' as shown [here](https://testing.sandia.gov/cdash-dev-view/testDetails.php?test=55725442&build=3998269) which shows the failing output:

```
5001
5001
5001
5001
TrilinosCouplings_ml_nox_1Delasticity_example.exe: /home/jenkins/white/workspace/Trilinos-atdm-white-ride-cuda-9.2-debug-pt/SRC_AND_BUILD/Trilinos/packages/trilinoscouplings/examples/ml/NonlinML/FiniteElementProblem.cpp:218: bool FiniteElementProblem::evaluate(FillType, const Epetra_Vector*, Epetra_Vector*, Epetra_RowMatrix*): Assertion `ierr' failed.
[white27:17997] *** Process received signal ***
[white27:17997] Signal: Aborted (6)
[white27:17997] Signal code:  (-6)
[white27:17997] [ 0] [0x3fffa9850478]
[white27:17997] TrilinosCouplings_ml_nox_1Delasticity_example.exe: /home/jenkins/white/workspace/Trilinos-atdm-white-ride-cuda-9.2-debug-pt/SRC_AND_BUILD/Trilinos/packages/trilinoscouplings/examples/ml/NonlinML/FiniteElementProblem.cpp:218: bool FiniteElementProblem::evaluate(FillType, const Epetra_Vector*, Epetra_Vector*, Epetra_RowMatrix*): Assertion `ierr' failed.
[white27:17998] *** Process received signal ***
[white27:17998] Signal: Aborted (6)
[white27:17998] Signal code:  (-6)
[white27:17998] [ 0] [0x3fff7ce70478]
[white27:17998] [ 1] TrilinosCouplings_ml_nox_1Delasticity_example.exe: /home/jenkins/white/workspace/Trilinos-atdm-white-ride-cuda-9.2-debug-pt/SRC_AND_BUILD/Trilinos/packages/trilinoscouplings/examples/ml/NonlinML/FiniteElementProblem.cpp:218: bool FiniteElementProblem::evaluate(FillType, const Epetra_Vector*, Epetra_Vector*, Epetra_RowMatrix*): Assertion `ierr' failed.
[white27:17999] *** Process received signal ***
[white27:17999] Signal: Aborted (6)
[white27:17999] Signal code:  (-6)
[white27:17999] [ 0] [0x3fffa4920478]
[white27:17999] [ 1] /lib64/libc.so.6(abort+0x2b4)[0x3fff97081f94]
[white27:17999] [ 2] TrilinosCouplings_ml_nox_1Delasticity_example.exe: /home/jenkins/white/workspace/Trilinos-atdm-white-ride-cuda-9.2-debug-pt/SRC_AND_BUILD/Trilinos/packages/trilinoscouplings/examples/ml/NonlinML/FiniteElementProblem.cpp:218: bool FiniteElementProblem::evaluate(FillType, const Epetra_Vector*, Epetra_Vector*, Epetra_RowMatrix*): Assertion `ierr' failed.
[white27:18000] *** Process received signal ***
[white27:18000] Signal: Aborted (6)
[white27:18000] Signal code:  (-6)
...
```

This is an important build because we are targeting this build on 'white' and 'ride' as a Trilinos CUDA PR testing build (see #2464 ).  However, the SPARC and EMPIRE ATDM Trilinos builds don't enable TrilinosCouplings so we could just disable this test and not impact ATDM at all.

## Steps to reproduce

One should be able to reproduce these build errors on either 'white' or 'ride' by cloning the Trilinos git repo, checking out the 'develop' branch, creating a build directory, and then doing:

```
$ cd <some_build_dir>/

$ source $TRILINOS_DIR/cmake/std/atdm/load-env.sh cuda-9.2-debug

$ cmake \
  -GNinja \
  -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnvAllPtPackages.cmake \
  -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_TrilinosCouplings=ON \
  $TRILINOS_DIR

$ make NP=16

$ bsub -x -Is -q rhel7F -n 16 ctest -j16
```

**Comment by jhux2** [comment]
This should probably just be disabled for CUDA builds.

**Comment by jhux2** [comment]
@bartlettroscoe Is there a convenient guard I can use in CMakeLists.txt to avoid even running this under CUDA?

**Comment by jhux2** [comment]
> This should probably just be disabled for CUDA builds.

Nope.  There appears to be a real bug in the code.  PR submitted.

**Comment by bartlettroscoe** [comment]
Looks like PR #3568 merged on 10/5/2018 fixed this test as shown in the build on 10/6/2018 shown [here](https://testing.sandia.gov/cdash-dev-view/index.php?project=Trilinos&parentid=4022582) (see the `-1` subscript and `+1` superscript by the number of failing and passing tests for Trilinos couplings).  See the newly passing test at:

* https://testing.sandia.gov/cdash-dev-view/viewTest.php?onlydelta&buildid=4022630

Closing as complete.

Thanks @jhux2!

**Comment by bartlettroscoe** [comment]
Closing
