### ISSUE TITLE
MueLu: uncoupled aggregation phase 3 failing on CUDA builds

### ISSUE THREAD

**Issue by lucbv** [trilinos/Trilinos#3556]
@trilinos/muelu 
@rstumin 

## Expectations
All tests should pass on the [CUDA build](https://testing.sandia.gov/cdash/buildSummary.php?buildid=4003452) especially since they might be used by the auto-tester...

## Current Behavior
The two CUDA builds with `KOKKOS_REFACTOR=ON` on geminga are failing due to a failure to aggregates all nodes. This seem like a bug newly introduced in phase 3 of uncoupled aggregation.

## Motivation and Context
Mainly we want to maintain a clean dashboard.

## Definition of Done
- [ ] The CUDA builds with `KOKKOS_REFACTOR=ON` are clean and no tests fail

## Possible Solution
I am not sure but it looks like a logic error so probably looking at aggregation phase 3 will be enough

**Comment by jhux2** [comment]
I am working on a fix now.

**Comment by jhux2** [comment]
Dashboard is cleaner.  Just pushed another fix that hopefully gets the last phase 3 failures on geminga.

**Comment by jhux2** [comment]
Blocks #2674.

**Comment by jhux2** [comment]
Dashboard is clear of any Phase3 errors. I'm closing this as fixed.
