### ISSUE TITLE
ML: add option to replace MPI communicator

### ISSUE THREAD

**Issue by jhux2** [trilinos/Trilinos#3565]
@rhoope has asked whether it would be possible to update ML's preconditioner ctors to allow a user to pass in an MPI communicator that would replace the default (MPI_COMM_WORLD).

@csiefer2 @trilinos/ml

**Comment by jhux2** [comment]
That's what I see, as well.  However, @rhoope is going to submit a patch, so we'll have a chance to see what he's proposing.

**Comment by csiefer2** [comment]
Reviewed changes to the C interface.  They look good.

**Comment by rhoope** [comment]
I think this has been resolved as needed by Alegra and can be closed.  I don't have permission to do so.
