### ISSUE TITLE
Ifpack2 + Kokkos + complex float : compilation error

### ISSUE THREAD

**Issue by davydden** [trilinos/Trilinos#3574]
## Expectations

Trilinos `trilinos-release-12-14-branch` builds  with ETI and complex and float types

## Current Behavior
```
8051    In file included from /Users/davydden/spack/var/spack/stage/trilinos-12.14-hpmbucm6pphwdcf3p6hhqcac2cm5qts6/Trilinos/spack-build/packages/ifpack2/src/Ifpack2_BlockTriDiContainer_Serial.cpp:50:
     8052    In file included from /Users/davydden/spack/var/spack/stage/trilinos-12.14-hpmbucm6pphwdcf3p6hhqcac2cm5qts6/Trilinos/packages/ifpack2/src/Ifpack2_BlockTriDiContainer_def.hpp:52:
  >> 8053    /Users/davydden/spack/var/spack/stage/trilinos-12.14-hpmbucm6pphwdcf3p6hhqcac2cm5qts6/Trilinos/packages/kokkos-kernels/src/batched/KokkosBatched_Util.hpp:195:7: error: static_assert failed "KokkosKernels:: Invalid SIMD<> type."
     8054          static_assert( std::is_same<T,bool>::value                     ||
     8055          ^              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     8056    /Users/davydden/spack/var/spack/stage/trilinos-12.14-hpmbucm6pphwdcf3p6hhqcac2cm5qts6/Trilinos/packages/ifpack2/src/Ifpack2_BlockTriDiContainer_impl.hpp:1568:28: note: in instantiation of template class 'KokkosBatched::Experimental::SIMD<Kokkos::complex<floa
             t> >' requested here
     8057                B.assign_data( &vector_values(i0+1,0,0) );
     8058                               ^
     8059    /Users/davydden/spack/var/spack/stage/trilinos-12.14-hpmbucm6pphwdcf3p6hhqcac2cm5qts6/Trilinos/packages/ifpack2/src/Ifpack2_BlockTriDiContainer_impl.hpp:1651:9: note: in instantiation of member function 'Ifpack2::BlockTriDiContainerDetails::ExtractAndFactori
             zeTridiags<Tpetra::Classes::RowMatrix<std::__1::complex<float>, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > >::factorize' requested here

```

## Steps to Reproduce
configure and build with:

```
-DTrilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON
-DTpetra_INST_DOUBLE:BOOL=ON
-DTpetra_INST_INT_LONG:BOOL=ON
-DTpetra_INST_COMPLEX_DOUBLE=ON
-DTpetra_INST_COMPLEX_FLOAT=ON
-DTpetra_INST_FLOAT=ON
-DTpetra_INST_SERIAL=ON
-DTeuchos_ENABLE_COMPLEX=ON
-DTeuchos_ENABLE_FLOAT=ON
```

## Your Environment

macOS Mojave
Apple Clang 10.0.0
gfortran 8.2.0

## Additional Information
full config/build logs:

[logs.zip](https://github.com/trilinos/Trilinos/files/2454254/logs.zip)

**Comment by mhoemmen** [comment]
I've filed this as a kokkos-kernels issue, since it relates to kokkos-kernels' explicit SIMD type.

**Comment by kyungjoo-kim** [comment]
@davydden 

I don't understand this error. When I look at the ``branch trilinos-release-12-4-branch`` and packge list is as follows:
https://github.com/trilinos/Trilinos/tree/trilinos-release-12-4-branch/packages
there is no kokkos-kernels and ifpack2 does not include block tridi container.

**Comment by kyungjoo-kim** [comment]
Oh.. sorry.... it is 12-14

**Comment by kyungjoo-kim** [comment]
now the assert included in kokkoskernels PR 320. 

https://github.com/kokkos/kokkos-kernels/pull/320

The fix will arrive after kokkos and kokkoskernels are integrated into trilinos.

**Comment by davydden** [comment]
> The fix will arrive after kokkos and kokkoskernels are integrated into trilinos.

Thanks. Is this planned before 12.14 release?

**Comment by srajama1** [comment]
We can cherry-pick into 12.14 

@jwillenbring : We need a tag or some identification for issues that need to be fixed in 12.14 branch. This is the second one. There is also the SuperLU-dist issue. What do you want to do cherry-pick now, wait for PR testing on that branch ?

**Comment by kyungjoo-kim** [comment]
I would also like to push the fix into Trilinos repo so that you can compile with the develop branch. However, I am afraid of that it may not pass the PR test due to some happening from tpetra deprecation. @mhoemmen knows it.

**Comment by jwillenbring** [comment]
@srajama1 I added a label and applied it to this issue. I suggest we wait for the PR testing to be done. I am working on it right now.

**Comment by mhoemmen** [comment]
@kyungjoo-kim Do you mean getting rid of the `Tpetra::Classes` namespace?  That shouldn't be a big problem, due to the type aliases from before.

**Comment by kyungjoo-kim** [comment]
Currently I cannot compile ifpack2 with current develop branch.

**Comment by kyungjoo-kim** [comment]
I will double check with develop branch. So far I tested it with my fork after merging upstream develop.

**Comment by mhoemmen** [comment]
@kyungjoo-kim I'm not finding these errors on the Dashboard -- have you tried perhaps deleting the build directory and starting from fresh?

**Comment by kyungjoo-kim** [comment]
Does our test or dashboard include float or complex<float> as shown in this issue ?

**Comment by kyungjoo-kim** [comment]
BTW, my configure script includes the above ETIs described in this issue.

**Comment by kyungjoo-kim** [comment]
@mhoemmen I did clean build and actually I found a different error. It can compile it. Sorry that I make a false alarm. All the fix will be also pushed into Trilinos soon.

**Comment by mhoemmen** [comment]
@kyungjoo-kim Just wanted to make sure -- I've been doing a Clang build with all the Scalar types enabled just to check, but it takes a while.

**Comment by mhoemmen** [comment]
See also PR #3597.

**Comment by srajama1** [comment]
Please close this issue after cherry-picking into 12.14

**Comment by tjhei** [comment]
I am getting the same error with the newly tagged https://github.com/trilinos/Trilinos/releases/tag/trilinos-release-12-14-1 
I assume this means the fix did not get merged?

**Comment by mhoemmen** [comment]
@trilinos/ifpack2
