### ISSUE TITLE
Anasazi/RBGen compilation error

### ISSUE THREAD

**Issue by ikalash** [trilinos/Trilinos#3576]
This morning a Trilinos compilation error cropped up in Albany nightly testing having to do with Anasazi/RBen:

```
repos/Trilinos/packages/anasazi/epetra/src-rbgen/../../src-rbgen/RBGen_Filter.hpp:205:46: error: ‘tval’ is not captured
```

(or see here http://cdash.sandia.gov/CDash-2-3-0/viewBuildError.php?buildid=76890 ).  Can someone please fix this issue?

@trilinos/anasazi

**Comment by mhoemmen** [comment]
Huh, this could be related to PR #3571.  Will also need to fix PR #3573 if this is the case.

**Comment by jhux2** [comment]
@trilinos/anasazi

**Comment by mhoemmen** [comment]
Huh, that's weird.  PR #3573 should never have compiled, since the capture clause is empty.  I'm wondering how it got through.

@trilinos/anasazi @hkthorn @trilinos/framework @bartlettroscoe @jwillenbring Does PR testing not enable this code?

**Comment by mhoemmen** [comment]
Only the one file in PR #3573 has this issue.  The other files' lambdas don't capture any variables.  I'll post a fix soon and cherry-pick into 12.14.

**Comment by bartlettroscoe** [comment]
> Does PR testing not enable this code?

@mhoemmen, we would have to run a coverage build build using one of the PR builds.  The instructions for how to that are at:

* https://trilinos.org/docs/files/TrilinosBuildReference.html#enabling-support-for-coverage-testing
* https://trilinos.org/docs/files/TrilinosBuildReference.html#dashboard-submissions

Should be pretty fast.

**Comment by mhoemmen** [comment]
@davydden See above.

**Comment by bartlettroscoe** [comment]
> Does PR testing not enable this code?

Wait, Anasazi/RBGen is disabled by default in Trilinos.  To see that see:

* https://testing-vm.sandia.gov/cdash-dev-view/viewNotes.php?buildid=4030844#!#note1

which shows:

```
Anasazi_ENABLE_RBGen:BOOL=OFF
```

Anything that is turned off by default in Trilinos is likely not getting tested anywhere (unless we are doing it for ATDM Trilinos builds).

**Comment by mhoemmen** [comment]
@bartlettroscoe Huh, that's weird.  We do get coverage through Albany testing, and RBGen doesn't change terribly much, so I'm not too worried about this.  On the other hand, I don't imagine it's very expensive to build RBGen.  I wonder why it got turned off.

**Comment by mhoemmen** [comment]
@ikalash Thanks for reporting this!  I have a PR ready, #3584, that fixes this issue.  It looks like RBGen does not get exercised in Trilinos' PR tests -- another reason to be grateful for Albany's extensive tests :-)

**Comment by ikalash** [comment]
Thanks @mhoemmen .  I’m glad the tests are useful to trilinos folks :),  I’ll check that things are good with your PR once it makes it to develop.

**Comment by bartlettroscoe** [comment]
@mhoemmen, does PR #3584 fix the CUDA build for Anasazi/RBGen?  Also, not that SPARC is currently enabling Anasazi/RBGen so it would be good if this could be enabled by default in Trilinos perhaps.  Either that, or Anasazi should be broken into subpackages, with AnasaziRBGen being one subpackage, and then downstream customers can decide which parts of Anasazi they want to enable and use.

**Comment by mhoemmen** [comment]
@bartlettroscoe wrote:
> Does PR #3584 fix the CUDA build for Anasazi/RBGen?

It doesn't actually relate to the CUDA build; non-CUDA builds were broken too.

> so it would be good if this could be enabled by default in Trilinos perhaps.

I really do wish PR testing would enable the packages that got touched, but somehow that is broken right now; not sure why.
