### ISSUE TITLE
Test Anasazi_Epetra_OrthoManagerGenTester_0_MPI_4 appears to be randomly failing in many builds including CI, PR, and ATDM builds

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#3585]
CC: @trilinos/framework, @trilinos/anasazi, @srajama1 (Trilinos Linear Solver Product Area Lead)

## Next Action Status

PR #4052 merged to 'develop' on 12/18/2018 but still failing after that.  Next: Try to fix again?

## Description

It would seem that the test `Anasazi_Epetra_OrthoManagerGenTester_0_MPI_4` is very occasionally randomly failing in various builds.  As shown in [this query](https://testing.sandia.gov/cdash-dev-view/queryTests.php?project=Trilinos&date=2018-10-09&filtercount=4&showfilters=1&filtercombine=and&field1=testname&compare1=61&value1=Anasazi_Epetra_OrthoManagerGenTester_0_MPI_4&field2=status&compare2=61&value2=failed&field3=details&compare3=64&value3=timeout&field4=buildstarttime&compare4=83&value4=2018-07-01), this test failed 10 times since 7/1/2018 in the builds:

* `Linux-GCC-4.8.4-MPI_RELEASE_DEBUG_SHARED_PT_OPENMP_CI` (post-push CI build): 1 time (today)
* `PR-XXXX-test-Trilinos_pullrequest_gcc_4.9.3-YYYY` (standard PR build): 4 times
* `PR-XXXX-test-Trilinos_pullrequest_gcc_4.8.4-YYYY` (standard PR build): 1 time
* `Trilinos-atdm-chama-intel-debug-openmp` (standard ATDM build): 1 time
* `Trilinos-atdm-rhel6-gnu-opt-openmp` (standard ATDM build): 2 times
* `Trilinos-atdm-waterman-cuda-9.2-debug` (standard ATDM build): 1 time

In each of these 10 failures in the last 3 months, such as the CI failure today shown [here](https://testing.sandia.gov/cdash-dev-view/testDetails.php?test=56264374&build=4031303), it shows failures like:

```
projectAndNormalizeGen() returned rank 5
   || <S,S> - I || after  : 2.65912e-11
  1|| S_in - X1*C1 - X2*C2 - S_out*B || : 1.70776e-09
         vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv         tolerance exceeded! test failed!
```

The location of these failures seems to change in this test but all of the failures appear to be "tolerance exceeded! test failed!"

Is there some type of non-deterministic behavior in this test or in the underlying Anasazi code that allows for these types of random failures?

## Steps to Reproduce

Given that this test seems to be failing randomly only very occasionally, this might be hard to reproduce locally.  But given that this has failed in the post-push GCC 4.8.4 CI build and the GCC 4.9.3 PR build one might be able to use one of those.

**Comment by bartlettroscoe** [comment]
This randomly failing test has killed 5 PR build/test iterations in the last 3 months.  It also broke the ATDM Trilinos builds 4 times in the last 3 months.  That is not super high but it is something worth looking into.

**Comment by srajama1** [comment]
@hkthorn

**Comment by hkthorn** [comment]
@srajama1 @bartlettroscoe The Anasazi code is deterministic, but most of its tests (like with Belos) use random vectors.  Those are not deterministic.  I will look into this test.

**Comment by bartlettroscoe** [comment]
CC: @fryeguy52, @srajama1, @hkthorn 

FYI: This just broke the `Trilinos-atdm-sems-rhel6-gnu-debug-openmp` nightly build this morning as shown [here](https://testing.sandia.gov/cdash-dev-view/testDetails.php?test=57065637&build=4068796) showing:

```
...

projectGen(): testing [X2 Y1]-range multivector against P_{X2,X2} P_{Y1,Y1} 
   || <S,Y1> || before     : 139287
   || <S,Y2> || before     : 4.50888
  0|| S_in - X1*C1 - X2*C2 - S_out || : 0
  1|| S_in - X1*C1 - X2*C2 - S_out || : 1.08075e-11
         vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv         tolerance exceeded! test failed!
  1|| <Y[0],S> || after      : 2.94507e-10
  2|| S_in - X1*C1 - X2*C2 - S_out || : 1.08075e-11
         vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv         tolerance exceeded! test failed!
  2|| <Y[0],S> || after      : 2.94507e-10
  3|| S_in - X1*C1 - X2*C2 - S_out || : 1.08075e-11
         vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv         tolerance exceeded! test failed!
...
```

**Comment by bartlettroscoe** [comment]
NOTE: We are seeing this in other ATDM Trilinos builds as well, for example, as shown [here](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=7&showfilters=1&filtercombine=and&field1=site&compare1=62&value1=mutrino&field2=buildname&compare2=65&value2=Trilinos-atdm-&field3=buildname&compare3=62&value3=Trilinos-atdm-cee-rhel6-gnu-7.2.0-opt-serial&field4=testname&compare4=61&value4=Anasazi_Epetra_OrthoManagerGenTester_0_MPI_4&field5=status&compare5=62&value5=passed&field6=status&compare6=62&value6=notrun&field7=buildstarttime&compare7=83&value7=2018-10-22) which shows the failure in the builds on days:

| Site | Build Name | Test Name | Status | Time | Details | Build Time |
| :--  | :--        | :--       | :--    | --:  | :--     | --:        |
| cee-rhel6 | Trilinos-atdm-cee-rhel6-gnu-7.2.0-openmpi-1.10.2-serial-static-opt | Anasazi_Epetra_OrthoManagerGenTester_0_MPI_4 | Failed | 17s 930ms | Completed (Failed) | 2018-11-26T09:04:41 UTC |
| sems-rhel6 | Trilinos-atdm-sems-rhel6-gnu-debug-serial | Anasazi_Epetra_OrthoManagerGenTester_0_MPI_4 | Failed | 630ms | Completed (Failed) | 2018-11-15T04:28:01 UTC |

**Comment by fryeguy52** [comment]
FYI: this test failed in 
`Trilinos-atdm-sems-rhel6-gnu-opt-serial` on 12/3/2018 
and in 
`Trilinos-atdm-cee-rhel6-gnu-7.2.0-openmpi-1.10.2-serial-static-opt` on 11/26/2018

see [here](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-&field2=testname&compare2=61&value2=Anasazi_Epetra_OrthoManagerGenTester_0_MPI_4&field3=buildstarttime&compare3=84&value3=2018-12-04T00%3A00%3A00&field4=buildstarttime&compare4=83&value4=2018-11-04T00%3A00%3A00&field5=status&compare5=61&value5=Failed)

**Comment by bartlettroscoe** [comment]
> Which app in ATDM is enabling Anasazi ? Do they really need Anasazi ?

@srajama1, currently SPARC explicitly enables and pulls in Anasazi.  Whether they actually need it or not is a question for @micahahoward or perhaps @mhoemmen.

**Comment by bartlettroscoe** [comment]
@srajama1, also, EMPIRE implicitly enables Anasazi through Panzer.  @rppawlo should know if EMPIRE is actually using Anasazi.

**Comment by bartlettroscoe** [comment]
FYI: The Trilinos CI build just got bit by this again just now as shown [here](https://testing-vm.sandia.gov/cdash/testDetails.php?test=61513720&build=4297247).  Therefore, this will also be breaking Trilinos PR test iterations randomly going forward.  As shown in [this query](https://testing.sandia.gov/cdash-dev-view/queryTests.php?project=Trilinos&date=2018-10-09&filtercount=5&showfilters=1&filtercombine=and&field1=groupname&compare1=61&value1=Pull%20Request&field2=testname&compare2=61&value2=Anasazi_Epetra_OrthoManagerGenTester_0_MPI_4&field3=status&compare3=61&value3=failed&field4=details&compare4=64&value4=timeout&field5=buildstarttime&compare5=83&value5=2018-07-01) you can see this break PR builds as recently as today and on 2018-11-29.

And as @fryeguy52 noted [above](https://github.com/trilinos/Trilinos/issues/3585#issuecomment-444194179), this fairly recently broke some (promoted) ATDM builds.

Once we can implement support for the "randomly_failing" and "ok_to_fail" fields in the CDash analysis tool being developed in #2933, we will classify this test as `randomly_failing=2` (i.e. very rarely randomly fails) and `okay_to_fail=1` (don't trigger global FAIL).  That will remove this failing test as a problem for ATDM.

**Comment by hkthorn** [comment]
@bartlettroscoe I think I have a fix for this.  It is a test that generates a biorthogonal basis.  The dimensions used add up to something close enough to the dimension of the operator that generating a degenerate orthogonal subspace from random vectors is much more likely than with the two other orthogonalization tests.  I have experimented with this test on the CEE, where I have a binary that fails often enough for me to explore the issue.  I have reduced the subspace sizes for the orthogonalization test and that failure seems to stop occurring on this particular platform.  I would like to check in this modification.

**Comment by bartlettroscoe** [comment]
> I have reduced the subspace sizes for the orthogonalization test and that failure seems to stop occurring on this particular platform. I would like to check in this modification.

@hkthorn, excellent!  Thanks for looking into this.  Please create a PR for this and I will review and approve it (unless you want another Belos developer like @mhoemmen to review it).

**Comment by hkthorn** [comment]
@bartlettroscoe This is such a minor change, I don't think we need to bother @mhoemmen with it.

**Comment by hkthorn** [comment]
@bartlettroscoe @srajama1 Thanks for your patience on this one.  I finally found a platform that displayed the issue with some regularity so that I could explore it with some confidence.

**Comment by bartlettroscoe** [comment]
PR #4052 with likely fix merged to 'develop' on 12/18/2018.  Next: Let run for two months and then close if no failures by 2/18/2018 ...

**Comment by srajama1** [comment]
@hkthorn Thanks for taking care of this. @bartlettroscoe If it is ok I recommend closing this and reopening if it still happens again.

**Comment by bartlettroscoe** [comment]
@srajama1 said

> @hkthorn Thanks for taking care of this. @bartlettroscoe If it is ok I recommend closing this and reopening if it still happens again.

Okay, I set up a calendar reminder to check on this.  If we find there were more random failures (or find out sooner than that), we will re-open this issue.

@hkthorn, thanks for fixing this!

(We are still trying to figure out the best way to address these only very ocassinal randomly failing tests.  Hopefully this process of optimistically closing the issue but setting up a reminder to check is a good one.)

Closing the issue ...

----

From: Bartlett, Roscoe A 
Sent: Friday, December 14, 2018 3:16 PM
To: Frye, Joe
Subject: #3585: Verify that Anasazi_Epetra_OrthoManagerGenTester_0_MPI_4 has not failed since 12/14/2018
When: Monday, February 11, 2019 10:00 AM-10:30 AM (UTC-05:00) Eastern Time (US & Canada).
Where: Reminder

This calendar reminder is to check the query:

    https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&date=2018-10-09&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=5&showfilters=1&filtercombine=and&field1=groupname&compare1=62&value1=Experimental&field2=testname&compare2=61&value2=Anasazi_Epetra_OrthoManagerGenTester_0_MPI_4&field3=status&compare3=61&value3=failed&field4=details&compare4=64&value4=timeout&field5=buildstarttime&compare5=83&value5=2018-12-14

and verify that there were no more random failures like seen in:

   https://github.com/trilinos/Trilinos/issues/3585

NOTE: The issue is already closed so just add a comment in the closed issue that indeed there have been no more random failures.  If you do see any new random failures like this, please reopen the issue and add a comment about the failures.

**Comment by mhoemmen** [comment]
@hkthorn Y'all let me have a couple days off ;-)

**Comment by bartlettroscoe** [comment]
This test failed again in the build `Trilinos-atdm-sems-rhel6-intel-opt-openmp` yesterday 1/6/2019 as shown [here](https://testing.sandia.gov/cdash/testDetails.php?test=63447147&build=4380521) showing:

```
projectAndNormalizeGen() returned rank 3
   || <S,S> - I || after  : 2.05042e-12
         vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv         tolerance exceeded! test failed!
  19|| S_in - X1*C1 - X2*C2 - S_out*B || : 1.01754e-08
  19|| <Y[0],S> || after      : 3.04764e-12
```

And looking at [this query](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&date=2018-10-09&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=5&showfilters=1&filtercombine=and&field1=groupname&compare1=62&value1=Experimental&field2=testname&compare2=61&value2=Anasazi_Epetra_OrthoManagerGenTester_0_MPI_4&field3=status&compare3=61&value3=failed&field4=details&compare4=64&value4=timeout&field5=buildstarttime&compare5=83&value5=2018-12-14) there have been 5 failures since 12/14/2018, including in a PR test build.

Reopening this issue :-(

**Comment by fryeguy52** [comment]
failed 3 times in the last month on `Trilinos-atdm-sems-rhel7-gnu-7.2.0-openmp-complex-shared-release-debug`. see [here](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercombine=and&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-sems-rhel7-gnu-7.2.0-openmp-complex-shared-release-debug&field2=testname&compare2=61&value2=Anasazi_Epetra_OrthoManagerGenTester_0_MPI_4&field3=site&compare3=61&value3=sems-rhel7&field4=buildstarttime&compare4=84&value4=2019-04-02T00%3A00%3A00&field5=buildstarttime&compare5=83&value5=2019-03-03T00%3A00%3A00)

**Comment by fryeguy52** [comment]
Looking closer this test has failed over a dozen times on 8 different Trilinos builds in the last month shown [here](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=4&showfilters=1&filtercombine=and&field1=testname&compare1=61&value1=Anasazi_Epetra_OrthoManagerGenTester_0_MPI_4&field2=status&compare2=61&value2=Failed&field3=buildstarttime&compare3=84&value3=2019-04-02T00%3A00%3A00&field4=buildstarttime&compare4=83&value4=2019-03-03T00%3A00%3A00)

**Comment by bartlettroscoe** [comment]
Anasazi is not used by ATDM so failures in Anasazi tests are not an ATDM issue.  Therefore, I am removing the 'client: ATDM' label to get this off of our list of active issues for ATDM.  (Really we should not even be running Anasazi tests in ATDM Trilinos builds.)

**Comment by bartlettroscoe** [comment]
FYI: These tests have been disabled in ATDM Trilinos testing as per:

* https://sems-atlassian-srn.sandia.gov/browse/ATDV-263

Adding "Disabled Tests" label.

**Comment by bartlettroscoe** [comment]
@trilinos/framework, this test took our a PR testing iteration as shown in https://github.com/trilinos/Trilinos/pull/6641#issuecomment-579044999.  It showed:

```
projectAndNormalizeGen() returned rank 3
   || <S,S> - I || after  : 1.05981e-12
         vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv         tolerance exceeded! test failed!
```

This test should be removed from all PR iterations.

**Comment by mhoemmen** [comment]
@trilinos/anasazi
