### ISSUE TITLE
Epetra: NumGlobalElements in Epetra_Map without MPI

### ISSUE THREAD

**Issue by freaklovesmango** [trilinos/Trilinos#3589]
If I create a Epetra_CrsMatrix and let's say this matrix is 10x10 big and has 50 non-zero values. If I want to create this without MPI, what is the right number for the NumGlobalElements for the Epetra_Map? I mean how should I think this? Is it all non-zero values, hence 50? Or maybe the entries per row?

**Comment by freaklovesmango** [comment]
Edit: I understand, that I can create a Epetra_CrsMatrix with a RowMap and a ColMap. Does that mean, that I create the Maps with Dimension as NumGlobalElements?

**Comment by mhoemmen** [comment]
1. Don't create the matrix with a column Map unless you know what you're doing.  (Epetra has this way of silently ignoring inserts of column indices that aren't in the column Map on the calling process.)

2. "No MPI" behaves like "MPI with 1 process."

**Comment by mhoemmen** [comment]
@trilinos/epetra

**Comment by freaklovesmango** [comment]
I wanted to use the method InsertMyValues(), hence the need of a ColMap additional to the RowMap is mandatory, right?
I understand, that it is one process but does that automatically mean, that this one processor has to deal with everything and hence, a distribution of the entries is unnecessary or wrong?

**Comment by mhoemmen** [comment]
It's OK to provide a column Map, but note that it must include all the entries needed in order for sparse matrix-vector multiply's communication pattern to be correct.  If you have only 1 MPI process, you could make the row Map and the column Map the same, and everything should work just fine (as long as the matrix is square).

**Comment by freaklovesmango** [comment]
Sorry for the late response, thank you!

**Comment by mhoemmen** [comment]
Glad to help!
