### ISSUE TITLE
Threading of Tpetra::CrsMatrix doExport

### ISSUE THREAD

**Issue by eric-c-cyr** [trilinos/Trilinos#359]
The current doExport routine needs to be threaded. My (personal) usage of this is limited to export from one static graph matrix to another static graph matrix. No entries are added. Adding @bathmatt, @kddevin and @rppawlo.

**Comment by mhoemmen** [comment]
@eric-c-cyr It would be helpful to have the following information:

1. How much of a performance issue is this for you?
2. What is the priority for a fix?
3. What are the Kokkos back-ends of most interest?

You're welcome to e-mail @kddevin and myself directly if you prefer.

**Comment by mhoemmen** [comment]
We'll have threaded CrsMatrix pack and unpack soon.  We have threaded MultiVector pack and unpack already.  Please file new issues with specific requirements if this does not suffice.
