### ISSUE TITLE
Make Explicit Template Instantiation (ETI) the default with Trilinos

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#361]
**Description:**

This story is to do the planning and the work necessary to make Trilinos build with explicit template instantiation (ETI) enabled by default.  If you don't have ETI enabled but instead use the default implicit template instantation process, the build times for Trilinos can be massive.  In addition, some compilers (e.g. Intel) will even crash when you try to use implicit template instantiation with Trilinos.  

Whenever a Trilinos user complains about build times or the compiler crashing, our first response is to tell them to enable ETI and every Trilinos developer and experienced user pretty much pretty exclusively enables ETI.

**Tasks:**

???

**Comment by mhoemmen** [comment]
Tasks:
1. Make sure that turning on ETI works for major customers -- get them the settings they need to make it work
2. Make sure turning on ETI doesn't massively increase their executable sizes (remember that some major customers use static libraries exclusively)

**Comment by bartlettroscoe** [comment]
> 1. Make sure that turning on ETI works for major customers -- get them the settings they need to make it work

We are only changing the default.  Important customers can turn off ETI if they want (it is just one CMake variable).

> 2. Make sure turning on ETI doesn't massively increase their executable sizes (remember that some major customers use static libraries exclusively)

I think this is an issue for SIERRA which does all static library builds.  But SIERRA does not even use the CMake build for Trilinos so this would not even affect them.  If they do use the CMake build for Trilinos, then they can disable it.

Existing customers are already turning on ETI.  What we are trying to do here is to reduce the build times for Trilinos for the average new-comer.  My guess is that Trilinos is loosing a lot of potential new users due to the excessive default build times for Trilinos.

**Comment by bartlettroscoe** [comment]
I added explicit mention of about how to enable ETI and shared libs to the INSTALL document and put in a link right on the front Triinos/README.md page.  Hopefully users will be able to find this easier now.

**Comment by mhoemmen** [comment]
This is not properly a Tpetra issue; it's a Trilinos-wide issue.

**Comment by bartlettroscoe** [comment]
> This is not properly a Tpetra issue; it's a Trilinos-wide issue.

Yes, but it is strongly related to Tpetra.  How you use labels for such a purpose is open for debate.

**Comment by mhoemmen** [comment]
> Yes, but it is strongly related to Tpetra. How you use labels for such a purpose is open for debate.

Tpetra's not the center of the universe ;-)  ETI touches a lot of packages.  We could list all the packages, or none of them and call this "Framework."

**Comment by bartlettroscoe** [comment]
Closing as a duplicate of newer issue #8130.
