### ISSUE TITLE
Sundance no longer configures with updated Trilinos and TriBITS

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#3611]
@trilinos/framework

The package Sundance stored in the extra repo https://github.com/trilinos/Sundance does not configure with the current version of Trilinos 'develop'.  The only automated Trilinos build that actually pulls in Sundance is the build `Linux-GCC-4.9.3-openmpi-1.8.7_Debug_DEV_Werror` posting the the "Experimental" CDash group shown today at:

* https://testing.sandia.gov/cdash-dev-view/index.php?project=Trilinos&parentid=4038223

In this build, Sundance fails to configure showing the configure failure [here](https://testing.sandia.gov/cdash-dev-view/viewConfigure.php?buildid=4042789) which shows the configure failure:

```
Processing enabled package: Sundance (Libs, Tests, Examples)
adding Playa/src
-- DEPLIBS=''
adding Playa/tests
CMake Error at packages/Sundance/cmake/AddTestBatch.cmake:8 (PARSE_ARGUMENTS):
  Unknown CMake command "PARSE_ARGUMENTS".
Call Stack (most recent call first):
  packages/Sundance/Playa/tests/Operator/CMakeLists.txt:20 (ADD_TEST_BATCH)
```

TriBITS removed the deprecated function `PARSE_ARGUMENTS()` a long time ago in the TriBITS commit TriBITSPub/TriBITS@e7bfe1a5337f11a3b070a7a272032f6de430b482 on 5/19/2017 and was snapshotted to Trilinos 'develop' in the commit 12c4cf6defd5b5f4572a4ab52bb2920d24f4061b on 6/1/2017.  That means that **Sundance has likely not been able to configure against the Trilinos 'develop' branch in over 16 months**!

But when the package-by-package mode was being used for this build as recently as 9/21/2018 shown [here](https://testing.sandia.gov/cdash-dev-view/index.php?project=Trilinos&parentid=3959759&filtercount=2&showfilters=1&field1=buildstarttime&compare1=83&value1=4%20weeks%20ago&filtercombine=and), that configure failure only killed the build and testing of the Sundance package and therefore all of the other packages still got built and tests run.  But when switching to the all-at-once mode as part of #1761 on 10/10/2018, that Sundance configure failure now stops the build and testing of all of the Trilinos packages.  Therefore, this issue must be addressed.

**Comment by bartlettroscoe** [comment]
Given that Sundance has not even configured against Trilinos 'develop' in orver 16 months and since development on Sundance is dead (the last commit to trilinos/Sundance@master was trilinos/Sundance@c7158e88f14a6a2244bd357f133efce885a9c6bc back on 6/27/2015), I think it is time to remove it from the list of extra repos for Trilinos.

**Comment by bartlettroscoe** [comment]
FYI: PR #3612 removes Sundance from the list of offical extra repos for Trilinos.  NOTE: One can always just clone the Sundance repo under Trilinos/packages and Trilinos will still automatically build it.  But the TriBITS CTest -S driver script will no longer clone it or update it.

@william76, @jwillenbring, or @prwolfe, can one of you please approve PR #3612 so that it can be merged?

**Comment by bartlettroscoe** [comment]
PR #3612 merged yesterday did not make the configure error in the build `Linux-GCC-4.9.3-openmpi-1.8.7_Debug_DEV_Werror` go away as shown today [here](https://testing.sandia.gov/cdash-dev-view/index.php?project=Trilinos&parentid=4046397).  The problem is that the Sundance repo is already cloned in the right place on the nightly testing machine and therefore it gets picked up automatically due to the listing of `packages/sundance` in the file `Trilinos/PackagesList.cmake` as an "inserted package".  So we can either remove the listing of Sundance from `Trilinos/PackagesList.cmake` or we can wipe the cloned repos from the job `Linux-GCC-4.9.3-openmpi-1.8.7_Debug_DEV_Werror`.  The disadvantage if removing `packages/sundance` in the file `Trilinos/PackagesList.cmake` is that it will not allow someone to try to build Sundance against Trilinos anymore (but that can be fixed by treating it as an extra TriBITS repo by adding two trivial files).  But since no one is likely going to try to build Sundance against Trilinos, I doubt this matters.

I guess the right thing to do is to just remove `packages/sundance` in the file `Trilinos/PackagesList.cmake`.  I will do this in a new PR.

**Comment by bartlettroscoe** [comment]
I posted PR #3621 that will fix this build by removing Sundance without having to blow away the existing clones.

@william76, @jwillenbring, or @prwolfe, can one of you please approve PR #3621 so that it can be merged?

**Comment by mhoemmen** [comment]
Done!
