### ISSUE TITLE
PyTrilinos: Cherry-pick recent fixes into 12.14 release branch

### ISSUE THREAD

**Issue by wfspotz** [trilinos/Trilinos#3615]
@trilinos/pytrilinos 

## Expectations
PyTrilinos should compile and install, and all tests should pass for the 12.14 release. Since PyTrilinos is not yet part of nightly or PR testing, this verification has to be done separately.

## Current Behavior
There are installation and testing errors for PyTrilinos in the current 12.14 branch. These problems have been fixed on the develop branch, so cherry-picking the appropriate commits should be all that is required.

## Definition of Done
Under the 12.14 branch:
For Python 2:
- [x] PyTrilinos configures correctly for all wrapped packages, with the possible exception of Tpetra
- [x] PyTrilinos builds without errors for this configuration
- [x] PyTrilinos can be installed into an installation directory without errors
- [x] All tests and examples pass within the build directory
- [x] All packages can be manually `import`ed into python successfully from the installed version

For Python 3:
- [x] PyTrilinos configures correctly for all wrapped packages, with the possible exception of Tpetra
- [x] PyTrilinos builds without errors for this configuration
- [x] PyTrilinos can be installed into an installation directory without errors
- [x] All tests and examples pass within the build directory
- [x] All packages can be manually `import`ed into python successfully from the installed version

**Comment by jwillenbring** [comment]
> @jwillenbring is there a process for merging to to 12.14 branch? Can we just do a pull request like we do for develop? Will that initiate automatic testing?

@wfspotz Yes, that is now the process. We just recently set this up.
