### ISSUE TITLE
Amesos2 doesn't build most of its examples

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#3629]
@trilinos/amesos2 

All but one of the Amesos2 examples in `amesos2/example/CMakeLists.txt` are commented out.  That means they aren't tested and we don't even know if they build.  Did somebody not know what CMake options they needed to use?

**Comment by srajama1** [comment]
This is strange and I don't know why. We will investigate. Thanks for reporting it.

**Comment by mhoemmen** [comment]
@ndellingwood
