### ISSUE TITLE
Add support for 'release-debug' build for ATDM Trilinos builds and use to avoid timeouts

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#3633]
CC: @fryeguy52, @mhoemmen, @rppawlo, @bathmatt, @micahahoward, @trilinos/kokkos, @trilinos/kokkos-kernels 

## Description

Currently, the ATDM Trilinos builds support `debug` and an `opt` build.  The `debug` build uses `CMAKE_BUILD_TYPE=DEBUG` (with `-O0`) and enables runtime debug-mode checking while the `opt` build uses `CMAKE_BUILD_TYPE=RELEASE` (with `-O3`) and no runtime debug-mode checking.  The problem with this approach is that some of the Trilinos tests (especially many of the Kokkos and KokkosKernels tests) run many times slower wtih `-O0` than with `-O3`.  This has caused many tests to timeout at 10 minutes in `debug` builds that finish is well under 10 minutes in `opt` builds (e.g. #2964, #2921, #2461).

A solution that we discussed was to change most `debug` builds into `release-debug` builds that will set `CMAKE_BUILD_TYPE=RELEASE` (with `-O3`) but enable runtime debug-mode checking.

## Proposed solution 

The idea would be to add a new `release-debug` keyword that matches before `opt` or `debug` which will set `ATDM_CONFIG_BUILD_TYPE=RELEASE_DEBUG` and then update the file `ATDMDevEnvSettings.cmake` accordingly.  That will be easy.  The harder part will be updating the tweaks `*.cmake` files and all of the Jenkins jobs to accommodate the name change.  NOTE: calling this `release-debug` as apposed to `opt-debug` hopefully might be more clear.

We can still leave some full `debug` builds to help support full GDB debugging by the ATDM APPs teams but they should be sparing (because we are constantly dealing with timeouts with full debug builds).

## Tasks:

* ???

**Comment by bartlettroscoe** [comment]
FYI: I think we should call this new build type `release-debug` instead of `opt-debug` since that might be more clear.

**Comment by bartlettroscoe** [comment]
CC: @fryeguy52, @trilinos/intrepid2, @trilinos/piro, @trilinos/framework

After the merge of #3659 yesterday, the new `release-debug` builds on 'waterman' today shown [here](https://testing.sandia.gov/cdash-dev-view/queryTests.php?project=Trilinos&date=2018-10-18&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-waterman-&field2=buildname&compare2=63&value2=release-debug&field3=status&compare3=62&value3=passed) are actually showing some new failures in the Intrepid2 and Piro packages that did not occur in the `opt` or `debug` builds on that machine.  We will create separate Trilinos GitHub issues for those failures but I thought that it would be useful to point this out here.  

What this shows is that there is some code in Trilinos that behaves differently on some platforms with optimized compiler flags and runtime debug checking turned on compared to builds with non-optimized compiler flags and debug checking disabled.  What is interested is that the GCC 4.8.4 + OpenMPI 1.10.1 + OpenMP build actually uses optimized compiler flags with runtime debug checking enabled so it is not like were don't have testing for this code path in PR testing. We just don't test all platforms in PR testing (obviously).

If I was a Trilinos customer, my default development build would be against a `release-debug` build instead of a `debug` build because the code runs pretty fast but still checks for runtime errors and reports them nicely.  Therefore, that `release-debug` builds should be higher priority to test than `debug` or even `opt`/`release` builds.

**Comment by mperego** [comment]
@bartlettroscoe  I had a look at the failures and they seem to be all due to tolerances being too tight. I can try to fix this later today or tomorrow

**Comment by bartlettroscoe** [comment]
I was going to switch over more `debug` builds to `release-debug` builds on platforms where we had disabled tests that were timing out but given the new failures that are appearing in the `release-debug` builds on 'waterman' I describe above, I think that I am going to punt on this for now.  If we get new timing out tests in only the `debug` builds but not the `opt` builds on these other platforms, then we can switch some of these `debug` builds over to `release-debug` builds.

Therefore, I am going to close this issue and we will deal with the new failures in other issues.

**Comment by bartlettroscoe** [comment]
> @bartlettroscoe I had a look at the failures and they seem to be all due to tolerances being too tight. I can try to fix this later today or tomorrow

@mperego, these same failures have been happening in lots of other builds as well as described in #2747.  Let's continue the discuss on the Piro test failure there.

**Comment by bartlettroscoe** [comment]
@mperego, sorry, the issue for the Piro test failures is #2474.
