### ISSUE TITLE
Teko_testdriver_tpetra_MPI_1 Failing in ATDM cee-rhel6-clang-opt-serial build

### ISSUE THREAD

**Issue by fryeguy52** [trilinos/Trilinos#3637]
CC: @trilinos/teko , @srajama1  (Trilinos Linear Solvers Product Lead), @bartlettroscoe 
 
## Next Action Status

Test has filed every day for 4 days starting 10/12/2018 when this build was set up till 10/17/2018 but passed on 10/18/2018 as shown [here](https://testing.sandia.gov/cdash-dev-view/queryTests.php?project=Trilinos&date=2018-10-18&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-cee-rhel6-clang-opt-serial&field2=testname&compare2=61&value2=Teko_testdriver_tpetra_MPI_1&field3=buildstarttime&compare3=83&value3=2018-10-10).  Next: Watch test for next few days to see if this test keeps passing ...

## Description

As shown in [this query](https://testing.sandia.gov/cdash-dev-view/queryTests.php?project=Trilinos&date=2018-10-15&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-cee-rhel6-&field2=status&compare2=62&value2=passed) the tests:

* Teko_testdriver_tpetra_MPI_1

are failing in the builds:
* Trilinos-atdm-cee-rhel6-clang-opt-serial

This was failing on the rhel6 sems environment jobs earlier and the solution was a tageted disabling of part of the test.  Is this the same issue? see #2656

```
Test "LSCStabilized_tpetra" completed ... FAILED (1)
```
...
```
Tests Passed: 85, Tests Failed: 1
(Incidently, you want no failures)
Teko tests failed
```

## Steps to Reproduce

One should be able to reproduce this failure any CEE LAN RHEL6 SRN machine as described in:
* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md
More specifically, the commands given for the CEE LAN RHEL6 SRN machines are provided at:
* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#cee-rhel6-environment
The exact commands to reproduce this issue should be:
```
$ cd <some_build_dir>/

$ source $TRILINOS_DIR/cmake/std/atdm/load-env.sh cee-rhel6-clang-opt-serial

$ cmake \
  -GNinja \
  -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
  -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_Teko=ON \
  $TRILINOS_DIR

$ make NP=16

$ ctest -j16
```

**Comment by bartlettroscoe** [comment]
Hum, this test passed today in this build as shown [here](https://testing.sandia.gov/cdash-dev-view/viewTest.php?onlydelta&buildid=4064302).  I guess we should wait and see what this test does over the next couple of days to see if this is a randomly failing test or not.

**Comment by bartlettroscoe** [comment]
Okay, as shown [here](https://testing.sandia.gov/cdash-dev-view/queryTests.php?project=Trilinos&date=2018-10-18&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-cee-rhel6-clang-opt-serial&field2=testname&compare2=61&value2=Teko_testdriver_tpetra_MPI_1&field3=buildstarttime&compare3=83&value3=2018-10-10), this is the third consecutive day in a row that the test `Teko_testdriver_tpetra_MPI_1` passed in the build `Trilinos-atdm-cee-rhel6-clang-opt-serial` where it failed three consecutive days before that.  It is not clear what changed to allow this pass but some change pulled on 10/18/2018 shown [here](https://testing.sandia.gov/cdash-dev-view/viewNotes.php?buildid=4064282#!#note6) must have caused this test to pass.

Therefore, it seems obvious that this test passing is not a fluke so I will close this issue.
