### ISSUE TITLE
Teko_ModALPreconditioner_MPI_1 Failing in build Trilinos-atdm-cee-rhel6-clang-5.0.1-openmpi-1.10.2-serial-static-opt

### ISSUE THREAD

**Issue by fryeguy52** [trilinos/Trilinos#3638]
CC: @trilinos/teko , @srajama1  (Trilinos Linear Solvers Product Lead), @bartlettroscoe 
 
## Next Action Status

With the merge of PR #4079 to 'develop' on 12/19/2018, this test `Teko_ModALPreconditioner_MPI_1` is disabled and shown missing in the build `Trilinos-atdm-cee-rhel6-clang-5.0.1-openmpi-1.10.2-serial-static-opt ` on 12/20/2018.

## Description

As shown in [this query](https://testing.sandia.gov/cdash-dev-view/queryTests.php?project=Trilinos&date=2018-10-15&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-cee-rhel6-&field2=status&compare2=62&value2=passed) the tests:

* Teko_ModALPreconditioner_MPI_1

are failing in the builds:
* Trilinos-atdm-cee-rhel6-clang-opt-serial

failing from a seg fault:
```
[ceerws1113:36105] *** Process received signal ***
[ceerws1113:36105] Signal: Segmentation fault (11)
[ceerws1113:36105] Signal code: Address not mapped (1)
[ceerws1113:36105] Failing at address: (nil)
```

## Steps to Reproduce

One should be able to reproduce this failure any CEE LAN RHEL6 SRN machine as described in:
* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md

More specifically, the commands given for the CEE LAN RHEL6 SRN machines are provided at:
* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#cee-rhel6-environment

The exact commands to reproduce this issue should be:
```
$ cd <some_build_dir>/

$ source $TRILINOS_DIR/cmake/std/atdm/load-env.sh cee-rhel6-clang-opt-serial

$ cmake \
  -GNinja \
  -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
  -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_Teko=ON \
  $TRILINOS_DIR

$ make NP=16

$ ctest -j16
```

**Comment by srajama1** [comment]
@trilinos/teko

**Comment by srajama1** [comment]
@eric-c-cyr Do you have some time to look at this and assign it to the appropriate person please ?

**Comment by bartlettroscoe** [comment]
> @eric-c-cyr Do you have some time to look at this and assign it to the appropriate person please ?

@srajama1, @eric-c-cyr, and @rppawlo,

Do we know if SPARC or EMPIRE is using Teko functionality protected by this test?  If not, then can we mark this as "ATDM Nonblocker"?  That is really the first step so that we know the importance of this failing test as it impacts ATDM.  (But just because ATDM is not being impacted does not mean we should not fix it as it may impact other important Trilinos customers.)

**Comment by eric-c-cyr** [comment]
No one on earth is using this capability.

**Comment by bartlettroscoe** [comment]
@eric-c-cyr said:

> No one on earth is using this capability.

In this case, I added "ATDM Nonblocking" label and I think we should just disable this test for this build.  (Seems okay okay to keep it running in the other builds where it is passing or should we disable this in all ATDM Trilinos builds.)

@eric-c-cyr or @srajama1, should we disable for just this build or for all ATDM Trilinos builds?

**Comment by eric-c-cyr** [comment]
This is fine with me.

**Comment by srajama1** [comment]
Fine with me as well.

**Comment by bartlettroscoe** [comment]
> Fine with me as well. I should say disable for all ATDM builds to avoid another issue in some other ATDM platform in future. However, we need to reenable if ATDM starts using it. I believe that will be the responsibility of the Teko developers who will recommend its usage, so this model is fine.

@srajama1, Thanks!  Will do!

**Comment by bartlettroscoe** [comment]
With the merge of PR #4079 to 'develop' on 12/19/2018, these this should now be disabled in this `Trilinos-atdm-cee-rhel6-clang-opt-serial` build.  Next: Confirm this test is disabled in this build on 12/20/2018 ...
