### ISSUE TITLE
Sacado_view_example_MPI_1 on ATDM cee-rhel6-intel-opt-serial build

### ISSUE THREAD

**Issue by fryeguy52** [trilinos/Trilinos#3639]
CC: @trilinos/sacado  , @rppawlo  (Trilinos Nonlinear Solvers Product Lead), @bartlettroscoe 
 
## Description

As shown in [this query](https://testing.sandia.gov/cdash-dev-view/queryTests.php?project=Trilinos&date=2018-10-15&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-cee-rhel6-&field2=status&compare2=62&value2=passed) the tests:

* Sacado_view_example_MPI_1

are failing in the builds:
* Trilinos-atdm-cee-rhel6-intel-opt-serial

test output:
```
===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   PID 14938 RUNNING AT ceerws1113
=   EXIT CODE: 139
=   CLEANING UP REMAINING PROCESSES
=   YOU CAN IGNORE THE BELOW CLEANUP MESSAGES
===================================================================================
```

## Steps to Reproduce

One should be able to reproduce this failure any CEE LAN RHEL6 SRN machine as described in:
* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md

More specifically, the commands given for the CEE LAN RHEL6 SRN machines are provided at:
* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#cee-rhel6-environment

The exact commands to reproduce this issue should be:
```
$ cd <some_build_dir>/

$ source $TRILINOS_DIR/cmake/std/atdm/load-env.sh cee-rhel6-intel-opt-serial

$ cmake \
  -GNinja \
  -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
  -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_Sacado=ON \
  $TRILINOS_DIR

$ make NP=16

$ ctest -j16
```

**Comment by bartlettroscoe** [comment]
PR #3664 merged on 10/16/2018 fixed the test when ran on 10/17/2018 as shown newly passing in this build [here](https://testing.sandia.gov/cdash-dev-view/viewTest.php?onlydelta&buildid=4060500).

Closing as complete.

Thanks for fixing @etphipp!

**Comment by bartlettroscoe** [comment]
Closing for real
