### ISSUE TITLE
Compilation error due to seacas on some platforms

### ISSUE THREAD

**Issue by ikalash** [trilinos/Trilinos#3663]
Trilinos failed to compile in last night's Albany tests on the NERSC machines (Cori, Edison) and some machines at SNL (@lxmota 's Fedora 28 machine, algol) due to what appears to be a seacas issue:
```
repos/Trilinos/packages/seacas/libraries/exodus/src/ex_utils.c:1664:17: error: 'exoid' undeclared (first use in this function); did you mean 'exit'?
```
The full output can be found here: https://my.cdash.org/viewBuildError.php?buildid=1545426 or here: http://cdash.sandia.gov/CDash-2-3-0/viewBuildError.php?buildid=77215 .  Curiously enough the problem didn't occur in the other Albany nightly tests, so it may be machine/compiler-specific or due to the specific NERSC configuration.  

@trilinos/seacas

**Comment by mhoemmen** [comment]
@gsjaardema

**Comment by mhoemmen** [comment]
This may be related to the recent PR https://github.com/trilinos/Trilinos/pull/3657 .

**Comment by spdomin** [comment]
Yes, same with Nalu - only on Mac clang 9.1.0 and neither gcc 7.2 not intel:

> /Users/naluIt/gitHubWork/nightlyBuildAndTest/Trilinos/packages/seacas/libraries/exodus/src/ex_utils.c:1527:15: error: 
>       use of undeclared identifier 'exoid'; did you mean 'exit'?
>     ex_err_fn(exoid, __func__, errmsg, EX_BADPARAM);
>               ^~~~~
>               exit
> /usr/include/stdlib.h:150:7: note: 'exit' declared here
> void     exit(int) __dead2;

**Comment by spdomin** [comment]
Same on this side - feel free to close.

**Comment by djlittl** [comment]
@gsjaardema

I ran into this glitch today.  It looks like a possible bug to me.  In the file ex_create_group.c, if NC_HAS_HDF5 is not defined, then as far as I can tell, exoid is not defined:

int ex_create_group(int parent_id, const char *group_name)
{
  char errmsg[MAX_ERR_LENGTH];
#if NC_HAS_HDF5
  int exoid = -1;
  int status;

  EX_FUNC_ENTER();
  ex_check_valid_file_id(parent_id, __func__);

  if ((status = nc_redef(parent_id)) != NC_NOERR) {
    snprintf(errmsg, MAX_ERR_LENGTH, "ERROR: failed to put file id %d into define mode", parent_id);
    ex_err_fn(exoid, __func__, errmsg, status);
    EX_FUNC_LEAVE(EX_FATAL);
  }

  if ((status = nc_def_grp(parent_id, group_name, &exoid)) != NC_NOERR) {
    snprintf(errmsg, MAX_ERR_LENGTH, "ERROR: group create failed for %s in file id %d", group_name,
             parent_id);
    ex_err_fn(exoid, __func__, errmsg, status);
    EX_FUNC_LEAVE(EX_FATAL);
  }

  if ((status = nc_enddef(parent_id)) != NC_NOERR) {
    snprintf(errmsg, MAX_ERR_LENGTH, "ERROR: failed to complete definition for file id %d", exoid);
    ex_err_fn(exoid, __func__, errmsg, status);
    EX_FUNC_LEAVE(EX_FATAL);
  }
  EX_FUNC_LEAVE(exoid);
#else
  EX_FUNC_ENTER();
  snprintf(errmsg, MAX_ERR_LENGTH,
           "ERROR: Group capabilities are not available in this netcdf "
           "version--not netcdf4");
  ex_err_fn(exoid, __func__, errmsg, NC_ENOTNC4);
  EX_FUNC_LEAVE(EX_FATAL);
#endif
}

**Comment by djlittl** [comment]
Looks like the difficulty was due to the way I compiled netcdf.  I originally used the following:

./configure --prefix=/my_path/TPL/netcdf/netcdf-4.6.1/GCC_4.9.2 --disable-netcdf-4 --disable-dap

which led to the "exoid undefined" error in my trilinos build.

I recompiled netcdf with:

CFLAGS="-I/my_path/TPL/hdf5/hdf5-1.10.2/GCC_4.9.2/include" LDFLAGS="-L/my_path/TPL/hdf5/hdf5-1.10.2/GCC_4.9.2/lib" ./configure --prefix=/my_path/TPL/netcdf/netcdf-4.6.1/GCC_4.9.2

and the "exoid undefined" error went away, presumably because building netcdf with hdf5 set the NC_HAS_HDF5 flag.

Still, it appears from the code in ex_create_group.c that the intention is to be able to build trilinos without hdf5 enabled in netcdf, in which case the ex_create_group() function would error out at runtime if called.

**Comment by ysp8293** [comment]
@djlittl 
In the CFLAGS path, which packages are pointed to the include & lib folder,  the gcc or the netcdf

**Comment by gsjaardema** [comment]
Sorry, didn't see this until today for some reason.  It should be possible to build without NC_HAS_HDF5 defined, so I will fix the error in `ex_create_group.c` and verify that there are no other issues related to this.

**Comment by djlittl** [comment]
@ysp8293 The command like for configuring netcdf contains CFLAGS and LDFLAGS that point to a hdf5 installation.

To be clear, in all cases I was building seacas with netcdf and hdf5.  The build error occurred when the netcdf build did not have hdf5 enabled.

What didn't work (but did in the past):
1) build hdf5
2) build netcdf without hdf5
3) build seacas with hdf5 and netcdf

What worked:
1) build hdf5
2) build netcdf with hdf5
3) build seacas with hdf5 and netcdf

**Comment by gsjaardema** [comment]
@djlittl Both of those configurations should now work.  The second is the preferred method as it gives you more options

**Comment by gsjaardema** [comment]
@djlittl Note that there is nothing in SEACAS itself that uses HDF5 directly.  Only the TPLs NetCDF, CGNS, and Mario use HDF5, so your first option should behave the same whether or not you build hdf5 (with respect to SEACAS behavior)
