### ISSUE TITLE
KokkosKernels: missing doxygen documentation

### ISSUE THREAD

**Issue by jhux2** [trilinos/Trilinos#3664]
KokkosKernels doesn't have any links to its Doxygen documentation on trilinos.org, at least not that I could find.  I think it would be useful to have doxygen available, similarly to what other Trilinos packages provide, e.g., [Tpetra](https://trilinos.org/docs/dev/packages/tpetra/doc/html/index.html).

**Comment by srajama1** [comment]
@jhux2  We don't do Doxygen, but use the wiki. I will add a link to the wiki.

**Comment by jhux2** [comment]
@srajama1 Thank you.  Are the interfaces for Kokkos_Sparse_CrsMatrix documented there somewhere?

**Comment by srajama1** [comment]
Nope, Sorry ! Will add that too. If you are looking for a specific functionality we can take it offline.
