### ISSUE TITLE
Intrepid2: "unreachable" code warning under CUDA

### ISSUE THREAD

**Issue by jhux2** [trilinos/Trilinos#3680]
I think I fixed similar issues in MueLu by just removing the break statement that's immediately after the return.  Btw, the warnings aren't a problem for me at all, so please prioritize as you see fit.
 
```
/home/jhu/software/trilinos/Trilinos/packages/intrepid2/src/Discretization/Basis/Intrepid2_HGRAD_TRI_Cn_FEM.hpp(290): warning: statement is unreachable
/home/jhu/software/trilinos/Trilinos/packages/intrepid2/src/Discretization/Basis/Intrepid2_HGRAD_TET_Cn_FEM.hpp(298): warning: statement is unreachable
/home/jhu/software/trilinos/Trilinos/packages/intrepid2/src/Discretization/Basis/Intrepid2_HVOL_TRI_Cn_FEM.hpp(106): warning: statement is unreachable
/home/jhu/software/trilinos/Trilinos/packages/intrepid2/src/Discretization/Basis/Intrepid2_HVOL_TRI_Cn_FEMDef.hpp(216): warning: statement is unreachable
```

@trilinos/intrepid2

**Comment by mperego** [comment]
@jhux2 thanks!!!

**Comment by jhux2** [comment]
@mperego Sure thing.  I realized that since I had the build on waterman already in place, it would be pretty simple to make the changes.  It's weird that the warnings don't show up on the ATDM dashboard, since I was ostensibly using the same configuration.
