### ISSUE TITLE
Intrepid2 unit tests failing in new ATDM 'release-debug' builds on 'waterman'

### ISSUE THREAD

**Issue by fryeguy52** [trilinos/Trilinos#3681]
CC: @trilinos/intrepid2 , @mperego  (Trilinos Discretizations Product Lead), @bartlettroscoe 
 
## Description
As shown in [this query](https://testing.sandia.gov/cdash-dev-view/queryTests.php?project=Trilinos&date=2018-10-18&filtercount=4&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-waterman-&field2=buildname&compare2=63&value2=release-debug&field3=testname&compare3=63&value3=Intrepid2_unit-test_Discretization_Basis_HDIV_TET&field4=status&compare4=62&value4=Passed) the tests:
* Intrepid2_unit-test_Discretization_Basis_HDIV_TET_In_FEM_Serial_Test_01_SLFadDouble_MPI_1
* Intrepid2_unit-test_Discretization_Basis_HDIV_TET_In_FEM_Serial_Test_01_SLFadDFad_MPI_1
* Intrepid2_unit-test_Discretization_Basis_HDIV_TET_In_FEM_Serial_Test_01_SFadSFad_MPI_1
* Intrepid2_unit-test_Discretization_Basis_HDIV_TET_In_FEM_Serial_Test_01_MPI_1
* Intrepid2_unit-test_Discretization_Basis_HDIV_TET_In_FEM_Cuda_Test_01_SFadSFad_MPI_1
* Intrepid2_unit-test_Discretization_Basis_HDIV_TET_In_FEM_Cuda_Test_01_MPI_1
* Intrepid2_unit-test_Discretization_Basis_HDIV_TET_In_FEM_Cuda_Test_01_DFadDFad_MPI_1

are failing in the builds:
* Trilinos-atdm-waterman-cuda-9.2-release-debug
* Trilinos-atdm-waterman-gnu-release-debug-openmp

## Steps to Reproduce

One should be able to reproduce this failure on waterman as described in:
* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md
More specifically, the commands given for waterman are provided at:
* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#waterman
The exact commands to reproduce this issue should be:
```
$ cd <some_build_dir>/

$ source $TRILINOS_DIR/cmake/std/atdm/load-env.sh cuda-9.2-release-debug

$ cmake \
  -GNinja \
  -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
  -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_Intrepid2=ON \
  $TRILINOS_DIR

$ make NP=20

$ bsub -x -Is -n 20 ctest -j20
```

**Comment by mperego** [comment]
@fryeguy52 thanks. I'll try to fix them soon. I think it is just a matter of tolerances being too tight.

**Comment by bartlettroscoe** [comment]
After the merge of PR #3688 yesterday, we are seeing these Intrepid2 tests newly passing in these builds today.

As shown [here](https://testing.sandia.gov/cdash-dev-view/index.php?project=Trilinos&parentid=4078320) , the 7 failing Intrepid2 tests for the build `Trilinos-atdm-waterman-cuda-9.2-release-debug` described in this Issue have bee fixed as of today (see the `-7` subscript and `+7` superscript for the number of failing and passing tests for Intrepid, respectfully).  And you can see the newly passing Intrepid2 tests for this build [here](https://testing.sandia.gov/cdash-dev-view/viewTest.php?onlydelta&buildid=4078325).

And we see 5 Intrepid2 tests newly passing today for the build `Trilinos-atdm-waterman-gnu-release-debug-openmp` [here](https://testing.sandia.gov/cdash-dev-view/index.php?project=Trilinos&parentid=4078964) and [here](https://testing.sandia.gov/cdash-dev-view/viewTest.php?onlydelta&buildid=4078969).

Closing as complete.
