### ISSUE TITLE
Move findRelOffset from TpetraCore into KokkosKernels

### ISSUE THREAD

**Issue by bathmatt** [trilinos/Trilinos#369]
So we can do fast sorted insertion we need to move findRelOffset from TpetraCore into KokkosKernels as a first step.  This is according to @mhoemmen 

@eric-c-cyr @rppawlo

**Comment by mhoemmen** [comment]
findRelOffset lives in tpetra/core/src/Tpetra_Util.hpp and is tested in TpetraCore.  We need to move the test into KokkosKernels as well.

**Comment by mhoemmen** [comment]
@bathmatt 's commit 1e65cffac05ae95bbc4e6f0d6d4d428886704834 relates to this.  Matt implemented a `sumIntoValuesSorted` method in `KokkosSparse::CrsMatrix`, and is using it in Panzer.  It looks pretty good -- thanks Matt! :-D  I'll open a new issue to discuss this further.
