### ISSUE TITLE
EpetraExt_MultiVectorIn.cpp not found in Waterman (CUDA) build for Albany

### ISSUE THREAD

**Issue by ikalash** [trilinos/Trilinos#3698]
In our Albany nightly testing on Waterman, Trilinos failed to compile, it looks like due to EpetraExt_MultiVectorIn not being found when compiling some Kokkos files: 
http://cdash.sandia.gov/CDash-2-3-0/viewBuildError.php?onlydeltap&buildid=77329

@trilinos/kokkos , @trilinos/kokkos-kernels

**Comment by mhoemmen** [comment]
@ikalash did you mean TpetraExt?

**Comment by mhoemmen** [comment]
@trilinos/tpetra @trilinos/epetra @trilinos/xpetra @trilinos/muelu 

@ikalash Hm, does albany disable EpetraExt?

**Comment by ikalash** [comment]
The problem has gone away on its own as mysteriously as it appeared.
