### ISSUE TITLE
Tpetra: cmake error when building with Clang + CUDA

### ISSUE THREAD

**Issue by Char-Aznable** [trilinos/Trilinos#3702]
@mhoemmen I'm getting this superfluous cmake error from cmake:
```cmake
Processing enabled package: Tpetra (Classic, TSQR, Core)
CMake Error at packages/tpetra/CMakeLists.txt:79 (MESSAGE):
  If building with CUDA, Tpetra and downstream packages require, at least
  with CUDA_VERSION >= 7.5 and <= 9.0, that you add "--expt-extended-lambda"
  to either Trilinos_CXX11_FLAGS or CMAKE_CXX_FLAGS.  You must also set
  Kokkos_ENABLE_Cuda_Lambda:BOOL=ON, if it is not already ON by default.
```
AFIK, `--expt-extended-lambda` is nvcc specific and doesn't apply to clang. Also, it should be `Trilinos_CXX_FLAGS` instead of `Trilinos_CXX11_FLAGS` that is checked here judging from the CMakeLists.txt

**Comment by Char-Aznable** [comment]
The cmake options are:
```
-DCMAKE_PREFIX_PATH=$BREW \
-DCMAKE_CXX_COMPILER=$CLANGBIN/clang++ \
-DCMAKE_C_COMPILER=$CLANGBIN/clang \
-DCMAKE_BUILD_TYPE=Debug \
-DCMAKE_CXX_FLAGS_DEBUG="-ggdb3 -O0" \
-DTrilinos_ENABLE_DEBUG=ON \
-DTrilinos_ENABLE_DEBUG_SYMBOLS=ON \
-DTrilinos_HIDE_DEPRECATED_CODE=ON \
-DTrilinos_ENABLE_Fortran=OFF \
-DTrilinos_ENABLE_ALL_PACKAGES=OFF \
-DTrilinos_ENABLE_ALL_OPTIONAL_PACKAGES=OFF \
-DTrilinos_ASSERT_MISSING_PACKAGES=OFF \
-DTrilinos_ENABLE_TESTS=OFF \
-DTrilinos_ENABLE_EXAMPLES=OFF \
-DTrilinos_ENABLE_Kokkos=ON \
-DTrilinos_ENABLE_ROL=ON \
-DTrilinos_ENABLE_Tpetra=ON \
-DKOKKOS_ENABLE_CUDA=ON \
-DKOKKOS_ENABLE_CUDA_UVM=ON \
-DKOKKOS_ARCH="SNB;Pascal61" \
-DKOKKOS_ENABLE_CUDA_LAMBDA=ON \
-DKOKKOS_DEBUG_CMAKE=yes \
-DKOKKOS_ENABLE_DEBUG=yes \
-DKOKKOS_ENABLE_DEPRECATED_CODE=OFF \
-DTpetra_INST_SERIAL=ON \
-DTpetra_INST_OPENMP=ON \
-DTrilinos_ENABLE_OpenMP=ON \
-DTPL_ENABLE_Pthread=OFF \
-DTPL_ENABLE_CUDA=ON \
-DTrilinos_ENABLE_EXPLICIT_INSTANTIATION=ON \
-DCMAKE_INSTALL_PREFIX=${BREW}/Cellar/Trilinos/${VERSION}

```

**Comment by mhoemmen** [comment]
Try setting `Trilinos_CXX11_FLAGS="-std=c++11 --expt-extended-lambda"`.

**Comment by mhoemmen** [comment]
@trilinos/tpetra

**Comment by Char-Aznable** [comment]
I believe `--expt-extended-lambda` is a nvcc specific thing and should not be set for clang

**Comment by mhoemmen** [comment]
You could also try setting `KOKKOS_ENABLE_CUDA_LAMBDA=ON` or the equivalent alternate Kokkos option.

**Comment by Char-Aznable** [comment]
`KOKKOS_ENABLE_CUDA_LAMBDA=ON` was set but still gave the error. I think checking for `--expt-extended-lambda` should be disabled in Tpetra's CMakeLists.txt if compiler is clang

**Comment by crtrott** [comment]
@Char-Aznable is right. This check for the --expt-extended-lambda should probably be removed or only be made if NVCC is used. KOKKOS_ENABLE_CUDA_LAMBDA is probably on automatically. That check was meant for the case where people didn't set KOKKOS_ARCH which would sidestep Kokkos process of modifying CXX flags.

**Comment by jjwilke** [comment]
This is still an issue. I was trying to play around with clang-cuda for performance and templight++ for compile time profiling and had to manually modify tpetra/CMakeLists.txt.

I suspect it's good enough to check if the compiler family is clang? And if not clang execute the check?

**Comment by mhoemmen** [comment]
@jjwilke From what I recall of our out-of-band discussions, I think this works now.  Please feel free to reopen this issue or open a new issue if it doesn't.  Thanks!

**Comment by jjwilke** [comment]
I don't think the changes are in master? But, yes, the Kokkos modifications and Trilinos promotion modifications will no longer check this.

**Comment by mhoemmen** [comment]
@jjwilke Thanks for the update! Does "master" refer to Kokkos:master?

**Comment by jjwilke** [comment]
Trilinos master.
