### ISSUE TITLE
MueLu: OpenMP Kokkos refactor failing unit-tests

### ISSUE THREAD

**Issue by lucbv** [trilinos/Trilinos#3717]
@trilinos/muelu @trilinos/xpetra 

## Expectations
This issue is opened to track progress on fixing tests that fail on [this](https://testing.sandia.gov/cdash/index.php?project=Trilinos&parentid=4083699) nightly build.

## Current Behavior
We have 7 tests failing and we would like to fix them.

## Motivation and Context
This goes along the work being done to enable KOKKOS_REFACTOR=ON by default when the node type is not Serial. It also allows us to monitor and prepare MueLu/Xpetra for the ATDM build that will enable the kokkos refactor.

## Definition of Done
All the tests need to pass or be guarded appropriately so that the build is clean.

## Related Issues
* Blocks #2674
* Related to #3703 #3689

**Comment by lucbv** [comment]
Looking at the [dashboard](
https://testing.sandia.gov/cdash/buildSummary.php?buildid=4094218) there is only one test still failing for this build, it looks like an issue with an Epetra tests that runs the kokkos refactor stack. Does it make sense? Do we need to modify the test so that it initializes the Kokkos memory space correctly?

**Comment by jhux2** [comment]
@lucbv Can the test check that `linAlgebra=Epetra` and set `kokkos refactor` off?

**Comment by lucbv** [comment]
I see that this build is clean today so I am closing this issue, thanks all for tackling these failures!
