### ISSUE TITLE
Trilinos compilation error on Ride and Waterman due to Xpetra 

### ISSUE THREAD

**Issue by ikalash** [trilinos/Trilinos#3727]
Trilinos failed to compile in the Albany nightlies on Ride and Waterman (CUDA KokkosNode) last night due to an issue in Xpetra:

http://cdash.sandia.gov/CDash-2-3-0/viewBuildError.php?buildid=77411
http://cdash.sandia.gov/CDash-2-3-0/viewBuildError.php?buildid=77406

@trilinos/xpetra

**Comment by ikalash** [comment]
@jhux2 : sure, here it is

```

  | https://github.com/gahansen/Albany/blob/master/repos/Trilinos/packages/xpetra/src/CrsGraph/Xpetra_TpetraCrsGraph.hpp
/.../repos/Trilinos/packages/stk/stk_topology/stk_topology/topology_type.tcc(248): here             instantiation of "void stk::topology::topology_type::permutation_nodes(const NodeArray &, unsigned int, NodeOutputIterator) [with Topology=stk::topology::HEX_20, NodeArray=stk::mesh::EntityVector, NodeOutputIterator=__gnu_cxx::__normal_iterator>>]"  /.../repos/Trilinos/packages/stk/stk_topology/stk_topology/topology.tcc(161): here             instantiation of "void stk::topology_detail::permutation_nodes_impl::operator()(Topology) const [with NodeArray=stk::mesh::EntityVector, NodeOutputIterator=__gnu_cxx::__normal_iterator>>, Topology=stk::topology::topology_type]"  /.../repos/Trilinos/packages/stk/stk_topology/stk_topology/apply_functor.tcc(176): here             instantiation of "stk::topology::apply_functor::result_type stk::topology::apply_functor::operator()(stk::topology::topology_t) [with Functor=stk::topology_detail::permutation_nodes_impl>>>]"  /.../repos/Trilinos/packages/stk/stk_topology/stk_topology/topology.tcc(161): here             instantiation of "void stk::topology::permutation_nodes(const NodeArray &, unsigned int, NodeOutputIterator) const [with NodeArray=stk::mesh::EntityVector, NodeOutputIterator=__gnu_cxx::__normal_iterator>>]"  /.../repos/Trilinos/packages/stk/stk_mesh/stk_mesh/baseImpl/elementGraph/SideConnector.cpp(78): here                          /.../repos/Trilinos/packages/xpetra/src/CrsGraph/Xpetra_TpetraCrsGraph.hpp(694): error: name followed by "::" must be a class or namespace name
/.../repos/Trilinos/packages/xpetra/src/CrsGraph/Xpetra_TpetraCrsGraph.hpp(694): error: name followed by "::" must be a class or namespace name
```
You should be able to access the links if you're on the SRN - perhaps you're just on Tbird wifi and this is why you can't?

**Comment by jhux2** [comment]
Thanks.

> You should be able to access the links if you're on the SRN - perhaps you're just on Tbird wifi and this is why you can't?

Nope, I'm on my SRN workstation, specifically, not on Tbird.

**Comment by jhux2** [comment]
@lucbv Could this be due to your recent changes to CrsGraph?

**Comment by ikalash** [comment]
Ok, thanks @alaw0 .  Please keep me posted.

**Comment by jewatkins** [comment]
@alanw0 @jhux2 In this case, it's a build error instead of a warning. Is there something we can turn off in our builds to get past the error while the stk team works on a fix (if it's going to take a while)?

**Comment by alanw0** [comment]
@jewatkins I only see warnings for the stk stuff (unless you have other output that I'm not seeing here). Looks like @jhux2 is looking at the Xpetra error.

**Comment by jewatkins** [comment]
@alanw0 oh sorry, I didn't notice that they were separate issues

**Comment by jhux2** [comment]
@ikalash @jewatkins I pushed a fix yesterday.  Can you confirm whether this fixed the Albany compilation?

**Comment by ikalash** [comment]
@jhux2 : unfortunately we still had a failed build last night on waterman as well as ride 

http://cdash.sandia.gov/CDash-2-3-0/viewBuildError.php?buildid=77447

**Comment by jhux2** [comment]
Argh, missed that line.  PR has been submitted.

**Comment by ikalash** [comment]
It appears this is fixed now.  Thanks @jhux2 .
