### ISSUE TITLE
Panzer:  Hessian Support Broken

### ISSUE THREAD

**Issue by jmgate** [trilinos/Trilinos#3728]
@trilinos/panzer 

## Description
@rppawlo, can you figure out how 63db1e5 broke Hessian support?  Looking at the diff, the best I can figure is maybe we should comment out
```c++
BASIS_VALUES_INSTANTIATION(panzer::Traits::HessianType)
```

in `Panzer_BasisValues2.cpp`, but I really haven't wrapped my head around that change-set yet.

## Current Behavior
The `PanzerAdaptersSTK_CurlLaplacianExample` is failing when Hessian support is turned on.

<details>
<summary>Test output (click to expand)</summary>
<code>
<pre>
140/169 Test #133: PanzerAdaptersSTK_CurlLaplacianExample ...........................***Failed  Required regular expression not found.Regex=[OVERALL FINAL RESULT: TEST PASSED .PanzerAdaptersSTK_CurlLaplacianExample.
]  1.33 sec

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

Advanced Test: PanzerAdaptersSTK_CurlLaplacianExample

Selected Test/CTest Propeties:
  CATEGORIES = BASIC
  PROCESSORS = 4
  TIMEOUT    = DEFAULT

Running test commands: TEST_0, TEST_1

================================================================================

TEST_0

Running: "/home/jmgate/toolchain/install/openmpi-3.0.0/bin/mpiexec" "-np" "4" "/workspace/build/trilinos/packages/panzer/adapters-stk/example/CurlLaplacianExample/PanzerAdaptersSTK_CurlLaplacianExample.exe" "--use-epetra" "--output-filename=base-curl-test-"

--------------------------------------------------------------------------------

Teuchos::GlobalMPISession::GlobalMPISession(): started processor with name s1002179.srn.sandia.gov and rank 1!
Teuchos::GlobalMPISession::GlobalMPISession(): started processor with name s1002179.srn.sandia.gov and rank 3!
Teuchos::GlobalMPISession::GlobalMPISession(): started processor with name s1002179.srn.sandia.gov and rank 2!
Teuchos::GlobalMPISession::GlobalMPISession(): started processor with name s1002179.srn.sandia.gov and rank 0!
terminate called after throwing an instance of 'std::runtime_error'
  what():  /workspace/Trilinos/packages/phalanx/src/Phalanx_EvaluationContainer_Def.hpp:146:

Throw number = 1

Throw test that evaluated to true: fields_.find((*var)->identifier()) == fields_.end()

Error: PHX::EvaluationContainer::postRegistrationSetup(): could not build a Kokkos::View for field named "HCurl:1:BasisPoints_coords_ref" of type "d" for the evaluation type "panzer::Traits::Hessian".
terminate called after throwing an instance of 'std::runtime_error'
  what():  /workspace/Trilinos/packages/phalanx/src/Phalanx_EvaluationContainer_Def.hpp:146:

Throw number = 1

Throw test that evaluated to true: fields_.find((*var)->identifier()) == fields_.end()

Error: PHX::EvaluationContainer::postRegistrationSetup(): could not build a Kokkos::View for field named "HCurl:1:BasisPoints_coords_ref" of type "d" for the evaluation type "panzer::Traits::Hessian".
[s1002179:59115] *** Process received signal ***
[s1002179:59114] *** Process received signal ***
[s1002179:59114] Signal: Aborted (6)
[s1002179:59114] Signal code:  (-6)
[s1002179:59115] Signal: Aborted (6)
[s1002179:59115] Signal code:  (-6)
[s1002179:59114] [ 0] [s1002179:59115] [ 0] /usr/lib64/libpthread.so.0(+0xf680)[0x7f46e6454680]
[s1002179:59115] [ 1] /usr/lib64/libpthread.so.0(+0xf680)[0x7f1e1a327680]
[s1002179:59114] [ 1] /usr/lib64/libc.so.6(gsignal+0x37)[0x7f46e60ae207]
[s1002179:59115] [ 2] /usr/lib64/libc.so.6(gsignal+0x37)[0x7f1e19f81207]
[s1002179:59114] [ 2] /usr/lib64/libc.so.6(abort+0x148)[0x7f46e60af8f8]
[s1002179:59115] [ 3] /usr/lib64/libc.so.6(abort+0x148)[0x7f1e19f828f8]
[s1002179:59114] [ 3] /home/jmgate/toolchain/install/gcc-7.3.0/lib64/libstdc++.so.6(_ZN9__gnu_cxx27__verbose_terminate_handlerEv+0x125)[0x7f46e6c0b205]
[s1002179:59115] [ 4] /home/jmgate/toolchain/install/gcc-7.3.0/lib64/libstdc++.so.6(_ZN9__gnu_cxx27__verbose_terminate_handlerEv+0x125)[0x7f1e1aade205]
[s1002179:59114] [ 4] /home/jmgate/toolchain/install/gcc-7.3.0/lib64/libstdc++.so.6(+0x8efd6)[0x7f46e6c08fd6]
[s1002179:59115] [ 5] /home/jmgate/toolchain/install/gcc-7.3.0/lib64/libstdc++.so.6(+0x8efd6)[0x7f1e1aadbfd6]
[s1002179:59114] [ 5] /home/jmgate/toolchain/install/gcc-7.3.0/lib64/libstdc++.so.6(+0x8f021)[0x7f1e1aadc021]
[s1002179:59114] /home/jmgate/toolchain/install/gcc-7.3.0/lib64/libstdc++.so.6(+0x8f021)[0x7f46e6c09021]
[s1002179:59115] [ 6] /home/jmgate/toolchain/install/gcc-7.3.0/lib64/libstdc++.so.6(+0x8f264)[0x7f46e6c09264]
[s1002179:59115] [ 6] /home/jmgate/toolchain/install/gcc-7.3.0/lib64/libstdc++.so.6(+0x8f264)[0x7f1e1aadc264]
[s1002179:59114] [ 7] [ 7] /workspace/build/trilinos/packages/panzer/adapters-stk/example/CurlLaplacianExample/PanzerAdaptersSTK_CurlLaplacianExample.exe(_ZN3PHX19EvaluationContainerIN6panzer6Traits7HessianES2_E21postRegistrationSetupERKNS2_2SDERNS_12FieldManagerIS2_EERKb+0x521)[0x2e8a315]
[s1002179:59114] [ 8] /workspace/build/trilinos/packages/panzer/adapters-stk/example/CurlLaplacianExample/PanzerAdaptersSTK_CurlLaplacianExample.exe(_ZN3PHX19EvaluationContainerIN6panzer6Traits7HessianES2_E21postRegistrationSetupERKNS2_2SDERNS_12FieldManagerIS2_EERKb+0x521)[0x2e8a315]
[s1002179:59115] [ 8] /workspace/build/trilinos/packages/panzer/adapters-stk/example/CurlLaplacianExample/PanzerAdaptersSTK_CurlLaplacianExample.exe(_ZN3PHX12FieldManagerIN6panzer6TraitsEE21postRegistrationSetupERKNS2_2SDERKb+0x8b)[0x2e757a1]
[s1002179:59114] [ 9] /workspace/build/trilinos/packages/panzer/adapters-stk/example/CurlLaplacianExample/PanzerAdaptersSTK_CurlLaplacianExample.exe(_ZN3PHX12FieldManagerIN6panzer6TraitsEE21postRegistrationSetupERKNS2_2SDERKb+0x8b)[0x2e757a1]
[s1002179:59115] [ 9] terminate called after throwing an instance of 'std::runtime_error'
  what():  /workspace/Trilinos/packages/phalanx/src/Phalanx_EvaluationContainer_Def.hpp:146:

Throw number = 1

Throw test that evaluated to true: fields_.find((*var)->identifier()) == fields_.end()

Error: PHX::EvaluationContainer::postRegistrationSetup(): could not build a Kokkos::View for field named "HCurl:1:BasisPoints_coords_ref" of type "d" for the evaluation type "panzer::Traits::Hessian".[s1002179:59113] *** Process received signal ***
[s1002179:59113] Signal: Aborted (6)
[s1002179:59113] Signal code:  (-6)
[s1002179:59113] [ 0] /usr/lib64/libpthread.so.0(+0xf680)[0x7ff815880680]
[s1002179:59113] [ 1] /usr/lib64/libc.so.6(gsignal+0x37)[0x7ff8154da207]
[s1002179:59113] [ 2] /usr/lib64/libc.so.6(abort+0x148)[0x7ff8154db8f8]
[s1002179:59113] [ 3] /home/jmgate/toolchain/install/gcc-7.3.0/lib64/libstdc++.so.6(_ZN9__gnu_cxx27__verbose_terminate_handlerEv+0x125)[0x7ff816037205]
[s1002179:59113] [ 4] /home/jmgate/toolchain/install/gcc-7.3.0/lib64/libstdc++.so.6(+0x8efd6)[0x7ff816034fd6]
[s1002179:59113] [ 5] /home/jmgate/toolchain/install/gcc-7.3.0/lib64/libstdc++.so.6(+0x8f021)[0x7ff816035021]
[s1002179:59113] [ 6] /home/jmgate/toolchain/install/gcc-7.3.0/lib64/libstdc++.so.6(+0x8f264)[0x7ff816035264]
[s1002179:59113] [ 7] /workspace/build/trilinos/packages/panzer/adapters-stk/example/CurlLaplacianExample/PanzerAdaptersSTK_CurlLaplacianExample.exe(_ZN6panzer19FieldManagerBuilder20setupBCFieldManagersERKSt6vectorINS_2BCESaIS2_EERKS1_IN7Teuchos3RCPINS_12PhysicsBlockEEESaISA_EERKNS7_3PtrIKNS_18EquationSetFactoryEEERKNS_35ClosureModelFactory_TemplateManagerINS_6TraitsEEERKNS_17BCStrategyFactoryERKNS7_13ParameterListERKNS_16LinearObjFactoryISM_EESV_+0x1512)[0x2e70454]
[s1002179:59115] [10] /workspace/build/trilinos/packages/panzer/adapters-stk/example/CurlLaplacianExample/PanzerAdaptersSTK_CurlLaplacianExample.exe(_ZN6panzer19FieldManagerBuilder20setupBCFieldManagersERKSt6vectorINS_2BCESaIS2_EERKS1_IN7Teuchos3RCPINS_12PhysicsBlockEEESaISA_EERKNS7_3PtrIKNS_18EquationSetFactoryEEERKNS_35ClosureModelFactory_TemplateManagerINS_6TraitsEEERKNS_17BCStrategyFactoryERKNS7_13ParameterListERKNS_16LinearObjFactoryISM_EESV_+0x1512)[0x2e70454]
[s1002179:59114] [10] /workspace/build/trilinos/packages/panzer/adapters-stk/example/CurlLaplacianExample/PanzerAdaptersSTK_CurlLaplacianExample.exe(_ZN6panzer19FieldManagerBuilder20setupBCFieldManagersERKSt6vectorINS_2BCESaIS2_EERKS1_IN7Teuchos3RCPINS_12PhysicsBlockEEESaISA_EERKNS_18EquationSetFactoryERKNS_35ClosureModelFactory_TemplateManagerINS_6TraitsEEERKNS_17BCStrategyFactoryERKNS7_13ParameterListERKNS_16LinearObjFactoryISJ_EESS_+0x66)[0x2b05c3c]
[s1002179:59115] [11] /workspace/build/trilinos/packages/panzer/adapters-stk/example/CurlLaplacianExample/PanzerAdaptersSTK_CurlLaplacianExample.exe(_ZN6panzer19FieldManagerBuilder20setupBCFieldManagersERKSt6vectorINS_2BCESaIS2_EERKS1_IN7Teuchos3RCPINS_12PhysicsBlockEEESaISA_EERKNS_18EquationSetFactoryERKNS_35ClosureModelFactory_TemplateManagerINS_6TraitsEEERKNS_17BCStrategyFactoryERKNS7_13ParameterListERKNS_16LinearObjFactoryISJ_EESS_+0x66)[0x2b05c3c]
[s1002179:59114] [11] /workspace/build/trilinos/packages/panzer/adapters-stk/example/CurlLaplacianExample/PanzerAdaptersSTK_CurlLaplacianExample.exe(_ZN3PHX19EvaluationContainerIN6panzer6Traits7HessianES2_E21postRegistrationSetupERKNS2_2SDERNS_12FieldManagerIS2_EERKb+0x521)[0x2e8a315]
[s1002179:59113] [ 8] /workspace/build/trilinos/packages/panzer/adapters-stk/example/CurlLaplacianExample/PanzerAdaptersSTK_CurlLaplacianExample.exe(main+0x4027)[0x2af769f]
[s1002179:59115] [12] /usr/lib64/libc.so.6(__libc_start_main+0xf5)[0x7f46e609a3d5]
[s1002179:59115] [13] /workspace/build/trilinos/packages/panzer/adapters-stk/example/CurlLaplacianExample/PanzerAdaptersSTK_CurlLaplacianExample.exe(main+0x4027)[0x2af769f]
[s1002179:59114] [12] /usr/lib64/libc.so.6(__libc_start_main+0xf5)[0x7f1e19f6d3d5]
[s1002179:59114] [13] /workspace/build/trilinos/packages/panzer/adapters-stk/example/CurlLaplacianExample/PanzerAdaptersSTK_CurlLaplacianExample.exe[0x2af35c9]
[s1002179:59115] *** End of error message ***
/workspace/build/trilinos/packages/panzer/adapters-stk/example/CurlLaplacianExample/PanzerAdaptersSTK_CurlLaplacianExample.exe[0x2af35c9]
[s1002179:59114] *** End of error message ***
/workspace/build/trilinos/packages/panzer/adapters-stk/example/CurlLaplacianExample/PanzerAdaptersSTK_CurlLaplacianExample.exe(_ZN3PHX12FieldManagerIN6panzer6TraitsEE21postRegistrationSetupERKNS2_2SDERKb+0x8b)[0x2e757a1]
[s1002179:59113] [ 9] /workspace/build/trilinos/packages/panzer/adapters-stk/example/CurlLaplacianExample/PanzerAdaptersSTK_CurlLaplacianExample.exe(_ZN6panzer19FieldManagerBuilder20setupBCFieldManagersERKSt6vectorINS_2BCESaIS2_EERKS1_IN7Teuchos3RCPINS_12PhysicsBlockEEESaISA_EERKNS7_3PtrIKNS_18EquationSetFactoryEEERKNS_35ClosureModelFactory_TemplateManagerINS_6TraitsEEERKNS_17BCStrategyFactoryERKNS7_13ParameterListERKNS_16LinearObjFactoryISM_EESV_+0x1512)[0x2e70454]
[s1002179:59113] [10] /workspace/build/trilinos/packages/panzer/adapters-stk/example/CurlLaplacianExample/PanzerAdaptersSTK_CurlLaplacianExample.exe(_ZN6panzer19FieldManagerBuilder20setupBCFieldManagersERKSt6vectorINS_2BCESaIS2_EERKS1_IN7Teuchos3RCPINS_12PhysicsBlockEEESaISA_EERKNS_18EquationSetFactoryERKNS_35ClosureModelFactory_TemplateManagerINS_6TraitsEEERKNS_17BCStrategyFactoryERKNS7_13ParameterListERKNS_16LinearObjFactoryISJ_EESS_+0x66)[0x2b05c3c]
[s1002179:59113] [11] /workspace/build/trilinos/packages/panzer/adapters-stk/example/CurlLaplacianExample/PanzerAdaptersSTK_CurlLaplacianExample.exe(main+0x4027)[0x2af769f]
[s1002179:59113] [12] /usr/lib64/libc.so.6(__libc_start_main+0xf5)[0x7ff8154c63d5]
[s1002179:59113] [13] /workspace/build/trilinos/packages/panzer/adapters-stk/example/CurlLaplacianExample/PanzerAdaptersSTK_CurlLaplacianExample.exe[0x2af35c9]
[s1002179:59113] *** End of error message ***
terminate called after throwing an instance of 'std::runtime_error'
  what():  /workspace/Trilinos/packages/phalanx/src/Phalanx_EvaluationContainer_Def.hpp:146:

Throw number = 1

Throw test that evaluated to true: fields_.find((*var)->identifier()) == fields_.end()

Error: PHX::EvaluationContainer::postRegistrationSetup(): could not build a Kokkos::View for field named "HCurl:1:BasisPoints_coords_ref" of type "d" for the evaluation type "panzer::Traits::Hessian".
[s1002179:59116] *** Process received signal ***
[s1002179:59116] Signal: Aborted (6)
[s1002179:59116] Signal code:  (-6)
[s1002179:59116] [ 0] /usr/lib64/libpthread.so.0(+0xf680)[0x7f767bf18680]
[s1002179:59116] [ 1] /usr/lib64/libc.so.6(gsignal+0x37)[0x7f767bb72207]
[s1002179:59116] [ 2] /usr/lib64/libc.so.6(abort+0x148)[0x7f767bb738f8]
[s1002179:59116] [ 3] /home/jmgate/toolchain/install/gcc-7.3.0/lib64/libstdc++.so.6(_ZN9__gnu_cxx27__verbose_terminate_handlerEv+0x125)[0x7f767c6cf205]
[s1002179:59116] [ 4] /home/jmgate/toolchain/install/gcc-7.3.0/lib64/libstdc++.so.6(+0x8efd6)[0x7f767c6ccfd6]
[s1002179:59116] [ 5] /home/jmgate/toolchain/install/gcc-7.3.0/lib64/libstdc++.so.6(+0x8f021)[0x7f767c6cd021]
[s1002179:59116] [ 6] /home/jmgate/toolchain/install/gcc-7.3.0/lib64/libstdc++.so.6(+0x8f264)[0x7f767c6cd264]
[s1002179:59116] [ 7] /workspace/build/trilinos/packages/panzer/adapters-stk/example/CurlLaplacianExample/PanzerAdaptersSTK_CurlLaplacianExample.exe(_ZN3PHX19EvaluationContainerIN6panzer6Traits7HessianES2_E21postRegistrationSetupERKNS2_2SDERNS_12FieldManagerIS2_EERKb+0x521)[0x2e8a315]
[s1002179:59116] [ 8] /workspace/build/trilinos/packages/panzer/adapters-stk/example/CurlLaplacianExample/PanzerAdaptersSTK_CurlLaplacianExample.exe(_ZN3PHX12FieldManagerIN6panzer6TraitsEE21postRegistrationSetupERKNS2_2SDERKb+0x8b)[0x2e757a1]
[s1002179:59116] [ 9] /workspace/build/trilinos/packages/panzer/adapters-stk/example/CurlLaplacianExample/PanzerAdaptersSTK_CurlLaplacianExample.exe(_ZN6panzer19FieldManagerBuilder20setupBCFieldManagersERKSt6vectorINS_2BCESaIS2_EERKS1_IN7Teuchos3RCPINS_12PhysicsBlockEEESaISA_EERKNS7_3PtrIKNS_18EquationSetFactoryEEERKNS_35ClosureModelFactory_TemplateManagerINS_6TraitsEEERKNS_17BCStrategyFactoryERKNS7_13ParameterListERKNS_16LinearObjFactoryISM_EESV_+0x1512)[0x2e70454]
[s1002179:59116] [10] /workspace/build/trilinos/packages/panzer/adapters-stk/example/CurlLaplacianExample/PanzerAdaptersSTK_CurlLaplacianExample.exe(_ZN6panzer19FieldManagerBuilder20setupBCFieldManagersERKSt6vectorINS_2BCESaIS2_EERKS1_IN7Teuchos3RCPINS_12PhysicsBlockEEESaISA_EERKNS_18EquationSetFactoryERKNS_35ClosureModelFactory_TemplateManagerINS_6TraitsEEERKNS_17BCStrategyFactoryERKNS7_13ParameterListERKNS_16LinearObjFactoryISJ_EESS_+0x66)[0x2b05c3c]
[s1002179:59116] [11] /workspace/build/trilinos/packages/panzer/adapters-stk/example/CurlLaplacianExample/PanzerAdaptersSTK_CurlLaplacianExample.exe(main+0x4027)[0x2af769f]
[s1002179:59116] [12] /usr/lib64/libc.so.6(__libc_start_main+0xf5)[0x7f767bb5e3d5]
[s1002179:59116] [13] /workspace/build/trilinos/packages/panzer/adapters-stk/example/CurlLaplacianExample/PanzerAdaptersSTK_CurlLaplacianExample.exe[0x2af35c9]
[s1002179:59116] *** End of error message ***
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpiexec noticed that process rank 1 with PID 0 on node s1002179 exited on signal 6 (Aborted).
--------------------------------------------------------------------------

--------------------------------------------------------------------------------

TEST_0: Return code = 134
TEST_0: Pass criteria = Match REGEX {ALL PASSED: Epetra} [FAILED]
TEST_0: Result = FAILED
</pre>
</code>
</details>

## Motivation and Context
I'm starting more Panzer refactoring, and I'm not sure if I'm breaking things.

## Definition of Done
This test passes with Hessian support on.  Or we give up on Hessian support altogether.

**Comment by rppawlo** [comment]
I'll take a look. It should be easy to fix.

**Comment by jmgate** [comment]
Should this be closed?

**Comment by rppawlo** [comment]
yeah - lets close this.
