### ISSUE TITLE
ATDM build config not valid for cuda

### ISSUE THREAD

**Issue by bathmatt** [trilinos/Trilinos#3746]
You do this in  $ATDM_SCRIPT_DIR/$ATDM_CONFIG_KNOWN_SYSTEM_NAME/environment.sh
 
  export OMPI_CXX=$ATDM_CONFIG_TRILNOS_DIR/packages/kokkos/bin/nvcc_wrapper

But that doesn't point to the installed nvcc_wrapper..  Therefore you can't build sub-cuda builds.

**Comment by bartlettroscoe** [comment]
@bathmatt, sorry about that.  I will fix that right away.  Stay tuned for PR.

**Comment by bartlettroscoe** [comment]
@bathmatt, will be fixed by the merge of PR #3746.  If you approve that PR, then it will merge tonight with automerge.

**Comment by bartlettroscoe** [comment]
With PR #3748 merged, this should be fixed.  @bathmatt can you please confirm that this fixes your usage and then close this issue?

**Comment by bathmatt** [comment]
Thought it autoclosed w/ the MR. closing
