### ISSUE TITLE
TrilinosCouplings build and test failures in the build Trilinos-atdm-white-ride-cuda-9.2-release-debug-pt starting 2018-10-24

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#3749]
@trilinos/trilinoscouplings, @jwillenbring (Trilinos Framework Product Area Lead), @trilinos/muelu, @lucbv 

## Next Action Status

Build and test errors were caused by merge of PR #3723 on 10/23/2018 that enabled this code by allowing the enable of `MueLu_ENABLE_Epetra=ON`.  Next: Fix or disable these tests?

## Description

As shown [here](https://testing.sandia.gov/cdash-dev-view/viewBuildError.php?buildid=4103503), the TrilinosCouplings example files `IntrepidPoisson_Pamgen_EpetraAztecOO_main.cpp` and `IntrepidPoisson_Pamgen_Epetra_main.cpp` starting failing to compile in the build `Trilinos-atdm-white-ride-cuda-9.2-release-debug-pt` on 'ride' and 'white' starting on 2018-10-27 showing the build errors:

```
/home/jenkins/ride/workspace/Trilinos-atdm-white-ride-cuda-9.2-release-debug-pt/SRC_AND_BUILD/Trilinos/teuchos/core/src/Teuchos_RCP.hpp(288): error: a value of type "MueLu::Hierarchy<TrilinosCouplings::EpetraIntrepidPoissonExample::ST, int, int, KokkosClassic::DefaultNode::DefaultNodeType> *" cannot be used to initialize an entity of type "MueLu::EpetraOperator::Hierarchy *"
          detected during instantiation of "Teuchos::RCP<T>::RCP(const Teuchos::RCP<T2> &) [with T=MueLu::EpetraOperator::Hierarchy, T2=MueLu::Hierarchy<TrilinosCouplings::EpetraIntrepidPoissonExample::ST, int, int, KokkosClassic::DefaultNode::DefaultNodeType>]" 
/home/jenkins/ride/workspace/Trilinos-atdm-white-ride-cuda-9.2-release-debug-pt/SRC_AND_BUILD/Trilinos/trilinoscouplings/examples/scaling/IntrepidPoisson_Pamgen_EpetraAztecOO_main.cpp(259): here

1 error detected in the compilation of "/tmp/tmpxft_00005fee_00000000-6_IntrepidPoisson_Pamgen_EpetraAztecOO_main.cpp1.ii".
```

and

```
/home/jenkins/ride/workspace/Trilinos-atdm-white-ride-cuda-9.2-debug-pt/SRC_AND_BUILD/Trilinos/teuchos/core/src/Teuchos_RCP.hpp(288): error: a value of type "MueLu::Hierarchy<TrilinosCouplings::EpetraIntrepidPoissonExample::ST, int, int, KokkosClassic::DefaultNode::DefaultNodeType> *" cannot be used to initialize an entity of type "MueLu::EpetraOperator::Hierarchy *"
          detected during instantiation of "Teuchos::RCP<T>::RCP(const Teuchos::RCP<T2> &) [with T=MueLu::EpetraOperator::Hierarchy, T2=MueLu::Hierarchy<TrilinosCouplings::EpetraIntrepidPoissonExample::ST, int, int, KokkosClassic::DefaultNode::DefaultNodeType>]" 
/home/jenkins/ride/workspace/Trilinos-atdm-white-ride-cuda-9.2-debug-pt/SRC_AND_BUILD/Trilinos/trilinoscouplings/examples/scaling/IntrepidPoisson_Pamgen_Epetra_main.cpp(286): here

1 error detected in the compilation of "/tmp/tmpxft_00006693_00000000-6_IntrepidPoisson_Pamgen_Epetra_main.cpp1.ii".
```

This results in the test failures shown, for example, [here](https://testing.sandia.gov/cdash-dev-view/viewTest.php?onlyfailed&buildid=4103503):

* TrilinosCouplings_Example_Maxwell_MueLu_MPI_1
* TrilinosCouplings_Example_Maxwell_MueLu_MPI_4

Looking at the history of the TrilinosCouplings build on 'ride' [here](https://testing.sandia.gov/cdash-dev-view/index.php?project=Trilinos&date=2018-10-27&filtercount=4&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-white-ride-cuda-9.2-debug-pt&field2=site&compare2=61&value2=ride&field3=subprojects&compare3=93&value3=TrilinosCouplings&field4=buildstarttime&compare4=83&value4=2018-09-26) we can see this these build failures started on 2018-10-24.

Looking at the git commits pulled that day shown [here](https://testing.sandia.gov/cdash-dev-view/viewNotes.php?buildid=4088183#!#note6), we see that the commits that likely caused by the PR #3722 with commits from @lucbv.

## Current Status on CDash

To see the current status of the build and tests for the current testing day and previous few days, click the below link:

* [TrilinosCouplings build and test results for 'Trilinos-atdm-white-ride-cuda-9.2-debug-pt' on 'ride'](https://testing.sandia.gov/cdash-dev-view/index.php?project=Trilinos&filtercount=4&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-white-ride-cuda-9.2-debug-pt&field2=site&compare2=61&value2=ride&field3=subprojects&compare3=93&value3=TrilinosCouplings&field4=buildstarttime&compare4=83&value4=10%20days%20ago)

NOTE: On above page, click on the "Start Time" column header to see the build results sorted by date.

## Steps to Reproduce

One should be able to reproduce these build errors on either 'white' or 'ride' by cloning the Trilinos git repo, checking out the 'develop' branch, creating a build directory, and then doing:

```
$ cd <some_build_dir>/

$ source $TRILINOS_DIR/cmake/std/atdm/load-env.sh cuda-9.2-release-debug

$ cmake \
  -GNinja \
  -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
  -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_TrilinosCouplings=ON \
  $TRILINOS_DIR

$ make NP=16

$ bsub -x -Is -q rhel7F -n 16 ctest -j16
```

**Comment by lucbv** [comment]
@bartlettroscoe I am rebuilding Trilinos on white and l will assess the damage there, it looks like some appropriate guards should be enough to prevent that Epetra test from running when CUDA is enable which does not make sense.
I'll let you know when I have a fix for that.

**Comment by bartlettroscoe** [comment]
Thanks @lucbv!  When the PR for this gets merged, please update this Issue and let us know.

**Comment by lucbv** [comment]
@bartlettroscoe, after further inspection, PR #3722 cannot have generated the new failures as it only changed xml files in `muelu` and these xml are not used in `trilinoscouplings`...
Furthermore, the build error reported and the test failures are unrelated, indeed if an example cannot build ctest will not try to run it.

I did look into the build failure and I am wondering why it is happening now, the only logical explanation is that someone changed the node type used in this example or the example was never run with the atdm: cuda-9.2-debug configuration until now?

I have submitted PR #3767 to fix the test build error, this won't fix the failing test at this time...

**Comment by lucbv** [comment]
@bartlettroscoe yes this test is guarded in `trilinoscouplings/examples/scaling/CMakeList.txt` with `IF(MueLu_ENABLE_Epetra)`.
At this point the two tests that were not building will build correctly.

**Comment by bartlettroscoe** [comment]
> At this point the two tests that were not building will build correctly.

@lucbv, great, thanks!  Once the Trilinos Framework gets a CUDA PR build running based on this build, then stuff like this will never break again.

**Comment by bartlettroscoe** [comment]
Merge of PR #3767 on 10/29/2018 resulted in the TrilinosCouplings build errors described above to go away on 10/30/2018 as shown [here](https://testing.sandia.gov/cdash-dev-view/index.php?project=Trilinos&parentid=4114263) (see the `-2` subscript by the `0` build errors for TrilinosCouplings).

Now that just leaves the two failing tests:

* TrilinosCouplings_Example_Maxwell_MueLu_MPI_1
* TrilinosCouplings_Example_Maxwell_MueLu_MPI_4

**Comment by bartlettroscoe** [comment]
Defects with Primary tested code not currently used (or being tested) by ATDM is not really an ATDM issue so I am removing the "client: ATDM" label to get this off our list of active issues.

**Comment by jhux2** [comment]
Closing, since CUDA version and platform are no longer relevant.
