### ISSUE TITLE
Framework: do Trilinos teams have repo read access?

### ISSUE THREAD

**Issue by jhux2** [trilinos/Trilinos#3761]
@trilinos/framework @srajama1 (product owner) @maherou @jwillenbring @bartlettroscoe 

I would like to be able to assign the @trilinos/muelu team as a reviewer for MueLu-related PRs.  According to [this](https://help.github.com/articles/requesting-a-pull-request-review/) page, this should be possible _if_ the team has read permission for the repo.

Question:  Do Trilinos teams have read permissions for the Trilinos repo?   If not, would it be possible to allow teams read access, or is there a good reason for not doing so?

**Comment by jhux2** [comment]
@csiefer2

**Comment by jhux2** [comment]
@trilinos/framework Some teams *can* review PRs.  I would like to request that @trilinos/muelu be added to that list.

![teams](https://user-images.githubusercontent.com/12970120/47673626-65794080-db72-11e8-8b4d-40495008d830.png)

**Comment by jmgate** [comment]
Please see the discussion on #2013.  If someone wants to give me the permissions, I'll be happy to set things up.

**Comment by csiefer2** [comment]
@jmgate What permissions do you need?

**Comment by jmgate** [comment]
The ability to give `trilinos` teams write access to the `Trilinos` repository.  I think that's **Admin** permissions to the `Trilinos` repo, but it might be **Owner** permissions to the `trilinos` organization (GitHub's permissions model makes less sense to me compared to GitLab's).  There are good reasons for not giving me either of those&mdash;I'm just saying I know how to hook you up, but my hands are tied.

**Comment by jmgate** [comment]
From GitHub support:

> You'll have to grant that team direct write access to the repository before the team can be requested as a reviewer:
> https://help.github.com/articles/managing-team-access-to-an-organization-repository

@jhux2, I'm not sure why some teams are available to request as reviewers while others aren't.  I know Panzer was given write access to test out the `CODEOWNERS` capability in #2013, but at the time I think the only teams with write access were Panzer and Framework.

**Comment by jhux2** [comment]
@jmgate Huh, that's different from what I found from 
https://help.github.com/articles/requesting-a-pull-request-review.

> Repository owners and collaborators can request a pull request review from anyone with read access to the repository. Organization members can also request a pull request review from teams with read access to the repository. The requested reviewer or team will receive a notification that you asked them to review the pull request.

But it sounds like you got information directly from a github human.

**Comment by jmgate** [comment]
My information is from January 2nd of this year, so something may have changed in the intervening months.  If read access is all that's required, then the rest of the infrastructure is already in place.  If someone can give @trilinos/muelu read access, then that team will automatically be requested for review of any PR that touches `packages/muelu`.

**Comment by jhux2** [comment]
> If someone can give @trilinos/muelu read access, then that team will automatically be requested for review of any PR that touches packages/muelu.

@jwillenbring @maherou I assume that you two can do this as owners.

**Comment by jhux2** [comment]
@jwillenbring Just following up.  May the MueLu team have read access?

**Comment by jwillenbring** [comment]
@jhux2 @jmgate 

I explicitly set read access for the MueLu team.

**Comment by csiefer2** [comment]
I verified that trilinos/muelu can be added as a reviewer to a PR.

Thanks!

**Comment by jmgate** [comment]
Does that mean we can give read access to all package teams?  If so, they'll automatically be requested for review on PRs that touch them.

**Comment by jhux2** [comment]
> I explicitly set read access for the MueLu team.

@jwillenbring Thank you!

> Does that mean we can give read access to all package teams? If so, they'll automatically be requested for review on PRs that touch them.

@jmgate  I'm not sure all teams will want this feature enabled.

**Comment by jwillenbring** [comment]
@jmgate @jhux2 

So to summarize, the suggestion here is that we add explicit read access for all package teams, and then they will be requested to review relevant PR's by default, but they can turn it off if they prefer?

If this is confirmed, I will add read access for these teams and then send a note to the developers explaining what was done and what their options are.

If someone on the team then reviews, is the review request for the team automatically checked off?

**Comment by jmgate** [comment]
> So to summarize, the suggestion here is that we add explicit read access for all package teams, and then they will be requested to review relevant PR's by default, but they can turn it off if they prefer?

Yup, and they can do that my modifying one line in the [.github/CODEOWNERS](https://github.com/trilinos/Trilinos/blob/master/.github/CODEOWNERS) file, which they'd do by submitting a PR, as usual.

> If someone on the team then reviews, is the review request for the team automatically checked off?

Yes, if anyone who is part of a team reviews the PR, GitHub will record something along the lines of "`@somebody` approved on behalf of `@trilinos/some-team`."

**Comment by jhux2** [comment]
@jmgate PR #3886 doesn't the MueLu team as a reviewer.  Should that have happened automatically?

**Comment by jwillenbring** [comment]
@jhux2 @jmgate 

> apparently it's the case that if you want to be able to manually add a team as a PR reviewer (or add it with the GitHub API via some script), the team needs read access, but if you want the team to automatically be requested for review via the CODEOWNERS file, the team needs write access.

OK, I changed it to write access. Please confirm this works as expected.

**Comment by jhux2** [comment]
@jwillenbring I can confirm that the MueLu team label is added automatically.  See PR #3892.

**Comment by mayrmt** [comment]
Auto-requesting of reviews from teams based on the `CODEOWNERS` file seems desirable to me.

**Comment by jwillenbring** [comment]
There is no consensus for this generally. We fixed this for MueLu. If someone wants to, they can file a more general ticket on that topic. I am going to close this ticket.
