### ISSUE TITLE
clang compiler warning: Belos

### ISSUE THREAD

**Issue by DrBooom** [trilinos/Trilinos#377]
This warning appears with clang compiler, with debug.

/scratch/cbluchi/sierra/TPLs/Trilinos_flat_headers/BelosStatusTestUserOutput.hpp:365:85: warning: expression result unused [-Wunused-value]
            os << std::setw(15) << (resTestVec_[j]->getStatus() == Belos::Passed) ? "Passed" : (resTestVec_[j]->getStatus() == Belos::Failed) ? "Failed" : "Undefined";

**Comment by tawiesn** [comment]
@DrBooom Could you check whether the warning is fixed?

**Comment by mhoemmen** [comment]
@DrBooom says: "Fixed, thanks!"
