### ISSUE TITLE
Framework: Who switched the packages labels and why?

### ISSUE THREAD

**Issue by csiefer2** [trilinos/Trilinos#3771]
Our labels just went from "MueLu" to "packages: MueLu"

Anyone care to explain?

@trilinos/framework

**Comment by mhoemmen** [comment]
@jhux2 could say more, I think

**Comment by csiefer2** [comment]
*All* of the package labels changed, not just ours.

**Comment by jhux2** [comment]
That was me.  See #1619.  If we decide we dislike it, it's easy enough to switch back.

**Comment by csiefer2** [comment]
Will makepr.sh process the space correctly in a label w/ a space in it (if you quote it)?

**Comment by jhux2** [comment]
@csiefer2 The following worked:
```
makepr.sh -l "packages: muelu" "MueLu: test PR, DO NOT MERGE"
```
See #3776.

**Comment by csiefer2** [comment]
Cool!

**Comment by jhux2** [comment]
Two label PR works, as well, see #3777.
```
makepr.sh -l "packages: muelu" -l "packages: ifpack2" "MueLu: test PR 2, DO NOT MERGE"
```

**Comment by csiefer2** [comment]
Everything is awesome!!!

**Comment by jhux2** [comment]
> Everything is awesome!!!

when you're part of a team

**Comment by csiefer2** [comment]
:gift_heart: :gift_heart: :gift_heart: :gift_heart: :gift_heart: :gift_heart: :gift_heart: :gift_heart:
