### ISSUE TITLE
Framework: Autotester for master merge does not delete branches after merge

### ISSUE THREAD

**Issue by csiefer2** [trilinos/Trilinos#3778]
The branch list is littered with merged branches like this guy:

master_merge_20181018_074226 

After getting on my case about automatically generated branch proliferation, I'd like to return the favor :stuck_out_tongue: 

@trilinos/framework 
@william76

**Comment by jwillenbring** [comment]
This is a feature request for the autotester, which is no longer under active development. I am going to close this ticket.
