### ISSUE TITLE
Ifpack2::ILUT: "fact: ilut level-of-fill" parameter really should be double; documentation is wrong

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#3782]
@atoth1 noticed that Ifpack2::ILUT wants the "fact: ilut level-of-fill" parameter to have type `int`.  (It accepts it as `magnitude_type` as a "backwards compatibility" measure, according to the comment.)  However, the code immediately casts the value to `double`.  AztecOO's ILUT implementation does something similar.  The code in both packages uses the parameter as a fraction, not as a count of things.  Therefore, a `double` would be more appropriate.  `magnitude_type` is not appropriate, because the fraction's required precision should depend on `local_ordinal_type`, not on `scalar_type`. 

Ifpack2's documentation for this parameter is also wrong.

@trilinos/ifpack2

**Comment by mhoemmen** [comment]
@atoth1 noticed also that Ifpack2's formula for fill usually matches that of AztecOO, but sometimes differs a bit.

**Comment by aprokop** [comment]
I remember that `ilut: level-of-fill` parameter calculation was extremely weird, and not matching to any existing literature. The Ifpack2 guide has the formula for it. If level is 1, then the weirdness goes away due to multiplication by `level_of_fill-1`.

**Comment by jhux2** [comment]
> The formula almost matches what AztecOO does.

If I recall correctly, @alanw0 implemented Ifpack2's ILUT using AztecOO's algorithm for inspiration.

**Comment by alanw0** [comment]
It was a long time ago and I don't remember what happens with the fill etc., but I do remember trying to emulate the Aztec implementation which was written by the great Tuminaro. I thought I even had some tests in there to verify that it was matching behavior.

**Comment by atoth1** [comment]
Just to put some numbers to this, here's the max number of extra non-zeros per row of the L and U factors I'm getting for a 100x100x100 3d Laplace problem for several values of the input fill parameter (AZ_ilut_fill for Aztec and "fact: ilut level-of-fill" for Ifpack2)
input_param 1   2   3   4   5
Aztec            0   3   6   10  13
Ifpack2         0   4   7   10  13
So those agree pretty well for the most part. However, even in cases where the extra non-zeros/row match (i.e. input fill value 4 or 5), the final number of non-zeros in final L and U factors computed by the two codes differ by a bit. I'm assuming that explains most of difference in the GMRES solves. Should the sparsity patterns be expected to agree in this case?

**Comment by mhoemmen** [comment]
@atoth1 The implementations differ in other ways.  We talked yesterday about AztecOO permuting the matrix possibly by default.  Other parameters, like the relative and absolute drop tolerances, may affect the sparsity pattern.

If Ifpack2 drops fewer entries than AztecOO, then Ifpack2's incomplete factorization hopefully won't be worse.  It might take a bit more memory, but part of the point of ILUT is to make dropping a per-row affair rather than the complicated graph problem it is in ILU(k).  Hopefully that makes ILUT less sensitive to retaining a few more entries.

**Comment by mhoemmen** [comment]
We tagged this "results impacting", because changing the parameter not to truncate could change results for people who e.g., are using fill = 2.5.  However, they weren't getting what they expected before anyway.

**Comment by mhoemmen** [comment]
Fixed in develop; thanks!
