### ISSUE TITLE
PyTrilinos: How can I get the MPI include directory in a robust way?

### ISSUE THREAD

**Issue by wfspotz** [trilinos/Trilinos#3783]
@trilinos/pytrilinos @trilinos/framework 

## Expectations
In PyTrilinos, I have a python script that generates a SWIG interface file. That SWIG interface file needs to know where the `mpi.h` header file is, so I can parse it and extract `MPI_VERSION`. I developed some logic to find it that worked for me, but it is not robust enough to work for all users.  How can I obtain the MPI include path for finding `mpi.h` in a robust way?

## Current Behavior
In #3618 the user specifies his MPI configuration with

     -D TPL_ENABLE_MPI:BOOL=ON
     -D MPI_EXEC:FILEPATH=/opt/apps/xalt/0.6/bin/ibrun

but my script specifies the path to `mpi.h` incorrectly.

## Motivation and Context
Here is what I do. I start with a file `get_teuchos_rcp.py.in` that will get copied to the build directory with `cmake` variable substituted in.  It has the following function defined to correctly interpret `cmake` boolean variables:

    def cmake_bool(value):
        if value.upper() in ("", "0", "FALSE", "N", "NO", "OFF"):
            return False
        return True

I then define python variable `WITH_MPI` (among many others) using

    WITH_MPI = cmake_bool("${TPL_ENABLE_MPI}")

I then use this logic to define python variable `MPI_BASE_DIR`:

    MPI_BASE_DIR = "${MPI_BASE_DIR}"
    if WITH_MPI:
        if MPI_BASE_DIR == "":
            MPI_BIN_DIR  = os.path.split("${MPI_CXX_COMPILER}")[0]
            MPI_BASE_DIR = os.path.split(MPI_BIN_DIR)[0]

All this leads to supporting the following function:

    def get_mpi_version():
        header = os.path.join(MPI_BASE_DIR, "include", "mpi.h")
        version = ""
        for line in open(header, 'r').readlines():
            if "MPI_VERSION" in line:
                version = line.split()[2]
                break
        return version

But the assumption that `mpi.h` lives in `MPI_BASE_DIR/include` is wrong, because in my user's case, the actual path does not have an `include` suffix.

## Definition of Done
When the user in #3618 can build PyTrilinos at his installation, which is TACC.

## Possible Solution
Does the `cmake` logic that looks for MPI have logic that extracts the location of the `mpi.h` file?  If not, could it be added?

## Related Issues

* Blocks #3618

**Comment by jhux2** [comment]
@wfspotz In such cases, I think you must require that the full path to `mpi.h` be specified at configure time.  I see no other way if an installation is going to allow the header to be in an arbitrary location.

**Comment by jhux2** [comment]
Would this do what you want?
```
-DTPL_MPI_INCLUDE_DIRS=/some/arbitrary/mpi/include/path
```

**Comment by VictorEijkhout** [comment]
Not clear: is this the solution, or a proposal for an option that you may add to your build system? I've added this option and it doesn't work. Log attached.
[trilinos.zip](https://github.com/trilinos/Trilinos/files/3237328/trilinos.zip)
