### ISSUE TITLE
Panzer Orientation Error 

### ISSUE THREAD

**Issue by bathmatt** [trilinos/Trilinos#3785]
It looks like the orientation is stored as a workset local var, however, we are using MPI rank cell index.  This doesn't show up unless you use multi blocks.

Two blocks  gives this solution, blocks split down the middle

![visit0000](https://user-images.githubusercontent.com/14926624/47810242-6d6ae900-dd08-11e8-9f4e-9cf304e83982.png)

with the fix in the related PR you get

![visit0001](https://user-images.githubusercontent.com/14926624/47810314-a7d48600-dd08-11e8-9012-f00c4daa00a2.png)

which is the correct results..  I ran all the tests in panzer, they pass.

@trilinos/<teamName>

## Your Environment

- **Relevant repo SHA1s:**  
- **Relevant configure flags or configure script:**  
- **Operating system and version:**  
- **Compiler and TPL versions:**  

## Related Issues

* Blocks 
* Is blocked by 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of

**Comment by bathmatt** [comment]
@rppawlo let me know if you can show this in a panzer test

**Comment by bathmatt** [comment]
Before my changes or after

**Comment by rppawlo** [comment]
> Before my changes or after

Sorry - missed your reply. I compared before and after your changes for CurlLaplacian and MixedPoisson. Multiple orders on hex, tri and quad with different mpi distributions. Couldn't trigger a failure or a difference with your changes. Were you using one of the panzer inline mesh generators for the problem that exhibited this or was it an exodus file? If inline, could you send the values to reconstruct that mesh exactly?

**Comment by rppawlo** [comment]
Fix is in. New tests for multiblock are in as well. Closing.
