### ISSUE TITLE
SuperLU 5

### ISSUE THREAD

**Issue by nschloe** [trilinos/Trilinos#379]
[SuperLU 5.0 was released about a year ago](http://crd-legacy.lbl.gov/~xiaoye/SuperLU/) and since it's breaking backwards compatibility, Trilinos (specifically: Amesos, Amesos2) fail to compile against it. This presents a problem on platforms that have upgraded to SuperLU 5.

**Comment by mhoemmen** [comment]
I'm classifying this as an "enhancement," since (a) SuperLU 5 broke backwards compatibility, and (b) we don't claim to support SuperLU 5:

https://trilinos.org/about/tpl-version-compatibility/

**Comment by bavier** [comment]
Perhaps you could use this as a starting point: [trilinos-superlu5-patch.txt](https://github.com/trilinos/Trilinos/files/280146/trilinos-superlu5-patch.txt)

**Comment by nmhamster** [comment]
Will the version be detected at configure time and then used correctly -- i.e. support for 4.3 and 5.0?

**Comment by bavier** [comment]
The patch I attached uses a configure-time check for the superlu API and adjusts function calls appropriately.  I have used to to build trilinos with both version 4.3 and 5.0.  It does not address Amesos2's interface to superlu.

**Comment by nschloe** [comment]
I see `superlu_5.0` added in the patch. Should `superlu_5.1` and `superlu_5.2` should also be part of it?

**Comment by ndellingwood** [comment]
PR #1620 issue to partially address this issue (Amesos2 enhancement to use SuperLU 5.0); PR #411 merged in with the PR with Amesos and Cmake fixes by @bavier and @nschloe

**Comment by ndellingwood** [comment]
PR #1643 merged into Trilinos develop branch with SuperLU 5.0, 5.1.1 support for Amesos and Amesos2.
