### ISSUE TITLE
Xpetra: wrong specialization implementation in CrsMatrix

### ISSUE THREAD

**Issue by lucbv** [trilinos/Trilinos#3804]
@trilinos/xpetra 

The following [nightly build](https://testing.sandia.gov/cdash/index.php?project=Trilinos&parentid=4138372) is reporting build errors.
This should be fixed...

**Comment by jhux2** [comment]
This may also fix errors reported by @micahahoward.
@bartlettroscoe

**Comment by lucbv** [comment]
The [build of interest](https://testing.sandia.gov/cdash/index.php?project=Trilinos&parentid=4144096) is clean this morning so I am closing this issue.
