### ISSUE TITLE
Trilinos dependencies version!

### ISSUE THREAD

**Issue by Hostudent** [trilinos/Trilinos#3808]
I installed trilinos on my MacBook (on Mojave OS) and encountered with lots of failed test.
after a couple of days, i realized that the problem is with the versions of the dependencies.
 as i mentioned in the last issue I'm really amateur in Unix systems.
now my question is: which version of these packages are more stable to install:
and please write down the configure command for each one to provide correct dependencies. I'm trying to install trilinos in order to install peridigm.  so please someone explain each part.
gcc
Boost
OpenMPI
NetCDF
Curl
HDF5
and any dependencies that these packages need to be installed before them.
thank you

**Comment by mhoemmen** [comment]
1. The default `clang++` on Mac works fine with Trilinos.
2. Do you really need all of those third-party libraries?  It depends on which Trilinos packages you need.

**Comment by Hostudent** [comment]
@mhoemmen im trying to install trilinos in order to install peridigm. as peridigm's team asked in peridigm's installation documents, these third-party libraries are required. the problem is that, i installed the last versions of all of them and got some Errors, by downgrading some of the packages (as other offered), most of the Errors disappeared! i tried several combinations of libraries versions but some Errors still exist. my question is:
which versions of those packages are compatible with the master version of peridigm and master version of trilinos for both Mac (Mojave OS) and linux (ubuntu 18.04 LTS)?

**Comment by mhoemmen** [comment]
It's hard to answer that a priori -- check with the Peridigm authors for their recommendations.

**Comment by Hostudent** [comment]
@djlittl @johntfoster @mbhzdi what is your recommendations?
I have 3 questions.
1) I installed the last version of each packages and found some conflict between them. For example in the last version of boost(1.67) the memory.h file is moved from its previous directory (include/boost/tr1/memory.hpp) and tr1 directory is removed at all but, the master version of peridigm still calls for memory.h in that directory. Therefore im looking for compatible versions of each packages with master-peridigm and master-trilinos. What is your recommendations(for mac os mojave and ubuntu 18.04 LTS)?
2) as i compiled trilinos with both openmpi and mpich, i got 2 kinds of errors then i decided to choose openmpi and set trilino_test=OFF, to avoid get Errors. but nearly all the Zoltan/MPI tests still get failed. What is you suggestion between openmpi and mpich for mac?
3) and the last one is that im not clear on the installation of the netcdf, which release must be installed? Netcdf-c release or Netcdf-c++ release?

**Comment by mbhzdi** [comment]
1. Try boost 1.64.
2. I have openmpi on my Mac.
3. NetCDF-c it is. Make sure to change the include.h file if you plan to use SEACAS/Peridigm. You can also try this version, which is already modified:
https://github.com/mbhzdi/netcdf-c

PS. For your reference, here are the installation scripts for Trilinos/Peridigm on my macOS. 
https://gist.github.com/mbhzdi/36b972e8e01a88489e8079dc8d5e34b9
https://gist.github.com/mbhzdi/342709876b84c4e069b2bcc8c25ee0c0

**Comment by Hostudent** [comment]
@mbhzdi include.h?
do you mean the netcdf.h?

**Comment by mbhzdi** [comment]
Yeah, that’s why I mentioned to use that repo, so you don’t have to do any modifications and just install as is. 
openmpi 3, but I doubt if that matters.

**Comment by Hostudent** [comment]
@mbhzdi it matters!!
i installed hdf5 1.10.4 and after configuring it by:
# CC=/usr/local/Cellar/open-mpi/3.1.3/bin/mpicc  ../configure --prefix=/usr/local/packages/hdf5  --enable-parallel
and 
# make -j4
in order to 
# make test 
got this error:
Testing  -- compressed dataset collective read (cmpdsetr)
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpiexec noticed that process rank 3 with PID 0 on node Hoseins-Mac exited on signal 14 (Alarm clock: 14).
--------------------------------------------------------------------------
     1202.79 real      4773.89 user        12.89 sys
make[4]: *** [testphdf5.chkexe_] Error 1
make[3]: *** [build-check-p] Error 1
make[2]: *** [test] Error 2
make[1]: *** [check-am] Error 2
make: *** [check-recursive] Error 1
so i think there must be a problem with openmpi compiler, what do you suggest?
(im a mechanical engineer neither a programmer!! so consider me as an amateur !!!)

**Comment by Hostudent** [comment]
before this Error, I've received another Error in parallel test part which says there is not enough slot in the system, that i found default number of nodes for the parallel test was set: NPROCS:=6 and manually changed it to 4 which is the number of my mac CPU's cores. after this modification, i received that Error.

**Comment by mbhzdi** [comment]
Well, I just installed hdf5 and openmpi with homebrew. Here are the versions currently installed on mine:
 brew list --versions openmpi
open-mpi 3.0.1
 brew list --versions hdf5
hdf5 1.10.1_2

**Comment by mbhzdi** [comment]
Btw, I've got 2 cores on my computer. If I run test on Peridigm, all the parallel tests that want to use 3 or more processors will fail. It doesn't mean that the MPI functionality is not working or anything. 

What I suggest you to do is to install trilinos and peridigm with the versions I mentioned (I have macOS Sierra btw, not sure if that's relevant though), then try to see if you can run peridigm (first, try it in serial, then parallel if passed).

**Comment by Hostudent** [comment]
@mbhzdi my problem is with peridigm's tests. All the MPI tests (132 out of 188) failed!! Im looking for the root of the problem and i think the problem is with the openmpi!!

**Comment by Hostudent** [comment]
@mbhzdi whats your script for installation netcdf? it seems must be installed with cmake.

**Comment by mbhzdi** [comment]
cmake \
    -DCMAKE_BUILD_TYPE:STRING=Release \
    -DCMAKE_C_COMPILER:FILEPATH=/usr/local/bin/mpicc \
    -DCMAKE_INSTALL_PREFIX:PATH=/usr/local/netcdf \
    -DCMAKE_INSTALL_NAME_DIR:PATH=/usr/local/netcdf/lib \
    -DCMAKE_MACOSX_RPATH:BOOL=OFF \
    -DENABLE_PARALLEL:BOOL=ON \
    ..
