### ISSUE TITLE
PR build Trilinos_pullrequest_gcc_4.9.3_SERIAL and the nightly "Clean" build Linux-gcc-4.9.3-SERIAL_Release_gcc_4.9.3__DEV are not the same

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#3813]
CC: @dridzal, @crtrott, @srajama1 

@trilinos/framework,

It looks like the PR build `Trilinos_pullrequest_gcc_4.9.3_SERIAL` and the nightly "Clean" build `Linux-gcc-4.9.3-SERIAL_Release_gcc_4.9.3__DEV` are **NOT** the same!

The configuration for the PR build `Trilinos_pullrequest_gcc_4.9.3_SERIAL` for this PR shown [here](https://testing-vm.sandia.gov/cdash/viewConfigure.php?buildid=4141632) shows the Pthread TPL being explicitly enabled:

```
Explicitly enabled TPLs on input (by user):  Pthread BLAS LAPACK Boost Zlib HDF5 Netcdf SuperLU BoostLib DLlib 10
...
Final set of enabled TPLs:  Pthread BLAS LAPACK Boost Zlib HDF5 Netcdf SuperLU BoostLib DLlib 10
```

but the nightly "Clean" build `Linux-gcc-4.9.3-SERIAL_Release_gcc_4.9.3__DEV` shown [here](https://testing.sandia.gov/cdash-dev-view/viewConfigure.php?buildid=4142839) shows that the Pthread is **not** being explicitly enabled:

```
Explicitly enabled TPLs on input (by user):  BLAS LAPACK Boost Zlib HDF5 Netcdf SuperLU BoostLib DLlib 9
...
Final set of enabled TPLs:  BLAS LAPACK Boost Zlib HDF5 Netcdf SuperLU BoostLib X11 DLlib 10
```

This explains how code got onto 'develop' that was allowed to break the "Clean" non-MPI SERIAL build (see #3773 and #3803)

I thought the goal of the adding a (non-MPI) SERIAL PR build was to guarantee that the nightly "Clean" SERIAL would be clean?

**Comment by bartlettroscoe** [comment]
@trilinos/framework,

Can you just make the nightly "Clean" builds use the exact same env and `*.cmake` files as the matching PR builds?  That would solve this problem, no?

**Comment by william76** [comment]
@bartlettroscoe
The Nightly Clean tests will be deprecated out at some point in favor of the dev->master Pull Request setup. It doesn't make a ton of sense to me to modify the serial build on the Clean track at this time.  I'm fine leaving it as it's been as we decide what to do with it.

**Comment by prwolfe** [comment]
Siva,

This large of a blanket statement worries me.  The current builds this issue refers to should be identical, but the final develop to master promotion builds will have a slightly expanded goal than the PR builds do.  Basically integration is a bit different from delivery - in particular additional platforms and verification testing is often added. Please understand that there are likely going to be differences, for good reason, and that we will work to minimize those as we go.

Paul
