### ISSUE TITLE
Need to Install TOSS3 Environment Scripts on Chama and Serrano

### ISSUE THREAD

**Issue by jmgate** [trilinos/Trilinos#3816]
## Expectations
I should be able to build an application against an install of Trilinos on `chama` by sourcing `${Trilinos_INSTALL_DIR}/load_matching_env.sh`.

## Current Behavior
When I do so, that script sources `${Trilinos_INSTALL_DIR}/share/atdm-trilinos/load-env.sh`, which sources `$ATDM_SCRIPT_DIR/$ATDM_CONFIG_KNOWN_SYSTEM_NAME/environment.sh` (where `$ATDM_CONFIG_KNOWN_SYSTEM_NAME` is `chama`), which sources `$ATDM_SCRIPT_DIR/toss3/environment.sh`, which doesn't exist, because it wasn't installed.

## Motivation and Context
Trying to stand up a build of all of EMPIRE on `chama`.

## Definition of Done
If `$ATDM_CONFIG_KNOWN_SYSTEM_NAME` is `chama` or `serrano`, then the `toss3` directory and its contents also get installed.

## Possible Solution
Take a look at [this line in `ATDMDevEnvSettings.cmake`](https://github.com/trilinos/Trilinos/blob/cdbfaf56f44997486e915d967f664d5108070ebe/cmake/std/atdm/ATDMDevEnvSettings.cmake#L362).  After this `INSTALL` directive, you need something along the lines of
```cmake
IF ($ENV{ATDM_CONFIG_KNOWN_SYSTEM_NAME} EQUAL "chama" OR
    $ENV{ATDM_CONFIG_KNOWN_SYSTEM_NAME} EQUAL "serrano")
  INSTALL( DIRECTORY ${CMAKE_CURRENT_LIST_DIR}/toss3
    DESTINATION ${ATDM_CONFIG_SCRIPTS_INSTALL_DIR}
    PATTERN "*.cmake" EXCLUDE )
ENDIF()
```

## Steps to Reproduce
See the `EMPIRE_EM-Plasma-Trilinos-chama-test-all-of-EMPIRE-intel-opt-openmp` Jenkins job and its console log.

## Related Issues
#2689 (see commit 3fef8c21e58ba7e12de77f7a95ba01b5caf038cc)

**Comment by bartlettroscoe** [comment]
CC: @fryeguy52 

@jmgate, okay, I see the problem.  Sorry about that.

We will have to think of way to address this going forward that is logical and maintainable.  One idea might be to move directories like `toss3` into a dir `Trilinos/cmake/std/atdm/common/` and then just always install `Trilinos/cmake/std/atdm/common/` when installing on any platform.  The thing that I am trying to avoid is allowing a user to try to source an env that does not match the installed Trilinos configuration and then expecting that install Trilinos library to support.  Therefore, it would be a bad idea to install of all `Trilinos/cmake/std/atdm/` as it would allow them to try that (with bad consequences).  I think going with  `Trilinos/cmake/std/atdm/common/` would achieve these goals.  Agree?

**Comment by jmgate** [comment]
That sounds fine to me.  I know the solution I proposed above should be generalized in some way; just wasn't sure how you'd want to go about it.  In the meantime, I'm going to wind up sourcing the `load-env.sh` from the Trilinos source (instead of install) directory.  That work-around should be fine for now, so you should have time to figure out how you best want to implement this.

**Comment by jmgate** [comment]
Many thanks @bartlettroscoe.

**Comment by bartlettroscoe** [comment]
PR #3817 was just merged.

@jmgate, when EMPIRE gets and updated version of Trilinos 'develop', can you please verify that this fixes this problem and then close this issue?

**Comment by jmgate** [comment]
Looks like we pulled in the update.  Installing on `chama` now and then I can test.

**Comment by jmgate** [comment]
This worked.  Thanks @bartlettroscoe.
