### ISSUE TITLE
MueLu: proposal: create smoother for level L after creating level L+1

### ISSUE THREAD

**Issue by jhux2** [trilinos/Trilinos#3822]
The MueLu hierarchy currently creates the smoother for level `k` prior to creating level `k+1`.  I propose creating the smoother after level `k+1` is created.

Motivation: For the Chebyshev smoother, it is advantageous to know the coarsening rate from Level `k` to `k+1` in order to set `alpha`, the lower end of the Chebyshev effective smoothing interval.

**Comment by csiefer2** [comment]
Neat idea!  Is there any evidence this would actually work?

I mean, we could test this by running MueLu once, recording the coarsening rate and then resetting the Chebyshev params to be "correct" and then running again.  Then we could see if it improves performance...

**Comment by jhux2** [comment]
I've got anecdotal evidence.
