### ISSUE TITLE
Tpetra: MultiVector unit test failure with complex turned on

### ISSUE THREAD

**Issue by lucbv** [trilinos/Trilinos#3823]
@trilinos/tpetra @crtrott 

## Expectations
I am seeing test failures in MueLu's unit-test with complex turned on this morning.
My guess is that the failure is not completely (at all?) in MueLu as no commit was made to it since yesterday's nightly builds.

## Current Behavior
The unit-test: `TpetraCore_MultiVector_UnitTests_MPI_4` fails when complex is turned on with `SHA1 23c8989` but it works fine without complex unabled and with complex unabled and `SHA1 bf01cda`. Actually I narrowed it down to working commit `SHA1 0c5d4cf` and not working commit `SHA1 eb41c7f` which points at the kokkos promotion.

## Motivation and Context
I think this might be the reason for failures I am seeing in MueLu with complex enabled. I would like to resolve these...

## Definition of Done
We need to have that test pass with complex unabled

## Steps to Reproduce
Build with the indicated SHA1 and the following options:
```
            -D Trilinos_ENABLE_COMPLEX_DOUBLE=ON \
            -D Trilinos_ENABLE_Tpetra=ON \
            -D   Tpetra_ENABLE_TESTS=ON \
```

**Comment by ndellingwood** [comment]
Added PR #3838 which addresses the compilation error, thanks to @crtrott for taking a look at it with me. Tpetra compiles without error but there are failing tests in the MultiVector unit test that need to be addressed.

**Comment by mhoemmen** [comment]
Wow, we never actually fixed this.  @trilinos/tpetra @kddevin 

Does kokkos-kernels not test complex?
https://github.com/kokkos/kokkos-kernels/issues/360

**Comment by mhoemmen** [comment]
I know the likely cause and how to fix this:

https://github.com/kokkos/kokkos-kernels/issues/360#issuecomment-455251898

**Comment by mhoemmen** [comment]
@ndellingwood Does kokkos-kernels actually test the value of the complex dot product?

**Comment by ndellingwood** [comment]
@mhoemmen kokkos-kernels tests the value of the complex dot product. Two views are initialized with random values, and the dot result is compared with the serialized result computed on the host. There is an error tolerance used in the comparison since sum is not associative for floating point types in a parallel reduction.

**Comment by mhoemmen** [comment]
@ndellingwood Should we close this issue then? https://github.com/kokkos/kokkos-kernels/issues/360  I mean the promotion broke Trilinos, so something is wrong.

**Comment by ndellingwood** [comment]
@mhoemmen I would keep this issue open to keep the issue visible until a fix is in Trilinos, but I'll defer to your judgement on the best practice for tracking/reporting when fixed.

**Comment by mhoemmen** [comment]
"Should we close this issue" was a rhetorical question, whose answer is "no" ;-)

**Comment by mhoemmen** [comment]
PR: https://github.com/trilinos/Trilinos/pull/4253
