### ISSUE TITLE
Lumped projection fails for tri's and maybe other basis as well...

### ISSUE THREAD

**Issue by bathmatt** [trilinos/Trilinos#3825]
The projection produces bad values for higher order basis and lumping,

@trilinos/<teamName>

## Your Environment

- **Relevant repo SHA1s:**  
- **Relevant configure flags or configure script:**  
- **Operating system and version:**  
- **Compiler and TPL versions:**  

## Related Issues

* Blocks 
* Is blocked by 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of

**Comment by bathmatt** [comment]
@rppawlo did you happen to add a test that shows this in panzer?

**Comment by bathmatt** [comment]
* [new branch]      project-fix -> project-fix

this is a branch to build this fix in.

**Comment by bathmatt** [comment]
@rppawlo I have a fix in this branch that passes the test and resolves some of the error in my code for the higher order, but it is wiggly.  Also the fix sucks in terms of how one should do coding but it is the fasest way to get to an answer.

As for the actual issue, not sure why it is wiggling, this should be a constant

**Comment by bathmatt** [comment]
![visit0003](https://user-images.githubusercontent.com/14926624/48166511-04eeaf80-e2a6-11e8-9c6a-4b7068949c14.png)

**Comment by rppawlo** [comment]
Summary for this ticket:
The Lumped L2 projection can be implemented in a number of ways. The current implementation is the row sum version that is not guaranteed to work for arbitrary bases of high order. A discussion in Tom Hughes' book recommended the algorithm by Hinton, 1976. @bathmatt  has implemented that here.

**Comment by rppawlo** [comment]
@bathmatt - Thanks for implementing this! I'd like to keep the row sum version around as well. I will add some more tests to exercise this new option on a high order tri case.
