### ISSUE TITLE
Framework: Stop builds with unsuported compilers

### ISSUE THREAD

**Issue by lucbv** [trilinos/Trilinos#3830]
@trilinos/framework @bartlettroscoe 

## Expectations
I am not sure it makes sense to keep the following nightly build:
ascic 144: [Linux-gcc-4.7.2-MPI_Release_gcc_4.7.2_openmpi_1.8.7_DEV](https://testing.sandia.gov/cdash/buildSummary.php?buildid=4152501)

## Current Behavior
The build is failing at configure time, it returns the following error message:
```
CMake Error at packages/kokkos/cmake/kokkos_functions.cmake:68 (message):
  Compiler not supported by Kokkos.  Required compiler versions:

      Clang      3.5.2 or higher
      GCC        4.8.4 or higher
      Intel     15.0.2 or higher
      NVCC      7.0.28 or higher
      PGI         17.1 or higher
```

## Motivation and Context
This might free up a bit the machines and make the dashboard more readable.

**Comment by csiefer2** [comment]
See also #3670

**Comment by jhux2** [comment]
Could this be an unowned machine?  Anyone can submit to cdash afaik.

**Comment by lucbv** [comment]
Yeah I now, but I figured since it's an ascic machine...

**Comment by lucbv** [comment]
@william76 do you know anything about this machine?

**Comment by william76** [comment]
@lucbv 	nope... It's a node on the ASCIC farm. The ascic machines are owned by ceelan. It looks like it's a haswell node, but other than that I don't know much about how they're set up.  Ceelan handles the setup & maintenance of the ascic machines.

@prwolfe, the only job I see tied to ascic144 is that sleep job we put in to 'disable' the node back when we were having tons of problems with ceelan nodes in august that wouldn't connect to the internal gitlab repositories, which was causing failures on PR testing. Do we still need to be blocking those nodes?  I thought the ceelan folks finally got that ssh problem fixed a week ago or so...?

@jwillenbring @trilinos/framework if the gcc 4.7.2 build is obsolete, can we turn it off? It's off in the Experimental track. 

I believe the test is driven by the `trilinos_generic_nightly` job, which is kicked off in the `trilinos_nightly_driver` using the default options.

**Comment by prwolfe** [comment]
Yep - there is one trigger with no parameters.

More generally, the ones that do have parameters are behind.  gcc 4.9.3, openmpi 1.8.7, intel 16

My recommendations

* all gcc compiles move up to 7.3
* openmpi versions move to 1.10.1
* all versions called from the driver are explicitly set to make it obvious what we are building.
* move the intel 16 compile to 18 as soon as we can convince sems to install it unless a code team has a valid argument against it.

Since all but the last one are quick changes in Jenkins agreement is the long pole in the tent.

Paul

**Comment by csiefer2** [comment]
@trilinos/framework I'm not sure all of the platforms our apps need to work on have gcc 7.3.

**Comment by prwolfe** [comment]
> @trilinos/framework I'm not sure all of the platforms our apps need to work on have gcc 7.3.

True - that is part of why the minimum will remain 4.8.4 and we will test that case.

**Comment by jwillenbring** [comment]
I don't see a 4.7 build on the dashboard this morning, so I am closing this issue.
