### ISSUE TITLE
ShyLU/FROSch: config flags not properly included

### ISSUE THREAD

**Issue by mayrmt** [trilinos/Trilinos#3846]
@trilinos/shylu 

## Expectations
Enable a proper inclusion of the define flags `HAVE_SHYLU_DDFROSCH_EPETRAEXT` and `HAVE_EPETRAEXT_HDF5` in the test  `ShyLU_DDFROSch_twolevelblockinputfiles.exe` defined in `packages/shyly/shylu_dd/frosch/tests/TwoLevelPreconditionerBlockInputFiles/main.cpp`.

## Current Behavior
The two flags `HAVE_SHYLU_DDFROSCH_EPETRAEXT` and `HAVE_EPETRAEXT_HDF5` seem not to be included into the test. 

## Motivation and Context
The tests just prints the parameter list to screen and then does _not_ perform any computations. Hence, it always passes without doing the actual testing.

## Definition of Done
- [ ] Guarantee proper inclusion of all necessary define flags.

## Possible Solution
For now, I manually included `ShyLU_DDFROSch_config.h` and `EpetraExt_config.h` at the very top of the list of header inclusions. Not sure, if this is an appropriate fix to be committed.

## Steps to Reproduce
In your build directory, execute the test `packages/shyly/shylu_dd/frosch/tests/TwoLevelPreconditionerBlockInputFiles/ShyLU_DDFROSch_twolevelblockinputfiles.exe`. The tests just prints the parameter list to screen and then does _not_ perform any computations. Hence, it always passes without doing the actual testing.

## Your Environment
- **Relevant repo SHA1s:**  cb7bb14910bd76d554926f6a0c3d5c5353f0cef9
- **Relevant configure flags or configure script:**  
[do-configure-trilinos_shylu2.txt](https://github.com/trilinos/Trilinos/files/2571642/do-configure-trilinos_shylu2.txt)
- **Operating system and version:**  Ubuntu 16.04
- **Compiler and TPL versions:**  

## Additional Information
* Configure log file:  
[configure.log](https://github.com/trilinos/Trilinos/files/2571634/configure.log)

## Interested Parties
@searhein

**Comment by mayrmt** [comment]
@searhein This is a brief summary of our observations and discussions that we had over the phone. Any ideas on how to proceed on this?

**Comment by searhein** [comment]
@mayrmt I have fixed this on my machine while we discussed it. Let me prepare a PR later today/tomorrow. I want to make sure that there is no other file in FROSch with similar issues.

**Comment by mayrmt** [comment]
Has been addressed in #3947. Closing.
