### ISSUE TITLE
KokkosKernels tests randomly timing out on ATDM mutrino KNL build

### ISSUE THREAD

**Issue by fryeguy52** [trilinos/Trilinos#3864]
CC: @trilinos/<package-name>, @kddevin  (Trilinos Data Services Product Lead), @bartlettroscoe 
 
## Description
As shown in [this query](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercombine=and&filtercount=6&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-mutrino-intel-opt-openmp-KNL&field2=testname&compare2=65&value2=KokkosKernels_&field3=site&compare3=61&value3=mutrino&field4=buildstarttime&compare4=84&value4=2018-11-13T00%3A00%3A00&field5=buildstarttime&compare5=83&value5=2018-10-14T00%3A00%3A00&field6=details&compare6=61&value6=Completed%20%28Timeout%29) the tests:
* [KokkosKernels_sparse_serial_MPI_1](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-mutrino-intel-opt-openmp-KNL&field2=testname&compare2=61&value2=KokkosKernels_sparse_serial_MPI_1&field3=site&compare3=61&value3=mutrino&field4=buildstarttime&compare4=84&value4=2018-11-13T00:00:00&field5=buildstarttime&compare5=83&value5=2018-10-14T00:00:00)
* [KokkosKernels_sparse_openmp_MPI_1](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercombine=and&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-mutrino-intel-opt-openmp-KNL&field2=testname&compare2=61&value2=KokkosKernels_sparse_openmp_MPI_1&field3=site&compare3=61&value3=mutrino&field4=buildstarttime&compare4=84&value4=2018-11-13T00%3A00%3A00&field5=buildstarttime&compare5=83&value5=2018-10-14T00%3A00%3A00)
* [KokkosKernels_graph_serial_MPI_1](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-mutrino-intel-opt-openmp-KNL&field2=testname&compare2=61&value2=KokkosKernels_graph_serial_MPI_1&field3=site&compare3=61&value3=mutrino&field4=buildstarttime&compare4=84&value4=2018-11-13T00%3A00%3A00&field5=buildstarttime&compare5=83&value5=2018-10-14T00%3A00%3A00)
* [KokkosKernels_graph_openmp_MPI_1](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-mutrino-intel-opt-openmp-KNL&field2=testname&compare2=61&value2=KokkosKernels_graph_openmp_MPI_1&field3=site&compare3=61&value3=mutrino&field4=buildstarttime&compare4=84&value4=2018-11-13T00:00:00&field5=buildstarttime&compare5=83&value5=2018-10-14T00:00:00)
* [KokkosKernels_common_serial_MPI_1](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-mutrino-intel-opt-openmp-KNL&field2=testname&compare2=61&value2=KokkosKernels_common_serial_MPI_1&field3=site&compare3=61&value3=mutrino&field4=buildstarttime&compare4=84&value4=2018-11-13T00%3A00%3A00&field5=buildstarttime&compare5=83&value5=2018-10-14T00%3A00%3A00)
* [KokkosKernels_common_openmp_MPI_1](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-mutrino-intel-opt-openmp-KNL&field2=testname&compare2=61&value2=KokkosKernels_common_openmp_MPI_1&field3=site&compare3=61&value3=mutrino&field4=buildstarttime&compare4=84&value4=2018-11-13T00:00:00&field5=buildstarttime&compare5=83&value5=2018-10-14T00:00:00)
* [KokkosKernels_blas_serial_MPI_1](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-mutrino-intel-opt-openmp-KNL&field2=testname&compare2=61&value2=KokkosKernels_blas_serial_MPI_1&field3=site&compare3=61&value3=mutrino&field4=buildstarttime&compare4=84&value4=2018-11-13T00%3A00%3A00&field5=buildstarttime&compare5=83&value5=2018-10-14T00%3A00%3A00)
* [KokkosKernels_blas_openmp_MPI_1](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercombine=and&filtercombine=and&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-mutrino-intel-opt-openmp-KNL&field2=testname&compare2=61&value2=KokkosKernels_blas_openmp_MPI_1&field3=site&compare3=61&value3=mutrino&field4=buildstarttime&compare4=84&value4=2018-11-13T00%3A00%3A00&field5=buildstarttime&compare5=83&value5=2018-10-14T00%3A00%3A00)

are randomly timing out in the build:
* Trilinos-atdm-mutrino-intel-opt-openmp-KNL 

Links above are to a 30 day history of each test.  The `KokkosKernels_*_serial_MPI_1` tests are nearly 3 times as likely to timeout over the last 30 days vs the `KokkosKernels_*_openmp_MPI_1` tests.   On average 3 of the 8 tests fail and there has been only one day in that last 30 when all passed.

## Current Status on CDash

The current status of these tests/builds for the current testing day can be found at:

[Current test status](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-mutrino-intel-opt-openmp-KNL&field2=testname&compare2=65&value2=KokkosKernels_&field3=buildstarttime&compare3=83&value3=yesterday)

## Steps to Reproduce

One should be able to reproduce this failure on the machine mutrino as described in:
* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md
More specifically, the commands given for the system mutrino are provided at:
* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#<mutrino

The exact commands to reproduce this issue should be:
```
$ cd <some_build_dir>/

$ source $TRILINOS_DIR/cmake/std/atdm/load-env.sh Trilinos-atdm-mutrino-intel-opt-openmp-KNL

$ cmake \
  -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
  -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_KokkosKernels=ON \
  $TRILINOS_DIR

$ make -j16

$ salloc -N 1 -p standard -J Trilinos-atdm-mutrino-intel-opt-openmp-KNL ctest -j16
```

**Comment by bartlettroscoe** [comment]
@trilinos/kokkos-kernels developers, 

Note that we are struggling with the KNL setting on 'mutino' a bit (see https://software-sandbox.sandia.gov/jira/browse/TRIL-219).  We should try running some of these tests individually to see what happens.  But I think we need some help with this.

Do you know anyone who is knowledgeable with configure and runtime setting for running on the Intel KNL with the KNL KOKKOS_ARCH?  @trilinos/kokkos?

**Comment by srajama1** [comment]
We will take care of this. I believe @crtrott has access to this machine. We are all at a conference this week and will attend to it when we return. If it is a quick check @ndellingwood might be able to help too. At the least there needs to be a kokkos kernels issue for this.

**Comment by bartlettroscoe** [comment]
After talking with Si Hammond and looking over the KNL settings, I think this might be related to our settings on 'mutrino' (see [TRIL-219](https://sems-atlassian-son.sandia.gov/jira/browse/TRIL-219)).  Therefore, I am adding the label "ATDM Env Issue" to raise this as a possibility.

**Comment by srajama1** [comment]
@ndellingwood @crtrott Can one of you check this ?

**Comment by srajama1** [comment]
@bartlettroscoe This issue was closed from the Kokkos Kernels side as an environment issue. We can't do much from Kokkos Kernels side. We can close this from Kokkos Kernels/Data Services perspective. Or remove those labels and track it as a Dev Ops issue for getting the environment cleaned up.

**Comment by ndellingwood** [comment]
Cross-referencing with issue #2422

**Comment by bartlettroscoe** [comment]
@srajama1 said:

> This issue was closed from the Kokkos Kernels side as an environment issue. We can't do much from Kokkos Kernels side. We can close this from Kokkos Kernels/Data Services perspective. Or remove those labels and track it as a Dev Ops issue for getting the environment cleaned up.

@srajama1, we have the `ATDM Env Issue` label put on this so this this will not count against Trilinos.  But the problem is that as shown [here](https://groups.google.com/forum/#!topic/atdm-trilinos-builds-status/t4YkWTcn2iw), KokkosKernels and Sacado tests are still randomly failing in this KNL build.  Do the KokkosKernels developers have advice on how to correctly set up to run with KNL on 'mutrino'?  But as long as these tests are still failing, we have to keep the issue open. 

But to get this off of your list, would transferring this from `PA: Data Services` over to `PA: Framework` be sufficient?   What GitHub queries do you run?

**Comment by fryeguy52** [comment]
closing as these have been passing for 25 days.  The one failure is due to a random system issue

---

<table style="width:100%" boarder="1">

<tr>
<th>Site</th>
<th>Build Name</th>
<th>Test Name</th>
<th>Status</th>
<th>Details</th>
<th>Consec&shy;utive Pass Days</th>
<th>Non-pass Last 30 Days</th>
<th>Pass Last 30 Days</th>
<th>Issue Tracker</th>
</tr>


<tr>
<td align="left">mutrino</td>
<td align="left"><a href="https://testing.sandia.gov/cdash/index.php?project=Trilinos&filtercombine=and&filtercombine=&filtercount=4&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-mutrino-intel-opt-openmp-KNL&field2=site&compare2=61&value2=mutrino&field3=buildstarttime&compare3=84&value3=2019-04-02T00:00:00&field4=buildstarttime&compare4=83&value4=2019-03-03T00:00:00">Trilinos-atdm-mutrino-intel-opt-openmp-KNL</a></td>
<td align="left"><a href="https://testing.sandia.gov/cdash/testDetails.php?test=73129512&build=4815643">KokkosKernels_&shy;blas_&shy;openmp_&shy;MPI_&shy;1</a></td>
<td align="left"><a href="https://testing.sandia.gov/cdash/testDetails.php?test=73129512&build=4815643"><font color="green">Passed</font></a></td>
<td align="left">Completed</td>
<td align="right"><a href="https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-mutrino-intel-opt-openmp-KNL&field2=testname&compare2=61&value2=KokkosKernels_blas_openmp_MPI_1&field3=site&compare3=61&value3=mutrino&field4=buildstarttime&compare4=84&value4=2019-04-02T00:00:00&field5=buildstarttime&compare5=83&value5=2019-03-03T00:00:00"><font color="green">25</font></a></td>
<td align="right"><a href="https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-mutrino-intel-opt-openmp-KNL&field2=testname&compare2=61&value2=KokkosKernels_blas_openmp_MPI_1&field3=site&compare3=61&value3=mutrino&field4=buildstarttime&compare4=84&value4=2019-04-02T00:00:00&field5=buildstarttime&compare5=83&value5=2019-03-03T00:00:00"><font color="red">0</font></a></td>
<td align="right"><a href="https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-mutrino-intel-opt-openmp-KNL&field2=testname&compare2=61&value2=KokkosKernels_blas_openmp_MPI_1&field3=site&compare3=61&value3=mutrino&field4=buildstarttime&compare4=84&value4=2019-04-02T00:00:00&field5=buildstarttime&compare5=83&value5=2019-03-03T00:00:00"><font color="green">25</font></a></td>
<td align="right"><a href="https://github.com/trilinos/Trilinos/issues/3864">#3864</a></td>
</tr>

<tr>
<td align="left">mutrino</td>
<td align="left"><a href="https://testing.sandia.gov/cdash/index.php?project=Trilinos&filtercombine=and&filtercombine=&filtercount=4&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-mutrino-intel-opt-openmp-KNL&field2=site&compare2=61&value2=mutrino&field3=buildstarttime&compare3=84&value3=2019-04-02T00:00:00&field4=buildstarttime&compare4=83&value4=2019-03-03T00:00:00">Trilinos-atdm-mutrino-intel-opt-openmp-KNL</a></td>
<td align="left"><a href="https://testing.sandia.gov/cdash/testDetails.php?test=73129519&build=4815643">KokkosKernels_&shy;blas_&shy;serial_&shy;MPI_&shy;1</a></td>
<td align="left"><a href="https://testing.sandia.gov/cdash/testDetails.php?test=73129519&build=4815643"><font color="green">Passed</font></a></td>
<td align="left">Completed</td>
<td align="right"><a href="https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-mutrino-intel-opt-openmp-KNL&field2=testname&compare2=61&value2=KokkosKernels_blas_serial_MPI_1&field3=site&compare3=61&value3=mutrino&field4=buildstarttime&compare4=84&value4=2019-04-02T00:00:00&field5=buildstarttime&compare5=83&value5=2019-03-03T00:00:00"><font color="green">25</font></a></td>
<td align="right"><a href="https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-mutrino-intel-opt-openmp-KNL&field2=testname&compare2=61&value2=KokkosKernels_blas_serial_MPI_1&field3=site&compare3=61&value3=mutrino&field4=buildstarttime&compare4=84&value4=2019-04-02T00:00:00&field5=buildstarttime&compare5=83&value5=2019-03-03T00:00:00"><font color="red">0</font></a></td>
<td align="right"><a href="https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-mutrino-intel-opt-openmp-KNL&field2=testname&compare2=61&value2=KokkosKernels_blas_serial_MPI_1&field3=site&compare3=61&value3=mutrino&field4=buildstarttime&compare4=84&value4=2019-04-02T00:00:00&field5=buildstarttime&compare5=83&value5=2019-03-03T00:00:00"><font color="green">25</font></a></td>
<td align="right"><a href="https://github.com/trilinos/Trilinos/issues/3864">#3864</a></td>
</tr>

<tr>
<td align="left">mutrino</td>
<td align="left"><a href="https://testing.sandia.gov/cdash/index.php?project=Trilinos&filtercombine=and&filtercombine=&filtercount=4&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-mutrino-intel-opt-openmp-KNL&field2=site&compare2=61&value2=mutrino&field3=buildstarttime&compare3=84&value3=2019-04-02T00:00:00&field4=buildstarttime&compare4=83&value4=2019-03-03T00:00:00">Trilinos-atdm-mutrino-intel-opt-openmp-KNL</a></td>
<td align="left"><a href="https://testing.sandia.gov/cdash/testDetails.php?test=73129516&build=4815643">KokkosKernels_&shy;common_&shy;openmp_&shy;MPI_&shy;1</a></td>
<td align="left"><a href="https://testing.sandia.gov/cdash/testDetails.php?test=73129516&build=4815643"><font color="green">Passed</font></a></td>
<td align="left">Completed</td>
<td align="right"><a href="https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-mutrino-intel-opt-openmp-KNL&field2=testname&compare2=61&value2=KokkosKernels_common_openmp_MPI_1&field3=site&compare3=61&value3=mutrino&field4=buildstarttime&compare4=84&value4=2019-04-02T00:00:00&field5=buildstarttime&compare5=83&value5=2019-03-03T00:00:00"><font color="green">25</font></a></td>
<td align="right"><a href="https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-mutrino-intel-opt-openmp-KNL&field2=testname&compare2=61&value2=KokkosKernels_common_openmp_MPI_1&field3=site&compare3=61&value3=mutrino&field4=buildstarttime&compare4=84&value4=2019-04-02T00:00:00&field5=buildstarttime&compare5=83&value5=2019-03-03T00:00:00"><font color="red">0</font></a></td>
<td align="right"><a href="https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-mutrino-intel-opt-openmp-KNL&field2=testname&compare2=61&value2=KokkosKernels_common_openmp_MPI_1&field3=site&compare3=61&value3=mutrino&field4=buildstarttime&compare4=84&value4=2019-04-02T00:00:00&field5=buildstarttime&compare5=83&value5=2019-03-03T00:00:00"><font color="green">25</font></a></td>
<td align="right"><a href="https://github.com/trilinos/Trilinos/issues/3864">#3864</a></td>
</tr>

<tr>
<td align="left">mutrino</td>
<td align="left"><a href="https://testing.sandia.gov/cdash/index.php?project=Trilinos&filtercombine=and&filtercombine=&filtercount=4&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-mutrino-intel-opt-openmp-KNL&field2=site&compare2=61&value2=mutrino&field3=buildstarttime&compare3=84&value3=2019-04-02T00:00:00&field4=buildstarttime&compare4=83&value4=2019-03-03T00:00:00">Trilinos-atdm-mutrino-intel-opt-openmp-KNL</a></td>
<td align="left"><a href="https://testing.sandia.gov/cdash/testDetails.php?test=73129518&build=4815643">KokkosKernels_&shy;common_&shy;serial_&shy;MPI_&shy;1</a></td>
<td align="left"><a href="https://testing.sandia.gov/cdash/testDetails.php?test=73129518&build=4815643"><font color="green">Passed</font></a></td>
<td align="left">Completed</td>
<td align="right"><a href="https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-mutrino-intel-opt-openmp-KNL&field2=testname&compare2=61&value2=KokkosKernels_common_serial_MPI_1&field3=site&compare3=61&value3=mutrino&field4=buildstarttime&compare4=84&value4=2019-04-02T00:00:00&field5=buildstarttime&compare5=83&value5=2019-03-03T00:00:00"><font color="green">25</font></a></td>
<td align="right"><a href="https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-mutrino-intel-opt-openmp-KNL&field2=testname&compare2=61&value2=KokkosKernels_common_serial_MPI_1&field3=site&compare3=61&value3=mutrino&field4=buildstarttime&compare4=84&value4=2019-04-02T00:00:00&field5=buildstarttime&compare5=83&value5=2019-03-03T00:00:00"><font color="red">0</font></a></td>
<td align="right"><a href="https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-mutrino-intel-opt-openmp-KNL&field2=testname&compare2=61&value2=KokkosKernels_common_serial_MPI_1&field3=site&compare3=61&value3=mutrino&field4=buildstarttime&compare4=84&value4=2019-04-02T00:00:00&field5=buildstarttime&compare5=83&value5=2019-03-03T00:00:00"><font color="green">25</font></a></td>
<td align="right"><a href="https://github.com/trilinos/Trilinos/issues/3864">#3864</a></td>
</tr>

<tr>
<td align="left">mutrino</td>
<td align="left"><a href="https://testing.sandia.gov/cdash/index.php?project=Trilinos&filtercombine=and&filtercombine=&filtercount=4&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-mutrino-intel-opt-openmp-KNL&field2=site&compare2=61&value2=mutrino&field3=buildstarttime&compare3=84&value3=2019-04-02T00:00:00&field4=buildstarttime&compare4=83&value4=2019-03-03T00:00:00">Trilinos-atdm-mutrino-intel-opt-openmp-KNL</a></td>
<td align="left"><a href="https://testing.sandia.gov/cdash/testDetails.php?test=73129517&build=4815643">KokkosKernels_&shy;graph_&shy;openmp_&shy;MPI_&shy;1</a></td>
<td align="left"><a href="https://testing.sandia.gov/cdash/testDetails.php?test=73129517&build=4815643"><font color="green">Passed</font></a></td>
<td align="left">Completed</td>
<td align="right"><a href="https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-mutrino-intel-opt-openmp-KNL&field2=testname&compare2=61&value2=KokkosKernels_graph_openmp_MPI_1&field3=site&compare3=61&value3=mutrino&field4=buildstarttime&compare4=84&value4=2019-04-02T00:00:00&field5=buildstarttime&compare5=83&value5=2019-03-03T00:00:00"><font color="green">25</font></a></td>
<td align="right"><a href="https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-mutrino-intel-opt-openmp-KNL&field2=testname&compare2=61&value2=KokkosKernels_graph_openmp_MPI_1&field3=site&compare3=61&value3=mutrino&field4=buildstarttime&compare4=84&value4=2019-04-02T00:00:00&field5=buildstarttime&compare5=83&value5=2019-03-03T00:00:00"><font color="red">0</font></a></td>
<td align="right"><a href="https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-mutrino-intel-opt-openmp-KNL&field2=testname&compare2=61&value2=KokkosKernels_graph_openmp_MPI_1&field3=site&compare3=61&value3=mutrino&field4=buildstarttime&compare4=84&value4=2019-04-02T00:00:00&field5=buildstarttime&compare5=83&value5=2019-03-03T00:00:00"><font color="green">25</font></a></td>
<td align="right"><a href="https://github.com/trilinos/Trilinos/issues/3864">#3864</a></td>
</tr>

<tr>
<td align="left">mutrino</td>
<td align="left"><a href="https://testing.sandia.gov/cdash/index.php?project=Trilinos&filtercombine=and&filtercombine=&filtercount=4&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-mutrino-intel-opt-openmp-KNL&field2=site&compare2=61&value2=mutrino&field3=buildstarttime&compare3=84&value3=2019-04-02T00:00:00&field4=buildstarttime&compare4=83&value4=2019-03-03T00:00:00">Trilinos-atdm-mutrino-intel-opt-openmp-KNL</a></td>
<td align="left"><a href="https://testing.sandia.gov/cdash/testDetails.php?test=73129521&build=4815643">KokkosKernels_&shy;graph_&shy;serial_&shy;MPI_&shy;1</a></td>
<td align="left"><a href="https://testing.sandia.gov/cdash/testDetails.php?test=73129521&build=4815643"><font color="green">Passed</font></a></td>
<td align="left">Completed</td>
<td align="right"><a href="https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-mutrino-intel-opt-openmp-KNL&field2=testname&compare2=61&value2=KokkosKernels_graph_serial_MPI_1&field3=site&compare3=61&value3=mutrino&field4=buildstarttime&compare4=84&value4=2019-04-02T00:00:00&field5=buildstarttime&compare5=83&value5=2019-03-03T00:00:00"><font color="green">25</font></a></td>
<td align="right"><a href="https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-mutrino-intel-opt-openmp-KNL&field2=testname&compare2=61&value2=KokkosKernels_graph_serial_MPI_1&field3=site&compare3=61&value3=mutrino&field4=buildstarttime&compare4=84&value4=2019-04-02T00:00:00&field5=buildstarttime&compare5=83&value5=2019-03-03T00:00:00"><font color="red">0</font></a></td>
<td align="right"><a href="https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-mutrino-intel-opt-openmp-KNL&field2=testname&compare2=61&value2=KokkosKernels_graph_serial_MPI_1&field3=site&compare3=61&value3=mutrino&field4=buildstarttime&compare4=84&value4=2019-04-02T00:00:00&field5=buildstarttime&compare5=83&value5=2019-03-03T00:00:00"><font color="green">25</font></a></td>
<td align="right"><a href="https://github.com/trilinos/Trilinos/issues/3864">#3864</a></td>
</tr>

<tr>
<td align="left">mutrino</td>
<td align="left"><a href="https://testing.sandia.gov/cdash/index.php?project=Trilinos&filtercombine=and&filtercombine=&filtercount=4&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-mutrino-intel-opt-openmp-KNL&field2=site&compare2=61&value2=mutrino&field3=buildstarttime&compare3=84&value3=2019-04-02T00:00:00&field4=buildstarttime&compare4=83&value4=2019-03-03T00:00:00">Trilinos-atdm-mutrino-intel-opt-openmp-KNL</a></td>
<td align="left"><a href="https://testing.sandia.gov/cdash/testDetails.php?test=73129515&build=4815643">KokkosKernels_&shy;sparse_&shy;openmp_&shy;MPI_&shy;1</a></td>
<td align="left"><a href="https://testing.sandia.gov/cdash/testDetails.php?test=73129515&build=4815643"><font color="green">Passed</font></a></td>
<td align="left">Completed</td>
<td align="right"><a href="https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-mutrino-intel-opt-openmp-KNL&field2=testname&compare2=61&value2=KokkosKernels_sparse_openmp_MPI_1&field3=site&compare3=61&value3=mutrino&field4=buildstarttime&compare4=84&value4=2019-04-02T00:00:00&field5=buildstarttime&compare5=83&value5=2019-03-03T00:00:00"><font color="green">1</font></a></td>
<td align="right"><a href="https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-mutrino-intel-opt-openmp-KNL&field2=testname&compare2=61&value2=KokkosKernels_sparse_openmp_MPI_1&field3=site&compare3=61&value3=mutrino&field4=buildstarttime&compare4=84&value4=2019-04-02T00:00:00&field5=buildstarttime&compare5=83&value5=2019-03-03T00:00:00"><font color="red">1</font></a></td>
<td align="right"><a href="https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-mutrino-intel-opt-openmp-KNL&field2=testname&compare2=61&value2=KokkosKernels_sparse_openmp_MPI_1&field3=site&compare3=61&value3=mutrino&field4=buildstarttime&compare4=84&value4=2019-04-02T00:00:00&field5=buildstarttime&compare5=83&value5=2019-03-03T00:00:00"><font color="green">24</font></a></td>
<td align="right"><a href="https://github.com/trilinos/Trilinos/issues/3864">#3864</a></td>
</tr>

<tr>
<td align="left">mutrino</td>
<td align="left"><a href="https://testing.sandia.gov/cdash/index.php?project=Trilinos&filtercombine=and&filtercombine=&filtercount=4&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-mutrino-intel-opt-openmp-KNL&field2=site&compare2=61&value2=mutrino&field3=buildstarttime&compare3=84&value3=2019-04-02T00:00:00&field4=buildstarttime&compare4=83&value4=2019-03-03T00:00:00">Trilinos-atdm-mutrino-intel-opt-openmp-KNL</a></td>
<td align="left"><a href="https://testing.sandia.gov/cdash/testDetails.php?test=73129514&build=4815643">KokkosKernels_&shy;sparse_&shy;serial_&shy;MPI_&shy;1</a></td>
<td align="left"><a href="https://testing.sandia.gov/cdash/testDetails.php?test=73129514&build=4815643"><font color="green">Passed</font></a></td>
<td align="left">Completed</td>
<td align="right"><a href="https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-mutrino-intel-opt-openmp-KNL&field2=testname&compare2=61&value2=KokkosKernels_sparse_serial_MPI_1&field3=site&compare3=61&value3=mutrino&field4=buildstarttime&compare4=84&value4=2019-04-02T00:00:00&field5=buildstarttime&compare5=83&value5=2019-03-03T00:00:00"><font color="green">25</font></a></td>
<td align="right"><a href="https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-mutrino-intel-opt-openmp-KNL&field2=testname&compare2=61&value2=KokkosKernels_sparse_serial_MPI_1&field3=site&compare3=61&value3=mutrino&field4=buildstarttime&compare4=84&value4=2019-04-02T00:00:00&field5=buildstarttime&compare5=83&value5=2019-03-03T00:00:00"><font color="red">0</font></a></td>
<td align="right"><a href="https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-mutrino-intel-opt-openmp-KNL&field2=testname&compare2=61&value2=KokkosKernels_sparse_serial_MPI_1&field3=site&compare3=61&value3=mutrino&field4=buildstarttime&compare4=84&value4=2019-04-02T00:00:00&field5=buildstarttime&compare5=83&value5=2019-03-03T00:00:00"><font color="green">25</font></a></td>
<td align="right"><a href="https://github.com/trilinos/Trilinos/issues/3864">#3864</a></td>
</tr>

</table>
