### ISSUE TITLE
Include Amesos2 into Stratimikos package

### ISSUE THREAD

**Issue by mjuha** [trilinos/Trilinos#388]
Dear developers,

Now that trilinos is moving to a Tpetra version, it should be important to have a sparse direct solver, based on a Tpetra operator, implemented into the Stratimikos package. This will also be beneficial in Albany Multi physics code because Albany uses stratimikos. Then we will have a direct sparse solver for the Tpetra version of Albany.

Cordially,

Mario J. Juha

**Comment by ibaned** [comment]
This will be resolved if/when #1090 is merged.
