### ISSUE TITLE
Zoltan_ch_onedbug_zoltan_parallel

### ISSUE THREAD

**Issue by jwillenbring** [trilinos/Trilinos#389]
@trilinos/zoltan 
I am trying to set up a new cdash dashboard, or fix the cdash problems we have been having in some way. I discovered today that the 

Zoltan_ch_onedbug_zoltan_parallel

test has 27MB of test output, in over 200,000 lines. I recognize this is a 'dbug' test, and that might be intentional, but I wanted to verify that you do in fact want that much test output. I also wanted to see if so, if this test should be run by default for all builds. Preliminary indications seem to be that a very small number of tests accounts for a very, very large percentage of all data that needs to be uploaded, so I wanted to start to dig into some of these situations.  We are not certain how much trimming very large tests would help the current situation, but we do know that the largest available cdash subscription level is 1024 MB/day. I had a single submission of just 11 packages taking up over 41 MB, so 1024 MB doesn't go very far.  Thanks for any comments on this issue.

http://my.cdash.org/testDetails.php?test=25237435&build=965387

**Comment by kddevin** [comment]
We can certainly change this test to either produce less output or not make it run for all testing configurations.  
Please let me know what your timeframe (deadlines) and urgency (importance) are for resolving this issue.  Thanks.

**Comment by jwillenbring** [comment]
Karen,

Thanks for the reply. I think the urgency of this is somewhat decreased for right now. We can't likely make my.cdash.org work for a long-term solution. We will gather more data. It is not clear to me yet if reducing test output for a relatively small number of tests will make a meaningful difference for our dashboards.

**Comment by kddevin** [comment]
Thanks, Jim.  I will close the bug for now, then.  Please reopen it when/if you need us to do something about this test's output.
