### ISSUE TITLE
MueLu_UnitTests[Blocked][Epetra|Tpetra]_MPI_4 failing randomly on several ATDM builds

### ISSUE THREAD

**Issue by fryeguy52** [trilinos/Trilinos#3897]
CC: @trilinos/MueLu, @srajama1 (Trilinos Linear Solvers Product Lead), @bartlettroscoe 
 
## Next Action Status

PR #4046 merged to 'develop' on 12/18/2018 may fix these random failures.  Next: Watch for more failures over the coming days and weeks to see if there are any more failures ...

## Description

As shown in the links below the tests:
* [MueLu_UnitTestsBlockedEpetra_MPI_4](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-&field2=buildname&compare2=62&value2=Trilinos-atdm-cee-rhel6-gnu-7.2.0-opt-serial&field3=testname&compare3=61&value3=MueLu_UnitTestsBlockedEpetra_MPI_4&field4=status&compare4=61&value4=failed&field5=buildstarttime&compare5=83&value5=2018-10-17)
* [MueLu_UnitTestsEpetra_MPI_4](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-&field2=testname&compare2=61&value2=MueLu_UnitTestsEpetra_MPI_4&field3=status&compare3=61&value3=failed&field4=details&compare4=64&value4=Timeout&field5=buildstarttime&compare5=83&value5=2018-10-16)
* [MueLu_­UnitTestsEpetra_­MPI_­1](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-&field2=testname&compare2=61&value2=MueLu_UnitTestsEpetra_MPI_1&field3=status&compare3=61&value3=failed&field4=details&compare4=64&value4=Timeout&field5=buildstarttime&compare5=83&value5=2018-10-16)
* [MueLu_­UnitTestsTpetra_­MPI_­1](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-&field2=testname&compare2=61&value2=MueLu_UnitTestsTpetra_MPI_1&field3=status&compare3=61&value3=failed&field4=details&compare4=64&value4=Timeout&field5=buildstarttime&compare5=83&value5=2018-10-16)
* [MueLu_UnitTestsTpetra_MPI_1](https://testing.sandia.gov/cdash/testDetails.php?test=61339618&build=4287170)

are randomly failing across several builds.  They has failed several times in the last month on different builds.  The builds where we have seen failures are:

* Trilinos-atdm-cee-rhel6-gnu-4.9.3-opt-serial
* Trilinos-atdm-cee-rhel6-gnu-opt-serial
* Trilinos-atdm-cee-rhel6-intel-opt-serial
* Trilinos-atdm-hansen-shiller-gnu-opt-openmp
* Trilinos-atdm-hansen-shiller-gnu-opt-serial
* Trilinos-atdm-hansen-shiller-gnu-opt-serial
* Trilinos-atdm-hansen-shiller-intel-debug-openmp
* Trilinos-atdm-hansen-shiller-intel-debug-serial
* Trilinos-atdm-mutrino-intel-opt-openmp-HSW
* Trilinos-atdm-mutrino-intel-opt-openmp-KNL
* Trilinos-atdm-sems-rhel6-gnu-debug-openmp
* Trilinos-atdm-sems-rhel6-intel-opt-openmp
* Trilinos-atdm-serrano-intel-opt-openmp
* Trilinos-atdm-waterman-gnu-opt-openmp
* Trilinos-atdm-waterman-gnu-release-debug-openmp
* Trilinos-atdm-white-ride-cuda-9.2-opt
* Trilinos-atdm-white-ride-gnu-opt-openmp

It looks like that in each case something similar to the following appears in the 'openmp' builds:

```
...

p=0: *** Caught standard std::exception of type 'Xpetra::Exceptions::RuntimeError' :

  EpetraExt::MatrixMarketFileToCrsMatrix return value of -1
 [FAILED]  (0.0902 sec) Hierarchy_double_int_int_Kokkos_Compat_KokkosOpenMPWrapperNode_Write_UnitTest
 Location: /home/jenkins/hansen/workspace/Trilinos-atdm-hansen-shiller-intel-debug-openmp/SRC_AND_BUILD/Trilinos/packages/muelu/test/unit_tests/Hierarchy.cpp:889
...

The following tests FAILED:
    116. Hierarchy_double_int_int_Kokkos_Compat_KokkosOpenMPWrapperNode_Write_UnitTest ... 

...
```

and the 'serial' builds show:

```
...

p=0: *** Caught standard std::exception of type 'Xpetra::Exceptions::RuntimeError' :
 
  EpetraExt::MatrixMarketFileToCrsMatrix return value of -1
 [FAILED]  (0.00618 sec) Hierarchy_double_int_int_Kokkos_Compat_KokkosSerialWrapperNode_Write_UnitTest
 Location: /jenkins/slave/workspace/Trilinos-atdm-sems-rhel6-gnu-debug-serial/SRC_AND_BUILD/Trilinos/packages/muelu/test/unit_tests/Hierarchy.cpp:889

...

The following tests FAILED:
    116. Hierarchy_double_int_int_Kokkos_Compat_KokkosSerialWrapperNode_Write_UnitTest ... 

...
```

It is just that one failing unit test 116 called `Hierarchy_double_int_int_Kokkos_Compat_KokkosSerialWrapperNode_Write_UnitTest` in the 'serial' builds and called `Hierarchy_double_int_int_Kokkos_Compat_KokkosOpenMPWrapperNode_Write_UnitTest` in the 'openmp' builds.

The first failure showed up on 2018-10-21

## Current Status on CDash

To see failures for these tests in the last month click [here](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-&field2=testname&compare2=65&value2=MueLu_UnitTests&field3=status&compare3=61&value3=failed&field4=details&compare4=64&value4=Timeout&field5=buildstarttime&compare5=83&value5=30%20days%20ago).

## Steps to Reproduce

This may be very difficult to reproduce because it is failing infrequently on a single build but nearly every other day across all the builds.  Instructions for reproducing ATDM builds can be found at:
* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md

More specifically, the commands given for ride or white are provided at:
* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#ridewhite

The exact commands to reproduce one build where this has failed on white or ride are:
```
$ cd <some_build_dir>/
$ source $TRILINOS_DIR/cmake/std/atdm/load-env.sh Trilinos-atdm-white-ride-gnu-opt-openmp
$ cmake \
 -GNinja \
 -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
 -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_MueLu=ON \
 $TRILINOS_DIR
$ make NP=16
$ bsub -x -Is -q rhel7F -n 16 ctest -j16

**Comment by bartlettroscoe** [comment]
NOTE: It is just that one failing unit test 116 called `Hierarchy_double_int_int_Kokkos_Compat_KokkosSerialWrapperNode_Write_UnitTest` in the 'serial' builds and called `Hierarchy_double_int_int_Kokkos_Compat_KokkosOpenMPWrapperNode_Write_UnitTest` in the 'openmp' builds.

**Comment by srajama1** [comment]
@trilinos/muelu 

Why is this Epetra test important for ATDM ? Both codes use the Tpetra stack. Panzer has a dependency on Epetra for historic reasons, but can we explicitly turn off Epetra for ATDM builds ?

**Comment by bartlettroscoe** [comment]
> Why is this Epetra test important for ATDM ? Both codes use the Tpetra stack. Panzer has a dependency on Epetra for historic reasons, but can we explicitly turn off Epetra for ATDM builds ?

@srajama1, that is a good question.  @jhux2, do the ATDM APPs use Epetra support under MueLu?  We turned this test back on because you requested to do so (see https://github.com/trilinos/Trilinos/issues/2674#issuecomment-431512088).

But note that the same unit test  116 `Hierarchy_double_int_int_Kokkos_Compat_Kokkos[Serial|OpenMP]WrapperNode_Write_UnitTest in the 'serial' is failing in both the `MueLu_UnitTestsBlockedEpetra_MPI_4` and `MueLu_UnitTestsBlocked_MPI_4` tests so if you fix this unit test in the test `MueLu_UnitTestsBlocked_MPI_4` you will automatically fix it in the test `MueLu_UnitTestsBlockedEpetra_MPI_4`.

**Comment by rppawlo** [comment]
> Panzer has a dependency on Epetra for historic reasons, but can we explicitly turn off Epetra for ATDM builds ?

Disabling epetra in panzer is going to take some time. We just don't have the manpower at this point.

**Comment by fryeguy52** [comment]
I added the tests `MueLu_­UnitTestsEpetra_­MPI_­1 ` and `MueLu_­UnitTestsTpetra_­MPI_­1 ` to the scope of this issue because they are also randomly failing across builds with:
```
The following tests FAILED:
    116. Hierarchy_double_int_int_Kokkos_Compat_KokkosSerialWrapperNode_Write_UnitTest ... 
```

**Comment by jhux2** [comment]
> do the ATDM APPs use Epetra support under MueLu? We turned this test back on because you requested to do so

@bartlettroscoe Not that I know of.  However, I think it would be better to disable Epetra entirely in that case, rather than disabling it on a package-by-package basis.

**Comment by bartlettroscoe** [comment]
> However, I think it would be better to disable Epetra entirely in that case, rather than disabling it on a package-by-package basis.

@jhux2, I don't think we can disable Epetra because that would disable a bunch of tests, especially in Panzer.  Do you have any objection to going back to setting `MueLu_ENABLE_Epetra=OFF`.  Does MueLu loose any valuable testing if Epetra is disabled?

**Comment by bartlettroscoe** [comment]
@jhux2, do you expect the commit 005ea37 merged from PR #4046 to fix all of the random failures for this unit test `116. Hierarchy_double_int_int_Kokkos_Compat_Kokkos[Serial|OpenMP]WrapperNode_Write_UnitTest`?  If so, if you put "#4046" in that PR comment, then we can see that more directly in this issue.

**Comment by bartlettroscoe** [comment]
FYI: We are also seeing this same unit test `116. Hierarchy_double_int_int_Kokkos_Compat_KokkosSerialWrapperNode_Write_UnitTest` failing in Tpetra implementation [MueLu_UnitTestsTpetra_MPI_1](https://testing.sandia.gov/cdash/testDetails.php?test=61339618&build=4287170) too.

**Comment by jhux2** [comment]
> do you expect the commit [005ea37](https://github.com/trilinos/Trilinos/commit/005ea37a58d45162b67548d9c0c33982b60b4c58) merged from PR #4046 to fix all of the random failures

@bartlettroscoe That's my hope.  (But hope is the first step on the road to disappointment.)  My current theory is that the  [TE]petra writers only ever write from proc/thread 0.  Other procs/threads might race ahead and delete the temporary file prior to it being read back in.

**Comment by bartlettroscoe** [comment]
> > do you expect the commit 005ea37 merged from PR #4046 to fix all of the random failures
> 
> @bartlettroscoe That's my hope. (But hope is the first step on the road to disappointment.) My current theory is that the [TE]petra writers only ever write from proc/thread 0. Other procs/threads might race ahead and delete the temporary file prior to it being read back in.

@jhux2, okay, then let's put this issue "in review" and we will watch CDash over the coming days and weeks to see if we see this failure pop up anymore.

**Comment by jhux2** [comment]
I haven't found any new errors with MueLu's `Hierarchy::Write()` unit test.  However, `MueLu_UnitTestsBlockedEpetra_MPI_1` is consistently failing under clang, as can be seen [here](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-&field2=testname&compare2=65&value2=MueLu_UnitTests&field3=status&compare3=61&value3=failed&field4=details&compare4=64&value4=Timeout&field5=buildstarttime&compare5=83&value5=10%20days%20ago).

PR #4072 is meant to address this.

**Comment by srajama1** [comment]
For a CDash newbie, the link above doesn't work to check if these tests are passing now. I am not able to understand all the fields in the CDash query in the link to modify them correctly.

**Comment by jhux2** [comment]
> For a CDash newbie, the link above doesn't work to check if these tests are passing now. I am not able to understand all the fields in the CDash query in the link to modify them correctly.

Try [this link](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=6&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-&field2=testname&compare2=65&value2=MueLu_UnitTests&field3=status&compare3=61&value3=failed&field4=details&compare4=64&value4=Timeout&field5=buildstarttime&compare5=83&value5=30%20days%20ago&field6=site&compare6=62&value6=white).

**Comment by bartlettroscoe** [comment]
@srajama1 said:

> For a CDash newbie, the link above doesn't work to check if these tests are passing now. I am not able to understand all the fields in the CDash query in the link to modify them correctly.

@srajama1, the link under the section "Current Status on CDash" [above](https://github.com/trilinos/Trilinos/issues/3897#issue-382327373) worked fine for me.  But note that most of those errors involve crashing tests due to a problem with a compute node on 'white' ('white25', see [TRIL-253](https://sems-atlassian-son.sandia.gov/jira/browse/TRIL-253)).  The others were from a problem with SLURM on 'mutrino' on day where it would not recognize the user account ID.  When you filter out all of those bad builds, you get [this query](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=14&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-&field2=buildname&compare2=62&value2=Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-release-debug-pt&field3=testname&compare3=65&value3=MueLu_UnitTests&field4=status&compare4=61&value4=failed&field5=details&compare5=64&value5=Timeout&field6=buildstarttime&compare6=83&value6=30%20days%20ago&field7=buildstarttime&compare7=82&value7=2019-01-20T07%3A46%3A09%20UTC&field8=buildstarttime&compare8=82&value8=2019-01-16T09%3A09%3A06%20UTC&field9=buildstarttime&compare9=82&value9=2019-01-15T07%3A46%3A18%20UTC&field10=buildstarttime&compare10=82&value10=2019-01-13T11%3A23%3A13%20UTC&field11=buildstarttime&compare11=82&value11=2019-01-10T11%3A06%3A18%20UTC&field12=buildstarttime&compare12=82&value12=2019-01-09T11%3A06%3A30%20UTC&field13=buildstarttime&compare13=82&value13=2018-12-27T11%3A09%3A13%20UTC&field14=buildstarttime&compare14=82&value14=2019-01-16T07%3A45%3A55%20UTC) which comes up empty.

I wish there was a way to mark all of these tests as system issues so that we could filter them out of queries like this but you can't do that on CDash without deleting the entire builds.  (There are features we can request from CDash in the future that could help to address tests like this.)

Sorry for so many test failures that show up due to system issues like this.  It just seems to be the nature of these machines.

**Comment by lucbv** [comment]
@bartlettroscoe @fryeguy52 are we still observing these issue or are things somehow better these days?
I have not seen failures on [this](https://testing.sandia.gov/cdash/index.php?subproject=MueLu&project=Trilinos) dashboard in the ATDM track for some time now.

**Comment by bartlettroscoe** [comment]
@lucbv adked:

> @bartlettroscoe @fryeguy52 are we still observing these issue or are things somehow better these days?

Please see the link provided under "Current Status on CDash" [above](https://github.com/trilinos/Trilinos/issues/3897#issue-382327373).  That should provide the data needed to determine status of this.  Please let us know if you have questions about what that CDash query shows.

**Comment by jhux2** [comment]
According to the link under "Current Status on CDash", the only failures are on white, and those look like slurm or environment problems.  Therefore I am closing this.
