### ISSUE TITLE
Can't download trilinos

### ISSUE THREAD

**Issue by VictorEijkhout** [trilinos/Trilinos#3900]
Connecting to trilinos.csbsju.edu (trilinos.csbsju.edu)|152.65.160.65|:80... failed:

**Comment by VictorEijkhout** [comment]
Guys this is obscene! Your website "https://trilinos.org/download/" has links to your "oldsite". I've alerted you to the dangers of having an old site that is indistinguishable from the new site before!

**Comment by mhoemmen** [comment]
@trilinos/framework

**Comment by jmgate** [comment]
Out of curiosity, why do we support downloads when one can just
```bash
git clone git@github.com:trilinos/Trilinos
cd Trilinos
git checkout trilinos-release-12-12-1
```

?

**Comment by VictorEijkhout** [comment]
On Nov 19, 2018, at 2:57 PM, Jason M. Gates <notifications@github.com<mailto:notifications@github.com>> wrote:

one can just

Victor’s rules of technical writing: #1 never use the words “just”. It usually hides the fact that your argument is missing steps.

For instance, 1. this fact is not published. 2. the download page doesn’t even mention github, so even you’d published it, a google search for “trilinos download” would still take you to the wrong location.

Victor.

**Comment by csiefer2** [comment]
@trilinos/framework  I believe website improvements are on your agenda, yes?

**Comment by jhux2** [comment]
@trilinos/framework @VictorEijkhout  I just added a big, bold message at the top of the download page.  It points to github and mentions this issue.

**Comment by william76** [comment]
This should grab the latest branch that I see in the repo as a zipfile:
- https://github.com/trilinos/Trilinos/archive/trilinos-release-12-14-branch.zip

@jwillenbring I tried downloading Trilinos via the links at https://trilinos.org and at [https://trilinos.github.io][1] ... it timed out from both locations for me... should we update the links there to point at the github zip download or is the zip file that's normally downloaded from there different from a vanilla clone of the zipfile?

@csiefer2, Yeah... I think things are moving to https://trilnos.github.io, we haven't discussed the website in our meetings in a while. I'll bring it up in our meeting on Wednesday to get updated on that.

[1]: https://trilinos.github.io

**Comment by jhux2** [comment]
The older issue is #2616.  I'll close that one in favor of this one.

**Comment by jhux2** [comment]
@jrobcary Hmm, not sure.  Have a look here: https://help.github.com/articles/which-remote-url-should-i-use/

**Comment by bobbielf2** [comment]
@jrobcary Try use `git clone https://github.com/trilinos/Trilinos.git` instead?

**Comment by jrobcary** [comment]
I found that this works:

`wget https://github.com/trilinos/Trilinos/archive/trilinos-release-12-12-1.zip`

after which I do

`unzip trilinos-release-12-12-1.zip`
`mv Trilinos-trilinos-release-12-12-1 trilinos-12.12.1`
`env COPYFILE_DISABLE=true tar cJf trilinos-12.12.1.tar.xz trilinos-12.12.1`

to get a tarball with the standard naming.

**Comment by mhoemmen** [comment]
That tarballs is at least three years old btw. Current accepted practice is to follow master.

**Comment by jmgate** [comment]
@jrobcary, have you added a public SSH key to your GitHub account?  If not, can you try `git clone https://github.com/trilinos/Trilinos` and see if you have better luck there?

**Comment by hkthorn** [comment]
I'm just going to point out that Xyce still requires Trilinos 12.12.1 and has not upgraded to newer versions of Trilinos because of the C++11 issues on COE machines that still linger.  So, I understand the response that users should be interacting with more recent versions or the master branch of Trilinos.  However, there may be cause for them to need Trilinos 12.12.1, so keep that in mind.

**Comment by jrobcary** [comment]
Similar to @hkthorn, as deliverers of endpoint software, facing problems with builds, validation, provenance, etc., we like to work from a particular release that has been tested in the field and that we have appropriately patched to work in all of our build environments.  So I hope that the "work from master" idea does not mean that trilinos will no longer have numbered releases.  ????

(Cloning is not the issue, we have done that.  But the particular URL given did not work out of the box.  The wget method did, and so I wanted to share that in case it could help anyone else.)

**Comment by mhoemmen** [comment]
@maherou is ultimately responsible for deciding (or not deciding, in this case) on the release schedule.  If you want regular releases, talk to him, and to @trilinos/framework.

**Comment by jhux2** [comment]
Closing as fixed.  See https://github.com/trilinos/trilinos.github.io/issues/32.
