### ISSUE TITLE
Tpetra BlockCrsMatrix fails to compile wiht GCC 4.7.2 due to internal compiler error

### ISSUE THREAD

**Issue by crtrott** [trilinos/Trilinos#393]
@mhoemmen 
@trilinos/tpetra 

Looks like the particular usage of lambdas does not play well with GCC 4.7.2:

```
make[2]: *** [packages/tpetra/core/src/CMakeFiles/tpetra.dir/Tpetra_Experimental_BlockCrsMatrix_COMPLEX_DOUBLE_INT_INT_OPENMP.cpp.o] Error 1
In file included from /home/projects/install/rhel6-x86_64/sems/compiler/gcc/4.7.2/base/bin/../lib/gcc/x86_64-unknown-linux-gnu/4.7.2/../../../../include/c++/4.7.2/functional:56:0,
                 from /home/projects/install/rhel6-x86_64/sems/compiler/gcc/4.7.2/base/bin/../lib/gcc/x86_64-unknown-linux-gnu/4.7.2/../../../../include/c++/4.7.2/bits/stl_algo.h:68,
                 from /home/projects/install/rhel6-x86_64/sems/compiler/gcc/4.7.2/base/bin/../lib/gcc/x86_64-unknown-linux-gnu/4.7.2/../../../../include/c++/4.7.2/algorithm:63,
                 from /home/crtrott/Trilinos/packages/kokkos/core/src/KokkosExp_View.hpp:48,
                 from /home/crtrott/Trilinos/packages/kokkos/core/src/Kokkos_View.hpp:2104,
                 from /home/crtrott/Trilinos/packages/kokkos/core/src/Kokkos_Parallel.hpp:52,
                 from /home/crtrott/Trilinos/packages/kokkos/core/src/Kokkos_Serial.hpp:52,
                 from /home/crtrott/Trilinos/packages/kokkos/core/src/Kokkos_Core.hpp:53,
                 from /home/crtrott/Trilinos/packages/teuchos/kokkoscompat/src/KokkosCompat_View.hpp:58,
                 from /home/crtrott/Trilinos/packages/teuchos/kokkoscompat/src/KokkosCompat_ClassicNodeAPI_Wrapper.hpp:5,
                 from /home/crtrott/TrilinosBuild/OpenMP/GCC/4.7.2/Downstream/build/packages/tpetra/core/src/Tpetra_Experimental_BlockCrsMatrix_DOUBLE_INT_LONG_LONG_OPENMP.cpp:68:
/home/projects/install/rhel6-x86_64/sems/compiler/gcc/4.7.2/base/bin/../lib/gcc/x86_64-unknown-linux-gnu/4.7.2/../../../../include/c++/4.7.2/tuple: In lambda function:
/home/projects/install/rhel6-x86_64/sems/compiler/gcc/4.7.2/base/bin/../lib/gcc/x86_64-unknown-linux-gnu/4.7.2/../../../../include/c++/4.7.2/tuple:501:12: internal compiler error: in get_expr_operands, at tree-ssa-operands.c:1035
```

**Comment by nmhamster** [comment]
Can you try this on a non-SEMS GCC 4.7.2 as well just to check it really is an ICE. My guess is that this will be the same, just want to check the optimizer isn't hurt. This is a real pain.

**Comment by crtrott** [comment]
Yeah can do, but probably not today. I am trying to get through an integration cycle of Kokkos to Trilinos, and am already about 14 hours into that ....

**Comment by crtrott** [comment]
Yeah can do, but probably not today. I am trying to get through an integration cycle of Kokkos to Trilinos, and am already about 14 hours into that ....

**Comment by crtrott** [comment]
Yeah can do, but probably not today. I am trying to get through an integration cycle of Kokkos to Trilinos, and am already about 14 hours into that ....

**Comment by nmhamster** [comment]
Well hopefully you aren't going to integrate if there is a ICE in the main compiler right?

**Comment by crtrott** [comment]
This is present in the current master branch of Trilinos. The issue is identified as coming from the lambda implementation of the BlockCSR Matvec in Tpetra.

**Comment by ambrad** [comment]
Confirmed with my own workstation's 4.7.2, built myself from the source when 4.7.2 became the min required. The message is this:

/home/ambradl/bigcode/tril/Trilinos/CHECKIN/MPI_DEBUG/packages/tpetra/core/src/Tpetra_Experimental_BlockCrsMatrix_DOUBLE_INT_INT_SERIAL.cpp:80:1: internal compiler error: in get_expr_operands, at tree-ssa-operands.c:1035

The line number in the Tpetra code is not helpful; it's just the ETI. But you can see where gcc is choking if you have the 4.7.2 source. See Mark's commits from earlier today to see the lambda function of interest.

**Comment by nmhamster** [comment]
Thanks @ambrad. This is a real pain for sure.

**Comment by mhoemmen** [comment]
I'm on it.

**Comment by mhoemmen** [comment]
Part of #178 is replacing the lambda with a functor anyway.  Here's my plan:

  1. Temporarily revert to the sequential code for GCC < 4.8
  2. Replace lambda with a functor (needed for #178 anyway)

**Comment by crtrott** [comment]
Sounds good to me.

**Comment by mhoemmen** [comment]
@DrBooom is also interested in a fix.
