### ISSUE TITLE
Significant frequent CDash submit failures to testing-vm.sandia.gov/cdash Trilinos project starting mid 11/2018

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#3930]
@trilinos/framework, @fryeguy52 

## Next Action Status

After addressing jenkins-srn.sandia.gov builds crashing by moving start times (see [TRIL-237](https://sems-atlassian-son.sandia.gov/jira/browse/TRIL-237)), we finally saw a day 12/19/2018 with full build and test results on CDash.  Next: Watch for a couple of weeks over XMAS break to see if any more CDash failures occur and then close first week of Jan 2019 if no more submit failures are seen ...

## Description

Starting around 11/18/2018 or so, we started to see significant numbers of CDash submit failures.  This has resulted in up to 9 out of 30 promoted ATDM Trilinos builds not submitting test results as shown, for example, [on CDash on 11/25/2018](https://testing.sandia.gov/cdash-dev-view/index.php?project=Trilinos&date=2018-11-25&filtercount=1&showfilters=1&field1=buildname&compare1=65&value1=Trilinos-atdm-).  You can see that these seem to be CDash submit failures from looking at the Jenkins output.  And we see not just failures to submit test results (but that is the most common submit failure) but we also see failures to submit 'update' and 'configure' results in:

* https://jenkins-son.sandia.gov/view/Trilinos%20ATDM/job/Trilinos-atdm-hansen-shiller-cuda-8.0-opt/184/consoleFull

showing:

```
00:25:14 Submit files (using http)
00:25:14    Send to track: ATDM
00:25:14    Using HTTP submit method
00:25:14    Drop site:http://testing-vm.sandia.gov/cdash/submit.php?project=Trilinos
00:27:21    Submit failed, waiting 3 seconds...
00:27:24    Retry submission: Attempt 1 of 5
00:28:06    Submission failed: Checksum failed for file.  Expected 9cc616d7c7444ddd408b2aa89977a0b8 but got 636f51bd65019e2d3d39d4fdb012ef00.
00:28:06    Submit failed, waiting 3 seconds...
00:28:09    Retry submission: Attempt 2 of 5
00:28:44    Submission failed: Checksum failed for file.  Expected 9cc616d7c7444ddd408b2aa89977a0b8 but got d41d8cd98f00b204e9800998ecf8427e.
00:28:44    Submit failed, waiting 3 seconds...
00:28:47    Retry submission: Attempt 3 of 5
00:29:34    Submission failed: Checksum failed for file.  Expected 9cc616d7c7444ddd408b2aa89977a0b8 but got 64fec38d5fd635493fd311dc65ff631c.
00:29:34    Submit failed, waiting 3 seconds...
00:29:37    Retry submission: Attempt 4 of 5
00:30:04    Submission failed: Checksum failed for file.  Expected 9cc616d7c7444ddd408b2aa89977a0b8 but got d41d8cd98f00b204e9800998ecf8427e.
00:30:04    Submit failed, waiting 3 seconds...
00:30:07    Retry submission: Attempt 5 of 5
00:32:14    Error when uploading file: /home/jenkins/hansen/workspace/Trilinos-atdm-hansen-shiller-cuda-8.0-opt/SRC_AND_BUILD/BUILD/Testing/20181125-0400/Configure.xml
00:32:14    Error message was: Failed to connect to testing-vm.sandia.gov port 80: Connection timed out
00:32:14    Problems when submitting via HTTP
```

and failures to submit 'build' results in:

* https://jenkins-son.sandia.gov/view/Trilinos%20ATDM/job/Trilinos-atdm-hansen-shiller-cuda-9.0-debug/183/consoleFull

showing:

```
11:50:15 Submit files (using http)
11:50:15    Send to track: ATDM
11:50:15    Using HTTP submit method
11:50:15    Drop site:http://testing-vm.sandia.gov/cdash/submit.php?project=Trilinos
11:50:51    Submission failed: Checksum failed for file.  Expected b6b1936e73c4fcda5459c4c3305718ad but got f33c85574fc1714cb55e743d00c37f63.
11:50:51    Submit failed, waiting 3 seconds...
11:50:54    Retry submission: Attempt 1 of 5
11:53:01    Submit failed, waiting 3 seconds...
11:53:04    Retry submission: Attempt 2 of 5
11:55:11    Submit failed, waiting 3 seconds...
11:55:14    Retry submission: Attempt 3 of 5
11:57:22    Submit failed, waiting 3 seconds...
11:57:25    Retry submission: Attempt 4 of 5
11:57:45    Submission failed: Checksum failed for file.  Expected b6b1936e73c4fcda5459c4c3305718ad but got d41d8cd98f00b204e9800998ecf8427e.
11:57:45    Submit failed, waiting 3 seconds...
11:57:48    Retry submission: Attempt 5 of 5
11:58:35    Submission failed: Checksum failed for file.  Expected b6b1936e73c4fcda5459c4c3305718ad but got 4822ffa741a1777a465e8cfdd7764c97.
11:58:35    Uploaded: /home/jenkins/hansen/workspace/Trilinos-atdm-hansen-shiller-cuda-9.0-debug/SRC_AND_BUILD/BUILD/Testing/20181125-0400/Build.xml
11:58:35    Errors occurred during submission.
```

and of course failures to submit 'test' results in:

* https://jenkins-son.sandia.gov/view/Trilinos%20ATDM/job/Trilinos-atdm-hansen-shiller-gnu-debug-openmp/286/consoleFull

showing:

```
Submit files (using http)
   Send to track: ATDM
   Using HTTP submit method
   Drop site:http://testing-vm.sandia.gov/cdash/submit.php?project=Trilinos
   Submission failed: Checksum failed for file.  Expected 4a3869a85b2dacb9947d040b2c22673d but got f898f5520369486d65c0a4e5bf510f8b.
   Submit failed, waiting 3 seconds...
   Retry submission: Attempt 1 of 5
   Submission failed: Checksum failed for file.  Expected 4a3869a85b2dacb9947d040b2c22673d but got f6d6ed6443bb76d6f2ecdf8c9103c065.
   Submit failed, waiting 3 seconds...
   Retry submission: Attempt 2 of 5
   Submission failed: Checksum failed for file.  Expected 4a3869a85b2dacb9947d040b2c22673d but got bf51a2e520d51fc30a9a06459bbf88e9.
   Submit failed, waiting 3 seconds...
   Retry submission: Attempt 3 of 5
   Submission failed: Checksum failed for file.  Expected 4a3869a85b2dacb9947d040b2c22673d but got c8f2a8d360b11a165ebd854dd3676604.
   Submit failed, waiting 3 seconds...
   Retry submission: Attempt 4 of 5
   Submission failed: Checksum failed for file.  Expected 4a3869a85b2dacb9947d040b2c22673d but got a1292fc160823ef0142d7f01a960dd47.
   Submit failed, waiting 3 seconds...
   Retry submission: Attempt 5 of 5
   Submission failed: Checksum failed for file.  Expected 4a3869a85b2dacb9947d040b2c22673d but got 94252fe24f52c3dafae1f00fe671ad4c.
   Uploaded: /home/jenkins/hansen/workspace/Trilinos-atdm-hansen-shiller-gnu-debug-openmp/SRC_AND_BUILD/BUILD/Testing/20181125-0400/Test.xml
   Errors occurred during submission.
```

But this is not only impacting the ATDM Trilinos builds.  For example, if you look at the submits of the "Clean" builds since 11/01/2018 shown [here](https://testing.sandia.gov/cdash-dev-view/index.php?project=Trilinos&date=2018-11-25&filtercount=2&showfilters=1&filtercombine=and&field1=groupname&compare1=61&value1=Clean&field2=buildstarttime&compare2=83&value2=2018-11-01), you can see test results missing as far back as 11/16/2018 and more recently we see significant numbers of missing test results on 11/22/2108, 11/25/2018 and today on 11/26/2018.

**Comment by bartlettroscoe** [comment]
CC: @william76, @prwolfe, @fryeguy52 

@jwillenbring, at this point this looks to be a major impediment to the ATDM Trilinos stabilization and integration effort.  I am not sure what changed over the last couple of weeks but we are loosing about 1/3rd of our test results on many days.

**Comment by csiefer2** [comment]
@bartlettroscoe You can actually load the cdash tests results page?  That's a whole lot more than I'm getting...

**Comment by csiefer2** [comment]
Working now.

**Comment by bartlettroscoe** [comment]
@csiefer2 said:

> You can actually load the cdash tests results page? That's a whole lot more than I'm getting...

Chris, @fryeguy52 and myself have also noticed times today when we could not access the Trilinos CDash site.  I suspect that this is related to the CDash submit failures we have been seeing the last few days as reported in this Issue.

@trilinos/framework , I am worried that this might be a sign there is something wrong with the VM that is hosting the CDash site.  Or this might be something wrong with the network.  How can we debug this issue?

**Comment by jwillenbring** [comment]
@bartlettroscoe @csiefer2 

I am not sure what is going on here. I did log into the machine, and it is very low on memory. I am not sure why that is, or if it is the cause. I will report back when I know more.

**Comment by bartlettroscoe** [comment]
@trilinos/framework, @jwillenbring 

FYI: I just tried to go to:

* https://testing.sandia.gov/cdash-dev-view/index.php?project=Trilinos&date=2018-11-26

and I got the dreaded:

```
Error: CDash cannot connect to the database.
```

**Comment by jwillenbring** [comment]
@bartlettroscoe @trilinos/framework 

I was in the process of attempting to fix the issue at that time. Please try again. When the machine came back up, the memory situation was much better and then I had to clean up as previously instructed by @zackgalbreath.

I don't know for sure that this will fix it, but I would like to wait until tomorrow to see if things are better. The machine was definitely much faster logging me in after the reboot than before.

**Comment by bartlettroscoe** [comment]
CC: @trilinos/framework 

@jwillenbring, it looks like whatever was done yesterday did not resolve the problems.  As shown here:

* https://testing.sandia.gov/cdash-dev-view/index.php?project=Trilinos&date=2018-11-27&filtercount=1&showfilters=1&field1=buildname&compare1=65&value1=Trilinos-atdm-

we are still seeing significant numbers of missing configure, build, and test results on CDash.  Also, the Python script getting data from CDash being developed in #2933 just crashed when I tried to run it as it could not get data from CDash.

@fryeguy52, can you please see if we can submit to the SEMS SON CDash site as a secondary submit?  IF that site is still available, we can set up a new Trilinos CDash project there pretty fast (I can walk you through the process).

**Comment by bartlettroscoe** [comment]
FYI: Looks like the PR builds are suffering from loosing results as well as I just noticed at:

* https://testing-vm.sandia.gov/cdash/index.php?project=Trilinos&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=63&value1=PR-3935-test&field2=buildstarttime&compare2=84&value2=NOW

This shows cases of configure, build, and test results missing for various builds (i.e. when the "build time" is 0s, that means it did not submit build results).

**Comment by bartlettroscoe** [comment]
FYI: The new cee-rhel6 builds that run as a cron job on my CEE machine 'ceerws1113' has not had a single bit of lost data to CDash since 11/17/2018 as shown in [this query](https://testing.sandia.gov/cdash-dev-view/index.php?project=Trilinos&date=2018-11-28&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-cee-rhel6&field2=buildstarttime&compare2=83&value2=2018-11-15).  That makes me think this might be a problem with some of the subnets.

**Comment by jwillenbring** [comment]
@bartlettroscoe 

> The new cee-rhel6 builds that run as a cron job on my CEE machine 'ceerws1113' has not had a single bit of lost data to CDash since 11/17/2018 as shown in this query. That makes me think this might be a problem with some of the subnets.

That is a useful bit of information. I am not sure who the right person is to try to investigate that. @prwolfe do you know who could look at this?

**Comment by prwolfe** [comment]
@jwillenbring - I'm not sure who to ask on this, but I will talk to the few network guys I do know.  Digging I see that the PR builds seem fine since your reboot, the SON jobs are still intermittent.  

@bartlettroscoe - do you have any idea where the checksum failures are coming from? My suspicion in apache rather than CDash.

**Comment by bartlettroscoe** [comment]
> @bartlettroscoe - do you have any idea where the checksum failures are coming from? My suspicion in apache rather than CDash.

@prwolfe, I am not sure.  This is why we have Kitware contracts since this is their software.  From what @jwillenbring told me yesterday, hopefully we will have that contract back up and running again soon so they should be able to help us debug this.

**Comment by bartlettroscoe** [comment]
FYI: All of the missing build and test results for the ATDM Trilinos builds in the last week where not due to CDash submit failures.  It turns out that we are seeing crashing of the Jenkins jobs during building and running tests as described in, for example:

* https://sems-atlassian-son.sandia.gov/jira/browse/TRIL-237

It does not look like any of missing ATDM Trilinos build results on testing day 2018-12-02 shown [here](https://testing.sandia.gov/cdash-dev-view/index.php?project=Trilinos&date=2018-12-02&filtercount=1&showfilters=1&field1=buildname&compare1=65&value1=Trilinos-atdm-) was a result of submit failures.

From what I am looking at on jenkins-srn.sandia.gov right now, it seems something changed in Trilinos or on the jenkins-srn.sandia.gov slaves between 11/27/2018 and 11/28/2018 to case these jenkins-srn.sandia.gov jobs to start crashing.  I am investigating all of this right now ...

**Comment by bartlettroscoe** [comment]
FYI: Since we moved the start of the various ATDM Trilinos builds run from jenkins-srn.sandia.gov to start a different times (see [TRIL-237](https://sems-atlassian-son.sandia.gov/jira/browse/TRIL-237)) for the first time yesterday we got a full set of build and test results as shown [here]().

Therefore, I put this "in review" will leave this over the XMAS break to see if we see any other instances where we could not post CDash results.

**Comment by bartlettroscoe** [comment]
FYI: The major failures submitting to CDash are mostly gone.  It looks like there still are some problems but we have other issues to address these:

* https://sems-atlassian-son.sandia.gov/jira/browse/TRIL-237: Investigate jenkins-srn.sandia.gov build crashes (still may be seeing a few of these every so often)
* https://gitlab.kitware.com/snl/project-1/issues/79: Investigate why submitted ctest XML file did not get inserted into MySQL DB

Therefore, some the major problems have been resolved, I will close this issue.
