### ISSUE TITLE
Framework: CDash interprets failed shared library load as a "not run" rather than as a fail

### ISSUE THREAD

**Issue by csiefer2** [trilinos/Trilinos#3934]
@trilinos/framework @trilinos/muelu 

As I discovered from our testing, if a program cannot find a shared library at run time (and the test fails to run), cdash reports that as a "Not Run" which has no useful screen output.  This case really ought to be a run failure, so we can see the effect of the failed library load.

See:
https://testing.sandia.gov/cdash/index.php?project=Trilinos&parentid=4215058

**Comment by csiefer2** [comment]
Things are actually worse than that.  This is a "files are not building and cdash reports them as building successfully.  The "not run" is a bit of a red herring.

**Comment by jwillenbring** [comment]
@csiefer2 @bartlettroscoe 

Maybe @bartlettroscoe can correct me if I am wrong, but I seem to think that this was called a "not run" because most often there is a compile/link error when building the executable, so flagging a test failure would be flagging the same failure twice.

**Comment by bartlettroscoe** [comment]
@csiefer2, can you point to a specific "Not Run" test example on CDash?

**Comment by bartlettroscoe** [comment]
> Maybe @bartlettroscoe can correct me if I am wrong, but I seem to think that this was called a "not run" because most often there is a compile/link error when building the executable, so flagging a test failure would be flagging the same failure twice.

@jwillenbring, the build at:

* https://testing.sandia.gov/cdash/index.php?project=Trilinos&parentid=4215058

does not show any build failures.

**Comment by jwillenbring** [comment]
@bartlettroscoe 

>the build at:
https://testing.sandia.gov/cdash/index.php?project=Trilinos&parentid=4215058
does not show any build failures.

I apologize for not being more clear. I was just trying to verify that this was the rationale used for not calling a missing executable a test failure. If so, that was not a valid assumption, but I am still hesitant to double flag issues in the other situation.

**Comment by csiefer2** [comment]
It turns out that that particular guy never actually built, and did not run because the executable wasn't there.  However the build reported as OK.

**Comment by bartlettroscoe** [comment]
> It turns out that that particular guy never actually built, and did not run because the executable wasn't there. However the build reported as OK.

@csiefer2, I think I have seen that happen before with the ATDM Trilinos builds.

@jwillenbring, we need to alert Kitware about this and see if they can explain why CDash did not report a build failure.
