### ISSUE TITLE
MueLu_ENABLE_Kokkos_Refactor_Use_By_Default=ON by default for CUDA builds

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#3941]
@trilinos/muelu 

CC: @bathmatt, @jmgate, @jhux2, @fryeguy52 

It was reported by EMPIRE developers (i.e. @bathmatt) that the option `HAVE_MUELU_KOKKOS_REFACTOR_USE_BY_DEFAULT` is getting set to `OFF` by default for CUDA builds where it was seemed to be getting set to `ON` by default as verified in https://github.com/trilinos/Trilinos/issues/2674#issuecomment-433185731 on 10/25/2018.

However, looking at a recent CUDA for `Trilinos-atdm-white-ride-cuda-9.2-debug` for example shown [here](https://testing.sandia.gov/cdash-dev-view/viewNotes.php?buildid=4220171#!#note1) today we see:

```
MueLu_ENABLE_Kokkos_Refactor:BOOL=ON
MueLu_ENABLE_Kokkos_Refactor_Use_By_Default:BOOL=NO
...
Xpetra_ENABLE_Kokkos_Refactor:BOOL=ON
```

But I am also seeing:

```
HAVE_MUELU_KOKKOS_REFACTOR:INTERNAL=ON
HAVE_MUELU_KOKKOS_REFACTOR_USE_BY_DEFAULT:INTERNAL=OFF
...
HAVE_XPETRA_KOKKOS_REFACTOR:INTERNAL=ON
```

@jhux2, how is it possible for `MueLu_ENABLE_Kokkos_Refactor_Use_By_Default` to be different than `HAVE_MUELU_KOKKOS_REFACTOR_USE_BY_DEFAULT`?

**Comment by bartlettroscoe** [comment]
@trilinos/muelu,

The following CMake code is in `Trilinos/packages/muelu/CMakeLists.txt`:

```
# default. This is useful for running all non-unit tests with Kokkos
# without having to set "use kokkos refactor" in all parameter lists.
TRIBITS_ADD_OPTION_AND_DEFINE(
  ${PACKAGE_NAME}_ENABLE_Kokkos_Refactor_Use_By_Default
  HAVE_${PACKAGE_NAME_UC}_KOKKOS_REFACTOR_USE_BY_DEFAULT
  "Use MueLu code refactored to use Kokkos by default."
  NO)
```

Should this not be:

```
# default. This is useful for running all non-unit tests with Kokkos
# without having to set "use kokkos refactor" in all parameter lists.
TRIBITS_ADD_OPTION_AND_DEFINE(
  ${PACKAGE_NAME}_ENABLE_Kokkos_Refactor_Use_By_Default
  HAVE_${PACKAGE_NAME_UC}_KOKKOS_REFACTOR_USE_BY_DEFAULT
  "Use MueLu code refactored to use Kokkos by default."
  ${Kokkos_Refactor_On_By_Default})
```

?

But I don't understand how we could have `MueLu_ENABLE_Kokkos_Refactor_Use_By_Default:BOOL=NO` and `HAVE_MUELU_KOKKOS_REFACTOR_USE_BY_DEFAULT:INTERNAL=OFF` in the cache at the same time.

**Comment by jmgate** [comment]
I'm not terribly fond of CMake's `ON == YES` and `OFF == NO` business.  Makes a typo like `NO` when you meant `ON` a real pain.  Can we stick to `ON` and `OFF`?  That's seems to be accepted practice throughout most of Trilinos.

**Comment by bartlettroscoe** [comment]
> I'm not terribly fond of CMake's `ON == YES` and `OFF == NO` business.  Makes a typo like `NO` when you meant `ON` a real pain.  Can we stick to `ON` and `OFF`?  That's seems to be accepted practice throughout most of Trilinos.

Agreed.  We should stick with `ON` / `OFF` AND `TRUE` / `FALSE` (and use those pairs).  Using `yes` / `no` or `YES` / `NO` is kind of dumb.

**Comment by bartlettroscoe** [comment]
> However, the Kokkos code path is not run unless either it's specified in the input deck or the above cmake option is ON.

@jhux2, does this mean that the Kokkos path is not enabled in any automated Trilinos tests unless you explicitly configure with:

```
-D MueLu_ENABLE_Kokkos_Refactor_Use_By_Default:BOOL=YES
```

?

**Comment by bartlettroscoe** [comment]
@cgcgcg said:

> @bartlettroscoe Kokkos is enabled in unit tests. The parameter decides whether or not we are building Kokkos factories at runtime when the user does not specify exactly what is required. This is for example the case in the non-unit tests, where we test the default behavior.

Why is that the behavior for CUDA builds?  Does that mean that for CUDA builds, by default, you don't run on the GPU?

**Comment by cgcgcg** [comment]
If you want all tests to run on the GPU, you need to set the default to 
```
-D MueLu_ENABLE_Kokkos_Refactor_Use_By_Default:BOOL=TRUE
```
as pointed out by @jhux2.

**Comment by bartlettroscoe** [comment]
CC: @bathmatt, @jmgate, @rppawlo, @srajama1 

@cgcgcg and @jhux2, I was addressing this more for the user's perspective.  Why would the user not want to run on the GPU by default when they are doing a CUDA build?  Is that not the entire point of a CUDA build?  Should then the default behavior be for MueLu not be changed to set `MueLu_ENABLE_Kokkos_Refactor_Use_By_Default:BOOL=TRUE` by default for CUDA builds and then require users to turn that off if they don't want to use the Kokkos implementation by default for CUDA builds?  And, by having `MueLu_ENABLE_Kokkos_Refactor_Use_By_Default:BOOL=FALSE` are a lot of the tests in Trilinos not using the Kokkos GPU implementation when we do a CUDA build?  Does that seems reasonable?  This is what tripped up EMPIRE (and confused me) as described above.

And I never got an answer to [above](https://github.com/trilinos/Trilinos/issues/3941#issue-384995000) which was:

* @jhux2, how is it possible for `MueLu_ENABLE_Kokkos_Refactor_Use_By_Default` to be different than `HAVE_MUELU_KOKKOS_REFACTOR_USE_BY_DEFAULT`?

That is what we are seeing.  How is that possible?

In any case, I can set `MueLu_ENABLE_Kokkos_Refactor_Use_By_Default:BOOL=TRUE`  for CUDA builds in the [ATDM Trilinos configuration settings](https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md)  but now we run the risk of getting a bunch of failing tests on the various platforms with the CUDA builds.

**Comment by lucbv** [comment]
@bartlettroscoe the major reason for
```
MueLu_ENABLE_Kokkos_Refactor_Use_By_Default:BOOL=NO
...
HAVE_MUELU_KOKKOS_REFACTOR_USE_BY_DEFAULT:INTERNAL=OFF
```
is backward compatibility. If you run naively your old xml input decks with `MueLu_ENABLE_Kokkos_Refactor_Use_By_Default:BOOL=ON` you most likely will run into trouble calling a mix of refactored and non-refactored factories.
My guess is any app that has tests setup to run MueLu will break instantly if we made turned on the refactor...

**Comment by bartlettroscoe** [comment]
CC: @bathmatt, @jmgate, @srajama1 

@lucbv, @cgcgcg, and @jhux2,

Okay, I understand the desire to support backward compatibility for other customers that have CUDA builds but are not actually running on the GPU currently with MueLu.  (Not sure why they would want to keep doing that but okay.)

EMPIRE has just changed (read that **diverged**) their Trilinos configuration from out tested ATDM Trilinos confiugration to set  `MueLu_ENABLE_Kokkos_Refactor_Use_By_Default:BOOL=ON`.  Therefore, we need to update the ATDM Trilinos CUDA configuration to exactly match that.  But If we turn on this option, are we going to see several new failures in downstream package test suites (e.g. Panzer)?  If that happens, can MueLu developers help to fix the failures quickly?  (People don't like to see lots of red on the CDash site.)

**Comment by bartlettroscoe** [comment]
> I suggest we demote these builds, change the MueLU option, fix any failures, promote the builds again.

@srajama1, we could do that, but this might include the really critical builds `Trilinos-atdm-waterman-cuda-9.2-xxx` which are the closest thing we have to ATS-2.  I worry if we demote builds from "ATDM" to "Specialized" that the issues for those builds will get ignored.

**Comment by srajama1** [comment]
@bartlettroscoe The trilinos product leads will make sure these don't get ignored, especially for this critical build that just got demoted. Another option start a new specialized build with MueLU option changed and promote that. I worry the second case will probably get a lower priority as there is a build passing :). I am fine with both options.

**Comment by bartlettroscoe** [comment]
>  The trilinos product leads will make sure these don't get ignored, especially for this critical build that just got demoted. Another option start a new specialized build with MueLU option changed and promote that. I worry the second case will probably get a lower priority as there is a build passing :). I am fine with both options.

@srajama1, we need to determine what are reasonable conditions for when we should demote and when we should not.

**Comment by bartlettroscoe** [comment]
@rppawlo, @bathmatt, and @jhux2,

Do we want to set `MueLu_ENABLE_Kokkos_Refactor_Use_By_Default=ON ` for just CUDA ATDM Trilinos builds or also for OpenMP builds?

**Comment by rppawlo** [comment]
If kokkos is enabled, I would like to see that on for all such builds.

**Comment by bartlettroscoe** [comment]
> If kokkos is enabled, I would like to see that on for all such builds.

@rppawlo, I think the current logic in `Trilinos/packages/muelu/CMakeLists.txt` is to only compile in support for the Kokkos implementation for OpenMP and CUDA builds.  See:

* https://github.com/trilinos/Trilinos/blob/develop/packages/muelu/CMakeLists.txt#L182
* https://github.com/trilinos/Trilinos/blob/develop/packages/muelu/CMakeLists.txt#L189

There is no Kokkos support compiled in by default for (nonthreaded) Serial builds.  We would have to explicitly add the configure options:

* `Xpetra_ENABLE_Kokkos_Refactor=ON`
* `MueLu_ENABLE_Kokkos_Refactor=ON`
* `MueLu_ENABLE_Kokkos_Refactor_Use_By_Default=ON`

for **all** ATDM Trilinos builds.

Is that what we want to do?

NOTE: The Trilinos PR builds are currently **not** turning these options on by default.  Should we push that they enable these for all Trilinos PR builds?  Otherwise, I don't know that we should enable these for ATDM Trilinos builds (except for CUDA builds).

What says everyone?

**Comment by jhux2** [comment]
> If kokkos is enabled, I would like to see that on for all such builds.

@rppawlo Do you include Serial node in this set?   I'd certainly want MueLu's kokkos code path on and tested for both CUDA and OpenMP.  Kokkos won't help MueLu in serial.

**Comment by rppawlo** [comment]
Serial really doesn't matter from an atdm standpoint, except for occasionally falling back on it in debugging to check for race conditions. I was more thinking that if you do plan to deprecate the non-kokkos path, there are still users who will want serial builds of trilinos so it might be good to be testing the kokkos path with a serial node build as well.

**Comment by rppawlo** [comment]
Just keying off kokkos being enabled would also simplify the cmake logic rather than checking node types too.

**Comment by bartlettroscoe** [comment]
@rppawlo said:

> Just keying off kokkos being enabled would also simplify the cmake logic rather than checking node types too.

@jhux2, how about that?  If 'kokkos' is enabled then compile in support for the Kokkos implementation in MueLu by default, even if this is a serial Kokkos node?   Why not?

**Comment by jhux2** [comment]
@bartlettroscoe PR is submitted to check whether Kokkos is enabled.  If it is, then MueLu's Kokkos-refactor code path is enabled for *compilation*.

**Comment by bartlettroscoe** [comment]
> @bartlettroscoe PR #4044 is submitted to check whether Kokkos is enabled. If it is, then MueLu's Kokkos-refactor code path is enabled for compilation.

@jhux2, sounds good to me.  Also, this sounds like what @rppawlo.  I understand that we will need to set `MueLu_ENABLE_Kokkos_Refactor_Use_By_Default=ON` manually ourselves.  After PR #4044 is merged, I will create a branch and PR that does that for the ATDM Trilinos builds and then I will run some experimental builds on several platforms.

Since this is not really a "bug" but a misunderstanding, I will remove the "bug" label and put on "enhancement".

**Comment by bartlettroscoe** [comment]
FYI: I added this to our out [WIP backlog](https://snl-wiki.sandia.gov/pages/viewpage.action?pageId=341516978).

**Comment by bartlettroscoe** [comment]
This has been done for a long time and both EMPIRE and SPARC have had several updates of Trilinos since then.  If there was a problem related this, I would have heard about it.

Closing as complete.
