### ISSUE TITLE
Randomly failing Sacado tests on ATDM KNL mutrino build

### ISSUE THREAD

**Issue by fryeguy52** [trilinos/Trilinos#3942]
CC: @trilinos/sacado, @rppawlo (Trilinos Nonlinear Solvers Product Lead), @bartlettroscoe, @fryeguy52
 
<Checklist>
<???: Once GitHub Issue is created, add entries for tests to TrilinosATDMStatus/*.csv files>
 
## Next Action Status
Waiting for https://sems-atlassian-son.sandia.gov/jira/browse/TRIL-219 to be addressed. This seems to be an environment issue with slurm.
 
## Description
 
As shown in [this query](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-mutrino-intel-opt-openmp-KNL&field2=testname&compare2=65&value2=Sacado_&field3=site&compare3=61&value3=mutrino&field4=details&compare4=61&value4=Completed%20%28Timeout%29&field5=buildstarttime&compare5=83&value5=2018-11-01) the tests:
* Sacado_FadKokkosTests_Serial_MPI_1
* Sacado_FadSerializationTests_MPI_1
* Sacado_TaySerializationTests_MPI_1

are failing in the build:
* Trilinos-atdm-mutrino-intel-opt-openmp-KNL

each of these tests have timed out more than once in the last month and this appears to be random.  Here are links to each test's history going back to 2018-10-01:

[Sacado_FadKokkosTests_Serial_MPI_1](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-mutrino-intel-opt-openmp-KNL&field2=testname&compare2=61&value2=Sacado_FadKokkosTests_Serial_MPI_1&field3=buildstarttime&compare3=83&value3=2018-10-01)
[Sacado_FadSerializationTests_MPI_1](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-mutrino-intel-opt-openmp-KNL&field2=testname&compare2=61&value2=Sacado_FadSerializationTests_MPI_1&field3=buildstarttime&compare3=83&value3=2018-10-01)
[Sacado_TaySerializationTests_MPI_1](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-mutrino-intel-opt-openmp-KNL&field2=testname&compare2=61&value2=Sacado_TaySerializationTests_MPI_1&field3=buildstarttime&compare3=83&value3=2018-10-01)

## Current Status on CDash

The current status of the Sacado tests for this build for the current testing day can be found [here](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-mutrino-intel-opt-openmp-KNL&field2=testname&compare2=65&value2=Sacado_)

## Steps to Reproduce

Because these failures are appear to be random it may be difficult to reproduce the failures.  One should be able to reproduce the identical build as described in:
* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md

More specifically, the commands given for mutrino are provided at:
* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#mutrino

The exact commands to reproduce this issue should be:
```
$ cd <some_build_dir>/
$ source $TRILINOS_DIR/cmake/std/atdm/load-env.sh Trilinos-atdm-mutrino-intel-opt-openmp-KNL
$ cmake \
 -GNinja \
 -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
 -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_Sacado=ON \
 $TRILINOS_DIR
$ make NP=16
$ salloc -N 1 -p standard -J $ATDM_CONFIG_JOB_NAME ctest -j16
```

**Comment by rppawlo** [comment]
@etphipp

**Comment by etphipp** [comment]
If you look at the test output, they all have output similar to this:
```
srun: Job 13276448 step creation temporarily disabled, retrying
```
and this is the only output.  A successful test output looks something like this:
```
srun: Job 11971935 step creation temporarily disabled, retrying
srun: Step created for job 11971935
Teuchos::GlobalMPISession::GlobalMPISession(): started processor with name nid00261 and rank 0!

***
*** Unit test suite ...
***


Sorting tests by group name then by the order they were added ... (time = 0.0213)

Running unit tests ...

0. CacheFad_DFad_Serialization_FadUniform_UnitTest ... [Passed] (0.271 sec)
1. CacheFad_DFad_Serialization_FadEmpty_UnitTest ... [Passed] (0.00486 sec)
2. CacheFad_DFad_Serialization_FadMixed_UnitTest ... [Passed] (0.000414 sec)
3. CacheFad_DFad_Serialization_FadFadUniform_UnitTest ... [Passed] (0.0889 sec)
4. CacheFad_DFad_Serialization_FadFadEmptyInner_UnitTest ... [Passed] (0.0054 sec)
5. CacheFad_DFad_Serialization_FadFadEmptyOuter_UnitTest ... [Passed] (0.00606 sec)
6. CacheFad_DFad_Serialization_FadFadEmptyAll_UnitTest ... [Passed] (0.00578 sec)
7. CacheFad_SFad_Serialization_FadUniform_UnitTest ... [Passed] (0.0339 sec)
8. CacheFad_SFad_Serialization_FadFadUniform_UnitTest ... [Passed] (0.00724 sec)
9. CacheFad_SLFad_Serialization_FadUniform_UnitTest ... [Passed] (0.0101 sec)
10. CacheFad_SLFad_Serialization_FadEmpty_UnitTest ... [Passed] (0.000288 sec)
11. CacheFad_SLFad_Serialization_FadMixed_UnitTest ... [Passed] (0.0056 sec)
12. CacheFad_SLFad_Serialization_FadFadUniform_UnitTest ... [Passed] (0.00602 sec)
13. CacheFad_SLFad_Serialization_FadFadEmptyInner_UnitTest ... [Passed] (0.00546 sec)
14. CacheFad_SLFad_Serialization_FadFadEmptyOuter_UnitTest ... [Passed] (0.00608 sec)
15. CacheFad_SLFad_Serialization_FadFadEmptyAll_UnitTest ... [Passed] (0.00562 sec)
16. ELRCacheFad_DFad_Serialization_FadUniform_UnitTest ... [Passed] (0.0503 sec)
17. ELRCacheFad_DFad_Serialization_FadEmpty_UnitTest ... [Passed] (0.00496 sec)
18. ELRCacheFad_DFad_Serialization_FadMixed_UnitTest ... [Passed] (0.000413 sec)
19. ELRCacheFad_DFad_Serialization_FadFadUniform_UnitTest ... [Passed] (0.0219 sec)
20. ELRCacheFad_DFad_Serialization_FadFadEmptyInner_UnitTest ... [Passed] (0.00533 sec)
21. ELRCacheFad_DFad_Serialization_FadFadEmptyOuter_UnitTest ... [Passed] (0.006 sec)
22. ELRCacheFad_DFad_Serialization_FadFadEmptyAll_UnitTest ... [Passed] (0.000996 sec)
23. ELRCacheFad_SFad_Serialization_FadUniform_UnitTest ... [Passed] (0.00483 sec)
24. ELRCacheFad_SFad_Serialization_FadFadUniform_UnitTest ... [Passed] (0.0022 sec)
25. ELRCacheFad_SLFad_Serialization_FadUniform_UnitTest ... [Passed] (0.00997 sec)
26. ELRCacheFad_SLFad_Serialization_FadEmpty_UnitTest ... [Passed] (0.000255 sec)
27. ELRCacheFad_SLFad_Serialization_FadMixed_UnitTest ... [Passed] (0.00448 sec)
28. ELRCacheFad_SLFad_Serialization_FadFadUniform_UnitTest ... [Passed] (0.00638 sec)
29. ELRCacheFad_SLFad_Serialization_FadFadEmptyInner_UnitTest ... [Passed] (0.00517 sec)
30. ELRCacheFad_SLFad_Serialization_FadFadEmptyOuter_UnitTest ... [Passed] (0.00587 sec)
31. ELRCacheFad_SLFad_Serialization_FadFadEmptyAll_UnitTest ... [Passed] (0.000996 sec)
32. ELRFad_DFad_Serialization_FadUniform_UnitTest ... [Passed] (0.0293 sec)
33. ELRFad_DFad_Serialization_FadEmpty_UnitTest ... [Passed] (0.000262 sec)
34. ELRFad_DFad_Serialization_FadMixed_UnitTest ... [Passed] (0.00485 sec)
35. ELRFad_DFad_Serialization_FadFadUniform_UnitTest ... [Passed] (0.0303 sec)
36. ELRFad_DFad_Serialization_FadFadEmptyInner_UnitTest ... [Passed] (0.00514 sec)
37. ELRFad_DFad_Serialization_FadFadEmptyOuter_UnitTest ... [Passed] (0.00626 sec)
38. ELRFad_DFad_Serialization_FadFadEmptyAll_UnitTest ... [Passed] (0.000991 sec)
39. ELRFad_SFad_Serialization_FadUniform_UnitTest ... [Passed] (0.00986 sec)
40. ELRFad_SFad_Serialization_FadFadUniform_UnitTest ... [Passed] (0.00228 sec)
41. ELRFad_SLFad_Serialization_FadUniform_UnitTest ... [Passed] (0.0098 sec)
42. ELRFad_SLFad_Serialization_FadEmpty_UnitTest ... [Passed] (0.000301 sec)
43. ELRFad_SLFad_Serialization_FadMixed_UnitTest ... [Passed] (0.00558 sec)
44. ELRFad_SLFad_Serialization_FadFadUniform_UnitTest ... [Passed] (0.00625 sec)
45. ELRFad_SLFad_Serialization_FadFadEmptyInner_UnitTest ... [Passed] (0.00628 sec)
46. ELRFad_SLFad_Serialization_FadFadEmptyOuter_UnitTest ... [Passed] (0.00624 sec)
47. ELRFad_SLFad_Serialization_FadFadEmptyAll_UnitTest ... [Passed] (0.000946 sec)
48. Fad_DFad_Serialization_FadUniform_UnitTest ... [Passed] (0.025 sec)
49. Fad_DFad_Serialization_FadEmpty_UnitTest ... [Passed] (0.000255 sec)
50. Fad_DFad_Serialization_FadMixed_UnitTest ... [Passed] (0.00469 sec)
51. Fad_DFad_Serialization_FadFadUniform_UnitTest ... [Passed] (0.0154 sec)
52. Fad_DFad_Serialization_FadFadEmptyInner_UnitTest ... [Passed] (0.00567 sec)
53. Fad_DFad_Serialization_FadFadEmptyOuter_UnitTest ... [Passed] (0.00124 sec)
54. Fad_DFad_Serialization_FadFadEmptyAll_UnitTest ... [Passed] (0.00099 sec)
55. Fad_DMFad_Serialization_FadUniform_UnitTest ... [Passed] (0.00557 sec)
56. Fad_DMFad_Serialization_FadEmpty_UnitTest ... [Passed] (0.000252 sec)
57. Fad_DMFad_Serialization_FadMixed_UnitTest ... [Passed] (0.0149 sec)
58. Fad_DMFad_Serialization_FadFadUniform_UnitTest ... [Passed] (0.00678 sec)
59. Fad_DMFad_Serialization_FadFadEmptyInner_UnitTest ... [Passed] (0.00543 sec)
60. Fad_DMFad_Serialization_FadFadEmptyOuter_UnitTest ... [Passed] (0.0461 sec)
61. Fad_DMFad_Serialization_FadFadEmptyAll_UnitTest ... [Passed] (0.000956 sec)
62. Fad_SFad_Serialization_FadUniform_UnitTest ... [Passed] (0.005 sec)
63. Fad_SFad_Serialization_FadFadUniform_UnitTest ... [Passed] (0.0022 sec)
64. Fad_SLFad_Serialization_FadUniform_UnitTest ... [Passed] (0.00475 sec)
65. Fad_SLFad_Serialization_FadEmpty_UnitTest ... [Passed] (0.000328 sec)
66. Fad_SLFad_Serialization_FadMixed_UnitTest ... [Passed] (0.00568 sec)
67. Fad_SLFad_Serialization_FadFadUniform_UnitTest ... [Passed] (0.00605 sec)
68. Fad_SLFad_Serialization_FadFadEmptyInner_UnitTest ... [Passed] (0.00519 sec)
69. Fad_SLFad_Serialization_FadFadEmptyOuter_UnitTest ... [Passed] (0.00627 sec)
70. Fad_SLFad_Serialization_FadFadEmptyAll_UnitTest ... [Passed] (0.000991 sec)

Total Time: 0.972 sec

Summary: total = 71, run = 71, passed = 71, failed = 0

End Result: TEST PASSED
```
It looks to me that the tests never actually start and it is hanging somewhere while launching the job.  I don't see what I can do about this.

**Comment by etphipp** [comment]
After googling what a slurm "step" is (see, e.g., [here](https://stackoverflow.com/questions/46506784/how-do-the-terms-job-task-and-step-relate-to-each-other)) it is clear slurm is hanging somewhere while launching the job, and that the test is never executed.  This looks to be an environment or slurm issue and I don't see how it is related to these tests.

**Comment by bartlettroscoe** [comment]
> This looks to be an environment or slurm issue and I don't see how it is related to these tests.

@etphipp, it is hard to compute statistics (because it requires inspecting the test output) but it seems that these Sacado tests showed this random timeout showing `srun: Job <jobid> step creation temporarily disabled, retrying` and that is all.  For example, if you look at all of the Sacado timeouts for this build since 10/1/2018 in [this query](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=7&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-mutrino-intel-opt-openmp-KNL&field2=testname&compare2=65&value2=Sacado_&field3=buildstarttime&compare3=82&value3=2018-11-24T07%3A21%3A43%20UTC&field4=status&compare4=62&value4=passed&field5=status&compare5=62&value5=notrun&field6=details&compare6=63&value6=Timeout&field7=buildstarttime&compare7=83&value7=2018-10-01), you see 18 such instances (but I did not look at all 18 of them).  

If you look at all of the timeouts in that build from 10/01/2018 till now in [this query](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=6&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-mutrino-intel-opt-openmp-KNL&field2=buildstarttime&compare2=82&value2=2018-11-24T07%3A21%3A43%20UTC&field3=status&compare3=62&value3=passed&field4=status&compare4=62&value4=notrun&field5=details&compare5=63&value5=Timeout&field6=buildstarttime&compare6=83&value6=2018-10-01) you see that out of the 169 tests that timed out over that time that only 4 of them were not Sacado or KokkosKernels tests! 

I think that is pretty strong evidence that this behavior of printing `srun: Job <jobid> step creation temporarily disabled, retrying` and then hanging and timing out likely **is** correlated with the tests being run.  Can you think of another explanation?

**Comment by bartlettroscoe** [comment]
@etphipp, out configuration for this KNL machine is terrible.  See [TRIL-219](https://sems-atlassian-son.sandia.gov/jira/browse/TRIL-219).  It may very well be that our terrible KNL settings may be the cause of this behavior.  Therefore, I will add the "ATDM Env Issue" label since this is a strong possibility.

**Comment by etphipp** [comment]
My interpretation of this is that since there is no line like:
```
srun: Step created for job 11971935
```
slurm never created the "step", which has to happen before the test runs.  Also, there is no MPI initialization info printed, which happens when the test first starts.

**Comment by bartlettroscoe** [comment]
@etphipp, you could be correct.  But since almost all of these instances seem to be manifested in Sacado and KokkosKernels tests, it would be good to understand why that is the case.

For now, I would not bother doing anything on this.  I think we need to revisit the settings for the KNL build on this machine as part of https://sems-atlassian-son.sandia.gov/jira/browse/TRIL-219.  Creating this GitHub Issue just creates visibility for this issue and allows us to track this as part of our Python analysis script being developed as part of #2933.

**Comment by fryeguy52** [comment]
I am closing this because these have been passing for a while now:

---

<table style="width:100%" boarder="1">

<tr>
<th>Site</th>
<th>Build Name</th>
<th>Test Name</th>
<th>Status</th>
<th>Details</th>
<th>Consec&shy;utive Pass Days</th>
<th>Non-pass Last 30 Days</th>
<th>Pass Last 30 Days</th>
<th>Issue Tracker</th>
</tr>

<tr>
<td align="left">mutrino</td>
<td align="left"><a href="https://testing.sandia.gov/cdash/index.php?project=Trilinos&filtercombine=and&filtercombine=&filtercount=4&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-mutrino-intel-opt-openmp-KNL&field2=site&compare2=61&value2=mutrino&field3=buildstarttime&compare3=84&value3=2019-04-02T00:00:00&field4=buildstarttime&compare4=83&value4=2019-03-03T00:00:00">Trilinos-atdm-mutrino-intel-opt-openmp-KNL</a></td>
<td align="left"><a href="https://testing.sandia.gov/cdash/testDetails.php?test=73129524&build=4815652">Sacado_&shy;FadKokkosTests_&shy;Serial_&shy;MPI_&shy;1</a></td>
<td align="left"><a href="https://testing.sandia.gov/cdash/testDetails.php?test=73129524&build=4815652"><font color="green">Passed</font></a></td>
<td align="left">Completed</td>
<td align="right"><a href="https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-mutrino-intel-opt-openmp-KNL&field2=testname&compare2=61&value2=Sacado_FadKokkosTests_Serial_MPI_1&field3=site&compare3=61&value3=mutrino&field4=buildstarttime&compare4=84&value4=2019-04-02T00:00:00&field5=buildstarttime&compare5=83&value5=2019-03-03T00:00:00"><font color="green">25</font></a></td>
<td align="right"><a href="https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-mutrino-intel-opt-openmp-KNL&field2=testname&compare2=61&value2=Sacado_FadKokkosTests_Serial_MPI_1&field3=site&compare3=61&value3=mutrino&field4=buildstarttime&compare4=84&value4=2019-04-02T00:00:00&field5=buildstarttime&compare5=83&value5=2019-03-03T00:00:00"><font color="red">0</font></a></td>
<td align="right"><a href="https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-mutrino-intel-opt-openmp-KNL&field2=testname&compare2=61&value2=Sacado_FadKokkosTests_Serial_MPI_1&field3=site&compare3=61&value3=mutrino&field4=buildstarttime&compare4=84&value4=2019-04-02T00:00:00&field5=buildstarttime&compare5=83&value5=2019-03-03T00:00:00"><font color="green">25</font></a></td>
<td align="right"><a href="https://github.com/trilinos/Trilinos/issues/3942">#3863</a></td>
</tr>

<tr>
<td align="left">mutrino</td>
<td align="left"><a href="https://testing.sandia.gov/cdash/index.php?project=Trilinos&filtercombine=and&filtercombine=&filtercount=4&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-mutrino-intel-opt-openmp-KNL&field2=site&compare2=61&value2=mutrino&field3=buildstarttime&compare3=84&value3=2019-04-02T00:00:00&field4=buildstarttime&compare4=83&value4=2019-03-03T00:00:00">Trilinos-atdm-mutrino-intel-opt-openmp-KNL</a></td>
<td align="left"><a href="https://testing.sandia.gov/cdash/testDetails.php?test=73129523&build=4815652">Sacado_&shy;FadSerializationTests_&shy;MPI_&shy;1</a></td>
<td align="left"><a href="https://testing.sandia.gov/cdash/testDetails.php?test=73129523&build=4815652"><font color="green">Passed</font></a></td>
<td align="left">Completed</td>
<td align="right"><a href="https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-mutrino-intel-opt-openmp-KNL&field2=testname&compare2=61&value2=Sacado_FadSerializationTests_MPI_1&field3=site&compare3=61&value3=mutrino&field4=buildstarttime&compare4=84&value4=2019-04-02T00:00:00&field5=buildstarttime&compare5=83&value5=2019-03-03T00:00:00"><font color="green">25</font></a></td>
<td align="right"><a href="https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-mutrino-intel-opt-openmp-KNL&field2=testname&compare2=61&value2=Sacado_FadSerializationTests_MPI_1&field3=site&compare3=61&value3=mutrino&field4=buildstarttime&compare4=84&value4=2019-04-02T00:00:00&field5=buildstarttime&compare5=83&value5=2019-03-03T00:00:00"><font color="red">0</font></a></td>
<td align="right"><a href="https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-mutrino-intel-opt-openmp-KNL&field2=testname&compare2=61&value2=Sacado_FadSerializationTests_MPI_1&field3=site&compare3=61&value3=mutrino&field4=buildstarttime&compare4=84&value4=2019-04-02T00:00:00&field5=buildstarttime&compare5=83&value5=2019-03-03T00:00:00"><font color="green">25</font></a></td>
<td align="right"><a href="https://github.com/trilinos/Trilinos/issues/3942">#3863</a></td>
</tr>

<tr>
<td align="left">mutrino</td>
<td align="left"><a href="https://testing.sandia.gov/cdash/index.php?project=Trilinos&filtercombine=and&filtercombine=&filtercount=4&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-mutrino-intel-opt-openmp-KNL&field2=site&compare2=61&value2=mutrino&field3=buildstarttime&compare3=84&value3=2019-04-02T00:00:00&field4=buildstarttime&compare4=83&value4=2019-03-03T00:00:00">Trilinos-atdm-mutrino-intel-opt-openmp-KNL</a></td>
<td align="left"><a href="https://testing.sandia.gov/cdash/testDetails.php?test=73129522&build=4815652">Sacado_&shy;TaySerializationTests_&shy;MPI_&shy;1</a></td>
<td align="left"><a href="https://testing.sandia.gov/cdash/testDetails.php?test=73129522&build=4815652"><font color="green">Passed</font></a></td>
<td align="left">Completed</td>
<td align="right"><a href="https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-mutrino-intel-opt-openmp-KNL&field2=testname&compare2=61&value2=Sacado_TaySerializationTests_MPI_1&field3=site&compare3=61&value3=mutrino&field4=buildstarttime&compare4=84&value4=2019-04-02T00:00:00&field5=buildstarttime&compare5=83&value5=2019-03-03T00:00:00"><font color="green">25</font></a></td>
<td align="right"><a href="https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-mutrino-intel-opt-openmp-KNL&field2=testname&compare2=61&value2=Sacado_TaySerializationTests_MPI_1&field3=site&compare3=61&value3=mutrino&field4=buildstarttime&compare4=84&value4=2019-04-02T00:00:00&field5=buildstarttime&compare5=83&value5=2019-03-03T00:00:00"><font color="red">0</font></a></td>
<td align="right"><a href="https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-mutrino-intel-opt-openmp-KNL&field2=testname&compare2=61&value2=Sacado_TaySerializationTests_MPI_1&field3=site&compare3=61&value3=mutrino&field4=buildstarttime&compare4=84&value4=2019-04-02T00:00:00&field5=buildstarttime&compare5=83&value5=2019-03-03T00:00:00"><font color="green">25</font></a></td>
<td align="right"><a href="https://github.com/trilinos/Trilinos/issues/3942">#3863</a></td>
</tr>

</table>
