### ISSUE TITLE
MueLu: Scalar=float build errors

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#3946]
@trilinos/muelu 
Reported by @davydden in [this comment](https://github.com/trilinos/Trilinos/issues/3572#issuecomment-442327278).  Here are the reported build errors:

```
    8158    In file included from /Users/davydden/spack/var/spack/stage/trilinos-develop-p6xmhguuqtomai5fy4a36qmnn4wpqzfq/Trilinos/spack-build/packages/muelu/src/Utils/ExplicitInstantiation/MueLu_Zoltan2Interface.cpp:55:
  >> 8159    /Users/davydden/spack/var/spack/stage/trilinos-develop-p6xmhguuqtomai5fy4a36qmnn4wpqzfq/Trilinos/packages/muelu/src/Rebalancing/MueLu_Zoltan2Interface_def.hpp:197:24: error: no matching constructor for initialization of 'InputAdapterType' (aka 'XpetraMultiVe
             ctorAdapter<MultiVector<float, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > >')
     8160          InputAdapterType adapter(coords, weights, strides);
     8161                           ^       ~~~~~~~~~~~~~~~~~~~~~~~~
     8162    /Users/davydden/spack/var/spack/stage/trilinos-develop-p6xmhguuqtomai5fy4a36qmnn4wpqzfq/Trilinos/packages/muelu/src/Utils/MueLu_ETI_4arg.hpp:32:45: note: in instantiation of member function 'MueLu::Zoltan2Interface<float, int, int, Kokkos::Compat::KokkosDevi
             ceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::Build' requested here
     8163      TPETRA_INSTANTIATE_SLGN_NO_ORDINAL_SCALAR(MUELU_ETI_GROUP)
     8164                                                ^
     8165    /Users/davydden/spack/var/spack/stage/trilinos-develop-p6xmhguuqtomai5fy4a36qmnn4wpqzfq/Trilinos/packages/zoltan2/src/input/Zoltan2_XpetraMultiVectorAdapter.hpp:119:3: note: candidate constructor not viable: no known conversion from 'std::vector<const double
              *>' to 'std::vector<const scalar_t *> &' (aka 'vector<const float *> &') for 2nd argument
```

It's possible that this could block Sierra promotion, since they enable Scalar=float.

**Comment by kddevin** [comment]
@jhux2 
I think this is an easy fix -- just changing weights from double to scalar_t in MueLu_Zoltan2Interface_def.hpp.
I can give it a try if you like.

**Comment by cgcgcg** [comment]
@kddevin I started doing that, and that does work. However, I am getting more MueLu build errors that will need to be taken care of as well..

**Comment by kddevin** [comment]
OK, @cgcgcg .  It is in your capable hands.  Thanks!

**Comment by csiefer2** [comment]
#weclearlydonthaveenoughofthemillionsofTrilinosoptionstested

**Comment by cgcgcg** [comment]
@davydden I think I got to the point where MueLu at least builds, but I don't think that it will run. Out of curiosity: MueLu has not supported `Scalar=float` or `Scalar=complex<float>` in the past. Is this a Sierra requirement?

**Comment by mhoemmen** [comment]
@cgcgcg wrote:
> Is this a Sierra requirement?

Sierra builds with `Scalar=float` enabled.

**Comment by cgcgcg** [comment]
@davydden MueLu should build and run using `float` and `complex<float>` now. Some tests will fail, since the tolerances that we set are too tight. Could you check that everything works for Sierra?

**Comment by jhux2** [comment]
@cgcgcg Unless I'm mistaken, this issue was not opened on behalf of Sierra.

**Comment by jhux2** [comment]
> Unless I'm mistaken, this issue was not opened on behalf of Sierra.

The code, not the OS or machine :P.

**Comment by davydden** [comment]
> Could you check that everything works for Sierra?

ah... I don't have access to [Sierra](https://hpc.llnl.gov/hardware/platforms/sierra) ;-) I reported those issues from building on macOS, but I doubt they are specific to hardware/OS.

**Comment by mhoemmen** [comment]
Sierra does build with `float` and `complex<float>`.

**Comment by cgcgcg** [comment]
Oh, my bad :-)

**Comment by mhoemmen** [comment]
Said more precisely: "Sierra does _need_ to build with `float` and `complex<float>`."

**Comment by lucbv** [comment]
@mhoemmen PR #5288 gave another look at the `float` build for MueLu and it works fine.
Some improvement have also been made to allow unit-tests to use variable tolerance criteria based on the Scalar type instantiated.
I think we can close this old issue at this point.

**Comment by mhoemmen** [comment]
Thanks all! :D
