### ISSUE TITLE
Trilinos needs automated coverage testing

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#3958]
@trilinos/framework 

Trilinos currently has no coverage testing.  The last coverage build posted to CDash was for MueLu back on 8/20/2018 as shown in [this query](https://testing.sandia.gov/cdash-dev-view/index.php?project=Trilinos&date=2018-11-28&filtercount=2&showfilters=1&filtercombine=and&field1=hascoverage&compare1=1&value1=&field2=buildstarttime&compare2=84&value2=now).

We need regular automated coverage builds posting to CDash.

**Comment by csiefer2** [comment]
I've generally found coverage testing to demonstrate a few issues, but be buried in an avalanche of false alarms based on debugging code and/or error messages which never execute in the tests.

What is the value proposition here?

**Comment by bartlettroscoe** [comment]
> I've generally found coverage testing to demonstrate a few issues, but be buried in an avalanche of false alarms based on debugging code and/or error messages which never execute in the tests.

You can write unit tests to trigger all of that.  With proper test-driven development a few helper macros (to disable defensive code that should never get triggered or unreachable returns, etc.) it is pretty easy to get near 100% line coverage.  Any code not under automated testing has 0% confidence.

> What is the value proposition here?

We can't currently tell if test coverage is  getting better or worse without automated coverage builds.

It is insane a project the size and importance of Trilinos has no coverage testing and does not take coverage seriously.

**Comment by bartlettroscoe** [comment]
@csiefer2, and according to this policy:

* https://github.com/trilinos/Trilinos/wiki/Trilinos-Testing-Policy

Production Trilinos code should have almost 100% line and feature coverage.

**Comment by csiefer2** [comment]
> You can write unit tests to trigger all of that. With proper test-driven development a few helper macros (to disable defensive code that should never get triggered or unreachable returns, etc.) it is pretty easy to get near 100% line coverage. Any code not under automated testing has 0% confidence.

Sure, you *can*.  But nobody *will*.

**Comment by bartlettroscoe** [comment]
> Sure, you can. But nobody will.

I do.  Otherwise, you can't trust your error handling.

**Comment by csiefer2** [comment]
> It is insane a project the size and importance of Trilinos has no coverage testing and does not take coverage seriously.

Insane, perhaps.  But Trilinos is not unique in this regard.  We used to do coverage testing for <insert engineering code here>.  We stopped because the signal-to-noise ratio was way too low for it to be remotely useful.

**Comment by bartlettroscoe** [comment]
> We stopped because the signal-to-noise ratio was way too low for it to be remotely useful.

@csiefer2, lots of examples of bad SE practices.  Trilinos should be better.  Trilinos customers need Trilinos to be better.

**Comment by csiefer2** [comment]
> I do. Otherwise, you can't trust your error handling.

I salute your dedication to testing, sir.

**Comment by csiefer2** [comment]
> @csiefer2, lots of examples of bad SE practices. Trilinos should be better. Trilinos customers need Trilinos to be better.

Don't get me wrong, there's nothing wrong with running together code coverage tests, so long as it doesn't stop @trilinos/framework from doing something more important.  I'm just skeptical that they'll make any meaningful impact on developer behavior.

**Comment by bartlettroscoe** [comment]
> I salute your dedication to testing, sir.

@csiefer2, if one can make it all the way through the book [Working Effectively with Legacy Code](https://bartlettroscoe.github.io/readingList.html#Most_Recommended_SE_Books) without adopting a "dedication to testing" then one should not be writing production quality software.

**Comment by bartlettroscoe** [comment]
> I'm just skeptical that they'll make any meaningful impact on developer behavior.

It will if it is part of PR testing.  For example, coverage has to go up or be the same in order to accept a PR.  Forcing compliance is the only way to viable way to "impact developer behavior".

**Comment by csiefer2** [comment]
> @csiefer2, if one can make it all the way through the book [Working Effectively with Legacy Code](https://bartlettroscoe.github.io/readingList.html#Most_Recommended_SE_Books) without adopting a "dedication to testing" then one should not be writing production quality software.

So you recommend that test then?

**Comment by csiefer2** [comment]
> It is pretty obvious which direction things are going. And Trilinos is behind in this trend if you look at other projects.

It depends on your basis for comparison, I suppose.  Trilinos looks way ahead of the curve from this chair (to the point where productivity is negatively impacted).

**Comment by bartlettroscoe** [comment]
Would be great if we had one build with coverage results.  Would help in the code review process.
