### ISSUE TITLE
Website: Trilinos Capability Area Information Out of Date

### ISSUE THREAD

**Issue by csiefer2** [trilinos/Trilinos#3959]
Information on Trilinos product leads still lists the old capability areas:

https://trilinos.org/capability-areas/
https://trilinos.github.io/capability-areas.html

This leaves people who don't know who is in charge of what no way of finding that information out.

@trilinos/framework 
@trilinos/linear-solvers 
@trilinos/trilinos-web-portal

**Comment by srajama1** [comment]
We are discussing a revamp of the Trilinos website. Please note https://trilinos.github.io/ is updated to reflect the product areas.

**Comment by jwillenbring** [comment]
Closing. A refresh of this info is being coordinated separately by @ccober6
