### ISSUE TITLE
Tpetra: Possible OpenMPI bug; don't enable CUDA-aware MPI support

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#3968]
@trilinos/tpetra @trilinos/framework 

When debugging #3500, @rppawlo found a possible bug in OpenMPI 2.1.2 with CUDA-aware MPI enabled.  When doing a Tpetra::Export between two MultiVectors with AbsMax CombineMode, the target MultiVector sometimes doesn't get the right result.  Roger found that on unpack, the receive buffer doesn't always have the right values in it.  It's not consistently reproducible -- Roger sometimes has to run the test three times to get this to happen -- but it does happen fairly often.  Roger thinks that MPI might not have finished writing to the buffer, on a process (Proc 0) that has no sends but some receives, even though Process 0 should have done an `MPI_Waitall` on the receives (they are `MPI_Irecv`, always).  The results are _always_ correct when running with CUDA-aware MPI disabled (that's a Tpetra option, not an MPI option).

Next steps:
  - [x] Make sure this isn't an issue with `Kokkos::atomic_assign` in AbxMax
  - [ ] Test with different OpenMPI versions
  - [ ] Write a short reproducer, to make sure this isn't a Tpetra issue (start perhaps with @crtrott 's CG solve)

We recommend disabling Tpetra's CUDA-aware MPI option for now.

**Comment by mhoemmen** [comment]
@micahahoward @vbrunini @jclause

**Comment by mhoemmen** [comment]
Roger commented out the kernel launch (on device), and wrote a host kernel that assumes UVM.  It's sequential, but uses `Kokkos::atomic_assign` on the UVM destination buffer.  This works correctly, thus ruling out `Kokkos::atomic_assign` as a possible issue (at least on host).

**Comment by mhoemmen** [comment]
Running the kernel on device twice, with fences all around and in between, still manifests the bug.  Even if we put a `sleep(5)` in between the two kernel launches, we still sometimes manifest the bug.

**Comment by mhoemmen** [comment]
This example uses 4 MPI processes.  Could not get it to fail when changing it to smaller numbers of MPI processes, but that changes the distribution.

**Comment by mhoemmen** [comment]
This is running on waterman.  Interactive job launched like this:
```
bsub -Is -n 4 -q rhel7W bash
```
`mpirun` launched like this:
```
mpirun -np 4 ./PanzerAdaptersSTK_PoissonInterfaceExample.exe --3d --nx=6 --nonlinear
```

**Comment by mhoemmen** [comment]
Roger can't test with other OpenMPI versions on waterman, since there are only two available, and the other one is known to be broken.

**Comment by mhoemmen** [comment]
@rppawlo The issue could be that the AbsMax implementation could have a race condition on `dest`.  Here is the implementation:
```c++
  template<class ExecutionSpace>
  struct AbsMaxOp {
    template <typename T>
    KOKKOS_INLINE_FUNCTION
    T max(const T& a, const T& b) const { return a > b ? a : b; }

    template <typename Scalar>
    KOKKOS_INLINE_FUNCTION
    void operator() (Scalar& dest, const Scalar& src) const {
      typedef Kokkos::Details::ArithTraits<Scalar> SCT;
      Kokkos::atomic_assign(&dest, Scalar(max(SCT::abs(dest),SCT::abs(src))));
    }
  };
```
The functor first reads `dest` _nonatomically_, inside the max.  It then updates `dest` _atomically_ in `Kokkos::atomic_assign`.  The read could get a "stale" value.  If `src` is smaller than that stale value, then `dest` could get clobbered with the resulting stale value.

For example, suppose that only one `dest` value, 7, gets updated by two threads.  Each thread has one `src` value.  Thread 0 has `src=6`, and Thread 1 has `src=8`.  A correct run would have `dest=8` on output.  Here is a sequence of operations that results in an incorrect `dest` value on output:

  1. Thread 0 reads `dest=7`, nonatomically.
  2. Thread 0 computes `max(abs(dest), abs(src))` as `max(7, 6) = 7`.
  3. Thread 1 reads `dest=7`, nonatomically.
  4. Thread 1 computes `max(abs(dest), abs(src))` as `max(7, 8) = 8`.
  5. Thread 1 atomically assigns 8 to `dest`.
  6. Thread 0 atomically assigns 7, the wrong value, to `dest`.

The nice thing is that Kokkos provides `atomic_fetch_max`, that does the right thing.  We could try this:
```c++
template<class Scalar1, class Scalar2>
struct AbsMaxOper {
  KOKKOS_FORCEINLINE_FUNCTION
  static Scalar1 apply(const Scalar1& val1, const Scalar2& val2) {
    const auto val1_abs = Kokkos::ArithTraits<Scalar1>::abs (val1);
    const auto val2_abs = Kokkos::ArithTraits<Scalar2>::abs (val2);
    return val1_abs > val2_abs ? Scalar1 (val1_abs) : Scalar1 (val2_abs);
  }
};

template<class ExecutionSpace>
struct AbsMaxOp {
  template <typename Scalar>
  KOKKOS_INLINE_FUNCTION
  void operator() (Scalar& dest, const Scalar& src) const {
    // Imitate implementation of Kokkos::atomic_fetch_max
    Kokkos::Impl::atomic_fetch_oper (AbsMaxOper<Scalar, const Scalar>(), dest, val);
  }
};
```

**Comment by crtrott** [comment]
Was wondering why you don't use atomic_fetch_max, but saw it now (AbsMax). And yeah this is fine. I am almost tempted to expose the interface in the non-impl namespace anyway (i.e. that we have a generic atomic_fetch_oper and you can provide the operations implementation.

**Comment by crtrott** [comment]
Also: Mark is certainly right that the other implementation of doing this with atomic_assign is incorrect. Our fetch_oper thing goes through CAS loops or the lock_array stuff to make the full thing work correct.

**Comment by mhoemmen** [comment]
@rppawlo Thanks!  I will write a unit test now and see if I can get it to fail on a GPU.  That would give me more confidence that what you observed was caused by this race condition, rather than by some awful "CUDA-aware MPI is broken in an awful way" thing.

**Comment by rppawlo** [comment]
@mhoemmen - That did it! Thanks! Had to make some minor changes to code above to get it to compile. Just put up a PR with that change and some panzer cleanup (in a separate commit) as well. See #3999 
@crtrott - if you could make the atomic_fetch_oper public, I could see many use cases for it!

**Comment by mhoemmen** [comment]
@rppawlo It looks like you missed PR #3996.  I'll close that one, since you actually had a chance to test the fix on waterman.  However, I'll need to pull in the test that I wrote in PR #3996.

**Comment by rppawlo** [comment]
PR #3999 was merged. Closing.
