### ISSUE TITLE
Set up CDash on a new testing VM

### ISSUE THREAD

**Issue by jwillenbring** [trilinos/Trilinos#399]
**CC:** @trilinos/framework

The VM will be based on either the current "testing" machine, or it will be a plain COE VM. I don't have the VM yet. The sysadmins are working on the VM. My understanding is that it exists, but I don't have access to it yet.

Once I get access, I will work through the CDash installation instructions and the extra information from Zack G. This should help us determine if either the actual hardware, or the specific version CDash we were working with is causing the submission issues. I will also verify based on Zack's comments that we are attempting to use the right type of database. I have a good CDash SHA from Ross to use.

This will be supported by Kitware through:

* https://gitlab.kitware.com/snl/project-1/issues/7

**Comment by bartlettroscoe** [comment]
Can we add some detail here?

**Comment by jwillenbring** [comment]
This is being tracked elsewhere. Closing this ticket.
