### ISSUE TITLE
MueLu_Maxwell3D- tests not run due to build failure in ATDM build

### ISSUE THREAD

**Issue by fryeguy52** [trilinos/Trilinos#3994]
CC: @trilinos/muelu, @srajama1 (Trilinos Linear Solvers Product Lead), @bartlettroscoe, @fryeguy52
 
## Description
 
As shown in [this query](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercombine=and&filtercombine=and&filtercount=6&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-cee-rhel6-clang-5.0.1-openmpi-1.10.2-serial-static-opt&field2=testname&compare2=65&value2=MueLu_Maxwell3D-&field3=testname&compare3=66&value3=_MPI_4&field4=site&compare4=61&value4=cee-rhel6&field5=buildstarttime&compare5=84&value5=2018-12-04T00%3A00%3A00&field6=buildstarttime&compare6=83&value6=2018-11-04T00%3A00%3A00) the following tests are not being run due to a [build failure](https://testing.sandia.gov/cdash/viewBuildError.php?buildid=4245202) that started on 12/01/2018:
* MueLu_Maxwell3D-Epetra_MPI_4
* MueLu_­Maxwell3D-Tpetra-Stratimikos_­MPI_­4
* MueLu_­Maxwell3D-Tpetra_­MPI_­4

 in the build:
* Trilinos-atdm-cee-rhel6-clang-5.0.1-openmpi-1.10.2-serial-static-opt

The error occurs when building `packages/muelu/test/maxwell/CMakeFiles/MueLu_Maxwell3D.dir/Maxwell3D.cpp.o`

Standard error:
```
/scratch/rabartl/Trilinos.base/NightlyBuilds/Trilinos-atdm-cee-rhel6-clang-5.0.1-openmpi-1.10.2-serial-static-opt/SRC_AND_BUILD/Trilinos/packages/muelu/test/maxwell/Maxwell3D.cpp:262:11: error: no viable overloaded '='
      tm2 =  Teuchos::null;
      ~~~ ^  ~~~~~~~~~~~~~
/scratch/rabartl/Trilinos.base/NightlyBuilds/Trilinos-atdm-cee-rhel6-clang-5.0.1-openmpi-1.10.2-serial-static-opt/SRC_AND_BUILD/Trilinos/packages/teuchos/comm/src/Teuchos_TimeMonitor.hpp:178:34: note: candidate function (the implicit copy assignment operator) not viable: no known conversion from 'Teuchos::ENull' to 'const Teuchos::TimeMonitor' for 1st argument
class TEUCHOSCOMM_LIB_DLL_EXPORT TimeMonitor :
                                 ^
/scratch/rabartl/Trilinos.base/NightlyBuilds/Trilinos-atdm-cee-rhel6-clang-5.0.1-openmpi-1.10.2-serial-static-opt/SRC_AND_BUILD/Trilinos/packages/muelu/test/maxwell/Maxwell3D.cpp:274:11: error: no viable overloaded '='
      tm3 = Teuchos::null;
      ~~~ ^ ~~~~~~~~~~~~~
/scratch/rabartl/Trilinos.base/NightlyBuilds/Trilinos-atdm-cee-rhel6-clang-5.0.1-openmpi-1.10.2-serial-static-opt/SRC_AND_BUILD/Trilinos/packages/teuchos/comm/src/Teuchos_TimeMonitor.hpp:178:34: note: candidate function (the implicit copy assignment operator) not viable: no known conversion from 'Teuchos::ENull' to 'const Teuchos::TimeMonitor' for 1st argument
class TEUCHOSCOMM_LIB_DLL_EXPORT TimeMonitor :
                                 ^
2 errors generated.
```

## Current Status on CDash

The current status of these tests/builds for the current testing day can be found [here](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercount=4&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-cee-rhel6-clang-5.0.1-openmpi-1.10.2-serial-static-opt&field2=testname&compare2=65&value2=MueLu_Maxwell3D-&field3=testname&compare3=66&value3=_MPI_4&field4=site&compare4=61&value4=cee-rhel6)

## Steps to Reproduce

One should be able to reproduce this failure on a machine with a cee rhel6 environment as described in:
* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md

More specifically, the commands given for a machine with a cee rhel6 environment are provided at:
* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#cee-rhel6-environment

The exact commands to reproduce this issue should be:
```
$ cd <some_build_dir>/
$ source $TRILINOS_DIR/cmake/std/atdm/load-env.sh Trilinos-atdm-cee-rhel6-clang-5.0.1-openmpi-1.10.2-serial-static-opt
$ cmake \
 -GNinja \
 -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
 -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_MueLu=ON \
 $TRILINOS_DIR
$ make NP=16
$ ctest -j16
```

**Comment by srajama1** [comment]
@cgcgcg Thank you

**Comment by bartlettroscoe** [comment]
After the merge of PR #3993 yesterday, the [today](https://testing.sandia.gov/cdash-dev-view/index.php?project=Trilinos&parentid=4253654) the build error is gone (see the `-1` but the `0` build errors in the "MueLu" row)

NOTE: The the one failing MueLu test shown [here](https://testing.sandia.gov/cdash-dev-view/viewTest.php?onlydelta&buildid=4253662) is actually just the randomly failing test `MueLu_UnitTestsBlockedEpetra_MPI_4` with the failing unit test 116 `116. Hierarchy_double_int_int_Kokkos_Compat_KokkosSerialWrapperNode_Write_UnitTest` which we already know about (see  #3897).

Therefore, looks like this issue is addressed and we can close.

Thanks @cgcgcg!
