### ISSUE TITLE
Tpetra::BlockCrsMatrix: Why does _decl.hpp header include <ctime> ???

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#40]
@trilinos/tpetra @jhux2

**Comment by mhoemmen** [comment]
As far as I can tell, nothing in the decl or def uses it.

**Comment by jhux2** [comment]
This is not longer necessary.  It is a hold-over from when the write 
functionality was in the class file.  The writer puts a time stamp in 
the file.

Mark Hoemmen wrote on 12/02/2015 11:13 AM:

**Comment by mhoemmen** [comment]
Cool, just wanted to make sure removing it wouldn't break anything.  Thanks!

**Comment by mhoemmen** [comment]
I didn't get the commit message syntax right to close this issue automatically; it's now closed.
