### ISSUE TITLE
Enable Amesos2Smoother in MueLu for non-conventional maps

### ISSUE THREAD

**Issue by tawiesn** [trilinos/Trilinos#402]
The MueLu::Amesos2Smoother can handle arbitrary linear systems with non-conventional maps (e.g. maps with discontinuous GID numbering) in serial. Extend this functionality to number of procs > 1.

**Comment by tawiesn** [comment]
The same would be useful for MueLu::AmesosSmoother. In case of Amesos only certain direct solvers can be used which support the Amesos "Reindex" flag. Reindexing the matrix might not be a cheap option. Add some screen output with a performance warning.

**Comment by aprokop** [comment]
Ideally, this should be done in Amesos2, MueLu simply works around the issue.

**Comment by mhoemmen** [comment]
btw Amesos2 works for Epetra objects too, so maybe MueLu doesn't need an additional Amesos interface here?

**Comment by tawiesn** [comment]
I guess we want to keep our (separate) AmesosSmoother, since Amesos2 (as far as i know) does not support all direct solvers that Amesos is supporting. In MueLu, we use Amesos2 only together with Tpetra and Amesos with Epetra.

**Comment by jhux2** [comment]
@tawiesn @aprokop I'm revisiting this issue.  Was there a patch involved?

**Comment by jhux2** [comment]
@pwxy

**Comment by aprokop** [comment]
@jhux2 Not sure, it's been so long. I also remember some progress being made on Amesos2 side, so need to touch bases with @srajama1 .

**Comment by srajama1** [comment]
@ndellingwood has implemented reindexing in Amesos2.  I would rather not add anymore new features to Amesos.

**Comment by jhux2** [comment]
@srajama1 I don't think Amesos was part of the discussion.

**Comment by jhux2** [comment]
Issue #2270 may be related.

**Comment by mhoemmen** [comment]
@trilinos/muelu @trilinos/amesos2 Was this ever fixed?  Aria ran a test with a simple input deck, and it threw the following exception:
```
**  Throw test that evaluated to true: rowMap->getComm()->getSize() > 1
**  
**  MueLu::Amesos2Smoother::Setup Fixing coarse matrix for Amesos2 for multiple processors has not been implemented yet.
```
@jclause tracked this down to the following checks in `MueLu_Amesos2Smoother_def.hpp`:
```cpp
      // If our system is non-conventional, here is the place where we try to fix it
      // One example is: if our maps contain a gap in them, for instance GIDs
      // are [0,..., 100, 10000, ..., 10010], then Amesos2 breaks down.
      //
      // The approach we take is to construct a second system with maps
      // replaced by their continuous versions.
      //
      // FIXME: for the moment, this functionality works for selected limited scenarios
      this->GetOStream(Runtime1) << "MueLu::Amesos2Smoother::Setup(): using system transformation" << std::endl;

      TEUCHOS_TEST_FOR_EXCEPTION(rowMap->getComm()->getSize() > 1, Exceptions::RuntimeError,
        "MueLu::Amesos2Smoother::Setup Fixing coarse matrix for Amesos2 for multiple processors has not been implemented yet.");
      TEUCHOS_TEST_FOR_EXCEPTION(!rowMap->isSameAs(*A->getColMap()), Exceptions::RuntimeError,
        "MueLu::Amesos2Smoother::Setup Fixing coarse matrix for Amesos2 when row map is different from column map has not been implemented yet.");

      RCP<CrsMatrixWrap> Acrs = rcp_dynamic_cast<CrsMatrixWrap>(A);
      TEUCHOS_TEST_FOR_EXCEPTION(Acrs.is_null(), Exceptions::RuntimeError,
        "MueLu::Amesos2Smoother::Setup Fixing coarse matrix for Amesos2 when matrix is not a Crs matrix has not been implemented yet.");
```
@jclause says, "I can almost guarantee we have gaps in the GID maps."

**Comment by cgcgcg** [comment]
@mhoemmen Can we check if MueLu ever builds a coarse grid, or if this is directly the matrix provided by Aria?

**Comment by vbrunini** [comment]
It looks like https://github.com/trilinos/Trilinos/pull/6905 gets our test working by using Amesos2's ability to handle non-contiguous maps instead of the MueLu fixup code. Is that approach a viable option in general?
