### ISSUE TITLE
Xpetra: Build warnings with GCC 7.2 and CUDA (ATDM build)

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#4035]
@trilinos/xpetra  
```
.../Trilinos/packages/xpetra/src/CrsMatrix/Xpetra_TpetraCrsMatrix.hpp(955): warning: missing return statement at end of non-void function "Xpetra::TpetraCrsMatrix<Scalar, int, int, Xpetra::EpetraNode>::getLocalMatrix [with Scalar=double]"
          detected during:
            instantiation of "Xpetra::TpetraCrsMatrix<Scalar, int, int, Xpetra::EpetraNode>::local_matrix_type Xpetra::TpetraCrsMatrix<Scalar, int, int, Xpetra::EpetraNode>::getLocalMatrix() const [with Scalar=double]"
(613): here
            instantiation of "Xpetra::TpetraCrsMatrix<Scalar, int, int, Xpetra::EpetraNode>::TpetraCrsMatrix(const Teuchos::RCP<const Xpetra::Map<int, int, Xpetra::EpetraNode>> &, size_t, Xpetra::ProfileType, const Teuchos::RCP<Teuchos::ParameterList> &) [with Scalar=double]"
.../Trilinos/packages/xpetra/src/CrsMatrix/Xpetra_CrsMatrixFactory.hpp(288): here
```

**Comment by jhux2** [comment]
@mhoemmen Can this be reproduced using the Trilinos ATDM [recipe](https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md) for CUDA?

**Comment by cgcgcg** [comment]
@mhoemmen Huh, it seems that there is a `TEUCHOS_UNREACHABLE_RETURN` there. Shouldn't that have fixed the issue?

**Comment by mhoemmen** [comment]
@cgcgcg I can't take a couple days off I guess ;-)  CUDA warnings are weird.  If you can figure out how to make the macro work without breaking an existing non-CUDA warnings-as-errors build, please feel free to try.

**Comment by mhoemmen** [comment]
On the other hand, we haven't tried `[[noreturn]]` yet.  That's legit C++11.  Here is how Teuchos defines the macro now:
```c++
#ifdef __NVCC__
  #define TEUCHOS_UNREACHABLE_RETURN_IMPL(dummyReturnVal)
#else
  #define TEUCHOS_UNREACHABLE_RETURN_IMPL(dummyReturnVal) \
    return dummyReturnVal
#endif
```
It literally does nothing when building with CUDA.  That's perhaps the first issue ;-) .  Second issue is that Xpetra usually uses the macro when it wants to throw.  Why not just have a `[[noreturn]]` function that throws, and call that, instead of using a macro _and_ another macro that throws?  For example:
```c++
[[noreturn]] void
throw_logic_error(const std::string& msg) {
  throw std::logic_error (msg);
}

ReturnValue foo () {
  if (using_Epetra) {
    return foo_Epetra ();
  } else if (using_Tpetra) {
    return foo_Tpetra ();
  }
  throw_logic_error ("uh oh");
}
```
