### ISSUE TITLE
Proposed Belos interface change for speedup when x_init = 0.

### ISSUE THREAD

**Issue by ambrad** [trilinos/Trilinos#404]
It's common when solving A x = b iteratively for x_init = 0.

BelosLinearProblem::setProblem always calls computeCurrResVec, and
computeCurrResVec (essentially) always compute A*x_init. This is a waste of an
MVP if x_init = 0.

Mark, Alicia, and I discussed an interface change to optimize out the wasted
MVP. We propose adding the function
`
void setAXMinusB(const Teuchos::RCP<MV>& newR)
`
This function would be optionally called before setProblem. If it is called,
then setProblem will use newR instead of explicitly computing the residual.

**Comment by agsalin** [comment]
Can you make this selectable through an teuchos parameterList option? From Albany we access Belos through Stratimikos, which in turn is accessed through Piro.

Will it be safe if someone sends  x_init != 0  but still requests this, perhaps by overwriting x instead of updating it?

**Comment by amklinv** [comment]
Tagging @hkthorn and @mhoemmen :-)

**Comment by mhoemmen** [comment]
> Can you make this selectable through an teuchos parameterList option? From Albany we access Belos through Stratimikos, which in turn is accessed through Piro.

Hi @agsalin -- I've made that feature request a separate issue, #412.  We have to add the feature to Belos first.  btw does the application ever want to precompute the residual vector on its own before handing off the linear system to the linear solver?

**Comment by mhoemmen** [comment]
> Will it be safe if someone sends x_init != 0 but still requests this, perhaps by overwriting x instead of updating it?

No.  If users provide an initial residual vector R = AX - B that is not consistent with the initial guess X, then we do nothing to fix it.

**Comment by amklinv** [comment]
A related message from Mark: 

> We want users to have to call setProblem before solving the linear system, even if they specified the residual vector(s).  This lets Belos::LinearProblem put itself in a consistent state.  In Belos::LinearProblem::setProblem, check whether the user specified the residual vector(s); if so, don’t compute them.  setProblem may and should also check the invariants below.

> If the user’s unpreconditioned residual is set:
- The problem must be set
- If the user’s preconditioned residual is NOT set, then the left preconditioner must be null.
- In this case, Belos::LinearProblem::setProblem must set the user’s preconditioned residual to the unpreconditioned residual.

> If the user’s preconditioned residual is set:
- The problem must be set
- The user’s unpreconditioned residual must be set

> Name the new methods setInitResVec (unpreconditioned) and setInitPrecResVec (left preconditioned).  Their corresponding get* methods return the user’s vector(s) if they are not null, else they return the LinearProblem’s existing built-in vector(s).

**Comment by amklinv** [comment]
The changes have been merged into the develop branch and should hit master sometime later this week.

**Comment by mhoemmen** [comment]
Thanks @amklinv !  I'll close this issue then.
