### ISSUE TITLE
Zoltan test diff failures in targeted CUDA PR build Trilinos-atdm-white-ride-cuda-9.2-release-debug-pt

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#4042]
CC: @trilinos/zoltan, @kddevin (Trilinos <product-area-name> Product Lead), @bartlettroscoe, @fryeguy52

## Next Action Status

<status-and-or-first-action>

## Description

As shown in [this query](https://testing.sandia.gov/cdash-dev-view/viewTest.php?onlyfailed&buildid=4287837) the tests:

* `Zoltan_ch_simple_zoltan_parallel`
* `Zoltan_ch_grid20x19_zoltan_parallel`
* `Zoltan_ch_ewgt_zoltan_parallel`
* `Zoltan_ch_nograph_zoltan_parallel`

fail in the build `Trilinos-atdm-white-ride-cuda-9.2-release-debug-pt` which is the current candidate CUDA PR build described in #2464.  They have failed since we switched from a `debug` build to a `release-debug` build for the reasons described in https://github.com/trilinos/Trilinos/issues/2464#issuecomment-444637454.  These are the only new tests that are failing since we switched from a `debug` to a `release-debug` build. 

These all look to be "diff" failures like [here](https://testing.sandia.gov/cdash-dev-view/testDetails.php?test=61372846&build=4287837) showing:

```
DEBUG moving files:  simple.out.4.3 output/simple.rib-partlocal4.4.3
DEBUG comparing files:  answers/simple.rib-partlocal4.4.3 output/simple.rib-partlocal4.4.3
DEBUG comparing files:  answers/simple.rib-partlocal4.drops.4.3 output/simple.rib-partlocal4.drops.4.3
DEBUG COMPARISON 1   1
Test simple:rib-partlocal4 FAILED (Diff failed on 1 files)
```

## Current Status on CDash

The current status of these tests/builds for the current testing day can be found at:

* [Zoltan tests in Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-release-debug-pt build over last two days](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-release-debug-pt&field2=testname&compare2=65&value2=Zoltan_&field3=buildstarttime&compare3=83&value3=2%20days%20ago)

NOTE: Click "previous" to see the previous day's test results in case this build did not run today or add the filter ["Build Start Time", "is after", "2 weeks ago"] to see history of tests in previous days.   (Or create any filters you want from there.)

## Steps to Reproduce

One should be able to reproduce these build errors on either 'white' or 'ride' by cloning the Trilinos git repo, checking out the 'develop' branch, creating a build directory, and then doing:

```
$ cd <some_build_dir>/

$ source $TRILINOS_DIR/cmake/std/atdm/load-env.sh cuda-9.2-release-debug

$ cmake \
  -GNinja \
  -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
  -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_Zoltan=ON \
  $TRILINOS_DIR

$ make NP=16

$ bsub -x -Is -q rhel7F -n 16 ctest -j16
```

**Comment by srajama1** [comment]
@kddevin should have been mentioned in this issue

**Comment by bartlettroscoe** [comment]
Actually, these are NIGHTLY tests and are not run in the Trilinos CUDA PR build.  Therefore, I don't know if there is any driver to fix these in this build.  We can leave them failing.  It does not mess up our ability to see new failures but if there is no plan to fix these then we might as well disable them in this build.

**Comment by bartlettroscoe** [comment]
Defects with Primary tested code not currently used (or being tested) by ATDM is not really an ATDM issue so I am removing the "client: ATDM" label to get this off our list of active issues.
