### ISSUE TITLE
MueLu: proposed change for when to enable Kokkos refactor

### ISSUE THREAD

**Issue by jhux2** [trilinos/Trilinos#4044]
@trilinos/muelu @csiefer2 

In order to make testing for ATDM easier (#3941), I propose enabling *compilation* of Kokkos refactor code in MueLu based on having Kokkos enabled.

This is the current situation:

```
IF ( ${PACKAGE_NAME}_ENABLE_Tpetra AND (Tpetra_INST_OPENMP OR Tpetra_INST_CUDA) )
  SET(Kokkos_Refactor_On_By_Default ON)
  MESSAGE("-- MueLu: Kokkos_Refactor ON by default")
ELSE()
  SET(Kokkos_Refactor_On_By_Default OFF)
ENDIF()
```

This is what I propose:

```
IF ( ${PACKAGE_NAME}_ENABLE_KokkosCore )
  SET(Kokkos_Refactor_On_By_Default ON)
  MESSAGE("-- MueLu: Kokkos_Refactor ON by default")
ELSE()
  SET(Kokkos_Refactor_On_By_Default OFF)
ENDIF()
```

**Comment by lucbv** [comment]
@jhux2 will this work for people who use `Epetra` and `Kokkos` for no good reason?

**Comment by csiefer2** [comment]
You have my _nihil obstat_

**Comment by lucbv** [comment]
@jhux2 should we close this?
