### ISSUE TITLE
Thyra: Add time step size to Thyra::ModelEvaluator::InArgs

### ISSUE THREAD

**Issue by rppawlo** [trilinos/Trilinos#405]
@trilinos/thyra 
@bartlettroscoe 
@eric-c-cyr

We have many algorithms where the physics equation assembly that requires knowledge of the time step size. An example is the tau computation in stabilization of finite element formulations. We would like to add the time step size as a first class input parameter to the Model Evaluator InArgs. This is to support the new time integration library where feedback from application devs cited this as an important item.

**Comment by agsalin** [comment]
Yes, we have run across this several times as well: rate of strain for stateful materials; semi-implicit time integrators; calls to subgrid models for multiscale.

I like the vision of not needing it, and just x_dot, but unfortunately delta_t comes up often.

**Comment by rppawlo** [comment]
cc'ing Curt @ccober6

**Comment by rppawlo** [comment]
This is completed.
