### ISSUE TITLE
Panzer_IntegrationValues2 build failures on ATDM cuda 9.2 builds

### ISSUE THREAD

**Issue by fryeguy52** [trilinos/Trilinos#4050]
CC: @trilinos/panzer, @mperego (Trilinos Discretizations Product Lead), @bartlettroscoe, @fryeguy52 
 
## Next Action Status

PR #4051 with fix merged to 'develop' on 12/13/2018.  Next: Watch for cleaned-up builds starting 12/14/2018 ...
 
## Description
 
As shown in [this query](https://testing.sandia.gov/cdash/index.php?project=Trilinos&date=2018-12-13&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=6&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-&field2=buildname&compare2=62&value2=Trilinos-atdm-white-ride-cuda-9.2-release-debug-pt&field3=subprojects&compare3=93&value3=Panzer&field4=builderrors&compare4=43&value4=0&field5=buildstarttime&compare5=83&value5=2018-12-12&field6=buildstarttime&compare6=84&value6=2018-12-14) there is a build failure while building `packages/panzer/disc-fe/src/CMakeFiles/panzer-disc-fe.dir/Panzer_IntegrationValues2.cpp.o` in the following builds:

* Trilinos-atdm-waterman-cuda-9.2-debug
* Trilinos-atdm-waterman-cuda-9.2-opt
* Trilinos-atdm-waterman-cuda-9.2-release-debug
* Trilinos-atdm-white-ride-cuda-9.2-debug
* Trilinos-atdm-white-ride-cuda-9.2-opt
* Trilinos-atdm-white-ride-cuda-9.2-release-debug

here is part of the output from the failures:
```
/home/jenkins/white/workspace/Trilinos-atdm-white-ride-cuda-9.2-release-debug/SRC_AND_BUILD/Trilinos/packages/panzer/disc-fe/src/Panzer_IntegrationValues2.cpp(1140): error: no instance of function template "std::make_pair" matches the argument list
            argument types are: (int, Kokkos::Cuda::size_type)
          detected during instantiation of "void panzer::IntegrationValues2<Scalar>::getCubatureCV(const PHX::MDField<Scalar, panzer::Cell, panzer::BASIS, panzer::Dim, void, void, void, void, void> &, int) [with Scalar=double]" 
(275): here
```

## Current Status on CDash

The current status of these tests/builds for the current testing day can be found [here](https://testing.sandia.gov/cdash/index.php?project=Trilinos&date=2018-12-13&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=4&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-&field2=buildname&compare2=62&value2=Trilinos-atdm-white-ride-cuda-9.2-release-debug-pt&field3=subprojects&compare3=93&value3=Panzer&field4=builderrors&compare4=43&value4=0)

## Steps to Reproduce

One should be able to reproduce this failure on waterman as described in:
* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md

More specifically, the commands given for waterman are provided at:
* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#waterman

The exact commands to reproduce this issue should be:
```
$ cd <some_build_dir>/
$ source $TRILINOS_DIR/cmake/std/atdm/load-env.sh Trilinos-atdm-waterman-cuda-9.2-debug
$ cmake \
 -GNinja \
 -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
 -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_Panzer=ON \
 $TRILINOS_DIR
$ make NP=16
$ bsub -x -Is -n 20 ctest -j20
```

**Comment by rppawlo** [comment]
Fixed in PR #4051

**Comment by bartlettroscoe** [comment]
PR #4051 just merged to 'develop'.  Now we wait and watch for passing builds tomorrow posted to CDash and then we can close.

**Comment by bartlettroscoe** [comment]
As shown in [this query](https://testing.sandia.gov/cdash-dev-view/index.php?project=Trilinos&date=2018-12-14&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-&field2=buildname&compare2=62&value2=Trilinos-atdm-white-ride-cuda-9.2-release-debug-pt&field3=buildname&compare3=63&value3=cuda), the CUDA build errors are all gone today.  Closing as complete.
