### ISSUE TITLE
Framework: Intel Autotester is Woofing

### ISSUE THREAD

**Issue by csiefer2** [trilinos/Trilinos#4069]
Status Flag 'Pull Request AutoTester' - Failure: Timed out waiting for job Trilinos_pullrequest_intel_17.0.1 to start: Total Wait = 603

    Other jobs have been previously started - We must stop them...

**Comment by william76** [comment]
Hey @csiefer2 a link to where this message came from would greatly increase the chances someone might go try and find it and see what it was...
