### ISSUE TITLE
Tpetra: BCRS mat-vec internal compiler error

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#407]
Reported by @agsalin, repeated by @bathmatt and @crtrott .

In file included from
/home/agsalin/Trilinos/build/packages/tpetra/core/src/Tpetra_Experimental_BlockCrsMatrix.hpp:2:0,
                  from
/home/agsalin/Trilinos/packages/ifpack2/src/Ifpack2_Relaxation_def.hpp:50,
                  from
/home/agsalin/Trilinos/build/packages/ifpack2/src/Ifpack2_Relaxation.hpp:2,
                  from
/home/agsalin/Trilinos/packages/ifpack2/src/Ifpack2_Details_OneLevelFactory_def.hpp:51,
                  from
/home/agsalin/Trilinos/build/packages/ifpack2/src/Ifpack2_Details_OneLevelFactory.hpp:2,
                  from
/home/agsalin/Trilinos/packages/ifpack2/src/Ifpack2_Details_Factory_def.hpp:46,
                  from
/home/agsalin/Trilinos/build/packages/ifpack2/src/Ifpack2_Details_Factory.hpp:2,
                  from
/home/agsalin/Trilinos/packages/ifpack2/src/Ifpack2_Factory_decl.hpp:48,
                  from
/home/agsalin/Trilinos/build/packages/ifpack2/src/Ifpack2_Factory.hpp:1,
                  from
/home/agsalin/Trilinos/packages/ifpack2/src/Ifpack2_Details_LinearSolverFactory_def.hpp:54,
                  from
/home/agsalin/Trilinos/build/packages/ifpack2/src/Ifpack2_Details_LinearSolverFactory.hpp:2,
                  from
/home/agsalin/Trilinos/packages/ifpack2/src/Ifpack2_Details_registerLinearSolverFactory.cpp:45:
/home/agsalin/Trilinos/packages/tpetra/core/src/Tpetra_Experimental_BlockCrsMatrix_def.hpp:
In lambda function:
/home/agsalin/Trilinos/packages/tpetra/core/src/Tpetra_Experimental_BlockCrsMatrix_def.hpp:1438:31:
internal compiler error: in gimplify_var_or_parm_decl, at gimplify.c:1797
            Kokkos::parallel_for( Kokkos::TeamThreadRange(member,
rowBeg, rowEnd), [&](const LO lclRow) {

**Comment by mhoemmen** [comment]
Commit de880a17890ffb910713eb3890265f307f8c3a69 fixes this.

**Comment by agsalin** [comment]
Mark: Still broken for gcc 5.1. Perhaps this code only works for 4.8.y?

**Comment by mhoemmen** [comment]
@agsalin I tested with GCC 4.9.2.

**Comment by agsalin** [comment]
Can you change the ifdef that kicks in specifically for v<= 4.7 and v=4.9 to apply to versions 5.x as well?  Or, equivalently, for all versions not named 4.8?

**Comment by mhoemmen** [comment]
> Can you change the ifdef that kicks in specifically for v<= 4.7 and v=4.9 to apply to versions 5.x as well? Or, equivalently, for all versions not named 4.8?

I just changed it to skip all GCC versions.  Once #178 is fixed (in progress now), this whole problem will go away.
