### ISSUE TITLE
Framework: Change Autotester Default Behavior When Sub-Tests Fail

### ISSUE THREAD

**Issue by csiefer2** [trilinos/Trilinos#4071]
@trilinos/framework 

Since this is far from the first Intel compiler issue we've had, I propose adding logic to the PR system to have it approve PRs if the Intel compiler dies before reaching configure of Trilinos AND the gcc tests pass.

The logic behind this is to keep non-code Intel compiler fails from creating a "stop the line" condition in  which framework team members need to drop everything and fix the Intel issue du jour.

**Comment by csiefer2** [comment]
Fair enough.  The question I would ask is what works best for the workflow of @trilinos/framework . If you guys are all happy enough with "drop everything and fix it" as opposed to "hope that nobody checks in bad code while you fix it and the hound them if they did" then that's OK.  But I'd like confirmation that the choice is a conscious one :)

**Comment by prwolfe** [comment]
This is not a team policy, but a personal preference, but I would prefer “being attacked by a puma” to “let them break everything and then hound them later”.  If nothing else it means fewer complaining e-mails ;->

Joking aside, patience is the real keyword both from the developers and as a framework team member.  While it seems slower, this system is proven to be faster, warts and all.

-----------------------------------------------------------------------
Recommending policy and creating automation to
enable DevOps in the Trilinos and CTH organizations.
