### ISSUE TITLE
MueLu: migrate HHG driver to Xpetra

### ISSUE THREAD

**Issue by mayrmt** [trilinos/Trilinos#4084]
@trilinos/muelu 

## Expectations
Switch from `Epetra` stack to `Xpetra` (or `Tpetra` if `Xpetra` is to much trouble).

## Current Behavior
The MueLu/HHG driver in `packages/muelu/research/mmayr/composite_to_regions/src/main.cpp` is fully implemented using the old `Epetra` stack.

## Motivation and Context
@lucbv's performance improvements for structured grid's rely on Kokkos. To enable them in the HHG driver, we need to migrate the driver at least to `Tpetra`. Let's try to use `Xpetra` for better MueLu compatibility.

## Definition of Done
- [ ] Completely switch from `Epetra` to `Xpetra` (or `Tpetra` as fall back)
- [ ] Update CMake dependencies accordingly

## Possible Solution
Replace `Epetra` stuff by corresponding `Xpetra` stuff.

**Comment by mayrmt** [comment]
Note to myself: First, migrate everything to Xpetra using the Xpetra_UseShortNames. Later, use specific `typedef Xpetra::Vector<GlobalOrdinal,LocalOrdinal,GlobalOrdinal,node> VectorGO;` for those vectors that just store GIDs as their entries.

**Comment by mayrmt** [comment]
@lucbv During creation of the region matrices, there's a point where I have a quasiRegion matrix, i.e. values have already been splitted and GIDs at the interface have been duplicated (but are not unique). This has to be transformed into a true region matrix, i.e. with the same entries but different row/col/range/domain maps, namely with unique maps where we replace one of each duplicated GID with a new GID. I can't convert the Epetra implementation straightforwardly into Xpetra as Xpetra does not provide the same routines. Do you have an idea how I could achieve this?

You can find the current Epetra-based implementation [here](https://github.com/trilinos/Trilinos/blob/f6e61209c6316c0a7b34cd18d525d5299887384a/packages/muelu/research/mmayr/composite_to_regions/src/main.cpp#L1593).

**Comment by lucbv** [comment]
@mayrmt here is an approach that will allow you to do what you want (I think):
```
regionGrpMats[j] = rcp(new CrsMatrixWrap(*(revisedRowMapPerGrp[j]), *(revisedColMapPerGrp[j]) 0, Xpetra::StaticProfile));

// Extract current region CrsMatrix
RCP<CrsMatrix> regionCrsMat = rcp_dynamic_cast<CrsMatrixWrap>(regionGrpMats[j])->getCrsMatrix();

// Extract current quasi-region CrsMatrix
RCP<CrsMatrix> quasiRegionCrsMat = rcp_dynamic_cast<CrsMatrixWrap>(quasiRegionGrpMats[j])->getCrsMatrix();

// Pull out the data from the quasi-region CrsMatrix
ArrayRCP<const size_t> rowptrQuasiRegion;
ArrayRCP<const LocalOrdinal> colindQuasiRegion;
ArrayRCP<const Scalar> valuesQuasiRegion;
quasiRegionCrsMat->getAllValues(rowptrQuasiRegion, colindQuasiRegion, valuesQuasiRegion);

// Do a deep copy of values
// (at least you've been doing deep copies so far, maybe we could do shallow copies to save time?)
const ArrayRCP<size_t> rowptrRegion(rowptrQuasiRegion.size());
const ArrayRCP<LocalOrdinal> colindRegion(colindQuasiRegion.size());
const ArrayRCP<Scalar> valuesRegion(valuesQuasiRegion.size());

for(LO idx = 0; idx < static_cast<LO>(rowptrRegion.size()); ++idx) {
  rowptrRegion[idx] = rowptrQuasiRegion[idx];
}

for(LO idx = 0; idx < static_cast<LO>(colindRegion.size()); ++idx) {
  colindRegion[idx] = colindQuasiRegion[idx];
  valuesRegion[idx] = valuesQuasiRegion[idx];
}

// Set and fillComplete the region CrsMatrix
regionCrsMat->setAllValues(rowptrRegion, colindRegion, valuesRegion);
regionCrsMat->expertStaticFillComplete(*(revisedRowMapPerGrp[j]),*(revisedRowMapPerGrp[j]));
```

At least something along these lines should do the trick, I have not tested this so there might be some syntax and logic to clean-up...
Let me know if that looks good?

**Comment by mayrmt** [comment]
@lucbv I didn't think about the `CrsMatrixWrap`. That should do the trick. 

So far, I have used deep copies since I wasn't concerned with performance at all. I'll keep this in mind and address it once the Xpetra version works.

**Comment by mayrmt** [comment]
@lucbv after #4202/#4419, we have to address #4193.

**Comment by mayrmt** [comment]
@lucbv @pohm01 @rstumin Just a brief udpate: To complete the migration to Xpetra, I just have to figure out a solution to #4193. I'm working on this right now.

**Comment by mayrmt** [comment]
@lucbv Right now, I'm only missing the coarse level solver. In the old Epetra implementation, I've been using Amesos directly. How can I handle such a situation in Xpetra? I could either call Amesos or Amesos2 depending on `Xpetra::UnderlyingLib`, though I'm not sure whether that's a great idea. Any recommendations?

**Comment by lucbv** [comment]
@mayrmt if you look in `packages/muelu/src/Smoothers/MueLu_DirectSolver_{decl,def}.hpp` you will see that the way we handle this is a manual selection of Amesos/Amesos2. I am suspecting that there is not a much better approach at this point.

You could create a smoother or direct solver the way we do it in the unit-tests and hopefully this will take care of things for you under the hood...

**Comment by lucbv** [comment]
@mayrmt I have pushed a new commit that includes the split between `driver.cpp` and `SetupRegionHierarchy_def.hpp`.
I think that the new header contains everything needed to run the region MG algorithm. We should be able to include it in the new 3D driver and get it to work as long as we can interface it correctly.

Also the previous commit formalized the idea of a function pointer associated with `LIDregion`, this should make our requirements clearer, although I believe that we might move away from the function pointer soon enough.

**Comment by mayrmt** [comment]
@lucbv I'll move the code that reads the Matlab-generated region data from files to a separate file `HHG_read_from_file_def.hpp`. That's just intended to be a utility file to handle the Matlab-data.
