### ISSUE TITLE
Many deprecated warnings for the deprecated class Ifpack2::Krylov

### ISSUE THREAD

**Issue by nschloe** [trilinos/Trilinos#409]
When compiling Trilinos, I'm getting more than one thousand (!) warnings of the kind
```
/«PKGBUILDDIR»/packages/ifpack2/src/Ifpack2_Krylov_decl.hpp:280:19: warning: ‘template<class MatrixType> class Ifpack2::Krylov’ is deprecated [-Wdeprecated-declarations]
     Krylov (const Krylov<MatrixType>& RHS);
                   ^
In file included from /«PKGBUILDDIR»/obj-x86_64-linux-gnu/packages/ifpack2/src/Ifpack2_Krylov.hpp:1:0,
                 from /«PKGBUILDDIR»/packages/stokhos/src/sacado/kokkos/vector/ifpack2/Ifpack2_Krylov_MP_Vector.hpp:52,
                 from /«PKGBUILDDIR»/packages/stokhos/src/sacado/kokkos/vector/ifpack2/Stokhos_Ifpack2_MP_Vector.hpp:50,
                 from /«PKGBUILDDIR»/obj-x86_64-linux-gnu/packages/stokhos/src/Ifpack2_Diagonal_MP_Vector_Serial.cpp:48:
/«PKGBUILDDIR»/packages/ifpack2/src/Ifpack2_Krylov_decl.hpp:95:28: note: declared here
   class IFPACK2_DEPRECATED Krylov :
                            ^
```
The deprecating commit is
```
commit f45616d794c95455bf15abd859b1aefdec2710b3
Author: Mark Hoemmen <mhoemme@sandia.gov>
Date:   Thu Aug 13 13:28:55 2015 -0600

    Ifpack2::Krylov: Deprecated.

    There's no need for Ifpack2 to implement Krylov methods.  Belos does a
    fine job of this.  Furthermore, the LinearSolverFactory will make such
    duplication of functionality unnecessary and obsolete.
    
    Ifpack2::Factory, and other implementation-level factories in Ifpack2,
    no longer create instances of Ifpack2::Krylov.  Instead, they throw an
    exception with an informative message.  They no longer include
    Ifpack2::Krylov header files.  The header files still exist, but are
    heavily marked as deprecated.  The class itself uses the deprecated
    macro.
```
so this is nearly a year old. Time to scratch `Ifpack2_Krylov_decl.hpp`?

**Comment by mhoemmen** [comment]
I think you're right.  I didn't find any uses of Ifpack2::Krylov outside of Ifpack2 itself.  Main customer is @trilinos/muelu so I'll check with them: Hey @jhux2, @tawiesn, @aprokop, @csiefer2 , can we get rid of this?

**Comment by jhux2** [comment]
> I think you're right. I didn't find any uses of Ifpack2::Krylov outside of Ifpack2 itself. Main customer is @trilinos/muelu so I'll check with them: Hey @jhux2, @tawiesn, @aprokop, @csiefer2 , can we get rid of this?

An internal user has requested that we not remove this class.   Options that I see are:

1) Ignore the deprecated warnings.
2) Compile with deprecated warnings turned off.
3) Undeprecate the class.

**Comment by nschloe** [comment]
I believe the classes have been deprecated because Krylov methods are very well implemented in Belos. My guess is that said user could benefit from that, too. Promoting an upgrade path to Belos might be worthwhile.

If we'd like to continue to support Ifpack2::Krylov, then removing the deprecation message is in order. (It does seem wasteful though to actually do that.)

**Comment by mhoemmen** [comment]
> An internal user has requested that we not remove this class. 

@jhux2 , good to know.  Would they object if we moved the class into a different namespace, like Ifpack2::Deprecated::Krylov ?

**Comment by jhux2** [comment]
> @jhux2 , good to know. Would they object if we moved the class into a different namespace, like Ifpack2::Deprecated::Krylov ?

I think that would be fine, and solve Nico's issue to boot.

**Comment by mhoemmen** [comment]
> I think that would be fine, and solve Nico's issue to boot.

Oh, I wasn't planning on removing the "deprecated" macro ;-) but if that would help, we could do that.

**Comment by mhoemmen** [comment]
@jhux2 @nschloe Ok, what do we want to do?  Do we want to move the class into the Ifpack2::Deprecated namespace _and_ remove the IFPACK2_DEPRECATED macro?

**Comment by jhux2** [comment]
> @jhux2 @nschloe Ok, what do we want to do? Do we want to move the class into the Ifpack2::Deprecated namespace and remove the IFPACK2_DEPRECATED macro?

Moving the class into the Ifpack2::Deprecated namespace for sure.   To avoid the warnings Nico mentions, a possibility is keeping IFPACK2_DEPRECATED in Ifpack2::Deprecated::Krylov class, but only build that class if the user explicitly asks for it, e.g., with a cmake option like -DIfpack2_EnableDeprecatedNamespace.  Comments?

**Comment by mhoemmen** [comment]
@jhux2 Only one customer wants the thing.  I would say, let's ask them to set the following CMake option:
```
Ifpack2_SHOW_DEPRECATED_WARNINGS:BOOL=OFF
```
This selectively disables Ifpack2 deprecated warnings.  @nschloe , is that an option for you too?

**Comment by nschloe** [comment]
I like @jhux2's approach of
```
Ifpack2_EnableDeprecatedNamespace:BOOL=ON
```
(`OFF` by default). In a vanilla build, this removes the warnings and also discourages other customers from using the interface.

**Comment by mhoemmen** [comment]
I'm moving this into the Ifpack2::DeprecatedAndMayDisappearAtAnyTime namespace.  It comes with the following documentation:
```
  /// \namespace DeprecatedAndMayDisappearAtAnyTime
  /// \brief Ifpack2 features that have been DEPRECATED and may
  ///   DISAPPEAR AT ANY TIME.  USE AT YOUR OWN RISK.
  ///
  /// This namespace only exists because some users insist on certain
  /// classes continuing to exist, even though they have been
  /// deprecated for a long time.  This inconveniences other users,
  /// who have to endure lots of deprecated warnings just because of
  /// those people who don't respect our backwards compatibility
  /// rules.  The rule is that, if I deprecate something no later than
  /// version x.y, where y is no later than the second-to-last minor
  /// release before (x+1).0, then I get to remove it in (x+1).0.
  namespace DeprecatedAndMayDisappearAtAnyTime {}
```

**Comment by mhoemmen** [comment]
Running check-in tests now.

**Comment by mhoemmen** [comment]
Just pushed the following changes:

  1. Moved `Ifpack2::Krylov` to the `Ifpack2::DeprecatedAndMayDisappearAtAnyTime` namespace
  2. Documented `Ifpack2::DeprecatedAndMayDisappearAtAnyTime` namespace as deprecated
  3. `Ifpack2::DeprecatedAndMayDisappearAtAnyTime::Krylov` no longer exists or builds by default.  If you want it, you must enable it at configure time by setting the CMake option `Ifpack2_ENABLE_DEPRECATED_CODE:BOOL=ON`.
