### ISSUE TITLE
MueLu: detect if input matrix is identity

### ISSUE THREAD

**Issue by jhux2** [trilinos/Trilinos#4093]
A user recently tried to run MueLu on an identity matrix.  For a large enough system, MueLu will coarsen to a zero-by-zero system, which causes problems.  There should be a mechanism for detecting if all DOFs are boundary points, i.e., there are zero aggregates.  One solution is to throw an exception during Dirichlet detection.

**Comment by csiefer2** [comment]
This situation could also occur with overly aggressive dropping...

**Comment by GrahamBenHarper** [comment]
This should be covered by Dirichlet detection, right?

**Comment by jhux2** [comment]
> This should be covered by Dirichlet detection, right?

Actually, no.  Dirichlet detection just flags rows.

**Comment by jhux2** [comment]
Fixed by #11576.
