### ISSUE TITLE
Tpetra: Build errors with complex enabled

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#4094]
@trilinos/tpetra 

When I enable `Scalar=complex<double>` in Tpetra with GCC 4.9.3 (debug build) and OpenMP, I get build errors that look like build errors currently on the Dashboard:

https://testing.sandia.gov/cdash/viewBuildError.php?buildid=4326483
```
.../Trilinos/packages/tpetra/core/src/kokkos_refactor/Tpetra_KokkosRefactor_Details_MultiVectorDistObjectKernels.hpp:755:39: error: no matching function for call to ‘atomic_fetch_oper(Tpetra::KokkosRefactor::Details::AbsMaxOper<Kokkos::complex<double>, Kokkos::complex<double> >, Kokkos::complex<double>*, const Kokkos::complex<double>&)’
       Kokkos::Impl::atomic_fetch_oper (AbsMaxOper<Scalar,Scalar>(), &dest, src);
```

## Possible Solution

Fix https://github.com/kokkos/kokkos/issues/1951 .

## Related Issues
* Is blocked by https://github.com/kokkos/kokkos/issues/1951

**Comment by ndellingwood** [comment]
Related - #4095

**Comment by mhoemmen** [comment]
@ndellingwood @crtrott Here is the corresponding Kokkos PR: https://github.com/kokkos/kokkos/pull/1953
