### ISSUE TITLE
Tpetra::CrsMatrix::getLocalDiagCopy: Kokkos-parallelize diagonal extraction

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#41]
@trilinos/tpetra Performance tests with Nalu discovered that Ifpack2::Relaxation Jacobi setup had a sequential section in CrsMatrix::getLocalDiagCopy (the two-argument version, though it's easy enough to optimize the one-argument version too).  Nalu developers experimented with putting a parallel_for loop around diagonal extraction in getLocalDiagCopy, and it worked great.

**Comment by mhoemmen** [comment]
It's OK to make this a host execution space loop; then we can use a lambda.

**Comment by crtrott** [comment]
I made it parallel on the host (i.e. with GPUs it still copies it still syncs the data to the host and runs the loop there).

**Comment by mhoemmen** [comment]
I think that's OK for now.  Making it GPU-parallel would require either making Tpetra's interface device-friendly, or talking directly to the KokkosSparse::CrsMatrix.  Thanks Christian!  Is that the two-argument version?

**Comment by crtrott** [comment]
Yes this is the two argument version. That is why I left the ticket open.

**Comment by etphipp** [comment]
Is this code thread-safe?  I am getting random seg faults in the RCPNodeHandle destructor from inside the lambda when I use the OpenMP execution space with more than one thread, so I don't believe it is.

Internally it appears to be using RCP's in a few places:

* getLocalRowView() internally calls getRowMap(), which returns an RCP.
* In a debug build ArrayView internally uses ArrayRCP.

**Comment by crtrott** [comment]
Ah the joy of not having sufficient threaded unit testing. Let me look into it. 

Christian

**Comment by crtrott** [comment]
I am working on that right now. It probably explains a couple of occasional non-determinstic crashes in Nalu I have seen.

**Comment by crtrott** [comment]
Pushed a fix.

**Comment by mhoemmen** [comment]
Argh, sorry folks.  I'm in the middle of debugging some possible issues with Tpetra::BlockCrsMatrix::getLocalDiagOffsets.

mfh

On 12/14/15, 9:45 AM, "etphipp" <notifications@github.com<mailto:notifications@github.com>> wrote:


Is this code thread-safe? I am getting random seg faults in the RCPNodeHandle destructor from inside the lambda when I use the OpenMP execution space with more than one thread, so I don't believe it is.

Internally it appears to be using RCP's in a few places:

  *   getLocalRowView() internally calls getRowMap(), which returns an RCP.
  *   In a debug build ArrayView internally uses ArrayRCP.

-

**Comment by crtrott** [comment]
As I said I think I fixed it already, just waiting for Eric to confirm.

**Comment by etphipp** [comment]
Yes, it appears to work now.  Thanks.

**Comment by mhoemmen** [comment]
One-argument `getLocalDiagCopy` is not yet thread parallel.  It uses `CrsMatrix::getView`, a nonpublic method which returns a `Teuchos::ArrayView` of the entries in a row.  `Teuchos::ArrayView` is not thread safe in a debug build (`Teuchos_ENABLE_DEBUG=ON`).  Thus, we have to fix this before we can make the method thread parallel.

**Comment by mhoemmen** [comment]
Current status: both 1-argument and 2-argument getLocalDiagCopy, and getLocalDiagOffsets, are both thread-parallel, using the host execution space.  Next step is execution on the CUDA device if appropriate to the current storage status.

**Comment by mhoemmen** [comment]
I just renamed this from "Thread-parallelize" to "Kokkos-parallelize."  The code already uses the host execution space (e.g., OpenMP) for parallelization; we just need to turn the existing lambda into a functor and take a few other measures to make this work with CUDA as well.

**Comment by mhoemmen** [comment]
Discussion continues on the following pull request: https://github.com/crtrott/Trilinos/pull/3

**Comment by mhoemmen** [comment]
@amklinv -- please refer to my most recent comments on your pull request: https://github.com/crtrott/Trilinos/pull/3

In particular, #205 only blocks Kokkos-ization of one-argument getLocalDiagCopy.  Ifpack2 only cares deeply about two-argument getLocalDiagCopy, which is a lot easier.  You'll still need two code paths, depending on whether the matrix is fillComplete. If it's not, just use the existing code path, with its host execution space parallelization. If it is fillComplete, write a device functor that gets the `KokkosSparse::CrsMatrix` out and works on that. Remember that offsets are relative to each row, not absolute over the whole matrix.  `KokkosSparse::CrsMatrix` has a clever row view thing that you can pretend is an unmanaged Kokkos::View (implements `operator()`).

**Comment by mhoemmen** [comment]
@amklinv -- please refer to my latest patches for #212.  This should serve as a model for full Kokkos-ization of two-argument (and indeed one-argument) getLocalDiagCopy.

**Comment by mhoemmen** [comment]
Note that I did push those patches to fix #212.

**Comment by mhoemmen** [comment]
Note that Tpetra::Experimental::BlockCrsMatrix::getLocalDiagCopy (the 2-argument Kokkos::View version) currently runs in the host execution space.  This is partly because it uses a lambda (which requires a new CUDA version with a special flag) and partly because the lambda in question calls BlockCrsMatrix methods that aren't marked as device functions.  Just marking the methods as device functions won't work, because that won't correctly capture `*this` (that issue will get fixed in the C++17 standard, I think).  Thus, the right fix for now is to write a functor that takes all the necessary state from BlockCrsMatrix.

**Comment by mhoemmen** [comment]
Fixed by a commit on 12 May 2016.  Not sure why this got so mixed up with BCRS.
