### ISSUE TITLE
Thyra, Belos: Closing old PR #1144 "Mod in Thyra_BelosLinearOpWithSolve: separating ..."

### ISSUE THREAD

**Issue by william76** [trilinos/Trilinos#4108]
@trilinos/belos 
@trilinos/thyra 

Pull Request #1144 "Mod in Thyra_BelosLinearOpWithSolve: separating..." is really old and appears to be stale and/or abandoned.  I'm closing that PR and creating this issue to link to it. 

I'm doing this because we need to close out some of the old PR's due to some GitHub limitations on the number of checks/hour that are allowed.  The pull request autotester uses a polling model to check existing pull requests' status flags, etc. and we have occasionally hit that limit, which causes GitHub to reject the queries and can cause the Autotester to fail on a PR. If this PR needs to be brought back to life it can easily be reopened on the pull request page.

If this PR is truly dead, please close out this issue ticket.

FYI: @bartgol @mhoemmen @jwillenbring

**Comment by mhoemmen** [comment]
@william76 If the PR is labeled as a WIP, does that still count in the polling limit, as long as the autotester filters the search by label?
