### ISSUE TITLE
Tpetra: Closing old PR #1930: "Fix #1925"

### ISSUE THREAD

**Issue by william76** [trilinos/Trilinos#4112]
@trilinos/pliris

Pull Request #1930 "Fix #1925" is really old and appears to be stale and/or abandoned.  I'm closing that PR and creating this issue to link to it. 

I'm doing this because we need to close out some of the old PR's due to some GitHub limitations on the number of checks/hour that are allowed.  The pull request autotester uses a polling model to check existing pull requests' status flags, etc. and we have occasionally hit that limit, which causes GitHub to reject the queries and can cause the Autotester to fail until the counter resets at the start of the next hour. If this PR needs to be brought back to life it can easily be reopened on the pull request page.

If this PR is truly dead, please close out this issue ticket.

FYI: @mhoemmen

**Comment by mhoemmen** [comment]
@william76 I wouldn't call the PR "dead," but it has merge conflicts and is known to make a test fail.  It's useful as a reference, but closed PRs don't disappear.  So, I'm closing this issue.  Thanks!
