### ISSUE TITLE
MueLu: Closing old PR #2136 "uncoupled aggregation refactor"

### ISSUE THREAD

**Issue by william76** [trilinos/Trilinos#4113]
@trilinos/muelu 

Pull Request #2136 "uncoupled aggregation refactor" is really old and appears to be stale and/or abandoned.  I'm closing that PR and creating this issue to link to it. 

I'm doing this because we need to close out some of the old PR's due to some GitHub limitations on the number of checks/hour that are allowed.  The pull request autotester uses a polling model to check existing pull requests' status flags, etc. and we have occasionally hit that limit, which causes GitHub to reject the queries and can cause the Autotester to fail until the counter resets at the start of the next hour. If this PR needs to be brought back to life it can easily be reopened on the pull request page.

If this PR is truly dead, please close out this issue ticket.

FYI: @lucbv @jhux2 @srajama1

**Comment by lucbv** [comment]
I am closing this as I am reopening an issue for uncoupled aggregation and the amalgamation process here: #5838
