### ISSUE TITLE
PanzerAdaptersSTK_MixedCurlLaplacianExample-ConvTest-Tri-Order-1 timing out in Trilinos-atdm-white-ride-cuda-9.2-release-debug builds starting 12/19/2018

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#4116]
CC: @trilinos/panzer , @mperego (Trilinos Discretizations Product Lead), @bartlettroscoe, @fryeguy52

<Checklist>
<???: Once GitHub Issue is created, add entries for tests to TrilinosATDMStatus/*.csv files>

## Next Action Status

As shown in [this query](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercombine=and&filtercombine=and&filtercount=4&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-release-debug&field2=testname&compare2=61&value2=PanzerAdaptersSTK_MixedCurlLaplacianExample-ConvTest-Tri-Order-1&field3=site&compare3=61&value3=white&field4=buildstarttime&compare4=83&value4=2018-12-20), this test has not timed out at all since 12/20/2018 when this issue was first opened. (NOTE: The failure on 2019-01-11 was part of a strange set of segfaults that impacted a bunch of tests in this build and was likely not related.)

## Description

As shown in [this query](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-white-ride-cuda-9.2-release-debug&field2=testname&compare2=61&value2=PanzerAdaptersSTK_MixedCurlLaplacianExample-ConvTest-Tri-Order-1&field3=buildstarttime&compare3=83&value3=2018-12-15) the test:

* `PanzerAdaptersSTK_MixedCurlLaplacianExample-ConvTest-Tri-Order-1`

is timing out in the builds:

* `Trilinos-atdm-white-ride-cuda-9.2-release-debug`
* `Trilinos-atdm-white-ride-cuda-9.2-release-debug-pt`

on 'white' and 'ride' starting on 12/19/2018 (where is before was not even running in that build before that).

The new commits that were pulled the day that these timeouts started are show [here](https://testing.sandia.gov/cdash/viewNotes.php?buildid=4325408#!#note0).  Seems like the commit 97efcbc from @fryeguy52 merged into 'develop' in PR #4079 is the trigger for this.  Before commit 97efcbc, this test was disabled in all CUDA builds.  After commit 97efcbc, this test is disabled only in the build `Trilinos-atdm-waterman-cuda-9.2-release-debug`.

## Current Status on CDash

The current status of this test or the current testing day can be found at [here](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-white-ride-cuda-9.2-release-debug&field2=testname&compare2=61&value2=PanzerAdaptersSTK_MixedCurlLaplacianExample-ConvTest-Tri-Order-1).

## Steps to Reproduce

One should be able to reproduce this failure on the machine 'white' or 'ride' as described in:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md

More specifically, the commands given for the system 'white' or 'ride' are provided at:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#ridewhite

The exact commands to reproduce this issue should be:

```
$ cd <some_build_dir>/

$ source $TRILINOS_DIR/cmake/std/atdm/load-env.sh Trilinos-atdm-white-ride-cuda-9.2-release-debug

$ cmake \
 -GNinja \
 -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
 -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_Panzer=ON \
 $TRILINOS_DIR

$ make NP=16

$ bsub -x -Is -q rhel7F -n 16 ctest -j16
```

**Comment by bartlettroscoe** [comment]
@rppawlo, since this test is disabled in the build `Trilinos-atdm-waterman-cuda-9.2-release-debug` and since it is running and passing today and yesterday in the build `Trilinos-atdm-waterman-cuda-9.2-opt` as shown [here](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=4&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-&field2=buildname&compare2=63&value2=cuda&field3=testname&compare3=61&value3=PanzerAdaptersSTK_MixedCurlLaplacianExample-ConvTest-Tri-Order-1&field4=buildstarttime&compare4=83&value4=2018-12-15), can we go ahead and disable this timing out test in this build `Trilinos-atdm-white-ride-cuda-9.2-release-debug`?

**Comment by rppawlo** [comment]
Sure!
