### ISSUE TITLE
Teuchos: StackedTimer missing a pushRegion for kokkos profiling

### ISSUE THREAD

**Issue by jewatkins** [trilinos/Trilinos#4119]
@trilinos/teuchos

## Expectations

StackedTimer should work with kokkos profiling tools

## Current Behavior

space time stack throws a seg fault because there's no pushRegion in the top level timer

## Motivation and Context

Removing the stacked timer or changing the kokkos profiler to run a profile is not practical. It's better to fix the stacked timer.

## Possible Solution

Unless I'm mistaken, it's currently only possible to start the top level timer via the constructor of StackedTimer. Either the constructor needs a pushRegion or the user should be able to start the top level timer explicitly (start() has a pushRegion).

## Steps to Reproduce

I think any code with the stacked timer should segfault if run with kokkos profiling tools

**Comment by mhoemmen** [comment]
@trilinos/teuchos

**Comment by rppawlo** [comment]
@jewatkins - can you verify this is fixed?

**Comment by jewatkins** [comment]
Yes, it's working now. Thanks!
