### ISSUE TITLE
Amesos2 and SuperLU_Dist_4.2, incompatibility when _LONGINT is used

### ISSUE THREAD

**Issue by mjuha** [trilinos/Trilinos#413]
Dear developers,

I recently compiled Amesos2 with enable TPL SuperLU_Dist_4.2. For my surprise, there is a problem with compatibility when I activate _LONGINT in SuperLU_DIST_4.2 for indexing global indices. SuperLU_Dist_4.2 assign a 64 bit to the variable int_t, but Amesos2 instantiate the same variable to a 32 bits. Next I specified the _LONGINT definition in the CMAKE_CXX_FLAG of the configuration script of trilinos. In that case int_t is assigned as 64 bits. Then there is an incompatibility with some functions, because they expect a pointer to an integer instead of a pointer to an int_t. A clear example is found in this line:

https://github.com/trilinos/Trilinos/blob/master/packages/amesos2/src/Amesos2_Superludist_FunctionMap.hpp#L265

Am I doing something wrong?

Thank you,

Mario J. Juha

**Comment by jhux2** [comment]
@trilinos/amesos2

**Comment by srajama1** [comment]
Glen Hansen offered to help you with respect to Albany configure, but this points to a broader issue of supporting _LONGINT of Superlu_Dist in Amesos2. It is possible to do this with TypeMap and from the e-mail thread it appears you are progressing towards that with changes already in place. If you can submit a pull request once the configure issues are resolved, I can take a look at it. If it is not just configure and you still face problems from Amesos2 let us know.

**Comment by mjuha** [comment]
Hi,
I found many problems compiling Amesos2 with SuperLU_DIST_4.2 and _LONGINT. So I changed the version and all the integers are indexed using a 32-bits (int) instead of the 64-bits (long long int). Then, it works okay.

-- Mario
