### ISSUE TITLE
Intrepid2: improve performance of LagrangianInterpolation 

### ISSUE THREAD

**Issue by rppawlo** [trilinos/Trilinos#4141]
An application is using the function `Intrepid2::Experimental::LagrangianInterpolation<DeviceSpace>::getDofCoordsAndCoeffs`. The function is not optimized to use kokkos and is causing scaling issues for large problems. 

@trilinos/intrepid2 
@mperego 
@bathmatt

**Comment by mperego** [comment]
I think this was addressed by PR #5431.
