### ISSUE TITLE
Tpetra: In-place conversion from BlockMultiVector to BlockVector

### ISSUE THREAD

**Issue by wfspotz** [trilinos/Trilinos#4143]
@trilinos/tpetra

## Expectations
Given a `Tpetra::BlockMultiVector`, it should be possible to extract a const or non-const `Tpetra::BlockVector` with view semantics.

The `Tpetra::MultiVector` class has `getVector()` and `getVectorNonConst()` methods, but no `operator()` or `operator[]` operators.  The `Tpetra::BlockMultiVector` interface should mimic the `Tpetra::MultiVector` interface with `getBlockVector()` and `getBlockVectorNonConst()` methods.

## Current Behavior
There are currently no methods or operators to do this.

## Motivation and Context
In SPARC, I am trying to add support for `LINSYS_TPETRA_BLOCK_CRS` linear systems with the `NonlinearSolverNox` solver.  The conversion from the SPARC type `VectorTpetraBlock` to a `Thyra::Vector` for the NOX ModelEvaluator solver requires this capability.

## Definition of Done                                                   
- [x] Develop tests for `BlockVector` constructor that takes a `Tpetra::Vector` as an argument
- [x] Implement new `BlockVector` constructor
- [x] Verify that tests of new constructor work as expected
- [ ] Develop tests for `Thyra::createVector()` factory function that takes a `Tpetra::BlockMultiVector`
- [ ] Implement new `Thyra::createVector()` factory function
- [ ] Verify that tests of new factory function work as expected

**Comment by wfspotz** [comment]
@mhoemmen I don't see much testing of the `BlockVector` class.  Just some usage in `BlockCrsMatrix.cpp`.  How would you like to proceed with testing of the new `BlockVector` constructor?

**Comment by wfspotz** [comment]
@mhoemmen Actually, I see the following constructor:

    BlockVector (const mv_type& X_mv,
                 const map_type& meshMap,
                 const LO blockSize);

`mv_type` is a `Tpetra::MultiVector`, which should accept a `Tpetra::Vector`.  Is there any reason to believe this wouldn't work?

**Comment by mhoemmen** [comment]
@wfspotz I would prefer for BlockVector's constructor to take a `Tpetra::Vector`.  That way, it has one column by construction.  The result of getVector and getVectorNonConst is a `Tpetra::Vector`, so that should be what you need.  Do you actually need this to take a MultiVector?

**Comment by wfspotz** [comment]
@mhoemmen No, I do not need it to take a `MultiVector`.

**Comment by wfspotz** [comment]
@mhoemmen The current `MultiVector` constructor throws if `getNumVectors() != 1`.

**Comment by mhoemmen** [comment]
@wfspotz Cool :-) So, is the desired feature then the following?
```c++
BlockVector (const Tpetra::Vector<...>& X_vec, const map_type& meshMap, const LO blockSize);
```

**Comment by wfspotz** [comment]
@mhoemmen Or

    BlockVector (const vec_type& X_vec, const map_type& meshMap, const LO blockSize);

**Comment by wfspotz** [comment]
@mhoemmen I have a feature branch with this new constructor implemented.  It was pretty straightforward.  It is not tested, but then most `BlockVector` constructors, methods and operators are not tested.  Do you think we should implement a Tpetra test, or implement a test of the Thyra use case?

**Comment by mhoemmen** [comment]
@wfspotz It would be nice to have a Tpetra test that constructs a BlockVector from the result of MultiVector::getVector, then gets the (Multi)Vector out of the BlockVector and makes sure the pointers are the same.  If you're too busy, though, please do the Thyra use case first.  Thanks!

**Comment by mhoemmen** [comment]
@wfspotz Could you just add this to one of the relevant .cpp files in `Trilinos/packages/tpetra/core/test/Block/`?  Thanks!
