### ISSUE TITLE
Remove Kokkos_ENABLE_Profiling=OFF from current ATDM Trilinos configuration?

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#4148]
CC: @bathmatt, @micahahoward, @fryeguy52, @rppawlo, @mhoemmen 

The current ATDM Trilinos configuration sets `Kokkos_ENABLE_Profiling=OFF` which was copied from the EMPIRE Trilinos configuration.  This resulted in code passing the Trilinos PR builds (which all have the default `Kokkos_ENABLE_Profiling=ON`) but failing in all of the ATDM Trilinos builds (see #4145 and #4146).

This Story is to inquire if we can remove `Kokkos_ENABLE_Profiling=OFF` from the ATDM Trilinos configuration (or document why it needs to be kept).

**Comment by bartlettroscoe** [comment]
CC: @micahahoward, @fryeguy52, @mhoemmen 

@bathmatt and @rppawlo,

Note that non of the native SPARC Trilinos configurations currently set `Kokkos_ENABLE_Profiling=OFF` which means that Kokkos profiling must be on by default for all SPARC builds with Trilinos.

Why does EMPIRE set `Kokkos_ENABLE_Profiling=OFF`?  Can we try removing this option and see what happens?

Removing this option will help with the stability of that ATDM Trilinos builds since the Trilinos PR builds with match and protect them better.

**Comment by mhoemmen** [comment]
In particular, if there is any rumor of Kokkos profiling having too much overhead (even when not actually using a profiling library), we want to know about it, so we can fix it at the Kokkos level.  Kokkos profiling is meant to be low overhead, at least when not actively in use (i.e., when not running with a profiling library).

**Comment by bartlettroscoe** [comment]
In https://github.com/trilinos/Trilinos/issues/4190#issuecomment-454376271 @rppawlo said:

> Last week we cleaned up the interaction between the StackedTimer and kokkos profiling (#4119). StackedTimers and TimeMonitors all feed into kokkos profiling. All panzer, EMPIRE and Drekar tests were passing with profiling on. So this should hopefully be a simple configure change.

So we have  EMPIRE approval to remove the option `Kokkos_ENABLE_Profiling=ON` from the ATDM Trilinos configuration?

**Comment by rppawlo** [comment]
yes - we have approval.

**Comment by mhoemmen** [comment]
@rrdrake

**Comment by bartlettroscoe** [comment]
I added this to our out [WIP backlog](https://snl-wiki.sandia.gov/pages/viewpage.action?pageId=341516978).

**Comment by crtrott** [comment]
Note that Empire turns this now also on. So the only people not turning it on are the folks who are trying to reproduce whats happening in Empire and SPARC without building the apps, and just doing it inside Trilinos.

**Comment by nmhamster** [comment]
Confusing - is the default that profiling is enabled or disabled? The overhead should be very small to zero, allowing it to always be enabled.

**Comment by bartlettroscoe** [comment]
Okay, I will create a branch to turn on profiling by default and run a few trial builds on a couple of machines and make sure we don't see a bunch of new test failures (or if we do, that is good?)

**Comment by crtrott** [comment]
As long as you don't load a tool (by setting the env variable KOKKOS_PROFILE_LIBRARY) this should do practically nothing.

**Comment by bartlettroscoe** [comment]
This has been done for a long time and both EMPIRE and SPARC have had several updates of Trilinos since then.  If there was a problem related this, I would have heard about it.

Closing as complete.
