### ISSUE TITLE
Tpetra: Objects that return a Kokkos::View of the data should return it unmanaged

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#415]
@trilinos/tpetra As discussed in the Kokkos / Tpetra developers' meeting yesterday (Wed 01 Jun 2016), all Tpetra objects that return a Kokkos::View of their data should return it unmanaged.  This lets TPLs manage data if they need to, and also avoids awkward situations where data persist beyond their owning object's lifetime.

**Comment by tawiesn** [comment]
This would make Tpetra consistent with the behavior of Xpetra, too. Xpetra already returns the underlying Kokkos objects as an unmanaged view. This was necessary in order to provide a Kokkos emulation layer for the Epetra stack in Xpetra.
