### ISSUE TITLE
Using magnitudeType for coordinates in MueLu

### ISSUE THREAD

**Issue by etphipp** [trilinos/Trilinos#4150]
@trilinos/muelu @kliegeois 

MueLu developers,

I have a student, @kliegeois, working on a modification of one of Stokhos' scalar types that changes Teuchos::ScalarTraits::magnitudeType to something other than a builtin type, and we are running into many issues in MueLu, where magnitudeType is feely converted to/from double.  The issue seems to be that the interface for mesh coordinates takes vectors of magnitudeType, but the implementation often assigns these values to double types.  We started converting most of this code to use magnitudeType throughout, but this is becoming untenable and we are wondering what the right path forward is.  

It seems to me that using magnitudeType for coordinates is something of an abuse of what magnitudeType is supposed to represent, since it is supposed to represent magnitudes (i.e., real, non-negative numbers).  What would you think of introducing a new type trait for coordinates that would compute the coordinate type from the scalar type, but be divorced from magnitudeType?  This could be done using Teuchos::ScalarTraits (e.g., Teuchos::ScalarTraits::coordinateType), or MueLu could introduce its own trait, something like:
```
// Default implementation where CoordinateTraits<Scalar>::type == Scalar
template <class Scalar>
struct CoordinateTraits {
  typedef Scalar type;
};

// Specialization for std::complex<>
template <class T> {
struct CoordinateTraits< std::complex<T> > {
  typedef T type;
};
```
Then Stokhos would then provide its own specialization where CoordinateTraits<>::type is a builtin type.

To me, this seems like the right way to do this.  If someone wanted to use, e.g., extended precision types, then magnitudeType would be extended precision (and therefore not safely convertible to double), but it seems very unlikely that anyone would want the coordinate type to be extended precision.

**Comment by lucbv** [comment]
@etphipp, this sounds like a good suggestion. We have been slowly moving away from using the `double` type for coordinates since we quickly run into trouble when a `Scalar` is instantiated with `float`, even more so with `std::complex<float>`.

**Comment by jhux2** [comment]
@etphipp This is a good idea, thanks for the suggestion.  Is this blocking your work at the moment, ie, what is your time frame?

**Comment by etphipp** [comment]
This is blocking @kliegeois, but he is also willing to make the necessary modifications to MueLu :)

I just wanted agreement on what the path forward was before we start down any road, since it will involve a significant number of modifications.  

Is there any preference on whether this is added to Teuchos::ScalarTraits or if MueLu introduces its own type trait?  The latter makes more sense to me because it is kind of a MueLu specific thing, unless there are other solver packages that might need this too.

**Comment by lucbv** [comment]
@etphipp @kliegeois there is a couple of PR trying to address this issue see #4023 and #3986, we might not have caught all the instances of conversion from `double` to `magnitudeType`...

**Comment by csiefer2** [comment]
The other option would be to make "CoordinateType" a compile-time parameter, which defaults to magnitudeType<Scalar> unless you ask for something else.

**Comment by etphipp** [comment]
> @etphipp @kliegeois there is a couple of PR trying to address this issue see #4023 and #3986, we might not have caught all the instances of conversion from double to magnitudeType...

It looks like those have all been merged, so yes there are still plenty of cases of implicit conversions from magnitudeType to double.

**Comment by etphipp** [comment]
> The other option would be to make "CoordinateType" a compile-time parameter, which defaults to magnitudeType unless you ask for something else.

So you're saying you want to add another template parameter to MueLu ;)

My suggestion at this point, which we will start working on unless someone objects, is to add "coordinateType" to Teuchos::ScalarTraits and modify MueLu accordingly.  The problem I see with calling it "value_type" is it isn't really clear what it means for a given type, and therefore what it is supposed to be used for, whereas "coordinateType" makes that very explicit.

**Comment by jhux2** [comment]
> Is there any preference on whether this is added to Teuchos::ScalarTraits or if MueLu introduces its own type trait? The latter makes more sense to me because it is kind of a MueLu specific thing, unless there are other solver packages that might need this too. Would Ifpack2 or Amesos2 ever need something like this?

There are a few cases where Ifpack2 takes coordinates, e.g., line detection, and the assumption appears to be that they are type double.   I doubt Amesos2 would need this.  Zoltan2 uses coordinates, but the type is determined by the template parameters used by whoever is calling Zoltan2.

> My suggestion at this point, which we will start working on unless someone objects, is to add "coordinateType" to Teuchos::ScalarTraits and modify MueLu accordingly. The problem I see with calling it "value_type" is it isn't really clear what it means for a given type, and therefore what it is supposed to be used for, whereas "coordinateType" makes that very explicit.

I agree that adding it to Teuchos::ScalarTraits is the better option.

**Comment by kliegeois** [comment]
> My suggestion at this point, which we will start working on unless someone objects, is to add "coordinateType" to Teuchos::ScalarTraits and modify MueLu accordingly. The problem I see with calling it "value_type" is it isn't really clear what it means for a given type, and therefore what it is supposed to be used for, whereas "coordinateType" makes that very explicit.

I am currently working on that.

**Comment by mhoemmen** [comment]
If you add stuff to `Teuchos::ScalarTraits`, then you will break any downstream code that specializes ScalarTraits for its own type.  Why can't Xpetra or MueLu have its own traits class?  "Coordinates" are things that MueLu and maybe Zoltan2 want, not things that everybody wants.

**Comment by jhux2** [comment]
@mhoemmen I hadn't thought of that.  Do you know of any applications currently specializing ScalarTraits?

**Comment by mhoemmen** [comment]
I'm thinking more downstream classes, but it's certainly possible.  Anasazi and Belos have this trouble with their traits classes, though they are designed to be specialized.  Nobody ever bothered to say whether ScalarTraits was a customization point, so it's up for grabs.

**Comment by mhoemmen** [comment]
Having a single traits class with a bunch of properties in it is no longer idiomatic C++, for two reasons:

  1. Adding a trait to a traits class breaks backwards compatibility, if the traits class is a customization point (i.e., intended for downstream specialization).
  2. C++14 has templated constants.  C++17 uses them; see e.g., [`is_integral_v`](https://en.cppreference.com/w/cpp/types/is_integral).  [P0437](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2018/p0437r1.pdf), a proposal to replace `numeric_limits` with separate constants, one per trait, was uncontroversial.

This means that I don't care so much about ScalarTraits any more.  Whatever, add stuff, delete stuff.  It's old stuff that will go away at some point.

**Comment by kliegeois** [comment]
I guess that we can close it. #4168
