### ISSUE TITLE
Framework: Windows tests need updated cmake

### ISSUE THREAD

**Issue by csiefer2** [trilinos/Trilinos#4154]
For the first time in forever, windows tests are posting to cdash.  But we've got an out-of-date cmake there.
Can we get this updated?

CMake Error at CMakeLists.txt:62 (CMAKE_MINIMUM_REQUIRED):
  CMake 3.10.0 or higher is required.  You are running version 3.8.1

**Comment by mhoemmen** [comment]
@trilinos/framework

**Comment by jwillenbring** [comment]
@csiefer2 

I saw some activity on this VM, and am trying to track down what changed.

**Comment by jwillenbring** [comment]
This machine was retired. I am going to close this ticket.
