### ISSUE TITLE
Belos_Tpetra_HybridGMRES_hb_test_* randomly failing in many trilinos builds

### ISSUE THREAD

**Issue by fryeguy52** [trilinos/Trilinos#4159]
CC: @trilinos/belos, @srajama1 (Trilinos Linear Solvers Product Lead), @bartlettroscoe, @fryeguy52
 
## Next Action Status
 
PR #4229 that may fix this was merged to 'develop' on 1/22/2019.  Next: Watch for any more random failures and if no new failures by 2/22/2019 then we can close ...

## Description
 
As shown in [this query](https://testing.sandia.gov/cdash-dev-view/queryTests.php?project=Trilinos&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm&field2=testname&compare2=65&value2=Belos_Tpetra_HybridGMRES_hb_test_&field3=status&compare3=62&value3=passed&field4=status&compare4=62&value4=notrun&field5=buildstarttime&compare5=83&value5=2018-12-01) the tests:
* Belos_Tpetra_HybridGMRES_hb_test_1_MPI_4
* Belos_Tpetra_HybridGMRES_hb_test_0_MPI_4

have failed 11 total times since 2018-12-01 in the following ATDM builds:
* Trilinos-atdm-cee-rhel6-clang-5.0.1-openmpi-1.10.2-serial-static-opt
* Trilinos-atdm-cee-rhel6-gnu-4.9.3-openmpi-1.10.2-serial-static-opt
* Trilinos-atdm-cee-rhel6-gnu-7.2.0-openmpi-1.10.2-serial-static-opt
* Trilinos-atdm-mutrino-intel-opt-openmp-HSW
* Trilinos-atdm-sems-rhel6-gnu-debug-openmp
* Trilinos-atdm-sems-rhel6-gnu-opt-openmp
* Trilinos-atdm-sems-rhel6-gnu-opt-serial

[This query](https://testing.sandia.gov/cdash-dev-view/queryTests.php?project=Trilinos&filtercount=4&showfilters=1&filtercombine=and&field1=testname&compare1=65&value1=Belos_Tpetra_HybridGMRES_hb_test_&field2=status&compare2=62&value2=passed&field3=status&compare3=62&value3=notrun&field4=buildstarttime&compare4=83&value4=2018-12-01) shows that `Belos_Tpetra_HybridGMRES_hb_test_*` tests have been failing in other trilinos builds as well during that same time period. 

Here is some typical output from a failure:
```
Belos Version 1.3d - 9/17/2008



Dimension of matrix: 1806
Number of right-hand sides: 1
Block size used by solver: 1
Max number of Gmres iterations: 1805
Relative residual tolerance: 1e-05

Failed.......OR Combination -> 
  OK...........Number of Iterations = 800 < 1805
  Unconverged..(2-Norm Res Vec) / (2-Norm Prec Res0)
               residual [ 0 ] = 0.0224497 > 1e-05

========================================================================================================================

                                         TimeMonitor results over 4 processors

Timer Name                                  MinOverProcs      MeanOverProcs     MaxOverProcs      MeanOverCallCounts    
------------------------------------------------------------------------------------------------------------------------
Belos: BlockGmresSolMgr total solve time    0.5308 (1)        0.5308 (1)        0.5308 (1)        0.5308 (1)            
Belos: DGKS[2]: Ortho (Inner Product)       0.03627 (1370)    0.03643 (1370)    0.03654 (1370)    2.659e-05 (1370)      
Belos: DGKS[2]: Ortho (Norm)                0.01371 (2416)    0.01547 (2416)    0.01742 (2416)    6.402e-06 (2416)      
Belos: DGKS[2]: Ortho (Update)              0.02398 (1370)    0.02443 (1370)    0.02485 (1370)    1.783e-05 (1370)      
Belos: DGKS[2]: Orthogonalization           0.08255 (816)     0.08426 (816)     0.08634 (816)     0.0001033 (816)       
Belos: GmresPolyOp creation time            0.001283 (1)      0.001308 (1)      0.001326 (1)      0.001308 (1)          
Belos: Hybrid Gmres: Operation Op*x         0.03555 (815)     0.03593 (815)     0.03648 (815)     4.408e-05 (815)       
Belos: Hybrid Gmres: Operation Prec*x       0.3885 (816)      0.3908 (816)      0.3932 (816)      0.0004789 (816)       
Belos: Operation Op*x                       0.382 (8986)      0.3853 (8986)     0.3886 (8986)     4.288e-05 (8986)      
Belos: Operation Prec*x                     0 (0)             0 (0)             0 (0)             0 (0)                 
========================================================================================================================
---------- Actual Residuals (normalized) ----------

Problem 0 : 	0.0224497

End Result: TEST FAILED
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpiexec detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[58035,1],2]
  Exit code:    1
--------------------------------------------------------------------------
```

## Current Status on CDash

* [Current status and recent history of failures of test Belos_Tpetra_HybridGMRES_hb_test_* on CDash](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercombine=and&filtercombine=and&filtercount=5&showfilters=1&filtercombine=and&field1=groupname&compare1=61&value1=ATDM&field2=buildname&compare2=65&value2=Trilinos-atdm-&field3=testname&compare3=65&value3=Belos_Tpetra_HybridGMRES_hb_test_&field4=status&compare4=61&value4=failed&field5=buildstarttime&compare5=83&value5=4%20weeks%20ago)
* [Recent history of test Belos_Tpetra_HybridGMRES_hb_test_1_MPI_4 in build](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercombine=and&filtercombine=and&filtercount=4&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-chama-intel-opt-openmp&field2=testname&compare2=61&value2=Belos_Tpetra_HybridGMRES_hb_test_1_MPI_4&field3=site&compare3=61&value3=chama&field4=buildstarttime&compare4=83&value4=4%20weeks%20ago)

## Steps to Reproduce

One should be able to reproduce a build where this random failure has a chance of occurring with a sems rhel6 environment as described in:
* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md

More specifically, the commands given for with a sems rhel6 environment are provided at:
* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#sems-rhel6-environment

The exact commands to reproduce a build where this random failure has a chance of occurring should be:
```
$ cd <some_build_dir>/
$ source $TRILINOS_DIR/cmake/std/atdm/load-env.sh Trilinos-atdm-sems-rhel6-gnu-opt-openmp
$ cmake \
 -GNinja \
 -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
 -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_Belos=ON \
 $TRILINOS_DIR
$ make NP=16
$ ctest -j8
```

**Comment by bartlettroscoe** [comment]
FYI: This test just failed in the standard post-push GCC 4.8.4 CI build shown [here just now](https://testing-vm.sandia.gov/cdash/testDetails.php?test=64268334&build=4415847).

**Comment by bartlettroscoe** [comment]
PR #4229 that may fix this was merged to 'develop' on 1/22/2019.  Next: Watch for any more random failures and if no new failures by 2/22/2019 then we can close ...

Putting in review.

**Comment by bartlettroscoe** [comment]
@hkthorn,

FYI, this test failed today in the build `Trilinos-atdm-chama-intel-opt-openmp` shown [here](https://testing.sandia.gov/cdash/testDetails.php?test=65006954&build=4447868).

Looks like this may not be fixed yet.  Removing the "in review" label ...

**Comment by fryeguy52** [comment]
@bartlettroscoe @hkthorn  

`Belos_Tpetra_HybridGMRES_hb_test_1_MPI_4` has been failing almost every time in the build `Trilinos-atdm-chama-intel-opt-openmp` since 2019-01-23.  It has only passed once since that day. However it has not failed on any other builds in the last month, is this the same issue? There was a commit on the day it started failing regularly that looks possibly related:

```
3b1b7a5:  Changing test default to use RHS as initial vector for Hybrid Gmres
Author: Heidi K. Thornquist <hkthorn@sandia.gov>
Date:   Mon Jan 21 12:56:41 2019 -0700

M	packages/belos/tpetra/test/BlockGmres/test_hybrid_gmres_hb.cpp
```
[Last 30 days on CDash](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercombine=and&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-chama-intel-opt-openmp&field2=testname&compare2=61&value2=Belos_Tpetra_HybridGMRES_hb_test_1_MPI_4&field3=site&compare3=61&value3=chama&field4=buildstarttime&compare4=84&value4=2019-02-07T00%3A00%3A00&field5=buildstarttime&compare5=83&value5=2019-01-08T00%3A00%3A00)

**Comment by bartlettroscoe** [comment]
FYI: We have not asked but I don't think that they ATDM APPs are using a hybrid GMRES solver and we have not seen any problems in EMPIRE or SPARC.  Also, this test is failing in just this one build.  So I don't think this should be considered a "blocking" failure.  Therefore, I am marking this "Nonblocking".

**Comment by mhoemmen** [comment]
@hkthorn Is this the "apply the GMRES polynomial" solver that your intern wrote not long ago?  If so, the intern is here and maybe we can fix this.

**Comment by bartlettroscoe** [comment]
CC: @srajama1 (Trilinos Linear Solvers Product Area Lead)

Hello @trilinos/belos developers,

As shown in  [this query](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercombine=and&filtercombine=and&filtercount=4&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-chama-intel-opt-openmp&field2=testname&compare2=61&value2=Belos_Tpetra_HybridGMRES_hb_test_1_MPI_4&field3=site&compare3=61&value3=chama&field4=buildstarttime&compare4=83&value4=4%20weeks%20ago) this test has been failing every day it has been run for the last month in the build `Trilinos-atdm-chama-intel-opt-openmp`.  If there are no active plans to fix this, then we should just disable the test in this one build.  (It is passing in every other ATDM Trilinos build in the last 30 days as shown in [this query](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercombine=and&filtercombine=and&filtercount=5&showfilters=1&filtercombine=and&field1=groupname&compare1=61&value1=ATDM&field2=buildname&compare2=65&value2=Trilinos-atdm-&field3=testname&compare3=65&value3=Belos_Tpetra_HybridGMRES_hb_test_&field4=status&compare4=61&value4=failed&field5=buildstarttime&compare5=83&value5=4%20weeks%20ago).)  Otherwise we can continue to ignore this failing test but letting this test keep failing every day does not provide any value at this point.

**Comment by mhoemmen** [comment]
@bartlettroscoe I say disable it for now, but @hkthorn has the last word.

**Comment by hkthorn** [comment]
@bartlettroscoe Disable the test on that one platform.   I am fine with that.

**Comment by bartlettroscoe** [comment]
For some reason, the test `Belos_Tpetra_HybridGMRES_hb_test_1_MPI_4` has passed every day it ran starting 3/21/2019 as shown in [this query](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercombine=and&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-chama-intel-opt-openmp&field2=testname&compare2=61&value2=Belos_Tpetra_HybridGMRES_hb_test_1_MPI_4&field3=site&compare3=61&value3=chama&field4=buildstarttime&compare4=84&value4=2019-03-27T00%3A00%3A00&field5=buildstarttime&compare5=83&value5=2019-02-25T00%3A00%3A00).  Diid someone fix this on purpose or did it get fixed accidentally?

**Comment by mhoemmen** [comment]
I don't think we did anything with it -- did we?

**Comment by srajama1** [comment]
I was testing a machine learning code to automatically fix belos tests .. it might have worked :)

**Comment by hkthorn** [comment]
@srajama1 Wah?

**Comment by bartlettroscoe** [comment]
As shown in [this query](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercombine=and&filtercombine=and&filtercount=4&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-chama-intel-opt-openmp&field2=testname&compare2=61&value2=Belos_Tpetra_HybridGMRES_hb_test_1_MPI_4&field3=site&compare3=61&value3=chama&field4=buildstarttime&compare4=83&value4=2019-03-06T00%3A00%3A00), this test was failing every day in the build `Trilinos-atdm-chama-intel-opt-openmp` prior to 3/21/2019 and has been passing every day in that build since then.

Also, as shown in [this query](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=4&showfilters=1&filtercombine=and&field1=testname&compare1=61&value1=Belos_Tpetra_HybridGMRES_hb_test_1_MPI_4&field2=groupname&compare2=62&value2=Experimental&field3=status&compare3=61&value3=failed&field4=buildstarttime&compare4=83&value4=2019-02-01), this test has not failed in any non-Experimental build submitted to CDash since 3/20/2019 except for the build [Trilinos-atdm-waterman-cuda-9.2-rdc-release-debug on 4/5/2019](https://testing.sandia.gov/cdash/buildSummary.php?buildid=4840721) but there were many failing tests in that build due to system problems (running out of CUDA memory) and therefore that failure was not related to this issue.

Other than the build `Trilinos-atdm-chama-intel-opt-openmp` where this test was failing every day prior to 3/20/2019, there were 8 failures in other builds since 2/1/2019.  Looking through those 8 failures, all of them look to be random system failures except for the one build [Trilinos-atdm-sems-rhel6-intel-17.0.1-openmp-release on 3/14/2019](https://testing.sandia.gov/cdash/testDetails.php?test=70761168&build=4714814) which shows the failure:

```
Dimension of matrix: 1806
Number of right-hand sides: 1
Block size used by solver: 1
Max number of Gmres iterations: 1805
Relative residual tolerance: 1e-05

Failed.......OR Combination -> 
  OK...........Number of Iterations = 800 < 1805
  Unconverged..(2-Norm Res Vec) / (2-Norm Prec Res0)
               residual [ 0 ] = 0.0429812 > 1e-05

========================================================================================================================

                                         TimeMonitor results over 4 processors

Timer Name                                  MinOverProcs      MeanOverProcs     MaxOverProcs      MeanOverCallCounts    
------------------------------------------------------------------------------------------------------------------------
Belos: BlockGmresSolMgr total solve time    0.818 (1)         0.8181 (1)        0.8181 (1)        0.8181 (1)            
Belos: DGKS[2]: Ortho (Inner Product)       0.07492 (1577)    0.07571 (1577)    0.07633 (1577)    4.801e-05 (1577)      
Belos: DGKS[2]: Ortho (Norm)                0.01996 (2416)    0.04893 (2416)    0.06628 (2416)    2.025e-05 (2416)      
Belos: DGKS[2]: Ortho (Update)              0.04414 (1577)    0.05001 (1577)    0.06586 (1577)    3.171e-05 (1577)      
Belos: DGKS[2]: Orthogonalization           0.1778 (816)      0.1885 (816)      0.2 (816)         0.000231 (816)        
Belos: GmresPolyOp creation time            0.01267 (1)       0.01272 (1)       0.01275 (1)       0.01272 (1)           
Belos: Hybrid Gmres: Operation Op*x         0.04131 (815)     0.04278 (815)     0.04361 (815)     5.249e-05 (815)       
Belos: Hybrid Gmres: Operation Prec*x       0.53 (816)        0.5363 (816)      0.542 (816)       0.0006572 (816)       
Belos: Operation Op*x                       0.4491 (8986)     0.4856 (8986)     0.5032 (8986)     5.404e-05 (8986)      
Belos: Operation Prec*x                     0 (0)             0 (0)             0 (0)             0 (0)                 
========================================================================================================================
---------- Actual Residuals (normalized) ----------

Problem 0 : 	0.0429812

End Result: TEST FAILED
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpiexec detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[13425,1],3]
  Exit code:    1
```

This might suggest that this test is still (very rarely) randomly failing.  But there was some change to Trilinos on 3/30/2019 that caused this test to start passing in the build `Trilinos-atdm-chama-intel-opt-openmp`.

When that test passes, it looks like:

```
Dimension of matrix: 1806
Number of right-hand sides: 1
Block size used by solver: 1
Max number of Gmres iterations: 1805
Relative residual tolerance: 1e-05


Belos::StatusTestGeneralOutput: Passed
  (Num calls,Mod test,State test): (68, 1, Passed)
   Passed.......OR Combination -> 
     OK...........Number of Iterations = 66 < 1805
     Converged....(2-Norm Res Vec) / (2-Norm Prec Res0)
                  residual [ 0 ] = 9.86283e-06 < 1e-05

Passed.......OR Combination -> 
  OK...........Number of Iterations = 66 < 1805
  Converged....(2-Norm Res Vec) / (2-Norm Prec Res0)
               residual [ 0 ] = 9.86283e-06 < 1e-05

========================================================================================================================

                                         TimeMonitor results over 4 processors

Timer Name                                  MinOverProcs      MeanOverProcs     MaxOverProcs      MeanOverCallCounts    
------------------------------------------------------------------------------------------------------------------------
Belos: BlockGmresSolMgr total solve time    0.05609 (1)       0.05614 (1)       0.05627 (1)       0.05614 (1)           
Belos: DGKS[2]: Ortho (Inner Product)       0.003938 (131)    0.004018 (131)    0.004111 (131)    3.067e-05 (131)       
Belos: DGKS[2]: Ortho (Norm)                0.00153 (200)     0.001837 (200)    0.00229 (200)     9.186e-06 (200)       
Belos: DGKS[2]: Ortho (Update)              0.002286 (131)    0.002361 (131)    0.00242 (131)     1.802e-05 (131)       
Belos: DGKS[2]: Orthogonalization           0.008628 (68)     0.008917 (68)     0.009253 (68)     0.0001311 (68)        
Belos: GmresPolyOp creation time            0.02144 (1)       0.02151 (1)       0.02158 (1)       0.02151 (1)           
Belos: Hybrid Gmres: Operation Op*x         0.003167 (68)     0.003259 (68)     0.003309 (68)     4.792e-05 (68)        
Belos: Hybrid Gmres: Operation Prec*x       0.03968 (68)      0.03985 (68)      0.0401 (68)       0.0005861 (68)        
Belos: Operation Op*x                       0.03373 (759)     0.03392 (759)     0.03408 (759)     4.47e-05 (759)        
Belos: Operation Prec*x                     0 (0)             0 (0)             0 (0)             0 (0)                 
========================================================================================================================
---------- Actual Residuals (normalized) ----------

Problem 0 : 	9.86283e-06

End Result: TEST PASSED
```

I don't believe that going from 66 iterations with a residual norm of < 1e-5 to 800 iterations and a residual norm of 4e-2 is due to random accumulation errors due to threading.  Is this test possibly exposing a defect that may kill someone's expensive simulation at some point (like running on 4k nodes and 20K GPUs on Summit for a week and then have it crash)?

I would say to leave this issue open for a few more months to see if we see any more of these random failures before we close this.  (@fryeguy52 and myself will modify our CDash analysis tool to categorize this as a rarely randomly failing test so that it will stand out if it fails again.)

P.S. I did all of this analysis hoping to close this issue but no dice :-(

**Comment by bartlettroscoe** [comment]
FYI: This test is also randomly failing in the build:

* `Trilinos-atdm-sems-rhel7-intel-17.0.1-openmp-complex-shared-debug`

shown [here](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercombine=and&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-sems-rhel7-intel-17.0.1-openmp-complex-shared-debug&field2=testname&compare2=61&value2=Belos_Tpetra_HybridGMRES_hb_test_1_MPI_4&field3=site&compare3=61&value3=sems-rhel7&field4=buildstarttime&compare4=84&value4=2019-04-26T00%3A00%3A00&field5=buildstarttime&compare5=83&value5=2019-03-27T00%3A00%3A00).  The latest failure shown [here](https://testing.sandia.gov/cdash/testDetails.php?test=76151071&build=4946958) showed:

```
imension of matrix: 1806
Number of right-hand sides: 1
Block size used by solver: 1
Max number of Gmres iterations: 1805
Relative residual tolerance: 1e-05

Failed.......OR Combination -> 
  OK...........Number of Iterations = 800 < 1805
  Unconverged..(2-Norm Res Vec) / (2-Norm Prec Res0)
               residual [ 0 ] = 0.0317169 > 1e-05

========================================================================================================================

                                         TimeMonitor results over 4 processors

Timer Name                                  MinOverProcs      MeanOverProcs     MaxOverProcs      MeanOverCallCounts    
------------------------------------------------------------------------------------------------------------------------
Belos: BlockGmresSolMgr total solve time    4.768 (1)         4.768 (1)         4.769 (1)         4.768 (1)             
Belos: DGKS[2]: Ortho (Inner Product)       0.1356 (1576)     0.1387 (1576)     0.1423 (1576)     8.799e-05 (1576)      
Belos: DGKS[2]: Ortho (Norm)                0.0423 (2416)     0.1152 (2416)     0.1815 (2416)     4.769e-05 (2416)      
Belos: DGKS[2]: Ortho (Update)              0.07802 (1576)    0.07988 (1576)    0.08489 (1576)    5.069e-05 (1576)      
Belos: DGKS[2]: Orthogonalization           0.3017 (816)      0.365 (816)       0.4304 (816)      0.0004473 (816)       
Belos: GmresPolyOp creation time            0.03541 (1)       0.03548 (1)       0.03555 (1)       0.03548 (1)           
Belos: Hybrid Gmres: Operation Op*x         0.3638 (815)      0.3653 (815)      0.367 (815)       0.0004482 (815)       
Belos: Hybrid Gmres: Operation Prec*x       3.86 (816)        3.921 (816)       3.976 (816)       0.004805 (816)        
Belos: Operation Op*x                       3.933 (8986)      3.993 (8986)      4.041 (8986)      0.0004443 (8986)      
Belos: Operation Prec*x                     0 (0)             0 (0)             0 (0)             0 (0)                 
========================================================================================================================
---------- Actual Residuals (normalized) ----------

Problem 0 : 	0.0317169

End Result: TEST FAILED
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpiexec detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[38986,1],2]
  Exit code:    1
--------------------------------------------------------------------------
```

**Comment by bartlettroscoe** [comment]
@srajama1, @trilinos/belos, @mhoemmen,

What should we do about this failing test?  Is it worth fixing or should we just disable it in ATDM Trilinos testing?  If no customer is using this, then is this worth our time writing issue comments like this?  We can leave it running in the Trilinos PR builds to make sure it does not get broken.

**Comment by srajama1** [comment]
@bartlettroscoe : I would vote for disabling it. @hkthorn has the ultimate authority.

**Comment by bartlettroscoe** [comment]
FYI: We plan to extend our cdash analysis tool to allow using a wildcard for tests like this so that it matches every build so it gets sorted to the bottom of the summary email into a section "Tests with issue trackers randomly failing allowed to fail Failed: twirfatff=???".  That way it would never take up any more of our time.  But it will continue to bleed red on the dashboard (which some people care about but I don't really since the tool can be extended to handle cases like this).

**Comment by mhoemmen** [comment]
@hkthorn should be the one to make the final decision, but I'm OK with disabling the test everywhere for now.  The person who wrote that solver might be coming back this summer, so they may have a chance to fix it then.

**Comment by bartlettroscoe** [comment]
FYI: As shown in [this query](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-sems-rhel7-intel-17.0.1-openmp-complex-shared-debug&field2=testname&compare2=61&value2=Belos_Tpetra_HybridGMRES_hb_test_1_MPI_4&field3=site&compare3=61&value3=sems-rhel7&field4=buildstarttime&compare4=84&value4=2019-06-04T04%3A01%3A00UTC&field5=buildstarttime&compare5=83&value5=2019-05-05T04%3A01%3A00UTC) this test also appears to be failing randomly in this same way failing 5 times over the last 30 days showing the output (e.g. [here](https://testing.sandia.gov/cdash/testDetails.php?test=80097863&build=5126547)):

```
Failed.......OR Combination -> 
  OK...........Number of Iterations = 800 < 1805
  Unconverged..(2-Norm Res Vec) / (2-Norm Prec Res0)
               residual [ 0 ] = 0.0317169 > 1e-05
```

when it fails and showing the output (e.g. [here](https://testing.sandia.gov/cdash/testDetails.php?test=80016370&build=5122639)):

```
Belos::StatusTestGeneralOutput: Passed
  (Num calls,Mod test,State test): (69, 1, Passed)
   Passed.......OR Combination -> 
     OK...........Number of Iterations = 67 < 1805
     Converged....(2-Norm Res Vec) / (2-Norm Prec Res0)
                  residual [ 0 ] = 9.81581e-06 < 1e-05

Passed.......OR Combination -> 
  OK...........Number of Iterations = 67 < 1805
  Converged....(2-Norm Res Vec) / (2-Norm Prec Res0)
               residual [ 0 ] = 9.81581e-06 < 1e-05
```

when it passes.

We will extend out `cdash_analyze_and_report.py` tool to allow these tests to fail.

**Comment by bartlettroscoe** [comment]
As shown in [this query](https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-sems-rhel7-intel-18.0.5-openmp-complex-shared-release-debug&field2=testname&compare2=61&value2=Belos_Tpetra_HybridGMRES_hb_test_1_MPI_4&field3=site&compare3=61&value3=sems-rhel7&field4=buildstarttime&compare4=84&value4=2019-08-01T04:01:00UTC&field5=buildstarttime&compare5=83&value5=2019-07-02T04:01:00UTC) this test is also randomly failing in the build:

* Trilinos-atdm-sems-rhel7-intel-18.0.5-openmp-complex-shared-release-debug

failing 7 times out of the last 30 days most recently showing:

```
Dimension of matrix: 1806
Number of right-hand sides: 1
Block size used by solver: 1
Max number of Gmres iterations: 1805
Relative residual tolerance: 1e-05

Failed.......OR Combination -> 
  OK...........Number of Iterations = 800 < 1805
  Unconverged..(2-Norm Res Vec) / (2-Norm Prec Res0)
               residual [ 0 ] = 0.0317169 > 1e-05
```

**Comment by bartlettroscoe** [comment]
As ATDM is not using the Belos HybridGMRES solver, I will remove the 'client: ATDM' label.  We will address tests like this in our `cdash_analyze_and_report.py` tool by assigning them `allow_to_fail=1`.

**Comment by bartlettroscoe** [comment]
These tests have been disabled as per:

* https://sems-atlassian-srn.sandia.gov/browse/ATDV-263

Adding label "Disabled Tests".

**Comment by jennloe** [comment]
@seheracer I don't know if this is related to your other failing tests with the polynomial.  It doesn't seem to give the same error message.  #8540

**Comment by mhoemmen** [comment]
@csiefer2 autobot begone?

**Comment by mhoemmen** [comment]
autobot begone?
