### ISSUE TITLE
Tempus: NaNs thrown from sqrt with Clang debug builds

### ISSUE THREAD

**Issue by krcb** [trilinos/Trilinos#4176]
EMPIRE identified NaNs thrown in Tempus due to inconsistent usage of Scalar
type with Teuchos::ScalarTraits:squareroot.

@trilinos/tempus 

## Expectations

Should be able to run without NaNs being generated.

## Possible Solution

Ensure that usage of Teuchos::ScalarTraits:squareroot occurs without generating NaNs.

**Comment by ccober6** [comment]
Did another check for the usage of Teuhos::ScalarTriats::SquareRoot, and cleaned them up.
