### ISSUE TITLE
Need a shallow swap method for Teuchos Serial Dense Vector

### ISSUE THREAD

**Issue by rhoope** [trilinos/Trilinos#4183]
Teuchos: Mike Eldred has need of a shallow swap method for performance related to Dakota multilevel algorithms.  He also identified some additional performance gains by not tallying flop metrics when these are not used.

@trilinos/teuchos

enhancement
## Expectations

I will submit a pull request for candidate changes to address this issue.
## Definition of Done

Done is when a shallow swap method is available in the master branch of trilinos.
## Possible Solution

A pull request is forthcoming.
## Your Environment

- **Relevant repo SHA1s:**  
- **Relevant configure flags or configure script:**  
- **Operating system and version:**  
- **Compiler and TPL versions:**  

## Related Issues

* Blocks 
* Is blocked by 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of

**Comment by jhux2** [comment]
@trilinos/teuchos
