### ISSUE TITLE
Extract Teuchos Memory Management documents from old Trilinos git repo to put into new TeuchosMMDoc repo

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#419]
**Description:**

When Trilinos was filtered to put on GitHub, the Teuchos Memory Management documents in the directories:

* Trilinos/doc/TeuchosMemoryManagementSAND
* Trilinos/doc/RefCountPtr

where filtered out.

This Story is to extract the history for these documents from these two directories and put them into a new GitHub repo.  I think for now I will put the main git repo in my GitHub account to make it less visible for now.

**Comment by jwillenbring** [comment]
I think these documents are in the TrilinosDocuments repo. Is that not a good solution in this case?

**Comment by bartlettroscoe** [comment]
Where is that repo?  Is that a got repo?

-Ross
________________________________

**Comment by bartlettroscoe** [comment]
I pulled out the git history for these two directories and pushed them to a new git repo `TeuchosMMDocs` on my GitHub account (see details below).

Apparently the Trilinos/doc repo got pulled off into a separate internal TrilinosDocumentation repo.  But I like having the Teuchos MM documentation in its own smaller git repo.  And having it on github will allow people to make PR against it.

All done

-----

**Detailed Notes:**

I need to split off the Teuchos MM Report as its own git repo so that I can maintain it.   I also need to split off the Teuchos RCP beginners guide.  I want them both in the same git repo.

**1) Split off the git histories:**

I will start by using git subtree to get the histories:

```
$ cd Trilinos/

$ time git subtree split --prefix=doc/TeuchosMemoryManagementSAND -b teuchos-mm-doc
Created branch 'teuchos-mm-doc'
b255365280be2540c8b3d9d973dca3ba952bb557

real	11m33.425s
user	3m9.627s
sys	4m21.489s

$ time git subtree split --prefix=doc/RefCountPtr -b teuchos-rcp-beginners-guide
Created branch 'teuchos-rcp-beginners-guide'
954562b564c45821b6cbcc1ad968911b6cf0c836

real	14m40.877s
user	4m0.386s
sys	6m6.618s
```


**2) Combine branches into a new git repo and push to new private bb repo:**

I would like to have both the Teuchos::RCP beginner’s guide and the complete report in the same git reo.  Therefore, I will need to move the directories around in the history.  Therefore, I think it might make sense to first create temp git repos and use ‘filter branch’ in order to move these into the right subdir and then combine them together in the same repo.

To move these into their own directly, I can do like I did for PIKE when I moved it from its own git repo into Trilinos:

```
$ cd pike/
$ git checkout -b packages_pike
$ time git filter-branch --prune-empty --tree-filter '
if [[ ! -e packages/pike ]]; then
    mkdir -p packages/pike
    git ls-tree --name-only $GIT_COMMIT | xargs -I files mv files packages/pike
fi'

real	0m10.289s
user	0m3.356s
sys	0m5.378s
```

I think to do this, I need to create temporary git repos for each of these two extracted branches, then I can pull them into the same git repo:

```
$ cd ~/junk/
$ mkdir TeuchosMMDocTmp
$ cd TeuchosMMDocTmp/

$ git init .
Initialized empty Git repository in /home/8vt/junk/TeuchosMMDocTmp/.git/

$ git remote add trilinos-local ../../localhome/PROJECTS/VERA.base/VERA/Trilinos

$ git fetch trilinos-local teuchos-mm-doc
…
From ../../localhome/PROJECTS/VERA.base/VERA/Trilinos
 * branch            teuchos-mm-doc -> FETCH_HEAD
 * [new branch]      teuchos-mm-doc -> trilinos-local/teuchos-mm-doc

$ git merge trilinos-local/teuchos-mm-doc

$ git log-short --name-status

b255365 "Updated debugging instructions for current Teuchos code"
Author: Roscoe A. Bartlett <bartlettra@ornl.gov>
Date:   Wed Sep 5 16:14:37 2012 -0400 (3 years, 9 months ago)

M       TeuchosMemoryManagementSAND.tex

6b0e415 "Changing to colorlinks in hyperref."
Author: Roscoe A. Bartlett <bartlettra@ornl.gov>
Date:   Mon Nov 21 18:54:30 2011 -0500 (4 years, 7 months ago)

M       TeuchosMemoryManagementSAND.tex

…

$ time git filter-branch --prune-empty --tree-filter '
if [[ ! -e memory_management_report ]]; then
    mkdir -p memory_management_report
    git ls-tree --name-only $GIT_COMMIT | xargs -I files mv files memory_management_report
fi'
Rewrite b255365280be2540c8b3d9d973dca3ba952bb557 (139/139)
Ref 'refs/heads/master' was rewritten

real	2m34.320s
user	0m9.650s
sys	0m20.328s

$ git log-short --name-status -2
909c68c "Updated debugging instructions for current Teuchos code"
Author: Roscoe A. Bartlett <bartlettra@ornl.gov>
Date:   Wed Sep 5 16:14:37 2012 -0400 (3 years, 9 months ago)

M       memory_management_report/TeuchosMemoryManagementSAND.tex

80d220f "Changing to colorlinks in hyperref."
Author: Roscoe A. Bartlett <bartlettra@ornl.gov>
Date:   Mon Nov 21 18:54:30 2011 -0500 (4 years, 7 months ago)

M       memory_management_report/TeuchosMemoryManagementSAND.tex
```

That worked!

Now to do the same thing for the Teuchos RCP Beginners Guide:

```
$ cd ~/junk/
$ mkdir TeuchosRCPBeginnersGuideTmp
$ cd TeuchosRCPBeginnersGuideTmp/
$ git init .
$ git remote add trilinos-local ../../localhome/PROJECTS/VERA.base/VERA/Trilinos
$ git fetch trilinos-local teuchos-rcp-beginners-guide
$ git merge trilinos-local/teuchos-rcp-beginners-guide

$ time git filter-branch --prune-empty --tree-filter '
if [[ ! -e ref_count_ptr ]]; then
    mkdir -p ref_count_ptr
    git ls-tree --name-only $GIT_COMMIT | xargs -I files mv files ref_count_ptr
fi'
Rewrite 954562b564c45821b6cbcc1ad968911b6cf0c836 (53/53)
Ref 'refs/heads/master' was rewritten

real	0m20.465s
user	0m2.087s
sys	0m3.719s

$ git log-short --name-status
fafb9d6 "Permissions corrections of source files."
Author: Mark E. Hamilton <mhamilt@sandia.gov>
Date:   Thu Feb 9 14:49:23 2012 -0700 (4 years ago)

M       ref_count_ptr/design/bad_ref.cpp

f6a374c "Updating all Trilinos code to use namespaced TEUCHOS_TEST_FOR_EXCEPT macros"
Author: Roscoe A. Bartlett <bartlettra@ornl.gov>
Date:   Tue Oct 18 08:39:35 2011 -0400 (4 years, 8 months ago)

M       ref_count_ptr/design/RefCountPtrBody.tex
M       ref_count_ptr/example/classicMakefile

a36ace1 "Updated updated and printed date."
Author: Roscoe A. Bartlett <rabartl@sandia.gov>
Date:   Fri Sep 10 18:01:14 2010 -0600 (6 years ago)

M       ref_count_ptr/beginners/RefCountPtrBeginnersGuideSAND.tex
```

Looks good to me.

Now to combine them into the same git repo:

```
$ cd ~/PROJECTS/
$ mkdir TeuchosMMDocs
$ cd TeuchosMMDocs/
$ git init .
$ git pull ~/junk/TeuchosRCPBeginnersGuideTmp master
$ git pull ~/junk/TeuchosMMDocTmp master
$ git log-short --name-status -- ref_count_ptr/
$ git log-short --name-status -- memory_management_report/
```

Now to create my GitHub repo TeuchosMMDocs and push it.

```
$ git remote add rab-github git@github.com:bartlettroscoe/TeuchosMMDocs.git
$ git push -u rab-github master
...
To git@github.com:bartlettroscoe/TeuchosMMDocs.git
 * [new branch]      master -> master
Branch master set up to track remote branch master from rab-github.
```

Now we can see it here:

https://github.com/bartlettroscoe/TeuchosMMDocs

**3) Get the documents building again from the new repo:**

I then cloned this on my Windows 7 laptop running cygwin and tried to build the Teuchos MM document with:

```
$ cd memory_management_report/
$ make
...
ps2pdf TeuchosMemoryManagementSAND.ps TeuchosMemoryManagementSAND.pdf
```

Wow, that is still using ps2pdf?  I will need to swtich that to use pdflatex at some point there.

This seemed to build the document correctly.

I also tried to build the beginners guide:

```
$ cd ref_count_ptr/beginners/
$ ls
$ make
...
$ acrobat TeuchosMemoryManagementSAND.pdf &
```

This all worked.  I pushed to a git repo `TeuchosMMDocs` on my GitHub account.

Apparently the Trilinos/doc repo got pulled off into a separate internal TrilinosDocumentation repo.  But I like having the Teuchos MM documentation in its own smaller git repo.  And having it on github will allow people to make PR against it.

All done.
