### ISSUE TITLE
MueLu: add local values in regionalToComposite manually

### ISSUE THREAD

**Issue by mayrmt** [trilinos/Trilinos#4193]
@trilinos/muelu 

## Expectations
Replace current use of `Epetra_CombineMode Epetra_AddLocalAlso` in the MueLu HHG driver by an implementation that performs the local adds manually when transforming a region matrix back to a composite matrix.

## Current Behavior
In the HHG driver's routine `regionToComposite()`, we rely on the `Epetra_CombineMode Epetra_AddLocalAlso` to not only add values accross processes, but also to add process-local values.

## Motivation and Context
`Tpetra/Xpetra` does not support a `AddLocalAlso`-type CombineMode.

## Definition of Done
- [ ] Add manual add operation for processor-local values.
- [ ] Remove use of `Epetra_CombineMode Epetra_AddLocalAlso`.

## Possible Solution
This is already implemented for vector operations. We might follow a similar idea.

There's already some code that's trying to do that by perform inter-process add operations based on a `Xpetra::CombineMode Add`, but performs on-process operations separately. We just have to get it right.

## Related Issues
* Blocks #4084

**Comment by mayrmt** [comment]
@lucbv I'm working on this right now. This should be one of the last bits to complete #4084.

**Comment by mayrmt** [comment]
@lucbv I have an implementation that works on the fine level. Should be same on any coarse level, though I'm still testing.

**Comment by lucbv** [comment]
@mayrmt I think this has been done now, should we close this issue or is there more work that needs to happen on this?

**Comment by mayrmt** [comment]
@lucbv You’re right. That has been taken care of. Let’s close!
