### ISSUE TITLE
Amesos2 tests don't build with ETI OFF

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#4194]
@trilinos/amesos2

## Your Environment

- **Relevant repo SHA1s:**  
- **Relevant configure flags or configure script:**  
- **Operating system and version:**  
- **Compiler and TPL versions:**  

## Related Issues

* Blocks 
* Is blocked by 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of

**Comment by mhoemmen** [comment]
My web browser is giving me trouble, so I can't edit the above right now.  I am working on a fix.  I will paste bug details in comments below.

**Comment by mhoemmen** [comment]
Here is how I replicated the build errors first noticed by Sierra in their attempts to build with Trilinos' native CMake-based build system.  I first applied the fixes from earlier (see Trilinos PR #4187) to develop.  Then, I configured Trilinos with the following settings:

  - Turned OFF ETI (`Trilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=OFF`)
  - Enabled SuperLU TPL
  - Enabled complex<double> (`Trilinos_ENABLE_COMPLEX_DOUBLE:BOOL=ON`)
  - Set `Amesos2_ENABLE_SuperLU:BOOL=ON` (just in case?)
  - Enabled TpetraCore and Amesos2 tests and examples

and built with GCC 4.9.3 + OpenMPI 1.10.1.  After a much longer build (ETI OFF hurts, esp. w/ tests & examples), I got build errors like the following:
```
...
.../Trilinos/packages/amesos2/src/Amesos2_Tacho_def.hpp:347:77:   required from ‘bool Amesos2::TachoSolver< <template-parameter-1-1>, <template-parameter-1-2> >::loadA_impl(Amesos2::EPhase) [with Matrix = Tpetra::CrsMatrix<std::complex<double>, long long int, long long int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP> >; Vector = Tpetra::MultiVector<std::complex<double>, long long int, long long int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP> >]’
.../Trilinos/packages/amesos2/src/Amesos2_SolverCore_def.hpp:519:18:   required from ‘void Amesos2::SolverCore<ConcreteSolver, Matrix, Vector>::loadA(Amesos2::EPhase) [with ConcreteSolver = Amesos2::TachoSolver; Matrix = Tpetra::CrsMatrix<std::complex<double>, long long int, long long int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP> >; Vector = Tpetra::MultiVector<std::complex<double>, long long int, long long int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP> >]’
.../Trilinos/packages/amesos2/src/Amesos2_SolverCore_def.hpp:105:20:   required from ‘Amesos2::Solver<Matrix, Vector>& Amesos2::SolverCore<ConcreteSolver, Matrix, Vector>::preOrdering() [with ConcreteSolver = Amesos2::TachoSolver; Matrix = Tpetra::CrsMatrix<std::complex<double>, long long int, long long int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP> >; Vector = Tpetra::MultiVector<std::complex<double>, long long int, long long int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP> >]’
.../Trilinos/packages/amesos2/test/solvers/Solver_Test.cpp:1610:1:   required from here
.../Trilinos/packages/tpetra/core/src/Tpetra_Import_def.hpp:385:30: error: no matching function for call to ‘Teuchos::Array<int>::Array(const Teuchos::ArrayView<const long long int>&)’
     ImportData_->exportLIDs_ = Teuchos::Array<int>(userExportLIDs);
...
```
Check out those types!  For example:
```
Tpetra::CrsMatrix<std::complex<double>, long long int, long long int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP> >;
```
The only valid and allowed LocalOrdinal (LO) type is `int`, but here, Amesos2 is trying to build with `LO=long long int`.  (LocalOrdinal is the second template parameter of most Tpetra classes.)

This is very wrong.  I'll need to look more closely at Amesos2's build logic when ETI is OFF.  The only work-around for now would be for Sierra to turn ON ETI.

I have a fix in progress.

**Comment by mhoemmen** [comment]
@rrdrake @theguruat12 #4194 blocks Sierra from using Trilinos' native CMake-based build system.  My PR #4195 should help fix that.

**Comment by srajama1** [comment]
@ndellingwood
