### ISSUE TITLE
Set Trilinos_ENABLE_DEBUG=ON for all 'debug' ATDM Trilinos bulds

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#4201]
CC: @fryeguy52, @rppawlo, @mhoemmen 

In the current ATDM Trilinos 'debug' configurations, only the options `Kokkos_ENABLE_Debug_Bounds_Check=ON` and `KOKKOS_ENABLE_DEBUG=ON` are getting set.  That leaves a lot of runtime debug-mode checking that is built into Trilinos turned off.  It would be much better to set `Trilinos_ENABLE_DEBUG=ON`.  That enables a lot of this extra runtime debug-mode checking that can help catch developer mistakes.

Given the PR #4198 that just got merged, hopefully we can finally set `Trilinos_ENABLE_DEBUG=ON` for ATDM Trilinos builds.  Also, now that we know how to test SPARC and EMPIRE against the ATDM Trilinos build locally, we can check to see if this breaks anything in the ATDM APPs.

**Comment by mhoemmen** [comment]
Doesn’t that get set by default in a debug build?

**Comment by bartlettroscoe** [comment]
@mhoemmen said:

> Doesn’t that get set by default in a debug build?

Not for the current ATDM Trilinos configuration (initially copied from the EMPIRE Trilinos configuration).  See the file [ATDMDevEnvSettings.cmake](https://github.com/trilinos/Trilinos/blob/c7c06b7a0a46de09d1a6476c8dfcb5e1b6025e5e/cmake/std/atdm/ATDMDevEnvSettings.cmake#L203).

**Comment by mhoemmen** [comment]
> Not for the current ATDM Trilinos configuration (initially copied from the EMPIRE Trilinos configuration).

Wow, that's weird.  OK, I'm glad you're fixing this.

**Comment by bartlettroscoe** [comment]
FYI: The current EMPIRE BuildScripts/ALL/configure-trilinos.sh script currently sets `Trilinos_ENABLE_DEBUG=ON` when `CMAKE_BUILD_TYPE=DEBUG`.  Therefore, w.r.t. EMPIRE, we should be good to go with turning this on.  The question is if the Trilinos test suite will be clean with this, especially with the CUDA builds.

**Comment by mhoemmen** [comment]
@bartlettroscoe I don't think much RCP stuff could survive entering a `__device__` function and still compile, any more than `std::shared_ptr` could.  Nevertheless, I'm curious to see what happens :-)

**Comment by bartlettroscoe** [comment]
This has been done for a long time and both EMPIRE and SPARC have had several updates of Trilinos since then.  If there was a problem related this, I would have heard about it.

Closing as complete.
