### ISSUE TITLE
ShyLu/FROSch: improve run-time error in case of missing packages

### ISSUE THREAD

**Issue by mayrmt** [trilinos/Trilinos#4208]
@trilinos/shylu 
@searhein 

## Expectations
Provide a more meaningful error message in case that a certain (optional) Trilinos package has been chosen as subdomain solver, but is not included into the build configuration.

## Current Behavior
I'm attempting to use MueLu as coarse solver for FROSch's GDSW preconditioner. This requires the cmake option `-D ShyLU_DDFROSch_ENABLE_MueLu:BOOL=ON`. However, without this option the subdomain solver is not recognized and the error message is just `FROSCH_ASSERT(false,"SolverType unknown...");`. 

Taking MueLu as an example as implemented [here](https://github.com/trilinos/Trilinos/blob/develop/packages/shylu/shylu_dd/frosch/src/Tools/FROSch_SubdomainSolver_def.hpp#L123): 
```
#ifdef HAVE_SHYLU_DDFROSCH_MUELU
    } else if (!ParameterList_->get("SolverType","Amesos").compare("MueLu")) {
        // ... calling MueLu setup here ...
    }
#endif
    else {
        FROSCH_ASSERT(false,"SolverType unknown...");
    }
```

The check, whether `"MueLu"` has been set as `"SolverType"` in the parameter list is already guarded by `#ifdef HAVE_SHYLU_DDFROSCH_MUELU`, so we can't tell the user that MueLu is required, but not enabled by the build configuration.

## Motivation and Context
Telling the user that a package is required, but has not been enabled in the build configuration helps to figure out, why an error occurs and points to possible solutions.

## Definition of Done
- [ ] Improve error message such that it contains details about missing packages.

## Possible Solution
We could move the `#ifdef HAVE_SHYLU_DDFROSCH_MUELU` inside the parameter check. This detects that MueLu has been asked for, but is not enabled. We can throw an error then that contains much more details. Maybe something along the lines of:
```
    } else if (!ParameterList_->get("SolverType","Amesos").compare("MueLu")) {
    #ifdef HAVE_SHYLU_DDFROSCH_MUELU
        // ... calling MueLu setup here ...
    #else
        FROSCH_ASSERT(false, "SolverType is chosen as MueLu, but MueLu is not enabled to work with FROSch. Modify your build configuration to enable MueLu inside ShyLU_DDFROSch!
    #endif
    }
    else {
        FROSCH_ASSERT(false,"SolverType unknown...");
    }
```

## Steps to Reproduce
1. Disable MueLu inside FROSch by setting `-D ShyLU_DDFROSch_ENABLE_MueLu:BOOL=OFF` in the configure script
1. Set the coarse solver's `"SolverType"` to `"MueLu"`
1. Run any test based on `ShyLU_DDFROSch_thyra_xpetra_laplace.exe`.

## Additional Information
I described the issue for MueLu here, but a similar strategy could be applied to all other package dependencies, namely Amesos, Amesos2, and Belos.

**Comment by mayrmt** [comment]
@searhein What's a central place to add utilities to FROSch? Is `frosch/src/tools/FROSch_Tools_*.hpp` the right place? I would add a routine along the lines of
```
    /*!
    \brief Throw runtine error due to missing package in build configuration

    As many packages are optional, we might detect only at runtime that are certain package
    is not included into the build configuration, but still is used by FROSch.
    Use this routine to throw a generic error message with some information for the user
    and details how to fix it.

    \param[in] forschObj FROSch object that is asking for the missing package
    \param[in] packageName Name of the missing package
    */
    void ThrowErrorMissingPackage(const std::string& froschObj, const std::string& packageName)
    {

      std::stringstream errMsg;
      errMsg << froschObj << " is asking for the Trilinos packate '"<< packageName << "', "
          "but this package is not included in your build configuration. "
          "Please enable '" << packageName << "' in your build configuration to be used with ShyLU_DDFROSch.";
      FROSCH_ASSERT(false, errMsg.str());

      return;
    }
```

**Comment by searhein** [comment]
@mayrmt, you are right. Currently, we collect all kinds of utilities in `frosch/src/tools/FROSch_Tools_*.hpp`
At some point, we will have to split it into multiple files. For now, you can put all kinds of utilities there. Thanks!

**Comment by mayrmt** [comment]
I've addressed this locally and will push it along with other changes.
