### ISSUE TITLE
Elevate ShyLU_Node from ST to PT since it is being used by SPARC?

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#4219]
**CC:** @trilinos/framework, @trilinos/shylu, @srajama1 (Trilinos Linear Solvers Product Area Lead)

**Blocking:** #2597 

## Description

The current SPARC Trilinos configuration explicitly enables `ShyLU_Node` subpackage `ShyLU_NodeHTS` (see [here](https://sems-atlassian-son.sandia.gov/jira/browse/TRIL-212?focusedCommentId=25503&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-25503).  Therefore, ATDM Trilinos builds supporting SPARC are enabling ShyLU_Node, for example, as shown [here](https://testing.sandia.gov/cdash-dev-view/viewConfigure.php?buildid=4427483) showing:

```
...
-- Setting Trilinos_ENABLE_ShyLU_NodeHTS=ON
-- Setting Trilinos_ENABLE_ShyLU_NodeTacho=ON
-- Setting Trilinos_ENABLE_ShyLU_Node=ON
...
Final set of enabled packages:  ... ShyLU_Node ... 41

Final set of enabled SE packages:  ... ShyLU_NodeHTS ShyLU_NodeTacho ShyLU_Node ...  112
```

So it looks like `ShyLU_NodeTacho` may be getting implicitly enabled by accident.  (We will need to see if SPARC actually using `ShyLU_NodeTacho` or not.)  But `ShyLU_NodeTacho` is already declared to be `PT` (Primary Tested) but  `ShyLU_NodeHTS` is currently declared to be `ST` (Secondary Tested).

In any case, since an important internal Trilinos customer (i.e SPARC) is using `ShyLU_NodeHTS`, [by definition](http://trac.trilinos.org/wiki/TribitsLifecycleModelOverview#test_categories), it needs to be elevated from Secondary Tested (ST) to Primary Tested (PT).  Otherwise, `ShyLU_NodeHTS` will not get enabled in Trilinos PR builds and therefore will not protect SPARC (see #2597).

## Proposed Solution

Update the line:

```
  HTS                   hts               ST       OPTIONAL
```

to be

```
  HTS                   hts               PT       OPTIONAL
```

in the file

* Trilinos/packages/shylu/shylu_node/cmake/Dependencies.cmake

**Comment by mhoemmen** [comment]
@rrdrake @theguruat12 Doesn't @crdohrm use Tacho?

**Comment by crdohrm** [comment]
Yes, Sierra-SD has an option to use Tacho as a sparse solver inside the GDSW domain decomposition solver.

**Comment by bartlettroscoe** [comment]
> Yes, Sierra-SD has an option to use Tacho as a sparse solver inside the GDSW domain decomposition solver.

The ShyLU_NodeTacho subpackage is already declared as `PT` (Primary Tested) and therefore is already included in Trilinos PR testing.

**Comment by ambrad** [comment]
IMO, switch HTS to PT. It has strong tests both in HTS and Ifpack2. It is intended to (and if SPARC is sufficient evidence, does) pass -Werror builds. It works in serial, OpenMP, MPI, Cuda builds (but does not run on GPU). The tests are short running (modulo the usual thread issues in the tests), and the build is fast, so there is not much cost to CI.

If you decide to switch HTS to PT and you encounter issues in one of these special builds, please let me know the build data, and then I will reproduce and fix the problem.

**Comment by bartlettroscoe** [comment]
> but does not run on GPU

@ambrad, does that mean we should put in an auto-disable for `The ShyLU_NodeHTS` when doing a CUDA build?

**Comment by ambrad** [comment]
If it messes up the Cuda build or testing, then yes, and I'll let you know when I have fixed that. Otherwise, it's intended to build, and the tests are intended to run, even in a Cuda build. (Cuda builds still imply code, possibly substantial bits of it, can run on the host.) The last time I looked, it built and ran cleanly everywhere.
