### ISSUE TITLE
Tpetra::BlockMultiVector doImport needs to implement "new" DistObject interface

### ISSUE THREAD

**Issue by ambrad** [trilinos/Trilinos#422]
@mhoemmen, @ambrad,

In the BCRS MVP, BMV::doImport is called. In turn, DistObject::doTransferOld is called. This is causing a large slowdown in GPU runs. This issue will track solving this problem.

Original title: "Modify Tpetra::BlockMultiVector so that useNewInterface() can be true"

**Comment by mhoemmen** [comment]
Temporary work-around: BlockCrsMatrix (BCRS) constructs and caches the point Import, then calls doImport on the MultiVectors (MVs) that live inside the BlockMultiVectors (BMVs).

Proper fix: Make BMV implement the "new" DistObject interface.  copyAndPermute (old) appears to be the bottleneck, but the interface is an all-or-nothing choice, so we'll have to implement pack and unpack on device too.  We can use MV's implementation (thanks @etphipp ! ) as a model.

**Comment by ambrad** [comment]
Progress on this issue depends on #426.

**Comment by ambrad** [comment]
#426 is done.
