### ISSUE TITLE
Minitensor produces compiler warnings with nvidia compiler 

### ISSUE THREAD

**Issue by khpierson** [trilinos/Trilinos#4220]
There are a number of warnings coming from the Trilinos package: MiniTensor. 
The Sierra team would like these removed by the next Trilinos integration. 
Would that be possible?

Thanks,
-Kendall

Here is a list of some of the warnings, note, I would expect Trilinos to already be seeing these warnings when building with nvidia (provided our compiler flags are the same across SIERRA and Trilinos.

/sierra/dev/continuous_integration/frame02/sierra.code/TPLs_src/Trilinos_flat_headers/include/MiniTensor_Utilities.i.h(280): warning #111-D: statement is unreachable

/sierra/dev/continuous_integration/frame02/sierra.code/TPLs_src/Trilinos_flat_headers/include/MiniTensor_Utilities.i.h(283): warning #111-D: statement is unreachable

/sierra/dev/continuous_integration/frame02/sierra.code/TPLs_src/Trilinos_flat_headers/include/MiniTensor_Utilities.i.h(286): warning #111-D: statement is unreachable

/sierra/dev/continuous_integration/frame02/sierra.code/TPLs_src/Trilinos_flat_headers/include/MiniTensor_Utilities.i.h(289): warning #111-D: statement is unreachable

/sierra/dev/continuous_integration/frame02/sierra.code/TPLs_src/Trilinos_flat_headers/include/MiniTensor_Utilities.i.h(295): warning #111-D: statement is unreachable

/sierra/dev/continuous_integration/frame02/sierra.code/TPLs_src/Trilinos_flat_headers/include/MiniTensor_LinearAlgebra.t.h(112): warning #111-D: statement is unreachable

/sierra/dev/continuous_integration/frame02/sierra.code/TPLs_src/Trilinos_flat_headers/include/MiniTensor_LinearAlgebra.t.h(120): warning #111-D: statement is unreachable

/sierra/dev/continuous_integration/frame02/sierra.code/TPLs_src/Trilinos_flat_headers/include/MiniTensor_LinearAlgebra.t.h(124): warning #111-D: statement is unreachable

/sierra/dev/continuous_integration/frame02/sierra.code/TPLs_src/Trilinos_flat_headers/include/MiniTensor_LinearAlgebra.t.h(164): warning #111-D: statement is unreachable

**Comment by mhoemmen** [comment]
@khpierson These look pretty easy to fix -- I think we just need to delete unnecessary `break` statements.

@lxmota , are you still working on MiniTensor?

**Comment by jhux2** [comment]
@mhoemmen Another way to get rid of this warning is to use the Teuchos macro `TEUCHOS_NONREACHABLE_RETURN`.  (But your way is faster!)

**Comment by khpierson** [comment]
Thanks for fixing these warnings. 

I will look at the sierra-trilinos nightly build that uses votd Trilinos on Monday to see if the warnings have been fixed. If so, then I guess this can be closed.

**Comment by khpierson** [comment]
Looking at the nightly dashboard, I can confirm that that the reported warnings in minitensor are fixed.

There are actually hundreds of more warnings in minitensor related to compilation with nvidia. 

Does anyone have a suggestion on how to proceed? 
Maybe we need to close this issue and collect the warnings somewhere else?

**Comment by mhoemmen** [comment]
@khpierson I think develop-to-master promotions automatically close issues based on keywords.  Should we open a new issue that says "minitensor should build warning free with NVCC"?

**Comment by lxmota** [comment]
Sorry I come late to the party, and thanks @mhoemmen for fixing the warnings. @khpierson what are the nvcc warnings?

**Comment by khpierson** [comment]
The warnings can be found on the Sierra nightly dashboard under the nvcc compiler line. I do not have the link handy but you can ask Mike V. To point you in the right direction
