### ISSUE TITLE
SPARC source build error from Tpetra_Experimental_BlockCrsMatrix_decl.hpp -Werror for shadowing warning with Clang 5.0.1 build

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#4221]
CC: @trilinos/tpetra, @kddevin  (Trilinos Data Services Product Lead), @mhoemmen, @bartlettroscoe, @fryeguy52, @micahahoward, @sebrowne 

## Next Action Status

<status-and-or-first-action>

## Description

As of the Trilinos 'develop' version 882d842b73dc475291b1e2945a9ba532577e2f1d, the Clang 5.0.1 build of SPARC (using the `cee-rhel6_clang-5.0.1_openmpi-1.10.2_serial_static_opt` build of Trilinos) is broken which uses -Werror in the build showing the build error:

```
In file included from /scratch/rabartl/SPARC.base/sparc/Trilinos/cee-rhel6_clang-5.0.1_openmpi-1.10.2_serial_static_opt/include/Xpetra_TpetraBlockCrsMatrix.hpp:53:
In file included from /scratch/rabartl/SPARC.base/sparc/Trilinos/cee-rhel6_clang-5.0.1_openmpi-1.10.2_serial_static_opt/include/Tpetra_Experimental_BlockCrsMatrix.hpp:1:
/scratch/rabartl/SPARC.base/sparc/Trilinos/cee-rhel6_clang-5.0.1_openmpi-1.10.2_serial_static_opt/include/Tpetra_Experimental_BlockCrsMatrix_decl.hpp:757:3: error: 'Tpetra::Experimental::BlockCrsMatrix<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::packAndPrepareNew' hides overloaded virtual function [-Werror,-Woverloaded-virtual]
  packAndPrepareNew (const SrcDistObject& sourceObj,
  ^
../include/linsys/MatrixTpetraBlockCrs.h:71:25: note: in instantiation of template class 'Tpetra::Experimental::BlockCrsMatrix<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >' requested here
      return tpetra_mat_->getNodeNumRows() * block_size_;
                        ^
/scratch/rabartl/SPARC.base/sparc/Trilinos/cee-rhel6_clang-5.0.1_openmpi-1.10.2_serial_static_opt/include/Tpetra_DistObject_decl.hpp:823:5: note: hidden overloaded virtual function 'Tpetra::DistObject<char, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::packAndPrepareNew' declared here: type mismatch at 3rd parameter ('Kokkos::DualView<packet_type *, buffer_device_type> &' (aka 'DualView<char *, Device<Kokkos::Serial, Kokkos::HostSpace> > &') vs 'Kokkos::DualView<impl_scalar_type *, buffer_device_type> &' (aka 'DualView<double *, Device<Kokkos::Serial, Kokkos::HostSpace> > &'))
    packAndPrepareNew (const SrcDistObject& source,
    ^
In file included from ../src/hofd-aero/AlgorithmComputeResidualVolumeCCHOFD.C:8:
In file included from ../include/hofd-core/StructuredCCHOFDDiscretization.h:11:
In file included from ../include/disc-core/StructuredDiscretization.h:11:
In file included from ../include/sparc-util/Array4D.h:27:
In file included from ../include/sparc-util/ProjectDefs.h:28:
In file included from /scratch/rabartl/SPARC.base/sparc/Trilinos/cee-rhel6_clang-5.0.1_openmpi-1.10.2_serial_static_opt/include/Xpetra_TpetraBlockCrsMatrix.hpp:53:
In file included from /scratch/rabartl/SPARC.base/sparc/Trilinos/cee-rhel6_clang-5.0.1_openmpi-1.10.2_serial_static_opt/include/Tpetra_Experimental_BlockCrsMatrix.hpp:1:
/scratch/rabartl/SPARC.base/sparc/Trilinos/cee-rhel6_clang-5.0.1_openmpi-1.10.2_serial_static_opt/include/Tpetra_Experimental_BlockCrsMatrix_decl.hpp:765:3: error: 'Tpetra::Experimental::BlockCrsMatrix<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::unpackAndCombineNew' hides overloaded virtual function [-Werror,-Woverloaded-virtual]
  unpackAndCombineNew (const Kokkos::DualView<const local_ordinal_type*, device_type>& importLIDs,
  ^
/scratch/rabartl/SPARC.base/sparc/Trilinos/cee-rhel6_clang-5.0.1_openmpi-1.10.2_serial_static_opt/include/Tpetra_DistObject_decl.hpp:889:5: note: hidden overloaded virtual function 'Tpetra::DistObject<char, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::unpackAndCombineNew' declared here: type mismatch at 2nd parameter ('const Kokkos::DualView<const packet_type *, buffer_device_type> &' (aka 'const DualView<const char *, Device<Kokkos::Serial, Kokkos::HostSpace> > &') vs 'const Kokkos::DualView<const impl_scalar_type *, buffer_device_type> &' (aka 'const DualView<const double *, Device<Kokkos::Serial, Kokkos::HostSpace> > &'))
    unpackAndCombineNew (const Kokkos::DualView<const local_ordinal_type*, device_type>& importLIDs,
    ^
2 errors generated.
```

Not clear when this first started failing since we don't have automated builds of SPARC 'master' against Trilinos 'develop' running yet (see [TRIL-243](https://sems-atlassian-son.sandia.gov/jira/browse/TRIL-243)).

## Current Status on CDash

Can't see this on CDash yet.  Instead, must build SPARC 'master' against Trilinos 'develop' as described below.

## Steps to Reproduce

Follow the directions [here](https://snl-wiki.sandia.gov/display/CoodinatedDevOpsATDM/Building+ATDM+APPs+Against+Local+Installs+of+Trilinos#BuildingATDMAPPsAgainstLocalInstallsofTrilinos-BuildingandTestingSPARCAgainstLocalTrilinosInstallation) for building SPARC 'master' against Trilinos 'develop'.  use the build name `cee-rhel6_clang-5.0.1_openmpi-1.10.2_serial_static_opt`.  To run just that build, use:

```
$ cd sparc/
$ ./sparc-tril-dev-scripts/build_and_test_atdm_trilinos_and_sparc.sh \
   cee-rhel6_clang-5.0.1_openmpi-1.10.2_serial_static_opt
```

**Comment by bartlettroscoe** [comment]
CC: @trilinos/tpetra, @kddevin, @mhoemmen , @micahahoward

If SPARC were to try to update Trilinos right now, then this error would block that update.  Not sure if there are other errors that would also block this update as well.

@mhoemmen, given that you do some SPARC development, could you try to reproduce this build error with SPARC 'master' + Trilinos 'develop' given the "Steps to Reproduce" [above](https://github.com/trilinos/Trilinos/issues/4221#issue-401172998) and see if you can fix the errors?

**Comment by mhoemmen** [comment]
@bartlettroscoe I suspect this is caused by https://github.com/trilinos/Trilinos/pull/4162 .  Clang has a different set of warnings than GCC.  Does SPARC require `-Werror` with Clang in order to accept a new Trilinos update?

**Comment by mhoemmen** [comment]
@bartlettroscoe This is probably a question for @micahahoward .  We do want to fix all the build warnings, but it's helpful to know whether this actually blocks Trilinos promotion for SPARC.

@kyungjoo-kim -- not sure if you have time to fix this.  If not, just let me know and I'll do it.

**Comment by kyungjoo-kim** [comment]
Do I need to compile sparc to reproduce this warning error ? Or does the warning pop up without sparc if I put -Woverloaded-virtual with a clang compiler ? I can try today and let @mhoemmen know if I can reproduce the warning from trilinos.

**Comment by mhoemmen** [comment]
@kyungjoo-kim Huh, this looks weird.  It looks like one of the DualView arguments to `packAndPrepareNew` and `unpackAndCombineNew` in BlockCrsMatrix has the wrong type.  (It should be `packet_type`, not `impl_scalar_type`.)  That could be bad -- it could mean that DistObject doesn't call the right methods.

**Comment by bartlettroscoe** [comment]
@kyungjoo-kim asked:

> Do I need to compile sparc to reproduce this warning error ? Or does the warning pop up without sparc if I put -Woverloaded-virtual with a clang compiler ?

The Trilinos build `Trilinos-atdm-cee-rhel6_clang-5.0.1_openmpi-1.10.2_serial_static_opt` itself as shown [here](https://testing.sandia.gov/cdash-dev-view/buildSummary.php?buildid=4434288) this morning does not show any warnings.  But these are release-mode builds (i.e. `Trilinos_ENABLE_DEVELOPMENT_MODE=OFF`) that don't set any extra warnings.   These warnings are enabled in the SPARC builds.

 But there is a good chance that you can enable these exact warning flags with the ATDM Trilinos build and see if you can get the same warnings.

We may need to think more carefully about what warning options we turn on for the ATDM Trilinos build to best support SPARC and EMPIRE.   Currently we use `Trilinos_ENABLE_DEVELOPMENT_MODE=OFF` which causes no extra warning options to get enabled beyond the default warnings the compiler spits out.

**Comment by bartlettroscoe** [comment]
Following the instructions [here](https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#cee-rhel6-environment), you may be able to reproduce these warnings with the Trilinos build on any CEE RHEL6 machine as:

```
$ cd <some_build_dir>/

$ source $TRILINOS_DIR/cmake/std/atdm/load-env.sh \
   cee-rhel6_clang-5.0.1_openmpi-1.10.2_serial_static_opt

$ cmake \
  -GNinja \
  -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
  -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_Tpetra=ON \
  -DCMAKE_CXX_FLAGS="-Wall -Werror -Wsign-compare -Wno-unused-function -Wno-error=unused-function"
  $TRILINOS_DIR

$ make NP=16

$ ctest -j16
```

If that reproduces the issue, we should consider adding those compiler flags to these 'cee-rhel6' builds.

We still need to work out how SPARC and Trilinos interact with things like this.

**Comment by kyungjoo-kim** [comment]
@bartlettroscoe Could you explain me what testbed machine is equivalent to CEE RHEL6 machine (I don't know what CEE stands for) ?

**Comment by bartlettroscoe** [comment]
> Could you explain me what testbed machine is equivalent to CEE RHEL6 machine (I don't know what CEE stands for) ?

@kyungjoo-kim, I don't there there is any SON equivalent to the CEE RHEL6 machines.  SEMS does not have a Clang 5.0.1 compiler so we can't expect to reproduce this on a standard SRN COE RHEL6 machine with the SEMS env.  We really need SEMS to install clang-5.0.1 and then we should be able to reproduce such issues on SON machines.

**Comment by bartlettroscoe** [comment]
Looks like PR #4226 merged to 'develop' on 1/23/2019 has fixed these build errors with SPARC as shown in the new SPARC 'master' + Trilinos 'develop' testing process being set up in [TRIL-243](https://sems-atlassian-son.sandia.gov/jira/browse/TRIL-243).  In particular, the 100% clean SPARC 'master' builds (against Trilinos from  1/31/2019) shown [here](http://compsim-dashboard.sandia.gov/cdash/index.php?project=SPARC&date=2019-01-31&filtercount=1&showfilters=1&field1=groupname&compare1=61&value1=Trilinos%20Integration) proves this.

Closing as complete.
