### ISSUE TITLE
Tpetra: Fix MultiVector to allow Kokkos to pad Views for alignment

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#423]
@trilinos/tpetra @hcedwar 

A while back, Kokkos turned off View padding by default, since it broke Tpetra and downstream packages.  We want to turn on padding in Kokkos again to improve vectorization.  This may require fixing things in Tpetra and downstream packages.

**Comment by rppawlo** [comment]
This definitely is an issue in panzer. We were using the get1DView accessors. Need to check with @eric-c-cyr to see if these have been removed from gather/scatter routines.

**Comment by mhoemmen** [comment]
Thanks @rppawlo !  Just to clarify, this relates to `Tpetra::MultiVector::get1dView*`.  We will need to extract a unit test that we can put in Tpetra.

**Comment by mhoemmen** [comment]
Carter tells me that padding is off by default, and can be enabled as a run-time argument at allocation.  See https://github.com/kokkos/kokkos/issues/273

**Comment by mhoemmen** [comment]
This depends on https://github.com/kokkos/kokkos/issues/324 , since it's important for Tpetra::MultiVector performance to be able to allocate its View(s) uninitialized.

**Comment by mhoemmen** [comment]
@eric-c-cyr wrote in an e-mail:
>What is the suggested conversion path. Say I always want to run on the host as a quick change, what would that entail? Wouldn’t it be a simple as calling getLocalView<????> with the correct device type? 

The quickest conversion path requires only one change to your code: stop assuming that stride == local # rows.  You’re welcome to keep using get1dView() if you like.  Just use the correct stride.  You’ll need to do that anyway if you use Kokkos::View instead of Teuchos::ArrayRCP.  For example:

```
// … X is a Tpetra::MultiVector<> …
using Teuchos::ArrayRCP;
if (X.isConstantStride ()) {
  ArrayRCP<const double> X_lcl = X.get1dView ();
  const size_t LDA = X.getStride ();
  const size_t lclNumRows = X.getLocalLength ();
  const size_t numVecs = X.getNumVectors ();
  size_t offset = 0;
  for (size_t j = 0; j < numVecs; ++j, offset += LDA) {
    ArrayRCP<const double> X_lcl_j = X_lcl (offset, lclNumRows);
    doWhateverYouWantWithCurrentColumn (X_lcl_j);
  }
}
```

**Comment by eric-c-cyr** [comment]
Okay, this is a fine approach. Though at some point we have to go to the Kokkos version (I assume). Is that the right approach? In the interest in understanding the range of possible implementations, how would you recommend doing this to a new user with no existing code? Should they use get1dView?

**Comment by mhoemmen** [comment]
At risk of sounding rude, the point of my example is to show that the original code that used get1dView*() was incorrect.  Tpetra::MultiVector never promised that stride == local # rows.  It only just happened to work.

> Though at some point we have to go to the Kokkos version (I assume). Is that the right approach? 

Yes.  Correct use of getLocalView() will help you remove dependency on UVM.  This will fend off potential accusations that "your code is slow because it relies on UVM."  Here is an example:
```
if (X.isConstantStride ()) {
  X.template sync<Kokkos::HostSpace> ();
  auto X_lcl_host = X.template getLocalView<Kokkos::HostSpace> ();
  for (size_t j = 0; j < X.getNumVectors (); ++j) {
    auto X_lcl_host_j = Kokkos::subview (X_lcl_host, Kokkos::ALL (), j);
    doWhateverYouWantWithCurrentColumnOnHost (X_lcl_host_j);
  }
}
```

**Comment by eric-c-cyr** [comment]
Okay. If you have an isConstantStride case, its conceivable you might want to do something if not constant stride. How does the code change in that context? The striding is associated with the columns in the multi-vector?

**Comment by mhoemmen** [comment]
> Okay. If you have an isConstantStride case, its conceivable you might want to do something if not constant stride. How does the code change in that context? The striding is associated with the columns in the multi-vector?

```
if (! X.isConstantStride ()) {
  for (size_t j = 0; j < X.getNumVectors (); ++j) {
    Teuchos::RCP<Tpetra::Vector<> > X_j = X.getVectorNonConst (j);

    // Don't sync the whole MV; since it doesn't have
    // constant stride, it doesn't all belong to us.
    X_j->template sync<Kokkos::HostSpace> ();

    // Get a local host view of the Vector's data
    auto X_j_lcl_2d = X_j->template getLocalView<Kokkos::HostSpace> ();
    auto X_j_lcl_1d = Kokkos::subview (X_j_lcl_2d, Kokkos::ALL (), j);

    doWhateverYouWantWithCurrentColumnOnHost (X_j_lcl_1d);
  }
}
```

**Comment by eric-c-cyr** [comment]
Great. This looks like its saying, if you always access through Kokkos, you can always fall back on the (single) vector view and it should be independent of stride with the exception of syncing and modifying. Is that accurate? Also, the modify goes after you do any modifications and will sync back to the device (presumably modify<NonHostDevice> would be called from NonHostDevice)?

**Comment by mhoemmen** [comment]
> Great. This looks like its saying, if you always access through Kokkos, you can always fall back on the (single) vector view and it should be independent of stride with the exception of syncing and modifying. Is that accurate?

Yes.  If you always work with a Kokkos::View, you never have to worry about stride.

> Also, the modify goes after you do any modifications and will sync back to the device ... ?

The modify() call just sets a flag indicating that you modified the data.  Users are responsible for sync()ing the data wherever they need it.  The standard idiom is to sync only as needed.

> (presumably modify would be called from NonHostDevice)?

sync() and modify() are called from host.  The template parameter of sync() tells it where to send the data ("sync _to_ $SPACE").  The template parameter of modify() tells it the space in which you plan to / have already modified the data.

**Comment by mhoemmen** [comment]
> The quickest conversion path requires only one change to your code: stop assuming that stride == local # rows. You’re welcome to keep using get1dView() if you like. Just use the correct stride. You’ll need to do that anyway if you use `Kokkos::View` instead of `Teuchos::ArrayRCP`.

Code that assumed that stride == local # rows was always incorrect, for as long as Tpetra has existed.  Tpetra reserves the right to change padding however it wishes.
