### ISSUE TITLE
Albany builld broken due to missing KokkosKernels_FortranMangling.h header

### ISSUE THREAD

**Issue by ikalash** [trilinos/Trilinos#4235]
Here is the error:
```
/home/ikalash/nightlyAlbanyTests/Results/Trilinos/build/install/include/KokkosBlas1_dot_tpl_spec_decl.hpp:50:10: fatal error: KokkosKernels_FortranMangling.h: No such file or directory
```
You can see more details on the Albany dashboard, e.g., http://cdash.sandia.gov/CDash-2-3-0/viewBuildError.php?buildid=80609

**Comment by ikalash** [comment]
@trilinos/kokkos-kernels

**Comment by spdomin** [comment]
Same with Nalu.. 

I opened an issue under: https://github.com/kokkos/kokkos-kernels/issues/372

**Comment by rppawlo** [comment]
also related: #4237

**Comment by mhoemmen** [comment]
Huh, well, I guess PR testing doesn't exercise this case. Let me revert the changes for now. It should be easy for me to fix.

**Comment by mhoemmen** [comment]
Other kokkos-kernels developers: These changes were a patch to Trilinos. I was about to add them to the kokkos-kernels repo as well, but these build errors show that we also need to test with Fortran disabled. Thus, these changes are not in the kokkos-kernels repo; they are only in the Trilinos repo, in develop. I have a Trilinos PR open (#4241) to revert the changes.

I think I know what to do to fix this (extra header file with "if Fortran enabled" macro to decide whether to include the Fortran mangling header file that CMake generates).

**Comment by ikalash** [comment]
Just to follow up: this issue has been resolved within Albany.

**Comment by mhoemmen** [comment]
Thanks @ikalash ! :D
