### ISSUE TITLE
kokkos-kernels: now requires fortran to configure

### ISSUE THREAD

**Issue by rppawlo** [trilinos/Trilinos#4237]
A change to kokkos-kernels last week now makes the package require fortran. This has brought down testing suite for Drekar that use the type2 stack but does not enable fortran. We are trying to avoid requiring users to have to use the kitware hacked ninja to get fortran support. Was this dependency change intended?

**Comment by rppawlo** [comment]
@mhoemmen - #4228 also broke all empire builds since they disable fortran as well.

@jmgate

**Comment by jmgate** [comment]
Yup.  If a fix is imminent, that'd be great.  Otherwise I'll look into backing out that merge commit in our fork.

**Comment by mhoemmen** [comment]
Huh, well, I guess PR testing doesn't exercise this case.  Let me revert the changes for now.  It should be easy for me to fix.

**Comment by rppawlo** [comment]
Thanks @mhoemmen !
