### ISSUE TITLE
Disable Fortran in one of the Trilinos PR builds

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#4238]
CC: @trilinos/framework, @mhoemmen, @rppawlo, @bathmatt, @jmgate, @fryeguy52 

There are several projects that disable Fortran when building Trilinos.  Currently, the EMPIRE ATDM Trilinos configuration disables Fortran.  (But that will chance once we fully merge the SPARC and EMPIRE ATDM Trilinos configurations since the SPARC configuration enables Fortran.)  The Drekar developers disable Fortran in their configurations (which is not likely to change).  Also, many people who build on Macs disable Fortran (since Macs don't come with a Fortran compiler by default).  

Therefore, it is important for Trilinos to support a Fortran-less configuration and build.  Therefore, at least one of the Trilinos PR builds needs to set `Trilinos_ENABLE_Fortran=OFF`.

**Comment by bartlettroscoe** [comment]
CC: @fryeguy52 

@mhoemmen, I added this since it looks like PR #4228 that you merged yesterday broke all of the EMPIRE ATDM Trilinos builds shown [here](https://testing.sandia.gov/cdash/index.php?project=Trilinos&date=2019-01-22&filtercount=1&showfilters=1&field1=buildname&compare1=65&value1=Trilinos-atdm-).

**Comment by bartlettroscoe** [comment]
@trilinos/framework, it seems like a good candidate Trilinos PR build to set `Trilinos_ENABLE_Fortran=OFF` would be the build `Trilinos_pullrequest_gcc_4.9.3_SERIAL`.  It seems like someone who would want to an MPI-less build of Trilinos might also want to not have to have a working version of Fortran either.

**Comment by mhoemmen** [comment]
Thanks @bartlettroscoe ; this would be super helpful :D

**Comment by mhoemmen** [comment]
> It seems like someone who would want to an MPI-less build of Trilinos might also want to not have to have a working version of Fortran either.

That's a good idea.  Most of the Fortran issues relate to TPLs and binding to non-MPI functions.

**Comment by jwillenbring** [comment]
@bartlettroscoe @mhoemmen 

This seems like a reasonable thing to do. It seems unlikely that we would have many cases where a serial no fortran build would pass, when a serial build with fortran would fail. I have fired off a build to help us look at the current situation more closely.

**Comment by bartlettroscoe** [comment]
> It seems unlikely that we would have many cases where a serial no fortran build would pass, when a serial build with fortran would fail.

Right.  Most of the Fortran/no-Fortran logic in Trilinos has nothing to do with MPI, it is all serial code.

>  I have fired off a build to help us look at the current situation more closely.

Thanks!

**Comment by jwillenbring** [comment]
@bartlettroscoe @mhoemmen @trilinos/kokkos-kernels 

I ran the SERIAL PR build with Fortran disabled (and no other changes) and got the configure error:
``
CMake Error at /projects/sems/install/rhel7-x86_64/sems/utility/cmake/3.10.3/share/cmake-3.10/Modules/FortranCInterface.cmake:205 (message):
  FortranCInterface requires the Fortran language to be enabled.
Call Stack (most recent call first):
  packages/kokkos-kernels/src/CMakeLists.txt:1 (INCLUDE)
``

Should Kokkos-kernels simply be disabled if Fortran is disabled?

**Comment by bartlettroscoe** [comment]
@jwillenbring said:

> I ran the SERIAL PR build with Fortran disabled (and no other changes) and got the configure error ...

That is error got onto 'develop' that we are trying to avoid but adding `Trilinos_ENABLE_Fortran=OFF` to this PR build :-)  See #4242 and #4241.  Please rebsae your branch on top of 'develop' and it should work now.

**Comment by jwillenbring** [comment]
@bartlettroscoe @mhoemmen 

After rebasing, things [look much better](https://testing.sandia.gov/cdash/index.php?project=Trilinos&parentid=4445043). This build ran only 3 fewer tests than [the one with fortran enabled](https://testing.sandia.gov/cdash/index.php?project=Trilinos&parentid=4444674) for comparison (although this build was not rebased, it was using develop from earlier in the day - I didn't see a need to regenerate these results).

I will see if there are any concerns about modifying the existing SERIAL PR bulid to disable Fortan at this mornings @trilinos/framework standup. If not, I don't see any impediments to pushing this.

**Comment by bartlettroscoe** [comment]
@jwillenbring, this looks good and what one would expect.  Let us know once this update gets merged.

Thanks!

**Comment by bartlettroscoe** [comment]
@trilinos/framework, it just occurred to met that it would be good to document the set of Trilinos PR builds and what each of them vary to make it clear that if you were to drop off this GCC SERIAL PR build, you loose testing with Fortran disabled, for example.  The same goes for testing with complex enabled, with OpenMP enabled, etc.  A small table on the Trilinos GitHub wiki would do the trick. 

What do you think?

**Comment by jwillenbring** [comment]
@bartlettroscoe 

> @trilinos/framework, it just occurred to met that it would be good to document the set of Trilinos PR builds and what each of them vary to make it clear that if you were to drop off this GCC SERIAL PR build, you loose testing with Fortran disabled, for example.

I updated the [existing PR testing page](https://github.com/trilinos/Trilinos/wiki/Pull-Request-Testing-Interface). This should be at least a start of what you are looking for.

**Comment by bartlettroscoe** [comment]
@jwillenbring said:

> I updated the [existing PR testing page](https://github.com/trilinos/Trilinos/wiki/Pull-Request-Testing-Interface). This should be at least a start of what you are looking for.

Thanks!  I added a bullet that the GCC 4.8.4 actually enables OpenMP (which is more than just including the pthread TPL).

**Comment by jwillenbring** [comment]
I am going to close this because #4238 was merged.

**Comment by bartlettroscoe** [comment]
> I am going to close this because #4238 was merged.

That is PR #4308, correct? Note that #4238 is this issue.
