### ISSUE TITLE
EMPIRE ATDM Trilinos builds broken that have Fortran disabled starting 1/22/2018

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#4242]
CC: @trilinos/framework, @jwillenbring  (Trilinos Framework Product Lead), @bartlettroscoe, @fryeguy52

## Next Action Status

<status-and-or-first-action>

## Description

As shown in [this query](https://testing.sandia.gov/cdash-dev-view/index.php?project=Trilinos&date=2019-01-22&filtercount=1&showfilters=1&field1=buildname&compare1=65&value1=Trilinos-atdm-) all of the ATDM Trilinos builds that have Fortran disabled failed to configure today.

## Current Status on CDash

The current status of the ATDM Trilinos builds is found on CDash [here](https://testing.sandia.gov/cdash-dev-view/index.php?project=Trilinos&filtercount=1&showfilters=1&field1=buildname&compare1=65&value1=Trilinos-atdm-).

## Steps to Reproduce

One should be able to reproduce this failure on any of the machines and builds shown above as described in:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md

**Comment by bartlettroscoe** [comment]
CC: @fryeguy52, @mhoemmen 

This is being address in PR #4228 which reverts PR #4228.

Just created this issue to make sure we log this with other ATDM Trilinos issues.

**Comment by mhoemmen** [comment]
Correction: PR #4241 reverts PR #4228 :-)

@ibaned suggests that this might still be an issue with Fortran enabled, if the generated header file doesn't get installed.

**Comment by bartlettroscoe** [comment]
The Fortran-only ATDM Trilinos builds have been fixed for some time now as shown on CDash, for example, on [1/31/2019](https://testing.sandia.gov/cdash/index.php?project=Trilinos&date=2019-01-31&filtercount=1&showfilters=1&field1=buildname&compare1=63&value1=Trilinos-atdm-).

Closing as complete.
