### ISSUE TITLE
Zoltan2 test build errors in all ATDM Trilinos CUDA builds starting 1/22/2019

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#4244]
CC: @trilinos/zoltan2, @kddevin (Trilinos Data Services Product Lead), @bartlettroscoe, @fryeguy52

<Checklist>
<???: Once GitHub Issue is created, add entries for tests to TrilinosATDMStatus/*.csv files>

## Next Action Status

<status-and-or-first-action>

## Description

The build of several Zoltan2 test object files and executables are broken in the ATDM Trilinos CUDA builds starting 1/22/2018 as shown in the builds:

* [Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-release-debug-pt](https://testing.sandia.gov/cdash-dev-view/index.php?project=Trilinos&parentid=4443057)
* [Trilinos-atdm-white-ride-cuda-10.0-gnu-7.4.0-debug-exp](https://testing.sandia.gov/cdash-dev-view/index.php?project=Trilinos&parentid=4445140)

(NOTE: It is likely broken in all of the other CUDA builds as well but we can't tell because of a configure failure in all of that ATDM Trilinos CUDA builds on 1/22/2019 as described in #4242.  The only reason that the build `Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-release-debug-pt` did not fail at configure time was that it has Fortran enabled and the only reason that the build `Trilinos-atdm-white-ride-cuda-10.0-gnu-7.4.0-debug-exp` which disables Fortran did not have configure failures is that reverting PR #4238 was merged before this build was run.)

There were also 2 new failing Zoltan2 tests as shown [here](https://testing.sandia.gov/cdash-dev-view/viewTest.php?onlyfailed&buildid=4442262) for the tests:

* Zoltan2_directoryTest_Kokkos_MPI_4
* Zoltan2_directoryTest_KokkosSimple_MPI_4

and 33 not-run tests (as you would expect given the build failures).

The new failing tests showed CUDA errors and segfaults like shown for [Zoltan2_directoryTest_Kokkos_MPI_4](https://testing.sandia.gov/cdash-dev-view/testDetails.php?test=64892618&build=4442262) showing:

```
...
 Passed: Vector_User_Multiple_GID contiguous int mode: Aggregate
Testing totalIds: 1
  Passed: Single_User_Single_GID contiguous int mode: Replace
  Passed: Single_User_Single_GID non-contiguous int mode: Replace
  Passed: Single_User_Single_GID long long mode: Replace
terminate called after throwing an instance of 'std::runtime_error'
  what():  cudaGetLastError() error( cudaErrorLaunchFailure): unspecified launch failure /home/jenkins/white/workspace/Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-release-debug-pt/SRC_AND_BUILD/Trilinos/packages/kokkos/core/src/Cuda/Kokkos_CudaExec.hpp:401
Traceback functionality not available

[white23:35877] *** Process received signal ***
[white23:35877] Signal: Aborted (6)
[white23:35877] Signal code:  (-6)
...
```

The new commits that were pulled the day that these failures started are show, for example, [here](https://testing.sandia.gov/cdash-dev-view/viewNotes.php?buildid=4443057#!#note5) which suggest that the breaking commits were from the merged PR #1533.

## Current Status on CDash

The current status of these tests/builds for the current testing day can be found [here](https://testing.sandia.gov/cdash-dev-view/index.php?project=Trilinos&filtercount=3&showfilters=1&filtercombine=and&field1=subprojects&compare1=93&value1=Zoltan2&field2=buildname&compare2=65&value2=Trilinos-atdm-&field3=buildname&compare3=63&value3=cuda).

## Steps to Reproduce

One should be able to reproduce this failure on any of the machines with a CUDA build as described in:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md

More specifically, the commands given for the system `white` or `ride` are provided at:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#ridewhite

The exact commands to reproduce this issue should be:

```
$ cd <some_build_dir>/

$ source $TRILINOS_DIR/cmake/std/atdm/load-env.sh cuda-9.2-gnu-7.2.0-release-debug

$ cmake \
  -GNinja \
  -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
  -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_Zoltan2=ON \
  $TRILINOS_DIR

$ make NP=16

$ bsub -x -Is -q rhel7F -n 16 ctest -j16
```

**Comment by bartlettroscoe** [comment]
FYI: I changed this to [`ATDM Sev: Critical`](https://snl-wiki.sandia.gov/display/CoodinatedDevOpsATDM/ATDM-Specific+Trilinos+GitHub+Labels#ATDM-SpecificTrilinosGitHubLabels-LabelsforSeverity/Criticality) because this takes out 35 Zoltan2 tests on all CUDA builds.  This should be fixed ASAP or backed out since we now have zero CUDA testing on those 35 Zoltan2 tests.

**Comment by mhoemmen** [comment]
Looks like this broke Albany too: https://github.com/trilinos/Trilinos/issues/4246

**Comment by bartlettroscoe** [comment]
CC: @trilinos/zoltan, @trilinos/framework 

@kddevin,

As this is triggering O(200) failing and notrun tests, can we back out the PR #1533 that is causing these?  Otherwise, I think we need to disable all of these tests in all CUDA builds since we can't see new failures due to this many failing tests and I don't want to add O(200) known failing tests to out `*.csv` files for our Python CDash analysis and reporting tool (see https://groups.google.com/forum/#!forum/atdm-trilinos-builds-status). 

If we are not going to back out this PR, I would propose that we disable the examples and tests that are not building and the not-run tests in the ATDM CUDA builds but list the actual failing tests in our `*.csv` file list of failing tests so that our SPARC and EMPIRE analysis emails show failing.

Okay?

----

<h2>Build and Test results for Early Promoted ATDM Trilinos Builds on 2019-01-23</h2>

<p>
<a href="https://testing.sandia.gov/cdash/index.php?project=Trilinos&amp;date=2019-01-23&amp;filtercount=1&amp;showfilters=1&amp;field1=groupname&amp;compare1=61&amp;value1=ATDM">Builds on CDash</a> (num/expected=33/33)<br>
<a href="https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&amp;date=2019-01-23&amp;filtercombine=and&amp;filtercount=2&amp;showfilters=1&amp;filtercombine=and&amp;field1=groupname&amp;compare1=61&amp;value1=ATDM&amp;field2=status&amp;compare2=62&amp;value2=passed">Non-passing Tests on CDash</a> (num=211)<br>
</p>

<p>
<font color="red">Builds Missing: bm=2</font><br>
<font color="red">Builds with Configure Failures: cf=1</font><br>
<font color="red">Builds with Build Failures: bf=6</font><br>
<font color="red">Tests without issue trackers Failed: twoif=13</font><br>
<font color="orange">Tests without issue trackers Not Run: twoinr=198</font><br>
</p>

**Comment by MicheldeMessieres** [comment]
@bartlettroscoe I've just setup PR  #4252 which should clear this up. It is all passing on white.

**Comment by bartlettroscoe** [comment]
> @bartlettroscoe I've just setup PR #4252 which should clear this up. It is all passing on white.

@MicheldeMessieres, great!  Please let use know once it merges.

**Comment by kddevin** [comment]
@MicheldeMessieres Thanks for fixing this issue so quickly (less than 18 hours after report).  The fix is already merged.

**Comment by MicheldeMessieres** [comment]
@bartlettroscoe Thanks, I had not checked them all. I'll post cdash links in the future.
