### ISSUE TITLE
Zoltan2 missing file leading to Albany build failures

### ISSUE THREAD

**Issue by ikalash** [trilinos/Trilinos#4246]
Looks like Trilinos broke the Albany nightly builds again.  Here is the error:
```
/home/ikalash/nightlyAlbanyTests/Results/Trilinos/build/install/include/Zoltan2_Directory_Impl.hpp:62:10: fatal error: murmur3.c: No such file or directory
```
Please see our dashboard for more info, e.g., http://cdash.sandia.gov/CDash-2-3-0/viewBuildError.php?buildid=80648 .

**Comment by ikalash** [comment]
@trilinos/zoltan2

**Comment by mhoemmen** [comment]
Looks like this broke ATDM too: https://github.com/trilinos/Trilinos/issues/4244

**Comment by ikalash** [comment]
This has been resolved in Albany - thank you!
