### ISSUE TITLE
Thyra/Stokhos: Attempting to create Thyra objects using the multipoint scalar type from Stokhos

### ISSUE THREAD

**Issue by jfike** [trilinos/Trilinos#425]
I am attempting to create Thyra objects using the multipoint type from Stokhos as the scalar type.  The ultimate goal would be to use Thyra model evaluators using the multipoint type in Albany.

@bartlettroscoe @etphipp 

Currently there are compiler errors when I try to create Thyra objects, such as a VectorSpace, using the multipoint type as the scalar type.  The error appears to be related to RTOpPack::PrimitiveTypeTraits.  The fix may be as simple as ensuring that these traits are defined for the multipoint type

I have created a fork, and have copied the Stokhos unit tests for Tpetra in order to start creating Thyra tests.  So far, the only change other than the name is the attempt to create a Thyra::VectorSpace in one test.  Eventually the Tpetra operations will be replaced by Thyra operations.

**Comment by bartlettroscoe** [comment]
@jfike,

You should create a branch called something like `thyra-stokos-425` and you should include `#425` in all of your commits so that it gets connected to this GitHub Issue.

Once you have something ready for me to look at, push the branch (e.g. `thyra-stokos-425`) and then do a pull-request against this repo's master branch.

**Comment by jfike** [comment]
@bartlettroscoe @etphipp 

I created a thyra-stokhos-425 branch and created a pull request #427

**Comment by bartlettroscoe** [comment]
Jeff,

I forgot to add this to my personal todo list.  I will look at this next week.

-Ross

**Comment by jfike** [comment]
Ross,
Just to summarize the current status of the issue:
- I was able to successfully create and run some tests using the multipoint type with Thyra.  To get these to work I needed to set Stokhos_ENABLE_Ensemble_Reduction = OFF in my configuration script.  I talked with Eric last week and he may implement the required traits to allow for this option to be on.
- I'm currently trying to modify Albany to allow for the multipoint type to be used with Thyra model evaluators.

Jeff

**Comment by bartlettroscoe** [comment]
Jeff,

Glad to hear that you have been able to make some progress on this.  Is there any critcal short-term show-stoppers you are currently experiencing because of this?

In any case, I will try to take a look in the next few days.

-Ross
