### ISSUE TITLE
Teuchos errors in Werror build

### ISSUE THREAD

**Issue by jwillenbring** [trilinos/Trilinos#4254]
@trilinos/teuchos 
@bartlettroscoe @hkthorn @mhoemmen 

## Expectations

Teuchos should build warning free as a matter of code quality, and because of important customer requirements.  We are currently using the following cxxflags for this build:

`-Wall -ansi -pedantic -Werror -Wno-unknown-pragmas -Wno-narrowing -Wno-pragmas -Wno-delete-non-virtual-dtor`

## Current Behavior

Currently Teuchos has a number of warnings that are promoted to errors in this build as seen [here](https://testing.sandia.gov/cdash/viewBuildError.php?buildid=4448361).

## Motivation and Context

We are working to set up dev->master and pull request builds that use these flags for GCC 7.2 to protect the code from the introduction of more warnings. We are starting with some low-level packages as some warnings from these packages have the potential to impact packages downstream in this build.
## Definition of Done

Teuchos builds warning free with the flags above for GCC 7.2.

## Steps to Reproduce

The GitHub Trilinos fork

jwillenbring/Trilinos

has a branch

jwillenbring-PR-Werror-2

that can be merged in to test via submitting a PR. If that is done, only the Teuchos changes should be merged for now (not the PR test definition changes). Alternatively, @jwillenbring can test any proposed solutions if you prefer.

**Comment by mhoemmen** [comment]
```
error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support 
...
error: identifier ‘decltype’ is a keyword in C++11 [-Werror=c++11-compat]
```
Teuchos requires C++11; we decided that a while back.  It looks like we're somehow not giving GCC 7.2 the right flags to tell it that we want C++11.

**Comment by bartlettroscoe** [comment]
That is strange because `-std=c++11` is in the compiler command-line list such as shown [here](https://testing.sandia.gov/cdash/viewBuildError.php?buildid=4448361) showing:

`"/projects/sems/install/rhel6-x86_64/sems/compiler/gcc/7.2.0/openmpi/1.10.1/bin/mpicxx" ... "-pedantic" "-Wall" "-Wno-long-long" "-Wwrite-strings" "-Wshadow" "-Woverloaded-virtual" "-g" "-std=c++11" "-ansi" "-Werror" "-Wno-unknown-pragmas" "-Wno-narrowing" "-Wno-pragmas" "-Wno-delete-non-virtual-dtor" "-O3" "-DNDEBUG" "-MD" "-MT" ... "-c" "/scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_7.2.0/Trilinos/packages/teuchos/core/test/MemoryManagement/GetBaseObjVoidPtr_UnitTests.cpp`

The problem looks to be in the C++ header file:

`/projects/sems/install/rhel6-x86_64/sems/compiler/gcc/7.2.0/base/include/c++/7.2.0/bits/c++0x_warning.h`

being read in a shown in the message:

```
In file included from /projects/sems/install/rhel6-x86_64/sems/compiler/gcc/7.2.0/base/include/c++/7.2.0/type_traits:35:0,
                 from /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_7.2.0/Trilinos/packages/teuchos/core/src/Teuchos_getBaseObjVoidPtr.hpp:52,
                 from /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_7.2.0/Trilinos/packages/teuchos/core/test/MemoryManagement/GetBaseObjVoidPtr_UnitTests.cpp:44:
/projects/sems/install/rhel6-x86_64/sems/compiler/gcc/7.2.0/base/include/c++/7.2.0/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support \
```

This does not look to be a Teuchos bug or even a CMake/TriBITS bug.  This looks to be a problem with the compiler somehow.   We are passing in `-std=c++11` and yet the compiler is including this file `c++0x_warning.h`.

**Comment by mhoemmen** [comment]
@bartlettroscoe @jwillenbring It's actually a problem with `-ansi`, not with `-Werror`.  Check out this example, that's perfectly valid C++11:

https://godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(j:1,lang:c%2B%2B,source:'%23include+%3Ciostream%3E%0A%0Aclass+Foo+%7B%0Apublic:%0A++Foo+()+%3D+default%3B%0A++template%3Cclass...+Size%3E%0A++explicit+Foo+(Size...+sizes)+%7B%7D%0A%0A++constexpr+int+thing()+const+%7B+return+42%3B%7D%0A%7D%3B%0A%0A%0Aint+main()%0A%7B%0A++++Foo+f1%3B%0A++++Foo+f2(3)%3B%0A++++return+0%3B%0A%7D'),l:'5',n:'0',o:'C%2B%2B+source+%231',t:'0')),k:38.91733723482078,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:compiler,i:(compiler:g72,filters:(b:'0',binary:'1',commentOnly:'0',demangle:'0',directives:'0',execute:'1',intel:'0',libraryCode:'1',trim:'1'),lang:c%2B%2B,libs:!(),options:'-std%3Dc%2B%2B11+-Werror+-ansi',source:1),l:'5',n:'0',o:'x86-64+gcc+7.2+(Editor+%231,+Compiler+%231)+C%2B%2B',t:'0')),k:36.338127990616535,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:output,i:(compiler:1,editor:1,wrap:'1'),l:'5',n:'0',o:'%231+with+x86-64+gcc+7.2',t:'0')),k:24.74453477456269,l:'4',n:'0',o:'',s:0,t:'0')),l:'2',n:'0',o:'',t:'0')),version:4

It builds fine with `-std=c++11 -Werror`, but errors out with `-std=c++11 -Werror -ansi`.

**Comment by mhoemmen** [comment]
btw, godbolt.org is THE BEST :D

**Comment by jwillenbring** [comment]
@bartlettroscoe @mhoemmen 

Thanks guys. I was confused by this with Kokkos previously too. I am going to verify that the set of flags I am using is still current.

**Comment by bartlettroscoe** [comment]
> It builds fine with `-std=c++11 -Werror`, but errors out with `-std=c++11 -Werror -ansi`.

Perhaps it is time to remove '-ansi'?  Why would '-ansi' trigger an error like this?

**Comment by mhoemmen** [comment]
@rrdrake @theguruat12 @micahahoward It looks like GCC 7.2's `-ansi` flag is broken?

**Comment by mhoemmen** [comment]
https://gcc.gnu.org/onlinedocs/gcc-8.2.0/gcc/C-Dialect-Options.html#C-Dialect-Options

"In C mode, this [the `-ansi` flag] is equivalent to `-std=c90`. In C++ mode, it is equivalent to `-std=c++98`."

**Comment by mhoemmen** [comment]
So, the flag is not broken, it's just not what we want any more ;-)

**Comment by mhoemmen** [comment]
The `-pedantic` option (without `-ansi`) works fine with both GCC 7.2 and GCC 8.2.

**Comment by jwillenbring** [comment]
This was resolved as part of the larger Werror effort.
