### ISSUE TITLE
TriKota: Build errors with Dakota 6.8 and newer

### ISSUE THREAD

**Issue by briadam** [trilinos/Trilinos#4270]
@trilinos/trikota

## Expectations

Trilinos should work when TriKota is enabled with Dakota 6.8 and newer.

## Current Behavior
Build fails due to Dakota not being able to find ROL headers. (Dakota now has an optional dependence on ROL)

## Motivation and Context
Trying to verify that recent changes in Dakota will not break TriKota users of Dakota.

## Definition of Done

Enabling TriKota should build and test with Dakota 6.8 or newer.

## Possible Solution

Ideally, want to allow TriKota/Dakota to use Trilinos ROL, however, this results in a circular dependency because ROL has an optional dependence on TriKota. For now, recommend workaround where Dakota's ROL is disabled when building under TriKota.

## Steps to Reproduce

Clone Trilinos, checkout devel, place Dakota in trilinos/packages/TriKota/Dakota. Configure Trilinos with TriKota enabled, get build error at make time.

## Your Environment

- **Relevant repo SHA1s:** Trilinos master at 4f15e6fb356295d8ba1e022e94d8b0bad732e082
- **Relevant configure flags or configure script:**  
```
cmake \
-DCMAKE_BUILD_TYPE=RELEASE \
-DCMAKE_INSTALL_PREFIX=../install \
-DBUILD_SHARED_LIBS:BOOL=TRUE \
-DTrilinos_ENABLE_TESTS:BOOL=ON \
-DTrilinos_ENABLE_Teuchos:BOOL=ON \
-DTrilinos_ENABLE_ROL:BOOL=ON \
-DTrilinos_ENABLE_TriKota:BOOL=ON \
-DTrilinos_ENABLE_ALL_PACKAGES:BOOL=OFF \
-DTrilinos_ENABLE_ALL_FORWARD_DEP_PACKAGES:BOOL=OFF \
-DTrilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=ON \
-DTrilinos_ENABLE_COMPLEX_DOUBLE:BOOL=ON \
../source
```
- **Operating system and version:**  RHEL 7.6
- **Compiler and TPL versions:**  Default RHEL7 toolchain (gcc-4.8.5) and TPLs

**Comment by briadam** [comment]
I should have mentioned (perhaps its obvious) this is only a problem when configuring with ROL enabled. Moreover, additional fixes are needed to restore ROL adapters/trikota tests (submitted separately to upstream ROL developers).

**Comment by mhoemmen** [comment]
@trilinos/rol @trilinos/trikota

**Comment by rhoope** [comment]
@briadam I'm about to open a new and related issue and wanted to make sure this one has been sufficiently resolved?

**Comment by briadam** [comment]
I think so @rhoope. It's a workaround, but I don't think anyone cares enough to resolve it in a more nuanced way. TriKota users won't be able to use the ROL solver in Dakota, but presumably they can use ROL directly if crucial. I'll close it.
