### ISSUE TITLE
Add keyword 'complex' to ATDM Trilinos builds for Gemma builds

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#4273]
**CC:** @fryeguy52 

## Description

The ATDM code Gemma requires complex support enabled in Trilinos.  To support this, the ATDM Trilinos builds need to support a new `complex` keyword that when added to the build name will enable `Trilinos_ENABLE_COMPLEX=ON`.  (NOTE: Setting `Trilinos_ENABLE_COMPLEX=ON` will only enable `Trilinos_ENABLE_COMPLEX_DOUBLE=ON` by default if `Trilinos_ENABLE_FLOAT=OFF`, which is the default value for float support.)

**Comment by lucbv** [comment]
@bartlettroscoe so to be clear do we need to support both `Trilinos_ENABLE_COMPLEX_DOUBLE=ON` and `Trilinos_ENABLE_COMPLEX_FLOAT=ON` or are we OK if we only support `Trilinos_ENABLE_COMPLEX_DOUBLE=ON`?

Also will complex be enabled in all builds or just specific ones? If the latter is chosen, can we avoid adding it to the `intel` build, it is already slow enough as it is...

**Comment by bartlettroscoe** [comment]
@lucbv, as described [above](https://github.com/trilinos/Trilinos/issues/4273#issue-403438061), this is only going to impact the ATDM Trilinos builds and there only `Trilinos_ENABLE_COMPLEX_DOUBLE=ON` is going to be enabled (since `Trilinos_ENABLE_COMPLEX_DOUBLE=ON` by default since `Trilinos_ENABLE_FLOAT=OFF` by default). 

I don't see a GitHub issue for enabling complex support Trilinos PR builds but see #4196?

**Comment by bartlettroscoe** [comment]
With the merge of PR #4524, this should not be complete.  Closing as complete.
