### ISSUE TITLE
ShyLU_DD/FROSch: Interface for each block is needed otherwise code stops.

### ISSUE THREAD

**Issue by chochmuth** [trilinos/Trilinos#4276]
@trilinos/shylu 
With the introduction of the new graph interface entity structure, some new functions were implemented which do not account for "empty" blocks. Here, an empty block is either a block where no interface was identified or a block which is not contributing to the corresponding coarse space (user choice). For example in `FROSch_GDSWCoarseOperator_def.hpp:345`   
`for (UN i=0; i<interface->getEntity(0)->getNumNodes(); i++) {`
asserts to false for `getEntity(0)`, as `interface` might be empty.

**Comment by searhein** [comment]
@chochmuth Thanks for pointing this bug out. I will fix it hopefully this week.
