### ISSUE TITLE
Tpetra: sort and merge on insert: CrsGraph::insertLocalIndices

### ISSUE THREAD

**Issue by tjfulle** [trilinos/Trilinos#4279]
## What

Sort and merge new indices in `CrsGraph::insertLocalIndices`

## Why

`CrsGraph` does not sort/merge new indices. Instead, indices are appended to their row of the graph, regardless if they are already present in the row.  During `fillComplete`, rows are sorted/merged so that duplicate entries are "compressed" out.  For `StaticProfile` graph, this can lead to running out of capacity due to duplicate entries.

@trilinos/tpetra 

## Related Issues
#4278

**Comment by mhoemmen** [comment]
Closed by PR #4733.
