### ISSUE TITLE
Tpetra: sort and merge values: CrsMatrix::insertGlobalValues

### ISSUE THREAD

**Issue by tjfulle** [trilinos/Trilinos#4280]
## What

Sort and merge new values in `CrsMatrix::insertGlobalValues`

## Why

`CrsMatrix::insertGlobalValues` does not sort/merge existing values. Instead, indices/values are appended to their row of the matrix, regardless if they are already present in the row.  During `fillComplete`, rows are sorted/merged so that duplicate entries are "compressed" out.  For `StaticProfile` matrix, this can lead to running out of capacity due to duplicate entries.

@trilinos/tpetra 

## Related Issues
#4278, #4279

**Comment by mhoemmen** [comment]
Closed by PR #4733.

**Comment by tjfulle** [comment]
Thanks @mhoemen!
