### ISSUE TITLE
Tpetra: sort and merge values: CrsMatrix::insertLocalValues

### ISSUE THREAD

**Issue by tjfulle** [trilinos/Trilinos#4281]
## What

Sort and merge new values in `CrsMatrix::insertLocalValues`

## Why

`CrsMatrix::insertLocalValues` does not sort/merge existing values. Instead, indices/values are appended to their row of the matrix, regardless if they are already present in the row.  During `fillComplete`, rows are sorted/merged so that duplicate entries are "compressed" out.  For `StaticProfile` matrix, this can lead to running out of capacity due to duplicate entries.

@trilinos/tpetra 

## Related Issues
#4278, #4279, #4280

**Comment by tjfulle** [comment]
This is done in #4733.  indices are not sorted/merged, but are unique.

**Comment by mhoemmen** [comment]
Closed by PR #4733.
