### ISSUE TITLE
Tpetra: update tests to StaticProfile

### ISSUE THREAD

**Issue by tjfulle** [trilinos/Trilinos#4282]
## What

Update Tpetra tests to pass if default profile type is `StaticProfile`

## Why

`DynamicProfile` is the current default profile type for `Tpetra::CrsMatrix` and `Tpetra::CrsGraph` but is being deprecated in favor of `StaticProfile`

@trilinos/tpetra 

## Related Issues
#4278, #4279, #4280, #4281

**Comment by tjfulle** [comment]
@GeoffDanielson this is done, right?

**Comment by mhoemmen** [comment]
This is done.
