### ISSUE TITLE
Tpetra: update tests to StaticProfile (downstream packages)

### ISSUE THREAD

**Issue by tjfulle** [trilinos/Trilinos#4283]
## What

Update Tpetra's downstream tests to pass if default profile type is `StaticProfile`

## Why

`DynamicProfile` is the current default profile type for `Tpetra::CrsMatrix` and `Tpetra::CrsGraph` but is being deprecated in favor of `StaticProfile`

@trilinos/tpetra 

## Related Issues
#4282

**Comment by GeoffDanielson** [comment]
Verified Amesos2, Anasazi, Belos, Ifpack2, and Muelu as of 2/8.

**Comment by mhoemmen** [comment]
This is done.
