### ISSUE TITLE
Tpetra: matrix market reader to return StaticProfile containers

### ISSUE THREAD

**Issue by tjfulle** [trilinos/Trilinos#4284]
## What

Update Tpetra matrix market reader to return graphs and matrices with `StaticProfile`

## Why

`DynamicProfile` is the current default profile type for `Tpetra::CrsMatrix` and `Tpetra::CrsGraph` but is being deprecated in favor of `StaticProfile`.

@trilinos/tpetra 

## Related Issues
#4282, #4283

**Comment by tjfulle** [comment]
@GeoffDanielson, this may have already been merged with your work?

**Comment by GeoffDanielson** [comment]
@tjfulle it looks like it's in the tjfulle fork?

**Comment by tjfulle** [comment]
Probably?  Most of those branches are stale.  Your branch may be the only up to date working version.

**Comment by GeoffDanielson** [comment]
@tjfulle I can pull the MatrixMarket_Tpetra.hpp into a branch and create an MR for it, would that work?

**Comment by tjfulle** [comment]
@GeoffDanielson this is probably taken care of with your merge of the tests, right?

**Comment by mhoemmen** [comment]
This is done.
