### ISSUE TITLE
Tpetra: Consolidate reduceAll in noncontiguous Map constructor

### ISSUE THREAD

**Issue by DrBooom** [trilinos/Trilinos#43]
@trilinos/tpetra 

The noncontiguous Tpetra::Map constructor has a reduceAll at line 465 of Tpetra_Map_def.hpp:

```
 if (numGlobalElements != GSTI) {
      numGlobalElements_ = numGlobalElements; // Use the user's value.
    } else { // The user wants us to compute the sum.
      reduceAll<int, GST> (*comm, REDUCE_SUM, as<GST> (numLocalElements),
                           outArg (numGlobalElements_));
    }
```

And one at line 616:

```
  GO minMaxOutput[3];
      minMaxOutput[0] = 0;
      minMaxOutput[1] = 0;
      minMaxOutput[2] = 0;
      reduceAll<int, GO> (*comm, REDUCE_MAX, 3, minMaxInput, minMaxOutput);
      minAllGID_ = -minMaxOutput[0];
      maxAllGID_ = minMaxOutput[1];
      const GO globalDist = minMaxOutput[2];
```

Mark thinks that these could be fused into a single call. Since this Map constructor is one of the most expensive and frequent calls in the R4-5 scaling, any reduction in all-reduce calls will help.

**Comment by mhoemmen** [comment]
The challenge here is that the second all-reduce currently depends on the result of the first.  Specifically, `minMaxInput[2]` depends on `numGlobalElements_`.  Fusing the two all-reduces would require figuring out how to get both `numGlobalElements_` and `localIsDist` at the same time.

**Comment by DrBooom** [comment]
If instead of directly reducing to numGlobalElements_, why not pass a vector of length of number of procs, with numLocalElements inserted into a vector of zeros, in mpi-rank position. Then you have all the local numLocalElements, and can do a local computation of

localDist.

   Better yet, swap minMyGid and maxMyGid, then each proc can process for min, max, localDist numLocalElements_ and do the test on

Tpetra::Details::OrdinalTraits<GO>::invalid()) for the minMyGID_ and maxMyGID_. Kill 2.5 FIXME's with one (moderatly hefty) stone.




Chris Luchini
ORG 1443
Sandia National Laboratory
(505) 284 3484
(505) 690 5008 Cell (505) is required.
________________________________

**Comment by mhoemmen** [comment]
MPI_Allreduce of a length-(# procs) array is pretty heavyweight.  Tpetra::Distributor does this at one point (as part of Import / Export setup), but users accept that this is a heavier-weight operation than Map construction.  It's fine if # procs is small, but MPI implementations use more expensive send and receive operations for larger messages.

**Comment by mhoemmen** [comment]
However, per your second paragraph above, I'm pretty confident that we could compute all those four things in a single all-reduce with a custom MPI_Op.  Custom MPI_Op may have a performance penalty on some networks compared with simple integer min / max / sum, but it might be worthwhile.

**Comment by DrBooom** [comment]
I accept that a # procs all reduce is heavy, but is is heavier than 2 vanilla all reduces? I doubt it, but welcome being proven wrong. The custom MPI_Op would likely be the better option, but since I've never used them, I've got no intuition as to the cost.


I would like to see both variations tested at scale ~2k nodes


Chris Luchini
ORG 1443
Sandia National Laboratory
(505) 284 3484
(505) 690 5008 Cell (505) is required.
________________________________

**Comment by csiefer2** [comment]
Alternative idea: Could we add an option to the constructor that allows lazy evaluation of those quantities (so you can build a map with no communication) and then have them evaluate on call instead?

**Comment by mhoemmen** [comment]
@csiefer2 With the contiguous nonuniform Map constructor, each process needs the result of the MPI scan to find out what its global indices are.  Since getGlobalElement and getLocalElement never require communication, we couldn't do the scan lazily.  

We could instead add a new contiguous nonuniform Map constructor that takes each process' starting global index, as well as the global and local index counts.  That would obviate the scan, as long as users already know that information.

Another idea would be to combine the scan with all-reduces, using a very clever custom MPI_Op.

**Comment by csiefer2** [comment]
I spoke with Mark and we agreed that we should try adding an additional constructor which allows you to provide the things which we're reducing to calculate (since the DomainMap knows min/max GIDs and we can lie about numGlobalElements).  Then use that and see what happens.

**Comment by mhoemmen** [comment]
Chris' alternate idea was to change Map semantics to support lazy initialization.  This could make sense for the noncontiguous Map constructor (the one that takes a list of global indices on each MPI process).  However, it would change some Map methods (e.g., getGlobalNumElements()) from local to collective.  This could make users' code deadlock if they don't expect the change.  Chris suggested that we could let users pass an option to the constructor for lazy initialization, and have it be off (don't be lazy) by default, for backwards compatibility.

These are all good ideas, but I think it makes more sense first to figure out whether this is really the performance issue.

**Comment by DrBooom** [comment]
I've put barriers before each of the reduceAll calls in Map::Map, and will re-run on the R3 problem, hopefully tonight.



Chris Luchini
ORG 1443
Sandia National Laboratory
(505) 284 3484
(505) 690 5008 Cell (505) is required.
________________________________

**Comment by mhoemmen** [comment]
I'm calling this an "enhancement" because it's not clear how important this is (that doesn't mean it's _not_ important, just that we haven't evaluated its importance yet, nor do we have a customer demand indicating its importance).

**Comment by mhoemmen** [comment]
I'm calling this a "story" because it's not clear what the tasks are yet.
