### ISSUE TITLE
KokkosKernels,Tpetra: Plug in TPLs (MKL, cuSPARSE, ...) for sparse matrix-matrix multiply

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#430]
@trilinos/tpetra @trilinos/muelu @mndevec @csiefer2 

See #147 for discussion.
Depends on #148 (otherwise we can't plug in a local kernel).
Depends on #415 (MKL sparse matrix-matrix multiply wants to own deallocation of the result matrix's arrays, so Kokkos can't own them; deallocation has to happen in the handle)

**Comment by kddevin** [comment]
Discussion with @csiefer2 today:
@csiefer2 will be the assignee; targeting FY17 Q1-Q2 for the work.

**Comment by mhoemmen** [comment]
@csiefer2 discovered possible bugs in MKL's sparse matrix-matrix multiply, for the case of empty rows and/or columns in the input matrices.  This suggests that we should avoid relying on MKL for this critical kernel.

**Comment by nmhamster** [comment]
@mhoemmen - can you provide a small reproducer so we can file a bug report?

**Comment by mhoemmen** [comment]
@csiefer2, would you happen to know what matrices didn't work with MKL's implementation?

**Comment by srajama1** [comment]
Note that KokkosKernel SpGEMM is anyway faster than MKL (except when using small number of threads *and* there is no reuse of structure). So we might not rely on it anyway.

**Comment by maherou** [comment]
In the long run, we want MKL to work well.  If it’s not too much work, it would be good to provide them a test case, or at least mention this result to them.  We want their kernels to be fast, so there is less work for us.

**Comment by mhoemmen** [comment]
I just heard from @csiefer2 today about this.  I know his time is limited this fiscal year, so if he finds something, he should feel welcome just to point out the example (e.g., test number or matrix file) and put the rest of us to work in helping him turn that into a test case for MKL.

**Comment by csiefer2** [comment]
Mehmet already has a lists of problems where MKL doesn't work.

**Comment by mhoemmen** [comment]
@mndevec , would you happen to have some matrices that are known to fail with MKL?  Thanks!

**Comment by mndevec** [comment]
@mhoemmen 
In my case, MKL does not complete (in ~20 min) with 256 threads on KNL (with intel 17~). The matrices I tried are laplace and brick matrices. I can provide the matrix market formats for those.

Mehmet

**Comment by nmhamster** [comment]
@mndevec please can you supply these so we can file an issue with Intel?

**Comment by mhoemmen** [comment]
@mndevec wrote:
> ... MKL does not complete (in 20 min) with 256 threads on KNL (with intel 17) for laplace and brick matrices.

Wow ;-P

**Comment by mndevec** [comment]
@nmhamster 
The matrices are a bit large, laplace A and P matrices are located under /home/mndevec/matrix_market
in bowman.

**Comment by mndevec** [comment]
By the way, I am using inspector executor with the function: mkl_sparse_spmm. 
There is another function in MKL for matrix-matrix multiply. I will plug that in the coming weeks.
