### ISSUE TITLE
MueLu: structured region driver

### ISSUE THREAD

**Issue by lucbv** [trilinos/Trilinos#4304]
@trilinos/muelu 
@rstumin @mayrmt @pohm01 

## Expectations
This new driver constructs a problem on a perfectly structured grid and provides necessary data for HHG region matrix construction

## Motivation and Context
This driver will provide a testing ground for new HHG capabilities on a simple mesh.

**Comment by lucbv** [comment]
PR #4310 implements the 2D case and started on the 3D case.
I will try to finish the 3D case quickly to give us a good starting point to test the HHG approach.

**Comment by lucbv** [comment]
@pohm01 update the driver's code and we have a new PR: #4339, that fixes the 2D case and implements the 3D case.
@mayrmt,  I tested the example you presented above and it works fine, we should probably poke at the 3D case to make sure it does fine, but hopefully this will provide enough capabilities for now.

**Comment by mayrmt** [comment]
@lucbv I ran a 3D case with 8 regions (with in total 7x7x7 nodes) and 27 regions (with in total 10x10x10 nodes) and looked at the number of send/received GIDs per proc. That looked good. I didn't check every single GID as it's kind of hard to draw the little picture in 3D. Any ideas how we can really verify that?

**Comment by pohm01** [comment]
@mayrmt @lucbv I found the most useful test was doing something like 27 regions with 3x3x3 nodes, so each region only owns one node.

**Comment by mayrmt** [comment]
@pohm01 did you check send/receive GIDs for this case? I guess that every GID should be send to neighboring processes as every GID needs to be duplicated, right?

**Comment by pohm01** [comment]
@mayrmt I did check the send/receive GIDs for this case, and each GID got sent out to neighbors with higher proc number (adjacent, diagonal, and corner neighbors). The receive is easy to check in this case as the proc id ends up being equal to the GID.

**Comment by lucbv** [comment]
@pohm01 @mayrmt PR #4339 has now been merged, I will run some local test with the 3D version some time this week and let you know if I see anything suspicious but that should be it.
Do we want to push further to get the multiple dofs/node case implemented?
I guess we can talk about this tomorrow.

**Comment by mayrmt** [comment]
@lucbv @pohm01 The multipler DOFs per node case would be a natural next step and would allow us to run much nicer examples. However, I also see two other issues that are more important from a short-term perspective, namely migrating the HHG driver to Xpetra (cf. #4084) and getting the hybrid structured/unstructured aggregation to work (at least for a simple example). Let's discuss this tomorrow!

**Comment by lucbv** [comment]
With the recent PR #5211 merged we are now able to run 3D case which is a good step forward.
I am also adding some small improvement in PR #5232, we are now checking the relative norm of the residual against the tolerance instead of the absolute norm. This will avoid having us try to converge to a tolerance tighter than machine precision.
The final step for this driver will probably be to allow for multiple dofs per node.

**Comment by lucbv** [comment]
So with PR #5466 merged I think that we have achieved all we wanted in terms of features for the driver.
I will close this now but might expect to have to open other issues related to this if any unexpected behavior is observed with the driver.
