### ISSUE TITLE
MueLu: CoalesceDropFactory builds Import object ex nihilo, if we amalgamate

### ISSUE THREAD

**Issue by csiefer2** [trilinos/Trilinos#4309]
We should be able to amalgamate an importer.

Filing for future consideration.

**Comment by mhoemmen** [comment]
Does "amalgamate" mean a set union of Imports?

**Comment by lucbv** [comment]
@mhoemmen, amalgamate means reducing a problem from multiple dofs per node to single dof per node. So for a 3D vectorial problem with `3n` unknowns we want to get a problem with `n` unknowns, hence the importer needs to be `amalgamated`.

**Comment by mhoemmen** [comment]
@lucbv thanks!  I think I get it now -- you want to use already known DOF ownership information to construct the new Import object.

**Comment by csiefer2** [comment]
And do it without communication.
