### ISSUE TITLE
Tpetra::getDefaultComm fails after calling Tpetra::initialize

### ISSUE THREAD

**Issue by rwirth** [trilinos/Trilinos#432]
The second line of the following snippet throws an exception claiming that Tpetra::initialize has not been called

    Tpetra::initialize (&argc, &argv);
    RCP<const Teuchos::Comm<int> > comm = Tpetra::getDefaultComm ();

The issue is probably a missing negation in line 100 of packages/tpetra/core/src/Tpetra_Core.cpp. Also, Tpetra::finalize is missing a prototype in Tpetra_Core.hpp

**Comment by mhoemmen** [comment]
@rwirth Thanks for reporting!  Please refer to #194 discussion.  In particular, if your application uses any of {Kokkos, MPI, OpenMP, CUDA} on its own, outside of Trilinos objects and functions, then your application should initialize whatever it uses outside of Trilinos.  If Kokkos and MPI have been initialized, then you don't need to call Tpetra::initialize.

**Comment by mhoemmen** [comment]
I'll defer exposing Tpetra::finalize until #434 is fixed.  I'll fix the getDefaultComm issue though.

**Comment by mhoemmen** [comment]
@rwirth Note that I've only fixed this in the `develop` branch.  We just switched over to a two-branch `develop` / `master` repo model this week.  Changes in `develop` get propagated to `master` frequently but not instantaneously.
