### ISSUE TITLE
MueLu: why using `linAlgebra=Epetra` with unit_tests_kokkos?

### ISSUE THREAD

**Issue by lucbv** [trilinos/Trilinos#4325]
@trilinos/muelu

## Expectations
It should be possible to use all of `kokkos` and `kokkos-kernels` in functions marked `_kokkos` in MueLu. Otherwise what is the point of the kokkos refactor?

## Current Behavior
`unit_tests_kokkos.exe` is called with both `linAlgebra=Tpetra` and `linAlgebra=Epetra`

## Motivation and Context
Running these kokkos specific unit tests with `linAlgebra=Epetra` pretty much guarantees a problematic behavior and a failing test...

## Definition of Done
MueLu team members need to discuss the need for the `linAlgebra=Epetra` test of the kokkos refactor path in MueLu, if there is a legitimate reason for this behavior we then also need to come up with a reasonable way to still allow kokkos refactor work to happen while this restriction is applied.

**Comment by csiefer2** [comment]
I have no problem with banning Epetra matrices w/ Kokkos refactor... as long as the non-Kokkos code path still exists.

The problem comes when we try to eliminate the non-Kokkos code path AND still support Epetra.

**Comment by jhux2** [comment]
@lucbv and I have discussed this offline.  For the life of me I can't remember what the rationale (if any) there was for testing Kokkos factories with Epetra.  I am in favor of dropping Epetra from these tests.

**Comment by lucbv** [comment]
@jhux2 @csiefer2 I have created a PR to remove these tests (finally), I think that if we really wanted to run these type of tests we should do it in builds with `Tpetra=OFF` which of course would not work...
The only thing that was potentially tested here is that `Xpetra` can create Tpetra objects with an `EpetraNode`.

**Comment by lucbv** [comment]
The merge of PR #5302 fixed this so I am closing the issue
