### ISSUE TITLE
Catalyst IOSS Adapter Python Imports

### ISSUE THREAD

**Issue by jrood-nrel** [trilinos/Trilinos#4327]
@tjotaha @jeffmauldin I have one more question about the Catalyst IOSS adapter. I am working on a pull request for Spack regarding this here https://github.com/spack/spack/pull/10501 that might give some more information. Basically if I don't have the Paraview `site-packages/vtkmodules` in the `PYTHONPATH`, then the `phactori.py` file can't import `vtkParallelCorePython`:
```
/python/phactori.py", line 1897, in SmartGetLocalProcessId
    import vtkParallelCorePython
ImportError: No module named vtkParallelCorePython
```
Would the better fix be to update the import in the IOSS adapter to account for this, or will the `vtkmodules` be required in the `PYTHONPATH` when loading a Paraview module?

**Comment by tjotaha** [comment]
@jrood-nrel I talked to Jeff briefly about this issue. There may be a way to use the rpath information during the Catalyst IOSS adapter build to allow Python to find the libraries down in site-packages/vtkmodules. For right now, you have to set PYTHONPATH. We will experiment a bit and let you know if the rpath approach is viable.

**Comment by jrood-nrel** [comment]
Thanks for looking into this @tjotaha . The `vtkmodules` directory was included in the PYTHONPATH in Spack, so I am going to close this. I think that solution is pretty simple for this issue.
