### ISSUE TITLE
Ifpack2: BlockTriDi test does (bool > 1); probably meant just to eval the bool

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#4343]
@trilinos/ifpack2 

NVCC warned about the following line evaluating a `bool > 1` expression, that's always false. https://github.com/trilinos/Trilinos/blob/e476b66bcdd0fb2efa6018a4d5ff10f5bb02d2b9/packages/ifpack2/test/unit_tests/Ifpack2_UnitTestBlockTriDiContainerUtil.hpp#L249

**Comment by mhoemmen** [comment]
@kyungjoo-kim No pressure :-) I would have fixed it myself but I wanted my big DistObject DualView PR in first and didn't want to mix too many other things into it.

**Comment by ambrad** [comment]
@kyungjoo-kim I'll take care of this.

**Comment by kyungjoo-kim** [comment]
@ambrad It is a simple fix so I am fine whoever includes this fix. I am working on ifpack2 gpu improvement 
(https://github.com/kyungjoo-kim/Trilinos/tree/ifpack2-develop) and will submit a PR today. I can include this, too.

**Comment by ambrad** [comment]
I just posted PR #4387. Feel free to close it w/o merging. I decided I should take this b/c the seq_method corner case may not have been obvious to you.

**Comment by kyungjoo-kim** [comment]
Thanks.

**Comment by mhoemmen** [comment]
Thanks @ambrad ! :D

**Comment by mhoemmen** [comment]
Thanks @kyungjoo-kim ! :D
