### ISSUE TITLE
(C)Make fails at Scotch on various systems

### ISSUE THREAD

**Issue by LennartSchu** [trilinos/Trilinos#4364]
@trilinos/shylu 

Hello,
I'm currently trying to build the ShyLU-package with the Basker solver on my systems. I've tried that on a Ubuntu 16.04.5 LTS xenial Server and a Fedora Workstation. Building the packages works on neither one of them with different errors. However, both errors seem to be caused by the Scotch-package.

In order to make sure that this error is not due to my system, I'm asking you to provide information about the system (OS, version, version of gcc, cmake, etc.) with which you build the Basker-Library in ShyLU. The README.txt in Trilinos/packages/shylu/shylu_node/Basker includes the info "Currently, it is unknown how Basker will behave on a random system and with HWLOC.", which is why I ask about your set up.

## Current Behavior
On Ubuntu, you have to build scotch version 6.0.3 by yourself since the most recent one provided by the official Ubuntu-repositories is version 5.1. Doing so, the CMake command (you find the exact commands below) runs fine and Scotch is included. However, running "make" gives numerous errors caused by scotch, first one of which is:

/home/om/Trilinos/packages/shylu/shylu_node/basker/src/shylubasker_order_scotch.hpp:186:5: error: ‘SCOTCH_Strat’ was not declared in this scope
     SCOTCH_Strat strdat;

which indicates that Scotch is not actually linked in the process. My effort of debugging the error came to the conclusion that it might be due to the inclusion of the C-code into a C++-library. Scotch is written in C, but not included into the C++ code of Basker using an 'extern "C"'-statement. It might be that the version of g++ on the server (which is 5.5.0) does not support this.

Running the same CMake-command on the Fedora Workstation (which provides Scotch 6.0.7 in the repositories) fails at checking the scotch version:

HAVE_SCOTCH_VERSION_6_0_3 - Failure

even though Version 6.0.3 (or newer) is installed and cmake finds the libraries.

## Motivation and Context
I'm currently working on including Basker into the ida/sundials library. I've already included the NicsLU-solver into that library after observing that it is quicker in a testing environment I've set up for linear solvers. In my next step, I want to implement Basker into that testing enviroment to determine whether it would be useful for large-scale power system simulations. Finding quicker solvers is useful for both research and companies (e.g. transmission system operators) that use simulation software to provide stability and safety of the power supply of their customers. 

## Steps to Reproduce
On Ubuntu 16.10 LTS:
1. Install Scotch 6.0.3 (or higher) manually and install it (here in /usr/local)
1. run cmake -DTrilinos_ENABLE_ShyLU=ON -DTrilinos_ENABLE_ShyLUBasker=ON -DTrilinos_ENABLE_ShyLU_NodeBasker=ON -DTPL_ENABLE_OpenMP=ON -DTrilinos_ENABLE_Kokkos=ON -DTrilinos_ENABLE_ShyLU_DD=ON -DTrilinos_ENABLE_ShyLU_DDBDDC=ON -DTPL_ENABLE_MPI=ON -DTrilinos_ENABLE_OpenMP=ON .. 
1. run make

On Fedora Workstation:
1. Install Scotch (either using the official repositories or manually, the error will be the same)
1. run cmake -DTrilinos_ENABLE_ShyLU=ON -DTrilinos_ENABLE_ShyLUBasker=ON -DTrilinos_ENABLE_ShyLU_NodeBasker=ON -DTPL_ENABLE_OpenMP=ON -DTrilinos_ENABLE_Kokkos=ON -DTrilinos_ENABLE_ShyLU_DD=ON -DTrilinos_ENABLE_ShyLU_DDBDDC=ON -DTPL_ENABLE_MPI=ON -DTrilinos_ENABLE_OpenMP=ON .. 

## Your Environment

- **Relevant configure flags or configure script:**  the cmake-flags given above
- **Operating system and version:**  Ubuntu 16.10 LTS and Fedora Workstation
- **Compiler and TPL versions:**  gcc version 5 on Ubuntu, version 8 on Fedora

**Comment by lucbv** [comment]
@LennartSchu how are you specifying the path to Scotch in you configuration file for Trilinos?

**Comment by LennartSchu** [comment]
The path is being found (properly) by cmake. It doesn't make a difference when I specify the path. I verified that the "-I/usr/local/include"-flag (the path in which I've installed scotch.h) is passed in the command that leads to the failure. 
The according cmake-output is:
Processing enabled TPL: Scotch (enabled by ShyLU_NodeBasker, disable with -DTPL_ENABLE_Scotch=OFF)
-- Scotch_LIBRARY_NAMES='ptscotch;ptscotcherr;scotch;scotcherr'
-- TPL_Scotch_LIBRARIES='/usr/local/lib/libptscotch.so;/usr/local/lib/libptscotcherr.so;/usr/local/lib/libscotch.so;/usr/local/lib/libscotcherr.so'
-- TPL_Scotch_INCLUDE_DIRS='/usr/local/include'
which gives the proper files in which scotch is installed

However, if you copy scotch.h to scotch2.h and specify that one in shylubasker_order_scotch.hpp instead of scotch.h, the error does not appear anymore and the make-command runs flawlessy. 
It seems that there is an issue with the compiler, which includes the scotch.h, but doesn't find the symbols. It's also possible that I have made an error cmake-ing.

**Comment by ndellingwood** [comment]
@LennartSchu I'm not sure how to triage your specific scotch issues, but I built ShyLU_NodeBasker on my laptop with Ubuntu 16.04 and am providing some instructions for how I built the Scotch tpl from source, then configured and built Trilinos. Hopefully this helps to find a "common denominator" between your setup and mine to help you get past the build issues. 

Here is my computing setup for reference:

Dell laptop Ubuntu 16.04
Compiler: gcc/7.4 (this has worked for me in the past with gcc/5.x, gcc/6.x as well)

## Overview
1. Download and build scotch/6.0.3
2. Configure Trilinos (with ShyLU_NodeBasker enabled of course ;)
3. Build Trilinos

Obviously you've cloned Trilinos and have some system BLAS that was recognized so I won't go into detail about that.

## Scotch

### Downloading scotch
Download scotch/6.0.3 (6.0.3 is the version that Basker officially requires): [scotch download link](https://gforge.inria.fr/frs/?group_id=248&release_id=8831)

### Build scotch/6.0.3
1. Move your scotch download to directory you'd like the install to reside, unzip/uncompress the tarball
(assuming below that the unpacked scotch source code resides in a directory named `scotch-6.0.3`)
2. Copy the Makefile.inc file pasted below to `scotch-6.0.3/src`:

```
EXE   =   
LIB   = .a
OBJ   = .o

MAKE    = make
AR    = ar
ARFLAGS   = -ruv
CAT   = cat 
CCS   = gcc 
CCP   = mpicc
CCD   = gcc 
CFLAGS    = -O3 -DCOMMON_FILE_COMPRESS_GZ -DCOMMON_PTHREAD -DCOMMON_RANDOM_FIXED_SEED -DSCOTCH_RENAME -DSCOTCH_PTHREAD -Drestrict=__restrict -DIDXSIZE64
CLIBFLAGS =
LDFLAGS   = -lz -lm -lrt -pthread
CP    = cp
LEX   = flex -Pscotchyy -olex.yy.c
LN    = ln
MKDIR   = mkdir
MV    = mv
RANLIB    = ranlib
YACC    = bison -pscotchyy -y -b y
```

Note: If you want to build with MPI support, you may need to specify the path to your mpi install's include directory. I had to modify my CFLAGS as following in this case:

`CFLAGS    = -O3 -DCOMMON_FILE_COMPRESS_GZ -DCOMMON_PTHREAD -DCOMMON_RANDOM_FIXED_SEED -DSCOTCH_RENAME -DSCOTCH_PTHREAD -Drestrict=__restrict -DIDXSIZE64 -I<path-to-my-ompi2.1.2>/openmpi-2.1.2/include` the 

3. Build scotch
`cd <path-to-scotch-parent-dir>/scotch-6.0.3/src`
`make -j`

## Trilinos

### Configure Trilinos
Create a build directory and modify a copy of the configuration below script based on your system:

#### configure.sh

```
#!/bin/bash

export TRILINOS_HOME=${HOME}/Research/trilinos/Trilinos

TPL_PATH=${HOME}/TPLs/gcc-7.3.0
SCOTCH_PATH=${TPL_PATH}/scotch_6.0.3
GFORTRAN_LIB=/usr/lib/gcc/x86_64-linux-gnu/7/libgfortran.a

export INSTALL_LOCATION=${PWD}/install

rm -rf CMakeCache.txt CMakeFiles

cmake \
-D CMAKE_INSTALL_PREFIX:PATH="${INSTALL_LOCATION}" \
-D CMAKE_CXX_FLAGS:STRING="-g" \
-D CMAKE_BUILD_TYPE:STRING=RELEASE \
-D BUILD_SHARED_LIBS:BOOL=OFF \
-D Trilinos_EXTRA_LINK_FLAGS:STRING="${GFORTRAN_LIB}" \
\
-D TPL_ENABLE_Scotch:BOOL=ON \
  -D Scotch_INCLUDE_DIRS:PATH="${SCOTCH_PATH}/include" \
  -D Scotch_LIBRARY_DIRS:PATH="${SCOTCH_PATH}/lib" \
  -D Scotch_LIBRARY_NAMES:STRING="scotch;scotcherr" \
-D TPL_ENABLE_BLAS:STRING=ON \
-D TPL_ENABLE_LAPACK:STRING=ON \
\
-D Trilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON \
-D Trilinos_ENABLE_EXAMPLES:BOOL=OFF \
-D Trilinos_ENABLE_TESTS:BOOL=OFF \
-D Trilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=OFF \
\
-D Trilinos_ENABLE_CHECKED_STL:BOOL=OFF \
-D Trilinos_ENABLE_OpenMP:BOOL=ON \
-D Trilinos_ENABLE_Kokkos:BOOL=ON \
  -D Kokkos_ENABLE_OpenMP:BOOL=ON \
  -D Kokkos_ENABLE_TESTS:BOOL=OFF \
  -D Kokkos_ENABLE_EXAMPLES:BOOL=OFF \
-D Trilinos_ENABLE_ShyLU_NodeBasker:BOOL=ON \
${TRILINOS_HOME}
```

If you want to enable the ShyLU_NodeBasker tests as insurance the configure/build behaved as expected, add the following line to the configure above:
`  -D ShyLU_NodeBasker_ENABLE_TESTS:BOOL=ON \`


#### Configure and Build
```
cd <path-to-trilinos>
mkdir Build
cd Build
./configure
```

### Build/Install Trilinos
`make -j`
`make install -j`
