### ISSUE TITLE
Galeri/Triutils: Duplicate symbols in Galeri_iohb.cpp and Trilinos_util_iohb.cpp

### ISSUE THREAD

**Issue by vbrunini** [trilinos/Trilinos#4375]
## Expectations

It should be possible to link against both galeri and triutils without any duplicate symbols. 

## Current Behavior
I observe linker errors about duplicate symbols for functions defined in packages/triutils/src/Trilinos_util_iohb.cpp and packages/galeri/src-epetra/Galeri_iohb.cpp. I noticed this on an nvidia build with relocatable device code on and ETI off, but have not tested which (if any) of those are required to trigger the linker errors. The contents of those two files appear to be essentially identical, only differences I saw were Trilinos_util_iohb.cpp qualifying calls to std:: functions.

**Comment by mhoemmen** [comment]
@trilinos/muelu

**Comment by mhoemmen** [comment]
I'm working on some CUDA build link errors for ETI off in Tpetra: https://github.com/trilinos/Trilinos/issues/4334#issuecomment-462417954  Those might be unrelated, though.

**Comment by jhux2** [comment]
With the exception of AztecOO and Belos, all of the dependencies on Triutils are packages tests and/or examples.

AztecOO lists Triutils as a library dependency, but grep shows that is probably wrong:
```
(develop=) (~/.../packages/aztecoo) grep -rli triutils *
cmake/Dependencies.cmake
example/AztecOO_RecursiveCall/classicMakefile
example/MLAztecOO/classicMakefile
example/aztec_hb/az2azoo.mk
example/IfpackAztecOO/classicMakefile
example/azoo_iterate_hb/classicMakefile
example/Epetra_MsrMatrix_PowerMethod/classicMakefile
example/AztecOO/classicMakefile
example/AztecOO/vbr_main.mk
example/AztecOO/adapt_main.mk
example/IfpackIctAztecOO/classicMakefile
example/Epetra_MsrMatrix_AztecOO/classicMakefile
example/IfpackVbrAztecOO/classicMakefile
```

The free-standing utility functions in BelosEpetraUtils.[h|cpp] depend on TriUtils, but those functions are only used in examples and tests.

**Comment by jhux2** [comment]
Oh, it just gets better:
```
(.../trilinos/Trilinos/packages) find . -name "*iohb*"
./komplex/example/komplex_hb/iohb.h
./komplex/example/komplex_hb/iohb.c
./galeri/src-epetra/Galeri_iohb.cpp
./galeri/src-epetra/Galeri_iohb.h
./triutils/src/Trilinos_Util_iohb.cpp
./triutils/src/Trilinos_Util_iohb.h
./aztecoo/example/azoo_iterate_hb/iohb.h
./aztecoo/example/azoo_iterate_hb/iohb.c
./aztecoo/example/aztec_hb/iohb.h
./aztecoo/example/aztec_hb/iohb.c
./ifpack/example/ifpack_threaded_hb/iohb.h
./ifpack/example/ifpack_threaded_hb/iohb.c

```

**Comment by jhux2** [comment]
Just to add to the pile, Belos also has a dependency on Galeri's iohb code.

**Comment by csiefer2** [comment]
> Just to add to the pile, Belos also has a dependency on Galeri's iohb code.

As Kook-Aid Man would say, "Oh yeah!"

**Comment by jhux2** [comment]
PR submitted.

**Comment by vbrunini** [comment]
Thanks!

**Comment by jhux2** [comment]
@vbrunini The PR has been merged.  Could you please pull and retest?  Thanks.

**Comment by vbrunini** [comment]
Fix works for me, thanks!
