### ISSUE TITLE
Tpetra: Changes to Import broke MMM_Timings

### ISSUE THREAD

**Issue by csiefer2** [trilinos/Trilinos#4381]
Both the changes and the MMM_Timings use "prefix" to mean different data types.

**Comment by mhoemmen** [comment]
@csiefer2 May I remove the MMM timings macros and just introduce timers that always exist?

**Comment by csiefer2** [comment]
@mhoemmen I'd rather not --- Those guys do string manipulation to "nest" timer names.

Counterproposal:  Add a MMM Timings option to Tpetra_Details_Behavior

**Comment by mhoemmen** [comment]
@csiefer2 wrote:
> Counterproposal: Add a MMM Timings option to Tpetra_Details_Behavior

I'm OK with this.  How about `TPETRA_MMM_TIMINGS`?

**Comment by csiefer2** [comment]
@mhoemmen Sounds good to me.

**Comment by cgcgcg** [comment]
Fixed via #4382
