### ISSUE TITLE
KokkosKernels: KokkosKernels_blas_serial_MPI_1 tests are unstable

### ISSUE THREAD

**Issue by william76** [trilinos/Trilinos#4394]
@trilinos/kokkos-kernels 

The `KokkosKernels_blas_serial_MPI_1` test has been having some [intermittent failures the past few days][1]. Can someone on the @trilinos/kokkos-kernels have a look at this and see what's happening?

The [CDash output][2] isn't terribly exciting:
```
Note: Google Test filter = -serial.gemm_double
[==========] Running 89 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 89 tests from serial
[ RUN      ] serial.gemm_complex_double
```

@ndellingwood when you have a chance can you have a look at this? I've been seeing the error on the develop->master pull requests. It popped up after the merge of new kokkos stuff last week, but it seems to be intermittent so we don't have a ton of data points just yet.

[1]: https://testing.sandia.gov/cdash/testSummary.php?project=1&name=KokkosKernels_blas_serial_MPI_1&date=2019-02-13
[2]: https://testing-vm.sandia.gov/cdash/testDetails.php?test=65847315&build=4549908

**Comment by william76** [comment]
FYI @trilinos/framework

**Comment by mhoemmen** [comment]
It probably just takes a long time -- the test machine could be overloaded.

**Comment by william76** [comment]
@mhoemmen I had a look at the jenkins job... there was no timeout set. I added a 10 hour timeout to this one just a bit ago so that there -is- a timeout on it... but the job that failed only ran for about 2.5 hours so it's not doing anything bizarre time-wise. It's also reporting the results so /shrug 

@trilinos/framework
It's a little confusing since both attempts at the [dev->master from yesterday][1] (#4389) failed this specific test. 
Last night's dev->master PR build (#4399) had a lot of errors on the SERIAL build but nothing on the gcc 7.2.0 build :|  ... I haven't looked at the logs on that one though.

I will go look at the nightly [dev->master][2] PR's for the past week and see if I see anything common. That build has generally been pretty stable for quite a while, but this last week hasn't been so great. 
the [build farm is pretty loaded][3] though, but not maxxed I think. I know there was that issue last week with the Intel license server being down, but since they got that back up the Intel builds seem to be ok on licenses.

[1]: https://testing-vm.sandia.gov/cdash/index.php?project=Trilinos&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=63&value1=PR-4389-test&field2=buildstarttime&compare2=84&value2=NOW
[2]: https://github.com/trilinos/Trilinos/pulls?utf8=%E2%9C%93&q=is%3Apr+Master+Merge+PR+
[3]: https://ascic-jenkins.sandia.gov/label/trilinos-any/load-statistics

**Comment by mhoemmen** [comment]
@william76 wrote:
> I had a look at the jenkins job... there was no timeout set.

I was thinking that the test itself has a timeout -- but wouldn't it then report that?

**Comment by william76** [comment]
Yeah, if there's a timeout built-in to the test you'd think it would report that... I'm not sure what's going on with these... the failures are happening on different nodes of the build farm and they're consistently inconsistent (i.e., when it fails for a particular dev->master it seems to keep failing but I don't see that same error on other dev->master PR's...).  The job isn't consistently failing so I think normal PR's are getting through.  ¯\\\_(ツ)\_/¯

**Comment by ndellingwood** [comment]
@william76 what system or test bed should I use to try and reproduce? Like Mark said it may be a timeout issue, if that is the case we can try reducing the sizes when the tests run with the serial backend. Adding @kyungjoo-kim to this thread.

**Comment by ndellingwood** [comment]
@william76 also can you provide some configuration information and how the tests are run (i.e. ctest -j?) for reproducing the issue? This didn't show up during testing so it will help to find out where the configurations differ.

**Comment by william76** [comment]
@ndellingwood These are running on RHEL7 machines I believe, so nothing special... but this error has been inconsistent so far... I didn't see that error on last night's dev->master PR... I'm interested in seeing what the retest on #4399 does.  That's been going for the past 3 hours so hopefully it'll finish around noon or 1pm.

**Comment by william76** [comment]
[Wiki: How to Reproduce PR Testing Builds and Errors.][1]

For this particular build, it looks like [it turned these on][2]:
```
-- Setting Trilinos_ENABLE_ALL_PACKAGES = ON
-- Setting Trilinos_ENABLE_AztecOO = ON
-- Setting Trilinos_ENABLE_Belos = ON
-- Setting Trilinos_ENABLE_Galeri = ON
-- Setting Trilinos_ENABLE_Ifpack2 = ON
-- Setting Trilinos_ENABLE_MueLu = ON
-- Setting Trilinos_ENABLE_Pamgen = ON
-- Setting Trilinos_ENABLE_TpetraCore = ON
-- Setting Trilinos_ENABLE_Triutils = ON
-- Setting Trilinos_ENABLE_Zoltan2 = ON
```

[1]:https://github.com/trilinos/Trilinos/wiki/Reproducing-PR-Testing-Errors
[2]: https://testing-vm.sandia.gov/cdash/viewConfigure.php?buildid=4558510

**Comment by william76** [comment]
This test looks like it's failing by hitting the 10-minute wall for individual tests.  What's confusing is that if you look at the [table of all the runs of this test][1] this test varies from 8 seconds to timing out at 600 seconds on PR's and 900 seconds on some GCC 7.3.0 and 4.9.3 tests. I think the occasions where it passes are when we get lucky and it squeaks in under the 10-minute time limit... but at least 50% or more of the time in the last week it's hitting that wall and failing.

In our @trilinos/framework meeting today we had a conversation about increasing the timeout, but to do this the knob we have would be to increase the timelimit for -all- tests and we're reluctant to do this. We'd prefer that _individual_ tests should not take over 10 minutes unless it's indicating a problem.

Is it possible for KokkosKernels to split the `KokkosKernels_blas_serial_MPI_1` test up so that it won't take so long?

@ndellingwood if you think this can't be fixed by COB Thursday, we'll need to disable it from PR testing until its fixed.

@jwillenbring let me know if I missed anything from our conversation this morning.

@trilinos/kokkos-kernels 

[1]: https://testing-vm.sandia.gov/cdash/testSummary.php?project=1&name=KokkosKernels_blas_serial_MPI_1&date=2019-02-19

**Comment by srajama1** [comment]
@william76 : Why Thursday ? Can you use your Kokkos Kernels time to break the tests  :)

**Comment by ndellingwood** [comment]
@william76 this sounds like another issue with running tests with `ctest -j`; based on the variance in testing times (8 sec up to 900 sec) simply reducing the size of the test for the serial case is not likely to make a difference on the upper limit case which would have been the fast solution. I'm spread too thin this week to try out splitting the test apart so I'm in favor of temporarily disabling for now, adding @srajama1 and @kyungjoo-kim for their opinion. Is there a label like the ATDM labeling that can indicate this is a disabled test that cannot be forgotten about?

**Comment by srajama1** [comment]
I would rather *not* disable this test. If we can't confirm our blas tests are running we cannot have confidence in other packages above.

**Comment by kyungjoo-kim** [comment]
@william76 The failing test is mostly due to the gemm test. Because of the timeout issue, we already disabled gemm_double but we do not disable gemm_dcomplex at that time. Anyway, the gemm test @crtrott originally wrote tests very large problem sizes. My recommendation is to delete the largest test in the gemm test problems and re-enable all gemm tests. Unit test is for correctness and we don't really need to test such a large problem size for all cases. Currently the largest test problem is 1024,1024,2048 case. 
```
  Test::impl_test_gemm<view_type_a_ll, view_type_b_ll, view_type_c_ll, Device>(&mode[0],&mode[1],1024,1024,2048,alpha,beta); 
``` 
If you all are fine, I can submit a PR for this and re-enable all gemm tests.

**Comment by william76** [comment]
@srajama1 In the framework meeting it was discussed that if this isn't stable in a couple of days that we should disable it since the price of an intermittent test failing on pull requests by hitting the 10-minute timeout is pretty high. Rather than increasing the global timeout for all jobs, we'd prefer that individual tests don't run for long periods of time.

I'm mostly out of kokkos kernels time, but this can work for framework time I think... I'll check in with @ndellingwood about a plan of attack and how I can help.

**Comment by srajama1** [comment]
@kyungjoo-kim : please do. Thanks !

**Comment by william76** [comment]
@kyungjoo-kim Thanks!

**Comment by kyungjoo-kim** [comment]
@william76  One question. Do you set the OMP_NUM_THREADS when PR test runs ctest ? If it is not set, it will oversubscribe the entire compute node and this will increase test runtime a lot.

**Comment by william76** [comment]
@kyungjoo-kim 
Hmmm, looks like that's actually set for the GCC 4.8.4 configuration but not set for any others.  I think on the normal Trilinos builds, the jobs take 29 'executors' but use 18 or so cores due to memory constraints on the machines.  

The one that sets it uses `OMP_NUM_THREADS=2` ... is that a reasonable size? Are there any constraints on how big this should be? I suppose we could set it up to the number of executors on the system provided there's enough memory.  Most of the MPI tests that Trilinos runs tend to use 2 or 4 processes so I can get it set and use 4 for now... 

@jwillenbring any thoughts on a reasonable `OMP_NUM_THREADS` size? This would affect more than just the Kokkos-Kernels jobs -- do you know if we have any tests that run openmp on top of mpi?

**Comment by kyungjoo-kim** [comment]
@william76 If the compute resource allows, I would like to go up to 4. Two threads may not detect some edge cases. If we really want to test functionality itself, we may also want to use an odd number 3. As the objective of the PR test is to protect Trilinos, it is also good to vary the omp threads for different test beds. Just thought...

**Comment by william76** [comment]
@kyungjoo-kim 
I'll put in a PR to set `OMP_NUM_THREADS=2` for all the configurations and get it started in PR testing since the one test that was setting it was using 2.  

@jwillenbring has a meeting soon with some Kitware folks, so he'll check with them to see if CTest is OpenMP aware and he'll get back to me in a bit. If it sounds like 4 is good and won't oversubscribe the machines too much I'll push in an update to set them to 4.

**Comment by william76** [comment]
I kicked off a dev->master run after these two PR's went through.  The GCC 7.2 test passed.  I'll check the nightly dev->master tomorrow to see if it passes cleanly too and close this issue out if everything looks good :D
