### ISSUE TITLE
MueLu: Epetra examples won't build unless Tpetra_INST_SERIAL=ON

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#44]
@trilinos/muelu 

When I enable TpetraCore and all forward dependencies (including secondary stable packages), and turn on OpenMP, the build fails in MueLu with link errors, due to "missing" Tpetra Serial instantiations.

**Comment by mhoemmen** [comment]
Example:
[ 66%] Linking CXX executable MueLu_Challenge_XML.exe
CMakeFiles/MueLu_Challenge_XML.dir/Challenge.cpp.o: In function `main':
/scratch/prj/Trilinos/Trilinos/packages/muelu/doc/Tutorial/src/Challenge.cpp:214: undefined reference to `MueLu::ParameterListInterpreter<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::ParameterListInterpreter(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Teuchos::Comm<int> const&, Teuchos::RCP<MueLu::FactoryFactory<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > >)'
/scratch/prj/Trilinos/Trilinos/packages/muelu/doc/Tutorial/src/Challenge.cpp:216: undefined reference to `MueLu::Hierarchy<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::GetLevel(int)'
/scratch/prj/Trilinos/Trilinos/packages/muelu/doc/Tutorial/src/Challenge.cpp:222: undefined reference to `MueLu::ParameterListInterpreter<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::SetupHierarchy(MueLu::Hierarchy<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >&) const'
/scratch/prj/Trilinos/Trilinos/packages/muelu/doc/Tutorial/src/Challenge.cpp:227: undefined reference to `MueLu::Hierarchy<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::IsPreconditioner(bool)'
CMakeFiles/MueLu_Challenge_XML.dir/Challenge.cpp.o: In function `Xpetra::TpetraMultiVector<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::TpetraMultiVector(Teuchos::RCP<Xpetra::Map<int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > const> const&, unsigned long, bool)':
/scratch/prj/Trilinos/Trilinos/packages/xpetra/src/MultiVector/Xpetra_TpetraMultiVector.hpp:104: undefined reference to `Tpetra::MultiVector<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace>, false>::MultiVector(Teuchos::RCP<Tpetra::Map<int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > const> const&, unsigned long, bool)'

**Comment by mhoemmen** [comment]
I am checking now to see whether setting MueLu_ENABLE_Epetra=OFF works around the issue.  If so, I can add a check to muelu/CMakeLists.txt so that the configure process doesn't allow both MueLu_ENABLE_Epetra=ON and Tpetra_INST_SERIAL=OFF.

**Comment by etphipp** [comment]
It works.  I am now doing that in my builds to avoid having to instantiate Tpetra on the serial node.

Note that it doesn't appear to work to set Xpetra_ENABLE_Epetra=OFF due to some include problems.

-Eric

**Comment by mhoemmen** [comment]
Hm, it doesn't work for me.  Did you just set that one CMake variable?

**Comment by mhoemmen** [comment]
More importantly: Did you have to shut off tests and examples?

**Comment by aprokop** [comment]
We are aware of some problems with this case right now. Dashboard also shows other failures.
@mhoemmen You can use the Epetra=OFF workaround, but you should not add it to muelu/CMakeLists.txt. The reason is that it should still compile using Xpetra's dummy objects.

**Comment by jhux2** [comment]
Mark Hoemmen wrote on 12/03/2015 04:18 PM:
>
> Hm, it doesn't work for me. Did you just set that one CMake variable?
>
Mark, would you post your configure script or email it to me?

Jonathan

**Comment by mhoemmen** [comment]
-D Trilinos_ENABLE_Fortran:BOOL=OFF
-D Trilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON
-D TPL_ENABLE_Boost:BOOL=OFF
-D TPL_ENABLE_BoostLib:BOOL=OFF
-D TPL_ENABLE_SWIG:BOOL=OFF
-D CMAKE_CXX_FLAGS:STRING=\"-Wall --pedantic\"
-D MueLu_ENABLE_Epetra:BOOL=OFF
-D BUILD_SHARED_LIBS:BOOL=ON
-D CMAKE_BUILD_TYPE:STRING=DEBUG
-D Teuchos_ENABLE_DEBUG:BOOL=ON
-D TPL_ENABLE_MPI:BOOL=ON
-D Teuchos_ENABLE_COMPLEX:BOOL=ON
-D Tpetra_INST_COMPLEX_DOUBLE:BOOL=ON
-D Trilinos_ENABLE_OpenMP:BOOL=ON
-D Trilinos_SHOW_DEPRECATED_WARNINGS:BOOL=OFF

**Comment by mhoemmen** [comment]
I am using GCC 5.1.0 with OpenMPI 1.8.7.

**Comment by etphipp** [comment]
I have not tried it with MueLu examples/tests enabled.  I have tried it with Stokhos test/examples enabled that use MeuLu/Tpetra though.

-Eric

**Comment by mhoemmen** [comment]
btw if I use that configuration, and additionally set Tpetra_INST_SERIAL=ON, I get a build error in MueLu:

In file included from /scratch/prj/Trilinos/Trilinos/packages/teuchos/core/src/Teuchos_ArrayRCPDecl.hpp:47:0,
                 from /scratch/prj/Trilinos/Trilinos/packages/teuchos/core/src/Teuchos_ArrayRCP.hpp:46,
                 from /scratch/prj/Trilinos/Trilinos/packages/teuchos/core/src/Teuchos_ArrayView.hpp:47,
                 from /scratch/prj/Trilinos/Trilinos/packages/teuchos/core/src/Teuchos_GlobalMPISession.hpp:52,
                 from /scratch/prj/Trilinos/Trilinos/packages/teuchos/core/src/Teuchos_StandardCatchMacros.hpp:45,
                 from /scratch/prj/Trilinos/Trilinos/packages/muelu/example/advanced/levelwrap/LevelWrap.cpp:50:
/scratch/prj/Trilinos/Trilinos/packages/teuchos/core/src/Teuchos_RCP.hpp: In instantiation of ‘Teuchos::RCP<T>::RCP(const Teuchos::RCP<T2>&) [with T2 = Xpetra::Matrix<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial> >; T = Xpetra::Matrix<>]’:
/scratch/prj/Trilinos/Trilinos/packages/muelu/example/advanced/levelwrap/LevelWrap.cpp:207:83:   required from ‘void MueLuExamples::solve_system_list(Xpetra::UnderlyingLib&, Teuchos::RCP<Xpetra::Matrix<Scalar, LocalOrdinal, GlobalOrdinal, Node> >&, Teuchos::RCP<Xpetra::Vector<Scalar, LocalOrdinal, GlobalOrdinal, Node> >&, Teuchos::RCP<Xpetra::Vector<Scalar, LocalOrdinal, GlobalOrdinal, Node> >&, Teuchos::ParameterList&, Teuchos::RCP<Teuchos::ParameterList>&) [with Scalar = double; LocalOrdinal = int; GlobalOrdinal = int; Node = Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial>]’
/scratch/prj/Trilinos/Trilinos/packages/muelu/example/advanced/levelwrap/LevelWrap.cpp:503:65:   required from here
/scratch/prj/Trilinos/Trilinos/packages/teuchos/core/src/Teuchos_RCP.hpp:289:38: error: cannot convert ‘Xpetra::Matrix<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial> >*’ to ‘Xpetra::Matrix<>*’ in initialization
     node_(r_ptr.access_private_node())
                                      ^
/scratch/prj/Trilinos/Trilinos/packages/teuchos/core/src/Teuchos_RCP.hpp: In instantiation of ‘Teuchos::RCP<T>::RCP(const Teuchos::RCP<T2>&) [with T2 = Tpetra::CrsMatrix<>; T = Tpetra::CrsMatrix<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial>, false>]’:
/scratch/prj/Trilinos/Trilinos/packages/muelu/example/advanced/levelwrap/LevelWrap.cpp:207:85:   required from ‘void MueLuExamples::solve_system_list(Xpetra::UnderlyingLib&, Teuchos::RCP<Xpetra::Matrix<Scalar, LocalOrdinal, GlobalOrdinal, Node> >&, Teuchos::RCP<Xpetra::Vector<Scalar, LocalOrdinal, GlobalOrdinal, Node> >&, Teuchos::RCP<Xpetra::Vector<Scalar, LocalOrdinal, GlobalOrdinal, Node> >&, Teuchos::ParameterList&, Teuchos::RCP<Teuchos::ParameterList>&) [with Scalar = double; LocalOrdinal = int; GlobalOrdinal = int; Node = Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial>]’
/scratch/prj/Trilinos/Trilinos/packages/muelu/example/advanced/levelwrap/LevelWrap.cpp:503:65:   required from here
/scratch/prj/Trilinos/Trilinos/packages/teuchos/core/src/Teuchos_RCP.hpp:289:38: error: cannot convert ‘Tpetra::CrsMatrix<>*’ to ‘Tpetra::CrsMatrix<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial>, false>*’ in initialization

**Comment by mhoemmen** [comment]
Looks like some parts of MueLu assume the default Node type?

**Comment by jhux2** [comment]
Mark Hoemmen wrote on 12/03/2015 05:06 PM:
>
> Looks like some parts of MueLu assume the default Node type?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/trilinos/Trilinos/issues/44#issuecomment-161842094>.
>
Is your Trilinos up-to-date?  I pushed a commit today that should have 
fixed this.

**Comment by mhoemmen** [comment]
Up, it's up to date, just pulled now and retried.

**Comment by jhux2** [comment]
Mark Hoemmen wrote on 12/03/2015 05:15 PM:
>
> Up, it's up to date, just pulled now and retried.
>
Just fixed this with commit 4ece2a82.

**Comment by aprokop** [comment]
> Looks like some parts of MueLu assume the default Node type?

Yes, this is one of the issues. The tests must be refactored to be able to run with other node types depending on configuration. We've done some work on unit tests and couple other tests, but this is still very in progress.

**Comment by mhoemmen** [comment]
I'm able to build MueLu tests and examples now.  I haven't tried yet with Tpetra_INST_SERIAL=OFF; that's the next step.  Thanks Jonathan and Andrey! :-)

**Comment by mhoemmen** [comment]
btw there are a couple tests that fail with MueLu_ENABLE_Epetra=OFF, Tpetra_INST_SERIAL=ON, and Trilinos_ENABLE_OpenMP=ON.  For example:

$ ctest -V -R MueLu_Driver_TogglePFactory_semi_sa_line_easy_Tpetra_MPI_4

26: Test command: .../mpiexec "-np" "4" ".../muelu/test/toggletransfer/MueLu_TogglePFactory_driver.exe" "--matrixType=Laplace3D" "--nx=40" "--ny=40" "--nz=60" "--mz=1" "--xmlFile=parameters_semi_sa_easy.xml" "--linAlgebra=Epetra"
26: Test timeout computed to be: 9.99988e+06
26: Xpetra::Parameters
26:  Linear algebra library: Epetra
26: Galeri::Xpetra::Parameters<int>
26:  Matrix type: Laplace3D
26:  Problem size: 96000 (40x40x60)
26:
26: p=0: *** Caught standard std::exception of type 'Xpetra::Exceptions::RuntimeError' :
26:
26:  /scratch/prj/Trilinos/Trilinos/packages/xpetra/src/Map/Xpetra_EpetraMap.hpp:108:
26:
26:  Throw number = 2
26:
26:  Throw test that evaluated to true: true
26:
26:  Xpetra::EpetraMap only available for GO=int or GO=long long with Node=Kokkos::Compat::KokkosSerialWrapperNode.

**Comment by aprokop** [comment]
I'm pushing a commit that temporarily disables all MueLu and Xpetra tests. We are redoing the Xpetra ETI once again (hopefully, for the last time), and will reenable tests one by one. The tests will still be available on the Dashboard, but you have to explicitly ask for them.

**Comment by mhoemmen** [comment]
If I set Tpetra_INST_SERIAL=OFF, I still get build errors:

[ 69%] Linking CXX executable MueLu_Driver.exe
CMakeFiles/MueLu_Driver.dir/Driver.cpp.o: In function `Xpetra::TpetraMultiVector<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::TpetraMultiVector(Teuchos::RCP<Xpetra::Map<int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > const> const&, unsigned long, bool)':
.../Trilinos/packages/xpetra/src/MultiVector/Xpetra_TpetraMultiVector.hpp:104: undefined reference to `Tpetra::MultiVector<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace>, false>::MultiVector(Teuchos::RCP<Tpetra::Map<int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > const> const&, unsigned long, bool)'
CMakeFiles/MueLu_Driver.dir/Driver.cpp.o: In function `Xpetra::TpetraMultiVector<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::TpetraMultiVector(Teuchos::RCP<Xpetra::Map<int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > const> const&, unsigned long, bool)':

// ... many, many more ...

**Comment by mhoemmen** [comment]
Could you for now just disable the tests if Serial is not enabled (Tpetra_INST_SERIAL=OFF)? would at least like to test for Serial :-) Thanks!

**Comment by aprokop** [comment]
We've re-enabled some unit tests for all node types before Christmas. All other tests stay disabled until fixed.

**Comment by tawiesn** [comment]
Still on-going work. Please be patient.

**Comment by mhoemmen** [comment]
Don't worry Tobias!  Super happy you're working on this! :-D

**Comment by tawiesn** [comment]
Looking at the dashboard we can safely close the issue.

**Comment by jhux2** [comment]
tawiesn wrote on 05/18/2016 08:16 AM:
> Looking at the dashboard we can safely close the issue.
Nice job, Tobias, Andrey, and Mark!

**Comment by mhoemmen** [comment]
YAY! :-D
