### ISSUE TITLE
Switch to C bindings of BLAS & LAPACK?

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#4404]
@trilinos/framework 

@mwglass pointed out that:

  - Trilinos, kokkos-kernels, Sierra, ATDM, etc. all spent a lot of effort deducing and maintaining Fortran mangling of BLAS and LAPACK, yet
  - the BLAS (and even LAPACK)[
http://netlib.org/lapack/#_standard_c_language_apis_for_lapack] come with standard C bindings.

Why don't we all switch to the C bindings?  That would get rid of all that mangling deduction code.

**Comment by Rombur** [comment]
Just a heads up if you decide to use `lapacke`, depending on the version you are using you may have trouble compiling `lapacke` and `boost` at the same time see [here](https://github.com/xianyi/OpenBLAS/issues/1992)

**Comment by mhoemmen** [comment]
@Rombur Thanks for the heads-up!
