### ISSUE TITLE
Address failing STK CI tests

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#441]
**Next Action Status:**

STK team has created ticket in their system; STKClassic_stk_io_unit_tests_MPI_1 is fixed but STKUnit_tests_util_parallel_UnitTest_MPI_4 is still failing.

**Blocking:** #370

**CC:** @trilinos/stk, @trilinos/framework 

**Description:**

The tests `STKUnit_tests_util_parallel_UnitTest_MPI_4` and `STKClassic_stk_io_unit_tests_MPI_1` have been failing in Trilinos CI testing for a long time as shown by [this query](http://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&date=&limit=200&filtercount=3&showfilters=1&limit=200&filtercombine=and&field1=testname/string&compare1=61&value1=STKUnit_tests_util_parallel_UnitTest_MPI_4&field2=buildname/string&compare2=63&value2=CONTINUOUS&field3=buildstarttime/date&compare3=83&value3=52%20weeks%20ago) (for all stored history which currently only goes back to 2016-04-16) and [this query](http://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&date=&limit=200&filtercount=3&showfilters=1&limit=200&filtercombine=and&field1=testname/string&compare1=61&value1=STKClassic_stk_io_unit_tests_MPI_1&field2=buildname/string&compare2=63&value2=CONTINUOUS&field3=buildstarttime/date&compare3=83&value3=52%20weeks%20ago) (since 2016-05-18), respectively.

This is blocking the usage of the Trilinos CI build to be used in the criteria to update from the 'develop' branch to the 'master' branch (see #370).

**Tasks:**

1. Disable remaining failing test `STKUnit_tests_util_parallel_UnitTest_MPI_4` (see [below](https://github.com/trilinos/Trilinos/issues/441#issuecomment-228499760)) [Done]
2. Fix the failing test `STKUnit_tests_util_parallel_UnitTest_MPI_4` and then re-enable it ...

**Comment by bartlettroscoe** [comment]
If there is no objection from @trilinos/stk people, I will disable these tests in the CI build of Trilinos and then someone can fix these failing tests when they get a chance and then re-enable them (and close this ticket).  I appears that these tests are only run in this one Trilinos CI build as shown by [this query]() and [this query]().  Therefore, so I will just disable these tests in all Trilinos configures but setting:

````
SET(<full_test_name>_DISABLE TRUE ...)
```

in the file Trilinos/ProjectName.cmake.

**Comment by bartlettroscoe** [comment]
The word "perpetual" is not fair since `STKClassic_stk_io_unit_tests_MPI_1` has only been failing since 5/18, not for all of recording CDash history.

**Comment by gsjaardema** [comment]
I can fix the STK io test.

**Comment by gsjaardema** [comment]
`STKClassic_stk_io_unit_tests_MPI_1` test should now be working.

**Comment by bartlettroscoe** [comment]
It looks like Greg fixed the test STKClassic_stk_io_unit_tests_MPI_1 but the test STKUnit_tests_util_parallel_UnitTest_MPI_4 is still failing as shown most recently here:

​http://testing.sandia.gov/cdash/viewTest.php?buildid=2476807

If this test can't be fixed soon, we will disable it under Trilinos and then this Issue ticket will be a place holder for getting it fixed.  If I do need to disable it, I will provide instructions on how to enable it again.

**Comment by bartlettroscoe** [comment]
Also, the STK team has created a ticket in their native issue tracker for STK with the ID 15120 so their team is aware of the issue.

**Comment by bartlettroscoe** [comment]
The remaining filing test is now disabled by default in the commit 86eb6e9 just pushed.  This can be reproduced on any machine that has the SEMS Dev Env by doing something like:

```
$ cd Trilinos/
$ mkdir BUILD/
$ cd BUILD/
$ source ../cmake/load_ci_sems_dev_env.sh
$ cmake \
  -DCMAKE_BUILD_TYPE=RELEASE \
  -DBUILD_SHARED_LIBS=ON \
  -DTrilinos_ENABLE_DEBUG=ON \
  -DTrilinos_ENABLE_TESTS=ON \
  -DTrilinos_TRACE_ADD_TEST=ON \
  -DTPL_ENABLE_MPI=ON \
  -DTrilinos_ENABLE_STK=ON \
  ..
```

After you get the test working, you can revert the commit with:

```
$ git revert 86eb6e9
```

and then test and push with:

```
$ cd Trilinos/BUILD/
$ ../cmake/std/sems/checkin-test-sems.sh --enable-all-packages=off \
  --enable-packages=STK --no-enable-fwd-packages \
  --do-all --push
```

Let me know if you have any questions about this.

@bmpersc, note that I disabled this test without touching the packages/stk/ source tree at all so this should not mess up your syncs with for STK at all.

**Comment by bartlettroscoe** [comment]
I added `-DNDEBUG` to the release flags for GCC and the test `STKUnit_tests_util_parallel_UnitTest_MPI_4` passed.  I pushed the revert commit  82120c2 so now the test will be enabled again in pre-push testing:

```
654/2361 Test #1524: STKUnit_tests_util_parallel_UnitTest_MPI_4 .................................................   Passed    1.97 sec
```

Now I will just wait for confirmation that this is passing in the post-push CI build and then we can close this Issue ticket.

**Comment by bartlettroscoe** [comment]
The test `STKUnit_tests_util_parallel_UnitTest_MPI_4` is showing up passing along with all other STK tests in the CI build yesterday shown here:

* http://testing.sandia.gov/cdash/viewTest.php?onlypassed&buildid=2508012

I am closing this as fixed.
