### ISSUE TITLE
Tpetra::MultiVector: REPLACE / INSERT CombineMode need not use atomic updates

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#4417]
@trilinos/tpetra @crtrott @vbrunini @jjellio 

See discussion here: https://github.com/trilinos/Trilinos/issues/962#issuecomment-464524708

@vbrunini , @crtrott , and I found out Friday that MultiVector Import goes faster on multiple GPUs when we remove use of atomic updates (`Kokkos::atomic_assign`) with the REPLACE CombineMode.  (INSERT and REPLACE do the same thing with MultiVector.)  MultiVector uses atomics to implement "sparse all-reduce," but using them with the REPLACE CombineMode isn't a well-defined reduction, even ignoring rounding error. Thus, it makes sense to get rid of them, for MultiVector's REPLACE implementation at least.

## Related Issues
* Related to #962

**Comment by mhoemmen** [comment]
@csiefert reports that this might break Panzer, since they used to have inconsistent Dirichlet conditions and they relied on an implementation detail of how Tpetra ordered Import updates.  @trilinos/panzer, is this still a thing?

**Comment by rppawlo** [comment]
This is the first time I've heard of this. Maybe @eric-c-cyr knows more about it?

**Comment by eric-c-cyr** [comment]
I've not heard of this. I don't understand the implementation well enough to take advantage of it. @csiefer2 or @mhoemmen what were you think specifically?

**Comment by mhoemmen** [comment]
@eric-c-cyr The idea is that since Tpetra does not promise to execute combines in any particular order, it would be silly for users to expect a REPLACE on Import to use atomic updates.

MultiVector currently uses `Kokkos::atomic_assign` for REPLACE.  This guarantees that if multiple processes send my process data for the same row of my vector, then my value in that row will equal one (some random one) of the incoming data.  (Fun fact: for MultiVectors, we atomically update by entry; this means that different columns in the same row could get different values from different processes.)

If we take out `atomic_assign` and just use regular assignment (`operator=`), then the above situation would turn into a race condition.  Collisions by multiple threads writing to the same value nonatomically could corrupt the value.

**Comment by mhoemmen** [comment]
I've marked this as "results impacting", since it could affect code that tries to resolve conflicts across processes in a MultiVector Export / Import by assuming that REPLACE / INSERT does atomic updates.  That might arise when applying PDE boundary conditions, for example.
