### ISSUE TITLE
Address failing ROL CI tests 

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#442]
**Next Action Status:** 

Tests disabled.  Next: ROL developers fix so they can be run ...

**Blocking:** #370 

**Related To:** #462 

**CC:** @trilinos/rol, @trilinos/framework 

**Description:**

The tests `ROL_test_sol_solTeuchosBatchManager_MPI_4` and `ROL_example_PDE-OPT_elasticitySIMP_topologyOptimization_example_01_MPI_1` have been failing for a long time as shown by [this query](http://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&date=&limit=200&filtercount=3&showfilters=1&limit=200&filtercombine=and&field1=testname/string&compare1=61&value1=ROL_test_sol_solTeuchosBatchManager_MPI_4&field2=buildname/string&compare2=63&value2=CONTINUOUS&field3=buildstarttime/date&compare3=83&value3=52%20weeks%20ago) (since 2016-05-27) and [this query](http://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&date=&limit=200&filtercount=3&showfilters=1&limit=200&filtercombine=and&field1=testname/string&compare1=61&value1=ROL_example_PDE-OPT_elasticitySIMP_topologyOptimization_example_01_MPI_1&field2=buildname/string&compare2=63&value2=CONTINUOUS&field3=buildstarttime/date&compare3=83&value3=52%20weeks%20ago) (since 2016-04-29), respectively.

This is an impediment to including ROL in the testing criteria for the update of the 'develop' to the 'master' branches of Trilinos (see #370).

**Tasks:**
1. Stop these tests from failing in pre-push and post-push CI testing (see [below](https://github.com/trilinos/Trilinos/issues/442#issuecomment-228499369)) [Done]
2. Have ROL developers fix the failing tests and address the timing-out test(s) (also see #462) ...

**Comment by bartlettroscoe** [comment]
@dridzal already said that we could disable these tests as documented in [this comment](https://github.com/trilinos/Trilinos/issues/370#issuecomment-225065503).

The tests `ROL_test_sol_solTeuchosBatchManager_MPI_4` and `ROL_example_PDE-OPT_elasticitySIMP_topologyOptimization_example_01_MPI_1` appears to only be running in the CI build as shown in [this query](http://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&date=2016-06-13&limit=200&filtercount=1&showfilters=1&limit=200&field1=testname/string&compare1=61&value1=ROL_test_sol_solTeuchosBatchManager_MPI_4) and [this query](http://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&date=2016-06-13&limit=200&filtercount=1&showfilters=1&limit=200&field1=testname/string&compare1=61&value1=ROL_example_PDE-OPT_elasticitySIMP_topologyOptimization_example_01_MPI_1), respectively.  Therefore, we should just disable these tests for all configures of Trilinos for now by setting:

````
SET(<full_test_name>_DISABLE ON ...)
````

in the file Trilinos/ProjectName.cmake.

**Comment by dridzal** [comment]
Ross,


Just to make sure that we've coordinated -- will you do this, or should we do it?  Please choose and let us know.


Thanks,


Denis


________________________________

**Comment by bartlettroscoe** [comment]
> Just to make sure that we've coordinated -- will you do this, or should we do it? Please choose and let us know.

Denis, I will do the disable, test that it is working correctly and push to 'develop'.  Then I will update this Issue ticket with the instructions for how you can re-enable these tests and get them working.

**Comment by dridzal** [comment]
?Sounds good, thanks.


________________________________

**Comment by bartlettroscoe** [comment]
The failing CI test `ROL_example_PDE-OPT_elasticitySIMP_topologyOptimization_example_01_MPI_1` is actually a timeout at 10 minutes (i.e. 600s) as shown here:

http://testing.sandia.gov/cdash/viewTest.php?onlyfailed&buildid=2485203

I just built ROL using the new SEMS Dev Env (see #158) and I was able to reproduce the failing test `ROL_test_sol_solTeuchosBatchManager_MPI_4`.  However, I did not set a timeout and the test `ROL_example_PDE-OPT_elasticitySIMP_topologyOptimization_example_01_MPI_1` took 1119 sec (i.e. 18 minutes) to complete, but it did pass.  That is **way** too much time for a CI test.  Therefore, I propose to relegate this test to nightly testing (i.e. by setting the category to `NIGHTLY`).  However, it appears that ROL has no testing!  Check it out:

http://testing.sandia.gov/cdash/index.php?project=Trilinos&date=2016-06-22&subproject=ROL

There are 0 Nightly ROL tests running on any platform!  How does that happen?

@dridzal, you will need to talk with @bmpersc and @jwillenbring about getting ROL under some nighty testing (on at least one Nightly build I would hope).

Therefore, the way that I will address this problem will be:

1.  `ROL_test_sol_solTeuchosBatchManager_MPI_4`: Disable in CI testing (but I suspect this test will fail in all builds of ROL).
2.  `ROL_example_PDE-OPT_elasticitySIMP_topologyOptimization_example_01_MPI_1`: Relegate to `NIGHTLY` (but that will effectively remove ROL from all automated testing).

Given that the ROL developers seem to be okay with the current situation of these two fails failing in all automated testing, the above actions will not damage ROL testing at all.

I will update this Issue when I have pushed the commit to make these changes and I will provide instructions on how to revert the commit and then how to reproduce the failures (using the SEMS Dev Env).

**Comment by bmpersc** [comment]
Ross, if you look at the continuous section of the cdash link you provided you would see that ROL is in fact being tested there. In addition since our current cdash has been acting up some of our testing has been reporting to my cdash instead which has several more builds for ROL.

http://my.cdash.org/index.php?project=Trilinos&subproject=ROL

**Comment by bartlettroscoe** [comment]
Responding to @bmpersc from [above comment](https://github.com/trilinos/Trilinos/issues/442#issuecomment-228207994):

> Ross, if you look at the continuous section of the cdash link you provided you would see that ROL is in fact being tested there.

Right.  I did not mean to suggest that it was not (since this Issue is about failing ROL CI tests showing up on CDash).  What I meant to stress what that once we make the test `ROL_example_PDE-OPT_elasticitySIMP_topologyOptimization_example_01_MPI_1` a `NIGHTLY` test, then it will not longer get run in CI testing.

> In addition since our current cdash has been acting up some of our testing has been reporting to my cdash instead which has several more builds for ROL.
>
> http://my.cdash.org/index.php?project=Trilinos&subproject=ROL

Ah, I did not know that.  I added a link to this my.cdash.org site on the [testing wiki page](https://github.com/trilinos/Trilinos/wiki/Policies--%7C-Testing#overview) so that people can find this too.  Is this my.cdash.org project set up to send out CDash error emails?

I would like to point out that these ROL tests are also failing on a few Nightly builds showing up on the my.cdash.org project:

http://my.cdash.org/queryTests.php?project=Trilinos&date=2016-06-22&limit=200&subproject=ROL&filtercount=2&showfilters=1&limit=200&filtercombine=and&field1=testname/string&compare1=65&value1=ROL_&field2=status/string&compare2=62&value2=Passed

@dridzal, are the ROL developers getting CDash error emails for these failures?

Unfortunately, as shown at the above CDash link, the only time the test `ROL_example_PDE-OPT_elasticitySIMP_topologyOptimization_example_01_MPI_1` is run in Nightly testing, it is also timing out at 10 minutes as shown here:

http://my.cdash.org/testSummary.php?project=896&name=ROL_example_PDE-OPT_elasticitySIMP_topologyOptimization_example_01_MPI_1&date=2016-06-22

I don't think Trilinos should have any single tests that take longer than 10 minutes.

@dridzal, is there something that ROL developers can do to make this test run faster and finish in less than 10 minutes?  Otherwise, we should likely mark it as a `HEAVY` test which means that only ROL developers would be running this (when then configured with `-DTrilinos_TEST_CATEGORIES=HEAVY`).  Given that this test is timing out everywhere it is run, I think the right thing to do is to mark it `HEAVY` for now until ROL developers can get this to run faster.  Otherwise, Trilinos needs to set up a single `HEAVY` build to handle these really long running tests (like CASL VERA does for its heavy simulation tests).

**Comment by bartlettroscoe** [comment]
It seems that the test `ROL_test_sol_solTeuchosBatchManager_MPI_4` is failing in all automated builds of ROL as shown here:

http://my.cdash.org/testSummary.php?project=896&name=ROL_test_sol_solTeuchosBatchManager_MPI_4&date=2016-06-22

Therefore, I will disable this test for all builds of ROL.

**Comment by dridzal** [comment]
Ross,


Just to clarify:  These are important tests that we've been struggling with for some time now.  On some platforms they run just fine, on others they fail or time out.  Ideally, we would like to fix all of them and make them run in a minute or so, not >10 minutes.


We are perfectly happy with "demoting" these tests so that we are not in the way of develop/master/CI/PT practices and status.?  However, we don't quite know all options that are available for marking the tests appropriately.  Is the testing wiki page the ultimate resource for this?


Denis



________________________________

**Comment by bartlettroscoe** [comment]
Responding to @dridzal from [above comment](https://github.com/trilinos/Trilinos/issues/442#issuecomment-228474601):

> Just to clarify: These are important tests that we've been struggling with for some time now. On some platforms they run just fine, on others they fail or time out. Ideally, we would like to fix all of them and make them run in a minute or so, not >10 minutes.

Understood.  You may need to be careful about what tests run in debug mode vs. optimized mode perhaps?  I see there is some logic in ROL that tries to deal with this but I think it may need some tweaking.

> We are perfectly happy with "demoting" these tests so that we are not in the way of develop/master/CI/PT practices and status.? However, we don't quite know all options that are available for marking the tests appropriately. Is the testing wiki page the ultimate resource for this?

We will clarify all of this soon as a Trilinos development team.  The issue was that, up until now, there was not a viable way to have a consistent effective pre-push CI build for Trilinos.  But now that we have a standard SEMS Dev Env that I am about to push (see #158), we can now start to put together solid pre-push CI, post-push CI and Nightly testing process that will well support the 'develop'/'master' workflow.  I will create a new Trilnos GitHub Issue specifically on the issue of standardizing a pre-push CI testing process based on the SEMS Dev Env.  We will also discuss at a Trilinos Leaders Meeting soon.

Thanks for your patience.

**Comment by bartlettroscoe** [comment]
I pushed the commits b9c9411 and bb71e38.

To local enable the test `ROL_test_sol_solTeuchosBatchManager_MPI_4` in order to fix it, just configure with `-DROL_test_sol_solTeuchosBatchManager_MPI_4_DISABLE=FALSE`.   Then, once you get it working, just revert commit bb71e38 with:

```
$ git revert  bb71e38
```

and test and push (e.g. using the new checkin-test-sems.sh script, soon to be documented).

As for the test `ROL_example_PDE-OPT_elasticitySIMP_topologyOptimization_example_01_MPI_1`, ROL developers can enable it by configuring with `-DTrilinos_TEST_CATEGORIES=HEAVY`.  If you can make this test complete in less than 10 minutes in a RELEASE_DEBUG build, then you can change the category to `NIGHTLY` or even `CONTINUOUS` if you can get it to run fast enough.

I am turning this over to ROL developers now.

**Comment by dridzal** [comment]
We should be able to reenable a large number of tests after the ROL 2.0 branch is merged with develop.
