### ISSUE TITLE
Framework: new version of gtest with gmock and gtest_main

### ISSUE THREAD

**Issue by rppawlo** [trilinos/Trilinos#4421]
@trilinos/framework - is there any chance someone could upgrade the gtest version in Trilinos to the most recent release and make sure to include gmock and gtest_main? Since gtest is installed as part of Trilinos, some external apps are interested in leveraging this.

@jwillenbring @bathmatt

**Comment by mhoemmen** [comment]
Is that the gtest in @trilinos/kokkos ?

**Comment by rppawlo** [comment]
> Is that the gtest in @trilinos/kokkos ?

no - was talking about the one in Trilinos/commonTools/gtest. Is one snapshotted into trilinos as part of kokkos?

**Comment by prwolfe** [comment]
We were talking in todays standup about having two versions (which is not acceptable for a few reasons). We need to decide on a single solution for this before worrying about version changes.

common/gtest is "a fused source version of test 1.7.0"
packages/kokkos/tpls/gtest is "a fused source version of test 1.7.0"

but there are large differences between them for whatever reason including diffs in the source and header files in one that are missing from the other.

@trilinos/framework @trilinos/kokkos

**Comment by prwolfe** [comment]
Well, it turns out the version in common has been updated to 1.8.0 according to the commit messages, just that noon updated the readme.

ouch.
