### ISSUE TITLE
ROL: incomplete StepFactory class ?

### ISSUE THREAD

**Issue by jschueller** [trilinos/Trilinos#4426]
@trilinos/rol

I wonder why ROL_StepFactory.hpp allows only to build a subset of the available algorithms:
https://github.com/trilinos/Trilinos/blob/master/packages/rol/src/step/ROL_StepFactory.hpp#L73

As some others are available, like Newton-Krylov:
https://trilinos.org/docs/r12.12/packages/rol/doc/html/group__step__group.html

The same applies in isValidStep(), used in the OptimizationSolver interface.
https://github.com/trilinos/Trilinos/blob/master/packages/rol/src/zoo/ROL_Types.hpp#L357

**Comment by dridzal** [comment]
@jschueller 
You can get globalized Newton-Krylov if you select LineSearch as your Step followed by
```
       <ParameterList name="Descent Method">
        <Parameter name="Type"              type="string" value="Newton-Krylov"    /> 
      </ParameterList>
```
in the corresponding xml input file.  I believe that some of the Steps are best used through other robust, globally convergent Steps.

@dpkouri , could you please comment as well?

**Comment by dpkouri** [comment]
StepFactory only offers globalized steps (resulting in algorithms that converge from arbitrary initial guesses).  As @dridzal mentioned, you can use Newton-Krylov in conjunction with line search.

**Comment by jschueller** [comment]
ok, I guess that settles it, thanks
