### ISSUE TITLE
MueLu "repartition: heuristic target rows per process" not found

### ISSUE THREAD

**Issue by spdomin** [trilinos/Trilinos#4439]
New problem with select Muelu Nalu regression tests using develop Trilinos (started with 2/19/2019 nightly testing).

Error is as follows (all platforms):

terminate called after throwing an instance of 'MueLu::Exceptions::RuntimeError'
terminate called after throwing an instance of 'MueLu::Exceptions::RuntimeError'
  what():  /scratch/spdomin/nightlyBuildAndTest/Trilinos/packages/muelu/src/MueCentral/MueLu_Level.hpp:196:

Throw number = 1

Throw test that evaluated to true: !IsKey(fac, ename)

"repartition: heuristic target rows per process" not found
terminate called after throwing an instance of 'MueLu::Exceptions::RuntimeError'
  what():  /scratch/spdomin/nightlyBuildAndTest/Trilinos/packages/muelu/src/MueCentral/MueLu_Level.hpp:196:

Bad (2/19):

NaluCFD/Nalu SHA1: df59923cdcaf75cb68a715932b134596d5ebf733
Trilinos/develop SHA1: fc0976b09507f493cee89d2e8591bb0fa1e9fbe6

Good (2/18):

NaluCFD/Nalu SHA1: df59923cdcaf75cb68a715932b134596d5ebf733
Trilinos/develop SHA1: 30457dff21c3bbe6dc5ed0de6d44ea776db8f8d9

The following tests FAILED:
	  1 - ablNeutralEdge (Failed)
	 27 - elemHybridFluids (Failed)
	 74 - oversetHybrid (Failed)
	 75 - uqSlidingMeshDG (Failed)
	 76 - waleElemXflowMixFrac3.5m (Failed)

**Comment by cgcgcg** [comment]
@spdomin I'll have a look!

**Comment by cgcgcg** [comment]
@spdomin I pushed a fix, could you check if it helped?

**Comment by spdomin** [comment]
Thanks - I will report back when the nightly tests run as I test develop nightly. Best.

**Comment by spdomin** [comment]
The throws are gone. However, a new diff in the formerly throwing/failing waleElem* test appeared last night. If I look at the two log files, I see that the Muelu iteration counts are the same, however, the residuals are different.

Do you have any reason to believe that the set of changes you made should cause a diff? In general, my philosophy is simple in that diffs are fine if they are 1) understood and 2) improve the code base. If both are true, I can accept the diffs. However, generally, one or both of the above are mysteries. In such cases, I like to revert and take a step back to understand what nuance I might be missing.

Let me know what you feel regarding 1 and 2 above.

Best,

**Comment by cgcgcg** [comment]
@spdomin The change we made should speed up the repartitioning done by Zoltan2. However, setting the `mj_premigration_coordinates` to something different will most likely change the actual partition that is returned. So I don't think that this should worry us.
@kddevin, can you confirm that this can happen?

**Comment by spdomin** [comment]
Makes sense. Once Karen confirms, I can re-bless. Once I have a clean nightly, I can close the ticket.

**Comment by kddevin** [comment]
Karen confirms.

**Comment by spdomin** [comment]
Okay, I will proceed with a re-bless and report back (to close) tomorrow AM.

**Comment by jhux2** [comment]
Closing.  Please reopen if necessary.

**Comment by jhux2** [comment]
Closing.  Please reopen if necessary.
