### ISSUE TITLE
Ifpack2::BlockRelaxation: Refactor so each Container does multiple solves

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#444]
@trilinos/ifpack2 @csiefer2 @jhux2 

This work will enable thread parallelization across inner ("Container") solves, for outer block Jacobi or a single color of block Gauss-Seidel / SOR.

This refactor will have the beneficial side effect of making the second template parameter (`ContainerType`) of BlockRelaxation optional and unnecessary.  This is just like what we did with Ifpack2::AdditiveSchwarz a while back.

Here is a gradual porting strategy:
### 1. Make the default value of BlockRelaxation’s `ContainerType` template parameter `Container<MatrixType>`

This doesn’t actually change the tests.  Tests at this point will still specify a nondefault second template parameter explicitly.  Ditto for BlockRelaxation's explicit template instantiation (ETI).
### 2. Write a factory to create `Container<MatrixType>` instances

```
template<class MatrixType>
Teuchos::RCP<Container<MatrixType> >
createContainer (const std::string& containerName, const Teuchos::RCP<const MatrixType>& A, const Teuchos::ArrayView<const typename MatrixType::local_ordinal_type>& localRows);
```

Put this function in the `Ifpack2::Details` namespace.  You shouldn’t have to change any Container subclasses to do this.  Create a new header file Ifpack2_Details_createContainer.hpp.  It will unfortunately (currently) need to include all the header files for all the Container subclasses.
### 3. Replace `ContainerType` constructor invocations in BlockRelaxation with factory calls

See the implementation of `Ifpack2::BlockRelaxation::ExtractSubmatrices`.  Replace `ContainerType` constructor invocations with calls to `createContainer`.
### 4. Change tests, examples, and instantiations of BlockRelaxation to leave off the second template parameter (so it uses the default)

If users actually do specify the second template parameter to be a concrete subclass of Container, you’ll have to map from the class name to the string (to pass into `createContainer`).

Every Container subclass needs a static (class) function that returns its name.  This can be passed into `createContainer`.
### 5. Change Container and its subclasses to do all the blocks (a whole color’s worth) inside; make BlockRelaxation use this

This is the actual work.  I will describe this in more detail below.

It’s important to test against MueLu, because MueLu uses Ifpack2::BlockRelaxation for Vanka smoothing.

Think about how to do Step 5 in a way that allows porting one Container subclass at a time to do all the block solves inside.

**Comment by mhoemmen** [comment]
This comment explains Step 5 above, and gives background on the algorithms.

Ifpack2::BlockRelaxation implements general overlapping domain decomposition within an MPI process.  (It thus differs from Ifpack2::AdditiveSchwarz, which implements _additive_ Schwarz, a.k.a. block Jacobi, across MPI processes.)  Input to BlockRelaxation is a list of local index lists I_k.  Each I_k refers to both row and column indices (assume for the sake of argument they are the same).  I say I_k is a "list" rather than a set, because order may matter in the inner solver.  Different lists I_a and I_b on a process may overlap.  BlockRelaxation can do either Gauss-Seidel or Jacobi sweeps over blocks.  One Gauss-Seidel sweep looks like this (on each process):

for each k, sequentially:
  Gather x(I_k) and b(I_k) into x_local resp. b_local
  Solve A(I_k, I_k) x_local = b_local for x_local
  Scatter x_local and b_local back into x(I_k) resp. b(I_k)
end for

and one Jacobi sweep looks like this:

for each k, gather
for each k, solve
for each k, scatter

Each of the three "for each k" loops in a Jacobi sweep may be done in parallel; the loop order doesn't matter.

BlockRelaxation is a parameterized algorithm.  Its parameters are:

  1. "Outer" relaxation (Gauss-Seidel or Jacobi; loop order of Gauss-Seidel)
  2. Storage format of input matrix A ({Crs, BlockCrs, Row}Matrix)
  3. Storage format of each block A(I_k, I_k) (dense, sparse, tridiagonal, banded)
  4. How to solve each block linear system
  5. How to compute / get the I_k sets (Ifpack2 calls this a "Partitioner"; "UserPartitioner" takes the user's list of lists as input)

(3) and (4) are ALWAYS HOMOGENEOUS -- that is, for a given input matrix A, we always use the same block storage format and solution algorithm for all the blocks.  Right now, (3) and (4) happen through some weird combination of run-time and compile-time polymorphism.  Polymorphism is PER BLOCK.  This hinders thread parallelism, and efficiency in general.  Thus, our redesign should push the Jacobi sweep inside of the "container" class (making it a "container collection").  This would let us thread-parallelize line smoothing, both coarsely over lines, and finely within a line.

We would still need some way to implement a sequential sweep, or even a coloring Gauss-Seidel sweep (where blocks of the same color may be solved in parallel, but different colors must be solved in sequence).

**Comment by mhoemmen** [comment]
I marked this as "in progress" because Brian (the assignee) has already started on this.  Thanks @brian-kelley !

**Comment by tawiesn** [comment]
@mhoemmen  @brian-kelley  @csiefer2  What's the current status of this?

**Comment by brian-kelley** [comment]
The 5 steps above are done, plus I replaced MultiVector with Kokkos::View for all apply() computations (except for SparseContainer::applyImpl), which yielded a big performance improvement. The work is being done in my fork of Trilinos.

Only one BlockRelaxation unit test was failing (overlapping partitioner, DenseContainer). I will continue working on this next week and I don't anticipate it will take long to get that test to pass.

**Comment by tawiesn** [comment]
Thanks for the update

**Comment by mhoemmen** [comment]
> Only one BlockRelaxation unit test was failing (overlapping partitioner, DenseContainer).

Was it passing before?  I'm not sure if the overlapping case in BlockRelaxation works at all.

**Comment by brian-kelley** [comment]
Aha, I accidentally un-commented that test at some point. So all tests are passing, I think.

**Comment by mhoemmen** [comment]
@csiefer2, @brian-kelley, and I had a phone meeting today to review the code.  MPI tests are still failing.  We're working on diagnosing them.

**Comment by mhoemmen** [comment]
Here is Brian's branch: https://github.com/brian-kelley/Trilinos/tree/newDevelop

I am doing an MPI_DEBUG build with it as I write.

**Comment by mhoemmen** [comment]
Need to clean up "will be initialized after", "unused variable", and "comparison between signed and unsigned integer expressions" warnings.  Must build clean with -Wall.

**Comment by mhoemmen** [comment]
Ifpack2 tests that failed (I'm doing an OpenMP build with GCC 4.7.2):
  - Ifpack2_unit_tests_MPI_4
  - Ifpack2_TomVankaTest_MPI_4

**Comment by mhoemmen** [comment]
I studied Ifpack2_unit_tests a bit more closely.  TriDi fails for me:

```
21:  Comparing lhs.get1dView() == exact_soln.get1dView() ...
21:  Error, relErr(lhs.get1dView()[0],exact_soln.get1dView()[0]) = relErr(0,2) = 1 <= tol = 4.44089e-16: failed!
21:
21:  Error, relErr(lhs.get1dView()[1],exact_soln.get1dView()[1]) = relErr(0,2) = 1 <= tol = 4.44089e-16: failed!
21:
21:  Error, relErr(lhs.get1dView()[2],exact_soln.get1dView()[2]) = relErr(0,2) = 1 <= tol = 4.44089e-16: failed!
21:
21:  Error, relErr(lhs.get1dView()[3],exact_soln.get1dView()[3]) = relErr(0,2) = 1 <= tol = 4.44089e-16: failed!
21:
21:  Error, relErr(lhs.get1dView()[4],exact_soln.get1dView()[4]) = relErr(0,2) = 1 <= tol = 4.44089e-16: failed!
21:  [FAILED]  (0.00296 sec) Ifpack2BlockRelaxation_default_scalar_type_default_local_ordinal_type_default_global_ordinal_type_TriDi_UnitTest
21:  Location: /scratch/prj/Trilinos/Trilinos/packages/ifpack2/test/unit_tests/Ifpack2_UnitTestBlockRelaxation.cpp:253
```
LinePartition, BandedContainer, and BandedBlockedContainer tests fail with similar error messages.  I then get some view bounds errors from Kokkos, that appear to happen in Ifpack2::Container:
```
21: [artemis:87052] [ 6] /scratch/prj/Trilinos/CHECKIN-GCC-4.7.2/MPI_DEBUG/packages/ifpack2/src/libifpack2.so.12(_ZNK7Ifpack29ContainerIN6Tpetra9RowMatrixIdiiN6Kokkos6Compat23KokkosDeviceWrapperNodeINS3_6OpenMPENS3_9HostSpaceEEEEEE13DoGaussSeidelERNS3_12Experimental4ViewIPPdINS3_10LayoutLeftENS3_6DeviceIS6_S7_EEEEESJ_i+0x557)[0x7fd45944c0e1]
```
Enable the CMake options Kokkos_ENABLE_DEBUG=ON and Teuchos_ENABLE_DEBUG=ON to get bounds checking.  MPI_DEBUG _must_ pass clean with these options enabled.

**Comment by brian-kelley** [comment]
I fixed all the test failures and warnings and pushed to newDevelop.

**Comment by mhoemmen** [comment]
@brian-kelley @csiefer2 Thanks Brian!  I just tried your changes and they pass MPI_DEBUG with OpenMP!  Good work!!! :-D  It may be easiest just for me to cherry-pick them over.  Are they just the four commits on top:

```
commit 095a5bb8874cf89802b5d9b992885b95882097fe
Author: Brian Kelley <brian.honda11@gmail.com>
Date:   Tue Nov 1 15:13:14 2016 -0500

    Ifpack2: Fixed parallel BlockRelaxation

    -BlockRelaxation/Container were not doing Y vector import at correct
    times
    -BlockRelaxation importer was not being updated correctly
    -Container created incorrect importer, now it shares correct one with
    BlockRelaxation (in RCP)
    -Correct Import is passed to Container though
    Details::ContainerFactory
    -Fixed warnings in Container subclasses and BlockRelax performance test

commit 3daa84feb3c384211041baf10ed2cd5826afe344
Author: Brian Kelley <brian.honda11@gmail.com>
Date:   Mon Oct 31 16:53:33 2016 -0500

    Ifpack2: Fixed block relaxation perf test in MPI

    -Epetra comm now created correctly based on EPETRA_MPI define
    -BlockRelaxation constructor calls setMatrix so importer is created

commit 2eadd4ac8cf6fbc36e2d06788b88b3c144170d0f
Author: Brian Kelley <brian.honda11@gmail.com>
Date:   Thu Oct 6 18:13:42 2016 -0500

    Ifpack2: BlockRelaxation refactoring

    -Major refactoring of BlockRelaxation and
     Containers (done for performance reasons)
    -Container object now holds all blocks of a
     problem, instead of just one
    -Jacobi, Gauss-Seidel and SGS implementations
     moved into Container
    -Most internal Container operations now
     done with Kokkos::View instead of MultiVector
    -Added optional test to compare Ifpack2 speed
     with ML at various block sizes

commit b095a9ac59e563e242a2939bd59eaefe5b7e6930
Author: Brian Kelley <brian.honda11@gmail.com>
Date:   Thu Oct 6 18:02:10 2016 -0500

    Teuchos: Fixed SerialTriDiMatrix copy constructor

    -In conjugate transpose case, loop that copied elements
     was missing index operator
```

**Comment by brian-kelley** [comment]
Yes that's all of it and it should rebase/merge cleanly on the main develop.

**Comment by mhoemmen** [comment]
@brian-kelley wrote:
> Yes that's all of it and it should rebase/merge cleanly on the main develop.

Cool, thanks for testing that!  I'll do a rebase then.  I'll try CUDA just to see if it works before running tests and pushing.

**Comment by mhoemmen** [comment]
GCC 4.7.2, OpenMP, MPI_DEBUG and SERIAL_RELEASE all build Ifpack2 and pass Ifpack2 unit tests.  I'll test CUDA now.  If that works, I'll do an Ifpack2 and downstream test with GCC 4.7.2 (just want to make sure we don't break Stokhos, since it does some Ifpack2 instantiations).

**Comment by csiefer2** [comment]
Sweet!

@mhoemmen : If you want to handle the commit to Trilinos/develop, go right ahead?

**Comment by mhoemmen** [comment]
> @mhoemmen : If you want to handle the commit to Trilinos/develop, go right ahead?

Gladly, thanks!  CUDA MPI_DEBUG passes Ifpack2 build and tests.  I'm looking at CUDA MPI_RELEASE now.

**Comment by mhoemmen** [comment]
Sorry folks, got hung up in meetings.  I should be able to finish downstream tests tomorrow.  If Stokhos doesn't break, I should be able to push then too.

**Comment by mhoemmen** [comment]
Hm, the changes cause build errors in Stokhos.  Given that the Trilinos freeze is scheduled for tomorrow and I'm in a meeting all afternoon, I don't think it's wise for me to try to fix this and push before the freeze.

**Comment by brian-kelley** [comment]
Fixed Stokhos build, all MueLu/Ifpack2/Stokhos test pass. I put back the stub implementations of Dense/TriDi/Banded container classes where LAPACK doesn't support LocalScalarType.

**Comment by srajama1** [comment]
Should I wait for this to be pushed before I work on https://github.com/trilinos/Trilinos/issues/288 

It appears there will be lot of changes around the same area ?

**Comment by mhoemmen** [comment]
@srajama1 wrote:
> Should I wait for this to be pushed before I work on #288

No, this work is independent of #288.  It only affects Ifpack2::BlockRelaxation and Ifpack2's "container" classes.  #288 is point Gauss-Seidel and has nothing to do with block relaxation.

**Comment by srajama1** [comment]
Thanks ! I misinterpreted the containers might somehow manage both point and block.

**Comment by mhoemmen** [comment]
Doing final warning fixes and testing now.  CUDA MPI_DEBUG passes Ifpack2 tests.

**Comment by mhoemmen** [comment]
Also, non-CUDA Clang 3.9 build passes Stokhos tests.  Thanks @brian-kelley for fixing Stokhos :)

**Comment by mhoemmen** [comment]
Argh, have to do MPI_RELEASE for CUDA, forgot about the nvlink-running-out-of-memory issue that has nothing to do with this refactor.

**Comment by mhoemmen** [comment]
Just pushed changes.  Thanks @brian-kelley and @csiefer2 !

**Comment by mhoemmen** [comment]
FYI, CUDA MPI_RELEASE passed Stokhos build and tests.
