### ISSUE TITLE
Albany nightly builds (waterman, fedora + gcc) are broken b/c of Xpetra

### ISSUE THREAD

**Issue by ikalash** [trilinos/Trilinos#4440]
Looks like Trilinos broke a couple of the Albany builds (waterman, fedora + gcc). The culprit seems to be @trilinos/xpetra .

```
.../repos/Trilinos/packages/stk/stk_topology/stk_topology/apply_functor.hpp(154): here
            instantiation of "stk::topology::apply_host_functor::result_type stk::topology::apply_host_functor::operator()(stk::topology::topology_t) [with Functor=stk::topology_detail::face_nodes_impl>>>]" 
/.../repos/Trilinos/packages/stk/stk_topology/stk_topology/topology_utils.hpp(521): here
            instantiation of "void stk::topology::face_nodes(const NodeArray &, unsigned int, NodeOutputIterator) const [with NodeArray=const stk::mesh::Entity *, NodeOutputIterator=__gnu_cxx::__normal_iterator>>]" 
/.../repos/Trilinos/packages/stk/stk_topology/stk_topology/topology.hpp(262): here
            instantiation of "void stk::topology::sub_topology_nodes(const NodeArray &, unsigned int, unsigned int, NodeOutputIterator) const [with NodeArray=const stk::mesh::Entity *, NodeOutputIterator=__gnu_cxx::__normal_iterator>>]" 
/.../repos/Trilinos/packages/stk/stk_topology/stk_topology/topology.hpp(310): here
            instantiation of "void stk::topology::side_nodes(const NodeArray &, unsigned int, NodeOutputIterator) const [with NodeArray=const stk::mesh::Entity *, NodeOutputIterator=__gnu_cxx::__normal_iterator>>]" 
/.../repos/Trilinos/packages/stk/stk_mesh/stk_mesh/baseImpl/elementGraph/ElemElemGraphImpl.cpp(86): here

/.../repos/Trilinos/packages/xpetra/src/CrsMatrix/Xpetra_CrsMatrixFactory.hpp(288): error: object of abstract class type "Xpetra::TpetraCrsMatrix" is not allowed:

            pure virtual function "Xpetra::CrsMatrix::setObjectLabel [with Scalar=double, LocalOrdinal=int, GlobalOrdinal=int, Node=Xpetra::EpetraNode]" has no overrider

```
http://cdash.sandia.gov/CDash-2-3-0/viewBuildError.php?buildid=81706 
http://cdash.sandia.gov/CDash-2-3-0/viewBuildError.php?buildid=81711

**Comment by alanw0** [comment]
As an aside, the stk team has some work nearly finished which will fix the stk_topology warnings...

**Comment by ikalash** [comment]
Looks like this was a problem on NERSC as well: https://my.cdash.org/viewBuildError.php?buildid=1610941 .  Both Cori and Edison builds failed.

**Comment by cgcgcg** [comment]
@csiefer2 ?

**Comment by csiefer2** [comment]
Well, that's weird.

**Comment by csiefer2** [comment]
Is this an error building Albany or Trilinos?

**Comment by ikalash** [comment]
@csiefer2 : Trilinos.

**Comment by csiefer2** [comment]
Can you send me the location for your waterman build scripts?

**Comment by ikalash** [comment]
@csiefer2 : sure, Trilinos build options are here https://github.com/SNLComputation/Albany/blob/master/doc/dashboards/waterman.sandia.gov/ctest_nightly.cmake.frag#L153-L290 

This is a CDash script, so to turn the options into a cmake script, you'd have to do a little bit of processing.

Note that the issue doesn't just happen on waterman, so it's not just a GPU thing.

**Comment by ikalash** [comment]
Here are also the modules: https://github.com/SNLComputation/Albany/blob/master/doc/dashboards/waterman.sandia.gov/waterman_modules_cuda.sh

**Comment by csiefer2** [comment]
Out of Cori, Edison and Waterman, the last is the easiest to get to :)

**Comment by csiefer2** [comment]
That fails to configure somewhere in Kokkos due to invalid cmake logic.

Any other local machines I can try on?

**Comment by ikalash** [comment]
Hmmm, it shouldn't since it configured in the nightlies last night.  Is it possible you have a syntax error in converting the relevant code to a cmake script?  @jewatkins, do you happen to have a waterman Trilinos configure script that's equivalent to the nightly that you could share with Chris?  Do you have a NERSC account?  The builds there are pretty easy to reproduce.  The only other machine is one of Alejandro's Fedora machines, which I could get you access to if necessary.

**Comment by ikalash** [comment]
(it shouldn't unless Kokkos broke our configuration, which given how often Trilinos breaks Albany these days, is possible...  sigh...)

**Comment by csiefer2** [comment]
CMake Error at packages/kokkos/cmake/kokkos_settings.cmake:25 (list):
  list sub-command FIND requires three arguments.

**Comment by csiefer2** [comment]
Not sure how much that matters though... cmake tries to configure onward.

**Comment by ikalash** [comment]
Hmmm, not seeing that message in our nightly configuration output: http://cdash.sandia.gov/CDash-2-3-0/viewConfigure.php?buildid=81706

**Comment by csiefer2** [comment]
Ah!  I believe that was an error in the de-cmakeification on my part.

**Comment by csiefer2** [comment]
Building now.  Will look at the error in AM

**Comment by ikalash** [comment]
Ok, thanks Chris!

**Comment by mhoemmen** [comment]
@theguruat12 Is this related to the build errors that @crdohrm saw?

**Comment by ikalash** [comment]
Looks like the problem is happening on Ride too.  This is a clue - Ride was fine last night, but the Ride build happens earlier than the others, at 8PM.  This suggests the problematic code was checked in last night after this time.

**Comment by csiefer2** [comment]
https://github.com/trilinos/Trilinos/pull/4460

**Comment by jhux2** [comment]
@ikalash Do the Albany tests pull Trilinos directly from github, or are they all sync'd to test the same Trilinos SHA1?  The latter is what the Trilinos nightly tests do.

**Comment by ikalash** [comment]
@jhux2: we pull directly from github, develop branch.  Sync'ing to a SHA is something we've discussed (tagging @bartgol, @ibaned), but never implemented for the testing.

**Comment by bartgol** [comment]
Now that develop->master happens much more frequently in Trilinos, I guess we can pull master rather than develop. We started pulling develop a while ago, before the autotester era, when promotions were slower and it could take a while to get fixes from develop in master. Now, I think this concern no longer exists. I think.

**Comment by theguruat12** [comment]
> @theguruat12 Is this related to the build errors that @crdohrm saw?

I believe it's related, but alas, I'm not really a C++ developer, so it's more of an educated guess based on the pure-virtual messages and emanating from the same file.

**Comment by ikalash** [comment]
@bartgol : if develop is merged into master nightly (provided the tests pass), I'm open to switching the Albany nightlies to build against master rather than develop.  We should check with @lxmota , the owner of the nightlies that I do not own.  Alejandro, would you be OK switching your nightlies to build against master which gets updated almost every night now and has to pass more stringent checks, so we will likely have a more stable dashboard?

**Comment by csiefer2** [comment]
Merged.  @ikalash  Please check the nightlies this evening and let me know.

**Comment by ikalash** [comment]
@csiefer2 : thanks, will do!

**Comment by lxmota** [comment]
@ikalash If the lead time of develop vs master is only a few days, I think it should be OK to switch.

**Comment by ikalash** [comment]
Ok, great.  I opened an Albany issue so please lets move this discussion there: https://github.com/SNLComputation/Albany/issues/437 .

**Comment by ikalash** [comment]
We had new failures last night in our builds due to stk, but I think this problem has been resolved - thanks @csiefer2 !
