### ISSUE TITLE
EpetraExt HDF5 MATLAB example needs to namespace cout and cerr

### ISSUE THREAD

**Issue by bavier** [trilinos/Trilinos#445]
Currently `packages/epetraext/example/inout/HDF5_MATLAB.cpp` fails to build from source because of undefined `cout` and `cerr`.  This patch should fix it.

[epetraext-hdf5-matlab.patch.txt](https://github.com/trilinos/Trilinos/files/314410/epetraext-hdf5-matlab.patch.txt)

**Comment by jwillenbring** [comment]
@bmpersc If you are applying any patches in the near future, please consider applying this one too. I will do the same.

**Comment by bmpersc** [comment]
Does this need to be applied to the 12.6 branch?

**Comment by jwillenbring** [comment]
I spoke with @bmpersc and he will apply this to both 12.6 and develop/master.

**Comment by bmpersc** [comment]
patch has been applied to 12.6 and is available in the 12.6.4 release tarball. I have not applied it to develop yet.
