### ISSUE TITLE
Phalanx: add support for field aliasing

### ISSUE THREAD

**Issue by rppawlo** [trilinos/Trilinos#446]
@trilinos/phalanx

Some applications would like the ability to alias one MDField to another in the DAG.
1. Gather requirements from app teams.
2. Implement support in Field manager.

**Comment by rppawlo** [comment]
@eric-c-cyr - talked to Suzey - does not need this anymore.  Putting into backlog.

**Comment by eric-c-cyr** [comment]
Not disagreeing with you about back burner, but I'd actually like this capability (perhaps more than Suzey).

**Comment by rppawlo** [comment]
done!
