### ISSUE TITLE
Framework: Autotester Occasionally Refuses to Do Inspection

### ISSUE THREAD

**Issue by csiefer2** [trilinos/Trilinos#4461]
Which means you can't merge a tested, approved PR.

This can be 'fixed' by throwing on 'AT: RETEST' and burning another 4 hours of testing time (if the test machines all work), but this is getting annoying.

@trilinos/framework @william76 @jwillenbring

**Comment by csiefer2** [comment]
This has happened to me two times in under a week, and is well known enough that other devs recommend 'AT: RETEST' in comments:

https://github.com/trilinos/Trilinos/pull/4401
https://github.com/trilinos/Trilinos/pull/4297
https://github.com/trilinos/Trilinos/pull/4446

**Comment by jwillenbring** [comment]
Please point me to one of these at the point where you would typically throw on a retest label (but don’t do it) so I can see exactly the state of things.

**Comment by csiefer2** [comment]
Next time, it happens, I will do so!

**Comment by mayrmt** [comment]
@jwillenbring Here's an example: #4566 Tests passed and reviewer has approved it, though the inspection did not happen automatically.

**Comment by jwillenbring** [comment]
@mayrmt 

The auto tester probably has not looked at this PR yet since the approval. That flag is set by the autotester, it cannot be automatically set by inspection.

**Comment by prwolfe** [comment]
Jim,

I was curious so I traced this one.

PR 4566 - autotester #1
job #24552 ran the testing and completed at 2019-03-07 12:29:01.908870 utc
job #24553 bypassed as no review were done at 2019-03-07 12:30:39.211372 utc
job #24554 bypassed as no review were done at 2019-03-07 12:39:06.603034 utc
job #24555 bypassed as no review were done at 2019-03-07 13:09:14.324933 utc
job #24556 bypassed as no review were done at 2019-03-07 13:39:09.136690 utc
job #24557 bypassed as no review were done at 2019-03-07 14:09:16.579730 utc
job #24558 bypassed as no review were done at 2019-03-07 14:39:14.191427 utc
Approval at 7:38 MST
job #24559 merged the PR at 8:08 MST - 2019-03-07 15:09:21.917707 utc

which shows this merged the first time the autotester ran after the approval. What looks like clock skew here is the fact that the approval and merge times are exact while the autotester job times are the ending times. In fact job #24558 was already running when the approval happened giving @mayrmt the maximum 30 minute wait time.

**Comment by jwillenbring** [comment]
@prwolfe Thank you for looking into this.

**Comment by cgcgcg** [comment]
@prwolfe This PR #4467 has been hanging for 6 hours now..

**Comment by prwolfe** [comment]
This one is more interesting.

A single instance of the autotester ram from about 8:30am to 4:37pm yesterday (your auto merge flag and review went in about 9:13). It did it's check for merging, then did builds for 2 different PR's in serial. When it closed up the next job was waiting and did the merge for your PR at 4:38.

Jim - this speaks to the business case for the redesign work we have been discussing.

Thanks @cgcgcg !

**Comment by prwolfe** [comment]
@csiefer2 - As there are currently no plans to redesign/rebuild the autotester I would like to close this one.  We are using incremental builds at this point which I expect will help relive the time pressures.
