### ISSUE TITLE
ROL: Remove build warnings

### ISSUE THREAD

**Issue by ZUUL42** [trilinos/Trilinos#4469]
@trilinos/rol 

## Expectations

ROL builds should not emit any warnings that will be promoted to errors once Werror is set in the GCC 7.2.0 automated build.

## Current Behavior

Currently ROL has a number of warnings that need to be handled before we can set Werror for all packages.
A recent test build was performed with -Werror set for ROL. The CDash report can be found [here](https://testing.sandia.gov/cdash/viewBuildError.php?buildid=4983662).
UPDATE: [CDash](https://testing.sandia.gov/cdash/viewBuildError.php?buildid=5301681) after most recent ROL sync.

## Motivation, Context and Related Issues

Issue #3178 is working toward turning Warnings as Errors on for all packages.

**Comment by ZUUL42** [comment]
If you'd like the PR to test with Werror set for ROL, pull the commit from branch [Werror_ROL](https://github.com/ZUUL42/Trilinos/tree/Werror_ROL).

**Comment by ZUUL42** [comment]
I've made a [number minor changes](https://github.com/trilinos/Trilinos/compare/master...ZUUL42:Werror_ROL) and have got this issue down to one Werror. However, I'm not quite sure what might be the reasonable/prefered solution for this last one.
@dridzal @trilinos/rol @trilinos/tempus  Would you have any input?

[CDash](https://testing.sandia.gov/cdash/index.php?project=Trilinos&parentid=5321033&filtercount=1&showfilters=1&field1=buildstamp&compare1=61&value1=20190718-1619-Experimental)
`...`
`/scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_7.2.0/Trilinos/packages/teuchos/core/src/Teuchos_RCPDecl.hpp:990:33: error: deleting object of polymorphic class type ‘ROL::PinTVectorCommunication_Tpetra<double>’ which has non-virtual destructor might cause undefined behavior [-Werror=delete-non-virtual-dtor]`
`   void free( T* ptr ) { if(ptr) delete ptr; }`

**Comment by dridzal** [comment]
@ZUUL42 , my guess is that you would need to add a virtual destructor to the base class `PinTVectorCommunication`

`virtual ~PinTVectorCommunication() {}`

Let me know if it works.
