### ISSUE TITLE
stk broke Albany builds

### ISSUE THREAD

**Issue by ikalash** [trilinos/Trilinos#4470]
Another day, another issue on Trilinos breaking the Albany build...

Here is what we see in our nightlies:
```
[ 66%] Building CXX object packages/stk/stk_unit_test_utils/CMakeFiles/stk_unit_test_utils.dir/ReadWriteSidesetTester.cpp.o
/.../repos/Trilinos/SCOREC/stk/apfSTK.cc: In function 'T* apf::makeStkField(const char*, apf::StkMetaData*) [with T = stk::mesh::Field; apf::StkMetaData = stk::mesh::MetaData]':
```
We are getting the following error:
```
[ 66%] Building CXX object SCOREC/stk/CMakeFiles/apf_stk.dir/apfMeshSTK.cc.o 
[ 66%] Building CXX object packages/stk/stk_unit_test_utils/CMakeFiles/stk_unit_test_utils.dir/ParallelGtestOutput.cpp.o 
[ 66%] Building CXX object packages/stk/stk_unit_test_utils/CMakeFiles/stk_unit_test_utils.dir/ParticleUtils.cpp.o 
[ 66%] Building CXX object SCOREC/stk/CMakeFiles/apf_stk.dir/apfSTK.cc.o 
[ 66%] Building CXX object SCOREC/stk/CMakeFiles/apf_stk.dir/apfExodusOutput.cc.o 
[ 66%] Building CXX object packages/stk/stk_tools/stk_tools/CMakeFiles/stk_tools_lib.dir/mesh_clone/MeshCloneIo.cpp.o [ 66%] Building CXX object packages/tpetra/core/src/CMakeFiles/tpetra.dir/Tpetra_computeRowAndColumnOneNorms_DOUBLE_INT_LONG_LONG_SERIAL.cpp.o 
[ 66%] Building CXX object packages/tpetra/core/src/CMakeFiles/tpetra.dir/Tpetra_replaceDiagonalCrsMatrix_LONG_LONG_INT_LONG_LONG_SERIAL.cpp.o 
[ 66%] Building CXX object packages/stk/stk_unit_test_utils/CMakeFiles/stk_unit_test_utils.dir/ReadWriteSidesetTester.cpp.o /.../repos/Trilinos/SCOREC/stk/apfSTK.cc: In function 'T* apf::makeStkField(const char*, apf::StkMetaData*) [with T = stk::mesh::Field; apf::StkMetaData = stk::mesh::MetaData]':                         repos/Trilinos/SCOREC/stk/apfSTK.cc:130:14: error: 'put_field' is not a member of 'stk::mesh'
repos/Trilinos/SCOREC/stk/apfSTK.cc:130:14: error: 'put_field' is not a member of 'stk::mesh'
```
http://cdash.sandia.gov/CDash-2-3-0/viewBuildError.php?buildid=81771

Did the put_field method go away in STK?  If so, is there an alternate routine we should be doing?

@trilinos/stk 
k

**Comment by mhoemmen** [comment]
@ikalash I edited your comment for clarity.  @alanw0

**Comment by rppawlo** [comment]
yes - there was a deprecation warning being printed by STK in the December/January time frame. Here's the change for a panzer class (from 1333649c98):

```
-   stk::mesh::put_field( *facesField_ , metaData_->universal_part(), getDimension());
-   stk::mesh::put_field( *processorIdField_ , metaData_->universal_part());
-   stk::mesh::put_field( *loadBalField_ , metaData_->universal_part());
+   stk::mesh::put_field_on_mesh( *facesField_ , metaData_->universal_part(), getDimension(),nullptr);
+   stk::mesh::put_field_on_mesh( *processorIdField_ , metaData_->universal_part(),nullptr);
+   stk::mesh::put_field_on_mesh( *loadBalField_ , metaData_->universal_part(),nullptr);
```
We had an issue with 4.8 compilers. See commit cf5e5a33dcf96 if you need gcc 4.8 in Albany.

**Comment by alanw0** [comment]
@ikalash sorry for the breakage! Yes the put_field functions went away, replaced by the very similar put_field_on_mesh functions. The difference is that the last argument 'initialValue' is no longer optional. Sierra/Aria had encountered a scenario where if they didn't specify the optional argument, the compiler would pick the wrong overload of the function, and wrong behavior would occur. So we deprecated those methods late last year and have now deleted them. Our deprecation policy is as follows:
If we want to deprecate a function "foo", we wrap it like this:
`
#ifndef STK_HIDE_DEPRECATED_CODE
STK_DEPRECATE void foo();
# endif
'
So as long as you don't define STK_HIDE_DEPRECATED_CODE, then foo should still be available and you should see the deprecation warning. Then 2 sprints later (6 weeks), we go ahead and delete the deprecated code. In the sierra environment we do define the STK_HIDE_DEPRECATED_CODE macro, meaning the deprecated code is gone immediately and we must fix all dependent code immediately.

**Comment by alanw0** [comment]
Well that code formatting didn't work...

**Comment by ikalash** [comment]
Ah OK I see.  I added the ```-DSTK_HIDE_DEPRECATED_CODE``` configure option to the builds as a short term solution, and have opened an issue in Albany on switching SCOREC to the new syntax (https://github.com/SNLComputation/Albany/issues/438 ).

**Comment by alanw0** [comment]
@ikalash I don't know if I was clear - If you DON"T define STK_HIDE_DEPRECATED_CODE, then you get the deprecation warnings. If you DO define that macro, then deprecated stuff is hidden and you get a compile error, no deprecation warning. I would not expect codes to define that macro if they are outside of the sierra environment.

**Comment by ikalash** [comment]
@alanw0 : sorry for the confusion - yes, I understood there.  I was too hasty in cutting/pasting the configure option above - I've corrected it now.

**Comment by ikalash** [comment]
@alanw0 : I added a new debug Albany build to our nightly test harness at the end of last week that uses a clang compiler.  There is a stk-related undefined reference error when building Albany that happens only in this build: 
```
repos/Trilinos/packages/stk/stk_topology/stk_topology/topology_detail/meta_functions.hpp:91: undefined reference to `stk::topology_detail::topology_data<(stk::topology::topology_t)0, void>::spatial_dimension_vector'                  
/.../test/TrilinosInstallC11Dbg/lib/libstk_mesh_base.a(MetaData.cpp.o): In function `bool stk::topology_detail::defined_on_spatial_dimension_, 2u>()':
```
http://cdash.sandia.gov/CDash-2-3-0/viewBuildError.php?buildid=81850

Would this be related to recent changes pushed to STK?

**Comment by alanw0** [comment]
@ikalash Yes that was related to the recent STK changes. I put in a pull-request today, which should fix this. Hopefully the next nightly test will confirm.

**Comment by ikalash** [comment]
@alanw0 : great.  I'll keep an eye on the nightlies to check that the issue got fixed.  Thanks!

**Comment by ikalash** [comment]
Just to follow up @alanw0 : the issue went away in today’s nightlies.  Thanks again!
