### ISSUE TITLE
Belos: Remove build warnings

### ISSUE THREAD

**Issue by ZUUL42** [trilinos/Trilinos#4473]
@trilinos/belos  

## Expectations

Belos builds should not emit any warnings that will be promoted to errors once Werror is set in the GCC 7.2.0 automated build.

## Current Behavior

Currently Belos has a number of warnings that need to be handled before we can set Werror for all packages.
A recent test build was performed with -Werror set for Belos. The CDash report can be found [here](https://testing.sandia.gov/cdash/viewBuildError.php?buildid=4589921).

## Motivation, Context and Related Issues

Issue #3178 is working toward turning Warnings as Errors on for all packages.

**Comment by srajama1** [comment]
@trilinos/belos @hkthorn

**Comment by ZUUL42** [comment]
If you'd like the PR to test with Werror set for Belos, pull the commit from branch [Werror_Belos](https://github.com/ZUUL42/Trilinos/tree/Werror_Belos).
