### ISSUE TITLE
Teuchos Debug unit tests failing for Clang

### ISSUE THREAD

**Issue by MicheldeMessieres** [trilinos/Trilinos#449]
Three TeuchosParameterList unit tests are failing in Debug only, for clang only.
  TeuchosCore_MemoryManagement
  TeuchosParameterList_StringIndexedOrderedValueObjectContainer
  TeuchosParameterList_ObjectBuilder

**Comment by MicheldeMessieres** [comment]
Jim and I discussed these briefly. The tests failures are specific to debug and clang. I'll plan to work on them in a few days unless someone already has something in progress.

**Comment by mhoemmen** [comment]
Those have been failing with Clang for a long time.  I suspect the failures are spurious, but it would be nice to have a detailed analysis.  Thanks!

**Comment by bartlettroscoe** [comment]
@MicheldeMessieres, the test `TeuchosParameterList_ObjectBuilder_UnitTests` is failing for me as well on GCC 5.3.0 on RHEL 6.  What are the specific failures you are seeing?

**Comment by MicheldeMessieres** [comment]
@bartlettroscoe PR #577 has the details analysis I did for those clang failures. The no except issues are essentially just to get the clang to compile the destructors the same way as gcc, but the fundamental issue is clang won't allow a second attempt to delete after the exception is thrown from the destructor - so it considers the final delete a double delete while in gcc the second attempt goes through. (As you are already aware, this is changing in the new RCP code where we we will no longer throw in the first place.)

**Comment by bartlettroscoe** [comment]
This may be fixed with the merge of the TEuchos MM class changes a few weeks back.

**Comment by MicheldeMessieres** [comment]
This should all be resolved as long as old clang is not being used.
