### ISSUE TITLE
Tpetra/Teuchos: Allow Teuchos Complex w/o Tpetra Complex

### ISSUE THREAD

**Issue by csiefer2** [trilinos/Trilinos#4495]
This is a moral follow-on to #4080, except, I would like to reverse our decision.

I have an application that wishes to do some complex arithmetic using Teuchos::SerialDenseMatrix on the host and then later due some computing using Tpetra & CUDA.

At present, the resolution of #4080 means we have to have complex support on in both places.  However, Kokkos will not compile w/ cuda if std::complex<double> is enabled.

This renders my application unable to use Trilinos on CUDA.

**Comment by mhoemmen** [comment]
@csiefer2 wrote:
> However, Kokkos will not compile w/ cuda if std::complex is enabled.

Is that a known issue?  If not, what are the build errors?

**Comment by csiefer2** [comment]
One sample error:

Kokkos_Cuda_Parallel.hpp(474): error: identifier "std::complex<double> ::__rep const" is undefined in device code

**Comment by csiefer2** [comment]
Also this:
/gpfs1/csiefer/doom/TPL/trilinos/devel/TrilinosGIT/Trilinos/packages/kokkos/core/src/Cuda/Kokkos_Cuda_Parallel.hpp(474): error: calling a constexpr __host__ function("std::complex<double> ::complex") from a __device__ function("Kokkos::Impl::ParallelFor< ::,  ::Kokkos::RangePolicy<int,  ::Kokkos::Cuda > ,  ::Kokkos::Cuda> ::operator () const") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.

**Comment by mhoemmen** [comment]
@csiefer2 What code is using `std::complex` with CUDA?  What's the context for this error?

**Comment by csiefer2** [comment]
@mhoemmen We have a situation where the code does not require std::complex, but one of its TPL's does.

**Comment by mhoemmen** [comment]
@csiefer2 It sounds like some code is trying to use `std::complex` in a Kokkos parallel region on device.  What code is that?

**Comment by mhoemmen** [comment]
What I'm getting at is that I plan to mark this issue as "wontfix" and open a new issue for the CUDA build error.  We have a CUDA build in PR tests now, so if enabling complex results in a build error, we need to fix that.

**Comment by csiefer2** [comment]
I disabled the configure time test in Tpetra (it is now a warning), building only SerialNode and ran with the following options:

-D Teuchos_ENABLE_COMPLEX=ON 
-D Trilinos_ENABLE_COMPLEX=OFF 
-D Tpetra_INST_COMPLEX_DOUBLE=OFF 

All Stratimikos, Thyra, and MueLu tests pass. I'm not sure we need to wontfix this.

**Comment by csiefer2** [comment]
Another, related issue, is that I'm now forced to build a std::complex version of the entire Tpetra stack, which I'll never use.

**Comment by mhoemmen** [comment]
@csiefer2 I would like to see the build errors for the CUDA build.  That's a bug that we should file separately.

**Comment by csiefer2** [comment]
@mhoemmen Check your email :)

**Comment by mhoemmen** [comment]
It looks like MueLu is using `std::complex` in a device parallel region.  That's not allowed.  `Kokkos_Complex.hpp` has documentation saying this.  This is why `impl_scalar_type` exists in Tpetra.

**Comment by mhoemmen** [comment]
@csiefer2 wrote:
> Another, related issue, is that I'm now forced to build a `std::complex` version of the entire Tpetra stack, which I'll never use.

That's a separate question, worth answering :-)  Be sure to check whether Thyra builds correctly.  I think Thyra takes its ETI settings from `Trilinos_ENABLE_${SCALAR}`, and I'm not sure if it checks Teuchos' settings.

**Comment by csiefer2** [comment]
Could you open a separate bug for that?

**Comment by csiefer2** [comment]
> That's a separate question, worth answering :-) Be sure to check whether Thyra builds correctly. I think Thyra takes its ETI settings from `Trilinos_ENABLE_${SCALAR}`, and I'm not sure if it checks Teuchos' settings.

It did build correctly.

**Comment by mhoemmen** [comment]
Build error example: 
```
.../Trilinos/packages/muelu/src/Transfers/Smoothed-Aggregation/MueLu_TentativePFactory_kokkos_def.hpp(775): warning: calling a constexpr __host__ function("operator==") from a __host__ __device__ function("operator()") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.
```
That code doesn't look right.  I see it using TeamPolicy, but it's not actually parallel inside.  We don't have a batched QR yet, but maybe that's the next thing to implement.

**Comment by csiefer2** [comment]
So, w.r.t. code bloat, we have one of two options:
1) Checkin #4496 and downgrade the Tpetra_INST_COMPLEX_DOUBLE && Teuchos_ENABLE_COMPLEX case to a warning.

2) Apply #4496 as an application-specific patch to Trilinos and not let it loose on the broader Trilinos.

**Comment by mhoemmen** [comment]
Third option would be: Find out whatever it is in Thyra and/or Stratimikos that wants to do ETI for complex numbers with Tpetra, and shut it off if Tpetra shuts off complex.

**Comment by bartlettroscoe** [comment]
> Third option would be: Find out whatever it is in Thyra and/or Stratimikos that wants to do ETI for complex numbers with Tpetra, and shut it off if Tpetra shuts off complex.

Yes, that could work and may not be that hard to do.

**Comment by csiefer2** [comment]
@rhoope has graciously volunteered to comment on this

**Comment by cgcgcg** [comment]
Looks like Thyra checks `IF (Trilinos_ENABLE_COMPLEX_DOUBLE  AND  Teuchos_ENABLE_COMPLEX)` to enable complex, so only setting one of them will disable complex Thyra.

**Comment by csiefer2** [comment]
And Stratimikos doesn't do complex at all.

**Comment by csiefer2** [comment]
Moving discussion of potential solution to #4623
