### ISSUE TITLE
MueLu: Remove Build Warnings

### ISSUE THREAD

**Issue by ZUUL42** [trilinos/Trilinos#4513]
@trilinos/muelu 

## Expectations

MueLu builds should not emit any warnings that will be promoted to errors once Werror is set in the GCC 7.2.0 automated build.
## Current Behavior

Currently MueLu has a number of warnings that need to be handled before we can set Werror for all packages.
A recent test build was performed with -Werror set for MueLu. The CDash report can be found [here](https://testing-vm.sandia.gov/cdash/viewBuildError.php?buildid=4624484).
## Motivation and Context

Issue #3178 is working toward turning Warnings as Errors on for all packages.

**Comment by lucbv** [comment]
@ZUUL42 I am working on this and will have a PR for this today.
Any recommendation on how this can be tested locally?
I am just not sure how to get only MueLu to be compiled with `-Werror`.

**Comment by ZUUL42** [comment]
@lucbv, I'm not sure about a local method. I've been using my branches with -Werror set for individual packages to build in Jenkins, MueLu is set on branch ZUUL42:Werror_MueLu. To test it, I can create a build from your branch to that one. Just let me know when your ready, the branch name, and I'll create the build and post a CDash link for it.

**Comment by lucbv** [comment]
@ZUUL42 I have pushed PR #4543 with `AT: WIP` so that you can perform a test build on it.
Let me know how that works and if everything is fine feel free to approve and substitute `AT: AUTOMERGE` for `AT: WIP`

**Comment by ZUUL42** [comment]
Test build created. [CDash results](https://testing-vm.sandia.gov/cdash/index.php?project=Trilinos&display=project&filtercount=3&showfilters=1&filtercombine=and&field1=site&compare1=61&value1=ascic143&field2=buildname&compare2=61&value2=PR-UNKNOWN-test-Trilinos_pullrequest_gcc_7.2.0-647&field3=buildstamp&compare3=61&value3=20190304-2311-Pull%20Request) as it builds.
I'll keep an eye on it and I'll swap out the tags when it completes successfully.
Thanks

**Comment by ZUUL42** [comment]
@lucbv, Looks like there was only one last issue.

**Comment by lucbv** [comment]
@ZUUL42 I was able to reproduce your build after some cmake experimentation and using the proper modules from cmake/std/sems. I think the last commit should fix the remaining error.

**Comment by ZUUL42** [comment]
The build looks good now, but it appears some of the tests are failing.
https://testing-vm.sandia.gov/cdash/viewTest.php?onlyfailed&buildid=4659819

**Comment by lucbv** [comment]
@ZUUL42 yep, I made some changes in the BlackBox that would trigger this, I will now work on fixing this test. This should not be a big complication.
I will push another commit today after running all the tests. Let us hope we can push this today!

**Comment by lucbv** [comment]
@ZUUL42, new commit, if you want to test it that would be great, I have run the tests and they are passing in MueLu, there are no new warnings so it seems fine.

**Comment by ZUUL42** [comment]
One build kicked off just to be sure.
CDash results are coming together [here](https://testing-vm.sandia.gov/cdash/index.php?project=Trilinos&display=project&filtercount=3&showfilters=1&filtercombine=and&field1=site&compare1=61&value1=ascic143&field2=buildname&compare2=61&value2=PR-UNKNOWN-test-Trilinos_pullrequest_gcc_7.2.0-674&field3=buildstamp&compare3=61&value3=20190306-1752-Pull%20Request).

**Comment by lucbv** [comment]
@ZUUL42 the PR has been merged so I think that we can close this issue, but feel free to reopen it if we find more warnings being introduced.
