### ISSUE TITLE
Allow enable of TpetraTSQR to support SPARC

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#4526]
CC: @mhoemmen, @fryeguy52, @kddevin (Trilinos Data Services Product Lead), @trilinos/tpetra 

The SPARC team has requested the enable of the TpetraTSQR subpackage to usage in SPARC.  Currently the ATDM Trilinos configuration explicitly disables TpetraTSQR by default (because it was not being usesd by SPARC or EMPIRE).

But note that TpetraTSQR is enabled by default in the Trilinos PR builds, for example, as shown in the [GCC 4.8.4 build](https://testing.sandia.gov/cdash-dev-view/viewConfigure.php?buildid=4633913) and [CUDA 9.2 build](https://testing.sandia.gov/cdash-dev-view/viewConfigure.php?buildid=4633967) which showed:

```
Final set of enabled SE packages:  ... TpetraTSQR ... 137
```

Therefore, it should be safe to allow the enable of TpetraTSQR in the ATDM Trilinos builds.

**Comment by mhoemmen** [comment]
I sure would like this to be tested by default.

**Comment by bartlettroscoe** [comment]
@mhoemmen , as i noted above, TpetraTSQR is tested in PR builds.  It is just that we disabled every package and subpackage not being used by the ATMD Apps in the ATDM builds.  Building software you are not using increases overhead and risk.  If that does not make sense let's talk.

But since SPARC needs this we will enable it going forward.  As lomg as you can commit to address issues quickly, this should be no problem.

**Comment by mhoemmen** [comment]
@bartlettroscoe That's fine -- thanks!  I have support for fixing TSQR issues.

**Comment by bartlettroscoe** [comment]
FYI: PR #4548 will allow the enable of `TpetraTSQR` once it is merged.

**Comment by bartlettroscoe** [comment]
FYI: With the merge of PR #4548, `TpetraTSQR` is now enabled and hopefully will get installed along with the rest of Trilinos for SPARc to use starting tomorrow 3/6/2019.

I will put this Issue in review and watch for the impact of enabling `TpetraTSQR` and get feedback from the SPARC developers trying to use it.

**Comment by bartlettroscoe** [comment]
A shown from [this query](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-&field2=testname&compare2=65&value2=TpetraTSQR) 230 tests starting with the name "TpetraTSQR_" have showed up so far today in the ATDM Trilinos builds (about 16 tests per build) and they all passed (or are "not run" due to "RDC" build errors not related to Tpetra really).

Closing as complete.
