### ISSUE TITLE
Send out summary email of failing Trilinos Nightly builds and tests at end of each testing day

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#453]
**CC:** @trilinos/framework

**Related to:** #380

**Description:**

At a meeting last week between Jim W. (@jwillenbring), Brent P. (@bmpersc), Erik S. and myself (@bartlettroscoe), Erik mentioned that one of the internal projects had/has a process where they send out a summary email at the end of each testing day that summarizes the failing tests.  This email is seen by every developer on the project, the project lead, and the manager.  If these tests are allowed to fail day after day, then the project lead (and then the managers) will step in and provide motivation and encouragement for the development team to help address the issues.

With the current CDash setup that is used by Trilinos, a targeted email goes out for every configure, build, or test failure for a package as soon as the results are uploaded and processed by the CDash.  This email is targeted to the email list that is attached to a given Trilinos package.  This gives that package team a heads up about the failure as soon as it is known.  While this is good because it alerts the targeted people as soon as possible, one can't see the fully set of failures at the end of a testing day without going directly to CDash and looking.

This Story is to implement a process where a single email would be send out at the end of each testing day (e.g. at 1 am after the last testing day ended at 12 pm) to all of the Trilinos developers, project leads, and responsible managers with the full list of failing tests for the Nightly Trilinos builds.  As described for the other internal SNL project described above, having this feature would help to elevate the importance of keeping the Nightly builds clean and therefore would support beefing up the testing to promote from the 'develop' branch to the 'master' branch.

There are several ways to implement this:

1) Add this as an official feature to CDash and pay Kitware to add it.

2) Implement this as a python script that reads from CDash using the new CDash API.

In my opinion, it would be pretty easy to implement option-2 above given the new CDash API that returns a JSON file for any CDash PHP page.  This would be very similar to the script `send_kanban_wip_reminder_emails.py` which I (Ross) wrote for CASL PHI that queries the Trac DB and then creates a customized HTML-formatted email with a nice formatted table.  My guess is that writing a script like this could be done in about 4 hours, including some unit tests to define and protect this functionality.  You would then set up a cron job to run this script at the same time at the end of each testing day.

**Comment by bartlettroscoe** [comment]
We would implement in a Python script querying the new CDash API and turn of the CDash notification emails for Nightly builds.

But this really should be a CDash feature.  We can ask Kitware to add this in our current contract work with them.

**Comment by bartlettroscoe** [comment]
This needs to be higher priority.  We are never going to get people to pay attention to the CI build when they are flooded with nightly CDash failures.

**Comment by jhux2** [comment]
In the Trilinos Leaders meeting, there was a concern that a digest might arrive late (e.g., 24 hours after a bad commit), thus delaying fixes.  What about having individual emails sent if they are from the CI build.  Everything else gets digested.

**Comment by bartlettroscoe** [comment]
> In the Trilinos Leaders meeting, there was a concern that a digest might arrive late (e.g., 24 hours after a bad commit), thus delaying fixes. What about having individual emails sent if they are from the CI build, while everything else gets digested?

This is consistent with what I suggested at the Trilinos Leaders Meeting today which I list again below ...

Short-term:
* Turn off individual CDash emails for Nightly failures for now until a summary/digest email can be implemented and deployed
* Keep sending out CDash emails for CI build and focus on keeping CI build clean for a period of time

Intermediate-term:
* Get Kitware to implement more targeted and customized CDash email notification schemes (see [this CDash backlog item](https://docs.google.com/document/d/1TLHRp8eTNKw7udOhwIxrOYShXQUbxAzsXeOq5cwWnKM/edit#bookmark=id.vzxu6mcftmqo)) (or do a poor-man’s summary email based on CDash API).

I would suggest that we create a Google Doc were we collaborate on the requirements for the CDash notification scheme we want.  Then we can bring Kitware in and work with them to get CDash to support what we want.

But we might need to wait until Trilinos works out a more rigorous develop, test and deployment plan (you can't do any of these in isolation).

**Comment by jwillenbring** [comment]
Another possibility would be to create another track, perhaps promotional or clean, and send emails from that track, and only elevate builds from nightly to the new track when they are 100% clean.

**Comment by jhux2** [comment]
> This is consistent with what I suggested at the Trilinos Leaders Meeting today which I list again below ...
> Short-term:
>     Turn off individual CDash emails for Nightly failures for now until a summary/digest email can be implemented and deployed
>     Keep sending out CDash emails for CI build and focus on keeping CI build clean for a period of time

I would actually prefer to continue to get emails (even individual ones), since the timeframe for getting a digest is unclear (at least to me).

**Comment by bartlettroscoe** [comment]
> Another possibility would be to create another track, perhaps promotional or clean, and send emails from that track, and only elevate builds from nightly to the new track when they are 100% clean.

Sounds logical me.  How about we call this "Clean Nightly" to be clear what this is?

> I would actually prefer to continue to get emails (even individual ones), since the timeframe for getting a digest is unclear (at least to me).

@jhux2, if you and the @trilinos/muelu team members are committed to keeping your MueLu builds 100% clean on a timely schedule, then would you be okay with moving them into a new "Clean Nightly" track and leaving on CDash emails?

**Comment by bartlettroscoe** [comment]
FYI: Once we can write the Python script implementing #2933 for the ATDM Trilinos bilds, then it would be easy to use this script to keep up with these other various nightly builds of Trilinos.

**Comment by bartlettroscoe** [comment]
FYI: We are new actively working on a Python summary script in #2933.  We should have something soon.
