### ISSUE TITLE
MueLu and non-int LO type

### ISSUE THREAD

**Issue by cihanuq** [trilinos/Trilinos#454]
I managed to build the Tpetra stack with LO=long but MueLu required a few changes for this to work. These changes are all simple static_cast's (and similar tweaks), nothing major.

I thought it would be good to incorporate them into the code base. Happy to share a patch if required.

**Comment by jwillenbring** [comment]
CC: @trilinos/muelu

**Comment by tawiesn** [comment]
@cihanuq Thanks for working on this. Please feel free to send the patch to us or create a pull request.

**Comment by mhoemmen** [comment]
This probably won't work with ETI ON btw.  We'll have to add some CMake options to Tpetra and downstream packages for that.  Anyway, thanks for working on this! :-)

**Comment by cihanuq** [comment]
@mhoemmen I have actually patched Trilinos to allow LO=long and GO=long as well and reported on the mailing list (https://trilinos.org/pipermail/trilinos-users/2016-June/005571.html) but there was no reply so I wasn't sure Trilinos folks would be interested. I'll prepare separate patches and send in.

@tawiesn Great, will do!

**Comment by mhoemmen** [comment]
> @mhoemmen I have actually patched Trilinos to allow LO=long and GO=long as well and reported on the mailing list (https://trilinos.org/pipermail/trilinos-users/2016-June/005571.html) but there was no reply so I wasn't sure Trilinos folks would be interested. I'll prepare separate patches and send in.

I would be interested in seeing your patches.  Thanks!

**Comment by jhux2** [comment]
Closing as won't fix.
