### ISSUE TITLE
Is it possible to enable Scalar=float in Tpetra but not downstream (e.g., in MueLu)?

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#4540]
@trilinos/tpetra @trilinos/muelu 

I'm asking on behalf of @vbrunini .

**Comment by lucbv** [comment]
@mhoemmen, MueLu does not `float` for some reason?

**Comment by jhux2** [comment]
@mhoemmen So `-DTpetra_INST_INT_FLOAT:BOOL=ON` but disabled in MueLu?

**Comment by jhux2** [comment]
> @mhoemmen So `-DTpetra_INST_INT_FLOAT:BOOL=ON` but disabled in MueLu?

Scratch that.  `-DTpetra_INST_FLOAT:BOOL=ON`.

**Comment by mhoemmen** [comment]
@lucbv Victor's question, is whether it's possible to enable `Scalar=float` in Tpetra but not downstream.  He wants that whether or not MueLu works with `Scalar=float`.  It's just a question; the answer could be "no" ;-) .

**Comment by jhux2** [comment]
I'm testing this right now:
```
  -DTeuchos_ENABLE_FLOAT:BOOL=ON
  -DTpetra_INST_FLOAT:BOOL=ON
  -DMueLu_INST_FLOAT_INT_INT:BOOL=OFF
```

**Comment by mhoemmen** [comment]
@jhux2 Best practice would be to use `Trilinos_ENABLE_FLOAT` in place of both `Tpetra_INST_FLOAT` and `Teuchos_ENABLE_FLOAT`.

**Comment by jhux2** [comment]
@mhoemmen So the short answer seems to be "no", due to some MueLu test link failures.  I used this to configure:
```
  -DTrilinos_ENABLE_FLOAT:BOOL=ON
  -DTrilinos_ENABLE_TESTS:BOOL=OFF
  -DTrilinos_ENABLE_MueLu:BOOL=ON
  -DMueLu_ENABLE_TESTS:BOOL=ON
  -DMueLu_INST_FLOAT_INT_INT:BOOL=OFF
```

How important is this to @vbrunini?

**Comment by vbrunini** [comment]
It would be nice to have but not essential. My motivation was that we have one library which uses Tpetra float objects, but not muelu or ifpack2, however we do use muelu and ifpack2 with double so I'd be able to save a bit of build time by skipping float for those. I figured I'd ask if it was already supported, but if it doesn't just work I'm betting that the small reduction in build time for this somewhat unusual use case is not worth you guys needing to support another combination of configure-time options.

**Comment by mhoemmen** [comment]
@jhux2 Thanks for checking!

**Comment by lucbv** [comment]
@vbrunini @jhux2 @mhoemmen should this issue be closed now that we know the answer?

**Comment by mhoemmen** [comment]
Thanks @lucbv for answering this question!  I filed a new issue (https://github.com/trilinos/Trilinos/issues/5465) for the feature request.
