### ISSUE TITLE
New STKUnit test failing in ATDM CUDA PT build on white

### ISSUE THREAD

**Issue by fryeguy52** [trilinos/Trilinos#4551]
CC: @trilinos/stk, @kddevin (Trilinos Data Services Product Lead), @bartlettroscoe, @fryeguy52 
 
## Next Action Status
<status-and-or-first-action>
 
## Description
 
As shown in [this query](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercombine=and&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-release-debug-pt&field2=testname&compare2=61&value2=STKUnit_tests_stk_ngp_test_utest_MPI_4&field3=site&compare3=61&value3=white&field4=buildstarttime&compare4=84&value4=2019-03-05T00%3A00%3A00&field5=buildstarttime&compare5=83&value5=2019-02-03T00%3A00%3A00) the test:
* STKUnit_tests_stk_ngp_test_utest_MPI_4

is failing in the builds:
* Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-release-debug-pt

[Test Output on CDash](https://testing.sandia.gov/cdash/testDetails.php?test=69483834&build=4654832)

This looks like a new test that was added on 2019-02-22 and has been failing since

```
terminate called after throwing an instance of 'std::runtime_error'
  what():  cudaDeviceSynchronize() error( cudaErrorIllegalAddress): an illegal memory access was encountered /home/jenkins/ride/workspace/Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-release-debug-pt/SRC_AND_BUILD/Trilinos/packages/kokkos/core/src/Cuda/Kokkos_Cuda_Instance.cpp:120
```

## Current Status on CDash

[The current status and recent history of this test](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&date=2019-03-06&filtercombine=and&filtercombine=and&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-release-debug-pt&field2=testname&compare2=61&value2=STKUnit_tests_stk_ngp_test_utest_MPI_4&field3=site&compare3=61&value3=ride&field4=buildstarttime&compare4=84&value4=today&field5=buildstarttime&compare5=83&value5=14%20days%20ago)

## Steps to Reproduce

One should be able to reproduce this failure on ride or white as described in:
* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md

More specifically, the commands given for ride or white are provided at:
* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#ridewhite

The exact commands to reproduce this issue should be:
```
$ cd <some_build_dir>/
$ source $TRILINOS_DIR/cmake/std/atdm/load-env.sh Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-release-debug-pt
$ cmake \
 -GNinja \
 -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
 -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_STK=ON \
 $TRILINOS_DIR
$ make NP=16
$ bsub -x -Is -q rhel7F -n 16 ctest -j16
```

**Comment by alanw0** [comment]
We believe we have a fix for the failing stk unit test, we will try to get another stk update into trilinos in the next couple days.

**Comment by alanw0** [comment]
I believe this was fixed.

**Comment by bartlettroscoe** [comment]
It is not fixed:

* https://testing-dev.sandia.gov/cdash/viewTest.php?onlyfailed&buildid=4756558

**Comment by fryeguy52** [comment]
output from failed test:
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  cudaDeviceSynchronize() error( cudaErrorIllegalAddress): an illegal memory access was encountered /home/jenkins/ride/workspace/Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-release-debug-pt/SRC_AND_BUILD/Trilinos/packages/kokkos/core/src/Cuda/Kokkos_Cuda_Instance.cpp:120
```

**Comment by bartlettroscoe** [comment]
Defects with Primary tested code not currently used (or being tested) by ATDM is not really an ATDM issue so I am removing the "client: ATDM" label to get this off our list of active issues.
