### ISSUE TITLE
zoltan2 ordering:  allow different return types (lno_t vs gno_t) for local vs global ordering

### ISSUE THREAD

**Issue by kddevin** [trilinos/Trilinos#456]
In Zoltan2's OrderingSolution, getSeparatorRangeView and getSeparatorTreeView return lno_t_.  But in test orderingScotch.cpp, the pointers to which they are assigned are gno_t_.  Which is correct?

Errors occur when building with lno_t != gno_t (e.g., with -DTEST_STK_DATA_TYPES).

@trilinos/zoltan2

**Comment by egboman** [comment]
Not sure, will look at this in July.

**Comment by egboman** [comment]
This is a tricky question and also applies to other methods in OrderingSolution, such as getPermutationView. For consistency, they should all use the same data type. Intuitive, local ordering should use lno_t while global ordering should use gno_t (global is not yet implemented). However, Scotch always uses Scotch_Num so we had decided in March 2016 to switch from lno_t to gno_t everywhere. Then this happened:

commit 8aabd1bf59b59543fae70a07a454b565ee922f74
Author: bddavid <davidson@txcorp.com>
Date:   Thu Mar 10 13:04:46 2016 -0700

    Changed all lno_t to gno_t.

commit d832494f659bebc6731762859486424bb6e1b8a7
Author: K. Devine <kddevin@sandia.gov>
Date:   Fri Mar 11 11:55:53 2016 -0700

    Revert "Changed all lno_t to gno_t."
    
    This reverts commit 8aabd1bf59b59543fae70a07a454b565ee922f74.

The commit was reverted because Ifpack2 tests started to fail, expecting a local permutation of type lno_t.

We need revisit this topic again...

**Comment by kddevin** [comment]
Here's what we decided on July 21, as I understand it.  Feel free to comment and correct.

The OrderingProblem will have two pointers to OrderingSolutions -- one for a LocalOrderingSolution and one for a GlobalOrderingSolution.  (Currently it has only one OrderingSolution.)  

The parameters passed by a user will determine whether the OrderingProblem will compute a local or global ordering.  If a local ordering is computed, it is stored in the LocalOrderingSolution.  If a global ordering is computed, it is stored in the GlobalOrdering Solution.  The non-requested solution will remain a pointer to NULL.

The LocalOrderingSolution will be templated on lno_t, and its member functions will return lno_t.  The GlobalOrderingSolution will be templated on gno_t, and its member functions will return gno_t.

The OrderingProblem will need two accessors to get the solution:
getLocalOrderingSolution()
getGlobalOrderingSolution()
These methods will return a pointer to an OrderingSolution templated on the appropriate type (lno_t or gno_t, respectively).
These methods will deprecate getOrderingSolution().
If the corresponding ordering solution does not exist, these methods will throw an error.
We expect users to know whether they requested local or global ordering, and to call the appropriate accessor method.

An alternative we discussed was to have separate LocalOrderingProblem and GlobalOrderingProblem.  Since we currently provide only local ordering, we could simply change the name of OrderingProblem to LocalOrderingProblem, and some day in the future, create GlobalOrderingProblem.  But we do not have analogous Local/Global PartitioningProblem.  And much code might be duplicated between local and global versions of problems.  So we decided on the design described in detail above.

**Comment by egboman** [comment]
The outline above is a good start but I ran into a few more issues (discussed at 9/15 meeting):

1) TPL_Traits is needed to convert arrays of different types when calling TPLs like Scotch.
2) The Zoltan2::Algorithm base class currently has a method order() but it probably needs both localOrder() and globalOrder() as they need different template arguments.
3) The ordering algorithm classes need to be revisited. One option is to have different classes for local and global ordering but we think it's better to have just one AlgScotch or AlgRCM (as examples) and then each class can support either localOrder or globalOrder or both.
4) Scotch actually has different interfaces for local (serial) and global (distributed) ordering. For now, it is sufficient to support only local/serial.

This will have to wait  - help wanted.

**Comment by kddevin** [comment]
@egboman  I think this issue is fixed with the PRs above.  I will close; please reopen as needed.
