### ISSUE TITLE
Long file names in KokkosKernels have broken git clone of Trilinos on Windows

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#4571]
CC: @trilinos/framework, @trilinos/kokkos-kernels 

## Description

It appears that the Trilinos git repo has gotten into a state where it can't even be cloned on Windows systems with git.

The CASL PHI INF lead @lefebvrera reported the following error when trying to clone the current Trilinos git repo just a short time ago:

```
G:\raq\scale_dev\dev>git clone https://github.com/trilinos/Trilinos.git Trilinos
Cloning into 'Trilinos'...
remote: Enumerating objects: 47, done.
remote: Counting objects: 100% (47/47), done.
remote: Compressing objects: 100% (40/40), done.
remote: Total 957120 (delta 17), reused 14 (delta 7), pack-reused 957073
Receiving objects: 100% (957120/957120), 562.05 MiB | 26.56 MiB/s, done.
Resolving deltas: 100% (771153/771153), done.
error: unable to create file packages/kokkos-kernels/src/impl/generated_specializations_cpp/gauss_seidel_numeric/KokkosSparse_gauss_seidel_numeric_eti_spec_inst_Kokkos_complex_double__size_t_int64_t_LayoutRight_Cuda_CudaHostPinnedSpace_CudaHostPinnedSpace.cpp: Filename too long
error: unable to create file packages/kokkos-kernels/src/impl/generated_specializations_cpp/gauss_seidel_symbolic/KokkosSparse_gauss_seidel_symbolic_eti_spec_inst_Kokkos_complex_double__size_t_int64_t_LayoutLeft_Cuda_CudaHostPinnedSpace_CudaHostPinnedSpace.cpp: Filename too long
error: unable to create file packages/kokkos-kernels/src/impl/generated_specializations_cpp/gauss_seidel_symbolic/KokkosSparse_gauss_seidel_symbolic_eti_spec_inst_Kokkos_complex_double__size_t_int64_t_LayoutRight_Cuda_CudaHostPinnedSpace_CudaHostPinnedSpace.cpp: Filename too long
error: unable to create file packages/kokkos-kernels/src/impl/generated_specializations_cpp/gauss_seidel_symbolic/KokkosSparse_gauss_seidel_symbolic_eti_spec_inst_Kokkos_complex_float__size_t_int64_t_LayoutLeft_Cuda_CudaHostPinnedSpace_CudaHostPinnedSpace.cpp: Filename too long
error: unable to create file packages/kokkos-kernels/src/impl/generated_specializations_cpp/gauss_seidel_symbolic/KokkosSparse_gauss_seidel_symbolic_eti_spec_inst_Kokkos_complex_float__size_t_int64_t_LayoutRight_Cuda_CudaHostPinnedSpace_CudaHostPinnedSpace.cpp: Filename too long
Checking out files: 100% (56578/56578), done.
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'
```

**Comment by ZUUL42** [comment]
I ran into that last week as well on my new laptop.
I'm assuming those are generated, but that's an absurd filename at 147 characters. The path to it only leaves 28 characters to be used for the path to the repo. Anything inside your Windows user Documents directory is 27 characters to start with. "C:\Users\usernam\Documents\"

I worked around it by putting the repo as close to C: as I could. "C:\GitHub\Trilinos\" worked. The path came out to 251 characters, just under the 260 Windows path limit.
The other work around is modifying the group policy for "Enable Win32 long paths". That setting can be found in gpedit.msc under Local Computer Policy > Computer Configuration > Administrative Templates > System > Filesystem.
But ya, the best method might be to change the filename generation method.

**Comment by bartlettroscoe** [comment]
CC: @mbairdphys

**Comment by bartlettroscoe** [comment]
If these are generated file names, one option is to use a hash algorithm to compress them to make them shorter.  We recently had to do this with some filenames for the Python tool we are working on in #2933.  

@srajama1, can the KokkosKernels developers consider using some hash algorithm to some other compression method to shorten these file names?  My guess is that this is one reason we are seeing CMake reverting to using `*.rsp` response files when creating the library `kokkoskernels`.

**Comment by bartlettroscoe** [comment]
FYI: I created the issue:

* https://github.com/kokkos/kokkos-kernels/issues/395

to get this on the KokkosKernels developers radar.

**Comment by akhilPotla97** [comment]
I have a Ubuntu 16.04 machine, same issue.

**Comment by srajama1** [comment]
Why would this be a problem in Ubuntu ? Is there maximum character limitation on Ubuntu as well ? I thought this was a Windows only problem.

**Comment by jmgate** [comment]
Filesystem dependent, I think.  This should tell you what's allowable.
```bash
getconf NAME_MAX /
getconf PATH_MAX /
```
