### ISSUE TITLE
Teko: Teko_testdriver_tpetra_MPI_[14] test fails for me in an OpenMP build

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#458]
...
646: Test "tStridedTpetraOperator" completed ... PASSED (5)
646: Running test "tBlockedTpetraOperator"
646:    "vector_constr" ... PASSED
646:    "reorder(flat reorder)" ... PASSED
646:    "reorder(composite reorder = 1)" ... PASSED
646:    "reorder(composite reorder = 2)" ... PASSED
646: Test "tBlockedTpetraOperator" completed ... PASSED (4)
646:
646: Tests Passed: 91, Tests Failed: 0
646: (Incidently, you want no failures)
646: terminate called after throwing an instance of 'std::runtime_error'
646:   what():  Kokkos::OpenMP parallel_for ERROR: not initialized
646: Traceback functionality not available

**Comment by eric-c-cyr** [comment]
I can fix the issue in the custom unit test harness. However, there are others with regard to the Teuchos unit test framework. What is the right way to initialize Kokkos using the unit test harness? In panzer I cheat and use the Phalanx unit test harness which is correctly setup. 

Also this is probably related to #22, though I've never been able to replicate this.

**Comment by mhoemmen** [comment]
This error text only occurs in kokkos/core/src/OpenMP/Kokkos_OpenMPexec.cpp, line 112, in the `verify_initialized` function.  This gets called in `Kokkos::OpenMP::finalize`.

Is Teko using Kokkos::OpenMP there with Tpetra, or Kokkos::Serial?  Kokkos::initialize would have initialized Kokkos::OpenMP in my build.  (Since I enabled OpenMP and CUDA is OFF, Kokkos uses Kokkos::OpenMP as the default execution space.)

**Comment by ndellingwood** [comment]
If you place braces { } around everything between Kokkos::initialize() and Kokkos::finalize() in the test this may fix the issue.

**Comment by eric-c-cyr** [comment]
Yes...the issue is that initialize/finalize is called multiple times within the unit tests. In each unit test we have something like TEUCHOS...UNIT...(....) {Kokkos::initialize(); ... Kokkos::finalize(); } There are multiple of these calls within a given executable. This leads to bad things.

**Comment by eric-c-cyr** [comment]
@ndellingwood Did that in the custom test. That didn't quite fix things because there was some static data being cleaned up after the end of the call. I had to add a "clean" call, but that wasn't so difficult.

**Comment by mhoemmen** [comment]
> Yes...the issue is that initialize/finalize is called multiple times within the unit tests. In each unit test we have something like TEUCHOS...UNIT...(....) {Kokkos::initialize(); ... Kokkos::finalize(); } There are multiple of these calls within a given executable. This leads to bad things.

It might make sense for Teuchos' test executable to provide hooks for inserting custom initialization and finalization, but until then, I would suggest using a custom test executable.  This is what I do if I need to call Kokkos::initialize explicitly in a test.

btw, Teuchos::GlobalMPISession captures the command-line arguments if Kokkos is enabled.  You may use this feature to initialize Kokkos correctly (passing along the command-line arguments, so you can do things like setting the number of threads or the GPU device ID).

**Comment by eric-c-cyr** [comment]
So if I call Teuchos::GlobalMPISession there is no need to call Kokkos::initialize/finalize?

**Comment by mhoemmen** [comment]
> So if I call Teuchos::GlobalMPISession there is no need to call Kokkos::initialize/finalize?

No.  It doesn't try to initialize or finalize Kokkos for you, because it doesn't know whether you need Kokkos.  It just collects the test's command-line arguments, so you can feed them into Kokkos if you want.
