### ISSUE TITLE
Typo error in commit #4388 

### ISSUE THREAD

**Issue by kliegeois** [trilinos/Trilinos#4584]
There is a typo error in commit #4388 that prevents from compiling packages/ifpack2/src/Ifpack2_BlockTriDiContainer_impl.hpp if __KOKKOSBATCHED_INTEL_MKL_COMPACT_BATCHED__ is defined. 

Lines 2035-2039:
```
#if defined(__KOKKOSBATCHED_INTEL_MKL_COMPACT_BATCHED__) 
      typedef KokkosBatched::Experimental::Algo::Level3::CompactMKL algo_type;
#else
      typedef KokkosBatched::Experimental::Algo::Level3::Blocked multi_vector_algo_type;
#endif
```
should be replaced by
```
#if defined(__KOKKOSBATCHED_INTEL_MKL_COMPACT_BATCHED__) 
      typedef KokkosBatched::Experimental::Algo::Level3::CompactMKL multi_vector_algo_type;
#else
      typedef KokkosBatched::Experimental::Algo::Level3::Blocked multi_vector_algo_type;
#endif
```

@trilinos/ifpack2 @kyungjoo-kim

**Comment by kyungjoo-kim** [comment]
@kliegeois Sorry. I will submit a PR soon.

**Comment by kliegeois** [comment]
@kyungjoo-kim  No problem, thanks!

**Comment by kyungjoo-kim** [comment]
this should be fixed now. you can close this issue after you confirm that the problem is gone.

**Comment by kliegeois** [comment]
Thanks a lot.
I close the issue.
