### ISSUE TITLE
Epetra has no debug-mode macro

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#459]
@tawiesn 
Epetra lacks a debug-mode macro comparable to HAVE_TPETRA_DEBUG or KOKKOS_HAVE_DEBUG.

**Comment by tawiesn** [comment]
@mhoemmen I will add a HAVE_EPETRA_DEBUG macro. I'm going to guard the isSameAs calls in the doImport/doExport calls in Epetra_DistObject.cpp with HAVE_EPETRA_DEBUG. This would make the code more consistent to Tpetra where these checks are guarded by HAVE_TPETRA_DEBUG. For backwards compatibility i think we should set HAVE_EPETRA_DEBUG=On by default to keep the behavior we had so far. One can turn it explicitly off to gain more performance.
