### ISSUE TITLE
MueLu build failures in new ATDM Trilinos sems-rhel7+cuda+complex builds

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#4599]
CC: @trilinos/muelu, @srajama1 (Trilinos Linear Solvers Product Lead), @bartlettroscoe, @fryeguy52

## Next Action Status

<status-and-or-first-action>

## Description

As shown in [this query](https://testing.sandia.gov/cdash-dev-view/index.php?project=Trilinos&date=2019-03-11&filtercount=2&showfilters=1&filtercombine=and&field1=subprojects&compare1=93&value1=MueLu&field2=buildname&compare2=65&value2=Trilinos-atdm-sems-rhel7-cuda-9.2-Volta70-complex-), MueLu has build errors in library code in the new cuda+complex builds:

* `Trilinos-atdm-sems-rhel7-cuda-9.2-Volta70-complex-shared-release-debug`
* `Trilinos-atdm-sems-rhel7-cuda-9.2-Volta70-complex-static-release-debug`

using the 'sems-rhel7' env.

The build errors shown [here](https://testing.sandia.gov/cdash-dev-view/viewBuildError.php?buildid=4695056) and [here](https://testing.sandia.gov/cdash-dev-view/viewBuildError.php?buildid=4695082) show errors building the source files **`ExplicitInstantiation/MueLu_TentativePFactory_kokkos.cpp`** showing errors like:

* `Trilinos-atdm-sems-rhel7-cuda-9.2-Volta70-complex-shared-release-debug/SRC_AND_BUILD/Trilinos/packages/kokkos/core/src/Kokkos_View.hpp(816): error: calling a constexpr __host__ function("std::real<double> ") from a __device__ function("Kokkos::Impl::ParallelFor< ::,  ::Kokkos::RangePolicy<int,  ::Kokkos::Cuda > ,  ::Kokkos::Cuda> ::operator () const") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.`

and **`ExplicitInstantiation/MueLu_TentativePFactory_kokkos.cpp`** showing errors like:

* `Trilinos-atdm-sems-rhel7-cuda-9.2-Volta70-complex-shared-release-debug/SRC_AND_BUILD/Trilinos/packages/kokkos/core/src/Kokkos_View.hpp(971): error: calling a constexpr __host__ function("std::complex<double> ::complex") from a __device__ function("Kokkos::Impl::ParallelFor< ::,  ::Kokkos::RangePolicy<int,  ::Kokkos::Cuda > ,  ::Kokkos::Cuda> ::operator () const") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.`

## Current Status on CDash

The current status of these builds over the last 7 days can be see in [this query](https://testing.sandia.gov/cdash/index.php?project=Trilinos&date=2019-03-11&filtercount=3&showfilters=1&filtercombine=and&field1=subprojects&compare1=93&value1=MueLu&field2=buildname&compare2=65&value2=Trilinos-atdm-sems-rhel7-cuda-9.2-Volta70-complex-&field3=buildstarttime&compare3=83&value3=7%20days%20ago).

## Steps to Reproduce

These builds are from the CEE LAN machine 'ascicgpu14' and someone with access to the CEE LAN should be able to log onto 'ascicgpu15' and reproduce these failures in as described in:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md

More specifically, the commands given for the system `sems-rhel7' are provided at:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#sems-rhel7-environment

The exact commands to reproduce this issue should be:

```
$ cd <some_build_dir>/

$ source $TRILINOS_DIR/cmake/std/atdm/load-env.sh \
    sems-rhel7-cuda-9.2-Volta70-complex-shared-release-debug

$ cmake \
 -GNinja \
 -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
 -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_MueLu=ON \
 $TRILINOS_DIR

$ ninja -j16
```

Since some developers do not have access to the SRN  CEE LAN, it is likely that these build errors can also be produce on other machines that have a CUDA build.  For example, one can likely reproduce these build errors on the SON machine 'white' as described at:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#ridewhite

using the commands:

```
$ cd <some_build_dir>/

$ source $TRILINOS_DIR/cmake/std/atdm/load-env.sh cuda-9.2-complex-release-debug

$ cmake \
 -GNinja \
 -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
 -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_MueLu=ON \
 $TRILINOS_DIR

$ ninja -j16
```

**Comment by bartlettroscoe** [comment]
@trilinos/muelu and @srajama1,

Note that these cuda+complex builds were set up to support Gemma but Gemma does not use MueLu (see [TRIL-255](https://sems-atlassian-son.sandia.gov/jira/browse/TRIL-255?focusedCommentId=26278&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-26278)).  So we could disable MueLu and other packages not used by Gemma in these builds.  However, the ASC IC Sierra code Salinas does use cuda+complex and it was stated at the ATDM PI meeting today that Salinas would like to consider switching from ML over the MueLu and therefore would need MueLu to work with cuda+complex.  Therefore, in the interest of supporting non-ATDM ASC IC customers, we were asked to keep MueLu enabled in theses builds and ask to see if MueLu could be fixed for cuda+complex.

**Comment by lucbv** [comment]
@jhux2 I have looked at this issue a bit. Based on the error message the problem comes from the QR decomposition performed in `TentativePFactory_kokkos`.
One of the functor used in that factory is templated on **13** parameters! I think that this could easily generate since it is hard to control all possible bad interactions there...
I am guessing that a rewrite of this code is not urgent?
Should we try to work around or deactivate that code while we wait for a kokkos-kernel batched QR?

**Comment by mhoemmen** [comment]
@lucbv The issue could be that people are templating functors on the various View types, when really they only would ever vary the device type, scalar type, and a couple layouts.  You can get the same flexibility by expressing what you want at the lowest level (e.g., by templating the functor only on the things that matter), giving the functor a static `run` method that invokes the functor, then having a higher-level free function templated on the View types that just invokes the functor's run function.  This avoids duplicate instantiations for irrelevant variations on View types, and helps avoid type bugs.

**Comment by cgcgcg** [comment]
The functor in question has some other issues as well. We disable the QR in MiniEM on Cuda, since it tries to use too much L0 scratch memory..

**Comment by jhux2** [comment]
> I have looked at this issue a bit. Based on the error message the problem comes from the QR decomposition performed in `TentativePFactory_kokkos`.
> One of the functor used in that factory is templated on **13** parameters! I think that this could easily generate since it is hard to control all possible bad interactions there...
> I am guessing that a rewrite of this code is not urgent?
> Should we try to work around or deactivate that code while we wait for a kokkos-kernel batched QR?

@lucbv That code was never meant to be performant, just a work-around until something like a batched QR was available.  The easiest step would be to drop back to a purely serial code.  This should only impact apps solving systems of PDEs.  For any app solving a scalar problem, one can skip the QR like  @cgcgcg mentioned.

**Comment by jhux2** [comment]
@bartlettroscoe We'll fix this, but in the meantime, please temporarily disable the test where necessary.

**Comment by jhux2** [comment]
> Any plan to fix this soon? If not, we should disable MueLu in these cuda+complex builds since ATDM does not need MueLu cuda+complex.

@bartlettroscoe This is fine with me.

**Comment by bartlettroscoe** [comment]
FYI: I added the "Stalled" keyword to get this off of our main list of issues we are tracking.
