### ISSUE TITLE
Tpetra::RowMatrixTransposer does not sort rows

### ISSUE THREAD

**Issue by ndellingwood** [trilinos/Trilinos#4607]
@trilinos/tpetra @mhoemmen 

The CrsMatrix path of `Tpetra::RowMatrixTransposer::createTransposeLocal` does not sort rows in the `local_matrix_type`, yet it passes the `local_matrix_type` to CrsMatrix's constructor.  The latter assumes that the rows are sorted.  This causes problems downstream.  I have a small reproducer that I need to clean up, but @mhoemmen has a solution in mind.

**Comment by ndellingwood** [comment]
Reproducer cpp code attached, 5x5 symmetric sparse matrix matrix market file, and 5x5 identity matrix - all files have additional .txt suffix since Github doesn't like the other formats. 

[TpetraRowTransTest.cpp.txt](https://github.com/trilinos/Trilinos/files/2959190/TpetraRowTransTest.cpp.txt)

[mtx5sym.mm.txt](https://github.com/trilinos/Trilinos/files/2959191/mtx5sym.mm.txt)

[speye5.mm.txt](https://github.com/trilinos/Trilinos/files/2959193/speye5.mm.txt)

**Comment by ndellingwood** [comment]
Quick summary of the code:

Goal is to check if a matrix is symmetric using existing Tpetra functionality. A nice suggestion from @csiefer2 was to check the Frobenius norm on the matrix A - A^T.

Code overview:
Read input matrix
Create `RowMatrixTransposer`; call its `createTranspose()` routine
Compute and store CrsMatrix for `A^T - A` using `add`
Call `getFrobeniusNorm()` of the resulting matrix

When the input matrix is symmetric, that final result should be 0. But when running on a single node (non-distributed) with more than 1 threads (OpenMP was enabled in this case) the Frobenius norm is nowhere near 0.

**Comment by ndellingwood** [comment]
An interesting thing: If the matrix for `A^T-A` is multiplied by the identity matrix, then the Frobenius norm is checked, the result is 0 as expected. Danny Dunlavey pointed this out.

**Comment by ndellingwood** [comment]
Regarding the unsorted rows from the `CrsMatrix` code path for `Tpetra::RowMatrixTransposer::createTransposeLocal` mentioned above, the verbose `describe()` output for the transpose matrix shows the following unsorted column gids when number of threads > 1:

```
      Proc Rank   Global Row  Num Entries(Index,Value)
              0            0            4 (4, 1)  (3, 1)  (1, 1)  (2, 1) 
              0            1            4 (4, 1)  (1, 1)  (2, 1)  (0, 1) 
              0            2            5 (4, 1)  (3, 1)  (1, 1)  (2, 1)  (0, 1) 
              0            3            4 (4, 1)  (3, 1)  (2, 1)  (0, 1) 
              0            4            5 (4, 1)  (3, 1)  (1, 1)  (2, 1)  (0, 1) 
```

**Comment by ndellingwood** [comment]
Other output that may be of interest from verbose `describe()` call on the `A^T-A` matrix (repeat column gid entries):

```
      Proc Rank   Global Row  Num Entries(Index,Value)
              0            0            7 (1, -1)  (2, -1)  (3, -1)  (4, 0)  (3, 1)  (1, 1)  (2, 1) 
              0            1            7 (0, -1)  (1, -1)  (2, -1)  (4, 0)  (1, 1)  (2, 1)  (0, 1) 
              0            2            9 (0, -1)  (1, -1)  (2, -1)  (3, -1)  (4, 0)  (3, 1)  (1, 1)  (2, 1)  (0, 1) 
              0            3            7 (0, -1)  (2, -1)  (3, -1)  (4, 0)  (3, 1)  (2, 1)  (0, 1) 
              0            4            9 (0, -1)  (1, -1)  (2, -1)  (3, -1)  (4, 0)  (3, 1)  (1, 1)  (2, 1)  (0, 1) 
```

**Comment by ndellingwood** [comment]
Trilinos configuration for the lib that I installed and built the reproducer code against:

```
export INSTALL_LOCATION=${PWD}/install

cmake \
-DCMAKE_C_COMPILER=`which gcc` \
-DCMAKE_CXX_COMPILER=`which g++` \
-DCMAKE_Fortran_COMPILER=`which gfortran` \
-DCMAKE_CXX_FLAGS="-g -Wall -O3 -DNDEBUG" \
-DCMAKE_C_FLAGS="-g -Wall -O3 -DNDEBUG" \
-D CMAKE_INSTALL_PREFIX:PATH="${INSTALL_LOCATION}" \
-D Trilinos_ENABLE_Kokkos:BOOL=ON \
  -D Kokkos_ENABLE_OpenMP:BOOL=ON \
  -D Kokkos_ENABLE_Serial:BOOL=ON \
-D Trilinos_ENABLE_Tpetra:BOOL=ON \
  -D Tpetra_INST_OPENMP:BOOL=ON \
  -D Tpetra_INST_SERIAL:BOOL=ON \
-D Trilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=OFF \
-D Trilinos_ENABLE_OpenMP:BOOL=ON \
-D CMAKE_BUILD_TYPE:STRING="RELEASE" \
-D CMAKE_VERBOSE_MAKEFILE:BOOL=ON \
-D Trilinos_ENABLE_EXAMPLES:BOOL=OFF \
-D Trilinos_ENABLE_TESTS:BOOL=OFF \
-DTPL_ENABLE_BLAS=ON \
-DTPL_ENABLE_LAPACK=ON \
../../
```

**Comment by ndellingwood** [comment]
@mhoemmen I assigned to you since you mentioned an idea for a solution, hope this is okay.

**Comment by mhoemmen** [comment]
@ndellingwood please do; thanks!

**Comment by csiefer2** [comment]
@ndellingwood The muliply sorts rows by default.  There's a service routine that does it.

**Comment by mhoemmen** [comment]
@csiefer2 wrote:
> The multiply sorts rows by default. There's a service routine that does it.

The issue here is that @ndellingwood wants to compute the explicit transpose by itself.  It sounds like we should add a "sort the rows?" flag to RowMatrixTransposer, `true` by default, but have the multiply set it to false.

**Comment by ndellingwood** [comment]
@brian-kelley : Chris suggested I include you on this issue to see if you could look into the results I'm seeing here from the `add` routine. It's not clear to me from the chain of Tpetra calls I'm using where an issue may lie, a reproducer code is posted in the first comment; here is a quick summary, leading to questions about the transpose and add routines in this issue:

Goal - check if a CrsMatrix is symmetric by computing Frobenius norm on (A^T - A)

Issue - The result is non-zero for known symmetric matrices with more than 1 thread with the OpenMP backend (single node, non-distributed)

Mark looked at this a bit with me and had expected the colids should have been sorted after the transpose call, maybe this is part of the issue?
After the call to the add routine to compute A^T-A, the resultant matrix has multiple entries per row - maybe this causes some issue when computing the Frobenius norm after?

**Comment by mhoemmen** [comment]
@ndellingwood I have a fix pending here: https://github.com/trilinos/Trilinos/pull/5519
