### ISSUE TITLE
PR test timeouts preventing PRs from passing

### ISSUE THREAD

**Issue by ndellingwood** [trilinos/Trilinos#4614]
@trilinos/framework

The following test timeouts have resulted in several PRs failing and requiring re-test:

```
PanzerAdaptersSTK_PoissonInterfaceExample_2d_diffsideids_MPI_1
ROL_example_PDE-OPT_0ld_adv-diff-react_example_02_MPI_4
ROL_example_PDE-OPT_navier-stokes_example_01_MPI_4
```

Of immediate consequence is that this is preventing PR #4608 from completing and merging in, which will result in any Cuda PR testing that involves Ifpack2 from passing. 

The tests timing out above, along with #4608 in some cases which is also unable to complete PR testing due to these tests timing out is preventing PR completion of PRs #4609, #4603, #4604, #4601, #4597, ...

**Comment by rppawlo** [comment]
Did something change in the configure for these builds? The last commit to panzer was almost 4 weeks ago.

**Comment by ndellingwood** [comment]
@rppawlo I believe in one of the builds kokkos debugging was recently enabled, which exposed the error in Ifpack2 that #4608 will fix once it makes it through without a timeout. Kokkos debugging will increase the length of runtime, which I'm guessing is impacting the Panzer test. I'm not certain how long the ROL tests have been timing out and if they're correlated with the kokkos debug option or not.

**Comment by jhux2** [comment]
@bartlettroscoe

**Comment by bartlettroscoe** [comment]
The @trilinos/framework team just needs to turn down the parallel test level from 29 to 8 as per https://github.com/trilinos/Trilinos/issues/2464#issuecomment-471221881.  I told @jwillenbring about this over the phone on Monday.

**Comment by kyungjoo-kim** [comment]
@bartlettroscoe Your commit to reduce parallel test level from 29 to 8 is merged about 3 days ago and we still have failed tests owing to timeout.

**Comment by bartlettroscoe** [comment]
@kyungjoo-kim 

> @bartlettroscoe Your commit to reduce parallel test level from 29 to 8 is merged about 3 days ago and we still have failed tests owing to timeout.

What commit?  It is impossible for me to reduce the parallel test level for 29 to 8.  Only the @trilinos/framework team can do that.

**Comment by kyungjoo-kim** [comment]
@bartlettroscoe while I am editing the previous comment, you responded. I mean 
[this commit](https://github.com/trilinos/Trilinos/commit/2a2a65fe132894024d081ea1e9b9273a7da913a0) that disables time out tests. We need to disable more.

**Comment by jhux2** [comment]
Could the kokkos debug option be temporarily removed from the PR test in question until framework has time to deal with this?

**Comment by ndellingwood** [comment]
@trilinos/framework I put in a PR request #4615 that disables the tests mentioned above, based off past PRs referenced from @kyungjoo-kim 's comment above. Can someone review and accept or provide a more preferred/better solution? In either case, do you have control to drain the queue of PRs to test so that PR or your solution can get priority? No PRs will pass until the unit tests causing timeouts are disabled; once that is resolved, PR #4608 will pass (which failed again due to timeout of the same tests, but this PR is needed to allow Cuda PR testing to pass on any other PRs).

**Comment by jhux2** [comment]
@ndellingwood We can at least put "AT: WIP" labels on our PRs, and ask others to do the same for theirs.

**Comment by ndellingwood** [comment]
@jhux2 good point, thanks!

**Comment by jhux2** [comment]
@ndellingwood What about disabling the offending Ifpack2 test?

**Comment by ndellingwood** [comment]
PR #4608 will address that test so I'd rather not disable, hopefully it percolates to the top of the PR testing queue quickly!!

**Comment by dridzal** [comment]
Speaking just for ROL, @trilinos/rol , most of the tests that are currently failing on Cuda pass on old platforms.  This is due to timeouts.  I would say that no new test platforms should be put into circulation as PR platforms until the *existing* tests pass.  The current trend of disabling more and more tests is dangerous.  Do we have a policy about new platform deployment?  Or a policy on modifications to configure options?  If someone changes the configure options, and tests start failing, who needs to respond first?  The package developer?

**Comment by jwillenbring** [comment]
> What commit? It is impossible for me to reduce the parallel test level for 29 to 8. Only the @trilinos/framework team can do that.

We merged a change to the testing infrastructure to lower the parallel level to 9 (we discussed 8-10 on Monday, and I split the difference) late this morning. We will see if that fixes this.

**Comment by ndellingwood** [comment]
PR #4608 merged (with a disabled Panzer test), so #4615 is unnecessary. @rppawlo is going to revise the disabled Panzer test so it is only disabled for the Cuda builds, rather than all builds.

**Comment by ndellingwood** [comment]
Retested PR #4609, LOTS of new Cuda test failures and timeouts in Panzer, plus a couple in ROL and MueLU unrelated to that PR (#4609 makes changes in Amesos2 that are untouched, unused and unrelated to the failing tests). See here for the [test failures](https://testing-vm.sandia.gov/cdash/viewTest.php?onlyfailed&buildid=4716388)
Were there more configuration changes made to the PR testing? If so, do these changes even get properly tested before going in? @trilinos/framework  @jwillenbring @bartlettroscoe 
Adding @rppawlo @trilinos/panzer regarding the Panzer failures,
@dridzal @trilinos/rol regarding the ROL failures,
@jhux2 @trilinos/muelu regarding the MueLU faliures.

**Comment by jhux2** [comment]
I'm seeing similar failures/timeouts in testing of PR #4597.

**Comment by ndellingwood** [comment]
The change in parallel level fixed the test timeouts mentioned in this issue; this also ended up allowing #4608 to merge after some hop-scotch and resolved the issues mentioned in this PR. Issue #4631 supercedes this issue regarding PR testing.
