### ISSUE TITLE
Thyra_TpetraVectorSpace to expose getter for underlying Tpetra object

### ISSUE THREAD

**Issue by bartgol** [trilinos/Trilinos#4616]
@trilinos/tpetra
@trilinos/thyra

## Expectations

I want to be able to extract the underlying Tpetra map from a vector space

## Current Behavior

You can't.

## Motivation and Context

The Tpetra adapter offer the possibility to extract the Tpetra object for Vector, MultiVector, and LinearOp. However, such capability does not exist for VectorSpace. This is unfortunate. For (Multi)Vector, one can survive without this capability (at least on host), since there are methods in parent classes that allow extraction of local data or subviews. However, there is no Thyra equivalent of Global ID and Local ID, so one _needs_ to get the underlying map from Thyra, in order to access that information.

## Possible Solution

Simply add a method like this (copied and adapted from other adapters):

```
  /** \brief Get the embedded non-const Tpetra::Vector. */
  RCP<const Tpetra::Map<LocalOrdinal,GlobalOrdinal,Node> >
  getConstTpetraMap() const;
```

I can set up a quick PR for this, if the proposed addition is deemed reasonable. I can also add a quick check in the tpetra adapters tests.

**Comment by mhoemmen** [comment]
@trilinos/thyra @trilinos/tpetra

**Comment by rppawlo** [comment]
@bartgol Sounds good to me! Thanks for adding this!

**Comment by bartgol** [comment]
Random question: what's the point of telling people to tag the packages when submitting an issue/PR, if they don't work unless you're part of the Trilinos org? Shouldn't people be able to set them regardless of their affiliation, so that the notification reaches the appropriate people?*

* To be clear, I'm always pleased with how quickly the trilinos team responds to issues/PR, I'm not complaining at all. I just wonder what's the point of telling people to tag teams, if the feature doesn't work for common mortals...

**Comment by bartlettroscoe** [comment]
@bartgol said:

> I just wonder what's the point of telling people to tag teams, if the feature doesn't work for common mortals...

See #4621.
