### ISSUE TITLE
Allow Trilinos users to set Labels

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#4621]
@trilinos/framework 

The instructions for creating new GitHub issues at:

* https://github.com/trilinos/Trilinos/wiki/Managing-Trilinos-Project-Issues

and even the GitHub issue template at:

* https://raw.githubusercontent.com/trilinos/Trilinos/master/.github/ISSUE_TEMPLATE.md

tells users to set Issue Labels but it it is reported in https://github.com/trilinos/Trilinos/issues/4616#issuecomment-472939081 that users can't actually set labels.

Is there any reason we can't allow users to set labels on Trilinos GitHub Issues like they are being told to do?

**Comment by mhoemmen** [comment]
I think @bartgol is asking about tagging teams (like `@trilinos/framework` or `@trilinos/tpetra`), not about labels, but that's a related issue.

**Comment by bartlettroscoe** [comment]
@mhoemmen said:

> I think @bartgol is asking about tagging teams (like @trilinos/framework or @trilinos/tpetra), not about labels, but that's a related issue.

That can't be it because that is a free text that you just type in.

**Comment by bartgol** [comment]
Actually it's both. We can't set label, and everytime I do @trilinos/tpetra or something like that, it does not display in bold, which I'm taking it as "sorry, you're not allowed".

**Comment by jhux2** [comment]
Regarding @ mentioning teams, from the following snippet found [here](https://help.github.com/en/articles/about-teams), @ mentions only work if the person doing the mentioning is part of the organization:
```
Organization members can send a notification to an entire team by mentioning the team's name. Organization members can also send a notification to an entire team by requesting a review from that team. Organization members can request reviews from specific teams with read access to the repository where the pull request is opened. 
```

**Comment by bartgol** [comment]
So it appears that the users have no way to either tag the team or apply a label. Is that correct? Seems like a limitation of github. They should allow to customize your labels, so that outsiders can to a first triage of the issue/pr...

**Comment by jwillenbring** [comment]
> @bartlettroscoe See here for repo permissions. It appears that anyone who can apply labels must have at least "write" level permissions, which allows them to do other things like editing/deleting other folks' comments. I don't know about the @ mention part, though.

Yes, this has caused frustrations in other contexts too. I was not aware that @ mentions didn't work for non-organization members though if that is the case.

**Comment by mhoemmen** [comment]
revive
