### ISSUE TITLE
Ifpack2_BlockTriDiContainerUnitAndPerfTests_MPI_4 failing in ATDM cuda builds

### ISSUE THREAD

**Issue by fryeguy52** [trilinos/Trilinos#4622]
CC: @trilinos/ifpack2, @srajama1 (Trilinos Linear Solvers Product Lead), @bartlettroscoe, @fryeguy52 
 
## Description
 
As shown in [this query](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-&field2=testname&compare2=61&value2=Ifpack2_BlockTriDiContainerUnitAndPerfTests_MPI_4&field3=status&compare3=62&value3=Passed&field4=buildstarttime&compare4=84&value4=2019-03-14T00%3A00%3A00&field5=buildstarttime&compare5=83&value5=2019-03-13T00%3A00%3A00) the tests:
* Ifpack2_BlockTriDiContainerUnitAndPerfTests_MPI_4

are failing in the builds:
* Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-release-debug
* Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-rdc-shared-release-debug
* Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-rdc-release-debug 
* Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-debug 
* Trilinos-atdm-waterman-cuda-9.2-release-debug
* Trilinos-atdm-waterman-cuda-9.2-rdc-shared-release-debug
* Trilinos-atdm-waterman-cuda-9.2-rdc-release-debug
* Trilinos-atdm-waterman-cuda-9.2-opt
* Trilinos-atdm-waterman-cuda-9.2-debug
* Trilinos-atdm-sems-rhel7-cuda-9.2-Volta70-complex-static-release-debug
* Trilinos-atdm-sems-rhel7-cuda-9.2-Volta70-complex-shared-release-debug

The new commits that were pulled the day that these failures started are show, for example, here<link to Updates.txt notes file on CDash>.  From looking over that set of commits, it seems likecommits <sha1-a> .... by @<github-id> pulled in by the PR #<pr-id> might be the trigger for these failures.

## Current Status on CDash

[Currently Status on CDash for all ATDM builds](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=4&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-&field2=testname&compare2=61&value2=Ifpack2_BlockTriDiContainerUnitAndPerfTests_MPI_4&field3=buildstarttime&compare3=84&value3=today&field4=buildstarttime&compare4=83&value4=yesterday)

## Steps to Reproduce on waterman

One should be able to reproduce this failure on waterman as described in:
* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md

More specifically, the commands given for waterman are provided at:
* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#waterman

The exact commands to reproduce this issue should be:
```
$ cd <some_build_dir>/
$ source $TRILINOS_DIR/cmake/std/atdm/load-env.sh Trilinos-atdm-waterman-cuda-9.2-debug
$ cmake \
 -GNinja \
 -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
 -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_Ifpack2=ON \
 $TRILINOS_DIR
$ make NP=16
$ bsub -x -Is -n 20 ctest -j20
```

## Steps to Reproduce on white/ride

One should be able to reproduce this failure on ride or white as described in:
* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md

More specifically, the commands given for ride or white are provided at:
* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#ridewhite

The exact commands to reproduce this issue should be:
```
$ cd <some_build_dir>/
$ source $TRILINOS_DIR/cmake/std/atdm/load-env.sh Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-debug
$ cmake \
 -GNinja \
 -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
 -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_Ifpack2=ON \
 $TRILINOS_DIR
$ make NP=16
$ bsub -x -Is -q rhel7F -n 16 ctest -j16
```

**Comment by mhoemmen** [comment]
@kyungjoo-kim

**Comment by kyungjoo-kim** [comment]
@mhoemmen @fryeguy52 This is already addressed in #4608. Tomorrow, this ifpack2 failure will magically disappear.

**Comment by fryeguy52** [comment]
@kyungjoo-kim Great!

**Comment by jhux2** [comment]
> This is already addressed in #4608. Tomorrow, this ifpack2 failure will magically disappear.

:laughing:

**Comment by bartlettroscoe** [comment]
@jhux2, @kyungjoo-kim, @mhoemmen, @trilinos/framework, @jjellio, @srajama1, @ndellingwood, @crtrott 

Why did the Trilinos CUDA PR build not catch this and stop this failing test?  It failed every day in the build `Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-release-debug-pt` shown [here](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=4&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-release-debug-pt&field2=testname&compare2=61&value2=Ifpack2_BlockTriDiContainerUnitAndPerfTests_MPI_4&field3=site&compare3=61&value3=ride&field4=buildstarttime&compare4=83&value4=2019-02-11T00%3A00%3A00) starting 3/12/2018 that should be a 100% match for the Trilinos PR build (see #2464) so why did the Trilinos PR tester not catch this?

The answer is that it looks like it was failing in the Trilinos CUDA PR builds as shown [here](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=5&showfilters=1&filtercombine=and&field1=groupname&compare1=61&value1=Pull%20Request&field2=testname&compare2=61&value2=Ifpack2_BlockTriDiContainerUnitAndPerfTests_MPI_4&field3=buildname&compare3=63&value3=cuda&field4=buildstarttime&compare4=84&value4=2019-03-16&field5=buildstarttime&compare5=83&value5=2019-03-08) with this test starting to fail in the PR #4597 back on 3/11/2018.    How did this happen?

Looking at the commits that were pulled in the build `Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-release-debug-pt` on 3/12/2019 shown [here](https://testing.sandia.gov/cdash/viewNotes.php?buildid=4700279#!#note0) the PR merges pulled that day were just PR #4587 and PR #4592.  Looking at those two PRs (one that changes the test `Ifpack2_BlockTriDiContainerUnitAndPerfTests_MPI_4` and one that updates the CUDA PR build), my guess is that this is an unlucky example of a violation of the [additive test assumption of branches](https://docs.google.com/document/d/1uVQYI2cmNx09fDkHDA136yqDTqayhxqfvjFiuUue7wo/edit#bookmark=id.d1jneh8ubsyn).  From looking at the conversation in #4597, it looks like PR #4587 updated the Ifpack2 test which failed with Kokkos Array bounds checked turn on and PR #4592 fixed the CUDA PR build which turned on Kokkos array bounds checking.

I think what this shows is that a post-push CI build needs to be set up for the CUDA build, like is run for the GCC 4.8.4 build.  This will catch violations of the additive test assumption of branches faster and avoid situations like this and avoid pain and confusion like occurred in #4597.  This is needed to avoid this fundamental weakness of the Trilinos PR tester.

Also, of the CUDA PR build would have been set up correctly form the start, this would have been avoided as well.

**Comment by bartlettroscoe** [comment]
As shown in [this query](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=4&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-release-debug-pt&field2=testname&compare2=61&value2=Ifpack2_BlockTriDiContainerUnitAndPerfTests_MPI_4&field3=site&compare3=61&value3=ride&field4=buildstarttime&compare4=83&value4=2019-02-11T00%3A00%3A00) the test `Ifpack2_BlockTriDiContainerUnitAndPerfTests_MPI_4` is passing today 3/15/2019 in this build so we can close this issue.

**Comment by kyungjoo-kim** [comment]
@bartlettroscoe Just FYI: Previously Cuda PR test is built with RELEASE and it does not check kokkos view bounds. So, my PR and other PRs can pass without a problem in Ifpack2. Sometime ago (last week), the Cuda PR test is built with DEBUG and it checks kokkos view bounds. This causes some timeout issues as reported in #4614. 

Here every developer follows the PR test rule but the PR test is changed **without testing itself** and it just reveals a failure from a code. We can avoid this kind of failures if the Cuda PR test itself is tested when it changes the build configuration.

**Comment by bartlettroscoe** [comment]
@kyungjoo-kim 

> Here every developer follows the PR test rule but the PR test is changed without testing itself and it just reveals a failure from a code. We can avoid this kind of failures if the Cuda PR test itself is tested when it changes the build configuration.

That is not correct.  This change in the CUDA PR build was tested and passed the tests.  See https://github.com/trilinos/Trilinos/pull/4592#issuecomment-471362392

Please give me a call offline and I can explain what I was trying to explain [above](https://github.com/trilinos/Trilinos/issues/4622#issuecomment-473315595) which is that this type of situation can occur because the Trilinos PR tester uses **asynchronous** testing (that was not true of the SST PR tester).  This is a fundamental weakness in **asynchronous CI**.
