### ISSUE TITLE
Belos::MultiVecTraits: Tpetra specialization is slow on GPU, because it creates local MV & thus does extra CUDA allocations

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#4626]
@trilinos/belos @trilinos/tpetra @cgcgcg 

The Tpetra specialization of `Belos::MultiVecTraits` has two methods that need to create temporary "local" MultiVector instances.  This creation does a new DualView allocation each time.  This makes running on the GPU slow, especially for classical Gram-Schmidt in GMRES, or in general whenever doing `X^T * Y` or `X^H * Y` for either X or Y having multiple columns. 

I am working on a fix.  The idea is to maintain a static DualView "pool" that the local MultiVector can view.  One must be careful not to let any DualView instance persist past `Kokkos::finalize`.

**Comment by mhoemmen** [comment]
The Fix-4626 branch on my Trilinos fork has an incomplete fix.  I'm working out some bugs in `makeLocalMultiVector`.

**Comment by cgcgcg** [comment]
@mhoemmen Thank you for working on this!

**Comment by mhoemmen** [comment]
Related kokkos-kernels issue: https://github.com/kokkos/kokkos-kernels/issues/397
