### ISSUE TITLE
MueLu/Ifpack2: don't use Teuchos exception handling in non-error situations

### ISSUE THREAD

**Issue by jhux2** [trilinos/Trilinos#4647]
@eric-c-cyr has requested that MueLu move away from using Teuchos exception handling in non-error situations (e.g., smoother testing).  The rationale is to simplify debugging of downstream code by avoiding (perhaps many) non-error breaks in MueLu.

**Comment by vbrunini** [comment]
Could this request be made Trilinos-wide? In particular I've seen it in Ifpack2, but there may be other packages that do it as well.

**Comment by eric-c-cyr** [comment]
@vbrunini I agree with that. Its quite possible its a combination of Ifpack2 and MueLu that I'm stumbling through.

**Comment by csiefer2** [comment]
Oh please yes.

**Comment by mhoemmen** [comment]
I fixed this in Ifpack2, except for a couple deprecated or very rarely built classes (Ifpack2::Krylov and Ifpack2::SupportGraph).

**Comment by cgcgcg** [comment]
https://github.com/trilinos/Trilinos/pull/7208 took care of smoother construction. At least the MueLu driver runs through without any exceptions being thrown.

**Comment by mhoemmen** [comment]
revive? @jhux2 @csiefer2
