### ISSUE TITLE
TrilinosCouplings scaling/example_Poisson2D_p2_tpetra.cpp failes to build in serial

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#465]
**Next Action Status**

The example scaling/example_Poisson2D_p2_tpetra.cpp  was never intended for non-MPI builds so was marked with "COMM mpi".

**CC:** @trilinos/framework 

**Description:**

I am trying to build all of the ST Trilinos packages in several different build configurations as part of setting up a standard SEMS Dev Env (see #158) and the TrilinosCouplings file:

   examples/scaling/example_Poisson2D_p2_tpetra.cpp

does not build in a serial build of the code.  When you configure and build with:

```
$ cd Trilinos/
$ mkdir BUILD/
$ cd BUILD/
$ cmake \
  -DBUILD_SHARED_LIBS=ON \
  -DCMAKE_BUILD_TYPE=RELEASE \
  -DTrilinos_ENABLE_DEBUG=ON \
  -DTrilinos_ENABLE_TESTS=ON \
  -DTrilinos_ENABLE_TrilinosCouplings=ON \
  ..
$ make
```

you get the build failure:

```
[100%] Building CXX object packages/trilinoscouplings/examples/scaling/CMakeFiles/TrilinosCouplings_Example_Poisson2D_p2_tpetra.dir/example_Poisson2D_p2_tpetra.cpp.o
/home/rabartl/Trilinos.base/Trilinos/packages/trilinoscouplings/examples/scaling/example_Poisson2D_p2_tpetra.cpp: In function ‘int main(int, char**)’:
/home/rabartl/Trilinos.base/Trilinos/packages/trilinoscouplings/examples/scaling/example_Poisson2D_p2_tpetra.cpp:1200:46: error: ‘uCoeff’ was not declared in this scope
     ArrayRCP<const scalar_type> uCoeffData = uCoeff.getData(0);
                                              ^
make[2]: *** [packages/trilinoscouplings/examples/scaling/CMakeFiles/TrilinosCouplings_Example_Poisson2D_p2_tpetra.dir/example_Poisson2D_p2_tpetra.cpp.o] Error 1
make[1]: *** [packages/trilinoscouplings/examples/scaling/CMakeFiles/TrilinosCouplings_Example_Poisson2D_p2_tpetra.dir/all] Error 2
make: *** [all] Error 2
```
Since TrilinosCouplings has not been building in a long time (see #19), I am sure that this error went unnoticed.

**Comment by bartlettroscoe** [comment]
Looking at this a little, there is no way that this example could have built because the variable was protected in:

```
#ifdef HAVE_MPI
  ..l
  multivector_type  uCoeff(solnMap,1);
  ...
#endif
```

@jhux2, it looks like you added this example from looking at:

```
$ git log --name-status -SuCoeff -- packages/trilinoscouplings/examples/scaling/example_Poisson2D_p2_tpetra.cpp

commit dcf1986fd2d4533644cc4edfc9375f6c92cd7e85
Author: Jonathan Hu <jhu@sandia.gov>
Date:   Thu Jun 9 13:15:04 2016 -0700

    TrilinosCouplings: convert Poisson2D p=n to Tpetra
    
    This example now uses Belos and MueLu.

A       packages/trilinoscouplings/examples/scaling/example_Poisson2D_p2_tpetra.cpp
```

I will go ahead and disable this example for a serial build.  If you want this to work for a serial build, then please fix it.  Otherwise, just state that this example is not supposed to work in serial mode and just close this Issue ticket.

**Comment by bartlettroscoe** [comment]
FYI: After disable this test in a serial build, all of TrilinosCouplings builds in a serial build.

I will push the commit that implements this disable soon.

**Comment by jhux2** [comment]
> I will go ahead and disable this example for a serial build. If you want this to work for a serial build, then please fix it. Otherwise, just state that this example is not supposed to work in serial mode and just close this Issue ticket.

Ross,
  Thanks for catching/fixing this -- the example isn't intended for serial.
Jonathan

**Comment by bartlettroscoe** [comment]
> Thanks for catching/fixing this -- the example isn't intended for serial.

Excellent, then we can close this issue!

**Comment by bartlettroscoe** [comment]
I updated the next action status to:

The example scaling/example_Poisson2D_p2_tpetra.cpp was never intended for non-MPI builds so was marked with "COMM mpi".

 and am closing.
