### ISSUE TITLE
STK: STK requires MPI but does not state a required MPI dependency

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#466]
**Next Action Status:**

???

**CC:** @trilinos/stk, @trilinos/framework 

**Description:**

If you configure and try to build STK under Trilinos without MPI (i..e `-DTPL_ENABLE_MPI=OFF`), it fails to build with the build error:

```
In file included from /home/rabartl/Trilinos.base/Trilinos/packages/stk/stk_util/stk_util/parallel/GenerateParallelUniqueIDs.hpp:38:0,
                 from /home/rabartl/Trilinos.base/Trilinos/packages/stk/stk_util/stk_util/parallel/GenerateParallelUniqueIDs.cpp:34:
/home/rabartl/Trilinos.base/Trilinos/packages/stk/stk_util/stk_util/parallel/ParallelVectorConcat.hpp:40:19: fatal error: mpi.h: No such file or directory
 #include "mpi.h"  
                   ^
compilation terminated.
make[2]: *** [packages/stk/stk_util/stk_util/parallel/CMakeFiles/stk_util_parallel.dir/GenerateParallelUniqueIDs.cpp.o] Error 1 
```

The issue is that this STK subpackage does not declare a required dependency on MPI as shown by:

```
$ cd Trilinos/packages/stk/
$ find . -name Dependencies.cmake -exec grep -nH MPI {} \;
./cmake/Dependencies.cmake:22:SET(LIB_OPTIONAL_DEP_TPLS MPI)
```

Either STK needs to be fixed to build without MPI or it needs to declare a required dependency on MPI.

**Comment by bartlettroscoe** [comment]
For now, I will just disable STK for SEMS Dev Env builds (#158) so this does not mess up the serial build for other people as well. 

@bmpersc, I will disable STK for serial SEMS Dev Env builds by default without touching the packages/stk directory tree.

**Comment by bavier** [comment]
This issue was mentioned also in #241

**Comment by bartlettroscoe** [comment]
This got resolved a long time ago.  Closing as complete.
