### ISSUE TITLE
Are there ATDM-compatible SEMS modules for HDF5 and NetCDF on CEE lan?

### ISSUE THREAD

**Issue by jhux2** [trilinos/Trilinos#4662]
I like to build Trilinos on the CEE lan using clang because it's really fast.  I generally load the necessary modules with
```
source ${TRILINOS_DIR}/cmake/std/atdm/load-env.sh cee-rhel6-clang-debug-serial
```
However, I can't find compatible NETCDF or HDF modules, which some packages require.  The listed modules error out when I try to load them.

```
> module load atdm-hdf5/1.8.12/atdm
atdm-hdf5/1.8.12/atdm(34):ERROR:102: Tcl command execution failed: if {[module-info mode switch]} {
  set local_compiler_version $env(SEMS_HDF5_LOCAL_COMPILER_VERSION)
} elseif {[module-info mode remove]} {
  set local_compiler_version $env(SEMS_HDF5_LOCAL_COMPILER_VERSION)
  unsetenv SEMS_HDF5_LOCAL_COMPILER_VERSION
} else {
  set local_compiler_version [semsModuleSupport::getCurrentVersion gcc]
  setenv SEMS_HDF5_LOCAL_COMPILER_VERSION $local_compiler_version
}

> module load atdm-netcdf/4.4.1/atdm
atdm-netcdf/4.4.1/atdm(34):ERROR:102: Tcl command execution failed: if {[module-info mode switch]} {
  set local_compiler_version $env(SEMS_NETCDF_LOCAL_COMPILER_VERSION)
} elseif {[module-info mode remove]} {
  set local_compiler_version $env(SEMS_NETCDF_LOCAL_COMPILER_VERSION)
  unsetenv SEMS_NETCDF_LOCAL_COMPILER_VERSION
} else {
  set local_compiler_version [semsModuleSupport::getCurrentVersion gcc]
  setenv SEMS_NETCDF_LOCAL_COMPILER_VERSION $local_compiler_version
}

```

Is there something wrong in my environment, or some other way of getting the modules to load?

@bartlettroscoe @trilinos/framework

**Comment by bartlettroscoe** [comment]
@jhux2, I think you might need to be in the 'wg-sparc-dev' group to use the 'cee-rhel6' env currently.

NOTE that the 'sems-rhel7' env has a 'clang-3.9.0' compiler that you can use.  We can add that to the 'sems-rhel6' env as well if you are interested.

**Comment by jhux2** [comment]
UPDATE:  I've tried these ATDM Intel and GNU compiler environments, with similar results.  The HDF5 and NetCDF modules won't load with any ATDM compiler configuration, apparently.

```
source ${TRILINOS_DIR}/cmake/std/atdm/load-env.sh cee-rhel6-gnu-7.2.0-debug-serial
source ${TRILINOS_DIR}/cmake/std/atdm/load-env.sh cee-rhel6-gnu-debug-serial
source ${TRILINOS_DIR}/cmake/std/atdm/load-env.sh cee-rhel6-intel-debug-serial
```

**Comment by bartlettroscoe** [comment]
@jhux2, try the 'sems-rhel6' env.

**Comment by jhux2** [comment]
> I think you might need to be in the 'wg-sparc-dev' group to use the 'cee-rhel6' env currently.

Hmm, I can use the cee-rhel6 environment without issues, as long as I don't need HDF5 or NetCDF, so I don't think that's it.  Are you able to load either?

**Comment by jhux2** [comment]
> try the 'sems-rhel6' env.

`source ${TRILINOS_DIR}/cmake/std/atdm/load-env.sh sems-rhel6-gnu-debug-serial` loaded the modules without problems.  Thanks!  I'll see if I can build.

> NOTE that the 'sems-rhel7' env has a 'clang-3.9.0' compiler that you can use. We can add that to the 'sems-rhel6' env as well if you are interested.

I'm able to use the cee-rhel6 env without issues, just not with HDF5 or NetCDF.

**Comment by jhux2** [comment]
I've found a solution.  In order to use clang on the CEE lan (RHEL6), I did `module load sparc-dev`, which provides among other things an installation for NetCDF.  (It's enough to be in `wg-aero-usr`.)

**Comment by bartlettroscoe** [comment]
@jhux2 said:

> 've found a solution. In order to use clang on the CEE lan (RHEL6), I did `module load sparc-dev`, which provides among other things an installation for NetCDF. (It's enough to be in `wg-aero-usr`.)

I am not sure why you needed to load this module when my account does but I will add this to cmake/std/atdm/cee-rhel6/environment.sh so that it will work out of the box for you and others in the future.
