### ISSUE TITLE
Epetra_CrsMatrix::Multiply with locally replicated range map question

### ISSUE THREAD

**Issue by bartgol** [trilinos/Trilinos#4663]
@trilinos/epetra

## Current Behavior

Currently, if the range map is locally replicated, the result of `A.Apply(X,Y)` is not what I expected. In particular, Epetra does a final call `Y.Reduce()`, which ends up giving a Y vector that is numProc times larger than what I expected. Why is Epetra doing this? I.e., why are we reducing the output vector, in case of a locally replicated range map? Isn't the result (before the Reduce() call) already what one most likely wants? The user can always call `Y.Reduce()` if he is interested in that.

## Possible Solution

Assuming my concern is correct, simply remove line 3212 (and the likes in other branches of if statements) in Epetra_CrsMatrix.cpp

**Comment by bartgol** [comment]
I noticed the same thing happens in Tpetra. I guess there's a reason behind this, that I'm completely missing.

**Comment by mhoemmen** [comment]
@trilinos/epetra @trilinos/tpetra 

What is it that you're trying to do here?

The idea of a locally replicated Map is that it represents the distribution of quantities meant to be all-reduced.  For example, iterative solvers like CG or GMRES usually want the results of inner products -- in general, multiplications of the form `X^T * Y` or `X^H * Y` for globally distributed MultiVectors X and Y -- available on all processes in the communicator.  If you ask `MultiVector::multiply` to compute `Z = X^T * Y` for globally distributed X and Y, it wants the result Z to have a locally replicated Map, and it does an all-reduce with `MPI_SUM` over the local results to get the final result.

Sparse matrix-vector multiply `A.apply (X, Y)` is really a generalization of `MultiVector::multiply`.  If you give it locally replicated Y, it will want to do the same thing that `MultiVector::multiply` does.

**Comment by bartgol** [comment]
Well, the fact that you want to do a reduction on the result (like for inner products) is conceptually separated from the fact that the range map is replicated.

My use case is probably not a great example, especially since I was able to work around it with importers. I basically needed to sample a vector (a relatively small sample (<10 entries), regardless of the input vector size), and make the sampled vector replicated across ranks. The fact that the map of the output vector is locally replicated is mandatory. So my first implementation was to make a selection matrix, with the replicated map as row map, stuffing a single 'diagonal' entry in all the rows. At the end of the day, it is the same as an import operation. But potentially can be extended (e.g., each entry of the output vector could be an average of a patch of entries in the input vector).

Ideally, I see the reduction as an orthogonal concept to the multiplication (and how the gids are distributed in the range map). In fact, one can always call `Reduce` manually on the output vector, if the desired behavior is to obtain a reduced result (*); but you can't undo the reduction, if you didn't want it in the first place.

(*) At least for Epetra/Tpetra, Xpetra does not offer such method. And for Belos, this would require to add Reduce to the mv traits, and manually call it, since it is not in the current interface.

**Comment by mhoemmen** [comment]
@bartgol wrote:
> and make the sampled vector replicated across ranks.

When you say "sample," are you

  1. sampling the same set of local indices on each process, or
  2. sampling globally from some global set of global indices?

For example, if I have 4 processes with the following global indices:

  - Process 0: 0, 1, 2, 3, 4
  - Process 1: 5, 6, 7
  - Process 2: 8, 9, 10, 11
  - Process 3: 12, 13, 14, 15

are you doing something like this: "Sample the values at local indices 0 and 2 on every process, resulting in a locally replicated vector corresponding to global indices 0, 2, 5, 7, 8, 10, 12, 14"?  Or, are you doing something like this: "Sample global indices 3, 8, and 15, resulting in a locally replicated vector corresponding to global indices 3, 8, and 15"?

You could implement the former with `MPI_Allgather`.  You could implement the latter by constructing a Map that has global indices 3, 8, and 15 replicated on every process, then `Import`ing the Vector from its original Map to this new Map, with the `REPLACE` `CombineMode`.

**Comment by bartgol** [comment]
It's the latter. And yes, after I found out about the reduce, I switched to an import operation.

But the point remains: a user may want to do a mat-vec, and have the result being locally replicated. There's nothing that conceptually raises a flag: I make my range map replicated, and there you go, I have a locally replicated output vector. Nope, cause Petra will basically multiply the entries in the result by the number of ranks. I find this behavior quite sneaky. Someone without access to the source code would never guess it.

**Comment by bartgol** [comment]
Another way of seeing this is this: why should Petra care how I decide to distribute my range map? That's my business. Making assumptions on how I want to use the mat-vec result should not be any of Petra's business.

**Comment by bartgol** [comment]
Also (since I thought about it, but was wrong), creating the map without paying the number of global entries is not a solution (even if all ranks have all the gids), since the global size of the map would be multiplied by the number of ranks.

**Comment by mhoemmen** [comment]
> since the global size of the map would be multiplied by the number of ranks.

It doesn't actually matter -- it's still effectively a replicated Map.

**Comment by mhoemmen** [comment]
@bartgol wrote:
> why should Petra care how I decide to distribute my range map?

It surprises me that this case of a replicated range Map works or even exists, given that it violates the preconditions of Export.  (If the row Map and range Map differ, then the Export is nontrivial, and thus the range Map must be one to one.)  On the other hand, Ifpack2 (and probably also Ifpack) have a weird corner case for their AdditiveSchwarz implementations that breaks this assumption.

**Comment by mhoemmen** [comment]
Anyway, does this answer your question?

**Comment by bartgol** [comment]
> > since the global size of the map would be multiplied by the number of ranks.
> 
> It doesn't actually matter -- it's still effectively a replicated Map.

Not when you inspect the global dimension. A replicated map will have a different global dimension than one created with -1 (or invalid) number of global elements. From the _practical_ point of view, yes, they are the same. But some classes may see this as a different map. In particular, they would cause different behavior in the thyra tpetra vector spaces: if the number of gids is, say, 10, with a locally replicated petra map, the thyra vs has dimension 10, while with a map which is marked as distributed, the vs dimension will be 10*numRanks. So there are advantages in marking the map as really locally replicated.

> @bartgol wrote:
> 
> > why should Petra care how I decide to distribute my range map?
> 
> It surprises me that this case of a replicated range Map works or even exists, given that it violates the preconditions of Export. (If the row Map and range Map differ, then the Export is nontrivial, and thus the range Map must be one to one.) On the other hand, Ifpack2 (and probably also Ifpack) have a weird corner case for their AdditiveSchwarz implementations that breaks this assumption.

Oh, the row and range map will coincide. You simply have a replicated range (and row) map.



> Anyway, does this answer your question?

Yes and no. Yes, I see why it was implemented that way. But no, I don't understand why this should be the default behavior. In other words, what would the downsides of having the mat-vec multiply *not* doing the reduction in the locally replicated case? I mean, other than having to manually add the `Reduce` call after the cases that currently rely on that (which is, I admit, not a small effort).

**Comment by mhoemmen** [comment]
@bartgol If you have an application use case for this change in behavior, I'll be happy to file a feature request for Tpetra for you.

**Comment by bartgol** [comment]
Well, as I said, I found a workaround with Imports. I was wondering if there were compelling reasons to keep the current behavior vs a "normal" mat-vec.

I guess what would be helpful is a "warning" in the header file comments, that informs the user that *if* the output vector has a locally replicated map, a reduction across its comm will happen. It might save the user (most likely, future me) some debug time...

If I will run into this problem in the more general case when an actual mat-vec is needed (as opposed to my current case where an import operation does the trick), I will be happy to open a feature branch.
