### ISSUE TITLE
Fails to use then supplied openmpi path

### ISSUE THREAD

**Issue by yurivict** [trilinos/Trilinos#468]
On FreeBSD OpenMPI headers are in /usr/local/mpi/openmpi/include. During configure and build stages CXXFLAGS has -L flag with this folder.

cmake has these arguments:

```
-DTrilinos_ENABLE_OpenMP:BOOL=ON
-DTPL_ENABLE_MPI:BOOL=ON
-DMPI_BASE_DIR:PATH="/usr/local/mpi/openmpi"
-DMPI_BIN_DIR:PATH="/usr/local/mpi/openmpi/bin"
```

Yet build still breaks with this error:

```
/usr/ports/math/trilinos/work/Trilinos-trilinos-release-12-6-2/packages/zoltan/src/include/zoltan.h:50:17: fatal error: mpi.h: No such file or directory
 #include <mpi.h>
```

System calls trace shows that the "openmpi" folder is never looked at for mpi.h.

**Comment by jwillenbring** [comment]
CC: @bmpersc

**Comment by bmpersc** [comment]
Can you send the full compile line that is failing please? I need to see more information about the compile to be able to tell what may have happened.

**Comment by yurivict** [comment]
The configure line (doesn't fail) is:

/usr/bin/env CXXFLAGS=-O2 -pipe -fno-omit-frame-pointer -fstack-protector -Wl,-rpath=/usr/local/lib/gcc48 -fno-strict-aliasing -fno-omit-frame-pointer  -Wl,-rpath=/usr/local/lib/gcc48 PYTHON=/usr/local/bin/python2.7 XDG_DATA_HOME=/usr/ports/math/trilinos/work XDG_CONFIG_HOME=/usr/ports/math/trilinos/work HOME=/usr/ports/math/trilinos/work SHELL=/bin/sh CONFIG_SHELL=/bin/sh /usr/local/bin/cmake -DTrilinos_ENABLE_ALL_PACKAGES:BOOL=ON -DTrilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=ON -DTrilinos_ENABLE_OpenMP:BOOL=ON -DTPL_ENABLE_MPI:BOOL=ON -DMPI_BASE_DIR:PATH=/usr/local/mpi/openmpi -DMPI_BIN_DIR:PATH=/usr/local/mpi/openmpi/bin -DCMAKE_INSTALL_PREFIX:PATH=/usr/local -DBUILD_SHARED_LIBS:BOOL=ON -DTrilinos_ENABLE_SEACAS:BOOL=OFF -DCMAKE_C_COMPILER:STRING=gcc48 -DCMAKE_CXX_COMPILER:STRING=g++48 -DCMAKE_C_FLAGS:STRING=-O2 -pipe -fno-omit-frame-pointer  -fstack-protector -Wl,-rpath=/usr/local/lib/gcc48 -fno-strict-aliasing -DCMAKE_C_FLAGS_DEBUG:STRING=-O2 -pipe -fno-omit-frame-pointer  -fstack-protector -Wl,-rpath=/usr/local/lib/gcc48 -fno-strict-aliasing -DCMAKE_C_FLAGS_RELEASE:STRING=-O2 -pipe -fno-omit-frame-pointer  -fstack-protector -Wl,-rpath=/usr/local/lib/gcc48 -fno-strict-aliasing -DCMAKE_CXX_FLAGS:STRING=-O2 -pipe -fno-omit-frame-pointer -fstack-protector -Wl,-rpath=/usr/local/lib/gcc48 -fno-strict-aliasing -fno-omit-frame-pointer  -Wl,-rpath=/usr/local/lib/gcc48 -DCMAKE_CXX_FLAGS_DEBUG:STRING=-O2 -pipe -fno-omit-frame-pointer -fstack-protector -Wl,-rpath=/usr/local/lib/gcc48 -fno-strict-aliasing -fno-omit-frame-pointer  -Wl,-rpath=/usr/local/lib/gcc48 -DCMAKE_CXX_FLAGS_RELEASE:STRING=-O2 -pipe -fno-omit-frame-pointer -fstack-protector -Wl,-rpath=/usr/local/lib/gcc48 -fno-strict-aliasing -fno-omit-frame-pointer  -Wl,-rpath=/usr/local/lib/gcc48 -DCMAKE_EXE_LINKER_FLAGS:STRING= -fstack-protector -Wl,-rpath=/usr/local/lib/gcc48 -L/usr/local/lib/gcc48 -DCMAKE_MODULE_LINKER_FLAGS:STRING= -fstack-protector -Wl,-rpath=/usr/local/lib/gcc48 -L/usr/local/lib/gcc48 -DCMAKE_SHARED_LINKER_FLAGS:STRING= -fstack-protector -Wl,-rpath=/usr/local/lib/gcc48 -L/usr/local/lib/gcc48 -DCMAKE_INSTALL_PREFIX:PATH=/usr/local -DCMAKE_BUILD_TYPE:STRING=Release -DTHREADS_HAVE_PTHREAD_ARG:BOOL=YES -DCMAKE_INSTALL_RPATH_USE_LINK_PATH=YES -DPython_ADDITIONAL_VERSIONS=2.7 /usr/ports/math/trilinos/work/Trilinos-trilinos-release-12-6-2


The subsequent build line that fails:

/usr/bin/env XDG_DATA_HOME=/usr/ports/math/trilinos/work XDG_CONFIG_HOME=/usr/ports/math/trilinos/work HOME=/usr/ports/math/trilinos/work NO_PIE=yes MK_DEBUG_FILES=no MK_KERNEL_SYMBOLS=no SHELL=/bin/sh NO_LINT=YES ADDR2LINE=/usr/local/bin/addr2line AR=/usr/local/bin/ar AS=/usr/local/bin/as CPPFILT=/usr/local/bin/c++filt GPROF=/usr/local/bin/gprof LD=/usr/local/bin/ld NM=/usr/local/bin/nm OBJCOPY=/usr/local/bin/objcopy OBJDUMP=/usr/local/bin/objdump RANLIB=/usr/local/bin/ranlib READELF=/usr/local/bin/readelf SIZE=/usr/local/bin/size STRINGS=/usr/local/bin/strings PREFIX=/usr/local LOCALBASE=/usr/local LIBDIR=/usr/lib CC=gcc48 CFLAGS=-O2 -pipe -fno-omit-frame-pointer  -fstack-protector -Wl,-rpath=/usr/local/lib/gcc48 -fno-strict-aliasing CPP=cpp48 CPPFLAGS=-fno-omit-frame-pointer LDFLAGS= -fstack-protector -Wl,-rpath=/usr/local/lib/gcc48 -L/usr/local/lib/gcc48 LIBS= CXX=g++48 CXXFLAGS=-O2 -pipe -fno-omit-frame-pointer -fstack-protector -Wl,-rpath=/usr/local/lib/gcc48 -fno-strict-aliasing -fno-omit-frame-pointer  -Wl,-rpath=/usr/local/lib/gcc48 MANPREFIX=/usr/local BSD_INSTALL_PROGRAM=install   -m 555 BSD_INSTALL_LIB=install   -m 444 BSD_INSTALL_SCRIPT=install  -m 555 BSD_INSTALL_DATA=install  -m 0644 BSD_INSTALL_MAN=install  -m 444 gmake -f Makefile -j8 all
```
...
[  0%] Building C object packages/zoltan/src/CMakeFiles/zoltan.dir/all/all_allo.c.o
In file included from /usr/ports/math/trilinos/work/Trilinos-trilinos-release-12-6-2/packages/zoltan/src/zz/zz_const.h:58:0,
                 from /usr/ports/math/trilinos/work/Trilinos-trilinos-release-12-6-2/packages/zoltan/src/all/all_allo_const.h:51,
                 from /usr/ports/math/trilinos/work/Trilinos-trilinos-release-12-6-2/packages/zoltan/src/all/all_allo.c:57:
/usr/ports/math/trilinos/work/Trilinos-trilinos-release-12-6-2/packages/zoltan/src/include/zoltan.h:50:17: fatal error: mpi.h: No such file or directory
 #include <mpi.h>
                 ^
```

**Comment by jwillenbring** [comment]
This is very old. If this is still an issue, please reopen with updated info.
