### ISSUE TITLE
Trilinos compilation error in Albany nightly due to Xpetra/MueLu 

### ISSUE THREAD

**Issue by ikalash** [trilinos/Trilinos#4689]
We have a new failing build in the Albany nightlies: 

http://cdash.sandia.gov/CDash-2-3-0/viewBuildError.php?buildid=82719 

It appears the problem is with @trilinos/xpetra , @trilinos/muelu . The compiler is gcc/8.2.1 .  Note that Albany nightlies use master instead of develop branch of Trilinos.  I changed it in hopes that it would be more stable (but I am rethinking that decision now...).

**Comment by mhoemmen** [comment]
master is definitely more stable than develop :-)
Trilinos PR testing is in a bit of a bind at the moment, but the framework team is working on it and it should be OK soon.

**Comment by ikalash** [comment]
@mhoemmen : I believe it.  There are 2 issues I see with using master:

1.) Pushes that break Albany builds don't show up right away - there is a lag.
2.) Fixes that are pushed to try to fix things that broke in Albany don't get in right away - again there is a lag. 

For now I will keep master but we will see longer term.

**Comment by jhux2** [comment]
@ikalash It appears the output in the Albany dashboard logs isn't complete.  Maybe I'm just missing something?

**Comment by ikalash** [comment]
@jhux2 : sorry about that.  I'm attaching the entire log from the compilation.
[trilinos-serial-gcc-release.log](https://github.com/trilinos/Trilinos/files/2992997/trilinos-serial-gcc-release.log)

**Comment by ikalash** [comment]
P.S. I see we (Albany) have our own label now!

**Comment by ikalash** [comment]
Just talked to @jhux2 and this seems to be a falsely reported error by CDash - weird.  In the log there are a bunch of warning but no errors, even though 1 compilation error is reported at the end.  Albany built just fine on top of this Trilinos, as it turns out, meaning the Trilinos was actually good.  Closing - sorry for the spam!
