### ISSUE TITLE
Compile error with gcc-4.8.5: error: cast from 'std::nullptr_t' to 'char' loses precision

### ISSUE THREAD

**Issue by yurivict** [trilinos/Trilinos#469]
```
/usr/ports/math/trilinos/work/Trilinos-trilinos-release-12-6-2/packages/triutils/src/Trilinos_Util_iohb.cpp:1669:24: error: cast from 'std::nullptr_t' to 'char' loses precision [-fpermissive]
     SubS[len] = (char) NULL;
```

This is a valid error, because NULL is meant to be a pointer, not a char.

**Comment by jwillenbring** [comment]
@maherou can you suggest how to handle this? If I remember right, iohb is essentially a third-party code.

**Comment by maherou** [comment]
We are free to modify the source as long as we don't change the functional behavior.  Assigning an approrpriately sized char string end should be fine.

**Comment by jwillenbring** [comment]
@bmpersc Is this something you can slot in? Otherwise, I can look elsewhere.

**Comment by bmpersc** [comment]
This looks exactly like another issue that was reported a few weeks ago. The solution provided then was to use "\0" which should be the right thing here too. I will check that this wasn't fixed by that in a more recent bug fix to 12.6 and apply it to 12.6 and develop if it is still there.

**Comment by bmpersc** [comment]
Looks like this is one of the things fixed by Tom Russo's patch a few weeks ago. We haven't put out a bug fix containing it yet. I will look into getting that bug fix out this week. Tom's changes haven't been applied to develop yet. I will leave this bug open until I have gotten this fixed on develop.

**Comment by jwillenbring** [comment]
@bmpersc Can this issue now be closed?

**Comment by bmpersc** [comment]
I think I still need to apply the changes to develop. I will check and if they aren't there yet I will apply them.

**Comment by bmpersc** [comment]
Tom's changes have been pushed to develop now.
