### ISSUE TITLE
Framework: can't access PR dashboard, insecure connection?

### ISSUE THREAD

**Issue by jhux2** [trilinos/Trilinos#4690]
@trilinos/framework 

I can't access the PR dashboard, starting sometime on 3/21/2019.  The URL is `https://testing-vm.sandia.gov/cdash/index.php?project=Trilinos&filtercount=1&showfilters=1&field1=buildname&compare1=65&value1=PR-`, and until yesterday, it worked fine.

The message is

![image](https://user-images.githubusercontent.com/12970120/54767602-b7bb0c80-4bba-11e9-8f6e-0e9a4b4a2dfb.png)

**Comment by ZUUL42** [comment]
Until that gets through, you can delete "-vm" from the address or add an exception to Firefox.

**Comment by jhux2** [comment]
@ZUUL42 Thanks, removing "-vm" works.
