### ISSUE TITLE
Framework: Certificate errors on cdash website

### ISSUE THREAD

**Issue by csiefer2** [trilinos/Trilinos#4694]
This makes it difficult to persuade your web browser to let you see failing tests.

@jwillenbring @trilinos/framework

**Comment by csiefer2** [comment]
As per @jwillenbring links will be updated soon.

**Comment by ZUUL42** [comment]
#4690 #4691
Workarounds:
Remove "-vm" from the address.
Chrome doesn't allow cert issues, but Firefox will allow an exception.
