### ISSUE TITLE
Tempus: Fix Divide by Zero

### ISSUE THREAD

**Issue by ccober6** [trilinos/Trilinos#4698]
In the relative norm calculation, the denominator is not check if zero during the consistency check.

@trilinos/tempus

**Comment by rppawlo** [comment]
@ccober6 - do we not have a test for this code path in tempus? I'm wondering how it got through trilinos testing and was only caught by empire?

**Comment by ccober6** [comment]
Yeah, I was surprised too.  I need to check this, and see how it got through.  I thought I had fixed it in both explicit and implicit, and wondered if the merge was not "good".  But if we had a test on this it should have picked it up.
