### ISSUE TITLE
MueLu: Add MagmaSparse support to Matvec driver

### ISSUE THREAD

**Issue by jjellio** [trilinos/Trilinos#4718]
Enable evaluation and testing of SpMVs using MAGMA Sparse.

@trilinos/muelu 

## Expectations
Matvec driver should be able to compare Tpetra vs Magama Sparse for ScalarType=Double and Ordinals = INT or LONG LONG INT

## Possible Solution
Accept my PR that provides this.

**Comment by jhux2** [comment]
This was apparently addressed by #4719.  Please reopen if that's not the case.
