### ISSUE TITLE
release 12.6.4 bug fix tarball

### ISSUE THREAD

**Issue by bmpersc** [trilinos/Trilinos#472]
There are a number of patches to 12.6 that need to be released including one fix that is needed for issue #469.

**Comment by bmpersc** [comment]
issues also waiting for this release: #401 and #445

**Comment by nmhamster** [comment]
@bmpersc see update on #401 just posted.

**Comment by bmpersc** [comment]
Release 12.6.4 has been completed and is available on trilinos.org
