### ISSUE TITLE
STKBalance tests failing on ATDM cee intel builds 

### ISSUE THREAD

**Issue by fryeguy52** [trilinos/Trilinos#4724]
CC: @trilinos/stk, @kddevin (Trilinos Data Services Product Lead), @bartlettroscoe, @fryeguy52
 
## Next Action Status
<status-and-or-first-action>
 
## Description
 
As shown in [this query](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=7&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-cee-rhel6_intel-&field2=buildname&compare2=63&value2=static_opt&field3=testname&compare3=65&value3=STKBalance_stk_balance_&field4=testname&compare4=66&value4=_MPI_4&field5=site&compare5=61&value5=cee-rhel6&field6=buildstarttime&compare6=84&value6=2019-03-26T00%3A00%3A00&field7=buildstarttime&compare7=83&value7=2019-02-24T00%3A00%3A00) the tests:
* STKBalance_stk_balance_m2n_MPI_4
* STKBalance_stk_balance_MPI_4

are failing in the builds:
* Trilinos-atdm-cee-rhel6_intel-18.0.2_mpich2-3.2_openmp_static_opt
* Trilinos-atdm-cee-rhel6_intel-17.0.1_intelmpi-5.1.2_serial_static_opt

They are failing with s segmentation fault:
```
===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   PID 37762 RUNNING AT ceerws1113
=   EXIT CODE: 139
=   CLEANING UP REMAINING PROCESSES
=   YOU CAN IGNORE THE BELOW CLEANUP MESSAGES
===================================================================================
YOUR APPLICATION TERMINATED WITH THE EXIT STRING: Segmentation fault (signal 11)
This typically refers to a problem with your application.
Please see the FAQ page for debugging suggestions
```
new commits for that build can be found [here](https://testing.sandia.gov/cdash/viewNotes.php?buildid=4761571#!#note1)

## Current Status on CDash

[CDash results from the last testing day](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=7&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-cee-rhel6_intel-&field2=buildname&compare2=63&value2=static_opt&field3=testname&compare3=65&value3=STKBalance_stk_balance_&field4=testname&compare4=66&value4=_MPI_4&field5=site&compare5=61&value5=cee-rhel6&field6=buildstarttime&compare6=84&value6=today&field7=buildstarttime&compare7=83&value7=yesterday)

## Steps to Reproduce

One should be able to reproduce this failure on a machine with a cee rhel6 environment as described in:
* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md

More specifically, the commands given for a machine with a cee rhel6 environment are provided at:
* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#cee-rhel6-environment

The exact commands to reproduce this issue should be:
```
$ cd <some_build_dir>/
$ source $TRILINOS_DIR/cmake/std/atdm/load-env.sh Trilinos-atdm-cee-rhel6_intel-18.0.2_mpich2-3.2_openmp_static_opt
$ cmake \
 -GNinja \
 -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
 -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_STK=ON \
 $TRILINOS_DIR
$ make NP=16
$ ctest -j16
```

**Comment by alanw0** [comment]
I'll take a look at this. The stk_balance tests are of course passing in the sierra environment, so it leaves me with the drudgery of figuring out what's different between the environments.
Also, stk_balance was just recently cmake-ified. I would be surprised if the trilinos build enabled it explicitly, so I'll try to figure out why it's somehow being enabled automatically.

**Comment by bartlettroscoe** [comment]
@alanw0 said:

> Also, stk_balance was just recently cmake-ified. I would be surprised if the trilinos build enabled it explicitly, so I'll try to figure out why it's somehow being enabled automatically.

@kddevin and @alanw0, do we know if EMPIRE, Gemma, or SPARC are using STKBalance?  Given this fact it seems very unlikely.  Is it used by or will it be used by customers outside of Sierra through the CMake build system?

**Comment by alanw0** [comment]
@bartlettroscoe I don't believe anyone outside of sierra is using it yet. The exawind (nalu-wind) project will use it, which is the reason we recently added cmake support. In any case, it needs to work when enabled, so I'll look into what's going on.

**Comment by bartlettroscoe** [comment]
Since ATDM APPs are not using STKBalance, I have changed the label to `ATDM Sev: Nonblocker`.

**Comment by bartlettroscoe** [comment]
FYI: PR #4732 may fix this.

**Comment by bartlettroscoe** [comment]
@alanw0, do you have a desire to fix the test `STKBalance_stk_balance_m2n_MPI_4` in these ATDM Trilinos builds anytime soon?

**Comment by bartlettroscoe** [comment]
NOTE: This as shown [yesterday](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&date=2019-04-11&filtercount=1&showfilters=1&field1=testname&compare1=61&value1=STKBalance_stk_balance_m2n_MPI_4), this test only fails in these two ATDM Trilinos intel builds.  It passes in the other 74 builds run yesterday.

**Comment by alanw0** [comment]
@bartlettroscoe thanks for the notification, I'll take a look.

**Comment by bartlettroscoe** [comment]
After the merge of PR #4880 on 4/12/2019 (which removed the test `STKBalance_stk_balance_m2n_MPI_4` which was never supposed to be a test), as shown in [this query](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercombine=and&filtercombine=and&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-&field2=testname&compare2=65&value2=STKBalance_&field3=buildstarttime&compare3=83&value3=2019-04-10), there have been no failing STKBalance tests on any ATDM Trilinos build on any platform since 4/12/2019.

Thanks for fixing @alanw0!

Closing as complete.
