### ISSUE TITLE
NOX_LOCA_BrussXYZT_bdsdt_MPI_2 failing on ATDM serrano build

### ISSUE THREAD

**Issue by fryeguy52** [trilinos/Trilinos#4725]
CC: @trilinos/nox, @rppawlo (Trilinos Nonlinear Solvers Product Lead), @bartlettroscoe, @fryeguy52
 
<Checklist>
<???: Add label "ATDM">
<???: Add label "bug"?>
<???: Add label for affected packages (e.g. "MueLu", "Tpetra", "Kokkos", etc.)>
<???: Add milestone "Initial cleanup of new ATDM builds of Trilinos" or "Keep promoted ATDM builds of Trilinos clean">
<???: Once GitHub Issue is created, add entries for tests to TrilinosATDMStatus/*.csv files>
<???: Add label "PA: ???Project Area???" (e.g. "PA: Linear Solvers", "PA: Data Services")>
 
## Next Action Status
<status-and-or-first-action>
 
## Description
 
As shown in [this query](<cdash-query-url) the tests:
* NOX_LOCA_BrussXYZT_bdsdt_MPI_2

are failing in the builds:
* Trilinos-atdm-serrano-intel-debug-openmp

Test output can be found [here](https://testing.sandia.gov/cdash/testDetails.php?test=72062077&build=4773277)

## Current Status on CDash

current status on cdash can be found [here](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercombine=and&filtercombine=and&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-serrano-intel-debug-openmp&field2=testname&compare2=61&value2=NOX_LOCA_BrussXYZT_bdsdt_MPI_2&field3=site&compare3=61&value3=serrano&field4=buildstarttime&compare4=84&value4=today&field5=buildstarttime&compare5=83&value5=yesterday)

## Steps to Reproduce

One should be able to reproduce this failure on serrano as described in:
* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md

More specifically, the commands given for serrano are provided at:
* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#chamaserrano

The exact commands to reproduce this issue should be:
```
$ cd <some_build_dir>/
$ source $TRILINOS_DIR/cmake/std/atdm/load-env.sh Trilinos-atdm-serrano-intel-debug-openmp
$ cmake \
 -GNinja \
 -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
 -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_NOX=ON \
 $TRILINOS_DIR
$ make NP=16
$ salloc -N1 --time=0:20:00 --account=<YOUR_WCID> ctest -j16
```

**Comment by bartlettroscoe** [comment]
As shown [here](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-serrano-intel-debug-openmp&field2=testname&compare2=61&value2=NOX_LOCA_BrussXYZT_bdsdt_MPI_2&field3=site&compare3=61&value3=serrano&field4=buildstarttime&compare4=84&value4=2019-04-20T00:00:00&field5=buildstarttime&compare5=83&value5=2019-03-21T00:00:00), this has been passing for 24 straight days.  Whatever the problem was it must be resolved not.

Closing as fixed.
