### ISSUE TITLE
Teuchos::ScalarTraits has no specialization for Kokkos:complex<T>

### ISSUE THREAD

**Issue by csiefer2** [trilinos/Trilinos#4726]
We should probably fix this at some point.

### Related issues

Blocks #5263

**Comment by mhoemmen** [comment]
KokkosCore is already an optional dependency of TeuchosCore, so we should be able to add this to `Teuchos_ScalarTraits.hpp`, as long as we protect the `Kokkos_Complex.hpp` include and all `Kokkos::complex<T>`  use with the appropriate macro.

**Comment by mhoemmen** [comment]
This is related to #5269.
