### ISSUE TITLE
Tpetra:  std::call_once does not work well with gcc serial builds

### ISSUE THREAD

**Issue by kddevin** [trilinos/Trilinos#4729]
@trilinos/tpetra @egboman 

Recall from #3057:
Use of std::call_once with gcc in serial builds requires TPL_ENABLE_PThread=ON.

This requirement is not obvious to the user; indeed, only because I had been bitten by it once before (#3033) did I know that info was available in a github issue.  Most users will not guess that Pthreads is required for a serial build (nor should they).

Use of std::call_once has been reintroduced in Tpetra_Details_Behavior.cpp.
Is it necessary?  Can it be removed?

## Expectations

Serial configurations should not need to specify TPL Pthreads to work correctly with Tpetra.

## Current Behavior

std::call_once crashes in serial Trilinos builds without TPL_ENABLE_Pthread=ON.

## Motivation and Context

@egboman is trying to run serial coloring algorithms in Zoltan2 on his Linux workstation.  Tpetra CrsMatrix construction fails because std::call_once fails in fetching debug environment variables in CrsGraph constructor.

## Definition of Done

I hope:  std::call_once removed from Tpetra; I hate being bitten twice by the same bug.

## Steps to Reproduce

build serial Trilinos with Zoltan2 and TPL_ENABLE_Pthread=OFF
make test

## Your Environment
On @egboman's workstation

module purge
module load sems-env
module load sems-cmake
module load sems-gcc/4.9.3

cmake \
  -D CMAKE_BUILD_TYPE:STRING=DEBUG \
  -D BUILD_SHARED_LIBS:BOOL=ON \
  -D Trilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=OFF \
  -D Trilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON \
  -D Trilinos_ENABLE_Zoltan2:BOOL=ON \
  -D Zoltan2_ENABLE_Experimental:BOOL=ON \
  -D Trilinos_ENABLE_TESTS:BOOL=ON \
  -D TPL_BLAS_LIBRARIES="/usr/lib64/libblas.so.3" \
  -D TPL_LAPACK_LIBRARIES="/usr/lib64/liblapack.so.3" \
..

92bf4f0867cd171f89afcfd0a2266d33fd77de39

## Related Issues

Same as #3057 
Related to #3033

**Comment by mhoemmen** [comment]
Does @egboman actually need to disable the Pthread TPL?  He's just doing stuff on his workstation.  You can perfectly well enable the Pthread TPL and not enable Kokkos::Threads etc.

I consider this a GCC bug; using C++11 Standard Library functions should not require linking additional libraries.  Nevertheless, it's reasonable for us to remove use of `std::call_once` if that TPL isn't enabled. 

Note that  [[stmt.decl]](http://eel.is/c++draft/stmt.dcl) (para 4) only promises that initialization of static variables in functions is thread safe.  I don't think that's enough for us to promise thread safety of setting the `std::map` entries (in which `Behavior` caches results of `std::getenv`, to avoid system call overhead).  On the other hand, `std::call_once` only promises thread safety with respect to `std::thread`, not with respect to OpenMP or anything else.

**Comment by egboman** [comment]
Actually, I did not explicitly disable Pthread, this was what happened by default. I have a minimal build for testing and was surprised that tests failed - not expected behavior! Thanks to @kddevin for figuring this out.

Btw, when I enable Pthread as TPL then the tests pass, but there are several Tpetra compile time warnings, mostly unused variables.

**Comment by mhoemmen** [comment]
> Btw, when I enable Pthread as TPL then the tests pass, but there are several Tpetra compile time warnings, mostly unused variables.

Be patient; we're working on it :-)

**Comment by egboman** [comment]
That's fine - they seem to be harmless :-)

**Comment by mhoemmen** [comment]
@egboman I just submitted a PR, #4740, that removes the libpthread requirement and fixes build warnings observed on the Dashboard.  Please review.  Thanks for reporting!

**Comment by mhoemmen** [comment]
@kddevin We usually wait to close issues until fixes hit master (and let the issues automagically get closed by the commit message), but in this case, it looks like the specific problem is solved already, so it's OK to keep this one closed.
