### ISSUE TITLE
INSTALLING TRILINOS(ML SOLVER)

### ISSUE THREAD

**Issue by chandu1263** [trilinos/Trilinos#4736]
@trilinos/<teamName>

## Your Environment

- **Relevant repo SHA1s:**  
- **Relevant configure flags or configure script:**  
- **Operating system and version:**  
- **Compiler and TPL versions:**  

## Related Issues

* Blocks 
* Is blocked by 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of

**Comment by chandu1263** [comment]
I am trying to install ML SOLVER. But there has been a problem.
https://trilinos.org/oldsite/packages/ml/mlguide5.pdf 
I was following the above guide[5.3 Building with Trilinos Support (RECOMMENDED).  ]. And there was config file, then how could I set configuration? I am using UBUNTU 18.04. Please help me.

**Comment by mhoemmen** [comment]
@trilinos/ml

**Comment by csiefer2** [comment]
Just build using cmake 3.10 or greater:

cmake ${MyTrilinosDir} 

will build Trilinos with ML (and a bunch of other stuff).

**Comment by jhux2** [comment]
@chandu1263 wrote:
> I am trying to install ML SOLVER. But there has been a problem.
> https://trilinos.org/oldsite/packages/ml/mlguide5.pdf
> I was following the above guide[5.3 Building with Trilinos Support (RECOMMENDED). ]. And there was config file, then how could I set configuration? I am using UBUNTU 18.04. Please help me.

See the INSTALL.rst file in the root of the Trilinos directory that you download.  I highly recommend that you clone the Trilinos *master* branch from github.

**Comment by jhux2** [comment]
Closing, but feel free to reopen if necessary.
