### ISSUE TITLE
Intrepid2_unit-test_Projection_Serial_Test_InterpolationProjection_TET_MPI_1 failing ATDM mutrino build

### ISSUE THREAD

**Issue by fryeguy52** [trilinos/Trilinos#4738]
CC: @trilinos/intrepid2, @mperego (Trilinos Discretizations Product Lead), @bartlettroscoe, @fryeguy52
 
## Next Action Status
<status-and-or-first-action>
 
## Description
 
As shown in [this query](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercombine=and&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-mutrino-intel-opt-openmp-HSW&field2=testname&compare2=61&value2=Intrepid2_unit-test_Projection_Serial_Test_InterpolationProjection_TET_MPI_1&field3=site&compare3=61&value3=mutrino&field4=buildstarttime&compare4=84&value4=2019-03-27T00%3A00%3A00&field5=buildstarttime&compare5=83&value5=2019-02-25T00%3A00%3A00) the test:
* `Intrepid2_unit-test_Projection_Serial_Test_InterpolationProjection_TET_MPI_1` 

started failing in the build: 
* `Trilinos-atdm-mutrino-intel-opt-openmp-HSW` 

starting on 2019-03-26

test output can be found [here](https://testing.sandia.gov/cdash/testDetails.php?test=72286414&build=4781169)

new commits on the day it started failing can be found [here](https://testing.sandia.gov/cdash/viewNotes.php?buildid=4781164#!#note7)

## Current Status on CDash

current status can be found [here](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercombine=and&filtercombine=and&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-mutrino-intel-opt-openmp-HSW&field2=testname&compare2=61&value2=Intrepid2_unit-test_Projection_Serial_Test_InterpolationProjection_TET_MPI_1&field3=site&compare3=61&value3=mutrino&field4=buildstarttime&compare4=84&value4=today&field5=buildstarttime&compare5=83&value5=yesterday)

## Steps to Reproduce

One should be able to reproduce this failure on mutrino as described in:
* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md

More specifically, the commands given for mutrino are provided at:
* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#mutrino

The exact commands to reproduce this issue should be:
```
$ cd <some_build_dir>/
$ source $TRILINOS_DIR/cmake/std/atdm/load-env.sh Trilinos-atdm-mutrino-intel-opt-openmp-HSW
$ cmake \
 -GNinja \
 -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
 -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_Intrepid2=ON \
 $TRILINOS_DIR
$ make NP=16
$ salloc -N 1 -p standard -J $ATDM_CONFIG_JOB_NAME ctest -j16
```

**Comment by mperego** [comment]
@fryeguy52, this is a new build right?

**Comment by fryeguy52** [comment]
> this is a new build right?

@mperego, This build has been up for a while. We have results from this test on this build going back to November of last year

**Comment by bartlettroscoe** [comment]
@mperego, this failure was likely triggered by the upgrade of the default Intel compiler on ATS-1 ('mutrino', 'trinity', etc.) from intel-18.0.2 to intel-18.0.5 which occurred on 'mutrino' Sunday 3/25/2019 (which would impact builds starting on 3/26/2019).  You would not think that such as small change would trigger a failure but apparently it did.

**Comment by mperego** [comment]
@bartlettroscoe thanks.  In fact, on the Dashboard I was not able to go back before 3/26.

**Comment by mperego** [comment]
never mind, it was an  issue with filters.
