### ISSUE TITLE
basic examples not working in ML package

### ISSUE THREAD

**Issue by chandu1263** [trilinos/Trilinos#4768]
I built ML package using ml_guide.
And basic examples are not working. Please let me know if the build id wrong or anything else is the issue. I am attaching screenshots.
![Screenshot from 2019-03-30 16-55-36](https://user-images.githubusercontent.com/33172514/55275473-98378880-530c-11e9-9948-72636c55f59d.png)
![Screenshot from 2019-03-30 16-54-49](https://user-images.githubusercontent.com/33172514/55275474-98d01f00-530c-11e9-84e6-9a15b2c40646.png)

**Comment by mhoemmen** [comment]
Here's how you build examples:

  1. When configuring (running CMake on) Trilinos, set the CMake option `ML_ENABLE_EXAMPLES:BOOL=ON`.
  2. Use `make` (or `ninja` or your chosen CMake back-end) to build Trilinos.

The examples will build as part of Trilinos' normal build process.  Don't just run `g++` or whatever.  Trilinos' generated Makefiles (or Ninja files etc.) will pull in the right build and link options for you.

@trilinos/ml

**Comment by jhux2** [comment]
Instead of using the ML guide, you should use the directions in the Trilinos README.md, found [here](https://github.com/trilinos/Trilinos/blob/master/INSTALL.rst).

**Comment by jhux2** [comment]
@chandu1263 I just realized that you asked a related question in issue #4736.  Did you follow the advice there?

**Comment by jhux2** [comment]
Closing, but please update/reopen if you're still having problems.
