### ISSUE TITLE
Deprecation in Tpetra::CrsMatrix constructor triggers warning in Xpetra that crashes the SPARC build

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#4770]
CC: @trilinos/xpetra, @trilinos/tpetra , @kddevin  (Trilinos Data Services Product Lead), @bartlettroscoe, @fryeguy52, @mhoemmen 

## Next Action Status

<status-and-or-first-action>

## Description

The commit 24cef7553e09f35f08a8c93bd3c7f8dab5aeb3ea merged in PR #4748 deprecated a constructor for `Tpetra::CrsMatrix` and triggered a deprecated warning when SPARC builds showing the error:

```
/projects/atdm_devops/trilinos_installs/2019-03-29/cee-rhel6_clang-5.0.1_openmpi-1.10.2_serial_static_opt/include/Xpetra_TpetraCrsMatrix.hpp:109:31: error: 'CrsMatrix' is deprecated [-Werror,-Wdeprecated-declarations]
     : mtx_(Teuchos::rcp(new Tpetra::CrsMatrix (toTpetra(rowMap), NumEntriesPerRowToAlloc, toTpetra(pftype), params))) {  }
```

This deprecated warning (elevated to an error in SPARC because they set `-Werror`) is triggered inside of Trilinos headers but is not shown in the Xpetra test suite shown [here](https://testing.sandia.gov/cdash-dev-view/index.php?project=Trilinos&parentid=4809252).  Does this show a gap in the automated tests for Xpetra?

## Current Status on CDash

The current status can only be seen in the SPARC Trilinos Integration builds shown over the last few days [here](http://compsim-dashboard.sandia.gov/cdash/index.php?project=SPARC&date=2019-03-30&filtercombine=and&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=66&value1=-trildev&field2=buildstarttime&compare2=83&value2=5%20days%20ago).

## Steps to Reproduce

Since the native test suite does not show a problem, one can only reproduce this by building SPARC itself.  See the instructions for doing that [here](https://snl-wiki.sandia.gov/display/CoodinatedDevOpsATDM/Building+ATDM+APPs+Against+Local+Installs+of+Trilinos#BuildingATDMAPPsAgainstLocalInstallsofTrilinos-BuildingagainsttheSPARCTrilinos'master'versionusingthenativeSPARCTrilinosconfigurationscripts).

But if one wants to reproduce say the `clang-5.0.1` build on a CEE RHEL6 machine, one can follow the instructions at:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md

More specifically, the commands given for the system 'cee-rhel6' are provided at:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#cee-rhel6-environment

The exact commands to reproduce this issue should be:

```
$ cd <some_build_dir>/

$ source $TRILINOS_DIR/cmake/std/atdm/load-env.sh \
    Trilinos-atdm-cee-rhel6_clang-5.0.1_openmpi-1.10.2_serial_static_opt

$ cmake \
 -GNinja \
 -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
 -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_Xpetra=ON \
 $TRILINOS_DIR

$ make NP=16
```

But of course that does not show a warning so Xpetra needs to be upgraded to reproduce that warning.

**Comment by bartlettroscoe** [comment]
CC: @micahahoward, @mhoemmen, @kddevin 

I marked this as `ATDM Sev: Critical` because it destroys our ability to even run the [SPARC Trilinos Integration Builds](https://snl-wiki.sandia.gov/display/CoodinatedDevOpsATDM/SPARC+Trilinos+Integration+Process) and detect new failures.  Also, SPARC is trying to update Trilinos so it is extra important to fix this ASAP.

I will take a quick crack at this.  Looks easy to fix.

**Comment by mhoemmen** [comment]
Just put `()` after `NumEntriesPerRowToAlloc` and it will turn into an `ArrayView`, triggering the nondeprecated constructor.  I'll be happy to fix it unless you would like to.

@bartlettroscoe btw you should be proud of me for encouraging correct use of Teuchos Memory Management idioms here ;-) .  See https://github.com/trilinos/Trilinos/issues/4680 .

**Comment by mhoemmen** [comment]
@trilinos/tpetra @kddevin 

Hi Ross -- you asked on SPAR-537 that we use the `TRILINOS_VERSION_DATE` macro to protect deprecations.  This will affect work by other Tpetra developers, including PR #4701.  We had understood the intent of that macro differently, as a way to deal with actual removed or changed features.  Tpetra developers plan many deprecations before the next minor release.  Given that this is a change in Trilinos development policy, we would appreciate some more formal guidance on how to use this macro for deprecations.

**Comment by bartlettroscoe** [comment]
@mhoemmen,

The `TRILINOS_VERSION_DATE` macro is needed in SPARC if the function it calls need to change.  But it looks like we can contain this inside of Trilinos for now with the patch:

```
diff --git a/packages/xpetra/src/CrsMatrix/Xpetra_TpetraCrsMatrix.hpp b/packages/xpetra/src/CrsMatrix/Xpetra_TpetraCrsMatrix.hpp
index d8cb7f0..714776b 100644
--- a/packages/xpetra/src/CrsMatrix/Xpetra_TpetraCrsMatrix.hpp
+++ b/packages/xpetra/src/CrsMatrix/Xpetra_TpetraCrsMatrix.hpp
@@ -106,7 +106,7 @@ namespace Xpetra {

    //! Constructor specifying (possibly different) number of entries in each row.
    TpetraCrsMatrix(const Teuchos::RCP< const Map< LocalOrdinal, GlobalOrdinal, Node > > &rowMap, const ArrayRCP< const size_t > &NumEntriesPerRowToAlloc, ProfileType pftype=DynamicProfile, const Teuchos::RCP< T
      : mtx_(Teuchos::rcp(new Tpetra::CrsMatrix<Scalar, LocalOrdinal, GlobalOrdinal, Node> (toTpetra(rowMap), [-NumEntriesPerRowToAlloc,-]{+NumEntriesPerRowToAlloc(),+} toTpetra(pftype), params))) {  }

    //! Constructor specifying column Map and fixed number of entries for each row.
    TpetraCrsMatrix(const Teuchos::RCP< const Map< LocalOrdinal, GlobalOrdinal, Node > > &rowMap, const Teuchos::RCP< const Map< LocalOrdinal, GlobalOrdinal, Node > > &colMap, size_t maxNumEntriesPerRow, Profile
```

(See commit c9264fa372b5366e8f8fd6c914a1938d199a6df8 on branch `4770-fix-xpetra-tpetra-deprecated-error`.)

Note that SPARC builds with `-Werror` so deprecated warnings are elevated to errors.

@micahashoward, can we set `-Wno-deprecated-declarations` in the SPARC build to avoid deprecated warnings triggering build errors in SPARC (thereby destroying the purpose of deprecated warnings)?  I will try that out and submit a GitLab Merge Request for this if it works.

Otherwise, @trilinos/tpetra developers and SPARC developers should work this out.  But for now we need to get SPARC Trilinos Integration testing back online ASAP.

**Comment by bartlettroscoe** [comment]
@mhoemmen said:

> @bartlettroscoe btw you should be proud of me for encouraging correct use of Teuchos Memory Management idioms here ;-)

Yes, I saw that.  Greatly appreciated :-)

**Comment by bartlettroscoe** [comment]
Okay, so we do see the deprecated warnings in the build of MueLu shown [here](https://testing.sandia.gov/cdash-dev-view/viewBuildError.php?type=1&buildid=4812483) which shows:

```
...
In file included from /scratch/rabartl/Trilinos.base/NightlyBuilds/Trilinos-atdm-cee-rhel6_clang-5.0.1_openmpi-1.10.2_serial_static_opt/SRC_AND_BUILD/Trilinos/packages/xpetra/src/CrsMatrix/Xpetra_CrsMatrixFactory.hpp:54:
[CTest: warning matched] /scratch/rabartl/Trilinos.base/NightlyBuilds/Trilinos-atdm-cee-rhel6_clang-5.0.1_openmpi-1.10.2_serial_static_opt/SRC_AND_BUILD/Trilinos/packages/xpetra/src/CrsMatrix/Xpetra_TpetraCrsMatrix.hpp:109:31: warning: 'CrsMatrix' is deprecated [-Wdeprecated-declarations]
      : mtx_(Teuchos::rcp(new Tpetra::CrsMatrix<Scalar, LocalOrdinal, GlobalOrdinal, Node> (toTpetra(rowMap), NumEntriesPerRowToAlloc, toTpetra(pftype), params))) {  }
 ```

@mhoemmen, it seems that when deprecating code that one should build all of Trilinos downstream and then address the deprecated warnings in Trilinos.  Do you agree?

**Comment by mhoemmen** [comment]
@bartlettroscoe ok, you get to scold me now ;-)

**Comment by bartlettroscoe** [comment]
FYI: Adding `-Wno-error=deprecated-declaration` to the SPARC configure scripts addressed this for SPARC.  Therefore, I removed the label `ATDM Sev: Critical` and added `ATDM Sev: Nonblocker`.  Therefore, no rush to fix this but it would be nice if SPARC did not see this warning when building.

**Comment by bartlettroscoe** [comment]
Adding `-Wno-error=deprecated-declaration` to the SPARC configure scripts addressed this for SPARC.   Therefore, I don't see a reason to keep this open.  Closing.
