### ISSUE TITLE
EpetraExt unit test error for missing HDF5

### ISSUE THREAD

**Issue by MarDiehl** [trilinos/Trilinos#4774]
When building Trilinos 12.14.1, I get the error

`error: ‘HDF5’ was not declared in this scope`.

in `Trilinos-trilinos-release-12-14-1/packages/epetraext/test/inout/EpetraExt_HDF5_UnitTest.cpp`.
The full log is here [Error.log](https://github.com/trilinos/Trilinos/files/3028041/Error.log)

I have configures Trilinos with

`cmake .. -DTrilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=ON \                                      
             -DTrilinos_ENABLE_ALL_PACKAGES:BOOL=ON \                                               
             -DTrilinos_ENABLE_Gtest:BOOL=ON \                                                      
             -DTrilinos_ENABLE_TESTS=ON \                                                           
             -DTPL_ENABLE_gtest:BOOL=ON \                                                           
             -DTPL_ENABLE_MPI:BOOL=ON \                                                             
             -DPYTHON_EXECUTABLE:PATH=/usr/bin/python2 \                                            
             -DCMAKE_INSTALL_PREFIX:PATH=/usr \                                                     
             -DBUILD_SHARED_LIBS:BOOL=ON                                                            
    make VERBOSE=1`

and HDF5 is not added automatically, see [Configure.log](https://github.com/trilinos/Trilinos/files/3028040/Configure.log)

I'll now try to build explicitly with HDF5.Still, I think that the EpetraEx HDF5 unit test should be disabled if HDF5 is not added as a third partly library

## Teams
I don't know how to mention the EpetraExt team

## Labels
I don't see a drop down list for labels

**Comment by mayrmt** [comment]
@trilinos/epetraext
