### ISSUE TITLE
Trilinos PR testing missed Ifpack2 compile issue

### ISSUE THREAD

**Issue by prwolfe** [trilinos/Trilinos#4775]
From issue #4742

> Hmmm, this is short on details, but I just ran into an issue when using a recent master checkout of Trilinos. 
> 
> Basically lines 2472 and 2478 in the file packages/ifpack2/src/Ifpack2_BlockTriDiContainer_impl.hpp are using a const instance of a class (Kokkos::TeamPolicy) to call a const function for a non-const instance. Being named a "set" function I tried removing the "const" from the call in Ifpack2_BlockTriDiContainer_impl.hpp and got a clean build.
> 
> The $6 question is how did this get through Trilinos testing and how do we fix that.  This is a very simple issue which should have been caught early.
> 
> _Originally posted by @prwolfe in https://github.com/trilinos/Trilinos/issues/4742#issuecomment-478109186_
> 

This issue is to resolve what is missing in the testing and how to resolve that.

**Comment by prwolfe** [comment]
originally merged in #4587 - I was testing in Sierra using gcc 7.2.0

**Comment by prwolfe** [comment]
the Sierra config is attached

[trilinos_configure.txt](https://github.com/trilinos/Trilinos/files/3030227/trilinos_configure.txt)

**Comment by mhoemmen** [comment]
Sierra turns off deprecated Kokkos code (`-DKOKKOS_ENABLE_DEPRECATED_CODE:BOOL=OFF`), which is good, but maybe Trilinos' PR testing does not?

**Comment by mhoemmen** [comment]
revive

**Comment by jhux2** [comment]
closing, can reopen if necessary
