### ISSUE TITLE
Apply for Google's Season of Docs

### ISSUE THREAD

**Issue by jmgate** [trilinos/Trilinos#4776]
## What is It?
The [Software Sustainability Institute](https://www.software.ac.uk/) recently had [a blog post](https://www.software.ac.uk/blog/2019-03-26-season-docs-fostering-open-source-collaboration-tech-writers?mc_cid=19c554b05e&mc_eid=96b055f1e9) introducing Google's [Season of Docs](https://developers.google.com/season-of-docs/).  The goal of the project is to pair technical writers with open source projects in need of documentation for a three month period starting in September of this year.

> In case you're familiar with it, this is similar to Google's [Summer of Code](https://developers.google.com/open-source/gsoc/2008/) project from years ago.

## What's the Timeline Look Like?
The complete timeline [is available here](https://developers.google.com/season-of-docs/docs/timeline), but the parts we need to be aware of are:
*  April 2nd&ndash;23rd:  Submit application to Google
*  April 30th:  Selection of organizations announced
*  September 2nd:  Doc writing officially starts
*  November 29th:  Tech writer submits final work products

## Who Pays for What?
Google will pay the technical writer ~$6,000 (adjusted for cost of living) over the three month period.  They also supply some smaller amount of funding to the institution for the sake of mentoring the technical writer over the course of the season.

## How Does the Tech Writer Do the Work?
They work remotely from wherever they happen to be, using whatever remote collaboration means the mentoring organization uses.  For us, that'd mean we'd communicate via GitHub issues and pull requests, and if we need to speak in person, we could give them a call.  If Sandia wants to fly them out to meet/work in person, that's on us.  There's no need on our end for actual hiring, onboarding, etc.

## What Do We Need to Do?
- [ ] First we need to identify two organization administrators (a primary and a backup) to manage our participation in Season of Docs.  I can be one of these, though I don't need to be.
- [ ] Generate a list of project ideas.  These would be specific tasks that will be accomplished in the three-month program.  There's no need to adhere to these 100% once the program starts, but they are intended to give technical writers an accurate idea of what they might be doing with us.  To decide what we'd like to focus on, we probably want to bring this up at the next Trilinos leaders' meeting (@maherou, @rppawlo, @mperego, @kddevin, @srajama1, @jwillenbring).  If that's too far away, we should probably set up a Skype meeting sooner, because we don't have too much time to get an application together.
- [ ] Given the specific tasks above, we need to identify at least two mentors to help bring the tech writer on board and oversee their work throughout the season.
- [ ] Then we need to submit our application within the next three weeks.

**Comment by jmgate** [comment]
I remember development of tutorial level documentation being a significant discussion point in last year's TUG developer day.  Hopefully this can help us with some of what we were talking about then.

**Comment by srajama1** [comment]
Interesting thought, but I don't know about accepting funding from Google.

**Comment by csiefer2** [comment]
I think the point is that Google pays someone third party directly to write docs for our open source project.  We never see a dime.

**Comment by srajama1** [comment]
No copyright issues here ? I will check on this and get back.

**Comment by csiefer2** [comment]
@srajama1 That would be a concern.  Two questions on that:

1) Can we force the tech writer to match our preferred license?
2) Is the "Google Clause" for the writing a problem?

> 3.3 License to Google. You grant Google a non-exclusive, worldwide, perpetual, irrevocable, free license (with right to sublicense) to reproduce, prepare derivative works of, distribute, perform, display, and otherwise use your Submissions for the purpose of administering the Program and promoting Season of Docs.

**Comment by srajama1** [comment]
@csiefer2 I was checking the same thing. I see the benefit to Trilinos as a focused effort that will improve documentation. However, this seems a lot to give for that. We could pay it ourselves and still follow the same time line assuming we find the right person.

**Comment by jmgate** [comment]
Another concern is it looks like we have a dozen or so different licenses that apply to different packages of Trilinos.  That may disqualify us if any of those doesn't match the list of acceptable licenses.  I started looking through it, but I'm not convinced our License page is up-to-date.

As for accepting money from Google, apparently both the tech writer and the mentoring organization can refuse the stipend that would have been paid out.

**Comment by srajama1** [comment]
From my inquiries, we cannot apply to this. We have two tech writers assigned to our center, we can coordinate with them.

**Comment by srajama1** [comment]
@jmgate : If it is ok, please close this.
