### ISSUE TITLE
Strange behavior in LSQR condition number estimate

### ISSUE THREAD

**Issue by michael-a-hansen** [trilinos/Trilinos#478]
I am attempting to use LSQR to estimate the condition number of some matrices. I began testing my code on simple matrices for which I know the exact condition numbers. While I can successfully get K=1 for a scaled identity matrix, I get inaccurate condition numbers that depend heavily on the linear solve tolerance for matrices of any additional complexity. For instance, on a diagonal matrix with A_{i,i} = -i, I observe that the condition number estimate increases as I tighten solver tolerance, up to 33x the exact answer at machine precision tolerance. Is this behavior strange or am I wrong in my understanding that a converged linear solve with LSQR will correspond to a good estimate of the condition number?

**Comment by mhoemmen** [comment]
Is this the LSQR solver in Belos?

**Comment by michael-a-hansen** [comment]
Yes

**Comment by mhoemmen** [comment]
I'll poke the person who wrote it and see if they can help out.  Is this an urgent request?

**Comment by michael-a-hansen** [comment]
Thank you. It may be an important piece of a summer project, so I'd appreciate feedback within the next few weeks if possible.

**Comment by michael-a-hansen** [comment]
Hi again - while we wait and/or sort out potential Belos::LSQR issues, are there are any other options in Trilinos for estimating the condition number of a nonhermitian matrix?

**Comment by mhoemmen** [comment]
btw I didn't realize you were one of our summer interns.  Could you please send me an e-mail?  I'll put you in touch with the author of LSQR.  You could probably just walk over and bug them ;-)

We have sparse LU factorizations.  You could roll your own L1 condition number estimator using textbook algorithms.  Alternately, you could run Belos GMRES and get the upper Hessenberg matrix out.

**Comment by michael-a-hansen** [comment]
Email sent. My linear algebra is rusty but I'll check out these other options. Thanks!
