### ISSUE TITLE
Unused Tpetra var warning in header breaking SPARC Trilinos Integration builds with -Werror

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#4789]
CC: @trilinos/tpetra, @kddevin  (Trilinos Data Services Product Lead), @bartlettroscoe, @fryeguy52, @mhoemmen 

## Next Action Status

<status-and-or-first-action>

## Description

Recently Tpetra was updated to add a new unused var warning:

```
.../Tpetra_Details_StaticView.hpp:168:9: error: unused type alias 'host_device_type' [-Werror,-Wunused-local-typedef]
```

This is bringing down the [SPARC Trilinos Integration builds](https://snl-wiki.sandia.gov/display/CoodinatedDevOpsATDM/SPARC+Trilinos+Integration+Process) for Clang and GCC due to the SPARC setting `-Werror` in those builds.  Therefore, we get no build or test results in those builds due to this.

## Current Status on CDash

The current status can only be seen in the SPARC Trilinos Integration builds shown over the last few days [here](http://compsim-dashboard.sandia.gov/cdash/index.php?project=SPARC&date=2019-03-30&filtercombine=and&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=66&value1=-trildev&field2=buildstarttime&compare2=83&value2=5%20days%20ago).

## Steps to Reproduce

Instructions to reproduce builds are at:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md

More specifically, the commands given for the system 'cee-rhel6' are provided at:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#cee-rhel6-environment

The exact commands to reproduce this warning should (hopefully) be:

```
$ cd <some_build_dir>/

$ source $TRILINOS_DIR/cmake/std/atdm/load-env.sh \
    Trilinos-atdm-cee-rhel6_clang-5.0.1_openmpi-1.10.2_serial_static_opt

$ cmake \
 -GNinja \
 -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
 -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_Tpetra=ON \
 $TRILINOS_DIR

$ make NP=16
```

**Comment by bartlettroscoe** [comment]
CC: @micahahoward

@mhoemmen and @kddevin,

I marked this `ATDM Sev: Critical` since we don't get any test results for SPARC Trilinos  Integration testing for these two builds and the flood of failing tests due to these makes it hard to see new failures in the other builds that don't have `-Werror`.  Also SPARC is trying to get a Trilinos

If someone can't fix this ASAP I will post a PR to get this fixed.  SPARC Trilinos Integration builds (i.e. build failures taking down all tests) have been broken for since at least 3/20/2018 so it would be really nice to at least get the builds clean so SPARC developers can't triage the 7 failing tests that have been failing since 2/27/2019!

**Comment by bartlettroscoe** [comment]
FYI: With commit 1ebc752  merged directly to 'atdm-nightly' in merge commit 2309f9b, this should be resolved for SPARC (but not Trilinos 'develop' due to PR testing in #4791 crashing).

Putting in review.

**Comment by mhoemmen** [comment]
@bartlettroscoe I'm working on this as part of #4797.
