### ISSUE TITLE
Domi web presence missing

### ISSUE THREAD

**Issue by bmpersc** [trilinos/Trilinos#479]
The Domi package doesn't have any pages on the Trilinos.org site currently. Bill Spotz sent the following email regarding Domi's web presence.

Jim, Brent,

I assume this just got buried in the normal course of things, so I am going to nag again. Domi is not a listed package on the trilinos.org site, but it is officially released, so it should be. I don't really read perl, so it isn't obvious to me if I/we modify doc/build_docs.pl or some other database-type file to do this. Domi has a doc/build_docs script, but that doesn't seem to be sufficient. What else needs to be done?

Thanks,
Bill

**Comment by jwillenbring** [comment]
CC: @wfspotz I will work on this.

Definition of Done:

-create a stub page for Domi that Bill can populate with whatever content he would like there.
-link to the Domi Doxygen content

**Comment by jwillenbring** [comment]
CC: @trilinos/framework 
I created the Domi stub page:

https://trilinos.org/packages/domi/

This page links to the Domi Doxygen for dev and all previous release versions. I am going to close this. @wfspotz should notify us if he needs anything added.
