### ISSUE TITLE
Update dggsvd support in Epetra

### ISSUE THREAD

**Issue by jwillenbring** [trilinos/Trilinos#480]
CC: @bartlettroscoe @maherou 

dggsvd was deprecated in LAPACK 3.6.0. In the same version, dggsvd3 was added, which has one fewer argument but is similar otherwise.

ftp://ftp.icm.edu.pl/packages/netlib/lapack/lapack-3.6.0.txt
http://www.netlib.org/lapack/explore-html/d6/db3/dggsvd3_8f.html
http://www.netlib.org/lapack/explore-html/dd/db4/dggsvd_8f.html

@bartlettroscoe suggested that a configure-time check would be appropriate here to probe LAPACK and see which routine is available. There are examples of this sort of thing in Teuchos (see Trilinos/packages/teuchos/CMakelists.txt).

@krcb is this something @MicheldeMessieres or you could take a look at?

**Comment by krcb** [comment]
I think we can look at some ideas, yes.

**Comment by MicheldeMessieres** [comment]
I'm setting this up. 
dggsvd3 and sggsvd3 add a new parameter LWORK.

I'll need to know how we want to set up the API for the new LWORK parameter and if we need to preserve backwards compatibility and/or compatibility between the two versions.

Should builds with the new version of LAPACK simply change the format of Epetra_LAPACK::GGSVD and add the new parameter?

**Comment by maherou** [comment]
It seems that having a macro associated with the interface change, along with a configure-time check, would be appropriate.  Programmers will also need to know which version of the functions are available and provide the right interface, LWORK or not.

**Comment by MicheldeMessieres** [comment]
Thanks - I've set up a pull request #502 which will provide this configure time check.

**Comment by jwillenbring** [comment]
@bmpersc Could you look at the configure time check proposed in the associated pull request #502?

**Comment by bmpersc** [comment]
Maybe this is just my lack of knowledge on lapack, but is there a reason that the check is using CheckCXXSourceRuns to compile and run code? It seems that checking that dggsvd3 exists is all that is needed and that could be accomplished with one of the standard cmake modules CheckCXXSymbolExists, CheckFortranFunctionExists, or CheckFunctionExists

**Comment by MicheldeMessieres** [comment]
That sounds best. I'll make that change tomorrow and update this pull request. Thanks.

**Comment by MicheldeMessieres** [comment]
Investigating those options:

CheckFortranFunctionExists would work fine (checking for dggsvd3).
However it seems we have to have Fortran enabled so I'm fairly certain that is not an option unless there is a way to work around this.

CheckFunctionExists seems like the way to go and works - but I'll have to handle the name mangling. So for example my configuration needs to find dggsvd3_ (with underscore).

We would want to get the proper string in CMake using the F77_BLAS_MANGLE define but it's not clear to me there is a way to do this without somehow parsing it, which doesn't seem like a safe approach though I expect it can be done. Do you know if there is any precedent for checking a fortran library directly like this that I can use as an example? 

I've also pushed a fix to the header for #502 which I had left in a broken state somehow - this will link now properly for old and new LAPACK versions. Also fixed a setting in the source for the mangling which may affect some configurations - but hopefully can find a way to remove the source completely if I can resolve above issues.

**Comment by MicheldeMessieres** [comment]
I pushed an alternative to check the mangle names explicitly. So the prior commit (running the source) and this version (checking names) both will work. I'm not sure of a better way to do this than these two options.

**Comment by MicheldeMessieres** [comment]
@bmpersc 
hi Brent - following up to see if there is any opinion on this matter? Seems we could do this by specifically checking the various mangle names or do the compile time check. Those options are both set up in a pull request. Thanks.

**Comment by corbett5** [comment]
When I try to build against the reference LAPACK 3.8.0 (https://github.com/Reference-LAPACK/lapack/releases/tag/v3.8.0) I get undefined references to `dggsvd3` and the lot when I link my main code. I tinkered with `CheckHaveEpetraLapackGSSVD3.cmake` but I couldn't get it to work. In the end I had to add
```
-D HAVE_dggsvd3_POST=1
```
to the CMake args which seems pretty hackish.

I'm pointing Trilinos to lapack via
```
-D BLAS_LIBRARY_DIRS=${LAPACK_SUITE_DIR}/lib64
-D LAPACK_LIBRARY_DIRS=${LAPACK_SUITE_DIR}/lib64
```

**Comment by mhoemmen** [comment]
@corbett5 I need to work on some other things this weekend, but let me know if you still have trouble.  I've written link-time tests like this before (though it's been a few years).

**Comment by corbett5** [comment]
@mhoemmen adding `-D HAVE_dggsvd3_POST=1`  is hackish but it seems to work fine and it should work even with other name mangling schemes. It took me a while to figure it out so the main reason I added the comment above was to document my solution in case anyone else has a similar problem and stumbles upon this issue.
