### ISSUE TITLE
spack: Does a spack Trilinos variant exist for enabling CUDA support?

### ISSUE THREAD

**Issue by cwsmith** [trilinos/Trilinos#4810]
I'd like to install Kokkos with the CUDA backend, via Trilinos, with spack.  We use CMake for our projects that depend on Kokkos, hence the install via Trilinos.

Is there a branch of spack with a variant that enables CUDA in Trilinos/Kokkos?

Thank-you,
Cameron

**Comment by mhoemmen** [comment]
@trilinos/framework

**Comment by aprokop** [comment]
I don't think there is one.

**Comment by cwsmith** [comment]
OK.  Thank you.

**Comment by aprokop** [comment]
fwiw, it should be really easy to add it.

**Comment by cwsmith** [comment]
I was thinking the same thing.  Would the following additions cover the most common build configs?

- bool for enabling cuda
- arg for gpu architecture string
- bool for cuda lambda

**Comment by mhoemmen** [comment]
revive
