### ISSUE TITLE
KokkosKernels broke Albany build on Ride

### ISSUE THREAD

**Issue by ikalash** [trilinos/Trilinos#4829]
It appears some changes to KokkosKernels broke Albany's Ride build over the weekend.  Here is the error:
```

58%] Building C object packages/aztecoo/src/CMakeFiles/aztecoo.dir/az_gsumd_puma.c.o                         /.../repos/Trilinos/packages/kokkos-kernels/src/sparse/impl/KokkosSparse_spgemm_impl_color.hpp(516): error: namespace "KokkosGraph::Experimental" has no member "d2_graph_color"
--
```
http://cdash.sandia.gov/CDash-2-3-0/viewBuildError.php?buildid=83384

Could someone please have a look? 
@trilinos/kokkos-kernels

**Comment by mhoemmen** [comment]
@william76 alas this looks a bit familiar

**Comment by jewatkins** [comment]
FYI I turned off KOKKOS_ENABLE_DEPRECATED_CODE on the ride tests so it's most likely related to that?

**Comment by ndellingwood** [comment]
@jewatkins I think you're right, it looks like the patch has the deprecated call guarded out. I'll put in a PR pretty quick here that should fix it whether deprecated code is on or off.

**Comment by ndellingwood** [comment]
@ikalash @jewatkins PR #4832 in with the fix, sorry for the inconvenience.

**Comment by ikalash** [comment]
Thanks @ndellingwood , we'll keep an eye out for your fix.

**Comment by william76** [comment]
Sorry about this... none of my local testing or PR testing caught this...

@mhoemmen should I set up a local test that disables `KOKKOS_ENABLE_DEPRECATED_CODE` in the future to look for these?

@jwillenbring from the framework side, we always have deprecated code enabled by default on all PR testing?

**Comment by mhoemmen** [comment]
@william76 Don't worry, it looks easy to fix :-) 

> should I set up a local test that disables `KOKKOS_ENABLE_DEPRECATED_CODE` in the future to look for these?

Yes; in fact, it would make sense for that to be your default local test.  Thanks!

**Comment by ndellingwood** [comment]
#4832 merged into develop branch last night, hopefully it resolves this issue.

**Comment by ikalash** [comment]
Looks like our Ride nightlies are back to normal, so closing issue.  Thanks for fixing things!
