### ISSUE TITLE
Cdash is backed up again

### ISSUE THREAD

**Issue by bmpersc** [trilinos/Trilinos#483]
our cdash installation is backed up by about a day again. It looks like this started saturday night. I'm working on getting it processing again.

**Comment by tawiesn** [comment]
@bmpersc Dashboard seemed to work fine for the last two weeks. Any news about the dashboard issues? Can we safely close this issue?

**Comment by bmpersc** [comment]
working for the last two weeks isn't exactly accurate. I've been having to keep a close eye on it and have had to repair corruption in the database at least twice in the last two weeks. This seems to be just a standard day to day activity at this point, so it probably is best to close this ticket.

**Comment by tawiesn** [comment]
Any idea what causes the corruption of the database?

Tobias
