### ISSUE TITLE
KokkosKernels_graph tests timing out in ATDM builds

### ISSUE THREAD

**Issue by fryeguy52** [trilinos/Trilinos#4847]
CC: @trilinos/kokkoskernels, @kddevin (Trilinos Data Services Product Lead), @bartlettroscoe, @fryeguy52
 
<Checklist>
<???: Add label "ATDM">
<???: Add label "bug"?>
<???: Add label for affected packages (e.g. "MueLu", "Tpetra", "Kokkos", etc.)>
<???: Add milestone "Initial cleanup of new ATDM builds of Trilinos" or "Keep promoted ATDM builds of Trilinos clean">
<???: Once GitHub Issue is created, add entries for tests to TrilinosATDMStatus/*.csv files>
<???: Add label "PA: ???Project Area???" (e.g. "PA: Linear Solvers", "PA: Data Services")>
 
## Next Action Status
<status-and-or-first-action>
 
## Description
 
As shown in [this query](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=6&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-&field2=testname&compare2=65&value2=KokkosKernels_graph_&field3=testname&compare3=66&value3=_MPI_1&field4=status&compare4=62&value4=Passed&field5=buildstarttime&compare5=83&value5=2019-04-07&field6=buildstarttime&compare6=84&value6=2019-04-10) the tests:
* KokkosKernels_graph_openmp_MPI_1
* KokkosKernels_graph_serial_MPI_1

started timing out on 2019-04-07 in the builds:
* Trilinos-atdm-hansen-shiller-gnu-debug-serial
* Trilinos-atdm-waterman-cuda-9.2-debug
* Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-debug
* Trilinos-atdm-white-ride-gnu-7.2.0-openmp-debug

## Current Status on CDash

Failures for the current testing day can be found [here](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=6&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-&field2=testname&compare2=65&value2=KokkosKernels_graph_&field3=testname&compare3=66&value3=_MPI_1&field4=status&compare4=62&value4=Passed&field5=buildstarttime&compare5=83&value5=yesterday&field6=buildstarttime&compare6=84&value6=today)

## Steps to Reproduce

One should be able to reproduce this failure on ride or white as described in:
* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md

More specifically, the commands given for ride or white are provided at:
* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#ridewhite

The exact commands to reproduce this issue should be:
```
$ cd <some_build_dir>/
$ source $TRILINOS_DIR/cmake/std/atdm/load-env.sh Trilinos-atdm-white-ride-gnu-7.2.0-openmp-debug
$ cmake \
 -GNinja \
 -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
 -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_KokkosKernels=ON \
 $TRILINOS_DIR
$ make NP=16
$ bsub -x -Is -q rhel7F -n 16 ctest -j16
```

**Comment by bartlettroscoe** [comment]
FYI: These are all full `debug` builds (i.e. `-O0 -g` with debug-mode runtime checking enabled) so we will just disable these tests in all of the full `debug` builds.  They will still run in the `release`/`opt` (i.e. `-O3` and no debug-mode runtime checking) and `release-debug` (i.e. `-O3` with debug-mode runtime checking enabled) so they will still provide full coverage.

After we add those disables and confirm, we will add "Disabled Tests" label close.

**Comment by william76** [comment]
@fryeguy52 @bartlettroscoe 
Hmmm, I patched in some updates from the KokkosKernels Distance-2 graph coloring code, I didn't change any of the pre-existing serial algorithms but they are called via a new way, but there are wrappers to preserve backwards compatibility so the interface should have stayed the same.

I'll have a look and see if I can replicate this and get in a fix.  

FYI @ndellingwood I may ping you for advice if I get stuck :p

**Comment by ndellingwood** [comment]
@william76 did the graph coloring changes that you made in kokkos-kernels add new capabilities, algorithms, or options (particularly for d2 coloring) along with new unit tests to exercise that? If so, these tests may have been inching near the timeout limit and the new tests pushed them over and in that case possibly reducing the problem size may help.

**Comment by bartlettroscoe** [comment]
@ndellingwood, @william76, @srajama1,

Note that these tests are only timing out in full debug builds with `CMAKE_BUILD_TYPE=DEBUG` which sets `-O0`.  Either these tests should be disabled by default automatically in `CMAKE_BUILD_TYPE=DEBUG` builds or there should be a "fast" mode that configures these tests to run after when `CMAKE_BUILD_TYPE=DEBUG` but leave them alone otherwise.  Since we have been setting up [`release-debug`](https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#release_debug) builds on every system, I think it is fine to just disable these tests by default in full `CMAKE_BUILD_TYPE=DEBUG` builds.  You can see how Roger did that for Panzer tests in the commit 27ac702aa7c7c7b57b74925e0df149a76a9383b0.  Can we use that same strategy for these tests in Kokkos, KokkosKernels, etc. that run **much** slower in full  `CMAKE_BUILD_TYPE=DEBUG` builds?

**Comment by ndellingwood** [comment]
> Since we have been setting up [`release-debug`](https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#release_debug) builds on every system, I think it is fine to just disable these tests by default in full `CMAKE_BUILD_TYPE=DEBUG` builds. You can see how Roger did that for Panzer tests in the commit [27ac702](https://github.com/trilinos/Trilinos/commit/27ac702aa7c7c7b57b74925e0df149a76a9383b0). Can we use that same strategy for these tests in Kokkos, KokkosKernels, etc. that run **much** slower in full `CMAKE_BUILD_TYPE=DEBUG` builds?


@srajama1 @crtrott are either of you opposed to Ross's suggestion?

@bartlettroscoe Christian and Siva are on travel until tomorrow, but I'd like to get their opinion in case there is a case I am not considering that would require the full debug mode testing.

**Comment by bartlettroscoe** [comment]
@ndellingwood said:

> @bartlettroscoe Christian and Siva are on travel until tomorrow, but I'd like to get their opinion in case there is a case I am not considering that would require the full debug mode testing.

No big hurry to resolve this.  This is non-blocking so this is not urgent to fix ASAP.

To address this long-term, it would be nice if whoever does Kokkos and KokkosKernels syncs into Trilinos included a least one full  `CMAKE_BUILD_TYPE=DEBUG` and then set a timeout of say 2 minutes on tests in Kokkos and KokkosKernels.  That would help to see which tests need to be disabled in full `CMAKE_BUILD_TYPE=DEBUG`  builds.

**Comment by ndellingwood** [comment]
> To address this long-term, it would be nice if whoever does Kokkos and KokkosKernels syncs into Trilinos included a least one full `CMAKE_BUILD_TYPE=DEBUG` and then set a timeout of say 2 minutes on tests in Kokkos and KokkosKernels.

@bartlettroscoe Good suggestion, I'll do this the next round, thanks!

**Comment by william76** [comment]
@ndellingwood 

I was looking at the output on the [D2GC tests][1] and it looks like these tests are running for 30+ seconds, which is alot when there's a 10 minute timeout limit...

I was looking at the D2 coloring test code in:

https://github.com/trilinos/Trilinos/blob/bd42fe9f6086bde2f02273adecfc40a8ffa97d75/packages/kokkos-kernels/unit_test/graph/Test_Graph_graph_color_distance2.hpp#L253-L258

Which is generating a test graph with 50k nodes and 1.5M edges... I doubt we need a problem that large for a test... unless you're worried about memory footprints or something.  I can patch in a modification to this to drop the problem size 10x to 5000 nodes / 150k edges.

Thoughts?


[1]: https://testing.sandia.gov/cdash/testDetails.php?test=74923958&build=4887942

**Comment by william76** [comment]
@ndellingwood @bartlettroscoe 
I put in PR #4940 that reduces the problem size for the D2GC tests by a factor of 10, this should reduce the time that problem takes.  From the output on the debug mode those two things were eating about 30 seconds each.

I think it'd be good to have a look at the full output from the KokkosKernels test to see what else is taking a long time since the SPGEMM tests do run before the D2GC stuff.  The timing out just happening to happen when we hit D2GC but that doesn't mean that there aren't some things hitting earlier in the test that are eating up a lot of time too.

**Comment by fryeguy52** [comment]
These have been passing consistently for about 2 weeks and the test times are not close to timing out.  I am closing.

<h3><font color="green">Tests with issue trackers Passed: twip=14</font></h3>
<table style="width:100%" boarder="1">

<tr>
<th>Site</th>
<th>Build Name</th>
<th>Test Name</th>
<th>Status</th>
<th>Details</th>
<th>Consec&shy;utive Pass Days</th>
<th>Non-pass Last 30 Days</th>
<th>Pass Last 30 Days</th>
<th>Issue Tracker</th>
</tr>

<tr>
<td align="left">ride</td>
<td align="left"><a href="https://testing.sandia.gov/cdash/index.php?project=Trilinos&filtercombine=and&filtercombine=&filtercount=4&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-white-ride-gnu-7.2.0-openmp-debug&field2=site&compare2=61&value2=ride&field3=buildstarttime&compare3=84&value3=2019-05-01T00:00:00&field4=buildstarttime&compare4=83&value4=2019-04-01T00:00:00">Trilinos-atdm-white-ride-gnu-7.2.0-openmp-debug</a></td>
<td align="left"><a href="https://testing.sandia.gov/cdash/testDetails.php?test=76581462&build=4966879">KokkosKernels_&shy;graph_&shy;openmp_&shy;MPI_&shy;1</a></td>
<td align="left"><a href="https://testing.sandia.gov/cdash/testDetails.php?test=76581462&build=4966879"><font color="green">Passed</font></a></td>
<td align="left">Completed</td>
<td align="right"><a href="https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-white-ride-gnu-7.2.0-openmp-debug&field2=testname&compare2=61&value2=KokkosKernels_graph_openmp_MPI_1&field3=site&compare3=61&value3=ride&field4=buildstarttime&compare4=84&value4=2019-05-01T00:00:00&field5=buildstarttime&compare5=83&value5=2019-04-01T00:00:00"><font color="green">12</font></a></td>
<td align="right"><a href="https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-white-ride-gnu-7.2.0-openmp-debug&field2=testname&compare2=61&value2=KokkosKernels_graph_openmp_MPI_1&field3=site&compare3=61&value3=ride&field4=buildstarttime&compare4=84&value4=2019-05-01T00:00:00&field5=buildstarttime&compare5=83&value5=2019-04-01T00:00:00"><font color="red">12</font></a></td>
<td align="right"><a href="https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-white-ride-gnu-7.2.0-openmp-debug&field2=testname&compare2=61&value2=KokkosKernels_graph_openmp_MPI_1&field3=site&compare3=61&value3=ride&field4=buildstarttime&compare4=84&value4=2019-05-01T00:00:00&field5=buildstarttime&compare5=83&value5=2019-04-01T00:00:00"><font color="green">18</font></a></td>
<td align="right"><a href="https://github.com/trilinos/Trilinos/issues/4847">#4847</a></td>
</tr>

<tr>
<td align="left">hansen</td>
<td align="left"><a href="https://testing.sandia.gov/cdash/index.php?project=Trilinos&filtercombine=and&filtercombine=&filtercount=4&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-hansen-shiller-gnu-debug-serial&field2=site&compare2=61&value2=hansen&field3=buildstarttime&compare3=84&value3=2019-05-01T00:00:00&field4=buildstarttime&compare4=83&value4=2019-04-01T00:00:00">Trilinos-atdm-hansen-shiller-gnu-debug-serial</a></td>
<td align="left"><a href="https://testing.sandia.gov/cdash/testDetails.php?test=76559533&build=4965474">KokkosKernels_&shy;graph_&shy;serial_&shy;MPI_&shy;1</a></td>
<td align="left"><a href="https://testing.sandia.gov/cdash/testDetails.php?test=76559533&build=4965474"><font color="green">Passed</font></a></td>
<td align="left">Completed</td>
<td align="right"><a href="https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-hansen-shiller-gnu-debug-serial&field2=testname&compare2=61&value2=KokkosKernels_graph_serial_MPI_1&field3=site&compare3=61&value3=hansen&field4=buildstarttime&compare4=84&value4=2019-05-01T00:00:00&field5=buildstarttime&compare5=83&value5=2019-04-01T00:00:00"><font color="green">12</font></a></td>
<td align="right"><a href="https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-hansen-shiller-gnu-debug-serial&field2=testname&compare2=61&value2=KokkosKernels_graph_serial_MPI_1&field3=site&compare3=61&value3=hansen&field4=buildstarttime&compare4=84&value4=2019-05-01T00:00:00&field5=buildstarttime&compare5=83&value5=2019-04-01T00:00:00"><font color="red">12</font></a></td>
<td align="right"><a href="https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-hansen-shiller-gnu-debug-serial&field2=testname&compare2=61&value2=KokkosKernels_graph_serial_MPI_1&field3=site&compare3=61&value3=hansen&field4=buildstarttime&compare4=84&value4=2019-05-01T00:00:00&field5=buildstarttime&compare5=83&value5=2019-04-01T00:00:00"><font color="green">18</font></a></td>
<td align="right"><a href="https://github.com/trilinos/Trilinos/issues/4847">#4847</a></td>
</tr>

<tr>
<td align="left">waterman</td>
<td align="left"><a href="https://testing.sandia.gov/cdash/index.php?project=Trilinos&filtercombine=and&filtercombine=&filtercount=4&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-waterman-cuda-9.2-debug&field2=site&compare2=61&value2=waterman&field3=buildstarttime&compare3=84&value3=2019-05-01T00:00:00&field4=buildstarttime&compare4=83&value4=2019-04-01T00:00:00">Trilinos-atdm-waterman-cuda-9.2-debug</a></td>
<td align="left"><a href="https://testing.sandia.gov/cdash/testDetails.php?test=76618511&build=4967515">KokkosKernels_&shy;graph_&shy;serial_&shy;MPI_&shy;1</a></td>
<td align="left"><a href="https://testing.sandia.gov/cdash/testDetails.php?test=76618511&build=4967515"><font color="green">Passed</font></a></td>
<td align="left">Completed</td>
<td align="right"><a href="https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-waterman-cuda-9.2-debug&field2=testname&compare2=61&value2=KokkosKernels_graph_serial_MPI_1&field3=site&compare3=61&value3=waterman&field4=buildstarttime&compare4=84&value4=2019-05-01T00:00:00&field5=buildstarttime&compare5=83&value5=2019-04-01T00:00:00"><font color="green">11</font></a></td>
<td align="right"><a href="https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-waterman-cuda-9.2-debug&field2=testname&compare2=61&value2=KokkosKernels_graph_serial_MPI_1&field3=site&compare3=61&value3=waterman&field4=buildstarttime&compare4=84&value4=2019-05-01T00:00:00&field5=buildstarttime&compare5=83&value5=2019-04-01T00:00:00"><font color="red">12</font></a></td>
<td align="right"><a href="https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-waterman-cuda-9.2-debug&field2=testname&compare2=61&value2=KokkosKernels_graph_serial_MPI_1&field3=site&compare3=61&value3=waterman&field4=buildstarttime&compare4=84&value4=2019-05-01T00:00:00&field5=buildstarttime&compare5=83&value5=2019-04-01T00:00:00"><font color="green">17</font></a></td>
<td align="right"><a href="https://github.com/trilinos/Trilinos/issues/4847">#4847</a></td>
</tr>

<tr>
<td align="left">ride</td>
<td align="left"><a href="https://testing.sandia.gov/cdash/index.php?project=Trilinos&filtercombine=and&filtercombine=&filtercount=4&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-debug&field2=site&compare2=61&value2=ride&field3=buildstarttime&compare3=84&value3=2019-05-01T00:00:00&field4=buildstarttime&compare4=83&value4=2019-04-01T00:00:00">Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-debug</a></td>
<td align="left"><a href="https://testing.sandia.gov/cdash/testDetails.php?test=76590813&build=4966827">KokkosKernels_&shy;graph_&shy;serial_&shy;MPI_&shy;1</a></td>
<td align="left"><a href="https://testing.sandia.gov/cdash/testDetails.php?test=76590813&build=4966827"><font color="green">Passed</font></a></td>
<td align="left">Completed</td>
<td align="right"><a href="https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-debug&field2=testname&compare2=61&value2=KokkosKernels_graph_serial_MPI_1&field3=site&compare3=61&value3=ride&field4=buildstarttime&compare4=84&value4=2019-05-01T00:00:00&field5=buildstarttime&compare5=83&value5=2019-04-01T00:00:00"><font color="green">14</font></a></td>
<td align="right"><a href="https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-debug&field2=testname&compare2=61&value2=KokkosKernels_graph_serial_MPI_1&field3=site&compare3=61&value3=ride&field4=buildstarttime&compare4=84&value4=2019-05-01T00:00:00&field5=buildstarttime&compare5=83&value5=2019-04-01T00:00:00"><font color="red">4</font></a></td>
<td align="right"><a href="https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-debug&field2=testname&compare2=61&value2=KokkosKernels_graph_serial_MPI_1&field3=site&compare3=61&value3=ride&field4=buildstarttime&compare4=84&value4=2019-05-01T00:00:00&field5=buildstarttime&compare5=83&value5=2019-04-01T00:00:00"><font color="green">24</font></a></td>
<td align="right"><a href="https://github.com/trilinos/Trilinos/issues/4847">#4847</a></td>
</tr>

<tr>
<td align="left">ride</td>
<td align="left"><a href="https://testing.sandia.gov/cdash/index.php?project=Trilinos&filtercombine=and&filtercombine=&filtercount=4&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-white-ride-gnu-7.2.0-openmp-debug&field2=site&compare2=61&value2=ride&field3=buildstarttime&compare3=84&value3=2019-05-01T00:00:00&field4=buildstarttime&compare4=83&value4=2019-04-01T00:00:00">Trilinos-atdm-white-ride-gnu-7.2.0-openmp-debug</a></td>
<td align="left"><a href="https://testing.sandia.gov/cdash/testDetails.php?test=76581464&build=4966879">KokkosKernels_&shy;graph_&shy;serial_&shy;MPI_&shy;1</a></td>
<td align="left"><a href="https://testing.sandia.gov/cdash/testDetails.php?test=76581464&build=4966879"><font color="green">Passed</font></a></td>
<td align="left">Completed</td>
<td align="right"><a href="https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-white-ride-gnu-7.2.0-openmp-debug&field2=testname&compare2=61&value2=KokkosKernels_graph_serial_MPI_1&field3=site&compare3=61&value3=ride&field4=buildstarttime&compare4=84&value4=2019-05-01T00:00:00&field5=buildstarttime&compare5=83&value5=2019-04-01T00:00:00"><font color="green">12</font></a></td>
<td align="right"><a href="https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-white-ride-gnu-7.2.0-openmp-debug&field2=testname&compare2=61&value2=KokkosKernels_graph_serial_MPI_1&field3=site&compare3=61&value3=ride&field4=buildstarttime&compare4=84&value4=2019-05-01T00:00:00&field5=buildstarttime&compare5=83&value5=2019-04-01T00:00:00"><font color="red">12</font></a></td>
<td align="right"><a href="https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-white-ride-gnu-7.2.0-openmp-debug&field2=testname&compare2=61&value2=KokkosKernels_graph_serial_MPI_1&field3=site&compare3=61&value3=ride&field4=buildstarttime&compare4=84&value4=2019-05-01T00:00:00&field5=buildstarttime&compare5=83&value5=2019-04-01T00:00:00"><font color="green">18</font></a></td>
<td align="right"><a href="https://github.com/trilinos/Trilinos/issues/4847">#4847</a></td>
</tr>

</table>
