### ISSUE TITLE
MueLu: update LTG Matrix kernels in TpetraExt

### ISSUE THREAD

**Issue by jjellio** [trilinos/Trilinos#4850]
Update the TpetraExt (LTG) kernels to use improved copies and memory management.

These changes were not propagated from the work done last fall. This issue mirrors the PR being submitted.

@trilinos/muelu 
@csiefer2 

## Expectations

- [x] The kernels will use bulk threaded copies for copy-out
- [x] The kernels will compute the rowptr in-place (reduced memory overhead)

**Comment by csiefer2** [comment]
@lucbv - This will benefit your structured word w/ OpenMP
