### ISSUE TITLE
Tpetra: configure error using COMPLEX_DOUBLE and FLOAT types

### ISSUE THREAD

**Issue by ajpowel** [trilinos/Trilinos#4857]
@trilinos/Tpetra

## Expectations

We do not want to turn on Trilinos_ENABLE_COMPLEX_FLOAT if we are also using Trilinos_ENABLE_FLOAT and Trilinos_ENABLE_COMPLEX_DOUBLE.  Is the current behavior (below) correct? 

## Current Behavior
Processing enabled package: Tpetra (Classic, TSQR, Core)
-- Tpetra: Enabling deprecated code
-- Determine whether Tpetra will assume that MPI is CUDA aware:
--   - Tpetra_ENABLE_CUDA is OFF, so Tpetra will assume that MPI is not CUDA aware.
-- Tpetra execution space availability (ON means available): 
--   - Serial:  ON
--   - Threads: OFF
--   - OpenMP:  OFF
--   - Cuda:    OFF
CMake Error at packages/tpetra/CMakeLists.txt:986 (MESSAGE):
  Tpetra: Tpetra_INST_COMPLEX_FLOAT is OFF (meaning that you want to disable
  explicit instantiation and/or tests of Tpetra with Scalar =
  std::complex<float>), but Teuchos_ENABLE_COMPLEX is ON and
  Teuchos_ENABLE_FLOAT is ON.  This will cause downstream link errors, likely
  in Thyra or Stratimikos.  See GitHub Issue 4080 for details.  Best
  practice: Do NOT set Tpetra_INST_COMPLEX_FLOAT, Teuchos_ENABLE_COMPLEX, or
  Teuchos_ENABLE_FLOAT explicitly.  Instead, set
  Trilinos_ENABLE_COMPLEX_FLOAT explicitly.  That will set defaults for
  Teuchos and Tpetra correctly.

-- Configuring incomplete, errors occurred!
See also "/scratch/ajpowel/code_032119/fix_trilly/CMakeFiles/CMakeOutput.log".
See also "/scratch/ajpowel/code_032119/fix_trilly/CMakeFiles/CMakeError.log".

## Motivation and Context

Sierra-Trilinos integration 

## Steps to Reproduce

cmake -DTrilinos_ENABLE_Tpetra=ON -DTrilinos_ENABLE_COMPLEX_DOUBLE=ON -DTrilinos_ENABLE_FLOAT=ON -DTrilinos_ENABLE_Teuchos=ON $PATH_TO_MY_SOURCE_CODE

**Comment by sebrowne** [comment]
@mhoemmen

**Comment by mhoemmen** [comment]
@trilinos/tpetra 

@sebrowne I'm in a phone call now.  I doubt very much that Trilinos has any tests with `Scalar=float` and `Scalar=complex<double>` both enabled.  I'm not sure how to fix this, other than by disabling the check that caused the error, and letting users who do the wrong thing with respect to Thyra settings.  Is that OK?

**Comment by mhoemmen** [comment]
In experimentation yesterday, when we disabled the configure-time check, we got the following build error: https://github.com/trilinos/Trilinos/issues/4858

**Comment by mhoemmen** [comment]
@ajpowel @sebrowne Update: I'm making some progress in my above PR, by setting the following CMake options:
```
Trilinos_ENABLE_FLOAT:BOOL=ON
Amesos2_ENABLE_Epetra:BOOL=OFF
```

**Comment by mhoemmen** [comment]
@ajpowel @sebrowne @rrdrake 
ShyLU's Frosch subpackage is quite broken with respect to this.  Do y'all enable that?

**Comment by sebrowne** [comment]
@mhoemmen we do not, and when I checked CMake's output, it appears that it's disabled as well.

**Comment by mhoemmen** [comment]
This depends on PR https://github.com/trilinos/Trilinos/pull/4955 and PR #4948.
