### ISSUE TITLE
Remove Panzer Warnings

### ISSUE THREAD

**Issue by jmgate** [trilinos/Trilinos#490]
Building Panzer generates a handful of warnings --- looks like they're largely due to deprecated features of libraries we're using.  It'd be nice to clean things up a bit.
@trilinos/panzer

**Comment by jmgate** [comment]
At this point I've removed all the easy ones:
* unused variables and typedefs
* switched calls of Kokkos::View:: or PHX::MDField::dimension() to extent_int()
* switched std::size_ts to ints or ints to size_ts, wherever appropriate
* removed code that was no longer necessary
* static_casted some calls of MDField::size() to ints
* initialized uninitialized variables

**Comment by jmgate** [comment]
Two major tasks remain, which will require a bit more work:
* Switching `Workset::num_cells` from a `std::size_t` to an `int` (see #530).
* `PHX::EvaluatorWithBaseImpl::addDependentField(const PHX::MDField<DataT, Tag0, Tag1, Tag2, Tag3, Tag4, Tag5, Tag6, Tag7>& f)` was deprecated, replaced with a similar version in which `DataT` is `const`.  All uses of `addDependentField` need to be updated, but that change is not trivial.

**Comment by jmgate** [comment]
Finished work on #530&mdash;only bit that remains is the `addDependentField` business.

**Comment by jmgate** [comment]
At this point all warnings have been dealt with except for a few problematic occurrences of the deprecated `addDependentField` warnings.  Initial attempts to switch those fields to `const ScalarT`s, or to create a field with a `const ScalarT` out of the non-`const` one, have been fruitless.

**Comment by bathmatt** [comment]
pushed fix for clang
```
sanj2009-116-24:Trilinos mbetten$ git push
X11 forwarding request failed on channel 0
Counting objects: 13, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (13/13), done.
Writing objects: 100% (13/13), 1.13 KiB | 0 bytes/s, done.
Total 13 (delta 11), reused 0 (delta 0)
remote: Resolving deltas: 100% (11/11), completed with 10 local objects.
To github.com:/trilinos/Trilinos.git
   69a5575..a2052a8  develop -> develop
```

**Comment by jmgate** [comment]
So that `auto` was from fe8070f on April 4th, not from the latest commit on this story.  Any idea why `auto` would confuse clang in such a way?

**Comment by jmgate** [comment]
I've been trying to switch out things like

```c++
Teuchos::RCP<namespace::Package_Ridiculously_LongClass_Name> thing = Teuchos::rcp_dynamic_cast<namespace::Package_Ridiculously_LongClass_Name>(something);
```

with

```c++
auto thing = rcp_dynamic_cast<Package_Ridiculously_LongClass_Name>(something);
```

so the code is easier to read.  Should I not be using `auto` if clang doesn't fully support it?

**Comment by bathmatt** [comment]
I'm not sure why auto failed.  I switched only 2 of them, the rest were fine.  

Lets avoid auto for parameter lists for now..  It is mac that has this issue

**Comment by rppawlo** [comment]
@jmgate and @eric-c-cyr  - pushed the changes to phalanx this morning. See panzer::PointValues_Evaluator for an example of use. Not the most elegant design in the evaluator. A cleaner design would require changes to a number of panzer objects to support interoperability of mixed scalar types (we should do that long term).

**Comment by jmgate** [comment]
Moving this issue to In Review, lest it remain perpetually open.  We can file new issues for specific warnings in the future.

**Comment by eric-c-cyr** [comment]
Closing this. We will have to go through this again periodically, but I think @jmgate has made progress for now.
