### ISSUE TITLE
Stokhos doesn't build with GO=int disabled (GO=long long enabled) and Tpetra_ENABLE_DEPRECATED_CODE=OFF

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#4902]
@trilinos/stokhos @trilinos/tpetra @kddevin @william76 @etphipp 

I fixed all of Stokhos' unit tests and examples not to use `GO=int`, but am still getting link errors.  I will diagnose by inserting a `static_assert (std::is_same<global_ordinal_type, long long>::value, "UH OH");` in `Tpetra::Map` and seeing where it triggers.

**Comment by mhoemmen** [comment]
I tried the `static_assert` thing and got this: https://github.com/trilinos/Trilinos/issues/4903

**Comment by etphipp** [comment]
Did you change stokhos' ETI to not instantiate on `GO=int`?

**Comment by mhoemmen** [comment]
@etphipp wrote:
> Did you change stokhos' ETI to not instantiate on `GO=int`?

Is there a way to do that?  We set `Tpetra_INST_INT_INT=OFF`; does Stokhos not take that as its default?

**Comment by etphipp** [comment]
Currently Stokhos is hard-coded to instantiate on GO=int and LO=int.  I think we can just change those to Tpetra's default GO and LO types.
