### ISSUE TITLE
create 12.8 release

### ISSUE THREAD

**Issue by bmpersc** [trilinos/Trilinos#491]
Following checklist below and updating as needed:

                                                            rev 2016/01

Creating a New Trilinos (Release) Branch with GIT

A GIT branch can be used to maintain a version of the code that is different
than the primary development branch.  This process describes how to create a
Trilinos release branch, but the steps can easily be generalized to apply to
other types of branches.  There are eight steps in creating a Trilinos release
branch:

1. Clone Trilinos

You need to be in a clean state in order to branch Trilinos. It is best if you
start from a fresh clone, but any repository that is up-to-date and in a clean
state (no modified/untracked/etc files) can be used. This does mean that you can
not make changes and have them apply to the branch unless you have commited them
first. You will also need to clone each of the external repos that we release.
These repos will need to be cloned into the packages directory.

The list of external projects as of 1/12/2016 is:
CTrilinos
ForTrilinos
mesquite
moocho
optika
Sundance

To clone a copy of Trilinos type:

Command: git clone git@github.com:trilinos/Trilinos
         cd Trilinos/packages
         git clone git@github.com:trilinos/CTrilinos
         git clone git@github.com:trilinos/ForTrilinos
         git clone git@github.com:trilinos/mesquite
         git clone git@github.com:trilinos/moocho
         git clone git@github.com:trilinos/optika
         git clone git@github.com:trilinos/sundance

2. Tag the working copy

The existing branch is now tagged to mark the point where the new branch will
diverge. This will need to be done for every external repository as well as the
Trilinos repository. To do this, from anywhere in your clone type

Command: git tag -a -m "<short message about tag>" <tag name>

For a release branch, tag name should be root-of-trilinos-release-XYZ-branch,
where XYZ is the release number with the component numbers separated by hyphens
instead of periods.  For example for release 3.1.13, XYZ should be 3-1-13.

3. Create a branch

To create a branch, from anywhere in your clone type

Command: git branch <branch name>

For the Trilinos release version XYZ mentioned above, the branch name should be
trilinos-release-XYZ-branch.

4. Update to convert the working copy to the new branch

The act of creating a new branch does not change the existing working copy to
a that branch.  To make this switch type

Command: git checkout <branch name>

To verify that the preceding command was successful, type

Command: git branch

The branch you are on will have a '*' infront of it.

5. Updates to make to the code when branching

When creating a new Trilinos release branch, the Trilinos version number needs
to be updated in the Trilinos/Version.cmake file. The values for
Trilinos_MAJOR_VERSION, Trilinos_MAJOR_MINOR_VERSION, Trilinos_VERSION_STRING,
and Trilinos_VERSION need to be updated. Also the Trilinos_REPOSITORY_BRANCH
will need to be set to the correct branch name and Trilinos_TESTING_TRACK will
need to be set to the correct cdash track. As well as
${PROJECT_NAME}_ENABLE_DEVELOPMENT_MODE will need to be set to OFF. This file
also needs to be updated on the master branch, However only the version numbers
should be changed to reflect the new development version. 

After making these changes you will want to configure in a directory outside of
the repository you are working in. This is to update the files that are
dependent on the Version.cmake file as well as any other updates that
may have been made.

Finally, git commit the changes. In the commit message, note that branch name
is listed.

6. Tag the new branch

It is a good idea to tag the branch at this point so that the initial state of
the branch is easily retrievable.  To perform this step, type

Command: git tag -a -m "<short message about tag>" <initial tag name>

For the Trilinos release version XYZ mentioned above, the initial tag name
should be initial-trilinos-release-XYZ-branch.

7. Make the branch and tags public

At this point none of these changes, tags or the branch will be publicly
available we need to push them to the public repository, which should be origin.
There is a special way that you have to push branches to the public repository.
To push the branch type

Command: git push origin <local branch name>:<public branch name>

This will push the branch named <local branch name> and the new commits on it
from your clone to origin with the name <public branch name>. Note that you can
rename the branch by giving a different name for <public branch name>, but
recommend not doing this unless you need to fix the name of the branch for some
reason.

Tags are easier to push, you can push them one at a time like the branch, but it
is easier to push all of them at once. To push the tags type

Command: git push --tags

8. Test the new branch

It is a good idea to test the new branch to help make sure that the above
process has been completed properly.  As a part of the general release process,
many tests need to be run.  This step simply refers to running a few simple
sanity checks (for example, build a few Trilinos packages and run ctest for
those packages) to work out any obvious problems before the branch is subjected
to the more complete test suite.

---------------------------------
Reference on related git commands:

When you clone Trilinos you get a copy of every branch and tag that is on the
public repository. However, you do not have a local copy of the branch (unless
you used eg to clone) until you set it up. To checkout a different branch of
Trilinos, from the repository you just cloned type

Command: git checkout --track origin/<name of branch>

This will create a local branch for the given branch and check it out for you.
In addition any changes made to this branch will be pushed back to the correct
branch on origin when you push. This is what is called a tracking branch. Once
you have created a local tracking copy of a branch you won't have to do it again
in the same clone. Instead if you want to go to a different branch, back to
master for instance, and want to checkout the branch again you only need to type

command: git checkout <name of branch>

Tags, like branches, are all copied to your local repository when you clone.
Checking out a tag is similar to checking out a branch, but since tags only
point to a specific commit you do not need to create a local copy of the tag,
you only need to type

command: git checkout <name of tag>

**Comment by bmpersc** [comment]
The release branch has been created and develop has been made open to developers again. Still need to create the nightly testing for the branch.

**Comment by bmpersc** [comment]
nightly testing has been setup and the appropriate track setup in cdash.

**Comment by jwillenbring** [comment]
The 12.8 documentation has been generated, but I have not switched it to the default or added it to the list (which we shouldn't do until the release is ready).

**Comment by jwillenbring** [comment]
@bmpersc this can be closed, right?

**Comment by bmpersc** [comment]
Yes, the tarballs have been created and posted on Trilinos.org.
