### ISSUE TITLE
Tpetra configure warning about only one global ordinal type

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#4913]
@trilinos/tpetra 

I just noticed that all of the ATDM Trilinos builds, for example as shown [here](https://testing.sandia.gov/cdash-dev-view/viewConfigure.php?buildid=4892727), are generating the following configure warning:

```
CMake Warning at packages/tpetra/CMakeLists.txt:1176 (MESSAGE):
  Tpetra requires only one global ordinal, but more than one are set:
  {int;long long}.  Building with more than one global ordinal type in Tpetra
  is deprecated.
```

How do we avoid this in the ATDM Trilinos builds?

**Comment by mhoemmen** [comment]
@trilinos/tpetra @bartlettroscoe Setting `Tpetra_INST_INT_INT=OFF` should fix this.

**Comment by bartlettroscoe** [comment]
This question has been answered and the blocker issue #4915 has been added to the set of ATDM Trilinos GitHub issue.  Therefore, this issue can be closed.

Thanks @mhoemmen!
