### ISSUE TITLE
Anasazi: BSD license?

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#492]
@csiefer2 asked me to post this issue since he's having trouble logging into Github.

Customer requests BSD license for Anasazi, which reportedly has an LGPL license.

**Comment by jwillenbring** [comment]
@william76 I will reference this ticket during our conversation later.

**Comment by hkthorn** [comment]
@csiefer2 Yes, Anasazi can be BSD.  I believe only the headers in the code need to be changed.  I looked into this some time ago and do not remember the reason for it not being BSD before.

**Comment by jwillenbring** [comment]
@william76 has updated the appropriate files and the copyright admin has been informed about the updated license, so I am closing this ticket.
