### ISSUE TITLE
Compiling issue of MueLu with Trilinos 12.14.1

### ISSUE THREAD

**Issue by YingzhouLi** [trilinos/Trilinos#4927]
I am compiling Trilinos 12.14.1 on Ubuntu 18.04 with g++ 7.3 and matlab R2018a.

cmake \
     -D Trilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON  \
     -D Trilinos_ENABLE_Amesos:BOOL=ON \
     -D Trilinos_ENABLE_Amesos2:BOOL=ON \
     -D Amesos2_ENABLE_KLU2:BOOL=ON \
     -D Trilinos_ENABLE_AztecOO:BOOL=ON \
     -D Trilinos_ENABLE_Epetra:BOOL=ON \
     -D Trilinos_ENABLE_EpetraExt:BOOL=ON \
     -D Trilinos_ENABLE_Fortran:BOOL=OFF \
     -D Trilinos_ENABLE_Ifpack:BOOL=ON \
     -D Trilinos_ENABLE_Ifpack2:BOOL=ON \
     -D Trilinos_ENABLE_MueLu:BOOL=ON \
     -D MueLu_ENABLE_TESTS:STRING=ON \
     -D MueLu_ENABLE_EXAMPLES:STRING=OFF \
     -D Trilinos_ENABLE_Teuchos:BOOL=ON \
     -D Trilinos_ENABLE_Tpetra:BOOL=ON \
     -D Trilinos_ENABLE_Intrepid2:BOOL=ON \
     -D Trilinos_ENABLE_COMPLEX_DOUBLE=ON \
     -D Teuchos_ENABLE_COMPLEX=ON \
     -D TPL_ENABLE_MPI:BOOL=OFF \
     -D TPL_ENABLE_MATLAB:BOOL=ON \
     -D MATLAB_ROOT:STRING="/usr/local/MATLAB/R2018a/" \
     -D MATLAB_ARCH:STRING="glnxa64" \
     -D BUILD_SHARED_LIBS:BOOL=ON \
     -D CMAKE_CXX_FLAGS="-fPIC -g -DMEX_DOUBLE_HANDLE" \
     -D Trilinos_EXTRA_LINK_FLAGS="-lrt -lm -lgfortran" \
..

CMakeFiles/MueLu_UnitTests.dir/ParameterList/FactoryFactory.cpp.o: In function `MueLu::MatlabSmoother<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::Setup(MueLu::Level&)':
/home/yingzhou/Documents/Trilinos-trilinos-release-12-14-1/packages/muelu/test/unit_tests/../../src/../matlab/src/MueLu_MatlabSmoother_def.hpp:97: undefined reference to `MueLu::MuemexData<Teuchos::RCP<Xpetra::Matrix<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > > >::MuemexData(Teuchos::RCP<Xpetra::Matrix<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > >&)'
CMakeFiles/MueLu_UnitTests.dir/ParameterList/FactoryFactory.cpp.o: In function `MueLu::MatlabSmoother<std::complex<double>, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::Setup(MueLu::Level&)':
/home/yingzhou/Documents/Trilinos-trilinos-release-12-14-1/packages/muelu/test/unit_tests/../../src/../matlab/src/MueLu_MatlabSmoother_def.hpp:97: undefined reference to `MueLu::MuemexData<Teuchos::RCP<Xpetra::Matrix<std::complex<double>, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > > >::MuemexData(Teuchos::RCP<Xpetra::Matrix<std::complex<double>, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > >&)'
CMakeFiles/MueLu_UnitTests.dir/ParameterList/FactoryFactory.cpp.o: In function `MueLu::MatlabSmoother<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::Apply(Xpetra::MultiVector<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >&, Xpetra::MultiVector<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > const&, bool) const':
/home/yingzhou/Documents/Trilinos-trilinos-release-12-14-1/packages/muelu/test/unit_tests/../../src/../matlab/src/MueLu_MatlabSmoother_def.hpp:116: undefined reference to `MueLu::MuemexData<Teuchos::RCP<Xpetra::Matrix<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > > >::MuemexData(Teuchos::RCP<Xpetra::Matrix<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > >&)'
/home/yingzhou/Documents/Trilinos-trilinos-release-12-14-1/packages/muelu/test/unit_tests/../../src/../matlab/src/MueLu_MatlabSmoother_def.hpp:121: undefined reference to `MueLu::MuemexData<Teuchos::RCP<Xpetra::MultiVector<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > > >::MuemexData(Teuchos::RCP<Xpetra::MultiVector<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > >&)'
/home/yingzhou/Documents/Trilinos-trilinos-release-12-14-1/packages/muelu/test/unit_tests/../../src/../matlab/src/MueLu_MatlabSmoother_def.hpp:122: undefined reference to `MueLu::MuemexData<Teuchos::RCP<Xpetra::MultiVector<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > > >::MuemexData(Teuchos::RCP<Xpetra::MultiVector<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > >&)'
/home/yingzhou/Documents/Trilinos-trilinos-release-12-14-1/packages/muelu/test/unit_tests/../../src/../matlab/src/MueLu_MatlabSmoother_def.hpp:130: undefined reference to `MueLu::MuemexData<Teuchos::RCP<Xpetra::MultiVector<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > > >::getData()'
CMakeFiles/MueLu_UnitTests.dir/ParameterList/FactoryFactory.cpp.o: In function `MueLu::MatlabSmoother<std::complex<double>, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::Apply(Xpetra::MultiVector<std::complex<double>, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >&, Xpetra::MultiVector<std::complex<double>, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > const&, bool) const':
/home/yingzhou/Documents/Trilinos-trilinos-release-12-14-1/packages/muelu/test/unit_tests/../../src/../matlab/src/MueLu_MatlabSmoother_def.hpp:116: undefined reference to `MueLu::MuemexData<Teuchos::RCP<Xpetra::Matrix<std::complex<double>, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > > >::MuemexData(Teuchos::RCP<Xpetra::Matrix<std::complex<double>, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > >&)'
/home/yingzhou/Documents/Trilinos-trilinos-release-12-14-1/packages/muelu/test/unit_tests/../../src/../matlab/src/MueLu_MatlabSmoother_def.hpp:121: undefined reference to `MueLu::MuemexData<Teuchos::RCP<Xpetra::MultiVector<std::complex<double>, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > > >::MuemexData(Teuchos::RCP<Xpetra::MultiVector<std::complex<double>, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > >&)'
/home/yingzhou/Documents/Trilinos-trilinos-release-12-14-1/packages/muelu/test/unit_tests/../../src/../matlab/src/MueLu_MatlabSmoother_def.hpp:122: undefined reference to `MueLu::MuemexData<Teuchos::RCP<Xpetra::MultiVector<std::complex<double>, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > > >::MuemexData(Teuchos::RCP<Xpetra::MultiVector<std::complex<double>, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > >&)'
/home/yingzhou/Documents/Trilinos-trilinos-release-12-14-1/packages/muelu/test/unit_tests/../../src/../matlab/src/MueLu_MatlabSmoother_def.hpp:130: undefined reference to `MueLu::MuemexData<Teuchos::RCP<Xpetra::MultiVector<std::complex<double>, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > > >::getData()'
collect2: error: ld returned 1 exit status
packages/muelu/test/unit_tests/CMakeFiles/MueLu_UnitTests.dir/build.make:1421: recipe for target 'packages/muelu/test/unit_tests/MueLu_UnitTests.exe' failed
make[2]: *** [packages/muelu/test/unit_tests/MueLu_UnitTests.exe] Error 1
CMakeFiles/Makefile2:11396: recipe for target 'packages/muelu/test/unit_tests/CMakeFiles/MueLu_UnitTests.dir/all' failed
make[1]: *** [packages/muelu/test/unit_tests/CMakeFiles/MueLu_UnitTests.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by mhoemmen** [comment]
@YingzhouLi Try the latest (master) version of Trilinos, not the release.

@trilinos/muelu

**Comment by YingzhouLi** [comment]
Same configuration as above ends up with an error in muelu mex

In file included from /gtmp/yingzhou/local/Trilinos/packages/muelu/matlab/src/MueLu_SingleLevelMatlabFactory_def.hpp:55:0,
                 from /gtmp/yingzhou/local/Trilinos/packages/muelu/matlab/src/MueLu_SingleLevelMatlabFactory.cpp:50:
/gtmp/yingzhou/local/Trilinos/packages/muelu/matlab/src/MueLu_MatlabUtils_decl.hpp:118:60: error: ‘Scalar’ was not declared in this scope
 typedef Tpetra::MultiVector<typename Teuchos::ScalarTraits<Scalar>::magnitudeType, mm_LocalOrd, mm_GlobalOrd, mm_node_t> Tpetra_MultiVector_double;
                                                            ^
/gtmp/yingzhou/local/Trilinos/packages/muelu/matlab/src/MueLu_MatlabUtils_decl.hpp:118:66: error: template argument 1 is invalid
 typedef Tpetra::MultiVector<typename Teuchos::ScalarTraits<Scalar>::magnitudeType, mm_LocalOrd, mm_GlobalOrd, mm_node_t> Tpetra_MultiVector_double;
                                                                  ^
/gtmp/yingzhou/local/Trilinos/packages/muelu/matlab/src/MueLu_MatlabUtils_decl.hpp:118:120: error: template argument 1 is invalid
 typedef Tpetra::MultiVector<typename Teuchos::ScalarTraits<Scalar>::magnitudeType, mm_LocalOrd, mm_GlobalOrd, mm_node_t> Tpetra_MultiVector_double;
                                                                                                                        ^
/gtmp/yingzhou/local/Trilinos/packages/muelu/matlab/src/MueLu_MatlabUtils_decl.hpp:118:122: error: expected ‘::’ before ‘Tpetra_MultiVector_double’
 typedef Tpetra::MultiVector<typename Teuchos::ScalarTraits<Scalar>::magnitudeType, mm_LocalOrd, mm_GlobalOrd, mm_node_t> Tpetra_MultiVector_double;
                                                                                                                          ^
In file included from /gtmp/yingzhou/local/Trilinos/packages/muelu/matlab/src/MueLu_SingleLevelMatlabFactory_def.hpp:55:0,
                 from /gtmp/yingzhou/local/Trilinos/packages/muelu/matlab/src/MueLu_SingleLevelMatlabFactory.cpp:50:
/gtmp/yingzhou/local/Trilinos/packages/muelu/matlab/src/MueLu_MatlabUtils_decl.hpp:118:147: error: invalid type in declaration before ‘;’ token
 typedef Tpetra::MultiVector<typename Teuchos::ScalarTraits<Scalar>::magnitudeType, mm_LocalOrd, mm_GlobalOrd, mm_node_t> Tpetra_MultiVector_double;
                                                                                                                                                   ^
/gtmp/yingzhou/local/Trilinos/packages/muelu/matlab/src/MueLu_MatlabUtils_decl.hpp:125:60: error: ‘Scalar’ was not declared in this scope
 typedef Xpetra::MultiVector<typename Teuchos::ScalarTraits<Scalar>::magnitudeType, mm_LocalOrd, mm_GlobalOrd, mm_node_t> Xpetra_MultiVector_double;
                                                            ^
/gtmp/yingzhou/local/Trilinos/packages/muelu/matlab/src/MueLu_MatlabUtils_decl.hpp:125:66: error: template argument 1 is invalid
 typedef Xpetra::MultiVector<typename Teuchos::ScalarTraits<Scalar>::magnitudeType, mm_LocalOrd, mm_GlobalOrd, mm_node_t> Xpetra_MultiVector_double;
                                                                  ^
/gtmp/yingzhou/local/Trilinos/packages/muelu/matlab/src/MueLu_MatlabUtils_decl.hpp:125:120: error: template argument 1 is invalid
 typedef Xpetra::MultiVector<typename Teuchos::ScalarTraits<Scalar>::magnitudeType, mm_LocalOrd, mm_GlobalOrd, mm_node_t> Xpetra_MultiVector_double;
                                                                                                                        ^
/gtmp/yingzhou/local/Trilinos/packages/muelu/matlab/src/MueLu_MatlabUtils_decl.hpp:125:122: error: expected ‘::’ before ‘Xpetra_MultiVector_double’
 typedef Xpetra::MultiVector<typename Teuchos::ScalarTraits<Scalar>::magnitudeType, mm_LocalOrd, mm_GlobalOrd, mm_node_t> Xpetra_MultiVector_double;
                                                                                                                          ^
/gtmp/yingzhou/local/Trilinos/packages/muelu/matlab/src/MueLu_MatlabUtils_decl.hpp:125:147: error: invalid type in declaration before ‘;’ token
 typedef Xpetra::MultiVector<typename Teuchos::ScalarTraits<Scalar>::magnitudeType, mm_LocalOrd, mm_GlobalOrd, mm_node_t> Xpetra_MultiVector_double;
                                                                                                                                                   ^
make[2]: *** [packages/muelu/matlab/src/CMakeFiles/muelu-matlab.dir/MueLu_SingleLevelMatlabFactory.cpp.o] Error 1
make[1]: *** [packages/muelu/matlab/src/CMakeFiles/muelu-matlab.dir/all] Error 2
make: *** [all] Error 2

**Comment by csiefer2** [comment]
Yeah, that's a bug.  Working on a fix.

**Comment by csiefer2** [comment]
See #4941

**Comment by csiefer2** [comment]
My patch builds against R2017a (what I have handy) using a different set of configure options than yours.  Try the patch when you get a chance.  If you're still having issues, I'll install R2018a on my machine and then duplicate your configure options.  Just let me know.

**Comment by YingzhouLi** [comment]
Thank you @csiefer2 . Unfortunately, my first issue persist in the develop branch, where the #4941 is merged into.

**Comment by csiefer2** [comment]
Try adding: -D Tpetra_INST_INT_LONG_LONG=OFF .  That worked for me using develop and your cmake line.

We don't check Tpetra ETI types at configure time, but we should.  I'll patch the code to fail earlier (with a descriptive error message). #4966 

Thanks for bringing this to our attention!

**Comment by YingzhouLi** [comment]
Still no luck.

cmake \
-D Trilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON \
-D Trilinos_ENABLE_Amesos:BOOL=ON \
-D Trilinos_ENABLE_Amesos2:BOOL=ON \
-D Amesos2_ENABLE_KLU2:BOOL=ON \
-D Trilinos_ENABLE_AztecOO:BOOL=ON \
-D Trilinos_ENABLE_Epetra:BOOL=ON \
-D Trilinos_ENABLE_EpetraExt:BOOL=ON \
-D Trilinos_ENABLE_Fortran:BOOL=OFF \
-D Trilinos_ENABLE_Ifpack:BOOL=ON \
-D Trilinos_ENABLE_Ifpack2:BOOL=ON \
-D Trilinos_ENABLE_MueLu:BOOL=ON \
-D MueLu_ENABLE_TESTS:STRING=ON \
-D MueLu_ENABLE_EXAMPLES:STRING=OFF \
-D Trilinos_ENABLE_Teuchos:BOOL=ON \
-D Trilinos_ENABLE_Tpetra:BOOL=ON \
-D Trilinos_ENABLE_Intrepid2:BOOL=ON \
-D Trilinos_ENABLE_COMPLEX_DOUBLE=ON \
-D Teuchos_ENABLE_COMPLEX=ON \
-D Tpetra_INST_INT_LONG_LONG=OFF \
-D TPL_ENABLE_MPI:BOOL=OFF \
-D TPL_ENABLE_MATLAB:BOOL=ON \
-D MATLAB_ROOT:STRING="/usr/local/MATLAB/R2018a/" \
-D MATLAB_ARCH:STRING="glnxa64" \
-D BUILD_SHARED_LIBS:BOOL=ON \
-D CMAKE_CXX_FLAGS="-fPIC -g -DMEX_DOUBLE_HANDLE" \
-D Trilinos_EXTRA_LINK_FLAGS="-lrt -lm -lgfortran" \
..

../../src/Interface/libmuelu-interface.so.12.13: undefined reference to `std::vector<Teuchos::RCP<MueLu::MuemexArg>, std::allocator<Teuchos::RCP<MueLu::MuemexArg> > > MueLu::processNeeds<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >(MueLu::Factory const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, MueLu::Level&)'
../../src/Interface/libmuelu-interface.so.12.13: undefined reference to `MueLu::MuemexData<Teuchos::RCP<Xpetra::MultiVector<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > > >::getData()'
../../src/Interface/libmuelu-interface.so.12.13: undefined reference to `MueLu::MuemexData<Teuchos::RCP<Xpetra::Matrix<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > > >::MuemexData(Teuchos::RCP<Xpetra::Matrix<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > >&)'
../../src/Interface/libmuelu-interface.so.12.13: undefined reference to `MueLu::MuemexData<Teuchos::RCP<Xpetra::Matrix<std::complex<double>, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > > >::MuemexData(Teuchos::RCP<Xpetra::Matrix<std::complex<double>, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > >&)'
../../src/Interface/libmuelu-interface.so.12.13: undefined reference to `MueLu::tokenizeList(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
../../src/Interface/libmuelu-interface.so.12.13: undefined reference to `MueLu::MuemexData<Teuchos::RCP<Xpetra::MultiVector<std::complex<double>, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > > >::getData()'
../../src/Interface/libmuelu-interface.so.12.13: undefined reference to `MueLu::MuemexData<Teuchos::RCP<Xpetra::MultiVector<std::complex<double>, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > > >::MuemexData(Teuchos::RCP<Xpetra::MultiVector<std::complex<double>, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > >&)'
../../src/Interface/libmuelu-interface.so.12.13: undefined reference to `MueLu::callMatlab(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, std::vector<Teuchos::RCP<MueLu::MuemexArg>, std::allocator<Teuchos::RCP<MueLu::MuemexArg> > >)'
../../src/Interface/libmuelu-interface.so.12.13: undefined reference to `MueLu::MuemexData<Teuchos::RCP<Xpetra::MultiVector<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > > >::MuemexData(Teuchos::RCP<Xpetra::MultiVector<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > >&)'
../../src/Interface/libmuelu-interface.so.12.13: undefined reference to `void MueLu::processProvides<std::complex<double>, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >(std::vector<Teuchos::RCP<MueLu::MuemexArg>, std::allocator<Teuchos::RCP<MueLu::MuemexArg> > >&, MueLu::Factory const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, MueLu::Level&)'
../../src/Interface/libmuelu-interface.so.12.13: undefined reference to `MueLu::getInputParamList()'
../../src/Interface/libmuelu-interface.so.12.13: undefined reference to `void MueLu::processProvides<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >(std::vector<Teuchos::RCP<MueLu::MuemexArg>, std::allocator<Teuchos::RCP<MueLu::MuemexArg> > >&, MueLu::Factory const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, MueLu::Level&)'
../../src/Interface/libmuelu-interface.so.12.13: undefined reference to `std::vector<Teuchos::RCP<MueLu::MuemexArg>, std::allocator<Teuchos::RCP<MueLu::MuemexArg> > > MueLu::processNeeds<std::complex<double>, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >(MueLu::Factory const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, MueLu::Level&)'
collect2: error: ld returned 1 exit status
packages/muelu/test/maxwell/CMakeFiles/MueLu_Maxwell3D.dir/build.make:173: recipe for target 'packages/muelu/test/maxwell/MueLu_Maxwell3D.exe' failed
make[2]: *** [packages/muelu/test/maxwell/MueLu_Maxwell3D.exe] Error 1
CMakeFiles/Makefile2:15336: recipe for target 'packages/muelu/test/maxwell/CMakeFiles/MueLu_Maxwell3D.dir/all' failed
make[1]: *** [packages/muelu/test/maxwell/CMakeFiles/MueLu_Maxwell3D.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by csiefer2** [comment]
Drat.  Well, time to update my matlab to and try again.

**Comment by csiefer2** [comment]
If you turn of the MueLu Tests, does it generate the matlab file?

**Comment by YingzhouLi** [comment]
What do you mean "generate the matlab muelu file correctly"? The muemex.mexa64 is generated under the folder "../build/packages/muelu/matlab/bin"

**Comment by csiefer2** [comment]
Yes.  Because if you're trying to get the muemex.mexa64 file, then whether or not the MueLu tests build is kind of secondary :)

**Comment by YingzhouLi** [comment]
How should I check wehther matlab muelu is generated correctly?

**Comment by csiefer2** [comment]
If there's a muemex.mexa64 generated, then if you stick that guy in your matlab path, you should be able to access that (via muemex.m).

**Comment by YingzhouLi** [comment]
It turns out to be a compiler issue. I was using gcc 4.8 with matlab 2018a. Now I compiled it using GCC 7.2.0 with Matlab 2018a.

**Comment by YingzhouLi** [comment]
However, while running given muelu matlab tests in the package, I encountered the following error without any MPI enabled.

Kokkos allocation "DualView::modified_flags" is being deallocated after Kokkos::finalize was called
This behavior is incorrect Kokkos usage, and will crash in future releases
Kokkos allocation "MV::DualView" is being deallocated after Kokkos::finalize was called
This behavior is incorrect Kokkos usage, and will crash in future releases
Kokkos allocation "DualView::modified_flags" is being deallocated after Kokkos::finalize was called
This behavior is incorrect Kokkos usage, and will crash in future releases
Kokkos allocation "DualView::modified_flags" is being deallocated after Kokkos::finalize was called
This behavior is incorrect Kokkos usage, and will crash in future releases
Kokkos allocation "DualView::modified_flags" is being deallocated after Kokkos::finalize was called
This behavior is incorrect Kokkos usage, and will crash in future releases
Kokkos allocation "DualView::modified_flags" is being deallocated after Kokkos::finalize was called
This behavior is incorrect Kokkos usage, and will crash in future releases
Kokkos allocation "DualView::modified_flags" is being deallocated after Kokkos::finalize was called
This behavior is incorrect Kokkos usage, and will crash in future releases
Kokkos allocation "MV::DualView" is being deallocated after Kokkos::finalize was called
This behavior is incorrect Kokkos usage, and will crash in future releases
Kokkos allocation "DualView::modified_flags" is being deallocated after Kokkos::finalize was called
This behavior is incorrect Kokkos usage, and will crash in future releases
Kokkos allocation "DualView::modified_flags" is being deallocated after Kokkos::finalize was called
This behavior is incorrect Kokkos usage, and will crash in future releases
Kokkos allocation "DualView::modified_flags" is being deallocated after Kokkos::finalize was called
This behavior is incorrect Kokkos usage, and will crash in future releases
Kokkos allocation "DualView::modified_flags" is being deallocated after Kokkos::finalize was called
This behavior is incorrect Kokkos usage, and will crash in future releases
Kokkos allocation "Tpetra::CrsMatrix::val" is being deallocated after Kokkos::finalize was called
This behavior is incorrect Kokkos usage, and will crash in future releases
Kokkos allocation "Tpetra::CrsGraph::ptr" is being deallocated after Kokkos::finalize was called
This behavior is incorrect Kokkos usage, and will crash in future releases
Kokkos allocation "Tpetra::CrsGraph::ind" is being deallocated after Kokkos::finalize was called
This behavior is incorrect Kokkos usage, and will crash in future releases
WARNING: Tpetra::Map destructor (~Map()) is being called after Kokkos::finalize() has been called.  This is user error!  There are two likely causes: 
  1. You have a static Tpetra::Map (or RCP or shared_ptr of a Map)
  2. You declare and construct a Tpetra::Map (or RCP or shared_ptr of a Tpetra::Map) at the same scope in main() as Kokkos::finalize() or Tpetra::finalize().
