### ISSUE TITLE
Link problems with libmuelu breaking most ATDM Trilinos builds starting 4/17/2019

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#4929]
CC: @trilinos/muelu , @srajama1 (Trilinos Linear Solvers Product Lead), @bartlettroscoe, @fryeguy52

<Checklist>
<???: Add label "client: ATDM">
<???: Add label "ATDM Sev: Blocker" (by default but could be other "ATDM Sev: XXX")>
<???: Add label "type: bug"?>
<???: Add label for affected packages (e.g. "pkg: MueLu", "pkg: Tpetra", "pkg: Kokkos", etc.)>
<???: Add label "PA: ???Project Area???" (e.g. "PA: Linear Solvers", "PA: Data Services")>
<???: Add milestone "Initial cleanup of new ATDM ..." or "Keep promoted ATDM ...">
<???: Once GitHub Issue is created, add entries for tests to TrilinosATDMStatus/*.csv files>

## Next Action Status

<status-and-or-first-action>

## Description

As shown in [this query](https://testing.sandia.gov/cdash-dev-view/index.php?project=Trilinos&date=2019-04-17&filtercount=1&showfilters=1&field1=buildname&compare1=65&value1=Trilinos-atdm-) there are link errors related to the muelu library.  For example, as shown [here](https://testing.sandia.gov/cdash-dev-view/viewBuildError.php?buildid=4904861) it shows link errors like:

```
packages/muelu/src/libmuelu.a(MueLu_CoalesceDropFactory.cpp.o):(.rodata._ZTVN5MueLu7LWGraphIixN6Kokkos6Compat23KokkosDeviceWrapperNodeINS1_6OpenMPENS1_9HostSpaceEEEEE[_ZTVN5MueLu7LWGraphIixN6Kokkos6Compat23KokkosDeviceWrapperNodeINS1_6OpenMPENS1_9HostSpaceEEEEE]+0xa8): undefined reference to `MueLu::LWGraph<int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP, Kokkos::HostSpace> >::print(Teuchos::basic_FancyOStream<char, std::char_traits<char> >&, int) const'
packages/muelu/src/libmuelu.a(MueLu_CoalesceDropFactory.cpp.o):(.rodata._ZTVN5MueLu5GraphIixN6Kokkos6Compat23KokkosDeviceWrapperNodeINS1_6OpenMPENS1_9HostSpaceEEEEE[_ZTVN5MueLu5GraphIixN6Kokkos6Compat23KokkosDeviceWrapperNodeINS1_6OpenMPENS1_9HostSpaceEEEEE]+0xa8): undefined reference to `MueLu::Graph<int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP, Kokkos::HostSpace> >::print(Teuchos::basic_FancyOStream<char, std::char_traits<char> >&, int) const'
packages/muelu/src/libmuelu.a(MueLu_CoalesceDropFactory.cpp.o):(.rodata._ZTVN5MueLu7LWGraphIiiN6Kokkos6Compat23KokkosDeviceWrapperNodeINS1_6OpenMPENS1_9HostSpaceEEEEE[_ZTVN5MueLu7LWGraphIiiN6Kokkos6Compat23KokkosDeviceWrapperNodeINS1_6OpenMPENS1_9HostSpaceEEEEE]+0xa8): undefined reference to `MueLu::LWGraph<int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP, Kokkos::HostSpace> >::print(Teuchos::basic_FancyOStream<char, std::char_traits<char> >&, int) const'
packages/muelu/src/libmuelu.a(MueLu_CoalesceDropFactory.cpp.o):(.rodata._ZTVN5MueLu5GraphIiiN6Kokkos6Compat23KokkosDeviceWrapperNodeINS1_6OpenMPENS1_9HostSpaceEEEEE[_ZTVN5MueLu5GraphIiiN6Kokkos6Compat23KokkosDeviceWrapperNodeINS1_6OpenMPENS1_9HostSpaceEEEEE]+0xa8): undefined reference to `MueLu::Graph<int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP, Kokkos::HostSpace> >::print(Teuchos::basic_FancyOStream<char, std::char_traits<char> >&, int) const'
collect2: error: ld returned 1 exit status
```
 
## Steps to Reproduce

One should be able to reproduce this failure on many of the systems as described in:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md

**Comment by bartlettroscoe** [comment]
I have already been in contact with @jhux2 about how to fix this.

@trilinos/framework,

Looks like we have a pretty big gap in PR testing.  Looks like we need to have one of the PR builds be a static library build.  From looking at the build [Trilinos-atdm-sems-rhel6-gnu-7.2.0-openmp-release-debug](https://testing.sandia.gov/cdash-dev-view/index.php?project=Trilinos&parentid=4904594) it seems a static SEMS-based build would have caught this.   I will create a GitHub issue for this to update one of the Trilinos PR builds to be a static lib build.

**Comment by jhux2** [comment]
Reported already in #4925, fix in PR #4926.

**Comment by bartlettroscoe** [comment]
CC: @bathmatt 

@jhux2, PR #4926 is broken as these libs have circular dependences?  Can we go ahead and back out the branch merged in PR #4905 for now and fix this problem offline?

**Comment by bartlettroscoe** [comment]
CC: @srajama1, @bathmatt 

@jhux2, how far back do we have to go to back out these breaking changes for now?  Since this is bringing down all of our builds it seems that backing out the original split of the MueLU libraries is the way to go.  Then we can carefully get the splitting to work offline.

As this as brought down almost all of our ATDM Trilinos builds, I have marked this [`ATDM Sev: Critical`](https://snl-wiki.sandia.gov/display/CoodinatedDevOpsATDM/ATDM-Specific+Trilinos+GitHub+Labels#ATDM-SpecificTrilinosGitHubLabels-LabelsforSeverity/Criticality)

**Comment by jjellio** [comment]
@bartlettroscoe 

Trilinos could avoid alot of the link line headaches if Tribits would place Trilinos' libs within a linker group. (this is what MKL does). `-Wl,--start-group ... libraries -Wl,--end-group`.  The linker will automatically search the group repeatedly for symbols before moving on.

I tried to coerce Trilinos to use linker groups for some TPLs, but within the CMake magic, there is logic  that translates commas into semicolons.  That breaks all options (Assembler `-Wa,`, linker `-Wl,` , and any thing that contain a comma). Raw CMake allows this FYI, find_library just keeps anything that starts with a hyphen as is.

Linker groups also drastically reduce the link line size.

**Comment by bartlettroscoe** [comment]
@jjellio said:

> Linker groups also drastically reduce the link line size.

We should meet offline and discuss this some so I can understand the issues here.

**Comment by jhux2** [comment]
@bartlettroscoe I've updated PR #4926.  Please review.

**Comment by bartlettroscoe** [comment]
Updated PR #4926 just merged to 'develop'.

Putting this in review awaiting results on CDash ...

**Comment by bartlettroscoe** [comment]
@jhux2, after the merge of PR #4926 it looks like there are still link problems on some platforms with some builds as shown [here](https://testing.sandia.gov/cdash-dev-view/index.php?project=Trilinos&date=2019-04-18&filtercount=2&showfilters=1&filtercombine=and&field1=subprojects&compare1=93&value1=MueLu&field2=buildname&compare2=65&value2=Trilinos-atdm-).  Looks like this is occurring in all the the 'sems-rhel6' builds so you can reproduce on any SNL COE RHEL6 system as described at:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#sems-rhel6-environment

Just use any of the build names you see [here](https://testing.sandia.gov/cdash-dev-view/index.php?project=Trilinos&date=2019-04-18&filtercount=2&showfilters=1&filtercombine=and&field1=subprojects&compare1=93&value1=MueLu&field2=buildname&compare2=65&value2=Trilinos-atdm-sems-rhel6-).

Don't know why some platforms show problems and not others.

**Comment by jhux2** [comment]
@bartlettroscoe For the time being, it's probably easiest to just back out these merge commits:

b02c94efdcc8a
d24004c859

What's the exact command to do this?  `git revert` is asking for a parent ....

**Comment by bartlettroscoe** [comment]
@jhux2, you just need to revert these merge commits in reverse order.  Do this:

```
$ cd Trilinos/
$ git checkout develop
$ git pull
$ git checkout -b 4929-revert-muelu-multi-lib-merges
$ git revert -m 1 b02c94efdcc8a7ccf35a53944b1c56f82fb7445b
$ git revert -m 1 d24004c8594c93e4a01bfe4feea1d3b62956d8ba
```

and then push the branch `d24004c8594c93e4a01bfe4feea1d3b62956d8ba` to your fork and create a new PR.

NOTE: It is silly but you have to pass in the `-m 1` argument to the `git revert` command to tell git to go back to the "first parent" (which is on the trunk of the 'develop' branch).  If you look at your git first-parent history (i.e. `git log --first-parent`) and then run `git log --pretty=fuller -1` on these two merge commits, you can see which commit is first parent.  And after each revert commit you can carefully check the diffs from the merge by using `git log -m --name-status`.  That will make clear which files are changed w.r.t. to each ancestor.

**Comment by jhux2** [comment]
@bartlettroscoe Thanks.  Meantime, I found the issue, new PR coming shortly.

**Comment by bartlettroscoe** [comment]
@jhux2 said:

> Meantime, I found the issue, new PR coming shortly.

You were able to reproduce the link errors shown on CDash on a sems-rhel6 machine?  NOTE: We are also seeing the same problem with the Intel builds on 'serrano' and 'chama' too.

**Comment by jhux2** [comment]
Yes.  See PR #4950.

**Comment by bartlettroscoe** [comment]
With the merge of PR #4950, we can put this in review again.  Crossing finger for tomorrow :-)

**Comment by bartlettroscoe** [comment]
CC: @mhoward, @bathmatt

As shown [in the ATDM Trilinos builds on 2019-04-19](https://testing.sandia.gov/cdash-dev-view/index.php?project=Trilinos&date=2019-04-19&filtercount=1&showfilters=1&field1=buildname&compare1=65&value1=Trilinos-atdm-) all of the Muelu-related build errors are gone.

Closing as complete.
