### ISSUE TITLE
Add support for atdm/load-env.sh <build-name> <custom-config-dir>

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#4933]
## Description

This story is to scope out and implement a scheme to allow users and developers to extend the ATDM Trilinos configuration to support new systems without having to touch anything in the Trilinos source tree.  This would make the ATDM Trilinos configuration system satisfy the "Open-Closed Principle" (i.e. open to extension, closed to modification).

This has been requested both by EMPIRE and SPARC PIs.

## Proposed Solution

One idea I had is support this is to allow a second argument like:

```
$ source ~/workspace/Trilinos/cmake/std/atdm/load-env.sh \
   gnu-openmp-opt  ~/my_tril_config
```

which would require that the file:

```
~/my_tril_config/environment.sh
```
    
exists and be set up correctly (lots of examples under `Trilinos/cmake/std/atdm/`).

The top directory name (in this example `my_tril_config`) would be set as the system name in the places that need that name.

**Comment by bartlettroscoe** [comment]
CC: @fryeguy52 

@bathmatt,

I have a prototype for this in PR #5705.  Can you please take a look at:

* https://github.com/trilinos/Trilinos/pull/5705/files#diff-3b922030112cdbaf917bd43ba1f4f5a7

Can we talk through this briefly over Skype?

**Comment by bathmatt** [comment]
Not seeing my comments, huh, remaking them now.

I’ll try this tomorrow on waterman, 

Don’t think skype is needed yet, couple questions though

Vars like shared, rdc opt, are they respected?  Do I need to handle these..

**Comment by bartlettroscoe** [comment]
@bathmatt asked:

> Vars like shared, rdc opt, are they respected? Do I need to handle these?

All of the keywords that are parsed out of the build name are automatically handled in the script:

* [Trilinos/cmake/std/atdm/utils/set_build_options.sh](https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/utils/set_build_options.sh)

which sets env vars prefixed with `ATDM_CONFIG_` that are read in by `ATDMDevEnvSettings.cmake`.  That script gets called before your `<custom-config-dir>/environment.sh` script is sourced.

Your `<custom-config-dir>/environment.sh` script need to point to compilers, TPLs, MPI, etc. or any other bit of information that can't be parsed out of the build name by `set_build_options.sh`.  The driver script is hopefully not that complex to see this:

* [Trilinos/cmake/std/atdm/load-env.sh](https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/load-env.sh)

**Comment by bartlettroscoe** [comment]
@bathmatt,

How do we handle installs of Trilinos with this approach?  Two options that come to mind are:

1) Copy the directory `<custom-config-dir>` under the installed Trilinos directory and have installed `load_matching_env.sh` source the copied`<custom-config-dir>/environment.sh` scirpt.  That would require the `<custom-config-dir>/environment.sh` script to work with even when copied but would make older installs of Trilinos using this approach robust (as long as the underlying compilers and TPLs being pointed to did not change).

2) Have the installed `load_matching_env.sh` script point to the original `<custom-config-dir>` directory.  That would be more fragile as changes in `<custom-config-dir>/environment.sh` would break older installs of Trilinos.

My preference would be for option-1.  What do you think about that?

**Comment by bartlettroscoe** [comment]
I talked with @bathmatt and he confirmed that he likes option-1 defined [above](https://github.com/trilinos/Trilinos/issues/4933#issuecomment-521278214) where the `<custom-config-dir>` is copied into the Trilinos install tree.  Therefore, this is what I will implement.

**Comment by bathmatt** [comment]
will the load matching env auto load that configuration file??

**Comment by bartlettroscoe** [comment]
@bathmatt asked:

> will the load matching env auto load that configuration file??

Yes.  Let me get the updated version pushed to the branch so you can try out.  (Was in meetings all day yesterday.)

**Comment by bartlettroscoe** [comment]
@bathmatt, PR #5705 should be complete.  Just needs to be reviewed and approved and merged.

**Comment by bartlettroscoe** [comment]
@bathmatt, PR #5705 was just merged.  Please see the updated documentation at:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#custom-systems-and-configurations

Please provide a comment here if this is working as you expect.

Putting this in review waiting for feedback.

**Comment by bartlettroscoe** [comment]
Below are some notes for the development of this feature (for future reference).

<details>

<summary><b>DETAILED NOTES:</b> (click to expand)</summary>

.

**TASKS:**

ToDo:

* Create branch '4933-atdm-custom-env' [Done]

* Create Trilinos/cmake/std/atdm/examples/my_sems_rhel6_config/environment.sh skeleton [Done]

* Add hooks in Trilinos/cmake/std/atdm/load-env.sh to pick up custom dir:
  - Add new var ATDM_CONFIG_SYSTEM_DIR and use that to access all of the env stuff [Done]

* Fill out my_sems_rhel6_config/environment.sh until it can configure Trilinos (and perhaps update ATDMDevEnvSettings.cmake to make defaults easier):
  - Set up ATDMDevEnvSetting.cmake to just require <TPL>_ROOT set by default that works on SEMS RHEL systems [Done]
  - Rest of setup [Done]

* Test a configuration with Kokkos, Teuchos and SEACAS ... Passed [Done]

* Create commits [Done]

* Post WIP PR for '4933-atdm-custom-env' and ask Matt B. to comment on this [Done]

* Ask about how this is supposed to work for installs of Trilinos (e.g. copy the 'my-custom-config' directory into the Trilinos install directory)? [Done]

* Implement copy of `<custom-config-dir>` into Trilinos install tree and test with simple install of Trilinos (with just Kokkos) ... IN PROGRESS ...

* Test install with custom config and with standard config and make sure both work:
  - Test with custom config ... Passed [Done]
  - Test with standard config ... Passed [Done] 

* Refactor to clean stuff up:
  - Rename 'ATDM_CONFIG_KNOWN_SYSTEM_NAME' to 'ATDM_CONFIG_SYSTEM_NAME'  [Done]
  - Rename 'ATDM_CONFIG_KNOWN_HOSTNAME' to 'ATDM_CONFIG_CDASH_HOSTNAME' [Done]
  - Rename file 'get_known_system_name.sh' to 'get_known_system_info.sh' [Done]

* Test out updated 'sems-rhel6' env to make sure that it works [Done]

* Test submit on 'sems-rhel6' to CDash to make sure nothing is broken [Done]

* Add documentation for `<custom-config-dir>` [Done]

* Add support for custom env using env var ATDM_CONFIG_REGISTER_CUSTOM_SYSTEM_CONFIG_DIR:
  - Implement ATDM_CONFIG_REGISTER_CUSTOM_SYSTEM_CONFIG_DIR support and do some basic testing [Done]
  - Factor out atdm/utils/get_system_info.sh and eliminate duplication [Done]
  - Use atdm/utils/get_system_info.sh instead of atdm/utils/get_system_info.sh [Done]
  - Update documentation [Done]

* Rename example from 'my_sems_rhel6_config' to 'my-sems-rhel6-config' [Done]

* Test out updated 'sems-rhel6' and 'my_sems_rhel6_config' env using checkin-test-atdm.sh to make sure that everything works [Done]

* Remove updated file atdm/sems-rhel6/environment.sh from commit 15177a1 "Install custom config dir (#4933)" and put in its own commit [Done]

* Force push updated branch in PR, remove 'WIP' and add 'AT: AUTOMERGE'  [Done]

* Do more complete testing [Done]

**DETAILED LOG**

**(8/13/2019)**

At the ATDM PI meeting yesterday, @bathmatt stated that this was a top priority for EMPIRE work on ATS-2 and other systems where they want to set up there own envs and be able to use the ATDM Trilinos configuration.

I need to get something together as quickly as I can. The easiest thing that I can do is to just copy the 'sems-rhel6' env and create:


```
Trilinos/cmake/std/atdm/examples/my_sems_rhel6_config/
  environment.sh
```

This will just just one hard-coded env and that is it.  Let's see how easy we can make this.

I have a basic custom configuration working with:

```
$ cd ~/Trilinos.base/BUILDS/ATDM/CUSTOM_ENV/gnu-opt-openmp/

$ source ~/Trilinos.base/Trilinos/cmake/std/atdm/load-env.sh gnu-opt-openmp \
  ~/Trilinos.base/Trilinos/cmake/std/atdm/examples/my_sems_rhel6_config

$ cat do-configure
cmake \
-G Ninja \
-D Trilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
"$@" \
$HOME/Trilinos.base/Trilinos

$ rm -r CMake*

$ time ./do-configure -DTrilinos_ENABLE_TESTS=ON \
  -DTrilinos_ENABLE_Kokkos=ON -DTrilinos_ENABLE_Teuchos=ON -DTrilinos_ENABLE_SEACAS=ON \
  &> configure.out

real    0m8.355s
user    0m5.522s
sys     0m2.528s

$ time ninja -j20 &> make.out

real    2m8.571s
user    37m58.212s
sys     3m2.960s

$ time ctest -j20 &> ctest.out

real    1m26.750s
user    2m54.565s
sys     0m22.646s
```

I created PR #5705 with these commits.  Matt looked at it and said he thought that it looked reasonable and he would try it out soon.

**(8/14/2019)**

Got some feedback from Matt:

```
> From: Bettencourt, Matthew
> Sent: Wednesday, August 14, 2019 10:01 AM
> To: Bartlett, Roscoe A
> Subject: your cmake stuff
> 
> So,
> 
> I have it somewhat working, I can load-matching-env, it loads modules and
> then I can configure, it starts to build but it can't find -lcurl.
> 
> It is needed by netcdf. is there to add a lib search path for curl?
> 
> Also, it is the trilinos automagic stuff bringing curl in, can I stop that?  my
> config doesn't need curl..
```

But later he got it to work (by defining the full set of netcdf libs).

I talked with him and he said he would like the system to copy the `<custom-config-dir>` into the Trilinos install tree so that is what I will implement ...

**(8/15/2019)**

I added support for copying the custom config dir.  I tested this with:

```
$ cd ~/Trilinos.base/BUILDS/ATDM/CUSTOM_ENV/gnu-opt-openmp/

$ source ~/Trilinos.base/Trilinos/cmake/std/atdm/load-env.sh gnu-opt-openmp \
  ~/Trilinos.base/Trilinos/cmake/std/atdm/examples/my_sems_rhel6_config
Setting compiler and build options for build-name 'gnu-opt-openmp'
Using my custom SEMS RHEL6 env for compiler stack GNU to build RELEASE code with Kokkos node type OPENMP

$ cat do-configure
cmake \
-G Ninja \
-D Trilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
"$@" \
$HOME/Trilinos.base/Trilinos

$ rm -r CMake* install

$ time ./do-configure -DCMAKE_INSTALL_PREFIX=install \
  -DTrilinos_ENABLE_TESTS=OFF -DTrilinos_ENABLE_Kokkos=ON \
  &> configure.out

real    0m4.008s
user    0m2.447s
sys     0m1.318s

$ time ninja -j20 &> make.out

real    0m0.014s
user    0m0.008s
sys     0m0.005s

$ time ninja -j20 install &> make.install.out

real    0m0.073s
user    0m0.023s
sys     0m0.048s
```

This installed:

```
$ cat install/load_matching_env.sh 
# Source this script to load the env that was used to build this version of
# Trilinos and also load env vars that describe what was built.

source /ascldap/users/rabartl/Trilinos.base/BUILDS/ATDM/CUSTOM_ENV/gnu-opt-openmp/install/share/atdm-trilinos/load-env.sh gnu-opt-openmp /ascldap/users/rabartl/Trilinos.base/BUILDS/ATDM/CUSTOM_ENV/gnu-opt-openmp/install/share/atdm-trilinos/my_sems_rhel6_config

export ATDM_TRILINOS_INSTALL_PREFIX=/ascldap/users/rabartl/Trilinos.base/BUILDS/ATDM/CUSTOM_ENV/gnu-opt-openmp/install
export PATH=/ascldap/users/rabartl/Trilinos.base/BUILDS/ATDM/CUSTOM_ENV/gnu-opt-openmp/install/bin:${PATH}

$  ls install/share/atdm-trilinos/my_sems_rhel6_config/
environment.sh
```

And testing the load of the env with:

```
$ module purge

$ which gcc
/home/vera_env/gcc-4.8.3/toolset/gcc-4.8.3/bin/gcc

$ . install/load_matching_env.sh 
Setting compiler and build options for build-name 'gnu-opt-openmp'
Using my custom SEMS RHEL6 env for compiler stack GNU to build RELEASE code with Kokkos node type OPENMP

$ which gcc
/projects/sems/install/rhel6-x86_64/sems/compiler/gcc/7.2.0/base/bin/gcc

$ which cmake
/projects/sems/install/rhel6-x86_64/sems/utility/cmake/3.12.2/bin/cmake
```

That looks correct.

Also, need to test this with a known supported system with:

```
$ source ~/Trilinos.base/Trilinos/cmake/std/atdm/load-env.sh gnu-opt-openmp
Hostname 'crf450.srn.sandia.gov' matches known ATDM host 'sems-rhel6' and system 'sems-rhel6'
Setting compiler and build options for build-name 'gnu-opt-openmp'
Using SEMS RHEL6 compiler stack GNU-7.2.0 to build RELEASE code with Kokkos node type OPENMP

$ rm -r CMake* install

$ ./do-configure -DCMAKE_INSTALL_PREFIX=install \
  -DTrilinos_ENABLE_TESTS=OFF -DTrilinos_ENABLE_Kokkos=ON \
  &> configure.out

$ ninja -j20 &> make.out

$ ninja -j20 install &> make.install.out
```

which installed:

```
$ cat install/load_matching_env.sh 
# Source this script to load the env that was used to build this version of
# Trilinos and also load env vars that describe what was built.

source /ascldap/users/rabartl/Trilinos.base/BUILDS/ATDM/CUSTOM_ENV/gnu-opt-openmp/install/share/atdm-trilinos/load-env.sh gnu-opt-openmp 

export ATDM_TRILINOS_INSTALL_PREFIX=/ascldap/users/rabartl/Trilinos.base/BUILDS/ATDM/CUSTOM_ENV/gnu-opt-openmp/install
export PATH=/ascldap/users/rabartl/Trilinos.base/BUILDS/ATDM/CUSTOM_ENV/gnu-opt-openmp/install/bin:${PATH}

$ ls install/share/atdm-trilinos/sems-rhel6/
all_supported_builds.sh  environment.sh  tweaks
```

and testing the load with:

```
$ module purge

$ which gcc
/home/vera_env/gcc-4.8.3/toolset/gcc-4.8.3/bin/gcc

. install/load_matching_env.sh 
Hostname 'crf450.srn.sandia.gov' matches known ATDM host 'sems-rhel6' and system 'sems-rhel6'
Setting compiler and build options for build-name 'gnu-opt-openmp'
Using SEMS RHEL6 compiler stack GNU-7.2.0 to build RELEASE code with Kokkos node type OPENMP

$ which gcc
/projects/sems/install/rhel6-x86_64/sems/compiler/gcc/7.2.0/base/bin/gcc
```

That looks correct.

Now to cleanup and add documentation.

Some refactorings I would like to do:

- Rename 'ATDM_CONFIG_KNOWN_SYSTEM_NAME' to 'ATDM_CONFIG_SYSTEM_NAME' (since the system name can be from a custom configuration so it is not "known")
- Rename 'ATDM_CONFIG_KNOWN_HOSTNAME' to 'ATDM_CONFIG_CDASH_HOSTNAME' (since this is what this is actually used for)
- Rename file 'get_known_system_name.sh' to 'get_known_system_info.sh' (since more than just the system name is determined)

I also added support for env var ATDM_CONFIG_REGISTER_CUSTOM_SYSTEM_CONFIG_DIR and tested this with:

```
$ cd ~/Trilinos.base/BUILDS/ATDM/SEMS-RHEL6/CHECKIN/

$ export ATDM_CONFIG_REGISTER_CUSTOM_CONFIG_DIR=~/Trilinos.base/Trilinos/cmake/std/atdm/examples/my-sems-rhel6-config

$ ./checkin-test-atdm.sh \
  sems-rhel6-gnu-7.2.0-openmp-opt-dbg \
  my-sems-rhel6-config-gnu-openmp-opt-dbg \
  --enable-packages=Kokkos --local-do-all

***
*** ./checkin-test-atdm.sh  sems-rhel6-gnu-7.2.0-openmp-opt-dbg my-sems-rhel6-config-gnu-openmp-opt-dbg --enable-packages=Kokkos --local-do-all
***

ATDM_TRILINOS_DIR = '/home/rabartl/Trilinos.base/Trilinos/cmake/std/atdm/../../..'

Load some env to get python, cmake, etc ...

Hostname 'crf450.srn.sandia.gov' matches known ATDM host 'sems-rhel6' and system 'sems-rhel6'
Setting compiler and build options for build-name 'default'
Using SEMS RHEL6 compiler stack GNU-7.2.0 to build DEBUG code with Kokkos node type SERIAL
File local-checkin-test-defaults.py already exists, leaving it!

Running configure, build, and/or testing for 2 builds:
    sems-rhel6-gnu-7.2.0-openmp-opt-dbg
    my-sems-rhel6-config-gnu-openmp-opt-dbg


***
*** 0) Process build case sems-rhel6-gnu-7.2.0-openmp-opt-dbg
***

Hostname 'crf450.srn.sandia.gov' matches known ATDM host 'sems-rhel6' and system 'sems-rhel6'
Setting compiler and build options for build-name 'sems-rhel6-gnu-7.2.0-openmp-opt-dbg'
Using SEMS RHEL6 compiler stack GNU-7.2.0 to build RELEASE-DEBUG code with Kokkos node type OPENMP

Running: checkin-test.py --st-extra-builds=sems-rhel6-gnu-7.2.0-openmp-opt-dbg ...

  ==> See output file checkin-test.sems-rhel6-gnu-7.2.0-openmp-opt-dbg.out

+ /home/rabartl/Trilinos.base/Trilinos/cmake/std/atdm/../../../cmake/tribits/ci_support/checkin-test.py '--make-options=-j 20' '--ctest-options=-j 10' --st-extra-builds=sems-rhel6-gnu-7.2.0-openmp-opt-dbg --default-builds= --allow-no-pull --send-email-to= --test-categories=NIGHTLY --ctest-timeout=600 --enable-packages=Kokkos --local-do-all --use-ninja --log-file=checkin-test.sems-rhel6-gnu-7.2.0-openmp-opt-dbg.out
+ ATDM_CHT_SINGLE_RETURN_CODE=0
+ set +x
sems-rhel6-gnu-7.2.0-openmp-opt-dbg: PASSED!

***
*** 1) Process build case my-sems-rhel6-config-gnu-openmp-opt-dbg
***

Selecting custom system configuration 'my-sems-rhel6-config'
Setting compiler and build options for build-name 'my-sems-rhel6-config-gnu-openmp-opt-dbg'
Using my custom SEMS RHEL6 env for compiler stack GNU to build RELEASE-DEBUG code with Kokkos node type OPENMP

Running: checkin-test.py --st-extra-builds=my-sems-rhel6-config-gnu-openmp-opt-dbg ...

  ==> See output file checkin-test.my-sems-rhel6-config-gnu-openmp-opt-dbg.out
+ /home/rabartl/Trilinos.base/Trilinos/cmake/std/atdm/../../../cmake/tribits/ci_support/checkin-test.py '--make-options=-j 20' '--ctest-options=-j 1' --st-extra-builds=my-sems-rhel6-config-gnu-openmp-opt-dbg --default-builds= --allow-no-pull --send-email-to= --test-categories=NIGHTLY --ctest-timeout=600 --enable-packages=Kokkos --local-do-all --use-ninja --log-file=checkin-test.my-sems-rhel6-config-gnu-openmp-opt-dbg.out
+ ATDM_CHT_SINGLE_RETURN_CODE=0
+ set +x
my-sems-rhel6-config-gnu-openmp-opt-dbg: PASSED!

Collect and report final results:

  ==> See output file checkin-test.final.out


--------------------------------



PASSED (NOT READY TO PUSH): Trilinos: crf450.srn.sandia.gov

Fri Aug 16 09:48:29 MDT 2019

Enabled Packages: Kokkos

Build test results:
-------------------
0) MPI_RELEASE_DEBUG_SHARED_PT_OPENMP => Test case MPI_RELEASE_DEBUG_SHARED_PT_OPENMP was not run! => Does not affect push readiness! (-1.00 min)
1) sems-rhel6-gnu-7.2.0-openmp-opt-dbg => passed: passed=27,notpassed=0 (0.39 min)
2) my-sems-rhel6-config-gnu-openmp-opt-dbg => passed: passed=27,notpassed=0 (2.75 min)

A current successful pull does *not* exist => Not ready for final push!

Explanation: In order to safely push, the local working directory needs
to be up-to-date with the global repo or a full integration has not been
performed!


REQUESTED ACTIONS: PASSED
```

I think this looks good.

I also ran a CDash submit with the CTest -S driver with:

```
$ cd ~/Trilinos.base/BUILDS/ATDM/SEMS-RHEL6/CTEST_S/

$  env Trilinos_PACKAGES=Kokkos,Teuchos \
  ./ctest-s-local-test-driver.sh \
  sems-rhel6-gnu-7.2.0-openmp-release

***
*** ./ctest-s-local-test-driver.sh
***

ATDM_TRILINOS_DIR = '/home/rabartl/Trilinos.base/Trilinos'

Load some env to get python, cmake, etc ...

Hostname 'crf450.srn.sandia.gov' matches known ATDM host 'sems-rhel6' and system 'sems-rhel6'
Setting compiler and build options for build-name 'default'
Using SEMS RHEL6 compiler stack GNU-7.2.0 to build DEBUG code with Kokkos node type SERIAL

Running builds:
    sems-rhel6-gnu-7.2.0-openmp-release


Running Jenkins driver Trilinos-atdm-sems-rhel6-gnu-7.2.0-openmp-release.sh ...

Creating directory: Trilinos-atdm-sems-rhel6-gnu-7.2.0-openmp-release
Creating directory: SRC_AND_BUILD

real    2m49.062s
user    30m3.312s
sys     2m10.671s
```

which submitted just fine to:

* https://testing-dev.sandia.gov/cdash/index.php?project=Trilinos&parentid=4795002

So I think testing is complete.

</details>

**Comment by bartlettroscoe** [comment]
FYI: I checked the EM-Plasma/BuildScripts 'develop' branch files and I could not find any reference to `ATDM_CONFIG_KNOWN_SYSTEM_NAME`, or `ATDM_CONFIG_KNOWN_HOSTNAME` or `get_known_system_name` that would have been impacted by this refactoring.  So EMPIRE hopefully will not break due to the merged PR #5705.

**Comment by bartlettroscoe** [comment]
@bathmatt, have you had a chance to verify that the installed load_matching_env.sh script works correctly now for your custom env on 'vortex'?

**Comment by bartlettroscoe** [comment]
@bathmatt, does the installed `load_matching_env.sh` script with your custom 'vortex' env now work fo you?

**Comment by bartlettroscoe** [comment]
@rppawlo, can you let me know if the 'load_matching_env.sh' is working or now and if not how I can reproduce.

**Comment by rppawlo** [comment]
looks like it is working now - at least for running Matt's code on vortex.

**Comment by bartlettroscoe** [comment]
@rppawlo said:

> looks like it is working now - at least for running Matt's code on vortex.

Thanks!

Given Roger's feedback and my own testing, I think this should be fixed.

Closing as complete.
