### ISSUE TITLE
EXTERNAL] Fwd: [trilinos/Trilinos] ifpack2: build error with scalar=FLOAT and COMPLEX_DOUBLE enabled (#4858)  --> still not fixed!

### ISSUE THREAD

**Issue by ajpowelsnl** [trilinos/Trilinos#4934]
Trilinos configure failed (again) using the "develop" branch. 

@trilinos/<Sierra DevOps>

Mark Hoemmen and Kyungjoo Kim 

## Current Behavior

I will email you the log.

## Steps to Reproduce

% module list
Currently Loaded Modulefiles:
  1) sierra-python/2.7                       4) sierra-compiler/gcc/7.2.0               7) sntools/local
  2) sierra-git/2.6.1                        5) sierra-mpi/openmpi/1.10.2
  3) sierra-cmake/3.12.2                     6) sierra-devel/gcc-7.2.0-openmpi-1.10.2
cee-build011 1164 % 
cee-build011 1164 % 
cee-build011 1164 % echo $SIERRA_SNTOOLS_PATH
/sierra/dev/ajpowel/toolset
cee-build011 1165 % 
cee-build011 1165 % 
cee-build011 1165 % type -a mpicc
mpicc is /projects/sierra/linux_rh6/SDK/mpi/openmpi/1.10.2-gcc-7.2.0-RHEL6/bin/mpicc
cee-build011 1166 % 
cee-build011 1166 % 
cee-build011 1166 % type -a mpicxx
mpicxx is /projects/sierra/linux_rh6/SDK/mpi/openmpi/1.10.2-gcc-7.2.0-RHEL6/bin/mpicxx
cee-build011 1167 % 
cee-build011 1167 % mpicc --version
gcc (GCC) 7.2.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

cee-build011 1168 % 
cee-build011 1168 % 
cee-build011 1168 % mpicxx --version
g++ (GCC) 7.2.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

cee-build011 1169 % mpiexec --version
mpiexec (OpenRTE) 1.10.2

cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 6.9 (Santiago)

## Related Issues

] Fwd: [trilinos/Trilinos] ifpack2: build error with scalar=FLOAT and COMPLEX_DOUBLE enabled (#4858)

**Comment by mhoemmen** [comment]
@ajpowelsnl We're finishing up a large batch of Trilinos deprecation work; give us a bit please.

@trilinos/tpetra @trilinos/ifpack2 @kyungjoo-kim

**Comment by ajpowelsnl** [comment]
OK got it.  Many thanks!

**Comment by mhoemmen** [comment]
This appears to be fixed.  I'm closing for now.  Please reopen if this should arise again.  Thanks!
