### ISSUE TITLE
Trilinos_ENABLE_FORTRAN=OFF still complains that it can't find Fortran compiler

### ISSUE THREAD

**Issue by leonavery** [trilinos/Trilinos#494]
I'm trying to build trilinos on a Mac, thus without Fortran. I thought this would be straightforward. I start with `cmake -D Trilinos_ENABLE_FORTRAN=OFF trilinos-12.6.3-Source`, which creates a bunch of output that I attach below. The key point, though, is that it ends with 

    CMake Error at cmake/tribits/core/package_arch/TribitsGlobalMacros.cmake:1669     (ENABLE_LANGUAGE):
      No CMAKE_Fortran_COMPILER could be found.

      Tell CMake where to find the compiler by setting either the environment
      variable "FC" or the CMake cache entry CMAKE_Fortran_COMPILER to the full
      path to the compiler, or to the compiler name if it is in the PATH.
    Call Stack (most recent call first):
      cmake/tribits/core/package_arch/TribitsProjectImpl.cmake:188 (TRIBITS_SETUP_ENV)
      cmake/tribits/core/package_arch/TribitsProject.cmake:93 (TRIBITS_PROJECT_IMPL)
      CMakeLists.txt:90 (TRIBITS_PROJECT)
    
    
    -- Configuring incomplete, errors occurred!
    See also "/Users/lavery/Documents/OneDrive/fenics/CMakeFiles/CMakeOutput.log".
    See also "/Users/lavery/Documents/OneDrive/fenics/CMakeFiles/CMakeError.log".
    
I also tried to fool it with CMAKE_Fortran_COMPILER=/usr/bin/true, but it's too smart for that. 

So how do I build without Fortran? I assume the existence of the Trilinos_ENABLE_FORTRAN=OFF option means this is supposed to be possible -- what am I doing wrong?

Thanks.

[trilinos_cmake.TXT](https://github.com/trilinos/Trilinos/files/360057/trilinos_cmake.TXT)

**Comment by mhoemmen** [comment]
CMake is case sensitive.  Try Trilinos_ENABLE_Fortran:BOOL=OFF.  I use this to build with Clang on Mac.
