### ISSUE TITLE
Framework:  Does ATDM testing set MPI_EXEC correctly?

### ISSUE THREAD

**Issue by kddevin** [trilinos/Trilinos#4952]
## Bug Report
@trilinos/framework @bartlettroscoe 

### Description
I am trying to use ATDM testing as instructed in #4904 
The compilation works fine, but the tests all fail.  I suspect the problem is that ctest is using an incompatible version of mpiexec.  Should the atdm scripts set MPI_EXEC as they set the CMAKE_*_COMPILER flags?  

```
-- MPI_USE_COMPILER_WRAPPERS='ON'
-- Leaving current CMAKE_C_COMPILER=/projects/sems/install/rhel6-x86_64/sems/compiler/gcc/7.2.0/openmpi/1.10.1/bin/mpicc since it is already set!
-- Leaving current CMAKE_CXX_COMPILER=/projects/sems/install/rhel6-x86_64/sems/compiler/gcc/7.2.0/openmpi/1.10.1/bin/mpicxx since it is already set!
-- MPI_EXEC='mpiexec'
-- MPI_EXEC='/usr/local/bin/mpiexec'

```

### Steps to Reproduce
```
[vesper Obj_atdm]$ source ../cmake/std/atdm/load-env.sh  gnu-7.2.0-openmp-release-debug
Hostname 'vesper.sandia.gov' matches known ATDM host 'sems-rhel6' and system 'sems-rhel6'
Setting compiler and build options for buld name 'gnu-7.2.0-openmp-release-debug'
Using SEMS RHEL6 compiler stack GNU-7.2.0 to build RELEASE-DEBUG code with Kokkos node type OPENMP

[vesper Obj_atdm]$ which mpiexec
/projects/sems/install/rhel6-x86_64/sems/compiler/gcc/7.2.0/openmpi/1.10.1/bin/mpiexec

[vesper Obj_atdm]$ cmake \
>   -GNinja \
>   -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
>   -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_Piro=ON \
> .. >& output.txt

[vesper Obj_atdm]$ grep -i mpiexec output.txt
-- MPI_EXEC='mpiexec'
-- MPI_EXEC='/usr/local/bin/mpiexec
```

**Comment by bartlettroscoe** [comment]
@kddevin, this is strange.  On other 'sems-rhel6' systems with the identical build `gnu-7.2.0-openmp-release-debug` like you see [here](https://testing.sandia.gov/cdash-dev-view/index.php?project=Trilinos&parentid=4911882), the [cmake output](https://testing.sandia.gov/cdash-dev-view/viewConfigure.php?buildid=4911888) shows:

```
Probing the environment ...

...
-- MPI_EXEC='mpiexec'
-- MPI_EXEC='/projects/sems/install/rhel6-x86_64/sems/compiler/gcc/7.2.0/openmpi/1.10.1/bin/mpiexec'
```

and it appears to be set in the [cache](https://testing.sandia.gov/cdash-dev-view/viewNotes.php?buildid=4911882) correctly showing:

```
MPI_EXEC:FILEPATH=/projects/sems/install/rhel6-x86_64/sems/compiler/gcc/7.2.0/openmpi/1.10.1/bin/mpiexec
```

So I am confused about what is different about the machine 'vesper' from other SEMS RHEL6 machines.

Can you attach the cmake output (you captured in in `output.txt` above), the genreated `CMakeCache.txt` file and the `Testing/Temporary/LastTest.log`?

**Comment by kddevin** [comment]
@bartlettroscoe   

Here are the files you requested.  The tests time out (likely due to launch failure with the wrong mpiexec), so just a few entries are listed.

[LastTest.log.txt](https://github.com/trilinos/Trilinos/files/3122967/LastTest.log.txt)

[CMakeCache.txt](https://github.com/trilinos/Trilinos/files/3122915/CMakeCache.txt)

[output_cmake.txt](https://github.com/trilinos/Trilinos/files/3122905/output_cmake.txt)

**Comment by bartlettroscoe** [comment]
@kddevin, that is very strange how it is not finding the right `MPI_EXEC`:

```
-- MPI_EXEC='mpiexec'
-- MPI_EXEC='/usr/local/bin/mpiexec'
```

Any way that I can log onto this machine `vesper.sandia.gov` and see what is going on with this and try to fix this?  Should be easy to fix (whatever the cause) if I can get on the machine.

Otherwise, can I post a branch for you to test out to try to fix this?  I have an idea of something that might work.
