### ISSUE TITLE
Ifpack2_Relaxation_def.hpp variable template C++14 extension warning breaking SPARC Trilinos Integration builds starting 2019-04-18

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#4960]
CC: @trilinos/ifpack2, @srajama1  (Trilinos Linear Solvers Product Lead), @bartlettroscoe, @fryeguy52

<Checklist>
<???: Add label "client: ATDM">
<???: Add label "ATDM Sev: Blocker" (by default but could be other "ATDM Sev: XXX")>
<???: Add label "type: bug"?>
<???: Add label for affected packages (e.g. "pkg: MueLu", "pkg: Tpetra", "pkg: Kokkos", etc.)>
<???: Add label "PA: ???Project Area???" (e.g. "PA: Linear Solvers", "PA: Data Services")>
<???: Add milestone "Initial cleanup of new ATDM ..." or "Keep promoted ATDM ...">
<???: Once GitHub Issue is created, add entries for tests to TrilinosATDMStatus/*.csv files>

## Next Action Status

Resolved in SPARC for now.  Next: Refactor Ifpack2 and/or SPARC to not have SPARC use code in "details" that only exists in the defs.hpp file ...

## Description

The new warning elevated to an error:

```
Ifpack2_Relaxation_def.hpp:147:6: error: variable templates are a C++14 extension [-Werror,-Wc++14-extensions]
 void Relaxation::updateCachedMultiVector(const Teuchos::RCP > & map, size_t numVecs) const{
     ^
```

is breaking the SPARC Trilinos integration builds as shown [here](http://compsim-dashboard.sandia.gov/cdash/index.php?project=SPARC&date=2019-04-18&filtercount=1&showfilters=1&field1=buildname&compare1=66&value1=-trildev) with that warning being shown [here](http://compsim-dashboard.sandia.gov/cdash/viewBuildError.php?buildid=108404)

## Current Status on CDash

* [sparc-alltpls_cee-cpu_clang-5.0.1_openmpi-1.10.2_static_opt-trildev builds over last 5 days](http://compsim-dashboard.sandia.gov/cdash/index.php?project=SPARC&date=2019-04-18&filtercombine=and&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=sparc-alltpls_cee-cpu_clang-5.0.1_openmpi-1.10.2_static_opt-trildev&field2=buildstarttime&compare2=83&value2=5%20days%20ago)

## Steps to Reproduce

I can't see this warning being generated in the [Ifack2 package build itself for the build Trilinos-atdm-cee-rhel6_clang-5.0.1_openmpi-1.10.2_serial_static_opt](https://testing.sandia.gov/cdash-dev-view/viewBuildError.php?type=1&buildid=4910167) so I am not sure one can reproduce this just with Trilinos.  (Does this suggest a lack of test coverage for Ifpack2?)

But if one can get on the CEE LAN and can clone the SPARC repos, then one can reproduce using the scripts described [here](https://snl-wiki.sandia.gov/display/CoodinatedDevOpsATDM/Building+ATDM+APPs+Against+Local+Installs+of+Trilinos#BuildingATDMAPPsAgainstLocalInstallsofTrilinos-BuildingandTestingSPARCAgainstLocalTrilinosInstallation).  After getting Trilinos on to the 'develop' branch as described [here](https://snl-wiki.sandia.gov/display/CoodinatedDevOpsATDM/Building+ATDM+APPs+Against+Local+Installs+of+Trilinos#BuildingATDMAPPsAgainstLocalInstallsofTrilinos-BuildingagainstTrilinos'develop'usingtheATDMTrilinosconfiguration), one can reproduce this using the command:

```
$ cd sparc/

$ env \
    ATDM_TRIL_SPARC_BUILDS_LIST=cee-rhel6_clang-5.0.1_openmpi-1.10.2_serial_static_opt \
    ATDM_TRIL_SPARC_SKIP_NATIVE_BUILD=1 \
  ./sparc-tril-dev-scripts/run_builds_and_tests.sh
```

**Comment by bartlettroscoe** [comment]
@trilinos/ifpack2, @srajama1, 

I marked this as [`ATDM Sev: Critical`](https://snl-wiki.sandia.gov/display/CoodinatedDevOpsATDM/ATDM-Specific+Trilinos+GitHub+Labels#ATDM-SpecificTrilinosGitHubLabels-LabelsforSeverity/Criticality) because this one warning elevated to an error essentially brings down all SPARC Trilinos Integration testing.

P.S. I will contact the SPARC team to see if we can turn off `-Werror` for the SPARC Trilinos Integration builds.  It is creating too many fire-drills for me and Trilinos developers.

**Comment by bartlettroscoe** [comment]
Here is the request to turn off `-Werror` in SPARC Trilinos Integration builds so that warnings like this can be treated as [`ATDM Sev: Blocker`](https://snl-wiki.sandia.gov/display/CoodinatedDevOpsATDM/ATDM-Specific+Trilinos+GitHub+Labels#ATDM-SpecificTrilinosGitHubLabels-LabelsforSeverity/Criticality) instead of [`ATDM Sev: Critcal`](https://snl-wiki.sandia.gov/display/CoodinatedDevOpsATDM/ATDM-Specific+Trilinos+GitHub+Labels#ATDM-SpecificTrilinosGitHubLabels-LabelsforSeverity/Criticality):

* https://sems-atlassian-srn.sandia.gov/browse/SPAR-559

**Comment by mhoemmen** [comment]
I'm looking at the [line of code in question](https://github.com/trilinos/Trilinos/blob/a48c257ff025b90698910bb56e3e47a9ed18cb9f/packages/ifpack2/src/Ifpack2_Relaxation_def.hpp#L147), and I'm not seeing any [variable templates](https://en.cppreference.com/w/cpp/language/variable_template) or anything that looks like it requires C++14.  Could this perhaps be a Clang issue?

**Comment by bartlettroscoe** [comment]
The line (formatted better) is::

```
template<class MatrixType>
void Relaxation
<MatrixType>::updateCachedMultiVector(
     const Teuchos::RCP<const Tpetra::Map<local_ordinal_type,global_ordinal_type,node_type> > & map,
     size_t numVecs
    ) const
{
  ..
```

does look like pretty straightforward C++98/03 code.  

In any case, we need to make this warning go away one way or the other.

I need to build SPARC 'master' against Trilinos 'develop' anyway so I will take a quick look at this.

**Comment by bartlettroscoe** [comment]
FYI: A described in:

* https://sems-atlassian-srn.sandia.gov/browse/SPAR-560

technically this is caused not a defect in Trilinos but instead a defect in how SPARC is including Trilinos header files and directly using code in the `Ifpack2::Impl`.  

Since this is not a Trilinos defect but a SPARC defect, I am closing this as invalid.

**Comment by bartlettroscoe** [comment]
CC: @srajama1, @mhoemmen, @trilinos/ifpack2 

Some more details for those that can't see [SPAR-560](https://sems-atlassian-srn.sandia.gov/browse/SPAR-560) ...

The problem is that SPARC is directly including `Ifpack2_Relaxation_def.hpp` instead of **NOT** `Ifpack2_Relaxation.hpp`.  The reason is that SPARC is including `Ifpack2_Relaxation_def.hpp` is taht it directly using` Ifpack2::Impl::InvertDiagBlocks` which is only declared and defined in the file `Ifpack2_Relaxation_def.hpp`.  Looks like a recent refactoring of Ifpack2 make is so that you can't include just `Ifpack2_Relaxation_def.hpp` without also including  `Ifpack2_Relaxation_decl.hpp`

No client should every be directly including a file like `Ifpack2_Relaxation_def.hpp`.  How is explicit template instantiation supposed to help reduce build times and binary size if downstream clients are just going to be including the template definitions in the `XXX_def.hpp` files?

In any case, I hacked SPARC to get it to pass the build and tests again but it is still calling ` Ifpack2::Impl::InvertDiagBlocks` which should be a no-no.

Can some Ifpack2 developers work with SPARC to get it to not have to include `Ifpack2_Relaxation_def.hpp` and instead to include just `Ifpack2_Relaxation.hpp`?

I will re-open this issue and mark in "ATDM Sev: Nonblocking" to see if we can get this fixed.

**Comment by mhoemmen** [comment]
@kyungjoo-kim might better know how to fix this with minimal disruption.  I need to work on some other things for a couple days, but if it's desperately urgent, I can do it.

**Comment by srajama1** [comment]
@kyungjoo-kim cannot change SPARC, considering this is a SPARC code change needed I don't know why @bartlettroscoe reopened this issue.

**Comment by bartlettroscoe** [comment]
@srajama1 said:

> @kyungjoo-kim cannot change SPARC, considering this is a SPARC code change needed I don't know why @bartlettroscoe reopened this issue.

SPARC is going to need help with this.  They need for Ifpack2 to publish `Ifpack2::Impl::InvertDiagBlocks` and support it in the decl.hpp file or tell them what to use instead.  Andrew Bradly added this call and I don't think he is working with SPARC anymore.  Can someone of the Ifpack2 team with access to the SRN help?

**Comment by bartlettroscoe** [comment]
@mhoemmen said:

> @kyungjoo-kim might better know how to fix this with minimal disruption. I need to work on some other things for a couple days, but if it's desperately urgent, I can do it.

As @kyungjoo-kim can't access SPARC code, perhaps he can tell you what to do about `Ifpack2::Impl::InvertDiagBlocks`?

NOTE: This is not super urgent because I make the code work after the recent Ifpack2 refactoring that broke SPARC.  But the current situation with SPARC including def.hpp files is not good for many reasons so this should be fixed before this causes more trouble.

**Comment by srajama1** [comment]
@bartlettroscoe We will take care of this. @jjwilke

**Comment by kyungjoo-kim** [comment]
I don't understand why SPARC uses the Impl namespace function directly. If they want to use Ifpack2_Relaxation, there are block crs related methods: computeBlockCrs() and ApplyInverseJacobi_BlockCrsMatrix(). This looks like that SPARC may have its own version of block jaobi solver using the InvertDiagBlocks functor. Making it work for the moment might be one thing. However, if SPARC uses this block jacobi solver, it is not going to be performant. This is another problem. It is probably better to use BlockTriContainer with a block jacobi mode.

**Comment by bartlettroscoe** [comment]
@kyungjoo-kim said:

> I don't understand why SPARC uses the Impl namespace function directly.

Can you talk with @ambrad about this?  It think he added this code to SPARC.

**Comment by kyungjoo-kim** [comment]
I talked with @ambrad . The code is old clutter from 2016. As the ifpack2 block line solver can handle the block jacobi case, that code path should be removed from SPARC. As you know, I cannot do that and someone who can access SPARC change the code path.

**Comment by mhoemmen** [comment]
I'm experimenting now with removing that call to old code, and making BlockJacobi (SPARC class that calls the function in question) a stub class.

**Comment by bartlettroscoe** [comment]
Thanks @mhoemmen!

**Comment by bartlettroscoe** [comment]
@mhoemmen said:

> I'm experimenting now with removing that call to old code, and making BlockJacobi (SPARC class that calls the function in question) a stub class.

Any progress on this?  This is not urgent but is important to shield SPARC from future problems related to the current setup.

**Comment by mhoemmen** [comment]
The experiment didn't quite work.  I had to drop it at the time, so it's back in the backlog.

**Comment by bartlettroscoe** [comment]
FYI: SPARC reaching into "impl" stuff in Kokkos is currently breaking SPARC, keeping SPARC from updating Trilinos after the Kokkos 2.99 upgrade on 2020/02/03.  See:

* https://sems-cdash-srn.sandia.gov/sparc/index.php?project=SPARC&date=2020-02-12&filtercount=1&showfilters=1&field1=groupname&compare1=61&value1=Trilinos%20Integration

which show build errors like:

```
undefined symbol: Kokkos::Serial::impl_is_initialized()
```

That is not directly related to this GitHub issue but that is just an example of bad things that happen with client codes call "impl" stuff.

Perhaps this is just a SPARC issue and not a Trilinos issue and we should just push issues like this over into their issue tracking system?

**Comment by mhoemmen** [comment]
@jhux2 @csiefer2

**Comment by jhux2** [comment]
@bartlettroscoe Can this be closed, or is this still causing problems for SPARC?

**Comment by bartlettroscoe** [comment]
> @bartlettroscoe Can this be closed, or is this still causing problems for SPARC?

@jhux2, don't know.  I don't work with SPARC anymore.  I would assume someone has resolved this but you could ask @sebrowne.

**Comment by jhux2** [comment]
Closing as fixed/stale.
