### ISSUE TITLE
Tpetra broke Albany nightly build on waterman 

### ISSUE THREAD

**Issue by ikalash** [trilinos/Trilinos#4962]
Looks like Trilinos failed to compile in the Albany nightly build on waterman due to Tpetra.  Here is the error: 

```
 76%] Building CXX object packages/tpetra/core/src/CMakeFiles/tpetra.dir/Tpetra_EpetraRowMatrix.cpp.o

/.../repos/Trilinos/packages/tpetra/core/src/Tpetra_Details_normImpl.cpp(67): error: function "Tpetra::Details::normImpl(MagnitudeType *, const Kokkos::View &, Tpetra::Details::EWhichNorm, const Teuchos::ArrayView &, __nv_bool, __nv_bool, const Teuchos::Comm *) [with ValueType=int, ArrayLayout=Kokkos::LayoutLeft, DeviceType=Kokkos::Device, MagnitudeType=int]" explicitly instantiated more than once

```
http://cdash.sandia.gov/CDash-2-3-0/viewBuildError.php?buildid=83824 

@trilinos/tpetra

**Comment by mhoemmen** [comment]
Huh, that's weird -- this is likely related to @kddevin 's PR https://github.com/trilinos/Trilinos/pull/4956, but that was specifically to fix a link error due to a _missing_ instantiation.  It might be related to different behavior due to `Tpetra_ENABLE_DEPRECATED_CODE` being `OFF` for you.

**Comment by mhoemmen** [comment]
@kddevin In the worst case, we could separate out the "ordinal scalars" from the "nonordinal scalars":
```c++
TPETRA_INSTANTIATE_SN_NO_ORDINAL_SCALAR( TPETRA_DETAILS_NORMIMPL_INSTANT )
// TPETRA_INSTANTIATE_GN doesn't exist yet; would need to add
// this to tpetra/core/cmake/ExplicitInstantiationSupport.cmake
TPETRA_INSTANTIATE_GN( TPETRA_DETAILS_NORMIMPL_INSTANT )
#ifndef HAVE_TPETRA_INST_INT_INT
TPETRA_INSTANTIATE_N( TPETRA_DETAILS_NORMIMPL_INSTANT_INT )
#endif // HAVE_TPETRA_INST_INT_INT
```

**Comment by mhoemmen** [comment]
@kddevin The following macro (that writes a macro :-D ) might be useful in general for functions that `Tpetra::MultiVector` uses:
```c++
#define TPETRA_INSTANTIATE_MULTIVECTOR_SN( INSTMACRO ) \
  #define INSTMACRO_##_INT( N ) INSTMACRO( int, N ) \
  TPETRA_INSTANTIATE_SN_NO_ORDINAL_SCALAR( INSTMACRO ) \
  TPETRA_INSTANTIATE_GN( INSTMACRO ) \
  #ifndef HAVE_TPETRA_INST_INT_INT \
  TPETRA_INSTANTIATE_N( INSTMACRO_INT ) \
  #endif 
```

**Comment by kddevin** [comment]
Hi, @ikalash   
I'll get this fixed.  In #4951, @mhoemmen and I are discussing alternatives.  The initial solution recommended there worked for our testing (with and without Tpetra_ENABLE_DEPRECATED_CODE) and the PR testing; I'll look at why it didn't work in your use case.
Thanks for your patience.

**Comment by mhoemmen** [comment]
PR #4969 should fix this in develop.
