### ISSUE TITLE
Dakota public distribution site down? 

### ISSUE THREAD

**Issue by ikalash** [trilinos/Trilinos#4979]
Is the Dakota public distribution site (https://dakota.sandia.gov/sites/default/files/distributions/public) down?  Our nightly Albany tests are supposed to pull dakota as follows: 

wget -nv --no-check-certificate https://dakota.sandia.gov/sites/default/files/distributions/public/dakota-6.9-release-public.src.tar.gz -v

and this operation started to fail over the weekend.  I tried it on a non-Sandia machine and get the same issue, so I don't think it's a proxy thing.  Also when I try to access the website, I get "Problem loading page" message.  Perhaps the site moved? 

@trilinos/trikota 
@briadam

**Comment by briadam** [comment]
Yes, the server that hosts dakota.sandia.gov (and a number of other related services) was down earlier today. We believe service has been restored, but let us know what you find.

**Comment by ikalash** [comment]
Issue has been resolved thanks!
