### ISSUE TITLE
MueLu:  MueLu_Helmholtz2DParallel_MPI_4 failing on ATDM complex builds

### ISSUE THREAD

**Issue by fryeguy52** [trilinos/Trilinos#4982]
## Bug Report
CC: @trilinos/muelu, @srajama1 (Trilinos Linear Solvers Product Lead), @bartlettroscoe, @fryeguy52
 
## Description
 
As shown in [this query](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-&field2=buildname&compare2=63&value2=-complex-&field3=testname&compare3=65&value3=MueLu_Helmholtz2DParallel_MPI_4&field4=buildstarttime&compare4=84&value4=2019-04-22T00%3A00%3A00&field5=buildstarttime&compare5=83&value5=2019-03-23T00%3A00%3A00) the test:
* MueLu_Helmholtz2DParallel_MPI_4

has been failing since 2019-01-11 in the builds:
* Trilinos-atdm-sems-rhel7-intel-17.0.1-openmp-complex-shared-debug
* Trilinos-atdm-sems-rhel7-gnu-7.2.0-openmp-complex-shared-release-debug
* Trilinos-atdm-sems-rhel7-intel-17.0.1-openmp-complex-shared-release-debug
* Trilinos-atdm-sems-rhel7-clang-3.9.0-openmp-complex-shared-release-debug

new commits on 2019-04-11 can be found [here](https://testing.sandia.gov/cdash/viewNotes.php?buildid=4867040#!#note2)

## Current Status on CDash

[results for the current testing day](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-&field2=buildname&compare2=63&value2=complex&field3=testname&compare3=65&value3=MueLu_Helmholtz2DParallel_MPI_4&field4=buildstarttime&compare4=84&value4=today&field5=buildstarttime&compare5=83&value5=yesterday)

## Steps to Reproduce

One should be able to reproduce this failure on with a sems rhel6 environment as described in:
* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md

More specifically, the commands given for with a sems rhel6 environment are provided at:
* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#sems-rhel6-environment

The exact commands to reproduce this issue should be:
```
$ cd <some_build_dir>/
$ source $TRILINOS_DIR/cmake/std/atdm/load-env.sh Trilinos-atdm-sems-rhel6-gnu-7.2.0-openmp-complex-shared-release-debug
$ cmake \
 -GNinja \
 -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
 -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_MueLu=ON \
 $TRILINOS_DIR
$ make NP=16
$ ctest -j8
```

**Comment by lucbv** [comment]
@bartlettroscoe this happened because the MueLu testing was down for a significant amount of time...

**Comment by csiefer2** [comment]
This one's my fault.

**Comment by bartlettroscoe** [comment]
> @bartlettroscoe this happened because the MueLu testing was down for a significant amount of time

@lucbv, how?

**Comment by srajama1** [comment]
@csiefer2 : Thanks for raising the hand !

**Comment by lucbv** [comment]
@bartlettroscoe if we cannot monitor the 'std::complex<double>' build with MueLu we cannot catch these mistakes. While our nightly builds were down we didn't get emails warning that something was wrong...

I just want to point at the fact that we do care about thesw nightly builds for software qualitiy.

**Comment by bartlettroscoe** [comment]
@lucbv said:

> I just want to point at the fact that we do care about thesw nightly builds for software qualitiy.

Would MueLu developers want to directly monitor the ATDM Trilinos MueLu builds as well?  It would be easy to put together a drivers script for `cdash_analyze_and_report.py` (#2933) that does that.  Let me know if you are intested in that and we can put that together.

**Comment by csiefer2** [comment]
@jhux2 Thoughts?

**Comment by csiefer2** [comment]
#4991

**Comment by csiefer2** [comment]
Merged

**Comment by bartlettroscoe** [comment]
Now that PR #4991 is merged, putting in review awaiting confirmation on CDash tomorrow.

**Comment by fryeguy52** [comment]
This has not failed since 4/24/2019 shown [here](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercombine=and&filtercombine=and&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-&field2=testname&compare2=61&value2=MueLu_Helmholtz2DParallel_MPI_4&field3=site&compare3=65&value3=sems-rhel&field4=buildstarttime&compare4=84&value4=2019-05-01T00%3A00%3A00&field5=buildstarttime&compare5=83&value5=2019-04-01T00%3A00%3A00). closing
