### ISSUE TITLE
MueLu: reduce library size

### ISSUE THREAD

**Issue by jhux2** [trilinos/Trilinos#4984]
MueLu's library size is large, due to a few factors:

1) Lack of ETI / incorrect usage of ETI in MueLu and or upstream in Xpetra.
2) Unnecessary duplication of weak symbols in MueLu in non-templated classes.

Related issue: #3137 
@trilinos/muelu

**Comment by mhoemmen** [comment]
MueLu could perhaps also benefit from outsourcing factory code to upstream packages, and from use of the Dependency Injection and Inversion pattern (like how `Belos::SolverFactory` works).

**Comment by jhux2** [comment]
See PR #4996.

**Comment by jhux2** [comment]
@csiefer2 is tackling another class this morning.

**Comment by jhux2** [comment]
This can be closed, thanks to the work in #3137.
