### ISSUE TITLE
Muelu:  MueLu_Maxwell3D-Tpetra_MPI_4 failing on atdm complex build

### ISSUE THREAD

**Issue by fryeguy52** [trilinos/Trilinos#4989]
## Bug Report
CC: @trilinos/muelu, @srajama1 (Trilinos Linear Solvers Product Lead), @bartlettroscoe, @fryeguy52
 
<Checklist>
<???: Add label "ATDM">
<???: Add label "bug"?>
<???: Add label for affected packages (e.g. "MueLu", "Tpetra", "Kokkos", etc.)>
<???: Add milestone "Initial cleanup of new ATDM builds of Trilinos" or "Keep promoted ATDM builds of Trilinos clean">
<???: Once GitHub Issue is created, add entries for tests to TrilinosATDMStatus/*.csv files>
<???: Add label "PA: ???Project Area???" (e.g. "PA: Linear Solvers", "PA: Data Services")>
 
## Next Action Status
<status-and-or-first-action>
 
## Description
 
As shown in [this query](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercombine=and&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-sems-rhel7-intel-17.0.1-openmp-complex-shared-release-debug&field2=testname&compare2=61&value2=MueLu_Maxwell3D-Tpetra_MPI_4&field3=site&compare3=61&value3=sems-rhel7&field4=buildstarttime&compare4=84&value4=2019-04-22T00%3A00%3A00&field5=buildstarttime&compare5=83&value5=2019-03-23T00%3A00%3A00) the test:
* MueLu_Maxwell3D-Tpetra_MPI_4

is failing in the build:
* Trilinos-atdm-sems-rhel7-intel-17.0.1-openmp-complex-shared-release-debug

## Current Status on CDash

[Test results last 5 days](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=4&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-sems-rhel7-intel-17.0.1-openmp-complex-shared-release-debug&field2=testname&compare2=61&value2=MueLu_Maxwell3D-Tpetra_MPI_4&field3=site&compare3=61&value3=sems-rhel7&field4=buildstarttime&compare4=83&value4=5%20days%20ago)

## Steps to Reproduce

One should be able to reproduce this failure on with a sems rhel6 environment as described in:
* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md

More specifically, the commands given for with a sems rhel6 environment are provided at:
* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#sems-rhel6-environment

The exact commands to reproduce this issue should be:
```
$ cd <some_build_dir>/
$ source $TRILINOS_DIR/cmake/std/atdm/load-env.sh Trilinos-atdm-sems-rhel7-intel-17.0.1-openmp-complex-shared-release-debug
$ cmake \
 -GNinja \
 -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
 -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_MueLu=ON \
 $TRILINOS_DIR
$ make NP=16
$ ctest -j8
```

**Comment by lucbv** [comment]
@fryeguy52 this could be related to work I did last week to deprecate some adapters in MueLu.
However I do find it puzzling that the same test is passing in the following builds:
```
Trilinos-atdm-waterman-cuda-9.2-debug
Trilinos-atdm-sems-rhel7-gnu-7.2.0-openmp-complex-shared-release-debug 
Trilinos-atdm-sems-rhel7-clang-3.9.0-openmp-complex-shared-release-debug 
Trilinos-atdm-sems-rhel6-gnu-7.2.0-openmp-complex-shared-release-debug 
```
as can be seen [here](https://testing.sandia.gov/cdash/index.php?subproject=MueLu&project=Trilinos)

**Comment by lucbv** [comment]
@fryeguy52 I cannot set the Trilinos atdm as explained above since my local machine is not recognized as a sems machine. Is there a way to force the script to believe that my machine is similar to a sems rhel7 machine?

**Comment by bartlettroscoe** [comment]
@lucbv asked:

> I cannot set the Trilinos atdm as explained above since my local machine is not recognized as a sems machine. Is there a way to force the script to believe that my machine is similar to a sems rhel7 machine?

@lucbv, it would have to be 100% identical to the SEMS env including the module names.  If yo uhave a custom env, then I think what you need is #4933.  If that sounds about right, then we can implement thsi and you can try this out?

**Comment by fryeguy52** [comment]
@lucbv There are a couple ways to work with the sems environment.  You can mount the nfs on you workstation by following [these instructions](https://sems-atlassian-son.sandia.gov/confluence/display/SEMSKB/How+to+mount+NFS+TPL+server+on+Linux+workstation), or you can ssh to some sems login machines and those have the environment already set up.  Those machine are `sems-son-rhel6-login-01` and `sems-son-rhel7-login-01` and you should have access to those.

**Comment by fryeguy52** [comment]
This test is also failing in the job `Trilinos-atdm-sems-rhel7-intel-17.0.1-openmp-complex-shared-debug` shown [here](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercombine=and&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-sems-rhel7-intel-17.0.1-openmp-complex-shared-debug&field2=testname&compare2=61&value2=MueLu_Maxwell3D-Tpetra_MPI_4&field3=site&compare3=61&value3=sems-rhel7&field4=buildstarttime&compare4=84&value4=2019-04-25T00%3A00%3A00&field5=buildstarttime&compare5=83&value5=2019-03-26T00%3A00%3A00)

**Comment by lucbv** [comment]
@bartlettroscoe  @fryeguy52 I do not see the sems-rhel7 builds today.
I have pushed a fix in the Maxwell3D test but if the builds are not back up I won't be able to check that it was a proper fix...

**Comment by bartlettroscoe** [comment]
@lucbv,

> I do not see the sems-rhel7 builds today.

If they are missing again tomorrow we will look into this.  Builds go missing for various reasons from day to day.  (Automated testing on many if these systems is pretty fragile for many reasons.)

**Comment by bartlettroscoe** [comment]
@lucbv, FYI: that build failed today for some unknown reason as shown [here](https://testing.sandia.gov/cdash-dev-view/index.php?project=Trilinos&parentid=4968457).  My guess is this is some type of random failure that may not occur tomorrow.

**Comment by lucbv** [comment]
@bartlettroscoe sure, let us monitor this some more and see if the test passes on intel builds now.
I can also point you to [this nightly build](https://testing.sandia.gov/cdash/index.php?project=Trilinos&date=2019-04-29&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=63&value1=Linux-gcc-5.3.0-SERIAL-DEBUG_LONG-LONG_COMPLEX-DOUBLE&field2=buildstarttime&compare2=84&value2=2019-05-01) which was failing in the same test yesterday and that has passed today which might be a good sign.

**Comment by lucbv** [comment]
It looks like this is now passing on the sems-rhel7 intel build with complex.
@fryeguy52 and I will wait for another day before calling it good and closing this issue.

**Comment by lucbv** [comment]
@fryeguy52 @bartlettroscoe 
The test is passing again today. This looks like a good confirmation, should we close this issue?

**Comment by bartlettroscoe** [comment]
@lucbv asked:

> The test is passing again today. This looks like a good confirmation, should we close this issue?

Looking at [this query](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercount=4&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-sems-rhel7-intel-17.0.1-openmp-complex-shared-release-debug&field2=testname&compare2=61&value2=MueLu_Maxwell3D-Tpetra_MPI_4&field3=site&compare3=61&value3=sems-rhel7&field4=buildstarttime&compare4=83&value4=2019-04-15) the test was consecutively failing from  4/18/2019 through 4/28/2019 but has been consecutively passing the last two days (after a random build error resulted in a "Not Run" status on 4/30/2019).  Therefore, I think this is okay to close.

Closing as complete.

Thanks!

**Comment by bartlettroscoe** [comment]
Also, as shown in [this query](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercount=4&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-sems-rhel7-intel-17.0.1-openmp-complex-shared-debug&field2=testname&compare2=61&value2=MueLu_Maxwell3D-Tpetra_MPI_4&field3=site&compare3=61&value3=sems-rhel7&field4=buildstarttime&compare4=83&value4=2019-04-15) this test also passed the last three days in the build `Trilinos-atdm-sems-rhel7-intel-17.0.1-openmp-complex-shared-debug`.   So looking good there too.

P.S. Need a tool that will create these summaries automatically (i.e. #3887).
