### ISSUE TITLE
Tpetra::BlockCrsMatrix: Add LU factorization, solve, & inverse for small dense blocks

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#50]
@trilinos/tpetra 
Add GETRF (LU factorization), GETRS (solve linear system(s) using results of GETRF), and GETRI (compute explicit matrix inverse, using results of GETRF) for LittleBlock in BlockCrsMatrix.

GETRI will help accelerate block Jacobi (a.k.a. point implicit), by pushing solve costs to setup and making computation during the actual apply step just little dense matrix-vector multiplies.  This should be easier to vectorize.

**Comment by srajama1** [comment]
Can this go into KokkosKernels and used by Tpetra ?

**Comment by mhoemmen** [comment]
@srajama1 That's the ultimate plan.  I want to coordinate with the Intrepid2 folks with that, though.  The projects that want this want it NOW, so the point is just to get something up and running.

You know how @crtrott talks about different levels of kernels?  
  1. "Global" (may use resources of the entire execution space (instance))
  2. Single thread team (may make use of fine-grained synchronization or shared memory)
  3. Single thread / GPU warp (may use SIMD or GPU shuffle / swizzle inside)
  4. "Sequential" / single vector lane / single GPU thread (suitable for the "vector" / "elemental" function attribute)
These kernels belong to (3) or (4).
