### ISSUE TITLE
Develop and use git commit template for Trilinos repo

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#501]
**CC:** @trilinos/framework 

**Description:**

Using a commit template has been shown on other projects to help make commit messages more consistent and contain the proper information.

This story is to create a git commit template that will be used by default for all Trilinos commits.  

**Definition of Done:**

Git commit template is installed and presented for all Trilinos commits (but the commit author can modify the commit in the editor before the commit is created).

**Tasks:**
1. Learn and document how a git commit template works (see [here](https://github.com/TriBITSPub/TriBITS/issues/138#issuecomment-233959791)) [Done]
2. Develop template for a Trilinos commits (i.e. on a Google Doc) (see [below](https://github.com/trilinos/Trilinos/issues/501#issuecomment-233965160)) ... IN PROGRESS ...
3. Develop automated process for installing git commit hooks (e.g. as a side-effect of running the CMake configure) (see [here](https://github.com/TriBITSPub/TriBITS/issues/138#issuecomment-233962167)) ... Waiting to be worked ...

**Comment by bartlettroscoe** [comment]
See detailed proposal for these install hook in TriBITSPub/TriBITS#138

I would like to propose the following git commit template file:

```
# A) <Package>: Imperative one-line summary about 50 chars (#WXYZ)


# B) Explain your changes in new paragraph (wrapped to about 72 chars wide).


# C) Mention related issue tickets, even for other repos, e.g. <org>/<repo>#WXYZ


# Example:
#
# MyPackage: Add great new feature foo (#1234)
#
# This new foo feature is great because no one has ever done anything as
# great as this feature.  This is great because:
#
# * We are the first group to ever think of this
# * This solves a hard problem
# * Users will love this new feature
#
# This directly addresses #1234 but it also relates to #2345, 3456, and
# other_org/other_repo#4567.
```

The filled-out commit message would look like:

```
# A) <Package>: Imperative one-line summary about 50 chars (#WXYZ)
Teuchos: Add new reduction operation foo() (#568)

# B) Explain your changes in new paragraph (wrapped to about 72 chars wide).
This new reduction operation foo() is needed so that Tpetra can do that thing
it does better.

# C) Mention related issue tickets, even for other repos, e.g. <org>/<repo>#WXYZ
This mostly addresses #568 but also is related to #678 and kokkos/kokkos#789.

# Files being modified ...
```

Since the lines starting with `#" are removed, this creates the commit message

```
Teuchos: Add new reduction operation foo() (#568)

This new reduction operation foo() is needed so that Tpetra can do that thing
it does better.

This mostly addresses #568 but also is related to #678 and kokkos/kokkos#789.
```

The format of this commit template came from:

* http://codeinthehole.com/writing/a-useful-template-for-commit-messages/

Any objections?

**Comment by mhoemmen** [comment]
Is "about 50 chars" a hard limit?

**Comment by bartlettroscoe** [comment]
> Is "about 50 chars" a hard limit?

No, it is just a recommendation and it is based on the fact that git itself will clip summary lines longer than 50 chars in some contexts.  But git itself creates summary lines longer than that (i.e. if it merges from a long branch name).  It is just that we don't want summary lines that are too long.  I would put a hard limit of 120 chars.  If you can't summarize what you are doing in 120 chars, you should split up your commit into smaller commits.  In fact, I think we should add that to a local git commit hook to help people avoid this mistake.

**Comment by mhoemmen** [comment]
> If you can't summarize what you are doing in 120 chars, you should split up your commit into smaller commits. In fact, I think we should add that to a local git commit hook to help people avoid this mistake.

I accept that.  I try to keep the top line to 72 chars and use less if I can.  It's just hard to keep to 50 chars if you put the package name first, which I like as a way to help developers scan commits quickly.

**Comment by jwillenbring** [comment]
Would it be worth mentioning the requirements for automatically closing an issue through a commit? I don't know if we want to encourage that behavior or not. There are pros and cons to closing a  ticket in that way.

Feedback from @maherou and @agsalin at the leaders meeting: Mention tests added, mention if backward compatibility is broken.

**Comment by bmpersc** [comment]
72 chars is what the git developers adhere to themselves. I haven't seen any cases where you needed to be lower than that.

**Comment by bartlettroscoe** [comment]
> 72 chars is what the git developers adhere to themselves. I haven't seen any cases where you needed to be lower than that.

Then let's change the recommendation for 72 chars instead of 50 chars in the commit template?  And let's consider a (hard?) limit of 120 chars (we can print a warning using a `commit-msg` hook to remind people).

**Comment by bartlettroscoe** [comment]
> Would it be worth mentioning the requirements for automatically closing an issue through a commit? I don't know if we want to encourage that behavior or not. There are pros and cons to closing a ticket in that way.

I don't think we should encourage closing an Issue with a commit (i.e. `Fixes #1234`).  In fact, I would recommend discouraging this practice.  Most Issues should go through some type of review and there is usually some type of customer who should sign off before the Issue gets closed.  Otherwise, we think an issue is addressed but we never remember to follow up to see that the Issue is actually addressed.

**Comment by mhoemmen** [comment]
I've been having trouble getting Github to close issues automatically.

**Comment by aprokop** [comment]
1. Add explicitly a requirement for a blank line after the subject, some people don't realize you need one.
2. Are we going to be sticky about capitalization/punctuation(last period)/imperative and things like that?
3. Are we going to allow any specific markup language in the commit message (if necessary)?

**Comment by bartlettroscoe** [comment]
> Add explicitly a requirement for a blank line after the subject, some people don't realize you need one.

Yes, that is a big problem.  Not sure why it is so hard to get that message across.  The plan is to auto-install a `commit-msg` hook that will provide a verbose warning if people create a commit message that goes over 72 chars and to abort the commit if people go over 120 chars.  I have already written this script and it is shown below.

If you use a commit summary shorter than 72 chars, it just quietly accepts it:

```
$ git commit -a -m "this is a short summary line"
[master 584b5c7] this is a short summary line
 1 file changed, 3 insertions(+)
```

If you use a commit summary longer than 72 chars but less than 120 chars, it accepts it but prints a warning:

```
[8vt@th232 TriBITS (master)]$ git commit -a -m "This is a much longer summary line longer than 72 chars but still shorter than 120 chars"
***
*** WARNING: Summary line is 88 > 72 chars long!
***
*** NOTE: Please use 'git commit --amend' to reduce length of summary line!
***
[master a79db86] This is a much longer summary line longer than 72 chars but still shorter than 120 chars
 1 file changed, 3 insertions(+)
```

But if you get crazy and write a summary line over 120 chars you get:

```
$ git commit -a -m "This is a very long summary line that is over 120 chars.  It is over 120 chars because I forgot to add two newlines after the first sentence.  I can't believe that I did not see how long this summary line was and I would go ahead and push this anyway.  I must never actually run 'git log' or 'git log --oneline' before I push my commits to see my commits.  If I did, I would never push commits with crazy summary lines this long."
***
*** ERROR: Summary line is 429 > 120 chars long!  Commit rejected!
***
*** Summary line: This is a very long summary line that is over 120 chars.  It is over 120 chars because I forgot to add two newlines after the first sentence.  I can't believe that I did not see how long this summary line was and I would go ahead and push this anyway.  I must never actually run 'git log' or 'git log --oneline' before I push my commits to see my commits.  If I did, I would never push commits with crazy summary lines this long.
***
*** NOTE: Your rejected commit message is in the file ./git/COMMIT_EDITMSG
***
```

So if the user gets their commit message rejected, then they can just copy the message from the file `./git/COMMIT_EDITMSG` and fix it.

Anyone have an objection to using this `commit-msg` hook?  No need to remind people in the commit template if you use this commit hook.

> Are we going to be sticky about capitalization/punctuation(last period)/imperative and things like that?

I don't think we so strict about that.  The example shown in the template (see [above](https://github.com/trilinos/Trilinos/issues/501#issuecomment-233965160)) should hopefully make that clear.

> Are we going to allow any specific markup language in the commit message (if necessary)?

What markup?  I would not encourage non-ASCI markup since would make the commit message less readable when displayed with raw `git log`.
 
----

**`commit-msg` hook script:**

```
#!/usr/bin/env python
#
# Check to make sure commit message is formatted correctly
#

import sys

commitLogFileName = sys.argv[1]
commitLogFileStr = open(commitLogFileName, "r").read()

firstLine = commitLogFileStr.splitlines()[0]

firstLineLen = len(firstLine)
maxSummaryLen = 120
suggestedSummaryLen = 72

if (firstLineLen > maxSummaryLen):
  print("***")
  print("*** ERROR: Summary line is "+str(firstLineLen)+" > "+str(maxSummaryLen)+" chars long!  Commit rejected!")
  print("***")
  print("*** Summary line: "+firstLine) 
  print("***") 
  print("*** NOTE: Your rejected commit message is in the file ./git/COMMIT_EDITMSG")
  print("***")
  sys.exit(1)
elif (firstLineLen > suggestedSummaryLen):
  print("***")
  print("*** WARNING: Summary line is "+str(firstLineLen)+" > "+str(suggestedSummaryLen)+" chars long!")
  print("***") 
  print("*** NOTE: Please use 'git commit --amend' to reduce length of summary line!")
  print("***") 

# If we get here then it is okay to make the commit
sys.exit(0)
```

**Comment by bartlettroscoe** [comment]
I pushed the candidate commit message template and commit-msg hook to the Trilinos repo:

* [commonTools/git/local_hooks/commit_msg_template.txt](https://github.com/trilinos/Trilinos/blob/develop/commonTools/git/local_hooks/commit_msg_template.txt)
* [commonTools/git/local_hooks/commit-msg](https://github.com/trilinos/Trilinos/blob/develop/commonTools/git/local_hooks/commit-msg)

Please go ahead and modify these and commit your suggested modifications.  You can make your changes and directly commit on github.  No need to do this in the repo if you don't want. These files are not hooked in anywhere yet so it is safe to edit these right on github.

**Comment by bartlettroscoe** [comment]
At the Trilinos Leaders Meeting on 7/26, @agsalin suggested adding a checklist to the commit template reminding people to:

1. Add tests if they are adding new features
2. State if the commit is breaking backward compatibility (and if it is, some tests have to be changed that can detect that)

Depending on how many checklist items we put into a commit template, it could get long.

**Comment by jmgate** [comment]
> What markup?

If you include Markdown in the commit message, GitHub parses and renders it in certain contexts.

**Comment by bartlettroscoe** [comment]
> If you include Markdown in the commit message, GitHub parses and renders it in certain contexts.

Markdown is okay, as it is very readable in raw form.
