### ISSUE TITLE
Xpetra broke Albany and SPARC nightly builds 

### ISSUE THREAD

**Issue by ikalash** [trilinos/Trilinos#5011]
Looks like we have a compilation error in our nightlies when compiling against a new develop Trilinos: 

```
           from /.../trilinos-install-serial-intel-release/include/Piro_SolverFactory.hpp(97),
                 from /.../Albany/src/Albany_SolverFactory.cpp(24):

/.../trilinos-install-serial-intel-release/include/Xpetra_CrsMatrixFactory.hpp(54): catastrophic error: cannot open source file "Xpetra_TpetraCrsMatrix.hpp"

  #include "Xpetra_TpetraCrsMatrix.hpp"
                                       ^
```
http://cdash.sandia.gov/CDash-2-3-0/viewBuildError.php?buildid=84042 

@trilinos/xpetra

**Comment by jrood-nrel** [comment]
We are seeing this in Trilinos `develop` for our project as well.

**Comment by jhux2** [comment]
@ikalash @jrood-nrel This is probably due to our work to implement ETI in Xpetra (issue #4986).  Could one of you point me to your Trilinos configure script?

**Comment by ikalash** [comment]
@jhux2 : here is one of ours from my Fedora workstation.

**Comment by jhux2** [comment]
PR #5013 should fix this issue.

**Comment by spdomin** [comment]
Nalu saw this as well... We will look for the fix tonight.

**Comment by jhux2** [comment]
All, the PR has been merged into the develop branch.  It may or may not make it to master by this evening.

**Comment by bartlettroscoe** [comment]
CC: @micahahoward

Looks like this broke all of the SPARC Trilinos Integration builds too showing the error:

```
/projects/atdm_devops/trilinos_installs/2019-04-25/cee-rhel6_clang-5.0.1_openmpi-1.10.2_serial_static_opt/include/Xpetra_CrsMatrixFactory.hpp:54:10: fatal error: 'Xpetra_TpetraCrsMatrix.hpp' file not found
```

How did this pass PR testing?  Is the file `Xpetra_CrsMatrixFactory.hpp` not included in any automated tests run in PR testing?  Or are globs not used to install header files.

**Comment by jhux2** [comment]
@bartlettroscoe This is most likely a gap in Xpetra's testing.

**Comment by bartlettroscoe** [comment]
FYI: I did a trial build of SPARC 'master' + Trilinos 'develop' and verified this was fixed.

For the Trilinos version:

```
*** Git Repo: Trilinos
e2f3c75 [Thu Apr 25 16:56:24 2019 -0600] <csiefer2@users.noreply.github.com>
Merge pull request #5012 from jthano/ifpack_hypre_set_function_addition
```

I ran:

```
$ cd sparc/

$ env \
    SPARC_TRIL_BUILDS_LIST="cee-rhel6_clang-5.0.1_openmpi-1.10.2_serial_static_opt" \
    SPARC_TRIL_SKIP_NATIVE_BUILD=1 \
  ./sparc-tril-dev-scripts/run_builds_and_tests.sh 

Running the builds:
  cee-rhel6_clang-5.0.1_openmpi-1.10.2_serial_static_opt

./sparc-tril-dev-scripts/build_and_test_atdm_trilinos_and_sparc.sh \
   cee-rhel6_clang-5.0.1_openmpi-1.10.2_serial_static_opt "" ""


real    34m48.243s
user    345m41.937s
sys     10m49.903s

    Trilinos_DIR=/scratch/rabartl/SPARC.base/sparc/Trilinos/cee-rhel6_clang-5.0.1_openmpi-1.10.2_serial_static_opt/lib/cmake/Trilinos

100% tests passed, 0 tests failed out of 280
```

**Comment by spdomin** [comment]
Yes, sorry, we have been back in business since Jonathan's push to develop.

Feel free to close.
