### ISSUE TITLE
KokkosKernels promotion needs to update Ifpack2

### ISSUE THREAD

**Issue by jjwilke** [trilinos/Trilinos#5015]
`KokkosKernels::Experimental` has apparently disappeared in the devel branch of KokkosKernels. Ifpack2 references `namespace Experimental` in several places.  This will make the next promotion difficult - particularly the new CMake updates for kokkos-kernels.

**Comment by srajama1** [comment]
@kyungjoo-kim is aware of this. We will fix it during promotion.

**Comment by ndellingwood** [comment]
There is the kokkos-promotion branch of Trilinos tracking changes needed in Trilinos during the next promotion with a couple fixes. @kyungjoo-kim or I can make the fixes on that branch.

**Comment by ndellingwood** [comment]
@jjwilke is this blocking your cmake testing? If so we can get the fixes in quickly, I'm assuming this is the removal the batched blas stuff from the experimental namespace.

**Comment by ndellingwood** [comment]
@trilinos/kokkos-kernels

**Comment by kyungjoo-kim** [comment]
@jjwilke Could you check your cmake work after the PR #5032 ? If it works, would you please run your performance test of sparc to check that I did not create any side effects ?

**Comment by ndellingwood** [comment]
This was resolved by #5032, closing.
