### ISSUE TITLE
Framework: Installation Testing

### ISSUE THREAD

**Issue by william76** [trilinos/Trilinos#5027]
## Enhancement
@trilinos/framework 
@bartlettroscoe 
@jwillenbring 

As part of the roadmap towards implementing a backwards compatibility test to the Trilinos testing suite we need to first get Installation Testing up and running.

This will require some updates to [TriBiTS][1] to support some of the installation testing capabilities that we will need.  @bartlettroscoe can fill in more details on what we're needing to do there.

[1]: https://tribits.org/

**Comment by bartlettroscoe** [comment]
@william76, I should have time to look into this later this week.

**Comment by bartlettroscoe** [comment]
FYI: Getting bit by not having installation testing as part of PR testing (i.e. #5098).

I will try to work on the TriBITS stuff for this this week.

**Comment by bartlettroscoe** [comment]
@william76 and @jwillenbring,

So it turns out the installation testing feature in TriBITS still works!  The updated branch:

* https://github.com/TriBITSPub/TriBITS/tree/5027-enable-installation-testing

as of commit TriBITSPub/TriBITS@58ed6f999c9dd915d03e433d6b767b6cabcaff3a has the working test and draft documentation.

@william76, I will post a PR for this in the TriBITS repo.  After that, can you please test this this branch out with Trilinos and review the test and documentation?  We can go over this when I get back from my trip.

**Comment by bartlettroscoe** [comment]
@william76, I  invited you to be a TriBITS repo contributor.  Once you accept that, you should be able to review and approve the PR TriBITSPub/TriBITS#289.

You can then test Trilinos with this by cloning the TriBITS GitHub repo under your local Trilinos git repo and add:

```
   -DTrilinos_TRIBITS_DIR:STRING=TriBITS/tribits
```

to your `cmake` configure line.

Once you confirm it works as it should, I will clean up that TriBITS branch, merge it to the TriBITS 'master' branch and then snapshot to Trilinos and create a Trilinos PR to update TriBITS in Trilinos.

**Comment by bartlettroscoe** [comment]
@william76,

Any chance to review and approve https://github.com/TriBITSPub/TriBITS/pull/289 yet? See [above](https://github.com/trilinos/Trilinos/issues/5027#issuecomment-495730314).

**Comment by bartlettroscoe** [comment]
As this was sitting for 2 weeks with no review (other than Mark Hoemenn looking at it), I decided to not let it sit on a TriBITS branch and forget about it so I merged to TriBITS 'master' and created the PR #5352 to merge this updated documentation to Trilinos 'develop'.

@william76, let me know if you have any questions about this that are not answered by the updated documentation or the TriBITS unit tests (see TriBITSPub/TriBITS@8a774edae510405ccb78b2162bc069e4bca3e473).

Going to unsubscribe now.

**Comment by bartlettroscoe** [comment]
FYI: Looks like:

* https://trilinos.org/docs/files/TrilinosBuildReference.html

is not getting rebuilt automatically anymore to show the new section "Installation Testing" (see #5357).

Therefore, see the updated documentation in the generic project build reference:

* https://tribits.org/doc/TribitsBuildReference.html#installation-testing

Just replace `<Project>` with `Trilinos` and that should be it.

**Comment by bartlettroscoe** [comment]
> From: Mclendon, William C III
> Sent: Thursday, August 29, 2019 11:37 AM
> To: Bartlett, Roscoe A
> Subject: Re: Kokkos + Installation testing
> 
> Heya Ross,
> 
> I haven't tried this one since we spoke yesterday... I get that I think when I
> turn on Trilinos_ENABLE_INSTALLATION_TESTING... but the gtest stuff has
> been a big problem. I've tried to turn off Kokkos and KokkosKernels testing
> where I can because installation testing doesn't work for gtest.  When it's
> tried to build those packages I get bizarre "string is not a type" errors coming
> in from gtest .cc files ... or I'll get errors with delete operations but it's all
> internal to gtest stuff as far as I can tell so I've tried turning all of those off.
> 
> When I leave Trilinos_ENABLE_INSTALLATION_TESTING unset I generally
> don't see this "in TESTONLYLIBS not a TESTONLY lib" error.
> 
> -Will

**Comment by william76** [comment]
Closing this issue out since it's been superceded by #7383 which has better tracking of this issue.

**Comment by bartlettroscoe** [comment]
Related to:
* SEPW-213
* SEPW-214
