### ISSUE TITLE
Zoltan2:  Tests failing on ATDM cuda 10 build

### ISSUE THREAD

**Issue by fryeguy52** [trilinos/Trilinos#5036]
## Bug Report
CC: @trilinos/zoltan2, @kddevin (Trilinos Data Services Product Lead), @bartlettroscoe, @fryeguy52
 
## Next Action Status
<status-and-or-first-action>
 
## Description
 
As shown in [this query](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=6&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-white-ride-cuda-10.1-gnu-7.2.0-release-debug&field2=testname&compare2=65&value2=Zoltan2&field3=status&compare3=61&value3=Failed&field4=site&compare4=61&value4=white&field5=buildstarttime&compare5=84&value5=2019-04-29T00%3A00%3A00&field6=buildstarttime&compare6=83&value6=2019-03-30T00%3A00%3A00) the tests:
* Zoltan2_directoryTest_Kokkos_MPI_4
* Zoltan2_directoryTest_KokkosSimple_MPI_4
* Zoltan2_directoryTest_findUniqueGids.cpp_MPI_4

are failing in the build:
* Trilinos-atdm-white-ride-cuda-10.1-gnu-7.2.0-release-debug

## Current Status on CDash

[Failing zoltan2 tests for the current testing day](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=6&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-white-ride-cuda-10.1-gnu-7.2.0-release-debug&field2=testname&compare2=65&value2=Zoltan2&field3=status&compare3=61&value3=Failed&field4=site&compare4=61&value4=white&field5=buildstarttime&compare5=84&value5=today&field6=buildstarttime&compare6=83&value6=yesterday)

## Steps to Reproduce

One should be able to reproduce this failure on ride or white as described in:
* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md

More specifically, the commands given for ride or white are provided at:
* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#ridewhite

The exact commands to reproduce this issue should be:
```
$ cd <some_build_dir>/
$ source $TRILINOS_DIR/cmake/std/atdm/load-env.sh Trilinos-atdm-white-ride-cuda-10.1-gnu-7.2.0-release-debug
$ cmake \
 -GNinja \
 -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
 -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_Zoltan2=ON \
 $TRILINOS_DIR
$ make NP=16
$ bsub -x -Is -q rhel7F -n 16 ctest -j16
```

**Comment by bartlettroscoe** [comment]
CC: @srajama1, @trilinos/muelu, @trilinos/teko 

FYI: Looks like the same errors seen in #5033 and #5035:

```
Zoltan2_directoryTest_findUniqueGids.cpp.exe: sys/memtype_cache.c:90: ucs_memtype_cache_delete: Assertion `pgt_region != ((void *)0)' failed.
[white35:36900] *** Process received signal ***
[white35:36900] Signal: Aborted (6)
[white35:36900] Signal code:  (-6)
```

and

```
Zoltan2_directoryTest_Kokkos.exe: sys/memtype_cache.c:90: ucs_memtype_cache_delete: Assertion `pgt_region != ((void *)0)' failed.
[white35:36803] *** Process received signal ***
[white35:36803] Signal: Aborted (6)
[white35:36803] Signal code:  (-6)
```

and

```
Zoltan2_directoryTest_KokkosSimple.exe: sys/memtype_cache.c:90: ucs_memtype_cache_delete: Assertion `pgt_region != ((void *)0)' failed.
[white35:36856] *** Process received signal ***
[white35:36856] Signal: Aborted (6)
[white35:36856] Signal code:  (-6)
```

I suspect this is the same cause in all of these test failures.

**Comment by srajama1** [comment]
@bartlettroscoe This seems to be an environment issue. @nmhamster

**Comment by bartlettroscoe** [comment]
@srajama1 said:

> This seems to be an environment issue.

Perhaps, but who is qualified to debug this?

> @nmhamster

FYI: @nmhamster filters github issues and will not see references like this.  You need to send him direct emails.

**Comment by nmhamster** [comment]
@srajama1 / @bartlettroscoe - I'll take a look. Thank you for the bug report.

**Comment by nmhamster** [comment]
OK, I seem to have crashes in my test builds with the following tests now:

```
	107 - Zoltan2_directoryTest_Kokkos_MPI_4 (Failed)
	108 - Zoltan2_directoryTest_KokkosSimple_MPI_4 (Failed)
	109 - Zoltan2_directoryTest_findUniqueGids.cpp_MPI_4 (Failed)
```

All the other Zoltan2 tests look good.

**Comment by nmhamster** [comment]
@srajama1 / @bartlettroscoe / @fryeguy52 - reported to UCX team here: https://github.com/openucx/ucx/issues/3550

Also investigating alternative builds locally to see if we can get around the situation.

**Comment by nmhamster** [comment]
This looks like there maybe a bug in UCX when CUDA allocations are performed before `MPI_Init`. 

The suggested workaround for this is (while fixes are being considered):

```
export UCX_MEMTYPE_CACHE=n
```

Which produces:

```
110/112 Test #110: Zoltan2_block_MPI_4 ......................................   Passed    2.85 sec
        Start 111: Zoltan2_kokkosBlock_MPI_4
111/112 Test #111: Zoltan2_kokkosBlock_MPI_4 ................................   Passed    3.12 sec
        Start 112: Zoltan2_rcb_C_MPI_4
112/112 Test #112: Zoltan2_rcb_C_MPI_4 ......................................   Passed    2.86 sec

100% tests passed, 0 tests failed out of 112

Subproject Time Summary:
Zoltan2    = 1441.54 sec*proc (112 tests)

Total Test time (real) = 380.53 sec
```

**Comment by bartlettroscoe** [comment]
Okay, I will try setting `export UCX_MEMTYPE_CACHE=n` in the `cmake/std/atdm/ride/environment.sh` script for the `cuda-10.1` builds and see if that fixes all the failing tests for Zoltan2, Muelu (#5033), and Teko (#5035).  I will create a PR.

**Comment by nmhamster** [comment]
@bartlettroscoe - I think we should set it in the modules on the machine for now, don’t you?

**Comment by bartlettroscoe** [comment]
@nmhamster said:

>  I think we should set it in the modules on the machine for now, don’t you?

If you want to set `export UCX_MEMTYPE_CACHE=n` in the CUDA 10.1 modules on 'white', that is fine.  Just please let me know if that is what you are going to do and that we will watch to see if this fixes things.

**Comment by nmhamster** [comment]
@bartlettroscoe / @srajama1 - module files are updated on White. Please let me know if you notice anything else suspicious.

**Comment by bartlettroscoe** [comment]
Just logged on to 'white' and did:

```
$ cd Trilinos

$ git pull

$ . cmake/std/atdm/load-env.sh cuda-10.1
Hostname 'white11' matches known ATDM host 'white' and system 'ride'
Setting compiler and build options for buld name 'cuda-10.1'
Using white/ride compiler stack CUDA-10.1_GNU-7.2.0 to build DEBUG code with Kokkos node type CUDA and KOKKOS_ARCH=Power8,Pascal60

$ set | grep UCX_MEMTYPE_CACHE
UCX_MEMTYPE_CACHE=n
```

I will run an experimental build to see if this causes any problems.

**Comment by nmhamster** [comment]
Here are results from the Zoltan build I ran to check the module this morning (below). Obviously the more exhaustive tests you are doing will be needed to confirm a general fix.

```
108/112 Test #108: Zoltan2_directoryTest_KokkosSimple_MPI_4 .................   Passed    3.08 sec
        Start 109: Zoltan2_directoryTest_findUniqueGids.cpp_MPI_4
109/112 Test #109: Zoltan2_directoryTest_findUniqueGids.cpp_MPI_4 ...........   Passed    3.12 sec
        Start 110: Zoltan2_block_MPI_4
110/112 Test #110: Zoltan2_block_MPI_4 ......................................   Passed    2.98 sec
        Start 111: Zoltan2_kokkosBlock_MPI_4
111/112 Test #111: Zoltan2_kokkosBlock_MPI_4 ................................   Passed    3.24 sec
        Start 112: Zoltan2_rcb_C_MPI_4
112/112 Test #112: Zoltan2_rcb_C_MPI_4 ......................................   Passed    2.73 sec

100% tests passed, 0 tests failed out of 112

Subproject Time Summary:
Zoltan2    = 1424.09 sec*proc (112 tests)

Total Test time (real) = 376.62 sec
```

**Comment by bartlettroscoe** [comment]
I just ran an experimental build with the updated env and submitted to:

* https://testing.sandia.gov/cdash/index.php?project=Trilinos&parentid=4981429

and it looks like the Zoltan2 tests are now passing.  But we are seeing Teko and MueLu tests, but those are covered in #5033 and #5035.

Let's wait for the official nightly build to show these passing tomorrow on CDash and in our summary email (#2933) and then close this issue?

**Comment by kddevin** [comment]
Thanks, @nmhamster and @bartlettroscoe , for addressing this issue!
When I looked at the issue on Monday, I couldn't see any Zoltan2-specific cause.

**Comment by bartlettroscoe** [comment]
As shown in [this query](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-white-ride-cuda-10.1-gnu-7.2.0-release-debug&field2=testname&compare2=65&value2=Zoltan2_directoryTest_&field3=site&compare3=61&value3=white&field4=buildstarttime&compare4=84&value4=2019-06-04T04%3A01%3A00UTC&field5=buildstarttime&compare5=83&value5=2019-05-05T04%3A01%3A00UTC) all of these tests have been passing in last 30 days since we set the env var `UCX_MEMTYPE_CACHE=n`.

Closing as fixed!

**Comment by bartlettroscoe** [comment]
Closing for real this time!
