### ISSUE TITLE
Tpetra:  fix deprecated case in RowMatrix::add

### ISSUE THREAD

**Issue by kddevin** [trilinos/Trilinos#5042]
## Bug Report
@trilinos/tpetra

relate to #4701 

### Description

One case of RowMatrix::add is not handled correctly in the deprecation of DynamicProfile.  This case is rarely, if ever, used.  we should either fix it and test it so it works, or throw an error to state we don't support it.  (I prefer the first.)

for details and a proposed solution, see https://github.com/trilinos/Trilinos/pull/4701/files/cfd349400d2faa8009822abf165b7c7cfcfa7e74#diff-c109d71d09ef95780e788d789a64f2d9

**Comment by GeoffDanielson** [comment]
I have this fixed in the branch "5042_deprecated_row_add"

**Comment by mhoemmen** [comment]
@GeoffDanielson Best practice is to let develop-to-master promotion close the issue automatically, because the commit that closes the issue has a phrase like `"fix #NNNN` in it (where `#NNNN` is the GitHub issue number to close).
