### ISSUE TITLE
PackageName:  Tpetra, Teuchos, etc. compiler warnings being treated as errors for unused functions in Sierra - Trilinos integration

### ISSUE THREAD

**Issue by ajpowelsnl** [trilinos/Trilinos#5045]
## Bug Report
@trilinos/\<PackageName\>

Sierra - Trilinos integration is failing because the compiler is treating warnings as errors in these :

-Werror=unused-function

There are ~ 8000 instances of this type of error (see enclosed log):
grep -c [-Werror=unused-function] sierra_trilinos_int_042919.txt
8081

[sierra_trilinos_int_042919.txt.zip](https://github.com/trilinos/Trilinos/files/3131953/sierra_trilinos_int_042919.txt.zip)

### Description
Representative error --

/scratch/ajpowel/sierra_code_042619/fuego/src/nonconformal/Afgo_NonConformalDiffusiveScalarAlgorithm.C:16:
/scratch/ajpowel/sierra_code_042619/objs/tpls/trilinos_tpls/b2ed81b8c8472240/include/Tpetra_CrsMatrix_def.hpp:89:3: error: 'std::shared_ptr<Tpetra::Details::CommRequest> Tpetra::{anonymous}::iallreduceIntRaw(const int&, int&, Teuchos::EReductionType, const Teuchos::Comm<int>&)' defined but not used [-Werror=unused-function]
   iallreduceIntRaw (const int& localValue,
   ^~~~~~~~~~~~~~~~

### Steps to Reproduce

1) Set your development environment; module load sierra-devel; 
2) Clone a ${SIERRA_CODE_PROJECT};
3) cd to the ${SIERRA_CODE_PROJECT};
4) rm -fr TPLs_src/Trilinos;
5) git clone github.com/Trilinos/trilinos TPLs_src/Trilinos
6) bake --verbose trilinos-integration=on

**Comment by mhoemmen** [comment]
@trilinos/framework 

Thanks for filing this issue.  I have fixed two of these warnings (#5038) but doing so in the whole Trilinos code base would take a lot of time and probably not add much value compared to other work Trilinos developers could do.  I would recommend `-Wno-error=unused-function`: the warnings would still appear, but would no longer break the build.

**Comment by kddevin** [comment]
Actually, @mhoemmen 's changes in #5038 should remove all of the unused function warnings.
PR #5046 will remove the shadow warning from Tpetra.
Most remaining errors appear to come  from stk.
For the final error in the file, do not include Tpetra_DefaultPlatform.hpp in your  source code.

**Comment by ajpowelsnl** [comment]
Hi Karen and Mark,

Just to make sure I’m clear before proceeding (with another attempt to integrate the latest Trilinos):


  *   You have updated the compiler flags in Trilinos, such that warnings will not result in errors;
  *   We should delete the header (Tpetra_DefaultPlatform.hpp) you mention below;

Assuming I’m in the ballpark, then I’ll give it another go.

Many thanks!

Best,

AJP

**Comment by kddevin** [comment]
@ajpowelsnl 

The user (you) controls the warnings-as-errors flags; we cannot control that.
Rather, @mhoemmen rewrote parts of the code to avoid the spurious unused function warnings, so you should not see them anymore.

The file Tpetra_DefaultPlatform.hpp  does not exist in the Trilinos repository.  So no files in your application or in any other TPL should include it.  That change needs to be done on the application or other TPL side.

I think this issue is resolved, so I will close it.  If this issue persists, please re-open.

**Comment by bartlettroscoe** [comment]
Many Trilinos developers don't have access to Sierra machines or development environments (and the new Engineering Workspaces seem to be problematic, at least from my recent experience).

@trilinos/framework,

It would be great if the Triinos PR build(s) could reproduce these warnings so we could clean them up in those builds and the protect them as per #3178.
