### ISSUE TITLE
Trilinos Framework: Change GCC 4.8.4 PR build to use static libraries

### ISSUE THREAD

**Issue by jwillenbring** [trilinos/Trilinos#5058]
## Enhancement
@trilinos/framework 

Our PR testing does not currently include any static library builds. There are important use cases for static libraries, so we want to change one build to use static libraries. The GCC 4.8.4 MPI build has been chosen for this enhancement to the PR test suite.

**Comment by prwolfe** [comment]
Resolved with merge of #5111
