### ISSUE TITLE
PackageName:  Tpetra

### ISSUE THREAD

**Issue by ajpowelsnl** [trilinos/Trilinos#5059]
## Bug Report
@trilinos/\<PackageName\>

  COMPILE
/scratch/sierra/sierra_master/objs/apps/scefire/votd/gcc-7.2.0/release/address-model-64/mpi-openmpi/runtime-link-shared/threading-multi/trilinos-integration-on/app_scefire.o
In file included from
/scratch/sierra/sierra_master/TPLs_src/radlib/Nov-2017/src/KrylovTransportSolvers/krylovTransportSolve.hh:25:0,
                  from
/scratch/sierra/sierra_master/scefire/src/driver/scefire.cc:28:
/scratch/sierra/sierra_master/TPLs_src/radlib/Nov-2017/src/KrylovTransportSolvers/solveLinearSystem.hh:23:10:
fatal error: Tpetra_DefaultPlatform.hpp: No such file or directory
  #include "Tpetra_DefaultPlatform.hpp"
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
gmake: ***
[/scratch/sierra/sierra_master/objs/apps/scefire/votd/gcc-7.2.0/release/address-model-64/mpi-openmpi/runtime-link-shared/threading-multi/trilinos-integration-on/app_scefire.o]
Error 1
     XMLCONCAT
/scratch/sierra/sierra_master/bin/contact_usersub_signatures.map

### Description

Error caused Sierra build failure when attempting to integrate Trilinos master. 

### Steps to Reproduce
See Sierra - Trilinos integration steps communicated in previous bug reports.

**Comment by kddevin** [comment]
The file 
/scratch/sierra/sierra_master/TPLs_src/radlib/Nov-2017/src/KrylovTransportSolvers/solveLinearSystem.hh
should not include 
Tpetra_DefaultPlatform.hpp

The solveLinearSystem.hh file is not in Trilinos; the radlib developers need to remove this include statement.

**Comment by mhoemmen** [comment]
@kddevin I submitted a patch to fix that in radlib; the patch is going through the equivalent of PR testing now.

**Comment by mhoemmen** [comment]
@ajpowelsnl @Mark-E-Hamilton My change to radlib passed tests and has been pushed into Sierra master.
