### ISSUE TITLE
Tpetra: Failing Cuda unit tests, due to calling Kokkos::initialize after Kokkos::finalize

### ISSUE THREAD

**Issue by ndellingwood** [trilinos/Trilinos#506]
@mhoemmen The following Tpetra unit tests fail with Cuda/7.5.18

TpetraCore_ExpBlockView_MPI_1
TpetraCore_Map_removeEmptyProcesses_MPI_4

Sample error message:
Calling Cuda::initialize after Cuda::finalize is illegal

Kokkos has always forbidden calling Kokkos::initialize after Kokkos::finalize has been called.  However, recent Kokkos changes explicitly check for this.  We need to fix the tests in question in order to merge Kokkos develop into Kokkos master, and in order to snapshot the latest Kokkos into Trilinos.

**Comment by mhoemmen** [comment]
I've got a fix ready for TpetraCore_ExpBlockView_MPI_1.  Not pushed yet.  Starting on the second test.  Will push once finished.

**Comment by mhoemmen** [comment]
Second test also had an obvious fix (don't construct Node instances directly; let Map do it, so it can use the static Node instance that sticks around).

**Comment by mhoemmen** [comment]
Running check-in tests now.

**Comment by mhoemmen** [comment]
Pushed -- please close once it works for you.  CUDA tests pass for me.
