### ISSUE TITLE
Tpetra:  Deprecated DynamicProfile used without deprecation guards

### ISSUE THREAD

**Issue by kddevin** [trilinos/Trilinos#5065]
## Bug Report
@trilinos/tpetra 

### Description
DynamicProfile is a deprecated feature.
It is used in Tpetra_CrsMatrix_decl.hpp without deprecation guards.
https://github.com/trilinos/Trilinos/blob/ec7ddad27cbfca383fb4c70f8beeba6193739853/packages/tpetra/core/src/Tpetra_CrsMatrix_decl.hpp#L5039

Thus, building with TPETRA_ENABLE_DEPRECATED_CODE=OFF fails.

Related to #4701

### Steps to Reproduce

Build Tpetra with TPETRA_ENABLE_DEPRECATED_CODE=OFF.
I am building with many other packages; I don't know if they are needed to see the error.
```
-D Tpetra_ENABLE_DEPRECATED_CODE:BOOL=OFF \
-D Teuchos_HIDE_DEPRECATED_CODE:BOOL=ON \
\
-D Trilinos_ENABLE_Stokhos:BOOL=ON \
-D Trilinos_ENABLE_Nox:BOOL=ON \
-D Trilinos_ENABLE_ROL:BOOL=ON \
-D ROL_ENABLE_EXAMPLES:BOOL=OFF \
-D Trilinos_ENABLE_MiniTensor:BOOL=OFF \
-D ROL_ENABLE_MiniTensor:BOOL=OFF \
-D Trilinos_ENABLE_Panzer:BOOL=ON \
-D Trilinos_ENABLE_PanzerAdaptersSTK:BOOL=OFF \
-D Trilinos_ENABLE_PanzerAdaptersIOSS:BOOL=OFF \
-D Trilinos_ENABLE_Thyra:BOOL=ON \
-D Trilinos_ENABLE_MueLu:BOOL=ON \
-D Trilinos_ENABLE_Anasazi:BOOL=ON \
-D Trilinos_ENABLE_Belos:BOOL=ON \
-D Trilinos_ENABLE_TrilinosCouplings:BOOL=ON \
-D Trilinos_ENABLE_STKIO:BOOL=OFF \
-D Trilinos_ENABLE_STKUtil:BOOL=OFF \
```

**Comment by kddevin** [comment]
This one may be difficult to fix, as it is used without max number of entries per row throughout the Trilinos stack.  We may need help from other package developers to fix it correctly.

Not sure how this one got through testing with TPETRA_ENABLE_DEPRECATED_CODE=OFF, though, as we use this method in Tpetra tests.

**Comment by william76** [comment]
FYI, I don't think any of the PR tests ever set `TPETRA_ENABLE_DEPRECATED_CODE=OFF` so folks will probably want to run a sanity check on this locally before submitting PR's

**Comment by kddevin** [comment]
@mhoemmen @jhux2 @csiefer2 @GeoffDanielson 
Let's discuss possible solutions here.

From the Tpetra side, I think the fix is straightforward:
-  In createCrs*, require the user to provide a maxNumEntriesPerRow (deprecating the default value of 0) and then use StaticProfile
-  In Tpetra tests, most tests provide the maxNumEntriesPerRow; for any that don't, we can figure out the appropriate value

For packages that use Tpetra::createCrs*, figuring out the appropriate value may be more difficult.
I see use of createCrsMatrix and createCrsGraph in 

- @trilinos/muelu (MueLu_MatLabUtils_def.hpp)
- @trilinos/teko for MatrixMatrix multiplication, building block matrices, tests; some instances provide a size but many do not
- @trilinos/stokhos (Stokhos_Tpetra_Utilities_UQ_PCE.hpp)

**Comment by jhux2** [comment]
> For packages that use Tpetra::createCrs*, figuring out the appropriate value may be more difficult.
> I see use of createCrsMatrix and createCrsGraph in
> 
> * @trilinos/muelu (MueLu_MatLabUtils_def.hpp)

This looks simple to fix.  I'll submit a PR.

**Comment by mhoemmen** [comment]
@kddevin @jhux2 Teko should just use the sparse matrix-matrix interface that creates and returns a new CrsMatrix, not the "create an empty matrix and then fill it in" interface which is not idiomatic C++ anyway.

**Comment by kddevin** [comment]
Thanks @mhoemmen 

Can you point me to this interface?  All I see is interface that requires a matrix for C.
https://github.com/trilinos/Trilinos/blob/f58da722e20f5e1c72954f5e16081cce0c2826ec/packages/tpetra/core/ext/TpetraExt_MatrixMatrix_decl.hpp#L97

**Comment by mhoemmen** [comment]
@kddevin Huh, I didn't realize we didn't have one of those.  @trilinos/muelu I thought we had an interface like that?
