### ISSUE TITLE
MueLu: separate setup and solve of regionMG coarse level solver

### ISSUE THREAD

**Issue by mayrmt** [trilinos/Trilinos#5072]
## Enhancement
@trilinos/muelu 

On the coarse level, we need to perform a direct solve on the composite system. Right now, this is done by creating a Amesos2 KLU solver in every visit to the coarsest level.

Steps to do:
- Move the setup phase of the Amesos2 KLU solver to the setup of the hierarchy and store the factorizations
- Only leave the apply phase of the direct solver in the V-Cycle

Overall, this aims at reducing unnecessary (and duplicate) cost.

**Comment by mayrmt** [comment]
@lucbv I have done this, however when pulling in new changes from GitHub, my build broke. This will probably take some time to fix, especially there are some other issues with build problems in develop apparently.

**Comment by lucbv** [comment]
OK no rush, I put a review on the PR.
I am just glad we are looking into it instead of leaving it as a todo item on our list!

**Comment by lucbv** [comment]
@mayrmt I'm guessing we can close this issue with the merge of PR #5087

**Comment by mayrmt** [comment]
PR #5087 has been merged, this closing this issue.
