### ISSUE TITLE
Xpetra: Cloner_UnitTests test failure with Cuda & Serial enabled

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#508]
@trilinos/xpetra 

This depends on the fix for #506.  The Tpetra part of this test passes now. The Epetra part of this test fails:

13: 0. Cloner_int_int_NodeType_MapCloneTpetra_UnitTest ... \[Passed\] (0.977 sec)
13: 1. Cloner_int_int_NodeType_MapCloneEpetra_UnitTest ...
13:
13: p=0: *** Caught standard std::exception of type 'Xpetra::Exceptions::BadCast' :
13:
13: .../Trilinos/packages/xpetra/src/Map/Xpetra_MapFactory.hpp:255:
13:
13: Throw number = 1
13:
13: Throw test that evaluated to true: 1
13:
13: Epetra can only be used with Scalar=double and LocalOrdinal=GlobalOrdinal=int on a serial node
13: \[FAILED\] (0.000208 sec) Cloner_int_int_NodeType_MapCloneEpetra_UnitTest
13: Location: .../Trilinos/packages/xpetra/test/Cloner/Cloner_UnitTests.cpp:144
13:
13: 2. Cloner_int_long_NodeType_MapCloneTpetra_UnitTest ... \[Passed\] (0.00165 sec)
13:
13: The following tests FAILED:
13: 1. Cloner_int_int_NodeType_MapCloneEpetra_UnitTest ...

**Comment by mhoemmen** [comment]
Fix should be easy: In the MapCloneEpetra test, skip the test (at run time even) unless N1 and N2 are both the "serial node" type (whatever that means in Xpetra terms).

**Comment by mhoemmen** [comment]
"serial node" type means Xpetra::EpetraNode, which is a typedef in xpetra/src/Map/Xpetra_Map.hpp.  It is either Kokkos::Compat::KokkosOpenMPWrapperNode or Kokkos::Compat::KokkosSerialWrapperNode, depending on configuration options.  (In fact, those options aren't quite right -- they should check Kokkos macros to see whether the Node type in question is enabled.  Right now they just check EPETRA_HAVE_OMP.)

**Comment by mhoemmen** [comment]
I implemented the above fix.  It works (the test now passes) when Cuda and Serial are enabled.  I'm running the check-in tests now.

**Comment by tawiesn** [comment]
@mhoemmen  Thanks working on this.
