### ISSUE TITLE
Xpetra: EpetraNode typedef definition should check Kokkos macros too

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#509]
Xpetra's "serial node" type means Xpetra::EpetraNode, which is a typedef in xpetra/src/Map/Xpetra_Map.hpp.  It is either Kokkos::Compat::KokkosOpenMPWrapperNode or Kokkos::Compat::KokkosSerialWrapperNode, depending on configuration options.  

Currently, those options check the EPETRA_HAVE_OMP macro to decide whether to use KokkosOpenMPWrapperNode as EpetraNode.  They should _also_ check the Kokkos macros KOKKOS_HAVE_OPENMP and KOKKOS_HAVE_SERIAL.  It is entirely possible for either or both to be disabled Kokkos, yet for Epetra to be enabled.

**Comment by tawiesn** [comment]
@mhoemmen You are right: one should _also_ check the Kokkos macros KOKKOS_HAVE_OPENMP and KOKKOS_HAVE_SERIAL _if (and only if?)_ Kokkos is enabled. One could have an Epetra only build without Kokkos enabled, but OpenMP support.

**Comment by mhoemmen** [comment]
@tawiesn Does Xpetra have a stub Kokkos::OpenMP (or a stub KokkosOpenMPWrapperNode) when Kokkos is not enabled?  Otherwise, it wouldn't work to have an Epetra-only build without Kokkos being enabled.

**Comment by tawiesn** [comment]
@mhoemmen In xpetra/src/FakeKokkos there is a Kokkos_SerialNode.hpp which contains a stub Kokkos::Compat::KokkosSerialWrapperNode. As far as i remember we don't have a stub Kokkos::OpenMP (maybe we need that, too?). I think we've never tested an Epetra only built with Kokkos disabled but Epetra built with OpenMP support. At that time when we implemented that FakeKokkos thing i didn't even know that Epetra has OpenMP support.

**Comment by mhoemmen** [comment]
Epetra's OpenMP support is pretty limited.  By default, you'll get sparse mat-vecs and vector updates (axpy).  You have to set a nondefault CMake option to use OpenMP for vector dot products and norms in Epetra (since that changes the order of floating-point operations).

**Comment by mhoemmen** [comment]
> @mhoemmen In xpetra/src/FakeKokkos there is a Kokkos_SerialNode.hpp which contains a stub Kokkos::Compat::KokkosSerialWrapperNode. As far as i remember we don't have a stub Kokkos::OpenMP (maybe we need that, too?).

The main benefit of having a stub Kokkos::OpenMP would be doing OpenMP-threaded multigrid with Epetra objects.  Not sure if Epetra does first-touch allocation, though.

**Comment by tawiesn** [comment]
@mhoemmen @jhux2 Do we want to allow users to do an Epetra-only build with OpenMP support (but Kokkos disabled)? Are there concrete users requesting that? I personally tend to tell people to use Tpetra (with Kokkos enabled) when they want to run with OpenMP...

**Comment by mhoemmen** [comment]
> Do we want to allow users to do an Epetra-only build with OpenMP support (but Kokkos disabled)? 

If the Node name has "OpenMP" in it, users will expect OpenMP things to happen.  If all OpenMP in MueLu happens through Kokkos, and Kokkos doesn't exist, then MueLu can't do OpenMP.  That would violate users' expectations.

Epetra has very limited OpenMP support.  AztecOO does not use it at all (it just accesses Epetra data structures), and ML and Ifpack only use it through the sparse mat-vec and some vector operations.  Thus, it would not change current behavior if MueLu decides not to do OpenMP with Epetra objects, when Kokkos is disabled.

**Comment by tawiesn** [comment]
I think another important aspect one must not forget is, that Epetra itself has no node type, that is, OpenMP support in Epetra is enabled by a compile flag at compilation time. In the Epetra stack for Xpetra we just need a dummy node type which is somehow consistent with the Tpetra design. I've introduced the "EpetraNode" typedef (which is either Kokkos::Serial or Kokkos::OpenMP depending on the Epetra compile flag). At least if ETI is enabled there is always only one valid EpetraNode, that is the user cannot create a Xpetra object with the Epetra stack underneath for a node different than EpetraNode. A user is not supposed to hard-code a certain node type in his application but to use the content of the EpetraNode typedef to choose the appropriate node. What might be missing here is, that Epetra was compiled with OpenMP support, Kokkos is enabled (but the Kokkos::OpenMP node is disabled). I think, this is the case @mhoemmen is referring to?

If Kokkos is disabled (that is there is also no Tpetra), there is the FakeKokkos::Serial node. The question is, whether we accept this to be the (only) dummy node that is used to create Xpetra objects based on the Epetra stack. The user might get Epetra with OpenMP support underneath (even though the Node is called "Serial"). This would mean, that one would introduce a second stub node "OpenMP" in FakeKokkos. Xpetra::EpetraNode would again point either to Serial or OpenMP depending on the compiler flag for Epetra.

**Comment by mhoemmen** [comment]
> What might be missing here is, that Epetra was compiled with OpenMP support, Kokkos is enabled (but the Kokkos::OpenMP node is disabled). I think, this is the case @mhoemmen is referring to?

That's right.  My main concern is that everything compiles.  Both Epetra and Kokkos turn on their OpenMP support by default if Trilinos' OpenMP support is enabled.  However, users can turn off OpenMP support independently in each of these packages.
