### ISSUE TITLE
Pamgen: Remove Build Warnings

### ISSUE THREAD

**Issue by ZUUL42** [trilinos/Trilinos#5104]
## Enhancement
@trilinos/pamgen 

Issue #3178 is working toward turning Warnings as Errors on for _all_ packages in order in ensure Trilinos maintains a high level of SQA practices across the project.
Currently Pamgen has a warning that need to be handled before we can set Werror for Pamgen and eventually all packages.

A recent test build was performed with -Werror set. [The CDash report can be found here.](https://testing.sandia.gov/cdash/index.php?project=Trilinos&parentid=4989737&filtercount=2&showfilters=1&field1=buildstamp&compare1=63&value1=Experimental&field2=buildstarttime&compare2=83&value2=2019/04/30&filtercombine=and)
Once the Pamgen build doesn't emit any warnings that will be promoted to errors, [we can set `-Werror` in the GCC 7.2.0 automated build](https://github.com/ZUUL42/Trilinos/tree/Werror_Pamgen).

**Comment by csiefer2** [comment]
Looks like all you have to do is comment out one line.  Give it a go!
