### ISSUE TITLE
Teuchos TimeMonitor summarize prints zeros

### ISSUE THREAD

**Issue by srajama1** [trilinos/Trilinos#512]
Teuhos TimeMonitor summarize() call returns zeros for all the timers from Amesos2. However calling solver->printSolution in Amesos2 shows the actual times and number of calls for the Amesos2 timers.

The behavior was first exhibited in ROL. I have modified the a simple example in Amesos2 to demonstrate this behavior as well. Just run the example with --print-solution to see the problem.

The example code is in
packages/amesos2/example/SimpleSolve_File.cpp

CCing interested parties  @bartlettroscoe  @mhoemmen @dridzal

**Comment by mhoemmen** [comment]
It's been nearly 4 years so I'm closing this issue.  Please feel free to reopen if it's still a problem.
