### ISSUE TITLE
Stokhos/Tpetra/MueLu:  Missing symbols in static library build

### ISSUE THREAD

**Issue by prwolfe** [trilinos/Trilinos#5120]
## Bug Report
@trilinos/stokhos @trilinos/tpetra 

### Description
I am building using static libraries (see PR #5111 and issue #5058). At link time I get

> [ 94%] Linking CXX executable Stokhos_TpetraCrsMatrixMPVectorUnitTest_Serial.exe
> ../../src/libstokhos_tpetra_mp_16_serial.a(Tpetra_MultiVector_MP_Vector_16_Serial.cpp.o): In function `void (anonymous namespace)::multiVectorNormImpl<Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::Serial> >, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >(Tpetra::MultiVector<Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::Serial> >, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::mag_type*, Tpetra::MultiVector<Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::Serial> >, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >&, Tpetra::Details::EWhichNorm)':
/scratch/prwolfe/trilinos/Trilinos/packages/tpetra/core/src/Tpetra_MultiVector_def.hpp:387: undefined reference to `void Tpetra::Details::normImpl<Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::Serial> >, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::Serial> > >(Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::Serial> >*, Kokkos::View<Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::Serial> ><Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace> > const**> const&, Tpetra::Details::EWhichNorm, Teuchos::ArrayView<unsigned long const> const&, bool, bool, Tpetra::Details::EWhichNorm::Comm<int> const*)'
/scratch/prwolfe/trilinos/Trilinos/packages/tpetra/core/src/Tpetra_MultiVector_def.hpp:374: undefined reference to `void Tpetra::Details::normImpl<Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::Serial> >, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::Serial> > >(Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::Serial> >*, Kokkos::View<Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::Serial> ><Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace> > const**> const&, Tpetra::Details::EWhichNorm, Teuchos::ArrayView<unsigned long const> const&, bool, bool, Tpetra::Details::EWhichNorm::Comm<int> const*)'
../../../muelu/src/libmuelu_lgn.a(MueLu_IsorropiaInterface.cpp.o): In function `MueLu::IsorropiaInterface<int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::Build(MueLu::Level&) const':
/scratch/prwolfe/trilinos/Trilinos/packages/muelu/src/Rebalancing/MueLu_IsorropiaInterface_def.hpp:145: undefined reference to `MueLu::AmalgamationFactory<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::DOFGid2NodeId(int, int, int, int)'
/scratch/prwolfe/trilinos/Trilinos/packages/muelu/src/Rebalancing/MueLu_IsorropiaInterface_def.hpp:158: undefined reference to `MueLu::AmalgamationFactory<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::DOFGid2NodeId(int, int, int, int)'
../../../muelu/src/libmuelu_lgn.a(MueLu_IsorropiaInterface.cpp.o): In function `MueLu::IsorropiaInterface<int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::Build(MueLu::Level&) const':
/scratch/prwolfe/trilinos/Trilinos/packages/muelu/src/Rebalancing/MueLu_IsorropiaInterface_def.hpp:145: undefined reference to `MueLu::AmalgamationFactory<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::DOFGid2NodeId(long long, int, long long, long long)'
/scratch/prwolfe/trilinos/Trilinos/packages/muelu/src/Rebalancing/MueLu_IsorropiaInterface_def.hpp:158: undefined reference to `MueLu::AmalgamationFactory<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::DOFGid2NodeId(long long, int, long long, long long)'
../../../muelu/src/libmuelu_lgn.a(MueLu_IsorropiaInterface.cpp.o): In function `MueLu::IsorropiaInterface<int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP, Kokkos::HostSpace> >::Build(MueLu::Level&) const':
/scratch/prwolfe/trilinos/Trilinos/packages/muelu/src/Rebalancing/MueLu_IsorropiaInterface_def.hpp:145: undefined reference to `MueLu::AmalgamationFactory<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP, Kokkos::HostSpace> >::DOFGid2NodeId(int, int, int, int)'
/scratch/prwolfe/trilinos/Trilinos/packages/muelu/src/Rebalancing/MueLu_IsorropiaInterface_def.hpp:158: undefined reference to `MueLu::AmalgamationFactory<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP, Kokkos::HostSpace> >::DOFGid2NodeId(int, int, int, int)'
../../../muelu/src/libmuelu_lgn.a(MueLu_IsorropiaInterface.cpp.o): In function `MueLu::IsorropiaInterface<int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP, Kokkos::HostSpace> >::Build(MueLu::Level&) const':
/scratch/prwolfe/trilinos/Trilinos/packages/muelu/src/Rebalancing/MueLu_IsorropiaInterface_def.hpp:145: undefined reference to `MueLu::AmalgamationFactory<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP, Kokkos::HostSpace> >::DOFGid2NodeId(long long, int, long long, long long)'
/scratch/prwolfe/trilinos/Trilinos/packages/muelu/src/Rebalancing/MueLu_IsorropiaInterface_def.hpp:158: undefined reference to `MueLu::AmalgamationFactory<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP, Kokkos::HostSpace> >::DOFGid2NodeId(long long, int, long long, long long)'
collect2: error: ld returned 1 exit status
make[2]: *** [packages/stokhos/test/UnitTest/Stokhos_TpetraCrsMatrixMPVectorUnitTest_Serial.exe] Error 1
make[2]: Target `packages/stokhos/test/UnitTest/CMakeFiles/Stokhos_TpetraCrsMatrixMPVectorUnitTest_Serial.dir/build' not remade because of errors.
make[1]: *** [packages/stokhos/test/UnitTest/CMakeFiles/Stokhos_TpetraCrsMatrixMPVectorUnitTest_Serial.dir/all] Error 2
[ 95%] Linking CXX executable Stokhos_TpetraCrsMatrixUQPCEUnitTest_Serial.exe
../../src/libstokhos_tpetra_pce_serial.a(Tpetra_MultiVector_UQ_PCE_Serial.cpp.o): In function `void (anonymous namespace)::multiVectorNormImpl<Sacado::UQ::PCE<Stokhos::DynamicStorage<int, double, Kokkos::Serial> >, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >(Tpetra::MultiVector<Sacado::UQ::PCE<Stokhos::DynamicStorage<int, double, Kokkos::Serial> >, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::mag_type*, Tpetra::MultiVector<Sacado::UQ::PCE<Stokhos::DynamicStorage<int, double, Kokkos::Serial> >, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >&, Tpetra::Details::EWhichNorm)':
/scratch/prwolfe/trilinos/Trilinos/packages/tpetra/core/src/Tpetra_MultiVector_def.hpp:387: undefined reference to `void Tpetra::Details::normImpl<Sacado::UQ::PCE<Stokhos::DynamicStorage<int, double, Kokkos::Serial> >, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, double>(double*, Kokkos::View<Sacado::UQ::PCE<Stokhos::DynamicStorage<int, double, Kokkos::Serial> ><Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace> > const**> const&, Tpetra::Details::EWhichNorm, Teuchos::ArrayView<unsigned long const> const&, bool, bool, Tpetra::Details::EWhichNorm::Comm<int> const*)'
/scratch/prwolfe/trilinos/Trilinos/packages/tpetra/core/src/Tpetra_MultiVector_def.hpp:374: undefined reference to `void Tpetra::Details::normImpl<Sacado::UQ::PCE<Stokhos::DynamicStorage<int, double, Kokkos::Serial> >, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, double>(double*, Kokkos::View<Sacado::UQ::PCE<Stokhos::DynamicStorage<int, double, Kokkos::Serial> ><Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace> > const**> const&, Tpetra::Details::EWhichNorm, Teuchos::ArrayView<unsigned long const> const&, bool, bool, Tpetra::Details::EWhichNorm::Comm<int> const*)'
collect2: error: ld returned 1 exit status
make[2]: *** [packages/stokhos/test/UnitTest/Stokhos_TpetraCrsMatrixUQPCEUnitTest_Serial.exe] Error 1
make[2]: Target `packages/stokhos/test/UnitTest/CMakeFiles/Stokhos_TpetraCrsMatrixUQPCEUnitTest_Serial.dir/build' not remade because of errors.
make[1]: *** [packages/stokhos/test/UnitTest/CMakeFiles/Stokhos_TpetraCrsMatrixUQPCEUnitTest_Serial.dir/all] Error 2
 95%] Linking CXX executable Stokhos_TpetraCrsMatrixMPVectorUnitTest_OpenMP.exe
../../src/libstokhos_tpetra_mp_16_openmp.a(Tpetra_MultiVector_MP_Vector_16_OpenMP.cpp.o): In function `void (anonymous namespace)::multiVectorNormImpl<Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::OpenMP> >, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP, Kokkos::HostSpace> >(Tpetra::MultiVector<Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::OpenMP> >, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP, Kokkos::HostSpace> >::mag_type*, Tpetra::MultiVector<Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::OpenMP> >, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP, Kokkos::HostSpace> >&, Tpetra::Details::EWhichNorm)':
/scratch/prwolfe/trilinos/Trilinos/packages/tpetra/core/src/Tpetra_MultiVector_def.hpp:387: undefined reference to `void Tpetra::Details::normImpl<Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::OpenMP> >, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::OpenMP, Kokkos::HostSpace>, Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::OpenMP> > >(Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::OpenMP> >*, Kokkos::View<Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::OpenMP> ><Kokkos::LayoutLeft, Kokkos::Device<Kokkos::OpenMP, Kokkos::HostSpace> > const**> const&, Tpetra::Details::EWhichNorm, Teuchos::ArrayView<unsigned long const> const&, bool, bool, Tpetra::Details::EWhichNorm::Comm<int> const*)'
/scratch/prwolfe/trilinos/Trilinos/packages/tpetra/core/src/Tpetra_MultiVector_def.hpp:374: undefined reference to `void Tpetra::Details::normImpl<Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::OpenMP> >, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::OpenMP, Kokkos::HostSpace>, Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::OpenMP> > >(Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::OpenMP> >*, Kokkos::View<Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::OpenMP> ><Kokkos::LayoutLeft, Kokkos::Device<Kokkos::OpenMP, Kokkos::HostSpace> > const**> const&, Tpetra::Details::EWhichNorm, Teuchos::ArrayView<unsigned long const> const&, bool, bool, Tpetra::Details::EWhichNorm::Comm<int> const*)'
../../../muelu/src/libmuelu_lgn.a(MueLu_IsorropiaInterface.cpp.o): In function `MueLu::IsorropiaInterface<int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::Build(MueLu::Level&) const':
/scratch/prwolfe/trilinos/Trilinos/packages/muelu/src/Rebalancing/MueLu_IsorropiaInterface_def.hpp:145: undefined reference to `MueLu::AmalgamationFactory<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::DOFGid2NodeId(int, int, int, int)'
/scratch/prwolfe/trilinos/Trilinos/packages/muelu/src/Rebalancing/MueLu_IsorropiaInterface_def.hpp:158: undefined reference to `MueLu::AmalgamationFactory<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::DOFGid2NodeId(int, int, int, int)'
../../../muelu/src/libmuelu_lgn.a(MueLu_IsorropiaInterface.cpp.o): In function `MueLu::IsorropiaInterface<int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::Build(MueLu::Level&) const':
/scratch/prwolfe/trilinos/Trilinos/packages/muelu/src/Rebalancing/MueLu_IsorropiaInterface_def.hpp:145: undefined reference to `MueLu::AmalgamationFactory<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::DOFGid2NodeId(long long, int, long long, long long)'
/scratch/prwolfe/trilinos/Trilinos/packages/muelu/src/Rebalancing/MueLu_IsorropiaInterface_def.hpp:158: undefined reference to `MueLu::AmalgamationFactory<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::DOFGid2NodeId(long long, int, long long, long long)'
../../../muelu/src/libmuelu_lgn.a(MueLu_IsorropiaInterface.cpp.o): In function `MueLu::IsorropiaInterface<int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP, Kokkos::HostSpace> >::Build(MueLu::Level&) const':
/scratch/prwolfe/trilinos/Trilinos/packages/muelu/src/Rebalancing/MueLu_IsorropiaInterface_def.hpp:145: undefined reference to `MueLu::AmalgamationFactory<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP, Kokkos::HostSpace> >::DOFGid2NodeId(int, int, int, int)'
/scratch/prwolfe/trilinos/Trilinos/packages/muelu/src/Rebalancing/MueLu_IsorropiaInterface_def.hpp:158: undefined reference to `MueLu::AmalgamationFactory<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP, Kokkos::HostSpace> >::DOFGid2NodeId(int, int, int, int)'
../../../muelu/src/libmuelu_lgn.a(MueLu_IsorropiaInterface.cpp.o): In function `MueLu::IsorropiaInterface<int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP, Kokkos::HostSpace> >::Build(MueLu::Level&) const':
/scratch/prwolfe/trilinos/Trilinos/packages/muelu/src/Rebalancing/MueLu_IsorropiaInterface_def.hpp:145: undefined reference to `MueLu::AmalgamationFactory<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP, Kokkos::HostSpace> >::DOFGid2NodeId(long long, int, long long, long long)'
/scratch/prwolfe/trilinos/Trilinos/packages/muelu/src/Rebalancing/MueLu_IsorropiaInterface_def.hpp:158: undefined reference to `MueLu::AmalgamationFactory<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP, Kokkos::HostSpace> >::DOFGid2NodeId(long long, int, long long, long long)'
collect2: error: ld returned 1 exit status
make[2]: *** [packages/stokhos/test/UnitTest/Stokhos_TpetraCrsMatrixMPVectorUnitTest_OpenMP.exe] Error 1
make[2]: Target `packages/stokhos/test/UnitTest/CMakeFiles/Stokhos_TpetraCrsMatrixMPVectorUnitTest_OpenMP.dir/build' not remade because of errors.
make[1]: *** [packages/stokhos/test/UnitTest/CMakeFiles/Stokhos_TpetraCrsMatrixMPVectorUnitTest_OpenMP.dir/all] Error 2
[ 95%] Linking CXX executable Stokhos_TpetraCrsMatrixUQPCEUnitTest_OpenMP.exe
../../src/libstokhos_tpetra_pce_openmp.a(Tpetra_MultiVector_UQ_PCE_OpenMP.cpp.o): In function `void (anonymous namespace)::multiVectorNormImpl<Sacado::UQ::PCE<Stokhos::DynamicStorage<int, double, Kokkos::OpenMP> >, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP, Kokkos::HostSpace> >(Tpetra::MultiVector<Sacado::UQ::PCE<Stokhos::DynamicStorage<int, double, Kokkos::OpenMP> >, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP, Kokkos::HostSpace> >::mag_type*, Tpetra::MultiVector<Sacado::UQ::PCE<Stokhos::DynamicStorage<int, double, Kokkos::OpenMP> >, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP, Kokkos::HostSpace> >&, Tpetra::Details::EWhichNorm)':
/scratch/prwolfe/trilinos/Trilinos/packages/tpetra/core/src/Tpetra_MultiVector_def.hpp:387: undefined reference to `void Tpetra::Details::normImpl<Sacado::UQ::PCE<Stokhos::DynamicStorage<int, double, Kokkos::OpenMP> >, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::OpenMP, Kokkos::HostSpace>, double>(double*, Kokkos::View<Sacado::UQ::PCE<Stokhos::DynamicStorage<int, double, Kokkos::OpenMP> ><Kokkos::LayoutLeft, Kokkos::Device<Kokkos::OpenMP, Kokkos::HostSpace> > const**> const&, Tpetra::Details::EWhichNorm, Teuchos::ArrayView<unsigned long const> const&, bool, bool, Tpetra::Details::EWhichNorm::Comm<int> const*)'
/scratch/prwolfe/trilinos/Trilinos/packages/tpetra/core/src/Tpetra_MultiVector_def.hpp:374: undefined reference to `void Tpetra::Details::normImpl<Sacado::UQ::PCE<Stokhos::DynamicStorage<int, double, Kokkos::OpenMP> >, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::OpenMP, Kokkos::HostSpace>, double>(double*, Kokkos::View<Sacado::UQ::PCE<Stokhos::DynamicStorage<int, double, Kokkos::OpenMP> ><Kokkos::LayoutLeft, Kokkos::Device<Kokkos::OpenMP, Kokkos::HostSpace> > const**> const&, Tpetra::Details::EWhichNorm, Teuchos::ArrayView<unsigned long const> const&, bool, bool, Tpetra::Details::EWhichNorm::Comm<int> const*)'
collect2: error: ld returned 1 exit status
make[2]: *** [packages/stokhos/test/UnitTest/Stokhos_TpetraCrsMatrixUQPCEUnitTest_OpenMP.exe] Error 1
make[2]: Target `packages/stokhos/test/UnitTest/CMakeFiles/Stokhos_TpetraCrsMatrixUQPCEUnitTest_OpenMP.dir/build' not remade because of errors.
make[1]: *** [packages/stokhos/test/UnitTest/CMakeFiles/Stokhos_TpetraCrsMatrixUQPCEUnitTest_OpenMP.dir/all] Error 2

I know we have had previous issues like this relating to typedefs, not sure if that is happening here or not.

### Steps to Reproduce
1. SHA1:  Head of develop plus the code from #5111
1. Configure script:  Use gcc 4.8.4 and the instructions at https://github.com/trilinos/Trilinos/wiki/Reproducing-PR-Testing-Errors 
1. Configure log:  -DTrilinos_ENABLE_Stokkos

**Comment by prwolfe** [comment]
After I filed this I noticed two more instances of the same issue in TrilinosCouplings - TrilinosCouplings_fenl_ensemble.exe and  TrilinosCouplings_fenl_pce.exe.

**Comment by prwolfe** [comment]
Looking at the first symbol this seems to be a link order issue.

libstokhos_tpetra_mp_16_serial.a requires the symbol and is linked second
libstokhos_tpetra_sd_mp_16_serial.a defines the symbol but is linked first

And the function that sets these up will take some study to understand.

**Comment by etphipp** [comment]
Yep, I think you're right.  I am doing a static build right now to reproduce it, then I will just need to monkey with the cmake ETI logic to get the order right.

**Comment by etphipp** [comment]
PR #5121 should fix this.

**Comment by prwolfe** [comment]
> PR #5121 should fix this.

That fixed the Stokhos issues - I still see the ones from @trilinos/muelu. Would you prefer a second issue so you don't have to see all the traffic?

Thanks @etphipp!

**Comment by jhux2** [comment]
@prwolfe Please have a look at issue #5098 to see if you're having the same problem.

**Comment by prwolfe** [comment]
@jhux2 - I re-ordered the compile line and was able to solve this, but the CMakeLists.txt file has the dependencies explicitly set.

> #
> # Define the targets for package's library(s)
> #
> 
> TRIBITS_ADD_LIBRARY(
>   muelu_lgn
>   HEADERS ${HEADERS}
>   SOURCES ${SOURCES_LGN}
>   )
> 
> TRIBITS_ADD_LIBRARY(
>   muelu
>   HEADERS ${HEADERS}
>   SOURCES ${SOURCES}
>   DEPLIBS muelu_lgn
>   )
> 

So the question is what do I break in other links if I reverse these?

**Comment by jhux2** [comment]
> So the question is what do I break in other links if I reverse these?

Probably quite a bit.  I'm curious what's breaking, as I haven't seen any issues when I build MiniEM in Panzer using static linking.   If we need to repeat libraries, cmake has an [option](https://cmake.org/cmake/help/latest/command/target_link_libraries.html#id8) for that.

**Comment by prwolfe** [comment]
Ouch - I would rather spend the time to do a good library hierarchy redesign. This solution lacks elegance...

I am going to try reversing them first.

**Comment by mhoemmen** [comment]
This looks like a duplicate of https://github.com/trilinos/Trilinos/issues/4951 .  I think I will just get rid of ETI for normImpl.

**Comment by prwolfe** [comment]
@mhoemmen - that could work. I did confirm that reversing the dependency failed as @jhux2 predicted and that the "inelegant" solution is workable. Your idea is much better if it can be done without slowing compilation and linking too much.

**Comment by etphipp** [comment]
PR #5121 is merged in, so the stokhos part of this is fixed.

**Comment by prwolfe** [comment]
I merged #5131 this morning and am testing this now in PR #5111 - Thanks everyone!

**Comment by prwolfe** [comment]
Looks like we still have a circular dependency in mule and mule_ign. I dug a bit and am going to just set the circular dependency as this covers a lot in the constructors.

**Comment by prwolfe** [comment]
My testing shows that adding the circular dependencies to the CMakeLists.txt file works in Tribits, but will fail in Sierra builds.  The error I am currently seeing is

`[ 94%] Linking CXX executable Stokhos_TpetraCrsMatrixMPVectorUnitTest_Serial.exe
../../../muelu/src/libmuelu_lgn.a(MueLu_IsorropiaInterface.cpp.o): In function `MueLu::IsorropiaInterface<int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::Build(MueLu::Level&) const':
/scratch/prwolfe/trilinos/Trilinos/packages/muelu/src/Rebalancing/MueLu_IsorropiaInterface_def.hpp:145: undefined reference to `MueLu::AmalgamationFactory<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::DOFGid2NodeId(int, int, int, int)'
/scratch/prwolfe/trilinos/Trilinos/packages/muelu/src/Rebalancing/MueLu_IsorropiaInterface_def.hpp:158: undefined reference to `MueLu::AmalgamationFactory<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::DOFGid2NodeId(int, int, int, int)'
../../../muelu/src/libmuelu_lgn.a(MueLu_IsorropiaInterface.cpp.o): In function `MueLu::IsorropiaInterface<int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::Build(MueLu::Level&) const':
/scratch/prwolfe/trilinos/Trilinos/packages/muelu/src/Rebalancing/MueLu_IsorropiaInterface_def.hpp:145: undefined reference to `MueLu::AmalgamationFactory<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::DOFGid2NodeId(long long, int, long long, long long)'
/scratch/prwolfe/trilinos/Trilinos/packages/muelu/src/Rebalancing/MueLu_IsorropiaInterface_def.hpp:158: undefined reference to `MueLu::AmalgamationFactory<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::DOFGid2NodeId(long long, int, long long, long long)'
../../../muelu/src/libmuelu_lgn.a(MueLu_IsorropiaInterface.cpp.o): In function `MueLu::IsorropiaInterface<int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP, Kokkos::HostSpace> >::Build(MueLu::Level&) const':
/scratch/prwolfe/trilinos/Trilinos/packages/muelu/src/Rebalancing/MueLu_IsorropiaInterface_def.hpp:145: undefined reference to `MueLu::AmalgamationFactory<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP, Kokkos::HostSpace> >::DOFGid2NodeId(int, int, int, int)'
/scratch/prwolfe/trilinos/Trilinos/packages/muelu/src/Rebalancing/MueLu_IsorropiaInterface_def.hpp:158: undefined reference to `MueLu::AmalgamationFactory<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP, Kokkos::HostSpace> >::DOFGid2NodeId(int, int, int, int)'
../../../muelu/src/libmuelu_lgn.a(MueLu_IsorropiaInterface.cpp.o): In function `MueLu::IsorropiaInterface<int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP, Kokkos::HostSpace> >::Build(MueLu::Level&) const':
/scratch/prwolfe/trilinos/Trilinos/packages/muelu/src/Rebalancing/MueLu_IsorropiaInterface_def.hpp:145: undefined reference to `MueLu::AmalgamationFactory<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP, Kokkos::HostSpace> >::DOFGid2NodeId(long long, int, long long, long long)'
/scratch/prwolfe/trilinos/Trilinos/packages/muelu/src/Rebalancing/MueLu_IsorropiaInterface_def.hpp:158: undefined reference to `MueLu::AmalgamationFactory<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP, Kokkos::HostSpace> >::DOFGid2NodeId(long long, int, long long, long long)'
collect2: error: ld returned 1 exit status
make[2]: *** [packages/stokhos/test/UnitTest/Stokhos_TpetraCrsMatrixMPVectorUnitTest_Serial.exe] Error 1`

and a repeat in linking Stokhos_TpetraCrsMatrixMPVectorUnitTest_OpenMP.exe

Which is different that I first thought as it looks like it should be a simple matter of moving the ETI type into the _lgn library. I will test this and send a PR.

**Comment by kddevin** [comment]
This is probably outside the scope of this discussion, but I'll ask anyway.
Does MueLu still  need / use an Isorropia interface?  Does MueLu use things in Isorropia that aren't in Zoltan2?

**Comment by mhoemmen** [comment]
@prwolfe I took the liberty of reformatting your comment, by using triple back quotes to protect the error message.

**Comment by prwolfe** [comment]
I spent enough time yesterday trying to move this class from libmuelu to libmuelu_lgn to believe it is not feasible. Basically it touches enough other stuff that I'm not comfortable re-structuring someone else's code that far.  I think this needs to go back to the muelu team to work.

**Comment by jhux2** [comment]
@prwolfe Can I use the steps in your comment [above](https://github.com/trilinos/Trilinos/issues/5120#issue-441226200) to reproduce the static link issue?

**Comment by prwolfe** [comment]
Yes - if you rebase the branch onto develop you will get the previous 2 fixes. Alternately you can just start with develop and use "-DBUILD_SHARED_LIBS=OFF" in your config to get that change.

Thanks!

**Comment by jhux2** [comment]
@prwolfe I was able to reproduce the link problem locally, thanks for the instructions.  PR #5205 should fix the circular dependence.

**Comment by prwolfe** [comment]
@jhux2 - worked nicely on my blade, I have another issue with the original PR, but this issue can be closed.

Thanks everyone!
