### ISSUE TITLE
Tpetra: add nightly test that disables deprecated code

### ISSUE THREAD

**Issue by jhux2** [trilinos/Trilinos#5129]
@trilinos/tpetra

**Comment by kddevin** [comment]
Done by @jhux2 
E.g.,
https://testing.sandia.gov/cdash/index.php?project=Trilinos&subproject=Tpetra&filtercount=2&showfilters=1&filtercombine=and&field1=site&compare1=63&value1=rocketman&field2=buildname&compare2=63&value2=DEPRECATED
