### ISSUE TITLE
Ifpack2 non-backward compatible change broke SPARC

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#5132]
CC: @trilinos/ifpack2, @srajama1 (Trilinos Linear Solvers Product Area Lead), @kyungjoo-kim, @fryeguy52, @micahahoward, @mhoemmen 

## Next Action Status

Merged https://cee-gitlab.sandia.gov/sparc/sparc-ear99/merge_requests/178 on 5/7/2019 that should address the build errors.  Next: Watch for no build errors caused by this on SPARC CDash site and then close this issue ...

## Description

While not technically a bug, the non-backward compatible change to Ifpack2 in commit a88e5ce841909c2c8097b913efa698785b107a8f merged in PR #5032 broke the SPARC Trilinos Integration build (see [SPAR-567](https://sems-atlassian-srn.sandia.gov/browse/SPAR-567)).

The problem is that the functions `Ifpack2::BlockTriDiContainer::getNorms0()` and Ifpack2::BlockTriDiContainer::getNormsFinal()`.  These used to return array (`Teuchos::ArrayRCP<double>`) but now return scalars.  Fixing SPARC to build again is easy but what is not clear is how to translate from the array to the scalar in the customer numerical algorithms in SPARC.

## Current Status on CDash

* [SPARC Trilinos Integration Builds last 5 days](http://compsim-dashboard.sandia.gov/cdash/index.php?project=SPARC&filtercombine=and&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=66&value1=-trildev&field2=buildstarttime&compare2=83&value2=5%20days%20ago).

## Steps to Reproduce

Must have access to SPARC repos and instructions to reproduce for those with access are [here](https://snl-wiki.sandia.gov/display/CoodinatedDevOpsATDM/Building+ATDM+APPs+Against+Local+Installs+of+Trilinos#BuildingATDMAPPsAgainstLocalInstallsofTrilinos-BuildingagainstTrilinos'develop'usingtheATDMTrilinosconfiguration).

**Comment by bartlettroscoe** [comment]
@kyungjoo-kim, since this was your commit, can you please consult with someone on the SPARC team (or me) on how to adjust client code for this change?  In the SPARC code, it was taking the array, computing the max, of the elements and then dividing by the sqrt() of the number of rows in the matrix. 

From the patch in commit a88e5ce841909c2c8097b913efa698785b107a8f it looks like these arrays always had 0 or 1 elements so it seemed logical that it would be a simple substitution but that did not work and 6 new SPARC tests are failing.  Not sure if this or some other changes are causing the failures because the SPARC Trilinos Integration builds have been broken for several days (due to #5098).

FYI: (For those with access) the SPARC MR that gets SPARC to build again is:

* https://cee-gitlab.sandia.gov/sparc/sparc-ear99/merge_requests/178

**Comment by kyungjoo-kim** [comment]
A while ago, I talked to @micahahoward that Ifpack2 solver will change the norm interface but we do not discuss about specific way to change Ifpack2 and SPARC. The change is finally included in Ifpack2 by my last Pr. 

Briefly explaining the reason to change the interface
- Previous (1 year ago), we compute individual norm per residual vector. However, the solver use a stopping criteria collecting all vectors (Frobenius norm). Thus, returning a norm per vector is not practical. 
- As @bartlettroscoe indicates, I already put the change by returning a single array element. I think that the Ifpack2 getNorm interface is not examined individually per vector (so far no complains from SPARC).
- The reason that I compute norms for multivectors is because I compute (fuse) partial norm in the previous solver step to reduce reduction overhead. The operation uses a single thread local variable to accumulate norms. As the solver does not compute norm per column vector, the array interface is not right. 

I think that the fix on SPARC should be easy. @jjwilke Would you fix this problem on SPARC ?

**Comment by bartlettroscoe** [comment]
@kyungjoo-kim, the obvious change results in 6 failing SPARC tests.   Basically I replaced:

```
      return get_max_of_norms(btdc_->getNorms0()) / std::sqrt(num_all_rows_);
```

with:

```
      return btdc_->getNorms0() / std::sqrt(num_all_rows_);
```

and 

```
     return get_max_of_norms(btdc_->getNormsFinal()) / std::sqrt(num_all_rows_);
```

with:

```
       return btdc_->getNormsFinal() / std::sqrt(num_all_rows_);
```

where `btdc_` is a smart pointer to an `Ifpack2::BlockTriDiContainer` object.

I am wondering if the new failing SPARC tests (after making this change) are do to other changes pull in and not just this one simple change?

If anyone is going to fix this, please use:

* https://cee-gitlab.sandia.gov/sparc/sparc-ear99/merge_requests/178

in case that does not get merged before you start.

**Comment by mhoemmen** [comment]
@kyungjoo-kim @micahahoward I need to do some other stuff today, but I can take this if you're too busy.

**Comment by bartlettroscoe** [comment]
@mhoemmen said:

> I need to do some other stuff today, but I can take this if you're too busy.

As soon as I can verify that the merged MR:

* https://cee-gitlab.sandia.gov/sparc/sparc-ear99/merge_requests/178

has resolved the build errors in the SPARC Trilinos Integration testing builds, we can address the new failing tests in a separate issue (first as a SPARC JIRA issue since these are failing SPARC tests). 

Now that I have done the work to address the immediate build errors, this does not need to be a fire-drill for anyone else at this point.  (If that changes, I will let you know).

Thanks!

**Comment by bartlettroscoe** [comment]
I fixed SPARC for this non-backward compatible change and it seems that the failing SPARC tests are due to a SEACAS change, not this (see [SPAR-569](https://sems-atlassian-srn.sandia.gov/browse/SPAR-569) and #5191).  Therefore, we can close this issue and I will remove the "bug" label since this was not really a bug but a planned break in backward compatibility.

**Comment by mhoemmen** [comment]
Thanks @bartlettroscoe ! :D
