### ISSUE TITLE
MueLu: regionMG residual is 2x as large as expected at region interfaces

### ISSUE THREAD

**Issue by mayrmt** [trilinos/Trilinos#5135]
## Bug Report
@trilinos/muelu 

### Description
Here's a brief summary provided by @rstumin: 
"In particular, I am doing a 2 region example on a 13 x 13 mesh .... so there is just one interface. Along this interface the composite residual is  2x of what I expect it to be. Specifically, I initialize x to be 0 ... so I am expecting the composite residual to be r = b - A x = b. I've attached rhs.mm and compres.mm. You can do a diff -w to see the differences. Basically, we take the original composite b and convert it to regB. We do the same for composite x ... converting it to regX. The problem is that in the case of regX we want to replicate the values on the interface. However, I think for regB we want to scale things by the number of regions sharing an interface. Instead we replicate B along the interface. This means that when we compute a regional residual and then sum along the interface to get back to a composite residual ... we get 2x along the interface."

### Steps to Reproduce

Run the `MueLu_StructuredRegionDriver.exe` and look at the composite residual. In particular, compare 
- the composite residual computed with composite vectors/matrices only
- the composite residual computed via the region framework and then transforming it back to the composite layout.

They are expected to be identical, though they are not.

### Possible solution

Introduce a scaling option into `compositeToRegional()`, such that one *can* scale interface values by 1/N with N being the number of adjacent regions.

**Comment by lucbv** [comment]
@mayrmt let us see if @rstumin latest batch of tests using the Matlab code returns without error, if so I propose that we close this issue as it would seem that code is know working properly.

**Comment by mayrmt** [comment]
@lucbv I agree.

**Comment by lucbv** [comment]
@mayrmt I think it's time to close, feel free to reopen if needed!
