### ISSUE TITLE
Albany build issue on Ride due to undefined references in MueLu

### ISSUE THREAD

**Issue by ikalash** [trilinos/Trilinos#5156]
We're encountering a build error on Ride when building Albany in our nightlies against Trilinos.  It looks like there are undefined references due to MueLu: 
```
[100%] Linking CXX executable AlbanyT
/.../build/TrilinosInstall/lib/libml.a(ml_RowMatrix.cpp.o): In function `.LTHUNK30':

tmpxft_0001c7a8_00000000-5_ml_RowMatrix.cudafe1.cpp:(.text+0xfd4): undefined reference to `dcopy_'

/.../build/TrilinosInstall/lib/libml.a(ml_agg_min_energy.cpp.o): In function `ML_Satisfy_Constraints':
```
http://cdash.sandia.gov/CDash-2-3-0/viewBuildError.php?buildid=84588

Curiously enough, it doesn't happen on waterman. 

@trilinos/muelu

**Comment by nmhamster** [comment]
@ikalash - Ride has potential issues on the system. We are investigating.

**Comment by mhoemmen** [comment]
@ikalash also the Ride issue is blocking PR testing so we are highly motivated :)

**Comment by nmhamster** [comment]
@mhoemmen - understood. We are working on it .. promise.

**Comment by mhoemmen** [comment]
@nmhamster I know you care & are working hard so don't worry :D

**Comment by csiefer2** [comment]
#5147

**Comment by csiefer2** [comment]
This work on the nightlies?

**Comment by ikalash** [comment]
@csiefer2 : unfortunately we're still getting undefined reference errors on Ride (http://cdash.sandia.gov/CDash-2-3-0/viewBuildError.php?buildid=84721) .

**Comment by csiefer2** [comment]
That looks like a BLAS problem to me.  @nmhamster Any ideas?

**Comment by ikalash** [comment]
Any updates on getting this resolved?  We're still experiencing the problem.

**Comment by ikalash** [comment]
It looks like this was actually an ML issue, not MueLu, so I turned off ML to see what would happen.  I get blas/lapack-related issues: http://cdash.sandia.gov/CDash-2-3-0/viewBuildError.php?buildid=85246 .  Has anyone seen this?  Perhaps the lapack/blas I'm using is not valid anymore?

**Comment by ikalash** [comment]
Tagging @jewatkins

**Comment by mhoemmen** [comment]
@ikalash It could be that Epetra is assuming a BLAS mangling that doesn't correspond with your BLAS library.  You could test this by looking for the `ddot_` symbol in your BLAS library.

**Comment by cgcgcg** [comment]
Is this still an issue, or can we close this?

**Comment by ikalash** [comment]
No, not an issue any more.  Sorry, I forgot to close earlier.

**Comment by cgcgcg** [comment]
Great, thank you, @ikalash
