### ISSUE TITLE
Tpetra: Allow CrsMatrix import/export to change its graph's structure

### ISSUE THREAD

**Issue by tjfulle** [trilinos/Trilinos#5164]
## Enhancement
@trilinos/tpetra 

PR #4147 allows import/export operations to  change the structure of a `CrsGraph`.  Importantly, the user cannot change the structure directly, the structure changes happen in internal `CrsGraph` methods.

@kddevin and @mhoemmen should `CrsMatrix` provide the same functionality?

The answer to whether or not `CrsMatrix` does provide the functionality will have implications on many tests that fail with deprecated code OFF.

**Comment by mhoemmen** [comment]
@tjfulle asked:
> @kddevin and @mhoemmen should `CrsMatrix` provide the same functionality?

Yes, but only if the target CrsMatrix owns its graph.  If the target CrsMatrix was created with a const graph (the `RCP<const crs_graph_type>` constructor), then it does not have permission to change the graph.

**Comment by mhoemmen** [comment]
We pretty much need this in order to deprecate and remove `DynamicProfile` safely, so I'm removing the "enhancement" flag.

**Comment by mhoemmen** [comment]
@tjfulle https://github.com/trilinos/Trilinos/pull/5268 merged 3 days ago.  Did it get into master?  If so, can we consider this issue fixed?

**Comment by tjfulle** [comment]
I think so, I must not have put the right magic in the commit logs for it to close automagically

**Comment by mhoemmen** [comment]
Thanks @tjfulle ! :D
