### ISSUE TITLE
AztecOO Warnings for use of abs() when using float. Need fabs() calls.

### ISSUE THREAD

**Issue by nmhamster** [trilinos/Trilinos#5186]
## Bug Report
@trilinos/aztecoo 

Compiler warnings using Arm 19.1 compiler (which is based on LLVM 7.0/8.0).

### Description
```
/ascldap/users/sdhammo/git/sparc-trilinos-snl-gitlab-repo/packages/aztecoo/src/az_gmres_condnum.c:835:54: warning: using integer absolute value function 'abs' when argument is
      of floating point type [-Wabsolute-value]
    if( abs(Er[i])>largest_inv_A2 ) largest_inv_A2 = abs(Er[i]);
                                                     ^
/ascldap/users/sdhammo/git/sparc-trilinos-snl-gitlab-repo/packages/aztecoo/src/az_gmres_condnum.c:835:54: note: use function 'fabs' instead
    if( abs(Er[i])>largest_inv_A2 ) largest_inv_A2 = abs(Er[i]);
```

Just providing this as a potential area where warnings as errors will be an issue for compiling on larger machines moving forward.

**Comment by mhoemmen** [comment]
Interesting; this does not show up in the currently outstanding PR to clean up AztecOO for a warnings-as-errors build: https://github.com/trilinos/Trilinos/pull/5159/files .  Nevertheless, this looks scary (conversion of `double` to `int` and back again?!?) and we should fix it.

**Comment by mhoemmen** [comment]
begone autobot
