### ISSUE TITLE
Framework: Intel PR Testing Environment Potentially Broken

### ISSUE THREAD

**Issue by dridzal** [trilinos/Trilinos#5193]
## Bug Report
@trilinos/framework 

### Description
The Intel PR testing environment is potentially broken.  This may affect three ROL PR tests for which we can't find the cause of failures.  In order for us to proceed, this bug should either be fixed or it should be verified as a non-issue. 

```
[dridzal@optimizer pr-latest $ module purge
[dridzal@optimizer pr-latest $ source ../../../Trilinos/cmake/std/sems/PullRequestIntel17.0.1TestingEnv.sh
	WARNING: sems-gcc dependency already found but does not match listed dependency sems-gcc/4.8.4
	I will use the sems-gcc you have loaded but correct behavior is not guaranteed
```

### Steps to Reproduce
See above.  The system is RHEL6.

**Comment by dridzal** [comment]
I've also noticed that running

`source ../../../Trilinos/cmake/std/sems/PullRequestIntel17.0.1TestingEnv.sh`

without `module purge` prior to it results in errors (i.e., not simply warnings).  It seems like these scripts should be fail-safe if executed in our standard computing environments.

**Comment by dridzal** [comment]
@bartlettroscoe , do you know who would be handling this type of issue?  Something is clearly wrong here, and before we waste days on trying to find bugs, we need to be certain that the environment is clean.  Our Intel errors only appear with this specific PR testing environment script; if I load the Intel compiler manually, I don't get the above warning, and I also don't get the test timeouts, i.e., all ROL tests pass.

**Comment by bartlettroscoe** [comment]
@dridzal, the script `rilinos/cmake/std/sems/PullRequestIntel17.0.1TestingEnv.sh` is owned by the @trilinos/framework team.  They have to resolve any issues with it as I am not a member of the Trilinos Framework team.

**Comment by dridzal** [comment]
@bartlettroscoe , thanks.  @trilinos/framework , please chime in.  We haven't been able to merge ROL with Trilinos in a long time (5 months!) due to Intel test timeouts, and we would like to verify that the PR environment is not causing the issues.

**Comment by prwolfe** [comment]
@dridzal - I have loaded this script multiple times without seeing the error you are reporting.  In fact, gcc 4.8.4 is not in use in the script at all.  I did get a complaint about the atdm version of cmake not being available and we will get that moved to the semi version now that it is available.

This tells me that you have something going on with your environment that should not be present. Can you check that your .bashrc file does not load anything and then start from a clean shell please? I expect that will help resolve this.

Paul

**Comment by dridzal** [comment]
@prwolfe , thanks for looking into this.  I don't think that an empty .bashrc can be the solution.  The PR script needs to provide a clean environment.  Otherwise, the instructions on how to recreate the PR environment are wrong --I don't see anything about "make sure that your .bashrc does not load anything".  Also, it's unrealistic to expect Trilinos developers not to use .bashrc for anything.  In any case, I've now removed my .bashrc, and I get:

```
[dridzal@optimizer]$ module purge
[dridzal@optimizer]$ module list
No Modulefiles Currently Loaded.
[dridzal@optimizer]$ source ~/development/ROL-Trilinos/cmake/std/sems/PullRequestIntel17.0.1TestingEnv.sh
	WARNING: sems-gcc dependency already found but does not match listed dependency sems-gcc/4.8.4
	I will use the sems-gcc you have loaded but correct behavior is not guaranteed
```

Also, if I run the script several times in a row, I get;

```
[dridzal@optimizer]$ source ~/development/ROL-Trilinos/cmake/std/sems/PullRequestIntel17.0.1TestingEnv.sh
sems-gcc/4.9.3(3):ERROR:150: Module 'sems-gcc/4.9.3' conflicts with the currently loaded module(s) 'sems-intel/17.0.1'
sems-gcc/4.9.3(3):ERROR:102: Tcl command execution failed: conflict sems-gcc sems-intel sems-pgi sems-clang

	WARNING: sems-gcc dependency already found but does not match listed dependency sems-gcc/4.8.4
	I will use the sems-gcc you have loaded but correct behavior is not guaranteed
```

I see that some modules are loaded in my environment _prior_ to running `module purge` but that seems to be coming from somewhere else (not .bashrc, as it no longer exists) --maybe some SEMS script that is run automatically at a different stage of the loading process?

I recall a potentially related SEMS issue that @fryeguy52 helped resolve a while ago.  Maybe he can provide some feedback.

**Comment by prwolfe** [comment]
Modules frequently fail if prior modules are still loaded for whatever reason (the .bashrc is just the most common one.) The error you are seeing on repeated execution is in fact expected if you had not unloaded all of the modules beforehand.

**Comment by dridzal** [comment]
So why doesn't the script clear the environment first (module purge, etc., whatever is needed)?  I think that anyone going through the trouble of recreating the PR environment would prefer to start clean.

**Comment by prwolfe** [comment]
One of the problems with the tcl modules system is that there is no reliable way of resetting a user environment to it's clean state. (module purge for instance does a great job of convincing the module system that everything is unloaded and not as good a job of cleaning the environment - at least in part due to ordering issues.)

There are many others, but this space is a bit small to list them all. The Lua version is slightly improved. So we could make the attempt, but it would mostly be window dressing.

**Comment by dridzal** [comment]
I understand.  Since there seems to be no way for us to recreate a clean environment locally that matches the PR testing environment, can we get access to the test machine to debug our PR testing issues?  We have to move forward somehow.

**Comment by dridzal** [comment]
As another point of reference, here is some output in a completely clean environment:

```
[dridzal@optimizer]$ env -i bash --noprofile --norc
bash-4.1$ env
PWD=/home/dridzal/Desktop
SHLVL=1
_=/bin/env
bash-4.1$ source mod.sh 
bash-4.1$ source ../development/ROL-Trilinos/cmake/std/sems/PullRequestIntel17.0.1TestingEnv.sh
	WARNING: sems-gcc dependency already found but does not match listed dependency sems-gcc/4.8.4
	I will use the sems-gcc you have loaded but correct behavior is not guaranteed
sems-intel/17.0.1(140):ERROR:102: Tcl command execution failed: set uname [exec uname]

atdm-env(12):ERROR:102: Tcl command execution failed: set platform [exec $sems_root/utils/get-platform]

ModuleCmd_Load.c(213):ERROR:105: Unable to locate a modulefile for 'atdm-cmake/3.11.1'
ModuleCmd_Load.c(213):ERROR:105: Unable to locate a modulefile for 'atdm-ninja_fortran/1.7.2'
```
Note that I have to source the mod.sh file to tell bash what module means (it's a simple shell function).  This is because there is really nothing in the environment.  Anyway, I'm not sure that the PR scripts are working as they should.  Are you on RHEL6 or RHEL7?  This is all RHEL6.

**Comment by prwolfe** [comment]
I have been working on RHEL7 - I went to the normal build machine which is RHEL6 and did see the gcc 4.8.4 warning - again something that should be fed back to sems.  I am doing a build on my machine now to see what I can figure out.

As for machine access, these are very direct snapshots of the corporate RHEL image just like the CEE blades. That is very deliberate and all our added software is from the sems NFS servers so that should match well.  If you do not have a blade you should be able to get the same results from a stand-alone machine with the default image and the sems mounts or using any of the cee-build or cee-compute machines.

**Comment by prwolfe** [comment]
@dridzal - I checked out the code from #5149 and did a build on my news blade. I exactly replicated the timeout on the 3 failing tests using the intel 17.0.1 environment.

**Comment by dridzal** [comment]
@prwolfe thanks!  We'll start debugging the three failing tests.
