### ISSUE TITLE
Intel PR test jobs fail to start

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#5201]
## Bug Report
@trilinos/framework @trilinos/muelu 

### Description

Intel PR test jobs fail to start.  See the following MueLu PRs: #5196, #5199, #5200.  Typical report:
```
Status Flag 'Pull Request AutoTester' - Failure: Timed out waiting for job Trilinos_pullrequest_intel_17.0.1 to start: Total Wait = 603
```

**Comment by prwolfe** [comment]
It looks like all jobs were failing for most of the weekend. Not sure why these PR's recorded the intel job as failing before everything shut down. I'm not suer why the jobs weren't running either - I will dig

**Comment by prwolfe** [comment]
All three of the machines we use for intel jobs were down starting at 3:15pm Friday and continuing until 11 am Saturday. It looks like all the aspic machines were down and the gcc jobs that did try to start were on the smaller cloud nodes. Everything seems to be up at this point.

**Comment by mhoemmen** [comment]
Thanks @prwolfe !
