### ISSUE TITLE
Ifpack2:  Ifpack2_unit_tests_MPI_4 failing on ATDM waterman build

### ISSUE THREAD

**Issue by fryeguy52** [trilinos/Trilinos#5203]
## Bug Report
CC: @trilinos/ifpack2, @srajama1 (Trilinos Linear Solvers Product Lead), @bartlettroscoe, @fryeguy52
 
## Description
 
As shown in [this query](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercount=7&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-&field2=buildname&compare2=63&value2=opt&field3=buildname&compare3=64&value3=shared&field4=testname&compare4=61&value4=Ifpack2_unit_tests_MPI_4&field5=site&compare5=61&value5=waterman&field6=buildstarttime&compare6=84&value6=2019-06-12T00%3A00%3A00&field7=buildstarttime&compare7=83&value7=2019-05-01T00%3A00%3A00) the test:
* Ifpack2_unit_tests_MPI_4

is failing randomly in the builds:
* Trilinos-atdm-waterman-cuda-9.2-opt
* Trilinos-atdm-waterman_cuda-9.2_fpic_static_opt

<details>
  <summary>Expand to see new commits on 2019-05-15</summary>

```
*** Base Git Repo: Trilinos
7cb5217:  Merge remote-tracking branch 'origin/develop' into atdm-nightly
Author: Roscoe A. Bartlett <rabartl@sandia.gov>
Date:   Tue May 14 21:05:20 2019 -0600

c3f8e35:  Merge Pull Request #5170 from trilinos/Trilinos/csiefer-4dd8995
Author: trilinos-autotester <trilinos-autotester@trilinos.org>
Date:   Tue May 14 18:55:02 2019 -0600

c872f56:  Merge Pull Request #5144 from trilinos/Trilinos/csiefer-f3d9b2d
Author: trilinos-autotester <trilinos-autotester@trilinos.org>
Date:   Tue May 14 17:34:58 2019 -0600

6df3437:  Merge Pull Request #5140 from trilinos/Trilinos/csiefer-ad8ea7e
Author: trilinos-autotester <trilinos-autotester@trilinos.org>
Date:   Tue May 14 14:40:52 2019 -0600

7872b5d:  Merge Pull Request #5113 from ZUUL42/Trilinos/Werror_Pamgen
Author: trilinos-autotester <trilinos-autotester@trilinos.org>
Date:   Tue May 14 13:41:46 2019 -0600

6b3b548:  Merge Pull Request #5153 from ZUUL42/Trilinos/Werror_Triutils
Author: trilinos-autotester <trilinos-autotester@trilinos.org>
Date:   Tue May 14 13:27:10 2019 -0600

4dd8995:  Teuchos: Removing 'not' keyword so Visual Studio will compile the code
Author: Chris Siefert <csiefer@sandia.gov>
Date:   Tue May 14 08:29:59 2019 -0600

M	packages/teuchos/comm/test/StackedTimer/stacked_timer.cpp

b3a8dc8:  Merge pull request #5167 from kyungjoo-kim/ifpack2-develop
Author: kyungjoo-kim <kyukim@sandia.gov>
Date:   Mon May 13 21:28:33 2019 -0600

f99a925:  Merge remote-tracking branch 'upstream/develop' into ifpack2-develop
Author: Kyungjoo Kim <kyukim@sandia.gov>
Date:   Mon May 13 16:00:09 2019 -0600

d65032c:  Ifpack2 - add cmake option for controlloing tridiagonal matrix precision
Author: Kyungjoo Kim <kyukim@sandia.gov>
Date:   Mon May 13 15:59:32 2019 -0600

M	packages/ifpack2/CMakeLists.txt
M	packages/ifpack2/cmake/Ifpack2_config.h.in
M	packages/ifpack2/src/Ifpack2_BlockTriDiContainer_impl.hpp
M	packages/ifpack2/test/unit_tests/Ifpack2_UnitTestBlockTriDiContainerUtil.hpp

a753538:  Ifpack2 - modify test example to show error threshold.
Author: Kyungjoo Kim <kyukim@sandia.gov>
Date:   Mon May 13 11:12:16 2019 -0600

M	packages/ifpack2/test/unit_tests/Ifpack2_UnitTestBlockTriDiContainerUtil.hpp

8e85f35:  Ifpack2 - block tridiag - use float preconditioner for double tpetra input
Author: Kyungjoo Kim <kyukim@sandia.gov>
Date:   Fri May 10 12:45:33 2019 -0600

M	packages/ifpack2/src/Ifpack2_BlockTriDiContainer_impl.hpp

290e981:  Put all cnt in ifdef DEBUG for Werror
Author: Henry Swantner <HRSwant@sandia.gov>
Date:   Thu May 9 17:38:07 2019 -0600

M	packages/triutils/src/Trilinos_Util_ReadHpc2Epetra.cpp

8c4e442:  Issue 5104 Remove unused-variable lines to remove warnings
Author: Henry Swantner <HRSwant@sandia.gov>
Date:   Thu May 9 11:37:17 2019 -0600

M	packages/pamgen/mesh_spec_lt/pamgen_mesh_specification.C

f3d9b2d:  Belos: Using Xpetra [E|T]petra support macros to determine what to build w/ Xpetra instead of the Belos ones
Author: Chris Siefert <csiefer@sandia.gov>
Date:   Thu May 9 08:42:47 2019 -0600

M	packages/belos/xpetra/src/Belos_Details_Xpetra_registerSolverFactory.cpp

fae634a:  MueLu: Will not enable MueLu Epetra support unless Xpetra Epetra support is on
Author: Chris Siefert <csiefer@sandia.gov>
Date:   Wed May 8 16:13:55 2019 -0600

M	packages/muelu/CMakeLists.txt

6160079:  Xpetra: Fixing spelling
Author: Chris Siefert <csiefer@sandia.gov>
Date:   Wed May 8 15:58:24 2019 -0600

M	packages/xpetra/CMakeLists.txt

ad8ea7e:  Xpetra: Making implicit assumptions about configuration very clear
Author: Chris Siefert <csiefer@sandia.gov>
Date:   Wed May 8 11:48:04 2019 -0600

M	packages/xpetra/CMakeLists.txt

185274f:  Reverse NULL checks
Author: Henry Swantner <HRSwant@sandia.gov>
Date:   Tue May 7 16:03:36 2019 -0600

M	packages/triutils/src/Trilinos_Util_iohb.cpp

fc01961:  Issue 3178 Set Werror for Triutils in GCC 7.2.0 build
Author: Henry Swantner <HRSwant@sandia.gov>
Date:   Tue May 7 16:03:20 2019 -0600

M	cmake/std/PullRequestLinuxGCC7.2.0TestingSettings.cmake

fbdc418:  Issue 3178 Set Werror for Pamgen in GCC 7.2.0 build
Author: Henry Swantner <HRSwant@sandia.gov>
Date:   Mon May 6 11:23:02 2019 -0600

M	cmake/std/PullRequestLinuxGCC7.2.0TestingSettings.cmake
```
</details>

## Current Status on CDash

The current 2 week history this test can be found [here](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercount=7&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-&field2=buildname&compare2=63&value2=opt&field3=buildname&compare3=64&value3=shared&field4=testname&compare4=61&value4=Ifpack2_unit_tests_MPI_4&field5=site&compare5=61&value5=waterman&field6=buildstarttime&compare6=84&value6=tomorrow&field7=buildstarttime&compare7=83&value7=2%20week%20ago)

## Steps to Reproduce

One should be able to reproduce this failure on waterman as described in:
* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md

More specifically, the commands given for waterman are provided at:
* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#waterman

The exact commands to reproduce this issue should be:
```
$ cd <some_build_dir>/
$ source $TRILINOS_DIR/cmake/std/atdm/load-env.sh Trilinos-atdm-waterman-cuda-9.2-opt
$ cmake \
 -GNinja \
 -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
 -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_Ifpack2=ON \
 $TRILINOS_DIR
$ make NP=16
$ bsub -x -Is -n 20 ctest -j20
```

**Comment by srajama1** [comment]
@kyungjoo-kim : Lot of commits with your name on the commit list :)

@trilinos/ifpack2

**Comment by kyungjoo-kim** [comment]
I don't think that this is because of my commits. The failure happens here. If no one touched ifpack2 overlapping row matrix things, this might be a side effect from tpetra update. 
```
p=0 |  Location: /home/jenkins/waterman/workspace/Trilinos-atdm-waterman-cuda-9.2-opt/SRC_AND_BUILD/Trilinos/packages/ifpack2/test/unit_tests/Ifpack2_UnitTestOverlappingRowMatrix.cpp:112
```

**Comment by mhoemmen** [comment]
It looks like `Ifpack2::OverlappingRowMatrix` is broken in this build.  This most definitely has nothing to do with @kyungjoo-kim 's work.  @jhux2 or @csiefer2 might know if anything has changed there.

**Comment by jhux2** [comment]
> It looks like `Ifpack2::OverlappingRowMatrix` is broken in this build. This most definitely has nothing to do with @kyungjoo-kim 's work. @jhux2 or @csiefer2 might know if anything has changed there.

Not that I'm aware of.

**Comment by fryeguy52** [comment]
It turns out this failure has been randomly occurring on many different builds it failed on `Trilinos-atdm-waterman-cuda-9.2-opt` a few days in a row so I thought it was just that one build.  As shown [here](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-&field2=testname&compare2=61&value2=Ifpack2_unit_tests_MPI_4&field3=status&compare3=61&value3=Failed&field4=buildstarttime&compare4=84&value4=2019-06-03T04%3A01%3A00UTC&field5=buildstarttime&compare5=83&value5=2019-05-01T04%3A01%3A00UTC) it has failed at least once on 9 different builds.  
* Trilinos-atdm-mutrino-intel-opt-openmp-HSW-exp
* Trilinos-atdm-waterman_cuda-9.2_fpic_static_opt
* Trilinos-atdm-waterman-cuda-9.2-opt
* Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-debug
* Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-rdc-release-debug
* Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-rdc-release-debug-pt
* Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-release
* Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-release-debug
* Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-release-debug-pt


It looks like this started around 5/8/2019 but since it is not failing every day I can't say for sure.

<details>
  <summary>Expand to see new commits on 2019-05-08</summary>

```
*** Base Git Repo: Trilinos
39aabb7:  Merge remote-tracking branch 'origin/develop' into atdm-nightly
Author: Roscoe A. Bartlett <rabartl@sandia.gov>
Date:   Tue May 7 21:05:19 2019 -0600

dcc6bcb:  Teuchos::ParameterList: Fix #5127 (#5128)
Author: Mark Hoemmen <mhoemmen@users.noreply.github.com>
Date:   Tue May 7 19:25:22 2019 -0600

M	packages/teuchos/parameterlist/src/Teuchos_ParameterList.hpp

3e8bf2e:  Merge Pull Request #5125 from fryeguy52/Trilinos/swap-gcc-version-157
Author: trilinos-autotester <trilinos-autotester@trilinos.org>
Date:   Tue May 7 14:36:09 2019 -0600

6981633:  Merge Pull Request #5122 from mayrmt/Trilinos/region-mg-coarse-solver
Author: trilinos-autotester <trilinos-autotester@trilinos.org>
Date:   Tue May 7 12:51:09 2019 -0600

92b2abb:  Merge Pull Request #5121 from etphipp/Trilinos/stokhos_tpetra_link_order_fix
Author: trilinos-autotester <trilinos-autotester@trilinos.org>
Date:   Tue May 7 11:05:54 2019 -0600

74af28c:  MueLu:print msg if coarseSolver not setup properly
Author: Matthias Mayr <matthias.mayr@unibw.de>
Date:   Tue May 7 17:52:20 2019 +0200

M	packages/muelu/research/mmayr/composite_to_regions/src/SetupRegionHierarchy_def.hpp

043bde2:  swap gcc module in sems-rhel6 intel-17 builds
Author: Joe Frye <jfrye@sandia.gov>
Date:   Tue May 7 09:16:07 2019 -0600

M	cmake/std/atdm/sems-rhel6/environment.sh

0f8f01e:  Stokhos:  Fix tpetra link order.
Author: Eric Phipps <etphipp@sandia.gov>
Date:   Tue May 7 08:49:53 2019 -0600

M	packages/stokhos/src/CMakeLists.txt

0f180e4:  Merge Pull Request #5114 from lucbv/Trilinos/MueLu_fix_LineDetection
Author: trilinos-autotester <trilinos-autotester@trilinos.org>
Date:   Mon May 6 22:20:12 2019 -0600

766cf31:  Merge Pull Request #5116 from bartlettroscoe/Trilinos/atdv-151-waterman-shared-static-fpic-builds
Author: trilinos-autotester <trilinos-autotester@trilinos.org>
Date:   Mon May 6 21:46:03 2019 -0600

ce47d15:  Merge Pull Request #5100 from trilinos/Trilinos/csiefer-48785b1
Author: trilinos-autotester <trilinos-autotester@trilinos.org>
Date:   Mon May 6 21:25:25 2019 -0600

45c80d8:  MueLu: Fixing shadow error
Author: Chris Siefert <csiefer@sandia.gov>
Date:   Mon May 6 16:03:26 2019 -0600

M	packages/muelu/src/Misc/MueLu_RAPShiftFactory_def.hpp

06d633e:  MueLu: fix type issues in LineDetetion factory, see issue #5112
Author: Luc Berger-Vergiat <lberge@sandia.gov>
Date:   Mon May 6 16:02:42 2019 -0600

M	packages/muelu/src/Misc/MueLu_LineDetectionFactory_decl.hpp
M	packages/muelu/src/Misc/MueLu_LineDetectionFactory_def.hpp

48785b1:  MueLu: Ray's fixies to RAPShiftFactory
Author: Chris Siefert <csiefer@sandia.gov>
Date:   Mon May 6 08:51:19 2019 -0600

M	packages/muelu/src/Misc/MueLu_RAPShiftFactory_def.hpp
```
</details>

**Comment by jhux2** [comment]
@fryeguy52 How urgent is this issue?

**Comment by bartlettroscoe** [comment]
@jhux2 asked:

> How urgent is this issue?

Does this indicate a defect that will (or is) negatively impacting an ATDM APP customer?  If yes, then this should be higher priority.  If not, then it should be lower priority.  So you tell us.

**Comment by jhux2** [comment]
As far as I know, this is not currently on SPARC's or EMPIRE's critical path.

**Comment by bartlettroscoe** [comment]
@jhux2 said:

> As far as I know, this is not currently on SPARC's or EMPIRE's critical path.

The test executable `Ifpack2_unit_tests_MPI_4` is running 82 individual tests in this build to protect basic Ifpack2 functionality.  Is neither SPARC nor EMPIRE using Ifpack2?  If not, then why are they enabling it?

Note that one unit tests is failing as shown [here](https://testing.sandia.gov/cdash/testDetails.php?test=80099151&build=5126574) showing:

```
p=2 | The following tests FAILED:
p=2 |     48. Ifpack2OverlappingRowMatrix_default_scalar_type_default_local_ordinal_type_default_global_ordinal_type_Test0_UnitTest ... 
p=0 | The following tests FAILED:
p=0 |     48. Ifpack2OverlappingRowMatrix_default_scalar_type_default_local_ordinal_type_default_global_ordinal_type_Test0_UnitTest ... 
p=3 | The following tests FAILED:
p=3 |     48. Ifpack2OverlappingRowMatrix_default_scalar_type_default_local_ordinal_type_default_global_ordinal_type_Test0_UnitTest ... 
p=1 | The following tests FAILED:
p=1 |     48. Ifpack2OverlappingRowMatrix_default_scalar_type_default_local_ordinal_type_default_global_ordinal_type_Test0_UnitTest ... 
```

Since this build is an optimized CUDA build on 'waterman' (the closest thing we have to the ATS-2 machine 'sierra' so far), are you not concerned that this one failing unit test that we know about will mask other individual unit tests that might start failing and we will never notice it because we are expecting this test to fail?  

If none of the ATDM APPs are using functionality protected by the one unit test `Ifpack2OverlappingRowMatrix_default_scalar_type_default_local_ordinal_type_default_global_ordinal_type_Test0_UnitTest ` should we not just disable that one unit test in this one build so that we don't miss other unit tests that might start failing?

**Comment by jhux2** [comment]
> As far as I know, this is not currently on SPARC's or EMPIRE's critical path.

@bartlettroscoe I should have been more specific.  As far as I know, the capabilities in `Ifpack2OverlappingRowMatrix` aren't needed by EMPIRE or SPARC.

**Comment by jhux2** [comment]
Is there cmake logic to check which machine the test is being run on?

**Comment by bartlettroscoe** [comment]
@jhux2 asked:

> Is there cmake logic to check which machine the test is being run on?

We would use a "tweak" file as outlined [here](https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#disable-a-test-for-a-specific-build-on-a-specific-platform).   I can put in the disable in a PR to demonstrate.

**Comment by mhoemmen** [comment]
@jhux2 Does EMPIRE use overlapping domain decomposition?

**Comment by fryeguy52** [comment]
This is also randomly failing on `Trilinos-atdm-waterman_cuda-9.2_fpic_static_opt` shown [here](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-waterman_cuda-9.2_fpic_static_opt&field2=testname&compare2=61&value2=Ifpack2_unit_tests_MPI_4&field3=site&compare3=61&value3=waterman&field4=buildstarttime&compare4=84&value4=2019-06-12T04%3A01%3A00UTC&field5=buildstarttime&compare5=83&value5=2019-05-13T04%3A01%3A00UTC) with the same unit test failing

```
p=1 | The following tests FAILED:
p=1 |     48. Ifpack2OverlappingRowMatrix_default_scalar_type_default_local_ordinal_type_default_global_ordinal_type_Test0_UnitTest ... 
p=1 | 
p=1 | Total Time: 6.32 sec
p=1 | 
p=1 | Summary: total = 82, run = 82, passed = 81, failed = 1
```

**Comment by brian-kelley** [comment]
I think this problem was fixed, [it hasn't failed since June 25](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-waterman&field2=testname&compare2=65&value2=Ifpack2_unit_tests_MPI_4&field3=buildstarttime&compare3=83&value3=2019-06-15). Also, I wasn't able to replicate it in 10 or so runs on waterman.

**Comment by bartlettroscoe** [comment]
@brian-kelley said:

> I think this problem was fixed, it hasn't failed since June 25.

Okay, I will buy that.  Closing as complete.

Thanks for looking into this!
