### ISSUE TITLE
Xpetra: Cloner unit test is failing on muir

### ISSUE THREAD

**Issue by tawiesn** [trilinos/Trilinos#521]
It says 

>  Node is responsible for finalizing ExecutionSpace, but its destructor did not.

http://my.cdash.org/testDetails.php?test=26469899&build=1011641

**Comment by tawiesn** [comment]
Obviously fixed

http://my.cdash.org/index.php?project=Trilinos&subproject=Xpetra

**Comment by mhoemmen** [comment]
Yay, thanks!
