### ISSUE TITLE
Trilinos framework:  generated TrilinosConfig.cmake does not work if no TPLs

### ISSUE THREAD

**Issue by kddevin** [trilinos/Trilinos#5213]
## Bug Report
@trilinos/framework  @bartlettroscoe 

### Description
The generated file TrilinosConfig.cmake in
BUILD/lib/cmake/Trilinos/TrilinosConfig.cmake
does not work correctly if the Trilinos build has no TPLs.

It produces the following error when included by an application:
```
CMake Error at /Users/kddevin/tmp/tmp/Trilinos/Obj_tpetra/lib/cmake/Trilinos/TrilinosConfig.cmake:175 (LIST):
  LIST sub-command REMOVE_DUPLICATES requires list to be present.
Call Stack (most recent call first):
  CMakeLists.txt:31 (FIND_PACKAGE)

```

TrilinosConfig.cmake tries to remove duplicates from Trilinos_TPL_INCLUDE_DIRS.  But since there are no TPLs, Trilinos_TPL_INCLUDE_DIRS was never set.  I think this file needs an initialization of Trilinos_TPL_INCLUDE_DIRS before the loop that appends any TPLs to it.

I am willing to add the initialization if someone points me to the correct place to add it.  I do not know where to find the file that is used in generating TrilinosConfig.cmake.

This behavior has changed since February 2019.  An application build that worked in February no longer works due to this issue.

### Steps to Reproduce
1. SHA1:  [9fa2e68ac1e4f147d16723b2a14d5a14ee40e27d]
1. Configure script:  [attach here]
```
cmake \
-D Trilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON \
-D CMAKE_BUILD_TYPE:STRING="DEBUG" \
-D CMAKE_VERBOSE_MAKEFILE:BOOL=OFF \
\
-D TPL_ENABLE_MPI:BOOL=ON \
-D MPI_EXEC_MAX_NUMPROCS:STRING=11 \
\
-D TPL_ENABLE_BinUtils:BOOL=OFF \
-D TPL_ENABLE_Pthread:BOOL=OFF \
\
-D Trilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=OFF \
-D Trilinos_ENABLE_TESTS:BOOL=OFF \
-D Trilinos_ENABLE_EXAMPLES:BOOL=OFF \
\
-D Trilinos_VERBOSE_CONFIGURE:BOOL=OFF \
-D Trilinos_ENABLE_Fortran:BOOL=OFF \
\
-D Trilinos_ENABLE_Tpetra:BOOL=ON \
-D Tpetra_INST_FLOAT:BOOL=ON \
-D Teuchos_ENABLE_FLOAT:BOOL=ON \
-D Trilinos_ENABLE_Zoltan2:BOOL=ON \
-D Zoltan2_ENABLE_TESTS:BOOL=OFF \
-D Zoltan2_ENABLE_EXAMPLES:BOOL=OFF \
\
-D Teuchos_ENABLE_STACKTRACE:BOOL=OFF \
-D Teuchos_ENABLE_LONG_LONG_INT:BOOL=ON \
.. 

make 
make install

```
Then application sets Trilinos_DIR to point to TrilinosConfig.cmake, and does FIND_PACKAGE(Trilinos)

**Comment by bartlettroscoe** [comment]
That looks like a TriBITS defect that will be easy to fix.  I will update TriBITS 'master' then post a PR.

**Comment by kddevin** [comment]
That would be great.  It is a blocker right now.  Thanks!

**Comment by bartlettroscoe** [comment]
@kddevin 

FYI: PR #5215 should fix this.  Can you approve this PR?

**Comment by kddevin** [comment]
Works for me now.  Thanks, @bartlettroscoe
