### ISSUE TITLE
Epetra: how to create Epetra_CrsMatrix from user matrix

### ISSUE THREAD

**Issue by srinadhupreetham** [trilinos/Trilinos#5227]
While solving Ax= b type problem using ml solver  can someone help me how to give that crs matrix of mine as input to ml_preconditioner.cpp 

  Epetra_Map* Map = CreateMap("Cartesian3D", Comm, GaleriList);
  Epetra_CrsMatrix* A = CreateCrsMatrix("Laplace3D", Map, GaleriList);

i mean A in this above part of code here it is using inbuilt laplacian 3D

**Comment by mhoemmen** [comment]
@trilinos/ml

**Comment by jhux2** [comment]
@srinadhupreetham I think you are asking how you can use ML with your own matrix -- is this your question?

If you want to use the class MultiLevelPreconditioner, then your matrix must either be an [Epetra_CrsMatrix](https://trilinos.org/docs/dev/packages/epetra/doc/html/classEpetra__CrsMatrix.html), or satisfy the requirements of an [Epetra_RowMatrix](https://trilinos.org/docs/dev/packages/epetra/doc/html/classEpetra__RowMatrix.html).

If you are already building a CRS matrix yourself, it's not much more work to create an Epetra_CrsMatrix instead.

**Comment by srinadhupreetham** [comment]
Can you please post the code to convert our crs matrix into Epetra_CrsMatrix.

**Comment by mayrmt** [comment]
You can find exemplary code for creating an `Epetra_CrsMatrix` in `packages/epetra/test/CrsMatrix/cxx_main.cpp` and possibly in some other tests and examples inside `packages/epetra/...`.

**Comment by mhoemmen** [comment]
I'm calling this closed.  Please reopen if not.
