### ISSUE TITLE
Framework? STK PR test failure can't be reproduced

### ISSUE THREAD

**Issue by alanw0** [trilinos/Trilinos#5230]
## Question
@trilinos/framework 

I have a PR #5212 attempting to update the stk package (this is needed by the SPARC folks for some milestone work).
It has failed a couple of times, due to a stk_transfer unit-test failing for the gcc 7.2.0 build, with a message about a pthread_mutex error in a gtest file.. I have reproduced the build using the recipe provided, on a couple of different machines (rhel6 and rhel7 in case that matters). In these reproduced builds, the stk-transfer unit-test runs successfully.

@bartlettroscoe or @mhoemmen any suggestions?
Mentioning @tcfisher since he's waiting on the update.

**Comment by bartlettroscoe** [comment]
@alanw0, strange error.  I would say to disable this test for this PR build but I think this might be the only OpenMP build in the PR test suite.  Hopefully the @trilinos/framework team has advice on how to reproduce this failure.
