### ISSUE TITLE
Xpetra: build error w/ mutrino KNL?

### ISSUE THREAD

**Issue by tcfisher** [trilinos/Trilinos#5233]
## Question
@trilinos/Tpetra

Hello,

I'm having difficulty getting a new Trilinos build on mutrino with intel 18, OpenMP on KNL, and static linking. Has anyone else observed this issue? Do the nightly tests show something different? We are using -qoverride-limits for KNL but don't typically use it for HSW.
 
```bash
icpc: error #10106: Fatal error in /projects/Mutrino/hpcsoft/cle6.0/common/intel-clusterstudio/2018.2.046/compilers_and_libraries_2018.2.199/linux/bin/intel64/mcpcom, terminated by kill signal
compilation aborted for /home/tcfishe/sparc/builds/trilinos-knl/packages/tpetra/core/src/Tpetra_CrsMatrix_INT_INT_LONG_LONG_OPENMP.cpp (code 1)
packages/tpetra/core/src/CMakeFiles/tpetra.dir/build.make:933: recipe for target 'packages/tpetra/core/src/CMakeFiles/tpetra.dir/Tpetra_CrsMatrix_INT_INT_LONG_LONG_OPENMP.cpp.o' failed
make[2]: *** [packages/tpetra/core/src/CMakeFiles/tpetra.dir/Tpetra_CrsMatrix_INT_INT_LONG_LONG_OPENMP.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
icpc: error #10106: Fatal error in /projects/Mutrino/hpcsoft/cle6.0/common/intel-clusterstudio/2018.2.046/compilers_and_libraries_2018.2.199/linux/bin/intel64/mcpcom, terminated by kill signal
compilation aborted for /home/tcfishe/sparc/builds/trilinos-knl/packages/tpetra/core/src/Tpetra_CrsMatrix_DOUBLE_INT_LONG_LONG_OPENMP.cpp (code 1)
packages/tpetra/core/src/CMakeFiles/tpetra.dir/build.make:920: recipe for target 'packages/tpetra/core/src/CMakeFiles/tpetra.dir/Tpetra_CrsMatrix_DOUBLE_INT_LONG_LONG_OPENMP.cpp.o' failed
make[2]: *** [packages/tpetra/core/src/CMakeFiles/tpetra.dir/Tpetra_CrsMatrix_DOUBLE_INT_LONG_LONG_OPENMP.cpp.o] Error 1
```

@mhoemmen

**Comment by nmhamster** [comment]
@tcfisher:

Are you using a particularly large `-j` setting for your `make` command?

I usually re-run with `make -j 2` for a bit and it gets through the nasty files. Can you try that?

**Comment by mhoemmen** [comment]
@trilinos/tpetra

**Comment by tcfisher** [comment]
I think I just had a module problem. Now I get the following failure:
```bash
In file included from /home/tcfishe/Trilinos/packages/xpetra/src/Map/Xpetra_TpetraMap_decl.hpp(55),
                 from /home/tcfishe/Trilinos/packages/xpetra/src/Map/Xpetra_TpetraMap_def.hpp(49),
                 from /home/tcfishe/sparc/builds/trilinos-knl/packages/xpetra/src/Utils/ExplicitInstantiation/Xpetra_TpetraMap.cpp(55):
/home/tcfishe/Trilinos/packages/xpetra/src/Map/Xpetra_Map.hpp(78): error: namespace "Kokkos::Compat" has no member "KokkosSerialWrapperNode"
    typedef Kokkos::Compat::KokkosSerialWrapperNode EpetraNode;
                            ^

In file included from /home/tcfishe/Trilinos/packages/xpetra/src/Import/Xpetra_Import.hpp(54),
                 from /home/tcfishe/Trilinos/packages/xpetra/src/Import/Xpetra_TpetraImport_def.hpp(50),
                 from /home/tcfishe/sparc/builds/trilinos-knl/packages/xpetra/src/Utils/ExplicitInstantiation/Xpetra_TpetraImport.cpp(55):
/home/tcfishe/Trilinos/packages/xpetra/src/Map/Xpetra_Map.hpp(78): error: namespace "Kokkos::Compat" has no member "KokkosSerialWrapperNode"
    typedef Kokkos::Compat::KokkosSerialWrapperNode EpetraNode;
                            ^
```
I'm building with epetra disabled in xpetra. Did someone miss something?
@jhux2

**Comment by mhoemmen** [comment]
@trilinos/muelu @trilinos/xpetra

**Comment by jhux2** [comment]
@tcfisher Would you mind if I poked around in your build on mutrino?

**Comment by jhux2** [comment]
And is this Trilinos develop or master?

**Comment by tcfisher** [comment]
I sent you the path. This is master.

**Comment by jhux2** [comment]
Hmm, this logic doesn't make any sense.  @csiefer2 

https://github.com/trilinos/Trilinos/blob/7d7ba6c91a1fb48bef3fabe800068950bfdc0529/packages/xpetra/src/Map/Xpetra_Map.hpp#L70-L79

**Comment by jhux2** [comment]
@tcfisher Can you point me to your configure script.  I want to see what breaks if I change this logic.

**Comment by tcfisher** [comment]
It's in the same directory as the path I sent you.
`do-cmake_trilinos_ats1-knl_intel_mpich.sh`

**Comment by jhux2** [comment]
I'll submit a PR shortly to fix this error.  However, the compile will fail later because ShyLUCore (which requires Epetra) attempts to create a `Zoltan2::XpetraCrsMatrixAdapter<Matrix,Vector>` with Matrix=Epetra_CrsMatrix, and Xpetra's support for Epetra is disabled:

```
/scratch/jhu/trilinos/Trilinos/packages/teuchos/core/src/Teuchos_RCP.hpp(755): error: a const_cast can only adjust type qualifiers; it cannot change the underlying type
    T2 *check = const_cast<T2*>(p1.get());
                                ^
          detected during:
            instantiation of "Teuchos::RCP<T2> Teuchos::rcp_const_cast<T2,T1>(const Teuchos::RCP<T1> &) [with T2=const Xpetra::CrsMatrix<double, int, int, KokkosClassic::DefaultNode::DefaultNodeType>, T1=Epetra_CrsMatrix]" at line 258 of "/scratch/jhu/trilinos/Trilinos/packages/zoltan2/src/input/Zoltan2_XpetraCrsMatrixAdapter.hpp"
            instantiation of "Zoltan2::XpetraCrsMatrixAdapter<User, UserCoord>::XpetraCrsMatrixAdapter(const Teuchos::RCP<const User> &, int) [with User=Epetra_CrsMatrix, UserCoord=Epetra_MultiVector]" at line 125 of "/scratch/jhu/trilinos/Trilinos/packages/shylu/shylu_dd/core/src/epetra/shylu_partition_interface_def.hpp"
            instantiation of "int ShyLU::PartitionInterface<Matrix, Vector>::partitionZoltan2() [with Matrix=Epetra_CrsMatrix, Vector=Epetra_MultiVector]" at line 153 of "/scratch/jhu/trilinos/Trilinos/packages/shylu/shylu_dd/core/src/epetra/shylu_partition_interface_def.hpp"

/scratch/jhu/trilinos/Trilinos/packages/zoltan2/src/input/Zoltan2_XpetraCrsMatrixAdapter.hpp(374): error: argument of type "int *" is incompatible with parameter of type "const Zoltan2::default_gno_t={Tpetra::Details::DefaultTypes::global_ordinal_type={long long}} *"
                                                       importList.getRawPtr());
                                                       ^
          detected during instantiation of "void Zoltan2::XpetraCrsMatrixAdapter<User, UserCoord>::applyPartitioningSolution(const User &, User *&, const Zoltan2::PartitioningSolution<Adapter> &) const [with User=Epetra_CrsMatrix, UserCoord=Epetra_MultiVector, Adapter=Zoltan2::XpetraCrsMatrixAdapter<Epetra_CrsMatrix, Epetra_MultiVector>]" at line 192 of "/scratch/jhu/trilinos/Trilinos/packages/shylu/shylu_dd/core/src/epetra/shylu_partition_interface_def.hpp"

/scratch/jhu/trilinos/Trilinos/packages/teuchos/core/src/Teuchos_RCP.hpp(288): error: a value of type "Epetra_MultiVector *" cannot be used to initialize an entity of type "Xpetra::MultiVector<double, int, int, KokkosClassic::DefaultNode::DefaultNodeType> *"
    : ptr_(r_ptr.get()), // will not compile if T is not base class of T2
           ^
          detected during:
            instantiation of "Teuchos::RCP<T>::RCP(const Teuchos::RCP<T2> &) [with T=Xpetra::MultiVector<double, int, int, KokkosClassic::DefaultNode::DefaultNodeType>, T2=Epetra_MultiVector]" at line 228 of "/scratch/jhu/trilinos/Trilinos/packages/zoltan2/src/input/Zoltan2_XpetraMultiVectorAdapter.hpp"
            instantiation of "Zoltan2::XpetraMultiVectorAdapter<User>::XpetraMultiVectorAdapter(const Teuchos::RCP<const User> &) [with User=Epetra_MultiVector]" at line 223 of "/scratch/jhu/trilinos/Trilinos/packages/shylu/shylu_dd/core/src/epetra/shylu_partition_interface_def.hpp"

/scratch/jhu/trilinos/Trilinos/packages/zoltan2/src/input/Zoltan2_XpetraMultiVectorAdapter.hpp(297): error: argument of type "int *" is incompatible with parameter of type "const Zoltan2::default_gno_t={Tpetra::Details::DefaultTypes::global_ordinal_type={long long}} *"
                                                       importList.getRawPtr());
                                                       ^
          detected during instantiation of "void Zoltan2::XpetraMultiVectorAdapter<User>::applyPartitioningSolution(const User &, User *&, const Zoltan2::PartitioningSolution<Adapter> &) const [with User=Epetra_MultiVector, Adapter=Zoltan2::XpetraCrsMatrixAdapter<Epetra_CrsMatrix, Epetra_MultiVector>]" at line 224 of "/scratch/jhu/trilinos/Trilinos/packages/shylu/shylu_dd/core/src/epetra/shylu_partition_interface_def.hpp"

compilation aborted for /scratch/jhu/trilinos/Trilinos/packages/shylu/shylu_dd/core/src/epetra/shylu_partition_interface.cpp (code 2)
make: *** [packages/shylu/shylu_dd/core/src/CMakeFiles/shylu_ddcore.dir/epetra/shylu_partition_interface.cpp.o] Error 2
```

If SPARC does not require ShyLU_DDCore, then `-D Trilinos_ENABLE_ShyLU_DDCore=OFF` will allow the compile to finish successfully.

However, I believe the correct solution should be for ShyLU_DDCore to have logic to determine whether Zoltan2 can provide an Xpetra Epetra_CrsMatrix adapter, either a Zoltan macro or Xpetra macro.

@srajama1 @kddevin

**Comment by jhux2** [comment]
@tcfisher PR 5243 has been merged.

**Comment by tcfisher** [comment]
@jhux2, do you know why this only happens on KNL builds?

**Comment by tcfisher** [comment]
@srajama1, @kddevin, we need this to do some Sparc milestone work. Can you give me a timeline for a build fix for this type of configuration? Unfortunately we cannot disable ShyLU_DDCore on KNL.

**Comment by kddevin** [comment]
@tcfisher  Thanks for the ping.
You say above that you build Xpetra without Epetra support.  Is it necessary to disable the Epetra support in Xpetra?

**Comment by tcfisher** [comment]
@kddevin, it is necessary to disable Epetra in Xpetra to use Xpetra's ETI, which allows us to build intel with OpenMP in debug mode. Otherwise we have to either 1) not use Xpetra ETI, which eliminates our ability to use debug due to library size or 2) enable Tpetra int instantiations in addition to our Tpetra long long instantiations which may also eliminate our ability to use debug due to library size. 
@jhux2 is helping me evaluate whether what we need from ShyLU, which is HTS, can be used without DDCore.

**Comment by tcfisher** [comment]
> @tcfisher:
> 
> Are you using a particularly large `-j` setting for your `make` command?
> 
> I usually re-run with `make -j 2` for a bit and it gets through the nasty files. Can you try that?

@nmhamster, this worked to get through the files when we use qoverride-limits on KNL. 

@trilinos/tpetra, is there a possibility of breaking these files up so they don't take so much memory to compile with OpenMP?

**Comment by mhoemmen** [comment]
@tcfisher The files are already broken up into one per instantiation.  Reducing compile times further will require nontrivial work in both kokkos-kernels and Tpetra.

**Comment by tcfisher** [comment]
@mhoemmen, has something changed in the past couple months in these files to make them even larger? Micah does not recall having to reduce the number of build threads so drastically.

**Comment by nmhamster** [comment]
@tcfisher - are you using the general Intel programming environment. One thing which has changed is that the compilers have updated. They generate better code in some areas so this could be causing longer compile times and objects.

**Comment by tcfisher** [comment]
@nmhamster, we use PrgEnv-intel/6.0.4 and intel/18.0.2. Not sure about when this last changed...

**Comment by mhoemmen** [comment]
I don't imagine that the total number of lines of code has decreased, nor do I see any concerted efforts to reduce build time (with the exception of @tjfulle , who has been working on detangling CrsGraph from CrsMatrix so that we can hide the implementation of the former).

**Comment by nmhamster** [comment]
@tcfisher - its possible the compiler moved from Intel 17 to Intel 18 in this timeframe. One option might be to look at the old binary if you have it (using `ldd`).

**Comment by jhux2** [comment]
> it is necessary to disable Epetra in Xpetra to use Xpetra's ETI, which allows us to build intel with OpenMP in debug mode. Otherwise we have to either 1) not use Xpetra ETI, which eliminates our ability to use debug due to library size or 2) enable Tpetra int instantiations in addition to our Tpetra long long instantiations which may also eliminate our ability to use debug due to library size.
> @jhux2 is helping me evaluate whether what we need from ShyLU, which is HTS, can be used without DDCore.

Just to close the loop, DDCore is not necessary.  Sparc only needs HTS, and so could disable DDCore.

**Comment by srajama1** [comment]
@jhux2 : Disabling DDCore seems like the best path.
