### ISSUE TITLE
Various problems in building trilinos

### ISSUE THREAD

**Issue by leonavery** [trilinos/Trilinos#524]
I'm trying to build Trilinos on an old centos 6 system, on which I have installed, I believe, all prerequisites. I've run into some unexpected behaviors that I don't understand. I configured and generated Makefiles with cmake-gui, then used "make -k VERBOSE=1 all" for the build, so I could see which exact commands failed. 

The first occurred while building Mesquite. I got a mort of errors about undefined references to MPi functions. g++ was used in the build, and when I manually issued the command, replacing g++ with mpic++, it worked. I have MPI_USE_COMPILER_WRAPPERS=ON, and I even manually set the paths to the wrappers in MPI_{C,CXX,Fortran}_COMPILER. So why aren't the wrappers being used? (This one I was able to get around by setting Trilinos_EXTRA_LINK_FLAGS:STRING="-lmpi".)

The second problem is with PyTrilinos, specifcally with the NOX-PETSc interface. During configuration, there are errors from SWIG about several header files not being found. These headers are present in the source distribution at trilinos-12.6.3-Source/packages/nox/src-petsc, but apparently swig is not told to look for headers there. The same problem occurs during compilation. Compilation of several c++ files fails, because they are unable to find the same headers that swig failed to find. g++ is passed a long list of -I flags for this compilation, but there is no -I<path>/trilinos-12.6.3-Source/packages/nox/src-petsc in the list. I don't know enough about cmake to figure out how it produces the list of include directories, but apparently this one is being left out for PyTrilinos. (I'm now trying to work around it with CMAKE_CXX_FLAGS.)

**Comment by mhoemmen** [comment]
1. Are you able to build Trilinos with both those packages disabled?
2. What compiler version are you using?

**Comment by leonavery** [comment]
>Are you able to build Trilinos with both those packages disabled?
Yes, although I got an error (which I think I have fixed) when I tried "make install".

>What compiler version are you using?
gcc-6.1.0

I will post CMakeCache.txt and make log from a failed build tomorrow. (I didn't keep the failures around, and the full build takes several hours.)

**Comment by leonavery** [comment]
All right, here's some documentation. 

CMakeCache.txt
[CMakeCache.txt](https://github.com/trilinos/Trilinos/files/384042/CMakeCache.txt)

In the Build directory, I then did:
    cmake-gui ../trilinos-12.6.3-Source &

After clicking the Configure button, I copied everything in the output window and pasted it into 
this file:
[CMakeGuiConfigure.log.txt](https://github.com/trilinos/Trilinos/files/384044/CMakeGuiConfigure.log.txt)

Next, I did:

    make -j4 -k VERBOSE=1 all > make.log

That is 44.5 MB, so i can't attach it here. But after the make completed (with errors), I did:

    make -j4 -k VERBOSE=1 all > & make_stderr.log

which replays all the errors. 
[make_stderr.log.txt](https://github.com/trilinos/Trilinos/files/384045/make_stderr.log.txt)

You will see that, in addition to MPI link errors in Mesquite, I got them this time in some other packages as well. I don't know why this is different from my previous attempts. The PyTrilinos errors in compiling things that need headers from src-petsc are the same.

**Comment by mhoemmen** [comment]
Thanks for posting this!  btw what packages do you really need?  (You don't have to answer in public if you don't want.)

**Comment by leonavery** [comment]
> btw what packages do you really need?
Probably none, actually. I'm building FEniCS, and trilinos is an 
optional plug-in. I just wanted to make the most functional version I 
could, and the frustration of unaccountable errors took on a momentum of 
its own.


--

Leon Avery

**Comment by leonavery** [comment]
BTW, my strategy of using CMAKE_*_FLAGS to get around the issue of the header files not being found failed, because it's not just C and C++ compilers that need to find them -- it's also swig. I tried setting CMAKE_SWIG_FLAGS:STRING=-I<stuff>, but that had no effect. So I guess I will just disable PyTrilinos.

**Comment by mhoemmen** [comment]
> So I guess I will just disable PyTrilinos.

I was going to suggest disabling the packages that failed and trying again.

**Comment by leonavery** [comment]
That works. Trilinos_EXTRA_LINK_FLAGS:STRING="-lmpi" allows all the things that need MPI to link, and without PyTrilinos I get an (apparently) error-free build and install.

**Comment by mhoemmen** [comment]
> Trilinos_EXTRA_LINK_FLAGS:STRING="-lmpi" allows all the things that need MPI to link, ...

Is this a Mesquite-specific issue?

> ... without PyTrilinos I get an (apparently) error-free build and install.

I'll create a new issue for PyTrilinos.  Glad to hear it works now, and thanks for helping out!

**Comment by mhoemmen** [comment]
@leonavery #528 now governs the PyTrilinos NOX-PETSc interface build issues that you reported (thanks!).

**Comment by leonavery** [comment]
>>Trilinos_EXTRA_LINK_FLAGS:STRING="-lmpi" allows all the things that need MPI to link, ...

>Is this a Mesquite-specific issue?

Well, I'm now confused about that. At first, I had this problem only with Mesquite. But in my latest attempt to repeat the issue, it happened not just with libmesquite.so, but libzoltan.so also failed to link with the same errors.

**Comment by mhoemmen** [comment]
> Well, I'm now confused about that. At first, I had this problem only with Mesquite. But in my latest attempt to repeat the issue, it happened not just with libmesquite.so, but libzoltan.so also failed to link with the same errors.

That is quite weird.  I've split the Mesquite issue into its own issue, #529.  However, this could be a problem with your MPI setup.
