### ISSUE TITLE
Nalu Trilinos configs fails due to missing Parmetis - now required for STK_Rebalance?

### ISSUE THREAD

**Issue by spdomin** [trilinos/Trilinos#5245]
## Bug Report
@trilinos/stk

Greetings,

Trilinos develop, commit 9c140c2689d3fa761fef3b65d02161d02b66d471 is showing issues in my Mac testing. I also have a new set of diffs on gcc 7.2 that I will investigate today.

Looks like STKRebalance now requires ParMETIS? In order to move forward, I need to set the following:

-DTPL_ENABLE_ParMETIS=OFF
-DTrilinos_ENABLE_STKBalance:BOOL=OFF \

However, since STKUnit requires rebalance, I then need to turn off STKUnit. I can do this, however, this is starting feeling **not** like a toolkit.

 Any advice will be much appreciated.

**Comment by alanw0** [comment]
commit 9c140c2 is not a stk commit.

Sorry for introducing the mandatory ParMETIS requirement, that's an error in our cmake file. I'll fix that as soon as possible. It should be an optional dependency.

We have plans to fix the cmake files for stk_unit_tests so that the unit-tests for individual sub-packages can be turned on and off. Perhaps then stk can be a toolkit again.

**Comment by alanw0** [comment]
Pull request #5246 is in progress to fix the cmake file to remove the ParMETIS mandatory dependence. It will probably take a couple hours to work its way through, it should be in today.

**Comment by spdomin** [comment]
Okay, great. For short term, I have the Unit tests off and the build is working fine.

Above, I meant "as of current Trilinos SHA1" and did not mean to imply that that commit caused the issue.

**Comment by alanw0** [comment]
Pull request #5246 has now been merged into the develop branch. This pull-request removed the mandatory ParMETIS dependence, and also fixed a compile issue (as seen by nalu-wind, presumably similar for nalu-cfd) due to the boost deprecation in stk_transfer.

**Comment by spdomin** [comment]
Yes, similar as per our conversation this morning. Thanks. I will signal for close-out after a successful nightly test cycle.

**Comment by spdomin** [comment]
Tests are clean - closing with thanks.
