### ISSUE TITLE
Ifpack2::Chebyshev: Fuse "scaled damped residual" kernel

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#5249]
## Enhancement
@trilinos/ifpack2 @csiefer2 @jhux2 

Ifpack2::Chebyshev depends on the following computational kernels:

  * First iteration:
    * (Untested case) either `W := (1/theta)*D_inv*B` and `X := 0 + W`; or,
    * (Tested case) if the initial guess is assumed nonzero, `W := (1/theta)*D_inv*(B-A*X)` and `X := X + W`.
  * Subsequent iterations: `W := alpha*D_inv*(B-A*X) + beta*W` and `X := X + W`.

Here, `D_inv` is the inverse of a diagonal matrix, stored as a `Tpetra::Vector`.  This makes the following operation a candidate for kernel fusion:

`W := alpha*D_inv*(B-A*X) + beta*W`

I call this kernel "compute a scaled damped residual vector."  Note that we can't fuse this with a subsequent `X := X + W`, because X as output has data-dependent loop dependencies with X as input (in the sparse matrix-vector multiply `A*X`).

Right now, Ifpack2 issues the following kernels:
  1. `Tpetra::deep_copy (V1, B);`
  2. `A.apply (X, V1, Teuchos::NO_TRANS, -1.0, 1.0);`
  3. `W.elementWiseMultiply (alpha, D_inv, V1, beta);`

If the matrix A has no Export object, then we can fuse all these kernels into one.  This will make each iteration take only two kernels instead of four, not counting pack and unpack kernels in the sparse matrix-vector multiply.  In addition, we can get rid of the temporary vector V1.

**Comment by mhoemmen** [comment]
I have a local fix that passes Ifpack2's tests.

**Comment by csiefer2** [comment]
As per our meeting today, we now need to (a) write a test and  (b) do the kernel for the zero starting guess case.

**Comment by mhoemmen** [comment]
First iteration of Chebyshev looks like this:
```c++
  // Special case for the first iteration.
  if (! zeroStartingSolution_) {
    // NOTE: Ifpack2's tests don't actually exercise this path.
    if (sdr_.is_null ()) { // lazy init
      Teuchos::RCP<const op_type> A_op = A_;
      sdr_ = Teuchos::rcp (new ScaledDampedResidual<op_type> (A_op));
    }
    // W := (1/theta)*D_inv*(B-A*X) and X := X + W.
    sdr_->compute (W, one/theta, D_inv, B, X, zero);
    X.update (one, W, one);
  }
  else {
    // W := (1/theta)*D_inv*B and X := 0 + W.
    firstIterationWithZeroStartingSolution (W, one/theta, D_inv, B, X);
  }
```

**Comment by mhoemmen** [comment]
The `! zeroStartingSolution_` case is already fused.  (We can't fuse the update of X with the previous line, because data dependencies in X are not strictly `i -> i`.)  `firstIterationWithZeroStartingSolution` is not fused.  It does this:
```c++
  W.elementWiseMultiply (alpha, D_inv, B, 0.0); // W := alpha*D_inv*B
  Tpetra::deep_copy (X, W); // X = 0 + W
```
Fusion should be pretty easy for this case.  We could even have a special case for two sweeps:
```
W := dtemp2 * D_inv * (B - A * (alpha*D_inv*B)) + dtemp1 * (alpha*D_inv*B);
X := alpha*D_inv*B + W;
```
That reduces two sweeps to two kernels, not counting DistObject kernels.

**Comment by jhux2** [comment]
@mhoemmen Perhaps a stupid question -- why couldn't the multivector case be fused?

**Comment by mhoemmen** [comment]
@jhux2 We should be able to fuse for MultiVectors with constant stride.  It might not pay quite so much, though, given that we have column-major MultiVectors.
