### ISSUE TITLE
Panzer: compiler error: stk_mesh/base/CoordinateSystems.hpp: no such file

### ISSUE THREAD

**Issue by tawiesn** [trilinos/Trilinos#525]
@trilinos/panzer @trilinos/stk 
After updating Trilinos to the most recent develop version (f1d9dfc6f055d8) i get the following errors:

> In file included from /home/tawiesn/software/trilinos/Trilinos/packages/panzer/adapters-stk/src/Panzer_STK_Utilities.hpp:46:0,
>                  from /home/tawiesn/software/trilinos/Trilinos/packages/panzer/adapters-stk/src/Panzer_STK_Utilities.cpp:45:
> /home/tawiesn/software/trilinos/Trilinos/packages/panzer/adapters-stk/src/stk_interface/Panzer_STK_Interface.hpp:55:47: fatal error: stk_mesh/base/CoordinateSystems.hpp: No such file or directory
>  #include <stk_mesh/base/CoordinateSystems.hpp>
>                                                ^
> compilation terminated.
> In file included from /home/tawiesn/software/trilinos/Trilinos/packages/panzer/adapters-stk/src/Panzer_STK_SetupUtilities.hpp:46:0,
>                  from /home/tawiesn/software/trilinos/Trilinos/packages/panzer/adapters-stk/src/Panzer_STK_SetupUtilities.cpp:43:
> /home/tawiesn/software/trilinos/Trilinos/packages/panzer/adapters-stk/src/stk_interface/Panzer_STK_Interface.hpp:55:47: fatal error: stk_mesh/base/CoordinateSystems.hpp: No such file or directory
>  #include <stk_mesh/base/CoordinateSystems.hpp>
>                                                ^
> compilation terminated.
> In file included from /home/tawiesn/software/trilinos/Trilinos/packages/panzer/adapters-stk/src/Panzer_STKConnManager.hpp:57:0,
>                  from /home/tawiesn/software/trilinos/Trilinos/packages/panzer/adapters-stk/src/Panzer_STKConnManager.cpp:45:
> /home/tawiesn/software/trilinos/Trilinos/packages/panzer/adapters-stk/src/stk_interface/Panzer_STK_Interface.hpp:55:47: fatal error: stk_mesh/base/CoordinateSystems.hpp: No such file or directory
>  #include <stk_mesh/base/CoordinateSystems.hpp>
>                                                ^
> compilation terminated.
> In file included from /home/tawiesn/software/trilinos/Trilinos/packages/panzer/adapters-stk/src/Panzer_STK_SurfaceNodeNormals.cpp:45:0:
> /home/tawiesn/software/trilinos/Trilinos/packages/panzer/adapters-stk/src/stk_interface/Panzer_STK_Interface.hpp:55:47: fatal error: stk_mesh/base/CoordinateSystems.hpp: No such file or directory
>  #include <stk_mesh/base/CoordinateSystems.hpp>
>                                                ^
> compilation terminated.
> In file included from /home/tawiesn/software/trilinos/Trilinos/packages/panzer/adapters-stk/src/Panzer_STK_IOClosureModel_Factory_decl.hpp:50:0,
>                  from /home/tawiesn/software/trilinos/build/do-configure-drekar/packages/panzer/adapters-stk/src/Panzer_STK_IOClosureModel_Factory.hpp:1,
>                  from /home/tawiesn/software/trilinos/Trilinos/packages/panzer/adapters-stk/src/Panzer_STK_IOClosureModel_Factory.cpp:45:
> /home/tawiesn/software/trilinos/Trilinos/packages/panzer/adapters-stk/src/stk_interface/Panzer_STK_Interface.hpp:55:47: fatal error: stk_mesh/base/CoordinateSystems.hpp: No such file or directory
>  #include <stk_mesh/base/CoordinateSystems.hpp>
>                                                ^
> compilation terminated.
> In file included from /home/tawiesn/software/trilinos/Trilinos/packages/panzer/adapters-stk/src/Panzer_STK_WorksetFactory.hpp:50:0,
>                  from /home/tawiesn/software/trilinos/Trilinos/packages/panzer/adapters-stk/src/Panzer_STK_WorksetFactory.cpp:43:
> /home/tawiesn/software/trilinos/Trilinos/packages/panzer/adapters-stk/src/stk_interface/Panzer_STK_Interface.hpp:55:47: fatal error: stk_mesh/base/CoordinateSystems.hpp: No such file or directory
>  #include <stk_mesh/base/CoordinateSystems.hpp>
>                                                ^
> compilation terminated.
>

**Comment by jdmille** [comment]
Is this a Trilinos problem or a sierra stk problem?


=================================================
Joel D. Miller
Sierra Mechanics User Support [sierra-help@sandia.gov<mailto:sierra-help@sandia.gov>]
Scientific Applications & User Support Dept. 9326
Sandia National Laboratories
Albuquerque, NM 87185-0845
phone: (505) 844-1255
email: jdmille@sandia.gov<mailto:jdmille@sandia.gov>
=================================================

**Comment by tawiesn** [comment]
There were quite a few changes in panzer recently. A first guess would be, it is a problem in panzer?

**Comment by tawiesn** [comment]
Update: i had STK_mesh explicitly disabled in my configuration script. That is, obviously the package dependencies have changed (i.e. we need STK_mesh for compiling panzer).
Anyway, this solved this compiler problem. There are others. :-(

@trilinos/panzer Could you please update the dependencies? I think STK_mesh is needed in panzer/adapters-stk

**Comment by jmgate** [comment]
I ran into this yesterday as well.  The fix was to update my configure script with the following:
-D Trilinos_ENABLE_STKClassic:BOOL=OFF \
-D Trilinos_ENABLE_STK:BOOL=ON \
-D Trilinos_ENABLE_STKMesh:BOOL=ON \
-D Trilinos_ENABLE_STKUtil:BOOL=ON \
-D Trilinos_ENABLE_STKTopology:BOOL=ON \
-D Trilinos_ENABLE_STKTransfer:BOOL=ON \

**Comment by rppawlo** [comment]
Just to follow up - on Saturday, panzer switched from STK_Classic to the new STK. Due to not being able to build both STK Classic and new STK at the same time, you needed to hard enable STK Classic for panzer builds. With the switch, you now need to change panzer configures as Jason showed above.

**Comment by tawiesn** [comment]
Thanks for the comments! In addition to the configuration settings recommended by @jmgate i also had to make sure that STKIO is enabled (that is, Trilinos_ENABLE_STKIO is not set to OFF).
With these settings i can confirm that panzer is compiling.

I think it would make sense to update the Dependencies.cmake files in Panzer accordingly.
