### ISSUE TITLE
Teuchos:  logical operator macro 'and' not working in MSVC

### ISSUE THREAD

**Issue by hillyuan** [trilinos/Trilinos#5256]
## Enhancement
@trilinos/\<Teuchos\>

When using MSVC, compile error occurs at Logical operator 'and' in Teuchos_StackedTimer.cpp. Include file 'iso646.h' may needed to solve this problem. On the other hand, logical operator '&&' '!' are used elsewhere in the same file. It is therefore considered that operator 'and' be modified into '&&' form style consistent consideration

**Comment by mhoemmen** [comment]
@trilinos/teuchos

**Comment by csiefer2** [comment]
I believe this is already fixed in develop.

**Comment by hillyuan** [comment]
Fixed in develop.
