### ISSUE TITLE
PR tester: potential bug, change in Trilinos/cmake/ctest/drivers causes non-trivial testing

### ISSUE THREAD

**Issue by jhux2** [trilinos/Trilinos#5267]
@trilinos/framework 

PR #5266 made a change to `cmake/ctest/drivers`, which isn't supposed to initiate any non-trivial compilation/testing.  But as can be seen from [these results](https://testing.sandia.gov/cdash/index.php?project=Trilinos&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=63&value1=PR-5266-test&field2=buildstarttime&compare2=84&value2=NOW), one of the compile/test cycles is definitely non-trivial.

**Comment by prwolfe** [comment]
I think this is related to my work on incremental builds - I will look into it.

**Comment by prwolfe** [comment]
This should have been resolved with the merge of #5800 and #5668 

@jhux2 - can you confirm so I can close this?

Thanks!

**Comment by jhux2** [comment]
@prwolfe I'll let you know, PR #6056 will test this.

**Comment by jhux2** [comment]
@prwolfe. Still looks like the auto tester is configuring some builds.  See #6056.

**Comment by prwolfe** [comment]
That looks like I expect - No packages configured (except for the 2 python tests which are always going to run.) 0 builds done in 0 seconds - what is bothering you about this one?

**Comment by jhux2** [comment]
@prwolfe Ah, that's expected behavior, I just didn't know that.   I'll closed this as fixed.  Thank you for your help.

**Comment by prwolfe** [comment]
Cool - Thanks!
