### ISSUE TITLE
Sacado,Stokhos: No Kokkos::ArithTraits specializations?

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#5269]
@trilinos/stokhos @trilinos/sacado @etphipp 

It appears that there are no `Kokkos::ArithTraits` specializations for Sacado or Stokhos types.  I discovered this the hard way here:  https://github.com/trilinos/Trilinos/pull/5263 

This hinders thread parallelization of `Ifpack2::Relaxation` setup.

**Comment by mhoemmen** [comment]
I'm not sure, but I may be mistaken about this.  See the following:

- https://github.com/trilinos/Trilinos/pull/5263/commits/7eadfe6bade158181b973a925e6e6c4b50b3889f
- https://github.com/trilinos/Trilinos/pull/5263#issuecomment-497034412 

It could be that I was returning an arithmetic expression involving a Sacado type from a lambda, instead of returning the actual Sacado type.  That may have meant that the compiler was looking for an ArithTraits specialization for the expression type, instead of for the actual Sacado type.  I'll leave this issue open in case @etphipp wants to comment.

**Comment by etphipp** [comment]
There most certainly are Sacado/Stokhos specializations for Kokkos::ArithTraits, and looking at the code I can see how the expression template gets returned, so this was likely the case.  Its an unfortunate side effect of expression templates.  

Is there any remaining issue here?

**Comment by mhoemmen** [comment]
@etphipp Thanks for the clarification!  The expression template thing is not a bug -- it's just how expression templates work, as you pointed out.  I'll be happy to close this.
