### ISSUE TITLE
Trilinos: DependInfo.cmake generation

### ISSUE THREAD

**Issue by tjfulle** [trilinos/Trilinos#5272]
## Question

I am evaluating CLion for its remote debugging capabilities, but run in to a snag when configuring - CLion expects `DependInfo.cmake` to be generated in seemingly every sub package build directory.  For example, it expects `packages/tpetra/core/ext/src/CMakeFiles/edit_cache.dir/DependInfo.cmake`, but this file is not generated.  Many `DependInfo.cmake` files are generated.

The absence of these files does not impact a manual `CMake -> make` workflow, it just stops CLion from importing Trilinos fully.

Is there a CMake setting I can toggle to build these files unconditionally?

@bartlettroscoe is there a Tribits setting?

**Comment by bartlettroscoe** [comment]
@tjfulle, not sure how/why cmake generates that file.  Have you tried the ninja generator?  Otherwise, we should ask kitware.

**Comment by tjfulle** [comment]
Thanks @bartlettroscoe!  CLion does not support the Ninja generator :(. I’ll ask KitWare and JetBrains (maker of CLion) what they suggest.
