### ISSUE TITLE
Tpetra: Check input Views to make sure pointer matches memory space

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#5279]
## Enhancement
@trilinos/tpetra 

Context: Run-time errors in Panzer CUDA build.  See discussion [starting here](https://github.com/trilinos/Trilinos/issues/5179#issuecomment-496962330).

Whenever a Tpetra object (Map, MultiVector, CrsGraph, CrsMatrix) takes a Kokkos::View or Kokkos::DualView from the user, use the CUDA Runtime API to check the pointers.  Make sure that if the user claims that the View is a device View, then the pointer is a valid device pointer.

**Comment by mhoemmen** [comment]
I have a fix in progress for this.

**Comment by vbrunini** [comment]
Perhaps Kokkos should do this in the View constructor that takes a pointer? Maybe just in a debug mode?

**Comment by mhoemmen** [comment]
CUDA 11.0 has a much more reliable test than CUDA 9.2.  I'm still working out the kinks.

**Comment by mhoemmen** [comment]
@vbrunini I worked out the kinks :-) (turns out null pointers are not accessible from anywhere)
