### ISSUE TITLE
Belos: unresolved external symbol errors in MSVC

### ISSUE THREAD

**Issue by hillyuan** [trilinos/Trilinos#5284]
## Enhancement
@trilinos/belos 

When using VS2017, VS2019, following link error occurs when trying to link belosepetra.lib. 
```
unresolved external symbol ""class std::basic_ostream<char,struct std::char_traits<char> > std::cout" (?cout@std@@3V?$basic_ostream@DU?$char_traits@D@std@@@1@A)"	
```
(No problem when compiled in linux with gcc)

After sometimes of debug, I found it is due to the following sentence in all those BelosXXXMgr.hpp
files
```
static constexpr std::ostream * outputStream_default_ = &std::cout;
```
It is therefore modified as
```
static constexpr std::ostream * outputStream_default_ = nullptr;
```
and constructor of class member outputStream_ modified into
```
outputStream_((outputStream_default_) ? Teuchos::rcp(outputStream_default_,false): Teuchos::rcpFromRef(std::cout))
```
Everything works well after above modification.

My problem is:
1. I cannot understand the why above LINK error happens.
2. If the above modification available from the viewpoint of Belos development team.

Much thanks.

**Comment by mhoemmen** [comment]
@hillyuan wrote:
> 1. I cannot understand the why above LINK error happens.

Neither do I :-)

> 2. If the above modification available from the viewpoint of Belos development team.

It looks OK to me, though an even simpler modification would be to get rid of `outputStream_default_` and just assign `outputStream_` this way:
```c++
outputStream_ (Teuchos::rcpFromRef (std::cout))
```
@hkthorn , what do you think?

**Comment by hillyuan** [comment]
> @hillyuan wrote:
> 
> 
> I cannot understand the why above LINK error happens.
> 
> 
> Neither do I :-)
> 
> 
> If the above modification available from the viewpoint of Belos development team.
> 
> 
> It looks OK to me, though an even simpler modification would be to get rid of outputStream_default_ and just assign outputStream_ this way:
> outputStream_ (Teuchos::rcpFromRef (std::cout))
> @hkthorn , what do you think?

It seems that Belos allows user defined output stream from parameterList definition. The introduction of static variable outputStream_default_ is considered trying to do this: it is std::cout by default and could point to other stream defined by parameterList. It is therfore we cannot simply set outputStram_ to std::cout.

Variable "outputStream_default_" may be not needed. Such implementation is given in class BlockGCRODRSolMgr, it set parameterList to std::cout by default and could be modified later. I think it is clearer way than that use static variable outputStream_default_. They are based upon different design principle, in fact, we cannot find any static member inside class BlockGCRODRSolMgr.

**Comment by mhoemmen** [comment]
@hillyuan wrote:
> It seems that Belos allows user defined output stream from parameterList definition.

I'm pretty familiar with Belos :-)  Your statement is accurate.  My concern is that Belos may not have tests that adequately exercise user-defined output streams.  However, I think either your proposed code change or mine would work.

> Variable `outputStream_default_` may be not needed.

It's not needed, I agree.  Those static variables used to be just plain static variables that were not `constexpr`.  We made them `constexpr` a while back in hopes that they wouldn't stick around in memory.  My guess is that MSVC may have some bugs in its `constexpr` support.
