### ISSUE TITLE
STK_NGP unit test "File Not Found"

### ISSUE THREAD

**Issue by spdomin** [trilinos/Trilinos#5298]
## Bug Report
@trilinos/stk_ngp

### Description
Nightly Mac build error on Trilinos/develop

16 warnings generated.
/Users/naluIt/gitHubWork/nightlyBuildAndTest/Trilinos/packages/stk/stk_unit_test_utils/unit_main_lib/UnitTestMain.cpp:38:10: fatal error: 'stk_ngp_test/ngp_test.hpp' file not found
#include <stk_ngp_test/ngp_test.hpp>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by alanw0** [comment]
@spdomin can you paste or send your config output? This is clearly related to my recent changes to make it possible to enable some unit-tests without enabling all, but I'm puzzled as to why ngp-test would be disabled... Also puzzled as to why the mac is broken while none of the other platforms appear broken.

**Comment by spdomin** [comment]
@alanw0, the passing non-Mac platforms was a mistake on my part. See: 

https://github.com/trilinos/Trilinos/issues/5299

In my case, the Trilinos build fails and the Nalu config finds an older "stable" Trilinos. As such, this issue is in all platforms on which I test.

I will send you the config in an email. Below are the options:

-DTrilinos_ENABLE_STKMesh:BOOL=ON \
-DTrilinos_ENABLE_STKSimd:BOOL=ON \
-DTrilinos_ENABLE_STKIO:BOOL=ON \
-DTrilinos_ENABLE_STKTransfer:BOOL=ON \
-DTrilinos_ENABLE_STKSearch:BOOL=ON \
-DTrilinos_ENABLE_STKUtil:BOOL=ON \
-DTrilinos_ENABLE_STKTopology:BOOL=ON \
-DTrilinos_ENABLE_STKRebalance:BOOL=OFF \
-DTrilinos_ENABLE_STKUnit_tests:BOOL=ON \
-DTrilinos_ENABLE_STKUnit_test_utils:BOOL=ON \
-DTrilinos_ENABLE_Gtest:BOOL=ON \
-DTrilinos_ENABLE_STKClassic:BOOL=OFF \

that demonstrate (now on both Mac and Linux gcc 7.2)

[ 87%] Building CXX object packages/stk/stk_unit_test_utils/CMakeFiles/stk_unit_main.dir/unit_main_lib/UnitTestMain.cpp.o
/scratch/spdomin/nightlyBuildAndTest/Trilinos/packages/stk/stk_unit_test_utils/unit_main_lib/UnitTestMain.cpp:38:10: fatal error: stk_ngp_test/ngp_test.hpp: No such file or directory
 #include <stk_ngp_test/ngp_test.hpp>

**Comment by alanw0** [comment]
@spdomin ok, I'll look for the config output.
Note: You probably meant to say '-DTrilinos_ENABLE_STKBalance:BOOL=OFF'. There is no such thing as STKRebalance nor STKClassic these days, so those options have no effect.

**Comment by alanw0** [comment]
Pull Request #5305 is in progress and should fix this issue once it goes in.
A lot of stk unit-tests use the STK_NGP_TEST sub-package now. That's a relatively new package, it's not surprising that you didn't have it enabled. Once this pull-request is in, your current set of options should work, but most stk unit-tests will be disabled. If you wish to build more stk unit-tests, you can add '-DTrilinos_ENABLE_STKNGP_TEST:BOOL=ON'. Or preferably, you could use use '-DTrilinos_ENABLE_STK:BOOL=ON' and then just list the specific sub-packages that you want to disable.

**Comment by spdomin** [comment]
great. I will report back once I see a successful build and test cycle.

**Comment by spdomin** [comment]
Clean nightly build and test.
