### ISSUE TITLE
Trilinos application config question

### ISSUE THREAD

**Issue by spdomin** [trilinos/Trilinos#5299]
## Question
@trilinos/build

I have a simple configuration question for Nalu. 

Specifically, I maintain both a Trilinos nightly and stable installation location. My problem is that if the Trilinos nightly process fails, the Nalu config still finds a Trilinos version and the application nightly testing proceeds. See below for an example… 

How can I ensure that the config step fails if it does not find the exact Trilinos that I am pointing to in my application configuration? Does proximity of my two installation directories matter? If so, this might explain why some platforms still end up passing while others fail.

find: `./CMakeFiles': No such file or directory
find: `./reg_tests/CMakeFiles': No such file or directory
   Trilinos_DIR = /home/spdomin/gitHubWork/scratch_build/install/gcc7.2.0/Trilinos_nightly_release

Found Trilinos!  Here are the details: 
   Trilinos_DIR = //ascldap/users/spdomin/gitHubWork/scratch_build/install/gcc7.2.0/Trilinos_stable_release/lib/cmake/Trilinos

**Comment by mhoemmen** [comment]
It sounds like you want some kind of script that tells Nalu's nightly tests whether the Trilinos configuration succeeded that night.  Is that right?

**Comment by spdomin** [comment]
Yes, that would work. Alternatively, a less exhaustive TPL "find" option?

In short, if I ask for a version of Trilinos in my Nalu config file that does not exist, how do I error out then and there?

**Comment by mhoemmen** [comment]
It's not really a "version of Trilinos" -- it sounds like you're building against latest master or develop, in which case your script would need to check the SHA1.  Trilinos' source code doesn't have a macro or other way to get the current SHA1.  (That would increase rebuild times a LOT unless it were carefully protected.)

**Comment by spdomin** [comment]
I support two installations of Trilinos under: Trilinos_nightly_release/ and Trilinos_stable_release/

The former supports a nightly build-and-test process while the later is for stable development for Nalu developers.

If the build fails in the nightly, my Nalu config still "finds" Trilinos_stable_release/ even though I formally requested Trilinos_nightly_release/. Therefore, I end up with false testing.

**Comment by mhoemmen** [comment]
> In short, if I ask for a version of Trilinos in my Nalu config file that does not exist, how do I error out then and there?

Does "does not exist" mean that CMake `FIND_PACKAGE` fails in Nalu?  If so, it sounds like you could test that in Nalu.

**Comment by spdomin** [comment]
Thanks... Will try a few things and report back.

**Comment by spdomin** [comment]
courtesy of @bartlettroscoe:

-find_package(Trilinos REQUIRED)
+find_package(Trilinos NO_MODULE NO_CMAKE_ENVIRONMENT_PATH NO_SYSTEM_ENVIRONMENT_PATH REQUIRED)

Adding the above resolved my issue:

```
[spdomin@ceerws2214 build]$ ./do-configNalu_nightly_release 
find: `./CMakeFiles': No such file or directory
   Trilinos_DIR = /home/spdomin/gitHubWork/scratch_build/install/gcc7.2.0/Trilinos_nightly_release
CMake Error at CMakeLists.txt:21 (find_package):
  Could not find a package configuration file provided by "Trilinos" with any
  of the following names:

    TrilinosConfig.cmake
    trilinos-config.cmake

  Add the installation prefix of "Trilinos" to CMAKE_PREFIX_PATH or set
  "Trilinos_DIR" to a directory containing one of the above files.  If
  "Trilinos" provides a separate development package or SDK, be sure it has
  been installed.


-- Configuring incomplete, errors occurred!

```

**Comment by spdomin** [comment]
Issue resolved... Thanks @mhoemmen and @bartlettroscoe

**Comment by mhoemmen** [comment]
Thanks for posting the solution!
