### ISSUE TITLE
Panzer:  Make Workset::num_cells an int

### ISSUE THREAD

**Issue by jmgate** [trilinos/Trilinos#530]
Need to switch `Workset::num_cells` from a `std::size_t` to an `int` for performance reasons on GPUs.  Need to coordinate this change with Panzer users (e.g. Charon).

**Comment by jmgate** [comment]
From Roger:

Christian has said that there is a 30% hit on GPUs if the loops don’t use integers. I don’t think there is any performance issue on any other node type. Perhaps we should think about making the workset size an int. This would generate warnings for all 400-500, evaluators across our applications that use size_t. With Charon requiring warning free compiling, we would have to coordinate a push to panzer with fixing all of Charon.

**Comment by jmgate** [comment]
From Eric:

It might be good to do a typedef in the Traits (or somewhere) to protect ourselves. Perhaps doing a “typedef int LocalOrdinal".

**Comment by bathmatt** [comment]
I am guessing that 30% hit is for the loop that looks like
for ( i=0..N) ;
and not for a real loop body with real math in it.  It would be good to
clarify this.

**Comment by rppawlo** [comment]
I got that number from one of Christian's emails in this issue:
https://github.com/kokkos/kokkos/issues/28

**Comment by jmgate** [comment]
Looks like I need to put `typedef int LocalOrdinal` in `Workset` instead of `Traits` because `Traits` `#include`s `Workset`.  @eric-c-cyr and @rppawlo, is that cool with you?

**Comment by eric-c-cyr** [comment]
Okay that makes sense. Where is Ordinal64 defined (probably PanzerDiscFe_config.h), maybe we should put it there. The point is to have a place where the local ordinal can change and we are protected with regard to future changes. @rppawlo thoughts?

**Comment by rppawlo** [comment]
Ordinal64 is defined in panzer/packages/cmake/PanzerCore_config.hpp.in so to be consistent, I would add it there. One thing I don not like is the name LocalOrdinal. It's too long of a name if we need to use it in all our loops.

for (LocalOrdinal i=0; i ...

I would rather use something shorter like "index_t" injected into panzer namespace. This is consistent with standard use of size_t.

for (index_t i=0; ...

What do you think? I was actually planning to add this to the phalanx namespace too. For the last few years, we have had this in phalanx but was called an "index_size_type". But again - too long for use in frequently written loops.

**Comment by jmgate** [comment]
Looks like Ordinal64 is defined in `panzer/core/cmake/PanzerCore_config.hpp.in`&mdash;does that sound like a good spot for `LocalOrdinal`?  So we could just do
```cpp
namespace panzer {
#ifdef PANZER_HAVE_LONG_LONG_INT
  typedef long long int Ordinal64;
#else
  #define PANZER_ORDINAL64_IS_INT
  typedef int Ordinal64;
#endif
typedef int LocalOrdinal; // IS THIS WHERE WE WANT THIS?
}
```

**Comment by jmgate** [comment]
Ach, Roger, you beat me to it.  `index_t` sounds fine to me.

**Comment by eric-c-cyr** [comment]
Sounds fine to me as well.

**Comment by jmgate** [comment]
Looks like I got the switch to `index_t` working.  I'll start in on the Charon mods on Monday.

**Comment by jmgate** [comment]
Got the necessary Charon switches in place.  As far as I know, this issue's resolved.
