### ISSUE TITLE
Some of the tests in Trilinos 12.8.1 are timing out at 1500 seconds

### ISSUE THREAD

**Issue by davoodansari** [trilinos/Trilinos#5303]
## Bug Report
Testing issue (CTest)
Tests timeout

### Description
I am not sure if this is actually an issue but some input can really help.
I manged to build Trilinos 12.8.1 on a debain 9 machine with both MPI and openMP enabled.
When I run the tests some items run until they time out at 1500 seconds:

241/471 Test #196: Xpetra_BlockedCrsMatrix_UnitTests_MPI_4 .......................***Timeout 1500.07 sec
280/471 Test #239: Ifpack_Relaxation_MPI_4 .......................................***Timeout 1500.21 sec
314/471 Test #257: Ifpack_Relaxation_LL_MPI_4 ....................................***Timeout 1500.09 sec

The machine has a fairly recent 12 core Xeon processor and 64 GB of RAM.
Is this expected?

**Comment by mhoemmen** [comment]
1. Trilinos 12.8.1 is very old and no longer supported.
2. Best practice is to make sure that `mpiexec` correctly binds processes, and that OpenMP doesn't spawn too many threads.  Try setting `OMP_NUM_THREADS` to some small number as a temporary measure.
