### ISSUE TITLE
MueLu: assess coverage level in unit tests of Kokkos code paths

### ISSUE THREAD

**Issue by jhux2** [trilinos/Trilinos#5306]
This is reminder that the @trilinos/muelu team should assess the level of code coverage of MueLu's Kokkos path in MueLu's regular unit tests.

**Comment by jhux2** [comment]
bump

**Comment by cgcgcg** [comment]
https://testing-dev.sandia.gov/cdash/viewCoverage.php?buildid=4835634&filtercount=1&field1=filename/string&compare1=63&value1=_kokkos&status=6

**Comment by jhux2** [comment]
Nice, thanks!

**Comment by mayrmt** [comment]
See #9743

**Comment by mayrmt** [comment]
Still important. Let's keep open!

**Comment by GrahamBenHarper** [comment]
Since we're finally merging the Kokkos and non-Kokkos routes as part of #11658, should we close this and defer to #9743 instead?

**Comment by jhux2** [comment]
> Since we're finally merging the Kokkos and non-Kokkos routes as part of #11658, should we close this and defer to #9743 instead?

@GrahamBenHarper Yes, that's fine with me.
