### ISSUE TITLE
Tpetra::CrsGraph: Implement 2-arg "copy constructor" like MultiVector's

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#531]
@trilinos/tpetra Give Tpetra::CrsGraph a two-argument "copy constructor" like MultiVector's.  It should take an optional second argument that tells it whether to make a deep copy.

**Comment by kddevin** [comment]
CLosing

**Comment by mhoemmen** [comment]
Clarification: This was only relevant for `Tpetra::MultiVector` during the 2013-5 "Kokkos refactor" effort, when we had to support two Tpetra implementations, only one of which had view semantics (where constructors only shallow copied by default).  We don't need this any more.  We can always add a nonmember function for creating a deep copy; compare to `Kokkos::create_mirror`.
