### ISSUE TITLE
ATDM: Add Intel 18.0.5 compiler environment

### ISSUE THREAD

**Issue by krcb** [trilinos/Trilinos#5316]
## Enhancement

@bartlettroscoe As we discussed via email. Recent EMPIRE testing has revealed various I/O related test failures that occur under Intel 17.0.5. This enhancement adds an Intel 18.0.5 environment that resolves these failures.

**Comment by krcb** [comment]
@bartlettroscoe Ok to close this issue as #5317 is now merged?

**Comment by bartlettroscoe** [comment]
@krcb, it was automerged two days ago.  See [above](https://github.com/trilinos/Trilinos/issues/5316#ref-pullrequest-452245305).  Did you not get that email from GitHub?  Do you have email filters so you don't see this stuff?

**Comment by bartlettroscoe** [comment]
@krcb asked:

> @bartlettroscoe Ok to close this issue as #5317 is now merged?

Since you are the customer I seems best if you close this.  That indicates that you are satisfied it is complete.
