### ISSUE TITLE
STK_Util:  FileUtils.hpp not found

### ISSUE THREAD

**Issue by spdomin** [trilinos/Trilinos#5320]
## Bug Report
@trilinos/stk_Util

Nightly test process for Nalu failed due to missing STK files.

### Description
[  1%] Building CXX object CMakeFiles/nalu.dir/src/Realm.C.o
/Users/naluIt/gitHubWork/nightlyBuildAndTest/Nalu/src/Realm.C:99:10: fatal error: 'stk_util/environment/FileUtils.hpp' file not
      found
#include <stk_util/environment/FileUtils.hpp>

Adding @alanw0 directly

**Comment by alanw0** [comment]
@spdomin Ugh. At least this is different than yesterday, so my changes had some effect... Can you send the configure output again? I suspect that this is a symptom of BoostLib not being enabled. Now that stk is becoming a toolkit, it doesn't require boostlib but rather turns off stuff that needs boostlib if that isn't available. I can tell for sure if you send the config output. If you want to experiment, you can add '-DTPL_ENABLE_BoostLib:BOOL=ON' and see if that fixes it.

**Comment by spdomin** [comment]
Will do. I just opened another ticket - this time due to a search issue not finding a Boost file... Possibly all related.

In my case, I think I do not want Boost on through STK...

**Comment by alanw0** [comment]
@spdomin It looks like you are using 'filename_substitution' in Realm.C (nalu-wind does too), which is the reason you need stk_util/environment/FileUtils.hpp, and that is unfortunately implemented using magic from boost::program_options. It may be premature to remove the mandatory boostlib dependence. What is your preference? I can either put it back as a mandatory dependence, or you can explicitly enable it.

**Comment by spdomin** [comment]
Adding the enable_boost option resulted in a clean build.

Ideally, we are also in the process of removing boost. The above header was only required due to an interface with Catalysts. I am moving forward with a set of ifdefs on NALU_USES_CATALYSTS to ease our transition from boost as well.

**Comment by nmhamster** [comment]
@spdomin - I am seeing this on our Astra builds as well now. The missing FileUtils.hpp is unfortunately more than a missing header file. It then results in a load of missing symbols if the header can be found. I will try to get Boost enabled on the builds too.

**Comment by alanw0** [comment]
@nmhamster specifically it's '-DTPL_ENABLE_BoostLib:BOOL=ON'
Is this another point in favor of me restoring the mandatory dependence until we remove the actual boost usage from the code?

**Comment by spdomin** [comment]
The latest set of pushes to Nalu should resolve this. As @alanw0 notes, adding the ENBALE_BoostLib resolves my Mac and gcc build.

@nmhamster, let me know if you are up and running with the latest push to Nalu. 

https://github.com/NaluCFD/Nalu/commit/2d523218a36f56c324e859723e45faa4bc17e63a

I will wait until I hear back before I close this. However, all nightly Nalu tests are clean now.

**Comment by nmhamster** [comment]
@spdomin - sure let me know. I have NALU-CFD as of yesterday commits building on Astra with the `BoostLib` enabled although I still have to manually modify the library paths for link time.

**Comment by nmhamster** [comment]
@alanw0 - I seem to have made more progress with `BoostLib` defined but the link path for NALU needs modification for library paths. I didn't get compile/link errors though.

**Comment by spdomin** [comment]
I seem to recall having that same problem with Boost that I did with Trilinos the other day. Specifically, when I mis-typed a library path in my Trilinos config, the wrong Boost was being found (silently). Well, not silently since the config text captured the issue.

I am about to remove the Boost usage in Nalu that was causing a required dependency on this header..

**Comment by spdomin** [comment]
Clean nightly build and test.
