### ISSUE TITLE
STK_search File not found

### ISSUE THREAD

**Issue by spdomin** [trilinos/Trilinos#5322]
## Bug Report
@trilinos/stk_search

Another missing file - possibly related to https://github.com/trilinos/Trilinos/issues/5320

Seems like every platform is croaking in a different manner.

Adding @alanw0 

### Description
[ 89%] Building CXX object packages/stk/stk_transfer/stk_transfer/CMakeFiles/stk_transfer_impl.dir/copy_by_id/SearchByIdGeometric.cpp.o
In file included from /scratch/spdomin/nightlyBuildAndTest/Trilinos/packages/stk/stk_search/stk_search/CoarseSearchBoostRTree.hpp:39:0,
                 from /scratch/spdomin/nightlyBuildAndTest/Trilinos/packages/stk/stk_search/stk_search/CoarseSearch.hpp:39,
                 from /scratch/spdomin/nightlyBuildAndTest/Trilinos/packages/stk/stk_transfer/stk_transfer/copy_by_id/SearchByIdGeometric.cpp:37:
/scratch/spdomin/nightlyBuildAndTest/Trilinos/packages/stk/stk_search/stk_search/BoostRTreeInterface.hpp:14:10: fatal error: boost/geometry.hpp: No such file or directory
 #include <boost/geometry.hpp>

**Comment by nmhamster** [comment]
@spdomin - can you post a VERBOSE=1 line so we can see what the Boost includes are? It appears your Boost paths may be incorrect? In the latest Boost I can see the `geometry.hpp` is still there and installed as needed.

**Comment by alanw0** [comment]
It seems as though boost/geometry.hpp is part of the 'BoostLib' portion of boost. This is needed in stk_search, although I thought I had modified stk_search so that it would not try to build the files that depend on boost... Perhaps I'm premature in trying to make the boostlib dependence optional...

**Comment by alanw0** [comment]
Hmm. It seems as though boostlib is optional for stk_search but mandatory for stk_transfer. But stk_transfer depends on stk_search, so I'm afraid boostlib has to go back to mandatory for stk_search until boost can be removed from stk_transfer.

**Comment by spdomin** [comment]
Added enable_boost option resulted in a clean build.

@alanw0, do you know if this global Boost requirement affects other Trilinos products? Would it be better to add something specific to STK, e.g., STK_REQUIRES_BOOST?

**Comment by spdomin** [comment]
- also, you have my blessing to fully remove Boost from STK should you not desire a transition:)

**Comment by mhoemmen** [comment]
> Would it be better to add something specific to STK, e.g., `STK_REQUIRES_BOOST`?

TriBITS' dependency management will handle optional vs. required TPL dependencies correctly, if the package declares them.  The trick for the STK developers is to hunt down optional dependencies that they normally enable as part of their development workflow.

**Comment by spdomin** [comment]
Interesting... I am moving forward with the explicit setting of` -DTPL_ENABLE_BoostLib:BOOL=ON \` to get our nightly testing back up again..

**Comment by alanw0** [comment]
The current TPL_ENABLE_BoostLib seems to work, I don't know what the pros and cons would be for adding a STK_REQUIRES_BOOST. It is our plan to remove boost from stk, but it is a process that will take a while. I was pre-mature in making boostlib optional for stk_search when it's still mandatory for stk_transfer, with stk_transfer needing stk_search.

**Comment by mhoemmen** [comment]
> I don't know what the pros and cons would be for adding a STK_REQUIRES_BOOST.

There's no reason to do that, since TriBITS already has that feature.  The issue is that STK developers had undeclared dependencies on BoostLib.

**Comment by alanw0** [comment]
@mhoemmen tell me if this is correct or not: cmake (or TRIBITS) processes libraries in a certain order as dictated by the list in packages/stk/cmake/Dependencies.cmake. As such, stk_search gets processed before stk_transfer so if stk_search has an optional dependence on BoostLib, and it remains off, but then stk_transfer has a required dependence on both BoostLib and stk_search, tribits activates boostLib. But then errors ensue because stk_transfer references stk_search expecting to find the boost-using pieces of stk_search and they aren't there.

**Comment by spdomin** [comment]
If this is a huge headache, perhaps you should simply deprecate usage of Boost in STK now and then delete its usage once the next release is pushed?

**Comment by alanw0** [comment]
I'm nervous about the side-effects of doing it too quickly. This has already caused you a headache, I don't want the headaches to spread... We'll evaluate the order in which it can be removed from various sub-packages, and try to hit it in an organized fashion. I think I jumped the gun with some of these cmake changes. To limit the current issue I'm considering putting boost back as a required dependency on stk-search, then we'll remove it from stk_transfer, and *then* remove it from stk_search. (With appropriate announcements to folks who might be using the boost search variant etc.) Then the removal from stk_io (FileUtils) will come in a separate step.

**Comment by spdomin** [comment]
I will close all of the active issues once the nightly process is clean. Should be tomorrow barring any new unforeseen changes committed.

**Comment by spdomin** [comment]
Clean nightly build and test.
