### ISSUE TITLE
Tempus: Non-StepperExplicitRKObservers passed to StepperERK::setObservers cause an exception

### ISSUE THREAD

**Issue by krcb** [trilinos/Trilinos#5323]
## Bug Report
@trilinos/tempus 

### Description

PR #5282 added composite stepper observers for the ERK stepper. The ERK stepper setObserver method accepts a StepperObserver and casts this to a StepperExplicitRKObserver. If a user passes in a StepperObserver that isn't  StepperExplicitRKObserver, this cast fails and an exception is thrown. However, passing in a non-StepperExplicitRKObserver is an important use case which needs to be handled.

**Comment by sconde** [comment]
You want to pass in a non-ERK observer to an ERK stepper?

**Comment by krcb** [comment]
Yes. This turns out to be an important use case. The ERK stepper actually uses this in the takeStep method.

**Comment by rppawlo** [comment]
We could add a boolean to the observer registration that toggles a throw if the internal cast fails. The default would be to throw and empire can set it to not throw.

**Comment by ccober6** [comment]
I know I am coming late to this (been on vacation), but I had a question on this.  Other Tempus StepperObservers are just StepperObservers and not composite observers.  This allows "single" observers to be used, and composites be built and set on the Stepper.  It appears that this requires a CompositeObserver even if you just have a "single" observer.  Which design path do folks prefer?

**Comment by sconde** [comment]
I prefer the composite observer approach. An application can get the observer, clear it, and re-insert the observers in the order they want. This is what is done with the integrator observer.

Also, I was thinking of combining the ERK, DIRK, and IMEX RK stepper observers into a MSRK (multi stage RK) observer. The before/after solver for ERK can be a no-op. What do you think?

**Comment by ccober6** [comment]
I am on the fence.  Going with a "single" observer is a little easier for new users, but as you say they get composite features out of the box.  So if we go with composite approach, let's be consistent in both integrator and stepper, e.g., setCompositeObserver - set/replace composite observer; addObserver - add observer to composite observer.  Thoughts?

**Comment by ccober6** [comment]
For the MSRK, can we just add the before/after solver observer to the base StepperObserver and use no-op for all explicit steppers?

**Comment by sconde** [comment]
> let's be consistent in both integrator and stepper, e.g., setCompositeObserver - set/replace composite observer; addObserver - add observer to composite observer

I think this is a great idea. Makes it clear.


> For the MSRK, can we just add the before/after solver observer to the base StepperObserver and use no-op for all explicit steppers?

Ok. This will change the other stepper observers as well.

**Comment by ccober6** [comment]
> Ok. This will change the other stepper observers as well.
Yeah, but again let's make it consistent across the Steppers.

**Comment by krcb** [comment]
We should make a follow-up issue to deal with the refactor/redesign. Can we make sure that https://github.com/trilinos/Trilinos/pull/5324 is merged as this is needed to fix EMPIRE.

**Comment by ccober6** [comment]
Sounds good.  Go ahead and put in the what is needed for EMPIRE, and make an issue for the redesign and note that non-backward compatibility changes are required for EMPIRE.   Hope you understand the need to keep these types of things up to date, otherwise the mess gets worse.  :)

**Comment by krcb** [comment]
I think @sconde already has a follow-up issue in place. Part of the issue here is how the StepperERK interacts with the stepper observers, which appears to be different that the other steppers. In addition, there are data flow patterns that need to be carefully considered. So, this might be a much bigger issue. In any case, we will find out tomorrow whether the changes here fix the issues in EMPIRE, at which point I will close this out.
