### ISSUE TITLE
Update HTS in KokkosKernels to most recent version

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#534]
Right now, @ambrad says ShyLU has the most recent version of HTS.  This needs to remain the case for Various Reasons.  However, we could also make sure that this version gets copied into KokkosKernels.  Right now, KokkosKernels has an earlier version of HTS.

**Comment by mhoemmen** [comment]
We also have to make sure that the version of HTS in KokkosKernels does not conflict (e.g., use the same namespace as) the version of HTS in ShyLU.

**Comment by ambrad** [comment]
This was resolved several months ago. HTS is a subpackage of ShyLU and is used as such in, e.g., Ifpack2.
