### ISSUE TITLE
Xpetra: build error on Intel 17

### ISSUE THREAD

**Issue by spdomin** [trilinos/Trilinos#5340]
## Bug Report
@trilinos/xpetra 

In my latest pull from Trilinos/develop, I am seeing the following error in XPetra.

[ 40%] Building CXX object packages/xpetra/src/CMakeFiles/xpetra.dir/Utils/ExplicitInstantiation/Xpetra_TpetraExport.cpp.o
In file included from /projects/netpub/nalu/scratch_build/packages/Trilinos/build_stable_release/packages/xpetra/src/Utils/ExplicitInstantiation/Xpetra_TpetraExport.cpp(55):
/projects/netpub/nalu/scratch_build/packages/Trilinos/packages/xpetra/src/Export/Xpetra_TpetraExport_def.hpp(500): error: "export_" is not a nonstatic data member or base class of class "Xpetra::TpetraExport<int, long long, Xpetra::EpetraNode>"
      TpetraExport(const RCP<const Tpetra::Export<LocalOrdinal, GlobalOrdinal, Node>>& exp) : export_(exp)
                                                                                              ^

compilation aborted for /projects/netpub/nalu/scratch_build/packages/Trilinos/build_stable_release/packages/xpetra/src/Utils/ExplicitInstantiation/Xpetra_TpetraExport.cpp (code 2)
make[2]: *** [packages/xpetra/src/CMakeFiles/xpetra.dir/Utils/ExplicitInstantiation/Xpetra_TpetraExport.cpp.o] Error 2
make[1]: *** [packages/xpetra/src/CMakeFiles/xpetra.dir/all] Error 2
make: *** [all] Error 2

`cmake \
-DCMAKE_INSTALL_PREFIX=$trilinos_install_dir \
-DTrilinos_ENABLE_CXX11=ON \
-DTrilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON \
-DTpetra_INST_DOUBLE:BOOL=ON \
-DTpetra_INST_INT_LONG:BOOL=ON \
-DTpetra_INST_INT_LONG_LONG:BOOL=OFF \
-DTpetra_INST_COMPLEX_DOUBLE=OFF \
-DTrilinos_ENABLE_TESTS:BOOL=OFF \
-DTrilinos_ENABLE_ALL_OPTIONAL_PACKAGES=OFF \
-DTrilinos_ALLOW_NO_PACKAGES:BOOL=OFF \
-DTPL_ENABLE_MPI=ON \
  -DMPI_BASE_DIR:PATH=$mpi_base_dir \
-DTPL_ENABLE_SuperLU=ON \
  -DSuperLU_INCLUDE_DIRS:PATH=$superlu_inc_dir \
  -DSuperLU_LIBRARY_DIRS:PATH=$superlu_lib_dir \
-DTrilinos_ENABLE_Epetra:BOOL=ON \
-DTrilinos_ENABLE_Tpetra:BOOL=ON \
-DTrilinos_ENABLE_ML:BOOL=ON \
-DTrilinos_ENABLE_MueLu:BOOL=ON \
-DTrilinos_ENABLE_EpetraExt:BOOL=ON \
-DTrilinos_ENABLE_AztecOO:BOOL=ON \
-DTrilinos_ENABLE_Belos:BOOL=ON \
-DTrilinos_ENABLE_Ifpack2:BOOL=ON \
-DTrilinos_ENABLE_Amesos2:BOOL=ON \
-DTrilinos_ENABLE_Zoltan2:BOOL=ON \
-DTrilinos_ENABLE_Ifpack:BOOL=ON \
-DTrilinos_ENABLE_Amesos:BOOL=ON \
-DTrilinos_ENABLE_Zoltan:BOOL=ON \
-DTrilinos_ENABLE_STKMesh:BOOL=ON \
-DTrilinos_ENABLE_STKSimd:BOOL=ON \
-DTrilinos_ENABLE_STKIO:BOOL=ON \
-DTrilinos_ENABLE_STKTransfer:BOOL=ON \
-DTrilinos_ENABLE_STKSearch:BOOL=ON \
-DTrilinos_ENABLE_STKUtil:BOOL=ON \
-DTrilinos_ENABLE_STKTopology:BOOL=ON \
-DTrilinos_ENABLE_STKBalance:BOOL=OFF \
-DTPL_ENABLE_BoostLib:BOOL=ON \
-DTrilinos_ENABLE_STKUnit_tests:BOOL=OFF \
-DTrilinos_ENABLE_STKUnit_test_utils:BOOL=OFF \
-DTrilinos_ENABLE_Gtest:BOOL=ON \
-DTrilinos_ENABLE_SEACASExodus:BOOL=ON \
-DTrilinos_ENABLE_SEACASEpu:BOOL=OFF \
-DTrilinos_ENABLE_SEACASExodiff:BOOL=ON \
-DTrilinos_ENABLE_SEACASNemspread:BOOL=ON \
-DTrilinos_ENABLE_SEACASNemslice:BOOL=ON \
-DTrilinos_ENABLE_SEACASIoss:BOOL=ON \
  -DTPL_ENABLE_Netcdf:STRING=ON \
  -DTPL_Netcdf_LIBRARIES:PATH="${netcdf_install_dir}/lib/libnetcdf.a;${pnetcdf_install_dir}/lib/libpnet
cdf.a;${hdf_install_dir}/lib/libhdf5_hl.a;${hdf_install_dir}/lib/libhdf5.a;${z_install_dir}/lib/libz.a"
 \
  -DNetcdf_INCLUDE_DIRS:PATH="${netcdf_install_dir}/include;${pnetcdf_install_dir}/include" \
  -DNetcdf_LIBRARY_DIRS:PATH="${netcdf_install_dir}/lib;${pnetcdf_install_dir}/lib" \
  -DTPL_ENABLE_HDF5:STRING=ON \
  -DHDF5_INCLUDE_DIRS:PATH="${hdf_install_dir}/include" \
  -DTPL_HDF5_LIBRARIES:PATH="${hdf_install_dir}/lib/libhdf5_hl.a;${hdf_install_dir}/lib/libhdf5.a;${z_i
nstall_dir}/lib/libz.a" \
  -DTPL_ENABLE_Zlib:STRING=ON \
  -DZlib_INCLUDE_DIRS:PATH="${z_install_dir}/include" \
  -DTPL_Zlib_LIBRARIES:PATH="${z_install_dir}/lib/libz.a" \
  -DTPL_Netcdf_Enables_Netcdf4:BOOL=TRUE \
  -DTPL_Netcdf_PARALLEL:BOOL=ON \
-DBoostLib_INCLUDE_DIRS:PATH="$boost_dir/include" \
-DBoostLib_LIBRARY_DIRS:PATH="$boost_dir/lib" \
-DTrilinos_ASSERT_MISSING_PACKAGES=OFF \
$EXTRA_ARGS \
../
`

**Comment by jhux2** [comment]
@william76 Could this be related to your recent ETI work for Xpetra::TpetraExport?

**Comment by jhux2** [comment]
@trilinos/xpetra

**Comment by spdomin** [comment]
Sadly, I do not have nightly testing on intel/17.0.0.098 and can not provide a last "good" build (well, beyond the last time I built Trilinos on Eclipse was in November).

**Comment by jhux2** [comment]
@spdomin I think this is due to a very recent change in Xpetra's ETI system.  Would you post your cmake configure line?

**Comment by spdomin** [comment]
@jhux2. Are you asking for the full configure output? Otherwise, the config line with all of the options I have active is above (first post).

I noticed that this current config set has a lot of stuff I actually do not need, e.g., Epetra, ML, etc... As such, I am testing with a pruned version now. However, I am sure that someone might want the above set of options (for codes supporting both E and Tpetra).

**Comment by jhux2** [comment]
@spdomin I missed that you already posted your configure line.  It's been a long day ....

**Comment by william76** [comment]
@jhux2 It could be... I'll have to check.  I didn't get any errors in my testing though.

@spdomin can you tell me if this is just on a standard RHEL machine or is it something different?  Are there any modules you're loading in your environment like a specific compiler, mpi version, TPLs, etc. ?

**Comment by spdomin** [comment]
The modules are as follows:

  1) sntools/master      5) mkl/17.0.0.098                 9) sierra-mpi/openmpi/1.10
  2) sierra-python/2.7   6) sierra-mkl/17.0.0             10) sierra-devel/intel-17.0.0-openmpi-1.10
  3) sierra-git/2.6.1    7) sierra-compiler/intel/17.0.0  11) cmake/3.11.1
  4) intel/17.0.0.098    8) openmpi-intel/1.10            12) seacas

Also, when I pruned all of the extra Epetra/ML/Amesos/EpetraExt, the build was successful.

I am willing to close this from the perspective of my immediate needs. However, my guess is that Sierra needs the above (although they may have bumped up to intel 19)..

**Comment by jhux2** [comment]
@spdomin Let's keep this open, it's still a bug.

**Comment by jhux2** [comment]
@william76 This failure was on the Eclipse cluster, but my bet is it's reproducible on the CEE lan.

**Comment by vbrunini** [comment]
As @spdomin suspected this showed up in the Sierra nightly building against Trilinos/master last night. Happened with all of gcc-7.2, intel-17.0, and intel 19.0.3.

**Comment by william76** [comment]
@jhux2 I don't really have any machines I use on the CEELan... I have a RHEL7 machine with the SEMS modules on it but it looks like SuperLU isn't loading with gcc 7.2 ... I'll see if I can replicate this without it...

@spdomin @vbrunini is there a dashboard link to the output of the nightlies that you could link here or send to me via email?

**Comment by william76** [comment]
Working on reproducing this... I have a RHEL7 machine with SEMS modules I'll try on first.  I'll see if I can get it replicated using GCC 7.2 since the compile times are way shorter with that than on Intel ;).  

@vbrunini if you could send me a configure + module list for the GCC 7.2 build for me to try and see if I can use?

Also, early in the week is usually heavily chopped up with meetings for me, so most likely I won't have a lot of time available to look at it until Tues or Wednesday.

**Comment by spdomin** [comment]
I do not test nightly for Intel 17 - sorry. However, gcc 7.2 and clang 9.0 are also clean.

**Comment by vbrunini** [comment]
I don't have a SEMS machine, so no module list. Configure is the same as in https://github.com/trilinos/Trilinos/issues/5148#issue-442437174

**Comment by lucbv** [comment]
@william76 the same error can be found in [this](https://testing.sandia.gov/cdash/index.php?project=Trilinos&parentid=5158567) nightly build, see the Xpetra error.
I am not sure what modules are being used for this nightly but it looks like:
sems-cmake/3.12.2
sems-gcc/7.3.0
sems-openmpi/1.10.1

there is no superlu required.

**Comment by william76** [comment]
FYI @spdomin @lucbv @vbrunini, The configure being used in the nightly that @lucbv mentioned above sets `-DTpetra_HIDE_DEPRECATED_CODE:BOOL=ON` but this is not the flag that controls whether or not Tpetra is disabling deprecated code.  The `<package>_HIDE_DEPRECATED_CODE` flags are set up automagically by TriBiTS, but I don't think Tpetra uses that one... it uses `Tpetra_ENABLE_DEPRECATED_CODE` instead... so to turn off deprecated code, you'd want to use `-DTpetra_ENABLE_DEPRECATED_CODE:BOOL=OFF` if you want to cut out deprecated code...  @kddevin we just went through this recently on the Tpetra side, please correct me if I'm mistaken...

**Comment by william76** [comment]
@lucbv I have replicated the configure line as close as I can get it.  I can't pull in the Sierra specific stuff... but I'm getting configuration errors for RHEL7 complaining about not finding all the parts of NetCDF.  I noticed the CDash build you linked to me is running on a RHEL6 machine.  I don't currently have a RHEL6 machine that I use, do you know of any that can be logged into that have the SEMS modules?

I can look more at this and start turning off things like NetCDF, etc. but so far when I try that I have been unable to replicate the issue... :(

**Comment by william76** [comment]
I'm able to replicate it now... will start working on a fix.

**Comment by william76** [comment]
@spdomin I have a PR in which should fix this... the auto-tester is already working on it so assuming all goes well and it automerges, it should be fixed in time for tonight's nightly builds.

**Comment by william76** [comment]
@spdomin @vbrunini 
It got merged in last night but it may or may not have gotten in prior to your nightly run.  When you get a chance, can you check and let me know if that issue got fixed?

**Comment by spdomin** [comment]
My Intel 17 with the original (extra) packages is now building with the latest changes above.
