### ISSUE TITLE
Add option to turn off the install of gtest header and lib even if Gtest package is enabled

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#5341]
CC: @bathmatt, @jmgate, @fryeguy52 

## Description

The EMPIRE configuration of Trilinos currently sets:

```
  -D TPL_ENABLE_gtest=OFF \
  -D Trilinos_ENABLE_Gtest=OFF \
```

That is so that gtest headers and lib don't get installed which then screws up the versions of gtest that EMPIRE wants to use?

This is not good because this will disable a bunch of Trilinos tests that depend on the Gtest package.  We would like to be able to build and tests EMPIRE against at build of Trilinos that enables all tests and we can't do that if you need to set `Trilinos_ENABLE_Gtest=OFF`.

## Proposed solution

One possible solution is to add an option like `Gtest_SKIP_INSTALL` that defaults to `FALSE` but can be set to `TRUE` and then gtest headers and lib will not be installed along with Trilinos.

**Comment by jmgate** [comment]
Your proposed solution sounds fine to me.  I think @bathmatt inserted this because of problems with SPIN, or perhaps EPIXS, though I may be mistaken there.

**Comment by bartlettroscoe** [comment]
CC: @jmgate, @bathmatt, @alanw0 

Hum, this is a little harder than it should be.  Looks like some STK subpackages actually have **library** dependencies on the Gtest package as shown by:

```
$ find packages/ -name Dependencies.cmake -exec grep -nH Gtest {} \; | grep LIB
packages/shylu/shylu_node/tacho/cmake/Dependencies.cmake:2:SET(LIB_OPTIONAL_DEP_PACKAGES TrilinosSS Gtest)
packages/stk/stk_ngp_test/cmake/Dependencies.cmake:1:SET(LIB_REQUIRED_DEP_PACKAGES Kokkos KokkosCore Gtest)
packages/stk/stk_exp/cmake/Dependencies.cmake:1:SET(LIB_REQUIRED_DEP_PACKAGES Gtest Shards STKTopology STKUtil STKMesh)
packages/stk/stk_unit_test_utils/cmake/Dependencies.cmake:1:SET(LIB_REQUIRED_DEP_PACKAGES Gtest)
packages/stk/stk_doc_tests/cmake/Dependencies.cmake:1:SET(LIB_REQUIRED_DEP_PACKAGES Gtest)
packages/stk/stk_unit_tests/cmake/Dependencies.cmake:1:SET(LIB_REQUIRED_DEP_PACKAGES Gtest)
```

That is not good and that was not the intent of the Gtest package in Trilinos (since it would confict with downstream customers' usage of gtest).

 Therefore, when you remove the install targets for the Gtest library, you get STK configure errors like:

```
CMake Error: INSTALL(EXPORT) given unknown export "Gtest"                                                                                                                           
CMake Error: install(EXPORT "STKNGP_TEST" ...) includes target "stk_ngp_test" which requires target "gtest" that is not in the export set.                                          
CMake Error: install(EXPORT "STKUnit_test_utils" ...) includes target "stk_unit_test_utils" which requires target "gtest" that is not in the export set.                   
```

So we will need to not install all of those as well based on Gtest not installing.

But the good news is that we know that EMPIRE works with Gtest disabled and therefore these downstsream STK packages are not needed by EMPIRE.

**Comment by alanw0** [comment]
The stk_ngp_test sub-package was written by the sierra/sm folks (I'm not sure they have GitHub ids). It is intended to help with writing tests that run on gpu. i.e., the EXPECT-like statements can run on gpu. It is indeed a library that depends on gtest, but it would only be used by unit-tests. Does that mean that the 'LIB_REQUIRED_*' dependencies are right or wrong?

**Comment by bartlettroscoe** [comment]
@alanw0 asked:

> Does that mean that the 'LIB_REQUIRED_*' dependencies are right or wrong?

I suspect that these should really be `TESTONLY` libraries and the 'Gtest' package should only be listed as a TEST dependency in the `Dependencies.cmake` files and all libraries that depend on Gtest should be marked as `TESTONLY`.  (That will result in none of these libraries being installed.)  I think in general we don't want to be installing gtest from Trilinos since there is a high probability that it will conflict with downstream customers that are using their own version of gtset (which is what is happening with EMPIRE).

For now I think I can just disable gtest, see what STK subpackages that takes out, and then disable all of those STK subpackages in all of the ATDM Trilinos builds.  We know this works for EMPIRE and I will test if this works for SPARC as well.  (If it does not work for SPARC, then we will need to address this problem the correct way.)

**Comment by alanw0** [comment]
@bartlettroscoe  ok, let me know what that reveals. If it appears to be disabling more stk packages than it should, I may need to re-visit our cmake files and figure out what's wrong. Basically I think it should only disable stk_unit_tests, stk_doc_tests, and stk_ngp_test.

**Comment by bartlettroscoe** [comment]
@alanw0 said:

>  Basically I think it should only disable stk_unit_tests, stk_doc_tests, and stk_ngp_test.

Let me know if you need any help or advice with this.   I think disabling the Gtest package is a good check to make sure that only right things get disabled.

I will push a PR branch soon that has a couple of little tweaks to STK CMake files I saw (but does not really fix this problem).

**Comment by bartlettroscoe** [comment]
NOTE: We don't want to complete turn off the Gtest package because it is used in testing for ROL:

```
packages/rol/cmake/Dependencies.cmake:9:SET(TEST_OPTIONAL_DEP_PACKAGES Gtest)
```

So I will try as hard as I can to get as much testing to build as I can with Gtest enabled and still satisfy the needs of SPARC and EMPIRE (and therefore hopefully GEMMA too).

**Comment by bartlettroscoe** [comment]
Okay, we have a problem.  The problem is that SPARC can't build its test suite without gtest installed from Trilinos :-(

What needs to happen is that we need to copy gtest into SPARC so that it has its own copy of gtest and then stop asking for Gtest from TrilinosConfig.cmake.  I will write a SPARC JIRA issue for that.

FYI: The whole purpose for this exercise is to make the identical install of Trilinos using the standard ATDM Trilinos configuratioin work for SPARC and EMPIRE.  Otherwise, the standard ATDM Trilinos configuration will be more serving SPARC or EMPIRE (and it has to be SPARC for SPARC Trilinos Integration testing and upgrades).

**Comment by bartlettroscoe** [comment]
FYI: I created [SPAR-614](https://sems-atlassian-srn.sandia.gov/browse/SPAR-614) to get SPARC to use its own version of gtest.

**Comment by bartlettroscoe** [comment]
This has been done for a long time and both EMPIRE and SPARC have had several updates of Trilinos since then.  If there was a problem related this, I would have heard about it.

Closing as complete.

**Comment by bartlettroscoe** [comment]
Closing as complete
