### ISSUE TITLE
python executable

### ISSUE THREAD

**Issue by VictorEijkhout** [trilinos/Trilinos#5342]
What is the cmake flag for the name of the python executable?

Background: at TACC we now have executables python2 and python3 for obvious reasons. Unfortunately, "python" is still an executable that we inherit from the unix distribution, and we can not throw it away because system stuff depends on it.

Anyway, trilinos picks up on the system python, but I want it to pick up my explicitly specified executable.

**Comment by VictorEijkhout** [comment]
Btw, would it be an idea for you guys to publish a list of all cmake options?

**Comment by mhoemmen** [comment]
@trilinos/framework

**Comment by prwolfe** [comment]
I use

> set(PYTHON_EXECUTABLE /path/to/python CACHE FILEPATH  "Some comment I will recognize")

Which has allowed me to set up both python 2 and 3 testing
