### ISSUE TITLE
Amesos2: Compiler error when linked with SuiteSparse and all packages are enabled

### ISSUE THREAD

**Issue by wortiz** [trilinos/Trilinos#5345]
## Bug Report
@trilinos/amesos2

### Description
TPLS etc:
gcc 9.1 + openmpi 4.0.1 and gcc 8.2 + openmpi 3.1.3
SuiteSparse 5.4.0
Boost 1.70.0
netlib blas/lapack

When configuring Trilinos with:

    -DTrilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=ON \
    -DTrilinos_ENABLE_ALL_PACKAGES:BOOL=ON \
    -DTPL_ENABLE_UMFPACK:BOOL=ON \

I get the following compiler error for amesos2:

    In file included from /opt/toolchain/gcc-9.1.0/modules/suitesparse-5.4.0/include/umfpack.h:29,
                     from /home/wortiz/Downloads/trilinos/packages/amesos2/src/Amesos2_Umfpack_FunctionMap.hpp:56,
                     from /home/wortiz/Downloads/trilinos/packages/amesos2/src/Amesos2_Umfpack_decl.hpp:49,
                     from /home/wortiz/Downloads/trilinos/packages/amesos2/src/Amesos2_Umfpack.hpp:47,
                     from /home/wortiz/Downloads/trilinos/packages/amesos2/src/Amesos2_Factory.hpp:116,
                     from /home/wortiz/Downloads/trilinos/packages/amesos2/src/Amesos2_Details_LinearSolverFactory_def.hpp:52,
                     from /home/wortiz/Downloads/trilinos/packages/amesos2/src/Amesos2_Details_LinearSolverFactory.hpp:49,
                     from /home/wortiz/Downloads/trilinos/packages/amesos2/src/Amesos2_Details_registerLinearSolverFactory.cpp:45:
    /opt/toolchain/gcc-9.1.0/modules/suitesparse-5.4.0/include/SuiteSparse_config.h:62:26: error: declaration does not declare anything [-fpermissive]
       62 | #define SuiteSparse_long long
          |                          ^~~~
    /opt/toolchain/gcc-9.1.0/modules/suitesparse-5.4.0/include/SuiteSparse_config.h:62:26: note: in definition of macro ‘SuiteSparse_long’
       62 | #define SuiteSparse_long long
          |                          ^~~~
    
However if I only enable a few packages and enable amesos2 I do not get that error and Trilinos builds fine.

### Steps to Reproduce
1. SHA1:  c0d5961d4dde88
2. Broken Configure script: 
[configure-trilinos-broken.txt](https://github.com/trilinos/Trilinos/files/3266271/configure-trilinos-broken.txt)

3. Working Configure script:
[configure-trilinos-working.txt](https://github.com/trilinos/Trilinos/files/3266272/configure-trilinos-working.txt)

**Comment by jhux2** [comment]
@trilinos/amesos2

**Comment by srajama1** [comment]
Strange error. Why would long be not recognized ? Why would it work if only some packages are enabled. Are you sure this is not a transient error due to some CMake Cache etc ?

**Comment by wortiz** [comment]
It doesn't appear to be any cmake cache issue tried again with this


    TMPDIR=$(mktemp -d)

    echo $TMPDIR
    cd $TMPDIR
    git clone --depth=1 https://github.com/trilinos/trilinos
    COMMIT=$(git rev-parse --short HEAD)
    echo $COMMIT

    mkdir build
    cd build

    cmake ../trilinos \
    -DTPL_ENABLE_MPI:BOOL=ON \
    -DCMAKE_C_COMPILER=mpicc \
    -DCMAKE_CXX_COMPILER=mpicxx \
    -DCMAKE_Fortran_COMPILER=mpifort \
    -DMPI_BASE_DIR:PATH=$MPI_HOME \
    -DTrilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=ON \
    -DTrilinos_ENABLE_ALL_PACKAGES:BOOL=ON \
    -DTPL_ENABLE_UMFPACK:BOOL=ON \
    -DUMFPACK_LIBRARY_DIRS:PATH=$SUITESPARSE_HOME/lib \
    -DUMFPACK_INCLUDE_DIRS:PATH=$SUITESPARSE_HOME/include \
    -DUMFPACK_LIBRARY_NAMES="umfpack;amd;colamd;cholmod;suitesparseconfig" \
    -DTPL_ENABLE_BLAS=ON \
    -DTPL_BLAS_LIBRARIES="$BLAS_HOME/lib/libblas.so" \
    -DTPL_ENABLE_LAPACK=ON \
    -DTPL_ENABLE_Boost:BOOL=ON \
    -DTPL_ENABLE_Netcdf=OFF \
    -DTrilinos_ENABLE_PyTrilinos:BOOL=OFF \
    -DTPL_LAPACK_LIBRARIES="$LAPACK_HOME/lib/liblapack.so" \
    -DBoostLib_INCLUDE_DIRS:PATH=$BOOST_HOME/include \
    -DBoostLib_LIBRARY_DIRS:PATH=$BOOST_HOME/lib \
    -DBoost_INCLUDE_DIRS:PATH=$BOOST_HOME/include \
    -DBoost_LIBRARY_DIRS:PATH=$BOOST_HOME/lib

    make -j24

Maybe some weird interaction with one of the `typedef UF_long SuiteSparse_long;` in the code

**Comment by srajama1** [comment]
Ah, you are using your own suitesparse and Trilinos has older versions with UF_long. That typedef is for compatibility with older codes, but may be that gets confused. The odd thing is all packages I would expect to use a direct solver are all in "fewer packages" configure file as well. I would recommend enabling the packages only you need anyway.

**Comment by wortiz** [comment]
Here is a patch that allows building with suitesparse
[suitesparse.patch.txt](https://github.com/trilinos/Trilinos/files/3281388/suitesparse.patch.txt)

**Comment by srajama1** [comment]
@kyungjoo-kim : Can you check and apply this patch for Tacho please ?

**Comment by kyungjoo-kim** [comment]
I do not think that this is a right solution even if it works. Tacho uses the trilinos version of CAMD and the trilinos suite sparse has separate prefix with those definitions to insulate the code from TPL suitesparse. Putting the typedef of external suitesparse definitions in Tacho is not right.

**Comment by wortiz** [comment]
Maybe Tacho could be using `UF_long` instead of `SuiteSparse_long` and avoid the pollution issue since it appears to cause conflicts with amesos2 and SuiteSparse_long doesn't seem to be used for trilinos suitesparse anywhere else

Or maybe try segregating that typedef to only Tacho because it looks like it gets pulled in from "Tacho.hpp" in "Amesos2_Factory.hpp" which also pulls in "umfpack.h"

**Comment by wortiz** [comment]
@srajama1 @kyungjoo-kim Here is a small configure script that exhibits this behavior, only Amesos2/Tpetra Explicitly enabled, only TPLS blas, lapack, umfpack

[small_trilinos_configure_script.txt](https://github.com/trilinos/Trilinos/files/3585653/small_trilinos_configure_script.txt)
