### ISSUE TITLE
TrilinosBuildReference.html no longer getting rebuilt automatically?

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#5357]
@trilinos/framework 

It looks like the document:

* https://trilinos.org/docs/files/TrilinosBuildReference.html

may not be getting rebuilt automatically anymore.  The PR #5352 merged on 6/8/2019 (two days ago) does not show the new section "Installation Testing" shown in:

* https://tribits.org/doc/TribitsBuildReference.html#installation-testing

**Comment by prwolfe** [comment]
Did someone already look at this? I see the section this morning when I go to the URL given. Is this a timing/trigger question possibly?

**Comment by bartlettroscoe** [comment]
> I see the section this morning when I go to the URL given. Is this a timing/trigger question possibly?

I see it now:

* https://trilinos.org/docs/files/TrilinosBuildReference.html#installation-testing

When I looked yesterday, it was not there even though the PR that added this section got merged more than 24 hours before I looked.  So if it is a timing issue, it must run less than each 24 hours.

**Comment by jjellio** [comment]
This is really bad. This build reference use to be the top google hit for trilinos + build.  Now, it no longer shows up because the file is gone.

`
https://docs.trilinos.org/files/TrilinosBuildReference.html
`

**Comment by jjellio** [comment]
Mention #6601

**Comment by bartlettroscoe** [comment]
Looks like someone finally fixed this:

* https://docs.trilinos.org/files/TrilinosBuildReference.html

Closing as complete.
