### ISSUE TITLE
Tpetra: Cuda warnings about local scoped vars in lambdas

### ISSUE THREAD

**Issue by bathmatt** [trilinos/Trilinos#5359]
## Bug Report
@trilinos/tpetra 
@mhoemmen @nmhamster 

### Description
What went wrong?  What should have happened?  Do you have an idea what might
fix things?  How has this bug affected you?  What are you trying to accomplish?
What specifically must we demonstrate to call this work complete?

I'm seeing a lot (140) of warnings in tpetra like this

/home/mbetten/Trilinos/Trilinos/packages/tpetra/core/src/Tpetra_Details_unpackCrsMatrixAndCombine_def.hpp(844): warning: calling a __host__ function("std::__cxx11::basic_string<char,     ::std::char_traits<char> , ::std::allocator<char> > ::~basic_string") from a __host__ __device__ function("") is not allowed

If you dig it looks like it is bringing a local scoped var into the lambda that isn't used.  Thinks like this will warn on the string

```
  func() {
       string a;
          int i;
       parallel_for(1, KOKKOS_LAMBDA () { x=i;});

```

only see this on cuda-10.1 and not 9.2

### Steps to Reproduce
1. SHA1:  [insert here]
1. Configure script:  [attach here]
1. Configure log:  [attach here]
1. Build log:  [attach here]
1. Input deck:  [attach here]
1. Do this.
1. Do that.
1. Shake fist angrily at computer.
1. Run log:  [attach here]

**Comment by mhoemmen** [comment]
Thanks @bathmatt !  I'm hoping that nvcc isn't actually pulling in those variables.  I can think of two possible work-arounds:

1. Replace the lambda with a functor.
2. Instead of using `KOKKOS_LAMBDA`, add a macro just for the `__host__ __device__` part of the lambda signature, and write the lambda's capture clause explicitly.

**Comment by bathmatt** [comment]
I guess I don't understand the second option, can you list vars to capture?

**Comment by mhoemmen** [comment]
@bathmatt wrote:
> can you list vars to capture?

Yes.  The `KOKKOS_LAMBDA` macro just captures by value anything that the lambda uses (`[=]`).
