### ISSUE TITLE
Documentation Bug for ATDM EMPIRE Build in Wiki

### ISSUE THREAD

**Issue by nmhamster** [trilinos/Trilinos#5378]
@bartlettroscoe - I think there is a documentation bug in the Wiki for EMPIRE builds (ATDM).

We have:

```
cmake \
  -GNinja \
  -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake,cmake/std/atdm/apps/empire/EMPIRETrilinosPackagesEnables.cmake \
  -DCMAKE_INSTALL_PREFIX=<trilinos-install-dir> \
```

But `cmake/std/atdm/apps/empire/EMPIRETrilinosPackagesEnables.cmake` does not exist in my latest checkout (is this now `EMPIRETrilinosEnables.cmake`?

**Comment by bartlettroscoe** [comment]
@nmhamster,

A few days ago updated and moved that info and fixed that issue.  See the updated info at:

* https://snl-wiki.sandia.gov/display/CoodinatedDevOpsATDM/Building+and+Testing+EMPIRE+against+Trilinos#BuildingandTestingEMPIREagainstTrilinos-RawbuildandinstallofTrilinosandtestingEMPIRE

It currently says:

```
$ cmake \
 -GNinja \
 -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake,cmake/std/atdm/apps/empire/EMPIRETrilinosEnables.cmake \
 -DCMAKE_INSTALL_PREFIX=<trilinos-install-dir> \
 <trilinos-src-dir>
```

which I think is correct.

What wiki site are you looking at?

Also, please checkout the new high-level drivers that I created for testing EMPIRE with Trilinos described at:

* https://snl-wiki.sandia.gov/display/CoodinatedDevOpsATDM/Building+and+Testing+EMPIRE+against+Trilinos#BuildingandTestingEMPIREagainstTrilinos-Buildandtestusingempire-tril-build-test-scripts

Makes building and testing EMPIRE against local builds of Trilinos super easy (1 command after cloning the repos).

Also note the script I created for cloning the EMPIRE repos documented at:

* https://snl-wiki.sandia.gov/display/CoodinatedDevOpsATDM/Building+and+Testing+EMPIRE+against+Trilinos#BuildingandTestingEMPIREagainstTrilinos-CloningEMPIREGitRepos

But I need to merge the PR #4683 to fix some things with `EMPIRETrilinosEnables.cmake` but it might work as is.

**Comment by nmhamster** [comment]
@bartlettroscoe - current page I am looking at is here (Trilinos Wiki on Github): `https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md`

**Comment by bartlettroscoe** [comment]
@nmhamster said:

> current page I am looking at is here (Trilinos Wiki on Github):
> 
> https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md

Shoot.  I forgot about that.  I need to gut that and just point to the internal wiki page:

* https://snl-wiki.sandia.gov/display/CoodinatedDevOpsATDM/Building+ATDM+APPs+against+Trilinos

Don't know what I was thinking duplicating this info.

Sorry about that.

Give me some time to merge a branch and then try out the instructions at:

* https://snl-wiki.sandia.gov/display/CoodinatedDevOpsATDM/Building+and+Testing+EMPIRE+against+Trilinos

I will ping you in this issue when ready.

**Comment by nmhamster** [comment]
@barlettroscoe - thanks, appreciate the help. I have used the Wiki as its easy to get to :-).

**Comment by bartlettroscoe** [comment]
@nmhamster,

With the merge of PR #4683 just now, the instructions at:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#building-and-installing-trilinos-for-atdm-applications

should be correct now.

Please let me know if you have any questions about this or any problems with this.
