### ISSUE TITLE
Panzer:  Memory Usage Utility

### ISSUE THREAD

**Issue by jmgate** [trilinos/Trilinos#538]
It'd be great to be able to determine what our memory usage is so when we make changes to Panzer we can definitively say what the change in memory footprint looks like.

**Comment by jmgate** [comment]
Check out <a href="https://github.com/trilinos/Trilinos/commit/c623c3cdaa63d12d0e8009a5da87bc6a41283b55">this commit</a> for a place to start.

**Comment by jmgate** [comment]
I'm afraid I don't quite understand how the methods implemented in the commit mentioned above are working.  Adding a bunch of `double`s seems to increase the memory usage by less than the size of all those `double`s.  Adding a bunch of `int`s instead doesn't increase the memory usage at all.  Adding a `vector` of `double`s behaves the same as adding a bunch of `double`s.  Very strange.

Trying a different attempt based on reading `"/proc/self/stat"`...

**Comment by jmgate** [comment]
Attempt number two yielded similar results.

Attempted a third solution based on <a href="http://nadeausoftware.com/articles/2012/07/c_c_tip_how_get_process_resident_set_size_physical_memory_use">this code</a>.  Results were similar.  Seems like I can track memory usage to within an order of magnitude, but not necessarily more precisely than that.

**Comment by ibaned** [comment]
On systems that support it, `mallinfo().uordblks` will be more precise, because it sees individual calls to `malloc` as opposed to just process page maps.

http://man7.org/linux/man-pages/man3/mallinfo.3.html

**Comment by jmgate** [comment]
All options investigated did not have the precision I was looking for, so I settled on the third attempt, which gives both current and peak memory usage for the current process across all cores.  Added two unit tests to verify both that the memory usage increases after creating a bunch of variables, and that the peak usage is always >= the current usage.

Best way to use this tool is probably at the end of a problem.  Just call `printMemoryUsage()`, passing it an `ostream` and a `Teuchos::Comm`.  You'd probably want to save off that usage information, so after you've made some changes to the code, you can run the same problem, note the new usage info, and then be able to say definitively how the memory footprint had changed due to your changes.  For that use case it should be more than adequate.

**Comment by eric-c-cyr** [comment]
Reopening this issue to explore some tools that Paul Lin uses.
