### ISSUE TITLE
MueLu: trilinos@develop via spack fails to build on OSX for clang@10.0.1-apple

### ISSUE THREAD

**Issue by balay** [trilinos/Trilinos#5381]
## Bug Report

trilinos@develop via spack fails to build on OSX for clang@10.0.1-apple

The failure appears to be in MueLu component.

### Steps to Reproduce
1. on OSX - obtain spack and seup to use xcode clang [with brew gfortran]
2. spack install xsdk@develop
3. SHA1:  commit 6e86eb49d1cc3440f5f0e9e607f800974e5b6c5e
4. Spack Build log:  
[spack-build.out.txt](https://github.com/trilinos/Trilinos/files/3287053/spack-build.out.txt)

cc: @jwillenbring @keitat

**Comment by mhoemmen** [comment]
@trilinos/muelu

**Comment by jhux2** [comment]
Another user has also reported this, but I have no access to a Mac to try to reproduce this.  Clang on Linux works fine, so it appears to be something specific to the Apple linker.

**Comment by etphipp** [comment]
I suspect you could reproduce this on linux (with clang or gcc) by adding `--no-allow-shlib-undefined` as a linker flag.

**Comment by jhux2** [comment]
I'm told it's possible to force the gnu linker to enforce the same behavior as on an Apple, which will give me a path to fixing this.  In the meantime, @balay, you may be able to work around this by using the flag `-undefined treatment`:

```
     -undefined treatment
                 Specifies how undefined symbols are to be treated. Options
                 are: error, warning, suppress, or dynamic_lookup.  The
                 default is error.
```

**Comment by jhux2** [comment]
This was fixed a while ago by reverting to a single MueLu library.
