### ISSUE TITLE
IOSS Catalyst Adapter and Python3

### ISSUE THREAD

**Issue by jrood-nrel** [trilinos/Trilinos#5386]
## Bug Report
@trilinos/ioss

Would it be possible to get the Catalyst IOSS adapter updated for Python 3? Specifically `PhactoriDriver.py` appears to fail when using Python 3. @tjotaha @jeffmauldin

**Comment by tjotaha** [comment]
Jon. I talked to Jeff about this issue, and he will make the necessary changes to get PhactoriDriver.py working with Python 3.

**Comment by jrood-nrel** [comment]
Excellent.

**Comment by jrood-nrel** [comment]
I haven't checked on this lately. Have these changes occurred?

**Comment by tjotaha** [comment]
@jrood-nrel Development is still in progress.

**Comment by DeeDiveT** [comment]
Hi @tjotaha, I have similar dependency issues with installing the  Trilinos IOSS Catalyst Adapter by spack, see https://github.com/Exawind/nalu-wind/issues/557. How about the progress now?

Thanks.
