### ISSUE TITLE
Panzer: build error due to autogenerated header files: Panzer_STK_SetupLOWSFactory.cpp

### ISSUE THREAD

**Issue by Tdub1229** [trilinos/Trilinos#5394]
## Question
@trilinos/\Piro

I was building and installing Trilinos on my new desktop and I got this message:

g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
packages/panzer/adapters-stk/src/CMakeFiles/panzer-stk.dir/build.make:206: recipe for target 'packages/panzer/adapters-stk/src/CMakeFiles/panzer-stk.dir/Panzer_STK_SetupLOWSFactory.cpp.o' failed
make[2]: *** [packages/panzer/adapters-stk/src/CMakeFiles/panzer-stk.dir/Panzer_STK_SetupLOWSFactory.cpp.o] Error 4
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:23685: recipe for target 'packages/panzer/adapters-stk/src/CMakeFiles/panzer-stk.dir/all' failed
make[1]: *** [packages/panzer/adapters-stk/src/CMakeFiles/panzer-stk.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2

Any help would be greatly appreciated! Thank you

**Comment by rppawlo** [comment]
Try wiping your build directory. That class had an autogenerated header file that was created in the build directory at configure time. The autogenerated file was removed in a commit late last week.  If you updated trilinos and recompiled, you will pick up the old corrupted header in the build directory instead of the new one in the source directory.

**Comment by Tdub1229** [comment]
I wiped the build directory. It did not solve the problem. I tried by removing the "old" version of Trilinos and repeated the following steps about 2 hours ago: git clone, cmake -DTPL_ENABLE_MPI=ON -DMPI_BASE_DIR=/usr/bin/gcc -DTrilinos_ENABLE_ALL_PACKAGES=ON -DTPL_ENABLE_Matio=OFF -DCMAKE_INSTALL_PREFIX=/usr/bin /home/ed/Trilinos make -j8 install. There was a issue with Matio, but since I dont need it (80% sure) for both Albany and DAKOTA I'm happy building Trilinos without it. Not sure what is going on?

Thank you for your time!

**Comment by mhoemmen** [comment]
Try a lower `-j` number -- depending on how much memory your laptop has.

**Comment by rppawlo** [comment]
As Mark mentioned - this is most likely lack of memory. Closing since panzer is builds on all CI/nightly testing platforms. Feel free to reopen if needed.
