### ISSUE TITLE
Tpetra:  unused variable 'tfecfFuncName' warning

### ISSUE THREAD

**Issue by rrdrake** [trilinos/Trilinos#5408]
## Bug Report
@trilinos/tpetra

### Description
Sierra compilation with GCC 7.2 is failing (warnings are treated as errors) because of
```
Tpetra_CrsGraph_def.hpp:2356:16: error: unused variable 'tfecfFuncName' [-Werror=unused-variable]
     const char tfecfFuncName[] = "findLocalIndices: ";
                ^~~~~~~~~~~~~
```

### Steps to Reproduce
1. Checkout Trilinos 7506e6b2909e2dd8841e42471bea2f99346f9a53 into Sierra
1. Build Sierra aria

**Comment by mhoemmen** [comment]
PR with fix here: https://github.com/trilinos/Trilinos/pull/5410
