### ISSUE TITLE
Piro test build error in Trilinos-atdm-sems-rhel6-gnu-7.2.0-openmp-release-debug-no-global-int (ATDV-174)

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#5412]
CC: @trilinos/piro, @rppawlo  (Trilinos Nonlinear Solvers Product Lead), @bartlettroscoe, @fryeguy52

<Checklist>
<???: Add label "client: ATDM">
<???: Add label "ATDM Sev: Blocker" (by default but could be other "ATDM Sev: XXX")>
<???: Add label "type: bug"?>
<???: Add label for affected packages (e.g. "pkg: MueLu", "pkg: Tpetra", "pkg: Kokkos", etc.)>
<???: Add label "PA: ???Project Area???" (e.g. "PA: Linear Solvers", "PA: Data Services")>
<???: Add milestone "Initial cleanup of new ATDM ..." or "Keep promoted ATDM ...">
<???: Once GitHub Issue is created, add entries for tests to TrilinosATDMStatus/*.csv files>

## Next Action Status

<status-and-or-first-action>

## Description

As shown in [this query](https://testing-dev.sandia.gov/cdash/index.php?project=Trilinos&date=2019-06-19&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-sems-rhel6-gnu-7.2.0-openmp-release-debug-no-global-int&field2=subprojects&compare2=93&value2=Piro&field3=buildstarttime&compare3=83&value3=2019-06-15) and [here](https://testing-dev.sandia.gov/cdash/viewBuildError.php?buildid=4663645), Piro has a build error in the new build:

* Trilinos-atdm-sems-rhel6-gnu-7.2.0-openmp-release-debug-no-global-int

when linking the exectuable

* [packages/piro/test/Piro_ThyraSolver.exe](https://testing-dev.sandia.gov/cdash/viewBuildError.php?buildid=4663645)

showing the link error:

```
/usr/bin/ld: skipping incompatible /lib/libgcc_s.so.1 when searching for libgcc_s.so.1
/usr/bin/ld: skipping incompatible /lib/libgcc_s.so.1 when searching for libgcc_s.so.1
packages/piro/test/CMakeFiles/Piro_ThyraSolver.dir/Main_ThyraSolver.cpp.o: In function `allocate':
/jenkins/slave/workspace/Trilinos-atdm-sems-rhel6-gnu-7.2.0-openmp-release-debug-no-global-int/SRC_AND_BUILD/Trilinos/packages/teuchos/coreTeuchos_AbstractFactoryStd.hpp:68: undefined reference to `Thyra::Ifpack2PreconditionerFactory<Tpetra::CrsMatrix<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP, Kokkos::HostSpace> > >::Ifpack2PreconditionerFactory()'
collect2: error: ld returned 1 exit status
```

which results in just one not-run test:

* [Piro_ThyraSolver_MPI_4](https://testing-dev.sandia.gov/cdash/testDetails.php?test=69771464&build=4663657)

This is part of an effort to set `Tpetra_INST_INT_INT=OFF` in all of that ATDM Trilinos builds (see [ATDV-174](https://sems-atlassian-srn.sandia.gov/browse/ATDV-174)) related to #4915.

## Current Status on CDash

See recent results for Piro in this build over [last several days](https://testing-dev.sandia.gov/cdash/index.php?project=Trilinos&date=2019-06-19&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-sems-rhel6-gnu-7.2.0-openmp-release-debug-no-global-int&field2=subprojects&compare2=93&value2=Piro&field3=buildstarttime&compare3=83&value3=5%20days%20ago).

## Steps to Reproduce

One should be able to reproduce this failure on any SNL COE RHEL6 machine that has the SEMS env mounted.  See:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md

The exact commands to reproduce this issue should be:

```
$ cd <some_build_dir>/

$ source $TRILINOS_DIR/cmake/std/atdm/load-env.sh \
  Trilinos-atdm-sems-rhel6-gnu-7.2.0-openmp-release-debug-no-global-int

$ cmake \
 -GNinja \
 -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
 -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_Piro=ON \
 $TRILINOS_DIR

$ ninja -j16
```

**Comment by bartlettroscoe** [comment]
@rppawlo,

Given that the ATDM APPs don't actually use Piro, can we just disable the building and running of this one test in all of that ATDM Trilinos builds?  This would not disable this in any other builds.

**Comment by rppawlo** [comment]
Sure - that works fine.

**Comment by bartlettroscoe** [comment]
> > Given that the ATDM APPs don't actually use Piro, can we just disable the building and running of this one test in all of that ATDM Trilinos builds? 
> 
> Sure - that works fine.

See PR #5424.

**Comment by bartlettroscoe** [comment]
FYI: With PR #5424 merged, this error should go away.  I will wait until we get confirmation of this on CDash tomorrow and then will add the "Disabled Tests" label to remove this from our query.

However, we should not close this since this should get fixed since all Trilinos builds will need to eliminate the instantiation of both `int` and `long long int` for global ordinals since Tpetra will not support that in the future.

**Comment by bartlettroscoe** [comment]
As shown [here](https://testing-dev.sandia.gov/cdash/index.php?project=Trilinos&parentid=4667495&filtercount=1&showfilters=1&field1=subprojects&compare1=93&value1=Piro), this build and test not-run failure are gone in this build `Trilinos-atdm-sems-rhel6-gnu-7.2.0-openmp-release-debug-no-global-int` (see the little `-1` subscripts by the `0` in the columns "Build Error" and "Test Not Run").  You can see this is due to the disable of this test as shown in the [configure output](https://testing-dev.sandia.gov/cdash/viewConfigure.php?buildid=4667520) showing:

```
-- Piro_ThyraSolver EXE NOT being built due to Piro_ThyraSolver_EXE_DISABLE='ON'
-- Piro_ThyraSolver_MPI_4: NOT added test because Piro_ThyraSolver_MPI_4_DISABLE='ON'!
```

Adding label "Disabled Tests" to get this off of our list of active ATDM issues (which is over 30 now and going to get larger).
