### ISSUE TITLE
Test MueLu_Maxwell3D-Tpetra-ML-list_MPI_4 failing in new build Trilinos-atdm-sems-rhel6-gnu-7.2.0-openmp-release-debug-no-global-int

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#5414]
CC: @trilinos/muelu, @srajama1 (Trilinos Linear Solvers Product Lead), @bartlettroscoe, @fryeguy52, @rppawlo 

<Checklist>
<???: Add label "client: ATDM">
<???: Add label "ATDM Sev: Blocker" (by default but could be other "ATDM Sev: XXX")>
<???: Add label "type: bug"?>
<???: Add label for affected packages (e.g. "pkg: MueLu", "pkg: Tpetra", "pkg: Kokkos", etc.)>
<???: Add label "PA: ???Project Area???" (e.g. "PA: Linear Solvers", "PA: Data Services")>
<???: Add milestone "Initial cleanup of new ATDM ..." or "Keep promoted ATDM ...">
<???: Once GitHub Issue is created, add entries for tests to TrilinosATDMStatus/*.csv files>

## Next Action Status

<status-and-or-first-action>

## Description

As shown in [this query](https://testing-dev.sandia.gov/cdash/index.php?project=Trilinos&date=2019-06-19&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-sems-rhel6-gnu-7.2.0-openmp-release-debug-no-global-int&field2=subprojects&compare2=93&value2=MueLu&field3=buildstarttime&compare3=83&value3=2019-06-15) the MueLu test:

* [MueLu_Maxwell3D-Tpetra-ML-list_MPI_4](https://testing-dev.sandia.gov/cdash/viewTest.php?onlyfailed&buildid=4663645)

fails in the new build:

* Trilinos-atdm-sems-rhel6-gnu-7.2.0-openmp-release-debug-no-global-int

showing the error [here](https://testing-dev.sandia.gov/cdash/testDetails.php?test=69836850&build=4663653) showing:

```
p=1: *** Caught standard std::exception of type 'MueLu::Exceptions::RuntimeError' :

 /jenkins/slave/workspace/Trilinos-atdm-sems-rhel6-gnu-7.2.0-openmp-release-debug-no-global-int/SRC_AND_BUILD/Trilinos/packages/muelu/src/Interface/MueLu_ML2MueLuParameterTranslator.cpp:328:
 
 Throw number = 1
 
 Throw test that evaluated to true: !paramList.sublist("coarse: list").isParameter("smoother: type")
 
 MueLu::MLParameterListInterpreter::Setup(): no coarse grid solver defined.
```

which results in just one not-run test:

* [MueLu_ThyraSolver_MPI_4](https://testing-dev.sandia.gov/cdash/testDetails.php?test=69771464&build=4663657)

This is part of an effort to set `Tpetra_INST_INT_INT=OFF` in all of that ATDM Trilinos builds (see [ATDV-174](https://sems-atlassian-srn.sandia.gov/browse/ATDV-174)) related to #4915.

## Current Status on CDash

See recent results for MueLu in this build over [last several days](https://testing-dev.sandia.gov/cdash/index.php?project=Trilinos&date=2019-06-19&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-sems-rhel6-gnu-7.2.0-openmp-release-debug-no-global-int&field2=subprojects&compare2=93&value2=MueLu&field3=buildstarttime&compare3=83&value3=5%20days%20ago).

## Steps to Reproduce

One should be able to reproduce this failure on any SNL COE RHEL6 machine that has the SEMS env mounted.  See:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md

The exact commands to reproduce this issue should be:

```
$ cd <some_build_dir>/

$ source $TRILINOS_DIR/cmake/std/atdm/load-env.sh \
  Trilinos-atdm-sems-rhel6-gnu-7.2.0-openmp-release-debug-no-global-int

$ cmake \
 -GNinja \
 -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
 -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_MueLu=ON \
 $TRILINOS_DIR

$ ninja -j16

$ ctest -VV -R MueLu_Maxwell3D-Tpetra-ML-list_MPI_4
```

**Comment by cgcgcg** [comment]
PR #5402 should take care of this.

**Comment by srajama1** [comment]
@cgcgcg Thanks ! I suggest closing this then .. Does Maxwell get tested in PR testing ? How did this pass there ?

**Comment by cgcgcg** [comment]
@srajama1 I'll close it once the PR is merged. Yep, it does. The error comes from enabling ML without Epetra.

**Comment by bartlettroscoe** [comment]
@srajama1 said:

> I suggest closing this then

We can't close an ATDM Trilinos GitHub issue until the PR is merged and we get confirmation on CDash that the issue is resolved.

**Comment by csiefer2** [comment]
> The error comes from enabling ML without Epetra, which the PR tester is not doing.

That is an perverse configuration which does not represent the needs of ATDM customers.  I highly suggest changing the configuration.

**Comment by bartlettroscoe** [comment]
@cgcgcg said:

> The error comes from enabling ML without Epetra, which the PR tester is not doing.

Do you mean "enabling MueLu without Epetra"?  What does ML have to do with MueLu?  We are talking about a MueLu test here, not an ML test.  I see that MueLu has a dependence on ML but I would assume this is just a test dependence (to compare MueLu and ML) but that core MueLu functionality does not depend on ML (or how would you run on a GPU)?

And just to be clear, Epetra support in ML is **not** currently being disabled in the ATDM Trilinos configuration as shown [here](https://testing-dev.sandia.gov/cdash/viewConfigure.php?buildid=4663645) which shows:

```
-- Setting ML_ENABLE_Epetra=ON since Trilinos_ENABLE_ML=ON AND Trilinos_ENABLE_Epetra=ON
```


@csiefer2 said:

> That is an perverse configuration which does not represent the needs of ATDM customers. I highly suggest changing the configuration.

In what way?  Enabling MueLu with Tpetra but without Epetra seems perfectly logical.

**Comment by cgcgcg** [comment]
@bartlettroscoe We test the translation of an ML style parameter list for use with MueLu. We call the ML parameter list validation.

**Comment by csiefer2** [comment]
> In what way? Enabling MueLu with Tpetra but without Epetra seems perfectly logical.

It is.  Turning on ML without Epetra is illogical.  Which is, from what you've presented, not happening either.

**Comment by bartlettroscoe** [comment]
> It is. Turning on ML without Epetra is illogical. Which is, from what you've presented, not happening either.

Can we just turn of ML all together for ATDM?  Can MueLu be made to build and work correctly without ML?  Can the parts of ML that MueLu uses be moved into an independent (sub)package and then used by ML and MueLu?

**Comment by bartlettroscoe** [comment]
CC: @rppawlo, @srajama1 

@trilinos/muelu 

FYI: With #5411 and #5412 now resolved, this MueLu failure is the last failure we need to resolve in order to disable the global ordinal 'int' instantiation in the ATDM Trilinos builds.  We can't pull the trigger on that until this failure is resolved (one way or another) or this test will fail in every ATDM Trilinos build on all platforms.

Is this test alone protecting critical functionality for ATDM APPs?  Are the no other MueLu tests protecting this functionality?  What is the risk if we just disable this test for ATDM Trilinos builds?  (But once a test gets disabled it seems they never get re-enabled.)

**Comment by srajama1** [comment]
@bartlettroscoe : I suggest we fix it rather than disable it. As you note, we rarely go through disabled tests and reenable it.

**Comment by cgcgcg** [comment]
PR #5402 is almost through the autotester..

**Comment by bartlettroscoe** [comment]
> As you note, we rarely go through disabled tests and reenable it.

There are exceptions such as #2410.  In that case, the full test `TeuchosNumerics_LAPACK_test_MPI_1` was disabled for a time and then it get re-enabled (and just a single unit tests for Power platforms got disabled).  So it does happen.

**Comment by bartlettroscoe** [comment]
It looks like PR #5402 made the failing test `MueLu_Maxwell3D-Tpetra-ML-list_MPI_4` disappear in this build as shown [here](https://testing-dev.sandia.gov/cdash/viewTest.php?buildid=4674719&filtercount=1&showfilters=1&field1=testname&compare1=61&value1=MueLu_Maxwell3D-Tpetra-ML-list_MPI_4).

@cgcgcg, was this a mistake?  Will this test be added back or is it gone for good?  It is safe to go ahead and use the setting in this build `Trilinos-atdm-sems-rhel6-gnu-7.2.0-openmp-release-debug-no-global-int` in all of the ATDM Trilinos builds?

**Comment by cgcgcg** [comment]
@bartlettroscoe The test is now only added if MueLu has support for ML and Epetra. Since this is not the case for this build, it disappeared (and should be gone for good).

**Comment by bartlettroscoe** [comment]
> The test is now only added if MueLu has support for ML and Epetra. Since this is not the case for this build, it disappeared (and should be gone for good).

Okay, since this test is invalid in this case we can go ahead and close this issue as done.

Thanks for resolving!

**Comment by bartlettroscoe** [comment]
Closing for real :-)
