### ISSUE TITLE
Tpetra: is there a Tpetra analog of the EpetraExt::HDF5 class?

### ISSUE THREAD

**Issue by ikalash** [trilinos/Trilinos#5415]
An Albany user is interested in whether there is a Tpetra version of the EpetraExt::HDF5 routine for reading/writing parallel HDF5 files from Tpetra objects.  It doesn't seem like there is looking at the documentation, but I was wondering if someone could confirm this.

@trilinos/tpetra

**Comment by mhoemmen** [comment]
That doesn't exist.

**Comment by ikalash** [comment]
Thanks, I thought so.
