### ISSUE TITLE
Intrepid2:  Unconditional screen output during runs

### ISSUE THREAD

**Issue by glhenni** [trilinos/Trilinos#5423]
## Bug Report
@trilinos/intrepid2

### Description
Looks like there's some screen output left over from probably some debugging work. At `Intrepid2_CubatureControlVolumeBoundaryDef.hpp:279` there is a statement,
```
std::cout << "subcv jacobian rank = " << subcvJacobian.rank() << std::endl;
```
which isn't blocked off by anything so it is unconditionally being printed out to the screen. It's a bit annoying when you're running on hundreds+ of processors.

**Comment by jhux2** [comment]
@trilinos/intrepid2 @mperego
