### ISSUE TITLE
Set Tpetra_INST_INT_INT=OFF and some related options in one Trilinos PR build to protect ATDM

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#5435]
CC: @trilinos/tpetra, @rppawlo, @kddevin, @mhoemmen 

@trilinos/framework 

Can we please change one of the Trilinos PR builds to set `Tpetra_INST_INT_INT=OFF` and some related options?  We need to do the to protect ATDM Trilinos builds that will be setting this option very shortly (see [ATDV-174](https://sems-atlassian-srn.sandia.gov/browse/ATDV-174) and #4915).  The other options that need to be set are shown in PR #5384 and #5424.   (I can create a PR to set just the right options, it is not many).

I fear that if we don't have a Trilinos PR build that sets these options, then Trilinos will get broken more frequently for ATDM customers.

Also, since Tpetra has deprecated support for multiple global ordinal types, this is the direction all of Trilinos will need to go at some point.

**Comment by mhoemmen** [comment]
SPARC already sets this option in its Trilinos builds.

**Comment by jwillenbring** [comment]
We will discuss this at the @trilinos/framework standup tomorrow. This is a good idea.

**Comment by kddevin** [comment]
Tpetra_INST_INT_INT=OFF is the default since #6388 
Now we need a Tpetra_INST_INT_INT=ON build now:  #6570 
I will close this issue.
