### ISSUE TITLE
Failing Albany builds due to changes in STK 

### ISSUE THREAD

**Issue by ikalash** [trilinos/Trilinos#5436]
Our nightly builds of Albany failed last night due to STK.  Here is the error: 

```
/.../repos/Albany/src/disc/stk/Albany_GenericSTKMeshStruct.cpp(178): error: no instance of constructor "stk::mesh::BulkData::BulkData" matches the argument list
```
(http://cdash.sandia.gov/CDash-2-3-0/viewBuildError.php?buildid=86175 ) .  The builds use Trilinos develop branch.

Did stk::mesh::BulkData change?

**Comment by alanw0** [comment]
Irina, yes a BulkData constructor was deprecated. It had been marked with a DEPRECATED macro previously, so it should have been producing warnings. (But possibly the warnings are off unless you use the -DTrilinos_SHOW_DEPRECATED_WARNINGS:BOOL=ON flag.) I'll try to take a look at the error and let you know which constructor argument is no longer accepted.

**Comment by alanw0** [comment]
Irina, the 'ConnectivityMap' argument to the stk::mesh::BulkData constructor has been removed. On about line 183 of Albany_GenericSTKMeshStruct.cpp you just need to delete the 'NULL' that represents the ConnectivityMap argument.

**Comment by ikalash** [comment]
Thanks @alanw0 , I'll give it a try.
