### ISSUE TITLE
Tpetra:  Multiply (reduce) is very slow

### ISSUE THREAD

**Issue by jjellio** [trilinos/Trilinos#5437]
## Bug Report
@trilinos/tpetra

### Description
I've profiled native Kokkos::gemm and MPI_Allreduce, and compared the sum of the parts to the Tpetra::multiply.

Allreduce(2 scalars) : 4 us
Gemm (10000x1, 10000x2): 37.9 +/- 0.6 us (cublas)
Expected Tpetra::Multiply time: 42 us

I observe,
Tpetra::multiply : 97.4 +/- 0.6 us

I did a simple test, and commented out the reduce() portion of the Multiply routine, and I obtained a timing of  38 us. (so the problem is in reduce)

Moreover, I hunted the issue in reduce() down to allReduceView(), which will always result in 'needContiguousTemporaryBuffers' being true when UVM is used.  This then constructs new buffers, copies data, does MPI, then copies back to the intended buffers.

This should be reproducible on any GPU testbed using UVM, or ping me I'll share the driver in my Trilinos fork.

I believe the root of the problem is that Tpetra is trying to do things differently based on whether the buffers are UVM and whether CudaAwareMPI is available.

If I modify the code to only use CudaAwareMPI as the flag for needing to copy, I can recover expected performance:
Tpetra::multiply: 45.3 +/- 0.5 us

In my opinion, it would be better to just 'do' whatever the user requests (use their buffers) and rely on the user to do the right thing.  Then, most of the code for 'reduce' can go away, and the the code paths using 'reduce()' will become substantially faster.

@mhoemmen @csiefer2 @srajama1

**Comment by csiefer2** [comment]
@kddevin

**Comment by jjellio** [comment]
This should be closed.

I botched something, and this issue didn't see the PR:
https://github.com/trilinos/Trilinos/pull/5445

**Comment by mhoemmen** [comment]
Thanks @jjellio ! :-D
