### ISSUE TITLE
PyTrilinos library being exported when it shouldn't be

### ISSUE THREAD

**Issue by bmpersc** [trilinos/Trilinos#545]
Bill Spotz reported that the export system for Trilinos is exporting the PyTrilinos library which is a problem since it depends on the python library. This causes linking errors when people use find_package(Trilinos) to get all the necessary information for Trilinos. The PyTrilinos library is in the list of Trilinos libraries, but it won't ever link. The sticking point here is that this library needs to be installed to work properly, but should not be in the export files.

I'm not sure of the right way to solve this. Should this be a special option passed in to the tribits_add_library? would doing that have impact on linking other things that are currently working? Maybe this should be a post processing step stripping it out for only the export. We'll need to look into the right way to do this.

**Comment by wfspotz** [comment]
Closing in favor of #866
