### ISSUE TITLE
CMake fails after 100% building

### ISSUE THREAD

**Issue by Tdub1229** [trilinos/Trilinos#5469]
Install the project...
-- Install configuration: "RELEASE"
-- Up-to-date: /usr/bin/./TrilinosRepoVersion.txt
CMake Error at cmake_install.cmake:41 (file):
  file INSTALL cannot set permissions on "/usr/./TrilinosRepoVersion.txt"

Makefile:73: recipe for target 'install' failed
make: *** [install] Error 1

Is there a possible conflict between dependent packages?

**Comment by jhux2** [comment]
Do you have root permissions to install in that location?
