### ISSUE TITLE
Ifpack2::AdditiveSchwarz RBILUK unit test failing

### ISSUE THREAD

**Issue by jhux2** [trilinos/Trilinos#547]
In looking at issue #460, I've found that the AdditiveSchwarz unit test w/ RBILUK as a subdomain solve is failing in my local build.  The dashboard appears to be clean.  Here are my configure options:

```
 -D CMAKE_BUILD_TYPE:STRING="DEBUG"
  -D CMAKE_CXX_FLAGS:STRING="-g"
  -D DART_TESTING_TIMEOUT:STRING=30

  -D Trilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON
    -D Teuchos_ENABLE_COMPLEX:BOOL=ON
    -D Tpetra_INST_COMPLEX_FLOAT=OFF
    -D Tpetra_INST_COMPLEX_DOUBLE=ON
  -D Trilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=OFF

  -D Trilinos_ENABLE_Amesos2:BOOL=ON
    -D Amesos2_ENABLE_Basker:BOOL=ON
  -D Trilinos_ENABLE_Belos:BOOL=ON
  -D Trilinos_ENABLE_Galeri:BOOL=ON
  -D Trilinos_ENABLE_Ifpack2:BOOL=ON
    -D Ifpack2_ENABLE_Experimental:BOOL=ON
    -D Ifpack2_ENABLE_TESTS:STRING=ON
  -D Trilinos_ENABLE_Teuchos:BOOL=ON
    -D Teuchos_ENABLE_STACKTRACE:BOOL=OFF
  -D Trilinos_ENABLE_Xpetra:BOOL=ON
    -D Xpetra_ENABLE_TESTS:STRING=OFF
    -D Xpetra_ENABLE_EXAMPLES:STRING=OFF
    -D Xpetra_ENABLE_Experimental=ON
  -D Trilinos_ENABLE_Zoltan2:BOOL=ON
  -D Zoltan2_ENABLE_Experimental:BOOL=ON

  -D TPL_ENABLE_BLAS:BOOL=ON
  -D TPL_ENABLE_MPI:BOOL=ON
```

**Comment by kddevin** [comment]
@jhux2 :  Complex=on is currently a problem for Zoltan2.  See #244.  We are addressing the problem and hope to have it resolved in a week or so; see the discussion in #244 .  Until then, disabling Zoltan2 ordering is one option; disabling complex is another.  I apologize for the inconvenience.

**Comment by kddevin** [comment]
This week, we pushed changes to Zoltan2 and Ifpack2 that we hope will fix this problem.  Would you please try your compilation again and let us know whether or not it works?  Thanks.

**Comment by aprokop** [comment]
No traffic on the ticker in a while. Assuming the push in the last comment fixed the issue.
