### ISSUE TITLE
TrilinosCouplings: Add distance dropping stats

### ISSUE THREAD

**Issue by agenbyte** [trilinos/Trilinos#5471]
## Enhancement
@trilinos/trilinoscouplings 

Adding mesh statistics for distance dropping to get a better feature set for machine learning drop tol algorithm.

**Comment by mhoemmen** [comment]
@agenbyte I edited your `@` tag to correct the spelling error and remove the angle brackets.

**Comment by csiefer2** [comment]
Excited! :)
