### ISSUE TITLE
ShyLU_Node: Intermittent test failure on master in GCC 4.8.4

### ISSUE THREAD

**Issue by prwolfe** [trilinos/Trilinos#5472]
## Bug Report
@trilinos/shylu 
@trilinos/kokkos 

### Description
The test ShyLU_NodeTacho_Tacho_TestOpenMPDoubleTaskSchedulerMultiple_MPI_1 has been failing itermmitently since the 28th when run on gc 4.8.4 builds. We have had develop -> master promotions during this time so it's already there. the error is

> Kokkos contract violation:
>    Expected precondition `not m_wait_queue.is_consumed()` evaluated false.

So this may relate to the Kokkos team.

### Steps to Reproduce
Build and run the test using gcc 4.8.4 and the pull request instructions at https://github.com/trilinos/Trilinos/wiki/Reproducing-PR-Testing-Errors. Repeat until you get a failure (about 1 out of 3 so far.)

**Comment by srajama1** [comment]
@kyungjoo-kim I am not able to find David Hollman in github mention, so adding Kyungjoo.

**Comment by kyungjoo-kim** [comment]
@prwolfe Could you show me the complete error message output ? It uses gtest and we need to know which test triggers the failure. Does this failure only happen with a gcc compiler ? 

@dhollman I think that we saw this error before somehow and this should not be happened. I thought that we fixed the problem but we did not check openmp gcc version.  As kokkos promotion PR passes the PR test, this might be related to a runtime race condition. Do you have any idea of this failure ?

**Comment by prwolfe** [comment]
@kyungjoo-kim - see https://testing.sandia.gov/cdash/testDetails.php?test=82838381&build=5260496 for the full output. If you don't have access it's

> Test output
> Kokkos::OpenMP::initialize WARNING: OMP_PROC_BIND environment variable not set
>   In general, for best performance with OpenMP 4.0 or better set OMP_PROC_BIND=spread and OMP_PLACES=threads
>   For best performance with OpenMP 3.1 set OMP_PROC_BIND=true
>   For unit testing set OMP_PROC_BIND=false
>      DeviceSpace::  Kokkos::OpenMP thread_pool_topology[ 1 x 2 x 1 ]
>        HostSpace::  Kokkos::OpenMP thread_pool_topology[ 1 x 2 x 1 ]
> [==========] Running 58 tests from 7 test cases.
> [----------] Global test environment set-up.
> [----------] 2 tests from CrsMatrixBase
> [ RUN      ] CrsMatrixBase.constructor
> [       OK ] CrsMatrixBase.constructor (0 ms)
> [ RUN      ] CrsMatrixBase.matrixmarket
> [       OK ] CrsMatrixBase.matrixmarket (0 ms)
> [----------] 2 tests from CrsMatrixBase (0 ms total)
> 
> [----------] 1 test from Graph
> [ RUN      ] Graph.constructor
> [       OK ] Graph.constructor (0 ms)
> [----------] 1 test from Graph (0 ms total)
> 
> [----------] 3 tests from Symbolic
> [ RUN      ] Symbolic.constructor
> [       OK ] Symbolic.constructor (0 ms)
> [ RUN      ] Symbolic.functions
> 
> camd version 2.2, May 31, 2007:  approximate minimum degree ordering:
>     dense row parameter: 10
>     (rows with more than max (10 * sqrt (n), 16) entries are
>     considered "dense", and placed last in output permutation)
>     aggressive absorption:  yes
> 
> [       OK ] Symbolic.functions (0 ms)
> [ RUN      ] Symbolic.interface
> 
> camd version 2.2, May 31, 2007:  approximate minimum degree ordering:
>     dense row parameter: 10
>     (rows with more than max (10 * sqrt (n), 16) entries are
>     considered "dense", and placed last in output permutation)
>     aggressive absorption:  yes
> 
> [       OK ] Symbolic.interface (1 ms)
> [----------] 3 tests from Symbolic (1 ms total)
> 
> [----------] 3 tests from Numeric
> [ RUN      ] Numeric.constructor
> [       OK ] Numeric.constructor (0 ms)
> [ RUN      ] Numeric.Cholesky_Serial
> 
> camd version 2.2, May 31, 2007:  approximate minimum degree ordering:
>     dense row parameter: 10
>     (rows with more than max (10 * sqrt (n), 16) entries are
>     considered "dense", and placed last in output permutation)
>     aggressive absorption:  yes
> 
> [       OK ] Numeric.Cholesky_Serial (1 ms)
> [ RUN      ] Numeric.factorizeCholesky_Parallel
> 
> camd version 2.2, May 31, 2007:  approximate minimum degree ordering:
>     dense row parameter: 10
>     (rows with more than max (10 * sqrt (n), 16) entries are
>     considered "dense", and placed last in output permutation)
>     aggressive absorption:  yes
> 
> [       OK ] Numeric.factorizeCholesky_Parallel (0 ms)
> [----------] 3 tests from Numeric (1 ms total)
> 
> [----------] 3 tests from DenseMatrixView
> [ RUN      ] DenseMatrixView.flat
> [       OK ] DenseMatrixView.flat (0 ms)
> [ RUN      ] DenseMatrixView.hier
> [       OK ] DenseMatrixView.hier (0 ms)
> [ RUN      ] DenseMatrixView.memorypool
> [       OK ] DenseMatrixView.memorypool (0 ms)
> [----------] 3 tests from DenseMatrixView (0 ms total)
> 
> [----------] 5 tests from DenseByBlocks
> [ RUN      ] DenseByBlocks.ldl
> [       OK ] DenseByBlocks.ldl (0 ms)
> [ RUN      ] DenseByBlocks.chol
> [       OK ] DenseByBlocks.chol (1 ms)
> [ RUN      ] DenseByBlocks.gemm
> [       OK ] DenseByBlocks.gemm (4 ms)
> [ RUN      ] DenseByBlocks.herk
> [       OK ] DenseByBlocks.herk (1 ms)
> [ RUN      ] DenseByBlocks.trsm
> Kokkos contract violation:
>     Expected precondition `not m_wait_queue.is_consumed()` evaluated false.--------------------------------------------------------------------------
> mpiexec noticed that process rank 0 with PID 22756 on node tr-test-7 exited on signal 6 (Aborted).
> --------------------------------------------------------------------------
>
