### ISSUE TITLE
Seacas:  seacas commit in 09/2018 messed up Exodus output for some Albany problems

### ISSUE THREAD

**Issue by ikalash** [trilinos/Trilinos#5479]
## Bug Report
@trilinos/seacas 

### Description
We recently discovered that since September 2018, some of the Exodus files produced by Albany runs are corrupted.  Using the method of bisection, I've identified that the following commit in Trilinos is what broke this capability for us: 

```
12cd80bbbdf88ce3ad2f7b4e7077419bf6d07aa0 .

    Automatic snapshot commit from seacas at 933debf80 (#3406)
    
    Origin repo remote tracking branch: 'origin/master'
    Origin repo remote repo URL: 'origin = https://github.com/gsjaardema/seacas'
    
    At commit:
    
    commit 933debf806affe117bf9992aaabf0e7dfc50c273
    Author:  Greg Sjaardema <gsjaardema@gmail.com>
    Date:    Fri Sep 7 09:01:04 2018 -0600
    Summary: EXODUS: Update version number forgotten in recent changes
```
The symptoms are as follows.  If I run the the following Albany example: 

Albany/tests/large/LCM/Schwarz/Alternating/Quasistatics
 
and then do ncdump -h cuboid_00.e (cuboid_00.e is the exodus file created by the run), the resulting file has 11 snapshots:
```
time_step = UNLIMITED ; // (11 currently)
```
In contrast, after the commit, I see:  
```
time_step = UNLIMITED ; // (0 currently)
```
There are no changes on the Albany side, I'm just using different Trilinos, so I'm sure the problem is not in Albany.  This issue is a spin-off of this Albany issue: https://github.com/SNLComputation/Albany/issues/482 . 

@gdsjaar could you please look at this?  It's possible this is not a bug but rather our usage of seacas/stk is no longer correct given whatever changes were in 12cd80bbbdf88ce3ad2f7b4e7077419bf6d07aa0 .

### Steps to Reproduce
I will provide instructions for building Trilinos/Albany on the platform of choice, as well as how to reproduce the issue.

**Comment by ikalash** [comment]
Just wanted to follow up on this issue: @gdsjaar , have you had a chance to look into it?

**Comment by gsjaardema** [comment]
Sorry, I just saw this today. Not sure why it didn't show up earlier in my queries/email.

If you can tell me how to build Trilinos/Albany on the CEE lan (or any of the clusters if CEE not an option), I will take a look

**Comment by ikalash** [comment]
@gsjaardema : no worries.  Let me test the scripts on CEE before I send them to you to make sure they work and you can reproduce the issue.  I'll be in touch soon.

**Comment by ikalash** [comment]
My apologies for the delay @gsjaardema .  Here are scripts you can use to reproduce the issue on the CEE.

Trilinos configure script and modules:
https://github.com/SNLComputation/Albany/blob/luca/bisection_tweaks/doc/do-cmake-trilinos-cee-gcc
https://github.com/SNLComputation/Albany/blob/luca/bisection_tweaks/doc/modules_cee_gcc.sh

Albany configure script: 
https://github.com/SNLComputation/Albany/blob/luca/bisection_tweaks/doc/do-cmake-albany-cee-gcc 

Here are instructions for how to build Albany and reproduce the issue:

1.) Build and install Trilinos using the modules and build script above.  It should work out of the box on the CEE.
2.) Clone Albany: git clone git@github.com:SNLComputation/Albany.git
cd Albany 
git checkout luca/bisection_tweaks
3.) Build Albany:
mkdir build
cd build
cp /path/to/do-cmake-albany* .
./do-cmake-albany* 
make -j32 
4.) To run the problematic test: 
cd /path/to/Albany/build/tests/large/LCM/Schwarz/Alternating/Quasistatics_seacasDebug
ctest -V 
or ./Albany cuboids.yaml

**Comment by ikalash** [comment]
As I said, if you pull this commit, you will see the issue described above: 12cd80bbbdf88ce3ad2f7b4e7077419bf6d07aa0  .

If you pull one commit earlier, the issue is not there.

An interesting symptom is if you do a debug build with the sha 12cd80bbbdf88ce3ad2f7b4e7077419bf6d07aa0 , things are good again.  

Please let me know if you have any questions or encounter any issues.  Thanks again for being willing to look at this @gsjaardema !

**Comment by gsjaardema** [comment]
Any idea what to do if the test passes?   I built optimized with the settings you gave and the correct commit, but the test passes...
```
1/1 Test #1: Schwarz_Alternating_Quasistatics ...   Passed    6.53 sec

100% tests passed, 0 tests failed out of 1
```

**Comment by ikalash** [comment]
@gsjaardema : sorry for the confusion.  The way the test is written, ctest will report it as passing even with this issue - this is showing a deficiency in how the test is written, and the reason why this slipped through the cracks for so many months.  To see the problem, you need to execute the command "ncdump -h cuboid_00.e" on one of the exodus files produced when you run the test (cuboid_00.e).  Specifically, you should see: 
```
time_step = UNLIMITED ; // (0 currently)
```
with the problematic commit, which says that no solution snapshots were written to the Exodus output file.  This is wrong, as the test did all the necessary solves and should have written the solution to the output file.  If you checkout the sha right before 12cd80bbbdf88ce3ad2f7b4e7077419bf6d07aa0, you should see:
```
time_step = UNLIMITED ; // (11 currently)
```
when you do "ncump -h cuboid_00.e", which is what we would expect (i.e., the solution snapshots were correctly written to the exodus output file).

**Comment by ikalash** [comment]
We'd like to understand what in 12cd80bbbdf88ce3ad2f7b4e7077419bf6d07aa0 caused the attempts to write the solution to the Exodus file to not happen, when they were happening correctly prior to this commit.

**Comment by gsjaardema** [comment]
OK thanks.  That makes sense now.

**Comment by ikalash** [comment]
Great, let me know if you have any more questions/issue.

**Comment by gsjaardema** [comment]
Update, but not a cause/solution yet.  Looks like the data is being output and is making it to the exodus file.  If I run the optimized code in the debugger and stop at each call to `ex_put_time`, it does end up hitting that routine several times and then if I look at the file during and after execution, the data is in the file...  

Looks like it is somehow related to flushing of the database.  I also ran an experimental capability in which each time steps data is split into a separate file.  At the end of the run, I had 11 files.  Files 1..10 all had data and a timestep in them as expected; however, the 11th file did not have any data in it.

I think the issue is related to the data not being flushed to the file correctly.  I put a breakpoint in `ex_close` which should be called at the end of the run, and that is not hit.  So, it looks like the destructors are not being run correctly at the end of the run.  Will try to run in debug or relwithdebinfo modes to see if I can see what is happening.  

Looking at the changes at that commit, I don't really see much of what would cause this, but there are a few changes related to flushing...  Not sure how much more I will get to before Monday, but I think I am getting close...

**Comment by ikalash** [comment]
Interesting - thanks for the update @gdsjaar .  Tagging @lxmota who will likely be interested - Alejandro, Greg is looking at the broken Schwarz I/O issue you discovered some time back.

@gdsjaar : as I said above, one interesting feature (that is somewhat bizarre to me), is the issue does not happen in a debug build - that may complicate debugging this in a debug build.

**Comment by gsjaardema** [comment]
The diff that broke` it is most likely line 4526 of `Iofx_DatabaseIO.C` where the `ex_update` call was removed.  Uncommenting this will give you a fragile fix as it relies on there being nodeset or sideset variables being output.  If there were no set variables, then this would not get hit and the file would not be flushed.  In other words, lucky that it worked before...

Adding the update back in does give you valid files at the end, so that is at least promising.  

I will need to do a debug build to see why the flushes and ex_close calls are not happening at other places or at the end of the run.  Should have something on Monday.

**Comment by gsjaardema** [comment]
Yes, makes sense that doesn't happen in debug build since there are sometimes more flushes in debug for some reason or even the extra time needed to run makes the OS do more flushing...

I think the debug run will be OK since I know what calls I am looking for and the call stacks.  Will definitely verify any fixes on an optimized run.

**Comment by ikalash** [comment]
Gotcha - thanks for the explanation.  Sounds good.

**Comment by gsjaardema** [comment]
I ran in the debugger and I do not see the destructors of any of the output code being run and the output files are never closed.  This is causing the issue as the data in the file is being buffered and unless the file is closed, there is no indication that the data should be buffered.

As mentioned above, it was probably "luck" that was causing this to work prior to the commit.  There used to be an explicit call to flush the data in the output of nodeset and/or sideset data and this analysis happened to output nodeset or sideset data and happened to call this output after the output of nodal and element data so everything would get flushed at the end of a timestep.  However, if there were no nodeset/sideset variables, then this flush would not get called and the data would not be written to disk.  Just luck that it was working in this case.

There is a mechanism to force a flush at the end of each timestep and that might help the situation, but I think that it would still be good to make sure that the destructors were called such that the file could be explicitly closed at the end of the run.  I was unable to see where they should be called from and why they weren't being called.  There may be some architectural reason why this isn't possible and, if so, we may have to look at another mechanism for closing the file(s) at the end of execution.

**Comment by gsjaardema** [comment]
After a closer look, the mechanism to force a flush at a specific number of steps (FLUSH_INTERVAL property) is only enabled for parallel runs; the serial runs rely on a time-based flushing interval.  

I have fixe this in the SEACAS github repository and will sync the capability over to Trilinos soon.  Albany will have to be modified to use this by setting the FLUSH_INTERVAL property to 1.  This can be done externally via an environment variable: `export IOSS_PROPERTIES="FLUSH_INTERVAL=1"` or by passing the `FLUSH_INTERVAL` property to the IOSS database IO constructor; probably through the STKMeshIoBroker constructor...

**Comment by ikalash** [comment]
Thanks @gsjaardema!  What is the syntax for passing the flush_interval property to the iOSs database constructor?  I'm thinking that might be cleaner than doing the export.

**Comment by gsjaardema** [comment]
It is similar to what is being done in `src/disc/stk/Albany_IossSTKMeshStruct.cpp` with the `mesh_data->property_add()` calls.  The property string would be `FLUSH_INTERVAL` and the value would be `1`.  

This will require a new version of Trilinos which I will be committing today or I can provide a patch.

**Comment by ikalash** [comment]
I am back in the office and have made the necessary changes to resolve the issue.  Thanks again @gsjaardema !
