### ISSUE TITLE
Xpetra: throw better error messages in constructors of stub implementations

### ISSUE THREAD

**Issue by tawiesn** [trilinos/Trilinos#549]
Add missing exceptions and improve existing error messages in all constructors of the stub implementations for disabled types. We forgot to add exceptions in some constructors.

It would be helpful to tell the user if he tries to create an object using disabled types and give a detailed error message with hints of what types have to be enabled in the Trilinos configuration.

**Comment by mhoemmen** [comment]
Does this relate to @DrBooom 's issue, possibly reported yesterday?

**Comment by tawiesn** [comment]
@mhoemmen Yes. But we had a similar issue with Zoltan2 a couple of weeks ago, too.

**Comment by mhoemmen** [comment]
Yay, thanks!
