### ISSUE TITLE
MueLu:  How to export aggregates for structured regionMG

### ISSUE THREAD

**Issue by mayrmt** [trilinos/Trilinos#5509]
## Question
@trilinos/muelu 

I'm trying to visualize the aggregates for a structured regionMG problem. Here's my command line expression to start the driver: 
```
mpirun -np 4 ./MueLu_StructuredRegionDriver.exe --linAlgebra=Tpetra --xml=structured_1dof.xml --matrixType=Star2D --nx=100 --ny=100 --smootherIts=1 --tol=100.0
```
I made some changes to the xml-file:
- In <ParameterList name="myAggregationFact">: set "aggregation: output type" to "Aggregates" (otherwise the AggregationExportFactory won't find a `Graph`).
- Include the list
    ````
    <ParameterList name="myAggExport">
      <Parameter name="factory"                             type="string" value="AggregationExportFactory"/>
      <Parameter name="Aggregates"                          type="string" value="myAggregationFact"/>
      <Parameter name="aggregation: output filename"        type="string" value="structured_aggs_level%LEVELID_proc%PROCID.out"/>
    </ParameterList>
    ```
    to define the aggregates export factory
- In <ParameterList name="TransferFactories"> in `<ParameterList name="myRAPFact">`: set "AggregationExportFactory" to "myAggExport" (this line is there, but has to be un-commented).

Then, I get the error message:
```
p=0: *** Caught standard std::exception of type 'MueLu::Exceptions::RuntimeError' :

 /ssd/codes/mayrmt_trilinos/src-trilinos/packages/muelu/src/MueCentral/MueLu_Level.hpp:208:
 
 Throw number = 1
 
 Throw test that evaluated to true: !IsAvailable(ename, fac)
 
 MueLu::Level::Get(): factory did not produce expected output. "prolongatorGraph" has not been generated by  MueLu::StructuredAggregationFactory
```

@lucbv How can I export visualization information for aggregates using structured aggregation in a regionMG setting? I could not find any examples in the repository. Many xml-file store a `<ParameterList name="myAggExport">` list, but it is always commented and never actually used.

**Comment by mayrmt** [comment]
I also looked into a pure structured example (without any region stuff). It's the same problem there. In essence, when using the `StructuredAggregationFactory` with "aggregation: output type" set to "Aggregates" as required by the `AggregationExportFactory`, then the `GeometricInterpolationPFactory` cannot access the "prolongatorGraph" (which is declared as a necessary input).

I understand, why the structured aggregation rather wants to deliver an "CrsGraph" as output than "Aggregates". However, this seems to be in conflict with MueLu's visualization capabilities.

@lucbv How do you visualize structured aggregats if at all? Do you see a way to fix this problem?

**Comment by lucbv** [comment]
@mayrmt the way to do this is to use the structured aggregation and ask for "Aggregates" as output instead of the CrsGraph. This means as you noticed that GeometricInterpolationPFactory is unhappy since it wants a graph but you can substitute it with TentativePFactory which will be happy with aggregates and will allow you to export things correctly.
At some point I will probably need to think about how the CrsGraph can be used to visualize aggregates but that's not a high priority at the moment...

**Comment by lucbv** [comment]
@mayrmt are you having some success exporting the aggregates with the tentative prolongator?

**Comment by mayrmt** [comment]
@lucbv I‘m done for today, but will look at it first thing tomorrow morning. I‘ll keep you posted.

**Comment by lucbv** [comment]
@mayrmt fair enough, I am adding a quick feature to the driver before going back to structured/unstructured, if I have time I will also add an example xml file that export the aggregates.

**Comment by mayrmt** [comment]
@lucbv Looking at the structured driver (no region stuff), I can export aggregates on level 0 and they look fine. I can also export them on level 1, but they coordinates seem to be weird. Maybe the coordinate transfer is not hooked up properly with the aggregate export factory.

**Comment by mayrmt** [comment]
@lucbv Aggregate export is also broken, if not running serial.

As an example, I used the structured driver with this command line:
```
mpirun -np 1 ./MueLu_Structured.exe --linAlgebra=Tpetra --xml=structured_1dof_export_aggs.xml --matrixType=Laplace2D --nx=25 --ny=25
```

The serial case:
![1proc](https://user-images.githubusercontent.com/14297653/61119143-81bbd400-a49a-11e9-9653-ab1083332902.png)

With 2 ranks:
![2procs](https://user-images.githubusercontent.com/14297653/61119151-854f5b00-a49a-11e9-83b1-cc3826670f02.png)

**Comment by mayrmt** [comment]
@lucbv Thanks for sharing your xml-files to export aggregates. I'll look into them to figure out, what I did wrong.

When I was trying to export aggregates, I looked through MueLu examples and tests, though I didn't find it to be used anywhere. How can we include the aggregate export into testing?

**Comment by lucbv** [comment]
@mayrmt actually the xml file was emailed by mistake... but I can send you the correct one if you want it?
Overall exporting the aggregates to paraview is a harder endeavour than one might expect, just look at these files: [MueLu_AggregationExportFactory](https://github.com/trilinos/Trilinos/blob/develop/packages/muelu/src/Utils/MueLu_AggregationExportFactory_def.hpp) and [MueLu_VizualizationHelpers](https://github.com/trilinos/Trilinos/blob/develop/packages/muelu/src/Utils/MueLu_VisualizationHelpers_def.hpp), to get an idea of what the code looks like.
I remember looking at these last year and fixing a few issues related to geometric processing and looking at the vtu files, I can already tell that some nodes are missing and probably wrongly discarded by the convex hull 3D function. At the moment fixing these does not seem critical but it might become more important if we want present these figures.

**Comment by lucbv** [comment]
Also regarding the testing of the aggregation export, the only solution I can think of is to run the code and compare the vtu files to some gold files and make sure that they are the same.
Of course that requires reproducibility of aggregation... but as long as we don't use any kokkos aggregation we should be fine.

**Comment by mayrmt** [comment]
@lucbv wrote:
>  actually the xml file was emailed by mistake... but I can send you the correct one if you want it?
Sure! It would be great if you could send me the file (or maybe upload it here). I want to visualise some aggregates in another context as well, so a working example will be really helpful.

I know, that the implementation is not "super clean" and we probably can spent quite some time on improving them. 😏 I agree that it's currently not our main focus, though.

Maybe I'll open a separate issue to keep track of problems and progress of these visualization tools. Regarding testing, I was also thinking about comparing vtu-files with some gold-files. However, even just running through the export factory and checking for successful completion would be a step forward as compared to the current status.

**Comment by lucbv** [comment]
@mayrmt first some eye candy:
![structured_unstructured_aggregates3D](https://user-images.githubusercontent.com/22935531/61393028-59a6e900-a87d-11e9-9431-a14240a753f4.png)
and [here](https://github.com/trilinos/Trilinos/files/3402843/structured_unstructured_1dof.xml.txt) is the xml file I use to generate this. If we get someone next summer we could look into this, I might talk to Ray and Jonathan about it.

**Comment by mayrmt** [comment]
I really like this picture! :smile:

**Comment by mayrmt** [comment]
Again regarding the testing of aggregate visualization: The VTU output is written to ASCII files, so performing a diff on these files should not be too hard.

**Comment by mayrmt** [comment]
Seems like @lucbv is able to export some aggregate visualisations, hence I close this issue for now.

At some point, we might want to rework the visualization factory, but let's save that for some later time.

**Comment by maxfirmbach** [comment]
While trying to prepare some nice pictures of aggregates using uncoupled and structured aggregation for a  student project, I ran into a problem. For both cases I start a serial run and store aggregates and try to visualize them with the `AggregationExportFactory` (my grid is just a 3D unit cube for a linear elasticity problem). For both cases and default parameters in the `AggregationFactories` I run into some kind of deadlock during the export, the .vtu file is created but nothing is written into it and MueLu starts to idle / or just does nothing (not sure). Actually for some parameter combinations it works, for others not (aggregation procedure goes through without ill formed aggregates in all of my tested cases).

So to me it seems like there's still a problem happening inside the 3D convex hull creation.
Might also be interesting for @mayrmt.

**Comment by cgcgcg** [comment]
@pohm01 Any idea?

**Comment by pohm01** [comment]
No idea. I poked around a little but wasn't able to get any structured aggregates (I kept running into an error for trying to build aggregates multiple times, which could be related...), but I was doing so on a very old version that is in a pretty sad state of chaos so that might just be a me problem.

Actually, I have a bad idea. You could try a fake hybrid aggregation but with no regions specified as unstructured (which luckily is the default). The eye candy aggregate picture in this issue has the xml to reference for trying to do that. I was able to get structured aggs from that xml for 3D Elasticity by changing "PDE equations" to 3 and "aggregation: coarsening rate" to "{3}". Hybrid handles aggregate info more like the unstructured aggregations, so it may help.
