### ISSUE TITLE
TpetraCore_MatrixMatrix_UnitTests_MPI_4 randomly failing in several ATDM Trilinos builds starting 2019-06-12

### ISSUE THREAD

**Issue by fryeguy52** [trilinos/Trilinos#5515]
## Bug Report
CC: @trilinos/tpetra, @kddevin (Trilinos Data Services Product Lead), @bartlettroscoe, @fryeguy52
 
<Checklist>
<???: Add label "ATDM">
<???: Add label "bug"?>
<???: Add label for affected packages (e.g. "MueLu", "Tpetra", "Kokkos", etc.)>
<???: Add milestone "Initial cleanup of new ATDM builds of Trilinos" or "Keep promoted ATDM builds of Trilinos clean">
<???: Once GitHub Issue is created, add entries for tests to TrilinosATDMStatus/*.csv files>
<???: Add label "PA: ???Project Area???" (e.g. "PA: Linear Solvers", "PA: Data Services")>
 
## Next Action Status
<status-and-or-first-action>
 
## Description
 
As shown in [this query](https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-&field2=testname&compare2=61&value2=TpetraCore_MatrixMatrix_UnitTests_MPI_4&field3=buildstarttime&compare3=83&value3=2019-06-12&field4=buildstarttime&compare4=84&value4=2019-07-12&field5=status&compare5=62&value5=Passed) the tests:
* TpetraCore_MatrixMatrix_UnitTests_MPI_4

is randomly failing in the builds:
* Trilinos-atdm-sems-rhel7-cuda-9.2-Volta70-complex-shared-release-debug
* Trilinos-atdm-waterman_cuda-9.2_fpic_static_opt
* Trilinos-atdm-waterman-cuda-9.2-opt
* Trilinos-atdm-sems-rhel7-intel-18.0.5-openmp-complex-shared-release-debug

from the test output:
```
3. Tpetra_MatMat_double_int_int_Kokkos_Compat_KokkosCudaWrapperNode_threaded_add_sorted_UnitTest ... :0: : block: [13,0,0], thread: [0,49,0] Assertion `View bounds error of view C colinds` failed.
```
## Current Status on CDash

The current status of this tests on all ATDM builds for the current testing day can be found [here](https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercount=4&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-&field2=testname&compare2=61&value2=TpetraCore_MatrixMatrix_UnitTests_MPI_4&field3=buildstarttime&compare3=83&value3=today&field4=buildstarttime&compare4=84&value4=tomorrow)

## Steps to Reproduce

One should be able to reproduce this failure on with a sems rhel6 environment as described in:
* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md

More specifically, the commands given for with a sems rhel6 environment are provided at:
* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#sems-rhel6-environment

The exact commands to reproduce this issue should be:
```
$ cd <some_build_dir>/
$ source $TRILINOS_DIR/cmake/std/atdm/load-env.sh Trilinos-atdm-sems-rhel7-cuda-9.2-Volta70-complex-shared-release-debug
$ cmake \
 -GNinja \
 -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
 -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_Tpetra=ON \
 $TRILINOS_DIR
$ make NP=16
$ ctest -j8
```

**Comment by bathmatt** [comment]
@kddevin @srajama1 This is a high priority issue for the EMPIRE team that was brought up at todays meeting, tagging another issue as well

**Comment by fryeguy52** [comment]
Here is an example of failure output:
```
3. Tpetra_MatMat_double_int_int_Kokkos_Compat_KokkosCudaWrapperNode_threaded_add_sorted_UnitTest ... :0: : block: [13,0,0], thread: [0,49,0] Assertion `View bounds error of view C colinds` failed.
```

**Comment by bartlettroscoe** [comment]
CC: @crtrott, @bathmatt, @srajama1 

It was just mentioned at the ATDM PM & PI meeting today that these tests were fixed (I think @srajama1).  [This query showing Assertion `View bounds error of view C colinds` failed.](https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&begin=2019-09-01&end=2019-09-30&filtercount=4&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-&field2=testname&compare2=61&value2=TpetraCore_MatrixMatrix_UnitTests_MPI_4&field3=status&compare3=61&value3=failed&field4=testoutput&compare4=97&value4=Assertion%20%60View%20bounds%20error%20of%20view%20C%20colinds%60%20failed.) shows the following failures in the last 30 days:


Site | Build Name | Test Name | Status | Time | Proc Time | Details | Build Time | Processors
-- | -- | -- | -- | -- | -- | -- | -- | --
sems-rhel7 | Trilinos-atdm-sems-rhel7-cuda-9.2-Volta70-complex-shared-release-debug | TpetraCore_MatrixMatrix_UnitTests_MPI_4 | Failed | 22s 340ms | 1m 29s 360ms | Completed (Failed) | 2019-09-04T04:33:23 MDT | 4
sems-rhel7 | Trilinos-atdm-sems-rhel7-cuda-9.2-Volta70-complex-shared-release-debug | TpetraCore_MatrixMatrix_UnitTests_MPI_4 | Failed | 19s 250ms | 1m 17s | Completed (Failed) | 2019-09-19T04:33:27 MDT | 4

The last failure is as recent as 2019-09-19.  NOTE: This is not a Power9 machine.

Does this mean that this Trilinos test is still manifesting this error also seen in EMPIRE?  Or is this not related?

**Comment by srajama1** [comment]
@bartlettroscoe I didn't say this test was fixed. I was saying we don't know if this test failure is even related to EMPIRE failure. @trillinos/tpetra @kddevin

**Comment by bartlettroscoe** [comment]
According to [this query](https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&date=2020-01-11&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-&field2=testname&compare2=61&value2=TpetraCore_MatrixMatrix_UnitTests_MPI_4) and [this query](https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&begin=2019-12-01&end=2020-01-11&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-&field2=testname&compare2=61&value2=TpetraCore_MatrixMatrix_UnitTests_MPI_4&field3=buildstarttime&compare3=83&value3=today&field4=buildstarttime&compare4=84&value4=tomorrow&field5=status&compare5=61&value5=failed), all of the `TpetraCore_MatrixMatrix_UnitTests_MPI_4` tests have passed in all of the ATDM Trilinos builds since 2019-12-01.

Not sure when these got fixed but closing as complete.
