### ISSUE TITLE
Seacas:  Ioss defines `FMT_FALLTHROUGH` to be gcc's attribute even if using intel

### ISSUE THREAD

**Issue by bartgol** [trilinos/Trilinos#5524]
Note: not really a bug, but I didn't know how to mark it.

## Bug Report
@trilinos/\<seacas\>

### Description
In `ioss/src/fmt/format-inl.h` you see the following snippet:

```
#if FMT_CLANG_VERSION
#define FMT_FALLTHROUGH [[clang::fallthrough]];
#elif FMT_GCC_VERSION >= 700
#define FMT_FALLTHROUGH [[gnu::fallthrough]];
#else
#define FMT_FALLTHROUGH
#endif
```
This ends up defining `FMT_FALLTHROUGH` to be the gcc attribute even when using intel compilers (if gcc version is >= 7.0.0), which causes a warning.

A better way to handle this would be to check for intel compilers before resorting to gcc. In other words, check whether `__INTEL_COMPILER` is defined (and larger than 1800)  _before_ checking GCC's version; if positive, use intel 18+ version of the fallthrough attribute.

### Steps to Reproduce
1. SHA1:  c38dd12

Enable SeacasIoss and compile with intel compilers that use gcc > 7.0.0.

**Edit**: it seems that, despite saying it is supported on the intel online manuals, the attribute `[[fallthrough]]` is not supported by intel 18 or 19 (I tried 18.1 and 19.3). I guess in this case the best thing to do would be to simply define `FMT_FALLTHROUGH` to be empty in case of intel compiler, and let the user decide what to do with un-handled fallthrough warnings.

**Comment by mhoemmen** [comment]
@trilinos/seacas

**Comment by gsjaardema** [comment]
Yes.  I have fixed this in the seacas github buy it has not yet been synced over to trilinos.  Will try to do that in the next week

**Comment by bartgol** [comment]
Great! I'm closing this then. Thanks for the quick reply!
