### ISSUE TITLE
panzer:  passing in list of variables names with space separation for MMS not working

### ISSUE THREAD

**Issue by glhenni** [trilinos/Trilinos#5530]
## Bug Report
@trilinos/\<panzer\>

### Description
In charon we read in a section of XML that looks like:
```xml
    <ParameterList name="Global MMS Parameters">

      <ParameterList name="Global Statistics">
	<Parameter name="Value" type="string" value="ELECTRIC_POTENTIAL, ELECTRON_DENSITY, HOLE_DENSITY"/>
      </ParameterList>
    </ParameterList>
```
The `Value` string gets passed in via a parameter list to the ctor `panzer::GloablStatistics<EvalT, Traits>()`. Within that ctor the string gets pulled out of the parameter list into a std::string and is used in an invocation of `panzer::StringTokenizer(returnTokes, inp_string). That invocation uses the default arguments such that only a comma can be used as a delimiter and leading and trailing space is not stripped, therefore, at some point the code complains about a lack of evaluator for " ELECTRON_DENSITY". It's including that leading whitespace in the field name and that causes an error since the correct field name does not include that leading space.

For now we're just insuring that we don't have spaces in that particular variable list in the input file. That alleviates the problem.

**Comment by rppawlo** [comment]
Thanks for reporting @glhenni !
