### ISSUE TITLE
ROL: Duplicate ROL_FunctionBindings.hpp results in numerous build errors

### ISSUE THREAD

**Issue by etphipp** [trilinos/Trilinos#5535]
@trilinos/rol 

Building against a Trilinos install tree and including a file such as ROL_DynamicObjectiveCheck.hpp results in numerous build errors along the lines of
```
/home/etphipp/project/atdm/sparc/Trilinos/install/opt_mpi_openmp_clang_shared/include/ROL_Objective_CheckInterface.hpp:70:3: error: 
      unknown type name 'f_update_t'
  f_update_t<Real> update() {
```
It appears that the issue is there are two different files with the name ROL_FunctionBindings.hpp:

https://github.com/trilinos/Trilinos/blob/develop/packages/rol/src/utils/ROL_FunctionBindings.hpp
https://github.com/trilinos/Trilinos/blob/develop/packages/rol/src/utils/function_bindings/ROL_FunctionBindings.hpp

Only the second one defines `f_update_t`.  In my install tree, only the first one appears, which I believe is the source of the problem.

**Comment by dridzal** [comment]
@gregvw , which one should be used?

**Comment by etphipp** [comment]
I assume it must be the latter one.  If I replace the one in my install tree with it, everything seems to work (or at least compile).
