### ISSUE TITLE
Tpetra: Build errors with deprecated code off

### ISSUE THREAD

**Issue by tjfulle** [trilinos/Trilinos#5536]
## Bug Report
@trilinos/tpetra 

I am seeing a bunch of errors when trying to compile with deprecated code off.
 
My configuration is the following:
 
```console
$ cmake \
  -G "Ninja" \
  -D Trilinos_ENABLE_Tpetra:BOOL=ON \
  -D Trilinos_CONFIGURE_OPTIONS_FILE:FILEPATH=$TRILINOS_DIR/cmake/std/PullRequestLinuxCommonTestingSettings.cmake \
  -DTpetra_ENABLE_DEPRECATED_CODE:BOOL=OFF \
  $TRILINOS_DIR
 ```

Using this configuration results in configuration errors:
 
```console
-- Xpetra: Enabling deprecated code
-- Xpetra support for 32 bit Epetra enabled.
--    Xpetra_Epetra_NO_32BIT_GLOBAL_INDICES=OFF
CMake Error at packages/xpetra/CMakeLists.txt:146 (MESSAGE):
  If Xpetra Epetra support is enabled and Epetra 32-bit global indices are
  enabled, Xpetra requires that you enable Tpetra_INST_INT_INT
 ```

Okay, I’ll add `Tpetra_INST_INT_INT=ON` to the configuration.  This leads to compile time errors in STK – STK requires Tpetra’s GO=long long.  Why does STK check at compile time and not in cmake?
 
Okay, I’ll add `Trilinos_ENABLE_STK=OFF`.  This leads to compile time errors:
 
```console
Trilinos/develop/packages/xpetra/src/Map/Xpetra_TpetraMap_decl.hpp:240:37: error: ‘const class Tpetra::Map<int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial> >’ has no member named ‘clone’
       return toXpetraNonConst(map_->clone(node2));
 ```
  
I figured I could take a standard configuration and add `Tpetra_ENABLE_DEPRECATED_CODE=OFF` and have it “just work”.  That’s clearly not the case.
 
Are there known workarounds, or are these cases we haven’t seen/fixed yet?  I’m happy to look in to fixing, just don’t want to if these are known problems and/or have other fixes.

**Comment by csiefer2** [comment]
The deprecated code off nightlies are clean:

**Comment by tjfulle** [comment]
@csiefer2 that is only for `Trilinos_ENABLE_Tpetra`.  If you enable all downstream code, then you run in to problems.

**Comment by mhoemmen** [comment]
It works if you disable Epetra support in Xpetra, MueLu, and Amesos2.  `Xpetra_ENABLE_Epetra=OFF` etc.

**Comment by tjfulle** [comment]
@mhoemmen - all of Tpetra's downstream packages compile with `Tpetra_ENABLED_DEPRECATED_CODE=OFF` if Epetra support is disabled or just this `Xpetra` issue?  I seem to have gotten past `Xpetra` (see #5537) - now I'm on to ROL (#5540)

**Comment by mhoemmen** [comment]
@tjfulle I haven't tested ROL that way, but I've had success setting `Tpetra_ENABLE_DEPRECATED_CODE=OFF` all the way through MueLu and Stokhos.

**Comment by tjfulle** [comment]
Superseded by #5602
