### ISSUE TITLE
Xpetra: inconsistent declaration of TpetraMap::clone

### ISSUE THREAD

**Issue by tjfulle** [trilinos/Trilinos#5537]
## Bug Report
@trilinos/xpetra 

### Description
The deprecated `Xpetra::TpetraMap<>::clone` is declared in `xpetra/src/Map/Xpetra_TpetraMap_decl.hpp` guarded by `#ifdef XPETRA_ENABLE_DEPRECATED_CODE` but defined in `xpetra/src/Map/Xpetra_TpetraMap_def.hpp` guarded by `#ifdef TPETRA_ENABLE_DEPRECATED_CODE`.  The `clone` method is later called in `packages/xpetra/sup/Cloner/Xpetra_Cloner.hpp` but is guarded only by `#ifdef XPETRA_HAVE_TPETRA`.  The inconsistency causes build errors (#5536).

I have a potential fix building right now.  It

- replaces `#ifdef XPETRA_ENABLE_DEPRECATED_CODE`  in `xpetra/src/Map/Xpetra_TpetraMap_decl.hpp` with `#ifdef TPETRA_ENABLE_DEPRECATED_CODE`
- replaces `#ifdef XPETRA_HAVE_TPETRA` in `packages/xpetra/sup/Cloner/Xpetra_Cloner.hpp` with `#if defined(XPETRA_HAVE_TPETRA) && defined(TPETRA_ENABLE_DEPRECATED_CODE)`

The build seems to get by this error but fails at MueLu now...

**Comment by jhux2** [comment]
@william76 is this something you could have a look at?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by tjfulle** [comment]
@jhux2, I have a whole bevy of foxes for building with/without Tpetra deprecated code, including a fix for this.

**Comment by tjfulle** [comment]
This should be closed by #5750

**Comment by william76** [comment]
@tjfulle Just checking in, was this issue ever fixed?
