### ISSUE TITLE
STK: compile time error that could be configure time

### ISSUE THREAD

**Issue by tjfulle** [trilinos/Trilinos#5541]
## Bug Report

The following logic in `packages/stk/stk_balance/stk_balance/internal/balanceTypes.hpp` can be moved to CMake and be caught at configure time.

```
#if defined(HAVE_TPETRA_INST_INT_LONG_LONG)
typedef long long BalanceGlobalNumber;
#elif defined(HAVE_TPETRA_INST_INT_LONG)
typedef long BalanceGlobalNumber;
#else
#error "stk_balance requires that Tpetra instantiate either long or long-long."
#endif
```

**Comment by alanw0** [comment]
Yes I agree with this, we will figure out how to put this check in a cmake file.
Thanks!
