### ISSUE TITLE
Tpetra: Make it possible to Import/Export a RowGraph into a CrsGraph

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#555]
@kddevin writes:

> I would like to redistribute a Tpetra::RowGraph into a new Tpetra::CrsGraph.
> 
> To distribute a Tpetra::RowMatrix into a new Tpetra::CrsMatrix, we can use CrsMatrix::doImport, as both CrsMatrix and RowMatrix are SrcDistObject and, thus, the RowMatrix source can be the first argument of CrsMatrix::doImport.
> 
> But for RowGraph, we cannot use CrsGraph::doImport, as RowGraph is not a SrcDistObject, even though CrsGraph, RowMatrix, and CrsMatrix are all SrcDistObject.
> 
> Why isn't RowGraph a SrcDistObject?  Is there a better way to do the redistribution?

CrsGraph's implementation of DistObject methods (in particular, checkSizes, copyAndPermute, and packAndPrepare) all use the RowGraph interface.  Furthermore, RowGraph implements Packable.  Thus, all we need to do is make RowGraph inherit from SrcDistObject.

This is TRIVIAL since SrcDistObject implements no methods other than a virtual destructor.  Would you like to do it?

**Comment by maherou** [comment]
Just to add historical context:  The reason for the "Src" in SrcDistObject, starting with Epetra was to support this kind of feature.  Just FYI.

**Comment by mhoemmen** [comment]
@maherou Thanks Mike!  We added SrcDistObject to Tpetra, imitating Epetra, for this very reason.

@kddevin Do you actually have a RowGraph that is not a CrsGraph?  If so, I would like to use it for the text.  It's true that the fix is trivial, but the test is not.  (I can't just use CrsGraph as the source object, since the target object (the `*this` of the doExport or doImport call) attempts to cast the source object to CrsGraph.  This has a faster interface than RowGraph.)

**Comment by kddevin** [comment]
Thanks, @mhoemmen .  I can try to make the trivial change, following the example of RowMatrix.

No, sorry, we don't have our own RowGraph.  In our tests, we get the CrsGraph from CrsMatrix::getGraph() and cast it up to RowGraph.  That's probably why our tests compile, but I don't think they would work for anyone not using an underlying CrsGraph.  In Ifpack2, we get the RowGraph from RowMatrix::getGraph(). 

By chance, is there anything crazy in Trilinos like a Tpetra::RowMatrix built on an Epetra_CrsMatrix?  Or on a PETSc matrix?  Anything besides Tpetra::CrsMatrix that inherits from Tpetra::RowMatrix?  We could use any of those for testing.

**Comment by kddevin** [comment]
After talking with @amklinv , I think we'll do the following:
-  If we can cast the input RowGraph to a CrsGraph, we'll do the redistribution into a CrsGraph.
-  If the cast does not work, we will throw an error saying we cannot redistribute the RowGraph.

@amklinv  said users who wrap their own data structures with Tpetra::RowGraph or Tpetra::RowMatrix would be unlikely to want a Tpetra::CrsMatrix or Tpetra:CrsGraph after redistribution.  They likely would want to use their own interfaces, rather than Tpetra::RowMatrix/RowGraph interfaces, to manipulate the redistributed matrices/graphs.  

With this decision, no changes will be needed in RowGraph.  I'll close the issue.
Thanks, all and especially @amklinv, for your help.

**Comment by mhoemmen** [comment]
> By chance, is there anything crazy in Trilinos like a Tpetra::RowMatrix built on an Epetra_CrsMatrix? Or on a PETSc matrix? Anything besides Tpetra::CrsMatrix that inherits from Tpetra::RowMatrix? We could use any of those for testing.

Ifpack2::Details::OverlappingRowGraph inherits from Tpetra::RowGraph, but not Tpetra::CrsGraph.  It's a bit of a disaster though, given #438 and #558.

**Comment by mhoemmen** [comment]
Hi @kddevin !  I think it's OK to leave this issue open.  I'll just mark it as an "enhancement" (lower priority).

Best way to test this would be to write a custom graph class that inherits from Tpetra::RowGraph.  The implementation would store pairs of global indices `(i_gbl, j_gbl)` on each process.  It would only offer access by copy, not by view.

This would be a way to solve the outstanding issue of poor performance and high memory usage of Tpetra::CrsGraph::globalAssemble.

**Comment by mhoemmen** [comment]
The main work here is writing the test.  The change itself is not hard.

> Best way to test this would be to write a custom graph class that inherits from Tpetra::RowGraph. The implementation would store pairs of global indices (i_gbl, j_gbl) on each process. It would only offer access by copy, not by view.

**Comment by mhoemmen** [comment]
@ambrad mentioned just now that fixing this could also help with Ifpack2::RILUK setup.

**Comment by mhoemmen** [comment]
Actually, an easier test would be to write a RowGraph subclass that _wraps_ a CrsGraph, using the CrsGraph to implement RowGraph methods.
