### ISSUE TITLE
Auto-tester: GPU builds (Ride?) are not starting

### ISSUE THREAD

**Issue by lucbv** [trilinos/Trilinos#5550]
@william76  @jwillenbring @nmhamster 

## Bug Report
@trilinos/framework 

### Description
Looking at the pull requests of the day I notice that none of them are performing the CUDA build. This is preventing code from being checked in...
Is there a sense that this is a hardware or a software problem?

**Comment by nmhamster** [comment]
@lucbv - issue with Ride is under investigation.

**Comment by lucbv** [comment]
Thanks for the info @nmhamster

**Comment by lucbv** [comment]
I see things are back to working fine now so I'm closing this : )

**Comment by nmhamster** [comment]
@lucbv - I believe Ride is available for use. Can you or @william76 / @jwillenbring confirm we are good? Thanks.

**Comment by nmhamster** [comment]
@lucbv - oops my browser hadn't refreshed, looks like things are good. Thanks!
