### ISSUE TITLE
MueLu: reorganization of the Graph subdirectory in MueLu

### ISSUE THREAD

**Issue by lucbv** [trilinos/Trilinos#5564]
## Enhancement
@trilinos/muelu 
@jhux2 @csiefer2 @cgcgcg @rstumin 

I would like to reorganize the `muelu/src/Graph` directory in a more coherent way so that browsing the code tree to find a feature is a little easier.

Here is the current directory structure:
```
muelu/src/Graph/
            |
            |---  BrickAggregation/
            |---  HybridAggregation/
            |---  StructuredAggregation/
            |---  UncoupledAggregation/
            |---  UserAggregation/
```
plus a whole lot of files regarding Graph data structured, coupled aggregation, matrix drop and amalgamation of various flavors.
I would like to move to the following structured:
```
muelu/src/Graph/
            |
            |---  BrickAggregation/
            |---  Containers/
            |---  CoupledAggregation/
            |---  HybridAggregation/
            |---  MatrixTransformation/
            |---  StructuredAggregation/
            |---  UncoupledAggregation/
            |---  UserAggregation/
            |---  MueLu_AggregationAlgorithmBase.hpp
            |---  MueLu_AggregationAlgorithmBase_kokkos.hpp
```
This structure tries to group classes by type of work performed and also pulls the AggregationAlgorithmBase out of the UncoupledAggregation as these are could be used by all types of aggregation.

Let me know what you think of this, I will create a PR with the changes for all to look at.

**Comment by mhoemmen** [comment]
Will this address #5557?

**Comment by lucbv** [comment]
@mhoemmen no this is just cleaning up some stuffs that bother me a bit... unrelated to #5557
