### ISSUE TITLE
Tpetra:  tsqr configure dependencies causing build errors with Trilinos_ENABLE_ALL_OPTIONAL_PACKAGES=OFF

### ISSUE THREAD

**Issue by kddevin** [trilinos/Trilinos#557]
@trilinos/tpetra @trilinos/zoltan2 @MicheldeMessieres @krcb

**Comment by mhoemmen** [comment]
Wait, what's this all about?  Was this not an issue then?

**Comment by kddevin** [comment]
It seems to be a cdash issue; we cannot reproduce it with outside cdash.  Sorry for the noise.

**Comment by mhoemmen** [comment]
No need for apologies!  Just wanted to see if it was something needing fixing.
