### ISSUE TITLE
Tpetra_CrsMatrix_def.hpp exposes "using Teuchos::rcpFromRef" in global namespace

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#5572]
## Bug Report
@trilinos/tpetra @tjfulle 

### Description

Line 84 of `Tpetra_CrsMatrix_def.hpp` exposes `using Teuchos::rcpFromRef;` in the global namespace.  This is bad if ETI is OFF, because it means that downstream packages and applications will see the resulting `using` declaration in their global namespace.

**Comment by tjfulle** [comment]
The strange thing is, everywhere `rcpFromRef` Is actually used in the file, it is either namespace qualified, or the `using` declaration is included locally in the function using it.

**Comment by mhoemmen** [comment]
begone autobot
