### ISSUE TITLE
Xpetra:  BlockedMultiVector build errors with ETI off

### ISSUE THREAD

**Issue by vbrunini** [trilinos/Trilinos#5591]
## Bug Report
@trilinos/Xpetra

### Description
Xpetra fails to build with ETI disabled. There are a large number of errors similar to:

```
[1720/2591] Building CXX object packages/xpetra/src/CMakeFiles/xpetra.dir/MultiVector/Xpetra_EpetraMultiVectorFactory.cpp.o
FAILED: packages/xpetra/src/CMakeFiles/xpetra.dir/MultiVector/Xpetra_EpetraMultiVectorFactory.cpp.o 
In file included from packages/xpetra/src/Xpetra_BlockedMultiVector.hpp:2:0,
                 from /scratch/vebruni/src/Trilinos/packages/xpetra/src/MultiVector/Xpetra_MultiVectorFactory_def.hpp:50,
                 from packages/xpetra/src/Xpetra_MultiVectorFactory.hpp:2,
                 from /scratch/vebruni/src/Trilinos/packages/xpetra/src/BlockedMultiVector/Xpetra_BlockedMultiVector_decl.hpp:58,
                 from packages/xpetra/src/Xpetra_BlockedMultiVector.hpp:1,
                 from /scratch/vebruni/src/Trilinos/packages/xpetra/src/MultiVector/Xpetra_EpetraMultiVectorFactory.cpp:47: 
/scratch/vebruni/src/Trilinos/packages/xpetra/src/BlockedMultiVector/Xpetra_BlockedMultiVector_def.hpp:56:1: error: 'BlockedMultiVector' does not name a type; did you mean 'TpetraMultiVector'?
 BlockedMultiVector<Scalar, LocalOrdinal, GlobalOrdinal, Node>::
 ^~~~~~~~~~~~~~~~~~
 TpetraMultiVector
```

**Comment by mhoemmen** [comment]
@trilinos/muelu @trilinos/xpetra This is probably related to recent efforts to improve Xpetra's ETI.  The end result will be good, but we have to struggle a bit through the process :-)

**Comment by csiefer2** [comment]
@william76

**Comment by jhux2** [comment]
@vbrunini Could you please post your cmake script?

**Comment by jhux2** [comment]
@trilinos/xpetra

**Comment by vbrunini** [comment]
For the cmake script see https://github.com/trilinos/Trilinos/issues/5148 and turn off ETI (though I'm guessing @william76 was able to reproduce this already based on the issue traffic).

As an aside, it would be really nice to get an automated build using that configure script (which is the Sierra configuration of Trilinos right now) added as a CI or nightly Trilinos build if possible.

**Comment by mhoemmen** [comment]
@trilinos/framework See Victor's remark above.

**Comment by william76** [comment]
@vbrunini I merged in my fix today that should address this error, but I'm not 100% sure since I wasn't able to exactly match your configuration that you noted in #5148 ... when you have a chance can you send me a list of what modules you guys load and other environment stuff, preferably modules that are available on cee-compute systems?
When you get a chance, can you see if you can kick off a re-run of the test you had failing and post here if it's fixed or if there's more that needs fixing =)

**Comment by vbrunini** [comment]
Looks like your fix did the trick for the Xpetra issues. Found a small ifpack2 issue as well that I just submitted PR #5638 for and with that I got a successful build.

**Comment by william76** [comment]
@vbrunini awesome! Thanks for checking =)
