### ISSUE TITLE
Galeri: build fails with Epetra disabled

### ISSUE THREAD

**Issue by tjfulle** [trilinos/Trilinos#5593]
## Bug Report
@trilinos/galeri 

With `Trilinos_ENABLE_Epetra:BOOL=OFF` defined, I get the following build errors:

```
packages/galeri/src-xpetra/../src-epetra/Galeri_Maps.h:47:10: fatal error: Epetra_ConfigDefs.h: No such file or directory
 #include "Epetra_ConfigDefs.h"
```

Full configure script:

```
/projects/sems/install/rhel6-x86_64/sems/utility/cmake/3.12.2/bin/cmake \
  -G "Ninja" \
  -D Trilinos_CONFIGURE_OPTIONS_FILE:FILEPATH=$TRILINOS_DIR/cmake/std/PullRequestLinuxCommonTestingSettings.cmake \
  -D Trilinos_ENABLE_Tpetra:BOOL=ON \
  -D Trilinos_ENABLE_Epetra:BOOL=OFF \
  -D Trilinos_ENABLE_Moertel:BOOL=OFF \
  -D Trilinos_ENABLE_ShyLU_DDFROSch:BOOL=OFF \
  -D Trilinos_ENABLE_Stokhos:BOOL=OFF \
  -D ROL_ENABLE_EXAMPLES:BOOL=OFF \
  -D Tpetra_ENABLE_DEPRECATED_CODE:BOOL=OFF \
  -D Xpetra_ENABLE_DEPRECATED_CODE:BOOL=OFF \
  $TRILINOS_DIR
```

**Comment by lucbv** [comment]
@tjfulle do you know which file required `src-epetra/Galeri_Maps.h` ?
The `src-epetra` directory is not supposed to be added by CMake when Epetra is off...

I will do a local build and look at this problem.

**Comment by tjfulle** [comment]
@lucbv, the file is in the first comment.  I looked at this a year or so ago, but the issue ran deeper than the single file.  With Tpetra’s code deprecation, this now needs to be resolved

**Comment by lucbv** [comment]
@tjfulle I am actually looking for the file that includes the file you mention.
I am ready for my local build, are you using any particular modules to test this?
I ususally load the modules associated with the auto-tester build for gcc/7.2.0 located here: `cmake/std/sems/PullRequestGCC7.2.0TestingEnv.sh`

**Comment by tjfulle** [comment]
Ya, that’s the environment I source.  Warning: the configuration options in `Trilinos_CONFIGURE_OPTIONS_FILE` enable all downstream code from Tpetra and build times are horrendous.  You might just want to disable Epetra and disable Galeri

**Comment by lucbv** [comment]
No I'm good, I already arrived at the error so that's fine.
I think the problem might actually be simple enough, it seems that some examples that require Epetra are not guarded properly.

**Comment by tjfulle** [comment]
@lucbv #1033 is another, related, issue.

**Comment by lucbv** [comment]
@tjfulle I think my build is passing Galeri but now fails in Domi.
I will disable it and see if it goes all the way through, but in my opinion the galeri issue is resolved.

**Comment by tjfulle** [comment]
Dome fails to build if Tpetra deprecated code is disabled.  Sigh...

**Comment by lucbv** [comment]
@tjfulle see PR #5593 above, I think it should do the trick.
Of course I could not get things to build completely with Tpetra deprecated code off, however I am able to compile everything with Epetra=OFF now.
Hopefully this is good enough for your needs?

**Comment by tjfulle** [comment]
Thanks @lucbv!

**Comment by lucbv** [comment]
@tjfulle the PR merged so you should be able to test this.
Let me know how it goes and we might be able to close this issue and #1033 : )

**Comment by tjfulle** [comment]
Looks good on my end.  I did not try installing Trilinos, so I can't say that #1033 is also resolved.
