### ISSUE TITLE
MueLu: tests  fail to build if Galeri is disabled

### ISSUE THREAD

**Issue by tjfulle** [trilinos/Trilinos#5595]
## Bug Report
@trilinos/muelu 

### Description
Many MueLu tests fail to build if `Trilinos_ENABLE_Galeri:BOOL=OFF` is defined.

Related to #5590

**Comment by jhux2** [comment]
@tjfulle I will take this.

**Comment by jhux2** [comment]
@tjfulle This was a simple fix.  PR is in.

**Comment by jhux2** [comment]
This was already fixed in head:
 https://github.com/trilinos/Trilinos/blob/0193ca84a98452528343e362b77a0f61ee757ac3/packages/muelu/example/basic/CMakeLists.txt#L18

I will leave this open until you verify it works for you.

**Comment by tjfulle** [comment]
Thanks @jhux2!  I think it is working.  I'll leave it open a while longer until the other MueLu work related #5602 is finished.

**Comment by cgcgcg** [comment]
Since we have made Galeri a required dependency for MueLu's tests, this is fixed.
https://github.com/trilinos/Trilinos/blob/6e5c6c9586ccd0b63855c5fd9789a386d85a6a9c/packages/muelu/cmake/Dependencies.cmake#L6
