### ISSUE TITLE
SEACAS:  builds failures in ATDM waterman and cee-rhel6 builds

### ISSUE THREAD

**Issue by fryeguy52** [trilinos/Trilinos#5611]
## Bug Report
CC: @trilinos/seacas, @kddevin (Trilinos Data Services Product Lead), @bartlettroscoe, @gdsjaar 
 
## Next Action Status
<status-and-or-first-action>
 
## Description
 
As shown in [this query](https://testing.sandia.gov/cdash/index.php?project=Trilinos&date=2019-07-30&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=63&value1=Trilinos-atdm-&field2=buildstarttime&compare2=83&value2=2019-07-29&field3=buildstarttime&compare3=84&value3=2019-07-30&field4=builderrors&compare4=43&value4=0&field5=builderrors&compare5=44&value5=50) the builds:
* Trilinos-atdm-cee-rhel6_clang-5.0.1_openmpi-1.10.2_serial_static_opt
* Trilinos-atdm-cee-rhel6_gnu-7.2.0_openmpi-1.10.2_serial_shared_opt
* Trilinos-atdm-cee-rhel6_intel-17.0.1_intelmpi-5.1.2_serial_static_opt
* Trilinos-atdm-cee-rhel6_intel-18.0.2_mpich2-3.2_openmp_static_opt
* Trilinos-atdm-sems-rhel7-cuda-9.2-Volta70-complex-static-release-debug
* Trilinos-atdm-waterman_cuda-9.2_fpic_static_opt
* Trilinos-atdm-waterman_cuda-9.2_shared_opt
* Trilinos-atdm-waterman-cuda-9.2-debug
* Trilinos-atdm-waterman-cuda-9.2-opt
* Trilinos-atdm-waterman-cuda-9.2-rdc-release-debug
* Trilinos-atdm-waterman-cuda-9.2-release-debug

Have been failing to build seacas since 2019-07-26

Output shows:
```
/home/jenkins/waterman/workspace/Trilinos-atdm-waterman-cuda-9.2-release-debug/SRC_AND_BUILD/Trilinos/packages/seacas/libraries/ioss/src/cgns/Iocgns_ParallelDatabaseIO.C:60:2: error: #error "At this time, CGNS must be patched using CGNS-sandia.patch; contact gdsjaar@sandia.gov for info"
 #error                                                                                             \
  ^~~~~
```

## Current Status on CDash

The current status of thesebuilds for the current testing day can be found at:

[current day's builds on waterman](https://testing.sandia.gov/cdash/index.php?project=Trilinos&date=2019-07-30&filtercount=4&showfilters=1&filtercombine=and&field1=buildname&compare1=63&value1=Trilinos-atdm-&field2=buildstarttime&compare2=83&value2=yesterday&field3=buildstarttime&compare3=84&value3=today&field4=buildname&compare4=63&value4=waterman)
[current day's builds on cee-rhel6](https://testing.sandia.gov/cdash/index.php?project=Trilinos&date=2019-07-30&filtercount=4&showfilters=1&filtercombine=and&field1=buildname&compare1=63&value1=Trilinos-atdm-&field2=buildstarttime&compare2=83&value2=yesterday&field3=buildstarttime&compare3=84&value3=today&field4=buildname&compare4=63&value4=cee-rhel6)

## Steps to Reproduce

One should be able to reproduce this failure on waterman as described in:
* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md

More specifically, the commands given for waterman are provided at:
* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#waterman

The exact commands to reproduce this issue should be:
```
$ cd <some_build_dir>/
$ source $TRILINOS_DIR/cmake/std/atdm/load-env.sh Trilinos-atdm-waterman-cuda-9.2-debug
$ cmake \
 -GNinja \
 -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
 -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_SEACAS=ON \
 $TRILINOS_DIR
$ make NP=16
$ bsub -x -Is -n 20 ctest -j20
```

**Comment by bartlettroscoe** [comment]
This is better explained in [SPAR-589](https://sems-atlassian-srn.sandia.gov/browse/SPAR-589) and was resolved by PR #5597.   You can see thse builds were clean of build errors [yesterday on CDash](https://testing-dev.sandia.gov/cdash/index.php?project=Trilinos&date=2019-08-01&filtercount=2&showfilters=1&filtercombine=or&field1=buildname&compare1=65&value1=Trilinos-atdm-cee-rhel6&field2=buildname&compare2=65&value2=Trilinos-atdm-waterman).

Thanks to @gsjaardema for getting this fixed once he was alerted to the issue!

NOTE: This took down all testing of SPARC 'master' + Trilinos 'develop' for several days and obscured other changes to Trilinos that broke SPARC as well (see [SPAR-593](https://sems-atlassian-srn.sandia.gov/browse/SPAR-593)).

Closing as complete.
