### ISSUE TITLE
Zoltan2: Test failures with Tpetra deprecated code disabled

### ISSUE THREAD

**Issue by tjfulle** [trilinos/Trilinos#5615]
## Bug Report
@trilinos/zoltan2

Part of: #5602 
### Description

With Tpetra's deprecated code disabled, many Zoltan2 tests fail for `GlobalOrdinal=[int,long long int]`

-  Zoltan2_GraphModel2ndAdjsFromAdjs_MPI_4
-  Zoltan2_Metric_MPI_4
-  Zoltan2_TaskMapper_MPI_4
-  Zoltan2_TaskMappingProblemTest_MPI_4
-  Zoltan2_componentMetrics_MPI_4
-  Zoltan2_pamgenMeshAdapterTest_ghosthg_MPI_4
-  Zoltan2_simplePamgenTest_MPI_3

See the full configuration for `GlobalOrdinal=int` at https://github.com/trilinos/Trilinos/issues/5602#issuecomment-516593697

See the full configuration for `GlobalOrdinal=long long int` at: https://github.com/trilinos/Trilinos/issues/5602#issuecomment-516594843

Note: if you work off of the Trilinos develop branch, you will likely get build errors using the above linked configurations.  The branch tjfulle:issue-5536 is currently working.

**Comment by tjfulle** [comment]
@kddevin I believe #5645 fixes this, right?

**Comment by kddevin** [comment]
@tjfulle Yes, I expect that it does.  Let me know if you see different results.
