### ISSUE TITLE
ShyLU: build failures with Tpetra's deprecated code disabled

### ISSUE THREAD

**Issue by tjfulle** [trilinos/Trilinos#5618]
## Bug Report
@trilinos/shylu 

Part of: #5602 

### Description

With Tpetra's deprecated code disabled, ShyLU fails to build with the configuration at `GlobalOrdinal=long long int` at: https://github.com/trilinos/Trilinos/issues/5602#issuecomment-516594843 (removing the lines disabling ShyLU, of course)

The build failure could be due to `GlobalOrdinal=long long int`, or Epetra being disabled?

**Comment by tjfulle** [comment]
@kddevin could you assign the Tpetra team member that was going to look in to this?

**Comment by brian-kelley** [comment]
See fix in #5650.
