### ISSUE TITLE
Cdash Trilinos_ENABLE_ALL_OPTIONAL_PACKAGES OFF Question

### ISSUE THREAD

**Issue by MicheldeMessieres** [trilinos/Trilinos#562]
This question is about the intended behavior of Trilinos_ENABLE_ALL_OPTIONAL_PACKAGES for cdash tests.

**Summary:**

Is the intention that EXTRA_CONFIGURE_OPTIONS can be used to turn off Trilinos_ENABLE_ALL_OPTIONAL_PACKAGES? I think this is the intention but the current setup seems to override this with a hard coded ON setting in TribitsCTestDriverCore.cmake.

This apparently means we cannot run a manual configuration build with Trilinos_ENABLE_ALL_OPTIONAL_PACKAGES OFF which will behave identically to a cdash test run with Trilinos_ENABLE_ALL_OPTIONAL_PACKAGES OFF.

**Details:**

TribitsCTestDriverCore.cmake explicitly sets this value to ON:
  SET(${PROJECT_NAME}_ENABLE_ALL_OPTIONAL_PACKAGES ON)

Then package dependencies are calculated which depend on that value:
  TRIBITS_ADJUST_AND_PRINT_PACKAGE_DEPENDENCIES()

Then EXTRA_CONFIGURE_OPTIONS are applied. I believe EXTRA_CONFIGURE_OPTIONS is the proper place we would want to turn Trilinos_ENABLE_ALL_OPTIONAL_PACKAGES off but the above sequence means that the dependencies are calculated before reading this value.

An example would be running a cdash test with Zoltan2 and Trilinos_ENABLE_ALL_OPTIONAL_PACKAGES set OFF in EXTRA_CONFIGURE_OPTIONS.
This will still result in attempts to build Thyra which would not occur for a manual configuration build. Note this then leads to some build errors for cdash only which I haven't looked into yet but I expect are directly related to this setting.

Amending my own comment here: Simply removing the hard-coded Trilinos_ENABLE_ALL_OPTIONAL_PACKAGES=ON setting probably does not work as expected - I will have to investigate that further.

There are only a few cases of EXTRA_CONFIGURE_OPTIONS using Trilinos_ENABLE_ALL_OPTIONAL_PACKAGES OFF currently in the repo.

**Comment by jwillenbring** [comment]
@bartlettroscoe this would probably be best answered by you.

**Comment by MicheldeMessieres** [comment]
@bartlettroscoe  We made progress on this. We are using the exclude packages option in cdash to turn off the packages we don't want. I think we have achieved our original goals and based on other examples and the documentation this may be the intended setup. 

So it seems with cdash we should start all on and turn things off instead of all off and turning packages on. 

If this is the best way to set the tests up then perhaps we want to close this.

**Comment by bartlettroscoe** [comment]
@MicheldeMessieres, there is an **outer** dependency calculation that takes place in the `ctest -S <script>` program and an **inner** dependency calculation for the inner CMake configure of Trilinos.    
The `ctest -S` script that runs code in TribitsCTestDriverCore.cmake just happens to define a few TriBITS variables like `${PROJECT_NAME}_ENABLE_ALL_OPTIONAL_PACKAGES` that can be set in the **outer** dependency calculation that also get passed down through to the **inner** CMake configure.  However, in the case of this variable it looks like it is hard coded to turn these ON as seen [here](https://github.com/trilinos/Trilinos/blob/master/cmake/tribits/ctest_driver/TribitsCTestDriverCore.cmake#L1424) and [here](https://github.com/trilinos/Trilinos/blob/master/cmake/tribits/ctest_driver/TribitsCTestDriverCore.cmake#L1557).  Therefore, it looks like you can't change that currently.

> We made progress on this. We are using the exclude packages option in cdash to turn off the packages we don't want. I think we have achieved our original goals and based on other examples and the documentation this may be the intended setup. 

That is in fact the best way to do dependency handling with TriBITS.  This is what I call "black-listing" and it generally works much better than "white-listing".  For example, see:

* https://github.com/trilinos/Trilinos/issues/215#issuecomment-198538224

I need to get the word out about this "white-listing" vs. "black-listing" and point to the Panzer example.

Does this make sense?

**Comment by MicheldeMessieres** [comment]
@bartlettroscoe   The distinction between the outer and inter dependency was a source of confusion at first so this is more clear now. We've got things working with a black list approach but should we consider using the black list mandatory for cdash tests? The documentation suggests it is preferred, not mandatory. If white listing should work I'll need to go back at some point and further investigate the dependency errors I had seen.

**Comment by bartlettroscoe** [comment]
Can we close this?

**Comment by bartlettroscoe** [comment]
Question was answered
