### ISSUE TITLE
ML: free() corrupted unsorted chunks whileusing ml epetra multi level preconditioner

### ISSUE THREAD

**Issue by srinadhupreetham** [trilinos/Trilinos#5622]
## Question
@trilinos/ML

Error while using MultiLevelPredonditioner In MLEpetra
![issue](https://user-images.githubusercontent.com/20642187/62274576-c913ff80-b45d-11e9-91e7-5eb6b1190428.png)

**Comment by mayrmt** [comment]
@trilinos/ml

**Comment by jhux2** [comment]
@srinadhupreetham Is this happening in an ML test or example, or in your own application?  If the latter, please provide a reproducer program or instructions how this might be reproduced.  Was this serial or parallel?   What platform, compiler, etc.?

**Comment by srinadhupreetham** [comment]
This is happening in the modified ml_preconditioner.cpp 
Can you please refer to the code file attached


[preconditioner.zip](https://github.com/trilinos/Trilinos/files/3458019/preconditioner.zip)

**Comment by mhoemmen** [comment]
Please give us an actual code example as either an attached .cpp file, or an inline example in your comment.  It's not safe to unzip random zip files on the internet.

**Comment by srinadhupreetham** [comment]
#include "Epetra_Time.h"
#include "Epetra_Flops.h"
#include "Epetra_Version.h"
#include <fstream>
#include "ml_include.h"
#if defined(HAVE_ML_EPETRA) && defined(HAVE_ML_TEUCHOS) && defined(HAVE_ML_GALERI) && defined(HAVE_ML_AZTECOO)
#ifdef HAVE_MPI
#include "mpi.h"
#include "Epetra_MpiComm.h"
#else
#include "Epetra_SerialComm.h"
#endif
#include "Epetra_Map.h"
#include "Epetra_Vector.h"
#include "Epetra_CrsMatrix.h"
#include "Epetra_LinearProblem.h"
// required to build the example matrix
#include "Galeri_Maps.h"
#include "Galeri_CrsMatrices.h"
// required by the linear system solver
#include "AztecOO.h"
// required by ML
#include "ml_MultiLevelPreconditioner.h"
#include <fstream> 
using namespace Teuchos;
using namespace Galeri;
using namespace std;
int main(int argc, char *argv[])
{
  int ierr = 0, forierr = 0;
  bool debug = false;
#ifdef EPETRA_MPI
  MPI_Init(&argc,&argv);
  MPI_Comm_rank(MPI_COMM_WORLD, &rank);
  Epetra_MpiComm Comm( MPI_COMM_WORLD );
#else
  Epetra_SerialComm Comm;
#endif

  ifstream infile("ash219.mtx");
  string line;
  cout << infile <<  " Input Matrix file is read " << endl;
  int NumMyEquations,NumCols,NonZeros;
  if(getline(infile,line)){
  istringstream iss(line);
  iss >> NumMyEquations >> NumCols >> NonZeros;
}

  Comm.SetTracebackMode(0);
  int MyPID = Comm.MyPID();
  int NumProc = Comm.NumProc();

  int NumGlobalEquations = (NumMyEquations * NumProc) + EPETRA_MIN(NumProc,3);
  if(MyPID < 3)
    NumMyEquations++;

  Epetra_Map Map(NumGlobalEquations, NumMyEquations, 0, Comm);

  int* MyGlobalElements = new int[Map.NumMyElements()];
  Map.MyGlobalElements(MyGlobalElements);
  int* NumNz = new int[NumMyEquations];
int arow,acol;
 while(getline(infile,line)){
   istringstream iss(line);
   iss >> arow >> acol;
   NumNz[arow-1] += 1;
}
  Epetra_CrsMatrix B(Copy, Map, NumNz);
 // B.IndicesAreLocal();
 // B.IndicesAreGlobal();
  ifstream infilep("ash219.mtx");
  getline(infilep,line);
  double* Values = new double[1];
  int* Indices = new int[1];
 while(getline(infilep,line)){
   istringstream iss(line);
   iss >> arow >> acol;
   Indices[0] = acol-1;
   Values[0] = 1;
   B.InsertGlobalValues(arow-1,1,Values,Indices);
}
#ifdef ML_SCALING
   const int ntimers=4;
   enum {total, probBuild, precBuild, solve};
   ml_DblLoc timeVec[ntimers], maxTime[ntimers], minTime[ntimers];

  for (int i=0; i<ntimers; i++) timeVec[i].rank = Comm.MyPID();
  timeVec[total].value = MPI_Wtime();
#endif

#ifdef ML_SCALING
  timeVec[probBuild].value = MPI_Wtime();
#endif

 // Epetra_Map* Map1 = CreateMap("Cartesian2D", Comm, GaleriList);
 // Epetra_CrsMatrix* A = CreateCrsMatrix("Laplace2D", Map1, GaleriList);
    //B.FillComplete();
 // B.OptimizeStorage();

  Epetra_CrsMatrix *A(&B);
  Epetra_Map* Map1(&Map);
  Epetra_Vector LHS(*Map1); LHS.Random();
  Epetra_Vector RHS(*Map1); RHS.PutScalar(0.0);
  Epetra_LinearProblem Problem(A, &LHS, &RHS);
  A->FillComplete();
  A->OptimizeStorage();
  // As we wish to use AztecOO, we need to construct a solver object
  // for this problem
  AztecOO solver(Problem);
#ifdef ML_SCALING
  timeVec[probBuild].value = MPI_Wtime() - timeVec[probBuild].value;
#endif

  // =========================== begin of ML part ===========================

#ifdef ML_SCALING
  timeVec[precBuild].value = MPI_Wtime();
#endif
  // create a parameter list for ML options
  ParameterList MLList;

  // Sets default parameters for classic smoothed aggregation. After this
  // call, MLList contains the default values for the ML parameters,
  // as required by typical smoothed aggregation for symmetric systems.
  // Other sets of parameters are available for non-symmetric systems
  // ("DD" and "DD-ML"), and for the Maxwell equations ("maxwell").
  ML_Epetra::SetDefaults("SA",MLList);
  MLList.set("ML output", 10);
  MLList.set("max levels",5);
  MLList.set("increasing or decreasing","increasing");
  MLList.set("aggregation: type", "Uncoupled");
  MLList.set("smoother: type","Chebyshev");
  MLList.set("smoother: sweeps",3);
  MLList.set("smoother: pre or post", "both");

#ifdef HAVE_ML_AMESOS
  // solve with serial direct solver KLU
  MLList.set("coarse: type","Amesos-KLU");
#else
  // this is for testing purposes only, you should have
  // a direct solver for the coarse problem (either Amesos, or the SuperLU/
  // SuperLU_DIST interface of ML)
  MLList.set("coarse: type","Jacobi");
#endif
  /////////////////////////////////////////////////////////////////////////////////
  cout << " above is fine" << endl;
  ML_Epetra::MultiLevelPreconditioner* MLPrec =
    new ML_Epetra::MultiLevelPreconditioner(*A, MLList);
/////////////////////////////////////////////error part//////////////////////////////
  // verify unused parameters on process 0 (put -1 to print on all
  // processes)
  MLPrec->PrintUnused(0);
#ifdef ML_SCALING
  timeVec[precBuild].value = MPI_Wtime() - timeVec[precBuild].value;
#endif
  // =========================== end of ML part =============================

  // tell AztecOO to use the ML preconditioner, specify the solver
  // and the output, then solve with 500 maximum iterations and 1e-12
  // of tolerance (see AztecOO's user guide for more details)

#ifdef ML_SCALING
  timeVec[solve].value = MPI_Wtime();
#endif
  solver.SetPrecOperator(MLPrec);
  solver.SetAztecOption(AZ_solver, AZ_cg);
  solver.SetAztecOption(AZ_output, 32);
  solver.Iterate(500, 1e-12);
#ifdef ML_SCALING
  timeVec[solve].value = MPI_Wtime() - timeVec[solve].value;
#endif

  // destroy the preconditioner
  delete MLPrec;

  // compute the real residual

  double residual;
  LHS.Norm2(&residual);

  if( Comm.MyPID()==0 ) {
    cout << "||b-Ax||_2 = " << residual << endl;
  }

  // for testing purposes
  if (residual > 1e-5)
    exit(EXIT_FAILURE);

  delete A;
  delete Map1;

#ifdef ML_SCALING
  timeVec[total].value = MPI_Wtime() - timeVec[total].value;

  //avg
  double dupTime[ntimers],avgTime[ntimers];
  for (int i=0; i<ntimers; i++) dupTime[i] = timeVec[i].value;
  MPI_Reduce(dupTime,avgTime,ntimers,MPI_DOUBLE,MPI_SUM,0,MPI_COMM_WORLD);
  for (int i=0; i<ntimers; i++) avgTime[i] = avgTime[i]/Comm.NumProc();
  //min
  MPI_Reduce(timeVec,minTime,ntimers,MPI_DOUBLE_INT,MPI_MINLOC,0,MPI_COMM_WORLD);
  //max
  MPI_Reduce(timeVec,maxTime,ntimers,MPI_DOUBLE_INT,MPI_MAXLOC,0,MPI_COMM_WORLD);

  if (Comm.MyPID() == 0) {
    printf("timing :  max (pid)  min (pid)  avg\n");
    printf("Problem build         :   %2.3e (%d)  %2.3e (%d)  %2.3e \n",
             maxTime[probBuild].value,maxTime[probBuild].rank,
             minTime[probBuild].value,minTime[probBuild].rank,
             avgTime[probBuild]);
    printf("Preconditioner build  :   %2.3e (%d)  %2.3e (%d)  %2.3e \n",
             maxTime[precBuild].value,maxTime[precBuild].rank,
             minTime[precBuild].value,minTime[precBuild].rank,
             avgTime[precBuild]);
    printf("Solve                 :   %2.3e (%d)  %2.3e (%d)  %2.3e \n",
             maxTime[solve].value,maxTime[solve].rank,
             minTime[solve].value,minTime[solve].rank,
             avgTime[solve]);
    printf("Total                 :   %2.3e (%d)  %2.3e (%d)  %2.3e \n",
             maxTime[total].value,maxTime[total].rank,
             minTime[total].value,minTime[total].rank,
             avgTime[total]);
  }
#endif

#ifdef HAVE_MPI
  MPI_Finalize();
#endif

  return(EXIT_SUCCESS);
}

#else

#include <stdlib.h>
#include <stdio.h>
#ifdef HAVE_MPI
#include "mpi.h"
#endif

int main(int argc, char *argv[])
{
#ifdef HAVE_MPI
  MPI_Init(&argc,&argv);
#endif

  puts("Please configure ML with:");
  puts("--enable-epetra");
  puts("--enable-teuchos");
  puts("--enable-aztecoo");
  puts("--enable-galeri");

#ifdef HAVE_MPI
  MPI_Finalize();
#endif

  return(EXIT_SUCCESS);
}

#endif

**Comment by mhoemmen** [comment]
I added triple backquotes to your code sample to improve formatting.  Can you simplify this further by removing the ifdef-related code paths that never get compiled?  Right now we see two `main` definitions, which doesn't make any sense.

**Comment by jhux2** [comment]
@srinadhupreetham Is the driver reading in the matrix `ash219.mtx` from https://math.nist.gov/MatrixMarket/data/Harwell-Boeing/smtape/ash219.html?  That matrix isn't even square.

**Comment by srinadhupreetham** [comment]
I updated the code and yes this matrix is not square
