### ISSUE TITLE
Xpetra/Tpetra: MatrixMatrixMultiply fails with Tpetra deprecated code OFF

### ISSUE THREAD

**Issue by lucbv** [trilinos/Trilinos#5629]
## Bug Report
@trilinos/xpetra @trilinos/tpetra
@tjfulle @mhoemmen @jhux2 @csiefer2 

This issue is related to the work done in issue #5614 and probably needs to be tracked separately from the rest of the work done there.

### Description
MueLu's Petrov-Galerkin prolongator factory is failing when Tpetra deprecated code is off.
A gdb trace leads to the MMM kernel as the culprit, see [here](https://github.com/trilinos/Trilinos/files/3454010/matmatmult_backtrace.txt).

Here is the detective work I have been doing on this so far:

1. muelu factories like to call a version of `Xpetra::MMM` that only takes two matrices as inputs and returns one as output. Said function is defined [here](https://github.com/trilinos/Trilinos/blob/0193ca84a98452528343e362b77a0f61ee757ac3/packages/xpetra/sup/Utils/Xpetra_MatrixMatrix.hpp#L381).
2. The above function is wrapping a call to [this function](https://github.com/trilinos/Trilinos/blob/0193ca84a98452528343e362b77a0f61ee757ac3/packages/xpetra/sup/Utils/Xpetra_MatrixMatrix.hpp#L325) that takes three matrices as input but allows the result of the MMM to be `Teuchos::Null`. In the `C == Teuchos::null` case, `C` is created with `double nnzPerRow = Teuchos::as<double>(0);`

Now I have two questions:
1. Is it OK to pass matrix `C` with `nnzPerRow = 0` ro should we just omit it?
2. Shouldn't Tpetra compute the max number of non-zero per rows for C defined as `C=A*B` while it performs the multiplication?

**Comment by jhux2** [comment]
@csiefer2 ping

**Comment by mhoemmen** [comment]
> 1. Is it OK to pass matrix `C` with `nnzPerRow = 0` or should we just omit it?

MueLu often follows an interface pattern of "give me an empty object and I'll fill it."  I think the original intent was to support various forms of reuse, if the in/out argument already has an allocation.

> 2. Shouldn't Tpetra compute the max number of non-zero per rows for C defined as `C=A*B` while it performs the multiplication?

If C is empty, then I think that's reasonable.  The question is whether MueLu always assumes that C is empty.  If so, then the interface really should be changed to return a new C, not take C as an in/out argument.

**Comment by kddevin** [comment]
With the current interface, sending an empty matrix (i.e., one created with nnzPerRow=0) to the matrix-matrix multiplication should work.

**Comment by mhoemmen** [comment]
I worry a little bit, because @csiefer2 did what he did [here](https://github.com/trilinos/Trilinos/blob/0193ca84a98452528343e362b77a0f61ee757ac3/packages/xpetra/sup/Utils/Xpetra_MatrixMatrix.hpp#L343) precisely because reallocation on demand was (& is) faster in ML than preallocation.

**Comment by csiefer2** [comment]
MueLu is calling a "slow" multiply (aka no FillComplete).  That's the problem here.

**Comment by brian-kelley** [comment]
Fixed in #5935.
