### ISSUE TITLE
muelu: build error on OSX [xsdk/spack]

### ISSUE THREAD

**Issue by balay** [trilinos/Trilinos#5630]
trilinos@develop build fails on OSX [with xcode clang+gfortran] build.

Attaching the build log

cc: @jwillenbring @keitat
[spack-build-out.txt](https://github.com/trilinos/Trilinos/files/3458216/spack-build-out.txt)

**Comment by mhoemmen** [comment]
@trilinos/muelu @trilinos/xpetra I had also reported this [here](https://github.com/trilinos/Trilinos/issues/5557#issue-470636975), but that issue got conflated with another issue that got fixed.  The original Clang build issue remains.

**Comment by jwillenbring** [comment]
@trilinos/muelu Any thoughts on this issue? We are trying to resolve this for the ECP xSDK release.

**Comment by keitat** [comment]
We are planning to release xSDK-0.5.0 on 9/12. This bug needs to be fixed for the release.

**Comment by jhux2** [comment]
@keitat and I talked about this.  I’ve got some high priority items to take care of, then I’ll fix this.  I believe the fix should be fairly straightforward. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jhux2** [comment]
Btw, @balay reported this in an earlier issue that I believe is still open. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by balay** [comment]
A reminder: this issue still comes up on osx build of trilinos@develop

**Comment by jhux2** [comment]
@balay Thank you for the reminder.  @keitat had told me that the xsdk release was delayed -- is there a new date?

**Comment by balay** [comment]
xsdk release is at the end of oct.

However, each individual packages were to provide a release (or equivalent) by end of sept [as some of the individual packages had this deadline for their ECP quarterly report]. 

So xsdk release was extended to end of oct [requeted this extension from ECP] - this way we can  do testing with stable packages - [and have some time to deal with any issues that might come up]

**Comment by jwillenbring** [comment]
@jhu2 Due to the timing of the xSDK release, I went ahead and created a trilinos-release-12-14-branch for testing to occur on. If you have not implemented this fix yet, please do so on that branch and then apply the fix also to develop.

**Comment by jhux2** [comment]
> Due to the timing of the xSDK release, I went ahead and created a trilinos-release-12-18-branch for testing to occur on. If you have not implemented this fix yet, please do so on that branch and then apply the fix also to develop.

@jwillenbring @balay The fix was merged to Trilinos develop yesterday.  I just cherry-picked over to `trilinos-release-12-18-branch`.  Please let me know if this fixes the problem.

**Comment by balay** [comment]
@jhux2 Thanks! I'm now able to build trilinos on OSX via spack/xsdk [with both xcode/clang and brew/gcc]

**Comment by jhux2** [comment]
Closing as fixed.
