### ISSUE TITLE
STK: missing ngp_test.hpp file

### ISSUE THREAD

**Issue by rppawlo** [trilinos/Trilinos#5635]
@alanw0 - I'm seeing the failure below when building the current trilinos on my rhel6 workstation. 

/ascldap/users/rppawlo/Trilinos/packages/stk/stk_unit_test_utils/unit_main_lib/UnitTestMain.cpp:39:10: fatal error: stk_ngp_test/ngp_test.hpp: No such file or directory
 #include <stk_ngp_test/ngp_test.hpp>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~

The enabled packages are:

Processing enabled package: STK (Math, Util, Topology, Mesh, IO, Unit_test_utils, Search, Transfer, ExprEval)

If I disable the Unit_test_utils, this goes away. I think there may be a missing ifdef around the include above for when the NGP package is not enabled but the unit test utils are enabled.

**Comment by alanw0** [comment]
@rppawlo Thanks Roger, I'll take a look at that.
