### ISSUE TITLE
Ifpack2: buid error on Ride 

### ISSUE THREAD

**Issue by ikalash** [trilinos/Trilinos#5653]
Our Albany nightly build on Ride failed due to Ifpack2.  Here is the error: 

```
/.../repos/Trilinos/packages/ifpack2/src/Ifpack2_Container_def.hpp(319): error: a nonstatic member reference must be relative to a specific object
```
http://cdash.sandia.gov/CDash-2-3-0/viewBuildError.php?buildid=87610

Could someone please have a look?  

@trilinos/ifpack2

**Comment by jhux2** [comment]
@trilinos/ifpack2

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mhoemmen** [comment]
@brian-kelley might be already on this one but if he's too busy let me know.

**Comment by brian-kelley** [comment]
@ikalash @mhoemmen I'm looking into this.

**Comment by ikalash** [comment]
Looks like this issue has been resolved.  Thanks!

**Comment by brian-kelley** [comment]
@ikalash I wasn't able to replicate this yesterday (same GCC/CUDA, version a4f99ce6). The failing build on ride was from August 3rd, and I'm pretty sure this commit (7ddef9a51) from August 5th fixed the error, since it's about the deprecated Kokkos execution space fence():
    Merge pull request #5638 from vbrunini/ifpack2_deprecated_fence_fix    
    ifpack2: Fix use of deprecated execution_space::fence() static method.
