### ISSUE TITLE
ML: Change in behavior from specific commit

### ISSUE THREAD

**Issue by dlkarnitz** [trilinos/Trilinos#5657]
## Question
@trilinos/\<ML\>

We have identified a specific change to Trilinos that changed the behavior in an undesirable way for our non-linear solver which uses AztecOO/ML/Epetra as an inner linear solver.

We'd like to get more information about why this change was originally made and what the possible risks would be for reverting it in our usage of Trilinos.

The change specifically is:

https://github.com/trilinos/Trilinos/commit/b529efe138d6ce6b9ef375022d6524e75a147655

We were able to identify that this change causes overall less stable convergence for our solver on various process counts. From that we created a single linear solve test case that showed enough difference in a 10 cpu case to trace the change.

This plot shows convergence behavior for our linear solve test case in version 10.10.2 (our original usage of Trilinos) and 12.10.1 (the version we recently upgraded to); and also compares the test case run against builds of Trilinos commits bounding the identified change.

![ml-example-12-10-1-revert np10](https://user-images.githubusercontent.com/26779012/62486278-d813ee00-b78c-11e9-87fa-d3ef48729e5f.png)

**Comment by mhoemmen** [comment]
@trilinos/ml

**Comment by csiefer2** [comment]
@rstumin

**Comment by mhoemmen** [comment]
begone autobot
