### ISSUE TITLE
ML: Smoothers that support our data matrices

### ISSUE THREAD

**Issue by srinadhupreetham** [trilinos/Trilinos#5665]
Few Smoothers and Coarse List are resulting in a segmentation fault with my input A(data matrix). Is there a way to know what are the smoothers that will work for my specific data matrix

**Comment by mayrmt** [comment]
@trilinos/ml

**Comment by mhoemmen** [comment]
> Is there a way to know what are the smoothers that will work for my specific data matrix

I would recommend a book on multigrid.  Beyond that, experience (either yours or your colleague's) is your best guide.

**Comment by srinadhupreetham** [comment]
Basically, I am dealing with a large data set of matrices where each matrix will be of different types. So it is not possible to go through each of them manually. Is there a way to know what are the smoothers that work for the particular matrix through code

**Comment by mhoemmen** [comment]
> Is there a way to know what are the smoothers that work for the particular matrix through code

Short answer is "no."

Longer answer: You can use code to tell if the matrix is symmetric.  Testing if the matrix is positive definite is more costly.  The fastest way to tell if incomplete Cholesky or ILU work on a general matrix is probably just to try them.

**Comment by jhux2** [comment]
Please give us some more information about the type of systems you’re interested in solving. As @mhoemmen mentioned, our suggestions will depend on your answers. The more details you can provide, the better.

**Comment by srinadhupreetham** [comment]
I am trying to find solvation time for Ax =b with A matrix as 494_bus.mtx from [https://sparse.tamu.edu/HB/494_bus](url) 

Some Combinations of these parameters are not working:
ex:1.max levels:5
     2.smoother: Gauss-Seidel
     3.aggregation: Uncoupled
     4. smoother sweeps : 3
     5.coarse type : Guass-Seidel
   
*** I would like to know what combinations will work and what wont as i need to wright a script that does the same for large dataset ***


//////code part for parameters/////
int maxlevels[5] = {5,8,10,13,15};
  string IncreaseOrDecrease[2] = {"increasing","decreasing"};
  string aggregationType[6] ={"Uncoupled","MIS","Uncoupled-MIS","METIS","ParMETIS"};
  string smootherType[9] ={"Jacobi","Gauss-Seidel","symmetric Guass-Seidel","block Gauss-Seidel","block symmetric Guass-Seidel","Chebyshev","IC","Aztec","petsc"};
  string coarseType[9] ={"Jacobi","Guass-Seidel","symmetric Gauss-Seidel","Chebyshev","Hiptmair","Amesos-KLU","Amesos-Superlu","Amesos-MUMPS","SuperLU"};
  int smootherSweeps[3] ={3,5,7};
  string smootherPreOrPost[3] = {"pre","post","both"};
  ParameterList MLList;
  ML_Epetra::SetDefaults("SA",MLList);
  MLList.set("ML output", 10);
  MLList.set("max levels",5);
  MLList.set("increasing or decreasing","increasing");
  MLList.set("aggregation: type", "Uncoupled");
  MLList.set("smoother: type",smootherType[1]);
  MLList.set("smoother: sweeps",3);
  MLList.set("smoother: pre or post", "both");
  MLList.set("coarse: type",coarseType[temp1]);
  /////////////////////////////////////////////////////////////////////////////////
  ML_Epetra::MultiLevelPreconditioner* MLPrec =
    new ML_Epetra::MultiLevelPreconditioner(*A, MLList);

**Comment by mhoemmen** [comment]
I would recommend taking the MueLu tutorial and reading up on multigrid.  There's no automatic mapping from matrix to multigrid parameters.

**Comment by mayrmt** [comment]
ML User Guide: https://trilinos.org/oldsite/packages/ml/mlguide5.pdf

Here‘s the user guide of MueLu: https://trilinos.github.io/pdfs/mueluguide.pdf

And the MueLu Tutorial: https://trilinos.github.io/muelu_tutorial.html

**Comment by srinadhupreetham** [comment]
Is there way where i can print only solution time instead of verbose description of the warnings and output

**Comment by mayrmt** [comment]
If yes, then it’s probably described in the user guides. If no, you can just put your own timers around the ML call.

**Comment by jhux2** [comment]
@srinadhupreetham The AMG methods in ML and MueLu are really designed for PDE-based systems, the matrix you're trying to solve is from a power network.  Have you read papers or other references that suggest that AMG will work for this type of system?

If you just want the solution time, grep will work.

**Comment by jhux2** [comment]
Closing, but please reopen if necessary.
