### ISSUE TITLE
amesos2 - add check for factorization failure.

### ISSUE THREAD

**Issue by bathmatt** [trilinos/Trilinos#5666]
## Enhancement
@trilinos/amesos2 

Can we add a check here 
```
       data_.numeric_ = ::KLU2::klu_factor<slu_type, local_ordinal_type>
          (sp_rowptr_with_common_type.getRawPtr(), sp_colind, sp_values,
           data_.symbolic_, &(data_.common_)) ;
      }
      else {
        data_.numeric_ = ::KLU2::klu_factor<slu_type, local_ordinal_type>
          (colptr_.getRawPtr(), rowind_.getRawPtr(), nzvals_.getRawPtr(),
           data_.symbolic_, &(data_.common_)) ;
      } //end single_process_optim_check = false

      // This is set after numeric factorization complete as pivoting can be used;
      // In this case, a discrepancy between symbolic and numeric nnz total can occur.

<<<<< HERE >>>>>
      this->setNnzLU( as<size_t>((data_.numeric_)->lnz) + as<size_t>((data_.numeric_)->unz) );

```

that is something like assert(data_.numeric_  != NULL);

I can do it, if @srajama1 or someone else can tell me the amesos2 was of throwing errors.

We have this happen to often and a segfault is less helpful

**Comment by bathmatt** [comment]
@kyungjoo-kim @mhoemmen you guys are listed on amesos2 as well...

**Comment by srajama1** [comment]
We can add an assert, @ndellingwood .

**Comment by bathmatt** [comment]
can we have a message..

**Comment by mhoemmen** [comment]
@bathmatt Note that `assert` only does something in a debug build.

**Comment by bathmatt** [comment]
Right, I wasn't saying use an assert, I was saying use what amesos2 uses as it's standard error reporting tool.  That is the bit I don't know, It should check and always error out.  I could just put an if () throw ... but wanted to conform to the rest of the code

**Comment by srajama1** [comment]
throw is fine as well. We will take care of it.

**Comment by srajama1** [comment]
@MicheldeMessieres

**Comment by MicheldeMessieres** [comment]
@srajama1 Closing this issue as it should be resolved now.
