### ISSUE TITLE
Tpetra: proposed changes to handle processes with zero rows

### ISSUE THREAD

**Issue by allaffa** [trilinos/Trilinos#568]
@allaffa @jhux2 @trilinos/tpetra @rstumin 

I am currently working on a project at Sandia about multigrid preconditioners where some tasks have no matrix rows. This has revealed two places where KokkosKernels and Tpetra throw an exception.  
I would like to propose a change of the conditions to throw the exception, checking also that the number of rows be different from zero. 

See attached .txt files. 
[0005-Tpetra-added-check-on-rows-in-exception.txt](https://github.com/trilinos/Trilinos/files/425981/0005-Tpetra-added-check-on-rows-in-exception.txt)
[0007-Kokkos-added-check-on-rows-in-exception.txt](https://github.com/trilinos/Trilinos/files/425980/0007-Kokkos-added-check-on-rows-in-exception.txt)

**Comment by amklinv** [comment]
Tagging @mhoemmen, the king of tpetra

**Comment by mhoemmen** [comment]
@amklinv "king" only if Tpetra is one of those micronations that stamps your passport for fun and grants titles like "Her Grace the Archbishop of Anasazi" ;-)

@allaffa I appreciate your contributions!  As a work-around, you may also want to consider using Map's removeEmptyProcesses method to exclude processes with zero rows.  If you have a LOT of processes with zero rows, this may improve performance.

**Comment by allaffa** [comment]
@mhoemmen Thank you for the suggestion about excluding the process with zero rows from the Map. However, I don't think I can do that for the goal of my project. The map with a process doing nothing is associated with a fine level of a MueLu preconditioner. Via repartitioning, the process which is idle at the fine level is in charge of solving the coarse level. The only way for me to call an idle process into action later on in the MueLu hierarchy is to keep such an idle process included in the communicator, even if it does nothing. Removing the process from the communicator at the fine level prevents me from using such a process at lower levels of MueLu. In fact each coarser level of the MG preconditioner has a subcommunicator which is a subset of the communicator at the finer level.

**Comment by mhoemmen** [comment]
@allaffa It sounds like you are either a MueLu developer, or interacting directly with the coarser levels of the MueLu hierarchy, for example to change how MueLu does coarsening.  Is that correct?

Your patches look both harmless and useful.  It might take me a little while to get to this -- I'm working on #558 now, and that needs focus.  Have you tried running any downstream tests?  The only way this could get interesting is in interactions with MueLu repartitioning; that's exactly why you wrote these changes, so I'm guessing you have already tried them out, at least in your application.  The trouble with MueLu testing is that it might be hard to exercise all the repartitioning possibilities without running on a large number of MPI processes.

**Comment by allaffa** [comment]
@mhoemmen
I had a conversation yesterday with @jhux2 about running tests in this respect. I know that he already started checking some tests yesterday. He might confirm/correct this statement of mine and provide you with information about the outcome of the downstream test checks.

**Comment by tawiesn** [comment]
@allaffa Can Epetra deal with the empty processes? I just want to make sure, since you are using MueLu (with Xpetra), that it works both with the Epetra and Tpetra stack in the end.

**Comment by jhux2** [comment]
> He might confirm/correct this statement of mine and provide you with information about the outcome of the downstream test checks.

MueLu broke in a way unrelated to @allaffa's changes.  That being said, his code changes are heavily guarded, so the checkin procedure won't tell us if anything downstream is affected.  I'll have to enable this code locally and run the downstream tests manually (i.e., outside the checkin script).

> @allaffa Can Epetra deal with the empty processes? I just want to make sure, since you are using MueLu (with Xpetra), that it works both with the Epetra and Tpetra stack in the end.

I believe @allafa and @rstumin only considered using the Tpetra stack.

**Comment by mhoemmen** [comment]
Thanks @jhux2 and @tawiesn for context!  I'm just being extra cautious about how these code changes might interact with MueLu, independently of other changes @allaffa may have made.

**Comment by jhux2** [comment]
> MueLu broke in a way unrelated to @allaffa's changes. That being said, his code changes are heavily guarded, so the checkin procedure won't tell us if anything downstream is affected. I'll have to enable this code locally and run the downstream tests manually (i.e., outside the checkin script).

@allaffa's changes to MueLu and Ifpack2 have been pushed.  As I said, they are not enabled by default (and in fact marked as experimental).  I will test the proposed changes to Tpetra and KokkosKernels to see whether anything downstream is affected.

**Comment by jhux2** [comment]
I applied the Tpetra patches that avoid some test-for-exceptions when the number of rows on a process is zero, and ran the checkin script with downstream dependencies enabled.  All downstream tests pass except for 11 ROL tests in MPI_SS_DEBUG.  I then backed out the patches and reran the MPI_SS_DEBUG configuration, and the same 11 ROL tests still failed.  This gives me confidence the patches are not to blame.

```
passed: Trilinos/MPI_DEBUG: passed=467,notpassed=0
passed: Trilinos/SERIAL_RELEASE: passed=432,notpassed=0
passed: Trilinos/SERIAL_SS_RELEASE: passed=531,notpassed=0
FAILED: Trilinos/MPI_SS_DEBUG: passed=819,notpassed=11

Fri Aug 19 16:09:47 PDT 2016

Enabled Packages: TpetraCore, TpetraKernels
Enabled all Forward Packages
Hostname: typhon.ca.sandia.gov
Source Dir: /home/scratch/checkin/Trilinos
Build Dir: /home/scratch/checkin/Trilinos/CHECKIN/MPI_SS_DEBUG

CMake Cache Varibles: -DTrilinos_TRIBITS_DIR:PATH=/home/scratch/checkin/Trilinos/cmake/tribits -DTrilinos_ENABLE_TESTS:BOOL=ON -DTrilinos_TEST_CATEGORIES:STRING=BASIC -DTrilinos_ALLOW_NO_PACKAGES:BOOL=OFF -DDART_TESTING_TIMEOUT:STRING=600.0 -D CMAKE_AR="/usr/bin/ar" -D BUILD_SHARED_LIBS:BOOL=ON -D Trilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON -D BLAS_LIBRARY_DIRS:PATH="${BLAS_LIBRARY_DIRS}" -D BLAS_LIBRARY_NAMES:STRING="${BLAS_LIBRARY_NAMES}" -D LAPACK_LIBRARY_DIRS:PATH="${LAPACK_LIBRARY_DIRS}" -D LAPACK_LIBRARY_NAMES:STRING="${LAPACK_LIBRARY_NAMES}" -D TPL_SuperLU_LIBRARIES:PATH=/usr/local/superlu/SuperLU_4.3/lib/libsuperlu_4.3.so -D SuperLU_INCLUDE_DIRS:PATH=/usr/local/superlu/SuperLU_4.3/include -D Amesos2_ENABLE_Basker:BOOL=ON -D Trilinos_ENABLE_MOOCHO:BOOL=OFF -D Trilinos_ENABLE_FEI:BOOL=OFF -D Trilinos_ENABLE_GlobiPack:BOOL=OFF -D Trilinos_ENABLE_Moertel:BOOL=OFF -D Trilinos_ENABLE_OptiPack:BOOL=OFF -D Trilinos_ENABLE_RBGen:BOOL=OFF -D Trilinos_ENABLE_RTOp:BOOL=OFF -D Trilinos_ENABLE_Rythmos:BOOL=OFF -D Trilinos_ENABLE_CHECKED_STL:BOOL=OFF -D Trilinos_EXTRA_LINK_FLAGS:STRING="-pthread" -D CMAKE_BUILD_TYPE:STRING=DEBUG -D TPL_ENABLE_MPI:BOOL=ON -D MPI_BASE_DIR:PATH=/usr/local/mpich2/1.4.1p1_gcc_4.4.7 -D Trilinos_ENABLE_SECONDARY_STABLE_CODE=ON -D TPL_ENABLE_Netcdf:BOOL=OFF -D TPL_ENABLE_Boost:BOOL=OFF -DTrilinos_ENABLE_PyTrilinos:BOOL=OFF -DTrilinos_ENABLE_GlobiPack:BOOL=OFF -DTrilinos_ENABLE_OptiPack:BOOL=OFF -DTrilinos_ENABLE_Pliris:BOOL=OFF -DTrilinos_ENABLE_FEI:BOOL=OFF -DTrilinos_ENABLE_Teko:BOOL=OFF -DTrilinos_ENABLE_Phalanx:BOOL=OFF -DTrilinos_ENABLE_Moertel:BOOL=OFF -DTrilinos_ENABLE_Rythmos:BOOL=OFF -DTrilinos_ENABLE_MOOCHO:BOOL=OFF -DTrilinos_ENABLE_RTOp:BOOL=OFF -DTrilinos_ENABLE_STK:BOOL=OFF -DTrilinos_ENABLE_Piro:BOOL=OFF -DTrilinos_ENABLE_Panzer:BOOL=OFF -DTrilinos_ENABLE_Sundance:BOOL=OFF -DTrilinos_ENABLE_CTrilinos:BOOL=OFF -DTrilinos_ENABLE_Didasko:BOOL=OFF -DTrilinos_ENABLE_FEApp:BOOL=OFF -DTrilinos_ENABLE_Optika:BOOL=OFF -DTrilinos_ENABLE_RBGen=OFF -D TPL_ENABLE_SuperLU:BOOL=OFF -D Amesos2_ENABLE_KLU2:BOOL=OFF -D Amesos2_ENABLE_Basker:BOOL=ON -DTrilinos_ENABLE_TpetraCore:BOOL=ON -DTrilinos_ENABLE_TpetraKernels:BOOL=ON -DTrilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=ON -DTrilinos_ENABLE_ALL_FORWARD_DEP_PACKAGES:BOOL=ON
Make Options: -j16
CTest Options: -j16

Pull: Passed (0.00 min)
Configure: Passed (1.45 min)
Build: Passed (32.91 min)
Test: FAILED (9.14 min)

99% tests passed, 11 tests failed out of 830

Label Time Summary:
Amesos               =   7.30 sec (12 tests)
Amesos2              =   2.91 sec (7 tests)
Anasazi              =  92.02 sec (91 tests)
Belos                = 163.94 sec (71 tests)
Galeri               =   2.27 sec (9 tests)
Ifpack               =  44.64 sec (53 tests)
Ifpack2              =  61.52 sec (29 tests)
Isorropia            =   3.52 sec (6 tests)
ML                   =  30.25 sec (34 tests)
MueLu                = 1075.27 sec (61 tests)
NOX                  = 154.39 sec (84 tests)
ROL                  = 621.67 sec (87 tests)
ShyLU                =   4.46 sec (3 tests)
Stokhos              = 190.69 sec (61 tests)
Tpetra               =  56.74 sec (114 tests)
TrilinosCouplings    = 208.45 sec (14 tests)
Xpetra               = 147.23 sec (15 tests)
Zoltan2              =  66.66 sec (85 tests)

Total Test time (real) = 548.42 sec

The following tests FAILED:
    803 - ROL_example_PDE-OPT_poisson_example_01_MPI_4 (Failed)
    804 - ROL_example_PDE-OPT_poisson_example_02_MPI_4 (Failed)
    805 - ROL_example_PDE-OPT_poisson-boltzmann_example_01_MPI_4 (Failed)
    806 - ROL_example_PDE-OPT_poisson-topOpt_example_01_MPI_4 (Failed)
    807 - ROL_example_PDE-OPT_stefan-boltzmann_example_03_MPI_4 (Failed)
    808 - ROL_example_PDE-OPT_stefan-boltzmann_example_04_MPI_4 (Failed)
    809 - ROL_example_PDE-OPT_elasticity_example_01_MPI_1 (Failed)
    810 - ROL_example_PDE-OPT_elasticity_example_02_MPI_1 (Failed)
    811 - ROL_example_PDE-OPT_adv-diff-react_example_01_MPI_4 (Failed)
    812 - ROL_example_PDE-OPT_adv-diff-react_example_02_MPI_4 (Failed)
    813 - ROL_example_PDE-OPT_stoch-adv-diff_example_01_MPI_4 (Failed)
```

**Comment by mhoemmen** [comment]
Thanks @jhux2 !  ROL has been churning a lot lately.  The only thing I see in the changes that I don't like, are some signed / unsigned comparisons in the KokkosKernels patch (search for `0!=numRows`).  Otherwise, I think it's safe to push.  Would you like to do it?

**Comment by jhux2** [comment]
@mhoemmen ```numRows``` is of type ```size_type```, which is really BMV::size_type.  Ultimately, is this guaranteed to be unsigned?

**Comment by mhoemmen** [comment]
@jhux2 Unfortunately, this is signed on CPUs (size_t) and unsigned on GPUs (int).  The Kokkos developers would consider making it signed on both platforms.

**Comment by jhux2** [comment]
Good to know.  So I guess it should be something like ```Teuchos::OrdinalTraits<size_type>::zero()!=numrows```?

**Comment by jhux2** [comment]
> Good to know. So I guess it should be something like Teuchos::OrdinalTraits<size_type>::zero()!=numrows?

No ... since this would be a dependence on Teuchos.  Instead

```
const size_type numRows = ...
const size_type zero = static_cast<size_type> (0);
if (zero!=numRows)...
```

**Comment by jhux2** [comment]
Ok, I've pushed these changes.  @mhoemmen thanks for the review.

**Comment by jhux2** [comment]
Tpetra dashboard today is showing one failure:  http://testing.sandia.gov/cdash/viewTest.php?onlyfailed&buildid=2538924.  Since my commit was the only one to Tpetra, looks like it broke something.  I'll have a look.

**Comment by jhux2** [comment]
I don't understand.  The test reports as passing, but there's a nonzero return code:
```
Summary: total = 1, run = 1, passed = 1, failed = 0

End Result: TEST PASSED
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.
-------------------------------------------------------
```

**Comment by etphipp** [comment]
Do you have the option to globally reduce the test status across processors enabled (the Teuchos unit test harness does not do this by default)?  I bet your test is passing on proc 0 but failing on some other processor.  If you run the test with output from all processors, you should see that.

-Eric

**Comment by jhux2** [comment]
Thanks for the tip, Eric.  Yes, the test is failing on proc 1.  Back to the commit question.  I backed out the changes, and the test, TpetraCore_Map_Bug5822_2.exe, still fails.  This unit test is exercising Map->getRemoteIndexList().  My checkins affect Tpetra_CrsMatrix and KokkosKernels, so I see no way these two commits could break this unit test.

**Comment by mhoemmen** [comment]
Thanks @jhux2, @etphipp, and @allaffa !

I opened a new issue, #580, for the failing Tpetra test.

**Comment by mhoemmen** [comment]
Regarding #580, I don't see the failing test any more, so I closed that issue.
