### ISSUE TITLE
Phalanx:  Phalanx_mdfield_runtime_MPI_1 failing on ATDM KNL build

### ISSUE THREAD

**Issue by fryeguy52** [trilinos/Trilinos#5685]
## Bug Report
CC: @trilinos/phalanx, @mperego (Trilinos Discretizations Product Lead), @bartlettroscoe, @fryeguy52 
 
## Next Action Status
<status-and-or-first-action>
 
## Description
 
As shown in [this query](https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-mutrino-intel-opt-openmp-KNL&field2=testname&compare2=61&value2=Phalanx_mdfield_runtime_MPI_1&field3=site&compare3=61&value3=mutrino&field4=buildstarttime&compare4=84&value4=2019-08-09T04%3A01%3A00UTC&field5=buildstarttime&compare5=83&value5=2019-07-09T04%3A01%3A00UTC) the tests:
* Phalanx_mdfield_runtime_MPI_1

is failing since 7/15/2019 in the builds:
* Trilinos-atdm-mutrino-intel-opt-openmp-KNL

```
p=0: *** Caught standard std::exception of type 'St11logic_error' :
 
  /lscratch1/jenkins/mutrino-slave/workspace/Trilinos-atdm-mutrino-intel-opt-openmp-KNL/SRC_AND_BUILD/Trilinos/packages/phalanx/test/Field/MDField_Runtime.cpp:548:
  
  Throw number = 1
  
  Throw test that evaluated to true: output.str() != "MDField(100,4): Tag: density, double, DataLayout: <Cell,Node>(100,4)"
  
  String match failed!
 [FAILED]  (0.373 sec) mdfield_RuntimeTimeChecked_UnitTest
 Location: /lscratch1/jenkins/mutrino-slave/workspace/Trilinos-atdm-mutrino-intel-opt-openmp-KNL/SRC_AND_BUILD/Trilinos/packages/phalanx/test/Field/MDField_Runtime.cpp:77
 

The following tests FAILED:
    0. mdfield_RuntimeTimeChecked_UnitTest ... 

Total Time: 0.41 sec

Summary: total = 1, run = 1, passed = 0, failed = 1

End Result: TEST FAILED
srun: error: nid00252: task 0: Exited with exit code 1
srun: Terminating job step 18807155.1462

```

## Current Status on CDash

The current status of this test for the current testing day can be found [here](https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-mutrino-intel-opt-openmp-KNL&field2=testname&compare2=61&value2=Phalanx_mdfield_runtime_MPI_1&field3=site&compare3=61&value3=mutrino&field4=buildstarttime&compare4=84&value4=today&field5=buildstarttime&compare5=83&value5=yesterday)

## Steps to Reproduce

One should be able to reproduce this failure on mutrino as described in:
* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md

More specifically, the commands given for mutrino are provided at:
* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#mutrino

The exact commands to reproduce this issue should be:
```
$ cd <some_build_dir>/
$ source $TRILINOS_DIR/cmake/std/atdm/load-env.sh Trilinos-atdm-mutrino-intel-opt-openmp-KNL
$ cmake \
 -GNinja \
 -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
 -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_Phalanx=ON \
 $TRILINOS_DIR
$ make NP=16
$ salloc -N 1 -p standard -J $ATDM_CONFIG_JOB_NAME ctest -j16
```

**Comment by rppawlo** [comment]
@fryeguy52 - fix has been pushed into trilinos develop.

**Comment by fryeguy52** [comment]
@rppawlo Thanks!

**Comment by rppawlo** [comment]
@fryeguy52 - can we close this? I think it has been passing the last few nights.

**Comment by bartlettroscoe** [comment]
As shown in [this query](https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercount=4&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-mutrino-intel-opt-openmp-KNL&field2=testname&compare2=61&value2=Phalanx_mdfield_runtime_MPI_1&field3=site&compare3=61&value3=mutrino&field4=buildstarttime&compare4=83&value4=2019-07-01) this was consistently failing since 7/16/2019 but as of today it passed.  Therefore, it is safe to assume this is fixed.

Closing as complete.  Thanks for fixing so fast @rppawlo!
