### ISSUE TITLE
Symbol not found: _PyBool_Type

### ISSUE THREAD

**Issue by dpo** [trilinos/Trilinos#569]
When Trilinos is built with Python support and an external C++ library links against the Trilinos library list given in the CMake file, the following error results:

```
dyld: Symbol not found: _PyBool_Type
  Referenced from: /usr/local/opt/trilinos/lib/libpytrilinos.12.dylib
  Expected in: flat namespace
 in /usr/local/opt/trilinos/lib/libpytrilinos.12.dylib
```

The issue has been around for quite a while and the problem is described here: https://github.com/Homebrew/homebrew-science/issues/2148#issuecomment-103614509

Here's an example of occurrence of the error when linking deal.II with Trilinos: https://gist.github.com/dpo/3a617befecd9c2065a2c755b13b95006#file-consoletext-L312

It would be great if this could be prioritized somehow. I'm not sure why the problem isn't more widespread.

**Comment by hmpelta** [comment]
Please give some advice, how should solve this issue on osx?

**Comment by wfspotz** [comment]
Here is a script you can run to modify the export Makefiles generated by Trilinos that will fix this issue for Makefiles:
```
#! /usr/bin/env python
import os

fileNames = ["Makefile.export.Trilinos", "Makefile.export.Trilinos_install"]
for fileName in fileNames:
    if os.path.isfile(fileName):
        backup = fileName + ".bak"
        backupFile = open(backup, "w")
        for line in open(fileName, "r"):
            backupFile.write(line.replace("-lpytrilinos", ""))
        backupFile.close()
        os.rename(backup, fileName)

fileNames = ["TrilinosConfig_install.cmake"]
for fileName in fileNames:
    if os.path.isfile(fileName):
        backup = fileName + ".bak"
        backupFile = open(backup, "w")
        for line in open(fileName, "r"):
            out = line.replace("pytrilinos;", "")
            backupFile.write(out.replace("PyTrilinos;", ""))
        backupFile.close()
        os.rename(backup, fileName)
```
You will need to `cd` to the build directory that contains `Makefile.export.Trilinos`, `Makefile.export.Trilinos_install`, and `TrilinosConfig_install.cmake` and run the script from there.

**Comment by wfspotz** [comment]
Closing in favor of #866
