### ISSUE TITLE
Panzer:  Add quick check for spatial dimension to pamgen reader

### ISSUE THREAD

**Issue by eric-c-cyr** [trilinos/Trilinos#5693]
## Enhancement
@trilinos/panzer 

Currently the pamgen reader just reads a mesh. But if you want to know the dimension before reading in the mesh fully, its difficult. Add a method to do this.

**Comment by rppawlo** [comment]
PR #5717 will address this.

**Comment by rppawlo** [comment]
PR went in. Closing.
