### ISSUE TITLE
kokkos-kernels:  too long file-name

### ISSUE THREAD

**Issue by looooo** [trilinos/Trilinos#5700]
## Bug Report
@trilinos/kokkos

### Description
Problem occurs with trilinos build for conda on windows. It's not really a bug but maybe it can be easily fixed. So I ask if this file can be renamed to something not as long as:
`KokkosSparse_gauss_seidel_apply_eti_spec_inst_Kokkos_complex_double__int_int64_t_LayoutLeft_Cuda_CudaHostPinnedSpace_CudaHostPinnedSpace.cpp`

problem occurs here: https://github.com/conda-forge/trilinos-feedstock/pull/23#issuecomment-520312932

**Comment by jhux2** [comment]
@trilinos/kokkos

**Comment by jhux2** [comment]
@trilinos/kokkos-kernels

**Comment by sethrj** [comment]
Duplicate of https://github.com/trilinos/Trilinos/issues/4571 and https://github.com/kokkos/kokkos-kernels/issues/395 .

**Comment by mhoemmen** [comment]
It's also a bit goofy that we're instantiating a sequential algorithm for every possible device type and memory space.  This would be a good use case for `Kokkos::AnonymousSpace`.  It's also related to https://github.com/trilinos/Trilinos/issues/1543 .
