### ISSUE TITLE
DUPLICATE: Use RAM high watermark scripts to help diagnose expense build targets for Trilinos

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#5703]
@trilinos/framework, @william76, @nmhamster 

This story is to track efforts to locate and try some compiler wrapper scripts that can provide estimates of the high watermark for RAM usage to build object files and perform links while building Trilinos.  This can help determine where work is needed to reduce the cost of building Trilinos and to determine if efforts to reduce the cost of building are improving things.

Some compiler wrapper scripts were created for this purpose as part of that ATDM Performance project that @nmhamster was running until a few months ago.

**Comment by bartlettroscoe** [comment]
@nmhamster, can you please point @ZUUL42 and @william76 to the location of the compiler wrapper scripts developed as part of your own ATDM Performance project that can give the high watermark for RAM usage to build various targets like object files and link libraries and exectuables?

**Comment by bartlettroscoe** [comment]
From: Bartlett, Roscoe A 
Sent: Tuesday, August 13, 2019 12:10 PM
To: Mclendon, William C III ; Hammond, Simon David 
Cc: Willenbring, James M
Subject: RE: Trilinos Meeting Follow Up : High water mark RAM scripts

Hello Will,

I just created the following issue for this:

   https://github.com/trilinos/Trilinos/issues/5703

Hello Si,

Can you please point Will to the location of the compiler wrapper scripts that were developed as part of your ATDM Performance project and add a comment to:

   https://github.com/trilinos/Trilinos/issues/5703

thanks,

-Ross

From: Mclendon, William C III 
Sent: Tuesday, August 13, 2019 11:34 AM
To: Bartlett, Roscoe A
Subject: Trilinos Meeting Follow Up : High water mark RAM scripts

Hey Ross,

Just shooting you an email reminder that we should follow up after the discussion on today’s Trilinos meeting about getting the memory high water mark scripts from Si over to me so I can test them out with the Xpetra ETI work.

-William

**Comment by jjellio** [comment]
These scripts may the things I wrote (they weren't part of APT though, I used them to figure out build errors).

I've attached a tarball, they live in a private Gitlab (SRN) repo.  If they can live elsewhere that is more accessible, I am happy to support them.

 They use /usr/bin/time, which provides CSV output of everything from /proc/status.

They scripts create compiler/linker wrappers when you run do-configure, then they create "*.timing" files when you execute the build command.

When finished, you can GNU Find all *.timings, and concatenate them to get a large CSV of file + timing data. I also have a viz tool that plots these using shaded rectangles representing whatever metric you want (e.g., time)
[jje-build-tools.tar.gz](https://github.com/trilinos/Trilinos/files/3507203/jje-build-tools.tar.gz)

**Comment by bartlettroscoe** [comment]
This is a duplicate of newer issue #7376.  We about have that (see PR #7508).

**Comment by bartlettroscoe** [comment]
Close as duplicate.
