### ISSUE TITLE
Nalu application code diffs noted in head Trilinos

### ISSUE THREAD

**Issue by spdomin** [trilinos/Trilinos#572]
Last week, a commit tracked to Hoemann was found to cause diffs. After accepting these diffs, this past weekend (after the next update cycle), I am again seeing new diffs.

Has the head been updated again?

Shall I bisect?

**Comment by jwillenbring** [comment]
@bmpersc can comment on when the head was last updated.

**Comment by mhoemmen** [comment]
Diffs may result from our fixes to outstanding serious Ifpack2 issues, like #64.  We need information on the gravity of those diffs, especially if we're being asked to revert commits that clearly appear to have increased code quality.

**Comment by spdomin** [comment]
This is the second set of diffs noted in the past week. Any way that we can understand how your changes are affecting application codes before you push?

**Comment by spdomin** [comment]
What is the ifpack2 interface that recovers the following commit: 

Ifpack2::Details::Chebyshev: Fix #64 (failing Ifpack2_Cheby_belos test

From an application perspective, what is the preferred option?

**Comment by bmpersc** [comment]
The last update I did was on Friday morning. I don't know the exact time, but that shouldn't matter. 

Is tracking when these updates happen going to be something that we need to do going forward? Once we go to an automated process the updates will happen when they happen and tracking that down, while possible, won't be time well spent IMO. We can find a way to track this information, but honestly when the update from develop to master happens should be inconsequential. It is knowing which commit broke things that matters. As Stefan pointed out this is obtainable with git bisect.

**Comment by spdomin** [comment]
After meetings with the appropriate party, a path forward was decided upon. In the end, I was able to revert my previous NaluRtest changes. With this revert, the current head code base in Trilinos produced zero diffs. Therefore, the conclusion is that no Nalu test produced an estimate of the systems eigenvalues that were negative. 

Now that the current Trilinos behavior replicates the historic Chebychev implementation (assuming no problem systems) all is well. 

The Trilinos team can feel free to close the ticket.
