### ISSUE TITLE
Framework: Create Debug Build

### ISSUE THREAD

**Issue by ZUUL42** [trilinos/Trilinos#5728]
## Enhancement
@trilinos/framework

Create a debug build. This will help ensure codebase readiness for developers.
Look into performance considerations/build duration. So this will first be tried in dev->master.

**Comment by bartlettroscoe** [comment]
This is for a PR build, right?  We already have plenty of post-push pure debug builds in the ATDM Trilinos builds we are maintaining.  What we really need is a PR build that is a pure debug build, meaning:

* `CMAKE_BUILD_TYPE=DEBUG`
* `Trilinos_ENABLE_DEBUG=ON`

**Comment by prwolfe** [comment]
This is old - we currently run a debug build using gcc 7.2.0 (see #7850 and #7581
