### ISSUE TITLE
Epetra_VbrMatrix::ExtractGlobalRowCopy has not been implemented yet.

### ISSUE THREAD

**Issue by RATATATO** [trilinos/Trilinos#574]
When I used Epetra_VbrMatrix::ExtractGlobalRowCopy in my source, my program outputted "Must implement....". and no elements were copied to an array.

Here is an example.
https://gist.github.com/RATATATO/5aaae9ed130d9bed87cb779531b25a84

Output is as follow

```
Must implement...
ExtractGlobalRowCopy: -1 -1 
ExtractMyRowCopy: 1 4
```

**Comment by jwillenbring** [comment]
@maherou Chetan was the last one to touch this line. Do you remember why the code is in this state?

https://github.com/trilinos/Trilinos/blame/master/packages/epetra/src/Epetra_VbrMatrix.cpp
