### ISSUE TITLE
ROL test failures when using the checkin script

### ISSUE THREAD

**Issue by jhux2** [trilinos/Trilinos#576]
@trilinos/rol 
Hi,
  Earlier this week I was running the checkin script to test some changes in Tpetra (issue #568).  During that process, some ROL tests failed, independently of the changes I was testing.  The tests are:

```
    803 - ROL_example_PDE-OPT_poisson_example_01_MPI_4 (Failed)
    804 - ROL_example_PDE-OPT_poisson_example_02_MPI_4 (Failed)
    805 - ROL_example_PDE-OPT_poisson-boltzmann_example_01_MPI_4 (Failed)
    806 - ROL_example_PDE-OPT_poisson-topOpt_example_01_MPI_4 (Failed)
    807 - ROL_example_PDE-OPT_stefan-boltzmann_example_03_MPI_4 (Failed)
    808 - ROL_example_PDE-OPT_stefan-boltzmann_example_04_MPI_4 (Failed)
    809 - ROL_example_PDE-OPT_elasticity_example_01_MPI_1 (Failed)
    810 - ROL_example_PDE-OPT_elasticity_example_02_MPI_1 (Failed)
    811 - ROL_example_PDE-OPT_adv-diff-react_example_01_MPI_4 (Failed)
    812 - ROL_example_PDE-OPT_adv-diff-react_example_02_MPI_4 (Failed)
    813 - ROL_example_PDE-OPT_stoch-adv-diff_example_01_MPI_4 (Failed)
```

I didn't see these failures on the dashboard.  Ultimately I was able to work around this, but wanted to let the ROL team know in case they want to investigate.

**Comment by jhux2** [comment]
This build was using gcc/4.8.4 and mpich-1.4.1p1.  The configure scripts are attached.
[do-configure-base.txt](https://github.com/trilinos/Trilinos/files/433269/do-configure-base.txt)
[do-configure.txt](https://github.com/trilinos/Trilinos/files/433270/do-configure.txt)

**Comment by mhoemmen** [comment]
@trilinos/rol @gregvw @dridzal

**Comment by dridzal** [comment]
I haven't been able to re-create these failures with the SEMS version of gcc/4.8.4 and OpenMPI.  I don't have mpich.  @jhux2 , could you give us an idea about the type of failures (errors, timeouts)?  And what do you mean by "work around"; did you have to modify code to make these tests pass?  Thanks, Denis

**Comment by jhux2** [comment]
@dridzal I looked at a sample of the tests.   The issue appears to be that the tests require Amesos2 with KLU2 enabled.  Here's an example:

```
ctest -R  ROL_example_PDE-OPT_stoch-adv-diff_example_01_MPI_4 -VV
test 84
    Start 84: ROL_example_PDE-OPT_stoch-adv-diff_example_01_MPI_4

84: Test command: /usr/local/mpich2/1.4.1p1_gcc_4.4.7/bin/mpiexec "-np" "4" "/home/scratch/checkin/Trilinos/CHECKIN/MPI_SS_DEBUG/packages/rol/example/PDE-OPT/stoch-adv-diff/ROL_example_PDE-OPT_stoch-adv-diff_example_01.exe" "PrintItAll"
84: Test timeout computed to be: 9.99988e+06
84: Total number of processors: 1
84: Number of nodes = 1089
84: Number of cells = 1024
84: Number of edges = 2112
84: Cell offsets across processors: {0}
84: /home/scratch/checkin/Trilinos/packages/amesos2/src/Amesos2_Factory.hpp:592:
84: 
84: Throw number = 1
84: 
84: Throw test that evaluated to true: true
84: 
84: KLU2 is not enabled or is not supported
84: /home/scratch/checkin/Trilinos/packages/amesos2/src/Amesos2_Factory.hpp:592:
```

I use SuperLU in my checkin process.  KLU2 is hardwired in ```rol/example/PDE-OPT/stoch-adv-diff/constraint.hpp```.  A possible solution is to query Amesos2 in ```constraint.hpp``` to see which direct solver is available, and use that one.  It's possible that the test would still fail if Amesos2 doesn't have any direct solvers available.  A more robust solution would be to check at configure time in ```CMakeLists.txt```.

By "work around", I just meant that I disabled the failing tests.

**Comment by dridzal** [comment]
I thought that Amesos2 would at least build KLU2.  What if you didn't have SuperLU?  Would it not build anything?  If you enable Amesos2, then, in my opinion, it is implied that you want to solve a linear system with it.  Including @srajama1 for clarification: What is the best solution here?

**Comment by srajama1** [comment]
I will enable it by default, now that so many users are using it. The reason for not enabling it by default no longer exist. Sorry for the trouble.

**Comment by jhux2** [comment]
> I thought that Amesos2 would at least build KLU2. What if you didn't have SuperLU? Would it not build anything? If you enable Amesos2, then, in my opinion, it is implied that you want to solve a linear system with it. Including @srajama1 for clarification: What is the best solution here?

Looking back at my configure, in fact I explicitly *disabled* KLU2.  A user can alway configure Amesos2 without KLU2 (which is what I did).   So in my opinion there needs to be guard to only enable the test if KLU2 is available.

**Comment by srajama1** [comment]
I must have had a brain freeze. It is enabled by default ! I did it long time ago. This is Jonathan disabling it as he said above (Why ?).

**Comment by dridzal** [comment]
?I disagree.  I don't think that we should support the possibility of do-nothing packages.  In that case the user should disable the entire package.


________________________________

**Comment by jhux2** [comment]
> ?I disagree. I don't think that we should support the possibility of do-nothing packages. In that case the user should disable the entire package.

Here's the relevant part of my configure:

```
-D TPL_ENABLE_SuperLU:BOOL=OFF \
-D Amesos2_ENABLE_KLU2:BOOL=OFF \
-D Amesos2_ENABLE_Basker:BOOL=ON \
```
Amesos2 *is* providing a direct solver, just not the one required by the ROL tests that failed.  So I disagree -- it should be the job of the ROL tests to check for the presence of KLU2.

**Comment by dridzal** [comment]
?OK, so which solver is always enabled in Amesos2?


________________________________

**Comment by dridzal** [comment]
@srajama1 , @jhux2 to simplify the question:  If I want to make sure that I run Amesos2, which solver or which "factory" options should I use?  In other words, how do I make sure that enabling Amesos2 will execute these tests properly?  I really don't care about which solver it is, as long as Amesos2 picks something.  It seems strange that I would have to guard against both the package being disabled and a suboption of the package being disabled.

**Comment by srajama1** [comment]
You can use the query() to see if the solver you want is there. Grep for "query" in Amesos2 example to see the usage. The trouble is Amesos2 has no control over what the users choose to disable. They can disable all the solvers that comes with the package, which I don't know why. 

I can put in an option something like : Give me the name of any one solver available, with default being KLU2 ? If not it will give you whatever was configured. If there is more than one, it will pick something. You can then use it to create the solver. Will that be useful ?

**Comment by dridzal** [comment]
Yes, that would be very useful.  Another, possibly simpler option may be to always build at least one solver that does not require a TPL, like KLU2 or Basker, and let people know which solver this is.  This would simply mean that you don't let users disable one of the solvers.  This is important for ROL, for example, to get good test coverage regardless of what the user chose in their configure script.  Basically, there should always be a default, working option if Amesos2 is enabled (and it obviously can't be a TPL-based option).


________________________________

**Comment by srajama1** [comment]
Actually, KLU2 is that option :). Jonathan is disabling it. I am just wondering why ...

**Comment by jhux2** [comment]
Siva Rajamanickam wrote on 08/26/2016 09:02 AM:
 >
 > Actually, KLU2 is that option :). Jonathan is disabling it. I am just 
wondering why ...
 >

It's a checkin configure script I've been using for a long time, I don't 
remember why I chose Basker.

**Comment by dridzal** [comment]
Because he can.  It may be best not to give users this option at all.  It would be nice if we could always have KLU2 available.  This would avoid a lot of configure-time and/or run-time logic.


________________________________

**Comment by srajama1** [comment]
I believe that can be done. Let me see. One trouble could be if someone sends in a matrix with fancy scalar types. I don't want it to go to KLU2 (even though it is templated). It has to go to Basker. The default solver has to be able to handle all options, which makes it tricky.

**Comment by dridzal** [comment]
I would be OK with Basker as well, as long as there is a default that always works.


________________________________

**Comment by dridzal** [comment]
I believe this issue has not been fully resolved.  After some further thought, I think that always building KLU2 should be the default.  In other words, not offering an option to disable it.  This will be the main solver for Xyce once @hkthorn is done with the transition to the Tpetra stack.  Again, there should be no harm in building it.  If a different solver is needed for fancy scalar types, then the user can enable that solver in addition to KLU2.
