### ISSUE TITLE
Compilation error for Albany due to missing Phalanx header

### ISSUE THREAD

**Issue by ikalash** [trilinos/Trilinos#5764]
Did the Phalanx_TypeStrings.hpp header go away, or get replaced by something else?  

We are getting the following compilation error in our Albany nightlites: 

```
repos/Albany/src/./PHAL_AlbanyTraits.hpp:18:10: fatal error: Phalanx_TypeStrings.hpp: No such file or directory
```

http://cdash.sandia.gov/CDash-2-3-0/viewBuildError.php?buildid=88177

@trilinos/phalanx

**Comment by rppawlo** [comment]
Yes. Use Phalanx_Print.hpp.

**Comment by ikalash** [comment]
Thanks, @rppawlo .  It would have been nice to get some kind of heads up about the upcoming change, as it required quite a bit of changes in Albany to get the code to compile again.

**Comment by rppawlo** [comment]
Sorry @ikalash. Didn't realize an app was using this directly. It should have been a simple search and replace. Here's the script using trilnos tools that I used to fix use in panzer:

```
#!/bin/bash
## run this script with the following:
## find . -name '*pp' -exec ~/refactor4 '{}' \;
perl ~/Trilinos/commonTools/refactoring/string-replace.pl "typeAsString" "print" "$1" "$1"
perl ~/Trilinos/commonTools/refactoring/string-replace.pl "Phalanx_TypeStrings.hpp" "Phalanx_Print.hpp" "$1" "$1"
```

**Comment by ikalash** [comment]
Yes, it wasn't bad, as you said, just a search and replace.  It did touch a lot of files though - it surprised me somewhat how extensive our usage of typeAsString was.  Anyway, no worries, all is good now!

**Comment by nestordemeure** [comment]
I just got the same error compiling Albany with the default Spack command : `spack install albany`

(which is problematic as one is not expected to modify the sources when using Spack)
