### ISSUE TITLE
Zoltan2: imbalance metrics reporting no imbalance when all vertices assigned to part 0

### ISSUE THREAD

**Issue by gslota** [trilinos/Trilinos#578]
When evaluating the metrics after performing partitioning, no imbalance is reported (imbalance = 1) when all vertices end up assigned to part 0, even when the target number of parts is >=2. The expected behavior would be, e.g. for target num parts = 2, that the reported imbalance would also be 2 when this occurs.

To reproduce:
Configure and compile Trilinos with Zoltan2 and PuLP enabled
$ export OMP_NUM_THREADS=1
$ mpirun -n 4 ./Zoltan2_test_driver.exe driverinputs/pulpVwgtTest.xml

**Comment by kddevin** [comment]
The real bug here:  The metric evaluation uses the actual number of parts that exist rather than the target number of parts for the solution.  The fix should be easy; I'll look at it within a week.

**Comment by kddevin** [comment]
@gslota This issue is now fixed.  Let me know if you continue to see errors.
