### ISSUE TITLE
SEACAS: SEACASIoss_pamgen_exodus_io_info randomly failing on ATDM ride builds

### ISSUE THREAD

**Issue by fryeguy52** [trilinos/Trilinos#5784]
## Bug Report
CC: @trilinos/seacas, @kddevin (Trilinos Data Services Product Lead), @bartlettroscoe, @fryeguy52
 
<Checklist>
<???: Add label "ATDM">
<???: Add label "bug"?>
<???: Add label for affected packages (e.g. "MueLu", "Tpetra", "Kokkos", etc.)>
<???: Add milestone "Initial cleanup of new ATDM builds of Trilinos" or "Keep promoted ATDM builds of Trilinos clean">
<???: Once GitHub Issue is created, add entries for tests to TrilinosATDMStatus/*.csv files>
<???: Add label "PA: ???Project Area???" (e.g. "PA: Linear Solvers", "PA: Data Services")>
 
## Next Action Status
<status-and-or-first-action>
 
## Description
 
As shown in [this query](https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-&field2=testname&compare2=61&value2=SEACASIoss_pamgen_exodus_io_info&field3=buildstarttime&compare3=84&value3=2019-08-23T04%3A01%3A00UTC&field4=buildstarttime&compare4=83&value4=2019-07-24T04%3A01%3A00UTC&field5=status&compare5=61&value5=Failed) the test:
* SEACASIoss_pamgen_exodus_io_info

is failing randomly in the builds:
* Trilinos-atdm-white-ride-gnu-7.2.0-openmp-release
* Trilinos-atdm-white-ride-gnu-7.2.0-openmp-debug
* Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-release-debug-pt
* Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-release-debug
* Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-release
* Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-rdc-release-debug
* Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-debug

Since 2019-08-15 this test has failed 12 times in the above builds.  
```
TEST_5

Running: "diff" "info_exodus.out" "info_pamgen.out"

--------------------------------------------------------------------------------

0a1,8
> ibv_exp_query_device: invalid comp_mask !!! (comp_mask = 0x1002541cb40 valid_mask = 0x1)
> [ride14][[59966,1],0][btl_openib_component.c:1648:init_one_device] error obtaining device attributes for mlx5_1 errno says Invalid argument
> --------------------------------------------------------------------------
> WARNING: There was an error initializing an OpenFabrics device.
> 
>   Local host:   ride14
>   Local device: mlx5_1
> --------------------------------------------------------------------------

--------------------------------------------------------------------------------

TEST_5: Return code = 1
TEST_5: Pass criteria = Zero return code [FAILED]
TEST_5: Result = FAILED

```

<details>
  <summary>Click to see new commits on 2019-08-15:</summary>
  
  ## Commits on 2019-08-15
  *** Base Git Repo: Trilinos
f24c6b9:  Merge remote-tracking branch 'origin/develop' into atdm-nightly
Author: Roscoe A. Bartlett <rabartl@sandia.gov>
Date:   Wed Aug 14 21:05:28 2019 -0600

de9498e:  Merge pull request #5588 from cgcgcg/miniem-pr
Author: Christian Glusa <cgcgcg@users.noreply.github.com>
Date:   Wed Aug 14 17:32:54 2019 -0600

dc908d5:  Merge Pull Request #5707 from gsjaardema/Trilinos/seacas-pamgen-fix
Author: trilinos-autotester <trilinos-autotester@trilinos.org>
Date:   Wed Aug 14 17:03:03 2019 -0600

e353e9b:  Merge Pull Request #5710 from trilinos/Trilinos/rstumin-12a8ec1
Author: trilinos-autotester <trilinos-autotester@trilinos.org>
Date:   Wed Aug 14 16:44:20 2019 -0600

30fcc03:  Merge Pull Request #5709 from trilinos/Trilinos/jhu-96d41c2
Author: trilinos-autotester <trilinos-autotester@trilinos.org>
Date:   Wed Aug 14 15:50:00 2019 -0600

a162e6d:  IOSS: summary to cout, not cerr, to match other output
Author: Greg Sjaardema <gdsjaar@sandia.gov>
Date:   Wed Aug 14 13:01:11 2019 -0600

M	packages/seacas/libraries/ioss/src/main/io_info.C

12a8ec1:  Fix up diagonal term in Jacobi/GS calculation so that we do a sum now instead of a scaling.
Author: rstumin <rstumin@sandia.gov>
Date:   Wed Aug 14 12:00:38 2019 -0600

M	packages/muelu/research/mmayr/composite_to_regions/src/SetupRegionHierarchy_def.hpp
M	packages/muelu/research/mmayr/composite_to_regions/src/SetupRegionSmoothers_def.hpp
M	packages/muelu/research/regionMG/examples/structured/Driver_Structured_Regions.cpp

96d41c2:  Tpetra: fixing README mistake
Author: Jonathan Hu <jhu@sandia.gov>
Date:   Wed Aug 14 11:45:26 2019 -0600

M	packages/tpetra/core/example/BlockCrs/README.md

167c8ce:  MueLu: add guard if Galeri is disabled
Author: Jonathan Hu <jhu@sandia.gov>
Date:   Wed Aug 14 11:41:24 2019 -0600

M	packages/muelu/test/structured/CMakeLists.txt

29dc756:  IOSS: add / fix pamgen tests
Author: Greg Sjaardema <gdsjaar@sandia.gov>
Date:   Wed Aug 14 09:52:37 2019 -0600

M	packages/seacas/libraries/ioss/src/main/CMakeLists.txt
M	packages/seacas/libraries/ioss/src/main/test/pamgen_to_unstructured_cgns.gold

3b131d6:  IOSS: pamgen - handle connectivity_raw
Author: Greg Sjaardema <gdsjaar@sandia.gov>
Date:   Wed Aug 14 09:52:13 2019 -0600

M	packages/seacas/libraries/ioss/src/pamgen/Iopg_DatabaseIO.C

de83894:  IOSS: Eliminate dead-lock in thread-safe code
Author: Greg Sjaardema <gdsjaar@sandia.gov>
Date:   Wed Aug 14 09:51:55 2019 -0600

M	packages/seacas/libraries/ioss/src/Ioss_DatabaseIO.h
M	packages/seacas/libraries/ioss/src/Ioss_Region.C

4db1a66:  SEACAS: ioss - add pamgen tests
Author: gsjaardema <gsjaardema@gmail.com>
Date:   Wed Aug 14 09:19:25 2019 -0600

M	packages/seacas/libraries/ioss/src/main/CMakeLists.txt
A	packages/seacas/libraries/ioss/src/main/test/pamgen_to_unstructured_cgns.gold

e1860ea:  IOSS: Fix pamgen block_membership; add nodeset alias
Author: gsjaardema <gsjaardema@gmail.com>
Date:   Wed Aug 14 08:50:37 2019 -0600

M	packages/seacas/libraries/ioss/src/pamgen/Iopg_DatabaseIO.C
M	packages/seacas/libraries/ioss/src/pamgen/Iopg_DatabaseIO.h

55e7c44:  MiniEM: Fix bug in discrete gradient
Author: Christian Glusa <caglusa@sandia.gov>
Date:   Wed Jul 31 15:11:23 2019 -0600

M	packages/panzer/mini-em/src/solvers/MiniEM_DiscreteGradient.hpp

ef914ba:  MiniEM: Refactor solvers
Author: Christian Glusa <caglusa@sandia.gov>
Date:   Sat Jul 27 00:18:23 2019 -0600

M	packages/panzer/mini-em/example/BlockPrec/main.cpp
M	packages/panzer/mini-em/example/BlockPrec/solverAugmentation.xml
M	packages/panzer/mini-em/example/BlockPrec/solverAugmentationEpetra.xml
M	packages/panzer/mini-em/example/BlockPrec/solverAugmentationUseILU.xml
M	packages/panzer/mini-em/example/BlockPrec/solverMLRefMaxwell.xml
M	packages/panzer/mini-em/example/BlockPrec/solverMueLuRefMaxwell.xml
M	packages/panzer/mini-em/example/BlockPrec/solverMueLuRefMaxwellEpetra.xml
M	packages/panzer/mini-em/src/solvers/MiniEM_FullMaxwellPreconditionerFactory.cpp
M	packages/panzer/mini-em/src/solvers/MiniEM_FullMaxwellPreconditionerFactory.hpp
A	packages/panzer/mini-em/src/solvers/MiniEM_FullMaxwellPreconditionerFactory_Augmentation.cpp
C056	packages/panzer/mini-em/src/solvers/MiniEM_FullMaxwellPreconditionerFactory.hpp	packages/panzer/mini-em/src/solvers/MiniEM_FullMaxwellPreconditionerFactory_Augmentation.hpp
A	packages/panzer/mini-em/src/solvers/MiniEM_Utils.cpp
A	packages/panzer/mini-em/src/solvers/MiniEM_Utils.hpp

6f1e277:  MiniEM: Add discrete curl
Author: Christian Glusa <caglusa@sandia.gov>
Date:   Fri Jul 26 19:07:16 2019 -0600

M	packages/panzer/mini-em/example/BlockPrec/main.cpp
A	packages/panzer/mini-em/src/solvers/MiniEM_DiscreteCurl.hpp
M	packages/panzer/mini-em/src/solvers/MiniEM_FullMaxwellPreconditionerFactory.cpp
M	packages/panzer/mini-em/src/solvers/MiniEM_FullMaxwellPreconditionerFactory.hpp

7ad3115:  MiniEM: Simple changes to Maxwell preconditioner
Author: Christian Glusa <caglusa@sandia.gov>
Date:   Fri Jul 26 19:06:29 2019 -0600

M	packages/panzer/mini-em/example/BlockPrec/main.cpp
M	packages/panzer/mini-em/src/solvers/MiniEM_FullMaxwellPreconditionerFactory.cpp
M	packages/panzer/mini-em/src/solvers/MiniEM_FullMaxwellPreconditionerFactory.hpp

</details>

<more-details>

## Current Status on CDash

A current 2 week history of this test on ATDM ride builds can be found [here](https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-&field2=testname&compare2=61&value2=SEACASIoss_pamgen_exodus_io_info&field3=buildstarttime&compare3=84&value3=now&field4=buildstarttime&compare4=83&value4=2%20weeks%20ago&field5=site&compare5=61&value5=ride)
## Steps to Reproduce

One should be able to reproduce this failure on ride or white as described in:
* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md

More specifically, the commands given for ride or white are provided at:
* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#ridewhite

The exact commands to reproduce this issue should be:
```
$ cd <some_build_dir>/
$ source $TRILINOS_DIR/cmake/std/atdm/load-env.sh Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-release
$ cmake \
 -GNinja \
 -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
 -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_SEACAS=ON \
 $TRILINOS_DIR
$ make NP=16
$ bsub -x -Is -q rhel7F -n 16 ctest -j16
```

**Comment by bartlettroscoe** [comment]
CC: @rppawlo, @trilinos/framework 

Looks like this same random failure just took out the [lastest PR iteration](https://github.com/trilinos/Trilinos/pull/5829#issuecomment-530611903) for PR #5829 shown [here](https://testing.sandia.gov/cdash/testDetails.php?test=88830939&build=5616141) showing:

```
ibv_exp_query_device: invalid comp_mask !!! (comp_mask = 0x10032271e40 valid_mask = 0x1)
[ride11][[64882,1],0][btl_openib_component.c:1648:init_one_device] error obtaining device attributes for mlx5_1 errno says Invalid argument
```

@gsjaardema,

Any idea what is causing this?  Does this test protect important functionality used by ATDM or other important customers with CUDA?

**Comment by gsjaardema** [comment]
Not sure what is causing this but the test can be disabled.

.. greg

**Comment by bartlettroscoe** [comment]
> Not sure what is causing this but the test can be disabled.

Can we disable this test for all CUDA builds for now?  It does not seem to be failing in non-CUDA builds so no need to disable for those.

**Comment by gsjaardema** [comment]
This test is consistently passing.  Last failures were 09-24.

**Comment by bartlettroscoe** [comment]
> This test is consistently passing. Last failures were 09-24.

Okay, [this query](https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&begin=2019-09-01&end=2019-10-04&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-&field2=testname&compare2=61&value2=SEACASIoss_pamgen_exodus_io_info&field3=status&compare3=62&value3=notrun) seems to confirm the last failure of this test was on 2019-09-25.

@gsjaardema, did you do something to fix this?

**Comment by gsjaardema** [comment]
Yes, I changed the method of determining success/failure.  I thought I had mentioned the issue number in the commit, but obviously I didn't.  It was part of the last seacas snapshot...
