### ISSUE TITLE
PanzerAdaptersSTK_tDOFManager2_SimpleTests_MPI_4 timing out randomly in build Trilinos-atdm-sems-rhel7-cuda-9.2-Volta70-complex-static-release-debug starting 2019-07-04

### ISSUE THREAD

**Issue by fryeguy52** [trilinos/Trilinos#5786]
## Bug Report
CC: @trilinos/panzer, @mperego (Trilinos Discretizations Product Lead), @bartlettroscoe, @fryeguy52
 
 
## Next Action Status
<status-and-or-first-action>
 
## Description
 
As shown in [this query](https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercount=6&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-&field2=testname&compare2=65&value2=PanzerAdaptersSTK_tDOFManager2_SimpleTests_MPI_4&field3=buildstarttime&compare3=84&value3=2019-08-23&field4=buildstarttime&compare4=83&value4=2019-07-01&field5=status&compare5=61&value5=Failed&field6=details&compare6=63&value6=Timeout) the tests:
* PanzerAdaptersSTK_tDOFManager2_SimpleTests_MPI_4

is randomly timing out in the build:
* Trilinos-atdm-sems-rhel7-cuda-9.2-Volta70-complex-static-release-debug

<more-details>

When this test passes, it does so in less than 5 seconds.  When it fails it is a timeout with the output:
```
***
*** Unit test suite ...
***


Sorting tests by group name then by the order they were added ... (time = 8.82e-06)

Running unit tests ...

0. DOFManager_tests_BasicCreation_UnitTest ... [Passed] (0.0274 sec)
1. DOFManager_tests_ReorderingFields_UnitTest ... [Passed] (0.0297 sec)
2. DOFManager_tests_myOwnedwithGhosted_UnitTest ... [Passed] (0.0228 sec)
3. DOFManager_tests_gidsAreSet_UnitTest ... [Passed] (0.0266 sec)
4. DOFManager_tests_gidFieldAssociations_UnitTest ... [Passed] (0.0206 sec)
5. DOFManager_tests_3dmyOwnedwithGhosted_UnitTest ... [Passed] (0.0665 sec)
```

## Current Status on CDash

A current 4 week history for this test can be seen [here](https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercount=4&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-sems-rhel7-cuda-9.2-Volta70-complex-static-release-debug&field2=testname&compare2=65&value2=PanzerAdaptersSTK_tDOFManager2_SimpleTests_MPI_4&field3=buildstarttime&compare3=84&value3=now&field4=buildstarttime&compare4=83&value4=4%20weeks%20ago)
## Steps to Reproduce

One should be able to reproduce this failure on with a sems rhel6 environment as described in:
* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md

More specifically, the commands given for with a sems rhel6 environment are provided at:
* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#sems-rhel6-environment

The exact commands to reproduce this issue should be:
```
$ cd <some_build_dir>/
$ source $TRILINOS_DIR/cmake/std/atdm/load-env.sh Trilinos-atdm-sems-rhel7-cuda-9.2-Volta70-complex-static-release-debug
$ cmake \
 -GNinja \
 -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
 -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_Panzer=ON \
 $TRILINOS_DIR
$ make NP=16
$ ctest -j8
```

**Comment by bartlettroscoe** [comment]
@fryeguy52, can you please add the TrilinosATDMStatus/*.csv entry for this test?  Our automated emails don't show this failure associated with this test:

<h3><font color="red">Tests without issue trackers Failed (limited to 20): twiof=???</font></h3>
<table style="width:100%" boarder="1">

<tr>
<th>Site</th>
<th>Build Name</th>
<th>Test Name</th>
<th>Status</th>
<th>Details</th>
<th>Consec­utive Non-pass Days</th>
<th>Non-pass Last 30 Days</th>
<th>Pass Last 30 Days</th>
<th>Issue Tracker</th>
</tr>

<tr>
<td align="left">sems-rhel7</td>
<td align="left"><a href="https://testing-dev.sandia.gov/cdash/index.php?project=Trilinos&amp;filtercombine=and&amp;filtercombine=&amp;filtercount=4&amp;showfilters=1&amp;filtercombine=and&amp;field1=buildname&amp;compare1=61&amp;value1=Trilinos-atdm-sems-rhel7-cuda-9.2-Volta70-complex-static-release-debug&amp;field2=site&amp;compare2=61&amp;value2=sems-rhel7&amp;field3=buildstarttime&amp;compare3=84&amp;value3=2019-09-14T04:01:00UTC&amp;field4=buildstarttime&amp;compare4=83&amp;value4=2019-08-15T04:01:00UTC">Trilinos-atdm-sems-rhel7-cuda-9.2-Volta70-complex-static-release-debug</a></td>
<td align="left"><a href="https://testing-dev.sandia.gov/cdash/testDetails.php?test=75001798&amp;build=4856155">PanzerAdaptersSTK_­tDOFManager2_­SimpleTests_­MPI_­4</a></td>
<td align="left"><a href="https://testing-dev.sandia.gov/cdash/testDetails.php?test=75001798&amp;build=4856155"><font color="red">Failed</font></a></td>
<td align="left">Completed (Timeout)</td>
<td align="right"><a href="https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&amp;filtercombine=and&amp;filtercombine=&amp;filtercount=5&amp;showfilters=1&amp;filtercombine=and&amp;field1=buildname&amp;compare1=61&amp;value1=Trilinos-atdm-sems-rhel7-cuda-9.2-Volta70-complex-static-release-debug&amp;field2=testname&amp;compare2=61&amp;value2=PanzerAdaptersSTK_tDOFManager2_SimpleTests_MPI_4&amp;field3=site&amp;compare3=61&amp;value3=sems-rhel7&amp;field4=buildstarttime&amp;compare4=84&amp;value4=2019-09-14T04:01:00UTC&amp;field5=buildstarttime&amp;compare5=83&amp;value5=2019-08-15T04:01:00UTC"><font color="red">2</font></a></td>
<td align="right"><a href="https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&amp;filtercombine=and&amp;filtercombine=&amp;filtercount=5&amp;showfilters=1&amp;filtercombine=and&amp;field1=buildname&amp;compare1=61&amp;value1=Trilinos-atdm-sems-rhel7-cuda-9.2-Volta70-complex-static-release-debug&amp;field2=testname&amp;compare2=61&amp;value2=PanzerAdaptersSTK_tDOFManager2_SimpleTests_MPI_4&amp;field3=site&amp;compare3=61&amp;value3=sems-rhel7&amp;field4=buildstarttime&amp;compare4=84&amp;value4=2019-09-14T04:01:00UTC&amp;field5=buildstarttime&amp;compare5=83&amp;value5=2019-08-15T04:01:00UTC"><font color="red">4</font></a></td>
<td align="right"><a href="https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&amp;filtercombine=and&amp;filtercombine=&amp;filtercount=5&amp;showfilters=1&amp;filtercombine=and&amp;field1=buildname&amp;compare1=61&amp;value1=Trilinos-atdm-sems-rhel7-cuda-9.2-Volta70-complex-static-release-debug&amp;field2=testname&amp;compare2=61&amp;value2=PanzerAdaptersSTK_tDOFManager2_SimpleTests_MPI_4&amp;field3=site&amp;compare3=61&amp;value3=sems-rhel7&amp;field4=buildstarttime&amp;compare4=84&amp;value4=2019-09-14T04:01:00UTC&amp;field5=buildstarttime&amp;compare5=83&amp;value5=2019-08-15T04:01:00UTC"><font color="green">20</font></a></td>
<td align="right"></td>
</tr>

</table>

**Comment by bartlettroscoe** [comment]
We are not testing Panzer and any other packages used by GEMMA anymore in cuda+complex ATDM Trilinos builds.  (See [ATDV-261](https://sems-atlassian-srn.sandia.gov/browse/ATDV-261)).

Closing as wontfix
