### ISSUE TITLE
Tempus:  Option to select Explicit/Implicit tableau of an IMEX method

### ISSUE THREAD

**Issue by sconde** [trilinos/Trilinos#5790]
## Question
@trilinos/tempus 

An IMEX RK method is a pair of Explicit and Implicit Butcher tableau. I would like to propose that we introduce an option to select either the explicit or implicit tableau of an IMEX RK pair from the input file to get the respective tableau. This will eliminate duplicating the tableau for the Explicit, Implicit, and IMEX method.

This could allow the user, especially in Drekar, to quickly and easily switch between Explicit, Implicit, and IMEX run for a problem.

What do you think about this? @ccober6 @rppawlo @krcb @eric-c-cyr @seamill

**Comment by eric-c-cyr** [comment]
Seems like a good idea to me.

Sent from my iPad

On Aug 26, 2019, at 6:05 AM, Sidafa Conde <notifications@github.com<mailto:notifications@github.com>> wrote:

Question

@trilinos/tempus<https://github.com/orgs/trilinos/teams/tempus>

An IMEX RK method is a pair of Explicit and Implicit Butcher tableau. I would like to propose that we introduce an option to select either the explicit or implicit tableau of an IMEX RK pair from the input file to get the respective tableau. This will eliminate duplicating the tableau for the Explicit, Implicit, and IMEX method.

This could allow the user, especially in Drekar, to quickly and easily switch between Explicit, Implicit, and IMEX run for a problem.

What do you think about this? @ccober6<https://github.com/ccober6> @rppawlo<https://github.com/rppawlo> @krcb<https://github.com/krcb> @eric-c-cyr<https://github.com/eric-c-cyr> @seamill<https://github.com/seamill>

**Comment by seamill** [comment]
Sounds fine. Dumb question: Does this mean there is only a single allowed implicit tableau for a given explicit tableau in IMEX-RK? If not, how do we chose an acceptable default? For mixed order schemes (like the ones we've been playing with), this could lead to unexpected behavior for the user.

**Comment by ccober6** [comment]
This sounds good.  On the implementation side, we should talk through if this should be just part of the IMEX RK (and Partitioned IMEX RK) stepper, or should be an option to construct an ERK, DIRK or IMEX RK stepper.

Also as a heads up, I am close to finishing the Tempus-Bug-Setting-Tableau-and-Initializing-4965 branch (#4965), which changes how the RK tableaus and steppers are constructed and used.  Before making any changes along these lines, we should talk about it wrt the changes in this branch.

**Comment by sconde** [comment]
I see code duplications: the RK tableaus are repeating in the IMEX RK. 

I propose we construct a Factory of RK tableaus that maps the name to the `RKButcherTableau`. This means that the RK tableaus will be defined only once.
