### ISSUE TITLE
SEACAS:  SEACASIoss_exodus32_to_exodus32 failing in ATDM builds

### ISSUE THREAD

**Issue by fryeguy52** [trilinos/Trilinos#5794]
## Bug Report
CC: @trilinos/seacas, @kddevin (Trilinos Data Services Product Lead), @bartlettroscoe, @fryeguy52 
 
## Next Action Status
<status-and-or-first-action>
 
## Description
 
As shown in [this query](https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-&field2=testname&compare2=61&value2=SEACASIoss_exodus32_to_exodus32&field3=buildstarttime&compare3=84&value3=2019-08-26T04%3A01%3A00UTC&field4=buildstarttime&compare4=83&value4=2019-08-01T04%3A01%3A00UTC&field5=status&compare5=61&value5=Failed) the tests:
* SEACASIoss_exodus32_to_exodus32

is randomly failing in the builds:
* Trilinos-atdm-waterman_cuda-9.2_shared_opt
* Trilinos-atdm-waterman_cuda-9.2_fpic_static_opt
* Trilinos-atdm-waterman-cuda-9.2-release-debug
* Trilinos-atdm-waterman-cuda-9.2-rdc-release-debug
* Trilinos-atdm-waterman-cuda-9.2-debug
* Trilinos-atdm-sems-rhel7-cuda-9.2-Volta70-complex-static-release-debug
* Trilinos-atdm-cee-rhel6_intel-18.0.2_mpich2-3.2_openmp_static_opt
* Trilinos-atdm-cee-rhel6_gnu-7.2.0_openmpi-1.10.2_serial_shared_opt
* Trilinos-atdm-cee-rhel6_clang-5.0.1_openmpi-1.10.2_serial_static_opt

It has failed 17 times since 2019-08-21
Here are some examples of ways it has failed:
```
exodiff: Files are different (# time steps differ)

--------------------------------------------------------------------------------

TEST_1: Return code = 2
TEST_1: Pass criteria = Zero return code [FAILED]
TEST_1: Result = FAILED

================================================================================

OVERALL FINAL RESULT: TEST FAILED (SEACASIoss_exodus32_to_exodus32)
```
```
Reading first file ... 
Reading second file ... 
exodiff: ERROR: Nodal variable names appear corrupt
                A length is 0 or greater than name_size(8)
                Here are the names that I received from a call to ex_get_var_names(...):
		1) ""
		2) ""
		3) ""
		4) ""
		5) ""
		6) ""
		7) ""
		8) ""
		9) ""
		10) ""
		11) ""
		12) ""
                 Aborting...
```
```
exodiff: ERROR: .. First file has 11 result times while the second file has 0.
exodiff: ERROR: Unable to match element 1 in first file with element in second file.
```

## Current Status on CDash

[Current 1 week history on cee-rhel6 builds](https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercount=4&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-cee-rhel6&field2=testname&compare2=61&value2=SEACASIoss_exodus32_to_exodus32&field3=buildstarttime&compare3=84&value3=now&field4=buildstarttime&compare4=83&value4=1%20week%20ago)

[Current 1 week history on waterman builds](https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercount=4&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-waterman&field2=testname&compare2=61&value2=SEACASIoss_exodus32_to_exodus32&field3=buildstarttime&compare3=84&value3=now&field4=buildstarttime&compare4=83&value4=1%20week%20ago)

## Steps to Reproduce

One should be able to reproduce this failure on waterman as described in:
* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md

More specifically, the commands given for waterman are provided at:
* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#waterman

The exact commands to reproduce this issue should be:
```
$ cd <some_build_dir>/
$ source $TRILINOS_DIR/cmake/std/atdm/load-env.sh Trilinos-atdm-waterman-cuda-9.2-debug
$ cmake \
 -GNinja \
 -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
 -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_SEACAS=ON \
 $TRILINOS_DIR
$ make NP=16
$ bsub -x -Is -n 20 ctest -j20
```

**Comment by bartlettroscoe** [comment]
FYI: As described in https://github.com/trilinos/Trilinos/issues/3276#issuecomment-532024413, this looks to be causing the Trilinos PR builds to randomly fail as well.

**Comment by gsjaardema** [comment]
The tests now seem to be passing consistently on the platforms mentioned above.  Can this be closed?

**Comment by bartlettroscoe** [comment]
As shown in [this query](https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&begin=2019-09-01&end=2019-10-04&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-&field2=testname&compare2=61&value2=SEACASIoss_exodus32_to_exodus32&field3=status&compare3=62&value3=notrun) the last time this test failed in an ATDM Trilinos build was on 2019-09-25.  Therefore, it looks like it might be fixed.

@gsjaardema, did you do anything to fix this?

**Comment by bartlettroscoe** [comment]
As shown in [this query](https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&begin=2019-09-08&end=2019-10-08&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm&field2=testname&compare2=61&value2=SEACASIoss_exodus32_to_exodus32&field3=status&compare3=61&value3=failed) the last time this test failed in any ATDM Trilinos build was on 2019-09-25.  Since this test failed 8 times over several builds between 2019-09-17 through 2019-09-25 over the last month, it looks like this failure was resolved.

Closing as complete.
