### ISSUE TITLE
Tpetra::CrsMatrix: Deprecate and remove localSolve

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#581]
@trilinos/tpetra @trilinos/ifpack2 

As discussed in #514, sparse triangular solve properly belongs to a solver or preconditioner package, rather than to Tpetra.  Removing this method would reduce the amount of code to build in Tpetra.  It would also give us the freedom to reduce the cost of fillComplete, by not computing local constants (like whether the matrix is upper or lower triangular).

Tpetra::CrsMatrix::localSolve does give Tpetra users a way to solve triangular systems where the vectors have a different Scalar type than the matrix.  However, KokkosSparse::trsv already exposes this functionality.  Furthermore, putting a local sparse triangular solve in Tpetra may confuse users who think of Tpetra as offering global computational kernels, and who don't understand the difference between "local" and "global."

**Comment by mhoemmen** [comment]
@trilinos/tpetra @jhux2 @csiefer2 @kddevin 

#2644 adds some urgency to this issue.  The implementation of `Tpetra::CrsMatrix::localSolve` (local sparse triangular solve) currently:
  - uses `is{Lower,Upper}Triangular` to decide whether the local matrix is lower or upper triangular, and
  - uses `getNodeNumDiags` to decide whether the local matrix has an explicitly stored diagonal, or an implicitly stored unit diagonal (no local diagonal entries at all means the latter).

In practice, however, callers who want to do sparse triangular solve know whether they have an L or U factor, and know whether to assume an implicitly stored unit diagonal (typical for the L factor in LU or Cholesky).

The real problem is that Tpetra should not take responsibility for what properly belongs to a sparse factorization code.  As a start for fixing this issue, I added `Ifpack2::LocalSparseTriangularSolver`.  Currently, that class just defers to `Tpetra::CrsMatrix::localSolve`.  We can migrate LocalSparseTriangularSolver away from deprecated or to-be-deprecated methods, via the following steps:

  1. Add a method that merges counting local diagonal entries and determining local triangularity, into a single `Kokkos::parallel_reduce` kernel.
  2. Call that method in the `initialize` method of `Ifpack2::LocalSparseTriangularSolver`.
  3. Add a way for callers to tell `Ifpack2::LocalSparseTriangularSolver`, at `initialize` time, whether the input matrix is lower or upper triangular, and whether to assume an implicit unit diagonal.
  4. Change all uses of `Ifpack2::LocalSparseTriangularSolver` (currently just in Ifpack2, as far as I know) to use (3).  The class will still use (2) by default, to preserve current behavior.

The only uncertainty is that `Ifpack2::LocalSparseTriangularSolver` has an optional HTS-based back-end, that may complicate some steps above.  I have no idea whether the HTS back-end has been tested regularly; I doubt very much that it is enabled by default.  @ambrad wrote HTS; please feel free to comment if you have a chance.  Thanks!

**Comment by ambrad** [comment]
Yes, HTS can only do an efficient forward solve, so an HTS object would have to be created for the transpose separately. (However, HTS does not require the input matrix to be explicitly transposed; the user just has to request that HTS build its data structures for the transpose solve.)

**Comment by mhoemmen** [comment]
@ambrad Sorry to be a pest -- I just want to make sure I get it right -- does HTS implement the reverse non-transposed solve?  That is, does HTS handle both L and U?

**Comment by ambrad** [comment]
1. HTS handles L and U, optionally with implicit unit diagonal. These properties are detected automatically.
2. It won't solve L'x = b if you ask it to construct its internal data structures for L.
3. But you can ask it to form data structures for L', given L, and then solve L'x = b.
4. Related to these, it handles row and column permutations and row scaling. The idea is to do everything necessary, in the most efficient way, to solve a problem with UMFPACK-type output: `[L U p q R] = lu(A, 'vector')`.

**Comment by mhoemmen** [comment]
Thanks @ambrad !  This is super helpful! :-D

**Comment by mhoemmen** [comment]
PR #2918 will fix this issue.

**Comment by mhoemmen** [comment]
PR #2918 fixed this issue in develop.  Thanks all!
