### ISSUE TITLE
MueLu: Layout of maps for blocked operators?

### ISSUE THREAD

**Issue by mayrmt** [trilinos/Trilinos#5815]
## Question
@trilinos/muelu @trilinos/xpetra 

When looking at the example `packages/muelu/tests/navierstokes/`, it seems that block matrices use strides maps with the nodal unknowns ordered as [u_x, u_y, p]. I can see, how this is beneficial when thinking about (node-based) aggregation. My guess is that this is related to the parameter list entry "number of PDE equations" (or so...)

However, in some codes unknowns are ordered differently, maybe first all velocity DOFs and then all pressure DOFs. Can this case be dealt with with the blocked operators multigrid as well?

**Comment by lucbv** [comment]
Blocked operators can always be applied regardless of the underlying format. But with the blocked operators you cannot get a monolithic multigrid anymore. I am sure there are trade-offs to blocked vs amalgamated format, if you wanted something monolithic with the second layout you mention, it can probably be done applying some permutation on the top level (internally as to not copy A would be better).

I am not sure I completely answer your question though?

**Comment by mayrmt** [comment]
@lucbv Thanks for you though! I was also convinced, that blocked operators can be applied in any case and that they do not rely on a particular map layout. I'm also fine with separation into velocity and pressure, actually that's my main intention. So, loosing the possibility of a "monolithic" multigrid is ok with me. 

Still, velocity and pressure aggregates need to match (as far as my experience goes). Do you think, that this can be achieved by just reusing the velocity aggregates for the pressure field?

**Comment by tawiesn** [comment]
@mayrmt I can confirm that the blocked operators are independent of the map layout even though certain map layouts make more sense for certain applications than others. In principle, you can choose any kind of map layout. You only need to make sure that you create reasonable aggregates for each block (or reuse existing aggregates, if possible). Aggregates are node-based. So if you want to reuse aggregates, you have to map the dof ids to the corresponding node ids. A very general example you can find with the contact solvers in saddle point formulation.

**Comment by mayrmt** [comment]
@tawiesn thanks a lot for the clarification! I suspected that that is the case.

**Comment by mayrmt** [comment]
Closing this issue, since my question has been answered. I'll reopen, if further questions arise.
