### ISSUE TITLE
Amesos2 MUMPS control over matrix type ( i.e. symmetric, nonsymmetric, ... )

### ISSUE THREAD

**Issue by davoodansari** [trilinos/Trilinos#5819]
From Trilinos 12.8, I am using Amesos2 to solver Tpetra based sparse linear problems.
Between the doc and doxygen I was not able to figure out how to inform the solver that the matrix is symmetric so that I can take advantage of filling only one half of the matrix.

The older documentation mentions MatrixType as a general parameter for amesos2 but this option does not seem to be available in the newer versions of Amesos2. 

Any advice is highly appreciated.

Davood

**Comment by davoodansari** [comment]
Not sure if this helps or not. This is just an attempt to directly mess with MUMPS native parameters. I tried to do some reverse engineering. I used these code lines:
        const char* solverNames = "MUMPS";
        if( !Amesos2::query(solverNames) ) std::cerr << solverNames << " not enabled.  Exiting..." << std::endl;
        amesosSolver = Amesos2::create<MT,MV>(solverNames,A);
        amesosParamList = Teuchos::createParameterList("Amesos2");
        Teuchos::ParameterList &MumpsList = amesosParamList->sublist("MUMPS");
        MumpsList.set("ICNTL(1)", "on");
        amesosSolver->setParameters(amesosParamList);

At run-time I get this error:

terminate called after throwing an instance of 'Teuchos::Exceptions::InvalidParameterType'
  what():  Error!  The parameter "ICNTL(1)" exists
in the parameter (sub)list "Amesos2->MUMPS"
but it does not contain any validator needed to extract
an integral value of type "int"!

Throw number = 1

**Comment by jhux2** [comment]
@trilinos/amesos2

**Comment by srajama1** [comment]
Yes, we do check which parameters get passed. Our support for symmetric problems is not very strong. Is this distributed memory ?

**Comment by davoodansari** [comment]
Currently I am running it on one node only so although MPI is enabled I am
not really using it in the strong sense.
Is there a workaround for this?
I tried to read the code without much luck though.

**Comment by srajama1** [comment]
If you are running on one MPI, it could just work if you just add ICNTL(1) as a valid parameter for MUMPS. It might be just a 3 line change, but no guarantees. We do not test this case at all.

**Comment by davoodansari** [comment]
Can you elaborate where or in which file
I will certainly try if you point with more specifics
Thanks

**Comment by srajama1** [comment]
See
https://github.com/trilinos/Trilinos/blob/82907a1ac1b0be71f966cb52bb5f3fbdaabe5f34/packages/amesos2/src/Amesos2_MUMPS_def.hpp#L318

ICNTL(1) is already recognized, you just need to pass an int instead of on. We just past the int to MUMPS.

**Comment by davoodansari** [comment]
Thank you Siva
ICNTL(1) has nothing to do with use of symmetric matrices. I was merely trying to pass parameters to MUMPS before getting to deep. And I did try to set it to integer 1:

            amesosParamList = Teuchos::createParameterList("Amesos2");
            Teuchos::ParameterList &MumpsList = amesosParamList->sublist("MUMPS");
            MumpsList.set("ICNTL(1)", 1);


 and got this error at runtime:

terminate called after throwing an instance of 'Teuchos::Exceptions::InvalidParameterType'
  what():  Error, the parameter {name="ICNTL(1)",type="int",value="1"}
in the parameter (sub)list "Amesos2->MUMPS"
exists in the list of valid parameters but has the wrong type.

The correct type is "string". 

It seems to me as there is a bug involved in this.
Now the parameter that controls symmtery  is "sym". I don't think we are passing anthing to MUMPS that would control this.

**Comment by davoodansari** [comment]
I added the sym parameter by adding these lines to Amesos2_MUMPS_def.hpp
In setParameters_impl :
    if(parameterList->isParameter("sym"))
      {
        mumps_par.sym = getIntegralValue<local_ordinal_type>(*parameterList,"sym");
      }
In getValidParameters_impl:
pl->set("sym", 0, "See Manual" ); 

Now I am getting the error about validator which I am not sure what it implies or how it can be resolved:

terminate called after throwing an instance of 'Teuchos::Exceptions::InvalidParameterType'
  what():  Error!  The parameter "sym" exists
in the parameter (sub)list "Amesos2->MUMPS"
but it does not contain any validator needed to extract an integral value of type "int"!
Throw number = 1

Any suggestions on how to address this??

**Comment by davoodansari** [comment]
OK, upon further research I was able to create a sol called validator and get to change the mumps_par in Amesos2_MUMPS_def.hpp (with some corrections to the code there as well )
This had absolutely no impact on the solver behavior since the mumps_par struct is passed to the solver via mumps_c function and for the symmetry parameter 'sym' to work it must be set at the time of creation of the solver. This happens in Amesos2_MUMPS_def.hpp inside this function

  MUMPS<Matrix,Vector>::MUMPS(
                              Teuchos::RCP<const Matrix> A,
                              Teuchos::RCP<Vector>       X,
                              Teuchos::RCP<const Vector> B)
    : SolverCore<Amesos2::MUMPS,Matrix,Vector>(A, X, B)
{
.
.
.
}

Question is, how do I get the knowledge of matrix symmetry (or the lack of) into this function?
When creating an Amesos2 solver what native parameter or member is used to indicate the symmetry property of the underlying operator? 

Andy advise is highyl appreciated.
