### ISSUE TITLE
Ifpack2: Do we really need Filters?

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#582]
@trilinos/ifpack2 @jhux @csiefer2 

Any optimized subdomain solver that depends on the structure of the matrix -- e.g., sparse LU or ILU\* -- will want to access the data structures directly.  For example, Ifpack2's ILU(k) or ILUT all take the input RowMatrix -- which may perhaps be a LocalFilter -- and convert it to a CrsMatrix, if it is not already a CrsMatrix. 

This makes me wonder why we need Filters.  It's just another layer between the subdomain solver and its data.  RowMatrix is still a good idea; if a solver needs a CrsMatrix, it can always copy the RowMatrix into a CrsMatrix.

**Comment by mhoemmen** [comment]
See also #560.  Many Ifpack2 filters, such as SingletonFilter, do not correctly implement methods like getGraph().  They either throw, or return the wrong graph.  (The returned graph should be the graph of the filtered matrix, not the graph of the original matrix.)

**Comment by jhux** [comment]
Hello,

I’m not quite sure why I’m receiving these email notifications in unaware of any of these issue. Is this something I worked on in the past?

Regards,
Joshua Hux
Associate Developer
Collaborative Consulting
Office: 715-393-4965 |Cell: (715) 803-8949 | www.collaborative.com<http://www.collaborative.com/>
[Description: M:\Design\Logos\Tagline Logos\tagline - CDSC logo\Logo-Tagline to right-smaller.jpg]
Collaborative Domestic Solution Center | 500 First Street Suite 7000| Wausau, WI 54403 | Phone 715-393-4700

**Comment by mhoemmen** [comment]
@jhux Sorry about that!  I meant to tag @jhux2 but forgot the "2" at the end :-)
