### ISSUE TITLE
STK: stk-search fails to compile with gcc 9 and OpenMP

### ISSUE THREAD

**Issue by rppawlo** [trilinos/Trilinos#5827]
## Bug Report
@alanw0 

### Description
When building stk-search under gcc 9, most of the openmp code in stk_search fails to compile. Details are in the “OpenMP data sharing” section at:

https://www.gnu.org/software/gcc/gcc-9/porting_to.html
 
> GCC releases before 9 were implementing an OpenMP 3.1 data sharing rule that const qualified variables without mutable member are predetermined shared, ... GCC 9 started implementing the OpenMP 4.0 and later behavior. When not using default clause or when using default(shared), this makes no difference, but if using default(none), previously the choice was not specify the const qualified variables on the construct at all, ...

The errors are attached. 

[stk_search_errors.txt](https://github.com/trilinos/Trilinos/files/3560598/stk_search_errors.txt)

### Steps to Reproduce
Build stk-search with OpenMP enabled using gcc 9 compilers.

Thanks to StefanBruens for identifying the issue for epetra in #5390

**Comment by alanw0** [comment]
@rppawlo Sorry I forgot to update this issue sooner, I fixed these compile errors a week or two ago. (At least I think so, we don't have gcc 9 on the sierra systems so I had trouble reproducing the issue...)
