### ISSUE TITLE
Teuchos add feature to dump timer data without it being the end of the run

### ISSUE THREAD

**Issue by bathmatt** [trilinos/Trilinos#5833]
## Enhancement
@trilinos/teuchos 

I have runs that start to really slow down due to work load increasing exponentially, i'd like to set up the code to dump out the stacked timer every 100 steps or so...  

@rppawlo would you have time to look at it?

**Comment by mhoemmen** [comment]
Is that really a Teuchos feature?  You would just need to call `Teuchos::TimeMonitor::report` at some point.

**Comment by rppawlo** [comment]
@bathmatt - sure I can take care of this. On the trilinos side I think that all we need is a reset method on the stacked timer to clear out all counters and timer data. Then the app can call and report and reset as needed.

**Comment by mhoemmen** [comment]
Ah, I think I get it now -- stacked timer is running out of space so you need to clear it out during the run now and then.
