### ISSUE TITLE
ROL: File name misspelled in rol/adapters/teuchos/src/CMakeLists.txt

### ISSUE THREAD

**Issue by lxmota** [trilinos/Trilinos#584]
In the file:
  rol/adapters/teuchos/src/CMakeLists.txt
the name of the header ROL_TeuchosVector.hpp is misspelled as ROL_TeuchoVector.hpp (missing an "s").

**Comment by dridzal** [comment]
@gregvw , could you please take a look at this and close the issue?

**Comment by gregvw** [comment]
Fixed
