### ISSUE TITLE
Tpetra: is getLocalGraph() still an implementation detail?

### ISSUE THREAD

**Issue by lucbv** [trilinos/Trilinos#5840]
## Question
@trilinos/tpetra

I would like to access the rowPointers of a `CrsGraph` so I read the documentation and fine this:
```
    /// \brief Get a host view of the row offsets.
    ///
    /// \note Please prefer getLocalGraph() to get the row offsets.
    ///
    /// This may return either a copy or a view of the row offsets.
    /// In either case, it will <i>always</i> live in host memory,
    /// never in (CUDA) device memory.
    Teuchos::ArrayRCP<const size_t> getNodeRowPtrs () const;
```
Since I would rather get a view potentially on device than a host side `Teuchos::ArrayRCP`, I moved on to the documentation regarding access to the local graph.

Reading the documentation of `Tpetra::CrsGraph::getLocalGraph()` I saw the following:
```
    /// \brief Get the local graph.
    ///
    /// \warning THIS IS AN EXPERT MODE FUNCTION.  THIS IS AN
    ///   IMPLEMENTATION DETAIL.  DO NOT CALL THIS FUNCTION!!!
    ///
    /// This is only a valid representation of the local graph if the
    /// (global) graph is fill complete.
    local_graph_type getLocalGraph () const;
```

So should I be worried about using `getLocalGraph()` as it could disappear without warning or is the documentation just not up to data?

**Comment by mhoemmen** [comment]
@lucbv Just speaking for myself and not for the other @trilinos/tpetra developers, I think we use getLocalGraph so much that we might as well consider it part of the public interface.  It bothers me that we never managed to finish dual view semantics for CrsGraph and CrsMatrix, but I think `withLocalAccess` is a better approach for that.

**Comment by lucbv** [comment]
@mhoemmen I am not sure I understand well what you would like to advocate with `withLocalAccess`, I cannot find this method defined anywhere in the `Tpetra::CrsGraph_decl.hpp`...
Based on what you wrote in PR #5841 it sounds like a method that takes a lambda acting on the `local_graph` allowing say to compute coloring of the graph without taking it out of the distributed object?

**Comment by mhoemmen** [comment]
@lucbv wrote:
> I am not sure I understand well what you would like to advocate with `withLocalAccess`, I cannot find this method defined anywhere in the `Tpetra::CrsGraph_decl.hpp`...

That's correct; I haven't yet overloaded `withLocalAccess` for CrsGraph.  [Here is a MultiVector example.](https://github.com/trilinos/Trilinos/blob/53d8254e4f8205c8147dae3bd03bb0da322c22ea/packages/tpetra/core/test/MultiVector/WithLocalAccess.cpp#L385)  The syntax gets a bit nicer with C++14's `auto` lambdas:
```c++
Vector<> x_global (...);
withLocalAccess ([&] (const auto& x_local) {
    cout << "x_local is " << x_local.extent(0) << " by " << x_local.extent(1) << endl;
  },
  readOnly (x_global).on (HostSpace ()));
```
With C++11, you must name the type of `x_local`, but otherwise this works.  Note the declarative syntax: "I want to access the data in read-only fashion, on host."  That avoids the whole worry about whether and where to sync.  Vector takes care of that.

**Comment by lucbv** [comment]
@mhoemmen OK, I think that answers my question well!
I will close this issue now and keep in mind the `withLocalAccess`, I read the details in Tpetra and it seems interesting but I will wait for the CrsGraph overload before revisiting my work in `MueLu::LWGraph`
