### ISSUE TITLE
Trilinos/Tribits/CMake: CTest needs to support flags for single process unit tests

### ISSUE THREAD

**Issue by jjellio** [trilinos/Trilinos#5855]
On some platforms MPI adds hooks that expect MPI_Init to be called... this is related to optimizing the library for GPU use.

If we have unit tests that use a single process, they may fail.  On Summit, Sierra, and testbeds for them, we need to disable these hooks for non-mpi jobs.

This effectively says that Trilinos' Test setup code needs to be able to apply flags differently based on whether the unit test will have 1 MPI or more.

E.g.,
```
     91 - TpetraCore_computeOffsetsFromCounts_MPI_1 (Failed)

91: CUDA Hook Library: Failed to find symbol mem_find_dreg_entries, /vscratch1/jhu/build-trilinos-dev-vortex-gcc-7.2-cuda-9.2-debug/packages/tpetra/core/test/HashTable/TpetraCore_computeOffsetsFromCounts.exe: undefined symbol: __PAMI_Invalidate_region
91: Kokkos::Cuda ERROR: Failed to call Kokkos::Cuda::finalize()

     92 - TpetraCore_computeOffsetsFromConstantCount_MPI_1 (Failed)

92: CUDA Hook Library: Failed to find symbol mem_find_dreg_entries, /vscratch1/jhu/build-trilinos-dev-vortex-gcc-7.2-cuda-9.2-debug/packages/tpetra/core/test/HashTable/TpetraCore_computeOffsetsFromConstantCount.exe: undefined symbol: __PAMI_Invalidate_region
92: Kokkos::Cuda ERROR: Failed to call Kokkos::Cuda::finalize()

```

But doing some sed magic on the CTest files to add a flag allows the tests to pass. Ideally, we need this ability w/out sed.
e.g.,
```
The following tests passed:
	TpetraCore_Map_initializes_Kokkos_inner_scope_MPI_1
	TpetraCore_Map_does_not_double_initialize_Kokkos_MPI_1

100% tests passed, 0 tests failed out of 2

Subproject Time Summary:
Tpetra    =   3.33 sec*proc (2 tests)
```

```
for f in $(find -name "CTestTestfile.cmake"); do sed -i -e 's/"-p" "1"/"-M" "-disable_gpu_hooks" "-p" "1"/g' $f; done
```

**Comment by mhoemmen** [comment]
@jjellio Thanks for tracking this down!  Is the issue that `MPI_Init` is not getting called, or that the job only has one MPI process?  We can always add a `Tpetra::ScopeGuard` thing to those tests to ensure the former.

**Comment by jhux2** [comment]
@trilinos/framework @bartlettroscoe

**Comment by jjellio** [comment]
We could try to root cause it. My guess is it is processes that either allocate memory before MPI_Init or never call MPI_Init.

All of the tests that 'failed' were single process unit tests. By adding a flag to disable some of the MPI/GPU hooks, those tests succeed.

On our platforms, if we did want to enable unit testing, we could call a script to find/replace much as I did. But a better solution would be a way to convey extra parameters to the run command.

It is also reasonable to ask IBM to handle the case of 'np =1' and disable this stuff (or LLNL to modify their wrapper scripts to do it)

**Comment by mhoemmen** [comment]
Hi @jjellio !  I looked into some of those tests.  All four of the following tests just initialize and finalize Kokkos; they don't initialize or finalize MPI.

  1. `TpetraCore_computeOffsetsFromCounts_MPI_1`
  2. `TpetraCore_computeOffsetsFromConstantCount_MPI_1`
  3. `TpetraCore_Map_initializes_Kokkos_inner_scope_MPI_1`
  4. `TpetraCore_Map_does_not_double_initialize_Kokkos_MPI_1`

For Tests (3) and (4), it's part of the point that the tests don't initialize MPI.  Tpetra does not initialize MPI for you if the user hasn't initialized it yet.  That's part of good behavior for a library.  (Tpetra has to initialize Kokkos if Kokkos hasn't been initialized yet, because there's no way for Tpetra to run without Kokkos.  Tpetra can run just fine with `Teuchos::SerialComm`.)

**Comment by jjellio** [comment]
You should see the log for running the full trilinos tests... (so many aren't MPI).

I emailed LLNL and asked them about it.  IMO, the MPI layer should be doing this.  There is a significant performance improvement on UCX by letting it cache pointers (cuda-aware or not). So, I can see the point.  Still, their impl doesn't freak out if you don't use MPI. (But I should verify that... it's pretty easy to forget to evaluate the non-mpi tests when you are stress testing an MPI  install >< )

**Comment by bartlettroscoe** [comment]
Why can't these 1-proc test executables just use [Teuchos::GlobalMPISession](https://trilinos.org/docs/dev/packages/teuchos/doc/html/classTeuchos_1_1GlobalMPISession.html) like all of the others in Trilinos?  That calls `MPI_Init()/MPI_Finalize()` if building with MPI and avoids calling `MPI_Init()/MPI_Finalize()` when not (i.e. `TPL_ENABLE_MPI=[ON|OFF]`).  It is 2 lines of code at most (one `#include` and `Teuchos::GlobalMPISession mpiSession(argc, argv)` at the top of `main()`).  Is there any harm in running these with `mpiexec -np 1`?

**Comment by mhoemmen** [comment]
@bartlettroscoe Some of the tests actually need to control MPI initialization and finalization, in order to test what they want to test.

**Comment by bartlettroscoe** [comment]
@jjellio and @mhoemmen, why not just put in:

```
set(MPI_EXEC_PRE_NUMPROCS_FLAGS "${MPI_EXEC_PRE_NUMPROCS_FLAGS} -disable_gpu_hooks")
```

for these tests in their CMakeLists.txt file?  See:

* https://tribits.org/doc/TribitsBuildReference.html#configuring-with-mpi-support

Or, write your own CMake function (to create a scope) and then set the flags there.

No modifications to TriBITS or CTest should be needed to handle something like this.

**Comment by jjellio** [comment]
Ross, the problem is this impacts every packages in Trilinos.  We could always implement a find/replace script, but there is a semantic difference between 'single process mpi' and 'single process'.  I think some of the unit tests Mark highlighted were exactly those cases - they want to test what happens w/out MPI.

This whole thing is a mess, I reported it here, because when CI happens on these platforms we collectively need to be prepared. Right now, if you try to unit test Trilinos you most likely will see a very large portion of the unit tests fail.

Hard coding the flag in CMakeList is probably bad - this is a platform specific flag (IBM LSF w/Spectrum). A different MPI on that platform may not need it.

If we had CTest packing tests using the machine's native batch system, then this flag would naturally sit in the 'LSF/Spectrum template'.  E.g., detect launcher is 'jsrun' then you take a different code path in generating the CTest files.

**Comment by bartlettroscoe** [comment]
@jjellio, how many tests in Trilinos need to run as a single process test without MPI?

**Comment by bartlettroscoe** [comment]
We will be running Trilinos builds and tests suites on ATS-2 machines soon so will we see this problem then?

**Comment by jjellio** [comment]
I don't know the answer to your first question. Mark dug into the ones he posted.  My hypothesis was that the error comes when you run a process with Jsrun but never init MPI.

You will see this crap on ATS-2. If you have launches that fail you often end up with network timeouts afterwards where the interconnect is hung due to not cleanly shutting down.... Then you end up having to get a new allocation.  Effectively, you have to ensure that few if any processes segfault/exit unexpectedly. 

IMO, we should be aware of this and think about what the plan should be.  Since it is platform specific whatever is done needs to not break the other platforms that are tested.

**Comment by bartlettroscoe** [comment]
If the best way to address this is to modify TriBITS, then so be it.  But that means it will need to be documented and have strong automated tests inside of TriBITS (to whatever extent possible).

**Comment by mhoemmen** [comment]
begone autobot

**Comment by jjellio** [comment]
I guess this can close.

To recap the issue, in 2022 times, the problem was that on ATS-2 type platforms, they couldn't handle apps that didn't call `MPI_Init`. This is because the device aware MPI needs to track memory to know how MPI handles it.  On ATS-2 this could be worked around by disabling the gpu hooks.  This was needed because on ATS-2, a shared library is LD_PRELOAD'd that hooks all memory allocs (expecting you to then call `MPI_Init/Finialize` (these are the gpu hooks).  

Our stuff caused problems because we have some tests that are non-MPI, but our unit test framework (correctly) launches every job using the system's job launcher (jsrun in this case, but could be slurm or flux).

We ultimately worked around the nuances of `jsrun` and GPU hooks, by writing a `jsrun_wrapper` that could massage things before launching. 

Hopefully, as platforms continue to become more heterogeneous MPI and the system side will be able to handle all this more robustly. I.e., gracefully realize the mem-hooks aren't necessary if MPI_Init isn't called (and don't spam warnings at exit).
