### ISSUE TITLE
Xpetra: deprecate use of `getLocalView` for MultiVector and Vector classes

### ISSUE THREAD

**Issue by lucbv** [trilinos/Trilinos#5863]
## Enhancement
@trilinos/xpetra

To mirror what is currently implemented in `Tpetra::MultiVector` we should deprecate the use of `Vector.template<DeviceTarget>getLocalView()` in favor of `Vector.getLocalViewDevice` and `Vector.getLocalViewHost`

**Comment by mhoemmen** [comment]
I would prefer to see Xpetra go with the `withLocalAccess` pattern -- that would let MueLu run on GPU even with Epetra.

**Comment by mhoemmen** [comment]
begone autobot
