### ISSUE TITLE
SEACAS:  SEACASIoss_pamgen_exodus_io_info randomly failing ATDM builds on ride

### ISSUE THREAD

**Issue by fryeguy52** [trilinos/Trilinos#5868]
## Bug Report
CC: @trilinos/seacas, @kddevin (Trilinos Data Services Product Lead), @bartlettroscoe, @fryeguy52
 
<Checklist>
<???: Add label "ATDM">
<???: Add label "bug"?>
<???: Add label for affected packages (e.g. "MueLu", "Tpetra", "Kokkos", etc.)>
<???: Add milestone "Initial cleanup of new ATDM builds of Trilinos" or "Keep promoted ATDM builds of Trilinos clean">
<???: Once GitHub Issue is created, add entries for tests to TrilinosATDMStatus/*.csv files>
<???: Add label "PA: ???Project Area???" (e.g. "PA: Linear Solvers", "PA: Data Services")>
 
## Next Action Status
<status-and-or-first-action>
 
## Description
 
As shown in [this query](https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-white-ride-&field2=testname&compare2=61&value2=SEACASIoss_pamgen_exodus_io_info&field3=status&compare3=61&value3=Failed&field4=buildstarttime&compare4=84&value4=2019-09-06T04%3A01%3A00UTC&field5=buildstarttime&compare5=83&value5=2019-08-07T04%3A01%3A00UTC) the test:
* SEACASIoss_pamgen_exodus_io_inf

has failed 32 times in 9 different builds since 2019-08-15.  All of the builds are in ride and they are the following:
* Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-debug
* Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-rdc-release-debug
* Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-rdc-release-debug-pt
* Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-release
* Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-release-debug
* Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-release-debug-pt
* Trilinos-atdm-white-ride-gnu-7.2.0-openmp-debug
* Trilinos-atdm-white-ride-gnu-7.2.0-openmp-release

typical out put looks like:
```
--------------------------------------------------------------------------------

1,8d0
< ibv_exp_query_device: invalid comp_mask !!! (comp_mask = 0x100034cc850 valid_mask = 0x1)
< [ride11][[50396,1],0][btl_openib_component.c:1648:init_one_device] error obtaining device attributes for mlx5_1 errno says Invalid argument
< --------------------------------------------------------------------------
< WARNING: There was an error initializing an OpenFabrics device.
< 
<   Local host:   ride11
<   Local device: mlx5_1
< --------------------------------------------------------------------------
```

## Current Status on CDash

[Failures in the last 2 weeks](https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-white-ride-&field2=testname&compare2=61&value2=SEACASIoss_pamgen_exodus_io_info&field3=status&compare3=61&value3=Failed&field4=buildstarttime&compare4=84&value4=now&field5=buildstarttime&compare5=83&value5=2%20weeks%20ago)

[Test results on all ride builds today](https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercount=4&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-white-ride-&field2=testname&compare2=61&value2=SEACASIoss_pamgen_exodus_io_info&field3=buildstarttime&compare3=84&value3=today&field4=buildstarttime&compare4=83&value4=yesterday)

## Steps to Reproduce

One should be able to reproduce this failure on ride or white as described in:
* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md

More specifically, the commands given for ride or white are provided at:
* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#ridewhite

The exact commands to reproduce this issue should be:
```
$ cd <some_build_dir>/
$ source $TRILINOS_DIR/cmake/std/atdm/load-env.sh Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-release
$ cmake \
 -GNinja \
 -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
 -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_SEACAS=ON \
 $TRILINOS_DIR
$ make NP=16
$ bsub -x -Is -q rhel7F -n 16 ctest -j16
```

**Comment by mhoemmen** [comment]
@gdsjaar

**Comment by gsjaardema** [comment]
I think this can be closed.  Tests seem to be working.

**Comment by bartlettroscoe** [comment]
As shown in [this query](https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&begin=2019-09-01&end=2019-10-04&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-white-ride-&field2=testname&compare2=61&value2=SEACASIoss_pamgen_exodus_io_info), the last test failure was on 2019-09-16 so this does look like this is fixed.

@gsjaardema, what did you change to fix this?
