### ISSUE TITLE
Phalanx tests failing in build Trilinos-atdm-mutrino-intel-opt-openmp-KNL starting 2019-08-22

### ISSUE THREAD

**Issue by fryeguy52** [trilinos/Trilinos#5872]
## Bug Report
CC: @trilinos/phalanx, @mperego (Trilinos Discretizations Product Lead), @bartlettroscoe, @fryeguy52
 
## Next Action Status
<status-and-or-first-action>
 
## Description
 
As shown in [this query](https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercount=6&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-mutrino-intel-opt-openmp-KNL&field2=testname&compare2=65&value2=Phalanx_&field3=site&compare3=61&value3=mutrino&field4=status&compare4=61&value4=Failed&field5=buildstarttime&compare5=84&value5=2019-09-06T04%3A01%3A00UTC&field6=buildstarttime&compare6=83&value6=2019-08-07T04%3A01%3A00UTC) the tests:
* Phalanx_dag_manager_MPI_1
* Phalanx_field_MPI_1
* Phalanx_mdfield_compiletime_MPI_1
* Phalanx_mdfield_runtime_MPI_1

are failing in the build:
* Trilinos-atdm-mutrino-intel-opt-openmp-KNL

They started failing on 2019-08-22:

<details><summary>Click to see new commits on 2019-08-22</summary>

```
*** Base Git Repo: Trilinos
d71bc30db3:  Merge remote-tracking branch 'origin/develop' into atdm-nightly
Author: Roscoe A. Bartlett <rabartl@sandia.gov>
Date:   Wed Aug 21 21:05:23 2019 -0600

f0079857e4:  Merge Pull Request #5770 from brian-kelley/Trilinos/FixDecoupled
Author: trilinos-autotester <trilinos-autotester@trilinos.org>
Date:   Wed Aug 21 15:13:35 2019 -0600

542500529f:  MueLu: set dofs/node for decoupled line smoothing
Author: Brian Kelley <bmkelle@sandia.gov>
Date:   Thu Aug 1 09:00:37 2019 -0600

M	packages/muelu/src/Smoothers/MueLu_Ifpack2Smoother_def.hpp

09efe4a816:  Merge Pull Request #5768 from cgcgcg/Trilinos/thyra-fix
Author: trilinos-autotester <trilinos-autotester@trilinos.org>
Date:   Wed Aug 21 09:38:06 2019 -0600

b5ec4b71ac:  Merge Pull Request #5767 from william76/Trilinos/fmwk-installtesting-teuchos-fix-20190820
Author: trilinos-autotester <trilinos-autotester@trilinos.org>
Date:   Wed Aug 21 08:52:23 2019 -0600

c75ec7783d:  Belos Thyra adapter: Use caching in inner products when using Tpetra
Author: Christian Glusa <caglusa@sandia.gov>
Date:   Tue Aug 20 20:55:27 2019 -0600

M	packages/stratimikos/adapters/belos/src/BelosThyraAdapter.hpp

b45d411983:  Thyra VectorSpace: Add new method createCachedMembersView
Author: Christian Glusa <caglusa@sandia.gov>
Date:   Tue Aug 20 20:53:33 2019 -0600

M	packages/thyra/adapters/tpetra/src/Thyra_TpetraVectorSpace_decl.hpp
M	packages/thyra/adapters/tpetra/src/Thyra_TpetraVectorSpace_def.hpp
M	packages/thyra/core/src/interfaces/operator_vector/fundamental/Thyra_VectorSpaceBase_decl.hpp

b7e65b6a1a:  Teuchos: Add Teuchos_string.hpp to CMakeLists.txt
Author: William McLendon <wcmclen@sandia.gov>
Date:   Tue Aug 20 17:55:16 2019 -0600

M	packages/teuchos/parser/src/CMakeLists.txt

```
</details>

## Current Status on CDash

The current status of these tests/builds for the current testing day can be found at:

* testing.sandia.gov/cdash/queryTests.php?project=Trilinos&<filter-for-test-1>

* testing.sandia.gov/cdash/queryTests.php?project=Trilinos&<filter-for-test-2>

<NOTE: Just put in whatever CDash links are easy to construct that will show the status>

<NOTE: Could show recent history, etc.>

## Steps to Reproduce

One should be able to reproduce this failure on mutrino as described in:
* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md

More specifically, the commands given for mutrino are provided at:
* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#mutrino

The exact commands to reproduce this issue should be:
```
$ cd <some_build_dir>/
$ source $TRILINOS_DIR/cmake/std/atdm/load-env.sh Trilinos-atdm-mutrino-intel-opt-openmp-KNL
$ cmake \
 -GNinja \
 -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
 -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_Phalanx=ON \
 $TRILINOS_DIR
$ make NP=16
$ salloc -N 1 -p standard -J $ATDM_CONFIG_JOB_NAME ctest -j16
```

**Comment by bartlettroscoe** [comment]
Site | Build Name | Test Name | Status | Details | Consec­utive Pass Days | Non-pass Last 30 Days | Pass Last 30 Days | Issue Tracker
-- | -- | -- | -- | -- | -- | -- | -- | --
mutrino | Trilinos-atdm-mutrino-intel-opt-openmp-KNL | Phalanx_­dag_­manager_­MPI_­1 | Passed | Completed | 18 | 11 | 18 | #5872
mutrino | Trilinos-atdm-mutrino-intel-opt-openmp-KNL | Phalanx_­field_­MPI_­1 | Passed | Completed | 18 | 11 | 18 | #5872
mutrino | Trilinos-atdm-mutrino-intel-opt-openmp-KNL | Phalanx_­mdfield_­compiletime_­MPI_­1 | Passed | Completed | 18 | 11 | 18 | #5872
mutrino | Trilinos-atdm-mutrino-intel-opt-openmp-KNL | Phalanx_­mdfield_­runtime_­MPI_­1 | Passed | Completed | 18 | 11 | 18 | #5872

Passing for 18 days so we can close?

**Comment by rppawlo** [comment]
sounds good to me!
