### ISSUE TITLE
Tpetra undefined references to beginFill/endFill in tests

### ISSUE THREAD

**Issue by jjwilke** [trilinos/Trilinos#5886]
## Bug Report
@trilinos/tpetra

### Description
The unit tests for Tpetra are failing to build with undefined references to `endFill` for the `FECrsMatrix` and `FECrsGraph` classes. 

### Steps to Reproduce
1. kokkos-promotion branch: e7ce3e00974b5072da52e1f37c5d1e36e435a6e4
1. Sandia-SEMS: configure-testbeds-jenkins-all

These unit tests, e.g. `FECrsGraph_UnitTests.cpp` do not appear to include the file `Tpetra_FECrsGraph_def.hpp` (directly or indirectly) leading to undefined references. Same for `Tpetra_FECrsMatrix_def.hpp`

````
/ascldap/users/jjwilke/Programs/trilinos/kokkos-promotion/packages/tpetra/core/test/FECrsGraph/FECrsGraph_UnitTests.cpp:335: undefined reference to `Tpetra::FECrsGraph<int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Threads, Kokkos::HostSpace> >::beginFill()'
````

This problem is occurring in the units tests and also `fem_assembly_main`.
Adding the necessary `_def` headers got rid of the errors.

**Comment by brian-kelley** [comment]
@jjwilke This seems like a problem with Tpetra ETI; you shouldn't ever need to include a "_def" in a test cpp file. I'll take a look at this.

**Comment by jjwilke** [comment]
Yep, that makes sense. We are testing some build system changes - so I almost certainly broke the ETI stuff. You can hold off diving in until I look at the ETI stuff.

**Comment by mhoemmen** [comment]
@brian-kelley Huh, I think we're just missing `Tpetra_FECrsGraph_ThreadsWrapperNode.cpp`.

**Comment by mhoemmen** [comment]
@brian-kelley `tpetra/core/src/CMakeLists.txt` now has a way to generate ETI .cpp files for classes with (LO, GO, NT) template parameters.  We do this now for CrsGraph and similar classes.  We could probably also add this now for FECrsGraph.

**Comment by jjwilke** [comment]
Okay, confirmed. Even without my build system updates I am getting the same error on `kokkos-promotion` and `develop`. 

````
/ascldap/users/jjwilke/Programs/trilinos/develop/packages/tpetra/core/src/Tpetra_Assembly_Helpers.hpp:71: undefined reference to `Tpetra::FECrsGraph<int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Threads, Kokkos::HostSpace> >::endFill()'
````

**Comment by brian-kelley** [comment]
OK, made PR #5888 to fix this.

**Comment by jjwilke** [comment]
The PR does fix my problem. I'm curious what tests are being run for merging into develop? This must have been passing for some configure script that allowed it into develop?

**Comment by brian-kelley** [comment]
@jjwilke None of the checkin tests instantiate Tpetra for Pthreads, even though some of them do enable it as a Kokkos backend.

**Comment by mhoemmen** [comment]
@jjwilke Trilinos' PR tests have never enabled the Threads back-end.  There may have been Dashboard tests that did so before mandatory PR testing, but it's been years.

**Comment by brian-kelley** [comment]
@mhoemmen @jjwilke Oops, pthreads is never used as a Kokkos backend in the testing. I just saw "KokkosCore_ENABLE_Pthreads=ON", which enables the TPL but doesn't enable the backend; the host parallel execution space for those builds is None.

**Comment by mhoemmen** [comment]
@brian-kelley `tpetra/core/test/FECrsGraph/FECrsGraph_UnitTests.cpp` just uses `TPETRA_INSTANTIATE_LGN`; it doesn't refer to `Kokkos::Threads` or the corresponding Node type directly.  Thus, it must be that the Node type is getting enabled in Tpetra somehow.

**Comment by mhoemmen** [comment]
begone autocloser!
