### ISSUE TITLE
MueLu: warnings from catching polymorphic types by value

### ISSUE THREAD

**Issue by brian-kelley** [trilinos/Trilinos#5891]
## Bug Report
@trilinos/muelu

### Description

Many ``-Wcatch-value`` warnings caused by catching polymorphic types (subclasses of std::exception) by value, instead of reference. Example:

```
/ascldap/users/bmkelle/MiscWork/Trilinos/packages/muelu/src/Interface/../Utils/MueLu_Utilities_decl.hpp:363:23: warning: catching polymorphic type ‘class std::bad_cast’ by value [-Wcatch-value=]
  363 |         } catch (std::bad_cast) {
```

### Steps to Reproduce
Built from current develop branch with GCC 9.1.

**Comment by brian-kelley** [comment]
The recommended fix is to just make the type inside the catch a reference. I could do this fix if it is ok for @trilinos/muelu.

**Comment by jhux2** [comment]
@brian-kelley  Fine with me.  Thank you.

**Comment by jhux2** [comment]
@brian-kelley Can this be closed?

**Comment by brian-kelley** [comment]
Yep
