### ISSUE TITLE
Pkg:ROL  c++11 compilation failures with ROL_Ptr=std::shared_ptr

### ISSUE THREAD

**Issue by eleaver** [trilinos/Trilinos#5906]
## Bug Report
@trilinos/rol

### Description
1. rol/adapters/mpi/src/function/ROL_PinTHierarchy.hpp does not compile with ROL_Ptr=std::shared_ptr, because line 729 TEUCHOS_ASSERT(comm!=Teuchos::null); should be TEUCHOS_ASSERT(!ROL::is_nullPtr(comm));

2. rol/example/PinT/parabolic-control/AugmentedSystem.cpp does not compile with ROL_Ptr=std::shared_ptr, either because rol/src/compatibility/std/shared_ptr/ROL_Ptr.hpp does not provide a makePtr(std::initializer_list) overload, OR because AugmentedSystem.cpp line 221 attempts to instantiate kkt_vector = makePtr<PartitionedVector>({list}) where PartitionedVector::create({list}) might be more appropriate.

The ROL_PinTHierarchy.hpp fix is trivial. AugmentedSystem.cpp may be fixed directly via the indicated PartitionedVector::create({list})  static method, or by adding a rol/src/compatibility/std/shared_ptr/ROL_Ptr::makePtr(std::initializer_list) overload. I've done the latter in my local development fork for consistency with teuchos/rcp/ROL_Ptr.hpp, but one might argue PartitionedVector::create({list}) is the better approach and ROL_Ptr::makePtr(std::initializer_list) overloads should be deprecated in both std/shared_ptr and teuchos/rcp. 

But I don't know how much code that would break.

Either way, std/shared_ptr/ROL_Ptr::makePtr( Args&&... args ) is missing std::forward, and should return std::make_shared<T>(std::forward<Args>(args)...);

As an aside, in the makePtr( std::initializer_list<U>&& u ) overloads "u" appears to be an rvalue reference, and might be moved rather than forwarded. Semantics, is all.  

**************************************

What went wrong? --- My build failed. :(
What should have happened? My builds should succeed...
Do you have an idea what might fix things?  Yes, see above.
How has this bug affected you? It's delayed my fixing and reporting other ROL bugs. 
What are you trying to accomplish? Optimize a simplex to "most closely" fit a collection of n-dimensional points.

What specifically must we demonstrate to call this work complete? Incorporate the above suggestions or similar, build with C++11 and ROL_Ptr=std::shared_ptr and run unit tests and examples.  I could submit a pull request, if it would help.

### Steps to Reproduce
1. SHA1:  develop b9364059c688f7afdf676fd22d353fce75484778

2. Configure script:
[ConfigureTrilinosMPI.txt](https://github.com/trilinos/Trilinos/files/3608272/ConfigureTrilinosMPI.txt)

3. Edit Configure script to export TRILINOS_HOME someplace useful.

4. mkdir build; cd build; ../../ConfigureTrilinosMPI.sh; make -j6;

5. make test

I build my applications on Fedora 30 with gcc-8.3.0, both single and double precision.

**Comment by eleaver** [comment]
Addendum. As part of Configuration, before running the Configure script, I edit  rol/cmake/BuildOptions.cmake to SET_DEFAULT( ROL_Ptr  "std::shared_ptr" )

**Comment by dridzal** [comment]
@eleaver , many thanks for catching this.  @gregvw , could you please look into this?  @eric-c-cyr , I believe that this affects our PinT work, but Greg should look into the shared_ptr vs. teuchos rcp issue.
