### ISSUE TITLE
Pkg::ROL:  Unit test ROL_adapters_eigen_test_vector_EigenVectorInterface fails

### ISSUE THREAD

**Issue by eleaver** [trilinos/Trilinos#5909]
## Bug Report
@trilinos/rol

### Description
What went wrong?  
ROL_adapters_eigen_test_vector_EigenVectorInterface_MPI_4 ...........***Failed  Required regular expression not found.Regex=[TEST PASSED

What should have happened?
ROL_adapters_eigen_test_vector_EigenVectorInterface_MPI_4 ...........   Passed

Do you have an idea what might fix things? Yes.  

How has this bug affected you?  
Delays me from addressing other ROL::EigenVector bugs and interface issues.

What are you trying to accomplish? 
N-dimensional simplex optimization

What specifically must we demonstrate to call this work complete?
Fix the following:
1. rol/adapters/eigen/test/vector/test_01.cpp -- assign outStream at lines 27 and 29
2. rol/adapters/eigen/src/vector/ROL_EigenVector.hpp
   a. default ctor should zero out the vector when asked, e.g.
  `Eigen3Vector( int dim, bool zeroOut=false ) : dim_(dim) {
    vec_ = ROL::makePtr<EV>(dim_);
    if( zeroOut ) {
      (*vec_).setZero();
    }
  }`

   b. Likewise, Eigen3Vector::basis(int i) should also setZero() it's new data vector before assigning it's i-th element to 1, that is, auto data = ROL::makePtr<EV>(dim_,true); doesn't do what you think it does:
 `  ROL::Ptr<V> basis( const int i ) const {
      auto data = ROL::makePtr<EV>(dim_);
      data->setZero();
      (*data)(i) = static_cast<Real>(1.0);
      return ROL::makePtr<Eigen3Vector>(data);
  }`
or alternatively,
` ROL::Ptr<V> basis( const int i ) const {
    auto unitp = ROL::makePtr<EV>(vec_->Unit(dim_,i));
    return ROL::makePtr<Eigen3Vector>(unitp);
  }`
 
### Steps to Reproduce
1. SHA1: 4b0a90b56784165bedc2a87f19b155d56307b198
2. Configure script:  [attach here]
[ConfigureTrilinosMPI.txt](https://github.com/trilinos/Trilinos/files/3611632/ConfigureTrilinosMPI.txt)

3. Edit ConfigureTrilinosMPI.sh to point TRILINOS_HOME someplace useful. Set ROL_Ptr='teuchos::rcp' if you'd like, otherwise edit rol/cmake/BuildOptions.cmake to SET_DEFAULT( ROL_Ptr           "std::shared_ptr")

4. mkdir build; cd build; ../ConfigureTrilinosMPI.sh; make; make test

**Comment by mhoemmen** [comment]
@trilinos/rol (it's annoying that non-developers can't tag teams)

**Comment by dridzal** [comment]
@eleaver , thanks.  @gregvw , please take a look.

**Comment by eleaver** [comment]
You are welcome, @dridzal. It has occurred to me the basis() method may be simplified thus:
 ROL::Ptr<V> basis( const int i ) const {
    auto unitp = ROL::makePtr<Eigen3Vector>(dimension(),true);
    (*(unitp->getVector()))(i) = static_cast<Real>(1);
    return unitp;
  }

Avoids some pointer arithmetic. I'll likely include vector element accessor operator()(int) and operator[](int) in a future feature request.

**Comment by eleaver** [comment]
Eigen3Vector does have operator()(int), ergo
(*unitp)(i) = static_cast<Real>(1);

**Comment by mhoemmen** [comment]
begone autocloser!
