### ISSUE TITLE
Zoltan: safe way to get the recursive bisection tree 

### ISSUE THREAD

**Issue by egboman** [trilinos/Trilinos#591]
Some applications need the tree corresponding to recursive bisection in partitioning methods like RCB and PHG. Currently they assume "natural" order, for example ((0,1), (2,3)) for k=4. This is actually not guaranteed to hold by Zoltan and in fact LB_REMAP could permute the parts and "mess things up". There should be a safer API for applications to use, both in Zoltan and Zoltan2.

**Comment by kddevin** [comment]
Needed for Nested Dissection ordering by FY17 Q1
Needed for H2 hierarchical solver by FY17 

Applications need the tree structure along with part numbers at the leaves.

Need to design interface that works in RCB, PHG, MJ
-  consider number of processors != 2^n
-  consider non-bisection as in MJ

@trilinos/zoltan2

**Comment by kddevin** [comment]
@egboman I think this issue is resolved now with PR #1120 and its related PRs.
Do you agree?  If so, we can close this issue.
