### ISSUE TITLE
MPI_EXEC_PRE_NUMPROCS_FLAGS:STRING not propagated to install cmake files

### ISSUE THREAD

**Issue by bathmatt** [trilinos/Trilinos#5914]
## Enhancement
@trilinos/

It doesn't look like MPI_EXEC_PRE_NUMPROCS_FLAGS:STRING=--bind-to;none is being saved in any of the cmake install files.  

searching the install dir I see 
(DESKTOP)-dir-GNU-7.2.0-RELEASE-OPENMP-shared [GNU-7.2.0]$ 59 $ find . -type f -exec grep -I bind-to {} \;
export ATDM_CONFIG_MPI_PRE_FLAGS="--bind-to;none"

Something like Trilinos_MPI_EXEC_PRE_NUMPROCS_FLAGS

would be good

**Comment by bartlettroscoe** [comment]
CC: @jfrye

@bathmatt,

I will take a look at this and see if this can be resolved.

**Comment by bartlettroscoe** [comment]
@bathmatt,

Looks like this is already supported as the env var `ATDM_CONFIG_MPI_PRE_FLAGS`:

```
cmake/std/atdm/ATDMDevEnvSettings.cmake:255:ATDM_SET_CACHE(MPI_EXEC_PRE_NUMPROCS_FLAGS "$ENV{ATDM_CONFIG_MPI_PRE_FLAGS}" CACHE STRING)
```

And there is lots of examples of how this gets used in:

```
$ find cmake/std/atdm -type f -exec grep -nH ATDM_CONFIG_MPI_PRE_FLAGS {} \;
cmake/std/atdm/utils/unset_atdm_config_vars_environment.sh:43:unset ATDM_CONFIG_MPI_PRE_FLAGS
cmake/std/atdm/sems-rhel6/environment.sh:204:export ATDM_CONFIG_MPI_PRE_FLAGS="--bind-to;none"
cmake/std/atdm/cee-rhel6/environment.sh:94:  export ATDM_CONFIG_MPI_PRE_FLAGS="--bind-to;none"
cmake/std/atdm/cee-rhel6/environment.sh:107:  export ATDM_CONFIG_MPI_PRE_FLAGS="--bind-to;none"
cmake/std/atdm/examples/my-sems-rhel6-config/environment.sh:43:export ATDM_CONFIG_MPI_PRE_FLAGS="--bind-to;none"
cmake/std/atdm/examples/my-sems-rhel6-config/environment.sh~:200:export ATDM_CONFIG_MPI_PRE_FLAGS="--bind-to;none"
cmake/std/atdm/mutrino/environment.sh:40:export ATDM_CONFIG_MPI_PRE_FLAGS="--mpi=pmi2;--ntasks-per-node;36"
cmake/std/atdm/ATDMDevEnvSettings.cmake:255:ATDM_SET_CACHE(MPI_EXEC_PRE_NUMPROCS_FLAGS "$ENV{ATDM_CONFIG_MPI_PRE_FLAGS}" CACHE STRING)
cmake/std/atdm/spack-rhel/environment.sh:181:export ATDM_CONFIG_MPI_PRE_FLAGS="--bind-to;none"
cmake/std/atdm/common/toss3/environment.sh:83:export ATDM_CONFIG_MPI_PRE_FLAGS="--mpi=pmi2;--ntasks-per-node;36"
cmake/std/atdm/sems-rhel7/environment.sh:258:export ATDM_CONFIG_MPI_PRE_FLAGS="--bind-to;none"
```

NOTE: The name `MPI_PRE_FLAGS` name was adapted from the name `MPI_POST_FLAG` which was copied from the original EMPIRE Trilinos configure scripts.

The list of variables that can be set in `<system_name>/environment.sh` and are read in by `ATDMDevEnvSettings.cmake` by CMake are listed in:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/utils/unset_atdm_config_vars_environment.sh

With a little bit of effort, we could provide a list of these vars in a bash file and provide comments that explain what each of these is used for.  Would that be helpful?

**Comment by bathmatt** [comment]
I understand they are in the environment vars.  However, they are not in the install really.  to use these I need to search my env and it should be stored here
./lib/cmake/Trilinos/TrilinosConfig.cmake

**Comment by bartlettroscoe** [comment]
Not sure how that would help EMPIRE the way things are currently set up. Can you please give more info on the use cases that are the driver for this?  Can we talk about this briefly?

**Comment by bathmatt** [comment]
I just want a uniform way to get parameters on running tests, don't want a mix of env like this and first class vars like Trilinos_MPI_NP.. or some such stuff

**Comment by bathmatt** [comment]
All I want is in the ./lib/cmake/Trilinos/TrilinosConfig.cmake to have the def matching trilinos install, and the same for post.  This will match other things like TrilinosConfig.cmake:SET(Trilinos_MPI_EXEC_NUMPROCS_FLAG "-np")

why is pre and post flags different??

Trilinos_MPI_EXEC_PRE_NUMPROCS_FLAGS

**Comment by bartlettroscoe** [comment]
> why is pre and post flags different??

Okay, I did not realize that any MPI-related runtime vars were getting set in the installed `<Project>Config.cmake` file but now I see them:


```
SET(${PROJECT_NAME}_MPI_EXEC "${MPI_EXEC}")
SET(${PROJECT_NAME}_MPI_EXEC_MAX_NUMPROCS "${MPI_EXEC_MAX_NUMPROCS}")
SET(${PROJECT_NAME}_MPI_EXEC_NUMPROCS_FLAG "${MPI_EXEC_NUMPROCS_FLAG}")
```

in:

* Trilinos/cmake/tribits/core/installation/TribitsProjectConfigTemplate.cmake.in

I did not write any of that code and it would not have occurred to me to put any MPI-runtime stuff in there but there it is.  I will add the other ones as well.

**Comment by bartlettroscoe** [comment]
@bathmatt, try out #5916  if you want but I am pretty sure this does what it should.  Otherwise, can you please just approve this?

**Comment by bartlettroscoe** [comment]
@bathmatt, PR #5916 merged last night. Please let me know if this addresses the request so that I can close this issue.

**Comment by bartlettroscoe** [comment]
> @bathmatt, PR #5916 merged last night. Please let me know if this addresses the request so that I can close this issue.

@bathmatt, you posted this issue.  Do you know if this is resolved for EMPIRE?  The PR #5916 was merged way back on 9/16/2019.

@jmgate?

**Comment by krcb** [comment]
@bartlettroscoe In my `<trilinos-install-path>/lib/cmake/Trilinos/TrilinosConfig.cmake`, I see:

```
## ---------------------------------------------------------------------------
## MPI specific variables
##   These variables are provided to make it easier to get the mpi libraries
##   and includes on systems that do not use the mpi wrappers for compiling
## ---------------------------------------------------------------------------

SET(Trilinos_MPI_LIBRARIES "")
SET(Trilinos_MPI_LIBRARY_DIRS "")
SET(Trilinos_MPI_INCLUDE_DIRS "")
SET(Trilinos_MPI_EXEC "<path-to-mpi-exec>")
SET(Trilinos_MPI_EXEC_PRE_NUMPROCS_FLAGS "")
SET(Trilinos_MPI_EXEC_MAX_NUMPROCS "4")
SET(Trilinos_MPI_EXEC_POST_NUMPROCS_FLAGS "")
SET(Trilinos_MPI_EXEC_NUMPROCS_FLAG "-np")
```

which is what we needed. I think this can be closed.

**Comment by bartlettroscoe** [comment]
Thanks @krcb!

Closing as complete
