### ISSUE TITLE
MueLu: null space fix breaks const solution

### ISSUE THREAD

**Issue by bathmatt** [trilinos/Trilinos#5928]
## Bug Report
@trilinos/\<PackageName\>
This commit broke EMPIRE

```
(DESKTOP)-dir-Trilinos [GNU-7.2.0]$ 151 $ git bisect bad
ef41a37a29102c6df16bc253c89f058bdb3196e6 is the first bad commit
commit ef41a37a29102c6df16bc253c89f058bdb3196e6
Author: Christian Glusa <caglusa@sandia.gov>
Date:   Tue Sep 10 14:46:07 2019 -0600

    MueLu: Nullspace fix for distributed coarse matrix

```
### Description
Our EM solve is show incorrect results for a periodic problem with this fix.  To reproduce look at ExternalDriveMagneticImplicit if you have access to the repo.  Prior you get a constant solution which is correct, once you add this you get a non-const solution

**Comment by bathmatt** [comment]
@jmgate @egphill

**Comment by cgcgcg** [comment]
@bathmatt Will look at it once I'm back on Monday.

**Comment by bathmatt** [comment]
Cool, thanks.  We should test in EMPIRE prior to pushing into develop to
speed up the process

**Comment by cgcgcg** [comment]
@bathmatt Will do!

**Comment by bathmatt** [comment]
Fixed
