### ISSUE TITLE
Mispelled ATDM environment variable

### ISSUE THREAD

**Issue by jhux2** [trilinos/Trilinos#5930]
@bartlettroscoe @trilinos/framework  The variable `ATDM_CONFIG_TRILNOS_DIR` is mispelled in the following files (missing an "I"):

```bash
std/atdm/utils/unset_atdm_config_vars_all.sh:unset ATDM_CONFIG_TRILNOS_DIR
std/atdm/load-env.sh:export ATDM_CONFIG_TRILNOS_DIR=`atdm_config_get_abs_dir_path ${ATDM_CONFIG_SCRIPT_DIR}/../../..`
std/atdm/load-env.sh:  echo "ATDM_CONFIG_TRILNOS_DIR = $ATDM_CONFIG_TRILNOS_DIR"
std/atdm/load-env.sh:  export ATDM_CONFIG_NVCC_WRAPPER="${ATDM_CONFIG_TRILNOS_DIR}/packages/kokkos/bin/nvcc_wrapper"
```

This could potentially lead to confusion for anyone using these variables downstream.

**Comment by bartlettroscoe** [comment]
@jhux2, thanks for the FYI.  Just hope EMPIRE is not using the wrong name but I can check that.

**Comment by bartlettroscoe** [comment]
I checked the EM-Plasma/BuildScripts 'develop' branch and could not find any reference to `ATDM_CONFIG_TRILNOS_DIR`.  All that I could find was in the Trilinos files:

```
./cmake/std/atdm/utils/unset_atdm_config_vars_all.sh
./cmake/std/atdm/load-env.sh
```

The fix for this is in PR #5981

**Comment by jhux2** [comment]
@bathmatt @jjellio I think this will affect the EMPIRE build scripts.

**Comment by bartlettroscoe** [comment]
> @bathmatt @jjellio I think this will affect the EMPIRE build scripts.

I searched all of the files in the EM-Plasma/BuildScripts files and could not find any references to this variable.  That env var was not really mean to be used externally.  The location of Trilinos that EMPIRE is using is likely the env var set by `<install-prefix>/load_matching_env.sh` which has not changed.

**Comment by jjellio** [comment]
Is this what caused Trilinos to recursively install stuff into `install_dir/share`?
I never root caused that... but when I pulled EMPIRE Trilinos it would install all manner of things form the parent directory (I think Jonathan saw that behavior as well).

**Comment by bartlettroscoe** [comment]
@jjellio asked:

> Is this what caused Trilinos to recursively install stuff into `install_dir/share`?

Never heard of such an error but this little change should not be related to that that I can see.  What are you seeing and is it reproducable?

**Comment by jjellio** [comment]
Jonathan and I saw it on Vortex, but I am not sure either of us had time to reason out what the problem is.

The series of events, was 
*  Pull EMPIRE Trilinos
*  Start a build (using a custom vortex environment that works fine)
*  install the build

The install would start putting the entire build directory (maybe more?) into `install_path/share`

I never wanted to pull, so I rolled back my clone since I am bug hunting and didn't want my Trilinos to change. I think Jonathan saw the same thing.

**Comment by bartlettroscoe** [comment]
FHI: PR #5981 just merged.

I will leave this issue "In Review" for now just to make sure this does not cause a problem for EMPIRE or any other ATDM customer.

**Comment by rppawlo** [comment]
This variable is in @bathmatt 's custom environment.sh script on vortex. If anyone is using that script, you will need to fix the spelling when you update Trilinos. These changes probably will not make it into empire's fork of Trilinos for a while. The sync has been broke and fixing is less a priority than the cuda random failure thing.

**Comment by bartlettroscoe** [comment]
> This variable is in @bathmatt 's custom environment.sh script on vortex. 

I wonder why?  The other `<system_name>/environment.sh` scripts don't use this variable.

Might be good to put that script and others like it under version control in the `EM-Plasma/BuildScripts` repo.  That way, we can all work together keep these things working.

**Comment by bartlettroscoe** [comment]
When can we close this issue?  What further confirmation is needed?

**Comment by jhux2** [comment]
EMPIRE has updated its scripts.   We can close. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
