### ISSUE TITLE
MueLu: matrix-reading in Driver.cpp requires coordinates

### ISSUE THREAD

**Issue by jhux2** [trilinos/Trilinos#5934]
@trilinos/muelu 

When reading a matrix into the MueLu scaling driver Driver.cpp, coordinates are also required.  If you don't supply them, the driver crashes in a non-obvious way.  Coordinates should be optional.  At the very least, MueLu should print a better error message.

**Comment by csiefer2** [comment]
#5941

**Comment by jhux2** [comment]
@rstumin If this works for you, please feel free to close.  Thanks, @csiefer2!

**Comment by rstumin** [comment]
I'm a happy guy. Things now work for me without coordinates.
