### ISSUE TITLE
Tpetra: Best practice for sparse matrix A(i,j) access?

### ISSUE THREAD

**Issue by DABH** [trilinos/Trilinos#5943]
I built a distributed Tpetra::CrsMatrix A.  Mostly for sanity checking purposes, I wanted to access A(i,j) -- which might live non-locally -- for some rows/cols to make sure the matrix looks good.  However, I didn't see an obvious way to do this from the docs.  The solution I came up with was to use A.getGlobalRowCopy and pick out a particular column, but this feels kind of ugly because in particular it requires allocating extra ArrayViews, knowledge of the number of non-zeros per row, etc.

Is there an easy way to do what I'm trying to achieve, or any best practices?  My current code looks something like this:

```
        std::vector<global_ordinal_type> indices(nnzs[i]);
        std::vector<scalar_type> values(nnzs_teuchos[i]);
        Teuchos::ArrayView<global_ordinal_type> _i = Teuchos::arrayViewFromVector(indices);
        Teuchos::ArrayView<scalar_type> _v = Teuchos::arrayViewFromVector(values);
        (*A).getGlobalRowCopy(static_cast<global_ordinal_type>(i), _i, _v, nnzs[j]);
        printf("entry is %f\n", _v[j]);
```

**Comment by mhoemmen** [comment]
Have you gone through the Tpetra tutorial?  Look [here](https://github.com/trilinos/Trilinos/tree/master/packages/tpetra/core/example) (`Trilinos/packages/tpetra/core/example`) for `Lesson*` directories.

In general, you can't access nonlocal data.  If you need to, then you'll need to redistribute it by using `doExport` or `doImport`, as appropriate.

**Comment by DABH** [comment]
Thanks!  Yep, I’ve gone through the lessons.  I guess this confirms my suspicion that there’s no easy way to do this (by design) so if really needed I’ll just write a helper function to do the global communication.

**Comment by kliegeois** [comment]
If it is just for sanity checking/debugging purposes, @DABH you might want to look into `Tpetra::MatrixMarket::Writer` which will write your distributed sparse matrix on disk.
