### ISSUE TITLE
MueLu: compilation error

### ISSUE THREAD

**Issue by jhux2** [trilinos/Trilinos#5948]
Compilation is broken in a couple different situations:

https://testing.sandia.gov/cdash/viewBuildError.php?buildid=5663513
https://github.com/trilinos/Trilinos/pull/5883#issuecomment-533398209

Looks like it could be related PR #5883.

@trilinos/muelu @csiefer2

**Comment by jhux2** [comment]
@DABH

**Comment by DABH** [comment]
It's definitely that PR since if I check out the commit right before that PR was merged, compilation goes fine.

**Comment by csiefer2** [comment]
Ugh.  Lovely.

**Comment by DABH** [comment]
This can probably be closed, I haven't seen any recurrence of these compilation issues after #5963 .
