### ISSUE TITLE
MueLu: expected type-specifier error

### ISSUE THREAD

**Issue by hillyuan** [trilinos/Trilinos#5952]
## Bug Report
@trilinos/\MueLu

### Description
Following  error when compile in Ubuntu with gcc

> MueLu_FactoryManager_def.hpp:163:108: error: expected type-specifier before ‘ScaledNullspaceFactory’

**Comment by DABH** [comment]
This is a duplicate of https://github.com/trilinos/Trilinos/issues/5948 but your fix looks good, thanks for getting to the bottom of this

**Comment by mhoemmen** [comment]
@trilinos/muelu

**Comment by csiefer2** [comment]
See #5963

**Comment by jhux2** [comment]
Closing as duplicate of #5948.
