### ISSUE TITLE
Simplify Panzer_EquationSet_Factory_Defines

### ISSUE THREAD

**Issue by jmgate** [trilinos/Trilinos#596]
In `panzer/disc-fe/src/Panzer_EquationSet_Factory_Defines.hpp` we have `PANZER_DECLARE_EQSET_TEMPLATE_BUILDER` which takes a `key` and doesn't use it, and we have `PANZER_BUILD_EQSET_OBJECTS` which takes a `fClass` and doesn't use it.  These definitions should be cleaned up, and then their use in Panzer and any of the applications it supports should be updated accordingly.

**Comment by jmgate** [comment]
Just to give an idea of scope, here are the occurrences of these functions in our code:
 | Panzer | DrekarBase | DrekarResearch | Charon2
`PANZER_DECLARE_EQSET_TEMPLATE_BUILDER` | 16 | 0 | 0 | 13
`PANZER_BUILD_EQSET_OBJECTS` | 22 | 0 | 0 | 13
Not sure why they don't show up in Drekar.

**Comment by jmgate** [comment]
Ah, Drekar has its own methods:
`DREKAR_DECLARE_EQSET_TEMPLATE_BUILDER`:
* DrekarBase:  23
* DrekarResearch:  6

`DREKAR_BUILD_EQSET_OBJECTS`:
* DrekarBase:  23
* DrekarResearch:  6

**Comment by jmgate** [comment]
Looks like Drekar also has similar `_GENERAL` and `_AUX_` macros that all need the same changes.

**Comment by jmgate** [comment]
Made all the necessary changes -- just waiting on a coordinated push to Trilinos, Drekar, Charon, and Empire.

**Comment by bathmatt** [comment]
You can push whenever, I will clean up EMPIRE at a later date...

**Comment by jmgate** [comment]
Changes pushed to Panzer, Drekar, and Charon.  @bathmatt will take care of Empire sometime soon.

**Comment by jmgate** [comment]
Realized that the macros in `Panzer_BCStrategy_Factory_Defines.hpp` could be cleaned up similarly.  Reopening this issue to do that work and check to make sure there's nothing more out there that should be cleaned up in a similar fashion.

**Comment by jmgate** [comment]
Latest changes pushed to Panzer, DrekarBase, DrekarResearch, and Charon.  @bathmatt, there might be similar updates to make in Empire&mdash;not sure.

**Comment by jmgate** [comment]
@rppawlo, @eric-c-cyr, can we close this out?

**Comment by rppawlo** [comment]
> @rppawlo, @eric-c-cyr, can we close this out?

yes
