### ISSUE TITLE
MueLu: build error on Ride 

### ISSUE THREAD

**Issue by ikalash** [trilinos/Trilinos#5962]
The Albany nightlies last night failed due to MueLu.  Here is the error - seems like there is a missing overloaded implementation:

```
 91%] Building CXX object packages/muelu/src/CMakeFiles/muelu_lgn.dir/Utils/ExplicitInstantiation/MueLu_LocalLexicographicIndexManager.cpp.o
/home/projects/albany/ride/repos/Trilinos/packages/muelu/src/Graph/UncoupledAggregation/MueLu_AggregationPhase2bAlgorithm_kokkos_def.hpp(144): error: no instance of overloaded function "Kokkos::View<DataType, Properties...>::operator() [with DataType=signed int *, Properties=<Kokkos::CudaUVMSpace::memory_space>]" matches the argument list
            argument types are: (signed int, int)
            object type is: const Kokkos::View<signed int *, Kokkos::CudaUVMSpace::memory_space>
          detected during instantiation of "void MueLu::AggregationPhase2bAlgorithm_kokkos<LocalOrdinal, GlobalOrdinal, Node>::BuildAggregatesRandom(const Teuchos::ParameterList &, const MueLu::AggregationPhase2bAlgorithm_kokkos<LocalOrdinal, GlobalOrdinal, Node>::LWGraph_kokkos &, MueLu::AggregationPhase2bAlgorithm_kokkos<LocalOrdinal, GlobalOrdinal, Node>::Aggregates_kokkos &, Kokkos::View<unsigned int *, MueLu::LWGraph_kokkos<LocalOrdinal, GlobalOrdinal, Node>::memory_space> &, MueLu::AggregationPhase2bAlgorithm_kokkos<LocalOrdinal, GlobalOrdinal, Node>::LO &) const [with LocalOrdinal=int, GlobalOrdinal=longlong, Node=Kokkos_Compat_KokkosCudaWrapperNode]"
(80): here
```
Unfortunately our dashboard is down right now, so I cannot point you to that.

@trilinos/muelu

**Comment by lucbv** [comment]
@ikalash this is related to work I am doing now.
Could you add a config script for reproduceability?

**Comment by ikalash** [comment]
@lucbv : oh ok, great.  You will find our config options here: https://github.com/SNLComputation/Albany/blob/master/doc/dashboards/ride.sandia.gov/ctest_nightly.cmake.frag#L153-L295 (unfortunately it's part of a cdash script, so you'd have to parse it a little bit to convert it to a configure script that can be executed).

**Comment by lucbv** [comment]
@ikalash 
PR #5969 should fix your problem, at least I was able to fix a problem reported by @bartgol with the same class `AggregationPhase2bAlgorithm_kokkos` using his CMake configuration.
I will do a build with the configuration you sent above and check that it works fine, although I probably won't have time to build on `white` until tomorrow morning.

**Comment by ikalash** [comment]
@lucbv: thanks!  It may be easiest to just push the fix, then let the CDash tell us if it fixed the issue or not, given how long the GPU builds typically take.

**Comment by lucbv** [comment]
@ikalash sounds good to me, the patch has been merged yesterday so there is a chance it might have already been tested overnight. Let me know if you see any improvement.

**Comment by ikalash** [comment]
Seems our ride nightly is back to normal - thanks for fixing it!
