### ISSUE TITLE
Amesos2:  Memory Leak with SuperLU

### ISSUE THREAD

**Issue by jfike** [trilinos/Trilinos#5988]
## Bug Report
@trilinos/amesos2

### Description
When running SPARC with clang's address sanitizer we see reports of memory leaks that point to using SuperLU in amesos2.  I don't believe that is an issue with how SPARC is using amesos2, but I could be wrong.  Based on the error messages it looks like the leak is created by the call to dist_psymbtonum in Superludist::numericFactorization_impl.

**Comment by jhux2** [comment]
@trilinos/amesos2

**Comment by srajama1** [comment]
@kyungjoo-kim : Do you have time to help with this one please ?

**Comment by kyungjoo-kim** [comment]
@jhux2 Is this the same problem that Micah asked in the other email thread ? Could you give me an instrution to reproduce ?

**Comment by jhux2** [comment]
I'm not the reporter, @jfike is.

**Comment by kyungjoo-kim** [comment]
Oh.. .sorry.. then it should be the same one.

**Comment by jfike** [comment]
I don't believe it is the same issue as the other email thread about SuperLU-dist 5.4.  This is using SPARC's current set of TPLs, so it is clang 5.0.1 and SuperLU-dist 4.2.  I'm not sure how to reproduce this without running SPARC.

If it helps, here are some of the memory leak messages reported by the address sanitizer:
Direct leak of 65736 byte(s) in 99 object(s) allocated from:
    #0 0xd247f28 in __interceptor_malloc /sierra/sntools/extras/build/llvm-5.01-src/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:67
    #1 0x24e7d614 in superlu_malloc_dist (/scratch/jafike/CODES/sparc/clang_asan/bin/sparc+0x24e7d614)
    #2 0x24e7d68d in intMalloc_dist (/scratch/jafike/CODES/sparc/clang_asan/bin/sparc+0x24e7d68d)
    #3 0x24e61474 in dist_symbLU (/scratch/jafike/CODES/sparc/clang_asan/bin/sparc+0x24e61474)
    #4 0x24e5d48a in ddist_psymbtonum (/scratch/jafike/CODES/sparc/clang_asan/bin/sparc+0x24e5d48a)
    #5 0x22ed3578 in Amesos2::FunctionMap<Amesos2::Superludist, double>::dist_psymbtonum(SLUD::fact_t, int, SLUD::SuperMatrix*, SLUD::ScalePermstruct_t*, SLUD::Pslu_freeable_t*, SLUD::D::LUstruct_t*, SLUD::gridinfo_t*) /ascldap/users/sparc/Trilinos/packages/amesos2/src/Amesos2_Superludist_FunctionMap.hpp:349:7
    #6 0x22ed30de in Amesos2::Superludist<Tpetra::CrsMatrix<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >, Tpetra::MultiVector<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > >::numericFactorization_impl() /ascldap/users/sparc/Trilinos/packages/amesos2/src/Amesos2_Superludist_def.hpp:419:9
    #7 0x22ed8808 in Amesos2::SolverCore<Amesos2::Superludist, Tpetra::CrsMatrix<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >, Tpetra::MultiVector<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > >::numericFactorization() /ascldap/users/sparc/Trilinos/packages/amesos2/src/Amesos2_SolverCore_def.hpp:153:36
    #8 0x2070f86b in LinearSolverAmesos2::Solve() /scratch/jafike/CODES/sparc/sparc-ear99/src/solver-linsys/LinearSolverAmesos2.C:84:17

This leads me to suspect that the call to dist_psymbtonum in Superludist::numericFactorization_impl is declaring memory that is not freed.

**Comment by jfike** [comment]
I built SuperLU-dist 4.2 with "-g" so that I could get line numbers.  Here are the updated address sanitizer messages:

    #0 0xd5bbf08 in __interceptor_malloc /sierra/sntools/extras/build/llvm-5.01-src/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:67
    #1 0x251c0154 in superlu_malloc_dist /scratch/jafike/sparc_repo_full_tpls/sparc/sparc-devops/build/superlu_dist-4.2/SRC/memory.c:108:20
    #2 0x251c01cd in intMalloc_dist /scratch/jafike/sparc_repo_full_tpls/sparc/sparc-devops/build/superlu_dist-4.2/SRC/memory.c:146:21
    #3 0x251a3fb4 in dist_symbLU /scratch/jafike/sparc_repo_full_tpls/sparc/sparc-devops/build/superlu_dist-4.2/SRC/pdsymbfact_distdata.c:167:20
    #4 0x2519ffca in ddist_psymbtonum /scratch/jafike/sparc_repo_full_tpls/sparc/sparc-devops/build/superlu_dist-4.2/SRC/pdsymbfact_distdata.c:1275:8

**Comment by jfike** [comment]
The memory leak is a result of calling symbolic factorization multiple times without freeing the memory in between.  This is resolved in our application by ensuring that we only call symbolic factorization once.

**Comment by ndellingwood** [comment]
Cross-referencing PR #6010
