### ISSUE TITLE
Failing MueLu tests on perseus

### ISSUE THREAD

**Issue by tawiesn** [trilinos/Trilinos#599]
The tests [here](http://testing.sandia.gov/cdash/buildSummary.php?buildid=2554392) are failing.

According to the configuration output it uses a current Trilinos version (e.g., from Sep 2).

I tried to reproduce the problem (using gcc instead of intel, since i have no SEMS environment on my machine), but it is not even linking on my machine. 

```
Processing enabled package: Tpetra (Classic, Kernels, TSQR, Core)
-- NOTE: Kokkos::Serial is ON (the CMake option Kokkos_ENABLE_Serial is ON), but the corresponding Tpetra Node type is disabled.  If you want to enable instantiation and use of Kokkos::Serial in Tpetra, please also set the CMake option Tpetra_INST_SERIAL:BOOL=ON.  If you use the Kokkos::Serial Node type in Tpetra without doing this, you will get link errors!
-- Tpetra execution space availability (ON means available): 
--   - Serial:  OFF
--   - Threads: ON
--   - OpenMP:  OFF
--   - Cuda:    OFF
-- User-set default Node: Kokkos::Compat::KokkosThreadsWrapperNode
-- Not enabling Tpetra/RTI
Processing enabled package: Xpetra (Libs)
-- Xpetra support for 32 bit Epetra enabled.
--    Xpetra_Epetra_NO_32BIT_GLOBAL_INDICES=OFF
-- Xpetra support for 64 bit Epetra enabled.
--    Xpetra_Epetra_NO_64BIT_GLOBAL_INDICES=OFF
...
Processing enabled package: MueLu (Libs, Tests, Examples)
-- MueLu ETI support enabled
-- <float,   int, int>       : OFF
-- <double,  int, int>       : ON
-- <double,  int, long>      : OFF
-- <double,  int, long long> : ON
-- <complex, int, int>       : OFF
-- HAVE_MUELU_SERIAL       : ON
-- HAVE_MUELU_PTHREAD      : ON
-- HAVE_MUELU_OPENMP       : OFF
-- HAVE_MUELU_CUDA         : OFF

```
So, i don't know what exactly runs in that test.

**Comment by jhux2** [comment]
@trilinos/muelu

**Comment by aprokop** [comment]
The issue is obvious: Zoltan2Interface does not have "number of partitions" in the GetValidParameterList.

Also, why is GetValidParameterList definition is in the MueLu_Zoltan2Interface_decl.hpp instead of _def.hpp? This is against the normal approach.

**Comment by tawiesn** [comment]
@aprokop You're right. The "number of partitions" was missing in the Epetra specialization of the Zoltan2Interface. I forgot to add it there (since i didn't expect it in the *_decl.hpp file).

In the *_decl.hpp file we have a specialization of the Zoltan2Interface for Epetra which either uses Zoltan instead of Zoltan2 underneath or provides a stub implementation. I think the reason was that we wanted to test the repartitioning using Zoltan/Zoltan2 with only one testing stack (i.e. Zoltan2Interface in the xml files). In case of Epetra it was supposed to fall back to using Zoltan. I don't know whether there was a specific reason why we did not want to use Zoltan2 with Epetra. Maybe, it was because we could not check whether Zoltan has been compiled with Epetra support or not. One probably should check the HAVE_ZOLTAN2_EPETRA flag and adapt the guards in Zoltan2Interface accordingly.

The checkin script is running to fix the problem with "number of partitions". I will file a new issue about the Zoltan2Interface and Epetra support.

**Comment by aprokop** [comment]
OK. I did not notice the stub.
