### ISSUE TITLE
MueLu/Belos: Preconditioning Poisson system with rank 1 nullspace

### ISSUE THREAD

**Issue by DABH** [trilinos/Trilinos#6005]
## Question

I have a square, symmetric, positive-(semi)-definite matrix A which comes from a Poisson system with all Neumann boundary conditions and therefore has a rank one nullspace, whose basis is just the constant vector.  I'm able to use Belos with an unpreconditioned CG solve to solve my system without any issues.  However, when trying to add preconditioners from MueLu, the ability of CG to converge seems very sensitive to the preconditioner settings -- sometimes I can get a solution with a great speedup and other times I get errors about p^H A p < 0.  It tends to be much more of the latter for larger problem sizes.

I'm aware that due to the singularity of the matrix it's natural to expect issues like this, but I also believe there are several potential ways to work around them.

1) Are you aware of any preconditioner / preconditioner settings which are effective for a case like this with a trivial, know, rank 1 nullspace for an otherwise "nice" system?

2) I've seen some references in the MueLu user's guide / tutorials about nullspace, but I didn't find a complete example of how to set the nullspace for the preconditioner/solver, and I'm not sure where this info about the nullspace needs to be propagated.  For instance:
-- Do all layers of the hierarchy need to have the nullspace set?
-- Does the Belos solver need to be told about the nullspace, or only the preconditioners?
-- If I specify the nullspace from an XML file, how do I specify _what_ the nullspace is?

3) For other libraries like petsc I've found threads like
https://lists.mcs.anl.gov/pipermail/petsc-users/2008-August/003240.html
which describe options they have like `-pc_factor_shift_positive_definite` which help keep preconditioners positive definite (probably at the cost of some efficacy?).  Is there anything similar in MueLu where I can just "force" the levels to all be PD with some diagonal shifting?

4) On paper at least, if x sums to zero, then I can solve (A + oo^T)x = b (where o is an all ones vector) and get the same answer as Ax=b, but in this case (A + oo^T) is full rank.  Is there any way with Trilinos where I could solve this modified system in a way that does the rank-one update efficiently, i.e. computes Ax and o*(o^T x) separately in the CG iteration, etc.?  I'm not sure whether this would ultimately help, and the problem may be in the preconditioners not the system itself, but thought I'd ask your thoughts about it.

Thanks in advance for sharing any expertise you might have!

**Comment by mayrmt** [comment]
@trilinos/muelu

**Comment by mayrmt** [comment]
@DABH Regarding your second question about setting the null space:

> Do all layers of the hierarchy need to have the nullspace set?

No, just on the fine level. When creating the preconditioner via `MueLu::CreateXpetraPreconditioner()` (similar functions exist for Epetra and Tpetra), then the fine level null space is read from the xml-file. To set the null space in the xml-file, first create it as an `Teuchos::RCP<Xpetra::MultiVector< >> nullspace` and put this vector as a parameter named "Nullspace" into the "user data" sublist of the MueLu parameter list, somehow similar to `mueluParameterList->sublist("user data").set("Nullspace", nullspace)`.
Furthermore, the xml-file then specifies, which factory (usually some prolongator factory) will generate the null space for the coarser levels.

> Does the Belos solver need to be told about the nullspace, or only the preconditioners?

No, just the MueLu preconditioner.

> If I specify the nullspace from an XML file, how do I specify what the nullspace is?

See above.

**Comment by cgcgcg** [comment]
@DABH Usually, what MueLu refers to as the 'nullspace' is a near-nullspace, so it's not actually eigenvectors with eigenvalue zero. In your case, the constant function forms an actual nullspace. We recently added an option to deal with this use case. Could you try adding
```
<Parameter name="coarse: type" type="string" value="Klu">
<ParameterList name="coarse: params">
<Parameter name="fix nullspace" type="bool" value="true">
</ParameterList>
```
to your input xml? This does modify the coarsest level system A to A + oo^T, but you should not see much in terms of a performance hit. I believe that Belos also has some projected CG that you could look into.

**Comment by DABH** [comment]
@mayrmt @cgcgcg Thanks both so much for the insights, this is very useful.

I tried both of your suggestions.  Interestingly, neither the `fix nullspace` option nor setting the nullspace via
```
Teuchos::RCP<vec_type> nullspace = Teuchos::rcp(new vec_type(A->getDomainMap(), 1));
nullspace->putScalar(1);
muleLuPreconditioner->GetHierarchy()->GetLevel(0)->Set("Nullspace", nullspace);
```
seemed to have an effect on whether PCG ran into an error or not.  In particular, the parameter XML file I've been playing with looks like
```
<ParameterList name="MueLu">
	<Parameter name="verbosity" type="string" value="high"/>
	<Parameter name="max levels" type="int" value="3"/>
	<Parameter name="coarse: max size" type="int" value="10"/>
	<Parameter name="multigrid algorithm" type="string" value="sa"/>

    <Parameter name="transpose: use implicit" type="bool" value="true"/>
    <Parameter name="repartition: enable" type="bool" value="false"/>
    <Parameter name="repartition: rebalance P and R" type="bool" value="false"/>

    <Parameter name="smoother: type" type="string" value="CHEBYSHEV"/>
    <ParameterList name="smoother: params">
        <Parameter name="chebyshev: degree" type="int" value="2"/>
        <Parameter name="chebyshev: ratio eigenvalue" type="double" value="20"/>
        <Parameter name="chebyshev: min eigenvalue" type="double" value="1.0"/>
        <Parameter name="chebyshev: zero starting solution" type="bool" value="true"/>
    </ParameterList>

    <Parameter name="coarse: type" type="string" value="Klu"/>
	<ParameterList name="coarse: params">
		<Parameter name="fix nullspace" type="bool" value="true"/>
	</ParameterList>

	<!-- Damped Jacobi smoothing -->
	<!--<Parameter name="smoother: type" type="string" value="RELAXATION"/>
	<ParameterList name="smoother: params">
		<Parameter name="relaxation: type" type="string" value="Jacobi"/>
		<Parameter name="relaxation: sweeps" type="int" value="3"/>
		<Parameter name="relaxation: damping factor" type="double" value="0.9"/>
	</ParameterList>-->

	<!-- Aggregation -->
	<Parameter name="aggregation: type" type="string" value="uncoupled"/>
	<Parameter name="aggregation: min agg size" type="int" value="9"/>
	<Parameter name="aggregation: max agg size" type="int" value="27"/>
</ParameterList>
```
When I use the Chebyshev smoother with degree 2 then PCG converges great, but if I change this to e.g. degree 3 or to Jacobi relaxation instead of Chebyshev then I get errors about p^H A p <= 0.

Perhaps my usage is just wrong still?  Or, any thoughts as to why the behavior might be so sensitive as to the preconditioner parameters, especially when (I think?) I'm handling the nullspace appropriately?

**Comment by mhoemmen** [comment]
Belos' CG implementation has an option to turn off those errors and let `p^H A p <= 0` happen.  You could try that.  It would be better to run MINRES in this case, but people don't.

**Comment by DABH** [comment]
Thanks, I managed to find that option -- for reference,
```
belosList.set("Assert Positive Definiteness", false);
```
although setting it didn't seem to actually disable the check -- so I just edited the header file https://trilinos.org/docs/dev/packages/belos/doc/html/BelosCGIter_8hpp_source.html to default that variable to false.  Anyway, without doing that check, CG doesn't crash but doesn't converge, and I also tried MINRES and BiCGSTAB and neither converged (nothing totally diverged / went crazy either, but couldn't get residual down past 1e-1 or 1e-2...).

So I guess my conclusion is that the preconditioners really need to be positive definite or I'll be in trouble (at least for my system)?  Are there any recommended choices/settings for MueLu which guarantee PD preconditioners?  Or is it kind of a question of "guess and check" (for instance, Chebyshev smoother with degree 2 seems fine, but degree 3 runs into issues)?

**Comment by cgcgcg** [comment]
@DABH Well, the issue really is that the original matrix is not positive definite. I'm a bit puzzled as to why degree 2 Chebyshev works, but not degree 3. What you could do is to increase the number of initial power iterations to something large, say 100. If that does help, we can work from there. As for Jacobi, you could try reducing the damping factor.

**Comment by cgcgcg** [comment]
@DABH Also, just to make sure: You did check that the rhs is orthogonal to the constant vector?

**Comment by mhoemmen** [comment]
@DABH Would you mind making a pull request with your changes to Belos to make that option work? I'm curious what you had to do, since this thing worked a while back for a different problem.  Thanks!

**Comment by DABH** [comment]
@mhoemmen , finally circling back to this, here is what I had to do to make this work: https://github.com/trilinos/Trilinos/pull/6085 .  Let me know what you think -- thanks.

Now trying the other suggestions mentioned above to see how things go... appreciate the insights

**Comment by mhoemmen** [comment]
@DABH , I just approved your PR -- thanks! :-D

**Comment by DABH** [comment]
Going to go ahead and close this for now since my concerns have mostly evolved to #6094 .  By playing with the MueLu params I can tend to make the preconditioner work, and solve my system, but the performance seems to be suboptimal and that is ultimately the goal.  Thanks again
