### ISSUE TITLE
Intrepid2 tests timing out in build Trilinos-atdm-white-ride-gnu-7.2.0-openmp-debug starting testing day 2019-09-24

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#6020]
CC: @trilinos/intrepid2, @mperego (Trilinos Discretizations Product Lead), @bartlettroscoe, @fryeguy52

<Checklist>
<???: Add label "client: ATDM">
<???: Add label "ATDM Sev: Blocker" (by default but could be other "ATDM Sev: XXX")>
<???: Add label "type: bug"?>
<???: Add label for affected packages (e.g. "pkg: MueLu", "pkg: Tpetra", "pkg: Kokkos", etc.)>
<???: Add label "PA: ???Project Area???" (e.g. "PA: Linear Solvers", "PA: Data Services")>
<???: Add milestone "Initial cleanup of new ATDM ..." or "Keep promoted ATDM ...">
<???: Once GitHub Issue is created, add entries for tests to TrilinosATDMStatus/*.csv files>

## Next Action Status

<status-and-or-first-action>

## Description

As shown in [this query](https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&begin=2019-09-01&end=2019-10-02&filtercount=4&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-&field2=testname&compare2=65&value2=Intrepid2_&field3=status&compare3=61&value3=failed&field4=details&compare4=61&value4=Completed%20(Timeout)) the tests:

* `Intrepid2_unit-test_Projection_Serial_Test_Convergence_TET_MPI_1` (timing out every day)
* `Intrepid2_unit-test_Projection_Serial_Test_InterpolationProjection_HEX_MPI_1` (timing out most days)

are timing out in the build:

* `Trilinos-atdm-white-ride-gnu-7.2.0-openmp-debug`

starting testing day '2019-09-24' with history shown in the table:

<h3><font color="red">Tests without issue trackers Failed: twoif=2 (as of testing day 2019-10-01)</font></h3>
<table style="width:100%" boarder="1">

<tr>
<th>Site</th>
<th>Build Name</th>
<th>Test Name</th>
<th>Status</th>
<th>Details</th>
<th>Consec­utive Non-pass Days</th>
<th>Non-pass Last 30 Days</th>
<th>Pass Last 30 Days</th>
<th>Issue Tracker</th>
</tr>

<tr>
<td align="left">ride</td>
<td align="left"><a href="https://testing-dev.sandia.gov/cdash/index.php?project=Trilinos&amp;filtercombine=and&amp;filtercombine=&amp;filtercount=4&amp;showfilters=1&amp;filtercombine=and&amp;field1=buildname&amp;compare1=61&amp;value1=Trilinos-atdm-white-ride-gnu-7.2.0-openmp-debug&amp;field2=site&amp;compare2=61&amp;value2=ride&amp;field3=buildstarttime&amp;compare3=84&amp;value3=2019-10-02T04:01:00UTC&amp;field4=buildstarttime&amp;compare4=83&amp;value4=2019-09-02T04:01:00UTC">Trilinos-atdm-white-ride-gnu-7.2.0-openmp-debug</a></td>
<td align="left"><a href="https://testing-dev.sandia.gov/cdash/testDetails.php?test=75705062&amp;build=4897243">Intrepid2_­unit-test_­Projection_­Serial_­Test_­Convergence_­TET_­MPI_­1</a></td>
<td align="left"><a href="https://testing-dev.sandia.gov/cdash/testDetails.php?test=75705062&amp;build=4897243"><font color="red">Failed</font></a></td>
<td align="left">Completed (Timeout)</td>
<td align="right"><a href="https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&amp;filtercombine=and&amp;filtercombine=&amp;filtercount=5&amp;showfilters=1&amp;filtercombine=and&amp;field1=buildname&amp;compare1=61&amp;value1=Trilinos-atdm-white-ride-gnu-7.2.0-openmp-debug&amp;field2=testname&amp;compare2=61&amp;value2=Intrepid2_unit-test_Projection_Serial_Test_Convergence_TET_MPI_1&amp;field3=site&amp;compare3=61&amp;value3=ride&amp;field4=buildstarttime&amp;compare4=84&amp;value4=2019-10-02T04:01:00UTC&amp;field5=buildstarttime&amp;compare5=83&amp;value5=2019-09-02T04:01:00UTC"><font color="red">7</font></a></td>
<td align="right"><a href="https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&amp;filtercombine=and&amp;filtercombine=&amp;filtercount=5&amp;showfilters=1&amp;filtercombine=and&amp;field1=buildname&amp;compare1=61&amp;value1=Trilinos-atdm-white-ride-gnu-7.2.0-openmp-debug&amp;field2=testname&amp;compare2=61&amp;value2=Intrepid2_unit-test_Projection_Serial_Test_Convergence_TET_MPI_1&amp;field3=site&amp;compare3=61&amp;value3=ride&amp;field4=buildstarttime&amp;compare4=84&amp;value4=2019-10-02T04:01:00UTC&amp;field5=buildstarttime&amp;compare5=83&amp;value5=2019-09-02T04:01:00UTC"><font color="red">7</font></a></td>
<td align="right"><a href="https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&amp;filtercombine=and&amp;filtercombine=&amp;filtercount=5&amp;showfilters=1&amp;filtercombine=and&amp;field1=buildname&amp;compare1=61&amp;value1=Trilinos-atdm-white-ride-gnu-7.2.0-openmp-debug&amp;field2=testname&amp;compare2=61&amp;value2=Intrepid2_unit-test_Projection_Serial_Test_Convergence_TET_MPI_1&amp;field3=site&amp;compare3=61&amp;value3=ride&amp;field4=buildstarttime&amp;compare4=84&amp;value4=2019-10-02T04:01:00UTC&amp;field5=buildstarttime&amp;compare5=83&amp;value5=2019-09-02T04:01:00UTC"><font color="green">22</font></a></td>
<td align="right"></td>
</tr>

<tr>
<td align="left">ride</td>
<td align="left"><a href="https://testing-dev.sandia.gov/cdash/index.php?project=Trilinos&amp;filtercombine=and&amp;filtercombine=&amp;filtercount=4&amp;showfilters=1&amp;filtercombine=and&amp;field1=buildname&amp;compare1=61&amp;value1=Trilinos-atdm-white-ride-gnu-7.2.0-openmp-debug&amp;field2=site&amp;compare2=61&amp;value2=ride&amp;field3=buildstarttime&amp;compare3=84&amp;value3=2019-10-02T04:01:00UTC&amp;field4=buildstarttime&amp;compare4=83&amp;value4=2019-09-02T04:01:00UTC">Trilinos-atdm-white-ride-gnu-7.2.0-openmp-debug</a></td>
<td align="left"><a href="https://testing-dev.sandia.gov/cdash/testDetails.php?test=75705060&amp;build=4897243">Intrepid2_­unit-test_­Projection_­Serial_­Test_­InterpolationProjection_­HEX_­MPI_­1</a></td>
<td align="left"><a href="https://testing-dev.sandia.gov/cdash/testDetails.php?test=75705060&amp;build=4897243"><font color="red">Failed</font></a></td>
<td align="left">Completed (Timeout)</td>
<td align="right"><a href="https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&amp;filtercombine=and&amp;filtercombine=&amp;filtercount=5&amp;showfilters=1&amp;filtercombine=and&amp;field1=buildname&amp;compare1=61&amp;value1=Trilinos-atdm-white-ride-gnu-7.2.0-openmp-debug&amp;field2=testname&amp;compare2=61&amp;value2=Intrepid2_unit-test_Projection_Serial_Test_InterpolationProjection_HEX_MPI_1&amp;field3=site&amp;compare3=61&amp;value3=ride&amp;field4=buildstarttime&amp;compare4=84&amp;value4=2019-10-02T04:01:00UTC&amp;field5=buildstarttime&amp;compare5=83&amp;value5=2019-09-02T04:01:00UTC"><font color="red">2</font></a></td>
<td align="right"><a href="https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&amp;filtercombine=and&amp;filtercombine=&amp;filtercount=5&amp;showfilters=1&amp;filtercombine=and&amp;field1=buildname&amp;compare1=61&amp;value1=Trilinos-atdm-white-ride-gnu-7.2.0-openmp-debug&amp;field2=testname&amp;compare2=61&amp;value2=Intrepid2_unit-test_Projection_Serial_Test_InterpolationProjection_HEX_MPI_1&amp;field3=site&amp;compare3=61&amp;value3=ride&amp;field4=buildstarttime&amp;compare4=84&amp;value4=2019-10-02T04:01:00UTC&amp;field5=buildstarttime&amp;compare5=83&amp;value5=2019-09-02T04:01:00UTC"><font color="red">5</font></a></td>
<td align="right"><a href="https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&amp;filtercombine=and&amp;filtercombine=&amp;filtercount=5&amp;showfilters=1&amp;filtercombine=and&amp;field1=buildname&amp;compare1=61&amp;value1=Trilinos-atdm-white-ride-gnu-7.2.0-openmp-debug&amp;field2=testname&amp;compare2=61&amp;value2=Intrepid2_unit-test_Projection_Serial_Test_InterpolationProjection_HEX_MPI_1&amp;field3=site&amp;compare3=61&amp;value3=ride&amp;field4=buildstarttime&amp;compare4=84&amp;value4=2019-10-02T04:01:00UTC&amp;field5=buildstarttime&amp;compare5=83&amp;value5=2019-09-02T04:01:00UTC"><font color="green">24</font></a></td>
<td align="right"></td>
</tr>

</table>

The new commits that were pulled on testing day 2019-09-24 were shown, for example, [here](https://testing.sandia.gov/cdash/viewNotes.php?buildid=5684647#!#note6).  It seems likely that these timeouts were triggered by the setting of `Trilinos_ENABLE_DEBUG=ON` in all of the ATDM `debug` builds in the commit c870075 merged to 'atdm-nightly' that day in the commit 004065d (later merged to the 'develop' branch in the PR #5970.

## Current Status on CDash

The failures of the Intrepid2 tests over the last 10 says can be see in:

* [Intrepid2 failing tests in build Trilinos-atdm-white-ride-gnu-7.2.0-openmp-debug last 10 days](https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&begin=10%20days%20ago&end=now&filtercount=4&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-white-ride-gnu-7.2.0-openmp-debug&field2=testname&compare2=65&value2=Intrepid2_&field3=status&compare3=61&value3=failed&field4=details&compare4=61&value4=Completed%20(Timeout))

## Steps to Reproduce

One should be able to reproduce this failure on the machines 'ride' or 'white' as described in:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md

More specifically, the commands given for the system 'ride' or 'white' are provided at:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#ridewhite

The exact commands to reproduce this issue should be:

```
$ cd <some_build_dir>/

$ source $TRILINOS_DIR/cmake/std/atdm/load-env.sh \
    Trilinos-atdm-white-ride-gnu-7.2.0-openmp-debug

$ cmake \
 -GNinja \
 -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
 -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_Intrepid2=ON \
 $TRILINOS_DIR

$ make NP=16

$ bsub -x -Is -q rhel7F -n 16 ctest -j8
```

**Comment by bartlettroscoe** [comment]
@trilinos/intrepid2, @mperego,

Given that theses tests run just fine in all of the other builds as shown in [this query](https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&date=2019-10-01&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-&field2=block&field2count=2&field2field1=testname&field2compare1=61&field2value1=Intrepid2_unit-test_Projection_Serial_Test_Convergence_TET_MPI_1&field2field2=testname&field2compare2=61&field2value2=Intrepid2_unit-test_Projection_Serial_Test_InterpolationProjection_HEX_MPI_1), I would suggest just disabling these tests for just this one build.  

Okay?

**Comment by bartlettroscoe** [comment]
@fryeguy52, FYI: It took about 15 min to create this issue by hand.

**Comment by bartlettroscoe** [comment]
These are disabled in PR #6121 and I manually merged to 'atdm-nightly' in the commit 1fe27b5.

Putting this in review until we get confirmation from CDash tomorrow.

**Comment by bartlettroscoe** [comment]
As shown in the below table, these tests have been disabled for 17 days in this build.  Therefore, I will now add the "Disabled Tests" label and remove the entries for this issue from our TrilinosATDMStatus/*.csv file.

<details>

<summary><b>Missing tests for issue #6020 as of testing day 2019-11-03</b></summary>

<h3>Tests with issue trackers Missing</h3>
<table style="width:100%" boarder="1">

<tr>
<th>Site</th>
<th>Build Name</th>
<th>Test Name</th>
<th>Status</th>
<th>Details</th>
<th>Consec­utive Missing Days</th>
<th>Non-pass Last 30 Days</th>
<th>Pass Last 30 Days</th>
<th>Issue Tracker</th>
</tr>

<tr>
<td align="left">ride</td>
<td align="left"><a href="https://testing.sandia.gov/cdash/index.php?project=Trilinos&amp;begin=2019-10-05&amp;end=2019-11-03&amp;filtercombine=and&amp;filtercombine=&amp;filtercount=2&amp;showfilters=1&amp;filtercombine=and&amp;field1=buildname&amp;compare1=61&amp;value1=Trilinos-atdm-white-ride-gnu-7.2.0-openmp-debug&amp;field2=site&amp;compare2=61&amp;value2=ride">Trilinos-atdm-white-ride-gnu-7.2.0-openmp-debug</a></td>
<td align="left">Intrepid2_­unit-test_­Projection_­Serial_­Test_­Convergence_­TET_­MPI_­1</td>
<td align="left"><font color="gray">Missing</font></td>
<td align="left">Missing</td>
<td align="right"><a href="https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&amp;begin=2019-10-05&amp;end=2019-11-03&amp;filtercombine=and&amp;filtercombine=&amp;filtercount=3&amp;showfilters=1&amp;filtercombine=and&amp;field1=buildname&amp;compare1=61&amp;value1=Trilinos-atdm-white-ride-gnu-7.2.0-openmp-debug&amp;field2=testname&amp;compare2=61&amp;value2=Intrepid2_unit-test_Projection_Serial_Test_Convergence_TET_MPI_1&amp;field3=site&amp;compare3=61&amp;value3=ride"><font color="gray">17</font></a></td>
<td align="right"><a href="https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&amp;begin=2019-10-05&amp;end=2019-11-03&amp;filtercombine=and&amp;filtercombine=&amp;filtercount=3&amp;showfilters=1&amp;filtercombine=and&amp;field1=buildname&amp;compare1=61&amp;value1=Trilinos-atdm-white-ride-gnu-7.2.0-openmp-debug&amp;field2=testname&amp;compare2=61&amp;value2=Intrepid2_unit-test_Projection_Serial_Test_Convergence_TET_MPI_1&amp;field3=site&amp;compare3=61&amp;value3=ride"><font color="red">13</font></a></td>
<td align="right"><a href="https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&amp;begin=2019-10-05&amp;end=2019-11-03&amp;filtercombine=and&amp;filtercombine=&amp;filtercount=3&amp;showfilters=1&amp;filtercombine=and&amp;field1=buildname&amp;compare1=61&amp;value1=Trilinos-atdm-white-ride-gnu-7.2.0-openmp-debug&amp;field2=testname&amp;compare2=61&amp;value2=Intrepid2_unit-test_Projection_Serial_Test_Convergence_TET_MPI_1&amp;field3=site&amp;compare3=61&amp;value3=ride"><font color="green">0</font></a></td>
<td align="right"><a href="https://github.com/trilinos/Trilinos/issues/6020">#6020</a></td>
</tr>

<tr>
<td align="left">ride</td>
<td align="left"><a href="https://testing.sandia.gov/cdash/index.php?project=Trilinos&amp;begin=2019-10-05&amp;end=2019-11-03&amp;filtercombine=and&amp;filtercombine=&amp;filtercount=2&amp;showfilters=1&amp;filtercombine=and&amp;field1=buildname&amp;compare1=61&amp;value1=Trilinos-atdm-white-ride-gnu-7.2.0-openmp-debug&amp;field2=site&amp;compare2=61&amp;value2=ride">Trilinos-atdm-white-ride-gnu-7.2.0-openmp-debug</a></td>
<td align="left">Intrepid2_­unit-test_­Projection_­Serial_­Test_­InterpolationProjection_­HEX_­MPI_­1</td>
<td align="left"><font color="gray">Missing</font></td>
<td align="left">Missing</td>
<td align="right"><a href="https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&amp;begin=2019-10-05&amp;end=2019-11-03&amp;filtercombine=and&amp;filtercombine=&amp;filtercount=3&amp;showfilters=1&amp;filtercombine=and&amp;field1=buildname&amp;compare1=61&amp;value1=Trilinos-atdm-white-ride-gnu-7.2.0-openmp-debug&amp;field2=testname&amp;compare2=61&amp;value2=Intrepid2_unit-test_Projection_Serial_Test_InterpolationProjection_HEX_MPI_1&amp;field3=site&amp;compare3=61&amp;value3=ride"><font color="gray">17</font></a></td>
<td align="right"><a href="https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&amp;begin=2019-10-05&amp;end=2019-11-03&amp;filtercombine=and&amp;filtercombine=&amp;filtercount=3&amp;showfilters=1&amp;filtercombine=and&amp;field1=buildname&amp;compare1=61&amp;value1=Trilinos-atdm-white-ride-gnu-7.2.0-openmp-debug&amp;field2=testname&amp;compare2=61&amp;value2=Intrepid2_unit-test_Projection_Serial_Test_InterpolationProjection_HEX_MPI_1&amp;field3=site&amp;compare3=61&amp;value3=ride"><font color="red">11</font></a></td>
<td align="right"><a href="https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&amp;begin=2019-10-05&amp;end=2019-11-03&amp;filtercombine=and&amp;filtercombine=&amp;filtercount=3&amp;showfilters=1&amp;filtercombine=and&amp;field1=buildname&amp;compare1=61&amp;value1=Trilinos-atdm-white-ride-gnu-7.2.0-openmp-debug&amp;field2=testname&amp;compare2=61&amp;value2=Intrepid2_unit-test_Projection_Serial_Test_InterpolationProjection_HEX_MPI_1&amp;field3=site&amp;compare3=61&amp;value3=ride"><font color="green">2</font></a></td>
<td align="right"><a href="https://github.com/trilinos/Trilinos/issues/6020">#6020</a></td>
</tr>

</table>



</details>

**Comment by bartlettroscoe** [comment]
I removed our tracking of these tests with the TrilinosATDMStatus commit:

```
b347ba4 "Remove disabled tests Intrepid2 (trilinos/Trilinos#6020)"
Author: Roscoe A. Bartlett <rabartl@sandia.gov>
Date:   Tue Nov 5 07:02:29 2019 -0700 (13 minutes ago)

M       promotedAtdmTrilinosTestsWithIssueTrackers.csv
```

**Comment by bartlettroscoe** [comment]
@trilinos/intrepid2, if there is no desire to fix these tests so they don't timeout in these builds, then we should just close this issue.

**Comment by mperego** [comment]
Yeah, no desire to avoid these test to time out on those builds. Closing.
