### ISSUE TITLE
Seacas/stk: adding non-double attribute fields leads to garbage numbers in the exodus file?

### ISSUE THREAD

**Issue by bartgol** [trilinos/Trilinos#6030]
## Question
@trilinos/\<SEACAS\>
@trilinos/\<stk\>

I'm not sure if this is a bug, or an intended behavior, so I'll start this as a question. My question stems from #5371  (which I'm re-closing).

In that issue I was discussing how to export with stk_io a field that is not transient. I was suggested to use "attribute" fields. I tried, and indeed the field is written in the exodus file (even though Paraview does not, unfortunately, display attribute fields...unless I'm not looking in the right place?).

However, inspecting the exodus file (via ncdump or exotxt), I noticed a bunch of e-314 numbers, while my field was storing ints. I digged, and noticed that ultimately, `DatabaseIO::write_attribute_field` gets called, and it _always_ reinterpret the data as `double`. Isn't this dangerous? My actual data contains 32bits int, so this reinterpret cast is very wrong (it will even start reading garbage once it is 'half way through').

I was wondering if there is a way to export non-double attribute fields via stk into an exodus file or not. The stk interface does not enforce attribute fields to have double data type, so it makes me feel like ints are fine, but eventually it seems like they are not.

Is there a different set of calls to do? Is this not supported? If so, though, I'd like stk to error out when one tries to add a non-double attribute field...

For completeness, this is how I add the attribute field (copied from the issue linked above):
``
auto& my_mesh_field = ...;
stk::io::OutputVariableParams vars(my_mesh_field.name());
mesh_data->add_attribute_field(outputFileIdx, my_mesh_field, vars);
```

**Comment by gsjaardema** [comment]
I will fix the `write_attribute_field` function to query the type of the `Ioss::Field` being input/output and correctly handle integer data similar to how it is done in the transient field output.  Similarly to the transient fields, currently exodus had only float/double output for attributes and (should) convert integers to/from float/double for non-real fields.

This is currently not done in the attribute code and is an oversight which I will fix. 

Another option for storing integer non-transient data is to use a `map`, but again this will not be visible to ParaView and has some other limitations.  As long as the integers are less than 2^53, then there is no loss of data converting to/from a double.

**Comment by gsjaardema** [comment]
This should now be fixed via https://github.com/trilinos/Trilinos/pull/6092
