### ISSUE TITLE
Belos:  GMRES communication avoiding

### ISSUE THREAD

**Issue by nuraiman** [trilinos/Trilinos#6036]
## Enhancement
@trilinos/\<Belos\>

I have seen that CG communication avoiding is currently available in Belos.
Could you please release also the GMRES communication avoiding please?

Kind regards,
Nur

**Comment by jhux2** [comment]
@trilinos/belos @iyamazaki @srajama1

**Comment by mhoemmen** [comment]
It's released already.  @iyamazaki can give you more details.  See `packages/belos/tpetra/src/solvers/`.

**Comment by lucbv** [comment]
@mhoemmen I think that @nuraiman wants to call the communication avoiding GMRES using the xml interface. Is that already possible?

**Comment by mhoemmen** [comment]
It should be, though you might have to call the Belos registration functions in your own application.

**Comment by iyamazaki** [comment]
@mhoemmen is right. These solvers (e.g., single-reduce, communication-avoiding, and pipelined GMRES) are not registered by default. So you need to register. We don't have a simple example, but there are testers in the packages/belos/tpetra/test/Native directory. Please let me know if I can help, @nuraiman.

**Comment by mhoemmen** [comment]
@jennloe @csiefer2 @jhux2
