### ISSUE TITLE
Tribits/Framework: Allow automatic global configuration changes

### ISSUE THREAD

**Issue by brian-kelley** [trilinos/Trilinos#6041]
## Enhancement
@trilinos/framework 

I'm trying to make a CMake change to Xpetra and its downstream packages (Galeri, Ifpack2, MueLu, ShyLU_DD, Zoltan2). For a long time in Xpetra, if Tpetra GO=int was disabled and Epetra GO=int was enabled, Xpetra's configuration would error out because no single GO type could be used in both E & Tpetra. But with Tpetra deprecated OFF, this situation is the default: Epetra/Tpetra both enabled because they're PT, Tpetra GO=long long only, and Epetra GO=int enabled.

In order to make this default configuration work, we want to disable Xpetra's Epetra support in this case. Any packages using Epetra through Xpetra must turn that off, and just use Xpetra/Tpetra. The pure Epetra stack (ML, Aztec, etc) shouldn't be affected.

The problem is, this case (currently) can only be detected inside Xpetra's local package configuration. By then, the package enables have been decided and setting ``Xpetra_ENABLE_Epetra=OFF`` has no effect on downstream packages. But this logic can't go in cmake/RepositoryDependenciesSetup.cmake either, because the default values for variables like ``Tpetra_INST_INT_INT`` and ``Xpetra_ENABLE_Epetra`` haven't been assigned yet. Basically, in the [TriBITS configuration sequence](https://tribits.org/doc/TribitsDevelopersGuide.html#full-tribits-project-configuration), I want to be able to place custom global logic somewhere between step 10 (package dependency resolution) and step 14 (local configuration of each package). This logic must be able to set ``Xpetra_ENABLE_Epetra=OFF`` globally and have this be persistent in the cache, as if the user had set it explicitly.

Edit: I should add that we only want to disable Xpetra-Epetra if Epetra was implicitly enabled, which I can get easily from ``Epetra IN_LIST ${${PROJECT_NAME}_ENABLED_PACKAGES_LIST}``. If Epetra was enabled explicitly then we will still error out.

**Comment by jhux2** [comment]
@bartlettroscoe

**Comment by bartlettroscoe** [comment]
@brian-kelley, if this is a short-term situation, could we just ask users to work around this by explicitly setting the right variables?  For our important customers like Sierra and ATDM, that should be easy.  But if this is a long-term situation, then we should find a more automated way to get this to work.

In the latter case, I think we should do back to to post-modifying the enables in the `CMakeLists.txt` vars.  I think the trick is to set `<Package>_ENABLE_Epetra` in the base project scope instead of as cache vars.  (The variable scoping rules in CMake are very confusing.)

Can you post a PR with your initial attempt to set cache vars in `packages/xpetra/CMakeLists.txt`?  I believe that I/we can make that work.  (And we can add some documentation about how to do non-standard stuff like this if one really needs to do this.)

**Comment by brian-kelley** [comment]
@bartlettroscoe Oh, so I can just do ``SET (Xpetra_ENABLE_Epetra OFF PARENT_SCOPE)`` in xpetra's CMakeLists.txt?

Anyway, I don't know how permanent this will be but it could easily be several months. The ideal solution would be to use Epetra64 by default to match Tpetra's default GO=long long, but there are still many test failures caused by Epetra64 (although, @csiefer2 made progress recently by getting that to compile at least).

**Comment by bartlettroscoe** [comment]
@brian-kelley asked:

> Oh, so I can just do `SET (Xpetra_ENABLE_Epetra OFF PARENT_SCOPE)` in xpetra's CMakeLists.txt?

Yes.  If you run that in the base `packages/xpetra/CMakeLists.txt` file, that will likely do what you want as that is one level below. (I don't think you want to override this in the cache as that was not the user's input.  (Either way, someone will be confused but if you print out your logic in the cmake STDOUT, it can be followed.)  (Likely we need to explain better how the enable/disable logic works in TriBITS and why it works the way it does.  This is all written in CMake so we have to live with CMake language quirks.)

**Comment by brian-kelley** [comment]
@bartlettroscoe Yep, that worked! It doesn't even seem too hacky now. PR #6045 has these changes.

**Comment by bartlettroscoe** [comment]
> Yep, that worked!

Great!  CMake is so strange.  Is it worth documenting this use case?  One has to be careful what vars one set's because some will have the impact you want and setting other vars will not.  CMake has no encapsulation mechanisms so this can get tricky.

**Comment by brian-kelley** [comment]
@bartlettroscoe When you say use case, do you mean this particular Trilinos configuration, or this way of disabling a feature at a later stage of the configuration?

If it's the first one, I think it'll be OK because the impacted Trilinos developers understand it, and application developers know whether they want to use the Epetra or Tpetra stack, so they'll explicitly enable one or the other (or both, and then see that they'll need to enable Tpetra_INST_INT_INT also).

if it's the second one, yes it should probably be documented in some way (although I don't know where). Even though this technique should be a last resort it's still useful.

**Comment by bartlettroscoe** [comment]
@brian-kelley 

> When you say use case, do you mean this particular Trilinos configuration, or this way of disabling a feature at a later stage of the configuration?

The latter.

> if it's the second one, yes it should probably be documented in some way (although I don't know where). Even though this technique should be a last resort it's still useful.

If I would to add some documentation for this use case in the document:

* https://tribits.org/doc/TribitsDevelopersGuide.html

would you be willing to review it?

**Comment by brian-kelley** [comment]
@bartlettroscoe Ah, if I had read this cover to cover the section for ``DUAL_SCOPE_SET`` would have given me everything I needed. But I can add a how-to called "Changing downstream feature enables during package configuration". I will say that it's preferable to change X_ENABLE_Y in the RepositoryDependenciesSetup.cmake instead, and there's already a how-to for that.

**Comment by bartlettroscoe** [comment]
@brian-kelley,

>  I can add a how-to called "Changing downstream feature enables during package configuration".

Wow, if you want to take a short at that, that would be great :-)

Just fork the TriBITS GitHub repo:

* https://github.com/TriBITSPub/TriBITS

and create a branch in your repo with your changes to the file:

* TriBITS/tribits/doc/developers_guide/TribitsDevelopersGuide.rst

(written in reStructuredText) and then post a PR to the TriBITS GitHub repo, I will review.

> I will say that it's preferable to change X_ENABLE_Y in the RepositoryDependenciesSetup.cmake instead, and there's already a how-to for that.

That current section [How to check for and tweak TriBITS "ENABLE" cache variables](https://tribits.org/doc/TribitsDevelopersGuide.html#how-to-check-for-and-tweak-tribits-enable-cache-variables) really describes a different use case and allows you to do things you can't do once package configuration has started.  For example, the logic currently implemented in:

* https://github.com/trilinos/Trilinos/blob/719334d934e2f71c5f65c5d30d1eb155496b5d91/cmake/RepositoryDependenciesSetup.cmake

can't be done once you start package configuration.  That allows you to actually disable entire packages (which you can't do once package configuration has started).

Therefore, the new section "How to change downstream feature enables during package configuration" would described a different use case; the one related to GitHub issue.

**Comment by brian-kelley** [comment]
@bartlettroscoe Here's the PR: https://github.com/TriBITSPub/TriBITS/pull/296

**Comment by bartlettroscoe** [comment]
Just merged TriBITSPub/TriBITS#296.

Thanks @brian-kelley!
