### ISSUE TITLE
ROL Vector, StdVector, and Eigen3Vector API consistency features request

### ISSUE THREAD

**Issue by eleaver** [trilinos/Trilinos#6053]
@dridzal ROL features request. 
I use ROL::StdVector and ROL::Eigen3Vector in my own application, and am seeking a common interface between them and with their ROL::Vector base class to the extent practical. The first 7 of these suggestions are straightforward. The last (number 8) has implications. 9 and 10 mention an example implementation and test results. 1 and 10 might be considered bugs.

Discussion is against develop affd384f7643ba1dd9d11b4ddf04c0274a85d379 of 5 Oct 2019

1. Most important, might I suggest we remove ROL::Eigen3Vector's redundant dim_ element?
   ROL::Eigen3Vector::dimension() can simply return static_cast<int>(vec_->size()).
   This is what ROL::StdVector does, and here dim_ prevents such things as 
   Eigen3Vector::getVector()->resize()
   or *(getVector()) = (some other Eigen::Matrix<Real,Eigen::Dynamic,1>) of
   different size, because dim_ will not be updated and dimension() will become invalid.

2. For consistency, might ROL::StdVector inherit ROL::ElementwiseVector rather than ROL_Vector directly? This is what ROL::Eigen3Vector does, and has some advantages:
   a. At present StdVector::dot(const Vector<Real> x) throws an invalid_cast runtime exception
      if x is not itself a StdVector. ElementwiseVector::dot(const Vector<Real> x) does a right
      thing, albeit at expense of a memory allocation.
   b. Same for StdVector::axpy(const Real alpha, const Vector<Real> &x)
   c. StdVector does not have a set() method, but ElementwiseVector does.
   If StdVector inherited ElementwiseVector, the exceptional behavior of StdVector::dot() and axpy() could be avoided by making them simple overloads of their ElementwiseVector counterparts, e.g.
```
     virtual Real dot( const StdVector<Real> &x ) const {
        ROL_TEST_FOR_EXCEPTION( dimension() != x.dimension(),
                              std::invalid_argument,
                              "Error: Vectors must have the same dimension." );
        Real val = 0;
        for (uint i=0; i<std_vec_->size(); ++i) {
           val += (*std_vec_)[i]*x[i];
        }
        return val;
     }
```
3. For consistency with StdVector, might Eigen3Vector be granted a proper initialization constructor, that is
   Eigen3Vector( const int dim=0, const Real val=0.0)?
   
   Of course Eigen3Vector( const int dim, const int val ) will also be necessary unless we can
   eliminate Eigen3Vector( int dim, bool zeroOut=false ), which would simplify things without loss of functionality.
   However, Eigen3Vector(int, bool) is already in master; deprecating it's use might take some time.
   Meanwhile, Eigen3Vector(int,Real) may be implemented as long as Eigen3Vector(int,int) is as well.
   
4. Might StdVector(const int dim, const Element val=0.0) be changed to StdVector(const int dim=0, const Element val=0.0)?

5. For consistency with Eigen3Vector, might StdVector be granted an element access operator()(int)?
   For consistency with ComplexStdVector and StdArray, might Eigen3Vector and StdVector both be given
   operator[](int) in addition, or instead?

6. Minus methods. To ROL::ElementwiseVector might we add
   method void minus(const Vector<Real> &x)?
   It would be more efficient than axpy(-1,x), and more readable.
   The requisite template<class Real>  class Minus : public BinaryFunction<Real> 
   may easily be added to elementwise/ROL_BinaryFunctions.hpp.
   (This might have already been considered and rejected.)

7. Convenience copy template function.
   This is hardly critical, as users such as myself could place such a
   template method in any local utilities header. But we might wish a
   standard syntax in a standard location, such as ROL_Vector.hpp:
```   
   template<class V>
   ROL::Ptr<V> copy(const V& v){
     auto newVec = ROL::makePtr<V>(v.dimension());
     newVec->set(v);
     return newVec;
   }
```
   should work for any class V that implements dimension() and set().
   
   Alternatively, a similar copy() method might be added to individual subclasses, e.g.
   ```
   ROL::Ptr<Eigen3Vector> copy() const {
    auto newVec = ROL::makePtr<Eigen3Vector>(dimension());
    *(newVec->vec_) = *vec_;
    return newVec;
  }
```
  The key is to return a pointer to a subclass object, not the ROL::Vector base.

8. Questions, no answers. I've considered how base class Rol::Vector() might also be granted optional element access operator()(int) and/or operator[](int), and not come to a good solution. Although element access operators were likely omitted from the present ROL::Vector interface by intent, their absence leads to myriad subclass methods that downcast a Vector parameter to their specific type rather than overloading it. This could be avoided if the base class had access operators that allowed default implementations.

As an example, StdVector::applyBinary(const BinaryFunction<Real>& f, const Vector<Real>& x) will throw bad_cast at runtime if x itself is not a StdVector.
   
Such behavior could be avoided if ROL::Vector interface suggested access operator()(int) and provided default implementations of applyUnary(), applyBinary(), etc. in terms of those operators. Vector subclasses could then overload for their specific vector type as desired, without a dynamic downcast.

The problem with Vector::operator()(int) is it's return type. If template <class Real> class Vector could be generalized to something like template class<Real, class Element=Real> Vector like StdVector, we could specify things like Element& Vector::operator[](int) and be fine: subclasses like ComplexStdVector and PartitionVector and ReiszVector could inherit Vector and overload their access operators to return what they like.

But for Vector, typename Real is pretty well restricted to scalar types, and I've yet to figure out how to generalize Vector's template parameters to specify an Element type that might be something different. Has anyone else tried?

Additionally, these element access operators might not be practical for all ROL vector types. For instance, it's unclear just what non-const Real& RieszPrimalVector::operator()(int i) should do -- return v_->operator()(i) is a possibility much in the spirit of RieszPrimalVector::applyXnary(), setScalar(), etc., as none of these update their corresponding dual_ values either. But it isn't clear to me why they *shouldn't* effect such an update. These setter methods do not appear in the test_07.cpp unit tests, and when I added one to Vector::checkVector() it failed -- see 10 below. Perhaps someone can clarify my misunderstanding?

Attached are example ROL::Vector, ROL::StdVector, and ROL::Eigen3Vector implementations that effect these suggestions, an optional squaredNorm() method, and corresponding test files:

9. In ROL_Vector.hpp are two preprocessor macros:
   a. #define ROL_TRAP_UNIMPLEMENTED_VECTOR_METHOD
       Causes unimplemented basis() and dimension() calls to throw exceptions rather than silently 
       returning a wrong answer.
   b. #define ROL_VECTOR_ACCESS_OPERATOR
        Implements dummy virtual Real operator()(int), and minus(), but eschews operator[](int) as
        it would interfere with PartitionedVector and ComplexStdVector.

10. To ROL::Vector::checkVector() I've added an illustrative test:
```
// Consistency of setScalar and dot
if(x.norm() > 0.0){
    v->setScalar(a);
    Real vsquaredNorm = v->dot(*v);
    Real vdim = static_cast<Real>(v->dimension());
    vCheck.push_back( std::abs(vsquaredNorm - a*a*vdim) / (a*a*vdim) );
    *pStream << std::setw(width) << std::left
             << "Consistency of setScalar and dot. Consistency error: "
             << " " << vCheck.back() << "\n";
}
```
...upon which the following rol/test/vector tests fail:
	  3 - ROL_test_vector_ScaledStdVectorInterface_MPI_1 (Failed)
	  5 - ROL_test_vector_RieszVectorInterface_MPI_1 (Failed)
	  7 - ROL_test_vector_StdArrayInterface_MPI_1 (Failed)

Notes on consistency check:
   3 - It is not clear (to me) what ScaledStdVector::dot() does; it appears incomplete.
   5 - As previously discussed, RieszVector::setScalar() et al. do not update it's dual_ vector.
   7 - About StdArray I'm clueless, save to note it's pool_ptr is never initialized.

Notes on ComplexStdVector:
   1. The return downcasts inside complex_cast should almost certainly be dynamic_casts, rather than static.
   2. set(), plus(), axpy(), dot() methods might benefit from a dimension() check on their input parameter.

Thanks!

[RolExampleVectors1.zip](https://github.com/trilinos/Trilinos/files/3695562/RolExampleVectors1.zip)

**Comment by dridzal** [comment]
Thanks @eleaver .  There are several good suggestions here.  Since many are also related to Eigen3Vector and Elementwise, @gregvw should chime in.

**Comment by gregvw** [comment]
@eleaver, thank you for testing so many of ROL's components and sharing your detailed input. 

1. Yes, I think removing dim_ is a fine idea.

2. StdVector predates ElementwiseVector and was the first concrete Vector class implemented in ROL. The reason we haven't refactored it yet to use Elementwise is that we wanted a fairly simple "tutorial" class to illustrate to developers how to create a new Vector class. There are some other classes in src/vector that do inherit from ElementwiseVector.

3. We can add these constructors

4. Default dim=0 is fine

5. We could add a subscript operator to StdVector as we have to ROL::TeuchosVector. I think the reason StdVector has not traditionally implemented element access was to highlight the idea that ROL's algorithms do not operate on individual elements, however, I do agree that it makes life easier on the application side to implement element access in the concrete Vector classes. 

6.  Minus is handy, but we have tried to corral the over-proliferation of Vector methods. Eigen does even better by using expression templates so the minus operator can be used directly without incurring overhead. Would having a Vector::minus be better than getting the underlying Eigen::Vector and using the operators?

7. I've done this in other experimental implementations of ROL::Vector and find it useful. Again, I'm reluctant to make changes to the Vector interface unless there is a substantial need. 

8-9. I should mention that we have an experimental development branch where concrete classes
need not inherit from ROL::Vector, but only support its interface. All of ROL's components (_e.g._ Objective, Constraint, Step...) are templated on Vector types rather than the Real type. This obviates a lot of the issues you've brought up.

10. ComplexStdVector is admittedly a work in progress. I will look into that and the failing vector checks you mentioned. Thanks again!

@dridzal, @dpkouri, do you have any thoughts on any of these items?
