### ISSUE TITLE
Tpetra, Teuchos: Tpetra::MultiVector::get1dView() on subvector

### ISSUE THREAD

**Issue by ecoon** [trilinos/Trilinos#6058]
## Bug Report
@trilinos/tpetra @trilinos/teuchos @trilinos/kokkos

### Description
Calling MultiVector::get1dView() on a MultiVector constructed via MultiVector::offsetView() gives a view of the incorrect size.  

Pseudo-code:

```
Map map(...);
Map submap( ... contiguous subset of map's local IDs, starting at 0 ...);
MultiVector vec(map, N);
MultiVector subvec = vec.offsetView(submap, 0); // non-owning vector with view into vec

auto subvec_2d_view = subvec.getLocalViewHost();
assert(subvec_2d_view.extent(0) == submap.getNodeNumElements()); // good!

auto subvec_1d_view = subvec.get1dView();
// assert( subvec_1d_view.size() == submap.getNodeNumElements() * N ); // fails!
assert( subvec_1d_view.size() == map.getNodeNumElements() * N); // passes, wrong!
```

The documentation of [offsetView()](https://trilinos.org/docs/dev/packages/tpetra/doc/html/classTpetra_1_1MultiVector.html#a0975abcfe663b046489c313d367bd64f) mentions that it assumes that "This method assumes that the local indices of X1 and X2 are each contiguous, and that the local indices of X2 follow those of X1."  This, and a strided layout, should be the requirements of `get1dView()` to work, so I would expect this to be valid code.

The issue seems to be that the Tpetra [code calls Kokkos::Compat::persistingView()](https://github.com/trilinos/Trilinos/blob/master/packages/tpetra/core/src/Tpetra_MultiVector_def.hpp#L3697) which [uses span()](https://github.com/trilinos/Trilinos/blob/master/packages/teuchos/kokkoscompat/src/KokkosCompat_View.hpp#L189) to get its extent, which, according to the [Kokkos docs](https://github.com/kokkos/kokkos/wiki/Kokkos::View), "can be larger than the product of extents due to padding" (and in this case is).

So I'm not sure if the inconsistency is that Tpetra can't use persistentView() in this case, or if Teuchos's persistentView() shouldn't use span() here, but something is wrong :)

### Steps to Reproduce
1. SHA1:  a5f7683012ec5567679a5d065f91dcbe553c24a8 is what I have tested on, which is a bit old, but having inspected the source it doesn't appear this should have changed in today's master.
2. Configure, build with Tpetra (doesn't matter how).
3. Below is a unit test from Amanzi -- apologies but there are a few typedefs and functions included here, but it should be obvious how to make this a compilable test for Trilinos.

```
TEST(OFFSET_VIEW_1D_VIEW) {
  // having some trouble with communication -- lets make sure we understand
  // how to use tpetra
  auto comm = getDefaultComm();

  int size = comm->getSize(); CHECK_EQUAL(2,size);
  int rank = comm->getRank();
  int n_vecs = 5;

  Map_ptr_type owned_map, ghost_map;
  if (rank == 0) {
    std::vector<int> gids_owned{0,1};
    owned_map = Teuchos::rcp(new Map_type(4, gids_owned.data(), 2, 0, comm));

    std::vector<int> gids_used{0,1,2};
    ghost_map = Teuchos::rcp(new Map_type(6, gids_used.data(), 3, 0, comm));
  } else {
    std::vector<int> gids_owned{2,3};
    owned_map = Teuchos::rcp(new Map_type(4, gids_owned.data(), 2, 0, comm));

    std::vector<int> gids_used{2,3,1};
    ghost_map = Teuchos::rcp(new Map_type(6, gids_used.data(), 3, 0, comm));
  }

  auto ghost = Teuchos::rcp(new MultiVector_type(ghost_map, n_vecs));
  auto owned = ghost->offsetViewNonConst(owned_map, 0);

  CHECK_EQUAL(3, ghost->getLocalLength());
  CHECK_EQUAL(2, owned->getLocalLength());
  CHECK_EQUAL(n_vecs, ghost->getNumVectors());
  CHECK_EQUAL(n_vecs, owned->getNumVectors());

  CHECK_EQUAL(3*n_vecs, ghost->get1dView().size());
  CHECK_EQUAL(2*n_vecs, owned->get1dView().size()); // this fails
  
  CHECK_EQUAL(3, ghost->getLocalViewHost().extent(0));
  CHECK_EQUAL(2, owned->getLocalViewHost().extent(0)); // this passes!
}
```

**Comment by mhoemmen** [comment]
@ecoon wrote:
```c++
 CHECK_EQUAL(3*n_vecs, ghost->get1dView().size());
 CHECK_EQUAL(2*n_vecs, owned->get1dView().size()); // this fails
```
Right; it is allowed to fail, and this has nothing to do with padding.  `get1dView` returns a one-dimensional `Teuchos::ArrayRCP` which views all of the MultiVector's data, across all the columns.  In this case, the MultiVector `owned` is itself a subview of the MultiVector `ghosted`.  Thus, `owned->get1dView()` is allowed to equal (have the same pointer and size) as `ghosted->get1dView()`.

The proper way to use `get1dView` and `get1dViewNonConst` is with `isConstantStride()` and `getStride()`:
```c++
if (owned->isConstantStride()) {
  CHECK_EQUAL(owned->get1dView().size(), owned->getStride() * owned->getNumVectors());
}
if (ghost->isConstantStride()) {
  CHECK_EQUAL(ghost->get1dView().size(), ghost->getStride() * ghost->getNumVectors());
}
```

**Comment by ecoon** [comment]
“get1dView returns a one-dimensional Teuchos::ArrayRCP which views all of the MultiVector’s data, across all the columns.”  

That's not true.  `get1dView()` returns a one-dimensional Teuchos::ArrayRCP which views all of the **parent MultiVector's** data, **not** this's data, across all columns. 

Equivalently, why should `owned->getLocalHostView()` return a view of ONLY owned’s data, but `owned->get1dView()` return a view of ALL originally constructed data?

**Comment by mhoemmen** [comment]
@ecoon wrote:
> `get1dView()` currently returns a one-dimensional Teuchos::ArrayRCP which views all of the **parent** MultiVector's data, not this's data, across all the **parent vector's** columns, not this's columns.

Ok, right, that's what I meant to write ;-)  This is correct and expected behavior.

> I'm ok if the answer is "this should actually error because it isn't possible to construct the necessary non-contiguous, non-strided 1d view." But then the bug is it should error.

There's no bug.  You're supposed to interpret the 1-D array as 2-D data using `getStride()`.

> Equivalently, why should `owned->getLocalHostView()` return a view of ONLY owned’s data, but `owned->get1dView()` return a view of ALL originally constructed data?

Because `getLocalViewHost` returns a 2-D Kokkos::View that encodes the correct stride.

**Comment by ecoon** [comment]
@mhoemmen 

Well, then at the least this should be in the documentation.  Currently the documentation is incorrect, as it says:  

```
Const persisting (1-D) view of this multivector's local values.

This method assumes that the columns of the multivector are stored contiguously. If not, this method throws std::runtime_error.

Definition at line 3678 of file Tpetra_MultiVector_def.hpp.
```

When actually it returns a "Const persisting (1-D) view of this multivector's parent multivector's values (if it was constructed as a subvector) or of this multivector's values (otherwise)."

**Comment by ecoon** [comment]
@mhoemmen 

I still can't believe this is intentional, that calling a subvector's get1dView() is the same as calling the parent's get1dView().  I’ve attached an image that I’ll refer to that describes what is happening here.  Please correct me if I misunderstand.

![image](https://user-images.githubusercontent.com/5126139/66534876-a0efef00-eae5-11e9-8ea2-f72be0476ba2.png)

First, offsetView() allows the creation of sub-vectors that look like S in the image in that they have a subset of V’s rows.  Once I have created that subvector, however, there is nothing special about it.  It _is a_ MultiVector.  It has a sense of its data, defined by its view.  Data entries outside of the dashed box are not a part of S’s values.  If, for instance, S.normInf() returned 17, I would explode.  It had better return 15.

I would expect that no part of S's public interface allowed access to entries in V that are not in S.  For instance, imagine someone doing the following:

```
  auto S_view = S.get1dViewNonConst();
  S_view[5] = 100;
```

Now, we have, in a perfectly “legal” way, changed V without actually affecting S in measurable way, despite doing it through S’s interface.  S.normInf() still returns 15, but V.normInf() returns 100, despite that entry not being in the subset of rows we gave S access to.  **Through this interface, S has access to all of V, not just the rows we gave S access to.**

Currently S.get1dView() returns the same view as V.get1dView().  Is it not self-evident that this is wrong?  **S’s interface should not allow access to values outside of S’s sub-space.**

Now, I recognize that providing a 1D view of S’s actual values is not currently possible in Kokkos.  What I would expect to get is a view that acted like the array shown in the image.  Currently, this view cannot be constructed as a subview, because Kokkos does not currently allow subviews of arbitrary indices (as this is neither a contiguous subset nor a strided subset), so it would require a copy.  So I would really expect S.get1dView() to error.

**Comment by mhoemmen** [comment]
I'm not in charge of Tpetra any more.  You're welcome to try to convince @kddevin , who is in charge of Tpetra, that this is an issue.  I would prefer that Tpetra deprecate and remove all of the `Teuchos::ArrayRCP` methods.  If you have suggestions for documentation changes, you are welcome to submit a pull request.

`Tpetra::MultiVector::get1dView` behaves very much like `Kokkos::View::data`.  It returns a pointer to the local data.  Just like with `Kokkos::View`, if the user gets a pointer to the data, then the user is responsible for interpreting the pointer with the appropriate layout and stride(s).  If I use the pointer to access data outside of its View, the result is undefined behavior.

**Comment by ecoon** [comment]
Fair enough.  data() would actually have been a better name for this method in my opinion, because it is a common enough name that it clues the user in that "you're just getting the raw data, break the container if you so desire..." (in the same way of std::vector::data, etc).  My issue with this as named is that S conceptually has a self-consistent 1d view, and it isn't this.  As always, thanks for your time.

**Comment by mhoemmen** [comment]
I would love to remove the method -- it's superfluous and confusing.  I would recommend only using the methods that give access using `Kokkos::View`.  Better yet, consider the `withLocalAccess` interface.
