### ISSUE TITLE
Tpetra::Crs{Graph,Matrix}: Either remove getGlobalNumEntries & getGlobalMaxNumRowEntries, or make them global collectives

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#606]
@trilinos/tpetra 
@trilinos/amesos2 @trilinos/ifpack2 @trilinos/muelu @trilinos/xpetra @trilinos/zoltan2 

Tpetra::CrsGraph and Tpetra::CrsMatrix provide three methods, getGlobalNumDiags, getGlobalNumEntries, and getGlobalMaxNumRowEntries.  These methods do _not_ currently have collective semantics.  Thus, it must be correct to call them at any time (when the graph / matrix is fillComplete), on any process.  This implies that the graph / matrix must compute them via all-reduce at first fillComplete.  This increases set-up cost.

Most users don't need to know the global (over all MPI processes in the communicator) number of entries, or diagonal entries.  Some users might; for example, Amesos2 might want to know the global number of entries in order to prepare enough space to gather in the matrix for a direct solve.  However, those users can do the all-reduce themselves, and save and reuse its result as part of the "symbolic factorization" set-up phase.

Thus, I think it would be good to deprecate and remove these methods.  @csiefer2 talked about another option, namely to change the methods to have collective semantics that cache the value on first call and clear the cache at resumeFill (if the graph's structure can change).  Please explain which option you would prefer here.

Edit (21 Dec 2016): I changed the issue title, to make clear the consequences of a fix, and edited the text a bit to give affected packages a chance to offer feedback for their preferred solution.

**Comment by mhoemmen** [comment]
This is a "task," but if you take this one, please be sure to check downstream packages.  This is particularly important for Xpetra and MueLu.

**Comment by tawiesn** [comment]
Xpetra and MueLu definitely use getGlobalNumEntries (e.g. in some unit tests)

**Comment by mhoemmen** [comment]
> Xpetra and MueLu definitely use getGlobalNumEntries (e.g. in some unit tests)

  1. Could those unit tests replace that call with an all-reduce on getNodeNumEntries()?
  2. Could Xpetra change semantics of its getGlobalNumEntries() so that it's allowed to be collective?

Thanks Tobias!  I don't mean to make more work; I'm just prepping Tpetra issues for discussion with our new arrival next week.

**Comment by mhoemmen** [comment]
I really want to implement this.  The quickest solution would be the caching approach that @csiefer2 proposed.  In that approach, the first call of getGlobalNumDiags and getGlobalNumEntries would invoke a collective and cache the result.  Subsequent calls would return the cached result.

**Comment by jhux2** [comment]
> > Xpetra and MueLu definitely use getGlobalNumEntries (e.g. in some unit tests)
> > 
>     Could those unit tests replace that call with an all-reduce on getNodeNumEntries()?
>     Could Xpetra change semantics of its getGlobalNumEntries() so that it's allowed to be collective?
> 
> Thanks Tobias! I don't mean to make more work; I'm just prepping Tpetra issues for discussion with our new arrival next week.

@mhoemmen In addition to the tests, MueLu uses this for various statistics reporting, e.g., multigrid "operator complexity", and for various sanity checks.  We could do collectives ourselves, if that's the route you want to go.

> I really want to implement this. The quickest solution would be the caching approach that @csiefer2 proposed. In that approach, the first call of getGlobalNumDiags and getGlobalNumEntries would invoke a collective and cache the result. Subsequent calls would return the cached result.

I think this is a reasonable approach.

**Comment by mhoemmen** [comment]
@jhux2 wrote:
> We could do collectives ourselves, if that's the route you want to go.

I'm starting to favor the "change to collective semantics, and cache" approach.  In fact, I'm tempted just to _do_ it and see if anyone notices ;-)

**Comment by mhoemmen** [comment]
(Of course I would test everything downstream first.  The issue is that it's really hard to warn users about a change in _semantics_.  That's one reason why I was thinking of just getting rid of the methods in question.  On the other hand, I doubt most users would call these methods in a way that's not collective.)

**Comment by srajama1** [comment]
Is this really that big of a burden in setup costs ? It is one/two all reduce at the setup() time. May be this is a low hanging fruit ?

We could do the collective in Amesos2 as well. The cache approach has to be designed carefully. resumeFill() needs to do the collective and reset the values.

**Comment by mhoemmen** [comment]
@srajama1 wrote:
> resumeFill() needs to do the collective and reset the values.

Tpetra::CrsGraph does not currently allow structure changes after first fillComplete, so this would not be necessary.

**Comment by aprokop** [comment]
Is caching a different name for "lazy evaluation", or is it different?

**Comment by srajama1** [comment]
Modifying the structure is an important use case, that is coming up very quickly (ECP-Apps, Nalu).

As I understand, caching as described here is find it once and store it in a member variable.

**Comment by mhoemmen** [comment]
@aprokop wrote:
> Is caching a different name for "lazy evaluation", or is it different?

Same thing.

@srajama1 wrote:
> As I understand, caching as described here is find it once and store it in a member variable.

That's right.

@srajama1 wrote:
> Modifying the structure is an important use case, that is coming up very quickly (ECP-Apps, Nalu).

If we want to support structure modifications efficiently, I think it would pay to start fresh with a totally new graph class, then think about how to fit that class in.  Neither Epetra nor Tpetra designed their graph class for that use case, and the graph and matrix classes are full of hidden assumptions about the graph not changing after first fillComplete.  It's really hard to write unit tests that expose all those assumptions.

**Comment by mhoemmen** [comment]
Hm, there are a few cases where downstream packages use these functions in ways that may diverge across processes.  One example is in Xpetra's interface to sparse matrix-matrix addition, in xpetra/sup/Utils/Xpetra_MatrixMatrix.hpp, lines 1892-1930:

https://github.com/trilinos/Trilinos/blob/develop/packages/xpetra/sup/Utils/Xpetra_MatrixMatrix.hpp

One work-around would be for the code in question to invoke the method in a nondivergent way before divergence, in order to preload the cache.  That would let some code benefit from the change, without forcing everyone to pay for the all-reduce (which is the case now).

Currently, getGlobalMaxNumRowEntries requires its own all-reduce.  (See comments in Tpetra::CrsGraph::computeGlobalConstants for an explanation.)  It would be nice to get rid of that one all-reduce, which involves a rarely-used method with little benefit to applications.

**Comment by aprokop** [comment]
@mhoemmen I'm missing something. How's the Xpetra code you pointed to divergent?

**Comment by mhoemmen** [comment]
@aprokop wrote:
> @mhoemmen I'm missing something. How's the Xpetra code you pointed to divergent?

Oops, my bad ;-)  Actually it's not.  I could imagine some code that is, though.

**Comment by maherou** [comment]
The incremental change use case has been handled in a variety of ways over the years.  In most cases the rigorous and scalable approach has been to store rows that would change (which is often known ahead of time) as a separate matrix from rows that don't change, then write a lightweight RowMatrix interface adapter to logically present the combined matrix as a single operator.

For the single matrix approach, Epetra (and maybe Tpetra since it started as direct Epetra translation?) support insertion of new graph and matrix entries after calling fillcomplete,  _if_ the new entry does not change the communication requirements. Basically meaning that global column of the new entry was already part of the matrix in some other row.

While starting fresh might be the right answer, existing functionality should be carefully understood.

**Comment by mhoemmen** [comment]
#2630 covers `getNodeNumDiags`, `getGlobalNumDiags`, `isLowerTriangular`, and `isUpperTriangular`.  We decided in #2630 to preserve `getNodeMaxNumEntries` for now.

CrsGraph and CrsMatrix expertStaticFillComplete already have a `computeGlobalConstants` bypass.  #2565 is about adding a `computeLocalConstants` bypass for `getNodeNumDiags`, `getGlobalNumDiags`, `isLowerTriangular`, and `isUpperTriangular`.  #2630 is about deprecating and purging those methods.  Tpetra developers have decided to preserve `getNodeMaxNumEntries` etc. for now, since they are both cheaper to compute, and useful for typical user code that iterates over the rows of a `Row{Graph,Matrix}`.

@trilinos/tpetra should we rename or remove this issue, as a result of us splitting this work into parts?

**Comment by mhoemmen** [comment]
I decided to rename this issue, since #2630 covers `getGlobalNumDiags`.
