### ISSUE TITLE
Test MueLu_Structured_Line_Tpetra_MPI_4 randomly timing out (hanging) in build Trilinos-atdm-waterman_cuda-9.2_shared_opt starting 9/17/2019

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#6070]
CC: @trilinos/muelu, @srajama1 (Trilinos Linear Solvers Product Lead), @bartlettroscoe, @fryeguy52

<Checklist>
<???: Add label "client: ATDM">
<???: Add label "ATDM Sev: Blocker" (by default but could be other "ATDM Sev: XXX")>
<???: Add label "type: bug"?>
<???: Add label for affected packages (e.g. "pkg: MueLu", "pkg: Tpetra", "pkg: Kokkos", etc.)>
<???: Add label "PA: ???Project Area???" (e.g. "PA: Linear Solvers", "PA: Data Services")>
<???: Add milestone "Initial cleanup of new ATDM ..." or "Keep promoted ATDM ...">
<???: Once GitHub Issue is created, add entries for tests to TrilinosATDMStatus/*.csv files>

## Next Action Status

<status-and-or-first-action>

## Description

As shown in [this query](https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-waterman_cuda-9.2_shared_opt&field2=testname&compare2=61&value2=MueLu_Structured_Line_Tpetra_MPI_4&field3=site&compare3=61&value3=waterman&field4=buildstarttime&compare4=84&value4=2019-10-09T04%3A01%3A00UTC&field5=buildstarttime&compare5=83&value5=2019-09-09T04%3A01%3A00UTC) the test:

* `MueLu_Structured_Line_Tpetra_MPI_4`

is randomly timing out in the build:

* `Trilinos-atdm-waterman_cuda-9.2_shared_opt`

It timed out 6 times at 10 minutes and when it passed, it passed under 10 seconds.  When it times, it shows an error message like:

```
Laplace3D: Setup Smoother (MueLu::Ifpack2Smoother{type = LINESMOOTHING_BANDEDRELAXATION})
orientation = Z   [default]


p=0: *** Caught standard std::exception of type 'std::runtime_error' :

 /home/atdm-devops-admin/jenkins/waterman/Trilinos-atdm-waterman_cuda-9.2_shared_opt/SRC_AND_BUILD/Trilinos/packages/ifpack2/src/Ifpack2_BandedContainer_def.hpp:411:
 
 Throw number = 1
 
 Throw test that evaluated to true: INFO > 0
 
 Ifpack2::BandedContainer::factor: LAPACK's _GBTRF (LU factorization with partial pivoting) reports that the computed U factor is exactly singular.  U(13,13) (one-based index i) is exactly zero.  This probably means that the input matrix has a singular diagonal block.
```

Therefore, the timeout appears to be due to a hang where one process throws and exception and the other process hang (which MPI is not supposed to do anymore but there you go).

What is interesting is that different diagonals as shown as being singular as shown in [this query](https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&begin=2019-08-01&end=2019-10-10&filtercount=4&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-&field2=testname&compare2=61&value2=MueLu_Structured_Line_Tpetra_MPI_4&field3=status&compare3=61&value3=failed&field4=testoutput&compare4=95&value4=This%20probably%20means%20that%20the%20input%20matrix%20has%20a%20singular%20diagonal%20block).  Also, that query shows that this error only occurs in this one build (at least since 8/1/2019).

It seems unlikely this is a system issue.  Could there be a race condition?

## Current Status on CDash

* [MueLu_Structured_Line_Tpetra_MPI_4 on Trilinos-atdm-waterman_cuda-9.2_shared_opt last 30 days](https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&begin=30%20days%20ago&end=now&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-waterman_cuda-9.2_shared_opt&field2=testname&compare2=61&value2=MueLu_Structured_Line_Tpetra_MPI_4&field3=site&compare3=61&value3=waterman)

## Steps to Reproduce

One should be able to reproduce this failure on the machine <supported-atdm-machine> as described in:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md

More specifically, the commands given for the system <supported-atdm-system> are provided at:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#waterman

The exact commands to reproduce this issue should be:

```
$ cd <some_build_dir>/

$ source $TRILINOS_DIR/cmake/std/atdm/load-env.sh \
    Trilinos-atdm-waterman_cuda-9.2_shared_opt

$ cmake \
  -GNinja \
  -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
  -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_MueLu=ON \
  $TRILINOS_DIR

$ make NP=20

$ bsub -x -Is -n 20 ctest -j20
```

Since this is randomly failing, it may be hard to repoduce.

**Comment by cgcgcg** [comment]
This looks like it's been resolved.
https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&begin=2019-10-01&end=NOW&filtercount=7&showfilters=1&filtercombine=and&field1=testname&compare1=61&value1=MueLu_Structured_Line_Tpetra_MPI_4&field2=status&compare2=61&value2=Failed&field3=testoutput&compare3=94&value3=Error%3A%20error%20in%20ptssup_mkcltsock_afunix()&field4=testoutput&compare4=94&value4=Error%3A%20Remote%20JSM%20server%20is%20not%20responding&field5=testoutput&compare5=94&value5=step%20creation%20temporarily%20disabled%2C%20retrying&field6=testoutput&compare6=94&value6=Unable%20to%20create%20step%20for%20job&field7=buildname&compare7=63&value7=atdm
