### ISSUE TITLE
MueLu: long build time on rocketman

### ISSUE THREAD

**Issue by jhux2** [trilinos/Trilinos#6072]
In the nightly testing of Tpetra with deprecated code disabled on the machine rocketman, it's taking about 4 hours to compile just MueLu.

https://testing.sandia.gov/cdash/buildSummary.php?buildid=5758837#!#Build

@trilinos/muelu @trilinos/tpetra

**Comment by csiefer2** [comment]
:open_mouth:

**Comment by jhux2** [comment]
Closing, as this is very low priority.  Can reopen if necessary.
