### ISSUE TITLE
Trilinos:  RHEL7 sems openmpi runtime failure

### ISSUE THREAD

**Issue by tjfulle** [trilinos/Trilinos#6075]
## Question
@trilinos/framework 

Is the atdm/sems-rhel7 environment used?  I ask because we can't get a simple program to compile using its compilers:

```
[micpowe@cee-compute005 openmpi]$ module purge
[micpowe@cee-compute005 openmpi]$ module load sems-env
[micpowe@cee-compute005 openmpi]$ module load sems-gcc/7.2.0 sems-openmpi/1.10.1
[micpowe@cee-compute005 openmpi]$ echo $LD_LIBRARY_PATH
/projects/sems/install/rhel7-x86_64/sems/compiler/gcc/7.2.0/openmpi/1.10.1/lib:/projects/sems/install/rhel7-x86_64/sems/compiler/gcc/4.8.5/openmpi/1.10.1/lib:/projects/sems/install/rhel7-x86_64/sems/compiler/gcc/7.2.0/base/lib64:/projects/sems/install/rhel7-x86_64/sems/compiler/gcc/7.2.0/base/lib
[micpowe@cee-compute005 openmpi]$ cat mpi_hello.C
#include <mpi.h>
#include <iostream>
 
int main(int argc, char *argv[])
{
  MPI_Init(&argc, &argv);
  std::cout << "Hello, world :)\n";
  MPI_Finalize();
}
[micpowe@cee-compute005 openmpi]$ mpicxx mpi_hello.C
[micpowe@cee-compute005 openmpi]$ mpirun -np 2 ./a.out
./a.out: symbol lookup error: /projects/sems/install/rhel7-x86_64/sems/compiler/gcc/7.2.0/openmpi/1.10.1/lib/libmca_common_verbs.so.7: undefined symbol: ompi_common_verbs_usnic_register_fake_drivers
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.
-------------------------------------------------------
```

How have other Trilinos users been able to use this sems environment on this platform?  A quick google search brings up others with similar problems and the suggestion to ditch openmpi 1.10.1.

**Comment by jhux2** [comment]
@tjfulle I just tried the reproducer on an RHEL7 machine with SEMS mounted, and everything worked just fine.  Have you tried logging out and back in, rather than doing a module purge?

**Comment by tjfulle** [comment]
Thanks @jhux2!  I've heard from a few people that it works fine for them.  Must be an environment thing.  I'll keep probing...

**Comment by lxmota** [comment]
@tjfulle Did you find out what the issue was? I just ran into the same problem.

**Comment by tjfulle** [comment]
@lxmota , nope, never did find the problem.  With my blade being updated this week, I this may be an issue for me again...

**Comment by lxmota** [comment]
My blade had been running RHEL7.2 for several months now, and I hadn't run into this issue until I tried to use a version of gcc > 6.2. I'm reverting back to that compiler now. In my case, this crops up when trying to run Albany.
