### ISSUE TITLE
Belos: working with CUDA_LAUNCH_BLOCKING unset?

### ISSUE THREAD

**Issue by jewatkins** [trilinos/Trilinos#6079]
## Bug Report
@trilinos/belos

### Description
Block gmres + ilu only ran one iteration (normally runs 10) then threw this error on the next call:
```
p=0: *** Caught standard std::exception of type 'Belos::OrthoError' :

 /home/sparc/Trilinos/packages/belos/src/BelosICGSOrthoManager.hpp:1060:

 Throw number = 1

 Throw test that evaluated to true: SCT::real(oldDot[0]) < ZERO

 Belos::ICGSOrthoManager::findBasis(): Negative definiteness discovered in inner product
```
I tried adding `Kokkos::fence()` after all other parallel loops but still got the error so I suspect it might be in belos. This is while running some tests in sparc. Some tests pass and others don't so it may be a specific code path (for example the single vector version seemed to pass). 

Is belos working with CUDA_LAUNCH_BLOCKING unset? Checking as this may be one of a few things preventing us from nightly testing with CUDA_LAUNCH_BLOCKING unset.

**Comment by jhux2** [comment]
@trilinos/belos

**Comment by csiefer2** [comment]
@jewatkins This is not a regularly tested configuration, so I suspect that nobody knows.

**Comment by jewatkins** [comment]
I suspected as much. Could someone change the label to enhancement? It's not urgent right now but could be something to look into later.

**Comment by kddevin** [comment]
@trilinos/tpetra is looking at fences and CUDA_LAUNCH_BLOCKING removal from Tpetra now.  #7446 
When we are done, we will spin back to this issue and engage with @trilinos/below.   
If you don't hear from us, @jewatkins , please ping us again.

**Comment by mhoemmen** [comment]
begone bot

**Comment by jewatkins** [comment]
What is the current status on this?

**Comment by jhux2** [comment]
@jloe @hkthorn

**Comment by kddevin** [comment]
Trilinos is PR tested with CUDA_LAUNCH_BLOCKING=OFF.

**Comment by jewatkins** [comment]
okay, will give this another go.

**Comment by mhoemmen** [comment]
@jhux2 Did you perhaps mean @jennloe ?

**Comment by jhux2** [comment]
Oh man, the paparazzi are going to have a fit!

**Comment by jewatkins** [comment]
This is working now with the latest trilinos develop. In order to turn off CUDA_LAUNCH_BLOCKING for nightly testing, we need a better way to capture timing data for performance tests. How are you all approaching that? Are you adding fences within each timer region? kokkos-tools? It might be nice to have an option to fence all teuchos timers.

I could open another issue. Thanks all!

**Comment by jhux2** [comment]
> In order to turn off CUDA_LAUNCH_BLOCKING for nightly testing, we need a better way to capture timing data for performance tests. How are you all approaching that? Are you adding fences within each timer region? kokkos-tools? It might be nice to have an option to fence all teuchos timers.
> 
> I could open another issue. Thanks all!

@jewatkins Please do, this would be a good discussion to have.

**Comment by jennloe** [comment]
@jewatkins This is a good question; I will soon be running new performance tests for Belos.
