### ISSUE TITLE
KokkosCore and Intrepid2 tests timing out in build Trilinos-atdm-white-ride-cuda-10.1-gnu-7.2.0-release-debug starting 2019-10-03

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#6091]
CC: @trilinos/kokkos, @trilinos/intrepid2, @kddevin (Trilinos Data Services Product Lead), @mperego (Trilinos Discretizations Product Lead), @bartlettroscoe, @fryeguy52

<Checklist>
<???: Add label "client: ATDM">
<???: Add label "ATDM Sev: Blocker" (by default but could be other "ATDM Sev: XXX")>
<???: Add label "type: bug"?>
<???: Add label for affected packages (e.g. "pkg: MueLu", "pkg: Tpetra", "pkg: Kokkos", etc.)>
<???: Add label "PA: ???Project Area???" (e.g. "PA: Linear Solvers", "PA: Data Services")>
<???: Add milestone "Initial cleanup of new ATDM ..." or "Keep promoted ATDM ...">
<???: Once GitHub Issue is created, add entries for tests to TrilinosATDMStatus/*.csv files>

## Next Action Status

<status-and-or-first-action>

## Description

As shown in [this query](https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&begin=2019-09-14&end=2019-10-13&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-white-ride-cuda-10.1-gnu-7.2.0-release-debug&field2=block&field2count=2&field2field1=testname&field2compare1=61&field2value1=KokkosCore_UnitTest_Cuda_MPI_1&field2field2=testname&field2compare2=61&field2value2=Intrepid2_unit-test_Discretization_Basis_HVOL_HEX_Cn_FEM_Serial_Test_01_SLFadDFad_MPI_1&field3=site&compare3=61&value3=ride) the tests:

* `KokkosCore_UnitTest_Cuda_MPI_1`
* `Intrepid2_unit-test_Discretization_Basis_HVOL_HEX_Cn_FEM_Serial_Test_01_SLFadDFad_MPI_1`

starting timing out in the build:
	 	
* `Trilinos-atdm-white-ride-cuda-10.1-gnu-7.2.0-release-debug`

starting on testing day 2019-10-03.

The output for [KokkosCore_UnitTest_Cuda_MPI_1](https://testing-dev.sandia.gov/cdash/testDetails.php?test=76194541&build=4901747) shows it timing out while running the unit test:

```
[ RUN      ] cuda.scan
```

The output for [Trilinos-atdm-white-ride-cuda-10.1-gnu-7.2.0-release-debug](https://testing-dev.sandia.gov/cdash/testDetails.php?test=76194745&build=4901746) shows it timing out while `Testing Cause Points` showing:

```
===============================================================================
| TEST 3: correctness of basis function values                                |
===============================================================================
 -- Testing Equispaced Points -- 
 -- Testing WarpBlend Points -- 
 -- Testing Gauss Points -- 
```

The new commits that were pulled the day that these failures started are show, for example, [here](https://testing-dev.sandia.gov/cdash/viewNotes.php?buildid=4901741#!#note6) does not show any changes to the ATDM Trilinos configuration or Kokkos or Intrepid2.  Thereofre, it seems unlikley these new timeouts were due to changes in Trilinos but it is possible (as other tests changed).

I lumped these two test failures together in the same Issue because they started on the same day.

## Current Status on CDash

* [30 days of history on these tests in this build](https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&begin=30%20days%20ago&end=now&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-white-ride-cuda-10.1-gnu-7.2.0-release-debug&field2=block&field2count=2&field2field1=testname&field2compare1=61&field2value1=KokkosCore_UnitTest_Cuda_MPI_1&field2field2=testname&field2compare2=61&field2value2=Intrepid2_unit-test_Discretization_Basis_HVOL_HEX_Cn_FEM_Serial_Test_01_SLFadDFad_MPI_1&field3=site&compare3=61&value3=ride)

## Steps to Reproduce

One should be able to reproduce this failure on the machine 'ride' as described in:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md

More specifically, the commands given for the system 'ride' are provided at:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#ridewhite

The exact commands to reproduce this issue should be:

```
$ cd <some_build_dir>/

$ source $TRILINOS_DIR/cmake/std/atdm/load-env.sh <build-name>

$ cmake \
 -GNinja \
 -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
 -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_KokkosCore=ON -DTrilinos_ENABLE_Intrepid2=ON \
 $TRILINOS_DIR

$ make NP=16

$ bsub -x -Is -q rhel7F -n 16 ctest -j4
```

**Comment by srajama1** [comment]
@mperego is a better contact than me.

**Comment by bartlettroscoe** [comment]
@trilinos/kokkos, @trilinos/intrepid2, 

If you look at [this query](https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&date=2019-10-13&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-&field2=block&field2count=2&field2field1=testname&field2compare1=61&field2value1=KokkosCore_UnitTest_Cuda_MPI_1&field2field2=testname&field2compare2=61&field2value2=Intrepid2_unit-test_Discretization_Basis_HVOL_HEX_Cn_FEM_Serial_Test_01_SLFadDFad_MPI_1&field3=site&compare3=61&value3=ride) you can that the test `Intrepid2_unit-test_Discretization_Basis_HVOL_HEX_Cn_FEM_Serial_Test_01_SLFadDFad_MPI_1` passes in less than 4s in all of the other CUDA 9.2 and non-CUDA builds.  And the test `KokkosCore_UnitTest_Cuda_MPI_1` passes in less than 1.5 minutes in all of the other CUDA 9.2 and non-CUDA builds.

Given that there were no changes to Trilinos pulled on 2019-10-03 that I can see that could trigger this changes in behavior for this Kokkos test, we might consider if there was a change to the CUDA 10.1 env on 'ride'?  But I can't find any emails sent out about changes to 'ride' around that time.

What is the status of CUDA 10.1 for ATDM?

**Comment by bartlettroscoe** [comment]
As shown in [this query[(https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&begin=2020-01-20&end=2020-02-18&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-white-ride-cuda-10.1-gnu-7.2.0-release-debug&field2=testname&compare2=61&value2=Intrepid2_unit-test_Discretization_Basis_HVOL_HEX_Cn_FEM_Serial_Test_01_SLFadDFad_MPI_1&field3=site&compare3=61&value3=ride), the test:

* 
Intrepid2_unit-test_Discretization_Basis_HVOL_HEX_Cn_FEM_Serial_Test_01_SLFadDFad_MPI_1
     
has gone missing from the build

* Trilinos-atdm-white-ride-cuda-10.1-gnu-7.2.0-release-debug

since 2020-01-31.   So I will drop it from tracking.

**Comment by mperego** [comment]
I guess we can close this issue now. @bartlettroscoe feel free to reopen if this is not the case.
