### ISSUE TITLE
Tpetra: building a CrsMatrix from an Eigen SparseMatrix

### ISSUE THREAD

**Issue by DABH** [trilinos/Trilinos#6093]
## Question
@trilinos/tpetra

I have some legacy code that uses Eigen to build a SparseMatrix (a row-major CRS sparse matrix).  In my program I'm trying to convert that Eigen matrix to a Tpetra CrsMatrix, which I believe is mathematically the same representation.  However, I haven't found an efficient way to do the conversion between these data structures, and have so far been resorting to manually building the Tpetra matrix one row at a time, in serial, with the entries of my Eigen matrix.  Does anyone have any experience converting sparse matrices from Eigen to the Trilinos/Tpetra format, and how do to this as efficiently as possible, e.g. with memcpying the underlying arrays?  Thanks in advance!

cc @sslattery

**Comment by jhux2** [comment]
@DABH Have a look at the `setAllValues` method of Tpetra::CrsMatrix.  For an example of how this is used, see `MueLu_TentativePFactory_def.hpp`.

**Comment by jhux2** [comment]
Btw, only members of the Trilinos repo can do @ mentions.  (It's a known github limitation.) @trilinos/tpetra

**Comment by mhoemmen** [comment]
@jhux2 It's nicer to use the constructors that take Kokkos::View.  `setAllValues` (at least the overload that takes `Teuchos::ArrayRCP`) must deep-copy its input.  Also, creating a filled matrix on construction better respects the RAII idiom than creating an empty matrix and calling `setAllValues` later.

**Comment by lucbv** [comment]
I will add a little on to what @mhoemmen is saying:
1. here is a constructor for a CrsMatrix that takes five arguments (the sixth argument is optional):
 ```
CrsMatrix (const Teuchos::RCP< const map_type > &rowMap,
            const Teuchos::RCP< const map_type > &colMap,
            const typename local_matrix_type::row_map_type &rowPointers,
            const typename local_graph_type::entries_type::non_const_type &columnIndices,
            const typename local_matrix_type::values_type &values,
            const Teuchos::RCP< Teuchos::ParameterList > &params=Teuchos::null)
```
as you can see the main new data you will need to provide are the `rowMap` and `colMap`, the three views for `rowPointers`, `columnIndices` and `values` can probably be constructed using the data in the Eigen SparseMatrix. You can find more info on Tpetra CrsMatrix [here](https://trilinos.org/docs/dev/packages/tpetra/doc/html/classTpetra_1_1CrsMatrix.html)

2. you can construct Kokkos views from pointers as follows:
```
const int numNonZeros = EigenMatrix.nonZeros();
double* values_ptr = EigenMatrix.valuePtr();
Kokkos::View<double*, Kokkos::HostSpace, Kokkos::MemoryTraits<Kokkos::Unmanaged> >
    values (x_raw, numNonZeros);
```
you can find more info on Kokkos views [here](https://github.com/kokkos/kokkos/wiki/View), in your case I recommend [this section](https://github.com/kokkos/kokkos/wiki/View#654-unmanaged-views) in particular.
