### ISSUE TITLE
MueLu: Improving performance

### ISSUE THREAD

**Issue by DABH** [trilinos/Trilinos#6094]
## Question
@trilinos/muelu 

In #6005 I was trying to get a linear solve working with PCG for a Poisson-type system that has a rank-one nullspace.  I'm able to solve my systems now (although still not having success all the time with the MG preconditions, having enough success from tuning parameters).  So now I am trying to look at performance and see whether MueLu+Belos can outperform other libraries such as Eigen for the systems I'm interested in.

So far, this does not seem to be the case; e.g. if I do an incomplete-Cholesky-preconditioned CG solve in Eigen on my systems, I can get performance that's roughly as good and sometimes a couple times better than what I get with my Trilinos solve.  I tried out my solve on a V100 GPU but didn't get any noticeable performance benefits, despite having a pretty large system (~2 million DOFs) -- this was rather sad to see!  Anyway, seems like it's a combination of the preconditioner being expensive to apply, and the preconditioner just not working well enough to drive the number of iterations down to where the benefits outweigh the costs.

Would anyone be able to help take a look at the system I'm trying to solve and provide any advice on how I could tackle it more performantly, e.g. using some different MueLu settings?  I uploaded a copy of one of my large systems here: https://www.filemail.com/d/xstysvakchyivih (~8GB) and a smaller version of the system (~130MB) in the Dropbox link below.  These systems are both in Eigen SparseMatrix format.

I also can share a demo program that solves the system using Trilinos or Eigen (some tweaks would need to be made to CMakeLists.txt to compile on your machine, to point to Trilinos/Eigen or to remove support for one or the other): https://www.dropbox.com/sh/5isgc1fs4o9qyqa/AACg---8HnkowAHK0Q1nRnR-a?dl=0 The usage is like `OMP_NUM_THREADS=16 ./solver_benchmarking -i ./mat.bin --solver cg --lib trilinos --remove_zrc --max_iter 10000 --tol 1e-4 --use_precond`.  Hope that can help ease the process of investigating the performance.

Very grateful for any tips you can provide from the general to the specific - thanks in advance!

cc @sslattery

**Comment by cgcgcg** [comment]
@DABH Could you post the log file of one of your runs? Maybe with "verbosity" set to "extreme"?

**Comment by DABH** [comment]
Absolutely!  Here is an example I ran where Eigen did a solve in ~88s and with Belos + MueLu preconditioner the total time was ~102s (excluding things like preconditioner setup -- i.e. only counting time during the PCG iterations).  Let me know if you spot anything immediately fishy.  Thanks again.

[log.txt](https://github.com/trilinos/Trilinos/files/3726936/log.txt)

**Comment by cgcgcg** [comment]
@DABH Is this a high-order discretization? It has ~330 unknowns per row! At least for low-order discretization, I would not expect more than ~10 iterations. A quick (performance improving) change that you could easily try out is to switch "multigrid algorithm" to "unsmoothed". Please also set "use kokkos refactor" to true.

**Comment by DABH** [comment]
@cgcgcg yes, this is arising from some higher-order stuff.  I took your changes and used "unsmoothed" as well as "use kokkos refactor."  This meant I also had to change min and max agg size to 0 because otherwise I was getting errors from MueLu about leftover nodes while constructing the preconditioner.  Anyway, with those changes in, I'm now down to 101s.  This is like 20% better!!   But unfortunately is still lagging Eigen by 20%.  The other cost I haven't mentioned is actually building the preconditioner in the first place, which of course takes even more time...

Thanks again so much for the quick reply and help with this.  Would really appreciate any other ideas you have to try.

[log2.txt](https://github.com/trilinos/Trilinos/files/3728404/log2.txt)

**Comment by sslattery** [comment]
Also, for reference these systems @DABH are generating have been coming from some flow problems in the ExaAM ECP project - we are very keen on using MueLu for some of our challenge problems in that project using Summit if possible.

**Comment by cgcgcg** [comment]
@DABH 

It looks like the dominating cost is the matvec on the finest level, i.e. with the input matrix.

You could try increasing "chebyshev: ratio eigenvalue". I'd try some values between 20 and 60ish, which is the coarsening ratio. You could also experiment with "chebyshev: degree" = 1 and see if that does anything for you.

Out of curiosity: you said that CG+diagonal preconditioning resulted in a solve time of 88s. I see that Trilinos takes about 0.35s for a single matvec with the matrix, so 55 its * 6 * 0.35 s = 113 s. (The 6 comes from 2 pre- + 2 postsmoothing steps, 1 residual, 1 in CG.) So I imagine CG+diagonal takes about 500 iterations? And how does that behave for larger problems?

**Comment by cgcgcg** [comment]
@DABH Oh, and you probably also want increase "max levels" to 10 and instead set "coarse: max size" to something reasonable. Remember that by using "fix nullspace" = true, the system on the coarsest grid becomes dense, so you might not want something too big there..

**Comment by DABH** [comment]
@cgcgcg I tried playing around with the parameters/values you mentioned.  I seem to keep hitting minor variations of this error:
```
MueLu::R*A*P-implicit-8 ERROR, not enough memory allocated for matrix product. Allocated: 1630
```
(sometimes says implicit-9).  I attached a log from a sample run.

Eigen solves the system in 88 seconds and 217 iterations so like 0.41 seconds/iteration vs. ~2.1 seconds/iteration for Trilinos?

This is the largest problem I've tried.  I could try a larger one though my hope was that by ~2M DOFs I'd start to see Trilinos winning out :)

[log3.txt](https://github.com/trilinos/Trilinos/files/3731451/log3.txt)

**Comment by cgcgcg** [comment]
@DABH It looks like the coarsening is almost stagnating which is not great. You could try setting "coarse: max size" = 5000 and see how good/bad that does.

**Comment by DABH** [comment]
@cgcgcg Nice, that resolved that error!  Solve time still floats around like 104s (54 iterations) so ideally could still find some ways to improve performance, but definitely acknowledge this system has some features that make it a bit trickier (more non zeros per row, constant nullspace...)

**Comment by cgcgcg** [comment]
@DABH So varying the Chebyshev parameter did not do anything? :-(

**Comment by DABH** [comment]
@cgcgcg not so much unfortunately.  I've tried a few values of the Chebyshev degree (1,2,3), the eigenvalue ratio (20, 40, 60), and the max size (3, 4, 10), and the best run I got so far was ~97s for 38 iterations.  Driving up the Chebyshev degree does reduce iterations further but then the solve time just goes up again.

**Comment by jhux2** [comment]
@sslattery @DABH What's the order of the FE bases?

**Comment by DABH** [comment]
@jhux2 This is arising from something like an FEM discretization with quadratic B-splines.  So the system itself should be at least "second order" in terms of the bases its using.

**Comment by cgcgcg** [comment]
@DABH Is this a scalar system? Or vector-Poisson?

**Comment by DABH** [comment]
@cgcgcg The solution vector is just scalar pressure values on nodes of a uniform Cartesian grid (which is why the matrix is pretty structured).

**Comment by cgcgcg** [comment]
I was asking because I wasn't quite sure about the number of entries per row. If this is a tensor product stencil, then this looks like 7^3 = 343 is about 310 modulo boundary conditions. Anyway, we do have some capabilities for higher order discretizations, but I am not sure if they will work for you. @csiefer2 ?

**Comment by DABH** [comment]
As a follow up on this / point of comparison, I tried out the same system using AMGCL (https://amgcl.readthedocs.io/en/latest/), using smoothed aggregation + degree 5 chebyshev + cg, and was able to build the preconditioner (on the CPU) + solve the system (on the GPU) to tolerance in a total of ~25s / 34 iterations.  The actual CG iterations took about 5 of those 25s; the other 20 were preconditioner setup + data transfer.  Perhaps an unfair comparison since my Trilinos solve is all on the CPU, but I don't think just CPU/GPU is enough to explain the drastic difference compared to the ~100s solve time with MueLu+Belos.

Would love to hear any ideas on how to make the Trilinos stack perform better -- since these results suggest it's possible -- or if there's anything more I can try as far as capabilities for higher order discretization.  Thanks again!

**Comment by cgcgcg** [comment]
@DABH Could you add the following to your input xml
```
<ParameterList name="export data">
    <Parameter name="A" type="string" value="{0}"/>
</ParameterList> 
```
and then post the resulting matrix file? Also, what's your RHS and Belos settings?

**Comment by DABH** [comment]
@cgcgcg Here is a link to the matrix file.  It's compressed; uncompressed the file is ~27G.
https://tinyurl.com/y46lh5xw

The RHS is just `b = A*x` for a random `x`.  Then `b` gets shifted so its mean is zero.  Thus is should be entirely in the range of `A` with no nullspace component.  Here is the code:
```
    size_t numrhs = 1; // this is the number of columns in the vector -- should be 1!!
    printf("Problem dimensions: %d rows, %d rows, %d RHS\n", (int)numGblIndices, (int)rows, (int)numrhs);
    // Create initial vectors
    Teuchos::RCP<vec_type> B, X;
    X = Teuchos::rcp(new vec_type(A_trilinos->getDomainMap(),numrhs));
    Belos::MultiVecTraits<scalar_type, vec_type>::MvRandom(*X);
    B = Teuchos::rcp(new vec_type(A_trilinos->getRangeMap(),numrhs));
    Belos::OperatorTraits<scalar_type, vec_type, op_type>::Apply(*A_trilinos, *X, *B);

    // Zero-mean-shift B
    std::vector<T> mv(numrhs);
    Teuchos::ArrayView<T> means(mv);
    B->meanValue(means);
    T mean = means[0];
    Teuchos::RCP<vec_type> shift = Teuchos::rcp(new vec_type(A_trilinos->getRangeMap(),numrhs));
    shift->putScalar(mean);
    B->update(T(-1), *shift, T(1));

    Belos::MultiVecTraits<scalar_type, vec_type>::MvInit(*X, 0.0);
```

Belos settings look like
```
    Belos::LinearProblem<scalar_type, vec_type, op_type> problem(A_trilinos, X, B);
    problem.setLeftPrec(mueLuPreconditioner);
    bool set = problem.setProblem();

    Teuchos::ParameterList belosList;
    belosList.set("Block Size", 1);
    belosList.set("Maximum Iterations", config.max_iter); // 500
    belosList.set("Convergence Tolerance", config.tol); // 1e-4
    belosList.set("Output Frequency", 1);
    belosList.set("Verbosity", Belos::TimingDetails + Belos::FinalSummary + Belos::IterationDetails);

    Belos::BlockCGSolMgr<scalar_type, vec_type, op_type> solver(rcp(&problem, false), rcp(&belosList, false));
    Belos::ReturnType ret = solver.solve();
    printf("Solver returned code %d, should be 0\n", (int)ret);
```
where `mueLuPreconditioner` comes from
```
    std::string optionsFile = "mueluOptions.xml";
    Teuchos::RCP<MueLu::TpetraOperator<> > mueLuPreconditioner =
        MueLu::CreateTpetraPreconditioner(A_trilinos, optionsFile);
    Teuchos::RCP<vec_type> nullspace = Teuchos::rcp(new vec_type(A_trilinos->getDomainMap(), 1));
    nullspace->putScalar(T(1));
    mueLuPreconditioner->GetHierarchy()->GetLevel(0)->Set("Nullspace", nullspace);
    printf("Created preconditioner\n");
```

**Comment by cgcgcg** [comment]
@DABH Any chance we can get a smaller system?

**Comment by DABH** [comment]
@cgcgcg ha, sure, here is one that is only 3.3G uncompressed :) https://tinyurl.com/y3wggyqn I can go smaller too, just let me know, but if the system gets too small then fancy preconditioning definitely becomes overkill.

**Comment by csiefer2** [comment]
> @jhux2 This is arising from something like an FEM discretization with quadratic B-splines.

You could probably put something together do to P-coarsening using MueLu.  That might work better.  Unfortunately, quadratic B-splines are not a basis we have built-in support for.
