### ISSUE TITLE
MueLu:  Zero Init Guess Busted when only doing post-smoothing

### ISSUE THREAD

**Issue by rstumin** [trilinos/Trilinos#6111]
## Bug Report
@trilinos/\<muelu\>

### Description
When only doing post-smoothing with 'zeroGuess' true, the solution 'X' is used before it is initialized when computing the residual (for projection) and when the interpolation solution is added to X.  I've  attached my patch to this, but I'm not really sure how robust this is. There are some "interesting" things in the V cycle like emptyFineSolve and emptyCoarseSolve that I don't fully understand. 
[myPatch.txt](https://github.com/trilinos/Trilinos/files/3736851/myPatch.txt)

### Steps to Reproduce
Just do post-smoothing only.

**Comment by jhux2** [comment]
@trilinos/muelu

**Comment by csiefer2** [comment]
#6130

**Comment by jhux2** [comment]
Can this be closed as fixed?
