### ISSUE TITLE
ATDM scripts: how to add "--remove-duplicate-link-files"

### ISSUE THREAD

**Issue by jhux2** [trilinos/Trilinos#6116]
@bartlettroscoe 

I am compiling Trilinos on waterman and need RDC and the option `--remove-duplicate-link-files`.  It appears that the ATDM scripts should allow for this: https://github.com/trilinos/Trilinos/blob/648b1ad4ee087a129f5b6c895e5085483949c45b/cmake/std/atdm/ATDMDevEnvSettings.cmake#L185-L186.

However, if I do the following, neither `ATDM_USE_CUDA` nor `ATDM_CUDA_RDC` are defined.

```
source $TRILINOS_DIR/cmake/std/atdm/load-env.sh cuda-debug-rdc
cmake -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake ...
```

Should the scripts define them?  If so, how should they be invoked to get the desired behavior?  Thanks for any help you provide.

**Comment by bartlettroscoe** [comment]
@jhux2, as explained in:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#rdc

just adding `rdc` to your build name should add `--remove-duplicate-link-files`.  For example, you can see `--remove-duplicate-link-files` being added for the build `Trilinos-atdm-waterman-cuda-9.2-rdc-release-debug` at:

* https://testing.sandia.gov/cdash/viewBuildError.php?type=1&buildid=5787753

showing

`/home/projects/ppc64le-pwr9-nvidia/openmpi/2.1.2/gcc/7.2.0/cuda/9.2.88/bin/mpicxx" "-I." "-I/home/jenkins/waterman/workspace/Trilinos-atdm-waterman-cuda-9.2-rdc-release-debug/SRC_AND_BUILD/Trilinos/packages/kokkos/tpls/gtest" "-Ipackages/kokkos/core/src" "-I/home/jenkins/waterman/workspace/Trilinos-atdm-waterman-cuda-9.2-rdc-release-debug/SRC_AND_BUILD/Trilinos/packages/kokkos/core/src" "-I/home/projects/ppc64le-pwr9-nvidia/cuda/9.2.88/include" "-Ipackages/kokkos/core/unit_test" "-I/home/jenkins/waterman/workspace/Trilinos-atdm-waterman-cuda-9.2-rdc-release-debug/SRC_AND_BUILD/Trilinos/packages/kokkos/core/unit_test" "--remove-duplicate-link-files" "--std=c++11" "-lineinfo" "-g" "--relocatable-device-code=true" "-Xcudafe" "--diag_suppress=esa_on_defaulted_function_ignored" "-expt-extended-lambda" "-arch=sm_70" "-DGTEST_HAS_PTHREAD=0" "-O3" "-DNDEBUG" "-MD" "-MT" "packages/kokkos/core/unit_test/CMakeFiles/KokkosCore_UnitTest_Serial.dir/serial/TestSerial_Task.cpp.o" "-MF" "packages/kokkos/core/unit_test/CMakeFiles/KokkosCore_UnitTest_Serial.dir/serial/TestSerial_Task.cpp.o.d" "-o" "packages/kokkos/core/unit_test/CMakeFiles/KokkosCore_UnitTest_Serial.dir/serial/TestSerial_Task.cpp.o" "-c" "/home/jenkins/waterman/workspace/Trilinos-atdm-waterman-cuda-9.2-rdc-release-debug/SRC_AND_BUILD/Trilinos/packages/kokkos/core/unit_test/serial/TestSerial_Task.cpp"`

for example.

On 'waterman' I just did:

```
$ hostname
waterman11

$  . ~/Trilinos.base/Trilinos/cmake/std/atdm/load-env.sh cuda-debug-rdc 
Hostname 'waterman11' matches known ATDM host 'waterman' and system 'waterman'
Setting compiler and build options for build-name 'cuda-debug-rdc'
Using waterman compiler stack CUDA to build DEBUG code with Kokkos node type CUDA and KOKKOS_ARCH=Power9,Volta70

$ set | grep ATDM_CONFIG | grep _RDC
ATDM_CONFIG_CUDA_RDC=ON
```

Not sure why this is not working for you.

**Comment by jhux2** [comment]
@bartlettroscoe Can you grep for `--remove-duplicate-link-files`?

**Comment by bartlettroscoe** [comment]
> Can you grep for `--remove-duplicate-link-files`?

@jhux2, what do you mean?  Grep what?  It should be sets in the CMakeCache.txt file.  Grep for:

```
$ grep CMAKE_CXX_FLAGS CMakeCache.txt
```

and you should see it set there.

**Comment by jhux2** [comment]
Ok, I figured out my mistake.  My cmake configure line was overwriting CMAKE_CXX_FLAGS. After removing that from my cmake line, I now see `--remove-duplicate-link-files` in my CMakeCache.txt.  Thanks for your help, sorry about the noise.
