### ISSUE TITLE
Tpetra::Map/Epetra_BlockMap: preserve indexBase in ReplaceCommWithSubset

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#613]
@trilinos/xpetra @trilinos/tpetra @tawiesn @csiefer2 

The index base is redundant; users can get this information from the min or min overall global index.  Furthermore, it's confusing that Epetra requires the index base to equal the min overall global index.  This causes problems with implementing subset and strided Maps.

Changing this requirement on the index base might break backwards compatibility.  The easiest way to work around for now would be for SameAs to ignore the index base.

**Comment by tawiesn** [comment]
According to Chris, it is not a strict requirement for indexBase to be the global minimum of the global indices. The most reasonable solution is to keep the old index base in the ReplaceCommWithSubset routine. There is no reason why this routine should change the indexBase of the map (even if the subset comm keeps only a subpart of all GIDs the index base should not change...)

**Comment by tawiesn** [comment]
For your information: it's the same for Tpetra.
@mhoemmen,@csiefer2: i propse to replace
```
 const GO myMinGid = (this->getNodeNumElements () == 0) ?
        this->getMaxAllGlobalIndex () : this->getMinGlobalIndex ();
 GO newIndexBase = OrdinalTraits<GO>::invalid ();
 reduceAll<int, GO> (*newComm, REDUCE_MIN, myMinGid, outArg (newIndexBase));
 return rcp (new map_type (globalNumElts, myElts, newIndexBase, newComm, node));

```
by
`      return rcp (new map_type (globalNumElts, myElts, getIndexBase(), newComm, node));
`
in Tpetra::Map::replaceCommWithSubset
@mhoemmen: could you test this for me? There's still this issue with my configuration which makes the Tpetra tests crash.

**Comment by mhoemmen** [comment]
@tawiesn Would you consider using the testbeds for testing?  I could also get you an account on my workstation if that doesn't work.

**Comment by tawiesn** [comment]
@mhommen: yeah i can do that. I think i just start with a simple Tpetra configuration that should also work on my workstation.

**Comment by mhoemmen** [comment]
> @mhoemmen: yeah i can do that. I think i just start with a simple Tpetra configuration that should also work on my workstation.

I feel better about that.  I'm happy to test for CUDA but we should really get you a sensible configuration that works for Serial and OpenMP.  Otherwise you'll have to wait on me too much :-)

**Comment by tawiesn** [comment]
I have a working configuration with Tpetra tests now. Not sure, what's wrong with my other configuration.

**Comment by mhoemmen** [comment]
> I have a working configuration with Tpetra tests now.

Yay! :-D
