### ISSUE TITLE
Drop support for CUDA < 9

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#6134]
@trilinos/framework 

Kokkos is [dropping support for CUDA 7 and CUDA 8](https://github.com/kokkos/kokkos/issues/2489).  This means Trilinos should too, though in practice I suspect it already has long ago (since we don't do PR testing with CUDA < 9).

**Comment by crtrott** [comment]
Yeah that is why we didn't discuss this much with Trilinos. Since none of Trilinos's official testing does test CUDA pre 9 we didn't think this is an issue. Also CUDA 8 doesn't support Volta at all (and thus no support for Summit and Sierra).

**Comment by csiefer2** [comment]
We still use a Cuda 8 machine for development.  We'll need to upgrade that....
