### ISSUE TITLE
Epetra_DistObject: Get rid of DistributedGlobal_ field

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#614]
@trilinos/xpetra @trilinos/tpetra @tawiesn @csiefer2 

Get rid of Epetra_DistObject::DistributedGlobal_.  That field is redundant with its Map's field.  This causes confusion when implementing ReplaceMap, e.g., in Epetra_MultiVector.

**Comment by tawiesn** [comment]
Epetra_DistObject::DistributedGlobal_ is easy and safe to remove. In fact, it is only used in Epetra_DistObject in three places as well as in the Epetra_MultiVector.

**Comment by tawiesn** [comment]
My patch passed all Epetra tests on my machine. Let's check the dashboard tomorrow.

**Comment by tawiesn** [comment]
All tests are fine. Close issue
