### ISSUE TITLE
Panzer:  Split up Owned and Ghosted Vectors

### ISSUE THREAD

**Issue by jmgate** [trilinos/Trilinos#615]
Currently the `DOFManager` has `owned_` and `owned_and_ghosted_` vectors, where the second contains a copy of the first.  This work is to split those up such that we don't have any data replication, while maintaining the same functionality.
@trilinos/panzer

**Comment by jmgate** [comment]
A first task is the terms 'ghosted' and 'shared' are used throughout the `DOFManager` to mean the same thing.  This should be cleaned up&mdash;we're going with 'ghosted' throughout.

**Comment by eric-c-cyr** [comment]
This looks good. To be clear you clarified the distinction between using Neighbors and Ghosted values as well right?

**Comment by jmgate** [comment]
That's correct.  It seemed like the term 'ghosted' was overloaded, sometimes referring to all ghosted IDs, and sometimes referring only to ghosted IDs from neighbor element blocks.

**Comment by jmgate** [comment]
In `panzer::DOFManager` the `owned_and_ghosted_` vector has been replaced with a `ghosted_` one (`owned_` already existed), and the same functionality has been maintained without the data duplication.  The next step is to see about modifying our Epetra scatter/gathers.

**Comment by jmgate** [comment]
Another discrepancy in terminology, we had "unique" and "owned" referring to the same thing in various places.  This has been cleaned up such that we now have "owned" and "ghosted" vectors/maps/spaces everywhere.

**Comment by jmgate** [comment]
The completion of this work is being tracked in #1521.

**Comment by eric-c-cyr** [comment]
@jmgate We will close pending tests on Monday morning.
