### ISSUE TITLE
Tpetra: internal compiler error for CrsMatrix with gcc 7.4.0

### ISSUE THREAD

**Issue by aprokop** [trilinos/Trilinos#6154]
## Bug Report
@trilinos/tpetra 

### Description
When compiling on Summit with 7.4.0 compiler I was getting:
```
/ccs/home/aprokop/code/exawind/source/trilinos/packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp:4378:27: internal compiler error: in maybe_undo_parenthesized_ref, at cp/semantics.c:1739
         if (h_offsets[lclRow] != INV) {
```
Couple things of note:
- I am adding `-DCMAKE_CXX_STANDARD=14` to CMake options, as I need Kokkos to be compiled in c++14 mode
  The rest of Trilinos is compiled in C++11 as I don't touch `-DTrilinos_CXX11_FLAGS`
- I had to fix `kokkos-kernels` with a patch prior to getting to this point, see [here](https://github.com/kokkos/kokkos-kernels/issues/349#issuecomment-546071487) 

### Steps to Reproduce
SHA1:  66052799e001529e3a9db42d1e7c5cc57f7d1c8d
Configure log: 
[cmake_output.log](https://github.com/trilinos/Trilinos/files/3769312/cmake_output.log)

### Fix
A single line change to pass by value instead of by reference in the lambda fixed it for me.

**Comment by ndellingwood** [comment]
The kokkos-kernels patch to Trilinos issued in PR #6164, corresponding fix in kokkos/kokkos-kernels#485
