### ISSUE TITLE
Tpetra::CrsGraph: Feature request for option to build column Map with reachables last, rather than AztecOO ordering

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#6155]
## Enhancement
@trilinos/tpetra @csiefer2 @mperego 

> What feature/addition is needed?

Request for option in Tpetra::CrsGraph, so that when it generates its column Map, it puts the reachables on each process last in the Map, rather than using AztecOO order. In this way the first #owned+#shared elements of the column Map would have the same local ids of the row Map.

> How does this differ from what we currently have?

Generated column Map is always in AztecOO order (remotes are sorted by process rank first, rather than by shared /  reachable first). 

> Are there any alternative solutions you've considered?  Do you have suggestions on implementation?  How has the lack of this feature affected you? 

The lack of this feature makes the assembly more expensive (see last point).

> What are you trying to accomplish?  What specifically must we demonstrate to call this work complete?

The idea is to reuse the local Ids of the row Map also for the column map in the assembly phase, in order to avoid computing the column local ids from the global ids.

**Comment by csiefer2** [comment]
I think this was especially an FE request

**Comment by mperego** [comment]
@mhoemmen thanks for generating the issue. Can you confirm that with this implementation the first #owned+#shared elements of the column Map will have the same local ids of the row Map?

**Comment by mhoemmen** [comment]
@mperego Here is the thing that the implementation would promise: "On every MPI process in the Maps' communicator, all the indices in the domain Map on my process would be the indices that appear first in the column Map on my process."

1. The CrsGraph's Import is computed with respect to the domain Map, not the row Map.  (For many users and probably for you, the row and domain Maps are the same.)

2. The shared indices in the column Map on a process do not have local indices in the domain Map on that process.

**Comment by mperego** [comment]
Oh right, I always forget that the domain map and the row map can be different.
In the second point, are you referring to reachable indices? Otherwise I'm not understanding it.

**Comment by mhoemmen** [comment]
@mperego Only the owned indices in the column Map have corresponding indices in the domain Map on a process.  The shared or reachable indices in the column Map do not exist in the domain Map on that process.  Thus, the shared or reachable indices in the column Map do not have local indices in the domain Map.

**Comment by mperego** [comment]
Would you mind chatting briefly about this when you are in CSRI? Possibly with @csiefer2 as well. Thanks!

**Comment by mhoemmen** [comment]
@mperego If you've never called `fillComplete` on the CrsGraph, and if you didn't give CrsGraph's constructor a column Map, then the CrsGraph does not have a column Map until you call `fillComplete` on it.  If the CrsGraph does not have a column Map, then it does not have local column indices.

When you call `fillComplete`, if the graph does not yet have a column Map, `fillComplete` will make one for you.  `fillComplete` uses the domain Map to build the column Map.  If you do not give `fillComplete` a domain Map (that is, if you write `A.fillComplete()` instead of `A.fillComplete(domainMap, rangeMap)`), then `fillComplete` will use the row Map as the graph's domain Map.  In your case, that is incorrect behavior.  The domain Map must always be one to one.  A Map with owned and shared indices in it is _not_ one to one, in general.

Suppose that you give `CrsGraph::fillComplete` the correct domain Map, that only has the owned indices in it.  Here is what I can say about the column Map that `fillComplete` would construct.

  * Let `W_p` be the ordered set of owned indices on process p.  (W comes from "owned."  O is confusing.)
  * Let `S_p` be the ordered set of shared indices on process p.
  * For any two ordered sets of indices A and B, let `[A, B]` denote their concatenation.

Suppose the following:
  * You construct the row Map so that on each process p, its indices are `[W_p, S_p]`.
  * When you call `fillComplete` on the graph, you give the graph a domain Map whose indices on each process are `W_p`.

Then, `fillComplete` will construct a column Map such that the owned local column indices on each process are the same as the owned local column indices in the _domain_ Map.  However, the column Map includes shared and reachable indices in it, and they are _NOT_ necessarily in the same order as in the row Map you provided.

If you want the row Map and the column Map to use the same local indices, you'll need to construct the column Map yourself and give it to CrsGraph's constructor.

**Comment by mperego** [comment]
Thanks @mhoemmen for the detailed explanation. It makes sense. And sorry for my confusion. I'll chat with @csiefer2 and get back to you.

**Comment by mhoemmen** [comment]
@mperego Short answer: If you want to use local indices for what @csiefer2 calls "Type 2 global assembly" (where you Export from shared to owned manually), then you'll need to construct the column Map yourself and give it to CrsGraph's constructor.
