### ISSUE TITLE
Stokhos: Link errors due to recent Tpetra ETI improvements

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#618]
@trilinos/stokhos @trilinos/tpetra 

Recent Tpetra ETI improvements may have caused link errors in Stokhos, relating to Tpetra::Details::getLocalDiagCopyWithoutOffsetsNotFillComplete.  This affects Albany, as reported by @lxmota .

**Comment by tawiesn** [comment]
It also affects drekar as well...

**Comment by mhoemmen** [comment]
I'm working on it.

**Comment by mhoemmen** [comment]
Hm, I'm stuck, not sure what to do.  E-mailed @etphipp for help.

**Comment by mhoemmen** [comment]
[ 70%] Building CXX object packages/stokhos/src/CMakeFiles/stokhos_tpetra.dir/sacado/kokkos/pce/tpetra/Tpetra_CrsMatrix_UQ_PCE_Serial.cpp.o
In file included from /scratch/prj/Trilinos/Trilinos/packages/stokhos/src/sacado/kokkos/pce/linalg/Kokkos_ArithTraits_UQ_PCE.hpp:46:0,
                 from /scratch/prj/Trilinos/Trilinos/packages/stokhos/src/sacado/kokkos/pce/tpetra/Stokhos_Tpetra_UQ_PCE.hpp:103,
                 from /scratch/prj/Trilinos/Trilinos/packages/stokhos/src/sacado/kokkos/pce/tpetra/Stokhos_Tpetra_ETI_Helpers_UQ_PCE.hpp:43,
                 from /scratch/prj/Trilinos/Trilinos/packages/stokhos/src/sacado/kokkos/pce/tpetra/Tpetra_CrsMatrix_UQ_PCE_Serial.cpp:45:
/scratch/prj/Trilinos/Trilinos/packages/tpetra/kernels/src/Kokkos_ArithTraits.hpp:384:40: warning: inline function ‘static T Kokkos::Details::ArithTraits<T>::zero() [with T = Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 32, Kokkos::Serial> >]’ used but never defined [enabled by default]

**Comment by mhoemmen** [comment]
I'm trying to add the appropriate ETI macros to Tpetra_CrsMatrix_UQ_PCE_$NODE.cpp in Stokhos (where the Sacado ETI happens), but it's not working.

**Comment by mhoemmen** [comment]
Manually pasting the missing instantiations (not the macros) into the .cpp files mentioned above fixed some link errors, but now I get these:
```
../src/libstokhos_tpetra.so.12.9: undefined reference to `Kokkos::Details::ArithTraits<Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 4, Kokkos::Serial> > >::zero()'
../src/libstokhos_tpetra.so.12.9: undefined reference to `Kokkos::Details::ArithTraits<Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 8, Kokkos::OpenMP> > >::zero()'
../src/libstokhos_tpetra.so.12.9: undefined reference to `Kokkos::Details::ArithTraits<Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 32, Kokkos::Serial> > >::zero()'
../src/libstokhos_tpetra.so.12.9: undefined reference to `Kokkos::Details::ArithTraits<Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 32, Kokkos::OpenMP> > >::zero()'
../src/libstokhos_tpetra.so.12.9: undefined reference to `Kokkos::Details::ArithTraits<Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 4, Kokkos::OpenMP> > >::zero()'
../src/libstokhos_tpetra.so.12.9: undefined reference to `Kokkos::Details::ArithTraits<Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::Serial> > >::zero()'
../src/libstokhos_tpetra.so.12.9: undefined reference to `Kokkos::Details::ArithTraits<Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 8, Kokkos::Serial> > >::zero()'
../src/libstokhos_tpetra.so.12.9: undefined reference to `Kokkos::Details::ArithTraits<Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::OpenMP> > >::zero()'
```
If those ArithTraits specializations live in a header file somewhere, I'll need to include that header file.

**Comment by mhoemmen** [comment]
It looks like those ArithTraits specializations live in the following header file:

Kokkos_ArithTraits_MP_Vector.hpp

**Comment by mhoemmen** [comment]
Hm, including that header file worked.  Yay!  Let me now see if I can get the macros to work.  Otherwise, I can still fix this, but it will be an ugly temporary solution that @etphipp will have to clean up later.

**Comment by mhoemmen** [comment]
I'm running tests for the temporary fix.  Couldn't figure out how to make the macros work (they seemed to have no effect), so I just pasted in the required instantiations.

**Comment by mhoemmen** [comment]
hold on, just making sure everything builds right...

**Comment by mhoemmen** [comment]
Just pushed a temporary fix.

**Comment by etphipp** [comment]
I just pushed a permanent fix for this.  A new entry was needed in Stokhos' list of Tpetra classes to instantiate.

Thanks Mark for addressing this so quickly.

**Comment by mhoemmen** [comment]
> Thanks Mark for addressing this so quickly.

Thanks for adding the permanent fix!
