### ISSUE TITLE
Fix EMPIRE configuration of Trilinos where gtest is not installed

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#6203]
CC: @jmgate, @rppawlo 

As reported in https://github.com/trilinos/Trilinos/pull/6105#issuecomment-548389753, it would seem that after the merge of PR #6105 that the EMPIRE configuration of Trilinos is now broken where:

```
cmake \
  -G Ninja \
  -D Trilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake,cmake/std/atdm/apps/empire/EMPIRETrilinosEnables.cmake \
  -D Panzer_ENABLE_EXAMPLES:BOOL=ON \
  -D Panzer_ENABLE_TESTS:BOOL=ON \
  -D CMAKE_INSTALL_PREFIX=/path/to/install/dir \
  /path/to/Trilinos
```

results in the configure error:

```
CMake Error: install(EXPORT "STKUnit_test_utils" ...) includes target "stk_mesh_fixtures" which requires target "stk_ngp_test" that is not in the export set.
CMake Error: install(EXPORT "STKUnit_test_utils" ...) includes target "stk_mesh_fixtures" which requires target "gtest" that is not in the export set.
```

This is likely due to the enable of Percept triggering the enable of a new STK subpackage that installable libraries that depend on the install of the 'gtest' library the the EMPIRE Trilinos configuration does not depend on.

The fix should be simple.   Either this new subpackage can be disabled or the install of this library can be disabled when gtest is not being installed.

I will reproduce and fix.

**Comment by bartlettroscoe** [comment]
@jmgate,

FYI: the fix should be in PR #6204 

I am currently testing against EMPIRE with:

```
$ cd BUILD/
$ ../empire-tril-build-test-scripts/empire-tril-build-test.sh -p ../EMPIRE -b gnu-opt -a 
```

and will post to PR #6204 once that is complete.

**Comment by jmgate** [comment]
Thanks for the quick turn-around, @bartlettroscoe.

**Comment by bartlettroscoe** [comment]
I verified this works for EMPIRE in https://github.com/trilinos/Trilinos/pull/6204#issuecomment-548615503 so I am closing this as complete.

**Comment by bartlettroscoe** [comment]
CC: @alanw0 

FYI:  I also patched the Sierra.base repo stk version for this changes with the Sierra.base commit:

```
commit 5ccd636c72c99d031b98a897a4f90328c8c45b06
Author: Roscoe A. Bartlett <rabartl@sandia.gov>
Date:   Thu Oct 31 09:03:15 2019 -0600

    Fix the EMPIRE configuration of Trilinos that does not install gtest libs (#6203)

diff --git a/stk/stk_unit_test_utils/stk_unit_test_utils/stk_mesh_fixtures/CMakeLists.txt b/stk/stk_unit_test_utils/stk_unit_test_utils/stk_mesh_fixtures/CMakeLists.txt
index 4586005..f7a5592 100644
--- a/stk/stk_unit_test_utils/stk_unit_test_utils/stk_mesh_fixtures/CMakeLists.txt
+++ b/stk/stk_unit_test_utils/stk_unit_test_utils/stk_mesh_fixtures/CMakeLists.txt
@@ -67,6 +67,7 @@ TRIBITS_ADD_LIBRARY(
   DEPLIBS
   NOINSTALLHEADERS ${HEADERS}
   SOURCES ${SOURCES}
+  ${Gtest_NO_INSTALL_LIB_OR_HEADERS_ARG}
   )
 
 INSTALL(FILES ${HEADERS} DESTINATION
```

Therefore, the next snapshot of STK to Trilinos will not write over this change.

**Comment by alanw0** [comment]
@bartlettroscoe thanks for also patching it in sierra, that helps a lot.
