### ISSUE TITLE
Kokkos_View.hpp error: declaration of 'prop' shadows a previous local

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#6207]
## Bug Report
@trilinos/kokkos 

### Description

This is from @Mark-E-Hamilton , who originally posted it [here](https://github.com/trilinos/trilinos.github.io/issues/20).

> When building Sierra with our (slightly out-of-date) version of Trilinos and using gcc-8.3 we get shadow errors from Kokkos_View.hpp, as shown below. (Trilinos itself built without errors.) We are doing this build to prepare for building Sierra on Astra.
> 
> I'm going to attempt to resolve this error in our version of Trilinos (since we are not quite ready for another integration yet) but thought it might need to be addressed in the code base.

```
/projects/sierra/linux_rh7/nightly/cee_gcc_8_openmpi_4_master/objs/tpls/trilinos_tpls/a186395cd481bacf/include/Kokkos_View.hpp:2080:18: error: declaration of 'prop' shadows a previous local [-Werror=shadow]
       alloc_prop input_prop( arg_prop );
                  ^~~~
In file included from /projects/sierra/linux_rh7/nightly/cee_gcc_8_openmpi_4_master/objs/tpls/trilinos_tpls/a186395cd481bacf/include/Kokkos_Parallel.hpp:52,
...
/Aria_CreateGenericPointExpression.h:12,
                 from /sierra/dev/nightly/Sierra.code.master/aria/src/Aria_EQ_Description_CVFEM_Impl.C:6:
/projects/sierra/linux_rh7/nightly/cee_gcc_8_openmpi_4_master/objs/tpls/trilinos_tpls/a186395cd481bacf/include/Kokkos_View.hpp:273:48: note: shadowed declaration is here
   typedef ViewTraits< void , Properties ... >  prop ;
                                                ^~~~
```

My response:
> How is it that `input_prop` shadows `prop`?  This doesn't quite look like the same code we talked about over the phone.  More importantly, I think you meant to file this issue here: `github.com/trilinos/Trilinos/issues`.  Let me see if it's been fixed in new Trilinos or new Kokkos.

### Steps to Reproduce

Use Sierra's current version of Trilinos.

**Comment by mhoemmen** [comment]
It looks like this has been fixed in Trilinos:master: https://github.com/trilinos/Trilinos/blob/e7759b8947687551cefe54b742000864d689ffd9/packages/kokkos/core/src/Kokkos_View.hpp#L2114

**Comment by Mark-E-Hamilton** [comment]
Sorry, Mark, I pasted the wrong error message. The original code had prop at line 2080 which shadowed prop. I changed it to test it; I can't explain why it was still complaining after I changed it. Thanks for letting me know it was fixed.

**Comment by mhoemmen** [comment]
This has been fixed in Trilinos:master, so I'll close the issue.  Thanks for reporting!
