### ISSUE TITLE
Framework:  tests might have run, but there are no results on dashboard

### ISSUE THREAD

**Issue by jhux2** [trilinos/Trilinos#6210]
## Question
@trilinos/framework 

In the following nightly testing, there is no indication that the tests have run, or if they have, whether they passed.  The configuration output indicates that tests are enabled, and I can run them from the test build by hand.

Any idea why the tests aren't running and/or the results aren't posting?

https://testing-dev.sandia.gov/cdash/index.php?project=Trilinos&parentid=4989676

**Comment by william76** [comment]
@jhux2 
Your link is to testing-dev.sandia.gov ... I'm seeing results at testing.sandia.gov:
- Trilinos: https://testing.sandia.gov/cdash/index.php?project=Trilinos
- Rocketman: https://testing.sandia.gov/cdash/index.php?project=Trilinos&parentid=5835299

Do you see results that you're looking for on testing.sandia.gov?

@trilinos/framework 
Were all the issues from last week with CDash resolved?  It looks like testing.sandia.gov is getting PR data and tests.
Are we still using testing-dev?

**Comment by jhux2** [comment]
> Do you see results that you're looking for on testing.sandia.gov?

No:

https://testing.sandia.gov/cdash/index.php?project=Trilinos&filtercount=2&showfilters=1&filtercombine=and&field1=site&compare1=63&value1=rocketman&field2=buildname&compare2=63&value2=DEPRECATED

**Comment by prwolfe** [comment]
I modified the url just a bit to search a larger date range (https://testing.sandia.gov/cdash/index.php?project=Trilinos&filtercount=3&showfilters=1&filtercombine=and&field1=site&compare1=63&value1=rocketman&field2=buildname&compare2=63&value2=DEPRECATED&field3=buildstarttime&compare3=83&value3=October%201st) and I see results up to November 1st. Even looking at the history on testing-dev it seems that the tests are dropping in and out going back as far as October 12th.  I see a lot of builds that do and the inconsistency makes me wonder if the ctest process was killed. You are using the main tributes drivers so I don't expect any instability (the last merge was back in September.)

**Comment by prwolfe** [comment]
That looks like what I was seeing for previous days.  You will need to dig into the log files to see what is really happening.

**Comment by jhux2** [comment]
Closing as won't fix.
