### ISSUE TITLE
Disable deprecated code in ATDM Trilinos builds slated to be removed in Trilinos 13.0

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#6217]
CC: @bathmatt, @jmgate, @rppawlo 

Turn off all Trilinos deprecated code slated to be removed in Trilinos 13.0 release.  The full set of deprecated settings are now being used in EMPIRE as shown in:

* https://cee-gitlab.sandia.gov/EM-Plasma/BuildScripts/merge_requests/232/diffs

which include:

```
-D KOKKOS_ENABLE_DEPRECATED_CODE=OFF \
-D Tpetra_ENABLE_DEPRECATED_CODE=OFF  \
-D Belos_HIDE_DEPRECATED_CODE=ON  \
-D Epetra_HIDE_DEPRECATED_CODE=ON  \
-D Ifpack2_HIDE_DEPRECATED_CODE=ON \
-D Ifpack2_ENABLE_DEPRECATED_CODE=OFF \
-D MueLu_ENABLE_DEPRECATED_CODE=OFF \
-D Panzer_HIDE_DEPRECATED_CODE=ON  \
-D Phalanx_HIDE_DEPRECATED_CODE=ON \
-D RTop_HIDE_DEPRECATED_CODE=ON \
-D STK_HIDE_DEPRECATED_CODE=ON \
-D Teuchos_HIDE_DEPRECATED_CODE=ON\
-D Thyra_HIDE_DEPRECATED_CODE=ON \
-D Trios_HIDE_DEPRECATED_CODE=ON \
```

The ATDM Dev Env & Tools Issue for this is:

* https://sems-atlassian-srn.sandia.gov/browse/ATDV-243

**SUB-TASKS:**

* Create branch '6427-hide-deprecated-code' and add deprecated settings to `cmake/std/atdm/ATDMDevEnvSettings.cmake` ...
* Test updated ATDM Trilinos builds and test suite for a few different builds (cee-rhel6 clang & gnu, waterman cuda, sems-rhel7 gnu) ...
* Test SPARC against updated configuration (clang, gnu, and cuda) ...
* ???

**Comment by bartlettroscoe** [comment]
CC: @kddevin, @jmgate 

@rppawlo, @bathmatt,

What about these other deprecation that @kddevin announced in the below email (and detailed in [trilinos_deprecations.pdf](https://github.com/trilinos/Trilinos/files/3802251/trilinos_deprecations.pdf))?  This deprecated code is supposed to start getting removed starting Nov. 15!!!!!

----

From: Trilinos-Users <trilinos-users-bounces@trilinos.org> On Behalf Of Devine, Karen D
Sent: Tuesday, October 22, 2019 7:46 PM
To: tpetra-developers@software.sandia.gov; tpetra-announce@software.sandia.gov; trilinos-announce@trilinos.org; trilinos-users@trilinos.org; trilinos-developers@trilinos.org
Subject: [EXTERNAL] [Trilinos-Users] Trilinos code deprecation announcement

Trilinos is announcing the deprecation of 37 features in 16 packages.  Full details of the deprecated features, including mitigations, are in the attached document.  All deprecated features have produced warnings in Trilinos builds since Trilinos v12.16.

The expected deprecation schedule is
•	November 15, 2019:  Trilinos developers may begin removing deprecated code from Trilinos' develop branch
•	December 4, 2019:  Trilinos release v13
Users can test their applications now without deprecated code by adding the following configuration flags to their Trilinos builds:

```
 -D KOKKOS_ENABLE_DEPRECATED_CODE=OFF \
 -D Tpetra_ENABLE_DEPRECATED_CODE=OFF  \
 -D Belos_HIDE_DEPRECATED_CODE=ON  \
 -D Epetra_HIDE_DEPRECATED_CODE=ON  \
 -D Ifpack2_HIDE_DEPRECATED_CODE=ON \
 -D Ifpack2_ENABLE_DEPRECATED_CODE=OFF \
 -D MueLu_ENABLE_DEPRECATED_CODE=OFF \
 -D Panzer_HIDE_DEPRECATED_CODE=ON  \
 -D Phalanx_HIDE_DEPRECATED_CODE=ON \
 -D RTop_HIDE_DEPRECATED_CODE=ON \
 -D STK_HIDE_DEPRECATED_CODE=ON \
 -D Teuchos_HIDE_DEPRECATED_CODE=ON\
 -D Thyra_HIDE_DEPRECATED_CODE=ON \
 -D Claps_HIDE_DEPRECATED_CODE=ON \
 -D GlobiPack_HIDE_DEPRECATED_CODE=ON \
 -D OptiPack_HIDE_DEPRECATED_CODE=ON \
 -D Trios_HIDE_DEPRECATED_CODE=ON \
```

Concerns should be shared with Trilinos product leaders (Karen Devine, Roger Pawlowski, Mauro Perego, Siva Rajamanickam, and Jim Willenbring) and Trilinos product managers (Michael Wolf, Dena Vigil).

**Comment by rppawlo** [comment]
Hi Ross,

We can not turn off trilinos deprecated code in atdm builds just yet (kokkos deprecated code is now to turn off). @etphipp verified sparc is working without deprecated code. We have pushed changes on empire side, but there are two runtime failures occurring. These issues are blocking:

https://github.com/trilinos/Trilinos/issues/6163

https://github.com/trilinos/Trilinos/issues/6149

once these are finished we should be good to go.

**Comment by bartlettroscoe** [comment]
CC: @kddevin, @rppawlo 

In:

* https://cee-gitlab.sandia.gov/EM-Plasma/BuildScripts/issues/184

@bathmatt requested that we hold off on turning off deprecated code in the ATDM Trilinos builds until after Dec 15.

@william76, @ZUUL42,

But we still need to set up a Trilinos PR build that disables deprecated code so that Trilinos 'develop' does not backslide.

**Comment by mhoemmen** [comment]
@bartlettroscoe wrote:
> But we still need to set up a Trilinos PR build that disables deprecated code so that Trilinos 'develop' does not backslide.

Please -- I cannot emphasize how critical this is, @trilinos/framework .

**Comment by bartlettroscoe** [comment]
FYI: I removed:

```
 -D Claps_HIDE_DEPRECATED_CODE=ON \
 -D GlobiPack_HIDE_DEPRECATED_CODE=ON \
 -D OptiPack_HIDE_DEPRECATED_CODE=ON \
```

because those packages are not even in Trilinos anymore.

**Comment by bartlettroscoe** [comment]
Seems that SPARC's and EMPIRE's Trilinos configurations recently set all of these options and disabled all of this deprecated code.  Therefore, we might as well do so for the ATDM Trilinos builds too.  But note that none of the Trilinos PR builds disable any of this code yet (see #6347).  Therefore, we should expect updates that pass the PR builds to break the ATDM Trilinos builds and break the usage of Trilinos by the ATDM APPs.

I will post the PR for this but will not merge this until after the ECP Annual meeting in case this triggers a bunch of new test failures.

**Comment by bartlettroscoe** [comment]
Just waiting for PR #6730 to be merged and then watch the ATDM Trilinos builds ...

**Comment by bartlettroscoe** [comment]
With EMPIRE having updated Trilinos 'develop' as recently as:

```
*   ff9e590 "Merge 'trilinos/Trilinos:develop' (2639a33) into 'EM-Plasma/Trilinos:develop' (4b63fe4)."
|\  Author: Jenkins Pipeline <jenkins@jenkins-srn.sandia.gov>
| | Date:   Mon Feb 24 06:21:23 2020 -0700 (71 minutes ago)
| |     
| *   2639a33 "Merge pull request #5714 from Tech-XCorp/amesos2GPU-Tacho"
| |\  Author: Michel de Messieres <michel@demessieres.com>
| | | Date:   Sun Feb 23 06:08:35 2020 -0500 (27 hours ago)
```

and with SPARC Trilinos Integration building clean as of testing day 2020-02-21 (see [SPAR-767] and [SPARC CDash on 2020-02-24](https://sems-atlassian-srn.sandia.gov/browse/SPAR-767) [here](https://sems-cdash-srn.sandia.gov/sparc/index.php?project=SPARC&date=2020-02-24&filtercount=1&showfilters=1&field1=groupname&compare1=61&value1=Trilinos%20Integration)), I SPARC and EMPIRE are good with the disable of deprecated code in Trilinos.

Closing this Issue as complete.
