### ISSUE TITLE
Set to Epetra_FEVector with Epetra_BlockMap

### ISSUE THREAD

**Issue by RATATATO** [trilinos/Trilinos#622]
It seems not to work Epetra_FEVector::ReplaceGlobalValues on Epetra_FEVector with Epetra_BlockMap.

Epetra_FEVector::ReplaceGlobalValues (and Epetra_FEVector::SumIntoGlobalValues)
sets only the head of a block.

1. It is a bug? or
2. It is correct, so we should not use Epetra_BlockMap to Epetra_FEVector?

An example is here:
https://gist.github.com/RATATATO/457f25c1e5960632378e7559cfeb0225

The output is as the follow:
```
ReplaceGlobalValues: 1 0 0 2 0 0 
ReplaceGlobalValue: 1 2 4 8 16 32 
```

**Comment by mhoemmen** [comment]
> It is correct, so we should not use Epetra_BlockMap to Epetra_FEVector?

I'm not sure if this is correct behavior, but it is the behavior that I expect.  As a work-around, you could just convert your global indices to local indices, and access the Vector's data directly.

**Comment by RATATATO** [comment]
Thank you for your reply.

It is confused one C++ programmer that
- Epetra_FEVector with Epetra_Map is a 1D vector, but it with Epetra_BlockMap is a multidimensional vector,
- Its members (Epetra_FEVector::ReplaceGlobalValues, Epetra_FEVector::SumIntoGlobalValues, ...) are only for a 1D vector.
