### ISSUE TITLE
Kokkos: Cannot build with CUDA using Intel Compiler

### ISSUE THREAD

**Issue by BrettDong** [trilinos/Trilinos#6221]
## Question
@trilinos/kokkos

I tried to build Trilinos with Intel MPI, CUDA and Intel Compiler (set `$I_MPI_CXX` environment variable to point to `nvcc_wrapper` and edited `nvcc_wrapper` script to use `icpc` as C++ compiler), then I got the following compile errors on `nvcc` not recognizing Intel Compiler intrinsics:
```
~/trilinos/packages/kokkos-kernels/src/common/KokkosKernels_BitUtils.hpp(91): error: identifier "_popcnt64" is undefine
d                                                                                   
                                                          
~/trilinos/packages/kokkos-kernels/src/common/KokkosKernels_BitUtils.hpp(96): error: identifier "_popcnt64" is undefin$
d                                                                                         

~/trilinos/packages/kokkos-kernels/src/common/KokkosKernels_BitUtils.hpp(106): error: identifier "_popcnt64" is undefin
ed

~/trilinos/packages/kokkos-kernels/src/common/KokkosKernels_BitUtils.hpp(111): error: identifier "_popcnt64" is undefin
ed
```

Meanwhile I got hundreds of warnings about `__host__` and `__device__` annotation but I don't know if this is related:
```
~/trilinos/packages/kokkos/core/src/Cuda/Kokkos_Cuda_UniqueToken.hpp(114): warning: __device__ annotation is ignored on a function("UniqueToken") that is explicitly defaulted on its first declaration                                                                                  

~/trilinos/packages/kokkos/core/src/Cuda/Kokkos_Cuda_UniqueToken.hpp(114): warning: __host__ annotation is ignored on a function("UniqueToken") that is explicitly defaulted on its first declaration
```

I was trying to build Trilinos 12.14.1 on Ubuntu 18.04.3 LTS, Intel Compiler version 19.0.5.281, CUDA 10.1.168.

#4379 also reports failure to build Trilinos with CUDA and Intel Compiler but the error message is different.

**Comment by BrettDong** [comment]
The exact same issue persists in master version.

**Comment by mhoemmen** [comment]
@trilinos/kokkos 

I've never actually tried putting together the Intel compiler with nvcc.  The Kokkos team might have some comments on that.  Have you tried gcc + nvcc with OpenMPI?

**Comment by BrettDong** [comment]
gcc+cuda+openmpi is okay.
