### ISSUE TITLE
Belos: inverting 3x3 matrix fails with "One or more of the current implicit residual norms is NaN"

### ISSUE THREAD

**Issue by jwuttke** [trilinos/Trilinos#6224]
## Bug Report
@trilinos/\belos

### Description
To demonstrate and test the sparse matrix solver, I wrote a short program that solves small non-sparse equation systems. For some input, it fails with "One or more of the current implicit residual norms is NaN".

### Steps to Reproduce

    class Options {
    public:
    int whichSolver = 1; // 0:direct, 1:iterative
    double solverTolerance = 6e-8;
    double collocTolerance = 1e-5;
    int nzStart = 8;
    int nzStep = 4;
    };
    #include <BelosBlockGmresSolMgr.hpp>
    #include <BelosEpetraAdapter.hpp>
    #include <BelosLinearProblem.hpp>
    #include <Epetra_CrsMatrix.h>
    #include <Epetra_MultiVector.h>
    #include <Epetra_Vector.h>
    #include <Ifpack.h>
    #include <Ifpack_AdditiveSchwarz.h>
    #include <Teuchos_ParameterList.hpp>

    using Teuchos::RCP;

    namespace {

    Teuchos::ParameterList my_solver_parameters(const Options& opts)
    {
    Teuchos::ParameterList ret;
    ret.set("Maximum Iterations", 200); // Maximum number of iterations allowed
    ret.set("Convergence Tolerance", opts.solverTolerance);
    using namespace Belos;
    ret.set("Verbosity", Errors /+Warnings+FinalSummary/); // TimingDetails required MPI
    return ret;
    }

    } // namespace

    //! Returns the solution x of the equation system L*x=RHS.
    //!
    //! Usage is demonstrated by unit_tests/test009_solver.cpp.

    Epetra_Vector solve(Epetra_CrsMatrix* L, Epetra_Vector* RHS, const Options& opts)
    {
    static Clock clock{"solver", 4};
    clock.report("elsewhere");

    // Preconditioner parameters.
    Teuchos::ParameterList preconditioner_params;
    preconditioner_params.set("fact: level-of-fill", 0); // ILU(0)
    preconditioner_params.set("fact: drop tolerance", 1e-5);

    // Construct the preconditioner.
    RCP<Ifpack_Preconditioner> Prec{Ifpack{}.Create("ILU", L, 1)};
    assert(Prec != Teuchos::null);
    assert(!Prec->SetParameters(preconditioner_params));
    assert(!Prec->Initialize());
    clock.report("setup1");
    assert(!Prec->Compute()); // <--- most time is spent here
    clock.report("compute P");

    // Setup the linear problem, consisting of the numeric input and preconditioner.
    RCP<Epetra_Vector> LHS{new Epetra_Vector{L->OperatorDomainMap(), true}};
    RCP<Belos::LinearProblem<double, Epetra_MultiVector, Epetra_Operator>> problem{
        new Belos::LinearProblem<double, Epetra_MultiVector, Epetra_Operator>{
            RCP<Epetra_CrsMatrix>{L}, LHS, RCP<Epetra_Vector>{RHS}}};
    RCP<Belos::EpetraPrecOp> PrecOp{new Belos::EpetraPrecOp{Prec}};
    problem->setRightPrec(PrecOp);
    assert(problem->setProblem());

    // Iterative solve.
    RCP<Teuchos::ParameterList> solverParams{
        new Teuchos::ParameterList{my_solver_parameters(opts)}};
    Belos::BlockGmresSolMgr<double, Epetra_MultiVector, Epetra_Operator> belosSolver{
        problem, solverParams};
    clock.report("setup2");
    auto ret = belosSolver.solve(); // <--- much time is spent here
    clock.report("solve");
    // print_solution(*LHS);
    if (ret != Belos::Converged) {
        std::cerr << "not converged\n";
        exit(1);
    }

    return *LHS;

    }

    #include "catch.hpp"
    #include "options.h"
    #include "solver.h"

    #include <Epetra_SerialComm.h>
    #include <Epetra_CrsMatrix.h>
    #include <Epetra_Vector.h>
    #include

    using std::vector;

    void run(const vector<vector>& A, const vector& b, const double tol)
    {
    // For readability of the initializer, A[j] is a row vector.

    int n = b.size();
    assert(A.size()==n);
    for( const vector<double>& a: A)
        assert(a.size()==n);

    // Compute LHS y=Ab:
    vector<double> y(n, 0.);
    for (int j=0; j<n; ++j) // rows
        for (int i=0; i<n; ++i) // columns
            y[j] += A[j][i] * b[i];

    // Print the problem
    printf("matrix A / lhs b / rhs y\n");
    for (int j=0; j<n; ++j) { // rows
        for (int i=0; i<n; ++i) // columns
            printf(" %g", A[j][i]);
        printf("  %g  %g\n", b[j], y[j]);
    }
    printf("\n");

    // Copy A to sparse matrix L:
    Epetra_SerialComm comm;
    auto * L = new Epetra_CrsMatrix{Copy, Epetra_Map{n, 0, comm}, 0};
    for (int j=0; j<n; ++j) {
        vector<int> idx;
        vector<double> val;
        for (int i=0; i<n; ++i) {
            if (A[j][i]) {
                idx.push_back(i);
                val.push_back(A[j][i]);
            }
        }
        L->InsertGlobalValues(j, idx.size(), &val[0], &idx[0]);
    }
    L->FillComplete();

    // set RHS = y:
    auto* RHS = new Epetra_Vector{L->OperatorRangeMap()};
    for (int i=0; i<n; ++i)
        (*RHS)[i] = y[i];

    // Solve Lx=y:
    Epetra_Vector x = solve(L, RHS, {});

    // Print result
    printf("solution x (expected / computed / abs_diff):\n");
    for (int i=0; i<n; ++i) {
        printf("  %g %g %g\n", b[i], x[i], std::abs(b[i]-x[i]));
        CHECK(std::abs(b[i]-x[i]) < tol);
    }
    printf("\n");

    }

    TEST_CASE("Solver")
    {
    run({{1., 1.},{4., 1.}}, {2., 3.}, 1e-14); // passes
    run({{1., 0., 3.}, {0., 5., 6.}, {0., 8., 9.}}, {1.e3, 1., 1e-3}, 1e-10); // passes
    run({{1., 2., 3.}, {4., 5., 6.}, {7., 8., 9.}}, {0., -10., 10.}, 1e-10); // fails
    }

**Comment by jwuttke** [comment]
Thank you very much for this analysis, Heidi. So I'll close this bug. I wonder, however, whether the error message isn't too much from an internal perspective, and ought to be reworded for the benefit of nonexpert users?

**Comment by hkthorn** [comment]
@jwuttke Thanks for the feedback, that is pretty specific output that could be more informative!

**Comment by jwuttke** [comment]
Just for the archive, in integer arithmetics my matrix is singular. Shame on me.
