### ISSUE TITLE
ML:  MIS Aggregation QR Factorization Error

### ISSUE THREAD

**Issue by dlkarnit** [trilinos/Trilinos#6229]
## Bug Report
@trilinos/\<ML\>

### Description
Error reported by ML:

<code>On entry to "DGEQRF" parameter number  4 had an illegal value</code>

I believe we have tracked this down to a QR factorization in the MIS aggregation. Where it tries to perform a QR factorization on a 0x0 matrix. We would like feedback on our proposed change to identify if it is an acceptable fix for us to deploy in our use of Trilinos.

Proposed patch:
<pre>
Index: v12.10.1-mpich-3-2-1/packages/ml/src/Coarsen/ml_agg_MIS.c
===================================================================
--- v12.10.1-mpich-3-2-1/packages/ml/src/Coarsen/ml_agg_MIS.c  (revision 212)
+++ v12.10.1-mpich-3-2-1/packages/ml/src/Coarsen/ml_agg_MIS.c  (working copy)
@@ -1446,6 +1446,8 @@
 
    for (i = 0; i < aggr_count; i++)
    {
+      if (aggr_cnt_array[i] == 0) continue;
+
       /* ---------------------------------------------------------- */
       /* set up the matrix we want to decompose into Q and R:       */
       /* ---------------------------------------------------------- */
@@ -1663,7 +1665,7 @@
       /* ---------------------------------------------------------- */
       /* now calculate QR using an LAPACK routine                   */
       /* ---------------------------------------------------------- */
-      if (aggr_cnt_array[i] >= nullspace_dim) {
+      if (aggr_cnt_array[i] >= nullspace_dim && aggr_cnt_array[i] > 0) {
 
         DGEQRF_F77(&(aggr_cnt_array[i]), &nullspace_dim, qr_tmp,
                   &(aggr_cnt_array[i]), tmp_vect, work, &lwork, &info);
</pre>

**Comment by dlkarnit** [comment]
More info from the aggregation output from ML when generating the hierarchy in our case:

<pre>
------------------------------------------------------------------------------
Using `cg' for eigen-computations
*** 
*** ML_Epetra::MultiLevelPreconditioner
***
Matrix has 912 rows and 92370 nonzeros, distributed over 4 process(es)
The linear system matrix is an Epetra_CrsMatrix
** Leaving column map of Main linear system matrix unchanged
Default values for `SA'
Maximum number of levels = 10
Using increasing levels. Finest level  = 0, coarsest level = 9
Number of applications of the ML cycle = 1
Number of PDE equations = 1
Aggregation threshold = 0
Max coarse size = 128
R and P smoothing : P = (I-\omega A) P_t, R = P^T
R and P smoothing : \omega = 0/lambda_max
Null space type      = default (constants)
Null space dimension = 1
-----------------------------------------------------------------------
ML_Gen_MultiLevelHierarchy (level 0) : Gen Restriction and Prolongator
-----------------------------------------------------------------------
ML_Aggregate_Coarsen (level 0) begins
ML_Aggregate_CoarsenMIS : current level = 0
ML_Aggregate_CoarsenMIS : current eps = 0.000000e+00
Aggregation(MIS) : Total nonzeros = 92370 (Nrows=912)
Aggregation(MIS) : Phase 1 - nodes aggregated = 359 
Aggregation(MIS) : Phase 1 - total aggregates = 50
Aggregation(MIS) : Phase 2a- additional aggregates = 3
Aggregation(MIS) : Phase 2 - total aggregates = 53
Aggregation(MIS) : Phase 2 - boundary nodes   = 7
Aggregation(MIS) : Phase 3 - leftovers = 0 and singletons = 0
Communicating phase 2/3 info
Calling ML_Operator_UnAmalgamateAndDropWeak
Aggregation(MIS) : QR factorization - too small aggregates = 0
</pre>

I'm confused here as to why under the Uncoupled-MIS hybrid scheme the aggregator would attempt to use MIS at all for such a small number of processes.

**Comment by jhux2** [comment]
@trilinos/ml 
@dlkarnit In the UC/MIS case, the purpose of MIS is to allow aggregates to span processes to keep a good coarsening rate.  Otherwise, the aggregation would stagnate because UC only considers local connections.  In the example you posted, there are 228 DOFs per rank, which I suspect is below the threshold at which MIS kicks in.

**Comment by jhux2** [comment]
@rstumin

**Comment by dlkarnit** [comment]
@jhux2 
Thank you, that makes sense. I was confused by the ML user guide which claims MIS is only used when the aggregation reaches 1 aggregate per process. But it looks like the implementation triggers the switch over at around 250 dofs per process.

Regarding our patch to skip the QR factorization error for 0-sized aggregates. Do you think there is much risk in our proposed patch?

**Comment by jhux2** [comment]
@dlkarnit I find it strange that there are zero-sized aggregates.  Do you know why the size is zero?
