### ISSUE TITLE
Declaration errors when compiling PyTrilinos

### ISSUE THREAD

**Issue by gpkc** [trilinos/Trilinos#623]
I'm trying to compile PyTrilinos, but I can't figure out how to get rid of this error:
```
[ 93%] Building CXX object packages/PyTrilinos/src/CMakeFiles/pytrilinos.dir/PyTrilinos_PythonException.cpp.o
.../Trilinos/packages/PyTrilinos/src/PyTrilinos_PythonException.cpp: In constructor ‘PyTrilinos::PythonException::PythonException()’:
.../Trilinos/packages/PyTrilinos/src/PyTrilinos_PythonException.cpp:65:64: error: ‘PyString_FromString’ was not declared in this scope
       "Please contact a PyTrilinos developer with the details.");
                                                                ^
.../Trilinos/packages/PyTrilinos/src/PyTrilinos_PythonException.cpp:72:41: error: ‘PyString_AsString’ was not declared in this scope
   errorMsg       = PyString_AsString(msg);
                                         ^
```
Anyone has suggestion on how to fix this?

**Comment by ambrad** [comment]
Directing this to @wfspotz , the PyTrilinos expert.

**Comment by gregvw** [comment]
Are you using Python 3 by any chance? If so, that could be the problem. PyString_FromString is defined for Python 2, but Python 3 has moved to unicode.


Greg



________________________________

**Comment by gpkc** [comment]
I tried using Python3 at first, but then I noticed that the cmake function FindPythonInterp uses Python2 syntax:
```
${PYTHON_EXECUTABLE} -c "import sys; print(sys.version.split()[0])"
```
So I'm using, or trying to use, Python2. I'm not sure if Trilinos is somehow using my Python3 dev files, though. I'll try to check this out.

**Comment by gpkc** [comment]
NVM, this was the problem. The PYTHON_INCLUDE_DIR and PYTHON_LIBRARY config variables were pointing to my python3 dirs, while the PYTHON_EXECUTABLE config variable were pointing to the correct binary. The project is now building properly.
Thanks.
