### ISSUE TITLE
MueLu: Inconsistent names in Teuchos::TimeMonitor summary

### ISSUE THREAD

**Issue by mayrmt** [trilinos/Trilinos#6241]
## Bug Report
@trilinos/muelu 

### Description

For the "scaling" and "structured" driver, the timer names in the time monitor summary are inconsistenst, which poses some intricacies for postprocessing of timing results via scripts.

For Laplace problems, the Galeri matrix type is included into the time name. For others, e.g. elasticity, it's not. This makes scripting of output postprocessing difficult.

Here are the detailed examples:
- Considering the driver `packages/muelu/test/scaling/MueLu_Driver.exe`: 
    - For `--matrixType=Laplace3D`, an exemplary line of the time summary starts with `MueLu: Laplace3D: UncoupledAggregationFactory: Build (level=0)`
    - For `--matrixType=Elasticity3D`, an exemplary line of the time summary starts with `MueLu: UncoupledAggregationFactory: Build (level=0)`
- Considering the driver `packages/muelu/test/structured/MueLu_Structured.exe`: 
    - For `--matrixType=Laplace3D`, an exemplary line of the time summary starts with `MueLu: Laplace3D: StructuredAggregationFactory: Build (level=0)`
    - For `--matrixType=Elasticity3D`, an exemplary line of the time summary starts with `MueLu: StructuredAggregationFactory: Build (level=0)`

### Steps to Reproduce
1. SHA1:  5d2a1c6623869b4923e2e0f5334347c22dbbc460
1. Run the MueLu scaling/structured drivers for Laplace and Elasticity

**Comment by mayrmt** [comment]
@jhux2 @lucbv I suggest to just remove the matrix type string from the timer summary. What do you think? Or is there a particular reason for the current behavior, that I just didn't see, yet?

**Comment by mayrmt** [comment]
@jhux2 @lucbv Or we could just include the matrix type into the timer names consistently for every matrix type.

**Comment by jhux2** [comment]
@mayrmt I don't see a good reason to have the matrix type in the timer.

**Comment by cgcgcg** [comment]
You can get rid of the matrix name in the timer by not naming the matrix. I do want to keep the current timer behavior for RefMaxwell, where we are using 2 hierarchies.

**Comment by jhux2** [comment]
> I do want to keep the current timer behavior for RefMaxwell, where we are using 2 hierarchies.

Yes, but there you prepend the Hierarchy name, right?

**Comment by cgcgcg** [comment]
@jhux2 No, I think I am using the same mechanism. We could change Galeri to not setting object labels, which would be pretty easy to do.

**Comment by jhux2** [comment]
> No, I think I am using the same mechanism. We could change Galeri to not setting object labels, which would be pretty easy to do.

I agree.

**Comment by mayrmt** [comment]
I would also be fine to consistently insert the matrix type into the timer name for _all_ Galeri Problem types. Then, processing timers via scripts works nicely as well.

**Comment by mayrmt** [comment]
I can't fine the piece of code, that inserts the matrix type into the timer name. Can you point me to it? Thanks!

**Comment by cgcgcg** [comment]
@mayrmt  Have a look here:
 https://github.com/trilinos/Trilinos/blob/343e2925d860f6958f88b26e2d240c11c44384ed/packages/galeri/src-xpetra/Galeri_StencilProblems.hpp#L96

**Comment by cgcgcg** [comment]
@mayrmt Should be fixed, please reopen if there are still issues.
