### ISSUE TITLE
Ifpack2: Chebyshev params not exposed in adapter

### ISSUE THREAD

**Issue by egphill** [trilinos/Trilinos#6243]
## Bug Report
@trilinos/ifpack2 

### Description
When setting up a Chebyshev preconditioner through Stratimikos, the Chebyshev specific parameters are not available in the Ifpack2 Settings sublist. Looks like these are missing from `packages/ifpack2/src/ifpack2_Parameters.cpp` 

@cgcgcg 

### Steps to Reproduce
1. SHA1:  [insert here]
1. Configure script:  [attach here]
1. Configure log:  [attach here]
1. Build log:  [attach here]
1. Input deck:  [attach here]
1. Do this.
1. Do that.
1. Shake fist angrily at computer.
1. Run log:  [attach here]

**Comment by mhoemmen** [comment]
@trilinos/ifpack2 I'm surprised that the functions in `Ifpack2_Parameters.hpp` haven't been deprecated yet.  It's error prone and not scalable to have to define valid parameters in two different places -- the individual Ifpack2 preconditioner classes, and the functions in `Ifpack2_Parameters.hpp`.  For the latter, if we want to keep the global "all the valid parameters" function, then we could just harvest valid parameters from all the Ifpack2 preconditioner classes, using `Ifpack2::Factory` in a static initialization step to enumerate all enabled Ifpack2 preconditioners.

**Comment by jhux2** [comment]
It would be nice to have a validation method that generates documentation automatically, like MueLu does.

**Comment by mhoemmen** [comment]
@jhux2 If it's automated and reduces duplication and errors like this, then I'm all for it :-D

**Comment by cgcgcg** [comment]
This was fixed in #6270
