### ISSUE TITLE
configure Trilinos fail with ShyLU

### ISSUE THREAD

**Issue by leihaoda** [trilinos/Trilinos#6255]
## Bug Report
@trilinos/shylu
### Description
I am trying build trilinos for Xyce Parallel on Ubuntu 18.04.3 LTS, I got error with "ERROR: Setting Trilinos_ENABLE_ShyLU=OFF which was 'ON' because ShyLU has a required library dependence on disabled package ShyLU_DD!". How can i fix it? 
P.S I did enable Shy_DD & Shy_DDBDDC option. However, it is still not working.

### Steps to Reproduce
1. Configure script: 
SRCDIR=$HOME/Trilinos-trilinos-release-12-18-branch
ARCHDIR=$HOME/XyceLibs/Parallel
FLAGS="-O3 -fPIC"
cmake \
-G "Unix Makefiles" \
-DCMAKE_C_COMPILER=mpicc \
-DCMAKE_CXX_COMPILER=mpic++ \
-DCMAKE_Fortran_COMPILER=mpif77 \
-DCMAKE_CXX_FLAGS="$FLAGS" \
-DCMAKE_C_FLAGS="$FLAGS" \
-DCMAKE_Fortran_FLAGS="$FLAGS" \
-DCMAKE_INSTALL_PREFIX=$ARCHDIR \
-DCMAKE_MAKE_PROGRAM="make" \
-DTrilinos_ENABLE_NOX=ON \
  -DNOX_ENABLE_LOCA=ON \
-DTrilinos_ENABLE_EpetraExt=ON \
  -DEpetraExt_BUILD_BTF=ON \
  -DEpetraExt_BUILD_EXPERIMENTAL=ON \
  -DEpetraExt_BUILD_GRAPH_REORDERINGS=ON \
-DTrilinos_ENABLE_TrilinosCouplings=ON \
-DTrilinos_ENABLE_Ifpack=ON \
-DTrilinos_ENABLE_ShyLU=ON \
-DTrilinos_ENABLE_Isorropia=ON \
-DTrilinos_ENABLE_AztecOO=ON \
-DTrilinos_ENABLE_Belos=ON \
-DTrilinos_ENABLE_Teuchos=ON \
  -DTeuchos_ENABLE_COMPLEX=ON \
-DTrilinos_ENABLE_Amesos=ON \
  -DAmesos_ENABLE_KLU=ON \
-DTrilinos_ENABLE_Sacado=ON \
-DTrilinos_ENABLE_Kokkos=OFF \
-DTrilinos_ENABLE_Zoltan=ON \
-DTrilinos_ENABLE_ALL_OPTIONAL_PACKAGES=OFF \
-DTrilinos_ENABLE_CXX11=ON \
-DTPL_ENABLE_AMD=ON \
-DAMD_LIBRARY_DIRS="/usr/lib" \
-DTPL_AMD_INCLUDE_DIRS="/usr/include/suitesparse" \
-DTPL_ENABLE_BLAS=ON \
-DTPL_ENABLE_LAPACK=ON \
-DTPL_ENABLE_MPI=ON \
$SRCDIR
2. Configure log: 
Configuring Trilinos build directory

-- PROJECT_SOURCE_DIR='/home/kevin/Trilinos-trilinos-release-12-18-branch'
-- PROJECT_BINARY_DIR='/home/kevin/Build'
-- Trilinos_TRIBITS_DIR='/home/kevin/Trilinos-trilinos-release-12-18-branch/cmake/tribits'
-- TriBITS_VERSION_STRING='0.9 (Dev)'
-- CMAKE_VERSION='3.10.2'
-- CMAKE_GENERATOR='Unix Makefiles'
-- CMAKE_HOST_SYSTEM_NAME='Linux'
-- Trilinos_HOSTNAME='kevin-XPS-15-9575'
-- Found PythonInterp: /usr/bin/python (found suitable version "2.7.15", minimum required is "2.6") 
-- PYTHON_EXECUTABLE='/usr/bin/python'
-- Found Git: /usr/bin/git (found version "2.17.1") 

Setting up major user options ...

***
*** NOTE: Setting Trilinos_ENABLE_PyTrilinos=OFF because BUILD_SHARED_LIBS=OFF!
***

-- Setting Trilinos_ENABLE_TriKota=OFF because '/home/kevin/Trilinos-trilinos-release-12-18-branch/packages/TriKota/Dakota' does not exist!

NOTE: Skipping generation of TrilinosRepoVersion.txt because project source is not a git repo!

Reading list of native packages from /home/kevin/Trilinos-trilinos-release-12-18-branch/PackagesList.cmake

-- Trilinos_NUM_PACKAGES='62'

Reading list of native TPLs from /home/kevin/Trilinos-trilinos-release-12-18-branch/TPLsList.cmake

-- Trilinos_NUM_TPLS='112'

Processing Project, Repository, and Package dependency files and building internal dependencies graph ...

-- Trilinos_NUM_SE_PACKAGES='165'
-- Tentatively enabling TPL 'DLlib'

Explicitly enabled packages on input (by user):  Teuchos Sacado Zoltan EpetraExt Isorropia AztecOO Amesos Ifpack Belos NOX ShyLU TrilinosCouplings 12

Explicitly enabled SE packages on input (by user):  Teuchos Sacado Zoltan EpetraExt Isorropia AztecOO Amesos Ifpack Belos NOX ShyLU TrilinosCouplings 12

Explicitly disabled packages on input (by user or by default):  Kokkos Claps Trios TriKota PyTrilinos NewPackage 6

Explicitly disabled SE packages on input (by user or by default):  KokkosExample Kokkos Claps ShyLU_NodeBasker ShyLU_NodeFastILU SEACASExotec2 SEACASSlice Trioscommsplitter Triossupport Triosnnti Triosnssi Triosprograms Triosexamples Triostests Triosnetcdf-service Trios TriKota STKExp ShyLU_DDCore PanzerExprEval PyTrilinos NewPackage 22

Explicitly enabled TPLs on input (by user):  MPI BLAS LAPACK AMD DLlib 5

Explicitly disabled TPLs on input (by user or by default):  0

Disabling all packages that have a required dependency on disabled TPLs and optional package TPL support based on TPL_ENABLE_<TPL>=OFF ...

Disabling subpackages for hard disables of parent packages due to Trilinos_ENABLE_<PARENT_PACKAGE>=OFF ...

-- Setting subpackage enable Trilinos_ENABLE_KokkosCore=OFF because parent package Trilinos_ENABLE_Kokkos=OFF
-- Setting subpackage enable Trilinos_ENABLE_KokkosContainers=OFF because parent package Trilinos_ENABLE_Kokkos=OFF
-- Setting subpackage enable Trilinos_ENABLE_KokkosAlgorithms=OFF because parent package Trilinos_ENABLE_Kokkos=OFF

Disabling forward required SE packages and optional intra-package support that have a dependancy on disabled SE packages Trilinos_ENABLE_<TRIBITS_PACKAGE>=OFF ...

-- Setting Trilinos_ENABLE_TeuchosKokkosCompat=OFF because TeuchosKokkosCompat has a required library dependence on disabled package KokkosCore
-- Setting Trilinos_ENABLE_TeuchosKokkosComm=OFF because TeuchosKokkosComm has a required library dependence on disabled package KokkosCore
-- Setting Trilinos_ENABLE_KokkosKernels=OFF because KokkosKernels has a required library dependence on disabled package KokkosCore
-- Setting Trilinos_ENABLE_MiniTensor=OFF because MiniTensor has a required library dependence on disabled package KokkosCore
-- Setting Trilinos_ENABLE_TpetraClassic=OFF because TpetraClassic has a required library dependence on disabled package KokkosCore
-- Setting Trilinos_ENABLE_TpetraTSQR=OFF because TpetraTSQR has a required library dependence on disabled package KokkosCore
-- Setting Trilinos_ENABLE_TpetraCore=OFF because TpetraCore has a required library dependence on disabled package KokkosCore
-- Setting Trilinos_ENABLE_Intrepid2=OFF because Intrepid2 has a required library dependence on disabled package KokkosCore
-- Setting Trilinos_ENABLE_STKMath=OFF because STKMath has a required library dependence on disabled package KokkosCore
-- Setting Trilinos_ENABLE_STKUtil=OFF because STKUtil has a required library dependence on disabled package KokkosCore
-- Setting Trilinos_ENABLE_STKSimd=OFF because STKSimd has a required library dependence on disabled package KokkosCore
-- Setting Trilinos_ENABLE_STKNGP=OFF because STKNGP has a required library dependence on disabled package KokkosCore
-- Setting Trilinos_ENABLE_STKNGP_TEST=OFF because STKNGP_TEST has a required library dependence on disabled package KokkosCore
-- Setting Trilinos_ENABLE_STKUnit_test_utils=OFF because STKUnit_test_utils has a required library dependence on disabled package KokkosCore
-- Setting Trilinos_ENABLE_Phalanx=OFF because Phalanx has a required library dependence on disabled package KokkosCore
-- Setting Trilinos_ENABLE_Stokhos=OFF because Stokhos has a required library dependence on disabled package KokkosCore
-- Setting Trilinos_ENABLE_PanzerDiscFE=OFF because PanzerDiscFE has a required library dependence on disabled package KokkosCore
-- Setting Sacado_ENABLE_KokkosCore=OFF because Sacado has an optional library dependence on disabled package KokkosCore
-- Setting Trilinos_ENABLE_Domi=OFF because Domi has a required library dependence on disabled package Kokkos
-- Setting Trilinos_ENABLE_ShyLU_NodeTacho=OFF because ShyLU_NodeTacho has a required library dependence on disabled package Kokkos
-- Setting Trilinos_ENABLE_Amesos2=OFF because Amesos2 has a required library dependence on disabled package Kokkos
-- Setting Trilinos_ENABLE_STKSearch=OFF because STKSearch has a required library dependence on disabled package Kokkos
-- Setting Teuchos_ENABLE_TeuchosKokkosCompat=OFF because Teuchos has an optional library dependence on disabled package TeuchosKokkosCompat
-- Setting Teuchos_ENABLE_TeuchosKokkosComm=OFF because Teuchos has an optional library dependence on disabled package TeuchosKokkosComm
-- Setting Sacado_ENABLE_TeuchosKokkosComm=OFF because Sacado has an optional library dependence on disabled package TeuchosKokkosComm
-- Setting Trilinos_ENABLE_Ifpack2=OFF because Ifpack2 has a required library dependence on disabled package KokkosKernels
-- Setting Trilinos_ENABLE_Tpetra=OFF because Tpetra has a required library dependence on disabled package TpetraClassic
-- Setting Trilinos_ENABLE_PanzerCore=OFF because PanzerCore has a required library dependence on disabled package TpetraCore
-- Setting Trilinos_ENABLE_ThyraTpetraAdapters=OFF because ThyraTpetraAdapters has a required library dependence on disabled package Tpetra
-- Setting Trilinos_ENABLE_Zoltan2=OFF because Zoltan2 has a required library dependence on disabled package Tpetra
-- Setting Trilinos_ENABLE_Teko=OFF because Teko has a required library dependence on disabled package Tpetra
-- Setting Trilinos_ENABLE_ShyLU_DDBDDC=OFF because ShyLU_DDBDDC has a required library dependence on disabled package Tpetra
-- Setting Trilinos_ENABLE_ShyLU_DDFROSch=OFF because ShyLU_DDFROSch has a required library dependence on disabled package Tpetra
-- Setting Trilinos_ENABLE_PanzerDofMgr=OFF because PanzerDofMgr has a required library dependence on disabled package Tpetra
-- Setting Belos_ENABLE_Tpetra=OFF because Belos has an optional library dependence on disabled package Tpetra
-- Setting Trilinos_ENABLE_STKBalance=OFF because STKBalance has a required library dependence on disabled package Zoltan2
-- Setting PanzerAdaptersSTK_ENABLE_TESTS=OFF because PanzerAdaptersSTK has a required test/example dependence on disabled package Ifpack2
-- Setting PanzerAdaptersSTK_ENABLE_EXAMPLES=OFF because PanzerAdaptersSTK has a required test/example dependence on disabled package Ifpack2
-- Setting Trilinos_ENABLE_PanzerMiniEM=OFF because PanzerMiniEM has a required library dependence on disabled package Teko
-- Setting NOX_ENABLE_Teko=OFF because NOX has an optional library dependence on disabled package Teko
-- Setting Trilinos_ENABLE_STKExprEval=OFF because STKExprEval has a required library dependence on disabled package STKMath
-- Setting Trilinos_ENABLE_STKTopology=OFF because STKTopology has a required library dependence on disabled package STKUtil
-- Setting Trilinos_ENABLE_STKMesh=OFF because STKMesh has a required library dependence on disabled package STKUtil
-- Setting Trilinos_ENABLE_STKSearchUtil=OFF because STKSearchUtil has a required library dependence on disabled package STKUtil
-- Setting Trilinos_ENABLE_STKTransfer=OFF because STKTransfer has a required library dependence on disabled package STKUtil
-- Setting Trilinos_ENABLE_STKTools=OFF because STKTools has a required library dependence on disabled package STKUtil
-- Setting Trilinos_ENABLE_Percept=OFF because Percept has a required library dependence on disabled package STKUtil
-- Setting Trilinos_ENABLE_PanzerAdaptersSTK=OFF because PanzerAdaptersSTK has a required library dependence on disabled package STKUtil
-- Setting STKIO_ENABLE_TESTS=OFF because STKIO has a required test/example dependence on disabled package STKUtil
-- Setting STKIO_ENABLE_EXAMPLES=OFF because STKIO has a required test/example dependence on disabled package STKUtil
-- Setting Trilinos_ENABLE_STKIO=OFF because STKIO has a required library dependence on disabled package STKMesh
-- Setting Trilinos_ENABLE_ShyLU_DD=OFF because ShyLU_DD has a required library dependence on disabled package ShyLU_DDBDDC
CMake Error at cmake/tribits/core/package_arch/TribitsAdjustPackageEnables.cmake:1098 (MESSAGE):
   ***
   *** ERROR: Setting Trilinos_ENABLE_ShyLU=OFF which was 'ON' because ShyLU has a required library dependence on disabled package ShyLU_DD!
   ***

Call Stack (most recent call first):
  cmake/tribits/core/package_arch/TribitsAdjustPackageEnables.cmake:1181 (TRIBITS_PRIVATE_PRINT_DISABLE)
  cmake/tribits/core/package_arch/TribitsAdjustPackageEnables.cmake:1204 (TRIBITS_PRIVATE_PRINT_DISABLE_REQUIRED_PACKAGE_ENABLE)
  cmake/tribits/core/package_arch/TribitsAdjustPackageEnables.cmake:1396 (TRIBITS_PRIVATE_DISABLE_REQUIRED_PACKAGE_ENABLES)
  cmake/tribits/core/package_arch/TribitsAdjustPackageEnables.cmake:2320 (TRIBITS_DISABLE_FORWARD_REQUIRED_DEP_PACKAGES)
  cmake/tribits/core/package_arch/TribitsGlobalMacros.cmake:1782 (TRIBITS_ADJUST_PACKAGE_ENABLES)
  cmake/tribits/core/package_arch/TribitsProjectImpl.cmake:171 (TRIBITS_ADJUST_AND_PRINT_PACKAGE_DEPENDENCIES)
  cmake/tribits/core/package_arch/TribitsProject.cmake:93 (TRIBITS_PROJECT_IMPL)
  CMakeLists.txt:90 (TRIBITS_PROJECT)

-- Configuring incomplete, errors occurred!
See also "/home/kevin/Build/CMakeFiles/CMakeOutput.log".

**Comment by mhoemmen** [comment]
@trilinos/shylu

**Comment by srajama1** [comment]
Do you want Kokkos to be OFF ?  -DTrilinos_ENABLE_Kokkos=OFF. The problem starts from there and disables bunch of other stuff. In theory, the one level Schur complement in ShyLU could run with Kokkos. We could enable a build path to do that, but we haven't done it.

**Comment by leihaoda** [comment]
Thx, its work!
