### ISSUE TITLE
Teuchos: Have stacked time summary have a minimum report time

### ISSUE THREAD

**Issue by bathmatt** [trilinos/Trilinos#6289]
## Enhancement
@trilinos/tempus 

I'm seeing a ton of 0 cost things in the timing log file, I'd like to have a minimum value for run time to count

```
|   |   runEvaluators: 362.898 - 17.9087% [6000] {min=198.397, max=629.832, std dev=140.738} <12, 19, 8, 3, 0, 5, 0, 0, 13, 4>
|   |   |   BC1 - AfterSolve: 0.00091644 - 0.000252534% [1000] {min=0.00077158, max=0.00107357, std dev=7.58366e-05} <3, 8, 5,\

```

SO, this is about 1e-6 and could be ignored.  So adding an arg to the dump command

**Comment by rppawlo** [comment]
PR is up in #6291
