### ISSUE TITLE
Tpetra: Make sparse matrix-matrix multiply thread-parallel

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#629]
@trilinos/tpetra 
This is related to #148 and #430.  It may not require completion of either of those.

**Comment by mhoemmen** [comment]
@csiefer2 has been working on this, so I'm assigning him just so he gets credit for finishing it :-)

**Comment by mhoemmen** [comment]
Note that @csiefer2 finished OpenMP integration in FY17 Q1.  Unclear whether CUDA is part of the requirement for FY17.  (CUDA must run correctly, but unclear whether we need to plug in sparse matrix-matrix multiply for CUDA; is it acceptable for now to run on host?)

**Comment by mhoemmen** [comment]
Aiming for end of FY17 or beginning of FY18, for CUDA.

**Comment by csiefer2** [comment]
To build w/ the  OpenMP kernels, you need these configure options
-D Trilinos_ENABLE_OpenMP:BOOL=ON 
-D TpetraKernels_ENABLE_Experimental:BOOL=ON

**Comment by mhoemmen** [comment]
Next step is to enable this capability for OpenMP by default.  We'll need to make sure that tests pass.  Since CUDA is not an immediate priority, we should for now only enable this by default for non-CUDA builds.
