### ISSUE TITLE
Zoltan2: Minimum part size

### ISSUE THREAD

**Issue by SteffenSeckler** [trilinos/Trilinos#6290]
## Question
@trilinos/Zoltan2

Is there any way to specify a minimum size for each partition?
I want to use Zoltan2's MultiJagged method for some particle methods, however, I require to be able to set a minimum size, i.e., elongation of each partition in every direction.
Is this somehow possible using Zoltan2?

**Comment by mhoemmen** [comment]
@trilinos/zoltan2

**Comment by kddevin** [comment]
@SteffenSeckler Am I understanding correctly that you'd like a minimum length, width and height for each part, regardless of whether or not balance could be achieved given those minimums?
Currently such minimum are not available in MultiJagged.   What is the use case for this constraint?
Thanks!

**Comment by SteffenSeckler** [comment]
Hi
yes that is correct. In most particle-in-cell (linked-cells, verlet-lists) methods, it makes computations a lot easier if each cell is bigger that the cutoff (length for which a specific potential is assumed to be more or less 0). and ifneach cell needs that size, each partition should also be at least that big.
