### ISSUE TITLE
Create CUDA 10.1 PR Testing Build

### ISSUE THREAD

**Issue by ZUUL42** [trilinos/Trilinos#6296]
## Enhancement
@trilinos/framework

Look into creating a PR Testing build that uses CUDA 10.1.
Currently we have a CUDA 9.2 PR testing build.
CUDA 10.1 would likely replace the 9.2 build.

**Comment by ZUUL42** [comment]
Looking into possible issue about a know defect in OpenMPI/UCX with CUDA 10 causing lots of random test failures. #5713
Thanks @bartlettroscoe

**Comment by bartlettroscoe** [comment]
Given the large number of random OpenMPI/UCX errors with the CUDA 10.1 build documented in #5713, I don't know that this build is stable enough create a Trilinos pre-merge PR build.  In fact, that build is even too unstable to promote to an official ATDM Trilinos build.

Who requested a CUDA 10.1 PR build?  This issue does not mention who actually requested this.

**Comment by ZUUL42** [comment]
It was in my notes as mentioned in a conversation about future compiler support at TUG, but I did not write down who mentioned.
If it's that unstable, we can either shelve or close this.

**Comment by ZUUL42** [comment]
We can open a new issue when a suitable version of CUDA is released.
