### ISSUE TITLE
Framework: Create Clang PR Testing Build

### ISSUE THREAD

**Issue by ZUUL42** [trilinos/Trilinos#6303]
## Enhancement
@trilinos/framework

Look into creating a PR Testing build that uses Clang.
There have been mentions/requests for a PR testing build that uses Clang.
However the version has varied between 5.0.1, 7.0.1, & 9.0.0.

We are looking to start with creating a 5.0.1 build. After that, we can consider the value of other versions.

**Comment by bartlettroscoe** [comment]
Yes, ATDM currently would like a clang 5.0.1 build.

**Comment by bartlettroscoe** [comment]
CC: @ndellingwood, @jhux2 

@trilinos/framework, the lack of a clang PR build allowed #6671 to get merged that broke every clang build of Trilinos as reported in #6734.  SEMS RHEL7 has a clang 7.0.1 env now.  Can we please add a clang 7.0.1 build?

**Comment by ndellingwood** [comment]
> SEMS RHEL7 has a clang 7.0.1 env now. Can we please add a clang 7.0.1 build?

@bartlettroscoe I'll also add this to testing during kokkos integration tests.

**Comment by ZUUL42** [comment]
A Clang 7.0.1 PR build is ready to go, save a few failing tests.

Could @trilinos/fei, @trilinos/rol, & @trilinos/rythmos take a look at these results? [CDash](https://testing.sandia.gov/cdash/index.php?project=Trilinos&display=project&filtercount=3&showfilters=1&filtercombine=and&field1=site&compare1=61&value1=ascic114&field2=buildname&compare2=61&value2=PR-Clang-test-Trilinos_pullrequest_clang_7.0.1-70&field3=buildstamp&compare3=61&value3=20200226-1928-Experimental)
Please let me know if you can modify the tests to pass or if I can modify [the build](https://github.com/trilinos/Trilinos/compare/develop...ZUUL42:Clang) somehow to get them passing.

I'd like to get it the build in place building with all tests in place, but we could just [turn off those tests for this build](https://testing.sandia.gov/cdash/index.php?project=Trilinos&display=project&filtercount=3&showfilters=1&filtercombine=and&field1=site&compare1=61&value1=ascic143&field2=buildname&compare2=61&value2=PR-Clang_clean-test-Trilinos_pullrequest_clang_7.0.1-71&field3=buildstamp&compare3=61&value3=20200226-2028-Experimental) as well to get this into PR testing.

**Comment by bartlettroscoe** [comment]
@ZUUL42, I would say to just post an issue for the failing test  Rythmos_StepperBuilder_UnitTest_MPI_1 and then disable it in this PR build for now.  The unit test that is failing is obscure and may not even be valid considering C++11 destructors not being allowed to throw.

**Comment by ZUUL42** [comment]
Then we'll move forward adding the build with those tests turned off and I'll create some issues addressing the tests.

**Comment by ZUUL42** [comment]
It appears Clang 9.0.0 is functioning in the PR test and 7.0.1 & 9.0.0 are working in the dev > master merge. So, I'm closing this issue.
