### ISSUE TITLE
Intrepid2: Test Failure with KOKKOS_ENABLE_DEPRECATED_CODE=OFF

### ISSUE THREAD

**Issue by CamelliaDPG** [trilinos/Trilinos#6307]
## Bug Report
@trilinos/intrepid2

### Description
Tests in `packages/intrepid2/unit-test/Discretization/Basis/HierarchicalBases` emit the following:
```
Kokkos::abort: Requested Team Size is too large!
```
when Trilinos is built with `KOKKOS_ENABLE_DEPRECATED_CODE=OFF`.

I have seen this in a serial debug build (Apple clang), as well as with OpenMP (gnu 7.2.0).

**Comment by CamelliaDPG** [comment]
@bartlettroscoe @rppawlo 
The fact that my PR that introduced these failures got past CI testing would seem to indicate that we don't have any CI tests for Intrepid2 that build with `KOKKOS_ENABLE_DEPRECATED_CODE=OFF`.  Can that be true?  If so, could we add such a build?

**Comment by bartlettroscoe** [comment]
> The fact that my PR that introduced these failures got past CI testing would seem to indicate that we don't have any CI tests for Intrepid2 that build with `KOKKOS_ENABLE_DEPRECATED_CODE=OFF`. Can that be true? If so, could we add such a build?

The @trilinos/framework team can comment but yes, I believe that is the case.  I don't think any of the Trilinos PR builds turn off any deprecated code yet.

**Comment by mhoemmen** [comment]
@jwillenbring @trilinos/framework Could we please fix that?  It would be really helpful if we had a Trilinos PR build that disables deprecated code.  Otherwise, our attempts to remove deprecated code will be an endless chase to keep up with developers in other packages.

**Comment by rppawlo** [comment]
> @jwillenbring @trilinos/framework Could we please fix that? It would be really helpful if we had a Trilinos PR build that disables deprecated code. Otherwise, our attempts to remove deprecated code will be an endless chase to keep up with developers in other packages.

We discussed this at the last product leaders meeting and agreed to switch over one of the PR builds. I don't know where it lands on the framework team's priority list.

**Comment by CamelliaDPG** [comment]
This issue (the Intrepid2 test failure, not the absence of PR builds testing with deprecated code disabled) fixed by PR #6310, so closing.
