### ISSUE TITLE
tribits:  windows cmake-install-error

### ISSUE THREAD

**Issue by looooo** [trilinos/Trilinos#6312]
## Bug Report
@trilinos/tribits

### Description
building 12.18.1 for windows ends with cmake error:
```
CMake Error at cmake_install.cmake:56 (file):
-- Installing: D:/bld/trilinos_1574101714727/_h_env/Library/lib/cmake/tribits/examples/MockTrilinos/packages/sacado/cmake/Dependencies.cmake
  file INSTALL cannot read symlink
```
### Steps to Reproduce
conda-forge feedstock:
https://github.com/conda-forge/trilinos-feedstock/pull/23

**Comment by mhoemmen** [comment]
@trilinos/framework
