### ISSUE TITLE
What is the latest trilinos version and where?

### ISSUE THREAD

**Issue by VictorEijkhout** [trilinos/Trilinos#6338]
Your site

https://trilinos.github.io/

claims 12.12 as the latest but I have 12.14.

However, I can't find either for download on

https://github.com/trilinos/trilinos.github.io

there are zero releases.

**Comment by mhoemmen** [comment]
I'm not saying you should have necessarily known this, but the place where you get Trilinos is this repository (https://github.com/trilinos/Trilinos), not that `trilinos.github.io` repository.  If you look there (this repo, not that one) in the list of branches, you'll find the [Trilinos 12.18](https://github.com/trilinos/Trilinos/tree/trilinos-release-12-18-branch) branch.

**Comment by VictorEijkhout** [comment]
On Nov 24, 2019, at 10:17 PM, Mark Hoemmen <notifications@github.com<mailto:notifications@github.com>> wrote:

I'm not saying you should have necessarily known this, but the place where you get Trilinos is this repository (https://github.com/trilinos/Trilinos), not that trilinos.github.io<http://trilinos.github.io/> repository.

Seriously? Havwn’t we gone over this? Just how many fully functional repositories do you guys have that are out of data and completely not marked as such?

Even this github page leads me in two clicks to the other github page.Why on God’s Green Earth ?!?!?!?!?!?!

No seriously….. WHY!!!!!!

Victor.

**Comment by mhoemmen** [comment]
@VictorEijkhout I understand your frustration, but that's a question for @trilinos/framework .

**Comment by jhux2** [comment]
Closed as fixed.  See https://github.com/trilinos/trilinos.github.io/issues/32.
