### ISSUE TITLE
Framework: Create Build That Tests Turning Off Deprecated Code

### ISSUE THREAD

**Issue by ZUUL42** [trilinos/Trilinos#6347]
## Enhancement
@trilinos/framework 

Create a build that hides/disables deprecated code.
Flags to be used:
- set(KOKKOS_ENABLE_DEPRECATED_CODE OFF CACHE BOOL "Set deprecated code flags")
- set(TPETRA_ENABLE_DEPRECATED_CODE OFF CACHE BOOL "Set deprecated code flags")
- set(Belos_HIDE_DEPRECATED_CODE ON CACHE BOOL "Set deprecated code flags")
- set(Epetra_HIDE_DEPRECATED_CODE ON CACHE BOOL "Set deprecated code flags")
- set(Ifpack2_HIDE_DEPRECATED_CODE ON CACHE BOOL "Set deprecated code flags")
- set(Ifpack2_ENABLE_DEPRECATED_CODE OFF CACHE BOOL "Set deprecated code flags")
- set(MueLu_ENABLE_DEPRECATED_CODE OFF CACHE BOOL "Set deprecated code flags")
- set(Panzer_HIDE_DEPRECATED_CODE ON CACHE BOOL "Set deprecated code flags")
- set(Phalanx_HIDE_DEPRECATED_CODE ON CACHE BOOL "Set deprecated code flags")
- set(RTop_HIDE_DEPRECATED_CODE ON CACHE BOOL "Set deprecated code flags")
- set(STK_HIDE_DEPRECATED_CODE ON CACHE BOOL "Set deprecated code flags")
- set(Teuchos_HIDE_DEPRECATED_CODE ON CACHE BOOL "Set deprecated code flags")
- set(Thyra_HIDE_DEPRECATED_CODE ON CACHE BOOL "Set deprecated code flags")
- set(Claps_HIDE_DEPRECATED_CODE ON CACHE BOOL "Set deprecated code flags")
- set(GlobiPack_HIDE_DEPRECATED_CODE ON CACHE BOOL "Set deprecated code flags")
- set(OptiPack_HIDE_DEPRECATED_CODE ON CACHE BOOL "Set deprecated code flags")
- set(Trios_HIDE_DEPRECATED_CODE ON CACHE BOOL "Set deprecated code flags")

**Comment by ZUUL42** [comment]
Initial build with flags on the GCC 4.8.4 build, produce these [results](https://testing.sandia.gov/cdash/index.php?project=Trilinos&parentid=5952480&filtercount=1&showfilters=1&field1=buildstamp&compare1=61&value1=20191122-2318-Experimental&filtercombine=and).
It hit the 50 error max, but shows errors that need to be fixed in @trilinos/stokhos, @trilinos/muelu, & @trilinos/piro. There may be others when those are cleared.

**Comment by ZUUL42** [comment]
Ran another build with flags on the GCC 7.2.0 Werror build, produce these [results](https://testing.sandia.gov/cdash/index.php?project=Trilinos&parentid=5952001&filtercount=1&showfilters=1&field1=buildstamp&compare1=61&value1=20191122-2236-Experimental&filtercombine=and).
It hit the 50 error max, but shows errors that need to be fixed in @trilinos/stokhos, @trilinos/muelu, & @trilinos/shylu _DD. There may be others when those are cleared.

**Comment by ZUUL42** [comment]
These jobs are being run pulling [ZUUL42/deprecated to trilinos/develop](https://github.com/trilinos/Trilinos/compare/develop...ZUUL42:deprecated) with just the flags in each corresponding cmake file.

**Comment by rppawlo** [comment]
Thanks @ZUUL42 ! Looks like we will need help cleaning these up from @etphipp @jhux2 @srajama1 and @mperego . @trilinos/stokhos @trilinos/shylu  @trilinos/muelu

**Comment by lucbv** [comment]
@ZUUL42 it looks like you are not turning deprecated code off in every package, for instance Iooking at the configure log I find the following output line:
```
-- Tpetra: Enabling deprecated code
```
which means that Xpetra will assume that deprecated code is turned ON and it leads to a lot of subsequent false positives in MueLu...

**Comment by kddevin** [comment]
The Tpetra flag should be capitalized like this:

 -D Tpetra_ENABLE_DEPRECATED_CODE=OFF 

You have it in all caps above.  CMake cares about that, right?  That would lead to @lucbv 's observation that Tpetra's code is still on.

**Comment by kddevin** [comment]
I don't think we'll need help from @etphipp @jhux2 @srajama1 or @mperego yet.  These errors all appear to be the same Xpetra problem, perhaps arising from the flag above.  Stay tuned.

**Comment by ZUUL42** [comment]
Casing it as `Tpetra_ENABLE_DEPRECATED_CODE`, caused the build to crash during configuration, so I changed it. I'll take a closer look. Now I see there are both versions in different parts of the code.

**Comment by kddevin** [comment]
@ZUUL42 
Here are the CMake flags that we set in our testing at TUG:
```
-D KOKKOS_ENABLE_DEPRECATED_CODE=OFF \
 -D Tpetra_ENABLE_DEPRECATED_CODE=OFF  \
 -D Belos_HIDE_DEPRECATED_CODE=ON  \
 -D Epetra_HIDE_DEPRECATED_CODE=ON  \
 -D Ifpack2_HIDE_DEPRECATED_CODE=ON \
 -D Ifpack2_ENABLE_DEPRECATED_CODE=OFF \
 -D MueLu_ENABLE_DEPRECATED_CODE=OFF \
 -D Panzer_HIDE_DEPRECATED_CODE=ON  \
 -D Phalanx_HIDE_DEPRECATED_CODE=ON \
 -D RTop_HIDE_DEPRECATED_CODE=ON \
 -D STK_HIDE_DEPRECATED_CODE=ON \
 -D Teuchos_HIDE_DEPRECATED_CODE=ON\
 -D Thyra_HIDE_DEPRECATED_CODE=ON \
 -D Claps_HIDE_DEPRECATED_CODE=ON \
 -D GlobiPack_HIDE_DEPRECATED_CODE=ON \
 -D OptiPack_HIDE_DEPRECATED_CODE=ON \
 -D Trios_HIDE_DEPRECATED_CODE=ON \
```

**Comment by ZUUL42** [comment]
I saw that and tried that case at first. It produces [this](https://testing.sandia.gov/cdash/index.php?project=Trilinos&display=project&filtercount=3&showfilters=1&filtercombine=and&field1=site&compare1=61&value1=ascic158&field2=buildname&compare2=61&value2=PR-deprecated-test-Trilinos_pullrequest_gcc_7.2.0-3117&field3=buildstamp&compare3=61&value3=20191125-2316-Experimental).

**Comment by rppawlo** [comment]
The deprecated code limits you to one Tpetra GO type. If your GO is long long then you need these flags:
```
-D Xpetra_ENABLE_Epetra:BOOL=OFF \
-D MueLu_ENABLE_Epetra:BOOL=OFF \
```
Otherwise I think it will work if you make the GO int. This may impact test coverage. We probably should limit to one PR build for now.

**Comment by brian-kelley** [comment]
@rppawlo It does affect test coverage. During the deprecated removal project we've been testing both int and long long. There are many tests in TrilinosCouplings, ShyLU and others that get disabled without Epetra/GO=int enabled. There are also a few tests sprinkled around that are disabled without GO=long long enabled. If you had to pick one for PR testing, GO=int and Epetra enabled better test coverage, even though GO=long long is the default for Tpetra.

**Comment by ikalash** [comment]
FYI since this is related: I just changed most of the Albany nightlies to turn off the Tpetra and Xpetra deprecated code

```
-D Tpetra_ENABLE_DEPRECATED_CODE:BOOL=OFF \
-D Xpetra_ENABLE_DEPRECATED_CODE:BOOL=OFF \
```

The CDash sites can be found here: http://cdash.sandia.gov/CDash-2-3-0/index.php?project=Albany and https://my.cdash.org/viewSubProjects.php?project=Albany .

**Comment by wadeburgess** [comment]
This was migrated to the Trilinos Help Desk, so this issue is now being closed.
