### ISSUE TITLE
MueLu: region MG test fail in debug builds

### ISSUE THREAD

**Issue by lucbv** [trilinos/Trilinos#6349]
## Bug Report
@trilinos/muelu @mayrmt 

### Description
When running `ctest -R` from `packages/muelu/research/regionMG/examples/structured` in a debug build, most of the tests fail (especially though with more than 1 MPI rank).
This might reveal a potential bug in the region MG code.

**Comment by mayrmt** [comment]
@lucbv I just double checked: `MueLu_Structured_Region*` tests from`develop` in debug mode are passing on my machine. 

Should we close this issue?

**Comment by lucbv** [comment]
@mayrmt yes, let us close this since the change of maps was sufficient.
