### ISSUE TITLE
Tpetra: compilation error with Tpetra deprecated code off in Tpetra::TsqrAdapter

### ISSUE THREAD

**Issue by ikalash** [trilinos/Trilinos#6354]
Along with @mperego, I'm trying to switch the Albany nightlies to turn off the Tpetra/Xpetra deprecated code:

```
 -D Tpetra_ENABLE_DEPRECATED_CODE:BOOL=OFF \
 -D Xpetra_ENABLE_DEPRECATED_CODE:BOOL=OFF \
```

I encountered the following compilation error in most of my nightlies when doing this: 

```
repos/Trilinos/packages/tpetra/core/src/Tpetra_TsqrAdaptor.hpp:353:72: error: no member named 'getNode' in 'Tpetra::Map >'
```

http://cdash.sandia.gov/CDash-2-3-0/viewBuildError.php?buildid=91235 

A sample configuration that produces the error can be found here: https://github.com/SNLComputation/Albany/blob/master/doc/dashboards/cee-compute011.sandia.gov/ctest_nightly.cmake

**Comment by ikalash** [comment]
@trilinos/tpetra

**Comment by mperego** [comment]
@kddevin It seems Albany exposed another bug.. but it might be the last one! (at least in Tpetra)

**Comment by mhoemmen** [comment]
@kddevin I have a branch that fixes this.  Let me try it in PR testing.

**Comment by mhoemmen** [comment]
I happened to be working on TSQR for another project, and that work fixes this issue.  I've started a PR (#6359).

**Comment by ikalash** [comment]
Seems we're still seeing the same problem: http://cdash.sandia.gov/CDash-2-3-0/viewBuildError.php?buildid=91319 .

**Comment by mhoemmen** [comment]
Oopsie, let me check that out.

**Comment by mhoemmen** [comment]
@trilinos/framework This is relevant to #6347.

**Comment by mhoemmen** [comment]
@ikalash Here's a PR that fixes it.  I also added a test to Tpetra so issues like this would be caught in Tpetra, not downstream.  Thanks for reporting! :-)

**Comment by ikalash** [comment]
I can confirm that the Albany dashboard is all good now.  Thanks again for fixing the issue, @mhoemmen !

**Comment by mhoemmen** [comment]
Double win -- for Albany and for @fnrizzi 's project :-D
