### ISSUE TITLE
Nalu application diffs due to new Trilinos/develop

### ISSUE THREAD

**Issue by spdomin** [trilinos/Trilinos#6358]
## Bug Report
@trilinos/\<Zoltan2\>

### Description
I am seeing four new Nalu nightly regression tests diffs on gcc 7.2 and 8.3 due to a new Trilinos develop build:

git bisect bad 143ac5f761f187b98f79173b1670cb40c86e357e
git bisect good 0141ed90626699ba8402f52af9c25553bf947d67

The diffs in Nalu also seemingly show up on Nalu-Wind.

Once I have more details, I will report back. I just wanted to capture this to avid multiple developers performing a Trilinos bisect.

Best,

**Comment by spdomin** [comment]
Perhaps this is a Muleu->Zoltan2 dependency that affects an application code?

c6f8278e84b1eac8e007527c56808a31835aedbc is the first bad commit
commit c6f8278e84b1eac8e007527c56808a31835aedbc
Author: micheldemessieres <michel@demessieres.com>
Date:   Tue Oct 8 21:34:20 2019 -0400

    Zoltan2: Refactor Multijagged to use Kokkos and CUDA
    
    MJ now uses Kokkos views.
    GPU support has been added.
    Added testing for UVM on and off.
    Resolves merge with DragonFly code.

:040000 040000 4765da3530c5a4eb87a4f40d95388c19b60b4d74 a08888d68aa6f708e1c8007c15c236eda0bc68af M	packages
:000000 100644 0000000000000000000000000000000000000000 ed2a9ab1b37c50f42278b571dcd4f3d40be63653 A	save_Zoltan2_AlgMultiJagged.hpp
:000000 100644 0000000000000000000000000000000000000000 014a66b3077288b546dba2e7d9ce86c6a095244f A	save_Zoltan2_TaskMapping.hpp

**Comment by spdomin** [comment]
Perhaps @jhux2 could provide insight here?

**Comment by mhoemmen** [comment]
@kddevin @MicheldeMessieres

**Comment by jhux2** [comment]
@spdomin What are the level of diffs that you are seeing?

**Comment by spdomin** [comment]
Most are small, e.g., 1e-12, however, one is 1e-6. These diffs are based on the average nonlinear norm per time step for some rather non-linear mechanics. Moreover, none of my "correctness" tests failed, i.e., order of convergence checks.

To conclude, these diffs are small, however, you probably know my philosophy - diffs/changes in code behavior are perfectly acceptable if understood:)

**Comment by jhux2** [comment]
@spdomin  It's hard for me to say if this change is benign.  The commit you mention looks like it's targeting GPUs.  What's the time span that you had to bisect?

**Comment by spdomin** [comment]
The time span was one day. 11 commits. My bisect converged after I think four iterations.

**Comment by jhux2** [comment]
@spdomin Ah, ok, the commit date threw me off.  @MicheldeMessieres Can you comment on the commit pointed out above?

**Comment by spdomin** [comment]
I know. I saw that the original effort started back in October, however, it was merged just yesterday.

**Comment by MicheldeMessieres** [comment]
The zoltan2 Multijagged algorithm was significantly refactored to support Kokkos views and GPU. The original algorithm had some non-deterministic behaviors for openmp. The new algorithm fixes this though there could be some subtle shifts in part assignments which still meet the load balancing criteria, even if not running OpenMP.

I'm guessing this might be causing the diffs. To evaluate more carefully we could look at the part assignments before and after the code changes, verify we see some part assignments which changed, and verify the new part assignments are still a legitimate partitioning.

**Comment by spdomin** [comment]
Thank you for your detailed reply - much appreciated. If your set of changes were associated with some sort of correctness testing, then I would be happy to accept the diffs and move on. The set of changes looked to be large, I.e., 20k lines+. 

In short, I trust the judgement of the Trilinos team in such matters. Just let me know if you are nervous with this finding and would like to pursue this more. If you do, I would be happy to support before and after push matrix files, etc. 

Thus far, due to the pressure projection scheme, I have verified that  the first non-muelu momentum solve for both code versions provides the same velocity field to muelu. It is at the first elliptic solve that diffs occur.

Best

**Comment by MicheldeMessieres** [comment]
@spdomin @kddevin  Issue #6374 was just reported which has a hang using the new MJ code for Empire + MueLu so I'll need to resolve that before making any further judgement about the correctness of the commit.

**Comment by kddevin** [comment]
@MicheldeMessieres  I agree with your plan:  address #6374 and then confirm partitioning results for this issue.  Thanks!

**Comment by spdomin** [comment]
Are you reverting then?

**Comment by MicheldeMessieres** [comment]
@spdomin I just opened PR #6377 which will fix #6374. Thanks to @cgcgcg. That issue was specific to builds with KOKKOS_ENABLE_DEPRECATED_CODE OFF. I do not anticipate those fixes will cause any change to the issue with the diffs.

@kddevin would like me to check your partitioning before and after my recent Multijagged changes. As she stated for #6374, if you add the command below for your problem with diffs you can generate output files which allow me to replicate the partitioning. Then I will run that both for before and after the new Multijagged PR and analyze the outputs to confirm any changes are expected.

In MueLu, Immediately before calling partitioningProblem.solve(), call inputAdapter.generateFiles("filenameprefix", communicator).
@kddevin please correct me if this would not be the best approach.

**Comment by spdomin** [comment]
If someone could provide a Muelu patch, I can test this next week - perhaps @jhux2 ?

**Comment by spdomin** [comment]
Actually, @jhux2 and @MicheldeMessieres, I can not find in the Muelu code base where I should add the above line. I searched for "ProblemType", "partictioningProblem", etc. to no avail.

@jhux2, Nalu-Wind also diff'd due to this change. If you have an active build, you can probably take this next phase over?

**Comment by cgcgcg** [comment]
@spdomin You can trigger it from parameter list. Simply put "mj_debug"=True in the "repartition: params" list. Unfortunately you will have to change the code if rebalance more than once, since this filename is hard coded in 
https://github.com/trilinos/Trilinos/blob/b7e7c05a9927944c8465c495b1e73adb6cbbb6b2/packages/muelu/src/Rebalancing/MueLu_Zoltan2Interface_def.hpp#L215-L220

**Comment by spdomin** [comment]
@cgcgcg, could you tell me if this Muelu XML will require a code change - specifically, "if rebalance more than once":

https://github.com/NaluCFD/Nalu/blob/master/reg_tests/xml/milestone_aspect_ratio.xml

I plan on running on of the four cases failing (smallest test).

**Comment by cgcgcg** [comment]
@spdomin It depends on how big of a problem you are running. If you have a log file of a previous run, you can check the "Mutigrid Summary". The last column shows the number of ranks per level. If that number decreases more than once, you are rebalancing more than once and need a code change.

**Comment by spdomin** [comment]
Specifically, @cgcgcg, I am planning on running the following case:

https://github.com/NaluCFD/Nalu/tree/master/reg_tests/test_files/elemHybridFluids

Using the following XML:

https://github.com/NaluCFD/Nalu/blob/master/reg_tests/xml/milestone_aspect_ratio.xml

Please let me know specifically the code change (if any) that you would expect from a single time step of this case.

In the meantime, I will add the above. It may be later in the week as I have a couple of deliverables..

Best,

**Comment by cgcgcg** [comment]
@spdomin If you can wait for https://github.com/trilinos/Trilinos/pull/6381 to be merged, this will work no matter what problem.

**Comment by spdomin** [comment]
K... I also have this patch that I am now building using the two different versions of Trilinos... Flying blind, however, hopefully, this might work:

```
diff --git a/packages/muelu/src/Rebalancing/MueLu_Zoltan2Interface_def.hpp b/packages/muelu/src/Rebalancing/MueLu_Zoltan2Interface_def.hpp
index adff3c0..07c10b3 100644
--- a/packages/muelu/src/Rebalancing/MueLu_Zoltan2Interface_def.hpp
+++ b/packages/muelu/src/Rebalancing/MueLu_Zoltan2Interface_def.hpp
@@ -65,6 +65,8 @@
 #include "MueLu_Monitor.hpp"
 #include "MueLu_Utilities.hpp"
 
+#include <sstream>
+
 namespace MueLu {
 
  template <class Scalar, class LocalOrdinal, class GlobalOrdinal, class Node>
@@ -120,6 +122,8 @@ namespace MueLu {
   void Zoltan2Interface<Scalar, LocalOrdinal, GlobalOrdinal, Node>::Build(Level& level) const {
     FactoryMonitor m(*this, "Build", level);
 
+    static int counterForZ = 0;
+
     typedef typename Teuchos::ScalarTraits<SC>::coordinateType real_type;
     typedef typename Xpetra::MultiVector<real_type,LO,GO,NO> RealValuedMultiVector;
 
@@ -214,8 +218,14 @@ namespace MueLu {
 
       {
         SubFactoryMonitor m1(*this, "Zoltan2 " + toString(algo), level);
-        if (writeZoltan2DebuggingFiles)
-          adapter.generateFiles("mj_debug", *(rowMap->getComm()));
+        if (writeZoltan2DebuggingFiles) {
+          std::stringstream ss;
+          ss << counterForZ;
+          const std::string incrementName = ss.str();
+          const std::string theName = "mj_debug_" + incrementName;
+          adapter.generateFiles(theName, *(rowMap->getComm()));
+          counterForZ++;
+        }
         problem->solve();
       }

```

**Comment by spdomin** [comment]
The parameter name "repartition: mj_debug" is not valid. Did you mean "repartition: node id"?

based on my complete guess:

  <Parameter        name="repartition: mj_debug"            type="bool"     value="true"/>

**Comment by cgcgcg** [comment]
Here is what I mean:
```
<ParameterList name="repartition: params">
    <Parameter name="mj_debug" type="bool" value="true"/>
</ParameterList>
```

**Comment by spdomin** [comment]
Okay, in my current Trilinos version (before any of my hacked code I showed above), adding:

  <ParameterList    name="smoother: params">
     <Parameter name="chebyshev: degree"                    type="int"      value="2"/>
     <Parameter name="chebyshev: ratio eigenvalue"          type="double"   value="20"/>
     <Parameter name="chebyshev: min eigenvalue"            type="double"   value="1.0"/>
     <Parameter name="chebyshev: zero starting solution"    type="bool"     value="true"/>
     <Parameter name="chebyshev: eigenvalue max iterations" type="int"      value="15"/>
     <Parameter name="mj_debug"                             type="bool" value="true"/>
  </ParameterList>

Does not seem to create any special file.

**Comment by cgcgcg** [comment]
That's because you added it to the smoother parameters. Just add the parameter list below 
```
<Parameter        name="repartition: partitioner"         type="string"   value="zoltan2"/>
```

**Comment by spdomin** [comment]
Sorry about that. I have the output and will forward it to @MicheldeMessieres

**Comment by spdomin** [comment]
Too bad... The first case that I ran (elemHybridFluids) with this new using the "bad" and "good" Trilinos versions demonstrated the expected diff in the log file, however, the three files that each produced: mj_debug_0.assign, mj_debug_0.coords, and mj_debug_0.graph are all the same... 

Specifically, something like the following:

`tkdiff mj_debug_0.graph ../nightlyDevel/mj_debug_0.graph
`
did not show any diffs between the three files.

I can try one more larger case, however, if that does not show anything, I may need to hand this to the Muelu team.

**Comment by MicheldeMessieres** [comment]
I need to check exactly what the logging does but I think this may be expected as you are only logging the input state before multijagged runs. If you send those files to me I can do some analysis of the final output data. We should probably extend this logging system so we can capture the outputs as well.

**Comment by spdomin** [comment]
I will send you the files. My second case, uqSlidingMeshDG showed the same lack of differences between the mj files, however, again diff-d in the log file.

**Comment by alanw0** [comment]
Mentioning @sayerhs so he can keep apprised of progress (for the nalu-wind point of view).

**Comment by kddevin** [comment]
@MicheldeMessieres is correct; the files represent the input state to the partitioner, so we would expect them to be the same.
With the files, @MicheldeMessieres can run old vs new to see whether the results differ, and whether or not the difference is important.

**Comment by kddevin** [comment]
@MicheldeMessieres 
I think you can use the same mj_debug.xml that you used with Christian, changing only the number of parts.  I don't see info from MueLu in NALU's logs that specifies the target number of parts. (@spdomin , do you know the number of parts for the coarse operator?)  

The runs appeared to be on eight parts, so you could try different numbers and compare before/after partitions.  

Alternatively, it wouldn't be hard to add a method that takes an input adapter and a partitioning solution to produce files similar to generate_files with the result partition.  But working with @spdomin 's files and the test_driver is fine.

**Comment by MicheldeMessieres** [comment]
Thanks, I am doing that now, just wanted to be sure I was matching the part count at this step. If 8 is correct with 8 procs, then I'll just start with that.

**Comment by kddevin** [comment]
Sorry; I wasn't clear.  I don't know that eight parts is correct; I suspect some number less than eight is correct.  But there are only six possible values, so if @spdomin doesn't know the exact value, it isn't difficult to try 2-7.

**Comment by MicheldeMessieres** [comment]
I just opened PR #6385 which I expect will resolve these diffs and probably others. There was an error and in some setups proper load balancing was not achieved due to precision errors for coordinates falling on partition cuts.
@spdomin I was able to match partitioning outputs exactly before and after the new multijagged changes once this fix was applied. Note I didn't complete cuda testing as white is not currently working for me but I think this will likely pass auto tester.

**Comment by spdomin** [comment]
Excellent. I will report back on the nightly test suite ASAP.

**Comment by mhoemmen** [comment]
@rrdrake @sebrowne FYI (if planning a Trilinos integration, please wait until this is resolved -- thanks!)

**Comment by jhux2** [comment]
@MicheldeMessieres thank you!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by kddevin** [comment]
#6385 is merged into develop.  Please let us know whether or not it resolves the Nalu issue.

**Comment by spdomin** [comment]
Everything looks clean for Nalu for all of my previously diffing tests:

```
100% tests passed, 0 tests failed out of 69
NaluCFD/Nalu SHA1: df0c1a21c669fcc5be6459a367ddbbff4cc971ec
Trilinos/develop SHA1: 88f86a2671854a35cd571615057fc436f201beae

```

Feel free to close this issue with my thanks. I appreciate the Zoltan team working to track down these application diffs.

**Comment by mhoemmen** [comment]
Thanks for reporting! :-D
