### ISSUE TITLE
Belos Static Teuchos RCP Segmentation Fault with Clang

### ISSUE THREAD

**Issue by sslattery** [trilinos/Trilinos#636]
Per discussion with @bartlettroscoe, Clang 7 and 8 produce a segmentation fault on Mac OS X 10.11.6 at runtime in Belos when trying to construct a static RCP to an ostream using std::cout. The belos unit tests do not pass on the master due to the segmentation fault:

```
    Start 1: Belos_Factory_MPI_4
1/5 Test #1: Belos_Factory_MPI_4 ................***Failed    0.04 sec
    Start 2: Belos_test_gcrodr_complex_MPI_4
2/5 Test #2: Belos_test_gcrodr_complex_MPI_4 ....***Failed    0.09 sec
    Start 3: Belos_test_rcg_complex_MPI_4
3/5 Test #3: Belos_test_rcg_complex_MPI_4 .......***Failed    0.07 sec
    Start 4: Belos_test_lsqr_complex_MPI_4
4/5 Test #4: Belos_test_lsqr_complex_MPI_4 ......   Passed    0.15 sec
    Start 5: Belos_test_factory_complex_MPI_4
5/5 Test #5: Belos_test_factory_complex_MPI_4 ...   Passed    0.16 sec

```

Attached the configuration file and an lldb stack trace from the factory test failure. Configuration is standard with MPI and Belos enabled.

[configure.txt](https://github.com/trilinos/Trilinos/files/486421/configure.txt)

[belos_segfault.txt](https://github.com/trilinos/Trilinos/files/486409/belos_segfault.txt)

The stack trace points to BelosBlockGmresSolMgr.hpp:404 but I have also experienced this with the BelosPseudoBlockGmresSolMgr and I suspect it also occurs with other places where the static RCP to the stream is being constructed.

**Comment by bartlettroscoe** [comment]
@sslattery, thanks for reporting this!  I don't have access to Clang on a Mac.  I only have access to some Clang 3.6.1 on RHEL 6 Linux.  Does Clang on OSX have different version numbers than for Linux?

I will add labels for Teuchos and Belos because the problem could be a defect in Teuchos, Belos, or this Clang compiler.

Also, how urgent this to address?

**Comment by sslattery** [comment]
@bartlettroscoe 

Looks like I have llvm 3.8 on my system. The 8.0 version comes from the latest Xcode release on OS X.

As far as urgency, I am able to use another machine for now but this prevents me from using my Mac for development with Belos unless I replace my development environment with a gcc toolchain.

**Comment by mhoemmen** [comment]
As a work-around, I think you can set the Belos solver's ParameterList to use a different RCP<std::ostream>.

**Comment by crtrott** [comment]
I also just put in a sems ticket to get us newer clang compilers (i.e. beyond 3.6).

**Comment by mhoemmen** [comment]
@ambrad points out that we should also refer to (old) Bugzilla Bug 6262.
