### ISSUE TITLE
Zoltan2: Hang in MultiJagged

### ISSUE THREAD

**Issue by cgcgcg** [trilinos/Trilinos#6374]
## Bug Report
@trilinos/zoltan2 

### Description
Some EMPIRE + MueLu runs on lassen are hanging in the rebalancing using Zoltan2 MultiJagged. Reverting https://github.com/trilinos/Trilinos/pull/5332 fixes the issue. Since I am not getting any output from Zoltan2: what can I do to make it easier to debug this?

**Comment by MicheldeMessieres** [comment]
@cgcgcg Can you give some general details about the setup? I am not familiar with Lassen but I understand it's a CUDA capable machine. If this is a CUDA run, does it run with CUDA off or does the run work on any other setup?  Is it hanging on the first pass through Multijagged or after some cycles? Number of coordinates and partitioning requested could be helpful to have a sense of the scale we're dealing with. Thanks.

**Comment by cgcgcg** [comment]
@MicheldeMessieres I was able to observe the same hang on 8 ranks, using OpenMP. Is there an option in Zoltan2 to dump out whatever inputs are used? I believe @kddevin added an option for that at some point. Otherwise I'll hack something into MueLu.
Currently, I only see that MueLu passes things into Zoltan2, but I really have zero Zoltan output. If there is a verbose option, I'm happy to try that.

**Comment by kddevin** [comment]
@cgcgcg @MicheldeMessieres 

There is a way to write the data being passed to Zoltan2 to a file that can be read by the Zoltan2 driver for testing and reproducing errors.
In MueLu, Immediately before calling partitioningProblem.solve(), call  inputAdapter.generateFiles("filenameprefix", communicator).

https://github.com/trilinos/Trilinos/blob/40fdb76d0106b140739022b8452748f7d5eca23c/packages/zoltan2/src/input/Zoltan2_VectorAdapter.hpp#L190

The resulting files, filenameprefix.*, can be read by the Zoltan2 test driver in test/driver.  See an example xml file:  packages/zoltan2/test/driver/driverinputs/miniem4669/miniem.xml

This should allow @MicheldeMessieres to reproduce the problem in a simpler environment.

**Comment by cgcgcg** [comment]
@kddevin Perfect! Will do!

**Comment by kddevin** [comment]
you may be able to get more info out of Zoltan2 by adding parameter "debug_level"   = "detailed_status" to your parameter list passed to the partitioningProblem.

**Comment by MicheldeMessieres** [comment]
This will be resolved by PR #6377. The issue was specific to builds with KOKKOS_ENABLE_DEPRECATED_CODE set to OFF.
