### ISSUE TITLE
Tpetra: computeNumPacketsAndOffsets: parallel_scan error

### ISSUE THREAD

**Issue by stanmoore1** [trilinos/Trilinos#6389]
## Bug Report
@trilinos/Tpetra

### Description
On Astra using 2048 nodes, I sometimes see a crash in Tpetra: `computeNumPacketsAndOffsets: parallel_scan error code 3 != 0`. I believe this issue is distinct from #6345 because it happens with an older version of Trilinos, while #6345 only happens with a newer version of Trilinos. The crash happens in nearly the same place though, right after the linear system has been initialized.

I'm using Trilinos from 11-11-2019.

**Comment by stanmoore1** [comment]
@bathmatt @rppawlo

**Comment by stanmoore1** [comment]
@kddevin @csiefer2

**Comment by mhoemmen** [comment]
@trilinos/tpetra

**Comment by kddevin** [comment]
@stanmoore1  Is this issue still a problem for you?

**Comment by stanmoore1** [comment]
I don't know--I'm pushing up the latest version today and will try to reproduce the error.

**Comment by kddevin** [comment]
Great!  Thanks, @stanmoore1

**Comment by kddevin** [comment]
Hi @stanmoore1 .  Is there more status on this issue?

**Comment by kddevin** [comment]
My understanding is that this error has been resolved through a fix in Kokkos' parallel_scan.
I will close this issue.  If the problem persists, please re-open.
