### ISSUE TITLE
Create Trilinos GitHub Issue Lifecycle Model

### ISSUE THREAD

**Issue by maherou** [trilinos/Trilinos#639]
Recent activity with GitHub issues suggests we need an explicit issue lifecycle model to communicate expectations for clients, users and developers.
This issue results from a query by @mwglass.  Others who might be interested are: @jwillenbring @bmpersc and @bartlettroscoe 

Also, I have added a new label "process improvement" so we can group issues that have this theme.

**Comment by bartlettroscoe** [comment]
@maherou, I just now saw this issue (I did not get a GitHub notification email).

When can we pull the trigger on this?
