### ISSUE TITLE
Epetra: CASK TPL no longer needed

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#6395]
## Enhancement
@trilinos/epetra 

### Description

A senior Cray person just said that I could say in a public forum that Cray no longer uses CASK with Trilinos.  This means that we may remove CASK TPL support.

**Comment by mhoemmen** [comment]
begone autobot

**Comment by GrahamBenHarper** [comment]
With the removal of the Epetra stack coming ~~soon™~~ in the next couple years, I don't know if this would necessarily be worth the effort... especially since most of the stack is no longer updated. Any thoughts? Maybe @jhux2?

**Comment by jhux2** [comment]
@GrahamBenHarper Yes, I agree.

**Comment by jhux2** [comment]
I'll close.  If an @trilinos/epetra developer or @ccober6 disagrees, feel free to reopen.

**Comment by ccober6** [comment]
👍
