### ISSUE TITLE
Ifpack2: Ifpack2_Cheby_belos test fails with exactly 2 OpenMP threads

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#64]
@trilinos/ifpack2 
Oddly enough, if I replace the random initial vector (`x.randomize()`) with `x.putScalar(1.0)`, then the test passes.  There might be something fishy either with `randomize` or with diagonal extraction.

**Comment by mhoemmen** [comment]
Furthermore, replacing x.randomize() on the second powerMethodWithInitialGuess pass with the following makes the test pass:
```
x.putScalar (1.0);
V x2 (A.getDomainMap ());
x2.randomize ();
x.update (1.0, x2, 1.0);
```

**Comment by mhoemmen** [comment]
The test fails with exactly 2 OpenMP threads.  When I set OMP_NUM_THREADS to 1, 3, or 4, the test passes.  This doesn't necessarily indicate a bug.  It could be that the test matrix is not truly SPD, so a  different random vector (`Tpetra::Vector::randomize()` uses Kokkos' pseudorandom number generator, which depends on the number of threads) just happens to catch in the right subspace to make the power method go negative.  We need to investigate more.

**Comment by mhoemmen** [comment]
I'm reverting this commit because it caused some diffs in a key customer's tests.  The diffs might be appropriate (slightly different power method means slightly different Chebyshev results, but it still could converge and be correct), but indicate that we need to understand this temporary fix more before we just leave it.

**Comment by mhoemmen** [comment]
When running Ifpack2's tests with OpenMP in an MPI_RELEASE build:

$ export MKL_NUM_THREADS=1
$ export OMP_NUM_THREADS=2
$ ctest
...
The following tests FAILED:
15 - Ifpack2_Cheby_belos_MPI_1 (Failed)

$ export MKL_NUM_THREADS=2
$ export OMP_NUM_THREADS=1
$ ctest
...
The following tests FAILED:
5 - Ifpack2_Jacobi_belos_MPI_1 (Failed)
7 - Ifpack2_Jacobi_hb_belos_MPI_1 (Failed)
8 - Ifpack2_Jacobi_hb_belos_MPI_2 (Failed)

**Comment by mhoemmen** [comment]
$ export OMP_NUM_THREADS=1
$ export MKL_NUM_THREADS=1
$ ctest -R Jacobi
Test project /scratch/prj/Trilinos/CHECKIN-NO-CUDA/MPI_RELEASE/packages/ifpack2
    Start 5: Ifpack2_Jacobi_belos_MPI_1
1/4 Test #5: Ifpack2_Jacobi_belos_MPI_1 ..............   Passed    0.49 sec
    Start 6: Ifpack2_Jacobi_belos_constGraph_MPI_4
2/4 Test #6: Ifpack2_Jacobi_belos_constGraph_MPI_4 ...   Passed    0.40 sec
    Start 7: Ifpack2_Jacobi_hb_belos_MPI_1
3/4 Test #7: Ifpack2_Jacobi_hb_belos_MPI_1 ...........   Passed    0.43 sec
    Start 8: Ifpack2_Jacobi_hb_belos_MPI_2
4/4 Test #8: Ifpack2_Jacobi_hb_belos_MPI_2 ...........   Passed    0.44 sec

$ export MKL_NUM_THREADS=2
$ ctest -R Jacobi
...
The following tests FAILED:
          5 - Ifpack2_Jacobi_belos_MPI_1 (Failed)
          7 - Ifpack2_Jacobi_hb_belos_MPI_1 (Failed)
          8 - Ifpack2_Jacobi_hb_belos_MPI_2 (Failed)

**Comment by mhoemmen** [comment]
Also, if I unset MKL_NUM_THREADS and set OMP_NUM_THREADS=2:

The following tests FAILED:
          5 - Ifpack2_Jacobi_belos_MPI_1 (Failed)
          7 - Ifpack2_Jacobi_hb_belos_MPI_1 (Failed)
          8 - Ifpack2_Jacobi_hb_belos_MPI_2 (Failed)
         15 - Ifpack2_Cheby_belos_MPI_1 (Failed)

**Comment by bartlettroscoe** [comment]
FYI: The test `Ifpack2_Cheby_belos_MPI_1` test failed in my SEMS Dev Env MPI build of Trilinos.  This was the **only** remaining test in all of the ST packages of Trilinos. I can provide reproducability instructions if needed.

**Comment by mhoemmen** [comment]
> FYI: The test Ifpack2_Cheby_belos_MPI_1 test failed in my SEMS Dev Env MPI build of Trilinos. This was the only remaining test in all of the ST packages of Trilinos. I can provide reproducability instructions if needed.

@bartlettroscoe Was that with a particular count of threads or just the default settings?  Just curious.

**Comment by bartlettroscoe** [comment]
Responding to @mhoemmen from [above comment](@bartlettroscoe Was that with a particular count of threads or just the default settings? Just curious.):

> @bartlettroscoe Was that with a particular count of threads or just the default settings? Just curious.

Not sure. How can you tell? Does this get printed in the test output?

**Comment by mhoemmen** [comment]
You can set the thread count with OpenMP using the OMP_NUM_THREADS environment variable.

**Comment by mhoemmen** [comment]
I'm working on this now.  Don't know what's wrong yet.  It may take me a while.

**Comment by mhoemmen** [comment]
With OMP_NUM_THREADS=2, here is what I found:

  1. Kokkos::fill_random (initial guess for power method iteration that estimates max eigenvalue) was producing perfectly reasonable, random-looking numbers between -1 and 1. 
  2. Max eigenvalue estimate quickly became negative in that case.
  3. When I constrained the random numbers to be between 0 and 1, the test passed.

**Comment by mhoemmen** [comment]
Fix works!  Running check-in tests now.

**Comment by mhoemmen** [comment]
Just pushed fix.
