### ISSUE TITLE
MueLu:  type mismatch in residual norm initialization

### ISSUE THREAD

**Issue by ndellingwood** [trilinos/Trilinos#6401]
## Bug Report
@trilinos/muelu 

### Description
Compilation error when complex is enabled with intel/18 compiler and serial build:

```
/ascldap/users/ndellin/IntegrationTests-Blake/serial/trilinos-update/packages/muelu/research/regionMG/examples/structured/Driver_Structured_Regions.cpp(795): error: no suitable conversion function from "std::complex<double>" to "double" exists
      typename Teuchos::ScalarTraits<Scalar>::magnitudeType normResIni = Teuchos::ScalarTraits<Scalar>::zero();
                                                                         ^
          detected during instantiation of "int main_<Scalar,LocalOrdinal,GlobalOrdinal,Node>(Teuchos::CommandLineProcessor &, Xpetra::UnderlyingLib &, int, char **) [with Scalar=std::complex<double>, LocalOrdinal=int, GlobalOrdinal=int, Node=KokkosClassic::DefaultNode::DefaultNodeType]" at line 162 of "/ascldap/users/ndellin/IntegrationTests-Blake/serial/trilinos-update/packages/muelu/research/regionMG/examples/structured/../../../../test/unit_tests/MueLu_Test_ETI.hpp"
```

SHA1:  88f86a2671854a35cd571615057fc436f201beae

Detected on Blake testbed (Skylake arch), Serial build with complex_double enabled, using the following module loads:

```
module load devpack/20171203/openmpi/2.1.2/intel/18.1.163
module swap cmake/3.9.0 cmake/3.10.2
```

**Comment by ndellingwood** [comment]
I can include a fix with kokkos+kokkos-kernels integration testing when it is complete, but that might be a little while yet to wait for a simple fix.

**Comment by cgcgcg** [comment]
@ndellingwood Any particular reason why experimental code is tested during the Kokkos promotion?

**Comment by ndellingwood** [comment]
@cgcgcg we have tested it in past rounds of integration testing so just continuing the same process, but I can disable if the setting is also disabled with ATDM testing.

**Comment by cgcgcg** [comment]
Alright, let's see what @lucbv and @mayrmt want to do..

**Comment by ndellingwood** [comment]
@cgcgcg I may not have phrased my last answer well, just to clarify, if ATDM testing doesn't enable experimental then I don't think we need to and I should disable, but if there are ATDM configurations that test with experimental on then we should probably do this too for consistency.

**Comment by mayrmt** [comment]
@ndellingwood When I did these changes, it was suggested during the review as a future improvement to replace
```
typename Teuchos::ScalarTraits<Scalar>::magnitudeType normResIni = Teuchos::ScalarTraits<Scalar>::zero();
```
with
```
typename Teuchos::ScalarTraits<Scalar>::magnitudeType normResIni {};
```
However, I have no experience with `complex`, so I don't know, if this will help at all. I guess, @lucbv is of more help here.

Of course, I'm happy to assist in fixing this and to learn something new.

**Comment by lucbv** [comment]
@mayrmt 
the issue here is that the left hand side is of type `magnitude` where as the right hand side is of type `Scalar`.
All you need to do is something like this:
```
using magnitude_type = typename Teuchos::ScalarTraits<Scalar>::magnitudeType;
magnitude_type normResIni = Teuchos::ScalarTraits<magnitude_type>::zero();
```

Of course the comment from @mhoemmen is valid and works just fine as it should call the default constructor for your type and initialize the variable value to that type's zero.

You can chose which ever you prefer and I think we should just push this fix directly instead of waiting for @ndellingwood PR as the problem is very minor and easy to correct.

**Comment by mhoemmen** [comment]
@mayrmt Either way is fine.  `magnitude_type` is usually something like `double` or `float`.  If it's not, say for some Sacado type, then hopefully `{}` initialization still does the right thing; if not, that's a bug in Sacado that we should be able to fix easily.

**Comment by mayrmt** [comment]
@ndellingwood PR #6403 should fix this. Sorry for the inconvenience!

@mhoemmen @lucbv Thanks for the explanations.

**Comment by ndellingwood** [comment]
Thanks @mayrmt for quick fix!

**Comment by lucbv** [comment]
I will claim that this can be closed now but if there are still issues feel free to re-open
