### ISSUE TITLE
Supes:  Links to multiple versions of libgfortran

### ISSUE THREAD

**Issue by jrood-nrel** [trilinos/Trilinos#6413]
## Bug Report
@trilinos/supes

### Description
If I build Trilinos with Clang. I get these warnings:
```
/whatever1/bin/ld: warning: libgfortran.so.3, needed by /whatever2/trilinos-develop-imgt6ae2bqw2752jubbuiu6epnznpsbz/lib/libsupes.so.12.17, may conflict with libgfortran.so.4
```
`ldd` shows that `libgfortran.so.4` and `libgfortran.so.3` are indeed both linked. Am I doing something ignorant to cause this? I'm building with Spack if that matters. Since rpath is being used, the conflicts seem benign, but I would like to get rid of the warning if possible.

**Comment by mhoemmen** [comment]
I don't know what a "supes" is, but @trilinos/framework might.

**Comment by lucbv** [comment]
It looks that this is coming from @trilinos/seacas maybe @gsjaardema knows what this is about?

**Comment by gsjaardema** [comment]
I have seen it before with both gcc and clang builds.  It seems to be caused by the fortran version used to build mpifort or openmpi to be different than the gfortran compiler being used.  I haven't noticed problems with it, but haven't yet had a chance to figure out how to fix it.

**Comment by jrood-nrel** [comment]
Thanks @gsjaardema . No problem. I can just ignore the warning then.
