### ISSUE TITLE
TpetraCore_MultiVector_UnitTests_MPI_4 and TpetraCore_gemm_m_eq_<X>_MPI_1 tests in build Trilinos-atdm-sems-rhel7-cuda-9.2-Volta70-complex-shared-release-debug failing starting 2019-12-07 

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#6418]
CC: @trilinos/tpetra, @kddevin (Trilinos Data Services Product Lead), @bartlettroscoe, @fryeguy52, @seheracer

<Checklist>
<???: Add label "client: ATDM">
<???: Add label "ATDM Sev: Blocker" (by default but could be other "ATDM Sev: XXX")>
<???: Add label "type: bug"?>
<???: Add label for affected packages (e.g. "pkg: MueLu", "pkg: Tpetra", "pkg: Kokkos", etc.)>
<???: Add label "PA: ???Project Area???" (e.g. "PA: Linear Solvers", "PA: Data Services")>
<???: Add milestone "Initial cleanup of new ATDM ..." or "Keep promoted ATDM ...">
<???: Once GitHub Issue is created, add entries for tests to TrilinosATDMStatus/*.csv files>

## Next Action Status

<status-and-or-first-action>

## Description

As shown in [this query](https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&begin=2019-11-11&end=2019-12-10&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-sems-rhel7-cuda-9.2-Volta70-complex-shared-release-debug&field2=site&compare2=61&value2=sems-rhel7&field3=block&field3count=2&field3field1=testname&field3compare1=61&field3value1=TpetraCore_MultiVector_UnitTests_MPI_4&field3field2=testname&field3compare2=65&field3value2=TpetraCore_gemm_m_eq_) the tests:

* `TpetraCore_gemm_m_eq_1_MPI_1`
* `TpetraCore_gemm_m_eq_2_MPI_1`
* `TpetraCore_gemm_m_eq_5_MPI_1`
* `TpetraCore_gemm_m_eq_13_MPI_1`
* `TpetraCore_MultiVector_UnitTests_MPI_4`

are failing in build:

* `Trilinos-atdm-sems-rhel7-cuda-9.2-Volta70-complex-shared-release-debug`

starting 2019-12-07.

As shown in [this query](https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&begin=2019-11-11&end=2019-12-10&filtercount=4&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-sems-rhel7-cuda-9.2-Volta70-complex-shared-release-debug&field2=site&compare2=61&value2=sems-rhel7&field3=testname&compare3=65&value3=TpetraCore_gemm_m_eq_&field4=testoutput&compare4=97&value4=FAILED.*%20Blas_std_complex0double0_Gemm_UnitTest), the tests `TpetraCore_gemm_m_eq_<X>_MPI_1` are all failing the unit test `Blas_std_complex0double0_Gemm_UnitTest` showing error output like:

```
     ...
     trans_A: C
     trans_B: N
     A_norm: 1.15513
     B_norm: 0.355242
     C_norm: 1.13028
     bound: 1.77636e-15
     false = 0 == true : FAILED ==> /scratch/jenkins/ascicgpu14/workspace/Trilinos-atdm-sems-rhel7-cuda-9.2-Volta70-complex-shared-release-debug/SRC_AND_BUILD/Trilinos/packages/tpetra/core/test/Blas/gemm.cpp:306
     Comparing KokkosBlas::gemm against Teuchos::BLAS::GEMM: Max error 0.699682 > error bound 1.77636e-15
     false = 0 == true : FAILED ==> /scratch/jenkins/ascicgpu14/workspace/Trilinos-atdm-sems-rhel7-cuda-9.2-Volta70-complex-shared-release-debug/SRC_AND_BUILD/Trilinos/packages/tpetra/core/test/Blas/gemm.cpp:333
     Comparing KokkosBlas::Default::gemm against Teuchos::BLAS::GEMM: Max error 0.699682 > error bound 1.77636e-15
     At least one test FAILED; abandoning the others.
   At least one test FAILED; abandoning the others.
   At least one test FAILED; abandoning the others.
 [FAILED]  (2.47 sec) Blas_std_complex0double0_Gemm_UnitTest
```

As shown in [this query](https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&begin=2019-11-11&end=2019-12-10&filtercount=4&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-sems-rhel7-cuda-9.2-Volta70-complex-shared-release-debug&field2=site&compare2=61&value2=sems-rhel7&field3=testname&compare3=61&value3=TpetraCore_MultiVector_UnitTests_MPI_4&field4=testoutput&compare4=97&value4=FAILED.*MultiVector_int_longlong_std_complex0double0_Kokkos_Compat_KokkosCudaWrapperNode_Multiply_UnitTest), the test `TpetraCore_MultiVector_UnitTests_MPI_4` is failing the unit test `MultiVector_int_longlong_std_complex0double0_Kokkos_Compat_KokkosCudaWrapperNode_Multiply_UnitTest` showing oputput like:

```
88. MultiVector_int_longlong_std_complex0double0_Kokkos_Compat_KokkosCudaWrapperNode_Multiply_UnitTest ... 
 Test: MultiVector, Multiply
  Comparing tmpView(0,9) == check3 ... passed
  Comparing tmpView(0,4) == check2 ... passed
  Comparing tmpView(0,4) == check2 ... passed
  Comparing tmpView(0,9) == check3 ... passed
  gblSuccess == 1 = 1 == true : passed
  Comparing tmpView == sdmView ... passed
  gblSuccess == 1 = 1 == true : passed
  Comparing tmpView == sdmView ... passed
  gblSuccess == 1 = 1 == true : passed
  Comparing tmpView == sdmView ... 
  Error, relErr(tmpView[0],sdmView[0]) = relErr((1.3406,0.995454),(2.15303,0)) = 0.596788 <= tol = 2.22045e-14: failed!
  
  Error, relErr(tmpView[1],sdmView[1]) = relErr((-0.767759,0.205214),(-0.0764208,-0.51095)) = 1.25254 <= tol = 2.22045e-14: failed!
  
  Error, relErr(tmpView[2],sdmView[2]) = relErr((-0.767759,0.205214),(-0.0764208,0.51095)) = 0.951195 <= tol = 2.22045e-14: failed!
  
  Error, relErr(tmpView[3],sdmView[3]) = relErr((-0.18601,0.101217),(0.738326,0)) = 1.25942 <= tol = 2.22045e-14: failed!
  gblSuccess == 1 = 0 == true : FAILED ==> /scratch/jenkins/ascicgpu14/workspace/Trilinos-atdm-sems-rhel7-cuda-9.2-Volta70-complex-shared-release-debug/SRC_AND_BUILD/Trilinos/packages/tpetra/core/test/MultiVector/MultiVector_UnitTests.cpp:815
  Comparing tmpView == sdmView ... passed
  gblSuccess == 1 = 0 == true : FAILED ==> /scratch/jenkins/ascicgpu14/workspace/Trilinos-atdm-sems-rhel7-cuda-9.2-Volta70-complex-shared-release-debug/SRC_AND_BUILD/Trilinos/packages/tpetra/core/test/MultiVector/MultiVector_UnitTests.cpp:828
  Comparing tmpView == check(0,tmpView.size()) ... passed
  Comparing tmpView == check(0,tmpView.size()) ... passed
  Comparing tmpView == check(0,tmpView.size()) ... passed
  Comparing tmpView == check(0,tmpView.size()) ... passed
  gblSuccess == 1 = 0 == true : FAILED ==> /scratch/jenkins/ascicgpu14/workspace/Trilinos-atdm-sems-rhel7-cuda-9.2-Volta70-complex-shared-release-debug/SRC_AND_BUILD/Trilinos/packages/tpetra/core/test/MultiVector/MultiVector_UnitTests.cpp:861
  Comparing tmpView == check2 ... passed
  Comparing tmpView == check3 ... passed
  gblSuccess == 1 = 0 == true : FAILED ==> /scratch/jenkins/ascicgpu14/workspace/Trilinos-atdm-sems-rhel7-cuda-9.2-Volta70-complex-shared-release-debug/SRC_AND_BUILD/Trilinos/packages/tpetra/core/test/MultiVector/MultiVector_UnitTests.cpp:888
 [FAILED]  (0.0303 sec) MultiVector_int_longlong_std_complex0double0_Kokkos_Compat_KokkosCudaWrapperNode_Multiply_UnitTest
 Location: /scratch/jenkins/ascicgpu14/workspace/Trilinos-atdm-sems-rhel7-cuda-9.2-Volta70-complex-shared-release-debug/SRC_AND_BUILD/Trilinos/packages/tpetra/core/test/MultiVector/MultiVector_UnitTests.cpp:707
```

The new commits that were pulled on the testing day 2019-12-07 as shown [here](https://testing-dev.sandia.gov/cdash/viewNotes.php?buildid=5069857#!#note6).  Looking over that set of commits, the commits most likely to have triggered this failuire are:

```
d3a22b1:  Add beta=0 case and allow number of teams smaller than 32 to resolve NaN and diff issues in some Teko and ShyLu tests.
Author: Seher Acer <sacer@sandia.gov>
Date:   Wed Dec 4 21:10:29 2019 -0700

M	packages/kokkos-kernels/src/impl/tpls/KokkosBlas3_gemm_tpl_spec_decl.hpp

e5f7c38:  KokkosKernels: Optimized GEMM (over CUBLAS GEMM) for A^TB with tall and skinny matrices on CUDA.
Author: Seher Acer <sacer@sandia.gov>
Date:   Tue Nov 5 19:47:58 2019 -0700

M	packages/kokkos-kernels/src/impl/tpls/KokkosBlas3_gemm_tpl_spec_decl.hpp
```

pulled in from PR #6226 by @seheracer.

## Current Status on CDash

* [`TpetraCore_MultiVector_UnitTests_MPI_4` and `TpetraCore_gemm_m_eq_<X>_MPI_1` tests in build Trilinos-atdm-sems-rhel7-cuda-9.2-Volta70-complex-shared-release-debug for current testing day](https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-sems-rhel7-cuda-9.2-Volta70-complex-shared-release-debug&field2=site&compare2=61&value2=sems-rhel7&field3=block&field3count=2&field3field1=testname&field3compare1=61&field3value1=TpetraCore_MultiVector_UnitTests_MPI_4&field3field2=testname&field3compare2=65&field3value2=TpetraCore_gemm_m_eq_)

## Steps to Reproduce

One should be able to reproduce this failure on a CEE LAN `ascicgpu<NUM>` 'sems-rhel7' as described in:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md

More specifically, the commands given for the system CEE LAN `ascicgpu<NUM>` 'sems-rhel7' are provided at:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#sems-rhel7-environment

The exact commands to reproduce this issue should be:

```
$ cd <some_build_dir>/

$ source $TRILINOS_DIR/cmake/std/atdm/load-env.sh \
  Trilinos-atdm-sems-rhel7-cuda-9.2-Volta70-complex-shared-release-debug

$ cmake \
 -GNinja \
 -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
 -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_TpetraCore=ON \
 $TRILINOS_DIR

$ make NP=16

$ ctest -j4
```

**Comment by bartlettroscoe** [comment]
@srajama1 and @kddevin,

FYI: This issue took me about 45 minutes to triage and create.

**Comment by bartlettroscoe** [comment]
FYI: I pushed the following commit to the https://gitlab-ex.sandia.gov/atdm/TrilinosATDMStatus git repo:

```
d8d1603 "Add entries for TpetraCore tests for trilinos/Trilinos#6418"
Author: Roscoe A. Bartlett <rabartl@sandia.gov>
Date:   Tue Dec 10 09:28:20 2019 -0700 (3 minutes ago)

M       promotedAtdmTrilinosTestsWithIssueTrackers.csv
```

**Comment by kddevin** [comment]
@srajama1 @trilinos/kokkos-kernels

**Comment by kddevin** [comment]
@srajama1 @seheracer Was there a change to gemm that requires changes to Tpetra?

**Comment by seheracer** [comment]
@kddevin I don't think this problem is due to Tpetra.

@srajama1 I think I should trace what the new gemm does on these failing test, but on which machine?

**Comment by bartlettroscoe** [comment]
WE need to determine if GEMMA is using the Tpetra GEMM algorithm to know if this a problem for ATDM or not.

**Comment by ndellingwood** [comment]
@seheracer since this is Volta70 I'm assuming this was on Waterman

**Comment by ndellingwood** [comment]
@seheracer scratch my previous comment - CDash shows this was on some sems-rhel7 resource, though you may be able to try testing on waterman to get started if you don't have access to sems-rhel7.

@william76 can you help with a testing question - how do devs get access to sems-rhel7 testing resources?

**Comment by bartlettroscoe** [comment]
>  how do devs get access to sems-rhel7 testing resources?

@ndellingwood, the 'sems-rhel7' builds run on the CEE LAN machine 'ascicgpu14' and local builds are done on the identical machine 'ascicgpu15'.  To access that machine, you need a CEE LAN machine and then get added to the access list for 'ascicgpu15'.  For info on how to do that, please contact me offline.

**Comment by bartlettroscoe** [comment]
> since this is Volta70 I'm assuming this was on Waterman

No, this is actually and Intel x86 processor with a Volta GPU.  Note the comment above:

> One should be able to reproduce this failure on a CEE LAN `ascicgpu<NUM>` 'sems-rhel7' as described in:
>
> * https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md

**Comment by william76** [comment]
@ndellingwood @bartlettroscoe 
I generally use the RHEL compute systems on CEE.  I also know of a couple servers that have the SEMS modules on it too that I use.

Here's a list of the SEMS computing resources:
https://sems-atlassian-son.sandia.gov/confluence/display/SEMSTEAM/Computing+Resources

Probably the system you'd want is `sems-son-rhel7-login-01` or `sems-srn-rhel7-login-01`.  My understanding is that you can just use your kerberos to log into it without having any extra hoops to jump through for an account.

**Comment by ndellingwood** [comment]
@bartlettroscoe thanks for the fast responses, I'll follow up with an email.

@william76 thanks for the info and fast response, I was able to login to the systems you mentioned, but it doesn't look like there are GPUs available:

```
[ndellin@sems-son-rhel7-login-01 ~]$ nvidia-smi
bash: nvidia-smi: command not found...
```

@seheracer while we figure out machine access, can you kick off a build on waterman? Since the changes referenced only affect runs on the GPU hopefully a build on a system with Volta GPUs will be sufficient to reproduce. I think if you modify Ross's build instructions like below that should prepare a similar configuration:

```
$ source $TRILINOS_DIR/cmake/std/atdm/load-env.sh \
  Trilinos-atdm-waterman-cuda-9.2-release-debug

$ cmake \
 -GNinja \
 -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
 -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_TpetraCore=ON \
 -DTrilinos_ENABLE_COMPLEX=ON\
 $TRILINOS_DIR
```

**Comment by seheracer** [comment]
@ndellingwood Unfortunately, I don't have access to waterman. I heard that it is not an SON machine.

**Comment by ndellingwood** [comment]
@seheracer my mistake, I'll email you about finding alternative testing resources.

**Comment by william76** [comment]
@ndellingwood for GPU shouldn't you use a Testbed?

**Comment by bartlettroscoe** [comment]
> for GPU shouldn't you use a Testbed?

@william76, we don't always see the same behavior with a Power+GPU vs. an Intel+GPU system.   I don't know of any SEMS SON machines that have a Volta GPU.

**Comment by william76** [comment]
Yeah... I don't think any of the SEMS machines have GPUs... the word from SEMS folks is that if GPUs are needed for SEMS machines for things like CI, then maybe submit a change request to the SEMS help desk and they'll look into it :p

**Comment by ndellingwood** [comment]
> @ndellingwood for GPU shouldn't you use a Testbed?

@william76 yes that is an option, but I was trying to track down a resource where we can match the environment where the failures occur.

**Comment by seheracer** [comment]
I have just reproduced the errors, started debugging..

**Comment by seheracer** [comment]
I figured out the problem: I had mistakenly used the exact same GEMM algorithm for transpose and conjugate-transpose cases of A. I'm surprised by this code having passed the Trilinos tests before. I will push a PR tonight to fix this.

**Comment by bartlettroscoe** [comment]
> I figured out the problem: I had mistakenly used the exact same GEMM algorithm for transpose and conjugate-transpose cases of A. I'm surprised by this code having passed the Trilinos tests before. I will push a PR tonight to fix this.

@seheracer, would it be possible to add a new test to KokkosKernels that exposes this defect with OpenMP only?  That way the Trilinos PR tester builds will catch defects like this in the future.

I think that is the official Trilinos policy as stated in:

* https://github.com/trilinos/Trilinos/wiki/Trilinos-Testing-Policy

The test suite for KokkosKernels should be comprehensive in its own right.  It should not rely on testing in Tpetra or other Trilinos packages to assert its correctness.

**Comment by mhoemmen** [comment]
@seheracer I don't think it's too hard to add a test -- you could just compare against the system BLAS directly.  That's what the failing test did.  You don't even need to run cuBLAS -- just copy to host and call the system BLAS.

**Comment by bartlettroscoe** [comment]
Just an FYI, but our policy is that we don't close issues until we get confirmation from results posted to CDash.  See:

* https://snl-wiki.sandia.gov/display/CoodinatedDevOpsATDM/Triaging+and+Addressing+ATDM+Trilinos+Failures#TriagingandAddressingATDMTrilinosFailures-7.CloseaResolvedTrilinosGitHubIssue:

Reopening until we get confirmation on CDash.  The earliest that can occur is Sunday morning since this will not get run in ATDM Trilinos testing until tomorrow.

**Comment by ndellingwood** [comment]
@bartlettroscoe it looks like the auto-tester was the culprit for closing this automatically, at odds with the policy you cited. @trilinos/framework

**Comment by bartlettroscoe** [comment]
> it looks like the auto-tester was the culprit for closing this automatically, at odds with the policy you cited. 

@ndellingwood, I don't think the Trilinos auto-tester Jenkins job itself closes issues.  I think GitHub does that automatically when a PR is merged that contains `Fixes #<issue-id>` in the PR text or one of the commits has text `Fixes #<issueid>`.

**Comment by ndellingwood** [comment]
> @ndellingwood, I don't think the Trilinos auto-tester Jenkins job itself closes issues. I think GitHub does that automatically when a PR is merged that contains `Fixes #<issue-id>` in the PR text or one of the commits has text `Fixes #<issueid>`.

@bartlettroscoe I didn't realize that, thanks for clearing up my misunderstanding.

**Comment by bartlettroscoe** [comment]
According to [this query](https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&begin=2019-12-01&end=2020-01-11&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-sems-rhel7-cuda-9.2-Volta70-complex-shared-release-debug&field2=site&compare2=61&value2=sems-rhel7&field3=block&field3count=2&field3field1=testname&field3compare1=61&field3value1=TpetraCore_MultiVector_UnitTests_MPI_4&field3field2=testname&field3compare2=65&field3value2=TpetraCore_gemm_m_eq_), these tests have been passing every day since 2019-12-13 where they were failing every day before that.

If I had to guess, I think that PR #??? merged on 2019-12-12 is what fixed this.  I can't see anything else merged on 2019-12-12 that would have impacted TpetraCore_gemm tests.

Closing as complete.
