### ISSUE TITLE
Compilation of Trilinos fails due to Xpetra

### ISSUE THREAD

**Issue by anates** [trilinos/Trilinos#6428]
When compiling Trilinos without external packages, just enabling internal packages, the compilation fails for the package xpetra, mainly with errors like 
`~/Downloads_GCC7/Trilinos/packages/xpetra/src/Vector/Xpetra_TpetraVector_def.hpp:74:15: error: invalid use of incomplete type 'class Xpetra::TpetraVector<S, LO, GO, N>'`
Thus I assume I missed a switch somewhere, but can not find it atm. Error output and CMakeCache-file are attached.
[build_error.log](https://github.com/trilinos/Trilinos/files/3949436/build_error.log)
[CMakeCache.txt](https://github.com/trilinos/Trilinos/files/3949437/CMakeCache.txt)

**Comment by ndellingwood** [comment]
@anates which SHA of Trilinos are you using? I ran into this issue (cross-referencing #6314 #6404) and @william76 recently pushed in a fix in PR #6414

**Comment by anates** [comment]
I am using 50ff9ab8b574944b741f10ac972a832f7e1afc8f. Enabling ETI explicitely for every package helped, but led to additional problems in ShyLU. When disabling that, it worked.

**Comment by william76** [comment]
@anates 
There has been some activity recently trying to track down some of these reference issues in Xpetra with and without ETI enabled... if you haven't updated in a while, you might want to update your develop branch too.

If you're still having problems using the latest develop or master branches, can you post your configuration line as well as information on any libraries you're loading as well?

**Comment by anates** [comment]
Ran into different problems now, could not reproduce that problem in the latest patches. Thus I'll close that issue for now
