### ISSUE TITLE
MueLu: build failure in unit_tests/RegionMatrix with KokkosRefactor disabled

### ISSUE THREAD

**Issue by mayrmt** [trilinos/Trilinos#6442]
## Bug Report
@trilinos/muelu @lucbv 

### Description

When building the regionMG unit tests in `packages/muelu/test/unit_tests/RegionMatrix.cpp`, the line
https://github.com/trilinos/Trilinos/blob/acd133cc41cdf910c5d2dcc9757e219b031f7c19/packages/muelu/test/unit_tests/RegionMatrix.cpp#L363
causes trouble if one does not configure with `-D MueLu_ENABLE_Kokkos_Refactor:BOOL=ON` and `-D Xpetra_ENABLE_Kokkos_Refactor:BOOL=ON`. Then, the build error reads:
```bash
/Users/mayr/research/codes/mayrmt_trilinos/src-trilinos/packages/muelu/test/unit_tests/RegionMatrix.cpp: In instantiation of 'void MueLuTests::RegionMatrix_CompositeToRegionMatrix_UnitTest<Scalar, LocalOrdinal, GlobalOrdinal, Node>::runUnitTestImpl(Teuchos::FancyOStream&, bool&) const [with Scalar = double; LocalOrdinal = int; GlobalOrdinal = int; Node = Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial>; Teuchos::FancyOStream = Teuchos::basic_FancyOStream<char>]':
/Users/mayr/research/codes/mayrmt_trilinos/src-trilinos/packages/muelu/test/unit_tests/../../src/Utils/MueLu_ETI_4arg.hpp:42:3:   required from here
/Users/mayr/research/codes/mayrmt_trilinos/src-trilinos/packages/muelu/test/unit_tests/RegionMatrix.cpp:363:9: error: no type named 'local_matrix_type' in 'class Xpetra::Matrix<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial> >'
  363 |   using local_matrix_type = typename Xpetra::Matrix<Scalar, LocalOrdinal, GlobalOrdinal, Node>::local_matrix_type;
      |         ^~~~~~~~~~~~~~~~~
```

Enabling the Kokkos_refactor flag makes the build pass.

### Steps to Reproduce
1. SHA1:  1201bbf76419a188b90338ad6fe8afa4e1451ed0
1. Configure script:  
[do-configure-trilinos_muelu_spack.txt](https://github.com/trilinos/Trilinos/files/3954616/do-configure-trilinos_muelu_spack.txt)
1. Configure log:  
[do-configure.log](https://github.com/trilinos/Trilinos/files/3954626/do-configure.log)
1. Build log:  build error is reported above.

### Additional Information

- The regionMG framework is fully guarded by `-D MueLu_ENABLE_Experimental`.
- `MueLu_UnitTestsRegion_MPI_1` and `MueLu_UnitTestsRegion_MPI_4`are passing, so from a testing perspective everything is ok.

**Comment by mayrmt** [comment]
@lucbv For me, it's ok to build with Kokkos_refactor enabled. We still might want to properly guard this for those users, who disable Kokkos_refactor of MueLu/Xpetra. What do you think?

**Comment by lucbv** [comment]
Yep that's a fair comment, I will add appropriate guard around the code.

**Comment by mayrmt** [comment]
I just built with MueLu Kokkos refactor disabled. Build passes. Hence, this issue can be closed.
