### ISSUE TITLE
NOX:  misleading indentation, possibly missing braces

### ISSUE THREAD

**Issue by brian-kelley** [trilinos/Trilinos#6446]
## Bug Report
@trilinos/nox 

### Description
On line 324 of packages/nox/test/tpetra/ME_Tpetra_1DFEM_def.hpp:
```
    // Create ghosted objects
    if (is_null(uPtr_))
      uPtr_ = Teuchos::rcp(new tpetra_vec(xGhostedMap_));
      uPtr_->modify_host();
      uPtr_->doImport(*(tpetra_extract::getConstTpetraVector(inArgs.get_x())), *importer_, Tpetra::REPLACE);

    if (is_null(xPtr_)) {
      xPtr_ = Teuchos::rcp(new tpetra_vec(xGhostedMap_));
      xPtr_->modify_host();
      xPtr_->doImport(*nodeCoordinates_, *importer_, Tpetra::INSERT);
    }
```
Either there should be curly braces covering the 3 lines after ``if(is_null(uPtr_))``, or the 2nd and 3rd lines should not be indented. Based on the other if right below it, it's probably missing the braces.

**Comment by mhoemmen** [comment]
I don't understand why @trilinos/nox would want to mark `uPtr_` as modified on host, right before doing an Import to it.  Is the intent to force MPI to use host buffers for MPI communication?  There are other ways of doing that that still do pack and unpack on device.  @rppawlo might know about this.

**Comment by rppawlo** [comment]
@mhoemmen - Thanks for finding this. I can't answer your question, it was written by a postdoc a few years ago. I will look into fixing that shortly.

**Comment by rppawlo** [comment]
This was fixed over a year ago. closing.
