### ISSUE TITLE
Tpetra: Test TpetraCore_AddProfiling_UnitTests_MPI_4 removed on purpose?

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#6449]
## Question
@trilinos/tpetra 

FYI: The post-push CI build just sent out the following auto email showing that the test TpetraCore_AddProfiling_UnitTests_MPI_4 has been removed.  You can see this at:

* https://testing.sandia.gov/cdash/viewTest.php?buildid=6053771

Was this test removed on purpose?

----

From: admin@cdash.org <admin@cdash.org> 
Sent: Friday, December 13, 2019 3:53 AM
To: Bartlett, Roscoe A <rabartl@sandia.gov>
Subject: [EXTERNAL] FAILED (t=0, m=1): Trilinos - Linux-GCC-4.8.4-MPI_RELEASE_DEBUG_SHARED_PT_OPENMP_CI - Continuous

A submission to CDash for the project Trilinos has failing tests and missing tests. You have been identified as one of the authors who have checked in changes that are part of this submission or you are listed in the default contact list.

Details on the submission can be found at https://testing.sandia.gov/cdash/buildSummary.php?buildid=6053744.

Project: Trilinos
Site: ceerws1113
Build Name: Linux-GCC-4.8.4-MPI_RELEASE_DEBUG_SHARED_PT_OPENMP_CI
Build Time: 2019-12-13 07:54:43
Type: Continuous
Total Failing Tests: 0
Total Missing Tests: 1

*Failing Tests* 

*Missing Tests* 
TpetraCore_AddProfiling_UnitTests_MPI_4 (https://testing.sandia.gov/cdash/viewTest.php?buildid=6053771)

-CDash on testing.sandia.gov

**Comment by brian-kelley** [comment]
@bartlettroscoe Yes, I did that in #6433. It was misnamed (unit tests, not performance tests), and those tests really belonged in MatrixMatrix_UnitTests.cpp, so I moved them there.

**Comment by brian-kelley** [comment]
@bartlettroscoe I didn't know you got notifications for missing tests. Is there a certain procedure for removing one, without it getting marked as missing?

**Comment by bartlettroscoe** [comment]
> I didn't know you got notifications for missing tests. Is there a certain procedure for removing one, without it getting marked as missing?

Not that I know of.  This was a feature added to CDash to help catch cases where tests got disabled by accident and people did not know for months (which happened once on the CASL project and had a big negative impact).  Not a big deal.
