### ISSUE TITLE
Kokkos-kernels: compilation failure on Ride with CUDA 

### ISSUE THREAD

**Issue by ikalash** [trilinos/Trilinos#6450]
My nightly build of Trilinos (for Albany) on Ride failed last night due to a Kokkos-kernels error: 

```
/.../repos/Trilinos/packages/kokkos-kernels/src/graph/KokkosGraph_Distance1ColorHandle.hpp(527): error: no instance of overloaded function "KokkosKernels::Impl::get_suggested_team_size" matches the argument list
```
http://cdash.sandia.gov/CDash-2-3-0/viewBuildError.php?buildid=91686 

Could someone please look into this?  Here are the modules being used: 

https://github.com/SNLComputation/Albany/blob/master/doc/dashboards/ride.sandia.gov/ride_modules_cuda.sh

@trilinos/kokkos-kernels

**Comment by ndellingwood** [comment]
@brian-kelley would changes in kokkos-kernels with your ifpack2 PR #6439 be at play? It looks like some updates to `get_suggested_team_size` got cherry-picked in, but the accompanying changes to the call in the d1 color handle were missed?

**Comment by ndellingwood** [comment]
@ikalash we should have a PR ready shortly

**Comment by ndellingwood** [comment]
@ikalash PR #6451 should fix this issue, sorry for the inconvenience.

**Comment by ikalash** [comment]
No problem - thanks for fixing it so fast!  I'll close the issue once our Ride build is back to normal.

**Comment by ndellingwood** [comment]
PR #6451 merged into develop

**Comment by ikalash** [comment]
It's fixed - closing.
