### ISSUE TITLE
STK Mac build requires long; long long - a new clash with Tpetra

### ISSUE THREAD

**Issue by spdomin** [trilinos/Trilinos#6460]
## Bug Report
@trilinos/stk

### Description
I have a new error on my Nalu Mac build:

-- Tpetra: Validate global ordinal setting ...
CMake Error at packages/tpetra/CMakeLists.txt:1153 (MESSAGE):
  Tpetra requires only one global ordinal, but more than one are set:
  {long;long long}.

As I recall, I was required to activate long and long long for a STK Mac nuance related to STK_transfer (or search, or some other unit test clash).

Wondering how to proceed now? I will re-build now without long long to familiarize myself with the former Mac/STK nuance and report back.

**Comment by spdomin** [comment]
I can not find a closed issue on this subject. As such, this must have been a discussion offline, however, I can recall @alanw0 and @mhoemmen being part of the discussion.

**Comment by spdomin** [comment]
Okay, found it... This was related to stk-balance and the requirement of this package on long-long. However, as far as I can tell, this requirement was removed on April 12... I suppose I simply needed to update my config file.

Closing now..

**Comment by mhoemmen** [comment]
Thanks @spdomin !  Glad it worked out!  We just merged the "remove deprecated code" PR #6388.  Those changes now require that users only enable one GlobalOrdinal type.
