### ISSUE TITLE
Teko_testdriver_tpetra_MPI_4 randomly timing out/hanging in all CUDA 'waterman' builds starting 2019-11-14

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#6463]
CC: @trilinos/teko, @srajama1  (Trilinos Linear Solvers Product Lead), @bartlettroscoe, @fryeguy52

<Checklist>
<???: Add label "client: ATDM">
<???: Add label "ATDM Sev: Blocker" (by default but could be other "ATDM Sev: XXX")>
<???: Add label "type: bug"?>
<???: Add label for affected packages (e.g. "pkg: MueLu", "pkg: Tpetra", "pkg: Kokkos", etc.)>
<???: Add label "PA: ???Project Area???" (e.g. "PA: Linear Solvers", "PA: Data Services")>
<???: Add milestone "Initial cleanup of new ATDM ..." or "Keep promoted ATDM ...">
<???: Once GitHub Issue is created, add entries for tests to TrilinosATDMStatus/*.csv files>

## Next Action Status

<status-and-or-first-action>

## Description

As shown in [this query](https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&begin=2019-08-01&end=2019-12-17&filtercount=5&showfilters=1&filtercombine=and&field1=groupname&compare1=62&value1=Experimental&field2=buildname&compare2=65&value2=Trilinos-atdm-&field3=testname&compare3=61&value3=Teko_testdriver_tpetra_MPI_4&field4=status&compare4=61&value4=failed&field5=testoutput&compare5=96&value5=cudaErrorUnknown) and [this query](https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&begin=2019-08-01&end=2019-12-17&filtercount=5&showfilters=1&filtercombine=and&field1=groupname&compare1=62&value1=Experimental&field2=buildname&compare2=65&value2=Trilinos-atdm-&field3=testname&compare3=61&value3=Teko_testdriver_tpetra_MPI_4&field4=status&compare4=61&value4=failed&field5=testoutput&compare5=97&value5=Running%20test%20.LSCIntegrationTest_tpetra.) over the time period [2019-08-01, 2019-12-17], the test:

* `Teko_testdriver_tpetra_MPI_4`

in the builds:

* `Trilinos-atdm-waterman_cuda-9.2_fpic_static_opt`
* `Trilinos-atdm-waterman_cuda-9.2_shared_opt`
* `Trilinos-atdm-waterman-cuda-9.2-debug`
* `Trilinos-atdm-waterman-cuda-9.2-opt`
* `Trilinos-atdm-waterman-cuda-9.2-rdc-release-debug`
* `Trilinos-atdm-waterman-cuda-9.2-release-debug`

started randomly timing out (or hanging) on testing day 2019-11-14.  It randomly timed out (or hung) a total of 29 times between 2019-11-14 and 2019-12-17 in those 6 builds.  (Therefore, it times out only occasionally).

As shown in [this query](https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&begin=2019-11-10&end=2019-12-17&filtercount=3&showfilters=1&filtercombine=and&field1=groupname&compare1=62&value1=Experimental&field2=buildname&compare2=65&value2=Trilinos-atdm-waterman-cuda-&field3=testname&compare3=61&value3=Teko_testdriver_tpetra_MPI_4), the runtimes over the time period [2019-11-10, 2019-12-17] for this test are very erratic.  When it passes, it can pass in just over a minute and take between the lowest time and timing out at 10 minutes.  Since these CUAA builds now all use `ctest -j4` (see #6051) and since this is an MPI-4 test, this test should be running by itself on its own node on its own GPU.  So the big differences may be due to non-determinism in the code.

There is no sense in looking for commits that could have triggered this as this is a rarely randomly failing test.

## Current Status on CDash

* [Teko_testdriver_tpetra_MPI_4 in 'waterman' CUDA builds over last 30 days](https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&begin=30%20days%20ago&end=now&filtercount=3&showfilters=1&filtercombine=and&field1=groupname&compare1=62&value1=Experimental&field2=buildname&compare2=65&value2=Trilinos-atdm-waterman-cuda-&field3=testname&compare3=61&value3=Teko_testdriver_tpetra_MPI_4)

## Steps to Reproduce

One should be able to reproduce this failure on the machine 'waterman' as described in:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md

More specifically, the commands given for the system 'waterman' are provided at:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#waterman:

The exact commands to reproduce this issue should be:

```
$ cd <some_build_dir>/

$ source $TRILINOS_DIR/cmake/std/atdm/load-env.sh \
    Trilinos-atdm-waterman-cuda-9.2-debug

$ cmake \
 -GNinja \
 -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
 -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_Teko=ON \
 $TRILINOS_DIR

$ make NP=16

$ bsub -x -Is -n 20  ctest -j4
```

However, given this is a rarely randomly failing test, this could be hard to reproduce.

**Comment by bartlettroscoe** [comment]
For example, for the build `Trilinos-atdm-waterman-cuda-9.2-opt` over the time period [2019-11-10, 2019-12-17], the runtimes varied between 1m 19s to 9m 25s and timing out once at 10m a shown in [this query](https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&begin=2019-11-10&end=2019-12-17&filtercount=3&showfilters=1&filtercombine=and&field1=groupname&compare1=62&value1=Experimental&field2=buildname&compare2=61&value2=Trilinos-atdm-waterman-cuda-9.2-opt&field3=testname&compare3=61&value3=Teko_testdriver_tpetra_MPI_4) showing:

 Test Name | Status | Time | Details | Build Time 
 -- | -- | -- | -- | -- 
 Teko_testdriver_tpetra_MPI_4 | Passed | 2m 52s 190ms | Completed | 2019-12-17T05:42:06 MST 
 Teko_testdriver_tpetra_MPI_4 | Passed | 3m 27s 500ms | Completed | 2019-12-16T05:41:44 MST 
 Teko_testdriver_tpetra_MPI_4 | Passed | 1m 58s 260ms | Completed | 2019-12-15T05:40:58 MST 
 Teko_testdriver_tpetra_MPI_4 | Passed | 2m 8s 590ms | Completed | 2019-12-14T07:51:59 MST 
 Teko_testdriver_tpetra_MPI_4 | Passed | 1m 25s 420ms | Completed | 2019-12-13T08:02:43 MST 
 Teko_testdriver_tpetra_MPI_4 | Passed | 1m 49s 940ms | Completed | 2019-12-12T11:56:11 MST 
 Teko_testdriver_tpetra_MPI_4 | Passed | 1m 49s 940ms | Completed | 2019-12-12T11:56:11 MST 
 Teko_testdriver_tpetra_MPI_4 | Passed | 1m 49s 940ms | Completed | 2019-12-12T11:56:11 MST 
 Teko_testdriver_tpetra_MPI_4 | Passed | 3m 27s 910ms | Completed | 2019-12-11T15:37:39 MST 
 Teko_testdriver_tpetra_MPI_4 | Passed | 6m 27s 930ms | Completed | 2019-12-10T06:55:50 MST 
 Teko_testdriver_tpetra_MPI_4 | Passed | 1m 29s 580ms | Completed | 2019-12-09T11:53:35 MST 
 Teko_testdriver_tpetra_MPI_4 | Passed | 1m 29s 580ms | Completed | 2019-12-09T11:53:35 MST 
 Teko_testdriver_tpetra_MPI_4 | Failed | 10m 170ms | Completed (Timeout) | 2019-12-08T16:04:17 MST 
 Teko_testdriver_tpetra_MPI_4 | Passed | 4m 41s 560ms | Completed | 2019-12-07T12:20:47 MST 
 Teko_testdriver_tpetra_MPI_4 | Passed | 3m 24s 180ms | Completed | 2019-12-06T12:23:17 MST 
 Teko_testdriver_tpetra_MPI_4 | Passed | 2m 20s 200ms | Completed | 2019-12-01T05:51:45 MST 
 Teko_testdriver_tpetra_MPI_4 | Passed | 2m 8s 190ms | Completed | 2019-11-30T05:42:14 MST 
 Teko_testdriver_tpetra_MPI_4 | Passed | 5m 14s 390ms | Completed | 2019-11-29T05:53:42 MST 
 Teko_testdriver_tpetra_MPI_4 | Passed | 1m 19s 560ms | Completed | 2019-11-28T07:40:39 MST 
 Teko_testdriver_tpetra_MPI_4 | Passed | 6m 5s 180ms | Completed | 2019-11-27T08:01:25 MST 
 Teko_testdriver_tpetra_MPI_4 | Passed | 3m 7s 630ms | Completed | 2019-11-26T08:10:31 MST 
 Teko_testdriver_tpetra_MPI_4 | Passed | 2m 27s 620ms | Completed | 2019-11-25T05:37:06 MST 
 Teko_testdriver_tpetra_MPI_4 | Passed | 6m 32s 150ms | Completed | 2019-11-24T06:19:52 MST 
 Teko_testdriver_tpetra_MPI_4 | Passed | 7m 30s 680ms | Completed | 2019-11-23T08:49:22 MST 
 Teko_testdriver_tpetra_MPI_4 | Passed | 4m 49s 450ms | Completed | 2019-11-22T06:04:22 MST 
 Teko_testdriver_tpetra_MPI_4 | Passed | 1m 42s 400ms | Completed | 2019-11-21T06:05:21 MST 
 Teko_testdriver_tpetra_MPI_4 | Passed | 4m 5s 480ms | Completed | 2019-11-20T08:26:50 MST 
 Teko_testdriver_tpetra_MPI_4 | Passed | 3m 56s 690ms | Completed | 2019-11-19T07:48:22 MST 
 Teko_testdriver_tpetra_MPI_4 | Passed | 8m 23s 930ms | Completed | 2019-11-18T05:49:06 MST 
 Teko_testdriver_tpetra_MPI_4 | Passed | 9m 25s 50ms | Completed | 2019-11-17T05:50:44 MST 
 Teko_testdriver_tpetra_MPI_4 | Passed | 3m 19s 200ms | Completed | 2019-11-16T16:48:54 MST 
 Teko_testdriver_tpetra_MPI_4 | Passed | 2m 14s 750ms | Completed | 2019-11-15T09:17:58 MST 
 Teko_testdriver_tpetra_MPI_4 | Passed | 5m 19s 500ms | Completed | 2019-11-14T07:44:48 MST 

But compare this to the runtimes for the test `Teko_StridedEpetraOperator_test_MPI_4` in that same build `Trilinos-atdm-waterman-cuda-9.2-opt` over that same time period which shows times between 4s and 19s in [this query](https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&begin=2019-11-10&end=2019-12-17&filtercount=3&showfilters=1&filtercombine=and&field1=groupname&compare1=62&value1=Experimental&field2=buildname&compare2=61&value2=Trilinos-atdm-waterman-cuda-9.2-opt&field3=testname&compare3=61&value3=Teko_StridedEpetraOperator_test_MPI_4) showing the times:

 Test Name | Status | Time | Details | Build Time 
 -- | -- | -- | -- | -- 
 Teko_StridedEpetraOperator_test_MPI_4 | Passed | 7s 200ms | Completed | 2019-12-17T05:42:06 MST 
 Teko_StridedEpetraOperator_test_MPI_4 | Passed | 5s 270ms | Completed | 2019-12-16T05:41:44 MST 
 Teko_StridedEpetraOperator_test_MPI_4 | Passed | 5s 60ms | Completed | 2019-12-15T05:40:58 MST 
 Teko_StridedEpetraOperator_test_MPI_4 | Passed | 5s 170ms | Completed | 2019-12-14T07:51:59 MST 
 Teko_StridedEpetraOperator_test_MPI_4 | Passed | 10s 190ms | Completed | 2019-12-13T08:02:43 MST 
 Teko_StridedEpetraOperator_test_MPI_4 | Passed | 4s 510ms | Completed | 2019-12-12T11:56:11 MST 
 Teko_StridedEpetraOperator_test_MPI_4 | Passed | 4s 510ms | Completed | 2019-12-12T11:56:11 MST 
 Teko_StridedEpetraOperator_test_MPI_4 | Passed | 4s 510ms | Completed | 2019-12-12T11:56:11 MST 
 Teko_StridedEpetraOperator_test_MPI_4 | Passed | 9s 60ms | Completed | 2019-12-11T15:37:39 MST 
 Teko_StridedEpetraOperator_test_MPI_4 | Passed | 5s 870ms | Completed | 2019-12-10T06:55:50 MST 
 Teko_StridedEpetraOperator_test_MPI_4 | Passed | 7s 260ms | Completed | 2019-12-09T11:53:35 MST 
 Teko_StridedEpetraOperator_test_MPI_4 | Passed | 7s 260ms | Completed | 2019-12-09T11:53:35 MST 
 Teko_StridedEpetraOperator_test_MPI_4 | Passed | 5s 440ms | Completed | 2019-12-08T16:04:17 MST 
 Teko_StridedEpetraOperator_test_MPI_4 | Passed | 19s 670ms | Completed | 2019-12-07T12:20:47 MST 
 Teko_StridedEpetraOperator_test_MPI_4 | Passed | 4s 770ms | Completed | 2019-12-06T12:23:17 MST 
 Teko_StridedEpetraOperator_test_MPI_4 | Passed | 4s 930ms | Completed | 2019-12-01T05:51:45 MST 
 Teko_StridedEpetraOperator_test_MPI_4 | Passed | 8s | Completed | 2019-11-30T05:42:14 MST 
 Teko_StridedEpetraOperator_test_MPI_4 | Passed | 5s 170ms | Completed | 2019-11-29T05:53:42 MST 
 Teko_StridedEpetraOperator_test_MPI_4 | Passed | 5s 30ms | Completed | 2019-11-28T07:40:39 MST 
 Teko_StridedEpetraOperator_test_MPI_4 | Passed | 5s 200ms | Completed | 2019-11-27T08:01:25 MST 
 Teko_StridedEpetraOperator_test_MPI_4 | Passed | 4s 650ms | Completed | 2019-11-26T08:10:31 MST 
 Teko_StridedEpetraOperator_test_MPI_4 | Passed | 4s 770ms | Completed | 2019-11-25T05:37:06 MST 
 Teko_StridedEpetraOperator_test_MPI_4 | Passed | 5s 30ms | Completed | 2019-11-24T06:19:52 MST 
 Teko_StridedEpetraOperator_test_MPI_4 | Passed | 4s 910ms | Completed | 2019-11-23T08:49:22 MST 
 Teko_StridedEpetraOperator_test_MPI_4 | Passed | 5s 40ms | Completed | 2019-11-22T06:04:22 MST 
 Teko_StridedEpetraOperator_test_MPI_4 | Passed | 4s 950ms | Completed | 2019-11-21T06:05:21 MST 
 Teko_StridedEpetraOperator_test_MPI_4 | Passed | 4s 600ms | Completed | 2019-11-20T08:26:50 MST 
 Teko_StridedEpetraOperator_test_MPI_4 | Passed | 17s 850ms | Completed | 2019-11-19T07:48:22 MST 
 Teko_StridedEpetraOperator_test_MPI_4 | Passed | 5s | Completed | 2019-11-18T05:49:06 MST 
 Teko_StridedEpetraOperator_test_MPI_4 | Passed | 17s 500ms | Completed | 2019-11-17T05:50:44 MST 
 Teko_StridedEpetraOperator_test_MPI_4 | Passed | 5s 810ms | Completed | 2019-11-16T16:48:54 MST 
 Teko_StridedEpetraOperator_test_MPI_4 | Passed | 13s 700ms | Completed | 2019-11-15T09:17:58 MST 
 Teko_StridedEpetraOperator_test_MPI_4 | Passed | 4s 730ms | Completed | 2019-11-14T07:44:48 MST 

I wonder if this is due to the CPU and/or GPUs getting hot and throttling back speed?  Steven Oliver suggested this is happening on these types of machines and it is mentioned in:

* https://www.quora.com/Does-a-GPU-run-faster-when-it-is-hot

Can such factors of 5x or more differences in runtime be caused by such issues on these machines?  Is this just par-for-the-course when testing on these types of systems?

**Comment by bartlettroscoe** [comment]
Unless there is an objection, I will just disable this randomly timing out test in all of the ATDM Trilinos builds on 'waterman'.  This test will still run on the builds on 'ride' and will also run on 'vortex' once we get those builds up and running.

**Comment by eric-c-cyr** [comment]
No objection

Sent from my iPad

On Jan 6, 2020, at 9:24 AM, Roscoe A. Bartlett <notifications@github.com> wrote:

﻿

Unless there is an objection, I will just disable this randomly timing out test in all of the ATDM Trilinos builds on 'waterman'. This test will still run on the builds on 'ride' and will also run on 'vortex' once we get those builds up and running.

**Comment by bartlettroscoe** [comment]
> > Unless there is an objection, I will just disable this randomly timing out test in all of the ATDM Trilinos builds on 'waterman'. 
>
> No objection

@eric-c-cyr, I created PR #6600 for this disable.  Can you approve that PR?

In any case, I manaully merged that branch to the 'atdm-nightly' branch for tomorrow in commit 
2e26557 so this test will be disabled in ATDM Trilinos builds going forward in case PR #6600 can't be merged before tonight for some reason.

**Comment by bartlettroscoe** [comment]
With the merge of #6600, we can add the "Disabled Tests" label and remove this issue from our main list of issues.

@trilinos/teko, if there is no interest in trying to get this test running better on 'waterman' (and I don't know why there would be since it runs fine everywhere else including 'ride' and on 'sems-rhel7' builds with CUDA and GPUs), then can we just close this as "WONTFIX"?
