### ISSUE TITLE
KokkosKernels_sparse_serial_MPI_1 randomly timing out in pure debug builds on 'ride', 'waterman', and 'ats2' starting 2019-10-18

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#6464]
CC: @trilinos/kokkos-kernels, @kddevin (Trilinos Data Services Product Lead), @bartlettroscoe

<Checklist>
<???: Add label "client: ATDM">
<???: Add label "ATDM Sev: Blocker" (by default but could be other "ATDM Sev: XXX")>
<???: Add label "type: bug"?>
<???: Add label for affected packages (e.g. "pkg: MueLu", "pkg: Tpetra", "pkg: Kokkos", etc.)>
<???: Add label "PA: ???Project Area???" (e.g. "PA: Linear Solvers", "PA: Data Services")>
<???: Add milestone "Initial cleanup of new ATDM ..." or "Keep promoted ATDM ...">
<???: Once GitHub Issue is created, add entries for tests to TrilinosATDMStatus/*.csv files>

## Next Action Status

Disabled `KokkosKernels_sparse_serial_MPI_1` is pure debug builds on 'ride', 'waterman', and 'ats2'.

## Description

As shown in [this query](https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&begin=2019-08-01&end=2019-12-17&filtercount=5&showfilters=1&filtercombine=and&field1=groupname&compare1=62&value1=Experimental&field2=buildname&compare2=65&value2=Trilinos-atdm&field3=testname&compare3=65&value3=KokkosKernels_&field4=status&compare4=61&value4=failed&field5=details&compare5=61&value5=Completed%20(Timeout)) the test

* `KokkosKernels_sparse_serial_MPI_1`

in the builds:

* `Trilinos-atdm-white-ride-gnu-7.2.0-openmp-debug`
* `Trilinos-atdm-waterman-cuda-9.2-debug`

started randomly timing out testing day 2019-10-18.  Out of all of the ATDM Trilinos builds, that is the only KokkosKernels test that has timed out since 2019-10-01 and it only timed out in these two builds a total of 8 times over that time period.

## Current Status on CDash

* [Timing out KokkosKernels_sparse_serial_MPI_1 tests in all ATDM Trilinos builds last 30 days](https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&begin=30%20days%20ago&end=now&filtercount=5&showfilters=1&filtercombine=and&field1=groupname&compare1=62&value1=Experimental&field2=buildname&compare2=65&value2=Trilinos-atdm&field3=testname&compare3=65&value3=KokkosKernels_sparse_serial_MPI_1&field4=status&compare4=61&value4=failed&field5=details&compare5=61&value5=Completed%20(Timeout))

## Steps to Reproduce

One should be able to reproduce this failure on the machine 'ride' or 'waterman' as described in:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md

More specifically, the commands given for the system 'white' (SON) or 'ride' (SRN) are provided at:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#ridewhite

The exact commands to reproduce this issue should be:

```
$ cd <some_build_dir>/

$ source $TRILINOS_DIR/cmake/std/atdm/load-env.sh <build-name>

$ cmake \
 -GNinja \
 -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
 -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_KokkosKernels=ON \
 $TRILINOS_DIR

$ make NP=16

$ <command-to-run-on-compute-node> ctest -j4<command-to-run-on-compute-node> ctest -j4
```

**Comment by bartlettroscoe** [comment]
As shown in [this query](https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&begin=2019-08-01&end=2019-12-17&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-white-ride-gnu-7.2.0-openmp-debug&field2=testname&compare2=61&value2=KokkosKernels_sparse_serial_MPI_1&field3=site&compare3=61&value3=ride) for this test in the build `Trilinos-atdm-white-ride-gnu-7.2.0-openmp-debug`, it is pretty expensive and the median time it finished in the date range [2019-08-01, 2019-12-17] was around 8m30s.  Therefore, this is a pretty expensive test in a pure debug build.

Therefore, I think it is reasonable to disable this test in the pure debug builds on 'ride' and and 'waterman' to make these timeouts go away.  The `opt`/`release` and `release-debug` builds will still run so this functionality is still fully protected.

**Comment by brian-kelley** [comment]
@bartlettroscoe I noticed a timeout here too in my own testing on white. In KokkosKernels PR #544 I cut the size of the rank-1 GaussSeidel tests from 10k rows to 5k. GS and block GS are still the most expensive tests, so I made a note to cut this down more for the Kokkos/KokkosKernels 3.0 release. That will most likely be a few days after the shutdown ends.

But until then, I agree about disabling the debug+cuda version.

**Comment by brian-kelley** [comment]
@bartlettroscoe I ended up shrinking the matrices down to 2k rows, and now the sparse unit tests in serial+debug+double/complex complete in 6 minutes.

**Comment by bartlettroscoe** [comment]
> I ended up shrinking the matrices down to 2k rows, and now the sparse unit tests in serial+debug+double/complex complete in 6 minutes.

@brian-kelley, in the kokkos-kernels git repo 'develop' branch or in the Trilinos repo 'develop' branch?  Which PR?

**Comment by mhoemmen** [comment]
For OpenMP, we shouldn't make the tests too small, just to make sure that we get enough concurrency.  I don't think this matters so much for Serial, though.

**Comment by bartlettroscoe** [comment]
Can we just have KokkosKernels disable these real expensive tests for full debug builds (i.e. `CMAKE_BUILD_TYPE=DEBUG`) by default?  We have `release-debug` builds (i.e. `CMAKE_BUILD_TYPE=RELEASE` and `Trilinos_ENABLE_DEBUG=ON`) that fully test with runtime checking turned on so we have full coverage testing.  Is there any point in running these tests by default in full debug builds?  At least we could provide an option to enable these (like `KokkosKernels_ENABLE_EXPENSIVE_TESTS_IN_DEBUG_BUILDS`) which defaults to off.

**Comment by brian-kelley** [comment]
@bartlettroscoe In KokkosKernels develop, PR #548. I don't see any reason to test all the cases in full debug. Would I just use "#ifdef NDEBUG"? Also, we could always break the sparse unit tests into different executables so that testing has more parallelism.

@mhoemmen That's a good idea.

**Comment by mhoemmen** [comment]
@brian-kelley wrote:
> Would I just use "#ifdef NDEBUG"?

Most Trilinos packages have a CMake option and corresponding macro.  The option's default comes from `CMAKE_BUILD_TYPE`, I think.  If kokkos-kernels doesn't already have this option, then it should.

The point of this option is so that users can enable debugging features in a release build, or disable them in a debug build.  The latter can often reduce build size and/or time.

**Comment by bartlettroscoe** [comment]
FYI: As shown in [this query](https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&begin=2020-01-13&end=2020-02-11&filtercount=4&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-ats2-&field2=buildname&compare2=66&value2=dbg&field3=testname&compare3=61&value3=KokkosKernels_sparse_serial_MPI_1&field4=site&compare4=61&value4=vortex), the test:

* `KokkosKernels_sparse_serial_MPI_1`

is also timing out in the builds:

* `Trilinos-atdm-ats2-cuda-10.1.243-gnu-7.3.1-spmpi-2019.06.24_static_dbg`
* `Trilinos-atdm-ats2-gnu-7.3.1-spmpi-2019.06.24_serial_static_dbg`

That is not surprising becuase this is a Power/GPU system just like 'ride' and 'waterman' so I think we should expect similar behavior.

I will therefore add disables for this test in those builds as well.

**Comment by bartlettroscoe** [comment]
This test is now disabled in the pure 'debug' builds on the 'ats2' builds on 'vortex' as well.  Therefore, I will not add the label `Disabled Tests` to get this off of our list of active issues.

However, @trilinos/kokkos-kernels developers should really consider adding native logic to default disable these tests for pure debug builds so that regular users don't get hit with these long running tests when the do a `CMAKE_BUILD_TYPE=Debug` build.
