### ISSUE TITLE
MueLu:  enabling CreateEpetraPreconditioner

### ISSUE THREAD

**Issue by aprokop** [trilinos/Trilinos#6490]
@trilinos/muelu 

I'm confused about how to enable installation of `MueLu_CreateEpetraPreconditioner.hpp` after the recent dramatic changes in Tpetra/Xpetra/MueLu. I've been playing around with different Tpetra instantiations for global ordinals (trying both long and long long) but I cannot seem to make MueLu and Xpetra to detect Epetra, and thus they don't enable that path. Does anybody have a configuration script that works with the tip of `develop` that enables Epetra?

**Comment by csiefer2** [comment]
Ar present Xpetra/Muelu only enable Epetra support if (a) Tpetra is disabled or (b) Tpetra is enablef with GO=int.

**Comment by lucbv** [comment]
@aprokop has this resolved your problem, can we close this issue?

**Comment by aprokop** [comment]
No. The pending spack issue has no resolution due to this at this point. I'm not sure how to move forward there as xsdk needs to build multiple packages, including dealii, which needs MueLu (needs in xsdk context).

**Comment by mhoemmen** [comment]
I'm tempted to rewrite Xpetra so that it doesn't need to have the same GlobalOrdinal type as its underlying linear algebra type.  Is this impossible or just difficult?

**Comment by csiefer2** [comment]
I did briefly try to rewrite Xpetra to work against Epetra64, but soooooo many of the tests are GO=int specific, it gets really frustrating.  The xpetra-epetra64 branch has a bunch of that code.

Once we purge the LO & GO template parameters, I suspect that supporting Epetra64 in Xpetra will be easier.

**Comment by mhoemmen** [comment]
begone autobot

**Comment by GrahamBenHarper** [comment]
Similar to the other issue, is this worth bumping, or do we say it's too much effort with Epetra stack being phased out?
