### ISSUE TITLE
Tpetra:  Read and write hdf5 files

### ISSUE THREAD

**Issue by mosayed86** [trilinos/Trilinos#6493]
## Question
@trilinos/\<Tpetra\>

Is there an option to read and write teptra matrices and multivectors using the binary HDF5 library. If not, what is the best way to read and write very large files (hundreds of GBs) in Tpetra.

**Comment by mhoemmen** [comment]
@trilinos/tpetra `Tpetra::MultiVector` doesn't have built-in HDF5 support.  However, it's probably not hard to write this; it's just column-major storage on each MPI process.

**Comment by mosayed86** [comment]
How about Tpetra::CrsMatrix, in case of reading and writing CrsMatrices in Tpetra?

**Comment by mhoemmen** [comment]
MueLu has binary I/O for some Tpetra data structures, but it's not HDF5.

**Comment by mhoemmen** [comment]
lol begone autobot

**Comment by rohany** [comment]
> MueLu has binary I/O for some Tpetra data structures, but it's not HDF5.

@mhoemmen can you point me to code / examples for this, or anything related? I'd like to read a matrix market file once and dump it into a binary format for faster loading into tpetra.

**Comment by cgcgcg** [comment]
@rohany For reading a matrix, either as binary or in MatrixMarket format, have a look here:
https://github.com/trilinos/Trilinos/blob/d1004dda768fbe7052ee748007f46c7b279e0b43/packages/xpetra/sup/Utils/Xpetra_IO.hpp#L514-L527
There also is a converted script from MatrixMarket to binary:
https://github.com/trilinos/Trilinos/blob/d1004dda768fbe7052ee748007f46c7b279e0b43/packages/muelu/utils/matrix/ascii2binary.cpp

**Comment by rohany** [comment]
Thanks for the quick response! A few questions:

* I'm hoping to use a released version of Trilinos (i.e. 13.2 or something). Is there a path forward for me here?
* My application right now is mostly using TPetra (I'm very new to the trilinos ecosystem). How can I make those data structures work here? 
* Can the TPetra loader understand files generated by that script? Or only this XPetra loader?
* IIUC, I need to enable the muelu package in order to have my cmake build that package?

**Comment by cgcgcg** [comment]
- We are planning for a minor release early next year. That release would include those changes.
- Xpetra is a wrapper that can handle both old (Epetra) and new (Tpetra) linear algebra backends using a common interface. The code above will give you an Xpetra CrsMatrix, but you can then get the Tpetra operator out of it.
- No, this was only implemented for Xpetra. So you will have to enable the Xpetra package in your build, even though you want to only use Tpetra.
- Actually no. The script can be build independently from MueLu (and Trilinos). (I think we didn't even add it to our CMake.)

**Comment by rohany** [comment]
> Xpetra is a wrapper that can handle both old (Epetra) and new (Tpetra) linear algebra backends using a common interface. The code above will give you an Xpetra CrsMatrix, but you can then get the Tpetra operator out of it.

Can you point me to an example? I'm having trouble finding the right converters in the documentation. Alternatively, an example using XPetra that performs a matvec or something -- the existing examples in the xpetra package directory are a little complicated.

**Comment by mhoemmen** [comment]
@rohany wrote:
> can you point me to code / examples for this, ....

I haven't been a Trilinos developer for nearly two years; I'm just poking the issue out of kindness to current Trilinos developers, so they don't lose issues to the autocloser.

**Comment by rohany** [comment]
@cgcgcg, one last question: Is this binary file format documented anywhere? I'm looking at the script and it doesn't seem to handle a variety of matrix market features, such a symmetric or pattern matrices. Adding support for pattern matrices would be straight forward, but I'm not sure how adding support for symmetric matrices would work.

**Comment by cgcgcg** [comment]
There is no support for anything but a "general" CSR format, since that's the only format that Tpetra supports (apart from some block format). As far as I know, there is no documentation for the binary format. The way it works is somewhat obvious from the converter in MueLu. An alternative to using Tpetra for the conversion from "symmetric" to "general" matrix market is to use SciPy.

**Comment by jhux2** [comment]
> one last question: Is this binary file format documented anywhere? I'm looking at the script and it doesn't seem to handle a variety of matrix market features, such a symmetric or pattern matrices. Adding support for pattern matrices would be straight forward, but I'm not sure how adding support for symmetric matrices would work.

@rohany Any improvement that you might make to the script (documentation and/or greater capability) would be much appreciated.  Thanks.

**Comment by rohany** [comment]
I'm trying to use the `XPetra::Read` function linked above, and am a little stuck. The function requires a `Map` which i think describes how the rows are to be distributed across the machine. However, the construction of a `Map` requires the number of global and local entries. This information is unknown until the matrix file is read. I could do an initial read of the header of the binary file generated by the script linked above, but that seems strange, since I would be passing the same file into the `XPetra::Read` function itself. What is the intended sequence of steps here?

I'm sorry to push a lot on this, but reading files with matrix market io is just too slow for my application to be productive.

**Comment by cgcgcg** [comment]
I believe that Tpetra creates a uniform contiguous one-to-one map by default if you don't pass a rowmap. Xpetra doesn't seem to have that extra step, so you'd need to do that yourself. It works the same way as in Tpetra, just replace "Tpetra" with "Xpetra".

**Comment by rohany** [comment]
The corresponding function used in the TPetra mtxmarket reader is https://github.com/trilinos/Trilinos/blob/d63b7e52f2b1ba598797a18b17275108c8222889/packages/tpetra/core/inout/MatrixMarket_Tpetra.hpp#L273, and is called after the dimensions of the matrix are known (i.e. the matrix has already been read). If this is what needs to be done, then I'll read those dimensions in from the file as well.

**Comment by cgcgcg** [comment]
Actually, maybe I just pointed you to the wrong function. Does this work?
https://github.com/trilinos/Trilinos/blob/5a67b70fb3816e1cea26554c650b4dc7ca26747d/packages/xpetra/sup/Utils/Xpetra_IO.hpp#L395-L396

**Comment by rohany** [comment]
That looks like the right interface! I'm running into a compilation issue now (the documentation around XPetra looks not that complete, so I don't know if I'm doing the installation correctly). My code snippet looks like this:
```
  auto xPetraMat = Xpetra::IO<double>::Read(filename, Xpetra::UseTpetra, comm);
  auto xPetraTpetraMat = Teuchos::rcp_dynamic_cast<Xpetra::TpetraCrsMatrix<double, int, long long>>(xpetraMat);
  auto A = xPetraTpetraMat->getTpetra_CrsMatrixNonConst();
  Teuchos::FancyOStream foo(Teuchos::rcp(&std::cout, false));
  A->describe(foo, Teuchos::VERB_EXTREME);
```

I build Trilinos like this:
```
cmake \
-DTPL_ENABLE_MPI=ON \
-DMPI_BASE_DIR=/usr/tce/packages/spectrum-mpi/spectrum-mpi-rolling-release-gcc-8.3.1/ \
-DTrilinos_ENABLE_Tpetra=ON \
-DTrilinos_ENABLE_Xpetra=ON \
-DTrilinos_ENABLE_OpenMP=ON \
-DTrilinos_ENABLE_CUDA=ON \
-DCMAKE_INSTALL_PREFIX=../cmake-install/ \
..
```

And I have a standard trilinos makefile. However, I see errors like this during the link stage of the build:
```
CMakeFiles/benchmark.dir/benchmark.cpp.o:(.data.rel.ro._ZTVN6Tpetra9CrsMatrixIdiiN6Kokkos6Compat23KokkosDeviceWrapperNodeINS1_6OpenMPENS1_9HostSpaceEEEEE[_ZTVN6Tpetra9CrsMatrixIdiiN6Kokkos6Compat23KokkosDeviceWrapperNodeINS1_6OpenMPENS1_9HostSpaceEEEEE]+0x2f0): undefined reference to `virtual thunk to Tpetra::CrsMatrix<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP, Kokkos::HostSpace> >::getDomainMap() const'
CMakeFiles/benchmark.dir/benchmark.cpp.o:(.data.rel.ro._ZTVN6Tpetra9CrsMatrixIdiiN6Kokkos6Compat23KokkosDeviceWrapperNodeINS1_6OpenMPENS1_9HostSpaceEEEEE[_ZTVN6Tpetra9CrsMatrixIdiiN6Kokkos6Compat23KokkosDeviceWrapperNodeINS1_6OpenMPENS1_9HostSpaceEEEEE]+0x2f8): undefined reference to `virtual thunk to Tpetra::CrsMatrix<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP, Kokkos::HostSpace> >::getRangeMap() const'
CMakeFiles/benchmark.dir/benchmark.cpp.o:(.data.rel.ro._ZTVN6Tpetra9CrsMatrixIdiiN6Kokkos6Compat23KokkosDeviceWrapperNodeINS1_6OpenMPENS1_9HostSpaceEEEEE[_ZTVN6Tpetra9CrsMatrixIdiiN6Kokkos6Compat23KokkosDeviceWrapperNodeINS1_6OpenMPENS1_9HostSpaceEEEEE]+0x300): undefined reference to `virtual thunk to Tpetra::CrsMatrix<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP, Kokkos::HostSpace> >::apply(Tpetra::MultiVector<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP, Kokkos::HostSpace> > const&, Tpetra::MultiVector<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP, Kokkos::HostSpace> >&, Teuchos::ETransp, double, double) const'
```

Do you know what is going wrong? I've enabled the Xpetra and TPetra libraries, and my build works when I don't include anything Xpetra related. I'm currently on the `develop` branch, commit `d1004dda768fbe7052ee748007f46c7b279e0b43`.

**Comment by cgcgcg** [comment]
Please change `Xpetra::IO<double>` to `Xpetra::IO<double, int, long long>`. It seems that `IO` defaults to `double, int, int`, but that's not what's enabled in the build.

**Comment by jhux2** [comment]
> It seems that `IO` defaults to `double, int, int`, but that's not what's enabled in the build.

That's possibly a bug in the cmake logic.

**Comment by rohany** [comment]
Everything is compiling now, but not working at runtime. For the below runs, I used the following matrix market file (and converted to binary with the script from above):
```
%%MatrixMarket matrix coordinate real general
%
5 5 3
1 1 2.000000000000000e+00
1 4 3.000000000000000e+00
2 5 4.000000000000000e+00
```

First, I tried directly using the Xpetra::IO::Read function as follows to load a binary file:
```
  auto xpetraMat = Xpetra::IO<double, int, long long>::Read(filename, Xpetra::UseTpetra, comm, true /* binary */);
  auto xPetraTpetraMat = Teuchos::rcp_dynamic_cast<Xpetra::TpetraCrsMatrix<double, int, long long>>(xpetraMat);
  auto A = xPetraTpetraMat->getTpetra_CrsMatrixNonConst();
  Teuchos::FancyOStream foo(Teuchos::rcp(&std::cout, false));
  A->describe(foo, Teuchos::VERB_EXTREME);
```
This snippet appears to hang within the IO::Read function call.

Next, I tried to use xpetra to load a matrix market file to see what would happen, but the `rcp_dynamic_cast` fails and returns a null pointer. Is this not the correct way to perform the cast?
```
  auto xpetraMat = Xpetra::IO<double, int, long long>::Read(filename, Xpetra::UseTpetra, comm);
  auto xPetraTpetraMat = Teuchos::rcp_dynamic_cast<Xpetra::TpetraCrsMatrix<double, int, long long>>(xpetraMat);
  auto A = xPetraTpetraMat->getTpetra_CrsMatrixNonConst();
  Teuchos::FancyOStream foo(Teuchos::rcp(&std::cout, false));
  A->describe(foo, Teuchos::VERB_EXTREME);
```

**Comment by cgcgcg** [comment]
You can set the optional second argument of `dynamic_cast` to `true`. That should give you an error message telling you why the cast failed.

**Comment by rohany** [comment]
I had to change the snippet to 
```
  auto matrixWrap = Teuchos::rcp_dynamic_cast<Xpetra::CrsMatrixWrap<double, int, long long>>(xpetraMat);
  auto xPetraTpetraMat = Teuchos::rcp_dynamic_cast<Xpetra::TpetraCrsMatrix<double, int, long long>>(matrixWrap->getCrsMatrix());
  auto A = xPetraTpetraMat->getTpetra_CrsMatrixNonConst();
```
as the return type from Read was a CrsMatrixWrap. So the final issue is the hang in `io::Read` for binary files!

**Comment by cgcgcg** [comment]
Oh, right. Yep, totally forgot about that. For binary, I'd try a matrix that isn't missing any rows. Maybe there are some issues with that.

**Comment by rohany** [comment]
Yep, the routine succeeds when reading a matrix with no missing entries.

**Comment by jhux2** [comment]
@rohany Is this issue resolved for you?

**Comment by rohany** [comment]
I have not tried it in a while. Is this expected to have been fixed? The last issue I ran into was that the binary loader would fail reading any "sparse" matrices that had zero entries.

**Comment by jhux2** [comment]
> I have not tried it in a while. Is this expected to have been fixed? The last issue I ran into was that the binary loader would fail reading any "sparse" matrices that had zero entries.

@rohany To be more specific, by "zero entries", you mean sparse matrices that have at least one row with no entries?

**Comment by jhux2** [comment]
Afaik, there haven't been any changes in the Xpetra binary reader since last you tried, so I expect it will still won't be able to read matrices with empty rows.

**Comment by cgcgcg** [comment]
Not sure there is actually a problem in the binary reader. But the MueLu converter from MatrixMarket to binary definitely doesn't handle empty rows correctly. Lemme try to fix that.

**Comment by jhux2** [comment]
@rohany Fyi, @cgcgcg fixed the binary converter in MueLu to be able to handle matrices with empty rows in PR #10328.  Thank you, @cgcgcg.  Could you please pull to see if that resolves the issue you reported?

**Comment by rohany** [comment]
Yup, works for me now.

**Comment by jhux2** [comment]
@rohany Thanks for checking.  I'll close this issue, but please reopen if necessary.
