### ISSUE TITLE
PyTrilinos: Get package working with latest Trilinos version

### ISSUE THREAD

**Issue by pyt-viper** [trilinos/Trilinos#6497]
## Enhancement
@trilinos/pytrilinos

When one tries to build the latest version of Trilinos with PyTrilinos enabled, there is a SWIG error during build when `Teuchos.RCP.i` is being processed.  There is also a SWIG error when processing `Tpetra_dox.i`, `%include`d from `Tpetra.i`.

Depends on:
#6498
#6500

**Comment by mayrmt** [comment]
@trilinos/pytrilinos

**Comment by mhoemmen** [comment]
@pyt-viper Normal procedure for closing issues is to let the daily automatic develop-to-master merge automatically close issues.  That requires putting text like `Fix #1234` or `Closes #1234` in your commit and/or PR comment.
