### ISSUE TITLE
PyTrilinos: SWIG does not process Teuchos.RCP.i correctly

### ISSUE THREAD

**Issue by pyt-viper** [trilinos/Trilinos#6498]
## Bug Report
@trilinos/pytrilinos

### Description
With the latest version of Trilinos, SWIG fails to process `Teuchos.RCP.i` correctly.  The C++ macro `TPETRA_DEPRECATED` is not getting set, causing a parsing error downstream.

### Steps to Reproduce
1. SHA1:  0c4cf70368bd5148dacdd37cafbe71231f870b98
1. Anaconda configuration: cmake, openblas, python=3, swig=3.0.11, numpy, openmpi-mpicc, openmpi-mpicxx, mpi4py, doxygen
1. Configure script:  
[do-configure.txt](https://github.com/trilinos/Trilinos/files/3996792/do-configure.txt)
1. Run the configure script and `make`.  When `Teuchos.RCP.i` is processed, SWIG will report a syntax error because macro `TPETRA_DEPRECATED` isn't defined.

Blocks: #6497

**Comment by mayrmt** [comment]
@trilinos/pytrilinos
