### ISSUE TITLE
unexpected (and silent) sumIntoGlobalValues failure

### ISSUE THREAD

**Issue by nschloe** [trilinos/Trilinos#65]
@trilinos/tpetra

I have a larger application code in which I build up a matrix by looping over the edges of a mesh and sum values into the matrix for each of the two end points. I found that some indices aren't correctly inserted when running on more than one processes.

I could boil it down to
```c++
#include <Teuchos_DefaultComm.hpp>
#include <Tpetra_CrsMatrix.hpp>

int main ( int argc, char *argv[] )
{
  Teuchos::GlobalMPISession session(&argc, &argv, NULL);

  // Initialize MPI
  auto comm = Teuchos::DefaultComm<int>::getComm();

  // build map in which process K owns row K
  std::vector<int> ids = {comm->getRank()};
  auto map = Teuchos::rcp(new Tpetra::Map<int>(-1, ids, 0, comm));

  const int globalSize = map->getGlobalNumElements();

  // insert indices from all processes
  auto graph = Teuchos::rcp(new Tpetra::CrsGraph<int, int>(map, map, 0));
  for (int i = 0; i < globalSize; i++) {
    for (int j = 0; j < globalSize; j++) {
      graph->insertGlobalIndices(i, Teuchos::tuple(j));
    }
  }
  graph->fillComplete();

  // fill matrix
  auto A = Teuchos::rcp(new Tpetra::CrsMatrix<double,int,int>(graph));
  A->setAllToScalar(0.0);
  for (size_t k = 0; k < globalSize; k++) {
    const int num = A->sumIntoGlobalValues(
        k,
        Teuchos::tuple(0, 1),
        Teuchos::tuple(0.33, 1.55)
        );
    std::cout << "added from @" << comm->getRank() << " in row " << k << ": "
      << num
      << std::endl;
  }
  A->fillComplete();

  return EXIT_SUCCESS;
}
```
When run on two procs, I'm getting
```
$ mpiexec -n 2 ./test
added from @0 in row 0: 1
added from @0 in row 1: 2
added from @1 in row 0: 2
added from @1 in row 1: 1
```
I would have expected that two entries are inserted for each `sumIntoGlobalValues`. The `insertGlobalIndices` I thought makes sure that the corresponding "slots" are present in the respective processes. Apparently, that's not the case.

When checking out the actual values after `A->fillComplete()` with
```c++
  Teuchos::Array<int> cols(100);
  Teuchos::Array<double> vals(100);
  size_t numss;
  for (size_t k = 0; k < globalSize; k++) {
    A->getGlobalRowCopy(k, cols, vals, numss);
    std::cout << "@" << comm->getRank()
      << ", row " << k
      << ", num columns "  << numss
      << ", columns ";
    for (size_t kk = 0; kk < numss; kk++) {
      std::cout  << cols[kk] << " ";
    }
    std::cout << ", values ";
    for (size_t kk = 0; kk < numss; kk++) {
      std::cout  << vals[kk] << " ";
    }
    std::cout << std::endl;
  }
```
I'm getting
```
@0, row 0, num columns 2, columns -1 0 , values 0 0.66 
@0, row 1, num columns 0, columns , values 
@1, row 0, num columns 0, columns , values 
@1, row 1, num columns 2, columns -1 1 , values 0 3.1
```

On a side node, is there a way to make Tpetra throw when this happens? Having to check the return value to assert correct operation seems a little Epetry.

**Comment by mhoemmen** [comment]
Hi Nico -- thanks for filing a bug! I'm traveling now and will get to this as soon as I can.

The point of returning an error code is to facilitate thread-parallel fill via the "count, allocate, fill, compute" paradigm.  Running out of space is not meant to be "exceptional" anymore, and exceptions are hard to handle efficiently with fine-grained parallelism.  The error code will tell you how many entries were successfully inserted, summed, etc.

mfh

On Dec 26, 2015, at 9:31 AM, Nico Schl?mer <notifications@github.com<mailto:notifications@github.com>> wrote:


I have a larger application code in which I build up a matrix by looping over the edges of a mesh and sum values into the matrix for each of the two end points. I found that some indices aren't correctly inserted when running on more than one processes.

I could boil it down to

#include <Teuchos_DefaultComm.hpp>
#include <Tpetra_CrsMatrix.hpp>

int main ( int argc, char *argv[] )
{
  Teuchos::GlobalMPISession session(&argc, &argv, NULL);

  // Initialize MPI
  auto comm = Teuchos::DefaultComm<int>::getComm();

  // build map in which process K owns row K
  std::vector<int> ids = {comm->getRank()};
  auto map = Teuchos::rcp(new Tpetra::Map<int>(-1, ids, 0, comm));

  const int globalSize = map->getGlobalNumElements();;

  // insert indices from all processes
  auto graph = Teuchos::rcp(new Tpetra::CrsGraph<int, int>(map, map, 0));
  for (int i = 0; i < globalSize; i++) {
    for (int j = 0; j < globalSize; j++) {
      graph->insertGlobalIndices(i, Teuchos::tuple(j));
    }
  }
  graph->fillComplete();

  // fill matrix
  auto A = Teuchos::rcp(new Tpetra::CrsMatrix<double,int,int>(graph));
  A->setAllToScalar(0.0);
  for (size_t k = 0; k < globalSize; k++) {
    const int num = A->sumIntoGlobalValues(
        k,
        Teuchos::tuple(0, 1),
        Teuchos::tuple(1.1, 2.2)
        );
    std::cout << "inserted from @" << comm->getRank() << ": "
      << num
      << std::endl;
  }
  A->fillComplete();

  return EXIT_SUCCESS;
}

When run on two procs, I'm getting

$ mpiexec -n 2 ./test
inserted from @0: 1
inserted from @0: 2
inserted from @1: 2
inserted from @1: 1


I would have expected that two entries are inserted for each sumIntoGlobalValues. The insertGlobalIndices I thought makes sure that the corresponding "slots" are present in the respective processes. Apparently, that's not the case.

On a side node, is there a way to make Tpetra throw when this happens? Having to check the return value to assert correct operation seems a little Epetry.

-

**Comment by nschloe** [comment]
Thanks Mark for the explanation. I had always perceived the failure of summing/inserting entries in a matrix as an error. However, I understand if difficulties in thread-parallelism prevent a sane implemention here.

Anyhow, I'm more interested as to _why_ it doesn't work. I had been under the impression that in Tpetra, it's possible to sum into off-process nodes (much like `Epetra_FECrsMatrix`). Probably a misunderstanding of some kind.

**Comment by nschloe** [comment]
Okay, I think I've found where I've been going wrong. The effect can actually be reproduced with only the graph,
```c++
#include <Teuchos_DefaultComm.hpp>
#include <Tpetra_CrsMatrix.hpp>

int main ( int argc, char *argv[] )
{
  Teuchos::GlobalMPISession session(&argc, &argv, NULL);

  // Initialize MPI
  auto comm = Teuchos::DefaultComm<int>::getComm();

  // build map in which process K owns row K
  std::vector<int> ids = {comm->getRank()};
  auto map = Teuchos::rcp(new Tpetra::Map<int>(
        Teuchos::OrdinalTraits<Tpetra::global_size_t>::invalid(),
        ids,
        0,
        comm
        ));

  const int globalSize = map->getGlobalNumElements();;

  // insert indices from all processes
  auto graph = Teuchos::rcp(new Tpetra::CrsGraph<int, int>(map, map, 0));
  for (int i = 0; i < globalSize; i++) {
    for (int j = 0; j < globalSize; j++) {
      graph->insertGlobalIndices(i, Teuchos::tuple(j));
    }
  }
  graph->fillComplete();

  {
    Teuchos::Array<int> cols(100);
    size_t numss;
    int k = comm->getRank();
    graph->getGlobalRowCopy(k, cols, numss);
    std::cout << "@" << comm->getRank()
      << ", row " << k
      << ", num columns "  << numss
      << ", columns ";
    for (size_t kk = 0; kk < numss; kk++) {
      std::cout  << cols[kk] << " ";
    }
    std::cout << std::endl;
  }

  return EXIT_SUCCESS;
}
```
This gives
```
@0, row 0, num columns 2, columns -1 0 
@1, row 1, num columns 2, columns -1 1
```
which was contrary to what I had expected. The reason for the `-1`s in the columns is the fact that the column map, too, is `map`. Changing the `graph` instatiation to
```c++
  auto graph = Teuchos::rcp(new Tpetra::CrsGraph<int, int>(map, 0));
```
such that the column map is determined automatically, one gets
```
@0, row 0, num columns 2, columns 0 1 
@1, row 1, num columns 2, columns 1 0
```
Alright, lesson learned I guess. :)

**Comment by mhoemmen** [comment]
Hi Nico!  Happy new year btw!

If the row Map and the column Map are the same, that effectively makes the graph / matrix block diagonal.  The behavior you observed relates to the "filtering" behavior that Tpetra inherited from Epetra.

For example, CrsGraph and CrsMatrix _currently_ (emphasis on the currently -- I plan to get rid of this behavior, because it hinders thread parallelism) allow inserts into nonowned rows.  These inserts get communicated to their owning processes at fillComplete.  However, if the columns in question don't exist in the column Map on the receiving process at fillComplete, they currently get silently ignored.  Detecting this error condition requires either an extra all-reduce at fillComplete (NOT acceptable, given the performance constraints of paying customers), or setting a local error flag and making the user take responsibility for resolving the global error condition.  I think the latter is a better option.  BlockCrsMatrix does this already, for example.

**Comment by nschloe** [comment]
> _currently_ (emphasis on the currently -- I plan to get rid of this behavior, because it hinders thread parallelism)

Good to know. I was going to think about reorganizing some code here and there anyways, so I'll probably look at that soon.

> Detecting this error condition requires either an extra all-reduce at fillComplete (NOT acceptable, given the performance constraints of paying customers)

To be honest, I'm not using exceptions as part of my regular C++ code flow. I've rather looked at exceptions as some kind of error, and taking a penalty when things are about to crash never seemed to harsh for me. One of the main benefits I've always gotten from exceptions is they, by default, aren't ignored (like return values are). Anyhow, I guess if exceptions are part of you normal code flow (e.g., if it's legal and expected for the `sumIntoGlobal` to go wrong), it doesn't really matter much if you throw or return a flag. Now that I know what's going on, I'm happy with both anyways.

**Comment by mhoemmen** [comment]
Exceptions make control flow non-vectorizable.  Thus, I need to avoid them in functions that I expect user code to drive using fine-grained parallelism.  Furthermore, running out of memory isn't necessarily an "exceptional condition."  "Count, allocate, fill, compute" lets the initial space estimate ("count") be too low, in which case the correct behavior is to re-estimate and try again.  The plan is for all methods that consume space (e.g., insert*) to return a count that helps users re-estimate space, in case they run out.

I'm still OK with exceptions in functions that aren't meant to be called in a fine-grained-parallel way.  They do cause issues with MPI parallelism, but so do error codes.  (Inconsistent state is bad.)  My eventual goal is to have smarter error propagation mechanisms that "just work," but that will take a long while to implement.
