### ISSUE TITLE
Teuchos:  create a new validator for booleans

### ISSUE THREAD

**Issue by kddevin** [trilinos/Trilinos#650]
@MicheldeMessieres @krcb @trilinos/teuchos 

Teuchos lacks a validator for boolean values.  It would be nice to have a validator that allows a user to set boolean values either as booleans or as strings, just as AnyNumberParameterEntryValidator does for numbers.  E.g.,
  pl.set("boolOne", true);
  pl.set("boolTwo", "true");

Then getValue would return a bool.
[paramBOOL.cpp.txt](https://github.com/trilinos/Trilinos/files/490587/paramBOOL.cpp.txt)

The attached program demonstrates the functionality and can be the basis of a test program.

**Comment by MicheldeMessieres** [comment]
@kddevin 
I’ve added code for a bool validator (BoolParameterEntryValidator) which accepts true/false/“true”/“false”
Right now “true” and “false” are hard-coded options and perhaps we want to make that a flexible choice.

This code is in the zoltan2ParameterLists branch and combined with the changes for #612.
I can break that out into different branches if we prefer but it may be easier to keep them together at least for now.

**paramBool.cpp example code:**
The example code provided was incorporated into a more extensive Teuchos unit test called boolValidator. The last part of that test closely follows the original example code provided.
