### ISSUE TITLE
PyTrilinos: Tpetra_dox.i has syntax errors

### ISSUE THREAD

**Issue by pyt-viper** [trilinos/Trilinos#6500]
## Bug Report
@trilinos/pytrilinos

### Description
When SWIG processes `Tpetra.i`, it encounters a syntax error in `%include`d file `Tpetra_dox.i` (actually, SWIG does not recognize the variadic template arguments in the `%feature("docstring")` directives -- there is a SWIG bug that needs to be worked around).  Since `Tpetra_dox.i` is a generated file, the bug/issue is in the `doxy2swig.py` script.

### Steps to Reproduce
1. SHA1:  0c4cf70368bd5148dacdd37cafbe71231f870b98
1. Configure script:  
[do-configure.txt](https://github.com/trilinos/Trilinos/files/3998833/do-configure.txt)

1. Anaconda environment: cmake, openblas, python=3, swig=3.0.11, numpy, openmpi-mpicc, openmpi-mpicxx, mpi4py, doxygen
1. Run the configure script and `make`

Blocks: #6497

**Comment by mhoemmen** [comment]
@trilinos/pytrilinos (If you're not a developer, GitHub doesn't let you tag teams -- annoying but such is life.)  It looks like you have a fix in mind -- are you planning to submit a PR?
