### ISSUE TITLE
PyTrilinos/Epetra:  Build fails

### ISSUE THREAD

**Issue by MarDiehl** [trilinos/Trilinos#6507]
## Bug Report
@trilinos/PyTrilinos
@trilinos/Epetra

### Description
Build fails

### Steps to Reproduce
Install on Arch Linux (python 3.8, swig 4.0.1)
1. run `cmake .. -DTrilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=ON -DTrilinos_ENABLE_ALL_PACKAGES:BOOL=ON -DTrilinos_ENABLE_PyTrilinos:BOOL=ON -DTrilinos_ENABLE_Gtest:BOOL=ON -DTrilinos_ENABLE_TESTS=OFF -DTPL_ENABLE_gtest:BOOL=ON -DTPL_ENABLE_MPI:BOOL=ON -DTPL_ENABLE_HDF5:BOOL=ON -DCMAKE_INSTALL_PREFIX:PATH=/usr -DBUILD_SHARED_LIBS:BOOL=ON `
1. get 
``` make[2]: Entering directory '/tmp/t/src/Trilinos-trilinos-release-12-18-1/build'  
[ 97%] Swig source /tmp/t/src/Trilinos-trilinos-release-12-18-1/packages/PyTrilinos/src/LOCA.Epetra.Interface.i  
...  
Deprecated command line option: -noproxydel. This option is now always on.  
/tmp/t/src/Trilinos-trilinos-release-12-18-1/packages/PyTrilinos/src/Teuchos.i:148: Error: Syntax error in input(1).  
make[2]: *** [packages/PyTrilinos/src/CMakeFiles/PyTrilinos_LOCA_Epetra_Interface.dir  /build.make:62: packages/PyTrilinos/src/LOCA.Epetra.InterfacePYTHON_wrap.cpp] Error 1  
make[2]: Leaving directory '/tmp/t/src/Trilinos-trilinos-release-12-18-1/build' 
```

The underlying problem seems to be that  `LOCA.Epetra.InterfacePYTHON_wrap.cpp` does not exist.

**Comment by mhoemmen** [comment]
@pyt-viper FYI

**Comment by pyt-viper** [comment]
@MarDiehl try swig 3.0.11

**Comment by MarDiehl** [comment]
thanks for the quick reply
