### ISSUE TITLE
TpetraTSQR link errors in all ATDM Trilinos CUDA+RDC builds starting 2019-12-24

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#6517]
CC: @trilinos/tpetra, @kddevin  (Trilinos Data Services Product Lead), @bartlettroscoe, @mhoemmen 

<Checklist>
<???: Add label "client: ATDM">
<???: Add label "ATDM Sev: Blocker" (by default but could be other "ATDM Sev: XXX")>
<???: Add label "type: bug"?>
<???: Add label for affected packages (e.g. "pkg: MueLu", "pkg: Tpetra", "pkg: Kokkos", etc.)>
<???: Add label "PA: ???Project Area???" (e.g. "PA: Linear Solvers", "PA: Data Services")>
<???: Add milestone "Initial cleanup of new ATDM ..." or "Keep promoted ATDM ...">
<???: Once GitHub Issue is created, add entries for tests to TrilinosATDMStatus/*.csv files>

## Next Action Status

<status-and-or-first-action>

## Description

As shown in [this query](https://testing-dev.sandia.gov/cdash/index.php?project=Trilinos&begin=2019-12-01&end=2020-01-03&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-&field2=buildname&compare2=63&value2=-rdc-) the ATDM Trilinos CUDA+RDC builds:

* `Trilinos-atdm-waterman-cuda-9.2-rdc-release-debug`
* `Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-rdc-release-debug`
* `Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-rdc-release-debug-pt`

starting having new build errors on tseting day 2019-12-24.

As shown in [this query](https://testing-dev.sandia.gov/cdash/index.php?project=Trilinos&begin=2019-12-01&end=2020-01-03&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-&field2=buildname&compare2=63&value2=-rdc-&field3=subprojects&compare3=93&value3=Tpetra) these build errors are in the Tpetra package and show the build errors:

**packages/tpetra/tsqr/test/TpetraTSQR_DistTsqr.exe:**
```
packages/tpetra/tsqr/src/libkokkostsqr.a(Tsqr_Test_MpiAndKokkosScope.cpp.o): In function `TSQR::Test::MpiScope::MpiScope(int*, char***)':
/home/jenkins/waterman/workspace/Trilinos-atdm-waterman-cuda-9.2-rdc-release-debug/SRC_AND_BUILD/Trilinos/packages/teuchos/coreTeuchos_RCPNode.hpp:795: multiple definition of `TSQR::Test::MpiScope::MpiScope(int*, char***)'
packages/tpetra/tsqr/test/CMakeFiles/TpetraTSQR_DistTsqr.dir/Tsqr_TestDistTsqr.cpp.o:/home/jenkins/waterman/workspace/Trilinos-atdm-waterman-cuda-9.2-rdc-release-debug/SRC_AND_BUILD/Trilinos/packages/tpetra/tsqrTsqr_Test_MpiAndKokkosScope.cpp:18: first defined here
packages/tpetra/tsqr/src/libkokkostsqr.a(Tsqr_Test_MpiAndKokkosScope.cpp.o): In function `TSQR::Test::MpiScope::MpiScope(int*, char***)':
/home/jenkins/waterman/workspace/Trilinos-atdm-waterman-cuda-9.2-rdc-release-debug/SRC_AND_BUILD/Trilinos/packages/teuchos/coreTeuchos_RCPNode.hpp:795: multiple definition of `TSQR::Test::MpiScope::MpiScope(int*, char***)'
...
collect2: error: ld returned 1 exit status
```

and

**packages/tpetra/tsqr/test/TpetraTSQR_FullTsqr.exe:**
```
packages/tpetra/tsqr/src/libkokkostsqr.a(Tsqr_Test_MpiAndKokkosScope.cpp.o): In function `TSQR::Test::MpiScope::MpiScope(int*, char***)':
/home/jenkins/waterman/workspace/Trilinos-atdm-waterman-cuda-9.2-rdc-release-debug/SRC_AND_BUILD/Trilinos/packages/teuchos/coreTeuchos_RCPNode.hpp:795: multiple definition of `TSQR::Test::MpiScope::MpiScope(int*, char***)'
packages/tpetra/tsqr/test/CMakeFiles/TpetraTSQR_FullTsqr.dir/Tsqr_TestFullTsqr.cpp.o:/home/jenkins/waterman/workspace/Trilinos-atdm-waterman-cuda-9.2-rdc-release-debug/SRC_AND_BUILD/Trilinos/packages/tpetra/tsqrTsqr_Test_MpiAndKokkosScope.cpp:18: first defined here
packages/tpetra/tsqr/src/libkokkostsqr.a(Tsqr_Test_MpiAndKokkosScope.cpp.o): In function `TSQR::Test::MpiScope::MpiScope(int*, char***)':
/home/jenkins/waterman/workspace/Trilinos-atdm-waterman-cuda-9.2-rdc-release-debug/SRC_AND_BUILD/Trilinos/packages/teuchos/coreTeuchos_RCPNode.hpp:795: multiple definition of `TSQR::Test::MpiScope::MpiScope(int*, char***)'
packages/tpetra/tsqr/test/CMakeFiles/TpetraTSQR_FullTsqr.dir/Tsqr_TestFullTsqr.cpp.o:/home/jenkins/waterman/workspace/Trilinos-atdm-waterman-cuda-9.2-rdc-release-debug/SRC_AND_BUILD/Trilinos/packages/tpetra/tsqrTsqr_Test_MpiAndKokkosScope.cpp:18: first defined here
...
collect2: error: ld returned 1 exit status
```

The new commits that were pulled on testing day 2019-12-24 as shown, for example, [here](https://testing-dev.sandia.gov/cdash/viewNotes.php?buildid=5111089#!#note1).  From looking over that set of commits, it seems likely that these build errors were triggered by the merge of th PRs #6488 from @mhoemmen.

## Current Status on CDash

* [Tpetra build status on CUDA+RDC builds last 2 weeks](https://testing-dev.sandia.gov/cdash/index.php?project=Trilinos&begin=2%20weeks%20ago&end=now&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-&field2=buildname&compare2=63&value2=-rdc-&field3=subprojects&compare3=93&value3=Tpetra)

## Steps to Reproduce

One should be able to reproduce this failure on the machines 'white' (SON), 'ride' (SRN), or 'waterman' (SRN) as described in:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md

More specifically, the commands given for the system 'ride' (on the machines 'white' or 'ride') are provided at:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#ridewhite

The exact commands to reproduce this issue should be:

```
$ cd <some_build_dir>/

$ source $TRILINOS_DIR/cmake/std/atdm/load-env.sh \
    Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-rdc-release-debug

$ cmake\
 -GNinja \
 -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
 -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_Tpetra=ON \
 $TRILINOS_DIR

$ make NP=16
```

**Comment by bartlettroscoe** [comment]
@mhoemmen, link errors seem to be caused by `packages/tpetra/tsqr/src/libkokkostsqr.a` so can this impact production usage of TSQR when CUDA+RDC is being used?

Is ATDM even using Tpetra TSQR?  If not, we should just disable this in the ATDM Trilinos builds and avoid these types of errors in the future.

**Comment by mhoemmen** [comment]
@bartlettroscoe ATDM will be using TSQR.  I definitely tested this with CUDA, just not with RDC enabled.  Give me a couple days to fix this; I'm in the middle of another thing.

**Comment by bartlettroscoe** [comment]
@mhoemmen 

> ATDM will be using TSQR. 

Actually, a better question is if ATDM is actually going to be using CUDA+RDC.  Last I heard, there was no immediate or mid-term plan to do so.  And with next-generation DOE Exascale machines not even using Nvidia GPUs and CUDA, do we really care long term?  I think setting up a CUDA+RDC build to support ATDM may have been a bit too forward looking.

I know that Sierra uses CUDA+RDC but if ATDM is not going to be using it soon, I would like to consider relegating these builds to Experimental builds and letting someone else traige them (or turn them off altogether).

> I definitely tested this with CUDA, just not with RDC enabled.

Right, that is why this issue says "CUDA+RDC" and not just "CUDA" :-)  Would be great if there was a CUDA+RDC PR build but that is a very expensive build and would really slow down the PR testing by a factor of 2 or more (if they keep doing builds from scratch).

> Give me a couple days to fix this; I'm in the middle of another thing.

That is fine.  If you fix this in the next week that will be orders of magnitude faster than most ATDM Trilinos GitHub issues are resolved.  (For example, check out #3862; it was created almost 14 months ago and those tests are still failing even today!)

**Comment by bartlettroscoe** [comment]
@mhoemmen,

I was reported by @bathmatt that EMPIRE has no plans to use Tpetra TSQR with EMPIRE and since SPARC can't currently build with CUDA+RDC, I don't think any ATDM customers are going to be using Tpetra TSQR.

Therefore, since is somewhat obscuring our ability to detect new build errors in the CUDA+RDC builds, can we just disable these two targets and the tests that depend on them from the ATDM Trilinos CUDA+RDC builds?  We would keep them enabled in all of the other builds where they are still working.

**Comment by mhoemmen** [comment]
I'm working on fixing these.

**Comment by mhoemmen** [comment]
I may have a fix for this; I'm testing it now.

**Comment by mhoemmen** [comment]
Hm, I can't test my fix, since I can't get kokkos-kernels to build shared + RDC.  @bartlettroscoe is there some trick to this?

**Comment by ndellingwood** [comment]
@mhoemmen I don't think rdc + shared is properly supported by the vendor, there was long discussion chain in an issue a year or so back, I'll update with the link if I find it.

**Comment by mhoemmen** [comment]
@ndellingwood Ah, should I just do a static build then, but keep the other flags including `-fPIC`?

**Comment by ndellingwood** [comment]
@mhoemmen I'm not certain of the best path, here's a comment with link to nvidia docs about the issue [link](https://github.com/trilinos/Trilinos/issues/4502#issuecomment-472175560)

**Comment by mhoemmen** [comment]
@ndellingwood Thanks!  I tried a static build with `-fPIC` and got through kokkos-kernels, but now TSQR's tests don't link:
```
[100%] Linking CXX executable TpetraTSQR_CuSolver.exe
[100%] Linking CXX executable TpetraTSQR_Combine.exe
CMakeFiles/TpetraTSQR_CuSolver.dir/CuSolver.cpp.o: In function `__sti____cudaRegisterAll()':
tmpxft_00005514_00000000-5_CuSolver.cudafe1.cpp:(.text.startup+0x1d): undefined reference to `__cudaRegisterLinkedBinary_43_tmpxft_00005514_00000000_6_CuSolver_cpp1_ii_main'
collect2: error: ld returned 1 exit status
make[2]: *** [packages/tpetra/tsqr/test/TpetraTSQR_CuSolver.exe] Error 1
make[1]: *** [packages/tpetra/tsqr/test/CMakeFiles/TpetraTSQR_CuSolver.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[100%] Linking CXX executable TpetraTSQR_DistTsqr.exe
CMakeFiles/TpetraTSQR_Combine.dir/Tsqr_TestCombine.cpp.o: In function `__sti____cudaRegisterAll()':
tmpxft_00005533_00000000-5_Tsqr_TestCombine.cudafe1.cpp:(.text.startup+0x1d): undefined reference to `__cudaRegisterLinkedBinary_51_tmpxft_00005533_00000000_6_Tsqr_TestCombine_cpp1_ii_main'
collect2: error: ld returned 1 exit status
make[2]: *** [packages/tpetra/tsqr/test/TpetraTSQR_Combine.exe] Error 1
make[1]: *** [packages/tpetra/tsqr/test/CMakeFiles/TpetraTSQR_Combine.dir/all] Error 2
CMakeFiles/TpetraTSQR_DistTsqr.dir/Tsqr_TestDistTsqr.cpp.o: In function `__sti____cudaRegisterAll()':
tmpxft_00005539_00000000-5_Tsqr_TestDistTsqr.cudafe1.cpp:(.text.startup+0x1d): undefined reference to `__cudaRegisterLinkedBinary_52_tmpxft_00005539_00000000_6_Tsqr_TestDistTsqr_cpp1_ii_main'
collect2: error: ld returned 1 exit status
make[2]: *** [packages/tpetra/tsqr/test/TpetraTSQR_DistTsqr.exe] Error 1
make[1]: *** [packages/tpetra/tsqr/test/CMakeFiles/TpetraTSQR_DistTsqr.dir/all] Error 2
[100%] Linking CXX executable TpetraTSQR_NodeTsqr.exe
[100%] Linking CXX executable TpetraTSQR_FullTsqr.exe
CMakeFiles/TpetraTSQR_NodeTsqr.dir/Tsqr_TestNodeTsqr.cpp.o: In function `__sti____cudaRegisterAll()':
tmpxft_00005526_00000000-5_Tsqr_TestNodeTsqr.cudafe1.cpp:(.text.startup+0x1d): undefined reference to `__cudaRegisterLinkedBinary_52_tmpxft_00005526_00000000_6_Tsqr_TestNodeTsqr_cpp1_ii_1a5f2a5a'
collect2: error: ld returned 1 exit status
make[2]: *** [packages/tpetra/tsqr/test/TpetraTSQR_NodeTsqr.exe] Error 1
make[1]: *** [packages/tpetra/tsqr/test/CMakeFiles/TpetraTSQR_NodeTsqr.dir/all] Error 2
CMakeFiles/TpetraTSQR_FullTsqr.dir/Tsqr_TestFullTsqr.cpp.o: In function `__sti____cudaRegisterAll()':
tmpxft_0000554c_00000000-5_Tsqr_TestFullTsqr.cudafe1.cpp:(.text.startup+0x1d): undefined reference to `__cudaRegisterLinkedBinary_52_tmpxft_0000554c_00000000_6_Tsqr_TestFullTsqr_cpp1_ii_main'
collect2: error: ld returned 1 exit status
make[2]: *** [packages/tpetra/tsqr/test/TpetraTSQR_FullTsqr.exe] Error 1
make[1]: *** [packages/tpetra/tsqr/test/CMakeFiles/TpetraTSQR_FullTsqr.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by bartlettroscoe** [comment]
> Hm, I can't test my fix, since I can't get kokkos-kernels to build shared + RDC

@mhoemmen, all of the ATDM Trilinos CUDA+RDC builds are `static` builds.   In fact, the default ATDM Trilinos build is a static build as per:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#shared_static

Did the "Steps to Reproduce" given [above](https://github.com/trilinos/Trilinos/issues/6517#issue-545061491) on 'white', 'ride' or 'waterman' not work for you?  It should be just that easy to reproduce the link errors.

**Comment by bartlettroscoe** [comment]
With the merge of PR #6583 (commit f580427ddd113119fa97e9779f8469580f9d573a?), these RDC link errors have gone away today 2020-01-16 as shown [here](https://testing-dev.sandia.gov/cdash/index.php?project=Trilinos&date=2020-01-16&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-&field2=buildname&compare2=63&value2=-rdc-) for these 3 builds.

Closing as complete.

Thanks @mhoemmen!

**Comment by mhoemmen** [comment]
@bartlettroscoe Huh, I didn't expect that but I'm happy!  Thanks for reporting! :-D
