### ISSUE TITLE
STK: install error 

### ISSUE THREAD

**Issue by ikalash** [trilinos/Trilinos#6522]
It looks like there is a Trilinos installation error due to STK showing up in the Albany nightlies: 

https://my.cdash.org/viewBuildError.php?buildid=1754035
http://cdash.sandia.gov/CDash-2-3-0/viewBuildError.php?buildid=92142

Here is the error:

```
CMake Error at packages/stk/stk_util/stk_util/cmake_install.cmake:64 (file):
  file INSTALL cannot find
  "/.../build/TriBuild/packages/stk/stk_util/stk_util/STK_Trilinos_config.h".
Call Stack (most recent call first):
  packages/stk/stk_util/cmake_install.cmake:69 (include)
  packages/stk/cmake_install.cmake:50 (include)
  cmake_install.cmake:110 (include)
```
Could you please have a look at / fix this?

@trilinos/stk

**Comment by alanw0** [comment]
Hi @ikalash, sorry about that! This is the same issue referenced in #6518, and I will have it either fixed or reverted before the end of tomorrow.

**Comment by ikalash** [comment]
Thanks, Alan!  Sorry about creating the duplicate issue - I must have missed #6521.

**Comment by alanw0** [comment]
A fix has been pushed to the develop branch for this. Let me know if you still see any issues.

**Comment by ikalash** [comment]
@alanw0 : I just checked our dashboard and while Trilinos builds/installs correctly now, it appears we have compilation errors in Albany having to do with STK:

```
/.../repos/Albany/src/disc/stk/Albany_AsciiSTKMesh2D.cpp(245): error: namespace "stk::mesh" has no member "set_cell_topology"
```
http://cdash.sandia.gov/CDash-2-3-0/viewBuildError.php?buildid=92176 

Did the ```stk::mesh::set_cell_topology``` routine in STK go away / change?

There's a similar error with ```get_cell_topology```:

```
 /.../repos/Albany/src/disc/stk/Albany_AsciiSTKMesh2D.cpp(255): error: class "stk::mesh::MetaData" has no member "get_cell_topology"
```

**Comment by alanw0** [comment]
@ikalash, yes some methods were deprecated. Our procedure is to decorate functions/methods with the STK_DEPRECATED macro, then after some time (at least 6 weeks) delete them. In this case it was more like 6 months. I've complained to the trilinos-frameowrk folks that the SHOW_DEPRECATED_WARNINGS flag should be on by default, because nobody ever sees our deprecations until we delete the method in question and then it becomes an error instead of a warning.
Anyway, in this case, the MetaData class only deals in stk::topology now. But in the MetaData.hpp header there are functions get_topology and get_cell_topology that can translate back and forth between stk::topology and shards::CellTopology.

**Comment by ikalash** [comment]
Seems this affects SCOREC as well: 
```
/home/ikalash/nightlyAlbanyTests/Results/Trilinos/SCOREC/stk/apfMeshSTK.cc:209:14: error: ‘set_cell_topology’ is not a member of ‘stk::mesh’; did you mean ‘get_cell_topology’?
  209 |   stk::mesh::set_cell_topology(part, topo);
      |              ^~~~~~~~~~~~~~~~~
      |              get_cell_topology
/home/ikalash/nightlyAlbanyTests/Results/Trilinos/SCOREC/stk/apfMeshSTK.cc: In function ‘void apf::copyMeshToMeta(apf::Mesh*, apf::StkModels&, apf::StkMetaData*)’:
/home/ikalash/nightlyAlbanyTests/Results/Trilinos/SCOREC/stk/apfMeshSTK.cc:227:11: error: ‘apf::StkMetaData’ {aka ‘class stk::mesh::MetaData’} has no member named ‘register_cell_topology’; did you mean ‘register_topology’?
  227 |     meta->register_cell_topology(topo[i], ranks[i]);
```
I will open an issue with the SCOREC folks.

**Comment by ikalash** [comment]
@alanw0 : I'm working on converting Albany to work with the new STK routines, and I had a quick question - is there an analog of get_cell_topology_root_part for the class ``stk::mesh::MetaData``?

**Comment by ikalash** [comment]
Never mind - silly me, it's ```get_topology_root_part```.

**Comment by alanw0** [comment]
Sorry I somehow missed your question earlier. But yes you are right, get_topology_root_part.

**Comment by ikalash** [comment]
No problem - I think webmail was malfunctioning...  I got ~30 notifications this afternoon that were from the morning.

**Comment by ikalash** [comment]
I'm almost done fixing up Albany to get it to compile with STK VOTD.  I've had to switch from shards traits to stk::topology for the various elements.  I was curious, what is the distinction b/w elements such as LINE_2 and LINE_2_1D and QUAD_4 and QUAD_4_2D?  I noticed in modifying the code that it matters which of these is used.

**Comment by alanw0** [comment]
Yes it's kind of a confusing distinction. QUAD_4 is a face, and can only be defined in a 3D mesh. QUAD_4_2D can only be defined in a 2D mesh, but then it's an element and not a face. To be more general, QUAD_4 is a side in a 3D mesh and LINE_2 is a side in a 2D mesh. LINE_2_1D is an element in a 1D mesh.

**Comment by ikalash** [comment]
Ah ok, that explains some of the errors I was still seeing for certain tests.  The distinction is critical in implementing a correct fix - thanks for the clarification.

**Comment by ikalash** [comment]
I've fixed Albany to compile/run with STK VOTD.  Thanks again for your help @alanw0 !
