### ISSUE TITLE
STK_Trilinos_config.h install errors in two independent fresh cee-rhel6 openmpi-4.0.1 builds on 2019-01-05

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#6527]
CC: @trilinos/stk, @kddevin (Trilinos Data Services Product Lead), @bartlettroscoe

<Checklist>
<???: Add label "client: ATDM">
<???: Add label "ATDM Sev: Blocker" (by default but could be other "ATDM Sev: XXX")>
<???: Add label "type: bug"?>
<???: Add label for affected packages (e.g. "pkg: MueLu", "pkg: Tpetra", "pkg: Kokkos", etc.)>
<???: Add label "PA: ???Project Area???" (e.g. "PA: Linear Solvers", "PA: Data Services")>
<???: Add milestone "Initial cleanup of new ATDM ..." or "Keep promoted ATDM ...">
<???: Once GitHub Issue is created, add entries for tests to TrilinosATDMStatus/*.csv files>

## Next Action Status

<status-and-or-first-action>

## Description

As shown in [this query](https://testing-dev.sandia.gov/cdash/index.php?project=Trilinos&date=2020-01-05&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-cee-rhel6&field2=buildname&compare2=63&value2=openmpi-4.0.1) the new ATDM Trilinos builds:

* [Trilinos-atdm-cee-rhel6_clang-5.0.1_openmpi-4.0.1_serial_static_opt](https://testing-dev.sandia.gov/cdash/index.php?project=Trilinos&parentid=5135747)
* [Trilinos-atdm-cee-rhel6_gnu-7.2.0_openmpi-4.0.1_serial_shared_opt](https://testing-dev.sandia.gov/cdash/index.php?project=Trilinos&parentid=5136383)

are showing install errors:

```
CMake Error at packagesstk_util/stk_util/cmake_install.cmake:69 (file):
  file INSTALL cannot find
  "/scratch/rabartl/Trilinos.base/NightlyBuilds/Trilinos-atdm-cee-rhel6_clang-5.0.1_openmpi-4.0.1_serial_static_opt/SRC_AND_BUILD/BUILD/packages/stk/stk_util/stk_util/STK_Trilinos_config.h".
Call Stack (most recent call first):
  packagesstk_util/cmake_install.cmake:74 (include)
  packagescmake_install.cmake:56 (include)
  cmake_install.cmake:187 (include)



***
*** The global install failed so resorting to package-by-package installs
***


CMake Error at stk_util/stk_util/cmake_install.cmake:69 (file):
  file INSTALL cannot find
  "/scratch/rabartl/Trilinos.base/NightlyBuilds/Trilinos-atdm-cee-rhel6_clang-5.0.1_openmpi-4.0.1_serial_static_opt/SRC_AND_BUILD/BUILD/packages/stk/stk_util/stk_util/STK_Trilinos_config.h".
Call Stack (most recent call first):
  stk_util/cmake_install.cmake:74 (include)
  cmake_install.cmake:56 (include)


CMake Error at cmake_pbp_install.cmake:25 (message):
  Error, full install failed!
```

Unfortunately, these show up as "Zoltan2" errors since this target does not have their own label.

## Current Status on CDash

The status of these builds for the current testing day can be found [here](https://testing-dev.sandia.gov/cdash/index.php?project=Trilinos&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-cee-rhel6&field2=buildname&compare2=63&value2=openmpi-4.0.1).

## Steps to Reproduce

One should be able to reproduce this failure on any CEE RHE6 or RHEL7 machine as described in:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md

More specifically, the commands given for the system 'cee-rhel6' are provided at:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#cee-rhel6-environment

The exact commands to reproduce this issue should be:

```
$ cd <some_build_dir>/

$ source $TRILINOS_DIR/cmake/std/atdm/load-env.sh \
    Trilinos-atdm-cee-rhel6_clang-5.0.1_openmpi-4.0.1_serial_static_opt

$ rm -r packages

$ cmake \
 -GNinja \
 -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
 -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_STK=ON \
 -DCMAKE_INSTALL_PREFIX=install /
 $TRILINOS_DIR

$ make NP=16 install
```

**Comment by bartlettroscoe** [comment]
Hum, sees this issue was already reported by @ikalash in #6522.  Albany testing just caught this earlier.

Note that rebuilds of Trilinos did not show this problem.

This suggests the Trilinos PR testing could be improved if it just do a 'make install' as part of the testing.

I will close this as a duplicate.

**Comment by bartlettroscoe** [comment]
FYI:  Those two builds showed no build errors today as shown at:

* https://testing-dev.sandia.gov/cdash/index.php?project=Trilinos&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-cee-rhel6&field2=buildname&compare2=63&value2=openmpi-4.0.1

And I verified that that file got installed today:

```
$ ssh ceerws1113

$ find /projects/atdm_devops/trilinos_installs/2020-01-06/cee-rhel6_clang-5.0.1_openmpi-4.0.1_serial_static_opt/ -type f -name "STK_Trilinos_config.h"
/projects/atdm_devops/trilinos_installs/2020-01-06/cee-rhel6_clang-5.0.1_openmpi-4.0.1_serial_static_opt/include/STK_Trilinos_config.h
```

**Comment by bartlettroscoe** [comment]
@trilinos/framework, @ikalash 

@alanw0,

Following up from our conversation in #6528, I checkout out the Trilinos version commit c858b704ab83574d26a647ff053fa782099cefdd  and then follows the "Steps to Reproduce" [above](https://github.com/trilinos/Trilinos/issues/6527#issue-545816345) on my CEE RHEL6 machine 'ceerws1113' and I go the 'make install' error:

```
CMake Error at packages/stk/stk_util/stk_util/cmake_install.cmake:69 (file):
  file INSTALL cannot find
  "/scratch/rabartl/Trilinos.base/BUILDS/ATDM/CEE-RHEL6/CHECKIN/cee-rhel6_clang-5.0.1_openmpi-4.0.1_serial_static_opt/packages/stk/stk_util/stk_util/STK_Trilinos_config.h".
Call Stack (most recent call first):
  packages/stk/stk_util/cmake_install.cmake:74 (include)
  packages/stk/cmake_install.cmake:56 (include)
  cmake_install.cmake:172 (include)
```

**Comment by alanw0** [comment]
@bartlettroscoe ok thanks, good info. In this case it would have caught my error.
