### ISSUE TITLE
Do 'make install' as part of Trilinos PR testing

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#6528]
@trilinos/framework, @ikalash 

One thing that would improve the testing done by the Trilios PR tester to help protect customers like ATDM and Albany is if it did a 'make install' as part of PR testing and submitting to CDash.  That is very easy to implement and takes very little extra computer time.  ATDM Trilinos builds now do this and it caught a problem with STK described in #6522 and #6527.  (But in that case, it was only on configure and build from scratch, not rebuilds.)

The ATDM Trilinos builds run with [TRIBITS_CTEST_DRIVER()](https://tribits.org/doc/TribitsDevelopersGuide.html#list-of-all-variables-tribits-ctest-driver) have an option to do 'make install' and report install errors the CDash like shown in #6527 and [here](https://testing-dev.sandia.gov/cdash/viewBuildError.php?buildid=5135747).  When using that system, it takes just one option [CTEST_DO_INSTALL=TRUE](https://tribits.org/doc/TribitsDevelopersGuide.html#tribits-ctest-driver) to set that up.

Consider this an official request from ATDM DevOps.

**Comment by ikalash** [comment]
I agree completely with Ross that testing an install of Trilinos as part of PR testing would be great.  I didn't realize it was not being done prior to the STK issue that affected the install cropping up this weekend.

**Comment by bartlettroscoe** [comment]
NOTE: What I a suggesting here is just the 'make install' part of the larger and more complete installation testing described in #5027.  Just the 'make install' catches dumb errors like messed up CMake logic about installing header files.  This is so easy to do there is no reason that I can see not to do it in every build of Trilinos that posts to CDash (and it is already implemented when using [TRIBITS_CTEST_DRIVER()](https://tribits.org/doc/TribitsDevelopersGuide.html#list-of-all-variables-tribits-ctest-driver)).  The only downside is that it will consume more memory since libraries and header files will be copied to the install directory.  But usually this is small compared to the disk storage for the Trilinos test and example executables that get built.

**Comment by alanw0** [comment]
@bartlettroscoe I don't know if a 'make install' would have caught this stk error. The stk error was that a header was not being installed (due to a mistake I made in editing CMakeLists.txt files). So unfortunately the only way to catch that error is probably to try to compile some code that includes that stk header... I don't know if that's feasible in automated pre-push testing.

**Comment by bartlettroscoe** [comment]
>  I don't know if a 'make install' would have caught this stk error.

@alanw0, in general, that is correct but not in this case.  In this case, the 'make install' command failed as shown in:

* https://testing-dev.sandia.gov/cdash/viewBuildError.php?buildid=5135747

showing:

```
CMake Error at packagesstk_util/stk_util/cmake_install.cmake:69 (file):
  file INSTALL cannot find
  "/scratch/rabartl/Trilinos.base/NightlyBuilds/Trilinos-atdm-cee-rhel6_clang-5.0.1_openmpi-4.0.1_serial_static_opt/SRC_AND_BUILD/BUILD/packages/stk/stk_util/stk_util/STK_Trilinos_config.h".
Call Stack (most recent call first):
  packagesstk_util/cmake_install.cmake:74 (include)
  packagescmake_install.cmake:56 (include)
  cmake_install.cmake:187 (include)
```

and returned a non-zero error code.

**Comment by wadeburgess** [comment]
Migrated to Jira.
