### ISSUE TITLE
Framework: autotester does not launch the cuda build

### ISSUE THREAD

**Issue by lucbv** [trilinos/Trilinos#6542]
## Bug Report
@trilinos/framework 

### Description
PR #6535 #6537 and #6452 are blocked because of CUDA build not starting or not finishing. This is blocking PRs from merging in Trilinos.

**Comment by csiefer2** [comment]
Lovely

**Comment by bartlettroscoe** [comment]
Yup, our ATDM Trilinos builds are not showing up from 'ride' either:

* https://testing-dev.sandia.gov/cdash/index.php?project=Trilinos&date=2020-01-08&filtercount=1&showfilters=1&field1=buildname&compare1=65&value1=Trilinos-atdm-

Someone needs to see whats up with the Jenkins slave on ride.

**Comment by jwillenbring** [comment]
Per an email to users, a hardware issue with Ride was resolved late yesterday afternoon. Looking at Jenkins this morning, it appears recent builds have been processed more successfully. No failed builds for 16 hours.

**Comment by lucbv** [comment]
@jwillenbring thanks for the update, it does look good now so I will close this issue
