### ISSUE TITLE
Trilinos PR Tester: Possible defective logic about code approvals and testing?

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#6545]
## Bug Report

@trilinos/framework, @jeforster 

### Description

Looks like there may be a bug in the Trilinos PR tester logic demonstrated in PR #6536.  The comment https://github.com/trilinos/Trilinos/pull/6536#issuecomment-571914353 posted by the PR tester this morning 1:46 AM ET 1/8/2020 said:

> Status Flag 'Pre-Test Inspection' - - This Pull Request Requires Inspection... The code must be inspected by a member of the Team before Testing/Merging
THE LAST COMMIT TO THIS PULL REQUEST HAS NOT BEEN REVIEWED YET!

However, I approved the PR at 4:46 PM ET 1/7/2020 the day before as shown at https://github.com/trilinos/Trilinos/pull/6536#pullrequestreview-339527781.  The last commit pushed was 34f69dc which was pushed at 4:38 PM ET 1/7/220 as shown at https://github.com/trilinos/Trilinos/pull/6536#event-2929142723.  The screen shot of this sequence that I took just now at 9:25 AM ET 1/8/2020 is:

![image](https://user-images.githubusercontent.com/1959736/71986250-232da380-31fa-11ea-9bac-f2d29f0831e8.png)

And this is very important, note that GitHub believes that the PR has been approved as shown in the following screen shot that I just took right now at 9:30 AM ET on 1/8/2020.

![image](https://user-images.githubusercontent.com/1959736/71986164-fa0d1300-31f9-11ea-826d-733334764bd1.png)

I am guessing this is some type of race condition in the Trilinos PR tester logic.

**Comment by bartlettroscoe** [comment]
@trilinos/framework,

Since there is some urgency in getting this branch merged, I will try adding a new review and see if the PR tester believes that it is reviewed.  And if that does not work, I will try to push a new dummy commit and then approve it and try to get it to work.

**Comment by bartlettroscoe** [comment]
Looks like adding a new approving review triggered the PR tester to try a PR build as shown at https://github.com/trilinos/Trilinos/pull/6536#issuecomment-572270436  But alas, that failed too due to no CUDA build (i.e. #6542).

**Comment by jwillenbring** [comment]
Since this has not been impacting us for the last year and a half, I am going to close this. If we see additional issues, we can consider those then.
