### ISSUE TITLE
MueLu: "Challenge" example fails to link with CUDA, when Serial Node disabled

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#655]
@trilinos/muelu 

MueLu's "Challenge" example (muelu/doc/Tutorial/src/Challenge.cpp) fails to link when CUDA is enabled, but Tpetra's "Serial" Node type is disabled.

```
undefined reference to `Tpetra::Map<int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::getNode() const'
```

(etc.)

**Comment by jhux2** [comment]
@tawiesn @mhoemmen Would you post your cmake configure line?

**Comment by mhoemmen** [comment]
```
-D Trilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON
-D BUILD_SHARED_LIBS:BOOL=ON
-D TPL_ENABLE_CUDA:BOOL=ON
  -D Kokkos_ENABLE_Cuda_UVM:BOOL=ON
  -D Tpetra_INST_CUDA:BOOL=ON
-D Trilinos_ENABLE_OpenMP:BOOL=OFF
-D Trilinos_SHOW_DEPRECATED_WARNINGS:BOOL=ON
-D Trilinos_ENABLE_Fortran:BOOL=OFF
-D Teuchos_ENABLE_COMPLEX:BOOL=ON
-D Tpetra_INST_COMPLEX_DOUBLE:BOOL=ON
-D TPL_ENABLE_SuperLU:BOOL=ON
  -D SuperLU_INCLUDE_DIRS:FILEPATH=\"${SUPERLU_PATH}/include\"
  -D SuperLU_LIBRARY_DIRS:FILEPATH=\"${SUPERLU_PATH}/lib\"
-D TPL_ENABLE_Netcdf:BOOL=ON
  -D Netcdf_INCLUDE_DIRS:FILEPATH=\"${NETCDF_PATH}/include\"
  -D Netcdf_LIBRARY_DIRS:FILEPATH=\"${NETCDF_PATH}/lib\"
-D TPL_ENABLE_HDF5:BOOL=ON
  -D HDF5_INCLUDE_DIRS:FILEPATH=\"${HDF5_PATH}/include\"
  -D HDF5_LIBRARY_DIRS:FILEPATH=\"${HDF5_PATH}/lib\"
-D TPL_ENABLE_ParMETIS:BOOL=ON
  -D ParMETIS_INCLUDE_DIRS:FILEPATH=\"${PARMETIS_PATH}/include\"
  -D ParMETIS_LIBRARY_DIRS:FILEPATH=\"${PARMETIS_PATH}/lib\"
-D TPL_ENABLE_Boost:BOOL=ON
  -D Boost_INCLUDE_DIRS=${BOOST_PATH}/include
  -D Boost_LIBRARY_DIRS=${BOOST_PATH}/lib
-D TPL_ENABLE_BoostLib:BOOL=ON
  -D BoostLib_INCLUDE_DIRS=${BOOST_PATH}/lib
  -D BoostLib_LIBRARY_DIRS=${BOOST_PATH}/lib
-D CMAKE_BUILD_TYPE:STRING=RELEASE
-D TPL_ENABLE_MPI:BOOL=ON
-D Tpetra_INST_OPENMP:BOOL=OFF
-D Tpetra_INST_SERIAL:BOOL=OFF
-D Tpetra_INST_INT_INT:BOOL=ON
```

**Comment by jhux2** [comment]
@mhoemmen Even before the error you report, I encounter the following:

```
/home/jhu/trilinos/Trilinos/packages/kokkos/core/src/Cuda/Kokkos_CudaExec.hpp(284): error: The closure type for a lambda ("lambda [](int)->void") cannot be used in the template argument type of a __global__ function template instantiation, unless the lambda is defined within a __device__ or __global__ function
          detected during:
            instantiation of "Kokkos::Impl::cuda_parallel_launch_local_memory" based on template argument <Kokkos::Impl::ParallelFor<lambda [](int)->void, Kokkos::RangePolicy<Kokkos::DefaultExecutionSpace>, Kokkos::DefaultExecutionSpace>>
(284): here
            instantiation of "Kokkos::Impl::CudaParallelLaunch<DriverType, false>::CudaParallelLaunch(const DriverType &, const dim3 &, const dim3 &, int, cudaStream_t) [with DriverType=Kokkos::Impl::ParallelFor<lambda [](int)->void, Kokkos::RangePolicy<Kokkos::DefaultExecutionSpace>, Kokkos::DefaultExecutionSpace>]"
/home/jhu/trilinos/Trilinos/packages/kokkos/core/src/Cuda/Kokkos_Cuda_Parallel.hpp(554): here
            instantiation of "void Kokkos::Impl::ParallelFor<FunctorType, Kokkos::RangePolicy<Traits...>, Kokkos::Cuda>::execute() const [with FunctorType=lambda [](int)->void, Traits=<Kokkos::DefaultExecutionSpace>]"
/home/jhu/trilinos/Trilinos/packages/kokkos/core/src/Kokkos_Parallel.hpp(221): here
            instantiation of "void Kokkos::parallel_for(size_t, const FunctorType &, const std::string &) [with FunctorType=lambda [](int)->void]"
/home/jhu/trilinos/Trilinos/packages/kokkos/core/src/Kokkos_Parallel.hpp(241): here
            instantiation of "void Kokkos::parallel_for(const std::string &, const ExecPolicy &, const FunctorType &) [with ExecPolicy=int, FunctorType=lambda [](int)->void]"
/home/jhu/trilinos/Trilinos/packages/muelu/src/Misc/MueLu_CoordinatesTransferFactory_kokkos_def.hpp(159): here
            instantiation of "void MueLu::CoordinatesTransferFactory_kokkos<Scalar, LocalOrdinal, GlobalOrdinal, Kokkos::Compat::KokkosDeviceWrapperNode<DeviceType, DeviceType::memory_space>>::Build(MueLu::CoordinatesTransferFactory_kokkos<Scalar, LocalOrdinal, GlobalOrdinal, Kokkos::Compat::KokkosDeviceWrapperNode<DeviceType, DeviceType::memory_space>>::Level &, MueLu::CoordinatesTransferFactory_kokkos<Scalar, LocalOrdinal, GlobalOrdinal, Kokkos::Compat::KokkosDeviceWrapperNode<DeviceType, DeviceType::memory_space>>::Level &) const [with Scalar=std_complex0double0, LocalOrdinal=int, GlobalOrdinal=long, DeviceType=Kokkos::Cuda]"
/home/jhu/trilinos/Trilinos/packages/muelu/src/Utils/MueLu_ETI_4arg.hpp(32): here

```

What the heck does this mean?

**Comment by jhux2** [comment]
Is it related to this?  http://stackoverflow.com/a/30441692

**Comment by jhux2** [comment]
I've disabled MueLu's Kokkos-specific code, which you were building anyway.  This will hopefully let the build get by the closure-type error.

**Comment by mhoemmen** [comment]
@jhux2 wrote:
> Is it related to this? http://stackoverflow.com/a/30441692

Yes.  CUDA 7.5 does not allow device lambdas by default.

**Comment by jhux2** [comment]
My build got further, but now I get
```
nvcc error   : 'nvlink' died due to signal 11 (Invalid memory reference)
nvcc error   : 'nvlink' core dumped
```
I'm using
```
nvlink --version
nvlink: NVIDIA (R) Cuda linker
Copyright (c) 2005-2015 NVIDIA Corporation
Built on Tue_Aug_11_14:27:32_CDT_2015
Cuda compilation tools, release 7.5, V7.5.17

```

**Comment by jhux2** [comment]
> My build got further, but now I get

This looks similar to a [link issue](https://devtalk.nvidia.com/default/topic/763460/cuda-programming-and-performance/how-to-debug-quot-invalid-memory-reference-quot-while-generating-linker/post/4270456/#4270456)  reported for CUDA 6.5:

**Comment by mhoemmen** [comment]
I've been getting those NVCC link errors too.  One way to fix those is to put Kokkos functors in named namespaces; NVCC doesn't seem to like them in anonymous namespaces.

**Comment by jhux2** [comment]
@mhoemmen MueLu just had a few functors in anonymous namespaces.  I converted those to named namespaces, but am still getting the same error.

**Comment by jhux2** [comment]
@crtrott @nmhamster I'm stuck on a link error using nvcc.  I can't tell much from the message, and searching mostly indicates that other folks have hit internal bugs in nvcc.  Might either of you have suggestions on what I might try next?  Attached are the link lines in case they are helpful.   Thanks.

[makelog-show.txt](https://github.com/trilinos/Trilinos/files/501187/makelog-show.txt)
[makelog.txt](https://github.com/trilinos/Trilinos/files/501188/makelog.txt)

**Comment by jhux2** [comment]
@mhoemmen Since I can't currently recreate the reported problem, I just pushed a new option ```-D MueLu_ENABLE_Tutorial```.  It defaults to ```ON```, so it's backwards compatible, but it should allow you to get past this particular compilation error.

**Comment by mhoemmen** [comment]
I have the same problem with Xpetra:
```
Linking CXX executable Xpetra_BlockedCrsMatrix_UnitTests.exe
nvcc error   : 'nvlink' died due to signal 11 (Invalid memory reference)
nvcc error   : 'nvlink' core dumped
```
I suspect that we could fix this by breaking up that rather large file into a collection of smaller files.

**Comment by jhux2** [comment]
> I have the same problem with Xpetra:
> 
> Linking CXX executable Xpetra_BlockedCrsMatrix_UnitTests.exe
> nvcc error   : 'nvlink' died due to signal 11 (Invalid memory reference)
> nvcc error   : 'nvlink' core dumped
> 
> I suspect that we could fix this by breaking up that rather large file into a collection of smaller files.

Is this a debug build by any chance?  In other cases where nvlink dies, I've found that removing '-G' (and maybe '-g') from the compile line fixes the problem.

**Comment by mhoemmen** [comment]
> Is this a debug build by any chance? In other cases where nvlink dies, I've found that removing '-G' (and maybe '-g') from the compile line fixes the problem.

yup, debug build.  i sure would like to have debug builds though ;-)  how do i remove -G but keep -g and CMAKE_BUILD_TYPE=DEBUG?

**Comment by jhux2** [comment]
> > Is this a debug build by any chance? In other cases where nvlink dies, I've found that removing '-G' (and maybe '-g') from the compile line fixes the problem.
> 
> yup, debug build. i sure would like to have debug builds though ;-) how do i remove -G but keep -g and CMAKE_BUILD_TYPE=DEBUG?
I don't know -- I gather you are not specifying -G in your config script.  In my case, I finally resorted to doing ```CMAKE_BUILD_TYPE=RELEASE```.

**Comment by jhux2** [comment]
@mhoemmen Did you ever figure out how to do the following simultaneously?

- remove ```-G```
- keep ```-g``` and ```CMAKE_BUILD_TYPE=debug```

**Comment by mhoemmen** [comment]
I was away at a workshop for the past couple days.  I'm rebuilding now to see if I can get the file to compile with most of the tests commented out.

**Comment by mhoemmen** [comment]
@jhux2 @tawiesn After commenting out all but one of the tests in xpetra/test/BlockedCrsMatrix/BlockedCrsMatrix_UnitTests.cpp, I was able to get the file to compile.  However, Xpetra_ThyraBlockedOperator_UnitTests.exe now refuses to link, likely for the same reason.

**Comment by tawiesn** [comment]
You mean the 

> Linking CXX executable Xpetra_BlockedCrsMatrix_UnitTests.exe
> nvcc error : 'nvlink' died due to signal 11 (Invalid memory reference)
> nvcc error : 'nvlink' core dumped

problem that @jhux2 also encountered?

**Comment by mhoemmen** [comment]
@jhux2 libbelostpetra.so also fails to link for me, so I might as well just figure out how to replace `-G` with `-g`, while still leaving `CMAKE_BUILD_TYPE=DEBUG`.  I think CMake has options to change the debug-build-only compiler flags.

**Comment by mhoemmen** [comment]
@jhux2 I'm trying again with `CMAKE_CXX_FLAGS_DEBUG:STRING="-g -Os"`.  This minimizes code size.  I'm hoping this will work, and also let me keep all the original debug flags.

**Comment by jhux2** [comment]
> @jhux2 I'm trying again with CMAKE_CXX_FLAGS_DEBUG:STRING="-g -Os". This minimizes code size. I'm hoping this will work, and also let me keep all the original debug flags.

@mhoemmen Maybe @bmpersc knows how to do this.

**Comment by mhoemmen** [comment]
@jhux2 Wow, that come me through libbelostpetra.so!  Working on the rest now.

**Comment by jhux2** [comment]
> @jhux2 Wow, that come me through libbelostpetra.so! Working on the rest now.

Nice.  Did you keep ```-G```?

**Comment by bmpersc** [comment]
I believe that setting the CMAKE_CXX_FLAGS_DEBUG manually will replace what cmake was going to put in for the flags. However, it is possible that tribits is also modifying that which is probably additive like you are wanting.

**Comment by mhoemmen** [comment]
@jhux2 wrote:
> Nice. Did you keep -G?

There never was a -G, as far as I can tell.

**Comment by mhoemmen** [comment]
This wasn't a complete fix; some Xpetra tests still fail to link.  However, it helped.  In particular, I was able to build libbelostpetra.so.

**Comment by jhux2** [comment]
> > @jhux2 wrote:
> > 
> >     Nice. Did you keep -G?
> 
> There never was a -G, as far as I can tell.

So maybe ```-Os``` would allow  the use of ```-G``` for nvcc, which would be great for debugging?

**Comment by mhoemmen** [comment]
I still can't build Xpetra_ThyraBlockedOperator_UnitTests.exe, for example, so I don't think this is a complete solution.  It still would make sense to split up tests.

**Comment by tawiesn** [comment]
@mhoemmen: Does it link if you comment out all except of one tests in Xpetra_ThyraBlockedOperator_UnitTests.exe now? If yes, we can split the unit tests. How many instantiations have you enabled in your build?

I'm wondering whether we could have some kind of test template which is used to auto generate a unit tests from a specific cpp file containing one test (similar to the ETI code generation). For adding a unit test we would have to add one more cpp file containing the test code and add a line to CMakeLists.txt. Does that make sense?

**Comment by mhoemmen** [comment]
@tawiesn wrote:
> Does it link if you comment out all except of one tests in Xpetra_ThyraBlockedOperator_UnitTests.exe now? If yes, we can split the unit tests.

I haven't tried this with that specific unit test yet, but I have tried it with another Xpetra test that was having the same trouble, and that worked.

> How many instantiations have you enabled in your build?

  - `Scalar = double, std::complex<double>` (plus all the integer Scalar types)
  - `GO = int, long` (would really love to disable `GO = int` at some point...)
  - `Node = KokkosCudaWrapperNode` (only that Node type)

**Comment by tawiesn** [comment]
@mhoemmen Do you have a rough idea how many unit tests can be conglomerated in an executable in order to be able to compile them (with cuda)? If we split the unit tests it would be good to have a rough idea how to split them (e.g. not more than 3000 lines,...)

**Comment by mhoemmen** [comment]
@tawiesn wrote:
> Do you have a rough idea how many unit tests can be conglomerated in an executable in order to be able to compile them (with cuda)?

Alas, no, I haven't done that experiment.  There are different ways you could split up tests.  You could either put each unit test in its own file, with all instantiations, or you could split up the tests by instantiations.
