### ISSUE TITLE
Phalanx_mda_data_layout_MPI_1 test failing in build Trilinos-atdm-mutrino-intel-opt-openmp-KNL starting 2020-01-04

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#6554]
CC: @trilinos/phalanx , @mperego (Trilinos Discretizations Product Lead)

<Checklist>
<???: Add label "client: ATDM">
<???: Add label "ATDM Sev: Blocker" (by default but could be other "ATDM Sev: XXX")>
<???: Add label "type: bug"?>
<???: Add label for affected packages (e.g. "pkg: MueLu", "pkg: Tpetra", "pkg: Kokkos", etc.)>
<???: Add label "PA: ???Project Area???" (e.g. "PA: Linear Solvers", "PA: Data Services")>
<???: Add milestone "Initial cleanup of new ATDM ..." or "Keep promoted ATDM ...">
<???: Once GitHub Issue is created, add entries for tests to TrilinosATDMStatus/*.csv files>

## Next Action Status

<status-and-or-first-action>

## Description

As shown in [this query](https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&begin=2019-12-10&end=2020-01-08&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-mutrino-intel-opt-openmp-KNL&field2=testname&compare2=61&value2=Phalanx_mda_data_layout_MPI_1&field3=site&compare3=61&value3=mutrino) the test:

* `Phalanx_mda_data_layout_MPI_1`

in the build:

* `Trilinos-atdm-mutrino-intel-opt-openmp-KNL`

started failing on testing day 2020-01-06.

There are numerous failures (O(90) failures).  Some examples of the types of failures seen include:

```
 rank8.identifier() = <8Ordinal1,8Ordinal2,8Ordinal3,8Ordinal4,8Ordinal5,8Ordinal6,8Ordinal7,8Ordinal8>(1,2,3,4,5,6,7,8) == "<Ordinal1,Ordinal2,Ordinal3,Ordinal4,Ordinal5,Ordinal6,Ordinal7,Ordinal8>(1,2,3,4,5,6,7,8)" = <Ordinal1,Ordinal2,Ordinal3,Ordinal4,Ordinal5,Ordinal6,Ordinal7,Ordinal8>(1,2,3,4,5,6,7,8) : FAILED ==> /lscratch1/jenkins/mutrino-slave/workspace/Trilinos-atdm-mutrino-intel-opt-openmp-KNL/SRC_AND_BUILD/Trilinos/packages/phalanx/test/DataLayout/MDALayout.cpp:101
```

and

```
 names[0] = 4Cell == "Cell" = Cell : FAILED ==> /lscratch1/jenkins/mutrino-slave/workspace/Trilinos-atdm-mutrino-intel-opt-openmp-KNL/SRC_AND_BUILD/Trilinos/packages/phalanx/test/DataLayout/MDALayout.cpp:155
```

and

```
 rank1.name(0) = 8Ordinal1 == "Ordinal1" = Ordinal1 : FAILED ==> /lscratch1/jenkins/mutrino-slave/workspace/Trilinos-atdm-mutrino-intel-opt-openmp-KNL/SRC_AND_BUILD/Trilinos/packages/phalanx/test/DataLayout/MDALayout.cpp:536
```

Therefore, this looks like a problem with name mangling.

## Current Status on CDash

* [Last 30 days of test history](https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&begin=30%20days%20ago&end=now&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-mutrino-intel-opt-openmp-KNL&field2=testname&compare2=61&value2=Phalanx_mda_data_layout_MPI_1&field3=site&compare3=61&value3=mutrino)

## Steps to Reproduce

One should be able to reproduce this failure on the machine 'mutrino' as described in:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md

More specifically, the commands given for the system 'mutrino' are provided at:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#mutrino

The exact commands to reproduce this issue should be:

```
$ cd <some_build_dir>/

$ source $TRILINOS_DIR/cmake/std/atdm/load-env.sh <build-name>

$ cmake \
 -GNinja \
 -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
 -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_Phalanx=ON \
 $TRILINOS_DIR

$ make NP=16

$ salloc -N 1 -p knl -J $ATDM_CONFIG_BUILD_NAME ctest -j4
```

**Comment by bartlettroscoe** [comment]
Could this be a change of the compler on 'mutrino'?  On testing day 2020-01-04, the [configure output](https://testing-dev.sandia.gov/cdash/viewConfigure.php?buildid=5139278) showed:

```
-- The CXX compiler identification is Intel 19.0.4.20190416
```

On the previous testing day for which results were available 2019-12-31, the [configure output](https://testing-dev.sandia.gov/cdash/viewConfigure.php?buildid=5125654) showed:

```
-- The CXX compiler identification is Intel 19.0.4.20190416
```

Therefore, it does not look like the compiler changed.

Therefore, someone should look into code changes between 2019-12-31 and 2020-01-04.

**Comment by rppawlo** [comment]
It was a quick fix, but I'm waiting for mutrino admins to fix my account. Currently can't launch jobs to verify. Should go in soon...

**Comment by bartlettroscoe** [comment]
Looking at [this query](https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&begin=2019-12-01&end=2020-02-28&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-mutrino-intel-opt-openmp-KNL&field2=testname&compare2=61&value2=Phalanx_mda_data_layout_MPI_1&field3=site&compare3=61&value3=mutrino) we can see this test started passing in this build on 2020-01-10 and has been passing ever since.

Closing as complete.
