### ISSUE TITLE
Zoltan: Driver/example for running coloring algorithms on raw CRS graph?

### ISSUE THREAD

**Issue by brian-kelley** [trilinos/Trilinos#6560]
## Question
@trilinos/zoltan

I would like to run the Zoltan distance-2 coloring on a graph from the SuiteSparse collection, for comparing performance to KokkosKernels. Is there an example somewhere that sets up the Zoltan_Struct and all the callbacks for accessing a graph that is stored explicitly? (e.g. ``int nrows``, ``int* rowptrs`` and ``int* colinds``). This would be on a single MPI rank only. Even better would be to not use MPI at all.

**Comment by srajama1** [comment]
The best option is to use zdrive.exe I think. 
See for example 
https://github.com/trilinos/Trilinos/blob/master/packages/zoltan/test/ch_simple/zdrive.inp.color-dist2

I also think the File Type there could be matrix market, but don't remember that exactly. I am not able to find the old zdrive documentation too.  @egboman and @kddevin can help you there.

**Comment by kddevin** [comment]
Siva is correct.  Here's how to run:
BUILD_DIR/packages/zoltan/test/zdrive.exe zdrive.inp

Here's a file that will read matrix market; here "simple" refers to filename simple.mtx, which is a general MatrixMarket file.
```
Decomposition Method = none
Zoltan Parameters = comm_pattern=S
Zoltan Parameters = vertex_visit_order=I
Zoltan Parameters = superstep_size=100
Zoltan Parameters = coloring_problem=distance-2
File Type = matrixmarket
File Name = simple
Parallel Disk Info = number=0
zdrive action = 5
```
The number of colors gets reported:
```
Valid coloring found; #colors = 7.
```

Note that this test calls a no-op partitioning method before doing the coloring.  If you want to measure times, we'll need to add some timers around only the coloring call.  The times reported are for partitioning.

**Comment by kddevin** [comment]
The parameters are described at http://cs.sandia.gov/zoltan/ug_html/ug_color.html

**Comment by brian-kelley** [comment]
@srajama1 @kddevin Thanks, this is perfect.
