### ISSUE TITLE
ShyLU: CUDA build error, possibly related to "using namespace std" in global namespace

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#657]
@trilinos/shylu I think we've seen something like this before.  Back then, it related to including math.h instead of cmath.  I didn't see any math.h includes in this file or its header, but there might be some included somewhere.

```
[ 90%] Building CXX object packages/shylu/core/src/CMakeFiles/shylu.dir/epetra/shylu_local_schur_operator.cpp.o
.../Trilinos/packages/tpetra/kernels/src/Kokkos_ArithTraits.hpp(572): error: more than one instance of overloaded function "isinf" matches the argument list:
            function "isinf(float)"
            function "std::isinf(float)"
            argument types are: (const float)
```

**Comment by jjellio** [comment]
This may come up from "using namespace std" in shylu_util.h  I've also seen this from including tgmath.

**Comment by mhoemmen** [comment]
> "using namespace std" in shylu_util.h

oh...

**Comment by srajama1** [comment]
I'll take care of it.

**Comment by mhoemmen** [comment]
> I'll take care of it.

Thanks Siva!  It's not really blocking anything at the moment, but it might cause some trouble once we plug ShyLU into Ifpack2 for solves.
