### ISSUE TITLE
Framework:  PR Testing needs one test with Tpetra_INST_INT_INT

### ISSUE THREAD

**Issue by kddevin** [trilinos/Trilinos#6570]
## Bug Report
@trilinos/framework @jwillenbring @ZUUL42 

### Description

The default global ordinal type in Trilinos has been changed to long long.  ETI no longer builds global ordinal type int by default.  A PR test is needed that enables Tpetra_INST_INT_INT so that global ordinal = int continues to be tested and so that any tests hard-coded to use int are run as part of PR testing.  Tpetra_INST_INT_INT allows code (e.g., Xpetra, Zoltan2) that interoperates with Epetra to be exercised as well.

I think this issue is high priority.

**Comment by kddevin** [comment]
@jwillenbring @ZUUL42

**Comment by kddevin** [comment]
Discussed at Trilinos Product Leader's meeting on 1/22/20
@trilinos/framework will convert one of the PR tests to use Tpetra_INST_INT_INT
They will use one of the older compiler tests.  Thanks, @jwillenbring

**Comment by cgcgcg** [comment]
Was an int-int build ever added? It seems that the autotester doesn not test MueLu with Epetra.

**Comment by ZUUL42** [comment]
I added the Tpetra_INST_INT_INT = ON flag to the Intel 17 PR build.
I'm getting a few failing tests from @trilinos/trilinoscouplings & @trilinos/muelu.
[CDash](https://testing.sandia.gov/cdash/index.php?project=Trilinos&display=project&filtercount=3&showfilters=1&filtercombine=and&field1=site&compare1=61&value1=ascic158&field2=buildname&compare2=61&value2=PR-instintintON-test-Trilinos_pullrequest_intel_17.0.1-6212&field3=buildstamp&compare3=61&value3=20200421-1749-Experimental)

**Comment by cgcgcg** [comment]
@ZUUL42 Nice. We'll clean up these issues and let you know when you can kick off another build.

**Comment by cgcgcg** [comment]
@ZUUL42 Can we try the build again?

**Comment by ZUUL42** [comment]
@cgcgcg already on it.
I kicked off this build a couple hours ago merging my branch to yours in that PR.
[CDash](https://testing.sandia.gov/cdash/index.php?project=Trilinos&display=project&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=PR-instintintON-test-Trilinos_pullrequest_intel_17.0.1-6228&field2=buildstamp&compare2=63&value2=Experimental)
It should finish up soon.

**Comment by cgcgcg** [comment]
Looks like the build went through?

**Comment by cgcgcg** [comment]
Looks like MueLu+Epetra is being tested now. I'm cool with closing the issue.
