### ISSUE TITLE
AztecOO solve for MultiVector

### ISSUE THREAD

**Issue by humhang** [trilinos/Trilinos#6573]
I would like to solve for system AX=B where X and B is MultiVectors using AztecOO. But it seems that only the first vector in MultiVectors are solved. 

Is this intended or a bug?

**Comment by mhoemmen** [comment]
@trilinos/aztecoo 

AztecOO only knows how to solve for one vector at a time.  You can work around this issue by iterating over the vectors of X and B and doing a separate AztecOO solve for each.

**Comment by mhoemmen** [comment]
It looks like your question has been answered.  If not, please feel free to reopen.  Thanks!
