### ISSUE TITLE
Teptra: MultiVector and const protection

### ISSUE THREAD

**Issue by rppawlo** [trilinos/Trilinos#6575]
## Bug Report
@trilinos/tpetra 

### Description
To prevent a tpetra object from changing values, I thought we should be using:
```
const Tpetra::MultiVector<double,...>
```
However, the return type on getLocalViewDevice() is
```
typename dual_view_type::t_dev getLocalViewDevice () const;
```
I think this should instead be dual_view_type::t_dev_const with a separate implementation for the non-const accessor?

If Tpetra was following a similar approach to const enforcement as kokkos views where you have to declare the scalar type to be const to block values from changing:
```
Kokkos::View<const double,...>
```
then, using t_dev makes sense. But I tried to create a Tpetra::MultiVector<const double,...> and that failed with a ton of undefined references. Maybe the eti for const versions is missing (I'd hate to have to go down that path since is will increase compile times since const version  would be treated as a separate scalar type). @mhoemmen can you comment on const correctness of MultiVector objects? Maybe I am missing something?

**Comment by mhoemmen** [comment]
`Tpetra::MultiVector` is more like a `Kokkos::DualView` and not at all like a `std::vector`.

That was a decision that came out of the 2014 Kokkos 2.0 refactor.  It's generally awful that Trilinos passes everything around by RCP, and Christian was hoping Tpetra objects would have behavior more consistent with `Kokkos::View`.

**Comment by rppawlo** [comment]
So does that mean to support const you will have to double the number of ETI scalar types? I tried putting const on the scalar type and had a bunch of link errors.

**Comment by mhoemmen** [comment]
@rppawlo No -- the idea is that Scalar is always nonconst.  You can use `withLocalAccess` to declare access intent.

**Comment by rppawlo** [comment]
@mhoemmen - so just to be clear, with the current design, if I am passing around a MultiVector, there's currently no way to prevent someone from changing values even if the MultiVector is declared const? 

Also - the const model for Tpetra is not the same as a View (which can block changing values with View<const double,...>) on one end and std::vector (can block with const std::vector<...>) on the other end, but is something in between?

**Comment by mhoemmen** [comment]
@rppawlo wrote:
> if I am passing around a MultiVector, there's currently no way to prevent someone from changing values even if the MultiVector is declared const?

That's correct.

> Also - the const model for Tpetra is not the same as a View (which can block changing values with `View<const double,...>`) on one end and `std::vector` (can block with `const std::vector<...>`) on the other end, but is something in between?

That's correct.

**Comment by rppawlo** [comment]
Thanks @mhoemmen . One last question before closing - what is the long term plan? Will Tpetra object const model morph into the complete kokkos view model or will they stay put as is?

**Comment by mhoemmen** [comment]
My personal view is that neither model (containers or views) is the correct model for Tpetra objects, STK fields, or any large distributed data structure.  If I remember right, @ibaned would prefer to handle more of these large objects by `unique_ptr`; I'm not opposed to that.  `withLocalAccess` (see Tpetra examples) reflects my opinions about the best way to access a large distributed object's local data.

**Comment by ibaned** [comment]
Since I was mentioned, I'll just say that what I've done in my most recent code is containers with "container" (`std::vector`) semantics, but kernels never capture a copy of or reference to the container, they only capture "iterator"s or pointers. I usually implement distributed data structures as local data structures with extra functions that do distributed operations.

**Comment by mhoemmen** [comment]
@ibaned Thanks for explaining!  I also like the idea that nothing can capture an owning reference to the local data.  Tpetra users have a bad habit of extracting owning Kokkos::View references and stashing them away, then forgetting to update them if their parent Tpetra object changes (e.g., due to the mesh changing).

**Comment by mhoemmen** [comment]
Looks like this question has been answered -- please feel free to reopen if not.  Thanks!
