### ISSUE TITLE
Tech-X: Warnings as errors patches

### ISSUE THREAD

**Issue by bddavid** [trilinos/Trilinos#66]
<h3> Brief: </h3>

<p>Patches generated by Tech-X need to be applied and merged when possible.  This work was completed at the end of September, 2015.</p>

<p>The master repo will be forked and a series of branches will be created by package with the associated patch (as described in trilinosWarningsList.pdf) applied.  A pull request will then be issued for each branch.  Once a pull request has been accepted then the branch may be removed from the repo. </p>

<p>A summary of the work is given by trilinosWarningsList.pdf (see attached). </p>

<h5>Packages affected include:</h5>

<ul> 
<li> @trilinos/epetra </li>
<li> @trilinos/amesos </li>
<li> @trilinos/didasko</li>
<li> @trilinos/fei </li>
<li> @trilinos/intrepid </li>
<li> @trilinos/phalanx </li>
<li> @trilinos/panzer </li>
<li> @trilinos/pliris </li>
<li> @trilinos/muelu </li>
<li> @trilinos/seacas </li>
<li> @trilinos/shylu </li>
</ul>

<h5>To-do</h5>

_Pull requests:_
- [x]  Create Pull request for 0001-Epetra-Package-Warning-Fixes
- [x]  Create Pull request for 0002-Amesos-Package-Warning-Fixes<br/>
  ~~Create Pull request for 0003-Didasko-Package-Warning-Fixes~~
- [x]  Create Pull request for 0006-Mesquite-Package-Warning-Fixes
- [x]  Create Pull request for 0007-Phalanx-Package-Warning-Fixes<br/>
  ~~Create Pull request for 0008-Panzer-Package-Warning-Fixes~~
- [x]  Create Pull request for 0009-Pliris-Package-Warning-Fixes
- [x]  Create Pull request for 0010-Pamgen-Package-Warning-Fixes

_Merges:_
- [ ] [Review and merge pull request for Epetra Warnings patches](67)
- [x] [Review and merge pull request for Amesos Warnings patches](72)<br/>
  ~~Review and merge pull request for Didasko Warnings patches~~
- [ ] [Review and merge pull request for Mesquite Warnings patches](https://github.com/trilinos/mesquite/pull/1)
- [ ] [Review and merge pull request for Phalanx Warnings patches](71)<br/>
  ~~Review and merge pull request for Panzer Warnings patches~~
- [ ] [Review and merge pull request for Pliris Warnings patches](73)
- [ ] [Review and merge pull request for Pamgen Warnings patches](69)
##### Notes:

_\- FEI and Intrepid built without warnings or errors._
*

<h3> Detailed summary of work product: </h3>

[trilinosWarningsList.pdf](https://github.com/trilinos/Trilinos/files/77685/trilinosWarningsList.pdf)

**Comment by jwillenbring** [comment]
I want to make sure I am understanding what you are saying. Please create the branches you mention on a fork of the repository, not the main Trilinos repository. Then we don't need to try to delete branches off the main repo later.

**Comment by bddavid** [comment]
@jwillenbring I should have been more clear. The branches will be added to a fork of the repo.

**Comment by ZaherHa** [comment]
i have a warning in IDE0006 when i lunch the Xamarin App haw i can fix it??

**Comment by aprokop** [comment]
@ZaherHa Please create a new issue for it. Please provide the full warning message and the configuration script that you used.

**Comment by ZaherHa** [comment]
it is all here
[Xamarin.Android.Build.Tasks] IDE0006 warning on File -> New CrossPla…
…tform App (#730)

Context: https://bugzilla.xamarin.com/show_bug.cgi?id=58448

Based on feedback from the VS team we now know that library
projects are NEVER built as part of a DesignTimeBuild :(.

Furthermore, if ANY error occurs during the DesignTimeBuild
VS throws a wobbly and does not initialise the project
correctly. The suggestion is to use `ContinueOnError` to
ignore the errors and allow the build to complete.

**Comment by ZaherHa** [comment]
it is have issue here but i did not find the solve

**Comment by ibaned** [comment]
@ZaherHa this is the Trilinos GitHub page. Your issue doesn't seem to have anything to do with Trilinos?

**Comment by aprokop** [comment]
@ZaherHa This is not a Trilinos issue from what I can tell.

**Comment by ZaherHa** [comment]
so What i must to do now to solve this warning??

**Comment by aprokop** [comment]
@ZaherHa Post the issue [here](https://github.com/xamarin/xamarin-android).

**Comment by ZaherHa** [comment]
Ok thanks

**Comment by aprokop** [comment]
@ibaned Can we purge the history on this issue?

**Comment by ibaned** [comment]
There are "Delete comment" buttons on the upper right of each comment (at least in my view).

**Comment by aprokop** [comment]
I'm talking about "censoring" aspects of rewriting history. What's Trilinos policy on that?

**Comment by ibaned** [comment]
> I'm talking about "censoring" aspects of rewriting history. What's Trilinos policy on that?

Beats me. @jwillenbring @bmpersc ?
