### ISSUE TITLE
Tpetra::CrsGraph: 2- or 3-level thread parallelization of sortAllIndices & mergeAllIndices

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#660]
@trilinos/tpetra Do a 2-level or 3-level thread parallelization of Tpetra::CrsGraph methods sortAllIndices and mergeAllIndices.

This is a "story" because this may call for a thread-parallel segmented sort, or segmented sort-and-merge.

Update (12 Nov 2016): I rewrote this issue to reflect a multiple-step process.  See #832.  The first step will be a single-level thread parallelization.  The second step (likely done at the same time) will be to remove any implicit UVM assumptions that the methods may make.  The third step would be this issue, a 2-level or 3-level parallelization that relies on a segmented sort (which does not exist yet; see #662).

**Comment by srajama1** [comment]
thread-parallels (segmented) sort will be useful in many other contexts as well. Might be good to discuss in KokkosKernels context.

**Comment by mhoemmen** [comment]
> thread-parallels (segmented) sort will be useful in many other contexts as well. Might be good to discuss in KokkosKernels context.

I'll break this into a separate issue.

**Comment by crtrott** [comment]
This might be something for Kokkos Algorithms.
