### ISSUE TITLE
Framework: https://docs.trilinos.org/files/TrilinosBuildReference.html missing

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#6601]
@trilinos/framework 

The link "Trilinos CMake Reference (html, pdf) – Instructions for building Trilinos 10.0 and later." from the page:

* https://trilinos.github.io/documentation.html

that takes you to

* https://docs.trilinos.org/files/TrilinosBuildReference.html

it says:

> This page no longer exists
You might be trying to find documentation for a version of Trilinos that is no longer supported.
>
> In many cases, it is possible to find the current version of a documentation page by simply replacing /r*.*/ in the url address bar with /dev/ for the development version of the documentation, or /latest-release/ for the latest release version.

**Comment by bartlettroscoe** [comment]
I think this is kind of a serious defect because now no one can get to the Trilinos configure, build and test documentation.

**Comment by jjellio** [comment]
You don't think this is a serious defect... it **is** a serious defect! We can skip the thinking part!

I use that reference all the time to dig up obscure variables and options.

**Comment by jwillenbring** [comment]
I think I know what is going on here. I am at a meeting all week and need to prep for 3 talks, but I will look into this ASAP.

**Comment by william76** [comment]
@jwillenbring Just doing a quick pass through things and it looks like the HTML link for _Trilinos CMake Reference_ is still broken. The PDF link does load a document but I don't know how current it is.

I noticed the same link is also broken on https://trilinos.github.io/getting_started.html as well.

**Comment by bartlettroscoe** [comment]
Looks like someone finally fixed this:

* https://docs.trilinos.org/files/TrilinosBuildReference.html

Closing as complete.
