### ISSUE TITLE
PyTrilinos: Get SWIG 4.0 to Work

### ISSUE THREAD

**Issue by pyt-viper** [trilinos/Trilinos#6607]
## Enhancement
@trilinos/pytrilinos 

If a user tries to build PyTrilinos using SWIG 4.0, it results in a build error.  Three issues and one opportunity have been identified:

- [x]  The `SWIGEMPTYHACK` macro is no longer defined
- [x]  Logic produced by SWIG 4.0 wrapping arguments that are shared pointers uses the `operator bool` operator.  The way `Teuchos::RCP` arguments are wrapped in PyTrilinos, this operator would have to be supported by `Teuchos::RCP` to work.
- [x]  Code that is supposed to be inserted into the wrappers via the `%fragment()` directive is not getting inserted.  This looks like a bug in SWIG 4.0.1, but it might just be a different behavior that needs to be addressed.
- [x]  There is also an opportunity to leverage SWIG's new support converting doxygen comments to Python doctrings.  There is a somewhat ad-hoc system in place for doing this, but a couple of issues have popped up recently, so this more direct approach might be better.

**Comment by pyt-viper** [comment]
@mhoemmen For the last item of this enhancement, I added `-doxygen` to the command line options when I call SWIG.  It appears that the current version of SWIG (4.0.1) can't process `enum`s that are formatted as

    enum myEnum {
        enum1    ///< Doxygen comment for enum1
        ,enum2   ///< Doxygen comment for enum2
        ,enum3   ///< Doxygen comment for enum3
    } 

SWIG reports an error at the first comma.  I think this pattern is repeated many places in Trilinos for many different types of argument lists, but the SWIG bug only appears for `enum`s.  As a result, and pretty fortunately, the only files SWIG encounters in PyTrilinos with this problem are `Teuchos_ParameterList.hpp` and `EpetraExt_ModelEvaluator.h`.  So I propose the following:

1. As a quick workaround, modify these two files to move commas immediately after the preceding enumeration, and
1. Submit a bug report to SWIG

Do you have any issues with this?

**Comment by mhoemmen** [comment]
@pyt-viper I have no problem with this -- thanks!
