### ISSUE TITLE
Ifpack2:  are preconditioner clone methods deprecated?

### ISSUE THREAD

**Issue by kddevin** [trilinos/Trilinos#6614]
## Question
@trilinos/ifpack2 

The deprecation document says Ifpack2 clone methods are deprecated.  Yet I see them unflagged in Ifpack2's Chebyshev, RILUK, and Factory.

https://github.com/trilinos/Trilinos/wiki/Trilinos_v12_code_deprecation.pdf

Should these methods be removed from Ifpack2?  Or are they somehow different from the clone methods listed in the document?

We have someone to help remove deprecated code from Trilinos, so we're sorting out what needs to go.

Thanks.

@jeforster

**Comment by csiefer2** [comment]
I can't think of a reason to keep them...

**Comment by kddevin** [comment]
Thanks.  I will ask @jeforster to remove them. #6655
