### ISSUE TITLE
Sacado:  Change implementation of derivatives of hyperbolic functions to avoid FPE

### ISSUE THREAD

**Issue by mperego** [trilinos/Trilinos#6632]
## Enhancement
@trilinos/sacado 

Change the algorithm to compute the derivative of tanh and coth functions.

Current algorithm:
tanh(x)' = 1/cosh^2(x)
coth(x)' = -1/sinh^2(x)

Issue: for large x, sinh(x) and coth(x) can be Inf, triggering FPE errors.

Proposed algorithm:
tanh(x)' = 1-tanh^2(x)
coth(x)' = 1-coth^2(x)

Thanks.

**Comment by mhoemmen** [comment]
@mperego I edited your post to get the group tag right.

**Comment by etphipp** [comment]
Done in PR #6645.  Note Sacado currently doesn't implement coth(x), so I just did this for tanh(x).

**Comment by etphipp** [comment]
PR #6645 has been merged, so closing.
