### ISSUE TITLE
Adelus: Create new dense linear solver package

### ISSUE THREAD

**Issue by srajama1** [trilinos/Trilinos#6639]
## Enhancement

Create a new package Adelus for the dense linear solver capabilities.

1) Commit package to Trilinos
2) Add package to PR testing
3) Add package to ATDM builds

@vqd8a : I am not able to assign this to you.

**Comment by vqd8a** [comment]
Thanks @srajama1. Can you add me as a Trilinos developer?

**Comment by bartlettroscoe** [comment]
Actually, I think the initial work here is for the @trilinos/framework team to get added into the PR builds.

**Comment by bartlettroscoe** [comment]
@srajama1, you will need to coordinated with @jwillenbring to get this prioritized with the @trilinos/framework team for the initial part of this.  Once this gets merged to 'develop', then you can assign to me to add to the ATDM Trilinos builds.

**Comment by srajama1** [comment]
@jwillenbring : Can you please add @vqd8a as a Trilinos developer so he can commit the package ? Assigning it to you first, please reassign to @vqd8a for the second step.

**Comment by bartlettroscoe** [comment]
I guess there is zero harm in committing this to Trilinos 'develop' initially as an Experimental (EX) package to start with.  (TriBITS ensures that will cause zero harm.)

**Comment by jwillenbring** [comment]
> @jwillenbring : Can you please add @vqd8a as a Trilinos developer so he can commit the package ? 

Done. More accurately, I sent an invitation for @vqd8a to accept. I cannot add him directly. Also, it is not necessary to be a Trilinos developer to issue a PR to add a package. However, it is useful for other reasons.

**Comment by vqd8a** [comment]
Thanks @jwillenbring. The copyright assertion is in process.

**Comment by srajama1** [comment]
@jwillenbring Thank you ! I wasn't able to assign @vqd8a before to this issue. I assume that list gets populated from the developers somehow.

An aside, @vqd8a is the lead of this new package and an active Kokkos Kernels developer. It is correct for him to be in the developers list.

**Comment by srajama1** [comment]
@vqd8a : Now that copyright is in let us add it to the files and create a new package. Once you do that, you can assign this to @bartlettroscoe for adding Adelus to ATDM testing.

**Comment by bartlettroscoe** [comment]
> Once you do that, you can assign this to @bartlettroscoe for adding Adelus to ATDM testing.

@vqd8a and @srajama1, the way the ATDM Trilinos builds are currently set up using the "Black Listing" approach, the if the new package is added as a "Primary Tested" package (i.e. listed as "PT" in the `Trilinos/PackagesList.cmake` file), then it will automatically get picked up in the ATDM Trilinos builds.  I will create a single GitHub issue for all of the failures once the new package shows up on CDash.

**Comment by srajama1** [comment]
This should not be closed.

@jwillenbring @vqd8a : I believe this is still relevant. 

Adelus is used by our production applications. It should be tested in PR builds and other builds (dev-> master), etc.

**Comment by srajama1** [comment]
I removed the MARKED_FOR_CLOSURE label. I am guessing that is the correct process.
