### ISSUE TITLE
Tpetra::CrsMatrix::unpackAndCombine, non-static-graph path, allocates too much memory

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#6663]
## Bug Report
@trilinos/tpetra  

### Description

This is a narrowing-down of #6648.  @shardest and I ran an 8-MPI-process Sierra SD test with Trilinos master in a debugger, and used `top` to look at per-process memory increases.   We noticed that `copyAndPermute` showed a modest increase in memory use per process, but `unpackAndCombine` showed a greater than 2x increase.  This prompted me to take a closer look at `unpackAndCombine`.

Use case: {Ex,Im}port from a full CrsMatrix into an empty CrsMatrix.  This means that the target CrsMatrix owns its graph; this is the case where `isStaticGraph()` is `false`.

1. The target CrsMatrix owns its graph, so `unpackAndCombine` [calls `computeCrsPadding` and `applyCrsPadding`](https://github.com/trilinos/Trilinos/blob/496de8209c83846169d0651de19aaa24d10a2ac6/packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp#L7361).
2. `applyCrsPadding` [makes deep copies of the matrix's values](https://github.com/trilinos/Trilinos/blob/496de8209c83846169d0651de19aaa24d10a2ac6/packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp#L6221) and column indices, as long as `padding.size() != 0`.
3. `applyCrsPadding` calls `padCrsArrays`, which again [makes deep copies of the matrix's indices and values](https://github.com/trilinos/Trilinos/blob/496de8209c83846169d0651de19aaa24d10a2ac6/packages/tpetra/core/src/Tpetra_Details_crsUtils.hpp#L119).
4. The first copy only goes away when `applyCrsPadding` returns, so at some point, we have 2x extra copies (3x total) of the matrix per process.

Repacking the matrix does require one copy.  However, I think we can fix it so it only needs the one copy, not an extra one.

### Steps to Reproduce

I'll send instructions for running the Sierra SD test over e-mail, but I determined the above 3x copy issue by inspection.  We'll need to verify by tracing execution in a debugger.

**Comment by mhoemmen** [comment]
We tried two different work-arounds, but both threw exceptions, for reasons that are harder to fix than just fixing the original SD use case.

Summary:
1. `importAndFillCompleteCrsMatrix` failed, and it wouldn't work anyway in this case.
2. Avoiding the "non-static-graph" code path by making the graphs separately first also failed.

We first tried `importAndFillCompleteCrsMatrix`, but it failed with an exception message.  We then realized it wouldn't work anyway, since the original code sets the target CrsMatrix's column Map explicitly.  The "domain Import" argument of `importAndFillCompleteCrsMatrix` is from the source's domain Map to the target's domain Map; it's not, in general suitable for the target's domain-to-column Import.  Neither the 5-argument nor the 6-argument version of `importAndFillCompleteCrsMatrix` worked.

We then tried avoiding the "non-static-graph" code path of `CrsMatrix::doImport`.  We did so as follows:
  a. Create the output CrsGraph as an empty CrsGraph.
  b. Import from the input matrix's CrsGraph to this empty CrsGraph.
  c. Call fillComplete on the output CrsGraph.
  d. Create the output CrsMatrix from the output CrsGraph (so that the matrix has a "static" graph -- `isStaticGraph()` is `true`).
  e. Import from the input matrix to the output matrix.
  f. Return the output matrix.

The code looks like this:
```cpp
CrsMatrix makeTheMatrix (
  const CrsMatrix& inputMatrix,
  RCP<const Map> outputRowMap)
{
  // Make output matrix’s graph
  auto inputGraph = inputMatrix.getCrsGraph();
  assert(! inputGraph.is_null());
  auto outputColMap = outputRowMap;
  RCP<CrsGraph> outputGraph(new CrsGraph(outputRowMap, outputColMap, 0));
  Import importer(inputGraph.getRowMap(), outputRowMap);
  outputGraph->doImport(*inputGraph, importer, Tpetra::INSERT); 
  auto domainMap = inputGraph->getRowMap();
  auto rangeMap = inputGraph->getRowMap();
  outputGraph->fillComplete(domainMap, rangeMap);
 
  // Make output matrix itself, from the output graph
  CrsMatrix outputMatrix(outputGraph);
  outputMatrix.doImport(inputMatrix, importer, Tpetra::INSERT);
  outputMatrix.fillComplete(); // this will use outputGraph’s domain & range Maps
  return outputMatrix;
}
```
However, this failed, with errors that look like this (and are repeated on all MPI processes of the 8-process job):
```
Runtime error on processor 2!
.../Trilinos/packages/tpetra/core/src/Tpetra_CrsGraph_def.hpp:3608:
 
Throw number = 1
 
Throw test that evaluated to true: (makeIndicesLocalResult.first != 0)
 
Tpetra::CrsGraph<int, long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::fillComplete: (Process 2) When converting column indices from global to local, we encountered 240930 indices that does not live in the column Map on this process.
```
I think the problem is that CrsMatrix non-static doTransfer does column Map filtering (it ignores input column indices that aren't in the target column Map), but CrsGraph doTransfer does _not_ do column Map filtering.

**Comment by mhoemmen** [comment]
@shardest build SD with [my branch of Trilinos](https://github.com/mhoemmen/Trilinos/tree/Tpetra-Crs-memory-use), that adds extensive debug output for `Kokkos::View` allocations, if you set the `TPETRA_VERBOSE` environment variable to `CrsMatrix` or 1.  We were able to capture just the output relating to the function that caused the test to fail due to running above its memory limits.

I will send out the log file, but the essence is that not only are we allocating more duplicates, the unpacked CrsMatrix local allocations are _much_ larger than the packed (final) allocations.  My guess is that `unpackAndCombine` is overestimating the required target matrix allocations, possibly because there are many duplicate column indices that could be merged.  This matters now because DynamicProfile is gone, so we're paying for those overestimates up front.

The least invasive fix would be for `unpackAndCombine` to make two passes through the target. The first pass would get accurate counts, including the possibility of merges.  That is, it would look through each row of the received data for column indices that are not already in the corresponding target matrix row.  Then, `unpackAndCombine` would reallocate if needed, and the second pass would actually do the merging and combining of values.

The next step would be to remove all memory duplication, by combining the `copyAndPermute` and `unpackAndCombine` phases, so that the target matrix would not need redundant allocations or repacking.  That should actually make Tpetra use less memory than before the removal of DynamicProfile.

**Comment by mhoemmen** [comment]
Here's an except of the log for `outputMatrix`'s `fillComplete` call:
```
Proc 3: Tpetra::CrsMatrix::fillLocalGraphAndMatrix: Unpacked 1-D storage: numEnt=4054086, allocSize=36041016
Proc 2: Tpetra::CrsMatrix::fillLocalGraphAndMatrix: Unpacked 1-D storage: numEnt=4513113, allocSize=44753640
Proc 7: Tpetra::CrsMatrix::fillLocalGraphAndMatrix: Unpacked 1-D storage: numEnt=4397067, allocSize=39004551
Proc 5: Tpetra::CrsMatrix::fillLocalGraphAndMatrix: Unpacked 1-D storage: numEnt=4020732, allocSize=43670004
Proc 4: Tpetra::CrsMatrix::fillLocalGraphAndMatrix: Unpacked 1-D storage: numEnt=6452379, allocSize=68234100
Proc 1: Tpetra::CrsMatrix::fillLocalGraphAndMatrix: Unpacked 1-D storage: numEnt=6509457, allocSize=73271166
Proc 6: Tpetra::CrsMatrix::fillLocalGraphAndMatrix: Unpacked 1-D storage: numEnt=6425325, allocSize=63402054
Proc 0: Tpetra::CrsMatrix::fillLocalGraphAndMatrix: Unpacked 1-D storage: numEnt=7051131, allocSize=82674678
```
Notice how much bigger the unpacked (`allocSize`) number of entries is vs. packed (`numEnt`).  When previous routines duplicate storage, they are duplicated the unpacked number of entries, not the packed number.

**Comment by mhoemmen** [comment]
@tjfulle @kddevin Search in the log I sent out for "73271166" (no quotes).  You'll find this:
```
Proc 1: Tpetra::...::pad_crs_arrays: Allocate indices_new: 73271166
Proc 1: Tpetra::...::pad_crs_arrays: Allocate values_new: 73271166
Kokkos::HostSpace::allocate[ STD_MALLOC ]( 586169456 ) FAILED NULL
```
The allocation fails due to the memory limit.  586169456 (500 MB!) is `sizeof(double)` times 73271166.  If you generate the log from running with 10x memory limit (as described in my e-mail from last night), you'll see that this allocation succeeds.
```
Proc 1: Tpetra::...::pad_crs_arrays: Allocate indices_new: 73271166
Proc 1: Tpetra::...::pad_crs_arrays: Allocate values_new: 73271166
...
Proc 1: Tpetra::...::pad_crs_arrays: Assign to indices: old=2756394, new=73271166
```
If you look further in that log for "73271166", you'll see two things:

  1. It goes into `makeIndicesLocal`, meaning that despite the target matrix having a column Map, it gets filled with global indices, resulting in a 2x memory increase.
  2. `fillLocalGraphAndMatrix` says that the allocation has size 73271166 entries, but the actual number of local entries in the matrix is 6509457.  That's over 11 times!

The latter suggests that the most important issue is not the 2x storage duplication, but the large overallocation.  My guess is that overallocation comes from counting incoming duplicate entries as distinct entries, rather than merging them in as they come.  Fixing that will make the biggest impact.

**Comment by tjfulle** [comment]
Thanks @mhoemmen.  I'm not recalling exactly, but we discussed the issue of duplicating entries wrt to `insert*Indices`.  I believe that was part of the motivation for having `CrsMatrix` use its `CrsGraph` do insertions (using the callback mechanism), because the graph could handle the issue of duplicate entries more transparently.   In this case, perhaps should we do some sort of "merged insertion" for preexisiting indices followed by the resizing for non-existent?

**Comment by mhoemmen** [comment]
> My guess is that overallocation comes from counting incoming duplicate entries as distinct entries, rather than merging them in as they come.

The reason this didn't happen before is likely because `CrsMatrix::insert*` with DynamicProfile merged.  Since we only have StaticProfile now, we need to precount the allocation with merging in mind.  That means we need to inspect the incoming data and search for column indices that also appear in the target matrix in that row.  It would be hard do that for both copies and imports, since that would call for simulating a three-way merge without actually merging.  Thus, a logical first fix would be to reallocate twice, once for copies and once for imports.

If we need to optimize this further, note that `DistObject::unpackAndCombine` permits implementations to overwrite the `imports` array.  Thus, we could use `imports` as scratch.

**Comment by mhoemmen** [comment]
@tjfulle wrote:
> In this case, perhaps should we do some sort of "merged insertion" for preexisting indices followed by the resizing for non-existent?

Something like that.  Here's a sketch of the first pass:

  1. copyAndPermute merges incoming entries with column indices that are already in the target graph, and counts incoming entries for each row that aren't already there.
  2. unpackAndCombine does the same, adding to the existing counts.
  3. Allocate target matrix.
  4. Make another copyAndPermute pass for entries that aren't already in the target.
  5. Make another unpackAndCombine pass for entries that aren't already in the target.

The missing optimization is for entries that unpackAndCombine didn't need to count, because copyAndPermute would have added them.  We could deal with those without additional allocations by searching the source matrix for entries in the `imports` array that copyAndPermute would have inserted, and then overwriting the `imports` array to mask them out.

**Comment by mhoemmen** [comment]
@tjfulle There might be a way to do this without needing to reimplement `DistObject::doTransferNew` for CrsMatrix.  We could instead add the following new protected virtual methods to DistObject, with default implementations that do nothing:

  - `copyAndPermuteCount`
  - `unpackAndCombineCount`

Then, we would change the generic implementation of `DistObject::doTransferNew` to use these methods, if `constantNumberOfPackets()` is zero.  It's zero for classes that may need to pack a nonconstant number of packets per LID; that includes CrsGraph, CrsMatrix, and BlockCrsMatrix.  Classes that always packet a constant number of packets per LID are MultiVector and Vector.

**Comment by nate945** [comment]
Thanks, I definitely don't understand the details here, but in general a count then fill approach sounds like a great path.  For SD use of these matrix formations memory is at an absolute premium while the runtime of the import operation is negligible compared to the overal analysis runtime.

**Comment by mhoemmen** [comment]
@nate945 @shardest @crdohrm I just merged PR https://github.com/trilinos/Trilinos/pull/6831 into develop.  It's not in master yet; the automatic develop-to-master PR should take care of that tomorrow.  I tested those changes with SD and got the test to complete and pass with `testrun`, respecting the per-process memory-limit.  It took only 343s even in a debug build, so I feel pretty confident that the tests will pass now.

Standard procedure is to let GitHub close the issue automatically, once the commit that says `Fix #6663` merges into master.  Once this happens, we can always reopen the issue if the problem hasn't gone away.  Thanks all for your help diagnosing and fixing this issue! :-D

**Comment by nate945** [comment]
Mark,

Great, thanks!  We will evaluate switching back to the Tpetra calls after we get the current Trilinos integration and upcoming Sierra release complete.  Hopefully we could do this in the first sprint or two of the next release cycle.  I'll put something on the SD backlog to remind to revisit this.

-Nate

**Comment by mhoemmen** [comment]
@nate945 Instead of switching back to how you did it before @crdohrm 's work-around, we had talked about adopting the work-around in Tpetra itself.  It's a straightforward extension of the existing function `{im,ex}portAndFillComplete`.  I think it would make more sense to do that, since the interface would be more idiomatic C++ (vs. creating an empty CrsMatrix as the target of an `{Im,Ex}port`) and it would expose more optimization hints.

**Comment by nate945** [comment]
@mhoemmen OK, that sounds good.  We can follow up on that after the release, also wanted to follow up on SD critical test cases in Tpetra so that would be good way to hit both those fronts.

**Comment by mhoemmen** [comment]
@nate945 I'm tempted to just dump the matrix from that one SD test, and use it as a correctness test.  In many cases, I was able to make SD hang or fail (I'm not even talking about the memory limit) with a set of changes that didn't make Trilinos' tests fail.
