### ISSUE TITLE
Almost all packages: How to compile/link every package separeately?

### ISSUE THREAD

**Issue by issabass** [trilinos/Trilinos#6664]
## Question
Hello team Trilinos,
I've just started learning Trilinos. I followed the tuto to compile and install the packages into a local directory. But I've issue as to how link the needed libraries.
To avoid the libraries overlapping, I'd like to have one of you guys providing me a mwe based on my setting as to how to make the right cmake set up:
*My_Trilinos_DIR_INSTALL= /home/issaq/mydev/DTrilino
*My_Trilinos_DIR_APPS= /home/issaq/myapps/dtrilino
To be precise, I want a small cmake file that can compile and link the tuto example like the one in https://github.com/trilinos/Trilinos_tutorial/wiki/KokkosTutorial01 . I just want to use every package separately...
Thank you much

**Comment by mhoemmen** [comment]
Check past Trilinos tutorials for instructions on how to link against Trilinos with a CMake project.

**Comment by jhux2** [comment]
@issabass Check out the tutorials at https://github.com/kokkos/kokkos-tutorials.  Is this what you're after?

**Comment by issabass** [comment]
Many thanks, indeed!

**Comment by jhux2** [comment]
Glad this helped.  If you feel this answered your question, please close this issue.
