### ISSUE TITLE
Moertel: Comparing signed and unsigned variables breaks auto-tester

### ISSUE THREAD

**Issue by lucbv** [trilinos/Trilinos#6698]
## Bug Report
@kliegeois 

### Description
Simply need to change some `std::size_t` into `int`
Kim, if you could run with -Werror on when you make changes that would be nice ; )

**Comment by lucbv** [comment]
This seem to be resolved now so I'm closing the issue

**Comment by kliegeois** [comment]
Sorry for those signed-unsigned comparisons @lucbv !
And sorry for not seeing that issue earlier.
