### ISSUE TITLE
Teuchos:  Preferred way of printing docstrings

### ISSUE THREAD

**Issue by Sbte** [trilinos/Trilinos#6702]
## Question
@trilinos/teuchos

What is the preferred way of printing docstrings from a parameter list?

For our application, we want to print all parameters that can be set, their default values, and their docstrings. This so we have the documentation of the parameters all in one place. I'm confused as to what would be the right way to obtain those.

I expected `validateParameters` or `validateParametersAndSetDefaults` or something alike to set the docstrings, but it seems like only `setParameters` sets it. If I look at for instance `Belos::BlockGmresSolMgr`, I see that it has a method `getValidParameters` that sets the docstrings. Would the "right" way be to implement `getValidParameters` for every class and recursively call `getValidParameters` + `setParameters` for any data members? And then when we want to print them, apparently I have to do this?

```
Teuchos::ParameterList::PrintOptions po;
po.showDoc(true);

Teuchos::RCP<const Teuchos::ParameterList> pars = c.getValidParameters();
pars.print(std::cout, po);
```

Also, why are these `getValidParameters` methods not static so you can get the parameters before you construct the class?

**Comment by jhux2** [comment]
@trilinos/teuchos

**Comment by bartlettroscoe** [comment]
@Sbte, yes you want to implement getValidParameter().  Look at an example of this in:

*  https://docs.trilinos.org/dev/packages/stratimikos/doc/html/classStratimikos_1_1DefaultLinearSolverBuilder.html#details

And you can expand out the list of "Valid Parameters" shown there.

I did not write all of the code that does that and I am not sure that documentation is being kept up-to-date (by cron jobs that did that likely died a long time ago) but you should be able to reverse engineer that.
