### ISSUE TITLE
Trilinos PR testing should not run any tests for "Python" builds for cmake/std/atdm/ changes

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#6723]
@trilinos/framework 

As per our prior agreement and the logic in:

* https://github.com/trilinos/Trilinos/blob/develop/commonTools/framework/ProjectCiFileChangeLogic.py

changes to files under Trilinos/cmake/std/atdm/ and other such special locations should not trigger any testing in Trilinos PR builds.

However, it would appear the the "Python" PR builds violate this described in https://github.com/trilinos/Trilinos/issues/3276#issuecomment-581539629 and shown in https://github.com/trilinos/Trilinos/pull/6719#issuecomment-581525965.

**Comment by jwillenbring** [comment]
Given the new consolidated testing system that is being developed, I am going to close this. It isn't worth fixing at this point.
