### ISSUE TITLE
Tpetra::Details::Behavior::debug("CrsGraph") ignores default

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#6727]
## Bug Report
@trilinos/tpetra 

### Description

`Tpetra::Details::Behavior::debug("CrsGraph")` always defaults to `false`, even if `TPETRA_DEBUG` is 1 or `Tpetra::Details::Behavior::debug()` is true.

### Steps to Reproduce

Run in a debug build.  I'll write a test.

**Comment by mhoemmen** [comment]
@tjfulle I'm looking at `tpetra/core/test/Behavior/Behavior_Named.cpp`.  That expresses the intent that if you set `TPETRA_DEBUG=Foo`, debug for anything else is false.  I think I get the reason: you want fine-grained control for opting into the expensive thing.  Thus, I'll call this "not an issue," and just fix the CrsGraph BadGIDs test to use `debug("CrsGraph")` to decide whether to run.

**Comment by tjfulle** [comment]
@mhoemmen , yep that was the original reason for wanting "Named" debug behavior.

There is also a way to programmatically turn on/off debug:

```c++
Tpetra::Details::Behavior::disable_verbose_behavior();
// do some quiet stuff
Tpetra::Details::Behavior::enable_verbose_behavior():
// do some noisy stuff
```

**Comment by mhoemmen** [comment]
@tjfulle convinced me that this is not a bug.  I will change the CrsGraph unit test (BadGIDs) to use `Behavior::debug("CrsGraph")` to decide whether to run, rather than using `HAVE_TPETRA_DEBUG`.

**Comment by tjfulle** [comment]
@mhoemmen if you do TPETRA_DEBUG=ON then all debug statements should run.  If TPETRA_DEBUG=name1,name2,...,namen then only the names should run.  The separator might be ; and not ,
