### ISSUE TITLE
STK install error

### ISSUE THREAD

**Issue by ikalash** [trilinos/Trilinos#6728]
It looks like we have a STK install error in some of the Albany nightlies: 
```
-- Up-to-date: /home/ikalash/nightlyAlbanyTests/Results/Trilinos/build/install/include/Makefile.export.STKUtil
-- Up-to-date: /home/ikalash/nightlyAlbanyTests/Results/Trilinos/build/install/include/stk_util/stk_config.h
-- Up-to-date: /home/ikalash/nightlyAlbanyTests/Results/Trilinos/build/install/include/stk_util/stk_kokkos_macros.h
CMake Error at packages/stk/stk_util/stk_util/cmake_install.cmake:64 (file):
  file INSTALL cannot find
  "/home/ikalash/nightlyAlbanyTests/Results/Trilinos/build/packages/stk/stk_util/stk_util/STK_Trilinos_config.h":
  No such file or directory.
Call Stack (most recent call first):
  packages/stk/stk_util/cmake_install.cmake:69 (include)
  packages/stk/cmake_install.cmake:62 (include)
  cmake_install.cmake:122 (include)
make: *** [Makefile:74: install] Error 1
```
This happens on my Fedora 31 workstation, not other platforms.  The machine was down since 1/28/2020 and was just brought back up today, so it may have started anytime b/w then and now.

**Comment by alanw0** [comment]
stk was updated about 11am this morning. I'll look into this error.

**Comment by ikalash** [comment]
That could actually be why it showed up only on my machine - when I brought it back up just now, I cloned from scratch, whereas the nightlies would have cloned from scratch early in the morning (around 12-1AM); so if something got pushed at 11, it wouldn't have shown up in the nightlies yet.  Thanks for looking at it!

**Comment by alanw0** [comment]
yes. it looks like we had a CMakeLists.txt file that had a fix in sierra that was missed in this morning's snapshot into trilinos. I have a pull-request in now (#6729) that will fix this.

**Comment by ikalash** [comment]
Great, thanks for doing that so fast!  I'll check tomorrow morning that things are fixed (provided the PR makes it in by the time the nightlies run).

**Comment by ikalash** [comment]
I can confirm that this issue has been resolved.  Thanks @alanw0 !

**Comment by alanw0** [comment]
@ikalash ok glad to hear it's fixed.
