### ISSUE TITLE
Non-CUDA Clang builds fail in Kokkos

### ISSUE THREAD

**Issue by jhux2** [trilinos/Trilinos#6734]
I just did fresh pull of Trilinos develop, SHA 44f13cb14.  An ATDM build on the CEE lan that previously worked just fine is now failing with this error:

```
[2/2834] Building CXX object packages/kokkos/core/src/CMakeFiles/kokkoscore.dir/impl/Kokkos_CPUDiscovery.cpp.o
FAILED: packages/kokkos/core/src/CMakeFiles/kokkoscore.dir/impl/Kokkos_CPUDiscovery.cpp.o 
/projects/sems/install/rhel7-x86_64/sems/compiler/clang/7.0.1/openmpi/1.10.1/bin/mpicxx   -I. -Ipackages/kokkos/core/src -I/scratch/jhu/trilinos/Trilinos/packages/kokkos/core/src -Ipackages/kokkos -std=c++11 -x cuda   -O2 -g -DNDEBUG -MD -MT packages/kokkos/core/src/CMakeFiles/kokkoscore.dir/impl/Kokkos_CPUDiscovery.cpp.o -MF packages/kokkos/core/src/CMakeFiles/kokkoscore.dir/impl/Kokkos_CPUDiscovery.cpp.o.d -o packages/kokkos/core/src/CMakeFiles/kokkoscore.dir/impl/Kokkos_CPUDiscovery.cpp.o -c /scratch/jhu/trilinos/Trilinos/packages/kokkos/core/src/impl/Kokkos_CPUDiscovery.cpp
clang-7: error: cannot find libdevice for sm_20. Provide path to different CUDA installation via --cuda-path, or pass -nocudalib to build without linking with libdevice.
clang-7: error: cannot find CUDA installation.  Provide its path via --cuda-path, or pass -nocudainc to build without CUDA includes.
clang-7: error: cannot find CUDA installation.  Provide its path via --cuda-path, or pass -nocudainc to build without CUDA includes.
```

This is not a CUDA build.

Modules:
```
Currently Loaded Modulefiles:
  1) sems-env                         5) sems-gcc/5.3.0                   9) sems-netcdf/4.4.1/exo_parallel
  2) sems-git/2.10.1                  6) sems-clang/7.0.1                10) sems-zlib/1.2.8/base
  3) sems-cmake/3.12.2                7) sems-openmpi/1.10.1             11) sems-boost/1.59.0/base
  4) sems-ninja_fortran/1.8.2         8) sems-hdf5/1.8.12/parallel       12) sems-superlu/4.3/base
```

Configure:

```bash
#!/bin/bash

ARGS=(
  -GNinja
  -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake
  -DCMAKE_BUILD_TYPE=RELWITHDEBINFO
  -DTrilinos_ENABLE_TESTS=OFF
  -DTrilinos_ENABLE_MueLu=ON
  -DTrilinos_ENABLE_ML=ON
  -DMueLu_ENABLE_TESTS=ON
  -DML_ENABLE_TESTS=ON
  -DML_ENABLE_EXAMPLES=ON
  -DTrilinos_ENABLE_Teko=OFF
  -DTrilinos_ENABLE_Intrepid2=OFF

  -DTpetra_INST_INT_LONG_LONG=OFF
  -DTpetra_INST_INT_INT=ON
)

cmake "${ARGS[@]}" ${TRILINOS_DIR}
```

@trilinos/kokkos @bartlettroscoe

**Comment by bartlettroscoe** [comment]
@jhux2, is this 'sems-rhel6' or 'sems-rhel7'?  What was the exact build name?  On what machine on the CEE LAN?

In any case, all of the 'sems-rhel6' and 'sems-rhel7' builds (including CUDA builds) on Trilinos 'develop' (actually 'atdm-nightly' which merges in 'develop' every day) this morning was just fine as shown at:

* https://testing-dev.sandia.gov/cdash/index.php?project=Trilinos&date=2020-02-03&filtercount=1&showfilters=1&field1=buildname&compare1=65&value1=Trilinos-atdm-sems-rhel

which showed:


| Site | Build Name  | Update | C W | C E | B W | B E | T NR | T F | T P | Start Time | Labels |
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- |
sems-rhel6 | Trilinos-atdm-sems-rhel6-gnu-7.2.0-openmp-complex-shared-release-debug | 2103c1 | 0 | 19 | 0 | 0 | 0 | 0 | 1972 | 15 hours ago | (24 labels)
sems-rhel6 | Trilinos-atdm-sems-rhel6-gnu-7.2.0-openmp-debug | 2103c1 | 0 | 19 | 0 | 0 | 0 | 0 | 1952 | 15 hours ago | (24 labels)
sems-rhel6 | Trilinos-atdm-sems-rhel6-gnu-7.2.0-openmp-release | 2103c1 | 0 | 19 | 0 | 0 | 0 | 0 | 1949 | 16 hours ago | (24 labels)
sems-rhel6 | Trilinos-atdm-sems-rhel6-gnu-7.2.0-openmp-release-debug | 2103c1 | 0 | 19 | 0 | 0 | 0 | 0 | 1954 | 16 hours ago | (24 labels)
sems-rhel6 | Trilinos-atdm-sems-rhel6-intel-17.0.1-openmp-release | 2103c1 | 0 | 19 | 0 | 0 | 0 | 0 | 1949 | 15 hours ago | (24 labels)
sems-rhel7 | Trilinos-atdm-sems-rhel7-cuda-9.2-Volta70-complex-shared-release-debug | 2103c1 | 0 | 3 | 0 | 0 | 0 | 2 | 1071 | 16 hours ago | (11 labels)
sems-rhel7 | Trilinos-atdm-sems-rhel7-gnu-7.2.0-openmp-complex-shared-release-debug | 2103c1 | 0 | 19 | 0 | 0 | 0 | 0 | 1972 | 15 hours ago | (24 labels)
sems-rhel7 | Trilinos-atdm-sems-rhel7-intel-18.0.5-openmp-complex-shared-release-debug | 2103c1 | 0 | 19 | 0 | 0 | 0 | 0 | 1972 | 15 hours ago | (24 labels)
sems-rhel7 | Trilinos-atdm-sems-rhel7-intel-18.0.5-openmp-shared-debug | 2103c1 | 0 | 19 | 0 | 0 | 0 | 0 | 1952 | 16 hours ago | (24 labels)
sems-rhel7 | Trilinos-atdm-sems-rhel7-intel-18.0.5-openmp-shared-release-debug | 2103c1 | 0 | 19 | 0 | 0 | 0 | 0 | 1954 | 15 hours ago | (24 labels)

Could this be a problem with the Kokkos branch?

**Comment by rppawlo** [comment]
I think the kokkos promotion was pushed into trilnos an hour ago.

**Comment by bartlettroscoe** [comment]
> I think the kokkos promotion was pushed into trilnos an hour ago.

Let's see what the ATDM Trilinos builds look like tomorrow.

**Comment by jhux2** [comment]
@bartlettroscoe This is RHEL7, cee-build014. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ndellingwood** [comment]
These are the kokkos PR's that touched the file that ninja is dying on:

https://github.com/kokkos/kokkos/pull/2477
https://github.com/kokkos/kokkos/pull/2626

though it isn't clear how the error message is at all connected to those changes.

@jhux2 is CUDA enabled by the `-DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake` line, and can you dump the configure output to file?

I don't see a cuda module loaded, but the error output is cuda related

```
clang-7: error: cannot find libdevice for sm_20. Provide path to different CUDA installation via --cuda-path, or pass -nocudalib to build without linking with libdevice.
clang-7: error: cannot find CUDA installation.  Provide its path via --cuda-path, or pass -nocudainc to build without CUDA includes.
clang-7: error: cannot find CUDA installation.  Provide its path via --cuda-path, or pass -nocudainc to build without CUDA includes.
```

@jjwilke @crtrott any ideas based on the info in this issue?

**Comment by ndellingwood** [comment]
@jhux2 what argument are you passing to `cmake/std/atdm/ATDMDevEnvSettings.cmake`?

**Comment by ndellingwood** [comment]
I reproduced this on kokkos-dev-2 and cee-compute008 (both recognized as sems-rhel7 systems), and the error occurs when building the first kokkos file (not specific to the CPUDiscovery file above, as it shouldn't)

I had to make a change to the `Trilinos/cmake/std/atdm/sems-rhel7/environment.sh` script to get this to configure, I added
 
`export ATDM_CONFIG_Kokkos_ENABLE_Serial=ON` to line 132, otherwise the scripts would attempt a serial build without ever enabling `Kokkos_ENABLE_Serial=ON` and give a configure error that no Host execution space was enabled for Kokkos.

@jjwilke are there CMake changes so that `Kokkos_ENABLE_Serial` must be explicitly enabled in a Trilinos build? At the very least, some change in Kokkos broke some assumption(s) made in the ATDM scripts. I'll post my configuration from kokkos-dev-2, can you take a look?

First add
`export ATDM_CONFIG_Kokkos_ENABLE_Serial=ON` 

to line 132
`Trilinos/cmake/std/atdm/sems-rhel7/environment.sh`

Configuration
```bash
export TRILINOS_DIR=<PATH>
source ${TRILINOS_DIR}/cmake/std/atdm/load-env.sh Trilinos-atdm-sems-rhel7-clang

ARGS=(
  -GNinja
  -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake
  -DCMAKE_BUILD_TYPE=RELWITHDEBINFO
  -DTrilinos_ENABLE_TESTS=OFF
  -DTrilinos_ENABLE_Kokkos=ON
  -DKokkos_ENABLE_TESTS=ON
  -DKokkos_ENABLE_SERIAL=ON
)

cmake "${ARGS[@]}" ${TRILINOS_DIR}
```

**Comment by ndellingwood** [comment]
@jjwilke Looking at the CMakeCache of a develop vs master branch of Trilinos configuration, I'm seeing this in the develop branch (kokkos 3.0 release):

`KOKKOS_CUDA_OPTIONS:INTERNAL=-x;cuda`

This gets set at line 160 of `kokkos/cmake/kokkos_arch.cmake` because this check passes with the clang compiler:
`IF (KOKKOS_CXX_COMPILER_ID STREQUAL Clang)`

Changing this to 
`IF (KOKKOS_CXX_COMPILER_ID STREQUAL Clang AND KOKKOS_ENABLE_CUDA)`

resolves the compile errors, but not the need to modify the ATDM scripts to get a serial build going. I'll put in an hot-fix PR to Trilinos ASAP for the fix above.

**Comment by ndellingwood** [comment]
PR #6738 issued with fix for the compilation errors. Not sure about the configuration error I ran into, possible user error but requires more feedback.

**Comment by ndellingwood** [comment]
@jhux2 did you need to make any modifications to the ATDM scripts to successfully configure the build where you found this error?

**Comment by bartlettroscoe** [comment]
@ndellingwood, to be clear, is there a problem with the way that the ATDM Trilinos configuration is setting Kokkos configuration options?  Regarding the logic mentioned [above](https://github.com/trilinos/Trilinos/issues/6734#issuecomment-581762623):

```
IF (KOKKOS_CXX_COMPILER_ID STREQUAL Clang)
```

was this assuming that if you were using Clang you automatically wanted to use CUDA?

**Comment by ndellingwood** [comment]
@bartlettroscoe :

> is there a problem with the way that the ATDM Trilinos configuration is setting Kokkos configuration options?

@jjwilke can you help address this? I'm assuming there was some change that breaks an assumption in the ATDM scripts, as I needed to modify the scripts to get them working



> ```
> IF (KOKKOS_CXX_COMPILER_ID STREQUAL Clang)
> ```
> 
> 
> was this assuming that if you were using Clang you automatically wanted to use CUDA?

I don't think this was intended to be assumed, but I made the change there because I traced the compilation issues back to options that were set here. @jjwilke proposed an alternative fix here https://github.com/trilinos/Trilinos/pull/6738#issuecomment-581942929

**Comment by ikalash** [comment]
This happens in our Albany nightlies as well.  Some additional info: 

- On a GPU platform like Ride and Waterman, we get a configuration error: 
```
-- Using -std=c++11 for C++11 standard as feature
CMake Error at packages/kokkos/cmake/kokkos_test_cxx_std.cmake:39 (MESSAGE):
  Compiler NVIDIA should support cxx_std_11, but CMake reports feature not
  supported
Call Stack (most recent call first):
  packages/kokkos/cmake/kokkos_test_cxx_std.cmake:54 (kokkos_set_cxx_standard_feature)
  packages/kokkos/cmake/kokkos_tribits.cmake:172 (INCLUDE)
  packages/kokkos/CMakeLists.txt:146 (KOKKOS_SETUP_BUILD_ENVIRONMENT)
```
http://cdash.sandia.gov/CDash-2-3-0/viewConfigure.php?buildid=92861
- When we build Albany using a compiler not affected by this issue on top of a successfully built Trilinos, Albany thinks the Trilinos has CUDA when it does now.  This is triggered by the following lines in the Albany CMakeLists.txt file: https://github.com/SNLComputation/Albany/blob/master/CMakeLists.txt#L239-L245 .

**Comment by ndellingwood** [comment]
@ikalash a PR #6738 just merged with additional followup #6744 sorry for the inconvenience

**Comment by jhux2** [comment]
@ndellingwood I can confirm that clang builds on the CEE lan are working again.  Thank you and @jjwilke for the quick fixes!

**Comment by ikalash** [comment]
I tested on waterman and I get this error now: 
```
-- Using -std=c++11 for C++11 standard as feature
CMake Error at packages/kokkos/cmake/kokkos_test_cxx_std.cmake:39 (MESSAGE):
  Compiler NVIDIA should support cxx_std_11, but CMake reports feature not
  supported
Call Stack (most recent call first):
  packages/kokkos/cmake/kokkos_test_cxx_std.cmake:54 (kokkos_set_cxx_standard_feature)
  packages/kokkos/cmake/kokkos_tribits.cmake:172 (INCLUDE)
  packages/kokkos/CMakeLists.txt:146 (KOKKOS_SETUP_BUILD_ENVIRONMENT)
 ```
I suspect my nvcc_wrapper needs updating.  The one I'm using is attached . Does it need to be updated?  
[nvcc_wrapper_volta.txt](https://github.com/trilinos/Trilinos/files/4156409/nvcc_wrapper_volta.txt)

**Comment by jjwilke** [comment]
Yeah, you will need to use the `nvcc_wrapper` in the Trilinos repo. The Waterman development modules probably set `OMPI_CXX` to point to an old `nvcc_wrapper`.

**Comment by jjwilke** [comment]
I will send notes to the mailing lists to figure out how to get these updated.

**Comment by ikalash** [comment]
@jjwilke : thanks, I figured.  Updating the nvcc_wrapper to match the one in the Trilinos repo seems to fix the problem with my builds.
