### ISSUE TITLE
 Zoltan2: reversal of Cuthill McKee ordering is incorrect

### ISSUE THREAD

**Issue by jhux2** [trilinos/Trilinos#6735]
The reversal of the Cuthill McKee ordering in `Zoltan2_AlgRCM.hpp` is incorrect.  This can result in orderings that make the matrix bandwidth worse than the original bandwidth.

**Comment by jhux2** [comment]
@trilinos/zoltan2

**Comment by vbrunini** [comment]
This fixed all of our regression tests where reordering was the difference between the solves converging or not with Aztec. Thanks!
