### ISSUE TITLE
Question: Was Boost removed from STK

### ISSUE THREAD

**Issue by spdomin** [trilinos/Trilinos#6740]
## Bug Report
@trilinos/stk

### Description
Undefined symbols for architecture x86_64:
  "boost::program_options::validators::check_first_occurrence(boost::any const&)", referenced from:

### Version
02/04/2020
PROCESS FAILED
NaluCFD/Nalu SHA1: df8e218c10a53497faff770b20f171c200e0739c
Trilinos/develop SHA1: 95ca69d7b65d7ea8bc8deac32934be55d674393b

**Comment by spdomin** [comment]
@alanw0, do you have any comments here? I was just looking into removing program options and looked into a simple option such as getopt_long.

When STK removes boost, what is the plan for boost_options?

In the meantime, I will proceed with a bisect.

**Comment by alanw0** [comment]
Stefan, a stk update was pushed yesterday. Initially there was a cmake error but a follow-up push fixed that around 6:45pm yesterday. I don't think this is related to what you are seeing. Additionally, it looks like boostlib was removed from the stk_search dependencies. Do you depend on boostlib directly? Can you include more linker output regarding this error?

**Comment by alanw0** [comment]
Regarding boost program_options, stk no longer needs that. Most sierra executables are now doing command-line parsing using stk classes which I can point you to if you are interested.

**Comment by alanw0** [comment]
Regarding the stk_search dependency on boostlib, I will put that back until we figure out which apps were indirectly depending on that, and how they can express the dependency directly.

**Comment by spdomin** [comment]
Please do point me to the STK program options example... I would probably like to avoid writing my own, even though I have a getopt_long that seems to work well.

I am not sure what is going on with my builds. A bisect is failing due to that make error.

**Comment by alanw0** [comment]
@spdomin I don't think you need a bisect, I'm pretty confident this is due to the stk update that happened yesterday.
The same link error is happening in nalu-wind. (Along with some kokkos errors, but I think those are un-related.)
Here's my short-term plan:
1. put the boostlib dependency back on stk_search. I'll do that today.
2. refactor nalu-wind's command-line-parsing code to stop using boost program_options, and also compare with nalu-cfd's command-line-parsing code which I suspect (hope) is still pretty similar, and I'll help you adapt.

**Comment by spdomin** [comment]
sounds like a plan. I looked at the Sierra codes and simply saw a number of Env classes. In the meantime, if you could point me to a STK example, I can refactor now.

**Comment by spdomin** [comment]
For the record, usage of getopt_long looks a bit flaky...

```
  struct option long_options[] =
    {
      {"help", optional_argument, NULL, 'h'},
      {"version", optional_argument, NULL, 'v'},
      {"input-file", optional_argument, NULL, 'i'},
      {"log-file", optional_argument, NULL, 'o'},
      {"serialized-io-group-size", optional_argument, NULL, 's'},
      {"Debug", optional_argument, NULL, 'D'},
      {"pprint", optional_argument, NULL, 'p'},
      {NULL, 0, NULL, 0}
    };

```

**Comment by alanw0** [comment]
ok here are a couple of examples you can look at:
aero/reorder_mesh/ReorderMeshMain.C roughly lines 70 - 100
stk/stk_unit_tests/stk_util/command_line/UnitTestCommandLineParser.cpp
stk/stk_unit_tests/stk_util/environment/UnitTestParseCommandLineArgs.cpp

**Comment by spdomin** [comment]
@alanw0, how do I possibly disable kokkos help? In some cases, this info is not germane to a simulation.

> --------------------------------------------------------------------------------
> -------------Kokkos command line arguments--------------------------------------
> --------------------------------------------------------------------------------
> The following arguments exist also without prefix 'kokkos' (e.g. --help).
> The prefixed arguments will be removed from the list by Kokkos::initialize(),
> the non-prefixed ones are not removed. Prefixed versions take precedence over 
> non prefixed ones, and the last occurrence of an argument overwrites prior
> settings.
> 
> --kokkos-help               : print this message
> --kokkos-disable-warnings   : disable kokkos warning messages
> --kokkos-threads=INT        : specify total number of threads or
>                               number of threads per NUMA region if 
>                               used in conjunction with '--numa' option. 
> --kokkos-numa=INT           : specify number of NUMA regions used by process.
> --kokkos-device=INT         : specify device id to be used by Kokkos. 
> --kokkos-ndevices=INT[,INT] : used when running MPI jobs. Specify number of
>                               devices per node to be used. Process to device
>                               mapping happens by obtaining the local MPI rank
>                               and assigning devices round-robin. The optional
>                               second argument allows for an existing device
>                               to be ignored. This is most useful on workstations
>                               with multiple GPUs of which one is used to drive
>                               screen output.
> 
> --------------------------------------------------------------------------------
> 
> Nalu Supported Options:
> 
> --help,-h                       Help message
> --version,-v                    v1.4.0-33-gdf8e218-dirty
> --input-file,-i                 Analysis input file
>                                  (default: nalu.i)
> --log-file,-o                   Analysis log file
>                                  (default: nalu.log)
> --serialized-io-group-size,-s   Specifies the number of processors that can
>                                 concurrently perform I/O. Specifying zero
>                                 disables serialization.
>                                  (default: 0)
> --debug,-D                      Debug output to the log file
> --pprint,-p                     Parallel output to the number of mpi rank log
>                                 files

**Comment by spdomin** [comment]
https://github.com/NaluCFD/Nalu/commit/360696f80f9ca565485ad702a71eecf98a22385f 

Closing.. Alan, your choice in patching STK.... Does that mean that we are now free of boost?

**Comment by alanw0** [comment]
@spdomin wow, well done, that was fast. That makes you free of boostlib, but unfortunately some stk files still need boost, i.e., some header-only libs in boost. It's a journey, but we aim to be completely free of boost at some point.

Regarding the kokkos help output, I don't know the answer but I'll try to find out how to stop that.

**Comment by spdomin** [comment]
I only see:

-- Setting TPL_ENABLE_Boost=ON because it is required by the enabled package STKSearch

However, I thought that is what you said was removed recently?

At any rate, the kokkos-help is fine if it can not be removed and let me know when I can remove Boost instructions from the Nalu build.

**Comment by rppawlo** [comment]
@spdomin - this might be of help with replacing program options:

https://github.com/trilinos/Trilinos/blob/master/packages/teuchos/core/src/Teuchos_CommandLineProcessor.hpp

**Comment by alanw0** [comment]
@spdomin I have to confess I "leveraged" (i.e., basically copied) your command-line-parsing conversion into nalu-wind's version of nalu.C.

Regarding the remaining boost dependency: You still need TPL_ENABLE_Boost=ON, but you no longer need TPL_ENABLE_BoostLib=ON.
