### ISSUE TITLE
ShyLU_DD:  48 tests missing?

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#6741]
## Question
@trilinos/shylu 

The last PR iteration shown [here](https://testing-dev.sandia.gov/cdash/index.php?project=Trilinos&parentid=5212151) showed that 48 ShyLU_DD tests have gone missing as listed [here](https://testing-dev.sandia.gov/cdash/viewTest.php?onlypassed&buildid=5212188).

Was this on purpose or was this due to the refactoring of the Kokkos build system they merged in?

**Comment by bartlettroscoe** [comment]
BTW, I got tipped of to this by the below email that I just got (and the @trilinos/framework team got it too).

----

From: admin@cdash.org <admin@cdash.org> 
Sent: Tuesday, February 4, 2020 8:19 AM
To: Bartlett, Roscoe A <rabartl@sandia.gov>
Subject: [EXTERNAL] FAILED (t=0, m=48): Trilinos - Linux-GCC-4.8.4-MPI_RELEASE_DEBUG_SHARED_PT_OPENMP_CI - Continuous

A submission to CDash for the project Trilinos has failing tests and missing tests. You have been identified as one of the authors who have checked in changes that are part of this submission or you are listed in the default contact list.

Details on the submission can be found at https://testing.sandia.gov/cdash/buildSummary.php?buildid=6335679.

Project: Trilinos
Site: ceerws1113
Build Name: Linux-GCC-4.8.4-MPI_RELEASE_DEBUG_SHARED_PT_OPENMP_CI
Build Time: 2020-02-04 11:02:07
Type: Continuous
Total Failing Tests: 0
Total Missing Tests: 48

*Failing Tests* 

*Missing Tests* (first 5 included)
ShyLU_DDFROSch_test_overlap_Graph_DIM2_DPN1_TPETRA_MPI_4 (https://testing.sandia.gov/cdash/viewTest.php?buildid=6335716)
ShyLU_DDFROSch_test_overlap_Graph_DIM2_DPN2_TPETRA_MPI_4 (https://testing.sandia.gov/cdash/viewTest.php?buildid=6335716)
ShyLU_DDFROSch_test_overlap_Matrix_DIM2_DPN1_TPETRA_MPI_4 (https://testing.sandia.gov/cdash/viewTest.php?buildid=6335716)
ShyLU_DDFROSch_test_overlap_Matrix_DIM2_DPN2_TPETRA_MPI_4 (https://testing.sandia.gov/cdash/viewTest.php?buildid=6335716)
ShyLU_DDFROSch_test_overlap_Old_DIM2_DPN1_TPETRA_MPI_4 (https://testing.sandia.gov/cdash/viewTest.php?buildid=6335716)

-CDash on testing.sandia.gov

**Comment by cgcgcg** [comment]
@searhein

**Comment by brian-kelley** [comment]
@cgcgcg @bartlettroscoe I believe this is because of ``shylu/shylu_dd/frosch/test/CMakeLists.txt``:

```
IF(ShyLU_DDFROSch_ENABLE_Belos AND KOKKOS_ENABLE_SERIAL AND ShyLU_DDFROSch_ENABLE_Stratimikos AND ShyLU_DDFROSch_ENABLE_Thyra)
ADD_SUBDIRECTORIES(
    Gathering
    Overlap
    Thyra_Xpetra_Elasticity
    Thyra_Xpetra_Laplace
)
ENDIF()
```
I don't think ``KOKKOS_ENABLE_SERIAL`` is the right case now. I'll put in a fix.

**Comment by bartlettroscoe** [comment]
> I don't think KOKKOS_ENABLE_SERIAL is the right case now. I'll put in a fix.

@brian-kelley, that is what I suspected.  See, this "missing tests" email is pretty handy, right!   (That was a feature that one of my earlier Kitware contracts while I was at ORNL paid for.)

**Comment by brian-kelley** [comment]
OK, that did enable all the tests, but now the Epetra versions are all failing (the Tpetra versions are all passing).

**Comment by searhein** [comment]
@brian-kelley I also had the same problem with all the Epetra tests, just two weeks ago. Unfortunately, due to time constraints, I was not able to fix it yet. I was very surprised because all the tests still worked fine a few months ago and the Tpetra tests are all fine. Do you have a clue what the problem could be?
I will look into it this week.

@bartlettroscoe What does "missing tests" actually mean?

**Comment by bartlettroscoe** [comment]
> What does "missing tests" actually mean?

@searhein, it means that on the previous build iteration, those tests existed and on the next iteration, they disappeared are were "missing".  Tests can be missing for one of the following reasons:

* They were removed on purpose
* They where renamed on purpose
* They were removed on accident (like happened here)

**Comment by brian-kelley** [comment]
@bartlettroscoe, @searhein I used a git bisect to figure out that the test failure were because of my own PR from November :)

#6835 re-enables the tests and fixes them for Epetra.

**Comment by brian-kelley** [comment]
That fix has been merged.

**Comment by bartlettroscoe** [comment]
> I used a git bisect to figure out that the test failure were because of my own PR from November :)

@brian-kelley, what PR was that?  What that a PR in the kokkos GitHub repo?

**Comment by brian-kelley** [comment]
@bartlettroscoe Oh actually the PR was from December (#6388) but the offending commit was from November. This was the huge PR that removed all Tpetra stack deprecated code.

**Comment by bartlettroscoe** [comment]
> Oh actually the PR was from December (#6388) but the offending commit was from November. This was the huge PR that removed all Tpetra stack deprecated code.

@brian-kelley, how did PR #6388 merged way back on 2019-12-17 result in failing tests that did not get disabled until the Kokkos 2.99 update got merged on 2020-02-02 where they got disabled?

**Comment by brian-kelley** [comment]
@bartlettroscoe This only affected the Epetra versions of the tests that went missing. To get those enabled, both Tpetra and Epetra must be enabled and Tpetra GO must be explicitly int (so they can both be supported by Xpetra). This is because Tpetra is required by FROSch, but FROSch can optionally use Epetra through Xpetra. Now that I look through the dashboard, I don't think we test this configuration. I also don't think any PR builds do but I could be wrong.

I know I did some work during the deprecated removal to get the Epetra versions passing, but I must have broken something later on in the PR and it never got caught.

The tests that went missing are all the Tpetra versions of these tests, so the Epetra ones have effectively been missing since #6388 because that's when multiple GO in Tpetra was removed.

**Comment by bartlettroscoe** [comment]
> The tests that went missing are all the Tpetra versions of these tests, so the Epetra ones have effectively been missing since #6388 because that's when multiple GO in Tpetra was removed.

@brian-kelley, thanks for the explanation.    Just as a check, what is the name of one of the ShyLU_DD FROSch tests that needs Epetra and GO int to be enabled?  With that info, we can search the CDash site to see what builds, if any, tests this configuration and when the last time these got tested.

I am mostly curious to know from an academic perspective.  Where do the Trilinos testing processes have gaps and are they gaps in tools, or gaps in the builds that are set up and running, or gaps in other processes?  The email generated shown [above](https://github.com/trilinos/Trilinos/issues/6741#issuecomment-581942508) clearly helped to identify a problem but if I had not been running this post-push CI server myself which generated this email, would anyone have noticed these tests having gone missing, and if so, how long would it have taken for someone to notice?

**Comment by brian-kelley** [comment]
@bartlettroscoe Here's one of them: ``ShyLU_DDFROSch_test_thyra_xpetra_laplace_TLP_RGDSW_DIM2_DPN1_ORD0_EPETRA_MPI_4``

**Comment by bartlettroscoe** [comment]
> Here's one of them: ShyLU_DDFROSch_test_thyra_xpetra_laplace_TLP_RGDSW_DIM2_DPN1_ORD0_EPETRA_MPI_4

Looks like we are in luck as we can see there are some builds running this test as shown yesterday in:

* https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&date=2020-02-16&filtercount=1&showfilters=1&field1=testname&compare1=61&value1=ShyLU_DDFROSch_test_thyra_xpetra_laplace_TLP_RGDSW_DIM2_DPN1_ORD0_EPETRA_MPI_4 

showing:

Site | Build Name | Test Name | Status | Time | Proc Time | Details | Build Time | Processors
-- | -- | -- | -- | -- | -- | -- | -- | --
ascic114 | Linux-GCC-4.9.3-openmpi-1.8.7_Debug_DEV_Werror | ShyLU_DDFROSch_test_thyra_xpetra_laplace_TLP_RGDSW_DIM2_DPN1_ORD0_EPETRA_MPI_4 | Passed | 1s 920ms | 7s 680ms | Completed | 2020-02-16T02:01:03 MST | 4
ascic166 | Linux-intel-17.0.1-MPI_Release_intel_17.0.1_openmpi_1.10.1_DEV | ShyLU_DDFROSch_test_thyra_xpetra_laplace_TLP_RGDSW_DIM2_DPN1_ORD0_EPETRA_MPI_4 | Passed | 990ms | 3s 960ms | Completed | 2020-02-15T22:55:40 MST | 4

and you can see the history of this test in say the build `Linux-GCC-4.9.3-openmpi-1.8.7_Debug_DEV_Werror` in the query:

* https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&begin=2019-12-01&end=2020-02-17&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Linux-GCC-4.9.3-openmpi-1.8.7_Debug_DEV_Werror&field2=testname&compare2=61&value2=ShyLU_DDFROSch_test_thyra_xpetra_laplace_TLP_RGDSW_DIM2_DPN1_ORD0_EPETRA_MPI_4

which shows this tests was passing contiguously from 2019-12-01 to 2020-02-17.

Why did you say it was failing?

**Comment by brian-kelley** [comment]
@bartlettroscoe Both of those builds are using the last release (4442eef) from last June, not develop. They still have all the deprecated Tpetra cmake logic supporting multiple GOs.

**Comment by brian-kelley** [comment]
@bartlettroscoe Actually, I don't know what's special about 4442eef, it's somewhere between release 12.14 and release 12.18. But all the nightly tests and some specialized tests use it.
