### ISSUE TITLE
Trikota compilation error

### ISSUE THREAD

**Issue by ikalash** [trilinos/Trilinos#6742]
The Albany nightlies that use TriKota have the following compilation error when building Trilinos: 

```
[ 22%] Building CXX object packages/TriKota/Dakota/packages/external/JEGA/src/CMakeFiles/jega.dir/Mutators/CauchyOffsetMutator.cpp.o
/home/ikalash/nightlyAlbanyTests/Results/Trilinos/packages/TriKota/Dakota/src/DataVariables.cpp: In member function ‘void Dakota::DataVariablesRep::write(std::ostream&) const’:
/home/ikalash/nightlyAlbanyTests/Results/Trilinos/packages/TriKota/Dakota/src/DataVariables.cpp:289:5: error: no match for ‘operator<<’ (operand types are ‘std::basic_ostream<char>’ and ‘const RealSymMatrix’ {aka ‘const Teuchos::SerialSymDenseMatrix<int, double>’})
  267 |   s << normalUncMeans << normalUncStdDevs << normalUncLowerBnds
      |   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  268 |     << normalUncUpperBnds << normalUncVars << lognormalUncLambdas
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  269 |     << lognormalUncZetas << lognormalUncMeans << lognormalUncStdDevs
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  270 |     << lognormalUncErrFacts << lognormalUncLowerBnds << lognormalUncUpperBnds
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  271 |     << lognormalUncVars << uniformUncLowerBnds << uniformUncUpperBnds
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  272 |     << uniformUncVars << loguniformUncLowerBnds << loguniformUncUpperBnds
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  273 |     << loguniformUncVars << triangularUncModes << triangularUncLowerBnds
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  274 |     << triangularUncUpperBnds << triangularUncVars << exponentialUncBetas
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  275 |     << exponentialUncVars << betaUncAlphas << betaUncBetas << betaUncLowerBnds
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  276 |     << betaUncUpperBnds << betaUncVars << gammaUncAlphas << gammaUncBetas
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
Could you please look into this?

@trilinos/trikota

**Comment by mhoemmen** [comment]
This might be because of removal of deprecated code in @trilinos/teuchos.  I didn't do it ;-P

**Comment by ikalash** [comment]
@briadam : could you please look into this?

**Comment by briadam** [comment]
Yes, this is almost surely related to removal of deprecated code in Teuchos, but Dakota should be providing operator<< for this data type (in header dakota_data_io.hpp around line 229). Before digging too much can you (@ikalash ) please confirm what Dakota version this is and what compiler toolchain?

I'll add this to our backlog in Dakota so I'm not a single point of failure.

**Comment by ikalash** [comment]
@briadam : it looks like our Dakota is quite old: dakota-6.9-release-public.src.tar.gz (from 2018) - I had forgotten that we are not using Dakota VOTD in our workflow.  I am guessing a newer release fixes the problem - can you please point me to which one is best to use?

**Comment by briadam** [comment]
I'd probably just go with latest 6.11 to avoid chasing other errors (I believe the change came in with Dakota 6.10 if we run into trouble with 6.11). Download link: https://dakota.sandia.gov/sites/default/files/distributions/public/dakota-6.11-release-public.src.tar.gz 

And we may still have to patch to help with compiler errors since I know you often use pretty new compilers and there isn't any other automated testing for Dakota under Trilinos, so Dakota's CMake can easily break for that scenario.

**Comment by bartlettroscoe** [comment]
@kddevin, @jeforster

**Comment by kddevin** [comment]
The ostream overload for Teuchos::SerialDense*Matrix was deprecated in #5374 as requested in #5085 by @mseldre and @rhoope .  The deprecated code was recently removed from Trilinos #6721.

If you have a Teuchos::SerialDense*Matrix object B, you can print it with 
cout << printMat(B) << endl;
See examples of printMat in packages/anasazi/epetra/test/OrthoManager/cxx_gentest.cpp

Please let me know here whether updating Dakota resolves the problem.  Thanks!

For more info on Trilinos deprecations, please see
https://github.com/trilinos/Trilinos/wiki/Trilinos_v12_code_deprecation.pdf

**Comment by ikalash** [comment]
This version of Dakota works - thanks for your help @briadam !
