### ISSUE TITLE
Kokkos:  Compilation with MSVC(Visual Studio 19) + ICC

### ISSUE THREAD

**Issue by alessiocacciatori** [trilinos/Trilinos#6745]
## Question
@trilinos/\<Kokkos\> 

Hi team,
  I am trying to compile entire Trilinos suite under MSVC(+ICC). Right now I managed to compile Kokkos + OpenMP but this came with quite a substantial effort and coding that raised many questions.

Basically we've found some issue that I would like to discuss before (possibly) submitting the emended code.

1) _Kokkos_HostBarrier.cpp_ Line 103. The function _try_wait(void)_ calls the static function _try_wait(int *, const int, const int)_ passing non-static members (m_buffer...). Problem is: HostBarrier methods are often called by their static methods (e.g _Kokkos_HostThreadTeam.hpp_, line 139).

This, of course, is an error and I am surprised on how GCC can overcome this.

2) cas128_t is defined twice (_Kokkos_AtomicAssembly.hpp_ and _Kokkos_AtomicWindows.hpp_) Solved this by removing definition in _Kokkos_AtomicAssembly.hpp_ but I am not sure what the differences are.

3) _atomic_compare_exchange_ with _cas128_t_ (_Impl::cas128_t atomic_compare_exchange<_) has a conversion error:     _tmp.t = dest;_ Indeed it is trying to convert a pointer to cas128_t to cas128_t. Solved with _tmp.t = *dest;_

4) _atomic_compare_exchange_ with SFINAE generates quite a lot of redefinition errors. Solved this by removing all SFINAE definitions and adding proper specialized bodies.

So, I am not sure if what we considered as errors are actual errors. Are we doing right with the proposed fixes (with those fixes we managed to compile Kokkos on Windows)?

Thank you in advance,
Alessio

**Comment by ndellingwood** [comment]
@trilinos/kokkos 

Also adding @ibaned and @crtrott as I think they have worked on Windows support in Kokkos somewhat recently.

**Comment by mhoemmen** [comment]
https://github.com/kokkos/kokkos/issues/1533

**Comment by ibaned** [comment]
Yes, we're working on this ourselves and have addressed the issues you listed. We still have remaining issues with excessive SFINAE in the `View::operator()` declarations that we're working through.

**Comment by alessiocacciatori** [comment]
Hi all,
  Thank you for the prompt feedback! 
Glad to see that, somewhat, we were moving in the right direction.

@ibaned : is there any roadmap on MSVC deployment that you may share  (So that we could focus on other aspects of the SW we're developing)?

Or, maybe we can cooperate by sharing our list of modifications if you think that this may help you.

**Comment by ibaned** [comment]
Hi @alessiocacciatori, our progress is tracked in this WIP PR:
https://github.com/kokkos/kokkos/pull/2655
We would like to get this done by Kokkos version 3.1
