### ISSUE TITLE
Kokkos:  Build issue with views

### ISSUE THREAD

**Issue by tasmith4** [trilinos/Trilinos#6747]
## Bug Report
@trilinos/kokkos

### Description

For the following statement:

      Kokkos::deep_copy(multiDimViews[i]->get_scratch_view_1D(0), i+1);

we get this build error after updating to the latest Trilinos (develop branch):

```
/tmp/tasmit/exawind/install/intel/trilinos/include/Kokkos_CopyViews.hpp(1430): error #373: "Kokkos::ScratchMemorySpace<ExecSpace>::ScratchMemorySp
ace() [with ExecSpace=Kokkos::OpenMP]" (declared at line 79 of "/tmp/tasmit/exawind/install/intel/trilinos/include/Kokkos_ScratchSpace.hpp") is in
accessible
              typename ViewType::memory_space().name()),
              ^
          detected during instantiation of "void Kokkos::deep_copy(const Kokkos::View<DT, DP...> &, Kokkos::ViewTraits<DT, DP...>::const_value_typ
e &, std::enable_if<std::is_same<Kokkos::ViewTraits<DT, DP...>::specialize, void>::value, void>::type *) [with DT=double *, DP=<Kokkos::LayoutRigh
t, sierra::nalu::DeviceShmem, Kokkos::MemoryUnmanaged>]" at line 137 of "/tmp/tasmit/exawind/source/nalu-wind/unit_tests/UnitTestCopyAndInterleave
.C"
```

Our code has not changed recently -- is there something we need to change in how we call `Kokkos::deep_copy`?

**Comment by mhoemmen** [comment]
@trilinos/kokkos

**Comment by ibaned** [comment]
Hi @tasmith4, I brought this to the Kokkos bug tracker here:
kokkos/kokkos#2723

**Comment by crtrott** [comment]
Repeat from the Kokkos issue: Ok this is problematic for various reasons. Right now we have something called `local_deep_copy` for being called inside of Kernels. `deep_copy` is not currently legal to be called inside of kernels. The primary reason for calling this different is that we can not reliably detect whether we are within kernel code with all backends, and at the same time we can not detect from the arguments which version we should call (obviously for scratch memory it should be fine, but for everything else it is not).

**Comment by crtrott** [comment]
Just to clarify: this is user error. `Kokkos::deep_copy` is not allowed to be used inside of Kernels. `Kokkos::Experimental::local_deep_copy` provides this capability. And it has an overload to take the team handle if called inside a hierarchical kernel.
