### ISSUE TITLE
Memory growth in Drekar application

### ISSUE THREAD

**Issue by jhux2** [trilinos/Trilinos#675]
@ambrad @rppawlo @eric-c-cyr

Reported by @pwxy 

"I'm running the drekar steady-state 3d MHD generator test case with tpetra/belos/muelu, and forcing the Krylov solver to always take 100 steps of TFQMR.  The memory usage appears to be growing, with maximum among the MPI processing being 303MB after the first newton step and 413 MB after the 6th newton step.  Maybe I'm missing something, but if I'm using TFQMR and running the same number of iterations per newton step, why should the max memory usage grow by 36% after 6 newton steps?  Seems to me that it should not be growing.  TFQMR is being preconditioned by MueLu with ifpack2 additive schwarz with one level of overlap."

**Comment by jhux2** [comment]
Quoting @pwxy
"Actually I've seen this memory growth issue for a while.  Because I normally run GMRES where memory usage should change from Newton step to Newton step, the source of the memory growth was more nebulous.

I just ran a drekar binary that has been sitting around since February with TFQMR, and I see the same memory growth issue with tpetra/belos/muelu ifpack2 RILUK.  So this issue has been around since at least February, and I'm sure even earlier."

**Comment by jhux2** [comment]
@pwxy Are you still seeing memory growth?

**Comment by pwxy** [comment]
I'll need to check, but I'm sure it is still there.

**Comment by jhux2** [comment]
Closing, as this is quite old.  If it's still valid, feel free to reopen.
