### ISSUE TITLE
Upgrade minimum CMake version for TriBITS/Trilinos to 3.13

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#6752]
@trilinos/framework, @jwillenbring (Framework Lead), @kddevin (Data Services Lead), @srajama1 (Linear Solvers Lead), @mperego (Discretizations Lead), @rppawlo (Nonlinear Solvers Lead)

In order to improve the usage of CMake in Kokkos and TriBITS, there is a desire to increase the minimum version of CMake from 3.10 to 3.13.   From @jjwilke, the motivation for Kokkos is:

* Move to CMake 3.13 (allows link_options and better with flag deduplication) 

For TriBITS refactoring in TriBITSPub/TriBITS#63, it allows the usage of `<PackageName>_ROOT`  in [find_package()](https://cmake.org/cmake/help/v3.13/command/find_package.html).

**Comment by rppawlo** [comment]
Sounds good to me. Is cmake 3.13 supported under the sems modules? Also we will need to make sure that all the testbeds have this installed. There was some disruption on the empire side the last time trilinos upped the cmake version so we should give the apps some lead time to update their pipelines. What would be the timeline?

**Comment by bartlettroscoe** [comment]
> Is cmake 3.13 supported under the sems modules?

No, looks like the most current version is `sems-cmake/3.12.2`.

We will need to ask for cmake 3.14.x.  (We can't use 3.15+ in EMPIRE due to problem with how C++ standard flags are being used as described in https://gitlab.kitware.com/snl/project-1/issues/131,  https://cee-gitlab.sandia.gov/EM-Plasma/EMPIRE/issues/1110, and https://gitlab.kitware.com/cmake/cmake/issues/19917).

**Comment by bartlettroscoe** [comment]
I requested SEMS add cmake 3.14.6 in:

* https://sems-atlassian-son.sandia.gov/jira/servicedesk/customer/portal/4/SEHELPD-1808

**Comment by bartlettroscoe** [comment]
NOTE: Our almost-ready ATDM Spack install process installs CMake 3.14:

* https://gitlab-ex.sandia.gov/atdm/atdm-spack

See:

* https://gitlab-ex.sandia.gov/atdm/atdm-spack/blob/snl-atdm/utils/spec_data.sh

**Comment by srajama1** [comment]
Sounds good to me. The sooner this gets done the better it is. If you need our help with sems team, please let us know. I am happy to convey the priorities.

**Comment by mperego** [comment]
Fine with me. Thanks.

**Comment by kddevin** [comment]
We need the updated SEMS modules first.  
After it is available through SEMS, updating the requirement is OK.  
It would be nice to have it done before Trilinos v13.

**Comment by bartlettroscoe** [comment]
> We need the updated SEMS modules first.

Yes, of course.  The Trilinos PR testing process would not even allow that to happen without the Trilinos PR builds being upgraded to use the cmake-3.14

> It would be nice to have it done before Trilinos v13.

This brings up another issue.  The refactorings of TriBITS and Trilinos to use target-centric features in CMake as requested by @jjwilke and Kokkos as specified in TriBITSPub/TriBITS#299 will make it very difficult to maintain backward comparability with-respect to the build system.  For example, it may not be possible keep supporting the generation of `Makefile.export.<Package>` files for customers like INL MOOSE.

**Comment by bartlettroscoe** [comment]
This is a duplicate of the more recent issue #8401 which is to upgrade the minimum version to 3.17.1.

**Comment by bartlettroscoe** [comment]
Related to:
* SEPW-213
* SEPW-214
