### ISSUE TITLE
belos/muelu: 12.18.1 fails to build with Clang 8.0.0 on Mac OS

### ISSUE THREAD

**Issue by scheibelp** [trilinos/Trilinos#6761]
## Bug Report
@trilinos/belos
@trilinos/muelu

### Description
The following patch was required to build Trilinos 12.18.1 with apple-clang 8.0.0 on Mac OS: https://github.com/spack/spack/pull/14723/files#diff-c48cdeb8f1368a888e7145112ab2a149 (it includes changes to the belos and muelu packages).

(I'm a Spack developer submitting this report on behalf of a user who submitted a patch to us)

### Steps to Reproduce
Attempt to build Trilinos 12.18.1 with apple-clang 8.0.0 on MacOS

**Comment by mhoemmen** [comment]
Do you really mean 12.8, or did you mean 12.18?  12.8 is quite old.

**Comment by scheibelp** [comment]
> Do you really mean 12.8, or did you mean 12.18?

I incorrectly stated Trilinos 12.8.1: I meant Trilinos 12.18.1

**Comment by mhoemmen** [comment]
@scheibelp I think you can just submit a PR to [the 12.18 branch](https://github.com/trilinos/Trilinos/tree/trilinos-release-12-18-branch).  Trilinos doesn't have tarball releases any more, as far as I know.  Thanks!
