### ISSUE TITLE
xSDK build error

### ISSUE THREAD

**Issue by jwillenbring** [trilinos/Trilinos#677]
error output:

[ 33%] Built target xsdkhypre
gmake[1]: Leaving directory `/jenkins/slave/workspace/Trilinos_xSDK_devel/installxSDK/xsdk/arch-linux2-c-debug/git.xsdktrilinos/build'In file included from /jenkins/slave/workspace/Trilinos_xSDK_devel/installxSDK/xsdk/arch-linux2-c-debug/git.xsdktrilinos/petsc/src/Tpetra_PETScAIJGraph.cpp:44:0:
/jenkins/slave/workspace/Trilinos_xSDK_devel/installxSDK/xsdk/arch-linux2-c-debug/git.xsdktrilinos/petsc/src/Tpetra_PETScAIJGraph.hpp:106:3: error: ‘RCP’ does not name a type
   RCP<const Comm> getComm() const {return comm_;};
   ^
/jenkins/slave/workspace/Trilinos_xSDK_devel/installxSDK/xsdk/arch-linux2-c-debug/git.xsdktrilinos/petsc/src/Tpetra_PETScAIJGraph.hpp:109:3: error: ‘RCP’ does not name a type
   RCP<Node> getNode() const { return rowMap_->getNode(); };
   ^
/jenkins/slave/workspace/Trilinos_xSDK_devel/installxSDK/xsdk/arch-linux2-c-debug/git.xsdktrilinos/petsc/src/Tpetra_PETScAIJGraph.hpp:112:3: error: ‘RCP’ does not name a type
   RCP<const Map<LO,GO,Node> > getRowMap() const { return rowMap_; };
   ^
/jenkins/slave/workspace/Trilinos_xSDK_devel/installxSDK/xsdk/arch-linux2-c-debug/git.xsdktrilinos/petsc/src/Tpetra_PETScAIJGraph.hpp:115:3: error: ‘RCP’ does not name a type
   RCP<const Map<LO,GO,Node> > getColMap() const { return colMap_; };
   ^
/jenkins/slave/workspace/Trilinos_xSDK_devel/installxSDK/xsdk/arch-linux2-c-debug/git.xsdktrilinos/petsc/src/Tpetra_PETScAIJGraph.hpp:118:3: error: ‘RCP’ does not name a type
   RCP<const Map<LO,GO,Node> > getDomainMap() const { return rowMap_; }; // TODO: domain and range map should not be the same
   ^
/jenkins/slave/workspace/Trilinos_xSDK_devel/installxSDK/xsdk/arch-linux2-c-debug/git.xsdktrilinos/petsc/src/Tpetra_PETScAIJGraph.hpp:121:3: error: ‘RCP’ does not name a type
   RCP<const Map<LO,GO,Node> > getRangeMap() const { return rowMap_; };
   ^

does anyone from @trilinos/tpetra or @trilinos/teuchos have ideas based on recent changes to Trilinos? This worked a couple weeks ago.

**Comment by bartlettroscoe** [comment]
I think this is due to a refactoring that @mhoemmen did to Tpetra recently cleaning out the Tpetra include files to improve build times.  I think that these xSDKTrilinos files just need to include "Teuchos_RCP.hpp" and all should be good.

**Comment by mhoemmen** [comment]
@amklinv told me she's got this.  Thanks!

**Comment by jwillenbring** [comment]
Thanks for the quick action on this @bartlettroscoe @mhoemmen @amklinv
