### ISSUE TITLE
STRUMPACK-Amesos2 Interface

### ISSUE THREAD

**Issue by keitat** [trilinos/Trilinos#6773]
STRUMPACK/ButterflyPack team at LBL are asking where their code should be interfaced to Trilinos. Originally, they are thinking about contributing to Amesos2, but the intended use is preconditioner. In this case, adding an interface to other Trilinos package sounds more reasonable. I need your advice!

STRUMPACK
https://github.com/pghysels/STRUMPACK
ButterflyPack
https://github.com/liuyangzhuan/ButterflyPACK

**Comment by mhoemmen** [comment]
@keitat What does "interfaced to Trilinos" mean?  Is the idea that Trilinos users would be able to use STRUMPACK through a Trilinos interface, or does STRUMPACK want to use Trilinos components in STRUMPACK?

**Comment by keitat** [comment]
I mean adding new capability to Trilinos to call these two packages for precondtioners.  It is somewhat similar to Amesos2, calling SuperLU.

**Comment by mhoemmen** [comment]
@keitat 
1. What does STRUMPACK take as input?  Does it accept a sparse matrix, just like the other solvers that Amesos2 makes available?
2. It looks like ButterflyPACK works on dense matrices.  That would make it not appropriate for Amesos2.
3. Would users want to use both of these libraries directly through Trilinos, or does one library just call the other?

**Comment by srajama1** [comment]
@keitat I am talking to the STRUMPACK and ButterflyPACK developers as well. Are you going to add this interface ? This came out of the speed dating session when I spoke to Pieter. Amesos2 is the best place for STRUMPACK, Adelus the new dense solver package that @vqd8a is writing is the best place for ButterflyPACK. Let us talk offline.

**Comment by keitat** [comment]
@srajama1  The issues is just STRUMPACK interface.  I will email to Peter and you to figure out how to proceed the work.

**Comment by srajama1** [comment]
@keitat ButterflPACK is what is needed. I don't know an use case for STRUMPACK yet.

**Comment by keitat** [comment]
Should we make another issue for ButterflyPACK and let's focus on STRUMPACK here.

**Comment by keitat** [comment]
Closing the issue until we start the development of STRUMPACK interface.
