### ISSUE TITLE
Trilinos linking errors on Ride/Waterman with CUDA KokkosNode

### ISSUE THREAD

**Issue by ikalash** [trilinos/Trilinos#6779]
We are getting Trilinos link errors in the Albany  nightlies on Ride/Waterman that started today.  The errors look as follows: 

```
tmpxft_000019c4_00000000-5_Teuchos_GlobalMPISession.cudafe1.cpp:(.text+0x71c): undefined reference to `MPI_Abort'
```
http://cdash.sandia.gov/CDash-2-3-0/viewBuildError.php?buildid=92948

**Comment by mhoemmen** [comment]
Could that be because of removal of deprecated functions in Teuchos?  Maybe the Dashboard builds need a "super-clean."

**Comment by ikalash** [comment]
What do you mean by super clean?  Everything gets wiped prior to the build starting so it’s always built from scratch.

**Comment by mhoemmen** [comment]
> Everything gets wiped prior to the build starting so it’s always built from scratch.

That's ... what I meant : - )  Then I have no idea, alas.

**Comment by ikalash** [comment]
Hmmm...  I did change to use the new nvcc_wrapper in Trilinos/packages/kokkos/bin a couple days ago.  Could this somehow be contributing to the issue?  Interestingly, despite the errors, it appears the Albany tests all run correctly.

**Comment by mhoemmen** [comment]
@ikalash Does Albany set `OMPI_CXX=nvcc_wrapper` in its builds?  @ndellingwood or @jjwilke  might remember something about that, though I think Nathan is taking a well-deserved rest today.

**Comment by ikalash** [comment]
@mhoemmen : we just set ``` "-DCMAKE_CXX_COMPILER:FILEPATH=${NVCC_WRAPPER}"``` when we configure Trilinos; we don't set an environment variables.  Should we be doing: ```export OMPI_CXX=/path/to/nvcc_wrapper```?

**Comment by mhoemmen** [comment]
I always do that -- I'm surprised you were able to make it work before without that.

**Comment by ikalash** [comment]
Hmmm, right.  Let me try adding it and see what happens.

**Comment by mhoemmen** [comment]
I actually didn't realize that it _could_ work without setting `OMPI_CXX`.  Perhaps it could work before, but something changed in Kokkos?

**Comment by jjwilke** [comment]
Probably TriBITS can be made to `find_package(MPI)` , in which case all the libraries and headers for MPI would be added regardless of whether you are using `mpicxx`. It's not something I've ever tried, though.

There are no changes to `nvcc_wrapper` that should have affected linking. I can try to reproduce.

**Comment by mhoemmen** [comment]
@jjwilke Are we still supposed to be setting `OMPI_CXX` as before?

**Comment by jjwilke** [comment]
Yes, `mpicxx` + setting `OMPI_CXX` to `nvcc_wrapper` is what we've been testing (and seems to be the main method in most of the Trilinos configure scripts).

**Comment by ikalash** [comment]
Just to follow up, we still see the issue even when setting the OMPI_CXX to nvcc_wrapper.  Even though there's an error, the executable seems to be OK and all the tests pass...  so I suppose we could punt on this for now.  It is somewhat of a mystery though...

**Comment by mhoemmen** [comment]
@ikalash Is it a new executable or does it just fail to link and leave the old executable in place?

**Comment by ikalash** [comment]
No, everything gets wiped and rebuilt from scratch each night.

**Comment by ikalash** [comment]
@jewatkins resolved this issue by modifying the nvcc_wrapper.
