### ISSUE TITLE
MueLu: Speed-up scaling of off-diagonal entries at region interfaces

### ISSUE THREAD

**Issue by mayrmt** [trilinos/Trilinos#6786]
## Enhancement
@trilinos/muelu 
@rstumin @lucbv @pohm01 

### Problem description

@rstumin reported that the step `MakeQuasiregionMatrices: 3 - Scale interface entries` during the transformation from a composite to a region operator takes considerably too much time. The reason is, that we don't use pre-computed interface data, but rather loop over every row in the composite operator and figure out, if it is associated with a region interface. Since we do this on the fine level, most nodes are not on region interfaces, so looping over all rows and trying to identify an interface is wasted effort on most rows.

### Possible solution

However, the region driver already knows about the region interfaces, so we can reuse that information to only loop over rows that are known to be associated with an interface. This will skip most of the rows in the composite operator and, thus, speed-up the scaling operation by far.

For the structured/unstructured scenario, the driver stores some interface data in a `Teuchos::RCP<Teuchos::ParameterList> interfaceParams`. I tried the following in a quick and dirty way:
1. Fill that list also in case of a fully structured problem.
1. Pass that list to `MakeQuasiRegionMatrices()`
1. Use interface info to only loop over interface-associated rows.

I tried it for a 1-DOF-per-node problem on 2 MPI ranks with a 500x500 mesh. The "old" way spends roughly 2.8 seconds to scale the interface-related off-diagonal entries, while the "new" path just requires 0.008 seconds. This discrepancy drastically grows with larger meshes.

Edit: On a 2000x2000 mesh on 2 MPI ranks, the numbers are 50 secs vs. 0.03 secs.

I'll look into this in more detail and try to clean it up, so that we can replace the current mechanism. However, there are some issues to be resolved with multiple DOFs per node. Though, this should be feasible. Just a matter of index counting...

**Comment by mayrmt** [comment]
I discussed this with @rstumin, @lucbv, and @pohm01 offline. We do not address this right now, as it is not a current bottleneck, but let's keep this in mind for future usage within application codes.

**Comment by mayrmt** [comment]
@lucbv I had a look at the driver. In preparation for the fast MatVec, we pre-compute interface data (GIDs and LIDs) of duplicated DOFs on the interface prior to the `MakeQausiRegionMatrices()` call. So, interface information is available at least in some form. We just need to figure out, how to re-use this data inside `MakeQuasiRegionMatrices()` in order to only loop over the interface rows when "splitting" the matrix along the region interfaces.

**Comment by lucbv** [comment]
OK, I am planning on working on this tomorrow morning ahead of the meeting, maybe tonight depending on how the rest of my to-do list makes progress. I do not expect this to be a huge difficulty it is probably just a bit tedious...
My guess is that once we have imported the data correctly with `MakeQuasiRegionMatrices()` we can simply restrict the loop to all the dofs listed for the `fastMatVec()` we might also need `regionsPerGIDWithGhosts ` or some other scaling information.

**Comment by mayrmt** [comment]
See https://github.com/trilinos/Trilinos/pull/8506#issuecomment-786433167 for some details on improved timings.

**Comment by mayrmt** [comment]
@lucbv and I fixed this via PR #8506. Closing.
