### ISSUE TITLE
Panzer: 1-ring support in worksets

### ISSUE THREAD

**Issue by rppawlo** [trilinos/Trilinos#679]
Design and implement data structures for 1-ring support in worksets for DG capability

**Comment by eric-c-cyr** [comment]
This is mostly done I think at this point. Though I wouldn't say the capability would extend naturally to the Phalanx evaluator sides of Panzer. @seamill do you agree? Can we close?

**Comment by rppawlo** [comment]
The intention of this ticket was for DG support. This is done, however we don't have true full one-ring support. We have the one-ring for faces of owned cells which is exactly what DG needs. Going to close this ticket. Will open a new one for the workset refactor for full one ring support.
