### ISSUE TITLE
Compile issue in test for Issue 46

### ISSUE THREAD

**Issue by bmpersc** [trilinos/Trilinos#680]
There is a compile error when building with gcc 4.7.2 in one test. The issue is template is used in a place where the compiler believes it shouldn't be. This does seem to be only happening on gcc 4.7.2. You can view the error at:

https://testing.sandia.gov/cdash/viewBuildError.php?buildid=2578629

**Comment by mhoemmen** [comment]
@bmpersc I've been having trouble getting the GCC 4.7.2 SEMS module to work with my check-in test script, so I haven't been exercising that compiler lately.  Let me take a look at the code.  Thanks for letting me know!

**Comment by mhoemmen** [comment]
I just implemented a work-around for GCC 4.7.2.  Running check-in tests now.

**Comment by mhoemmen** [comment]
Just pushed a fix.  Thanks @bmpersc !
