### ISSUE TITLE
TpetraCore_gemm_m_eq_13_MPI_1 timing out in ATDM Trilinos shared_opt and fpic_opt builds on 'waterman' starting 2020-02-04

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#6804]
CC: @trilinos/tpetra , @kddevin  (Trilinos Data Services Product Lead), @bartlettroscoe

<Checklist>
<???: Add label "client: ATDM">
<???: Add label "ATDM Sev: Blocker" (by default but could be other "ATDM Sev: XXX")>
<???: Add label "type: bug"?>
<???: Add label for affected packages (e.g. "pkg: MueLu", "pkg: Tpetra", "pkg: Kokkos", etc.)>
<???: Add label "PA: ???Project Area???" (e.g. "PA: Linear Solvers", "PA: Data Services")>
<???: Add milestone "Initial cleanup of new ATDM ..." or "Keep promoted ATDM ...">
<???: Once GitHub Issue is created, add entries for tests to TrilinosATDMStatus/*.csv files>

## Next Action Status

Test finishes and passes just fine when run by itself.  Next: @bartlettroscoe will set the property `RUN_SERIAL` for this test in all CUDA builds ...

## Description

As shown in [this query](https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&begin=2020-01-11&end=2020-02-09&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-waterman_cuda-9.2_shared_opt&field2=testname&compare2=61&value2=TpetraCore_gemm_m_eq_13_MPI_1&field3=site&compare3=61&value3=waterman) the test:

* `TpetraCore_gemm_m_eq_13_MPI_1`

in the build:

* `Trilinos-atdm-waterman_cuda-9.2_shared_opt`

started timing out on testing day 2020-02-04, the day after the Kokkos 2.99 update.

That query showed the test runtime was pretty erratic, getting as high as 9m28s but was also as low as 1m2s other days.

This suggests that KokkosKernels GEMM may have had a serious performance regression on this platform for this upgrade?

## Current Status on CDash

* [TpetraCore_gemm_m_eq_13_MPI_1 in build Trilinos-atdm-waterman_cuda-9.2_shared_opt last 30 days](https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&begin=30%20days%20ago&end=now&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-waterman_cuda-9.2_shared_opt&field2=testname&compare2=61&value2=TpetraCore_gemm_m_eq_13_MPI_1&field3=site&compare3=61&value3=waterman)

## Steps to Reproduce

One should be able to reproduce this failure on the machine 'waterman' as described in:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md

More specifically, the commands given for the system 'waterman' are provided at:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#waterman
The exact commands to reproduce this issue should be:

```
$ cd <some_build_dir>/

$ source $TRILINOS_DIR/cmake/std/atdm/load-env.sh \
    Trilinos-atdm-waterman_cuda-9.2_shared_opt

$ cmake \
 -GNinja \
 -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
 -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_ALL_PACKAGES=ON \
 $TRILINOS_DIR

$ make NP=16

$ bsub -x -Is -n 20  ctest -j4
```

**Comment by srajama1** [comment]
@seheracer

**Comment by mhoemmen** [comment]
@trilinos/tpetra This test normally takes forever -- I usually exclude it from debug tests during development.  Perhaps we should reduce the problem size.

**Comment by ndellingwood** [comment]
Doesn't `opt` indicate this is an optimized build and not a debug build?

**Comment by ndellingwood** [comment]
In any case, using the reproducer instructions posted I just tested with Trilinos SHA 8ff46051ea6a31de9719309447df0065287bd619
and these are the results I'm seeing for 5 repeat runs of the test:

```bash
bash-4.2$ for run in {1..5}; do echo $run; ctest -R TpetraCore_gemm_m_eq_13_MPI_1; done
1
Test project /ascldap/users/ndellin/KokkosReleaseDebugging/tpetra-release
    Start 26: TpetraCore_gemm_m_eq_13_MPI_1
1/1 Test #26: TpetraCore_gemm_m_eq_13_MPI_1 ....   Passed   11.83 sec

100% tests passed, 0 tests failed out of 1

Subproject Time Summary:
Tpetra    =  11.83 sec*proc (1 test)

Total Test time (real) =  12.03 sec
2
Test project /ascldap/users/ndellin/KokkosReleaseDebugging/tpetra-release
    Start 26: TpetraCore_gemm_m_eq_13_MPI_1
1/1 Test #26: TpetraCore_gemm_m_eq_13_MPI_1 ....   Passed   11.68 sec

100% tests passed, 0 tests failed out of 1

Subproject Time Summary:
Tpetra    =  11.68 sec*proc (1 test)

Total Test time (real) =  11.86 sec
3
Test project /ascldap/users/ndellin/KokkosReleaseDebugging/tpetra-release
    Start 26: TpetraCore_gemm_m_eq_13_MPI_1
1/1 Test #26: TpetraCore_gemm_m_eq_13_MPI_1 ....   Passed   11.70 sec

100% tests passed, 0 tests failed out of 1

Subproject Time Summary:
Tpetra    =  11.70 sec*proc (1 test)

Total Test time (real) =  11.86 sec
4
Test project /ascldap/users/ndellin/KokkosReleaseDebugging/tpetra-release
    Start 26: TpetraCore_gemm_m_eq_13_MPI_1
1/1 Test #26: TpetraCore_gemm_m_eq_13_MPI_1 ....   Passed   11.64 sec

100% tests passed, 0 tests failed out of 1

Subproject Time Summary:
Tpetra    =  11.64 sec*proc (1 test)

Total Test time (real) =  11.80 sec
5
Test project /ascldap/users/ndellin/KokkosReleaseDebugging/tpetra-release
    Start 26: TpetraCore_gemm_m_eq_13_MPI_1
1/1 Test #26: TpetraCore_gemm_m_eq_13_MPI_1 ....   Passed   11.82 sec

100% tests passed, 0 tests failed out of 1

Subproject Time Summary:
Tpetra    =  11.82 sec*proc (1 test)

Total Test time (real) =  11.97 sec
```

Around 12 seconds

**Comment by ndellingwood** [comment]
@bartlettroscoe @trilinos/tpetra @mhoemmen 
If I run `ctest -j2` from `packages/tpetra/core/test/Blas` (where the test disputed in this issue is located) I see the following results:

```bash
bash-4.2$ ctest -j2
Test project /ascldap/users/ndellin/KokkosReleaseDebugging/tpetra-release/packages/tpetra/core/test/Blas
    Start 1: TpetraCore_gemv_MPI_1
    Start 2: TpetraCore_gemm_m_eq_1_MPI_1
1/5 Test #1: TpetraCore_gemv_MPI_1 ............   Passed    6.24 sec
    Start 3: TpetraCore_gemm_m_eq_2_MPI_1
2/5 Test #2: TpetraCore_gemm_m_eq_1_MPI_1 .....   Passed   51.05 sec
    Start 4: TpetraCore_gemm_m_eq_5_MPI_1
3/5 Test #3: TpetraCore_gemm_m_eq_2_MPI_1 .....   Passed   51.00 sec
    Start 5: TpetraCore_gemm_m_eq_13_MPI_1
4/5 Test #4: TpetraCore_gemm_m_eq_5_MPI_1 .....   Passed   51.48 sec
5/5 Test #5: TpetraCore_gemm_m_eq_13_MPI_1 ....   Passed   47.39 sec

100% tests passed, 0 tests failed out of 5

Label Time Summary:
Tpetra    = 207.16 sec*proc (5 tests)

Total Test time (real) = 104.64 sec
```

However, if I run the gemm tests individually this is what I see:
```bash
bash-4.2$ ctest -R TpetraCore_gemm_m_eq_1_MPI_1
Test project /ascldap/users/ndellin/KokkosReleaseDebugging/tpetra-release/packages/tpetra/core/test/Blas
    Start 2: TpetraCore_gemm_m_eq_1_MPI_1
1/1 Test #2: TpetraCore_gemm_m_eq_1_MPI_1 .....   Passed   11.63 sec

100% tests passed, 0 tests failed out of 1

Label Time Summary:
Tpetra    =  11.63 sec*proc (1 test)

Total Test time (real) =  11.64 sec
bash-4.2$ ctest -R TpetraCore_gemm_m_eq_2_MPI_1
Test project /ascldap/users/ndellin/KokkosReleaseDebugging/tpetra-release/packages/tpetra/core/test/Blas
    Start 3: TpetraCore_gemm_m_eq_2_MPI_1
1/1 Test #3: TpetraCore_gemm_m_eq_2_MPI_1 .....   Passed   11.55 sec

100% tests passed, 0 tests failed out of 1

Label Time Summary:
Tpetra    =  11.55 sec*proc (1 test)

Total Test time (real) =  11.56 sec
bash-4.2$ ctest -R TpetraCore_gemm_m_eq_5_MPI_1
Test project /ascldap/users/ndellin/KokkosReleaseDebugging/tpetra-release/packages/tpetra/core/test/Blas
    Start 4: TpetraCore_gemm_m_eq_5_MPI_1
1/1 Test #4: TpetraCore_gemm_m_eq_5_MPI_1 .....   Passed   11.71 sec

100% tests passed, 0 tests failed out of 1

Label Time Summary:
Tpetra    =  11.71 sec*proc (1 test)

Total Test time (real) =  11.71 sec
bash-4.2$ ctest -R TpetraCore_gemm_m_eq_13_MPI_1
Test project /ascldap/users/ndellin/KokkosReleaseDebugging/tpetra-release/packages/tpetra/core/test/Blas
    Start 5: TpetraCore_gemm_m_eq_13_MPI_1
1/1 Test #5: TpetraCore_gemm_m_eq_13_MPI_1 ....   Passed   11.61 sec

100% tests passed, 0 tests failed out of 1

Label Time Summary:
Tpetra    =  11.61 sec*proc (1 test)

Total Test time (real) =  11.62 sec
bash-4.2$ 

```

These timeouts are due to running `ctest` with `j > 1`

**Comment by ndellingwood** [comment]
Added data - if I run `ctest -j8` from my build directory (only Tpetra tests enabled), I see these times for the gemm tests:

```bash
106/229 Test  #26: TpetraCore_gemm_m_eq_13_MPI_1 ...............................................................   Passed  143.01 sec
110/229 Test  #23: TpetraCore_gemm_m_eq_1_MPI_1 ................................................................   Passed  145.87 sec
111/229 Test  #24: TpetraCore_gemm_m_eq_2_MPI_1 ................................................................   Passed  145.65 sec
112/229 Test  #25: TpetraCore_gemm_m_eq_5_MPI_1 ................................................................   Passed  144.70 sec
```

**Comment by bartlettroscoe** [comment]
@ndellingwood, this is likely then due to loading issues on the GPU running 4 single-process tests at a time.  I updated the reproducability instructions for what actually happens on the machine:

```
$ cd <some_build_dir>/

$ source $TRILINOS_DIR/cmake/std/atdm/load-env.sh \
    Trilinos-atdm-waterman_cuda-9.2_shared_opt

$ cmake \
 -GNinja \
 -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
 -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_ALL_PACKAGES=ON \
 $TRILINOS_DIR

$ make NP=16

$ bsub -x -Is -n 20  ctest -j4
```

If you look at the runtimes in [this query](https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&begin=2020-01-11&end=2020-02-09&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-waterman_cuda-9.2_shared_opt&field2=testname&compare2=61&value2=TpetraCore_gemm_m_eq_13_MPI_1&field3=site&compare3=61&value3=waterman), they are incredibly erratic before 2020-02-04.  Before the Kokkos 2.99 upgrade, they were as high as 9m44s some days and as low as 1m other days (just in the last 30 days).

Note that if you look at the static libraries build for the otherwise **identical** build `Trilinos-atdm-waterman-cuda-9.2-opt` on CDash in [this query](https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&begin=2020-01-11&end=2020-02-09&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-waterman-cuda-9.2-opt&field2=testname&compare2=61&value2=TpetraCore_gemm_m_eq_13_MPI_1&field3=site&compare3=61&value3=waterman), the max runtime over the last 30 days was 4m46s and the min runtime was 18s!

If you look at all of the waterman builds over the last 30 days in [this query](https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&begin=2020-01-11&end=2020-02-09&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-waterman&field2=testname&compare2=61&value2=TpetraCore_gemm_m_eq_13_MPI_1), you can see that the there are also several timeouts in the build:

* `Trilinos-atdm-waterman_cuda-9.2_fpic_static_opt`

So, this test seems to run fine in the builds:

* `Trilinos-atdm-waterman-cuda-9.2-debug`
* `Trilinos-atdm-waterman-cuda-9.2-opt`
* `Trilinos-atdm-waterman-cuda-9.2-rdc-release-debug`
* `Trilinos-atdm-waterman-cuda-9.2-release-debug`

So there is something about shared libs or -fPIC and running multiple kernels run on the GPU on 'waterman' just seems very erratic.   

Given that this test runs fine in debug and optimized (and RDC) CUDA builds with static libs on 'waterman' and just has problems in shared and -fPIC builds, I would just disable this test in the builds:

* `Trilinos-atdm-waterman_cuda-9.2_shared_opt`
* `Trilinos-atdm-waterman_cuda-9.2_fpic_static_opt`

and be done this this.

A lot can be learned by looking at results on CDash.

**Comment by mhoemmen** [comment]
Please don't disable tests quite just yet -- let's just look into making the problems smaller.

**Comment by bartlettroscoe** [comment]
> Please don't disable tests quite just yet -- let's just look into making the problems smaller.

@mhoemmen, no need to disable any individual test.  We have a system where we can tolerate quite a few failing and timing out tests and it does not damage our ability to detect new failing tests.

So go ahead and try to make it faster if you want.  We just should not let it timeout for weeks and months (like often happens).

**Comment by mhoemmen** [comment]
Huh, the problems aren't very large in this test.  The max dimensions are 13,13,13.  There are a lot of combinations, but we do need to test all of them.  We could split up the test further.  I did some investigation and noticed that on a CPU in a debug build, the `Scalar=long long` case is MUCH slower than the remaining cases.  (We need that because `Tpetra::MultiVector<GlobalOrdinal, ...>` needs to build.)  I'll dig a bit more.

**Comment by rppawlo** [comment]
@mhoemmen - check out this comment: https://github.com/trilinos/Trilinos/issues/6801#issuecomment-584866511

Might be that launching multiple gemm tests together that hit the same gpu is the issue.

**Comment by mhoemmen** [comment]
@rppawlo On a CPU, even those `Scalar=long long` tests only take 22s in a debug build.  It's like only that long because `Teuchos::BLAS` resorts to a default implementation in that case.

**Comment by bartlettroscoe** [comment]
Waterman got moved from the SRN to the SON as the machine 'weaver' many months ago.  Closing this as "wontfix".
