### ISSUE TITLE
MueLu, STK, and Zoltan2 builds broken in all openmp builds starting 2020-02-11

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#6809]
CC: @trilinos/kokkos, @trilinos/muelu, @trilinos/stk, @trilinos/zoltan2, @kddevin (Trilinos Data Services Product Lead), @srajama1 (Trilinos Linear Solvers Product Lead)

As shown in [this query of builds so far today 2020-02-11](https://testing-dev.sandia.gov/cdash/index.php?project=Trilinos&date=2020-02-11&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-&field2=builderrors&compare2=43&value2=0), all of the openmp builds so far:

* `Trilinos-atdm-cee-rhel6_intel-18.0.2_mpich2-3.2_openmp_static_opt`
* `Trilinos-atdm-cts1-intel-19.0.5_openmpi-4.0.1_openmp_static_dbg`
* `Trilinos-atdm-cts1-intel-19.0.5_openmpi-4.0.1_openmp_static_opt`
* `Trilinos-atdm-mutrino-intel-opt-openmp-HSW`
* `Trilinos-atdm-mutrino-intel-opt-openmp-KNL-panzer`
* `Trilinos-atdm-sems-rhel6-gnu-7.2.0-openmp-complex-shared-release-debug`
* `Trilinos-atdm-sems-rhel6-intel-17.0.1-openmp-release`
* `Trilinos-atdm-sems-rhel7-gnu-7.2.0-openmp-complex-shared-release-debug`
* `Trilinos-atdm-sems-rhel7-intel-18.0.5-openmp-complex-shared-release-debug`
* `Trilinos-atdm-sems-rhel7-intel-18.0.5-openmp-shared-debug`
* `Trilinos-atdm-sems-rhel7-intel-18.0.5-openmp-shared-release-debug`
* `Trilinos-atdm-white-ride-gnu-7.2.0-openmp-debug`
* `Trilinos-atdm-white-ride-gnu-7.2.0-openmp-release`

show build errors.

As shown [here](https://testing-dev.sandia.gov/cdash/index.php?project=Trilinos&parentid=5228296&filtercount=1&showfilters=1&field1=builderrors&compare1=43&value1=0&filtercombine=and) the packages `MueLu`, `STK`, and `Zoltan2` all show build errors.

One of the build errors, for example, shown [here](https://testing-dev.sandia.gov/cdash/viewBuildError.php?buildid=5228303) shows:

```
/scratch/rabartl/Trilinos.base/NightlyBuilds/Trilinos-atdm-cee-rhel6_intel-18.0.2_mpich2-3.2_openmp_static_opt/SRC_AND_BUILD/Trilinos/packages/zoltan2/src/algorithms/partition/Zoltan2_AlgMultiJagged.hpp(4942): error: class "Kokkos::OpenMP" has no member "impl_max_hardware_threads"
    const int num_threads = Kokkos::OpenMP::impl_max_hardware_threads();
```

This looks like this occurred due to a violation of the [additive test assumption of branches](https://docs.google.com/document/d/1uVQYI2cmNx09fDkHDA136yqDTqayhxqfvjFiuUue7wo/edit#bookmark=id.d1jneh8ubsyn) in PR testing last night between PRs #6798  and #6778 that resulted in the post-merge CI failures shown in:

* https://testing-dev.sandia.gov/cdash/index.php?project=Trilinos&parentid=5229295

and the email that fired off this morning shown below.

It looks like PR #6778 added new code that was changed by PR #6798.  This is the classic problem with asynchronous CI testing :-(

----

From: admin@cdash.org <admin@cdash.org> 
Sent: Tuesday, February 11, 2020 7:16 AM
To: Bartlett, Roscoe A <rabartl@sandia.gov>
Subject: [EXTERNAL] FAILED (b=50): Trilinos - Linux-GCC-4.8.4-MPI_RELEASE_DEBUG_SHARED_PT_OPENMP_CI - Continuous

A submission to CDash for the project Trilinos has errors. You have been identified as one of the authors who have checked in changes that are part of this submission or you are listed in the default contact list.

Details on the submission can be found at https://testing.sandia.gov/cdash/buildSummary.php?buildid=6380791.

Project: Trilinos
Site: ceerws1113
Build Name: Linux-GCC-4.8.4-MPI_RELEASE_DEBUG_SHARED_PT_OPENMP_CI
Build Time: 2020-02-11 10:19:09
Type: Continuous
Total Errors: 50

*Errors* (first 5 included)
packages/muelu/src/Utils/ExplicitInstantiation/MueLu_Zoltan2Interface.cpp (https://testing.sandia.gov/cdash/viewBuildError.php?type=0&buildid=6380810)
In file included from /scratch/rabartl/Trilinos.base/SEMSCIBuild/Trilinos/packages/zoltan2/src/algorithms/partition/Zoltan2_PartitioningAlgorithms.hpp:54:0,
                 from /scratch/rabartl/Trilinos.base/SEMSCIBuild/Trilinos/packages/zoltan2/src/pro
packages/stk/stk_unit_tests/stk_balance/UnitTestIncrementalRebalance.cpp (https://testing.sandia.gov/cdash/viewBuildError.php?type=0&buildid=6380820)
In file included from /scratch/rabartl/Trilinos.base/SEMSCIBuild/Trilinos/packages/zoltan2/src/algorithms/partition/Zoltan2_PartitioningAlgorithms.hpp:54:0,
                 from /scratch/rabartl/Trilinos.base/SEMSCIBuild/Trilinos/packages/zoltan2/src/pro
packages/stk/stk_unit_tests/stk_balance/UnitTestBoundingBoxSearch.cpp (https://testing.sandia.gov/cdash/viewBuildError.php?type=0&buildid=6380820)
In file included from /scratch/rabartl/Trilinos.base/SEMSCIBuild/Trilinos/packages/zoltan2/src/algorithms/partition/Zoltan2_PartitioningAlgorithms.hpp:54:0,
                 from /scratch/rabartl/Trilinos.base/SEMSCIBuild/Trilinos/packages/zoltan2/src/pro
packages/stk/stk_unit_tests/stk_balance/UnitTestLearningZoltan2.cpp (https://testing.sandia.gov/cdash/viewBuildError.php?type=0&buildid=6380820)
In file included from /scratch/rabartl/Trilinos.base/SEMSCIBuild/Trilinos/packages/zoltan2/src/algorithms/partition/Zoltan2_PartitioningAlgorithms.hpp:54:0,
                 from /scratch/rabartl/Trilinos.base/SEMSCIBuild/Trilinos/packages/zoltan2/src/pro
packages/stk/stk_balance/stk_balance/fixSplitCoincidentElements.cpp (https://testing.sandia.gov/cdash/viewBuildError.php?type=0&buildid=6380820)
In file included from /scratch/rabartl/Trilinos.base/SEMSCIBuild/Trilinos/packages/zoltan2/src/algorithms/partition/Zoltan2_PartitioningAlgorithms.hpp:54:0,
                 from /scratch/rabartl/Trilinos.base/SEMSCIBuild/Trilinos/packages/zoltan2/src/pro

-CDash on testing.sandia.gov

**Comment by MicheldeMessieres** [comment]
@bartlettroscoe I'll open a PR shortly to clear this.

**Comment by MicheldeMessieres** [comment]
@kddevin @bartlettroscoe I put up PR #6810 to quick fix this issue. Will follow up later to resolve it properly.
