### ISSUE TITLE
Zoltan2: build error on Blake with OpenMP

### ISSUE THREAD

**Issue by ikalash** [trilinos/Trilinos#6816]
Our blake Trilinos build with an OpenMP Kokkos node failed with the following error: 

```
/.../repos/Trilinos/packages/zoltan2/src/algorithms/partition/Zoltan2_AlgMultiJagged.hpp(9053): error: namespace "Kokkos" has no member "Serial"
```
https://my.cdash.org/viewBuildError.php?buildid=1772926

Could you please look into this?  

@trilinos/zoltan2

**Comment by kddevin** [comment]
@MicheldeMessieres

**Comment by MicheldeMessieres** [comment]
@ikalash @kddevin I'll try to resolve this evening. I had tested with Serial + OpenMP enabled and forgotten I can't assume Kokkos::Serial is available. I guess auto tester doesn't have an OpenMP only test build.

**Comment by ikalash** [comment]
Sounds good.  I didn't realize there is not an OpenMP auto tester build.  Would be worth adding probably....

**Comment by MicheldeMessieres** [comment]
@ikalash There is OpenMP, but I think you have OpenMP enabled but Serial disabled, while the auto tester always has OpenMP + Serial enabled. I think I need to change Kokkos::Serial usage to Kokkos::HostSpace. Just checking a build now.

**Comment by MicheldeMessieres** [comment]
@ikalash Can you give me the config for the build? I don't see that I can read it from the cdash. I was trying to disable serial but getting other errors so I think you are doing something different. Thanks.

**Comment by ikalash** [comment]
Sure, they can be found here for our OpenMP build on blake, where the issue shows up: 
https://github.com/SNLComputation/Albany/blob/master/doc/dashboards/blake.sandia.gov/ctest_nightly.cmake.frag#L581-L701

**Comment by mhoemmen** [comment]
Why disable `Kokkos::Serial`?  If you enable OpenMP, Trilinos will use it as Tpetra's default.

**Comment by ikalash** [comment]
Good question.  I don't know why we have that...  my guess is it was recommended by someone at some point, or set by someone who created the original blake OpenMP input file.  I just checked my other OpenMP build on my workstation camobap and it seems both ```Kokkos::Serial``` and ```Kokkos::OpenMP``` are on....  hmmm that doesn't seem right....

**Comment by MicheldeMessieres** [comment]
@ikalash @kddevin I should fix these anyways for consistency. #6819 will resolve it.

**Comment by mhoemmen** [comment]
@MicheldeMessieres wrote:
> I think I need to change Kokkos::Serial usage to Kokkos::HostSpace.

If you want an execution space, you can write `Kokkos::DefaultHostExecutionSpace`.  It might be Serial or OpenMP or something else, depending on build settings, but it's always enabled.

**Comment by ikalash** [comment]
I have verified that this issue has been resolved.  Thanks!
