### ISSUE TITLE
Kokkos:  Configure fails on C++11 standard for Nvidia/CUDA using nvcc_wrapper

### ISSUE THREAD

**Issue by rrdrake** [trilinos/Trilinos#6817]
## Bug Report
@trilinos/kokkos

I am trying to build Trilinos for GPUs using the nvcc_wrapper, but get a configure error
```
-- Using -std=c++11 for C++11 standard as feature
CMake Error at packages/kokkos/cmake/kokkos_test_cxx_std.cmake:39 (MESSAGE):
  Compiler NVIDIA should support cxx_std_11, but CMake reports feature not
  supported
Call Stack (most recent call first):
  packages/kokkos/cmake/kokkos_test_cxx_std.cmake:54 (kokkos_set_cxx_standard_feature)
  packages/kokkos/cmake/kokkos_tribits.cmake:172 (INCLUDE)
  packages/kokkos/CMakeLists.txt:146 (KOKKOS_SETUP_BUILD_ENVIRONMENT)
```
This is with
```
Currently Loaded Modulefiles:
  1) sntools/master                 4) sierra-cmake/3.12.2            7) sierra-devel/nvidia
  2) sierra-python/2.7              5) sierra-compiler/nvidia/10.1.243
  3) sierra-git/2.6.1               6) sierra-mpi/openmpi/4.0.2
```
and
```
ascicgpu24% g++ --version
g++ (GCC) 7.2.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

ascicgpu24% nvcc_wrapper --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243
```
The configure log and out & err files are attached.

This used to work two or so weeks ago.  Clark Dohrmann is also seeing this error.

[trilinos_configure.log](https://github.com/trilinos/Trilinos/files/4189836/trilinos_configure.log)
[CMakeOutput.log](https://github.com/trilinos/Trilinos/files/4189839/CMakeOutput.log)
[CMakeError.log](https://github.com/trilinos/Trilinos/files/4189840/CMakeError.log)

**Comment by ndellingwood** [comment]
@rrdrake how are you setting your environment or configure to use `nvcc_wrapper` (I couldn't find anything in the posted logs)? If it is not using the copy in `Trilinos/packages/bin/nvcc_wrapper` then the `nvcc_wrapper` will need to be updated to be compatible with changes in the kokkos 2.9.99 release.

**Comment by rrdrake** [comment]
Good question, we are using OpenMPI and set `OMPI_CXX` to the `nvcc_wrapper` path.  So mpicxx ends up using the wrapper.

We are using a copy of `nvcc_wrapper` - I will try pulling a new one from `Trilinos/packages/kokkos/bin`.

**Comment by rrdrake** [comment]
Using the new `nvcc_wrapper` solved the configure problems.  Thank you.
