### ISSUE TITLE
STK_search boost error

### ISSUE THREAD

**Issue by spdomin** [trilinos/Trilinos#6828]
## Bug Report
@trilinos/STK

### Description
@alanw0,  it seems that I can not win with this STK Boost code churn. See below. 

Good: Trilinos/develop SHA1: 897a16bdbdafc6e3b70169376ffdb2214d7a8fa0
Bad: Trilinos/develop SHA1: fce866ee57ea7705b5cb84460bf42087ca26cf4b

In file included from /home/spdomin/gitHubWork/scratch_build/packages/Trilinos/packages/stk/stk_search/stk_search/CoarseSearchBoostRTree.hpp:40,
                 from /home/spdomin/gitHubWork/scratch_build/packages/Trilinos/packages/stk/stk_search/stk_search/CoarseSearch.hpp:43,
                 from /home/spdomin/gitHubWork/scratch_build/packages/Trilinos/packages/stk/stk_transfer/stk_transfer/copy_by_id/SearchByIdGeometric.cpp:38:
/home/spdomin/gitHubWork/scratch_build/packages/Trilinos/packages/stk/stk_search/stk_search/BoostRTreeInterface.hpp:14:10: fatal error: boost/geometry.hpp: No such file or directory
 #include <boost/geometry.hpp>
          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [packages/stk/stk_transfer/stk_transfer/CMakeFiles/stk_transfer_impl.dir/copy_by_id/SearchByIdGeometric.cpp.o] Error 1
make[1]: *** [packages/stk/stk_transfer/stk_transfer/CMakeFiles/stk_transfer_impl.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

### Steps to Reproduce
Trilinos config: https://github.com/NaluCFD/Nalu/blob/master/build/do-configTrilinos_release

**Comment by alanw0** [comment]
@spdomin thanks for posting your do-config file showing your cmake options. It looks like you are not enabling boost. (You are enabling boostlib, which is no longer needed.) Recall this comment from your previous issue:
https://github.com/trilinos/Trilinos/issues/6740#issuecomment-582130546

**Comment by spdomin** [comment]
Why does STK_Search not automatically activate this lib?

**Comment by spdomin** [comment]
Strange, in my last config:

-- Setting TPL_ENABLE_Boost=ON because it is required by the enabled package STKSearch

**Comment by alanw0** [comment]
Hmm. So it looks like in your last config it was automatically turning it on. I didn't know we could automatically turn on boost, I was thinking I needed to automatically turn off stk-search if boost wasn't enabled by the user. I'm going to have to ramp up my (or the team's) cmake/tribits expertise.

**Comment by spdomin** [comment]
Yes, I need that expertise as well... For example,

-DNetCDF_ROOT:PATH=${netcdf_install_dir} \
-DHDF5_ROOT:PATH=${hdf_install_dir} \
-DPNetCDF_ROOT:PATH=${pnetcdf_install_dir} \
-DZlib_ROOT:PATH=${z_install_dir} \
**-DBoost_ROOT:PATH=${boost_install_dir} \**

Resulted in:

  Manually-specified variables were not used by the project:

    Boost_ROOT
    Zlib_ROOT

**Comment by alanw0** [comment]
That is puzzling. It seems like Boost_ROOT should have been used by either enabling BoostLib or Boost.

**Comment by spdomin** [comment]
I am bisecting by attempts based on the config output... Let me have a few tens-of-minutes:)

**Comment by spdomin** [comment]
I suppose I need help from a (just throwing out names), @bartlettroscoe or a @mhoemmen 

In my Trilinos Config file, I have:

-DTPL_ENABLE_SuperLU=ON \
  -DSuperLU_INCLUDE_DIRS:PATH=$superlu_inc_dir \
  -DSuperLU_LIBRARY_DIRS:PATH=$superlu_lib_dir \
-DTPL_ENABLE_Boost:BOOL=ON \
  -DBoost_INCLUDE_DIRS:PATH=$boost_inc_dir \
  -DBoost_LIBRARY_DIRS:PATH=$boost_lib_dir \

The config shows a successful SuperLU find:

Processing enabled TPL: SuperLU (enabled explicitly, disable with -DTPL_ENABLE_SuperLU=OFF)
-- SuperLU_LIBRARY_NAMES='superlu superlu_3.0 superlu_4.0 superlu_4.1 superlu_4.2 superlu_4.3 superlu_5.0 superlu_5.1.1 superlu_5.2.1'
-- Searching for libs in SuperLU_LIBRARY_DIRS='/ascldap/users/spdomin/gitHubWork/scratch_build/install/gcc8.3.0/SuperLU/4.3/lib'
-- Searching for a lib in the set "superlu superlu_3.0 superlu_4.0 superlu_4.1 superlu_4.2 superlu_4.3 superlu_5.0 superlu_5.1.1 superlu_5.2.1":
--   Searching for lib 'superlu' ...
--   Searching for lib 'superlu_3.0' ...
--   Searching for lib 'superlu_4.0' ...
--   Searching for lib 'superlu_4.1' ...
--   Searching for lib 'superlu_4.2' ...
--   Searching for lib 'superlu_4.3' ...
--     Found lib '/ascldap/users/spdomin/gitHubWork/scratch_build/install/gcc8.3.0/SuperLU/4.3/lib/libsuperlu_4.3.a'
-- TPL_SuperLU_LIBRARIES='/ascldap/users/spdomin/gitHubWork/scratch_build/install/gcc8.3.0/SuperLU/4.3/lib/libsuperlu_4.3.a'
-- Searching for headers in SuperLU_INCLUDE_DIRS='/ascldap/users/spdomin/gitHubWork/scratch_build/install/gcc8.3.0/SuperLU/4.3/include'

However, for my boost find:

Processing enabled TPL: Boost (enabled explicitly, disable with -DTPL_ENABLE_Boost=OFF)
-- Searching for headers in Boost_INCLUDE_DIRS=''
-- Searching for a header file in the set "boost/version.hpp":
--   Searching for header 'boost/version.hpp' ...
--     Found header '/usr/include/boost/version.hpp'
-- Searching for a header file in the set "boost/mpl/at.hpp":
--   Searching for header 'boost/mpl/at.hpp' ...
--     Found header '/usr/include/boost/mpl/at.hpp'
-- Found TPL 'Boost' include dirs '/usr/include'
-- TPL_Boost_INCLUDE_DIRS='/usr/include'

What is going on with a different boost being found?

**Comment by bartlettroscoe** [comment]
@spdomin, is your env var `boost_inc_dir` empty or something?  You might want to print it out in your configure script with:

```
echo "boost_inc_dir = '${boost_inc_dir}'
```

If you look at:

```
Processing enabled TPL: Boost (enabled explicitly, disable with -DTPL_ENABLE_Boost=OFF)
-- Searching for headers in Boost_INCLUDE_DIRS=''
```

it is being told to look in the empty "" directory first.  And if it does not find the header there, it will look in the standard system paths.  Hence your problem.

Also note that the Boost TPL does not define any libraries so there is no need to set `Boost_LIBRARY_DIRS`.

**Comment by spdomin** [comment]
Thanks @bartlettroscoe 

All looks well... Probably a simple type-o..
boost_inc_dir = "/ascldap/users/spdomin/gitHubWork/scratch_build/install/gcc8.3.0/boost/1.68.0/include"
nalu_install_dir = "/ascldap/users/spdomin/gitHubWork/scratch_build/install/gcc8.3.0"

**Comment by spdomin** [comment]
I have the config file clean now with the latest STK changes.

Many thanks for the help!
