### ISSUE TITLE
Aztecoo example:  can not link with libepetra and libepetraext

### ISSUE THREAD

**Issue by jsmith173** [trilinos/Trilinos#6837]
## Bug Report
@trilinos/Aztecoo

### Description
I'm trying to work a simple Aztecoo example. I have modified the simple_epetra_aztecoo example but in the new example I'd like to use epetra and epetraext. The new example is not compiled when I compiling Trilinos so I have modified the flags.make (for this example) to find the include file (EpetraExt_CrsMatrixIn.h) and the compiler found this include file but has problem at the link phase (libepetraext.a not found). After that I have modified the link.txt (for this example) and I have added libepetraext.a with its path but I have still an error message: undefined reference to Epetra_Time::Epetra_Time. I don't understand th error message because Epetra_Time is in libepetra.a and it is linked. I'm stuck here. It would be important for me.
I think my example similar to AztecOO_MatlabInput. Maybe would help a make file for AztecOO_MatlabInput. There is for example for IfpackAztecOO.
Configured with: -DTrilinos_ENABLE_EXAMPLES=ON
OS: Ubuntu 16.04
CMake version: 3.16.4

### Steps to Reproduce
Error log: 
[err.txt](https://github.com/trilinos/Trilinos/files/4209857/err.txt)

**Comment by mhoemmen** [comment]
@jsmith173 Are you modifying the examples in AztecOO's source directory?  If so, you might have some problems with package dependencies.  Look in `packages/aztecoo/cmake/Dependencies.cmake` and you'll see that AztecOO depends on Epetra, not on EpetraExt.  This is probably why you're getting the link error.

The right way to modify this example, is to build and install Trilinos, then copy the example into a separate directory, and modify it there.  When you install Trilinos, you'll find a`Makefile.export.Trilinos` file in the install directory somewhere.  You can `include` that in your `Makefile`, and use the variables defined there to get the right link line.  Best practice is to use the variables in `Makefile.export.Trilinos`, not to hard-code them into your project.

**Comment by jhux2** [comment]
Alternatively, look downstream at the ML package.  It has examples that use Epetra and AztecOO, as I recall.

**Comment by jsmith173** [comment]
Epetra and AztecOO works. The problem Epetra+Epetraext in an AztecOO example.

**Comment by mhoemmen** [comment]
@jsmith173 It's not currently possible for an example living in the AztecOO package to depend on anything in the EpetraExt package.  If you want to write code that does that, then the code needs to live separately from Trilinos, or in some other Trilinos package that depends on both EpetraExt and AztecOO.

**Comment by jhux2** [comment]
> Epetra and AztecOO works. The problem Epetra+Epetraext in an AztecOO example.

@jsmith173 ML examples also use EpetraExt.   What exactly is it that you need from EpetraExt?

**Comment by jsmith173** [comment]
I tried the standalone example but still not works (not linked). Please check the trilinos-test project on my GitHub account. What I made wrong?

**Comment by jhux2** [comment]
Please post your complete cmake configure command and the actual error you are seeing. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jsmith173** [comment]
Configuration command: reconf_par file in my trilinos-test repo.
Error messages: errors.txt in my trilinos-test repo.

**Comment by srajama1** [comment]
@jsmith173 It appears you are new to Trilinos and this github forum. Let me give you some suggestions. 

1. You need to tell us why you are doing something instead of saying I am doing something. This will allow us to suggest alternate options.
2. If someone asks the error meesage and configure, attach the error message and configure here. This will save folks who are trying to help you in their "free time" few more clicks. Then they will be me responsive. In addition, you won't be perceived rude.

Let me ask this question, why do you want to use Epetra and EpetraExt in AztecOO ?

**Comment by jsmith173** [comment]
I have attached here error messages (errors.txt), configuration commands (reconf_par.txt).
My example file is from my friend. He wanted do similar to packages/aztecoo/example/AztecOO_MatlabInput/cxx_main.cpp, reading a matrix from a file and doing matrix operations. AztecOO_MatlabInput using both epetra and epetraext.

[errors.txt](https://github.com/trilinos/Trilinos/files/4237184/errors.txt)
[reconf_par.txt](https://github.com/trilinos/Trilinos/files/4237187/reconf_par.txt)

**Comment by gkovacsds** [comment]
Hi, I'm that friend of jsmith173 he mentioned. I used epetraext because there's a matrix market file (mtx) reader there: EpetraExt::MatrixMarketFileToCrsMatrix
We tried to test the parallel solver on real world matrices. 
The test program ran well on one MPI process with Windows compilation, but always failed on more MPI processes. We're still looking for the cause of the failure, but wanted to try it on Linux as well.

**Comment by srajama1** [comment]
Ok, thanks for this info. This is what @mhoemmen was trying to explain. Let me try and expand.

Trilinos is organized as packages and there is a dependency structure specified using Dependencies.cmake in these packages. AztecOO does not depend on EpetraExt currently. If you just add EpetraExt headers to AztecOO tests it will not work. A better way to do what you want is to think of yourself as an application and not modify Trilinos tests. Instead, enable AztecOO, Epetra and EpetraExt in Trilinos. Copy the test program outside Trilinos, compile and link with Epetra, EpetraExt and AztecOO in that order so there are no compile/link time errors.

We do not test/develop on Windows. Most of our codes "should" work on Windows, but even if you find a problem there we may not be able to quickly help you.

**Comment by jsmith173** [comment]
I'm working with a standalone application as  @mhoemmen suggested. I tried also @srajama1 suggestions also but still not works. My tesp app compiled (*.o created) but can not link. If possible try to compile your AztecOO_MatlabInput example because this is using epetra and epetraext. Maybe if you can compile AztecOO_MatlabInput I could compile my own example.

**Comment by srajama1** [comment]
@jsmith173 : We seem to be talking past each other. AztecOO_MatlabInput  won't compile because it depends on Epetraext. This is exactly why it is not included in

https://github.com/trilinos/Trilinos/blob/master/packages/aztecoo/example/CMakeLists.txt

See https://github.com/trilinos/Trilinos/blob/master/packages/aztecoo/cmake/Dependencies.cmake

where EpetraExt is not listed. We don't want to introduce EpetraExt to AztecOO at this point. It is in absolute maintenance mode. 

What is the error you get when you try link and what is your link line ?

**Comment by jsmith173** [comment]
AztecOO_MatlabInput should be compiled as a standalone app?
We plan to add the relevant parts (used by our example) from epetraext to epetra. Is it possible?
I have attached the errors and the link line.

[errors.txt](https://github.com/trilinos/Trilinos/files/4240625/errors.txt)
[link.txt](https://github.com/trilinos/Trilinos/files/4240626/link.txt)

**Comment by srajama1** [comment]
I believe AztecOO_MatlabInput was written before the current CMake dependency system. I would rather not go fix it now.

Your link line is ordered with epetra before epetraext. Just flip the order. This is also true for aztecoo. The general linking order is left to right.

**Comment by srajama1** [comment]
@srajama1

**Comment by mhoemmen** [comment]
@jsmith173 If you look in Trilinos' install directory, you'll find files of the form `Makefile.export.*`.  You're supposed to include e.g., `Makefile.export.Trilinos` in your Makefile, and use the resulting variable definitions to set up your link line.  That will give you the libraries in the right order.

**Comment by srajama1** [comment]
We should probably remove AztecOO_MatlabInput, but I would probably not even do that small change if it is absolutely not needed.

**Comment by jhux2** [comment]
> Hi, I'm that friend of jsmith173 he mentioned. I used epetraext because there's a matrix market file (mtx) reader there: EpetraExt::MatrixMarketFileToCrsMatrix
> We tried to test the parallel solver on real world matrices.
> The test program ran well on one MPI process with Windows compilation, but always failed (crashed) on more MPI processes. We're still looking for the cause of the failure, but wanted to try it on Linux as well.

ML has some simple examples that use AztecOO + Epetra + matrix reading, in particular, `ml/examples/BasicExamples/ml_read_MatrixMarket.cpp`.  Rather than modifying AztecOO, I'd recommend configuring Trilinos with ML, its examples + tests, and all its optional dependencies, something like this:

```
ARGS=(
  -DTrilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=ON
  -DCMAKE_BUILD_TYPE=RELWITHDEBINFO
  -DTrilinos_ENABLE_TESTS=OFF
  -DTrilinos_ENABLE_ML=ON
  -DML_ENABLE_TESTS=ON
  -DML_ENABLE_EXAMPLES=ON
)

cmake "${ARGS[@]}" ${TRILINOS_DIR}
```

`ml_read_MatrixMarket.cpp` doesn't have options to change AztecOO settings, but that's pretty easy to do with a code block like this:

```
+  std::vector<int> azOptions;
+  azOptions.resize(AZ_OPTIONS_SIZE);
+  std::vector<double> azParams;
+  azParams.resize(AZ_PARAMS_SIZE);
+  AZ_defaults(azOptions.data(),azParams.data());
+
+  azOptions[AZ_precond] = AZ_dom_decomp;
+  azOptions[AZ_subdomain_solve] = AZ_rilu;
+
+  MLList.set("coarse: Aztec options",rcpFromRef(azOptions));
+  MLList.set("coarse: Aztec params",rcpFromRef(azParams));

```

**Comment by jsmith173** [comment]
@mhoemmen : I tested with Makefile.export.Trilinos also, the same problem, cannot link.
Maybe this is the Ubuntu problem (16.04). I can not switch to the latest Ubuntu becase there is a problem with MPI. The Xyce MPI test results with BAD.

Thanks @jhux2 I will try it.

**Comment by jhux2** [comment]
I forgot to mention that you should also add this:
```
MLList.set("max levels",1);

```
which forces ML to do a single level and use native AztecOO preconditioning, which I guess is what you're interested in.

**Comment by mhoemmen** [comment]
begone autobot

**Comment by jhux2** [comment]
Closing, since no response from OP.
