### ISSUE TITLE
Belos:  Solution to ill-conditioned problem is very different using different number of processors

### ISSUE THREAD

**Issue by zhengshuang2005** [trilinos/Trilinos#6854]
## Question
@trilinos/\<Belos\>

Dear developers and users,

I am switching from Epetra+AztecOO to Tpetra+Belos+Ifpack2. I am using the trilinos packages to store and solve linear problems AX=B for different Newton-Raphson iterations (A is the Jacobian which is ill-conditioned, X is the incremental, B is the negative residual). It was working very well when I was using the combination of Epetra+AztecOO. But when I started to use Tpetra+Belos+Ifpack2, I have been facing the problems. 

First problem is that Tpetra+Belos+Ifpack2 gives more than one time slower down than Epetra+AztecOO. 
Second problem is that Tpetra+Belos+Ifpack2 gives very different results in parallel (MPI) as compared to in serial. And the results are different if different number of processor is used.

The Jacobian and residual assembling are the same and it turned out to work very well with Epetra+AztecOO. I even printed out the Jacobian and Residual from Tpetra csrmatrix and multi-vector and used Matlab to solve the linear system. It gives the same results which is consistent with Tpetra serial running and Epetra serial running however number of processors I am testing with the matrix and vector output.

So I am wondering if my configurations are consistent for both solvers and it maybe possible that something is wrong with my Belos or Ifpack2 configurations. 

My Epetra+AztecOO configuration is:

    // Create the linear solver
    solverPtr_ = rcp(new AztecOO(*linearProblemPtr_));

    // Set solver options
    solverPtr_->SetAztecOption(AZ_solver, AZ_gmres);
    solverPtr_->SetAztecOption(AZ_overlap, 0);
    solverPtr_->SetAztecOption(AZ_kspace, 1200);
    solverPtr_->SetAztecOption(AZ_scaling, 4);
    solverPtr_->SetAztecOption(AZ_precond, AZ_dom_decomp);
    solverPtr_->SetAztecOption(AZ_subdomain_solve, AZ_ilu);
    solverPtr_->SetAztecOption(AZ_graph_fill, 0);
    solverPtr_->SetAztecOption(AZ_output, AZ_none);

    // Solve
    solverPtr_->Iterate(1000, 1e-6);

And my Tpetra+Belos+Ifpack2 configuration is:

    // A matrix fill complete
    Kokkos::Timer timer;
    A_->fillComplete();

    // B vector fill complete
    LO nodeNumElements = map_->getNodeNumElements();
    for (LO i = 0; i < nodeNumElements; i++)
    {
        B_->get1dViewNonConst()[i] = b_[elementList_[i]];
    }

    // Preconditioner
    RCP<op_type> M = createPreconditioner(A_);

    // Solver
    RCP<ParameterList> solverParams = parameterList("GMRES");
    solverParams->set("Output Frequency", 1);
    solverParams->set("Num Blocks", 1000);
    solverParams->set("Block Size", 1);
    solverParams->set("Maximum Iterations", 1000);
    solverParams->set("Convergence Tolerance", 1e-6);
    solverParams->set("Orthogonalization", "IMGS");
    solverParams->set("Maximum Restarts", 10);

    Belos::SolverFactory<SC, vec_type, op_type> factory;
    RCP<Belos::SolverManager<SC, vec_type, op_type> > solver =
        factory.create("GMRES", solverParams);

    // Linaer problem
    RCP<LinearProblem> problem = rcp(new LinearProblem(A_, X_, B_));

    // Solve
    problem->setRightPrec(M);
    problem->setProblem();
    solver->setProblem(problem);
    Belos::ReturnType result = solver->solve();

With the preconditioner creation code:

    ParameterList pList;
    pList.set ("inner preconditioner name", "ILUT");
    {
        Teuchos::ParameterList innerParams;
        innerParams.set("fact: iluk level-of-fill", 0);
        innerParams.set("fact: drop tolerance", 0);
        innerParams.set("fact: relax value", 0);
        pList.set("inner preconditioner parameters", innerParams);
    }
    pList.set("schwarz: zero starting solution", true);
    pList.set("schwarz: overlap level", 0);
    pList.set("schwarz: combine mode", "ZERO");
    pList.set("schwarz: num iterations", schwarzIter_);
    pList.set("schwarz: use reordering", false);

    // Set up preconditioner type and parameters
    RCP<prec_type> prec;
    Ifpack2::Factory factory;

    // Set up the preconditioner of the given type.
    prec = factory.create("schwarz", A);
    prec->setParameters(pList);
    prec->initialize();

    // Compute the preconditioner: incomplete factorization
    prec->compute();

I would appreciate any hints or suggestions! And I would like to provide additional informations for you to diagnose the problem. Thank you in advance!

Best regards,
Shuang

**Comment by mayrmt** [comment]
@trilinos/belos

**Comment by mhoemmen** [comment]
@zhengshuang2005 Why did you turn off reordering for Ifpack2, but not for AztecOO?  Just curious.

**Comment by zhengshuang2005** [comment]
> @zhengshuang2005 Why did you turn off reordering for Ifpack2, but not for AztecOO? Just curious.

Because I did not build Xpetra.

Ifpack2::AdditiveSchwarz::setParameters: You specified "schwarz: use reordering" = true.  This is only valid when Trilinos was built with Ifpack2, Xpetra, and Zoltan2 enabled.  Either Xpetra or Zoltan2 was not enabled in your build of Trilinos.

**Comment by mhoemmen** [comment]
@zhengshuang2005 wrote:
> Because I did not build Xpetra.

Enable Zoltan2 and Xpetra, and try again, with reordering set to `true`.

**Comment by zhengshuang2005** [comment]
> @zhengshuang2005 wrote:
> 
> > Because I did not build Xpetra.
> 
> Enable Zoltan2 and Xpetra, and try again, with reordering set to `true`.

Thank you Mark! I will try it out.

**Comment by zhengshuang2005** [comment]
> @zhengshuang2005 wrote:
> 
> > Because I did not build Xpetra.
> 
> Enable Zoltan2 and Xpetra, and try again, with reordering set to `true`.

Hi Mark, I enabled Zoltan2 and Xpetra and set reordering to be `true`. But unfortunately, it did not help.

**Comment by jhux2** [comment]
Are you using Trilinos develop branch, or a release branch?

**Comment by zhengshuang2005** [comment]
> Are you using Trilinos develop branch, or a release branch?

Hi Jonathan, I am using the master branch (I guess it means release branch?). Used to be on commit of September 2019 and now using the latest one (747a3e780d399a5a5b80940c8cf089c7c0ff3559) of 2/18/2020. 
I am trying to prepare and upload the matrix and vector I am having trouble with so that people can have a direct view. 
Thanks!

**Comment by mhoemmen** [comment]
@zhengshuang2005 wrote:
> Hi Mark, I enabled Zoltan2 and Xpetra and set reordering to be true. But unfortunately, it did not help.

Thanks for trying!

**Comment by jhux2** [comment]
@zhengshuang2005 I noticed that your example is using `ILUT` in the Tpetra stack, versus `ILU(k)` in the Epetra stack.  Please try changing `inner preconditioner name` to `RILUK` in the Tpetra run to see if that is any help.

**Comment by zhengshuang2005** [comment]
> @zhengshuang2005 I noticed that your example is using `ILUT` in the Tpetra stack, versus `ILU(k)` in the Epetra stack. Please try changing `inner preconditioner name` to `RILUK` in the Tpetra run to see if that is any help.

I tried RILUK as the inner preconditioner name but it gives the same results.

**Comment by zhengshuang2005** [comment]
I have written some code to read the output matrix and RHS from text file. The linear system is then solved using AztecOO and Belos solvers separately. Results as well as the solver time are reported for both solver packages. I have three test cases running using 1, 2, and 4 processors with Matlab code to read and solve the linear system.

It turned out that using my solver configuration (which I think are almost identical for both solvers), AztecOO is faster than Belos solvers. AztecOO gives "more correct" results as compared to MATLAB solution.

Any thoughts?

[solverTest.zip](https://github.com/trilinos/Trilinos/files/4234093/solverTest.zip)

**Comment by jennloe** [comment]
Just happened to glance at this- It looks like you are asking Belos to use Modified Gram-Schmidt orthogonalization while the default for AztecOO is Classical Gram-Schmidt.  That could definitely make a difference in solve time.  Does changing the Belos orthogonalization parameter to "ICGS" make any improvement? 

Also- perhaps you could test running Belos on your Epetra linear problem in order to eliminate possible differences with Tpetra?  I'm not sure why Belos would give a "less correct" solution than AztecOO given the same problem.

**Comment by cgcgcg** [comment]
Depending on what your problem looks like, maybe you could do a first comparison without preconditioners to determine if there is a difference between AztecOO and Belos?
