### ISSUE TITLE
STK:  stk_simd and stk_math broken on GPUs

### ISSUE THREAD

**Issue by sayerhs** [trilinos/Trilinos#6856]
## Bug Report
@trilinos/stk

### Description

We are seeing compilation errors in exawind/nalu-wind with the latest Trilinos develop branch on GPUs. [see CDash](https://my.cdash.org/viewBuildError.php?buildid=1776645). I believe it is because of the definition of `STK_MATH_FORCE_INLINE` https://github.com/trilinos/Trilinos/blob/747a3e780d399a5a5b80940c8cf089c7c0ff3559/packages/stk/stk_math/stk_math/StkMath.hpp#L43-L47 

### Steps to Reproduce
1. SHA1:  747a3e780d399a5a5b80940c8cf089c7c0ff3559

Cc: @alanw0

**Comment by srajama1** [comment]
@sayerhs : Can we close this ?

**Comment by spdomin** [comment]
Hi. I am reviewing recent Nalu and Nalu-Wind build/test issues. I see a common pattern or 1) commit, 2) break, 3) revert, without a subsequent push to resolve the initial push that was reverted. Top capture my statistics properly, was this ever re-commited?

**Comment by alanw0** [comment]
The fix no doubt went in with a subsequent stk snapshot.

**Comment by spdomin** [comment]
Good to know. I will exclude this from my data point.
