### ISSUE TITLE
Improve String Handling of Validators

### ISSUE THREAD

**Issue by MicheldeMessieres** [trilinos/Trilinos#686]
We have added some code to EnhancedNumberValidator so it will handle strings.
This creates some duplication with AnyNumberParameterEntryValidator.

The task will be to reorganize the validator classes to eliminate the duplication. This has been discussed in issue #612.

The general plan would be to create a [composite class](https://en.wikipedia.org/wiki/Composite_pattern) that will allow of stringing together validators including AnyNumberParameterEntryValidator and EnhancedNumberValidator.

**Tasks:**
1. Create a CompositeParameterEntryValidator subclass and add unit tests (including stringing together AnyNumberParameterEntryValidator and EnhancedNumberValidator with all the various use cases).
2. Refactor Zoltan2 code to use new CompositeParameterEntryValidator subclass with AnyNumberParameterEntryValidator and EnhancedNumberValidator objects.
3. Remove all the string handling from EnhancedNumberValidator (since string conversions will now be handled with AnyNumberParameterEntryValidator that does the conversions).
4. Remove some unit tests added for EnhancedNumberValidator accepting strings.

**Comment by bartlettroscoe** [comment]
@MicheldeMessieres, thankls for creating this issue.  But note that we want a fully generic COMPOSITE subclass not one specific for these subclassess.   This design pattern is explained at:

* https://en.wikipedia.org/wiki/Composite_pattern

I don't think it would not take long to put together a CompositeParameterEntryValiator subclass.  When you get time to work on this I can write the skeleton for you if it is not clear what needs to be done or how this would be used.

**Comment by bartlettroscoe** [comment]
@MicheldeMessieres, I updated the set of "Tasks" in the Description field (i.e. the first comment) to be exactly what needs to be done and the best order to do them in.

**Comment by bartlettroscoe** [comment]
I also created the label "Tech-X" to help organize these Stories for the Tech-X Trilinos work.
