### ISSUE TITLE
Trilinos: Build instructions

### ISSUE THREAD

**Issue by letzfets** [trilinos/Trilinos#6860]
## Documentation
@trilinos/framework

I try to find the comprehensive build documentation (with all options). The only thing I can find, is the quick guide from Brent Perschbacher in [INSTALL](INSTALL.rst) and the following broken links:

https://trilinos.github.io/
Under trilinos 12.12 release, link to PDF:
https://trilinos.github.io/pdfs/Trilinos10.12Tutorial.pdf
Which has a broken link under 1.2 installation to:
http://trilinos.sandia.gov/build_instructions.html

In
https://github.com/trilinos/Trilinos.git
Broken link to:
 @https://docs.trilinos.org/files/TrilinosBuildReference.html

Where is the up-to-date comprehensive build guide?

**Comment by mayrmt** [comment]
@trilinos/framework

**Comment by hmenke** [comment]
The Arch Linux User Repository (AUR) has a package for Trilinos.  Generally the AUR is a good source when it comes to build instructions.
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=trilinos
It contains these instructions:
```shell
mkdir -p build
cd build

cmake .. -DTrilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=ON \
         -DTrilinos_ENABLE_ALL_PACKAGES:BOOL=ON \
         -DTrilinos_ENABLE_PyTrilinos:BOOL=OFF \
         -DTrilinos_ENABLE_Gtest:BOOL=ON \
         -DTrilinos_ENABLE_TESTS=OFF \
         -DTPL_ENABLE_gtest:BOOL=ON \
         -DTPL_ENABLE_MPI:BOOL=ON \
         -DTPL_ENABLE_HDF5:BOOL=ON \
         -DCMAKE_INSTALL_PREFIX:PATH=/usr \
         -DBUILD_SHARED_LIBS:BOOL=ON
make VERBOSE=1
```

**Comment by jennloe** [comment]
I was about to create this issue myself.  I found a build guide here: https://trilinos.github.io/pdfs/TrilinosBuildReference.pdf Not sure if it is up-to-date or not.  Author is @bartlettroscoe .  Maybe he knows what to do with the broken links?

The link on this page https://github.com/trilinos/Trilinos/blob/master/INSTALL.rst to the in-depth document is also broken.

**Comment by bartlettroscoe** [comment]
> Not sure if it is up-to-date or not. Author is @bartlettroscoe . Maybe he knows what to do with the broken links?

@jennloe, I don't control the automated process that builds the documentation and puts in the links.  The @trilinos/framework team does that.  Building the documentation requires python (2.6.6+) and docutils to be installed.  But other than that, it is just a single command to build it.  See:

* https://tribits.org/doc/TribitsDevelopersGuide.html#project-specific-build-reference

That is all that I can do.

**Comment by bartlettroscoe** [comment]
Looks like someone finally fixed this:

* https://docs.trilinos.org/files/TrilinosBuildReference.html

Closing as complete.
