### ISSUE TITLE
Tpetra: Remove Details::assumeMpiIsCudaAware in favor of Behavior::assumeMpiIsCudaAware

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#6873]
## Bug Report
@trilinos/tpetra 

### Description

Remove `Tpetra::Details::assumeMpiIsCudaAware` (and its header file) in favor of `Tpetra::Details::Behavior::assumeMpiIsCudaAware`.  See [discussion here](https://github.com/trilinos/Trilinos/issues/6796#issuecomment-588571853).  The two functions are redundant, and Behavior defines the default behavior that we want.

**Comment by kddevin** [comment]
I am already removing this function.  See #6796

**Comment by kddevin** [comment]
Done.
