### ISSUE TITLE
Ifpack2: implement s-step Chebyshev

### ISSUE THREAD

**Issue by jhux2** [trilinos/Trilinos#6877]
## Enhancement
Chebyshev is a go-to smoother for AMG methods.  The current implementation for a degree `d` polynomial does d matrix-vector products, each of which do a round of communication.  This issue is to track an implementation of Chebyshev that does a single halo exchange that brings in d levels, followed by d local matrix-vector multiplies.

@csiefer2 has already done some work in OverlappingRowMatrix towards supporting this.

**Comment by jhux2** [comment]
@trilinos/ifpack2

**Comment by csiefer2** [comment]
FYI @jennloe

**Comment by jhux2** [comment]
@jennloe Please let me know if you've already started working on this, I don't want to step on your toes.

**Comment by jennloe** [comment]
@jhux2 No, I have not started working on this.  It is just very related to my work since it involves polynomials and s-step methods.  @csiefer2 mentioned I might be interested in helping, but it is too far down on the list for me to look at it now.

**Comment by jhux2** [comment]
@cgcgcg is testing a initial cut of s-step Chebyshev.
