### ISSUE TITLE
TpetraCore_Behavior_Default_MPI_4 fails in new 'ats2' CUDA builds: Setting both environment variables and CMake options for behaviors causes tests to fail

### ISSUE THREAD

**Issue by kddevin** [trilinos/Trilinos#6883]
## Bug Report
@trilinos/tpetra 

Many Tpetra options can be controlled by both CMake options and environment variables.
The most troublesome pair recently is CMake option -DTpetra_ASSUME_CUDA_AWARE_MPI and environment variable TPETRA_ASSUME_CUDA_AWARE_MPI.  Compiling with one value and setting the environment variable to the opposite value causes tests to fail.  See, for example, #6796 .

This issue will deal with test TpetraCore_Behavior_Default.  See record of its failures here:
https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&begin=2020-01-22&end=2020-02-20&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-ats2-cuda-10.1.243-gnu-7.3.1-spmpi-2019.06.24_static&field2=testname&compare2=61&value2=TpetraCore_Behavior_Default_MPI_4&field3=site&compare3=61&value3=vortex

These failures were caused by changes to the ATS-2 testing in which a single build is used with two different values of environment variable TPETRA_ASSUME_CUDA_AWARE_MPI.  One of the two value conflicts with the default value, causing this test to fail.

Since we will now have tests with environment variables differing from configuration variables' values, we cannot rely on the configuration variables values anywhere in CMakeLists.txt or source code when we do testing.  

The solution for this test is to remove the check that assumeMpiIsCudaAware returns the default value, as it does not -- it returns the environment variable.

The longer term solution probably is to remove the CMake option for all variables that can be controlled by environment variables.

### Steps to Reproduce
See link above for test configuration.

**Comment by bartlettroscoe** [comment]
As shown in [this query](https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&begin=2020-01-22&end=2020-02-20&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-ats2-cuda-10.1.243-gnu-7.3.1-spmpi-2019.06.24_static&field2=testname&compare2=61&value2=TpetraCore_Behavior_Default_MPI_4&field3=site&compare3=61&value3=vortex), and [this query](https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&begin=2020-01-22&end=2020-02-20&filtercount=4&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-ats2-cuda-10.1.243-gnu-7.3.1-spmpi-2019.06.24_static&field2=testname&compare2=61&value2=TpetraCore_Behavior_Default_MPI_4&field3=site&compare3=61&value3=vortex&field4=testoutput&compare4=97&value4=FAILED.*Behavior_Default_UnitTest) (click "Show Matching Output" in upper right to see the failures) this impacts the test:

* `TpetraCore_Behavior_Default_MPI_4`

in the 'vortex' builds:

* `Trilinos-atdm-ats2-cuda-10.1.243-gnu-7.3.1-spmpi-2019.06.24_static_dbg`
* `Trilinos-atdm-ats2-cuda-10.1.243-gnu-7.3.1-spmpi-2019.06.24_static_dbg_cuda-aware-mpi`
* `Trilinos-atdm-ats2-cuda-10.1.243-gnu-7.3.1-spmpi-2019.06.24_static_opt`
* `Trilinos-atdm-ats2-cuda-10.1.243-gnu-7.3.1-spmpi-2019.06.24_static_opt_cuda-aware-mpi`

showing the error:

```
0. Behavior_Default_UnitTest ... 
 dbg==debug_default = 1 == true : passed
 verb==verbose_default = 1 == true : passed
 cuda_aware_mpi==cuda_aware_mpi_default = 0 == true : FAILED ==> /vscratch1/jenkins/vortex-slave/workspace/Trilinos-atdm-ats2-cuda-10.1.243-gnu-7.3.1-spmpi-2019.06.24_static_opt/SRC_AND_BUILD/Trilinos/packages/tpetra/core/test/Behavior/Behavior_Default.cpp:82
 [FAILED]  (8.02e-05 sec) Behavior_Default_UnitTest
 Location: /vscratch1/jenkins/vortex-slave/workspace/Trilinos-atdm-ats2-cuda-10.1.243-gnu-7.3.1-spmpi-2019.06.24_static_opt/SRC_AND_BUILD/Trilinos/packages/tpetra/core/test/Behavior/Behavior_Default.cpp:62
```

@kddevin, as mentioned in [Create a Trilinos GitHub issue for the failure](https://snl-wiki.sandia.gov/display/CoodinatedDevOpsATDM/Triaging+and+Addressing+ATDM+Trilinos+Failures#TriagingandAddressingATDMTrilinosFailures-3.CreateaTrilinosGitHubissueforthefailure:), we need to list the exact test names and the exact build names or people can't map from failures they are seeing on CDash to GitHub issues.

**Comment by kddevin** [comment]
Done

**Comment by bartlettroscoe** [comment]
The [policy](https://snl-wiki.sandia.gov/display/CoodinatedDevOpsATDM/Triaging+and+Addressing+ATDM+Trilinos+Failures#TriagingandAddressingATDMTrilinosFailures-7.CloseaResolvedTrilinosGitHubIssue:) is to leave open until we have confirmation on CDash that the tests are fixed.

**Comment by bartlettroscoe** [comment]
As shown in [this query](https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&begin=2020-02-23&end=2020-02-26&filtercount=5&showfilters=1&filtercombine=and&field1=groupname&compare1=62&value1=Experimental&field2=buildname&compare2=65&value2=Trilinos-atdm-ats2&field3=testname&compare3=61&value3=TpetraCore_Behavior_Default_MPI_4&field4=testoutput&compare4=94&value4=Error%3A%20Remote%20JSM%20server%20is%20not%20responding%20on%20host%20vortex&field5=testoutput&compare5=94&value5=OPAL%20ERROR%3A%20Unreachable), the test `TpetraCore_Behavior_Default_MPI_4` is now passing in all of the `ats2` builds on 'vortex' where it was failing consecutively and passed today showing the history:

Site | Build Name | Test Name | Status | Time | Proc Time | Details | Build Time | Processors
-- | -- | -- | -- | -- | -- | -- | -- | --
vortex | Trilinos-atdm-ats2-cuda-10.1.243-gnu-7.3.1-spmpi-2019.06.24_static_dbg | TpetraCore_Behavior_Default_MPI_4 | Passed | 620ms | 2s 480ms | Completed | 2020-02-26T02:07:36 MST | 4
vortex | Trilinos-atdm-ats2-cuda-10.1.243-gnu-7.3.1-spmpi-2019.06.24_static_dbg | TpetraCore_Behavior_Default_MPI_4 | Failed | 820ms | 3s 280ms | Completed (Failed) | 2020-02-25T02:07:51 MST | 4
vortex | Trilinos-atdm-ats2-cuda-10.1.243-gnu-7.3.1-spmpi-2019.06.24_static_dbg | TpetraCore_Behavior_Default_MPI_4 | Failed | 800ms | 3s 200ms | Completed (Failed) | 2020-02-24T02:07:06 MST | 4
vortex | Trilinos-atdm-ats2-cuda-10.1.243-gnu-7.3.1-spmpi-2019.06.24_static_dbg | TpetraCore_Behavior_Default_MPI_4 | Failed | 860ms | 3s 440ms | Completed (Failed) | 2020-02-23T02:07:08 MST | 4
vortex | Trilinos-atdm-ats2-cuda-10.1.243-gnu-7.3.1-spmpi-2019.06.24_static_dbg_cuda-aware-mpi | TpetraCore_Behavior_Default_MPI_4 | Passed | 1s 920ms | 7s 680ms | Completed | 2020-02-26T07:30:51 MST | 4
vortex | Trilinos-atdm-ats2-cuda-10.1.243-gnu-7.3.1-spmpi-2019.06.24_static_dbg_cuda-aware-mpi | TpetraCore_Behavior_Default_MPI_4 | Failed | 2s 950ms | 11s 800ms | Completed (Failed) | 2020-02-25T07:51:05 MST | 4
vortex | Trilinos-atdm-ats2-cuda-10.1.243-gnu-7.3.1-spmpi-2019.06.24_static_dbg_cuda-aware-mpi | TpetraCore_Behavior_Default_MPI_4 | Failed | 670ms | 2s 680ms | Completed (Failed) | 2020-02-24T05:28:32 MST | 4
vortex | Trilinos-atdm-ats2-cuda-10.1.243-gnu-7.3.1-spmpi-2019.06.24_static_opt | TpetraCore_Behavior_Default_MPI_4 | Passed | 850ms | 3s 400ms | Completed | 2020-02-26T02:04:30 MST | 4
vortex | Trilinos-atdm-ats2-cuda-10.1.243-gnu-7.3.1-spmpi-2019.06.24_static_opt | TpetraCore_Behavior_Default_MPI_4 | Failed | 830ms | 3s 320ms | Completed (Failed) | 2020-02-25T02:03:40 MST | 4
vortex | Trilinos-atdm-ats2-cuda-10.1.243-gnu-7.3.1-spmpi-2019.06.24_static_opt | TpetraCore_Behavior_Default_MPI_4 | Failed | 760ms | 3s 40ms | Completed (Failed) | 2020-02-24T02:02:44 MST | 4
vortex | Trilinos-atdm-ats2-cuda-10.1.243-gnu-7.3.1-spmpi-2019.06.24_static_opt | TpetraCore_Behavior_Default_MPI_4 | Failed | 880ms | 3s 520ms | Completed (Failed) | 2020-02-23T02:02:45 MST | 4
vortex | Trilinos-atdm-ats2-cuda-10.1.243-gnu-7.3.1-spmpi-2019.06.24_static_opt_cuda-aware-mpi | TpetraCore_Behavior_Default_MPI_4 | Passed | 1s 730ms | 6s 920ms | Completed | 2020-02-26T07:56:51 MST | 4
vortex | Trilinos-atdm-ats2-cuda-10.1.243-gnu-7.3.1-spmpi-2019.06.24_static_opt_cuda-aware-mpi | TpetraCore_Behavior_Default_MPI_4 | Failed | 960ms | 3s 840ms | Completed (Failed) | 2020-02-25T06:02:04 MST | 4
vortex | Trilinos-atdm-ats2-cuda-10.1.243-gnu-7.3.1-spmpi-2019.06.24_static_opt_cuda-aware-mpi | TpetraCore_Behavior_Default_MPI_4 | Failed | 650ms | 2s 600ms | Completed (Failed) | 2020-02-24T05:27:53 MST | 4
vortex | Trilinos-atdm-ats2-cuda-10.1.243-gnu-7.3.1-spmpi-2019.06.24_static_opt_cuda-aware-mpi | TpetraCore_Behavior_Default_MPI_4 | Failed | 740ms | 2s 960ms | Completed (Failed) | 2020-02-23T05:20:52 MST | 4
vortex | Trilinos-atdm-ats2-gnu-7.3.1-spmpi-2019.06.24_serial_static_dbg | TpetraCore_Behavior_Default_MPI_4 | Passed | 990ms | 3s 960ms | Completed | 2020-02-25T02:10:51 MST | 4
vortex | Trilinos-atdm-ats2-gnu-7.3.1-spmpi-2019.06.24_serial_static_dbg | TpetraCore_Behavior_Default_MPI_4 | Passed | 780ms | 3s 120ms | Completed | 2020-02-24T02:10:18 MST | 4
vortex | Trilinos-atdm-ats2-gnu-7.3.1-spmpi-2019.06.24_serial_static_dbg | TpetraCore_Behavior_Default_MPI_4 | Passed | 1s 670ms | 6s 680ms | Completed | 2020-02-23T02:10:16 MST | 4
vortex | Trilinos-atdm-ats2-gnu-7.3.1-spmpi-2019.06.24_serial_static_opt | TpetraCore_Behavior_Default_MPI_4 | Passed | 1s 70ms | 4s 280ms | Completed | 2020-02-25T02:11:47 MST | 4
vortex | Trilinos-atdm-ats2-gnu-7.3.1-spmpi-2019.06.24_serial_static_opt | TpetraCore_Behavior_Default_MPI_4 | Passed | 1s 10ms | 4s 40ms | Completed | 2020-02-24T02:11:26 MST | 4
vortex | Trilinos-atdm-ats2-gnu-7.3.1-spmpi-2019.06.24_serial_static_opt | TpetraCore_Behavior_Default_MPI_4 | Passed | 1s 70ms | 4s 280ms | Completed | 2020-02-23T02:11:24 MST | 4

Therefore, I think this is fixed and we can close.

Thanks for fixing @kddevin!
