### ISSUE TITLE
Amesos2: compilation error on Blake with OpenMP KokkosNode 

### ISSUE THREAD

**Issue by ikalash** [trilinos/Trilinos#6897]
We have a compilation error on Blake with an OpenMP KokkosNode in the Albany nightlies due to Amesos2: 

https://my.cdash.org/viewBuildError.php?buildid=1780128

```
/.../repos/Trilinos/packages/amesos2/src/Amesos2_EpetraMultiVecAdapter_decl.hpp(201): error: namespace "Kokkos" has no member "Serial"
```
Could someone please look into this? 

@trilinos/amesos2

**Comment by MicheldeMessieres** [comment]
@ikalash I have the fix in progress - will put that in soon.

**Comment by ikalash** [comment]
Great, thanks @MicheldeMessieres !  I'm happy to test it when it's ready.

**Comment by MicheldeMessieres** [comment]
@ikalash PR #6900 should clear this.

**Comment by ikalash** [comment]
Seems this has been resolved, thanks again!
