### ISSUE TITLE
Default disable STKClassic under Trilinos

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#693]
**CC:** @rppawlo, @nschloe @eric-c-cyr, @bmpersc, @trilinos/stk

**Description:**

Now that STKClassic is no longer used by Sandia customer codes downstream from Panzer and Albany (see [this comment](https://github.com/trilinos/Trilinos/pull/2#issuecomment-252425782)), we should at the very least stop enabling STKClassic by default and stop testing it.  A follow-on Story should result in STKClassic getting complete pulled out of STK under Trilinos.  But there may be some external Trilinos customers that are still using STKClassic so we would likely need to ask before pulling it out.

**Comment by mhoemmen** [comment]
I didn't realize I could both "like" and "hooray" a comment :-)

**Comment by bartlettroscoe** [comment]
I am doing this now as part of #410 and #482.

**Comment by bartlettroscoe** [comment]
This was completed as of commit ae6a8dd.

Closing as complete.
