### ISSUE TITLE
Zoltan2: Compilation error in PuLP interface

### ISSUE THREAD

**Issue by tzovas** [trilinos/Trilinos#6930]
## Bug Report
@trilinos/Zoltan2

### Description
Compilation errors in PuLP when zoltan2 is used as a library. The installation/compilation of Trilinos
works fine. Later, I am using some zoltan function in my code and so I include some zoltan2 libraries
like Zoltan2_PartitioningSolution.hpp and Zoltan2_PartitioningProblem.hpp. When compiling my
code I get an error in /zoltan2/src/algorithms/partition/Zoltan2_AlgPuLP.hpp, line 416. 

include/Zoltan2_AlgPuLP.hpp:416:21: error: cannot convert ‘std::unique_ptr<int []>’ to ‘int*’ in initialization
  416 |                     vertex_weights, edge_weights, vertex_weights_sum};
      |                     ^~~~~~~~~~~~~~
      |                     |
      |                     std::unique_ptr<int []>

Same for the edge_weights.

I fixed by using the .get() function for the vertex and edges weights as:
pulp_graph_t g = {num_verts, num_edges, 
                     out_edges, out_offsets,
                    vertex_weights.get(), edge_weights.get(), vertex_weights_sum};

I am using GNU gcc 9.2.0

**Comment by cgcgcg** [comment]
@trilinos/zoltan

**Comment by mhoemmen** [comment]
@trilinos/zoltan2

**Comment by kddevin** [comment]
@gslota Do you have time to look at this issue?

**Comment by kddevin** [comment]
@gslota Is this issue fixed?  Can you link the PR to this issue?  Thanks!

**Comment by gslota** [comment]
This bug was addressed by PR #7014

**Comment by kddevin** [comment]
Thanks, @gslota
