### ISSUE TITLE
Thyra: Create utility class to extract and load data from recursive product and SPMD (multi)vector objects

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#6933]
**CC**: @ccober6 

## Description

Tempus needs the ability to extract raw data from and load raw data to arbitrary `Thyra::[Multi]VectorBase` objects in order to implement checkpointing.  For the use cases of interest, one can likely do this by recursively dynamic casting and unwrapping `Thyra::ProductMultiVector` and `Thyra::SpmdMultiVectorBase` objects.  Both Epetra and Tpetra vector and multivector subclasses derive (directly or indirectly) from `Thyra::SpmdMultiVectorBase`.  This can produce a list of `Thyra::SpmdMultiVectorBase` objects for which one can call the `Thyra::SpmdMultiVectorBase::get[Nonconst]LocalData()` function to get a contiguous pointer to the data on each MPI rank for which to read from or write to to implement the checkpointing.

## Definition of Done

* Create unit-tested utlity classes/functions in Thyra capabile of extracting an contiguous array of data on each MPI rank for an arbitrary nesting of `Thyra::ProductMultiVectorBase` and `Thyra::SpmdMultiVectorBase` objects objects.

* Create an example that builds a nested `Thyra::DefaultProductMultiVector` and `Thyra::DefualtSpmdMultiVector` objects and reads and writes the data to files on disk.

* Create an example that builds a nested `Thyra::DefaultProductMultiVector` and `Thyra::TpetraMultiVector` objects and reads and writes the data to files on disk.

**Comment by bartlettroscoe** [comment]
One interesting composite subclass to deal with is the decorator class [`Thyra::DefaultMultiVectorProductVector`](https://docs.trilinos.org/dev/packages/thyra/doc/html/classThyra_1_1DefaultMultiVectorProductVector.html)  which wraps an arbitrary `Thyra::MultiVectorBase` object and streaches it out into `Thyra::ProcutVectorBase` object (one column at a time).   That class does get used in Tempus in lots of files as shown in:

```
$ find packages/tempus/src/ -name "*.*pp" -exec grep -l DefaultMultiVectorProductVector {} \; 
packages/tempus/src/Tempus_CombinedForwardSensitivityModelEvaluator_impl.hpp
packages/tempus/src/Tempus_IntegratorPseudoTransientAdjointSensitivity_decl.hpp
packages/tempus/src/Tempus_CombinedForwardSensitivityModelEvaluator_decl.hpp
packages/tempus/src/Thyra_MultiVectorPreconditioner.hpp
packages/tempus/src/Tempus_StepperStaggeredForwardSensitivity_decl.hpp
packages/tempus/src/Tempus_IntegratorPseudoTransientForwardSensitivity_decl.hpp
packages/tempus/src/Tempus_WrapperModelEvaluatorPairPartIMEX_StaggeredFSA_decl.hpp
packages/tempus/src/Tempus_IntegratorForwardSensitivity_impl.hpp
packages/tempus/src/Tempus_AdjointSensitivityModelEvaluator_decl.hpp
packages/tempus/src/Tempus_IntegratorPseudoTransientForwardSensitivity_impl.hpp
packages/tempus/src/Tempus_IntegratorForwardSensitivity_decl.hpp
packages/tempus/src/Thyra_MultiVectorLinearOpWithSolveFactory.hpp
packages/tempus/src/Tempus_StepperStaggeredForwardSensitivity_impl.hpp
packages/tempus/src/Tempus_IntegratorPseudoTransientAdjointSensitivity_impl.hpp
packages/tempus/src/Tempus_StaggeredForwardSensitivityModelEvaluator_decl.hpp
packages/tempus/src/Thyra_MultiVectorPreconditionerFactory.hpp
packages/tempus/src/Tempus_IntegratorAdjointSensitivity_impl.hpp
packages/tempus/src/Thyra_MultiVectorLinearOp.hpp
packages/tempus/src/Tempus_WrapperModelEvaluatorPairPartIMEX_CombinedFSA_decl.hpp
packages/tempus/src/Tempus_AdjointAuxSensitivityModelEvaluator_decl.hpp
packages/tempus/src/Tempus_StaggeredForwardSensitivityModelEvaluator_impl.hpp
packages/tempus/src/Tempus_AdjointSensitivityModelEvaluator_impl.hpp
```

So how does that impact things?  Does it need to impact the implementation of the class that I need to write?  Let's think about this?  The class `Thyra::DefaultMultiVectorProductVector` derives from the interface `Thyra::ProductVecotrBase` which derives from `Thyra::ProductMultiVectorBase`.  Therefore, we could just ignore the existance of the class `Thyra::DefaultMultiVectorProductVector` and let it be treated as a `Thyra::DefaultMultiVectorProductVector` object to extract the data.  That may not be the most efficeint implementation but it would work.  The fastest thing to do is to just use the default interfaces.  Since this is going to be used to copy in and out raw data and be used for checkpointing (which is going to be using super slow disk I/O) my guess is that the extra overhead will be in the noise and therefore not worth even looking at initially (unless a Teuchos Timer says differently).

**Comment by bartlettroscoe** [comment]
@ccober6, sorry I have not gotten to this yet.  Swamped by other things trying to keep other people working.  Let me know when you need this more urgently so I can get this done.

**Comment by ccober6** [comment]
@bartlettroscoe I have been on "vacation" getting my house ready for sale.  I would like to get this moving sooner than later as EMPIRE could use the restart capability for their milestone.  Where are you on this, and how much effort is left?

**Comment by ccober6** [comment]
@gsjaardema pinging Greg so he is in the loop.

**Comment by bartlettroscoe** [comment]
> Where are you on this, and how much effort is left?

@ccober6, I have done some of the design work but there is a couple of uninterrupted days of programming to get this done.   I pull put this at the top of my personal ToDo list.

**Comment by ccober6** [comment]
Hey @bartlettroscoe, I wanted to touch base on this and see where it is in your queue.  Thanks, Curt

**Comment by ccober6** [comment]
I missed earlier notices on this, but Tempus does have a deliverable this year for this, so reopening.
