### ISSUE TITLE
Tpetra::Map: Generalize tests that depend unnecessarily on particular GO types

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#695]
@trilinos/tpetra 

Find and generalize all Tpetra::Map tests that depend unnecessarily on particular GlobalOrdinal (GO) types.  These tests live in tpetra/core/test/Map.

One example of such a test is Map_removeEmptyProcesses.cpp.  There is no reason why this test needs LO=int and GO=long.  Its choice of GO=long is particularly bad, since GO=long is not enabled by default (default GO types are currently int and long long, but see #74).  This means that most developers haven't even been building the test, let alone running it.

See my recent commit cd63103cc7b9ff328b900b3e379be21bea61f705 for an example of what to do.  That commit fixes the test in other ways, but the main changes with respect to this task are as follows:
1. Make sure everything in the test lives in an anonymous namespace (always a good idea, to avoid namespace collisions)
2. Use TEUCHOS_UNIT_TEST_TEMPLATE_3_DECL instead of TEUCHOS_UNIT_TEST, to make the test templated on LO, GO, NT (the Node type; name doesn't matter)
3. Add test instantiations at the end, using the pattern in Map_replaceCommWithSubset.cpp (as of the above commit to the develop branch)

**Comment by mhoemmen** [comment]
I made the minor requested changes to one file (LO -> int for MPI process ranks).  Now that the freeze is done, I can run check-in tests and push.  Thanks @tjfulle !

**Comment by tjfulle** [comment]
Thanks @mhoemmen, I have the changes done - I'm still trying to figure out my mpiexec woes - I should have the changes pushed shortly

**Comment by mhoemmen** [comment]
@tjfulle Don't sweat it, changes were quick and easy, I just pushed them :)  I kept the changes in a separate commit so you get the credit for your work :)
