### ISSUE TITLE
Tpetra: Generalize sparse matrix-matrix multiply tests that depend unnecessarily on particular GO types

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#696]
@trilinos/tpetra 

See #695 for an explanation.  The tests in question live in tpetra/core/test/MatrixMatrix.  At the top of the CMakeLists.txt file in that directory, you can see that the test only gets built and run if GO=int or GO=long are enabled.

This issue is less urgent than #695, because GO=int currently gets enabled by default.  However, see #74.  Furthermore, GO=long is not enabled by default, which means that most developers do not test Tpetra's sparse matrix-matrix multiply implementation with a 64-bit GO type.  Some applications that exercise Tpetra's sparse matrix-matrix multiply for MueLu (algebraic multigrid) setup use GO=long, so at least this gets tested downstream.  However, I would prefer to catch any bugs that may exist before applications see them.

**Comment by tjfulle** [comment]
@mhoemmen, @csiefer2 took care of this in 239854bfd645b6cd97ca5fe76c96caadb596b173
