### ISSUE TITLE
Tpetra::CrsMatrix: Generalize tests that currently only build & run for GO=int

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#698]
@trilinos/tpetra

This is like #695, #696, and #697.  Look at tpetra/core/test/CrsMatrix/CMakeLists.txt.  Find the three tests protected by `IF(TPETRA_INST_INT_INT) ... ENDIF()`.  (I've marked it with a FIXME.)  Look at those tests to see if they can be generalized, and generalize them to exercise all GO types, not just GO=int.  Then, change CMakeLists.txt so those tests build and run unconditionally.

This task may be harder than the previous three.  You may have to look at the tests carefully to understand whether they really depend on GO=int.

**Comment by tjfulle** [comment]
@mhoemme, as I'm going through these tests, I'm seeing that some tests use

```c++
  using Tpetra::TestingUtilities::getNode;
  using Tpetra::TestingUtilities::getDefaultComm;
```

While others use `Tpetra::DefaultPlatform().getComm` and `SomeObjext.getNode()`.  Is one preferred over the other?

**Comment by mhoemmen** [comment]
@tjfulle It doesn't really matter.  Both of the comm-related ones just wrap MPI_COMM_WORLD in an MPI build, and Teuchos::SerialComm in a non-MPI build.  I would like to phase out Node-related functions.  The _really_ bad thing is creating a new Node instance by invoking its constructor directly.  Otherwise, the other functions should be equivalent.

**Comment by mhoemmen** [comment]
I just tested and merged @tjfulle 's changes into develop.
