### ISSUE TITLE
Load SEMS Modules If Not Already Loaded

### ISSUE THREAD

**Issue by jmgate** [trilinos/Trilinos#6986]
### Description
The `load-env.sh` script assumes the SEMS modules are defined (i.e. so the 'sems-env' module is defined and can be loaded using `module load semv-env`).  On some machines that's not the case.  It'd be nice to check if the modules aren't loaded yet, and if they're not, load them automatically.

## Tasks

* Modify `cmake/std/atdm/sems-rhel7/environment.sh` to define the SEMS modules if they are not already defined.
* Update documentation in  `cmake/std/atdm/sems-rhel7/README.md` for the change in assumptions and behavior.

**Comment by jmgate** [comment]
@bartlettroscoe, here you go.

**Comment by bartlettroscoe** [comment]
@jmgate, I think we should call this an "enhancement" and not a "bug" since it was previously assumed that the SEMS modules were defined (not loaded) on all of the supported systems (which seems like a reasonable assumption).

**Comment by bartlettroscoe** [comment]
This is occurring on one of the 'ascic' machines that EMPIRE is trying to set up Jenkins jobs on.

**Comment by bartlettroscoe** [comment]
@jmgate, can you please pull and test out the topic branch in the new WIP PR #6988 on the 'ascic' machine where the EMPIRE Jenkins scripts have having this problem?

**Comment by jmgate** [comment]
Yes, but need to put out a fire first.

**Comment by bartlettroscoe** [comment]
@jmgate tested and approved PR #6988.  Moving to in review until we get confirmation from Jenkins job.

**Comment by bartlettroscoe** [comment]
@jmgate, with the merge of PR #6988 are we good to close this Issue?

**Comment by jmgate** [comment]
Should be able to.  We don't have it in our fork yet due to testing failures on our end, but I tested this beforehand and it should do the trick.  Closing&hellip;
