### ISSUE TITLE
Tpetra: Map/Directory min GID uninitialized in some circumstances

### ISSUE THREAD

**Issue by tjfulle** [trilinos/Trilinos#6987]
## Bug Report
@trilinos/tpetra

### Description
`Tpetra::Map::myMinGID_` is the minimum GID held by a map on its owning process.  For a map that has no entries on a process, its value is left uninitialized.

The `Tpetra::Details::Directory::allMinGIDs_` array holds the minimum GID on each participating process.  This array is used, eg, in the directory's `getEntriesImpl` method.  For ranks whose maps are empty `allMinGIDs_[rank]` is uninitialized and any work using it triggers undefined behavior.

@rppawlo discovered this in a simple test where in a map was empty on every process *except* the last.  Use that map to build a `Tpetra::MultiVector` and then import that `MultiVector` to another `MultiVector` with a locally replicated map.  The result is failure to import the values from the original vector to the locally replicated vector (because of comparisons with uninitialized values in `Directory::getEntriesImpl`.  A simple reproducer is copied below.

A potential solution is to initialize `myMinGID_ = Invalid;` and check for `Invalid` in `getEntriesImpl` as part of its algorithm.

Any other ideas @mhoemmen ?

@rppawlo does the above adequately describe the issue?

Reproducer:

```c++
TEUCHOS_UNIT_TEST_TEMPLATE_3_DECL(Directory, AllMinGIDs, SC, LO, GO)
{
  using map_type = Tpetra::Map<LO, GO>;
  using vector_type = Tpetra::MultiVector<SC, LO, GO>;
  using import_type = Tpetra::Import<LO, GO>;

  auto comm = getDefaultComm();
  const auto my_rank = comm->getRank();
  const auto num_procs = comm->getSize();

  const GO index_base = 0;
  const size_t num_vecs = 1;

  Teuchos::RCP<vector_type> vec1;
  Teuchos::RCP<map_type> map1;
  {
    const Tpetra::global_size_t num_global_elements = 5;
    const size_t num_local_elements = (my_rank == num_procs - 1) ? 5 : 0;
    map1 = Teuchos::rcp(new map_type(num_global_elements, num_local_elements, index_base, comm));
    vec1 = Teuchos::rcp(new vector_type(map1, num_vecs, true));
    if (my_rank == 0) vec1->putScalar(Teuchos::as<SC>(5.0));
  }

  Teuchos::RCP<vector_type> vec2;
  Teuchos::RCP<const map_type> map2;
  {
    const size_t num_elements = 5;
    map2 = Tpetra::createLocalMap<LO,GO>(num_elements, comm);
    vec2 = Teuchos::rcp(new vector_type(map2, num_vecs, true));
  }

  auto import = import_type(map1, map2);
  vec2->doImport(*vec1, import, Tpetra::INSERT);

  auto data = vec2->getData(0);
  TEUCHOS_TEST_FOR_EXCEPTION(data.size() != 5, std::logic_error, "Vector data.size should be 5 but is " << data.size());
  TEUCHOS_TEST_FOR_EXCEPTION(data[0] != Teuchos::as<SC>(5.0), std::logic_error, "Vector data[0] should be 5.0");
  TEUCHOS_TEST_FOR_EXCEPTION(data[1] != Teuchos::as<SC>(5.0), std::logic_error, "Vector data[1] should be 5.0");
  TEUCHOS_TEST_FOR_EXCEPTION(data[2] != Teuchos::as<SC>(5.0), std::logic_error, "Vector data[2] should be 5.0");
  TEUCHOS_TEST_FOR_EXCEPTION(data[3] != Teuchos::as<SC>(5.0), std::logic_error, "Vector data[3] should be 5.0");
  TEUCHOS_TEST_FOR_EXCEPTION(data[4] != Teuchos::as<SC>(5.0), std::logic_error, "Vector data[4] should be 5.0");

}
```

**Comment by tjfulle** [comment]
Note: the above reproducer does not fail if `vec1`'s entries are put on rank 0.

**Comment by tjfulle** [comment]
Hmmm, `minMyGID_` does appear to be initialized to `Invalid`, but @rppawlo and I printed its value in his test and it was `Invalid`, but appeared to be some uninitialized rubbish...

**Comment by mhoemmen** [comment]
@tjfulle wrote:
> `Tpetra::Map::myMinGID_` is the minimum GID held by a map on its owning process.

Correction: `Tpetra::Map::minMyGID_`.

> A potential solution is to initialize `myMinGID_ = Invalid;` and check for `Invalid` in `getEntriesImpl` as part of its algorithm.
 
You could do that or instead pick the largest possible `global_ordinal_type`.  The latter might make the logic for computing the globally minimum global index easier.  In either case, you'll need to post-process `allMinGIDs_` after the all-gather, and overwrite that flag value with the most recent previous non-flag value.

Thanks Tim! : - )

**Comment by mhoemmen** [comment]
@tjfulle wrote:
> Perhaps we were using the wrong templated `Invalid` for comparison?

Could this be because @rppawlo might be using `GlobalOrdinal=unsigned long`?

**Comment by tjfulle** [comment]
@mhoemmen, `Map` does set `myMinGID` to `std::numeric_limit<blah>::max()` if the map is empty on its process.  I suspect we were printing `Invalid` correctly, but misinterpreted the value of `myMinGID` as uninitialized when, in fact, it was `std::numeric_limits<blah>::max()`.  I have a fix I am testing now.

**Comment by rppawlo** [comment]
> Could this be because @rppawlo might be using `GlobalOrdinal=unsigned long`?

@mhoemmen - this is not for the unsigned long use case. It is for GO = long long int (the default for all atdm builds). Thanks @tjfulle for working on this!

**Comment by mhoemmen** [comment]
@rppawlo Thanks -- just checking!

**Comment by tjfulle** [comment]
I just pushed a unit test that exhibits the problem, but my quick fix did not fix the issue (@rppawlo's quick fix did).  Hmmm, keep digging....

**Comment by rppawlo** [comment]
@mhoemmen - totally understand. unsigned is only required for applications using DatTransferKit 2.0. The new DTK 3.0 can use any global ordinal type but has a significantly different user interface. The only code I am aware of that is using 2.0 is Albany. So when that changes over, we can forget unsigned GOs ever existed :)

**Comment by tjfulle** [comment]
The search algorithm in `getEntriesImpl` assumes that entries are uniformly distributed over processes.  The maps in @rppawlo's (and the unit test i committed) violate that assumption.  As a result, the search will always fail when looking for `GID=0` with `numProcs>3`.

I believe the best way to generalize the search to work in this case is to reimplement the search as a binary search - which is consistent with comments in `getIntriesImple`: `TODO: replace by a binary search`.

I'll put in a binary search tomorrow to see if it fixes this bug.

**Comment by mhoemmen** [comment]
Thanks Tim!  That sounds like a good plan!

**Comment by tjfulle** [comment]
rats, the binary search wasn't as straightforward as I had thought it would be.  but, instead of rewriting the entire search, it occurred to me that we could just start the search from the first initialized GID.  Doing so passes the test that replicates @rppawlo's reproducer.  PR forthcoming.

**Comment by tjfulle** [comment]
@rppawlo the fix is in develop

**Comment by rppawlo** [comment]
> @rppawlo the fix is in develop

@tjfulle - thanks! Sorry for delay in testing the fix - the panzer test is now passing!

**Comment by tjfulle** [comment]
Yep!
