### ISSUE TITLE
KokkosKernels: Add simplified kernels for integer Scalar types

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#700]
@trilinos/zoltan2 @trilinos/tpetra 

Many Trilinos users have complained about long build times and large library and executable sizes.  One of the biggest sources of this in the Tpetra solver stack, is the large number of template parameter combinations for which Tpetra classes get instantiated.  For example, we build all of Tpetra for Scalar = int and Scalar = GlobalOrdinal for EVERY enabled GlobalOrdinal type, as well as for the usual Scalar types like double and std::complex<double>.

Use of integer Scalar types seems a little weird.  In most cases where Tpetra or downstream Trilinos packages use integer Scalar types, they use them for communication (as the source or target of an Export or Import), not for computation.  This could justify refactoring Tpetra's class hierarchy into integer and non-integer "branches."  However, I had a conversation with Michael Wolf about Zoltan2's needs.  He explained that for some computations of metrics, Zoltan2 does sparse matrix-vector multiplies with integer Scalar types.  This means that we really do need to compute with integer Scalar types.  However, we don't need highly optimized kernels for integer Scalar types, as far as I know.

This suggests that we could address the problem at the KokkosKernels level, by falling back to simple kernels for integer Scalar types.  This issue proposes to do just that.  The kernels still need to be thread parallel, and must use CUDA appropriately.  However, they don't need such heavy optimization.  We can write simple one-level parallelism, for example.

Here are some build directory size statistics, for the Trilinos/packages/tpetra build directory after `make clean` and `make`, with no examples or tests enabled.  I used GCC 4.7.2 on Linux, and enabled Scalar = std::complex<double>.  Otherwise, I only use default settings for enabled types.  (Default enabled LocalOrdinal type is int.  Default enabled GlobalOrdinal types are int and long long.)  *_STATIC builds indicate static libraries; otherwise, I use dynamic libraries.  *_DEBUG* builds have Kokkos and Teuchos debugging features (e.g., bounds checking) turned on; *_RELEASE* builds have these debugging features turned off.  I enabled only the Kokkos::OpenMP version of Tpetra (this should generate more code than the Kokkos::Serial version).

  - MPI_DEBUG: 2.1 G
  - MPI_DEBUG_STATIC: 11 G 
  - MPI_RELEASE: 187 M
  - MPI_RELEASE_STATIC: 2.3 G

Do you see why we recommend dynamic libraries? ;-)

Correction: My MPI_RELEASE build is Kokkos::Serial only.

**Comment by mhoemmen** [comment]
KokkosKernels currently pre-builds (it's not quite ETI; it uses full instantiation rather than Trilinos' ETI machinery) a different set of kernels than Tpetra needs.  It builds for all of Kokkos' enabled execution spaces, rather than looking at only the execution spaces that Tpetra uses, and it builds for Scalar = int, long, and double, whether or not Tpetra needs them.

Just to check, I changed KokkosKernels to pre-build Scalar = int, long long, and double (matching Tpetra's enabled Scalar types, except for std::complex<double>).  I got nearly the same build sizes for Trilinos/packages/tpetra (see above explanation):

  - MPI_DEBUG: 2.1 G
  - MPI_DEBUG_STATIC: 11 G
  - MPI_RELEASE:
  - MPI_RELEASE_STATIC: 2.3 G

**Comment by mhoemmen** [comment]
Next, for integer Scalar types, I replaced the pre-built sparse mat-vecs (that is, all use of the DEF macros for integer Scalar types int and long long) with a stub implementation that throws std::logic_error.  Then, I got the following build sizes:

  - MPI_DEBUG: 2.0 G
  - MPI_DEBUG_STATIC: 
  - MPI_RELEASE: 
  - MPI_RELEASE_STATIC:

**Comment by mhoemmen** [comment]
Next steps:
  1. Make the pre-building of kernels use the "TPETRAKERNELS_INSTANTIATE_*" macros
  2. Don't build kernels for Devices that Tpetra does not use (e.g., Kokkos::Serial may be enabled in Kokkos, but not necessarily in Tpetra)

**Comment by srajama1** [comment]
Before you spend a lot of time doing this, we were wondering in the Zolatn2 meeting if it is possible to remove the dependency on integer instantiations in Zoltan2. Can we talk , may be with @kddevin as well.

**Comment by mhoemmen** [comment]
@srajama1 I appreciate the thought :-)  On the other hand, it's not just Zoltan2 that needs integer Scalar types.  Furthermore, Michael Worf gave some good reasons why Zoltan2 might want to do sparse mat-vecs with integer Scalar types.

**Comment by mhoemmen** [comment]
Woah, I killed 2 MB just by changing the macros for axpby to match Tpetra's, rather than Kokkos'.

**Comment by mhoemmen** [comment]
I had some build settings wrong, so my above build size measurements were off.  This time, I tested MPI_RELEASE with only `Kokkos::Serial` and `Trilinos_ENABLE_OpenMP:BOOL=OFF`.  I used the check-in test script, but only enabled the Ifpack2 package (`--enable-packages=Ifpack2`), so that I would build Tpetra's libraries, but no tests or executables.

As of commit 33a2c7ec32ba20709f6ba46c8439d7ad297f49c4 (before my recent changes), the tpetra build directory (no tests or examples, just dynamic libraries) was 393 M.  Of that, core was 296 M, and kernels was 94 M.

As of commit 46a01d623c988b686e9af23e2eda920a2aa51de8 (after my recently pushed changes), the tpetra build directory (no tests or examples, just dynamic libraries) was 383 M.  Of that, core was 279 M, and kernels was 102 M.

These results are expected.  KokkosKernels does not build kernels for Scalar=long by default any more, so the total number of kernels Tpetra builds (both instantiated "pre-built" by KokkosKernels, and instantiated by Tpetra because KokkosKernels didn't pre-build them) is less.  KokkosKernels builds more kernels (e.g., for Scalar=std::complex<double>, if Tpetra needs it), so its build directory is larger.  However, KokkosKernels pre-builds exactly what Tpetra needs now, so Tpetra's build directory is smaller.  Net savings: 10 M.  Nice! :-D

**Comment by mhoemmen** [comment]
> Next step: Make the integer ("ordinal") Scalar kernels as small as possible. In particular, get rid of all optimizations for multiple right-hand sides.

As an experiment, I gave all the integer Scalar instantiations of SPMV_MV (sparse matrix-vector multiply with multiple right-hand sides) trivial implementations.  This brought the MPI_RELEASE tpetra build directory size down from 383 M to 374 M.  That's with two integer Scalar type instantiations.  Not quite as much as I had hoped, but still not bad.  This is with GCC; I would expect more with the Intel compiler.

**Comment by mhoemmen** [comment]
I repeated the above experiment, but replaced the stub implementations with repeated calls to SPMV::spmv (single-vector implementation).  Resulting build size: still 374 M!  (Not entirely surprising; we pre-build the single-vector implementation, so this should not build much more code).

**Comment by mhoemmen** [comment]
After my last commit mentioned above, the resulting build size was still 374 M!  (This is not entirely surprising; we pre-build the single-vector implementation, so this should not have built much more code.)

**Comment by mhoemmen** [comment]
My proposed fix for #762 may reduce this further, since I got rid of instantiations and made the sparse mat-vec functors simpler.  I'll check GCC 4.7.2 MPI_RELEASE again.
