### ISSUE TITLE
Bug during Trilinos installation using OpenBLAS

### ISSUE THREAD

**Issue by UfrancoU** [trilinos/Trilinos#7011]
Bug report on Building Trilinos using OpenBLAS

Hi all,

   I installed Trilinos 12.10.1 recently in my local cluster. During installation I had to sort out some difficulties associated with the OpenBLAS package.

   Of course I got the library (OpenBLAS  0.2.20) beforehand. During Trilinos installation the system could not find libblas. Seemingly, Trilinos build builds (old) openblas, then other components don't find it..cause they expect libblas.
   I managed to workaround the issue thanks to OpenBLAS support team, and the solution was to go into OpenBLAS/lib subdir and add two simple symlink for the expected names libblas and liblapack.

     ln -s libopenblas.so libblas.so
     ln -s libopenblas.so liblapack.so

  It was pretty easy solution once the problem was well identified, but it can be a headache.

  This problem was solved thanks to OPenBLAS people, and the thread of the issue can be found by the reference title:  Problem installing OpenBLAS #2499 
  
  I hope this helps.

cheers many,
Felipe

**Comment by mhoemmen** [comment]
@UfrancoU wrote:
> I installed Trilinos 12.10.1 recently in my local cluster.

That version of Trilinos is several years old.  I would recommend using the latest release (12.18, available as a tag at least) or master.

**Comment by UfrancoU** [comment]
Hello mhoemmen,

  Thanks for sharing your recommendations on this thread, we need collaboration.

   I think somewhat differently regarding the problem: Trilinos 12.10.1 is just -three and a half- years old. More so, these not too-recent versions usually have been installed and used by thousands of people, unlike the new ones. 
   I decided not to install the latest one on purpose. I expected everything to go well, but this detail of linking with openblas names came out. 
   Anyway, I think it is good that we have this forum so we have solutions and answers. 

   The support team is so helpful :)

cheers,
Felipe

**Comment by mhoemmen** [comment]
@UfrancoU -- thanks for your kind message!  I wish I could be responsible for Trilinos so that I could help nice users like you :-) .  Unfortunately I'm not, and I'm just reporting the reality that the people who are responsible for Trilinos are very unlikely to support past versions in any realistic way (e.g., port bug fixes consistently and run regular tests with different compilers).  The most recent release tag is 12.18, which you can find on GitHub.  I would suggest trying that.
