### ISSUE TITLE
Amesos2: Using Mumps solver

### ISSUE THREAD

**Issue by mosayed86** [trilinos/Trilinos#7024]
#Question
@trilinos/ameso2
@trilinos/epetra

I have a question when using Amesos2 with Mumps solver to solve Ax=B. I am reading very large square matrix A and vector B from *.mtx files using EpetraExt libraries. I am getting the correct result for vector x if I am using only one processor (mpirun -np 1), however, when more than one processor are used, vector x equals to vector B. I am not sure why I am getting such result. I am able to share my code if needed.

Thanks,
Mohamed

**Comment by jhux2** [comment]
@trilinos/amesos2 
Possibly related to #6996.

**Comment by srajama1** [comment]
@mosayed86 I don't think the developer who contributed MUMPS needed distributed version on MUMPS. As a result, I believe this was never implemented.

**Comment by mosayed86** [comment]
@srajama1 Thanks for your reply. Any suggestions to solve such large linear system of matrices and vectors on trilinos?

**Comment by srajama1** [comment]
Do you have a problem that needs direct methods ? Can you use iterative methods like Belos, w/ or w/o preconditioning ?

**Comment by mosayed86** [comment]
I am solving a large sparse problem that needs a direct linear solver, simply (Ax=B) with temporal increments.

**Comment by srajama1** [comment]
If you are sure you need a direct method, we support SuperLU Dist in both local and distributed modes. We could add the feature to MUMPS, but it would take some time and effort to do it.

**Comment by mosayed86** [comment]
It would be great if feature is added to MUMPS. I really need it for my research and upcoming work as well.

**Comment by srajama1** [comment]
@ndellingwood @MicheldeMessieres FYI ...

@mosayed86 : I will add it to the list of enhancements, but this may not happen quickly. It wouldn't be hard to add but finding the time and people is the hard part. If you are interested in you can add it to Amesos2_Mumps and contribute it back.
