### ISSUE TITLE
ROL: Including Tpetra_MultiVector_def.hpp exposes Sierra to build warnings

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#7034]
## Bug Report
@trilinos/rol @trilinos/tpetra @dridzal @gregvw 

### Description 

ROL includes `Tpetra_MultiVector_def.hpp`:
``` 
.../packages/rol/adapters/tpetra/src/vector/ROL_TpetraMultiVector.hpp:55:#include "Tpetra_MultiVector_def.hpp"
.../packages/tpetra/core/cmake/README:17:../src/Tpetra_MultiVector_def.hpp.
.../packages/tpetra/core/src/Tpetra_FEMultiVector_def.hpp:45:/// \file Tpetra_MultiVector_def.hpp
.../packages/tpetra/core/src/Tpetra_MultiVector_def.hpp:43:/// \file Tpetra_MultiVector_def.hpp
```
Doing so exposes Sierra to build warnings like #7032.  This hinders Sierra (@rrdrake @sebrowne) from adopting GCC 8.3.0.  Sierra enables ETI, and in an ETI=ON build, downstream code would not normally see those `_def.hpp` headers.  Also, including these headers risks rebuilding code that Trilinos has already expensively built.

Don't include `_def.hpp` headers.  You may only use `MultiVector` with one of the enabled combinations of template arguments.  Tpetra's CMake logic prints those enabled combinations at configure time.  Here is example output in my local build (note how I'm enabling more Scalar types than typical Trilinos developers do):
```
Processing ETI support: TpetraCore
-- TpetraCore: Processing ETI / test support
-- Enabled Scalar types:        long long|float|double|std::complex<float>|std::complex<double>
-- Enabled LocalOrdinal types:  int
-- Enabled GlobalOrdinal types: long long
-- Enabled Node types:          Kokkos::Compat::KokkosSerialWrapperNode
-- Excluded type combinations: :
-- Set of enabled types, before exclusions: S={float} N={Kokkos::Compat::KokkosSerialWrapperNode} LO={int} GO={long long};S={double} N={Kokkos::Compat::KokkosSerialWrapperNode} LO={int} GO={long long};S={std::complex<float>} N={Kokkos::Compat::KokkosSerialWrapperNode} LO={int} GO={long long};S={std::complex<double>} N={Kokkos::Compat::KokkosSerialWrapperNode} LO={int} GO={long long};S={long long} N={Kokkos::Compat::KokkosSerialWrapperNode} LO={int} GO={long long};S={float} N={Kokkos::Compat::KokkosSerialWrapperNode} LO={int} GO={long long};S={double} N={Kokkos::Compat::KokkosSerialWrapperNode} LO={int} GO={long long};S={std::complex<float>} N={Kokkos::Compat::KokkosSerialWrapperNode} LO={int} GO={long long};S={std::complex<double>} N={Kokkos::Compat::KokkosSerialWrapperNode} LO={int} GO={long long}
```

**Comment by dridzal** [comment]
@mhoemmen , can you give us a possible replacement of that include line?  Can the choice of template arguments be automated?  Hopefully we won't have to hard-code/guess what the users may be building with ...

**Comment by mhoemmen** [comment]
@dridzal 
```cpp
#include "Tpetra_MultiVector.hpp"
```

**Comment by mhoemmen** [comment]
@dridzal wrote:
> Can the choice of template arguments be automated?

Use the defaults.

**Comment by dridzal** [comment]
@mhoemmen , you mean an empty template argument list like <>?

**Comment by mhoemmen** [comment]
@dridzal Yes -- you may omit template arguments, in which case the defaults will be used.  For example:
```cpp
Tpetra::Map<> map;
Tpetra::CrsGraph<> graph;
Tpetra::MultiVector<double> multivec;
```

**Comment by dridzal** [comment]
@mhoemmen , got it, thanks!  I think this is what we already do in most cases.

**Comment by dridzal** [comment]
@mhoemmen , I tried removing _def from the include, but now I get errors about incomplete types.

@gregvw , I don't have time to handle this right now, could you please take a look and fix as soon as you can (it's an issue for Sierra).  If I use

`
#include "Tpetra_MultiVector.hpp"
`

I get errors like

`
../../packages/rol/adapters/tpetra/test/vector/test_03.cpp: In function ‘int main(int, char**)’:
../../packages/rol/adapters/tpetra/test/vector/test_03.cpp:101:10: error: invalid use of incomplete type ‘class Tpetra::Vector<double, int, long long int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP> >’
     W_ptr->putScalar(2.0);
          ^
In file included from ../../packages/tpetra/core/src/Tpetra_MultiVector_decl.hpp:55:0,
                 from packages/tpetra/core/src/Tpetra_MultiVector.hpp:1,
                 from ../../packages/rol/adapters/tpetra/src/vector/ROL_TpetraMultiVector.hpp:55,
                 from ../../packages/rol/adapters/tpetra/src/vector/ROL_ScaledTpetraMultiVector.hpp:53,
                 from ../../packages/rol/adapters/tpetra/test/vector/test_03.cpp:49:
../../packages/tpetra/core/src/Tpetra_Vector_fwd.hpp:56:7: error: declaration of ‘class Tpetra::Vector<double, int, long long int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP> >’
 class Vector;
       ^
In file included from ../../packages/rol/src/zoo/ROL_Types.hpp:67:0,
                 from ../../packages/rol/src/elementwise/ROL_Elementwise_Reduce.hpp:49,
                 from ../../packages/rol/src/elementwise/ROL_Elementwise_Function.hpp:130,
                 from ../../packages/rol/src/vector/ROL_Vector.hpp:54,
                 from ../../packages/rol/adapters/tpetra/src/vector/ROL_TpetraMultiVector.hpp:54,
                 from ../../packages/rol/adapters/tpetra/src/vector/ROL_ScaledTpetraMultiVector.hpp:53,
                 from ../../packages/rol/adapters/tpetra/test/vector/test_03.cpp:49:
../../packages/rol/src/compatibility/teuchos/rcp/ROL_Ptr.hpp: In instantiation of ‘ROL::Ptr<T> ROL::makePtr(Args&& ...) [with T = Tpetra::Vector<double, int, long long int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP> >; Args = {Teuchos::RCP<Tpetra::Map<int, long long int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP, Kokkos::HostSpace> > >&, bool}; ROL::Ptr<T> = Teuchos::RCP<Tpetra::Vector<double, int, long long int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP> > >]’:
../../packages/rol/adapters/tpetra/test/vector/test_03.cpp:92:40:   required from here
../../packages/rol/src/compatibility/teuchos/rcp/ROL_Ptr.hpp:83:59: error: invalid use of incomplete type ‘class Tpetra::Vector<double, int, long long int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP> >’
   return Teuchos::rcp( new T(std::forward<Args>(args)...) );
                                                           ^
`

Thanks!

**Comment by gregvw** [comment]
@mhoemmen I don't see a Tpetra_Multivector.hpp. There is a _fwd, _decl, and _def.hpp in tpetra/core/src. Could we not just include the declaration in rol/adapters and include the definition in the test.cpp files?

**Comment by dridzal** [comment]
My guess is that it is auto-generated by the build system.  I tried using it, and it exists, but there is something in the template arguments that somehow requires the _def version.  Not sure I understand it.  Maybe @mhoemmen can shed some light on why _def would work and the other one wouldn't.

**Comment by mhoemmen** [comment]
@gregvw wrote:
> I don't see a Tpetra_MultiVector.hpp. Is this file created by CMake?

Yes.  It's created in the build directory and installed.  If you're using Vector, try including `Tpetra_Vector.hpp`.

**Comment by gregvw** [comment]
@dridzal @mhoemmen I haven't been able to produce a build error for our ROL/Tpetra examples using GCC 8.3.0 with ETI and -Werror -Wall. Replacing Tpetra_MultiVector_def.hpp with Tpetra_MultiVector.hpp in the ROL headers does lead to the Denis listed above. I was able to get a clean build and passing tests by including the _def file in the rol/adapters/tpetra/tests/vector/*.cpp files, however, I don't have anyway of testing downstream implications of this change since I wasn't getting the original warnings anyway.

**Comment by dridzal** [comment]
@gregvw can you please try including both Tpetra_MultiVector.hpp and Tpetra_Vector.hpp in your build (instead of the one _def file)?  Do you still get the error I got?  If you don't, then I can push that fix and sync with Trilinos.  Since we don't really have a way to replicate this warning, we'll have to do some trial and error.

**Comment by gregvw** [comment]
@dridzal Yes, including both of those files in ROL_TpetraMultiVector.hpp looks like it works as well. So unless told otherwise, this looks like a 2 line fix.

**Comment by dridzal** [comment]
Excellent!  @mhoemmen , I'll include these two files instead of the one _def file and sync ROL with Trilinos.  Since we can't test this (we don't get the original warning with gcc 8.3.0), Sierra developers will have to let us know.

**Comment by mhoemmen** [comment]
@dridzal @gregvw Thanks for doing this!  Not including `_def.hpp` files is the right thing to do.

**Comment by mhoemmen** [comment]
@rrdrake @sebrowne FYI
