### ISSUE TITLE
PyTrilinos:  Impossible to import Teuchos

### ISSUE THREAD

**Issue by kliegeois** [trilinos/Trilinos#7038]
## Bug Report
@trilinos/PyTrilinos

### Description
After compiling and installing Trilinos/develop, it is impossible to import Teuchos:

```
from PyTrilinos import Teuchos
ImportError: cannot import name Teuchos
```

Even when the `PYTHONPATH` is set to include the installed directory.

It is, however, possible to import Teuchos if the `PYTHONPATH` is set to include the build directory.

I think that the PyTrilinos Makefiles might not install the Teuchos/__init__.py file in certain cases/configurations.

The workaround that worked for me was to explicitly copy the file after the installation:

`cp ~/dev/TrilinosB/packages/PyTrilinos/src/PyTrilinos/Teuchos/__init__.py* ~/local/trilinos/lib/python2.7/site-packages/PyTrilinos/Teuchos/.`

### Steps to Reproduce
Configure script: 
[config.txt](https://github.com/trilinos/Trilinos/files/4347832/config.txt)

**Comment by pyt-viper** [comment]
A fix for this problem is contained in PR #7052.  Currently under review/testing.

**Comment by pyt-viper** [comment]
Fixed merged.

**Comment by kliegeois** [comment]
Thanks @pyt-viper !
