### ISSUE TITLE
Tpetra:  Add MatrixMarket reader that uses 2D Cartesian matrix distribution

### ISSUE THREAD

**Issue by kddevin** [trilinos/Trilinos#7045]
## Enhancement
@trilinos/tpetra 

Tpetra's MatrixMarket reader assumes a 1D (i.e., row-wise) matrix distribution.  @ndellingwood would like a reader that allows 2D Cartesian matrix distribution.  

The current MatrixMarket reader in Tpetra reads the matrix entirely on processor 0, constructs a CrsMatrix on processor 0, distributes relevant entries to each process, and constructs a distributed CrsMatrix with those entries.

For the 2D reader, I propose a different approach.  Processor 0 reads the entries in batches from the MatrixMarket file and broadcasts them to all processes.  Each processor keeps the entries that are assigned to it.  After all entries are broadcast, a distributed CrsMatrix will be constructed.  This algorithm would work for 1D distributions as well, and may be more scalable wrt memory use than the existing code.

**Comment by mhoemmen** [comment]
We've proposed before the idea that if you know the row Map, Process 0 could send batches of entries directly to the process that owns them.  @aprokop looked into that too, I think.  This would work for any distribution; for 2-D distributions, each receiving process would need to reject entries not in its column Map ("column Map filtering"), so you would end up sending and receiving more data than necessary.  Alternately, Process 0 could use both the row Map and the column Map to decide where to send entries.

To figure out what process owns what entry, Process 0 could do a Directory lookup (`Map::getRemoteIndexList`).  However, that's an expensive collective if the Map is noncontiguous.  For 2-D distributions, both row and column Maps are usually noncontiguous.  (The only overlapping Map you can build with one of the contiguous constructors is a locally replicated Map.)  Alternately, you could start by distributing data according to the Directory Maps, then doing a big redistribution at the end.

**Comment by kddevin** [comment]
The challenge (I learned in my stand-alone reader) is that the rowMap and colMap describing the Cartesian distribution are not necessarily the rowMap and colMap that we want to use in the CrsMatrix.  So we use some sort of rowMap or colMap to determine which nonzeros a processor keeps based on the Cartesian layout, then build a new rowMap (and let fillComplete compute a new colMap) based on the actual nonzeros that were kept by each processor.

**Comment by mhoemmen** [comment]
@kddevin This relates back to the general problem we've faced in `*petra` for years, namely how to distribute sparse graphs and matrices by entries instead of by rows and columns.  Doing this would require a way to map from a global index pair `i,j` to a single global index that could go into a `Map`.  If we could do that, then we could let `DistObject::getMap()` differ from `Crs{Graph, Matrix}::getRowMap()`.  That would fix the problem of unnecessary communication when redistributing to a 2-D distribution.

**Comment by kddevin** [comment]
The first implementation is merged.  Here is work that remains (see https://github.com/trilinos/Trilinos/pull/8472#issuecomment-760505239)

- [ ] Replace std::map data structures with two-level hash table, with hopes of speeding execution for extremely large files and further reducing memory use.
- [ ] Make template parameters consistent with Tpetra's:  add Node to Distribution so that permutation matrix has same type as CrsMatrix in Operator; remove global ordinal and use default, or at least reorder consistently with CrsMatrix.
- [ ] Add testing for binary file formats
- [ ] Add more tests of existing capabilities (symmetrizing, require diagonal entries, pattern matrices, MMFile option).
- [ ] Add support for per-processor matrix-market files and an Identity distribution for it
- [ ]  Add capability to read skew symmetric and Hermetian matrices (as in Teuchos:
```
143 typedef Teuchos::ScalarTraits<value_type> STS;
144 const value_type Aji = skew_ ?
145 value_type(-(conjugate_ ? STS::conjugate(Aij) : Aij)) :
146 (conjugate_ ? STS::conjugate(Aij) : Aij);
in Teuchos_MatrixMarket_SymmetrizingAdder.hpp
```
- [ ] add interface that does 1D distribution using user-provided maps
- [ ] support rectangular matrices and their range/domain vector distributions
- [ ] Deprecate existing read_sparse_file interface, preferring one that takes a parameter list instead of an argument list of parameters.
- [ ] Remove existing limited implementation, instead calling this new implementation (part of deprecation effort).

Future extensions:
- [ ] matrix market writer that works with 2D distributions
- [ ] full matrix market support with binary reader (values, rectangular, etc.)

Outstanding questions:

- [ ] Is LowerTriangularBlock distribution general enough to stay in Tpetra? Or should there be a way for users to write their own distribution to be used by readSparseFile?
- [ ] What distribution should be used when users provide one file per processor containing the processor's nonzeros? Should we have an "identity" distribution, that answers Mine=true for all nonzeros? Is information (e.g., chunk boundaries) still needed from a distribution in this case and, if so, how are they computed?

**Comment by rohany** [comment]
Hi, just poking on this issue -- support for loading rectangular matrices (or a workaround / description for how to do this) would be great, as I'm currently looking at getting some rectangular matrices in matrix-market files into Trilinos.
