### ISSUE TITLE
Set MueLu_ENABLE_Kokkos_Refactor_Use_By_Default=ON in at least on Trilinos PR build

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#7046]
The ATDM Trilinos configuration sets `MueLu_ENABLE_Kokkos_Refactor_Use_By_Default=ON` while none of the Trilinos PR builds do.  That allows failures like occurred in #7041 to slip into the ATDM Trilinos testing.

It would be nice if at least on of the Trilinos PR builds set  `MueLu_ENABLE_Kokkos_Refactor_Use_By_Default=ON`.  Alternatively, it might be nice to take one of the Trilinos PR builds and replace it with the ATDM Trilinos configuration to ensure that that configuration is always tested in PR testing.  (But that has the downside of every change to the cmake/std/atdm/ directory triggering a full build and testing of all packages in Trilinos.  Therefore, I am not sure I would vote for that but perhaps it is worth it.)

**Comment by bartlettroscoe** [comment]
CC: @cgcgcg 

FYI: Another bunch of failures cased by not having  `MueLu_ENABLE_Kokkos_Refactor_Use_By_Default=ON` set in at least one PR build (see #7088).

@trilinos/framework, can we pick on of the PR builds to turn on `MueLu_ENABLE_Kokkos_Refactor_Use_By_Default=ON`?  Can someone (e.g. me) just pick one of the PR builds and set this?  For example, can I just turn this on in the CUDA PR build?

**Comment by bartlettroscoe** [comment]
@trilinos/muelu, as this option is being used by all of the ATDM APPs, is there a reason why this can't be made the default for MueLu?

**Comment by jwillenbring** [comment]
@bartlettroscoe 

> @trilinos/framework, can we pick on of the PR builds to turn on MueLu_ENABLE_Kokkos_Refactor_Use_By_Default=ON? Can someone (e.g. me) just pick one of the PR builds and set this? For example, can I just turn this on in the CUDA PR build?

At first this sounded like something experimental to me, but upon closer inspection, it looks like this is what ATDM relies on, and possibly also pointing to functionality that Kokkos currently supports. If that is the case, if the CUDA build is the logical one to modify, go ahead and ask for a Framework team member review (me and/or others) and we can do this.

**Comment by cgcgcg** [comment]
> @trilinos/muelu, as this option is being used by all of the ATDM APPs, is there a reason why this can't be made the default for MueLu?

@bartlettroscoe FYI #7139

**Comment by cgcgcg** [comment]
#7139 removed `MueLu_ENABLE_Kokkos_Refactor_Use_By_Default`
