### ISSUE TITLE
Framework: Replace CUDA 9 PR build with CUDA >= 10.1

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#7047]
## Bug Report
@trilinos/framework @trilinos/tpetra @rrdrake @sebrowne @micahahoward

### Description

CUDA 10 differs quite a bit from CUDA 9.  For instance, CUDA 10.1 deprecates several CUDA run-time functions, and several functions in cuSPARSE, and introduces new functions that could help Trilinos and kokkos-kernels developers.  CUDA 10.1 also appears to fix bugs in CUDA 9.2, as we've observed in PR https://github.com/trilinos/Trilinos/pull/7021 .

According to @vbrunini, Sierra TF (the application) does not need CUDA 9 support any more.  It seems like all the machines we care about have CUDA >= 10.1 available for developers to use.

Thus, it would be good to switch the CUDA PR test from CUDA 9 to CUDA >= 10.1.  That would 

  - align PR tests more with customers' builds, 
  - encourage developers to remove calls to deprecated functions, and
  - encourage use of new functions that can solve performance and correctness issues.

We could and should keep a CUDA 9 build on the Dashboard for as long as Trilinos wants to support CUDA 9.

**Comment by ndellingwood** [comment]
In case this is helpful for those installing newer versions of CUDA, the CUBLAS lib and packaging for CUDA >= 10.1 has changed to be outside of the Cuda Toolkit install, [see comment here](https://forums.developer.nvidia.com/t/cublas-for-10-1-is-missing/71015/2)

I ran into this after installing CUDA 10.2 on my Ubuntu machine at home, where libcublas was previously found at $(CUDA_PATH)/lib64/libcublas.so (for CUDA <= 10.0, maybe some 10.1 versions?) but for 10.2 was found at /usr/lib/x86_64-linux-gnu/libcublas.so (this broke an install of Suitesparse for example and required modifying the configure makefile to update the CUBLAS_LIB path).

**Comment by mhoemmen** [comment]
@ndellingwood wrote:
> I ran into this after installing CUDA 10.2 on my Ubuntu machine at home

This appears to be an issue with our CUDA 10.2 install.  It keeps looking for libcublasLt.so and not finding it.  @vbrunini @sebrowne @rrdrake

**Comment by rrdrake** [comment]
@mhoemmen do you mean "module load sierra-devel/nvidia" is broken?

**Comment by mhoemmen** [comment]
@rrdrake just `sierra-devel/nvidia-10.2.89-openmpi-4.0.2`.  Other modules (in particular `sierra-devel/nvidia-10.1.243-openmpi-4.0.2`) work fine for me.

**Comment by jwillenbring** [comment]
@ZUUL42 is working on this activity. We are having some issues with 10.1 revision 243, but having better success with 10.1, revision 105. This may be due to system configuration more so than issues with CUDA itself.

**Comment by ndellingwood** [comment]
@jwillenbring @ZUUL42 does the issue have to do with CUBLAS? If so, after a certain revision of CUDA 10.1 the CUBLAS lib and packaging changed to be outside of the Cuda Toolkit, I have a link to more discussion in this comment in case that's helpful https://github.com/trilinos/Trilinos/issues/7047#issuecomment-600873240

**Comment by jwillenbring** [comment]
We are again considering upgrading the existing cuda build because there have been issues with #8129. @ZUUL42 please provide an updated status on this when you have it.

**Comment by jwillenbring** [comment]
@ZUUL42 

We now have a clean build on ride. We are investigating issues with the compile taking almost no time at all, even when using the option to clean the builds space. The tests do seem to be running properly.

[CDash results](https://testing.sandia.gov/cdash/index.php?project=Trilinos&display=project&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=63&value1=cuda_10.1.105-5&field2=buildname&compare2=63&value2=&field3=buildstamp&compare3=63&value3=Experimental)

**Comment by jwillenbring** [comment]
The CUDA 10 build is now running on dev->master, but not yet on PR.

**Comment by ZUUL42** [comment]
This new build was tested in dev to master just before and over the break.
On Monday, Jan 04, the new CUDA 10.1.105 build replaced the CUDA 9.2 build for PR testing.

**Comment by jwillenbring** [comment]
This is done and running regularly.
