### ISSUE TITLE
Framework: ascic test machines pull from repo that is no longer updated

### ISSUE THREAD

**Issue by jhux2** [trilinos/Trilinos#7050]
## Bug Report
@trilinos/framework @bartlettroscoe 

### Description
The `ascic` dashboard testing machines are testing a version of Trilinos that is no longer updated.  ~~This includes some PR testing.~~ EDIT: I was wrong, the ascic PR testing machines are being updated.  It's just some specialized and experimental builds.

The machines are pulling from a repo on software.sandia.gov that hasn't been updated since July, 2019.  This can be see [here](https://testing.sandia.gov/cdash/index.php?project=Trilinos&filtercount=1&showfilters=1&field1=site&compare1=63&value1=ascic).

Related to issue #6971.

**Comment by bartlettroscoe** [comment]
FYI: I can't do anything about this so I assigned the "Framework Tasks" label.

**Comment by cgcgcg** [comment]
@trilinos/framework

**Comment by jwillenbring** [comment]
I am looking into this. I needed to submit a service request related to this, so I have no ETA.

**Comment by jwillenbring** [comment]
Once my account had the proper access restored to it, the repo is now updating again. Please reopen if you see additional issues.

**Comment by jhux2** [comment]
@jwillenbring There are still ascic machines that are pulling from the wrong repo.   In the following link, look in the "Experimental" section:   https://testing.sandia.gov/cdash/index.php?project=Trilinos&subproject=MueLu&filtercount=1&showfilters=1&field1=site&compare1=63&value1=ascic#.  In the configure log, search for the key phrase "Base Git Repo".

The machines that are pulling from an old repo are ascic144, ascic166, ascic158, and ascic114.

**Comment by cgcgcg** [comment]
Any updates on this?

**Comment by jhux2** [comment]
@prwolfe @ZUUL42 @jwillenbring @bartlettroscoe Any idea who owns the tests on the aforementioned ascic machines?  If if it's impossible to update the source repo, is there a mechanism for excluding the results from the dashboard, apart from filtering during search?

**Comment by bartlettroscoe** [comment]
> is there a mechanism for excluding the results from the dashboard, apart from filtering during search?

@jhux2, not that I know of.  Can I help you set up your own CDash email summary using the cdash_analyze_and_report.py tool?  With that, you can filter the builds you see anyway you like.

**Comment by jhux2** [comment]
@bartlettroscoe I'd be very interested in getting a summary email.  Can you email or post an example of what the email would look like?  A few of the MueLu test machines use a pretty fragile script mechanism.

**Comment by bartlettroscoe** [comment]
> @bartlettroscoe I'd be very interested in getting a summary email. Can you email or post an example of what the email would look like? A few of the MueLu test machines use a pretty fragile script mechanism.

@jhux2, just copy one of the examples you see in:

* https://gitlab-ex.sandia.gov/atdm/TrilinosATDMStatus

I would recommend you copy:

* https://gitlab-ex.sandia.gov/atdm/TrilinosATDMStatus/-/blob/master/trilinos_promoted_atdm_builds_status.sh

Most of those arguments are optional and you can leave them out.  You should, however, provide a list of expected builds but you can skip the tests with issue tracker file in the argument `--tests-with-issue-trackers-file` (but if you have a lot of recurring failures that have GitHub issues for them, I would recommend you use that file).

Let's talk more offline. (There is not a lot of user documentation for that tool yet but I have been using it to stay on top of the large number of ATDM builds and it has helped a lot.)

**Comment by prwolfe** [comment]
The ascic machines are a joint ASC resource. The machines in question are reserved for Trilinos use in PR testing. Jim, what was the original purpose of these?

**Comment by jhux2** [comment]
@bartlettroscoe Thanks.  I'll have a look (probably not this week though) to see if I can set something up.  If I get stuck, I'll email.

**Comment by jwillenbring** [comment]
Closing. Please reopen if there is additional work needed here.
