### ISSUE TITLE
Percept:  IBM XL doesn't like that you place ETI before class specializations

### ISSUE THREAD

**Issue by jjellio** [trilinos/Trilinos#7058]
## Bug Report
@trilinos/percept 

### Description
IBM XL does not like that ETI definitions are placed before additional class specializations. The fix is to move all ETI stuff to the end of the file. (see the offending file below). This was observed with XL v16 with CUDA enabled (the error is from XL not nvcc)

### Steps to Reproduce
Challenging, you need to build on ATS2 w/IBM XL.  I have a makeshift ATDM environment for this, but it will only work on the LLNL testbed rzansel.

The an example of the error is:
```
/g/g20/jjellio/rzansel/empire/Trilinos/packages/percept/src/percept/mesh/mod/smoother/GenericAlgorithm_total_element_metric.cpp:296:74: error: explicit specialization of
      'operator()' after instantiation
template<> inline void GenericAlgorithm_total_element_metric< STKMesh> ::operator()(const unsigned &index, Double &mtot_loc) 
                                                                         ^
/g/g20/jjellio/rzansel/empire/Trilinos/packages/percept/src/percept/mesh/mod/smoother/GenericAlgorithm_total_element_metric.cpp:106:1: note: implicit instantiation first required
      here
operator()(index, mtot); 
^
/g/g20/jjellio/rzansel/empire/Trilinos/packages/percept/src/percept/mesh/mod/smoother/GenericAlgorithm_total_element_metric.cpp:315:81: error: explicit specialization of
      'operator()' after instantiation
template<> inline void GenericAlgorithm_total_element_metric< StructuredGrid> ::operator()(const unsigned &index, Double &mtot_loc)
```

I was able to work around the error by editing `GenericAlgorithm_total_element_metric.cpp`

and move all ETI bits to the end of the file (but still inside the namespace)

That is, the end of the file now looks like this copy and paste bonanza:

```
// ETI
template
void GenericAlgorithm_total_element_metric<STKMesh>::
run(unsigned iBlock);

template
void GenericAlgorithm_total_element_metric<StructuredGrid>::
run(unsigned iBlock);

// ETI
template
SGridGenericAlgorithm_total_element_metric< SmootherMetricUntangleImpl<StructuredGrid> >::
SGridGenericAlgorithm_total_element_metric(PerceptMesh *eMesh, Double mtot_in, size_t n_invalid_in);

template
SGridGenericAlgorithm_total_element_metric<HexMeshSmootherMetric>::
SGridGenericAlgorithm_total_element_metric(PerceptMesh *eMesh, Double mtot_in, size_t n_invalid_in);
// ETI
template
void SGridGenericAlgorithm_total_element_metric<SmootherMetricUntangleImpl<StructuredGrid> >::
operator()(const unsigned& index, Double& mtot_loc) const;
// ETI
template
void SGridGenericAlgorithm_total_element_metric<SmootherMetricUntangleImpl<StructuredGrid> >::run(unsigned iBlock);

template/*<>*/
void SGridGenericAlgorithm_total_element_metric<HexMeshSmootherMetric>::run(unsigned iBlock);

} // namespace percept
```

If you feel this is XL being a jackass (and not a violation of a rule), I can ask LLNL to open a bug report with IBM (but those things generally are slow moving).

I also did this out of EMPIRE's Trilinos clone, so my source is a little behind trilinos/develop

**Comment by rppawlo** [comment]
I've cc'd the percept team. They snapshot percept into trilinos, so we would need to get any changes into the internal development repo first.

**Comment by jjellio** [comment]
Thanks Roger I'm happy to test a patch.

**Comment by rppawlo** [comment]
@jjellio - Brian C. put up a PR an hour ago and it has already been merged into develop. Let us know if anything else is needed.
