### ISSUE TITLE
Mass srun startup failures on CTS-1 build on 'attaway' showing [unable to read "/etc/slurm/slurm.conf": Permission denied]

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#7060]
## Description

It the build `Trilinos-atdm-cts1-intel-18.0.2_openmpi-2.0.3_openmp_static_dbg` yesterday (testing day 2020-03-19) on 'attaway' show [here](https://testing-dev.sandia.gov/cdash/index.php?project=Trilinos&parentid=5311194), we saw 146 tests failing showing the error:

```
srun: error: s_p_parse_file: unable to read "/etc/slurm/slurm.conf": Permission denied
srun: error: ClusterName needs to be specified
srun: fatal: Unable to process configuration file
```

as shown in [this query](https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&date=2020-03-19&filtercount=4&showfilters=1&filtercombine=and&field1=groupname&compare1=61&value1=Specialized&field2=buildname&compare2=65&value2=Trilinos-atdm-cts1&field3=status&compare3=62&value3=passed&field4=testoutput&compare4=97&value4=srun%3A%20error%3A%20s_p_parse_file%3A%20unable%20to%20read%20.%2Fetc%2Fslurm%2Fslurm.conf.%3A%20Permission%20denied).

I don't know that we have seen that failure before but with an extra 146 failing tests overwhelms our ability to see other errors.  So this is a type of random system failure that needs to be filtered out of our CDash analysis approach.

**Comment by bartlettroscoe** [comment]
I am going to address this by just filtering out tests that match `srun: error: s_p_parse_file: unable to read "/etc/slurm/slurm.conf": Permission denied` from our TrilinosATDMStatus cdash_analyze_and_report.py drivers.

**Comment by jjellio** [comment]
I've pointed this out to the testbed team.

**Comment by bartlettroscoe** [comment]
As shown in [this query](https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&begin=2020-01-01&end=2020-06-08&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-&field2=status&compare2=62&value2=passed&field3=testoutput&compare3=97&value3=srun%3A%20error%3A%20s_p_parse_file%3A%20unable%20to%20read.*%2Fetc%2Fslurm%2Fslurm.conf.*Permission%20denied), this failure only happened in one build one day since 2020-01-01 and it was this build `Trilinos-atdm-cts1-intel-18.0.2_openmpi-2.0.3_openmp_static_dbg` on 'attaway' on testing day 2020-03-19.

Therefore, this appears to have been a rare fluke.  I will close as 'worksforme'.

**Comment by bartlettroscoe** [comment]
There is not 'worksforme' label so I will just close.
