### ISSUE TITLE
Intrepid2: Some Bases Don't Have Unique Names

### ISSUE THREAD

**Issue by CamelliaDPG** [trilinos/Trilinos#7071]
## Bug Report
@trilinos/intrepid2

### Description
As discussed in #7048, some of the new bases in Intrepid2 don't override the base class's `getName()` method.  Since some Intrepid2 methods rely on a unique name for caching of basis-related values, this can result in incorrect computations.

This issue is therefore to add in those `getName()` implementations.  For the new "derived" basis implementations this can be done in a fairly general way, as follows:
1. Each component basis (line H^1, line H(vol)) should implement a descriptive name.
2. TensorBasis should implement a name that depends on the names of its tensorial components, something along the lines of `basis1Name x basis2Name`.
3. DirectSumBasis should behave similarly, with something along the lines of `basis1Name + basis2Name`.
4. HCurl, HDiv bases should do something similar, with something like `HCurl(HGRADBasisName,HVOLBasisName)`.

**Comment by mperego** [comment]
This should be fixed now. Thanks @CamelliaDPG .
