### ISSUE TITLE
Teuchos: How is TEUCHOS_DEPRECATED defined?

### ISSUE THREAD

**Issue by keitat** [trilinos/Trilinos#7076]
## Question
@trilinos/\teuchos\>

I am trying to write my own CMAKE script (without Tribit) for teuchos.  Now I observe preprocessor macro **TEUCHOS_DEPRECATED** in packages/teuchos/core/src/Teuchos_ConfigDefs.hpp.   How is this macro defined?  I cannot find it neither in Teuchos_Config.h nor TeuchosCore_config.hpp.

**Comment by jhux2** [comment]
@trilinos/teuchos

**Comment by bartlettroscoe** [comment]
> I am trying to write my own CMAKE script (without Tribit) for teuchos

@keitat, why?

**Comment by rppawlo** [comment]
That's a very dangerous thing to try. I would recommend against that. Teuchos has quite a few defines that are set by autogenerating include files at configure time when cmake interrogates the system (all subpackages in trilinos do this).  After you configure trilinos, look in the build directory. Here's what's generated from my laptop configure:

```
$ find . -name '*.h*'
./core/src/TeuchosCore_config.h
./core/src/Teuchos_config.h
./remainder/src/TeuchosRemainder_config.h
./kokkoscompat/src/TeuchosKokkosCompat_config.h
./kokkoscomm/src/TeuchosKokkosComm_config.h
$ 
```

**Comment by keitat** [comment]
> > I am trying to write my own CMAKE script (without Tribit) for teuchos
> 
> @keitat, why?

This is a suggestion from Michael Wolf to see how we can build a few basic packages (teuchos and tpetra).

**Comment by bartlettroscoe** [comment]
@keitat, wou can get Teuchos to build and install as its own CMake project by just pointing to an installed TriBITS.  TriBITS has been updated several times in the past to get that working.  Otherwise, that is a big waste of time in my opinion.  Taking on another CMake build system will not be maintainable.  You are just touching the tip of the iceberg here.

**Comment by mhoemmen** [comment]
@keitat wrote:
> This is a suggestion from Michael Wolf to see how we can build a few basic packages (teuchos and tpetra).

This is a terrible idea.  Sierra just got rid of its "let's rewrite Trilinos' build system incompletely and only update it when the linker fails" build system for Trilinos.  Ask them how fun it was to maintain.

@rrdrake @sebrowne See what happens when you don't watch people carefully?  They go off and do insane things ;-)

**Comment by keitat** [comment]
The idea is not intended to change the build system for the current Trilinos.  It is intended for an exploration activity in xSDK-ECP.  In ECP, many users have complained that Trilinos' build system is deviating from the standard CMAKE.  

> That's a very dangerous thing to try. I would recommend against that. Teuchos has quite a few defines that are set by autogenerating include files at configure time when cmake interrogates the system (all subpackages in trilinos do this). After you configure trilinos, look in the build directory. Here's what's generated from my laptop configure:
> 
> ```
> $ find . -name '*.h*'
> ./core/src/TeuchosCore_config.h
> ./core/src/Teuchos_config.h
> ./remainder/src/TeuchosRemainder_config.h
> ./kokkoscompat/src/TeuchosKokkosCompat_config.h
> ./kokkoscomm/src/TeuchosKokkosComm_config.h
> $ 
> ```

I tried CMAKE's  configure_file() to generate all configure files.  Interestingly, "TEUCHOS_DEPRECATE" was not defined in these files, and I thought it is given by externally.

**Comment by keitat** [comment]
> @keitat wrote:
> 
> > This is a suggestion from Michael Wolf to see how we can build a few basic packages (teuchos and tpetra).
> 
> This is a terrible idea. Sierra just got rid of its "let's rewrite Trilinos' build system incompletely and only update it when the linker fails" build system for Trilinos. Ask them how fun it was to maintain.
> 
> @rrdrake @sebrowne See what happens when you don't watch people carefully? They go off and do insane things ;-)

Yes, I understand it is a crazy thing.   It is not intended for changing the main Trilinos development, just for exploration to see how the modern CMAKE itself can handle a few of Trilinos' basic packages.

**Comment by rppawlo** [comment]
@keitat - in the autogenerated Teuchos_config.h file I see the following at the bottom of the file:
```
#ifndef TEUCHOS_DEPRECATED
#  if (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 1))
#    define TEUCHOS_DEPRECATED  __attribute__((__deprecated__))
#  else
#    define TEUCHOS_DEPRECATED
#  endif
#endif

#ifndef TEUCHOS_DEPRECATED_MSG
#  if (__GNUC__ > 4 || (__GNUC__ == 4 && __GNUC_MINOR__ >= 5))
#    define TEUCHOS_DEPRECATED_MSG(MSG)  __attribute__((__deprecated__ (#MSG) ))
#  elif (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 1))
#    define TEUCHOS_DEPRECATED_MSG(MSG)  __attribute__((__deprecated__))
#  else
#    define TEUCHOS_DEPRECATED_MSG(MSG)
#  endif
#endif
```

**Comment by keitat** [comment]
Thanks!  I talked to @bartlettroscoe about leveraging the modern CMAKE and Tribits.   I am redirecting the work to demonstrate/comapre between Tribits+CMAKE and Spack+CMAKE.

**Comment by keitat** [comment]
> @keitat - in the autogenerated Teuchos_config.h file I see the following at the bottom of the file:
> 
> ```
> #ifndef TEUCHOS_DEPRECATED
> #  if (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 1))
> #    define TEUCHOS_DEPRECATED  __attribute__((__deprecated__))
> #  else
> #    define TEUCHOS_DEPRECATED
> #  endif
> #endif
> 
> #ifndef TEUCHOS_DEPRECATED_MSG
> #  if (__GNUC__ > 4 || (__GNUC__ == 4 && __GNUC_MINOR__ >= 5))
> #    define TEUCHOS_DEPRECATED_MSG(MSG)  __attribute__((__deprecated__ (#MSG) ))
> #  elif (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 1))
> #    define TEUCHOS_DEPRECATED_MSG(MSG)  __attribute__((__deprecated__))
> #  else
> #    define TEUCHOS_DEPRECATED_MSG(MSG)
> #  endif
> #endif
> ```

This is auto-generated from Teuchos_config.h.in and its adjacent CMakeList.txt.  Interestingly, the entire macro is auto-generated outside Teuchos.  Original, .in file is just a single line.

**Comment by rppawlo** [comment]
> This is auto-generated from Teuchos_config.h.in and its adjacent CMakeList.txt. Interestingly, the entire macro is auto-generated outside Teuchos. Original, .in file is just a single line: @TEUCHOS_DEPRECATED_DECLARATIONS@.

@keitat - it is generated in teuchos. At the top level of each package there is a call to a tribits macro.  If you look in Trilinso/packages/teuchos/CMakeLists.txt, it defines TEUCHOS_DEPRECATED_DECLARATIONS with:
```
TRIBITS_ADD_DEBUG_OPTION()

TRIBITS_ADD_SHOW_DEPRECATED_WARNINGS_OPTION()
```
This is the power of tribits. We can set the default for deprecated warnings for all trilinos packages and then override the default on a package-by-package basis. The same macros exist for DEBUG and ETI support as well. If a package doesn't need the DEBUG/DEPRECATED/ETI, then it just doesn't call the tribits macro.
