### ISSUE TITLE
Ifpack2: s-step Chebyshev

### ISSUE THREAD

**Issue by cgcgcg** [trilinos/Trilinos#7083]
## Enhancement
@trilinos/ifpack2 

Current state of s-step Chebyshev, Kokkos profiler on 32 GPUs on lassen with Tpetra distributor timers and @jjellio's MPI profiler.

[sStep-timing.log](https://github.com/trilinos/Trilinos/files/4390419/sStep-timing.log)

[classical-timing.log](https://github.com/trilinos/Trilinos/files/4390418/classical-timing.log)

**Comment by jhux2** [comment]
@bathmatt @csiefer2

**Comment by bathmatt** [comment]
So, it is odd that we don't see a large reduction in calls to Tpetra::DistObject::doTransfer inside of the chebyshev, it only went from 21000 to 15000, so only a 25% reduction.  Are we really doing what we think we're doing?  

The math kernel is about the same, 5.5s->5.7s

**Comment by cgcgcg** [comment]
Not quite sure what to make of that. We looked at the number of `MPI_Waitall`s (9000). This number makes sense: we call Chebyshev 3000 times as pre-smoother and 3000 times as post-smoother. Pre-smoothing has a zero rhs, so we only communicate the rhs data. Post-smoothing requires solution and rhs, and we currently do not fuse this communication since it would involve more memory.

**Comment by cgcgcg** [comment]
@bathmatt Figured out where the extra 6000 `doTransfer` are coming from. In the final step of a Chebyshev apply, we export from an overlapping solution vector into a non-overlapping one. This is a purely local operation, which is why we don't see any communication for it.
