### ISSUE TITLE
Add RUN_SERIAL test property to many ATDM Trilinos tests on CUDA builds to address timeouts

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#7112]
I need to add option `<fullTestName>_SET_RUN_SERIAL=[ON|OFF]` to `TRIBITS_ADD[ADVANCED_]TEST()` to add the CTest `RUN_SERIAL` test property and use to mark many CUDA tests in Trilinos GitHub issues #7090, #6805, #6804, #6801

But first, we need to finish up and merge #6840 to first get the work spread out over the GPUs to see if that resolves some of these timeouts.

**Comment by bartlettroscoe** [comment]
The issues with timeouts in the ATDM Trilinos builds was resolved by using the new ctest GPU allocation approach in #6840 so we don't need to add support for `<fullTestName>_RUN_SERIAL` for that ATDM Trilinos builds.  But we may need to add it for the Trilinos PR builds (see #7464).

**Comment by bartlettroscoe** [comment]
NOTE: Using the CTest resource allocation approach does not help on 'ride' for some reason so we are still getting quite a few timeouts there.  Therefore, I will go ahead and implement this option and apply `RUN_SREIAL` to several of the tests on 'ride' to avoid those timeouts.

**Comment by bartlettroscoe** [comment]
The updates from PR #8063 seem to be working well setting the `RUN_SERIAL` property.  See evidence in the PR #8063 (which was merged to 'atdm-nightly' a few days ago).  Also see no timeouts in the build ??? the last 3 days as shown here:

* https://testing.sandia.gov/cdash/index.php?project=Trilinos&begin=2020-09-01&end=2020-09-23&filtercount=1&showfilters=1&field1=buildname&compare1=61&value1=Trilinos-atdm-white-ride-gnu-7.2.0-openmp-debug

**Comment by bartlettroscoe** [comment]
@brian-kelley, do you mind if we remove the hard-coded `RUN_SERIAL` options added with the commit 81746c0546d5cabb574b61502afd233b54bf2d04 and instead only set `RUN_SERIAL` for the CUDA builds on 'ride'?  On the other machines like 'vortex', the CTest resource allocation approach (see commit 292e9acd732b370f44a9f7d7a341117e10249d30 and [ATDV-333](https://sems-atlassian-srn.sandia.gov/browse/ATDV-333)) of ensuring only a single test runs on each of the 4 GPUs runs at a time works really well and will allow all 4 of the `TpetraCore_gemm_m_eq_<X>_MPI_1` tests, for example, to run at the same time on the 4 GPUs on ATS-2 'vortex'.

Note, we should leave `RUN_SERIAL` on any real PERFORMANCE tests since those always need to run by themselves on an otherwise unloaded machine.

**Comment by brian-kelley** [comment]
@bartlettroscoe Yes, that's fine. I think adding RUN_SERIAL to non-performance tests was a temporary hack for RIDE.
