### ISSUE TITLE
ROL: extraneous print statements of 'Value norm'

### ISSUE THREAD

**Issue by ikalash** [trilinos/Trilinos#7115]
Looks like someone forgot to remove some print statements in ROL of 'Value norm' before pushing changes.

```
grep "Value norm" -r
rol/adapters/thyra/src/function/ROL_ThyraProductME_Objective.hpp:    std::cout << "Value norm: " << norm << std::endl;
rol/adapters/thyra/src/function/ROL_ThyraProductME_Objective.hpp:    std::cout << "In Gradient, Value norm: " << norm << std::endl;
```

It's causing Albany performance tests to time out: https://sems-cdash-son.sandia.gov/cdash/testDetails.php?test=47740&build=349 .  Can you please remove the print statement?

@trilinos/rol

**Comment by ikalash** [comment]
@mperego, git blame show you were the ones who put the print statement in, though it seems it was awhile ago (12/5/2019), so it's a bit surprising I'm just noticing it now.

**Comment by mperego** [comment]
Oh yeah, I know. Sorry. I forgot to remove it and I was waiting to have something more substantial  than that to do a PR. Anyway, I'm working on Piro/ROL next week and I'll make sure to fix it. Didn't expect it to cause any noticeable slow down.

**Comment by ikalash** [comment]
No problem.  Perhaps the slowdown is due to other things, now that you mention it.  Anyway, it would be good to remove the print statement at some point, when you have time.

**Comment by mperego** [comment]
I think #7118 fixed this. Closing.
