### ISSUE TITLE
panzer connectivity questions for multi blocks.

### ISSUE THREAD

**Issue by bathmatt** [trilinos/Trilinos#712]
@rppawlo @eric-c-cyr 
I've been looking through the ConnManager and take the function

   virtual const GlobalOrdinal * getConnectivity(LocalOrdinal localElmtId) const = 0;

This doesn't take a local element id, It takes an index into which local element id.

This code fails if you have multiple blocks because localIDs[id] is not consecutive.  
    const std::vector<LocalOrdinal> &localIDs = conn_->getElementBlock(block_ids[which_blk]);
    for (unsigned id=0;id<localIDs.size(); ++id) {
      int n_conn = conn_->getConnectivitySize(localIDs[id]);
      const GlobalOrdinal * connectivity = conn_->getConnectivity(localIDs[id]);
}

I assume this is the intended use?  

So, the documentation should be made cleaner?

**Comment by bathmatt** [comment]
In addition, tihs seems to be at odds with the workset.  A workset is for a block, but if you ask, what is my cell_local_id it returns the value of localIDs above and not id.

**Comment by eric-c-cyr** [comment]
It does take a local element id. There are a list of elements on each processor and they are ordered (somehow) the argument to getConnectivity is the local element id. Practically you would not just loop from 0 ... Nel and do stuff, you would loop over element blocks. 

So I'm a little confused about the confusion here (not to say its not confusing...right). Each processor has its own Id for each element, it is a "local id" so different processors can have local element id 37 for example. 

I'm sure the documentation could be clearer, I'm just trying to get a little more discussion out of you to understand the point of confusion.

**Comment by bathmatt** [comment]
That is the way I thought it was, but I was seeing something off in the debugger.
It turns out  there was a memory error where some of the connectivity arrays was overwritten with other values causing the confusion.

**Comment by eric-c-cyr** [comment]
What this an error in panzer?

**Comment by bathmatt** [comment]
No, my code.  but building on top of conn manager..
