### ISSUE TITLE
ATDM: Simplify finding and using TrilinosConfig.cmake

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#7125]
This story is to make it easier for customers of Trilinos to find and installed `TrilinosConfig.cmake` file using `find_package(Trilinos)` when using the ATDM Trilinos configuration and also make it easier to use that Trilinos once it finds it.  It turns out that is not so simple currently (see the discussion in https://cee-gitlab.sandia.gov/EM-Plasma/EMPIRE/issues/1309#note_388706).

I talked with Eric Cyr about this and the solution we came to was to:

* Have the `TrilinosConfig.cmake` file define a variable called `Trilinos_INSTALL_DIR` that points to `CMAKE_INSTALL_PREFIX` where Trilinos is installed.

* Have the ATDM Trilinos config installed `load_matching_env.sh` set the env var `export Trilinos_ROOT=<install-prefix>` instead of `export ATDM_TRILINOS_INSTALL_PREFIX=<install-prefix>`.

The motivation for adding `Trilinos_INSTALL_DIR` is that currently there is no direct way to find out that info without having to infer directory locations.  For example, CMake proper `find_packge(Trilinos)` will set `TrilinosConfig.cmake` but that points to the location of the file `TrilinosConfig.cmake`, **not** the location of the base install directory.  (For example, currently I think this is installed under `<install-prefix>/lib/cmake/Trilinos` which is fragile to assume that base install dir is `${Trilinos_DIR}/../../..`.)

The motivation for setting `export Trilinos_ROOT=<install-prefix>` in `<install-prefix>/load_maching_env.sh` is that as of CMake 3.12, `find_package(<PackageName>)` will first look for look for `<PackageName>Config.cmake` under the directory specified CMake cache var and env var `<PackageName>_ROOT`.  So once the customer runs `source <install-prefix>/load_maching_env.sh` then `find_package(Trilinos)` will automatically find that Trilinos through the env var `Trilinos_ROOT`.

Adding to `TrilinosConfig.cmake`  requires a change in TriBITS.  The latter is a change under `Trilinos/cmake/std/atdm`.  This will cover both of those changes.

**Comment by bartlettroscoe** [comment]
I have this implemented in the branch:

* https://github.com/TriBITSPub/TriBITS/tree/tril-7125-project-install-dir-and-more 

(which includes the branches from PRs tribitspub/tribits#308 and tribitspub/tribits#311 to facilitate testing all together) which passed Travis CI testing as shown here:

* https://travis-ci.org/github/TriBITSPub/TriBITS/builds/670808701

**Comment by bartlettroscoe** [comment]
The TriBITS part is now done and pushed to TriBITS 'master' in TriBITS commit https://github.com/TriBITSPub/TriBITS/commit/a7e24049ea70d39f0c369ee6601ee4652e96e71d.

Now to implement the trivial ATDM Trilinos part.

**Comment by bartlettroscoe** [comment]
The PR for this is #7126.

**Comment by bartlettroscoe** [comment]
@eric-c-cyr, have you had a chance to try this yet with EMPIRE?  Just seeing if I can close this Issue.

**Comment by eric-c-cyr** [comment]
The merge just went in (yesterday?). Let me see how the tests do this AM. I’m not expecting anything.

Sent from my iPad

On Apr 17, 2020, at 7:17 AM, Roscoe A. Bartlett <notifications@github.com> wrote:

﻿

@eric-c-cyr<https://github.com/eric-c-cyr>, have you had a chance to try this yet with EMPIRE? Just seeing if I can close this Issue.
