### ISSUE TITLE
Installing Trilinos getting a random error on the install

### ISSUE THREAD

**Issue by Tread84** [trilinos/Trilinos#7135]
I have been trying to install Trilinos on my new linux box and I keep getting this error:

CMakeFiles/ThyraEpetraAdapters_TestThyraDebugHang.dir/TestThyraDebugHang.cpp.o: In function `ThyraEpetraMultiVector_HangingInParallelDebug_UnitTest::runUnitTestImpl(Teuchos::basic_FancyOStream<char, std::char_traits<char> >&, bool&) const':
TestThyraDebugHang.cpp:(.text+0x101b): undefined reference to `Thyra::DefaultSpmdVectorSpace<double>::initialize(Teuchos::RCP<Teuchos::Comm<long> const> const&, long, long, bool)'
collect2: error: ld returned 1 exit status
packages/thyra/adapters/epetra/test/CMakeFiles/ThyraEpetraAdapters_TestThyraDebugHang.dir/build.make:137: recipe for target 'packages/thyra/adapters/epetra/test/ThyraEpetraAdapters_TestThyraDebugHang.exe' failed
make[2]: *** [packages/thyra/adapters/epetra/test/ThyraEpetraAdapters_TestThyraDebugHang.exe] Error 1
CMakeFiles/Makefile2:55292: recipe for target 'packages/thyra/adapters/epetra/test/CMakeFiles/ThyraEpetraAdapters_TestThyraDebugHang.dir/all' failed
make[1]: *** [packages/thyra/adapters/epetra/test/CMakeFiles/ThyraEpetraAdapters_TestThyraDebugHang.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 75%] Building CXX object packages/thyra/adapters/epetra/example/CMakeFiles/ThyraEpetraAdapters_sillyCgSolve_epetra.dir/createTridiagEpetraLinearOp.cpp.o
[ 75%] Building CXX object packages/thyra/adapters/epetra/test/UnitTests/CMakeFiles/ThyraEpetraAdapters_EpetraThyraWrappersUnitTests.dir/__/__/__/__/__/teuchos/comm/test/UnitTesting/Teuchos_StandardParallelUnitTestMain.cpp.o
[ 75%] Linking CXX executable ThyraEpetraAdapters_sillyCgSolve_epetra.exe
[ 75%] Built target ThyraEpetraAdapters_sillyCgSolve_epetra
[ 75%] Linking CXX executable ThyraEpetraAdapters_EpetraThyraWrappersUnitTests.exe
[ 75%] Built target ThyraEpetraAdapters_EpetraThyraWrappersUnitTests
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by jhux2** [comment]
@trilinos/thyra @trilinos/epetra

**Comment by bartlettroscoe** [comment]
@Tread84, 

It looks like this build issues related to this have appeared before:

* https://github.com/trilinos/Trilinos/issues?q=is%3Aissue+Thyra%3A%3ADefaultSpmdVectorSpace%3A%3Ainitialize+

What OS, compiler, etc. are being used?  Is this a Mac by any chance?

**Comment by jhux2** [comment]
@bartlettroscoe OP reports "linux box", so likely not a Mac.

**Comment by cgcgcg** [comment]
@Tread84 Can this one be closed? Seems you managed to install Trilinos.

**Comment by Tread84** [comment]
@cgcgcg I will close it down now! Thanks for the reminder
