### ISSUE TITLE
TriBITS:  Snapshot into Trilinos

### ISSUE THREAD

**Issue by jmgate** [trilinos/Trilinos#7136]
## Enhancement
@bartlettroscoe, could we snapshot TriBITS into Trilinos so Trilinos users could start taking advantage of the enhancements to `snapshot-dir.py`?

**Comment by bartlettroscoe** [comment]
@jmgate, should be addressed in PR #7138.   Please review and approve.

**Comment by bartlettroscoe** [comment]
@jmgate, PR #7138 has been merged.  Can you verify you have what you need and then close this issue?

**Comment by jmgate** [comment]
I can’t seem to VPN in this morning to test it out, but I can see that the `--exclude` option’s there, so I think we’re good.
