### ISSUE TITLE
Pytrilinos Epetra map: Cannot create overlapping maps

### ISSUE THREAD

**Issue by hakeemo** [trilinos/Trilinos#714]
I cannot seem to create a nonunique Epetra map in PyTrilinos.  When I run the following code 

```python
from PyTrilinos import Epetra
import numpy as np
len_global = 100

comm = Epetra.PyComm()
unique_map = Epetra.Map(len_global, 0 , comm)
print unique_map.MyGlobalElements()

overlap_length = 10

num_proc = comm.NumProc()
my_id = comm.MyPID()
my_range = np.arange(len_global//num_proc*my_id,
                     min(len_global//num_proc*(my_id+1) + overlap_length, len_global,len_global), dtype = np.int32)
my_range= my_range.tolist()
nonunique_map = Epetra.Map(len_global, my_range , 0, comm)
print nonunique_map.MyGlobalElements()
```

I get   
File "/home/tigon/trilinos-install/lib/python2.7/site-packages/PyTrilinos/Epetra.py", line 3222, in __init__
    this = _Epetra.new_Map(*args)
Epetra.Error: Error code = -4

Unless I set overlap_length=0, which works fine.

**Comment by jwillenbring** [comment]
CC: @wfspotz

**Comment by wfspotz** [comment]
The first argument can be quite confusing. The length here is the total number of elements on each processor (owned AND overlap) summed over the processors. Epetra will check the computed sum against what you gave it, and the -4 error indicates that they don't match.

I have always used -1 in the past, but apparently 0 works as well. These values tell Epetra to compute the length for you.
