### ISSUE TITLE
MueLu: issues with CUDA for Albany Land Ice problems starting 4/8/2020

### ISSUE THREAD

**Issue by ikalash** [trilinos/Trilinos#7149]
This is a spin-off from the following Albany issue: https://github.com/SNLComputation/Albany/issues/572 .  On 4/8/2020, we started having issues with a few Albany Land Ice tests that use the MueLu preconditioner: 

https://sems-cdash-son.sandia.gov/cdash/viewTest.php?onlyfailed&buildid=561 

Here is the error for 2 of the problems:
``
 Kokkos::Impl::ParallelReduce< Cuda > requested too much L0 scratch memory
 Traceback functionality not available
```
The third one seems to hang and timeout.  The tests ran just fine prior to 4/8 and we did not make any changes on the Albany side that would case these issues, so I'm wondering if something changed in Trilinos.  

@trilinos/muelu

**Comment by cgcgcg** [comment]
@ikalash Do you have "use kokkos refactor" in your MueLu parameter list? If not, can you add
"use kokkos refactor" = false? We recently changed the default behavior, so we're now running on device by default.

**Comment by ikalash** [comment]
@cgcgcg : no, we do not.  I will add it and see if it resolves the issue.  @jewatkins this may be relevant to some of the cases you were looking at too.

**Comment by jewatkins** [comment]
This is actually what I figured happened. We see that error when it's set to true. We still need to debug what the real issue is so it should be fine to set it to false for now so we don't lose out on catching other errors.

**Comment by ikalash** [comment]
@cgcgcg : your suggestion solved the problem - thanks!
