### ISSUE TITLE
Implement getHostLocalView for Xpetra::EpetraIntVector.

### ISSUE THREAD

**Issue by tawiesn** [trilinos/Trilinos#715]
The implementation is missing and prevents us from running MueLu with CUDA, see e.g. here:
http://testing.sandia.gov/cdash/testDetails.php?test=35071999&build=2595353

**Comment by tawiesn** [comment]
The attached patch provides the implementation of the missing routines.
[0008-Xpetra-implement-getHostLocalView-for-Xpetra-EpetraI.txt](https://github.com/trilinos/Trilinos/files/537025/0008-Xpetra-implement-getHostLocalView-for-Xpetra-EpetraI.txt)

@jhux2 Could you test it with CUDA and run the tests. It is compiling on my machine (but i have no CUDA).

**Comment by jhux2** [comment]
@tawiesn yes, I'll do this

**Comment by aprokop** [comment]
Adding @trilinos/xpetra 
I think a better way to such patches is to submit/commit them to muelu/Trilinos develop, and run selected nightlies on that branch on geminga. This way you won't have to ask @jhux2 each time we are touching Kokkos.

**Comment by tawiesn** [comment]
I have an account on geminga (just tried it), but the test setup is in /home/jhu on geminga which i do not have access. How can i run selected nightlies then? Maybe we should use a general "muelu" user on geminga that we have all access to, or create a muelu group or...
We could also use docker containers (at least as long as we do not try to compile for CUDA, as far as i know you can't use docker with CUDA...)

**Comment by jhux2** [comment]
@tawiesn Some of the MueLu and Xpetra tests are taking a really long time to run (>20 minutes), and in some cases timing out.  As far as I can tell, my configuration is the same as the OpenMP one on geminga.

**Comment by jhux2** [comment]
> @tawiesn Some of the MueLu and Xpetra tests are taking a really long time to run (>20 minutes), and in some cases timing out. As far as I can tell, my configuration is the same as the OpenMP one on geminga

This is not due to your patch btw, but something is not the same between my hand-build and the dashboard.

**Comment by tawiesn** [comment]
In the geminga ctest*.cmake files is the command SET(CTEST_TEST_TIMEOUT 900) which should be 15 minutes. You can try to increase that. You should also check the ctest call (probably in the crontab of the "jhu" user that i have no access to). There could be a --test-timeout flag which overwrites the parameter in the ctest file.

**Comment by jhux2** [comment]
> In the geminga ctest*.cmake files is the command SET(CTEST_TEST_TIMEOUT 900) which should be 15 minutes. You can try to increase that. You should also check the ctest call (probably in the crontab of the "jhu" user that i have no access to). There could be a --test-timeout flag which overwrites the parameter in the ctest file.

What I find strange is that according to the [dashboard](http://testing.sandia.gov/cdash/viewTest.php?buildid=2596543), the tests should run very quickly.  The slowest should take at most 5.5 minutes, and most should run in seconds.  So I don't believe increasing the timeout will help.

**Comment by aprokop** [comment]
> Some of the MueLu and Xpetra tests are taking a really long time to run (>20 minutes)

Oversubscription?

**Comment by jhux2** [comment]
> > Some of the MueLu and Xpetra tests are taking a really long time to run (>20 minutes)
> 
> Oversubscription?

So how would I tell if this is the case?

**Comment by tawiesn** [comment]
@jhux2 Have you set the OMP_NUM_THREADS variable? I usually set it to 2. I think, Kokkos should print a warning on the screen, too. But it probably cannot detect if you run several tests in different configurations at the same time....

**Comment by jhux2** [comment]
> @jhux2 Have you set the OMP_NUM_THREADS variable? I usually set it to 2. I think, Kokkos should print a warning on the screen, too. But it probably cannot detect if you run several tests in different configurations at the same time....

@tawiesn Thanks, that is the issue.  Setting OMP_NUM_THREADS to 2 fixes it.  For the record, this is set in cron_driver.sh for the nightly tests.

**Comment by jhux2** [comment]
@tawiesn MueLu_UnitTestsTpetra_MPI_[14] pass with your patch.  However, Xpetra_CrsMatrix_UnitTests_MPI_4 is failing.
[output-Xpetra_CrsMatrix_UnitTests_MPI_4.txt](https://github.com/trilinos/Trilinos/files/540172/output-Xpetra_CrsMatrix_UnitTests_MPI_4.txt)

**Comment by tawiesn** [comment]
@jhux2 Thanks.

The error message is
>  Kokkos::OpenMP::initialize ERROR : already initialized
>  Traceback functionality not available

I think the problem is that we explicitly call
   ` Kokkos::initialize();`
and 
    `Kokkos::finalize();`
in the beginning and in the end of the ConstructMatrixKokkos unit test.

That's the issue described in #522.

**Comment by tawiesn** [comment]
I think we just need to remove the Kokkos::initialize and the Kokkos::finalize call. I have to test this with some configurations.

**Comment by tawiesn** [comment]
Closing issue. No crashes any more with respect to missing implementations
