### ISSUE TITLE
Tpetra's Node ctor needs to strip "--kokkos-*" command-line args from Teuchos::GlobalMPISession if it initializes Kokkos

### ISSUE THREAD

**Issue by jjellio** [trilinos/Trilinos#718]
The kokkos programming guide specifies that arguments intended for Kokkos that are prefixed with kokkos, e.g., --kokkos-ndevices, will be removed from the argument list before returning from Kokkos::initialize(argc,argv).

Calling Teuchos::GlobalMPISession(argc,argv) with kokkos prefixed arguments in argv does not preserve this behavior. This seems acceptable, because GlobalMPISession has no knowledge of kokkos and does not promise to initialize Kokkos immediately. But leaving the arguments in argv can break commandline parsing (resulting in std::invalid_argument exceptions)

Perhaps a work around would be a Kokkos static function eat_kokkos_args(argc,argv) that would purge kokkos arguments without performing an initialize. This could work, since Trilinos will initialize Kokkos at some point, but Teuchos::GlobalMPISession should not have Kokkos arguments hard coded into it for removal.... Or, the behavior could change and with no promise of Kokkos arguments being removed. This complicates using Teuchos command line parsing as stated above.

@mhoemmen @crtrott @hcedwar @kokkos @Trilinos/Teuchos

**Comment by mhoemmen** [comment]
> Calling Teuchos::GlobalMPISession(argc,argv) with kokkos prefixed arguments in argv does not preserve this behavior.

This is actually correct behavior for Teuchos.  Teuchos doesn't know whether you want to initialize Kokkos, nor does it know _when_ you want to initialize Kokkos.  Teuchos::GlobalMPISession just saves those command-line arguments.  

If Tpetra's Node instance needs to call Kokkos::initialize, then it uses the command-line arguments saved in Teuchos::GlobalMPISession.

> But leaving the arguments in argv can break command line parsing (resulting in std::invalid_argument exceptions)

Could you give an example?

**Comment by jjellio** [comment]
Simple. 

1. Create a Teuchos  CommandlineParser.
2. SetOption() for options relevant to your app. (Kokkos options are not *your* options to set. They belong to Kokkos, so I will *not* add them)
3. parseResult will not be CommandLineProcessor::PARSE_SUCCESSFUL because kokkos options will still be in argv.

So the user either needs to know and add *every* possible Kokkos argument. Updating and maintaining that code as Kokkos changes, or they need to design code that does *not* fail when options are unrecognised. The latter being dangerous, and the former advocating the user take ownership of options that are not theirs.

If Trilinos advocates that users call Kokkos::initialize() themselves that is fine.  But I have never seen that pushed as a Trilinos development practice. (Similar to how users do not call MPI_Init() either).

Another option would be to have the command line parser become kokkos aware, so that it will return success if kokkos options remain at the end of its loop.


The broader question is how to handle command line options that belong to components of Trilinos. (E.g., xml files scope these options using tags)

**Comment by mhoemmen** [comment]
It's not right for Teuchos to remove Kokkos' command-line arguments until Kokkos actually gets initialized.  However, it _is_ true that Kokkos currently has no way to remove those command-line arguments from Teuchos::GlobalMPISession.  The latter is a bug, in the sense that it prevents Kokkos from manifesting its promised behavior, when running in Trilinos, if the user or test or example uses Teuchos::GlobalMPISession to capture command-line arguments.  As a result, it is fair to call this a missing feature in Teuchos::GlobalMPISession, which Tpetra needs to use once it is implemented.

**Comment by jjellio** [comment]
This issue is now being discussed under #763

This issue relates to who is responsible for removing command line arguments that below to a low level package.

The broader issue is how Trilinos should orchestrate the initialization and finalization of specific packages. Discussion should be moved to #763

**Comment by mhoemmen** [comment]
We can actually keep backwards compatibility of Teuchos::GlobalMPISession, while still getting the desired effect.

  1. Teuchos::GlobalMPISession keeps (pointers to) the original argc and argv, as well as the copies.
  2. Tpetra Node initialization, if it initializes Kokkos, strips out "--kokkos*" arguments from both the original and the copies.

**Comment by mhoemmen** [comment]
My #1889 fix will address this, by letting Kokkos::initialize process command-line arguments, rather than trying to do it ourselves.

**Comment by kddevin** [comment]
Related to getting rid of Node; need way to make sure Kokkos::initialize() has been called.
Encourage (eventually require?) use of Tpetra::initialize()?  Or require users to do MPI_Init and Kokkos::initialize()?

**Comment by mhoemmen** [comment]
Just to clarify: `Tpetra::Map`'s constructor (currently more accurately, Node's constructor) currently initializes Kokkos automatically if it has not already been initialized, and schedules Kokkos finalization if necessary.  However, `Tpetra::Map`'s constructor does not have access to `argc` and `argv` (`main`'s arguments).  Tpetra does its best in that case by trying to get the command-line arguments from `Teuchos::GlobalMPISession`.  However, `GlobalMPISession` just makes a deep copy of the command-line arguments; it does not attempt to modify them in place.

We can fix this easily in the unit tests by changing the "unit test main" `.cpp` file specified in CMake, to call `Tpetra::initalize` (or `MPI_Init` followed by `Kokkos::initialize`) explicitly.  Those functions take `argc` and `argv` directly, and can modify them.  However, this doesn't fix the problem for users, who don't know about this issue.

The best way to fix this is to force correct initialization of Tpetra.  The easiest way to do that is for Tpetra to know whether it was initialized correctly, by treating Tpetra like MPI: You can't use it unless MPI and Kokkos were both initialized.  (Do we want a `Tpetra::initialize` function that does this?)  `Tpetra::Map`'s constructor can check this (but see https://github.com/kokkos/kokkos/issues/1060 ) and throw or `MPI_Abort` immediately if not satisfied.

For finalization, we have two options:

  1. Schedule finalization of Kokkos (only if needed) automatically via an `atexit` or `MPI_Finalize` hook, or
  2. require users to finalize Kokkos and MPI manually.

Option 2 can work either via explicit calls to `Kokkos::finalize` (or `finalize_all`) and `MPI_Finalize`, or by making users call a `Tpetra::finalize` function.

Advantages of having `Tpetra::initialize` (and possibly `Tpetra::finalize`):

  - It's a common pattern in scientific libraries, found e.g., in Zoltan and PETSc,
  - users don't have to know about Kokkos or MPI,
  - Tpetra can use them to initialize (or finalize) other state (e.g., custom `MPI_Op`), and
  - ease of use (`Tpetra::initialize` can handle any combination of cases where users have already initialized MPI or Kokkos).

The main disadvantage is that users might not know they are using Tpetra.  For example, Xpetra and thus MueLu can pick Epetra or Tpetra via run-time parameter.  Would we force MueLu to have `initialize` and `finalize` functions?  On the other hand, MueLu already implicitly requires MPI and Kokkos initialization (the latter often happening implicitly through Tpetra's Node constructor) before using Tpetra anyway.

**Comment by mhoemmen** [comment]
Node is going away.
