### ISSUE TITLE
Tpetra: compilation error in OpenMP build

### ISSUE THREAD

**Issue by ikalash** [trilinos/Trilinos#7184]
One of the Albany OpenMP nightlies recently began failing at the Trilinos configuration step with the following error:

```
-- Tpetra: Disabling deprecated code
-- Determine whether Tpetra will assume that MPI is CUDA aware:
--   - Tpetra_ENABLE_CUDA is OFF, so Tpetra will assume that MPI is not CUDA aware.
CMake Error at packages/tpetra/CMakeLists.txt:404 (MESSAGE):
  Tpetra: No Kokkos execution space is enabled.  This message should only
  come up if you explicitly disabled all the Kokkos execution spaces.  If you
  don't want Tpetra to use threads, try setting Kokkos_ENABLE_SERIAL=ON.
```
I have the Kokkos_ENABLE_...  flags set.  Here is the configuration script: https://github.com/SNLComputation/Albany/blob/master/doc/nightlyTestHarness/do-cmake-trilinos-mpi-openmp-camobap .  Did something change in Tpetra that requires me to have a different set of packages enables?

@trilinos/tpetra

**Comment by rppawlo** [comment]
Kokkos was upgraded from 3.0 to 3.1 in trilinos last night. Might be related to that.

 @crtrott @srajama1

**Comment by kddevin** [comment]
@ikalash's script has
```
      -D Kokkos_ENABLE_Cuda_UVM:BOOL=OFF \
      -D Kokkos_ENABLE_OpenMP:BOOL=ON \
      -D Kokkos_ENABLE_Pthread:BOOL=OFF \
      -D Kokkos_ENABLE_Serial:BOOL=ON \
```
The Trilinos CMakeCache.txt has different capitalization
```
      Kokkos_ENABLE_CUDA_UVM
      Kokkos_ENABLE_OPENMP
      Kokkos_ENABLE_PTHREAD
      Kokkos_ENABLE_SERIAL
```

But Trilinos/packages/tpetra/CMakeLists.txt has not changed.  Was there a translation from mixed-case to upper-case before that is now gone?

**Comment by crtrott** [comment]
yeah there was one. We didn't intentionally remove it but it was always fragile. But it did warn about it if it changed it. But I guess its hard to see these warnings in the 1000 line output of Trilinos.

**Comment by kddevin** [comment]
Thanks @crtrott 
So, as I understand it, if @ikalash  upper-case's everything after Kokkos_ENABLE_ , the problem should go away.   This capitalization is the new standard for Kokkos.

**Comment by ikalash** [comment]
Oh, wow, I can't believe I didn't notice that.  That was the issue indeed.  Thanks for your help!
