### ISSUE TITLE
Thyra: matrix transpose apply plus equals bug

### ISSUE THREAD

**Issue by egphill** [trilinos/Trilinos#7187]
## Bug Report
@trilinos/thyra

### Description
For a Thyra::LinearOpBase A, the call

A.apply(TRANS,y,x,a,b);

should compute

y = b*y +a*A^t x

I've called this on a TpetraLinearOp, and it works fine when I run with 1 MPI rank, but with multiple MPI ranks, I'm not getting the b*y contribution, so it does

y = a*A^t x

This only happens in parallel and only with TRANS. Everything is fine with NOTRANS.

### Steps to Reproduce
On master or develop, create a LinearOpBase wrapped around a Tpetra CRS matrix (mine is a discrete gradient matrix, but it probably doesn't matter). Make a call to

A.apply(TRANS,y,x,a,b);

where b and y are non-zero, x is zero, and see if you get the expected vector b*y.

**Comment by bartlettroscoe** [comment]
@egphill, this is an issue specifically with the Thyra::TpetraLinearOp subclass implementation of apply()?

**Comment by egphill** [comment]
> @egphill, this is an issue specifically with the Thyra::TpetraLinearOp subclass implementation of apply()?

@bartlettroscoe I'm not sure. It's just the case where I've seen it arise.

**Comment by cgcgcg** [comment]
@egphill Is this still an issue, or is that the issue we fixed offline?

**Comment by egphill** [comment]
@cgcgcg This is still an issue. It's totally different than the other one.

**Comment by cgcgcg** [comment]
@egphill Is there a test in EMPIRE where I can see this behavior?

**Comment by bartlettroscoe** [comment]
Is this impacting EMPIRE?

**Comment by egphill** [comment]
It's not currently impacting EMPIRE. I've gotten around it by applying the matrix transpose apply and then a Vp_StV separately rather than trying to do both of these operations in one call. So it's not a high priority. I just wanted to document the bug.

**Comment by kddevin** [comment]
@egphill #7898 fixed a bug in Tpetra's SpMV when beta != 0 and TRANS.  Perhaps that fix will address this issue.  If you have some spare time, we'd be grateful for a test.  Thanks.

**Comment by egphill** [comment]
@kddevin I rewrote some code in EMPIRE to use the TRANS apply with a non-zero beta and it looks like it works now. Thank you! I think we can close this issue.

**Comment by kddevin** [comment]
Wow, thanks for the fast response, @egphill !  I'm glad this fix did the trick.
