### ISSUE TITLE
MatrixMarket output for thyra matrix/vector

### ISSUE THREAD

**Issue by bathmatt** [trilinos/Trilinos#719]
@bartlettroscoe 
Is there any interface for dumping thyra vectors or operators in the matrix market like format, or any format for that matter?  Debugging something and I'm getting NaNs and don't know why.

**Comment by tawiesn** [comment]
Maybe there is a more elegant way, but i probably would use the routines in Xpetra: use Xpetra::toXpetra(...) from packages/xpetra/sup/Utils/Xpetra_ThyraUtils.{hpp,cpp} to transform a Thyra object into the corresponding Xpetra object (works for Maps, MultiVectors, LinearOperators/Matrices)
Use the "Write" member functions from the Xpetra::IO class (packages/xpetra/sup/Utils/Xpetra_IO.hpp) to write out the Xpetra object in files in matrix market format (works for Xpetra::Map, Xpetra::MultiVector and Xpetra::Matrix).

The nice thing of using Xpetra: it works both for Epetra and Tpetra and it doesn't matter which *petra version is used in Thyra to store the objects...

**Comment by bartlettroscoe** [comment]
Sounds like Xpetra is the best solution for large objects.  For small objects, you can just use the [Teuchos::Describable](https://trilinos.org/docs/dev/packages/teuchos/doc/html/classTeuchos_1_1Describable.html) interface and use something like:

```
out << describe(*thyraObjRcp, Teuchos::VERB_EXTREME);
```

That is guaranteed to work for any underlying type, no matter what.  But for large objects, that will be expensive and produce too much data.

**Comment by bathmatt** [comment]
Thanks,
