### ISSUE TITLE
Amesos2 transpose capability appears defunct

### ISSUE THREAD

**Issue by dridzal** [trilinos/Trilinos#720]
I would like to use the transpose solve capability in @trilinos/amesos2 .  After a few email exchanges with @srajama1 the conclusion is that this functionality may not work.  For example, in Amesos2, in the file

  test/solvers/KLU2_UnitTests.cpp

there is a line

  amesos2_params.sublist("KLU2").set("Trans","TRANS","Solve with transpose");

If I look at KLU2, the "Trans"/"TRANS" pair is not allowed as an option.  I get a runtime error.  Similarly for the "Trans"/"CONJ" pair.

The parameter list validator suggests the "Transpose"/true(false) pair,

  amesos2_params.sublist("KLU2").set("Transpose",true)

which doesn't throw an error, but also doesn't solve with the transpose.

The transpose capability is extremely important in numerical optimization.  The @trilinos/rol team can create tests for it once available.

**Comment by hkthorn** [comment]
@dridzal @srajama1 The KLU2 templated tsolve() method has been fixed and the KLU2 solver interface has been updated to allow the use of both parameter options

amesos2_params.sublist("KLU2").set("Trans","TRANS","Solve with transpose");

and

amesos2_params.sublist("KLU2").set("Transpose",true)

to achieve a transposed solve using the current numeric factors.  Additionally, transpose capabilities have been added to the Pardiso_MKL interface.

It does appear that a user should be able to get a transposed solve using the "Transpose" option without the specific solver sublist, i.e.

amesos2_params.set("Transpose", true);

but that doesn't seem to be working.  @srajama1 is that supposed to work?

**Comment by srajama1** [comment]
I believe this capability to set "global" transpose for all solvers was an idea that never got to all the solvers. If it is useful to do that for ROL we can do that.

**Comment by hkthorn** [comment]
I guess the useful part is that you don't have to know the correct solver-specific parameter sublist name to request a transposed, or non-transposed, solve.  ROL is fine for now, but that would be a useful feature to have in the future.  I can also look into it as I have time.

**Comment by srajama1** [comment]
Thank you. Yes, that will be useful.

**Comment by hkthorn** [comment]
This is still and issue in that the global transpose flags should work for the subordinate solvers.

**Comment by srajama1** [comment]
Thanks @hkthorn ! We will prioritize it.
