### ISSUE TITLE
ShyLU:  ShyLU_NodeTacho_Tacho_TestOpenMPDoubleTaskScheduler_MPI_1 randomly segfaulting in GCC 4.8.4 PR build

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#7209]
## Bug Report
@trilinos/shylu, @trilinos/framework 

### Description

As shown in [this query](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&begin=2020-01-01&end=2020-04-20&filtercount=4&showfilters=1&filtercombine=and&field1=groupname&compare1=61&value1=Pull%20Request&field2=testname&compare2=61&value2=ShyLU_NodeTacho_Tacho_TestOpenMPDoubleTaskScheduler_MPI_1&field3=status&compare3=61&value3=failed&field4=testoutput&compare4=95&value4=signal%2011%20(Segmentation%20fault)) is very randomly failing in the Trilinos GCC 4.8.4 PR build twice:

Site | Build Name | Test Name | Status | Time | Proc Time | Details | Build Time | Processors
-- | -- | -- | -- | -- | -- | -- | -- | --
tr-test-7.novalocal | PR-7202-test-Trilinos_pullrequest_gcc_4.8.4-6361 | ShyLU_NodeTacho_Tacho_TestOpenMPDoubleTaskScheduler_MPI_1 | Failed | 280ms | 280ms | Completed (Failed) | 2020-04-19T21:18:22 MDT | 1
tr-test-7.novalocal | PR-7023-test-Trilinos_pullrequest_gcc_4.8.4-6064 | ShyLU_NodeTacho_Tacho_TestOpenMPDoubleTaskScheduler_MPI_1 | Failed | 220ms | 220ms | Completed (Failed) | 2020-03-16T09:17:47 MDT | 1

showing the segfault:

```
[----------] 5 tests from DenseByBlocks
[ RUN      ] DenseByBlocks.ldl
[       OK ] DenseByBlocks.ldl (0 ms)
[ RUN      ] DenseByBlocks.chol
[       OK ] DenseByBlocks.chol (1 ms)
[ RUN      ] DenseByBlocks.gemm
[       OK ] DenseByBlocks.gemm (4 ms)
[ RUN      ] DenseByBlocks.herk
[       OK ] DenseByBlocks.herk (2 ms)
[ RUN      ] DenseByBlocks.trsm
--------------------------------------------------------------------------
mpiexec noticed that process rank 0 with PID 20034 on node tr-test-7 exited on signal 11 (Segmentation fault).
--------------------------------------------------------------------------
```

What went wrong?  What should have happened?  Do you have an idea what might
fix things?  How has this bug affected you?  What are you trying to accomplish?
What specifically must we demonstrate to call this work complete?

### Steps to Reproduce

It is randomly failing in the PR build as per above.

**Comment by bartlettroscoe** [comment]
Unfortunately, the two PRs where this failed were both my PRs #7023 and #7202.

This is failing pretty rarely and only in this on GCC 4.8.4 build for some reason.  Perhaps just disable this one GCC 4.8.4 PR build?

**Comment by kyungjoo-kim** [comment]
I am okay with disabling this test. The task scheduler that I mainly use and do test by default is "Kokkos::TaskSchedulerMultiple". I would care for multiple task queue scheduler tests but I do not concern much on the others. Digging this compiler specific issue would takes a lot more efforts than the gain (at the end we do not use the single task queue scheduler in the production code).

@bartlettroscoe I do not know how to disable the test for a specific compiler. Let me know how you would like to resolve this issue.

**Comment by bartlettroscoe** [comment]
>  I do not know how to disable the test for a specific compiler. Let me know how you would like to resolve this issue.

@kyungjoo-kim, you can just disable this one test for this one PR build by adding:

```
set (ShyLU_NodeTacho_Tacho_TestOpenMPDoubleTaskScheduler_MPI_1_DISABLE ON CACHE BOOL "Temporarily disabled in PR testing")
```

to the file:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/PullRequestLinuxGCC4.8.4TestingSettings.cmake

in a new PR and get it merged.  (You will see other ShyLU tests getting disabled there as well.)

See:

* https://tribits.org/doc/TribitsBuildReference.html#disabling-specific-tests

Is there any reason why this failure would happen with the GCC 4.8.4 build and not the other 7 compilers/versions?   Having this fail twice in same GCC 4.8.4 build and not in any of the other builds seems like a pretty big coincidence.

Note that the GCC 4.8.4 build will go away as soon as C++14 is required for Trilinos (see #6260).

**Comment by ndellingwood** [comment]
@kyungjoo-kim the ` ShyLU_NodeTacho_Tacho_TestOpenMPDoubleChaseLevTaskScheduler_MPI_1` test randomly seg-faulted at the same `DenseByBlocks.trsm` routine as above, in PR #7182 with changes unrelated to Tacho
