### ISSUE TITLE
STK: STKUnit_tests_util_UnitTest_MPI_1 unit test UnitTestTimer.UnitTest randomly failing in several GCC and Clang PR builds starting 2020-04-06

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#7210]
## Bug Report
@trilinos/stk, @trilinos/framework 

### Description

As shown in [this query](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&begin=2020-01-01&end=2020-04-20&filtercount=4&showfilters=1&filtercombine=and&field1=groupname&compare1=61&value1=Pull%20Request&field2=testname&compare2=61&value2=STKUnit_tests_util_UnitTest_MPI_1&field3=status&compare3=61&value3=failed&field4=testoutput&compare4=97&value4=.*FAILED.*UnitTestTimer.UnitTest), the test `STKUnit_tests_util_UnitTest_MPI_1` has randomly failed in 7 PR builds since 2020-04-06 with the builds and times:

Site | Build Name | Test Name | Status | Time | Proc Time | Details | Build Time | Processors
-- | -- | -- | -- | -- | -- | -- | -- | --
ascic141 | PR-7202-test-Trilinos_pullrequest_clang_9.0.0-350 | STKUnit_tests_util_UnitTest_MPI_1 | Failed | 4s 240ms | 4s 240ms | Completed (Failed) | 2020-04-19T15:50:00 MDT | 1
ascic141 | PR-7186-test-Trilinos_pullrequest_gcc_8.3.0-636 | STKUnit_tests_util_UnitTest_MPI_1 | Failed | 2s 640ms | 2s 640ms | Completed (Failed) | 2020-04-17T14:18:30 MDT | 1
ascic141 | PR-7179-test-Trilinos_pullrequest_clang_9.0.0-323 | STKUnit_tests_util_UnitTest_MPI_1 | Failed | 1s 880ms | 1s 880ms | Completed (Failed) | 2020-04-16T10:20:24 MDT | 1
ascic141 | PR-7176-test-Trilinos_pullrequest_clang_9.0.0-312 | STKUnit_tests_util_UnitTest_MPI_1 | Failed | 1s 760ms | 1s 760ms | Completed (Failed) | 2020-04-15T03:47:28 MDT | 1
ascic115 | PR-7172-test-Trilinos_pullrequest_clang_9.0.0-310 | STKUnit_tests_util_UnitTest_MPI_1 | Failed | 1s 770ms | 1s 770ms | Completed (Failed) | 2020-04-14T23:06:50 MDT | 1
ascic114 | PR-7140-test-Trilinos_pullrequest_clang_9.0.0-231 | STKUnit_tests_util_UnitTest_MPI_1 | Failed | 1s 790ms | 1s 790ms | Completed (Failed) | 2020-04-08T00:11:22 MDT | 1
tr-host-0.novalocal | PR-7133-test-Trilinos_pullrequest_gcc_7.2.0-4322 | STKUnit_tests_util_UnitTest_MPI_1 | Failed | 2s 410ms | 2s 410ms | Completed (Failed) | 2020-04-06T23:40:19 MDT | 1

These all show the unit test failure:

```
*** Starting test UnitTestTimer.UnitTest from UnitTestTimer.cpp:162
*** Failure on proc 0 in /scratch/trilinos/jenkins/ascic141/workspace/trilinos-folder/Trilinos_pullrequest_clang_9.0.0/Trilinos/packages/stk/stk_unit_tests/stk_util/diag/UnitTestTimer.cpp:192
The difference between 0.02 and lap_time is 0.0035450267791748043, which exceeds 1.0e-3, where
0.02 evaluates to 0.02,
lap_time evaluates to 0.023545026779174805, and
1.0e-3 evaluates to 0.001.
[  FAILED  ] on 1 of 1 procs UnitTestTimer.UnitTest (8316866959936270644 ms)
```

As shown above, this test killed 7 PR testing iterations in 7 different PRs over the last 2 weeks: #7133, #7140, #7172, #7176, #7179, #7186, #7202 (the last one #7202 being mine).

### Steps to Reproduce

This is randomly failing in PR builds.

**Comment by alanw0** [comment]
Thanks @bartlettroscoe I'll try to take care of this right away. Looks like we allowed a yucky test to sneak in that's testing something based on time which is subject to noise. I'll robustify this.

**Comment by bartlettroscoe** [comment]
> I'll try to take care of this right away. Looks like we allowed a yucky test to sneak in that's testing something based on time which is subject to noise. I'll robustify this.

Thanks @alanw0!

**Comment by bartlettroscoe** [comment]
@alanw0, here is another CI iteration where this test broke:

* https://testing-dev.sandia.gov/cdash/index.php?project=Trilinos&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Linux-GCC-4.8.4-MPI_RELEASE_DEBUG_SHARED_PT_OPENMP_CI&field2=buildstamp&compare2=61&value2=20200714-0722-Continuous

where the test output [here](https://testing-dev.sandia.gov/cdash/test/23236217) showed:

```
[       OK ] StkEnv.DomainName (130215983150163 ms)
*** Starting test UnitTestTimer.UnitTest from UnitTestTimer.cpp:164
*** Failure on proc 0 in /scratch/rabartl/Trilinos.base/SEMSCIBuild/Trilinos/packages/stk/stk_unit_tests/stk_util/diag/UnitTestTimer.cpp:194
The difference between 0.04 and lap_time is 0.014682970046997069, which exceeds millisecTolerance, where
0.04 evaluates to 0.040000000000000001,
lap_time evaluates to 0.05468297004699707, and
millisecTolerance evaluates to 0.01.
[  FAILED  ] on 1 of 1 procs UnitTestTimer.UnitTest (8391161944126090837 ms)
```

@alanw0, did you get an email like the one below?  If not, we need to fix that.

----

From: admin@cdash.org <admin@cdash.org> 
Sent: Tuesday, July 14, 2020 4:48 AM
To: Bartlett, Roscoe A <rabartl@sandia.gov>
Subject: [EXTERNAL] FAILED (t=1): Trilinos/STK - Linux-GCC-4.8.4-MPI_RELEASE_DEBUG_SHARED_PT_OPENMP_CI - Continuous

A submission to CDash for the project Trilinos has failing tests. You have been identified as one of the authors who have checked in changes that are part of this submission or you are listed in the default contact list.

Details on the submission can be found at https://testing.sandia.gov/cdash/buildSummary.php?buildid=7442121.

Project: Trilinos
SubProject: STK
Site: ceerws1113
Build Name: Linux-GCC-4.8.4-MPI_RELEASE_DEBUG_SHARED_PT_OPENMP_CI
Build Time: 2020-07-14 07:22:56
Type: Continuous
Total Failing Tests: 1

*Failing Tests* 
STKUnit_tests_util_UnitTest_MPI_1 | Completed (Failed) | (https://testing.sandia.gov/cdash/testDetails.php?test=119963373&build=7442139)

-CDash on testing.sandia.gov

**Comment by alanw0** [comment]
Hi @bartlettroscoe, thanks for the heads-up. No, I didn't get an email notification. We will take another shot at de-sensitizing that pesky test.

**Comment by bartlettroscoe** [comment]
> No, I didn't get an email notification.

@alanw0, can you create a CDash account and then sign up to get emails for the label "STK"?

**Comment by alanw0** [comment]
@bartlettroscoe ok I think I registered and subscribed.
