### ISSUE TITLE
ATDM Config:  van1-tx2 Permissions in Install

### ISSUE THREAD

**Issue by jmgate** [trilinos/Trilinos#7221]
## Bug Report
@bartlettroscoe, @e10harvey 

### Description
When installing Trilinos on stria, the `van1-tx2` directory in `share/atdm-trilinos` has permissions `rwx------`.  The root install directory has permissions `rwxrwsr-t`, and those seem to get propagated to installs we have for other machines; that is, the `ats2` directory on vortex, e.g., has `rwxrwxr-x`.  Something's going wrong in the Trilinos install to remove permissions from `van1-tx2`.  If we could get this fixed ASAP, that'd be great.  In the meantime, I'll `chmod` the directories so EMPIRE can continue to test out the new installs.  Thanks guys.

**Comment by bartlettroscoe** [comment]
@jmgate, unfortunately, we are seeing this on all of the HPC machines (except for 'vortex').  See:

* https://sems-atlassian-srn.sandia.gov/browse/CDOFA-115?focusedCommentId=56438&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-56438

The install permissions from the CMake side of things uses:

```
  INSTALL( DIRECTORY "${ATDM_SYSTEM_DIR_SRC}"
    DESTINATION ${ATDM_CONFIG_SCRIPTS_INSTALL_DIR}
    USE_SOURCE_PERMISSIONS
    PATTERN "*.cmake" EXCLUDE )
```

What are the permissions on your cloned Trilinos git repo?  Are they `rwx------`?

We should not discuss other aspects of this on GitHub.    I will add more comments in:

* https://sems-atlassian-srn.sandia.gov/browse/ATDV-241

**Comment by jmgate** [comment]
Closing to continue discussion elsewhere.

**Comment by bartlettroscoe** [comment]
@jmgate, unfortunately, we are seeing this on all of the HPC machines (except for 'vortex').  See:

* https://sems-atlassian-srn.sandia.gov/browse/CDOFA-115?focusedCommentId=56438&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-56438

The install permissions from the CMake side of things uses:

```
  INSTALL( DIRECTORY "${ATDM_SYSTEM_DIR_SRC}"
    DESTINATION ${ATDM_CONFIG_SCRIPTS_INSTALL_DIR}
    USE_SOURCE_PERMISSIONS
    PATTERN "*.cmake" EXCLUDE )
```

What are the permissions on your cloned Trilinos git repo?  Are they `rwx------`?

We should not discuss other aspects of this on GitHub.    I will add more comments in:

* https://sems-atlassian-srn.sandia.gov/browse/ATDV-241
