### ISSUE TITLE
Panzer, Tpetra: periodic bc communication has incorrect indices

### ISSUE THREAD

**Issue by rppawlo** [trilinos/Trilinos#7223]
## Bug Report
@trilinos/panzer 
@trilinos/tpetra 
@kddevin 

### Description
For periodic BCs, the communication to send node information on a periodic sideset is losing values. We are seeing this when we exceed 128 cores on an empire problem. Local panzer unit testing is passing. exporting TPETRA_DEBUG=1 results in the output below. Since the maps were constructed with local and global sizes (not gid lists), the indices should be handled internally. The source map being constructed does not have entries on every node since the source represents a sideset.

The code in question starts on line 279 in:

Trilinos/packages/panzer/adapters-stk/src/stk_interface/Panzer_STK_PeriodicBC_Matcher.cpp

```
*********** Caught Exception: Begin Error Report ***********
MultiVector single-column pack kernel had 6721 out-of bounds index/ices.  Here they are: [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -\
1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, \
-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,\
 -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1\
, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -\
1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
```

### Steps to Reproduce
1. SHA1:  [insert here]
1. Configure script:  [attach here]
1. Configure log:  [attach here]
1. Build log:  [attach here]
1. Input deck:  [attach here]
1. Do this.
1. Do that.
1. Shake fist angrily at computer.
1. Run log:  [attach here]

**Comment by kddevin** [comment]
To confirm:  you see this problem when building with Serial node on ceelan, right?

**Comment by rppawlo** [comment]
yes. this was identified before the kokkos 3.1 promotion as well.
