### ISSUE TITLE
Framework:  Github.io Releases Page is Outdated

### ISSUE THREAD

**Issue by william76** [trilinos/Trilinos#7231]
## Documentation
@trilinos/framework 

The [Releases][1] page on the github.io page is outdated.

[1]: https://trilinos.github.io/releases.html

**Comment by jhux2** [comment]
I think issues like this one are more appropriate to filed against trilinos.github.io.  @maherou @william76 what do you think?

**Comment by wadeburgess** [comment]
Migrated to Jira.
