### ISSUE TITLE
TriBITS: in Categories=PERFORMANCE build, trying to install missing executables

### ISSUE THREAD

**Issue by brian-kelley** [trilinos/Trilinos#7232]
## Bug Report
@trilinos/framework 

### Description
When calling CMake installation functions like ``install_executable`` and ``install``, CMake reports that the target does not exist. For example, in packages/seacas/libraries/ioss/src/main/CMakeLists.txt:
```
# Executable created here:
 39 TRIBITS_ADD_EXECUTABLE(
 40   cth_pressure_map
 41   NOEXEPREFIX
 42   NOEXESUFFIX
 43   SOURCES cth_pressure_map.C vector3d.C
 44   )

# and installed here:
199 install_executable(cth_pressure_map)
```
This produces configure-time error:
```
Processing enabled package: SEACAS (Exodus, Ioss, Aprepro_lib)
-- SEACASIoss_pamgen_exodus_io_info: NOT added test because SEACASIoss_ENABLE_TESTS=', SEACAS_ENABLE_TESTS='''.
CMake Error at packages/seacas/CMakeLists.txt:104 (INSTALL):
  INSTALL TARGETS given target "cth_pressure_map" which does not exist.
Call Stack (most recent call first):
  packages/seacas/libraries/ioss/src/main/CMakeLists.txt:199 (install_executable)
```

There are errors like that for several executables in SEACAS, as well as the Panzer MiniEM BlockPrec example/test.

### Steps to Reproduce
My full configuration:
```
cmake \
  -DTrilinos_ENABLE_TESTS=ON \
  -DTrilinos_TEST_CATEGORIES=PERFORMANCE \
  -DMPI_EXEC_MAX_NUMPROCS=20 \
  -DTrilinos_ENABLE_Zoltan=ON \
  -DTrilinos_ENABLE_Tpetra=ON \
  -DTrilinos_ENABLE_MueLu=ON \
  -DTrilinos_ENABLE_Thyra=ON \
  -DTrilinos_ENABLE_Epetra=ON \
  -DTrilinos_ENABLE_Teko=ON \
  -DTrilinos_ENABLE_Panzer=ON \
  -DTrilinos_ENABLE_PanzerMiniEM=ON \
  -DTrilinos_ENABLE_EXPLICIT_INSTANTIATION=ON \
  -DTPL_ENABLE_MPI=ON \
  -DBUILD_SHARED_LIBS=ON \
../Trilinos
```

**Comment by brian-kelley** [comment]
Oh, I think it's because TRIBITS_ADD_EXECUTABLE has the "categories" like tests do, so cth_pressure_map has category BASIC so it's not getting added to a PERFORMANCE testing build. @bartlettroscoe What would be the best solution here? Can I build with ``-DTrilinos_TEST_CATEGORIES=BASIC,PERFORMANCE``?

I suppose the ideal solution would be to have a ``TRIBITS_ADD_EXECUTABLE_AND_INSTALL`` function.

**Comment by brian-kelley** [comment]
Actually, I need to avoid enabling BASIC tests because I want to be able to run "ctest" and just get the PERFORMANCE tests.

**Comment by bartlettroscoe** [comment]
@brian-kelley, I am not sure what is going on here.  But I think that it might be better to refactor SEACAS to use the `INSTALLABLE` option with `TRIBITS_ADD_EXECUTABLE()` as documented at:

* https://tribits.org/doc/TribitsDevelopersGuide.html#tribits-add-executable

@gsjaardema, is there a reason why the SEACAS CMakeLists.txt files are manaully calling `install(...)` for installable executables instead of just passing the `INSTALLABLE` option to `TRIBITS_ADD_EXECUTABLE()`?

@brian-kelley, can you experiment real quick of that fixes your problem or now?

**Comment by brian-kelley** [comment]
@bartlettroscoe Great, I'll try that.

**Comment by brian-kelley** [comment]
@bartlettroscoe Adding INSTALLABLE fixed all the errors in SEACAS and Percept. Panzer_MiniEM_BlockPrec is another executable that's manually installed, but it allows a custom install location so it's not as easy to fix:
```
 32 # allow the user to override the install location and
 33 # provide a simple defintion for the default
 34 # EXAMPLE_INSTALL_DIR/Panzer/
 35 IF (NOT DEFINED ${PACKAGE_NAME}_INSTALL_PREFIX)
 36   SET(${PACKAGE_NAME}_INSTALL_PREFIX "${${PROJECT_NAME}_INSTALL_EXAMPLE_DIR}/${PACKAGE_NAME}/")
 37 ELSE()
 38   # inform the user where it will go, since they overrode the default
 39   PRINT_VAR(${PACKAGE_NAME}_INSTALL_PREFIX)
 40 ENDIF()
 41 
 42 INSTALL(FILES ${${PACKAGE_NAME}_InputFiles}
 43         DESTINATION ${${PACKAGE_NAME}_INSTALL_PREFIX}
 44        )
 45 INSTALL(TARGETS "${PACKAGE_NAME}_BlockPrec"
 46         COMPONENT ${PACKAGE_NAME} RUNTIME DESTINATION ${${PACKAGE_NAME}_INSTALL_PREFIX})
```
Is overriding ``${PACKAGE_NAME}_INSTALL_PREFIX`` a standard TriBITS feature? If it is, INSTALLABLE would still work here.

Either way, this isn't blocking my PERFORMANCE build because I use BlockPrec for a PERFORMANCE test.

**Comment by bartlettroscoe** [comment]
CC: @gsjaardema 

@brian-kelley, okay, I see.  The desire is to install these into a different subdir.

But why is this configure error occurring?  Why does the executable target `cth_pressure_map` not exist?

**Comment by brian-kelley** [comment]
@bartlettroscoe ``cth_pressure_map`` and a few other executables actually didn't exist because they only had the default ``CATEGORIES BASIC`` and I was doing a test categories ``Trilinos_TEST_CATEGORIES=PERFORMANCE`` build. So the ``TRIBITS_ADD_EXECUTABLE`` was conditional on the categories of the build, but the install_executable was running unconditionally.

**Comment by bartlettroscoe** [comment]
@brian-kelley, can you try this patch:

```
diff --git a/packages/seacas/CMakeLists.txt b/packages/seacas/CMakeLists.txt
index 4237b09..e1d75c9 100644
--- a/packages/seacas/CMakeLists.txt
+++ b/packages/seacas/CMakeLists.txt
@@ -101,7 +101,9 @@ ENDIF ()
 #  ADD_BIN_EXECUTABLE(<executable>)
 #
 function(install_executable target)
-  INSTALL(TARGETS ${target} COMPONENT ${PACKAGE_NAME} RUNTIME DESTINATION ${${PROJECT_NAME}_INSTALL_RUNTIME_DIR})
+  IF (TARGET ${target})
+    INSTALL(TARGETS ${target} COMPONENT ${PACKAGE_NAME} RUNTIME DESTINATION ${${PROJECT_NAME}_INSTALL_RUNTIME_DIR})
+  ENDIF()
 endfunction()
 
 TRIBITS_PROCESS_SUBPACKAGES()
```

If that works, can you put in a PR for this?  (We will also need to pull off this patch and create a PR for the independent SEACAS GitHub repo as well.)

**Comment by brian-kelley** [comment]
@bartlettroscoe That did work, so I'll use that instead of INSTALLABLE for SEACAS.

**Comment by bartlettroscoe** [comment]
> @bartlettroscoe That did work, so I'll use that instead of INSTALLABLE for SEACAS.

@brian-kelley, can you then submit a Trilinos PR for this fix and also one to:

* https://github.com/gsjaardema/seacas

?

Otherwise, the next snaphsot of SEACAS into Trilinos will overwrite the change in Trilinos.

**Comment by brian-kelley** [comment]
Cross-referencing https://github.com/gsjaardema/seacas/pull/166

**Comment by gsjaardema** [comment]
@bartlettroscoe Did not know about `INSTALLABLE`.  will look into using it.

**Comment by gsjaardema** [comment]
@bartlettroscoe It looks like there are currently only 4 uses of `INSTALLABLE` in all of Trilinos. Is this a new option, or are there reasons that it should not be used that I am not aware of?  I'm fine using it, but want to make sure it is recommended.

**Comment by bartlettroscoe** [comment]
> @bartlettroscoe Did not know about INSTALLABLE. will look into using it.

@gsjaardema, I think it would not work for SEACAS as-is because these are not getting installed into the `<prefix>/bin` directory.  We would need to put add a new argument to `TRIBITS_ADD_ADVANCED_TEST()` to allow you to pick a different install subdir.

**Comment by gsjaardema** [comment]
As far as I know, my executables are being installed in <prefix>/bin...  My tests should not be installing any executables, so not sure what you mean by adding argument to `TRIBITS_ADD_ADVANCED_TEST()`.  

I modified SEACAS and everything seems to be installing correctly, so I must be misunderstanding your comment.

**Comment by brian-kelley** [comment]
@bartlettroscoe I didn't see any executables in SEACAS that were installed in a custom place. The only place I saw that was in Panzer_MiniEM_BlockPrec.

But for that case, it would be useful if ``TRIBITS_ADD_EXECUTABLE`` could accept a custom install location. Then ``INSTALLABLE`` could be used pretty much everywhere, I think.

**Comment by bartlettroscoe** [comment]
> But for that case, it would be useful if TRIBITS_ADD_EXECUTABLE could accept a custom install location. Then INSTALLABLE could be used pretty much everywhere, I think.

@brian-kelley, right.
