### ISSUE TITLE
Tpetra: kokkos 3.1 promotion has broken an application unit test with Tpetra

### ISSUE THREAD

**Issue by rppawlo** [trilinos/Trilinos#7234]
## Bug Report
@trilinos/tpetra 

### Description
After the kokkos 3.1 promotion, an empire unit test is failing.

The issue looks like it has to do with using tpetra vectors generated with offsetViewNonConst. A reproducer has been added to PR: https://github.com/trilinos/Trilinos/pull/7233 

### Steps to Reproduce
1. SHA1:  [insert here]
1. Configure script:  [attach here]
1. Configure log:  [attach here]
1. Build log:  [attach here]
1. Input deck:  [attach here]
1. Do this.
1. Do that.
1. Shake fist angrily at computer.
1. Run log:  [attach here]

**Comment by kddevin** [comment]
@rppawlo  See
https://github.com/kokkos/kokkos/issues/2981
