### ISSUE TITLE
ATDM: Mass CUDA failures in build Trilinos-atdm-sems-rhel7-cuda-9.2-Volta70-complex-shared-release-debug starting 2020-04-23

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#7251]
CC: @trilinos/kokkos, @kddevin (Trilinos Data Services Product Lead)

<Checklist>
<???: Add label "client: ATDM">
<???: Add label "ATDM Sev: Blocker" (by default but could be other "ATDM Sev: XXX")>
<???: Add label "type: bug"?>
<???: Add label "impacting: tests"?>
<???: Add label for affected packages (e.g. "pkg: MueLu", "pkg: Tpetra", "pkg: Kokkos", etc.)>
<???: Add label "PA: ???Project Area???" (e.g. "PA: Linear Solvers", "PA: Data Services")>
<???: Add milestone "Initial cleanup of new ATDM ..." or "Keep promoted ATDM ...">
<???: Once GitHub Issue is created, add entries for tests to TrilinosATDMStatus/*.csv files>

## Next Action Status

The machine 'ascicgpu14' was upgraded on 4/22/2020 and most likely is causing these problems.  Next: The powers a be need to fix 'ascicgpu14' (see [CDOFA-118](https://sems-atlassian-srn.sandia.gov/browse/CDOFA-118)) ...

## Description

As shown in [this builds query](https://testing-dev.sandia.gov/cdash/index.php?project=Trilinos&begin=2020-04-01&end=2020-04-24&filtercount=1&showfilters=1&field1=buildname&compare1=61&value1=Trilinos-atdm-sems-rhel7-cuda-9.2-Volta70-complex-shared-release-debug) and [this tests query](https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&date=2020-04-24&filtercount=7&showfilters=1&filtercombine=and&field1=groupname&compare1=61&value1=ATDM&field2=buildname&compare2=65&value2=Trilinos-atdm-&field3=status&compare3=62&value3=passed&field4=testoutput&compare4=94&value4=Error%20initializing%20RM%20connection.%20Exiting&field5=testoutput&compare5=94&value5=OPAL%20ERROR%3A%20Unreachable&field6=testoutput&compare6=96&value6=srun%3A%20error%3A%20s_p_parse_file%3A%20unable%20to%20read%20.%2Fetc%2Fslurm%2Fslurm.conf.%3A%20Permission%20denied&field7=testoutput&compare7=97&value7=cudaGetDeviceCount.*cudaErrorUnknown.*unknown%20error.*Kokkos_Cuda_Instance.cpp), we are seeing massive tests failures (451) in the build:

* `Trilinos-atdm-sems-rhel7-cuda-9.2-Volta70-complex-shared-release-debug`

all showing the error:

```
terminate called after throwing an instance of 'std::runtime_error'
  what():  cudaGetDeviceCount(&m_cudaDevCount) error( cudaErrorUnknown): unknown error /scratch/jenkins/ascicgpu14/workspace/Trilinos-atdm-sems-rhel7-cuda-9.2-Volta70-complex-shared-release-debug/SRC_AND_BUILD/Trilinos/packages/kokkos/core/src/Cuda/Kokkos_Cuda_Instance.cpp:223
Traceback functionality not available
```

starting on testing day 2020-04-23.

## Current Status on CDash

* [Build and test results for Trilinos-atdm-sems-rhel7-cuda-9.2-Volta70-complex-shared-release-debug for last 5 days](https://testing-dev.sandia.gov/cdash/index.php?project=Trilinos&begin=5%20days%20ago&end=now&filtercount=1&showfilters=1&field1=buildname&compare1=61&value1=Trilinos-atdm-sems-rhel7-cuda-9.2-Volta70-complex-shared-release-debug)

## Steps to Reproduce

One should be able to reproduce this failure on the failure on any of the 'ascicgpuXY' machines as described in:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md

or more specifically in:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#sems-rhel7-environment

The exact commands to reproduce this issue should be:

```
$ cd <some_build_dir>/

$ source $TRILINOS_DIR/cmake/std/atdm/load-env.sh \
    Trilinos-atdm-sems-rhel7-cuda-9.2-Volta70-complex-shared-release-debug

$ cmake \
 -GNinja \
 -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
 -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_ALL_PACKAGES=ON \
 $TRILINOS_DIR

$ make NP=16

$ ctest -j8
```

**Comment by bartlettroscoe** [comment]
Because this is swamping out CDash summary emails, we will need to filter these errors out these errors so we can see the remaining errors for now.

@trilinos/kokkos, could this be caused by a problem in Kokkos or is this more likely a system issue with the machine 'ascicgpu14' that is running this CUDA build.

**Comment by bartlettroscoe** [comment]
NOTE: As shown in [this query](https://testing-dev.sandia.gov/cdash/index.php?project=Trilinos&date=2020-04-23&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-&field2=buildname&compare2=63&value2=cuda&field3=buildname&compare3=63&value3=complex), this is the only `cuda+complex` build that we run to help protect GEMMA.

**Comment by bartlettroscoe** [comment]
Looking at the commits pulled on 2020-04-23 when this started failing as shown [here](https://testing-dev.sandia.gov/cdash/viewNotes.php?buildid=5397453#!#note1), I don't see any commits to Kokkos.   I only see one commit that might have impacted this:  1c1e574 which is:

```
1c1e574:  CONFIG: Need to specify use of parallel netcdf
Author: Greg Sjaardema <gdsjaar@sandia.gov>
Date:   Fri Apr 17 12:46:42 2020 -0600

M	cmake/std/atdm/ATDMDevEnvSettings.cmake
```

But that only changed how the Netcdf TPL is found.  That can't impact Kokkos.

Therefore, the current evidence points to a system problem with 'ascicgpu14' that runs this build?

I will report this to the GEMMA developers that maintain that machine.

**Comment by bartlettroscoe** [comment]
I reported this to the GEMMA developers in:

* https://sems-atlassian-srn.sandia.gov/browse/CDOFA-118

I am filtering these out of our CDash summary emails by pushing the commit:

```
*** Base Git Repo: TrilinosATDMStatus
commit 877aa282d12ce7cc3fbe5f6c7edf7a0ed4323e35 (HEAD -> master)
Author: Roscoe A. Bartlett <rabartl@sandia.gov>
Date:   Fri Apr 24 11:29:37 2020 -0400

    Exclude mass Kokkos CUDA initialiation failures (trilinos/Trilinos#7251)
    
    We have to exclude these for now since they flood our CDash summary emails.

M       trilinos_promoted_atdm_builds_status.sh
```

**Comment by ndellingwood** [comment]
@bartlettroscoe I'm not familiar with ascicgpuXY machines, but you can try running the command `nvidia-smi` and if you receive an error message (instead of output about the NVIDIA driver version and list of available GPUs) then there may be some sort of driver issue. I think there was some maintenance work earlier this week on some of the CEE machines, maybe that would impact the ascicgpu machines?

**Comment by ndellingwood** [comment]
I've run into issues on machines where a restart corrupts the NVIDIA driver and the code executes but results are garbage, though `nvidia-smi` returns correct system info. 
In these cases I compile a small test Cuda code, and if the Cuda runtime call doesn't return the expected answer it could indicate issues with the driver and that likely requires reinstall of the driver. For example:

```cuda
// Filename: cuda_device.cu

// Usage instructions:
// 1. Load cuda module (if necessary) and allocate compute node (if necessary)
// 2. Compile the code: nvcc cuda_device.cu
// 3. Run the code: ./a.out

// Expected output: two lines per available device, e.g.
//  Device Number: 0
//     Device name: Tesla K40c

#include <cstdio>

int main() {
  int nDevices;

  cudaGetDeviceCount(&nDevices);
  for (int i = 0; i < nDevices; i++) {
    cudaDeviceProp prop;
    cudaGetDeviceProperties(&prop, i); 
    printf("Device Number: %d\n", i); 
    printf("  Device name: %s\n", prop.name);
  }
}
```

**Comment by bartlettroscoe** [comment]
@ndellingwood, as I commented in [CDOFA-118](https://sems-atlassian-srn.sandia.gov/browse/CDOFA-118?focusedCommentId=57128&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-57128) just now, it does look like that machine 'ascicgpu14' may have gotten updated on and rebooted on 4/22/2020.

Therefore, I will mark this issue with `ATDM Env Issue` and remove the Kokkos and Data Services labels so this will not count against those.

Thanks for the info!

**Comment by bartlettroscoe** [comment]
However, this issue needs to stay open until they can fix that machine because we now have on testing of `cuda+complex` of Trilinos at all with this build broken :-(

**Comment by bartlettroscoe** [comment]
Note that we also see other types of failures like 22 Sacado failures shown in [this query](https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&date=2020-04-24&filtercount=8&showfilters=1&filtercombine=and&field1=groupname&compare1=61&value1=ATDM&field2=buildname&compare2=65&value2=Trilinos-atdm-&field3=status&compare3=62&value3=passed&field4=testoutput&compare4=94&value4=Error%20initializing%20RM%20connection.%20Exiting&field5=testoutput&compare5=94&value5=OPAL%20ERROR%3A%20Unreachable&field6=testoutput&compare6=96&value6=srun%3A%20error%3A%20s_p_parse_file%3A%20unable%20to%20read%20.%2Fetc%2Fslurm%2Fslurm.conf.%3A%20Permission%20denied&field7=testoutput&compare7=96&value7=cudaGetDeviceCount.*cudaErrorUnknown.*unknown%20error.*Kokkos_Cuda_Instance.cpp&field8=testoutput&compare8=97&value8=cudaMallocManaged.*cudaErrorUnknown.*unknown%20error.*Sacado_DynamicArrayTraits.hpp) showing the error:

```
terminate called after throwing an instance of 'std::runtime_error'
  what():  cudaMallocManaged( (void**) &m, sz*sizeof(T), cudaMemAttachGlobal ) error( cudaErrorUnknown): unknown error /scratch/jenkins/ascicgpu14/workspace/Trilinos-atdm-sems-rhel7-cuda-9.2-Volta70-complex-shared-release-debug/SRC_AND_BUILD/Trilinos/packages/sacado/src/Sacado_DynamicArrayTraits.hpp:195
Traceback functionality not available
```

and two Xpetra failures shown in [this query](https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&date=2020-04-24&filtercount=8&showfilters=1&filtercombine=and&field1=groupname&compare1=61&value1=ATDM&field2=buildname&compare2=61&value2=Trilinos-atdm-sems-rhel7-cuda-9.2-Volta70-complex-shared-release-debug&field3=status&compare3=62&value3=passed&field4=testoutput&compare4=94&value4=Error%20initializing%20RM%20connection.%20Exiting&field5=testoutput&compare5=94&value5=OPAL%20ERROR%3A%20Unreachable&field6=testoutput&compare6=96&value6=srun%3A%20error%3A%20s_p_parse_file%3A%20unable%20to%20read%20.%2Fetc%2Fslurm%2Fslurm.conf.%3A%20Permission%20denied&field7=testoutput&compare7=96&value7=cudaGetDeviceCount.*cudaErrorUnknown.*unknown%20error.*Kokkos_Cuda_Instance.cpp&field8=testoutput&compare8=96&value8=cudaMallocManaged.*cudaErrorUnknown.*unknown%20error.*Sacado_DynamicArrayTraits.hpp) where are:


Site | Build Name | Test Name | Status | Time | Proc Time | Details | Build Time | Processors
-- | -- | -- | -- | -- | -- | -- | -- | --
sems-rhel7 | Trilinos-atdm-sems-rhel7-cuda-9.2-Volta70-complex-shared-release-debug | Xpetra_Laplace1D-Tpetra_MPI_4 | Failed | 590ms | 2s 360ms | Completed (Failed) | 2020-04-24T04:33:14 MDT | 4
sems-rhel7 | Trilinos-atdm-sems-rhel7-cuda-9.2-Volta70-complex-shared-release-debug | Xpetra_Laplace1D-Xpetra_MPI_4 | Failed | 590ms | 2s 360ms | Completed (Failed) | 2020-04-24T04:33:14 MDT | 4

and show nondescript errors:

```
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpiexec detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[11486,1],2]
  Exit code:    1
--------------------------------------------------------------------------
```

I will need to filter these errors out of the CDash summary emails as well.

**Comment by bartlettroscoe** [comment]
FYI: This was a problem with the CUDA driver on the machine 'asicgpu14' after a recent upgrade.  This was fixed by running:

```
$ rmmod nvidia
$ nvidia-smi
```

See [CDOFA-118](https://sems-atlassian-srn.sandia.gov/browse/CDOFA-118) for details.

Closing as complete.
