### ISSUE TITLE
We have been down this road before.

### ISSUE THREAD

**Issue by VictorEijkhout** [trilinos/Trilinos#7260]
Search for "trilinos download", and I get:

https://trilinos.github.io/download-12-0.html

which has no indication that it's out of date. 

But I know better so instead of downloading I follow the github link:

https://github.com/trilinos/trilinos.github.io

which has last been updated 4 months ago, so it must be correct, not?

Well, the lack of releases is a little suspicious.

Somehow and I don't remember how, I find:

https://github.com/trilinos/Trilinos

which looks equally legit, but it has tons of releases.

So what is the one repository and the other? And why a horrendously out of date web site?

**Comment by maherou** [comment]
Completed as mentioned on trilinos.github.io
