### ISSUE TITLE
Framework: PR Testing does not cover configuration w/ "Zoltan enabled, Zoltan2 disabled"

### ISSUE THREAD

**Issue by mayrmt** [trilinos/Trilinos#7265]
## Bug Report
@trilinos/framework @jwillenbring @ZUUL42

### Description

Configurations with `Zoltan` enabled, but `Zoltan2` disabled seem not to be covered by PR testing. Otherwise, the build error reported in #7263 should have been discovered during PR testing.

### Nest Steps

1. Discuss need for an autotester build with "Zoltan enabled, Zoltan2 disabled".
1. If need is recognized, create such a build.

**Comment by cgcgcg** [comment]
I don't think that we need an Epetra-only autotester build. We could add a nightly build to one of our systems, but I'm not sure how valuable this is, given that Epetra will be removed in the hopefully not too distant future.

**Comment by mayrmt** [comment]
@cgcgcg Out of curiosity and since some of our application codes rely on Epetra, what's the time line for there? I'm hearing this for the first time.

**Comment by cgcgcg** [comment]
@mayrmt No time line so far. I'd think that there will be an announcement once we get there.
As for an Epetra-only build, we have one: https://testing.sandia.gov/cdash/buildSummary.php?buildid=6905411
It's just been failing for a while now.
