### ISSUE TITLE
Teuchos on PPC64: The following tests FAILED: asSafe_stringToReal_UnitTest

### ISSUE THREAD

**Issue by nschloe** [trilinos/Trilinos#727]
On PPC64, I'm getting one test failure

```
The following tests FAILED:
   65 - TeuchosCore_TypeConversions_UnitTest_MPI_1 (Failed)
Errors while running CTest
```

```
65:  Test that code {valD = asSafe<double> (os.str ());} throws std::range_error: failed (code did not throw an exception at all)
65:  Test that code {valD = asSafe<double> (os.str ());} throws std::range_error: failed (code did not throw an exception at all)
[...]
65: The following tests FAILED:
65:     1. asSafe_stringToReal_UnitTest ....
```

Test passes on AMD64.

All details [here](https://launchpad.net/~nschloe/+archive/ubuntu/trilinos-nightly/+build/11059421/+files/buildlog_ubuntu-xenial-ppc64el.trilinos_12.9~20161022141326-06126655-1xenial1_BUILDING.txt.gz).

**Comment by nmhamster** [comment]
@nschloe - I've reported this bug a few times with different compiler combinations. You can see other bug reports for comments from @mhoemmen and @bartlettroscoe. Are you running on PPC64LE or PPC64BE?

**Comment by nschloe** [comment]
This is PPC64**LE** (Debian's default).
