### ISSUE TITLE
Amesos2: suspected memory leak in classic basker

### ISSUE THREAD

**Issue by maartenarnst** [trilinos/Trilinos#7274]
## Bug Report
@trilinos/amesos2 
@srajama1

### Description
I use Amesos2's classic basker as the linear solver in a Newton-type nonlinear solver.  I notice that as the Newton-type nonlinear solver goes through more and more iterations and classic basker is thus called more and more times to solve a linear system, the memory used by the program keeps increasing.  Ultimately, my code starts swapping and gets stuck.  The issue disappears when I use 'klu2' in place of 'basker.'

I suspect a memory leak related to the allocation of two arrays in dynamic memory, which do not appear to be freed later in the code.  This issue may have something to do with changes that appear to have been made in classic basker's memory management a while ago.  The code freeing these arrays was commented out, but it appears that it was not replaced with new code.

Specifically, in the 'develop' branch, in amesos2/src/basker/basker_def.hpp, on lines 253 and 255, two arrays 'tptr = new ... ' and 'X = new ... ' are allocated in dynamic memory.  On lines 603 and 604, there are now comments '//BASKERFREE(X)' and '//BASKERFREE(tptr)' but these lines do not appear to have been replaced with delete calls.

I replaced on line 603 '//BASKERFREE(X)' with 'delete [] X;' and on line 604 '//BASKERFREE(tptr)' with 'delete [] color;'  I used 'delete [] color;' instead of 'delete [] tptr;' because the basker code copies the pointer 'tptr' to the pointer 'color' and modifies 'tptr'.  In my code, the issue with the increasing memory consumption is solved after making this change.

I have not run any code with valgrind or any other tool to diagnose the memory use.

I remain available for any further information that may be helpful.  Thank you very much in advance!

**Comment by jhux2** [comment]
@trilinos/amesos2

**Comment by ndellingwood** [comment]
PR #7404 issued with the desired fix (along with some unit test fixes). Thanks @maartenarnst for reporting and testing the fix beforehand!

**Comment by srajama1** [comment]
@maartenarnst : Sorry for missing this issue. The github volume has become too much to manage. This should be a pretty easy to fix. I am not sure why these got commented out. Let me check.

**Comment by ndellingwood** [comment]
@srajama1 I put in a PR with the fix #7404, ready for review

**Comment by srajama1** [comment]
@ndellingwood : Thanks for the PR ! I just approved it

@maartenarnst : Thanks for the fix ! This is just an embarrassing bug and I worry how it went without getting caught for years.

**Comment by maartenarnst** [comment]
Thanks @ndellingwood  and @srajama1!
