### ISSUE TITLE
Teuchos: ~ActiveRCPNodesSetup: exception thrown in destructor

### ISSUE THREAD

**Issue by nschloe** [trilinos/Trilinos#728]
The method `~ActiveRCPNodesSetup` implictly throws an exception via `TEUCHOS_TEST_FOR_EXCEPT(0==rcp_node_list());`. This is probably a bad idea, see, e.g., [here](http://stackoverflow.com/a/130123/353337).

**Comment by bartlettroscoe** [comment]
Agreed.  We need a macro to replace TEUCHOS_TEST_FOR_EXCEPT() to be called from destructors.
