### ISSUE TITLE
Question about Trilinos: pkgconfig file

### ISSUE THREAD

**Issue by hpcnpatel** [trilinos/Trilinos#7281]
##Question##

I was wondering if pkg-config files are generated with the installation of Trilinos/all packages? To provide applications (Trillions + some other) to the user, one of the difficulties is, integrating them. Pkg-config collects metadata about the installed libraries on a system and easily provides it to the user. Any comment?

**Comment by jhux2** [comment]
@bartlettroscoe @trilinos/framework

**Comment by bartlettroscoe** [comment]
@hpcnpatel, as far as I know, Trilinos only supports `<Package>Config.cmake` (one for each enabled Trilinos package) and a `TrilinosConfig.cmake` files for downstream CMake customers and `Makefile.export.<Package>` (one for each enabled Trilinos package) and `Makefile.export.Triinos` files for downstream Makefile customers.  See:

* https://tribits.org/doc/TribitsBuildReference.html#generating-export-files

There is no support for generating `pkg-config` files.

NOTE: The Trilinos-specific version of that file has not been online for some time (see #6601).

I don't think CMake has direct support for generating `pkg-config` files so I don't think this would ever be supported.  (In fact, the next version of Trilinos may only support  `<Package>Config.cmake` files for CMake customers.)
