### ISSUE TITLE
Framework: PR Default Target Branch is master

### ISSUE THREAD

**Issue by csiefer2** [trilinos/Trilinos#7289]
Can we change that to develop or is this case of "github doesn't allow us to do the obvious thing"

I almost never generate PRs by hand, but when I do, I make mistakes :)

**Comment by csiefer2** [comment]
@prwolfe is default branch what you get when someone clones the repo?

**Comment by prwolfe** [comment]
I'm not sure - the help says it's the brach used for pull requests and pushes. We have pushes restricted anyway for both branches so it won't affect that. I will try it on my fork.

**Comment by prwolfe** [comment]
@csiefer2 - Changing the default branch also changed what was checked out when cloning. I now get develop when I clone my fork.

**Comment by csiefer2** [comment]
@prwolfe IIRC, I believe this is why Framework decided master should be the default branch --- so that's what users get by default.

I suspect the fact that PRs and checkouts are tied to the same branch is another poor design decision by our friends at Github.

**Comment by jwillenbring** [comment]
> @prwolfe IIRC, I believe this is why Framework decided master should be the default branch --- so that's what users get by default.

Yes, leaving the default branch as master was very intentional.

**Comment by prwolfe** [comment]
Ok - will do!

Paul
