### ISSUE TITLE
Nalu diffs due to Muelu Phase2a

### ISSUE THREAD

**Issue by spdomin** [trilinos/Trilinos#7295]
## Bug Report
@trilinos/Muelu

### Description
Bisect performed in Nalu and Nalu-wind (@alanw0):

Good: 
NaluCFD/Nalu SHA1: 84b7cc7502c1ffc639b8fd498b28a43780d0ada7
Trilinos/develop SHA1: 8d0204884ee7a52ffcad920ce4a4d8000a768d18

Bad:
NaluCFD/Nalu SHA1: 84b7cc7502c1ffc639b8fd498b28a43780d0ada7
Trilinos/develop SHA1: ac87b0893ca618317649f7302acc435945af50f5

Note, no changes in Nalu-proper.

Bisect reported the following:

[spdomin@ceerws2214 Trilinos]$ git bisect bad
4d37b7e41c8943cda2738c62080c2f95ecb7152f is the first bad commit
commit 4d37b7e41c8943cda2738c62080c2f95ecb7152f
Author: Christian Glusa <caglusa@sandia.gov>
Date:   Fri Apr 24 11:50:37 2020 -0600

    MueLu Phase2a:  Include root node in aggregate

:040000 040000 454f35b3f040019e48d6dea9f60f592787bbaae2 131dce5374624043e5594c17ba821829dbf4d9ea M	packages

@jhux2 or @glusa please advise on how to proceed. Max diffs are not huge, however, appreciable: max diff:  .00000017845541625999858208195814

The following tests FAILED:
	  1 - actuatorLine (Failed)
	  6 - dgNonConformal3dFluids (Failed)
	  7 - dgNonConformal3dFluidsHexTet (Failed)
	  8 - dgNonConformal3dFluidsP1P2 (Failed)
	 10 - dgNonConformalEdgeCylinder (Failed)
	 11 - dgNonConformalElemCylinder (Failed)
	 12 - dgNonConformalFluids (Failed)
	 17 - edgeHybridFluids (Failed)
	 22 - elemHybridFluidsShift (Failed)
	 27 - heatedBackStep (Failed)
	 28 - 1x2x10Tet10 (Failed)
	 29 - ductTet10 (Failed)
	 32 - heliumPlume (Failed)
	 33 - hoHelium (Failed)
	 37 - milestoneRun (Failed)
	 38 - milestoneRunConsolidated (Failed)
	 39 - mixedTetPipe (Failed)
	 44 - nonIsoElemOpenJet (Failed)
	 45 - nonIsoElemOpenJetConsolidated (Failed)
	 47 - nonIsoNonUniformElemOpenJet (Failed)
	 48 - nonUniformElemOpenJet (Failed)
	 60 - variableDensNonIso (Failed)
	 68 - oversetHybrid (Failed)
	 69 - uqSlidingMeshDG (Failed)
	 70 - waleElemXflowMixFrac3.5m (Failed)

**Comment by jhux2** [comment]
@spdomin The aggregation algorithm did indeed change.  It's difficult to say whether this is good/bad for Nalu or NaluWind.  It would be interesting to see details of MueLu's setup to see what changed.  @cgcgcg tested this with the E&M solver.

**Comment by cgcgcg** [comment]
@spdomin We included a parameter to switch off the new aggregation behavior. Could you try setting "aggregation: phase2a include root" = false in one of these tests? Also, how big is the max diff compared to the solver tolerance? Does it change the number of iterations?

**Comment by spdomin** [comment]
Might I propose that you re-interpret the latest default behavior as "phase2a include root = false"? After all, the low-Mach application space has been using the previous algorithm since we stood up Muelu in the ASC L2 milestone era (milestone.xml - FY12-FY14 and served at the parallel processing paper methodology). Until we know that the new settings are best, it would be great to avoid changing all of the Nalu and Fuego XML settings to revert back to default.

Does that sounds like a good path forward @jhux2? Otherwise, changing default behavior without a clear understanding of the end performance ramifications seems risky.

**Comment by jhux2** [comment]
@spdomin We'll discuss this at our team meeting today.

**Comment by spdomin** [comment]
I will test the back-up plan in the meantime.

**Comment by spdomin** [comment]
I added the following to all the Nalu xml tests:

<Parameter        name="aggregation: phase2a include root" type="bool"   value="false"/>

The cases still failed.

Let me know if I messed something up.

**Comment by cgcgcg** [comment]
@spdomin Hm, that's strange, it should just do exactly what it did before the change. @jhux2 will give me his nalu config, I'll give it a shot.

**Comment by spdomin** [comment]
Commit diff attached,

[NewXMLDiff.txt](https://github.com/trilinos/Trilinos/files/4576974/NewXMLDiff.txt)

Test voucher listed below:

```
The following tests FAILED:
	  1 - actuatorLine (Failed)
	  6 - dgNonConformal3dFluids (Failed)
	  7 - dgNonConformal3dFluidsHexTet (Failed)
	  8 - dgNonConformal3dFluidsP1P2 (Failed)
	 10 - dgNonConformalEdgeCylinder (Failed)
	 11 - dgNonConformalElemCylinder (Failed)
	 12 - dgNonConformalFluids (Failed)
	 17 - edgeHybridFluids (Failed)
	 22 - elemHybridFluidsShift (Failed)
	 27 - heatedBackStep (Failed)
	 28 - 1x2x10Tet10 (Failed)
	 29 - ductTet10 (Failed)
	 32 - heliumPlume (Failed)
	 33 - hoHelium (Failed)
	 37 - milestoneRun (Failed)
	 38 - milestoneRunConsolidated (Failed)
	 39 - mixedTetPipe (Failed)
	 44 - nonIsoElemOpenJet (Failed)
	 45 - nonIsoElemOpenJetConsolidated (Failed)
	 47 - nonIsoNonUniformElemOpenJet (Failed)
	 48 - nonUniformElemOpenJet (Failed)
	 60 - variableDensNonIso (Failed)
	 68 - oversetHybrid (Failed)
	 69 - uqSlidingMeshDG (Failed)
	 70 - waleElemXflowMixFrac3.5m (Failed)

```

**Comment by cgcgcg** [comment]
@spdomin Fix is in https://github.com/trilinos/Trilinos/pull/7307. With that and your patch, everything is passing.

**Comment by cgcgcg** [comment]
@jhux2 For later reference:
Running 1x2x10Tet10 without inclusion of the root:
```
Algo "Phase 2a (secondary)"
BuildAggregates (Phase 2a (secondary))
  aggregated : 4044 (phase), 12545/18495 [67.83%] (total)
  remaining  : 5950
  aggregates : 244 (phase), 645 (total)
Algo "Phase 2b (expansion)"
BuildAggregates (Phase 2b (expansion))
  aggregated : 5950 (phase), 18495/18495 [100.00%] (total)
  remaining  : 0
  aggregates : 0 (phase), 645 (total)
```
With inclusion of the root
```
Algo "Phase 2a (secondary)"
BuildAggregates (Phase 2a (secondary))
  aggregated : 4288 (phase), 12789/18495 [69.15%] (total)
  remaining  : 5706
  aggregates : 244 (phase), 645 (total)
Algo "Phase 2b (expansion)"
BuildAggregates (Phase 2b (expansion))
  aggregated : 5706 (phase), 18495/18495 [100.00%] (total)
  remaining  : 0
  aggregates : 0 (phase), 645 (total)
```
Since the residual history is slightly different (but iteration counts are identical) I'd say that some root nodes did simply not get added to their aggregate before the change.

**Comment by spdomin** [comment]
Thanks.

Okay, so the path forward is change underlying behavior of the former default value? Moreover, now our XML files all need to change?

For my 2 billion DNS running on 2000-4000 nodes, what would you suggest that I use?

**Comment by cgcgcg** [comment]
It's up to Nalu: either add a single parameter to your input decks and run exactly the same algorithm as before. Or don't and run a fixed version that avoids a potential issue in MueLu's aggregation. We have yet to see a use case where the two versions perform significantly differently. From what I have seen in Nalu runs, the iteration counts are identical.

**Comment by spdomin** [comment]
I think that regression tests are small and are, in general, not a great indication of capability-class performance. To me, its simply a matter of deciding whether or not the change in default behavior is good or bad. Based on @jhux2 comment, this is not yet known. As such, I am simply questioning the team as to what is better.

However, perhaps the new change is better for my previous issues: https://github.com/trilinos/Trilinos/issues/5146



I understand that drivers for Muelu or probably on the side of EM. I will put it on my ASC list to check out the new scheme at scale. Based on

**Comment by spdomin** [comment]
I made this push:

https://github.com/NaluCFD/Nalu/pull/503

We can take this offline to SNL.
