### ISSUE TITLE
Muelu: Build errors in Maxwell3D for all 'ats1' hsw opt builds starting 05-05-2020

### ISSUE THREAD

**Issue by e10harvey** [trilinos/Trilinos#7311]
## Bug Report
@trilinos/muelu 

### Description
As shown in [this query](https://testing.sandia.gov/cdash/index.php?project=Trilinos&date=2020-05-05&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=63&value1=ats1-hsw&field2=buildname&compare2=63&value2=opt) there are build errors in the builds:

- Trilinos-atdm-ats1-hsw_intel-18.0.5_mpich-7.7.6_openmp_static_opt
- Trilinos-atdm-ats1-hsw_intel-19.0.4_mpich-7.7.6_openmp_static_opt

These builds have been failing with:
```bash
<snip>
Trilinos/packages/muelu/test/maxwell/Maxwell3D.cpp(136): error: namespace "Kokkos::Compat" has no member "KokkosSerialWrapperNode"
  struct EpetraSolvers_Wrapper<double,int,GlobalOrdinal,Kokkos::Compat::KokkosSerialWrapperNode> {
<snip>
```
CC: @bartlettroscoe 

### Current status on cdash
[ATDM Trilinos builds for current testing day](https://testing.sandia.gov/cdash/index.php?project=Trilinos&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=63&value1=ats1-hsw&field2=buildname&compare2=63&value2=opt)

### Steps to Reproduce
One should be able to reproduce this failure on the machine as described in
* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md
For the system 'mutrino', the instructions are at:
* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#ats-1

```bash
$ source $TRILINOS_DIR/cmake/std/atdm/load-env.sh \
      Trilinos-atdm-ats1-hsw_intel-18.0.5_mpich-7.7.6_openmp_static_opt

$ cmake -G Ninja \
  -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
  -DTrilinos_ENABLE_TESTS=ON \
  -DTrilinos_ENABLE_MueLu=ON \
  $TRILINOS_DIR

$ make NP=8  # This is a shared node!
```

**Comment by cgcgcg** [comment]
Hopefully, https://github.com/trilinos/Trilinos/pull/7313 takes care of this.

**Comment by jhux2** [comment]
@e10harvey Can you reenable this test so we can see if it's fixed?

**Comment by e10harvey** [comment]
> @e10harvey Can you reenable this test so we can see if it's fixed?

@jhux2: The test can be re-enabled with:
```bash
cmake -G Ninja \
-DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
-DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_MueLu=ON \
-DMueLu_Maxwell3D_EXE_DISABLE=OFF -DMueLu_Maxwell3D-Tpetra_MPI_4_DISABLE=OFF 
```

**Comment by cgcgcg** [comment]
@e10harvey PR #7313 has been merged. Can you please confirm that this has been fixed?

**Comment by jhux2** [comment]
> > @e10harvey Can you reenable this test so we can see if it's fixed?
> 
> @jhux2: The test can be re-enabled with:
> 
> ```shell
> cmake -G Ninja \
> -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
> -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_MueLu=ON \
> -DMueLu_Maxwell3D_EXE_DISABLE=OFF -DMueLu_Maxwell3D-Tpetra_MPI_4_DISABLE=OFF 
> ```

Sorry, I was unclear.  I was asking that you please reenable this in the ATDM dashboard.

**Comment by e10harvey** [comment]
@cgcgcg: Looks good. Thanks, Christian!

I verified that the 'ats1' build passes via:
```bash
$ git log --pretty=oneline -1
7a74218d58456d0818e2f13dd8202451c1b133ac (HEAD -> develop, github-upstream/develop) Merge pull request #7313 from cgcgcg/epetraMueLuMaxwell
$ git status
On branch develop
Untracked files:
  (use "git add <file>..." to include in what will be committed)
$ cmake -G Ninja -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_MueLu=ON -DMueLu_Maxwell3D_EXE_DISABLE=OFF -DMueLu_Maxwell3D-Tpetra_MPI_4_DISABLE=OFF ../Trilinos &> configure.out &
$ ninja -j16 &> make.out &
```

make.out shows now build errors.

Addressed via #7313.

**Comment by e10harvey** [comment]
> Sorry, I was unclear. I was asking that you please reenable this in the ATDM dashboard.

@jhux2: No problem. I've opened https://github.com/trilinos/Trilinos/pull/7316 to address this.

**Comment by cgcgcg** [comment]
@e10harvey Great, thank you!

**Comment by bartlettroscoe** [comment]
I believe PRs #7313 and #7316 resolved this.  We can see the test `MueLu_Maxwell3D-Tpetra_MPI_4` is enabled in the new 'ats1' builds as shown [here](https://testing-dev.sandia.gov/cdash/build/5437053/configure) which shows:

```
-- MueLu_Maxwell3D-Tpetra_MPI_4: Added test (BASIC, NUM_MPI_PROCS=4, PROCESSORS=4)!
```

However, because we are not running tests for 'ats1' currently, we can only assume the test executable is being built correct.

Closing as complete.

Thanks for fixing so fast @cgcgcg!
