### ISSUE TITLE
Amesos:  linking problem

### ISSUE THREAD

**Issue by feof81** [trilinos/Trilinos#7327]
Dear Trilinos developers, I haveloped an application (https://github.com/feof81/morganaPublic) based on trilinos and I'm currently updating the underlying version from 12.10.1 to the 12.17 one.
I have used the configure script listed below which is very similar to the one used for the 12.10.1.
The 12.17 is built in a correct manner but, I'm experiencing some problems during the linking phase:

/home/avilla/Documenti/trilinos-12.17-release/lib/libifpack.a(Ifpack_AMDReordering.cpp.o): nella funzione "Ifpack_AMDReordering::Compute(Ifpack_Graph const&)":
Ifpack_AMDReordering.cpp:(.text+0xf10): riferimento non definito a "trilinos_amd_order"
/home/avilla/Documenti/trilinos-12.17-release/lib/libamesos.a(Amesos_Klu.cpp.o): nella funzione "Amesos_Klu::PerformSymbolicFactorization()":
Amesos_Klu.cpp:(.text+0x3e25): riferimento non definito a "trilinos_klu_defaults"
Amesos_Klu.cpp:(.text+0x3e6e): riferimento non definito a "trilinos_klu_free_symbolic"
Amesos_Klu.cpp:(.text+0x3e8c): riferimento non definito a "trilinos_klu_analyze"
/home/avilla/Documenti/trilinos-12.17-release/lib/libamesos.a(Amesos_Klu.cpp.o): nella funzione "Amesos_Klu::PerformNumericFactorization()":
Amesos_Klu.cpp:(.text+0x42c4): riferimento non definito a "trilinos_klu_free_numeric"
Amesos_Klu.cpp:(.text+0x42ce): riferimento non definito a "trilinos_klu_factor"
Amesos_Klu.cpp:(.text+0x4617): riferimento non definito a "trilinos_klu_refactor"
Amesos_Klu.cpp:(.text+0x474b): riferimento non definito a "trilinos_klu_rcond"
/home/avilla/Documenti/trilinos-12.17-release/lib/libamesos.a(Amesos_Klu.cpp.o): nella funzione "Amesos_Klu::Solve()":
Amesos_Klu.cpp:(.text+0x54ad): riferimento non definito a "trilinos_klu_solve"
Amesos_Klu.cpp:(.text+0x55b9): riferimento non definito a "trilinos_klu_tsolve"
collect2: error: ld returned 1 exit status
Makefile:355: recipe for target 'all' failed
make[1]: *** [all] Error 1
make[1]: uscita dalla directory "/home/avilla/Documenti/morganaTemp/src"
Makefile:3: recipe for target 'all' failed
make: *** [all] Error 2

(riferimento non definito -> undefined reference, nella funzione -> in function)
It seeems that klu is not built or moved to another library. I guess that klu should be embedded in amesos and, apparently, there is no way to prevent its building (it has no dependancies). I also attach the list of packages I'm passing to the linker when building my application. Am I missing something? This list was working correctly with the 12.10.1 version.

Any suggestion would be useful.
Thank you very much.
Best regards.

Andrea Villa.

cmake \
-D CMAKE_BUILD_TYPE:STRING=RELEASE \
-D CMAKE_CXX_FLAGS:STRING="-DBOOST_SP_DISABLE_THREADS" \
-D CMAKE_INSTALL_PREFIX:PATH=/home/avilla/Documenti/trilinos-12.17-release \
-D MEMORYCHECK_COMMAND:FILEPATH=/usr/bin \
-D DART_TESTING_TIMEOUT:STRING=600 \
-D TPL_ENABLE_Boost=OFF \
-D TPL_ENABLE_BoostLib=OFF \
-D TPL_ENABLE_MPI:BOOL=ON \
-D TPL_ENABLE_HDF5:BOOL=ON \
-D TPL_ENABLE_MUMPS:BOOL=ON \
-D TPL_ENABLE_METIS:BOOL=ON \
-D TPL_ENABLE_ParMETIS:BOOL=ON \
-D TPL_ENABLE_Netcdf:BOOL=OFF \
-D TPL_ENABLE_Matio=OFF \
-D BUILD_SHARED_LIBS:BOOL=OFF \
-D MUMPS_INCLUDE_DIRS:PATH=/home/avilla/Documenti/MUMPS_5.2.1/include \
-D MUMPS_LIBRARY_DIRS:PATH=/home/avilla/Documenti/MUMPS_5.2.1/lib \
-D HDF5_INCLUDE_DIRS:PATH=/home/avilla/Documenti/hdf5-1.10.6-release/include \
-D HDF5_LIBRARY_DIRS:PATH=/home/avilla/Documenti/hdf5-1.10.6-release/lib \
-D METIS_INCLUDE_DIRS:PATH=/home/avilla/Documenti/metis-4.0.3-release/include \
-D METIS_LIBRARY_DIRS:PATH=/home/avilla/Documenti/metis-4.0.3-release/lib \
-D ParMETIS_INCLUDE_DIRS:PATH=/home/avilla/Documenti/parmetis-4.0.3-release/include \
-D ParMETIS_LIBRARY_DIRS:PATH=/home/avilla/Documenti/parmetis-4.0.3-release/lib \
-D MPI_BASE_DIR:PATH=/home/avilla/Documenti/openmpi-4.0.2-release \
-D MPI_EXEC:FILEPATH="/home/avilla/Documenti/openmpi-4.0.2-release/bin/mpirun" \
-D Trilinos_ENABLE_ALL_PACKAGES:BOOL=ON \
-D Trilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=ON \
-D Trilinos_ENABLE_SEACAS:BOOL=OFF \
-D Trilinos_ENABLE_TESTS:BOOL=OFF \
-D Trilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON \
-D HAVE_PARMETIS_VERSION_4_0_3=ON

-lnoxepetra \
 -lnox \
 -lanasazi \
 -lanasaziepetra \
 -lbelos \
 -lbelosepetra \
 -lml \
 -lifpack \
 -lamesos2 \
 -lamesos \
 -laztecoo \
 -lzoltan \
 -lepetraext \
 -lepetra \
 -ltpetra \
 -ltpetraclassic \
 -ltpetraclassiclinalg \
 -ltpetraclassicnodeapi \
 -ltpetrainout \
 -ltpetraext \
 -lthyracore \
 -lthyraepetra \
 -lthyraepetraext \
 -lrtop \
 -lteuchosremainder \
 -lteuchosnumerics \
 -lteuchoskokkoscompat \
 -lteuchoscomm \
 -lteuchosparameterlist \
 -lteuchoscore \
 -lkokkosalgorithms \
 -lkokkoscontainers \
 -lkokkostsqr \
 -lkokkoscore \
 -ltriutils \
 -ldmumps \
 -lmumps_common \
 -lpord \
 -lhdf5 \
 -lparmetis \
 -lmetis \
 -lboost_thread \
 -lboost_mpi \
 -lboost_serialization \
 -lboost_system \
 -llapack \
 -lblas \
 -lscalapack \
 -lgfortran \
 -lmpi \
 -lmpi_mpifh \
 -lz \
 -ldl

**Comment by cgcgcg** [comment]
@trilinos/amesos

**Comment by srajama1** [comment]
Are you using the Trilnos Cmake install files ?

**Comment by feof81** [comment]
I have only used the makefile script above and then make and make install.
Unfortunately it seems that some kind of function inside the Ifpack package seeks a function in the amesos package and in particular a klu-related function.
The linker does not find it and this, as far as I know, may be due to either:
- the build is incomplete due to an error in my makefile script;
- I have forgotten a library when linking trilinos into my application. Unfortunately amesos seems to be built in only one library.
Thus I'm lost...

**Comment by srajama1** [comment]
Ideally, we recommend using our install files. If you manually do this using Make basically you have to maintain this file w/ Trilinos dependencies. I recommend not doing it. But if you really want to do it KLU is part of a special package in Trilinos under auxiliary software.
https://github.com/trilinos/Trilinos/tree/master/packages/common/auxiliarySoftware/SuiteSparse

You should be able to link to the libraries there.

**Comment by feof81** [comment]
Dear srajama, thank you very much. In fact, it is sufficient to include the -ltrilinosss library!!
There was not problem for the building phase, I only missed a library.

I have a last question: with "installation files" you mean the scripts in the sampleScripts folder?
I usually use part of them since I have to customize the script to the specific machine. In many case this is a cluster with intel compilers, mkl, etc...

**Comment by srajama1** [comment]
Glad it worked. What I mean is you should source  Makefile.export.Trilinos_install in your build directory and then use the variables there to link to Trilinos. I will close this for now as the main issue is resolved.
