### ISSUE TITLE
seacas:  ioss: function ex_open_par() not found

### ISSUE THREAD

**Issue by glhenni** [trilinos/Trilinos#7328]
## Bug Report
@trilinos/\<seacas\>

In our latest build against `Trilinos/develop` we're getting the following error during compilation:
```
/home/glhenni/Projects/Charon2/tcad-charon/Trilinos/packages/seacas/libraries/ioss/src/exodus/Ioex_ParallelDatabaseIO.C: In member function ‘virtual bool Ioex::ParallelDatabaseIO::open_input_file(bool, std::__cxx11::string*, int*, bool) const’:
/home/glhenni/Projects/Charon2/tcad-charon/Trilinos/packages/seacas/libraries/ioss/src/exodus/Ioex_ParallelDatabaseIO.C:384:23: error: ‘ex_open_par’ was not declared in this scope
     exodusFilePtr   = ex_open_par(filename.c_str(), EX_READ | mode, &cpu_word_size, &io_word_size,
                       ^~~~~~~~~~~
/home/glhenni/Projects/Charon2/tcad-charon/Trilinos/packages/seacas/libraries/ioss/src/exodus/Ioex_ParallelDatabaseIO.C:384:23: note: suggested alternative: ‘ex_open_int’
```
Did `ex_open_par()` actually get removed and someone missed this file or do we perhaps need to add a new `cmake` option to our build to reenable this function?

**Comment by rppawlo** [comment]
@gsjaardema

**Comment by ikalash** [comment]
We are seeing the same problem in Albany:  https://sems-cdash-son.sandia.gov/cdash/viewBuildError.php?buildid=1501 .

**Comment by glhenni** [comment]
The problem stems from the use of two different cmake variables. In `seacs/libraries/ioss/src/CMakeLists.txt` `PARALLEL_AWARE_EXODUS` is only turned on if `TPL_Netcdf_PARALLEL` is defined, but in `seacas/libraries/ioss/src/exodus/CMakeLists.txt` the parallel files are removed if `TPL_ENABLE_MPI` is not defined. So if you don't have `TPL_Netcdf_PARALLEL` defined but you do have `TPL_ENABLE_MPI` defined the aforementioned compile error happens. I think those two conditionals should use the same boolean, or at least booleans that are linked.

**Comment by glhenni** [comment]
This diff will alleviate the problem until it's fixed upstream
```
diff --git a/packages/seacas/libraries/ioss/src/exodus/CMakeLists.txt b/packages/seacas/libraries/ioss/src/exodus/CMakeLists.txt
index 08e2f6e307..43ab42cc7c 100644
--- a/packages/seacas/libraries/ioss/src/exodus/CMakeLists.txt
+++ b/packages/seacas/libraries/ioss/src/exodus/CMakeLists.txt
@@ -6,7 +6,7 @@ SET_AND_INC_DIRS(DIR ${CMAKE_CURRENT_SOURCE_DIR})
 APPEND_GLOB(HEADERS ${DIR}/*.h)
 APPEND_GLOB(SOURCES ${DIR}/*.C)
 
-IF (NOT TPL_ENABLE_MPI)
+IF (NOT TPL_Netcdf_PARALLEL)
   LIST(REMOVE_ITEM SOURCES ${DIR}/Ioex_ParallelDatabaseIO.C ${DIR}/Ioex_DecompositionData.C)
   LIST(REMOVE_ITEM HEADERS ${DIR}/Ioex_ParallelDatabaseIO.h ${DIR}/Ioex_DecompositionData.h)
 ENDIF()
```

**Comment by glhenni** [comment]
Below is a patch to fix this problem. It appears there are two booleans that assume that if MPI is enabled then so is parallel netcdf/exodus, which isn't the case in Charon. We use MPI, but we don't enable parallel netcdf/exodus. I'm guessing you could reproduce this problem yourselves in Sierra by building with parallel netcdf disabled.
```diff
diff --git a/packages/seacas/libraries/ioss/src/exodus/CMakeLists.txt b/packages/seacas/libraries/ioss/src/exodus/CMakeLists.txt
index 08e2f6e307..eb8977e61e 100644
--- a/packages/seacas/libraries/ioss/src/exodus/CMakeLists.txt
+++ b/packages/seacas/libraries/ioss/src/exodus/CMakeLists.txt
@@ -6,7 +6,7 @@ SET_AND_INC_DIRS(DIR ${CMAKE_CURRENT_SOURCE_DIR})
 APPEND_GLOB(HEADERS ${DIR}/*.h)
 APPEND_GLOB(SOURCES ${DIR}/*.C)
 
-IF (NOT TPL_ENABLE_MPI)
+IF (NOT PARALLEL_AWARE_EXODUS)
   LIST(REMOVE_ITEM SOURCES ${DIR}/Ioex_ParallelDatabaseIO.C ${DIR}/Ioex_DecompositionData.C)
   LIST(REMOVE_ITEM HEADERS ${DIR}/Ioex_ParallelDatabaseIO.h ${DIR}/Ioex_DecompositionData.h)
 ENDIF()
diff --git a/packages/seacas/libraries/ioss/src/exodus/Ioex_IOFactory.C b/packages/seacas/libraries/ioss/src/exodus/Ioex_IOFactory.C
index c66efc2886..3381405403 100644
--- a/packages/seacas/libraries/ioss/src/exodus/Ioex_IOFactory.C
+++ b/packages/seacas/libraries/ioss/src/exodus/Ioex_IOFactory.C
@@ -33,7 +33,7 @@
 #include <exodus/Ioex_IOFactory.h> // for Ioex IOFactory
 #include <exodus/Ioex_DatabaseIO.h> // for Ioex DatabaseIO
 
-#if defined(SEACAS_HAVE_MPI)
+#if defined(PARALLEL_AWARE_EXODUS)
 #include <exodus/Ioex_ParallelDatabaseIO.h> // for Ioex ParallelDatabaseIO
 #endif
 #include <tokenize.h>
@@ -86,7 +86,7 @@ namespace Ioex {
                                        MPI_Comm                     communicator,
                                        const Ioss::PropertyManager &properties) const
   {
-#if defined(SEACAS_HAVE_MPI)
+#if defined(PARALLEL_AWARE_EXODUS)
     // The "exodus" and "parallel_exodus" databases can both be accessed
     // from this factory.  The "parallel_exodus" is returned only if the following
     // are true:
```

**Comment by ikalash** [comment]
It seems the PR of this hasn't been merged in yet, as we are still seeing some failures in the Albany nightlies.  Any updates on the status of the PR?

**Comment by gsjaardema** [comment]
Sorry, I just saw this.  I need to look at this further. The intent was to try to remove CMake trickery and we were also assuming that all Parallel builds would also be using Parallel NetCDF which obviously is not the case.

The issue we were having is that applications that *did* have a parallel NetCDF were not getting the trigger that NetCDF *was* parallel.

I will see if I can figure out some method that works for both but also eliminates the need for manually setting CMake variables.  The find-netcdf package correctly sets what is needed, but it is bypassed if the path the the library is explicitly specified...

**Comment by gsjaardema** [comment]
This should be fixed with #7368

**Comment by glhenni** [comment]
@gsjaardema that seems to have gotten rid of the `ex_open_par()` issue, but now I'm getting a different undefined reference:
```
../exodus/libIoex.so.2.0.0: undefined reference to `Ioex::ParallelDatabaseIO::ParallelDatabaseIO(Ioss::Region*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Ioss::DatabaseUsage, ompi_communicator_t*, Ioss::PropertyManager const&)'
collect2: error: ld returned 1 exit status
```

**Comment by gsjaardema** [comment]
Are you using a parallel NetCDF, but telling CMake that is isn't parallel?

**Comment by glhenni** [comment]
On my test platform, the one I'm basing this on, I'm using a system installed netcdf library so I can't be entirely sure  (stock Ubuntu 18.04). It doesn't look to me like there's any parallel capabilities enabled. The library it's pointing to is `/usr/lib/x86_64-linux-gnu/libnetcdf.so.13` and the file `/usr/lib/x86_64-linux-gnu/libnetcdf.settings` has
```
# Features
--------
NetCDF-2 API:		yes
HDF4 Support:		no
NetCDF-4 API:		yes
NC-4 Parallel Support:	no
PNetCDF Support:	no
DAP2 Support:		yes
DAP4 Support:		yes
Diskless Support:	yes
MMap Support:		yes
JNA Support:		no
CDF5 Support:		no
ERANGE fill Support:	no
```

**Comment by gsjaardema** [comment]
Is there a `<build_dir>/packages/seacas/libraries/ioss/src/SEACASIoss_config.h` and if so what is the setting for `PARALLEL_AWARE_EXODUS` 

Also `<build_dir>/packages/seacas/libraries/exodus/exodus_config.h`

And, I guess for completness, is `TPL_NetCDF_PARALLEL` in the `<build_dir>/CMakeCache.txt`

**Comment by glhenni** [comment]
CMakeCache.txt:
```
//True if netcdf compiled with parallel enabled
TPL_Netcdf_PARALLEL:BOOL=False
```
SEACASIoss_config.h:
```
#define SEACAS_HAVE_MPI

/* #undef IOSS_THREADSAFE */

/* Define to indicate that the SEACAS project is being built with the KOKKOS package enabled*/
#define SEACAS_HAVE_KOKKOS

/* Define to indicate that the SEACAS project is being built with the Data Warehouse support enabled*/
/* #undef SEACAS_HAVE_DATAWAREHOUSE */

/* #undef SEACAS_HAVE_DATAWARP */

#define SEACAS_HAVE_EXODUS

/* #undef SEACAS_HAVE_CGNS */

/* #undef SEACAS_HAVE_PAMGEN */

/* #undef PARALLEL_AWARE_EXODUS */

/* #undef HAVE_SEACASIOSS_ADIOS2 */
```
exodus_config.h:
```
/* #undef EXODUS_THREADSAFE */

/* #undef PARALLEL_AWARE_EXODUS */

#ifndef SEACAS_DEPRECATED
#  if (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 1))
#    define SEACAS_DEPRECATED  __attribute__((__deprecated__))
#  else
#    define SEACAS_DEPRECATED
#  endif
#endif

#ifndef SEACAS_DEPRECATED_MSG
#  if (__GNUC__ > 4 || (__GNUC__ == 4 && __GNUC_MINOR__ >= 5))
#    define SEACAS_DEPRECATED_MSG(MSG)  __attribute__((__deprecated__ (#MSG) ))
#  elif (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 1))
#    define SEACAS_DEPRECATED_MSG(MSG)  __attribute__((__deprecated__))
#  else
#    define SEACAS_DEPRECATED_MSG(MSG)
#  endif
#endif
```

**Comment by gsjaardema** [comment]
OK, not sure how you are getting a reference to `Ioex::ParallelDatabaseIO` then.  Is this from a clean build or is there a possibility it is accessing old include files or old libraries/object files some way?

**Comment by gsjaardema** [comment]
And this is happening if you manually apply #7380 since it is stuck waiting for tests to run...

**Comment by glhenni** [comment]
Damn it! That will teach me to scroll to the bottom of PRs. I just assumed that after 4+ days it had merged in to `develop`. 

I applied the PR manually and charon builds fine.

Sorry for the confusion and wasted time.

**Comment by gsjaardema** [comment]
Not a problem. Glad it was solved.

**Comment by gsjaardema** [comment]
This should have been closed 15 months ago...
