### ISSUE TITLE
Belos: Too many all-reduces per CG iteration

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#733]
@trilinos/belos Talk at TUG 2016 today claims 4 all-reduces per CG iteration, compared to PETSc's single all-reduce.

**Comment by mhoemmen** [comment]
My work-around will be to roll an efficient Tpetra-native solver, then wrap it in a Belos::SolverManager interface.  I'll start with #734, showing an example of this wrapping process.

**Comment by mhoemmen** [comment]
Cause in Belos is known: the status test is doing an extra norm, because the solver's getNativeResiduals method returns nonnull.  I'm motivated to go the #734 route (wrap a native solver) for other reasons, but I think we can fix this in Belos.

**Comment by mhoemmen** [comment]
This is a duplicate of #742.  I'm pasting in the text from there:

@trilinos/belos @hkthorn @amklinv @rstumin @jhux2

Belos' implementation of CG, PseudoBlockCGSolMgr, does at least 3 all-reduces per iteration. The algorithm itself, implemented in Belos::PseudoBlockCGIter::iterate, does 2 all-reduces per iteration. However, the status check (StatusTestGenResNorm) does an extra all-reduce (MvNorm), even if it is set to Implicit mode (see lines 497-506 of BelosStatusTestGenResNorm.hpp). This is because PseudoBlockCGIter::getNativeResiduals returns nonnull (line 190 of BelosPseudoBlockCGIter.hpp). This need not happen, because CG computes an implicit estimate of the residual norm, just like GMRES. (Belos::PseudoBlockGmresIter::getNativeResiduals correctly returns null; see line 521 of BelosPseudoBlockGmresIter.hpp.)

I'm mentioning @rstumin and @jhux2 because they mentioned tonight having noticed this performance issue before.

**Comment by mhoemmen** [comment]
I'm calling this a "task" because it is well defined (change PseudoBlockCGIter::getNativeResiduals to return null and put the implicit residual norms in the output argument).

**Comment by jhux2** [comment]
Mark Hoemmen wrote on 10/31/2016 03:47 PM:
>
> @hkthorn <https://github.com/hkthorn> reports that Aztec(OO) actually 
> /does/ compute this explicit residual norm every iteration. Her 
> motivation in implementing it this way in Belos was to imitate 
> AztecOO's behavior.
>
>
It's the fault of the AztecOO developers, whoever they may be :).

**Comment by mhoemmen** [comment]
> It's the fault of the AztecOO developers, whoever they may be :).

;-) It's not about "fault" -- Heidi pointed out that they probably had users who didn't understand the whole "implicit residual may differ from explicit residual" thing.  Making the solver actually compute the norm at every iteration made those people go away.  (What Belos does isn't _quite_ that; it computes the explicit norm of the implicit residual vector.  Not sure what AztecOO actually does.)

**Comment by maherou** [comment]
It's bee a long time since I have been buried in AztecOO GMRES, but I am almost sure it does not compute the explicit residual at every iteration, at least by default.  It uses the approximation from the factorization during the Arnoldi process.  I think it is possible to make GMRES compute the residual at each iteration, using the status test capabilities.

**Comment by mhoemmen** [comment]
> It's been a long time since I have been buried in AztecOO GMRES, but I am almost sure it does not compute the explicit residual at every iteration, at least by default. 

This is about Aztec(OO)'s CG implementation.  Heidi mentioned that she added the explicit (rather, "sorta kinda explicit"; see above) residual check in order to imitate Aztec(OO)'s behavior.

**Comment by maherou** [comment]
Thanks for the clarification.

**Comment by hkthorn** [comment]
AztecOO's GMRES most certainly does not compute the explicit residual at every iteration, it uses the classical norm bound.  However, AztecOO's CG computes the norm of the recursive residual and that's what Belos does too.

**Comment by mhoemmen** [comment]
It could make sense to work on a Tpetra-native version of this for #748 comparison.

**Comment by rstumin** [comment]
@jhux2 @hkthorn So at the end of the day ... Belos still does these extra all reduces? We're using the Belos CG solver in an E3SM project ... and this is an issue for us. I might be "happy" to fix this, but would like to make sure I understand what I'm doing before mucking things up.

**Comment by cgcgcg** [comment]
@rstumin There is a single reduce option that (if I remember correctly) uses 2 allreduces per iteration (1 for basis updates, 1 for convergence test).

**Comment by rstumin** [comment]
@cgcgcg @hkthorn @jhux2 Ok. I now see a "Use Single Reduction". The comments in the code make me think ... that it only does one reduction. I'm looking at code now, but perhaps Heidi can fill me in on some insights.

**Comment by hkthorn** [comment]
The single-reduction CG iteration in BelosCGSingleRedIter.hpp implements a method found in:

A. T. Chronopoulos and C. W. Gear. 1989. s-Step iterative methods for symmetric
linear systems. J. Comput. Appl. Math. 25(2) (1989).

It is a single reduction iteration, but the convergence check may introduce a second reduction.  There are a couple options for folding the residual norm computation into the single-reduction in the iteration.  @cgcgcg added a "Fold Convergence Detection Into Allreduce" option that is recognized by this iteration.  I don't have experience with that, but maybe he can speak to its applicability.

**Comment by cgcgcg** [comment]
Oh, totally forgot about that! It looks like it actually gets rid of the allreduce for the convergence detection by lumping it into the other allreduce. There might be a penalty of having to take one additional iteration.

**Comment by rstumin** [comment]
@cgcgcg @hkthorn So ... then it looks like this issue really can be closed, because all of the main options that we can think of are actually implemented.

**Comment by hkthorn** [comment]
Maybe.  I would like to get your help with finding where in AztecOO (or Aztec) that the implicit residual norm is calculated for the CG solver.  I implemented the Belos CG solvers trying to follow those implementations and maybe I missed something that can be added back into the basic Belos CG iterations.  Make sense @rstumin?
