### ISSUE TITLE
Seacas: build error in Albany nightlies

### ISSUE THREAD

**Issue by ikalash** [trilinos/Trilinos#7335]
We get the following build error in several of the Albany nightlies due to seacas:

```
/.../repos/Trilinos/packages/seacas/applications/conjoin/Conjoin.C: In function 'void {anonymous}::map_sideset_vars(Excn::SideSet<INT>&, size_t, std::vector<double>&, std::vector<double>&)':
Trilinos/packages/seacas/applications/conjoin/Conjoin.C:2869:33: error: 'glob_entity_count' was not declared in this scope
       SMART_ASSERT(global_loc < glob_entity_count);
```
Can someone please have a look and resolve the problem?

@trilinos/seacas

**Comment by gsjaardema** [comment]
This is fixed by #7333.  It should have gone in yesterday, but for some reason the auto-build never started, so it is just sitting there.  I think @bartlettroscoe manually pushed it into the ATDM builds?

**Comment by bartlettroscoe** [comment]
> I think @bartlettroscoe manually pushed it into the ATDM builds?

@gsjaardema, yes.  There is a backdoor to get things into ATDM Trilinos testing just for cases like this.

**Comment by ikalash** [comment]
Oh ok.  I imagine we'll see this fix in Trilinos develop shortly?  I will check again tomorrow to see if the issue has gone away.

**Comment by bartlettroscoe** [comment]
FYI:  I heard that all PR testing is currently down and therefore no PRs will be merged until it comes back.

**Comment by ikalash** [comment]
@bartlettroscoe : I see, thanks for the heads up.  Has #7328 been resolved too in a PR, just not merged into develop yet?  We're still seeing that issue in some of our nightlies.

**Comment by bartlettroscoe** [comment]
>Has #7328 been resolved too in a PR, just not merged into develop yet?

@ikalash, as of right now, no one has approved PR #7328 yet.

Albany really should have its own fork of Trilinos so you can merge in specific changes (and you can auto-update from Trilinos 'develop' or 'master' every day if you want).
