### ISSUE TITLE
Belos: Add example wrapping native Tpetra solver in Belos::SolverManager interface

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#734]
@trilinos/belos @trilinos/tpetra 
This is the first step in fixing #733.

**Comment by mhoemmen** [comment]
I've got this ready on a local branch, as a Belos Tpetra example.  Just need to test and push.

**Comment by mhoemmen** [comment]
Just pushed the new example.

**Comment by kvmkrao** [comment]
I ran this example -diagonal CG solver (packages/belos/tpetra/example/) on Hansen. It was observed that  the solver time on GPU nodes is less compared to that on Haswell nodes. 

Haswell nodes | Solver time in sec
-- | --
1 (32 MPI) | 17.18
2 (64 MPI ) | 13.06
3 (96 MPI) | 9.436

The solver time on K80 GPUs is 

GPU nodes | Times in sec
-- | --
1 (4MPI, 1 GPU) | 4.569
2 (8 MPI, 2 GPUs) | 2.338
3 (16 MPI, 3 GPUs) | 1.659

I was trying to use this example to solve a linear system that contains maximum three non-zero elements in a row as it is useful to integrate with a legacy code. 

```
    dev_view_type diag_d ("diag", lclNumRows, 3);
    host_view_type diag_h = Kokkos::create_mirror_view (diag_d);

      for (LO lclRow = 0; lclRow < lclNumRows; ++lclRow) {
        diag_h(lclRow,0) = - ONE/(ONE + ONE + ONE) ;
        diag_h(lclRow,1) = ONE ; //diag_h(lclRow) * scalingFactor;
        diag_h(lclRow,2) = - ONE/(ONE + ONE + ONE) ;
      }
```
I could not compile this code without errors. 
Is it appropriate to use this code for solving a tri-diagonal linear system?.  If yes, could please suggest me the changes.   
 
**Compilation errors:** 
> 50%] Building CXX object CMakeFiles/example.dir/wrapTpetraSolver.cpp.o
> /ascldap/users/vkkotte/Trilinos/run/WrapTpetraSolver/modified/wrapTpetraSolver.cpp(713): error: expected a declaration
> 
> /ascldap/users/vkkotte/Trilinos/install/include/Kokkos_View.hpp(1105): error: static assertion failed with "Incompatible View copy assignment"
>           detected during:
>             instantiation of "Kokkos::View<DataType, Properties...> &Kokkos::View<DataType, Properties...>::operator=(const Kokkos::View<RT, RP...> &) [with DataType=const double *, Properties=<Kokkos::Device<Kokkos::CudaUVMSpace::execution_space, Kokkos::CudaUVMSpace::memory_space>>, RT=double **, RP=<Kokkos::Device<Kokkos::CudaUVMSpace::execution_space, Kokkos::CudaUVMSpace::memory_space>>]" 
> /ascldap/users/vkkotte/Trilinos/run/WrapTpetraSolver/modified/wrapTpetraSolver.cpp(710): here
>             instantiation of "TestDiagonalOperator<SC, LO, GO, NT>::TestDiagonalOperator(const Teuchos::RCP<const TestDiagonalOperator<SC, LO, GO, NT>::map_type> &, TestDiagonalOperator<SC, LO, GO, NT>::mag_type) [with SC=Tpetra::Details::DefaultTypes::scalar_type, LO=Tpetra::Details::DefaultTypes::local_ordinal_type, GO=Tpetra::Details::DefaultTypes::global_ordinal_type, NT=Tpetra::Details::DefaultTypes::node_type]" 
> /ascldap/users/vkkotte/Trilinos/run/WrapTpetraSolver/modified/wrapTpetraSolver.cpp(804): here
> 
> /ascldap/users/vkkotte/Trilinos/install/include/impl/Kokkos_ViewMapping.hpp(2915): error: static assertion failed with "View assignment must have compatible dimensions"
>           detected during:
>             instantiation of "void Kokkos::Experimental::Impl::ViewMapping<DstTraits, SrcTraits, std::enable_if<<expression>, void>::type>::assign(Kokkos::Experimental::Impl::ViewMapping<DstTraits, SrcTraits, std::enable_if<<expression>, void>::type>::DstType &, const Kokkos::Experimental::Impl::ViewMapping<DstTraits, SrcTraits, std::enable_if<<expression>, void>::type>::SrcType &, const Kokkos::Experimental::Impl::ViewMapping<DstTraits, SrcTraits, std::enable_if<<expression>, void>::type>::TrackType &) [with DstTraits=Kokkos::ViewTraits<const double *, Kokkos::Device<Kokkos::CudaUVMSpace::execution_space, Kokkos::CudaUVMSpace::memory_space>>, SrcTraits=Kokkos::ViewTraits<double **, Kokkos::Device<Kokkos::CudaUVMSpace::execution_space, Kokkos::CudaUVMSpace::memory_space>>]" 
> /ascldap/users/vkkotte/Trilinos/install/include/Kokkos_View.hpp(1106): here
>             instantiation of "Kokkos::View<DataType, Properties...> &Kokkos::View<DataType, Properties...>::operator=(const Kokkos::View<RT, RP...> &) [with DataType=const double *, Properties=<Kokkos::Device<Kokkos::CudaUVMSpace::execution_space, Kokkos::CudaUVMSpace::memory_space>>, RT=double **, RP=<Kokkos::Device<Kokkos::CudaUVMSpace::execution_space, Kokkos::CudaUVMSpace::memory_space>>]" 
> /ascldap/users/vkkotte/Trilinos/run/WrapTpetraSolver/modified/wrapTpetraSolver.cpp(710): here
>             instantiation of "TestDiagonalOperator<SC, LO, GO, NT>::TestDiagonalOperator(const Teuchos::RCP<const TestDiagonalOperator<SC, LO, GO, NT>::map_type> &, TestDiagonalOperator<SC, LO, GO, NT>::mag_type) [with SC=Tpetra::Details::DefaultTypes::scalar_type, LO=Tpetra::Details::DefaultTypes::local_ordinal_type, GO=Tpetra::Details::DefaultTypes::global_ordinal_type, NT=Tpetra::Details::DefaultTypes::node_type]" 
> /ascldap/users/vkkotte/Trilinos/run/WrapTpetraSolver/modified/wrapTpetraSolver.cpp(804): here
> 
> /ascldap/users/vkkotte/Trilinos/install/include/impl/Kokkos_ViewMapping.hpp(1015): error: static assertion failed with "ViewOffset assignment requires equal rank"
>           detected during:
>             instantiation of "Kokkos::Experimental::Impl::ViewOffset<Dimension, Kokkos::LayoutLeft, std::enable_if<<expression>, void>::type>::ViewOffset(const Kokkos::Experimental::Impl::ViewOffset<DimRHS, Kokkos::LayoutLeft, void> &) [with Dimension=Kokkos::Experimental::Impl::ViewDimension<0UL>, DimRHS=Kokkos::Experimental::Impl::ViewDimension<0UL, 0UL>]" 
> (2946): here
>             instantiation of "void Kokkos::Experimental::Impl::ViewMapping<DstTraits, SrcTraits, std::enable_if<<expression>, void>::type>::assign(Kokkos::Experimental::Impl::ViewMapping<DstTraits, SrcTraits, std::enable_if<<expression>, void>::type>::DstType &, const Kokkos::Experimental::Impl::ViewMapping<DstTraits, SrcTraits, std::enable_if<<expression>, void>::type>::SrcType &, const Kokkos::Experimental::Impl::ViewMapping<DstTraits, SrcTraits, std::enable_if<<expression>, void>::type>::TrackType &) [with DstTraits=Kokkos::ViewTraits<const double *, Kokkos::Device<Kokkos::CudaUVMSpace::execution_space, Kokkos::CudaUVMSpace::memory_space>>, SrcTraits=Kokkos::ViewTraits<double **, Kokkos::Device<Kokkos::CudaUVMSpace::execution_space, Kokkos::CudaUVMSpace::memory_space>>]" 
> /ascldap/users/vkkotte/Trilinos/install/include/Kokkos_View.hpp(1106): here
>             instantiation of "Kokkos::View<DataType, Properties...> &Kokkos::View<DataType, Properties...>::operator=(const Kokkos::View<RT, RP...> &) [with DataType=const double *, Properties=<Kokkos::Device<Kokkos::CudaUVMSpace::execution_space, Kokkos::CudaUVMSpace::memory_space>>, RT=double **, RP=<Kokkos::Device<Kokkos::CudaUVMSpace::execution_space, Kokkos::CudaUVMSpace::memory_space>>]" 
> /ascldap/users/vkkotte/Trilinos/run/WrapTpetraSolver/modified/wrapTpetraSolver.cpp(710): here
>             instantiation of "TestDiagonalOperator<SC, LO, GO, NT>::TestDiagonalOperator(const Teuchos::RCP<const TestDiagonalOperator<SC, LO, GO, NT>::map_type> &, TestDiagonalOperator<SC, LO, GO, NT>::mag_type) [with SC=Tpetra::Details::DefaultTypes::scalar_type, LO=Tpetra::Details::DefaultTypes::local_ordinal_type, GO=Tpetra::Details::DefaultTypes::global_ordinal_type, NT=Tpetra::Details::DefaultTypes::node_type]" 
> /ascldap/users/vkkotte/Trilinos/run/WrapTpetraSolver/modified/wrapTpetraSolver.cpp(804): here
> 
> /ascldap/users/vkkotte/Trilinos/run/WrapTpetraSolver/modified/wrapTpetraSolver.cpp(687): warning: variable "nonzero" was declared but never referenced
>           detected during instantiation of "TestDiagonalOperator<SC, LO, GO, NT>::TestDiagonalOperator(const Teuchos::RCP<const TestDiagonalOperator<SC, LO, GO, NT>::map_type> &, TestDiagonalOperator<SC, LO, GO, NT>::mag_type) [with SC=Tpetra::Details::DefaultTypes::scalar_type, LO=Tpetra::Details::DefaultTypes::local_ordinal_type, GO=Tpetra::Details::DefaultTypes::global_ordinal_type, NT=Tpetra::Details::DefaultTypes::node_type]" 
> (804): here
> 
> 4 errors detected in the compilation of "/tmp/tmpxft_0000a090_00000000-7_wrapTpetraSolver.cpp1.ii".
> make[2]: *** [CMakeFiles/example.dir/wrapTpetraSolver.cpp.o] Error 2
> make[1]: *** [CMakeFiles/example.dir/all] Error 2
> make: *** [all] Error 2

Thank you.

**Comment by ibaned** [comment]
@kvmkrao could you please open a new issue for this?

As for your question, my guess is that `host_view_type` may be ill-defined. I would just replace it with `auto` and let the compiler do the thinking (it likely has to do with the fact that `View` uses opposite layouts on the CPU and GPU by default...).

**Comment by kvmkrao** [comment]
@ibaned Thank you. Opened a new issue for this. 

I replaced host_view_type with auto and recompiled the code. And, it did not solve the problem. 
Sorry,  I forgot to post the code with HostMirror  statement in the previous post. 
```
 typedef Kokkos::View<mag_type**, device_type> dev_view_type;
    typedef typename dev_view_type::HostMirror host_view_type;
```

Sure, the default memory layouts are different on CPU and  GPU. Therefore, I explicitly specified them in the code.  
```
typename Kokkos::View<mag_type**, Kokkos::LayoutLeft, Kokkos::CudaSpace> diag_d("diag",   lclNumRows, nonzero);
 typename Kokkos::View<mag_type**, Kokkos::LayoutLeft, Kokkos::HostSpace> diag_h("diag_h", lclNumRows, nonzero);
```

These statements did not work and resulted the same errors. as last time. 
Thanks.

**Comment by mhoemmen** [comment]
Just for future reference, the new issue (build errors in test) is #1598.
