### ISSUE TITLE
Framework: Autotester isn't autotesting

### ISSUE THREAD

**Issue by csiefer2** [trilinos/Trilinos#7342]
Been waiting since Thursday night for this to get autotested...

https://github.com/trilinos/Trilinos/pull/7332

@trilinos/framework

**Comment by prwolfe** [comment]
I sent out a note about this earlier today. Until Sandia's gitlab instance comes back up nothing will happen.

**Comment by csiefer2** [comment]
Ah, so this is all due to gitlab being broken.  Good to know.
