### ISSUE TITLE
Add Nvidia warnings-as-errors build to Trilinos testing

### ISSUE THREAD

**Issue by jwillenbring** [trilinos/Trilinos#7346]
@trilinos/framework 

We received a request to clean up Nvidia warnings in Trilinos. @crtrott provided the following set of flags that Kokkos uses for nvcc warnings:

-Wall -Wunused-parameter -Wshadow -pedantic -Wsign-compare -Wtype-limits -Wuninitialized

**Comment by csiefer2** [comment]
Looking forward to all the red builds!

**Comment by wadeburgess** [comment]
Migrated to Trilinos Help Desk so closing this issue now.
