### ISSUE TITLE
Tpetra: CrsGraph creation

### ISSUE THREAD

**Issue by syaskovets** [trilinos/Trilinos#7350]
## Question
@trilinos/Tpetra
Hi there,

recently I was working through the wiki page on graph [partitioning](https://github.com/trilinos/Trilinos/wiki/Tpetra::CrsGraph-creation,-from-a-graph-perspective). Unfortunately, trying to reproduce the example on creating CrsGraph without specifying column Map 
`using crs_graph_type = Tpetra::CrsGraph<>;
RCP<crs_graph_type> G (new crs_graph_type (rowMap, numEntPerRow, Tpetra::StaticProfile));` 
I have encountered compile-time errors. The issue seems to be a missing constructor signature. And indeed taking a look at the [documentation](https://docs.trilinos.org/dev/packages/tpetra/doc/html/classTpetra_1_1CrsGraph.html) it seems Tpetra doesn't provide such an interface anymore, maybe deprecated. Could you please clarify this question, and maybe point out at a possible alternative. Thanks in advance!

**Comment by cgcgcg** [comment]
Could you try removing `Tpetra::StaticProfile`?

**Comment by syaskovets** [comment]
Thanks for the response! 
Yup, the result is the same. Namely, we have such a function call
`CrsGraph(Teuchos::RCP<const Tpetra::Map<...> > >&, Teuchos::ArrayRCP<...>&)` 
which doesn't match any of the constructor signatures available.

**Comment by cgcgcg** [comment]
Wait, have you tried using an `ArrayView` for `numEntPerRow`? Maybe try `numEntPerRow()` instead of `numEntPerRow`?

**Comment by syaskovets** [comment]
Indeed, it worked. Thanks a lot!

**Comment by kddevin** [comment]
I updated the wiki page with correct syntax.
