### ISSUE TITLE
zoltan2:  memory error when multijagged generates rectilinear partitions

### ISSUE THREAD

**Issue by kddevin** [trilinos/Trilinos#7351]
## Bug Report
@trilinos/zoltan2 @kuberry 

### Description
When generating rectilinear partitions, multijagged appears to have a memory error writing to local_cut_line_weight_to_put_left.

https://github.com/trilinos/Trilinos/blob/0c5b9ccf004d4efee9475d5aaef9139f7be2044d/packages/zoltan2/src/algorithms/partition/Zoltan2_AlgMultiJagged.hpp#L4721

A check of the extent for one test case shows the view has length zero, but i == num_cuts-1 == 1.

I am wondering if the bug is here, as the comment and the if-test differ:
https://github.com/trilinos/Trilinos/blob/0c5b9ccf004d4efee9475d5aaef9139f7be2044d/packages/zoltan2/src/algorithms/partition/Zoltan2_AlgMultiJagged.hpp#L2636

It appears thread_cut_line_weight_to_put_left should always be allocated, not only when not generating rectilinear parts. I don't understand the code enough, though.  Do the arrays *_rectilinear_cut_weight get used only when generating rectilinear parts?  Or only when NOT generating rectilinear parts?

@MicheldeMessieres  and I will discuss.

### Steps to Reproduce

On cee-lan:  module load sierra-devel/gcc-8.3.0-openmpi-1.10.2

```
cmake \
\
-D Trilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON \
-D Tpetra_INST_INT_LONG_LONG:BOOL=ON \
-D Tpetra_INST_INT_INT:BOOL=OFF \
-D Tpetra_INST_DOUBLE:BOOL=ON \
-D Tpetra_INST_FLOAT:BOOL=OFF \
-D Tpetra_INST_COMPLEX_FLOAT:BOOL=OFF \
-D Tpetra_INST_COMPLEX_DOUBLE:BOOL=OFF \
-D Tpetra_INST_INT_LONG:BOOL=OFF \
-D Tpetra_INST_INT_UNSIGNED:BOOL=OFF \
-D Tpetra_INST_SERIAL:BOOL=ON \
\
-D CMAKE_BUILD_TYPE:STRING=DEBUG  \
-D CMAKE_VERBOSE_MAKEFILE:BOOL=OFF \
-D CMAKE_C_FLAGS:STRING="-fopenmp -Wno-sign-compare" \
-D CMAKE_CXX_FLAGS:STRING="-fopenmp -Wno-sign-compare" \
\
-D TPL_ENABLE_MPI:BOOL=ON \
-D MPI_EXEC_MAX_NUMPROCS:STRING=11 \
\
-D TPL_ENABLE_Pthread:BOOL=OFF \
\
-D Trilinos_ENABLE_Kokkos:BOOL=ON \
-D Trilinos_ENABLE_KokkosCore:BOOL=ON \
-D Trilinos_ENABLE_KokkosAlgorithms:BOOL=ON \
-D Kokkos_ENABLE_Serial:BOOL=ON \
\
-D Trilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=OFF \
-D Trilinos_ENABLE_TESTS:BOOL=OFF \
-D Trilinos_ENABLE_EXAMPLES:BOOL=OFF \
-D Trilinos_VERBOSE_CONFIGURE:BOOL=OFF \
\
-D Trilinos_ENABLE_Zoltan2:BOOL=ON \
-D Zoltan2_ENABLE_EXAMPLES:BOOL=OFF \
-D Zoltan2_ENABLE_TESTS:BOOL=ON \
\
-D Teuchos_ENABLE_STACKTRACE=OFF
```

In branch https://github.com/trilinos/Trilinos/tree/zoltan2_kuberry, 
the test zoltan2/test/driver/driver_inputs/kuberry will show an invalid write in valgrind:
valgrind Zoltan2_test_driver.exe kuberry.xml

**Comment by MicheldeMessieres** [comment]
@kddevin I have a fix for this. I will open a PR tomorrow.

**Comment by kddevin** [comment]
Whoa, that was fast, @MicheldeMessieres .  Thanks!

**Comment by kddevin** [comment]
Fixed by @MicheldeMessieres 
https://github.com/trilinos/Trilinos/pull/7356
