### ISSUE TITLE
Tempus:  add initialize() and setObserver() routines to IntegratorAdjointSensitivity class

### ISSUE THREAD

**Issue by ikalash** [trilinos/Trilinos#7357]
This is a feature request from Albany.  In order to add adjoint transient sensitivities to Piro/Albany given the current design (intended to work in the same way for the no sensitivity, forward sensitivity, and adjoint sensitivity case), the Tempus::IntegratorAdjointSensitivity class needs the following routines to be implemented:
- ```void initialize()```
- ```void setObserver(Teuchos::RCP< IntegratorObserver< Scalar > > obs)```

@etphipp , can you please add these to Tempus and let me know when they are there?  Hopefully it is not too difficult to do so.

@trilinos/tempus

**Comment by etphipp** [comment]
I added a PR (#7592) that adds these functions as requested.  No tempus tests use these functions, so I guess we will just wait and see how they are used in piro to see if further changes are needed.  There are also many other IntegratorBasic functions that could be added as well, but I did not do so.

**Comment by ikalash** [comment]
Routines have been added - thanks @etphipp . Closing.
