### ISSUE TITLE
Thyra:  Can't cast DefaultZeroLinearOp to MultiVectorBase

### ISSUE THREAD

**Issue by jmgate** [trilinos/Trilinos#736]
I just ran into an issue working on Charon2 in which `Teko::getBlock()` returned a `Thyra::DefaultZeroLinearOp` instead of a `Thyra::LinearOpBase`, which was expected by Charon.  That's fine&mdash;the block was zero so it makes sense.  However the next line was to `rcp_dynamic_cast` it to a `Thyra::MultiVectorBase`, which would work for a `LinearOpBase` (if that block hadn't been zero), but doesn't for a `DefaultZeroLinearOp`.  There may be a perfectly good reason for that behavior, but speaking from a perspective of complete ignorance, I would expect to be able to get a multi-vector of all zeros out of a zero linear operator.  My work-around for the time being is simply to check if I get a `DefaultZeroLinearOp` back from `getBlock()` and then proceed accordingly, but it doesn't seem like that should be necessary.  Again, speaking from inexperience with Thyra here&mdash;if there's a good reason for this behavior, feel free to close the issue.
@trilinos/thyra @trilinos/teko

**Comment by bartlettroscoe** [comment]
I think it would be non-ideal for several reasons to require `Thyra::DefaultZeroLinearOp` to derive from `Thyra::MultiVectorBase`.  If someone tries to call nonconst multi-vector function, how should that be implemented?  What operation are you trying to perform?  Is there a way to do that just using the `Thyra::LinearOpBase` interface?  That would be ideal.

**Comment by jmgate** [comment]
Ultimately I wound up doing the following:
```c++
const Teko::LinearOp G = Teko::getBlock(1, 1, op);
Teuchos::RCP<const Thyra::DefaultZeroLinearOp<double> > zeroG =
  Teuchos::rcp_dynamic_cast<const Thyra::DefaultZeroLinearOp<double> >(G);
if (zeroG.is_null())
{
  Teuchos::RCP<const Thyra::MultiVectorBase<double> > mv_G =
    Tuechos::rcp_dynamic_cast<const Thyra::MultiVectorBase<double> >(G, true);
  // Do stuff with mv_G here.
}
else
{
  // mv_G would be all zeros, so there's really nothing to do here anyway.
}
```
The reason I'm hesitant about it is that kind of checking to see what kind of child is returned by `getBlock` seems to go against principles of object-oriented design.  It works&mdash;I can leave it in there&mdash;it just doesn't feel right.

**Comment by bartlettroscoe** [comment]
Ultimately, an implicitly zero linear operator can't implement the functionality of a multi-vector.  The only commonality that an implicitly zero linear operator and a multi-vector has is that both can be applied as a linear operator.  Therefore, they share the common interface Thyra::LinearOpBase.

Can we close this issue?  Otherwise, do you want to set up a time to talk about this?

**Comment by jmgate** [comment]
Yes, this could've been closed ages ago.  Sorry about that.
