### ISSUE TITLE
ROL build failures in continuous testing

### ISSUE THREAD

**Issue by bmpersc** [trilinos/Trilinos#737]
@trilinos/rol  there are 6 build errors in ROL that can be seen at:

https://testing.sandia.gov/cdash/viewBuildError.php?buildid=2598859

**Comment by jmgate** [comment]
@dpkouri Looks like this might be due to de12cac yesterday.

**Comment by jmgate** [comment]
@bmpersc Looks like this may have been taken care of with 4469c60 and e9bcb2a yesterday.

**Comment by bmpersc** [comment]
This issue has been fixed.
