### ISSUE TITLE
Tpetra: inconsistency between BlockMultiVector, BlockVector getLocalBlock()

### ISSUE THREAD

**Issue by brian-kelley** [trilinos/Trilinos#7372]
## Semi-bug
@trilinos/tpetra 

``BlockMultiVector::getLocalBlock(row, col)`` returns a host mirror of ``little_vec_type`` (``little_vec_type`` is a 1-D scalar view on device).

But ``BlockVector::getLocalBlock(row)`` just returns a ``little_vec_type``.

This is especially confusing since BlockMultiVector is the superclass of BlockVector. I think both versions of getLocalBlock should be returning a host subview. Right now, they're both constructing an unmanaged view based on a raw host pointer, which comes from the underlying MultiVector's host side of a DualView. This also means a sync_to_host on the underlying multivector is necessary (Mark added a comment about that, and a commented out assertion of ``!mv_.need_sync_host()``).

**Comment by kddevin** [comment]
Let's keep this issue in mind as we refactor BlockCrsMatrix.  
@trilinos/tpetra

**Comment by mhoemmen** [comment]
Those classes were pretty hastily thrown together to make a certain app developer happy; they could badly use a redesign.  All of Tpetra could but that's a different task ; - ) .

**Comment by brian-kelley** [comment]
Closing this as it was resolved by @tasmith4 in 4a621e2b5f64.
