### ISSUE TITLE
Seacas: new seacas build error in Albany nightlies

### ISSUE THREAD

**Issue by ikalash** [trilinos/Trilinos#7379]
We have a new seacas build error in some of our Trilinos nightlies: 
```
Trilinos/packages/seacas/libraries/ioss/src/exodus/Ioex_IOFactory.C:121: undefined reference to `Ioex::ParallelDatabaseIO::ParallelDatabaseIO(Ioss::Region*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Ioss::DatabaseUsage, ompi_communicator_t*, Ioss::PropertyManager const&)'
```
https://sems-cdash-son.sandia.gov/cdash/viewBuildError.php?buildid=1803

I'm guessing it crept in with PR https://github.com/trilinos/Trilinos/pull/7368 ?  @gsjaardema , can you please have a look?

@trilinos/seacas

**Comment by ikalash** [comment]
@gsjaardema : thanks for putting this together so fast!  I just tried building Albany with this PR and unfortunately other issues have cropped up, e.g.: 
```
[ 55%] Linking CXX executable io_info
/usr/bin/ld: ../exodus/libIoex.so.12.17: undefined reference to `Ioex::ParallelDatabaseIO::ParallelDatabaseIO(Ioss::Region*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Ioss::DatabaseUsage, ompi_communicator_t*, Ioss::PropertyManager const&)'
collect2: error: ld returned 1 exit status
make[2]: *** [packages/seacas/libraries/ioss/src/main/CMakeFiles/io_info.dir/build.make:123: packages/seacas/libraries/ioss/src/main/io_info] Error 1
make[1]: *** [CMakeFiles/Makefile2:11650: packages/seacas/libraries/ioss/src/main/CMakeFiles/io_info.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```
I am attaching the configure script I use to build the code.  You can probably reproduce the error if you use it.  

[do-cmake-trilinos-mpi-camobap.txt](https://github.com/trilinos/Trilinos/files/4637439/do-cmake-trilinos-mpi-camobap.txt)

**Comment by gsjaardema** [comment]
What system should this be run on to make the paths work.

**Comment by ikalash** [comment]
That build script was from my Fedora workstation, which is non-standard.  But I see the same error on my RHEL7 workstation with sems modules.  The modules to load are here: https://github.com/SNLComputation/Albany/blob/master/doc/nightlyTestHarness/mockba/modules_mockba.sh and the configure script here: https://github.com/SNLComputation/Albany/blob/master/doc/nightlyTestHarness/mockba/do-cmake-trilinos-mpi-mockba .  You may have to change the blas/lapack paths, but other than that, the script should work out of the box on a RHEL7 machine with sems modules.  Please let me know if you have any problems.

**Comment by ikalash** [comment]
Finally this is fixed!  Thanks @gsjaardema !

**Comment by gsjaardema** [comment]
Sorry for the problems.  I will try to be more careful/thorough in the future.
