### ISSUE TITLE
Templated Tpetra Matrices and LP64 vs ILP64 MKL 

### ISSUE THREAD

**Issue by davoodansari** [trilinos/Trilinos#7395]
## Question
@trilinos/\<Tpetra\>

Could not find anything relevant by searching via google so here is a perhaps 'trivial' question for those who know.

I am a little confused about the relationship between the ability to chose templates matrices and vectors (specifically global ordianal and local ordianl) in Tpetra and the potential dependency on BLAS/BLACS/LAPACK. More specifically, and as an example, 
1. if someone is using a 32bit global and local ordinals, do they have to link Trilinos against LP64 MKL
2. if someone is using a 64bit global and local ordinals, do they have to link Trilinos against ILP64 MKL

**Comment by jhux2** [comment]
@trilinos/tpetra

**Comment by mhoemmen** [comment]
@davoodansari I don't work on Trilinos any more, but as far as I know, Trilinos has only ever worked with BLAS implementations that use 32-bit integers in their interface.  The BLAS wrappers are the main reason.  It could be that kokkos-kernels has fixed that issue in its BLAS wrappers, but that's a question to ask its developers.  Furthermore, plenty of downstream solvers use Teuchos' BLAS and LAPACK wrappers, and those require interfaces that take 32-bit integers.
