### ISSUE TITLE
STK:  no type named 'pushRegion' in namespace 'Kokkos::Profiling'

### ISSUE THREAD

**Issue by krcb** [trilinos/Trilinos#7399]
## Bug Report
@trilinos/stk

### Description

Trying to build Trilinos with clang 8.0.1 on MacOS X yields the following error:

```
<path-to-Trilinos>/packages/stk/stk_ngp/stk_ngp/NgpProfilingBlock.cpp:23:79: error: no type named
      'pushRegion' in namespace 'Kokkos::Profiling'
ProfilingBlock::ProfilingBlock(const std::string & name) { Kokkos::Profiling::pushRegion(name); }
                                                           ~~~~~~~~~~~~~~~~~~~^
<path-to-Trilinos>/packages/stk/stk_ngp/stk_ngp/NgpProfilingBlock.cpp:31:22: error: no member named
      'popRegion' in namespace 'Kokkos::Profiling'
  Kokkos::Profiling::popRegion();
  ~~~~~~~~~~~~~~~~~~~^
2 errors generated.​
```

This appears to be due to a missing include:

```
diff --git a/packages/stk/stk_ngp/stk_ngp/NgpProfilingBlock.cpp b/packages/stk/stk_ngp/stk_ngp/NgpProfilingBlock.cpp
index 3950f771e33..d4243784d50 100644
--- a/packages/stk/stk_ngp/stk_ngp/NgpProfilingBlock.cpp
+++ b/packages/stk/stk_ngp/stk_ngp/NgpProfilingBlock.cpp
@@ -7,6 +7,7 @@
 /*    a license from the United States Government.                    */
 /*--------------------------------------------------------------------*/
 
+#include <Kokkos_Core.hpp>
 #include <Kokkos_Macros.hpp>
 #include <stk_ngp/NgpProfilingBlock.hpp>
 // mfh 27 Sep 2017: Note that it is possible to disable Kokkos'
```

### Steps to Reproduce
1. SHA1:  [insert here]
1. Configure script:  [attach here]
1. Configure log:  [attach here]
1. Build log:  [attach here]
1. Input deck:  [attach here]
1. Do this.
1. Do that.
1. Shake fist angrily at computer.
1. Run log:  [attach here]

**Comment by rppawlo** [comment]
@krcb - are you using the github trilinos or the empire fork of trilinos?

**Comment by krcb** [comment]
@rppawlo The empire fork.

**Comment by rppawlo** [comment]
@krcb - This is something @bathmatt was looking at and is specific to the empire fork. empire fork has pulled in changes to kokkos profile API (not currently in github trilinos version of kokkos) that breaks stk but so far only for one user. Sean saw this in an ubuntu build. See https://github.com/trilinos/Trilinos/pull/7370 and the internal gitlab issue on profiling hooks. Incidentally, I believe that this change means we can't use github trilinos directly against empire. They will sync up again once the next kokkos release is promoted into trilinos in about a month.

**Comment by krcb** [comment]
@rppawlo Great, thanks for the clarification. I will close this.

**Comment by alanw0** [comment]
One subtlety is that I think Matt made the fix (include a different/new kokkos header) in a stk_mesh file but we have the same file in the stk_ngp directory which is on its way to being deprecated. Theoretically stk_ngp shouldn't be built, as I don't think anything should need it. But it might get enabled by default so it might be necessary to add -DTrilinos_ENABLE_STKNGP:BOOL=FALSE
