### ISSUE TITLE
Teuchos: Move YAML ParameterList document into header file

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#741]
@trilinos/teuchos @DrBooom 

It lives in Trilinos/packages/teuchos/doc/paramlist_yaml.tex.  It should go into the YAML header file as Doxygen.

**Comment by ibaned** [comment]
I think I'm de facto in charge of YAML now...

**Comment by mhoemmen** [comment]
> I think I'm de facto in charge of YAML now...

No complaints :-D

**Comment by ibaned** [comment]
Pull request #1851 copied this document into Doxygen for the file `Teuchos_YamlParser_decl.hpp` in TeuchosParameterList.
