### ISSUE TITLE
MueLu: error when calling ReuseTpetraPreconditioner

### ISSUE THREAD

**Issue by jhux2** [trilinos/Trilinos#7411]
A number of users have reported that when using `ReuseTpetraPreconditioner`, the resulting `Hierarchy::apply()` crashes on the second go-round.

**Comment by jhux2** [comment]
I have a unit test that reproduces this.

**Comment by jhux2** [comment]
@vbrunini @rcknaus

**Comment by jhux2** [comment]
The PR that fixes this is now in Trilinos/develop.  Please let me know whether this fixes the problem for you.

**Comment by vbrunini** [comment]
Confirmed that this fixes the problem for both of our test cases.
