### ISSUE TITLE
Trilinos-amesos2:  Add STRUMPACK solver

### ISSUE THREAD

**Issue by lisaclaus** [trilinos/Trilinos#7413]
## Enhancement
@trilinos/\<Amesos2\>

Please review the changes we made to include STRUMPACK as a direct solver in the Trilinos-amesos2 interface.

**Comment by jhux2** [comment]
@lisaclaus If there is a PR that the @trilinos/amesos2 team should see, please link it to this issue.

**Comment by lisaclaus** [comment]
#7417

**Comment by srajama1** [comment]
This can be closed, right? @lisaclaus

**Comment by lisaclaus** [comment]
Yes, thanks @srajama1
