### ISSUE TITLE
Framework: Launch autotester, but don't approve PR

### ISSUE THREAD

**Issue by cgcgcg** [trilinos/Trilinos#7426]
## Question
@trilinos/framework 

Is there a way that I can launch the autotester for a PR created by someone who is not part of the Trilinos organisation without outright approving the PR?

**Comment by jwillenbring** [comment]
@cgcgcg I would need to understand a little more about what you mean. If auto merge is not on, approval will not cause the PR to merge after testing. I believe you could also watch it and modify your review after the testing starts. Another approach would be to submit your own PR with the changes from the PR, and then close your PR later. What is your objective?

**Comment by jhux2** [comment]
> This is mostly for when we get a PR from someone we don't really know. After looking over the proposed changes, I want them tested, but I want to avoid that me or someone else hits 'Merge' by accident once the AT succeeds. I guess I could change to a draft PR to avoid that. Alternatively, it could be nice if setting the AT:RETEST label would lauch the autotester regardless.

@cgcgcg This is now possible via the `AT: PRE-TEST INSPECTED` tag.
