### ISSUE TITLE
Trilinos PR tester allowing merge of "Stale" without new round of testing

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#7428]
## Bug Report
@trilinos/framework 

### Description

For the long-stale PR #7229, I just removed the `AT: STALE` label and added the `AT: RETEST` label and GitHub shows that I can merge this right away showing:

![image](https://user-images.githubusercontent.com/1959736/82930905-1fee4680-9f54-11ea-87bd-63f255ca4d6d.png)

last comment from the PR tester shown [here](https://github.com/trilinos/Trilinos/pull/7229#issuecomment-633747943) stated:

> All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested. Set the AT: RETEST Label to force retest....

Is this a bug?  I mean I could just click the merge button and it it looks like GitHub would merge this.

### Steps to Reproduce

I just added the label `AT: STALE` and added the label `AT: RETEST` and GitHub showed that I was allowed to merge the PR.  See that history starting [here](https://github.com/trilinos/Trilinos/pull/7229#event-3374575753).

**Comment by bartlettroscoe** [comment]
Just to prove what I am seeing, here is the GitHub page for #7229 right now:

![image](https://user-images.githubusercontent.com/1959736/82931385-d7835880-9f54-11ea-991f-1cf50db1ec8a.png)

**Comment by prwolfe** [comment]
If I remember correctly, the autotester expects it will be the only one setting and removing the Stale tag. There is no enforcement however. You will note that after your removal the autotester added it back in, then removed it when the tests fired about 30 seconds later.

**Comment by bartlettroscoe** [comment]
> If I remember correctly, the autotester expects it will be the only one setting and removing the Stale tag. There is no enforcement however. 

So an impatient developer can just quickly remove the `AT: STALE` label and then quickly click the "Merge" button?

**Comment by prwolfe** [comment]
> > If I remember correctly, the autotester expects it will be the only one setting and removing the Stale tag. There is no enforcement however.
> 
> So an impatient developer can just quickly remove the `AT: STALE` label and then quickly click the "Merge" button?

That would be bad and likely subject to "revert" and involve "talking to". We will discuss this one at stand-up in the AM. I'm pretty sure that the tests had to have previously passed as well.
