### ISSUE TITLE
Intrepid2 build errors in the tests intrepid2/unit-test/Projection/OpenMP starting 2020-05-27

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#7435]
CC: @trilinos/intrepid2, @mperego (Trilinos Discretizations Product Lead)

<Checklist>
<???: Add label "client: ATDM">
<???: Add label "ATDM Sev: Blocker" (by default but could be other "ATDM Sev: XXX")>
<???: Add label "type: bug"?>
<???: Add label "impacting: tests"?>
<???: Add label for affected packages (e.g. "pkg: MueLu", "pkg: Tpetra", "pkg: Kokkos", etc.)>
<???: Add label "PA: ???Project Area???" (e.g. "PA: Linear Solvers", "PA: Data Services")>
<???: Add milestone "Initial cleanup of new ATDM ..." or "Keep promoted ATDM ...">
<???: Once GitHub Issue is created, add entries for tests to TrilinosATDMStatus/*.csv files>

## Next Action Status

<status-and-or-first-action>

## Description

As shown in [this query](https://testing-dev.sandia.gov/cdash/index.php?project=Trilinos&date=2020-05-27&filtercount=4&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-ats1&field2=buildname&compare2=64&value2=-exp&field3=builderrors&compare3=43&value3=0&field4=subprojects&compare4=93&value4=Intrepid2) Intrepid2 is failing to build in new 'ats1' builds showing build errors in all of the opt builds:

* Trilinos-atdm-ats1-hsw_intel-18.0.5_mpich-7.7.6_openmp_static_opt
* Trilinos-atdm-ats1-hsw_intel-19.0.4_mpich-7.7.6_openmp_static_opt
* Trilinos-atdm-ats1-knl_intel-18.0.5_mpich-7.7.6_openmp_static_opt
* Trilinos-atdm-ats1-knl_intel-19.0.4_mpich-7.7.6_openmp_static_opt

The build errors impact the Intrepid2 test targets:

* packages/intrepid2/unit-test/Projection/OpenMP/CMakeFiles/Intrepid2_unit-test_Projection_OpenMP_Test_Convergence_QUAD.dir/test_convergence_QUAD.cpp.o
* packages/intrepid2/unit-test/Projection/OpenMP/CMakeFiles/Intrepid2_unit-test_Projection_OpenMP_Test_Convergence_HEX.dir/test_convergence_HEX.cpp.o
* packages/intrepid2/unit-test/Projection/OpenMP/CMakeFiles/Intrepid2_unit-test_Projection_OpenMP_Test_Convergence_TET.dir/test_convergence_TET.cpp.o
* packages/intrepid2/unit-test/Projection/OpenMP/CMakeFiles/Intrepid2_unit-test_Projection_OpenMP_Test_Convergence_TRI.dir/test_convergence_TRI.cpp.o

and show the build errors:

```
/lscratch1/jenkins/mutrino-slave/workspace/Trilinos-atdm-ats1-driver/Trilinos-atdm-ats1-hsw_intel-18.0.5_mpich-7.7.6_openmp_static_opt/SRC_AND_BUILD/Trilinos/packages/intrepid2/unit-test/Projection/OpenMP/test_convergence_QUAD.cpp(57): error: namespace "Kokkos" has no member "Serial"
    const int r_val = Intrepid2::Test::ConvergenceQuad<double,Kokkos::Serial>(verbose);
                                                                      ^

/lscratch1/jenkins/mutrino-slave/workspace/Trilinos-atdm-ats1-driver/Trilinos-atdm-ats1-hsw_intel-18.0.5_mpich-7.7.6_openmp_static_opt/SRC_AND_BUILD/Trilinos/packages/intrepid2/unit-test/Projection/OpenMP/test_convergence_QUAD.cpp(57): error: no instance of function template "Intrepid2::Test::ConvergenceQuad" matches the argument list
            argument types are: (const bool)
    const int r_val = Intrepid2::Test::ConvergenceQuad<double,Kokkos::Serial>(verbose);
                      ^
/lscratch1/jenkins/mutrino-slave/workspace/Trilinos-atdm-ats1-driver/Trilinos-atdm-ats1-hsw_intel-18.0.5_mpich-7.7.6_openmp_static_opt/SRC_AND_BUILD/Trilinos/packages/intrepid2/unit-test/Projection/OpenMP/../test_convergence_QUAD.hpp(101): note: this candidate was rejected because there is a type mismatch after argument substitution
  int ConvergenceQuad(const bool verbose) {
      ^

compilation aborted for /lscratch1/jenkins/mutrino-slave/workspace/Trilinos-atdm-ats1-driver/Trilinos-atdm-ats1-hsw_intel-18.0.5_mpich-7.7.6_openmp_static_opt/SRC_AND_BUILD/Trilinos/packages/intrepid2/unit-test/Projection/OpenMP/test_convergence_QUAD.cpp (code 2)
```

There were no build errors in the 'dbg' builds because we don't build any test executables in the 'dbg' builds.

The new commits that were pulled on testing day 2020-05-27 as shown, for example, [here](https://testing-dev.sandia.gov/cdash/viewNotes.php?buildid=5483728#!#note1).  Looking at those commits, it looks likely the trigger was the PR #7201.

## Current Status on CDash

* [Trilinos-atdm-ats1 builds for the current testing day](https://testing-dev.sandia.gov/cdash/index.php?project=Trilinos&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-ats1&field2=buildname&compare2=64&value2=-exp&field3=subprojects&compare3=93&value3=Intrepid2)

## Steps to Reproduce

One should be able to reproduce this failure on the machine <supported-atdm-machine> as described in:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md

More specifically, the commands given for the system <supported-atdm-system> are provided at:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#mutrino

The exact commands to reproduce this issue should be:

```
$ cd <some_build_dir>/

$ source $TRILINOS_DIR/cmake/std/atdm/load-env.sh \
  Trilinos-atdm-ats1-hsw_intel-18.0.5_mpich-7.7.6_openmp_static_opt

$ cmake \
 -GNinja \
 -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
 -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_Intrepid2=ON \
 $TRILINOS_DIR

$ make NP=16
```

**Comment by bartlettroscoe** [comment]
CC: @e10harvey 

Looking over this, it seems that the reason that these tests don't build in the 'ats1' builds but do build in the other ATDM Trilinos builds is that `Kokkos_ENABLE_Serial` is set to `OFF` in the 'ats1' builds as shown [here]() showing:

```
Kokkos_ENABLE_SERIAL:BOOL=OFF
```

but is turned on in all of the other ATDM Trilinos builds.

I am going to go ahead and turn Kokkos_ENABLE_SERIAL:BOOL=ON like in all of the other ATDM Trilinos builds (and all of the Trilinos PR builds).  There is no reason why only the 'ats1' builds should have `Kokkos_ENABLE_SERIAL:BOOL=OFF` set and not all of the other builds.

If SPARC really does not want `Kokkos_ENABLE_SERIAL:BOOL=ON`, then we should do that in all of the ATDM Trilinos builds and we will need a Trilinos PR build to protect that.  (Otherwise, we are just signing up for pain in having to triage failures that skip through PR testing.)

**Comment by e10harvey** [comment]
> then we should do that in all of the ATDM Trilinos builds and we will need a Trilinos PR build to protect that. (Otherwise, we are just signing up for pain in having to triage failures that skip through PR testing.)

Should we check with those developers before changing serial to on? We worked hard to match these settings, and, if they're needed for this system, I don't think we should change them without checking.

If serial should be on, why not disable those tests?

**Comment by bartlettroscoe** [comment]
> Should we check with those developers before changing serial to on? We worked hard to match these settings, and, if they're needed for this system, I don't think we should change them without checking.

@e10harvey, `Kokkos_ENABLE_SERIAL=ON` is set in every other ATDM Trilinos build except for these 'ats1' builds.  That does not make sense.  Either  `Kokkos_ENABLE_SERIAL=ON` should be set in every ATDM Trilinos build or `Kokkos_ENABLE_SERIAL=OFF` should be set in every ATDM Trilinos builds.

> If serial should be on, why not disable those tests?

If we need support for building `Kokkos_ENABLE_OpenMP=ON` and `Kokkos_ENABLE_SERIAL=OFF`, then we need Trilinos to support that configuration and that means we need at least one of the Trilinos PRs to use those settings.  Otherwise, we are asking for broken builds and wasted time (my time) having to triage builds that slip through PR testing.

I will open an ATDV issue to investigate the issue of `Kokkos_ENABLE_SERIAL` and SPARC.

**Comment by bartlettroscoe** [comment]
Turns out we already had an ATDV issue to study the impact of setting `Kokkos_ENABLE_SERIAL=ON` for SPARC in all of the ATDM Trilinos builds in [ATDV-337](https://sems-atlassian-srn.sandia.gov/browse/ATDV-337).  We just need to do that study.  But until we do, we need to set  `Kokkos_ENABLE_SERIAL=ON` in the 'ats1' builds to be consistent with all of the other ATDM Trilinos builds.

**Comment by bartlettroscoe** [comment]
For example, it the OpenMP build `Trilinos-atdm-cee-rhel6_intel-18.0.2_mpich2-3.2_openmp_static_opt` we see [here](https://testing-dev.sandia.gov/cdash/build/5483623/notes#note7)

```
Kokkos_ENABLE_OPENMP:BOOL=ON
...
Kokkos_ENABLE_SERIAL:BOOL=ON
```

and we know that SPARC works okay against that build.  So why would we not also set `Kokkos_ENABLE_SERIAL:BOOL=ON` in the 'ats1' builds?

**Comment by e10harvey** [comment]
Thanks for looking into this, Ross!

> So why would we not also set `Kokkos_ENABLE_SERIAL:BOOL=ON` in the 'ats1' builds?

The instructions given for setting up this environment were to match their settings, which have SERIAL set to OFF.

**Comment by bartlettroscoe** [comment]
> The instructions given for setting up this environment were to match their settings, which have SERIAL set to OFF.

@e10harvey, that is true, but we also talked about the fact that we don't expect to exactly match the settings.  The problem we are trying to solve with each new env setup is:

* Minimize configuration changes w.r.t. other ATDM Trilinos configurations
* Subject to: Make Trilinos, SPARC, and EMPIRE work

**Comment by mperego** [comment]
@bartlettroscoe Thanks Ross, I'll try to fix it later today. It's actually good that we have some tests with `Kokkos_ENABLE_SERIAL=OFF`. Otherwise I'd never firgure out that this test was acually running on Serial instead of OpenMP (it was a copy and paste error from the serial analog of this test).

**Comment by bartlettroscoe** [comment]
> It's actually good that we have some builds with Kokkos_ENABLE_SERIAL=OFF

@mperego, I agree, but that needs to be set in one of the Trilinos PR builds that has OpenMP enabled so that these don't slip through PR testing and then we have to deal with in in that ATDM Trilinos builds.  As a Trilinos Product Area lead, can you please request that the Trilinos Framework team set `Kokkos_ENABLE_OpenMP=ON` and `Kokkos_ENABLE_SERIAL=OFF` in at least one PR build.

**Comment by mperego** [comment]
> > It's actually good that we have some builds with Kokkos_ENABLE_SERIAL=OFF
> 
> @mperego, I agree, but that needs to be set in one of the Trilinos PR builds that has OpenMP enabled so that these don't slip through PR testing and then we have to deal with in in that ATDM Trilinos builds. As a Trilinos Product Area lead, can you please request that the Trilinos Framework team set `Kokkos_ENABLE_OpenMP=ON` and `Kokkos_ENABLE_SERIAL=OFF` in at least one PR build?

Sure, I will.

**Comment by bartlettroscoe** [comment]
One interesting thing about a test build failure like this is that it does not damage the install of Trilinos.  That is because we build with `ninja -k 999999` so it builds every target that will build (which includes all of the libraries).  Also, installs are done using the custom TriBITS [`install_package_by_package` target](https://tribits.org/doc/TribitsBuildReference.html#installing-the-software) which is robust to build errors. (The default CMake-created `install` target is not.  It will not install if there is even one build error in a test.)  So the SPARC Trilinos Integration builds (if those were set up yet) would not have been impacted by this at all.

Therefore, the only impact these tests build errors have is to not build some test executables which results in some "Not Run" tests as shown [here](https://testing-dev.sandia.gov/cdash/viewTest.php?onlynotrun&buildid=5483590) showing:

Name | Status | Time | Proc Time | Details | Labels | History | Summary | Processors
-- | -- | -- | -- | -- | -- | -- | -- | --
Intrepid2_unit-test_Projection_OpenMP_Test_Convergence_HEX_MPI_1 | Not Run | 0s | 0s | Required Files Missing | Intrepid2 | Inactive | Inactive | 1
Intrepid2_unit-test_Projection_OpenMP_Test_Convergence_QUAD_MPI_1 | Not Run | 0s | 0s | Required Files Missing | Intrepid2 | Inactive | Inactive | 1
Intrepid2_unit-test_Projection_OpenMP_Test_Convergence_TET_MPI_1 | Not Run | 0s | 0s | Required Files Missing | Intrepid2 | Inactive | Inactive | 1
Intrepid2_unit-test_Projection_OpenMP_Test_Convergence_TRI_MPI_1 | Not Run | 0s | 0s | Required Files Missing | Intrepid2 | Inactive | Inactive | 1

**Comment by bartlettroscoe** [comment]
After the merge of PR #7435 yesterday, we can see the Intrepid2 build errors are gone today as shown at:

* https://testing-dev.sandia.gov/cdash/index.php?project=Trilinos&date=2020-05-28&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-ats1&field2=buildname&compare2=64&value2=-exp

showing:

| Site | Build Name | Update | Update Time | C Err | C Warn | C Time | B Err | B Warn | B Time | Not Run | Fail | Pass | Time | Proc Time | Start Time | Labels |
| -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- |
mutrino | Trilinos-atdm-ats1-hsw_intel-18.0.5_mpich-7.7.6_openmp_static_dbg | 278411 | 1m 48s | 0 | 5 | 8m 36s | 0 | 50 | 49m 32s | 0 | 0 | 0 | 0s | 0s | 9 hours ago | (28 labels)
mutrino | Trilinos-atdm-ats1-hsw_intel-18.0.5_mpich-7.7.6_openmp_static_opt | 278411 | 2m 30s | 0 | 5 | 14m 17s | 0 | 50 | 3h 4m 5s | 0 | 11 | 2252 | 3h 45m 13s | 8h 18m 3s | 10 hours ago | (28 labels)
mutrino | Trilinos-atdm-ats1-hsw_intel-19.0.4_mpich-7.7.6_openmp_static_dbg | 278411 | 2m 12s | 0 | 5 | 8m 5s | 0 | 50 | 1h 7m 19s | 0 | 0 | 0 | 0s | 0s | 9 hours ago | (28 labels)
mutrino | Trilinos-atdm-ats1-hsw_intel-19.0.4_mpich-7.7.6_openmp_static_opt | 179a7b | 1m 18s |   |   |   |   |   |   |   |   |   |   |   | 10 hours ago | (none)
mutrino | Trilinos-atdm-ats1-knl_intel-18.0.5_mpich-7.7.6_openmp_static_dbg | 278411 | 2m 12s | 0 | 5 | 8m 30s | 0 | 50 | 1h 43m 49s | 0 | 0 | 0 | 0s | 0s | 9 hours ago | (28 labels)
mutrino | Trilinos-atdm-ats1-knl_intel-18.0.5_mpich-7.7.6_openmp_static_opt | 278411 | 1m 54s | 0 | 5 | 14m 20s | 0 | 50 | 5h 46m 16s |   |   |   |   |   | 10 hours ago | (28 labels)
mutrino | Trilinos-atdm-ats1-knl_intel-19.0.4_mpich-7.7.6_openmp_static_dbg | 278411 | 1m 48s | 0 | 5 | 8m 22s | 0 | 50 | 2h 1m 5s | 0 | 0 | 0 | 0s | 0s | 9 hours ago | (28 labels)
mutrino | Trilinos-atdm-ats1-knl_intel-19.0.4_mpich-7.7.6_openmp_static_opt | 278411 | 2m 18s | 0 | 5 | 14m 7s | 0 | 50 | 5h 33m 16s |   |   |   |   |   | 10 hours ago | (28 labels)

Closing as complete.
