### ISSUE TITLE
Epetra: Building specifically with MPI? 

### ISSUE THREAD

**Issue by jtoumey** [trilinos/Trilinos#7436]
## Question
@trilinos/Epetra

I am building a parallel application (using OpenMPI) that links with several Trilinos packages. The build platform is OpenSUSE 15.1 desktop with gcc 7.5.0 and Trilinos version 10.10.0.

When I compile the application, the source files are successfully compiled to object files, but the linker fails with the following error:
```
/home/julian/try03/Chisels/src/Obj_tel/update_aztec.cpp:230: undefined reference to `Epetra_MpiComm::Epetra_MpiComm(ompi_communicator_t*)'
collect2: error: ld returned 1 exit status
```

When I examine the static library `libepetra.a` with the `nm` tool, I find that the symbol is not included in the library:
```
$ nm -a libepetra.a | grep 'Epetra_MpiComm' 

```

**My question:** Does one have to build Epetra with MPI enabled in order to have access to these Epetra MPI constructors? In my `do-configure` script, I added the line to enable MPI, but I get an error in building Teuchos right away: 
```
julian@linux-myhg:~/Libraries/Trilinos/BUILD_DIR> make 
[  0%] Building CXX object packages/teuchos/src/CMakeFiles/teuchos.dir/Teuchos_CTimeMonitor.cpp.o
In file included from /home/julian/Libraries/Trilinos/packages/teuchos/src/Teuchos_FancyOStream.hpp:46:0,
                 from /home/julian/Libraries/Trilinos/packages/teuchos/src/Teuchos_Describable.hpp:46,
                 from /home/julian/Libraries/Trilinos/packages/teuchos/src/Teuchos_ReductionOp.hpp:45,
                 from /home/julian/Libraries/Trilinos/packages/teuchos/src/Teuchos_Comm.hpp:45,
                 from /home/julian/Libraries/Trilinos/packages/teuchos/src/Teuchos_TimeMonitor.hpp:64,
                 from /home/julian/Libraries/Trilinos/packages/teuchos/src/Teuchos_CTimeMonitor.cpp:43:
/home/julian/Libraries/Trilinos/packages/teuchos/src/Teuchos_GlobalMPISession.hpp:52:10: fatal error: mpi.h: No such file or directory
 #include "mpi.h"
          ^~~~~~~
compilation terminated.
make[2]: *** [packages/teuchos/src/CMakeFiles/teuchos.dir/build.make:87: packages/teuchos/src/CMakeFiles/teuchos.dir/Teuchos_CTimeMonitor.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1170: packages/teuchos/src/CMakeFiles/teuchos.dir/all] Error 2
make: *** [Makefile:163: all] Error 2
fatal error: mpi.h: No such file or directory not found
 #include "mpi.h"
``` 

The script: 

```
#!/bin/sh

export TRILINOS_HOME=/home/julian/Libraries/Trilinos
EXTRA_ARGS=$@

cmake \
    -D BUILD_SHARED_LIBS=OFF \
    -D TPL_ENABLE_MPI=ON \
    -D MPI_BASE_DIR='/usr/lib64/mpi/gcc/openmpi/' \
    -D Trilinos_ENABLE_Epetra=ON \
    -D Trilinos_ENABLE_AztecOO=ON \
    -D Trilinos_ENABLE_Zoltan=ON \
    -D Trilinos_ENABLE_TESTS=ON \
    -D TPL_BLAS_LIBRARIES=/usr/lib64/libblas.so.3 \
    -D TPL_LAPACK_LIBRARIES=/usr/lib64/liblapack.so.3 \
    $EXTRA_ARGS \
    ${TRILINOS_HOME}
```

Thanks for any help!

**Comment by cgcgcg** [comment]
@jtoumey Looks like your MPI wasn't found. Did cmake find MPI? You might have to start with a clean build. Maybe also set `-D MPI_BASE_DIR:STRING=` to where your MPI is installed?

**Comment by kddevin** [comment]
@jtoumey You do not have to explicitly enable MPI for Epetra.  Your script looks OK to me.  I agree with @cgcgcg; your path to MPI may not be correct.
The following script (based on yours) works for me.

```
cmake \
    -D BUILD_SHARED_LIBS=OFF \
    -D TPL_ENABLE_MPI=ON \
    -D Trilinos_ENABLE_Fortran=OFF \
    -D MPI_BASE_DIR='/Users/InstalledSoftware/openmpi-1.8.3' \
    -D Trilinos_ENABLE_Epetra=ON \
    -D Trilinos_ENABLE_AztecOO=ON \
    -D Trilinos_ENABLE_Zoltan=ON \
    -D Trilinos_ENABLE_TESTS=ON \
    .. |& tee OUTPUT.CMAKE
```

**Comment by jtoumey** [comment]
@cgcgcg @kddevin Thank you both kindly. 

I rebuilt in a new directory and this appears to resolve the `mpi.h: No such file...` error. Additionally, issuing `$ nm -a libepetra.a | grep 'Epetra_MpiComm` reveals that the necessary symbols are now in the static library. 

Much appreciated.
