### ISSUE TITLE
Add Kokkos_ENABLE_SERIAL=OFF to PR testing

### ISSUE THREAD

**Issue by jwillenbring** [trilinos/Trilinos#7441]
## Enhancement
@trilinos/framework 

@mperego requested that we add the

Kokkos_ENABLE_SERIAL=OFF

option to one of the PR builds. I think we could add this to the GCC 4.8.4 build unless someone sees a reason that is not a good idea.

**Comment by wadeburgess** [comment]
https://sems-atlassian-son.sandia.gov/jira/projects/TRILINOSHD/queues/custom/122/TRILINOSHD-3

**Comment by wadeburgess** [comment]
Migrated to Trilinos Help Desk, so closing this issue now.
