### ISSUE TITLE
STK build errors in Trilinos-atdm-cts1-intel-19.0.5_openmpi-4.0.1_openmp_static_dbg build starting 2020-05-27

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#7444]
CC: ???

## Description

As shown in [this query](https://testing-dev.sandia.gov/cdash/index.php?project=Trilinos&begin=2020-05-24&end=2020-05-28&filtercount=1&showfilters=1&field1=buildname&compare1=61&value1=Trilinos-atdm-cts1-intel-19.0.5_openmpi-4.0.1_openmp_static_dbg), the build:

* `Trilinos-atdm-cts1-intel-19.0.5_openmpi-4.0.1_openmp_static_dbg`

is showing build errors related to STK starting on testing day 2020-04-27.

The error yesterday shown [here](https://testing-dev.sandia.gov/cdash/viewBuildError.php?buildid=5484639) showed an error in linking the target:

* `packages/stk/stk_tools/stk_tools/stk_block_extractor`

showing the build error:

```
/usr/bin/ar: packages/stk/stk_mesh/stk_mesh/base/libstk_mesh_base.a: Error reading packages/stk/stk_mesh/stk_mesh/base/CMakeFiles/stk_mesh_base.dir/__/baseImpl/EquivalentEntityBlocks.cpp.o: File truncated
```

**Comment by bartlettroscoe** [comment]
Hum the build errors today shown [here](https://testing-dev.sandia.gov/cdash/index.php?project=Trilinos&parentid=5487561) and [here](https://testing-dev.sandia.gov/cdash/viewBuildError.php?buildid=5487561) start in STK are showing a different link-time error:

```
packages/stk/stk_io/stk_io/libstk_io.a(IOHelpers.cpp.o): In function `void stk::io::fill_element_and_side_ids_from_sideset<int>(stk::mesh::SideSet const&, stk::io::OutputParams&, stk::mesh::Part const*, stk::mesh::Part const*, stk::topology, std::vector<stk::mesh::Entity, std::allocator<stk::mesh::Entity> >&, std::vector<int, std::allocator<int> >&)':
/nscratch/jenkins/eclipse-slave/workspace/Trilinos-atdm-cts1-intel-19.0.5_openmpi-4.0.1_openmp_static_dbg/SRC_AND_BUILD/Trilinos/packagesstk_io/stk_io/SidesetTranslator.hpp:82: undefined reference to `stk::mesh::impl::get_element_block_part_ordinals(stk::mesh::Entity, stk::mesh::BulkData const&, std::vector<unsigned int, std::allocator<unsigned int> >&)'
packages/stk/stk_io/stk_io/libstk_io.a(IossBridge.cpp.o): In function `void stk::io::fill_element_and_side_ids_from_sideset<long>(stk::mesh::SideSet const&, stk::io::OutputParams&, stk::mesh::Part const*, stk::mesh::Part const*, stk::topology, std::vector<stk::mesh::Entity, std::allocator<stk::mesh::Entity> >&, std::vector<long, std::allocator<long> >&)':
/nscratch/jenkins/eclipse-slave/workspace/Trilinos-atdm-cts1-intel-19.0.5_openmpi-4.0.1_openmp_static_dbg/SRC_AND_BUILD/Trilinos/packagesstk_io/stk_io/SidesetTranslator.hpp:82: undefined reference to `stk::mesh::impl::get_element_block_part_ordinals(stk::mesh::Entity, stk::mesh::BulkData const&, std::vector<unsigned int, std::allocator<unsigned int> >&)'
```

I am going to try a build from scratch locally and see if I can reproduce this or not.

**Comment by alanw0** [comment]
@bartlettroscoe those build errors are puzzling, they appear to reference functions/files that the stk team hasn't touched recently. I'll see if I can help figure out what's going on.

**Comment by bartlettroscoe** [comment]
> I'll see if I can help figure out what's going on.

@alanw0, let me run a local build on 'eclipse' and see if i can reproduce this.  I am suspicious this might be due to some type of random disk IO error and a build from scratch might fix this.

**Comment by bartlettroscoe** [comment]
On 'eclipse' I ran:

```
$ ./ctest-s-local-test-driver.sh cts1-intel-19.0.5_openmpi-4.0.1_openmp_static_dbg
```

and it is posting to CDash:

* https://testing-dev.sandia.gov/cdash/index.php?project=Trilinos&date=2020-05-28&filtercount=1&showfilters=1&field1=buildname&compare1=61&value1=Trilinos-atdm-cts1-intel-19.0.5_openmpi-4.0.1_openmp_static_dbg-exp

showing:

| Site | Build Name | C Err | C Warn | C Time | B Err | B Warn | B Time | Start Time | Labels |
| -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | 
eclipse-login6 | Trilinos-atdm-cts1-intel-19.0.5_openmpi-4.0.1_openmp_static_dbg-exp | 0 | 4 | 9m 27s | 0 | 50 | 8h 14m 41s | 9 hours ago | (28 labels)

(The tests are still running.)

So it looks like this will build correctly from scratch.

I will set up the jenkins job to build from scratch tomorrow.

**Comment by alanw0** [comment]
@bartlettroscoe thanks for investigating

**Comment by bartlettroscoe** [comment]
Meant to post this yesterday ...

FYI: I deleted the build directory with the dummy Jenkins job:

* https://jenkins-srn.sandia.gov/view/Trilinos%20ATDM/job/Trilinos-atdm-do-stuff/14/console

This should build from scratch tomorrow.

**Comment by bartlettroscoe** [comment]
FYI: Note that the fact that the build `Trilinos-atdm-cts1-intel-19.0.5_openmpi-4.0.1_openmp_static_dbg` from scratch on 'eclipse' took 8h14m as shown [here](https://testing-dev.sandia.gov/cdash/index.php?project=Trilinos&date=2020-05-28&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-cts1&field2=buildname&compare2=63&value2=-exp) where the median rebuild time for this build over the last month is about 1h as shown in [this query](https://testing-dev.sandia.gov/cdash/index.php?project=Trilinos&begin=2020-05-01&end=2020-05-28&filtercount=1&showfilters=1&field1=buildname&compare1=61&value1=Trilinos-atdm-cts1-intel-19.0.5_openmpi-4.0.1_openmp_static_dbg) is why we suffer through some of these inconveniences with doing rebuilds.

There is no way we would get all of the ATDM Trilinos builds done every day on average on all of these systems if we always did builds from scratch every day.

**Comment by bartlettroscoe** [comment]
The build `Trilinos-atdm-cts1-intel-19.0.5_openmpi-4.0.1_openmp_static_dbg` ran from scratch today and submitted to CDash as shown here:

* https://testing-dev.sandia.gov/cdash/index.php?project=Trilinos&date=2020-05-29&filtercount=1&showfilters=1&field1=buildname&compare1=65&value1=Trilinos-atdm-cts1-intel-19.0.5_openmpi-4.0.1_openmp_static_dbg

showing a 100% passing build:

| Site | Build Name | Update | Update Time | C Err | C Warn | C Time | B Err | B Warn | B Time | Start Time | Labels |
| -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- |
eclipse | Trilinos-atdm-cts1-intel-19.0.5_openmpi-4.0.1_openmp_static_dbg | f60f18 | 1m 18s | 0 | 3 | 7m 49s | 0 | 50 | 7h 46m 7s | 10 hours ago | (28 labels)

The SLURM job that runs the tests is still stick in the queue on 'eclipse' so we don't have test results yet but since this Issue was about a build error and this shows that a build-from-scratch fixed the build error, I think it is safe to close this issue. 

As is suspected, this build error was likely due to a random disk IO problem or other random fluke and does not represent a likely problem with any Trilinos code.

Closing as complete.
