### ISSUE TITLE
Sacado: changes broke Albany build

### ISSUE THREAD

**Issue by ikalash** [trilinos/Trilinos#7445]
It looks like recent changes to Sacado broke all the nightly Albany builds: https://sems-cdash-son.sandia.gov/cdash/index.php?project=Albany&date=2020-05-28&filtercount=1&showfilters=1&field1=groupname&compare1=61&value1=Nightly .  In particular, it looks like setUpdateValue has gone away: 
```
/.../repos/Albany/src/evaluators/gather/PHAL_GatherScalarNodalParameter_Def.hpp(188): error: class "Sacado::Fad::Exp::GeneralFad<Sacado::Fad::Exp::StaticStorage<RealType, 100>>" has no member "setUpdateValue" .  
```
https://sems-cdash-son.sandia.gov/cdash/viewBuildError.php?buildid=2186

Is there an alternate routine we can use that this one was replaced with?

@trilinos/sacado 

@etphipp

**Comment by etphipp** [comment]
Sorry about this @ikalash.  I guess I removed this functionality in the new Fad design.  This functionality had very limited utility, it was only useful for differentiating linear problems and would avoid computation of the residual in the derivative computation (which was really only useful for intrusive PCE with Stokhos).  I can add a dummy operation back to the Sacado Fad types if you want.  The best solution though would be just to remove this call from Albany.

**Comment by ikalash** [comment]
Thanks @etphipp .  If I remove these calls there are additional problems, unfortunately: 
```
[  4%] Building CXX object src/CMakeFiles/albanyLib.dir/evaluators/utility/PHAL_FieldFrobeniusNorm.cpp.o
In file included from /home/ikalash/nightlyCDash/repos/Albany/src/PHAL_AlbanyTraits.hpp:21,
                 from /home/ikalash/nightlyCDash/repos/Albany/src/evaluators/utility/PHAL_FieldFrobeniusNorm.cpp:7:
/home/ikalash/nightlyCDash/repos/Albany/src/Albany_SacadoTypes.hpp: In instantiation of ‘struct Albany::ScalarConversionHelper<const double, Sacado::Fad::Exp::GeneralFad<Sacado::Fad::Exp::ViewStorage<const double, 0, 1, Sacado::Fad::Exp::GeneralFad<Sacado::Fad::Exp::DynamicStorage<double, double> > > > >’:
/home/ikalash/nightlyCDash/repos/Albany/src/Albany_SacadoTypes.hpp:102:54:   required from ‘ToST Albany::convertScalar(const FromST&) [with ToST = const double; FromST = Sacado::Fad::Exp::GeneralFad<Sacado::Fad::Exp::ViewStorage<const double, 0, 1, Sacado::Fad::Exp::GeneralFad<Sacado::Fad::Exp::DynamicStorage<double, double> > > >]’
/home/ikalash/nightlyCDash/repos/Albany/src/evaluators/utility/PHAL_FieldFrobeniusNorm_Def.hpp:184:58:   required from ‘void PHAL::FieldFrobeniusNormBase<EvalT, Traits, ScalarT>::evaluateFields(typename Traits::EvalData) [with EvalT = PHAL::AlbanyTraits::Jacobian; Traits = PHAL::AlbanyTraits; ScalarT = double; typename Traits::EvalData = PHAL::Workset&]’
/home/ikalash/nightlyCDash/repos/Albany/src/evaluators/utility/PHAL_FieldFrobeniusNorm.cpp:12:1:   required from here
/home/ikalash/nightlyCDash/repos/Albany/src/Albany_SacadoTypes.hpp:84:5: error: no type named ‘type’ in ‘struct std::enable_if<false, const double>’
   84 |     apply (const FromST& x)
      |     ^~~~~
```
Here is the problematic line in Albany: https://github.com/SNLComputation/Albany/blob/master/src/evaluators/utility/PHAL_FieldFrobeniusNorm_Def.hpp#L184 .  I'm not sure what is the issue - can you please advise?

**Comment by etphipp** [comment]
Hmm, looks like a Sacado traits specialization is missing.  I'll look into it.  If this his holding anyone one up, they can go back to the old Sacado design by configuring Trilinos with

-D Sacado_NEW_FAD_DESIGN_IS_DEFAULT:BOOL=OFF \

**Comment by ikalash** [comment]
Thanks, Eric.  I'll try this option to suppress the errors for now.  Please let me know what you find as you investigate the missing specialization.  I can provide instructions for how to build Albany to reproduce the issue, if this would be helpful.

**Comment by etphipp** [comment]
I think I've sorted out what is going on.  Apparently I made a subtle change between the old and new designs with regards to the "scalar type" for Fad types, when the inner type is const, e.g, `Sacado::Fad::DFad<const double>`.  Previously with the old design, we would have
```
typename Sacado::ScalarType< Sacado::Fad::DFad<const double> >::type == const double
```
but now with the new design we have
```
typename Sacado::ScalarType< Sacado::Fad::DFad<const double> >::type == double
```
The problem arises because `Albany::ScalarConversionHelper<ToST, FromST>` has a partial specialization for `ToST == Sacado::ScalarType<FromST>::type`, which no longer matches in this case.  One way to work around this would be to modify the specialization and add another one like so:
```
template<typename FromST>
struct ScalarConversionHelper<typename std::remove_cv< typename Sacado::ScalarType<FromST>::type >::type,FromST>
{
  static typename Sacado::ScalarType<FromST>::type apply (const FromST& x)
  {
    return ADValue(x);
  }
};

template<typename FromST>
struct ScalarConversionHelper<const typename std::remove_cv< typename Sacado::ScalarType<FromST>::type >::type,FromST>
{
  static typename Sacado::ScalarType<FromST>::type apply (const FromST& x)
  {
    return ADValue(x);
  }
};
```
That appears to work with both the old and new designs.

However I'm not really sure if this was a good choice on my part or not.  I think making `ScalarType<Fad>::type` never const makes many things a lot easier, but Sacado is not consistent about this.  I am considering changing the behavior of the new design to match the old where `ScalarType<DFad<const double> > == const double`.

**Comment by etphipp** [comment]
I went ahead and added a PR that should fix this by restoring the previous behavior with regards to `ScalarType<ViewFad<const T,...> >`.  I also put `setUpdateValue` back in as well.  Hopefully with this PR, no changes to Albany will be required.

**Comment by ikalash** [comment]
I have confirmed that the relevant PR has fixed this issue.  Closing.
