### ISSUE TITLE
Belos: FPEs in Albany/LCM tests

### ISSUE THREAD

**Issue by ikalash** [trilinos/Trilinos#7451]
A number of FPEs started showing up in some Albany/LCM tests on 5/20.

The changes are deep within Belos and appear related to changes made to Belos not long ago (b/w 5/6-5/20 - last successful run was on 5/6, and the tests did not run b/w 5/6-5/20 unfortunately).  The output from the failures can be found here:
https://sems-cdash-son.sandia.gov/cdash/viewTest.php?onlyfailed&buildid=2177

No changes were made to Albany/LCM when these issues started, so they are due to changes to Trilinos.  Can someone please have a look?

@trilinos/belos 

Tagging @lxmota , the owner of Albany/LCM.

**Comment by cgcgcg** [comment]
@ikalash EMPIRE saw some FPEs with PR #7366, but we're not sure whether that was just an issue in EMPIRE exposed by the change from DKGS to ICGS in Belos. Any chance you could revert that PR an check if that fixes things?

**Comment by ikalash** [comment]
Indeed reverting that PR makes the FPEs go away.

**Comment by jennloe** [comment]
@hkthorn and I are looking into this.

**Comment by jhux2** [comment]
@bathmatt 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by cgcgcg** [comment]
@ikalash Can this issue be closed?

**Comment by ikalash** [comment]
@cgcgcg : I don't know.  The owner of the machines (@lxmota) where these failures were happening is on vacation this week and there are other errors plaguing those builds.  Can you please keep this open until we've had a chance to verify that the failures are indeed resolved (next week)?

**Comment by cgcgcg** [comment]
@ikalash Of course!

**Comment by ikalash** [comment]
Thanks for understanding.  Sorry about the delay!

**Comment by lxmota** [comment]
These FPE errors have been resolved.
