### ISSUE TITLE
Tpetra: FECrsGraph wrong default domain map?

### ISSUE THREAD

**Issue by bartgol** [trilinos/Trilinos#7455]
## Question
@trilinos/Tpetra

I am not sure if this is a bug, so I'm posting it under 'questions', but I have the feeling it is either wrong or counterintuitive.

One can create a FECrsGraph passing only ownedRowMap and ownedPlusSharedRowMap (the domain and column maps being defaulted to null). In this case, FECrsGraph sets the domain map to the ownedRowMap, even if the graph is in FE_ACTIVE_OWNED_PLUS_SHARED state.

This cause the (overlapped) graph to potentially (and, in practice, I do observe it) have a domain map which is not locally fitted to the column map. This is usually not the case in a crs graph, and took me a while to figure out it's not the case for the FECrsGraph (when in owned+shared mode).

So the question is probably two faced:

1) In a CrsGraph, is it usually desired (and safe to assume) that colMap_->isLocallyFitted(domainMap_) returns true? My assumption was "yes", cause it helps in import/export operations. At the very least, isn't it desirable (and even safe to assume) in the case where the column map is internally generated by Tpetra (rather than passed in by the user)?
2) Assuming the answer to 1 is "yes" (or 'no', but 'yes' to the 'at least' clause), is there a reason not to keep this behavior for the overlapped FECrsGraph?

Note: assuming 1=yes, 2=no, we could restore this symmetry by simply setting domaniMap_ to ownedPlusSharedRowMap in case the input domain map is null.

**Comment by cgcgcg** [comment]
@trilinos/tpetra

**Comment by bartgol** [comment]
Bumping this, in case it got lost in the github feedback.

Any thoughts, comments?

**Comment by kddevin** [comment]
@csiefer2 Do you have time to look at this question?

**Comment by bartgol** [comment]
I gave it some more thought, and I'm more convinced that the current behavior of the FECrs graph is not optimal. Here's an argument:

When doing FE assembly, one has probably access to the ownedPlusShared map of its dofs, not necessarily the column map of the crs matrix. One may then use this map to convert the FE dofs GIDs to LIDs, for the assembly of the local matrix. However, in order for this to work correctly, the owned+shared dofs need to appear *in the same position* as they appear in the col map of the matrix.

If the FECrs matrix is built with domain map equal to the owned dofs only (as it is now), the col map will put the shared dof mixed up with the 'borrowed dofs' (I don't know how to call the dofs that are in the col map but not in the owned+shared). If, on the other hand, the domain map for the FECrs graph is the owned+shared one, then Tpetra will guarantee (when calling makeColMap) that the owned+shared domain map will be locally fitter in the graph col map.

All this makes sense in my head, but I might not be great at wording it. If, however, I managed to make myself clear, and you agree, I can put up a quick PR with a fix (I already have it locally).

**Comment by csiefer2** [comment]
@mperego requested something similar a while back for Albany.

I suspect the reason why we had the ownedPlusShared domainMap match the owned domainMap was to ensure Aztec ordering of the column maps.  

I know there's tons of code in the Epetra matrix-matrix product that assumes Aztec ordering.  I don't know how much of that @DrBooom copied into Tpetra.  There's a chance that MueLu will break if used on an FECrsMatrix _and we do not have tests of MueLu on Tpetra::FECrsMatrix_.

So if you want to put up a PR, go nuts, but be sure to add a test to MueLu that exercises this.

**Comment by bartgol** [comment]
Uhm, the thing is, if I build the overlapped matrix and owned matrix separatedly (the former has an owned+shared row map, the latter an owned only row map), do the assembly in the overlapped one, then export to the owned, I get the correct behavior. That is because the domain map of the overlapped matrix (the owned+shared) will be locally fitted to the col map.

I would expect that using a FECrs would yield a matrix that, while in FE fill mode, behaves exactly the same as the good old matrix build with owned+shared row map. This does not seem to be the case.

@csiefer2  Are you saying that it is expected (or desired?) that a FECrs in fill mode does not have the same col map as a Crs built with the owned+shared map (for both domain and range)?

**Comment by csiefer2** [comment]
A CrsGraph using ownedMap as the domain map will not have the the column map in the same order as a CrsGraph built using the ownedPlusSharedMap as the domain map.

FECrsGraph is no different in that regard.

**Comment by bartgol** [comment]
That's ok, I'm not puzzled by that. All I was trying to say is that CrsGraph, if built passing only rowMap and then fill completed without args (square matrix), will set domainMap=rowMap. FECrs does not do that for the owned+shared graph: the domain map, if not passed (null), is set to the owned gids only.

Sure, I can make sure I pass the domain map too, and that should fix the maps inconsistencies inside my app. But it felt a bit counterintuitive that FECrs picked a different default domain map (for the owned+shared graph) than what Crs would do.

**Comment by bartgol** [comment]
This has been fixed by #7572
