### ISSUE TITLE
override warnings in panzer

### ISSUE THREAD

**Issue by bathmatt** [trilinos/Trilinos#746]
@rppawlo @eric-c-cyr Do we want to fix these by adding overrides to all the model evaluator calls

In file included from /Users/mbetten/Trilinos/mini-PIC/src/main.cpp:69:
/Users/mbetten/installs/install-for-panzer/clang-DEBUG/include/Panzer_ModelEvaluator.hpp:131:68: warning: 'get_W_factory' overrides a member
      function but is not marked 'override' [-Winconsistent-missing-override]
  Teuchos::RCP<const Thyra::LinearOpWithSolveFactoryBase<Scalar> > get_W_factory() const;

**Comment by jmgate** [comment]
Did a quick search on this warning and it sounds like <a href="clang.llvm.org/extra/clang-tidy">clang-tidy</a> might be of some help in automating the fix, though I've never used it.

**Comment by rppawlo** [comment]
We should definitely do this. What compiler version is giving this warning?

**Comment by bathmatt** [comment]
clang on the mac,

s1000670:include mbetten$ clang++  --version

Apple LLVM version 7.3.0 (clang-703.0.31)

Target: x86_64-apple-darwin15.6.0

**Comment by bathmatt** [comment]
So, I looked at this a bit, it seems that we can automate the fixing with
clang-tidy.  There are some issues, but we need to make a cmake output file
and use it as input to clang-tidy.  I don't want to have everyone looking
into this, so should we assign it to one of us>

**Comment by bathmatt** [comment]
ok, it looks like it's sorta working, let me fix this

On Mon, Oct 31, 2016 at 10:16 AM, Matt Bettencourt <dr.bettencourt@gmail.com
> wrote:

> So, I looked at this a bit, it seems that we can automate the fixing with
> clang-tidy.  There are some issues, but we need to make a cmake output file
> and use it as input to clang-tidy.  I don't want to have everyone looking
> into this, so should we assign it to one of us>
>
> On Mon, Oct 31, 2016 at 9:14 AM, Matt Bettencourt <

**Comment by bathmatt** [comment]
So, the auto-fix doesn't seem to do its thing for override.  Not sure why.


dir-evaluators (clang) 119 $ clang-tidy -fix-errors
Panzer_Integrator_BasisTimesVector.cpp
-checks='clang-analyzer-*,-clang-analyzer-alpha*,cppcoreguidelines-*,modernize-use-override'
-p ~/builds/build_for_panzer/clang/tidy/

8 warnings generated.

*/home/mbetten/Trilinos/Trilinos/packages/panzer/disc-fe/src/evaluators/Panzer_Integrator_BasisTimesVector_impl.hpp:78:9:
**warning: **'addDependentField<Sacado::Fad::DFad<double>, panzer::Cell,
panzer::IP, panzer::Dim, void, void, void, void, void>' is deprecated
[clang-diagnostic-deprecated-declarations]*

  this->addDependentField(vectorField);

 */home/mbetten/Trilinos/Trilinos/packages/panzer/disc-fe/src/evaluators/Panzer_Integrator_BasisTimesVector.cpp:52:49:
note: *in instantiation of member function
'panzer::Integrator_BasisTimesVector<panzer::Traits::Tangent,
panzer::Traits>::Integrator_BasisTimesVector' requested here

PANZER_INSTANTIATE_TEMPLATE_CLASS_TWO_T(panzer::Integrator_BasisTimesVector)

*                                                ^*

*/home/mbetten/Trilinos/Trilinos/packages/panzer/disc-fe/src/Panzer_ExplicitTemplateInstantiation.hpp:90:51:
note: *expanded from macro 'PANZER_INSTANTIATE_TEMPLATE_CLASS_TWO_T'

  PANZER_INSTANTIATE_TEMPLATE_CLASS_TANGENT_TWO_T(name) \

*                                                  ^*

*/home/mbetten/Trilinos/Trilinos/packages/panzer/disc-fe/src/Panzer_ExplicitTemplateInstantiation.hpp:76:18:
note: *expanded from macro 'PANZER_INSTANTIATE_TEMPLATE_CLASS_TANGENT_TWO_T'

  template class name<panzer::Traits::Tangent, panzer::Traits>;

*                 ^*

*/home/mbetten/Trilinos/Trilinos/packages/phalanx/src/Phalanx_Evaluator_WithBaseImpl.hpp:115:10:
note: *'addDependentField<Sacado::Fad::DFad<double>, panzer::Cell,
panzer::IP, panzer::Dim, void, void, void, void, void>' has been explicitly
marked deprecated here

    void addDependentField(const PHX::MDField<DataT,Tag0,Tag1,Tag2,Tag3,

*         ^*

*/home/mbetten/Trilinos/Trilinos/packages/panzer/disc-fe/src/evaluators/Panzer_Integrator_BasisTimesVector_impl.hpp:78:9:
**warning: **'addDependentField<double, panzer::Cell, panzer::IP,
panzer::Dim, void, void, void, void, void>' is deprecated
[clang-diagnostic-deprecated-declarations]*

  this->addDependentField(vectorField);

*        ^*

*/home/mbetten/Trilinos/Trilinos/packages/panzer/disc-fe/src/evaluators/Panzer_Integrator_BasisTimesVector.cpp:52:49:
note: *in instantiation of member function
'panzer::Integrator_BasisTimesVector<panzer::Traits::Residual,
panzer::Traits>::Integrator_BasisTimesVector' requested here

PANZER_INSTANTIATE_TEMPLATE_CLASS_TWO_T(panzer::Integrator_BasisTimesVector)

*                                                ^*

*/home/mbetten/Trilinos/Trilinos/packages/panzer/disc-fe/src/Panzer_ExplicitTemplateInstantiation.hpp:89:52:
note: *expanded from macro 'PANZER_INSTANTIATE_TEMPLATE_CLASS_TWO_T'

  PANZER_INSTANTIATE_TEMPLATE_CLASS_RESIDUAL_TWO_T(name) \

*                                                   ^*

*/home/mbetten/Trilinos/Trilinos/packages/panzer/disc-fe/src/Panzer_ExplicitTemplateInstantiation.hpp:73:18:
note: *expanded from macro
'PANZER_INSTANTIATE_TEMPLATE_CLASS_RESIDUAL_TWO_T'

  template class name<panzer::Traits::Residual, panzer::Traits>;

*                 ^*

*/home/mbetten/Trilinos/Trilinos/packages/phalanx/src/Phalanx_Evaluator_WithBaseImpl.hpp:115:10:
note: *'addDependentField<double, panzer::Cell, panzer::IP, panzer::Dim,
void, void, void, void, void>' has been explicitly marked deprecated here

    void addDependentField(const PHX::MDField<DataT,Tag0,Tag1,Tag2,Tag3,

*         ^*

*/home/mbetten/Trilinos/Trilinos/packages/phalanx/src/Phalanx_Evaluator_WithBaseImpl.hpp:126:18:
**warning: **'postRegistrationSetup' overrides a member function but is not
marked 'override' [clang-diagnostic-inconsistent-missing-override]*

    virtual void postRegistrationSetup(typename Traits::SetupData d,

*                 ^*

*/home/mbetten/Trilinos/Trilinos/packages/panzer/disc-fe/src/evaluators/Panzer_Evaluator_WithBaseImpl.hpp:53:38:
note: *in instantiation of template class
'PHX::EvaluatorWithBaseImpl<panzer::Traits>' requested here

class EvaluatorWithBaseImpl : public PHX::EvaluatorWithBaseImpl<TRAITS> {

*                                     ^*

*/home/mbetten/Trilinos/Trilinos/packages/panzer/disc-fe/src/evaluators/Panzer_Integrator_BasisTimesVector_decl.hpp:56:1:
note: *in instantiation of template class
'panzer::EvaluatorWithBaseImpl<panzer::Traits>' requested here

PANZER_EVALUATOR_CLASS(Integrator_BasisTimesVector)

*^*

*/home/mbetten/Trilinos/Trilinos/packages/panzer/disc-fe/src/evaluators/Panzer_Evaluator_Macros.hpp:53:23:
note: *expanded from macro 'PANZER_EVALUATOR_CLASS'

  class NAME : public panzer::EvaluatorWithBaseImpl<Traits>,            \

*                      ^*

*/home/mbetten/Trilinos/Trilinos/packages/panzer/disc-fe/src/evaluators/Panzer_Integrator_BasisTimesVector.cpp:52:49:
note: *in instantiation of template class
'panzer::Integrator_BasisTimesVector<panzer::Traits::Residual,
panzer::Traits>' requested here

PANZER_INSTANTIATE_TEMPLATE_CLASS_TWO_T(panzer::Integrator_BasisTimesVector)

*                                                ^*

*/home/mbetten/Trilinos/Trilinos/packages/panzer/disc-fe/src/Panzer_ExplicitTemplateInstantiation.hpp:89:52:
note: *expanded from macro 'PANZER_INSTANTIATE_TEMPLATE_CLASS_TWO_T'

  PANZER_INSTANTIATE_TEMPLATE_CLASS_RESIDUAL_TWO_T(name) \

*                                                   ^*

*/home/mbetten/Trilinos/Trilinos/packages/panzer/disc-fe/src/Panzer_ExplicitTemplateInstantiation.hpp:73:18:
note: *expanded from macro
'PANZER_INSTANTIATE_TEMPLATE_CLASS_RESIDUAL_TWO_T'

  template class name<panzer::Traits::Residual, panzer::Traits>;

*                 ^*

*/home/mbetten/Trilinos/Trilinos/packages/phalanx/src/Phalanx_Evaluator.hpp:97:18:
note: *overridden virtual function is here

    virtual void postRegistrationSetup(typename Traits::SetupData d,

*                 ^*

Suppressed 4 warnings (4 in non-user code).

Use -header-filter='.*' to display errors from all non-system headers.

dir-evaluators (clang) 120 $ git s

# On branch develop

nothing to commit (use -u to show untracked files)

dir-evaluators (clang) 121 $


On Mon, Oct 31, 2016 at 10:37 AM, Matt Bettencourt <dr.bettencourt@gmail.com
> wrote:

> ok, it looks like it's sorta working, let me fix this
>
> On Mon, Oct 31, 2016 at 10:16 AM, Matt Bettencourt <

**Comment by bathmatt** [comment]
So, i've confirmed that the -fix-errors does not help with deprecated and
override, not sure on the second one why, but the first makes sense.  I'm
running panzer through the analysis anyways. but I don't expect much to
come of this.

I'm using 3.9.0 clang as well,

On Mon, Oct 31, 2016 at 10:52 AM, Matt Bettencourt <dr.bettencourt@gmail.com
> wrote:

> So, the auto-fix doesn't seem to do its thing for override.  Not sure why.
>
>
> dir-evaluators (clang) 119 $ clang-tidy -fix-errors Panzer_Integrator_BasisTimesVector.cpp
> -checks='clang-analyzer-*,-clang-analyzer-alpha*,
> cppcoreguidelines-*,modernize-use-override' -p ~/builds/build_for_panzer/clang/tidy/
>
>
> 8 warnings generated.
>
> */home/mbetten/Trilinos/Trilinos/packages/panzer/disc-fe/src/evaluators/Panzer_Integrator_BasisTimesVector_impl.hpp:78:9:
> **warning: **'addDependentField<Sacado::Fad::DFad<double>, panzer::Cell,
> panzer::IP, panzer::Dim, void, void, void, void, void>' is deprecated
> [clang-diagnostic-deprecated-declarations]*
>
>   this->addDependentField(vectorField);
>
>  */home/mbetten/Trilinos/Trilinos/packages/panzer/disc-fe/src/evaluators/Panzer_Integrator_BasisTimesVector.cpp:52:49:
> note: *in instantiation of member function 'panzer::Integrator_
> BasisTimesVector<panzer::Traits::Tangent, panzer::Traits>::Integrator_BasisTimesVector'
> requested here
>
> PANZER_INSTANTIATE_TEMPLATE_CLASS_TWO_T(panzer::
> Integrator_BasisTimesVector)
>
> *                                                ^*
>
> */home/mbetten/Trilinos/Trilinos/packages/panzer/disc-fe/src/Panzer_ExplicitTemplateInstantiation.hpp:90:51:
> note: *expanded from macro 'PANZER_INSTANTIATE_TEMPLATE_CLASS_TWO_T'
>
>   PANZER_INSTANTIATE_TEMPLATE_CLASS_TANGENT_TWO_T(name) \
>
> *                                                  ^*
>
> */home/mbetten/Trilinos/Trilinos/packages/panzer/disc-fe/src/Panzer_ExplicitTemplateInstantiation.hpp:76:18:
> note: *expanded from macro 'PANZER_INSTANTIATE_TEMPLATE_
> CLASS_TANGENT_TWO_T'
>
>   template class name<panzer::Traits::Tangent, panzer::Traits>;
>
> *                 ^*
>
> */home/mbetten/Trilinos/Trilinos/packages/phalanx/src/Phalanx_Evaluator_WithBaseImpl.hpp:115:10:
> note: *'addDependentField<Sacado::Fad::DFad<double>, panzer::Cell,
> panzer::IP, panzer::Dim, void, void, void, void, void>' has been explicitly
> marked deprecated here
>
>     void addDependentField(const PHX::MDField<DataT,Tag0,Tag1,Tag2,Tag3,
>
> *         ^*
>
> */home/mbetten/Trilinos/Trilinos/packages/panzer/disc-fe/src/evaluators/Panzer_Integrator_BasisTimesVector_impl.hpp:78:9:
> **warning: **'addDependentField<double, panzer::Cell, panzer::IP,
> panzer::Dim, void, void, void, void, void>' is deprecated
> [clang-diagnostic-deprecated-declarations]*
>
>   this->addDependentField(vectorField);
>
> *        ^*
>
> */home/mbetten/Trilinos/Trilinos/packages/panzer/disc-fe/src/evaluators/Panzer_Integrator_BasisTimesVector.cpp:52:49:
> note: *in instantiation of member function 'panzer::Integrator_
> BasisTimesVector<panzer::Traits::Residual, panzer::Traits>::Integrator_BasisTimesVector'
> requested here
>
> PANZER_INSTANTIATE_TEMPLATE_CLASS_TWO_T(panzer::
> Integrator_BasisTimesVector)
>
> *                                                ^*
>
> */home/mbetten/Trilinos/Trilinos/packages/panzer/disc-fe/src/Panzer_ExplicitTemplateInstantiation.hpp:89:52:
> note: *expanded from macro 'PANZER_INSTANTIATE_TEMPLATE_CLASS_TWO_T'
>
>   PANZER_INSTANTIATE_TEMPLATE_CLASS_RESIDUAL_TWO_T(name) \
>
> *                                                   ^*
>
> */home/mbetten/Trilinos/Trilinos/packages/panzer/disc-fe/src/Panzer_ExplicitTemplateInstantiation.hpp:73:18:
> note: *expanded from macro 'PANZER_INSTANTIATE_TEMPLATE_
> CLASS_RESIDUAL_TWO_T'
>
>   template class name<panzer::Traits::Residual, panzer::Traits>;
>
> *                 ^*
>
> */home/mbetten/Trilinos/Trilinos/packages/phalanx/src/Phalanx_Evaluator_WithBaseImpl.hpp:115:10:
> note: *'addDependentField<double, panzer::Cell, panzer::IP, panzer::Dim,
> void, void, void, void, void>' has been explicitly marked deprecated here
>
>     void addDependentField(const PHX::MDField<DataT,Tag0,Tag1,Tag2,Tag3,
>
> *         ^*
>
> */home/mbetten/Trilinos/Trilinos/packages/phalanx/src/Phalanx_Evaluator_WithBaseImpl.hpp:126:18:
> **warning: **'postRegistrationSetup' overrides a member function but is
> not marked 'override' [clang-diagnostic-inconsistent-missing-override]*
>
>     virtual void postRegistrationSetup(typename Traits::SetupData d,
>
> *                 ^*
>
> */home/mbetten/Trilinos/Trilinos/packages/panzer/disc-fe/src/evaluators/Panzer_Evaluator_WithBaseImpl.hpp:53:38:
> note: *in instantiation of template class 'PHX::EvaluatorWithBaseImpl<panzer::Traits>'
> requested here
>
> class EvaluatorWithBaseImpl : public PHX::EvaluatorWithBaseImpl<TRAITS> {
>
> *                                     ^*
>
> */home/mbetten/Trilinos/Trilinos/packages/panzer/disc-fe/src/evaluators/Panzer_Integrator_BasisTimesVector_decl.hpp:56:1:
> note: *in instantiation of template class 'panzer::
> EvaluatorWithBaseImpl<panzer::Traits>' requested here
>
> PANZER_EVALUATOR_CLASS(Integrator_BasisTimesVector)
>
> *^*
>
> */home/mbetten/Trilinos/Trilinos/packages/panzer/disc-fe/src/evaluators/Panzer_Evaluator_Macros.hpp:53:23:
> note: *expanded from macro 'PANZER_EVALUATOR_CLASS'
>
>   class NAME : public panzer::EvaluatorWithBaseImpl<Traits>,            \
>
> *                      ^*
>
> */home/mbetten/Trilinos/Trilinos/packages/panzer/disc-fe/src/evaluators/Panzer_Integrator_BasisTimesVector.cpp:52:49:
> note: *in instantiation of template class 'panzer::Integrator_
> BasisTimesVector<panzer::Traits::Residual, panzer::Traits>' requested here
>
> PANZER_INSTANTIATE_TEMPLATE_CLASS_TWO_T(panzer::
> Integrator_BasisTimesVector)
>
> *                                                ^*
>
> */home/mbetten/Trilinos/Trilinos/packages/panzer/disc-fe/src/Panzer_ExplicitTemplateInstantiation.hpp:89:52:
> note: *expanded from macro 'PANZER_INSTANTIATE_TEMPLATE_CLASS_TWO_T'
>
>   PANZER_INSTANTIATE_TEMPLATE_CLASS_RESIDUAL_TWO_T(name) \
>
> *                                                   ^*
>
> */home/mbetten/Trilinos/Trilinos/packages/panzer/disc-fe/src/Panzer_ExplicitTemplateInstantiation.hpp:73:18:
> note: *expanded from macro 'PANZER_INSTANTIATE_TEMPLATE_
> CLASS_RESIDUAL_TWO_T'
>
>   template class name<panzer::Traits::Residual, panzer::Traits>;
>
> *                 ^*
>
> */home/mbetten/Trilinos/Trilinos/packages/phalanx/src/Phalanx_Evaluator.hpp:97:18:
> note: *overridden virtual function is here
>
>     virtual void postRegistrationSetup(typename Traits::SetupData d,
>
> *                 ^*
>
> Suppressed 4 warnings (4 in non-user code).
>
> Use -header-filter='.*' to display errors from all non-system headers.
>
> dir-evaluators (clang) 120 $ git s
>
> # On branch develop
>
> nothing to commit (use -u to show untracked files)
>
> dir-evaluators (clang) 121 $
>
>
> On Mon, Oct 31, 2016 at 10:37 AM, Matt Bettencourt <

**Comment by bathmatt** [comment]
OK, so all the changes I see are like this


I don't even know why it is saying you need to add {}

Ideas?

--- a/packages/panzer/disc-fe/src/Panzer_BasisIRLayout.hpp

+++ b/packages/panzer/disc-fe/src/Panzer_BasisIRLayout.hpp

@@ -129,9 +129,9 @@ namespace panzer {



   private:

     std::string basis_name_;

-    int num_cells_;

-    int num_points_;

-    int dimension_;

+    int num_cells_{}{};

+    int num_points_{}{};

+    int dimension_{}{};

On Mon, Oct 31, 2016 at 11:48 AM, Matt Bettencourt <dr.bettencourt@gmail.com
> wrote:

> So, i've confirmed that the -fix-errors does not help with deprecated and
> override, not sure on the second one why, but the first makes sense.  I'm
> running panzer through the analysis anyways. but I don't expect much to
> come of this.
>
> I'm using 3.9.0 clang as well,
>
> On Mon, Oct 31, 2016 at 10:52 AM, Matt Bettencourt <
