### ISSUE TITLE
TriKota: Build errors with Dakota 6.12 and newer

### ISSUE THREAD

**Issue by rhoope** [trilinos/Trilinos#7466]
## Bug Report
@trilinos/trikota , @trilinos/rol

### Description
Trilinos currently won't build when TriKota is enabled.  Additional compile-time errors occur when ROL is also enabled.  Dakota now has a required dependence on both.

### Definition of Done
Enabling TriKota and ROL should build and test with Dakota 6.12 or newer.

### Steps to Reproduce
Clone Trilinos, checkout master, place Dakota in trilinos/packages/TriKota/Dakota. Apply the attached patch file to Dakota (`cd trilinos/packages/TriKota/Dakota; patch -p0 < dakota-6.12.txt`). Configure Trilinos with TriKota and ROL enabled, get build error at make time.

1. SHA1:  Trilinos master at 442a24ba
1. Configure script:
```
cmake3 \
  -D CMAKE_BUILD_TYPE=RELEASE \
  -D CMAKE_INSTALL_PREFIX=./install \
  -D BUILD_SHARED_LIBS:BOOL=TRUE \
  -D Trilinos_ENABLE_TESTS:BOOL=ON \
  -D Trilinos_ENABLE_Teuchos:BOOL=ON \
  -D Trilinos_ENABLE_TriKota:BOOL=ON \
  -D Trilinos_ENABLE_ROL:BOOL=ON \
  -D Trilinos_ENABLE_ALL_PACKAGES:BOOL=OFF \
  -D Trilinos_ENABLE_ALL_FORWARD_DEP_PACKAGES:BOOL=OFF \
  -D Trilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=OFF \
  -D Trilinos_ENABLE_COMPLEX_DOUBLE:BOOL=ON \
  ~/Projects/Trilinos
```

**Comment by rhoope** [comment]
@briadam FYI.

**Comment by rhoope** [comment]
I can't add labels but would add "pkg:TriKota" if so.

**Comment by rhoope** [comment]
Here is the patch file for reproducing the steps above:

[dakota-6.12.txt](https://github.com/trilinos/Trilinos/files/4720079/dakota-6.12.txt)

**Comment by jhux2** [comment]
@trilinos/rol
