### ISSUE TITLE
Amesos2_Basker_UnitTests with ShyLU Basker and Threads > 1 Failed

### ISSUE THREAD

**Issue by ndellingwood** [trilinos/Trilinos#747]
@ndellingwood
This test failed when using gcc version 5.4 and OpenMP build. 

```
    Start 2: Amesos2_Basker_UnitTests
2/3 Test #2: Amesos2_Basker_UnitTests ..........***Failed  Required regular expression not found.Regex=[End Result: TEST PASSED
]  0.02 sec
```

Relevant output line with more verbose output:
`Basker_double_int_LongInt_Solve_UnitTest ... "Tpetra::MultiVector":`

**Comment by srajama1** [comment]
Checking to see if this is still failing.
