### ISSUE TITLE
Support CUDA-10.1 on SEMS-RHEL7

### ISSUE THREAD

**Issue by jmgate** [trilinos/Trilinos#7471]
## Question
@bartlettroscoe, @e10harvey, I'm not sure when the sems-cuda/10.1 module was released on RHEL7 machines, but would it be possible to add that as a supported build in `cmake/std/atdm/sems-rhel7`?  I can create the PR&mdash;just didn't know if there was a reason it wasn't supported.

CC:  @eric-c-cyr

**Comment by bartlettroscoe** [comment]
> I can create the PR—just didn't know if there was a reason it wasn't supported.

@jmgate, yes, please just post a PR.

Does EMPIRE also need matching ATDM Trilinos nightly builds to support this build?

**Comment by jmgate** [comment]
@eric-c-cyr, did you wind up changing your Trilinos locally to enable 10.1?  If so, are you able to push a branch for this?  If not, I can eventually&mdash;just juggling too many flaming batons at the moment.

**Comment by eric-c-cyr** [comment]
I did not. I started to, but than @rppawlo had already built it

**Comment by jmgate** [comment]
Actually it sounds like this isn't high priority.  Closing.
