### ISSUE TITLE
Seacas: multiple definition of exodus_unused_symbol_dummy_1

### ISSUE THREAD

**Issue by MarDiehl** [trilinos/Trilinos#7480]
## Bug Report
@trilinos/seacas

### Description
Compilation with GCC 10.1 fails due to the repeated definition of `exodus_unused_symbol_dummy_1`.
It is defined twice, in `ex_create_par` and `ex_open_par.c`. The fix is straight forward: Either guard with `#ifndef` or rename to `exodus_unused_symbol_dummy_create` and `exodus_unused_symbol_dummy_open`. The best solution would be to remove the else branch completely and figure out if there are still `ranlib` versions around that have problems with empty object files.

**Comment by gsjaardema** [comment]
I will make the symbol unique.  There are still ranlib versions that are in use by major code projects which issue warnings about empty object files.

**Comment by gsjaardema** [comment]
Actually, looking at the current source code, the `dummy1` symbols were made unique as of commit d9e90334e1 on January 28th.

**Comment by MarDiehl** [comment]
> Actually, looking at the current source code, the `dummy1` symbols were made unique as of commit d9e90334e1 on January 28th.

sorry for the false alarm, I'm using the release version ad did not check the development version

**Comment by gsjaardema** [comment]
Just FYI -- The current SEACAS repository (https://github.com/gsjaardema/seacas) has recent commits that remove all warnings/errors for gcc-10 builds.  These changes have not yet been synched over to Trilinos, so you will probably get warnings/errors if you try to build Trilinos/SEACAS using gcc-10.X.  I will hopefully sync next week...

**Comment by MarDiehl** [comment]
@gsjaardema: Many thanks, good to hear.
