### ISSUE TITLE
Build error PyTrilinos - Unable to find 'Teuchos_dox.i'

### ISSUE THREAD

**Issue by cbcoutinho** [trilinos/Trilinos#749]
I am trying to build the latest release from the Trilinos repo - namely trilinos-release-12-8-1 - on my openSUSE Tumbleweed machine
- Linux kernel 4.8.4-1-default
- GNOME Shell 3.22.1

I created a build directory inside the source directory and used the following cmake command:

```
cmake \
-DTPL_ENABLE_MPI:BOOL=ON \
-DTrilinos_ENABLE_ALL_PACKAGES:BOOL=ON \
-DTPL_ENABLE_Matio:BOOL=OFF \
-DBUILD_SHARED_LIBS=ON \
-DTrilinos_ENABLE_EXPLICIT_INSTANTIATION=ON \
-DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python2.7 \
-DPYTHON_INCLUDE_DIR:PATH=/usr/include/python2.7 \
-DPYTHON_LIBRARY:FILEPATH=/usr/lib64/libpython2.7.so ../
```

Python3 is the default python version on my system, that's why I had to explicitly state where the python-related files are...

I attempted to build the project using make:

`make -j4 2>&1 | tee make.txt`

And got an error at around the 88% mark when building pytrilinos:

```
[ 88%] Swig source /home/chris/Software/Trilinos/packages/PyTrilinos/src/LOCA.Epetra.Interface.i
/home/chris/Software/Trilinos/packages/PyTrilinos/src/Teuchos.i:138: Error: Unable to find 'Teuchos_dox.i'
/home/chris/Software/Trilinos/packages/PyTrilinos/src/LOCA.Epetra.Interface.i:147: Error: Unable to find 'LOCA_dox.i'
/home/chris/Software/Trilinos/packages/PyTrilinos/src/NOX.Epetra.Interface.i:129: Error: Unable to find 'NOX_dox.i'
/home/chris/Software/Trilinos/packages/PyTrilinos/src/Epetra.i:260: Error: Unable to find 'Epetra_dox.i'
make[2]: *** [packages/PyTrilinos/src/CMakeFiles/PyTrilinos_LOCA_Epetra_Interface.dir/build.make:62: packages/PyTrilinos/src/LOCA.Epetra.InterfacePYTHON_wrap.cpp] Error 1
make[1]: *** [CMakeFiles/Makefile2:22478: packages/PyTrilinos/src/CMakeFiles/PyTrilinos_LOCA_Epetra_Interface.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

Here is a copy of the make.txt output generated when attempting to build Trilinos on my system
[make.txt](https://github.com/trilinos/Trilinos/files/559930/make.txt)

I would appreciate any help you could offer

**Comment by wfspotz** [comment]
I suspect that if you remove `CMakeCache.txt` and `CMakeFiles/` that this will go away.

If not, try

    `-D PyTrilinos_DOCSTRINGS:BOOL=OFF `

when invoking `cmake`.

**Comment by cbcoutinho** [comment]
Howdy @wfspotz, thanks for the tip. That solved the problem. Ciao!
