### ISSUE TITLE
ShyLU:  shylu_node/basker bug fix

### ISSUE THREAD

**Issue by LennartSchu** [trilinos/Trilinos#7492]
## Bugfix
@trilinos/shylu

Hello,
I'm not sure if you still work on the Basker solver in ShyLU, however, as it seems there is a minor error in the implementation. 
I've been comparing different LU factorization methods such as Basker for large sparse matrices, and in some cases, an segmentation fault occures in the *mwm_heap_extract_reheap2* function in the *packages/shylu/shylu_node/basker/src/mwm2.hpp* file.
This file seems to be a re-implementation of a FORTRAN-library called MC64. Looking at this library, and different C-Implementations, such as in NICSLU, it seems that there's a simple error in Line 337, where the variable **qlen** is compared to pos0. This is different to both the original and NICSLU, where pos0 is compared to **qlen-1**.
Changing this line accordingly in Basker solves the problem and Matrices are factorized correctly.

i.e.
```
if(qlen == pos0)
    {
      qlen--;
      return;
    }
```
has to be changed to
```
if(qlen-1 == pos0)
    {
      qlen--;
      return;
    }
```

I'm asking you to look into this (if you have the time) and fix the issue. I'm not entirely sure if my fix is correct, I basically just copied it from the NICSLU-version of mc64, which was created using a fortran-to-c translation tool, however, it works for my sample matrices. 
I can also create a merge request for my fix if you wish.

Regards,
Lennart

**Comment by srajama1** [comment]
@LennartSchu : Thanks for reporting the error and suggesting the fix. @iyamazaki and @ndellingwood have fixed lot of issues in Basker that live in a branch. I am not sure, if this was addressed there. I will let one of them check it.

**Comment by iyamazaki** [comment]
No, we have not looked at it, yet. We have been focusing on sequential runs, but are now moving to threaded runs. So, we can take a look, or @LennartSchu can make a PR. Thank you.

**Comment by iyamazaki** [comment]
I'm closing this since [PR 9525](https://github.com/trilinos/Trilinos/pull/9525) should fix this. Please let us know if you still see the issue..
