### ISSUE TITLE
Framework: Ride PR testing down

### ISSUE THREAD

**Issue by jhux2** [trilinos/Trilinos#7498]
## Bug Report
@trilinos/framework @bartlettroscoe 

PR testing on ride is broken:

```
Kokkos::Cuda::initialize ERROR: running kernels compiled for compute capability 3.7 on device with compute capability 6.0 is not supported by CUDA!
```

**Comment by cgcgcg** [comment]
Should be fixed by PR #7496

**Comment by jhux2** [comment]
Ok, PR testing on ride is working again.

**Comment by prwolfe** [comment]
My apologies for not seeing this earlier. I have reverted to the old node type and am testing a more correct fix by hand. The long cycle time will keep that from finishing today.

**Comment by jhux2** [comment]
@prwolfe No worries, thank you!
