### ISSUE TITLE
STK: STKUtil requires Boost but does not state a required Boost dependency

### ISSUE THREAD

**Issue by ibaned** [trilinos/Trilinos#750]
I configured Trilinos with STKExprEval enabled and the Boost TPL not enabled, and got compiler errors of which the following is one example:

```
/home/daibane/src/Trilinos/packages/stk/stk_util/stk_util/util/ParameterList.hpp:38:10: fatal error: 'boost/any.hpp' file not found
#include <boost/any.hpp>                // for any, any_cast
         ^
```

There seems to be some effort in the STKUtil CMake files to properly handle an optional dependency on BoostLib, but these errors show that either more files need to be conditionally compiled or a required dependency needs to be stated.

**Comment by jhux2** [comment]
@alanw0

**Comment by alanw0** [comment]
@bmpersc is the expert in cmake files for stk, it would be risky for me to try to fix this without his expertise. It does appear as though boost should be a required dependency. Does the stk label mean that this bug report is already referred to the stk support list?

**Comment by jhux2** [comment]
> Does the stk label mean that this bug report is already referred to the stk support list?

@alanw0 Labels are added by the Trilinos developer community, and help to categorize issues.  The ```STK``` label doesn't necessarily mean it's been reported elsewhere.  By support list, do you mean the canonical stk-users or stk-developers lists, or a different one?

**Comment by jwillenbring** [comment]
To report to the STK team, you need to mention @trilinos/stk. I wish that labels could be used to help report.

**Comment by bmpersc** [comment]
STK util is specifying an optional dependency on BoostLib, however, it seems the dependency has become required. There are several other subpackages of STK that already have a required dependency on BoostLib so making STK util require it too should not be a large issue. @alanw0 if you disagree with that let me know otherwise I will plan to change the dependency to required.

**Comment by alanw0** [comment]
@bmpersc It looks like it should be required.

**Comment by bathmatt** [comment]
Is there any progress on this?  I enable boost and boostlib and still get this error.
-D TPL_ENABLE_Boost:BOOL=ON \
-D TPL_ENABLE_BoostLib:BOOL=ON \
-D Boost_INCLUDE_DIRS:FILEPATH="${BOOST_ROOT}/include" \
-D Boost_LIBRARY_DIRS:FILEPATH="${BOOST_ROOT}/lib" \
-D BoostLib_LIBRARY_DIRS:FILEPATH="${BOOST_ROOT}/lib" \
...
make[2]: *** [packages/stk/stk_search_util/stk_search_util/CMakeFiles/stk_search_util_base.dir/PeriodicBoundarySearch.cpp.o] Error 1
make[1]: *** [packages/stk/stk_search_util/stk_search_util/CMakeFiles/stk_search_util_base.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs...

**Comment by jdmille** [comment]
Is this a question the sierra stk team needs to see? In all such cases please note that in your comment. Otherwise I will not take any action.

Joel D. Miller
sierra-help@sandia.gov

**Comment by bmpersc** [comment]
I have not had a chance to fix this yet. I will try and get it into Sierra and into Trilinos by the end of the week.
