### ISSUE TITLE
Muelu:  failed to compile with complex. 

### ISSUE THREAD

**Issue by kyungjoo-kim** [trilinos/Trilinos#7507]
## Bug Report
@trilinos/muelu 

@crdohrm attempts to compile Trilinos for Sierra code. Compiling fails with the following error message.
```
ded-virtual -O2 -w --relocatable-device-code=true  -expt-extended-lambda -arch=sm_70  -DNDEBUG   -std=c++11 -o CMakeFiles/muelu-adapters.dir/ExplicitInstantiation/MueLu_RefMaxwell.cpp.o -c /vscratch1/crdohrm/Sierra/codeTI/objs/tpls/Trilinos/f600745ecce0ca83/packages/muelu/adapters/ExplicitInstantiation/MueLu_RefMaxwell.cpp
/vscratch1/crdohrm/Sierra/codeTI/TPLs_src/Trilinos/packages/kokkos/core/src/Cuda/Kokkos_Cuda_Parallel.hpp(609): error: calling a constexpr __host__ function("std::complex<double> ::complex") from a __device__ function("Kokkos::Impl::ParallelFor< ::,  ::Kokkos::RangePolicy<int,  ::Kokkos::Cuda > ,  ::Kokkos::Cuda> ::operator () const") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.
 
/vscratch1/crdohrm/Sierra/codeTI/TPLs_src/Trilinos/packages/kokkos/core/src/Cuda/Kokkos_Cuda_Parallel.hpp(609): error: identifier "std::complex<double> ::complex" is undefined in device code 
```
The error message says that it requires --expt-relaxed-constexpr. However, the problem is somehow muelu instanciates with std::complex on cuda intead of using kokkos complex.

### Steps to Reproduce
1. SHA1: current master branch.
2. Configure script:  it enables complex on cuda and also enable relocatable device code.

**Comment by jhux2** [comment]
@kyungjoo-kim @crdohrm Thanks for reporting.  Would it be possible to get a minimal cmake configure line?

**Comment by lucbv** [comment]
@kyungjoo-kim trilinos does not need relocatable device flags so I am not sure why it is enabled. If I remember correctly though, there should be an ATDM build that enables it, so it should not create problems?
The complex issue I am sorry to say is not so surprising...

**Comment by cgcgcg** [comment]
@kyungjoo-kim Did the patch I sent you do anything?

**Comment by jhux2** [comment]
@crdohrm Please let us know if this fixes the error you're seeing.

**Comment by crdohrm** [comment]
Thanks guys! I'll try building again once Trilinos develop gets merged to master and let you know how it goes.

**Comment by crdohrm** [comment]
I was able to successfully build today with Trilinos/master. Thanks again.

**Comment by jhux2** [comment]
Closing as fixed.

**Comment by kyungjoo-kim** [comment]
@jwillenbring Do we have a separate issue tracker regarding to the testing infrastructure for Sierra code ?

**Comment by jhux2** [comment]
> Do we have a separate issue tracker regarding to the testing infrastructure for Sierra code ? If we have one, you may want to refer this issue to that.

@kyungjoo-kim Thanks for the reminder.  I think it would be better track the new PR instance in a separate issue.

**Comment by kyungjoo-kim** [comment]
#7548
