### ISSUE TITLE
Tempus: fail to compile with gcc in linux when Tempus_enable_tests turns on

### ISSUE THREAD

**Issue by hillyuan** [trilinos/Trilinos#7522]
## Bug Report
@trilinos/\Tempus

### Description
When compiled in Ubuntu 18 with gcc 7.5, or Centos 7.2 with gcc 4.8.5, Compiling fails with the following message

In file included from /Trilinos/packages/tempus/src/Tempus_StepperForwardEulerModifierDefault.hpp:14:0,
                 from Trilinos/packages/tempus/src/Tempus_StepperForwardEuler_impl.hpp:14,
                 from /Trilinos/build/packages/tempus/src/Tempus_StepperForwardEuler.hpp:2,
                 from /Trilinos/packages/tempus/src/Tempus_StepperForwardEulerAppAction.hpp:14,
                 from /Trilinos/packages/tempus/src/Tempus_StepperForwardEuler_decl.hpp:17,
                 from /Trilinos/build/packages/tempus/src/Tempus_StepperForwardEuler.hpp:1,
                 from /Trilinos/packages/tempus/src/Tempus_StepperFactory.hpp:13,
                 from /Trilinos/packages/tempus/src/Tempus_IntegratorBasic_impl.hpp:14,
                 from /Trilinos/build/packages/tempus/src/Tempus_IntegratorBasic.hpp:2,
                 from /Trilinos/packages/piro/src/Piro_TempusIntegrator.hpp:48,
                 from /Trilinos/packages/piro/src/Piro_TransientSolver.hpp:48,
                 from /Trilinos/packages/piro/src/Piro_TempusSolver.hpp:53,
                 from /Trilinos/packages/piro/src/Piro_SolverFactory_Def.hpp:60,
                 from /Trilinos/packages/piro/src/Piro_SolverFactory.hpp:94,
                 from /Trilinos/packages/piro/test/Main_ThyraSolver.cpp:48:
/Trilinos/packages/tempus/src/Tempus_StepperForwardEulerModifierBase.hpp:47:56: error: expected template-name before ‘<’ token
   : virtual public Tempus::StepperForwardEulerAppAction<Scalar>

  And vast number of relative errors. 

### Steps to Reproduce
Follows are my configuration:
cmake .. \
  -DCMAKE_INSTALL_PREFIX:FILEPATH="~/programs/solver/Trilinos/install" \
  -DCMAKE_CXX_COMPILER=mpic++ \
  -DCMAKE_C_COMPILER=mpicc \
  -DCMAKE_BUILD_TYPE:STRING=RELEASE \
  -DHDF5_INCLUDE_DIRS=/usr/include/hdf5/openmpi  \
  -DHDF5_LIBRARY_DIRS=/usr/lib/x86_64-linux-gnu/hdf5/openmpi  \
  -DTPL_ENABLE_MPI:BOOL=ON \
  -DTPL_ENABLE_HDF5=ON  \
  -DTPL_ENABLE_Matio=OFF  \
  -DTrilinos_ENABLE_Fortran=ON \
  -DTrilinos_ENABLE_SEACAS=ON \
  -DTrilinos_ENABLE_Panzer=ON  \
  -DTrilinos_ENABLE_STK=ON  \
  -DPiro_ENABLE_TESTS=ON \

  Nothing happens when Tempus related tests, such as Tempus_ENABLE_TESTS or Pito_ENABLE_TESTS turns off.

**Comment by ccober6** [comment]
This issue is likely not related to Tempus_ENABLE_TESTS being on/off, but the version of the compiler/platform being used.  We test against a wide variety of compilers/platforms, but unfortunately not either of the combinations you mentioned.   We currently test against the following gcc versions: 4.8.4, 4.9.3 5.3.0, 7.2.0, 8.3.0 without error.  Can you try one of these?

**Comment by ccober6** [comment]
FYI, also built and ran tests with gcc 9.2.0 without error.

**Comment by hillyuan** [comment]
Thanks @ccober6 

If is it possible, I would like try it at some other compiler or platform. However, I have found some head files depend upon each other. I think it would give rise to compiler error. I fixed those problems at merge request #7525. Would you please review this request.

**Comment by ccober6** [comment]
@hillyuan #7539 has been merged into Trilinos:develop.  Can you confirm that this fixes your issue?  Thanks!

**Comment by hillyuan** [comment]
It works. Thanks @ccober6
