### ISSUE TITLE
Framework:  Increase amount of test output shown on CDash for passing tests

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#7547]
## Bug Report
@trilinos/framework, @jjellio 

## Description:

It seems that the ctest -S driver used for the Trilinos PR builds is only allowing 1025 bytes of output for passing tests in PR builds.  This is undesirable because one can't see what a test looks like when it is passing to help diagnose when it is failing.  And, important info is given in some tests when they pass. 

For example, for the build stats compiler wrappers and reporting being developed in #7376 and PR #7508, the test `TrilinosBuildStats_Results` provides a summary of the most important build stats.  But you can't see them because of this limitation, as (not) seen for example, in:

* https://testing.sandia.gov/cdash/testDetails.php?test=117066225&build=7284178

**Comment by bartlettroscoe** [comment]
To fix this, one must process and read in:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/ctest/CTestCustom.cmake.in

The TRIBITS_CTEST_DRIVER() does this and as shown, for example, [here](https://testing-dev.sandia.gov/cdash/test/19550883) shows the full test output showing the critical data:

```
Full Project: sum(max_resident_size_mb) = 218011.21 (781 entries)
Full Project: max(max_resident_size_mb) = 1914.43 (packages/teuchos/parameterlist/test/Dependencies/CMakeFiles/TeuchosParameterList_Dependencies_Serialization_test.dir/Dependencies_SerializationTests.cpp.o)
Full Project: sum(elapsed_real_time_sec) = 12527.38 (781 entries)
Full Project: max(elapsed_real_time_sec) = 409.49 (packages/kokkos/core/unit_test/CMakeFiles/KokkosCore_UnitTest_Serial.dir/serial/TestSerial_Other.cpp.o)
Full Project: sum(file_size_mb) = 792.12 (781 entries)
Full Project: max(file_size_mb) = 48.94 (packages/kokkos/core/unit_test/KokkosCore_UnitTest_Serial.exe)
```

(but with just TeuchosCore and KokkosCore enabled).

**Comment by wadeburgess** [comment]
This was migrated to the Trilinos Help Desk, so this issue is being closed now.

**Comment by bartlettroscoe** [comment]
I had forgotten I created this GitHub issue when I wrote #10980.  Therefore, this issue is a duplicate of #10980 that documents how this got fixed (by me).
