### ISSUE TITLE
Framework: Trilinos testing for Sierra integration.

### ISSUE THREAD

**Issue by kyungjoo-kim** [trilinos/Trilinos#7548]
## Enhancement

@trilinos/framework @jwillenbring @crdohrm 

Following the #7507, this issue is for a better Trilinos Sierra itegration. Currently, there is no nightly test that follows Sierra Trilinos integration configurations. The configuration is given in #7206 (@vbrunini). For the cuda compilation, it also enables relocatable device code.

**Comment by jhux2** [comment]
@kyungjoo-kim I think @jwillenbring was proposing a new PR instance.
