### ISSUE TITLE
Kokkos: Bug in BoundsCheck and DynRankView makes Debug builds fail

### ISSUE THREAD

**Issue by crtrott** [trilinos/Trilinos#755]
This slipped integration testing, since it didn't enable boundschecks. I disabled the cmakeoption to enable boundschecks inside of Trilinos which should fix the issues. The Kokkos issue is:

kokkos/kokkos#516

**Comment by aprokop** [comment]
@crtrott Closing, as the fix was pushed to Kokkos and then to Trilinos.
