### ISSUE TITLE
Intrepid2: const nature with kokkos and output values

### ISSUE THREAD

**Issue by bathmatt** [trilinos/Trilinos#756]
@kyungjoo-kim @crtrott @rppawlo 

The prototype for getVaues assumes a non-const outputValue

However, if one uses internal class views for this, they have to be const, since the kokkos functor has to be const.  The only solution is to make the views mutable, is this the right option?  Do we want to specialize on kokkos::view types for const?  What is the right thing moving forward?

template<class Scalar, class ArrayScalar>
void getValues_HGRAD_Args(ArrayScalar &                outputValues,
                          const ArrayScalar &          inputPoints,
                          const EOperator              operatorType,
                          const shards::CellTopology&  cellTopo,
                          const int                    basisCard){

**Comment by kyungjoo-kim** [comment]
I am not sure if I understand the question correctly, but if your intention is about conversion between non-const view and const view, you can simply assign the view. For instance,

```
template<typename view_type>
using const_view_type = Kokkos::View<
    view_type::const_data_type,                                                     
    view_type::array_layout,
    view_type::device_type,
    view_type::memory_traits>;

typedef Kokkos::View<value_type*,lay_out_type,device_type> non_const_view_type;
non_const_view_type a("non_const_a",  10);
const_view_type<non_const_view_type> b(a); // or  b = a;

// now use b where you need
```

If this is wrong or there is a better way, please correct it.

**Comment by mhoemmen** [comment]
Kokkos::View has a "const_type" typedef that returns the const version of that View specialization.

**Comment by bathmatt** [comment]
The problem is that kokkos functor data has to be const, therefore, all
internal views have to be const.  So, if you call intrepid functions with a
kokkos view it fails to compile because it violates the const.  Therefore,
we need Intrepid2 to have a const array_type output_values,

**Comment by kyungjoo-kim** [comment]
Can you give me a more concrete example that invokes intrepid2 functions ? and the error message too. I may be dumb but I don't understand why kokkos functor data must be const. In the above particular example you mentioned, it uses reference and it could be problematic if you feed a const object into nonconst reference. In the refactored version, I do not reference for function arguments. It is all call by value. You should check intrepid2 refactored version code (even if right now you cannot use the code as other packages do not rely on it).

**Comment by bathmatt** [comment]
struct foo {
  Kokkos::View<double*> outvals,invals;
  void operator() (int i) const {
    Intrepid2:anyFunction(outvals,invals);
}

where intrepid2::anyFunction( array out, const array in){}

anyFunction has a non-const outvals., therefore, you can't call it from
operator which has to be const for kokkos.


Matt

**Comment by kyungjoo-kim** [comment]
Hi Matt

First, I try to generate your compiler error with the attached code. It compiles and works. If you see any problem inconsistency with your case, please let me know (I just want to know where the ''const'' matters. 

Second, Intrepid2 front interface cannot be included inside of a functor. It is not even decorated with KOKKOS_INLINE_FUNCTION as your functor is not either. So, your intention might be to use the code for host processors only. Since you mostly concern about basis function, in the refactored intrepid2 version, we have a separate serial interface which is callable within a functor evaluating basis for a single point. Please check that interface is suited for your use case. 


```
#include <Kokkos_Core.hpp>

template<typename outViewType, typename inViewType>
void myfunction(outViewType out, const inViewType in) {
  for (int i=0;i<out.dimension(0);++i)
    printf("data = %lf, %lf\n", out(i), in(i));
}

struct foo {
  Kokkos::View<double*> outVals, inVals;
  foo(Kokkos::View<double*> outVals_,
      Kokkos::View<double*> inVals_)
    : outVals(outVals_), inVals(inVals_) {}

  void operator()(const int i) const {
    myfunction(outVals, inVals);
  }
};

int main() {

  constexpr int N = 10;

  Kokkos::initialize();
  Kokkos::View<double*> out("out", N), in("in", N);
  Kokkos::parallel_for(N, foo(out, in));
  Kokkos::finalize();

  return 0;
}
```

**Comment by bathmatt** [comment]
Second things first, where in the refactored code can I find this serial
call?  Does it use the subview stuff you showed the other day?

Now, Here is the real code,


  Kokkos::DynRankView<double, PHX::Device> temp_vector_basis_in_;
  Kokkos::DynRankView<double, PHX::Device> temp_vector_basis_out_;


KOKKOS_INLINE_FUNCTION
template <typename TOPOLOGY>
void
PICMeshInteraction<TOPOLOGY>::getBasisVectorValuesAtPoint(Teuchos::RCP<PICMeshInteractionBase::intrepid_basis>
basis, const int which_elem, const double *p, Kokkos::View<double **>
values) const{

  double rp[3];
  mapToRefFrame( which_elem, p, rp);
  for ( int iDim=0; iDim< dimension_; ++iDim)
    temp_vector_basis_in_(0,iDim) = rp[iDim];

  vector_basis_->getValues(temp_vector_basis_out_, temp_vector_basis_in_,
Intrepid2::OPERATOR_VALUE);
  for (int icard=0;icard<temp_vector_basis_out_.extent(0); ++icard)
    for (int idim=0;idim<dimension_; ++idim)
      values(icard,idim) = temp_vector_basis_out_(icard,0,idim);
}

and it gives
/home/mbetten/Trilinos/mini-PIC/src/PIC/PIC_Mesh_interface_impl.hpp:413:90:
error: no matching function for call to ‘Intrepid2::Basis<double,
Kokkos::Experimental::DynRankView<double, Kokkos::OpenMP>
>::getValues(Kokkos::DynRankView<double, Kokkos::OpenMP>&,
Kokkos::DynRankView<double, Kokkos::OpenMP>&, Intrepid2::EOperator)’


but if I change
  Kokkos::DynRankView<double, PHX::Device> temp_vector_basis_out_;
to
mutable   Kokkos::DynRankView<double, PHX::Device> temp_vector_basis_out_;
it compiles fine

**Comment by kyungjoo-kim** [comment]
Please see line no 96, ``packages/intrepid2/refactor/src/Discretization/Basis/Intrepid2_HGRAD_HEX_C1_FEM.hpp``. 

This code is compiled with unit tests. You can also find out a functor interface that uses the serial interface. A few comment about this Serial interface: 
- The code under "Impl" namespace does not check any input parameters (parameter checking happens in the front interface). 
- The Serial interface does not include virtual function. Kokkos device functor won't take virtual functions on devices as virtual table include virtual function pointers and pointers are ambiguous on the device space (in my small opinion, your work scenario is probably not portable to gpus). 
- RCP is defnitely dangerous when you use it in a functor. 
- This means that if you want to use intrepid2 functions inside your functor, you probably need to use template based polymophism.


Kokkos developers, if you found any flaws in the above comments, please correct me.

**Comment by mhoemmen** [comment]
> RCP is definitely dangerous when you use it in a functor.

Specifically, Teuchos::*RCP reference count updating is _not_ thread safe (#229).

**Comment by kyungjoo-kim** [comment]
@bathmatt  

If this won't bother your work any more, I am going to close this issue.
