### ISSUE TITLE
Problems with Waffle.io

### ISSUE THREAD

**Issue by jmgate** [trilinos/Trilinos#758]
Here's a story to document any problems we're having with waffle.io, along with possible solutions.

**Comment by jmgate** [comment]
Here's @bartlettroscoe's email with a fix for Firefox on Window 7:

Hello Trilinos Developers,
 
At the TUG Developers Meeting this week, I heard several people mention that Waffe.io did not work for them to view and manage Trilinos GitHub Issues at:
 
    https://waffle.io/trilinos/Trilinos          
 
Below is an email I sent out earlier this year on how I fixed a problem with Waffe.io for FireFox on my SNL Windows 7 machine.  My guess is that some people may be having a similar problem.  The fix is to upgrade FireFox and then set the release channel from “esr” to “release”.
 
If there other problems with Waffe.io, then we should create a Trilinos GitHub Issue to document the problems that people are having and solutions that we find.
 
I have been using Waffe.io for a while now with both the Trilinos and TriBITS GitHUb sites and I think it works pretty well for what it is.  I think it provides real value over just raw GitHub issues if you want to use Kanban.
 
Cheers,
 
-Ross
 
 
 
From: Bartlett, Roscoe A 
Sent: Saturday, March 05, 2016 2:38 PM
To: 'trilinos-developers@software.sandia.gov'
Subject: Issue with FireFox and waffle.io
 
Hello Trilinos Developers,
 
If any of you are accessing the Trilinos waffle.io site:
 
    https://waffle.io/trilinos/Trilinos
 
with FireFox on a Sandia Windows 7 machine (where FireFox was installed already by the COE), then please take note of following issue …
 
It turns out that you need to have FireFox version 41 or newer or the waffle.io feature to hide or expand a column feature is broken.  That is, if you collapse a column with a version of FireFox earlier than version 41, you can never expend it again!  It turns out that the Sandia Windows 7 COE install of FireFox is set up update on the ‘esr’ update channel and not the regular ‘release’ channel.  The most current version on the ‘esr’ channel is version 38 which is before version 41 where this works.  To fix this, you have to reinstall FireFox on your Windows machine.  If you do that, it will install version 44 on the “release” channel (which is the most current releases).
 
Cheers,
 
-Ross
 
_______________________________________________
Trilinos-developers mailing list
Trilinos-developers@trilinos.org
https://trilinos.org/mailman/listinfo/trilinos-developers

**Comment by jmgate** [comment]
@jwillenbring's <a href="https://github.com/trilinos/Trilinos/issues/750#issuecomment-257566874">comment</a> is related to another issue&mdash;waffle.io does not autocomplete team mentions.  I didn't even realize that was possible, because I've been using waffle.io exclusively since starting here (and since starting with GitHub).  It might be a common misconception that labels fulfill the purpose of team mentions&mdash;at least that's how I thought it worked.  This is a waffle.io <a href="https://github.com/waffleio/waffle.io/issues/2400">issue</a>, though no idea when they'll get around to implementing it.

**Comment by jmgate** [comment]
Another irritation of working with waffle.io is the cards don't display all of the issue history as shown in GitHub issues.  Many people have requested this feature of waffle.io (as <a href="https://github.com/waffleio/waffle.io/issues/972">here</a>), but it doesn't look like there's any ETA.

**Comment by bartlettroscoe** [comment]
My view is that waffle.io **add** features to GitHub Issue, not replace them.  I just use the direct link to the GitHub issue to edit the fields of the issue.  I only use waffe.io to graphically show and filter the different issues into the different columns.   What people can't even do that?

**Comment by mhoemmen** [comment]
> What people can't even do that?

waffle.io crashes my Firefox (version > 41).  I can use it with Safari, though.

**Comment by bartlettroscoe** [comment]
> waffle.io crashes my Firefox (version > 41)

Below is an email about how to fix waffle.io for FireFox.

Hello Trilinos Developers,

If any of you are accessing the Trilinos waffle.io site:

* https://waffle.io/trilinos/Trilinos

with FireFox on a Sandia Windows 7 machine (where FireFox was installed already by the COE), then please take note of following issue …

It turns out that you need to have FireFox version 41 or newer or the waffle.io feature to hide or expand a column feature is broken.  That is, if you collapse a column with a version of FireFox earlier than version 41, you can never expend it again!  It turns out that the Sandia Windows 7 COE install of FireFox is set up update on the ‘esr’ update channel and not the regular ‘release’ channel.  The most current version on the ‘esr’ channel is version 38 which is before version 41 where this works.  To fix this, you have to reinstall FireFox on your Windows machine.  If you do that, it will install version 44 on the “release” channel (which is the most current releases).

Cheers,

-Ross
