### ISSUE TITLE
Trilinos config error for Nalu: mpif90 --broken

### ISSUE THREAD

**Issue by spdomin** [trilinos/Trilinos#7586]
## Bug Report
@trilinos/config

I have a new config error that started last night related to mpif90. I cannot determine if this is something new in Trilinos config or the modules that I pull in. @alanw0, any ideas?

Good:
NaluCFD/Nalu SHA1: 12a7d1c7b017ca070363b325f79f97eec39d374b
Trilinos/develop SHA1: 08709a71bd9a456d80eb732eddf5c5570929481d

Bad:
NaluCFD/Nalu SHA1: 12a7d1c7b017ca070363b325f79f97eec39d374b
Trilinos/develop SHA1: d0684fdb380a70c99ace5993b57f414f9c6cf2ab

### Description

-- The Fortran compiler identification is GNU 8.3.0
-- Check for working Fortran compiler: /projects/sierra/linux_rh6/SDK/mpi/openmpi/4.0.1-gcc-8.3.0-RHEL6/bin/mpif90
-- Check for working Fortran compiler: /projects/sierra/linux_rh6/SDK/mpi/openmpi/4.0.1-gcc-8.3.0-RHEL6/bin/mpif90  -- broken
CMake Error at /home/spdomin/gitHubWork/scratch_build/install/gcc8.3.0/cmake/3.12.3/share/cmake-3.12/Modules/CMakeTestFortranCompiler.cmake:45 (message):
  The Fortran compiler

    "/projects/sierra/linux_rh6/SDK/mpi/openmpi/4.0.1-gcc-8.3.0-RHEL6/bin/mpif90"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /home/spdomin/gitHubWork/nightlyBuildAndTest/Trilinos/build_nightly_release_8.3.0/CMakeFiles/CMakeTmp
    
    Run Build Command:"/usr/bin/gmake" "cmTC_ccb7a/fast"
    /usr/bin/gmake -f CMakeFiles/cmTC_ccb7a.dir/build.make CMakeFiles/cmTC_ccb7a.dir/build
    gmake[1]: Entering directory `/home/spdomin/gitHubWork/nightlyBuildAndTest/Trilinos/build_nightly_release_8.3.0/CMakeFiles/CMakeTmp'
    Building Fortran object CMakeFiles/cmTC_ccb7a.dir/testFortranCompiler.f.o
    /projects/sierra/linux_rh6/SDK/mpi/openmpi/4.0.1-gcc-8.3.0-RHEL6/bin/mpif90    -c /home/spdomin/gitHubWork/nightlyBuildAndTest/Trilinos/build_nightly_release_8.3.0/CMakeFiles/CMakeTmp/testFortranCompiler.f -o CMakeFiles/cmTC_ccb7a.dir/testFortranCompiler.f.o
    Linking Fortran executable cmTC_ccb7a
    /home/spdomin/gitHubWork/scratch_build/install/gcc8.3.0/cmake/3.12.3/bin/cmake -E cmake_link_script CMakeFiles/cmTC_ccb7a.dir/link.txt --verbose=1
    /projects/sierra/linux_rh6/SDK/mpi/openmpi/4.0.1-gcc-8.3.0-RHEL6/bin/mpif90      CMakeFiles/cmTC_ccb7a.dir/testFortranCompiler.f.o  -o cmTC_ccb7a 
    ld: error: corrupt input file: version definition index 0 for symbol mpi_fortran_unweighted_ is out of bounds
    >>> defined in /sierra/sntools/SDK/mpi/openmpi/4.0.1-gcc-8.3.0-RHEL6/lib/libmpi_usempif08.so
    
    ld: error: corrupt input file: version definition index 0 for symbol mpi_fortran_argv_null_ is out of bounds
    >>> defined in /sierra/sntools/SDK/mpi/openmpi/4.0.1-gcc-8.3.0-RHEL6/lib/libmpi_usempif08.so
    
    ld: error: corrupt input file: version definition index 0 for symbol mpi_fortran_errcodes_ignore_ is out of bounds
    >>> defined in /sierra/sntools/SDK/mpi/openmpi/4.0.1-gcc-8.3.0-RHEL6/lib/libmpi_usempif08.so
    
    ld: error: corrupt input file: version definition index 0 for symbol mpi_fortran_weights_empty_ is out of bounds
    >>> defined in /sierra/sntools/SDK/mpi/openmpi/4.0.1-gcc-8.3.0-RHEL6/lib/libmpi_usempif08.so
    
    ld: error: corrupt input file: version definition index 0 for symbol mpi_fortran_argvs_null_ is out of bounds
    >>> defined in /sierra/sntools/SDK/mpi/openmpi/4.0.1-gcc-8.3.0-RHEL6/lib/libmpi_usempif08.so
    collect2: error: ld returned 1 exit status
    gmake[1]: *** [cmTC_ccb7a] Error 1
    gmake[1]: Leaving directory `/home/spdomin/gitHubWork/nightlyBuildAndTest/Trilinos/build_nightly_release_8.3.0/CMakeFiles/CMakeTmp'
    gmake: *** [cmTC_ccb7a/fast] Error 2
  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  cmake/tribits/core/package_arch/TribitsGlobalMacros.cmake:2032 (ENABLE_LANGUAGE)
  cmake/tribits/core/package_arch/TribitsProjectImpl.cmake:193 (TRIBITS_SETUP_ENV)
  cmake/tribits/core/package_arch/TribitsProject.cmake:93 (TRIBITS_PROJECT_IMPL)
  CMakeLists.txt:90 (TRIBITS_PROJECT)

-- Configuring incomplete, errors occurred!
See also "/home/spdomin/gitHubWork/nightlyBuildAndTest/Trilinos/build_nightly_release_8.3.0/CMakeFiles/CMakeOutput.log".
See also "/home/spdomin/gitHubWork/nightlyBuildAndTest/Trilinos/build_nightly_release_8.3.0/CMakeFiles/CMakeError.log".
### Steps to Reproduce
1. SHA1:  [insert here]
1. Configure script:  [attach here]
1. Configure log:  [attach here]
1. Build log:  [attach here]
1. Input deck:  [attach here]
1. Do this.
1. Do that.
1. Shake fist angrily at computer.
1. Run log:  [attach here]

**Comment by alanw0** [comment]
@spdomin Hmm, it is suspicious that we pushed a stk update up to Trilinos two nights ago, but we didn't knowingly change anything related to fortran. (there is no fortran code in stk)
I'll look over our update and see if I can see anything that might have influenced this.

**Comment by rppawlo** [comment]
I had some trouble with stk and fortran wrappers a while ago. Run "git grep FORTRAN" and there is a ton of code in stk for wrappers to blas/lapack. It could be that the stk wrappers are changing trilinos variables or defining separate incompatible ones. Examples:
```
CMakeLists.txt:  SET(FORTRAN_NO_UNDERSCORE ON)
CMakeLists.txt:  SET(FORTRAN_ONE_UNDERSCORE ON)
CMakeLists.txt:  SET(FORTRAN_TWO_UNDERSCORES ON)
CMakeLists.txt:  SET(FORTRAN_NO_UNDERSCORE ON)
cmake/STK_Trilinos_config.h.in:#cmakedefine FORTRAN_NO_UNDERSCORE
cmake/STK_Trilinos_config.h.in:#cmakedefine FORTRAN_ONE_UNDERSCORE
cmake/STK_Trilinos_config.h.in:#cmakedefine FORTRAN_TWO_UNDERSCORES
stk_mesh/stk_mesh/base/FieldBLAS.hpp:void SIERRA_FORTRAN(dscal)(const int *n, const double *dscale, double *vect, const int *inc); //vect = dscale * vect
stk_mesh/stk_mesh/base/FieldBLAS.hpp:double SIERRA_FORTRAN(ddot)(const int * n, const double* x, const int * incx, const double* y, const int * incy); // < x , y >
stk_mesh/stk_mesh/base/FieldBLAS.hpp:double SIERRA_FORTRAN(dnrm2)(const int * n, const double* x, const int * incx); // || x ||
stk_mesh/stk_mesh/base/FieldBLAS.hpp:void SIERRA_FORTRAN(sscal)(const int *n, const float *sscale, float *vect, const int *inc); //vect = sscale * vect
stk_mesh/stk_mesh/base/FieldBLAS.hpp:void SIERRA_FORTRAN(dcopy)(const int* n, const double* d, const int* inc, double* d1, const int* inc1); // d1 = d
stk_mesh/stk_mesh/base/FieldBLAS.hpp:void SIERRA_FORTRAN(dswap)(const int* n, double* d, const int* inc, double* d1, const int* inc1); // switch d1 , d // D.N.E.
stk_mesh/stk_mesh/base/FieldBLAS.hpp:double SIERRA_FORTRAN(dasum)(const int * n,const double * x,const int * incx);
stk_mesh/stk_mesh/base/FieldBLAS.hpp:int SIERRA_FORTRAN(idamax)(const int *n, const double *vect, const int *inc);
stk_mesh/stk_mesh/base/FieldBLAS.hpp:void SIERRA_FORTRAN(saxpy)(const int *n, const float *xscale, const float x[], const int *incx, float y[],const int *incy); // y=y+sscale*x
stk_mesh/stk_mesh/base/FieldBLAS.hpp:void SIERRA_FORTRAN(scopy)(const int* n, const float* s, const int* inc, float* s1, const int* inc1); // s1 = s
stk_mesh/stk_mesh/base/FieldBLAS.hpp:float SIERRA_FORTRAN(sdot)(const int * n, const float* x, const int * incx, const float* y, const int * incy); // < x , y >
stk_mesh/stk_mesh/base/FieldBLAS.hpp:float SIERRA_FORTRAN(snrm2)(const int * n, const float* x, const int * incx); // || x ||
stk_mesh/stk_mesh/base/FieldBLAS.hpp:float SIERRA_FORTRAN(sasum)(const int * n,const float * x,const int * incx);
stk_mesh/stk_mesh/base/FieldBLAS.hpp:double SIERRA_FORTRAN(sdot)(const int * n, const float* x, const int * incx, const float* y, const int * incy); // < x , y >
stk_mesh/stk_mesh/base/FieldBLAS.hpp:double SIERRA_FORTRAN(snrm2)(const int * n, const float* x, const int * incx); // || x ||
stk_mesh/stk_mesh/base/FieldBLAS.hpp:double SIERRA_FORTRAN(sasum)(const int * n,const float * x,const int * incx);
stk_mesh/stk_mesh/base/FieldBLAS.hpp:void SIERRA_FORTRAN(sswap)(const int* n, float* s, const int* inc, float* s1, const int* inc1); // switch s1 , s // D.N.E.
```

**Comment by spdomin** [comment]
This might be modules... open MPI 4.0.1 and 4.0.2 fail while 4.0.3 works..

**Comment by spdomin** [comment]
I am going to close this issue as the bump to 4.0.3 (a more robust mpi) was suggested.
