### ISSUE TITLE
KokkosKernels unit tests' dependency to kokkos gtest build

### ISSUE THREAD

**Issue by mndevec** [trilinos/Trilinos#759]
Kokkos is using gtest for the unit tests. I think we talked briefly that we will use the same unit test harness for KokkosKernels, rather than introducing a dependency on Teuchos. 

I am trying to add unit tests that use gtest, assuming that kokkos builds gtest and I can access the prebuild kokkos_gtest library. However, it is only compiled when Kokkos test is enabled. 

I don't know an elegant way to handle this, I was wondering how this should be handled. 

@srajama1 @mhoemmen  @crtrott  @ambrad @kyungjoo-kim

**Comment by srajama1** [comment]
I don't think there is a way to check if Kokkos tests are enabled, other than directly using the Kokkos cmake macros. @crtrott might know better. We could ship with another version of gtest if needed.

**Comment by mhoemmen** [comment]
@srajama1 wrote:
> We could ship with another version of gtest if needed.

Just want to make sure we don't get weird link errors for having gtest twice, but that shouldn't matter, right? since we're only using it for tests?

**Comment by srajama1** [comment]
Yes, my assumption was no one else would link with it except Kokkoskernels tests.
