### ISSUE TITLE
Packages that work with MPI in a 32-bit build?

### ISSUE THREAD

**Issue by sagitter** [trilinos/Trilinos#760]
Hi all.

I'm testing `trilinos 12.8.1` with MPI activated, which packages are known as workable with MPI?

Currently, i'm keeping `Kokkos`, `Xpetra`, `Piro`, `Intrepid` and `Isorropia` deactivated on 32-bit architectures but even `STK` looks to have problem. Please, see this log: http://koji.fedoraproject.org/koji/getfile?taskID=16277182&name=build.log

Thanks.

**Comment by mhoemmen** [comment]
I renamed this to "Packages that work with MPI in a 32-bit build?".  We don't normally test Trilinos on 32-bit platforms, so it's important to make that distinction.
