### ISSUE TITLE
Zoltan2: Compilation error -Wformat-security

### ISSUE THREAD

**Issue by tzovas** [trilinos/Trilinos#7608]
## Bug Report
@trilinos/zoltan2

Early in the installation of zoltan2 (around 5%) I get the error

`cc1: error: -Wformat-security ignored without -Wformat [-Werror=format-security]`

If I add 
`-DCMAKE_C_FLAGS="-Wformat"`
in my cmake, the error goes away but I get another error about not finding the `Zoltan2_config.h.`

The PR https://github.com/trilinos/Trilinos/pull/7606  fixes the  `Zoltan2_config.h.` error but I still need to
add the "-Wformat" flag to avoid the first error error.

I also tried b18d109bc70cee79a58f960e784276277f611119 and there everything works fine
as before (no "-Wformat" flag is needed).

I am using a basic build with MPI and pulp ON.

**Comment by kddevin** [comment]
@tzovas are you still seeing this problem?  If so, would you please post your compiler version info and cmake configuration command with this issue?  If not, I will close this issue.

**Comment by tzovas** [comment]
I have not used or compile the code for a long time. So,
> are you still seeing this problem?

No (but because I haven't looked)
