### ISSUE TITLE
Stokhos TpetraMatvec test failing in continuous build

### ISSUE THREAD

**Issue by bmpersc** [trilinos/Trilinos#761]
@trilinos/stokhos the Stokhos_TpetraMatVec_MPI_4 seems to be failing, though the output doesn't make it clear. If you could look into this soon it would be appreciated. It is one of two tests that are new which need to be addressed before freezing for the 12.10 release.

you can see the error at:
https://testing.sandia.gov/cdash/viewTest.php?onlyfailed&buildid=2605794

**Comment by etphipp** [comment]
The test has been periodically failing for a few weeks now.  Unfortunately I haven't been able to reproduce it on any machine.  What's slightly disturbing about it is it is just doing a standard tpetra mat-vec.  This test was added during the kokkos refactor of Tpetra when Tpetra was unstable.

**Comment by etphipp** [comment]
It looks like the test is dying before the final "TEST PASSED" is printed out.  There is actually a second Belos test in there that I forgot about, and the output on cdash doesn't show anything about it.  I'll try disabling that one and see if it passes.

**Comment by etphipp** [comment]
It looks like from cdash that this test is passing now.

I don't understand what was wrong.  The test appeared to be timing out in the second unit test, which was using Belos GMRES to solve a 10x10 banded linear system.  I changed the linear system to a diagonal one, and it went from timing out after 10 min to taking about 2 sec to run.

**Comment by mhoemmen** [comment]
Huh, did my #762 fix last night (rewrote the KokkosKernels sparse mat-vec) have anything to do with this, or does Stokhos roll its own mat-vec?

**Comment by etphipp** [comment]
I believe this is due to how I changed the test.  Stokhos does not roll its own mat-vec (at least not in this case).
