### ISSUE TITLE
ROL:  StdVector needs to include numerics header

### ISSUE THREAD

**Issue by briadam** [trilinos/Trilinos#7612]
## Bug Report
@trilinos/ROL
@dridzal @dpkouri @gregvw @rhoope 

### Description
ROL_StdVector.hpp needs to include numeric header, pretty please

### Steps to Reproduce
1. SHA1:  I think Dakota's version is e9cb59b
1. Attempt to compile ROL on MSVS 2015

### Patch
```
diff --git a/trilinos/packages/rol/src/vector/ROL_StdVector.hpp b/trilinos/packages/rol/src/vector/ROL_StdVector.hpp
index f21f9e9f..d9c9c3cc 100644
--- a/trilinos/packages/rol/src/vector/ROL_StdVector.hpp
+++ b/trilinos/packages/rol/src/vector/ROL_StdVector.hpp
@@ -47,6 +47,7 @@
 #include <algorithm>
 #include <cstdlib>
 #include <initializer_list>
+#include <numeric>
 #include "ROL_Vector.hpp"

 /** \class ROL::StdVector
```

**Comment by dridzal** [comment]
Just last week an MSVS user, @tbinford, discovered the same problem ...

@gregvw , since you converted this file to use `<numeric>` functions, do you think that this is a complete fix?  Are there any other files where you have used `<numeric>` functions without including the header?  I can make the changes and submit a PR, but I would like to get all instances at once.

@briadam , I would like to ask for a favor.  Since you clearly have an MSVS build, could you please try building and running the `example_ineq_bnd.cpp` example in the tutorial directory of rol?  @tbinford is reporting run-time issues with a vector, possibly related to a memory leak in LBFGS, which seems to occur only with MSVS.

**Comment by briadam** [comment]
> @briadam , I would like to ask for a favor. Since you clearly have an MSVS build, could you please try building and running the `example_ineq_bnd.cpp` example in the tutorial directory of rol? @tbinford is reporting run-time issues with a vector, possibly related to a memory leak in LBFGS, which seems to occur only with MSVS.

Sure @dridzal I can attempt to do that. In our Dakota builds we neuter build and test of some chunks of Trilinos, but I can probably get them going to do this, as I have an interactive MSVS build on my DaaS as well as two workstations. I don't think I have a working "Dr. Memory" due to system restrictions, so probably can't get a trace if there is a memory issue.

**Comment by briadam** [comment]
P.S. I didn't know the C++ standard had an inner_product, so thanks for the education!

**Comment by briadam** [comment]
When I try to tweak my configure to build ROL's tests by setting ROL_ENABLE_TESTS in my CMakeCache.txt, I get this amusing(?) contradictory error message:
```
CMake Error at packages/external/trilinos/cmake/tribits/core/package_arch/TribitsAddExecutableTestHelpers.cmake:66 (MESSAGE):
  Error, the COMM value 'mpi' is not valid.  Only 'mpi' and 'serial' are
  allowed.
Call Stack (most recent call first):
  packages/external/trilinos/cmake/tribits/core/package_arch/TribitsAddExecutable.cmake:417 (TRIBITS_PROCESS_COMM_ARGS)
  packages/external/trilinos/cmake/tribits/core/package_arch/TribitsAddExecutableAndTest.cmake:68 (TRIBITS_ADD_EXECUTABLE)
  packages/external/trilinos/cmake/tribits/core/package_arch/TribitsAddExecutableAndTest.cmake:214 (TRIBITS_ADD_EXECUTABLE_WRAPPER)
  packages/external/trilinos/packages/rol/adapters/teuchos/test/vector/CMakeLists.txt:1 (TRIBITS_ADD_EXECUTABLE_AND_TEST)
```
I probably have some contradictory setting in my build, so will have to attempt a clean one, later.

**Comment by dridzal** [comment]
@briadam , thanks, for now we would just like to see if the issue is present in your build.  It did not exist in older versions of MSVS.  Since LBFGS is a popular Hessian approximation, it's quite important to ensure it works with all systems and compilers.  We can't reproduce the issue with gnu, clang or intel.

**Comment by briadam** [comment]
Sounds good. We don't build the ROL tests or examples in our Dakota build and it seems our Trilinos snapshot is missing some needed TriBITS foo. I'll do a full clone of Trilinos and build clean on MSVS and let you know what I find.

**Comment by tbinford** [comment]
@briadam You may need to add /D_USE_MATH_DEFINES to CMAKE_CXX_FLAGS otherwise things like M_PI aren't understood in MSVS.

**Comment by tbinford** [comment]
@briadm This is one problem I've encountered building some ROL examples cmath in MSVS.

**Comment by briadam** [comment]
Yes @tbinford I ran into the same compilation issue, which we can either resolve by setting compiler flags or maybe through the preprocessor, depending on ROL policy. I read your note about the same time as I worked about it!

**Comment by briadam** [comment]
> Sounds good. We don't build the ROL tests or examples in our Dakota build and it seems our Trilinos snapshot is missing some needed TriBITS foo. I'll do a full clone of Trilinos and build clean on MSVS and let you know what I find.

@dridzal Sorry for the delay. I struggled to get a full build of standalone Trilinos/ROL that day as I use static blas/lapack libs built with Intel on Windows and haven't yet found an easy way to coerce the ROL build to link all the necessary libs. I was able to build on test target manually, but now have to go back and get my whole build going.

**Comment by dridzal** [comment]
@trilinos/framework : What's the status of MSVS support for Trilinos?  There were several efforts in the past.  We can make changes to ROL to get around some of the MSVS requirements, but a per-package MSVS policy doesn't make much sense to me.

**Comment by briadam** [comment]
I'm interested in the broader answer Denis. FWIW, there was only one localized compile issue. The Windows work-around could go something like this:
```
diff --git a/packages/rol/src/zoo/testproblems/ROL_HS9.hpp b/packages/rol/src/zoo/testproblems/ROL_HS9.hpp
index 801aeea311..1ab403bdf1 100644
--- a/packages/rol/src/zoo/testproblems/ROL_HS9.hpp
+++ b/packages/rol/src/zoo/testproblems/ROL_HS9.hpp
@@ -50,6 +50,10 @@
 #ifndef ROL_HS9_HPP
 #define ROL_HS9_HPP

+// Needed for M_PI on MSVS 2015; perhaps include upstream before first math.h/cmath inclusion?
+#define _USE_MATH_DEFINES
+#include <math.h>
+
 #include "ROL_StdVector.hpp"
 #include "ROL_TestProblem.hpp"
 #include "ROL_Types.hpp"
```

Protected by a Windows conditional, probably. However, you could fix that test by just hard-coding a value for PI, until you migrate to C++20, which has proper math constants. We (Dakota) are grateful that you don't require C++20. ;-)

**Comment by briadam** [comment]
Using MSVS 2015, Intel Fortran 2017, with static BLAS/LAPACK Windows libraries from netlib, I get **70/70 CTest tests passing**. 

NOTE: When I set ROL_ENABLE_EXAMPLES, I get an additional 16 instances of M_PI not being defined, as well as two related to `feenableexcept(FE_DIVBYZERO | FE_INVALID | FE_OVERFLOW);` which might be due to missing fenv.h, or it's possible these weren't part of the C standard, only an extension.

However, **the examples you asked me to run seem to be working**:
```
C:\local\trilinos\build\packages\rol\tutorial>"C:\Program Files\CMake\bin"\ctest -C Release
Test project C:/local/trilinos/build/packages/rol/tutorial
    Start 1: ROL_tutorial_BoundAndInequality
1/2 Test #1: ROL_tutorial_BoundAndInequality ...   Passed    0.42 sec
    Start 2: ROL_tutorial_Unconstrained
2/2 Test #2: ROL_tutorial_Unconstrained ........   Passed    0.34 sec

100% tests passed, 0 tests failed out of 2
```

Let me know if anything else would help.

**Comment by dridzal** [comment]
@briadam , thanks!!  This is very helpful.  Are you using the Intel compiler with MSVS?

**Comment by briadam** [comment]
Yes. While it's not strictly necessary to build Teuchos numerics and link to BLAS/LAPACK on Windows, it's how my Windows Dakota build is setup, so I used in the Trilinos + ROL build for you. We build Dakota's Fortran modules with Intel Fortran 2017, then link against reference BLAS/LAPACK implementations built with same. For consistency, we just force Trilinos to enable Fortran and link everything with any Fortran dependence against the Intel Fortran runtime libs.

**Comment by tbinford** [comment]
@briadam Would you mind sharing your CMake setup? Are you using CMake-GUI? I'm particularly interested in how you are setting the BLAS and LAPACK directories in CMake. The GUI seems to be ignoring whatever I give it. So, I've had to resort to hacking the CMake cache file to successfully generate a solution.

I have both clapack and Intel Fortran libraries.

**Comment by tbinford** [comment]
@briadam Were you able to build ROL_example_PinT_tanks_example01? I am getting the following error with MSVS 2017 C++ compiler.

1>d:\software\surface_lwd\dev7.1\thirdparty\trilinos\12.18.x\trilinos\packages\rol\example\pint\tanks\Tanks_DynamicConstraint.hpp(136): error C2512: 'ROL::DynamicConstraint<Real>': no appropriate default constructor available

**Comment by briadam** [comment]
> Would you mind sharing your CMake setup? Are you using CMake-GUI?

Sure @tbinford, for better or worse I use this batch script fragment:
```
"C:\Program Files\CMake\bin\cmake.exe" -G "Visual Studio 14 2015" -D BUILD_SHARED_LIBS=FALSE -DROL_ENABLE_TESTS:BOOL=ON -DROL_ENABLE_EXAMPLES:BOOL=TRUE  -DTrilinos_ENABLE_TESTS:BOOL=OFF -DTrilinos_ENABLE_Teuchos:BOOL=ON -DTrilinos_ENABLE_ROL:BOOL=ON -DTrilinos_ENABLE_ALL_PACKAGES:BOOL=OFF -DTrilinos_ENABLE_ALL_FORWARD_DEP_PACKAGES:BOOL=OFF -DTrilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=OFF -DTrilinos_ENABLE_COMPLEX_DOUBLE:BOOL=ON -DTPL_BLAS_LIBRARIES=C:/local/lapack/3.5.0/BLAS.lib -DTrilinos_ENABLE_Fortran:BOOL=ON -DTPL_LAPACK_LIBRARIES=C:/local/lapack/3.5.0/LAPACK.lib -DTrilinos_ENABLE_TeuchosKokkosCompat:BOOL=OFF -DTrilinos_ENABLE_TeuchosKokkosCore:BOOL=OFF -D CMAKE_EXE_LINKER_FLAGS="/LIBPATH:C:\local\intel_libs ifconsol.lib libifcoremd.lib libifportmd.lib libmmd.lib libirc.lib svml_disp.lib" C:/local/trilinos/Trilinos
```

This is to link against the [Netlib-provided reference BLAS/LAPACK libraries (Intel static](https://icl.cs.utk.edu/lapack-for-windows/lapack/)), which is also why I have Fortran enabled, so the name mangling convention will match.

**Comment by briadam** [comment]
> Were you able to build ROL_example_PinT_tanks_example01?

Yes, it appears that one built for me using Trilinos 33d2b9fc (which is a touch stale), with MSVS 2015. The example binary runs without error, but I have no idea if it's correct. Actually I take that back, the CTest tests in that directory (tanks) are clean.

**Comment by dridzal** [comment]
@briadam , I have to clarify a question from earlier:  Are you using an Intel compiler for *everything*, or the MSVS compiler for all things C/C++, and Intel/Fortran for Fortran.  In the past, I've only managed to get clean Trilinos builds using Intel throughout.

**Comment by briadam** [comment]
MSVS 2015 for C/C++ and Intel Visual Fortran 2017 for Fortran parts. All seems well with my build and test of ROL and Teuchos. I don't have Intel C++ installed on Windows and am not eager to poke the bear that is a working, if annoying, Windows build environment.

**Comment by tbinford** [comment]
@briadam Sorry to resurrect this thread. Did your system build Sacado when you enabled ROL?

**Comment by briadam** [comment]
Hi @tbinford the short answer is my build didn't include Sacado as I neuter my Trilinos build to the minimum possible (only Tecuhos, ROL, and required dependencies). I can try this out, but haven't had a chance. Just wanted to leave you some response though.
