### ISSUE TITLE
Tpetra:  Determine best default imbalance threshold for decision path in SpMV

### ISSUE THREAD

**Issue by kddevin** [trilinos/Trilinos#7617]
## Documentation
@trilinos/tpetra 

For #7569, we should (a) experiment to determine the best default value of the imbalance threshold parameter and (b) document benefit of this approach in SpMV for @vbrunini .  Results documenting both can be posted here.

**Comment by mhoemmen** [comment]
I'm personally curious whether Tpetra uses cuSPARSE's merge path sparse matrix-vector multiply in a CUDA build by default.

**Comment by kyungjoo-kim** [comment]
@brian-kelley @csiefer2 I do not think that we need to document this ourselves. The load imbalance factor is very application specific. Measuring arbitrary imbalance case does not help users. For general sparse matrices, NVIDIA merge path spmv paper would be sufficient. I would close this issue.
