### ISSUE TITLE
SEACAS Building issues

### ISSUE THREAD

**Issue by sivanadarajah** [trilinos/Trilinos#7627]
Good Afternoon, I have the exact same issue as (SEACAS Building issues, holding up Trilinos #4553). I am using macOS 10.15.5 and Xcode 11.5. Doing grep -i hdf5 CMakeCache.txt only gives me the following message.

//Enable EpetraExt interface support for HDF5. This interface requires
// an already installed HDF5 library; the include, the library
EpetraExt_USING_HDF5:BOOL=OFF
//Enable support for the TPL HDF5 in all supported Trilinos packages.
TPL_ENABLE_HDF5:STRING=
HAVE_EPETRAEXT_HDF5:INTERNAL=OFF
//STRINGS property for variable: TPL_ENABLE_HDF5
TPL_ENABLE_HDF5-STRINGS:INTERNAL=;ON;OFF

Thank you for the help.

Regards,
Siva

**Comment by cgcgcg** [comment]
I don't think SEACAS builds without HDF5. Have you tried `-D TPL_ENABLE_HDF5=ON`?

**Comment by sivanadarajah** [comment]
Thanks. I assumed that cmake would have automatically included it. I am currently using

  cmake \
  -DTPL_ENABLE_MPI=ON \
  -DTPL_ENABLE_Matio=OFF \
  -DMPI_BASE_DIR=/opt/local/include/openmpi-gcc6/ \
  -D Trilinos_ENABLE_Fortran=OFF \
  -DTrilinos_ENABLE_ALL_PACKAGES=ON \
  -DCMAKE_INSTALL_PREFIX=<path-to-Trilinos>

**Comment by gsjaardema** [comment]
You will need to specify the `HDF5_ROOT` and `NetCDF_ROOT` and optionally `PNetCDF_ROOT` (if parallel build) so that CMake can find the required third-party libraries.

**Comment by sivanadarajah** [comment]
Thanks for the tip. I have it included but it stops with the following error. 

  "_ompi_request_null", referenced from:
      _Zoltan_Comm_Do_Post in libzoltan.a(comm_do.c.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [packages/seacas/applications/nem_slice/nem_slice] Error 1
make[1]: *** [packages/seacas/applications/nem_slice/CMakeFiles/nem_slice.dir/all] Error 2

**Comment by gsjaardema** [comment]
Not sure.  Are you doing a parallel (MPI enabled) build, or a serial build?  What are your configuration options...

**Comment by cgcgcg** [comment]
@sivanadarajah Maybe you're `MPI_ROOT` is wrong? I believe `MPI_ROOT=blub` will look for MPI includes in `blub/include` and for MPI libs in `blub/lib`. Yours looks like it might only be includes? You can alternatively try setting `MPI_INCLUDE_DIRS` and `MPI_LIBRARY_DIRS`.

**Comment by gsjaardema** [comment]
No communication in over a year.  Please reopen if still an issue.
