### ISSUE TITLE
TriBITS:  CPack packaging behavior

### ISSUE THREAD

**Issue by briadam** [trilinos/Trilinos#7636]
## Question
@trilinos/TriBITS

Hi @bartlettroscoe (all interested),

In Dakota's CMake, we still configure Trilinos (Teuchos and ROL only) as a sub-project with add_subdirectory(). While we realize this isn't a supported use case, we've been able to do so until now with only minor patches. Last week we updated from Trilinos d2fcc2f to e9cb59b and are no longer able to `make package` (binary packaging, which I also realize may not be supported).

The behavior we (@rhoope and I) see with the newer Trilinos is that during packaging, instead of CPack performing the make install to a staging area in the build tree, it attempts to install the whole binary package into the CMAKE_INSTALL_PREFIX, which defaults to /usr/local, and therefore fails due to permissions.

Are you aware of any changes in Trilinos' use of TriBITS and/or TriBITS itself which could cause this problem? I combed over the diff between the two SHA1s for changes to CMAKE_INSTALL_PREFIX (perhaps a hard-override), changes to CPack usage and related CPACK_ variables, etc., but didn't see any obvious culprit.

Thanks for any insights you might have,
Brian

**Comment by bartlettroscoe** [comment]
@briadam, TriBITS is moving to use modern CMake using target-based properties.  The first step was PR tribitspub/TriBITS#300.  That would be my guess.

**Comment by briadam** [comment]
Thanks for the pointer @bartlettroscoe We too are migrating to more modern CMake target properties so appreciate that path and the challenges of migrating incrementally. At least with a brief look, I didn't see anything in TriBITSPub/TriBITS#300, or the corresponding Trilinos changes, that would affect packaging or make install. 

I am looking a bit more at TriBITSPub/TriBITS#314 and a couple other PRs too. If you think of anything else, do please let me know. I'll also post on CMake Discourse to see if there are other reasons CPack might be behaving this way and what CMake variables we might need to review.

**Comment by briadam** [comment]
I was able to narrow this down to TriBITSPub/TriBITS#314, specifically https://github.com/TriBITSPub/TriBITS/blob/master/tribits/core/installation/set_installed_group_and_permissions.cmake.in where CMAKE_INSTALL_PREFIX is modified during make install / make package when CPack calls cmake_install.cmake for the permission fixing sub-directory. This causes problems for our (contorted) use case as then CMAKE_INSTALL_PREFIX might be changed for other sub-projects that follow Trilinos.

Two thoughts on this in case helpful (realizing this may be better discussed in the TriBITS repo):

1. Should this permission fixing be happening during a make package (binary package)? Or only during a build tree make install? Might need some conditional protection to be skipped during CPack packaging.

1. It seems the permissions install script could use a local variable instead of CMAKE_INSTALL_PREFIX, but I don't know enough about your design intent to know for sure. FWIW, editing the variable name to sigap_CMAKE_INSTALL_PREFIX in that install script does still seem to work at least for our use case.

_(I realize Dakota's use case of building Trilinos under Dakota is not intended for TriBITS, so totally understand if you don't want to adjust this, since your assumption that the permissions fixing should be the last thing to happen in a TriBITS build is sound.)_

Also, will permission fixing be appropriately skipped on a Windows build, or is there a control by which I can turn it off in general? It appears to make some assumptions about Unix commands like stat, chmod, etc.

**Comment by bartlettroscoe** [comment]
@briadam, looking at the code in:

* https://github.com/TriBITSPub/TriBITS/pull/315/files#diff-1957825f47bb203e5d727da92c53e397

it looks like we can change the name of `CMAKE_INSTALL_PREFIX` to be something else.  I think I named it that because that is what it was but if it causes problems for Dakota, we can change it.

I did not realize the `CMAKE_INSTALL_PREFIX` was actually used in the generated ``

I will change this in TriBITS and submit a Trilinos PR to update TriBITS in Trilinos.

> Also, will permission fixing be appropriately skipped on a Windows build, or is there a control by which I can turn it off in general? It appears to make some assumptions about Unix commands like stat, chmod, etc.

I don't know how this would work with Windows.  You would need to add a Windows-specific function to handle these issues.

But we have used the existing TriBITS/Trilinos install logic for 12+ years and did not have a problem until some very special use cases related to ATDM that drove https://github.com/TriBITSPub/TriBITS/issues/314.

**Comment by briadam** [comment]
Okay sounds good. FWIW, this was my quick hack that is currently committed to Dakota's snapshot and seems to work, granted with a pretty terrible variable name... :
```
diff --git a/trilinos/cmake/tribits/core/installation/set_installed_group_and_permissions.cmake.in b/trilinos/cmake/
index 4e54447..c34b2f4 100644
--- a/trilinos/cmake/tribits/core/installation/set_installed_group_and_permissions.cmake.in
+++ b/trilinos/cmake/tribits/core/installation/set_installed_group_and_permissions.cmake.in
@@ -77,7 +77,7 @@ IF (EXISTS "${projectInstallBaseDir}")
   SET(dirPath "${projectInstallBaseDir}")
   IF (numSubDirs EQUAL 0)
     # The base dir is CMAKE_INSTALL_PREFIX
-    SET(CMAKE_INSTALL_PREFIX "${dirPath}")
+    SET(sigap_CMAKE_INSTALL_PREFIX "${dirPath}")
   ELSE()
     # Non-recursive set of the group and permissions
     SET_DIR_OWNER_AND_PERMS("${dirPath}" "")
@@ -87,11 +87,11 @@ IF (EXISTS "${projectInstallBaseDir}")
     ENDFOREACH()
     # Append last subdir which gives CMAKE_INSTALL_PREFIX
     LIST(GET projectSubdirPathsArray -1 lastSubdir)
-    SET(CMAKE_INSTALL_PREFIX "${dirPath}/${lastSubdir}")
+    SET(sigap_CMAKE_INSTALL_PREFIX "${dirPath}/${lastSubdir}")
  ENDIF()
 
   # Recursive set of group and permsisions on CMAKE_INSTALL_PREFIX
-  SET_DIR_OWNER_AND_PERMS("${CMAKE_INSTALL_PREFIX}" "-R")
+  SET_DIR_OWNER_AND_PERMS("${sigap_CMAKE_INSTALL_PREFIX}" "-R")
 
 ELSE()
 ```

**Comment by briadam** [comment]
With respect to Windows, I more meant is there logic in TriBITS to **skip** the invocation of this post-install step on Windows? Because it seems like it could break there. It looked to me like it is included unconditionally when setting up TriBITS installation targets and helpers.

I will have an empirical test of this on Windows shortly and can post back.

**Comment by bartlettroscoe** [comment]
> With respect to Windows, I more meant is there logic in TriBITS to skip the invocation of this post-install step on Windows?

Yes, see the if statement at:

* https://github.com/TriBITSPub/TriBITS/pull/315/files#diff-b97da7727987a32971621310e5081e14R44

There are several customers that use TriBITS on Windows so I am careful to consider Windows (when I stray out outside of basic CMake).

**Comment by bartlettroscoe** [comment]
FYI: The PR #7642 should fix this.  Just needs to pass PR testing and a Trilinos developer needs to approve.

**Comment by briadam** [comment]
Thanks for the quick engagement and fix @bartlettroscoe Much appreciated! 

I found some related issues with Trilinos packages hard-coding ${CMAKE_INSTALL_PREFIX} in their install rules, but they aren't immediate blockers, so I'll collect those up and post a separate issue when I do.
