### ISSUE TITLE
Seacas: Ioex problem

### ISSUE THREAD

**Issue by ZhongshengSang** [trilinos/Trilinos#7637]
When I do the ./do-config...  step, the program reminds me that these packages I installed are totally not used and return as follow:

CMake Warning:
  Manually-specified variables were not used by the project:

    Boost_INCLUDE_DIRS
    HDF5_NO_SYSTEM_PATHS
    HDF5_ROOT
    NetCDF_ROOT
    PNetCDF_ROOT
    SuperLU_INCLUDE_DIRS
    SuperLU_LIBRARY_DIRS

Then comes the error which caused the failure of installation as follow:

/home/zsl1990/nalu_build_dir/packages/Trilinos/packages/seacas/libraries/ioss/src/main/io_modify.C: In function 'void {anonymous}::update_exodus_assembly_info(Ioss::Region&, const Modify::Interface&)':
/home/zsl1990/nalu_build_dir/packages/Trilinos/packages/seacas/libraries/ioss/src/main/io_modify.C:1185:17: error: 'Ioex' was not declared in this scope
     std::vector<Ioex::Assembly> ex_assemblies;
                 ^
/home/zsl1990/nalu_build_dir/packages/Trilinos/packages/seacas/libraries/ioss/src/main/io_modify.C:1185:31: error: template argument 1 is invalid
     std::vector<Ioex::Assembly> ex_assemblies;
                               ^
/home/zsl1990/nalu_build_dir/packages/Trilinos/packages/seacas/libraries/ioss/src/main/io_modify.C:1185:31: error: template argument 2 is invalid
/home/zsl1990/nalu_build_dir/packages/Trilinos/packages/seacas/libraries/ioss/src/main/io_modify.C:1185:46: error: invalid type in declaration before ';' token
     std::vector<Ioex::Assembly> ex_assemblies;
                                              ^
/home/zsl1990/nalu_build_dir/packages/Trilinos/packages/seacas/libraries/ioss/src/main/io_modify.C:1193:23: error: request for member 'emplace_back' in 'ex_assemblies', which is of non-class type 'int'
         ex_assemblies.emplace_back(*assembly);
                       ^
/home/zsl1990/nalu_build_dir/packages/Trilinos/packages/seacas/libraries/ioss/src/main/io_modify.C:1223:7: error: 'Ioex' is not a class, namespace, or enumeration
       Ioex::Internals::update_assembly_data(out_exoid, ex_assemblies, 1);
       ^
/home/zsl1990/nalu_build_dir/packages/Trilinos/packages/seacas/libraries/ioss/src/main/io_modify.C:1224:7: error: 'Ioex' is not a class, namespace, or enumeration
       Ioex::Internals::copy_database(exoid, out_exoid);
       ^
/home/zsl1990/nalu_build_dir/packages/Trilinos/packages/seacas/libraries/ioss/src/main/io_modify.C:1225:7: error: 'Ioex' is not a class, namespace, or enumeration
       Ioex::Internals::update_assembly_data(out_exoid, ex_assemblies, 2);
       ^
/home/zsl1990/nalu_build_dir/packages/Trilinos/packages/seacas/libraries/ioss/src/main/io_modify.C:1226:7: error: 'Ioex' is not a class, namespace, or enumeration
       Ioex::write_reduction_attributes(exoid, attributes_modified);
       ^
/home/zsl1990/nalu_build_dir/packages/Trilinos/packages/seacas/libraries/ioss/src/main/io_modify.C:1241:7: error: 'Ioex' is not a class, namespace, or enumeration
       Ioex::Internals::update_assembly_data(exoid, ex_assemblies);
       ^
/home/zsl1990/nalu_build_dir/packages/Trilinos/packages/seacas/libraries/ioss/src/main/io_modify.C:1242:7: error: 'Ioex' is not a class, namespace, or enumeration
       Ioex::write_reduction_attributes(exoid, attributes_modified);
       ^

Ioex does not found. What should I do to deal with it? Is that normal all these packages not used in the configure step?

Thanks for your help!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by jhux2** [comment]
@trilinos/seacas

**Comment by gsjaardema** [comment]
It is not normal that those symbols are not used.  If they are not used, then the Exodus library in SEACAS will not be enabled which will not enable the Ioex library in IOSS library and most of SEACAS will be not used.  If you do not want the SEACAS libraries or applications, then you should disable SEACAS; if you do want the SEACAS libraries and applications, then there is something in your configuration that is disabling part of SEACAS.   

The Ioex issue should not happen and I will fix that, but I think it is indicative of a problem in your Trilinos configuration...

**Comment by gsjaardema** [comment]
Note that #7640 fixes the build such that `io_modify` will build when Exodus is not enabled; however, I think that Nalu requires that exodus and IOSS be enabled in Trilinos, so I think you will probably have different issues even after #7640 is merged.

**Comment by jhux2** [comment]
@ZhongshengSang I missed the fact that you appear to be building Trilinos for Nalu.  Here's a configure script that I use for Nalu-Wind, which is based on Nalu.  One minor note, there's no compelling reason to use SuperLU in Nalu.  You could disable it and instead use KLU2.

```
ARGS=(
    -GNinja
    -D BUILD_SHARED_LIBS:BOOL=TRUE
    -D CMAKE_INSTALL_PREFIX:PATH="${trilinos_install_dir}"
    -D CMAKE_BUILD_TYPE:STRING=$BUILD_TYPE
    -D CMAKE_CXX_FLAGS:STRING="${CXX_WARNINGS}"
    -D Trilinos_ENABLE_CXX11:BOOL=ON
    -D Trilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=OFF
    -D Trilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON
    -D Trilinos_ENABLE_TESTS:BOOL=OFF
    -D Trilinos_ALLOW_NO_PACKAGES:BOOL=OFF
    -D Trilinos_ASSERT_MISSING_PACKAGES:BOOL=OFF
    -D Trilinos_ENABLE_Amesos:BOOL=OFF
    -D Trilinos_ENABLE_Amesos2:BOOL=ON
    -D   Amesos2_ENABLE_SuperLU:BOOL=ON
    -D   Amesos2_ENABLE_KLU2:BOOL=OFF
    -D Trilinos_ENABLE_SuperLU5_API:BOOL=OFF
    -D Trilinos_ENABLE_AztecOO:BOOL=OFF
    -D Trilinos_ENABLE_Belos:BOOL=ON
    -D Trilinos_ENABLE_Epetra:BOOL=OFF
    -D Trilinos_ENABLE_EpetraExt:BOOL=OFF
    -D Trilinos_ENABLE_Gtest:BOOL=ON
    -D Trilinos_ENABLE_Ifpack:BOOL=OFF
    -D Trilinos_ENABLE_Ifpack2:BOOL=ON
    -D Trilinos_ENABLE_ML:BOOL=OFF
    -D Trilinos_ENABLE_MueLu:BOOL=ON
    -D Trilinos_ENABLE_SEACASExodus:BOOL=ON
    -D Trilinos_ENABLE_SEACASEpu:BOOL=ON
    -D Trilinos_ENABLE_SEACASExodiff:BOOL=ON
    -D Trilinos_ENABLE_SEACASNemspread:BOOL=ON
    -D Trilinos_ENABLE_SEACASNemslice:BOOL=ON
    -D Trilinos_ENABLE_SEACASIoss:BOOL=ON
    -D Trilinos_ENABLE_STK:BOOL=ON
    -D Trilinos_ENABLE_Tpetra:BOOL=ON
    #-D   Tpetra_INST_INT_LONG:BOOL=ON
    -D   Tpetra_INST_DOUBLE:BOOL=ON
    -D   Tpetra_INST_COMPLEX_DOUBLE:BOOL=OFF
    -D Trilinos_ENABLE_Zoltan:BOOL=ON
    -D Trilinos_ENABLE_Zoltan2:BOOL=ON
    -D   BoostLib_INCLUDE_DIRS:PATH="${SEMS_BOOST_ROOT}/include"
    -D   BoostLib_LIBRARY_DIRS:PATH="${SEMS_BOOST_ROOT}/lib"
    -D   Boost_INCLUDE_DIRS:PATH="${SEMS_BOOST_ROOT}/include"
    -D   Boost_LIBRARY_DIRS:PATH="${SEMS_BOOST_ROOT}/lib"
    -D TPL_ENABLE_HDF5:BOOL=ON
    -D   HDF5_DIR:PATH="${SEMS_HDF5_ROOT}"
    -D TPL_ENABLE_MPI:BOOL=ON
    -D   MPI_BASE_DIR:PATH="${SEMS_OPENMPI_ROOT}"
    -D TPL_ENABLE_Netcdf:BOOL=ON
    -D   Netcdf_INCLUDE_DIRS:PATH="${SEMS_NETCDF_ROOT}/include"
    -D   Netcdf_LIBRARY_DIRS:PATH="${SEMS_NETCDF_ROOT}/lib"
    -D TPL_Netcdf_PARALLEL:BOOL=ON
    -D TPL_ENABLE_Pnetcdf:BOOL=ON
    -D   Pnetcdf_INCLUDE_DIRS:PATH="${SEMS_NETCDF_ROOT}/include"
    -D   Pnetcdf_LIBRARY_DIRS:PATH="${SEMS_NETCDF_ROOT}/lib"
    -D TPL_ENABLE_SuperLU:BOOL=ON
    -D   SuperLU_INCLUDE_DIRS:PATH="${SEMS_SUPERLU_ROOT}/include"
    -D   SuperLU_LIBRARY_DIRS:PATH="${SEMS_SUPERLU_ROOT}/lib"
    -DTPL_BLAS_LIBRARIES=/usr/lib64/libblas.so.3.4.2
    -DTPL_LAPACK_LIBRARIES=/usr/lib64/liblapack.so.3.4.2
)

cmake "${ARGS[@]}" $EXTRA_ARGS $trilinos_source_dir
```

**Comment by ZhongshengSang** [comment]
wow, thanks jhux2. It works for me
