### ISSUE TITLE
Zoltan does not seem to build if TPL_ENABLE_METIS defined

### ISSUE THREAD

**Issue by gsjaardema** [trilinos/Trilinos#765]
I have an experimental decomp tool in seacas that uses the metis (not parmetis) library.  If I define TPL_ENABLE_METIS in the cmake configuration, my build breaks because Zoltan sees that flag and seems to assume that I have parmetis.

For example, in parmetis_interface.c, the compilation will error out if PARMETIS_MAJOR_VERSION is not defined (which it isn't if I only have Metis).

Should zoltan be buildable with just Metis and not Parmetis?

**Comment by kddevin** [comment]
@gsjaardema The intent is that Zoltan can work with only METIS, so some fixes were needed.   I pushed them to Trilinos' develop branch today.

Are you accessing METIS through Zoltan?  Or do you have your own interface to METIS?

**Comment by gsjaardema** [comment]
I am accessing METIS directly.  It is a code that needs to be able to
handle >2 billion entties on a single processor and (at the time it was
written at least), zoltan cannot handle that on a single processor.

Thanks for the quick fix.  I will try it out.

..Greg

**Comment by kddevin** [comment]
I'll close this issue for now; please re-open if the fixes are insufficient.
Thanks for reporting, @gsjaardema .
