### ISSUE TITLE
Installation Error:  "_H5get_libversion"

### ISSUE THREAD

**Issue by debasishuiuc** [trilinos/Trilinos#7664]
I have a similar problem installing Trilinos that was closed last year but no solution was provided. "SEACAS Building issues, holding up Trilinos #4553" 

https://github.com/trilinos/Trilinos/issues/4553

I have followed the steps described there and did make Verbose =1. Please note that I have installed hdf5 and netcdf using home-brew. Kindly help me.

Debasishs-MacBook-Pro:exo_format debasish$ make VERBOSE=1
cd /Users/debasish/Desktop/hpcsoft/Trilinos-master/mybuilt && /usr/local/Cellar/cmake/3.17.3/bin/cmake -S/Users/debasish/Desktop/hpcsoft/Trilinos-master -B/Users/debasish/Desktop/hpcsoft/Trilinos-master/mybuilt --check-build-system CMakeFiles/Makefile.cmake 0
cd /Users/debasish/Desktop/hpcsoft/Trilinos-master/mybuilt && /usr/local/Cellar/cmake/3.17.3/bin/cmake -E cmake_progress_start /Users/debasish/Desktop/hpcsoft/Trilinos-master/mybuilt/CMakeFiles /Users/debasish/Desktop/hpcsoft/Trilinos-master/mybuilt/packages/seacas/applications/exo_format/CMakeFiles/progress.marks
cd /Users/debasish/Desktop/hpcsoft/Trilinos-master/mybuilt && /Library/Developer/CommandLineTools/usr/bin/make  -f CMakeFiles/Makefile2 packages/seacas/applications/exo_format/all
/Library/Developer/CommandLineTools/usr/bin/make  -f packages/seacas/libraries/exodus/CMakeFiles/exodus.dir/build.make packages/seacas/libraries/exodus/CMakeFiles/exodus.dir/depend
cd /Users/debasish/Desktop/hpcsoft/Trilinos-master/mybuilt && /usr/local/Cellar/cmake/3.17.3/bin/cmake -E cmake_depends "Unix Makefiles" /Users/debasish/Desktop/hpcsoft/Trilinos-master /Users/debasish/Desktop/hpcsoft/Trilinos-master/packages/seacas/libraries/exodus /Users/debasish/Desktop/hpcsoft/Trilinos-master/mybuilt /Users/debasish/Desktop/hpcsoft/Trilinos-master/mybuilt/packages/seacas/libraries/exodus /Users/debasish/Desktop/hpcsoft/Trilinos-master/mybuilt/packages/seacas/libraries/exodus/CMakeFiles/exodus.dir/DependInfo.cmake --color=
/Library/Developer/CommandLineTools/usr/bin/make  -f packages/seacas/libraries/exodus/CMakeFiles/exodus.dir/build.make packages/seacas/libraries/exodus/CMakeFiles/exodus.dir/build
[  0%] Linking C shared library libexodus.dylib
cd /Users/debasish/Desktop/hpcsoft/Trilinos-master/mybuilt/packages/seacas/libraries/exodus && /usr/local/Cellar/cmake/3.17.3/bin/cmake -E cmake_link_script CMakeFiles/exodus.dir/link.txt --verbose=1
/Users/debasish/mpi/bin/mpicc -O3 -DNDEBUG -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -dynamiclib -Wl,-headerpad_max_install_names -compatibility_version 12.0.0 -current_version 12.17.0 -o libexodus.12.17.dylib -install_name @rpath/libexodus.12.dylib CMakeFiles/exodus.dir/src/ex__put_homogenous_block_params.c.o CMakeFiles/exodus.dir/src/ex_add_attr.c.o CMakeFiles/exodus.dir/src/ex_close.c.o CMakeFiles/exodus.dir/src/ex_conv.c.o CMakeFiles/exodus.dir/src/ex_copy.c.o CMakeFiles/exodus.dir/src/ex_create.c.o CMakeFiles/exodus.dir/src/ex_create_group.c.o CMakeFiles/exodus.dir/src/ex_create_par.c.o CMakeFiles/exodus.dir/src/ex_cvt_nodes_to_sides.c.o CMakeFiles/exodus.dir/src/ex_err.c.o CMakeFiles/exodus.dir/src/ex_get_all_times.c.o CMakeFiles/exodus.dir/src/ex_get_assemblies.c.o CMakeFiles/exodus.dir/src/ex_get_assembly.c.o CMakeFiles/exodus.dir/src/ex_get_attr.c.o CMakeFiles/exodus.dir/src/ex_get_attr_names.c.o CMakeFiles/exodus.dir/src/ex_get_attr_param.c.o CMakeFiles/exodus.dir/src/ex_get_attribute.c.o CMakeFiles/exodus.dir/src/ex_get_blob.c.o CMakeFiles/exodus.dir/src/ex_get_blobs.c.o CMakeFiles/exodus.dir/src/ex_get_block.c.o CMakeFiles/exodus.dir/src/ex_get_block_param.c.o CMakeFiles/exodus.dir/src/ex_get_block_params.c.o CMakeFiles/exodus.dir/src/ex_get_cmap_params.c.o CMakeFiles/exodus.dir/src/ex_get_concat_sets.c.o CMakeFiles/exodus.dir/src/ex_get_concat_side_set_node_count.c.o CMakeFiles/exodus.dir/src/ex_get_conn.c.o CMakeFiles/exodus.dir/src/ex_get_coord.c.o CMakeFiles/exodus.dir/src/ex_get_coord_names.c.o CMakeFiles/exodus.dir/src/ex_get_coordinate_frames.c.o CMakeFiles/exodus.dir/src/ex_get_eb_info_global.c.o CMakeFiles/exodus.dir/src/ex_get_elem_cmap.c.o CMakeFiles/exodus.dir/src/ex_get_elem_type.c.o CMakeFiles/exodus.dir/src/ex_get_entity_count_per_polyhedra.c.o CMakeFiles/exodus.dir/src/ex_get_glob_var_time_int.c.o CMakeFiles/exodus.dir/src/ex_get_glob_vars_int.c.o CMakeFiles/exodus.dir/src/ex_get_group_id.c.o CMakeFiles/exodus.dir/src/ex_get_group_ids.c.o CMakeFiles/exodus.dir/src/ex_get_id_map.c.o CMakeFiles/exodus.dir/src/ex_get_ids.c.o CMakeFiles/exodus.dir/src/ex_get_info.c.o CMakeFiles/exodus.dir/src/ex_get_init.c.o CMakeFiles/exodus.dir/src/ex_get_init_ext.c.o CMakeFiles/exodus.dir/src/ex_get_init_global.c.o CMakeFiles/exodus.dir/src/ex_get_init_info.c.o CMakeFiles/exodus.dir/src/ex_get_loadbal_param.c.o CMakeFiles/exodus.dir/src/ex_get_map.c.o CMakeFiles/exodus.dir/src/ex_get_map_param.c.o CMakeFiles/exodus.dir/src/ex_get_name.c.o CMakeFiles/exodus.dir/src/ex_get_names.c.o CMakeFiles/exodus.dir/src/ex_get_nodal_var_int.c.o CMakeFiles/exodus.dir/src/ex_get_nodal_var_time_int.c.o CMakeFiles/exodus.dir/src/ex_get_node_cmap.c.o CMakeFiles/exodus.dir/src/ex_get_ns_param_global.c.o CMakeFiles/exodus.dir/src/ex_get_num_map.c.o CMakeFiles/exodus.dir/src/ex_get_object_truth_vector.c.o CMakeFiles/exodus.dir/src/ex_get_one_attr.c.o CMakeFiles/exodus.dir/src/ex_get_partial_attr.c.o CMakeFiles/exodus.dir/src/ex_get_partial_conn.c.o CMakeFiles/exodus.dir/src/ex_get_partial_coord.c.o CMakeFiles/exodus.dir/src/ex_get_partial_coord_component.c.o CMakeFiles/exodus.dir/src/ex_get_partial_id_map.c.o CMakeFiles/exodus.dir/src/ex_get_partial_nodal_var_int.c.o CMakeFiles/exodus.dir/src/ex_get_partial_num_map.c.o CMakeFiles/exodus.dir/src/ex_get_partial_one_attr.c.o CMakeFiles/exodus.dir/src/ex_get_partial_set.c.o CMakeFiles/exodus.dir/src/ex_get_partial_set_dist_fact.c.o CMakeFiles/exodus.dir/src/ex_get_partial_var.c.o CMakeFiles/exodus.dir/src/ex_get_processor_elem_maps.c.o CMakeFiles/exodus.dir/src/ex_get_processor_node_maps.c.o CMakeFiles/exodus.dir/src/ex_get_prop.c.o CMakeFiles/exodus.dir/src/ex_get_prop_array.c.o CMakeFiles/exodus.dir/src/ex_get_prop_names.c.o CMakeFiles/exodus.dir/src/ex_get_qa.c.o CMakeFiles/exodus.dir/src/ex_get_reduction_variable_name.c.o CMakeFiles/exodus.dir/src/ex_get_reduction_variable_names.c.o CMakeFiles/exodus.dir/src/ex_get_reduction_variable_param.c.o CMakeFiles/exodus.dir/src/ex_get_reduction_vars.c.o CMakeFiles/exodus.dir/src/ex_get_set.c.o CMakeFiles/exodus.dir/src/ex_get_set_dist_fact.c.o CMakeFiles/exodus.dir/src/ex_get_set_param.c.o CMakeFiles/exodus.dir/src/ex_get_sets.c.o CMakeFiles/exodus.dir/src/ex_get_side_set_node_count.c.o CMakeFiles/exodus.dir/src/ex_get_side_set_node_list.c.o CMakeFiles/exodus.dir/src/ex_get_side_set_node_list_len.c.o CMakeFiles/exodus.dir/src/ex_get_ss_param_global.c.o CMakeFiles/exodus.dir/src/ex_get_time.c.o CMakeFiles/exodus.dir/src/ex_get_truth_table.c.o CMakeFiles/exodus.dir/src/ex_get_var.c.o CMakeFiles/exodus.dir/src/ex_get_var_time.c.o CMakeFiles/exodus.dir/src/ex_get_variable_name.c.o CMakeFiles/exodus.dir/src/ex_get_variable_names.c.o CMakeFiles/exodus.dir/src/ex_get_variable_param.c.o CMakeFiles/exodus.dir/src/ex_inquire.c.o CMakeFiles/exodus.dir/src/ex_int_get_block_param.c.o CMakeFiles/exodus.dir/src/ex_ne_util.c.o CMakeFiles/exodus.dir/src/ex_open.c.o CMakeFiles/exodus.dir/src/ex_open_par.c.o CMakeFiles/exodus.dir/src/ex_opts.c.o CMakeFiles/exodus.dir/src/ex_put_all_var_param.c.o CMakeFiles/exodus.dir/src/ex_put_all_var_param_ext.c.o CMakeFiles/exodus.dir/src/ex_put_assemblies.c.o CMakeFiles/exodus.dir/src/ex_put_assembly.c.o CMakeFiles/exodus.dir/src/ex_put_attr.c.o CMakeFiles/exodus.dir/src/ex_put_attr_names.c.o CMakeFiles/exodus.dir/src/ex_put_attr_param.c.o CMakeFiles/exodus.dir/src/ex_put_attribute.c.o CMakeFiles/exodus.dir/src/ex_put_blob.c.o CMakeFiles/exodus.dir/src/ex_put_blobs.c.o CMakeFiles/exodus.dir/src/ex_put_block.c.o CMakeFiles/exodus.dir/src/ex_put_block_param.c.o CMakeFiles/exodus.dir/src/ex_put_block_params.c.o CMakeFiles/exodus.dir/src/ex_put_cmap_params.c.o CMakeFiles/exodus.dir/src/ex_put_cmap_params_cc.c.o CMakeFiles/exodus.dir/src/ex_put_concat_all_blocks.c.o CMakeFiles/exodus.dir/src/ex_put_concat_elem_block.c.o CMakeFiles/exodus.dir/src/ex_put_concat_sets.c.o CMakeFiles/exodus.dir/src/ex_put_conn.c.o CMakeFiles/exodus.dir/src/ex_put_coord.c.o CMakeFiles/exodus.dir/src/ex_put_coord_names.c.o CMakeFiles/exodus.dir/src/ex_put_coordinate_frames.c.o CMakeFiles/exodus.dir/src/ex_put_eb_info_global.c.o CMakeFiles/exodus.dir/src/ex_put_elem_cmap.c.o CMakeFiles/exodus.dir/src/ex_put_entity_count_per_polyhedra.c.o CMakeFiles/exodus.dir/src/ex_put_id_map.c.o CMakeFiles/exodus.dir/src/ex_put_info.c.o CMakeFiles/exodus.dir/src/ex_put_init.c.o CMakeFiles/exodus.dir/src/ex_put_init_ext.c.o CMakeFiles/exodus.dir/src/ex_put_init_global.c.o CMakeFiles/exodus.dir/src/ex_put_init_info.c.o CMakeFiles/exodus.dir/src/ex_put_loadbal_param.c.o CMakeFiles/exodus.dir/src/ex_put_loadbal_param_cc.c.o CMakeFiles/exodus.dir/src/ex_put_map.c.o CMakeFiles/exodus.dir/src/ex_put_map_param.c.o CMakeFiles/exodus.dir/src/ex_put_name.c.o CMakeFiles/exodus.dir/src/ex_put_names.c.o CMakeFiles/exodus.dir/src/ex_put_nodal_var.c.o CMakeFiles/exodus.dir/src/ex_put_nodal_var_int.c.o CMakeFiles/exodus.dir/src/ex_put_node_cmap.c.o CMakeFiles/exodus.dir/src/ex_put_ns_param_global.c.o CMakeFiles/exodus.dir/src/ex_put_num_map.c.o CMakeFiles/exodus.dir/src/ex_put_one_attr.c.o CMakeFiles/exodus.dir/src/ex_put_partial_attr.c.o CMakeFiles/exodus.dir/src/ex_put_partial_conn.c.o CMakeFiles/exodus.dir/src/ex_put_partial_coord.c.o CMakeFiles/exodus.dir/src/ex_put_partial_coord_component.c.o CMakeFiles/exodus.dir/src/ex_put_partial_id_map.c.o CMakeFiles/exodus.dir/src/ex_put_partial_nodal_var_int.c.o CMakeFiles/exodus.dir/src/ex_put_partial_num_map.c.o CMakeFiles/exodus.dir/src/ex_put_partial_one_attr.c.o CMakeFiles/exodus.dir/src/ex_put_partial_set.c.o CMakeFiles/exodus.dir/src/ex_put_partial_set_dist_fact.c.o CMakeFiles/exodus.dir/src/ex_put_partial_var.c.o CMakeFiles/exodus.dir/src/ex_put_processor_elem_maps.c.o CMakeFiles/exodus.dir/src/ex_put_processor_node_maps.c.o CMakeFiles/exodus.dir/src/ex_put_prop.c.o CMakeFiles/exodus.dir/src/ex_put_prop_array.c.o CMakeFiles/exodus.dir/src/ex_put_prop_names.c.o CMakeFiles/exodus.dir/src/ex_put_qa.c.o CMakeFiles/exodus.dir/src/ex_put_reduction_variable_name.c.o CMakeFiles/exodus.dir/src/ex_put_reduction_variable_names.c.o CMakeFiles/exodus.dir/src/ex_put_reduction_variable_param.c.o CMakeFiles/exodus.dir/src/ex_put_reduction_vars.c.o CMakeFiles/exodus.dir/src/ex_put_set.c.o CMakeFiles/exodus.dir/src/ex_put_set_dist_fact.c.o CMakeFiles/exodus.dir/src/ex_put_set_param.c.o CMakeFiles/exodus.dir/src/ex_put_sets.c.o CMakeFiles/exodus.dir/src/ex_put_ss_param_global.c.o CMakeFiles/exodus.dir/src/ex_put_time.c.o CMakeFiles/exodus.dir/src/ex_put_truth_table.c.o CMakeFiles/exodus.dir/src/ex_put_var.c.o CMakeFiles/exodus.dir/src/ex_put_variable_name.c.o CMakeFiles/exodus.dir/src/ex_put_variable_names.c.o CMakeFiles/exodus.dir/src/ex_put_variable_param.c.o CMakeFiles/exodus.dir/src/ex_update.c.o CMakeFiles/exodus.dir/src/ex_utils.c.o CMakeFiles/exodus.dir/src/deprecated/ex_get_concat_node_sets.c.o CMakeFiles/exodus.dir/src/deprecated/ex_get_concat_side_sets.c.o CMakeFiles/exodus.dir/src/deprecated/ex_get_elem_attr.c.o CMakeFiles/exodus.dir/src/deprecated/ex_get_elem_attr_names.c.o CMakeFiles/exodus.dir/src/deprecated/ex_get_elem_blk_ids.c.o CMakeFiles/exodus.dir/src/deprecated/ex_get_elem_block.c.o CMakeFiles/exodus.dir/src/deprecated/ex_get_elem_conn.c.o CMakeFiles/exodus.dir/src/deprecated/ex_get_elem_map.c.o CMakeFiles/exodus.dir/src/deprecated/ex_get_elem_num_map.c.o CMakeFiles/exodus.dir/src/deprecated/ex_get_elem_var.c.o CMakeFiles/exodus.dir/src/deprecated/ex_get_elem_var_tab.c.o CMakeFiles/exodus.dir/src/deprecated/ex_get_elem_var_time.c.o CMakeFiles/exodus.dir/src/deprecated/ex_get_glob_var_time.c.o CMakeFiles/exodus.dir/src/deprecated/ex_get_glob_vars.c.o CMakeFiles/exodus.dir/src/deprecated/ex_get_n_attr.c.o CMakeFiles/exodus.dir/src/deprecated/ex_get_n_conn.c.o CMakeFiles/exodus.dir/src/deprecated/ex_get_n_coord.c.o CMakeFiles/exodus.dir/src/deprecated/ex_get_n_elem_attr.c.o CMakeFiles/exodus.dir/src/deprecated/ex_get_n_elem_conn.c.o CMakeFiles/exodus.dir/src/deprecated/ex_get_n_elem_num_map.c.o CMakeFiles/exodus.dir/src/deprecated/ex_get_n_elem_var.c.o CMakeFiles/exodus.dir/src/deprecated/ex_get_n_nodal_var.c.o CMakeFiles/exodus.dir/src/deprecated/ex_get_n_node_num_map.c.o CMakeFiles/exodus.dir/src/deprecated/ex_get_n_node_set.c.o CMakeFiles/exodus.dir/src/deprecated/ex_get_n_node_set_df.c.o CMakeFiles/exodus.dir/src/deprecated/ex_get_n_one_attr.c.o CMakeFiles/exodus.dir/src/deprecated/ex_get_n_side_set.c.o CMakeFiles/exodus.dir/src/deprecated/ex_get_n_side_set_df.c.o CMakeFiles/exodus.dir/src/deprecated/ex_get_n_var.c.o CMakeFiles/exodus.dir/src/deprecated/ex_get_nodal_var.c.o CMakeFiles/exodus.dir/src/deprecated/ex_get_nodal_var_time.c.o CMakeFiles/exodus.dir/src/deprecated/ex_get_node_map.c.o CMakeFiles/exodus.dir/src/deprecated/ex_get_node_num_map.c.o CMakeFiles/exodus.dir/src/deprecated/ex_get_node_set.c.o CMakeFiles/exodus.dir/src/deprecated/ex_get_node_set_dist_fact.c.o CMakeFiles/exodus.dir/src/deprecated/ex_get_node_set_ids.c.o CMakeFiles/exodus.dir/src/deprecated/ex_get_node_set_param.c.o CMakeFiles/exodus.dir/src/deprecated/ex_get_nset_var.c.o CMakeFiles/exodus.dir/src/deprecated/ex_get_nset_var_tab.c.o CMakeFiles/exodus.dir/src/deprecated/ex_get_one_elem_attr.c.o CMakeFiles/exodus.dir/src/deprecated/ex_get_partial_elem_attr.c.o CMakeFiles/exodus.dir/src/deprecated/ex_get_partial_elem_conn.c.o CMakeFiles/exodus.dir/src/deprecated/ex_get_partial_elem_map.c.o CMakeFiles/exodus.dir/src/deprecated/ex_get_partial_elem_num_map.c.o CMakeFiles/exodus.dir/src/deprecated/ex_get_partial_elem_var.c.o CMakeFiles/exodus.dir/src/deprecated/ex_get_partial_nodal_var.c.o CMakeFiles/exodus.dir/src/deprecated/ex_get_partial_node_num_map.c.o CMakeFiles/exodus.dir/src/deprecated/ex_get_partial_node_set.c.o CMakeFiles/exodus.dir/src/deprecated/ex_get_partial_node_set_df.c.o CMakeFiles/exodus.dir/src/deprecated/ex_get_partial_side_set.c.o CMakeFiles/exodus.dir/src/deprecated/ex_get_partial_side_set_df.c.o CMakeFiles/exodus.dir/src/deprecated/ex_get_side_set.c.o CMakeFiles/exodus.dir/src/deprecated/ex_get_side_set_dist_fact.c.o CMakeFiles/exodus.dir/src/deprecated/ex_get_side_set_ids.c.o CMakeFiles/exodus.dir/src/deprecated/ex_get_side_set_param.c.o CMakeFiles/exodus.dir/src/deprecated/ex_get_sset_var.c.o CMakeFiles/exodus.dir/src/deprecated/ex_get_sset_var_tab.c.o CMakeFiles/exodus.dir/src/deprecated/ex_get_var_name.c.o CMakeFiles/exodus.dir/src/deprecated/ex_get_var_names.c.o CMakeFiles/exodus.dir/src/deprecated/ex_get_var_param.c.o CMakeFiles/exodus.dir/src/deprecated/ex_get_var_tab.c.o CMakeFiles/exodus.dir/src/deprecated/ex_put_concat_node_sets.c.o CMakeFiles/exodus.dir/src/deprecated/ex_put_concat_side_sets.c.o CMakeFiles/exodus.dir/src/deprecated/ex_put_concat_var_param.c.o CMakeFiles/exodus.dir/src/deprecated/ex_put_elem_attr.c.o CMakeFiles/exodus.dir/src/deprecated/ex_put_elem_attr_names.c.o CMakeFiles/exodus.dir/src/deprecated/ex_put_elem_block.c.o CMakeFiles/exodus.dir/src/deprecated/ex_put_elem_conn.c.o CMakeFiles/exodus.dir/src/deprecated/ex_put_elem_map.c.o CMakeFiles/exodus.dir/src/deprecated/ex_put_elem_num_map.c.o CMakeFiles/exodus.dir/src/deprecated/ex_put_elem_var.c.o CMakeFiles/exodus.dir/src/deprecated/ex_put_elem_var_slab.c.o CMakeFiles/exodus.dir/src/deprecated/ex_put_elem_var_tab.c.o CMakeFiles/exodus.dir/src/deprecated/ex_put_glob_vars.c.o CMakeFiles/exodus.dir/src/deprecated/ex_put_n_attr.c.o CMakeFiles/exodus.dir/src/deprecated/ex_put_n_coord.c.o CMakeFiles/exodus.dir/src/deprecated/ex_put_n_elem_attr.c.o CMakeFiles/exodus.dir/src/deprecated/ex_put_n_elem_conn.c.o CMakeFiles/exodus.dir/src/deprecated/ex_put_n_elem_num_map.c.o CMakeFiles/exodus.dir/src/deprecated/ex_put_n_nodal_var.c.o CMakeFiles/exodus.dir/src/deprecated/ex_put_n_node_num_map.c.o CMakeFiles/exodus.dir/src/deprecated/ex_put_n_node_set.c.o CMakeFiles/exodus.dir/src/deprecated/ex_put_n_node_set_df.c.o CMakeFiles/exodus.dir/src/deprecated/ex_put_n_one_attr.c.o CMakeFiles/exodus.dir/src/deprecated/ex_put_n_side_set.c.o CMakeFiles/exodus.dir/src/deprecated/ex_put_n_side_set_df.c.o CMakeFiles/exodus.dir/src/deprecated/ex_put_n_var.c.o CMakeFiles/exodus.dir/src/deprecated/ex_put_nodal_var_slab.c.o CMakeFiles/exodus.dir/src/deprecated/ex_put_node_map.c.o CMakeFiles/exodus.dir/src/deprecated/ex_put_node_num_map.c.o CMakeFiles/exodus.dir/src/deprecated/ex_put_node_set.c.o CMakeFiles/exodus.dir/src/deprecated/ex_put_node_set_dist_fact.c.o CMakeFiles/exodus.dir/src/deprecated/ex_put_node_set_param.c.o CMakeFiles/exodus.dir/src/deprecated/ex_put_nset_var.c.o CMakeFiles/exodus.dir/src/deprecated/ex_put_nset_var_tab.c.o CMakeFiles/exodus.dir/src/deprecated/ex_put_one_elem_attr.c.o CMakeFiles/exodus.dir/src/deprecated/ex_put_partial_elem_attr.c.o CMakeFiles/exodus.dir/src/deprecated/ex_put_partial_elem_conn.c.o CMakeFiles/exodus.dir/src/deprecated/ex_put_partial_elem_map.c.o CMakeFiles/exodus.dir/src/deprecated/ex_put_partial_elem_num_map.c.o CMakeFiles/exodus.dir/src/deprecated/ex_put_partial_nodal_var.c.o CMakeFiles/exodus.dir/src/deprecated/ex_put_partial_node_num_map.c.o CMakeFiles/exodus.dir/src/deprecated/ex_put_partial_node_set.c.o CMakeFiles/exodus.dir/src/deprecated/ex_put_partial_node_set_df.c.o CMakeFiles/exodus.dir/src/deprecated/ex_put_partial_side_set.c.o CMakeFiles/exodus.dir/src/deprecated/ex_put_partial_side_set_df.c.o CMakeFiles/exodus.dir/src/deprecated/ex_put_side_set.c.o CMakeFiles/exodus.dir/src/deprecated/ex_put_side_set_dist_fact.c.o CMakeFiles/exodus.dir/src/deprecated/ex_put_side_set_param.c.o CMakeFiles/exodus.dir/src/deprecated/ex_put_sset_var.c.o CMakeFiles/exodus.dir/src/deprecated/ex_put_sset_var_tab.c.o CMakeFiles/exodus.dir/src/deprecated/ex_put_var_name.c.o CMakeFiles/exodus.dir/src/deprecated/ex_put_var_names.c.o CMakeFiles/exodus.dir/src/deprecated/ex_put_var_param.c.o CMakeFiles/exodus.dir/src/deprecated/ex_put_var_tab.c.o  /usr/local/lib/libnetcdf.dylib 
Undefined symbols for architecture x86_64:
  "_H5get_libversion", referenced from:
      _ex_print_config in ex_utils.c.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [packages/seacas/libraries/exodus/libexodus.12.17.dylib] Error 1
make[1]: *** [packages/seacas/libraries/exodus/CMakeFiles/exodus.dir/all] Error 2
make: *** [all] Error 2

**Comment by cgcgcg** [comment]
Could you post your cmake configuration and the configure log?

**Comment by debasishuiuc** [comment]
[CMakeCache.txt](https://github.com/trilinos/Trilinos/files/4907609/CMakeCache.txt)

**Comment by debasishuiuc** [comment]
Is this the file you are looking for? Sorry, I am not very proficient with cmake

**Comment by cgcgcg** [comment]
```
//Enable support for the TPL HDF5 in all supported Trilinos packages.
//  This can be set to 'ON', 'OFF', or left empty ''.
TPL_ENABLE_HDF5:STRING=
```
Try setting `-D TPL_ENABLE_HDF5=ON`.

**Comment by gsjaardema** [comment]
The `libnetcdf.dylib` should automatically pull in the hdf5 libraries that are needed.  Not sure why this isn't working correctly -- Maybe the brew installed netcdf library wasn't build with HDF5 support. 

You can run the `/usr/local/bin/nc-config --all` and see if it has HDF5 support...

**Comment by debasishuiuc** [comment]
Thank you. This is what I get. It appears netCDF has HDF5 support.

/usr/local/bin/nc-config --all

This netCDF 4.7.4 has been built with the following features: 

  --cc            -> /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang
  --cflags        -> -I/usr/local/Cellar/netcdf/4.7.4_1/include
  --libs          -> -L/usr/local/Cellar/netcdf/4.7.4_1/lib -lnetcdf
  --static        -> -lhdf5_hl -lhdf5 -lsz -lz -ldl -lm -lcurl

  --has-c++       -> no
  --cxx           -> 

  --has-c++4      -> yes
  --cxx4          -> /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++
  --cxx4flags     -> -I/usr/local/Cellar/netcdf/4.7.4_1/include
  --cxx4libs      -> -L/usr/local/Cellar/netcdf/4.7.4_1/lib -lnetcdf-cxx4 -lnetcdf

  --has-fortran   -> yes
  --fc            -> /usr/local/bin/gfortran
  --fflags        -> /usr/local/Cellar/netcdf/4.7.4_1/include
  --flibs         -> -L/usr/local/Cellar/netcdf/4.7.4_1/lib
  --has-f90       -> TRUE
  --has-f03       -> FALSE

  --has-dap       -> yes
  --has-dap2      -> yes
  --has-dap4      -> yes
  --has-nc2       -> yes
  --has-nc4       -> yes
  --has-hdf5      -> yes
  --has-hdf4      -> no
  --has-logging   -> no
  --has-pnetcdf   -> no
  --has-szlib     -> no
  --has-cdf5      -> yes
  --has-parallel4 -> no
  --has-parallel  -> no

  --prefix        -> /usr/local/Cellar/netcdf/4.7.4_1
  --includedir    -> /usr/local/Cellar/netcdf/4.7.4_1/include
  --libdir        -> /usr/local/Cellar/netcdf/4.7.4_1/lib
  --version       -> netCDF 4.7.4

**Comment by debasishuiuc** [comment]
Hello, I have been able to install it on linux pretty easily as the apt-get packages are readily available. I have not been able to make it work on macOS still. Thank you for your time.
