### ISSUE TITLE
Belos: Incorrect use of a reduction in CG single reduction solver

### ISSUE THREAD

**Issue by hyungyukang** [trilinos/Trilinos#7680]
## Bug Report
@trilinos/Belos

### Description
When using the Belos - single reduction CG solver with a convergence folding option, a residual (`rHr_`) is using an incorrect array index.

Code: `Trilinos/packages/belos/src/BelosCGSingleRedIter.hpp`
```
    if (foldConvergenceDetectionIntoAllreduce_) {
      // Compute first <S_,T_> a.k.a. <R_,Z_>, <AZ_,Z_> and <R_,R2_> combined (also computes unneeded <AZ_,R2_>)
      MVT::Assign( *R_, *R2_ );
      MVT::MvTransMv( one, *S_, *T_, sHt );
      rHz_ = sHt(0,0);
      delta = sHt(1,0);
      rHr_ = sHt(1,1);
    } else {
```

In the code, `rHr_ = sHt(1,1);` should be changed to `rHr_ = sHt(0,1);`, since `sHt(1,1)` is a scalar for a dummy reduction '<AZ_,R2>' (see the comment line).

That incorrect index of the residual causes slower convergence of the solver.
I checked the number of iterations by comparing the standard CG solver in Trilinos (without any preconditioner).
After fix the index from `sHt(1,1)` to `sHt(0,1)`, the number of iterations becomes almost the same.

**Comment by jhux2** [comment]
@trilinos/belos @iyamazaki
