### ISSUE TITLE
Tpetra:  CrsMatrix fails to compile when LocalOrdinal != int

### ISSUE THREAD

**Issue by klevzoff** [trilinos/Trilinos#7695]
## Bug Report
@trilinos/tpetra

### Description
Hi,

I've encountered a couple compilation errors when trying to instantiate and use `Tpetra::CrsMatrix<>` template with `LocalOrdinal = std::ptrdiff_t` (which on my system resolves to `long int`). The errors reproduced on 12.18.1 release, but relevant code is still there in master branch. The errors were observed from a large code base, but I can try to make a minimal reproducer, if needed.

1. 
```
Tpetra_CrsMatrix_def.hpp:1133:41: error: operands to ?: have different types ‘Tpetra::CrsMatrix<double, long int, long long int>::local_matrix_type’ {aka ‘KokkosSparse::CrsMatrix<double, long int, Kokkos::OpenMP, void, long unsigned int>’} and ‘const local_matrix_type’ {aka ‘const KokkosSparse::CrsMatrix<double, int, Kokkos::OpenMP, void, long unsigned int>’}
     return lclMatrix_.get () == nullptr ?
Tpetra_CrsMatrix_def.hpp:1133:41: note:   and each type can be converted to the other
```
stemming from this piece of code:
https://github.com/trilinos/Trilinos/blob/9c0318f30ff284869ba160d851adaa45e09afe21/packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp#L1035-L1043
where 
```
using local_matrix_type =
      KokkosSparse::CrsMatrix<matrix_scalar_type,
                              local_ordinal_type,
                              execution_space,
                              void,
                              typename local_graph_type::size_type>;
```
The issue is that in the `CrsMatrix`, `local_ordinal_type` is an alias for `LocalOrdinal` (the template parameter of the matrix), but in `LocalCrsMatrixOperator` (the type pointed to by `lclMatrix_`) it aliases `Tpetra::Details::DefaultTypes::local_ordinal_type` (which is hardcoded to `int`). 

The compiler hints at conversion, but my understanding is that would invoke a deep copy via `KokkosSparse::CrsMatrix`'s [conversion constructor](https://docs.trilinos.org/dev/packages/kokkos/doc/html/classKokkos_1_1CrsMatrix.html#ae4e491881a1b9207b0d305080be0cae8), were I to try and convert the second return value in the ternary. I'm not sure what the best way around it is. Perhaps I'm misunderstanding something?

I'm also getting some other related errors (e.g. in `Tpetra::CrsMatrix::fillLocalMatrix()`), but those are buried under a whole stack of `std::shared_ptr` stuff and are harder to parse. The fundamental problem is the same: `LocalCrsMatrixOperator` doesn't know about `LocalOrdinal` and uses a different type for the actual Kokkos object it wraps.

2. 
```
Tpetra_CrsMatrix_def.hpp:9650:69: error: operands to ?: have different types ‘Teuchos::ArrayView<const int>’ and ‘Teuchos::ArrayView<const long int>’
         Teuchos::ArrayView<const LO>   ELID1 = MyImporter.is_null() ? Teuchos::ArrayView<const int>() : MyImporter->getExportLIDs();
```
related to this:
https://github.com/trilinos/Trilinos/blob/9c0318f30ff284869ba160d851adaa45e09afe21/packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp#L9605
Here a simple fix would be to replace `ArrayView<const int>` with `ArrayView<const LO>` in the rhs expression. It looks like that's what was intended there.

### Steps to Reproduce
1. SHA1:  55a75997332636a28afc9db1aee4ae46fe8d93e7 (aka `trilinos-release-12-18-1` tag)
1. Configure script: [trilinos_config.txt](https://github.com/trilinos/Trilinos/files/4951388/trilinos_config.txt)
1. Configure log: [trilinos_configure.log](https://github.com/trilinos/Trilinos/files/4951415/trilinos_configure.log)
1. Try to instantiate and use `Tpetra::CrsMatrix<double, std::ptrdiff_t, long long int>`

**Comment by mayrmt** [comment]
@trilinos/tpetra

**Comment by brian-kelley** [comment]
@klevzoff We only support LocalOrdinal=int now. The fact that it's still a template parameter is deprecated and will go away at some point. Do you have > 2^31 local rows or local columns in your matrix? Note that entries aren't indexed with LocalOrdinal (that's size_t), so you could have e.g. 1 billion local rows and 100 entries per row if you really wanted to.

**Comment by kddevin** [comment]
@brian-kelley is correct; the template parameter is going away.  We do not test with LocalOrdinal != int.
That said, the fix is simple, as you indicated.  Thanks!  We will push the fix to the repository.  See #7699

**Comment by tjfulle** [comment]
It was my understanding that, while the Local ordinal template parameter will be removed, the local ordinal type would be a typedef and not necessarily locked in to a certain underlying type.  Though, `int` would be the default and only tested local ordinal type.

**Comment by kddevin** [comment]
PR #7699 is merged into the develop branch.  I will close this issue, but please re-open if the PR does not fix your problem.

**Comment by klevzoff** [comment]
Hi everyone, thank you for the quick response and fix. I wasn't aware that `LocalOrdinal` template parameter was being deprecated. It certainly makes sense now. 

The reason I wanted to specify a local index type other than `int` was because we do thread-parallel fill into our own CRS data structure and the plan is to eventually use `CrsMatrix`'s [constructor](https://docs.trilinos.org/dev/packages/tpetra/doc/html/classTpetra_1_1CrsMatrix.html#a7bf35faa1344c19e0989768d64dcd344) that takes pre-baked CRS arrays, for which we would like to wrap non-owning `Kokkos::View`s around our data structure's arrays and thus make the Tpetra matrix construction copy-free (not having to duplicate matrix storage, especially on the GPU, is nice).

Our data structure is templated on the index type, but because it is used in conjunction with more than one linear algebra package, we are using our own local index type (which currently aliases `std::ptrdiff_t`), and try to make all LA backends be directly compatible with this index type, either via build-time options, or in case of Tpetra, via template parameters. This plan is not set in stone and we're still evaluating its feasibility.

In this regard, if the `LocalOrdinal` template parameter ends up being deprecated/removed, it would be great if `Tpetra::Details::DefaultTypes::local_ordinal_type` had a build-time option for using a different type (not that there's anything wrong with `int`). At the moment, this is not a huge problem though.
