### ISSUE TITLE
Tpetra: should FECrsGraph node ownership debug check be relaxed?

### ISSUE THREAD

**Issue by bartgol** [trilinos/Trilinos#7697]
## Question
@trilinos/tpetra 

Currently, there's a check performed by FECrsGraph during the call to `doOwnedPlusSharedToOwned`, which, if not successful, prints the error message:

```
"if you own an element (in the finite element sense) you "
"must also own one of the attached nodes.  This assumption has been violated in "
"your matrix fill."
```

However, this check seems a bit restrictive for folks that receive meshes partitioned by other tools. If you consider an unstructured triangular mesh, a partitioning will likely generate a zig-zagged border. It is not unlikely that one element might have all nodes belonging to the other process.

Yes, one could probably work out some rebalancing routine, to adjust these scenarios. However, it might take some work, and in some cases it might require diving into some complex data structures (e.g., stk meshes). Is there a reason why Tpetra should not like the idea of a rank owning an element without owning any of its nodes? After all, Tpetra does not even know what a mesh is, so why should it care about who owns (mesh) elements? Upon assembly, the matrix is exactly the same (modulo possibly some changes in the column map LIDs), regardless of who owned the element to start with.

**Comment by csiefer2** [comment]
We did that on purpose to guarantee map validity.   If you don't have that, you can create circumstances where the maps don't nest.  W ich means your maybe will be wrong.

One I page the details back into my brain, we can discuss what additional pinky swears we'll need about the mesh to allow you violate that assumption safely.

**Comment by csiefer2** [comment]
Now I remember!  Any row you assemble into will be in the column map.   If you own an element that's attached to that row, then that's OK.  That guy needs to be in your column map to do a matvec.

If you have some random element unrelated to the rest, those dogs you never need will also be stuck in your column map, almost certainly causing completely uneccesary communication.


I suspect I could add an option to let you carry on regardless, but there will be a performance cost.

**Comment by mperego** [comment]
Well, but it should not be up to Tpetra to judge whether a graph is performant or not, as long as it is legit. I think it is fair to throw a warning, but not to error out. 
Also, in the zig-zagged interface case depicted by Luca, even changing the ownership of the offending triangle to avoid that corner case, you would still have, most likely, two of the three dofs of the triangle to be shared nodes.

**Comment by bartgol** [comment]
@mperego, I believe that if you fix the triangle, then the column map will be the smallest col map possible (i.e., all GIDs in the col map are indeed needed by some row).

@csiefer2 I think Tpetra should only issue warnings when things may incur a performance hit due to poor setup. For some application, the number of "useless" GIDs in the col map may end up being fairly small (compared to the overall map size), that the effort of redistributing the mesh nodes ownership may not be worth the perf gain.

I think perhaps we could reach a compromise: we could stick something in the ctor parameter list, to give the user the ability to *explicitly* disable this check, or maybe turn it into a warning (probably still best to let the user know, in case they forget about what they explicitly requested).

I could put up a micro PR with this change, if you think it's a reasonable compromise.

**Comment by mperego** [comment]
Would it be possible to count the number of such bad dofs in debug mode, so that we can give a more informative warning message? 

My understanding is that we end up in this situation using SEACAS decomp tool. Depending on how bad is the performance loss, we might want to check with SEACAS team and see if there is (or they are willing to provide) a decomp option to prevent this to happen.

**Comment by bartgol** [comment]
@mperego I think  that's relatively easy to do.

@csiefer2 Would you  be ok if I put up a pr that a) checks the graph param list to see if the user requested to allow owned elems without owned nodes, and b) improves the error message by specifying which GIDs in the col map are not in the owned row map?

**Comment by csiefer2** [comment]
@bartgol Sounds fine by me.
