### ISSUE TITLE
Amesos: What parallel sparse direct solvers are available/maintained? 

### ISSUE THREAD

**Issue by JustinClough** [trilinos/Trilinos#7708]
## Question
@trilinos/amesos
@trilinos/amesos2

> What are you wondering about?  

What is the current list of available and maintained parallel sparse direct solvers? For TPLs, what versions need to have been installed? 

>What has you confused?  

There is conflicting and dated information about what direct solvers Trilinos has implemented. Some examples:
 - Paraklete is mentioned [here](https://trilinos.github.io/amesos-paraklete-install) and [here](https://trilinos.github.io/amesos.html) but according to [this](https://github.com/trilinos/Trilinos/blob/005c680226e214a6536cee867f5e11eff731c92e/packages/amesos/CMakeLists.txt#L19) it has been removed
 - According to [this page](https://trilinos.github.io/amesos.html) SuperLU_Dist v 2.5 is part of Amesos, but #6892 mentions versions 5.4 and 6.2 as part of Amesos2
 - [This page](https://trilinos.github.io/linear_solver.html#amesos-direct-sparse-linear-solver-interface) says that both Amesos and Amesos2 have serial sparse direct solvers but only Amesos has a parallel one (Paraklete).

>What answers do you need?  

A list of the available parallel sparse direct solvers implemented in Trilinos and corresponding version numbers for TPLs. 

> What are you trying to accomplish?  

@assad-oberai and I have been using Albany to model some problems of interest. Due to features of the problems, it's better for us to use direct solvers instead of iterative. I have been using SuperLU, which worked well, but now need a solver that scales well due to increasing problem size.

>How does your question fit into what you're trying to do?

A parallel sparse direct solver would really help me take the next steps in my project. Knowing which solvers are available would help in both choosing the best solver for my situation and installing it.

**Comment by jhux2** [comment]
@trilinos/amesos @trilinos/amesos2

**Comment by srajama1** [comment]
@JustinClough @assad-oberai: Paraklete was way before my time in Trilinos (10 years). My understanding was the solver was not completed for all intended use cases. It should be removed from the documentation.  We test with SuperLU-Dist 5.4 as mentioned in #6892. If you can use it you should use that.

As that same issue mentions, 6.x changed data structures, which means we need to change Trilinos as well. This could be done. If you are willing to do it and contribute, I can help. This has been in our backlog. There is no application push to move to 6.x from our side yet.

The page that says Amesos and Amesos2 has serial solvers is correct. As I mentioned above, Paraklete was a research effort that started and never finished to my knowledge. I wouldn't rely on it.

You could also use MUMPS with Amesos2, but this is not in our nightly tests. There are some issues that we know such as options we don't support in MUMPS.

**Comment by JustinClough** [comment]
Thanks @srajama1, this really helps. I'll focus on getting SuperLU_Dist v5.4 installed and linked for my problem of interest. 

I would love to help updating Trilinos to use v6.x but I just don't have the time right now. I'd also have to see if there are any new features in v6.x that I need. I will keep it in mind and on my todo list for the future!

**Comment by JustinClough** [comment]
@srajama1: On the machines that test with SuperLU_Dist v5.4.0, how exactly is that library configured? I'm still having some issues getting my installation working. Would you be able to send tarballs of that machine's SuperLU_Dist and CombBLAS directories?
