### ISSUE TITLE
Epetra: Segmentation fault when utilizing initialization list for Epetra_Map & Epetra_CrsMatrix

### ISSUE THREAD

**Issue by syaskovets** [trilinos/Trilinos#7709]
## Bug Report
@trilinos/epetra

### Description
In my use case scenario Epetra_CrsMatrix and Epetra_Map are being declared as class attributes (not via pointers). When using an initialization list, Epetra_Map object is instantiated first, and then next passed on to a constructor of Epetra_CrsMatrix. It causes a segfault. Output (for the snippet below):
```
[c77ad7ab992d:18893] *** Process received signal ***
[c77ad7ab992d:18893] Signal: Segmentation fault (11)
[c77ad7ab992d:18893] Signal code:  (128)
[c77ad7ab992d:18893] Failing at address: (nil)
[c77ad7ab992d:18893] [ 0] /lib/x86_64-linux-gnu/libc.so.6(+0x354b0)[0x7f12a2ed54b0]
[c77ad7ab992d:18893] [ 1] /usr/local/lib/libepetra.so.12(_ZN15Epetra_BlockMapC1ERKS_+0x12)[0x7f12a3b5dba2]
[c77ad7ab992d:18893] [ 2] /usr/local/lib/libepetra.so.12(_ZN17Epetra_DistObjectC2ERK15Epetra_BlockMapPKc+0x39)[0x7f12a3bb1f99]
[c77ad7ab992d:18893] [ 3] /usr/local/lib/libepetra.so.12(_ZN16Epetra_CrsMatrixC1E17Epetra_DataAccessRK10Epetra_Mapib+0x51)[0x7f12a3b90e71]
[c77ad7ab992d:18893] [ 4] ./trilinos(_ZN11TestInvalidC1EiRK14Epetra_MpiComm+0x3b)[0x401351]
[c77ad7ab992d:18893] [ 5] ./trilinos(main+0x8b)[0x4011d1]
[c77ad7ab992d:18893] [ 6] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0)[0x7f12a2ec0830]
[c77ad7ab992d:18893] [ 7] ./trilinos(_start+0x29)[0x401079]
[c77ad7ab992d:18893] *** End of error message ***
```
If, on the contrary, Epetra_CrsMatrix is declared and instantiated in the constructor body itself, the problem disappears.  

### Steps to Reproduce
Below is a much simplified code that reproduces the bug:

```
class TestInvalid {
  Epetra_CrsMatrix mat;
  Epetra_Map map;
public:
  TestInvalid(int N, const Epetra_MpiComm& comm): map(N, 0, comm), mat(Copy, map, 3) {}
};

class TestValid
{
  Epetra_Map map;
public:
  TestValid(int N, const Epetra_MpiComm& comm): map(N, 0, comm) { Epetra_CrsMatrix mat(Copy, map, 3); }  
};

int main(int argc, char *argv[])
{
  MPI_Init(&argc,&argv);
  Epetra_MpiComm Comm(MPI_COMM_WORLD);
  TestValid t_v(81, Comm);
  TestInvalid t_i(81, Comm);
  MPI_Finalize() ;
}
```
As far as I could trace out, map object passed in the init list has its BlockMapData_ pointing to `0x1`, while the same map object in the following constructor body is pointing to something more reasonable like `0x1627....`. I am not sure what might be the reason though.

**Comment by jhux2** [comment]
@trilinos/epetra

**Comment by vbrunini** [comment]
You declared the matrix before the map in the class definition, and initialization list entries are processed in order of member declarations, not the order you list them in the initialization list.

**Comment by syaskovets** [comment]
Yes, you are totally right. For some reason I was sure that it should be the order of the initialization list. Thank you!
