### ISSUE TITLE
MueLu: Where to implement unit tests for InterfaceAggregationFactory?

### ISSUE THREAD

**Issue by mayrmt** [trilinos/Trilinos#7716]
## Question
@trilinos/muelu 

While working on MG for BlockedCrsMatrices coming from contact problems, I'd like to add some unit tests for the `InterfaceAggregationFactory` (for forming conforming aggregates at the interface in surface-coupled problems). Therefore, I'd like to reuse the `class AggregateGenerator` defined in the unit test file `Aggregates.cpp`. 

Shall I put my new tests into `Aggregates.cpp` (although they do not fit there very well) or can I move the `class AggregateGenerator` to the `MueLu::TestHelpers::AggregatesGenerator` in `MueLu_TestHelpers.{app,cpp}` and then implement new unit tests for interface aggregation in a separate file `InterfaceAggregation.cpp`?

Any preferences?

**Comment by jhux2** [comment]
@mayrmt I don't have a strong opinion.  If you think the interface aggregation is sufficiently different, then I see no problem with creating a new file for the tests and move the help to `MueLu_TestHelpers`.  Thanks.

**Comment by mayrmt** [comment]
Ok, I'll have a look and decide then.

Closing.
