### ISSUE TITLE
Tpetra: Add Tpetra vs Epetra test to performance dashboard

### ISSUE THREAD

**Issue by tasmith4** [trilinos/Trilinos#7719]
## Enhancement
@trilinos/tpetra 

@jhux2 or @csiefer2 -- there was some discussion about possibly having this live under MueLu -- should this issue be under that package instead?

**Comment by jhux2** [comment]
@tasmith4 Let's leave it as a Tpetra issue for now, even though the tests will live in MueLu.

**Comment by tasmith4** [comment]
somehow this never got closed when #7823 merged
