### ISSUE TITLE
Tpetra:  Design discussion of CrsGraph and CrsMatrix packing

### ISSUE THREAD

**Issue by kddevin** [trilinos/Trilinos#7721]
@trilinos/tpetra and especially @tjfulle 

## Discussion of packing routines
I started looking at packing because we were examining fences with @MichelDeMessieres in #7446.  We saw that some fences were not exercised in our testing.  I built with Tpetra, MueLu, Ifpack2 and Belos to see which packing functions are exercised in tests. 

My conclusions (**open to debate**):  
* we can remove four routines (negative lines of code, including two untested fences #7446)
* we should fix a bug in CrsGraph::packAndPrepare
* we should model CrsGraph's packing after CrsMatrix's packing, if possible
* we don't test RowGraph or RowMatrix packing

My questions are here; supporting details are below.  **Please add your thoughts.**

* Is it correct that CrsGraph::pack (and thus, Details::packCrsGraph and CrsGraph::packFillActive) are never called?  Can we remove Details::packCrsGraph, CrsGraph::packFillActive, and the implementation of CrsGraph::pack?

* Is it correct that Details::packCrsMatrix can be removed?

* Why does the decision to call Details::packCrsGraphNew instead of CrsGraph::packFillActiveNew depend on the structure of the this object (i.e., the target's colMap, lclGraph_) rather than the source?  (Suspect bug)

* What is the difference between CrsGraph::packFillActiveNew and Details::packCrsGraphNew?  Is there a performance benefit from doing packCrsGraphNew when possible?  What are the conditions for having valid lclGraph_ and colMap?

* Why doesn't Details::packCrsGraphNew call Impl::packCrsGraph (instead doing rather similar operations)?  What is the difference between Details::packCrsGraphNew and Impl::packCrsGraph?  

* What is the difference between Details::packCrsGraph and Details::packCrsGraphWithOwningPIDs?  (And if we agree that Details::packCrsGraph should go away, do we care?)

* Should CrsGraph packing follow same design pattern as CrsMatrix packing (one Details::Impl implementation with translation of arguments calling it)?  CrsMatrix's design pattern is cleaner.

* Should CrsGraph and CrsMatrix follow same naming convention (packFillActiveNew vs packNonStaticNew)?

### Graph Packing

**CrsGraph::packAndPrepare** 

* function required by DistObject interface
* decides whether to treat source graph as CrsGraph or RowGraph
* suspect bug in decision to call Details::packCrsGraphNew or CrsGraph::packFillActiveNew; using the this object's (i.e., the target graph's) info on colMap and lclGraph_ rather than the src graph's info.
* tested

**CrsGraph::pack**

* suspect that this function is not called in any circumstance
* when the src graph is a RowGraph but NOT a CrsGraph, src->pack() is called, but this call would exercise RowGraph::pack(), not CrsGraph::pack()
* calls packCrsGraph or packFillActive
* NOT tested 

**Details::packCrsGraph**

* called by CrsGraph::pack() if the this object has a column map and valid lclGraph_
* converts Teuchos::Array arguments to Kokkos::View, then calls Impl::packCrsGraph
* since suspect CrsGraph::pack() is not called in any circumstance, this function would not be called either
* NOT tested

**CrsGraph::packFillActive**

* called by CrsGraph::pack() if Details::packCrsGraph is not called
* similar to packFillActiveNew but with Teuchos::Arrays rather than Kokkos::Views
* input = arrays of exportLIDs, exports, numPacketsPerLID, Distributor
* since suspect CrsGraph::pack() is not called in any circumstance, this function would not be called either
* no doxygen documentation
* NOT tested

**Details::packCrsGraphNew**

* called if source argument to packAndPrepare is a CrsGraph, and the this object has a column map and valid lclGraph_
* very similar to Impl::packCrsGraph
* calls do_pack, which creates PackCrsGraphFunctor and does parallel pack
* tested

**CrsGraph::packFillActiveNew**

* called if source is CrsGraph and not calling Details::packCrsGraphNew
* input = Views of exportLIDs, exports, numPacketsPerLID, Distributor
* no doxygen documentation
* tested

**Details::packCrsGraphWithOwningPIDs**

* called by transferAndFillComplete
* looks like Details::packCrsGraph but with different input arguments
* converts Teuchos::Arrays to Kokkos::Views, then calls Impl::packCrsGraph
* tested

**Impl::packCrsGraph**

* called by Details::packCrsGraph and Details::packCrsGraphWithOwningPIDs, but not by Details::packCrsGraphNew
* calls do_pack, which creates PackCrsGraphFunctor and does parallel pack
* tested

**RowGraph::pack**

* provides a default implementation of pack for RowGraph
* should be called when RowGraph cannot be cast to CrsGaph
* NOT tested

### Matrix Packing

**CrsMatrix::packAndPrepare**

* determines whether source matrix argument is CrsMatrix or RowMatrix
* if CrsMatrix, calls packNew
* if RowMatrix, calls source->pack()
* tested

**CrsMatrix::packNew**

* called if src matrix argument to packAndPrepare is a CrsMatrix
* selects between Details::packCrsMatrixNew and CrsMatrix::packNonStaticNew, depending on whether the source matrix has static graph.  (Note that this decision differs from CrsGraph::packAndPrepare.  CrsMatrix has it correct, I think.)
* tested

**Details::packCrsMatrix**

* translates Teuchos::Array arguments to Kokkos::View, then
* calls Impl::packCrsMatrix
* tested but not used in the libraries; can probably be removed

**Details::packCrsMatrixNew**

* does syncs, error checking, etc., then
* calls Impl::packCrsMatrix
* tested

**Details::packCrsMatrixWithOwningPIDS**

* called by CrsMatrix::transferAndFillComplete
* translates Teuchos::Array arguments to Kokkos::View, then
* calls Impl::packCrsMatrix
* looks similar to Details::packCrsMatrix, except that it is actually used
* tested

**CrsMatrix::packNonStaticNew**

* called by CrsMatrix::packNew
* used to pack when the local matrix does not have a static graph
* tested

**Impl::packCrsMatrix**

* implementation that does the packing from local matrix
* called by Details::packCrsMatrix and Details::packCrsMatrixNew
* nice design -- the work gets done here and all others are wrappers
* tested

**RowMatrix::pack**

* generic packing routine for RowMatrix objects
* called by CrsMatrix::packAndPrepare when source matrix is not CrsMatrix but is RowMatrix
* NOT tested

## Testing needs

* Exercise default implementation of RowGraph::pack -- Transfer source RowGraph that does NOT have an underlying CrsGraph into a CrsGraph
* Exercise default implementation of RowMatrix::pack -- Transfer source RowMatrix that does NOT have an underlying CrsMatrix into a CrsMatrix

**Comment by tjfulle** [comment]
Great questions!

The existence of all the different pack routines (and probably unpack) is due, in part, to having different pack routines for static and dynamic profile, and different routines for const and non-const graph.  On top of that, there was the old interface and the new interface (with the `New` postfix).  Also, `exportAndFillComplete` packs things differently, and so it has its own set of packing/unpacking routines (though, maybe only for CrsMatrix?). Many of these can probably be removed.

I'll answer your questions in more detail in separate comments in the following couple of days.

**Comment by cgcgcg** [comment]
I have a packing/unpacking related question: Would it be possible to start communicating before packing is done? I.e. pack all the data for the first message, kick off an Isend, pack the second message, etc. Currently, all packing is done first, and messages are sent. (Same goes for receiving data and unpacking.)
