### ISSUE TITLE
KokkosKernels: error: identifier "CUSPARSE_INDEX_64I" is undefined with cuda 10.1.105

### ISSUE THREAD

**Issue by jewatkins** [trilinos/Trilinos#7723]
## Bug Report
@trilinos/kokkos-kernels

### Description
I received the following build error while building trilinos develop with cuda 10.1.105 (10.1 general release):
```
packages/kokkos-kernels/src/impl/tpls/KokkosSparse_spmv_tpl_spec_decl.hpp(98): error: identifier "CUSPARSE_INDEX_64I" is undefined
```
It looks like `CUSPARSE_INDEX_64I` is not defined in cuda 10.1.105. 

@brian-kelley It looks like using `(10010 <= CUDA_VERSION)` [here](https://github.com/trilinos/Trilinos/commit/ce0cf5a1e71af2757df93a0f42b7a392cc578f29) might not be conservative enough? I was able to get past this through the cuda 9 path by checking for `CUSPARSE_VERSION` which 10.1.105 doesn't have. I.e.:
```
#if defined(CUSPARSE_VERSION) && (10000 <= CUSPARSE_VERSION)
```
I'm not sure if that will catch everything. I looked at 10.1.168 and 10.1.243 and they have the necessary defines (didn't try building though).

Either way, it looks like it's time for me to update my cuda version.

**Comment by brian-kelley** [comment]
@jewatkins Darn, sorry about that. You're right, 10010 <= CUDA_VERSION is necessary but not sufficient for the generic cuSPARSE API. I thought the API for cusparse wouldn't have changed between build versions.

It seems that the real condition to use is just whether CUSPARSE_VERSION is defined at all. 10.1.105 doesn't define it and doesn't have the generic API, but 10.1.243 has both. But in case some other part of a library tries to fill in a value for CUSPARSE_VERSION in the future, I'm going to use ``#if defined(CUSPARSE_VERSION) && (10300 <= CUSPARSE_VERSION)``.

**Comment by jewatkins** [comment]
Confirmed this is fixed, thanks Brian!
