### ISSUE TITLE
Catalyst IOSS Adapter:  Wrong comment type in CMakeLists

### ISSUE THREAD

**Issue by jrood-nrel** [trilinos/Trilinos#7730]
https://github.com/trilinos/Trilinos/blob/develop/packages/seacas/libraries/ioss/src/visualization/ParaViewCatalystIossAdapter/CMakeLists.txt

Resurfacing of #3652 .

**Comment by jhux2** [comment]
@trilinos/seacas

**Comment by gsjaardema** [comment]
This should have been fixed yesterday (304cefb).  I think for some reason my copyright update script has problems with that file and the copyright was updated recently...  Will try to remember this in the future.  Let me know if there is still an issue.
