### ISSUE TITLE
Xpetra::IO and short names may produce conflicts in third party applications

### ISSUE THREAD

**Issue by tawiesn** [trilinos/Trilinos#774]
If a code has its own namespace/class "IO" there might be conflicts with Xpetra::IO and short name definitions ("Xpetra_UseShortNamesScalar.hpp").

**Comment by tawiesn** [comment]
Proposed workaround: exclude Xpetra::IO from short names. Users are forced to specify the full class name (Xpetra::IO<....>) with all template parameters (or introduce their own typedefs)

**Comment by aprokop** [comment]
As long as we don't include the shortnames in the global names, and instead include them inside classes/functions, why would there be conflicst? We don't use other namespaces with IO.

**Comment by tawiesn** [comment]
> As long as we don't ...
In my opinion that's too much "as long as". I think it is quite common to name a class or namespace "IO" in third party applications. Users might use both Xpetra::IO routines and their own IO routines or just include theirs in the same place. I have a concrete problem report from an external customer.

**Comment by jhux2** [comment]
@trilinos/xpetra

**Comment by aprokop** [comment]
> I have a concrete problem report from an external customer.

This is really an external library problem that does not properly incapsulate the code. As long as we don't expose Xpetra's code globally ourselves I don't see why we should fix other library mistakes. In the application you have, is there no other way to fix the issue? Can't you call the external library routines as ::IO?

**Comment by tawiesn** [comment]
>  In the application you have, is there no other way to fix the issue? 

There are many ways to fix that. The best solution would be to remove Xpetra_UseShortNames.hpp from the application code and introduce typedefs for the Xpetra objects only that are really used in the application code. This would avoid conflicts in the future if other classes are added to Xpetra later.

**Comment by aprokop** [comment]
> The best solution would be to remove Xpetra_UseShortNames.hpp from the application code and introduce typedefs for the Xpetra objects only that are really used in the application code.

I think this would be the best way. If you do that, then there is no need to modify Xpetra, right?

**Comment by tawiesn** [comment]
Correct. I'll communicate what has to be done to the application developers...
