### ISSUE TITLE
Tpetra:  apply requiring export is incorrect when beta != 0

### ISSUE THREAD

**Issue by kddevin** [trilinos/Trilinos#7745]
## Bug Report
@trilinos/tpetra 
@csiefer2 @jhux2 @brian-kelley @tjfulle Please see questions below.

### Description

The following cases do not scale y by beta correctly:

    apply(x,y,TRANS,alpha,beta) with beta != 0 and default Trilinos maps
    apply(x,y,NO_TRANS,alpha,beta) with beta != 0 and rangeMap != rowMap.

Both of these cases require an export after the local matrix apply.

Question on combine mode in export / import:

**When combine mode = ADD, is the result**
1. **target[i] = SUM ( src contributions to i ),  OR**
2. **target[i] = target[i] + SUM ( src contributions to i ) ?**

The MultiVector copyAndPermute code does (1) for "sames"; it does a deep copy rather than an accumulation.  

The CrsMatrix::apply code requires an export after the local matrix apply; it assumes that (2) is done.

**For other use cases (e.g., FEMultiVector), what behavior is required and/or expected?**  

### Steps to Reproduce

Simplest test is
  crsMatrix->apply(x, y, TRANS, 2., 3.);
with default maps run on two MPI ransk

**Comment by jhux2** [comment]
@kddevin My thinking is that in the case of import/export, the Tpetra combine mode only governs how to entries in the *source* vector should be combined.  It says nothing about the target vector (in fact, I'd think those values should be over-written).

**Comment by kddevin** [comment]
Thanks, @jhux2.  Your thinking is consistent with the current export/import behavior.  I will fix the transpose apply, then.

**Comment by kddevin** [comment]
Fixed by #7898
