### ISSUE TITLE
Panzer Explicit Model Evaluator test failing

### ISSUE THREAD

**Issue by rppawlo** [trilinos/Trilinos#775]
The test:

PanzerAdaptersSTK_explicit_model_evaluator

is failing in a nightly build, but passing in the CI build. This test seems unstable. The failing test is printing solution values of 1e+38. I could not reproduce the failure locally. Need to have someone look into this.

**Comment by jmgate** [comment]
@trilinos/panzer

**Comment by jmgate** [comment]
I'm also seeing this on my Linux machine.  The basic unit test fails because `Thyra::norm_2(*mass_exp_f) > 1e-16`.  I'll start digging in to see what's going on.

**Comment by jmgate** [comment]
I've managed to narrow the problem down to the `fm->template evaluateFields<EvalT>(workset);` line of `panzer::AssemblyEngine<EvalT>::evaluateVolume(const panzer::AssemblyEngineInArgs& in)`.  Still digging...

**Comment by jmgate** [comment]
@rppawlo, @eric-c-cyr, is there an easy way to debug an `evaluateFields` call?  I'm having a hard time finding what's inside.

**Comment by jmgate** [comment]
Looks like if `parameter_on == true` in `explicit_model_evaluator.cpp`, then the `SOURCE_TEMPERATURE` is being created as a `panzer::Parameter` with a value of 1.13416e+103, instead of being created as a `double` with a value of 1.  Sounds like the `Parameter` isn't getting initialized.  Should we initialize `Parameter`s by default to `nan` so that we more readily know when we're about to do something foolish?

**Comment by jmgate** [comment]
Added some logic at the end of `buildAssemblyPieces()` to initialize `SOURCE_TEMPERATURE` to 1.0 if it happens to be a `Parameter`.  I'll look into initializing all `Parameter`s by default next.

**Comment by jmgate** [comment]
Looks like initializing `Parameter`s to `NAN` doesn't cause any problems.  This was apparently the only place in which we weren't giving one a value, so the switch to `NAN` should make this kind of thing easier to notice in the future.

**Comment by jmgate** [comment]
@rppawlo, @eric-c-cyr, can we close this out?
