### ISSUE TITLE
MueLu parameter list interpreter test is failing in the continuous build

### ISSUE THREAD

**Issue by bmpersc** [trilinos/Trilinos#776]
The test  MueLu_ParameterListInterpreterTpetra_MPI_1 is failing on the continuous build. It looks like a single check out of the entire test is the only thing failing:

Binary files Output/MLpgamg1_tpetra.gold_filtered and Output/MLpgamg1_tpetra.out_filtered differ
MLParameterListInterpreter/MLpgamg1.xml : failed

You can view the test at:
https://testing.sandia.gov/cdash/viewTest.php?onlyfailed&buildid=2606750

**Comment by bmpersc** [comment]
@trilinos/muelu

**Comment by aprokop** [comment]
From the output:
```
Binary files Output/MLpgamg1_tpetra.gold_filtered and Output/MLpgamg1_tpetra.out_filtered differ
```
I don't understand why they are treated as binary. It does not show actual diff, so I cannot comment on more.

If somebody could take a look at the test on the sadl30906 machine, if we know who the owner is.

**Comment by jhux2** [comment]
> If somebody could take a look at the test on the sadl30906 machine, if we know who the owner is.

@bmpersc I don't have access to this machine, either.

**Comment by bmpersc** [comment]
I could get the files off the machine and attach them here. Would that be helpful or do you need to actually run the test?

FWIW the machine is question is a fairly vanilla RHEL6 machine using the SEMS NFS for compilers/TPLs etc. So this should be easy to replicate.

**Comment by jhux2** [comment]
> I could get the files off the machine and attach them here. Would that be helpful or do you need to actually run the test?
> 
> FWIW the machine is question is a fairly vanilla RHEL6 machine using the SEMS NFS for compilers/TPLs etc. So this should be easy to replicate.

Except this test isn't failing elsewhere ... and as far as I know, there have been no changes that would cause this.

**Comment by aprokop** [comment]
@bmpersc Yes, we need to see both files. If you could run the test, that would be helpful too, just to make sure it was not a fluke for it to fail. But please send the files first as running the test will overwrite them.

**Comment by bmpersc** [comment]
[MLpgamg1_tpetra.gold_filtered.txt](https://github.com/trilinos/Trilinos/files/570309/MLpgamg1_tpetra.gold_filtered.txt)
[MLpgamg1_tpetra.gold.txt](https://github.com/trilinos/Trilinos/files/570310/MLpgamg1_tpetra.gold.txt)

I have attached the two files from the failing test. I have also tried to replicate the issue on my blade and have a failing test, but it is failing with an exception instead of this particular error. I'm not sure it they are related but in case they are the output from my blade is:

33: Test command: /projects/sems/install/rhel6-x86_64/sems/compiler/gcc/4.7.2/openmpi/1.6.5/bin/mpiexec "-np" "1" "/scratch/bmpersc/trilinos_projects/clean/continuous_build/packages/muelu/test/interface/MueLu_ParameterListInterpreter.exe" "--linAlgebra=Tpetra"
33: Test timeout computed to be: 1500
33: EasyParameterListInterpreter/coarse3.xml : passed
33: EasyParameterListInterpreter/reuse-none_np4.xml : passed
33: EasyParameterListInterpreter/reuse-tP-2_np4.xml : passed
33: 
33: p=0: *** Caught standard std::exception of type 'std::invalid_argument' :
33: 
33:  /scratch/bmpersc/trilinos_projects/clean/packages/teuchos/remainder/src/Trilinos_Details_LinearSolverFactory.hpp:599:
33:  
33:  Throw number = 58
33:  
33:  Throw test that evaluated to true: factory.get () == NULL
33:  
33:  Trilinos::Details::getLinearSolver: Package "Ifpack2" is valid, but it never registered a LinearSolverFactory for template parameters MV = Tpetra::MultiVector<double,int,long int,Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace>>, OP = Tpetra::Operator<double, int, long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >, NormType = double.  Trilinos_ENABLE_LINEAR_SOLVER_FACTORY_REGISTRATION = OFF.
33: --------------------------------------------------------------------------
33: mpiexec noticed that the job aborted, but has no info as to the process
33: that caused that situation.
33: --------------------------------------------------------------------------
1/1 Test #33: MueLu_ParameterListInterpreterTpetra_MPI_1 ...***Failed  Required regular expression not found.Regex=[End Result: TEST PASSED
]  1.18 sec

**Comment by aprokop** [comment]
@bmpersc We need `Output/MLpgamg1_tpetra.out_filtered` (`out_filtered` instead of `gold_filtered`

**Comment by bmpersc** [comment]
[MLpgamg1_tpetra.out_filtered.txt](https://github.com/trilinos/Trilinos/files/570362/MLpgamg1_tpetra.out_filtered.txt)
 Sorry about that. I saw gold and filtered and figured that was the right set. Here is the out_filtered file.

**Comment by aprokop** [comment]
Hmm, it's funny, the files don't differ (except for a whitespace).  It's unclear why the test failed. 
@bmpersc Can you manually run 
```bash
diff -u -w -I"^\\s*$"  MLpgamg1_tpetra.gold_filtered MLpgamg1_tpetra.out_filtered
```
on that machine? 'Cause that's the actual command that gives pass/fail result.

**Comment by jhux2** [comment]
@bmpersc By the way, the [continuous](http://testing.sandia.gov/cdash/buildSummary.php?buildid=2607878) build is passing now.
