### ISSUE TITLE
Zoltan:  Test failing in release 13.0 branch

### ISSUE THREAD

**Issue by ZUUL42** [trilinos/Trilinos#7768]
## Bug Report
@trilinos/zoltan 

### Description
The changes to Version.cmake for the release 13.0 branch #7735 turns off development mode. That has caused a Zoltan test to fail, Zoltan_ch_simple_zoltan_parallel. [CDash](https://testing.sandia.gov/cdash/index.php?project=Trilinos&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=63&value1=PR-7735-test-Trilinos_pullrequest_cuda_9.2&field2=buildstarttime&compare2=84&value2=NOW)

It can be fixed or since [the test does pass building with Cuda 9.2 with the dev tag in place](https://testing.sandia.gov/cdash/index.php?project=Trilinos&display=project&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=63&value1=ver_dev-test&field2=buildstamp&compare2=63&value2=Experimental), it doesn't seem like much of a risk to turn off the test on the release branch only.

**Comment by kddevin** [comment]
I agree with @ZUUL42 ; disabling these tests in the release branch only is very very low risk.
RIB is sensitive to compiler optimizations; one-point differences in the partitions sometimes occur.

@ZUUL42 how does one disable the tests?   Thanks.

**Comment by ZUUL42** [comment]
@kddevin I'll take care of it. I just wanted to run it past someone in Zoltan before I did so.

**Comment by kddevin** [comment]
Thanks, @ZUUL42
