### ISSUE TITLE
cgcgcg/Trilinos/ifpackChebyPower commit caused widespread Nalu regression test diffs

### ISSUE THREAD

**Issue by spdomin** [trilinos/Trilinos#7776]
## Bug Report
@trilinos/ifpack2

### Description
Widespread diffs noted in Nalu application; an app that extensively uses ifpack2.

Bisect calipers:

Good: 721370bdcc2c06828afb64232665b60798b882c8
Bad: e28ab81f8e059e3e4ab76174f4c1a9cdc040e9d3

Noted: @cgcgcg commit:

Bisecting: 0 revisions left to test after this (roughly 0 steps)
[866bab54b5bf59c1ba81d3ab3963bdd6e167517b] Ifpack2 Chebyshev: Remove unneeded global communication from power method
[spdomin@ceerws2214 Trilinos]$ git log
commit 866bab54b5bf59c1ba81d3ab3963bdd6e167517b
Author: Christian Glusa <caglusa@sandia.gov>
Date:   Fri Jul 31 17:08:07 2020 -0600

    Ifpack2 Chebyshev: Remove unneeded global communication from power method

Dear Christian, please let me know if this change was intentional and diffs are expected. The comment above suggests that the extra communication was not required, however, it clearly caused diffs - possibly through a Muelu interface for Chebyshev smoothing? Not sure as our routine ifpack2/balos combination is SGS/GMRES along with an elliptic pressure Poison system that uses Muleu (often times with Chebyshev smoothing).

Perhaps muele team might know? @jhux2 

Diffs are not huge, however, something clearly changed:

..dgNonConformalThreeBlade........... FAILED:   s  max diff:  .00000010000000000000243069453454

Let me know how to proceed or if a revert is in order to allow for time to understand while allowing Nalu to test effectively.

best.

Stefan

**Comment by cgcgcg** [comment]
@spdomin When you run these tests, does any of them actually report changes in the eigenvalue estimates? If so, how much? Changing the order of operations around can definitely result in different rounding.

**Comment by spdomin** [comment]
I do not have full diagnostic output activated in these tests. I can take a look at one or two of them. 

What is your opinion on the commit comment that this change should not have changed anything?

Best,

**Comment by spdomin** [comment]
For a few spot check cases, the iteration counts are the same. Setup and solve times are within statistical noise although always seems to break in favor of the pre-commit, I.e. new sims are slower. 

Let me know if you feel that this change is correct and the best path forward for Muelu and I will happily re-bless.

**Comment by cgcgcg** [comment]
I think that re-blessing the gold files is the way to go. What to you think @jhux2?

It might be worth adjusting nalu's tests though. I think that checking iteration counts for reaching a given tolerance should generally be enough, and be less sensitive to noise such as the one introduced by this PR. (I acknowledge though that changing tests is delicate business.)

**Comment by spdomin** [comment]
I have been saved in the past by algorithmic changes that caused really tiny diffs that were incorrect. I generally like one platform that is “strict” to find such changes. 

The recent Zoltan2 Nalu bisect comes to mind. I think that the change was unintended and, as far as I could tell, Nalu may have been the only app code to find it. 

As soon as Jonathan suggests a re-bless we can close this out. 

Best

**Comment by spdomin** [comment]
This one comes to mind:

https://github.com/trilinos/Trilinos/issues/6358

**Comment by spdomin** [comment]
https://github.com/NaluCFD/Nalu/commit/cfac515e4a0e6f63639455f082475673481c2dc5

Sadly, it looked to me that all of the small regression tests that were diffing ran a bit faster and all of the larger cases ran a bit slower. However, suite is diff free.

Let me know if any other changes are coming down the pipeline.

**Comment by jhux2** [comment]
@spdomin I reviewed the PR that led to these changes, and support reblessing (which it looks like you did earlier today).

**Comment by spdomin** [comment]
Excellent! Thanks.
