### ISSUE TITLE
Create 12.6 branch

### ISSUE THREAD

**Issue by bmpersc** [trilinos/Trilinos#78]

**Comment by bmpersc** [comment]
The branch has been made and master returned to developers

Still to do:
Testing needs to be setup, there was an issue with the version of python on the current testing machine. 
Release notes need to be gathered and updated.
Tarball creation with external packages needs to be tested and any issues resolved.

**Comment by bmpersc** [comment]
The testing machine was not able to update the python to a new enough version in a workable way. This will require us moving to a newer machine. The SEMS Jenkins has suitable machines so I will look into moving the release testing to one of those.

**Comment by bartlettroscoe** [comment]
I think this issue is complete, is it not?

**Comment by bmpersc** [comment]
Normally we leave the release issues open until the official announcement, but at this point I think it is safe to close it.
