### ISSUE TITLE
STK doc problem

### ISSUE THREAD

**Issue by VictorEijkhout** [trilinos/Trilinos#780]
File cmake/PyTrilinos/PyTrilinosConfig.cmake

contains a line:

INCLUDE("${CMAKE_CURRENT_LIST_DIR}/../STKDoc_tests/STKDoc_testsConfig.cmake")

referring to a non-existing file. This does not impede trilinos installation, but it trips up for instance DealII.

[Archive.zip](https://github.com/trilinos/Trilinos/files/571715/Archive.zip)

Victor.

PS why doesn't your ticket system accept files with extension that you generate by the dozen? That kinda makes it hard to attach files. I've packaged some log files and zipped them as attachment to this ticket.

**Comment by jhux2** [comment]
> PS why doesn't your ticket system accept files with extension that you generate by the dozen? That kinda makes it hard to attach files. I've packaged some log files and zipped them as attachment to this ticket.

This is a github [limitation](https://github.com/blog/2061-attach-files-to-comments).

**Comment by sconde** [comment]
@mhoemmen  @wfspotz  I am also seeing the same error when trying to build Empire:
```
  CMakeLists.txt:19 (find_package)


CMake Error at /home/sconde/Documents/trilinos/install/lib/cmake/PanzerAdaptersSTK/PanzerAdaptersSTKConfig.cmake:152 (INCLUDE):
  include could not find load file:

    /home/sconde/Documents/trilinos/install/lib/cmake/PanzerAdaptersSTK/../STKDoc_tests/STKDoc_testsConfig.cmake
```

**Comment by VictorEijkhout** [comment]
So, no progress on this? I really hate having to do a bunch of sed script as post-processing of my installation.

**Comment by jhux2** [comment]
@bmpersc @trilinos/stk

**Comment by wfspotz** [comment]
I checked my PyTrilinosConfig.cmake file (or at least one of them) and there is no reference to STK.

@VictorEijkhout, can you post your `cmake` invocation?

**Comment by VictorEijkhout** [comment]
On Dec 2, 2016, at 1:28 PM, Bill Spotz <notifications@github.com<mailto:notifications@github.com>> wrote:


I checked my PyTrilinosConfig.cmake file (or at least one of them) and there is no reference to STK.

@VictorEijkhout<https://github.com/VictorEijkhout>, can you post your cmake invocation?

cd ${BUILD_LOCATION}
export shareopt="-D BUILD_SHARED_LIBS:BOOL=ON"
## VLE until we figure out that sighup: TESTS:OFF
cmake \
  ${shareopt} \
  -D Trilinos_VERBOSE_CONFIGURE=OFF \
  -D CMAKE_VERBOSE_MAKEFILE=ON \
  -D Trilinos_ENABLE_ALL_PACKAGES:BOOL=OFF \
  -D Trilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=OFF \
  -D Trilinos_ENABLE_TESTS:BOOL=OFF \
  -D Trilinos_ENABLE_EXAMPLES:BOOL=ON \
  -D Trilinos_ENABLE_Export_Makefiles:BOOL=ON \
  -D Trilinos_ENABLE_Fortran:BOOL=ON \
  \
  -D CMAKE_INSTALL_PREFIX:PATH=${INSTALL_LOCATION} \
  -D CMAKE_BUILD_TYPE:STRING=RELEASE \
  -D CMAKE_C_FLAGS:STRING="${COPTFLAGS}" \
  -D CMAKE_CXX_FLAGS:STRING="${COPTFLAGS} -DMPICH_SKIP_MPICXX" \
  \
  -D BLAS_INCLUDE_DIRS:PATH="${TACC_MKL_INC}" \
  -D BLAS_LIBRARY_DIRS:PATH="${TACC_MKL_LIB}" \
  -D BLAS_LIBRARY_NAMES:STRING="mkl_intel_lp64;mkl_sequential;mkl_core;pthread" \
  -D LAPACK_INCLUDE_DIRS:PATH="${TACC_MKL_INC}" \
  -D LAPACK_LIBRARY_DIRS:PATH="${TACC_MKL_LIB}" \
  -D LAPACK_LIBRARY_NAMES:STRING="mkl_intel_lp64;mkl_sequential;mkl_core;pthread" \
  \
  -D TPL_ENABLE_MPI:BOOL=ON \
  -D MPI_EXEC:FILEPATH="/opt/apps/xalt/0.4.6/bin/ibrun" \
  -D TPL_ENABLE_GLM=OFF \
  -D TPL_ENABLE_Matio=OFF \
  \
  -D TPL_ENABLE_Boost:BOOL=ON \
  -D Boost_INCLUDE_DIRS:PATH=$TACC_BOOST_INC      \
  -D Boost_LIBRARY_DIRS:PATH=$TACC_BOOST_LIB      \
  -D TPL_ENABLE_BoostLib:BOOL=ON \
  -D BoostLib_INCLUDE_DIRS:PATH=$TACC_BOOST_INC      \
  -D BoostLib_LIBRARY_DIRS:PATH=$TACC_BOOST_LIB      \
  \
  -D TPL_ENABLE_HDF5:BOOL=ON \
  -D HDF5_INCLUDE_DIRS:PATH=$TACC_HDF5_INC    \
  -D HDF5_LIBRARY_DIRS:PATH=$TACC_HDF5_LIB    \
  -D TPL_ENABLE_Netcdf:BOOL=ON \
  -D Netcdf_INCLUDE_DIRS:PATH=$TACC_NETCDF_INC    \
  -D Netcdf_LIBRARY_DIRS:PATH=$TACC_NETCDF_LIB    \
  \
  -D Trilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=ON \
  \
  -D Trilinos_ENABLE_Amesos:BOOL=ON \
  -D Amesos2_ENABLE_Basker:BOOL=ON \
  -D Trilinos_ENABLE_Anasazi:BOOL=ON \
  -D Trilinos_ENABLE_AztecOO:Bool=ON \
  -D Trilinos_ENABLE_Belos:BOOL=ON \
  -D Trilinos_ENABLE_Epetra:Bool=ON \
  -D Trilinos_ENABLE_EpetraExt:Bool=ON \
  -D                 Epetra_ENABLE_TESTS:BOOL=ON \
  -D Trilinos_ENABLE_Ifpack:Bool=ON \
  -D Trilinos_ENABLE_Intrepid:BOOL=ON \
  -D                 Intrepid_ENABLE_TESTS:BOOL=ON \
  -D Trilinos_ENABLE_ML:BOOL=ON \
  -D Trilinos_ENABLE_MOOCHO:BOOL=ON \
  -D Trilinos_ENABLE_MueLu:BOOL=ON \
  -D Trilinos_ENABLE_NOX=ON \
  -D                 NOX_ENABLE_TESTS:BOOL=ON \
  -D Trilinos_ENABLE_Pamgen:Bool=ON \
  -D Trilinos_ENABLE_Phalanx:BOOL=ON \
  -D Phalanx_EXPLICIT_TEMPLATE_INSTANTIATION=ON \
  -D Trilinos_ENABLE_Rythmos:BOOL=ON \
  -D Trilinos_ENABLE_Sacado:Bool=ON \
  -D Trilinos_ENABLE_SEACASIoss:BOOL=ON \
  -D Trilinos_ENABLE_SEACAS:BOOL=ON \
  -D Trilinos_ENABLE_SEACASBlot:BOOL=ON \
  -D Trilinos_ENABLE_Shards:BOOL=ON \
  -D Trilinos_ENABLE_ShyLU:BOOL=ON \
  -D Trilinos_ENABLE_STK:BOOL=ON \
  -D Trilinos_ENABLE_Stokhos:BOOL=ON \
  -D Trilinos_ENABLE_Stratimikos:BOOL=ON \
  -D Trilinos_ENABLE_Teko:BOOL=ON \
  -D Trilinos_ENABLE_Teuchos:BOOL=ON \
  -D Trilinos_ENABLE_Tpetra:Bool=ON \
  -D Trilinos_ENABLE_TriKota:BOOL=ON \
  -D Trilinos_ENABLE_Zoltan:BOOL=ON \
  \
  -D CMAKE_PYTHON_INCLUDE_DIR:PATH="${TACC_PYTHON_INC}" \
  -D CMAKE_PYTHON_LIBRARIES:STRING="${TACC_PYTHON_LIB}" \
  -D Trilinos_ENABLE_PyTrilinos:Bool=ON \
  -D PyTrilinos_DOCSTRINGS:BOOL=OFF \
  -D SWIG_EXECUTABLE:FILEPATH=${TACC_SWIG_DIR}/bin/swig \
  \
  ${TRILINOS_LOCATION}/trilinos-${VERSION} \
  > ${HOME}/Software/trilinos/cmake-${VERSION}.log 2>&1


With obvious expansion of system dependent variables.

Victor.
