### ISSUE TITLE
Ifpack:  Removing "virtual inline" functions to make it standard compliant

### ISSUE THREAD

**Issue by alenacpp** [trilinos/Trilinos#7802]
## Enhancement
@trilinos/ifpack

There are virtual inline functions declared in ifpack. They are defined in a different translation unit, which makes it a non-standard C++.
gcc gives a warning, nvc++ gives an error in a pedantic mode. Removing 'inline' fixes the issue.

**Comment by jhux2** [comment]
Closing as resolved.
