### ISSUE TITLE
ifpack:  memory leak in Ifpack_Hypre

### ISSUE THREAD

**Issue by ecoon** [trilinos/Trilinos#7807]
## Bug Report
@trilinos/ifpack

### Description

Normal usage of Ifpack_Hypre leaks memory.

### Steps to Reproduce
1. SHA1:  688a924
2. Configure script:  (built through cmake, standard configure of Epetra stack)
3. Configure log:  (if needed I can go searching...)
4. Build log:  (same as configure)
5. Input deck:  [attach here]
[solver_pc_boomeramg.cc.txt](https://github.com/trilinos/Trilinos/files/5045269/solver_pc_boomeramg.cc.txt)

See attached unittest. 

6. Compile and run valgrind:

`valgrind --leak-check=full solver_pc_boomeramg &> valgrind_out.txt`

7. Run log:
[valgrind_out.txt](https://github.com/trilinos/Trilinos/files/5045272/valgrind_out.txt)

### Why is it broken?

Effectively the issue is the following path through the code:

1. Use Hypre as a Preconditioner `SolverOrPreconditioner == Preconditioner`
2. Supply no Solver.  Ifpack_Hypre defaults to `PCG`.
 https://github.com/trilinos/Trilinos/blob/master/packages/ifpack/src/Ifpack_Hypre.cpp#L73
3.  Despite not being asked to supply a Solver, Ifpack calls CreateSolver, which since there is a default value of a real solver (e.g. not NULL or comparable), Ifpack creates the object.  This allocates memory (in Hypre)
  https://github.com/trilinos/Trilinos/blob/master/packages/ifpack/src/Ifpack_Hypre.cpp#L166
4. When `Compute()` is called, `SolverSetupPtr_` is _not_ called, because there it correctly checks and sees that a solver was not requested.  As a result, the flag  `IsSolverSetup_[0] == false`
https://github.com/trilinos/Trilinos/blob/master/packages/ifpack/src/Ifpack_Hypre.cpp#L279
5. Since `IsSolverSetup_[0] == false`, `Destroy()` does _not_ call `DestroySolverPtr_`: 
https://github.com/trilinos/Trilinos/blob/master/packages/ifpack/src/Ifpack_Hypre.cpp#L142

Not calling `DestroySolverPtr_` leaks the memory.  Note, I have not confirmed that DestroySolverPtr_ can be called on a created but not setup Hypre solver, but one would hope so.

Note also that there is a comparable memory leak where you could replace "Solver" by "Preconditioner" and leak the PC object (if `UsePreconditioner_ == false`)

### Proposed fix

There are a few issues here, and fixes are pretty straightforward.  Pull request coming in the next few days.

1. Rename the flag IsSolverSetup_ to IsSolverCreated_, set it on creation, and destroy if created.  This would fix the memory leak.  (Respectively, IsPreconSetup_), and doing this makes the code safer.
2. Check whether `SolverOrPreconditioner_ != Preconditioner` before creating a solver.  Similarly, check whether `UsePreconditioner_ == true` before creating a preconditioner.  These shouldn't be created if they aren't going to be used.

**Comment by ecoon** [comment]
Also, for what it's worth, it looks like Hypre's GMRES solver doesn't have it's SolverSolvePtr_ set... should be here.

https://github.com/trilinos/Trilinos/blob/master/packages/ifpack/src/Ifpack_Hypre.cpp#L512

Guess no one has ever used this code (we don't either, just was looking for something for testing...)

**Comment by ecoon** [comment]
@cgcgcg  Can you also add a comment and mention @trilinos/ifpack so the right people see it?  My mentions won't get sent out because I don't have that permission.  (Unless they are automatically notified by applying the tag...)  Thanks!

**Comment by cgcgcg** [comment]
@trilinos/ifpack

**Comment by csiefer2** [comment]
We already have a branch with some of these fixes in it that I need to merge to develop anyway.  I'll try to get those squared away with your changes and merge 'em all together sometime this week.

**Comment by cgcgcg** [comment]
Taken care of via #8060
