### ISSUE TITLE
Trilinos test programs question

### ISSUE THREAD

**Issue by VictorEijkhout** [trilinos/Trilinos#781]
All the trilinos packages come with test code. I would like to tell users "copy this directory out of the source tree to your own area, set these environment variables, and then you can build an example code".

The trilinos test examples don't seem to be designed along these lines. For instance, the test executables are in the build directory, not in the final install. These build directories are (naturally) not part of the installation that I offer to users. Also, they seem for testing the correctness of the installation, rather than as usage examples for users.

Is my proposed scenario possible? I want to offer users kind of a template of how to build a trilinos application.

Victor.

**Comment by mhoemmen** [comment]
@VictorEijkhout wrote:
> Also, they seem for testing the correctness of the installation, rather than as usage examples for users.

Some packages have usage examples for users.  For example, Tpetra has lessons in Trilinos/packages/tpetra/core/example/Lesson*.  These do have the issue you mention, that the executables live in the build directory and the source files are not copied into the installation directory.

**Comment by mhoemmen** [comment]
> Is my proposed scenario possible?

It's certainly possible to tell CMake to install source files in the installation directory.  We could also generate sample CMakeLists.txt files to install with them, that use the installed Trilinos.  So yes, I think it is possible.

**Comment by jwillenbring** [comment]
We don't do a great job of it in all cases, but usefulness to users vs testing value is supposed to be the differences between tests and examples in Trilinos. @VictorEijkhout 's comment is strongly in line with a discussion earlier this week with @bartlettroscoe @BarrySmith and others concerning having a set of Trilinos tests that can be run post installation for xSDK testing.

**Comment by bartlettroscoe** [comment]
> ... @bartlettroscoe @BarrySmith and others concerning having a set of Trilinos tests that can be run post installation for xSDK testing.

What we discussed for xSDK testing was more on the testing side and not really on the examples side.  For xSDK testing, our strategy (that we need to revive) of building the Trilinos examples and tests pointing to the install tree takes care of that.  But that is not a user example of how to link against Trilinos.  And therefore, I would say that is almost completely orthogonal to what is asked for in this Issue.

I would say that any executables that are built and run as part of Trilinos testing can have their source code copied out and then a Makefile or CMake build system can be written for it that sucks in the `TrilinosConfg.cmake` (or `<Package>Config.cmake`) file and to pull in the include directories and libraries.

I guess that someone just needs to write some documentation on how to do that process in general.  Or, someone needs to step and take the time to install example code with example Makefiles and/or CMakeLists.txt files and set up automated testing to test those from the install tree.  I used to do that with some Thyra examples when we used autotools (but did not copy that over for the CMake build of Trilinos).

This sounds like a something that might fall under the [Trilinos User Experience Capability Area](https://trilinos.org/capability-areas/user-experience/) (@wfspotz lead, @mhoemmen sub-lead for [Documentation, Examples, and Tutorials](https://trilinos.org/capability-areas/user-experience/#DocExTut)) to consider.

**Comment by mhoemmen** [comment]
@bartlettroscoe wrote:
> I guess that someone just needs to write some documentation on how to do that process in general. Or, someone needs to step and take the time to install example code with example Makefiles and/or CMakeLists.txt files and set up automated testing to test those from the install tree. 

If we do it, let's do it by default, at least for examples' source code and Makefiles.  They don't take up that much space compared with the libraries.  Vendors and third-party distributors that build Trilinos are not likely to dig much into nondefault CMake options.

**Comment by bartlettroscoe** [comment]
> If we do it, let's do it by default, at least for examples' source code and Makefiles.

Yup.  But whatever we install we need to have automated testing to make sure that these examples continue to build and run successfully.  There is nothing worse than having a user go to our installed examples and then find out that they don't even build or if they do build, the segfault or do something terrible.  However, given that these same examples are likely also to be built and run from the source and build tree, I think just having the examples build and run and returning 0 error codes is likely enough of a test.  That is what we do for installed examples for the CASL VERA project and it has been very successful for that project.

But we don't have people to do this work unless some "hero" steps up and does it.  If when they do, they typically only do it for their own Trilinos package and don't think about things from the Trilinos level (lots of examples).

**Comment by mhoemmen** [comment]
@bartlettroscoe wrote:
> I think just having the examples build and run and returning 0 error codes is likely enough of a test.

That's what the Tpetra Lessons do.  

> But we don't have people to do this work unless some "hero" steps up and does it. If when they do, they typically only do it for their own Trilinos package and don't think about things from the Trilinos level (lots of examples).

We have to start somewhere.  It's OK if we just start with one package, then expand out from there.

**Comment by sagitter** [comment]
>The trilinos test examples don't seem to be designed along these lines. For instance, the test executables are in the build directory, not in the final install. These build directories are (naturally) not part of the installation that I offer to users. Also, they seem for testing the correctness of the installation, rather than as usage examples for users.

Not only. I noted that to perform a generic `ctest` i need setting LD_LIBRARY_PATH with a list of directories that contain all `lib?_test.so` files. It would be better having all libraries for testing in a single build directory.

**Comment by tjfulle** [comment]
This is essentially what @mhoemmen and I were getting at with #689.  It would be nice to, e.g., read the tpetra tutorials and be able to modify the source, do the suggested exercises, etc. and run a simple Makefile to compile them.

**Comment by mhoemmen** [comment]
@tjfulle wrote:
> This is essentially what @mhoemmen and I were getting at with #689. It would be nice to, e.g., read the tpetra tutorials and be able to modify the source, do the suggested exercises, etc. and run a simple Makefile to compile them.

I think we could just stuff a Makefile (that uses the Makefile.export.Trilinos system) into each directory, and tell CMake to install it and the source file.  If we generate the Makefile (e.g., from a Makefile.in file) using CMake, we could also have CMake write Trilinos' install directory to the generated Makefile.  That would allow use of the Makefile without needing to modify it, assuming that the compiler and TPLs all have the same locations as when Trilinos was built.

**Comment by bartlettroscoe** [comment]
> Not only. I noted that to perform a generic ctest i need setting LD_LIBRARY_PATH with a list of directories that contain all lib?_test.so files. It would be better having all libraries for testing in a single build directory.

That is why I would recommend using raw CMake and CTest to build and run the examples.  That way, CMake can bake in RPATH automatically so that no one needs to mess with `LD_LIBRARY_PATH`.  And that is very portable.  See TriBITSPub/TriBITS#126.

**Comment by mhoemmen** [comment]
@bartlettroscoe wrote:
> That is why I would recommend using raw CMake and CTest to build and run the examples.

On the other hand, it would be nice if every example showed the current best way to build an application against an installed Trilinos ;-)

**Comment by VictorEijkhout** [comment]
> On the other hand, it would be nice if every example showed the current best way to build an 
> application against an installed Trilinos ;-)

That was my whole point. The current setup gives no "follow these instructions and you'll have one working example in your own directory".

Just look at petsc: copy any example directory, set two environment variables to point into the system, and you have a working program makefile that you can edit and use as basis for your own setup.

Btw, it would be **really** nice if you could provide a regular makefile. I've come across very few users who are cmake virtuosos.

**Comment by bartlettroscoe** [comment]
> Btw, it would be really nice if you could provide a regular makefile. I've come across very few users who are cmake virtuosos.

Trilinos could provide a Makefile and a CMakeLists.txt file for each example.  In the case of the CMakeLists.txt file, we can set it up so that the user just needs to provide a single CMake cache var on the configure line.  Something similar can be done for the Makefile (but would need to use a env var perhaps).

This is likely not a terribly hard system to put together.  I can even imagine a simple TriBITS/CMake function that would set up the install/example directory in one short so that many packages could use this.   It could look something like:

```
TRIBITS_INSTALL_EXAMPLE(
   EXAMPLE_SUBDIR  simple_example
   EXAMPLE_MAIN simple_example_main.cpp
   EXAMPLE_FILES  simple_example.cpp  simple_example.hpp 
   )
```

What that could is install the listed source files under the directory:

```
  <install-prefix>/share/<PackageName>/examples/simple_example/
```

and it would automatically write in a Makefile file, a CMakeLists.txt, file, and a README file.  I think given the installation of `<PackageName>Config.cmake` and `Makefile.export.<PackageName>`, you can write the installed Makefile and CMakeLists.txt files automatically.  In the case of the CMakeLists.txt file, it can use CTest to run the example.  For the Makefile case, you would have to use 'make test' or something.

But whatever is put in place needs to be under automated testing or it will break.

I just know who would do this work.  We desperately need someone with some CMake skills to do this type of work.

**Comment by jwillenbring** [comment]
We could use the Trilinos_tutorial project as a baseline for some of this if we identify someone to do the work. There is a makefile system and a CMake system for building that. As @bartlettroscoe said for a different approach, we would need to put some testing in place.
