### ISSUE TITLE
Header file MueLu_CreateEpetraPreconditioner.hpp contains non-template function definitions

### ISSUE THREAD

**Issue by ambrad** [trilinos/Trilinos#782]
@trilinos/muelu, as reported by a user. header file MueLu_CreateEpetraPreconditioner.hpp contains non-template function definitions, causing multiple symbols when linking his program. These non-template function definitions should be moved to a .cpp file, leaving just the declarations.

**Comment by ambrad** [comment]
@jhux2 @tawiesn

**Comment by aprokop** [comment]
I've attached a patch. If somebody can run the checkin script on it, that would be great, I can't do that at the moment.
[create_epetra.txt](https://github.com/trilinos/Trilinos/files/582324/create_epetra.txt)

**Comment by aprokop** [comment]
Oh, we can remove inclusion guards in .cpp
