### ISSUE TITLE
MueLu: reorganize regionMG code

### ISSUE THREAD

**Issue by mayrmt** [trilinos/Trilinos#7824]
## Enhancement
@trilinos/muelu 

The regionMG code started out as purely experimental code in `packages/muelu/research/mmayr/composite_to_regions/` and relied on the interplay of some C++ executable with some Matlab scripts. Meanwhile, a pure C++ implementation is available in `packages/muelu/research/regionMG/`.

The first Matlab-based version still compiles, but has not been used in more than a year. All developments are only carried out in the new C++ version. To prepare for a more mature implementation of the regionMG framework, @lucbv and I have discussed some ideas on how to restructure the current source code directories. This issue is intended to agree on a new directory structure, which will then be implemented.

## Proposal

What about this new directory structure:
```
packages/muelu/research/regionMG/
    |__doc/
    |__examples/
    |__src/
```
where
- the `src/` folder will contain the `SetupRegion*.hpp` files currently living in `packages/muelu/research/mmayr/composte_to_regions/`
- the `examples/` folder will contain the driver `Driver_Structured_Regions.cpp` and the associated `xml`-files

Then, 
- the existing directory `packages/muelu/research/mmayr/hhg/` will be deleted
- the remaining files in `packages/muelu/research/mmayr/composte_to_regions/` can be removed
- finally, we can probably remove the entire `packages/muelu/research/mmayr/` directory

**Comment by lucbv** [comment]
@mayrmt yes that is exactly what I have in mind, I will add that the report I am working on should eventually be located in the doc subfolder. This can probably happen only after the document is at least well drafted and can be put through R&A.

**Comment by mayrmt** [comment]
@lucbv @pohm01 @rstumin The directory `packages/muelu/research/regionMG/examples/structured/` contains the region driver, some xml-files, and the gold files and a python script for testing. Is `examples/` an appropriate name or should we rather got for `tests/`? Right now, I'd prefer `tests/` over `examples/` as it describes the content more clearly.

**Comment by mayrmt** [comment]
@lucbv PR #7830 contains the reorganisation of the directory structure.

**Comment by mayrmt** [comment]
@lucbv I have not added a `doc/` directory yet, since it would be empty. Feel free to add it, when you put the report there.

**Comment by mayrmt** [comment]
This has been addressed in `develop`, so let's close this issue. The autotester will bring it to `master`.
