### ISSUE TITLE
Trilinos: Installation Error

### ISSUE THREAD

**Issue by bdas123** [trilinos/Trilinos#7825]
I was trying to make Trilinos on the UT Stampede 2 TACC Computer. However, I got this error. 

Please let me know if you need any more information. 

Thank you!

[ 84%] Built target moertel
CMakeFiles/belosxpetra.dir/Belos_Details_Xpetra_registerSolverFactory.cpp.o: file not recognized: File truncated
make[2]: *** [packages/belos/xpetra/src/libbelosxpetra.so.12.17] Error 1
make[2]: Leaving directory `/home1/07571/barundas/Scratch/Trilinos/build'
make[1]: *** [packages/belos/xpetra/src/CMakeFiles/belosxpetra.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
CMakeFiles/belosepetra.dir/Belos_Details_Epetra_registerSolverFactory.cpp.o: file not recognized: File truncated
make[2]: *** [packages/belos/epetra/src/libbelosepetra.so.12.17] Error 1
make[2]: Leaving directory `/home1/07571/barundas/Scratch/Trilinos/build'
make[1]: *** [packages/belos/epetra/src/CMakeFiles/belosepetra.dir/all] Error 2
CMakeFiles/belostpetra.dir/solvers/Belos_Tpetra_GmresPoly.cpp.o: file not recognized: File truncated
make[2]: *** [packages/belos/tpetra/src/libbelostpetra.so.12.17] Error 1
make[2]: Leaving directory `/home1/07571/barundas/Scratch/Trilinos/build'
make[1]: *** [packages/belos/tpetra/src/CMakeFiles/belostpetra.dir/all] Error 2
make[1]: Leaving directory `/home1/07571/barundas/Scratch/Trilinos/build'
make: *** [all] Error 2

**Comment by jhux2** [comment]
@bdas123 Is it possible that you've run out of disk space:  `file not recognized: File truncated`?

Otherwise, please post the version of Trilinos, your cmake configure script, and compiler/MPI versions.

**Comment by bdas123** [comment]
I went to a part of the system that gave more disk space. 

Here is the error I am now getting: CMakeFiles/ifpack2.dir/Ifpack2_Details_registerLinearSolverFactory.cpp.o: file not recognized: File truncated
make[2]: *** [packages/ifpack2/src/libifpack2.so.12.17] Error 1
make[2]: Leaving directory `/work/07571/barundas/stampede2/Scratch/Trilinos/build'
make[1]: *** [packages/ifpack2/src/CMakeFiles/ifpack2.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
CMakeFiles/stratimikos.dir/Stratimikos_DefaultLinearSolverBuilder.cpp.o: file not recognized: File truncated
make[2]: *** [packages/stratimikos/src/libstratimikos.so.12.17] Error 1
make[2]: Leaving directory `/work/07571/barundas/stampede2/Scratch/Trilinos/build'
make[1]: *** [packages/stratimikos/src/CMakeFiles/stratimikos.dir/all] Error 2
make[1]: Leaving directory `/work/07571/barundas/stampede2/Scratch/Trilinos/build'
make: *** [all] Error 2

**Comment by jhux2** [comment]
Are you using parallel make?   It's possible that the compile failed in another thread, and the error is higher up.  Try piping make to a file, then looking for failures in that file.  Also see my comment above.

**Comment by cgcgcg** [comment]
@bdas123 Has this been resolved?

**Comment by bdas123** [comment]
Hello! Yes it has

**Comment by jhux2** [comment]
@bdas123 In the interest of contributing to the Trilinos community, could you please post your solution?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
