### ISSUE TITLE
cmake/TPLs:  SuperLU configure test fails incorrectly, resulting in failing Amesos compilation

### ISSUE THREAD

**Issue by ecoon** [trilinos/Trilinos#7838]
## Bug Report
@trilinos/cmake?  @trilinos/amesos

### Description
SuperLU_dist now includes C++ code, so, in static builds of Trilinos with SuperLU_dist, the configure test at:

https://github.com/trilinos/Trilinos/blob/2761e293602a70e98441268b8e18bcfd81d38f8e/cmake/TPLs/FindTPLSuperLUDist.cmake#L107

fails not because SuperLU_dist is the 3-argument version, but because it can't link in the c++ standard library dependencies.

### Steps to Reproduce
1. SHA1:  master
2. configure with SuperLU_dist version 6 (which includes the 2-Argument version of LUstructInit() ).
3. Bang head against wall when Amesos fails to compile because it can't find the 3-argument version of LUstructInit()
4. read the configure logs to see that `CHECK_SUPERLUDIST_LUSTRUCTINIT()` fails, so Amesos thinks it has 3-Argument version.
5. dive deeper into CMake hell to find the output of that test, realize it is failing because (only in static builds, not in shared builds) it fails to link in libc++.
6. realize this is a C compiler being used.

Below I have attached CMakeError.log evidence of static libs failing to link because of C++ symbols in SuperLU_dist.
[CMakeError.log](https://github.com/trilinos/Trilinos/files/5075215/CMakeError.log)

### Steps to fix:

replace line linked above with:

`CHECK_CXX_SOURCE_COMPILES("${SOURCE}" ${VARNAME})`

Probably the same should be done at line 85 as well.

**Comment by jhux2** [comment]
@trilinos/amesos @trilinos/framework

**Comment by ecoon** [comment]
I haven't looked to see if this is still an issue, but I don't see why it wouldn't be.  We're still patching Trilinos in case someone tries to build with recent SuperLU, recent compilers, but static builds (see the linked PR in Amanzi above for a detailed desccription) though who builds static builds anymore?

**Comment by GrahamBenHarper** [comment]
@ecoon was your issue fixed by #11365?
