### ISSUE TITLE
Tempus: tests Tempus_HHTAlpha_MPI_1, Tempus_DIRK_ASA_MPI_1 and Tempus_ExplicitRK_ASA_MPI_1 time out in debug mode

### ISSUE THREAD

**Issue by prwolfe** [trilinos/Trilinos#7861]
## Enhancement
@trilinos/tempus 

These tests do not run in the 600 seconds allowed for PR testing in debug mode. We would like all tests to be run to confirm the capability in debug.

**Comment by ccober6** [comment]
Yeah, I know.  I have two PRs that hopefully will go through today that should fix these.  I will complain that these tests only take 4-8 seconds on my Mac laptop in opt mode.  I am going to check how long they take in debug mode, but it seems that these platforms are very slow.
