### ISSUE TITLE
Trilinos Release 13.0

### ISSUE THREAD

**Issue by ZUUL42** [trilinos/Trilinos#7877]
@trilinos/framework 

Create Trilinos Release 13.0

Branch: [trilinos-release-13-0-branch](https://github.com/trilinos/Trilinos/tree/trilinos-release-13-0-branch)
Jenkins Autotester Job: Trilinos_autotester_driver_rel_13_00
Tag: [trilinos-release-13-0-0](https://github.com/trilinos/Trilinos/releases/tag/trilinos-release-13-0-0)
Doxygen: [http://docs.trilinos.org/r13.0/](http://docs.trilinos.org/r13.0)

**Comment by ZUUL42** [comment]
Doxygen scripts modified to generate 13.0 on 2020/08/14.
Cron job running successfully since.

**Comment by jwillenbring** [comment]
The Trilinos 13 release is done.
