### ISSUE TITLE
TriBITS:  Permission errors trying to install Trilinos on Mac due to stat -c

### ISSUE THREAD

**Issue by ndellingwood** [trilinos/Trilinos#7881]
### Description
Attempting to install Trilinos on my MacOSX failed due to permission errors `stat illegal option -c` at this line

https://github.com/trilinos/Trilinos/blob/03ec279787739303ea4c2e5d3560857a05b58479/cmake/tribits/core/installation/set_installed_group_and_permissions.cmake.in#L31

Apparently this is because Darwin's binutils is not gnu binutils, and uses  `-f` instead of `-c` as argument

I can confirm this change allowed me to complete an install:
```bash
-  EXECUTE_PROCESS(COMMAND stat -c %U "${dirPath}"
+  EXECUTE_PROCESS(COMMAND stat -f "%Su" "${dirPath}"
```

**Comment by ndellingwood** [comment]
@bartlettroscoe I ran into this problem trying to install Trilinos on my Mac, is this something I should open an issue for in the TriBITS github repo, or is this case no longer supported?

**Comment by bartlettroscoe** [comment]
@ndellingwood, sorry I missed the creation of this Issue.  (In the future, make sure and add @bartlettroscoe so I will see this.)  This should likely be a TriBITS issue but it is okay here now that you have it.

It should be easy to fix this to work on the Mac as well.  Or, if you are not using the install permissions, we can avoid calling this altogether.  Are you using any the permissions fix-up options documented at:

* https://docs.trilinos.org/files/TrilinosBuildReference.html#setting-install-ownership-and-permissions

?

This permissions fix-up system was added to deal with some very difficult systems at SNL that don't allow setuid or the group sticky bit.  I doubt that is a problem for any  MacOSX system.

**Comment by ndellingwood** [comment]
> Are you using any the permissions fix-up options documented at

@bartlettroscoe I don't think so, I'm only setting the install path via `CMAKE_INSTALL_PREFIX` but none of the other options documented on the link you sent. One issue is that my Mac calls the Darwin binutils instead of the gnu version (requiring different arguments), but should I not be hitting that code path regardless since I'm not using the permission fix-up?

Here is my cmake line:
```bash
cmake \
 -DTPL_ENABLE_MPI:BOOL=ON \
 -DCMAKE_CXX_COMPILER=`which mpicxx` \
 -DCMAKE_C_COMPILER=`which mpicc` \
 -DCMAKE_Fortran_COMPILER:FILEPATH=`which mpifort` \
 -DCMAKE_INSTALL_PREFIX=${TRILINOS_INSTALL_PATH} \
 -DBUILD_TESTING:BOOL=OFF \
 -DTrilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=OFF \
 -DTrilinos_ASSERT_MISSING_PACKAGES:BOOL=OFF \
 -D TPL_ENABLE_BLAS:STRING=ON \
 -D TPL_ENABLE_LAPACK:STRING=ON \
  -D TPL_BLAS_LIBRARIES:PATH="${BLAS_LIBRARIES}" \
  -D TPL_LAPACK_LIBRARIES:PATH="${LAPACK_LIBRARIES}" \
 -DTrilinos_ENABLE_Belos:BOOL=ON \
 -DTrilinos_ENABLE_Anasazi:BOOL=ON \
 -DTrilinos_ENABLE_Tpetra:BOOL=ON \
 -DTrilinos_ENABLE_Ifpack2:BOOL=ON \
 -DTrilinos_ENABLE_OpenMP:BOOL=ON \
 -DKokkos_ENABLE_OpenMP:BOOL=ON \
 -DTpetra_INST_OPENMP:BOOL=ON \
$TRILINOS_PATH
```

**Comment by bartlettroscoe** [comment]
It is not okay that this is breaking installs of Trilinos on MacOSX systems where the user is not even setting any of these options.  I guess I would like to get this to work on MacOSX too.  But the first priority is to just skip all of this code if none of these options are set.  That should be pretty easy to do.

**Comment by bartlettroscoe** [comment]
@ndellingwood, the fix in TriBITS is in https://github.com/TriBITSPub/TriBITS/pull/327.  Just need to have that reviewed then I can merge to TriBITS 'master' then snapshot to Trilinos and create a Trilinos PR.

**Comment by ndellingwood** [comment]
Thanks @bartlettroscoe ! I'm not very knowledgeable of TriBITS' internals, but if needed I can give a go reviewing the PR

**Comment by bartlettroscoe** [comment]
@ndellingwood, if this is needed urgently, I can go ahead and merge this and then @jmgate can review after the fact and I can address issues in follow-on commits and PRs.

This is such simple code and has such a strong test I can about 100% guarantee this will fix your problem.

**Comment by ndellingwood** [comment]
@bartlettroscoe it's not urgent, I don't mind waiting until the review process is complete. Thanks!

**Comment by bartlettroscoe** [comment]
@ndellingwood, this is resolved in PR #8063.  In my opinion, that PR is ready to merge (it just needs to be approved).  Any remaining review comments can be addressed in https://github.com/TriBITSPub/TriBITS/pull/332.

**Comment by bartlettroscoe** [comment]
@ndellingwood, with the merge of PR #8063 this issue should be resolved.  Can you please confirm and close this Issue?

**Comment by ndellingwood** [comment]
@bartlettroscoe I tested on my mac and confirmed the changes resolved the install issue, thanks!
