### ISSUE TITLE
Trilinos build options not frequently used

### ISSUE THREAD

**Issue by keitat** [trilinos/Trilinos#7889]
Spack team is asking if the Trilinos build options listed below should be supported by Spack.    I guess many of them are outdated or no longer maintained.  For example, I do not see any value of using Pthread in practical situations.   If you see any of options makes sense for Spack users, please let me know.

- Enabling CTrilinos
- Enabling CPPUnit Tests
- Enabling PThread Support
- Enabling QT Support
- Enabling Trilinos Couplings
- Enabling Didasko
- Enabling Built in Examples
- Enabling Expat support
- Enabling GMP support
- Enabling libxml2 support
- Enabling built-in tests

**Comment by csiefer2** [comment]
There are so many different build options for Trilinos that having a single Trilinos spack configuration seems exceptionally limiting.

So who exactly are the intended Trilinos spack users?

**Comment by keitat** [comment]
I am expecting that most Spack Trilinos users want to use Trilinos from their applications on genetic production settings including OpenMP, CUDA, HIP and Intel's-oneAPI.  Among these options, only the libxml and built in examples options reasonable to me.  I am curious CTrilinos is frequently used.  To be honest, it should be provided as a separated library package like ForTrillinos.
