### ISSUE TITLE
importAndFillComplete (and analogous Epetra constructor) for CrsGraph

### ISSUE THREAD

**Issue by kddevin** [trilinos/Trilinos#79]
@trilinos/tpetra  
Chris Siefert directed my attention to the new importAndFillComplete utility in Tpetra::CrsMatrix, and an analogous constructor for Epetra_CrsMatrix.
It would be nice (but not urgent) to have analogous capability for CrsGraph.

**Comment by aprokop** [comment]
Can someone write a full description? What does this utility do? What is the difference with existing routines? Is it expected to improve performance?

**Comment by csiefer2** [comment]
We've had importAndFillComplete for CrsMatrix (and the Epetra analogue) for a year or two (side products from the MMM work).  They basically allow you to (efficiently) merge and Import and FillComplete of a "pristine" matrix into a single operation.  They bypass a bunch of serial work and some of the parallel communication for neighbor discovery by being smarter.

Karen has requested that we do something similar for CrsGraph which Mark and I agree would be quite nice for Zoltan2.

**Comment by mhoemmen** [comment]
Fixing #2267 would fix the Tpetra part of this issue.  If Epetra is still of interest, please open a separate issue for the requested Epetra feature.  I will therefore close this issue as a duplicate of #2267.
