### ISSUE TITLE
Intrepid2: refactor branch documentation

### ISSUE THREAD

**Issue by rppawlo** [trilinos/Trilinos#790]
In the intrepid2 refactor branch, some functions were modified to require scratch space. However the doxygen documentation was not modified to describe the scratch space requirements. Without diving into the implementation I don't know what the rank or size of the DynRankView scratch space should be prior to calling the function. 

An example of this is in the Intrepid2_FcuntionSpaceTools.hpp in the computeFaceMeasure() function.

This ticket is to request documentation be updated. Mention rank and size requirements for scratch space.

**Comment by rppawlo** [comment]
CellTools:checkPointwiseInclusion doxygen documentation is also incorrect.

**Comment by rppawlo** [comment]
@trilinos/intrepid2

**Comment by mperego** [comment]
We still need to update the documentation for several functions/classes in the refactored part of the code.
We plan to work on this in the next weeks.
