### ISSUE TITLE
STK Missing Headers for SIMD: Nalu and Nalu-wind build issues

### ISSUE THREAD

**Issue by spdomin** [trilinos/Trilinos#7900]
## Bug Report
@trilinos/STK

### Description
Hi @alanw0 or @jvo1012 - where are the new STK simd files located? 

How did this commit work without a build error? 

/gcc8.3.0/Trilinos_nightly_release/include/stk_simd/Simd.hpp:59:10: fatal error: kokkos_simd/simd.hpp: No such file or directory
 #include "kokkos_simd/simd.hpp"
          ^~~~~~~~~~~~~~~~~~~~~~

Possible a new config flag? Below is what I have now...

```
-DTrilinos_ENABLE_STKMesh:BOOL=ON \
-DTrilinos_ENABLE_STKSimd:BOOL=ON \
-DTrilinos_ENABLE_STKIO:BOOL=ON \
-DTrilinos_ENABLE_STKTransfer:BOOL=ON \
-DTrilinos_ENABLE_STKSearch:BOOL=ON \
-DTrilinos_ENABLE_STKUtil:BOOL=ON \
-DTrilinos_ENABLE_STKTopology:BOOL=ON \
-DTrilinos_ENABLE_STKBalance:BOOL=OFF \
-DTrilinos_ENABLE_STKUnit_tests:BOOL=OFF \
-DTrilinos_ENABLE_STKUnit_test_utils:BOOL=OFF \
```

**Comment by alanw0** [comment]
@tasmith4 is the knowledgeable part here. Good question, it's obviously working for sierra builds, perhaps there is something not right in the cmake support.

**Comment by alanw0** [comment]
@tasmith4 It looks like the nalu-wind dashboard is also in complete meltdown. @sayerhs

**Comment by spdomin** [comment]
It probably would be rather simple to add a Nalu or Nalu-wind build as part of the STK development cycle. We may be simply in a bad luck patch, however, it almost feels like I am in an O(1) per week Trilinos bisect/build/run issue cycle (muleu, ifpack2, stk). Perhaps an agenda item to add to @jwillenbring monthly Trilinos meeting?

**Comment by alanw0** [comment]
Clearly we have to do something different. We've gotten close to the point where stk tests provide adequate correctness testing, but our cmake/installation testing is a huge problem.

**Comment by tasmith4** [comment]
So, the `kokkos_simd` directory is in `stk/stk_simd/stk_simd`.  `stk/stk_simd/stk_simd/CMakeLists.txt` declares `CMAKE_CURRENT_SOURCE_DIR` as an include directory, so I'm surprised it can't pick up `kokkos_simd/simd.hpp`.

Further, I really don't understand how this passes PR testing then crashes all the dashboards, if it's really a CMake include issue.  Obviously something more or less subtle going on here.

I'm in and out of a class all day, so won't get a chance to look at this in detail until tomorrow morning.  In the meantime @alanw0 do you want to revert the snapshot?

**Comment by alanw0** [comment]
This probably means it is an install issue, which doesn't (probably) get tested at all by the trilinos PR testing.
I will revert it.

**Comment by spdomin** [comment]
@crtrott, I think even after @alanw0's revert, I am now seeing:

/Users/naluIt/gitHubWork/packages/install/Trilinos_nightly_release/include/Kokkos_Timer.hpp:58:15: error: 
      no member named 'Timer' in namespace 'Kokkos'
using Kokkos::Timer;

- not sure...

**Comment by spdomin** [comment]
@jwillenbring and @maherou, what is the process to discuss recent application Trilinos experiences?

**Comment by spdomin** [comment]
Transitioned kokkos::timer to: https://github.com/trilinos/Trilinos/issues/7907
