### ISSUE TITLE
README:  Wrong documentation path

### ISSUE THREAD

**Issue by cook-1229** [trilinos/Trilinos#7905]
## Documentation
@trilinos/README

The Trilinos README directs the user to '<trilinos_base_directory>/TrilinosBuildQuickRef.*' for information on how to build the software.  This file does not exist.

**Comment by jhux2** [comment]
@maherou @jwillenbring

**Comment by jhux2** [comment]
@cook-1229 This is now fixed in the develop branch (see https://github.com/trilinos/Trilinos/blob/develop/README) and should be fixed shortly in master after the next automatic promotion.

**Comment by cook-1229** [comment]
Looks good.  Thank you!
