### ISSUE TITLE
SEACAS:  Missing library when linking nemesis (and others)

### ISSUE THREAD

**Issue by cook-1229** [trilinos/Trilinos#7906]
## Bug Report
@trilinos/SEACAS

### Description
Using the libraries offered by the Ubuntu 20.04 repos (so no custom linking paths), I ran into missing libraries when linking.  For example,
```
/usr/bin/mpicxx     -O3 -DNDEBUG   CMakeFiles/SEACASNemesis_ne_ctest_wrap.dir/ne_ctest_wrap.c.o  -o SEACASNemesis_ne_ctest_wrap.exe  libnemesis.a ../exodus/libexodus.a /usr/lib/x86_64-linux-gnu/libnetcdf.so
```
fails.  I added `-lhdf5_serial` manually, and the linking finished without error  Alternatively, `/usr/lib/x86_64-linux-gnu/libhdf5_serial.a` works too.

With that fixed, SEACAS moved onto a series of failed linkings because the ```-lhdf5_serial -lsz -lz -laec``` libraries were missing.  Sphgen and io_shell are examples.   I fixed several of these errors manually in the hope there wouldn't be many, but they keep coming.

The Makefiles do not appear to recognize the value of LDFLAGS in the environment.

### Steps to Reproduce
1. SHA1:  Version 13 tarball
1. 
```
cmake \
  -D Trilinos_VERBOSE_CONFIGURE:BOOL=ON \
  -D CMAKE_VERBOSE_MAKEFILE:BOOL=TRUE \
  -D CMAKE_BUILD_TYPE:STRING=RELEASE \
  -D TPL_ENABLE_BinUtils:BOOL=OFF \
  -D TPL_ENABLE_MPI:BOOL=ON \
  -D MPI_BASE_DIR:PATH=$MPIHOME \
  -D TPL_ENABLE_BLAS:BOOL=ON \
  -D TPL_ENABLE_LAPACK:BOOL=ON \
  -D TPL_ENABLE_Boost:BOOL=ON \
  -D TPL_ENABLE_Netcdf:BOOL=ON \
  -D TPL_ENABLE_Matio:BOOL=OFF \
  -D TPL_ENABLE_X11:BOOL=OFF \
  -D Trilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=OFF \
  -D Trilinos_ENABLE_Amesos:BOOL=ON \
  -D Trilinos_ENABLE_Amesos2:BOOL=ON \
  -D Trilinos_ENABLE_AztecOO:BOOL=ON \
  -D Trilinos_ENABLE_Belos:BOOL=ON \
  -D Trilinos_ENABLE_Epetra:BOOL=ON \
  -D Trilinos_ENABLE_EpetraExt:BOOL=ON \
  -D Trilinos_ENABLE_Tpetra:BOOL=ON \
  -D Trilinos_ENABLE_Xpetra:BOOL=ON \
  -D Trilinos_ENABLE_Thyra:BOOL=ON \
  -D Trilinos_ENABLE_Kokkos:BOOL=ON \
  -D Trilinos_ENABLE_Ifpack:BOOL=ON \
  -D Trilinos_ENABLE_Ifpack2:BOOL=ON \
  -D Trilinos_ENABLE_ML:BOOL=ON \
  -D Trilinos_ENABLE_MueLu:BOOL=ON \
  -D Trilinos_ENABLE_MueLu_ENABLE_Amesos2::BOOL=ON \
  -D Trilinos_ENABLE_ROL:BOOL=ON \
  -D Trilinos_ENABLE_SEACAS:BOOL=ON \
  -D SEACASExodus_ENABLE_MPI:BOOL=OFF \
  -D Trilinos_ENABLE_Teko:Bool=ON \
  -D Trilinos_ENABLE_Teuchos:BOOL=ON \
  -D Teuchos_ENABLE_COMPLEX:BOOL=OFF \
  -D Trilinos_ENABLE_Triutils:BOOL=ON \
  -D Trilinos_ENABLE_Zoltan:BOOL=ON \
  -D Trilinos_ENABLE_Zoltan2:BOOL=ON \
  -D Trilinos_ENABLE_TESTS:BOOL=OFF \
  -D Trilinos_ENABLE_DEBUG:BOOL=OFF \
  -D Trilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON \
  ${trilinos_path}
```
1. Run into missing library message. 
1. cd to path, manually copy-paste the call to the linker with the libraries added
1. cd back to main build directory
1. ```make```
1. Run into missing library message.
1. Repeat.

**Comment by jhux2** [comment]
@trilinos/seacas

**Comment by jhux2** [comment]
@cook-1229 Please try adding locations of the TPLs like HDF5, netcdf, etc.  See https://docs.trilinos.org/files/TrilinosBuildReference.html#enabling-support-for-an-optional-third-party-library-tpl.

**Comment by cook-1229** [comment]
Thanks for the response, @jhux2.  I can't reach that webpage, likely due to network problems on my side.  Still, in Makefile.Trilinos.export, I see
```
Trilinos_TPL_LIST= DLlib Netcdf Boost LAPACK BLAS MPI
```
None of those libraries are the ones missing.  It's ```-lhdf5_serial -lsz -lz -laec``` missing, all of which are located in the standard system folder /usr/lib/x86_64-linux-gnu.

**Comment by jhux2** [comment]
Ah, I misunderstood the issue.  Could you add this flag`-DCMAKE_EXE_LINKER_FLAGS="-L/usr/lib/x86_64-linux-gnu -lhdf5_serial -lsz -lz -laec"` and reconfigure/rebuild?  (I think I got the quotes right.)  This adds those libraries unconditionally to all the link lines.  Be sure to blow away the `CMakeCache.txt` file and `CMakeFiles` directory.

**Comment by cook-1229** [comment]
Using ```-DCMAKE_EXE_LINKER_FLAGS="-L/usr/lib/x86_64-linux-gnu -lhdf5_serial ``` as suggested, the linker flags are inclued...but at the wrong spot.
```
$ /usr/bin/mpicxx     -O3 -DNDEBUG  -L/usr/lib/x86_64-linux-gnu -lhdf5_serial -lsz -lz -laec CMakeFiles/SEACASNemesis_ne_ctest_wrap.dir/ne_ctest_wrap.c.o  -o SEACASNemesis_ne_ctest_wrap.exe  libnemesis.a ../exodus/libexodus.a /usr/lib/x86_64-linux-gnu/libnetcdf.so
/usr/bin/ld: ../exodus/libexodus.a(ex_utils.c.o): undefined reference to symbol 'H5get_libversion@@HDF5_SERIAL_1.8.7'
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libhdf5_serial.so: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```
Manually moving those libraries to the end matches the linker search order, resulting in success.
```
$ /usr/bin/mpicxx     -O3 -DNDEBUG  -L/usr/lib/x86_64-linux-gnu CMakeFiles/SEACASNemesis_ne_ctest_wrap.dir/ne_ctest_wrap.c.o  -o SEACASNemesis_ne_ctest_wrap.exe  libnemesis.a ../exodus/libexodus.a /usr/lib/x86_64-linux-gnu/libnetcdf.so -lhdf5_serial -lsz -lz -laec
```
I wonder if ```CMAKE_LINK_LIBRARY_FLAG``` might be what we are looking for instead?  I'm not very familiar with CMake.

**Comment by cook-1229** [comment]
Nope, CMAKE_LINK_LIBRARY_FLAG is not the solution.  I wonder if Exodus (and others) are lacking the configuration that they need these libraries?

**Comment by cook-1229** [comment]
Excuse me, I wrote Exodus, but the issue is appearing in the linking of SEACASNemesis_ne_ctest_wrap.exe.

**Comment by jhux2** [comment]
Hmm, @gsjaardema is the SEACAS expert and might have to weigh in here.

**Comment by jhux2** [comment]
@bartlettroscoe might also know how to get the link order correct, so that `-L/usr/lib/x86_64-linux-gnu -lhdf5_serial -lsz -lz -laec` shows up after `/usr/lib/x86_64-linux-gnu/libnetcdf.so`.

**Comment by cook-1229** [comment]
Looking in the SEACAS README.md, I found ```Trilinos_EXTRA_LINK_FLAGS```.  I set ```-D Trilinos_EXTRA_LINK_FLAGS:STRING="-lhdf5_serial -lsz -lz -laec"``` in the cmake call, and the compilation completed without error.

These libraries are required to compile SEACAS, suggesting that they be part of the default build configuration wherever netcdf is linked.  I wonder how other builds would not encounter this problem.

I was finally able to read the webpage linked above, a helpful resource if I would have been able to reach it at the beginning.

**Comment by jhux2** [comment]
@cook-1229 Glad you were able to figure it out!

**Comment by gsjaardema** [comment]
I'm not sure why you had to go through this.  Typically, the `libnetcdf.so` will correctly pull in all of its dependencies so this is not required.  There is also CMake code which will determine the dependencies of a static NetCDF and/or HDF5 library and correctly add them and set the additional symbols that tell code using the libraries what capabilities they have.

In your case, it looks like none of these were working correctly and you had to manually specify the libraries and all of the dependencies...  Perhaps we need to look deeper into why CMake did not correctly deduce this information in this case, but it does in many other cases...

**Comment by jmbr** [comment]
I had the same problem as @cook-1229 on Ubuntu 20.04.3 and got past that problem thanks to the `Trilinos_EXTRA_LINK_FLAGS`.

**Comment by jml-1** [comment]
> Looking in the SEACAS README.md, I found `Trilinos_EXTRA_LINK_FLAGS`. I set `-D Trilinos_EXTRA_LINK_FLAGS:STRING="-lhdf5_serial -lsz -lz -laec"` in the cmake call, and the compilation completed without error.
> 
> These libraries are required to compile SEACAS, suggesting that they be part of the default build configuration wherever netcdf is linked. I wonder how other builds would not encounter this problem.
> 
> I was finally able to read the webpage linked above, a helpful resource if I would have been able to reach it at the beginning.

thank U very much。I use the this tip slove my problem。 best wish to you.
