### ISSUE TITLE
Muelu: internal compiler error: in reload_cse_simplify_operands, at postreload.c

### ISSUE THREAD

**Issue by sagitter** [trilinos/Trilinos#791]
Hi all.

This is a compiler error that comes out by compiling `Trilinos` on a `RHEL7` build-system (`PowerPC 64-bit`):

```
In file included from /builddir/build/BUILD/trilinos-12.8.1/Trilinos-trilinos-release-12-8-1/packages/muelu/src/Interface/../Smoothers/MueLu_SmootherPrototype_decl.hpp:52:0,
                 from /builddir/build/BUILD/trilinos-12.8.1/Trilinos-trilinos-release-12-8-1/build/packages/muelu/src/MueLu_SmootherPrototype.hpp:1,
                 from /builddir/build/BUILD/trilinos-12.8.1/Trilinos-trilinos-release-12-8-1/packages/muelu/src/Interface/../Smoothers/MueLu_Ifpack2Smoother_decl.hpp:74,
                 from /builddir/build/BUILD/trilinos-12.8.1/Trilinos-trilinos-release-12-8-1/build/packages/muelu/src/MueLu_Ifpack2Smoother.hpp:1,
                 from /builddir/build/BUILD/trilinos-12.8.1/Trilinos-trilinos-release-12-8-1/packages/muelu/src/Interface/../Smoothers/MueLu_SmootherCloner.hpp:56,
                 from /builddir/build/BUILD/trilinos-12.8.1/Trilinos-trilinos-release-12-8-1/packages/muelu/src/Interface/../MueCentral/MueLu_Hierarchy_decl.hpp:59,
                 from /builddir/build/BUILD/trilinos-12.8.1/Trilinos-trilinos-release-12-8-1/build/packages/muelu/src/MueLu_Hierarchy.hpp:1,
                 from /builddir/build/BUILD/trilinos-12.8.1/Trilinos-trilinos-release-12-8-1/packages/muelu/src/Interface/../Headers/MueLu.hpp:68,
                 from /builddir/build/BUILD/trilinos-12.8.1/Trilinos-trilinos-release-12-8-1/packages/muelu/adapters/tpetra/MueLu_RefMaxwell_decl.hpp:49,
                 from /builddir/build/BUILD/trilinos-12.8.1/Trilinos-trilinos-release-12-8-1/packages/muelu/adapters/tpetra/MueLu_RefMaxwell_def.hpp:55,
                 from /builddir/build/BUILD/trilinos-12.8.1/Trilinos-trilinos-release-12-8-1/packages/stokhos/src/sacado/kokkos/pce/muelu/MueLu_RefMaxwell_UQ_PCE_Serial.cpp:53:
/builddir/build/BUILD/trilinos-12.8.1/Trilinos-trilinos-release-12-8-1/packages/muelu/src/Interface/../MueCentral/MueLu_Factory.hpp: In member function 'Teuchos::RCP<Teuchos::ParameterList> MueLu::Factory::RemoveFactoriesFromList(const Teuchos::ParameterList&) const':
/builddir/build/BUILD/trilinos-12.8.1/Trilinos-trilinos-release-12-8-1/packages/muelu/src/Interface/../MueCentral/MueLu_Factory.hpp:127:5: error: insn does not satisfy its constraints:
     }
     ^
(insn 868 210 869 5 (set (reg:DI 7 7)
        (reg:DI 38 6 [orig:145 ivtmp.20487 ] [145])) /usr/include/c++/4.8.2/bits/stl_deque.h:154 518 {*movdi_internal64}
     (nil))
/builddir/build/BUILD/trilinos-12.8.1/Trilinos-trilinos-release-12-8-1/packages/muelu/src/Interface/../MueCentral/MueLu_Factory.hpp:127:5: internal compiler error: in reload_cse_simplify_operands, at postreload.c:411
```

`cmake` configure:

`+ /usr/bin/cmake -DCMAKE_C_FLAGS_RELEASE:STRING=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE:STRING=-DNDEBUG -DCMAKE_Fortran_FLAGS_RELEASE:STRING=-DNDEBUG -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DCMAKE_INSTALL_PREFIX:PATH=/usr -DINCLUDE_INSTALL_DIR:PATH=/usr/include -DLIB_INSTALL_DIR:PATH=/usr/lib64 -DSYSCONF_INSTALL_DIR:PATH=/etc -DSHARE_INSTALL_PREFIX:PATH=/usr/share -DLIB_SUFFIX=64 -DBUILD_SHARED_LIBS:BOOL=ON -DCMAKE_BUILD_TYPE:STRING=Release '-DCMAKE_C_FLAGS_RELEASE:STRING=-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mcpu=power7 -mtune=power7 -Wl,-z,relro -fPIC -Wl,-z,now' '-DCMAKE_CXX_FLAGS_RELEASE:STRING=-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mcpu=power7 -mtune=power7 -Wl,-z,relro -fPIC -Wl,-z,now' '-DCMAKE_Fortran_FLAGS_RELEASE:STRING=-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mcpu=power7 -mtune=power7 -Wl,-z,relro -fPIC -Wl,-z,now' '-DCMAKE_EXE_LINKER_FLAGS:STRING=-Wl,-z,relro  -fPIC -pie -Wl,-z,now -Wl,--as-needed' -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_SKIP_RPATH:BOOL=YES -DCMAKE_SKIP_INSTALL_RPATH:BOOL=YES -DBUILD_SHARED_LIBS:BOOL=ON -DTPL_ENABLE_MPI=OFF -DTrilinos_ENABLE_FORTRAN:BOOL=ON -DTrilinos_ENABLE_OpenMP:BOOL=ON -DTrilinos_ENABLE_PyTrilinos:BOOL=OFF -DTpetra_INST_SERIAL:BOOL=ON -DCMAKE_VERBOSE_MAKEFILE=TRUE -DTrilinos_VERBOSE_CONFIGURE=OFF -DTrilinos_ENABLE_CXX11=ON -DTPL_Boost_INCLUDE_DIRS:PATH=/usr/include/boost148 -DTPL_Boost_LIBRARIES:PATH=/usr/lib64/boost148/libboost_system.so:/usr/lib64/boost148/libboost_program_options.so:/usr/lib64/boost148/libboost_signals.so:/usr/lib64/boost148/libboost_regex.so:/usr/lib64/boost148/libboost_filesystem.so:/usr/lib64/boost148/libboost_thread.so:/usr/lib64/boost148/libboost_wserialization.so:/usr/lib64/boost148/libboost_serialization.so -DTrilinos_INSTALL_INCLUDE_DIR=/usr/include/trilinos -DTrilinos_INSTALL_LIB_DIR=/usr/lib64 -DTrilinos_INSTALL_RUNTIME_DIR=/usr/bin -DTrilinos_INSTALL_EXAMPLE_DIR=/usr/share/trilinos/examples -DTrilinos_ENABLE_STRONG_C_COMPILE_WARNINGS=OFF -DTrilinos_ENABLE_STRONG_CXX_COMPILE_WARNINGS=OFF -DTrilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON -DTPL_ENABLE_gtest:BOOL=OFF -DTrilinos_ENABLE_STK:BOOL=OFF -DTrilinos_ENABLE_ALL_PACKAGES=ON -DTrilinos_NO_64BIT_GLOBAL_INDICES=ON ..`

GCC 4.8.5
Full build log: http://koji.fedoraproject.org/koji/getfile?taskID=16356006&name=build.log

**Comment by mhoemmen** [comment]
Try GCC 4.7.2 or 4.8.4 or 5.3.0?  I've never see this before.

**Comment by mhoemmen** [comment]
@trilinos/muelu

**Comment by jhux2** [comment]
Not sure what's going on. I've never seen this either.

**Comment by mhoemmen** [comment]
64-bit PowerPC?!?  I don't recall seeing anyone try a Trilinos build on that platform since I started working on Trilinos.  We care about IBM Power (see https://asc.llnl.gov/coral-info), but PowerPC is an entirely different architecture.

@sagitter , this looks like a compiler bug, not a Trilinos issue.  You're welcome to try making things work on that platform, but we wouldn't be able to help.  I would first suggest trying a newer version of GCC, if it exists.  If you can't find a compiler that works, I would suggest cloning our develop branch, trying to work around the compiler bug, and then submitting a pull request to the develop branch with your changes.  We have no way to test them with 64-bit PowerPC, so we would have to trust you that they work.  We would of course test them on other platforms before considering them them.  Furthermore, if the changes look cryptic or "weird," we will reject them without testing them.  I'm sorry to say such a thing, but I hope you can understand the importance of serving our primary customers.  I appreciate your help and interest in working on this.

**Comment by sagitter** [comment]
>@sagitter , this looks like a compiler bug, not a Trilinos issue. You're welcome to try making things work on that platform, but we wouldn't be able to help. I would first suggest trying a newer version of GCC, if it exists.

Let me test Trilinos on Fedora PPC64 that uses GCC 6.2.1
There are other platforms like ARM/ARM64/s390 on which i can build, are supported in case?

**Comment by mhoemmen** [comment]
@sagitter wrote:
> There are other platforms like ARM/ARM64/s390 on which i can build, are supported in case?

We do care about ARM, but our primary testing platforms these days are x86, KNL, IBM Power, and NVIDIA GPUs.  All of these are 64-bit only.

**Comment by sagitter** [comment]
>Try GCC 4.7.2 or 4.8.4 or 5.3.0? I've never see this before.

Not exactly. I'm testing `Trilinos` builds on different platforms:

(Main) 
       Fedora: `x686, x86_64, ppc64, ppc64le, arm, arm64, s390` (`GCC 6.2.1`)

(Additional)
       [RHEL](https://fedoraproject.org/wiki/EPEL)6: `x686, x86_64, ppc64` (`GCC 4.4.7`)
       [RHEL](https://fedoraproject.org/wiki/EPEL)7: `x86_64, ppc64, ppc64le, arm64` (`GCC 4.8.5`)

Currently (since you said me that you're testing on `64-bit` only), i'm working on 64-bit only.

>@sagitter , this looks like a compiler bug, not a Trilinos issue.

In fact, it's working with `GCC 6.2.1` on Fedora PPC64.

As of now, i see that `Trilinos` compiles fine on Fedora with 64-bit architectures.
RHEL6 systems are excluded because of unavailable `CXX11` function (GCC 4.4.7), unless exist Trilinos packages which compile without `CXX11`.

**Comment by sagitter** [comment]
I have disabled `MueLu`, all other packages are compiled fine with `GCC 4.8.5`

**Comment by mhoemmen** [comment]
@sagitter wrote:
> In fact, it's working with GCC 6.2.1 on Fedora PPC64.

Good to know -- thanks for checking!  btw I appreciate all your efforts testing Trilinos on these platforms.  I don't know if this is your job or if you are a volunteer, but either way, it's kind of you and/or your employer to take an interest in Trilinos.

> ... unless there exist Trilinos packages which compile without CXX11.
 
There definitely do exist Trilinos packages which compile without CXX11.  However, it would be better to require C++11, considering that almost all new Trilinos development happens in packages that require C++11.

**Comment by jhux2** [comment]
Closing, as this is for a very old version of Trilinos and MueLu.
