### ISSUE TITLE
README.md:  Links go to non-existent pages

### ISSUE THREAD

**Issue by cook-1229** [trilinos/Trilinos#7911]
## Documentation

In README.md, there are links to trilinos.org pages that all redirect to the homepage of https://trilinos.github.io/.  The mailing-list link goes a mailing-list page that does not include a trilinos-users list.

[Website](http://trilinos.org/) |
[Documentation](http://trilinos.org/about/documentation/) |
[Mailing List](https://trilinos.org/mailman/listinfo/trilinos-users) |
[Packages](http://trilinos.org/packages/)

- [Getting Started with Trilinos](https://trilinos.org/getting-started/) 

- [General Documentation](https://trilinos.org/about/documentation/)

Separately, waffle.io appears to no longer exist.
[![Stories in Ready](https://badge.waffle.io/trilinos/Trilinos.png?label=ready&title=Ready)](https://waffle.io/trilinos/Trilinos)

**Comment by jhux2** [comment]
@maherou @jwillenbring

**Comment by jhux2** [comment]
@cook-1229 This is now fixed in the develop branch (see https://github.com/trilinos/Trilinos/tree/develop) and should be fixed shortly in master after the next automatic promotion.

**Comment by cook-1229** [comment]
Excellent, looks good to me in the development branch.  I made a proposed edit for the figure at the top.
