### ISSUE TITLE
Tpetra:  Inconsistent with Cuda 11.0

### ISSUE THREAD

**Issue by hillyuan** [trilinos/Trilinos#7923]
## Enhancement
@trilinos/Tpetra

The member variables  _isManaged_ and _memoryType_ do not exist in struct cudaPointerAttributes of cuda 11.0 but used in file Tpetra_Details_checkPointer.cpp. Compiling Tpetra with Cuda 11.0 is therfore fails.

**Comment by mayrmt** [comment]
@trilinos/tpetra

**Comment by csiefer2** [comment]
Ah, the joys of API changes!  Thanks Cuda developers!

@kddevin

**Comment by kddevin** [comment]
These fields are in a file that appears to be unused.  We will investigate removing the file.
Thank you for the report, @hillyuan
