### ISSUE TITLE
ShyLU: Basker - Symbolic - Assertion failed for at least 4 threads

### ISSUE THREAD

**Issue by gkovacsds** [trilinos/Trilinos#7931]
## Bug Report
@trilinos/\<ShyLU\>

### Description
Error message:
Basker U_blk_sfactor assert: nrow > 0 failed
LINE: 1272
FILE: /home/gergo/Trilinos/source/packages/shylu/shylu_node/basker/src/shylubasker_sfactor.hpp  

### Steps to Reproduce
Execute basker_test.exe    (in shylu/shylu_node/basker/test)
with public matrix file parameter  "memplus.mtx"    https://math.nist.gov/MatrixMarket/data/misc/hamm/memplus.html
and number of threads 4
Thread number 1 and 2 solves fine, 4 causes assertion failed. Error comes with other own circuit simulation matrix too, from 4 threads.
Tested on Ubuntu 20.04

Verbosed outputs are in the attached file, as well as a slightly modified source code, for reading RHS and timing measurements. Error comes with original unmodified basker_test.cpp too.

Thank you for any feedback.

[bugreport.zip](https://github.com/trilinos/Trilinos/files/5141758/bugreport.zip)

**Comment by jhux2** [comment]
@trilinos/shylu

**Comment by srajama1** [comment]
@iyamazaki has a fix, I think.

**Comment by gkovacsds** [comment]
Thanks, can I find it?

**Comment by iyamazaki** [comment]
We've been working to improve the sequential robustness/performance in [another branch](https://github.com/iyamazaki/Trilinos/tree/shylu-basker2). We have not merged because it is still work-in-progress. Let us know if this helps. We are just starting to look at thread-parallel. Best.

**Comment by gkovacsds** [comment]
Thank you, this error seems to be fixed now.
Though I experience a noticeable higher calculation time measurement even in sequential mode - I only run the test program with 1 matrix.

**Comment by iyamazaki** [comment]
I'm closing this since [PR 9525](https://github.com/trilinos/Trilinos/pull/9525) should fix this. Please let us know if you still see the issue..
