### ISSUE TITLE
Epetra:  how to export csrmatrix into a ascii file. 

### ISSUE THREAD

**Issue by ztdepztdep** [trilinos/Trilinos#7936]
I want to export my distributed csrmatrix into files. could you please give me some suggestion.

**Comment by jhux2** [comment]
Yes. See the EpetraExt doxygen, https://docs.trilinos.org/dev/packages/epetraext/browser/doc/html/namespaceEpetraExt.html.

**Comment by jhux2** [comment]
@trilinos/epetra @trilinos/epetraext

**Comment by jhux2** [comment]
@ztdepztdep Did this help?

**Comment by ztdepztdep** [comment]
Thanks. it works.


| |
Professor Ding、
|
|
ztdepyahoo@163.com
|
签名由网易邮箱大师定制
On 8/31/2020 10:50，Jonathan Hu<notifications@github.com> wrote：

Yes. See the EpetraExt doxygen, https://docs.trilinos.org/dev/packages/epetraext/browser/doc/html/namespaceEpetraExt.html.
