### ISSUE TITLE
Xpetra: Kokkos::fence with Epetra

### ISSUE THREAD

**Issue by cgcgcg** [trilinos/Trilinos#8010]
## Bug Report
@trilinos/xpetra 

### Description
Build failure on an Epetra-only build:
https://testing.sandia.gov/cdash/viewBuildError.php?buildid=7850071
The call to `Kokkos::fence` needs to be guarded.

**Comment by lucbv** [comment]
Yeah, if we wanted to be cute, we could create an `Xpetra::fence()` that handles that instead of calling a `Kokkos::fence()`.
I am just worried that users might not understand what this would entail exactly.
Of course we can simply add guards around in our code, that's also fine with me.
