### ISSUE TITLE
PR Testing: Use C++14 standard for Intel 17.0.1 build

### ISSUE THREAD

**Issue by ZUUL42** [trilinos/Trilinos#8015]
## Enhancement
@trilinos/framework 

We are going to add -std=c++14 to the Intel 17.0.1 build. While some packages are looking to use C++14 (and C++17) features, this will at least move us in the right direction and ensure that customers will be able to build Trilinos with C++14.

This incremental step is consistent with discussions at the Trilinos Product Leaders meeting and is related to #6260.

**Comment by ndellingwood** [comment]
If using modules for intel/17,0.1 you'll likely need to swap out the auto-loaded gcc for a newer version within PR/autotester scripts, see explanations in comments linked below

https://github.com/trilinos/Trilinos/issues/8048#issuecomment-694538389
https://github.com/trilinos/Trilinos/issues/8047#issuecomment-694539145

**Comment by ZUUL42** [comment]
Doh! Thanks. Can't believe I missed that. It was still using the default GCC 4.9.3 for Intel 17.
Now that I have it updated to GCC 5.3.0, we only have tests failing for ROL & Piro.

To members of @trilinos/rol  & @trilinos/piro, here are the results from the Intel 17.0.1 build with the standard set to c++14 using gcc 5.3.0.
[CDash](https://testing.sandia.gov/cdash/index.php?project=Trilinos&display=project&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=63&value1=intel17c14&field2=buildstamp&compare2=63&value2=Experimental&field3=buildstarttime&compare3=83&value3=2020%2F09%2F17)
We would like to have this build ready to move to c++14 by Friday for Kokkos to merge in their 3.3 release on Monday.
To do that, I will need to turn off 44 tests in ROL and 2 tests in Piro. To give you a chance to fix them, I can wait until the last minute to turn any remaining failing tests off until Friday. Then we can always turn them back on as they are fixed beyond that date.
