### ISSUE TITLE
PR Testing: Use C++14 standard for CUDA 9.2.88 build

### ISSUE THREAD

**Issue by ZUUL42** [trilinos/Trilinos#8016]
## Enhancement
@trilinos/framework 

We are going to add -std=c++14 to the CUDA 9.2.88 build. While some packages are looking to use C++14 (and C++17) features, this will at least move us in the right direction and ensure that customers will be able to build Trilinos with C++14.

This incremental step is consistent with discussions at the Trilinos Product Leaders meeting and is related to #6260.

**Comment by kddevin** [comment]
Most (if not all) of these compilation errors are due to a compiler error:
```
internal compiler error: in maybe_undo_parenthesized_ref, at cp/semantics.c
```
Previous hacks around the problem exist but are cryptic to me; does anyone have a pattern that we should follow?
See #8031 and https://github.com/kokkos/kokkos-kernels/issues/349

@trilinos/kokkos

**Comment by ZUUL42** [comment]
That last change seems to have Tpetra fixed up. Thanks @kddevin.
I think I have a fix for the 2 errors with @trilinos/ifpack2 and I'm testing a possible fix for the 2 errors with @trilinos/kokkos-kernels.
[Diff](https://github.com/trilinos/Trilinos/compare/develop...ZUUL42:cuda9c14)
[CDash](https://testing.sandia.gov/cdash/index.php?project=Trilinos&display=project&filtercount=3&showfilters=1&filtercombine=and&field1=site&compare1=61&value1=ride14&field2=buildname&compare2=61&value2=PR-cuda9c14fixes-test-Trilinos_pullrequest_cuda_9.2-5593&field3=buildstamp&compare3=61&value3=20200925-0332-Experimental)
