### ISSUE TITLE
PR Testing: Use C++14 standard for Clang 10.0.0 build

### ISSUE THREAD

**Issue by ZUUL42** [trilinos/Trilinos#8017]
## Enhancement
@trilinos/framework 

We are going to add -std=c++14 to the Clang 10.0.0 build. While some packages are looking to use C++14 (and C++17) features, this will at least move us in the right direction and ensure that customers will be able to build Trilinos with C++14.

This incremental step is consistent with discussions at the Trilinos Product Leaders meeting and is related to #6260.

**Comment by rppawlo** [comment]
@ZUUL42 - we are looking to better track covered features in various PR builds. On the wiki page:

https://github.com/trilinos/Trilinos/wiki/Pull-Request-Testing-Interface

For each build in the PR test list, could you add whether it is using c++11 or c++14?

**Comment by ZUUL42** [comment]
@rppawlo we are looking to have all PR testing use c++14 soon. So, I'll add a note to that affect when the move is complete.
