### ISSUE TITLE
CDash upgrade to official v3.0.z release

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#8030]
@trilinos/framework,

What type of notice and planning is needed for upgrade?  (Want to make sure that no one is surprised by this one.)

----

From: Bartlett, Roscoe A 
Sent: Tuesday, September 15, 2020 1:10 PM
To: trilinos-framework@software.sandia.gov
Cc: 'trilinos-products-bounces@software.sandia.gov' <trilinos-products-bounces@software.sandia.gov>; Zack Galbreath <zack.galbreath@kitware.com>; Wolf, Michael M <mmwolf@sandia.gov>; Willenbring, James M <jmwille@sandia.gov>; Wolfenbarger, Paul R <prwolfe@sandia.gov>
Subject: CDash upgrade to official v3.0.z release

Hello Trilinos Framework team members,

Kitware is planning to upgrade https://testing.sandia.gov/cdash/ to an official release of CDash v3.0.z to close out the last upgrade.  Currently, that CDash site is based on a release candidate for v3.0.0 (currently CDash v3.0.0-rc1-10-ge49219b) is there a good or bad time for them to do this upgrade?

This last upgrade should be fast and very low risk since it is not upgading the DB schema.

Please let me and Zack know.

Thanks,

-Ross

Dr. Roscoe A. Bartlett, PhD
https://bartlettroscoe.github.io/ 
Sandia National Laboratories

**Comment by jwillenbring** [comment]
I think a low risk upgrade is reasonable to do with a day or two notice. Is this Friday an option? Otherwise, Thursday would work too. If we do not want to be running PR tests during the upgrade, we will need to coordinate a time to shut the system down. I could help with that Thursday or Friday. I will follow up via email for more specific planning.

**Comment by bartlettroscoe** [comment]
The upgrade is complete. The sites:

* https://testing.sandia.gov/cdash/viewProjects.php
* https://testing-dev.sandia.gov/cdash/viewProjects.php

in the bottom right are now showing `CDash v3.0.0 © Kitware`. Since `v3.0.0` is generated using `git describe`, this is pretty good proof.

Closing as complete.
