### ISSUE TITLE
Trilinos/Tpetra: Enable coverage testing

### ISSUE THREAD

**Issue by prwolfe** [trilinos/Trilinos#8036]
## Enhancement
@trilinos/tpetra 

The Trilinos testing should enable coverage testing for development teams. 

From a previous e-mail exchange:

Progress:
 
I based my work on a gcc 7.2.0 debug build and enabled tpetra
Enabled coverage using “-D Trilinos_ENABLE_COVERAGE_TESTING=ON”
Link time errors in libgcov.a at all executables
Found that the shared libraries must have a flag (--coverage) in order to resolve the previous link problem.
I added it by hand with “-DCMAKE_SHARED_LINKER_FLAGS=--coverage”
Compile and executable link flags are set in tribits/core/package_arch/TribitsSetupBasicCompileLinkFlags
Run time for tests – used make test ARGS=”-j 8”
Almost all tests failed with “Required regular expression not found”
The logs are full of mpi errors of the form “TpetraTSQR_DistTsqr.exe: symbol lookup error: libmca_common_verbs.so.7: undefined symbol: ompi_common_verbs_usnic_register_fake_drivers
I can verify that the *gcno and *gcda files used by gcov/lcov are being produced
 
So I should at least file a bug report with tribits, but I’m unsure if the Tpetra team will be interested in chasing down the mpi symbol issue. I tried google right quick without success.
 
Paul
 
From: "Willenbring, James M" <jmwille@sandia.gov>
Date: Tuesday, August 11, 2020 at 2:34 PM
To: "Wolfenbarger, Paul R" <prwolfe@sandia.gov>
Cc: "Mclendon, William C III" <wcmclen@sandia.gov>, "Swantner, Henry Roy" <hrswant@sandia.gov>
Subject: Re: Trilinos coverage tests
 
Paul,
 
To be clear, for now we should tell Karen we don’t have any specific pointers to get her started, right. 
 
Thanks
 
Jim

Sent from my iPhone

On Aug 11, 2020, at 2:17 PM, Wolfenbarger, Paul R <prwolfe@sandia.gov> wrote:

Looks like the build failed looking for a symbol in libgcov.a. so the setup was trivial, but it is not in actual use with gcc 7.2 at least.
 
Paul
 
From: "Willenbring, James M" <jmwille@sandia.gov>
Date: Tuesday, August 11, 2020 at 12:53 PM
To: "Wolfenbarger, Paul R" <prwolfe@sandia.gov>, "Mclendon, William C III" <wcmclen@sandia.gov>, "Swantner, Henry Roy" <hrswant@sandia.gov>
Subject: Re: Trilinos coverage tests
 
Paul,
 
Did you have any chance to look into this at all?
 
Thanks
 
Jim
 
From: "Wolfenbarger, Paul R" <prwolfe@sandia.gov>
Date: Wednesday, August 5, 2020 at 12:44 PM
To: James Willenbring <jmwille@sandia.gov>, "Mclendon, William C III" <wcmclen@sandia.gov>, "Swantner, Henry Roy" <hrswant@sandia.gov>
Subject: Re: Trilinos coverage tests
 
Not sure how well it would work from a command-line, but Tribits has coverage testing setup – looks lie using Trilinos_ENABLE_COVERAGE_TESTING=ON will start that process. I will set up a hand build to look at that.
 
Paul
 
 
From: "Willenbring, James M" <jmwille@sandia.gov>
Date: Wednesday, August 5, 2020 at 12:00 PM
To: "Wolfenbarger, Paul R" <prwolfe@sandia.gov>, "Mclendon, William C III" <wcmclen@sandia.gov>, "Swantner, Henry Roy" <hrswant@sandia.gov>
Subject: Re: Trilinos coverage tests
 
Would someone be able to point Karen in the right direction here? Ideally we could resurrect our coverage testing, but I don’t know that anyone has the capacity to look at that now.
 
Jim
 
From: Karen Devine <kddevin@sandia.gov>
Date: Tuesday, August 4, 2020 at 1:50 PM
To: James Willenbring <jmwille@sandia.gov>
Subject: Trilinos coverage tests
 
 

Hi, Jim.

 

Does Trilinos run any coverage tests?  If so, what tool do they use?

 

The Tpetra team is on the hunt for dead code; we've identified some "by hand" but would some help from a tool.  If Trilinos doesn't have tests, we'd be happy for pointers on tools we could use in our testing environment.

 

Thank you, Jim.

Karen

**Comment by kddevin** [comment]
@prwolfe if you post or email your CMake configuration command, I'll use it to look at the link errors.  I assume you are working on cee-lan; is that correct?  Thanks!

**Comment by prwolfe** [comment]
Karen,

I was in fact on the dee-lan using my "CEE - Engineering Workspace" blade. I did the standard procedure to replicate a gcc 7.2.0 build and added the -D for coverage using

>. ../Trilinos/cmake/std/sems/PullRequestGCC7.2.0TestingEnv.sh
>cmake -DTrilinos_ENABLE_COVERAGE_TESTING=ON -DTrilinos_ENABLE_Tpetra=ON -C ../Trilinos/cmake/std/PullRequestLinuxGCC7.2.0DebugTestingSettings.cmake -GNinja ../Trilinos

and then built as normal. The testing showed the symbol lookup error

> TpetraTSQR_DistTsqr.exe: symbol lookup error: libmca_common_verbs.so.7: undefined symbol: ompi_common_verbs_usnic_register_fake_drivers

in most of the tests. Enough that I would see if it is possible to resolve that first and see what's left.

Paul

**Comment by kddevin** [comment]
@prwolfe I think I am building the same way on cee-compute006.  I haven't see the MPI link errors yet, but I see the following error:
```
FAILED: packages/thyra/core/test/operator_vector/ThyraCore_test_std_ops.exe
: && /projects/sems/install/rhel7-x86_64/sems/compiler/gcc/7.2.0/openmpi/1.10.1/bin/mpicxx  -pedantic -Wall -Wno-long-long -Wwrite-strings -Wshadow -Woverloaded-virtual -Wall -Wno-clobbered -Wno-vla -Wno-pragmas -Wno-unknown-pragmas -Wno-unused-local-typedefs -Wno-literal-suffix -Wno-deprecated-declarations -Wno-misleading-indentation -Wno-int-in-bool-context -Wno-maybe-uninitialized -Wno-nonnull-compare -Wno-address -Wno-inline -DTRILINOS_HIDE_DEPRECATED_HEADER_WARNINGS -Werror   -g -O0  -fprofile-arcs -ftest-coverage packages/thyra/core/test/operator_vector/CMakeFiles/ThyraCore_test_std_ops.dir/test_std_ops.cpp.o  -o packages/thyra/core/test/operator_vector/ThyraCore_test_std_ops.exe  -Wl,-rpath,/ascldap/users/kddevin/code/Trilinos/Obj_prwolfe/packages/thyra/core/src:/ascldap/users/kddevin/code/Trilinos/Obj_prwolfe/packages/rtop/src:/ascldap/users/kddevin/code/Trilinos/Obj_prwolfe/packages/teuchos/numerics/src:/ascldap/users/kddevin/code/Trilinos/Obj_prwolfe/packages/teuchos/comm/src:/ascldap/users/kddevin/code/Trilinos/Obj_prwolfe/packages/teuchos/parameterlist/src:/ascldap/users/kddevin/code/Trilinos/Obj_prwolfe/packages/teuchos/parser/src:/ascldap/users/kddevin/code/Trilinos/Obj_prwolfe/packages/teuchos/core/src:/ascldap/users/kddevin/code/Trilinos/Obj_prwolfe/packages/kokkos/core/src packages/thyra/core/src/libthyracore.so.13.1 packages/rtop/src/librtop.so.13.1 packages/teuchos/numerics/src/libteuchosnumerics.so.13.1 /usr/lib64/liblapack.so /usr/lib64/libblas.so packages/teuchos/comm/src/libteuchoscomm.so.13.1 packages/teuchos/parameterlist/src/libteuchosparameterlist.so.13.1 packages/teuchos/parser/src/libteuchosparser.so.13.1 packages/teuchos/core/src/libteuchoscore.so.13.1 packages/kokkos/core/src/libkokkoscore.so.3.2.0 /usr/lib64/libdl.so && :
/usr/bin/ld: packages/thyra/core/test/operator_vector/ThyraCore_test_std_ops.exe: hidden symbol `__gcov_init' in /projects/sems/install/rhel7-x86_64/sems/compiler/gcc/7.2.0/base/lib/gcc/x86_64-pc-linux-gnu/7.2.0/libgcov.a(_gcov.o) is referenced by DSO
/usr/bin/ld: final link failed: Bad value
```

Here's my cmake script:

```
module purge
source  ../cmake/std/sems/PullRequestGCC7.2.0TestingEnv.sh

cmake \
  -DTrilinos_ENABLE_COVERAGE_TESTING=ON \
  -DTrilinos_ENABLE_Tpetra=ON \
  -C ../cmake/std/PullRequestLinuxGCC7.2.0DebugTestingSettings.cmake \
  -GNinja  \
..
```

I get the same error for many Thyra tests.

Have you seen this error?

**Comment by prwolfe** [comment]
Yes – I missed a flag in that command line – you should “-DCMAKE_SHARED_LINKER_FLAGS=--coverage” to it (or you can do it in the curses gui.)

My apologies for missing this.

Paul

**Comment by kddevin** [comment]
@prwolfe The following configuration worked for me on a cee compute node: no build or link errors.

```
module purge
source  ../cmake/std/sems/PullRequestGCC7.2.0TestingEnv.sh

cmake \
  -DCMAKE_SHARED_LINKER_FLAGS=--coverage \
  -DTrilinos_ENABLE_COVERAGE_TESTING=ON \
  -DTrilinos_ENABLE_Tpetra=ON \
  -C ../cmake/std/PullRequestLinuxGCC7.2.0DebugTestingSettings.cmake \
  -GNinja  \
.. 
make NP=6 
```
How do I get coverage stats now from the tests?  Running "make test" did not produce anything that looked like coverage stats.  Do we have to mark up the tribits test specifications in any way?

**Comment by prwolfe** [comment]
Did you get the library errors when running the tests?

**Comment by kddevin** [comment]
No; all of the tests that I ran passed.
I am just doing "make test"; should I do something else?
In an earlier comment, you said "gcno and *gcda files used by gcov/lcov are being produced"; where should I look for these files?

**Comment by prwolfe** [comment]
No, that should be all of it. Wonder what I did wrong.

The gcov/lcov files are placed alongside the object files in the build tree. They are not easy to read however. I would have to look up how, but the lcov system has scripts to accumulate the results. I would just google it and read the docs.

Paul
