### ISSUE TITLE
Teuchos: Expose MpiTypeTraits

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#804]
@trilinos/teuchos 
Story: #748 
Blocks: #752

Teuchos has an MpiTypeTraits, but it currently lives in an anonymous namespace inside the Teuchos namespace, in teuchos/comm/src/Teuchos_CommHelpers.cpp.  It would make sense to expose this class to Trilinos developers.  We should put it in an inner implementation namespace to make clear that it is not for users.

The point of this is to make it easier to implement more efficient "by-passes" of Teuchos' serialization traits mechanism, for more MPI functions.  My motivation is to wrap MPI_Iallreduce in order to implement pipelined Krylov solvers.

**Comment by aprokop** [comment]
Agreed. One place where we already duplicated the functionality of MpiTypeTraits is MueLu's RepartitionFactory @trilinos/muelu

**Comment by mhoemmen** [comment]
@aprokop wrote:
> Agreed. One place where we already duplicated the functionality of MpiTypeTraits is MueLu's RepartitionFactory @trilinos/muelu

Thanks for pointing that out :-)  It looks like MueLu only specializes this class for built-in integer types.  Would you happen to know the reason for MueLu wanting to go to MPI directly?  Were the Teuchos wrappers not performing well?  (We've more or less fixed the problem in Teuchos for built-in types.)  Was it an issue with Import / Export?  (That's more important, but it's something Tpetra needs to fix.)

**Comment by aprokop** [comment]
The code in question uses `MPI_Probe` as we did not want to do some overlapping of computation and communication and did not know where the messages are arriving from. I'm not sure if Teuchos wrappers play nicely (or played nicely at the time) with asynchronous sending and probing.

**Comment by mhoemmen** [comment]
@aprokop wrote:
> ... as we did not want to do some overlapping of computation and communication ...

Should I delete "not" in the above phrase?

@aprokop wrote:
> I'm not sure if Teuchos wrappers play nicely (or played nicely at the time) with asynchronous sending and probing.

If they don't, the right thing for us to do would be to fix that.  On the other hand, MueLu's use of raw MPI won't hurt anything :-)

**Comment by aprokop** [comment]
> If they don't, the right thing for us to do would be to fix that. On the other hand, MueLu's use of raw MPI won't hurt anything :-)

I see no benefits converting to Teuchos at this point.

**Comment by mhoemmen** [comment]
@aprokop wrote:
> I see no benefits converting to Teuchos at this point.

No worries :-)  I'm about to push a change that gives Teuchos::Details::MpiTypeTraits the same interface that MueLu uses for its MpiTypeTraits.  That will at least let you use the one interface if you like.

**Comment by aprokop** [comment]
@mhoemmen Feel free to remove MueLu's `MpiTypeTraits` when you expose it in Teuchos.
