### ISSUE TITLE
Tpetra:  Build Errors with C++14 builds

### ISSUE THREAD

**Issue by ZUUL42** [trilinos/Trilinos#8047]
## Bug Report
@trilinos/tpetra 

### Description
In updating the CUDA 9.2.88 PR build to C++14, I'm getting build errors from Tpetra.

We're trying to update these builds to C++14 before 09/28 when @trilinos/kokkos is going to merge in a snapshot that requires C++14.
Ties to #8016 & [#6260](https://github.com/trilinos/Trilinos/issues/6260#issuecomment-672256473).

### Steps to Reproduce
These errors came up after adding two lines to the cmake file to set the standard to c++14.
```
set (CMAKE_CXX_STANDARD "14" CACHE STRING "Set C++ standard to C++14")
...
set(CMAKE_CXX_FLAGS "-std=c++14" CACHE STRING "Set standard to C++14")
```

[CDash showing failing builds](https://testing.sandia.gov/cdash/index.php?project=Trilinos&display=project&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=63&value1=cuda9c14&field2=buildstamp&compare2=63&value2=Experimental&field3=buildstarttime&compare3=83&value3=2020%2F09%2F15)

**Comment by kddevin** [comment]
Can we get some help from @trilinos/kokkos ?  
The Intel17.0.1 builds have compilation errors in Kokkos header files Kokkos_EBO.hpp, Kokkos_Combined_Reducer.hpp, and Kokkos_Complex.hpp.  
If @trilinos/tpetra is using the files incorrectly, please let me know.

**Comment by kddevin** [comment]
For the Cuda builds...
Most (if not all) of these compilation errors are due to a compiler error:
```
internal compiler error: in maybe_undo_parenthesized_ref, at cp/semantics.c
```

Previous hacks around the problem exist but are cryptic to me; does anyone have a pattern that we should follow?
See #8031 and kokkos/kokkos-kernels#349

@trilinos/kokkos

**Comment by ndellingwood** [comment]
@kddevin @ZUUL42 regarding some of the intel/17 issues, I just posted what I had seen in the kokkos nightlies, reposting here and cross-referencing the comment:

> @rppawlo @ZUUL42 the issue is the intel/17 module is likely loading an older gcc (4.9.3 or 4.8.4), or using an older system install of gcc. I had to update the kokkos nightly intel builds to swap out the old gcc module with a newer version with full c++14 support, I'm guessing something similar will need to be done with the framework's PR testing scripts.

https://github.com/trilinos/Trilinos/issues/8048#issuecomment-694538389

**Comment by ndellingwood** [comment]
@kddevin to clarify, errors of the form:

```
In file included from /scratch/trilinos/jenkins/ascic158/workspace/trilinos-folder/Trilinos_pullrequest_intel_17.0.1/Trilinos/packages/kokkos/core/src/impl/Kokkos_TaskNode.hpp(61),
                 from /scratch/trilinos/jenkins/ascic158/workspace/trilinos-folder/Trilinos_pullrequest_intel_17.0.1/Trilinos/packages/kokkos/core/src/impl/Kokkos_TaskResult.hpp(57),
                 from /scratch/trilinos/jenkins/ascic158/workspace/trilinos-folder/Trilinos_pullrequest_intel_17.0.1/Trilinos/packages/kokkos/core/src/impl/Kokkos_TaskQueue.hpp(59),
                 from /scratch/trilinos/jenkins/ascic158/workspace/trilinos-folder/Trilinos_pullrequest_intel_17.0.1/Trilinos/packages/kokkos/core/src/Kokkos_Future.hpp(57),
                 from /scratch/trilinos/jenkins/ascic158/workspace/trilinos-folder/Trilinos_pullrequest_intel_17.0.1/Trilinos/packages/kokkos/core/src/Kokkos_TaskScheduler.hpp(60),
                 from /scratch/trilinos/jenkins/ascic158/workspace/trilinos-folder/Trilinos_pullrequest_intel_17.0.1/Trilinos/packages/kokkos/core/src/Kokkos_Serial.hpp(57),
                 from /scratch/trilinos/jenkins/ascic158/workspace/trilinos-folder/Trilinos_pullrequest_intel_17.0.1/Trilinos/packages/kokkos/core/src/Kokkos_Core.hpp(54),
                 from /scratch/trilinos/jenkins/ascic158/workspace/trilinos-folder/Trilinos_pullrequest_intel_17.0.1/Trilinos/packages/phalanx/src/Phalanx_KokkosDeviceTypes.hpp(5),
                 from /scratch/trilinos/jenkins/ascic158/workspace/trilinos-folder/Trilinos_pullrequest_intel_17.0.1/Trilinos/packages/phalanx/example/FiniteElementAssembly/Mesh.hpp(50),
                 from /scratch/trilinos/jenkins/ascic158/workspace/trilinos-folder/Trilinos_pullrequest_intel_17.0.1/Trilinos/packages/phalanx/example/FiniteElementAssembly/auxiliary_tests/Example_FEM_Workset_AuxTest.cpp(51):
/scratch/trilinos/jenkins/ascic158/workspace/trilinos-folder/Trilinos_pullrequest_intel_17.0.1/Trilinos/packages/kokkos/core/src/impl/Kokkos_EBO.hpp(128): error: invalid type for defaulted assignment operator
    EBOBaseImpl& operator=(EBOBaseImpl const&) = default;
```

would be related to the intel/17 + old gcc issue.

**Comment by kddevin** [comment]
@ndellingwood awesome info on Intel17; thank you!
@ZUUL42  I'll wait for an update from you before doing anything further with the Intel17 errors.

**Comment by ZUUL42** [comment]
Thanks. My mistake on not updating the gcc version on the Intel build. That is taken are of and I'll remove it from the issue.

Though I think I could still use a hand with the fix for Cuda.

**Comment by kddevin** [comment]
@ZUUL42 Can you please add the "steps to reproduce"?  Thanks.

**Comment by ZUUL42** [comment]
@kddevin I added two lines to the cmake file to set the standard to c++14.
```
set (CMAKE_CXX_STANDARD "14" CACHE STRING "Set C++ standard to C++14")
...
set(CMAKE_CXX_FLAGS "-std=c++14" CACHE STRING "Set standard to C++14")
```
branch [cuda9c14](https://github.com/trilinos/Trilinos/compare/develop...ZUUL42:cuda9c14)

**Comment by crtrott** [comment]
Do you need that second line?

**Comment by crtrott** [comment]
Yeah I think you adding -std=c++14 explicitly causes the warning in the build (not the error though).

**Comment by crtrott** [comment]
Folks: https://github.com/kokkos/kokkos-kernels/issues/349
That discussion triggers the same issue in GCC and at the time I tracked down where its coming from and multiple possible workarounds for a similar issue in KokkosKernels. I believe you just have to look out for the same stuff.

**Comment by kddevin** [comment]
Thanks, @crtrott 
One might ask why we support bad compilers, but one might not like the answer.  ;)
