### ISSUE TITLE
Phalanx:  Build Errors with C++14 builds

### ISSUE THREAD

**Issue by ZUUL42** [trilinos/Trilinos#8048]
## Bug Report
@trilinos/phalanx 

### Description
In updating the CUDA 9.2.88 build to C++14, I'm getting build errors from Phalanx.

We're trying to update these builds to C++14 before 09/28 when @trilinos/kokkos is going to merge in a snapshot that requires C++14.
Ties to #8016 [#6260](https://github.com/trilinos/Trilinos/issues/6260#issuecomment-672256473).

### Steps to Reproduce
[CDash showing failing builds](https://testing.sandia.gov/cdash/index.php?project=Trilinos&display=project&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=63&value1=cuda9c14&field2=buildstamp&compare2=63&value2=Experimental&field3=buildstarttime&compare3=83&value3=2020%2F09%2F15)

**Comment by rppawlo** [comment]
@ZUUL42 - the two phalanx errors on the intel build look like they are actually kokkos issues. The nox and panzer build errors are exactly the same. For example, here are two of the errors:

```
In file included from /scratch/trilinos/jenkins/ascic158/workspace/trilinos-folder/Trilinos_pullrequest_intel_17.0.1/Trilinos/packages/teuchos/core/src/Teuchos_ScalarTraits.hpp(59),
                 from /scratch/trilinos/jenkins/ascic158/workspace/trilinos-folder/Trilinos_pullrequest_intel_17.0.1/Trilinos/packages/teuchos/core/src/Teuchos_TestingHelpers.hpp(52),
                 from /scratch/trilinos/jenkins/ascic158/workspace/trilinos-folder/Trilinos_pullrequest_intel_17.0.1/Trilinos/packages/teuchos/core/src/Teuchos_LocalTestingHelpers.hpp(56),
                 from /scratch/trilinos/jenkins/ascic158/workspace/trilinos-folder/Trilinos_pullrequest_intel_17.0.1/Trilinos/packages/teuchos/core/src/Teuchos_UnitTestHarness.hpp(54),
                 from /scratch/trilinos/jenkins/ascic158/workspace/trilinos-folder/Trilinos_pullrequest_intel_17.0.1/Trilinos/packages/phalanx/example/FiniteElementAssembly/auxiliary_tests/Example_FEM_Workset_AuxTest.cpp(50):
/scratch/trilinos/jenkins/ascic158/workspace/trilinos-folder/Trilinos_pullrequest_intel_17.0.1/Trilinos/packages/kokkos/core/src/Kokkos_Complex.hpp(162): error: cannot overload functions distinguished by return type alone
    constexpr RealType real() const noexcept { return re_; }
```

```
In file included from /scratch/trilinos/jenkins/ascic158/workspace/trilinos-folder/Trilinos_pullrequest_intel_17.0.1/Trilinos/packages/kokkos/core/src/impl/Kokkos_TaskNode.hpp(61),
                 from /scratch/trilinos/jenkins/ascic158/workspace/trilinos-folder/Trilinos_pullrequest_intel_17.0.1/Trilinos/packages/kokkos/core/src/impl/Kokkos_TaskResult.hpp(57),
                 from /scratch/trilinos/jenkins/ascic158/workspace/trilinos-folder/Trilinos_pullrequest_intel_17.0.1/Trilinos/packages/kokkos/core/src/impl/Kokkos_TaskQueue.hpp(59),
                 from /scratch/trilinos/jenkins/ascic158/workspace/trilinos-folder/Trilinos_pullrequest_intel_17.0.1/Trilinos/packages/kokkos/core/src/Kokkos_Future.hpp(57),
                 from /scratch/trilinos/jenkins/ascic158/workspace/trilinos-folder/Trilinos_pullrequest_intel_17.0.1/Trilinos/packages/kokkos/core/src/Kokkos_TaskScheduler.hpp(60),
                 from /scratch/trilinos/jenkins/ascic158/workspace/trilinos-folder/Trilinos_pullrequest_intel_17.0.1/Trilinos/packages/kokkos/core/src/Kokkos_Serial.hpp(57),
                 from /scratch/trilinos/jenkins/ascic158/workspace/trilinos-folder/Trilinos_pullrequest_intel_17.0.1/Trilinos/packages/kokkos/core/src/Kokkos_Core.hpp(54),
                 from /scratch/trilinos/jenkins/ascic158/workspace/trilinos-folder/Trilinos_pullrequest_intel_17.0.1/Trilinos/packages/phalanx/src/Phalanx_KokkosDeviceTypes.hpp(5),
                 from /scratch/trilinos/jenkins/ascic158/workspace/trilinos-folder/Trilinos_pullrequest_intel_17.0.1/Trilinos/packages/phalanx/example/FiniteElementAssembly/Mesh.hpp(50),
                 from /scratch/trilinos/jenkins/ascic158/workspace/trilinos-folder/Trilinos_pullrequest_intel_17.0.1/Trilinos/packages/phalanx/example/FiniteElementAssembly/auxiliary_tests/Example_FEM_Workset_AuxTest.cpp(51):
/scratch/trilinos/jenkins/ascic158/workspace/trilinos-folder/Trilinos_pullrequest_intel_17.0.1/Trilinos/packages/kokkos/core/src/impl/Kokkos_EBO.hpp(128): error: invalid type for defaulted assignment operator
    EBOBaseImpl& operator=(EBOBaseImpl const&) = default;
                 ^
```

Maybe these are already fixed in kokkos? It looks like we may need changes to kokkos to fix these errors. @crtrott - can you comment on this?

**Comment by ndellingwood** [comment]
@rppawlo @ZUUL42 the issue is the intel/17 module is likely loading an older gcc (4.9.3 or 4.8.4), or using an older system install of gcc. I had to update the kokkos nightly intel builds to swap out the old gcc module with a newer version with full c++14 support, I'm guessing something similar will need to be done with the framework's PR testing scripts.

**Comment by ZUUL42** [comment]
Thanks. My mistake on not updating the gcc version on the Intel build. That is taken are of and I'll remove it from the issue.

Though I think I could still use a hand with the fix for Cuda.

**Comment by crtrott** [comment]
Which one is the CUDA issue?

**Comment by ZUUL42** [comment]
@crtrott, here is the latest c++14 CUDA 9.2 test build. [CDash](https://testing.sandia.gov/cdash/index.php?project=Trilinos&display=project&filtercount=3&showfilters=1&filtercombine=and&field1=site&compare1=61&value1=ride12&field2=buildname&compare2=61&value2=PR-cuda9c14-test-Trilinos_pullrequest_cuda_9.2-5488&field3=buildstamp&compare3=61&value3=20200916-2015-Experimental)

**Comment by ndellingwood** [comment]
@ZUUL42 I just reproduced the kokkos-kernels unit test errors, will work on a fix for the batched kokkos-kernels stuff for the 3.2.1 patch release

**Comment by ndellingwood** [comment]
@ZUUL42 looks like kokkos-kernels issues are already fixed on the develop branch by https://github.com/kokkos/kokkos-kernels/pull/790, this will be added to the 3.2.1 patch release

**Comment by crtrott** [comment]
https://github.com/kokkos/kokkos-kernels/issues/349 in the discussion where I root caused similar issues with multiple workarounds. This is fixed somewhere in GCC 7 or 8. Generally this seemed to have been caused by nested lambdas and reference capture.

**Comment by rppawlo** [comment]
Thanks @crtrott ! It's interesting. I already had a fix in those functors for the gcc 5/6 bug. The change to c++14 seems to have triggered the bug in a few more lambdas in the same file.

**Comment by ZUUL42** [comment]
Thanks. That seems to have taken care of the Phalanx build errors.
[CDash](https://testing.sandia.gov/cdash/index.php?project=Trilinos&display=project&filtercount=3&showfilters=1&filtercombine=and&field1=site&compare1=61&value1=ride12&field2=buildname&compare2=61&value2=PR-cuda9c14-test-Trilinos_pullrequest_cuda_9.2-5566&field3=buildstamp&compare3=61&value3=20200923-1726-Experimental)
Though now I see a @trilinos/kokkos test failure in its place. Though I assume it would be appropriate to turn off KokkosCore_UnitTest_Cuda3_MPI_1 for a Serial build.

**Comment by crtrott** [comment]
That error is likely spurious due to timing issues. We are working on a resolution.
