### ISSUE TITLE
Compadre: Failing Tests with Intel 17 C++14 build

### ISSUE THREAD

**Issue by ZUUL42** [trilinos/Trilinos#8049]
## Bug Report
@trilinos/compadre 

### Description
In updating the Intel 17.0.1 build to C++14, I'm getting failing tests from Compadre.

We're trying to update these builds to C++14 before 09/28 when @trilinos/kokkos is going to merge in a snapshot that requires C++14.
Ties to #8015 & [#6260](https://github.com/trilinos/Trilinos/issues/6260#issuecomment-672256473).

### Steps to Reproduce
[CDash showing failing builds](https://testing.sandia.gov/cdash/index.php?project=Trilinos&display=project&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=63&value1=c14&field2=buildstamp&compare2=63&value2=Experimental&field3=buildstarttime&compare3=83&value3=2020%2F09%2F15)

**Comment by ndellingwood** [comment]
FYI: errors of this form

```
/scratch/trilinos/jenkins/ascic158/workspace/trilinos-folder/Trilinos_pullrequest_intel_17.0.1/Trilinos/packages/kokkos/core/src/impl/Kokkos_EBO.hpp(128): error: invalid type for defaulted assignment operator
    EBOBaseImpl& operator=(EBOBaseImpl const&) = default;
```

indicate that the intel/17.0.1 module is loading too old of a gcc compiler, this will require loading/swapping the gcc module for a newer version (I had to do this for the Kokkos nightly builds).

Cross-reference
https://github.com/trilinos/Trilinos/issues/8048#issuecomment-694538389

**Comment by kuberry** [comment]
If you look in the test warnings, you will see things like:
https://testing.sandia.gov/cdash/test/32180733
Unable to find required file: /scratch/trilinos/jenkins/ascic158/workspace/trilinos-folder/Trilinos_pullrequest_intel_17.0.1/pull_request_test/packages/compadre/examples/Compadre_GMLS_Staggered.exe

Do these executables exist? CTest is saying that they don't. The tests that fail (3 of them) are python tests that call these non-existent executables:

https://testing.sandia.gov/cdash/test/32006363
['/scratch/trilinos/jenkins/ascic142/workspace/trilinos-folder/Trilinos_pullrequest_intel_17.0.1/pull_request_test/packages/compadre/examples/Compadre_GMLS_Staggered_Manifold_Test.exe', '3', '100', '3', '2000', '1', '1', '0', '--kokkos-threads=4']
Traceback (most recent call last):
  File "/scratch/trilinos/jenkins/ascic142/workspace/trilinos-folder/Trilinos_pullrequest_intel_17.0.1/pull_request_test/packages/compadre/examples/GMLS_Staggered_Manifold.py", line 45, in <module>
    output = subprocess.check_output(output_commands, stderr=devnull)
  File "/projects/sems/install/rhel7-x86_64/sems/compiler/python/2.7.9/lib/python2.7/subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/projects/sems/install/rhel7-x86_64/sems/compiler/python/2.7.9/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/projects/sems/install/rhel7-x86_64/sems/compiler/python/2.7.9/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by kuberry** [comment]
I wanted to follow-up on this previous reply by noting that :

**3138** tests did not run on intel (because the .exe's are missing), these 3 failed, and only 59 passed. Seems like this is a bigger issue. Where are those other exe's and why are they not showing up in the build warnings and errors?

**Comment by ZUUL42** [comment]
Doh!
Thanks. Can't believe I missed that. It was still using the default GCC 4.9.3 for Intel 17.
Now that I have it updated, I only have errors for ROL & Piro.
I'll close this and write appropriate issue tickets.

**Comment by crtrott** [comment]
Note: GCC 5.3.0 is the absolute minimum for C++14, I mean its Trilinos's decisison what to use but we may wanna go higher than that for the C++ library side. Kokkos will guarantee that GCC 5.3.0 works though ...
