### ISSUE TITLE
Panzer:  Build Errors with Intel 17.0.1 C++14 build

### ISSUE THREAD

**Issue by ZUUL42** [trilinos/Trilinos#8050]
## Bug Report
@trilinos/panzer 

### Description
In updating the Intel 17.0.1 build to C++14, I'm getting build errors from Panzer.

We're trying to update these builds to C++14 before 09/28 when @trilinos/kokkos is going to merge in a snapshot that requires C++14.
Ties to #8015 & [#6260](https://github.com/trilinos/Trilinos/issues/6260#issuecomment-672256473).

### Steps to Reproduce
[CDash showing failing builds](https://testing.sandia.gov/cdash/index.php?project=Trilinos&display=project&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=63&value1=c14&field2=buildstamp&compare2=63&value2=Experimental&field3=buildstarttime&compare3=83&value3=2020%2F09%2F15)

**Comment by ndellingwood** [comment]
FYI: errors of this form

```
/scratch/trilinos/jenkins/ascic158/workspace/trilinos-folder/Trilinos_pullrequest_intel_17.0.1/Trilinos/packages/kokkos/core/src/impl/Kokkos_EBO.hpp(128): error: invalid type for defaulted assignment operator
    EBOBaseImpl& operator=(EBOBaseImpl const&) = default;
```

indicate that the intel/17.0.1 module is loading too old of a gcc compiler, this will require loading/swapping the gcc module for a newer version (I had to do this for the Kokkos nightly builds).

Cross-reference
https://github.com/trilinos/Trilinos/issues/8048#issuecomment-694538389

**Comment by ZUUL42** [comment]
Doh!
Thanks. Can't believe I missed that. It was still using the default GCC 4.9.3 for Intel 17.
Now that I have it updated, I only have errors for ROL & Piro.
I'll close this and write appropriate issue tickets.
