### ISSUE TITLE
[xSDK-0.6.0] Amesos2/Amesos SuperLU_DIST-6.3 Support

### ISSUE THREAD

**Issue by keitat** [trilinos/Trilinos#8062]
## Bug Report
@trilinos/amesos2
@trilinos/amesos
### Background
xSDK team is working on the version 0.6.0 (released before the SC) that comprises 20+ different scientific libraries together and provides some interoperability between them. This version will include the latest version of SuperLU_DIST (6.3), which introduces new precision-specific data types so that their direct solvers with different precisions can coexist in a same program.  As a result, Amesos and Amesos2 are no longer compatible with SuperLU_DIST and xSDK.    Although Amesos (and epetra) is no longer actively developed (just maintenance only), there are still many applications and libraries using Amesos and Epetra for their basic linear algebra packages.  For example, deal.II, one of xSDK packages, relies on Epetra and Amesos for linear system solvers (including SuperLU_DIST).   As for the xSDK packages, SUNDIALS, PETSc, and MFEM have a direct support for the new data types of the SuperLU_DIST-6.3 to keep the interoperability in the xSDK collection.  Therefore, adding SuperLU_DIST-6.3 support to Amesos and Amesos2  is essential to be part of xSDK..

### Description
The latest SuperLU_DIST introduces the change in its data structure naming.  Amesos2/Amesos needs to support this change.

```
In file included from /Users/knteran/ECP/Trilinos/packages/amesos2/src/Amesos2_Superludist_FunctionMap.hpp:63,
                 from /Users/knteran/ECP/Trilinos/packages/amesos2/src/Amesos2_Superludist_decl.hpp:58,
                 from /Users/knteran/ECP/Trilinos/packages/amesos2/src/Amesos2_Superludist.hpp:47,
                 from /Users/knteran/ECP/Trilinos/packages/amesos2/src/Amesos2_Factory.hpp:108,
                 from /Users/knteran/ECP/Trilinos/packages/amesos2/src/Amesos2_Details_LinearSolverFactory_def.hpp:52,
                 from /Users/knteran/ECP/Trilinos/packages/amesos2/src/Amesos2_Details_LinearSolverFactory.hpp:49,
                 from /Users/knteran/ECP/Trilinos/packages/amesos2/src/Amesos2_Details_registerLinearSolverFactory.cpp:45:
/Users/knteran/ECP/Trilinos/packages/amesos2/src/Amesos2_Superludist_TypeMap.hpp: At global scope:
/Users/knteran/ECP/Trilinos/packages/amesos2/src/Amesos2_Superludist_TypeMap.hpp:238:20: error: 'LUstruct_t' in namespace 'SLUD::D' does not name a type; did you mean 'dLUstruct_t'?
  238 |   typedef SLUD::D::LUstruct_t LUstruct_t;
      |                    ^~~~~~~~~~
      |                    dLUstruct_t
/Users/knteran/ECP/Trilinos/packages/amesos2/src/Amesos2_Superludist_TypeMap.hpp:239:20: error: 'SOLVEstruct_t' in namespace 'SLUD::D' does not name a type; did you mean 'dSOLVEstruct_t'?
  239 |   typedef SLUD::D::SOLVEstruct_t SOLVEstruct_t;
      |                    ^~~~~~~~~~~~~
      |                    dSOLVEstruct_t
In file included from /Users/knteran/ECP/Trilinos/packages/amesos2/src/Amesos2_Superludist_decl.hpp:58,
                 from /Users/knteran/ECP/Trilinos/packages/amesos2/src/Amesos2_Superludist.hpp:47,
                 from /Users/knteran/ECP/Trilinos/packages/amesos2/src/Amesos2_Factory.hpp:108,
                 from /Users/knteran/ECP/Trilinos/packages/amesos2/src/Amesos2_Details_LinearSolverFactory_def.hpp:52,
                 from /Users/knteran/ECP/Trilinos/packages/amesos2/src/Amesos2_Details_LinearSolverFactory.hpp:49,
                 from /Users/knteran/ECP/Trilinos/packages/amesos2/src/Amesos2_Details_registerLinearSolverFactory.cpp:45:
/Users/knteran/ECP/Trilinos/packages/amesos2/src/Amesos2_Superludist_FunctionMap.hpp:127:19: error: 'Amesos2::type_map<Amesos2::Superludist, double>::LUstruct_t' has not been declared
  127 |         type_map::LUstruct_t* LU, SLUD::gridinfo_t* grid, SLUD::SuperLUStat_t* stat,
```
### Steps to Reproduce

 Configure script:  `/Applications/CMake.app/Contents/bin/cmake ../Trilinos  -DTrilinos_ENABLE_Amesos2=ON -DTrilinos_ENABLE_Amesos=OFF  -DTrilinos_ENABLE_Epetra=ON  -DCMAKE_INSTALL_PREFIX=./install  -DTPL_ENABLE_SuperLUDist=ON -DTPL_SuperLUDist_LIBRARIES='/Users/knteran/ECP/superlu_dist;/Users/knteran/ECP/superlu_dist/include/;/Users/knteran/ECP/superlu_dist/lib' -DSuperLUDist_INCLUDE_DIRS=/Users/knteran/ECP/superlu_dist/include   -DCMAKE_INSTALL_PREFIX=./install `

**Comment by keitat** [comment]
Adding @trilinos/amesos .  Confirmed compile-time errors with the both packages.

**Comment by jhux2** [comment]
@trilinos/amesos @trilinos/amesos2 

@keitat The Epetra stack is as you know not under active development.  It would probably help both development teams to know what's driving this change.

More generally, it would be great if the XSDK project could convince the SuperLU developers to maintain some sort of backwards compatibility.   I

**Comment by keitat** [comment]
@jhux2 A few xSDK packages such as deal.ii rely on Amesos to call sparse direct solver.  For this reason, I suggest supporting the new SuperLU_DIST with old Amesos.  I already created my own folk/branch with the fix.  I am asking Siva to ensure my fix works.

**Comment by srajama1** [comment]
@keitat I didn't understand your request properly. It would be nice to do this in Amesos2, but not in Amesos.

**Comment by keitat** [comment]
@srajama1  Should we ask deal.II developers to switch to Amesos2 and feasibility?  With this proposal, we have to disable Amesos in the Trilinos in xSDK 0.6.

Meanwhile, I have my Amesos and Amesos2 source that works with old and new versions of SuperLU_DIST in https://github.com/keitat/Trilinos/tree/8062-amesos-superludist. This can be a good short term solution.

**Comment by srajama1** [comment]
If deal.II is ok with using Amesos that is actually fine. We will *support* it, I am saying we don't want to add new features to it.

**Comment by keitat** [comment]
@jhux2  According to SuperLU_DIST team, they have to change the API (data structure) in order to have double precision and double complex solvers together in a same application program.  They have introduced some precision-specific data types in the new version. To support backward compatibility, I guess that they have to add macro-heavy source.  ... Modern C++ shines in this situation.

**Comment by keitat** [comment]
> If deal.II is ok with using Amesos that is actually fine. We will _support_ it, I am saying we don't want to add new features to it.

Sure.  BTW, should I post my fork/branch to the pull request?

**Comment by srajama1** [comment]
If you are ok with creating a PR with just Amesos2 changes, it would be easy to review it and merge it.

**Comment by keitat** [comment]
OK, will do.  FYI, my solution with Amesos is adding `#ifdef` macro in the SuperLU_DIST interface, but I understand the danger associated with that.

**Comment by keitat** [comment]
From the xSDK perspective, promoting modern C++ is the solution for interoperability and flexibility.  Especially, the xSDK team/developers should be an exemplar.  I will ask all xSDK folks to switch to Amesos2 for long term solution

**Comment by keitat** [comment]
Comment from the deal.II team on Tpetra.

> We can switch from Amesos to Amesos2 if the latter supports Epetra, but we're set on Epetra for the moment. Switching to Tpetra is a long-term goal, but whenever we looked at that in the past, there were either packages that we need and that hadn't themselves switched to Tpetra, and/or Tpetra itself was still working through interface revisions that made it unattractive to switch to it.

**Comment by keitat** [comment]
> @trilinos/amesos @trilinos/amesos2
> 
> @keitat The Epetra stack is as you know not under active development. It would probably help both development teams to know what's driving this change.
> 
> More generally, it would be great if the XSDK project could convince the SuperLU developers to maintain some sort of backwards compatibility.

Adding some background info in the description.

**Comment by keitat** [comment]
As posted earlier, I talked to the deal.II team for the feasibility of Tpetra/Amesos2.  Unfortunately, it is non-trivialI.  Meanwhile, the xSDK team is updating the version of individual libraries.   If we do not update the SuperLU_DIST support in Amesos, the next xSDK release will have to drop either deal.II or the latest SuperLU_DIST (keep the old version).  I am not sure if this is an acceptable solution in this case.

**Comment by keitat** [comment]
> As posted earlier, I talked to the deal.II team for the feasibility of Tpetra/Amesos2. Unfortunately, it is non-triviaI. Meanwhile, the xSDK team is updating the version of individual libraries. If we do not update the SuperLU_DIST support in Amesos, the next xSDK release will have to drop either deal.II or the latest SuperLU_DIST (keep the old version). I am not sure if this is an acceptable solution. Any alternative/suggestions for the next xSDK release?

deal.II source uses Epetra, AztecOO and Amesos2.  Possible solution is using Amesos2 and Epetra together (still not good solution for long term). I guess it still involves some coding and testing, but simpler than introducing Tpetra and Belos. 
https://github.com/dealii/dealii/blob/master/source/lac/trilinos_solver.cc#L702-L743

**Comment by keitat** [comment]
Sorry, I meant Amesos (not 2!)

**Comment by srajama1** [comment]
@keitat Amesos2 works with Epetra adapters, though no one uses it that way. Can you test that path ?

**Comment by hkthorn** [comment]
@keitat @srajama1 Xyce has been using the Epetra/Amesos2 combination for a couple years now.  This is how we test the ShyLU-Basker solver, KLU2, and other TPLs.  We don't use SuperLU-Dist, so we cannot say that is valid, but much of the other Epetra/Amesos2 mechanics have been tested.

**Comment by srajama1** [comment]
@hkthorn : I didn't realize that. Thanks for that pointer ! 

@keitat : you would want to make sure the tests actually ran as sometimes not finding the package and not doing anything is also a PASS.

**Comment by keitat** [comment]
@srajama1  As for the SuperLU_DIST versioning, this API change could have been treated as a major change (Sherry Li admitted it was a mistake.)  The version 7 will include more changes including the new communication avoiding algorithms.

@kddevin @srajama1 
xSDK members are still asking us for adding SuperLU_DIST6.3 patch in Amesos for a short term solution because the first generation Trilinos packages  (Epetra, AztecOO, if pack and Amesos) are still popular in the user community.  One of the problem is a lack of document describing the future of the first generation Trilinos packages and their interoperability.   I can improve the documentation and putting some examples to help the external users (xSDK project can cover any outreach of Trilinos projects).
