### ISSUE TITLE
Phalanx tutorial code/doxygen don't match

### ISSUE THREAD

**Issue by pbosler** [trilinos/Trilinos#807]
The Phalanx doxygen has a user guide with a tutorial  (https://trilinos.org/docs/r12.8/packages/phalanx/doc/html/user_guide.html) which says that the tutorial code resides in phalanx/example/EnergyFlux, but that directory does not exist in the git repo.  

It seems that much of the tutorial's code may have been moved to phalanx/examples/FEM_Nonlinear but that example does not follow the tutorial's steps.  Data types and template parameters are different in Traits.hpp than the ones specified in the tutorial step 3; the evaluators listed in tutorial step 5 are not in the evaluators folder, etc.

**Comment by rppawlo** [comment]
Unfortunately, the user guide is out of date due to a major refactor of data structures to use Kokkos. I will try to update soon. FEM_Nonlinear is deprecated. The main example is in MultiDimensionalArray.
