### ISSUE TITLE
PR Testing: Create a new GCC 7.2.0 C++14 Serial PR build

### ISSUE THREAD

**Issue by ZUUL42** [trilinos/Trilinos#8071]
## Enhancement
@trilinos/framework 

We are looking to add -std=c++14 to a GCC 7.2.0 build. While some packages are using C++14 (and C++17) features, this will move us in the right direction and ensure that customers will be able to build Trilinos with C++14.
Moving to C++14 will also require us to turn off testing for the 4.9.3 Serial build, so this GCC 7.2.0 build will also be a serial build.

This incremental step is consistent with discussions at the Trilinos Product Leaders meeting and is related to #6260.

**Comment by ZUUL42** [comment]
Initial testing has 20 build errors.
[CDash](https://testing.sandia.gov/cdash/index.php?project=Trilinos&display=project&filtercount=3&showfilters=1&filtercombine=and&field1=site&compare1=61&value1=ascic158&field2=buildname&compare2=61&value2=PR-gcc72c14serial-test-Trilinos_pullrequest_gcc_7.2.0-5688&field3=buildstamp&compare3=61&value3=20200920-0048-Experimental)
All are WError related, either unused-but-set-variable, unused-variable, or one unused-label
Affected packages include @trilinos/nox @trilinos/epetraext @trilinos/ML @trilinos/stokhos @trilinos/anasazi @trilinos/muelu @trilinos/pamgen @trilinos/trilinoscouplings 

Since these warnings are covered in the GCC 8.3.0 build, unless anyone has any objections, I will turn off these warnings for this build. `-Wno-unused-but-set-variable -Wno-unused-variable -Wno-unused-label` Then we've got a clean build for C++14.
[CDash](https://testing.sandia.gov/cdash/index.php?project=Trilinos&display=project&filtercount=3&showfilters=1&filtercombine=and&field1=site&compare1=61&value1=ascic158&field2=buildname&compare2=61&value2=PR-gcc72c14serial-Wno-test-Trilinos_pullrequest_gcc_7.2.0-5695&field3=buildstamp&compare3=61&value3=20200922-0808-Experimental)

**Comment by jhux2** [comment]
> Since these warnings are covered in the GCC 8.3.0 build, unless anyone has any objections, I will turn off these warnings for this build.

@ZUUL42 Would you post a link to the GCC 8.3.0 build?  I can't seem to find it in the list of MueLu dashboard results.

**Comment by lucbv** [comment]
@jhux2 if you go here: [https://testing.sandia.gov/cdash/index.php?project=Trilinos](https://testing.sandia.gov/cdash/index.php?project=Trilinos) you can see it in the clean track and in the Pull Request track

**Comment by jhux2** [comment]
@lucbv Thanks, but I don't see any warnings as failures there.

**Comment by lucbv** [comment]
@jhux2 sure but that's not the question you asked ; )

That probably means that the last line in `cmake/std/PullRequestLinuxGCC8.3.0TestingSettings.cmake` is wrong or overwritten?

**Comment by lucbv** [comment]
@jhux2 @ZUUL42 
so the last line in `cmake/std/PullRequestLinuxGCC8.3.0TestingSettings.cmake` is:
`set(CMAKE_CXX_FLAGS "-std=c++14 -fno-strict-aliasing -Wall -Wno-clobbered -Wno-vla -Wno-pragmas -Wno-unknown-pragmas -Wno-parentheses -Wno-unused-local-typedefs -Wno-literal-suffix -Wno-deprecated-declarations\
 -Wno-misleading-indentation -Wno-int-in-bool-context -Wno-maybe-uninitialized -Wno-class-memaccess -Wno-inline -Wno-nonnull-compare -Wno-address -DTRILINOS_HIDE_DEPRECATED_HEADER_WARNINGS -Werror" CACHE STRIN\
G "Warnings as errors settings")`

and I am guessing that the `-Werror` should happen before `-D TRILINOS_HIDE_DEPRECATED_HEADER_WARNINGS` if it needs to be included in `CMAKE_CXX_FLAGS`

**Comment by jhux2** [comment]
That definition of `CMAKE_CXX_FLAGS` looks weird to me, especially the inclusion of `-DTRILINOS_HIDE_DEPRECATED_HEADER_WARNINGS`.

**Comment by ZUUL42** [comment]
I moved -Werror for the GCC 7.2.0/debug PR builds.
It still is in the old order in the GCC 8.3.0 PR build. I'll catch it there next time I'm making a change, unless it's a pressing issue.
