### ISSUE TITLE
Panzer: Small updates to edge block capability in STK_Interface

### ISSUE THREAD

**Issue by tkordenbrock** [trilinos/Trilinos#8072]
@trilinos/panzer

This issue tracks recent updates to panzer::STK_Interface:
 * fix a bug that prevented edge ID initialization in the 3D mesh factories
 * add an `isEdgeLocal()` method
 * use `put_edge_block_io_part_attribute()` to differentiate edge blocks from sidesets

**Comment by rppawlo** [comment]
@tkordenbrock - can we close this? There is one PR associated with this issue and it has been merged.

**Comment by tkordenbrock** [comment]
@rppawlo - Sorry about that.  I thought it would close automatically when the PR was merged.  Closing now.
