### ISSUE TITLE
Documentation:  Can the bootstrap JavaScript be updated to >v3.4.0

### ISSUE THREAD

**Issue by sebrowne** [trilinos/Trilinos#8073]
## Question
@trilinos/framework

There are reported security vulnerabilities in the bootstrap version (JavaScript code) contained inside of Trilinos (which appear to be related to generating documentation).  Can this be upgraded to >=3.4.0?  That was the listed mitigation for the issues when I had it scanned last.  (Also I didn't know the best team to put, but framework seemed almost barely relevant?)

**Comment by sebrowne** [comment]
@bartlettroscoe

**Comment by bartlettroscoe** [comment]
@sebrowne, what code is this?

**Comment by bartlettroscoe** [comment]
CC: @trilinos/framework, @jwillenbring

**Comment by sebrowne** [comment]
These two in particular, I believe:

./doc/DocumentingParameterLists/webfiles/bootstrap/js/bootstrap.js
./doc/DocumentingParameterLists/webfiles/bootstrap/js/bootstrap.min.js

**Comment by bartlettroscoe** [comment]
People who have touched this:

```
$ cd Trilinos

$ git shortlog -ns doc/DocumentingParameterLists/
    17  William F. Spotz
     2  Brent M. Perschbacher
     2  Dena Vigil
     1  Peter Bosler
     1  Roscoe A. Bartlett
     1  Sidafa Conde
     1  William McLendon
```

This stuff was being used to display ParameterList information at some point.   The main contributed to this (Bill Spotz) is no longer at SNL. No idea if that is stuff still working or if anyone is using any of this.

I  wonder if this needs to even be in Trilinos proper at this point and could not just be pulled out into its own little git repo and cloned under Trilinos and managed with gitdist if someone wanted to use this stuff?

**Comment by jwillenbring** [comment]
This functionality is still used as part of the documentation generation process. There are issues with that process when we move to C++14 on Monday, but it is currently used nightly.

**Comment by jwillenbring** [comment]
I discovered some of the files that were used no longer exist in current versions. It is going to take a little work to see if the new version works. I don't recall the specifics for what this does, and there is no testing I am aware of.

**Comment by sebrowne** [comment]
That's a very acceptable solution to me, thank you!

**Comment by bartlettroscoe** [comment]
> Therefore, I propose that we simply remove these two files from the source tree. 

If someone needs to add back updated files, someone can do that in the future.

**Comment by jwillenbring** [comment]
Since #8376 has been merged into develop, I am closing this issue.
