### ISSUE TITLE
Panzer: getSubcellIndices must store values internally

### ISSUE THREAD

**Issue by rppawlo** [trilinos/Trilinos#808]
In the transition to the refactored Intrepid2, the Panzer_IntrepidFieldPattern_DynRankView.hpp needs to store off the values during calls to getSubcellIndices(...). 

@trilinos/panzer
@trilinos/intrepid2

Blocks #274

**Comment by rppawlo** [comment]
@eric-c-cyr

**Comment by kyungjoo-kim** [comment]
I pushed the fix. @rppawlo if you can pass all panzer test with this commit, please close this ticket.

**Comment by rppawlo** [comment]
Thanks @kyungjoo-kim ! Verified that it fixed the issue. Closing.
