### ISSUE TITLE
Zoltan:  Segmentation fault on graphs from 3D Cartesian grids

### ISSUE THREAD

**Issue by kjetilly** [trilinos/Trilinos#8087]
## Bug Report
@trilinos/Zoltan

### Description
When running the ```simpleGRAPH.c``` example (with printing of the graph disabled) for a graph corresponding to a 30x30x30 Cartesian grid (data file and .c-file here: https://gist.github.com/kjetilly/b3eaf513ffb6c6df7615208d919f5241 ), Zoltan will often fail with a segmentation fault when running a large number of processes. The segmentation faults do not always trigger, but seem to be more frequent with more MPI processes. At 64 processes, we seem to get a failure rate of roughly 50%

This seems to happen exclusively on clusters (tested on the Norwegian cluster Saga and EULER in Switzerland, it seems to fail at the same point of the code on both clusters). I was not able to reproduce this on a local machine. Seems to happen with both OpenMPI (4.0.3) and Intel MPI (2019.7). Compiler used was GCC-9.3.0. 

When using Scotch (by setting the ```"GRAPH_PACKAGE"``` parameter to ```"Scotch"```), this does not happen. This is Scotch version 6.1.0.

### Steps to Reproduce
1. SHA1: 9fec35276d846a667bc668ff4cbdfd8be0dfea08 (version 13.0.0)
2. Configure script: 

```bash
# Here LOCAL_INSTALL_DIR is the folder containing the Trilinos-code
cd Trilinos
mkdir build
cd build
cmake \
    -DCMAKE_INSTALL_PREFIX=${LOCAL_INSTALL_DIR}/trilinostestinstall \
    -DCMAKE_PREFIX_PATH=${LOCAL_INSTALL_DIR}/scotch \
    -DTPL_ENABLE_MPI:BOOL=ON \
    -DTPL_ENABLE_Scotch:BOOL=ON \
    -DTrilinos_ENABLE_ALL_PACKAGES:BOOL=OFF \
    -DTrilinos_ENABLE_Zoltan:BOOL=ON \
    -DCMAKE_BUILD_TYPE=Debug \
    ../
```
2. Configure log: 
[configure_log.txt](https://github.com/trilinos/Trilinos/files/5269406/configure_log.txt)

3. Build log:  
[build_log.txt](https://github.com/trilinos/Trilinos/files/5269403/build_log.txt)

4. [Download simpleGRAPH.c and graph.txt from the gist](https://gist.github.com/kjetilly/b3eaf513ffb6c6df7615208d919f5241). Also attached to this post [graph.txt](https://github.com/trilinos/Trilinos/files/5269086/graph.txt) and [simpleGRAPH.c.txt](https://github.com/trilinos/Trilinos/files/5269104/simpleGRAPH.c.txt) 

5. Compile ```simpleGRAPH.c```
```bash
mpicc simpleGRAPH.c -o simpleGRAPH \
    -I${LOCAL_INSTALL_DIR}/trilinostestinstall \
    ${LOCAL_INSTALL_DIR}/trilinostestinstall/lib/libzoltan.a \
    ${LOCAL_INSTALL_DIR}/scotch/lib/libscotch.a \
    ${LOCAL_INSTALL_DIR}/scotch/lib/libscotcherr.a \
    ${LOCAL_INSTALL_DIR}/scotch/lib/libptscotch.a \
    ${LOCAL_INSTALL_DIR}/scotch/lib/libptscotcherr.a \
   -lm
```
6. Run with 64 processes (we get a roughly 50% failure rate with 64 processes, meaning half the runs fail. For lower number of processes, it happens less frequently, but does still happen)

```bash
# This is typically prefixed with the appropriate submit command
# requesting 64 cores, eg. bsub -n 64
mpirun -np 64 ./simpleGRAPH
```

7.  Sample output (when failing):
[output.txt](https://github.com/trilinos/Trilinos/files/5269113/output.txt)

8. When running it with Scotch as a backend, we do *not* get a segmentation fault, and everything works
```
mpirun -np 64 ./simpleGRAPH Scotch
```

**Comment by jhux2** [comment]
@trilinos/zoltan

**Comment by kddevin** [comment]
@kjetilly Thank you for providing a reproducer code and input.  Unfortunately, I am unable to reproduce this problem.
I built on one cluster with gcc 9.3.0 and openmpi 4.0.3; runs with 64 ranks complete every time.  I also ran this build through valgrind, and saw no errors reported.
I built on another cluster with Intel19 and OpenMPI 4.0.3; again, all runs with 64 ranks complete every time.

Since I cannot reproduce the problem, I'll need your help to address it.  Are you able to run with valgrind or to use the debugger to gather more information?  I am puzzled why your stack trace is pointing to an #ifdef statement.  Have you defined this macro in your build?

**Comment by kjetilly** [comment]
@kddevin Thank you for your reply.

First, for the macro. I assume you mean ```_DEBUG1```?  As far as I can tell, this is defined in Zoltan, in three files:

- ```src/phg/phg_distrib.c```
- ```src/phg/phg_rdivide.c```
- ```src/phg/phg_coarse.c```

It seems to be defined only when ```DEBUG``` is defined, and since I built zoltan with ```CMAKE_BUILD_TYPE=Debug```, ```DEBUG``` should also have been set, and hence ```_DEBUG1``` is set in those files.

I managed to run Valgrind on the cluster, but had to use GCC  8.3.0  and OpenMPI 3.1.4 to get Valgrind to compile.

Attached is the output of a failing run (Valgrind log for each process)  and the full job output   (sorry for  dumping all this output, but better safe than sorry I guess. I think the Valgrind logs look rather similar, but I have not studied them in detail).

I ran Valgrind as

```bash
valgrind --leak-check=full \
         --show-leak-kinds=all \
         --track-origins=yes \
         --verbose \
         --log-file=valgrind-out_%p.txt \
         ./simpleGRAPH
```

[stdout.txt](https://github.com/trilinos/Trilinos/files/5278518/stdout.txt)

[valgrind-out_18012.txt](https://github.com/trilinos/Trilinos/files/5278412/valgrind-out_18012.txt)
[valgrind-out_18013.txt](https://github.com/trilinos/Trilinos/files/5278413/valgrind-out_18013.txt)
[valgrind-out_18014.txt](https://github.com/trilinos/Trilinos/files/5278414/valgrind-out_18014.txt)
[valgrind-out_18015.txt](https://github.com/trilinos/Trilinos/files/5278416/valgrind-out_18015.txt)
[valgrind-out_18016.txt](https://github.com/trilinos/Trilinos/files/5278417/valgrind-out_18016.txt)
[valgrind-out_18017.txt](https://github.com/trilinos/Trilinos/files/5278418/valgrind-out_18017.txt)
[valgrind-out_18018.txt](https://github.com/trilinos/Trilinos/files/5278420/valgrind-out_18018.txt)
[valgrind-out_18019.txt](https://github.com/trilinos/Trilinos/files/5278423/valgrind-out_18019.txt)
[valgrind-out_18020.txt](https://github.com/trilinos/Trilinos/files/5278424/valgrind-out_18020.txt)
[valgrind-out_18022.txt](https://github.com/trilinos/Trilinos/files/5278427/valgrind-out_18022.txt)
[valgrind-out_18023.txt](https://github.com/trilinos/Trilinos/files/5278428/valgrind-out_18023.txt)
[valgrind-out_21655.txt](https://github.com/trilinos/Trilinos/files/5278429/valgrind-out_21655.txt)
[valgrind-out_21656.txt](https://github.com/trilinos/Trilinos/files/5278430/valgrind-out_21656.txt)
[valgrind-out_21657.txt](https://github.com/trilinos/Trilinos/files/5278432/valgrind-out_21657.txt)
[valgrind-out_21658.txt](https://github.com/trilinos/Trilinos/files/5278433/valgrind-out_21658.txt)
[valgrind-out_21659.txt](https://github.com/trilinos/Trilinos/files/5278434/valgrind-out_21659.txt)
[valgrind-out_21660.txt](https://github.com/trilinos/Trilinos/files/5278435/valgrind-out_21660.txt)
[valgrind-out_21661.txt](https://github.com/trilinos/Trilinos/files/5278437/valgrind-out_21661.txt)
[valgrind-out_21662.txt](https://github.com/trilinos/Trilinos/files/5278438/valgrind-out_21662.txt)
[valgrind-out_21663.txt](https://github.com/trilinos/Trilinos/files/5278440/valgrind-out_21663.txt)
[valgrind-out_21664.txt](https://github.com/trilinos/Trilinos/files/5278441/valgrind-out_21664.txt)
[valgrind-out_21665.txt](https://github.com/trilinos/Trilinos/files/5278444/valgrind-out_21665.txt)
[valgrind-out_21666.txt](https://github.com/trilinos/Trilinos/files/5278445/valgrind-out_21666.txt)
[valgrind-out_21667.txt](https://github.com/trilinos/Trilinos/files/5278446/valgrind-out_21667.txt)
[valgrind-out_21668.txt](https://github.com/trilinos/Trilinos/files/5278448/valgrind-out_21668.txt)
[valgrind-out_21669.txt](https://github.com/trilinos/Trilinos/files/5278449/valgrind-out_21669.txt)
[valgrind-out_28264.txt](https://github.com/trilinos/Trilinos/files/5278450/valgrind-out_28264.txt)
[valgrind-out_28265.txt](https://github.com/trilinos/Trilinos/files/5278451/valgrind-out_28265.txt)
[valgrind-out_28266.txt](https://github.com/trilinos/Trilinos/files/5278453/valgrind-out_28266.txt)
[valgrind-out_28267.txt](https://github.com/trilinos/Trilinos/files/5278454/valgrind-out_28267.txt)
[valgrind-out_28268.txt](https://github.com/trilinos/Trilinos/files/5278455/valgrind-out_28268.txt)
[valgrind-out_28269.txt](https://github.com/trilinos/Trilinos/files/5278456/valgrind-out_28269.txt)
[valgrind-out_28270.txt](https://github.com/trilinos/Trilinos/files/5278457/valgrind-out_28270.txt)
[valgrind-out_28271.txt](https://github.com/trilinos/Trilinos/files/5278459/valgrind-out_28271.txt)
[valgrind-out_28272.txt](https://github.com/trilinos/Trilinos/files/5278460/valgrind-out_28272.txt)
[valgrind-out_39316.txt](https://github.com/trilinos/Trilinos/files/5278461/valgrind-out_39316.txt)
[valgrind-out_39317.txt](https://github.com/trilinos/Trilinos/files/5278462/valgrind-out_39317.txt)
[valgrind-out_39318.txt](https://github.com/trilinos/Trilinos/files/5278463/valgrind-out_39318.txt)
[valgrind-out_39319.txt](https://github.com/trilinos/Trilinos/files/5278464/valgrind-out_39319.txt)
[valgrind-out_39320.txt](https://github.com/trilinos/Trilinos/files/5278465/valgrind-out_39320.txt)
[valgrind-out_39321.txt](https://github.com/trilinos/Trilinos/files/5278466/valgrind-out_39321.txt)
[valgrind-out_39322.txt](https://github.com/trilinos/Trilinos/files/5278467/valgrind-out_39322.txt)
[valgrind-out_39323.txt](https://github.com/trilinos/Trilinos/files/5278468/valgrind-out_39323.txt)
[valgrind-out_39324.txt](https://github.com/trilinos/Trilinos/files/5278469/valgrind-out_39324.txt)
[valgrind-out_44523.txt](https://github.com/trilinos/Trilinos/files/5278470/valgrind-out_44523.txt)
[valgrind-out_44524.txt](https://github.com/trilinos/Trilinos/files/5278471/valgrind-out_44524.txt)
[valgrind-out_60094.txt](https://github.com/trilinos/Trilinos/files/5278472/valgrind-out_60094.txt)
[valgrind-out_60095.txt](https://github.com/trilinos/Trilinos/files/5278473/valgrind-out_60095.txt)
[valgrind-out_60096.txt](https://github.com/trilinos/Trilinos/files/5278474/valgrind-out_60096.txt)
[valgrind-out_76738.txt](https://github.com/trilinos/Trilinos/files/5278475/valgrind-out_76738.txt)
[valgrind-out_76739.txt](https://github.com/trilinos/Trilinos/files/5278476/valgrind-out_76739.txt)
[valgrind-out_76740.txt](https://github.com/trilinos/Trilinos/files/5278477/valgrind-out_76740.txt)
[valgrind-out_76741.txt](https://github.com/trilinos/Trilinos/files/5278479/valgrind-out_76741.txt)
[valgrind-out_76742.txt](https://github.com/trilinos/Trilinos/files/5278480/valgrind-out_76742.txt)
[valgrind-out_76743.txt](https://github.com/trilinos/Trilinos/files/5278482/valgrind-out_76743.txt)
[valgrind-out_78097.txt](https://github.com/trilinos/Trilinos/files/5278483/valgrind-out_78097.txt)
[valgrind-out_78098.txt](https://github.com/trilinos/Trilinos/files/5278484/valgrind-out_78098.txt)
[valgrind-out_78099.txt](https://github.com/trilinos/Trilinos/files/5278485/valgrind-out_78099.txt)
[valgrind-out_78100.txt](https://github.com/trilinos/Trilinos/files/5278486/valgrind-out_78100.txt)
[valgrind-out_78101.txt](https://github.com/trilinos/Trilinos/files/5278490/valgrind-out_78101.txt)
[valgrind-out_78102.txt](https://github.com/trilinos/Trilinos/files/5278494/valgrind-out_78102.txt)
[valgrind-out_78103.txt](https://github.com/trilinos/Trilinos/files/5278496/valgrind-out_78103.txt)
[valgrind-out_78104.txt](https://github.com/trilinos/Trilinos/files/5278497/valgrind-out_78104.txt)
[valgrind-out_18021.txt](https://github.com/trilinos/Trilinos/files/5278426/valgrind-out_18021.txt)

**Comment by kjetilly** [comment]
I noticed that with the last  (with Valgrind), the examples were run with OpenMPI 4.0.3, but were compiled with OpenMPI 3.1.4. Attached are the results where it is also run with OpenMPI 3.1.4. Sorry  for the confusion! 

[stdout.txt](https://github.com/trilinos/Trilinos/files/5278793/stdout.txt)
[valgrind-out_619.txt](https://github.com/trilinos/Trilinos/files/5278795/valgrind-out_619.txt)
[valgrind-out_620.txt](https://github.com/trilinos/Trilinos/files/5278797/valgrind-out_620.txt)
[valgrind-out_621.txt](https://github.com/trilinos/Trilinos/files/5278799/valgrind-out_621.txt)
[valgrind-out_622.txt](https://github.com/trilinos/Trilinos/files/5278801/valgrind-out_622.txt)
[valgrind-out_623.txt](https://github.com/trilinos/Trilinos/files/5278802/valgrind-out_623.txt)
[valgrind-out_624.txt](https://github.com/trilinos/Trilinos/files/5278804/valgrind-out_624.txt)
[valgrind-out_1915.txt](https://github.com/trilinos/Trilinos/files/5278805/valgrind-out_1915.txt)
[valgrind-out_1916.txt](https://github.com/trilinos/Trilinos/files/5278806/valgrind-out_1916.txt)
[valgrind-out_1917.txt](https://github.com/trilinos/Trilinos/files/5278809/valgrind-out_1917.txt)
[valgrind-out_1918.txt](https://github.com/trilinos/Trilinos/files/5278810/valgrind-out_1918.txt)
[valgrind-out_1919.txt](https://github.com/trilinos/Trilinos/files/5278811/valgrind-out_1919.txt)
[valgrind-out_1920.txt](https://github.com/trilinos/Trilinos/files/5278813/valgrind-out_1920.txt)
[valgrind-out_1921.txt](https://github.com/trilinos/Trilinos/files/5278814/valgrind-out_1921.txt)
[valgrind-out_1922.txt](https://github.com/trilinos/Trilinos/files/5278815/valgrind-out_1922.txt)
[valgrind-out_1923.txt](https://github.com/trilinos/Trilinos/files/5278816/valgrind-out_1923.txt)
[valgrind-out_1924.txt](https://github.com/trilinos/Trilinos/files/5278818/valgrind-out_1924.txt)
[valgrind-out_1925.txt](https://github.com/trilinos/Trilinos/files/5278819/valgrind-out_1925.txt)
[valgrind-out_1926.txt](https://github.com/trilinos/Trilinos/files/5278820/valgrind-out_1926.txt)
[valgrind-out_1927.txt](https://github.com/trilinos/Trilinos/files/5278821/valgrind-out_1927.txt)
[valgrind-out_1928.txt](https://github.com/trilinos/Trilinos/files/5278823/valgrind-out_1928.txt)
[valgrind-out_1929.txt](https://github.com/trilinos/Trilinos/files/5278824/valgrind-out_1929.txt)
[valgrind-out_26611.txt](https://github.com/trilinos/Trilinos/files/5278826/valgrind-out_26611.txt)
[valgrind-out_26612.txt](https://github.com/trilinos/Trilinos/files/5278827/valgrind-out_26612.txt)
[valgrind-out_26613.txt](https://github.com/trilinos/Trilinos/files/5278829/valgrind-out_26613.txt)
[valgrind-out_26614.txt](https://github.com/trilinos/Trilinos/files/5278830/valgrind-out_26614.txt)
[valgrind-out_26615.txt](https://github.com/trilinos/Trilinos/files/5278831/valgrind-out_26615.txt)
[valgrind-out_26616.txt](https://github.com/trilinos/Trilinos/files/5278832/valgrind-out_26616.txt)
[valgrind-out_26617.txt](https://github.com/trilinos/Trilinos/files/5278834/valgrind-out_26617.txt)
[valgrind-out_26618.txt](https://github.com/trilinos/Trilinos/files/5278835/valgrind-out_26618.txt)
[valgrind-out_26619.txt](https://github.com/trilinos/Trilinos/files/5278836/valgrind-out_26619.txt)
[valgrind-out_26620.txt](https://github.com/trilinos/Trilinos/files/5278838/valgrind-out_26620.txt)
[valgrind-out_26621.txt](https://github.com/trilinos/Trilinos/files/5278839/valgrind-out_26621.txt)
[valgrind-out_26622.txt](https://github.com/trilinos/Trilinos/files/5278840/valgrind-out_26622.txt)
[valgrind-out_26623.txt](https://github.com/trilinos/Trilinos/files/5278841/valgrind-out_26623.txt)
[valgrind-out_26624.txt](https://github.com/trilinos/Trilinos/files/5278842/valgrind-out_26624.txt)
[valgrind-out_26625.txt](https://github.com/trilinos/Trilinos/files/5278843/valgrind-out_26625.txt)
[valgrind-out_33422.txt](https://github.com/trilinos/Trilinos/files/5278844/valgrind-out_33422.txt)
[valgrind-out_33423.txt](https://github.com/trilinos/Trilinos/files/5278845/valgrind-out_33423.txt)
[valgrind-out_33424.txt](https://github.com/trilinos/Trilinos/files/5278846/valgrind-out_33424.txt)
[valgrind-out_33425.txt](https://github.com/trilinos/Trilinos/files/5278847/valgrind-out_33425.txt)
[valgrind-out_33426.txt](https://github.com/trilinos/Trilinos/files/5278849/valgrind-out_33426.txt)
[valgrind-out_33427.txt](https://github.com/trilinos/Trilinos/files/5278850/valgrind-out_33427.txt)
[valgrind-out_33428.txt](https://github.com/trilinos/Trilinos/files/5278851/valgrind-out_33428.txt)
[valgrind-out_33429.txt](https://github.com/trilinos/Trilinos/files/5278852/valgrind-out_33429.txt)
[valgrind-out_33430.txt](https://github.com/trilinos/Trilinos/files/5278853/valgrind-out_33430.txt)
[valgrind-out_33431.txt](https://github.com/trilinos/Trilinos/files/5278855/valgrind-out_33431.txt)
[valgrind-out_33432.txt](https://github.com/trilinos/Trilinos/files/5278856/valgrind-out_33432.txt)
[valgrind-out_33433.txt](https://github.com/trilinos/Trilinos/files/5278858/valgrind-out_33433.txt)
[valgrind-out_51689.txt](https://github.com/trilinos/Trilinos/files/5278859/valgrind-out_51689.txt)
[valgrind-out_51690.txt](https://github.com/trilinos/Trilinos/files/5278861/valgrind-out_51690.txt)
[valgrind-out_69208.txt](https://github.com/trilinos/Trilinos/files/5278863/valgrind-out_69208.txt)
[valgrind-out_69209.txt](https://github.com/trilinos/Trilinos/files/5278864/valgrind-out_69209.txt)
[valgrind-out_69210.txt](https://github.com/trilinos/Trilinos/files/5278865/valgrind-out_69210.txt)
[valgrind-out_69211.txt](https://github.com/trilinos/Trilinos/files/5278866/valgrind-out_69211.txt)
[valgrind-out_78459.txt](https://github.com/trilinos/Trilinos/files/5278870/valgrind-out_78459.txt)
[valgrind-out_78460.txt](https://github.com/trilinos/Trilinos/files/5278871/valgrind-out_78460.txt)
[valgrind-out_78461.txt](https://github.com/trilinos/Trilinos/files/5278873/valgrind-out_78461.txt)
[valgrind-out_78462.txt](https://github.com/trilinos/Trilinos/files/5278874/valgrind-out_78462.txt)
[valgrind-out_78463.txt](https://github.com/trilinos/Trilinos/files/5278875/valgrind-out_78463.txt)
[valgrind-out_78464.txt](https://github.com/trilinos/Trilinos/files/5278877/valgrind-out_78464.txt)
[valgrind-out_78465.txt](https://github.com/trilinos/Trilinos/files/5278878/valgrind-out_78465.txt)
[valgrind-out_78466.txt](https://github.com/trilinos/Trilinos/files/5278880/valgrind-out_78466.txt)
[valgrind-out_78467.txt](https://github.com/trilinos/Trilinos/files/5278881/valgrind-out_78467.txt)
[valgrind-out_78468.txt](https://github.com/trilinos/Trilinos/files/5278882/valgrind-out_78468.txt)
