### ISSUE TITLE
Intrepid2: add Const Basis

### ISSUE THREAD

**Issue by rppawlo** [trilinos/Trilinos#809]
Panzer contains an extra Basis implementation for a const Basis. This object should be moved into Intrepid2. It will need the addition of the dofCoords support as that is currently missing.

@rppawlo will transition Panzer to use this once the object is added to Intrepid2.

@trilinos/panzer
@trilinos/intrepid2

**Comment by kyungjoo-kim** [comment]
pushed const basis and its unit tests.

**Comment by rppawlo** [comment]
I switched panzer to use the intrepid version but did not delete the old version in panzer yet. All tests are passing. Will add a ticket to panzer to remove the old const basis.
