### ISSUE TITLE
Belos: PseudoBlockGmres complex tests failing

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#81]
@trilinos/belos 

Belos_bl_gmres_complex_hb_3 and Belos_bl_gmres_complex_hb_4 fail.  See e.g., the perseus test on the Dashboard.  They fail for me in both MPI debug and non-MPI release builds.  The tests in question do NOT exercise either Epetra or Tpetra; they use Belos' custom linear algebra implementation that Belos has long used for testing.  I'm not sure how long the tests have been failing.  I played with the test executable and matrix, and did get them to converge when I changed the restart length, e.g.,

`/Belos_bl_gmres_complex_hb.exe --verbose --filename=mhd1280a.cua --pseudo --num-restarts=1 --frequency=1 --subspace-length=800 --num-restarts=1000`

Thus, I'm not sure what's going on here.  Could it be that the expected convergence rate depends on a particular random right-hand side, and I'm using a different system library's pseudorandom number generator?  (I'm using Clang 3.7 on Mac.)

**Comment by mhoemmen** [comment]
As a temporary measure, I will disable the two tests in question.

**Comment by mhoemmen** [comment]
btw I did actually disable those two tests.

**Comment by kddevin** [comment]
@mhoemmen 
@trilinos/belos 
I am trying to run the checkin script.  With the MPI_DEBUG build, I get the following Belos failures.  Are they related to this bug?  Or do I need some special CMake magic that is not enabled by default in the checkin script?  These tests were enabled only because I was running with forward dependencies enabled; my code changes were all in zoltan and zoltan2.   Thanks for your help!
         91 - Belos_gcrodr_hb_MPI_4 (Timeout)
	 94 - Belos_rcg_hb_MPI_4 (Timeout)
	102 - Belos_pseudo_ptfqmr_hb_1_MPI_4 (Failed)
	104 - Belos_pseudo_ptfqmr_hb_3_MPI_4 (Failed)

I'm not sure why 91 and 94 timed out.  They both ran for 1300 seconds.  How much more time do they need?

Error messages from 102:
   Passed.......OR Combination ->
     Failed.......Number of Iterations = 1029 == 1029
     Failed.......SEQ Combination ->

Error messages from 104:
     Failed.......Number of Iterations = 1029 == 1029
     Unconverged..(2-Norm Imp Res Vec) / (2-Norm Prec Res0)

**Comment by mhoemmen** [comment]
I'm in meetings all week, alas, but I think it's OK for you to disable these tests for now, by setting the appropriate arguments to CTest.  I don't have them right now but I can find them if you don't know how to do it.

**Comment by hkthorn** [comment]
I'm working on the pseudo-block tfqmr errors, so they are known.

I have no idea why the RCG and GCRO-DR tests timed out.

--

Heidi K. Thornquist
Electrical Models & Simulation
Sandia National Laboratories
Albuquerque, NM  87185-1323

**Comment by kddevin** [comment]
@mhoemmen
@trilinos/belos 
Thanks, Mark and Heidi.
I'm asking because Mike H. said when we have checkin test problems, we should report the issues.  I will just push my zoltan/zoltan2 changes.  I don't want to risk messing up your testing by disabling things I don't understand.

**Comment by mhoemmen** [comment]
You can pass the check-in test script --ctest-options to disable tests.  It takes a regular expression.  For example:

--ctest-options="-E '(TeuchosCore_MemoryManagement_UnitTests|Anasazi_Epetra_BKS_solvertest)'"

**Comment by maherou** [comment]
Karen,

Thanks for being conscientious about the failures.  This kind of attention to failures is really important as we go forward.

Mike

**Comment by bartlettroscoe** [comment]
This just blocked my push as well with the checkin-test.py script.  I am disabling these tests for all future pushes until this is resolved.  Once I push, see the updated script:

   Trilinos/cmake/ctest/drivers/fissile4/checkin-test-fissile4.sh

We need a policy that if there are failing tests like this that are know to fail and block pushes, that someone would take the initiative to disable the tests for pre-push testing. You can do by changing CATEGORES from BASIC to NIGHTLY.  But pushing on this is likely not worthwhile until we get a reasonable CI env set up.

**Comment by hkthorn** [comment]
Ross, are you pushing on the release branch?  The pseudo-block GMRES tests that were failing have been removed on the development branch.

Thanks!
Heidi

--

Heidi K. Thornquist
Electrical Models & Simulation
Sandia National Laboratories
Albuquerque, NM  87185-1323

**Comment by bartlettroscoe** [comment]
> Ross, are you pushing on the release branch? The pseudo-block GMRES tests that were failing have been removed on the development branch.

I am only disabling these in my invocation of the checkin-test.py script on the master branch.  I don't presume to disable this for everyone without the buy-in from the Belos developers.  But if you know that you have tests that are failing on several platforms stopping people's pushes, you should remove them from the BASIC (pre-push) test suite.

**Comment by bartlettroscoe** [comment]
I was able to successfully push after disabling these two tests.  See commit dd61cd6 for details on how this was done.  This can be used as a template for other people for their own checkin-test.py drivers.
