### ISSUE TITLE
Change Trilinos default to ETI=ON

### ISSUE THREAD

**Issue by jwillenbring** [trilinos/Trilinos#8130]
## Enhancement
@trilinos/framework 

CC: @kddevin @rppawlo @ccober6 @srajama1 @maherou @mperego 

We have decided to move forward with changing the default for Trilinos to ETI=ON. We need to decide when and how. How much notice do we provide? Do we wait for a major version of Trilinos? (We seem to be leaning towards no).

Most, if not nearly all, customers already explicitly turn ETI to ON.

**Comment by kddevin** [comment]
There's no need to wait for a major version release; is there a minor release coming soon?
Can we just advertise in mailing lists, SART meetings, etc., for a few weeks and then do it?

**Comment by jwillenbring** [comment]
There is not a specific date chosen for a minor release, but we had tentatively planned one for this fall. We could target, for example, Oct 27 if people think that would be a good day to branch. I am open to later than that too. I don't want to go a lot sooner, just because we tend to provide people with some notice. Also, just getting onto develop is not sufficient for people to get their changes in, the dev->master promotion also has to happen for any changes included in the release, so I want to allow a little time for that in case there is a hiccup in that process.

**Comment by jwillenbring** [comment]
There is now a PR up for this. See #8333

**Comment by prwolfe** [comment]
> There is now a PR up for this. See #8333

The PR was moved to https://github.com/trilinos/Trilinos/pull/8333 per the authors request

**Comment by prwolfe** [comment]
> There is now a PR up for this. See #8333

The PR was moved to https://github.com/TriBITSPub/TriBITS/pull/336 per the authors request.

**Comment by bartlettroscoe** [comment]
FYI: This is a duplicate of #361 from 4.5 years ago.

I will update the PR  TriBITSPub/TriBITS#336 to fix the documentation and edit the commit message to point back to this issue.  I will post a Trilinos PR with an updated TriBITS snapshot with this change.

Thanks for finally agreeing to make this change!

**Comment by bartlettroscoe** [comment]
The new Trilinos PR is #8340.  Please approve so it will get merged.  And thanks again!

**Comment by bartlettroscoe** [comment]
With the merge of #8340, this should not be complete.

**Comment by jwillenbring** [comment]
As Ross said, this can be closed.

**Comment by bartlettroscoe** [comment]
Related to:
* SEPW-213
