### ISSUE TITLE
Kokkos: configure error in OpenMP build with -D KOKKOS_ENABLE_LIBDL:BOOL=ON

### ISSUE THREAD

**Issue by ikalash** [trilinos/Trilinos#8134]
It appears in one of the openmp builds we have for Albany on my Fedora workstation camobap, adding the -D KOKKOS_ENABLE_LIBDL:BOOL=ON \ option leads to a configure error.  The relevant output files are attached.  Do you have any idea of what could be happening?  It could be that some of the other options in the configure file I’m using conflict with this one.  I noticed some warnings printed to screen when configuring.  Tagging @jewatkins who is also interested in this issue.

[CMakeError.log](https://github.com/trilinos/Trilinos/files/5314769/CMakeError.log)
[CMakeOutput.log](https://github.com/trilinos/Trilinos/files/5314770/CMakeOutput.log)
[cmake_out.txt](https://github.com/trilinos/Trilinos/files/5314774/cmake_out.txt)

@trilinos/kokkos

**Comment by crtrott** [comment]
Thansk for the report. Can you as a workaround just try to turn the tests for Kokkos off?

**Comment by ikalash** [comment]
That fixes it.  Thanks!

**Comment by jjwilke** [comment]
We have a PR open to address this.
