### ISSUE TITLE
Xpetra/Epetra test not compiled (NO_64BIT_GLOBAL_INDICES ON)

### ISSUE THREAD

**Issue by sagitter** [trilinos/Trilinos#814]
Hi all.

`Xpetra` test s not compiled with this error on Fedora 24 64-bit:

```
/builddir/build/BUILD/trilinos-12.8.1/Trilinos-trilinos-release-12-8-1/packages/xpetra/test/MatrixMatrix/MatrixMatrix_UnitTests.cpp: In member function 'void {anonymous}::MatrixMatrix_Multiply_Epetra64_UnitTest<M, MA, Scalar, LO, GO, Node>::runUnitTestImpl(Teuchos::FancyOStream&, bool&) const':
/builddir/build/BUILD/trilinos-12.8.1/Trilinos-trilinos-release-12-8-1/packages/xpetra/test/MatrixMatrix/MatrixMatrix_UnitTests.cpp:299:7: error: 'MatrixMarketFileToCrsMatrix64' is not a member of 'EpetraExt'
       EpetraExt::MatrixMarketFileToCrsMatrix64("A.mat",*epMap,*epMap,*epMap,ptrA);
       ^~~~~~~~~
/builddir/build/BUILD/trilinos-12.8.1/Trilinos-trilinos-release-12-8-1/packages/xpetra/test/MatrixMatrix/MatrixMatrix_UnitTests.cpp:300:7: error: 'MatrixMarketFileToCrsMatrix64' is not a member of 'EpetraExt'
       EpetraExt::MatrixMarketFileToCrsMatrix64("B.mat",*epMap,*epMap,*epMap,ptrB);
       ^~~~~~~~~
/builddir/build/BUILD/trilinos-12.8.1/Trilinos-trilinos-release-12-8-1/packages/xpetra/test/MatrixMatrix/MatrixMatrix_UnitTests.cpp:301:7: error: 'MatrixMarketFileToCrsMatrix64' is not a member of 'EpetraExt'
       EpetraExt::MatrixMarketFileToCrsMatrix64("AB.mat",*epMap,*epMap,*epMap,ptrAB);
       ^~~~~~~~~
/builddir/build/BUILD/trilinos-12.8.1/Trilinos-trilinos-release-12-8-1/packages/xpetra/test/MatrixMatrix/MatrixMatrix_UnitTests.cpp:302:7: error: 'MatrixMarketFileToCrsMatrix64' is not a member of 'EpetraExt'
       EpetraExt::MatrixMarketFileToCrsMatrix64("AtB.mat",*epMap,*epMap,*epMap,ptrAtB);
       ^~~~~~~~~
/builddir/build/BUILD/trilinos-12.8.1/Trilinos-trilinos-release-12-8-1/packages/xpetra/test/MatrixMatrix/MatrixMatrix_UnitTests.cpp:303:7: error: 'MatrixMarketFileToCrsMatrix64' is not a member of 'EpetraExt'
       EpetraExt::MatrixMarketFileToCrsMatrix64("ABt.mat",*epMap,*epMap,*epMap,ptrABt);
       ^~~~~~~~~
/builddir/build/BUILD/trilinos-12.8.1/Trilinos-trilinos-release-12-8-1/packages/xpetra/test/MatrixMatrix/MatrixMatrix_UnitTests.cpp:304:7: error: 'MatrixMarketFileToCrsMatrix64' is not a member of 'EpetraExt'
       EpetraExt::MatrixMarketFileToCrsMatrix64("AtBt.mat",*epMap,*epMap,*epMap,ptrAtBt);
       ^~~~~~~~~
packages/xpetra/test/MatrixMatrix/CMakeFiles/Xpetra_MatrixMatrix_UnitTests.dir/build.make:65: recipe for target 'packages/xpetra/test/MatrixMatrix/CMakeFiles/Xpetra_MatrixMatrix_UnitTests.dir/MatrixMatrix_UnitTests.cpp.o' failed
make[2]: Leaving directory '/builddir/build/BUILD/trilinos-12.8.1/Trilinos-trilinos-release-12-8-1/build'
make[2]: *** [packages/xpetra/test/MatrixMatrix/CMakeFiles/Xpetra_MatrixMatrix_UnitTests.dir/MatrixMatrix_UnitTests.cpp.o] Error 1
CMakeFiles/Makefile2:43098: recipe for target 'packages/xpetra/test/MatrixMatrix/CMakeFiles/Xpetra_MatrixMatrix_UnitTests.dir/all' failed
```
Full log: https://kojipkgs.fedoraproject.org//work/tasks/2528/16402528/build.log

`cmake` configuration:

`+ /usr/bin/cmake -DCMAKE_C_FLAGS_RELEASE:STRING=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE:STRING=-DNDEBUG -DCMAKE_Fortran_FLAGS_RELEASE:STRING=-DNDEBUG -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DCMAKE_INSTALL_PREFIX:PATH=/usr -DINCLUDE_INSTALL_DIR:PATH=/usr/include -DLIB_INSTALL_DIR:PATH=/usr/lib64 -DSYSCONF_INSTALL_DIR:PATH=/etc -DSHARE_INSTALL_PREFIX:PATH=/usr/share -DLIB_SUFFIX=64 -DBUILD_SHARED_LIBS:BOOL=ON -DCMAKE_BUILD_TYPE:STRING=Release '-DCMAKE_C_FLAGS_RELEASE:STRING=-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -Wl,-z,relro -fPIC -Wl,-z,now' '-DCMAKE_CXX_FLAGS_RELEASE:STRING=-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -Wl,-z,relro -fPIC -Wl,-z,now' '-DCMAKE_Fortran_FLAGS_RELEASE:STRING=-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -Wl,-z,relro -fPIC -Wl,-z,now' '-DCMAKE_EXE_LINKER_FLAGS:STRING=-Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -fPIC -pie -Wl,-z,now -Wl,--as-needed' -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_SKIP_RPATH:BOOL=YES -DCMAKE_SKIP_INSTALL_RPATH:BOOL=YES -DBUILD_SHARED_LIBS:BOOL=ON -DTPL_ENABLE_MPI=OFF -DTrilinos_ENABLE_FORTRAN:BOOL=ON -DTrilinos_ENABLE_TESTS:BOOL=ON -DTrilinos_ENABLE_OpenMP:BOOL=ON -DTrilinos_ENABLE_PyTrilinos:BOOL=OFF -DTpetra_INST_SERIAL:BOOL=ON -DCMAKE_VERBOSE_MAKEFILE=TRUE -DTrilinos_VERBOSE_CONFIGURE=OFF -DTrilinos_ENABLE_CXX11=ON -DTrilinos_INSTALL_INCLUDE_DIR=/usr/include/trilinos -DTrilinos_INSTALL_LIB_DIR=/usr/lib64 -DTrilinos_INSTALL_RUNTIME_DIR=/usr/bin -DTrilinos_INSTALL_EXAMPLE_DIR=/usr/share/trilinos/examples -DTrilinos_ENABLE_STRONG_C_COMPILE_WARNINGS=OFF -DTrilinos_ENABLE_STRONG_CXX_COMPILE_WARNINGS=OFF -DTrilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON -DTPL_ENABLE_gtest:BOOL=OFF -DTrilinos_ENABLE_STK:BOOL=OFF -DTrilinos_ENABLE_ALL_PACKAGES=ON -DTrilinos_NO_64BIT_GLOBAL_INDICES=ON ..`

**Comment by mhoemmen** [comment]
@trilinos/xpetra 

Hm, given `-DTrilinos_NO_64BIT_GLOBAL_INDICES=ON` and the build error in `EpetraExt::MatrixMarketFileToCrsMatrix64`, it looks like there are some EpetraExt features (or Xpetra use of those features) that might not be protected with the right macro.

We normally don't set `-DTrilinos_NO_64BIT_GLOBAL_INDICES=ON`.  Its default setting is `OFF`.  Is there some reason why you set it to ON?  Just curious :)

**Comment by sagitter** [comment]
>Hm, given -DTrilinos_NO_64BIT_GLOBAL_INDICES=ON and the build error in EpetraExt::MatrixMarketFileToCrsMatrix64, it looks like there are some EpetraExt features (or Xpetra use of those features) that might not be protected with the right macro.

Yes, i had realized that and i'm rebuilding without that option.

>We normally don't set -DTrilinos_NO_64BIT_GLOBAL_INDICES=ON. Its default setting is OFF. Is there some reason why you set it to ON? Just curious :)

Maybe, i have misunderstood its function. `Release_notes` reports:

> Epetra
>   Added support for 64-bit global indices
>   
>   Epetra supports 64-bit global indices beginning with Trilinos Release 11.0
>   by using the "long long" datatype. Epetra still supports 32-bit global
>   indices and the interface for using them remains the same.
>   
>   - To construct Epetra objects for 64-bit indices, certain input arguments
>     must be "long long" instead of "int". For example, compare
>     
>       32: Epetra_BlockMap(int NumGlobalElements, int NumMyElements,
>                           const int *MyGlobalElements, ...)
>       64: Epetra_BlockMap(long long NumGlobalElements, int NumMyElements,
>                           const long long *MyGlobalElements, ...)
> 
>   - New member functions that return a long long value have a suffix "64". For
>     example, GID64, NumGlobalNonzeros64, MaxAllGID64, etc. These functions work
>     whether the underlying object is 32-bit or 64-bit based. The older
>     non-suffixed functions work for 32-bit objects only.
> 
>   - New classes added for "long long" data: Epetra_LongLongVector,
>     Epetra_LongLongSerialDenseVector, Epetra_LongLongSerialDenseMatrix.
> 
>   - To build Epetra and dependent packages without any 64-bit support turn on
>     the CMake flag Trilinos_NO_64BIT_GLOBAL_INDICES. Default is off.
> 
>   - To enforce that a code is truly compatible with 64-bit Epetra
>     turn on the CMake flag Trilinos_NO_32BIT_GLOBAL_INDICES, and fix any
>     compile-time or run-time errors. Default is off.
> 
>   Epetra 64-bit support FAQ (compile problem)
> 
>   Epetra-dependent code may not compile if it relied on automatic type
>   conversion to "int" from non-int types when constructing Epetra objects or
>   calling certain member functions. This is because now there can be ambiguity
>   due to overloading. Use explicit conversion to either "int" or "long long".

Shouldn't it disable build of `64-bit integer` libraries?

**Comment by mhoemmen** [comment]
@sagitter wrote:
> Shouldn't it disable build of 64-bit integer libraries?

No.  This is the "Epetra64" feature that _adds_ a 64-bit integer interface (using `long long`) to the Epetra package.  The feature has nothing to do with `sizeof(void*)`.  64-bit indices refer only to _global_ indices, that is, indices across multiple MPI processes.  _Local_ indices are still 32 bits in Epetra, so local (per MPI process) data structures must still fit in 32 bits.  Thus, in theory the Epetra64 feature could even work with `sizeof(void*) == 4`, though we do not test this as far as I know.

In general, the experience of building Trilinos gets easier, the fewer nondefault options you enable :-)  However, I'm glad that you tested this, because it revealed an apparent bug in Xpetra.

**Comment by sagitter** [comment]
Okay; i suspect that even issue #794 is related to the option `-DTrilinos_NO_64BIT_GLOBAL_INDICES=ON`

**Comment by mhoemmen** [comment]
@sagitter , I think you're right :)

**Comment by sagitter** [comment]
Thank you.

**Comment by mhoemmen** [comment]
@sagitter sure you want to close this?  it looks like an actual bug, though not a critical one for us since it's a nondefault option.
