### ISSUE TITLE
Framework: PR testing fails due to leftover (?)

### ISSUE THREAD

**Issue by cgcgcg** [trilinos/Trilinos#8145]
## Bug Report
@trilinos/framework 

### Description
PR testing on ascic158 fails for at least two different PRs:
- PR #8144
  https://testing.sandia.gov/cdash/index.php?project=Trilinos&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=63&value1=PR-8144-test&field2=buildstarttime&compare2=84&value2=NOW
- PR #8143
  https://testing.sandia.gov/cdash/index.php?project=Trilinos&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=63&value1=PR-8143-test&field2=buildstarttime&compare2=84&value2=NOW

The only reported error is
```
packages/rythmos/src/librythmos.so.13.1: file not recognized: File format not recognized
```
Is this possibly a leftover from a previous failed build?

**Comment by cgcgcg** [comment]
@GrahamBenHarper

**Comment by GrahamBenHarper** [comment]
I force-pushed in the middle of the testing, so that could have caused an issue. I also see I need to fix the `MPI_4` region unit tests based on my local testing.

**Comment by cgcgcg** [comment]
No, it already started failing over the weekend. If anybody caused it, that's me. But aborting an autotester run should not leave the whole system in a broken state..

**Comment by jhux2** [comment]
@jwillenbring Is there someone who has access to the test machine in question and could look into this?

**Comment by jhux2** [comment]
This is potentially block a lot of PRs?

**Comment by jwillenbring** [comment]
I reset the build spaces on all PR test machines. That will force a new fresh build the next time any PR runs.

**Comment by cgcgcg** [comment]
@jwillenbring Thank you!

**Comment by cgcgcg** [comment]
Hm, something else might be broken on ascic158. PR #8144 failed again with the same issue. PR #8143 ended up running on a different node and passed this time.

**Comment by jwillenbring** [comment]
@prwolfe Can you check if ascic158 has a full drive or other issues? Otherwise, we may need to put this node to sleep for a while.

**Comment by prwolfe** [comment]
The node had plenty of space and memory. I found a significant number of zombie processes. The library also came back as "data" instead of as a library when I did a "file libname".

I killed all of the zombies and removed the build directories. I think watching it for a bit is in order, but I don't expect removing it is. As a note, the same PR ran most of it's intel 17 builds there without incident.

**Comment by cgcgcg** [comment]
Thanks, @prwolfe

**Comment by cgcgcg** [comment]
Seems fixed, see https://testing.sandia.gov/cdash/index.php?project=Trilinos&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=63&value1=PR-8006-test&field2=buildstarttime&compare2=84&value2=NOW

**Comment by prwolfe** [comment]
I was just about to ask - thanks for the follow up!
