### ISSUE TITLE
Test ML_ValidateParameters_compareTestOutput dying in continuous

### ISSUE THREAD

**Issue by bmpersc** [trilinos/Trilinos#815]
@jhux2 The ML_ValidateParameters_compareTestOutput is dying with a python error in compareTestOuput. The issue is baffling to me and I am certain it is an issue with the system and not an ML problem. Apparently the script is unable to import the re module. I am looking into this to see if I can find out that the issue is.

You can view the error at:
https://testing.sandia.gov/cdash/viewTest.php?onlyfailed&buildid=2614816

**Comment by jhux2** [comment]
@bmpersc There's no recent changes to ML that could cause this.  I agree, it looks like a system issue of some kind.
