### ISSUE TITLE
Xpetra: build error under windows

### ISSUE THREAD

**Issue by jhux2** [trilinos/Trilinos#8157]
## Bug Report
@trilinos/xpetra 

### Description

A user reported this error:

```
D:\winsame\cary\vorpalall-dev3\builds\trilinos-13.0.0\packages\xpetra\sup\Utils/Xpetra_MatrixMatrix.hpp(62,10):
fatal error: 'execinfo.h' file not found
#include <execinfo.h>
```

He tried https://github.com/kokkos/kokkos/pull/2977/commits/9f6f9f8ecd320470d25e0094603c0255ff6afb40, but that did not fix the error.

**Comment by jhux2** [comment]
@brian-kelley Looks like maybe you added the `execinfo.h` header to Xpetra_MatrixMatrix.hpp.  Do you remember why?  Looks like it provides backtrace information, but is perhaps Linux specific.

**Comment by jrobcary** [comment]
This was configured with llvm-clang using

'/winsame/dev3/contrib-llvm_vs2017/cmake-3.18.2-ser/bin/cmake' \
  -DCMAKE_INSTALL_PREFIX:PATH=D:/winsame/dev3/contrib-llvm_vs2017/trilinos-13.0.0-sercomm \
  -DCMAKE_BUILD_TYPE:STRING=Release \
  -DCMAKE_COLOR_MAKEFILE:BOOL=FALSE \
  -DCMAKE_VERBOSE_MAKEFILE:BOOL=TRUE \
  -DCMAKE_C_COMPILER:FILEPATH='C:/Program Files/LLVM/bin/clang-cl.exe' \
  -DCMAKE_CXX_COMPILER:FILEPATH='C:/Program Files/LLVM/bin/clang-cl.exe' \
  -DCMAKE_Fortran_COMPILER:FILEPATH='' \
  -DCMAKE_C_FLAGS:STRING='/W3 /D__STDC__=1' \
  -DCMAKE_CXX_FLAGS:STRING='/W3 /GR /EHsc /std:c++17 /Zc:__cplusplus /D_HAS_AUTO_PTR_ETC -fms-compatibility-version=19 -Wno-register' \
  -DCMAKE_Fortran_FLAGS:STRING='' \
  -DDART_TESTING_TIMEOUT:STRING=600 \
  -DPYTHON_EXECUTABLE:FILEPATH=D:/winsame/dev3/contrib-llvm_vs2017/Python-mastertxc.u20151102.270-pycsh/python.exe \
  -DTrilinos_ENABLE_Fortran=OFF \
  -DTrilinos_ENABLE_Kokkos:BOOL=FALSE \
  -DTrilinos_ENABLE_Belos:BOOL=FALSE \
  -DTrilinos_ENABLE_Thyra:BOOL=FALSE \
  -DTPL_BLAS_LIBRARIES:FILEPATH='/winsame/dev3/contrib-llvm_vs2017/clapack_cmake-3.2.1-ser/lib/blas.lib;/winsame/dev3/contrib-llvm_vs2017/clapack_cmake-3.2.1-ser/lib/f2c.lib' \
  -DTPL_LAPACK_LIBRARIES:FILEPATH='/winsame/dev3/contrib-llvm_vs2017/clapack_cmake-3.2.1-ser/lib/lapack.lib' \
  -DCMAKE_C_FLAGS_RELEASE:STRING='/O2 /Ob2 /DNDEBUG' \
  -DCMAKE_CXX_FLAGS_RELEASE:STRING='/O2 /Ob2 /DNDEBUG' \
  -DTrilinos_ENABLE_Teuchos:BOOL=ON \
  -DTrilinos_ENABLE_Triutils:BOOL=ON \
  -DTrilinos_ENABLE_Epetra:BOOL=ON \
  -DTrilinos_ENABLE_Amesos:BOOL=ON \
  -DTrilinos_ENABLE_Ifpack:BOOL=ON \
  -DTrilinos_ENABLE_AztecOO:BOOL=ON \
  -DTrilinos_ENABLE_ML:BOOL=ON \
  -DTrilinos_ENABLE_EpetraExt:BOOL=ON \
  -DTrilinos_ENABLE_Galeri:BOOL=ON \
  -DTrilinos_ENABLE_Shards:BOOL=ON \
  -DTrilinos_ENABLE_Intrepid:BOOL=ON \
  -DTrilinos_ENABLE_Komplex:BOOL=ON \
  -DTrilinos_ENABLE_NOX:BOOL=ON \
  -DTrilinos_ENABLE_Zoltan:BOOL=ON \
  -DTrilinos_ENABLE_Xpetra:BOOL=ON \
  -DTrilinos_ENABLE_MueLu:BOOL=ON \
  -DTeuchos_ENABLE_LONG_LONG_INT:BOOL=ON \
  -DTPL_ENABLE_BinUtils:BOOL=OFF \
  -DTPL_ENABLE_Pthread:BOOL=OFF \
  -DTPL_ENABLE_SuperLU:BOOL=ON \
  -DSuperLU_INCLUDE_DIRS:PATH='D:/winsame/dev3/contrib-llvm_vs2017/superlu-4.3-ser/include' \
  -DSuperLU_LIBRARY_DIRS:PATH='D:/winsame/dev3/contrib-llvm_vs2017/superlu-4.3-ser/lib' \
  -DSuperLU_LIBRARY_NAMES:STRING='superlu' \
  -G 'NMake Makefiles JOM' \
  D:/winsame/user/vorpalall-dev3/builds/trilinos-13.0.0

**Comment by brian-kelley** [comment]
@jhux2 I think I was using that to debug matrix-matrix add, and just forgot to remove the include. You can take it out (the code's not using backtrace now).
