### ISSUE TITLE
Sacado test  Sacado_tradoptest_59_ADC_MPI_1 failing in the continuous build

### ISSUE THREAD

**Issue by bmpersc** [trilinos/Trilinos#816]
@trilinos/sacado the  Sacado_tradoptest_59_ADC_MPI_1 is timing out on the continuous build. Looking at the output is not really helpful since all it reports is "ok."

You can view the error at:
https://testing.sandia.gov/cdash/viewTest.php?onlyfailed&buildid=2614593

**Comment by etphipp** [comment]
This happens periodically because Sacado has a large number of small tests, and there are occasionally some OS issues with that.  I wouldn't worry about it unless it fails systematically.

-Eric
