### ISSUE TITLE
EpetraExt:  Read a Symmteric Matrix in MatrixMarket Format

### ISSUE THREAD

**Issue by rezanajianasl** [trilinos/Trilinos#8160]
## Question
@trilinos/\<EpetraExt\>

I am experimenting trilinos linear solvers for large sparse unsymmetric and symmetric matrices. Using MatrixMarketFileToCrsMatrix, I can load general unsymmetric matrix, however when I try symmetric matrix the function returns error. The reason is that always 
%%MatrixMarket matrix coordinate real **general** is expected and %%MatrixMarket matrix coordinate real **symmetric** is not supported. Shall I convert my symmetric matrices to general/unsymmetric matrices and then call the function or there is a better way ?
I am concerned about the peromance of linear solvers, if relevant ?!

**Comment by mayrmt** [comment]
@trilinos/epetra @trilinos/epetraext

**Comment by jhux2** [comment]
@rezanajianasl Afaik, EpetraExt can't read MatrixMarket if the format is symmetric.  @maherou would know best.
