### ISSUE TITLE
Tpetra: How to support data types not available in the explicit template instantiations.

### ISSUE THREAD

**Issue by keitat** [trilinos/Trilinos#8165]
## Question
@trilinos/tpetra petra

In Spack, I am seeing the following Tpetra options, which are intended for explicit template instantiation.   My question is if it is possible to add any "data types" not supported by the explicit instantiations.

define('Tpetra_INST_COMPLEX_DOUBLE', complex_s),
define('Tpetra_INST_COMPLEX_FLOAT', float_s and complex_s)

**Comment by jhux2** [comment]
@keitat Do you have specific data types that you want to use?  One of the reasons for the ETI macros is because Tpetra is explicitly tested against these types.

**Comment by keitat** [comment]
> @keitat Do you have specific data types that you want to use? One of the reasons for the ETI macros is because Tpetra is tested against these types.

One of the new xSDK policy requires that the member libraries should provide some flexibilities of data types.  I think that Trilinos already follows the policy, but I am just curious with the possibility of other data types than the ETI macros defines.

**Comment by jhux2** [comment]
Afaik, Tpetra is only tested nightly with double and complex<double>.  Other @trilinos/tpetra team members (including @csiefer2) might know if apps test against other scalar types.

**Comment by kddevin** [comment]
If one compiles without explicit instantiation, one can use other scalar types.  For example, a student used a vertex label structure with Tpetra FEMultiVector to do distributed-memory label propagation in graphs.  The vertex label struct was the Scalar type, e.g., Tpetra::FEMultiVector<vertexLabelStruct>.

**Comment by kddevin** [comment]
@keitat. Is your question answered?  If not, how can we help?  If so, may I close this issue?
