### ISSUE TITLE
Belos ParameterList documentation broken

### ISSUE THREAD

**Issue by wfspotz** [trilinos/Trilinos#817]
The `ParameterList` documentation for the Belos `BlockGmresSolMgr` is not working. It is supposed to be a collapsible list of parameter descriptions, but nothing renders on the page. `ParameterList` documentation is working for Stratimikos and Domi. Locally, we can get the documentation to render correctly. On the trilinos.org site, the generated HTML and XML look OK. So we think there is some issue with dependent javascript or XML files, but Dena can't look at those.

**Comment by pbosler** [comment]
When I put this documentation into Belos, I added it to the four SolverManagers that (at the time) had correct implementations of `getValidParameters()`:  BlockCG, BlockGMRes, PseudoBlockCG, and PseudoBlockGMRes.  I've verified that these solver managers also have the same problem on the trilinos.org documentation -- their parameter lists do not expand.

I also cannot reproduce the problem locally -- I rebuilt the belos documentation today and it all works fine (except for one minor typo unrelated to this issue -- #841).   One thing that did stand out is that my locally generated doxygen for the BlockCG and PseudoBlockCG solver managers is _much_ longer and more complete than the trilinos.org doxygen for the same classes.  

This suggests that doxygen might be a good place to start digging here.  What version of Doxygen builds the trilinos.org documentation pages?  Does it use different Doxyfile* configurations than are in the repo?

**Comment by mhoemmen** [comment]
We used to use an ancient version of Doxygen for building Trilinos' online web documentation.  Is that still the case?  It got to be frustrating because Doxygen has since expanded its allowed mark-up syntax quite a bit, so the Doxygen online examples didn't match up with what Trilinos' Doxygen could accept.
