### ISSUE TITLE
MueLu: Have single proc tests run in MPI and non-MPI builds

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#8173]
## Enhancement
@cgcgcg 

Following the conversation in PR #8115, it would be good for MueLu single proc tests that ran in non-MPI (i.e. serial) builds to run in non-MPI and MPI builds.   This way, the set of tests that run in a non-MPI build will be a strict subset of the tests that run in an MPI build (and the MPI build will run a supersets of tests so just doing an MPI build should provide pretty good confidence that a non-MPI build will also pass all the MueLu tests).

The change in PR #8115 had the side-effect of removing several single proc tests in MueLu in a non-MPI build due to a change in backward compatibility addressing the issue #8110 the ripple effect that had as described in #8115.

**Comment by bartlettroscoe** [comment]
As discussed in #8115, I am going to write the function `MUELU_ADD_SERIAL_AND_MPI_TEST()` that will result in single-proc and multi-proc tests in an MPI build and just a single-proc test in a non-MPI build.  This will restore all of single-proc tests for a non-MPI build and will also add the single-proc tests for the MPI build (so the tests run in an MPI build are a strict superset of the tests run in an non-MPI build).

**Comment by jhux2** [comment]
@bartlettroscoe Thanks for fixing this.  Btw, I think other packages that MueLu would want to do this, i.e.., build with MPI but run single-process tests.  So I think it might be better to give the macro a more general name, i.e., `TRILINOS_ADD_SERIAL_AND_TEST`.

**Comment by jhux2** [comment]
@trilinos/muelu

**Comment by bartlettroscoe** [comment]
>  Btw, I think other packages that MueLu would want to do this, i.e.., build with MPI but run single-process tests.

@cgcgcg, let's start with MueLu and then we can move this to a central location in Trilinos for re-use.

Note that other packages like Ifpack2 expected just the opposite.  They were defining tests like:

```
TRIBITS_ADD_TEST(
  tif_belos
  NAME Jacobi_hb_belos
  ARGS "--xml_file=test_Jacobi_nos1_hb.xml"
  COMM serial mpi
  NUM_MPI_PROCS 1
  STANDARD_PASS_OUTPUT
)

TRIBITS_ADD_TEST(
  tif_belos
  NAME Jacobi_hb_belos
  ARGS "--xml_file=test_2_Jacobi_nos1_hb.xml"
  COMM serial mpi NUM_MPI_PROCS 2
  STANDARD_PASS_OUTPUT
)
```

and it was just the behavior of old `add_test()` that allowed the second test to get ignored in a non-MPI build because it had the same name as the first one!    But note that in their case, they are actually passing in different input files for the 1-proc vs. the many-proc case.  Therefore, they could not use the same function that MueLu would use.

Someone would need to see how many Trilinos packages would be impacted by this.  But again, this just impacts non-MPI builds, not MPI builds.  All of the same tests are still getting run in MPI bulids.

**Comment by bartlettroscoe** [comment]
@jhux2 and @cgcgcg, I am finding several tests like:

```
TRIBITS_ADD_TEST(
  Maxwell3D
  NAME "Maxwell3D-Tpetra"
  ARGS "--linAlgebra=Tpetra --reuse --xml=Maxwell.xml"
  ARGS "--linAlgebra=Tpetra --reuse --xml=Maxwell2.xml"
  COMM mpi
  NUM_MPI_PROCS 1
  )
```

that use only one MPI proc but are defined to only run with an MPI build?  Why is that?  Why can't these tests also be run with a non-MPI build?    Just curious.

**Comment by cgcgcg** [comment]
@bartlettroscoe These tests are using rebalancing, and MueLu would throw on that in serial. But I never liked that, so PR #8175.

**Comment by bartlettroscoe** [comment]
FYI: PR #8176 should address this.
