### ISSUE TITLE
Sacado: KOKKOS_INLINE_FUNCTION

### ISSUE THREAD

**Issue by frobnitzem** [trilinos/Trilinos#8174]
## Bug Report
@trilinosSacado

### Description

When compiling packages that depend on Sacado, I get build errors due to several Sacado headers that use the macro KOKKOS_INLINE_FUNCTION directly instead of SACADO_INLINE_FUNCTION.  I build Trilinos without Kokkos, and SACADO_INLINE_FUNCTION evaluates to 'inline', so this error was very confusing.

Sacado_Fad_Exp_Ops.hpp
Sacado_Fad_Ops.hpp
Sacado_mpl_for_each.hpp
Sacado_mpl_integral_nonzero_constant.hpp

### Steps to Reproduce
1. I built Trilinos using the spack spec: `trilinos@master%gcc@7.5.0~adios2~alloptpkgs+amesos~amesos2+anasazi+aztec+belos+boost~cgns~chaco~complex~debug~dtk+epetra+epetraext+exodus+explicit_template_instantiation~float+fortran+glm+gtest+hdf5+hypre+ifpack~ifpack2~intrepid~intrepid2~isorropia~kokkos+matio~mesquite+metis~minitensor+ml+mpi+muelu+mumps+netcdf~nox~openmp~phalanx~piro~pnetcdf~python+rol~rythmos+sacado~shards+shared~shylu~stk~stratimikos+suite-sparse~superlu~superlu-dist~teko~tempus+teuchos~tpetra~x11~xsdkflags~zlib+zoltan~zoltan2 build_type=RelWithDebInfo gotype=long arch=linux-ubuntu18.04-skylake`
1. I included "Sacado.hpp"
1. Sacado.hpp:82
1. Sacado_Fad_Exp_DFad.hpp:33
1. Sacado_Fad_Exp_GeneralFad.hpp:381

This file (among others) use KOKKOS_INLINE_FUNCTION directly, which crashes my build.

**Comment by etphipp** [comment]
Sorry about that.  SACADO_INLINE_FUNCTION was a recent change to insulate Sacado from changes in Kokkos, and apparently these were missed somehow (clearly there is no regular testing of Sacado without Kokkos).  This should be fixed by PR #8181

**Comment by etphipp** [comment]
PR #8181 is now merged, which should resolve this, so I'm closing this issue.  If problems still persist, please reopen.
