### ISSUE TITLE
cmake build with fetchcontent

### ISSUE THREAD

**Issue by Char-Aznable** [trilinos/Trilinos#8177]
## Question
@trilinos/framework
Is there a way to build some of the packages as dependency of my app using CMake's fetchcontent function? The motivation is to avoid the complication of managing different versions preinstalled libraries so that the users of my app don't have to know how to build and install Trilinos

**Comment by Char-Aznable** [comment]
@trilinos/framework

**Comment by jhux2** [comment]
@trilinos/framework @bartlettroscoe

**Comment by bartlettroscoe** [comment]
@Char-Aznable, I am not familiar with the [CMake FetchContent modulel](https://cmake.org/cmake/help/v3.18/module/FetchContent.html).  I don't know anyone really using [CMake ExternalProject modulel](https://cmake.org/cmake/help/v3.18/module/ExternalProject.html#module:ExternalProject) to build Trilinos.

Seems like the powers that be are pushing [Spack](https://spack.io/) but don't know if the Trilinos package there would meet your needs or not.

**Comment by Char-Aznable** [comment]
@bartlettroscoe FetchContent allows the user to set up dependency on a fetched source at config time (as opposed to build time like ExternalProject). `Kokkos` is already set up to be used with fetchcontent and I have been using Kokkos this way to allow the user to configure building my app with a host or device Kokkos parallel backend as needed. This allows the user to focus on using the dependent app without having to know how to build Kokkos with different backends. 

`Spack` is great but it takes a while to get familiar with. Practically speaking, not every user  wants to invest their time to learn how to use `Spack`. `Spack` also has its shortcoming in terms of how it propagates the compiler flags, e.g., it will rebuild the entire chain of software if you want to just add a debug flag to building Trilinos. `Spack` is also very slow on NFS.

It's not too complicated to set up to use fetchcontent. I found this minimal patch to allow Trilinos to be built from fetchcontent:
```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 97cc402c6ac..105ea02c7ea 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -63,7 +63,7 @@ CMAKE_MINIMUM_REQUIRED(VERSION 3.10.0 FATAL_ERROR)
 
 # Must set the project name as a variable at very beginning before including anything else
 # We set the project name in a separate file so CTest scripts can use it.
-INCLUDE(${CMAKE_SOURCE_DIR}/ProjectName.cmake)
+INCLUDE(${CMAKE_CURRENT_LIST_DIR}/ProjectName.cmake)
 
 # CMake requires that you declare the CMake project in the top-level file and
 # not in an include file :-(
@@ -76,7 +76,7 @@ set(ENV{CMAKE_IS_IN_CONFIGURE_MODE} 1)
 # B) Pull in the TriBITS system and execute
 #
 
-INCLUDE(${CMAKE_CURRENT_SOURCE_DIR}/cmake/tribits/TriBITS.cmake)
+INCLUDE(${CMAKE_CURRENT_LIST_DIR}/cmake/tribits/TriBITS.cmake)
```
This allows Trilinos to be added as dependency at configure time. I can then set up my cmake list like:
```
add_library(mylib INTERFACE)
target_include_directories(mylib INTERFACE "$<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR};${Trilinos_INCLUDE_DIRS};${Trilinos_TPL_INCLUDE_DIRS}>"
)
target_link_libraries(mylib INTERFACE ${Trilinos_LIBRARIES} ${Trilinos_TPL_LIBRARIES})

add_executable(myapp myapp.cpp)
target_link_libraries(myapp mylib) 

```
so that the dependency is propagated properly down the chain. I can give me details if interested.

**Comment by bartlettroscoe** [comment]
@Char-Aznable, those are minor and totally acceptable changes.  If you put in a [Pull Request](https://github.com/trilinos/Trilinos/wiki/Submitting-a-Trilinos-Pull-Request) for that small patch, I will approve it.

Note that [this upcoming refactoring](https://github.com/TriBITSPub/TriBITS/issues/299) should make this type of usage even easier since you will just be able to link to targets.

**Comment by Char-Aznable** [comment]
PR https://github.com/trilinos/Trilinos/pull/8184 submitted

The refactoring would be a big step towards this because currently the dependency transitivity of the individual package is not set up properly.
