### ISSUE TITLE
Tpetra: parallel update of sparse matrix in Kokkos kernel

### ISSUE THREAD

**Issue by Char-Aznable** [trilinos/Trilinos#8186]
## Question
@trilinos/tpetra

Does Tpetra support updating sparse matrix such as CrsMatrix in a Kokkos parallel kernel where the sparsity structure is also updated? An example usage case is to accumulate a long list of triplets `(i,j,v)` into a sparse matrix `m(i,j) = v` or `m(i,j) += v` if `m(i, j)` already exists, i.e., building a sparse 2d histogram.

**Comment by jhux2** [comment]
@trilinos/tpetra

**Comment by kyungjoo-kim** [comment]
Tpetra does not support dynamic allocation of the graph construction.
