### ISSUE TITLE
Tpetra: Benchmark performance of existing thread-parallel solver kernels

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#820]
@trilinos/tpetra 
(@jjellio, I can't assign you yet because you're not part of the Trilinos organization.  See #819.  After that's done, I'll assign you too :-) .)

Stories:
  - #822: Establish baseline by comparing performance against a reference (single-threaded CPU) implementation (solves only, not setup)
  - #823: Measure thread scaling of solver kernels (mainly OpenMP, Haswell and KNL, though other platforms are welcome), without MPI
  - #824: Same as above, but with MPI, single node
  - #825: Same as above, but with MPI, multiple nodes (modest node counts only)

"Solver kernels" include the following:
  - Sparse matrix-vector multiply
  - Vector dot products
  - Vector 2-norm
  - GEMV (Tpetra::multiply), both transpose and non-transpose cases; use a threaded BLAS (e.g., MKL with MKL_NUM_THREADS=OMP_NUM_THREADS)
  - Point Jacobi (Ifpack2::Relaxation, 1 sweep)

Where sensible, measurements should include the following levels:
  - KokkosKernels
  - Tpetra (e.g., CrsMatrix::apply)
  - Ifpack2(::Relaxation::apply)
  - Belos wrappers for vector operations (MultiVecTraits)

@jjellio has gotten a solid start on this, and has added timers already at many of the above levels.

We also have some data from a mid-2013 performance assessment, comparing solve performance of Tpetra/Belos/Ifpack2/MueLu solves (MPI only) with Epetra/AztecOO/ML solves.  I will ping @pwxy to see if he has more recent comparison data.  (@pwxy did studies after that performance assessment to track MueLu setup performance improvements.  There may be relevant data there.  This culminated in a 2014 journal paper.)

I will break this epic down into stories and tasks.  Please feel free to help out with that, especially at the task creation level.  Please tag all such issues with the Tpetra-FY17-Q2 "milestone."  Thanks all!

**Comment by jjellio** [comment]
I've worked with

https://github.com/trilinos/Trilinos/blob/master/packages/trilinoscouplings/examples/scaling/TrilinosCouplings_TpetraIntrepidPoissonExample.cpp

As-is, this scaling problem is sufficient for exercising all solvers of interest. (CG, GMRES, BiCGSTAB)

In my own fork, I have modified Belos' orthomanagers so that their Teuchos timers reflect which Ortho kernel is being used.
E.g.,
Belos: Ortho (Inner Product)
to
Belos::ICGS2: Ortho (Inner Product)

That is, Kernel_Name+OrthoPasses (ICGS2)

The timers for ortho are still very coarse. It may be more informative to modify the timers to use an array of timers, with unique timers for each multivector size. E.g., each GMRES iteration has unique ortho timers.

Another question is how to manager these modifications to Belos.  Should these types of changes be pushed to Develop as-is? Perhaps add a define to guard them?
```
Timer Name                                        MinOverProcs        MeanOverProcs       MaxOverProcs        MeanOverCallCounts     
-------------------------------------------------------------------------------------------------------------------------------------
Belos: Operation Op*x                             0.1961 (126)        0.1993 (126)        0.2014 (126)        0.001581 (126)         
Belos: Operation Prec*x                           0 (0)               0 (0)               0 (0)               0 (0)                  
Belos: PseudoBlockGmresSolMgr total solve time    2.354 (1)           2.354 (1)           2.354 (1)           2.354 (1)              
Belos::ICGS2: Ortho (Inner Product)               1.029 (248)         1.065 (248)         1.095 (248)         0.004294 (248)         
Belos::ICGS2: Ortho (Norm)                        0.01596 (125)       0.04178 (125)       0.06517 (125)       0.0003343 (125)        
Belos::ICGS2: Ortho (Update)                      0.9255 (248)        0.975 (248)         1.031 (248)         0.003931 (248)         
Belos::ICGS2: Orthogonalization                   2.101 (125)         2.105 (125)         2.109 (125)         0.01684 (125)          
Belos::MVT::MvTimesMatAddMv                       0.9328 (249)        0.9826 (249)        1.039 (249)         0.003946 (249)         
Belos::MVT::MvTransMv                             1.028 (248)         1.064 (248)         1.094 (248)         0.004291 (248)         
Build global maps                                 0.0008971 (1)       0.001029 (1)        0.00115 (1)         0.001029 (1)           
-------------------------------------------------------------------------------------------------------------------------------------
Build matrix graph: 0-Total                       0.9458 (1)          0.9462 (1)          0.9464 (1)          0.9462 (1)             
Build matrix graph: 1-Insert global indices       0.4863 (5.4e+04)    0.4992 (5.4e+04)    0.5196 (5.4e+04)    9.244e-06 (5.4e+04)    
Build matrix graph: 2-Overlapped fill complete    0.2742 (1)          0.2948 (1)          0.3078 (1)          0.2948 (1)             
Build matrix graph: 3-Owned graph export          0.04125 (1)         0.04173 (1)         0.04221 (1)         0.04173 (1)            
Build matrix graph: 4-Owned fill complete         0.1005 (1)          0.101 (1)           0.1016 (1)          0.101 (1)              
Dirichlet BC setup                                0.001485 (1)        0.001508 (1)        0.001554 (1)        0.001508 (1)           
Matrix/RHS fill:  0-Total                         1.176 (1)           1.177 (1)           1.177 (1)           1.177 (1)              
Matrix/RHS fill:  1-Element discretization        0.8754 (540)        0.8772 (540)        0.8803 (540)        0.001624 (540)         
Matrix/RHS fill:  2-Element assembly              0.1411 (540)        0.1415 (540)        0.142 (540)         0.000262 (540)         
Matrix/RHS fill:  3-Matrix export                 0.05545 (1)         0.05849 (1)         0.06021 (1)         0.05849 (1)            
-------------------------------------------------------------------------------------------------------------------------------------
Matrix/RHS fill:  4-Matrix fill complete          3.171e-05 (1)       0.001478 (1)        0.002959 (1)        0.001478 (1)           
Matrix/RHS fill:  5-RHS export                    0.000617 (1)        0.0006509 (1)       0.0006862 (1)       0.0006509 (1)          
Matrix/RHS fill:  6-Dirichlet BC assembly         0.03183 (1)         0.0331 (1)          0.03412 (1)         0.0331 (1)             
Total Assembly                                    2.832 (1)           2.833 (1)           2.833 (1)           2.833 (1)              
Total Preconditioner Setup                        7.18e-07 (1)        7.877e-07 (1)       9.29e-07 (1)        7.877e-07 (1)          
Total Solve                                       2.356 (1)           2.356 (1)           2.356 (1)           2.356 (1)              
Total Time                                        5.195 (1)           5.196 (1)           5.196 (1)           5.196 (1)              
=====================================================================================================================================
```
