### ISSUE TITLE
Panzer:  function faceGlobalId returns edge global Id

### ISSUE THREAD

**Issue by hillyuan** [trilinos/Trilinos#8201]
## Bug Report
@trilinos/\<Panzer\>

### Description
class Function STK_Interface::faceGlobalId
> return bulkData_->identifier((*orderedEdgeVector_)[lid]); 

returns edge global ID. The right one should be
> return bulkData_->identifier((*orderedFaceVector_)[lid]);

**Comment by rppawlo** [comment]
This was fixed in #9490
