### ISSUE TITLE
static analysis using PVS

### ISSUE THREAD

**Issue by davydden** [trilinos/Trilinos#821]
I did a static code analysis on Trilnos 12.8.1 with gcc 5.4.0 (build by Spack with `-DTrilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON`) using [PVS for Linux](http://www.viva64.com/en/b/0441/ ). The results are
```
Total messages: 3907
Filtered messages: 1657
```
There are certainly some false positives, but I am sure that there are also those to be fixed.
[pvs_tasks.txt](https://github.com/trilinos/Trilinos/files/586596/pvs_tasks.txt)

Keep in mind that (from http://www.viva64.com/en/m/0036/)

> It is important to understand that all files to be analyzed should be compiled. If your project actively uses code generation, then this project should be built before analysis, otherwise there may be errors during preprocessing.

Steps to reproduce
```
$ cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=On <blah-blah-blah>
$ make all -j8
$ pvs-studio-analyzer analyze -l PVS-Studio.lic -o pvs.log -j8
$ plog-converter -a GA:1,2 -t tasklist -o pvs_tasks.txt pvs.log
```

For a trial Linux license see http://www.viva64.com/en/b/0441/ .

**Comment by mhoemmen** [comment]
Thanks so much for the information! :-D

We do use some CMake-based code generation when explicit template instantiation (ETI) is enabled, in order to keep the instantiation .cpp files small and fast to build.  If ETI is not enabled, some code only gets built in tests and examples, but we could always just analyze those.

**Comment by davydden** [comment]
> If ETI is not enabled, some code only gets built in tests and examples

that's why i though having `DTrilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON` is good for analysis.

> If PVS can look into libraries, then it should thus suffice to analyze tests and examples.

most likely it can, but you would need to script it somehow or integrate with Cmake as discussed here http://www.viva64.com/en/m/0036/.
