### ISSUE TITLE
Teuchos:  Clang 10 compiler warning

### ISSUE THREAD

**Issue by nate945** [trilinos/Trilinos#8210]
## Bug Report
@trilinos/teuchos
@shardest

### Description
Using clang-10 to build Salinas from the master Sierra branch, we are getting 3095 compiler warnings related to the file Teuchos_as.hpp. This is against whatever Trilinos is currently in Sierra – not Trilinos integration, although it appears that this file has not changed in some time. There are several hundred more warnings that I have not examined; they may or may not have anything to do with Trilinos. The following is a typical example (starting at Teuchos_as.hpp:1392):

```c++
  static unsigned long long safeConvert (const double t) {
    const unsigned long long minVal = 0; // unsigned, so min value is 0.                          
    const unsigned long long maxVal = std::numeric_limits<unsigned long long>::max ();

    TEUCHOS_TEST_FOR_EXCEPTION(
      t < minVal || t > maxVal,
      std::range_error,
      "Teuchos::ValueTypeConversionTraits<unsigned long long, double>::safeConvert: "
      "Input double t = " << t << " is out of the valid range [" << minVal
      << ", " << maxVal << "] for conversion to unsigned long long.");

    return static_cast<unsigned long long> (t);
  }
```

```
Teuchos_as.hpp:1396:55: warning: implicit conversion from 'const unsigned long long' to 'double' changes value from 18446744073709551615 to 18446744073709551616 [-Wimplicit-int-float-conversion]
```

It appears to be implicitly casting maxVal to a double for the comparison against t, which is bad. I would think we’d want both values to be explicitly the type with larger range before doing a comparison. There are many related functions in this file with the same issue. I’m surprised that there isn’t yet some kind of STL function that does this?

**Comment by jhux2** [comment]
@trilinos/teuchos

**Comment by nate945** [comment]
Adding additional information from @shardest in an email chain:
-----------------
You can also simply compile the attached program with clang-10 – I think it is a good model of both the warning behavior and the original program:

clang++ -o warn_me warn_me.cpp 

warn_me.cpp:8:27: warning: implicit conversion from 'const unsigned long long' to 'double' changes value from 18446744073709551615 to 18446744073709551616 [-Wimplicit-int-float-conversion]
    if (t < minVal || t > maxVal) {
                        ~ ^~~~~~
1 warning generated.

The program is adapted from the function referenced in my previous e-mail. It looks like the intent is to check for overflow – not roundoff, which is to be expected. The first integer that can’t be represented by double-precision float is 2^53+1. By the time we get to doubles in the vicinity of 2^64, we are missing a bunch of digits on the end, so it’s a little hazy what should happen. However, I expected this program as written to either throw or return a large integer. In fact, it returns zero because:

•	2^64-1 becomes 2^64 when cast to double
•	2^64 is exactly representable as double

Thus, t == maxVal, so it doesn’t throw, but the conversion overflows. I didn’t make any effort to enable floating point exceptions, which I presume would have caught this, but it seems that the point of the function called “safeConvert” is to preclude this possibility.

    Sean


-------warn_me.cpp-------------
#include <limits>
#include <iostream>

unsigned long long safeConvert (const double t) {
    const unsigned long long minVal = 0; // unsigned, so min value is 0.
    const unsigned long long maxVal = std::numeric_limits<unsigned long long>::max ();
 
    if (t < minVal || t > maxVal) {
        throw std::range_error("double to long long conversion out of bounds");
    }
 
    return static_cast<unsigned long long> (t);
}

int main(void) {
    // 2^53 = 9007199254740992 = 9.007199254740992e15
    // 2^64 = 18446744073709551616 = 1.8446744073709551616e19

    // 2^53 is still representable as double
    std::cout << safeConvert(9007199254740992.0) << std::endl;

    // 2^53 + 1 is not
    std::cout << safeConvert(9007199254740993.0) << std::endl;

    // 2^64
    std::cout << safeConvert(1.8446744073709551616e19) << std::endl;

    return 0;
}

**Comment by mwglass** [comment]
Any idea when we can expect to have this fixed?

**Comment by bartlettroscoe** [comment]
> Any idea when we can expect to have this fixed?

@mwglass, I think I can fix this but  I would need a funding source to support this work since I think this fall out of the scope of any current support that I have.  We should talk offline.

**Comment by jwillenbring** [comment]
@prwolfe Is going to take a look at this. 

@nate945 Is there a set of flags we could try to add to our clang 10 build for warnings as errors that would help us stay more in front of these issues?

**Comment by nate945** [comment]
@jwillenbring at least for clang 10 the warning seems to be on by default.  It looks like it is also associated with the flag -Wimplicit-int-float-conversion which could be put in gcc or clang.  It seems to me the default clang behavior is only to warn when an implicit float to conversion definitely changes the numerical value.  I'd guess the only time this occurs is when trying to convert numeric max ints to floats.  However, putting in the compiler flag itself may also warn anytime there is there is any implicit float to int conversion, which may be an excessive number of warnings, I'm not sure.

**Comment by jwillenbring** [comment]
@nate945 Thanks. I see this may not be so simple.

**Comment by nate945** [comment]
I think this particular warning could be avoided by making the conversion explicit in the function and the behavior would be unchanged.  Though the warning seems legitimate in that the code in question could maybe behave unexpectedly for certain huge ints.  I guess it is problematic that there are some ints that can't be represented exactly as a float, and a lot of floats that can't be represented exactly as an int, so neither type is can be said to have the uniquely larger range.

**Comment by prwolfe** [comment]
I am adding static_casts where appropriate in these functions. I had no problem re-creating the warnings using our PR testing system. I was able to silence the warnings using -Wno-implicit-int-float-conversion, but that could potentially hide problems where this is not expected.

**Comment by jwillenbring** [comment]
Since Paul's PR is in, I will close this ticket and and new one can be filed to address additional warning issues.
