### ISSUE TITLE
Belos: SolverFactory says GMRES not registered

### ISSUE THREAD

**Issue by brian-kelley** [trilinos/Trilinos#8213]
## Question
@trilinos/belos 

I have some old code I'm trying to get up to date. It does a preconditioned solve with a Tpetra::CrsMatrix, a Tpetra::Operator (the MueLu preconditioner) and Tpetra::MultiVectors lhs and rhs:
```
    auto problem = rcp(new Belos::LinearProblem<Scalar, Tpetra_MultiVector, Tpetra_Operator>(matrix, lhs, rhs));
    problem->setRightPrec(prec);
    bool set = problem->setProblem();
    TEUCHOS_TEST_FOR_EXCEPTION(!set, runtime_error, "Linear Problem failed to set up correctly!");
    Belos::TpetraSolverFactory<Scalar, Tpetra_MultiVector, Tpetra_Operator> factory;
    string solverName = params->get("solver", "GMRES");
    RCP<Belos::SolverManager<Scalar, Tpetra_MultiVector, Tpetra_Operator>> solver = factory.create(solverName, params);
    solver->setProblem(problem);
    Belos::ReturnType ret = solver->solve();
```
solverName is "GMRES". 

The Scalar, LO, GO and Node types all match across these typedefs. This particular build is just (double, int, int, Serial) with MPI disabled, and that's what Scalar/LO/GO/Node are.

I saw an issue with the same error message (#6370) but that seemed to be caused by the template parameters not matching ETI'd types. My error output is:
```
1: Error occurred while running Belos solver:
1: /ascldap/users/bmkelle/MueMex/Trilinos/packages/belos/src/BelosSolverFactory.hpp:375:
1: 
1: Throw number = 1
1: 
1: Throw test that evaluated to true: it == get_solverManagers().end()
1: 
1: Belos solver manager GMRES with standardized name PSEUDOBLOCK GMRES has not been registered.
```
Could someone tell me what's wrong, or point me to an example of doing a solve with Tpetra objects?

**Comment by jennloe** [comment]
@brian-kelley I touched some of this code recently in PR #8021 
I don't think those changes should have caused your issues, but you might double-check?

**Comment by dridzal** [comment]
@brian-kelley , this looks like the MueMex error I was having.  CCing @hkthorn .

**Comment by brian-kelley** [comment]
@dridzal That's exactly what I'm working on (this is the last MueMex issue I'm seeing in the tests, so once the Belos solve works I can push it in)

**Comment by cgcgcg** [comment]
@brian-kelley You could try calling `Belos::Tpetra::Details::Tpetra::registerSolverFactory()`. Not sure if that's the issue here..

**Comment by brian-kelley** [comment]
@cgcgcg I did try
```
      BelosTpetra::Impl::register_Cg (verbose);
      BelosTpetra::Impl::register_CgPipeline (verbose);
      BelosTpetra::Impl::register_CgSingleReduce (verbose);
      BelosTpetra::Impl::register_Gmres (verbose);
      BelosTpetra::Impl::register_GmresS (verbose);
      BelosTpetra::Impl::register_GmresSstep (verbose);
      BelosTpetra::Impl::register_GmresSingleReduce (verbose);
```
like MueLu driver does but still got the same error. I will also try what you suggested. I'm hoping there is an intended way that doesn't require registering each individual solver, or using stuff in Details:: or Impl::, but I'll take whatever works

**Comment by cgcgcg** [comment]
Have you tried calling `BelosTpetra::Impl::register_PseudoBlockGmres (verbose);`?

**Comment by brian-kelley** [comment]
@jennloe I doubt this has anything to do with your recent changes since this code hasn't been touched for several years old.

**Comment by iyamazaki** [comment]
I think "TPETRA GMRES" is from BelosTpetra, but not "GMRES". Also, we shouldn't have to explicitly register these solvers anymore.. Please let me know if the issue is from the Tpetra solvers.

**Comment by brian-kelley** [comment]
@iyamazaki I still got:
```
Error occurred while running Belos solver:
/ascldap/users/bmkelle/MueMex/Trilinos/packages/belos/src/BelosSolverFactory.hpp:375:

Throw number = 1

Throw test that evaluated to true: it == get_solverManagers().end()

Belos solver manager TPETRA GMRES with standardized name TPETRA GMRES has not been registered.
```

**Comment by jhux2** [comment]
@brian-kelley Can you print the valid list of managers that are registered?

**Comment by brian-kelley** [comment]
@jhux2 The map of solver names to SolverManagers is empty:
```
BMK: all registered factory names:
***
//they would be listed here
***
```

**Comment by brian-kelley** [comment]
I still don't know what's going on with this - I printed out the Scalar/MV/Operator types when Tpetra SolveManagers get registered, and it looks like it should be registered. It's like it disappears from the list before I try to create a solver. In the end I just bypassed the factory and created a PseudoBlockGmres/PseudoBlockCG solver directly, and that's working.

If anyone sees this and finds the answer, please post what you did :)
