### ISSUE TITLE
FEI:  Segfaults with clang compiler

### ISSUE THREAD

**Issue by mwglass** [trilinos/Trilinos#8241]
## Bug Report
@trilinos/\<fei\>

### Description
For Sierra, we are now building/testing with clang compilers (v10) since there are now many compilers moving toward the clang/llvm framework (Cray, Intel, ARMHPC, IBM, etc). We had previously identified a bug in

EqnCommMgr::mirrorProcEqns() in packages/fei/base/fei_EqnCommMgr.cpp

with the ARMHPC compilers on stria. A workaround was put in place to de-optimize that function when compiling with the ARMHPC compilers. With our clang-10 testing, we now see that this issue is present here too. We would like to have this fixed to work with an optimized build with clang compilers.

**Comment by rppawlo** [comment]
@alanw0

**Comment by jhux2** [comment]
@trilinos/fei

**Comment by alanw0** [comment]
@mwglass Can you point me to the sierra test that is hitting the bug?
Regarding FEI, Sierra is the last known user, and perhaps it is time to pull the code from Trilinos and let it only exist in Sierra.

**Comment by mwglass** [comment]
@alanw0 almost all of the adagio test failures on the dashboard for the clang10 build/test is related to this. For ARMHPC we put in:

 #ifdef __ARM_HPC_COMPILER_VERSION__
 __attribute__((optnone))
 #endif
 int EqnCommMgr::mirrorProcEqns(ProcEqns& inProcEqns, ProcEqns& outProcEqns)

If your recommendation is to have us deprecate FEI (TF is already doing this) then just extending this fix to be something like the following would be OK:

 #if defined( __clang__) && !defined(__INTEL_CLANG_COMPILER)
 __attribute__((optnone))
 #endif
 int EqnCommMgr::mirrorProcEqns(ProcEqns& inProcEqns, ProcEqns& outProcEqns)

**Comment by mwglass** [comment]
@alanw0 Is there a timeframe for getting this work around in place?

**Comment by alanw0** [comment]
Sorry @mwglass, got swamped with other stuff... I'll try to get an fei pull-request in this afternoon.

**Comment by alanw0** [comment]
@mwglass are you pretty confident that the ifdef you show above will do it? If so, I can just put that in quickly.
Otherwise, I need to get into stria and build/test, which will take longer.

**Comment by mwglass** [comment]
Yes, I already patched out current version of Trilinos with this fix but want to make sure it gets into Trilinos itself for future integrations.

**Comment by alanw0** [comment]
ok great.

**Comment by alanw0** [comment]
The fix for this has been merged, #8263
