### ISSUE TITLE
Tempus: Remove ParameterList from Internals of TimeStepControl

### ISSUE THREAD

**Issue by ccober6** [trilinos/Trilinos#8246]
## Enhancement
@trilinos/tempus 

Remove all the internal uses of ParameterList from TimeStepControl.  This means moving the variables in the TimeStepControl ParameterList to member data.  TimeStepControl will not longer inherit from Teuchos::ParameterListAcceptor.  However TimeStepcontrol can still be built from a ParameterList, and will still provide a valid ParameterList.

This is in support of improving the data flow transparency for the Tempus PLATR deliverables.

**Comment by ccober6** [comment]
@sconde I am also thinking about switching 

`  Teuchos::RCP<TimeStepControlStrategyComposite<Scalar>> stepControlStrategy_;`
to
`  Teuchos::RCP<TimeStepControlStrategy<Scalar>> stepControlStrategy_;
`
and remove composite aspect from the TimeStepControl internals.  Do you see any issues in Drekar or EMPIRE in doing this?

**Comment by sconde** [comment]
> Do you see any issues in Drekar or EMPIRE in doing this?

I don't so. I believe we just pass everything in as `TimeStepControlStrategy`
