### ISSUE TITLE
Test Piro_EpetraSolver_MPI_4

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#826]
**CC:** @trilinos/framework, @agsalin 

**Description:**

The test `Piro_EpetraSolver_MPI_4` has been failing in CI test for all recorded history as shown by:

* * http://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&date=&limit=200&filtercount=3&showfilters=1&limit=200&filtercombine=and&field1=testname/string&compare1=61&value1=Piro_EpetraSolver_MPI_4&field2=buildname/string&compare2=61&value2=Linux-GCC-4.7.2-CONTINUOUS_MPI_OPT_DEV_SHARED&field3=buildstarttime/date&compare3=84&value3=2016-11-12

which currently is only going back to 9/20.  Yes, this test has been failing non-stop in CI testing for almost 2 full months!

**Comment by bartlettroscoe** [comment]
This failing test is a blocker for #482 so I will disable it for the checkin-test.py script until it can be fixed.

**Comment by rppawlo** [comment]
Disabled the epetra test completely and reverted Ross's original commit. The wrong vector space is being used. This looks like an issue in constructing the MV data structure for Dg/Dp.

**Comment by bartlettroscoe** [comment]
This is ready to close, right?

**Comment by william76** [comment]
@rppawlo 	

Has this ever been fixed?  The `Piro_EpetraSolver_MPI_4_DISABLE ON` setting is still set up in testing -- just checking if it'd be safe to remove that guard or if that test is still considered failing?
