### ISSUE TITLE
MueLu: remove dependency on UVM

### ISSUE THREAD

**Issue by jhux2** [trilinos/Trilinos#8265]
## Enhancement
@trilinos/muelu 

The Trilinos team has decided to remove internal dependencies on UVM.

This is a meta-issue for MueLu, please link UVM-related PRs/issues back to this one.

**Comment by jhux2** [comment]
better handled at the Trilinos level.

**Comment by cgcgcg** [comment]
Can this be closed?

**Comment by jhux2** [comment]
Closing as fixed.
