### ISSUE TITLE
Ifpack2: remove dependency on UVM

### ISSUE THREAD

**Issue by jhux2** [trilinos/Trilinos#8266]
## Enhancement
@trilinos/ifpack2 

The Trilinos team has decided to remove internal dependencies on UVM.

This is a meta-issue for Ifpack2, please link UVM-related PRs/issues back to this one.

**Comment by jhux2** [comment]
better handled at the Trilinos level.

**Comment by csiefer2** [comment]
0/46 Ifpack2 tests pass without UVM as of 12/4/20.

**Comment by csiefer2** [comment]
Looks like we're working.  Sticking a fork in this.

**Comment by jhux2** [comment]
Passing dashboard results:  https://testing.sandia.gov/cdash/index.php?project=Trilinos&subproject=Ifpack2&filtercount=1&showfilters=1&field1=buildname&compare1=63&value1=NO_UVM
