### ISSUE TITLE
Domi not under any automated testing and fail a bunch of tests in new targeted CI build

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#828]
**CC:** @trilinos/framework, @wfspotz 

**Description:**

The package Domi is being used (or at least is being configured) by at least one important Trilinos customer and is therefore slated to be included in the new set of Primary Tested (PT) packages (see #410 and #482).  However, Domin is not currently under any automated testing as shown yesterday:

* http://testing.sandia.gov/cdash/index.php?project=Trilinos&date=2016-11-10&subproject=Domi

And when I tried to enable it for the new CI build, I got a bunch of failing tests:

```
85% tests passed, 19 tests failed out of 125

Label Time Summary:
Domi    = 157.49 sec (125 tests)

Total Test time (real) =  22.43 sec

The following tests FAILED:
	 27 - Domi_MDMap_UnitTests_1D_1_MPI_1 (Failed)
	 28 - Domi_MDMap_UnitTests_1D_2_MPI_2 (Failed)
	 29 - Domi_MDMap_UnitTests_1D_4_MPI_4 (Failed)
	 30 - Domi_MDMap_UnitTests_2D_1_1_MPI_1 (Failed)
	 31 - Domi_MDMap_UnitTests_2D_1_2_MPI_2 (Failed)
	 32 - Domi_MDMap_UnitTests_2D_2_1_MPI_2 (Failed)
	 33 - Domi_MDMap_UnitTests_2D_1_4_MPI_4 (Failed)
	 34 - Domi_MDMap_UnitTests_2D_2_2_MPI_4 (Failed)
	 35 - Domi_MDMap_UnitTests_2D_4_1_MPI_4 (Failed)
	 36 - Domi_MDMap_UnitTests_3D_1_1_1_MPI_1 (Failed)
	 37 - Domi_MDMap_UnitTests_3D_1_1_2_MPI_2 (Failed)
	 38 - Domi_MDMap_UnitTests_3D_1_2_1_MPI_2 (Failed)
	 39 - Domi_MDMap_UnitTests_3D_2_1_1_MPI_2 (Failed)
	 40 - Domi_MDMap_UnitTests_3D_1_1_4_MPI_4 (Failed)
	 41 - Domi_MDMap_UnitTests_3D_1_2_2_MPI_4 (Failed)
	 42 - Domi_MDMap_UnitTests_3D_1_4_1_MPI_4 (Failed)
	 43 - Domi_MDMap_UnitTests_3D_2_1_2_MPI_4 (Failed)
	 44 - Domi_MDMap_UnitTests_3D_2_2_1_MPI_4 (Failed)
	 45 - Domi_MDMap_UnitTests_3D_4_1_1_MPI_4 (Failed)
```

Details are archived to the Experimental dashboard:

* http://testing.sandia.gov/cdash/index.php?display=project&project=Trilinos&parentid=2615560

**Comment by bartlettroscoe** [comment]
@wfspotz, for now I can either leave Domi out of the set of PT package or can disable all of these failing tests in the CI build for now.  The advantage of disabling these tests for CI testing is that we still build Domi in CI testing and run the other 85% of the passing tests.

Let me know what you want me to do.

**Comment by wfspotz** [comment]
I will see if I can replicate it and get back to you.

**Comment by wfspotz** [comment]
I was able to replicate this by turning Teuchos debugging on. I think I have a bead on where the problem is. I estimate it should be a quick fix.

**Comment by wfspotz** [comment]
Should be fixed now.

**Comment by bartlettroscoe** [comment]
I tested this out the fixing commit:

```
commit 5fa14318b20f77cc604418ef9a620b277fc01614
Author: Bill Spotz <wfspotz@sandia.gov>
Date:   Fri Nov 11 18:53:54 2016 -0700

    Domi: Fix bug in MDMap::getAugmentedMDMap
    
    The getAugmentedMDMap method did not properly update the
    _replicatedBoundary data member. It does now.

M       packages/domi/src/Domi_MDMap.hpp
```

locally and it seems to have fixed the failures.

Thanks for fixing this so quickly!
