### ISSUE TITLE
KokkosKernels: Failed to compile spGEMM_cuSPARSE due to deprecated cusparseXcsrgemmNnz with CUDA 11

### ISSUE THREAD

**Issue by sserita** [trilinos/Trilinos#8281]
## Bug Report
@trilinos/kokkos

### Description
Failure to compile with -D TPL_ENABLE_CUSPARSE:BOOL=ON with CUDA 11.0.3.

The key error message is

```
[  4%] Building CXX object packages/kokkos-kernels/src/CMakeFiles/kokkoskernels.dir/impl/generated_specializations_cpp/spgemm_symbolic/Sparse_spgemm_symbolic_eti_DOUBLE_ORDINAL_INT_OFFSET_INT_LAYOUTLEFT_EXECSPACE_CUDA_MEMSPACE_CUDASPACE_MEMSPACE_CUDASPACE.cpp.o
/home-emu/sserita/repos/Trilinos/packages/kokkos-kernels/src/sparse/impl/KokkosSparse_spgemm_cuSPARSE_impl.hpp(114): error: identifier "cusparseXcsrgemmNnz" is undefined
```

Checking `$CUDA_ROOT/include/cusparse.h` shows that `cusparseXcsrgemm2Nnz` is still available (which is the generalized form of `cusparseXcsrgemmNnz`). Documentation shows that `cusparseXcsrgemmNnz` was going to be deprecated with CUDA 11.
https://docs.nvidia.com/cuda/archive/10.2/cusparse/index.html#csrgemm

However, `cusparseXcsrgemm2Nnz` is also listed as deprecated in favor of `cusparseSpGEMM` for the next major release (CUDA 12), so may be worth jumping directly to this for future proofing: https://docs.nvidia.com/cuda/cusparse/index.html#csrgemm2

### Steps to Reproduce
This was run on the Kahuna HPDA cluster, which has access to SEMS TPL modules.
I attempted to make the environment as reproducible as possible by using personal modules for non-SEMS TPLs.
My hope is just sourcing `env.ampere` will be enough to get my environment when on the cluster.
`.txt` endings were added to the scripts for uploading.

1. SHA1:  4fc95b925454ddc4b6b3dbbc0efed2a39aa6777a
1. Configure script:  [do-cmake-trilinos-ampere.txt](https://github.com/trilinos/Trilinos/files/5460552/do-cmake-trilinos-ampere.txt)
1. Environment script: [env.ampere.txt](https://github.com/trilinos/Trilinos/files/5460561/env.ampere.txt)
1. NVCC wrapper script: [nvcc_wrapper_ampere.txt](https://github.com/trilinos/Trilinos/files/5460562/nvcc_wrapper_ampere.txt)
1. Configure log:  [cmake.log](https://github.com/trilinos/Trilinos/files/5460546/cmake.log)
1. Partial build log: [make.log](https://github.com/trilinos/Trilinos/files/5460548/make.log)

**Comment by cgcgcg** [comment]
@trilinos/kokkos-kernels

**Comment by brian-kelley** [comment]
A workaround for this was added in the KokkosKernels 3.3.0 snapshot.

**Comment by sebrowne** [comment]
What was the workaround?  We (Sierra) just hit this as a hard compile failure with CUDA 11.2.0.  I checked the CMakeCache and it has the TPL_CUSPARSE_INCLUDE_DIRS and TPL_CUSPARSE_LIBRARIES variables set correctly to the include dir of my CUDA installation, and libcusparse.so located in said installation.

**Comment by brian-kelley** [comment]
@sebrowne The workaround was just:

```
#if defined(CUSPARSE_VERSION) && (11000 <= CUSPARSE_VERSION)
      throw std::runtime_error ("SpGEMM cuSPARSE backend is not yet supported for this CUDA version\n");
#else
     //actually call it, with the old interface cusparseXcsrgemmNnz etc.
#endif
```
so the call to cusparseXcsrgemmNnz isn't supposed to get compiled for CUSPARSE 11 and up. At first look this looks to be correct. I checked the CUSPARSE_VERSION values for CUDA 10.2.89 (< 11000, and it has cusparseXcsrgemmNnz) and 11.0.2 (>= 11000, and doesn't have cusparseXcsrgemmNnz). Higher versions of CUDA 11 like yours would be the same.

You could show the CUSPARSE version at compile time, before being stopped by the error:
```
#define XSTR(x) STR(x)
#define STR(x) #x
#pragma message "CUSPARSE_VERSION = " XSTR(A)
```
