### ISSUE TITLE
Problem with Adelus when building Trilinos

### ISSUE THREAD

**Issue by faconcha** [trilinos/Trilinos#8299]
Hello,

I am trying to install Trilinos in Mac. First, I have configured installation by means of:

`cmake -DTPL_ENABLE_MPI=ON \
-DMPI_BASE_DIR=/usr/local/opt/open-mpi \
-DTrilinos_ENABLE_ALL_PACKAGES=ON \
-DTrilinos_ENABLE_TESTS=OFF \
-DBUILD_SHARED_LIBS=ON \
-DCMAKE_INSTALL_PREFIX= $HOME/install/Trilinos \
-DBoost_INCLUDE_DIRS=/usr/local/opt/boost/include \
-DTPL_ENABLE_Netcdf=OFF \
-DTrilinos_ENABLE_PyTrilinos=OFF \
-DTrilinos_ENABLE_STK=OFF ..`

Then, when I do `make -j4 install`, installation goes well until I get the following error:

`[ 46%] Linking CXX shared library libzadelus.dylib`
`Undefined symbols for architecture x86_64:`
  `"Adelus::nprocs_col", referenced from:`
    `  Adelus::initcomm() in Adelus_pcomm.cpp.o`
  `"Adelus::nprocs_row", referenced from:`
    `  Adelus::initcomm() in Adelus_pcomm.cpp.o`
  `"Adelus::me", referenced from:`
    `  Adelus::initcomm() in Adelus_pcomm.cpp.o`
`ld: symbol(s) not found for architecture x86_64`
`clang: error: linker command failed with exit code 1 (use -v to see invocation)`
`make[2]: *** [packages/adelus/src/libzadelus.13.1.dylib] Error 1`
`make[1]: *** [packages/adelus/src/CMakeFiles/zadelus.dir/all] Error 2`

Can anybody help me to fix this error to successfully install trilinos in my Mac? Please be as clear as possible because I am a newby in the world of C++ and compilers. Thank you!

**Comment by jhux2** [comment]
@vqd8a @srajama1

**Comment by rsiva-web** [comment]
@faconcha : Is this what you really want ? You are trying to install every Trilinos package on a laptop. What is your use case ?

**Comment by faconcha** [comment]
@rsiva-web yes, I need Trilinos for my laptop. Trilinos constitutes a third party library for an in-house code used by the research lab I am joining. So, even though they have a server for the real applications, everybody has the complete code in their laptops for practical purposes and fast code testing. Could you help me with this? I would really appreciate that!
