### ISSUE TITLE
TRILINOS_UNUSED_FUNCTION Doesn't work on windows with intel

### ISSUE THREAD

**Issue by bmpersc** [trilinos/Trilinos#83]
This looks like an issue with the intel compiler on windows. It seems that Tpetra has run into this before as the same logic for setting TRILINOS_UNUSED_FUNCTION was checking for windows and not setting TRILINOS_UNUSED_FUNCTION to __unused__ in that case. I have attached a patch that should fix this issue. I have two questions though, is this an acceptable solution? And Why is this logic in 3 places in Trilinos(1 in Teuchos and 2 in Tpetra)?

@mhoemmen 
[0001-Teuchos-Fix-compile-issue-on-windows-with-intel.patch.txt](https://github.com/trilinos/Trilinos/files/96309/0001-Teuchos-Fix-compile-issue-on-windows-with-intel.patch.txt)

**Comment by mhoemmen** [comment]
Hi Brent!  The change looks good to me.  I think the macro in question was my doing, a while back.  There was a push to build warning-free, and only Clang was warning about unused functions.  Given that Tpetra depends on Teuchos, it would make sense to consolidate this logic in Teuchos.

**Comment by mhoemmen** [comment]
Issue #86 covers Brent's request to consolidate the logic for defining this macro in one place.

**Comment by dicengine** [comment]
Thanks Brent and Mark! I've verified that the patch above fixes the problem for Intel 15 on Windows.

**Comment by bmpersc** [comment]
I pushed the patch earlier today to both master and the 12.6 branch. If you are still seeing issues please re-open this issue.

**Comment by mhoemmen** [comment]
Thanks Brent! :-D
