### ISSUE TITLE
Framework:  Standup CUDA 11 build

### ISSUE THREAD

**Issue by jwillenbring** [trilinos/Trilinos#8328]
## Enhancement
@trilinos/framework 
@srajama1 
@cgcgcg 
@lucbv 
@brian-kelley 
@mwglass 

We need to stand up a CUDA 11 nightly build for Trilinos. I am CC'ing relevant parties, including people who have worked with CUDA 11 already. We need to identify a platform where we can do this and specific Trilinos configuration options to use.

**Comment by jwillenbring** [comment]
Per @crtrott CUDA 11 is required for us to move to C++17.

**Comment by jwillenbring** [comment]
@fryeguy52 agreed to help us look at standing up a CUDA 11 build.

**Comment by wadeburgess** [comment]
Migrated to new Jira Help Desk and Jira project, so closing now.
