### ISSUE TITLE
Xpetra: build error when #include "Xpetra_StridedMap.hpp"

### ISSUE THREAD

**Issue by mayrmt** [trilinos/Trilinos#8332]
## Question
@trilinos/xpetra 

In the `Xpetra` package, in particular in the file `packages/xpetra/src/Utils/Xpetra_MapUtils.hpp`, I'd like to include the header file of the `StridedMap`. However, I end up with build errors like this one:
```
In file included from /ssd/codes/mayrmt_trilinos/src-trilinos/packages/xpetra/src/BlockedCrsMatrix/Xpetra_MapExtractor_decl.hpp:60:0,
                 from /ssd/codes/mayrmt_trilinos/src-trilinos/packages/xpetra/src/BlockedCrsMatrix/Xpetra_MapExtractor_def.hpp:53,
                 from packages/xpetra/src/Utils/ExplicitInstantiation/Xpetra_MapExtractor.cpp:55:
/ssd/codes/mayrmt_trilinos/src-trilinos/packages/xpetra/src/Utils/Xpetra_MapUtils.hpp:53:33: fatal error: Xpetra_StridedMap.hpp: No such file or directory
compilation terminated.
[54/972] Building CXX object packages/muelu/adapters/CMakeFiles/muelu-adapters.dir/ExplicitInstantiation/MueLu_RefMaxwell.cpp.o
ninja: build stopped: subcommand failed.
```
Obviously, the header file cannot be found. Why? 

Of course, there are other examples, where the header can be found, e.g.:

- Within the Xpetra test directory, this usually happens via
```
#include "Xpetra_StridedMap.hpp"
```
- Within MueLu, this usually happens via
```
#include <Xpetra_StridedMap.hpp>
```

Am I missing a configure option? Is there something with ETI going wrong?

If useful, I can provide a branch that reproduces that error. Just let me know!

## Context and Motivation

I have an application, where I work with `StridedMap` objects and also often apply `Xpetra::MapUtils::concatenateMaps()`. The latter works only for non-`StridedMap`s, but doesn't check for that. In order to add the check, I'd need to include the `Xpetra_StridedMap.hpp` in `packages/xpetra/src/Utils/Xpetra_MapUtils.hpp`.

**Comment by mayrmt** [comment]
Not sure if relevant, but maybe:

- ETI for `StridedMap` has been implemented in PR #5889 by @william76 
- ETI for `StridedMapFactory` has been implemented in PR #5900 by @william76

**Comment by tawiesn** [comment]
Hi @mayrmt! I don't really think that it is an ETI issue. I think the problem is, that the `StridedMap` class lives in `packages/xpetra/sup`, the "supplementary" code package (linked into the xpetra-sup library), whereas `Xpetra_MapUtils.hpp` lives in `packages/xpetra/src` and is part of the main xpetra library. The xpetra-sup library depends on the xpetra library. Therefore, the only reasonable solution would be, to move your code into a separate utils class (e.g. Xpetra_StridedMapUtils.hpp) within the sup package or - the other way around - move the StridedMap class functionality into main xpetra. Does that make sense?

**Comment by mayrmt** [comment]
@tawiesn yeah, that sounds reasonable. I did realize that they live in separate directories and I saw the two libraries `xpetra` and `Xperia-Sup`, but I wasn't aware of the implications.

**Comment by mayrmt** [comment]
@trilinos/xpetra What's the actual reasoning behind this separation into two libraries? Purely historic or anything, that's also fundamental as of today, where especially `Matrix`, but also `StridedMap` from the `xpetra-sup` library are used all over MueLu (and other codes, for example)?

**Comment by mayrmt** [comment]
I've put out the draft PR #8334 to see, if moving `StridedMap` to the main `xpetra` library has some weird side effects in any of the tested configurations. Not sure yet, if this route is worth to pursue, but a little investigation certainly does not hurt that much...
