### ISSUE TITLE
Tpetra: parallel error that cropped up with system upgrade (Fedora 32->33, openmp 3 -> openmpi 4) for Albany/LCM

### ISSUE THREAD

**Issue by ikalash** [trilinos/Trilinos#8336]
Two of our Albany/LCM nightlies run on a set of machines that were upgraded to Fedora 33 from Fedora 32 yesterday.  With the upgrade, some test failures cropped up with the following error in Tpetra: 

```
p=1: *** Caught standard std::exception of type 'std::logic_error' :

 /home/lcm/LCM/Trilinos/packages/tpetra/core/src/Tpetra_DirectoryImpl_def.hpp:877:
 
 Throw number = 1
 
 Throw test that evaluated to true: curLID == LINVALID
 
 Tpetra::Details::DistributedNoncontiguousDirectory<int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > constructor: Incoming global index 0 does not have a corresponding local index in the Directory Map.  Please report this bug to the Tpetra developers.
```
(e.g. https://sems-cdash-son.sandia.gov/cdash/testDetails.php?test=624418&build=8681 on our dashboard).  This happens in our gcc/10.2.0 and clang/11.0.0 builds.  None of these compilers changed in the upgrade, but some of the TPLs did, which could be affecting this.  We were hoping someone from the Trilinos side might point us in the right direction in terms of looking into the problem.  It occurs in parallel only, not serial.  I am also wondering if perhaps this is a genuine Trilinos bug that shows up only on some platforms. 

Tagging @lxmota , who owns the nightlies where the errors are showing up.

@trilinos/tpetra

**Comment by ikalash** [comment]
Just to follow up on this issue: I have found the cause, and it is openmpi 4.  The machines that got upgraded were switched to openmpi 4, which was causing the failures.  As a workaround, I installed an older version of openmpi (3.1.6) and the issue went away.  Does Trilinos currently support openmpi 4?  I suspect that the problems we encountered are real bugs in the code that are showing up with openmpi 4, perhaps due to a change in the standards.  Since I don't particularly want to be the guinea pig right now, as a workaround I am switching our nightly tests to use openmpi 3; but I wanted to let the Trilinos team know of the problem, since it will likely come up sooner or later when more platforms start using openmpi 4.

**Comment by csiefer2** [comment]
Trilinos is tested with OpenMPI 4.0.3 on several systems as part of the nightly testing.

**Comment by ikalash** [comment]
@csiefer2: This was with openmpi 4.0.4.  Could that be the difference?  I did not try running Trilinos tests but I could.  I suppose Tpetra would be the ones to try first - any other packages you think are worth testing?

Tagging @jewatkins as we were just talking about this.  Jerry, I'm guessing you haven't tried running the code with openmpi 4.0.4?

**Comment by jewatkins** [comment]
I haven't tried openmpi 4.0.4, only gcc 8.3.0/openmpi 4.0.2. I don't see any modules with 4.0.4 so I think you might be the first to try.

**Comment by ikalash** [comment]
@jewatkins: Thanks for weighing in.  That would be my guess.  I suppose I could try to install openmpi 4.0.3 and see what happens with that.  Not sure if I want to go that far at this point...

**Comment by ikalash** [comment]
@csiefer2 : to answer your question, yes, I do find that some Trilinos tests fail.  I enabled Tpetra, Ifpack2, Ifpack, ML, MueLu, AztecOO, Belos and Tempus tests in my Trilinos build.  Here is the list of failures/timeouts:

```
The following tests FAILED:
	 11 - TpetraTSQR_FullTsqr_Accuracy_10000rows_5cols_MPI_4 (Failed)
	 13 - TpetraTSQR_FullTsqr_Accuracy_5000rows_100cols_Sequential_MPI_4 (Timeout)
	 64 - TpetraCore_CrsGraph_UnpackMerge_MPI_2 (Failed)
	 69 - TpetraCore_CrsMatrix_UnitTests4_MPI_4 (Failed)
	 97 - TpetraCore_CrsMatrix_UnpackMerge_MPI_2 (Failed)
	365 - Belos_Tpetra_BlockCG_hb_test_MPI_4 (Timeout)
	366 - Belos_Tpetra_PseudoBlockCG_hb_test_MPI_4 (Timeout)
	367 - Belos_Tpetra_PseudoBlockStochasticCG_hb_test_MPI_4 (Timeout)
	368 - Belos_FixedPoint_tpetra_hb_test_no_precond_MPI_4 (Timeout)
	371 - Belos_Tpetra_BlockGMRES_hb_test_MPI_4 (Timeout)
	372 - Belos_Tpetra_BlockFGMRES_hb_test_MPI_4 (Timeout)
	373 - Belos_Tpetra_HybridGMRES_hb_test_0_MPI_4 (Timeout)
	374 - Belos_Tpetra_HybridGMRES_hb_test_1_MPI_4 (Timeout)
	375 - Belos_Tpetra_HybridGMRES_hb_test_2_MPI_4 (Timeout)
	455 - MueLu_Redirection_Tpetra_MPI_4 (Timeout)
	474 - MueLu_ParameterListInterpreterTpetra_MPI_4 (Failed)
	478 - MueLu_ParameterListInterpreterTpetraHeavy_MPI_4 (Failed)
	482 - MueLu_Maxwell3D-Tpetra_1_MPI_4 (Timeout)
	498 - MueLu_VarDofDriver_MPI_2 (Failed)
```
The Belos tests report exactly the same error as the Albany tests that fail with this version of openmpi-4.0.4:
```
 Start 1: Belos_Tpetra_BlockCG_hb_test_MPI_4

1: Test command: /usr/lib64/openmpi/bin/mpiexec "-np" "4" "/home/ikalash/Trilinos/build/packages/belos/tpetra/test/BlockCG/Belos_Tpetra_BlockCG_hb_test.exe" "--verbose"
1: Test timeout computed to be: 10000000
1: Teuchos::GlobalMPISession::GlobalMPISession(): started processor with name camobap.ca.sandia.gov and rank 0!
1: Teuchos::GlobalMPISession::GlobalMPISession(): started processor with name camobap.ca.sandia.gov and rank 2!
1: Teuchos::GlobalMPISession::GlobalMPISession(): started processor with name camobap.ca.sandia.gov and rank 1!
1: Teuchos::GlobalMPISession::GlobalMPISession(): started processor with name camobap.ca.sandia.gov and rank 3!
1: Belos Version 1.3d - 9/17/2008
1: 
1: 
1: p=1: *** Caught standard std::exception of type 'std::logic_error' :
1: 
1:  /home/ikalash/Trilinos/packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp:7298:
1:  
1:  Throw number = 1
1:  
1:  Throw test that evaluated to true: true
1:  
1:  (Proc 1) CrsMatrix::unpackRow: The number of entries to unpack (as reported by numPacketsPerLID) numEnt=0, but the number of bytes to unpack numBytes=564 != 0.
1: [1607026814.096204] [camobap:1546971:0]           sock.c:344  UCX  ERROR recv(fd=32) failed: Bad address
1: [1607026814.096288] [camobap:1546970:0]           sock.c:344  UCX  ERROR recv(fd=29) failed: Connection reset by peer
1: 
1: p=2: *** Caught standard std::exception of type 'std::logic_error' :
1: 
1:  /home/ikalash/Trilinos/packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp:7298:
1:  
1:  Throw number = 1
1:  
1:  Throw test that evaluated to true: true
1:  
1:  (Proc 2) CrsMatrix::unpackRow: The number of entries to unpack (as reported by numPacketsPerLID) numEnt=0, but the number of bytes to unpack numBytes=500 != 0.
1: [1607026814.096705] [camobap:1546972:0]           sock.c:344  UCX  ERROR recv(fd=29) failed: Bad address
1: [1607026814.096773] [camobap:1546970:0]           sock.c:344  UCX  ERROR recv(fd=30) failed: Connection reset by peer
```
I'm not sure how we want to proceed...  I could build openmpi-4.0.3 to verify that there is no problem there, if this would help.  It seems you would have to have access to a machine with openmpi-4.0.4 to try to debug this issue.  I'm happy to provide an account on my workstation to whoever is willing to have a look at this, if that helps.

**Comment by ikalash** [comment]
I should add, for the Tpetra and MueLu tests, the fails look like this: 

```
12: [camobap:1547304] *** An error occurred in MPI_Send
12: [camobap:1547304] *** reported by process [156303361,0]
12: [camobap:1547304] *** on communicator MPI_COMM_WORLD
12: [camobap:1547304] *** MPI_ERR_OTHER: known error not in list
12: [camobap:1547304] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
12: [camobap:1547304] ***    and potentially your MPI job)
```
I googled the error and came across this: https://github.com/openucx/ucx/issues/5443 .  Perhaps the issue is with scalapack not playing nicely w/ openmpi-4.0.4?

**Comment by ikalash** [comment]
One more piece of information: I built openmpi-4.0.1 on my workstation and with that, all tests pass.  This would be consistent w/ the nightly testing.

**Comment by rppawlo** [comment]
This was mentioned at the SART meeting today. I just did a gcc 10.2, openmpi 4.0.5, openmp build - all tpetra tests passed on my workstation:

```
100% tests passed, 0 tests failed out of 226

Label Time Summary:
Tpetra    = 209.46 sec*proc (226 tests)

Total Test time (real) =  13.45 sec
```

**Comment by csiefer2** [comment]
@ikalash Looks like we basically need access to your configuration (and possibly the test machine) for someone to reproduce this.

**Comment by ikalash** [comment]
Let me try openmpi-4.0.5 to see if the issue goes away.  If it does, I'm not too worried about the openmpi-4.0.4 - as long as things don't snowball with new releases of openmpi, I'm happy.  I'll test openmpi-4.0.5 and post back what I learn.

**Comment by ikalash** [comment]
I've verified that this issue goes away w/ openmpi-4.0.5.  This is very interesting!  Anyway I will close it.  Thanks @rppawlo and @csiefer2 for your help with this!

**Comment by kddevin** [comment]
At yesterday's SART meeting, @rrdrake said openmpi 4.0.4 would be the version installed on our institutional clusters.  
So I did an experiment building Tpetra and Zoltan2 with the following module
```
module load sparc-dev/intel-19.0.4_openmpi-4.0.4
```
All tests passed as expected.

**Comment by ikalash** [comment]
That's good to know @kddevin .  Maybe the issues @lxmota and I were seeing with openmpi-4.0.4 were somehow specific to the Fedora architecture that we use?  Anyway, it would be great if this is not a problem on the architectures that will be using the new openmpi-4.0.4 libraries.
