### ISSUE TITLE
Framework:  Intel 19.0.5 build fails Scotch tests

### ISSUE THREAD

**Issue by ZUUL42** [trilinos/Trilinos#8339]
## Bug Report
@trilinos/framework 

### Description
In putting together the Intel 19.0.5 build, it was found it failed a few tests that use Scotch.
A number of solutions were attempted, but a clean build wasn't able to be created without disabling tests.
So, 9 tests were turned off as well as Scotch for Zoltan in order to get the build in place.
The build needs to be fixed so those can be turned back on.

This is follow-on work to #6294.

### Steps to Reproduce
1. Remove test & Scotch disable lines in `cmake/std/PullRequestLinuxIntel19.0.5TestingSettings.cmake`
   (Currently lines 61 - 70)
2. Run Jenkin job `Trilinos_pullrequest_intel_19.0.5`

**Comment by kddevin** [comment]
I left this comment in #6294 as well:
@ZUUL42 @prwolfe Here's an idea.
Scotch has capabilities to sit underneath the ParMETIS interface. Thus, it creates include files parmetis.h and metis.h, but they are really Scotch files. Scotch needs them, but at Sandia, no one else does.

For the "identifier SCOTCH_Num undefined" error: make sure Scotch is not finding ParMETIS' parmetis.h when it is building. Just unloading your parmetis module while building Scotch may accomplish that. Scotch needs to find its own parmetis.h, not ParMETIS'.

For the Zoltan2 incompatible parmetis error:
Scotch's "fake" parmetis.h and metis.h files should not be installed with Scotch; only ptscotch*.h and scotch*.h should be installed with Scotch.
I'm guessing parmetis.h is installed in Scotch's include directory, but the module loads or include paths are specified in an order such that Trilinos finds Scotch's parmetis.h first and tries to use it.
Either way, I think the solution is to NOT install Scotch's parmetis.h and metis.h in the Scotch include directories.

**Comment by wadeburgess** [comment]
Migrated to Jira.
