### ISSUE TITLE
ATDM: Mass GPU test failures showing 'CUDA driver version is insufficient for CUDA runtime version' in CUDA builds on 'ride' starting 2020-11-11

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#8341]
CC: @trilinos/framework

<Checklist>
<???: Add label "client: ATDM">
<???: Add label "ATDM Sev: Blocker" (by default but could be other "ATDM Sev: XXX")>
<???: Add label "type: bug"?>
<???: Add label "impacting: tests"?>
<???: Add label for affected packages (e.g. "pkg: MueLu", "pkg: Tpetra", "pkg: Kokkos", etc.)>
<???: Add label "PA: ???Project Area???" (e.g. "PA: Linear Solvers", "PA: Data Services")>
<???: Add milestone "Initial cleanup of new ATDM ..." or "Keep promoted ATDM ...">
<???: Once GitHub Issue is created, add entries for tests to TrilinosATDMStatus/*.csv files>

## Next Action Status

<status-and-or-first-action>

## Description

As shown in [this query](https://testing.sandia.gov/cdash/index.php?project=Trilinos&begin=2020-11-11&end=2020-11-12&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-white-ride&field2=buildname&compare2=63&value2=cuda) and [this query](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&date=2020-11-11&filtercount=4&showfilters=1&filtercombine=and&field1=groupname&compare1=61&value1=ATDM&field2=buildname&compare2=65&value2=Trilinos-atdm-&field3=status&compare3=61&value3=failed&field4=block&field4count=2&field4field1=testoutput&field4compare1=97&field4value1=error.*cudaErrorInsufficientDriver.*CUDA%20driver%20version%20is%20insufficient%20for%20CUDA%20runtime%20version&field4field2=testoutput&field4compare2=95&field4value2=libcuda.so.1%3A%20cannot%20open%20shared%20object%20file%3A%20Stale%20file%20handle), there are mass test failures in all the CUDA builds on 'ride' impacting the builds:

* `Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-debug`
* `Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-rdc-release-debug`
* `Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-release`
* `Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-release-debug`
* `Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-rdc-release-debug-pt`
* `Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-release-debug-pt`

showing 2339 failing tests for 2020-11-11 shown [here](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&date=2020-11-11&filtercount=4&showfilters=1&filtercombine=and&field1=groupname&compare1=61&value1=ATDM&field2=buildname&compare2=65&value2=Trilinos-atdm-&field3=status&compare3=61&value3=failed&field4=block&field4count=2&field4field1=testoutput&field4compare1=97&field4value1=error.*cudaErrorInsufficientDriver.*CUDA%20driver%20version%20is%20insufficient%20for%20CUDA%20runtime%20version&field4field2=testoutput&field4compare2=95&field4value2=libcuda.so.1%3A%20cannot%20open%20shared%20object%20file%3A%20Stale%20file%20handle) with test output like:

```
terminate called after throwing an instance of 'std::runtime_error'
  what():  cudaGetDeviceCount(&m_cudaDevCount) error( cudaErrorInsufficientDriver): CUDA driver version is insufficient for CUDA runtime version /home/jenkins/ride/workspace/Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-rdc-release-debug/SRC_AND_BUILD/Trilinos/packages/kokkos/core/src/Cuda/Kokkos_Cuda_Instance.cpp:223
Traceback functionality not available

[ride8:98196] *** Process received signal ***
[ride8:98196] Signal: Aborted (6)
[ride8:98196] Signal code:  (-6)
...
--------------------------------------------------------------------------
mpiexec noticed that process rank 0 with PID 0 on node ride8 exited on signal 6 (Aborted).
--------------------------------------------------------------------------
```

or:

```
--------------------------------------------------------------------------
The library attempted to open the following supporting CUDA libraries,
but each of them failed.  CUDA-aware support is disabled.
libcuda.so.1: cannot open shared object file: Stale file handle
libcuda.dylib: cannot open shared object file: No such file or directory
/usr/lib64/libcuda.so.1: cannot open shared object file: Stale file handle
/usr/lib64/libcuda.dylib: cannot open shared object file: No such file or directory
If you are not interested in CUDA-aware support, then run with
--mca mpi_cuda_support 0 to suppress this message.  If you are interested
in CUDA-aware support, then try setting LD_LIBRARY_PATH to the location
of libcuda.so.1 to get passed this issue.
--------------------------------------------------------------------------
```

or just timeouts.

## Current Status on CDash

* [ATDM CUDA builds on 'ride' for current testing day](https://testing.sandia.gov/cdash/index.php?project=Trilinos&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-white-ride&field2=buildname&compare2=63&value2=cuda)

## Steps to Reproduce

One should be able to reproduce this failure on the machine <supported-atdm-machine> as described in:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md

More specifically, the commands given for the system <supported-atdm-system> are provided at:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#ridewhite

**Comment by bartlettroscoe** [comment]
@trilinos/framework, @trilinos/trilinos-product-owners 

FYI: Looks like this is impacting all of the CUDA PR builds on 'ride' as well for the last 16 hours as shown in [this query](https://testing.sandia.gov/cdash/index.php?project=Trilinos&begin=2020-11-10&end=2020-11-12&filtercount=2&showfilters=1&filtercombine=and&field1=groupname&compare1=61&value1=Pull%20Request&field2=buildname&compare2=63&value2=cuda).

I put the label `ATDM Env Issue` on this because this is clearly a problem with 'ride' and not Trilinos because all of the ATDM CUDA builds on other platforms are fine as shown in [this query](https://testing.sandia.gov/cdash/index.php?project=Trilinos&begin=2020-11-11&end=2020-11-12&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm&field2=buildname&compare2=64&value2=white-ride&field3=buildname&compare3=63&value3=cuda) (other than some known failing tests).

I am going to filter out all test failures on 'ride' for now from the [ATDM Trilinos Builds Status Summary](https://gitlab-ex.sandia.gov/atdm/TrilinosATDMStatus) until this is resolved.  (Otherwise, these 3K+ failing tests make it impossible to see other test failures.)

**Comment by etphipp** [comment]
I submitted a ticket to the ride admins about this earlier today, as it was killing my Jenkins jobs for my GenTen project, so they are aware of it.  Fixing it required them to reboot the compute nodes, which they were doing individually once they became idle.  My Jenkins jobs ran successfully earlier this evening, plus my Sacado PR #8325 just went through, so it might all be fixed now.

**Comment by prwolfe** [comment]
Thanks @etphipp - I did not get to this yesterday and I'm glad you did.

**Comment by prwolfe** [comment]
Everything since 8pm yesterday has passed. Ross can you confirm so we can close this one?

**Comment by bartlettroscoe** [comment]
> Everything since 8pm yesterday has passed. Ross can you confirm so we can close this one?

@prwolfe, looking [here](https://testing.sandia.gov/cdash/index.php?project=Trilinos&date=2020-11-13&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-white-ride&field2=buildname&compare2=63&value2=cuda) it looks like the problem is resolved.  However, we will need to check back tomorrow after getting in all of the results to make sure they have fixed this.

**Comment by bartlettroscoe** [comment]
As shown in [this query](https://testing.sandia.gov/cdash/index.php?project=Trilinos&date=2020-11-13&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-white-ride&field2=buildname&compare2=63&value2=cuda), all of the mass test failures appear to be gone.

Closing as complete.
