### ISSUE TITLE
Tpetra::CrsGraph: Thread-parallelize computeGlobalConstants (actually computeLocalConstants)

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#835]
@trilinos/tpetra 
Story: #832

**Comment by tjfulle** [comment]
@mhoemmen  I hit something on the github app on my phone and removed the labels :(. I replaced the Tpetra label, but don't remember what the other one was

**Comment by mhoemmen** [comment]
@tjfulle No worries :) it was "task."  I just added it back.

**Comment by tjfulle** [comment]
@mhoemmen, in `computeLocalConstants`, have you thought about how best to incorporate information returned from `getRowInfo` and `getLocalView` in a thread parallel way (that will run on GPU)?

**Comment by mhoemmen** [comment]
@tjfulle Sorry, I was at a workshop tonight and will be for the next couple days, so I might not respond so often.  By the time `computeLocalConstants` is called, the graph should be in fully packed, device-View storage.  Thus, you should just be able to use the Kokkos::StaticCrsGraph in a device kernel.

It's neither correct nor necessary to use `getRowInfo` and `getLocalView` on device.  Both of them are host-only methods.  `getRowInfo` is thread safe; `getLocalView` returns `Teuchos::ArrayView` and thus introduces possible host thread-safety issues in a debug build.

**Comment by mhoemmen** [comment]
This is actually in progress as part of #2630, via `Tpetra::Details::determineLocalTriangularStructure`.

#2565 will add a bypass for `CrsGraph::computeLocalConstants`, and #2630 will remove the most expensive part of this method.  Thus, I think we may close this issue as "invalid."  It's not "wontfix," because we will actually fix thread parallelization of `computeLocalConstants`, but the local triangular structure and `getNodeNumDiags` parts of that will go away anyway.
