### ISSUE TITLE
Tpetra:  MultiVector failing norm tests without UVM

### ISSUE THREAD

**Issue by tasmith4** [trilinos/Trilinos#8361]
## Bug Report
@trilinos/tpetra 

### Description
Without UVM, some MultiVector unit tests that compute norms are generating incorrect values:
* 7 OrthoDot
* 17 ScaleAndAssign

After discussing as a team, I believe we have high confidence that the KokkosBlas calls are doing the right thing, both numerically and with the memory spaces they use.

**Comment by brian-kelley** [comment]
Yep, for a little more info, I printed out the results in the rank-2 BLAS functions, and the results were exactly the same between a CudaUVMSpace and CudaSpace builds. So any differences are happening outside of KokkosBLAS.

**Comment by tasmith4** [comment]
More investigation on the OrthoDot test reveals a few possible sync issues:
1.  After the multivectors are initialized, they are marked as needing sync to host (I'd expect them to be synced after initialization, or if performance concerns dictate against that, to have them up-to-date on host, needing sync to device).
2.  The calls to `mvec1.getVector(0)->dot(*mvec2.getVector(0))` for some reason mark `mvec1` as modified on device (I'd expect the dot operation to not modify any data in either multivector).
3.  `replaceLocalValue`, `replaceGlobalValue`, `sumIntoLocalValue`, and `sumIntoGlobalValue` have comments stating they modify host memory, but do not seem to mark as modified on host, so later calls to `sync_device` do not bring the updated values to device.

**Comment by tasmith4** [comment]
fixed by #8427
