### ISSUE TITLE
MueLu: run time of some region tests is very high

### ISSUE THREAD

**Issue by mayrmt** [trilinos/Trilinos#8374]
## Description

@trilinos/muelu 
@lucbv @pohm01 

When running all region tests on my machine, some of them take very long, or let's say too long:

- `MueLu_Structured_Region_Linear_R_Elasticity3D_Tpetra_MPI_1` roughly 85 seconds
- `MueLu_Structured_Region_Linear_Elasticity3D_Tpetra_MPI_1` roughly 85 seconds
- `MueLu_Structured_Region_Example_Elasticity3D_MPI_4` roughly 100 seconds
- `MueLu_Structured_Region_Linear_R_Elasticity3D_Tpetra_MPI_4` roughly 50 seconds
- `MueLu_Structured_Region_Example_Poisson3D_27pt_stencil_MPI_1` roughly 170 seconds
- `MueLu_Structured_Unstructured_Region_Example_Poisson3D_27pt_stencil_MPI_1` roughly 170 seconds
- `MueLu_Structured_Region_Example_Poisson3D_27pt_stencil_AMG_MPI_1` roughly 500 seconds
- `MueLu_Structured_Region_Example_Elasticity3D_MPI_1` roughly 620 seconds

Is there something wrong with my configuration or is this a general problem? 

Overall, I'd prefer shorter run times, as they make it more convenient to run the tests more often during development and to detect changed behavior more easily, when refectoring code (as e.g. in #8369).

**Comment by GrahamBenHarper** [comment]
I can confirm that the tests run a little slow on my workstation, and that the majority of the slowdown is caused by elasticity tests. I've attached a log of the MueLu testsuite that I ran on my workstation with a debug build.

[MueLu-tests-vaporwave.txt](https://github.com/trilinos/Trilinos/files/5586048/MueLu-tests-vaporwave.txt)

Some tests like `MueLu_Structured_Region_Linear_Elasticity3D_Tpetra_MPI_1` would be hard to improve since they already only use a 10x10x10 mesh, but I see a couple spots where improvements can be made for other tests.

If these slowdowns are deemed to be more critical, I'm sure we could always peek at some Valgrind/KCacheGrind output to see if anything stands out.

**Comment by GrahamBenHarper** [comment]
Also, @cgcgcg pointed out that it looks like some of the region tests are struggling with the interface scaling. Has this always been an issue?

```
                       TimeMonitor results over 1 processor

Timer Name                                              Global time (num calls)    
-----------------------------------------------------------------------------------
ApplyMatVec: 1 - local apply                            1.31 (495)                 
ApplyMatVec: 2 - communicate data                       0.005448 (419)             
ApplyMatVec: 3 - sum interface contributions            0.001863 (419)             
Compute Linear Interpolation                            0.05965 (2.189e+04)        
Driver: 1 - Build Composite Matrix                      1.822 (1)                  
Driver: 2 - Compute region data                         0.003307 (1)               
Driver: 3 - Build Region Matrix                         31.44 (1)                  
Driver: 3.1 - Build Region Maps                         0.000989 (1)               
Driver: 3.2 - Build Region Importers                    0.0004542 (1)              
Driver: 3.3 - Import ghost GIDs                         0.01414 (1)                
-----------------------------------------------------------------------------------
Driver: 3.4 - Build QuasiRegion Matrix                  31.3 (1)                   
Driver: 3.5 - Build Region Matrix                       0.1256 (1)                 
Driver: 4 - Build Region Hierarchy                      0.3767 (1)                 
Driver: 5 - Solve with V-cycle                          1.451 (1)                  
Driver: S - Global Time                                 35.1 (1)                   
MakeCompositeDirectSolver: 1 - Setup                    0.0006981 (1)              
MakeCompositeDirectSolver: 2 - Factorization            0.003519 (1)               
MakeQuasiregionMatrices: 1 - Create Matrix              0.000145 (1)               
MakeQuasiregionMatrices: 2 - Import data                0.3456 (1)                 
MakeQuasiregionMatrices: 3 - Scale interface entries    30.87 (1)    
...
```
Source: https://testing.sandia.gov/cdash/test/44281633

**Comment by mayrmt** [comment]
@GrahamBenHarper I can confirm @cgcgcg's observation. This is already recorded in #6786. Back then, we decided that this does not require immediate attention. We might reconsider this position. I'll bring this up in our next region MG meeting.

**Comment by mayrmt** [comment]
The timings reported above are so bad, since they were done with a debug build. My bad!

Still, the underlying issue remains, namely that the `MakeQuasiRegionMatrices` takes the largest portion of the overall run time.

**Comment by mayrmt** [comment]
Test runtime is down to less than 0.5 seconds per test. Closing.
