### ISSUE TITLE
Tpetra:  CrsMatrix::getLocalDiagCopy() fails with invalid memory access on GPU

### ISSUE THREAD

**Issue by etphipp** [trilinos/Trilinos#8382]
@trilinos/tpetra 

SPARC is seeing a Kokkos error about an invalid memory access inside Tpetra::CrsMatrix::getLocalDiagCopy() when run on the GPU.  The issue appears to be that this function calls a parallel reduce that runs on the host:
```
GetLocalDiagCopyWithoutOffsetsNotFillCompleteFunctor (LO& lclNumErrs,
                                                        vec_type& diag,
                                                        const row_matrix_type& A) :
    ...
 
    Kokkos::RangePolicy<host_execution_space, LO> range (0, lclNumRows);
    lclNumErrs = 0;
    Kokkos::parallel_reduce (range, *this, lclNumErrs);

    ...
  }

  void operator () (const LO& lclRowInd, LO& errCount) const {
    using KokkosSparse::findRelOffset;

    D_lcl_1d_(lclRowInd) = Kokkos::Details::ArithTraits<IST>::zero ();
    const GO gblInd = lclRowMap_.getGlobalElement (lclRowInd);
```
but the view inside Tpetra::Details::LocalMap does not use CudaUVM space:
```
  using no_uvm_memory_space = typename std::conditional<std::is_same<memory_space, Kokkos::CudaUVMSpace>::value,
    Kokkos::CudaSpace, memory_space>::type;
  using no_uvm_device_type = Kokkos::Device<execution_space, no_uvm_memory_space>;

...

::Kokkos::View<const GlobalOrdinal*, ::Kokkos::LayoutLeft, no_uvm_device_type> lgMap_;
```

Fixing this may be as simple as running the parallel-reduce on the device, but I don't know.

@tcfisher

**Comment by etphipp** [comment]
Changing the parallel-reduce to run on the device appears to not be so simple.  The operator() appears to call Tpetra::RowMatrix::getLocalRowViewRaw, which is a virtual function...

I guess the other option is to deep-copy the map over to the host.

**Comment by brian-kelley** [comment]
@etphipp Thanks for the report, it looks like we don't test the non-fill complete path for ``CrsMatrix::getLocalDiagCopy()``. And I think copying the map to host is probably the best solution - since the device local matrix doesn't exist, this will have to run on host.

**Comment by kddevin** [comment]
Thanks for reporting the error, @etphipp 

Tpetra Maps store both host and device lookup tables.  For device code, Map->getLocalMap()->getGlobalElement() should be used.  For host code, Map->getGlobalElement() should be used.

We will look at this functor to figure out where it should be running and which map it should be using.
What is the timeframe needed for a fix?

**Comment by etphipp** [comment]
Thanks @kddevin.  SPARC can't upgrade to the latest Trilinos-develop until this is fixed.  I'm not sure how soon they will need/want to do that.  Maybe @tcfisher can comment.

**Comment by tcfisher** [comment]
We need this ASAP.

**Comment by etphipp** [comment]
It does appear that changing `Map->getLocalMap()->getGlobalElement()` to `Map->getGlobalElement()` resolves the problem.  Here is the diff of my exact changes:
```
diff --git a/packages/tpetra/core/src/Tpetra_Details_getDiagCopyWithoutOffsets_d
index 32b2074..f8792dc 100644
--- a/packages/tpetra/core/src/Tpetra_Details_getDiagCopyWithoutOffsets_def.hpp
+++ b/packages/tpetra/core/src/Tpetra_Details_getDiagCopyWithoutOffsets_def.hpp
@@ -114,8 +114,8 @@ public:
                                                         vec_type& diag,
                                                         const row_matrix_type& 
     A_ (A),
-    lclRowMap_ (A.getRowMap ()->getLocalMap ()),
-    lclColMap_ (A.getColMap ()->getLocalMap ()),
+    lclRowMap_ (*A.getRowMap ()),
+    lclColMap_ (*A.getColMap ()),
     sorted_ (graphIsSorted (A))
   {
     const LO lclNumRows = static_cast<LO> (diag.getLocalLength ());
@@ -179,8 +179,8 @@ public:
 
 private:
   const row_matrix_type& A_;
-  typename map_type::local_map_type lclRowMap_;
-  typename map_type::local_map_type lclColMap_;
+  map_type lclRowMap_;
+  map_type lclColMap_;
   typename vec_type::dual_view_type::t_host D_lcl_;
   decltype (Kokkos::subview (D_lcl_, Kokkos::ALL (), 0)) D_lcl_1d_;
   const bool sorted_;
```

**Comment by kddevin** [comment]
Thanks, @etphipp .
I will try to get this patch in today or tomorrow.  Or if you already have it in a good format for a PR, you are welcome to submit and I will review.  Your choice.  Thanks again.

**Comment by etphipp** [comment]
@kddevin I created the PR #8404 as requested

**Comment by kddevin** [comment]
Thanks, @etphipp
