### ISSUE TITLE
Framework: Add CUDA_LAUNCH_BLOCKING=OFF PR build

### ISSUE THREAD

**Issue by jwillenbring** [trilinos/Trilinos#8396]
## Enhancement
@trilinos/framework 

Once either #7047 or #8129 has been completed, we need to switch CUDA_LAUNCH_BLOCKING=OFF.

**Comment by jwillenbring** [comment]
With the #8482 PR submitted which will satisfy #7047, I want to lay out a proposed plan for completing this issue. We can iterate on this as it makes sense. As we complete the steps in the plan we decide upon, I want to track the completion of each step in this ticket. Here is my proposed plan:

1) Make changes to turn CUDA_LAUNCH_BLOCKING=OFF to a branch and fire off a test build. Paste a link to the results in this ticket.

1) Once we have a build reflective of the overall state, set up a nightly specialized build on the dashboard with all packages (at least those relevant to the build) enabled. Leave this build running until the end of the effort to establish a fully clean launch blocking=off build, including having a PR build that protects that functionality.

1) Establish a new PR build for CUDA_LAUNCH_BLOCKING=OFF that enables only those packages working at 100%. We can add to this build as additional packages are cleaned up. However, when this build is fully in place, this ticket as defined is done.

@trilinos/framework Let's discuss this plan of action.

**Comment by jwillenbring** [comment]
@ZUUL42 fired off [a build](https://testing.sandia.gov/cdash/index.php?project=Trilinos&parentid=8406294&filtercount=1&showfilters=1&field1=buildstamp&compare1=63&value1=Experimental&filtercombine=and) as described in 1 above. There were only 3 test failures. We will fire off a second to confirm these results. It is clear turning off launch blocking worked because of the warning near the top of the failing test output. 

`Kokkos::Cuda::initialize WARNING: Cuda is allocating into UVMSpace by default
                                  without setting CUDA_LAUNCH_BLOCKING=1.
                                  The code must call Cuda().fence() after each kernel
                                  or will likely crash when accessing data on the host.`

This output was also present for passing tests that were sampled.

With so few failures, we may simply move to a PR build more quickly, and disable these few tests for that build until the tests are fixed.

**Comment by jwillenbring** [comment]
This build is now running on dev->master. We still need to promote to PR.

**Comment by ZUUL42** [comment]
`setenv CUDA_LAUNCH_BLOCKING: 0` was added to a new CUDA 10.1.105 build via the above noted PR.
This new build was tested in dev to master just before and over the break.
On Monday, Jan 04, the new CUDA 10.1.105 build replaced the CUDA 9.2 build for PR testing.

**Comment by jwillenbring** [comment]
This is done and running now.
