### ISSUE TITLE
Framework: Upgrade Intel PR build

### ISSUE THREAD

**Issue by jwillenbring** [trilinos/Trilinos#8398]
## Enhancement
@trilinos/framework 

Per @mwglass Intel 19.1 builds Trilinos much faster than 19.0. We should upgrade the compiler we use for PR builds. First step is to verify if and where we have a version 19.1 compiler available.

**Comment by jwillenbring** [comment]
Per @crtrott Intel 19.1 is the minimum version of the Intel compiler that we can use with the C++17 option.

**Comment by jwillenbring** [comment]
Per @mwglass, Intel OneAPI 2021 might be the next version of the Intel compiler to target, rather than Intel 19.1. Per @mmwolf we should consider a nightly build first prior to a PR build.

**Comment by nmhamster** [comment]
@jwillenbring - @fryeguy52 is installing a suite of TPLs and Intel OneAPI compiler modules on Blake for testing. We would recommend keeping in contact with him on the progress. There are some non-trivial tweaks that this environment needs.

**Comment by wadeburgess** [comment]
Migrated to the Trilinos Help Desk, so closing this issue.
