### ISSUE TITLE
Xpetra::MultiVector tests segfaulting after recent changes in Tpetra

### ISSUE THREAD

**Issue by tawiesn** [trilinos/Trilinos#84]
The Tpetra stack tests in Xpetra for the MultiVector are segfaulting after the recent changes in the Tpetra::MultiVector:

==29656==    at 0x989A7C8: Tpetra::MultiVector<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP, Kokkos::HostSpace>, false>::MultiVector(Teuchos::RCP<Tpetra::Map<int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP, Kokkos::HostSpace> > const> const&, Kokkos::DualView<double**, Kokkos::LayoutLeft, Kokkos::OpenMP, void> const&, Kokkos::DualView<double**, Kokkos::LayoutLeft, Kokkos::OpenMP, void> const&) (Tpetra_MultiVector_def.hpp:403)
==29656==  Address 0x29d is not stack'd, malloc'd or (recently) free'd

The problem seems to result from one of the changes between the commits a244ea7cf43 and 369d2c3d17da.

In my configuration ETI=on

@trilinos/tpetra 
@trilinos/xpetra 
@mhoemmen

**Comment by mhoemmen** [comment]
I haven't been able to replicate this on my machine, in either a debug or a release build.  Does reverting commit a244ea7 help?

**Comment by tawiesn** [comment]
Yes, locally reverting a244ea7 solves the problem for me. Some (but not all) of the nightly test configurations also fail with the same problem. But i cannot see a pattern in which configuration is failing and which is not.

**Comment by tawiesn** [comment]
I studied your patch and the problem seems to be the line 
size_t strides[ViewType::rank];
which should be
size_t strides[8];

[0001-Tpetra-bugfix-in-getColumnStrideOfMultiVectorView.patch.txt](https://github.com/trilinos/Trilinos/files/97729/0001-Tpetra-bugfix-in-getColumnStrideOfMultiVectorView.patch.txt)

**Comment by tawiesn** [comment]
github does not allow to upload *.patch files, so you i added the .txt suffix in above patch file. Please review the patch and submit it if it is ok.

**Comment by aprokop** [comment]
I assume dashboard is all red due to this?

**Comment by tawiesn** [comment]
Yes. All the failings in Xpetra are caused by this. All (new) failings for MueLu as well. The number of build errors is reduced compared to yesterday since i fixed some examples.

**Comment by srajama1** [comment]
Add amesos2 in the list of packages that fail now. The failures have verbose object now. 

@trilinos/amesos2 .

**Comment by bathmatt** [comment]
Shouldn't it be [9] and not [8] since down in the code you say stuff like this chunk.. where you can set stride[8].  

  // Stride with [ rank ] as total length
  template< typename iType >
  KOKKOS_INLINE_FUNCTION
  void stride( iType * const s ) const
    {
      s[0] = 1 ;
      if ( 0 < shape_type::rank ) { s[1] = S0 ; }
      if ( 1 < shape_type::rank ) { s[2] = s[1] * shape_type::N1 ; }
      if ( 2 < shape_type::rank ) { s[3] = s[2] * shape_type::N2 ; }
      if ( 3 < shape_type::rank ) { s[4] = s[3] * shape_type::N3 ; }
      if ( 4 < shape_type::rank ) { s[5] = s[4] * shape_type::N4 ; }
      if ( 5 < shape_type::rank ) { s[6] = s[5] * shape_type::N5 ; }
      if ( 6 < shape_type::rank ) { s[7] = s[6] * shape_type::N6 ; }
      if ( 7 < shape_type::rank ) { s[8] = s[7] * shape_type::N6 ; }
    }

**Comment by bathmatt** [comment]
Oh, and another bug, you have to shape_type:N6...

**Comment by tawiesn** [comment]
Probably, yes. I guess the right fix would be
size_t strides[ViewType::rank+1];
instead of 
size_t strides[ViewType::rank];
from Mark's original commit.
I've taken the "8" from the original version in Tpetra before Mark's commit  a244ea7.
In the concrete case ViewType::rank returned 2 which then obviously crashed when trying to access s[2].

**Comment by crtrott** [comment]
I just looked at it, and yes the rank+1  should do the trick. 
Also that N6 is a bug, I am fixing that and adding a unit test.

**Comment by mhoemmen** [comment]
If the patch works, please apply it.  Thanks!

Btw I was not able to replicate the failures on my computer, so I'm not quite sure what is going on.  As far as I could tell by examining the implementation of Kokkos::View::stride, it should only touch entries of the output array with index less than the rank of the View.  It's obnoxious to have to pass in an array with some magic number 8 for a 2-D View.  Is this a Kokkos::DualView issue?

On Jan 21, 2016, at 3:08 AM, tawiesn <notifications@github.com<mailto:notifications@github.com>> wrote:


Yes. All the failings in Xpetra are caused by this. All (new) failings for MueLu as well. The number of build errors is reduced compared to yesterday since i fixed some examples.

-

**Comment by mhoemmen** [comment]
Thanks Christian!  Hope I didn't cause too much trouble!

On Jan 21, 2016, at 6:41 AM, Christian Trott <notifications@github.com<mailto:notifications@github.com>> wrote:


I just looked at it, and yes the rank+1 should do the trick.
Also that N6 is a bug, I am fixing that and adding a unit test.

-

**Comment by mhoemmen** [comment]
It looks like the commit in question was reverted, and the code was changed back to strides[8].  Thus, I'm calling this closed.  Please feel free to reopen if it still causes troubles.  Thanks all!
