### ISSUE TITLE
Clean MueLu build directories on test machines apollo and perseus

### ISSUE THREAD

**Issue by jhux2** [trilinos/Trilinos#840]
@crtrott @tawiesn A few of the build errors on [perseus](http://testing.sandia.gov/cdash/viewTest.php?onlyfailed&buildid=2619238) and [apollo](http://testing.sandia.gov/cdash/viewTest.php?onlyfailed&buildid=2618965) are due to MueLu XML test files that are no longer in the repo but still in the build directories on those two machines.  Could you clean out those build directories to allow a fresh rebuild?

**Comment by tawiesn** [comment]
On behalf of Christian:

> Uhm, those jobs are run by jenkins, not by me. I thought they should be blown away automatically?
> Christian

**Comment by tawiesn** [comment]
There should be a possibility to clean up the build directory before build starts, shouldn't it?
@bmpersc Isn't there an option to do so in ctest/tribits?

For Jenkins there would be a plugin, see e.g. https://wiki.jenkins-ci.org/display/JENKINS/Workspace+Cleanup+Plugin

Not sure whether we really want that. Could be useful to tell people that they have to clean the build directory. Is there a policy to do this?

The corresponding CMakeLists.txt file contains a general hook to copy all xml files from the source to the build directory. Even if we touch it (which should trigger the copy process) it wouldn't remove files that are not existing any more, i guess...

**Comment by jhux2** [comment]
@tawiesn @bmpersc Another possibility is to use ```file(REMOVE [<files>...])``` in cmake.  If we follow this logic, then every time we removed an XML file, we'd need to add it to the list of files to delete.

**Comment by bmpersc** [comment]
The default for our testing system right now is to start from a clean build dir. I do not know why perseus or apollo would not be doing this, but I can look into it.

**Comment by aprokop** [comment]
It seems this is no longer an issue. Quick check of dashboard confirms that both apollo passes the tests, and perseus is no longer on the dashboard.
