### ISSUE TITLE
Framework:  Single vs. Multiple config.ini file support for PR builds

### ISSUE THREAD

**Issue by william76** [trilinos/Trilinos#8400]
@trilinos/framework 

## Enhancement
The current capabilities of the PR environment module script, which loads the [pullrequest.ini][1] file, is that each file is self-contained.

@jmgate has requested that we look into expanding the capabilities of [setenvironment][2] to give us an `import` function to allow us to split configurations across multiple files rather than use a single monolithic file that would encode all builds.

## Advantages to Multi-File
1. Avoid having a single monolithic file that contains ALL configurations.
1. We could create `common.ini` files for base configurations, and project specific files based on needs of a particular stakeholder (i.e., Sierra, ATDM, etc.)
1. It's easier to scroll around through files with hundreds of lines rather than thousands.
1. Reduces merge conflicts if different projects or developers are modifying their configurations simultaneously.

## Disadvantages to Multi-File
1. Increase complexity to the .ini file handler. We'll have to expand the tool to organize multiple files.
    - The package that handles the initial read of these files ([configparser][3])
    - Silly things, such as "must all the .ini files be in the same directory", can add a considerable amount of complexity to the app, its testing, and eventual technical debt due to stakeholders putting _their_ .ini files in "nonstandard" locations.
1. Increased chance of naming conflicts / ambiguity in our section headers.
1. It may be more difficult to find things if you're having to scan through and trace dependency trees across multiple files.
1. Is it worth the investment in the engineering of this for the benefit?
    - We can probably make a monolithic .ini file easier to get around through good use of comments and appropriate section headers, etc.

## Notes on the Configparser Module
The configparser module at its core is a pretty simple handler. It loads up a standard .ini file (similar to .gitconfig files for example) which are structured like this:
```ini
# comments and whitespace are allowed
[section name]
key = value
key : value
key with spaces : value with spaces


```
The main restriction is that section names must be unique and within a section each key must also be unique (they're stored as dictionaries). We impose a simple 'language' on top of this structure by splitting the keys into a space-delimited tuple containing an _operation_ and an _argument_... which lets us add commands such as `module-load sems-gcc : 8.3.0` which would equate to typing `module load sems-gcc/8.3.0` to the console.

## Roll our Own Configparser analogue?
The _configparser_ module isn't particularly complicated... I wonder if we wish to go down the rabbit hole of adding additional complexity to our parser layer that sits on top of configparser if we should just roll our own? Right now it's a pretty simple parser, but the more complexity we add the greater the chances we could have issues should the API for _configparser_ ever change (unlikely in the short term... but in the long term...)

ATTN: @jmgate,

[1]: https://github.com/trilinos/Trilinos/blob/develop/cmake/std/pr_config/pullrequest.ini
[2]: https://github.com/trilinos/Trilinos/tree/develop/cmake/std/trilinosprhelpers/setenvironment
[3]: https://docs.python.org/3/library/configparser.html

**Comment by jmgate** [comment]
Thanks for creating this, @william76.

@rppawlo, could I get some more of your thoughts here?  I understand the desire to avoid potentially deep nesting with a plethora of files, but I'm also hesitant to say the ideal solution is a single file containing all the environments any Trilinos user/developer, application user/developer, or CI service would like to use.  Perhaps the right solution is somewhere in between?  I'm thinking perhaps there's a base Trilinos file, but then a user/developer/app could create their own customization file that effectively inherits off the base, and then maybe we only allow for those two layers.  Then again, I also kind of like the idea of separating things out by machine.  There's a number of possible directions we could go, and I can see both pros and cons wherever I look.

For reference, an example of what such a file might look like can be found [here](https://github.com/trilinos/Trilinos/blob/master/cmake/std/pr_config/pullrequest.ini).  I like it as-is, but worry about when it grows to ten times its current size.

**Comment by rppawlo** [comment]
I think either way is fine. If I went to a new machine and had to create a new file to pass around to other users, is this the intended new mechanism to replace the single atdm config file? We definitely want to make that use case easy for reproducibility. Does configparser come with base python or is this going to be a new requirement to be able to reproduce any trilinos PR build failures? I'm more worried about making sure all the tools for standing up a new build or for reproducibility are easily available on all platforms. To me that might motivate me to write a simple parser inline so to avoid an explosion of non-standard python package requirements.

**Comment by jmgate** [comment]
@william76, correct me if I'm wrong, but I think `configparser` comes with base Python.

Also, is it worth going through the additional work / adding the additional complexity to allow config file inheritance if we only intend to allow two layers?  Perhaps one big file, appropriately documented, is the way to go.

**Comment by william76** [comment]
@jmgate I think `configparser` is included... I had a look at the [CentOS 8 App Search][1] which is similar to RHEL and there is a `python3-configparser` package but I checked in a Docker image of CentOS8 that I have which installs Python 3.x without explicitly installing that module and `configparser` was available so I think it's bundled with Python in some way automagically.

[1]: https://centos.pkgs.org/8/centos-appstream-x86_64/

**Comment by william76** [comment]
From some conversation earlier, the single configuration file vs. multiple configuration file question has pros and cons either way.  I think if we allow multi-configuration files within say, the setenvironment, framework I'd like to constrain _where_ it can look for files it might include... possibly restrict the search path to the same dir as the current .ini file or maybe only in an immediate subdir because one form of technical debt is the "where is the dang configuration file" problem. :p  I'm thinking about the 5-years-from-now situation where the hierarchy might get difficult to manage.

the single .ini file is also challenging in the '5-years-from-now' scenerio too when it's a 10,000 line file. At least it's all in one place, but we'd need to manage it to keep it under control and prune out deprecated builds too.

either way, I think we'll want to distinguish a configuration file that handles the _environment_ setup from a configuration file that defines the _cmake options_ that we'd want to send in. So in some way I don't think it's practical to get down to a "single configuration file for _everything_" world.

**Comment by jmgate** [comment]
> either way, I think we'll want to distinguish a configuration file that handles the environment setup from a configuration file that defines the cmake options that we'd want to send in. So in some way I don't think it's practical to get down to a "single configuration file for everything" world.

Good point, @william76.  Yes, the tools to load the environment and configure the code will be separate tools, so at a minimum we'd be dealing with two such configuration files.

Perhaps a good path forward is to stick with a single configuration file, with the understanding that we might refactor the infrastructure to handle multiple files if that becomes preferable in the future.  Does that seem reasonable?

@jwillenbring, @prwolfe, @e10harvey, @ZUUL42, anyone else want to weigh in?

**Comment by rppawlo** [comment]
Will this restrict users from supplying a new config file for a new platform? One of the more common use cases is where a team may start porting to a new machine and they develop a new file with all the required configure options for the new system. We usually pass this file around internally allowing the team members to test various packages/configure options/applications. Once it is in a good state we then pass along to the framework team (or maybe add it an an experimental/atdm build). Or is this config file for internal PR testing only?

**Comment by jmgate** [comment]
The change to the workflow would be rather than creating a new config file, you’d be modifying an existing one.  The intent would be to have one config file (per tool) for all users/developers/application customers/CI services/etc.  Instead of passing a new config file around, you’d
```
Create a branch
while not done:
    Edit config file
    Commit
    Push
    Test
Submit PR to Framework
```

**Comment by e10harvey** [comment]
> @jwillenbring, @prwolfe, @e10harvey, @ZUUL42, anyone else want to weigh in?

I am in favor of multiple config files with a restricted include path. In the long run, I think this will be less burden to maintain than one large config file.

**Comment by jmgate** [comment]
@e10harvey, can you elaborate on how you might restrict the include path?

**Comment by e10harvey** [comment]
> @e10harvey, can you elaborate on how you might restrict the include path?

I do not know. I am not familiar with all the details involved here so I'm looking at this from a high-level and incomplete view. That being said, I was picturing specifying the include path within the top-level ini file. For example, adding `include_path: /path/to/env/ini/files` to the top-level ini file and then updating the internal code to use the given ini filename instead of the given section name. Perhaps this over-complicates the configparser code. Another option would be to keep the current configparser code and write a small pre-pass phase that preprocess the ini files under VCS into a large monolithic ini file at runtime. A third approach would be to switch to another configuration file format. At first glance I see that pyyaml has an extension for supporting an include path: https://pypi.org/project/pyyaml-include/.

**Comment by jmgate** [comment]
We've made the decision for now to not allow `*.ini` file inheritance, so we'll just have one config file per tool.  That said, we may wind up revisiting this at some point in the future if the single configuration file becomes unmanageable and we want to look back into allowing a restricted hierarchy of them.
