### ISSUE TITLE
Tpetra: Bad interaction with Kokkos ETI with XL compiler

### ISSUE THREAD

**Issue by tcfisher** [trilinos/Trilinos#8418]
## Bug Report
@trilinos/tpetra
@jhux2 
@brian-kelley 

### Description
SPARC is failing to link on vortex pwr9 seemingly because of the change in TpetraExt_MatrixMatrix_def.hpp from 75333e4ed. The XL compiler is the only place it has appeared. The error is as follows: 

```
/projects/atdm_devops/trilinos_installs/2020-12-02/ats2-xl-2020.03.18_spmpi-rolling_serial_static_opt/lib/libtpetraext.a(TpetraExt_MatrixMatrix.cpp.o):(.toc+0x68): undefined reference to `KokkosSparse::Experimental::SortedCountEntries<unsigned long, int, Kokkos::View<unsigned long const*, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, Kokkos::MemoryTraits<0u> >, Kokkos::View<unsigned long const*, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, Kokkos::MemoryTraits<0u> >, Kokkos::View<int const*, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, Kokkos::MemoryTraits<0u> >, Kokkos::View<int const*, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, Kokkos::MemoryTraits<0u> >, Kokkos::View<unsigned long*, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, Kokkos::MemoryTraits<0u> > >::ORDINAL_MAX'
```

Please confirm that the deduced template arguments are the intended template arguments when using `GO=long long` and `LO = int`.

**Comment by jhux2** [comment]
@trilinos/tpetra

**Comment by jhux2** [comment]
@trilinos/xpetra

**Comment by brian-kelley** [comment]
@tcfisher Sorry I missed this notification. The missing symbol ``ORDINAL_MAX`` is a ``static constexpr`` member of a class, and I didn't know that (until C++17), you still need to give those an out-of-class definition. GCC and Clang let me do it anyway, but XL doesn't. I'll post a fix that doesn't involve static constexprs at all.

**Comment by jhux2** [comment]
@brian-kelley Thank you for looking at this.

**Comment by brian-kelley** [comment]
OK, I thought I understood this but there are 2 other places in KokkosKernels that also use static constexpr variables, without a definition in a .cpp, but those didn't cause any errors on XL (I did replicate the linker error with ORDINAL_MAX).

**Comment by brian-kelley** [comment]
#8443 fixes this. I built with XL on vortex all tests for KokkosKernels, Tpetra, Ifpack2, MueLu and got no errors. A handful of tests failed but I don't think they're related to this.

**Comment by kddevin** [comment]
Appears to be fixed.  Please re-open if not.  Thanks for reporting, @tcfisher
