### ISSUE TITLE
SEACAS Ioss: Installing Trilinos on Cray

### ISSUE THREAD

**Issue by alahyari** [trilinos/Trilinos#8425]
## Question
@trilinos/seacas

I'm trying to install Trilinos on our local Cray machine as part of the Exawind project. I installed all the dependencies via spack and I adjust and use the provided script in exawind-builder to install Trilinos (cmake_cmd is attached). 
[trilinos.txt](https://github.com/trilinos/Trilinos/files/5644224/trilinos.txt)

And I get the following error
[make_output.log](https://github.com/trilinos/Trilinos/files/5644261/make_output.log)

When I disable the SEACASIoss package, the build completes, but Nalu-Wind needs that package enabled. 

Any help would be greatly appreciated. And thank you in advance.

**Comment by jhux2** [comment]
@alahyari You might get a more informed answer if you post this to NaluWind.  Anyway, it looks like you're missing `zlib`, see https://stackoverflow.com/questions/20593423/undefined-reference-to-inflateinit2.  I'm not sure why it's missing from exawind-builder, @sayerhs will probably know.

**Comment by sayerhs** [comment]
@alahyari can you also share the `cmake_output.log` that exawind-builder generates? It is likely that there is a conflict between the zlib that was used to build HDF5/NetCDF and the one that was picked up during CMake configure step of Trilinos.

**Comment by alahyari** [comment]
Thank you @jhux2 and @sayerhs for your input. Here is the cmake_output.log
[cmake_output.log](https://github.com/trilinos/Trilinos/files/5645141/cmake_output.log)

**Comment by sayerhs** [comment]
Thanks. Looks like configure is picking up the same libz as what was used for HDF5 and NetCDF. Can you also run `make VERBOSE=1` so that we can see the link line for those STK executables?

**Comment by gsjaardema** [comment]
If you are using static libraries, then you probably need to explicitly specify linking to libz `-lz` in your cmake configuration.  I think that the Trilinos config scripts do this for some platforms.  For some reason, the HDF5 cmake file does not correctly add the libz dependency for static library builds.

**Comment by alahyari** [comment]
Here is the output of `VERBOSE=1 -j 1`
[make_output.log](https://github.com/trilinos/Trilinos/files/5645926/make_output.log)

**Comment by sayerhs** [comment]
@alahyari thanks. So looking at the output somehow the build line is incorrect. this should have all the libraries listed by TPL_Netcdf_LIBRARIES. Need to figure out why this isn't happening. 

```
[ 57%] Linking CXX executable io_shell
cd /lus/dal/users/shahab/ext_lib/source/trilinos/build/packages/seacas/libraries
/ioss/src/main && /usr/local/bin/cmake -E cmake_link_script CMakeFiles/io_shell.
dir/link.txt --verbose=1
/opt/cray/pe/craype/2.5.17/bin/CC  -pedantic -Wall -Wno-long-long -Wwrite-string
s -Wshadow -Woverloaded-virtual    -O3 -DNDEBUG CMakeFiles/io_shell.dir/io_shell
.C.o CMakeFiles/io_shell.dir/shell_interface.C.o -o io_shell  -Wl,-rpath,/lus/da
l/users/shahab/ext_lib/install/gcc/trilinos/lib libio_info_lib.a ../init/libIoni
t.a ../transform/libIotr.a ../heartbeat/libIohb.a ../gen_struc/libIogs.a ../gene
rated/libIogn.a ../visualization/libIovs.a ../exodus/libIoex.a ../libIoss.a ../.
./../exodus/libexodus.a /lus/dal/users/shahab/ext_lib/spack/opt/spack/cray-cnl6-
ivybridge/gcc-7.3.0/netcdf-c-4.7.3-fch/lib/libnetcdf.a /lus/dal/users/shahab/ext
_lib/spack/opt/spack/cray-cnl6-ivybridge/gcc-7.3.0/hdf5-1.10.4-w3w/lib/libhdf5_hl.a /usr/lib64/libm.a /lus/dal/users/shahab/ext_lib/spack/opt/spack/cray-cnl6-ivybridge/gcc-7.3.0/parallel-netcdf-1.12.1-s7s/lib/libpnetcdf.a ../../../../../zoltan/src/libzoltan.a -lm /lus/dal/users/shahab/ext_lib/spack/opt/spack/cray-cnl6-ivybridge/gcc-7.3.0/zlib-1.2.11-koc/lib/libz.a ../../../../../kokkos/algorithms/src/libkokkosalgorithms.a ../../../../../kokkos/containers/src/libkokkoscontainers.a ../../../../../kokkos/core/src/libkokkoscore.a /usr/lib64/libdl.a /lus/dal/users/shahab/ext_lib/spack/opt/spack/cray-cnl6-ivybridge/gcc-7.3.0/hdf5-1.10.4-w3w/lib/libhdf5.a
../visualization/libIovs.a(Iovs_DatabaseIO.C.o): In function `Iovs::DatabaseIO::load_plugin_library(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
```
