### ISSUE TITLE
Tpetra:  Sync/modify of subviews of a DualView

### ISSUE THREAD

**Issue by tasmith4** [trilinos/Trilinos#8426]
@trilinos/tpetra 

Syncing/modifying a subview will change the sync state of its parent DualView (see https://github.com/kokkos/kokkos/issues/2514 for more discussion on this).

This caused a subtle error in the MultiVector ScaleAndAssign unit test, where MultiVector A was initialized on device, then while filling B:

Case `j%2` ("Method 2") has
```
aj = A.subView
aj->get1dView does sync_host of ONLY aj BUT clears need_sync_host for ALL of A,
    as DualView shares the flags with subviews
```

Then in case `j%3` ("Method 3")
```
A.getData(j) does not sync to host, because need_sync_host is false from above,
    but vector 3 was not actually synced because aj didn't include it in its sync.
```

This can be fixed in this instance by calling `A.sync_host()` after initialization, but exposes a subtilty that may come back to bite us later.  If possible, we would like to find a way of handling DualView semantics with subviews that provides clear and consistent expectations to users of MultiVector.

**Comment by tasmith4** [comment]
@kddevin this is fixed in #8821, right?

**Comment by tasmith4** [comment]
@kddevin or @csiefer2, can we close this, or is it still an issue until MultiVector uses WrappedDualView?

**Comment by kddevin** [comment]
This was fixed by adding the owning view, requiring that the entire view is synced when a subview is synced, and not allowing subviews on host and device at the same time.
