### ISSUE TITLE
Can't reproduce non-CUDA PR builds on SNL COE RHEL7 machines with just the SEMS modules

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#8429]
@trilinos/framework,

FYI: It looks like you can no longer reproduce the non-CUDA PR builds on an SNL COE RHEL7 machine using just the SEMS modules.  Instead, it appears that you must be on a CEE LAN RHEL7 machine as now the Python being used in 3.6.10 which is using a Sierra module.  See https://github.com/trilinos/Trilinos/pull/7508#issuecomment-739318388

How are developers supposed to reproduce PR builds if they don't have a CEE LAN account and can't get one (i.e. if you can't get an SRN account)?

Also note that standard CEE LAN RHELl7 machines are not installed with BLAS and LAPACK and therefore you can't reproduce any of the non-CUDA PR builds on those machines either.  See https://github.com/trilinos/Trilinos/pull/7508#issuecomment-739073829.

**Comment by bartlettroscoe** [comment]
@trilinos/framework,

Even on a CEE LAN RHEL7 machine, you can't reproduce the non-CUDA PR builds.  It selects the wrong Python compared to the version shown in PR testing (for example [here](https://testing.sandia.gov/cdash/build/8338228/configure) for the 'gcc_7.2.0_debug') which shows:

```
-- Found PythonInterp: /projects/sierra/linux_rh7/install/Python/3.6.10/bin/python (found suitable version "3.6.10", minimum required is "2.6") 
-- PYTHON_EXECUTABLE='/projects/sierra/linux_rh7/install/Python/3.6.10/bin/python'
```

But when I try to reproduce this locally using Trilinos 'develop' as of commit fb03550 on my CEE LAN RHEL7 machine (just updated to RHEL7 from RHEL6 last month) using the directory setup:

```
$ cd /scratch/rabartl/Trilinos.base/BUILDS/PR/gcc_7.2.0_debug/

$ ls -l load-env.sh 
lrwxrwxrwx 1 rabartl rabartl 87 Dec  4 12:10 load-env.sh -> /scratch/rabartl/Trilinos.base/Trilinos/cmake/std/sems/PullRequestGCC7.2.0TestingEnv.sh

$ cat do-configure
TRILINOS_DIR=/scratch/rabartl/Trilinos.base/Trilinos
rm -r CMake*
cmake \
-G Ninja \
-C ${TRILINOS_DIR}/cmake/std/PullRequestLinuxGCC7.2.0DebugTestingSettings.cmake \
-D Trilinos_ENABLE_TESTS=ON \
-D Trilinos_ENABLE_ALL_FORWARD_DEP_PACKAGES=OFF \
-D TPL_ENABLE_BLAS=OFF \
-D TPL_ENABLE_LAPACK=OFF \
"$@" \
${TRILINOS_DIR}
```

(NOTE: I have to disable BLAS and LAPACK because they are not installed by default on CEE LANL RHEL7 machines) and running:

```
$ time ./do-configure -DTrilinos_ENABLE_TrilinosBuildStats=ON &> configure.out

real    0m8.191s
user    0m5.141s
sys     0m5.078s
```

it shows in the configure output in `configure.out`:

```
-- Found PythonInterp: /projects/sems/install/rhel7-x86_64/sems/compiler/python/2.7.9/bin/python (found suitable version "2.7.9", minimum required is "2.6") 
-- PYTHON_EXECUTABLE='/projects/sems/install/rhel7-x86_64/sems/compiler/python/2.7.9/bin/python'
```

But the SIERRA module exists on my system:

```
$ ls /projects/sierra/linux_rh7/install/Python/3.6.10/bin/python
/projects/sierra/linux_rh7/install/Python/3.6.10/bin/python
```

**Comment by bartlettroscoe** [comment]
I think I found the problem:

```
$ git log-short --name-status -S"3.6.10" -- cmake/std/
2069ef1 "Framework: PR driver scripts use Python 3.6.10"
Author: William McLendon <wcmclen@sandia.gov>
Date:   Wed Nov 4 14:34:39 2020 -0700 (4 weeks ago)

M       cmake/std/PullRequestLinuxDriver.sh

c588505 "Framework: Debugging Python2.x removal from PR Driver Framework"
Author: William McLendon <wcmclen@sandia.gov>
Date:   Tue Nov 3 15:38:55 2020 -0700 (5 weeks ago)

M       cmake/std/pr_config/pullrequest.ini

222c44e "Framework: Cloud nodes only have Python 3.6.3 in Sierra space"
Author: William McLendon <wcmclen@sandia.gov>
Date:   Tue Nov 3 15:33:39 2020 -0700 (5 weeks ago)

M       cmake/std/PullRequestLinuxDriver.sh

f8ea42d "Framework: Change python executable to the sierra one for test script driver"
Author: William McLendon <wcmclen@sandia.gov>
Date:   Tue Nov 3 15:00:06 2020 -0700 (5 weeks ago)

M       cmake/std/PullRequestLinuxDriver.sh

ab61341 "Framework: PR Driver Overhaul and Cleanup"
Author: William McLendon <wcmclen@sandia.gov>
Date:   Fri Sep 11 14:16:27 2020 -0600 (3 months ago)

M       cmake/std/PullRequestLinuxPython3.cmake
A       cmake/std/configs/trilinos_pr.ini
```

@william76, if you change the version of Python used by the outer Python driver, you are inadvertently changing the version of Python being used by the inner CMake configures.

Can you please change this to use the SEMS Python module `sems-python/3.5.2` that appears to be on all systems?

**Comment by bartlettroscoe** [comment]
This is now what you need to do to reproduce the env on CEE LAN RHEL7 machines:

```
$ module purge
$ source /scratch/rabartl/Trilinos.base/Trilinos/cmake/std/sems/PullRequestGCC7.2.0TestingEnv.sh
$ module unload sems-python/2.7.9
$ module load sierra-python/3.6.10

$ module list
Currently Loaded Modulefiles:
  1) sems-env                                     6) sems-zlib/1.2.8/base                        11) sems-superlu/4.3/base
  2) sems-gcc/7.2.0                               7) sems-hdf5/1.10.6/parallel                   12) sems-cmake/3.12.2
  3) sems-openmpi/1.10.1                          8) sems-netcdf/4.7.3/parallel                  13) sems-ninja_fortran/1.8.2
  4) sems-git/2.10.1                              9) sems-parmetis/4.0.3/parallel                14) sierra-python/3.6.10
  5) sems-boost/1.63.0/base                      10) sems-scotch/6.0.3/nopthread_64bit_parallel

$ which python
/projects/sierra/linux_rh7/install/Python/3.6.10/bin/python

$ python --version
Python 3.6.10
```

**Comment by bartlettroscoe** [comment]
FYI: I just realized that by mentioning trilinos/developers, they are not getting just the one email but are getting all future comments.  That was not my intention.  (I should have just used email for that.)

**Comment by bartlettroscoe** [comment]
And as shown [here](https://testing.sandia.gov/cdash/build/8338548/configure), the version of Python being used for the 'cuda_9.2' PR build is:

```
-- Found PythonInterp: /home/projects/ppc64le/python/3.7.3/bin/python (found suitable version "3.7.3", minimum required is "2.6") 
-- PYTHON_EXECUTABLE='/home/projects/ppc64le/python/3.7.3/bin/python'
```

**Comment by william76** [comment]
> @william76, if you change the version of Python used by the outer Python driver, you are inadvertently changing the version of Python being used by the inner CMake configures.
> 
> Can you please change this to use the SEMS Python module `sems-python/3.5.2` that appears to be on all systems?

@bartlettroscoe I don't have any bandwidth to look at this over the weekend. There's a lot here, I'll need to parse through it on Monday... but we did run into some issues when removing uses of Python2 in the scripts where some of the internal scripts were calling Python2 because of the shbang line just loading a `python` ... this causes problems when our PYTHONPATH is set pointing to the Python3 instance which is driving the top level script. 

Initially, I had tried just using the SEMS modules but ran into some issues with that and had to scrap it. I think there was some problem with SEMS not having a python >= 3.6 available which caused some issues. I've put in requests to them to add it but they have said they won't do it until their 'next gen' TPL tool is done.

**Comment by bartlettroscoe** [comment]
> I don't have any bandwidth to look at this over the weekend.

@william76, this is no huge emergency at this point.  Now that I have figured out what is happening and why I was not able to reproduce the errors initially by following the instructions in [Reproducing PR Testing Errors](https://github.com/trilinos/Trilinos/wiki/Reproducing-PR-Testing-Errors), I can deal with this.  (I will try to get everything working with Python 3.6 and 3.7 which is what is actually being used some PR builds instead of the Python 2.7.9 which is advertised in the `XXX_env.sh` file.)

But this is something that should be addressed soon so other developers don't loose a couple of hours trying to reproduce PR errors without success.

**Comment by bartlettroscoe** [comment]
BTW: It is fine if the Trilinos PR builds require Python 3.6 or any other version of Python.  It is just that the instructions for reproducing builds needs to use those versions.  And if you have to be on the CEE LAN to reproduce any PR builds, then so be it.  (But then I am not sure what developers will do to reproduce errors if they can't get on a CEE LAN RHEL7 machine.)

**Comment by rppawlo** [comment]
I don't think we want to rely on any cee modules at this point. Developers on the open network won't be able to reproduce builds with the exact testing stack.

**Comment by bartlettroscoe** [comment]
@william76, one thing that I think would fix this would be to put `module purge` at the top of all of the `XXXEnv.sh` files. 

I suspect what is happening right now is that the command:

```
module load sems-python/2.7.9
```

like at:

https://github.com/trilinos/Trilinos/blob/4271dc94f680c0c09878437703a49148d6619ca4/cmake/std/sems/PullRequestGCC7.2.0TestingEnv.sh#L11

is erroring out because another Python module is already loaded.  (But I can't confirm that because I don't run this stuff locally or at least I don't know where there are instructions for doing that.)

**Comment by bartlettroscoe** [comment]
FYI: It looks like even as of the merge of PR #8442 that some of the non-CUDA PR builds are still using:

```
/projects/sierra/linux_rh7/install/Python/3.6.10/bin/python
```

which is only available on the CEE LAN.  Therefore, Trilinos developers who can't access the CEE LAN can reproduce those PR builds.

See https://github.com/trilinos/Trilinos/pull/8442#issuecomment-741956488.

**Comment by william76** [comment]
@bartlettroscoe are you describing the _scripts to replicate a build_ or the _PR's themselves_ ?

We do have to use the sierra python 3.6 build for the actual PR runs because 
1. The SEMS 3.5.x has had problems
2. SEMS will not implement a 3.6.x until their next gen tool is out (There have been multiple tickets requesting this but we're still waiting for it after nearly a year). 
3. The `replication` scripts just use SEMS and so we've pointed them at the best we can get which is the sems 3.5.2. I ran it a couple times on a non-CEE rhel7 system and it built Trilinos successfully.

**Comment by bartlettroscoe** [comment]
CC: @rppawlo 

>  are you describing the scripts to replicate a build or the PR's themselves ?

@william76, this is pretty simple I think.  If you can't get on a CEE LAN RHEL7 machine, then you don't have access to:

* `/projects/sierra/linux_rh7/install/Python/3.6.10/bin/python`

and therefore you can't reproduce the PR builds that use those for the **inner** cmake configure.

Perhaps we need to chat briefly?

**Comment by etphipp** [comment]
I think this points to a fundamental flaw in how we do PR testing where the PR builds run on particular machines with a particular software environment that individuals may or may not have access to or be able to replicate.  Personally, I think a better approach would be to run the PR builds in something like Docker containers where users could download and run the exact same container the PR build used, regardless of what machines they have access to.  That may not be feasible for all PR builds because of some the special architectures used, but it should be for most of them.

**Comment by bartlettroscoe** [comment]
> Problem is we only want to modify the environment/configuration for EMPIRE. We don't want to impact any other customers using the ATDM scripts.

@etphipp, for the CUDA build running on 'ride', likely no. But all of the non-CUDA builds just run on CEE RHEL7 machines and use (mostly) SEMS modules.  Should be easy to do those in a container.

**Comment by etphipp** [comment]
> @etphipp, for the CUDA build running on 'ride', likely no. But all of the non-CUDA builds just run on CEE RHEL7 machines and use (mostly) SEMS modules. Should be easy to do those in a container.

I agree that machines like ride probably can't be done.  But I think that also begs the question whether we should be using machines like ride for PR testing (and not a more traditional x86-based GPU platform) ...

**Comment by bartlettroscoe** [comment]
>  But I think that also begs the question whether we should be using machines like ride for PR testing (and not a more traditional x86-based GPU platform) ...

@etphipp, what machines have the excess compacity for a ton of Trilinos PR builds that that also have exact clones on the SON?  Ride/white has that.  No other system at SNL has that that I know of.  But that is really a question for the @trilinos/framework team.

**Comment by etphipp** [comment]
> @etphipp, what machines have the excess compacity for a ton of Trilinos PR builds that that also have exact clones on the SON? Ride/white has that. No other system at SNL has that that I know of. But that is really a question for the @trilinos/framework team.

There was recently a big purchase where this could have been done, but it is unclear to me how much interest there was from the Trilinos side.  Regardless, this discussion has gotten completely off-topic!

**Comment by bartlettroscoe** [comment]
Talking with @william76, it turns out that the `XXXEnv.sh` scripts listed in:

* https://github.com/trilinos/Trilinos/tree/develop/cmake/std/sems

are not actually used by the Jenkins jobs that run the PR builds.  Someone instead has been trying to edit these files to try to match what is actually used.

**Comment by bartlettroscoe** [comment]
Related to:
* SEPW-213
