### ISSUE TITLE
Piro: introduced a required dependency on ROL.

### ISSUE THREAD

**Issue by rppawlo** [trilinos/Trilinos#8431]
## Bug Report
@trilinos/piro

### Description
Both Charon and EMPIRE are reporting failures due to new ROL requirement in Piro. 

```
00:03:35.172   105 - PanzerAdaptersSTK_solver_MPI_4 (Failed)
00:03:35.172   166 - PanzerAdaptersSTK_main_driver_energy-ss (Failed)
00:03:35.172   168 - PanzerAdaptersSTK_main_driver_energy-ss-blocked (Failed)
00:03:35.172   170 - PanzerAdaptersSTK_main_driver_energy-ss-blocked-tp (Failed)
00:03:35.172   171 - PanzerAdaptersSTK_main_driver_energy-periodic-32bit-limit (Failed)
00:03:35.172   172 - PanzerAdaptersSTK_main_driver_energy-neumann (Failed)
00:03:35.172   175 - PanzerAdaptersSTK_periodic_wedge (Failed)
 
00:01:49.758  *********** Caught Exception: Begin Error Report ***********
00:01:49.758  /scratch/empire-jenkins/trilinos-jobs/clang-opt-serial-static/src/Trilinos/packages/piro/src/Piro_SteadyStateSolver_Def.hpp:1256:
00:01:49.758  
00:01:49.758  Throw number = 1
00:01:49.758  
00:01:49.758  Throw test that evaluated to true: true
00:01:49.758  
00:01:49.758  
00:01:49.758  Piro::SteadyStateSolver::evalReducedHessian():  This fuction requires ROL.
00:01:49.758  
00:01:49.758  ************ Caught Exception: End Error Report ************
 ```

Neither code uses ROL or wants to build it. Can piro be cleaned up for this case?

@mperego @kliegeois @etphipp - we believe this was due to recent changes in Hessian support.

@jmgate @glhenni 

### Steps to Reproduce
1. SHA1:  [insert here]
1. Configure script:  [attach here]
1. Configure log:  [attach here]
1. Build log:  [attach here]
1. Input deck:  [attach here]
1. Do this.
1. Do that.
1. Shake fist angrily at computer.
1. Run log:  [attach here]

**Comment by etphipp** [comment]
@kliegeois, @mperego  Did we introduce this dependency intentionally?

**Comment by kliegeois** [comment]
We introduced a capability in Piro which requires ROL.
I will fix that tomorrow (Belgian time) and create a PR. 
This should be an easy fix.

**Comment by mperego** [comment]
Sorry, that was an oversight. I think the call to evalReducedHessian
https://github.com/trilinos/Trilinos/blob/develop/packages/piro/src/Piro_NOXSolver_Def.hpp#L205
should be ifdef'd guraded.
Kim, I'll fix that if you agree

**Comment by kliegeois** [comment]
> Sorry, that was an oversight. I think the call to evalReducedHessian
> https://github.com/trilinos/Trilinos/blob/develop/packages/piro/src/Piro_NOXSolver_Def.hpp#L205
> should be ifdef'd guraded.
> @kliegeois , I'll fix that if you agree

Thanks @mperego for your comment. I think so too.
If you have time, it would be great if you can fix it; otherwise, I will do so tomorrow.

**Comment by mperego** [comment]
@rppawlo is the problem fixed now?

**Comment by jmgate** [comment]
We're good on EMPIRE's end.  Thanks @mperego 😁

**Comment by bartlettroscoe** [comment]
Looks like these are passing in the ATDM Trilinos builds as well today.  Okay to close from that standpoint.

**Comment by rppawlo** [comment]
yes - thanks @mperego !
