### ISSUE TITLE
Ifpack & Ifpack2: missing Copy*petraToHypre()

### ISSUE THREAD

**Issue by ecoon** [trilinos/Trilinos#8433]
## Bug Report
@trilinos/Ifpack @trilinos/Ifpack2

### Description
Calling compute() multiple times after updating matrix values does not work.

### Steps to Reproduce
1. SHA1:  current master, 2492f4e
2. Configure script:  configure with Hypre and Ifpack or Ifpack2
3. Run any problem using Ifpack_Hypre or Ifpack2.
4. initialize(), compute(), applyInverse()
5. change matrix values
6. compute() again to signify changed values
7. applyInverse() again
8 be surprised when the inverse applied is the first inverse with old values.

The bug is quite simple -- compute() in Ifpack interfaces means that the values of the matrix have changed and you are free to do any work that is dependent upon the matrix values but not the rhs.  Neither Ifpack_Hypre nor Ifpack2_Hypre correctly deal with this because they do not call CopyEpetraToHypre() or CopyTpetraToHypre(), respectively, in their compute() implementation.

So new matrix values (with the same symbolic structure) never get handed off to Hypre.

The fix is to add calls to CopyEpetraToHypre() in compute() of both classes.

Now, there is a performance question here -- it is possible, if one only uses each matrix once, to call CopyEpetraToHypre() twice (once in initialize and once in compute).   So maybe there is a smarter way to avoid calling it twice in that case.  But it is definitely important that calling compute() with different values triggers the needed copy into Hypre with the new values.

Note this is a regression that was introduced in the latest significant refactor -- it worked as of 

https://github.com/trilinos/Trilinos/blob/c1818bba3beb42fbf8a13231fff3979b48a879d3/packages/ifpack/src/Ifpack_Hypre.cpp

**Comment by ecoon** [comment]
@csiefer2 can you take a look at this?  I would happily fix it by adding Copy*petraToHypre() calls in both computes, as we tend to call compute()/apply() many times and initialize() only once, but maybe you were trying to optimize for a single copy for a good reason...

**Comment by ecoon** [comment]
Also, at the risk of sounding picky, is this really the best interface:

https://github.com/trilinos/Trilinos/blob/master/packages/ifpack2/src/Ifpack2_Hypre_decl.hpp#L367

    SetParameter(bool)

I recognize that many of the other SetParameters are overloading based on a type, but this one seems a bit, well, generic :D

**Comment by jhux2** [comment]
@trilinos/ifpack @trilinos/ifpack2

**Comment by cgcgcg** [comment]
@ecoon I pushed a fix, please let me know if this resolves the issue.
