### ISSUE TITLE
Ifpack2: ok to add coloring algorithm as MTGS/MTSGS parameter?

### ISSUE THREAD

**Issue by brian-kelley** [trilinos/Trilinos#8441]
## Question
@trilinos/ifpack2 
@jhux2 especially

KokkosKernels has a couple of different distance-1 coloring algorithms suitable for GPUs: VBBIT and EB. These are used by Relaxation MTGS/MTSGS. Currently there is no way to choose the algorithm, and the KokkosKernels default for GPUs is EB. Would it make sense to add this a parameter, like "relaxation: mtgs coloring algorithm"?

Here are the tradeoffs:
VBBIT: faster setup and apply. Coloring is faster, and fewer colors used so fewer kernel launches during apply().
EB: more colors, so slightly better preconditioner.

The Ifpack2/Belos tests actually fail with VBBIT because the iterations increase by 1 or 2. If algorithm was a parameter, I would make VBBIT the default but use EB for these tests.

**Comment by cgcgcg** [comment]
I think that this is a pretty reasonable addition. Would it be possible to spell out the differences between the coloring options and their impact on performance in the parameter description (as you did above)? I personally don't have a problem with changing the default.

**Comment by jhux2** [comment]
@brian-kelley I agree, this sounds very reasonable to add.  Thank you.  Feel free to forge ahead!   @csiefer2

**Comment by csiefer2** [comment]
Yup!  No argument here!
