### ISSUE TITLE
ATDM Config:  Turn CUDA_LAUNCH_BLOCKING off for EMPIRE

### ISSUE THREAD

**Issue by jmgate** [trilinos/Trilinos#8452]
## Enhancement
@bartlettroscoe, if we want to ensure `CUDA_LAUNCH_BLOCKING` is off for EMPIRE, how do we insert that into the ATDM DevOps infrastructure such that it's always off when using `load-env.sh` and `load_matching_env.sh`?

CC:  @e10harvey, @rppawlo, @bathmatt

**Comment by jmgate** [comment]
**Note:**  If the answer is more than 30 minutes of work, please say so and we'll make the change elsewhere first and worry about integrating it into Trilinos later.

**Comment by bartlettroscoe** [comment]
@jmgate, @rppawlo, @bathmatt,

A simple solution is to have EMPIRE define an env var:

```
export ATDM_CONFIG_NO_CUDA_LAUNCH_BLOCKING=1
```

and then edit the line:

https://github.com/trilinos/Trilinos/blob/e29f0be643de0d55a202263ef1da8d4bc9c8001c/cmake/std/atdm/sems-rhel7/environment.sh#L209

to be:

```
if [[ "${ATDM_CONFIG_NO_CUDA_LAUNCH_BLOCKING}" != "1" ]] ; then
  export CUDA_LAUNCH_BLOCKING=1
fi
```

However, note that this variable is not being set anywhere else where in the ATDM Trilinos system other than 'ride' and some contributed configurations as shown by:

```
$ cd Trilinos/
$ find cmake/std/atdm cmake/ctest/drivers/atdm/ -type f -exec grep -nH CUDA_LAUNCH_BLOCKING {} \;
cmake/std/atdm/shiller/environment.sh:80:  export CUDA_LAUNCH_BLOCKING=1
cmake/std/atdm/ride/environment.sh:191:  export CUDA_LAUNCH_BLOCKING=1
cmake/std/atdm/ride/environment.sh:210:  export CUDA_LAUNCH_BLOCKING=1
cmake/std/atdm/contributed/kokkos-dev-2/environment.sh:221:  export CUDA_LAUNCH_BLOCKING=1
cmake/std/atdm/contributed/kokkos-dev-2/environment.sh:237:  export CUDA_LAUNCH_BLOCKING=1
cmake/std/atdm/contributed/weaver/environment.sh:171:  export CUDA_LAUNCH_BLOCKING=1
cmake/std/atdm/contributed/kokkos-dev/environment.sh:228:  export CUDA_LAUNCH_BLOCKING=1
cmake/std/atdm/contributed/kokkos-dev/environment.sh:246:  export CUDA_LAUNCH_BLOCKING=1
cmake/std/atdm/sems-rhel7/environment.sh:209:  export CUDA_LAUNCH_BLOCKING=1
```

But EMPIRE does not run on any of these.

What I find interesting is that `CUDA_LAUNCH_BLOCKING=1` is **not** being set for the CUDA builds on 'ats2' and 'cee-rhel6' as **not** shown in the files:

* https://github.com/trilinos/Trilinos/blob/e29f0be643de0d55a202263ef1da8d4bc9c8001c/cmake/std/atdm/ats2/environment.sh
* https://github.com/trilinos/Trilinos/blob/e29f0be643de0d55a202263ef1da8d4bc9c8001c/cmake/std/atdm/cee-rhel6/environment.sh

@trilinos/tpetra, @trilinos/kokkos, @ndellingwood, @rppawlo,

Does that mean that the Trilinos CUDA test suite can now run without setting `CUDA_LAUNCH_BLOCKING=1`?  Can someone test that out?

**Comment by bartlettroscoe** [comment]
> If the answer is more than 30 minutes of work, please say so and we'll make the change elsewhere first and worry about integrating it into Trilinos later.

@jmgate, given the above analysis, I think it is worthwhile trying to just remove the line:

https://github.com/trilinos/Trilinos/blob/e29f0be643de0d55a202263ef1da8d4bc9c8001c/cmake/std/atdm/sems-rhel7/environment.sh#L209

Given that we don't set `CUDA_LAUNCH_BLOCKING=1` for 'cee-rhel6' or 'ats2' CUDA builds, there is a good chance we don't need to set it for the `sems-rhel7` builds either.  Can someone try that and test this out?  When logged onto any 'asicgpuxy' machine, you can just run:

```
$ cd <some_build_dir>/

$ ln -s $TRILINOS_DIR/cmake/std/atdm/checkin-test-atdm.sh .

$ ./checkin-test-atdm.sh  cuda-volta70-shared-release-debug \
  --enable-all-packages=on --local-do-all```
```

as described at:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#checkin-test-atdmsh

NOTE: We are missing a non-complex CUDA build for 'sems-rhel7' as **not** shown at:

* https://testing.sandia.gov/cdash/index.php?project=Trilinos&date=2020-12-07&filtercount=1&showfilters=1&field1=buildname&compare1=65&value1=Trilinos-atdm-sems-rhel7

someone should likely add that build. That seems like a significant gap in testing.

**Comment by jmgate** [comment]
Problem is we only want to modify the environment/configuration *for EMPIRE*.  We don't want to impact any other customers using the ATDM scripts.

**Comment by bartlettroscoe** [comment]
> Problem is we only want to modify the environment/configuration for EMPIRE. We don't want to impact any other customers using the ATDM scripts.

@jmgate, what other customers?  There are no other customers for the `sems-rhel7` env other than EMPIRE (at least none I know about).

**Comment by bathmatt** [comment]
It is globally we don't want launch blocking.

**Comment by jmgate** [comment]
Wait, @bathmatt, we want to turn `CUDA_LAUNCH_BLOCKING` off for all configures/builds/installs of Trilinos for everyone?  If that's the case, we'll need to loop in the @trilinos/framework.

**Comment by rppawlo** [comment]
the launch blocking flag is only needed at runtime. Has nothing to do with builds. We just need to unset it when the tests are run.

**Comment by jmgate** [comment]
That means it needs to show up in the `load_matching_env.sh`, right?

**Comment by bartlettroscoe** [comment]
> That means it needs to show up in the load_matching_env.sh, right?

@jmgate, **not** show up.

**Comment by jmgate** [comment]
Rather
```bash
unset CUDA_LAUNCH_BLOCKING
```

needs to be in `load_matching_env.sh`, right?

**Comment by bartlettroscoe** [comment]
> `unset CUDA_LAUNCH_BLOCKING` needs to be in `load_matching_env.sh`, right?

@jmgate, if you put that in EMPIRE's wrapper for this you should be set.

**Comment by jmgate** [comment]
👍

Anyone else having trouble "reacting" to GitHub comments?  I had to insert the thumbs-up in a separate comment.

**Comment by bartlettroscoe** [comment]
> Anyone else having trouble "reacting" to GitHub comments?

@jmgate, no I just gave your last comment the thumbs up.

**Comment by bartlettroscoe** [comment]
FYI: What makes the CUDA builds for 'cee-rhel6' and 'ats2' different than for 'sems-rhel7' (see [above](https://github.com/trilinos/Trilinos/issues/8452#issuecomment-742651723)) is that the form are CUDA 10 builds while the latter is a CUDA 9.2 build.  So it seems that the Trilinos test suite seems to work with `CUDA_LAUNCH_BLOCKING` **not** set for CUDA 10!

**Comment by bartlettroscoe** [comment]
Related to:
* SEPW-215
