### ISSUE TITLE
seacas install issue on Edison machine

### ISSUE THREAD

**Issue by ikalash** [trilinos/Trilinos#846]
I have nightly tests on the Edison NERSC machine that build Trilinos with seacas.  Starting last week, the Trilinos install has begun to fail due to the following issue:

-- Installing: /project/projectdirs/piscees/nightlyEdisonCDash/build/TrilinosInstall/bin/cth_pressure_map
CMake Error at packages/seacas/libraries/ioss/src/main/cmake_install.cmake:56 (file):
  file RPATH_CHANGE could not write new RPATH:

    /project/projectdirs/piscees/nightlyEdisonCDash/build/TrilinosInstall/lib

  to the file:

    /project/projectdirs/piscees/nightlyEdisonCDash/build/TrilinosInstall/bin/cth_pressure_map

  No valid ELF RPATH or RUNPATH entry exists in the file;
Call Stack (most recent call first):
  packages/seacas/libraries/ioss/src/cmake_install.cmake:158 (include)
  packages/seacas/libraries/ioss/cmake_install.cmake:64 (include)
  packages/seacas/cmake_install.cmake:46 (include)
  cmake_install.cmake:90 (include)

Do you know how to resolve this?  Did something change in the seacas build rules that would cause this problem in the past week?  Greg Sjaardema mentioned that there were some changes to the RPATH handling in Trilinos (or TriBits) in the recent past.  I need to have a current version of Trilinos built on Edison for some land-ice simulations I am trying to make.  The problem started Mon. Nov. 7, 2016.

Thanks,

Irina

**Comment by bartlettroscoe** [comment]
@ikalash, can you please attach your full configure script and CMake STDOUT?

In the meantime, try `-DCMAKE_SKIP_INSTALL_RPATH=TRUE`.

**Comment by mhoemmen** [comment]
@trilinos/seacas @gsjaardema

**Comment by mperego** [comment]
I experienced the same issue. See attached the config and sdtout files.
This fixed it: 
 -DCMAKE_SKIP_INSTALL_RPATH=TRUE.

Thanks.

[edison-trilinos-cmake.txt](https://github.com/trilinos/Trilinos/files/628306/edison-trilinos-cmake.txt)
[stdout_build.txt](https://github.com/trilinos/Trilinos/files/628307/stdout_build.txt)
[stdout_install.txt](https://github.com/trilinos/Trilinos/files/628308/stdout_install.txt)
