### ISSUE TITLE
Amesos2_SuperLU no member named 'LargeDiag_MC64' Darwin Error

### ISSUE THREAD

**Issue by spdomin** [trilinos/Trilinos#8462]
## Bug Report
@trilinos/amesos2

### Description
I just noticed a Mac build issue for my Nalu build due to a failed Trilinos build.

Good SHA1:

```
12/10/2020
NaluCFD/Nalu SHA1: f3ad8416c50cd92dbe7a3c23e28d2ea45289a470
Trilinos/develop SHA1: 4c5776ae31069ff66a6737d962c72f49aeef8621

```

Bad SHA1:

```
12/11/2020
PROCESS FAILED
NaluCFD/Nalu SHA1: f3ad8416c50cd92dbe7a3c23e28d2ea45289a470
Trilinos/develop SHA1: 1d57a9275a9c9c5346511b807fd5a6ad47c965fa

```

Error:

 36%] Building CXX object packages/amesos2/src/CMakeFiles/amesos2.dir/Amesos2_Superlu.cpp.o
In file included from /Users/naluIt/gitHubWork/nightlyBuildAndTest/Trilinos/packages/amesos2/src/Amesos2_Superlu.cpp:48:
/Users/naluIt/gitHubWork/nightlyBuildAndTest/Trilinos/packages/amesos2/src/Amesos2_Superlu_def.hpp:763:18: error: 
      no member named 'LargeDiag_MC64' in namespace 'SLU'
            SLU::LargeDiag_MC64,
            ~~~~~^
1 error generated.

### Steps to Reproduce
This is my config... The same config file works on other platforms...

cmake \
-DCMAKE_INSTALL_PREFIX=$trilinos_install_dir \
-DTrilinos_ENABLE_CXX11=ON \
-DCMAKE_BUILD_TYPE=RELEASE \
-DTrilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON \
-DTpetra_INST_DOUBLE:BOOL=ON \
-DTpetra_INST_INT_LONG:BOOL=ON \
-DTpetra_INST_INT_LONG_LONG:BOOL=OFF \
-DTpetra_INST_COMPLEX_DOUBLE=OFF \
-DTrilinos_ENABLE_TESTS:BOOL=OFF \
-DTrilinos_ENABLE_ALL_OPTIONAL_PACKAGES=OFF \
-DTrilinos_ALLOW_NO_PACKAGES:BOOL=OFF \
-DTPL_ENABLE_MPI=ON \
  -DMPI_BASE_DIR:PATH=$mpi_base_dir \
-DTPL_ENABLE_SuperLU=ON \
  -DSuperLU_INCLUDE_DIRS:PATH=$superlu_inc_dir \
  -DSuperLU_LIBRARY_DIRS:PATH=$superlu_lib_dir \
-DTPL_ENABLE_Boost:BOOL=ON \
  -DBoost_INCLUDE_DIRS:PATH=$boost_inc_dir \
-DTrilinos_ENABLE_Epetra:BOOL=OFF \
-DTrilinos_ENABLE_Tpetra:BOOL=ON \
-DTrilinos_ENABLE_ML:BOOL=OFF \
-DTrilinos_ENABLE_MueLu:BOOL=ON \
-DTrilinos_ENABLE_EpetraExt:BOOL=OFF \
-DTrilinos_ENABLE_AztecOO:BOOL=OFF \
-DTrilinos_ENABLE_Belos:BOOL=ON \
-DTrilinos_ENABLE_Ifpack2:BOOL=ON \
-DTrilinos_ENABLE_Amesos2:BOOL=ON \
-DTrilinos_ENABLE_Zoltan2:BOOL=ON \
-DTrilinos_ENABLE_Ifpack:BOOL=OFF \
-DTrilinos_ENABLE_Amesos:BOOL=OFF \
-DTrilinos_ENABLE_Zoltan:BOOL=ON \
-DTrilinos_ENABLE_STKMesh:BOOL=ON \
-DTrilinos_ENABLE_STKSimd:BOOL=ON \
-DTrilinos_ENABLE_STKIO:BOOL=ON \
-DTrilinos_ENABLE_STKTransfer:BOOL=ON \
-DTrilinos_ENABLE_STKSearch:BOOL=ON \
-DTrilinos_ENABLE_STKUtil:BOOL=ON \
-DTrilinos_ENABLE_STKTopology:BOOL=ON \
-DTrilinos_ENABLE_STKBalance:BOOL=OFF \
-DTrilinos_ENABLE_STKUnit_tests:BOOL=OFF \
-DTrilinos_ENABLE_STKUnit_test_utils:BOOL=OFF \
-DTrilinos_ENABLE_Gtest:BOOL=ON \
-DTrilinos_ENABLE_SEACASExodus:BOOL=ON \
-DTrilinos_ENABLE_SEACASEpu:BOOL=ON \
-DTrilinos_ENABLE_SEACASExodiff:BOOL=ON \
-DTrilinos_ENABLE_SEACASNemspread:BOOL=ON \
-DTrilinos_ENABLE_SEACASNemslice:BOOL=ON \
-DTrilinos_ENABLE_SEACASIoss:BOOL=ON \
-DTPL_ENABLE_Netcdf:BOOL=ON \
-DNetCDF_ROOT:PATH=${netcdf_install_dir} \
-DHDF5_ROOT:PATH=${hdf_install_dir} \
-DHDF5_NO_SYSTEM_PATHS=ON \
-DPNetCDF_ROOT:PATH=${pnetcdf_install_dir} \
-DTrilinos_ASSERT_MISSING_PACKAGES=OFF \
$EXTRA_ARGS \
../

**Comment by ndellingwood** [comment]
@spdomin can you confirm if this is with version 5.2.1 of SuperLU?
@mperego if this bug is with 5.2.1 it is likely related to PR #8454, in which case we may need to revert, assuming my understanding is correct (based on email conversation with Sherry) indicating that the SuperLU enum issues you saw on Cori were possibly due to improper TPL install?

**Comment by mperego** [comment]
@ndellingwood Yeah sorry about that. According to Sherry it's a issue with cori installation. So I can revert the commit.

**Comment by spdomin** [comment]
Okay, let me know when the revert has been processed and I will make sure that I re-test and report back.

**Comment by spdomin** [comment]
Sorry. Missed the SuperLU question. We are sitting on: SuperLU v4.3

That sounds like it may be too old? In reality I think I had a Trilinos ticket open years ago on full transition to KLU and a deprecation of SuperLU. @jhux2 may recall. At the time Muelu may not have supported a pure KLY interface. 

At any rate is it everyone’s opinion that I should just remove SuperLU for KLU? When I tried that before I can recall many many diffs.

**Comment by mperego** [comment]
> Sorry. Missed the SuperLU question. We are sitting on: SuperLU v4.3
If that's the case, than my fix won't work.

In my experience SuperLU works much better than KLU for PDEs

**Comment by jhux2** [comment]
@spdomin wrote:
> Sorry. Missed the SuperLU question. We are sitting on: SuperLU v4.3
> 
> That sounds like it may be too old? In reality I think I had a Trilinos ticket open years ago on full transition to KLU and a deprecation of SuperLU. @jhux2 may recall. At the time Muelu may not have supported a pure KLY interface.
> 
> At any rate is it everyone’s opinion that I should just remove SuperLU for KLU? When I tried that before I can recall many many diffs.

@spdomin You might be thinking of this issue:  https://github.com/NaluCFD/Nalu/issues/87.  It appears that when issue 87 was closed, the Nalu test suite was passing with KLU2.

From the multigrid standpoint, I don't see any reason to prefer SuperLU (any version) over KLU2.  This is because the coarse grid system is relatively small (so any direct solve should be fine), plus multigrid is just a preconditioner.   Using SuperLU means dealing with the hassles of versioning -- in particular, I've observed that SuperLU doesn't maintain backwards compatibility.

If you do want to continue using SuperLU, I'm confident that version 4.3 is just as performant as any newer version.

**Comment by spdomin** [comment]
@jhux2, yes, that was the ticket - thanks for digging it up. I just need to work through those diffs (mostly just accept them). At that point, I can remove this dependency.

As noted above, we never use SuperLU as a direct solver for any simulation - just in Muelu for the coarse direct solve.

**Comment by ndellingwood** [comment]
> That sounds like it may be too old?

@spdomin SLU 4.3 should still be supported, the compilation error is a bit confusing because the line of code it points to indicates Trilinos detected that SLU version >= 5.2.2 was detected:

https://github.com/trilinos/Trilinos/blob/bc995600abe8a4c8e9adf1c44263922077ac462a/packages/amesos2/src/Amesos2_Superlu_def.hpp#L762-L766

**Comment by jhux2** [comment]
@ndellingwood Ah, I think I see the problem ....  SuperLU 4.3 doesn't define a macro `SUPERLU_MAJOR_VERSION`, nor any other versioning macro that I can find.

**Comment by jhux2** [comment]
On second thought, maybe that's not a problem, depending on what the C++ preprocessor does if a macro isn't defined.

**Comment by jhux2** [comment]
@spdomin What is the value of `superlu_inc_dir` in your configure?  I'm wondering if `cmake` is picking up a bad header.

**Comment by spdomin** [comment]
@jhux2, On our Mac side, we are actually running an updated version as @ndellingwood noted above - my mistake. I forgot that on the Mac, we use Homebrew for the build/test process, and that version pulls in 5.2.1.4:

```
superlu_inc_dir=/usr/local/Cellar/superlu/5.2.1_4/include/superlu

-- SuperLU_LIBRARY_NAMES='superlu superlu_3.0 superlu_4.0 superlu_4.1 superlu_4.2 superlu_4.3 superlu_5.0 superlu_5.1.1 superlu_5.2.1'
-- Searching for libs in SuperLU_LIBRARY_DIRS='/usr/local/Cellar/superlu/5.2.1_4/lib'
-- Searching for a lib in the set "superlu superlu_3.0 superlu_4.0 superlu_4.1 superlu_4.2 superlu_4.3 superlu_5.0 superlu_5.1.1 superlu_5.2.1":
--   Searching for lib 'superlu' ...
```

Therefore, as of: 

```
commit 8785e8c6c22dcf723b694ac5c91c21a2e7f7162b
Merge: a5b71ed f343ea5
Author: trilinos-autotester <trilinos@sandia.gov>
Date:   Tue Dec 15 15:08:15 2020 -0700

    Merge Pull Request #8478 from brian-kelley/Trilinos/FixIfpack2Timers
    
    Automatically Merged using Trilinos Pull Request AutoTester
    PR Title: Ifpack2: fix timers
    PR Author: brian-kelley
```

I still am seeing this same error:

```
In file included from /Users/naluIt/gitHubWork/nightlyBuildAndTest/Trilinos/packages/amesos2/src/Amesos2_Superlu.cpp:48:
/Users/naluIt/gitHubWork/nightlyBuildAndTest/Trilinos/packages/amesos2/src/Amesos2_Superlu_def.hpp:763:18: error: 
      no member named 'LargeDiag_MC64' in namespace 'SLU'
            SLU::LargeDiag_MC64,
```

I tested the deprecation of SuperLU this morning and, as Jonathan noted, am working through the diffs. Obviously, removing SuperLU resolves this Mac issue, however, I would like to keep this option optional.

**Comment by spdomin** [comment]
Sorry, forgot the final Config confirmation above:
`
--     Found lib '/usr/local/Cellar/superlu/5.2.1_4/lib/libsuperlu.a'`

**Comment by mperego** [comment]
@spdomin 
> I still am seeing this same error:
OK, this is likely because the PR 8471 has not been merged yet.

Would you mind trying this tiny patch?
https://github.com/trilinos/Trilinos/pull/8471/files

Thanks!

**Comment by spdomin** [comment]
> @spdomin
> 
> > I still am seeing this same error:
> 
> OK, this is likely because the PR 8471 has not been merged yet.
> 
> Would you mind trying this tiny patch?
> https://github.com/trilinos/Trilinos/pull/8471/files
> 
> Thanks!

I will try tomorrow AM - thanks:) In the meantime, the KLU2 option seems clean on the Mac platform where tolerances are a bit more lax..

**Comment by spdomin** [comment]
The following path resulted in a clean Trilinos build on my Mac system:

```
naluIt$ git diff origin/develop 
diff --git a/packages/amesos2/src/Amesos2_Superlu_def.hpp b/packages/amesos2/src/Amesos2_Superlu_def.hpp
index 4c19ec3..548ea9f 100644
--- a/packages/amesos2/src/Amesos2_Superlu_def.hpp
+++ b/packages/amesos2/src/Amesos2_Superlu_def.hpp
@@ -759,7 +759,7 @@ Superlu<Matrix,Vector>::getValidParameters_impl() const
             "Use weighted bipartite matching algorithm",
             "Use the ordering given in perm_r input"),
             tuple<SLU::rowperm_t>(SLU::NOROWPERM,
-#if SUPERLU_MAJOR_VERSION > 5 || (SUPERLU_MAJOR_VERSION == 5 && SUPERLU_MINOR_VERSION > 2) || (SUPERLU_MAJOR_VERSION == 5 && SUPERLU_MINOR_VERSION == 2 && SUPERLU_PATCH_VERSION >= 1)
+#if SUPERLU_MAJOR_VERSION > 5 || (SUPERLU_MAJOR_VERSION == 5 && SUPERLU_MINOR_VERSION > 2) || (SUPERLU_MAJOR_VERSION == 5 && SUPERLU_MINOR_VERSION == 2 && SUPERLU_PATCH_VERSION >= 2)
             SLU::LargeDiag_MC64,
 #else
             SLU::LargeDiag,

```

**Comment by mperego** [comment]
@spdomin Thanks! I erged the PR 8471

**Comment by spdomin** [comment]
All is well with the Mac builds now - many thanks for helping out.
