### ISSUE TITLE
Teko:  Two Test Fail from CUDA_LAUNCH_BLOCKING: 0

### ISSUE THREAD

**Issue by ZUUL42** [trilinos/Trilinos#8497]
## Bug Report
@trilinos/teko 

### Description
In order to turn off CUDA Launch Blocking in #8496, I had to disable two Teko tests.

- Teko_testdriver_tpetra_MPI_1
- Teko_testdriver_tpetra_MPI_4

I can turn them back on in the build once adjusted.

### Steps to Reproduce
When setting up the build
`setenv CUDA_LAUNCH_BLOCKING: 0`
When run in a Jenkins job for CUDA 10.1.105, we get these results: [CDash](https://testing.sandia.gov/cdash/index.php?project=Trilinos&parentid=8406294&filtercount=1&showfilters=1&field1=buildstamp&compare1=63&value1=Experimental&filtercombine=and)

**Comment by rppawlo** [comment]
@ZUUL42 - I just put up a PR to fix the failing teko tests and requested your review. Since #8496  has not merged, the tests in question have not yet been disabled yet. I could therefore not revert/reenable in my PR (#8502 ). If #8502 gets merged before #8496 , could you revert commit efa8bc61 in #8496 to reneable the teko tests before merging?

**Comment by ZUUL42** [comment]
I just ran a build that turned all Teko tests back on, including some previously turned off ones: [commit](https://github.com/ZUUL42/Trilinos/commit/5ca785fc6aeee6e68fcb9e9a0ce1204f852d3ff0)
It looks like we can turn 3 tests back on.
[CDash Results](https://testing.sandia.gov/cdash/index.php?project=Trilinos&display=project&filtercount=3&showfilters=1&filtercombine=and&field1=site&compare1=61&value1=ride17&field2=buildname&compare2=61&value2=PR-teko_tests_ON-test-Trilinos_pullrequest_cuda_10.1.105-67&field3=buildstamp&compare3=61&value3=20201221-1656-Experimental)

- `ModALPreconditioner_MPI_1` (turned off when CUDA 9.2 was setup)
- `testdriver_tpetra_MPI_1`
- `testdriver_tpetra_MPI_4`

I'll get that PR out today.

The only remaining failing test is `testdriver_MPI_4`. That was turned off with the initial setup of CUDA 10.1.105. I'll leave it off and let you decide if you'd like an issue setup for that or not.
