### ISSUE TITLE
Teuchos build failures on continuous build

### ISSUE THREAD

**Issue by bmpersc** [trilinos/Trilinos#851]
@trilinos/teuchos @mhoemmen all of Teuchos is failing to build from what appears to be the changes for 8eb97920. This is causing quite a lot of testing to not run due to the dependency on Teuchos.

You can see the errors at:
https://testing.sandia.gov/cdash/viewBuildError.php?buildid=2620467

**Comment by mhoemmen** [comment]
I'll fix it.  Don't anybody accuse me of not testing this.

**Comment by mhoemmen** [comment]
Some compilers support the one-argument version of static_assert.  GCC 4.7.2 does not.

**Comment by mhoemmen** [comment]
Running check-in tests now with GCC 4.7.2.

**Comment by mhoemmen** [comment]
#854 means I had to disable Sacado in the build.  I should get sufficient testing for these features through the Tpetra stack.
