### ISSUE TITLE
testing.sandia.gov/cdash is down starting 2020-12-22

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#8535]
@trilinos/framework

Looks like https://testing.sandia.gov/cdash is down.  I can't get the that site in the browser and I can't even SSH to the machine.

This is bringing down PR testing (see https://github.com/trilinos/Trilinos/pull/8531#issuecomment-754730720) and it is making the ATDM Trilinos builds take a lot longer to submit results because it takes about 12 minutes of retries to fail to submit to testing.sandia.gov/cdash before it gives up and submits to testing-dev.sandia.gov/cdash.  That is making it take a lot longer to run the ATDM Trilinos builds.

Also note #8529.

**Comment by crtrott** [comment]
Who is working on fixing this?

**Comment by e10harvey** [comment]
I opened a service request for this.

**Comment by e10harvey** [comment]
https://testing.sandia.gov/cdash is up again.
