### ISSUE TITLE
Sacado: Internal compiler error with GCC 4.7.2 (MPI_DEBUG build)

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#854]
@trilinos/sacado @etphipp @bmpersc 

```
.../Trilinos/packages/sacado/test/performance/fad_kokkos_hierarchical.cpp: In lambda function:
.../Trilinos/packages/sacado/test/performance/fad_kokkos_hierarchical.cpp:519:9: internal compiler error: in make_decl_rtl, at varasm.c:1147
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://gcc.gnu.org/bugs.html> for instructions.
```

GCC 4.7.2 doesn't like lambdas with Kokkos.  Lambdas are kind of essential to what you're doing, if the name means what I think it means, so I'm not sure if this will actually work with GCC 4.7.2 :(

**Comment by etphipp** [comment]
Argh.  I saw a similar error in the nightly tests but wasn't sure what was causing it.  The lambda issue makes sense.  Thanks for reporting this.

So are we just not using lambdas in Trilinos with Kokkos, and therefore forgoing any hierarchical parallelism, until gcc 4.7 is dropped as supported compiler version?  This is just a performance test so I can just disable it for gcc < 4.8, but I don't see how we can build new capabilities in Trilinos if we can't generally use lambdas.

**Comment by mhoemmen** [comment]
@etphipp wrote:
> So are we just not using lambdas in Trilinos with Kokkos, and therefore forgoing any hierarchical parallelism, until gcc 4.7 is dropped as supported compiler version? 

GCC 4.7.2 gives me troubles when I use a lambda for the outermost parallel loop body.  Said troubles go away when I replace that outer loop body with a functor.  I haven't pushed hard on hierarchical parallelism with GCC 4.7.2, so inner lambdas for the thread or vector loop may be OK.

> This is just a performance test so I can just disable it for gcc < 4.8, but I don't see how we can build new capabilities in Trilinos if we can't generally use lambdas.

I agree :-D  If I remember right, I think there's a push both from Kokkos and from internal customers (@crtrott and @nmhamster , is that right? sorry to draw you two into this) to require newer GCC versions.  It would be something like 4.9, for internal reasons and because CUDA 7.5 doesn't work with newer GCC.

**Comment by etphipp** [comment]
In this case the outer parallel loop is a functor, but uses inner lambdas for the thread and vector loops.

I just pushed cmake code to disable the test for gcc version < 4.8 (I've been building and running the test with gcc 4.8 and 4.9 without problem).
