### ISSUE TITLE
Tpetra build failures on continuous build

### ISSUE THREAD

**Issue by bmpersc** [trilinos/Trilinos#856]
@trilinos/tpetra @mhoemmen Tpetra is now failing to build in the continuous testing in a manner similar to what was causing teuchos to fail to build yesterday as reported in #851.

you can view the errors at:
https://testing.sandia.gov/cdash/viewBuildError.php?buildid=2621727

**Comment by mhoemmen** [comment]
I tested with the SEMS modules, GCC 4.7.2 and Clang 3.9, and OpenMPI.  I build MPI_DEBUG, SERIAL_RELEASE, MPI_RELEASE, and SERIAL_DEBUG, and also tested with CUDA.  You can see that I ran the check-in test script.

I'll work on this now.

**Comment by mhoemmen** [comment]
OK, that's weird.  I definitely had fixed that issue, but the fix disappeared somehow.

**Comment by mhoemmen** [comment]
I'm testing an OpenMPI 1.6.5 build now.

**Comment by mhoemmen** [comment]
I've got a fix ready, but I need to get rid of deprecated warnings from newer versions of OpenMPI.  Working on that now.

**Comment by mhoemmen** [comment]
Y'all were so busying finding my build errors that you didn't notice the utter lack of MPI_Type_commit ;-)

**Comment by mhoemmen** [comment]
OK, I have a complete fix now going through check-in tests.  I did GCC 4.7.2 with OpenMPI 1.6.5 (found some documentation chiseled on clay tablets, and a Sumerian dictionary, so it's all good), as well as Clang 3.9 with OpenMPI 1.10.1.

**Comment by mhoemmen** [comment]
Just pushed the fix.
