### ISSUE TITLE
Can we delete the `deveop` branch?

### ISSUE THREAD

**Issue by bartgol** [trilinos/Trilinos#8564]
## Question
@trilinos/framework

It seems that this branch was last updated a couple of weeks ago (a merge by the AT). The name is quite inconvenient, since it defies the TAB key when doing `git blah origin/dev<TAB>`.

I don't think this branch is used. I would guess someone at some point accidentally created the branch, which later got pushed along other stuff.

**Comment by jwillenbring** [comment]
We had something similar happen one other time. This branch would have at best caused confusion and at worst caused problems, so I deleted it. I have a snapshot if someone needs it.
