### ISSUE TITLE
Inconsistent parameter behavior with different compilers

### ISSUE THREAD

**Issue by pbosler** [trilinos/Trilinos#857]
When initializing a `Zoltan2::PartitioningProblem` for the multi jagged algorithm using
`Teuchos::ParameterList params("zoltan2 params");`
    `params.set("algorithm", "multijagged");`
the parameter "mj_keep_part_boxes" can be set two ways, either as a string or as an integer --listed as (1) and (2) below.  The integer method works for some compilers while the string method fails, and the situation is reversed for other compilers.  Details follow.  

1.    ` params.set("mj_keep_part_boxes", "true");`
2.   ` params.set("mj_keep_part_boxes", 1);`

The string (1) builds with GCC5.4 on Mac OS X, but fails at runtime with the error 
`terminate called after throwing an instance of 'std::logic_error'`
  `what():  Error: part boxes are not stored.`
But the integer version (2) works fine.

The situation is reversed on Skybridge with Intel 16.0; the string version (1) builds and runs fine but the integer version (2) fails to build with the error 
`/usr/lib64/libstdc++.so.6(_ZN9__gnu_cxx27__verbose_terminate_handlerEv+0x12d)[0x7fffefacfa7d]
  what():  Error, the parameter {paramName="mj_keep_part_boxes",type="int"}
in the sublist "zoltan2 params"
has the wrong type.`
`The accepted types are: "bool""string"!`
`Throw number = 1`

Could we either define one of the options (1) and (2) above as the "correct" one and make sure it works for all compilers or intelligently convert the type of the parameter as might be reasonably expected (i.e., `(int)1=(std::string)"true"=(bool)true`)?

Possibly related to #612?

**Comment by kddevin** [comment]
Hi, @pbosler   We recently changed the parameters.  We'll take a look at this problem.  I am on travel this week; what is your timeframe for getting this fixed?
@MicheldeMessieres  Can you take a quick look at this issue?

**Comment by MicheldeMessieres** [comment]
@kddevin I'll have a look at this now.

**Comment by pbosler** [comment]
@kddevin We're still in the early stages of developing our code, so there isn't any immediate pressure here.

**Comment by MicheldeMessieres** [comment]
@pbosler To clarify what should be happening:
The Skybridge appears to be working properly as case 2 should always fail. This parameter should now always be defined as bool or string, but never int.

So the GCC mac build should throw (for case 2) as soon as you create your PartitioningProblem and give an error about the int type - it's unclear at present how you would reach the "part boxes are not stored" throw. I will probably need to build that GCC version and try it but a bit more information will help to reproduce this.

(1) Can you confirm if Zoltan2_mjTest passes on your mac build if you change line 757 of MultiJaggedTest.cpp to be the following:
  params->set("mj_keep_part_boxes", 1); // change true to be 1

That should fail and throw for mjTest when you run the zoltan2 tests (which I have just confirmed) but it sounds like you are saying that works for you. So if you are still able to run that test then we should probably focus on resolving that first. If it does fail but that parameter setup is working for you on a different test, then I may need to get some more information about that test.

(2) Could you clarify if you are loading the parameters first from an XML? I think you may not be, but in case, they should all have that "mj_keep_part_boxes" set in the XML as type="bool" now, not type "int". I don't think this will explain the issue but may be a factor.

(3) Something potentially very helpful would be to set your parameter as:
  params->set("mj_keep_part_boxes", true);   // so use true, not "true" (no quotes)
If that resolves the problem on the mac build, it may help lead to clarity on this.

Then I will investigate further to see if I can reproduce the error.

**Comment by pbosler** [comment]
1) No, this test works properly -- it fails and throws the correct exception.  
2) I am not using XML; I am setting the parameters in-source.  
3) This works on both.

In a confusing twist, as part of pursuing your item 1) above, I did a `make clean`on my Mac code.  This resolved the issue -- the integer case is now throwing the correct exception.
