### ISSUE TITLE
Panzer: error with PHX being undefined broke Albany nightlies

### ISSUE THREAD

**Issue by ikalash** [trilinos/Trilinos#8579]
It looks like there is a Panzer issue that is causing errors in the Albany nightlies.  The error is as follows:

```
/.../repos/Trilinos/packages/panzer/expr-eval/src/Panzer_ExprEval.hpp(191): error: identifier "PHX" is undefined
```
Here is more info on our dashboard: https://sems-cdash-son.sandia.gov/cdash/viewBuildError.php?buildid=11200 .

If someone could please have a look at this / fix it, that would be great.

@trilinos/panzer

**Comment by rppawlo** [comment]
@ikalash - I am able to reproduce. Sorry about this. The ExprEval package is experimental so it did not get enabled in PR testing. A sed script used on panzer accidentally hit these files as well. Do you actually rely on this package or is it getting enabled with the "enable all optional packages" flag? I will get a fix in today.

**Comment by rppawlo** [comment]
PR is up - #8590

**Comment by mperego** [comment]
> @ikalash - I am able to reproduce. Sorry about this. The ExprEval package is experimental so it did not get enabled in PR testing. A sed script used on panzer accidentally hit these files as well. Do you actually rely on this package or is it getting enabled with the "enable all optional packages" flag? I will get a fix in today.

@rppawlo We do use this package in several tests in Albany.

**Comment by mperego** [comment]
@rppawlo would it make sense to enable it in PR testing?

**Comment by rppawlo** [comment]
@mperego - I'm torn on this. If Albany is using it we should probably promote the code to be tested with PR testing. However this is experimental and the main developer has moved on so I'm not sure how much we should invest in maintaining.

**Comment by ikalash** [comment]
Thanks in advance for fixing this, @rppawlo !

**Comment by mperego** [comment]
I think this was fixed. Thanks @rppawlo !

**Comment by ikalash** [comment]
Yes it was.  I thought I closed this, but I guess not.  Thanks @mperego for closing it.
