### ISSUE TITLE
singletons and tpetra/kokkos

### ISSUE THREAD

**Issue by bathmatt** [trilinos/Trilinos#858]
I'm trying to have a static tpetra map as part of a class, which anyone can grab so I can stop passing one around everywhere.  However, this doesn't get destroyed until after the program ends and that throws a kokkos error.

End Result: TEST PASSED
[Thread 0x7ffff34a7700 (LWP 8861) exited]
terminate called after throwing an instance of 'std::runtime_error'
  what():  Kokkos::OpenMP parallel_for ERROR: not initialized
Traceback functionality not available

Is there anyway to do this?  Should there be?

**Comment by mhoemmen** [comment]
Short answer: 

This is not just a Kokkos issue, it's an MPI issue.  In general, don't keep static data around that have MPI or Kokkos state.

Long answer:

This is not just a Kokkos issue, it's an MPI issue.  Tpetra::Map has an MPI_Comm inside, and thus becomes invalid once MPI_Finalize is called.  The Map's Teuchos::Comm could have wrapped an MPI_Comm that requires MPI_Comm_free, so it's important to let its destructor execute before MPI_Finalize is called.

It's possible to schedule a function (e.g., a deallocation / destruction function) to be called when MPI_Finalize is called.  Read the MPI standard and search for MPI_COMM_SELF.  Trilinos uses this in a few places where the interface calls for caching and reusing a persistent object.  However, that won't necessarily solve the Kokkos finalization issue.  Kokkos doesn't yet have an option to add a "finalization hook."

One thing you could try would be to stop calling Kokkos::finalize or MPI_Finalize directly.  Instead, register them (in that order) as atexit() hooks.  Then, register destruction of your static Tpetra::Map as a third atexit() hook.  atexit() is supposed to call its hooks in reverse order of their registration:

http://pubs.opengroup.org/onlinepubs/9699919799/functions/atexit.html
