### ISSUE TITLE
Tpetra: track MultiVector DualView refactoring

### ISSUE THREAD

**Issue by brian-kelley** [trilinos/Trilinos#8591]
## Work Tracking Issue

@trilinos/tpetra 

Branch for working on MultiVector DualView management refactor: TpetraDualViewRefactor.

Updated 2-3-21:
I replaced the new functions we just added (e.g. getLocalViewDeviceConst, getLocalViewHostNonConst) with permament tagged versions:
```
//New interface:
#include "Tpetra_Access.hpp"
//...
MultiVector::getLocalView<Device>(Tpetra::Access::ReadOnly());
MultiVector::getLocalView<Device>(Tpetra::Access::ReadWrite());
MultiVector::getLocalView<Device>(Tpetra::Access::WriteOnly());
```
Non-templated versions like ``getLocalViewHost(tag)`` too.
All getLocalView calls in MultiVector and core/test/MultiVector have been replaced with this new interface, but this caused new failures in tests.

MultiVector
- [x] TpetraCore_MultiVector_UnitTests_MPI_4
- [x] TpetraCore_Transform_MPI_4
- [x] TpetraCore_Bug7758_MPI_4
- [x] TpetraCore_Bug7745_MPI_4
- [x] TpetraCore_MultiVector_get2dView_MPI_1
- [x] TpetraCore_MultiVector_TwoArgRandomize_MPI_1
- [x] TpetraCore_Issue364_MPI_1
- [x] TpetraCore_MultiVector_MicroBenchmark_MPI_1 //works on 4 ranks, doesn't work on 1
- [x] TpetraCore_deep_copy_SerialDenseMatrix_to_MultiVector_MPI_1
- [x] TpetraCore_deep_copy_MultiVector_to_SerialDenseMatrix_MPI_1
- [x] TpetraCore_MV_reduce_strided_MPI_4 //Brian
- [x] TpetraCore_aliased_deep_copy_MPI_4

FEMultiVector
- [ ] TpetraCore_FEMultiVector_UnitTests_MPI_4. // Can't fix until CrsMatrix is fixed
- [x] TpetraCore_FEMultiVector_Fix3101_MPI_4

BlockMultiVector
- [x] BlockMultiVector_MPI_4 
- [x] BlockMultiVector2_MPI_4
- [x] BlockMap_MPI_4.

Import/Export
- [x] Issue3968

**Comment by brian-kelley** [comment]
List of tests in core/test/MultiVector that fail on this branch:

Unit tests:
- [ ] 14. MultiVector_int_longlong_double_Kokkos_Compat_KokkosCudaWrapperNode_CopyView_UnitTest ...
- [ ] 17. MultiVector_int_longlong_double_Kokkos_Compat_KokkosCudaWrapperNode_ScaleAndAssign_UnitTest ...
- [ ] 20. MultiVector_int_longlong_double_Kokkos_Compat_KokkosCudaWrapperNode_Multiply_UnitTest ...
- [ ] 23. MultiVector_int_longlong_double_Kokkos_Compat_KokkosCudaWrapperNode_NonContigView_UnitTest ...
- [ ] 28. MultiVector_int_longlong_double_Kokkos_Compat_KokkosCudaWrapperNode_DualViewSemantics_UnitTest ...
- [ ] 29. MultiVector_int_longlong_double_Kokkos_Compat_KokkosCudaWrapperNode_DualViewCtor_UnitTest ...
- [ ] 30. MultiVector_int_longlong_double_Kokkos_Compat_KokkosCudaWrapperNode_ViewCtor_UnitTest ...
- [ ] 35. MultiVector_int_longlong_double_Kokkos_Compat_KokkosCudaWrapperNode_DualViewRefcountCheck_UnitTest ...

Other tests:
- [ ] TpetraCore_Transform_MPI_4
- [ ] TpetraCore_Bug7758_MPI_4
- [ ] TpetraCore_Bug7745_MPI_4
- [ ] TpetraCore_rcb_MPI_4
- [ ] TpetraCore_Issue364_MPI_1
- [ ] TpetraCore_MV_reduce_strided_MPI_4

**Comment by kyungjoo-kim** [comment]
@brian-kelley  would you put your branch name here  so that I can fork from yours ?

**Comment by kddevin** [comment]
Branch for working on MultiVector DualView management refactor: TpetraDualViewRefactor.

**Comment by kyungjoo-kim** [comment]
Oh.... the branch is from Trilinos repo. I looked for it from brian's forked repo. Now I got it.

**Comment by kyungjoo-kim** [comment]
in order not to duplicate effort, I am currently working on the item 14. MultiVector_int_longlong_double_Kokkos_Compat_KokkosCudaWrapperNode_CopyView_UnitTest.

**Comment by kyungjoo-kim** [comment]
Issue 364 is done.

**Comment by csiefer2** [comment]
Working on removing all  the "old" calls from MultiVector proper

**Comment by csiefer2** [comment]
OK.  So I removed *every* reference to getLocalViewHost() and getLocalViewDevice() in Tpetra and the tests and replaced them with the appropriate const and non-const version.

Complications:

1) Tpetra::MultiVector::description() should *not* do any sync'ing.  To do this I added an "unsafe" function with the old sync-less behavior.  We should discuss this tomorrow.
2) Tpetra::Details::scaleBlockDiagonal calles into KokkosBatched::SerialLU.  This does not handle const args correctly, so I had to dump everything into an unmanged view in a poor man's const_cast.  @brian-kelley Could you take a look at this function and see if the KokkosBatched behavior is correct or if it has a const handling bug that should be fixed.

**Comment by kddevin** [comment]
List of things to do before merging:
- [ ] switch to use access tags (ReadOnly, WriteOnly, ReadWrite)
- [ ] remove sync/modify from all MV usage
- [ ] make sure MV tests work without UVM 
- [ ] make sure all tests work with UVM (a la PR testing)
- [ ] disable old interface when CUDA is ON and UVM is OFF

Eventually, but not necessarily for PR merge
- [ ] formally deprecate old functions (might do when CrsGraph/Matrix deprecations are ready)

**Comment by kddevin** [comment]
Thoughts on ReadOnly/WriteOnly/ReadWrite access:

```
1/29/21

namespace Access {
  struct ReadOnly  {};
  struct WriteOnly {};
  struct ReadWrite {};
}

getLocalView<device>(Tpetra::Access::ReadOnly());
getLocalViewHost(Tpetra::Access::WriteOnly());
getLocalViewDevice(Tpetra::Access::ReadWrite());

getLocalViewHost(const Tpetra::Access::WriteOnly &ignoreme) {
  don't bother syncing
  clear the sync flags
  mark host modify
  return host pointer
}

const getLocalViewHost(const Tpetra::Access::ReadOnly &ignoreme) const {
  sync if needed
  return host pointer
}

getLocalViewHost(const Tpetra::Access::ReadWrite &ignoreme) {
  sync if needed
  mark host modify
  return host pointer
}


getLocalView<device>(Access::ReadOnly());
getLocalViewHost(Access::WriteOnly());
getLocalViewDevice(Access::ReadWrite());
```

@kddevin will change existing Access struct in withLocalAccess
@brian-kelley will put the functions and tags n place
@trilinos/tpetra will update branch to use the new functions with tags

**Comment by kddevin** [comment]
@brian-kelley  @csiefer2 I got all tests except the mv-reduce-strided test passing today.  
The templated getLocalView<>(access) was not working correctly; it was always following the host view path.  So it would return the correct view but with the flags set and sync done incorrectly.  I changed the test for which path to take.  It isn't an elegant test, though, so you probably should review it.  13e3a19582c9fb3848942cd7969b98522fb656f2
I also changed the implementation of getLocalViewHost and getLocalViewDevice to NOT call the templated version.  From a design standpoint, I like avoiding the if tests in the templated function when the user has explicitly told us which view he wants. But I don't like having the logic duplicated in the templated and non-templated functions.  I wish we could just specialize the templated function.
Let's discuss on Tuesday.

**Comment by kyungjoo-kim** [comment]
I removed the sync, modify things on the multivector but I leave the interface there. This interface can be removed later after other items are fixed ie., local access interface is eliminated.

**Comment by brian-kelley** [comment]
I just checked in the removal of withLocalAccess, for_each and transform. The one issue I still see in Ifpack2 is that RBILUK is still trying to call removed BlockMultiVector functions like sync_host. But the things that used withLocalAccess (Chebyshev, Relaxation) built and passed before I rebased on that commit.

**Comment by brian-kelley** [comment]
I got rid of all the deprecated MV/BlockMV calls in Ifpack2, they're all using the new interface.

There were 2 tests in MultiVector_LocalViewTests that failed with CudaUVMSpace: HostDeviceView and DeviceHostView. I think the issue is that they were expecting ``{ h = mv.getLocalViewHost(); d = mv.getLocalViewDevice(); }`` to always throw, but it only throws if host and device are different spaces (if they're not, DualView's host and device views are the same, so reference counts are the same). I fixed one by doing this instead:

```
  bool shouldThrow = ! Kokkos::SpaceAccessibility<Kokkos::Serial, typename Node::memory_space>::accessible;
```
and that fixed HostDeviceView. DeviceHostView I commented out but the same fix should work there.

**Comment by brian-kelley** [comment]
Ifpack2 failures with UVM, without launch blocking:

- [ ] 	 Ifpack2_RILUK_hb_belos_MPI_2
- [ ] 	 Ifpack2_RILUK_hb_belos_MPI_4
- [ ] 	 Ifpack2_unit_tests_MPI_4
- [ ] 	 Ifpack2_AdditiveSchwarz_MPI_4
- [ ] 	 Ifpack2_RBILUK_MPI_4
- [ ] 	 Ifpack2_RILUKSingleProcessUnitTests_MPI_1
- [ ] 	 Ifpack2_BlockTriDiContainerUnitAndPerfTests_MPI_4

**Comment by brian-kelley** [comment]
@kddevin With the last commit, all tests in Tpetra, Belos, Ifpack2, MueLu, and Teko pass with UVM and without launch blocking.

**Comment by kyungjoo-kim** [comment]
@brian-kelley Does the last commit means that the fencing execution space in sync_host and sync_device ?

**Comment by jhux2** [comment]
Did someone say "double fencing"?  @csiefer2 might have something to say about that.

**Comment by brian-kelley** [comment]
@jhux2 Luckily, this is a 0 vs. 1 fences being different, not a 1 vs. 2 fences.

@kyungjoo-kim You were right, even though the fencing was not consistent before, just adding them to sync_host and sync_device wasn't the correct solution. Have a look at https://github.com/kokkos/kokkos/issues/3850 . I think our templated ``getLocalView<Device>(tag)`` is always taking the device path because DualView's type logic is inconsistent between view(), sync() and modify(). That means we could be skipping syncs and/or getting wrong modify flags.

**Comment by brian-kelley** [comment]
That's not the cause of all the ifpack2 failures, though.

**Comment by kyungjoo-kim** [comment]
@brian-kelley That is indeed a sneaky issue.

**Comment by brian-kelley** [comment]
I'm seeing some new failures without CUDA_LAUNCH_BLOCKING since we rebased on develop.
```
TpetraCore_CrsMatrix_Bug8794_MPI_4
TpetraCore_BlockCrsMatrix_MPI_4  -- this one is random, seems to fail roughly half the time
Ifpack2_RILUK_hb_belos_MPI_2
Ifpack2_RILUK_hb_belos_MPI_4
Ifpack2_AdditiveSchwarz_MPI_4
Ifpack2_RBILUK_MPI_4
Ifpack2_RILUKSingleProcessUnitTests_MPI_1
MueLu_UnitTestsIntrepid2Tpetra_MPI_1
MueLu_UnitTestsIntrepid2Tpetra_MPI_4
```
