### ISSUE TITLE
MueLu: fix handling of FactoryManagers in BraessSarazinSmoother

### ISSUE THREAD

**Issue by mayrmt** [trilinos/Trilinos#8596]
## Enhancement
@trilinos/muelu

When calling the `MueLu::BraessSarazinSmoother` from a user app, the very first `TEUCHOS_TEST_FOR_EXCEPTION(pos != 0, ...)` in `AddFactoryManager()` throws. Therefore, 

- [ ] fix implementation of `MueLu::BraessSarazinSmoother`, mainly its handling of `MueLu::FactoryManager` instances for the prediction and Schur complement step.
- [ ] deprecate outdated routines to set the `MueLu::FactoryManager` instances.
- [ ] Maybe introduce `enum` for more descriptive indexing of the positions in the vector of Factory Managers

## Additional Information

- Have a look at the `MueLu::UzawaSmoother`, where a similar mechanism is in place.
- See issue in user app: https://gitlab.lrz.de/baci/baci/-/issues/588

**Comment by mayrmt** [comment]
@mfirmbach Do you have a fix for this locally?

**Comment by maxfirmbach** [comment]
@mayrmt  Yes, I have one.

**Comment by mayrmt** [comment]
@maxfirmbach, great! If you find time to integrate it into `develop`, that would be great, so that we can finally not only close, but actually resolve this issue. It's not super urgent, but maybe you can tackle it within the next couple of weeks. Thanks!

**Comment by mayrmt** [comment]
As I learned in an offline discussion with @maxfirmbach, that one just needs to pass the Schur complement factory to the Braess-Sarazin smoother configuration, e.g. as follows (see `"block1"`):
```xml
<ParameterList name="myBlockSmoother">
      <Parameter name="factory" type="string" value="BraessSarazinSmoother"/>
      <Parameter name="Sweeps" type="int" value="3"/>
      <Parameter name="Damping factor" type="double" value="1.6"/>
      <!-- factory manager for block 1 -->
      <ParameterList name="block1">
        <Parameter name="A" type="string" value="mySchurCompFact"/>
        <Parameter name="Smoother" type="string" value="mySchurSmooFact"/>
      </ParameterList>
    </ParameterList>

    <ParameterList name="myBlockDirectSolver">
      <Parameter name="factory" type="string" value="BlockedDirectSolver"/>
    </ParameterList>
```

Since this fixes the problem, I close this issue.
