### ISSUE TITLE
KokkosAlgorithms_UnitTest_MPI_1 Failing in ATDM builds starting 01-17-2021

### ISSUE THREAD

**Issue by e10harvey** [trilinos/Trilinos#8598]
CC: @trilinos/kokkos, @crtrott (Trilinos Data Services Product Lead), @bartlettroscoe, @trilinos/framework 

## Next Action Status

<status-and-or-first-action>

## Description

As shown in [this query](https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&date=2021-01-17&filtercount=4&showfilters=1&filtercombine=and&field1=groupname&compare1=62&value1=Experimental&field2=buildname&compare2=65&value2=Trilinos-atdm-&field3=status&compare3=62&value3=passed&field4=testoutput&compare4=95&value4=TestRandom.hpp%3A468%3A%20Failure) (click "Shown Matching Output" in upper right) the tests:

* `KokkosAlgorithms_UnitTest_MPI_1`

in the builds:

* `Trilinos-atdm-cee-rhel7_cuda-10.1.243_gnu-7.2.0_openmpi-4.0.3_shared_dbg`

started failing on testing day 2021-01-17.

As shown in https://testing-dev.sandia.gov/cdash/test/41069751, we are seeing output like:
```
 -- Testing 3-D histogram
Density 3D: 6.96226e-07 -0.0140755 0.00321922 || 0.051031 1e+64 -1e+64
/path/to/Trilinos-atdm-cee-rhel7_cuda-10.1.243_gnu-7.2.0_openmpi-4.0.3_shared_dbg/SRC_AND_BUILD/Trilinos/packages/kokkos/algorithms/unit_tests/TestRandom.hpp:468: Failure
Value of: 1
Expected: test_float.pass_var
Which is: 0
Test Seed:1610868645951576250
Test Scalar=int
```

## Current Status on CDash

Run the [above query](https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&date=2021-01-17&filtercount=4&showfilters=1&filtercombine=and&field1=groupname&compare1=62&value1=Experimental&field2=buildname&compare2=65&value2=Trilinos-atdm-&field3=status&compare3=62&value3=passed&field4=testoutput&compare4=95&value4=TestRandom.hpp%3A468%3A%20Failure) adjusting the "Begin" and "End" dates to match today any other date range or just click "CURRENT" in the top bar to see results for the current testing day.

## Steps to Reproduce

One should be able to reproduce this failure as described in:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md

and the system-specific instructions at:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#specific-instructions-for-each-system

Just log into any of the associated machines and copy and paste the full CDash build name `<build-name>` listed above and run commands like:

```
$ cd <some_build_dir>/

$ source $TRILINOS_DIR/cmake/std/atdm/load-env.sh <build-name>

$ cmake \
 -GNinja \
 -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
 -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_<package-name>=ON \
 $TRILINOS_DIR

$ make NP=16

$ <command-to-run-on-compute-node> ctest -j4
```

where `<package-name>` is any package that you want to enable to reproduce build and/or test results.

Again, for exact system-specific details on what commands to run to build and run tests, see:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#specific-instructions-for-each-system

If you can't figure out what commands to run to reproduce the problem given this documentation, then please post a comment here and we will give you the exact minimal commands.

**Comment by crtrott** [comment]
I think this was just the expected occasional failure of the random test. Essentially the test actually does test whether the random generator generates proper random numbers. That specific test is expected to fail once every 10,000 to 100,000 times it is run or so. There are a handful of those tests in the unit test executable so the full executable should report an error maybe every 1,000 to 10,000 times its run or so. Now you do run like 50 different configs per day, so I expect a failure to be reported maybe 2-10 times a year.

**Comment by crtrott** [comment]
The above means I believe this acceptable behavior and the issue should be closed. Note: there is no deterministic way to reliably check whether a random number generator actually generates proper distributions. Hence the stochastic test which sometimes fails.

**Comment by e10harvey** [comment]
See https://github.com/trilinos/Trilinos/issues/3282#issuecomment-439258469 for a possible solution.
