### ISSUE TITLE
ML: implicit declaration of function ‘ML_Operator_Copy_Statistics’

### ISSUE THREAD

**Issue by nschloe** [trilinos/Trilinos#860]
From [the Debian build](https://qa.debian.org/bls/packages/t/trilinos.html):
```
"/<<PKGBUILDDIR>>/packages/ml/src/Coarsen/ml_aggregate.c"
/<<PKGBUILDDIR>>/packages/ml/src/Coarsen/ml_aggregate.c: In function ‘ML_repartition_matrix’:
/<<PKGBUILDDIR>>/packages/ml/src/Coarsen/ml_aggregate.c:2097:3: warning: implicit declaration of function ‘ML_Operator_Copy_Statistics’ [-Wimplicit-function-declaration]
   ML_Operator_Copy_Statistics(mat,permuted_Amat);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by aprokop** [comment]
Unfortunately, it's not as easy as including `<unistd.h>`. Even with defined `_XOPEN_SOURCE 500` it still produced the warnings for me.

**Comment by nschloe** [comment]
Is this really related to `unistd.h`? It seems that `ML_Operator_Copy_Statistics` is defined in `packages/ml/src/Operator/ml_operator.c`, but never declared in a header, so the compiler doesn't know about it in `packages/ml/src/Coarsen/ml_aggregate.c`.
