### ISSUE TITLE
Help Upgrading PyTrilinos to Python 3

### ISSUE THREAD

**Issue by wfspotz** [trilinos/Trilinos#862]
A while back, I created a branch in which I upgraded PyTrilinos to work with both Python 2.7 and Python 3.5. I have not merged this to the develop branch, mainly because it modified some of the Trilinos build system, and I was wary about pushing it onto the Trilinos community without fully testing it.

My upgrade was implemented prior to the TriBITS upgrade to support Python 3. When I merge my branch with develop, I should get all of the TriBITS upgrades. That will leave, for the most part I believe, CMakeLists.txt files that reside in packages that do stuff like:
```
    COMMAND ${PYTHON_EXECUTABLE} -c "print ..."
```
For packages that have Python wrappers, these cmake commands have already been fixed (probably in both develop _and_ my branch, with potential conflicts that will have to be addressed). So the risk is with non-PyTrilinos packages that still have these kind of cmake Python commands. Presumably, all of the PT packages have been addressed. Yes?

So @bartlettroscoe, what do you think? Would a typical checkin-test.py be sufficient? Can you think of any additional testing I should do pre-push?

**Comment by bartlettroscoe** [comment]
I think I would feel more comfortable pushing changes once the new set of PT CI build is pushed as part of #482.  What is your time schedule for this?  I am hoping to have #482 mostly done early next week.

But the big issue for PyTrilinos is that there is no nightly tests for it.  I am guessing the reason for that is that none of the test machines have a version of SWIG installed that will work with PyTrilinos.

We should look at the possibility of adding a 'trilinos' project are to the SEMS NFS mount where we could install a version of SWIG that will work with PyTrilinos.  If we did that, we could at least start testing PyTrilnos in Nighty testing if not in pre-push testing (I would assume that building PyTrilinos is not that much  incrementally more expensive to build and test compared to the rest of the PT packages).

**Comment by wfspotz** [comment]
There is no immediate pressure, so let's do it correctly. I'm happy to wait for #482.

Nightly testing: yes, this is an issue as well. Hopefully, we will work through it soon, though. SWIG is a requirements issue, as is an installed NumPy module for Python. There is an optional dependence on mpi4py as well.

Including these items in the SEMS NFS mount would be welcome.

**Comment by gpkc** [comment]
Are there any updates on this? I'd like very much to use PyTrilinos with Python3.

**Comment by bartlettroscoe** [comment]
I think the TriBITS part is finished.  See TriBITSPub/TriBITS#119.  Can't speak for the rest of Trilinos.  But if there is no automated testing of Trilinos with Python3, then if things do work at some point, they will not likely work for long.   The @trilinos/framework team would need to work to get a Trilinos build with Python3 going to make this happen (first as an experimental build then elevated once it is clean).  Or @wfspotz or someone else outside of the @trilinos/framework team could set up an automated build of Trilinos with PyTrilinos with Python3 and post it to CDash.

**Comment by gpkc** [comment]
Sorry for reposting but I don't know where else to follow this. How is the update for Python 3 going? Please let me know if there is something I can help with, although I have virtually no experience with SWIG.

Supporting Python 3 would surely be a great addition to PyTrilinos, since the Python 2 will only be maintained until 2020.

**Comment by wfspotz** [comment]
Python 3 support is in the 12.12 release.

**Comment by petronny** [comment]
@wfspotz 
No.
556051efdf40b6dd73f44e9b is committed on 5 Oct 2017.
But v12.12.1 is released on 29 Sep 2017.
We have to wait for the next release.

And I'm sure there are more scripts need to be fixed like https://github.com/trilinos/Trilinos/blob/master/doc/DocumentingParameterLists/doc/copy_xml_to_src_html.py#L25
