### ISSUE TITLE
Zoltan2:  interface and testing changes needed for Quotient algorithm

### ISSUE THREAD

**Issue by kddevin** [trilinos/Trilinos#8620]
## Bug Report
@trilinos/zoltan2 

### Description
See comments in late review of #8576 

Interface changes requested:
- Return partListView of quotient algorithm does not match that of other 
  algorithms.

- Currently returning:

  quotient:  one part assignment per MPI rank
    on each processor, Teuchos::ArrayView(1) with part(0) = 
    single value in [0,nparts)

  everything else:  one part assignment per matrix row
    Teuchos::ArrayView(nrows) with part(i) = some value in [0,nparts)

- We should return:

  quotient:  one part assignment per matrix row; all rows assigned to same
             part (until we implement chunking version)
    on each processor, Teuchos::ArrayView(nrows) with part(i) = 
    const A in [0,nparts) for every row i (same A for every row)

  everything else:  one part assignment per matrix row
    Teuchos::ArrayView(nrows) with part(i) = some value in [0,nparts)

- For quotient method, modifying partListView to return part assignment per 
  matrix row allows
    common user interface for all methods;
    matrix redistribution in the partitioning1.cpp test will work for 
      better testing; and
    with quotient, can also check that part(i) = A for all i

Algorithm changes requested:

-  To accomplish change above, might need to 
   have quotient algorithm take Adapter as input (as in AlgPuLP), 
   construct its CommGraphModel itself from adapter, 
   and then use GIDs from adapter to setParts with result.

- Make threshold_ a parameter so that for testing, we can set it 2 for some of
  the PR tests (runs on 4, but migrates to 2)

- Remove untested option to not migrate.
  User can run on 4 and migrate to 4 if he doesn't want to migrate
  Test this case

- Remove code that disables distributeInput for quotient method.

Tests:

-  test both distributeInput=false, true 
   (--no-distribute, --distribute (default))

-  set threshold to run on 4, migrate to 2

-  set threshold to run on 4, migrate to 4

### Steps to Reproduce

Not applicable

**Comment by egboman** [comment]
Fixed by PR #8701.
