### ISSUE TITLE
Autotester fails due to certificate error

### ISSUE THREAD

**Issue by cgcgcg** [trilinos/Trilinos#8630]
## Bug Report
@trilinos/framework 

### Description
The python build of the autotester just failed with a certificate error:
https://testing.sandia.gov/cdash/test/51871133
I don't think that this is related to my PR #8629 in any way.

**Comment by cgcgcg** [comment]
Same issue for PR #8631: https://testing.sandia.gov/cdash/viewTest.php?onlyfailed&buildid=8565833

**Comment by mayrmt** [comment]
Also:
- https://testing.sandia.gov/cdash/viewTest.php?onlyfailed&buildid=8573827 in PR https://github.com/trilinos/Trilinos/pull/8636#issuecomment-767019597
- https://testing.sandia.gov/cdash/test/52082867 in PR https://github.com/trilinos/Trilinos/pull/8593#issuecomment-767020698

**Comment by cgcgcg** [comment]
@trilinos/framework Is somebody taking care of this?

**Comment by jwillenbring** [comment]
@ZUUL42 Is there a status update on this?

**Comment by prwolfe** [comment]
See #8643 - I expect this to resolve this issue.

**Comment by mayrmt** [comment]
@prwolfe Is there something, we need to do in the affected PRs or just wait until #8643 is merged and then re-test the PRs?

**Comment by prwolfe** [comment]
@mayrmt - you should be able to just re-test after #8643 is merged. Assuming I got it right of course ;_>

**Comment by jhux2** [comment]
@prwolfe @jwillenbring Can you guys pause the other PRs to prioritize this one?  Manually labelling everything WIP would be slightly painful but should work.

**Comment by jhux2** [comment]
@trilinos/framework @bathmatt @cgcgcg We've temporarily labelled all other active PR's besides #8643 as "AT: WIP" and "AT: paused for maintenance".

**Comment by jhux2** [comment]
@prwolfe Seems that the output is still bad.

**Comment by cgcgcg** [comment]
Looks like this is resolved. Thanks, @prwolfe!
