### ISSUE TITLE
MiniTensor:  Inconsistent CUDA __host__ __device__ markings

### ISSUE THREAD

**Issue by japlews** [trilinos/Trilinos#8650]
## Bug Report
@trilinos/MiniTensor @lxmota 

### Description
CUDA/nvcc warnings emanating from inconsistent Kokkos inline markings.

### Steps to Reproduce
Build MiniTensor package with CUDA >= 10.1

**Comment by lxmota** [comment]
Closed by #8651, thanks to @japlews for fixing this.
