### ISSUE TITLE
Framework: Cannot Reproduce PR Build Failure

### ISSUE THREAD

**Issue by ccober6** [trilinos/Trilinos#8655]
## Bug Report
@trilinos/framework 

### Description
After getting a PR build failure notice (https://github.com/trilinos/Trilinos/pull/8403), I have tried to reproduce this build failure using the "Wiki: How to Reproduce PR Testing Builds and Errors." instructions, but it builds without a problem?!  This was on cee-build015.

What is different between the PR build and the instructions to reproduce this error?

FYI, I have build this on several machines (cee-build105, ascic169 and my Mac laptop) and different compilers (gcc 7.2 and gcc 8.3), and I still cannot reproduce this build failure.

### Steps to Reproduce
1. SHA1:  211971d
2. Configure script:  cmake -C ~/Tempus_Workspace/Trilinos/cmake/std/PullRequestLinuxGCC8.3.0TestingSettings.cmake -DTrilinos_ENABLE_Tempus=ON -D Trilinos_ENABLE_Piro:BOOL=ON -D Trilinos_ENABLE_ROL:BOOL=ON -G Ninja ~/Tempus_Workspace/Trilinos >& configure.log
3. Configure log:  [configure.log](https://github.com/trilinos/Trilinos/files/5888953/configure.log)
4. Build log:  [build.log](https://github.com/trilinos/Trilinos/files/5889120/build.log)

**Comment by ccober6** [comment]
FYI, it looks like I found the bug, so #8403 is now passing, but it still does not explain why I could not reproduce the PR builds.

**Comment by prwolfe** [comment]
Several of the failures were intel license issues. Likely you were able to get a license when you attempted to re-create this. Sorry that this was not obvious, we are working on reporting for this type of thing.
