### ISSUE TITLE
KokkosKernels:  poor performance for transpose SpMV with tall skinny matrices on host

### ISSUE THREAD

**Issue by kddevin** [trilinos/Trilinos#8658]
## Bug Report
@trilinos/tpetra @crdohrm 

### Description
Report from @crdohrm follows.

When doing 247 matrix-vector multiplies with Tpetra::CrsMatrix on the host (serial node type) when using just a single processor. Times below are in seconds for different ways of calculating matrix-vector products (247 total) involving a tall and skinny matrix (43,374 rows and 181 columns). Notice that the time to do a transpose multiply (mode = Teuchos::TRANS) with Tpetra (about 82 seconds) is much longer on the host than simply doing the calculation by hand (about 3 seconds). Is this expected behavior? In contrast, the time to do a transpose multiply on the device (default node type) is much more reasonable. Let me also note that vortex is the first platform where we’ve noticed this slowdown in performance of transpose multiplies on the host.

```
vortex timings:
numRows, numCols, numTerms = 43374, 181, 7353694
non-transpose by hand (host): 3.44778
transpose by hand     (host): 3.31255
transpose by hand csc (host): 3.18762
non-transpose Tpetra  (host): 3.47372
transpose Tpetra      (host): 82.4091
tranpose Tpetra csc   (host): 3.19165
non-transpose Tpetra  (device): 0.0537
transpose Tpetra      (device): 0.257253
tranpose Tpetra csc   (device): 0.786396

```

### Steps to Reproduce

@crdohrm will provide a unit test to reproduce.

**Comment by kyungjoo-kim** [comment]
@crdohrm @trilinos/tpetra 

The PR described in https://github.com/kokkos/kokkos-kernels/pull/893 would address the above performance issue.

**Comment by kddevin** [comment]
Thanks for the fix, @kyungjoo-kim
