### ISSUE TITLE
Framework: FORCE_CLEAN on build jobs is not working as expected

### ISSUE THREAD

**Issue by ZUUL42** [trilinos/Trilinos#8666]
## Bug Report
@trilinos/framework 

### Description

The FORCE_CLEAN feature on Jenkins jobs does not seem to be working as expected.
Checking the box will not necessarily cause the workspace to be cleaned.

### Steps to Reproduce

When jobs are run manually and the FORCE_CLEAN feature is enabled, the build may not be cleaned before building.

**Comment by wadeburgess** [comment]
Migrated to Jira.
