### ISSUE TITLE
Framework: Intel 19 build failure with CMake 3.17.x

### ISSUE THREAD

**Issue by william76** [trilinos/Trilinos#8669]
## Bug Report
@trilinos/framework 

### Description
The Intel 19 build is failing because of that bug in CMake > 3.17 where CMake fails to compile a trivial program using the Intel compiler. This wasn't tested in our earlier PR because the Intel 19 build is only running on dev->master at this time.

The error shows up in a recent dev->master PR: #8664 

Tasks
------
- [x] Add PR to update the config.ini file to set `LDFLAGS=-lifcore` for the Intel19 build like we did for Intel 17.
- [x] Merge the new PR

**Comment by jwillenbring** [comment]
Will's comment said that #8669 would close this ticket, but that did not happen automatically, so I am closing now.
