### ISSUE TITLE
Tpetra:  How to fill a CrsMatrix (and BlockCrsMatrix) in parallel when rows overlap

### ISSUE THREAD

**Issue by chrisrichardson** [trilinos/Trilinos#8671]
## Question
@trilinos/tpetra

I would like to use MueLu to solve large linear systems, in parallel, e.g. Poisson-3D and Elasticity-3D, from a finite element discretisation. As is usually the case with finite element, I am inserting into both locally owned rows, and unowned rows on each process.

I already have a sparsity pattern "CrsGraph" which is distributed in parallel, and so I think the correct way to do this is something like:

```
// Overlapping column map
  Teuchos::RCP<const Tpetra::Map<std::int32_t, std::int64_t>> colMap;

// Non-overlapping map for rows, and vectors
  Teuchos::RCP<const Tpetra::Map<std::int32_t, std::int64_t>> vectorMap;

  Teuchos::ArrayView<std::size_t> _nnz(nnz.data(), nnz.size());
  Teuchos::RCP<Tpetra::CrsGraph<std::int32_t, std::int64_t>> crs_graph(
      new Tpetra::CrsGraph<std::int32_t, std::int64_t>(vecMap, colMap, _nnz));

// Fill in sparsity locally
for (...)
    crs_graph->insertLocalIndices(row_index, col_indices);

  crs_graph->fillComplete();

  Teuchos::RCP<Tpetra::CrsMatrix<double, std::int32_t, std::int64_t>>
      A_Tpetra = Teuchos::rcp(new Tpetra::CrsMatrix<PetscScalar, std::int32_t, std::int64_t>(crs_graph));
```

Now, I can fill in my matrix entries, either using `A_Tpetra->sumIntoLocalValues()` if it is a local row, or `A_Tpetra->sumIntoGlobalValues()` if the row is on another process, and then call `A_Tpetra->fillComplete()` to "finalize".

This seems to work well. However, I was wondering about using an overlapping "rowMap" so that I can use the same `sumIntoLocalValues()` call for **all** my entries into `A_Tpetra`. This allows me to assemble the matrix, but I can't use it with MueLu, because it needs a one-to-one rowMap. Is there any way to work around this? I thought maybe I can "export" to a new matrix with a one-to-one rowMap, but that seems wasteful of memory.

The main reason I would like to only use local indices, is because for elasticity, I presume I would want to use `Tpetra::BlockCrsMatrix` which doesn't support inserting with global indices (nor does it have a fillComplete method), as far as I can tell. In this case, do I have to (a) manually transfer "unowned rows" to another process, or (b) do an export somehow.

Apologies for the long question - I hope it makes sense... and that there is an answer somewhere that I have missed, and you can just point me to an example!

Many thanks...

**Comment by jhux2** [comment]
Hi @chrisrichardson.  @csiefer2 and others have implemented a Tpetra finite element matrix class that results in an honest-to-goodness CrsMatrix.  It sounds like this is along the lines of what you're after.  I can't find the rendered documentation (I suspect there's something buggy in the doxygen source)  but please have a look at `tpetra/core/src/Tpetra_FE/CrsMatrix_decl.hpp` and the examples in `packages/tpetra/core/example/Finite-Element-Assembly` to see if this fits your needs.

@trilinos/tpetra

**Comment by jhux2** [comment]
@chrisrichardson Btw, it's ok to use a CrsMatrix for 3D elasticity, rather than a BlockCrsMatrix.  You can tell MueLu that there are 6 DOFs per mesh point, and it will consider each consecutive 6 rows as DOFS as living at a mesh node for purposes of coarsening.

**Comment by jhux2** [comment]
@chrisrichardson Did the advice above help at all?

**Comment by jhux2** [comment]
@chrisrichardson I'm closing this issue, please reopen if you have further questions.

**Comment by chrisrichardson** [comment]
Thanks @jhux2 - all useful information!
