### ISSUE TITLE
Tpetra/Kokkos: build errors in Albany due to recent changes

### ISSUE THREAD

**Issue by ikalash** [trilinos/Trilinos#8673]
Several of the Albany nightlies last night failed with the following errors.  On Cori: 

```
/.../Trilinos/packages/kokkos/core/src/impl/Kokkos_EBO.hpp(132): error: invalid type for defaulted assignment operator
```
(https://sems-cdash-son.sandia.gov/cdash/viewBuildError.php?buildid=11981).  On our Fedora machines with gcc: 

```
packages/tpetra/core/src/Tpetra_Details_FixedHashTable_def.hpp:1097:17: error: redeclaration of ‘using ViewAllocateWithoutInitializing = struct Kokkos::Impl::ViewCtorProp<Kokkos::Impl::WithoutInitializing_t, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, Kokkos::Impl::ViewAllocateWithoutInitializingBackwardCompat>
```
(https://sems-cdash-son.sandia.gov/cdash/viewBuildError.php?buildid=11988).
 
Could someone please have a look at this and resolve?

@trilinos/kokkos 
@trilinos/tpetra 

Tagging @lxmota so he's in the loop - some of his nightlies are affected by this.

**Comment by ndellingwood** [comment]
@ikalash I've seen the Kokkos error show up with Intel builds and older gcc headers (pre-5.3.0) that do not fully support c++14. Loading a newer gcc module (5.3.0 or newer) should resolve the issue (or swapping out the gcc module in the case where an older gcc is preloaded as part of a devpack).

**Comment by lxmota** [comment]
I am using gcc 10.2.1 and my nightly tests still failed with that error.

**Comment by ndellingwood** [comment]
@lxmota these types of errors from top of the first cdash link `error: namespace "std" has no member "remove_cv_t"` indicate something is going wrong and picking up gcc headers for an older gcc version that does not fully support c++14, maybe the system install of an older gcc being found first on the system path (I think gcc/4.8.5 is the system install on skybridge)?

**Comment by ikalash** [comment]
Just to clarify: the error with 10.2.1 on Fedora is this one: https://sems-cdash-son.sandia.gov/cdash/viewBuildError.php?buildid=11988 (2nd link).  Regarding the first error: I will check the modules on skybridge.  I think if it were using an older gcc, there would be far more errors.

**Comment by kddevin** [comment]
I'll fix the Tpetra error.  I don't know why the error wasn't seen before, as that file hasn't changed since November.  The fix is easy, though.  Stay tuned.

**Comment by ikalash** [comment]
> @lxmota these types of errors from top of the first cdash link `error: namespace "std" has no member "remove_cv_t"` indicate something is going wrong and picking up gcc headers for an older gcc version that does not fully support c++14, maybe the system install of an older gcc being found first on the system path (I think gcc/4.8.5 is the system install on skybridge)?

I just checked and the Skybridge build is using Intel 18.0.3.20180410, so I think it's highly unlikely something gcc-related is getting picked up.  Do I need to provide special c++14 flags to avoid this, perhaps?  From googling it seems this may fix the problem, but I have not tried it yet.

**Comment by ndellingwood** [comment]
@ikalash 

>  Do I need to provide special c++14 flags to avoid this, perhaps?

You can try explicitly adding `-DCMAKE_CXX_STANDARD=14` to your configuration, though I scanned over the configure output for the failing skybridge build (the first link of original post) and it looks like c++14 is being set

```
-- Using -std=c++14 for C++14 standard as feature
```

> I just checked and the Skybridge build is using Intel 18.0.3.20180410

Could you also confirm the gcc version available with this build? Even though intel is used as the compiler, it is necessary to have gcc version >= 5.3 loaded, otherwise older gcc headers etc. from the system install get picked up that may not have complete c++14 support. Based on my own past experience when seeing the first error of the original post (with intel/17 and intel/18 as compiler), the cause was due to an older version of gcc and I was able to resolve by loading/swapping for a newer gcc module.

**Comment by ikalash** [comment]
I can confirm that this has been resolved.  @ndellingwood I made sure that a newer gcc module was being loaded and added the C++14 flags, and the problem on skybridge is gone.  Thanks!
