### ISSUE TITLE
STK: Intel 19 build issue

### ISSUE THREAD

**Issue by jwillenbring** [trilinos/Trilinos#8684]
## Bug Report
CC: @trilinos/framework 

### Description

After the STK snapshot, there is an issue with the intel 19 dev->master build as shown here:

https://testing.sandia.gov/cdash/viewBuildError.php?buildid=8644855

I assigned this to @tasmith4 only because he filed the snapshot PR. Please reassign as appropriate.

**Comment by tasmith4** [comment]
Thanks @jwillenbring, I'll take a look.

FYI @trilinos/stk

**Comment by alanw0** [comment]
@jwillenbring Thanks Jim, we'll take care of this right away.

**Comment by tasmith4** [comment]
@jwillenbring we believe this is addressed by #8694
