### ISSUE TITLE
Framework:  Add OpenMP to Clang 10 build

### ISSUE THREAD

**Issue by jwillenbring** [trilinos/Trilinos#8693]
## Enhancement
@trilinos/framework 
@crtrott 

At a testbed meeting, it was suggested that we add OpenMP to a recent clang build using the llvm OpenMP runtime (not GCC). This will help prepare Trilinos for future architectures.

@crtrott, please specify which options you would specifically like added to the build.

**Comment by crtrott** [comment]
The SEMS clang supports OpenMP, so you just need to enable OpenMP (how do you do that in general: Trilinos_ENABLE_OPENMP or Kokkos_ENABLE_OPENMP?)

**Comment by wadeburgess** [comment]
https://sems-atlassian-son.sandia.gov/jira/projects/TRILINOSHD/queues/custom/122/TRILINOSHD-2

**Comment by wadeburgess** [comment]
Migrated to Trilinos Help Desk, so closing now.
