### ISSUE TITLE
ATDM:  Disabled Package for EMPIRE Still On

### ISSUE THREAD

**Issue by jmgate** [trilinos/Trilinos#8695]
Moving the conversation from email to here:

From @jmgate:

> @e10harvey, do you have any idea why builds on vortex would be ignoring [this change to Trilinos](https://github.com/trilinos/Trilinos/pull/8493) we pushed a week or so back to disable Tempus for EMPIRE.  Tempus looks to be disabled in other builds, e.g., [Deploy-develop-ascic-clang-opt-serial-static](https://do.sandia.gov/empire-jenkins/view/Deploy/job/Deploy-develop-ascic-clang-opt-serial-static/74/consoleFull) shows
>  
> 00:00:18.440  **Explicitly disabled packages** on input (by user or by default):  TrilinosFrameworkTests Gtest MiniTensor Domi Isorropia Pliris ShyLU_Node Komplex FEI TriKota Compadre Moertel ShyLU_DD ShyLU **Tempus** Stokhos ROL PyTrilinos NewPackage TrilinosCouplings Pike 21
>  
> But on vortex ([Deploy-develop-vortex-gnu-opt-openmp-static](https://do.sandia.gov/empire-jenkins/view/Deploy/job/Deploy-develop-vortex-gnu-opt-openmp-static/62/consoleFull)) we’re seeing
>  
> 00:01:22.708  -- **Setting Trilinos_ENABLE_Tempus=ON** because Piro has an optional dependence on Tempus
>  
> Any idea what might be going on?  Completely wiping everything out and starting from scratch didn’t help.

Then the response from @e10harvey:

> @jmgate, thank you for the detailed email. We are looking into a service desk or ticketing system to address requests like this going forward. For the time being, a GitHub issue is preferred over email.
>  
> From [Deploy-develop-vortex-gnu-opt-openmp-static](https://do.sandia.gov/empire-jenkins/view/Deploy/job/Deploy-develop-vortex-gnu-opt-openmp-static/62/consoleFull):
> 16:11:54  Explicitly disabled packages on input (by user or by default):  TrilinosFrameworkTests Gtest MiniTensor Domi Isorropia Pliris Komplex FEI TriKota Compadre Moertel ShyLU_DD ShyLU Stokhos PyTrilinos NewPackage TrilinosCouplings Pike 18
>  
> From [Deploy-develop-ascic-clang-opt-serial-static](https://do.sandia.gov/empire-jenkins/view/Deploy/job/Deploy-develop-ascic-clang-opt-serial-static/74/consoleFull):
> 10:22:07  Explicitly disabled packages on input (by user or by default):  TrilinosFrameworkTests Gtest MiniTensor Domi Isorropia Pliris ShyLU_Node Komplex FEI TriKota Compadre Moertel ShyLU_DD ShyLU **Tempus** Stokhos ROL PyTrilinos NewPackage TrilinosCouplings Pike 21
>  
> I see [the change from Trilinos](https://github.com/trilinos/Trilinos/pull/8493) on disk on vortex at https://do.sandia.gov/empire-jenkins/view/Deploy/job/Deploy-develop-vortex-gnu-opt-openmp-static/62/execution/node/8/ws/src/Trilinos/cmake/std/atdm/ATDMDisables.cmake/*view*/.
>  
> The problem is that the sems-rhel7 environment on the ascic machine does NOT set `ATDM_ENABLE_SPARC_SETTINGS`, resulting in the disable of Tempus being picked up while the vortex (ats2) environment sets `ATDM_CONFIG_ENABLE_SPARC_SETTINGS` by default.
>  
> `ATDM_CONFIG_ENABLE_SPARC_SETTINGS` was the default requested when the ats2 environment was requested. It seems bias to enable sparc settings by default but I guess there does have to be a default.
>  
> The fix is running `unset ATDM_CONFIG_ENABLE_SPARC_SETTINGS` after running `cmake/std/atdm/load-env.sh` (or `load_matching_env.sh`) AND before running `cmake`. Note that this configuration is not being tested on a nightly basis.
>  
> A longer-term solution would be to support an optional buildname keyword, like `sparc` or `empire`, to toggle which settings are used when invoking `load-env.sh`.

CC:  @jwillenbring

**Comment by jmgate** [comment]
Thanks for the information, @e10harvey.  I'll go ahead and unset that variable in our scripts after loading the environment and we should be good to go.

For my own edification, though, would you mind filling me in on how `cmake/std/atdm/apps/empire/EMPIRETrilinosPackagesList.cmake` gets triggered?  I tried grepping around like crazy before contacting you, but I'm at a loss.

**Comment by e10harvey** [comment]
> For my own edification, though, would you mind filling me in on how `cmake/std/atdm/apps/empire/EMPIRETrilinosPackagesList.cmake` gets triggered? I tried grepping around like crazy before contacting you, but I'm at a loss.

No problem. That CMake file gets pulled in through [EMPIRETrilinosEnables.cmake](https://github.com/trilinos/Trilinos/blob/master/cmake/std/atdm/apps/empire/EMPIRETrilinosEnables.cmake) which is passed into cmake like this:
```bash
          cmake \\
            -D Trilinos_CONFIGURE_OPTIONS_FILE:STRING=
               cmake/std/atdm/ATDMDevEnv.cmake,
               cmake/std/atdm/apps/empire/EMPIRETrilinosEnables.cmake \\
```

**Comment by jmgate** [comment]
I've made the necessary changes to our build scripts, but I'll keep this open till we see the jobs run successfully tonight and then I'll close.
