### ISSUE TITLE
STK: broken Albany builds due to boost file not found by STK

### ISSUE THREAD

**Issue by ikalash** [trilinos/Trilinos#8697]
A bunch of Albany nightlies are failing with the following error: 

``
/.../repos/Trilinos/packages/stk/stk_util/stk_util/util/ParameterList.cpp(40): catastrophic error: cannot open source file "boost/type_index/type_index_facade.hpp"
``
https://sems-cdash-son.sandia.gov/cdash/viewBuildError.php?buildid=12066 

Could someone please have a look at this?  Perhaps a newer version of boost is needed now?

@trilinos/stk

**Comment by alanw0** [comment]
@ikalash we'll take a look to see what's wrong.

**Comment by tasmith4** [comment]
@ikalash turns out we didn't even need that include -- sorry about that!  PR #8700 should fix this

**Comment by ikalash** [comment]
Thanks a lot!  I will close this issue if the nightlies are clean tomorrow morning.

**Comment by ikalash** [comment]
I can confirm that this has been resolved.  Thanks!
