### ISSUE TITLE
Address handling of CMAKE_BUILD_TYPE, -O0 for debug builds, etc.

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#87]
It seems there is some confusion/unhappiness with the way that Trilinos (through TriBITS) is dealing with `CMAKE_BUILD_TYPE` and the insertion or not of -O0 for "Debug" (or "DEBUG") builds.

For the way the CMake and TriBITS manipulates compiler flags, see ["Selecting compiler and linker options"](https://trilinos.org/docs/files/TrilinosBuildReference.html#selecting-compiler-and-linker-options) in the [Trilinos Build Reference](https://trilinos.org/docs/files/TrilinosBuildReference.html).

On one hand, we want TriBITS (and therefore Trilinos) to keep with raw CMake behavior intact as much as possible (so that people who know CMake already will know how to work with Trilinos), but that would mean that -O0 would **not** show up in "Debug" builds.  On the other hand, we should override default raw CMake behavior when raw CMake behavior it is actually counter-intuitive (in which case you would add -O0 to "Debug" builds).  But then that gets TriBITS into the business of knowing how to set compiler flags for all compilers and on platforms.  Do we want to step on the CMake's communities ties like this?  Do we really want to own this?

This Issue Ticket is to log the discussion of this topic and potentially come up with some action to address this in a way that makes people (by some definition) happy.

**Tasks:**
1. Add `-DNDEBUG` to C and C++ RELEASE compiler flags by default for GCC (see [below](https://github.com/trilinos/Trilinos/issues/87#issuecomment-232754822)) [Done]
2. Add `-O0` to C, C++, and Fortran debug flags for Intel builds ...

**Comment by jwillenbring** [comment]
@bmpersc @maherou
Just wanted to get some potentially interested people on this ticket.

**Comment by bartlettroscoe** [comment]
Here is an email thread that motivated this GitHub Issue ticket:

----

**Comment by bartlettroscoe** [comment]
The origin of TriBITS adding -O0 to debug builds for GCC goes back to at least:

```
$ cd Trilinos/
$ git log-short --name-status -1 150caa92f -- cmake/
150caa9 "SUMMARY: Adding general framework-level support for TPLs."
Author: Roscoe A. Bartlett <rabartl@sandia.gov>
Date:   Wed Dec 17 18:56:39 2008 +0000 (7 years ago)

M       cmake/TODO
M       cmake/TrilinosCMakeQuickstart.txt
M       cmake/TrilinosProbeEnv.cmake
A       cmake/TrilinosSetupStrongCompileWarnings.cmake
```

I am feeling old (and TriBITS feels old).

**Comment by nmhamster** [comment]
Ross, thank you for creating this as an issue and your feedback on the mechanisms in both CMake and TriBITS, I have to say this level of information is extremely helpful in understanding the complexities involved.

As more of a support to users in the codesign space than a developer of Trilinos, I want to advocate for sensible expected behavior in the case of the DEBUG and RELEASE builds. To me, when I select DEBUG I want Trilinos configured for the maximum debuggability within a debugger. That would lend itself to a -O0 -g setting for compiler flags. When I select RELEASE I am confident that the code works and I want the best performance/optimization that is possible = -O3 -NDEBUG. This seems to correlate with how most developers expect the build to function. Having TriBITS set these seems to fit with the idea of making the configuration less error prone and support a common development workflow.

Now, personally, I want to override compiler flags for optimization and debugging by setting the C++/C/Fortran flags. Why? because in cross compile environments I want to be able to turn on platform specific optimization etc in situations where I (think) I know better than CMake/TriBITS. I think the current proposal would mean I use the NONE build type and then set my own flags? This feels a bit clunky but if we can only get the main changes above it would be a good step forward.

**Comment by bartlettroscoe** [comment]
> As more of a support to users in the codesign space than a developer of Trilinos, I want to advocate for sensible expected behavior in the case of the DEBUG and RELEASE builds. To me, when I select DEBUG I want Trilinos configured for the maximum debuggability within a debugger. That would lend itself to a -O0 -g setting for compiler flags. When I select RELEASE I am confident that the code works and I want the best performance/optimization that is possible = -O3 -NDEBUG. This seems to correlate with how most developers expect the build to function. Having TriBITS set these seems to fit with the idea of making the configuration less error prone and support a common development workflow.

Seems reasonable to me.  I will ask the CMake leads (Bill Hoffman and Brad King) why CMake does not set -O0 on debug builds.  But in the meantime, we should likely just leave the default CMake flags in place and just append -O0 for the debug builds.  We will discuss this tomorrow at the Trilinos Leaders Meeting.

> Now, personally, I want to override compiler flags for optimization and debugging by setting the C++/C/Fortran flags. Why? because in cross compile environments I want to be able to turn on platform specific optimization etc in situations where I (think) I know better than CMake/TriBITS. I think the current proposal would mean I use the NONE build type and then set my own flags? This feels a bit clunky but if we can only get the main changes above it would be a good step forward.

Perfectly understandable.  That is what I would do when I wanted to know for sure what flags were being set.  I think the CMAKE_BUILD_TYPE is supposed to give reasonable values for the particular compiler you are using.  It saves you from having to dig into the compiler documentation for the details of what exact flags need to be set for these basic types of builds.

**Comment by bmpersc** [comment]
Could we allow Tribits to by default just do what Cmake would do for the given build type, but then allow a project to override this behavior through the CallbackSetupExtraOptions.cmake or a similar mechanism? That way Tribits will behave as people would expect, but a project can override and it will be on the project to support compiler options and take responsibility for confused users.

**Comment by maherou** [comment]
I think we want  the TriBITS definition of DEBUG to be the same as Cmake, even if it is strange.  In general I think we should have TriBITS behave like Cmake when it’s doing the same thing.  
I think we should in general encourage users to explicitly define the compiler arguments.  Then there is no ambiguity.  If they use DEBUG, we could print the details of the DEBUG definition in the output, so that people know.

**Comment by bmpersc** [comment]
We could require users to explicitly set the CMAKE_<lang>_FLAGS_<build type> if they want something other than the defaults. This is a bit of a doubled edged sword though. The default won't be surprising to those who know cmake well. However, users that don't know cmake could easily be surprised that the default for debug does not include -O0, as was the case for the developers that initiated this discussion.

**Comment by bartlettroscoe** [comment]
The issue is that there are cases where raw CMake is inconsistent and surprising to people in the CSE community used to things like autotools.  One example I mentioned above is the built-in FindMPI.cmake module that tries to unwrap the MPI compiler wrappers.  That is *not* how 95% of the builds for MPI work and that has (or had) major portability problems.  Another example is doing a serial build of a project, where [raw CMake looks for the `cc` compiler first](https://trilinos.org/docs/files/TrilinosBuildReference.html#selecting-compiler-and-linker-options).  So if you have a newer GCC installation in your path then it will not use those updated GCC compilers by default.  That confuses a *lot* of people (including me everytime it happens).  TriBITS right now does not mess with this but for goodness sake, I think it should (i.e. find `gcc` first for the C compiler if the user did not specify anything).

So the philosophy has been that TriBITS (and therefore Trilinos) should be consistent with raw CMake as much as possible but to make changes in cases where raw CMake behavior is crazy or unexpected (and there is more of that than what you would think).

**Comment by bartlettroscoe** [comment]
> Could we allow Tribits to by default just do what Cmake would do for the given build type, but then allow a project to override this behavior through the CallbackSetupExtraOptions.cmake or a similar mechanism? That way Tribits will behave as people would expect, but a project can override and it will be on the project to support compiler options and take responsibility for confused users.

Most of the other projects that use TriBITS just want to follow the conventions of Trilinos (since most of them have to use Trilinos anyway).

**Comment by dridzal** [comment]
I absolutely agree with the comment


TriBITS (and therefore Trilinos) should be consistent with raw CMake as much as possible but to make changes in cases where raw CMake behavior is unexpected


This additional layer of "protection" has helped the @trilinos/rol team turn around builds with customers more quickly.  I would prefer not to have to correct default CMake behavior in customer interactions.  The issue is really with CMake, not TriBITS.


Denis


________________________________

**Comment by nmhamster** [comment]
Are we able to utilize our relationship with the Kitware folks to have a discussion about what may be possible to change in this situation? I agree with Ross's previous comment that there is likely to be push back against changing this but it would be good to hear the initial justification that led to this design. Agreed that the issue is CMake (not TriBITS or Trilinos) but the practical reality here is that a "DEBUG" build cannot actually be debugged in many cases and that, at least to me, seems to be counter intuitive and a non-productive way to design a build system.

**Comment by bartlettroscoe** [comment]
I contacted the guys at Kitware and asked them to comment to this GitHub Issue ticket.

**Comment by bartlettroscoe** [comment]
I have also asked the [IDEAS Productivity Team](https://ideas-productivity.org/) if a "debug build" should have -O0 or not.  The [xSDK configure standard](https://docs.google.com/document/d/18028D6nsuhIrCvJnX6c07r8m_Np4SH-aGXMX4svMs1w/edit#bookmark=id.w1dwut61itqe) is currently silent on this.

**Comment by bartlettroscoe** [comment]
FYI: Turns out TriBITS allows the CamelCase spelling for `Debug`, `Release`, `RelWithDebInfo`, and `MinSizeRel` as well as `None`.  If the user passes in "empty", a default is set (usually 'Debug').  The raw CMake default is empty "".  I will add this documentation to the build reference guide.  I think having the default be Debug or Release makes more sense than defaulting to nothing, at least in development mode.

**Comment by bartlettroscoe** [comment]
So I am not sure what to do with this Issue at this point.  It has been sitting in "Ready" for a long time (last comment more than a month ago).  Is there a consensus on this?  I don't really personally care one way or the other.  Perhaps we should just take a vote somehow of the Trilinos developer and user community?

**Comment by nmhamster** [comment]
Did you get anything back from Kitware yet?

**Comment by bartlettroscoe** [comment]
Kitware (i.e. Brad King) has not responded.  My guess is that they will not change this so we need to decide on our own how to handle this.

**Comment by bartlettroscoe** [comment]
The response from Kitware is below.  I was wrong, they are willing to change this.  Should we ask them to add `-O0` to the `CMAKE_<LANG>_FLAGS_DEBUG` variables when the compiler is Intel?  But note that will only impact CMake 3.6.0 at the earliest.  In the meantime, do we want to just override `CMAKE_<LANG>_FLAGS_DEBUG` to add `-O0`?

Brad King, the lead developer of CMake seems to think this is not that big of a deal.  And if people want to know exactly what compiler flags are set, they should just set them manually.

Therefore, I propose the following:

1. Ask Kitware to add `-O0` to `CMAKE_<LANG>_FLAGS_DEBUG` for future versions of CMake
2. Make TriBITS override `CMAKE_<LANG>_FLAGS_DEBUG` by default to append `-O0` for Intel compilers (not needed for GCC compilers, right?).

Any objections?

> -----Original Message-----
> From: Brad King [mailto:brad.king@kitware.com]
> Sent: Monday, March 07, 2016 10:30 AM
> To: Bartlett, Roscoe A
> Cc: Bill Hoffman
> Subject: [EXTERNAL] Re: -O0 with CMAKE_<LANG>_FLAGS_Debug?
> 
> On 02/29/2016 02:03 PM, Bartlett, Roscoe A wrote:
> > why does the standard CMake  “Debug” build type not include -O0 in
> > addition to -g in the variable CMAKE_<LANG>_FLAGS_Debug?
> 
> I don't recall any specific reason it was done this way originally.
> 
> > It seems that when you build C++ code with the Intel compiler, that -g
> > by itself (with the standard optimization level) does not produce
> > binary code that allows for full debugging.
> [snip]
> > Some people want to update TriBITS (and therefore Trilinos) to always
> > add -O0 to debug builds by default and some want to just stick with
> > the default CMake behavior.  And some some of these people want CMake
> > to change it default to add -O0 to debug builds by default (which I am
> > guessing can’t happen due to backward compatibility constraints).
> 
> I'm not opposed to changing the default used for the Intel compiler specifically.
> While technically incompatible it shouldn't affect much.  Anyone that needs
> deep control of their flags in scripts should be specifying them all explicitly
> anyway.
> 
> -Brad

**Comment by nmhamster** [comment]
Sounds a good start to me.

**Comment by jwillenbring** [comment]
@mwglass asked about the status of this today.

**Comment by jwillenbring** [comment]
Mike G. requested a document that describes what to do before a full solution is implemented. This is currently unclear.

**Comment by bartlettroscoe** [comment]
> @mwglass asked about the status of this today.

My opinion was given in the [above comment](https://github.com/trilinos/Trilinos/issues/87#issuecomment-193413034).  Which was:

1. Ask Kitware to add `-O0` to `CMAKE_<LANG>_FLAGS_DEBUG` for future versions of CMake
2. Make TriBITS override `CMAKE_<LANG>_FLAGS_DEBUG` by default to append `-O0` for Intel compilers (not needed for GCC compilers, right?).

I think the second point ran contrary to Make Heroux's opinion.  I added an item on this to the Trilinos leaders meeting to get agreement on this.

> Mike G. requested a document that describes what to do before a full solution is implemented. This is currently unclear. For example, on the Trilinos website.

Controlling compiler options has been documented (for a couple years) here:

https://trilinos.org/docs/files/TrilinosBuildReference.html#selecting-compiler-and-linker-options

and more specifically here:

https://trilinos.org/docs/files/TrilinosBuildReference.html#overriding-cmake-build-type-debug-release-compiler-options

@mwglass, do you want specific documentation of the fact that Intel does not create debuggable executables by default or how to add -O0 to the debug build flags?

**Comment by bartlettroscoe** [comment]
At the Trilinos leaders meeting today, we made the decision to go with the above plan.

My one question is if we should add `-O0` to `CMAKE_<LANG>_FLAGS_DEBUG` even for release mode (i.e. `-DTrilinos_ENABLE_DEVELOPMENT_MODE=ON`).  I think that the answer should be "yes".  If people want a fast build, then they should be using a release build.

**Comment by bartlettroscoe** [comment]
At the Trilinos leaders meeting today, we made the decision to go with the above plan.

My one question is if we should add `-O0` to `CMAKE_<LANG>_FLAGS_DEBUG` even for release mode (i.e. `-DTrilinos_ENABLE_DEVELOPMENT_MODE=ON`).  I think that the answer should be "yes".  If people want a fast build, then they should be using a release build.

**Comment by bartlettroscoe** [comment]
Seems that TriBITS not setting `-DNDEBUG` for release builds is causing the failing test `STKUnit_tests_util_parallel_UnitTest_MPI_4` (#441)  (see native STK Trac ticket `#15120`).  Therefore, I will see if setting `-DNDEBUG` in the release build flags fixes this.

**Comment by bartlettroscoe** [comment]
The `-DNDEBUG` flag has been added to all `CMAKE_BUILD_TYPE=RELEASE` builds with GCC again by default.  This was done in the TriBITS to Trilinos snapshot commit 69c2781d7c1bea296e753455d12e11cc0f84c327:

```
Automatic snapshot commit from tribits at 0a17720

Origin repo remote tracking branch: 'github/master'
Origin repo remote repo URL: 'github = git@github.com:TriBITSPub/TriBITS.git'

At commit:

commit 733f1058f56e1174311eb19c17928ff7ed790d8c
Author:  Roscoe A. Bartlett <rabartl@sandia.gov>
Date:    Wed Jul 13 20:20:34 2016 -0600
Summary: Add -DNDEBUG to default RELEASE compiler flags, set Fortran flags
```

**Comment by bartlettroscoe** [comment]
The last thing to do is to override the default flags when building with Intel in addition to GCC.  I would have done that as part of my recent push  but the Intel compiler would not run on the machine `muir` I was working on so I could not test it.  I need to get my own Linux machine.
