### ISSUE TITLE
Link to Thyra Dev Doxygen is broken

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#871]
**CC:** @trilinos/framework 

**Description:**

The link to the "Thyra Dev Doxygen" from:

* https://trilinos.org/packages/thyra/thyra-doxygen/

is broken.  It tries to take you to:

* http://trilinos.sandia.gov/packages/docs/dev/packages/thyra/doc/html/index.html

but that just takes you back to:

* https://trilinos.org/

**Comment by jwillenbring** [comment]
@bartlettroscoe thanks for pointing this out. There was a mistake in the custom sidebar for child package pages. Please reopen if you see additional issues.
