### ISSUE TITLE
Kokkos: add cmake check for gcc version now that c++14 is required

### ISSUE THREAD

**Issue by jhux2** [trilinos/Trilinos#8720]
## Enhancement
@trilinos/kokkos

There are at least a couple issues (#8710 and #8673), as well as reports on the Kokkos slack channel, all related I think to the c++14 change.  When someone uses the intel compiler, they need to make sure that a new enough GCC is being used.

Can Kokkos add a cmake check to make sure that a recent enough GCC is being used?

**Comment by jjellio** [comment]
Jonathan,

This may work.

```
jjellio@~ $ ldd $(realpath -- "$(which icpc)" )
	linux-vdso.so.1 (0x00007fff07bc6000)
	libstdc++.so.6 => /opt/gcc/8.3.0/snos/lib64/libstdc++.so.6 (0x00007f81ba60f000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f81ba40b000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f81ba1ec000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f81b9eb4000)
	libgcc_s.so.1 => /opt/gcc/8.3.0/snos/lib64/libgcc_s.so.1 (0x00007f81b9c9c000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f81b98e1000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f81ba998000)
# now check for the GCC in the path
jjellio@~ $ which gcc
/opt/gcc/8.3.0/bin/gcc
# okay, remove that path, and we can see that atleast on this machine, Intel added rpath for the proper GCC to icpc
jjellio@~ $ path_remove /opt/gcc/8.3.0/bin
jjellio@mutrino ~ $ which gcc
/usr/bin/gcc
# now check the ldd again, and we see icpc still points to gcc 8.3
jjellio@~ $ ldd $(realpath -- "$(which icpc)" )
	linux-vdso.so.1 (0x00007fff07bc6000)
	libstdc++.so.6 => /opt/gcc/8.3.0/snos/lib64/libstdc++.so.6 (0x00007f81ba60f000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f81ba40b000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f81ba1ec000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f81b9eb4000)
	libgcc_s.so.1 => /opt/gcc/8.3.0/snos/lib64/libgcc_s.so.1 (0x00007f81b9c9c000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f81b98e1000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f81ba998000)
```

This would get ugly in CMake, (and fail if Intel used static libs!)

I tried `strings` on icpc, and unfortunately that was zero help.

It could be we could embed commands like I show about w/ldd into Trilinos' CMake. Maybe do a check compile w/C++14 (pick something like the issue that failed).  If it fails, then print out the commands above and exit (recommending the user investigate which GCC intel should be using)

**Comment by kddevin** [comment]
@trilinos/framework

**Comment by jhux2** [comment]
@ndellingwood reports in https://github.com/trilinos/Trilinos/issues/8673#issuecomment-772147025 that gcc 5.3 or newer is sufficient.

**Comment by jjellio** [comment]
I believe the general problem is the standard headers that get included are a lesser standard than the actual library linked. (as in icpc is finding a good libc++, but the included headers are from the older one).  Adding a trycompile w/a function only in a given standard would catch this - but I think it needs to be a template metaprogramming function - not something that will be found in the library (symbol). This bit me on Mutrino they they went from Intel 16 to 17. (I think). It's an obscure problem =\

**Comment by jhux2** [comment]
James, this is obscure for sure.  But since it’s now come up at least 3 different times, I think an automated check, even if it’s not bulletproof, is in order. Seems like Kokkos is the right place, as well. @crtrott

**Comment by crtrott** [comment]
You should add these requests in the kokkos github.

**Comment by jhux2** [comment]
Migrating this issue to Kokkos.

**Comment by dridzal** [comment]
It looks like the latest/default SEMS Intel compiler installed on Sandia's HPC platforms (19.0.5) suffers from the same issue.  My guess is this is due to the use of old headers in the environment (not Intel).  I've reported the problem to SEMS.  Are there workarounds?

```
Trilinos/packages/kokkos/core/src/impl/Kokkos_Utilities.hpp(409): error: namespace "std" has no member "remove_cv_t"
    using type = std::remove_cv_t<std::remove_reference_t<T>>;
```
