### ISSUE TITLE
ATDM:  cts1empire not working on eclipse

### ISSUE THREAD

**Issue by jmgate** [trilinos/Trilinos#8722]
## Question
@e10harvey, about a week ago (I think it was 2/3 or 4) our deploys of Trilinos on eclipse started failing with the following error:
```
00:02:57.481  Hostname 'eclipse-login1' matches known ATDM host 'eclipse-login1' and system 'cts1empire'
00:02:57.481  Setting compiler and build options for build-name 'Deploy-develop-eclipse-intel-opt-openmp-static'
00:02:57.481  Using cts1empire toss3 compiler stack INTEL-18.0.2_OPENMPI-4.0.1 to build RELEASE code with Kokkos node type OPENMP
00:03:01.711  ninja -C .  -j 16 ./all
00:03:01.711  ninja: Entering directory `.'
00:03:03.213  ninja: error: '/projects/sparc/tpls/cts1-bdw/netcdf-4.7.0/24baa07a3fa1ff9dbc8e70dc591ebbdec56783b2/cts1-bdw_intel-19.0.5_openmpi-4.0.1/lib/libnetcdf.a', needed by 'packages/seacas/libraries/ioss/src/main/io_shell', missing and no known rule to make it
00:03:03.213  make: *** [all] Error 1
00:03:03.213  make: Target `default_target' not remade because of errors.
```

I tried selecting the `intel-19` environment from `cts1` instead of `cts1empire`, but ran into more or less the same thing:
```
Hostname 'eclipse-login7' matches known ATDM host 'eclipse-login7' and system 'cts1'
Setting compiler and build options for build-name 'intel-19-opt-openmp-static'
Using cts1 toss3 compiler stack INTEL-19.0.4_OPENMPI-4.0.3 to build RELEASE code with Kokkos node type OPENMP
ninja -C .  -j 16 ./all
ninja: Entering directory `.'
ninja: error: '/projects/sparc/tpls/cts1-bdw/netcdf-4.7.0/1710af73d9e61434ec053613ec3764075718a9a5/cts1-bdw_intel-19.0.4_openmpi-4.0.3/lib/libnetcdf.a', needed by 'packages/seacas/libraries/ioss/src/main/io_modify', missing and no known rule to make it
make: *** [/home/jmgate/urgh/trilinos/src/Trilinos/cmake/tribits/core/utils/NinjaMakefileCommon.make:20: all] Error 1
make: Target 'default_target' not remade because of errors.
```

Are other builds on eclipse running into similar things?  Do we need to look into updating the `cts1` environment to use the latest `sparc-dev` module?  It sounds like EMPIRE has hacked around the Intel 19 compiler bug, so we may be able to ditch `cts1empire` and bring `cts1` up to date with whatever SPARC is using now.  Maybe.

**Comment by bathmatt** [comment]
If you take the second one (intel19) and change lib/ to lib64 this should go through

**Comment by bathmatt** [comment]
```
-rw-r--r-- 1 sparc wg-aero-usr 3560136 Mar 18  2020 /projects/sparc/tpls/cts1-bdw/netcdf-4.7.0/24baa07a3fa1ff9dbc8e70dc591ebbdec56783b2/cts1-bdw_intel-19.0.4_openmpi-4.0.3/lib64/libnetcdf.a
```

**Comment by e10harvey** [comment]
> Are other builds on eclipse running into similar things?

Not that I am aware of. Looking at https://testing-dev.sandia.gov/cdash/index.php?project=Trilinos&filtercount=1&showfilters=1&field1=buildname&compare1=63&value1=cts1, I see that the cts1 builds are running OK and that SEACAS is enabled but cts1empire is not picking up `sparc-dev` modules updates. If cts1empire is still needed, this can be fixed.


> Do we need to look into updating the `cts1` environment to use the latest `sparc-dev` module?

The `cts1` environment uses sparc-dev/intel-19.0.4_openmpi-4.0.3 but the `cts1empire` environment uses the `cts1-bdw_intel-19.0.5_openmpi-4.0.1` sparc TPLs with intel/18.

**Comment by jmgate** [comment]
@bathmatt, I'll throw up a PR when I've verified that'll do the trick.  Looks like it will.
