### ISSUE TITLE
Kokkos: TeamPolicy<Cuda> team size is too large

### ISSUE THREAD

**Issue by jewatkins** [trilinos/Trilinos#8727]
## Bug Report
@trilinos/kokkos
I will update the issue with other packages if we're able to narrow it down.

### Description
A couple of performance tests are failing in Albany in our GPU runs on weaver:
https://sems-cdash-son.sandia.gov/cdash/viewTest.php?onlyfailed&buildid=12122

Here is the error message:
```
 Kokkos::TeamPolicy< Cuda > the team size is too large. Team size x vector length must be smaller than 1024.
 Traceback functionality not available
```
and the relevant issue in Albany is here: https://github.com/SNLComputation/Albany/issues/661

I've narrowed down the issue to where Albany master does not work with kokkos-promotion-3.3: https://github.com/trilinos/Trilinos/commit/e4f6782142446ec47250b7d0f9b8c125f1e59bdd
but it works with the previous commit: https://github.com/trilinos/Trilinos/commit/7b95b7c396a45f4df4d4f15a7cc6fc08357d9229

Albany doesn't currently use TeamPolicy so my guess is that it is a trilinos package causing the issue. Unfortunately, I wasn't able to narrow down the package or kernel with kokkos tools. @ndellingwood do you have any ideas of what might have caused this or maybe you know of a way I could narrow it down?

### Steps to Reproduce
1. SHA1:  https://github.com/trilinos/Trilinos/commit/e4f6782142446ec47250b7d0f9b8c125f1e59bdd
1. Weaver modules: https://github.com/SNLComputation/Albany/blob/master/doc/dashboards/weaver.sandia.gov/weaver_modules_cuda.sh
1. Trilinos configure script: https://github.com/SNLComputation/Albany/blob/master/doc/dashboards/weaver.sandia.gov/do-cmake-weaver-trilinos
1. Albany configure script: can provide if needed
1. Input deck:  can provide if needed

**Comment by jewatkins** [comment]
Also, this seems to happen only for the larger cases. The nightly tests don't seem to catch the issue and there are some smaller cases which work fine.

**Comment by jhux2** [comment]
@trilinos/kokkos @crtrott @davidpoliakoff

**Comment by ccober6** [comment]
@crtrott @DavidPoliakoff  Do you know the status of this? Have a question today at the SART meeting about it.  Thanks Curt

**Comment by DavidPoliakoff** [comment]
Hey @ccober6 , I've not yet taken a look at this, apologies. I'll try to free up some time tomorrow on this

**Comment by ccober6** [comment]
Great! @ikalash was asking about the status as Albany performance tests are dependent on it.

**Comment by alanw0** [comment]
Tagging @sayerhs @tasmit @overfelt also.

**Comment by DavidPoliakoff** [comment]
Sorry, I missed this yesterday, just getting a Trilinos build going. Could somebody email me the Albany configure details? Unless we have a Trilinos reproducer

**Comment by DavidPoliakoff** [comment]
Also, what's `nvcc_wrapper_volta`?

**Comment by jewatkins** [comment]
> Sorry, I missed this yesterday, just getting a Trilinos build going. Could somebody email me the Albany configure details? Unless we have a Trilinos reproducer

I put everything on weaver here: `/home/projects/albany/forDavid`
Let me know if you're having issues accessing. Edit `do-cmake-albany-cuda-sfad4` to point to your trilinos install dir and the submission scripts need to be edited to point to the albany build directory. Run `submit_populate.sh` first, that should work fine. `submit.sh` should give the failure.

**Comment by jewatkins** [comment]
> Also, what's `nvcc_wrapper_volta`?

We have our own `nvcc_wrapper` here: https://github.com/SNLComputation/Albany/blob/master/doc/dashboards/weaver.sandia.gov/nvcc_wrapper_volta
which we update when needed. That's sometimes led to issues... Maybe I should check if it's up-to-date.

**Comment by DavidPoliakoff** [comment]
@jewatkins : thanks! Just got the Trilinos build going, will try the rest shortly. Didn't look like `nvcc_wrapper_volta` caused any grief

**Comment by DavidPoliakoff** [comment]
Hey all, sorry for the delay, I modified Kokkos to show what kernel it gets that error from (in a hacky way, we need a better one). But briefly, every time we run a kernel, I save off its name, and now Kokkos prints that name before the error of a too large team size. Error I'm getting says

```
Ran into a team size problem with kernel KokkosKernels::Common::FillReverseMap
Kokkos::TeamPolicy< Cuda > the team size is too large. Team size x vector length must be smaller than 1024.
```

I'm game to dig in to that kernel, but there are much wiser minds than mine on the Kernels team, we should decide whether we want me to dig in, or somebody from kernels

**Comment by sayerhs** [comment]
@lucbv @srajama1 Hope you guys are following this discussion. This is affecting [ExaWind/Nalu-Wind](https://my.cdash.org/test/25424874) also.

**Comment by jewatkins** [comment]
@sayerhs that stacktrace confirms my suspicions that it might be MTGS in ifpack2. Do you mind sharing how you were able to get it?

**Comment by sayerhs** [comment]
@jewatkins You can look at the full [build notes here](https://my.cdash.org/build/1969569/notes). I don't think we are doing anything special other than building with `RelWithDebInfo`. I am cc-ing @jrood-nrel who maintains [nalu-wind nightly testing](https://github.com/Exawind/build-test) in case I misspoke.

**Comment by jewatkins** [comment]
> @jewatkins You can look at the full [build notes here](https://my.cdash.org/build/1969569/notes). I don't think we are doing anything special other than building with `RelWithDebInfo`. I am cc-ing @jrood-nrel who maintains [nalu-wind nightly testing](https://github.com/Exawind/build-test) in case I misspoke.

Interesting, it looks like it might have something to do with MPT. I'll try RelWithDebInfo but maybe it's not reproducible on weaver. Thanks.

**Comment by jrood-nrel** [comment]
MPT just puts a prefix on output from ranks. I don't think our case has anything unique to MPT.

**Comment by jewatkins** [comment]
FYI, we just ran into this issue as well in sparc when trying MTGS

**Comment by brian-kelley** [comment]
Sorry everyone, this bug got fixed in KokkosKernels develop but missed the 3.3.1 promotion by a few days. I made the fake TeamPolicy (not to execute anything, but to ask Kokkos heuristics about the correct team size) with too many threads, but the TeamPolicy constructor is where that gets checked.

I'm patching in https://github.com/kokkos/kokkos-kernels/pull/872 to Trilinos now.

**Comment by DavidPoliakoff** [comment]
Just confirming, we're the same stacktrace, so fixing one is fixing both

**Comment by brian-kelley** [comment]
@jewatkins @sayerhs OK, the patch was merged into develop. Can you verify that it fixed the issue?

**Comment by jewatkins** [comment]
I've been testing this manually and it works so I'm okay with closing this. Thanks Brian and all!
