### ISSUE TITLE
Framework:  Syntax error in cmake file for experimental Cuda build

### ISSUE THREAD

**Issue by tasmith4** [trilinos/Trilinos#8729]
@ZUUL42 @trilinos/framework @alanw0 

FYI, a syntax error from #8716 seems to be breaking the configure for the experimental Cuda builds in the dev->master promotion (#8723, https://testing.sandia.gov/cdash/build/8685164/configure).

**Comment by ZUUL42** [comment]
I'm aware of the issue and am putting together an update to fix it.

**Comment by tasmith4** [comment]
fixed by #8735
