### ISSUE TITLE
Seacas: Trilinos Seacas Fortran settings are out of sync with Seacas repo

### ISSUE THREAD

**Issue by jjellio** [trilinos/Trilinos#8741]
## Bug Report
@trilinos/seacas 

### Description
I've been rebuilding on El Cap prep systems and noticed SEACAS packages giving Fortran compile errors.  The errors are are from `FortranSettings.cmake`, which in Trilinos/seacas are defaulting to `-r8 -i8`.  I was going to submit a patch that provides flags for `crayftn`, but noticed the upstream SEACAS repo has this fixed (since summer 2020).

Can FortranSettings.cmake get updated in Trilinos/seacas?
https://github.com/gsjaardema/seacas/blob/master/cmake/FortranSettings.cmake

**Comment by gsjaardema** [comment]
This should be working now.
