### ISSUE TITLE
Shylu: Re-enable FROSch + MueLu tests

### ISSUE THREAD

**Issue by mayrmt** [trilinos/Trilinos#8762]
## Enhancement
@trilinos/shylu 
@searhein 

Re-enable these tests:

- [ ] `test_thyra_xpetra_laplace_TLP_GDSW_MUELU_DIM2_DPN2_ORD1_EPETRA`
- [ ] `test_thyra_xpetra_laplace_TLP_GDSW_MUELU_DIM2_DPN2_ORD1_TPETRA`

**Comment by mayrmt** [comment]
Changing
```
MueLuHierarchy_->GetLevel(0)->Set("A", K_);
```
to 
```
MueLuHierarchy_->GetLevel(0)->Set("A", Teuchos::rcp_const_cast<XMatrix>(K_));
```
in `packages/shylu/shylu_dd/frosch/src/Tools/FROSch_SubdomainSolver_def.hpp` fixes the problem. However, not a nice solution! 

@searhein Any idea where this originates from? You were the last to change the matrix type of `K_` in 4c28005cdd13.

**Comment by mayrmt** [comment]
@searhein Seems to be a MueLu problem. See #6390.

**Comment by mayrmt** [comment]
Some more `#ifdef` to resolve, but I'm getting there...

**Comment by searhein** [comment]
@mayrmt Thanks. I think it reasonable to make the system matrix `const` since it should not be modified by the solver. I hope there is a way to get this to work with `MueLu`. Let me know. I will also start looking into this!

**Comment by mayrmt** [comment]
@searhein I agree, that one should be able to pass a `const` matrix. MueLu is aware of that, cf. #6390. There's currently no timeline on resolving that, though. For now, I created #8771 to circumvent the problem by removing the `const` qualifier.

**Comment by mayrmt** [comment]
#8711 has been merged to `develop`. Closing.
