### ISSUE TITLE
ATDM:  Stria Env Broken

### ISSUE THREAD

**Issue by jmgate** [trilinos/Trilinos#8763]
## Bug Report
@e10harvey 

### Description
Our deploy to stria last night ran into the following problem:
```
Hostname 'stria-login1' matches known ATDM host 'stria-login1' and system 'sems-rhel7'
Setting compiler and build options for build-name 'Deploy-develop-stria-arm-20-opt-openmp-static'

***
*** ERROR: A compiler was not specified in 'Deploy-develop-stria-arm-20-opt-openmp-static'!
***
Using SEMS RHEL7 compiler stack GNU-7.2.0 to build RELEASE code with Kokkos node type OPENMP
NOTE: SEMS modules not defined, loading their definition!
    ERROR loading module sems-git/2.10.1 
    Module points to path
    /projects/sems/install/rhel7-x86_64/sems/utility/git/2.10.1 which does not
    exist 
```

Did someone change the logic in determining what system you were on recently?

### Steps to Reproduce
1. Log on to stria.
2. `source /projects/empire/trilinos-src/cmake/std/atdm/load-env.sh Deploy-develop-stria-arm-20-opt-openmp-static`

**Comment by bathmatt** [comment]
It doesn't look like a change in trilinos going back to sept doesn't resolve this issue.  Probably a system change

**Comment by e10harvey** [comment]
> Did someone change the logic in determining what system you were on recently?

No. It looks like there was a DST completed yesterday morning. I just tried to reproduce using the tip of trilinos develop via:
```
source /projects/empire/trilinos-src/cmake/std/atdm/load-env.sh Deploy-develop-stria-arm-20-opt-openmp-static
Hostname 'foobar' batched known ATDM host 'foobar' and system 'van1-tx2'
Setting compiler and build options for build-name 'Deploy-develop-stria-arm-20-opt-openmp-static'
Using ARM ATSE compiler stack ARM-20.0_OPENMPI-4.0.2 to build RELEASE code with Kokkos node type OPENMP

The following have been reloaded with a version change:
  1) arm/20.1 => arm/20.0


The following have been reloaded with a version change:
  1) armpl/20.1.0 => armpl/20.0.0


The following have been reloaded with a version change:
  1) cmake/3.12.2 => cmake/3.17.1
```

@jmgate: Is this the output you expect?

**Comment by e10harvey** [comment]
@ZUUL42, FYI for triaging today.

**Comment by bathmatt** [comment]
Here's a patch
```
[mbetten@stria-login1 atdm]$ git diff
diff --git a/cmake/std/atdm/utils/get_known_system_info.sh b/cmake/std/atdm/utils/get_known_system_info.sh
index 08868fa2758..42e1ab16a6a 100644
--- a/cmake/std/atdm/utils/get_known_system_info.sh
+++ b/cmake/std/atdm/utils/get_known_system_info.sh
@@ -143,7 +143,7 @@ if [[ $realHostname == "mutrino"* || $HOST == "mutrino"* ]] ; then
 fi
 
 # ASTRA/Van1-Tx2 systems
-if [[ $SNLSYSTEM == "astra"* ]] ; then
+if [[ $realHostname == "astra"* || $realHostname == "stria"* ]] ; then
   systemNameTypeMatchedList+=(van1-tx2)
   systemNameTypeMatchedListHostNames[van1-tx2]=$SNLCLUSTER
 fi
```

**Comment by e10harvey** [comment]
> -if [[ $SNLSYSTEM == "astra"* ]] ; then
> +if [[ $realHostname == "astra"* || $realHostname == "stria"* ]] ; then

@bathmatt: will this work on compute and login nodes?

**Comment by bathmatt** [comment]
Not sure about compute, i can try to test.

**Comment by bathmatt** [comment]
No, it doesn't work on the backend.  we can add st# to the list.

**Comment by jmgate** [comment]
After further investigation, it looks like not all nodes got the `SNLSYSTEM` environment variable when the system came back up.  Does that sound right to you guys?

**Comment by jmgate** [comment]
Nope, actually that doesn't look right.  Maybe this was just a transient issue and our deploy will be back up and running tonight.

**Comment by e10harvey** [comment]
> After further investigation, it looks like not all nodes got the `SNLSYSTEM` environment variable when the system came back up. Does that sound right to you guys?

That is my speculation as well. `source cmake/std/atdm/load-env.sh Deploy-develop-stria-arm-20-opt-openmp-static` (using the tip of trilinos develop) is working on both login and compute nodes on my end.

**Comment by e10harvey** [comment]
There is a chicken and the egg problem in `cmake/std/atdm` but one could check for `[ -z $SNLSYSTEM ]` in a driver script that is intended to run on van1-tx2 systems.

**Comment by e10harvey** [comment]
> There is a chicken and the egg problem in `cmake/std/atdm` but one could check for `[ -z $SNLSYSTEM ]` in a driver script that is intended to run on van1-tx2 systems.

Alternatively, one can run load-env with a custom system config dir:
`source cmake/std/atdm/load-env.sh Deploy-develop-van1-tx2-arm-20-opt-openmp-static cmake/std/atdm/van1-tx2`.

https://github.com/trilinos/Trilinos/blob/master/cmake/std/atdm/README.md#custom-systems-and-configurations.
