### ISSUE TITLE
MueLu: cannot construct hierarchy from a const matrix

### ISSUE THREAD

**Issue by mayrmt** [trilinos/Trilinos#8765]
@trilinos/muelu 

### Description

Assume to construct a hierarchy as follows:
```c++
  RCP<const Matrix> matrix = ... // some matrix

  RCP<ParameterList> params = Teuchos::getParametersFromXmlFile(xmlFile);
  ParameterListInterpreter mueLuFactory(*params, comm);

  RCP<Hierarchy> hierarchy = mueLuFactory.CreateHierarchy();
  hierarchy->GetLevel(0)->Set("A", matrix);
```

Then, one ends up with this runtime error:

```
/ssd/codes/mayrmt_trilinos/src-trilinos/packages/muelu/src/Interface/../MueCentral/MueLu_VariableContainer.hpp:274:
 
Throw number = 1
  
Throw test that evaluated to true: data_->type() != typeid(TM)

Error, cast to type Data<Teuchos::RCP<Xpetra::Matrix<double, int, long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > >> failed since the actual underlying type is 'Teuchos::RCP<Xpetra::Matrix<double, int, long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > const>!
```

This goes away, when one sets the operator via
```c++
  hierarchy->GetLevel(0)->Set("A", Teuchos::rcp_const_cast<Matrix>(matrix));
```
i.e. without the `const` qualifier.

I'm very confused. Shouldn't MueLu be able to handle `const` matrices? Why's that? Am I missing something?

### Additional Information

Similarly, other MueLu entry points such as `MueLu::CreateXpetraPreconditioner()` do not accept a `RCP<const Matrix>`, 
but only a `RCP<Matrix>`.

### Steps to reproduce

Since I'm currently familiar with the code in `packages/muelu/src/test/meshtying/MortarSurfaceCoupling_DofBased.cpp`, I changed the MueLu call to use a `const Matrix` (as decribed above).

### Related Issues

I noticed this behavior while looking into #8762.

**Comment by cgcgcg** [comment]
Is this a duplicate of  #6390?

**Comment by mayrmt** [comment]
Duplicate of #6390. Closing.
