### ISSUE TITLE
Make Intrepid2 independent of (or optionally dependent on) Sacado

### ISSUE THREAD

**Issue by mperego** [trilinos/Trilinos#878]
Presently, Intrepid2 has a required dependency on Sacado.
This is not strictly needed and we want to remove this dependency in order to reduce interdependencies between packages. Intrepid2 can still have an optional dependency on Sacado for testing purposes.

In order to achieve this goal we need to move the factory (https://github.com/trilinos/Trilinos/blob/master/packages/sacado/src/Kokkos_ViewFactory.hpp) for creating Kokkos views and dynamic rank views from Sacado to Kokkos, and have Sacado provide the specializations for FAD types.

@trilinos/intrepid2
@trilinos/sacado 
@ndellingwood  @hcedwar @crtrott

**Comment by dridzal** [comment]
Isn't Sacado used for computing derivatives of certain high-order basis functions?  How can you remove it?


________________________________

**Comment by mperego** [comment]
@dridzal True, Sacado seems to be used for HGRAD_TRI_Cn_FEM_ORTH, HGRAD_TET_Cn_FEM_ORTH, HGRAD_POLY_C1_FEM. 
However these elements don't seem to be used often.. if so I think it still make sense to have SACADO optional (and these will be compiled only when SACADO is enabled). 
I'll look into this. Thanks for pointing this out.

**Comment by mperego** [comment]
Modified HGRAD_TRI_Cn_FEM_ORTH to enable basis evaluations and their first derivatives without using Sacado. Sacado will be needed for higher order derivatives.
Same approach can be used for the other basis using Sacado

**Comment by mperego** [comment]
I think all the bases classes that were using Sacado for computing derivatives can now be run without Sacado for first derivatives (which are anyway the only one used in most of the applications).
The only class using Sacado that we have not converted yet is HGRAD_POLY_C1_FEM. At the moment such class is not needed by our customers.

**Comment by mperego** [comment]
Sacado is now only an optional dependency for Intrepid2.
After @ndellingwood fix f1701112e8cb111cf110d43d6fba55829f686d68 I think we can close this issue.
Thanks @ndellingwood for the work in Kokkos and @etphipp @hcedwar @kyungjoo-kim  and @dridzal for helping.
