### ISSUE TITLE
ats2 xl Trilinos builds failing in SEACAS starting 02-03-2021

### ISSUE THREAD

**Issue by e10harvey** [trilinos/Trilinos#8791]
CC: @trilinos/seacas, @gdsjaar, @bartlettroscoe

## Next Action Status

<status-and-or-first-action>

## Description

As shown in [this query](https://testing-dev.sandia.gov/cdash/index.php?project=Trilinos&begin=2021-02-2&end=2021-02-22&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=63&value1=ats2-cuda-10&field2=buildname&compare2=63&value2=xl) the builds:

* `Trilinos-atdm-ats2-xl-2020.03.18_spmpi-rolling_static_opt`

started failing on testing day 2021-02-03.

All of the builds are show the following build output like shown [here](https://testing-dev.sandia.gov/cdash/viewBuildError.php?buildid=6172993):
```
CMakeFiles/conjoin.dir/Conjoin.C.o:(.toc+0x178): undefined reference to `fmt::v7::format_arg_store<fmt::v7::basic_format_context<fmt::v7::detail::buffer_appender<char>, char>, int, float, float, float, float, float, float, unsigned long>::desc'
../../libraries/suplib_cpp/libsuplib_cpp.a(copyright.C.o):(.toc+0x20): undefined reference to `fmt::v7::format_arg_store<fmt::v7::basic_format_context<fmt::v7::detail::buffer_appender<char>, char>, std::string const>::desc'
```

This is likely due to the C++ standard upgrade from C++11 to C++14. Related to #8756.

## Current Status on CDash

Run the [above query](https://testing-dev.sandia.gov/cdash/index.php?project=Trilinos&begin=2021-02-2&end=2021-02-22&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=63&value1=ats2-cuda-10&field2=buildname&compare2=63&value2=xl) adjusting the "Begin" and "End" dates to match today any other date range or just click "CURRENT" in the top bar to see results for the current testing day.

## Steps to Reproduce

One should be able to reproduce this failure as described in:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md

and the system-specific instructions at:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#specific-instructions-for-each-system

Just log into any of the associated machines and copy and paste the full CDash build name `<build-name>` listed above and run commands like:

```
$ cd <some_build_dir>/

$ source $TRILINOS_DIR/cmake/std/atdm/load-env.sh <build-name>

$ cmake \
 -GNinja \
 -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
 -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_<package-name>=ON \
 $TRILINOS_DIR

$ make NP=16

$ <command-to-run-on-compute-node> ctest -j4
```

where `<package-name>` is any package that you want to enable to reproduce build and/or test results.

Again, for exact system-specific details on what commands to run to build and run tests, see:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#specific-instructions-for-each-system

If you can't figure out what commands to run to reproduce the problem given this documentation, then please post a comment here and we will give you the exact minimal commands.

**Comment by e10harvey** [comment]
@bartlettroscoe: How can the csv be updated to track this even though there are no tests run?

**Comment by bartlettroscoe** [comment]
> @bartlettroscoe: How can the csv be updated to track this even though there are no tests run?

@e10harvey, the tool cdash_analyze_and_report.py is not really designed to track know build errors.  The assumption is that build errors will be fixed pretty quickly.   If the plan is to let tracked builds fail for long periods of time, then something different needs to be done with these builds so they don't build a tolerance for seeing build errors in the summary emails.  For the XL builds, I would suggest demoting them to Experimental builds and remove them from the list of expected for now to get them out of the Summary emails.

**Comment by bartlettroscoe** [comment]
FYI: People were warned months ago that these XL builds were going to fail with C++14 was enabled but the decision was to update Trilinos anyway.  So these failures were known months ahead of time.

**Comment by gsjaardema** [comment]
@e10harvey Should this be closed.  I don't think the ats2-xl build is used for Trilinos anymore?

**Comment by e10harvey** [comment]
@gsjaardema: Yes. Closing as `wontfix` due to removal of xl builds via https://github.com/trilinos/Trilinos/pull/9414.
