### ISSUE TITLE
Tpetra:  serial search in insert_crs_indices is expensive for dense rows

### ISSUE THREAD

**Issue by kddevin** [trilinos/Trilinos#8794]
## Bug Report
@trilinos/tpetra. @crdohrm @shardest

### Description
In insert_crs_indices, there is a serial search of a row's existing indices for the index to be inserted -- an operation that is effectively n^2 in the number of indices in a row.   See  https://github.com/trilinos/Trilinos/blob/1a61be2dc0378de70f515792f215889d6f449004/packages/tpetra/core/src/Tpetra_Details_crsUtils.hpp#L422

This serial search is probably OK when few indices per row are inserted, but when many indices are inserted in a row, the insertion becomes expensive.

We should look at replacing the serial search with an unordered_map.

### Steps to Reproduce

Build CrsMatrix with insertGlobalIndices and matrix with many nonzeros in a row.  Time fillComplete.

**Comment by kyungjoo-kim** [comment]
instead of "insert" interface, can we make a "replace" interface for this use case, which does not perform search operation but it overwrites all indicies of a row ? we only need to check the length of the row matches to the given array of indiies. just thought.

**Comment by kddevin** [comment]
@kyungjoo-kim  The search is to prevent inserting the same index twice; it is removing duplicates.  It is called from insertGlobalValues.  Is this the use case you are thinking of?

**Comment by crdohrm** [comment]
I was wondering why insertGlobalValues would get called from insertLocalValues (our use case). If we know our local indices and there are no duplicates, there shouldn't be a need for a search, right? I could be missing something basic here.

**Comment by kddevin** [comment]
@crdohrm insert_crs_indices is called from both insertLocalValues and insertGlobalValues.  insertGlobalValues is not called from insertLocalValues.

The search is needed in the local use case.  The local value is a local column number.  The search is for the nonzero in a given row with that local column number.
