### ISSUE TITLE
Adelus: Failing tests on candidate Dev->Master build

### ISSUE THREAD

**Issue by prwolfe** [trilinos/Trilinos#8796]
## Bug Report
@trilinos/Adelus

### Description
The candidate build for ats2 develop->master is failing the addles_vector_random_MPI[1-4] tests. All of these fail with errors like 

```
[vortex17:142199] *** Process received signal ***
[vortex17:142199] Signal: Segmentation fault (11)
[vortex17:142199] Signal code: Invalid permissions (2)
[vortex17:142199] Failing at address: 0x7ffef3737680
```

These need to be resolved in order to complete #8129 

### Steps to Reproduce
SHA1:  develop
Use the PR environment from cmake/std/sems/PullRequestCuda10.1.243TestingEnv.sh and instructions from https://github.com/trilinos/Trilinos/wiki/Reproducing-PR-Testing-Errors

**Comment by jwillenbring** [comment]
@vqd8a Can you comment on this issue?

**Comment by vqd8a** [comment]
@jwillenbring @prwolfe Sorry for the delay. I would appreciate if you can add a link to the failing tests. It looks to me that these tests were run without CUDA-aware MPI on vortex.

**Comment by prwolfe** [comment]
> @jwillenbring @prwolfe Sorry for the delay. I would appreciate if you can add a link to the failing tests. It looks to me that these tests were run without CUDA-aware MPI on vortex.

The last one is at https://testing.sandia.gov/cdash/viewTest.php?onlyfailed&buildid=8914772 - this job runs every 12 hours and you can find that series of jobs at https://testing.sandia.gov/cdash/index.php?project=Trilinos&begin=2021-03-22&end=now&filtercount=1&showfilters=1&field1=buildname&compare1=63&value1=PR-cuda10.1.243-test-Trilinos_pullrequest_cuda_10.1.243

**Comment by vqd8a** [comment]
@prwolfe 
The Adelus tests assume CUDA-aware MPI when tested with CUDA while in the test output I see ```TPETRA_ASSUME_CUDA_AWARE_MPI=0```.  
```
WARNING, you have not set TPETRA_ASSUME_CUDA_AWARE_MPI=0 or 1, defaulting to TPETRA_ASSUME_CUDA_AWARE_MPI=0
BEFORE: jsrun  '-p' '2' '--rs_per_socket' '4' '/vscratch1/trilinos/jenkins/vortex-trilinos/workspace/trilinos-folder/Trilinos_pullrequest_cuda_10.1.243/pull_request_test/packages/adelus/test/vector_random/Adelus_vector_random.exe' '1000' '1' '4'
AFTER: export TPETRA_ASSUME_CUDA_AWARE_MPI=0; jsrun  '-p' '2' '--rs_per_socket' '4' '/vscratch1/trilinos/jenkins/vortex-trilinos/workspace/trilinos-folder/Trilinos_pullrequest_cuda_10.1.243/pull_request_test/packages/adelus/test/vector_random/Adelus_vector_random.exe' '1000' '1' '4'
```
Is there a way to set ```TPETRA_ASSUME_CUDA_AWARE_MPI=1``` for these tests? Thanks.

**Comment by prwolfe** [comment]
That variable should have been set - let me look at that.

**Comment by prwolfe** [comment]
I set up a change that should get that variable set. It will have to merge and then run a new set of tests.

**Comment by vqd8a** [comment]
@prwolfe  Thanks Paul!

**Comment by prwolfe** [comment]
@vqd8a - Looks like just turning on TPETRA_ASSUME_CUDA_AWARE_MPI=1 in #8931 is not a good setup. It fixed 3 of the 4 failing Adelus tests and now a Stokkos test and a TrilinosCouplings test are failing very reliably. There is some work going on in #8934 that I want to ask Henry about. Can you look at the Adelus_vector_random_MPI_1 test and see what can be done there?

**Comment by vqd8a** [comment]
@prwolfe Sorry for my late response. I will look into the Adelus_vector_random_MPI_1 test and have a PR for the fix.
