### ISSUE TITLE
Zoltan: Failing tests on candidate Dev->Master build

### ISSUE THREAD

**Issue by prwolfe** [trilinos/Trilinos#8798]
## Bug Report
@trilinos/zoltan 

### Description
The tests

```
Zoltan_ch_simple_zoltan_parallel
Zoltan_hg_simple_zoltan_parallel
```
Are failing in the candidate build for ats2 on vortex. They seem to be differences with gold files mainly.

These need to run clean in oder to complete #8129

### Steps to Reproduce
SHA1: develop
Use the PR environment from cmake/std/sems/PullRequestCuda10.1.243TestingEnv.sh and instructions from https://github.com/trilinos/Trilinos/wiki/Reproducing-PR-Testing-Errors

**Comment by jwillenbring** [comment]
@kddevin Is there someone who could look at this, or is it safe to simply disable these tests for this build?

**Comment by kddevin** [comment]
@jwillenbring @prwolfe forgive me for the delay.  Can you add a link to the test so that I can peek at the Zoltan output?
I know you gave steps to reproduce, but if I can leverage your runs, I can make progress faster.  Thanks!

**Comment by prwolfe** [comment]
> @jwillenbring @prwolfe forgive me for the delay. Can you add a link to the test so that I can peek at the Zoltan output?
> I know you gave steps to reproduce, but if I can leverage your runs, I can make progress faster. Thanks!

The series is at https://testing.sandia.gov/cdash/index.php?project=Trilinos&begin=2021-03-28&end=now&filtercount=1&showfilters=1&field1=buildname&compare1=63&value1=PR-cuda10.1.243-test-Trilinos_pullrequest_cuda_10.1.243 and the last Zoltan tests are at https://testing.sandia.gov/cdash/viewTest.php?onlyfailed&buildid=8914829

These run every 12 hours.

**Comment by kddevin** [comment]
@prwolfe @jwillenbring 
I have tracked this failure down to a difference in vortex's MPI implementation (Spectrum) from the implementation used on other test platforms (OpenMPI).

```
  struct {
    float val;
    int rank;
  } local, global;
  local.val = 1.0;
  local.rank = me;
  MPI_Allreduce(&local, &global, 1, MPI_FLOAT_INT, MPI_MINLOC, MPI_COMM_WORLD);
  printf("%d MINLOC value %f on rank %d\n", me, global.val, global.rank);
```

When I run this code on vortex, it says the minimum value is on rank 3.
When I run it with OpenMPI, it says the minimum value is on rank 0.
Both are correct, of course. 

In Zoltan's PHG method, Zoltan generates separate coarse partitions on all ranks and selects the "best" in terms of a cut metric.  When the cut metric is equal on more than one processor (as in this test), Zoltan chooses the partition in global.rank.  Thus, if MPI returns a different global.rank, Zoltan chooses a different, equally good, partition.  The gold-standard answers, however, check for a specific partition, not an equally good one.  Thus, the tests fail even though the generated partition is just fine.

I will add a test to Zoltan that identifies whether this condition exists.  

 Until I think of an elegant workaround, disabling these zoltan tests on this platform is acceptable.  Zoltan does not use GPUs, and while it is a good canary for MPI problems, rigorous testing of Zoltan on vortex does not seem necessary.

Thanks for your patience as I dug into Zoltan to find the issue.

**Comment by kddevin** [comment]
This website indicates that the behavior of Spectrum MPI is incorrect in this use case:
https://www.mpi-forum.org/docs/mpi-1.1/mpi-11-html/node79.html

**Comment by kddevin** [comment]
Until SpectrumMPI is fixed, these tests, along with the newly added mpiMinLoc test will have to be disabled on vortex.  #8129
