### ISSUE TITLE
ROL: Failing tests in candidate PR build for ats2

### ISSUE THREAD

**Issue by prwolfe** [trilinos/Trilinos#8799]
## Bug Report
@trilinos/rol 

### Description
The test `ROL_example_poisson-inversion_example_01_MPI_1` is failing in the develop->master candidate build. 

This needs to run clean in oder to complete #8129

### Steps to Reproduce
SHA1: develop
Use the PR environment from cmake/std/sems/PullRequestCuda10.1.243TestingEnv.sh and instructions from https://github.com/trilinos/Trilinos/wiki/Reproducing-PR-Testing-Errors

**Comment by dridzal** [comment]
@prwolfe , do you have a CDash link?  This test is not failing in several of our own builds.

**Comment by prwolfe** [comment]
Must have missed this - see https://testing.sandia.gov/cdash/viewTest.php?onlyfailed&buildid=8752143

**Comment by jwillenbring** [comment]
@dridzal Do you have any thoughts on this issue? Should we disable this test for this build?

**Comment by dridzal** [comment]
@jwillenbring please provide a working link to the failing test.

**Comment by prwolfe** [comment]
> @jwillenbring please provide a working link to the failing test.

https://testing.sandia.gov/cdash/test/63654888 - these expire after 30 days or so

**Comment by prwolfe** [comment]
https://testing.sandia.gov/cdash/index.php?project=Trilinos&begin=2021-04-01&end=now&filtercount=1&showfilters=1&field1=buildname&compare1=63&value1=PR-cuda10.1.243-test-Trilinos_pullrequest_cuda_10.1.243 will show you the series.
