### ISSUE TITLE
Adding support for UMFPACK in Amesos2

### ISSUE THREAD

**Issue by dridzal** [trilinos/Trilinos#88]
@trilinos/amesos2:  The @trilinos/rol team would like to use Amesos2 as the interface to a direct solver that is well suited for solving PDEs in two spatial dimensions.  In our experience, UMFPACK works well for these problems.  This capability would support the PDE-OPT application development kit and test suite.

**Comment by srajama1** [comment]
The target date for this is mid february.

**Comment by egboman** [comment]
SuperLU, MUMPS and MKL-Pardiso are already supported. Do these not work well on PDEs?

**Comment by dridzal** [comment]
I've used SuperLU a few years ago, and found it (1) slightly slower than UMFPACK and (2) significantly less robust.  The latter issue is why I prefer UMFPACK.  Four or five years ago, I managed to compile Amesos with MUMPS, and it seemed to segfault on 50% of problems that I gave it, especially on KKT-type systems.  It is possible that this has improved now.  I have not tried Pardiso.  I guess a question to @trilinos/amesos2 is if my observations are consistent with their knowledge of the solvers.  I am open to exploring other options if adding UMFPACK is not worth it.  Having said that, it seems a little strange that a well-recognized solver like UMFPACK is left out of the Amesos2 interface.

**Comment by srajama1** [comment]
It is a fair request to have an interface for UMFPACK. We will add it.

**Comment by jdbooth** [comment]
I agree.  It is a fair request.  I have also experienced problems with robustness in SuperLU and even MUMPS (~4.5, I have not ran a large study with 5.0).  Also MKL-Pardiso is hard to build if not using Intel compilers. UMFPACK would also be nice to have for comparisons.

**Comment by srajama1** [comment]
Denis,  I'll work on this next week. I am sorry for the delay. There were some unexpected work on other projects that blocked the work on this.

**Comment by srajama1** [comment]
This has become higher priority, Moving to in progress.

**Comment by srajama1** [comment]
PR #1069 fixed this. This is still not tested nightly though. See #1255 for details of nightly testing
