### ISSUE TITLE
Kokkos: 

### ISSUE THREAD

**Issue by prwolfe** [trilinos/Trilinos#8800]
## Bug Report
@trilinos/kokkos 

### Description
The test ```KokkosCore_UnitTest_CudaTimingBased_MPI_1``` is failing in the develop->master candidate build. (https://testing.sandia.gov/cdash/viewTest.php?onlyfailed&buildid=8752143)

This needs to run clean in oder to complete #8129

### Steps to Reproduce
SHA1: develop
Use the PR environment from cmake/std/sems/PullRequestCuda10.1.243TestingEnv.sh and instructions from https://github.com/trilinos/Trilinos/wiki/Reproducing-PR-Testing-Errors

**Comment by jwillenbring** [comment]
@crtrott Do you have any thoughts on this failure? Should we disable this test for this build for the time being?
