### ISSUE TITLE
Framework: Autotester broken

### ISSUE THREAD

**Issue by cgcgcg** [trilinos/Trilinos#8803]
## Bug Report
@trilinos/framework 

### Description
Every autotester build excepts the CUDA one fails to start, see PRs #8792, #8793, #8795

**Comment by jhux2** [comment]
All the CEE machines were rebooted this morning, could this have caused it?

**Comment by jhux2** [comment]
Still fallout from the reboot:  EWS, EGS, and CEERWS still down as of 9am MT.

**Comment by prwolfe** [comment]
> All the CEE machines were rebooted this morning to fix a read only issue in /projects, could this have caused it?

It looks like this was an issue most of yesterday, so not likely.

**Comment by GrahamBenHarper** [comment]
related to #3276

**Comment by jwillenbring** [comment]
This internal account permission issue has still not been resolved. We are trying to focus admin attention on this.

**Comment by prwolfe** [comment]
@jwillenbring - I have had a few messages with the admins - still no answers though.

**Comment by GrahamBenHarper** [comment]
It looks like the testers are working and PRs are getting merged again. Can we close this?
