### ISSUE TITLE
Teuchos: C++11 noreturn attribute error in MSVS

### ISSUE THREAD

**Issue by briadam** [trilinos/Trilinos#8818]
## Bug Report
@trilinos/teuchos @ibaned 

### Description
The positioning of the C+11 noreturn attribute introduced in packages/teuchos/core/src/Teuchos_TestForException.hpp in commit 9c3771bd seems to cause trouble in MSVS 2017 and 2019.
```
TEUCHOSCORE_LIB_DLL_EXPORT [[noreturn]] void TestForTermination_terminate(const std::string &msg);
```

Error: 
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	C3829	standard attribute 'noreturn' may only be applied to functions	teuchoscore	c:\local\briadam\dakota\source\packages\external\trilinos\packages\teuchos\core\src\Teuchos_TestForException.hpp	79	
```

I've so far only observed this when building with Dakota + Teuchos, but the essence is that when doing a 64-bit shared library (DLL) build on Windows, MSVS seems to insist that the __declspec(dllexport) follow the [[noreturn]]. I can't find any MSDN docs that specify allowable interactions between the C++11 standard attributes and MS-specific extensions, but I can say that reordering so the attribute precedes the MS __declspec() works:

```
[[noreturn]] TEUCHOSCORE_LIB_DLL_EXPORT void TestForTermination_terminate(const std::string &msg);
```
This can also be demonstrated in a little test program in MSVS that has these signatures:
```
[[noreturn]] __declspec(dllexport) void works() { std::exit(1); }
 __declspec(dllexport) [[noreturn]] void fails() { std::exit(1); }

```
Unless the standard offers guidance, I'd suggest just reordering so the noreturn appears first. I haven't yet verified life is good on other compilers, but should have info soon as I'm making that change in Dakota's Teuchos snapshot.

**Comment by ibaned** [comment]
Sounds like reordering them is the right fix... are you willing to open a PR?

**Comment by briadam** [comment]
Yes, certainly. It will be super sparse in terms of testing evidence (I'll try to do a standalone Trilinos build but no promises), but as long as you're all good with that, happy to. Thanks!

**Comment by ibaned** [comment]
No worries on testing, Trilinos has invested a lot in PR and nightly testing.

**Comment by briadam** [comment]
Thanks for the help @ibaned and @rppawlo !
