### ISSUE TITLE
Problem with clang-700.1.81 Trilinos develop config step

### ISSUE THREAD

**Issue by spdomin** [trilinos/Trilinos#882]
I am firing up my Clang (Mac) application builds after about three weeks of down time and now have a host of issues with the config step of Trilinos. Below are some snippets from my failed config which look suspicious, however, I am not really sure if these are the major problem or not:

```
/Users/naluIt/gitHubWork/nightlyBuildAndTest/Trilinos/build_nightly_release/CMakeFiles/CMakeTmp/src.cxx:12:34: note: insert an explicit cast to silence this issue
  int seed[4] = { 0.0, 0.0, 0.0, 1.0 };
                                 ^~~
                                 static_cast<int>( )
4 errors generated.
make[1]: *** [CMakeFiles/cmTryCompileExec2817964852.dir/src.cxx.o] Error 1
make: *** [cmTryCompileExec2817964852/fast] Error 2
```

```
/Users/naluIt/gitHubWork/nightlyBuildAndTest/Trilinos/build_nightly_release/CMakeFiles/CMakeTmp/src.cxx:14:7: warning: comparison of function 'A::theFunction' not equal to a null pointer is always true [-Wtautological-pointer-compare]
  if (A::theFunction != NULL) {

```

```
Linking CXX executable cmTryCompileExec2441979721
/usr/local/Cellar/cmake/3.1.0/bin/cmake -E cmake_link_script CMakeFiles/cmTryCompileExec2441979721.dir/link.txt --verbose=1
/usr/local/Cellar/open-mpi/1.8.4/bin/mpicxx     -std=c++11 -DHAVE_CXX_PRAGMA_WEAK -Wl,-search_paths_first -Wl,-headerpad_max_install_names  CMakeFiles/cmTryCompileExec2441979721.dir/src.cxx.o  -o cmTryCompileExec2441979721  
Undefined symbols for architecture x86_64:
  "A::theFunction()", referenced from:
      _main in src.cxx.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [cmTryCompileExec2441979721] Error 1
make: *** [cmTryCompileExec2441979721/fast] Error 2

Source file was:

#include <iostream>

namespace A {
// theFunction never gets defined, because we
// don't link with a library that defines it.
// That's OK, because it's weak linkage.
#pragma weak theFunction
extern void theFunction ();
}

```

**Comment by mhoemmen** [comment]
The last "error" is just a test for whether the compiler supports `#pragma weak`.  It looks like the compiler in that case does not.

**Comment by nmhamster** [comment]
@mhoemmen do you also for square brackets attributes notation?

**Comment by spdomin** [comment]
These all look new to me. Also the seed error is obviously wrong. However this looked to be auto generated test files and I am too much of a novice to change it.

**Comment by mhoemmen** [comment]
@nmhamster wrote:
> do you also [have a test] for square brackets attributes notation?

I couldn't find a test for C++11 generalized attributes anywhere in Trilinos.  GCC 4.7.x doesn't support them:

https://gcc.gnu.org/gcc-4.7/cxx0x_status.html

but GCC 4.8 does:

https://gcc.gnu.org/gcc-4.8/cxx0x_status.html

Most of those tests come from either TriBITS or Teuchos, I think.  I only added the `#pragma weak` test to Teuchos as part of the LinearSolverFactory effort, hoping that I could work around the issues with static libraries.

**Comment by mhoemmen** [comment]
@nmhamster Would you like a CMake test for square brackets attributes notation?  That may be a bit tricky, because different versions of the C++ standard support different attributes, and because only C++17 proposes that compilers should ignore attributes that they don't understand:

http://en.cppreference.com/w/cpp/language/attributes

However, we could easily test an attribute specified in C++11, like `[[noreturn]]`.  (`[[deprecated]]` requires C++14.)

**Comment by spdomin** [comment]
I upgraded to clang 8 and now I can config. For my needs, this can be closed. However, I have no idea what the actual OS X version that is formally supported.
