### ISSUE TITLE
Epetra: Error in matrix-matrix multiplication

### ISSUE THREAD

**Issue by searhein** [trilinos/Trilinos#8826]
## Question
@trilinos/epetra
@trilinos/xpetra
@trilinos/shylu

First, I should not that I am using `Epetra` through the `Xpetra` interface in FROSch. My question is the following:

Previously, I constructed a specific `Epetra_CrsMatrix` (through an `Xpetra::Matrix`) without specifying a column map. Now, I added a column map to the call of the constructor in order to be able to assembly the matrix using local indices. This works smoothly.
However, at a later point in the code, I am multiplying another `Epetra_CrsMatrix` (`Xpetra::Matrix`) with this matrix using ``Xpetra::MatrixMatrix<>::Multiply()``. At this point the program, terminates with the error:
```
Epetra_MpiDistributor::CreateRecvStructures_ expected RemotePIDs to be in sorted order
```
I am very surprised about this, also because I do not obtain this error using `Tpetra` instead. For now, I added an `if` statement to differentiate between `Epetra` and `Tpetra`; see the changes to the file `packages/shylu/shylu_dd/frosch/src/CoarseSpaces/FROSch_CoarseSpace_def.hpp` (lines 170-193) in my PR #8825. This should be fine for now, however, it would be great to understand how I could also get this running with `Epetra`.

**Comment by csiefer2** [comment]
There's an assumption that the column map is in "Aztec" ordering, which is as follows:

1. All the "local rows" (aka rows which in the domain map) first.
2. Off-rank rows are ordered by owning PID and sub-sorted by GID.

**Comment by searhein** [comment]
@csiefer2 Thanks for the explanation. Is there a way to automatically re-order the map accordingly?
