### ISSUE TITLE
Trilinos-atdm-cee-rhel7_­cuda-10.1.243_­gnu-7.2.0_­openmpi-4.0.3_­shared_­opt build missing starting 02/21/21

### ISSUE THREAD

**Issue by e10harvey** [trilinos/Trilinos#8834]
@trilinos/framework, see the associated Failure Tracking page entry on 03/01/21 for more details.

**Comment by e10harvey** [comment]
As shown by [this](https://testing-dev.sandia.gov/cdash/index.php?project=Trilinos&begin=2021-03-01&end=2021-03-02&filtercount=1&showfilters=1&field1=buildname&compare1=63&value1=Trilinos-atdm-cee-rhel7_cuda-10.1.243_gnu-7.2.0_openmpi-4.0.3_shared_opt) cdash query, this issue has been resolved as of 03/02/21.

**Comment by ZUUL42** [comment]
This build has gone missing again on 2021-03-11.
