### ISSUE TITLE
TrilinosCouplings Scaling examples fails to build in CI build

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#884]
**CC:** @trilinos/framework, @trilinos/intrepid2 

**Description:**

The TrilinosCouplings example example_Poisson2D_pn_tpetra.cpp currently fails to build as shown here:

* http://testing.sandia.gov/cdash/viewBuildError.php?buildid=2632716

which shows:

```
trilinoscouplings/examples/scaling/example_Poisson2D_pn_tpetra.cpp:102:40: fatal error: Intrepid2_FieldContainer.hpp: No such file or directory
```

**Comment by bartlettroscoe** [comment]
This is blocking the completion of #482 so I am going to disable the build of this example for now.  Actually, once #482 is completed and people start using checkin-test-sems.sh to push, then we will not have pushes that break a CI build like this again in the future (or we will make them very rare).

**Comment by jhux2** [comment]
@csiefer2

**Comment by csiefer2** [comment]
Don't disable it.  This is on my list of things to fix tomorrow.

**Comment by bartlettroscoe** [comment]
> Don't disable it. This is on my list of things to fix tomorrow.

Re-enabling it will be a single `git revert <sha1>`.  I will provide the exact command once I push.  As it stands, it is blocking my push to implement #482 and it is breaking for everyone currently trying to build TrilinosCouplings tests.

**Comment by mperego** [comment]
Thanks @csiefer2, let me know if you need help with that.

**Comment by csiefer2** [comment]
BTW, the code will build if you do this:

-DIntrepid2_ENABLE_KokkosDynRankView:BOOL=OFF

**Comment by bartlettroscoe** [comment]
The commit that disabled this is:

```
2fb8bbc "Disable broken Example_Poisson2D_pn_tpetra for now (#884, #482)"
Author: Roscoe A. Bartlett <rabartl@sandia.gov>
Date:   Mon Nov 28 16:17:36 2016 -0700 (4 hours ago)

M       packages/trilinoscouplings/examples/scaling/CMakeLists.txt
```

@csiefer2, you can revert this in your local `develop` branch with:

```
$ git revert 2fb8bbc
```

and then fix this and push (now with the newly updated checkin-test-sems.sh script).

**Comment by rppawlo** [comment]
> BTW, the code will build if you do this:
> 
> -DIntrepid2_ENABLE_KokkosDynRankView:BOOL=OFF

Not sure if your current testing includes Panzer, but if it does, you will need to turn the above flag to ON.  It requires the new refactor branch.

**Comment by bartlettroscoe** [comment]
> > BTW, the code will build if you do this:
> > 
> >  -DIntrepid2_ENABLE_KokkosDynRankView:BOOL=OFF
>
> Not sure if your current testing includes Panzer, but if it does, you will need to turn the above flag to ON. It requires the new refactor branch.

Panzer is most definitely part the new PT CI build for Trilinos.  Also, we must have one unique CI buld so I am guessing that `-DIntrepid2_ENABLE_KokkosDynRankView:BOOL=ON` needs to be set for that build.

**Comment by rppawlo** [comment]
The default is "ON" for the flag Intrepid2_ENABLE_KokkosDynRankView, so you don't need to set anything.

**Comment by csiefer2** [comment]
I hope the irony of having a hard dependency on something in the Kokkos::Experimental namespace isn't lost on anyone else...

**Comment by bartlettroscoe** [comment]
> I hope the irony of having a hard dependency on something in the Kokkos::Experimental namespace isn't lost on anyone else...

It depends on what "Experimental" really means in Kokkos.  But form the standpoint of the TriBITS Lifecycle Model, less mature code can be wrapped and used under more mature code as long as the code hides the details and does its own acceptance testing.  Therefore, this Kokkos code can change rapidly under the covers but that is just fine as long as Panzer provides a consistent interface needed for higher maturity code.  But Panzer it self may be viewed as "Research Stable" in which case there is no expectation of maintaining backward compatibility.

But note that Test Category and Maturity Level are largely orthogonal concepts as described at:

* http://trac.trilinos.org/wiki/TribitsLifecycleModelOverview#test_categories

Therefore, I think Kokkos means "Exploratory" maturity (but more likely "Research Stable") and not "Experimental" as in a testing sense.

> The default is "ON" for the flag Intrepid2_ENABLE_KokkosDynRankView, so you don't need to set anything.

Right, I meant "ON" by default.
