### ISSUE TITLE
Amesos2:  Add Iterative refinement option to SuperLU-Dist

### ISSUE THREAD

**Issue by ctanis** [trilinos/Trilinos#8843]
## Bug Report
@trilinos/amesos2

### Description
I've built a standalone solver for matrix market files that is able to run Belos or Amesos2 solvers, for comparison purposes.  With *some* input matrices (~100k rows, ~500k nonzeros)  the Superlu variants of Amesos2 simply get the wrong answer (the L2 norm of difference between computed and actual solution is ~240 as opposed to 10^-10 with other solvers).  This error magnitude is consistent across Superlu_dist (with different number of processors), Superlu and Superlu_mt.  I'm using the current versions of these libraries, but I also tested an older version of the library when I saw it mentioned in some buried Trilinos documentation. 

The consistency of the problem across versions suggests that I"m doing something wrong in how I set up my Amesos2 solver, but the only parameters I see for Superlu solvers are "ReplaceTinyPivot" and "ColPerm", neither of which helps.  Smaller linear systems appear to solve correctly with SuperLU.

I'm using the last Trilinos git version that did not require C++14.

I'd love to get some advice on how to narrow down the problem here.  Is Superlu  still a recommended distributed direct sparse solver?

**Comment by rppawlo** [comment]
@srajama1

**Comment by srajama1** [comment]
@ctanis Yes, SuperLU variants are supported. As you have stand alone matrices, if I were you the first thing I would try is to just test drivers in SuperLU itself to make sure you are able to solve the problem correctly with just SuperLU and eliminate any issues Amesos2 might have. If that works, then the difference might be in default parameters we use vs what is set in their driver. If that fails, we could reach out to SuperLU developers. @iyamazaki

**Comment by ctanis** [comment]
@srajama1 sorry for the delay in following up.  I'm now using one of the example programs from the superlu_dist distribution and it appears to solve this particular system without any problems.  Something within Amesos2 is causing it to behave differently.

**Comment by ctanis** [comment]
It looks like the problem is that Amesos2 does not support the IterRefine option for superlu_dist

**Comment by srajama1** [comment]
Oh, this could be added to Amesos2. If you end up adding it you can submit a PR or we can do it. The later will be somewhat slow.
