### ISSUE TITLE
MueLu:  undefined symbol error with MueLu / MATLAB

### ISSUE THREAD

**Issue by branfosj** [trilinos/Trilinos#8848]
## Bug Report
@trilinos/muelu

### Description

I'm trying to get a working MueLu/MATLAB build of Trilinos. Thanks to the help in #8813 I now have it built, but I'm getting an undefined symbol error when running:

```
Invalid MEX-file '/rds/bear-apps/devel/2019b/branfosj-eb-1/EL7/EL7-cascadelake/software/Trilinos/13.0.1-golf-2019b-MATLAB/packages/muelu/matlab/bin/muemex.mexa64':
/rds/bear-apps/devel/2019b/branfosj-eb-1/EL7/EL7-cascadelake/software/Trilinos/13.0.1-golf-2019b-MATLAB/lib/libmuelu-matlab.so.13: undefined symbol:
_ZNK6Tpetra10DistObjectISt7complexIdEiiN6Kokkos6Compat23KokkosDeviceWrapperNodeINS3_6SerialENS3_9HostSpaceEEEE11descriptionB5cxx11Ev
```

I've done a search for that symbol in the build tree before running `make install` and I cannot see it defined anywhere.

### Steps to Reproduce
1. SHA1:  13.0.1 release (4796b92fb0644ba8c531dd9953e7a4878b05c62d) with the changes from #7870 and #8227 applied. I've also repeated the issue with the latest develop (0f69cc4a68000d6e4003faf00887e23791f4de06). 
1. MATLAB 2020a, GCC 8.3.0 , OpenBLAS 0.3.7, FFTW 3.3.8
1. Configure script:  `cmake -DCMAKE_INSTALL_PREFIX=/rds/bear-apps/devel/2019b/branfosj-eb-1/EL7/EL7-cascadelake/software/Trilinos/13.0.1-golf-2019b-MATLAB -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER='gcc' -DCMAKE_C_FLAGS='-O2 -ftree-vectorize -march=native -mieee-fp -mno-recip' -DCMAKE_CXX_COMPILER='g++' -DCMAKE_CXX_FLAGS='-O2 -ftree-vectorize -march=native -mieee-fp -mno-recip' -DCMAKE_Fortran_COMPILER='gfortran' -DCMAKE_Fortran_FLAGS='-O2 -ftree-vectorize -march=native -mieee-fp -mno-recip' -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_C_FLAGS="$CMAKE_C_FLAGS -fPIC" -DCMAKE_CXX_FLAGS="$CMAKE_CXX_FLAGS -fPIC"  -DCMAKE_C_FLAGS="-O2 -ftree-vectorize -march=native -mieee-fp -mno-recip"  -DCMAKE_CXX_FLAGS="-O2 -ftree-vectorize -march=native -mieee-fp -mno-recip"  -DCMAKE_Fortran_FLAGS="-O2 -ftree-vectorize -march=native -mieee-fp -mno-recip"  -DKokkos_ENABLE_SERIAL:BOOL=ON  -DTpetra_INST_SERIAL:BOOL=ON  -DTpetra_INST_INT_INT:BOOL=ON  -DTrilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON  -DMueLu_ENABLE_Tutorial:BOOL=OFF  -DTrilinos_ENABLE_MueLu:BOOL=ON  -DTPL_ENABLE_MATLAB:BOOL=ON  -DMATLAB_ARCH=glnxa64  -DMATLAB_ROOT=/rds/bear-apps/2019b/EL7-cascadelake/software/MATLAB/2020a  -DTrilinos_EXTRA_LINK_FLAGS="-lm"  -DTrilinos_ENABLE_EXAMPLES:BOOL=OFF  -DTrilinos_ENABLE_Fortran:BOOL=OFF  -DTPL_ENABLE_Boost=OFF  -DTrilinos_ENABLE_ALL_FORWARD_DEP_PACKAGES:BOOL=ON  -DTPL_ENABLE_BLAS:BOOL=ON  -DBLAS_LIBRARY_DIRS="/rds/bear-apps/devel/2019b/branfosj-eb-1/EL7/EL7-cascadelake/software/OpenBLAS/0.3.7-GCC-8.3.0/lib;/rds/bear-apps/devel/2019b/branfosj-eb-1/EL7/EL7-cascadelake/software/GCCcore/8.3.0/lib64"  -DBLAS_LIBRARY_NAMES="openblas;gfortran;libgfortran.a"  -DTPL_ENABLE_LAPACK:BOOL=ON  -DLAPACK_LIBRARY_DIRS="/rds/bear-apps/devel/2019b/branfosj-eb-1/EL7/EL7-cascadelake/software/OpenBLAS/0.3.7-GCC-8.3.0/lib;/rds/bear-apps/devel/2019b/branfosj-eb-1/EL7/EL7-cascadelake/software/GCCcore/8.3.0/lib64"  -DLAPACK_LIBRARY_NAMES="openblas;gfortran;libgfortran.a"  -DTrilinos_ENABLE_TrilinosCouplings:BOOL=OFF  -DBUILD_SHARED_LIBS=ON  /dev/shm/build-branfosj-admin/branfosj-admin-1/Trilinos-LzesO/src`
1. Configure log:  [configure.log.log](https://github.com/trilinos/Trilinos/files/6101422/configure.log.log)
1. Build log: https://gist.github.com/branfosj/3163ef15a85b3f080a58bab2bd1cac4d
1. Commands run:
1. `matlab`
1. `A = laplacianfun([50, 50]);` (with `laplcianfun.m` from https://gitlab.ritc.jp/library/Trilinos/-/blob/d575794f1510c0122a913ced9be3e18af7b26b8e/packages/muelu/matlab/tests/JacobiSmooth/laplacianfun.m)
1. ` problemID = muelu('setup', A);`

**Comment by mayrmt** [comment]
@trilinos/muelu @csiefer2

**Comment by branfosj** [comment]
Ah, I think I have fixed this. I've added:
```
-DTrilinos_ENABLE_COMPLEX_DOUBLE:BOOL=ON
-DTrilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON
```

I've also added Boost, but I am not sure that that was the issue.

**Comment by csiefer2** [comment]
Cool.  Anything else going wrong?

**Comment by jhux2** [comment]
Closing as fixed.  Please reopen if necessary.
