### ISSUE TITLE
Zoltan2_ImbalanceMetricsUtility.hpp targetNumParts is comm size

### ISSUE THREAD

**Issue by mndevec** [trilinos/Trilinos#885]
imbalanceMetrics function in Zoltan2_ImbalanceMetricsUtility.hpp seems to obtain targetNumParts from the communicatior size around line ~454. 

Is this the way that was decided? Shouldn't it obtain those from Solution using getTargetGlobalNumberOfParts? 

This prints invalid imbalances for the mapping problems where I have serial input adapters. 
@trilinos/zoltan2

**Comment by kddevin** [comment]
@mndevec Are you passing a PartitioningSolution to this function (argument "solution")?  If so, the code should reset  targetNumParts to a value from the solution at line ~459 of Zoltan2_ImbalanceMetricsUtility.hpp.  Is the value returned from line ~459 incorrect?  Is the solution pointer  being passed incorrectly?  What value are you getting back -- targetNumParts=1?

**Comment by kddevin** [comment]
@mndevec what test problem can I run to see this behavior?  I'd like to track where things go wrong.  Thanks.

**Comment by kddevin** [comment]
Example of invalid output comes from last test in 
mpirun -np 4 Zoltan2_TaskMappingProblemTest.exe

METRICS FOR THE SERIAL CASE - ONE PHASE MAPPING - EACH ELEMENT IS ASSUMED TO BE IN UNIQUE PART AT  THE BEGINNING
Imbalance Metrics: (4 existing parts)
Target number of parts is 1
                            min        max        avg   imbalance
        object count       1024       1024       4096           1

Graph Metrics:  (4 parts)
Target number of parts is: 1
...

Here, "target number of parts" should be 4, not 1.  The min/max object counts are correct, but the avg is incorrect.
