### ISSUE TITLE
Intrepid2_refactor_perf-test_DynRankView_Serial_Test_01_MPI_1 fails in new MPI_RELEASE_DEBUG_SHARED_PT_COMPLEX build

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#886]
**CC:** @trilinos/intrepid2, @trilinos/framework 

**Description:**

The test Intrepid2_refactor_perf-test_DynRankView_Serial_Test_01_MPI_1 fails in the new MPI_RELEASE_DEBUG_SHARED_PT_COMPLEX build being put together as part of the new checkin-test-sems.sh script (see #482).  The failure looks like:

```
66/68 Testing: Intrepid2_refactor_perf-test_DynRankView_Serial_Test_01_MPI_1
66/68 Test: Intrepid2_refactor_perf-test_DynRankView_Serial_Test_01_MPI_1
Command: "/projects/sems/install/rhel6-x86_64/sems/compiler/gcc/4.7.2/openmpi/1.6.5/bin/mpiexec" "-np" "1" "/home/rabartl/Trilinos.base/BUILDS/CHECKIN/MPI_RELEASE_DEBUG_SHARED_PT_COMPLEX/packages/intrepid2/refactor/perf-test/DynRankView/Serial/Intrepid2_refactor_perf-test_DynRankView_Serial_Test_01.exe"
Directory: /ascldap/users/rabartl/Trilinos.base/BUILDS/CHECKIN/MPI_RELEASE_DEBUG_SHARED_PT_COMPLEX/packages/intrepid2/refactor/perf-test/DynRankView/Serial
"Intrepid2_refactor_perf-test_DynRankView_Serial_Test_01_MPI_1" start time: Nov 28 18:40 MST
Output:
----------------------------------------------------------
Testing datatype double
DeviceSpace::  HostSpace::    ===============================================================================
 Performance Test for measuring DynRankView Overhead 
 # of workset = 8
 Test Array Structure (C,P,D) = 4096, 9, 3
===============================================================================

===============================================================================
TEST 1: RealSpaceTools det 
        input (C,P,D,D), output (C,P) 
===============================================================================
 -> Testing View 
 -> Testing DynRankView 
===============================================================================
TEST 0:  t_view = 0.318622,  t_dynrankview = 0.341686, ratio (v/drv) = 0.932499
Performance test failed as view/dynrankview is below 0.95
===============================================================================
End Result: TEST FAILED
--------------------------------------------------------------------------
mpiexec noticed that the job aborted, but has no info as to the process
that caused that situation.
--------------------------------------------------------------------------
<end of output>
Test time =   0.79 sec
----------------------------------------------------------
Test Fail Reason:
Required regular expression not found.Regex=[TEST PASSED
]
"Intrepid2_refactor_perf-test_DynRankView_Serial_Test_01_MPI_1" end time: Nov 28 18:40 MST
"Intrepid2_refactor_perf-test_DynRankView_Serial_Test_01_MPI_1" time elapsed: 00:00:00
----------------------------------------------------------
```

It seems that this test is failing randomly with the current CI server as shown here:

* http://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&limit=0&filtercount=2&showfilters=1&filtercombine=and&field1=testname&compare1=61&value1=Intrepid2_refactor_perf-test_DynRankView_Serial_Test_01_MPI_1&field2=buildstarttime&compare2=84&value2=now

I have run this test over and over again and it fails every time on my machine.

A performance test should not be run as part of a build where `Trilinos_ENABLE_DEBUG` is true or when a machine may be loaded.  Instead, such a performance test should be run as part of a special `PERFORMANCE` build with an unloaded machine.

**Comment by bartlettroscoe** [comment]
I am going to disable this test for the MPI_RELEASE_DEBUG_SHARED_PT_COMPLEX build in the checkin-test-sems.sh script.  It will still run (and likely randomly fail) as part of post-push testing and every other build/test of Trilinos.

**Comment by bartlettroscoe** [comment]
Strangely this test passes for the non-complex build MPI_RELEASE_DEBUG_SHARED_PT:

```
434/2259 Test #1642: Intrepid2_refactor_perf-test_DynRankView_Serial_Test_02_MPI_1 .......................................   Passed    1.02 sec
```

Since people routinely disable complex in their own local testing, I am wondering if they did not see this test failing in their build.  Go figure.

Therefore, this test will still be enabled in the one standard non-complex MPI_RELEASE_DEBUG_SHARED_PT build.

**Comment by mperego** [comment]
I can disable all the Intrepid2 performance tests for now. Sorry for the trouble, we just went through a major code update.

**Comment by bartlettroscoe** [comment]
> I can disable all the Intrepid2 performance tests for now. Sorry for the trouble, we just went through a major code update.

You can add the argument `CATEGORIES PERFORMANCE` to the `TRIBITS_ADD_TEST()` all and that will disable it for all but special performance builds.  In fact, you should that for all performance tests and then set up a nightly build that just runs those on an uploaded machine.  That is not that hard to do and I can help you set that up to protect such code.  I have some performance tests in Teuchos marked this way that have not run in years.

**Comment by mperego** [comment]
I've added CATEGORIES PERFORMANCE to the performance tests of Intrepid2.
10f13ef1b9a9f214c1e295430970d22ca37b406b
Thanks for helping.

**Comment by bartlettroscoe** [comment]
The commit that disables this test is:

```
66811f1 "Disable Intrepid2_refactor_perf-test_DynRankView_Serial_Test_01_MPI_1 for re-push testing (#886)"
Author: Roscoe A. Bartlett <rabartl@sandia.gov>
Date:   Mon Nov 28 19:00:04 2016 -0700 (58 minutes ago)

M       project-checkin-test-config.py
```

This only impacts the pre-push build so nothing needs to be done.
