### ISSUE TITLE
Kokkos Kernels:  Trilinos install and standalone install are inconsistent

### ISSUE THREAD

**Issue by lucbv** [trilinos/Trilinos#8866]
## Bug Report
@trilinos/kokkos-kernels 
@bartlettroscoe 

### Description
When installing Kokkos Kernels as a standalone package a `Kokkos::kokkoskernels` target is generated and can be used by downstream applications to use Kokkos Kernels.
When Kokkos Kernels is installed as part of Trilinos this is no longer the case, only a `kokkoskernels` target is generated. 
This makes using Trilinos and Kokkos Kernels hard as special logic is required for users to handle both cases, ideally the installation should provide the exact same targets after installation.
For additional information also look [here](https://github.com/kokkos/kokkos-kernels/issues/869)

**Comment by bartlettroscoe** [comment]
This will be fixed as part of TriBITSPub/TriBITS#299

**Comment by lucbv** [comment]
OK, do you have an idea of the ETA for that work to be completed?

**Comment by bartlettroscoe** [comment]
@lucbv, note that the agreed-upon target convention is actually `KokkosKernels::all_libs` and **not** `KokkosKernels::kokkoskernels`.  See [proposed standard for <Package>Config.cmake files](https://docs.google.com/document/d/19gIZgPAfnK7RTdh0sMKr5Yeo1epPVKIfona-oxoCtsg).  There is a lot of discussion about that in:

* https://gitlab.kitware.com/snl/project-1/-/issues/139

(I can provide access to that GitLab repo if you don't already have it.)
