### ISSUE TITLE
Question: how to configure/build with MPI enabled

### ISSUE THREAD

**Issue by PedroJorgeRodrigues** [trilinos/Trilinos#8874]
I am trying to build Trillions framework under Linux(ubuntu) and I am getting trouble with MPI during the "make" step. I don't have any problem witn **MPI** since I made a test with a simple **MPIC++** program and everything went as expected.

 - I have **mpi include** header files under **/usr/include//usr/x86_64-linux-gnu/mpich (and mpi)**;
 - - My **mpi bin** with wrappers are under **/usr/bin**;
 - My **mpi libs** are under /**usr/lib/86_64-linux-gnu**;
 - first I got an error reporting missing **mpi.h** (firtst header invoked) but I moved the headers to **/usr/include** and it went gone (this shouldn't be needed);
 - Second it fails reporting some undefined MPI functions due to missing MPI libs;
 - I tried everything: on cmake I gave MPI_BIN_DIR (/usr/bin), MPI_EXEC (/usr/bin/mpiexec) and checked the var MPI_USE_COMPILER_WRAPPERS;
 - In spite of this it fails as you can see from the attached file;
 
[error.log](https://github.com/trilinos/Trilinos/files/6132317/error.log)

**Comment by GrahamBenHarper** [comment]
Can you provide more information such as your configuration? Have you made sure to set `TPL_ENABLE_MPI:BOOL=ON` and set `MPI_BASE_DIR` at configure time?

**Comment by PedroJorgeRodrigues** [comment]
- Sending the CMakeCache with configuration. Did all of that.

[CMakeCache.txt](https://github.com/trilinos/Trilinos/files/6132880/CMakeCache.txt)

**Comment by GrahamBenHarper** [comment]
> //CXX compiler
> CMAKE_CXX_COMPILER:STRING=/usr/bin/c++
> //C compiler
> CMAKE_C_COMPILER:STRING=/usr/bin/cc
> //Base directory for the MPI implementation under which the bin,
// include, and lib directories are found
MPI_BASE_DIR:PATH=/usr
//Path to the bin directory where the MPI compiler and runtime
// executables are found
MPI_BIN_DIR:PATH=/usr/bin

It looks like mpicxx/mpicc have not been set as your compilers. Maybe it's still not finding them. What does it say when you configure? You should see something like 
```
Probing the environment ...

-- USE_XSDK_DEFAULTS='FALSE'
-- BUILD_SHARED_LIBS='ON'
-- CMAKE_BUILD_TYPE='DEBUG'
-- MPI_USE_COMPILER_WRAPPERS='ON'
-- MPI_C_COMPILER=
-- Setting CMAKE_C_COMPILER=${MPI_C_COMPILER}
-- CMAKE_C_COMPILER=
-- MPI_CXX_COMPILER=
```
where the spaces I left blank after the = sign should list your MPI executables.

**Comment by jhux2** [comment]
@PedroJorgeRodrigues Your MPI install doesn't conform to what Trilinos is expecting:

```
To enable MPI support you must minimally set:

-D TPL_ENABLE_MPI=ON

There is built-in logic to try to find the various MPI components on your system but you can override (or make suggestions) with:

-D MPI_BASE_DIR="path"

(Base path of a standard MPI installation which has the subdirs 'bin', 'libs', 'include' etc.)
```
(from https://docs.trilinos.org/files/TrilinosBuildReference.html#configuring-with-mpi-support)

Thus, you'll need to specify exactly where all the pieces (headers, libraries, execs) live.

**Comment by PedroJorgeRodrigues** [comment]
I have this (using cmake-gui):

Probing the environment ...

-- USE_XSDK_DEFAULTS='OFF'
-- BUILD_SHARED_LIBS='ON'
-- CMAKE_BUILD_TYPE='RELEASE'
-- MPI_BASE_DIR='/usr'
-- MPI_BIN_DIR='/usr/bin'
-- MPI_USE_COMPILER_WRAPPERS='ON'
Leaving current CMAKE_C_COMPILER=/usr/bin/cc since it is already set!
Leaving current CMAKE_CXX_COMPILER=/usr/bin/c++ since it is already set!
Leaving current CMAKE_Fortran_COMPILER=/usr/bin/gfortran since it is already set!
-- MPI_EXEC='/usr/bin/mpiexec'
-- MPI_EXEC='/usr/bin/mpiexec'
-- CMAKE_C_COMPILER_ID='GNU'
-- CMAKE_C_COMPILER_VERSION='9.3.0'
-- CMAKE_CXX_COMPILER_ID='GNU'
-- CMAKE_CXX_COMPILER_VERSION='9.3.0'
-- Skip adding flags for OpenMP because Kokkos flags does that ...
-- Trilinos_SET_INSTALL_RPATH='ON'
-- CMAKE_INSTALL_RPATH_USE_LINK_PATH='ON'
-- Setting default for CMAKE_INSTALL_RPATH pointing to Trilinos_INSTALL_LIB_DIR
-- CMAKE_INSTALL_RPATH='/home/ubuntu/Dev/Trilinos-master/INSTALL_DIR/lib'
-- Trilinos_MAKE_INSTALL_GROUP_READABLE='OFF'
-- Trilinos_MAKE_INSTALL_WORLD_READABLE='OFF'
-- CMAKE_INSTALL_DEFAULT_DIRECTORY_PERMISSIONS = (OWNER_READ OWNER_WRITE OWNER_EXECUTE)
Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE)

**Comment by PedroJorgeRodrigues** [comment]
How do I specify exactly where are the headers/libraries/exec are under cmake-gui? There is no entry for that. I expected to have three entries for include/lib/bin concerning MPI.

**Comment by PedroJorgeRodrigues** [comment]
`Probing the environment ...

-- USE_XSDK_DEFAULTS='OFF'
-- BUILD_SHARED_LIBS='ON'
-- CMAKE_BUILD_TYPE='RELEASE'
-- MPI_BASE_DIR='/usr'
-- MPI_BIN_DIR='/usr/bin'
-- MPI_USE_COMPILER_WRAPPERS='ON'
Leaving current CMAKE_C_COMPILER=/usr/bin/cc since it is already set!
Leaving current CMAKE_CXX_COMPILER=/usr/bin/c++ since it is already set!
Leaving current CMAKE_Fortran_COMPILER=/usr/bin/gfortran since it is already set!
-- MPI_EXEC='/usr/bin/mpiexec'
-- MPI_EXEC='/usr/bin/mpiexec'
-- CMAKE_C_COMPILER_ID='GNU'
-- CMAKE_C_COMPILER_VERSION='9.3.0'
-- CMAKE_CXX_COMPILER_ID='GNU'
-- CMAKE_CXX_COMPILER_VERSION='9.3.0'
-- Skip adding flags for OpenMP because Kokkos flags does that ...
-- Trilinos_SET_INSTALL_RPATH='ON'
-- CMAKE_INSTALL_RPATH_USE_LINK_PATH='ON'
-- Setting default for CMAKE_INSTALL_RPATH pointing to Trilinos_INSTALL_LIB_DIR
-- CMAKE_INSTALL_RPATH='/home/ubuntu/Dev/Trilinos-master/INSTALL_DIR/lib'
-- Trilinos_MAKE_INSTALL_GROUP_READABLE='OFF'
-- Trilinos_MAKE_INSTALL_WORLD_READABLE='OFF'
-- CMAKE_INSTALL_DEFAULT_DIRECTORY_PERMISSIONS = (OWNER_READ OWNER_WRITE OWNER_EXECUTE)
Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) `

**Comment by jhux2** [comment]
@PedroJorgeRodrigues Please start with making sure the compilers are specified correctly, as described in the document above.  That may be enough because the compilers are wrappers and should encode where the include and library directories live.  I hope this helps.
