### ISSUE TITLE
Build_Error: possible missing member functions

### ISSUE THREAD

**Issue by PedroJorgeRodrigues** [trilinos/Trilinos#8878]
- I got an error during the build step;
- See the attached files;
- CmakeCache.txt with my options;
- error.log with the error report;
[CMakeCache.txt](https://github.com/trilinos/Trilinos/files/6136315/CMakeCache.txt)
[error.log](https://github.com/trilinos/Trilinos/files/6136316/error.log)

**Comment by jjellio** [comment]
Can you post your full cmake line (how you are calling cmake), and the output.

For example
```
cmake ... args | tee cmake.out
```

Then upload the cmake line + output (this is more informative than the Cache - it shows what you asked for and what Cmake/Tribits did)

**Comment by PedroJorgeRodrigues** [comment]
I am using cmake-gui not any command line cmake with options.

**Comment by jjellio** [comment]
Pedro, I think the problem is the config (or cache) still isn't describing what you want to achieve. Trilinos generally isn't tested (or intended to be used) by turning on everything. I'd recommend describing what you want to do and maybe we can help you with a good configuration.

**Comment by jhux2** [comment]
@PedroJorgeRodrigues To echo what @jjellio said, what is it that you want to do with Trilinos?  Describe the type of math problem you're trying to solve, the Trilinos packages that you want to enable, and any other information you think would be useful (e.g., using GPUs, MPI, OpenMP, etc.).

There are probably multiple ways that Trilinos could be configured that would break the cmake process, so just posting logs cmake output without context is not particularly helpful.

**Comment by jjellio** [comment]
Give this a try:

```
export CXX=mpicxx
export CC=mpicc
export FC=mpifort

cmake -DTPL_ENABLE_MPI=ON \
-DTrilinos_ENABLE_TESTS=ON \
-DTrilinos_ENABLE_EXAMPLES=ON \
-DTrilinos_ENABLE_ROL=ON \
-DTPL_ENABLE_Boost=OFF ..
```

It may work to set CC/CXX/FC, then run cmake-gui.  Then enable the ones I list.  That should get a ROL build going with Examples turned on. It should enable whatever other things it needs (nox, tpetra, etc..)

**Comment by PedroJorgeRodrigues** [comment]
I built it already. I want to solve PDE time dependent  together with nonlinear system of equations concerning Chemical Reactors. MPI can be used of course. Finite element methods or finite difference methods can be applied for discretizations.

**Comment by jhux2** [comment]
> I built it already. I want to solve PDE time dependent together with nonlinear system of equations concerning Chemical Reactors. MPI can be used of course. Finite element methods or finite difference methods can be applied for discretizations.

What packages Trilinos packages/capabilities are you interested in?

**Comment by PedroJorgeRodrigues** [comment]
Concerning what I said in my last post I suppose that Tempus/NOx/FEI. What do you think?

**Comment by jhux2** [comment]
@PedroJorgeRodrigues As far as I know, FEI is no longer maintained.  I'd recommend against it, and instead point you to Tpetra, which now has a matrix class geared towards FE assembly called FECrsMatrix.  Trilinos also has a great deal of linear solver capability, which presumably you might want to explore (Belos, Ifpack2, Frosch, MueLu, Amesos2). Hope this helps.

**Comment by PedroJorgeRodrigues** [comment]
Just to clarify:

 To solve my type of problems with non-linear equations and PDE(2D,3D) I can use:

 - NOX  - nonlinear equations;
 - Tempus - ODE solver;
 - Tpetra - FE;
 - Belos,...to Algebra;
 - Finite differences - I can build it;
 - Finite Volume method - Trillinos doesn't have; 
 
thanks for your help

**Comment by jhux2** [comment]
@PedroJorgeRodrigues Yes, your list is correct.

**Comment by rppawlo** [comment]
If all of your degrees of freedom use the same basis and the same equations are solved in all element blocks, then you can avoid FEI. If you want to use a mixed basis (combining HGrad/HCurl/HDiv/HVol) or want to build a single linear system with different DOFs in different element blocks, then a replacement for FEI is in the degree of freedom manager found in the Trilinos/packages/panzer/dof-mgr subpackage.
