### ISSUE TITLE
Substantial slow-down in Tpetra Muelu

### ISSUE THREAD

**Issue by spdomin** [trilinos/Trilinos#888]
Greetings,

Does anyone on the Trilinos development team have a recent set of Muelu/ML comparisons?

As I transition **fully** from ML to Muelu (this effort is part of Epetra deprecation) almost every single test is O(30)% slower. In most cases, I am using a Muelu XML file that “matches” the previous ML input. See attached test example (nonIsoElemOpenJet). Although I am using the blessed XML for Muelu that matches ML, linear solves increased by almost three iterations. Solver time, however, is almost 2x slower. Moreover, preconditioner setup time is also 2x slower. This result is very much representative of all ten+ tests that I am converting.

I was just wondering if anyone on the Trilinos team is keeping up with the previous Muelu benchmarks against ML. At one point, Muleu was only 10% slower in most cases.

Best,

Stefan

**Comment by rppawlo** [comment]
@pwxy do you have data for Drekar?

**Comment by spdomin** [comment]
no, sorry. my guess it has also taken a hit.

**Comment by jhux2** [comment]
@trilinos/muelu

**Comment by jhux2** [comment]
> See attached test example (nonIsoElemOpenJet).

@spdomin There's no attachment.  Github allows just a [limited number of file extensions](https://github.com/blog/2061-attach-files-to-comments).

**Comment by spdomin** [comment]
Sorry, I was trying to post to the Trilinos mail page all morning and forgot to remove the reference of the file. However, here it is...
[mlMuelu.pdf](https://github.com/trilinos/Trilinos/files/619760/mlMuelu.pdf)

Also, in this case, is the mesh so small that it is actually doing a direct solve?

**Comment by jhux2** [comment]
> Sorry, I was trying to post to the Trilinos mail page all morning and forgot to remove the reference of the file. However, here it is...
> mlMuelu.pdf
> 
> Also, in this case, is the mesh so small that it is actually doing a direct solve?

@spdomin Thanks for the data.  The mesh is has about 45K elements, so MueLu should be creating a multiple level hierarchy.  You can verify this by changing the verbosity in the MueLu XML file to "high".  (For the benefit of others, this question pertains to issue #889.)

**Comment by jhux2** [comment]
I have done some checking into this.  We don't have recent data tracking the performance of MueLu/Tpetra versus ML over time. I have results that compare the Tpetra SPGEMM to the one in ML.  These use Nalu, but just do one time step and repeated calls to set up the MueLu preconditioner.

**Comment by pwxy** [comment]
@rppawlo sorry, nothing recent.

**Comment by spdomin** [comment]
Our ECP Q1 deliverable is to benchmark the solves and assembly for an atmospheric boundary layer flow. Weak scaling results at ~60k elem/core show almost doubling of solve time for even modest total mesh sizes (order 200 million). I will circulate this report internally. However clearly there has been regression in performance.

**Comment by srajama1** [comment]
Adding myself to follow @srajama1

**Comment by jhux2** [comment]
@alanw0 I'm trying to build Nalu against Trilinos branch trilinos-release-12-6-4-2, SHA1 gc85db0e3.  The build fails in this way:
```
/ascldap/users/jhu/nalu/Nalu/src/PeriodicManager.C: In member function ‘void sierra::nalu::PeriodicManager::add_periodic_pair(stk::mesh::Part*, stk::mesh::Part*, const double&, const string&)’:
/ascldap/users/jhu/nalu/Nalu/src/PeriodicManager.C:95:20: error: ‘KDTREE’ is not a member of ‘stk::search’
     searchMethod = stk::search::KDTREE;
```

Is this a known problem?  I welcome any suggestions on how to work around this, as I'll be building Nalu with a number of different Trilinos releases.

**Comment by jhux2** [comment]
> @alanw0 I'm trying to build Nalu against Trilinos branch trilinos-release-12-6-4-2, SHA1 gc85db0e3. The build fails in this way: ...

I forgot to mention that the SHA1 of Nalu is 6fc3c6a50.

**Comment by spdomin** [comment]
@jhux2, your error suggests an old version of trilinos. This is not doubt an issue with bisecting. I had this issue before and had to manually edit code. In this case, you may need to change KDTREE to OCTREE to get the code to build. I think to be safe in the bisect, you need to check out the closest NaluRtest as well...

**Comment by jhux2** [comment]
@spdomin @alanw0 That's right, I'm using a Trilinos release.   But what I'm finding is that Nalu is not compatible with the version of STK in the Trilinos release.   Is there anyway to know what version of STK that Nalu requires, or is it a matter of what you (@spdomin) suggest, checking out a Trilinos version and Nalu version that are close in date?

**Comment by jhux2** [comment]
I don't think bisecting is a viable approach, since the version of STK used in Nalu isn't well-aligned with Trilinos releases.  Instead, I'm going to dump the linear system and maps from nonIsoElemOpenJet and read those into a MueLu test driver.  As long as I use Nalu's MueLu XML deck, the resulting multigrid hierarchy should be exactly the same as the one built in Nalu itself.

**Comment by spdomin** [comment]
@jhux2 sounds good. @mbarone81 is planning on running the same mesh and physics without periodic bcs. I think that this will be a good experiment to see if load balancing is a factor her since the coordinates at periodic bcs nodes are the same...

**Comment by spdomin** [comment]
@jhux2, perhaps as we wait for the Cori non-peridoc runs, we should re-establish the Muelu/ML comparison from our 2015 paper?

<img width="651" alt="figfive" src="https://cloud.githubusercontent.com/assets/8699324/20991708/15a82512-bc9d-11e6-8bfa-1df20fecbd4e.png">

**Comment by jhux2** [comment]
Adding @tgvoskuilen to this conversation.

**Comment by mbarone81** [comment]
@jhux2 and @spdomin  : here are the latest timings for continuity solve on Cori.  This is for the same ABL case as before, only replacing the periodic boundary conditions with inflow/outflow fore and aft, and symmetry on the lateral boundaries.  One difference in solver behavior is that the average number of linear iterations changes with core count, from 9.3 at 256 cores to 10.8 at 2048 cores.  For the periodic case, the average number of linear iterations was constant with core count at 8.0.
![weak_contsolve_nonp](https://cloud.githubusercontent.com/assets/6090175/21017452/a5394baa-bd26-11e6-8d1c-b69c990205ec.png)

**Comment by jhux2** [comment]
@sddomin @mbarone81 For the R2 runs, would you advise using the element or edge formulation?

**Comment by jhux2** [comment]
@spdomin domin @mbarone81 For the R2 runs, would you advise using the element or edge formulation?

**Comment by mbarone81** [comment]
@jhux2 @spdomin : I have been using primarily the edge scheme so I would recommend doing the same.

**Comment by jhux2** [comment]
@mbarone81 Thanks.  I've dumped the linear system data for the nalu R2 edge case.

**Comment by spdomin** [comment]
MilestoneRun uses the element base scheme. I would not think that this matters. My guess is that element is even slower since that was the trend in the milestone days.

**Comment by mbarone81** [comment]
Adding a timing result from the ABL runs that highlights some difficulty with preconditioner setup scaling for continuity, in addition to solve
![cont_strong_134m](https://cloud.githubusercontent.com/assets/6090175/21146788/28b39de0-c110-11e6-82ac-054066800e26.png)
.

**Comment by srajama1** [comment]
@mbarone81 : Is the #cores here equal to #mpi ranks ?

**Comment by mbarone81** [comment]
@sjrama1 : yes, that is the case here... running on Haswell nodes with 32 ranks per node

**Comment by mbarone81** [comment]
Some new timing data from the Serrano machine, very modest problem size, but encouraging...
![weak_cont_solve_serrano](https://cloud.githubusercontent.com/assets/6090175/21158777/d256a6e6-c13b-11e6-9b1c-5c978eadfef4.png)

**Comment by jhux2** [comment]
Here's an update on tracking MueLu's performance over time.  I've built Trilinos and a MueLu driver for three different git snapshots:

trilinos-release-11-4-branch, 76fed4c07 [last commit is Oct 28th, 2013]
trilinos-release-11-10-branch, 9e80a98d7 [last commit is Aug 27, 2014]
trilinos develop, 0f302d7d [last commit is Dec 6, 2016]

I had to make some minimal changes because the MueLu driver + matrix reading changed over time.  I did *not* change anything related to solver setup or apply.

Here are the results using the Nalu "R2" pressure matrix, which as .  Times are averaged over 100 rebuilds of the MueLu preconditioner.  All results are from cee-build013 when it was in a quiet state.

Matrix:  Nalu "R2" pressure matrix, 2.2m rows, run on 32 MPI processes
Solve: GMRES preconditioned by MueLu. Forced 50 iterations
Machine: cee-build013 (Xeon E7-4880, 120 cores, 1TB RAM)
Modules:
1) sntools/master                         3) sierra-python/2.7                      5) sierra-mpi/openmpi/1.8.8
2) sierra-compiler/gcc/4.8.5              4) sierra-git/2.6.1                       6) sierra-devel/gcc-4.8.5-openmpi-1.8.8

```
                               |   ------------------------------------------------------------------------------
                               |                                  Timer
                               |   ------------------------------------------------------------------------------
Trilinos version               |   MueLu setup time (max)       MueLu: Hierarchy: Solve* Belos: BlockGmresSolMgr
                               |   [avg'd over 100 rebuilds]    [50 gmres iterations]    total solve time
-----------------------------------------------------------------------------------------------------------------
trilinos-release-11-4-branch   |   1.51                         0.96                     1.78
trilinos-release-11-10-branch  |   1.27                         1.35                     2.18
develop                        |   0.46                         1.06                     1.91
-----------------------------------------------------------------------------------------------------------------

*this timer label is called "MueLu: Hierarchy: Iterate" in the 11-4 branch
```


Matrix:  Nalu "nonIsoElemOpenJet", first time step, 2nd linear solve, 4 processes
Solve: GMRES preconditioned by MueLu. Forced 50 iterations
```
                               |   ------------------------------------------------------------------------------
                               |                                  Timer
                               |   ------------------------------------------------------------------------------
Trilinos version               |   MueLu setup time (max)       MueLu: Hierarchy: Solve* Belos: BlockGmresSolMgr
                               |   [avg'd over 100 rebuilds]    [50 gmres iterations]    total solve time
-----------------------------------------------------------------------------------------------------------------
trilinos-release-11-4-branch   |   0.19                         0.14                     0.22
trilinos-release-11-10-branch  |   0.08                         0.12                     0.21
develop                        |   0.07                         0.17                     0.28
```

My next step will be to run the R3 matrix on skybridge using these same three Trilinos snapshots.  That matrix has 17.5m rows distributed on 256 cores.

**Comment by jhux2** [comment]
I should have specified in my last post that the results are using MueLu using Tpetra.

**Comment by spdomin** [comment]
We are leaning towards a haswell nuance... Data is still in flux, so please stay tuned..

**Comment by jhux2** [comment]
R3 results from skybridge:

Matrix:  Nalu "R3" pressure matrix, 17.5m rows, run on 256 MPI processes (8 nodes)
Solve: GMRES preconditioned by MueLu
Machine: skybridge (Intel Sandybridge)
Modules:
```
  1) sntools/master                        4) intel/intel-16.0.3.210                7) openmpi-intel/1.8
  2) sierra-python/2.7.4                   5) sierra-mkl/16.0                       8) sierra-mpi/openmpi/1.8
  3) sierra-git/2.6.1                      6) sierra-compiler/intel/16.0            9) sierra-devel/intel-16.0-openmpi-1.8
```
```
                               |   ------------------------------------------------------------------------------
                               |                                  Timer
                               |   ------------------------------------------------------------------------------
Trilinos version               |   MueLu setup time (max)       MueLu: Hierarchy: Solve* Belos: BlockGmresSolMgr
                               |   [avg'd over 10 total builds]                          total solve time
-----------------------------------------------------------------------------------------------------------------
trilinos-release-11-4-branch   |   2.78                         1.52                     2.46 (35 iterations)
trilinos-release-11-10-branch  |   2.24                         1.17                     2.2 (32 iterations)
develop                        |   0.82                         1.16                     2.15 (34 iterations)
-----------------------------------------------------------------------------------------------------------------

*this timer label is called "MueLu: Hierarchy: Iterate" in the 11-4 branch

**Comment by spdomin** [comment]
Its nice to see this data. I will try to replicate this effort on the R4 and 5 mesh so that the scale is closer to our production level. Thanks...

**Comment by spdomin** [comment]
I need a sanity check on the Muelu parameters.. From what I can see, the XML from the original Trinity runs looks like the following attached file:

[milestone_orig.txt](https://github.com/trilinos/Trilinos/files/657973/milestone_orig.txt)

The one that Matt has been running is located under the NaluRtest repos,

https://github.com/NaluCFD/NaluRtest/blob/master/xml/milestone.xml

Note that there are many others there..

Finally, my ML runs are using the following:

```
    ML_options_int:
      - name: "coarse: max size"
        value: 1000
      - name: "repartition: enable"
        value: 0
      - name: "repartition: min per proc"
        value: 1000
      - name: "max levels"
        value: 10
      - name: "repartition: Zoltan dimensions"
        value: 3
      - name: "smoother: sweeps"
        value: 2
      - name: "eigen-analysis: iterations"
        value: 15
      - name: "ML output"
        value: 11
      - name: "output"
        value: 11
    ML_options_real:
      - name: "repartition: max min ratio"
        value: 1.327
      - name: "aggregation: damping factor"
        value: 1.333
      - name: "aggregation: threshold"
        value: 0.02
    ML_options_string:
      - name: "aggregation: type"
        value: "Uncoupled"
      - name: "repartition: partitioner"
        value: "Zoltan"
      - name: "smoother: type"
        value: "Chebyshev"
      - name: "smoother: pre or post"
        value: "both"
      - name: "eigen-analysis: type"
        value: "power-method"

```

I would like to make sure that I am replicated the above figure from Lin et all perfectly. Can someone chime in? Is @pwxy the one and only PL?

**Comment by spdomin** [comment]
Here is another interesting data point from our open science work... Executable build was on the master Trilinos/Nalu around 4/8/2016. The mesh used for this strong scaling had 5,789,267,137 nodes.

65K core job:

```
Timing for Eq: MomentumEQS
             init --   	avg: 6.96494 	min: 6.544 	max: 7.012
         assemble --   	avg: 1.98732 	min: 1.528 	max: 2.968
    load_complete --   	avg: 1.80512 	min: 0.744 	max: 2.336
            solve --   	avg: 1.67028 	min: 1.596 	max: 1.684
             misc --   	avg: 1.53665 	min: 1.244 	max: 2.284
linear iterations --  	avg: 1 	min: 1 	max: 1
Timing for Eq: ContinuityEQS
             init --   	avg: 4.30968 	min: 4.276 	max: 4.336
         assemble --   	avg: 2.76972 	min: 2.28 	max: 3.468
    load_complete --   	avg: 1.36831 	min: 0.672 	max: 1.856
            solve --   	avg: 62.143 	min: 60.064 	max: 62.156
             misc --   	avg: 1.93587 	min: 1.456 	max: 2.396
linear iterations --  	avg: 40 	min: 30 	max: 50
```

130K core job:
```
Timing for Eq: MomentumEQS
             init --   	avg: 3.01857 	min: 3 	max: 3.056
         assemble --   	avg: 0.965312 	min: 0.728 	max: 1.552
    load_complete --   	avg: 1.38475 	min: 0.712 	max: 1.652
            solve --   	avg: 0.959336 	min: 0.924 	max: 0.972
             misc --   	avg: 0.90012 	min: 0.724 	max: 2.996
linear iterations --  	avg: 1 	min: 1 	max: 1
Timing for Eq: ContinuityEQS
             init --   	avg: 1.96981 	min: 1.944 	max: 1.98
         assemble --   	avg: 1.34419 	min: 1.104 	max: 2.624
    load_complete --   	avg: 1.61279 	min: 0.328 	max: 1.848
            solve --   	avg: 89.3409 	min: 89.296 	max: 89.356
             misc --   	avg: 1.04984 	min: 0.824 	max: 2.444
linear iterations --  	avg: 41.5 	min: 33 	max: 50
```

**Comment by spdomin** [comment]
I replicated the R4 study on Serrano using 38 and 76 nodes. The plot may be busy, so let me explain. I used ML with the above ML parameters. I compared these results to the Muelu runs with the milestone.xml and the muelu_matches_ml.xml file.

![mlmuelubenchmarkr4](https://cloud.githubusercontent.com/assets/8699324/21283995/69d40036-c3cb-11e6-8929-9f22678df064.png)

Results indicate that for both the edge and element scheme, the solve time (normalized by average iterations) divided by the ML results can be nearly 1.6. In general, Muelu iteration counts are higher. However, even with this correction, Muelu is still not nearly as efficient.

**Comment by srajama1** [comment]
Github issue https://github.com/trilinos/Trilinos/issues/883 might be related. That is fixed now.

**Comment by mhoemmen** [comment]
(#883 relates to apply, not to solve)

**Comment by jhux2** [comment]
@spdomin Thanks for generating this strong-scaling data.  In my R2 data, I was reporting weak scaling.  Our Parallel Processing Letters paper only reports strong scaling for the momentum solve.

**Comment by jhux2** [comment]
> I replicated the R4 study on Serrano using 38 and 76 nodes. The plot may be busy, so let me explain. I used ML with the above ML parameters. I compared these results to the Muelu runs with the milestone.xml and the muelu_matches_ml.xml file.

@spdomin I looked at the run directory on serrano (```/gscratch/spdomin/benchMarkET```) and noticed some problems with the input decks.

-  All the simulations using MueLu have dropping turned off, whereas dropping is turn on for ML.
- There is also at least one run where repartitioning is disabled.
- There are three runs that are using ILUT as a coarse grid solve.

We should talk about this graph -- I am very concerned that this graph is an apples-to-orange comparison.

**Comment by jhux2** [comment]
@spdomin The results with labels with the ```_mm``` suffix were generated using the ```matches_ml_default.xml``` input deck.  This input deck has aggregation dropping disabled, which is inconsistent with the milestone and ML input decks.

**Comment by jhux2** [comment]
> Results indicate that for both the edge and element scheme, the solve time (normalized by average iterations) divided by the ML timing results can be nearly 1.6.

@spdomin  I **strongly** disagree with this statement.  The factor of 1.6 is derived from columns that used the input ```matches_ml_default.xml```, which has repartitioning disabled.

**Comment by spdomin** [comment]
The matches_ml and milestone Xml files were obtain by the team many months ago. I can track the pedigree of these input files. 

Do you not agree with the milestone xml? Please submit a pull request on the updated Snl files to be in the NaluRtest repos.

**Comment by jhux2** [comment]
@spdomin and I looked at the details of the runs used for the first plot, and identified a few issues with solver option choices.  Using the same executable and test problem, but improved solver inputs, here is an updated study.  It omits the previous "_mm" results, as they were using settings that weren't appropriate for this problem.
![new-scaling](https://cloud.githubusercontent.com/assets/12970120/21401222/459279b4-c768-11e6-99ac-9912e232d659.png)

**Comment by mhoemmen** [comment]
@jjellio and @tjfulle, @jhux2's result above could be helpful for comparison with our ongoing benchmarking effort.

**Comment by spdomin** [comment]
Thanks for posting as I can reply to some of the subtleties. Muelu performance was once within 3% of ML for the element-based scheme and ~18% of the edge-based scheme. Now, Muelu is showing both within a 10% range. So, speed-up in the edge-based scheme and slow-down in the element-based scheme. I also ran a weak scaling plot of the R3 and R4 mesh on Serrano. The numbers are not ideal, however, no where as bad as the ABL.

**Comment by mhoemmen** [comment]
@spdomin wrote:
> Oh, @mhoemmen, the good news of this recent study is that matrix assembly remains the champion as does advection/diffusiuon solves through balos/ifpack2.

I'm pleased to hear this :-)  There are a few benchmarking and performance improvement efforts this FY for both assembly and solves.  In particular for assembly, performance should improve even for the MPI-only (no threads) case, because the planned improvements will search the matrix's rows less.

**Comment by jhux2** [comment]
> The Trinity case, which used the same milestone.xml file, actually showed that the solve time for the 130k job was larger than the 65k job (~5 billion element mesh).
> 
> Perhaps we still have a contaminated xml file?

It's possible, but I suspect other causes.  Since this is strong scaling, we know at some point the scaling degrades (I am not saying that that is happening here).

**Comment by mbarone81** [comment]
Hi @spdomin, @jhux2, I just wanted to note that the very limited weak scaling study for continuity solve that I performed on Serrano using the ABL problem looked perfectly fine as well.  It was on Skybridge and Cori where the weak scaling results were sub-optimal.  Would be great if someone can produce good weak scaling on, say, Skybridge with some other problem for a sanity check.

**Comment by jhux2** [comment]
I don't see a need to keep this issue open.

**Comment by spdomin** [comment]
@jhux2, I do not believe this finding from FY17/Q1 was ever resolved? That being said, we have deprecated ML and really have no choice but to accept Muelu with improvements as the project moves forward. Perhaps someone can address the 5% slow down over the past year in the new ticket?

**Comment by jhux2** [comment]
> Perhaps someone can address the 5% slow down over the past year in the new ticket?

@spdomin Please remind me of the issue number, I'll link it to this one. Thanks.

**Comment by mhoemmen** [comment]
@spdomin I may have done some good there with recent CrsGraph changes that fuse column Map and Import construction in CrsGraph.

**Comment by spdomin** [comment]
@mhoemmen, as usual - thanks. As for the baseline between v1.1 (from last October) and master, this is a new finding in our FY17/Q4 effort that has yet to make its way to any issue/story. Hopefully, that will be picked up. Essentially, we are only asking for routine benchmarking of our complete application code run (at an affordable scale) to monitor performance behavior. We can pick this up on ExaWind and then transition as required. I will stop posting here now:)
