### ISSUE TITLE
ShyLU:  Build fails without KokkosKernels enabled

### ISSUE THREAD

**Issue by PedroJorgeRodrigues** [trilinos/Trilinos#8887]
## Bug Report
@trilinos/\<ShyLU\>

### Description
Without KokkosKernels enabled the build failed reporting missing member functions.
[error.log](https://github.com/trilinos/Trilinos/files/6144591/error.log)

**Comment by mayrmt** [comment]
@trilinos/shylu

**Comment by srajama1** [comment]
@ambrad is the original owner of this code. @PedroJorgeRodrigues Do you really want to use this with Kokkos Kernels enabled or is this just an FYI.

**Comment by ambrad** [comment]
We might need the reproducing script. Note that the error log indicates `ShyLU_NodeHTS_ENABLE_KokkosKernels=ON`. So the question is why the preprocessor symbol at this line
https://github.com/trilinos/Trilinos/blob/1a61be2dc0378de70f515792f215889d6f449004/packages/shylu/shylu_node/hts/src/shylu_hts_impl_def.hpp#L1211 is not defined.

**Comment by PedroJorgeRodrigues** [comment]
These are the files you want to see: (I uploaded the wrong one - a later change I made with the same error, but I got around it). The attached files related with the first time I got it.

[CMakeCache.txt](https://github.com/trilinos/Trilinos/files/6147502/CMakeCache.txt)
[cmake-config.txt](https://github.com/trilinos/Trilinos/files/6147503/cmake-config.txt)
[error.log](https://github.com/trilinos/Trilinos/files/6147504/error.log)

**Comment by ambrad** [comment]
Thanks. Would you mind uploading your cmake command script? I still see
```
-- Setting ShyLU_NodeHTS_ENABLE_KokkosKernels=ON since Trilinos_ENABLE_ShyLU_NodeHTS=ON AND Trilinos_ENABLE_KokkosKernels=ON
```
in cmake-config.txt, which makes the error in error.log not make sense to me.
