### ISSUE TITLE
Amesos2: Klu2 solver with Epetra matrix and multivector

### ISSUE THREAD

**Issue by Adrian-Diaz** [trilinos/Trilinos#8888]
## Question
@trilinos/\<Amesos2\>

Greetings,

I tried the Simple Solve example with Tpetra in the Amesos2 package folder successfully when setting the solver to KLU2. However, when I try converting it to try it with Epetra the KLU2 solver reports a failed numerical factorization. As far as I can tell from the printed output the matrix and B vector have the correct values. Is there an additional step needed for Epetra? I've attached both of the example files (original and my edit). Thanks for any help rendered.

[SimpleSolve_Epetra_text.txt](https://github.com/trilinos/Trilinos/files/6144759/SimpleSolve_Epetra_text.txt)
[SimpleSolve_text.txt](https://github.com/trilinos/Trilinos/files/6144760/SimpleSolve_text.txt)

Sincerely,
Adrian Diaz

**Comment by srajama1** [comment]
@Adrian-Diaz Anything with Epetra will be lower priority. We will look at the issue ? Is there a reason you want to use Epetra and not Tpetra.

**Comment by Adrian-Diaz** [comment]
Hello,
I was just trying to get both to work to have options for an interface. However I couldn't get it to work with Epetra so I tried this simple example to see if I was doing something wrong with Epetra itself or I was misusing the solver somehow. If its just not supported for some reason then I will just use Tpetra.

**Comment by srajama1** [comment]
@Adrian-Diaz In theory we support both Epetra and Tpetra. However, Tpetra has become our primary stack as applications have moved to it. The support for Epetra is for applications that have not yet migrated. There could be an issue here with the Epetra usage or a bug in the code. However, it will take us time to reproduce and fix it as this will be lower in the priority.
