### ISSUE TITLE
NOX:  PETSc example

### ISSUE THREAD

**Issue by PedroJorgeRodrigues** [trilinos/Trilinos#8890]
## Bug Report
@trilinos/\<NOX\>

### Description
The PETSc example has an error: **cannot convert ‘int*’ to ‘const char*’**

[error.log](https://github.com/trilinos/Trilinos/files/6151729/error.log)

**Comment by mayrmt** [comment]
@trilinos/nox

**Comment by rppawlo** [comment]
@PedroJorgeRodrigues - the petsc support in nox was an experimental option. It is no longer supported by the nox team or tested in any Trilinos builds. It is kept in the code base in case a need arises and was last updated for petsc version 3.7 back in 2018. If you really need this option, please feel free to submit a PR with changes to update the linear algebra to the latest version of petsc.
