### ISSUE TITLE
adelus: does a standalone version exist?

### ISSUE THREAD

**Issue by gzagaris** [trilinos/Trilinos#8913]
## Question
@trilinos/\<adelus\>

Hello,

- Does a standalone version of adelus exist (i.e., outside of Trilinos)? If not, what would be the minimal cmake config required to compile adelus with MPI and CUDA support?
- Are there any good examples that illustrate basic usage or a user-guide?

Thanks,
George

**Comment by jhux2** [comment]
@vqd8a @srajama1

**Comment by srajama1** [comment]
@gzagaris No, we do not have a stand alone version. That said Adelus dependency on other Trilinos  packages are quite small. Checkout the README.md in
https://github.com/trilinos/Trilinos/tree/master/packages/adelus

**Comment by srajama1** [comment]
https://github.com/trilinos/Trilinos/blob/master/packages/adelus/example/adelus_driver.cpp

is a self contained example.

**Comment by gzagaris** [comment]
Thanks @srajama1.
