### ISSUE TITLE
Tpetra:  CrsMatrix construction with Kokkos views

### ISSUE THREAD

**Issue by Adrian-Diaz** [trilinos/Trilinos#8918]
## Question
@trilinos/\<Tpetra\>

Greetings,

I was wondering if there was a readily available way to construct the column map that the following Crs matrix constructor requires when passing kokkos views:

    CrsMatrix (const Teuchos::RCP<const map_type>& rowMap,
               const Teuchos::RCP<const map_type>& colMap,
               const typename local_matrix_type::row_map_type& rowPointers,
               const typename local_graph_type::entries_type::non_const_type& columnIndices,
               const typename local_matrix_type::values_type& values,
               const Teuchos::RCP<Teuchos::ParameterList>& params = Teuchos::null);

Thanks for any help rendered.

Sincerely,
Adrian Diaz

**Comment by jhux2** [comment]
@trilinos/tpetra
