### ISSUE TITLE
Trilinos Site:  Add PR Build Status Notification Area

### ISSUE THREAD

**Issue by ZUUL42** [trilinos/Trilinos#8919]
## Enhancement
@trilinos/framework 

What feature/addition is needed?  How does this differ from what we currently
have?  Are there any alternative solutions you've considered?  Do you have
suggestions on implementation?  How has the lack of this feature affected you? 
What are you trying to accomplish?  What specifically must we demonstrate to
call this work complete?
Add a PR Build notification area to the front page of the Trilinos developer wiki.
https://github.com/trilinos/Trilinos/wiki
Looking for a table with headers and colors that will stand out more.

**Comment by wadeburgess** [comment]
This was migrated to Trilinos Help Desk, so closing it now.
