### ISSUE TITLE
Tpetra readSparseFile error

### ISSUE THREAD

**Issue by tjfulle** [trilinos/Trilinos#892]
@trilinos/tpetra @mhoemmen 

The `Tpetra::MatrixMarket::Reader<Tpetra::CrsMatrix<> >::readSparseFile` method fails to read in files if there are multiple spaces between fields on the banner line.  For example, given the banner

```sh
%%MatrixMarket matrix coordinate  real    symmetric
```

the reader throws the following error:

```sh
Matrix Market banner line contains syntax error(s): Data type "real    symmetric" is not one of the valid values
```

Removing the spaces between fields, i.e.

```sh
%%MatrixMarket matrix coordinate real symmetric
```

resolves the problem.  However, many files at <http://math.nist.gov/MatrixMarket/> are formatted with multiple spaces in the banner, which leads me to believe that the MatrixMarket specification does not require a single space between fields, as assumed by Tpetra.

**Comment by mhoemmen** [comment]
@tjfulle You caught me on my week off ;-)  Care to take this one yourself?  teuchos/numerics/src/Teuchos_MatrixMarket_Banner.cpp, Banner's constructor.  I was pretty sure that the split() function used on line 221 of that file would take care of multiple spaces, but apparently not!

We could take care of this quickly by first adding a new unit test (in a separate file) to the teuchos/numerics/test/MatrixMarket directory.  The test would exercise different kinds of valid banners, to make sure that the Banner class accepts them and gets the keywords right.

**Comment by tjfulle** [comment]
@mhoemmen, yep, I'll take care of it tomorrow.

**Comment by mhoemmen** [comment]
Thanks @tjfulle !  You're awesome! :-D
