### ISSUE TITLE
Tpetra: MultiVector multiply performance

### ISSUE THREAD

**Issue by jennloe** [trilinos/Trilinos#8923]
@trilinos/tpetra 

**Enhancement summary:**  Change default of Tpetra::MultiVector 'multiply' to call GEMV instead of GEMM when multiplying by a single column vector (argument B).  This is expected to improve performance of Belos GMRES solver with a single right-hand side and ICGS[2] orthogonalization.  

**Background/Details:**
In writing a Kokkos adapter to Belos, I observed significant speedup over the Tpetra Belos adapter in the Belos::Multivector function MvTimesMatAddMv.  

This speedup seems to appear because the Kokkos adapter is calling KokkosBlas::GEMV when appropriate, while the Tpetra adapter is calling KokkosBlas::GEMM in every case (via the multiply function in Tpetra::MultiVector).  I believe if we make an analogous call to GEMV in Tpetra, we can see a reasonable speedup in Belos for GMRES with a single right-hand side.

I was testing GMRES(50) for  A nxn, a single right-hand side, and with ICGS[2] orthogonalization.  All variables were in double precision.
In practice, for the single right-hand side case, MvTimesMatAddMv computes V*u where V has dimension n x i, u is i x 1, and i ranges from 1 to 50.  (No transposes for this call.)  All experiments were run on a single compute node with a V100 GPU. 

**Additional Considerations:**
Are there any cases where this would give slowdown rather than speedup?  (For instance, I found in my experiments that calling GEMV was much slower for any transposed call that would have run with Seher's dot-based GEMM.)

How does this change affect performance with MPI?

**Comment by jhux2** [comment]
@jennloe Nice.  How big are the matrices (`n` in this case), and what were the speedup?

**Comment by cgcgcg** [comment]
Something to that effect was implemented in Kokkos Kernels by @seheracer, but it seems that was only for CuBlas. You're using the Kokkos Blas implementation?

**Comment by jennloe** [comment]
@jhux2  Here are some profiling results I’ve run with two different matrices.  I compared the Tpetra solver, the Kokkos solver, and then a 'bad' version of the Kokkos solver where I perform GEMM throughout the MvTimesMatAddMv function (as Tpetra does) instead of having the GEMV option for single-column calls.  

**Ex a:** **BentPipe2D with nx=1500 (so n=2.25 million)** 
2500 iterations of GMRES(50) with ICGS[2], rhs of all ones
Tpetra Block Gmres solve time: 14.67s
Kokkos BlockGmres solve time:  10.89s (=1.347x speedup)
Kokkos solve time with bad GEMM setting: 16.07s
[BentPipeProfile.pdf](https://github.com/trilinos/Trilinos/files/6208165/BentPipeProfile.pdf)

**Ex b:** **Laplace3D with nx=100 (n=1 million).**  
709 iterations of GMRES(50) with ICGS[2], rhs of all ones
Tpetra Block Gmres solve time: 2.424s
Kokkos BlockGmres solve time: 2.023s (=1.19x speedup)
Kokkos solve time with bad GEMM setting: 2.73s
[LaplaceProfile.pdf](https://github.com/trilinos/Trilinos/files/6208167/LaplaceProfile.pdf)

Complete stats from the KokkosSimpleKernelTimer are attached.  These speedups are consistent with what I’ve seen for other problems.  Again, this is on one CPU using one V100 GPU, so it needs further testing to see how far the speedups will go.  
All versions are running Belos::BlockGmres with the same matrix, right-hand side, and parameters.  

Note: I'm not 100% sure why the Kokkos version is making a few more calls to GEMM than the Tpetra version, but I could look into that.

**Comment by jennloe** [comment]
@kddevin @brian-kelley any thoughts on this?

**Comment by brian-kelley** [comment]
@jennloe I think it would make sense to handle this at the KokkosBlas::gemm level, rather than in Tpetra. It sounds like for multiplying an m*n by an n*k (after transposes), we want to use gemv if ``k == 1`` and ``!(m << n)`` (effectively the condition for using DotBasedGemm). Does that summarize what you've found?

Some other things we have to figure out are how LHS layout affects the heuristic (although for Tpetra MV*MV, it's always left). And maybe this is still profitable for k larger than 1 but still small.

**Comment by jennloe** [comment]
@brian-kelley That all sounds reasonable!

**Comment by jennloe** [comment]
After PR #9083 addressed this issue and PR #9276 fixed another performance problem introduced during the UVM removal, the performance of Tpetra ICGS[2] seems to be on-par with that of Kokkos!

**Comment by jennloe** [comment]
I summarize updated results from the tests in my previous comment on Mar 25:

Ex a: BentPipe2D with nx=1500 (so n=2.25 million)
2500 iterations of GMRES(50) with ICGS[2], rhs of all ones
Tpetra Block Gmres solve time: 10.31s
Kokkos BlockGmres solve time: 10.91s 
[GEMM2BentPipeProfile.pdf](https://github.com/trilinos/Trilinos/files/6673245/GEMM2BentPipeProfile.pdf)

Ex b: Laplace3D with nx=100 (n=1 million).
709 iterations of GMRES(50) with ICGS[2], rhs of all ones
Tpetra Block Gmres solve time: 1.88s
Kokkos BlockGmres solve time: 1.96s 
[GEMM2LaplaceProfile.pdf](https://github.com/trilinos/Trilinos/files/6673246/GEMM2LaplaceProfile.pdf)

All versions are running Belos::BlockGmres with the same matrix, right-hand side, and parameters.  Runs are on Weaver on a single V100 GPU.

Detailed results and test scripts are in the .zip file attached.  
[GEMVTests.zip](https://github.com/trilinos/Trilinos/files/6673240/GEMVTests.zip)
Test codes can be found in my fork here: https://github.com/jennloe/Trilinos/tree/KokkosBelos/packages/belos/kokkos/src 

These are significant improvements over the original tests!
We are still working to find an application code which has benefited from these improvements.

**Comment by jhux2** [comment]
> We are still working to find an application code which has benefited from these improvements.

@jennloe Are you still seeking sample matrices, or would you rather test in situ with an application?

**Comment by jennloe** [comment]
@jhux2 Either would be fine.  @iyamazaki is working on getting me some Nalu matrices, and @csiefer2 is helping me build some Sparc examples. I'm certainly open to other possibilities as well.  Really needs to be non-symmetric since CG doesn't ever call GEMM.

**Comment by kddevin** [comment]
Is this issue completed?  If so, please feel free to close.  Thanks.
