### ISSUE TITLE
Address expensive PT pre-push BASIC Trilinos tests

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#893]
**CC:** @trilinos/framework, @trilinos/rol, @trilinos/teko, @trilinos/zoltan 

**Description**

The initial PT pre-push CI test suite (see #482) currently has some pretty expensive tests.  Looking a the first post-push CI iteration this morning, we see the 2259 tests and their times at:

*  http://testing.sandia.gov/cdash/viewTest.php?onlypassed&buildid=2634468

We see that there are 9 tests that take over 1 minute to run and they drop down to under 30s once you get past the 18 most expensive tests.  These tests are:

| Test Name                                                                     | Status | Time |
|------------------------------------------------------------|------|------------|
|KokkosContainers_UnitTest_MPI_1 | Passed | 2m 45s 30ms|
|ROL_example_PDE-OPT_topo-opt_elasticity_example_02_MPI_4 | Passed | 2m 35s 300ms|
|ROL_example_PDE-OPT_0ld_adv-diff-react_example_02_MPI_4 | Passed | 1m 59s 280ms|
|Teko_testdriver_tpetra_MPI_1 | Passed | 1m 36s 880ms|
|Zoltan_hg_simple_zoltan_parallel | Passed | 1m 28s 370ms|
|ROL_example_PDE-OPT_0ld_poisson_example_01_MPI_4 | Passed | 1m 14s 460ms|
|Zoltan_ch_simple_zoltan_parallel | Passed | 1m 7s 150ms|
|ROL_example_PDE-OPT_topo-opt_elasticity_example_01_MPI_4 | Passed | 1m 7s 40ms|
|ROL_example_burgers-control_example_06_MPI_1 | Passed | 1m 4s 170ms|
|MueLu_ParameterListInterpreterTpetra_MPI_1 | Passed | 58s 70ms|
|ROL_test_sol_solSROMGenerator_MPI_1 | Passed | 55s 390ms|
|Teko_testdriver_tpetra_MPI_4 | Passed | 54s 950ms|
|KokkosAlgorithms_UnitTest_MPI_1 | Passed | 48s 850ms|
|Rythmos_IntegratorBuilder_ConvergenceTest_MPI_1 | Passed | 44s 730ms|
|ROL_example_PDE-OPT_ginzburg-landau_example_02_MPI_4 | Passed | 35s 810ms|
|KokkosCore_UnitTest_Serial_MPI_1 | Passed | 35s 220ms|
|ROL_example_parabolic-control_example_03_MPI_1 | Passed | 31s 70ms|
|Rythmos_BackwardEuler_ConvergenceTest_MPI_1 | Passed | 29s 700ms|
| ... | ... | ... |

After that, all of the remaining tests 2241 of the 2259 tests take less than 30s to run in this build.

What I would like to propose is that we make all of these tests that take longer than 1 minute and either do some work to make them run in under 1 minute or we change their category from the default `BASIC` to `CONTINUOUS` using the argument `CATEGORY CONTINUOUS`.

And I would like to make it a policy that we try to keep the test times for pre-push `BASIC` tests to under 1 minute.  If we can do that, then we can make the pre-push test suite run faster.  If you have just a single test that takes 2m45s to run, then no matter how many processes your throw at it, the test suite will never run faster than 2m45s.  That is the major motivation here for focusing on individual test times.

As part of this, we can consider how long each package's test suite takes to run by looking at the package-by-package summary this morning at:

* http://testing.sandia.gov/cdash/index.php?project=Trilinos&parentid=2634468

which when sorted by Test Time looks like:

| Package | Test time |
|---------|-----------|
|ROL | 6m 34s |
|Kokkos | 2m 45s |
|Zoltan | 2m 1s  |
|Teko | 1m 37s |
|Panzer | 1m 28s |
|MueLu | 1m 25s |
|Zoltan2 | 55s 	 |
|Tpetra | 54s 	 |
|Rythmos | 51s |
| ... | ... |

If we could cut down on these tests that take over 1 minute, I think it would also help to shorten the test time for each package as well.

Does anyone from any of these packages have any objections to relegating these tests from `BASIC` to `CONTINUOUS` using the argument `CATEGORY CONTINUOUS`?  If so, is it possible to make these run a little faster for pre-push testing?

Note that changing from `BASIC` to `CONTINUOUS`  does not impact what tests get enabled by default when you configure Trilinos manually since the default test category enabled is `NIGHTLY`.  See:

* https://tribits.org/doc/TribitsDevelopersGuide.html#test-test-category

**Comment by kddevin** [comment]
In Zoltan, while two tests run, there are actually many (80+) different executions (different parameter/algorithm options) in each test.  That is why the time per zoltan test is over one minute.  We don't have the resources to break the combined tests into separate tests to satisfy a one-minute maximum.  Changing these tests from BASIC to CONTINUOUS means NO zoltan tests will run in BASIC testing, so I would rather not do that.

**Comment by dridzal** [comment]
In ROL, we could reduce some of the test times to under a minute, however, the question is "on which hardware?"  A minute on a brand-new workstation is about 3 minutes on my 6-year old machine.  Also, we are testing a large number of algorithm options in many tests, which artificially inflates the numbers.


Another question I have is about the testing of MPI builds.  I've been told that for those the only "safe" way to run tests is with "ctest", i.e., that we shouldn't use "ctest -j8" or similar.  I've seen test times increase by a factor of 20 for some tests (when using ctest -jX) because of hardware-specific or environment-specific interpretations of what "mpirun -np 4" means, for example, and how it interacts with ctest options.  If there is no concurrency allowed for ctest, then the only number that matters is the total test time.  Is that correct?



________________________________

**Comment by mhoemmen** [comment]
Just curious -- is there a way for check-in test script users to "opt into" tests beyond BASIC?

**Comment by eric-c-cyr** [comment]
The Teko test that takes a "long time" (1.5 minutes I guess) is large and predates the broad usage of the unit test framework. But it also provides the most complete coverage and is probably the most important test to run. I'm having a hard time believing that this time is really to long. I'm concerned this is just busy work for someone to convert them. Panzer is more broken up, but also the test coverage is really good and I would be loath to cut things out for the sake of being "PT". Is PT just intended to be the lowest most useless bar? Moreover, since we have an automated check-in test script, I would think that the run time is not so much of a big deal.

**Comment by bartlettroscoe** [comment]
> Just curious -- is there a way for check-in test script users to "opt into" tests beyond BASIC?

Yup.  Pass in `--test-categories=NIGHTLY`.  See [`checkin-test.py --help`](https://tribits.org/doc/TribitsDevelopersGuide.html#checkin-test-py-help).

**Comment by bartlettroscoe** [comment]
> We don't have the resources to break the combined tests into separate tests to satisfy a one-minute maximum. Changing these tests from BASIC to CONTINUOUS means NO zoltan tests will run in BASIC testing, so I would rather not do that.

That is fine.  Zoltan and Kokkos test suite times are not a big problem because they are upstream packages.  Therefore, unless you are enabling all tests (like when you change a top-level *.cmake file), then the only people who have to run these test suites are people who are changing these packages.  Therefore, only Zoltan and Kokkos developers are penalized by the longer test times.

The packages that are more the issue are downstream packages that a lot dependencies flow into like Teko and ROL.  I will respond some some of the other comments in a bit and provide some perspective that might be helpful (or not).

**Comment by bartlettroscoe** [comment]
@dridzal, responses to your questions and comments ...

> In ROL, we could reduce some of the test times to under a minute, however, the question is "on which hardware?" A minute on a brand-new workstation is about 3 minutes on my 6-year old machine.

The issue is relative times, not absolute times.  We could do a more detailed analysis but when you have a single test that take 2.5 minutes to run for a test suite that takes 12 minutes to run nearly 2300 tests on 16 cores (see [here](https://github.com/trilinos/Trilinos/issues/482#issuecomment-261101400)), then you can see that this is out of balance.  For the sake of argument, let's say 1 minute is measured on the post-push CI machine that reports these results.  We could come up with better metrics to measure test time imbalance but I don't think the 1 minute goal is too unreasonable for pre-push CI testing on a fast machine. 

> Also, we are testing a large number of algorithm options in many tests, which artificially inflates the numbers. Another question I have is about the testing of MPI builds. I've been told that for those the only "safe" way to run tests is with "ctest", i.e., that we shouldn't use "ctest -j8" or similar.

Who told you that?   If you define your tests correctly you be able to use `ctest -j<n>` where `<n>` is all your cores and CTest should not overload that.

> I've seen test times increase by a factor of 20 for some tests (when using ctest -jX) because of hardware-specific or environment-specific interpretations of what "mpirun -np 4" means, for example, and how it interacts with ctest options.

Again, if the tests are defined correctly, that is not a problem.  You can tell CTest how many total cores your test takes.  See [Running multiple tests at the same time (TRIBITS_ADD_TEST())](https://tribits.org/doc/TribitsDevelopersGuide.html#running-multiple-tests-at-the-same-time-tribits-add-test).  Perhaps there are some tests that need to be fixed in Trilinos?  We can do some experimentation to see if there are problems with the current Trilinos test suite by sampling `top` while we run the test suite with `ctest -j<all-the-cores>` and watch for overloading.  That might be a little tedious so we may need an automated way to do this.  And this is not just an issue for just long running tests.  The is an issue for the entire test suite.  That is a much more serious problem that the one this Issue is considering.

>  If there is no concurrency allowed for ctest, then the only number that matters is the total test time. Is that correct?

Again, if the tests are defined correctly (i.e. correctly telling CTest the total number of cores used for each test) then `ctest -j<n>` will schedule the tests to try to keep `<n>` cores busy but not exceed that many cores.  It is insane to have a machine with 32 cores and then only allow yourself to use 4 of them (the default max number of MPI processes) when running tests.

@eric-c-cyr, responses to your questions and comments ...

> The Teko test that takes a "long time" (1.5 minutes I guess) is large and predates the broad usage of the unit test framework.

Again, judgment about "long time" is relative.  For many application codes, a 1.5 minute test is pretty fast.

> But it also provides the most complete coverage and is probably the most important test to run. I'm having a hard time believing that this time is really too long.

Again, no one said "too long" (you will not find any statement like that I have made here).  It is relative to all the other tests that is all.

>I'm concerned this is just busy work for someone to convert them. Panzer is more broken up, but also the test coverage is really good and I would be loath to cut things out for the sake of being "PT". Is PT just intended to be the lowest most useless bar?

Not sure what "lowest most useless bar" means.  The goals of the pre-push PT test suite and process should be articulated in the Description field in #482.  We can discuss at the next Trilinos leaders meeting if there are questions about this.

> Moreover, since we have an automated check-in test script, I would think that the run time is not so much of a big deal.

That is mostly true, as long as you don't feel that your machine is unusable (because it is running the checkin-test.py script) for too long.

Anyway, I was just reporting what I found in my analysis of the Trilinos test suite while doing #482.  And given the massive build times, the cost of the test suite is not such a huge issue currently.  But if we can bring down the build times (see stories in epic/milestone ["Reduce build times for Trilinos"](https://github.com/trilinos/Trilinos/milestone/22)), then the test times will become more of an issue so we always need to keep an eye on this.  And there are times when you just need to rerun the test suite (like when there is a random failure) and don't need to rebuild and that is when expensive tests have the biggest impact.

We might consider running a larger test suite in post-push CI testing as long as it did not increase the chances that the build would fail.  That way, we could relegate some of these tests from `BASIC` to `CONTINUOUS` and they would get tested in every incremental post-push CI iteration.  Is that a reasonable compromise?  And note that if you are changing your own package, then you can run whatever test suite you want before you run the checkin-test-sems.sh script.  The question is what are you going to force other package developers to have to run pre-push?

I am happy enough to do nothing about this.  But if people complain that the checkin-test-sems.sh script takes too long then at least we analyzed a way to potentially cut down on this some without a lot of effort (i.e. moving the most expensive tests from running pre-push to post-push).

**Comment by dridzal** [comment]
This is very useful; I was not aware of the second option in the example,

NUM_MPI_PROCS  4  NUM_TOTAL_CORES_USED  40


My guess is that if you don't specify NUM_TOTAL_CORES_USED, the behavior may be undefined (or at least not what you expect).  This is the scenario where some tests in ROL were taking a very long time, even though running them with mpirun -np 4 was quick.


In any case, is this a well-tested set of ctest options?  If so, we'll change the tests and examples in ROL accordingly.



________________________________

**Comment by mhoemmen** [comment]
@bartlettroscoe wrote:
> @mhoemme wrote:
> > Just curious -- is there a way for check-in test script users to "opt into" tests beyond BASIC?
>
> Yup. Pass in `--test-categories=NIGHTLY`. See `checkin-test.py --help`.

This says:
```
--test-categories=TESTCATEGORIES
                        . Change the test categories.  Can be 'BASIC',
                        'CONTINUOUS',  'NIGHTLY', or 'HEAVY' (default set by
                        project, see --show-defaults).
```
`--show-defaults` says the default is BASIC.  If I set `--test-categories=NIGHTLY`, does that exclude BASIC tests?  I'm guessing not, but just wanted to make sure.

In general, are these test categories nesting?  For example, does HEAVY include NIGHTLY?

**Comment by bartlettroscoe** [comment]
> In general, are these test categories nesting? For example, does HEAVY include NIGHTLY?

Yes, BASIC, CONTINUOUS, NIGHTLY and HEAVY are nested (PERFORMANCE is not).  See:

* https://tribits.org/doc/TribitsDevelopersGuide.html#test-test-category

I also updated the user documentation to make this more clear:

*https://tribits.org/doc/TribitsBuildReference.html#enabling-different-test-categories

(It will get updated for Trilinos the next time I sync TriBITS to Trilinos.)

**Comment by bartlettroscoe** [comment]
> In any case, is this a well-tested set of ctest options? If so, we'll change the tests and examples in ROL accordingly.

@dridzal, yes, it is very well tested.  See unit tests with `NUM_TOTAL_CORES_USED` for this in:

* http://my.cdash.org/testDetails.php?test=28210159&build=1094039

This was added to support CASL VERA codes that use threading and have different number of MPI processes and threads per process.

If you find any problems with this, please let me know.

**Comment by bartlettroscoe** [comment]
We are no longer going to purse extending the checkin-test-sems.sh (or checkin-test.py) script for Trilinos.  See https://github.com/trilinos/Trilinos/issues/482#issuecomment-266124179.

Closing and won't fix.
