### ISSUE TITLE
Ifpack2:  Ifpack2_Hypre_Serial.cpp.o and Ifpack2_Hypre_Cuda.cpp.o redefinition. 

### ISSUE THREAD

**Issue by JulienLoiseau** [trilinos/Trilinos#8959]
## Question
@trilinos/Ifpack2

I am posting this as a question because I don't know if I am doing something wrong or if it should be an issue. 

The problem: 
I am using Hypre with GPU support and then I would like Ifpack2 to support Kokkos/CUDA and Kokkos/Serial for the Hypre interface. 
Hypre compiles well but when I try to compile Ifpack2 interface I have this error (truncated): 
 
```
CMakeFiles/ifpack2.dir/Ifpack2_Hypre_Cuda.cpp.o: In function `Ifpack2::IFPACK2_CHK_ERRV(int) [clone .localalias.594]':
tmpxft_0000336d_00000000-5_Ifpack2_Hypre_Cuda.cudafe1.cpp:(.text+0x3d0): multiple definition of `Ifpack2::IFPACK2_CHK_ERRV(int)'
CMakeFiles/ifpack2.dir/Ifpack2_Hypre_Serial.cpp.o:tmpxft_00002908_00000000-5_Ifpack2_Hypre_Serial.cudafe1.cpp:(.text+0x3d0): first defined here
CMakeFiles/ifpack2.dir/Ifpack2_Hypre_Cuda.cpp.o: In function `Ifpack2::IFPACK2_CHK_ERR(int)':
tmpxft_0000336d_00000000-5_Ifpack2_Hypre_Cuda.cudafe1.cpp:(.text+0x510): multiple definition of `Ifpack2::IFPACK2_CHK_ERR(int)'
CMakeFiles/ifpack2.dir/Ifpack2_Hypre_Serial.cpp.o:tmpxft_00002908_00000000-5_Ifpack2_Hypre_Serial.cudafe1.cpp:(.text+0x510): first defined here
CMakeFiles/ifpack2.dir/Ifpack2_Hypre_Cuda.cpp.o:(.bss+0x81e0): multiple definition of `Ifpack2::FunctionParameter::hypreMapIntFunc_[abi:cxx11]'
CMakeFiles/ifpack2.dir/Ifpack2_Hypre_Serial.cpp.o:(.bss+0x81e0): first defined here
CMakeFiles/ifpack2.dir/Ifpack2_Hypre_Cuda.cpp.o:(.bss+0x81b0): multiple definition of `Ifpack2::FunctionParameter::hypreMapDoubleFunc_[abi:cxx11]'
CMakeFiles/ifpack2.dir/Ifpack2_Hypre_Serial.cpp.o:(.bss+0x81b0): first defined here
CMakeFiles/ifpack2.dir/Ifpack2_Hypre_Cuda.cpp.o:(.bss+0x8180): multiple definition of `Ifpack2::FunctionParameter::hypreMapDoubleIntFunc_[abi:cxx11]'
CMakeFiles/ifpack2.dir/Ifpack2_Hypre_Serial.cpp.o:(.bss+0x8180): first defined here
...
 ```

It seems that Ifpack2 creates both Kokkos_CUDA and Kokkos_Serial objects and of course this causes functions to be redefined. 
The conflicts are from: Ifpack2_Hypre_Cuda.cpp.o and Ifpack2_Hypre_Serial.cpp.o
I have the same problem when I am compiling with both OpenMP for host and CUDA for the device.

**Comment by jhux2** [comment]
@trilinos/ifpack2 @csiefer2 @cgcgcg

**Comment by csiefer2** [comment]
Yeah, that looks like a bug alright.  Weve never actually tried Hypre GPU builds before, so I'm not surprised it doesn't work.

What version of Hypre and what options are you using to build it?

**Comment by JulienLoiseau** [comment]
My options: 

For Tpetra/Xpetra/Epetra: 
```
-DTpetra_INST_INT_INT:BOOL=ON
-DTpetra_INST_INT_LONG:BOOL=OFF
-DTpetra_INST_INT_LONG_LONG:BOOL=OFF
-DTpetra_INST_SERIAL:BOOL=ON

-DXpetra_Epetra_NO_64BIT_GLOBAL_INDICIES:BOOL=ON
```

For Kokkos:
```
-DKokkos_ENABLE_SERIAL:BOOL=ON
-DTPL_ENABLE_CUDA:BOOL=ON
-DKokkos_ENABLE_CUDA:BOOL=ON
-DKokkos_ENABLE_OPENMP:BOOL=OFF
```

I am also using the Kokkos' nvcc_wrapper.

**Comment by csiefer2** [comment]
Options for Hypre?

**Comment by JulienLoiseau** [comment]
For Hypre we are using the configure (not the cmake) build to be able to use the options for either OpenMP or CUDA. 
You can find our full file at: 
https://github.com/amanzi/amanzi/blob/feature/openmp-build/config/SuperBuild/include/Build_HYPRE.cmake

The flag used for Serial+CUDA: 
```
                         --with-MPI
                         --enable-shared
                         --with-lapack-lib= ...
                         --with-blas-lib= ... 
 #cuda 
                         --with-cuda
                         --enable-cusparse
                         --enable-unified-memory
                         CUDA_HOME=...
                         HYPRE_CUDA_SM=70 
# superlu / dspuerlu 
                         --with-superlu
                         --with-superlu-include= ...
                         --with-superlu-lib= ...
                         --with-dsuperlu
                         --with-dsuperlu-include=... 
                         --with-dsuperlu-lib=...
```

**Comment by csiefer2** [comment]
Ifpack2+Hypre builds just fine for me (surprisingly) if you only instantiate CudaNode and not CudaNode and SerialNode.

Is that an option for you?

**Comment by JulienLoiseau** [comment]
I will try this, could you try to build with OpenMP + CUDA? Then this problem should arise for you too anyways.

**Comment by cgcgcg** [comment]
@JulienLoiseau Please pull develop and see if this is fixed for you.

**Comment by JulienLoiseau** [comment]
I was able to install with Serial + CUDA and OpenMP + CUDA. 
Thank you!
