### ISSUE TITLE
 TrilinosCouplings_Poisson2D_pn=4_tpetra_MPI_1 failing in current CI build

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#896]
**CC:** @trilinos/framework@, @csiefer2 

**Description:**

It appears that the commits:

```
commit f76752c69bf5231f98e0ac77436dce44e15a57aa
Author: Chris Siefert <csiefer@sandia.gov>
Date:   Wed Nov 30 15:30:33 2016 -0700

    TrilinosCouplings: Debugging gunk for one-grid

M       packages/trilinoscouplings/examples/scaling/example_Poisson2D_pn_tpetra.cpp

commit e7ba523edb56fd067366fe1455903cedb2ee89a0
Author: Chris Siefert <csiefer@sandia.gov>
Date:   Wed Nov 30 15:30:05 2016 -0700

    MueLu: Adding support for block relaxation on coarse grids

M       packages/muelu/src/Interface/MueLu_ParameterListInterpreter_def.hpp
```

broke the test TrilinosCouplings_Poisson2D_pn=4_tpetra_MPI_1 in the new CI build as shown here:

* http://testing.sandia.gov/cdash/index.php?project=Trilinos&parentid=2636238

**Comment by bartlettroscoe** [comment]
@csiefer2, 

Can you please see about fixing this and using the updated [checkin-test-sems.sh] on an SNL RHEL 6 machine to push the fix?

If you can't get to this right away, then we must disable this test since it will block people from pushing with the checkin-test-sems.sh script.  This this test will **not** be disabled in post-push CI testing so that that people can see that it is failing (but it will block the update from the 'develop' to the 'master' branch).

**Comment by csiefer2** [comment]
TrilinosCouplings isn't something that should be tested in CI.

**Comment by bartlettroscoe** [comment]
> TrilinosCouplings isn't something that should be tested in CI.

TrilinosCouplings is being enabled by at least one internal Trilinos customer and therefore it was included in the set of Primary Tested packages.  See #410 and the details about which customer this is in [TRIL-59](https://sems.sandia.gov/jira/browse/TRIL-59?focusedCommentId=13151&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-13151).   Actually, if you clone the repo `git@gitlab-ex.sandia.gov:rabartl/trilinos_pt_packages.git` and look at the file `combined_list_of_trlinos_customer_enables.sh` you can see exactly which internal Trilinos customer this is (and it is arguably the most important Trilinos customer).

Therefore, we need to either tell that customer to stop enabling and/or using TrilinosCouplings or (I would argue) we should be testing it in pre-push CI testing.  But if other Trilinos developers think that we should remove TrilinosCouplings from pre-push CI testing, I am fine with that.   But this should be a orderly process.  The selection of PT packages was very analytical.

But note that TrilinosCouplings does not take very long to build and test so I don't see the major objection to leaving it in pre-push PT CI testing given that an important Trilinos customer is enabling it.

@csiefer2, can you pleae give the new checkin-test-sems.sh script a try and fix this?  Or if you don't have to time to fix this right away, should I disable this test in pre-push testing so that it will not block other people's pushes?  We have to stay on top of this CI build or it falls apart pretty fast.  Yes, I will get to https://github.com/TriBITSPub/TriBITS/issues/152 but there are other things that I have to get done first.

**Comment by jwillenbring** [comment]
Given the customer who is using TrilinosCouplings, I think we should try very hard to avoid disabling the package all together.

**Comment by bartlettroscoe** [comment]
> Given the customer who is using TrilinosCouplings, I think we should try very hard to avoid disabling the package all together.

@jwillenbring, you mean in "disable the package all together" CI testing right?  It could still run in post-push Nightly testing.  But given that package has to configure and build in order for that important customer to get an update of Trilinos, then that would increase the chances of delaying the update of Trilinos to that customer.  The cost of testing it in CI testing seems small for including it in CI testing (just a few extra minutes to build and test) and the risk of breaking the update to that customer seems high if it were excluded from CI testing (because TrilinosCouplings seems to break more than other packages).

Seems like something higher-ups should decide.  @maherou, what do you think?

Any any case, while we debate this I will disable the test for now in pre-push (not post-push) CI testing.

**Comment by csiefer2** [comment]
I don't have access to that repo.  Please email me that info.

@bartlettroscoe Or you could just wait the 10 minutes for me to finish testing fixes.

**Comment by bartlettroscoe** [comment]
> I don't have access to that repo.

Do you have an account on `https://gitlab-ex.sandia.gov`?  If you don't, get one and then tell me your userid (offline in email) and I will provide you access to that repo.

> Or you could just wait the 10 minutes for me to finish testing fixes.

I will wait :-)

Thanks for taking care of this.

**Comment by csiefer2** [comment]
Fix pushed.

**Comment by bartlettroscoe** [comment]
Can verify it is fixed:

* http://testing.sandia.gov/cdash/index.php?project=Trilinos&parentid=2637486

Thanks!
