### ISSUE TITLE
SEACAS: Bad header path in Iovs_exodus_DatabaseIO.h

### ISSUE THREAD

**Issue by sayerhs** [trilinos/Trilinos#8967]
## Bug Report
@trilinos/seacas

### Description
PR #8951 breaks https://github.com/exawind/nalu-wind with the following error

```
In file included from /home/sanantha/exawind/source/nalu-wind/src/Realm.C:158:
/nopt/nrel/ecom/exawind/exawind-2020-09-21/install/gcc/trilinos-2021-04-04/include/Iovs_exodus_DatabaseIO.h:18:10: fatal error: visualization/utils/Iovs_Utils.h: No such file or directory
 #include <visualization/utils/Iovs_Utils.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

This line https://github.com/trilinos/Trilinos/blob/7ecf9753b5c093035f3d877bf6ccdbc2a6459939/packages/seacas/libraries/ioss/src/visualization/exodus/Iovs_exodus_DatabaseIO.h#L18 should be 

```C++
#include <Iovs_Utils.h>
``` 

when Trilinos is used from an installed location. 

### Steps to Reproduce
1. SHA1:  43df5d7
1. CMake configure output: [cmake_configure.txt](https://github.com/trilinos/Trilinos/files/6254883/cmake_configure.txt)

Cc: @alanw0 @jrood-nrel

**Comment by sayerhs** [comment]
It appears that `parseCatalystFile` has been removed from `Iovs_exodus::DatabaseIO`. https://github.com/trilinos/Trilinos/blob/7ecf9753b5c093035f3d877bf6ccdbc2a6459939/packages/seacas/libraries/ioss/src/visualization/exodus/Iovs_exodus_DatabaseIO.h#L53

Is this capability not supported anymore?

**Comment by gsjaardema** [comment]
I can fix the include path.  

@tjotaha, @jeffmauldin -- Can you answer the `parseCatalystFile` question

**Comment by tjotaha** [comment]
@sayerhs I forgot to remove this commented out code from the header file. The parse Catalyst file capability is now controlled by an IOSS property that specifies the name of the file to parse.  We are planning to modify Nalu to support this new API.

**Comment by sayerhs** [comment]
Thanks @gsjaardema I will test again once #8971 is merged. 

@tjotaha Great, let us know how we can help. For now we have created a compile time option to [enable/disable Catalyst support in Nalu-Wind](https://github.com/Exawind/nalu-wind/blob/master/src/Realm.C#L792-L799) to workaround this issue.
