### ISSUE TITLE
Clean configure with only Tpetra solver stack

### ISSUE THREAD

**Issue by spdomin** [trilinos/Trilinos#900]
I formally deprecated Epetra in my application. However, when trying to remove Epetra code from my configure, there is still a tangled web of dependencies.

Specifically, amesos2 still requires amesos which requires Epetra. I thought that this was resolved by @srajama1?

https://github.com/trilinos/Trilinos/issues/649

However, my master and develop Trilinos branch is still complaining.

commit 293814324c1fcdf92e338b5924464f5b026dae56
Author: Alejandro Mota <amota@sandia.gov>
Date:   Fri Dec 2 16:44:47 2016 -0800

   *** ERROR: Setting Trilinos_ENABLE_Amesos2=OFF which was 'ON' because Amesos2 has a required library dependence on disabled package Amesos!

**Comment by srajama1** [comment]
@spdomin #649 is still open because it was not resolved. Tech-X is working through the stack to get this done. @krcb @jwillenbring. If this is a duplicate of #649 we can close this.
