### ISSUE TITLE
Automated testing with docker containers

### ISSUE THREAD

**Issue by tawiesn** [trilinos/Trilinos#901]
This story is to collect all ideas for setting up a checkin/testing environment based on docker containers. The idea is to develop Trilinos on platforms different than Linux but make sure that all tests run on selected Linux platforms before checkin the changes to the Trilinos repository.
@jwillenbring @maherou

**Comment by tawiesn** [comment]
Task list:

1. Create a general docker image for testing Trilinos
2. Create a shell script/python program to run the Trilinos compiler which internally compiles Trilinos with the local changes included, runs the test suite (check-in script, no-push) and decides whether a push to the github repository would be allowed
3. If the test suite succeeds without error, the changes can be pushed to the develop branch. Otherwise, give the user instructions to log in to the test docker container and analyze the error messages.

**Comment by tawiesn** [comment]
List of features for the docker image:

- We need one (or several) base images which provide the necessary TPLs and a build system (compilers...). The images tawiesn/dev-base and tawiesn/dev-tpl on github can be examples or starting points.
- (optional) We should have a Sandia-internal base image with parts of the SEMS environment
- The Dockerfile for the base images should be published. We should have a separate repository for them on github or just add them to the Trilinos sources (in a subfolder in sampleScripts...)
- For simplicity, we have to copy a packed version of the Trilinos sources into the container. This can be done by the external test script (see discussion later). The Trilinos sources shall contain potential changes by the user that he wants to test.
- The container runs an internal script (call it "compile_and_test_trilinos.sh") which does the following:

    1. Unpack the Trilinos sources in the container
    2. Create a build directory
    3. Configure and make Trilinos
    4. Run the test suite (checkin script with no-push option set)
    5. Check the return value for an error
    6. Exit the container with the return value of the checkin script

**Comment by tawiesn** [comment]
Driver sciprt for the Trilinos test container:
- The driver script should be a shell script or a python program which must run on the host system. For compatiblity (Windows, Mac, Linux), a python script could be a good option.
- The script should do the following

    1. Create a new contianer of the dev-tpl image (the base image which brings all dependencies for compiling Trilinos). Store the container name in a variable CONTAINER_NAME
    2. Pack the Trilinos sources into a tar.gz file. The folder must be provided by the user (e.g. as parameter)
    3. Copy the tar.gz file into the container using, e.g.
`docker cp Trilinos-develop.tar.gz CONTAINER_NAME:/home/test/trilinos`
    4. Run the "compile_and_test_trilinos.sh" script within the container
`docker exec CONTAINER_NAME /home/test/compile_and_test_trilinos.sh`
    5. Check the return value of the test script. If successful give 0 as return code. The user can then safely push the changes to the repository. Or the native checkin script can use this return value to initiate the push. We have to do the push on the host system, since we cannot push from within the container as long as we do not set the corresponding user name and ssh keys within the linux container. The container should be deleted using
`docker rm CONTAINER_NAME`
    6. If there is a compiler error or the test suite is failing the script should return an error code and print the following line:
```
docker start CONTAINER_NAME
docker attach CONTAINER_NAME
...
exit
```
 
which tells the user how to log in to the container and check the error messages.
- (optional) we can pipe the container output into a file that the user can check and delete the container. Disadvantage: if we keep the container the user can log into the container and try to fix the problem in real time. Nevertheless, once he has found a fix, he has to copy it back to the native  host system and run the script again.
- The user should call the "docker-test-trilinos.py" script using something like
`./docker-test-trilinos.py --trilinos-path=/home/user/trilinos`

**Comment by tjfulle** [comment]
@tawiesn, I used `Dockerfile`s from your github page to make a docker image to run the Trilinos tests (on a Mac), one issue I have run in to is that read/write times from mounted volumes is too slow for practical use.  e.g., I started a container with `-v /projects/sems:/projects/sems` so I could use the `sems` modules, but it would take minutes to compile a single file.  No problem, I'll just tar up `/projects/sems` and create a container `ADD`ing `projects/sems` in the `Dockerfile` - no bueno, the resulting image overflows the size allowed by Docker.  I think this will work, but a custom `/projects/sems` directory will have to be made containing only, say, a single `gcc` stack.

That is all assuming you would use the `sems` environment, of course...

**Comment by tawiesn** [comment]
@tjfulle Yes, it is a well-known issue that mounting files is extremely slow. There are some workarounds using NFS to mount host folders ([that's what i'm using](https://github.com/brikis98/docker-osx-dev)). However, it only works for the docker-machine solution on the Mac. As far as i know it is not compatible to the new Docker for Mac toolbox. With the NFS mount you get nearly native speed when compiling, but it is somewhat fragile and probably not the right thing for a general test container.
Yes, when using sems we have to tar a single gcc stack with the corresponding libraries and use that for creating the container.

**Comment by aprokop** [comment]
@tawiesn [DataTransferKit](https://github.com/ORNL-CEES/DataTransferkit) is doing something very similar. It has a pre-built container with TPLs, and Jenkins simply launches Docker containers, and builds and tests in them. Can get more details from the person in charge if necessary, but the process is not too complicated.

**Comment by tjfulle** [comment]
@tawiesn, ya, I looked in to several different solutions to speed up shared volumes, but it looks like the Docker devs are aware of the problem and working on a native solution (and I don't want to sink a bunch of time in to figuring something else out).  I think that the `sems` sync tool can be used to selectively sync only those things that are wanted - it may already have the capability to make a stripped down `sems` environment needed for a docker image.
