### ISSUE TITLE
Framework: Test PR testing with new loadenv capability

### ISSUE THREAD

**Issue by jwillenbring** [trilinos/Trilinos#9010]
## Enhancement
@trilinos/framework 

The newly developed loadenv capability is ready for testing within Trilinos PR testing. Since @william76 developed much of the capability, we want someone else to integrate it into the current system. He could consult as necessary. We can talk about tasking and priority at an upcoming standup. This is very important, and somewhat urgent, but not stop-the-line urgent.

**Comment by jmgate** [comment]
You may also want to consult with @e10harvey for how to integrate the various repositories into Trilinos, as he's figured out how to get them in the right place w.r.t. one another in the midst of Jenkins testing.  Note that this issue may depend on us at least completing a first pass on the documentation for `LoadEnv` first.

**Comment by wadeburgess** [comment]
As per Jim W, closing this issue.
