### ISSUE TITLE
CMake:  How to identify Trilinos builds that use OpenMP

### ISSUE THREAD

**Issue by TBird2001** [trilinos/Trilinos#9020]
## Question
@trilinos/CMake

So, I understand how to build Trilinos with OpenMP support using:
```
-D Trilinos_ENABLE_OpenMP=ON
```
However, I'm a bit lost as to how an importing project can know whether OpenMP is "ON".

My thought of how this would work is as follows. I would have the Xyce CMake look for OpenMP in Trilinos. Then, if it's there, do a `find_package(OpenMP)` and use the `OpenMP::OpenMP_CXX` target. Xyce doesn't use any threading (at the moment), so we have no need to include it all the time. Thoughts on the best way to approach this?

Tagging @bartlettroscoe, since maybe he can help.

**Comment by jjellio** [comment]
In general, most modern Trilinos code won't specifically know that OpenMP is there - instead, you program against Kokkos (I'd check out some Kokkos tutorials). The gist is write `parallel_foo` constructs - and if Kokkos is built for an execution space, then Kokkos will make `parallel_foo` into the right thing. The trilinos libs (tpetra, muelu, etc) are templated so that if you construct a vector or matrix, it will land in the `default` execution space. That's all a gross simplification  (it's pretty abstract) - I'd checkout some Kokkos examples that will convey the general ideas (memory spaces and execution spaces)

**Comment by bartlettroscoe** [comment]
> I'm a bit lost as to how an importing project can know whether OpenMP is "ON".

@TBird2001, I don't think there is a direct way to know that just from importing the installed `TrilinosConfig.cmake` file.  There are a number of configure-time attributes like this that could be injected into the installed `<Package>Config.cmake` files and made known to down-stream clients calling `find_package(<Package>)`.  If there was enough of a demand, it would not be that hard to provide a mechanism to be able to do that in a maintainable way.  But that would actually be a [TriBITS feature request](https://github.com/TriBITSPub/TriBITS/issues) and would take some work to implement.

**Comment by TBird2001** [comment]
Thanks for your comments, @jjellio and @bartlettroscoe; they were definitely helpful to my thinking. As I was exploring this, I found that Kokkos exports a CMake list, `Kokkos_DEVICES` that contains `OPENMP` if Kokkos was compiled with OpenMP capabilities. At this point, I'm going to use that as a conditional for our own search for OpenMP. If that proves to not be robust, I have some other approaches in mind.

I'm going to leave this issue open for the time being in case a related question comes up in the short term. After a while, if things prove to be stable, I'll close it.

**Comment by bartlettroscoe** [comment]
@trilinos/framework, this is something you may want to add to your backlog.  (That is, exporting attributes like `Trilinos_ENABLE_OpenMP` to `TrilinosConfig.cmake`.)

**Comment by wadeburgess** [comment]
Migrated to Jira

**Comment by bartlettroscoe** [comment]
FYI: I am going to be extending TriBITS shortly in general to add more info like this to the installed `<Package>Config.cmake` and `<Project>Config.cmake` files.
