### ISSUE TITLE
Framework: Create exploratory PR build using the new SEMS spack-cm TPL tool

### ISSUE THREAD

**Issue by ZUUL42** [trilinos/Trilinos#9021]
## Enhancement
@trilinos/framework 

What feature/addition is needed?  How does this differ from what we currently
have?  Are there any alternative solutions you've considered?  Do you have
suggestions on implementation?  How has the lack of this feature affected you? 
What are you trying to accomplish?  What specifically must we demonstrate to
call this work complete?

With the Spack based SEMS TPL v2 tool being released in beta, a PR build should be put together that uses this new tool to test it out.
- [ ] Determine a best candidate current PR build to use as a test case, one that uses only TPLs in the new tool's current offerings.
- [ ] Manually build Trilinos using the SEMS TPL v2 tool
- [ ] Create a Jenkins job that uses the tool
- [ ] Look into further use of the new tool

**Comment by wadeburgess** [comment]
Migrated to Jira
