### ISSUE TITLE
Framework:  PR tests with CUDA need to enable COMPLEX data types

### ISSUE THREAD

**Issue by kddevin** [trilinos/Trilinos#9025]
## Bug Report
@trilinos/framework 
@ccober6 @jwillenbring @prwolfe @trilinos/muelu 

### Description

With CUDA, one cannot use std::complex in device kernels, so Trilinos goes to great lengths to cast to and use Kokkos::Complex when users request std::complex.  This "feature" is needed only for CUDA builds; std::complex will work elsewhere.

Trilinos' PR tests appear to not enable COMPLEX in CUDA builds, however, so the translations to Kokkos::Complex are not being exercised.  

Please add 
```
-D Trilinos_ENABLE_COMPLEX=ON \
-D Teuchos_ENABLE_COMPLEX=ON \
-D Tpetra_INST_COMPLEX_DOUBLE=ON \
```
to one of the CUDA PR tests.  Thanks!  

(My guess is that codes will have some clean-up to do when this feature is enabled.  Is this feature used in any of the nightly or promotion tests?)

### Steps to Reproduce

Here's a build/test that brought the issue to our attention:
CUDA Builds, COMPLEX on as shown above, build package MueLu, Belos, Amesos2, Ifpack2.  
Run MueLu_UnitTestsTpetra_MPI_1

1. SHA1:  [insert here]
1. Configure script:  [attach here]
1. Configure log:  [attach here]
1. Build log:  [attach here]
1. Input deck:  [attach here]
1. Do this.
1. Do that.
1. Shake fist angrily at computer.
1. Run log:  [attach here]

**Comment by jjellio** [comment]
Karen, how does this differ from building with `load-env.sh ...-complex` ? (seems the two should be made identical if they aren't).  For debugging complex issues, I've been using the ATDM load-env stuff...

**Comment by jjellio** [comment]
@kddevin I have an ATS2 complex build, and my "atdm" load-env stuff w/-complex, is giving me these CMakeCache variables:

```
[jjellio@vortex78 build-ats2-complex]$ grep COMPLEX CMakeCache.txt 
// enabled during a Trilinos build with Trilinos_ENABLE_COMPLEX_DOUBLE.
KokkosKernels_INST_COMPLEX_DOUBLE:BOOL=ON
// enabled during a Trilinos build with Trilinos_ENABLE_COMPLEX_FLOAT.
KokkosKernels_INST_COMPLEX_FLOAT:BOOL=OFF
Kokkos_ENABLE_COMPLEX_ALIGN:BOOL=OFF
Teuchos_ENABLE_COMPLEX:BOOL=TRUE
Thyra_ENABLE_COMPLEX:BOOL=ON
//  This is currently ON if Teuchos_ENABLE_COMPLEX is ON.  The
Tpetra_INST_COMPLEX_DOUBLE:BOOL=ON
Tpetra_INST_COMPLEX_FLOAT:BOOL=OFF
Trilinos_ENABLE_COMPLEX:BOOL=ON
Trilinos_ENABLE_COMPLEX_DOUBLE:BOOL=ON
Trilinos_ENABLE_COMPLEX_FLOAT:BOOL=OFF
//Test CXX_COMPLEX_BLAS_WORKS
CXX_COMPLEX_BLAS_WORKS:INTERNAL=1
CXX_COMPLEX_BLAS_WORKS_COMPILED:INTERNAL=TRUE
CXX_COMPLEX_BLAS_WORKS_EXITCODE:INTERNAL=0
HAVE_COMPLEX_BLAS:INTERNAL=NOT;HAVE_COMPLEX_BLAS_PROBLEM;OR;HAVE_FIXABLE_COMPLEX_BLAS_PROBLEM;OR;HAVE_VECLIB_COMPLEX_BLAS
HAVE_COMPLEX_BLAS_PROBLEM:INTERNAL=FALSE
HAVE_ML_COMPLEX_MAXWELL:INTERNAL=OFF
HAVE_TEUCHOS_COMPLEX:INTERNAL=ON
HAVE_THYRA_COMPLEX:INTERNAL=ON
HAVE_TPETRATSQR_COMPLEX:INTERNAL=ON
HAVE_TPETRA_COMPLEX_DOUBLE:INTERNAL=ON
HAVE_TPETRA_COMPLEX_FLOAT:INTERNAL=OFF
HAVE_TPETRA_INST_COMPLEX_DOUBLE:INTERNAL=ON
HAVE_TPETRA_INST_COMPLEX_FLOAT:INTERNAL=OFF
//Test KOKKOSKERNELS_TPL_BLAS_RETURN_COMPLEX
KOKKOSKERNELS_TPL_BLAS_RETURN_COMPLEX:INTERNAL=1
KOKKOSKERNELS_TPL_BLAS_RETURN_COMPLEX_COMPILED:INTERNAL=TRUE
KOKKOSKERNELS_TPL_BLAS_RETURN_COMPLEX_EXITCODE:INTERNAL=0
Tpetra_INST_COMPLEX_DOUBLE_DEFAULT:INTERNAL=ON
Tpetra_INST_COMPLEX_FLOAT_DEFAULT:INTERNAL=OFF
```

I'm curious about this stuff - as Issue (closed) #8474 seems to show some kinda build with it

Clearly from that issue+PR this should be tested, since it seems fragile.

**Comment by kddevin** [comment]
Hmmm, @jjellio .  I don't understand the entire landscape.  When I build on the ascicgpu machines with the following CMake, I get "unspecified launch errors" from CUDA in MueLu.  Fixes such as #9029 make the errors go away.  And the fixes make sense to me, as std::complex<> can't be used on device.  The question, then, is why the atdm builds don't show the same behavior on vortex.
```
module load sierra-devel/nvidia
module swap sierra-cmake/3.17.5
cmake  \
  -D Kokkos_ENABLE_DEBUG=ON \
  -D CMAKE_BUILD_TYPE=DEBUG \
  -D TPL_ENABLE_MPI=ON \
  -D TPL_ENABLE_CUDA=ON \
  -D MPI_BIN_DIR=${MPI_BIN} \
  -D MPI_EXEC_MAX_NUMPROCS=16 \
  -D MPI_EXEC_POST_NUMPROCS_FLAGS=--oversubscribe \
  -D Trilinos_ENABLE_EXPLICIT_INSTANTIATION=ON \
  -D Trilinos_ENABLE_ALL_OPTIONAL_PACKAGES=OFF \
  -D Trilinos_ENABLE_TESTS=OFF \
  -D Trilinos_ENABLE_EXAMPLES=OFF \
  -D Trilinos_VERBOSE_CONFIGURE=OFF \
  -D Trilinos_ENABLE_COMPLEX=ON \
  -D Teuchos_ENABLE_COMPLEX=ON \
  -D Trilinos_ENABLE_Tpetra=ON \
  -D Tpetra_ENABLE_TESTS=ON \
  -D Tpetra_ENABLE_EXAMPLES=ON \
  -D Trilinos_ENABLE_MueLu=ON \
  -D MueLu_ENABLE_TESTS=ON \
  -D MueLu_ENABLE_EXAMPLES=ON \
  -D Trilinos_ENABLE_Amesos2=ON \
  -D Amesos2_ENABLE_TESTS=ON \
  -D Amesos2_ENABLE_EXAMPLES=ON \
  -D Trilinos_ENABLE_Zoltan2=ON \
  -D Zoltan2_ENABLE_TESTS=ON \
  -D Zoltan2_ENABLE_EXAMPLES=ON \
  -D Trilinos_ENABLE_Belos=ON \
  -D Belos_ENABLE_TESTS=ON \
  -D Belos_ENABLE_EXAMPLES=ON \
  -D Trilinos_ENABLE_Ifpack2=ON \
  -D Ifpack2_ENABLE_TESTS=ON \
  -D Ifpack2_ENABLE_EXAMPLES=ON \
  -D Trilinos_ENABLE_NOX=ON \
  -D NOX_ENABLE_TESTS=ON \
  -D NOX_ENABLE_EXAMPLES=ON \
  -D Trilinos_ENABLE_Teko=ON \
  -D Teko_ENABLE_TESTS=ON \
  -D Teko_ENABLE_EXAMPLES=ON \
  -D Trilinos_ENABLE_Stratimikos=ON \
  -D Stratimikos_ENABLE_TESTS=ON \
  -D Stratimikos_ENABLE_EXAMPLES=ON \
  -D Tpetra_INST_COMPLEX_DOUBLE=ON \
  -D Tpetra_INST_INT_LONG_LONG=ON \
  -D Tpetra_INST_SERIAL=OFF \
  -D Tpetra_INST_CUDA=ON \
  -D Tpetra_ENABLE_CUDA_UVM=ON \
  -D Kokkos_ARCH_VOLTA70=ON \
  -D Kokkos_ENABLE_CUDA=ON \
  -D Kokkos_ENABLE_CUDA_UVM=ON \
  -D Kokkos_ENABLE_CUDA_RELOCATABLE_DEVICE_CODE=OFF \
  -D Kokkos_ENABLE_CUDA_LAMBDA=ON
..
```

**Comment by jjellio** [comment]
On vortex, to help with the all reduce issues, I've only been building Tpetra+Belos.

```bash
#!/bin/bash

TRILINOS=$(cd ..; pwd)
# Load env and configure on the login node
source $TRILINOS/cmake/std/atdm/load-env.sh ats2-cuda-complex-release-shared

cmake -GNinja \
  -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
  -DTrilinos_ENABLE_TESTS=ON \
  -DTrilinos_ENABLE_Tpetra=ON \
  -DTrilinos_ENABLE_Belos=ON \
  $TRILINOS
```

I'd like to know what is the right way to get complex, as my efforts on El Cap are using the prior (with all packages on). 

It could be something to do with UVM and ATS (address translation service) - Vortex/Power9 + Volta allows unified memory access (a curse and blessing) - on vortex, you can `malloc` and access the memory from the device. I'm wondering if the asicicgpu machines don't support that - which makes them better candidates to test UVM removal (as you won't get silently saved by the OS)... I'm don't know off hand how to test if ATS is available. In the past I've flipped Kokkos' allocator to malloc to rule out nutty memory behavior. (nightmares we did during EMPIRE's bug a while back).

**Comment by kddevin** [comment]
```
 -D Trilinos_ENABLE_COMPLEX=ON \
-D Teuchos_ENABLE_COMPLEX=ON \
-D Tpetra_INST_COMPLEX_DOUBLE=ON \
```

**Comment by jwillenbring** [comment]
@ZUUL42 Could you fire off a PR that adds the following options to the existing base CUDA build?

>  -D Trilinos_ENABLE_COMPLEX=ON \
-D Teuchos_ENABLE_COMPLEX=ON \
-D Tpetra_INST_COMPLEX_DOUBLE=ON \

After the PR reports, we can look at the number of errors and decide what to do from there. Thanks.

**Comment by ZUUL42** [comment]
I added the flags to both cuda_10.1.105 builds on [a test branch](https://github.com/trilinos/Trilinos/compare/develop...ZUUL42:complex).
Results: [CDash](https://testing.sandia.gov/cdash/index.php?project=Trilinos&display=project&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=63&value1=complex-test-Trilinos_pullrequest_cuda_10.1.105&field2=buildstamp&compare2=63&value2=Experimental)
We do get 2 test failures, both MueLu, on the normal (UVM ON) build.

Just to make sure, do we want these on the cuda_10.1.105[_uvm_on] build and/or the cuda_10.1.105_uvm_off build?
Once we get those failures cleaned up, I can get a PR in for one or both.

**Comment by cgcgcg** [comment]
@ZUUL42 PR #9122 should take care of the MueLu test failures.

**Comment by ZUUL42** [comment]
Looks good.
[CDash](https://testing.sandia.gov/cdash/index.php?project=Trilinos&display=project&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=63&value1=complex-test-Trilinos_pullrequest_cuda_10.1.105&field2=buildstamp&compare2=63&value2=Experimental&field3=buildstarttime&compare3=83&value3=2021-05-10)

Now do we want complex turned on for both builds or just one of them?
- cuda 10.1.105 [uvm on]
and/or
- cuda 10.1.105 uvm off

Currently both of them are run for all normal PRs and Master Merge PRs.

**Comment by jwillenbring** [comment]
@ZUUL42 Per @kddevin please turn COMPLEX on for both the UVM on and off builds.

**Comment by ZUUL42** [comment]
Complex data types have been turned on for the UVM 10.1.105 builds, both UVM on and off.
We have not seen a significant increase in build times.

**Comment by jwillenbring** [comment]
Since #9126 was merged, this can be closed.
