### ISSUE TITLE
Amesos missing Xpetra multivector

### ISSUE THREAD

**Issue by VictorEijkhout** [trilinos/Trilinos#9026]
## Bug Report
@trilinos/amesos 

### Description
Installation fails. See attached log.
[trilinos_amesos.zip](https://github.com/trilinos/Trilinos/files/6328107/trilinos_amesos.zip)

**Comment by cgcgcg** [comment]
Not an Amesos developer, but I see that you set
```
-D Trilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=OFF
```
You could try setting that to `ON`. (Or removing it entirely, since `ON` is the default.)

**Comment by jjellio** [comment]
Is Trilinos still supporting non-ETI builds? (I'm pretty sure the default was toggled to ON a while back - but I don't know if that means it's on the table for deprecation)

**Comment by ccober6** [comment]
Yes, Trilinos would still like to support non-ETI builds.  This is needed for builds with user specified types (e.g., Scalar).  I believe the Framework will have/has a PR build to cover this, but many packages have regressed?  @jwillenbring do you have an update on this?

**Comment by jwillenbring** [comment]
#5729 Is tracking the work for adding a no-ETI build. There are some outstanding issues, and probably more that are currently reflected in the ticket. Other issues took priority for a  while. @zuul42 started looking at this again last week.

**Comment by VictorEijkhout** [comment]
On , 2021Apr20, at 11:10, Christian Glusa ***@***.******@***.***>> wrote:


-D Trilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=OFF


You could try setting that to ON. (Or removing it entirely, since ON is the default.)

With Trilinos 12 I had:

  -D Trilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON \
  -D Tpetra_INST_INT_LONG_LONG:BOOL=ON \
  -D Tpetra_INST_INT_INT:BOOL=ON \

However now this gives:

-- Tpetra: Validate global ordinal setting ...
CMake Error at packages/tpetra/CMakeLists.txt:1148 (MESSAGE):
  Tpetra requires only one global ordinal, but more than one are set:
  {int;long long}.

1. Removed all the explicit instantiation: yay! Now it builds correctly.
2. Was Trilinos 12 able to build multiple integer precisions and 13 doesn’t? In that case I may need to figure out how to build multiple installations.
3. And now on to my ticket 9013 about python problems.

Victor.

**Comment by cgcgcg** [comment]
@VictorEijkhout 
Yes, explicit instantiation of multiple global ordinal types was deprecated and then removed. I believe this document
https://github.com/trilinos/Trilinos/wiki/Trilinos_v12_code_deprecation.pdf
was sent out to the user list. Personally, I now have one build where I set `-D Tpetra_INST_INT_INT:BOOL=ON` for use with the old Epetra stack and the equivalent Tpetra stack, and another one where I don't set anything, since `long long` global ordinals are the default.

**Comment by VictorEijkhout** [comment]
Hm. I thought I responded: I seem to be able to conclude a build successfully. Thanks.
