### ISSUE TITLE
Allow github integration tool "reviewable" access to repo

### ISSUE THREAD

**Issue by jhux2** [trilinos/Trilinos#903]
@bmpersc @jwillenbring 

This is a request to make the Trilinos repo accessible by the github integration tool [reviewable](https://reviewable.io/reviews#-).  See the message at the bottom of the attached screenshot.
![reviewable](https://cloud.githubusercontent.com/assets/12970120/20899488/791a6f7a-badf-11e6-9986-496435fefbda.png)

**Comment by jhux2** [comment]
I tried using the reviewable plugin with pull request #898.  A couple comments:

1. It's really slow.
2. My  comments didn't show up as email;  the requester had to refresh his browser to see them.  I don't know if this would change if/when reviewable is granted access to the repo.

**Comment by jhux2** [comment]
It's faster using chromium on RHEL6.

**Comment by jwillenbring** [comment]
@jhux2 Is this still something you would like to have done? I wanted to check before we look into how to make this happen. Sorry for the delay.

**Comment by jhux2** [comment]
Yes, I'm still interested in this.  Might be worthwhile to see how many other developers are interested before investing much time, however.

**Comment by jmgate** [comment]
I'd sure like it.

**Comment by aprokop** [comment]
To be fair, the Github's review system is getting better. I think what reviewable provides is a per comment resolution requirement, and a better handling of rebased PRs.
