### ISSUE TITLE
Teuchos: does not build shared on windows

### ISSUE THREAD

**Issue by jrobcary** [trilinos/Trilinos#9036]
## Bug Report
@trilinos/teuchos 

### Description
Looks like teuchos is not building the .lib file:

        cd D:\winsame\user\ulixesall-devu17\builds\trilinos\sercommsh
NMAKE : fatal error U1073: don't know how to make 'packages\teuchos\parser\src\teuchosparser.lib'

Only the dll is present

$ pwd
/winsame/cary/ulixesall-devu17/builds/trilinos/sercommsh/packages/teuchos/parser/src
$ ls
cmake_install.cmake  CTestTestfile.cmake  teuchosparser.dll
CMakeFiles           Makefile             teuchosparser.dll.manifest

### Steps to Reproduce
1. SHA1:  065e3d88ee0a2174a0ab80cebd93aa1359259552
1. Configure script: 
[grating.txcorp.com-trilinos-sercommsh-config.sh.txt](https://github.com/trilinos/Trilinos/files/6346990/grating.txcorp.com-trilinos-sercommsh-config.sh.txt)

1. Configure log:  [attach here]

[grating.txcorp.com-trilinos-sercommsh-config.txt](https://github.com/trilinos/Trilinos/files/6346991/grating.txcorp.com-trilinos-sercommsh-config.txt)

1. Build log:  [attach here]

[grating.txcorp.com-trilinos-sercommsh-build.txt](https://github.com/trilinos/Trilinos/files/6346993/grating.txcorp.com-trilinos-sercommsh-build.txt)

1. Input deck: NA
1. Run lo NA

**Comment by csiefer2** [comment]
Visual studio I take it?

**Comment by jrobcary** [comment]
I have moved to static with shared runtime, which works, so closing this as not needed.
