### ISSUE TITLE
Check-in test script reports TCL errors

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#904]
```
sems-python/2.7.9(32):ERROR:102: Tcl command execution failed: if {[module-info mode remove]} {
  set local_compiler_version $env(SEMS_PYTHON_LOCAL_COMPILER_VERSION)
  unsetenv SEMS_PYTHON_LOCAL_COMPILER_VERSION
} else {
  set local_compiler_version [semsModuleSupport::getCurrentVersion gcc]
  setenv SEMS_PYTHON_LOCAL_COMPILER_VERSION $local_compiler_version
}

sems-python/2.7.9(32):ERROR:102: Tcl command execution failed: if {[module-info mode remove]} {
  set local_compiler_version $env(SEMS_PYTHON_LOCAL_COMPILER_VERSION)
  unsetenv SEMS_PYTHON_LOCAL_COMPILER_VERSION
} else {
  set local_compiler_version [semsModuleSupport::getCurrentVersion gcc]
  setenv SEMS_PYTHON_LOCAL_COMPILER_VERSION $local_compiler_version
}
```

The script still runs, apparently, but it reports the above errors every time I run it.

**Comment by bartlettroscoe** [comment]
Mark,

This looks like a problem with the SEMS modules.  What machine, OS, and shell are you using?

What happens when you just do:

$ source ~/Trilinos/cmake/load_ci_sems_dev_env.sh

?

**Comment by mhoemmen** [comment]
@bartlettroscoe wrote:
> What machine, OS, and shell are you using?

Linux, RHEL 6, with the SEMS modules, and bash.

> What happens when you just do: 
> $ source ~/Trilinos/cmake/load_ci_sems_dev_env.sh

I get the following output:
```
$ source ~/Trilinos/cmake/load_ci_sems_dev_env.sh
sems-cmake/3.5.2(3):ERROR:150: Module 'sems-cmake/3.5.2' conflicts with the currently loaded module(s) 'sems-cmake/3.3.2'
sems-cmake/3.5.2(3):ERROR:102: Tcl command execution failed: conflict sems-cmake

sems-boost/1.55.0/base(3):ERROR:150: Module 'sems-boost/1.55.0/base' conflicts with the currently loaded module(s) 'sems-boost/1.59.0/base'
sems-boost/1.55.0/base(3):ERROR:102: Tcl command execution failed: conflict sems-boost
```
However, the tcl errors no longer appear.

**Comment by bartlettroscoe** [comment]
@mhoemmen,

> Linux, RHEL 6, with the SEMS modules, and bash.

This should be exactly what I use as well.  Strange it did not work for you out of the box.  We will fix that.

> I get the following output [... failures ...]

As described at:

* https://github.com/trilinos/Trilinos/wiki/SEMS-Dev-Env

try

```
$ module purge
$ unset TRILINOS_SEMS_DEV_ENV_LOADED
```

then

```
$ source ~/Trilinos/cmake/load_ci_sems_dev_env.sh
```

**Comment by bartlettroscoe** [comment]
We are no longer going to purse extending the checkin-test-sems.sh (or checkin-test.py) script for Trilinos.  See https://github.com/trilinos/Trilinos/issues/482#issuecomment-266124179.

Closing and won't fix.
