### ISSUE TITLE
Amesos2 (and Amesos): MUMPS-5.4.0 support

### ISSUE THREAD

**Issue by keitat** [trilinos/Trilinos#9042]
## Enhancement
@trilinos/amesos2 

@trilinos/amesos  (Maintenance?)

The latest version of MUMPS (5.4.0) released recently has several new features.  I am curious if we want to support this quickly.
http://mumps.enseeiht.fr/index.php?page=dwnld#cl

In addition to that, MUMPS team is making some modification in Spack script to introduce OpenMP.  I do not think this will affect Spack-Trilinos.  I am going to investigate further.
See https://github.com/spack/spack/pull/23143#issuecomment-823870074

**Comment by srajama1** [comment]
@keitat This is not a need for Amesos, but a good idea to add Amesos2.

**Comment by jpthiele** [comment]
There is something fishy.
Building MUMPS 5.4.0.7 using deal.ii's candi script Trilinos 12.8 builds fine and I can use MUMPS in deal.ii's SolverDirect Wrapper for Amesos(1)

Today I got Shylu_DD's FROSch preconditioners to work with deal.ii TrilinosWrapper Epetra matrices and vectors using Xpetra's convert functionality. As it is rather recent I used Trilinos 13.2 here
For the FROSch parameter list I tried setting the internal solver to Amesos2 MUMPS and got the error that 
MUMPS is either not enable or supported. 

Is there an Amesos2 specific parameter to set together with -D TPL_ENABLE_MUMPS=ON to enable MUMPS support?
If yes I could check whether Amesos2 works with MUMPS 5.4.0.7 out of the box

**Comment by jpthiele** [comment]
I currently have a job running on the code using Amesos1, when that is done I can build it with the Trilinos 13.2 version to make sure it's not a trilinos version thing.

**Comment by jpthiele** [comment]
Update. There was a weird git automerge error in out mumps config file.
With that fixed I can report that 5.4.0.7 works out of the box (if configured correctly...)
So the question would be whether any of the new features need different parameters or function calls.
