### ISSUE TITLE
Tpetra::RowMatrixTransposer::createTranspose() might not work correctly in the case of missing columns

### ISSUE THREAD

**Issue by csiefer2** [trilinos/Trilinos#905]
@trilinos/tpetra 
Story: #629 
Blocks: #664 

Even on one MPI rank.  Please investigate.

**Comment by mhoemmen** [comment]
In our discussion today @csiefer2 suggested that the following could be an issue.  Even if a CrsMatrix's communicator has only one process, it's still possible for the domain and column Maps not to be the same.  This can happen if the CrsMatrix was created with only a row Map, the matrix has empty columns (columns with no entries), and the user let fillComplete compute the column Map.  CrsMatrix::makeColMap only adds entries to the column Map for populated columns.

**Comment by csiefer2** [comment]
This is not a serial problem at least.  That was due to map mismatches.  Will need to check more in ||.

**Comment by csiefer2** [comment]
This turns out to work just fine in parallel too.  Closing

**Comment by mhoemmen** [comment]
Neat!
