### ISSUE TITLE
PyTrilinos Install Issues

### ISSUE THREAD

**Issue by bretstanford** [trilinos/Trilinos#9065]
I'm attempting to install PyTrilinos on a linux cluster, and I get the output below from the cmake process.

`Processing enabled package: PyTrilinos (Libs)`
`-- Found PythonInterp: /usr/local/pkgs-modules/Python_3.7.1/bin/python (found suitable version "3.7.1", minimum required is "2.5") `
`-- PYTHON_INCLUDE_PATH is /usr/local/pkgs-modules/Python_3.7.1/include/python3.7m`
`-- Found NumPy: 1.18.1 (found suitable version "1.18.1", minimum required is "1.0") `
`-- Found swig: 4.0.2`
`-- Found Mpi4Py: 3.0.2 (found version "3.0.2") `
`-- Enabled PyTrilinos packages:`
`--     Teuchos;Epetra;TriUtils;Tpetra;Domi;EpetraExt;Isorropia;Pliris;AztecOO;Galeri;Amesos;IFPACK;Komplex;Anasazi;ML;NOX;LOCA`
`-- PyTrilinos installation path: /nobackup5/bstanfor/Trilinos-master/AMESOS_MPI_python_2/lib/python3.7/site-packages/PyTrilinos`

Seems to work fine, but the only problem is that the stated installation path doesn't exist.  `AMESOS_MPI_python_2` is the INSTALL_PREFIX, and when the make process is over there is plenty of stuff in that directory, but `lib` isn't one of them.

Probably something simple that I'm doing wrong here, but not sure what?

**Comment by jhux2** [comment]
@trilinos/pytrilinos @pyt-viper
