### ISSUE TITLE
Tpetra:  4 Tests failing in UVM Off build

### ISSUE THREAD

**Issue by ZUUL42** [trilinos/Trilinos#9068]
## Bug Report
@trilinos/tpetra

### Description

Master Merge PR #9066 failed last night due to 4 failing tests in the UVM Off build. [CDash](https://testing.sandia.gov/cdash/index.php?project=Trilinos&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=63&value1=PR-9066-test&field2=buildstarttime&compare2=84&value2=NOW)
- TpetraCore_CrsMatrix_Bug8794_MPI_4
- TpetraCore_Distributor_CreateFromSendsAndRecvs_MPI_4
- TpetraCore_EpetraRowMatrix_UnitTests_MPI_4
- TpetraCore_Issue601_MPI_4

We can fix the tests to pass the UVM build or I can turn the tests off for that build to get the Master Merge back on track.

**Comment by brian-kelley** [comment]
I'm taking a look at these tests.

Side note, I think we will want to change the names of the UVM=OFF PR tests and files - ``PR-9066-test-Trilinos_pullrequest_cuda_10.1.105_uvm-108`` sounds like it's the one that would have UVM enabled but it's the opposite.

**Comment by brian-kelley** [comment]
@ZUUL42 OK, so all four of those tests use CrsMatrix or CrsGraph, so they should be disabled in UVM=OFF builds until those classes get support for CudaSpace (probably in https://github.com/trilinos/Trilinos/pull/9038).

**Comment by kddevin** [comment]
@brian-kelley   Thank you for looking at these tests so quickly.

**Comment by ZUUL42** [comment]
@brian-kelley I agree. I didn't think about the name confusion until the build got into use. I'll look to change it when I move it to the PR build set.

I'll go ahead and put in a PR to turn these tests off then.

**Comment by ZUUL42** [comment]
Tests turned off in #9075.
Build name changed in code #9080.
Name changed for Jenkins job & in autotester config for Master Merge.
Master Merge PR passed. 
UVM OFF build added to standard PR testing config.
Closing Issue.
