### ISSUE TITLE
`Teuchos_ObjectBuilder_unsetParameterList_UnitTest` fails with gcc 6.2 on Mac OS X

### ISSUE THREAD

**Issue by tjfulle** [trilinos/Trilinos#907]
@trilinos/teuchos 

The test `Teuchos_ObjectBuilder_unsetParameterList_UnitTest` fails on Mac OS X with gcc 6.2.  In `packages/teuchos/parameterlist/test/ObjectBuilder/ObjectBuilder_UnitTests.cpp`, there are some notes about some of the tests failing on gcc 4.8 and gcc 5.3, so the tests are shielded by compile time `#ifdef`s from those compilers.  If I add gcc 6.2 to the list of failing compilers as:

```c
#if !(__GNUC__ == 4 && __GNUC_MINOR__ == 8) && !(__GNUC__ == 5 && __GNUC_MINOR__ == 3) && !(__GNUC__ == 6 && __GNUC_MINOR__ == 2)
```

The test passes.

**Comment by bartlettroscoe** [comment]
@tjfulle, I think this is similar to #831 which I recently fixed.  Please go ahead and fix and test locally and then push with the checkin-test-sems.sh on a RHEL 6 machine.  If you don't have access to such as machine, just push the fix to a branch and I will test and push it for you for now or you can use my machine crf450 to do the [remote pull, test, and push process](https://github.com/trilinos/Trilinos/wiki/Local-development-with-remote-pull%2C-test%2C-and-push) to safely push this.  Once you get your CEE LAN machine, then you can push these yourself.   Just make sure and reference `#907` in your commit message.

**Comment by bartlettroscoe** [comment]
I merged and rebased the fixing commit and pushed it as the commit e312736 to the 'develop' branch.  

This is complete.
