### ISSUE TITLE
Kokkos:  Nalu diffs due to recent commit

### ISSUE THREAD

**Issue by wjhorne** [trilinos/Trilinos#9070]
## Bug Report
@trilinos/kokkos 

### Description
Nalu ( @spdomin ) is currently producing diffs due to recent changes in Trilinos. The output of a bisect is shown below indicating the culprit is commit  [86c737da8545db97f51ae9c77197552e130cbe87] by @ndellingwood . 

### Steps to Reproduce
1. Fetch commit:  [86c737da8545db97f51ae9c77197552e130cbe87] 
2. Build with Configure script: 
[do-configTrilinos_release.TXT](https://github.com/trilinos/Trilinos/files/6393410/do-configTrilinos_release.TXT)
3. Build most current Nalu version and link to Trilinos
4. Run ctest 

### Bisection output

git bisect start
bad: [354848357b8ae65aed2e8e97c15c0e014897bb82] Merge Pull Request #9059 from trilinos/Trilinos/master_merge_20210427_000552
good: [464028f45c1fc1ff10d5c59e622aeb64574e3a96] make "delayed normalization" default for single-reduce MGS
good: [ec0f9a38a6b2c18e1ab96343a47bc99d8d278740] Merge Pull Request #8338 from trilinos/Trilinos/master_merge_20201112_000618
good: [d1f9a8cde3a21e9a1761d1c303b4f668d9dbe45b] Merge Pull Request #8639 from trilinos/Trilinos/master_merge_20210126_000547
good: [f23f4d3b010aeda367bf91bb941b1f1ae182618d] Merge Pull Request #9012 from trilinos/Trilinos/master_merge_20210415_000556
good: [cb6ccbee88da03f9d346b4efddf35f9471fea989] Merge Pull Request #9048 from trilinos/Trilinos/master_merge_20210424_000555
good: [8482d7991ae7f879806fa2ddd4efd52091268b16] Snapshot of kokkos.git from commit 04b8196e0e3bfc4cee4047dbbbb13fc227730fe8
bad: [ad38bd074a74b0abdc5fbcb3f5e6ed93c7eb1ceb] Merge pull request #9054 from trilinos/kokkos-promotion
good: [f8f33cbb111dbf50a0724a0eac970b2bb7e3bea9] Merge pull request #9046 from iyamazaki/peeks-2
bad: [86c737da8545db97f51ae9c77197552e130cbe87] Snapshot of kokkos-kernels.git from commit 3eb6a9298b58f224b876b6e29cda4491cddc53c5
first bad commit: [86c737da8545db97f51ae9c77197552e130cbe87] Snapshot of kokkos-kernels.git from commit 3eb6a9298b58f224b876b6e29cda4491cddc53c5

**Comment by spdomin** [comment]
@crtrott and @alanw0, in my nightly test suite, I noted an edge-based scheme diff: dgNonConformalFluidsEdge

I am not sure how a Kokkos change could drive an edge-based scheme diff since this avoids the current Kokkos Kernel Nalu-Algorithm approach.

Did this change also affect something that STK might use? Or, possibly our linear system assembly has some raw Kokkos usage..

**Comment by crtrott** [comment]
So the kokkos core update is ok but kokkos kernels goes bad? That is weird.

**Comment by spdomin** [comment]
Let us know if you have a theory (like order-of-ops, etc.) and if you believe the diffs can be accepted. They are very small, however, in the past year, we have caught two - shall I say "non-ideal" Trinilos commits by the Nalu regression suite lighting up.

I still would like to determine a working theory why an edge-based scheme would diff.

**Comment by rppawlo** [comment]
@spdomin - is there any particular kokkos backend node type that you are seeing the diffs with. The Kokkos update broke one single test in empire but it is only happening with a Serial backend (very strange). Seems to be an issue with the crs matrix apply.

**Comment by spdomin** [comment]
@rppawlo, the bisect was performed on a Serial usage. The CRS concept seems interesting in that it would explain why the edge-based regression test diffed.

**Comment by ndellingwood** [comment]
There was a new Serial specialization for spmv added to kokkos-kernels with this release, https://github.com/kokkos/kokkos-kernels/pull/893, from the conversation on this issue and reference to serial test issue in EMPIRE with a crs matrix apply I'm guessing that change is leading to the diffs
@kyungjoo-kim @lucbv @brian-kelley could one of you comment on the changes?

**Comment by jhux2** [comment]
> There was a new Serial code path for spmv added to kokkos-kernels with this release, [kokkos/kokkos-kernels#893](https://github.com/kokkos/kokkos-kernels/pull/893), from the conversation on this issue and reference to serial test issue in EMPIRE with a crs matrix apply I'm guessing that change is leading to the diffs
> @kyungjoo-kim @lucbv @brian-kelley could one of you comment on the changes?

@ndellingwood  This was for Sierra, not EMPIRE.

**Comment by kyungjoo-kim** [comment]
I think that passing the spmv unit test implies that the code itself is fine. Tpetra PR tests also pass with serial specialization. @wjhorne What do you mean by "diff" ? Is it error ? or just text-diff with a golden file ?

**Comment by rppawlo** [comment]
In the failing empire test, we have a crs matrix apply that gives completely incorrect values, only on the kokkos Serial node build. Not minor diffs in our case.

**Comment by rppawlo** [comment]
I should mention that this only happens in a single unit test. All the system tests pass. If I dump TPETRA_VERBOSE and TPETRA_DEBUG, the only thing diff'ing in the output are the following flags:

kokkos 3.3:
```
Proc 0: MV::copyAndPermute: copyOnHost=true
Proc 0: MV::copyAndPermute: Copy
Proc 0: MV::copyAndPermute: Permute
Proc 0: MV::copyAndPermute: nonConstStride=false
Proc 0: MV::copyAndPermute: Get permute LIDs on host
Proc 0: MV::copyAndPermute: Permute on host
...
Proc 0: MV::copyAndPermute: copyOnHost=true
Proc 0: MV::copyAndPermute: Copy
Proc 0: MV::copyAndPermute: No permutations. Done!
```

Kokkos 3.4:
```
Proc 0: MV::copyAndPermute: copyOnHost=false
Proc 0: MV::copyAndPermute: Copy
Proc 0: MV::copyAndPermute: Permute
Proc 0: MV::copyAndPermute: nonConstStride=false
Proc 0: MV::copyAndPermute: Get permute LIDs on device
Proc 0: MV::copyAndPermute: Permute on device
...
Proc 0: MV::copyAndPermute: copyOnHost=false
Proc 0: MV::copyAndPermute: Copy
Proc 0: MV::copyAndPermute: No permutations. Done!
```

```

**Comment by spdomin** [comment]
Well, to start, I think @rppawlo and @kyungjoo-kim should share notes. In our case, we test a non-linear norm for our full low-Mach turbulent fluid mechanics. The diffs are O(1.0e-6)...

**Comment by wjhorne** [comment]
@kyungjoo-kim the diffs are text-diffs to a gold file which tracks a non-linear norm as described by @spdomin .

**Comment by kyungjoo-kim** [comment]
@spdomin The change I made in the serial specialization is basically loop unrolling to get better performance on the serial node.  

@rppawlo I am not sure if the empire test failure is related to this. Lately, tpetra also merge a big PR (#8821) for the UVM removal on the multivector. Is there a way for empire to separate these two concerns ? I would think that there could be some precision difference with performance optimization but the wrong result from empire might be related to the tpetra PR.

FYI: @kddevin

**Comment by brian-kelley** [comment]
@rppawlo This is just a guess, but some nontrivial Kokkos::DualView changes got merged in with 3.4 also (but that was in Kokkos core). Could explain the copyAndPermute differences. The version you're looking at was before the huge Tpetra Multivector UVM-dependence removal.

**Comment by rppawlo** [comment]
This error showed up after the kokkos promotion in trilinos but before the Tpetra UVM commit. So it is definitnely the kokkos changes. @spdomin - sorry to hijack this thread if this is different from your issue.

**Comment by spdomin** [comment]
@kyungjoo-kim, yes, these look like order of ops changes. In reality, the largest set of diffs are as follows:

..heatedWaterChannelElem........... FAILED:   s  max diff:  .00000004593290001131400401845895
..heatedWaterChannelEdge........... FAILED:   s  max diff:  .00000004276450000367804094025815

I have not looked at performance.

If you are sure that the code is improved and correct, we can accept the diffs.

@wjhorne, could you comment on if we see a performance improvement?

**Comment by wjhorne** [comment]
@spdomin I noticed a very slight improvement in the range of maybe 5% or so for some of the tests. Could be more substantive if measured in a more controlled setting.

**Comment by kyungjoo-kim** [comment]
@spdomin So the max diff is max norm (the biggest single entry of diff). I assume that the difference is not a single spmv but it is after nonlinear iteration converges within a given threshold, right ? Does the number of nonlinear iterations remain the same or increase or decrease ? Does nalu have an isolated test for spmv on your sparse matrices of interest ?

**Comment by spdomin** [comment]
We do not have unit test-like coverage for a matrix assembly, only these integrated tests that, in most cases, can be highly non-linear. We do have an order of convergence test that (in theory) can be used to sort through order of ops changes and correctness. We can concentrate on making this test more robust. Then, we can say "the local nonlinear behavior changed, however, we still see the same spatial or temporal order of convergence".

What you are seeing now is essentially a Loo error in nonlinear residual.

From what I can tell from spot checks, the iteration count is remaining the same. @Wyatt, please confirm this is true.

If we see that the iterations are the same, and that @kyungjoo-kim and company feel that this is simply due to un-rolling inner loops, we can re-bless the suite.

**Comment by wjhorne** [comment]
@spdomin @kyungjoo-kim I have not noticed significant differences in iteration counts across the failing tests. It appears that the final residuals are the main culprit in the diffs.

**Comment by kyungjoo-kim** [comment]
Thank you. If the different precision does not impact the nonlinear iteration counts, then I would not consider that the difference is a problem as the implementation difference can accumulate different round-off error in the nonlinear solve iterations. 

One more thing to check. I kind of remember that @brian-kelley added MKL spmv. I presume that the above difference happens without enabling the MKL but you might want to try and see the difference on the serial node. 
 
FYI: The serial spmv loop unrolling is for a Sierra application where the sparse matrix is relatively denser than the conventional one. For their problems, we see some speedup more than 2x but the similar performance may not be achieved for other sparse problems.

**Comment by crtrott** [comment]
Can you check #9074? I found a bug in the spmv Serial specialization for dobeta==-1.

**Comment by crtrott** [comment]
Considering that the diff in this case is more epsilon related: I would concur that this is not the bug from 9074 but just the unrolling. The bug I fixed in 9074 definitely just gives completely wrong results. But it only hit cases where you do y = -y + alpha*Ax. I.e. have a beta of exactly -1.

**Comment by wjhorne** [comment]
The diffs still remain and the behavior seems largely the same using the fix in #9074 . I think the unrolling fits the results well

**Comment by spdomin** [comment]
@wjhorne, please proceed with a pull request for re-blessing.

**Comment by wjhorne** [comment]
@spdomin I have now submitted a re-bless to accept the diffs. I believe that this is ready to be closed

**Comment by wjhorne** [comment]
Pull request with re-bless has now been processed. No diffs remain.
