### ISSUE TITLE
Small dense matrix inversion

### ISSUE THREAD

**Issue by bathmatt** [trilinos/Trilinos#908]
@mhoemmen I can see this being somewhere for your block crs matrix inversion.

Is there a class where I can do a small dense matrix inversion?  Example, I can grab a sub-view out of a kokkos 2D view and call it a matrix and compute its inverse? 

Thanks

**Comment by mhoemmen** [comment]
Yes, look in tpetra/core/src/Tpetra_Experimental_BlockView.hpp.  It's a KOKKOS_FUNCTION, but currently sequential inside.

**Comment by bathmatt** [comment]
Since I'm slow, 
You are talking specifically calling

GETRI(const LittleBlockType& A,
       const LittleIntVectorType& ipiv,
       const LittleScalarVectorType& work,
       int& info)

Which calls this to get the LU
GETF2 (const LittleBlockType& A, const LittleVectorType& ipiv, int& info)

Specifically I would have my 
```
Kokkos::View<double**> A("",n,n);
Kokkos::View<double*> work("",n)
Kokkos::View<int*> pivot("",n);
GETF2(A,pivot,info);
GETRI(A,pivot,work,info);

```

**Comment by mhoemmen** [comment]
@bathmatt yes. also, name your Views ;-)

**Comment by bathmatt** [comment]
I did, they are all names 0 clearly :)..  Thanks

**Comment by mhoemmen** [comment]
@bathmatt I'm closing this; please feel free to reopen or open a new issue if you need to.  Thanks!
