### ISSUE TITLE
Framework:  automated regression testing for HIP and SYCL is needed

### ISSUE THREAD

**Issue by kddevin** [trilinos/Trilinos#9093]
## Enhancement
@trilinos/framework @crtrott @trilinos/tpetra @ccober6 @iyamazaki 

As Trilinos is prepared for HIP and SYCL environments, regression testing for HIP and SYCL are needed.  
Tpetra is already being prepared (#8938, #9090, #9086) for HIP and SYCL, but we don't have automated regression testing.  Downstream packages are starting their conversion.

Kokkos has testing enabled for these environments; we can build off their environments to test Trilinos.

**Comment by lucbv** [comment]
This is becoming more pressing as {kokkos,kokkos kernels}/3.4.01 was just merged and mostly enables Tpetra to build with said backends (provided Tpetra PRs are merged).

**Comment by wadeburgess** [comment]
This was migrated to the Trilinos Help Desk, so this issue is now being closed.
