### ISSUE TITLE
tribits and amesos

### ISSUE THREAD

**Issue by jrobcary** [trilinos/Trilinos#9094]
## Enhancement
@trilinos/\<tribits\>

Remove spaces around time.h in gettimeofday.c as disliked by llvm on Windows.

@trilinos/\<amesos\>

Allow configuring with superludist but without parmetis, as superludist can now be built without parmetis

A PR is in the works.

**Comment by bartlettroscoe** [comment]
@trilinos/amesos

**Comment by jrobcary** [comment]
I see this in develop now, so closing.
