### ISSUE TITLE
ATDM/van1-tx2: Deprecate and remove old toolchains

### ISSUE THREAD

**Issue by e10harvey** [trilinos/Trilinos#9100]
CC: @trilinos/framework

Now that the openmpi 4.0.5 toolchain has been in use for several weeks, older toolchains should be marked for deprecation.

Related to https://github.com/trilinos/Trilinos/pull/9001.

**Comment by e10harvey** [comment]
@jmgate Is `ARM-20.0_OPENMPI-4.0.2` still in use?

**Comment by e10harvey** [comment]
@sebrowne is sparc using any toolchains other than `ARM-20.1_OPENMPI-4.0.5`?

**Comment by rppawlo** [comment]
We have a TPL in empire that is hitting a bug in 4.0.2 that has been fixed in 4.0.5. Could we change the default to 4.0.5 even if we have to keep around the old toolchain?

**Comment by e10harvey** [comment]
> Could we change the default to 4.0.5 even if we have to keep around the old toolchain?

Yes.

**Comment by jmgate** [comment]
> @jmgate Is empire still using ARM-20.0_OPENMPI-4.0.2?

If it's still the default when matching `arm-20` in the build name, then yes.

**Comment by rppawlo** [comment]
@e10harvey and @jmgate - Empire is building and passing fine with these changes except for one thing. The environment is loading python 2 instead of python 3 and the empire testing needs python 3. A simple module swap fixed it. The python issue could be unrelated to this commit, but perhaps it would be worth making that change as part of this commit? What do you think?  @bartlettroscoe - was there a reason stria modules load python 2?

**Comment by bartlettroscoe** [comment]
> @bartlettroscoe - was there a reason stria modules load python 2?

@rppawlo, I don't remember.  The git log might say something about this but I doubt it.

**Comment by e10harvey** [comment]
> What do you think?

I don't think so. The 4.0.5 environment isn't loading a python module.

**Comment by e10harvey** [comment]
> I don't think so. The 4.0.5 environment isn't loading a python module.

I stand corrected. The python/2 module is loaded from the `arm-20.1_openmpi-4.0.5` module; since this works for other customers, let's leave the swap in empire.

**Comment by jmgate** [comment]
And there should be nothing to do on the EMPIRE end.  If folks are using our BuildScripts, they should automatically get the Python we support in their environment.

**Comment by sebrowne** [comment]
FWIW, we're pursuing changing the default to python3 (slowly but surely, and really maybe not that slowly)

SPARC is only using the mentioned toolchain

**Comment by rppawlo** [comment]
@e10harvey - I think these changes do inadvertently switch us from python 3 to 2 for empire. In the file:
```
Trilinos/cmake/std/atdm/van1-tx2/environment.sh
```

There is this block of code:
```
if [[ "$ATDM_CONFIG_COMPILER" == "ARM-20.0_OPENMPI-4.0.2" ]]; then
  module load devpack-arm
  module unload yaml-cpp
  # provides numpy module for empire                                                                                                                                                
  module load python/3.6.8-arm
  module load arm/20.0
```
This particular build was forcing python 3 for empire reasons. I'll talk to Jason about doing something on the empire side. Maybe we can hold off on #9101 until we get a fix in place on our side? Hopefully we can tackle this by tomorrow.

**Comment by jmgate** [comment]
Tagging @dc-snl, so he's aware of this.

**Comment by e10harvey** [comment]
> This particular build was forcing python 3 for empire reasons. I'll talk to Jason about doing something on the empire side. Maybe we can hold off on #9101 until we get a fix in place on our side? Hopefully we can tackle this by tomorrow.

Sounds good. Yea, the 4.0.5 build doesn't load python/3 so we would have to change that env which would affect other customers.

**Comment by e10harvey** [comment]
@dc-snl, @jmgate, @sebrowne: Are there any objections to deprecating everything except `ARM-20.1_OPENMPI-4.0.5` for van1-tx2?

**Comment by jmgate** [comment]
We don't yet have Trilinos deploys up on stria for `ARM-20.1_OPENMPI-4.0.5`.  Running into some problem with a Python version, I think.  Probably don't want to rip out the old versions just yet, but if you're just going to issue a deprecation warning, that should be fine.

**Comment by jwillenbring** [comment]
@e10harvey Should this be closed, or did you want to wait until removal?

**Comment by e10harvey** [comment]
@jwillenbring I'd like to wait until removal which is scheduled for 07/12.
