### ISSUE TITLE
Adelus: How to figure out the version

### ISSUE THREAD

**Issue by bdas123** [trilinos/Trilinos#9102]
Hello, I turn Adelus on in Trilinos in order to use Peridigm, but then I get the following error: 

`make[2]: *** [src/CMakeFiles/PeridigmLib.dir/core/Peridigm.cpp.o] Error 2
make[1]: *** [src/CMakeFiles/PeridigmLib.dir/all] Error 2
/home1/07571/barundas/projects/trilinos/lib/libzadelus.so.13.1: undefined reference to `Adelus::nprocs_row'
/home1/07571/barundas/projects/trilinos/lib/libzadelus.so.13.1: undefined reference to `Adelus::nprocs_row'
/home1/07571/barundas/projects/trilinos/lib/libzadelus.so.13.1: undefined reference to `Adelus::nprocs_col'
/home1/07571/barundas/projects/trilinos/lib/libzadelus.so.13.1: undefined reference to `Adelus::nprocs_row'
/home1/07571/barundas/projects/trilinos/lib/libzadelus.so.13.1: undefined reference to `Adelus::nprocs_row'
/home1/07571/barundas/projects/trilinos/lib/libzadelus.so.13.1: undefined reference to `Adelus::nprocs_col'
/home1/07571/barundas/projects/trilinos/lib/libzadelus.so.13.1: undefined reference to `Adelus::me'
/home1/07571/barundas/projects/trilinos/lib/libzadelus.so.13.1: undefined reference to `Adelus::nprocs_col'
/home1/07571/barundas/projects/trilinos/lib/libzadelus.so.13.1: undefined reference to `Adelus::me'
/home1/07571/barundas/projects/trilinos/lib/libzadelus.so.13.1: undefined reference to `Adelus::nprocs_col'
/home1/07571/barundas/projects/trilinos/lib/libzadelus.so.13.1: undefined reference to `Adelus::me'
/home1/07571/barundas/projects/trilinos/lib/libzadelus.so.13.1: undefined reference to `Adelus::me'
make[2]: *** [src/io/mesh_input/quick_grid/unit_test/ut_SmallMeshCylinder_np4] Error 1
make[1]: *** [src/io/mesh_input/quick_grid/unit_test/CMakeFiles/ut_SmallMeshCylinder_np4.dir/all] Error 2
make[2]: *** [src/io/mesh_input/quick_grid/unit_test/ut_Q2CylinderRingHorizon] Error 1
make[1]: *** [src/io/mesh_input/quick_grid/unit_test/CMakeFiles/ut_Q2CylinderRingHorizon.dir/all] Error 2
/home1/07571/barundas/projects/trilinos/lib/libzadelus.so.13.1: undefined reference to `Adelus::nprocs_row'
make[2]: *** [src/io/mesh_input/quick_grid/unit_test/ut_QuickGrid_solidCylinder_np2] Error 1
make[1]: *** [src/io/mesh_input/quick_grid/unit_test/CMakeFiles/ut_QuickGrid_solidCylinder_np2.dir/all] Error 2
/home1/07571/barundas/projects/trilinos/lib/libzadelus.so.13.1: undefined reference to `Adelus::nprocs_col'
make[2]: *** [src/io/pdneigh/unit_test/ut_kdtree_rectangular_search] Error 1
make[1]: *** [src/io/pdneigh/unit_test/CMakeFiles/ut_kdtree_rectangular_search.dir/all] Error 2
/home1/07571/barundas/projects/trilinos/lib/libzadelus.so.13.1: undefined reference to `Adelus::me'
make[2]: *** [src/io/mesh_input/quick_grid/unit_test/ut_QuickGridHorizon] Error 1
make[1]: *** [src/io/mesh_input/quick_grid/unit_test/CMakeFiles/ut_QuickGridHorizon.dir/all] Error 2
/home1/07571/barundas/projects/trilinos/lib/libzadelus.so.13.1: undefined reference to `Adelus::nprocs_row'
/home1/07571/barundas/projects/trilinos/lib/libzadelus.so.13.1: undefined reference to `Adelus::nprocs_row'
/home1/07571/barundas/projects/trilinos/lib/libzadelus.so.13.1: undefined reference to `Adelus::nprocs_col'
/home1/07571/barundas/projects/trilinos/lib/libzadelus.so.13.1: undefined reference to `Adelus::nprocs_col'
/home1/07571/barundas/projects/trilinos/lib/libzadelus.so.13.1: undefined reference to `Adelus::me'
/home1/07571/barundas/projects/trilinos/lib/libzadelus.so.13.1: undefined reference to `Adelus::me'
/home1/07571/barundas/projects/trilinos/lib/libzadelus.so.13.1: undefined reference to `Adelus::nprocs_row'
/home1/07571/barundas/projects/trilinos/lib/libzadelus.so.13.1: undefined reference to `Adelus::nprocs_row'
/home1/07571/barundas/projects/trilinos/lib/libzadelus.so.13.1: undefined reference to `Adelus::nprocs_col'
/home1/07571/barundas/projects/trilinos/lib/libzadelus.so.13.1: undefined reference to `Adelus::nprocs_col'
/home1/07571/barundas/projects/trilinos/lib/libzadelus.so.13.1: undefined reference to `Adelus::me'
/home1/07571/barundas/projects/trilinos/lib/libzadelus.so.13.1: undefined reference to `Adelus::me'
make[2]: *** [src/io/pdneigh/unit_test/ut_point] Error 1
make[1]: *** [src/io/pdneigh/unit_test/CMakeFiles/ut_point.dir/all] Error 2
make[2]: *** [src/io/pdneigh/unit_test/ut_kdtree_spherical_search] Error 1
make[1]: *** [src/io/pdneigh/unit_test/CMakeFiles/ut_kdtree_spherical_search.dir/all] Error 2
make[2]: *** [src/io/mesh_input/quick_grid/unit_test/ut_QuickGridMPI_np3] Error 1
make[1]: *** [src/io/mesh_input/quick_grid/unit_test/CMakeFiles/ut_QuickGridMPI_np3.dir/all] Error 2
make[2]: *** [src/io/mesh_input/quick_grid/unit_test/ut_QuickGrid_solidCylinder_np1] Error 1
make[1]: *** [src/io/mesh_input/quick_grid/unit_test/CMakeFiles/ut_QuickGrid_solidCylinder_np1.dir/all] Error 2
make: *** [all] Error 2`

I believe that I may not have the proper version of Adelus installed.

**Comment by vqd8a** [comment]
@bdas123 I think you use the right Adelus version. Can you try including "Adelus.hpp" in your code?

**Comment by bdas123** [comment]
@vqd8a Sure, I'll give it a shot.

**Comment by bdas123** [comment]
Problem solved.
