### ISSUE TITLE
TriBITS: Problem with Mac using BSD stat vs. Gnu stat

### ISSUE THREAD

**Issue by TBird2001** [trilinos/Trilinos#9105]
### Description
This is specific to Release 13.0.1. I just ran into the exact same bug that was reported in Issue #7881. Looking at the history, the fix went into the master branch after the 13.0.0 release, and it never got ported to the release-13 branch. I can work around it for now, but it would be nice to have it in a Trilinos release.

**Comment by TBird2001** [comment]
I forgot to tag @bartlettroscoe in the report. Doing that here.

**Comment by bartlettroscoe** [comment]
CC: @TBird2001 

@trilinos/framework, is putting out another minor release of Trilinos 13.0.z an option?  I should ask the first before updating the Trilinos 13.0 branch to address this.

**Comment by bartlettroscoe** [comment]
> @trilinos/framework, is putting out another minor release of Trilinos 13.0.z an option? It occurred to me that I should ask this first before updating the Trilinos 13.0 branch to address this.

@trilinos/framework, is putting out Trilinos 13.0.2 after this patch an option?  This is an important internal customer asking for this.

**Comment by jwillenbring** [comment]
> @trilinos/framework, is putting out Trilinos 13.0.2 after this patch an option? This is an important internal customer asking for this.

Yes. There is actually another potential driver for doing this soon.

**Comment by bartlettroscoe** [comment]
> Yes. There is actually another potential driver for doing this soon.

@jwillenbring, okay, I will put in the patch.

On a related note, is there a plan for a Max OSX PR or develop-to-master build for Trilinos?  If that build also did an install as a byproduct of the build (like is done for the ATDM Trilinos builds), then this defect would have been caught as part of regular testing before getting out into a release.

**Comment by jwillenbring** [comment]
> On a related note, is there a plan for a Max OSX PR or develop-to-master build for Trilinos? If that build also did an install as a byproduct of the build (like is done for the ATDM Trilinos builds), then this defect would have been caught as part of regular testing before getting out into a release.

There are some machines now where we could potentially run some tests. Adding a PR build for OSX has not been prioritized highly enough to make it happen. Given the scalability issues with the current system, adding PR builds is carefully considered. I would be interested to learn about any strong internal drivers for such a build.

**Comment by bartlettroscoe** [comment]
> Given the scalability issues with the current system, adding PR builds is carefully considered.

@jwillenbring, any ETA on what that will be fixed so that if just one test fails in one PR build you don't rerun all the PR builds?

> I would be interested to learn about any strong internal drivers for such a build.

A **lot** of Trilinos developers and users do development on their Mac OSX laptops.

**Comment by jwillenbring** [comment]
> @jwillenbring, any ETA on what that will be fixed so that if just one test fails in one PR build you don't rerun all the PR builds?

I don't anticipate that this issue will ever be fixed in the current tool due to the fact that all development activity seems to be focused on the next generation tool. From what I understand, the next generation tool is moving slowly due to other commitments. I am interested in exploring completely different approaches that could help with this issue, but do not currently have staffing to explore those ideas.

**Comment by TBird2001** [comment]
> I will therefore have to try to surgically pull over just the changes to TriBITS to address this issue. I will have to manually test with Linux but I can't test on a Mac OSX machine so someone will have to do that for me to ensure this is fixed.

@bartlettroscoe, I can do the testing on my Mac, if you don't get any other volunteers. Just let me know the best way to get access to the changes.

**Comment by bartlettroscoe** [comment]
@TBird2001, the fixes should be in the commit in the branch in PR #9110.  (That PR must pass PR testing and be approved by at least one Trilinos developer before it can be merged to the Trilinos 13.0 branch.)  Just pull that branch from my fork and give it a try.  (I can provide exact instructions on how to do that if needed.)

**Comment by TBird2001** [comment]
@bartlettroscoe, I just tested it on my Mac, and the installation went smoothly. The fix appears to have worked!
