### ISSUE TITLE
KokkosKernels:  LAPACKE cannot be enabled

### ISSUE THREAD

**Issue by terwin** [trilinos/Trilinos#9121]
## Bug Report
@trilinos/kokkos-kernels

### Description
An optional Kokkos-Kernels TPL, LAPACKE, is not handled by Trilinos.

### Steps to Reproduce
1. SHA1:  944c1269589
1. Configure with KokkosKernels enabled
1. There is no way to enable LAPACKE
    - Standalone KokkosKernels handles LAPACKE
    - In Trilinos it expects all TPLs to be handled by Trilinos, but LAPACKE is not

**Comment by jhux2** [comment]
@trilinos/framework @jwillenbring Not sure who should own this.

**Comment by srajama1** [comment]
@terwin Looks like when this feature was introduced it was not integrated into the Trilinos side of KK correctly. Where do you need to use this feature?

**Comment by terwin** [comment]
I'm trying to use the batched Eigendecomposition in KokkosKernels, which seems to be the only thing that depends on LAPACKE. Related to kokkos/kokkos-kernels#873.

**Comment by srajama1** [comment]
@terwin Just to confirm, do you have to use this with Trilinos and not standalone KK?

**Comment by srajama1** [comment]
@lucbv

**Comment by terwin** [comment]
Yes, I’m also using other Trilinos packages.
