### ISSUE TITLE
Framework:  Add CUDA 10.1.105 UVM OFF PR build to PR Autotester

### ISSUE THREAD

**Issue by ZUUL42** [trilinos/Trilinos#9127]
## Enhancement
@trilinos/Framework

In order the protect the Master Merge PR builds, we are going to add the CUDA 10.1.105 UVM OFF build to the regular PR builds in the autotester. Previously it has only been run by the autotester for the Master Merge PRs.

The build will be tested and ensured to be clean before adding.
The name will have changed to specify "...uvm_off" from the ambiguous "..._uvm" via #9080.

**Comment by jwillenbring** [comment]
This has been completed. Closing.
