### ISSUE TITLE
SEACAS:  Missing #include <limits> leads to compile errors with gcc 11.1.1

### ISSUE THREAD

**Issue by lxmota** [trilinos/Trilinos#9136]
## Bug Report
@trilinos/seacas 

### Description
A missing `#include <limits>` in file https://github.com/trilinos/Trilinos/blob/master/packages/seacas/libraries/ioss/src/main/shell_interface.h
leads to numerous compile errors saying that std::numeric_limits is not on the std namespace when compiling with gcc 11.1.1.

Adding `#include <limits>` to that file fixes the errors.

### Steps to Reproduce
Compile with gcc 11.1.1

**Comment by gsjaardema** [comment]
Thanks.  That was fixed in seacas but I was hoping I could wait to snapshot
into Trilinos until there was one l more pr merged on the seacas side.   I
know have that pr and will hopefully snapshot into trilinos monday
