### ISSUE TITLE
panzer not building under clang

### ISSUE THREAD

**Issue by bathmatt** [trilinos/Trilinos#914]
Getting an error on panzer with clang. 
using  sems-clang/3.9.0

@jmgate @eric-c-cyr @rppawlo 

Probably won't get to this, this year but 

FAILED: packages/panzer/dof-mgr/src/CMakeFiles/panzer-dof-mgr.dir/Panzer_Filtered_UniqueGlobalIndexer.cpp.o 
/projects/sems/install/rhel6-x86_64/sems/compiler/clang/3.9.0/openmpi/1.10.1/bin/mpicxx    -I. -Ipackages/panzer/dof-mgr/src -I/home/mbetten/Trilinos/Trilinos/packages/panzer/dof-mgr/src -Ipackages/panzer/core/src -I/home/mbetten/Trilinos/Trilinos/packages/panzer/core/src -I/home/mbetten/Trilinos/Trilinos/packages/teuchos/comm/src -I/home/mbetten/Trilinos/Trilinos/packages/teuchos/parameterlist/src -Ipackages/teuchos/core/src -I/home/mbetten/Trilinos/Trilinos/packages/teuchos/core/src -Ipackages/kokkos/core/src -I/home/mbetten/Trilinos/Trilinos/packages/kokkos/core/src -I/projects/sems/install/rhel6-x86_64/sems/tpl/boost/1.59.0/clang/3.9.0/base/include -Ipackages/phalanx/src -I/home/mbetten/Trilinos/Trilinos/packages/phalanx/src -Ipackages/intrepid2/refactor/src -I/home/mbetten/Trilinos/Trilinos/packages/intrepid2/refactor/src/Cell -I/home/mbetten/Trilinos/Trilinos/packages/intrepid2/refactor/src/Discretization/Basis -I/home/mbetten/Trilinos/Trilinos/packages/intrepid2/refactor/src/Discretization/FunctionSpaceTools -I/home/mbetten/Trilinos/Trilinos/packages/intrepid2/refactor/src/Discretization/Integration -I/home/mbetten/Trilinos/Trilinos/packages/intrepid2/refactor/src/Orientation -I/home/mbetten/Trilinos/Trilinos/packages/intrepid2/refactor/src/Shared -I/home/mbetten/Trilinos/Trilinos/packages/intrepid2/refactor/src/Shared/../../../core/src/Shared/MiniTensor -I/home/mbetten/Trilinos/Trilinos/packages/intrepid2/refactor/src -Ipackages/shards/src -I/home/mbetten/Trilinos/Trilinos/packages/shards/src -Ipackages/sacado/src -I/home/mbetten/Trilinos/Trilinos/packages/sacado/src -I/home/mbetten/Trilinos/Trilinos/packages/sacado/src/template -I/home/mbetten/Trilinos/Trilinos/packages/sacado/src/parameter -I/home/mbetten/Trilinos/Trilinos/packages/sacado/src/mpl -Ipackages/teuchos/kokkoscomm/src -I/home/mbetten/Trilinos/Trilinos/packages/teuchos/kokkoscomm/src -Ipackages/teuchos/kokkoscompat/src -I/home/mbetten/Trilinos/Trilinos/packages/teuchos/kokkoscompat/src -I/home/mbetten/Trilinos/Trilinos/packages/teuchos/remainder/src -Ipackages/teuchos/remainder/src -I/home/mbetten/Trilinos/Trilinos/packages/teuchos/numerics/src -Ipackages/kokkos/algorithms/src -I/home/mbetten/Trilinos/Trilinos/packages/kokkos/algorithms/src -Ipackages/kokkos/containers/src -I/home/mbetten/Trilinos/Trilinos/packages/kokkos/containers/src -I/home/mbetten/Trilinos/Trilinos/packages/tpetra/core/ext -Ipackages/tpetra/core/ext -I/home/mbetten/Trilinos/Trilinos/packages/tpetra/core/inout -Ipackages/tpetra/core/inout -I/home/mbetten/Trilinos/Trilinos/packages/tpetra/core/src -I/home/mbetten/Trilinos/Trilinos/packages/tpetra/core/src/kokkos_refactor -Ipackages/tpetra/core/src -Ipackages/tpetra/kernels/src -I/home/mbetten/Trilinos/Trilinos/packages/tpetra/kernels/src -I/home/mbetten/Trilinos/Trilinos/packages/tpetra/kernels/src/impl -I/home/mbetten/Trilinos/Trilinos/packages/tpetra/classic/LinAlg -I/home/mbetten/Trilinos/Trilinos/packages/tpetra/classic/NodeAPI -Ipackages/tpetra/classic/NodeAPI -Ipackages/tpetra/classic/src -I/home/mbetten/Trilinos/Trilinos/packages/tpetra/classic/src -Ipackages/epetra/src -I/home/mbetten/Trilinos/Trilinos/packages/epetra/src -std=c++11 -g -MD -MT packages/panzer/dof-mgr/src/CMakeFiles/panzer-dof-mgr.dir/Panzer_Filtered_UniqueGlobalIndexer.cpp.o -MF packages/panzer/dof-mgr/src/CMakeFiles/panzer-dof-mgr.dir/Panzer_Filtered_UniqueGlobalIndexer.cpp.o.d -o packages/panzer/dof-mgr/src/CMakeFiles/panzer-dof-mgr.dir/Panzer_Filtered_UniqueGlobalIndexer.cpp.o -c /home/mbetten/Trilinos/Trilinos/packages/panzer/dof-mgr/src/Panzer_Filtered_UniqueGlobalIndexer.cpp
In file included from /home/mbetten/Trilinos/Trilinos/packages/panzer/dof-mgr/src/Panzer_Filtered_UniqueGlobalIndexer.cpp:45:
In file included from /home/mbetten/Trilinos/Trilinos/packages/panzer/dof-mgr/src/Panzer_Filtered_UniqueGlobalIndexer.hpp:46:
In file included from /home/mbetten/Trilinos/Trilinos/packages/panzer/dof-mgr/src/Panzer_UniqueGlobalIndexer.hpp:51:
/home/mbetten/Trilinos/Trilinos/packages/teuchos/core/src/Teuchos_RCP.hpp:288:5: error: cannot initialize a member subobject of type 'const Tpetra::Map<int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Threads, Kokkos::HostSpace> > *' with an rvalue of type 'const Tpetra::Map<int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > *'
  : ptr_(r_ptr.get()), // will not compile if T is not base class of T2
    ^    ~~~~~~~~~~~
/home/mbetten/Trilinos/Trilinos/packages/panzer/dof-mgr/src/Panzer_Filtered_UniqueGlobalIndexer_impl.hpp:116:9: note: in instantiation of function template specialization 'Teuchos::RCP<const Tpetra::Map<int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Threads, Kokkos::HostSpace> > >::RCP<const Tpetra::Map<int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > >' requested here
      = Tpetra::createNonContigMap<LO,GO>(ownedIndices,getComm());
        ^
1 error generated.

**Comment by bathmatt** [comment]
Actually, think I did get to it..  testing fix with compile only.

**Comment by bathmatt** [comment]
@mhoemmen 
I am not going to fix this before I have to leave,, the issue is that the node and tpetra nodes are different with clang because of serial.  If I take account for that I get a patch that looks like this
```
dir-Trilinos (clang) 25 $ git diff
diff --git a/packages/panzer/dof-mgr/src/Panzer_DOFManager_impl.hpp b/packages/panzer/dof-mgr/src/Panzer_DOFManager_impl.hpp
index 8a0f8c0..b6cf75a 100644
--- a/packages/panzer/dof-mgr/src/Panzer_DOFManager_impl.hpp
+++ b/packages/panzer/dof-mgr/src/Panzer_DOFManager_impl.hpp
@@ -1161,7 +1161,7 @@ buildOverlapMapFromElements(const ElementBlockAccess & access) const
 
   /* 3.  Construct an overlap map from this structure.
    */
-  return Tpetra::createNonContigMap<LO,GO>(overlapVector,getComm());
+  return Tpetra::createNonContigMapWithNode<LO,GO,panzer::TpetraNodeType>(overlapVector,getComm());
 }
 
 template <typename LO,typename GO>
diff --git a/packages/panzer/dof-mgr/src/Panzer_Filtered_UniqueGlobalIndexer_impl.hpp b/packages/panzer/dof-mgr/src/Panzer_Filtered_UniqueGlobalIndexer_impl.hpp
index fc1ad2e..601a5b9 100644
--- a/packages/panzer/dof-mgr/src/Panzer_Filtered_UniqueGlobalIndexer_impl.hpp
+++ b/packages/panzer/dof-mgr/src/Panzer_Filtered_UniqueGlobalIndexer_impl.hpp
@@ -113,9 +113,9 @@ getOwnedAndGhostedNotFilteredIndicator(std::vector<int> & indicator) const
   getOwnedAndGhostedIndices(ghostedIndices);
 
   RCP<const Map> ownedMap 
-      = Tpetra::createNonContigMap<LO,GO>(ownedIndices,getComm());
+      = Tpetra::createNonContigMapWithNode<LO,GO,panzer::TpetraNodeType>(ownedIndices,getComm());
   RCP<const Map> ghostedMap 
-      = Tpetra::createNonContigMap<LO,GO>(ghostedIndices,getComm());
+      = Tpetra::createNonContigMapWithNode<LO,GO,panzer::TpetraNodeType>(ghostedIndices,getComm());
 
   // allocate the owned vector, mark those GIDs as unfiltered
   // (they are by definition)
```

However, when I link I get tons of errors of missing symbols.
/home/mbetten/Trilinos/Trilinos/packages/panzer/dof-mgr/src/Panzer_DOFManager.cpp:(.text._ZNK6panzer10DOFManagerIiiE23buildGlobalUnknowns_GUNERKN6Tpetra11MultiVectorIiiiN6Kokkos6Compat23KokkosDeviceWrapperNodeINS4_7ThreadsENS4_9HostSpaceEEELb0EEERSA_[_ZNK6panzer10DOFManagerIiiE23buildGlobalUnknowns_GUNERKN6Tpetra11MultiVectorIiiiN6Kokkos6Compat23KokkosDeviceWrapperNodeINS4_7ThreadsENS4_9HostSpaceEEELb0EEERSA_]+0xff6): undefined reference to `Tpetra::MultiVector<int, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Threads, Kokkos::HostSpace>, false>::getDualView() const'

It could be a config issue, or somehting else.  Not sure what to do, Maybe Mark knows about this??

**Comment by mhoemmen** [comment]
@bathmatt I'm surprised that you're getting Kokkos::Threads, unless Panzer or Drekar or whatever somehow wants to use Kokkos::Threads by default.  Here's the logic that Tpetra uses to pick its default execution space:
```
if (you have CUDA) {
  then it's CUDA;
} else if (you have OpenMP) {
  then it's OpenMP;
} else {
  if (Kokkos::Serial is enabled) {
    then it's Kokkos::Serial;
  } else if (Kokkos::Threads is enabled) {
    then it's Kokkos::Threads;
  } else {
    sorry, you didn't enable any Kokkos execution spaces;
  }
}
```

**Comment by bathmatt** [comment]
Well, under clang I build with threads since openmp is not available.

**Comment by mhoemmen** [comment]
Tpetra does not enable its support for Kokkos::Threads by default, even if Kokkos::Threads is available.  This saves build time and size.  If you want Tpetra to use Kokkos::Threads, you must set the CMake option `Tpetra_INST_PTHREAD:BOOL=ON`.
