### ISSUE TITLE
Xpetra: issue with MultiVector::getLocalView in uvm_off build

### ISSUE THREAD

**Issue by jewatkins** [trilinos/Trilinos#9146]
## Bug Report
@trilinos/xpetra

### Description
The uvm_off build is broken in PR #9107 because of the use of Xpetra::MultiVector::getLocalView(). See: https://testing.sandia.gov/cdash/viewBuildError.php?buildid=9186703
There's some logic there that I don't think works for cuda space. Is someone planning to work on this soon? I imagine the fix would be similar to what's done in Tpetra.

I'm able to get passed this issue by specifically calling getDeviceLocalView() but it's probably better to fix getLocalView().

### Steps to Reproduce
Build the uvm_off build with https://github.com/jewatkins/Trilinos/tree/jewatkins/muelu-semicoarsen-kokkos

**Comment by jhux2** [comment]
@jewatkins Yes, we are planning to rewrite parts of Xpetra to use Tpetra's new interfaces.  If you can work around this, that might be better for the moment, but leaving this issue open as a reminder that we need to revisit this.  Would that be ok with you?

@trilinos/xpetra

**Comment by jewatkins** [comment]
Yes, I think that's okay for now. Let me see if the work around works for all cases.

**Comment by jewatkins** [comment]
Xpetra multivector has been updated and I don't currently see any issues with what's currently being used so I think we can close this.
