### ISSUE TITLE
Teuchos, Sacado, and Anasazi to split ENABLE_COMPLEX into ENABLE_COMPLEX_FLOAT and ENABLE_COMPLEX_DOUBLE

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#916]
**CC:** @trilinos/framework, @trilinos/teuchos, @trilinos/anasazi, @trilinos/thyra 

As part of #362, I noticed that Teuchos, Sacado, and Anasazi only have `<PackageName>_ENABLE_COMPLEX` and `<PackageName>_ENABLE_FLOAT` options.  Unlike Tpetra, they don't allow you to enable `float` and `complex<double>` bout not `complex<float>`.  Well, no one is using `complex<float>` so even if some customer enables `float` and `complex<double>` they should not have to pay the compile and object code cost for `complex<float>`.

This story is to provide the options  `<PackageName>_ENABLE_COMPLEX_FLOAT` and `<PackageName>_ENABLE_COMPLEX_DOUBLE` for these packages. and hook these into the global enable options like Tpetra now does (as part of #362).

**Comment by bartlettroscoe** [comment]
I realize this is low priority but it was worth mentioning.

**Comment by mhoemmen** [comment]
Isn't the Teuchos case a little bit different, because Teuchos' settings affect Thyra ETI?

**Comment by bartlettroscoe** [comment]
> Isn't the Teuchos case a little bit different, because Teuchos' settings affect Thyra ETI?

Good point.  Thyra would need to be updated as well.  Thyra could/should add its own vars `Thyra_ENABLE_FLOAT`, `Thyra_ENABLE_COMPLEX`, `Thyra_ENABLE_COMPLEX_FLOAT` and `Thyra_ENABLE_COMPLEX_DOUBLE`.

**Comment by mhoemmen** [comment]
cool, as long as we don't forget :)

**Comment by bartlettroscoe** [comment]
> cool, as long as we don't forget :)

That is why this Issue exists :-)

However, this is not super high priority because the only harm is that you will get an extra set of `std::complex<float>` instantiations that you don't want or need when `float` is enabled.  But we don't have any customers that are using `float` and `complex` so no current harm is being done to them.
