### ISSUE TITLE
Trilinos Framework: Move CUDA PR build to weaver

### ISSUE THREAD

**Issue by jwillenbring** [trilinos/Trilinos#9173]
## Enhancement
@trilinos/framework 

Ride and white are to be decommissioned soon. We need to move the PR builds that run on ride to weaver.

**Comment by fryeguy52** [comment]
@jwillenbring I made versions of the cmake file and environment file for weaver and that is running now.  It has passed the configure and is in the build phase building.  It is with gcc/7.2.0, cuda/10.2.2, and openmpi/4.0.5

**Comment by e10harvey** [comment]
> @jwillenbring I made versions of the cmake file and environment file for weaver and that is running now. It has passed the configure and is in the build phase building. It is with gcc/7.2.0, cuda/10.2.2, and openmpi/4.0.5

@fryeguy52 FYI, there is a strange bug with this software stack. See https://github.com/kokkos/kokkos-kernels/issues/998.

**Comment by fryeguy52** [comment]
I am trying an environment with cuda 10.1 and that has the kokkos errors fixed. next I will try a full build with that environment

**Comment by wadeburgess** [comment]
test comment

**Comment by wadeburgess** [comment]
going to close because this has been migrated to Jira
