### ISSUE TITLE
Ifpack2: improve (symmetric) Gauss-Seidel performance on GPUs for matrices with dense rows

### ISSUE THREAD

**Issue by jhux2** [trilinos/Trilinos#9177]
For sparse matrices with a few dense rows, Ifpack2's Gauss-Seidel is very slow on GPUs.  Ifpack2 calls multithreaded Gauss-Seidel (MTGS) in Kokkos-Kernels.

@brian-kelley has developed a new algorithm in Kokkos-Kernels to handle this case.  In Ifpack2, there is a new option, `relaxation: long row threshold`.   The default value is zero, in which case the existing MTGS algorithm is called.  For a positive value, the new algorithm is called, with the threshold indicating which rows should be handled separately.

See PR #9174.

@trilinos/ifpack2

**Comment by brian-kelley** [comment]
#9174 has been merged. @jhux2 posted some performance results there from a Sierra problem of interest:

| Before                                         |        |
|------------------------------------------------|--------|
| Belos: BiCGStabSolMgr total solve time         | 7.626  |
| Belos: PseudoBlockCGSolMgr total solve time    | 6.015  |
| Belos: PseudoBlockGmresSolMgr total solve time | 6.064  |
| After                                          |        |
| Belos: BiCGStabSolMgr total solve time         | 0.9696 |
| Belos: PseudoBlockCGSolMgr total solve time    | 0.9998 |
| Belos: PseudoBlockGmresSolMgr total solve time | 0.971  |

So about 6-7x speedup in overall solve.
