### ISSUE TITLE
Amesos2: can Amesos2 solvers be made to work with ScalarType = long double?

### ISSUE THREAD

**Issue by ikalash** [trilinos/Trilinos#9185]
## Question
@trilinos/amesos2 

I am interested in performing a Trilinos direct linear solve using a 'long double' ScalarType.  I just went through the exercise of implementing several missing specializations in Teuchos to get my Tpetra-based code with ScalarType = long double to compile, only to find that the code throws when I try to run it with the error:

``The requested Amesos2  solver interface does not support the long double scalar type.``

My question is, are there any hurdles to extending Amesos2 to work with the 'long double' type?  I am worried that the fact that Amesos2 relies on TPLs for the solve might cause a problem, e.g., if the TPL does not support a long double.  I am currently trying to use `klu2`, but I am not married to it.  Before I look into adding any implementation for 'long double' into Amesos2, I want to make sure there are no known dead ends preventing this from working.

**Comment by ikalash** [comment]
Tagging @DrBooom who is interested in this also.  Tagging also @srajama1 who likely can answer this question.

**Comment by srajama1** [comment]
I don't know any TPL that works with long double (assuming you just want it to be treated as double as several compilers do).  KLU2, could be made to work, but this is unchartered territory.

**Comment by ikalash** [comment]
Thanks @srajama1 .  We do want the solve to happen using 'long double' arithmetic.  It sounds like going the iterative solver route might be more viable given what you said, though it sounds like all of this is uncharted territory based on conversations @DrBooom and I have had.  Can you please remind me, is KLU2 all coded within Amesos2, or it is relying on a TPL?

**Comment by srajama1** [comment]
KLU2 is all in Trilinos.
