### ISSUE TITLE
Tempus:  Unable to Reconcile Inherited Objects

### ISSUE THREAD

**Issue by ccober6** [trilinos/Trilinos#9188]
## Bug Report
@trilinos/tempus 

### Description

@dridzal reported that the new nonmember constructor `Tempus::createIntegratorBasic(pl_tempus, physics)` gets an error when the old member constructor `IntegratorBasic(pl_tempus, physics)` does not.  E.g.,

```
../../fem-cubed/FEM-Cubed/example/driver/driver.cpp:186:11: error: no matching function for call to 'createIntegratorBasic'
          Tempus::createIntegratorBasic(pl_tempus, physics);
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../packages/tempus/src/Tempus_IntegratorBasic_decl.hpp:213:40: note: candidate template ignored: could not match 'Thyra::ModelEvaluator' against 'panzer::ModelEvaluator'
Teuchos::RCP<IntegratorBasic<Scalar> > createIntegratorBasic(

```

When I have seen this in the past, it seemed related to the compiler unable to reconcile the inherited object when within a Teuchos::RCP.

**Comment by ccober6** [comment]
Hey @bartlettroscoe would you happen to know anything about this issue?

**Comment by bartlettroscoe** [comment]
I suspect the problem and the solution is described in section "5.7.3 Implicit type conversion problems and shortcomings" in:

* https://bartlettroscoe.github.io/publications/TeuchosMemoryManagementSAND.pdf

Otherwise, I would need to see the full error call stack.

**Comment by bartlettroscoe** [comment]
Hello Curt,

What P/T should I charge for Trilinos C++ related requests like this?  This is not really Trilinos Framework that supports by help with build system issues.  Is there a better ASC support P/T for this type of thing?

-Ross


Dr. Roscoe A. Bartlett, PhD
https://bartlettroscoe.github.io/
Sandia National Laboratories

From: Curtis Ober ***@***.***>
Sent: Friday, May 28, 2021 12:50 PM
To: trilinos/Trilinos ***@***.***>
Cc: Bartlett, Roscoe A ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [trilinos/Trilinos] Tempus: Unable to Reconcile Inherited Objects (#9188)
Importance: High


Hey @bartlettroscoe<https://github.com/bartlettroscoe> would you happen to know anything about this issue?

**Comment by ccober6** [comment]
@dridzal can you supply @bartlettroscoe with some additional information on this build?  Thanks, Curt

**Comment by ccober6** [comment]
@dridzal has found a way around this issue by using a dynamic RCP cast to Thyra::ModelEvaluator, so this issue can be closed.
