### ISSUE TITLE
ShyLUBasker Test failures

### ISSUE THREAD

**Issue by krcb** [trilinos/Trilinos#919]
ShyLUBasker has 2 tests that report status "not run" in develop, one of which fails when I enable it's execution. These failures block #649. Details below:

Start 4: ShyLUBasker_basker_amesos2_test_4
Unable to find required file: 
<path-to-build>/packages/shylu/basker/test/basker_amesos2_interface_test.exe
4/8 Test #4: ShyLUBasker_basker_amesos2_test_4 .............***Not Run   0.00 sec
    Start 5: ShyLUBasker_basker_amesos2_coverage_test_14
Unable to find required file: 
<path-to-build>packages/shylu/basker/test/basker_amesos2_coverage_test.exe
5/8 Test #5: ShyLUBasker_basker_amesos2_coverage_test_14 ...***Not Run   0.00 sec

In packages/ShyLU/basker/test/CMakeLists.txt, the executables named by these tests are inconsistently named at compilation time. amesos2_interface_test should be named basket_amesos2_interface_test and amesos2_interface_coverage_test should be named basker_amesos2_coverage_test. After fixing this inconsistency, on a clean checkout of develop, I see:

4/8 Test #4: ShyLUBasker_basker_amesos2_test_4 .............   Passed    0.55 sec
    Start 5: ShyLUBasker_basker_amesos2_coverage_test_14
5/8 Test #5: ShyLUBasker_basker_amesos2_coverage_test_14 ...***Failed  Required regular expression not found.Regex=[OVERALL FINAL RESULT: TEST PASSED .ShyLUBasker_basker_amesos2_coverage_test_14.
]  0.23 sec

In the output from the failed test, I have:

--------------------------------------------------------------------------------

Matrix read
Read Matrix, Time: 0.000764
Kokkos Settings
hwloc aval: 0
numa count: 1
thrd numa:  1
==============Starting Test 1, 1 Threads===========
Setting Threads:1
Done with Symbolic, Time: 0.000594
Done with Factor, Time: 0.000398
btf_c spmv 

TEST_SOLVE: ||x-x||/||x| = -2.540280e-09
TEST PASSED 
Done with Solve, Time: 6.8e-05
||X||: 429 ||Y-AX||: 0
Done with Refactor Factor, Time: 0.000261
Done with Refactor Solve, Time: 2e-05
||X||: 429 ||Y-AX||: 0
============Starting Test 2, 2 Threads================
Setting Threads:2
Done with Symbolic, Time: 0.000441
Done with Factor, Time: 0.000312
btf_c spmv 

TEST_SOLVE: ||x-x||/||x| = -2.540280e-09
TEST PASSED 
Done with Solve, Time: 9.9e-05
||X||: 429 ||Y-AX||: 0
Done with Refactor Factor, Time: 0.000336
Done with Refactor Solve, Time: 2.9e-05
||X||: 429 ||Y-AX||: 0
============Starting Test 4, 4 Threads=============
Setting Threads:4
Done with Symbolic, Time: 0.002628
Done with Factor, Time: 0.000362

--------------------------------------------------------------------------------

TEST_0: Return code = Segmentation fault
TEST_0: Pass criteria = Zero return code [FAILED]
TEST_0: Pass criteria = Not match REGEX {FAILED} [FAILED]
TEST_0: Result = FAILED

================================================================================

**Comment by ndellingwood** [comment]
@krcb Thanks for pointing out the changes needed in the CMakeLists.txt file regarding the inconsistent naming.
The commit in #920 partially addresses this issue. 
The intermittent test failure for case with 4 threads is independent of #649 and is temporarily disabled to prevent blocking of that issue while permanent fix is underway.
