### ISSUE TITLE
xpetra: multivector getLocalView uses deprecated interface

### ISSUE THREAD

**Issue by bathmatt** [trilinos/Trilinos#9206]
## Bug Report
@trilinos/xpetra

@fnrizzi @ppebay

### Description
In the current develop and also tpetraCrsRefactor branches xpetra getLocalView does the old way of just getting a view without read/write traits assigned.  We should make the new interface take the traits and propagate that code through the stack..  
Because of this xpetra will have some dummy classes which map to the tpetra ones with read, write, ...  The names will be the same

This can be built and tested off develop with a few patches from @csiefer2 to fix up thyra.

We will probably only merge this into the crs refactor branch unless it gets merged first which I doubt.

Thoughts?

**Comment by csiefer2** [comment]
I would refer you to the Thyra package owner, @cgcgcg 🚌

**Comment by bathmatt** [comment]
Poor guy

**Comment by cgcgcg** [comment]
I'm the lucky owner of Teko, not Thyra :-P

**Comment by csiefer2** [comment]
Mea culpa.  Who won the Thyra lottery?

**Comment by jhux2** [comment]
@bathmatt @csiefer2 What/where are the Thyra patches that you mentioned?

**Comment by bathmatt** [comment]
commit c54c669fe41cd64678d517f7e7ff8c8b740fe8a3 (*fork/xpetra-mv*)

Author: Christopher Siefert ***@***.***>

Date:   Tue May 11 10:47:39 2021 -0600


    Thyra: Removing more Tpetra deprecated code


commit da500411a247090f15d2e04c5d8b22e239d60c85

Author: Christopher Siefert ***@***.***>

Date:   Tue May 11 10:19:50 2021 -0600


    Thyra: Purging use of deprecated Tpetra functions


commit dbbb3b1510ad320f0a91b7c8181c42f349ab55e6

Author: Christopher Siefert ***@***.***>

Date:   Tue May 11 10:09:50 2021 -0600


    Thyra: Purging use of deprecated Tpetra functions

**Comment by bathmatt** [comment]
when i looked at them I saw that syncs were being removed and was concerned
about accuracy.

**Comment by bathmatt** [comment]
@jhux2 you can look at the branch on the fork if you need to see where I'm going. I have multivector working, it is based off the tpetra refactor branch so the whole thing doesn't compile unless you have deprecated code on as there are CRS pushes in that branch

**Comment by csiefer2** [comment]
Tpetra MultiVector should now handle all of the sync-ing itself, via the WrappedDualView.  That's why all those syncs are gone now.

**Comment by bathmatt** [comment]
sounds good to me. ...

**Comment by jhux2** [comment]
I think this can be closed ....
