### ISSUE TITLE
How do I specify the python executable?

### ISSUE THREAD

**Issue by VictorEijkhout** [trilinos/Trilinos#9216]
Cmake is finding the wrong python, so I'd like to specify python explicitly.

(Is there a documentation of all cmake options?)

**Comment by ccober6** [comment]
Tagging @trilinos/framework.

A list of cmake options can be found at https://docs.trilinos.org/files/TrilinosBuildReference.html.

**Comment by VictorEijkhout** [comment]
A list of cmake options

None for pytrilinos.

Victor.

**Comment by mayrmt** [comment]
@VictorEijkhout I'm not sure, if this is what your looking for: `-D PYTHON_EXECUTABLE:PATH="/usr/bin/python3" \`. Maybe it helps.
