### ISSUE TITLE
Tpetra: New thread-parallel sparse matrix-matrix multiply test fails ("experimental")

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#922]
@trilinos/tpetra 
http://testing.sandia.gov/cdash/viewTest.php?onlyfailed&buildid=2651259

**Comment by mndevec** [comment]
@csiefer2, 
Is this a new error after map fixes? I just simply run couple SPGEMM versions and some TPLS and all seem to return the same output that does not match the expected output. I can have a deeper look if this is an error that still keeps happening after fixing the maps.

**Comment by csiefer2** [comment]
@mndevec  Trilinos doesn't have the map fixes checked in yet.

Don't worry about this.

**Comment by mndevec** [comment]
Is this still an issue? I have not received test failures for a while.
