### ISSUE TITLE
problem for Installation Testing

### ISSUE THREAD

**Issue by Ethan-GitHub** [trilinos/Trilinos#9234]
## cmake error for testing
I have buid and installed the Trilinos, the error occurred when i install the testing  by cmake:
```shell
$ cmake \
  -D TPL_ENABLE_MPI=ON \
  -D MPI_BASE_DIR=/usr/lib64/mpich/bin/ \
  -D Trilinos_ENABLE_ALL_PACKAGES=ON \
  -D Trilinos_ENABLE_TESTS=ON \
  -D Trilinos_ENABLE_INSTALLATION_TESTING=ON \
  -D TPL_ENABLE_Netcdf=OFF \
  -D TPL_ENABLE_X11=OFF \
  -D FINITE_VALUE_HAVE_GLOBAL_ISNAN=OFF \
  -D FINITE_VALUE_HAVE_GLOBAL_ISINF=OFF \
  -D Trilinos_INSTALLATION_DIR=/home/maolin.wang/software/trilinnos/tril-install \
  -D CMAKE_INSTALL_PREFIX=/home/maolin.wang/software/trilinnos/BUID_TESTS \
  /home/maolin.wang/software/trilinnos/Trilinos
```
error information:
```shell
Configuring individual enabled Trilinos packages ...

Processing enabled package: TrilinosFrameworkTests (Libs, Tests, Examples)
CMake Error at cmake/tribits/core/package_arch/TribitsAddAdvancedTest.cmake:1224 (MESSAGE):
  Must have EXEC, CMND, or COPY_FILES_TO_TEST_DIR for TEST_0
Call Stack (most recent call first):
  commonTools/framework/CMakeLists.txt:4 (TRIBITS_ADD_ADVANCED_TEST)


-- Configuring incomplete, errors occurred!
See also "/home/maolin.wang/software/trilinnos/BUID_TESTS/CMakeFiles/CMakeOutput.log".
```
There was no error information in the CMakeOutput.log.
who can help? thanks

**Comment by jhux2** [comment]
@bartlettroscoe might have a suggestion?

**Comment by bartlettroscoe** [comment]
@Ethan-GitHub and @jhux2, I don't think installation testing currently works for Trilinos.   It has not been run for may years (perhaps as many as 8 years or so).  I think that @william76 has been working on this (see #7383 and #5027).

**Comment by dridzal** [comment]
Reviving this functionality is important for integration with application codes.  A recent effort with ROL @trilinos/rol identified missing headers as the only major integration issue.  Missing headers would have been identified through installation testing.
