### ISSUE TITLE
Which Amesos2 tools are available for use in PyTrilinos?

### ISSUE THREAD

**Issue by bretstanford** [trilinos/Trilinos#9244]
## Question
@trilinos/amesos
@trilinos/amesos2
@trilinos/pytrilinos

I'm trying to understand which Amesos2 tools can be used via PyTrilinos.  My understanding is that PyTrilinos (which is no longer being actively developed?) mostly was written to work with Amesos, and Amesos also appears that its no longer actively maintained.

Amesos2 is clearly being actively developed and maintained, and the main external solver it interfaces with is SuperLU_dist, though again its unclear which version of SuperLU_dist should be used (#7708 indicates 5.4).

Will PyTrilinos work with Amesos2 and SuperLU_dist?

**Comment by jhux2** [comment]
@trilinos/amesos2 @trilinos/amesos @trilinos/pytrilinos

**Comment by pyt-viper** [comment]
PyTrilinos is “lightly maintained.”  Amesos2 is not yet supported because Tpetra is not yet supported.  It has been a challenge to develop a clean interface where the scalar type is a template.

**Comment by mhoemmen** [comment]
> It has been a challenge to develop a clean interface where the scalar type is a template.

I always figured that would work like NumPy arrays, but you would need a way to query the set of enabled Scalar types.  Devs talked about that but I haven't been involved or following for over a year.
