### ISSUE TITLE
Tpetra shadow warning

### ISSUE THREAD

**Issue by kddevin** [trilinos/Trilinos#925]
Trilinos/packages/tpetra/core/src/Tpetra_Details_FixedHashTable_def.hpp:1043:82: warning: declaration of 'maxVal' shadows a member of 'this' [-Wshadow]

It appears maxVal is also a method in this class.  

gcc 4.7.2 compiler on linux

Priority for me is low, but this might trigger warnings=errors problems for others.

**Comment by mhoemmen** [comment]
@trilinos/tpetra

**Comment by mhoemmen** [comment]
@kddevin is this with ETI on or off?  Just curious; thanks!

**Comment by kddevin** [comment]
My build has ETI=OFF.

**Comment by mhoemmen** [comment]
@kddevin I just pushed a fix.  Please feel free to reopen if it should continue to show up.  Thanks for reporting!
