### ISSUE TITLE
Tpetra:  non-blocking Import/Export

### ISSUE THREAD

**Issue by tasmith4** [trilinos/Trilinos#9251]
## Enhancement
@trilinos/tpetra

Provide an API for non-blocking imports and exports on DistObjects.  The new API will have three general types of functions for both imports and exports.  Using import as an example:
* beginImport -- packs the data and initiates the asynchronous send
* endImport -- waits for the asynchronous request to complete and unpacks the data
* isImportReady -- check if the data is ready to unpack

@cgcgcg @vbrunini

**Comment by tasmith4** [comment]
Yes, that was done a while back.  Looks like I tried to autoclose it in #10300, not sure why that didn't work ...

**Comment by GrahamBenHarper** [comment]
@tasmith4 I noticed autocloses no longer work in Trilinos. I'm not sure what changed, but it's been this way for somewhere between months and a year

**Comment by sebrowne** [comment]
I show that this has the DO_NOT_AUTOCLOSE label on it.  Can you link any others that should have been closed but were not?

**Comment by tasmith4** [comment]
@sebrowne I think we thought that DO_NOT_AUTOCLOSE would keep the bot from closing it, but would still allow it to be closed with keywords in the PR.  Is that not true -- i.e. does DO_NOT_AUTOCLOSE also block closing on merge?

If so, is there a way to keep the "one-year bot" from closing it, without blocking closing on merge with keywords?
