### ISSUE TITLE
Tpetra/Kokkos: build error with OpenMP on Blake

### ISSUE THREAD

**Issue by ikalash** [trilinos/Trilinos#9256]
## Bug Report
@trilinos/tpetra @trilinos/kokkos 

We are getting the following error in our Blake OpenMP build of Trilinos for Albany: 

```
/.../repos/Trilinos/packages/tpetra/core/src/Tpetra_Details_WrappedDualView.hpp(124): error: namespace "Kokkos" has no member "Serial"
      Kokkos::SpaceAccessibility<Kokkos::Serial, typename DeviceViewType::memory_space>::accessible;
                                         ^

In file included from /.../repos/Trilinos/packages/tpetra/core/src/Tpetra_CrsGraph_decl.hpp(53),
                 from /.../build/TriBuildOpenMP/packages/tpetra/core/src/Tpetra_CrsGraph.hpp(1),
                 from /.../repos/Trilinos/packages/tpetra/core/src/Tpetra_CrsMatrix_decl.hpp(51),
                 from /.../repos/Trilinos/packages/tpetra/core/src/Tpetra_CrsMatrix_convert.cpp(48):
```
https://sems-cdash-son.sandia.gov/cdash/viewBuildError.php?buildid=17547

Curiously it does not happen in the other OpenMP build we have in our nightlies.  Perhaps there is some issue with the configuration?  The configure script can be found here: https://github.com/SNLComputation/Albany/blob/master/doc/dashboards/blake.sandia.gov/do-cmake-trilinos-intel-openmp .

**Comment by cgcgcg** [comment]
This looks like #9336. Is this fixed?

**Comment by ikalash** [comment]
Yes - sorry for not closing earlier.

**Comment by cgcgcg** [comment]
No worries :-)
