### ISSUE TITLE
proposal for "Linear" solver in NOX

### ISSUE THREAD

**Issue by ibaned** [trilinos/Trilinos#926]
What I mean by this is to implement a "dummy" NOX "nonlinear" solver which is simply a light wrapper around a given linear solver, and executes only one nonlinear iteration.

The rationale for this comes from Albany, which uses NOX through Piro and the LOCA AdaptiveStepper, meaning users must select a nonlinear solver type even if their problem is linear. Instead of trying to "trick" a real non-linear solver into always executing exactly one iteration by adjusting status tests, it may be better to have a special class in NOX for this purpose. The end result would be one could specify "Linear" or perhaps "None" as the "Nonlinear Solver" parameter and get this object in return. Thus the nonlinear portion of the hierarchy is cleanly disabled.

I've assigned this to myself, meaning if it makes sense then I'll try to develop it myself and submit a pull request to Trilinos.

This issue is here simply to request feedback from NOX developers (@rppawlo I believe ?) about whether this is a good idea and advice for implementing it.

**Comment by rppawlo** [comment]
@ibaned This is a good idea. Several teams have asked about this in the past. I have always told them what you mentioned - use a status test object that claims convergence after one nonlinear iteration. Makes sense to just add a simple solver object. Please go ahead and submit a pull request. Thanks!

**Comment by mhoemmen** [comment]
@trilinos/nox

**Comment by ibaned** [comment]
I've submitted my implementation as pull request #938.

**Comment by rppawlo** [comment]
Closing
