### ISSUE TITLE
STK:  Nalu errors due to recent changes in STK

### ISSUE THREAD

**Issue by wjhorne** [trilinos/Trilinos#9267]
## Bug Report
@trilinos/stk

### Description
Nalu (@spdomin) now errors during regression runs, see the dgNonConformalThreeBlade test, with the following error. Based on a bisection the culprit is [98e69dce5243027fc4354039d8a3674e33134743] STK: Snapshot 06-08-21 17:10 . 

### Error
OSS: Using decomposition method 'RCB' for 49,013 elements on 4 mpi ranks.
terminate called after throwing an instance of 'std::logic_error'
  what():  Requirement( internal_destroy_entity_with_notification(rmEntity, true) ) FAILED
Error occurred at: stk_mesh/stk_mesh/base/BulkData.cpp:3652
Error: P1: ghost-id=2, FAILED to destroy remove-recv-ghost entity: (NODE_RANK,28963)

### Bisection 
git bisect start
bad: [17a0d3c6b2ce1f79c0acb49f076c54f734e20187] Merge Pull Request #9240 from kyungjoo-kim/Trilinos/tpetra-bcrs
good: [d2ab6093d3509bb8de0eb29b13ec1681f348cc50] Merge Pull Request #9239 from gsjaardema/Trilinos/SEACAS-fix-fortran-exodus-tests
good: [38a7a40fee045a7f8e6c3161396fe650af95d472] Fix ups after rebasing
good: [ca8b9e0ea7e209444a6cb1d86a55fb15fa65ba74] Merge Pull Request #9224 from brian-kelley/Trilinos/FixMiniFEVectors
good: [97aaf2b6bbeec6c3aaef5d44fcd14985eb9f9cfc] Merge Pull Request #9236 from trilinos/Trilinos/csiefer-fc658a5
bad: [f82a23e2455c3f370feed1936a78d6f1dbe1b389] Merge Pull Request #9247 from trilinos/Trilinos/stk-snapshot
bad: [98e69dce5243027fc4354039d8a3674e33134743] STK: Snapshot 06-08-21 17:10
first bad commit: [98e69dce5243027fc4354039d8a3674e33134743] STK: Snapshot 06-08-21 17:10
### Steps to Reproduce
1. Build Trilinos using [98e69dce5243027fc4354039d8a3674e33134743] STK: Snapshot 06-08-21 17:10 or later
2. Build Nalu using most recent release
3. Run Nalu using ctest -R "ThreeBlade"

**Comment by alanw0** [comment]
I'm on it, I'll get a fix or revert in as soon as I can.

**Comment by spdomin** [comment]
I was able to verify that if I remove all of the dynamic ghosting (which requires dynamic ghosting calls), the latest STK code works. This suggests either a new STK issue, or a flawed Nalu interface to the dynamic ghosting changes.

I also noticed that the elemsToGhost_ is the full set of elements provided from the coarse search. However, the fine search might reduce this number [substantially]. Nevertheless, the linear system will be provided the communication for the search, not the final best set of ghosted elements for the linear system stencil. Therefore, I am evaluating supporting two ghosting objects: the first for the search and the second for the linear system.

**Comment by spdomin** [comment]
Just a FYI that the Mac platform is failing with the same error.

**Comment by alanw0** [comment]
ok, I found the problem, and a fix should be in this afternoon with any luck.
The stk ghosting code internally was doing a sort when it needed to do a sort-and-unique. Our dynamic ghosting manipulations in nalu were adding some duplicate entries to the remove-from-ghosting list, and stk-mesh was throwing when the ghosting code tried to delete an entity more than once. The lack of 'unique-ing' the input list was an error in the recent stk change.
This issue of duplicate entries in the remove-from-ghosting list is also not an issue in your simpler destroy-all-and-re-ghost approach...

**Comment by spdomin** [comment]
Interesting. So we were asking for a element to be deleted that had already been... This reminds me of the framework days where I would check on "have you been deleted"... Thanks for finding this.

**Comment by alanw0** [comment]
Yes...
I've been trying to get the fix through the sierra build checks and it keeps aborting or failing due to apparent system flakiness. Also, I don't think any other stk guys are here this afternoon to approve a trilinos push... so it may be Monday before this gets in. Sorry about that!

**Comment by spdomin** [comment]
Oh, I missed the "internally" aspect. I though this may have been Nalu code. I can approve it if you send it my way:)

**Comment by alanw0** [comment]
Update: I ended up getting the fix into a pull-request Friday afternoon, but the PR testing doesn't seem to be progressing (or even starting), possibly due to the widespread computer/filesystem issues...
We'll get it in as soon as we can.

**Comment by spdomin** [comment]
Alan, yes, all weekend key locations have been unavailable.. Let me know when this is pushed and I can execute a nightly test.

**Comment by spdomin** [comment]
We look clean now...

100% tests passed, 0 tests failed out of 74

Total Test time (real) = 1382.09 sec
NaluCFD/Nalu SHA1: 35b4b429ccd4a442d2dbb79274e15b6e46ab2fbc
Trilinos/develop SHA1: 97aab17fb39d7e8d54b6f978000d70ba152cf50a

Feel free to close.

**Comment by tasmith4** [comment]
Glad it's resolved.  Thanks for your patience, @spdomin.
