### ISSUE TITLE
Trilinos Framework: Improve ATS2 build

### ISSUE THREAD

**Issue by jwillenbring** [trilinos/Trilinos#9270]
## Enhancement
@trilinos/framework 

We received the following request with regards to the ATDM ATS2 xl build:

Full ats2 with the xl compiler (at least on power 9) would be useful. Right now the Trilinos tests are not built or tested.

As discussed with @fryeguy52 the first step would be to fix the current build errors in the build, then the next step would be to evaluate what else needs to be turned on (likely it sounds like tests primarily).

**Comment by jwillenbring** [comment]
Per @bartlettroscoe this request is obsolete. Closing.

**Comment by bartlettroscoe** [comment]
@jwillenbring, does this mean we can get rid of all of the broken ats2 xl builds polluting the dashboard for the last 6 months?

**Comment by jwillenbring** [comment]
@bartlettroscoe Possibly/probably. We are going to do some additional checking.
