### ISSUE TITLE
Framework:  PR autotester not running

### ISSUE THREAD

**Issue by tasmith4** [trilinos/Trilinos#9283]
## Bug Report
@trilinos/framework 

### Description
The PR autotester seems not to have run since sometime on Thursday (June 10).  See for example #9274, #9276, #9278, #9279.  @trilinos/framework, do any of you know what might be going on?

FYI @brian-kelley @jhux2 @alanw0

**Comment by tasmith4** [comment]
@trilinos/framework @prwolfe @william76 I notice some PR's are starting to merge, has this issue been resolved, or is anything still outstanding?

**Comment by jhux2** [comment]
@tasmith4 The AT is working again.

**Comment by tasmith4** [comment]
@jhux2 thanks for pointing me to this other issue.

**Comment by prwolfe** [comment]
Closing as duplicate of #9293
