### ISSUE TITLE
Thyra:  Allow absence of IN_ARG_alpha

### ISSUE THREAD

**Issue by jmgate** [trilinos/Trilinos#929]
Allow the absence of `IN_ARG_alpha` in `assertInArgsOutArgsSetup()`.  @trilinos/thyra

**Comment by jmgate** [comment]
I was troubleshooting some failing tests in Drekar when built with `Trilinos_ENABLE_DEBUG=ON`, and ran into the following:  In `drekar/test/transient/BlockedLinearSystemModel.cpp` in the `setupInOutArgs_()` routine, we have

```c++
if (isImplicit_) // We can comment out this if() and solve the problem really quickly.
  inArgs.setSupports(ModelEvaluatorBase::IN_ARG_alpha);
```

In talking with @egphill, it sounds like that’s as it should be — implicit models need an alpha, explicit ones don’t.  However, `initializeDefaultBase()` in `Thyra_ModelEvaluatorDefaultBase.hpp` has

```c++
#ifdef TEUCHOS_DEBUG
  assertInArgsOutArgsSetup(this->description(), inArgs, outArgsImpl);
```

and in that routine in `Thyra_ModelEvaluatorHelpers.hpp`, we have

```c++
TEUCHOS_TEST_FOR_EXCEPTION(
  (
    ( outArgs.supports(MEB::OUT_ARG_W) || (outArgs.supports(MEB::OUT_ARG_W_op) )
    &&
    inArgs.supports(MEB::IN_ARG_x_dot)
    &&
    !( inArgs.supports(MEB::IN_ARG_alpha) && inArgs.supports(MEB::IN_ARG_beta) )
    ),
  std::logic_error,
  “Error: The underlying model “ << modelEvalDescription << “ supports W and/or W_op\n”
  “and x_dot but it does not support alpha and beta as InArgs!”
  );
```

If the setup in Drekar is indeed correct, does that mean the routine in Thyra needs to be changed to allow for the absence of alpha (that is, "you definitely need beta, and you might have alpha with it", instead of “you definitely need both”)?  Alternatively, when the in and out args are set up in Drekar, we can say alpha is supported and then just never supply one.  Shouldn’t change the functionality at all (unless maybe someone goes and gives one an alpha?), and it’ll get Thyra to stop complaining.

I'm going with the latter change for now, because it's quick and easy, but if Thyra does need to change to allow for this use case, I'll just revert the change in Drekar.

**Comment by bartlettroscoe** [comment]
From looking at:

* https://trilinos.org/docs/dev/packages/thyra/doc/html/classThyra_1_1ModelEvaluator.html#Thyra_ME_implicit_dae_sec

this defines the matrix `W` for an implicit ODE or DAE model as:

```
W=alpha*D(f)/D(x_dot)+beta*D(f)/D(x)
```

Therefore, if the model defines `x_dot`, they by definition is a implicit ODE or DAE, and therefore it must also define `alpha` (better called `coeff_x_dot`?).  What does the absence of `alpha` mean for implicit transient model?  Does it mean that the mass matrix `D(f)/D(x_dot)` is zero?  You can't have an implicit model if `D(f)/D(x_dot)` is zero can you?  Would that not make it an explicit model?  Should the underlying ME object just not define the InArg `x_dot` then?

@rppawlo or @eric-c-cyr, can one of you please help clear this up?

**Comment by jmgate** [comment]
Ah, perhaps that's it then&mdash;if the model's implicit, we support `IN_ARG_x_dot` and `IN_ARG_alpha`, but if the model's explicit, we don't.  If that's right, then that's just a quick change to Drekar and we can close this issue.

**Comment by bartlettroscoe** [comment]
> Ah, perhaps that's it then—if the model's implicit, we support `IN_ARG_x_dot` and `IN_ARG_alpha`, but if the model's explicit, we don't. If that's right, then that's just a quick change to Drekar and we can close this issue.

Thanks @jmgate, glad this was a simple mix-up.  I guess the ME should put in longer explanation for these assertions?  Perhaps we could expand on the exception message to explain the relationship between `x_dot`, `alpha` and `W` better?  Like, should we say:

```
“Error: The underlying model “ << modelEvalDescription << “ supports W and/or W_op\n”
  “and x_dot but it does not support alpha and beta as InArgs!  If the model supports W and x_dot, then”
  " it can be interpreted as an implicit ODE/DAE and therefore D(f)/D(x_dot) must be non-zero and"
  " therefore alpha must be supported.  If, however, the model can be interpreted as an explicit"
  " ODE, then x_dot should not be supported at all."  
```

?  Would that help?

**Comment by jmgate** [comment]
That looks great to me.  @rppawlo, @eric-c-cyr, does this sound like a good path forward?

**Comment by bartlettroscoe** [comment]
Has this been resolved yet?  Can the ME implementation in question just not provide support for `x_dot` for a steady-state model?

**Comment by rppawlo** [comment]
While the issue has been resolved by fixing the user's model evaluator, I'd like to leave this open and assign to me to follow up on the suggestion of changing the error message as noted above. I can make this change today.

**Comment by rppawlo** [comment]
Pushed fix for the error message mentioned above. Closing.
