### ISSUE TITLE
Trilinos Autotester proxy issues

### ISSUE THREAD

**Issue by prwolfe** [trilinos/Trilinos#9293]
## Bug Report
@trilinos/framework 

### Description
Beginning on Friday June 11th the proxy and certificate sets used in the autotester has changed. Currently this has kept all pull requests from running.

**Comment by prwolfe** [comment]
See #9295

**Comment by prwolfe** [comment]
Just a bit of info on the work done on this ticket

Monday 6/14/2021: Found that the AutoTester jobs were failing in 2 different ways.
* changed all jobs to use a login shell so they got the proxy variables
* Changed to use the new tokens Henry had set up that were in instance 0
* Created PR #9286 to correct proxy settings in the PullRequestDriver*sh scripts
  * Note that this fails as the fetch is before the restart mechanism and is later force pushed

Tuesday 6/15/2021: Jobs still do not clone due to a proxy variable in the Jenkins configuration
* Filed a ticket with CEE requesting the Jenkins configuration be corrected

Wednesday 6/16/2021: Jenkins was corrected about 10:00 am and jobs began to run.
* No jobs actually report to dash
  * Began tracing log files looking for the problem - Noted that the https_proxy seems to be removed part-way through. No idea how or if it is relevant
  * Met with Aaron, Victoria, Will and Jim after our stand-up to team debug. Victoria notes a missing term (.sandia.gov) in the no_proxy variable set 
  * Created a PR #9295 to add the missing term back in.
  * Ran a python job by hand (see crash report at https://testing.sandia.gov/cdash/index.php?project=Trilinos&parentid=9349541)
  * Force pushed with concurrence from @william76 to get items moving

**Comment by prwolfe** [comment]
Thursday 6/17/2021: Noted that no intel jobs are getting past configure.
* Confirmed that I get the same failure at a command line
* Attempted to do `icc --version` with the same failures
* Filed a ticket with CEE

**Comment by prwolfe** [comment]
@jwillenbring , @william76 

Realized that the CTH intel builds are working
* CTH uses the module compilers/intel/intel_2019_ClusterEdition
  * sets "prepend-path	 LM_LICENSE_FILE 28518@cee-infra009.sandia.gov"
* Trilinos uses the module sems-intel/17.0.1
  * sets "setenv INTEL_LICENSE_FILE /projects/sems/install/rhel7-x86_64/sems/compiler/intel/17.0.1/base/Licenses/intel-Linux-SON.lic "

I was able to use the sems module by doing
* unset INTEL_LICENSE_FILE
* export LM_LICENSE_FILE=28518@cee-infra009.sandia.gov

and then successfully did 'icc --version' and compiled a test source. Options
1) Ask sems to change their module to use the same license information as the default compiler module or update the license file in use
2) Make the environment changes in the PR job via the pullrequest.ini file
3) Other?

**Comment by jwillenbring** [comment]
> @jwillenbring , @william76
> 
> Realized that the CTH intel builds are working
> 
>     * CTH uses the module compilers/intel/intel_2019_ClusterEdition
>       
>       * sets "prepend-path	 LM_LICENSE_FILE [28518@cee-infra009.sandia.gov](mailto:28518@cee-infra009.sandia.gov)"
> 
>     * Trilinos uses the module sems-intel/17.0.1
>       
>       * sets "setenv INTEL_LICENSE_FILE /projects/sems/install/rhel7-x86_64/sems/compiler/intel/17.0.1/base/Licenses/intel-Linux-SON.lic "
> 
> 
> I was able to use the sems module by doing
> 
>     * unset INTEL_LICENSE_FILE
> 
>     * export LM_LICENSE_FILE=[28518@cee-infra009.sandia.gov](mailto:28518@cee-infra009.sandia.gov)
> 
> 
> and then successfully did 'icc --version' and compiled a test source. Options
> 
>     1. Ask sems to change their module to use the same license information as the default compiler module or update the license file in use
> 
>     2. Make the environment changes in the PR job via the pullrequest.ini file
> 
>     3. Other?

Should we do 2 for now and look at 1 longer term?

**Comment by prwolfe** [comment]
> > Options
> > ```
> > 1. Ask sems to change their module to use the same license information as the default compiler module or update the license file in use
> > 
> > 2. Make the environment changes in the PR job via the pullrequest.ini file
> > 
> > 3. Other?
> > ```
> 
> Should we do 2 for now and look at 1 longer term?

Probably - I hate temporary solutions as they tend to be very permanent. I will put together a PR.

I sent an e-mail to seas-help already

**Comment by prwolfe** [comment]
Looks like the jobs that launch are going through ok - so far only 2 PR's have completed and another is close. Several did not manage to launch all the jobs as a few node (115 and 144) are not connecting to Jenkins. I don't have any feedback on that from the Jenkins server so I put in a ticket with the admin team.

**Comment by william76** [comment]
@prwolfe @bartlettroscoe 
I did a quick grep on places that have the old proxy in them still (wwwproxy):

```
cmake/tribits/ctest_driver/README:machines, this is http://wwwproxy.sandia.gov:80/.
cmake/tribits/ctest_driver/README:  export TDD_HTTP_PROXY="http://wwwproxy.sandia.gov:80/"
cmake/tribits/ctest_driver/README:  set TDD_HTTP_PROXY="http://wwwproxy.sandia.gov:80/"
cmake/tribits/python_utils/download-cmake.py:    default_http_proxy  = "http://wwwproxy.sandia.gov:80/"
cmake/tribits/python_utils/download-cmake.py:    default_https_proxy = "https://wwwproxy.sandia.gov:80/"
cmake/tribits/python_utils/download-cmake.py:the fully qualified form, as in: --http-proxy="http://wwwproxy.sandia.gov:80/"
cmake/ctest/drivers/s861036/cron_driver.sh:export TDD_HTTP_PROXY="http://wwwproxy.sandia.gov:80/"
cmake/ctest/drivers/lightsaber/cron_driver.csh:setenv TDD_HTTP_PROXY "http://wwwproxy.sandia.gov:80"
cmake/ctest/drivers/lightsaber/cron_driver.csh:setenv TDD_HTTPS_PROXY "https://wwwproxy.sandia.gov:80"
cmake/ctest/drivers/lightsaber/cron_driver.csh:setenv http_proxy "http://wwwproxy.sandia.gov:80"
cmake/ctest/drivers/lightsaber/cron_driver.csh:setenv https_proxy "https://wwwproxy.sandia.gov:80"
cmake/ctest/drivers/gabriel/cron_driver_gabriel.sh:export TDD_HTTP_PROXY="http://wwwproxy.sandia.gov:80/"
cmake/ctest/drivers/muir/cron_driver.sh:export TDD_HTTP_PROXY="http://wwwproxy.sandia.gov:80/"
cmake/ctest/drivers/trilinos-test/cron_driver.sh:export TDD_HTTP_PROXY="http://wwwproxy.sandia.gov:80/"
cmake/ctest/drivers/rouson-mp/cron_driver.sh:export TDD_HTTP_PROXY="http://wwwproxy.ca.sandia.gov:80/"
cmake/ctest/drivers/sourcery/cron_driver.sh:export TDD_HTTP_PROXY="http://wwwproxy.ca.sandia.gov:80/"
cmake/ctest/drivers/typhon/cron_driver.sh:export TDD_HTTP_PROXY="http://wwwproxy.sandia.gov:80"
cmake/ctest/drivers/typhon/cron_driver.sh:export http_proxy="http://wwwproxy.sandia.gov:80"
cmake/ctest/drivers/hansel/cron_driver.sh:export TDD_HTTP_PROXY="http://wwwproxy.sandia.gov:80/"
cmake/ctest/drivers/rhel6-x86_64/SERIAL_OPT_GCC_4.7.2/cron_driver.sh:export TDD_HTTP_PROXY="http://wwwproxy.sandia.gov:80/"
cmake/ctest/drivers/eleanor/cron_driver.sh:export TDD_HTTP_PROXY="http://wwwproxy.sandia.gov:80"
cmake/ctest/drivers/eleanor/cron_driver.sh:export http_proxy="http://wwwproxy.sandia.gov:80"
packages/kokkos-kernels/doc/kokkos-promotion.txt:         export https_proxy=http://wwwproxy.sandia.gov:80
packages/kokkos/doc/kokkos-promotion.txt:         export https_proxy=http://wwwproxy.sandia.gov:80
```
It looks like most of this is in tribits or ctest/drivers.

Should we do a pass sometime and do a search/replace with the new proxy info? 
Do we know what stuff in `cmake/ctest/drivers` is still in use? That's the pre-PR test driver stuff, right?

**Comment by jhux2** [comment]
`eleanor` and `typhon` -- belong to me, are no longer being used for nightly specialized testing.
`lightsaber` -- @csiefer2
`gabriel` -- @bartlettroscoe?
`rouson-mp` and `sourcery` -- Damian Rouson or @kmorris3?
`hansel` -- @crtrott?
`muir` -- Mark Hoemmen's old machine?

**Comment by bartlettroscoe** [comment]
> gabriel -- @bartlettroscoe?

That machine has been gone for many years (perhaps 10?)

**Comment by prwolfe** [comment]
From those comments we should remove the old stuff then do a search/replace pass.

Removed code does not need to be tested!

Paul

**Comment by prwolfe** [comment]
All related issues are closed - I believe this one is done.
