### ISSUE TITLE
Framework: Migrate to new Jenkins

### ISSUE THREAD

**Issue by jwillenbring** [trilinos/Trilinos#9298]
## Enhancement
@trilinos/framework 

We need to migrate to a new Jenkins server.

**Comment by allevin** [comment]
@jwillenbring FYI, SST is working on setting up a JaaS system (Jenkins as a Service) as other teams have.  Suggest that @trilinos/framework investigate this.  @wadeburgess may be able to put you in contact with the right people.

**Comment by jwillenbring** [comment]
@fryeguy52 Has requested and begun to set up the new Jenkins instance. A weaver agent is set up. Next step is to set up authentication to gitlab-ex.

**Comment by jwillenbring** [comment]
General setup of the new Jenkins is done. The weaver agent works. What remains is to migrate other agents to the new Jenkins.

**Comment by wadeburgess** [comment]
Closing since this has been migrated to Jira
