### ISSUE TITLE
Teuchos on Cray with Intel

### ISSUE THREAD

**Issue by crtrott** [trilinos/Trilinos#93]
We are tracking problems all over Trilinos which appear to originate in Teuchos, in particular the Output classes. This manifested in multiple down stream packages as segfaults, which according to some extensive debugging seem to happen due to virtual function pointers which are 0. 
The same compiler combination (Intel 15 and GCC 4.9.2) is fine on basic Red Hat system. Currently we suspect a compiler bug or something similar in the cray environment. I will add more details later.

**Comment by crtrott** [comment]
One of the failing tests which seem to expose this is this:
```
crtrott@volta:~/TrilinosBuild/Teuchos/build/packages/teuchos/parameterlist/test/FancyOutputting> aprun -n 1 ./TeuchosParameterList_FancyOutputting_test.exe 

***
*** Printing to default OStream before main() even starts!
***

Teuchos::GlobalMPISession::GlobalMPISession(): started processor with name nid00060 and rank 0!

Teuchos in Trilinos 12.7 (Dev)


***
*** Testing VerboseObject base class use
***

*** Algorithm output with default formatting

_pmiu_daemon(SIGCHLD): [NID 00060] [c0-0c0s15n0] [Fri Jan 22 10:13:08 2016] PE RANK 0 exit signal Segmentation fault
Application 244782 exit codes: 139
Application 244782 resources: utime ~0s, stime ~0s, Rss ~7200, inblocks ~5389, outblocks ~20429
```

**Comment by nmhamster** [comment]
I am seeing the same errors in the NALU builds when using Intel 15.3 and Intel 16.1 on the Cray platform with GCC 4.9.2 loaded.

**Comment by crtrott** [comment]
The aformentioned test is failing in VerboseObject::VerboseObject which gets triggered through the ALgorithmA (AlgorithmA algoA;) construction in FancyOutputting_test.cpp.

**Comment by crtrott** [comment]
The following diff fixes the issue in the parameter list test. But Tpetra Multivector Unittest still fails when testing describable. 

```
diff --git a/packages/teuchos/core/src/Teuchos_VerboseObject.cpp b/packages/teuchos/core/src/Teuchos_VerboseObject.cpp
index 46108fa..286140a 100644
--- a/packages/teuchos/core/src/Teuchos_VerboseObject.cpp
+++ b/packages/teuchos/core/src/Teuchos_VerboseObject.cpp
@@ -102,7 +102,7 @@ void VerboseObjectBase::initializeVerboseObjectBase(
   )
 {
   thisOStream_ = oStream;
-  informUpdatedVerbosityState();
+  //informUpdatedVerbosityState();
 }
 
 
diff --git a/packages/teuchos/core/src/Teuchos_VerboseObject.hpp b/packages/teuchos/core/src/Teuchos_VerboseObject.hpp
index 6ae674b..88ad507 100644
--- a/packages/teuchos/core/src/Teuchos_VerboseObject.hpp
+++ b/packages/teuchos/core/src/Teuchos_VerboseObject.hpp
@@ -392,7 +392,7 @@ void VerboseObject<ObjectType>::initializeVerboseObject(
   )
 {
   thisVerbLevel_ = verbLevel;
-  this->initializeVerboseObjectBase(oStream);
+  VerboseObjectBase::initializeVerboseObjectBase(oStream);
 }
```

**Comment by crtrott** [comment]
The Multivector thing was misleading. That was due to an unrelated bug which was fixed yesterday or so, I just had not updated yet. Tpetra passes now. I am going to test MueLu now.

**Comment by bartlettroscoe** [comment]
No idea what this is about but making that change I think breaks existing behavior (but we might have a test that is missing).

**Comment by crtrott** [comment]
I was greping through the code for informUpdatedVerbosityState and the only place that that is called is in Thyra. I think the second change (eliminiate the this->) should be fine and still give the same behaviour as before. So currently I believe that the only one who would potentially be effected is Thyra (since the function is empty inside of VerboseObjectBase itself), since its the only package which implements its own version of that virtual function.

**Comment by crtrott** [comment]
Just to add: fixing the issues we have is absolutely critical since it prevents the usage of Trilinos on Trinity, i.e. the new production platform of Sandia/Los Alamos where science runs are supposed to start like now.

**Comment by bartlettroscoe** [comment]
Since I don't have access to this platform, I can't reproduce this issue.  It looks like the only classes that will be affected are:

```
[8vt@th232 thyra (master)]$ find . -name "*pp" -exec grep -l informUpdatedVerbosityState  {} \;
./core/src/support/operator_solve/client_support/Thyra_DefaultBlockedTriangularLinearOpWithSolveFactory_def.hpp
./core/src/support/operator_solve/client_support/Thyra_DefaultBlockedTriangularLinearOpWithSolveFactory_decl.hpp
./core/src/support/operator_solve/client_support/Thyra_DelayedLinearOpWithSolve_def.hpp
./core/src/support/operator_solve/client_support/Thyra_DelayedLinearOpWithSolveFactory_def.hpp
./core/src/support/operator_solve/client_support/Thyra_DelayedLinearOpWithSolve_decl.hpp
./core/src/support/operator_solve/client_support/Thyra_DelayedLinearOpWithSolveFactory_decl.hpp
```
Those are not terribly important classes so if you need to make this change for now, so be it.

Actually, can you just put in an ifdef for this platform and comment out the call of this virtual function only on that platform?  For example, can you do:

```
{
  thisOStream_ = oStream;
#ifndef <the_bad_cray_compiler>
  informUpdatedVerbosityState();
#endif
 }
``` 

Just fill in `<the_bad_cray_compiler>` with whatever identifies that compiler.

Sometimes you have to hack around compiler defects.  That is life (but that does not mean that we should not complain like hell to the people that force use to use these substandard compilers).

**Comment by crtrott** [comment]
Yeah I was thinking of doing something like that actually. Its a bit more complicated than just the compiler version since the same compiler combination (Intel 15/GCC 4.9.2) seems to be fine on red hat, but we probably can identifiy the platform somehow. Worst case I put an ifdef in there, which the (currently few) affected users have to put on the CXX_FLAGS.

**Comment by bartlettroscoe** [comment]
> Yeah I was thinking of doing something like that actually. Its a bit more complicated than just the compiler version since the same compiler combination (Intel 15/GCC 4.9.2) seems to be fine on red hat, but we probably can identifiy the platform somehow. Worst case I put an ifdef in there, which the (currently few) affected users have to put on the CXX_FLAGS.

If you do that, you could add a macro like `THIS_IS_TRINITY_CRAY` or something.  Then, at configure time, you could add logic (perhaps in Teuchos) to add `#define THIS_IS_TRINITY_CRAY` to the configured TeuchosCore_config.h file.  That is likely the best way to do this since it will also make sure that gets defined for all downstream Trilinos customer code.  If you just tell people to add `-DTHIS_IS_TRINITY_CRAY` to their CMAKE_CXX_FLAGS, they are going to be mad when they did not get the "memo" and get build failures.  I did this same thing many years ago for a bad IBM compiler and it caused a lot of people a lot of headaches since this did not know about this magic variable.  Now that we have CMake, we can do a lot of checking at configure time and handle this sort of thing automatically for the user.

**Comment by crtrott** [comment]
True enough, I will do that then eventually. Right now I am looking into failures in MueLu Parameter list tests which are probably connected.

**Comment by crtrott** [comment]
Ok so I am adding the top level Teuchos_ENABLE_CRAY_VERBOSEOBJECT_FIX cmake variable
and the TEUCHOSCORE_CRAY_VERBOSEOBJECT_FIX macro to guard the fix. Unfortunately we didn't yet find an automatic way to enable it since we are not building with the cray compiler.

**Comment by bartlettroscoe** [comment]
There may be other bug fixes for that platform so you might not want to just name it for that compiler/platform instead of the specific hack.  Just a suggestion.

**Comment by crtrott** [comment]
I got a reproduction example which is fairly short, we will probably file it through a bug report.

**Comment by crtrott** [comment]
Here is some text I found which seems to indicate that the code is valid:
```
However, during the construction and destruction of an object, the rules for virtual method dispatch on that object are restricted. The C++ Standard, [class.cdtor], paragraph 4 [ISO/IEC 14882-2014], states:

Member functions, including virtual functions, can be called during construction or destruction. When a virtual function is called directly or indirectly from a constructor or from a destructor, including during the construction or destruction of the class’s non-static data members, and the object to which the call applies is the object (call it x) under construction or destruction, the function called is the final overrider in the constructor’s or destructor’s class and not one overriding it in a more-derived class. If the virtual function call uses an explicit class member access and the object expression refers to the complete object of x or one of that object’s base class subobjects but not x or one of its base class subobjects, the behavior is undefined.
```
that said, it looks as if my fix would not change the behaviour of code, since the informUpdatedVerbosityState();
call during construction of VerboseObjectBase is only allowed to actually invoke the empty variant of that function in VerboseObjectBase. Hence we don't need to call it at all.
Also the change of "this->" to "VerboseObjectBase::" should again not actually change the behaviour since VerboseObject doesn't override the initializeVerboseObjectBase member function and during construction it is not allowed to call the variant from a derived class further downstream anyway.

**Comment by bartlettroscoe** [comment]
@crtrott,

Looking over this more carefully, I see where there are problems.  I am surprised that compilers don't warn about this.  Looking at these "initialize" functions, I can see that they are never called by outside clients in Trilinos:

```
$ find . -name "*" -exec grep -l initializeVerboseObject {} \;
./packages/teuchos/core/src/Teuchos_VerboseObject.hpp
./packages/teuchos/core/src/Teuchos_VerboseObject.cpp
```

That means that these functions are only ever called by the constructors for these classes (and therefore should not be virtual or public).

Actually, looking at initializeVerboseObjectBase(), I am not sure that function really works correctly anyway when called later anyway.  Therefore, what I would try is:

1) Make the functions VerboseObjectBase::initializeVerboseObjectBase() and VerboseObjectBase::initializeVerboseObject() *non-virtual* and *protected*.  Since these are only called by the constructors (perhaps indirectly), that should be fine.

2) Remove the call of the virtual function informUpdatedVerbosityState() from  VerboseObjectBase::initializeVerboseObjectBase() (as you have already done).

@crtrott, can you see if that fixes the problem on this machine?  With this, you should not have to mess with any macros.  Also, can you push the commit to a branch in the main Trilinos repo with a pull-request so that I can review?

**Comment by hcedwar** [comment]
C++11 standard 10.4.6:
Member functions can be called from a constructor (or destructor) of an abstract class; the effect of making a virtual call (10.3) to a pure virtual function directly or indirectly for the object being created (or destroyed) from such a constructor (or destructor) is undefined.

Not a good idea to call virtual functions from within a constructor or destructor.

**Comment by crtrott** [comment]
In this case the code was not calling pure virtual functions. The base classes have implementations of the called functions.

**Comment by bartlettroscoe** [comment]
> Not a good idea to call virtual functions from within a constructor or destructor.

Yes, of course.  Obviously this was a mistake (as I said above).  Why compilers don't not warn about this, I have no idea.

**Comment by bartlettroscoe** [comment]
> In this case the code was not calling pure virtual functions. The base classes have implementations of the called functions. 

While it should be valid code, in general it usually does not have the behavior that would be expected in that it will not act like a virtual function.  But in this case, I would argue that everything should have worked fine (and it did on other more compliant compilers).

**Comment by crtrott** [comment]
Pull request is posted.

**Comment by bartlettroscoe** [comment]
I reviewed the commit c97162f and it looks perfect.  If this builds and passes all of the tests, then this is fine to push.

Thanks for taking care of this @crtrott!

**Comment by aprokop** [comment]
Am I right assuming that we are getting a Jenkins build on Volta some time soon to make sure our stuff runs on Trinity?

**Comment by nmhamster** [comment]
Yes, we are working on it. We need to ensure this is done correctly using the SEMS and center testing infrastructure so it takes a bit longer to bring up.

**Comment by crtrott** [comment]
Ross: did something go wrong with the push? @bartlettroscoe

**Comment by bartlettroscoe** [comment]
@crtrott, sorry, I thought that you were going to push this.  I did the review and said it was okay to push.

**Comment by crtrott** [comment]
Arg I thought your "if this passes all tests" means you were running tests. Ok I push it.

**Comment by crtrott** [comment]
Pushed a fix. We need to verify on Cray.

**Comment by nmhamster** [comment]
Runnng on Volta now.

**Comment by mhoemmen** [comment]
Looks like this is done.  Please feel free to reopen if not.  Thanks @crtrott for the fix, and thanks all for testing!
