### ISSUE TITLE
Test Ifpack2_Jacobi_bcsstk14_hb_belos_MPI_1 randomly failing in PR testing?

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#9306]
CC: @trilinos/ifpack2, @srajama1 (Linear Solvers lead)

## Description

The test `Ifpack2_Jacobi_bcsstk14_hb_belos_MPI_1` appears to be randomly failing in several Trilinos PR builds as shown by [this query](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&begin=2021-03-01&end=2021-06-18&filtercount=3&showfilters=1&filtercombine=and&field1=groupname&compare1=61&value1=Pull%20Request&field2=testname&compare2=61&value2=Ifpack2_Jacobi_bcsstk14_hb_belos_MPI_1&field3=status&compare3=61&value3=failed) showing:

Site | Build Name | Test Name | Status | Time | Proc Time | Details | Build Time | Processors
-- | -- | -- | -- | -- | -- | -- | -- | --
ascic141 | PR-8638-test-Trilinos_pullrequest_gcc_8.3.0-4784 | Ifpack2_Jacobi_bcsstk14_hb_belos_MPI_1 | Failed | 900ms | 900ms | Completed (Failed) | 2021-06-17T16:05:42 MDT | 1
ride17 | PR-9245-test-Trilinos_pullrequest_cuda_10.1.105-1401 | Ifpack2_Jacobi_bcsstk14_hb_belos_MPI_1 | Failed | 3s 300ms | 3s 300ms | Completed (Failed) | 2021-06-10T19:10:43 MDT | 1
ascic158 | PR-9245-test-Trilinos_pullrequest_gcc_7.2.0_debug-2684 | Ifpack2_Jacobi_bcsstk14_hb_belos_MPI_1 | Failed | 830ms | 830ms | Completed (Failed) | 2021-06-10T19:10:06 MDT | 1

It just took out my last PR testing iteration https://github.com/trilinos/Trilinos/pull/8638#issuecomment-863682541.

The changes in PR #8638 should not be able to impact this test in this way.  (It only wraps the compilers to capture build stats, nothing else.)

This test failed in 1 different ways:

* Printed `Actual iters(571) > expected number of iterations (562), or resid-norm(0) >= 1.e-7` (see [here](https://testing.sandia.gov/cdash/test/76990842), this caused https://github.com/trilinos/Trilinos/pull/8638#issuecomment-863682541 to fail).
* Segfaulted (see [here](https://testing.sandia.gov/cdash/test/76172655))
* Printed `Error in build_solver: solver_type (Block Gmres) not recognized` (see [here](https://testing.sandia.gov/cdash/test/76100991))

That last failure does not look random and my have been a problem with the branch in PR #9245.

**Comment by cgcgcg** [comment]
@hkthorn Could #9264 have something to do with this?

**Comment by jhux2** [comment]
If this a problem for PRs, we could just temporarily disable this test.

**Comment by jhux2** [comment]
[One](https://testing.sandia.gov/cdash/test/76990842) of the failures has this message:

```
Kokkos::OpenMP::initialize WARNING: OMP_PROC_BIND environment variable not set
  In general, for best performance with OpenMP 4.0 or better set OMP_PROC_BIND=spread and OMP_PLACES=threads
  For best performance with OpenMP 3.1 set OMP_PROC_BIND=true
  For unit testing set OMP_PROC_BIND=false
```

I'd think that this would be set to `false` for PR testing.

**Comment by hkthorn** [comment]
@cgcgcg @jhux2 I can disable this test for the time being.
