### ISSUE TITLE
Test TpetraCore_Bug7758_MPI_4 randomly failing in clang_10.0.0 PR build with mangled output

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#9307]
CC: @trilinos/tpetra, @kddevin (Data Services Lead)

## Description

As shown in [this query](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&begin=2021-03-01&end=2021-06-18&filtercount=4&showfilters=1&filtercombine=and&field1=groupname&compare1=61&value1=Pull%20Request&field2=testname&compare2=61&value2=TpetraCore_Bug7758_MPI_4&field3=status&compare3=61&value3=failed&field4=testoutput&compare4=95&value4=TEST%20PASSED) showing:

Site | Build Name | Test Name | Status | Time | Proc Time | Details | Build Time | Processors
-- | -- | -- | -- | -- | -- | -- | -- | --
tr-test-9.novalocal | PR-8638-test-Trilinos_pullrequest_clang_10.0.0-2869 | TpetraCore_Bug7758_MPI_4 | Failed | 190ms | 760ms | Completed (Failed) | 2021-06-17T16:06:04 MDT | 4
tr-host-0.novalocal | PR-9259-test-Trilinos_pullrequest_clang_10.0.0-2852 | TpetraCore_Bug7758_MPI_4 | Failed | 330ms | 1s 320ms | Completed (Failed) | 2021-06-17T00:25:51 MDT | 4
tr-test-9.novalocal | PR-8944-test-Trilinos_pullrequest_clang_10.0.0-2433 | TpetraCore_Bug7758_MPI_4 | Failed | 180ms | 720ms | Completed (Failed) | 2021-04-27T14:28:37 MDT | 4
tr-test-9.novalocal | PR-8821-test-Trilinos_pullrequest_clang_10.0.0-2360 | TpetraCore_Bug7758_MPI_4 | Failed | 190ms | 760ms | Completed (Failed) | 2021-04-16T17:52:28 MDT | 4

the test `TpetraCore_Bug7758_MPI_4` appears to be randomly failing. 

It looks like there is a race condition in writing STDOUT that is mangling test output and not clearly printing  `End Result: TEST PASSED`.  For example, this last failure taking out my last PR iteration https://github.com/trilinos/Trilinos/pull/8638#issuecomment-863682541 showed:

```
End2 NOSAMES TO DEFAULT 
 Result: TEST PASSED
```

**Comment by kddevin** [comment]
Fixed by #9308
