### ISSUE TITLE
Tpetra:  getting host device count errors on an internal tpetra var

### ISSUE THREAD

**Issue by bathmatt** [trilinos/Trilinos#9309]
## Bug Report
@trilinos/tpetra 

@jhux2 this is blocking progress on lots of the muelu stuff

### Description
I am working to make muelu UVM free and I'm seeing an error inside of Tpetra when I am calling getLocalDiagCopy.  There is a call inside Tpetra 

  >│4151        auto valuesPackedHost = valuesPacked_wdv.getHostView(Access::ReadOnly);                                                                                                                           │

and this trips the device host view count error

"Tpetra::Details::WrappedDualView (name =	Tpetra::CrsMatrix::values; host	use_count = 4; device use_count	= 5): Cannot access data on host while a device	view is	alive"

Now, this is an internal variable within Tpetra so it is likely a Tpetra bug somewhere.  I could use some help tracking this down and would be willing to pair program with a tpetra guy.

### Steps to Reproduce
1.Branch: muelu-tpetra-dep
1. Configure script: [conf.txt](https://github.com/trilinos/Trilinos/files/6678609/conf.txt)
1. test command: [mbetten@ascicgpu042 unit_tests]$ ctest -R CreatePreconditioner

**Comment by brian-kelley** [comment]
@bathmatt This exception is how tpetra enforces the requirement that host and device view lifetimes can't overlap. It means that something before called ``getLocalValuesView()`` or ``getLocalMatrixDevice()`` and is still holding that view/matrix.

**Comment by bathmatt** [comment]
> @bathmatt This exception is how tpetra enforces the requirement that host and device view lifetimes can't overlap. It means that something before called `getLocalValuesView()` or `getLocalMatrixDevice()` and is still holding that view/matrix.

I totally get that, however, it is a tpetra protected temp variable so I don't control it, something inside of Tpetra must be holding on to this somehow.

**Comment by brian-kelley** [comment]
@bathmatt I looked at the backtrace and the problem is that MueLu CoaleseDropFactory_kokkos is getting the local (device) matrix near the top of Build() and holding onto it:
```
549       auto kokkosMatrix = A->getLocalMatrix();
550       auto nnzA  = kokkosMatrix.nnz();
551       auto rowsA = kokkosMatrix.graph.row_map;
```
but then the diagonal extraction a bit later needs to get the same local matrix on host:
```
589           RCP<Vector> ghostedDiag;
590           {
591             SubFactoryMonitor m2(*this, "Ghosted diag construction", currentLevel);
592             ghostedDiag     = Utilities_kokkos::GetMatrixOverlappedDiagonal(*A);
593           }
```

**Comment by bathmatt** [comment]
Shit sorry, didn't realize that was kept with the matrix, 
sorry and thank you so much

**Comment by bathmatt** [comment]
Mia Coppa, thanks @brian-kelley
