### ISSUE TITLE
Build stats fails for PRs that don't build anything

### ISSUE THREAD

**Issue by cgcgcg** [trilinos/Trilinos#9314]
## Bug Report
@bartlettroscoe @jjellio 

### Description
The build stats script seems to fail for PR builds that don't compile anything:
https://testing.sandia.gov/cdash/viewTest.php?onlyfailed&buildid=9376784

**Comment by bartlettroscoe** [comment]
@cgcgcg, sorry about that.  I will fix that ASAP and submit a PR.

**Comment by bartlettroscoe** [comment]
@cgcgcg, the fix in in PR #9315.  Can you please approve that PR so it can merge once testing is complete?

**Comment by cgcgcg** [comment]
Thanks for the fix!
