### ISSUE TITLE
Expose Belos' fixed solver through Stratimikos

### ISSUE THREAD

**Issue by aprokop** [trilinos/Trilinos#932]
@trilinos/stratimikos @trilinos/belos 

I have a code that uses Stratimikos/Thyra to run a preconditioned solve for a linear problem. I'd like to try out a preconditioner in a Richardson/fixed point iteration. The easiest thing would be to try out the Belos' fixed point iteration (@mhoemmen @csiefer2 is it used/correct/recently tested?)

Unfortunately, it does not seem to be exposed through Stratimikos. I will probably have to fix this.

**Comment by csiefer2** [comment]
Probably not / Probably / Only lightly.

**Comment by bartlettroscoe** [comment]
What code is this?  Why can't it be exposed through Stratimikos?

**Comment by amklinv** [comment]
https://trilinos.org/docs/dev/packages/belos/doc/html/classBelos_1_1FixedPointSolMgr.html

It works just like any other Belos solver manager; I don't see any reason it can't be exposed through Stratimikos.

In answer to your other question, the fixed point solver does get used.  @mhoemmen can give you more information.

**Comment by mhoemmen** [comment]
@aprokop @csiefer2 would it make sense to have Richardson iteration in Ifpack2 instead of in Belos?  Just curious.  Either way, folks would have to add something to Stratimikos if they want it exposed there.

**Comment by aprokop** [comment]
@mhoemmen It may. But if you have a code that goes through Stratimikos, does it not have to use a Belos solver? If that's the case, it will still need a Belos fixed iteration.

> Either way, folks would have to add something to Stratimikos if they want it exposed there.

Right. I plan on adding the code in the next day or two. Btw, what is it's proper name, "FIXED POINT", or "Fixed Point", or something else?

**Comment by mhoemmen** [comment]
@aprokop wrote:
> Btw, what is it's proper name, "FIXED POINT", or "Fixed Point", or something else?

Belos' factory should just map everything to upper case.  I'm hoping that Stratimikos uses Belos' factory, and doesn't try to reimplement the factory.

**Comment by aprokop** [comment]
Stratimikos adapter has hardcoded names for validation. And from what I was it does try to reimplement the Belos factory.

**Comment by hkthorn** [comment]
To be fair, Stratimikos came before the Belos solver factory.  But I think there is a valid case for using the Belos factory from within Stratimikos to avoid parameter naming conflicts.  Such a change would also have to address backward compatibility since many users of Belos go through Stratimikos.

Mark, any thoughts?

Heidi

--

Heidi K. Thornquist
Electrical Models & Simulation
Sandia National Laboratories
Albuquerque, NM  87185-1323

**Comment by bartlettroscoe** [comment]
Just the be clear, Stratimikos is designed to provide a single point of selection for various direct and iterative linear solvers.  It is not just a wrapper around only Belos solvers.

**Comment by mhoemmen** [comment]
@hkthorn wrot:
> To be fair, Stratimikos came before the Belos solver factory.

That's right.  I didn't expect time travelers ;-)  Stratimikos does not currently use Belos' factory.

> But I think there is a valid case for using the Belos factory from within Stratimikos to avoid parameter naming conflicts. Such a change would also have to address backward compatibility since many users of Belos go through Stratimikos. Mark, any thoughts?

I agree.  I think we can get backwards compatibility in Stratimikos by looking at and possibly changing the user's input strings, while still using Belos' factory.

**Comment by aprokop** [comment]
If I read it write, here are the steps to do:
- [ ] Add a parameter converter for currently accepted Stratimikos "Belos" names to proper Belos names
- [ ] Switch in Stratimikos to using Belos SolverFactory
- [ ] Deprecate custom Stratimikos names

**Comment by aprokop** [comment]
Have not had time to work on this, and the priority for me dropped. This is now a free-for-all issue.
