### ISSUE TITLE
Tpetra: link error for extended scalar types + ETI=OFF when using certain routines

### ISSUE THREAD

**Issue by ikalash** [trilinos/Trilinos#9325]
I was asked to open this issue by @hkthorn in the discussion found here: https://github.com/trilinos/Trilinos/pull/9281 .  I've recently been doing some work in Trilinos to make it possible to do a Belos linear solve with an extended ScalarType (e.g. long double, float128).  The capability works in a ETI=OFF build but it looks like there are still some issues when using certain Tpetra routines in an ETI=ON build.  I have created a branch that manifests the problem: https://github.com/trilinos/Trilinos/tree/longdouble-eti .  If this branch is built with Ifpack2 tests and ETI = ON (using the attached configure script), the Belos long double test I have put into this branch will fail to link due to the following error: 

```
 87%] Linking CXX executable Ifpack2_tif_belos_longdouble.exe
/usr/bin/ld: CMakeFiles/Ifpack2_tif_belos_longdouble.dir/belos_solve_longdouble.cpp.o: in function `main':
belos_solve_longdouble.cpp:(.text.startup+0x721): undefined reference to `void Tpetra::MatrixMatrix::Multiply<long double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >(Tpetra::CrsMatrix<long double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > const&, bool, Tpetra::CrsMatrix<long double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > const&, bool, Tpetra::CrsMatrix<long double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >&, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Teuchos::RCP<Teuchos::ParameterList> const&)'
collect2: error: ld returned 1 exit status
make[2]: *** [packages/ifpack2/test/belos/CMakeFiles/Ifpack2_tif_belos_longdouble.dir/build.make:145: packages/ifpack2/test/belos/Ifpack2_tif_belos_longdouble.exe] Error 1
make[1]: *** [CMakeFiles/Makefile2:12310: packages/ifpack2/test/belos/CMakeFiles/Ifpack2_tif_belos_longdouble.dir/all] Error 2
```

The problem specifically is this line, which calls the ```Tpetra:MatrixMatrix::Multiply``` routine (in TpetraExt): https://github.com/trilinos/Trilinos/blob/longdouble-eti/packages/ifpack2/test/belos/belos_solve_longdouble.cpp#L135, which I added intentionally to the test to be able to trigger the problem w/o needing to build any external codes on top of Trilinos.  I think I added all the infrastructure for ETI to work for the basic Tpetra routines to ```Tpetra_config.h.in``` and the test compiles/runs just fine if I take the TpetraExt::MatrixMatrix call out.  Are the TpetraExt routines not instantiated in the same way as the usual Tpetra routines?  I am guessing something like this is the problem and was wondering if someone more familiar with the inner workings of Tpetra and how it works with ETI can weigh in.  This is not a super critical issue for me right now but based on the discussion in PR  https://github.com/trilinos/Trilinos/pull/9281, it seems the extended scalar types are of interest to various other folks, so making a note of the problem is worthwhile.

Note that, to reproduce the problem, one needs to use the following fork/branch of Kokkos: https://github.com/ikalash/kokkos/tree/for-alegra (my changes to Kokkos for the extended scalar types are not pushed to Kokkos develop yet).

[do-cmake-trilinos-mpi-camobap-extended-sts.txt](https://github.com/trilinos/Trilinos/files/6690164/do-cmake-trilinos-mpi-camobap-extended-sts.txt)

@trilinos/tpetra

**Comment by csiefer2** [comment]
The MatrixMatrix stuff uses part, but not all of the Tpetra ETI system.  It uses the _macros_ but not the automated CPP file generation.  That stuff predated the Tpetra ETI system and somehow didn't get converted over.

You need to add your stuff to the cpp files directory, sad to say.

**Comment by ikalash** [comment]
Ah I see, I somehow completely missed the .cpp files with the template instantiations.  I'll give this a try, thanks!

There is definitely still some work to do for the extended scalar types in general, though I have made progress and some cases work end-to-end. 
 There's a lot of issues in Belos + ETI + float128 that discovered for example that @hkthorn is helping me with.  It's a bit like "wack-a-mole" - every time I fix one issue, something else crops up.  If there is interest in the extended scalar types, it would be great for someone to help streamline things.  I'm happy to share what I've learned / help.  I do have a nightly build set up to ensure what I have working does not get broken.

**Comment by csiefer2** [comment]
@ikalash What is your nightly test called so I know what to look for on cdash?

**Comment by ikalash** [comment]
Sure - this it my special scalar type build right now: https://sems-cdash-son.sandia.gov/cdash/viewTest.php?onlypassed&buildid=18206.  This build has ETI=OFF.  I'll probably add one with ETI once the PR related to this issue gets merged in.
