### ISSUE TITLE
MueLu: reenable nightly testing on rocketman

### ISSUE THREAD

**Issue by jhux2** [trilinos/Trilinos#9327]
## Bug Report
@trilinos/muelu

### Description
Nightly testing on rocketman has been down for a few months.  It needs to be reenabled.

**Comment by cgcgcg** [comment]
Looks like rocketman is back:
https://testing.sandia.gov/cdash/index.php?subproject=MueLu&project=Trilinos&filtercount=1&showfilters=1&field1=site&compare1=63&value1=rocketman

**Comment by jhux2** [comment]
The notification emails aren't working properly.  Not a high priority item, but I'll leave this open as a reminder to fix hat.

**Comment by jhux2** [comment]
The script in [this](https://github.com/trilinos/Trilinos/issues/7050#issuecomment-718883380) issue might provide a more robust solution than what is used on rocketman and other machines.
