### ISSUE TITLE
Tpetra: OpenMP-only build requires Serial

### ISSUE THREAD

**Issue by cgcgcg** [trilinos/Trilinos#9336]
## Bug Report
@trilinos/tpetra

### Description
A OpenMP-only build fails due to use of `Kokkos::Serial` here:
https://github.com/trilinos/Trilinos/blob/e7a5a6c29d8b2a6a565dacebfd861dd9504b1cdd/packages/tpetra/core/src/Tpetra_Details_WrappedDualView.hpp#L123-L124
Is Serial required for Tpetra? If so, that should maybe be checked by CMake?

**Comment by tasmith4** [comment]
That does seem like a bug.  Thanks for pointing this out.

**Comment by tasmith4** [comment]
@cgcgcg can you try changing `Kokkos::Serial` to `Kokkos::DefaultHostExecutionSpace` on that line?  Does that work in your build?

**Comment by cgcgcg** [comment]
Thanks for your help, @tasmith4!
