### ISSUE TITLE
Make MueLu dependency on Epetra optional

### ISSUE THREAD

**Issue by krcb** [trilinos/Trilinos#934]
Compiling MueLu with Epetra explicitly turned off reveals that (at least) muelu/test/scaling/ImportPerformance.cpp has a dependency on Epetra that is not wrapped at the CMake level (i.e. this test is enabled irrespective of whether Epetra is enabled or not).

**Comment by jhux2** [comment]
@trilinos/muelu I'll have a look at this.

**Comment by jhux2** [comment]
@krcb I just pushed what I think is a fix.  However, I can't really test this until Amesos2 doesn't depend on Amesos :).  Please let me know if this helps.

**Comment by krcb** [comment]
@jhux2 I just tested this out on #918 and the Epetra dependency is gone. Thanks!

**Comment by jhux2** [comment]
Great.  By the way, it looks like one of Ifpack2's tests (Ifpack2_UnitTestBlockRelaxationPerf.cpp) suffers from a similar problem.  I will open a separate ticket on this.
