### ISSUE TITLE
Xpetra (?): errors reported to Albany CDash site in clang builds

### ISSUE THREAD

**Issue by ikalash** [trilinos/Trilinos#9341]
Starting today, all the Albany and Albany/LCM Trilinos clang builds have started reporting errors: 

https://sems-cdash-son.sandia.gov/cdash/viewBuildError.php?buildid=18284
https://sems-cdash-son.sandia.gov/cdash/viewBuildError.php?buildid=18290
https://sems-cdash-son.sandia.gov/cdash/viewBuildError.php?buildid=18301 

Curiously I don't think these are real errors - I don't see any errors in the output and Albany builds just fine on top of the Trilinos with the errors.  Does anyone know what might cause this?  Tagging @lxmota as the owner of the Albany/LCM clang build.

@trilinos/xpetra @trilinos/muelu

**Comment by cgcgcg** [comment]
@bathmatt

**Comment by bathmatt** [comment]
@ikalash is there an easy way to reproduce this?  Are you building just Trilinos or Trilinos+Albany 

It is missing overrides with -Werror

**Comment by ikalash** [comment]
@bathmatt : oh yes, this is easy to reproduce.  Here are the modules and configure script on CEE.  The error happens when building Trilinos.

https://github.com/SNLComputation/Albany/blob/master/doc/dashboards/cee-compute011.sandia.gov/do-cmake-trilinos-mpi-sems-clang 
https://github.com/SNLComputation/Albany/blob/master/doc/dashboards/cee-compute011.sandia.gov/sems-clang-modules.sh

Would compiling with -Wno-error flags fix the problem?

**Comment by bathmatt** [comment]
I have a branch to test soon, give me a minute, i'm testing now

**Comment by ikalash** [comment]
Sounds good, thanks!

**Comment by bathmatt** [comment]
@ikalash i assigned you a MR to fix this

**Comment by ikalash** [comment]
Yes I saw this.  Will test this afternoon.  Thanks!

**Comment by bathmatt** [comment]
Hit merge if the PR tester and your tests pass please.

**Comment by ikalash** [comment]
The Albany clang nightlies are clean today - closing.
