### ISSUE TITLE
Framework: How does one test the cuda builds on ride

### ISSUE THREAD

**Issue by bathmatt** [trilinos/Trilinos#9345]
## Question
@trilinos/framework 

I have followed the directions at https://github.com/trilinos/Trilinos/wiki/Reproducing-PR-Testing-Errors and have been able to reproduce many issues.  However, I'm doing UVM removal and I need to get the tests running on ride without UVM.  

What are the steps to get that to work, 

what I do now
1. set up modules
2. bsub -Is bash #get backend node
3. build
4. ctest

ANy job that has a MPI proc count higher than 1 fails with a 
Not enough slots available 
error

I want to add xpetra to the things automatically tested but I can't reproduce locally 

@csiefer2 I saw you modified some of the testing last, do you have any idea

Thanks

**Comment by csiefer2** [comment]
Yup.  That will totally fail.

You need -n 4

**Comment by bathmatt** [comment]
Where do I need-n 4??

**Comment by csiefer2** [comment]
Because Ride's MPI will only let you get a single GPU if you do -n 1.  Even though there are 4 on the node...

**Comment by bathmatt** [comment]
Issue resolved, thanks @csiefer2
