### ISSUE TITLE
teko:  Particular GO for tpetra required?

### ISSUE THREAD

**Issue by keitat** [trilinos/Trilinos#9358]
## Question
@trilinos/teko 

In E4S and Spack, we observed teko requiring a specific GO value for version 12.15.
https://github.com/spack/spack/issues/24455

Does this problem persist with the latest version (13)?

**Comment by cgcgcg** [comment]
Which global ordinal do you need?

**Comment by cgcgcg** [comment]
Just checked, looks like @eric-c-cyr fixed this already.

**Comment by keitat** [comment]
Thanks!  It only happens with the older version.  Got it.
