### ISSUE TITLE
Framework: should Amesos2 tests be enabled in no-UVM PR testing?

### ISSUE THREAD

**Issue by jhux2** [trilinos/Trilinos#9359]
## Question
@trilinos/framework 
@trilinos/amesos2 
@lucbv @iyamazaki @csiefer2 @bathmatt 

As seen in [this round of PR testing](https://testing.sandia.gov/cdash/index.php?project=Trilinos&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=63&value1=PR-9338-test&field2=buildstarttime&compare2=84&value2=NOW), in the build [PR-9338-test-Trilinos_pullrequest_cuda_10.1.105_uvm_off-580](https://testing.sandia.gov/cdash/index.php?project=Trilinos&parentid=9410177&filtercount=1&showfilters=1&field1=buildstarttime&compare1=84&value1=NOW), the Amesos2 library is enabled, but its tests are not.

Are the Amesos2 tests UVM free?  If they are UVM-free, then shouldn't they be enabled in PR testing?

**Comment by lucbv** [comment]
I can make a PR to enable them and see what passes and what breaks, you can then at least enable all the tests that are currently working.
It is my expectation that the tests should pass since they do with HIPSpace but let us double check.

**Comment by iyamazaki** [comment]
Thank you, @lucbv & @jhux2. I thought [9288](https://github.com/trilinos/Trilinos/pull/9288) enabled the test, but maybe, we missed something. We've at least tested Amesos2 locally for SuperLU & KLU2 with/without UVM.

**Comment by csiefer2** [comment]
Amesos2 tests won't run if you don't touch code upstream from Amesos2.

The tests will be enabled if you do.

**Comment by bathmatt** [comment]
I've seen the tests do run sometimes so . . .   closing issue.
