### ISSUE TITLE
Intrepid Doxygen generation broken

### ISSUE THREAD

**Issue by jwillenbring** [trilinos/Trilinos#936]
@mperego @dridzal 

I noticed that the doxygen documentation for intrepid is not currently generating properly. This appears to be due to this commit:

commit e3ffb45f4172a69fd204a4b74e5cce1ca85d4cc9
Author: avdelor <avdelor@sandia.gov>
Date:   Tue Aug 11 09:31:27 2015 +0000

    Fixed executable flag in intrepid. Set folders to 755 and files to 644

Apparently a number of files in Intrepid were set to be executable accidentally, and all files in intrepid were made to be not executable, but the build_docs file needs to be executable.

I did a test and making the file executable again allows proper Doxygen generation. 

See the 12.8 Release link for the documentation I generated using the modified file. See the 12.10 release link as documentation that the file needs to be executable. Note that the development version documentation has not been updated for some time.

[intrepid documentation link](https://trilinos.org/packages/intrepid/intrepid-doxygen/)

Any objection to changing the executable flag for the build_docs file? I just want to confirm that I am not misinterpreting what I found, and that you still intend to generate Doxygen documentation for Intrepid. If there are no objections, would you like me to do this, or would you prefer to?

**Comment by mperego** [comment]
I'm fine changing the flag for the build_docs file. @dridzal, is that OK with you?
Thanks for looking at that.

**Comment by dridzal** [comment]
I'm fine with that, as long as the documentation starts generating properly again.

**Comment by jwillenbring** [comment]
Pushing the above referenced change resolved this issue as can be seen by the fact that the development version documentation has now been updated as of last Friday. Closing.
