### ISSUE TITLE
Ifpack2: Intermittent failure of Ifpack2BlockTriDi_double_int_longlong_Unit_UnitTest

### ISSUE THREAD

**Issue by prwolfe** [trilinos/Trilinos#9365]
## Bug Report
@trilinos/ifpack2 

### Description
There have been intermittent failures when promoting develop to master in the cuda 9.2 build of the Ifpack2BlockTriDi_double_int_longlong_Unit_UnitTest. See https://testing.sandia.gov/cdash/viewTest.php?onlyfailed&buildid=9449921 for an example. It takes only a few of these to effectively block develop promotion for long time periods.

**Comment by csiefer2** [comment]
@kyungjoo-kim

**Comment by kyungjoo-kim** [comment]
The core part of the code has not been changed. When I glance the recent changes, the modifications are made for HIP and UVM removal. I don't really see why the residual behavior slightly changed. The residual changes are not significant but I would like to be more cautious about the changes. Does this just happen in the last promotion or it still happen during other PR tests ? If the PR tests are fine, I don't really think that we need to relax the residual tolerance.
