### ISSUE TITLE
Amesos2:  info > 0 error

### ISSUE THREAD

**Issue by Adrian-Diaz** [trilinos/Trilinos#9366]
## Question
@trilinos/\<amesos2\>

I've got a linear system with a well defined result where the Amesos2 KLU solver gives me the correct answer if I run it up to 4 MPI ranks. However when I try with 5 or more ranks the solver gives me "info > 0" as an error. I've checked the output for the matrix and vectors I'm feeding to the solver and the values and the maps associated with them all seem correct to me. What motivates this error prompt? I've attached the matrix and vector data that introduces the issue.
[matrix_vector_output.txt](https://github.com/trilinos/Trilinos/files/6749999/matrix_vector_output.txt)

**Comment by Adrian-Diaz** [comment]
@srajama1

**Comment by cgcgcg** [comment]
Could you provide that matrix in MatrixMarket format? That might make it easier to reproduce the issue.

**Comment by Adrian-Diaz** [comment]
How does one output it in MatrixMarket format?

**Comment by cgcgcg** [comment]
https://github.com/trilinos/Trilinos/blob/d8c96d1ea19b5e60c1c6bc1b12c311f8b29b0ca0/packages/tpetra/core/inout/MatrixMarket_Tpetra.hpp#L5715-L5720
should do the trick. There are other methods to write maps as well.

**Comment by Adrian-Diaz** [comment]
[A_matrix.txt](https://github.com/trilinos/Trilinos/files/6751381/A_matrix.txt)

I couldn't get that to work for the vectors if you also wanted that.

**Comment by cgcgcg** [comment]
@Adrian-Diaz 
I hacked the example at https://github.com/trilinos/Trilinos/blob/master/packages/amesos2/example/SimpleSolve_File.cpp to use Klu2 instead of SuperLU and ran
```
mpiexec -n 5 ./Amesos2_SimpleSolveFileExample.exe --filename=A_matrix.txt --print-matrix --all-print
```
The solve goes through without any issue.
The output is quite similar to what you posted above. 
[log.txt](https://github.com/trilinos/Trilinos/files/6751432/log.txt)

One notable difference is that your matrix appears to have unmerged entries for (42,0). The matrix market writer summed them up, which might explain why the factorization didn't fail for me. Maybe try fixing that first and see if it helps.

**Comment by srajama1** [comment]
info > 0 is sort of a catch all error. None of the direct solvers can handle unmerged entries. As @cgcgcg points out fixing that might be the first step.

**Comment by Adrian-Diaz** [comment]
What does it mean for the entries to be unmerged? That matrix is the result of an import operation so maybe something went wrong there.

**Comment by cgcgcg** [comment]
In the log you posted it says that row 42 looks like this:
```
3           42           42 (33, -555.556)  (34, -208.333)  (35, 208.333)  (36, 555.556)  (37, 0)  (38, 2.84217e-14)  (39, -694.444)  (40, 416.667)  (41, 208.333)  (42, 8888.89)  (43, 0)  (0, -208.333)  (0, -208.333)  (0, -555.556)  (0, -694.444)  (0, -208.333)  (0, -416.667)  (18, -555.556)  (19, 0)  (20, -2.84217e-14)  (21, -555.556)  (22, 208.333)  (23, 208.333)  (24, 1111.11)  (25, 2.84217e-14)  (26, 5.68434e-14)  (27, -1388.89)  (28, -8.52651e-14)  (29, 833.333)  (30, -555.556)  (31, 0)  (32, -5.68434e-14)  (44, 0)  (45, -1111.11)  (46, -5.68434e-14)  (47, 833.333)  (48, 555.556)  (49, 0)  (50, -2.84217e-14)  (51, -694.444)  (52, -416.667)  (53, 208.333) 
```
There are multiple entries for (42,0), and they should be summed together into a single one.

**Comment by Adrian-Diaz** [comment]
Yea thanks for catching that repeat index. It turns out it was a bug with the setup for the Kokkos view fed into the matrix. Solver's working fine as far as this is concerned!
