### ISSUE TITLE
CMake configure (runtime) tests and Cross compiling

### ISSUE THREAD

**Issue by jjellio** [trilinos/Trilinos#937]
I am having a problem configuring Trilinos using the Cray programming environment.

Specifically, I have ParMETIS and Zoltan2 enabled. Zoltan2 requires ParMETIS >= 4.0.3.

The test for this builds a simple binary that includes parmetis.h and checks that the version is sufficient.

The problem seems to be that on Mutrino, the node used for compiling is not the same ARCH as the target. E.g., Cray's CC sets -xCORE-AVX2 for haswell, but the login nodes actually support AVX1 only.

The offending configure step is part of the Find ParMetis macro:

> -- Performing Test HAVE_PARMETIS_VERSION_4_0_3
> -- Run Output: 
> Please verify that both the operating system and the processor support Intel(R) MOVBE, F16C, FMA, BMI, LZCNT and AVX2 instructions.

In this case, the test that fails is:
cmake/TPLs/FindTPLParMETIS.cmake, which calls CHECK_C_SOURCE_RUNS.  The test executable is built using the cray wrappers (CC/cc) and will not run because the system does not support the instruction set.

```
FUNCTION(CHECK_PARMETIS_HAS_VERSION_4_0_3  VARNAME)
  SET(SOURCE
  "
  #include <stdio.h>
  #include <parmetis.h>
  int main()
  {
    if( PARMETIS_MAJOR_VERSION > 4 )
      return 0;
    if( PARMETIS_MAJOR_VERSION == 4 )
    if( PARMETIS_MINOR_VERSION > 0 )
      return 0;
    if( PARMETIS_MAJOR_VERSION == 4 )
    if( PARMETIS_MINOR_VERSION == 0 )
    if( PARMETIS_SUBMINOR_VERSION >= 3 )
      return 0;
    return 1;
  }
  "
  )
  SET(CMAKE_REQUIRED_INCLUDES ${TPL_ParMETIS_INCLUDE_DIRS})
  SET(CMAKE_REQUIRED_LIBRARIES ${TPL_ParMETIS_LIBRARIES})
  SET(CMAKE_REQUIRED_FLAGS ${CMAKE_EXE_LINKER_FLAGS})
  CHECK_C_SOURCE_RUNS("${SOURCE}" ${VARNAME})
ENDFUNCTION()
```

The output above is from instrumenting the CHECK_C_SOURCE_RUNS so I can see why it is failing. You can obtain the same error by copy the source from CMakeFiles/CMakeError.log and compiling it.

I am a bit confused as to why other configure checks do not fail, or is it that Trilinos' CMake avoids checks that require executing a built binary?

@trilinos/zoltan2 @bartlettroscoe

**Comment by bartlettroscoe** [comment]
Generally it is better not to test if a built executable runs due to cross-compiling situations like this.  Most of the rest of the TPLs just check that the files exist and at most makes sure that things link.

But note that you can just set the cache vars manually to avoid the attempt to run anything.  See:

* https://cmake.org/cmake/help/v3.0/manual/cmake-toolchains.7.html

**Comment by mhoemmen** [comment]
@trilinos/framework

**Comment by bmpersc** [comment]
@jjellio the solution to this and any other configure time test that needs to run an executable is to proved cmake the answer for the target machine in your toolchain file. In this case you will need to set “HAVE_PARMETIS_VERSION_4_0_3” to TRUE. I know that this has worked for at least one other person who ran into this issue when cross compiling.

Note that while I have anecdotal evidence that this will work for versions of Parmetis 4.0.2 and up, I would highly recommend making sure that your Parmetis is version 4.0.3 before just declaring it as true.

**Comment by jwillenbring** [comment]
@jjellio Any update on the status of this based on the comments?

**Comment by jjellio** [comment]
@jwillenbring I used @bmpersc 's suggestion, which works.

I think this is sufficient to make this compile time. (or it seems to work for me under Cray's PE)

Here is a pull request that resolves this on Cray's systems. I am not too sure how to test this further.  Perhaps @bartlettroscoe @bmpersc  can review it.
https://github.com/trilinos/Trilinos/pull/1096

**Comment by jjellio** [comment]
Closing this. Parmetis and Scotch both use compile time checks now. I'll reopen if I find other runtime checks that can shifted to compile time.
