### ISSUE TITLE
MueLu: Relatively large deviation between residual history in the experimental region tests on Geminga, Enigma, and Trappist

### ISSUE THREAD

**Issue by GrahamBenHarper** [trilinos/Trilinos#9377]
## Bug Report
@trilinos/muelu

### Description
While working on fixes for some of the experimental tests that are failing, I realized most of the failures in experimental tests across various machines are due to variations in residual history that can't really be accounted for by increasing the tolerance. This can make parsing CDash results difficult because these tests "behave correctly" in their current state, but they do not technically pass.

### Steps to Reproduce
Look at CDash for Geminga, Enigma, or Trappist :eyes: 

### Discussion
Currently, we have four experimental region tests that use the `packages/muelu/research/regionMG/test/structured/compare_residual_history.py` script to compare residual histories. Here's a brief discussion of possible approaches:
1. Add a whitelist for machine names by checking `os.getenv('HOSTNAME')` in the script. Pros: CDash turns green, and it's simple to do. Cons: If something is changed in build configurations that aren't tested on a whitelisted machine, we won't know it.
2. Check iteration count only. Pros: CDash turns green, and it's simple to do. Cons: We don't have the precision to tell if something has been changed and causes issues. 
3. Add gold files for each machine. Pros: CDash turns green, and we have very fine control to make sure the tests are passing and behaving as expected. Cons: We now have 3-4 gold files per gold file test, but at least they're small gold files...
4. ??? (add your own)

I think this is something that should definitely be addressed, but we should definitely have a discussion about it first.

**Comment by cgcgcg** [comment]
How about using a relative error tolerance for the two residual histories?

**Comment by GrahamBenHarper** [comment]
We do a sort of hybrid approach already. In compare_residual_history.py, it seems we use the absolute error specified in the CMakeLists.txt if `abs(goldResidual) < 1e-7`and a relative error of `1e-7` otherwise.

**Comment by jhux2** [comment]
@GrahamBenHarper Do you know why the test results vary by machine?  Is it random number seeding, order of operations, different algorithm, something else?

**Comment by GrahamBenHarper** [comment]
@lucbv has suggested it may be due to a difference in TPL versions (i.e. BLAS/LAPACK), but I haven't personally verified this

**Comment by GrahamBenHarper** [comment]
This could also be related to a couple unit tests, which seem to fail because it's comparing numbers that should match, but don't, but I'd have to read through the tests and figure out what these values mean.
https://testing.sandia.gov/cdash/test/79642889

**Comment by GrahamBenHarper** [comment]
related to #9376, which is just a temporary fix while we figure out what's going on
