### ISSUE TITLE
Tpetra: call to deprecated code not protected and should be replaced

### ISSUE THREAD

**Issue by bathmatt** [trilinos/Trilinos#9381]
## Bug Report
@trilinos/tpetra 

### Description

packages/tpetra/core/src/Tpetra_CrsGraph_def.hpp:6748

has a call to getLocalGraph and should be getLocalGraphHost most likely.  Fixing and sending to @cgcgcg

### Steps to Reproduce
1. SHA1:  [insert here]
1. Configure script:  [attach here]
1. Configure log:  [attach here]
1. Build log:  [attach here]
1. Input deck:  [attach here]
1. Do this.
1. Do that.
1. Shake fist angrily at computer.
1. Run log:  [attach here]

**Comment by cgcgcg** [comment]
Fixed in #9383
