### ISSUE TITLE
Teko:  Uses deprecated tpetra functions

### ISSUE THREAD

**Issue by bathmatt** [trilinos/Trilinos#9385]
## Bug Report
@trilinos/teko 

### Description
WE're working to get muelu and zoltan2 UVM free, the first step is to remove all deprecated tpetra calls from the package.  This appears to be completed for buth muelu and zoltan2 but they depend on teko. we will need to resolve this issue

### Steps to Reproduce
disable Tpetra deprecated code and compile teko

**Comment by bathmatt** [comment]
@trilinos/muelu this is required for UVM removal of MueLu

**Comment by jhux2** [comment]
@bathmatt How pervasive is this in Teko?

**Comment by cgcgcg** [comment]
Should be fixed by #9399 and tested by #9416. Guess we can close?

**Comment by lucbv** [comment]
Yeah, that looks good and the tests are enabled in the tests are enabled in the no uvm PR build!
