### ISSUE TITLE
tpetra: convertToBlockCrsMatrix appears to hold on to a host view of something

### ISSUE THREAD

**Issue by bathmatt** [trilinos/Trilinos#9398]
## Bug Report
@trilinos/tpetra
@kyungjoo-kim  this is your function
### Description
Not sure if this is a bug in tpetra or something odd in xpetra but I'll give it a shot here

I am removing UVM from MueLu and I ran into a problem with the balancing of host and device references when I use the convertToBlockCrsMatrix call.  I construct a Acrs matrix and then convert it to a block matrix and then wrap that in a Xpetra_CrsMatrix.  After that the count has gone from balanced in the host and device space to the new wrapped matrix having a host view checked out.  

Below is a code snippet, I use the    
```
   { auto fff = Acrs->getLocalMatrixDevice();} 
```
to make sure I don’t have more host views checked out than device.

```
    { auto fff = Acrs->getLocalMatrixDevice();}  // Acrs is balanced
    Ablock = Tpetra::convertToBlockCrsMatrix<SC,LO,GO,NO>(*Acrs,blocksize);
    { auto fff = Acrs->getLocalMatrixDevice();}  // Acrs is still balanced

    // Now wrap BlockCrs to Xpetra::Matrix
    RCP<Xpetra_CrsMatrix> Axt = rcp(new Xpetra_TpetraBlockCrsMatrix(Ablock));  
    A = rcp(new Xpetra_CrsMatrixWrap(Axt));
    { auto fff = A->getLocalMatrixDevice();}  // This call fails as there is one more host reference than device.
```

Is there any chance someone can look at the convertToBlockCrsMatrix code to see if there is anything in it which might be holding onto a reference?

Also, do anyone know of anyway to use my getLocalMatrixDevice trick on a block matrix?

Thanks

**Comment by kyungjoo-kim** [comment]
which view does report the reference counting exception ?

**Comment by bathmatt** [comment]
i might be wrong on this, give me a few minutes, I made a mistake on my check

**Comment by bathmatt** [comment]
I'm going to close this, and reopen if I can show what I thought I showed, sorry for the churn
