### ISSUE TITLE
NetCDF/HDF5 Load Issue with SEACAS/Ioss on Cray (with Intel 15.3 and 16.1)

### ISSUE THREAD

**Issue by nmhamster** [trilinos/Trilinos#94]
Have been encouraged to submit issues for tracking by @maherou.

We are seeing that NALU builds running with VOTD from Trilinos are failing to correctly load Exodus databases on Cray platforms when using the Intel 15.3 and 16.1 compiled modules. Not sure where the error is coming from yet but diagnostics are underway. @gsjaardema is involved in conversations.

**Comment by nmhamster** [comment]
First correctly executing builds of NALU have been run on Friday. So far the fix appears to be a custom rebuild of NetCDF using Cray's HDF5 libraries and a custom build of pNetCDF. We are observing correct behavior with NetCDF 4.4.0, Cray's HDF5 1.8.14 and pNetCDF 1.6.1 all set to compile with Intel 16.1 and Cray's MPI libraries. Thanks to @gsjaardema for the suggestion.

**Comment by gsjaardema** [comment]
@trilinos/seacas
