### ISSUE TITLE
Amesos2:  Compile with SuperLUDist

### ISSUE THREAD

**Issue by Adrian-Diaz** [trilinos/Trilinos#9403]
## Question
@trilinos/\Amesos2

Greetings,

I'm trying to use the SuperLUDist solver through the Amesos2 interface but I can't seem to get it to compile. I compiled Parmetis and SuperLUDist and set the paths in the cmake configure script using:

#!/bin/bash
cmake -DCMAKE_BUILD_TYPE=RELEASE \
-DTrilinos_MUST_FIND_ALL_TPL_LIBS=TRUE \
-DTPL_ENABLE_MPI=ON \
-DTPL_ENABLE_ParMETIS=ON \
-DTPL_ParMETIS_INCLUDE_DIRS="/mnt/c/ParMETIS/include;/mnt/c/ParMETIS/metis/include" \
-DTPL_ParMETIS_LIBRARIES="/mnt/c/ParMETIS/build/Linux-x86_64/libparmetis/libparmetis.a;/mnt/c/ParMETIS/build/Linux-x86_64/libmetis/libmetis.a" \
-DTPL_ENABLE_SuperLUDist=ON -DTPL_SuperLUDist_INCLUDE_DIRS=/mnt/c/superlu_dist/build/include/ \
-DTPL_SuperLUDist_LIBRARIES=/mnt/c/superlu_dist/build/lib/libsuperlu_dist.a -DTrilinos_ENABLE_Amesos2=ON \
-DTrilinos_ENABLE_ALL_PACKAGES=OFF -DTrilinos_ENABLE_ALL_OPTIONAL_PACKAGES=ON -DTrilinos_ENABLE_TESTS=ON \
-DCMAKE_INSTALL_PREFIX=/mnt/c/Users/Adrian\ Diaz/Documents/Github/ELEMENTS/Trilinos/build/ \
..

Then when I use "make -j4 install amesos2" I get the attached compiler output. Am I missing additional configure options or libraries?
[my_compile_output.txt](https://github.com/trilinos/Trilinos/files/6780372/my_compile_output.txt)

**Comment by Adrian-Diaz** [comment]
@srajama1

**Comment by srajama1** [comment]
It looks like the linking error is because of the threading library can't be found.

**Comment by nmhamster** [comment]
You should be able to add `-lgomp` to your link line to get this problem to go away. Other option is to recompile SuperLU-DIST without OpenMP enabled.

**Comment by Adrian-Diaz** [comment]
Adding -DTrilinos_ENABLE_OpenMP=ON \
and clearing my build directory to start from scratch (very important apparently) seems to have fixed it.
