### ISSUE TITLE
Decomp: Getting an error

### ISSUE THREAD

**Issue by bdas123** [trilinos/Trilinos#9418]
## Question
@trilinos/\<Decomp\>

I need to decomp a mesh called dummy on my native Mac, but when I use Trilinos, I get the following error message: 

Exodus Library Warning/Error: [ex_put_elem_cmap] in file 'dummy.g.nem'
	ERROR: failed to find index for variable "e_comm_ids" in file ID 65536

Exodus Library Warning/Error: [ex_put_node_cmap] in file 'dummy.g.nem'
	ERROR: failed to find index for variable "n_comm_ids" in file ID 65536
================================messages================================
	fatal: unable to output elemental communication map
	fatal: could not output Nemesis file
================================messages================================
	fatal: unable to output nodal communication map
	fatal: could not output Nemesis file

ERROR:******************************************************************
ERROR:
ERROR:******************************************************************
ERROR:
ERROR     During nem_slice execution. Check error output above and rerun
ERROR:
ERROR     During nem_slice execution. Check error output above and rerun
ERROR:
ERROR:******************************************************************
ERROR:******************************************************************

--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
Time to write Nemesis file: 0.0138255s

Exodus Library Warning/Error: [ex_put_node_cmap] in file 'dummy.g.nem'
	ERROR: failed to find index for variable "n_comm_ids" in file ID 65536
================================messages================================
	fatal: unable to output nodal communication map
	fatal: could not output Nemesis file
--------------------------------------------------------------------------
mpiexec detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[46476,1],3]
  Exit code:    1
--------------------------------------------------------------------------

**Comment by jhux2** [comment]
@bdas123 For any SEACAS-related questions, please ask @gsjaardema.  Because you're not member of Trilinos, you can't @ mention any of its teams.

**Comment by gsjaardema** [comment]
Is it possible to get a copy of the mesh.  It looks like it might not have any nodes or elements and decomp isn't handling that very well...

**Comment by jhux2** [comment]
@gsjaardema Does SEACAS have utilities that @bdas123 could run to check whether the mesh file `dummy` is OK?

**Comment by gsjaardema** [comment]
Try running `explore {file}` and then type `check`.    Can also try `io_info` and see if it can read and output information about the mesh.

**Comment by bdas123** [comment]
*** Explore Version 3.09 ***
                                Revised 20210331

                  A GENESIS/EXODUS DATABASE EXPLORATION PROGRAM

                          Run on 2021-07-15 at 14:12:47

               ==== Email gdsjaar@sandia.gov for support ====

                          +++ Copyright 2008 NTESS +++
                       +++ Under the terms of Contract +++
                      +++ DE-NA0003525 with NTESS, the +++
        +++ U.S. Government retains certain rights in this software. +++


                          *** Explore Version 3.09 ***
                                Revised 20210331

                  A GENESIS/EXODUS DATABASE EXPLORATION PROGRAM

                          Run on 2021-07-15 at 14:12:47

               ==== Email gdsjaar@sandia.gov for support ====

                          +++ Copyright 2008 NTESS +++
                       +++ Under the terms of Contract +++
                      +++ DE-NA0003525 with NTESS, the +++
        +++ U.S. Government retains certain rights in this software. +++


                          *** Explore Version 3.09 ***
                                Revised 20210331

                  A GENESIS/EXODUS DATABASE EXPLORATION PROGRAM

                          Run on 2021-07-15 at 14:12:47

               ==== Email gdsjaar@sandia.gov for support ====

                          +++ Copyright 2008 NTESS +++
                       +++ Under the terms of Contract +++
                      +++ DE-NA0003525 with NTESS, the +++
        +++ U.S. Government retains certain rights in this software. +++


                          *** Explore Version 3.09 ***
                                Revised 20210331

                  A GENESIS/EXODUS DATABASE EXPLORATION PROGRAM

                          Run on 2021-07-15 at 14:12:47

               ==== Email gdsjaar@sandia.gov for support ====

                          +++ Copyright 2008 NTESS +++
                       +++ Under the terms of Contract +++
                      +++ DE-NA0003525 with NTESS, the +++
        +++ U.S. Government retains certain rights in this software. +++


 NOTE: This version has the option to use global ids for both node and element ids.
       To see the mapping from local to global, use the commands:
           "LIST MAP" (element map), or "LIST NODEMAP" (node map)
       To disable the maps and use local ids, restart explore with "-nomap node|element|all"

       To enable the maps and use global ids, restart explore with "-map node|element|all"

       Notify gdsjaar@sandia.gov if bugs found

 Nodes and Elements using Local Ids

 Database:  dummy.g

 cubit(_2021/visuals/dummy_file/native_test/test_03/mesh/dummy.g): 07/15/2021: 09

 NOTE: This version has the option to use global ids for both node and element ids.
       To see the mapping from local to global, use the commands:
           "LIST MAP" (element map), or "LIST NODEMAP" (node map)
       To disable the maps and use local ids, restart explore with "-nomap node|element|all"

       To enable the maps and use global ids, restart explore with "-map node|element|all"

       Notify gdsjaar@sandia.gov if bugs found

 Nodes and Elements using Local Ids

 Database:  dummy.g

 cubit(_2021/visuals/dummy_file/native_test/test_03/mesh/dummy.g): 07/15/2021: 09

 Number of coordinates per node       =           3
 Number of nodes                      =          96
 Number of elements                   =          36
 Number of element blocks             =           2

 Number of nodal point sets           =           2
    Length of node list               =          96
    Length of distribution list       =          96
 Number of element side sets          =           0

 Number of coo
 NOTE: This version has the option to use global ids for both node and element ids.
       To see the mapping from local to global, use the commands:
           "LIST MAP" (element map), or "LIST NODEMAP" (node map)
       To disable the maps and use local ids, restart explore with "-nomap node|element|all"

       To enable the maps and use global ids, restart explore with "-map node|element|all"

       Notify gdsjaar@sandia.gov if bugs found

 Nodes and Elements using Local Ids

 Database:  dummy.g

 cubit(_2021/visuals/dummy_file/native_test/test_03/mesh/dummy.g): 07/15/2021: 09

 Number of coordinates per node       =           3
 Number of nodes                      =          96
 Number of elements                   =          36
 Number of element blocks             =           2

 Number of nodal point sets           =           2
    Length of node list               =          96
    Length of distribution list       =          96
 Number of element side sets          =           0

 Number of coo
 NOTE: This version has the option to use global ids for both node and element ids.
       To see the mapping from local to global, use the commands:
           "LIST MAP" (element map), or "LIST NODEMAP" (node map)
       To disable the maps and use local ids, restart explore with "-nomap node|element|all"

       To enable the maps and use global ids, restart explore with "-map node|element|all"

       Notify gdsjaar@sandia.gov if bugs found

 Nodes and Elements using Local Ids

 Number of coordinates per node       =           3
 Number of nodes                      =          96
 Number of elements                   =          36
 Number of element blocks             =           2

 Number of nodal point sets           =           2
    Length of node list               =          96
    Length of distribution list       =          96
 Number of element side sets          =           0

 Number of coordinate frames          =           0
rdinate frames          =           0
rdinate frames          =           0

 Database:  dummy.g

 cubit(_2021/visuals/dummy_file/native_test/test_03/mesh/dummy.g): 07/15/2021: 09

 Number of coordinates per node       =           3
 Number of nodes                      =          96
 Number of elements                   =          36
 Number of element blocks             =           2

 Number of nodal point sets           =           2
    Length of node list               =          96
    Length of distribution list       =          96
 Number of element side sets          =           0

 Number of coordinate frames          =           0

 *** Use "precision low|normal|high|#" to control" output precision
 *** Nodes and Elements using Local Ids

EXPLORE> 

 *** Use "precision low|normal|high|#" to control" output precision
 *** Nodes and Elements using Local Ids


 *** Use "precision low|normal|high|#" to control" output precision
EXPLORE>  *** Nodes and Elements using Local Ids


EXPLORE> 

 Explore used 0.02 seconds of CPU time

 *** Use "precision low|normal|high|#" to control" output precision

 Explore used 0.02 seconds of CPU time

 Explore used 0.02 seconds of CPU time
 *** Nodes and Elements using Local Ids

**Comment by bdas123** [comment]
EXPLORE> check

 *** INFO: Node global id range: 1 to 96
 *** INFO: Element global id range: 1 to 36

 Database check is completed

EXPLORE> io_info

 LIST/PRINT Options:
    TITLE     VARS      COORDINA  MAP       NMAP      NODEMAP   BLOCKS  
    MATERIAL  LINK      CONNECTI  ATTRIBUT  NSETS     NNODES    NFACTORS
    INVCON    SSETS     SELEMS    SFACES    SFACTORS  NAMES     TIMES   
    STEPS     GVARS     GLOBALS   GLOBNODE  GLOBELEM  NVARS     NODALS  
    EVARS     ELEMENTS  VERSION   COMMANDS  NSVARS    NODESETV  SSVARS  
    SIDESETV  FRAMES

**Comment by gsjaardema** [comment]
Explore is a serial program -- was it run on multiple mpi ranks?  

Also, `io_info` is a separate executable, not a subcommand of explore.  At command line `io_info {mymesh}`

**Comment by bdas123** [comment]
Yes, Explore was run on multiple ranks. I forgot to specify 1 processor. 

Here is the result for io_info. 

bdas$ mpirun -np 1 /Users/bdas/Scratch/Trilinos_2/Trilinos/bin/io_info dummy.g

                          *** Explore Version 3.09 ***
                                Revised 20210331

                  A GENESIS/EXODUS DATABASE EXPLORATION PROGRAM

                          Run on 2021-07-15 at 14:56:13

               ==== Email gdsjaar@sandia.gov for support ====

                          +++ Copyright 2008 NTESS +++
                       +++ Under the terms of Contract +++
                      +++ DE-NA0003525 with NTESS, the +++
        +++ U.S. Government retains certain rights in this software. +++


 NOTE: This version has the option to use global ids for both node and element ids.
       To see the mapping from local to global, use the commands:
           "LIST MAP" (element map), or "LIST NODEMAP" (node map)
       To disable the maps and use local ids, restart explore with "-nomap node|element|all"

       To enable the maps and use global ids, restart explore with "-map node|element|all"

       Notify gdsjaar@sandia.gov if bugs found

 Nodes and Elements using Local Ids

 Database:  dummy.g

 cubit(_2021/visuals/dummy_file/native_test/test_03/mesh/dummy.g): 07/15/2021: 09

 Number of coordinates per node       =           3
 Number of nodes                      =          96
 Number of elements                   =          36
 Number of element blocks             =           2

 Number of nodal point sets           =           2
    Length of node list               =          96
    Length of distribution list       =          96
 Number of element side sets          =           0

 Number of coordinate frames          =           0

 *** Use "precision low|normal|high|#" to control" output precision
 *** Nodes and Elements using Local Ids

**Comment by gsjaardema** [comment]
That is actuall explore output, even though your command shows io_info being run.  Anyway, it does look like the mesh has nodes, elements, and element blocks.  There should be no issue with decomp running on it, so I would probably need a copy of the mesh to debug any further...

**Comment by bdas123** [comment]
Can I email you a copy of the .g. file? 

Your email is in the Trilinos code.

**Comment by gsjaardema** [comment]
yes, you can email me the .g file.

**Comment by gsjaardema** [comment]
Can you also post the decomp command line you used.  Is it possible it wsa being run on multiple ranks?  If that is the case, then multiple ranks would be overwriting the same file which could cause an issue similar to what you showed.

**Comment by gsjaardema** [comment]
Resolution was that the decomp was being run via "mpirun" with no processor argument.  Some mpiruns will then run on the maximum number of cores/processors available on the system so decomp was being run multiple times simultaneously and  multiple instances were writting to the same file which corrupted it.  User used "mpirun -np 1 decomp ..." or just "decomp ..." and it ran correctly.

**Comment by bdas123** [comment]
Yup yup!
