### ISSUE TITLE
Amesos2:  SuperLUDist Parallel Usage

### ISSUE THREAD

**Issue by Adrian-Diaz** [trilinos/Trilinos#9420]
## Question
@trilinos/\amesos2

Greetings,

I've been testing the amesos2 interface to SuperLUDist with the attached matrix and simple solve example, I noticed that the solver exits with an unhandled error whenever the number of MPI ranks is not a power of 2. I was wondering if this is a restriction of SuperLUDist, the way I compiled it, or do I need to change a parameter to the amesos2 interface?

[Simple_Solve_Attach.txt](https://github.com/trilinos/Trilinos/files/6804746/Simple_Solve_Attach.txt)
[https://github.com/Adrian-Diaz/ELEMENTS/blob/Infrastructure/Compile_Example/A_matrix.zip](url)

**Comment by Adrian-Diaz** [comment]
@srajama1

**Comment by srajama1** [comment]
I don't see any problems in the way you are calling. When you say solver exits where does this happen? Symbolic, numeric, or solve? This could be one of many places, Trilinos, SuperLU or ParMetis. For example, I remember the parallel symbolic factorization would require power of two in SuperLU-Dist. I am not sure if you are setting it or what is the default. Older versions of Parmetis also has this requirement. We tried avoiding this assumption in Trilinos, but there could be an issue here as well.

**Comment by Adrian-Diaz** [comment]
The stack trace for the error says numeric factorization. Sometimes I just get the other error output.
[error2.txt](https://github.com/trilinos/Trilinos/files/6812850/error2.txt)
[error.txt](https://github.com/trilinos/Trilinos/files/6812834/error.txt)

**Comment by srajama1** [comment]
@ndellingwood @iyamazaki

**Comment by srajama1** [comment]
@ndellingwood volunteered to look into this.

**Comment by iyamazaki** [comment]
I am going to close this, but please let us know if you still have any issues. Thank you, @Adrian-Diaz.
