### ISSUE TITLE
Adelus:  Error message when executing make command

### ISSUE THREAD

**Issue by bdas123** [trilinos/Trilinos#9426]
I get the following error when I am making Trilinos on my Mac_OSX. 

[ 98%] Linking CXX shared library libzadelus.dylib
cd /Users/bdas/Scratch/Trilinos_2/Trilinos/build/packages/adelus/src && /usr/local/bin/cmake -E cmake_link_script CMakeFiles/zadelus.dir/link.txt --verbose=1
/usr/local/bin/mpicxx -Wno-unused -I/usr/local/include -stdlib=libc++   -g -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.14 -dynamiclib -Wl,-headerpad_max_install_names -compatibility_version 13.0.0 -current_version 13.1.0 -o libzadelus.13.1.dylib -install_name @rpath/libzadelus.13.dylib CMakeFiles/zadelus.dir/AdelusVersion.cpp.o CMakeFiles/zadelus.dir/Adelus_pcomm.cpp.o CMakeFiles/zadelus.dir/Adelus_distribute.cpp.o  -Wl,-rpath,/Users/bdas/Scratch/Trilinos_2/Trilinos/build/packages/kokkos-kernels/src -Wl,-rpath,/Users/bdas/Scratch/Trilinos_2/Trilinos/build/packages/kokkos/algorithms/src -Wl,-rpath,/Users/bdas/Scratch/Trilinos_2/Trilinos/build/packages/kokkos/containers/src -Wl,-rpath,/Users/bdas/Scratch/Trilinos_2/Trilinos/build/packages/kokkos/core/src ../../kokkos-kernels/src/libkokkoskernels.13.1.dylib ../../kokkos/algorithms/src/libkokkosalgorithms.13.1.dylib ../../kokkos/containers/src/libkokkoscontainers.13.1.dylib ../../kokkos/core/src/libkokkoscore.13.1.dylib /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/lib/libblas.tbd /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/lib/libdl.tbd /usr/lib/liblapack.dylib /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/lib/libblas.tbd 
Undefined symbols for architecture x86_64:
  "Adelus::nprocs_col", referenced from:
      Adelus::initcomm() in Adelus_pcomm.cpp.o
  "Adelus::nprocs_row", referenced from:
      Adelus::initcomm() in Adelus_pcomm.cpp.o
  "Adelus::me", referenced from:
      Adelus::initcomm() in Adelus_pcomm.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [packages/adelus/src/libzadelus.13.1.dylib] Error 1
make[1]: *** [packages/adelus/src/CMakeFiles/zadelus.dir/all] Error 2
make: *** [all] Error 2

**Comment by srajama1** [comment]
Can you post your configure script ? 
@vqd8a

**Comment by bdas123** [comment]
I ended up turning Adelus off since I don't think my program needs it. But if there is a way to successfully install it without turning it off, please let me know. 


#!/usr/bin/env bash
  
rm -rf CMakeFiles CMakeCache.txt

MPI_HOME=/usr/local
EXTRA_ARGS=$@

cmake -D CMAKE_INSTALL_PREFIX:PATH=/Users/bdas/Scratch/Trilinos_2/Trilinos/ \
  \
  -D MPI_BASE_DIR:PATH=$MPI_HOME \
  \
  -D CMAKE_BUILD_TYPE:STRING=Debug \
  -D CMAKE_Fortran_COMPILER:FILEPATH=/usr/local/bin/mpif90 \
  -D CMAKE_CXX_FLAGS:STRING="-Wno-unused -I/usr/local/include -stdlib=libc++" \
  -D BUILD_SHARED_LIBS:BOOL=ON \
  -D Trilinos_WARNINGS_AS_ERRORS_FLAGS:STRING="" \
  \
  -D Trilinos_ENABLE_ALL_PACKAGES:BOOL=OFF \
  -D Trilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=ON \
  -D Trilinos_ENABLE_ALL_FORWARD_DEP_PACKAGES:BOOL=ON \
  -D Trilinos_ENABLE_Adelus:BOOL=OFF \
  -D Trilinos_ENABLE_AztecOO:BOOL=ON \
  -D Trilinos_ENABLE_Belos:BOOL=ON \
  -D Trilinos_ENABLE_Epetra:BOOL=ON \
  -D Trilinos_ENABLE_EpetraExt:BOOL=ON \
  -D Trilinos_ENABLE_FEI:BOOL=OFF \
  -D Trilinos_ENABLE_Ifpack:BOOL=ON \
  -D Trilinos_ENABLE_Intrepid:BOOL=ON \
  -D Trilinos_ENABLE_Isorropia:BOOL=ON \
  -D Trilinos_ENABLE_MueLu:BOOL=OFF \
  -D Trilinos_ENABLE_NOX:BOOL=ON \
  -D Trilinos_ENABLE_Pamgen:BOOL=ON \
  -D Trilinos_ENABLE_Phalanx:BOOL=ON \
  -D Phalanx_EXPLICIT_TEMPLATE_INSTANTIATION:BOOL=ON \
  -D Trilinos_ENABLE_Piro:BOOL=ON \
  -D Trilinos_ENABLE_PyTrilinos:BOOL=OFF \
  -D Trilinos_ENABLE_Sacado:BOOL=ON \
  -D Trilinos_ENABLE_SEACAS:BOOL=ON \
  -D Trilinos_ENABLE_SECONDARY_STABLE_CODE:BOOL=ON \
  -D Trilinos_ENABLE_Shards:BOOL=ON \
  -D Trilinos_ENABLE_Sundance:BOOL=OFF \
  -D Trilinos_ENABLE_STK:BOOL=OFF \
  -D Trilinos_ENABLE_Teuchos:BOOL=ON \
  -D Trilinos_ENABLE_Zoltan:BOOL=ON \
  \
  -D Trilinos_ENABLE_EXAMPLES:BOOL=OFF \
  -D Trilinos_ENABLE_TESTS:BOOL=OFF \
  \
  -D TPL_ENABLE_MATLAB:BOOL=OFF \
  -D TPL_ENABLE_Matio:BOOL=OFF \
  -D TPL_ENABLE_QT:BOOL=OFF \
  -D TPL_ENABLE_Netcdf:BOOL=ON \
  -D Netcdf_INCLUDE_DIRS:PATH=$MPI_HOME/netcdf/include \
  -D Netcdf_LIBRARY_DIRS:PATH=$MPI_HOME/netcdf/lib \
  -D TPL_ENABLE_HDF5:BOOL=ON \
  -D HDF5_INCLUDE_DIRS:PATH=/usr/local/opt/hdf5-parallel/include \
  -D HDF5_LIBRARY_DIRS:PATH=/usr/local/opt/hdf5-parallel/lib \
  -D TPL_ENABLE_MPI:BOOL=ON \
  -D TPL_ENABLE_BLAS:BOOL=ON \
  -D TPL_ENABLE_LAPACK:BOOL=ON \
  -D TPL_LAPACK_LIBRARIES:STRING=/usr/lib/liblapack.dylib \
  -D TPL_ENABLE_Boost:BOOL=ON \
  -D TPL_Boost_INCLUDE_DIRS:PATH=$MPI_HOME/include/boost \
  \
  -D CMAKE_VERBOSE_MAKEFILE:BOOL=ON \
  -D Trilinos_VERBOSE_CONFIGURE:BOOL=ON \
  -D Trilinos_ASSERT_MISSING_PACKAGES=OFF \
  \
  $EXTRA_ARGS \
  ..

**Comment by vqd8a** [comment]
@bdas123 Sorry for my late response. Can you try turning Adelus on with ```-DBUILD_SHARED_LIBS:BOOL=OFF```?

**Comment by vqd8a** [comment]
@bdas123 If it is not working either, can you try adding ```-undefined dynamic_lookup``` to ```CMAKE_CXX_FLAGS``` to ignore undefined symbols when compiling libzadelus? Pls let me know if these work or not. Thanks.
