### ISSUE TITLE
Decomp: Understand an if statement

### ISSUE THREAD

**Issue by bdas123** [trilinos/Trilinos#9430]
What does the following if statement mean? This can be found in the decomp code. 

484 if [ $? -ne 0 ]
485 then
486     echo ${txtred}
487     echo "ERROR:******************************************************************"
488     echo "ERROR:"
489     echo "ERROR    During nem_spread execution. Check error output above and rerun"
490     echo "ERROR:"
491     echo "ERROR:******************************************************************"
492     echo ${txtrst}
493     exit 1

**Comment by gsjaardema** [comment]
$?       Expands to the exit status of the most recently executed foreground pipeline.

It checks whether the `nem_spread` execution on the preceding line succeeded or exited with an error.
