### ISSUE TITLE
ROL:  Tpetra Multivector Interface

### ISSUE THREAD

**Issue by Adrian-Diaz** [trilinos/Trilinos#9442]
## Question
@trilinos/\ROL

Greetings,

I saw on this powerpoint https://trilinos.github.io/pdfs/ROL.pdf that there is a Tpetra::MultiVector interface to the optimization functionality, however I couldn't find documentation for the name of the derived class or the source files for that interface. Does anyone know where this information resides?

**Comment by ccober6** [comment]
Tagging @trilinos/rol  Can you help here?  Thanks!

**Comment by Adrian-Diaz** [comment]
I believe I found what I was looking for in the adapter folder of the base directory for the package.

**Comment by dridzal** [comment]
@Adrian-Diaz : yes, that's the spot.  Let me know if you have questions.

**Comment by Adrian-Diaz** [comment]
Is there an example that uses the Multivector to run in parallel?

**Comment by dridzal** [comment]
Sure.  All examples that use Tpetra Multivector can be run in parallel, for instance

https://github.com/trilinos/Trilinos/blob/master/packages/rol/adapters/tpetra/test/vector/test_01.cpp

Whether you run in parallel or in serial is given by the default communicator.  These examples should work with `mpirun -np 1` or `mpirun -np 2`, etc.

**Comment by Adrian-Diaz** [comment]
So just to make sure, do I have to implement any parallel ops in the definition of the virtual functions for objectives and constraints? or are those handled by the caller after exit?

**Comment by dridzal** [comment]
If you use ROL wrappers for the Tpetra vectors exclusively, you shouldn't have to implement parallel operations.  They are handled through the Tpetra interface.  However, ROL/Tpetra can't help with any external parallel data structures you may already use.

**Comment by Adrian-Diaz** [comment]
Yea I saw those, what's still not clear is whether I have to reduce the objective function values, constraint values, jacobians etc. for the optimization algorithm after defining local values in the virtual function implementation or is that done by the algorithm after exit from the virtual function?

**Comment by dridzal** [comment]
There is no parallel decomposition at the level of the function interface.  You need to define the "full" optimization problem through the objective, constraints, etc.  Also, the distributed ROL/Tpetra vectors are defined for the full problem.  If you use these vectors, the reductions will happen in the Tpetra layer.  For example, if the objective function is the dot product of your optimization variables, `f(x) = x'.x`, then calling `x.dot(x)` in the objective value() will perform the reduction to a scalar for the *entire* optimization vector.

**Comment by Adrian-Diaz** [comment]
Is there a full manual somewhere, I couldn't find a lot of the details to guide the implementation and passing of constraints to the problem interfaces, such as OptimizationProblem, in the linked powerpoint. Things like is it possible to pass multiple constraints of the same type or does the constraint object always have to define a vector valued result in that case, and the details for inequality constraints. Looking at the class definitions themselves was light on the comments for inputs :(

**Comment by Adrian-Diaz** [comment]
Is there a flag or counter I can query to see if the design vector has changed between virtual function calls, like from one objective value to the value function of a constraint, I need to communicate any updates to ghost values before I can accurately evaluate the values or gradients. The brute force approach would just be to force it to update every time I suppose, or check the vector for any differences w.r.t to a stored vector, but it'd be neat if I could reduce that without having to assume how the optimization algorithm is evolving the vector between calls.

**Comment by dridzal** [comment]
@Adrian-Diaz  Please take a look at https://github.com/trilinos/Trilinos/blob/master/packages/rol/Version-2.0.md.  You should probably work with the 2.0 interface.  We don't have a manual yet.  ROL 2.0 introduces the concept of adding/removing constraints.  ROL 2.0 also includes an `update()` system for objectives and constraints, discussed in the linked document.  This lets you know when the algorithm changes iterates, and in which way.  By overloading the objective `update()` you can control your vector updates.

**Comment by Adrian-Diaz** [comment]
Thanks, I'll take a look at that.

**Comment by Adrian-Diaz** [comment]
I was also wondering what the child is for the ROL::Vector<Real> &c input to constraint value functions. Is that always the StdVector child?
