### ISSUE TITLE
Framework:  Location of new PR Driver toolchain

### ISSUE THREAD

**Issue by william76** [trilinos/Trilinos#9453]
@trilinos/framework 

Where are we thinking of as a place to put the new PR driver toolchain?

Ideas thus far are something like:
- `packages/framework`
- `CommonTools/<something>`
- others?

I don't necessarily have any preference myself, but I do think there is value in having this new toolchain live in some new place that is cleanly separated from legacy framework. Doing this should help us do a clean-up pass once the new system is fully deployed to remove the dead legacy codes to reduce confusion down the road.

@jwillenbring @prwolfe @ZUUL42 @e10harvey

**Comment by prwolfe** [comment]
I have been using commonTools/framework/pr_tools, but I am open to other suggestions.

**Comment by e10harvey** [comment]
Which team is responsible for maintaining the new tools?

**Comment by prwolfe** [comment]
I expect framework. We are responsible for the old ones after all and we will remove those old tools as soon as possible so there should not be extra work.

**Comment by e10harvey** [comment]
> I expect framework. We are responsible for the old ones after all and we will remove those old tools as soon as possible so there should not be extra work.

OK, I would argue the tools should reside in `packages/framework`, perhaps in another sub-directory within `packages/framework`.

**Comment by wadeburgess** [comment]
Migrated to Jira
