### ISSUE TITLE
checkin-test-sems.sh uses same -jN for ctest as for make

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#947]
@trilinos/framework 
checkin-test-sems.sh uses the same -jN argument for ctest as for make.  This is a bad idea, because many tests use both MPI processes and threads.

**Comment by aprokop** [comment]
I was always wondering: how does one properly control number of threads, number of mpi rinks into the context of parallel ctest without oversubscribing. Is there a proper solution, or just upper boundaries?

**Comment by bartlettroscoe** [comment]
Just tell TriBITS/CTest how many total cores the test uses with `NUM_TOTAL_CORES_USED`.  See:

* https://tribits.org/doc/TribitsDevelopersGuide.html#running-multiple-tests-at-the-same-time-tribits-add-test

This has been implemented and used in CASL VERA for many years.

If there are Trilinos tests that are multi-threaded and not setting `NUM_TOTAL_CORES_USED` then that is a separate issue but checkin-test.py (and therefore checkin-test-sems.sh) is doing exactly the right thing for properly defined test suites.

Can we close this Issue and open other issues for packages with tests that are not properly setting `NUM_TOTAL_CORES_USED`?

**Comment by mhoemmen** [comment]
@bartlettroscoe wrote:
> Can we close this Issue and open other issues for packages with tests that are not properly setting NUM_TOTAL_CORES_USED?

This issue is really about `make` vs. `ctest` behavior, not about NUM_TOTAL_CORES_USED.  The old check-in script distinguished between "options to pass to `make`" and "options to pass to `ctest`".  Many users found that useful.

A separate issue is that `NUM_TOTAL_CORES_USED` isn't always helpful.  OpenMP expands to fill the number of cores that are available.  We actually _want_ that behavior, because it ensures that threaded algorithms get tested over the largest possible thread counts.  However, that interferes with `ctest -j N`.  My preference is to let MPI and OpenMP occupy the machine, and use `ctest -j 1`, but do parallel builds.

**Comment by bartlettroscoe** [comment]
> This issue is really about `make` vs. `ctest` behavior, not about NUM_TOTAL_CORES_USED.  The old check-in script distinguished between "options to pass to `make`" and "options to pass to `ctest`".  Many users found that useful.

You can still set anything you want.  Just update your defaults in the file local-checkin-test-defaults.py (see documentation in checkin-test-sems.sh).  You can remove `-j4` and then set separate parallel levels for the build and for ctest as you did before using something like `--make-options=-j16 --ctest-options=-j1`.  See the new "note":

* https://github.com/trilinos/Trilinos/wiki/Policies-%7C-Safe-Checkin-Testing#local-checkin-test-defaults.py

> A separate issue is that `NUM_TOTAL_CORES_USED` isn't always helpful.  OpenMP expands to fill the number of cores that are available.  We actually _want_ that behavior, because it ensures that threaded algorithms get tested over the largest possible thread counts.  However, that interferes with `ctest -j N`.  My preference is to let MPI and OpenMP occupy the machine, and use `ctest -j 1`, but do parallel builds.

I don't think having individual pre-push automated tests consuming all of the cores on a machine is desirable behavior.  That can yield very different behavior on different machines and is a big waste of your local cores.  For example, one of these one-process tests on an 8-core machine would only use 8 threads by on a 128 core machine it would use 128 thread?  Why is that desirable?  Surely OpenMP can be told how many cores to use on a given machine.  How else could you run a 2 process MPI job if each process consumed all of the cores on the machine?  Also, may tests are not threaded so you are leaving a lot of cores idle when you run with `ctest -j1`. 

I think people can define NIGHTLY tests to do anything they want but for pre-push tests, we want more uniformity.

Note that if Trilinos does eventually implement and adopt an automated PR system then **all** pre-push testing will occur on one machine with a fixed number of cores.  That will remove all variability in the number of cores use by individual tests.  Therefore, we might as well do that right now with the usage of the checkin-test-sems.py script.

This is a very important topic so I think we need to discuss this at the next Trilinos Leaders Meeting.

**Comment by mhoemmen** [comment]
@bartlettroscoe wrote:
> You can still set anything you want. Just update your defaults in the file local-checkin-test-defaults.py (see documentation in checkin-test-sems.sh). You can remove `-j4` and then set separate parallel levels for the build and for ctest as you did before using something like `--make-options=-j16 --ctest-options=-j1`.

Neat! :-D  I'll do that then, and close this issue.  Thanks!
