### ISSUE TITLE
MueLu: Misleading indent in unit test

### ISSUE THREAD

**Issue by cgcgcg** [trilinos/Trilinos#9484]
## Bug Report
@trilinos/muelu 

### Description
There is a warning about this bit:
https://github.com/trilinos/Trilinos/blob/4c26aae13e88b747e1f604b099ebc7178e29f850/packages/muelu/test/unit_tests/MapTransferFactory.cpp#L706-L709
Not sure what the intended behavior is.

**Comment by mayrmt** [comment]
I'll look into it.

**Comment by mayrmt** [comment]
@cgcgcg See PR #9557 for a fix.
