### ISSUE TITLE
Install Error: undefined reference to symbol 'H5get_libversion'

### ISSUE THREAD

**Issue by NjJu1** [trilinos/Trilinos#9487]
## Question
I am now installing Trilinos with version required by charon-release-v2.1-06.may.2020. 
However, in compiling, I meet with the following error:
`
/usr/bin/ld: ../exodus/libexodus.a(ex_utils.c.o): undefined reference to symbol 'H5get_libversion'
/home/nj/software/hdf5.1.10/lib/libhdf5.so.103: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
packages/seacas/libraries/nemesis/CMakeFiles/SEACASNemesis_ne_ctest_wrap.dir/build.make:105: recipe for target 'packages/seacas/libraries/nemesis/SEACASNemesis_ne_ctest_wrap.exe' failed
make[2]: *** [packages/seacas/libraries/nemesis/SEACASNemesis_ne_ctest_wrap.exe] Error 1
CMakeFiles/Makefile2:12685: recipe for target 'packages/seacas/libraries/nemesis/CMakeFiles/SEACASNemesis_ne_ctest_wrap.dir/all' failed
make[1]: *** [packages/seacas/libraries/nemesis/CMakeFiles/SEACASNemesis_ne_ctest_wrap.dir/all] Error 2
Makefile:181: recipe for target 'all' failed
make: *** [all] Error 2
`

My cmake command follows Simple MPI instructions (enables most packages) but disable Matio.

One possible reason: When compliing, I run the following command in another shell (and another conda environment):
 `conda install -c anaconda libopenblas`
which will install hdf5.10.6 (but I already has installed hdf5 in my home directory).
I am not sure if it is the reason for this error... But when I test my original hdf5, it succeeds in tests. I am completely confused and what could I do now??

Many thanks!

(By the way, to install charon, it says the built of charon is closed related with Trilino; but it also views Trilino as a prerequisity. According to his manual, I clone a Trilino in charon's directory. Then I first try to install Trilino. Is this strategy right?)

Sorry, perhaps there are too many questions now. Thanks a lot.

**Comment by GrahamBenHarper** [comment]
@NjJu1 I'm not familiar with Charon, but if I recall correctly, I've had similar linking issues in the past depending on which packages I'm building. My band-aid for this kind of issue is that I always add the link flags again at the end in my cmake configure script:
```
 -D Trilinos_EXTRA_LINK_FLAGS:STRING="-lpnetcdf -lhdf5_hl -lhdf5 -lz"
```
(the two lhdf5 flags in the middle are probably the most relevant for you)

**Comment by rppawlo** [comment]
@glhenni

**Comment by NjJu1** [comment]
@glhenni Thanks very much for your reply. In fact, currently I am not following this. I could not remember well whether I have tried this strategy, but in the end I failed to install Trilinos. I would return to this when I need to use tcad-charon again. 
Thanks anyway!
