### ISSUE TITLE
Teuchos::LAPACK: GESVD incorrect results with Intel 19.1.3

### ISSUE THREAD

**Issue by shardest** [trilinos/Trilinos#9496]
## Bug Report
@trilinos/Teuchos

### Description
GESVD gives incorrect results when using lwork size returned by optimal workspace size query (lwork=-1). Don't know whether issue occurs in Teuchos wrapper or underlying LAPACK library. This is part of a Sierra build.

### Steps to Reproduce
1. Sierra is using a tarball of Trilinos described as "2021.01.16" - I'd have to ask someone else how to figure out what SHA it is since the git information is now missing from the tarball being used by spack. It is kind of a pain to find all the build and configuration information within spack in the Sierra build. Could someone please just try to reproduce it? If it doesn't work, I will dig up more details.
2. Compile and run this code: `  const int nrows = 401, ncols = 2;
  double A[nrows*ncols] = {0, 0.00484434477051342, 0.00968868826588141, 0.0145330292109588, 0.0193773663306013, 0.0242216983496654, 0.0290660239930089, 0.0339103419854916, 0.038754651051975, 0.043598949917323, 0.0484432373064024, 0.0532875119440827, 0.058131772555237, 0.0629760178647421, 0.0678202465974786, 0.0726644574783316, 0.077508649232191, 0.0823528205839515, 0.0871969702585135, 0.0920410969807828, 0.0968851994756713, 0.101729276468097, 0.106573326682986, 0.11141734884527, 0.116261341679887, 0.121105303911787, 0.125949234265922, 0.130793131467258, 0.135636994240767, 0.14048082131143, 0.145324611404238, 0.150168363244191, 0.155012075556301, 0.159855747065587, 0.164699376497083, 0.16954296257583, 0.174386504026883, 0.179229999575309, 0.184073447946185, 0.188916847864601, 0.193760198055661, 0.198603497244482, 0.203446744156193, 0.208289937515937, 0.213133076048873, 0.217976158480171, 0.222819183535021, 0.227662149938622, 0.232505056416193, 0.237347901692966, 0.242190684494191, 0.247033403545134, 0.251876057571077, 0.25671864529732, 0.261561165449179, 0.26640361675199, 0.271245997931106, 0.276088307711898, 0.280930544819755, 0.285772707980089, 0.290614795918326, 0.295456807359917, 0.30029874103033, 0.305140595655053, 0.309982369959597, 0.314824062669494, 0.319665672510295, 0.324507198207575, 0.329348638486932, 0.334189992073983, 0.339031257694371, 0.343872434073761, 0.348713519937842, 0.353554514012325, 0.358395415022947, 0.363236221695471, 0.36807693275568, 0.372917546929387, 0.377758062942427, 0.382598479520664, 0.387438795389985, 0.392279009276307, 0.39711911990557, 0.401959126003744, 0.406799026296825, 0.411638819510839, 0.416478504371837, 0.4213180796059, 0.42615754393914, 0.430996896097694, 0.435836134807732, 0.440675258795452, 0.445514266787083, 0.450353157508884, 0.455191929687147, 0.46003058204819, 0.464869113318369, 0.469707522224068, 0.474545807491703, 0.479383967847724, 0.484222002018614, 0.489059908730889, 0.493897686711097, 0.498735334685821, 0.50357285138168, 0.508410235525324, 0.513247485843442, 0.518084601062753, 0.522921579910017, 0.527758421112027, 0.532595123395612, 0.537431685487638, 0.542268106115009, 0.547104384004665, 0.551940517883583, 0.556776506478781, 0.561612348517312, 0.566448042726268, 0.571283587832782, 0.576118982564023, 0.580954225647203, 0.585789315809572, 0.59062425177842, 0.595459032281079, 0.60029365604492, 0.605128121797357, 0.609962428265846, 0.614796574177882, 0.619630558261005, 0.624464379242797, 0.629298035850882, 0.634131526812928, 0.638964850856647, 0.643798006709795, 0.648630993100171, 0.653463808755619, 0.658296452404028, 0.663128922773335, 0.667961218591517, 0.672793338586602, 0.677625281486662, 0.682457046019816, 0.687288630914231, 0.692120034898118, 0.69695125669974, 0.701782295047405, 0.70661314866947, 0.71144381629434, 0.716274296650472, 0.721104588466368, 0.725934690470582, 0.730764601391717, 0.735594319958429, 0.74042384489942, 0.745253174943448, 0.750082308819317, 0.754911245255888, 0.75973998298207, 0.764568520726826, 0.769396857219171, 0.774224991188174, 0.779052921362956, 0.783880646472693, 0.788708165246613, 0.793535476414001, 0.798362578704194, 0.803189470846586, 0.808016151570626, 0.812842619605816, 0.817668873681719, 0.822494912527949, 0.82732073487418, 0.832146339450142, 0.836971724985624, 0.841796890210468, 0.84662183385458, 0.851446554647919, 0.856271051320507, 0.861095322602422, 0.865919367223803, 0.870743183914847, 0.875566771405813, 0.880390128427019, 0.885213253708844, 0.890036145981728, 0.894858803976173, 0.899681226422741, 0.904503412052057, 0.90932535959481, 0.914147067781748, 0.918968535343685, 0.923789761011498, 0.928610743516126, 0.933431481588573, 0.938251973959909, 0.943072219361265, 0.94789221652384, 0.952711964178898, 0.957531461057767, 0.962350705891843, 0.967169697412587, 0.972243636117669, 0.977317305351905, 0.982390703709058, 0.987463829782964, 0.992536682167535, 0.997609259456761, 1.00268156024471, 1.00775358312551, 1.01282532669339, 1.01789678954265, 1.02296797026766, 1.02803886746286, 1.03310947972279, 1.03817980564207, 1.04324984381537, 1.04831959283747, 1.05338905130321, 1.05845821780752, 1.06352709094542, 1.068595669312, 1.07366395150242, 1.07873193611194, 1.08379962173591, 1.08886700696974, 1.09393409040893, 1.09900087064908, 1.10406734628584, 1.10913351591499, 1.11419937813236, 1.11926493153387, 1.12433017471555, 1.12939510627347, 1.13445972480384, 1.13952402890291, 1.14458801716705, 1.1496516881927, 1.1547150405764, 1.15977807291476, 1.1648407838045, 1.16990317184242, 1.1749652356254, 1.18002697375042, 1.18508838481456, 1.19014946741497, 1.1952102201489, 1.2002706416137, 1.20533073040679, 1.21039048512571, 1.21544990436807, 1.22050898673158, 1.22556773081406, 1.23062613521339, 1.23568419852757, 1.24074191935469, 1.24579929629293, 1.25085632794057, 1.25591301289599, 1.26096934975764, 1.2660253371241, 1.27108097359403, 1.27613625776619, 1.28119118823944, 1.28624576361273, 1.29129998248511, 1.29635384345575, 1.30140734512389, 1.30646048608888, 1.31151326495018, 1.31656568030734, 1.32161773076001, 1.32666941490794, 1.331720731351, 1.33677167868913, 1.3418222555224, 1.34687246045096, 1.3519222920751, 1.35697174899516, 1.36202082981164, 1.36706953312509, 1.37211785753622, 1.37716580164579, 1.38221336405471, 1.38726054336397, 1.39230733817468, 1.39735374708804, 1.40239976870538, 1.40744540162812, 1.41249064445779, 1.41753549579603, 1.4225799542446, 1.42762401840534, 1.43266768688023, 1.43771095827135, 1.44275383118088, 1.44779630421112, 1.45283837596448, 1.45788004504347, 1.46292131005074, 1.46796216958902, 1.47300262226116, 1.47804266667014, 1.48308230141904, 1.48812152511106, 1.49316033634949, 1.49819873373777, 1.50323671587944, 1.50827428137814, 1.51331142883765, 1.51834815686185, 1.52338446405474, 1.52842034902043, 1.53345581036317, 1.53849084668731, 1.54352545659731, 1.54855963869776, 1.55359339159337, 1.55862671388896, 1.56365960418949, 1.5686920611, 1.57372408322569, 1.57875566917187, 1.58378681754396, 1.5888175269475, 1.59384779598816, 1.59887762327174, 1.60390700740415, 1.60893594699143, 1.61396444063973, 1.61899248695534, 1.62402008454467, 1.62904723201424, 1.63407392797071, 1.63910017102087, 1.64412595977162, 1.64915129282999, 1.65417616880315, 1.65920058629837, 1.66422454392308, 1.6692480402848, 1.67427107399122, 1.67929364365012, 1.68431574786943, 1.68933738525721, 1.69435855442163, 1.69937925397102, 1.70439948251381, 1.70941923865858, 1.71443852101403, 1.719457328189, 1.72447565879246, 1.7294935114335, 1.73451088472137, 1.73952777726542, 1.74454418767515, 1.7495601145602, 1.75457555653032, 1.75959051219543, 1.76460498016556, 1.76961895905088, 1.77463244746168, 1.77964544400843, 1.78465794730168, 1.78966995595217, 1.79468146857074, 1.79969248376837, 1.80470300015621, 1.80971301634551, 1.81472253094767, 1.81973154257425, 1.82474004983692, 1.82974805134751, 1.83475554571797, 1.83976253156042, 1.8447690074871, 1.84977497211039, 1.85478042404281, 1.85978536189705, 1.86478978428591, 1.86979368982234, 1.87479707711945, 1.87979994479047, 1.88480229144879, 1.88980411570794, 1.8948054161816, 1.89980619148359, 1.90480644022786, 1.90980616102854, 1.91480535249988, 1.91980401325628, 1.9248021419123, 1.92979973708264, 1.93479679738214, 1.9397933214258, 1.94478930782876, 1.94978475520631, 1.95477966217391, 1.95977402734713, 1.96476784934172, 1.96976112677358, 1.97475385825874, 
                           0, 0.00573936257960948, 0.0114787237942501, 0.0172180822789533, 0.0229574366687511, 0.0286967855986767, 0.0344361277037643, 0.0401754616190501, 0.0459147859795719, 0.0516540994203699, 0.057393400576487, 0.0631326880829689, 0.0688719605748645, 0.0746112166872264, 0.0803504550551111, 0.0860896743135791, 0.0918288730976958, 0.0975680500425312, 0.103307203783161, 0.109046332954665, 0.11478543619213, 0.12052451213065, 0.126263559405323, 0.132002576651256, 0.137741562503561, 0.14348051559736, 0.149219434567781, 0.154958318049961, 0.160697164679045, 0.166435973090186, 0.172174741918548, 0.177913469799302, 0.183652155367632, 0.189390797258728, 0.195129394107794, 0.200867944550043, 0.206606447220699, 0.212344900754997, 0.218083303788185, 0.223821654955523, 0.229559952892282, 0.235298196233746, 0.241036383615212, 0.246774513671992, 0.25251258503941, 0.258250596352803, 0.263988546247524, 0.26972643335894, 0.275464256322434, 0.281202013773402, 0.286939704347258, 0.29267732667943, 0.298414879405363, 0.304152361160519, 0.309889770580376, 0.31562710630043, 0.321364366956193, 0.327101551183198, 0.332838657616993, 0.338575684893146, 0.344312631647243, 0.350049496514891, 0.355786278131713, 0.361522975133356, 0.367259586155484, 0.372996109833782, 0.378732544803958, 0.384468889701738, 0.390205143162871, 0.395941303823128, 0.401677370318301, 0.407413341284206, 0.413149215356679, 0.418884991171583, 0.424620667364801, 0.43035624257224, 0.436091715429833, 0.441827084573536, 0.44756234863933, 0.453297506263221, 0.459032556081239, 0.464767496729442, 0.470502326843913, 0.476237045060759, 0.481971650016118, 0.487706140346152, 0.493440514687051, 0.499174771675031, 0.504908909946339, 0.510642928137248, 0.51637682488406, 0.522110598823106, 0.527844248590746, 0.533577772823371, 0.5393111701574, 0.545044439229282, 0.550777578675499, 0.55651058713256, 0.562243463237009, 0.56797620562542, 0.573708812934396, 0.579441283800578, 0.585173616860634, 0.590905810751268, 0.596637864109215, 0.602369775571245, 0.608101543774162, 0.613833167354802, 0.619564644950037, 0.625295975196774, 0.631027156731953, 0.636758188192552, 0.642489068215584, 0.648219795438096, 0.653950368497173, 0.659680786029938, 0.665411046673548, 0.6711411490652, 0.676871091842126, 0.682600873641598, 0.688330493100926, 0.694059948857458, 0.699789239548581, 0.705518363811723, 0.711247320284348, 0.716976107603963, 0.722704724408114, 0.728433169334388, 0.734161441020412, 0.739889538103855, 0.745617459222428, 0.751345203013882, 0.757072768116013, 0.762800153166656, 0.768527356803692, 0.774254377665044, 0.779981214388678, 0.785707865612603, 0.791434329974874, 0.797160606113591, 0.802886692666895, 0.808612588272976, 0.814338291570067, 0.820063801196449, 0.825789115790447, 0.831514233990433, 0.837239154434826, 0.842963875762091, 0.848688396610742, 0.85441271561934, 0.860136831426494, 0.86586074267086, 0.871584447991145, 0.877307946026104, 0.88303123541454, 0.888754314795307, 0.89447718280731, 0.900199838089501, 0.905922279280886, 0.91164450502052, 0.91736651394751, 0.923088304701014, 0.928809875920241, 0.934531226244456, 0.940252354312972, 0.945973258765156, 0.951693938240432, 0.957414391378271, 0.963134616818204, 0.968854613199811, 0.974574379162731, 0.980293913346655, 0.98601321439133, 0.991732280936557, 0.997451111622196, 1.00316970508816, 1.00888805997442, 1.014606174921, 1.02032404856799, 1.02604167955553, 1.03175906652382, 1.03747620811311, 1.04319310296373, 1.04890974971604, 1.05462614701048, 1.06034229348755, 1.06605818778779, 1.07177382855181, 1.0774892144203, 1.08320434403399, 1.08891921603366, 1.09463382906017, 1.10034818175445, 1.10606227275746, 1.11177610071026, 1.11748966425394, 1.12320296202968, 1.1289159926787, 1.13462875484229, 1.14034124716182, 1.1460534682787, 1.44825077880146, 1.75042986677358, 2.05258693004019, 2.35471816672357, 2.65681977527094, 2.95888795450232, 3.26091890365837, 3.56290882244816, 3.86485391109706, 4.1667503703945, 4.46859440174178, 4.77038220719987, 5.07210998953722, 5.37377395227749, 5.67537029974738, 5.97689523712432, 6.27834497048428, 6.57971570684947, 6.88100365423609, 7.182205021702, 7.48331601939449, 7.78433285859788, 8.08525175178126, 8.38606891264613, 8.686780556174, 8.98738289867408, 9.28787215783083, 9.58824455275159, 9.88849630401414, 10.1886236337142, 10.4886227655132, 10.7884899246854, 11.0882213381656, 11.3878132345968, 11.6872618443774, 11.9865633997086, 12.2857141346419, 12.5847102851267, 12.8835480890572, 13.1822237863201, 13.4807336188419, 13.7790738306359, 14.0772406678498, 14.3752303788126, 14.6730392140821, 14.9706634264921, 15.2680992711991, 15.56534300573, 15.8623908900287, 16.1592391865036, 16.4558841600742, 16.7523220782184, 17.0485492110193, 17.3445618312124, 17.6403562142321, 17.9359286382587, 18.2312753842655, 18.5263927360652, 18.821276980357, 19.1159244067731, 19.4103313079253, 19.7044939794521, 19.9984087200647, 20.2920718315942, 20.5854796190374, 20.8786283906041, 21.171514457763, 21.4641341352882, 21.7564837413057, 22.0485595973397, 22.3403580283587, 22.6318753628221, 22.9231079327261, 23.2140520736498, 23.5047041248017, 23.7950604290652, 24.0851173330453, 24.3748711871138, 24.6643183454558, 24.9534551661155, 25.2422780110417, 25.5307832461338, 25.8189672412878, 26.1068263704413, 26.3943570116197, 26.6815555469816, 26.9684183628643, 27.2549418498292, 27.5411224027074, 27.8269564206448, 28.1124403071478, 28.397570470128, 28.682343321948, 28.966755279466, 29.2508027640814, 29.5344822017794, 29.8177900231762, 30.1007226635637, 30.3832765629546, 30.6654481661272, 30.9472339226699, 31.228630287026, 31.5096337185384, 31.7902406814939, 32.0704476451679, 32.350251083869, 32.6296474769827, 32.9086333090166, 33.1872050696438, 33.4653592537477, 33.7430923614657, 34.0204008982333, 34.2972813748283, 34.5737303074145, 34.8497442175855, 35.1253196324088, 35.4004530844688, 35.6751411119114, 35.9493802584867, 36.2231670735928, 36.4964981123195, 36.7693699354911, 37.0417791097101, 37.3137222074004, 37.5851958068499, 37.8561964922544, 38.1267208537598, 38.3967654875055, 38.6663269956668, 38.9354019864982, 39.2039870743757, 39.4720788798393, 39.739674029636, 40.0067691567618, 40.2733609005041, 40.5394459064842, 40.8050208266996, 41.0700823195655, 41.3346270499577, 41.5986516892539, 41.8621529153758, 42.1251274128312, 42.3875718727551, 42.6494829929519, 42.9108574779366, 43.1716920389765, 43.4319833941322, 43.6917282682996, 43.9509233932504, 44.2095655076735, 44.467651357216, 44.7251776945243, 44.9821412792847, 45.2385388782646, 45.4943672653525, 45.7496232215991, 46.004303535258, 46.2584050018253, 46.5119244240808, 46.7648586121277, 47.0172043834328, 47.2689585628668, 47.5201179827439, 47.7706794828621, 48.0206399105424, 48.269996120669, 48.5187449757285, 48.7668833458495, 49.0144081088421, 49.261316150237, 49.5076043633249, 49.7532696491953, 49.9983089167757, 50.2427190828707, 50.4864970722, 50.7296398174382, 50.9721442592524, 51.2140073463414, 51.4552260354738, 51.6957972915261, 51.9357180875212, 52.1749854046666, 52.4135962323919, 52.651547568387, 52.8888364186398, 53.1254597974741, 53.3614147275867, 53.5966982400854, 53.8313073745257, 54.0652391789488, 54.2984907099183, 54.5310590325571, 54.7629412205848, 54.994134356354, 55.2246355308876, 55.4544418439147, 55.6835504039077, 55.9119583281185, 56.1396627426145, 56.3666607823151};
  double Svals[ncols];
  const int lwork = 808; // works if lwork=801
  double work[lwork];
  int info;

  Teuchos::LAPACK<int,double> lapack;
  lapack.GESVD('O', 'N', nrows, ncols, A, nrows, Svals, nullptr, nrows, nullptr, nrows, work, lwork, work, &info);

  for(int i=0;i<nrows;i++) {
    for(int j=0;j<ncols;j++) {
      std::cout << A[i+nrows*j] << " ";
    }
    std::cout << std::endl;
  }
`
3. Output is mostly zeros (or very close to it) with Intel 19.1.3. With every other compiler we have tried (Intel 19.0.3, various gcc, clang, etc.), it produces normal non-zero output.

**Comment by jwillenbring** [comment]
CC: @DavidMDay

**Comment by DavidMDay** [comment]
I noticed that A is being initialized to 803 values, but is only allocated at size 802.  Please clear up this ambiguity.

**Comment by shardest** [comment]
@DavidMDay - I pasted the numbers into Matlab, and the resulting variable has 802 entries. Are you sure you counted correctly?

**Comment by DavidMDay** [comment]
You are right.  There are 802 entries.  The regex that I used added a blank line between the two columns.

**Comment by shardest** [comment]
Brian Stevens did some experiments. Perhaps unsurprisingly, we found that the incorrect behavior is exactly the same when calling dgesvd directly rather through the Teuchos wrapper.

**Comment by shardest** [comment]
We've now found that it depends on the version of MKL - not the compiler.

Nate Crane found this page:
https://community.intel.com/t5/Intel-oneAPI-Math-Kernel-Library/SGESVD-produces-weird-results-for-Intel-MKL-2020-when-using/m-p/1236027

Looks like the solution is to avoid problematic versions of MKL. So far, we have found:

19.0.3.199  : passed
19.0.4.277 : passed
19.0.5.281 : passed
19.1.2.254: failed
20.0.1.217 : failed
20.0.2.254 : failed
21.3.0 : passed
