### ISSUE TITLE
Zoltan2:  TpetraCrsColorer with noncontiguous maps

### ISSUE THREAD

**Issue by kliegeois** [trilinos/Trilinos#9500]
## Bug Report
@trilinos/zoltan2 @mperego 
### Description
A bug has been observed in Albany when reconstructing a Hessian matrix using the `Zoltan2::TpetraCrsColorer` when the maps of the graph of the matrix are not contiguous (i.e. the global IDs included in the maps are not contiguous).

For the observed occurrences, the `Zoltan2::TpetraCrsColorer` was set to be used with the symmetry option and the reconstructed matrix was not symmetrical. Most of the entries were fine (more than 90% of the entries were correct) but few rows related to the last global IDs were not correct.

As an example, the following figure illustrates the correct Hessian of a response in Albany:

![Figure_1](https://user-images.githubusercontent.com/15634348/127350033-bf03292a-f7e4-4c8f-9d9b-f3928d80ffed.png)

And this second figure illustrates the difference between the correct Hessian and the Hessian computed using `Zoltan2::TpetraCrsColorer` with the symmetry option set to true and noncontiguous maps (the entries of the matrix have been reordered for comparison purpose with the contiguous case):

![Figure_5](https://user-images.githubusercontent.com/15634348/127350083-abf5eba4-617a-4a09-aa26-899e85976217.png)

The problem has been overcome in Albany using contiguous maps but it will be great if the `Zoltan2::TpetraCrsColorer` can support the noncontiguous cases.

**Comment by kddevin** [comment]
Appears to be a bug in Zoltan2's TpetraCrsColorer's symmetrization of the matrix before coloring.  I'm on it.

**Comment by kliegeois** [comment]
Thanks a lot!

**Comment by mperego** [comment]
Thanks @kddevin !

**Comment by kddevin** [comment]
@kliegeois  Does #9982 fix the problem in Albany?  If so, please feel free to close this issue.

**Comment by mperego** [comment]
@kddevin The test in Albany still fails for non contiguous ids. The matrix computed with coloring is not symmetric. Not sure if the issue is in Zoltan2, I would need to dig into it. @kliegeois is on vacation.

**Comment by kddevin** [comment]
@mperego Thanks; I'll take another look.

**Comment by kddevin** [comment]
@mperego can you point me to the Albany code that is calling the colorer?  I'd like to see the calling sequence.  Thanks.

**Comment by mperego** [comment]
@kddevin here is the code calling the coloring
https://github.com/sandialabs/Albany/blob/master/src/Albany_Application.cpp#L2535-L2611

**Comment by kliegeois** [comment]
I confirm that the issue is still there.
The last columns/rows are still non symmetrical while using a non-contiguous map.

This figure is the difference between the Hessian and its transpose computed using a non-contiguous map:

![diff-1](https://user-images.githubusercontent.com/15634348/148300994-ae759b36-575c-4c96-9d29-34a73983aa91.png)

@kddevin would there be some useful information that I can provide?

**Comment by kliegeois** [comment]
@kddevin @egboman 
I am still investigating the Albany side but I have a small question.
When using the symmetry option of Zoltan, does Zoltan guarantee that the reconstructed matrix is symmetric even if the used operator might not be?

To rephrase that, if `V` is the seed matrix and `H` an operator that might not be symmetrical, given `H(V)` do Zoltan compute `H` based on something such as `H = H(V) + H(V)^T`? In other words, what does the symmetry option imply?

**Comment by kddevin** [comment]
Hi, @kliegeois 
All of the symmetry options have to do with the input graph to be colored.
Users can tell us that the graph is "symmetric", in which case we use it as-is in coloring.  Other keywords (e.g., matrixType = Jacobian) also indicate non-symmetry of the input graph.
Users can also request that we symmetrize a graph, and can specify which symmetrization to use.
The symmetrize options do not get applied to the reconstructed matrix; how would you want them to be applied?

**Comment by kliegeois** [comment]
@kddevin thanks for the comment!

I think that the issue can be closed then.
I tried what we discussed today, to replace the evaluation of `H(v_i)` by:
```
    auto hv_view = HV->getLocalView<Tpetra_MultiVector::node_type::device_type>();
    auto v_view = V->getLocalView<Tpetra_MultiVector::node_type::device_type>();

    // Hv_i = (i+1) * v_i;
    for (int i = 0; i < hv_view.extent(0); ++i)
      for (int j = 0; j < hv_view.extent(1); ++j)
        hv_view(i,j) = v_view(i,j) * (i+1);
```
and the result is now symmetrical with the non-contiguous map.
I tried something like this earlier last year before the creation of the issue and that was not the case.
This implies that there is no more issue on the Zoltan side regarding this issue and that I have to continue to investigate the Albany side.

Thanks again for your time and help!

**Comment by kddevin** [comment]
Thank you, @kliegeois

**Comment by kliegeois** [comment]
Everything is good on Albany side now, thanks again!
