### ISSUE TITLE
Without Tpetra::CrsGraph's DynamicProfile (deprecated), best way to initialize graph

### ISSUE THREAD

**Issue by davoodansari** [trilinos/Trilinos#9507]
## Question
@trilinos/\<PackageName\>

I am aware that **DynamicProfile** has been deprecated for a little while now. That said, there are situations that having an estimated upper bound for the number of columns per row will entail a costly sweep of element DoF that might better be accompanied with the insertion of graph nodes; This has certain impact on the FEA pre-assembly process especially when higher order adaptive FE are involved. What I am missing here is

1. Is there any discussion on the philosophy that lead to the deprecation of **DynamicProfile**?
2. Is there an alternative approach to achive similar effects as that of **DynamicProfile**? 
3. What are the recommendation WRT pre-allocation of FE grpahs?

Any advice is highly appreciated
Thanks
Davood

**Comment by cgcgcg** [comment]
@trilinos/tpetra

**Comment by csiefer2** [comment]
DynamicProfile would never work on a GPU (or any other compute object that can't do in-kernel dynamic memory allocation quickly) was the main problem.

An easy to use device graph assembly layer is on our to-do list.    You can do this yourself right now (and all our apps do) using Kokkos::UnorderedMap, or something like that, but we'd like to develop a best-practice way to do that.
