### ISSUE TITLE
Belos and Amesos:  Error while installing and testing on Windows 10 using MSVS

### ISSUE THREAD

**Issue by jhimbele3** [trilinos/Trilinos#9512]
## Install Trilinos Header Files
@trilinos/<Belos>

I've been trying to install the Belos and Amesos solvers on Windows 10, but I always run into the same compiling error.

I first compiled with the following options, which successfully created the build files:
```
cmake -DTPL_ENABLE_MPI=OFF \
-DTPL_BLAS_LIBRARIES=C:/lapack/lib/libblas.lib \
-DTPL_LAPACK_LIBRARIES=C:/lapack/lib/liblapack.lib \
-DTrilinos_ENABLE_COMPLEX_DOUBLE=ON \
-DTrilinos_ENABLE_ALL_PACKAGES=OFF \
-DTrilinos_ENABLE_ALL_OPTIONAL_PACKAGES=ON \
-DTrilinos_ENABLE_Belos=ON \
-DTrilinos_ENABLE_Amesos=ON \
-DTrilinos_ENABLE_TESTS=OFF \
-DCMAKE_INSTALL_PREFIX=C:/Trilinos/build \
..\Trilinos-master
```
I then run the following to install:
```
cmake -P cmake_install.cmake
```
However, this always produces the following Cmake compiling error:
```
CMake Error at packages/kokkos/core/src/cmake_install.cmake:49 (file):
  file INSTALL cannot find
  "C:/Trilinos/build/packages/kokkos/core/src/Release/kokkoscore.lib": File
  exists.
Call Stack (most recent call first):
  packages/kokkos/core/cmake_install.cmake:37 (include)
  packages/kokkos/cmake_install.cmake:37 (include)
  cmake_install.cmake:45 (include)
```

As described in the above error message, I indeed confirmed that there was no file directory `"C:/Trilinos/build/packages/kokkos/core/src/Release"`. I therefore played with the file `cmake_install.cmake` in the build directory `"C:/Trilinos/build"` and I discovered that I was able to install all the Trilinos header files by changing the line 15 in `cmake_install.cmake` from **Release** to **Debug**:
```
set(CMAKE_INSTALL_CONFIG_NAME "Debug")
```

## Testing Installed Trilinos Header Files
Now, I tried to test the installed Trilinos header files with following options in new directory `C:/Trilinos/buildTest/`:
```
cmake -DTPL_ENABLE_MPI=OFF \
-DTPL_BLAS_LIBRARIES=C:/lapack/lib/libblas.lib \
-DTPL_LAPACK_LIBRARIES=C:/lapack/lib/liblapack.lib \
-DTrilinos_ENABLE_COMPLEX_DOUBLE=ON \
-DTrilinos_ENABLE_ALL_PACKAGES=OFF \
-DTrilinos_ENABLE_ALL_OPTIONAL_PACKAGES=ON \
-DTrilinos_ENABLE_Belos=ON \
-DTrilinos_ENABLE_Amesos=ON \
-DTrilinos_ENABLE_TESTS=ON \
-DTrilinos_ENABLE_INSTALLATION_TESTING=ON \
-DTrilinos_INSTALLATION_DIR=C:/Trilinos/biuld \
..\Trilinos-master
```
However, this always produces the same following Cmake compiling error claiming KokkosCore was not installed:
```
CMake Error at cmake/tribits/core/package_arch/TribitsLibraryMacros.cmake:975 (MESSAGE):
  The package KokkosCore was not installed with Trilinos! Please disable
  package KokkosCore or install it.
Call Stack (most recent call first):
  packages/kokkos/cmake/kokkos_tribits.cmake:496 (TRIBITS_ADD_LIBRARY)
  packages/kokkos/core/src/CMakeLists.txt:68 (KOKKOS_ADD_LIBRARY)
```
As suggested in the above error message, I disabled KokkosCore and TeuchosCore, but this caused another library dependency error to Amesos solver.

## Question
Here are my questions and I would appreciate for your advice!

1. Is it fine to change the `CMAKE_INSTALL_CONFIG_NAME` at line 15 in `cmake_install.cmake` from **Release** to **Debug** so that it successfully creates the Trilinos header files?
2. If the 1st question is true, how can I test the installed Trilinos files in the build directory? If the 1st question is wrong, what do I need to do to create `kokkoscore.lib` and `teuchoscore.lib`?

## Attached file
[cmake_install.txt](https://github.com/trilinos/Trilinos/files/6912845/cmake_install.txt)
[CMakeOutput.log](https://github.com/trilinos/Trilinos/files/6912848/CMakeOutput.log)
[CMakeError.log](https://github.com/trilinos/Trilinos/files/6912849/CMakeError.log)

## Version Info
Microsoft Visual Studio 2019 on Windows 10
Trilinos 12.12
Cmake 3.20.3

Please let me know if you need additional information and I appreciate any advice and comments.

Thank you,
Johnny

**Comment by cgcgcg** [comment]
@jhimbele3 Not quite sure what is happening here, but I noticed that you are calling `cmake -P cmake_install.cmake`. Could you try calling `make install` instead, and see if that makes a difference?

**Comment by jhimbele3** [comment]
@cgcgcg Thanks for the prompt reply. I tried calling `make install` before on both Windows **command prompt** and **developer command prompt for VS2019** and it always gives the following error.

```
make: *** No rule to make target 'install'.  Stop.
```
I thus ended up using `cmake -P cmake_install.cmake` instead.

FYI, I'm trying to build on Windows 10 using the Microsoft Visual Studio 2019, so it sets `Trilinos_ENABLE_Fortran=OFF` by default; while it uses ` C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30037/bin/Hostx64/x64/cl.exe` as CXX and C compiler.

I wonder whether the use of MSVS 2019 default compilers prevents creating `install` file and instead it creates `cmake_install.cmake`. If so, I already have `mingw` installed on my Windows, so do you think I should try using `gcc.exe`, `g++.exe` and `gfortran.exe` instead of `cl.exe`?

**Comment by cgcgcg** [comment]
That's weird. Can you post the console output of the CMake invocation? Does calling plain `make` do something? Unfortunately, I can't really help you with Windows issues.

**Comment by jhimbele3** [comment]
@cgcgcg , Thanks again!

[ConsoleOutput.txt](https://github.com/trilinos/Trilinos/files/6913200/ConsoleOutput.txt)

Attached is the console output of the following options:
```
cmake -DTPL_ENABLE_MPI=OFF \
-DTPL_BLAS_LIBRARIES=C:/lapack/lib/libblas.lib \
-DTPL_LAPACK_LIBRARIES=C:/lapack/lib/liblapack.lib \
-DTrilinos_ENABLE_COMPLEX_DOUBLE=ON \
-DTrilinos_ENABLE_ALL_PACKAGES=OFF \
-DTrilinos_ENABLE_ALL_OPTIONAL_PACKAGES=ON \
-DTrilinos_ENABLE_Belos=ON \
-DTrilinos_ENABLE_Amesos=ON \
-DTrilinos_ENABLE_TESTS=OFF \
-DCMAKE_INSTALL_PREFIX=C:/Trilinos/dummy \
..\Trilinos-master
```

One thing I noticed at line 328 - 348 in the attached file is that it failed to find the third party library `DLlib` , which I did not explicitly enable it in my options. Is `DLlib` required to build the `kokkoscore.lib` and `teuchoscore.lib`?

**Comment by cgcgcg** [comment]
Hm, that looks alright to me. How far does `make` get?

**Comment by jhimbele3** [comment]
`make install` doesn't work and it just outputs the following. In fact, there is no `Makefile` in the build directory.
```
make: *** No rule to make target 'install'.  Stop.
```

In case of running `cmake -P cmake_install.cmake`, the console output is
[ConsoleOutput2.txt](https://github.com/trilinos/Trilinos/files/6913302/ConsoleOutput2.txt)

If I change the `CMAKE_INSTALL_CONFIG_NAME` at line 15 in `cmake_install.cmake` from **Release** to **Debug**, there won't be any error and it successfully creates the Trilinos header files.

**Comment by cgcgcg** [comment]
That is super strange. CMake claims to have written build files, yet there is no `Makefile` in `C:/Trilinos/dummy`?

**Comment by jhimbele3** [comment]
No I can't find any `Makefile` in `C:/Trilinos/dummy` but I do see `cmake_install.cmake` instead.

It also created `cmake_pbp_install.cmake` in `C:/Trilinos/dummy`, which had an instruction for `cmake -P cmake_install.cmake`.
[cmake_pbp_install.txt](https://github.com/trilinos/Trilinos/files/6913332/cmake_pbp_install.txt)

Yes, `C:/Trilinos/dummy` is both my build and install dir for the moment. Of course, I will be changing the install dir later once I confirmed the testing.

**Comment by cgcgcg** [comment]
Looks like CMake might need `-G "Unix Makefiles"` on Windows:  https://stackoverflow.com/questions/39643291/make-without-makefile-after-cmake

**Comment by jhimbele3** [comment]
Wonderful! I was able to generate `Makefile` with `-G "Unix Makefiles"`. Thank you so much.

Now I tried `make install` again, it gave the following compile error. I will find out what it caused this error.
```
[  0%] Building CXX object packages/kokkos/core/src/CMakeFiles/kokkoscore.dir/impl/Kokkos_CPUDiscovery.cpp.obj
[  0%] Building CXX object packages/kokkos/core/src/CMakeFiles/kokkoscore.dir/impl/Kokkos_Core.cpp.obj
In file included from C:/Trilinos/Trilinos-master/packages/kokkos/core/src/Kokkos_Atomic.hpp:187,
                 from C:/Trilinos/Trilinos-master/packages/kokkos/core/src/impl/Kokkos_Atomic_View.hpp:48,
                 from C:/Trilinos/Trilinos-master/packages/kokkos/core/src/impl/Kokkos_ViewMapping.hpp:59,
                 from C:/Trilinos/Trilinos-master/packages/kokkos/core/src/Kokkos_View.hpp:501,
                 from C:/Trilinos/Trilinos-master/packages/kokkos/core/src/Kokkos_Parallel.hpp:53,
                 from C:/Trilinos/Trilinos-master/packages/kokkos/core/src/Kokkos_Serial.hpp:57,
                 from C:/Trilinos/Trilinos-master/packages/kokkos/core/src/decl/Kokkos_Declare_SERIAL.hpp:49,
                 from C:/Trilinos/dummy/packages/kokkos/KokkosCore_Config_DeclareBackend.hpp:47,
                 from C:/Trilinos/Trilinos-master/packages/kokkos/core/src/Kokkos_Core.hpp:56,
                 from C:/Trilinos/Trilinos-master/packages/kokkos/core/src/impl/Kokkos_Core.cpp:45:
C:/Trilinos/Trilinos-master/packages/kokkos/core/src/impl/Kokkos_Atomic_Windows.hpp: In function 'T Kokkos::atomic_compare_exchange(volatile T*, const T&, typename std::enable_if<(sizeof (T) == sizeof (char)), const T&>::type)':
C:/Trilinos/Trilinos-master/packages/kokkos/core/src/impl/Kokkos_Atomic_Windows.hpp:87:11: error: there are no arguments to '_InterlockedCompareExchange8' that depend on a template parameter, so a declaration of '_InterlockedCompareExchange8' must be available [-fpermissive]
   tmp.i = _InterlockedCompareExchange8((CHAR*)dest, *((CHAR*)&val),
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:/Trilinos/Trilinos-master/packages/kokkos/core/src/impl/Kokkos_Atomic_Windows.hpp:87:11: note: (if you use '-fpermissive', G++ will accept your code, but allowing the use of an undeclared name is deprecated)
make[2]: *** [packages/kokkos/core/src/CMakeFiles/kokkoscore.dir/build.make:92: packages/kokkos/core/src/CMakeFiles/kokkoscore.dir/impl/Kokkos_Core.cpp.obj] Error 1
make[1]: *** [CMakeFiles/Makefile2:2182: packages/kokkos/core/src/CMakeFiles/kokkoscore.dir/all] Error 2
make: *** [Makefile:166: all] Error 2
```

**Comment by cgcgcg** [comment]
Kokkos might have some outstanding issues building on Windows, see e.g. here https://github.com/kokkos/kokkos/pull/4030

**Comment by jhimbele3** [comment]
@cgcgcg Again, I appreciate your help. I will have a look!

**Comment by jhimbele3** [comment]
I still get the same error even after making the changes suggested by @cgcgcg.

```
[  0%] Building CXX object packages/kokkos/core/src/CMakeFiles/kokkoscore.dir/impl/Kokkos_CPUDiscovery.cpp.obj
[  0%] Building CXX object packages/kokkos/core/src/CMakeFiles/kokkoscore.dir/impl/Kokkos_Core.cpp.obj
In file included from C:/Trilinos/Trilinos-master/packages/kokkos/core/src/Kokkos_Atomic.hpp:187,
                 from C:/Trilinos/Trilinos-master/packages/kokkos/core/src/impl/Kokkos_Atomic_View.hpp:48,
                 from C:/Trilinos/Trilinos-master/packages/kokkos/core/src/impl/Kokkos_ViewMapping.hpp:59,
                 from C:/Trilinos/Trilinos-master/packages/kokkos/core/src/Kokkos_View.hpp:501,
                 from C:/Trilinos/Trilinos-master/packages/kokkos/core/src/Kokkos_Parallel.hpp:53,
                 from C:/Trilinos/Trilinos-master/packages/kokkos/core/src/Kokkos_Serial.hpp:57,
                 from C:/Trilinos/Trilinos-master/packages/kokkos/core/src/decl/Kokkos_Declare_SERIAL.hpp:49,
                 from C:/Trilinos/dummy/packages/kokkos/KokkosCore_Config_DeclareBackend.hpp:47,
                 from C:/Trilinos/Trilinos-master/packages/kokkos/core/src/Kokkos_Core.hpp:56,
                 from C:/Trilinos/Trilinos-master/packages/kokkos/core/src/impl/Kokkos_Core.cpp:45:
C:/Trilinos/Trilinos-master/packages/kokkos/core/src/impl/Kokkos_Atomic_Windows.hpp: In function 'T Kokkos::atomic_compare_exchange(volatile T*, const T&, typename std::enable_if<(sizeof (T) == sizeof (char)), const T&>::type)':
C:/Trilinos/Trilinos-master/packages/kokkos/core/src/impl/Kokkos_Atomic_Windows.hpp:87:11: error: there are no arguments to '_InterlockedCompareExchange8' that depend on a template parameter, so a declaration of '_InterlockedCompareExchange8' must be available [-fpermissive]
   tmp.i = _InterlockedCompareExchange8((CHAR*)dest, *((CHAR*)&val),
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:/Trilinos/Trilinos-master/packages/kokkos/core/src/impl/Kokkos_Atomic_Windows.hpp:87:11: note: (if you use '-fpermissive', G++ will accept your code, but allowing the use of an undeclared name is deprecated)
In file included from C:/Trilinos/Trilinos-master/packages/kokkos/core/src/Kokkos_Atomic.hpp:212,
                 from C:/Trilinos/Trilinos-master/packages/kokkos/core/src/impl/Kokkos_Atomic_View.hpp:48,
                 from C:/Trilinos/Trilinos-master/packages/kokkos/core/src/impl/Kokkos_ViewMapping.hpp:59,
                 from C:/Trilinos/Trilinos-master/packages/kokkos/core/src/Kokkos_View.hpp:501,
                 from C:/Trilinos/Trilinos-master/packages/kokkos/core/src/Kokkos_Parallel.hpp:53,
                 from C:/Trilinos/Trilinos-master/packages/kokkos/core/src/Kokkos_Serial.hpp:57,
                 from C:/Trilinos/Trilinos-master/packages/kokkos/core/src/decl/Kokkos_Declare_SERIAL.hpp:49,
                 from C:/Trilinos/dummy/packages/kokkos/KokkosCore_Config_DeclareBackend.hpp:47,
                 from C:/Trilinos/Trilinos-master/packages/kokkos/core/src/Kokkos_Core.hpp:56,
                 from C:/Trilinos/Trilinos-master/packages/kokkos/core/src/impl/Kokkos_Core.cpp:45:
C:/Trilinos/Trilinos-master/packages/kokkos/core/src/impl/Kokkos_Atomic_Exchange.hpp: At global scope:
C:/Trilinos/Trilinos-master/packages/kokkos/core/src/impl/Kokkos_Atomic_Exchange.hpp:406:46: note: #pragma message: WARNING: no atomics defined
 #pragma message("WARNING: no atomics defined")
                                              ^
make[2]: *** [packages/kokkos/core/src/CMakeFiles/kokkoscore.dir/build.make:92: packages/kokkos/core/src/CMakeFiles/kokkoscore.dir/impl/Kokkos_Core.cpp.obj] Error 1
make[1]: *** [CMakeFiles/Makefile2:2182: packages/kokkos/core/src/CMakeFiles/kokkoscore.dir/all] Error 2
make: *** [Makefile:166: all] Error 2
```


I was afraid that `_InterlockedCompareExchange8` and `_InterlockedCompareExchange128` are not recognized on my Windows system, so I commented out line 77-90 in `Kokos_Atomic_Windows.hpp` (https://github.com/kokkos/kokkos/blob/master/core/src/impl/Kokkos_Atomic_Windows.hpp#L77-L90). The above error has now disappeared but I got another error since other files invoke template functions using `_InterlockedCompareExchange8` and `_InterlockedCompareExchange128`.
So my assumption is that my Windows system recognizes `_InterlockedCompareExchange16`, `_InterlockedCompareExchange` and `_InterlockedCompareExchange64` but not `_InterlockedCompareExchange8` and `_InterlockedCompareExchange128`.

I need to find out how to fix aforementioned problem.

**Comment by cgcgcg** [comment]
@jhimbele3 My understanding is that Kokkos doesn't (currently) work on Windows. Is that correct, @trilinos/kokkos ?

**Comment by jhimbele3** [comment]
@cgcgcg Yes it looks like it doesn't work on Windows 10 unless I've missed something.

I want to use a direct and iterative solver for my FEM simulation project and I therefore selected Amesos and Belos. I will check whether I need a Epetra.

I will try building kokkos tonight again by adding some C/C++ compiler flags.

By the way, there was a max length string issue on Windows, so I added the following line to https://github.com/trilinos/Trilinos/blob/master/CMakeLists.txt

```
## set maximum length of string
if (WIN32)
  set(CMAKE_OBJECT_PATH_MAX 260)
endif ()
```
I don't know if you consider this as an enhancement.

**Comment by cgcgcg** [comment]
I think the best option is to use an OS that is not Windows ;-)
You probably will need Epetra or Tpetra since they provide linear algebra. Most of Trilinos' packages provide interfaces for either one or the other. (E.g. Amesos -> Epetra, Amesos2 -> Tpetra.) Epetra runs on CPUs, Tpetra on pretty much anything. New development mostly focuses on the Tpetra stack.

**Comment by jhimbele3** [comment]
@cgcgcg, Thanks for the help. I agree that I should use the Linux system as I see more and more errors from Kokkos. I will close this issue!
