### ISSUE TITLE
Accessing RCPs from Julia (programming language) (was "Only using non-owning RCPs")

### ISSUE THREAD

**Issue by barche** [trilinos/Trilinos#952]
Continuation from the mailing list discussion:
https://trilinos.org/pipermail/trilinos-users/2016-December/005744.html

@bartlettroscoe Thanks for the reply. I see now that my approach would require keeping all Trilinos objects that are created from Julia safe from garbage collection, which in Julia means they must always be referenced by a variable. This seems like an unreasonable burden on the user, so I'll default to constructing owning RCPs whenever a Trilinos object is allocated. Passing the RCP to Julia requires keeping a pointer to it, so that would mean heap-allocating the RCP and deleting it in the finalizer.

**Comment by mhoemmen** [comment]
It would make sense to talk to @wfspotz about what he does in PyTrilinos (a Python interface to Trilinos), or what @maherou plans for the revival of ForTrilinos.  One approach is for the interface layer to maintain a table of outstanding Trilinos objects, and do garbage collection on them.  It's a bit like the Fortran 77 MPI binding, where users see only integer "handles," and the binding layer has to manage all the objects.  (The MPI standard implies a need for reference counting internally, e.g., that it's legal to free an MPI_Datatype for an MPI_Irecv in flight.)

**Comment by bartlettroscoe** [comment]
> Passing the RCP to Julia requires keeping a pointer to it, so that would mean heap-allocating the RCP and deleting it in the finalizer.

@barche, that is some unfortunate extra overhead but for most use cases this is O(1) overhead so if you are dealing with larger objects on a more course-grained level, then this overhead should be small compared to the total runtime.

**Comment by barche** [comment]
Allright, thanks, I don't think the overhead will be a problem for my use case. I've taken the first steps (map initialization only) in translating the Tpetra power method example:
https://github.com/barche/Trilinos.jl/blob/master/examples/powermethod.jl

**Comment by mhoemmen** [comment]
@barche Nice!  Do you think your RCP->Julia scheme could generalize to other languages?

**Comment by wfspotz** [comment]
Just a note on what we do in PyTrilinos: SWIG provides a set of typemaps (the SWIG system for mapping between source language [C, C++, ...] types and target language [Python, ...] types) for smart pointers, which I was able to modify to work with RCPs.

This system does allocate RCPs on the heap. Typically, RCPs have ownership, although there are use cases for non-owning RCPs. Since Python employs reference counting for all Python objects, the typical reference counting is hierarchical: when a Python reference count goes to zero, only then is the RCP reference count decremented.

**Comment by barche** [comment]
@mhoemmen I don't think it would generalize directly. My approach is loosely based on what Boost.Python does, but different languages have different features. Julia has parametric types that are equivalent to C++ templates, so I'm using an RCP parametric type on the Julia side. Other than that, the approach is in fact similar to what @wfspotz said about PyTrilinos: conversion from RCP to the held type is automatic, so the user never has to deal with the RCP directly.

**Comment by bartlettroscoe** [comment]
@barche, have we addressed this issue?  Can we close this?

**Comment by barche** [comment]
Yes, thanks!
