### ISSUE TITLE
Belos: issue causing segfault when output requested

### ISSUE THREAD

**Issue by skennon10** [trilinos/Trilinos#9522]
This line sets "Output Style" to `verbosity_` instead of `outputStyle_`:
https://github.com/trilinos/Trilinos/blob/53ecba4c5e6b7b962967e5acdb6337d17b5002c7/packages/belos/src/BelosPseudoBlockGmresSolMgr.hpp#L711
For my case using this solver, `verbosity_ = 41`, and  it causes a segfault here since `StatusTestOutputFactory::create` has no "default" clause in the switch statement and returns a null RCP: 
https://github.com/trilinos/Trilinos/blob/53ecba4c5e6b7b962967e5acdb6337d17b5002c7/packages/belos/src/BelosPseudoBlockGmresSolMgr.hpp#L1184

**Comment by jennloe** [comment]
I'll look at this.

**Comment by jennloe** [comment]
Closed by PR #9539.
