### ISSUE TITLE
KokkosKernels:  kokkoskernels_tpls.cmake invalid parsing(string operation)

### ISSUE THREAD

**Issue by marcinwrobel1986** [trilinos/Trilinos#9528]
## Bug Report
@trilinos/KokkosKernels

### Description
Invalid parsing(string operation) at the bottom of `kokkoskernels_tpls.cmake` is causing an error after installing KokkosKernels.
 In `<install_path>/lib/cmake/KokkosKernels/KokkosKernelsConfig.cmake`, which is created based on `KokkosKernelsConfig.cmake.in`. 
Substitution of `@KOKKOSKERNELS_TPL_EXPORTS@` is causing problems.
It is getting substituted with:
```
IF(NOT TARGET KokkosKernels::SUPERLU)
ADD_LIBRARY(KokkosKernels::SUPERLU UNKNOWN IMPORTED)
SET_TARGET_PROPERTIES(KokkosKernels::SUPERLU PROPERTIES
IMPORTED_LOCATION /usr/lib/x86_64-linux-gnu/libsuperlu.so
INTERFACE_INCLUDE_DIRECTORIES /usr/include/superlu
/usr/include/superlu
)
ENDIF()
```
As [SET_TARGET_PROPERTIES](https://cmake.org/cmake/help/latest/command/set_target_properties.html?highlight=set_target_properties) is parsing it takes `prop1` and then `value1` and so on. In `INTERFACE_INCLUDE_DIRECTORIES` there are two arguments, which are identical(in my case) `/usr/include/superlu`. These two arguments are a list before it goes through mentioned  bottom lines  of `kokkoskernels_tpls.cmake` :

```shell
#Convert list to newlines (which CMake doesn't always like in cache variables)
STRING(REPLACE ";" "\n" KOKKOSKERNELS_TPL_EXPORT_TEMP "${KOKKOSKERNELS_TPL_EXPORTS}")
#Convert to a regular variable
UNSET(KOKKOSKERNELS_TPL_EXPORTS CACHE)
SET(KOKKOSKERNELS_TPL_EXPORTS ${KOKKOSKERNELS_TPL_EXPORT_TEMP})
```
It does not matter what arguments are passed into `INTERFACE_INCLUDE_DIRECTORIES`, if there is more than one, the error will always occur, because of replacing semicoln (";") from the list of `INTERFACE_INCLUDE_DIRECTORIES`.

**SOLUTION:**

In my case the solution would be not adding duplicate paths to `INTERFACE_INCLUDE_DIRECTORIES` list, but it will not help in more general case, where `INTERFACE_INCLUDE_DIRECTORIES` has more than one path and the paths are different. The problem is with replacment of semicoln (";").

What went wrong?
- `;` in CMake list was replaced with `new line` and a CMake list was not passed as CMake list, but two arguments with `new line` between them

What should have happened?
- CMake list should be passed as Cmake list as [SET_TARGET_PROPERTIES](https://cmake.org/cmake/help/latest/command/set_target_properties.html?highlight=set_target_properties) takes one value to one property (this value could be a CMake list)

Do you have an idea what might fix things?
- string replacement change at the bottom of `kokkoskernels_tpls.cmake`

How has this bug affected you?
- I needed to manually changed `KokkosKernelsConfig.cmake`

### Steps to Reproduce
- add a second path to: `${TPL_INCLUDES}` as it corresponds to `INTERFACE_INCLUDE_DIRECTORIES` anywhere in `kokkoskernels_tpls.cmake`
- install KokkosKernels and check KokkosKernelsConfig.cmake
- try to build anything with this installed library

**Comment by cgcgcg** [comment]
@trilinos/kokkos-kernels

**Comment by srajama1** [comment]
@ndellingwood This probably needs a fix in master repo and on the Trilinos repo.

**Comment by srajama1** [comment]
@lucbv FYI ..
