### ISSUE TITLE
MueLu: Factory Graph Output Upgrades

### ISSUE THREAD

**Issue by key6oardWarrior** [trilinos/Trilinos#9534]
## Enhancement
@trilinos/packages/muelu/utils/FacotryGraph

We need a python tool to combine files into a nested dot file. Currently there is no way of accomplishing this in python, so this tool will allow us to not have to do task by hand. For implementation the code will follow three rules:

1) Some nodes will appear on multiple levels. Those nodes should only appear on the first (lowest number) subgraph in which they exist (and the arrows should route between subgraphs).

2) "NoFactory" is a special case node and exists on every subgraph. Unlike other duplicates, that should just remain on each individual subgraph.

3) Nodes with no edges can be removed.

The lack of this feature makes it harder for anyone who wants to see all factories and how they are connected in one file. So someone will have to do this task by hand which will take a long time and that person may make mistakes.

To call this work complete we must demonstrate that all .dot files are merged into one .dot file based on the three rules listed and that a .png file can also be created for easy viewing.

**Comment by cgcgcg** [comment]
Closed by #9536
