### ISSUE TITLE
Ifpack2: dangerous shadowing in Details::MultiVectorLocalGatherScatter

### ISSUE THREAD

**Issue by jhux2** [trilinos/Trilinos#954]
@trilinos/ifpack2 
In Ifpack2_Details_MultiVectorLocalGatherScatter.hpp in the gatherMVtoView method, there is this code:

```
170     for(LO i = 0; i < perm.size(); ++i)
171     //note: j is col, i is row
172     for(size_t j = 0; j < X_out.getNumVectors(); ++j) {
173       Teuchos::ArrayRCP<OutScalar> X_out_j = X_out.getDataNonConst(j);
174       for(size_t i = 0; i < X_out.getLocalLength(); ++i) {
175         const LO i_perm = perm[i];
176         X_out_j[i] = X_in(i_perm, j);
177       }
178     }
179   }
```
The inner use of ```i``` is shadowed by the outer.  This looks dangerous.

I thought this would be the proper fix:
```
170     for(LO i = 0; i < perm.size(); ++i)
171     //note: j is col, i is row
172     for(size_t j = 0; j < X_out.getNumVectors(); ++j) {
173       Teuchos::ArrayRCP<OutScalar> X_out_j = X_out.getDataNonConst(j);
174       for(size_t k = 0; k < X_out.getLocalLength(); ++k) {
175         const LO i_perm = perm[i];
176         X_out_j[k] = X_in(i_perm, j);
177       }
178     }
179   }

```

However, ```SparseContainer_double_int_int_ILUT_UnitTest``` fails when I make that change.

I had hoped to fix this while simultaneously pushing an unrelated change to MueLu, but no dice.

**Comment by jhux2** [comment]
@brian-kelley

**Comment by brian-kelley** [comment]
I just made a patch that fixes this and the other shadow warnings in DenseContainer_def and TriDiContainer_def that Brent discovered when building Sierra. In this case, the first loop shouldn't have been there at all. The patch is in my fork, https://github.com/brian-kelley/Trilinos/tree/newDevelop. Should I push it to develop?

**Comment by mhoemmen** [comment]
> The patch is in my fork, https://github.com/brian-kelley/Trilinos/tree/newDevelop. Should I push it to develop?

Does it pass the tests?

**Comment by brian-kelley** [comment]
Yes, all Ifpack2 tests pass.
