### ISSUE TITLE
PyTrilinos: move out SWIG detection to root cmake/

### ISSUE THREAD

**Issue by aprokop** [trilinos/Trilinos#955]
ForTrilinos will use SWIG and thus this code could be shared by both.

**Comment by mhoemmen** [comment]
I recall @wfspotz saying a while back that SWIG has had significant bug fixes across versions, and thus the version might matter quite a bit for PyTrilinos vs. ForTrilinos.  It would make sense to check with @wfspotz for the version that works with PyTrilinos.

**Comment by wfspotz** [comment]
I currently use version 3.0.10. Versions 3.0.11 and 3.0.12 generate wrappers that have errors in PyTrilinos.

**Comment by wfspotz** [comment]
@aprokop What is the status of ForTrilinos for ECP?

**Comment by aprokop** [comment]
@wfspotz Right now, ForTrilinos uses a custom fork of SWIG and runs off Trilinos 12.12 branch. It supports linear solvers, implicit linear operators and eigensolvers.
