### ISSUE TITLE
Ifpack2::BlockRelaxation: Failing unit test

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#956]
@trilinos/ifpack2 @brian-kelley @csiefer2 

Ifpack2BlockRelaxation_Performance_UnitTest is reporting a failure:

http://testing.sandia.gov/cdash/testDetails.php?test=35939586&build=2677425
```
Throw test that evaluated to true: (static_cast<size_t> (indices.size ()) < theNumEntries || static_cast<size_t> (values.size ()) < theNumEntries)
 
Tpetra::CrsMatrix<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Cuda, Kokkos::CudaUVMSpace>, false>::getLocalRowCopy: Row with local index 0 has 4294967293 entry/ies, but indices.size() = 3 and values.size() = 3.
```
4294967295 is the max `unsigned int` value; Tpetra uses values like that as "invalid" flags.

That's a CUDA build.  If you need help setting up a CUDA build, let me know.

**Comment by brian-kelley** [comment]
I couldn't replicate this exception on geminga with MPI and CUDA (both debug and release). I think the bug was in Tpetra or Ifpack2 but was fixed at some point. It also doesn't show up anywhere on CDash. I'll close this for now, and can of course check again if it is still an issue.

**Comment by mhoemmen** [comment]
Thanks @brian-kelley !
