### ISSUE TITLE
Tpetra::CrsMatrix: Possible bug in transposed apply

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#958]
@trilinos/tpetra 

@ikalash reported the following:
> I am trying to use Tpetra::CrsMatrix apply method with a Teuchos::TRANS combine mode, and the method does not appear to be working correctly.  I end up with a vector of zeros even though the operator is nonzero, nor is the input vector.  If I set the combine mode to Teuchos::NO_TRANS, things work correctly.  I assume Teuchos::TRANS has been tested, so perhaps I am doing something wrong, although I am not sure what it could be.  Is there some caveat about the method’s usage with the TRANS combine mode?  I printed the Boolean returned when calling hasTransposeApply() and it prints true.

@ikalash also sent data, which I'll post here.

**Comment by mhoemmen** [comment]
Here are the data that @ikalash sent me.  All three files are in Matrix Market format.  The first file represents the matrix's row Map, the second file its column Map, and the third the matrix itself.

[rowMapT.txt](https://github.com/trilinos/Trilinos/files/680252/rowMapT.txt)
[colMapT.txt](https://github.com/trilinos/Trilinos/files/680251/colMapT.txt)
[filteredOperatorT.txt](https://github.com/trilinos/Trilinos/files/680250/filteredOperatorT.txt)

**Comment by ikalash** [comment]
@mhoemmen I used 1 process.  Sorry for the delay in my response.  For some reason, I don't get notifications about issues in which I am mentioned on github.  Have you had a chance to look into this issue?

**Comment by mhoemmen** [comment]
@ikalash Sorry, haven't had time yet.  Is this getting urgent for you, or can you work around for a little while yet?  I've been juggling a pressing deliverable (scaling and performance comparisons for basic iterative solvers -- you might find the results interesting) with another milestone, and you're the only one right now wanting transposed apply.  I can reprioritize if it's urgent.  Thanks!

**Comment by ikalash** [comment]
@mhoemmen That's OK.  I would estimate right now that we'd need this within a month or so.  We are planning to remove Epetra from Albany in the very near future.  Until then, we can use the Epetra Multiply() routine with transpose set to true (what we are using now in the code).

**Comment by mhoemmen** [comment]
@ikalash Just curious -- do you need this because you're using a solver that requires the transpose (e.g., QMR), or because you're building a block operator [A, B; B^T H] ?

**Comment by ikalash** [comment]
@mhoemmen The former.  I just need to be able to compute y = A^T*x.  Is there any alternative way to achieve this in Tpetra w/o using apply with a TRANS CombineMode, if I do not want to form explicitly A^T?

**Comment by mhoemmen** [comment]
@ikalash The reason I asked was to figure out whether you could get around not having the transpose.  You could also work around by using Tpetra::RowMatrixTransposer to compute the transpose explicitly.  However, if this is a bug, I really need to fix it :)

**Comment by ikalash** [comment]
@mhoemmen I think probably it's possible to get around not having the transpose.  I was trying to find something like the Tpetra::RowMatrixTransposer.  I'll take a look at that and let you know if it works for me.  I guess it might be slower than doing the apply with the TRANS CombineMode?

**Comment by mhoemmen** [comment]
@ambrad explained that you probably want the transpose for adjoints.  That's different than wanting to use an iterative linear solver like QMR, that requires transposed apply.

@ikalash wrote:
> I was trying to find something like the Tpetra::RowMatrixTransposer. I'll take a look at that and let you know if it works for me. I guess it might be slower than doing the apply with the TRANS CombineMode?

Yes.  It actually constructs a new matrix B, which equals the transpose of A.  Thus, it uses more memory, and you should try to reuse the result.

**Comment by ikalash** [comment]
@mhoemmen I tried it and I think I can make the rowmatrixtransposer work as a temporary fix.  Thanks for the suggestion.

**Comment by kddevin** [comment]
#7898 fixes bugs in Transposed apply.  Would it address the use case described here?

**Comment by csiefer2** [comment]
Closed as per @ikalash
