### ISSUE TITLE
MueLu:  Trans mode is not supported but no error is thrown when requested

### ISSUE THREAD

**Issue by mperego** [trilinos/Trilinos#9590]
## Bug Report
@trilinos/muelu 

### Description
MueLu, when used as preconditioner, does not support the TRANS mode. However, no error is thrown when TRANS mode is requested, which typically leads to very poor convergence since the preconditioner is built for the original matrix rather than the transposed one.

An error should be thrown when the TRANS mode is requested.
In case it's useful, here is how other solvers handle this:
https://github.com/trilinos/Trilinos/blob/master/packages/ifpack2/src/Ifpack2_Details_Amesos2Wrapper_def.hpp#L452
https://github.com/trilinos/Trilinos/blob/master/packages/shylu/shylu_dd/frosch/src/SolverInterfaces/FROSch_Amesos2SolverTpetra_def.hpp#L102

### Steps to Reproduce
I don't have a unit test to reproduce this, but once you have a fix, I can verify it using Albany tests, which use Stratimikos.

**Comment by srajama1** [comment]
@jhux2

**Comment by cgcgcg** [comment]
@mperego Could you check if this is fixed for you?

**Comment by mperego** [comment]
It is fixed, thanks @cgcgcg!
