### ISSUE TITLE
Ifpack2: Improve block Jacobi performance

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#96]
@trilinos/ifpack2 @trilinos/tpetra @amklinv 

We want to improve performance of block Jacobi by at least 2x.  "Block Jacobi" is what happens when one gives a `Tpetra::Experimental::BlockCrsMatrix` to `Ifpack2::Relaxation` and asks for Jacobi.  The current implementation of block Jacobi lives in Ifpack2_Relaxation_def.hpp, in the `ApplyInverseJacobi_BlockCrsMatrix` method.  

There are two optimizations that come to mind:

1. If the initial guess vector is zero (`ZeroStartingSolution_` is `true`), then on the first (zeroth) sweep, we can replace the sparse mat-vec (`blockMat->apply(Y, A_times_Y)`, line 1166) with a "block scaling" by the inverse of the block diagonal.  Compare to non-block Jacobi in lines 1076-1100 of the same file (`ApplyInverseJacobi` method).

2. Currently, we apply the inverse of the block diagonal, by using linear solves (GETRS).  It's likely more efficient to precompute the inverse (GETRI) and apply it directly (GEMV).  I think this for the following reasons.  First, batched GEMV is a simpler kernel and thus easier to optimize.  It may even have vendor implementations.  Second, not passing the pivots around means less data movement.  Third, not passing the pivots around makes interfaces simpler, and thus easier to optimize. 

All other optimizations should wait until we know how many sweeps the users want.  Block Jacobi relies on `BlockCrsMatrix::apply` (sparse mat-vec) after the first sweep.  The logical way to improve performance for multiple sweeps would be to make sparse mat-vec faster.  With thread parallelization, we will also need to consider the update and "block scaling" kernels (compare to lines 1111 and 1112 of nonblock Jacobi).  It may also pay to merge the sparse mat-vec, update, and block scaling kernels into a single kernel, like we do with block Gauss-Seidel.

**Comment by mhoemmen** [comment]
I am about to push two commits that begin to address both issues.  This work is not finished yet, but the commits will make both of the optimizations mentioned above much easier.  The two commits break out the block scaling and update kernels into two new BlockMultiVector methods, blockWiseMultiply and blockJacobiUpdate.  Writing unit tests for each of them paid off, because they let me find and fix a tricky bug!

Thus far, I have only modified Tpetra.  It's trickier to test Ifpack2 because the applications in question seem to be more sensitive to convergence then the typical test problems that we cook up.  I might choose instead to submit the changes to Ifpack2 as a pull request or patch, so that the apps can try them out.

**Comment by mhoemmen** [comment]
Note that using the two new methods mentioned above should also improve Ifpack2::Relaxation build time, once we actually start using them there.  BlockMultiVector doesn't have a lot of code in it, so it's not so bad to add a couple kernels to it.

**Comment by mhoemmen** [comment]
One issue preventing us from using these new methods for block Jacobi, is that block Gauss-Seidel uses GETRS to apply the inverse of the diagonal blocks, instead of storing the inverses explicitly and using GEMV.  It's pretty easy to fix this, but we have to change the interface of BlockCrsMatrix.  (I don't mind doing that -- it's still in the Experimental namespace for a reason!)

**Comment by mhoemmen** [comment]
@amklinv Please see the above pull request, and try out that commit when you get the chance.  Thanks!

**Comment by mhoemmen** [comment]
In case you have trouble with the pull request, I've attached the patch (it's one commit) to this comment as a .txt file.  Github doesn't allow .patch attachments.  Just rename .txt to .patch.  Thanks!

[0001-Ifpack2-Tpetra-Optimize-BlockCrs-Jacobi-S-GS-per-Iss.txt](https://github.com/trilinos/Trilinos/files/102756/0001-Ifpack2-Tpetra-Optimize-BlockCrs-Jacobi-S-GS-per-Iss.txt)

**Comment by mhoemmen** [comment]
I decided to close the pull request and just commit the changes.  This is only because Ifpack2::Relaxation is undergoing a lot of changes right now due to Issue #85, and I didn't want y'all to have to struggle with difficult merges.  The two commits in question (see above) are self-contained, so it should be pretty easy to compare performance before and after.  The text below summarizes the main optimizations, which are in the first commit (4dfbd6b) mentioned above.

I optimized Ifpack2's implementation of block Jacobi and block (Symmetric) Gauss-Seidel, in Ifpack2::Relaxation. I did the following:

  1. Ifpack2 now stores and applies the inverse of the matrix's block diagonal explicitly.
  2. Use the new BlockMultiVector::blockWiseMultiply method to optimize the first sweep of block Jacobi
  3. Use the new BlockMultiVector::blockJacobiUpdate method for subsequent sweeps, rather than hard-coding the low-level kernel in Ifpack2::Relaxation

In (1), "explicitly" means that each block's inverse is computed in place (LU factorization (GETF2) + GETRI) and applied using a matrix-vector product (GEMV). Before, Ifpack2::Relaxation would store
the LU factorization of each block (result of GETF2), and apply it using a linear solve (GETRS).

Ifpack2::Relaxation uses the same storage format for the block diagonal, for both (block) Jacobi and (block) (Symmetric) Gauss-Seidel. Thus, I had to change both at the same time. I also had to change Tpetra::Experimental::BlockCrsMatrix's localGaussSeidel interface, because it no longer needs the array of pivots from the LU factorizations (GETRS needs the pivots, but GEMV does not). This makes BlockCrsMatrix's localGaussSeidel interface more consistent with CrsMatrix's interface.

**Comment by aprokop** [comment]
> Ifpack2 now stores and applies the inverse of the matrix's block diagonal explicitly.

Theoretically, this is a tradeoff. If your block size is large enough, you will get better performance out of linear solves rather than full inversion when doing a limited number of iterations. The only variant that comes to mind is the high order Travis' runs, where one uses block GS/block Jacobi in a multigrid that converges quickly on a matrix that uses a high order approximation. The higher the order of approximation, the larger the block size. It would make sense to make sure that the performance of his runs hasn't suffered. How difficult would it be to add an option to switch between two variants?

**Comment by mhoemmen** [comment]
On Jan 29, 2016, at 10:10 PM, Andrey Prokopenko <notifications@github.com<mailto:notifications@github.com>> wrote:


Ifpack2 now stores and applies the inverse of the matrix's block diagonal explicitly.

Theoretically, this is a tradeoff. If your block size is large enough, you will get better performance out of linear solves rather than full inversion when doing a limited number of iterations.

Thanks for pointing this out.  On the other hand, it's easier to do fine-grained parallelization in GEMV than GETRS.  I see your point, though.

How difficult would it be to add an option to switch between two variants?

Not terribly hard.  Could you file a separate issue for this?  Thanks!

**Comment by mhoemmen** [comment]
I'm closing this.  Implementations evolve too fast and performance testing is ongoing.
