### ISSUE TITLE
Merge Kokkos and non-Kokkos implementations in MueLu_Aggregates_kokkos_decl.hpp

### ISSUE THREAD

**Issue by ppebay** [trilinos/Trilinos#9601]
## Enhancement
@trilinos/MueLu

* There are some minor changes in signature and a few cases where there are functions in one that are not in the other.
* Somebody munched up the template params from 4-param (non-Kokkos) to 3-param (Kokkos).  That'll need to get fixed.
* Verdict:  Should be mergeable with limited instructions.

**Comment by jhux2** [comment]
@trilinos/muelu
