### ISSUE TITLE
MueLu:  Merge Kokkos and non-Kokkos versions of MueLu_CoordinatesTransferFactory

### ISSUE THREAD

**Issue by JacobDomagala** [trilinos/Trilinos#9608]
## Enhancement
@trilinos/MueLu

**Comment by GrahamBenHarper** [comment]
@trilinos/muelu at this point, we have a hard dependency on Kokkos, so I think it's a good time to revisit how Kokkos refactor codes are handled

**Comment by cgcgcg** [comment]
Merged in #11659
