### ISSUE TITLE
Kokkos: an illegal memory access was encountered

### ISSUE THREAD

**Issue by jumlamb** [trilinos/Trilinos#9622]
## Bug Report
@trilinos/\<Kokkos\>

### Description
The Sierra/TF Team has seen a nightly test failure on an Nvidia build for a few weeks. Here's the error output:

```
terminate called after throwing an instance of 'std::runtime_error'
  what():  cudaDeviceSynchronize() error( cudaErrorIllegalAddress): an illegal memory access was encountered /sierra/build/linux_rh7/nightly/nvidia_trilinos_master/objs/tpls/spack/spack/.spack/stage/spack-stage-trilinos-2021.08.25-r32nhlwga6ychgkw2fmq5aujn2yylorp/spack-src/packages/kokkos/core/src/Cuda/Kokkos_Cuda_Instance.cpp:144
Traceback functionality not available
```
The below warning is seen several times before the test terminates:

```
Kokkos::Cuda::initialize WARNING: Cuda is allocating into UVMSpace by default
                                  without setting CUDA_LAUNCH_BLOCKING=1.
                                  The code must call Cuda().fence() after each kernel
                                  or will likely crash when accessing data on the host.
```

Thanks for any assistance you can provide. I can point to the nightly test files or provide any further information as needed.

Best,
Justin

**Comment by brian-kelley** [comment]
@jumlamb The warning about CUDA_LAUCH_BLOCKING is nothing to worry about. I think this is a case of a Cuda error being generated in a previous kernel, and that error flag is not checked (using cudaGetLastError) until this impl_deallocate call. If that's true you could get a much more useful backtrace by enabling these:
```
-DKokkos_ENABLE_DEBUG=ON
-DKokkos_ENABLE_DEBUG_BOUNDS_CHECK=ON
```
That will do 2 things:
- Abort on host or device on any out-of-bounds access of a Kokkos::View (a likely cause of cudaErrorIllegalAddress)
- Check the Cuda error flag after every kernel launch

**Comment by vbrunini** [comment]
For reference, the last kernel started when running with the Kokkos kernel logger is: `KokkosP:         MueLu::TentativeP::BuildCoords` and @jhux2 has the files to reproduce the issue.

**Comment by kyungjoo-kim** [comment]
@vbrunini Is this still issue or the updated Tpetra magically remove all the problem ?
