### ISSUE TITLE
Trilinos fails to build on Summit after OS upgrade

### ISSUE THREAD

**Issue by jrood-nrel** [trilinos/Trilinos#9625]
### Description

I'm personally using Spack on Summit to build my project (Nalu-Wind). I've tried GCC 10.2.0 and GCC 9.3.0 both with this same result shown below. One of my colleagues building without Spack encountered this problem as well. I think it is a problem with the newest Spectrum MPI compiler wrappers. I got this same problem in another project (AMR-Wind), but when I didn't pass the MPI compiler wrappers to CMake as `CMAKE_CXX_COMPILER=mpicxx` for example, and just let `FindMPI` do whatever it needed, it solved this problem. Trilinos, however, seems to always latch onto the compiler wrappers for the CMake compilers no matter what I try.

Can anyone confirm they can build Trilinos on Summit RHEL 8?

```
     436    -- Check for working CXX compiler: /sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-9.3.0/spectrum-mpi-10.4.0.3-20210112-2s7kpbzydf
            6val7k2d3e6cz3zdhtcwlw/bin/mpicxx - skipped
     437    -- Detecting CXX compile features
     438    -- Detecting CXX compile features - done
     439    -- CMAKE_CXX_COMPILER_ID='GNU'
     440    -- CMAKE_CXX_COMPILER_VERSION='9.3.0'
     441    -- The Fortran compiler identification is GNU 9.3.0
  >> 442    /lib/../lib64/crt1.o:(.rodata+0x8): undefined reference to `main'
     443    /usr/bin/ld: link errors found, deleting executable `a.out'
  >> 444    collect2: error: ld returned 1 exit status
     445    -- Detecting Fortran compiler ABI info
     446    -- Detecting Fortran compiler ABI info - failed
     447    -- Check for working Fortran compiler: /sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-9.3.0/spectrum-mpi-10.4.0.3-20210112-2s7kpb
            zydf6val7k2d3e6cz3zdhtcwlw/bin/mpif90
     448    -- Check for working Fortran compiler: /sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-9.3.0/spectrum-mpi-10.4.0.3-20210112-2s7kpb
            zydf6val7k2d3e6cz3zdhtcwlw/bin/mpif90 - broken
```

**Comment by jrood-nrel** [comment]
After inspecting the `trilinos` modules which already exist on Summit which were built using Spack, I was able to backtrack to a point in time where the CMake configure succeeds on Summit. So I should be able to solve this. I'm closing this and will reopen if necessary.

@sethrj I verified I can succeed with the latest Spack and this version of `trilinos/package.py` https://github.com/spack/spack/blob/0cc42acbbd0ae628b6e72ead02287930eef738b2/var/spack/repos/builtin/packages/trilinos/package.py so I will try to investigate the fix.

**Comment by jrood-nrel** [comment]
Turns out this is a problem with using Ninja for Trilinos on Summit. Which worked before the OS upgrade for us (or whatever may have changed in CMake or Trilinos over time, etc). However, I have no idea exactly what broke it.

CMake configure without ninja which succeeds:
```
-- Check for working Fortran compiler: /sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-10.2.0/spectrum-mpi-10.4.0.3-20210112-vet2p2ttgtyh6ixvtxq523rdi7ydj7r7/bin/mpif90 - skipped
```
CMake configure with ninja which fails the entire configure:
```
-- Check for working Fortran compiler: /sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-10.2.0/spectrum-mpi-10.4.0.3-20210112-vet2p2ttgtyh6ixvtxq523rdi7ydj7r7/bin/mpif90 - broken
```

**Comment by sethrj** [comment]
@tmdelellis saw something like this. I think it only happened when building on GPFS?
