### ISSUE TITLE
plans for explicit template instantiation in Intrepid2

### ISSUE THREAD

**Issue by jhux2** [trilinos/Trilinos#963]
Are there plans to add ETI support in Intrepid2?  This would help reduce build times in packages that depend on Intrepid2.

@trilinos/intrepid2

**Comment by kyungjoo-kim** [comment]
As far as I know, we do not have a plan to add ETI support on Intrepid2. For ETI, Intrepid2 can have built-in data types (double, float, and complex for certain functionalities) and AD types. Probably we want to instanciate for double and AD types. It is not quite intuitive for me to understand how to separate header files, its implmentation for AD types (AD dimension is compile time so we cannot explicitly instanciate for AD types, right ???) and the explicitly instanciated library for built-in datatypes. Do we have any other ETI examples that mix AD types and built-in types ?

**Comment by jhux2** [comment]
> Do we have any other ETI examples that mix AD types and built-in types ?

You might have a look at the system in stokhos that @etphipp created.
