### ISSUE TITLE
Kokkos::StaticCrsGraph does not use memory space template parameter passed to KokkosSparse::CrsMatrix

### ISSUE THREAD

**Issue by mndevec** [trilinos/Trilinos#964]
I am providing a device to CrsMatrix in the constructor. This is different than default, where device is either Kokkos::Cuda with hostpinned space, or Kokkos::OpenMP with Kokkos::Hostspace when HBM is enabled. 

I was expecting CrsMatrix memory to be allocated at the memory space I provide. However, this holds only for the values view, while row pointers and entries are still allocated at the default memory space of the provided execution space. 
It seems that StaticCrsGraph do not take the device as template argument, instead it is provided the execution space. It creates a default device, as a result allocated memories diverge for values and entries views.

Shouldn't StaticCrsGraph take the device as template argument instead of execution space?

@srajama1 @crtrott  @mhoemmen

**Comment by srajama1** [comment]
Yes, this needs to be fixed.

**Comment by mhoemmen** [comment]
@mndevec wrote:
> I am providing a device to CrsMatrix in the constructor.

Does that mean an "instance of a Kokkos::Device"?  Could you post a short example code here?

**Comment by mndevec** [comment]
I mean a template parameter, not an instance 
```c++
    typedef Kokkos::Device<Kokkos::OpenMP, Kokkos::HostSpace> myHostExecSpace;
    typedef typename MyKokkosSparse::CrsMatrix<wt, idx, myHostExecSpace, void, size_type > crsMat_host_t;
```

**Comment by mhoemmen** [comment]
@crtrott wants to be CC'd too.

**Comment by mhoemmen** [comment]
This is not actually an interface change; it does not break backwards compatibility.
