### ISSUE TITLE
Tpetra:  remove unneeded operations from fillComplete

### ISSUE THREAD

**Issue by kddevin** [trilinos/Trilinos#9655]
## Enhancement
@trilinos/tpetra

Tpetra's fillComplete does unnecessary work in cases where the graph is not modified.  These operations could be avoided.

Right now, to change the values in a matrix, it is recommended (and in some cases, enforced) that users do 
```
A.resumeFill();
change the values
A.fillComplete();
```

If only the values are changed, fillComplete does not need to recompute any graph metrics, nor check the structure of the graph, etc.  It really needs to do only globalAssemble.    But it does a lot of graph checking and recomputation of metrics.  This slows down operations that should be fast, such as scale and setAllToScalar.  

We could remove the requirement to resumeFill for these operations (as proposed in #9640), but the same performance hit would be felt when users are polite enough to call resumeFill / fillComplete when they use replace*Values or grab the values views and modify the values themselves.  And it won't help users who have the resumefill/fillComplete around scale or setAllToScalar because of the past checks.  (I'll argue that #9640 should still be done.)

Here's an example using a matrix from Xyce.  It does 100 calls to setAllToScalar.  The times for 100 calls are reported.  The fillComplete adds 33% overhead to the total time to setAllToScalar on one processor.  Since Epetra doesn't require the resumeFill and fillComplete, it doesn't add the same overhead.

one processor
```
CRS Init Epetra set all to scalar      7.581 (100)       
CRS Init Tpetra resumeFill             0.000124 (100)          
CRS Init Tpetra setAllToScalar call    7.585 (100)          
CRS Init Tpetra fillComplete           2.576 (100)          
CRS Init Tpetra Total Time            10.16 (100) 
```

four processors
```
CRS Init Epetra set all to scalar                           1.775 (100)       1.951 (100)        2.11 (100)         0.01951 (100)
CRS Init Tpetra resumeFill                                  5.96e-05 (100)    8.613e-05 (100)    0.0001209 (100)    8.613e-07 (100)
CRS Init Tpetra setAllToScalar call                         1.832 (100)       1.932 (100)        2.015 (100)        0.01932 (100)
CRS Init Tpetra FillComplete                                0.9604 (100)      4.217 (100)        5.979 (100)        0.04217 (100)
CRS Init Tpetra Total Time                                  2.94 (100)        6.149 (100)        7.881 (100)        0.06149 (100)
```

I propose that we add a flag modifiedGraph_ to CrsGraph that is  
- set to false in resumeFill;
- set to true in insert*Values or removeLocalIndices; 
- checked in fillComplete to avoid all the graph checking if false;  and
- set to false in fillComplete

TRILINOS-23

**Comment by tasmith4** [comment]
I support this -- it seems like a very reasonable proposal.

**Comment by brian-kelley** [comment]
I also think this is a good idea.
