### ISSUE TITLE
Amesos2:  Banded Parallel Solve

### ISSUE THREAD

**Issue by Adrian-Diaz** [trilinos/Trilinos#9675]
## Question
@trilinos/\<amesos2\>

Greetings,

I was wondering which of the amesos2 TPL interfaces has shown the best consistency and parallel performance when solving large linear systems with a sparse banded structure. Thanks for any info on the matter.

Adrian

**Comment by Adrian-Diaz** [comment]
@srajama1

**Comment by jhux2** [comment]
@trilinos/amesos2

**Comment by srajama1** [comment]
We do not interface any special solver for banded structure. That is more of an LAPACK functionality than a sparse functionality. Our standard sparse solvers typically do a decent job though.

**Comment by Adrian-Diaz** [comment]
No worries, I was more concerned with which tends to deliver the fastest runtime as the row count N gets large and we have many MPI ranks decomposing the problem.
