### ISSUE TITLE
ShyLUTacho does not appear to have tests

### ISSUE THREAD

**Issue by krcb** [trilinos/Trilinos#968]
ShyLUTacho builds code present in shylu/tacho/refactor by default; however, this code does not appear to have tests implemented. Code present in shylu/tacho/core does have tests implemented, but these fail to compile with errors such as:

packages/shylu/tacho/core/test/main_graphviz.cpp:4:45: fatal error: impl/Kokkos_Serial_TaskPolicy.hpp: No such file or directory
#include <impl/Kokkos_Serial_TaskPolicy.hpp>

Tests are needed in order to verify that the SuiteSparse refactor performed under #649 does not negatively impact ShyLUTacho.

**Comment by srajama1** [comment]
Kyungjoo, can you test against the pull request and give a thumbs up ?

**Comment by kyungjoo-kim** [comment]
You mean the pull request of "Remove Unnecessary Amesos2 dependence on Amesos Amesos Amesos2", right ?

**Comment by srajama1** [comment]
Yes.

**Comment by kyungjoo-kim** [comment]
Done. It compiles Tacho and the solver works correctly.

**Comment by srajama1** [comment]
I would still keep this open, so we remember to add tests to Tacho itself.

**Comment by kyungjoo-kim** [comment]
This is done now as we have real tests in tacho.
