### ISSUE TITLE
Framework: UVM off PR testing is much slower than other tests

### ISSUE THREAD

**Issue by jhux2** [trilinos/Trilinos#9698]
## Question/Comment
@trilinos/framework @jjellio 

I've observed that the UVM-off PR test is hours slower than all of the other PR tests (and hence is a bottleneck).   For example, in the testing for PR #9532,

https://testing.sandia.gov/cdash/index.php?project=Trilinos&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=63&value1=PR-9532-test&field2=buildstarttime&compare2=84&value2=NOW

there are two CUDA build/test instances on ride.  The instance PR-9532-test-Trilinos_pullrequest_cuda_10.1.105-2264 finished at least two hours before PR-9532-test-Trilinos_pullrequest_cuda_10.1.105_uvm_off-1259.

If the no-UVM build/test instance could be sped up, that would really help through-put.

**Comment by csiefer2** [comment]
@jjellio Is there anything in the build stats that can be used to diagnose this?

**Comment by jhux2** [comment]
One other fun tidbit.  The memory consumption is really high during testing, e.g.,

```
   PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
 86041 trilinos  20   0   22.5g 675840 295936 R  88.9  0.1   0:02.15 MueLu_Stratimik
 86042 trilinos  20   0   22.4g 683776 308288 R  88.9  0.1   0:02.16 MueLu_Stratimik
 86043 trilinos  20   0   22.4g 641280 280192 R  88.9  0.1   0:02.16 MueLu_Stratimik
 86044 trilinos  20   0   22.4g 665920 298176 R  88.9  0.1   0:02.15 MueLu_Stratimik
```

Maybe this is completely unrelated....

**Comment by jjellio** [comment]
I think so Chris,

I am not the best at writing the CDash queries to do this.

I believe something like
https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&begin=2021-09-01&end=2021-09-14&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=63&value1=PR-9532-test&field2=testname&compare2=61&value2=TrilinosBuildStats_Results&field3=testoutput&compare3=95&value3=elapsed_real_time_sec


Just glancing at two builds UVM vs UVM off:

(off)
https://testing.sandia.gov/cdash/test/93474796
vs 
(on)
https://testing.sandia.gov/cdash/test/93478349


off
Full Project: sum(elapsed_real_time_sec) = 296212.54 (11901 entries)
Full Project: max(elapsed_real_time_sec) = 1128.67 (packages/intrepid2/unit-test/performance/StructuredIntegration/CMakeFiles/Intrepid2_unit-test_performance_StructuredIntegration_StructuredIntegrationPerformance.dir/StructuredIntegrationPerformance.cpp.o)


vs
on
Full Project: sum(elapsed_real_time_sec) = 392210.85 (14670 entries)
Full Project: max(elapsed_real_time_sec) = 1065.45 (packages/amesos2/test/solvers/CMakeFiles/Amesos2_Solver_Test.dir/Solver_Test.cpp.o)

The CSV data is embedded and can be downloaded. I'm having trouble getting them to load (and I can't reset my VPN as Iam locked on a long call)


That doesn't seem to really capture the problem, but the csv files should point out what's wrong (maybe there is a query that can do it?)

**Comment by rppawlo** [comment]
Just an FYI - we added panzer to the uvm=off testing just today. So there should have been a big jump in time.

**Comment by jhux2** [comment]
> Just an FYI - we added panzer to the uvm=off testing just today. So there should have been a big jump in time.

For the build in question, Panzer is listed as explicitly disabled (https://testing.sandia.gov/cdash/build/9923736#Configure), so I don't think that's the reason.
