### ISSUE TITLE
libmuelu.a is Zero Length with Intel 15.5/16.1 Compiler when Building with Debug

### ISSUE THREAD

**Issue by nmhamster** [trilinos/Trilinos#97]
We have seen a few builds where libmuelu.a is zero length or 8 bytes in length when installed. The common situation appears to be with roughly the packages required for NALU but also when CMAKE_BUILD_TYPE is set to DEBUG and the compiler flags are set to -O3 -g. In all sightings so far we have been using either the Intel 15.3, 15.5 or 16.1 compilers. Looking at the object files some of these are quite large making me wonder if the collective size is exceeding limits somewhere in the archive/library building process. The result is that Muelu objects are not found in the library and linking fails. If CMAKE_BUILD_TYPE is set to RELEASE the library builds correctly and linking proceeds as expected.

**Comment by crtrott** [comment]
Can you post the relevant parts of the configure output (where it states what Tpetra and MueLu will instantiate?) In particular I like to know whether complex is enabled and whether more than one execution space enabled (i.e. Serial and OpenMP)?

**Comment by aprokop** [comment]
Can we get access to a build directory that fails like that? I would like to run the ar utility by hand to figure out the max size for such a failure. Also, I assume this is a static build?

**Comment by mhoemmen** [comment]
Just curious -- have you tried turning off some Tpetra instantiations?  For example:

```
Tpetra_INST_INT_INT:BOOL=OFF
Tpetra_INST_INT_LONG:BOOL=ON
Tpetra_INST_INT_LONG_LONG:BOOL=OFF
```

**Comment by jhux2** [comment]
Appears to be superceded by #1605.  Please reopen if this isn't the case.
