### ISSUE TITLE
SEACAS:  Compilation Error on Ubuntu 21.04

### ISSUE THREAD

**Issue by Nidish96** [trilinos/Trilinos#9703]
## Bug Report
@trilinos/SEACAS

### Description
I'm unable to compile SEACAS on ubuntu 21.04. I've installed the hdf5, netcdf, PnetCDF, openmpi, and matio provided by apt. Here are the versions:
hdf5 - 1.10.6
netcdf - 4.7.4
pnetcdf - 1.12.2
openmpi - 4.1.0
matio - 1.5.19

Here's the error I'm getting : 
`Scanning dependencies of target exo_format

[ 29%] Building C object packages/seacas/applications/exo_format/CMakeFiles/exo_format.dir/exo_format.c.o
[ 30%] Linking C static library libzoltan.a
[ 30%] Linking CXX executable exo_format
[ 30%] Building CXX object packages/seacas/libraries/suplib_cpp/CMakeFiles/suplib_cpp.dir/hwm.C.o
/usr/bin/ld: ../../libraries/exodus/libexodus.a(ex_utils.c.o): undefined reference to symbol 'H5get_libversion@@HDF5_SERIAL_1.8.7'
/usr/bin/ld: /lib/x86_64-linux-gnu/libhdf5_serial.so.103: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
[ 30%] Built target zoltan
make[2]: *** [packages/seacas/applications/exo_format/CMakeFiles/exo_format.dir/build.make:105: packages/seacas/applications/exo_format/exo_format] Error 1
make[1]: *** [CMakeFiles/Makefile2:4860: packages/seacas/applications/exo_format/CMakeFiles/exo_format.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....`

I have a feeling it's because of version mismatch of hdf5 but I wanted to see if this is something that can be fixed easily enough so I can use it with hdf5 1.10.1.

### Steps to Reproduce
1. Cmake build command:  `cmake -DTrilinos_ENABLE_SEACAS=ON -DTPL_ENABLE_MPI=ON -DCMAKE_INSTALL_PREFIX=$HOME/mysw ..`
2. Cmake log : [cmakebuild.log](https://github.com/trilinos/Trilinos/files/7172882/cmakebuild.log)
3. make log (I'm using `make -j4`):  [makelog.log](https://github.com/trilinos/Trilinos/files/7172884/makelog.log)

**Comment by jhux2** [comment]
@trilinos/seacas

**Comment by gsjaardema** [comment]
It looks like is it somehow finding a different hdf5 include file and library file between compile time and link time.  

It also looks like the configure is finding a system-installed netcdf instead of the version you installed (from cmakebuild.log):
```
-- Using FIND_PACKAGE(Netcdf ...) ...
-- NetCDF include file /usr/include/netcdf.h will be searched for define values
-- NetCDF does not require HDF5
-- NetCDF does not require PNetCDF
-- Found NetCDF: /usr/lib/x86_64-linux-gnu/libnetcdf.so  
-- NetCDF Version: 
-- 	NetCDF_NEEDS_HDF5        = 
-- 	NetCDF_NEEDS_PNetCDF     = 
```
I think that if it can find the correct netCDF library, then (assuming shared libraries), then it might also pick up the correct hdf5 library...

Are you specifying the `NetCDF_ROOT` and `HDF5_ROOT` paths during your cmake config?  These _should_ help CMake in finding the correct installations...

**Comment by Dragon20180618** [comment]
Add the option may solve your question。I got the simaliar question。
-DTrilinos_EXTRA_LINK_FLAGS:STRING="-L<hdf_lib_path> -lhdf5 "

**Comment by gsjaardema** [comment]
This should be working now.  We have a github actions rule that is building on Ubuntu 22.04LTS.  Please reopen if you are still having a problem with this

**Comment by s-kanaev** [comment]
@gsjaardema , FYI this issue takes place on Fedora 34 as well. Solution from @DragonPara helped to mitigate it locally.
