### ISSUE TITLE
BELOS:  Strange throw at computing linear system at 2 or more threads

### ISSUE THREAD

**Issue by WhiteFang13** [trilinos/Trilinos#9707]
## Bug Report
@trilinos/belos

### Description
We solve linear equations system Ax = b. 
If we use only 1 mpi process for solving, the code is working well, but using 2 or more mpi processes (matrices A and b are the same) the exception is thrown: “Belos::StatusTestImpResNorm::checkStatus(): One or more of the current implicit residual norms is NaN.”. 
But matrices A and b do not contain “nan” values, that is confirmed by system solving using 1 mpi process. 

### Steps to Reproduce
Files A.txt and B.txt contain A and B configuration cause such behaviour.
Files main.cpp, LinearEquationSolver.h, LinearEquationSolver.cpp contain code that we run.
(First process is used as a root process in this code)

Files are uploaded here: https://github.com/WhiteFang13/Files-for-trilinos-bug.git

Looking for your answers!

**Comment by hkthorn** [comment]
@WhiteFang13 Can you include the cmake script with your files so we can see what options you used?  That helps reproduce the issue.

**Comment by cgcgcg** [comment]
@WhiteFang13 Is that system maybe singular?

**Comment by WhiteFang13** [comment]
> @WhiteFang13 Is that system maybe singular?
I've added the file CMakeList.txt into the repository by the link above.

**Comment by WhiteFang13** [comment]
@hkthorn I've added the file CMakeList.txt into the repository by the link above.

**Comment by WhiteFang13** [comment]
@cgcgcg The matrix should be not singular as it is successfully solved by 1 solving process (and the 2d process is managing). But we will calculate the matrix determinant, and will verify its solution obtained by 1 solving process.

**Comment by WhiteFang13** [comment]
@cgcgcg The determinant is actually zero. Thank you, we will change the matrix.

Then, the issue shifts to the question, why belos gives us a correct solution at 1 solving process, and the behaviour is different at few processes.

**Comment by cgcgcg** [comment]
I guess you could have gotten lucky in that you somehow ended up in the complement of the nullspace. Also, keep in mind that the preconditioner is different on 1 and 2 ranks.

**Comment by WhiteFang13** [comment]
@cgcgcg Should we use preconditioner as Teuchos::RCP instead of static variable, do you think that?

**Comment by cgcgcg** [comment]
No, the factorization preconditioner is essentially block diagonal by MPI rank (plus some overlap). So on one rank, it is constructed for the entire matrix, but one two ranks each rank essentially only inverts a diagonal block of half the matrix size.

**Comment by WhiteFang13** [comment]
@cgcgcg Do you know any trilinos tools for calculation of the ranks and determinants of custom matrices? The "hand" calculations give us strange results.

**Comment by WhiteFang13** [comment]
Thanks everyone, we solved the issue, the problem was in our matrices.
