### ISSUE TITLE
Ifpack2: update user guide with new block relaxation options

### ISSUE THREAD

**Issue by jhux2** [trilinos/Trilinos#971]
@trilinos/ifpack2 The Ifpack2 user's guide should be updated to reflect changes in options to block relaxation.

**Comment by aprokop** [comment]
@jhux2 Are there any other updates pending?

**Comment by jhux2** [comment]
Possibly.  There might be new options for the sparse triangular solve and the various threaded solvers.

**Comment by srajama1** [comment]
See #288 that @mhoemmen fixed. Thanks, Mark !!

Is the user guide in the repo the most current one, so whoever adds a new solver/preconditioner can add to it ?

**Comment by jhux2** [comment]
> Is the user guide in the repo the most current one, so whoever adds a new solver/preconditioner can add to it ?

@srajama1 Yes, the repo is the most current one.

**Comment by srajama1** [comment]
Alright, it is easy to modify then. Thanks !
