### ISSUE TITLE
Teuchos_CommandLineProcessor.hpp:  Ability to optionally know which options were selected by the user

### ISSUE THREAD

**Issue by tonyskjellum** [trilinos/Trilinos#9719]
## Enhancement
@trilinos/\<Teuchos_CommandLineProcessor.hpp:\>

The ability to parse command lines is great.  However, knowing what command line options were selected is semantically independent of changing from a default value for cases where a value is selected, even if it is a bool value.  There is no apparent way to know this, only to test if default values have changed.  The mere presence of the command line option can be used to override config files if known to be selected, even if selected with a default value, but only if we know the option was indeed selected.  After reading the APIs, I conclude that can't get that info as coded.  This would add an optional argument (out bool) to the APIs.

**Comment by jhux2** [comment]
@trilinos/teuchos

**Comment by bartlettroscoe** [comment]
Just seeing this now (after the above auto-close comment).  Sorry this was never responded to.
