### ISSUE TITLE
Ifpack2: BlockRelaxation OverlappingPartition unit test fails after being reenabled

### ISSUE THREAD

**Issue by jhux2** [trilinos/Trilinos#972]
The test OverlappingPartition has been disabled since last fall (commit 06bf1ead).  The test compares convergence of two versions of overlapping block Gauss Seidel against point Gauss Seidel.  The two block versions use dense and sparse block solves, respectively.

After being reenabled, the dense block solve fails (convergence stagnates immediately), whereas the sparse block solve converges acceptably.   Is the dense block solve known to work properly?

It's entirely possible that I've missed setting an option, although I don't see any special settings in the other unit tests.

@trilinos/ifpack2 @brian-kelley

**Comment by jhux2** [comment]
I just reenabled this test in commit 81719a67, but I had to comment out comparisons involving the solution from the dense block solve.

**Comment by brian-kelley** [comment]
I just pushed a patch that fixed the problem and fully re-enabled the test.

**Comment by jhux2** [comment]
Thanks @brian-kelley!
