### ISSUE TITLE
Amesos2:  Compiling with MUMPS

### ISSUE THREAD

**Issue by Adrian-Diaz** [trilinos/Trilinos#9729]
## Question
@trilinos/\<amesos2>

Greetings,

I was trying to compile Amesos2 with support for MUMPS using the attached cmake configure file, however when I try to compile my application, using the attached cmake list which imports compiler settings from Trilinos, it gives the following error at link time:

"undefined reference to symbol '_gfortran_transfer_real_write@@GFORTRAN_8'"

Does anyone know how to alter the configure settings to encompass that?

Thanks for any help,
Adrian Diaz
[cmake_configure_mumps_parallel.txt](https://github.com/trilinos/Trilinos/files/7212866/cmake_configure_mumps_parallel.txt)

[CMakeLists.txt](https://github.com/trilinos/Trilinos/files/7212904/CMakeLists.txt)

**Comment by jhux2** [comment]
@trilinos/amesos2 @ndellingwood

**Comment by srajama1** [comment]
Is libgfortran.a available and can you try linking to it directly with -lgfortan ?

**Comment by Adrian-Diaz** [comment]
If I specify the path to libgfortran in the cmake link libraries then it complains about quadmath_snprintf

**Comment by jhux2** [comment]
Try adding `-lquadmath` (for libquadmath).

**Comment by Adrian-Diaz** [comment]
Yea I tried that and then it couldn't find the mpi fortran library either for some reason even though it should be linked to the target.

**Comment by Adrian-Diaz** [comment]
Currently I'm using the following top level list and lower level list for the executable


[CMakeListsupper.txt](https://github.com/trilinos/Trilinos/files/7219694/CMakeListsupper.txt)


[CMakeLists.txt](https://github.com/trilinos/Trilinos/files/7219697/CMakeLists.txt)

**Comment by Adrian-Diaz** [comment]
I got it to link mpif90 with set_property(TARGET main PROPERTY LINKER_LANGUAGE Fortran) but now it seems numroc_ and some other scalapack routines aren't being linked.

**Comment by srajama1** [comment]
I don't think that is the correct way (turning on Trilinos modules so Scalapack routines are automatically found). Notice that most of these are MUMPS dependencies. The clean way that I like to think about this APP depends on MUMPS and Trilinos. MUMPS and Trilinos have their own dependencies. When you compile and link APP, both MUMPS and dependencies should be linked in the right order. However, it is hard to provide a Trilinos install option that can recursively handle all TPL dependencies, if I understand what you are asking.

SDKs like xSDK are partially going in this direction, but I don't think MUMPS is part of it.

**Comment by keitat** [comment]
At this moment, MUMPS is not part of xSDK.  I really wish MUMPS provides clean CMAKE script (cmake.config) to describe ScaLAPACK dependencies so that any libraries and applications dependent on MUMPS can handle both MUMPS and ScaLAPACK (plus Fortran runtime) in a right order.

**Comment by Adrian-Diaz** [comment]
I managed to get it to compile, thanks for the help!

**Comment by srajama1** [comment]
@Adrian-Diaz Can you post all the stumbing blocks and steps you did here? We can keep that in a wiki for future users. Trilinos.github.io willl be a good place to maintain this.

**Comment by Adrian-Diaz** [comment]
Well I haven't been able to get it to scale in parallel yet the way I have things configured (I'm getting like 10% efficiency to 16 ranks) so I'm not sure everything is fine.  However as far as getting the compiler to declare victory I did the following.

1: I downloaded mumps from https://github.com/scivision/mumps and used "cmake -B build" in the topmost directory; this automatically leaves a build folder with the libs and some include directories.

2: Then in the Trilinos build folder I added the following to my cmake configure script: 
-DTPL_ENABLE_MUMPS=ON 
-DTPL_MUMPS_INCLUDE_DIRS="/mnt/c/MUMPS/mumps/include/;/mnt/c/MUMPS/mumps/build/_deps/mumps-build/src/include/;/mnt/c/MUMPS/mumps/build/_deps/mumps-src/include/" \
-DTPL_MUMPS_LIBRARIES="/mnt/c/MUMPS/mumps/build/libsmumps.a;/mnt/c/MUMPS/mumps/build/libdmumps.a;/mnt/c/MUMPS/mumps/build/libmumps_common.a;/mnt/c/MUMPS/mumps/build/libpord.a" \

3. Then in my application cmake list I had to force it to link to the mpif90 compiler with "enable_language(Fortran)" and "set_property(TARGET main PROPERTY LINKER_LANGUAGE Fortran)" after linking the other Trilinos library variables seen in the demo build script.

4. Last was linking against the Scalapack lib files:
target_link_libraries(main /mnt/c/Scalapack/scalapack/build/libscalapack.a)
target_link_libraries(main /mnt/c/Scalapack/scalapack/build/libblacs.a)
