### ISSUE TITLE
Zoltan2: Add example showing graph repartitioning for a sparse matrix, followed by an iterative solve

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#973]
@trilinos/zoltan2 @vbrunini requests this.

**Comment by mhoemmen** [comment]
I suggested that @vbrunini get in touch with @mmwolf to ask about 2-D distributions.  @vbrunini will first look at using @trilinos/zoltan2 with 1-D distributions.  If that doesn't improve performance sufficiently, @vbrunini would like to explore 2-D distributions.

**Comment by kddevin** [comment]
Hi, @vbrunini .

For which capabilities are you interested in having an example?  matrix partitioning?  matrix redistribution?  vector redistribution?

We have a test program zoltan2/test/partition/partitioning1.cpp that partitions a matrix, redistributes it and an associated vector, does matrix-vector multiplication with both the original and redistributed matrices and vectors, and compares the results to verify that the redistribution is correct.  Would that be sufficient?

Adding a linear solve to the example would complicate the Trilinos dependencies.  Zoltan2 does not currently depend on Belos, but we would need to depend on it if we added a linear solve to the example.  I'd rather not add this dependence, if possible. There are Belos examples showing how to do a linear solve when given a Tpetra matrix and vector.

**Comment by kddevin** [comment]
"improve performance" of what?  What is the matrix structure?  Typical FEM?  Something more dense?  More irregular?

**Comment by egboman** [comment]
Does "iterative solve" include preconditioning? Partitioners typically partition to optimize SpMV. The effect on preconditioners is often unpredictable.

**Comment by mhoemmen** [comment]
@kddevin wrote:
> We have a test program zoltan2/test/partition/partitioning1.cpp that partitions a matrix, redistributes it and an associated vector, does matrix-vector multiplication with both the original and redistributed matrices and vectors, and compares the results to verify that the redistribution is correct. Would that be sufficient?

I should let @vbrunini speak for himself, but I'm happy to find out about that example, so thanks! :-D

@egboman wrote:
> Does "iterative solve" include preconditioning? Partitioners typically partition to optimize SpMV. The effect on preconditioners is often unpredictable.

@vbrunini uses a simple Jacobi preconditioner.  (The only reason repartitioning could be worthwhile is because he reuses the graph over many linear solvers.)  The one issue there is that Ifpack2::Relaxation currently assumes a 1-D matrix distribution when it extracts the matrix's diagonal entries.  Users could get around this by supplying their own diagonal entries (as a Tpetra::Vector).

**Comment by mhoemmen** [comment]
Tpetra's support for 2-D distributions exists, but is a bit weak, and redistribution from 1-D to 2-D moves more data than it needs to move.  The latter is a cost that @vbrunini would have to pay for _each_ linear solve, since he assembles into a 1-D - distributed matrix first.  I can fix this in Tpetra, but it would take a me a while, and I would have to be careful to avoid making the common case of global assembly for 1-D - distributed matrices more expensive than it is now.  Thus, I pointed @vbrunini to Zoltan2's repartitioning technology to see whether it can help.

**Comment by vbrunini** [comment]
That example looks helpful thanks.

This is for a radiosity solution method so the matrices are much more dense than typical FEM. The range I've seen in practice is ~5% dense up to ~95% dense and the sparsity patterns are not regular. Typically our larger problems are on the less dense end of that spectrum. As Mark mentioned no complex preconditioning is used, each solve generally only needs a handful of iterations with either Jacobi or no preconditioning at all.

As a first go I'd like to just look at a 1D distribution with Tpetra and using Zoltan to load balance, but as Mark said I may be interested in 2D distributions depending on how that goes.

I was initially interested in a simple driver program to read a matrix market file, do the Zoltan partitioning and solve that I could use for some quick performance exploration, but I don't think it would be too bad to combine the Zoltan example with a Belos example to do that myself.

**Comment by srajama1** [comment]
@vbrunini : 1D is a good starting point. Whether you want 2D or not depends not just on the structure, but also on the scale you want to run on. At smaller scale (O(100) ranks), 1D will be competitive. If you need runs at a larger scale, especially with problems that have interesting non-zero pattern then 2D could be worth your time.

**Comment by kddevin** [comment]
Thanks for the extra details, @vbrunini .
I agree with @srajama1 and @egboman that starting with 1D is best.  

The default in Zoltan2 is to assign equal numbers of rows per part; for FEM, most rows have roughly the same number of nonzeros, so the balance is the same whether we account for nonzeros or not.

If you have widely varying numbers of nonzeros per row, you might want to weight rows by the number of their nonzeros.  There is a function setWeightIsDegree in Zoltan2 to set these weights automatically.  In the partitioning1.cpp test (near line 227), we have some code for setting artificial weights that we use for testing; you don't want to use that code.  Instead, you'd want to call 
adapter.setWeightIsDegree(0).  

If you want some help with this example, please let me know.  I'm happy to help.

In the meantime, I think there is nothing new needed from Zoltan2 for this issue, so I will close it.  If I am wrong, please reopen.  Thanks.

**Comment by vbrunini** [comment]
I'm trying this out and I think I've found a bug in Zoltan2_XpetraCrsMatrixAdapter when using it with a matrix whose row graph has a non-zero indexBase. In the constructor it sets:
`base_ = rowMap_->getIndexBase();`
and then later in a loop over the number of local rows does:
`
    lno_t row = i + base_;
    nnz = matrix_->getNumEntriesInLocalRow(row);
    matrix_->getLocalRowView(row, indices, nzs);
`
which can end up with row being an invalid local row ID. I think base_ should be set to `rowMap_->getMinLocalIndex()` here, though I'm not sure if it is used anywhere else in the class.

**Comment by kddevin** [comment]
I will look at this issue this week; @vbrunini will share a matrix exhibiting the problem.

**Comment by kddevin** [comment]
Actually, I think we shouldn't use base_ at all in this context.  We access only local row data (getNumEntriesInLocalRow, getLocalRowView); thus a local (zero-based) index should be used as the function arguments.  Thus, it should be row = i.

It appears we were not testing cases with row global IDs not starting at zero.  I will add a test and fix this code appropriately.

@vbrunini Thank you for reporting this problem.

**Comment by kddevin** [comment]
@vbrunini I believe this bug is fixed.  Thanks for bringing it to my attention.
I also disabled "tolerant" matrix-market reading in our test program, as it was causing the matrix file with IDs outside the range of the number of rows that you sent me to be expanded into a much larger matrix (size maxID rather than number of rows) that didn't represent the structure you wanted.
