### ISSUE TITLE
Muelu:  Is IsolatedNodeAggregationAlgorithm deprecated ?

### ISSUE THREAD

**Issue by mperrinel** [trilinos/Trilinos#9732]
## Question
@trilinos/\<Muelu\>

I want to verify that the IsolatedNodeAggregationAlgorithm (Muelu package) still makes sense to stay on Trilinos.
1) I don't think that any class of Trilinos uses it
2) According to a comment on this PR #9695 it seems to be inactive since 2015.
3) According to this commit : https://github.com/trilinos/Trilinos/commit/7e892ecb58513a6e6f9017f1e277915713a8f008#diff-4abf20d14b91dda5281d2427a0075a78ed80ca9a39342e1362fd3ccba6f741ef , an effort has been done to remove it uses from the UncoupledAggregationFactory

I'm working on the code coverage of the Muelu package and I don't know if that makes sense to test it anymore.

**Comment by jhux2** [comment]
@trilinos/muelu

**Comment by mayrmt** [comment]
I agree with @lucbv's comment in PR #9695 that isolated nodes are not boundary nodes and, thus, should not be mislabeled as boundary nodes. Following this philosophy, MueLu would need to keep (or revive) the IsolatedNodeAggregationAlgorithm. However, there possibly other opinions on that...
