### ISSUE TITLE
MueLu::LWGraph : problem with objectLabel_ attribut

### ISSUE THREAD

**Issue by mperrinel** [trilinos/Trilinos#9734]
## Bug Report
@trilinos/\<MueLu::LWGraph\> kokkos and no kokkos version

### Description

Both of MueLu_LWGraph_decl.hpp and MueLu_LWGraph_kokkos_decl.hpp files hold the name of a graph as an attribute that way:
` //! Name of this graph.
    const std::string& objectLabel_;`

Both of the LWGraph and LWGraph_kokkos constructors set this attribute like that : 
`objectLabel_(objectLabel)` where the parameter objectLabel is of type "const std::string&"

As a consequence, "objectLabel_" and the parameter "objectLabel" refer to the same std::string object. When the string object is destroyed, the objectLabel_ is not available anymore and the method "description()" (which simply return a string using objectLabel_) makes crash the runtime.
Do we have any reason to keep the objectLabel_ with a reference as a type ?
We can simply fix it by ensuring that objectLabel_ is a copy of the parameter provided to the constructor by removing the reference : 
`const std::string& objectLabel_ ` would become `const std::string objectLabel_`

I'm currently working on the code coverage of the MueLu package and I saw this problem when I cover the description method inside the LWGraph unit test.

**Comment by jhux2** [comment]
@trilinos/muelu
