### ISSUE TITLE
Teuchos:  Add option to barrier/fence timers

### ISSUE THREAD

**Issue by jewatkins** [trilinos/Trilinos#9765]
## Question
@trilinos/teuchos 

Teuchos timer regions can sometimes be misleading when an mpi rank has to wait for other ranks or `CUDA_LAUNCH_BLOCKING` is off and there's no `fence` to stop a rank from continuing. This is based on some runs I performed while looking at #6079. Is it possible to add an option to add barriers/fences within a timed region? There's probably multiple ways of implementing this and there's probably issues so it'd be good to get some discussion. Maybe something like this:
```
    Kokkos::fence();
    MPI_Barrier(comm);
    Kokkos::Timer timer;
    func();
    Kokkos::fence();
    double time = timer.seconds();
```
I could see something similar being done for the stacked timer start/stop and wrapping the fence/barrier with a run-time/compile-time option.

This is preventing us from turning off `CUDA_LAUNCH_BLOCKING` completely.

**Comment by csiefer2** [comment]
If Kokkos profiling is enabled, Teuchos timers include Kokkos profile regions, which will fence.

**Comment by jewatkins** [comment]
Perfect, that might be all I need to stop using `CUDA_LAUNCH_BLOCKING`. Any ideas for misleading timers when an mpi rank has to wait for other ranks? It makes it difficult to see which region has issues.

**Comment by jewatkins** [comment]
Also, is Kokkos profiling a runtime option?

**Comment by jhux2** [comment]
> Any ideas for misleading timers when an mpi rank has to wait for other ranks? It makes it difficult to see which region has issues.

@jewatkins You could either look at min/max/avg, or if using stacked timers, the timer histogram.  Would that be sufficient for your needs?

**Comment by iyamazaki** [comment]
If there are load-imbalance among MPI processes, I was wondering how that will show up.. We've seen load imbalance in compute (e.g., local SuperLU with an irregular mesh), but because we did not have `MPI_Barrier` before solve, the imbalance could also show up in solve (e.g., with GMRES's orthogonalization)?

**Comment by jewatkins** [comment]
@jhux2 that's usually what I do. If a particular timer region has an mpi barrier and I see the min is small but the average is large, than I assume (although probably not always true) that there's one or more ranks waiting for a rank to "catch up". As @iyamazaki mentioned, there might be a timer region with load imbalance but it's not clear which one it could be (or whether the imbalance is even captured in a timer region). I think a well place mpi barrier before the timer region at least rules out specific regions from being the issue. It would be good to have that as a runtime option instead of having to manually add the barrier and rebuild.

**Comment by jhux2** [comment]
@jewatkins Fwiw, MueLu has a runtime option to add barriers to its timers.

**Comment by jewatkins** [comment]
> > Also, is Kokkos profiling a runtime option?
> 
> Yes. You just need to set the right environment variable to point to the Kokkos profiling library of your choice.
> 
> See: https://github.com/kokkos/kokkos-tools/wiki

Ah okay, I was thinking of a runtime option to just turn on timer fencing without having to build/use a kokkos profiling tool that will not be used. Victor suggested this already. I think I'm 0/2 so far on making this a thing :(

**Comment by jewatkins** [comment]
> @jewatkins Fwiw, MueLu has a runtime option to add barriers to its timers.

Very nice, I'll have to try that. If it's in Teuchos, maybe we can avoid having to do that for all packages?

**Comment by rppawlo** [comment]
@jewatkins - there are runtime functions you can call to set the profiler in kokkos to avoid having to export env variables. We do this in empire to set our own profiler tools. I can show you this after our meeting later today.

**Comment by cgcgcg** [comment]
There is also a `Teuchos::SyncTimeMonitor`. But I don't think there is a global option to swap that in for the regular time monitor.
