### ISSUE TITLE
Ifpack: Compile Time Error with ifpack-hypre interface

### ISSUE THREAD

**Issue by keitat** [trilinos/Trilinos#9788]
## Bug Report
@trilinos/ifpack 

### Description
After the change in the data type definitions in Hyper package at LLNL, we see compile time error at Ifpack's hype interface.   Ifpack is a 1st-gen package, and I believe that nobody is using this capability/interface.  Should we remove this or still change the source to support the new versions of Hypre?  

### Steps to Reproduce
See https://github.com/xsdk-project/xsdk-issues/issues/157#issuecomment-938003490

**Comment by cgcgcg** [comment]
I think we can just comment out that particular call.

**Comment by csiefer2** [comment]
Not in Trilinios, you can't.  We use that.

**Comment by cgcgcg** [comment]
Should be fixed. Please reopen if this is still an issue.
