### ISSUE TITLE
KokkosKernels: Graph coloring test fails

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#979]
@trilinos/tpetra @trilinos/ifpack2 
The KokkosKernels graph coloring test fails with the following run-time error:
```
terminate called after throwing an instance of 'std::runtime_error'
11:   what():  Kokkos::OpenMP parallel_for ERROR: not initialized
11: Traceback functionality not available
```
This looks pretty easy to fix.  Somewhere, something is not initializing Kokkos::OpenMP.

I am disabling the test for now to ensure that I can proceed with #288.

**Comment by mndevec** [comment]
This should be fixed, closing for now.
