### ISSUE TITLE
Remove Tribits dependencies in KokkosKernels

### ISSUE THREAD

**Issue by srajama1** [trilinos/Trilinos#981]
There are bunch of tribits related dependencies that has come into KokkosKernels. Eventually we would like a Kokkos model where we could build without Tribits and test with gtest. This needs a cleanup.

@mndevec @crtrott @mhoemmen

**Comment by mhoemmen** [comment]
The "test with gtest" bit isn't so hard.  We could put a copy of gtest in the new Trilinos package for TPLs, and just point tests to it.  Since only tests use it, there shouldn't be any conflicts with Kokkos' version of gtest.

Does "build without TriBITS" mean a CMake build, or a Makefile build?

**Comment by srajama1** [comment]
Just to be consistent same as Kokkos, which I believe is just Make outside Trilinos.

@crtrott : Is there a plan to support CMake in Kokkos outside Trilinos as well ?
