### ISSUE TITLE
Amesos2: Parallel Solve with Equilibration

### ISSUE THREAD

**Issue by Adrian-Diaz** [trilinos/Trilinos#9814]
## Question
@trilinos/\<PackageName\>

Greetings,

Is there a way to tell Amesos2, or another Trilinos package that can do so before the solve, to equilibrate the system (lower the condition number) when solving with SuperLUDist? or any other of the parallel solver interfaces. Thanks for any info.

Adrian Diaz

**Comment by jhux2** [comment]
@trilinos/amesos2 @iyamazaki

**Comment by iyamazaki** [comment]
I had to do something like:
```
Teuchos::ParameterList amesos2_params("Amesos2");`
auto superlu_params = Teuchos::sublist(Teuchos::rcpFromRef(amesos2_params), "SuperLU_DIST");
superlu_params->set("Equil", equil);
solver->setParameters( Teuchos::rcpFromRef(amesos2_params) );
```
`Equil` may help but may not solve all the accuracy issue.

I only enabled the matrix col & row scaling. SuperLU_Dist has another option that permutes the large nonzero entries to diagonal before scaling the matrix. I have not enabled this option for a couple of reasons, but we can also look into that..

**Comment by iyamazaki** [comment]
Yay @Adrian-Diaz. Let us know if you see any other issues. I can close this issue once [PR #9824](https://github.com/trilinos/Trilinos/pull/9824) get merged.
