### ISSUE TITLE
PR autotesting reports time outs

### ISSUE THREAD

**Issue by jhux2** [trilinos/Trilinos#9818]
## Bug Report
@trilinos/framework 

### Description
In at least some PR's, the tests are failing due to timeouts.

<img width="956" alt="Screen Shot 2021-10-15 at 8 39 12 AM" src="https://user-images.githubusercontent.com/12970120/137514975-f1b7ec66-0509-4507-8a8a-0b8921ab851c.png">

For example
  https://github.com/trilinos/Trilinos/pull/9811
  https://github.com/trilinos/Trilinos/pull/9683

**Comment by jwillenbring** [comment]
Jobs were not timing out properly. A bunch of hanging jobs were filing the queue. It is possible there is more going on here, but for the time being I have emptied hanging jobs out of the queue.
