### ISSUE TITLE
KokkosKernels: Graph coloring uses Serial execution space for OpenMP view

### ISSUE THREAD

**Issue by jjellio** [trilinos/Trilinos#985]
In
/src/Trilinos/packages/tpetra/kernels/perf_test/graph/KokkosKernels_GraphColoringTest.cpp

On lines 176 and 236, the test creates views using Kokkos::Serial, but this is inside of the region guarded for OpenMP, e.g., #if defined( KOKKOS_HAVE_OPENMP ).

That is, these tests will fail to compile if OpenMP is enabled and Serial is disabled.

Edited to mention tpetra as there is not a project for KokkosKernels.
@trilinos/tpetra @mndevec

**Comment by mndevec** [comment]
Thanks James, those were for stress testing. 
I changed the Serial to HostSpace instead.
