### ISSUE TITLE
Tpetra:  Distributor claims to support Isend, Rsend, Ssend, but all Tpetra tests use Send

### ISSUE THREAD

**Issue by kddevin** [trilinos/Trilinos#9852]
## Bug Report
@trilinos/tpetra 

### Description

Tpetra's Distributor takes parameters a "Send type" and "Barrier between receives and sends."   The default values are 
```
Send type = Send (for MPI_Send)
Barrier between receives and sends = false
```
No Tpetra tests exercise other available options (Send type = Isend, Rsend, Ssend).  
No Trilinos methods explicitly set "Send type," although @trilinos/frosch allows users to pass through a value.

@trilinos/tpetra should either deprecate support for these methods OR add tests for them.

Question for
@rppawlo @iyamazaki @trilinos/muelu @trilinos/belos @trilinos/panzer @mperego @ikalash @crdohrm @vbrunini @jclause @japlews @tcfisher  @searhein  : 

**Do you use "Send type" or "Barrier between..."?**

**Comment by ikalash** [comment]
I think @bartgol, @mperego or @jewatkins can best answer this for Albany.
