### ISSUE TITLE
KokkosKernels: Gauss-Seidel test fails with CUDA

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#988]
@trilinos/tpetra @trilinos/ifpack2 

The Gauss-Seidel test that I reenabled as part of #977 fails in a CUDA debug build for me, with CUDA 7.5 and GCC 4.8.4.  It passes in a non-CUDA Clang 3.9 build with Kokkos::Serial.  The error messages look like this:  
```
result_norm_res:3.05254e+36 initial_norm_res:160.873
3: .../Trilinos/packages/tpetra/kernels/unit_test/graph/KokkosKernels_Test_GaussSeidel.cpp:219: Failure
3: Value of: (result_norm_res < initial_norm_res)
3:   Actual: false
3: Expected: true
```

**Comment by mhoemmen** [comment]
The test does not yet build by default.  To make it build and run, one must edit tpetra/kernels/unit_test/graph/CMakeLists.txt.

**Comment by mndevec** [comment]
Mark, which test is this? If it is Si2.mtx, it is not supposed to work, as it is not diagonally dominant.

**Comment by mhoemmen** [comment]
> Mark, which test is this? If it is Si2.mtx, it is not supposed to work, as it is not diagonally dominant. That test should not be enabled.

Let me check.  Do you need that matrix for other tests?  If not, I'll delete it from the repo.  Thanks!

**Comment by mndevec** [comment]
That matrix is one of the three matrices where SPGEMM and coloring is tested. I wanted to test GaussSeidel too, but I realized gauss seidel won't work on that matrix afterwards. 

You can remove the matrix, but it is currently used for other tests.

**Comment by mhoemmen** [comment]
I'll leave the matrix.  No worries then!  I'll make sure only that test fails, and if that's the case, I'll disable that test and close this issue.

**Comment by mndevec** [comment]
I am closing the issue for now. This should be fixed.
