### ISSUE TITLE
How to solve Ax=b iterativelly with azetoo on each mesh block.

### ISSUE THREAD

**Issue by ztdepztdep** [trilinos/Trilinos#9889]
I  am developing a flow solve based on a multiblock mesh system. I need to solve Ax=b iteratively on each mesh block separately( I have total of 9 mesh blocks and  each block corresponds to 1 cpu ).  I have successfully resolved this by solving Ax=b with KLU direct solver.  But the Aztecoo solver can not run separately on each cpu, it must run parallelly with 9 cpus together.  
  Could you please give me some suggestions about this problem. 
The error is :
```
      Error: Communicator not set. Use AZ_set_comm()
       (e.g. AZ_set_comm(proc_config,MPI_COMM_WORLD)).
    AztecOO::SetProcConfig ERROR, failed to dynamic_cast Comm to Epetra_MpiComm.
```

**Comment by ccober6** [comment]
@trilinos/aztecoo
