### ISSUE TITLE
Kokkos: CMake Error (ADD_LIBRARY): add_library cannot create target "trilinos_kokkos_gtest" because another   target with the same name already exists.

### ISSUE THREAD

**Issue by nschloe** [trilinos/Trilinos#990]
When configuring Trilinos from master, I'm getting
```
Processing enabled package: Tpetra (Classic, Kernels, TSQR, Core, Tests)
-- Tpetra execution space availability (ON means available): 
--   - Serial:  ON
--   - Threads: OFF
--   - OpenMP:  OFF
--   - Cuda:    OFF
-- Setting default Node to Kokkos::Compat::KokkosSerialWrapperNode.
CMake Error at cmake/tribits/core/package_arch/TribitsLibraryMacros.cmake:731 (ADD_LIBRARY):
  add_library cannot create target "trilinos_kokkos_gtest" because another
  target with the same name already exists.  The existing target is a shared
  library created in source directory
  "/home/nschloe/software/trilinos/source-upstream/packages/kokkos/core/unit_test".
  See documentation for policy CMP0002 for more details.
Call Stack (most recent call first):
  packages/tpetra/kernels/unit_test/graph/CMakeLists.txt:13 (TRIBITS_ADD_LIBRARY)
```
and the configuration fails.

**Comment by jwillenbring** [comment]
@bartlettroscoe @crtrott - I thought you guys should see this.

**Comment by mndevec** [comment]
@mhoemmen  

This is the same error I was getting in the case of TpetraKernels Tests are enabled while Kokkos tests are not enabled. 

This is related to #759, I will disable the experimental unit tests for now.

**Comment by mndevec** [comment]
@mhoemmen 
Looking at the error again, I  think Mark fix this in develop branch in commit 6c36aca653e432dd432b2f44fe2e75fffa335821

**Comment by mhoemmen** [comment]
@mndevec That's right, I fixed this in develop.

**Comment by nschloe** [comment]
Thanks for the clarification. What's the relationship of master and development branch btw?

**Comment by bartlettroscoe** [comment]
> What's the relationship of master and development branch btw?

* https://github.com/trilinos/Trilinos/wiki/VC-(VERSION-CONTROL)
* https://github.com/trilinos/Trilinos/wiki/VC-%7C-'develop'-'master'-workflow

**Comment by nschloe** [comment]
Any chance this change will land in master soon? (After all master is broken atm.)

**Comment by jwillenbring** [comment]
master was updated earlier today.
