### ISSUE TITLE
Treatment of 'deprecated' warnings in builds

### ISSUE THREAD

**Issue by dridzal** [trilinos/Trilinos#991]
@trilinos/framework  @trilinos/muelu  @trilinos/tpetra 
The @trilinos/rol team has been seeing this warning for several months, so it may be good to register this as an issue (or at least document it).  We don't know if this is related to the internal compiler error (see below) --probably not.  In any case, it was my understanding that we needed to keep the nightly builds clean of any warnings.  If 'deprecated' doesn't fall into this category, should we not disable such warnings in said builds?  Please advise on policy.

http://testing.sandia.gov/cdash/viewBuildError.php?type=0&buildid=2694326

In file included from /data/jenkins/slave/workspace/Trilinos_continuous/CONTINUOUS_MPI_OPT_DEV_SHARED/Trilinos/packages/muelu/src/Interface/../Utils/MueLu_Utilities_decl.hpp:59:0,
                 from /data/jenkins/slave/workspace/Trilinos_continuous/CONTINUOUS_MPI_OPT_DEV_SHARED/BUILD/packages/muelu/src/MueLu_Utilities.hpp:1,
                 from /data/jenkins/slave/workspace/Trilinos_continuous/CONTINUOUS_MPI_OPT_DEV_SHARED/Trilinos/packages/muelu/src/Interface/../MueCentral/MueLu_Level.hpp:68,
                 from /data/jenkins/slave/workspace/Trilinos_continuous/CONTINUOUS_MPI_OPT_DEV_SHARED/Trilinos/packages/muelu/src/Interface/../MueCentral/MueLu_Factory.hpp:65,
                 from /data/jenkins/slave/workspace/Trilinos_continuous/CONTINUOUS_MPI_OPT_DEV_SHARED/Trilinos/packages/muelu/src/Interface/../Smoothers/MueLu_SmootherPrototype_decl.hpp:52,
                 from /data/jenkins/slave/workspace/Trilinos_continuous/CONTINUOUS_MPI_OPT_DEV_SHARED/BUILD/packages/muelu/src/MueLu_SmootherPrototype.hpp:1,
                 from /data/jenkins/slave/workspace/Trilinos_continuous/CONTINUOUS_MPI_OPT_DEV_SHARED/Trilinos/packages/muelu/src/Interface/../Smoothers/MueLu_Ifpack2Smoother_decl.hpp:74,
                 from /data/jenkins/slave/workspace/Trilinos_continuous/CONTINUOUS_MPI_OPT_DEV_SHARED/BUILD/packages/muelu/src/MueLu_Ifpack2Smoother.hpp:1,
                 from /data/jenkins/slave/workspace/Trilinos_continuous/CONTINUOUS_MPI_OPT_DEV_SHARED/Trilinos/packages/muelu/src/Interface/../Smoothers/MueLu_SmootherCloner.hpp:56,
                 from /data/jenkins/slave/workspace/Trilinos_continuous/CONTINUOUS_MPI_OPT_DEV_SHARED/Trilinos/packages/muelu/src/Interface/../MueCentral/MueLu_Hierarchy_decl.hpp:59,
                 from /data/jenkins/slave/workspace/Trilinos_continuous/CONTINUOUS_MPI_OPT_DEV_SHARED/BUILD/packages/muelu/src/MueLu_Hierarchy.hpp:1,
                 from /data/jenkins/slave/workspace/Trilinos_continuous/CONTINUOUS_MPI_OPT_DEV_SHARED/Trilinos/packages/muelu/src/Interface/../Headers/MueLu.hpp:68,
                 from /data/jenkins/slave/workspace/Trilinos_continuous/CONTINUOUS_MPI_OPT_DEV_SHARED/Trilinos/packages/rol/example/PDE-OPT/poisson-boltzmann/../TOOLS/solver.hpp:68,
                 from /data/jenkins/slave/workspace/Trilinos_continuous/CONTINUOUS_MPI_OPT_DEV_SHARED/Trilinos/packages/rol/example/PDE-OPT/poisson-boltzmann/../TOOLS/pdeconstraint.hpp:54,
                 from /data/jenkins/slave/workspace/Trilinos_continuous/CONTINUOUS_MPI_OPT_DEV_SHARED/Trilinos/packages/rol/example/PDE-OPT/poisson-boltzmann/example_01.cpp:62:
/data/jenkins/slave/workspace/Trilinos_continuous/CONTINUOUS_MPI_OPT_DEV_SHARED/Trilinos/packages/xpetra/src/CrsMatrix/Xpetra_TpetraBlockCrsMatrix.hpp: In instantiation of ‘void Xpetra::TpetraBlockCrsMatrix<Scalar, LocalOrdinal, GlobalOrdinal, Node>::getLocalDiagOffsets(Teuchos::ArrayRCP<long unsigned int>&) const [with Scalar = double; LocalOrdinal = int; GlobalOrdinal = int; Node = Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial>]’:
/data/jenkins/slave/workspace/Trilinos_continuous/CONTINUOUS_MPI_OPT_DEV_SHARED/Trilinos/packages/rol/example/PDE-OPT/poisson-boltzmann/example_01.cpp:180:1:   required from here
/data/jenkins/slave/workspace/Trilinos_continuous/CONTINUOUS_MPI_OPT_DEV_SHARED/Trilinos/packages/xpetra/src/CrsMatrix/Xpetra_TpetraBlockCrsMatrix.hpp:339:7: warning: ‘void Tpetra::Experimental::BlockCrsMatrix<S, LO, GO, N>::getLocalDiagOffsets(Teuchos::ArrayRCP<long unsigned int>&) const [with Scalar = double; LO = int; GO = int; Node = Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial>]’ is deprecated (declared at /data/jenkins/slave/workspace/Trilinos_continuous/CONTINUOUS_MPI_OPT_DEV_SHARED/Trilinos/packages/tpetra/core/src/Tpetra_Experimental_BlockCrsMatrix_decl.hpp:660) [-Wdeprecated-declarations]
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://gcc.gnu.org/bugs.html> for instructions.

**Comment by bartlettroscoe** [comment]
Should the usage of depreciated code not be removed?  That is the purpose for deprecated warnings.  It seems like this is something for ROL and Tpetra developers to come to an agreement on.  Not sure what I an do about this.   If you find this is a defect in TriBITS, please let me know.

**Comment by jhux2** [comment]
I don't see how deprecated warnings can be treated as fatal, since their purpose is to give users enough lead time to stop using the deprecated code.  That being said, we've let this particular warning lag for quite a while, and it is (now officially) on our to-do list.

**Comment by mhoemmen** [comment]
> It seems like this is something for ROL and Tpetra developers to come to an agreement on.

This is just a matter of MueLu folks switching to use the new getLocalDiagOffsets interface in Tpetra.  It doesn't involve ROL.

**Comment by dridzal** [comment]
Just to clarify: My only question is why the 'deprecated' warnings are enabled in our testing framework.  They result in a bunch of clutter on CDash, but are not helpful to developers, who should see them anyway in their local builds.  No developer goes to CDash to educate themselves about deprecated code.  I think that the official test builds should disable such warnings.

**Comment by mhoemmen** [comment]
Deprecated warnings only _break_ warnings-as-errors builds.

**Comment by dridzal** [comment]
Let me clarify again.  Often, when looking for an actual error on CDash, I have to scroll through hundreds if not thousands of lines of deprecated warnings and try to find the first occurrence of an error.  Why can't we disable these warnings?  Also, I'm not sure if enabling deprecated warnings is in the spirit of warning-as-errors builds.  I would reserve these for internal compiler warnings, and disable deprecated warnings.  In summary, deprecated warnings should never be registered in CDash builds.   @bartlettroscoe , what do you think?

**Comment by jhux2** [comment]
> In summary, deprecated warnings should never be registered in CDash builds.

@dridzal I completely agree.

**Comment by bartlettroscoe** [comment]
IMO, at least one CDash build should show deprecated warnings.  Otherwise, if every developer just turns them off locally, then we will never see them (until the bomb goes off when the deprecated code is removed).

But developers should be seeing deprecated warnings in their local builds and fixing them.  If developers are not doing that, then why not?

If people want to turn off deprecated warnings on the Trilinos CDash builds, it is a single option. See:

* https://tribits.org/doc/TribitsBuildReference.html#enabling-disabling-deprecated-warnings

That is not for me to decide.

**Comment by dridzal** [comment]
I would never disable deprecated warnings locally.  That is a bad idea.  Otherwise, I would never catch them -- I don't browse CDash output for such warnings.  I propose that in builds where warnings are not treated as errors, we disable deprecated warnings.  For builds where warning=error, we can make a collective decision.  It may be sufficient to have a single build with deprecated warnings enabled.
  Maybe we should include this in the next meeting's agenda?

**Comment by jwillenbring** [comment]
I think this is worth bringing up at an upcoming leaders meeting. I agree with @bartlettroscoe that the warnings should be on for at least 1 build.

**Comment by dridzal** [comment]
Closing this issue:  We've agreed to discuss deprecated warnings in the context of CDash builds at an upcoming leaders' meeting.
