### ISSUE TITLE
Panzer: commit has increased run time by approx. 2.5x on problem using epetra

### ISSUE THREAD

**Issue by glhenni** [trilinos/Trilinos#9913]
## Bug Report
@trilinos/Panzer

### Description
For the most part the charon team has moved to tpetra but we have a few tests that, due to convergence behavior, still use epetra. Because it's a small set it took a while to notice but @LawrenceCMusson was running a problem for analysts and noticed that the most recent version of charon was considerably slower than an older version he was using. I looked back at our regression testing and this is what I saw:
![charon-test](https://user-images.githubusercontent.com/15944593/140963797-0fc96eef-6e52-4f23-85db-0f829877d471.png)

Notice on or around Aug. 25 a change was made that caused an approximately 2.5x increase in the run time of that test. This is exactly what @LawrenceCMusson noticed in the much larger problem he's running for an analyst. Using `git bisect` I identified the problematic commit as:
```
c2a27a8405d8d01f73662444e2827fb86d50b276 is the first bad commit
commit c2a27a8405d8d01f73662444e2827fb86d50b276
Author: bathmatt <dr.bettencourt@gmail.com>
Date:   Wed Aug 25 18:44:57 2021 -0400
```

What can be done to get our performance back? I suppose I can back out the change. I may try a straight `git revert` locally on the change to see how cleanly that goes but that isn't an acceptable long-term solution, unless panzer developers revert the change in the "live" trilinos/panzer repo.

**Comment by rppawlo** [comment]
That commit really can't be reverted in trilinos proper. It was needed keep the epetra tests running in CUDA builds where UVM is disabled. Even though epetra doesn't know a thing about cuda, the scatter data comes from a kokkos view that is in cuda space if cuda node is enabled. Looks like some of the loops were reordered to allow for allocations of host views and deep copies of the data. I'll see if I can speed this up. We are trying to deprecate the epetra stack so we didn't invest much in preserving performance of this object (and thought charon was completely converted to the tpetra stack). The other alternative is to revert the commit and disable all epetra-based tests in cuda builds. This will cause a loss of coverage of panzer capabilities in cuda testing. Converting the tests form epetra to tpetra is the long term plan that will hopefully happen this FY. Let's talk more tomorrow at the Charon dev meeting.

**Comment by dridzal** [comment]
@rppawlo :  We use both Tpetra and Epetra stacks in the (𝔽𝔼𝕄)³ app.  The Epetra stack is currently the only option for large-scale optimization, because the required Panzer Tpetra block objects are not yet available.  I believe there is an ASC task to implement these ... maybe this performance loss could elevate the block object task in priority?

**Comment by rppawlo** [comment]
@glhenni  - short term, you should be able to revert that commit in the local charon fork. The panzer tests won't pass for no-uvm cuda builds but I don't think that is a high priority for charon at this point?

@dridzal - I can't find an issue on the trilinos jira planning site. Can you point me to the issue? I believe this was getting the Tangent assembly type to work for blocked tpetra gather/scatter? Is that correct?

**Comment by dridzal** [comment]
It's 'Enable support for Tpetra block operators with different domains and ranges', issue 175.  The error we are getting is

`panzer::cloneWithNewRangeAndDomain: Blocked Tpetra LOF does not yet support different range and domain indexers!
`

however it looks like this was re-assigned from Panzer to Tpetra.  I'm not sure where the missing functionality belongs.  I thought this was Panzer.  It's definitely related to optimization infrastructure.
