### ISSUE TITLE
MueLu:  3D Linear Elasticity Example

### ISSUE THREAD

**Issue by Adrian-Diaz** [trilinos/Trilinos#9915]
## Question
@trilinos/\<MueLu\>

Greetings,

Is there an example in the current package repository set up to solve Ax=b, where A results from the FEA discretization of 3D Linear Elasticity, that I could study? Thanks for any help rendered on the matter

Adrian

**Comment by cgcgcg** [comment]
Have a look at the Galeri package. It comes with the Elasticity3D example. The problem can be built directly from some of the MueLu drivers, e.g. `muelu/tests/scaling/MueLu_Driver.exe`.

**Comment by Adrian-Diaz** [comment]
Thanks for the prompt reply. I'll take a look at that.

**Comment by Adrian-Diaz** [comment]
After copying the way they implement the nullspace and coords vectors the solver seems to be working well up to a point. While it works for poisson ratios such as 0.1 for some reason whenever I set Poisson ratios that are too high (the highest I've tried is 0.3 such as for steel) I get the following convergence failure from Belos:

![image](https://user-images.githubusercontent.com/46537160/141554132-3065eca2-17c9-4295-9b51-701aa4e0fdd8.png)

Any idea how to resolve this?

**Comment by cgcgcg** [comment]
This is a failure in CG. I have seen this before when either the matrix or the preconditioner is singular, or has a negative eigenvalue.

**Comment by Adrian-Diaz** [comment]
That's strange, the system in question should always have a non-singular solution. It definitely works with a direct solver. At first when using the "simple" parameter the solver would fail for my initial Topology optimization iteration (where it was all just homogeneous material at a certain poisson ratio). Afterwards I applied the  "Elasticity3D" parameter file with number of equations set to 1 or 3 and it works for several iterations of the TO problem before giving me the same error.
[simple.txt](https://github.com/trilinos/Trilinos/files/7540033/simple.txt)
[Elasticity3D.txt](https://github.com/trilinos/Trilinos/files/7540035/Elasticity3D.txt)

**Comment by cgcgcg** [comment]
You could try using a different smoother, e.g. Gauss-Seidel. TBH, I don't know if you need to adjust things like the Chebyshev eigenvalue ration wrt Poisson ratio.

**Comment by dridzal** [comment]
@Adrian-Diaz , I have seen this error in several contexts, including linear elasticity and the curl-curl equations of electromagnetics.  In the context of linear elasticity, we were doing topology optimization and the filter we used ("Helmholtz filter") was making some densities negative.  So, just to be sure, do you get this error in the simple context of solving the 'forward' elasticity equations (no optimization, no filter)?  If so, then this would be a great reproducer to have, especially if the problem size isn't too large.  I believe you can dump the matrices in a format suitable for analysis in Matlab, where you could easily compute the spectrum.  @cgcgcg , is the matrix output capability available in this case?

**Comment by cgcgcg** [comment]
We can dump matrices at the end of the multigrid setup call, so that should work here.

**Comment by Adrian-Diaz** [comment]
The case with the relaxation smoothening in the "simple" parameter setup was throwing up the convergence error for the default beam with solid material (so far tested with 10k nodes as smallest system). The Chebyshev smoothening in the other param file was able to solve the initial block and for several iterations. Its possible the preconditioning step is having trouble with my epsilon density of 10^-4 through the TO iterations in that case. Do I output the preconditioner with the H->Write I see in the driver?

**Comment by cgcgcg** [comment]
You can add
```
<ParameterList name="export data">
<Paramter name="A" type="string" value="{0}"/>
</ParameterList>
```
to your input XML file. That should write out the matrix as `A0.mtx`

**Comment by dridzal** [comment]
In the "simple" case with the solid material, you're just using the Jacobi smoother.  My guess is that this should not give you an indefinite preconditioner.  This may point to a bug somewhere.  In the second case, with optimization, I would inspect the material properties _right before_ the system is reassembled.

**Comment by Adrian-Diaz** [comment]
[Matrix_output.zip](https://github.com/trilinos/Trilinos/files/7541424/Matrix_output.zip)
So far this matrix with 10k nodes is the smallest failing case I've found when using poisson = 0.3 and the jacobi smoother. It solves with the direct solver or Chebyshev smoothing. Also so far the entire TO process works if I set poisson = 0. I'll try a few more meshing cases that are smaller to see if that can simplify the output size.

**Comment by cgcgcg** [comment]
@Adrian-Diaz What damping are you using when running with Jacobi? Have you computed the spectrum of your operator?

**Comment by Adrian-Diaz** [comment]
The damping in the file is set to 0.8. Is there a command to compute the spectrum that way?

**Comment by cgcgcg** [comment]
It's a small matrix, I'd use SciPy..

**Comment by cgcgcg** [comment]
NVM, try setting the damping to 0.3. Does that fix things?

**Comment by Adrian-Diaz** [comment]
Yea setting it to 0.3 lets it solve.

**Comment by cgcgcg** [comment]
Ok, that makes sense. I find a spectral radius of D^-1 A of 0.309. Before, when the damping was 0.8, the preconditioner was indefinite.

**Comment by Adrian-Diaz** [comment]
So is the Jacobi smoothening more robust as long as the damping constant is lower than that condition?

**Comment by Adrian-Diaz** [comment]
Seems like Jacobi is working now for all the TO iterations. I do want to figure out the chebyshev parameters though since that one seems considerably faster, any ideas with that? I tried lowering and raising the "ratio eigenvalue" parameter for that but it still failed through the TO process. Is there a set of conditions for that related to the spectral radius?
![image](https://user-images.githubusercontent.com/46537160/141934658-b5dcbda2-c735-4748-866a-86240b2b85ff.png)

**Comment by cgcgcg** [comment]
In the "smoother: params", try setting
```
<Parameter name="chebyshev: eigenvalue max iterations" type="int" value="100"/>
```
This will definitely slow down the preconditioner setup, but helps in cases where we struggle to find a good estimate for the upper bound of the spectrum. If that doesn't work, try increasing the ratio to 50.

**Comment by Adrian-Diaz** [comment]
Seems like increasing max iterations to 100 did the trick. Gauss Siedel is also working with the 0.3 damping constant.

**Comment by cgcgcg** [comment]
@Adrian-Diaz Can we close this issue, or are there outstanding problems?

**Comment by Adrian-Diaz** [comment]
Things seem fine so far. Closing.
