### ISSUE TITLE
Framework: Autotester broken?

### ISSUE THREAD

**Issue by cgcgcg** [trilinos/Trilinos#9916]
## Bug Report
@trilinos/framework 

### Description
As far as I can tell, the autotester has not run at all in the last day. There are PRs that are ready for testing, e.g. #9914.

**Comment by jwillenbring** [comment]
@cgcgcg Thanks for bringing this to our attention. I can see something is badly broken. We will report back when we know more.

**Comment by jwillenbring** [comment]
@cgcgcg we have identified the likely issue. When the authentication service comes back online, we will evaluate if the issue is resolved, or if we need to look at rebooting the cloud resources.

**Comment by jhux2** [comment]
@jwillenbring This is a somewhat separate question, but there are 14 PR's open for merge-to-master.   I was wondering if there was duplication, so I looked at the oldest and newest (#9804 and #9906), and see the same commits in both.  Does 9906 include 9804, or is that just an artifact of how github displays the information?

**Comment by jhux2** [comment]
@william76 closed all but one of the Merge-to-master PRs.  Thanks, @william76!

**Comment by GrahamBenHarper** [comment]
Tagging #3276 for posterity...

Any updates @jwillenbring?
