### ISSUE TITLE
trilinos: release fine tuning

### ISSUE THREAD

**Issue by MarDiehl** [trilinos/Trilinos#9921]
## Enhancement
I have two small suggestions for the release:
* would it be possible to offer a lite version of the tarball (just code, no examples etc)?
* the name of the tarball (`trilinos-release-13-2-0.tar.gz`) and the folder therein (`Trilinos-trilinos-release-13-2-0`) is different and follows no commonly used scheme. Would it be possible to unify to `trilinos-13.2.0`/`trilinos-13.2.0.tar.gz`?

**Comment by cgcgcg** [comment]
@trilinos/framework
