### ISSUE TITLE
Thyra:  How to pre and postprocess linear equation system in the framework using a preconditioner

### ISSUE THREAD

**Issue by kaiserls** [trilinos/Trilinos#9922]
## Question
@trilinos/\<Thyra\>
@searhein 

### What are you trying to accomplish?
I am trying to adapt a linear equation system Ax=b before solving the system with the Thyra/Stratimikos framework. The information/routines needed to adapt the system are however contained in the preconditioner which is hidden in the solver.
At the moment the preconditioner is constructed by the solver which in turn is constructed by Thyra::LinearOpWithSolveFactoryBase which again is constructed by the Stratimikos::DefaultLinearSolverBuilder.

### My current approach

* I added a getter to the belos source code: `BelosLinearOpWithSolve<Scalar>::getPreparePreconditioner()`

```C++
RCP<LinearOpWithSolveFactoryBase<SC>> lowsFactory=linearSolverBuilder.createLinearSolveStrategy("");
RCP<LinearOpWithSolveBase<SC> > lows=linearOpWithSolve(*lowsFactory, K_thyra);
//Thyra to BelosOp
auto belosLinearOpWithSolve = rcp_dynamic_cast<Thyra::BelosLinearOpWithSolve<SC>,LinearOpWithSolveBase<SC>>(lows, true);
//get belos op preconditioner
auto precNonConst = rcp_const_cast<LinearOpBase<SC>>(belosLinearOpWithSolve->getPreparePreconditioner());
//BelosOp to FROSch Operator
auto froschLinearOp = rcp_dynamic_cast<Thyra::FROSchLinearOp<SC, LO, GO,NO>,LinearOpBase<SC>>(precNonConst, true);
// Preconditioner is called from FROSch Operator
froschLinearOp->preSolve(thyraB.ptr());
SolveStatus<double> status = solve<double>(*lows, Thyra::NOTRANS, *thyraB, thyraX.ptr());
froschLinearOp->afterSolve(thyraX.ptr());
```

### What answers do you need?
Does someone have an idea how this could be accomplished more elegantly and user friendly while still using the Thyra/Stratimikos framework?

**Comment by cgcgcg** [comment]
This is what we're doing in a MueLu example:
https://github.com/trilinos/Trilinos/blob/5a67b70fb3816e1cea26554c650b4dc7ca26747d/packages/muelu/example/basic/Stratimikos.cpp#L234-L251
Is that what you need?

**Comment by kaiserls** [comment]
Thank your very much for the fast answer. This is indeed a great step forward in comparison with my approach.
Do you see any possibility to hide this behavior in a customLinearOpWithSolveFactory and customLinearOperatorWithSolve interface which is passed to the linearSolverBuilder? I failed to find a solution which doesn't bring the need to propagate a new interface, let's call it "linearOpWithSolveAndProjection' through the full thyra framework.

**Comment by cgcgcg** [comment]
I'm not sure I understand what you need. You can get the preconditioner, and cast it to a FROSch operator. Is the question now if it is possible to do the pre/post steps in the solve call?

**Comment by kaiserls** [comment]
>  Is the question now if it is possible to do the pre/post steps in the solve call?
Exactly.

**Comment by cgcgcg** [comment]
No, I don't think so. I guess you have to define your own Stratimikos solver for that. There might be a way to do it using Teko and define it as a product. Also, some of the Belos solvers have an option to define a nullspace that needs to be projected out, in case that's what you're doing.

**Comment by searhein** [comment]
@cgcgcg Thank you for your help and suggestions. This already helps us a lot to get started.
Ultimately, @kaiserls and I were hoping for a non-intrusive solution, i.e., some option that could be easily changed within the parameter list, of course, without re-coding all the Stratimikos solver interfaces. Somehow, it would be nice to have the option of performing pre and post processing steps for any linear equation system. But I understand if this is currently not possible.
