### ISSUE TITLE
[Best Practice] Compiling on Windows, with fortran enabled

### ISSUE THREAD

**Issue by nrsharan** [trilinos/Trilinos#9936]
## Question

I am trying to install the below mentioned packages to work on windows. What is the best toolchain to use? 
I currently have MSVS 2019 and Intel oneAPI (C/C++, Fortran compilers) installed. I presume using MSVS will prevent me from enabling Fortran, is this the case? 

I tried using the Cmake GUI configured with Intel compilers and Ninja, but enabling Fortran throws the following error when performing the Fortran compiler check.

```
/out:VerifyFortran.lib 
    CMakeFiles/VerifyFortran.dir/VerifyFortran.f.obj 
    [8/8] Linking CXX executable VerifyFortranC.exe
    FAILED: VerifyFortranC.exe 
    cmd.exe /C "cd . && C:\PROGRA~2\Intel\oneAPI\compiler\latest\windows\bin\CLANG_~1.EXE -fuse-ld=lld-link -nostartfiles -nostdlib -O3 -DNDEBUG -D_DLL -D_MT -Xclang --dependent-lib=msvcrt /subsystem:console CMakeFiles/VerifyFortranC.dir/main.c.obj CMakeFiles/VerifyFortranC.dir/VerifyC.c.obj CMakeFiles/VerifyFortranC.dir/VerifyCXX.cxx.obj -o VerifyFortranC.exe -Xlinker /implib:VerifyFortranC.lib -Xlinker /pdb:VerifyFortranC.pdb -Xlinker /version:0.0   VerifyFortran.lib  -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32 -loldnames && cd ."
    clang++: error: no such file or directory: '/subsystem:console'
```

Also, I need to work with MPI. Keeping all of this in mind, please let me know what is the best option. I am at the brink of giving up and installing Linux/getting a mac. 

Please help! 
Thanks and stay safe!

Required Packages: 
```
Amesos
Amesos2
AztecOO
Belos
Epetra
EpetraExt
Galeri
Ifpack
Ifpack2
Kokkos
ShyLU
Stratimikos
Teko
Teuchos
Thyra
Tpetra
Xpetra
Zoltan
Zoltan2
```

**Comment by jhux2** [comment]
@nrsharan I suggest that you search the github issues for advice that Windows users have posted.  As far as I know, there are no nightly tests to cover Windows builds on the Trilinos dashboard.
