### ISSUE TITLE
Trilinos:  Why isn't OpenMP appended to Trilinos_TPL_LIBRARIES even if Trilinos is built with OpenMP?

### ISSUE THREAD

**Issue by humhang** [trilinos/Trilinos#9940]
## Question
@trilinos

My code uses Epetra and AztecOO. Recently I tried to compile my code in a system with Trilinos pre-installed, and I got a linking error because OpenMP was not linked against. 

My code itself does not use OpenMP, so I didn't include OpenMP explicitly in its CMakeLists.txt. 

I think it is because Trilinos was compiled with OpenMP. In this scenarios, why isn't OpenMP appended to Trilinos_TPL_LIBRARIES or set as an interface library of Trilinos in CMake?

Is there any clean workaround for this problem without linking OpenMP explicitly in CMakeLists.txt of my code?

**Comment by cgcgcg** [comment]
Are building like in this example?
https://github.com/trilinos/Trilinos/tree/master/demos/simpleBuildAgainstTrilinos

I don't think we consider OpenMP as a TPL, so maybe the link flag for OpenMP gets appended to one of the other variables?

**Comment by humhang** [comment]
> Are building like in this example? https://github.com/trilinos/Trilinos/tree/master/demos/simpleBuildAgainstTrilinos
> 
> I don't think we consider OpenMP as a TPL, so maybe the link flag for OpenMP gets appended to one of the other variables?

Yes, I would be able to compile this example. It seems that -fopenmp is appended to Trilinos_CXX_COMPILER_FLAGS altogether with optimizations flags like -march=core-avx2 -O3, etc, and this example uses Trilinos_CXX_COMPILER_FLAGS as compiler flags.

**Comment by cgcgcg** [comment]
So this solves your issue then, correct? We can close?

**Comment by cgcgcg** [comment]
Seems to be resolved.
