### ISSUE TITLE
MueLu: "use kokkos refactor" requirement for kokkos openmp/cuda build

### ISSUE THREAD

**Issue by jewatkins** [trilinos/Trilinos#9943]
## Question
@trilinos/muelu 

For MueLu, is the input parameter "use kokkos refactor" a requirement for kokkos openmp/cuda builds? If it is, is there reason it's a runtime parameter rather then a build time parameter? Is the functionality the same with/without?

@mperego recently added a test in Albany that uses muelu and it's currently failing openmp/cuda nightly builds:
```
p=0: *** Caught standard std::exception of type 'Teuchos::bad_any_cast' :

 /nightlyAlbanyTests/Results/Trilinos/packages/muelu/src/MueCentral/MueLu_VariableContainer.hpp:101:
 
 Throw number = 1
 
 Throw test that evaluated to true: data_->type() != typeid(T)
 
 Error, cast to type Data<Teuchos::RCP<MueLu::GraphBase<int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP, Kokkos::HostSpace> > >> failed since the actual underlying type is 'Teuchos::RCP<MueLu::LWGraph_kokkos<int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP, Kokkos::HostSpace> > >!
```
If the functionality is the same, it probably makes sense just to add "use kokkos refactor" to the input file. But if it's not, then maybe it's best to disable the test for openmp/cuda builds and add a new test for the other platforms.

**Comment by cgcgcg** [comment]
We have legacy and kokkos-enabled factories. "use kokkos refactor" switches the default between for any factory that is not explicitly named in the input deck. You can run on OpenMP/CUDA with "use kokkos refactor"=false, but that obviously doesn't take advantage of any on-node parallelism. In your test, I am assuming you were using the extended input deck?

**Comment by jewatkins** [comment]
Yes, and nothing explicitly uses the kokkos factories: https://github.com/sandialabs/Albany/blob/master/tests/small/LandIce/FO_GIS/input_fo_humboldt_muelu.yaml#L474

I think what you mentioned is fine for now. We still need more work on the full on-node parallelism path for muelu (mainly replacing the block smoother). I'll try adding `use kokkos refactor: false`.

**Comment by cgcgcg** [comment]
Yep, we set the default value of "use kokkos refactor"=true on OpenMP/CUDA. If some factory is needed and not found in the input deck, it will be picked as a Kokkos factory, unless you explicitly set "use kokkos refactor"=false.

**Comment by cgcgcg** [comment]
@jewatkins Can we close this, or is there something that needs fixing?

**Comment by jewatkins** [comment]
This is fixed and the functionality makes sense, thanks!
