### ISSUE TITLE
MueLu: CoalesceDropFactory vs CoalesceDropFactory_kokkos

### ISSUE THREAD

**Issue by mperrinel** [trilinos/Trilinos#9957]
## Bug Report
@trilinos/@muelu:CoalesceDropFactory.cpp>

### Description
CoalesceDropFactory has a parameter "aggregation: greedy Dirichlet" but that is not the case for CoalesceDropFactory_kokkos. 
For the kokkos version, we need to use the "aggregation: preserve Dirichlet points" parameter of UncoupledAggregationFactory_kokkos.

**Comment by jhux2** [comment]
@pohm01

**Comment by pohm01** [comment]
I'm not sure I fully understand. The parameter "aggregation: greedy Dirichlet" and "aggregation: preserve Dirichlet points" do different things. The "aggregation: preserve Dirichlet points" dictates how Dirichlet points are treated for aggregation, where as "aggregation: greedy Dirichlet" is for which nodes are to be considered Dirichlet.

I can look into adding an "aggregation: greedy Dirichlet" option for CoalesceDropFactory_kokkos if that is what we need.

**Comment by jhux2** [comment]
@pohm01 I think @mperrinel is asking whether it's possible to get the option `aggregation: greedy Dirichlet` option for CoalesceDropFactory_kokkos.
