### ISSUE TITLE
Kokkos:  Compile Error

### ISSUE THREAD

**Issue by Adrian-Diaz** [trilinos/Trilinos#9963]
## Question
@trilinos/\<kokkos\>

Greetings,
[cmake_configure_superlu_parallel.txt](https://github.com/trilinos/Trilinos/files/7582703/cmake_configure_superlu_parallel.txt)

Lately I tried compiling Trilinos from scratch and for some reason I started getting this error when using the attached cmake configure and make -j4 install:

![image](https://user-images.githubusercontent.com/46537160/142897610-34ceda70-b0f1-4f62-9161-e6534f5145d0.png)

Any ideas how to resolve that?

Adrian

**Comment by cgcgcg** [comment]
It might be quicker to open an issue on https://github.com/kokkos/kokkos.

**Comment by Adrian-Diaz** [comment]
Seems like reinstalling my compiler and libs avoided this.
