### ISSUE TITLE
Nalu configure issues due to Kokkos or SEACAS?

### ISSUE THREAD

**Issue by spdomin** [trilinos/Trilinos#9973]
## Bug Report
@trilinos/kokkos

This looks new:

find: './CMakeFiles': No such file or directory
   Trilinos_DIR = /home/spdomin/gitHubWork/scratch_build/install/gcc8.4.0/Trilinos_nightly_release
-- Enabled Kokkos devices: SERIAL
CMake Warning at /home/spdomin/gitHubWork/scratch_build/install/gcc8.4.0/Trilinos_nightly_release/lib/cmake/Kokkos/KokkosConfig.cmake:176 (MESSAGE):
  The installed Kokkos configuration does not support CXX extensions.
  Forcing -DCMAKE_CXX_EXTENSIONS=Off

but it set Trilinos_FOUND to FALSE so package "Trilinos" is considered to
  be NOT FOUND.  Reason given by package:

  The following imported targets are referenced, but are missing:
  SEACASChaco::chaco SEACASSuplibC::suplib_c SEACASSuplibCpp::suplib_cpp

### Description
Bad config on the apps side - looks like SEACAS? @gdsjaar 

### Steps to Reproduce
Good:

NaluCFD/Nalu SHA1: c164464e0cd6e320cb5d30480fed49675cbee457
Trilinos/develop SHA1: 110b6c45b825a632d4a872ca168a6019ae140328

Bad:

NaluCFD/Nalu SHA1: c164464e0cd6e320cb5d30480fed49675cbee457
Trilinos/develop SHA1: acb9fc47ff2d55412e45974b5195d743cf2bf7ad

**Comment by spdomin** [comment]
@alanw0 - does this look familiar to you?

@wjhorne - could you try a bisect (assuming Greg or Alan don't know what happened here).

**Comment by gsjaardema** [comment]
I don't know what would cause this.  I do know that @bartlettroscoe has been doing some CMake modifications to modernize or use more CMake features.  Not sure if this is related to that...

**Comment by alanw0** [comment]
> @alanw0 - does this look familiar to you?
> 
> @wjhorne - could you try a bisect (assuming Greg or Alan don't know what happened here).

I'm not sure what this could be, but Irina Tezaur lodged a ticket also, so something happened. I'll figure out when the last stk update was and which files were touched.

**Comment by spdomin** [comment]
Good to know. We are using:

cmake version 3.17.0

I don't think that Irina's ticket is related, however, something definitely changed before the min-break.

**Comment by alanw0** [comment]
As far as I can tell the last stk change in trilinos was Nov 5: https://github.com/trilinos/Trilinos/pull/9896

**Comment by bartlettroscoe** [comment]
This may be related to the merge of PR #9894.  That PR should maintain 100% backward compatibility but there may be some use cases that have not been addressed and some of the custom `FindTPL<tplName>.cmake` files may need to be tweaked as per:

* https://tribits.org/doc/TribitsUsersGuide.html#how-to-use-find-package-for-a-tribits-tpl

@spdomin, how can I reproduce these configure errors?  You can contact me offline if it is too sensitive for GitHub Issues.

**Comment by bartlettroscoe** [comment]
FYI: I posted the revert of PR #9894 in the new PR #9977.  I just need someone to approve that PR so that it can merge.  Hopefully the PR can pass testing fast and merge (but I don't have any control over that).

**Comment by spdomin** [comment]
Nalu's nightly build and test process is now clean.

@bartlettroscoe, Thank you for the revert. If you have something to test, let me know and I can clone your forked version of Trilinos with your desired changes.

**Comment by bartlettroscoe** [comment]
> If you have something to test, let me know and I can clone your forked version of Trilinos with your desired changes.

@spdomin, Thanks, I will get back to you as part of development and testing of PR #9978.

**Comment by bartlettroscoe** [comment]
FYI: I have reproduced the bug with a native TriBITS test and this is the same bug impacting #9972.  This happens when `-DTrilinos_ENABLE_ALL_OPTIONAL_PACKAGES=OFF` and subpackages get enabled by not the parent package, in this case, `SEACAS` (and with Albany, STK). You can see these options from [do-configTrilinos_release](https://github.com/NaluCFD/Nalu/blob/master/build/do-configTrilinos_release) showing:

```
...
-DTrilinos_ENABLE_ALL_OPTIONAL_PACKAGES=OFF \
...
-DTrilinos_ENABLE_SEACASExodus:BOOL=ON \
-DTrilinos_ENABLE_SEACASEpu:BOOL=ON \
-DTrilinos_ENABLE_SEACASExodiff:BOOL=ON \
-DTrilinos_ENABLE_SEACASNemspread:BOOL=ON \
-DTrilinos_ENABLE_SEACASNemslice:BOOL=ON \
-DTrilinos_ENABLE_SEACASIoss:BOOL=ON \
...
```

**Comment by bartlettroscoe** [comment]
I would like to be able to do a reference build of Trilinos and Nalu and then test out updates of Trilinos against Nalu like for PR #9978 but what I (and other Trilinos developers) really need a dirt-simple, zero-chance-for-errors process as follows:

This should be just a few commands like for Trilinos that looks something like:

```
$ mkdir  <tril-build-dir>/
$ cd <tril-build-dir>/
$ source <env-load-script>
$ env TRILINOS_SRC_DIR=<tril-src-dir> \
    <trilinos-configure-script> -DTrilinos_ENABLE_TESTS=ON -DCMAKE_INSTALL_PREFIX=${PWD}/install
$ make -j12
$ ctest -j12
$ make -j12 install
```

and then configure and build Nalu against that Trilinos install like:

```
$ mkdir <nalu-build- dir>/
$ cd <nalu-build- dir>/
$ env NALU_SRC_DIR=<nalu-src-dir> \
    <nalu-configure-script> -DCMAKE_PREFIX_PATH=<tril-build-dir>/install
$ make -j12
$ ctest -j12
```

For standard systems at SNL, it should be about that simple.    I can give examples of this for SPARC and EMPIRE.
