### ISSUE TITLE
Trilinos: Cmake Error

### ISSUE THREAD

**Issue by slavakung** [trilinos/Trilinos#9975]
Apologies if this has been answered somewhere, I have looked.

I tried performing the standard initial cmake, after updating to the current version, by calling:

cmake \
-DCMAKE_C_COMPILER=/usr/bin/cmake \
-DCMAKE_CXX_COMPILER=/usr/bin/cmake \
-DCMAKE_Fortran_COMPILER=/usr/bin/gfortran \
-DTrilinos_ENABLE_ALL_PACKAGES=ON \
-DCMAKE_INSTALL_PREFIX=Trilexec \
Documents/Trilinos/Trilinos-master

and I get the following error:

CMake Error at /usr/share/cmake-3.22/Modules/CMakeTestCCompiler.cmake:69 (message):
  The C compiler

    "/usr/bin/cmake"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /home/slava/CMakeFiles/CMakeTmp
    
    Run Build Command(s):/usr/bin/make -f Makefile cmTC_9d5c8/fast && /usr/bin/make  -f CMakeFiles/cmTC_9d5c8.dir/build.make CMakeFiles/cmTC_9d5c8.dir/build
    make[1]: Entering directory '/home/slava/CMakeFiles/CMakeTmp'
    Building C object CMakeFiles/cmTC_9d5c8.dir/testCCompiler.c.o
    /usr/bin/cmake    -o CMakeFiles/cmTC_9d5c8.dir/testCCompiler.c.o -c /home/slava/CMakeFiles/CMakeTmp/testCCompiler.c
    CMake Error: Unknown argument -c
    CMake Error: Run 'cmake --help' for all supported options.
    make[1]: *** [CMakeFiles/cmTC_9d5c8.dir/build.make:78: CMakeFiles/cmTC_9d5c8.dir/testCCompiler.c.o] Error 1
    make[1]: Leaving directory '/home/slava/CMakeFiles/CMakeTmp'
    make: *** [Makefile:127: cmTC_9d5c8/fast] Error 2
    
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  cmake/tribits/core/package_arch/TribitsGlobalMacros.cmake:1674 (enable_language)
  cmake/tribits/core/package_arch/TribitsProjectImpl.cmake:182 (tribits_setup_env)
  cmake/tribits/core/package_arch/TribitsProject.cmake:93 (tribits_project_impl)
  CMakeLists.txt:109 (TRIBITS_PROJECT)

**Comment by cgcgcg** [comment]
That's because CMake isn't a compiler. It obviously depends on your system, but if you have the GNU compilers, you can set `gcc` and `g++`. Or you skip these lines
```
-DCMAKE_C_COMPILER=/usr/bin/cmake
-DCMAKE_CXX_COMPILER=/usr/bin/cmake 
```
CMake might be able to autodetect your compilers.
